Prusa Slicer: Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow Class Reference
Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow Class Reference
Classes
struct Alignment
struct State
Public Member Functions
RotoptimzeWindow (ImGuiWrapper *imgui, State &state, const Alignment &bottom_limit)
~RotoptimzeWindow ()
RotoptimzeWindow (const RotoptimzeWindow &)=delete
RotoptimzeWindow (RotoptimzeWindow &&)=delete
RotoptimzeWindow & operator= (const RotoptimzeWindow &)=delete
RotoptimzeWindow & operator= (RotoptimzeWindow &&)=delete
Private Attributes
ImGuiWrapper * m_imgui = nullptr
Detailed Description
Class Documentation
Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::Alignment
struct Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::Alignment
Class Members
float bottom_limit
float x
float y
Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::State
struct Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::State
Class Members
float accuracy = 1.f
int method_id = 0
Constructor & Destructor Documentation
RotoptimzeWindow() [1/3]
Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow (ImGuiWrapper * imgui, State & state, const Alignment & bottom_limit)
    : m_imgui{imgui}
{
    imgui->begin(_L("Optimize orientation"), ImGuiWindowFlags_NoMove |
                                     ImGuiWindowFlags_AlwaysAutoResize |
                                     ImGuiWindowFlags_NoCollapse);
    // adjust window position to avoid overlap the view toolbar
    float win_h = ImGui::GetWindowHeight();
    float x = alignment.x, y = alignment.y;
    y = std::min(y, alignment.bottom_limit - win_h);
    ImGui::SetWindowPos(ImVec2(x, y), ImGuiCond_Always);
    float max_text_w = 0.;
    auto padding = ImGui::GetStyle().FramePadding;
    padding.x *= 2.f;
    padding.y *= 2.f;
    for (size_t i = 0; i < RotoptimizeJob::get_methods_count(); ++i) {
        float w =
            ImGui::CalcTextSize(RotoptimizeJob::get_method_name(i).c_str()).x +
            padding.x + ImGui::GetFrameHeight();
        max_text_w = std::max(w, max_text_w);
    }
    ImGui::PushItemWidth(max_text_w);
    if (ImGui::BeginCombo("", RotoptimizeJob::get_method_name(state.method_id).c_str())) {
        for (size_t i = 0; i < RotoptimizeJob::get_methods_count(); ++i) {
            if (ImGui::Selectable(RotoptimizeJob::get_method_name(i).c_str())) {
                state.method_id = i;
                wxGetApp().app_config->set("sla_auto_rotate",
                                           "method_id",
                                           std::to_string(state.method_id));
            }
            if (ImGui::IsItemHovered())
                ImGui::SetTooltip("%s", RotoptimizeJob::get_method_description(i).c_str());
        }
        ImGui::EndCombo();
    }
    ImVec2 sz = ImGui::GetItemRectSize();
    if (ImGui::IsItemHovered())
        ImGui::SetTooltip("%s", RotoptimizeJob::get_method_description(state.method_id).c_str());
    ImGui::Separator();
    auto btn_txt = _L("Apply");
    auto btn_txt_sz = ImGui::CalcTextSize(btn_txt.c_str());
    ImVec2 button_sz = {btn_txt_sz.x + padding.x, btn_txt_sz.y + padding.y};
    ImGui::SetCursorPosX(padding.x + sz.x - button_sz.x);
    if (!wxGetApp().plater()->get_ui_job_worker().is_idle())
        imgui->disabled_begin(true);
    if ( imgui->button(btn_txt) ) {
        replace_job(wxGetApp().plater()->get_ui_job_worker(),
                    std::make_unique<RotoptimizeJob>());
    }
    imgui->disabled_end();
}
References _L, Slic3r::GUI::ImGuiWrapper::begin(), ImGui::BeginCombo(), Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::Alignment::bottom_limit, Slic3r::GUI::ImGuiWrapper::button(), ImGui::CalcTextSize(), Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), ImGui::EndCombo(), ImGuiStyle::FramePadding, Slic3r::GUI::RotoptimizeJob::get_method_description(), Slic3r::GUI::RotoptimizeJob::get_method_name(), Slic3r::GUI::RotoptimizeJob::get_methods_count(), ImGui::GetFrameHeight(), ImGui::GetItemRectSize(), ImGui::GetStyle(), ImGui::GetWindowHeight(), ImGuiCond_Always, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGui::IsItemHovered(), Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::State::method_id, Slic3r::GUI::plater(), ImGui::PushItemWidth(), Slic3r::GUI::replace_job(), ImGui::Selectable(), ImGui::Separator(), ImGui::SetCursorPosX(), ImGui::SetTooltip(), ImGui::SetWindowPos(), ImVec2::x, Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::Alignment::x, and Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::Alignment::y.
~RotoptimzeWindow()
Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow ()
{
    m_imgui->end();
}
References Slic3r::GUI::ImGuiWrapper::end(), and Slic3r::GUI::GLGizmoBase::m_imgui.
RotoptimzeWindow() [2/3]
Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow (const RotoptimzeWindow &) delete
RotoptimzeWindow() [3/3]
Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow (RotoptimzeWindow &&) delete
Member Function Documentation
operator=() [1/2]
RotoptimzeWindow & Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::operator= (const RotoptimzeWindow &) delete
operator=() [2/2]
RotoptimzeWindow & Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::operator= (RotoptimzeWindow &&) delete
Member Data Documentation
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::m_imgui = nullptr private
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoRotate.hpp
src/slic3r/GUI/Gizmos/GLGizmoRotate.cpp