Prusa Slicer: src/libigl/igl/mat_to_quat.cpp File Reference
mat_to_quat.cpp File Reference
#include "mat_to_quat.h"
#include <cmath>
Functions
template<typename Q_type >
static Q_type ReciprocalSqrt (const Q_type x)
Function Documentation
ReciprocalSqrt()
template<typename Q_type > static Q_type ReciprocalSqrt (const Q_type x) inline static
{
  return 1.0/sqrt(x);
}
References sqrt().
Referenced by igl::mat3_to_quat(), and igl::mat4_to_quat().