Prusa Slicer: Slic3r::Search::SearchListModel Class Reference
Slic3r::Search::SearchListModel Class Reference
#include <src/slic3r/GUI/Search.hpp>
Public Types
enum { colIcon , colMarkedText , colMax }
Public Member Functions
SearchListModel (wxWindow *parent)
void Clear ()
void Prepend (const std::string &text)
void sys_color_changed ()
unsigned int GetColumnCount () const override
wxString GetColumnType (unsigned int col) const override
void GetValueByRow (wxVariant &variant, unsigned int row, unsigned int col) const override
bool GetAttrByRow (unsigned int row, unsigned int col, wxDataViewItemAttr &attr) const override
bool SetValueByRow (const wxVariant &variant, unsigned int row, unsigned int col) override
Private Attributes
std::vector< std::pair< wxString, int > > m_values
ScalableBitmap m_icon [6]
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
colIcon
colMarkedText
colMax
         {
#ifdef __WXMSW__
        colIconMarkedText,
#else
        colIcon,
        colMarkedText,
#endif
        colMax
    };
Constructor & Destructor Documentation
SearchListModel()
Slic3r::Search::SearchListModel::SearchListModel (wxWindow * parent)
                                                 : wxDataViewVirtualListModel(0)
{
    int icon_id = 0;
    for (const std::string& icon : { "cog", "printer", "sla_printer", "spool", "resin", "notification_preferences" })
        m_icon[icon_id++] = ScalableBitmap(parent, icon);
}
References m_icon.
Member Function Documentation
Clear()
void Slic3r::Search::SearchListModel::Clear ()
{
    m_values.clear();
    Reset(0);
}
References m_values.
Referenced by Slic3r::Search::SearchDialog::update_list().
GetAttrByRow()
bool Slic3r::Search::SearchListModel::GetAttrByRow (unsigned int row, unsigned int col, wxDataViewItemAttr & attr) const inline override
{ return true; }
GetColumnCount()
unsigned int Slic3r::Search::SearchListModel::GetColumnCount () const inline override
{ return colMax; }
References colMax.
GetColumnType()
wxString Slic3r::Search::SearchListModel::GetColumnType (unsigned int col) const override
{
#ifdef __WXMSW__
    if (col == colIconMarkedText)
        return "DataViewBitmapText";
#else
    if (col == colIcon)
        return "wxBitmap";
#endif
    return "string";
}
References col(), and colIcon.
GetValueByRow()
void Slic3r::Search::SearchListModel::GetValueByRow (wxVariant & variant, unsigned int row, unsigned int col) const override
{
    switch (col)
    {
#ifdef __WXMSW__
    case colIconMarkedText: {
        const ScalableBitmap& icon = m_icon[m_values[row].second];
        variant << DataViewBitmapText(m_values[row].first, icon.bmp().GetBitmapFor(icon.parent()));
        break;
    }
#else
    case colIcon:
        variant << m_icon[m_values[row].second].bmp().GetBitmapFor(m_icon[m_values[row].second].parent());
        break;
    case colMarkedText:
        variant = m_values[row].first;
        break;
#endif
    case colMax:
        wxFAIL_MSG("invalid column");
    default:
        break;
    }
}
References ScalableBitmap::bmp(), col(), colIcon, colMarkedText, colMax, m_icon, m_values, ScalableBitmap::parent(), and row().
Prepend()
void Slic3r::Search::SearchListModel::Prepend (const std::string & text)
{
    const char icon_c = label.at(0);
    int icon_idx = icon_idxs.at(icon_c);
    wxString str = from_u8(label).Remove(0, 1);
    m_values.emplace_back(str, icon_idx);
    RowPrepended();
}
References Slic3r::Search::icon_idxs, and m_values.
Referenced by Slic3r::Search::SearchDialog::update_list().
SetValueByRow()
bool Slic3r::Search::SearchListModel::SetValueByRow (const wxVariant & variant, unsigned int row, unsigned int col) inline override
{ return false; }
sys_color_changed()
void Slic3r::Search::SearchListModel::sys_color_changed ()
{
    for (ScalableBitmap& bmp : m_icon)
        bmp.sys_color_changed();
}
References m_icon.
Referenced by Slic3r::Search::SearchDialog::on_sys_color_changed().
Member Data Documentation
m_icon
ScalableBitmap Slic3r::Search::SearchListModel::m_icon[6] private
Referenced by SearchListModel(), GetValueByRow(), and sys_color_changed().
m_values
std::vector<std::pair<wxString, int> > Slic3r::Search::SearchListModel::m_values private
Referenced by Clear(), GetValueByRow(), and Prepend().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Search.hpp
src/slic3r/GUI/Search.cpp