Prusa Slicer: Slic3r::GUI::Size Class Reference
Slic3r::GUI::Size Class Reference
#include <src/slic3r/GUI/GLCanvas3D.hpp>
Public Member Functions
Size ()=default
Size (int width, int height, float scale_factor=1.0f)
int get_width () const
void set_width (int width)
int get_height () const
void set_height (int height)
float get_scale_factor () const
void set_scale_factor (float factor)
Private Attributes
int m_width { 0 }
int m_height { 0 }
float m_scale_factor { 1.0f }
Detailed Description
Constructor & Destructor Documentation
Size() [1/2]
Slic3r::GUI::Size::Size () default
Size() [2/2]
Slic3r::GUI::Size::Size (int width, int height, float scale_factor = 1.0f) inline
: m_width(width), m_height(height), m_scale_factor(scale_factor) {}
Member Function Documentation
get_height()
int Slic3r::GUI::Size::get_height () const inline
{ return m_height; }
References m_height.
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::GLCanvas3D::_refresh_if_shown_on_screen(), Slic3r::GUI::GLCanvas3D::_render_collapse_toolbar(), Slic3r::GUI::GLCanvas3D::_render_main_toolbar(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_legacy(), Slic3r::GUI::GLCanvas3D::_render_undoredo_toolbar(), Slic3r::GUI::GLCanvas3D::_render_view_toolbar(), priv::calc_fine_position(), Slic3r::GUI::GLToolbar::contains_mouse_horizontal(), Slic3r::GUI::GLToolbar::contains_mouse_vertical(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLCanvas3D::LayersEditing::get_bar_rect_screen(), Slic3r::GUI::GLGizmosManager::get_gizmo_from_mouse(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLToolbarItem::render(), Slic3r::GUI::GLCanvas3D::Tooltip::render(), Slic3r::GUI::NotificationManager::PopNotification::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::GLGizmosManager::render_arrow(), Slic3r::GUI::GLToolbar::render_arrow(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLToolbar::render_horizontal(), Slic3r::GUI::GCodeViewer::render_legend(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_overlay(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::GLToolbar::render_vertical(), Slic3r::GUI::GLToolbar::update_hover_state_horizontal(), and Slic3r::GUI::GLToolbar::update_hover_state_vertical().
get_scale_factor()
float Slic3r::GUI::Size::get_scale_factor () const inline
{ return m_scale_factor; }
References m_scale_factor.
Referenced by Slic3r::GUI::GLCanvas3D::LayersEditing::thickness_bar_width().
get_width()
int Slic3r::GUI::Size::get_width () const inline
{ return m_width; }
References m_width.
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::GLCanvas3D::_refresh_if_shown_on_screen(), Slic3r::GUI::GLCanvas3D::_render_collapse_toolbar(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_legacy(), Slic3r::GUI::GLCanvas3D::_render_view_toolbar(), priv::calc_fine_position(), Slic3r::GUI::GLToolbar::contains_mouse_horizontal(), Slic3r::GUI::GLToolbar::contains_mouse_vertical(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLCanvas3D::LayersEditing::get_bar_rect_screen(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLToolbarItem::render(), Slic3r::GUI::GLCanvas3D::Tooltip::render(), Slic3r::GUI::NotificationManager::PopNotification::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::GLGizmosManager::render_arrow(), Slic3r::GUI::GLToolbar::render_arrow(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLToolbar::render_horizontal(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_overlay(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::GLToolbar::render_vertical(), Slic3r::GUI::GLToolbar::update_hover_state_horizontal(), and Slic3r::GUI::GLToolbar::update_hover_state_vertical().
set_height()
void Slic3r::GUI::Size::set_height (int height) inline
{ m_height = height; }
References m_height.
set_scale_factor()
void Slic3r::GUI::Size::set_scale_factor (float factor) inline
{ m_scale_factor = factor; }
References m_scale_factor.
set_width()
void Slic3r::GUI::Size::set_width (int width) inline
{ m_width = width; }
References m_width.
Member Data Documentation
m_height
int Slic3r::GUI::Size::m_height { 0 } private
Referenced by get_height(), and set_height().
m_scale_factor
float Slic3r::GUI::Size::m_scale_factor { 1.0f } private
Referenced by get_scale_factor(), and set_scale_factor().
m_width
int Slic3r::GUI::Size::m_width { 0 } private
Referenced by get_width(), and set_width().
The documentation for this class was generated from the following file:
src/slic3r/GUI/GLCanvas3D.hpp