Prusa Slicer: Slic3r::GUI::IconManager::Icon Struct Reference
Slic3r::GUI::IconManager::Icon Struct Reference
Data for render texture with icon.
#include <src/slic3r/GUI/IconManager.hpp>
Public Member Functions
bool is_valid () const
Public Attributes
ImVec2 size = ImVec2(-1, -1)
ImVec2 tl
ImVec2 br
unsigned int tex_id = 0
Detailed Description
Data for render texture with icon.
Member Function Documentation
is_valid()
bool Slic3r::GUI::IconManager::Icon::is_valid () const inline
{ return tex_id != 0;}
References tex_id.
Referenced by Slic3r::GUI::draw(), and priv::draw_transparent_icon().
Member Data Documentation
br
ImVec2 Slic3r::GUI::IconManager::Icon::br
Referenced by Slic3r::GUI::draw(), and priv::draw_transparent_icon().
size
ImVec2 Slic3r::GUI::IconManager::Icon::size = ImVec2(-1, -1)
Referenced by Slic3r::GUI::draw(), priv::draw_transparent_icon(), and Slic3r::GUI::IconManager::init().
tex_id
unsigned int Slic3r::GUI::IconManager::Icon::tex_id = 0
Referenced by Slic3r::GUI::draw(), Slic3r::GUI::IconManager::init(), and is_valid().
tl
ImVec2 Slic3r::GUI::IconManager::Icon::tl
Referenced by Slic3r::GUI::draw(), and priv::draw_transparent_icon().
The documentation for this struct was generated from the following file:
src/slic3r/GUI/IconManager.hpp