Prusa Slicer: Slic3r::FillLightning::GroundingLocation Struct Reference
Slic3r::FillLightning::GroundingLocation Struct Reference
#include <src/libslic3r/Fill/Lightning/Layer.hpp>
Public Member Functions
Point p () const
Public Attributes
NodeSPtr tree_node
not null if the gounding location is on a tree
std::optional< Point > boundary_location
in case the gounding location is on the boundary
Detailed Description
Member Function Documentation
p()
Point Slic3r::FillLightning::GroundingLocation::p () const
{
    assert(tree_node || boundary_location);
    return tree_node ? tree_node->getLocation() : *boundary_location;
}
References boundary_location, and tree_node.
Referenced by Slic3r::FillLightning::Layer::attach(), Slic3r::FillLightning::Layer::generateNewTrees(), and Slic3r::FillLightning::Layer::reconnectRoots().
Member Data Documentation
boundary_location
std::optional<Point> Slic3r::FillLightning::GroundingLocation::boundary_location
in case the gounding location is on the boundary
Referenced by Slic3r::FillLightning::Layer::attach(), p(), and Slic3r::FillLightning::Layer::reconnectRoots().
tree_node
NodeSPtr Slic3r::FillLightning::GroundingLocation::tree_node
not null if the gounding location is on a tree
Referenced by Slic3r::FillLightning::Layer::attach(), p(), and Slic3r::FillLightning::Layer::reconnectRoots().
The documentation for this struct was generated from the following files:
src/libslic3r/Fill/Lightning/Layer.hpp
src/libslic3r/Fill/Lightning/Layer.cpp