Prusa Slicer: ImGuiTextBuffer Struct Reference
ImGuiTextBuffer Struct Reference
#include <src/imgui/imgui.h>
Public Member Functions
ImGuiTextBuffer ()
char operator[] (int i) const
const char * begin () const
const char * end () const
int size () const
bool empty () const
void clear ()
void reserve (int capacity)
const char * c_str () const
IMGUI_API void append (const char *str, const char *str_end=NULL)
IMGUI_API void appendf (const char *fmt,...) IM_FMTARGS(2)
IMGUI_API void appendfv (const char *fmt, va_list args) IM_FMTLIST(2)
Public Attributes
ImVector< char > Buf
Static Public Attributes
static IMGUI_API char EmptyString [1] = { 0 }
Detailed Description
Constructor & Destructor Documentation
ImGuiTextBuffer()
ImGuiTextBuffer::ImGuiTextBuffer () inline
{ }
Member Function Documentation
append()
void ImGuiTextBuffer::append (const char * str, const char * str_end = NULL)
{
    int len = str_end ? (int)(str_end - str) : (int)strlen(str);
    // Add zero-terminator the first time
    const int write_off = (Buf.Size != 0) ? Buf.Size : 1;
    const int needed_sz = write_off + len;
    if (write_off + len >= Buf.Capacity)
    {
        int new_capacity = Buf.Capacity * 2;
        Buf.reserve(needed_sz > new_capacity ? needed_sz : new_capacity);
    }
    Buf.resize(needed_sz);
    memcpy(&Buf[write_off - 1], str, (size_t)len);
    Buf[write_off - 1 + len] = 0;
}
Referenced by ImGui::TabItemEx(), TableSettingsHandler_WriteAll(), ImGui::TableSetupColumn(), and WindowSettingsHandler_WriteAll().
appendf()
void ImGuiTextBuffer::appendf (const char * fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    appendfv(fmt, args);
    va_end(args);
}
Referenced by TableSettingsHandler_WriteAll(), and WindowSettingsHandler_WriteAll().
appendfv()
void ImGuiTextBuffer::appendfv (const char * fmt, va_list args)
{
    va_list args_copy;
    va_copy(args_copy, args);
    int len = ImFormatStringV(NULL, 0, fmt, args);         // FIXME-OPT: could do a first pass write attempt, likely successful on first pass.
    if (len <= 0)
    {
        va_end(args_copy);
        return;
    }
    // Add zero-terminator the first time
    const int write_off = (Buf.Size != 0) ? Buf.Size : 1;
    const int needed_sz = write_off + len;
    if (write_off + len >= Buf.Capacity)
    {
        int new_capacity = Buf.Capacity * 2;
        Buf.reserve(needed_sz > new_capacity ? needed_sz : new_capacity);
    }
    Buf.resize(needed_sz);
    ImFormatStringV(&Buf[write_off - 1], (size_t)len + 1, fmt, args_copy);
    va_end(args_copy);
}
References ImFormatStringV(), and va_copy.
Referenced by ExampleAppLog::AddLog(), and LogTextV().
begin()
const char * ImGuiTextBuffer::begin () const inline
{ return Buf.Data ? &Buf.front() : EmptyString; }
References ImVector< T >::Data, and ImVector< T >::front().
Referenced by ExampleAppLog::Draw(), and ImGui::LogFinish().
c_str()
const char * ImGuiTextBuffer::c_str () const inline
{ return Buf.Data ? Buf.Data : EmptyString; }
References ImVector< T >::Data.
Referenced by LogTextV(), ImGui::SaveIniSettingsToMemory(), and ImGui::ShowMetricsWindow().
clear()
void ImGuiTextBuffer::clear () inline
{ Buf.clear(); }
References ImVector< T >::clear().
Referenced by ExampleAppLog::Clear(), ImGui::ClearIniSettings(), ImGui::LogFinish(), ImGui::Shutdown(), and ImGui::TableGcCompactTransientBuffers().
empty()
bool ImGuiTextBuffer::empty () const inline
{ return Buf.Size <= 1; }
References ImVector< T >::Size.
Referenced by ImGui::LogBegin(), and ImGui::LogFinish().
end()
const char * ImGuiTextBuffer::end () const inline
{ return Buf.Data ? &Buf.back() : EmptyString; }   // Buf is zero-terminated, so end() will point on the zero-terminator
References ImVector< T >::back(), and ImVector< T >::Data.
Referenced by ExampleAppLog::Draw().
operator[]()
char ImGuiTextBuffer::operator[] (int i) const inline
{ IM_ASSERT(Buf.Data != NULL); return Buf.Data[i]; }
References ImVector< T >::Data, and IM_ASSERT.
reserve()
void ImGuiTextBuffer::reserve (int capacity) inline
{ Buf.reserve(capacity); }
References ImVector< T >::reserve().
Referenced by TableSettingsHandler_WriteAll(), and WindowSettingsHandler_WriteAll().
size()
int ImGuiTextBuffer::size () const inline
{ return Buf.Size ? Buf.Size - 1 : 0; }
References ImVector< T >::Size.
Referenced by ExampleAppLog::AddLog(), LogTextV(), ImGui::SaveIniSettingsToMemory(), ImGui::ShowMetricsWindow(), ImGui::TabItemEx(), TableSettingsHandler_WriteAll(), ImGui::TableSetupColumn(), and WindowSettingsHandler_WriteAll().
Member Data Documentation
Buf
ImVector<char> ImGuiTextBuffer::Buf
Referenced by ImGui::BeginTableEx(), ImGuiTabBar::GetTabName(), ImGui::LoadIniSettingsFromMemory(), LogTextV(), ImGui::SaveIniSettingsToMemory(), ImGui::ShowMetricsWindow(), ImGui::TabBarLayout(), and ImGui::TableGetColumnName().
EmptyString
char ImGuiTextBuffer::EmptyString = { 0 } static
The documentation for this struct was generated from the following files:
src/imgui/imgui.h
src/imgui/imgui.cpp