Prusa Slicer: Slic3r::GUI::BedShape Struct Reference
Slic3r::GUI::BedShape Struct Reference
#include <src/slic3r/GUI/BedShapeDialog.hpp>
Public Types
enum class PageType { Rectangle , Circle , Custom }
enum class Parameter { RectSize , RectOrigin , Diameter }
Public Member Functions
BedShape (const ConfigOptionPoints &points)
bool is_custom ()
PageType get_page_type ()
wxString get_full_name_with_params ()
void apply_optgroup_values (ConfigOptionsGroupShp optgroup)
Static Public Member Functions
static void append_option_line (ConfigOptionsGroupShp optgroup, Parameter param)
static wxString get_name (PageType type)
Private Attributes
BuildVolume m_build_volume
Detailed Description
Member Enumeration Documentation
PageType
enum class Slic3r::GUI::BedShape::PageType strong
Enumerator
Rectangle
Circle
Custom
{
        Rectangle,
        Circle,
        Custom
    };
Parameter
enum class Slic3r::GUI::BedShape::Parameter strong
Enumerator
RectSize
RectOrigin
Diameter
{
        RectSize,
        RectOrigin,
        Diameter
    };
Constructor & Destructor Documentation
BedShape()
Slic3r::GUI::BedShape::BedShape (const ConfigOptionPoints & points)
{
    m_build_volume = { points.values, 0. };
}
References m_build_volume, and Slic3r::ConfigOptionVector< T >::values.
Member Function Documentation
append_option_line()
void Slic3r::GUI::BedShape::append_option_line (ConfigOptionsGroupShp optgroup, Parameter param) static
{
    ConfigOptionDef def;
    t_config_option_key key;
    switch (param) {
    case Parameter::RectSize:
        def.type = coPoints;
        def.set_default_value(new ConfigOptionPoints{ Vec2d(200, 200) });
        def.min = 0;
        def.max = 1200;
        def.label = get_option_label(param);
        def.tooltip = L("Size in X and Y of the rectangular plate.");
        key = "rect_size";
        break;
    case Parameter::RectOrigin:
        def.type = coPoints;
        def.set_default_value(new ConfigOptionPoints{ Vec2d(0, 0) });
        def.min = -600;
        def.max = 600;
        def.label = get_option_label(param);
        def.tooltip = L("Distance of the 0,0 G-code coordinate from the front left corner of the rectangle.");
        key = "rect_origin";
        break;
    case Parameter::Diameter:
        def.type = coFloat;
        def.set_default_value(new ConfigOptionFloat(200));
        def.sidetext = L("mm");
        def.label = get_option_label(param);
        def.tooltip = L("Diameter of the print bed. It is assumed that origin (0,0) is located in the center.");
        key = "diameter";
        break;
    default:
        assert(false);
    }
    optgroup->append_single_option_line({ def, std::move(key) });
}
References Slic3r::coFloat, Slic3r::coPoints, Diameter, Slic3r::GUI::get_option_label(), L, Slic3r::ConfigOptionDef::label, Slic3r::ConfigOptionDef::max, Slic3r::ConfigOptionDef::min, RectOrigin, RectSize, Slic3r::ConfigOptionDef::set_default_value(), Slic3r::ConfigOptionDef::sidetext, Slic3r::ConfigOptionDef::tooltip, and Slic3r::ConfigOptionDef::type.
Referenced by Slic3r::GUI::BedShapePanel::build_panel().
apply_optgroup_values()
void Slic3r::GUI::BedShape::apply_optgroup_values (ConfigOptionsGroupShp optgroup)
{
    switch (m_build_volume.type()) {
    case BuildVolume::Type::Circle:
        optgroup->set_value("diameter", double_to_string(2. * unscaled<double>(m_build_volume.circle().radius)));
        break;
    default:
        // rectangle, convex, concave...
        optgroup->set_value("rect_size"     , to_2d(m_build_volume.bounding_volume().size()));
        optgroup->set_value("rect_origin"   , to_2d(-1 * m_build_volume.bounding_volume().min));
    }
}
References Slic3r::BuildVolume::bounding_volume(), Slic3r::BuildVolume::Circle, Slic3r::BuildVolume::circle(), Slic3r::GUI::double_to_string(), m_build_volume, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::Geometry::Circle< Vector >::radius, Slic3r::BoundingBox3Base< PointType >::size(), Slic3r::to_2d(), and Slic3r::BuildVolume::type().
Referenced by Slic3r::GUI::BedShapePanel::set_shape().
get_full_name_with_params()
wxString Slic3r::GUI::BedShape::get_full_name_with_params ()
{
    wxString out = _L("Shape") + ": " + get_name(this->get_page_type());
    switch (m_build_volume.type()) {
    case BuildVolume::Type::Circle:
        out += "\n" + _L(get_option_label(Parameter::Diameter)) + ": [" + double_to_string(2. * unscaled<double>(m_build_volume.circle().radius)) + "]";
        break;
    default:
        // rectangle, convex, concave...
        out += "\n" + _(get_option_label(Parameter::RectSize)) + ": [" + ConfigOptionPoint(to_2d(m_build_volume.bounding_volume().size())).serialize() + "]";
        out += "\n" + _(get_option_label(Parameter::RectOrigin)) + ": [" + ConfigOptionPoint(- to_2d(m_build_volume.bounding_volume().min)).serialize() + "]";
        break;
    }
    return out;
}
References _, _L, Slic3r::BuildVolume::bounding_volume(), Slic3r::BuildVolume::Circle, Slic3r::BuildVolume::circle(), Diameter, Slic3r::GUI::double_to_string(), get_name(), Slic3r::GUI::get_option_label(), get_page_type(), m_build_volume, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::Geometry::Circle< Vector >::radius, RectOrigin, RectSize, Slic3r::ConfigOptionPoint::serialize(), Slic3r::BoundingBox3Base< PointType >::size(), Slic3r::to_2d(), and Slic3r::BuildVolume::type().
Referenced by Slic3r::GUI::get_string_value().
get_name()
wxString Slic3r::GUI::BedShape::get_name (PageType type) static
{
    switch (type) {
    case PageType::Rectangle:  return _L("Rectangular");
    case PageType::Circle:     return _L("Circular");
    case PageType::Custom:     return _L("Custom");
    }
    // make visual studio happy
    assert(false);
    return {};
}
References _L, Circle, Custom, and Rectangle.
Referenced by Slic3r::GUI::BedShapePanel::build_panel(), and get_full_name_with_params().
get_page_type()
BedShape::PageType Slic3r::GUI::BedShape::get_page_type ()
{
    switch (m_build_volume.type()) {
    case BuildVolume::Type::Rectangle:
    case BuildVolume::Type::Invalid:    return PageType::Rectangle;
    case BuildVolume::Type::Circle:     return PageType::Circle;
    case BuildVolume::Type::Convex:
    case BuildVolume::Type::Custom:     return PageType::Custom;
    }
    // make visual studio happy
    assert(false);
    return PageType::Rectangle;
}
References Slic3r::BuildVolume::Circle, Circle, Slic3r::BuildVolume::Convex, Slic3r::BuildVolume::Custom, Custom, Slic3r::BuildVolume::Invalid, m_build_volume, Slic3r::BuildVolume::Rectangle, Rectangle, and Slic3r::BuildVolume::type().
Referenced by get_full_name_with_params(), and Slic3r::GUI::BedShapePanel::set_shape().
is_custom()
bool Slic3r::GUI::BedShape::is_custom () inline
{ return m_build_volume.type() == BuildVolume::Type::Convex || m_build_volume.type() == BuildVolume::Type::Custom; }
References Slic3r::BuildVolume::Convex, Slic3r::BuildVolume::Custom, m_build_volume, and Slic3r::BuildVolume::type().
Referenced by Slic3r::GUI::BedShapePanel::set_shape().
Member Data Documentation
m_build_volume
BuildVolume Slic3r::GUI::BedShape::m_build_volume private
Referenced by BedShape(), apply_optgroup_values(), get_full_name_with_params(), get_page_type(), and is_custom().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/BedShapeDialog.hpp
src/slic3r/GUI/BedShapeDialog.cpp