Prusa Slicer: Slic3r::CustomGCode Namespace Reference
Slic3r::CustomGCode Namespace Reference
Classes
struct Info
struct Item
Enumerations
enum Type {
ColorChange , PausePrint , ToolChange , Template ,
Custom
}
enum Mode { Undef , SingleExtruder , MultiAsSingle , MultiExtruder }
Functions
void update_custom_gcode_per_print_z_from_config (Info &info, DynamicPrintConfig *config)
void check_mode_for_custom_gcode_per_print_z (Info &info)
std::vector< std::pair< double, unsigned int > > custom_tool_changes (const Info &custom_gcode_per_print_z, size_t num_extruders)
Variables
static constexpr char SingleExtruderMode [] = "SingleExtruder"
static constexpr char MultiAsSingleMode [] = "MultiAsSingle"
static constexpr char MultiExtruderMode [] = "MultiExtruder"
Enumeration Type Documentation
Mode
enum Slic3r::CustomGCode::Mode
Enumerator
Undef
SingleExtruder
MultiAsSingle
MultiExtruder
{
    Undef,
    SingleExtruder,   // Single extruder printer preset is selected
    MultiAsSingle,    // Multiple extruder printer preset is selected, but
                      // this mode works just for Single extruder print
                      // (The same extruder is assigned to all ModelObjects and ModelVolumes).
    MultiExtruder     // Multiple extruder printer preset is selected
};
Type
enum Slic3r::CustomGCode::Type
Enumerator
ColorChange
PausePrint
ToolChange
Template
Custom
{
    ColorChange,
    PausePrint,
    ToolChange,
    Template,
    Custom
};
Function Documentation
check_mode_for_custom_gcode_per_print_z()
void Slic3r::CustomGCode::check_mode_for_custom_gcode_per_print_z (Info & info)
{
    if (info.mode != Undef)
        return;
    bool is_single_extruder = true;
    for (const Item& item : info.gcodes)
    {
        if (item.type == ToolChange) {
            info.mode = MultiAsSingle;
            return;
        }
        if (item.type == ColorChange && item.extruder > 1)
            is_single_extruder = false;
    }
    info.mode = is_single_extruder ? SingleExtruder : MultiExtruder;
}
References ColorChange, Slic3r::CustomGCode::Info::gcodes, Slic3r::CustomGCode::Info::mode, MultiAsSingle, MultiExtruder, SingleExtruder, ToolChange, and Undef.
Referenced by Slic3r::Model::read_from_archive(), and Slic3r::Model::read_from_file().
custom_tool_changes()
std::vector< std::pair< double, unsigned int > > Slic3r::CustomGCode::custom_tool_changes (const Info & custom_gcode_per_print_z, size_t num_extruders)
{
    std::vector<std::pair<double, unsigned int>> custom_tool_changes;
    for (const Item& custom_gcode : custom_gcode_per_print_z.gcodes)
        if (custom_gcode.type == ToolChange) {
            // If extruder count in PrinterSettings was changed, use default (0) extruder for extruders, more than num_extruders
            assert(custom_gcode.extruder >= 0);
            custom_tool_changes.emplace_back(custom_gcode.print_z, static_cast<unsigned int>(size_t(custom_gcode.extruder) > num_extruders ? 1 : custom_gcode.extruder));
        }
    return custom_tool_changes;
}
References custom_tool_changes(), Slic3r::CustomGCode::Info::gcodes, and ToolChange.
Referenced by Slic3r::ToolOrdering::ToolOrdering(), and custom_tool_changes().
update_custom_gcode_per_print_z_from_config()
void Slic3r::CustomGCode::update_custom_gcode_per_print_z_from_config (Info & info, DynamicPrintConfig * config)
{
  auto *colorprint_heights = config->option<ConfigOptionFloats>("colorprint_heights");
    if (colorprint_heights == nullptr)
        return;
    if (info.gcodes.empty() && ! colorprint_heights->values.empty()) {
    // Convert the old colorprint_heighs only if there is no equivalent data in a new format.
        const std::vector<std::string>& colors = ColorPrintColors::get();
        const auto& colorprint_values = colorprint_heights->values;
        info.gcodes.clear();
        info.gcodes.reserve(colorprint_values.size());
        int i = 0;
        for (auto val : colorprint_values)
            info.gcodes.emplace_back(Item{ val, ColorChange, 1, colors[(++i)%7] });
        info.mode = SingleExtruder;
  }
  // The "colorprint_heights" config value has been deprecated. At this point of time it has been converted
  // to a new format and therefore it shall be erased.
    config->erase("colorprint_heights");
}
References ColorChange, Slic3r::CustomGCode::Info::gcodes, Slic3r::ColorPrintColors::get(), Slic3r::CustomGCode::Info::mode, Slic3r::ConfigBase::option(), and SingleExtruder.
Referenced by Slic3r::GUI::Plater::priv::load_files(), Slic3r::Model::read_from_archive(), and Slic3r::Model::read_from_file().
Variable Documentation
MultiAsSingleMode
constexpr char Slic3r::CustomGCode::MultiAsSingleMode[] = "MultiAsSingle" static constexpr
Referenced by Slic3r::AMFParserContext::endElement(), and Slic3r::DoubleSlider::Control::get_tooltip().
MultiExtruderMode
constexpr char Slic3r::CustomGCode::MultiExtruderMode[] = "MultiExtruder" static constexpr
Referenced by Slic3r::DoubleSlider::Control::get_tooltip().
SingleExtruderMode
constexpr char Slic3r::CustomGCode::SingleExtruderMode[] = "SingleExtruder" static constexpr
Referenced by Slic3r::AMFParserContext::endElement(), and Slic3r::DoubleSlider::Control::get_tooltip().