Prusa Slicer: Slic3r::Zipper::Impl Class Reference
Slic3r::Zipper::Impl Class Reference
Public Member Functions
std::string formatted_errorstr () const
SLIC3R_NORETURN void blow_up () const
bool is_alive ()
std::string get_errorstr () const
bool is_alive () const
Static Public Member Functions
static std::string get_errorstr (mz_zip_error mz_err)
Public Attributes
std::string m_zipname
mz_zip_archive arch
Detailed Description
Member Function Documentation
blow_up()
SLIC3R_NORETURN void Slic3r::Zipper::Impl::blow_up () const inline
    {
        throw Slic3r::ExportError(formatted_errorstr());
    }
References formatted_errorstr().
formatted_errorstr()
std::string Slic3r::Zipper::Impl::formatted_errorstr () const inline
    {
        return _u8L("Error with ZIP archive") + " " + m_zipname + ": " +
               get_errorstr();
    }
References _u8L, Slic3r::MZ_Archive::get_errorstr(), and m_zipname.
Referenced by blow_up().
get_errorstr() [1/2]
std::string Slic3r::MZ_Archive::get_errorstr () const inline inherited
    {
        return get_errorstr(arch.m_last_error) + "!";
    }
References Slic3r::MZ_Archive::arch, Slic3r::MZ_Archive::get_errorstr(), and mz_zip_archive::m_last_error.
Referenced by formatted_errorstr(), and Slic3r::MZ_Archive::get_errorstr().
get_errorstr() [2/2]
std::string Slic3r::MZ_Archive::get_errorstr (mz_zip_error mz_err) static inherited
{
    switch (mz_err)
    {
    case MZ_ZIP_NO_ERROR:
        return "no error";
    case MZ_ZIP_UNDEFINED_ERROR:
        return _u8L("undefined error");
    case MZ_ZIP_TOO_MANY_FILES:
        return _u8L("too many files");
    case MZ_ZIP_FILE_TOO_LARGE:
        return _u8L("file too large");
    case MZ_ZIP_UNSUPPORTED_METHOD:
        return _u8L("unsupported method");
    case MZ_ZIP_UNSUPPORTED_ENCRYPTION:
        return _u8L("unsupported encryption");
    case MZ_ZIP_UNSUPPORTED_FEATURE:
        return _u8L("unsupported feature");
    case MZ_ZIP_FAILED_FINDING_CENTRAL_DIR:
        return _u8L("failed finding central directory");
    case MZ_ZIP_NOT_AN_ARCHIVE:
        return _u8L("not a ZIP archive");
    case MZ_ZIP_INVALID_HEADER_OR_CORRUPTED:
        return _u8L("invalid header or archive is corrupted");
    case MZ_ZIP_UNSUPPORTED_MULTIDISK:
        return _u8L("unsupported multidisk archive");
    case MZ_ZIP_DECOMPRESSION_FAILED:
        return _u8L("decompression failed or archive is corrupted");
    case MZ_ZIP_COMPRESSION_FAILED:
        return _u8L("compression failed");
    case MZ_ZIP_UNEXPECTED_DECOMPRESSED_SIZE:
        return _u8L("unexpected decompressed size");
    case MZ_ZIP_CRC_CHECK_FAILED:
        return _u8L("CRC-32 check failed");
    case MZ_ZIP_UNSUPPORTED_CDIR_SIZE:
        return _u8L("unsupported central directory size");
    case MZ_ZIP_ALLOC_FAILED:
        return _u8L("allocation failed");
    case MZ_ZIP_FILE_OPEN_FAILED:
        return _u8L("file open failed");
    case MZ_ZIP_FILE_CREATE_FAILED:
        return _u8L("file create failed");
    case MZ_ZIP_FILE_WRITE_FAILED:
        return _u8L("file write failed");
    case MZ_ZIP_FILE_READ_FAILED:
        return _u8L("file read failed");
    case MZ_ZIP_FILE_CLOSE_FAILED:
        return _u8L("file close failed");
    case MZ_ZIP_FILE_SEEK_FAILED:
        return _u8L("file seek failed");
    case MZ_ZIP_FILE_STAT_FAILED:
        return _u8L("file stat failed");
    case MZ_ZIP_INVALID_PARAMETER:
        return _u8L("invalid parameter");
    case MZ_ZIP_INVALID_FILENAME:
        return _u8L("invalid filename");
    case MZ_ZIP_BUF_TOO_SMALL:
        return _u8L("buffer too small");
    case MZ_ZIP_INTERNAL_ERROR:
        return _u8L("internal error");
    case MZ_ZIP_FILE_NOT_FOUND:
        return _u8L("file not found");
    case MZ_ZIP_ARCHIVE_TOO_LARGE:
        return _u8L("archive is too large");
    case MZ_ZIP_VALIDATION_FAILED:
        return _u8L("validation failed");
    case MZ_ZIP_WRITE_CALLBACK_FAILED:
        return _u8L("write calledback failed");
    default:
        break;
    }
    return "unknown error";
}
References _u8L, MZ_ZIP_ALLOC_FAILED, MZ_ZIP_ARCHIVE_TOO_LARGE, MZ_ZIP_BUF_TOO_SMALL, MZ_ZIP_COMPRESSION_FAILED, MZ_ZIP_CRC_CHECK_FAILED, MZ_ZIP_DECOMPRESSION_FAILED, MZ_ZIP_FAILED_FINDING_CENTRAL_DIR, MZ_ZIP_FILE_CLOSE_FAILED, MZ_ZIP_FILE_CREATE_FAILED, MZ_ZIP_FILE_NOT_FOUND, MZ_ZIP_FILE_OPEN_FAILED, MZ_ZIP_FILE_READ_FAILED, MZ_ZIP_FILE_SEEK_FAILED, MZ_ZIP_FILE_STAT_FAILED, MZ_ZIP_FILE_TOO_LARGE, MZ_ZIP_FILE_WRITE_FAILED, MZ_ZIP_INTERNAL_ERROR, MZ_ZIP_INVALID_FILENAME, MZ_ZIP_INVALID_HEADER_OR_CORRUPTED, MZ_ZIP_INVALID_PARAMETER, MZ_ZIP_NO_ERROR, MZ_ZIP_NOT_AN_ARCHIVE, MZ_ZIP_TOO_MANY_FILES, MZ_ZIP_UNDEFINED_ERROR, MZ_ZIP_UNEXPECTED_DECOMPRESSED_SIZE, MZ_ZIP_UNSUPPORTED_CDIR_SIZE, MZ_ZIP_UNSUPPORTED_ENCRYPTION, MZ_ZIP_UNSUPPORTED_FEATURE, MZ_ZIP_UNSUPPORTED_METHOD, MZ_ZIP_UNSUPPORTED_MULTIDISK, MZ_ZIP_VALIDATION_FAILED, and MZ_ZIP_WRITE_CALLBACK_FAILED.
is_alive() [1/2]
bool Slic3r::Zipper::Impl::is_alive () inline
    {
        return arch.m_zip_mode != MZ_ZIP_MODE_WRITING_HAS_BEEN_FINALIZED;
    }
References Slic3r::MZ_Archive::arch, mz_zip_archive::m_zip_mode, and MZ_ZIP_MODE_WRITING_HAS_BEEN_FINALIZED.
is_alive() [2/2]
bool Slic3r::MZ_Archive::is_alive () const inline inherited
    {
        return arch.m_zip_mode != MZ_ZIP_MODE_WRITING_HAS_BEEN_FINALIZED;
    }
References Slic3r::MZ_Archive::arch, mz_zip_archive::m_zip_mode, and MZ_ZIP_MODE_WRITING_HAS_BEEN_FINALIZED.
Member Data Documentation
arch
mz_zip_archive Slic3r::MZ_Archive::arch inherited
Referenced by Slic3r::MZ_Archive::MZ_Archive(), Slic3r::MZ_Archive::get_errorstr(), is_alive(), and Slic3r::MZ_Archive::is_alive().
m_zipname
std::string Slic3r::Zipper::Impl::m_zipname
Referenced by formatted_errorstr().
The documentation for this class was generated from the following file:
src/libslic3r/Zipper.cpp