Prusa Slicer: Slic3r::GUI::ArchiveViewModel Class Reference
Slic3r::GUI::ArchiveViewModel Class Reference
#include <src/slic3r/GUI/FileArchiveDialog.hpp>
Public Member Functions
ArchiveViewModel (wxWindow *parent)
~ArchiveViewModel ()
std::shared_ptr< ArchiveViewNode > AddFile (std::shared_ptr< ArchiveViewNode > parent, const wxString &name, bool container)
wxString GetColumnType (unsigned int col) const override
unsigned int GetColumnCount () const override
void Rescale ()
void Delete (const wxDataViewItem &item)
void Clear ()
wxDataViewItem GetParent (const wxDataViewItem &item) const override
unsigned int GetChildren (const wxDataViewItem &parent, wxDataViewItemArray &array) const override
void SetAssociatedControl (ArchiveViewCtrl *ctrl)
void GetValue (wxVariant &variant, const wxDataViewItem &item, unsigned int col) const override
bool SetValue (const wxVariant &variant, const wxDataViewItem &item, unsigned int col) override
void untoggle_folders (const wxDataViewItem &item)
bool IsEnabled (const wxDataViewItem &item, unsigned int col) const override
bool IsContainer (const wxDataViewItem &item) const override
bool HasContainerColumns (const wxDataViewItem &WXUNUSED(item)) const override
Protected Attributes
wxWindow * m_parent { nullptr }
ArchiveViewCtrl * m_ctrl { nullptr }
std::vector< std::shared_ptr< ArchiveViewNode > > m_top_children
Detailed Description
Constructor & Destructor Documentation
ArchiveViewModel()
Slic3r::GUI::ArchiveViewModel::ArchiveViewModel (wxWindow * parent)
    :m_parent(parent)
{}
~ArchiveViewModel()
Slic3r::GUI::ArchiveViewModel::~ArchiveViewModel ()
{}
Member Function Documentation
AddFile()
std::shared_ptr< ArchiveViewNode > Slic3r::GUI::ArchiveViewModel::AddFile (std::shared_ptr< ArchiveViewNode > parent, const wxString & name, bool container)
{
    std::shared_ptr<ArchiveViewNode> node = std::make_shared<ArchiveViewNode>(ArchiveViewNode(name));
    node->set_container(container);
    if (parent.get() != nullptr) {
        parent->get_children().push_back(node);
        node->set_parent(parent);
        parent->set_is_folder(true);
    } else {
        m_top_children.emplace_back(node);
    }
    wxDataViewItem child = wxDataViewItem((void*)node.get());
    wxDataViewItem parent_item= wxDataViewItem((void*)parent.get());
    ItemAdded(parent_item, child);
    if (parent)
        m_ctrl->Expand(parent_item);
    return node;
}
References m_ctrl, and m_top_children.
Referenced by Slic3r::GUI::FileArchiveDialog::FileArchiveDialog().
Clear()
void Slic3r::GUI::ArchiveViewModel::Clear ()
{
}
Referenced by Slic3r::GUI::ArchiveViewCtrl::~ArchiveViewCtrl().
Delete()
void Slic3r::GUI::ArchiveViewModel::Delete (const wxDataViewItem & item)
{
    assert(item.IsOk());
    ArchiveViewNode* node = static_cast<ArchiveViewNode*>(item.GetID());
    assert(node->get_parent() != nullptr);
    for (std::shared_ptr<ArchiveViewNode> child : node->get_children())
    {
        Delete(wxDataViewItem((void*)child.get()));
    }
    delete [] node;
}
References Slic3r::GUI::Delete, Slic3r::GUI::ArchiveViewNode::get_children(), and Slic3r::GUI::ArchiveViewNode::get_parent().
GetChildren()
unsigned int Slic3r::GUI::ArchiveViewModel::GetChildren (const wxDataViewItem & parent, wxDataViewItemArray & array) const override
{
    if (!parent.IsOk()) {
        for (std::shared_ptr<ArchiveViewNode>child : m_top_children) {
            array.push_back(wxDataViewItem((void*)child.get()));
        }
        return m_top_children.size();
    }
    ArchiveViewNode* node = static_cast<ArchiveViewNode*>(parent.GetID());
    for (std::shared_ptr<ArchiveViewNode> child : node->get_children()) {
        array.push_back(wxDataViewItem((void*)child.get()));
    }
    return node->get_children().size();
}
References Slic3r::GUI::ArchiveViewNode::get_children(), and m_top_children.
Referenced by Slic3r::GUI::FileArchiveDialog::on_all_button(), Slic3r::GUI::FileArchiveDialog::on_none_button(), and Slic3r::GUI::FileArchiveDialog::on_open_button().
GetColumnCount()
unsigned int Slic3r::GUI::ArchiveViewModel::GetColumnCount () const inline override
{ return 2; }
GetColumnType()
wxString Slic3r::GUI::ArchiveViewModel::GetColumnType (unsigned int col) const override
{
    if (col == 0)
        return "bool";
    return "string";//"DataViewBitmapText";
}
References col().
GetParent()
wxDataViewItem Slic3r::GUI::ArchiveViewModel::GetParent (const wxDataViewItem & item) const override
{
    assert(item.IsOk());
    ArchiveViewNode* node = static_cast<ArchiveViewNode*>(item.GetID());
    return wxDataViewItem((void*)node->get_parent().get());
}
References Slic3r::GUI::ArchiveViewNode::get_parent().
GetValue()
void Slic3r::GUI::ArchiveViewModel::GetValue (wxVariant & variant, const wxDataViewItem & item, unsigned int col) const override
{
    assert(item.IsOk());
    ArchiveViewNode* node = static_cast<ArchiveViewNode*>(item.GetID());
    if (col == 0) {
        variant = node->get_toggle();
    } else {
        variant = node->get_name();
    }
}
References col(), Slic3r::GUI::ArchiveViewNode::get_name(), and Slic3r::GUI::ArchiveViewNode::get_toggle().
HasContainerColumns()
bool Slic3r::GUI::ArchiveViewModel::HasContainerColumns (const wxDataViewItem & WXUNUSEDitem) const inline override
{ return true; }
IsContainer()
bool Slic3r::GUI::ArchiveViewModel::IsContainer (const wxDataViewItem & item) const override
{
    if(!item.IsOk())
        return true;
    ArchiveViewNode* node = static_cast<ArchiveViewNode*>(item.GetID());
    return node->is_container();
}
References Slic3r::GUI::ArchiveViewNode::is_container().
IsEnabled()
bool Slic3r::GUI::ArchiveViewModel::IsEnabled (const wxDataViewItem & item, unsigned int col) const override
{
    // As of now, all items are always enabled.
    // Returning false for col 1 would gray out text.
    return true;
}
Rescale()
void Slic3r::GUI::ArchiveViewModel::Rescale ()
{
    // There should be no pictures rendered
}
SetAssociatedControl()
void Slic3r::GUI::ArchiveViewModel::SetAssociatedControl (ArchiveViewCtrl * ctrl) inline
{ m_ctrl = ctrl; }
References m_ctrl.
Referenced by Slic3r::GUI::ArchiveViewCtrl::ArchiveViewCtrl().
SetValue()
bool Slic3r::GUI::ArchiveViewModel::SetValue (const wxVariant & variant, const wxDataViewItem & item, unsigned int col) override
{
    assert(item.IsOk());
    ArchiveViewNode* node = static_cast<ArchiveViewNode*>(item.GetID());
    if (col == 0) {
        node->set_toggle(variant.GetBool());
        // if folder recursivelly check all children
        for (std::shared_ptr<ArchiveViewNode> child : node->get_children()) {
            SetValue(variant, wxDataViewItem((void*)child.get()), col);
        }
        if(!variant.GetBool() && node->get_parent())
            untoggle_folders(wxDataViewItem((void*)node->get_parent().get()));
    } else {
        node->set_name(variant.GetString());
    }
    m_parent->Refresh();
    return true;
}
References col(), Slic3r::GUI::ArchiveViewNode::get_children(), Slic3r::GUI::ArchiveViewNode::get_parent(), m_parent, Slic3r::GUI::ArchiveViewNode::set_name(), Slic3r::GUI::ArchiveViewNode::set_toggle(), SetValue(), and untoggle_folders().
Referenced by SetValue().
untoggle_folders()
void Slic3r::GUI::ArchiveViewModel::untoggle_folders (const wxDataViewItem & item)
{
    assert(item.IsOk());
    ArchiveViewNode* node = static_cast<ArchiveViewNode*>(item.GetID());
    node->set_toggle(false);
    if (node->get_parent().get() != nullptr)
        untoggle_folders(wxDataViewItem((void*)node->get_parent().get()));
}
References Slic3r::GUI::ArchiveViewNode::get_parent(), Slic3r::GUI::ArchiveViewNode::set_toggle(), and untoggle_folders().
Referenced by SetValue(), and untoggle_folders().
Member Data Documentation
m_ctrl
ArchiveViewCtrl* Slic3r::GUI::ArchiveViewModel::m_ctrl { nullptr } protected
Referenced by AddFile(), and SetAssociatedControl().
m_parent
wxWindow* Slic3r::GUI::ArchiveViewModel::m_parent { nullptr } protected
Referenced by SetValue().
m_top_children
std::vector<std::shared_ptr<ArchiveViewNode> > Slic3r::GUI::ArchiveViewModel::m_top_children protected
Referenced by AddFile(), and GetChildren().
The documentation for this class was generated from the following files:
src/slic3r/GUI/FileArchiveDialog.hpp
src/slic3r/GUI/FileArchiveDialog.cpp