Prusa Slicer: priv::ModelCut2index Class Reference
priv::ModelCut2index Class Reference
Keep conversion from VCutAOIs to Index and vice versa Model_index .. contour(or hole) poin from ExPolygons Index .. continous number.
Public Member Functions
ModelCut2index (const VCutAOIs &cuts)
uint32_t calc_index (const ModelCutId &id) const
ModelCutId calc_id (uint32_t index) const
uint32_t get_count () const
const std::vector< uint32_t > & get_offsets () const
Private Attributes
std::vector< uint32_t > m_offsets
uint32_t m_count
Detailed Description
Keep conversion from VCutAOIs to Index and vice versa Model_index .. contour(or hole) poin from ExPolygons Index .. continous number.
Constructor & Destructor Documentation
ModelCut2index()
priv::ModelCut2index::ModelCut2index (const VCutAOIs & cuts)
{
    // prepare offsets
    m_offsets.reserve(cuts.size());
    uint32_t offset = 0;
    for (const CutAOIs &model_cuts: cuts) {
        m_offsets.push_back(offset);
        offset += model_cuts.size();
    }
    m_count = offset;
}
References m_count, m_offsets, and Slic3r::offset().
Member Function Documentation
calc_id()
priv::ModelCutId priv::ModelCut2index::calc_id (uint32_t index) const
{
    assert(index < m_count);
    ModelCutId result{0,0};
    // find shape index
    for (size_t model_index = 1; model_index < m_offsets.size(); ++model_index) {
        if (m_offsets[model_index] > index) break;
        result.model_index = model_index;
    }
    result.cut_index = index - m_offsets[result.model_index];
    return result;
}
References priv::ModelCutId::model_index.
calc_index()
uint32_t priv::ModelCut2index::calc_index (const ModelCutId & id) const
{
    assert(id.model_index < m_offsets.size());
    uint32_t offset = m_offsets[id.model_index];
    uint32_t res = offset + id.cut_index;
    assert(((id.model_index+1) < m_offsets.size() && res < m_offsets[id.model_index+1]) ||
           ((id.model_index+1) == m_offsets.size() && res < m_count));
    return res;
}
References Slic3r::offset().
get_count()
uint32_t priv::ModelCut2index::get_count () const inline
{ return m_count; };
References m_count.
Referenced by priv::diff_models(), and priv::has_bb_intersection().
get_offsets()
const std::vector< uint32_t > & priv::ModelCut2index::get_offsets () const inline
{ return m_offsets; }
References m_offsets.
Referenced by priv::has_bb_intersection().
Member Data Documentation
m_count
uint32_t priv::ModelCut2index::m_count private
Referenced by ModelCut2index(), and get_count().
m_offsets
std::vector<uint32_t> priv::ModelCut2index::m_offsets private
Referenced by ModelCut2index(), and get_offsets().
The documentation for this class was generated from the following file:
src/libslic3r/CutSurface.cpp