Prusa Slicer: Slic3r::GUI::DownloaderUtils::Worker Class Reference
Slic3r::GUI::DownloaderUtils::Worker Class Reference
#include <src/slic3r/GUI/ConfigWizard.hpp>
Public Member Functions
Worker (wxWindow *parent)
~Worker ()
void allow (bool allow_)
bool is_checked () const
wxString path_name () const
void set_path_name (wxString name)
void set_path_name (const std::string &name)
bool on_finish ()
bool perform_register (const std::string &path_override={})
Private Member Functions
void deregister ()
Private Attributes
wxWindow * m_parent { nullptr }
wxTextCtrl * m_input_path { nullptr }
bool downloader_checked { false }
Detailed Description
Constructor & Destructor Documentation
Worker()
Slic3r::GUI::DownloaderUtils::Worker::Worker (wxWindow * parent)
: wxBoxSizer(wxHORIZONTAL)
, m_parent(parent)
{
    m_input_path = new wxTextCtrl(m_parent, wxID_ANY);
    set_path_name(get_app_config()->get("url_downloader_dest"));
    auto* path_label = new wxStaticText(m_parent, wxID_ANY, _L("Download path") + ":");
    this->Add(path_label, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, 5);
    this->Add(m_input_path, 1, wxEXPAND | wxTOP | wxLEFT | wxRIGHT, 5);
    auto* button_path = new wxButton(m_parent, wxID_ANY, _L("Browse"));
    this->Add(button_path, 0, wxEXPAND | wxTOP | wxLEFT, 5);
    button_path->Bind(wxEVT_BUTTON, [this](wxCommandEvent& event) {
        boost::filesystem::path chosen_dest(boost::nowide::narrow(m_input_path->GetValue()));
        wxDirDialog dialog(m_parent, _L("Choose folder") + ":", chosen_dest.string() );
        if (dialog.ShowModal() == wxID_OK)
            this->m_input_path->SetValue(dialog.GetPath());
    });
    for (wxSizerItem* item : this->GetChildren())
        if (item->IsWindow()) {
            wxWindow* win = item->GetWindow();
            wxGetApp().UpdateDarkUI(win);
        }
}
References _L, Slic3r::GUI::get_app_config(), m_input_path, m_parent, boost::nowide::narrow(), set_path_name(), and wxEVT_BUTTON.
~Worker()
Slic3r::GUI::DownloaderUtils::Worker::~Worker () inline
{}
Member Function Documentation
allow()
void Slic3r::GUI::DownloaderUtils::Worker::allow (bool allow_) inline
{ downloader_checked = allow_; }
References downloader_checked.
Referenced by Slic3r::GUI::PageDownloader::PageDownloader(), and Slic3r::GUI::PreferencesDialog::show().
deregister()
void Slic3r::GUI::DownloaderUtils::Worker::deregister () private
{
#ifdef _WIN32
    std::string key_string = "";
    wxRegKey key_full(wxRegKey::HKCU, "Software\\Classes\\prusaslicer\\shell\\open\\command");
    if (!key_full.Exists()) {
        return;
    }
    key_full = key_string;
#elif __APPLE__
    // TODO
#else
    BOOST_LOG_TRIVIAL(debug) << "DesktopIntegrationDialog::undo_downloader_registration";
    DesktopIntegrationDialog::undo_downloader_registration();
    perform_registration_linux = false;
#endif
}
is_checked()
bool Slic3r::GUI::DownloaderUtils::Worker::is_checked () const inline
{ return downloader_checked; }
References downloader_checked.
on_finish()
bool Slic3r::GUI::DownloaderUtils::Worker::on_finish ()
{
    AppConfig* app_config = wxGetApp().app_config;
    bool ac_value = app_config->get_bool("downloader_url_registered");
    BOOST_LOG_TRIVIAL(debug) << "PageDownloader::on_finish_downloader ac_value " << ac_value << " downloader_checked " << downloader_checked;
    if (ac_value && downloader_checked) {
        // already registered but we need to do it again
        if (!perform_register())
            return false;
        app_config->set("downloader_url_registered", "1");
    } else if (!ac_value && downloader_checked) {
        // register
        if (!perform_register())
            return false;
        app_config->set("downloader_url_registered", "1");
    } else if (ac_value && !downloader_checked) {
        // deregister, downloads are banned now
        deregister();
        app_config->set("downloader_url_registered", "0");
    } /*else if (!ac_value && !downloader_checked) {
        // not registered and we dont want to do it
        // do not deregister as other instance might be registered
    } */
    return true;
}
References Slic3r::AppConfig::get_bool(), and Slic3r::AppConfig::set().
Referenced by Slic3r::GUI::PageDownloader::on_finish_downloader().
path_name()
wxString Slic3r::GUI::DownloaderUtils::Worker::path_name () const inline
{ return m_input_path ? m_input_path->GetValue() : wxString(); }
References m_input_path.
Referenced by perform_register().
perform_register()
bool Slic3r::GUI::DownloaderUtils::Worker::perform_register (const std::string & path_override = {})
{
    boost::filesystem::path aux_dest (GUI::into_u8(path_name()));
    if (!path_override.empty())
        aux_dest = boost::filesystem::path(path_override);
    boost::system::error_code ec;
    boost::filesystem::path chosen_dest = boost::filesystem::absolute(aux_dest, ec);
    if(ec)
        chosen_dest = aux_dest;
    ec.clear();
    if (chosen_dest.empty() || !boost::filesystem::is_directory(chosen_dest, ec) || ec) {
        std::string err_msg = GUI::format("%1%\n\n%2%",_L("Chosen directory for downloads does not exist.") ,chosen_dest.string());
        BOOST_LOG_TRIVIAL(error) << err_msg;
        show_error(m_parent, err_msg);
        return false;
    }
    BOOST_LOG_TRIVIAL(info) << "Downloader registration: Directory for downloads: " << chosen_dest.string();
    wxGetApp().app_config->set("url_downloader_dest", chosen_dest.string());
#ifdef _WIN32
    // Registry key creation for "prusaslicer://" URL
    boost::filesystem::path binary_path(boost::filesystem::canonical(boost::dll::program_location()));
    // the path to binary needs to be correctly saved in string with respect to localized characters
    wxString wbinary = wxString::FromUTF8(binary_path.string());
    std::string binary_string = (boost::format("%1%") % wbinary).str();
    BOOST_LOG_TRIVIAL(info) << "Downloader registration: Path of binary: " << binary_string;
    //std::string key_string = "\"" + binary_string + "\" \"-u\" \"%1\"";
    //std::string key_string = "\"" + binary_string + "\" \"%1\"";
    std::string key_string = "\"" + binary_string + "\" \"--single-instance\" \"%1\"";
    wxRegKey key_first(wxRegKey::HKCU, "Software\\Classes\\prusaslicer");
    wxRegKey key_full(wxRegKey::HKCU, "Software\\Classes\\prusaslicer\\shell\\open\\command");
    if (!key_first.Exists()) {
        key_first.Create(false);
    }
    key_first.SetValue("URL Protocol", "");
    if (!key_full.Exists()) {
        key_full.Create(false);
    }
    //key_full = "\"C:\\Program Files\\Prusa3D\\PrusaSlicer\\prusa-slicer-console.exe\" \"%1\"";
    key_full = key_string;
#elif __APPLE__
    // Apple registers for custom url in info.plist thus it has to be already registered since build.
    // The url will always trigger opening of prusaslicer and we have to check that user has allowed it. (GUI_App::MacOpenURL is the triggered method)
#else
    // the performation should be called later during desktop integration
    perform_registration_linux = true;
#endif
    return true;
}
References _L, error, Slic3r::GUI::format(), Slic3r::GUI::into_u8(), m_parent, path_name(), and Slic3r::GUI::show_error().
set_path_name() [1/2]
void Slic3r::GUI::DownloaderUtils::Worker::set_path_name (const std::string & name)
{
    if (!m_input_path)
        return;
    set_path_name(boost::nowide::widen(name));
}
References m_input_path, set_path_name(), and boost::nowide::widen().
set_path_name() [2/2]
void Slic3r::GUI::DownloaderUtils::Worker::set_path_name (wxString name)
{
    if (path.empty())
        path = boost::nowide::widen(get_app_config()->get("url_downloader_dest"));
    if (path.empty()) {
        // What should be default path? Each system has Downloads folder, that could be good one.
        // Other would be program location folder - not so good: access rights, apple bin is inside bundle...
        // default_path = boost::dll::program_location().parent_path().string();
        path = get_downloads_path();
    }
    m_input_path->SetValue(path);
}
References Slic3r::GUI::get_app_config(), m_input_path, and boost::nowide::widen().
Referenced by Worker(), set_path_name(), and Slic3r::GUI::PreferencesDialog::show().
Member Data Documentation
downloader_checked
bool Slic3r::GUI::DownloaderUtils::Worker::downloader_checked { false } private
Referenced by allow(), and is_checked().
m_input_path
wxTextCtrl* Slic3r::GUI::DownloaderUtils::Worker::m_input_path { nullptr } private
Referenced by Worker(), path_name(), set_path_name(), and set_path_name().
m_parent
wxWindow* Slic3r::GUI::DownloaderUtils::Worker::m_parent { nullptr } private
Referenced by Worker(), and perform_register().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ConfigWizard.hpp
src/slic3r/GUI/ConfigWizard.cpp