Prusa Slicer: Slic3r::client::FactorActions Struct Reference
Slic3r::client::FactorActions Struct Reference
Static Public Member Functions
static void set_start_pos (Iterator &start_pos, expr &out)
static void int_ (const MyContext *ctx, int &value, Iterator &end_pos, expr &out)
static void double_ (const MyContext *ctx, double &value, Iterator &end_pos, expr &out)
static void bool_ (const MyContext *ctx, bool &value, Iterator &end_pos, expr &out)
static void string_ (const MyContext *ctx, IteratorRange &it_range, expr &out)
static void expr_ (expr &value, Iterator &end_pos, expr &out)
static void minus_ (expr &value, expr &out)
static void not_ (expr &value, expr &out)
static void to_int (expr &value, expr &out)
static void round (expr &value, expr &out)
static void noexpr (expr &out)
Detailed Description
Member Function Documentation
bool_()
static void Slic3r::client::FactorActions::bool_ (const MyContext * ctx, bool & value, Iterator & end_pos, expr & out) inline static
{
            if (ctx->skipping()) {
                out.reset();
                out.it_range.end() = end_pos;
            } else
                out = expr(value, out.it_range.begin(), end_pos);
        }
References Slic3r::client::expr::it_range, Slic3r::client::expr::reset(), and Slic3r::client::MyContext::skipping().
Referenced by Slic3r::client::macro_processor::macro_processor().
double_()
static void Slic3r::client::FactorActions::double_ (const MyContext * ctx, double & value, Iterator & end_pos, expr & out) inline static
{
            if (ctx->skipping()) {
                out.reset();
                out.it_range.end() = end_pos;
            } else
                out = expr(value, out.it_range.begin(), end_pos);
        }
References Slic3r::client::expr::it_range, Slic3r::client::expr::reset(), and Slic3r::client::MyContext::skipping().
Referenced by Slic3r::client::macro_processor::macro_processor().
expr_()
static void Slic3r::client::FactorActions::expr_ (expr & value, Iterator & end_pos, expr & out) inline static
                { auto begin_pos = out.it_range.begin(); out = expr(std::move(value), begin_pos, end_pos); }
References Slic3r::client::expr::it_range.
Referenced by Slic3r::client::macro_processor::macro_processor().
int_()
static void Slic3r::client::FactorActions::int_ (const MyContext * ctx, int & value, Iterator & end_pos, expr & out) inline static
{
            if (ctx->skipping()) {
                out.reset();
                out.it_range.end() = end_pos;
            } else
                out = expr(value, out.it_range.begin(), end_pos);
        }
References Slic3r::client::expr::it_range, Slic3r::client::expr::reset(), and Slic3r::client::MyContext::skipping().
Referenced by Slic3r::client::macro_processor::macro_processor().
minus_()
static void Slic3r::client::FactorActions::minus_ (expr & value, expr & out) inline static
                { out = value.unary_minus(out.it_range.begin()); }
References Slic3r::client::expr::it_range, and Slic3r::client::expr::unary_minus().
Referenced by Slic3r::client::macro_processor::macro_processor().
noexpr()
static void Slic3r::client::FactorActions::noexpr (expr & out) inline static
{ out.reset(); }
References Slic3r::client::expr::reset().
Referenced by Slic3r::client::macro_processor::macro_processor().
not_()
static void Slic3r::client::FactorActions::not_ (expr & value, expr & out) inline static
                { out = value.unary_not(out.it_range.begin()); }
References Slic3r::client::expr::it_range, and Slic3r::client::expr::unary_not().
Referenced by Slic3r::client::macro_processor::macro_processor().
round()
static void Slic3r::client::FactorActions::round (expr & value, expr & out) inline static
                { out = value.round(out.it_range.begin()); }
References Slic3r::client::expr::it_range, and Slic3r::client::expr::round().
Referenced by Slic3r::client::macro_processor::macro_processor().
set_start_pos()
static void Slic3r::client::FactorActions::set_start_pos (Iterator & start_pos, expr & out) inline static
                { out.it_range = IteratorRange(start_pos, start_pos); }
References Slic3r::client::expr::it_range.
Referenced by Slic3r::client::macro_processor::macro_processor().
string_()
static void Slic3r::client::FactorActions::string_ (const MyContext * ctx, IteratorRange & it_range, expr & out) inline static
{
            if (ctx->skipping()) {
                out.reset();
                out.it_range = it_range;
            } else {
                // Unescape the string, UTF-8 safe.
                std::string s;
                auto        begin = std::next(it_range.begin());
                auto        end   = std::prev(it_range.end());
                assert(begin <= end);
                {
                    // 1) Get the size of the string after unescaping.
                    size_t len = 0;
                    for (auto it = begin; it != end;) {
                        if (*it == '\\') {
                            if (++ it == end ||
                                (*it != 'r' && *it != 'n' && *it != '"' && *it != '\\'))
                                ctx->throw_exception("Invalid escape sequence", {std::prev(it), std::next(it) });
                            ++ len;
                            ++ it;
                        } else {
                            size_t n = get_utf8_sequence_length(&*it, end - it);
                            len += n;
                            it  += n;
                        }
                    }
                    // and reserve the string.
                    s.reserve(len);
                }
                // 2) Copy & unescape the string.
                for (auto it = begin; it != end;) {
                    if (*it == '\\') {
                        char c = *(++ it);
                        if (c == 'r')
                            c = '\r';
                        else if (c == 'n')
                            c = '\n';
                        s += c;
                        ++ it;
                    } else {
                        size_t n = get_utf8_sequence_length(&*it, end - it);
                        s.append(&*it, n);
                        it += n;
                    }
                }
                out = expr(std::move(s), it_range.begin(), it_range.end());
            }
        }
References Slic3r::get_utf8_sequence_length(), Slic3r::client::expr::it_range, Slic3r::client::expr::reset(), Slic3r::client::MyContext::skipping(), and Slic3r::client::MyContext::throw_exception().
Referenced by Slic3r::client::macro_processor::macro_processor().
to_int()
static void Slic3r::client::FactorActions::to_int (expr & value, expr & out) inline static
                { out = value.unary_integer(out.it_range.begin()); }
References Slic3r::client::expr::it_range, and Slic3r::client::expr::unary_integer().
Referenced by Slic3r::client::macro_processor::macro_processor().
The documentation for this struct was generated from the following file:
src/libslic3r/PlaceholderParser.cpp