Prusa Slicer: Eigen::ColPivHouseholderQR< _MatrixType > Class Template Reference
Eigen::ColPivHouseholderQR< _MatrixType > Class Template Reference
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
#include <src/eigen/Eigen/src/QR/ColPivHouseholderQR.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime > PermutationType
typedef internal::plain_row_type< MatrixType, Index >::type IntRowVectorType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef internal::plain_row_type< MatrixType, RealScalar >::type RealRowVectorType
typedef HouseholderSequence< MatrixType, typename internal::remove_all< typename HCoeffsType::ConjugateReturnType >::type > HouseholderSequenceType
typedef MatrixType::PlainObject PlainObject
Public Member Functions
ColPivHouseholderQR ()
Default Constructor.
ColPivHouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
ColPivHouseholderQR (const EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename InputType >
ColPivHouseholderQR (EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename Rhs >
const Solve< ColPivHouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
HouseholderSequenceType householderQ () const
HouseholderSequenceType matrixQ () const
const MatrixType & matrixQR () const
const MatrixType & matrixR () const
template<typename InputType >
ColPivHouseholderQR & compute (const EigenBase< InputType > &matrix)
const PermutationType & colsPermutation () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< ColPivHouseholderQR > inverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
ColPivHouseholderQR & setThreshold (const RealScalar &threshold)
ColPivHouseholderQR & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
ComputationInfo info () const
Reports whether the QR factorization was succesful.
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename InputType >
ColPivHouseholderQR< MatrixType > & compute (const EigenBase< InputType > &matrix)
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
Protected Member Functions
void computeInPlace ()
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
PermutationType m_colsPermutation
IntRowVectorType m_colsTranspositions
RowVectorType m_temp
RealRowVectorType m_colNormsUpdated
RealRowVectorType m_colNormsDirect
bool m_isInitialized
bool m_usePrescribedThreshold
RealScalar m_prescribedThreshold
RealScalar m_maxpivot
Index m_nonzero_pivots
Index m_det_pq
Private Types
typedef PermutationType::StorageIndex PermIndexType
Friends
class CompleteOrthogonalDecomposition< MatrixType >
Detailed Description
template<typename _MatrixType>
class Eigen::ColPivHouseholderQR< _MatrixType >
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
Template Parameters
_MatrixType the type of the matrix of which we are computing the QR decomposition
This class performs a rank-revealing QR decomposition of a matrix A into matrices P, Q and R such that
by using Householder transformations. Here, P is a permutation matrix, Q a unitary matrix and R an upper triangular matrix.
This decomposition performs column pivoting in order to be rank-revealing and improve numerical stability. It is slower than HouseholderQR, and faster than FullPivHouseholderQR.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::colPivHouseholderQr()
Member Typedef Documentation
HCoeffsType
template<typename _MatrixType > typedef internal::plain_diag_type<MatrixType>::type Eigen::ColPivHouseholderQR< _MatrixType >::HCoeffsType
HouseholderSequenceType
template<typename _MatrixType > typedef HouseholderSequence<MatrixType,typename internal::remove_all<typename HCoeffsType::ConjugateReturnType>::type> Eigen::ColPivHouseholderQR< _MatrixType >::HouseholderSequenceType
IntRowVectorType
template<typename _MatrixType > typedef internal::plain_row_type<MatrixType,Index>::type Eigen::ColPivHouseholderQR< _MatrixType >::IntRowVectorType
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::ColPivHouseholderQR< _MatrixType >::MatrixType
PermIndexType
template<typename _MatrixType > typedef PermutationType::StorageIndex Eigen::ColPivHouseholderQR< _MatrixType >::PermIndexType private
PermutationType
template<typename _MatrixType > typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::ColPivHouseholderQR< _MatrixType >::PermutationType
PlainObject
template<typename _MatrixType > typedef MatrixType::PlainObject Eigen::ColPivHouseholderQR< _MatrixType >::PlainObject
RealRowVectorType
template<typename _MatrixType > typedef internal::plain_row_type<MatrixType,RealScalar>::type Eigen::ColPivHouseholderQR< _MatrixType >::RealRowVectorType
RealScalar
template<typename _MatrixType > typedef MatrixType::RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::RealScalar
RowVectorType
template<typename _MatrixType > typedef internal::plain_row_type<MatrixType>::type Eigen::ColPivHouseholderQR< _MatrixType >::RowVectorType
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::ColPivHouseholderQR< _MatrixType >::Scalar
StorageIndex
template<typename _MatrixType > typedef MatrixType::StorageIndex Eigen::ColPivHouseholderQR< _MatrixType >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
         {
      RowsAtCompileTime = MatrixType::RowsAtCompileTime,
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
ColPivHouseholderQR() [1/4]
template<typename _MatrixType > Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via ColPivHouseholderQR::compute(const MatrixType&).
      : m_qr(),
        m_hCoeffs(),
        m_colsPermutation(),
        m_colsTranspositions(),
        m_temp(),
        m_colNormsUpdated(),
        m_colNormsDirect(),
        m_isInitialized(false),
        m_usePrescribedThreshold(false) {}
ColPivHouseholderQR() [2/4]
template<typename _MatrixType > Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
ColPivHouseholderQR()
      : m_qr(rows, cols),
        m_hCoeffs((std::min)(rows,cols)),
        m_colsPermutation(PermIndexType(cols)),
        m_colsTranspositions(cols),
        m_temp(cols),
        m_colNormsUpdated(cols),
        m_colNormsDirect(cols),
        m_isInitialized(false),
        m_usePrescribedThreshold(false) {}
ColPivHouseholderQR() [3/4]
template<typename _MatrixType > template<typename InputType > Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR (const EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This constructor computes the QR factorization of the matrix matrix by calling the method compute(). It is a short cut for:
ColPivHouseholderQR<MatrixType> qr(matrix.rows(), matrix.cols());
qr.compute(matrix);
See also
compute()
      : m_qr(matrix.rows(), matrix.cols()),
        m_hCoeffs((std::min)(matrix.rows(),matrix.cols())),
        m_colsPermutation(PermIndexType(matrix.cols())),
        m_colsTranspositions(matrix.cols()),
        m_temp(matrix.cols()),
        m_colNormsUpdated(matrix.cols()),
        m_colNormsDirect(matrix.cols()),
        m_isInitialized(false),
        m_usePrescribedThreshold(false)
    {
      compute(matrix.derived());
    }
References Eigen::ColPivHouseholderQR< _MatrixType >::compute(), and Eigen::EigenBase< Derived >::derived().
ColPivHouseholderQR() [4/4]
template<typename _MatrixType > template<typename InputType > Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR (EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
ColPivHouseholderQR(const EigenBase&)
      : m_qr(matrix.derived()),
        m_hCoeffs((std::min)(matrix.rows(),matrix.cols())),
        m_colsPermutation(PermIndexType(matrix.cols())),
        m_colsTranspositions(matrix.cols()),
        m_temp(matrix.cols()),
        m_colNormsUpdated(matrix.cols()),
        m_colNormsDirect(matrix.cols()),
        m_isInitialized(false),
        m_usePrescribedThreshold(false)
    {
      computeInPlace();
    }
References Eigen::ColPivHouseholderQR< _MatrixType >::computeInPlace().
Member Function Documentation
_solve_impl() [1/2]
template<typename _MatrixType > template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::ColPivHouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
_solve_impl() [2/2]
template<typename _MatrixType > template<typename RhsType , typename DstType > void Eigen::ColPivHouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
  eigen_assert(rhs.rows() == rows());
  const Index nonzero_pivots = nonzeroPivots();
  if(nonzero_pivots == 0)
  {
    dst.setZero();
    return;
  }
  typename RhsType::PlainObject c(rhs);
  // Note that the matrix Q = H_0^* H_1^*... so its inverse is Q^* = (H_0 H_1 ...)^T
  c.applyOnTheLeft(householderSequence(m_qr, m_hCoeffs)
                    .setLength(nonzero_pivots)
                    .transpose()
    );
  m_qr.topLeftCorner(nonzero_pivots, nonzero_pivots)
      .template triangularView<Upper>()
      .solveInPlace(c.topRows(nonzero_pivots));
  for(Index i = 0; i < nonzero_pivots; ++i) dst.row(m_colsPermutation.indices().coeff(i)) = c.row(i);
  for(Index i = nonzero_pivots; i < cols(); ++i) dst.row(m_colsPermutation.indices().coeff(i)).setZero();
}
References eigen_assert, and Eigen::householderSequence().
absDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::ColPivHouseholderQR< MatrixType >::absDeterminant
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
logAbsDeterminant(), MatrixBase::determinant()
{
  using std::abs;
  eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
  eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
  return abs(m_qr.diagonal().prod());
}
References eigen_assert.
check_template_parameters()
template<typename _MatrixType > static void Eigen::ColPivHouseholderQR< _MatrixType >::check_template_parameters () inline static protected
    {
      EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
    }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
cols()
template<typename _MatrixType > Index Eigen::ColPivHouseholderQR< _MatrixType >::cols () const inline
{ return m_qr.cols(); }
References Eigen::ColPivHouseholderQR< _MatrixType >::m_qr.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::cols(), Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixZ().
colsPermutation()
template<typename _MatrixType > const PermutationType & Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation () const inline
Returns
a const reference to the column permutation matrix
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return m_colsPermutation;
    }
References eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_colsPermutation, and Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::colsPermutation().
compute() [1/2]
template<typename _MatrixType > template<typename InputType > ColPivHouseholderQR & Eigen::ColPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::compute().
compute() [2/2]
template<typename _MatrixType > template<typename InputType > ColPivHouseholderQR< MatrixType > & Eigen::ColPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
Performs the QR factorization of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class ColPivHouseholderQR, ColPivHouseholderQR(const MatrixType&)
{
  m_qr = matrix.derived();
  computeInPlace();
  return *this;
}
References Eigen::EigenBase< Derived >::derived().
computeInPlace()
template<typename MatrixType > void Eigen::ColPivHouseholderQR< MatrixType >::computeInPlace protected
{
  check_template_parameters();
  // the column permutation is stored as int indices, so just to be sure:
  eigen_assert(m_qr.cols()<=NumTraits<int>::highest());
  using std::abs;
  Index rows = m_qr.rows();
  Index cols = m_qr.cols();
  Index size = m_qr.diagonalSize();
  m_hCoeffs.resize(size);
  m_temp.resize(cols);
  m_colsTranspositions.resize(m_qr.cols());
  Index number_of_transpositions = 0;
  m_colNormsUpdated.resize(cols);
  m_colNormsDirect.resize(cols);
  for (Index k = 0; k < cols; ++k) {
    // colNormsDirect(k) caches the most recent directly computed norm of
    // column k.
    m_colNormsDirect.coeffRef(k) = m_qr.col(k).norm();
    m_colNormsUpdated.coeffRef(k) = m_colNormsDirect.coeffRef(k);
  }
  RealScalar threshold_helper =  numext::abs2<RealScalar>(m_colNormsUpdated.maxCoeff() * NumTraits<RealScalar>::epsilon()) / RealScalar(rows);
  RealScalar norm_downdate_threshold = numext::sqrt(NumTraits<RealScalar>::epsilon());
  m_nonzero_pivots = size; // the generic case is that in which all pivots are nonzero (invertible case)
  m_maxpivot = RealScalar(0);
  for(Index k = 0; k < size; ++k)
  {
    // first, we look up in our table m_colNormsUpdated which column has the biggest norm
    Index biggest_col_index;
    RealScalar biggest_col_sq_norm = numext::abs2(m_colNormsUpdated.tail(cols-k).maxCoeff(&biggest_col_index));
    biggest_col_index += k;
    // Track the number of meaningful pivots but do not stop the decomposition to make
    // sure that the initial matrix is properly reproduced. See bug 941.
    if(m_nonzero_pivots==size && biggest_col_sq_norm < threshold_helper * RealScalar(rows-k))
      m_nonzero_pivots = k;
    // apply the transposition to the columns
    m_colsTranspositions.coeffRef(k) = biggest_col_index;
    if(k != biggest_col_index) {
      m_qr.col(k).swap(m_qr.col(biggest_col_index));
      std::swap(m_colNormsUpdated.coeffRef(k), m_colNormsUpdated.coeffRef(biggest_col_index));
      std::swap(m_colNormsDirect.coeffRef(k), m_colNormsDirect.coeffRef(biggest_col_index));
      ++number_of_transpositions;
    }
    // generate the householder vector, store it below the diagonal
    RealScalar beta;
    m_qr.col(k).tail(rows-k).makeHouseholderInPlace(m_hCoeffs.coeffRef(k), beta);
    // apply the householder transformation to the diagonal coefficient
    m_qr.coeffRef(k,k) = beta;
    // remember the maximum absolute value of diagonal coefficients
    if(abs(beta) > m_maxpivot) m_maxpivot = abs(beta);
    // apply the householder transformation
    m_qr.bottomRightCorner(rows-k, cols-k-1)
        .applyHouseholderOnTheLeft(m_qr.col(k).tail(rows-k-1), m_hCoeffs.coeffRef(k), &m_temp.coeffRef(k+1));
    // update our table of norms of the columns
    for (Index j = k + 1; j < cols; ++j) {
      // The following implements the stable norm downgrade step discussed in
      // http://www.netlib.org/lapack/lawnspdf/lawn176.pdf
      // and used in LAPACK routines xGEQPF and xGEQP3.
      // See lines 278-297 in http://www.netlib.org/lapack/explore-html/dc/df4/sgeqpf_8f_source.html
      if (m_colNormsUpdated.coeffRef(j) != RealScalar(0)) {
        RealScalar temp = abs(m_qr.coeffRef(k, j)) / m_colNormsUpdated.coeffRef(j);
        temp = (RealScalar(1) + temp) * (RealScalar(1) - temp);
        temp = temp <  RealScalar(0) ? RealScalar(0) : temp;
        RealScalar temp2 = temp * numext::abs2<RealScalar>(m_colNormsUpdated.coeffRef(j) /
                                                           m_colNormsDirect.coeffRef(j));
        if (temp2 <= norm_downdate_threshold) {
          // The updated norm has become too inaccurate so re-compute the column
          // norm directly.
          m_colNormsDirect.coeffRef(j) = m_qr.col(j).tail(rows - k - 1).norm();
          m_colNormsUpdated.coeffRef(j) = m_colNormsDirect.coeffRef(j);
        } else {
          m_colNormsUpdated.coeffRef(j) *= numext::sqrt(temp);
        }
      }
    }
  }
  m_colsPermutation.setIdentity(PermIndexType(cols));
  for(PermIndexType k = 0; k < size/*m_nonzero_pivots*/; ++k)
    m_colsPermutation.applyTranspositionOnTheRight(k, PermIndexType(m_colsTranspositions.coeff(k)));
  m_det_pq = (number_of_transpositions%2) ? -1 : 1;
  m_isInitialized = true;
}
References eigen_assert, and Eigen::numext::sqrt().
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR().
dimensionOfKernel()
template<typename _MatrixType > Index Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return cols() - rank();
    }
References Eigen::ColPivHouseholderQR< _MatrixType >::cols(), eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::ColPivHouseholderQR< _MatrixType >::rank().
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::dimensionOfKernel().
hCoeffs()
template<typename _MatrixType > const HCoeffsType & Eigen::ColPivHouseholderQR< _MatrixType >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
{ return m_hCoeffs; }
References Eigen::ColPivHouseholderQR< _MatrixType >::m_hCoeffs.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::hCoeffs().
householderQ()
template<typename MatrixType > ColPivHouseholderQR< MatrixType >::HouseholderSequenceType Eigen::ColPivHouseholderQR< MatrixType >::householderQ
Returns
the matrix Q as a sequence of householder transformations. You can extract the meaningful part only by using:
qr.householderQ().setLength(qr.nonzeroPivots())
{
  eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
  return HouseholderSequenceType(m_qr, m_hCoeffs.conjugate());
}
References eigen_assert.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::matrixQ(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixQ().
info()
template<typename _MatrixType > ComputationInfo Eigen::ColPivHouseholderQR< _MatrixType >::info () const inline
Reports whether the QR factorization was succesful.
Note
This function always returns Success. It is provided for compatibility with other factorization routines.
Returns
Success
    {
      eigen_assert(m_isInitialized && "Decomposition is not initialized.");
      return Success;
    }
References eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::Success.
inverse()
template<typename _MatrixType > const Inverse< ColPivHouseholderQR > Eigen::ColPivHouseholderQR< _MatrixType >::inverse () const inline
Returns
the inverse of the matrix of which *this is the QR decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return Inverse<ColPivHouseholderQR>(*this);
    }
References eigen_assert, and Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized.
isInjective()
template<typename _MatrixType > bool Eigen::ColPivHouseholderQR< _MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return rank() == cols();
    }
References Eigen::ColPivHouseholderQR< _MatrixType >::cols(), eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::ColPivHouseholderQR< _MatrixType >::rank().
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInjective(), and Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible().
isInvertible()
template<typename _MatrixType > bool Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the QR decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return isInjective() && isSurjective();
    }
References eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective(), and Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInvertible().
isSurjective()
template<typename _MatrixType > bool Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return rank() == rows();
    }
References eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, Eigen::ColPivHouseholderQR< _MatrixType >::rank(), and Eigen::ColPivHouseholderQR< _MatrixType >::rows().
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isSurjective().
logAbsDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::ColPivHouseholderQR< MatrixType >::logAbsDeterminant
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
absDeterminant(), MatrixBase::determinant()
{
  eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
  eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
  return m_qr.diagonal().cwiseAbs().array().log().sum();
}
References eigen_assert.
matrixQ()
template<typename _MatrixType > HouseholderSequenceType Eigen::ColPivHouseholderQR< _MatrixType >::matrixQ () const inline
    {
      return householderQ();
    }
References Eigen::ColPivHouseholderQR< _MatrixType >::householderQ().
matrixQR()
template<typename _MatrixType > const MatrixType & Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return m_qr;
    }
References eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::ColPivHouseholderQR< _MatrixType >::m_qr.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixQTZ(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixT().
matrixR()
template<typename _MatrixType > const MatrixType & Eigen::ColPivHouseholderQR< _MatrixType >::matrixR () const inline
Returns
a reference to the matrix where the result Householder QR is stored
Warning
The strict lower part of this matrix contains internal values. Only the upper triangular part should be referenced. To get it, use
matrixR().template triangularView<Upper>()
For rank-deficient matrices, use
matrixR().topLeftCorner(rank(), rank()).template triangularView<Upper>()
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return m_qr;
    }
References eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::ColPivHouseholderQR< _MatrixType >::m_qr.
maxPivot()
template<typename _MatrixType > RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of R.
{ return m_maxpivot; }
References Eigen::ColPivHouseholderQR< _MatrixType >::m_maxpivot.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::maxPivot().
nonzeroPivots()
template<typename _MatrixType > Index Eigen::ColPivHouseholderQR< _MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the QR decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return m_nonzero_pivots;
    }
References eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::ColPivHouseholderQR< _MatrixType >::m_nonzero_pivots.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::nonzeroPivots().
rank()
template<typename _MatrixType > Index Eigen::ColPivHouseholderQR< _MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      using std::abs;
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      RealScalar premultiplied_threshold = abs(m_maxpivot) * threshold();
      Index result = 0;
      for(Index i = 0; i < m_nonzero_pivots; ++i)
        result += (abs(m_qr.coeff(i,i)) > premultiplied_threshold);
      return result;
    }
References eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, Eigen::ColPivHouseholderQR< _MatrixType >::m_maxpivot, Eigen::ColPivHouseholderQR< _MatrixType >::m_nonzero_pivots, Eigen::ColPivHouseholderQR< _MatrixType >::m_qr, and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rank().
rows()
template<typename _MatrixType > Index Eigen::ColPivHouseholderQR< _MatrixType >::rows () const inline
{ return m_qr.rows(); }
References Eigen::ColPivHouseholderQR< _MatrixType >::m_qr.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rows().
setThreshold() [1/2]
template<typename _MatrixType > ColPivHouseholderQR & Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the QR decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
    {
      m_usePrescribedThreshold = true;
      m_prescribedThreshold = threshold;
      return *this;
    }
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold().
setThreshold() [2/2]
template<typename _MatrixType > ColPivHouseholderQR & Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
    {
      m_usePrescribedThreshold = false;
      return *this;
    }
References Eigen::ColPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold.
solve()
template<typename _MatrixType > template<typename Rhs > const Solve< ColPivHouseholderQR, Rhs > Eigen::ColPivHouseholderQR< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method finds a solution x to the equation Ax=b, where A is the matrix of which *this is the QR decomposition, if any exists.
Parameters
b the right-hand-side of the equation to solve.
Returns
a solution.
\note_about_checking_solutions
\note_about_arbitrary_choice_of_solution
Example:
Output:
    {
      eigen_assert(m_isInitialized && "ColPivHouseholderQR is not initialized.");
      return Solve<ColPivHouseholderQR, Rhs>(*this, b.derived());
    }
References eigen_assert, and Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized.
Referenced by igl::mvc().
threshold()
template<typename _MatrixType > RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized || m_usePrescribedThreshold);
      return m_usePrescribedThreshold ? m_prescribedThreshold
      // this formula comes from experimenting (see "LU precision tuning" thread on the list)
      // and turns out to be identical to Higham's formula used already in LDLt.
                                      : NumTraits<Scalar>::epsilon() * RealScalar(m_qr.diagonalSize());
    }
References eigen_assert, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, Eigen::ColPivHouseholderQR< _MatrixType >::m_prescribedThreshold, Eigen::ColPivHouseholderQR< _MatrixType >::m_qr, and Eigen::ColPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold.
Referenced by Eigen::MatrixBase< Homogeneous< MatrixType, _Direction > >::colPivHouseholderQr(), Eigen::ColPivHouseholderQR< _MatrixType >::rank(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::threshold().
Friends And Related Symbol Documentation
CompleteOrthogonalDecomposition< MatrixType >
template<typename _MatrixType > friend class CompleteOrthogonalDecomposition< MatrixType > friend
Member Data Documentation
m_colNormsDirect
template<typename _MatrixType > RealRowVectorType Eigen::ColPivHouseholderQR< _MatrixType >::m_colNormsDirect protected
m_colNormsUpdated
template<typename _MatrixType > RealRowVectorType Eigen::ColPivHouseholderQR< _MatrixType >::m_colNormsUpdated protected
m_colsPermutation
template<typename _MatrixType > PermutationType Eigen::ColPivHouseholderQR< _MatrixType >::m_colsPermutation protected
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation().
m_colsTranspositions
template<typename _MatrixType > IntRowVectorType Eigen::ColPivHouseholderQR< _MatrixType >::m_colsTranspositions protected
m_det_pq
template<typename _MatrixType > Index Eigen::ColPivHouseholderQR< _MatrixType >::m_det_pq protected
m_hCoeffs
template<typename _MatrixType > HCoeffsType Eigen::ColPivHouseholderQR< _MatrixType >::m_hCoeffs protected
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::hCoeffs().
m_isInitialized
template<typename _MatrixType > bool Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized protected
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation(), Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< _MatrixType >::info(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::info(), Eigen::ColPivHouseholderQR< _MatrixType >::inverse(), Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible(), Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective(), Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), Eigen::ColPivHouseholderQR< _MatrixType >::matrixR(), Eigen::ColPivHouseholderQR< _MatrixType >::nonzeroPivots(), Eigen::ColPivHouseholderQR< _MatrixType >::rank(), Eigen::ColPivHouseholderQR< _MatrixType >::solve(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::solve(), and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
m_maxpivot
template<typename _MatrixType > RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::m_maxpivot protected
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::maxPivot(), and Eigen::ColPivHouseholderQR< _MatrixType >::rank().
m_nonzero_pivots
template<typename _MatrixType > Index Eigen::ColPivHouseholderQR< _MatrixType >::m_nonzero_pivots protected
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::nonzeroPivots(), and Eigen::ColPivHouseholderQR< _MatrixType >::rank().
m_prescribedThreshold
template<typename _MatrixType > RealScalar Eigen::ColPivHouseholderQR< _MatrixType >::m_prescribedThreshold protected
Referenced by Eigen::MatrixBase< Homogeneous< MatrixType, _Direction > >::colPivHouseholderQr(), and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
m_qr
template<typename _MatrixType > MatrixType Eigen::ColPivHouseholderQR< _MatrixType >::m_qr protected
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::cols(), Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), Eigen::ColPivHouseholderQR< _MatrixType >::matrixR(), Eigen::ColPivHouseholderQR< _MatrixType >::rank(), Eigen::ColPivHouseholderQR< _MatrixType >::rows(), and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
m_temp
template<typename _MatrixType > RowVectorType Eigen::ColPivHouseholderQR< _MatrixType >::m_temp protected
m_usePrescribedThreshold
template<typename _MatrixType > bool Eigen::ColPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold protected
Referenced by Eigen::MatrixBase< Homogeneous< MatrixType, _Direction > >::colPivHouseholderQr(), Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold(), and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/util/ForwardDeclarations.h
src/eigen/Eigen/src/QR/ColPivHouseholderQR.h