Prusa Slicer: src/avrdude/ft245r.c File Reference
ft245r.c File Reference
#include "ac_cfg.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <sys/time.h>
#include <unistd.h>
#include <stdint.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "bitbang.h"
#include "ft245r.h"
#include "usbdevs.h"
Macros
#define DO_NOT_BUILD_FT245R
Functions
static int ft245r_nopthread_open (struct programmer_t *pgm, char *name)
void ft245r_initpgm (PROGRAMMER *pgm)
Variables
const char ft245r_desc [] = "FT245R/FT232R Synchronous BitBangMode Programmer"
Macro Definition Documentation
DO_NOT_BUILD_FT245R
#define DO_NOT_BUILD_FT245R
Function Documentation
ft245r_initpgm()
void ft245r_initpgm (PROGRAMMER * pgm)
{
    strcpy(pgm->type, "ftdi_syncbb");
    pgm->open = ft245r_nopthread_open;
}
References ft245r_nopthread_open(), programmer_t::open, pgm, and programmer_t::type.
ft245r_nopthread_open()
static int ft245r_nopthread_open (struct programmer_t * pgm, char * name) static
{
    avrdude_message(MSG_INFO, "%s: error: no pthread support. Please compile again with pthread installed."
#if defined(_WIN32)
            " See http://sourceware.org/pthreads-win32/."
#endif
            "\n",
            progname);
    return -1;
}
References avrdude_message(), MSG_INFO, and progname.
Referenced by ft245r_initpgm().
Variable Documentation
ft245r_desc
const char ft245r_desc[] = "FT245R/FT232R Synchronous BitBangMode Programmer"