Prusa Slicer: Slic3r::EdgeGrid::Contour Class Reference
Slic3r::EdgeGrid::Contour Class Reference
#include <src/libslic3r/EdgeGrid.hpp>
Public Member Functions
Contour ()=default
Contour (const Slic3r::Point *begin, const Slic3r::Point *end, bool open)
Contour (const Slic3r::Point *data, size_t size, bool open)
Contour (const Points &pts, bool open)
const Slic3r::Point * begin () const
const Slic3r::Point * end () const
bool open () const
bool closed () const
const Slic3r::Point & front () const
const Slic3r::Point & back () const
const Slic3r::Point & segment_start (size_t idx) const
const Slic3r::Point & segment_end (size_t idx) const
const Slic3r::Point & segment_prev (size_t idx) const
const size_t segment_idx_prev (size_t idx) const
const size_t segment_idx_next (size_t idx) const
size_t num_segments () const
Line get_segment (size_t idx) const
Lines get_segments () const
Private Member Functions
size_t size () const
Private Attributes
const Slic3r::Point * m_begin { nullptr }
const Slic3r::Point * m_end { nullptr }
bool m_open { false }
Detailed Description
Constructor & Destructor Documentation
Contour() [1/4]
Slic3r::EdgeGrid::Contour::Contour () default
Contour() [2/4]
Slic3r::EdgeGrid::Contour::Contour (const Slic3r::Point * begin, const Slic3r::Point * end, bool open) inline
: m_begin(begin), m_end(end), m_open(open) {}
Contour() [3/4]
Slic3r::EdgeGrid::Contour::Contour (const Slic3r::Point * data, size_t size, bool open) inline
: Contour(data, data + size, open) {}
Contour() [4/4]
Slic3r::EdgeGrid::Contour::Contour (const Points & pts, bool open) inline
: Contour(pts.data(), pts.size(), open) {}
Member Function Documentation
back()
const Slic3r::Point & Slic3r::EdgeGrid::Contour::back () const inline
{ return *(m_end - 1); }
References m_end.
Referenced by get_segments().
begin()
const Slic3r::Point * Slic3r::EdgeGrid::Contour::begin () const inline
{ return m_begin; }
References m_begin.
Referenced by get_segments().
closed()
bool Slic3r::EdgeGrid::Contour::closed () const inline
{ return !m_open; }
References m_open.
end()
const Slic3r::Point * Slic3r::EdgeGrid::Contour::end () const inline
{ return m_end; }
References m_end.
Referenced by get_segments().
front()
const Slic3r::Point & Slic3r::EdgeGrid::Contour::front () const inline
{ return *m_begin; }
References m_begin.
Referenced by get_segments().
get_segment()
Line Slic3r::EdgeGrid::Contour::get_segment (size_t idx) const inline
    {
        assert(idx < this->num_segments());
        return Line(this->segment_start(idx), this->segment_end(idx));
    }
References num_segments(), segment_end(), and segment_start().
get_segments()
Lines Slic3r::EdgeGrid::Contour::get_segments () const inline
    {
        Lines lines;
        lines.reserve(this->num_segments());
        if (this->num_segments() > 2) {
            for (auto it = this->begin(); it != this->end() - 1; ++it) lines.push_back(Line(*it, *(it + 1)));
            if (!m_open) lines.push_back(Line(this->back(), this->front()));
        }
        return lines;
    }
References back(), begin(), end(), front(), m_open, and num_segments().
num_segments()
size_t Slic3r::EdgeGrid::Contour::num_segments () const inline
{ return this->size() - (m_open ? 1 : 0); }
References m_open, and size().
Referenced by get_segment(), get_segments(), segment_end(), segment_idx_next(), segment_idx_prev(), segment_prev(), and segment_start().
open()
bool Slic3r::EdgeGrid::Contour::open () const inline
{ return m_open; }
References m_open.
segment_end()
const Slic3r::Point & Slic3r::EdgeGrid::Contour::segment_end (size_t idx) const inline
{
    assert(idx < this->num_segments());
    const Slic3r::Point *ptr = m_begin + idx + 1;
    return ptr == m_end ? *m_begin : *ptr;
  }
References m_begin, m_end, and num_segments().
Referenced by get_segment(), Slic3r::EdgeGrid::Grid::has_intersecting_edges(), and Slic3r::EdgeGrid::Grid::intersecting_edges().
segment_idx_next()
const size_t Slic3r::EdgeGrid::Contour::segment_idx_next (size_t idx) const inline
{
    assert(idx < this->num_segments());
    ++ idx;
    return m_begin + idx == m_end ? 0 : idx;
  }
References m_begin, m_end, and num_segments().
segment_idx_prev()
const size_t Slic3r::EdgeGrid::Contour::segment_idx_prev (size_t idx) const inline
{
    assert(idx < this->num_segments());
    assert(idx > 0 || ! m_open);
    return (idx == 0 ? this->size() : idx) - 1;
  }
References m_open, num_segments(), and size().
segment_prev()
const Slic3r::Point & Slic3r::EdgeGrid::Contour::segment_prev (size_t idx) const inline
{
    assert(idx < this->num_segments());
    assert(idx > 0 || ! m_open);
    return idx == 0 ? m_end[-1] : m_begin[idx - 1];
  }
References m_begin, m_end, m_open, and num_segments().
segment_start()
const Slic3r::Point & Slic3r::EdgeGrid::Contour::segment_start (size_t idx) const inline
{
    assert(idx < this->num_segments());
    return m_begin[idx];
  }
References m_begin, and num_segments().
Referenced by get_segment(), Slic3r::EdgeGrid::Grid::has_intersecting_edges(), and Slic3r::EdgeGrid::Grid::intersecting_edges().
size()
size_t Slic3r::EdgeGrid::Contour::size () const inline private
{ return m_end - m_begin; }
References m_begin, and m_end.
Referenced by num_segments(), and segment_idx_prev().
Member Data Documentation
m_begin
const Slic3r::Point* Slic3r::EdgeGrid::Contour::m_begin { nullptr } private
Referenced by begin(), front(), segment_end(), segment_idx_next(), segment_prev(), segment_start(), and size().
m_end
const Slic3r::Point* Slic3r::EdgeGrid::Contour::m_end { nullptr } private
Referenced by back(), end(), segment_end(), segment_idx_next(), segment_prev(), and size().
m_open
bool Slic3r::EdgeGrid::Contour::m_open { false } private
Referenced by closed(), get_segments(), num_segments(), open(), segment_idx_prev(), and segment_prev().
The documentation for this class was generated from the following file:
src/libslic3r/EdgeGrid.hpp