Prusa Slicer: hidapi API
hidapi API
Functions
int HID_API_EXPORT HID_API_CALL hid_init (void)
Initialize the HIDAPI library.
int HID_API_EXPORT HID_API_CALL hid_exit (void)
Finalize the HIDAPI library.
struct hid_device_info HID_API_EXPORT *HID_API_CALL hid_enumerate (unsigned short vendor_id, unsigned short product_id)
Enumerate the HID Devices.
void HID_API_EXPORT HID_API_CALL hid_free_enumeration (struct hid_device_info *devs)
Free an enumeration Linked List.
HID_API_EXPORT hid_device *HID_API_CALL hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t *serial_number)
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
HID_API_EXPORT hid_device *HID_API_CALL hid_open_path (const char *path)
Open a HID device by its path name.
int HID_API_EXPORT HID_API_CALL hid_write (hid_device *dev, const unsigned char *data, size_t length)
Write an Output report to a HID device.
int HID_API_EXPORT HID_API_CALL hid_read_timeout (hid_device *dev, unsigned char *data, size_t length, int milliseconds)
Read an Input report from a HID device with timeout.
int HID_API_EXPORT HID_API_CALL hid_read (hid_device *dev, unsigned char *data, size_t length)
Read an Input report from a HID device.
int HID_API_EXPORT HID_API_CALL hid_set_nonblocking (hid_device *dev, int nonblock)
Set the device handle to be non-blocking.
int HID_API_EXPORT HID_API_CALL hid_send_feature_report (hid_device *dev, const unsigned char *data, size_t length)
Send a Feature report to the device.
int HID_API_EXPORT HID_API_CALL hid_get_feature_report (hid_device *dev, unsigned char *data, size_t length)
Get a feature report from a HID device.
void HID_API_EXPORT HID_API_CALL hid_close (hid_device *dev)
Close a HID device.
int HID_API_EXPORT_CALL hid_get_manufacturer_string (hid_device *dev, wchar_t *string, size_t maxlen)
Get The Manufacturer String from a HID device.
int HID_API_EXPORT_CALL hid_get_product_string (hid_device *dev, wchar_t *string, size_t maxlen)
Get The Product String from a HID device.
int HID_API_EXPORT_CALL hid_get_serial_number_string (hid_device *dev, wchar_t *string, size_t maxlen)
Get The Serial Number String from a HID device.
int HID_API_EXPORT_CALL hid_get_indexed_string (hid_device *dev, int string_index, wchar_t *string, size_t maxlen)
Get a string from a HID device, based on its string index.
HID_API_EXPORT const wchar_t *HID_API_CALL hid_error (hid_device *dev)
Get a string describing the last error which occurred.
Detailed Description
Function Documentation
hid_close()
void HID_API_EXPORT HID_API_CALL hid_close (hid_device * dev)
#include <src/hidapi/include/hidapi.h>
Close a HID device.
Parameters
dev A device handle returned from hid_open().
{
  if (!dev)
    return;
  close(dev->device_handle);
  free(dev);
}
References hid_device_::device_handle, hid_device_::disconnected, free(), free_hid_device(), hid_device_::input_report_buf, hid_device_::input_reports, hid_device_::max_input_report_len, hid_device_::mutex, pthread_barrier_wait(), return_data(), hid_device_::run_loop, hid_device_::run_loop_mode, hid_device_::shutdown_barrier, hid_device_::shutdown_thread, hid_device_::source, and hid_device_::thread.
Referenced by Slic3r::GUI::Mouse3DController::connect_device(), and Slic3r::GUI::Mouse3DController::disconnect_device().
hid_enumerate()
struct hid_device_info HID_API_EXPORT *HID_API_CALL hid_enumerate (unsigned short vendor_id, unsigned short product_id)
#include <src/hidapi/include/hidapi.h>
Enumerate the HID Devices.
This function returns a linked list of all the HID devices attached to the system which match vendor_id and product_id. If vendor_id is set to 0 then any vendor matches. If product_id is set to 0 then any product matches. If vendor_id and product_id are both set to 0, then all HID devices will be returned.
Parameters
vendor_id The Vendor ID (VID) of the types of device to open.
product_id The Product ID (PID) of the types of device to open.
Returns
This function returns a pointer to a linked list of type struct hid_device_info, containing information about the HID devices attached to the system, or NULL in the case of failure. Free this linked list by calling hid_free_enumeration().
{
  struct udev *udev;
  struct udev_enumerate *enumerate;
  struct udev_list_entry *devices, *dev_list_entry;
  struct hid_device_info *root = NULL; /* return object */
  struct hid_device_info *cur_dev = NULL;
  struct hid_device_info *prev_dev = NULL; /* previous device */
  hid_init();
  /* Create the udev object */
  udev = hid_wrapper_udev_new();
  if (!udev) {
    printf("Can't create udev\n");
    return NULL;
  }
  /* Create a list of the devices in the 'hidraw' subsystem. */
  enumerate = hid_wrapper_udev_enumerate_new(udev);
  hid_wrapper_udev_enumerate_add_match_subsystem(enumerate, "hidraw");
  hid_wrapper_udev_enumerate_scan_devices(enumerate);
  devices = hid_wrapper_udev_enumerate_get_list_entry(enumerate);
  /* For each item, see if it matches the vid/pid, and if so
     create a udev_device record for it */
    for (dev_list_entry = devices; dev_list_entry; dev_list_entry = hid_wrapper_udev_list_entry_get_next(dev_list_entry)) {
    const char *sysfs_path;
    const char *dev_path;
    const char *str;
    struct udev_device *raw_dev; /* The device's hidraw udev node. */
    struct udev_device *hid_dev; /* The device's HID udev node. */
    struct udev_device *usb_dev; /* The device's USB udev node. */
    struct udev_device *intf_dev; /* The device's interface (in the USB sense). */
    unsigned short dev_vid;
    unsigned short dev_pid;
    char *serial_number_utf8 = NULL;
    char *product_name_utf8 = NULL;
    int bus_type;
    int result;
    /* Get the filename of the /sys entry for the device
       and create a udev_device object (dev) representing it */
    sysfs_path = hid_wrapper_udev_list_entry_get_name(dev_list_entry);
    raw_dev = hid_wrapper_udev_device_new_from_syspath(udev, sysfs_path);
    dev_path = hid_wrapper_udev_device_get_devnode(raw_dev);
    hid_dev = hid_wrapper_udev_device_get_parent_with_subsystem_devtype(
      raw_dev,
      "hid",
      NULL);
    if (!hid_dev) {
      /* Unable to find parent hid device. */
      goto next;
    }
    result = parse_uevent_info(
      hid_wrapper_udev_device_get_sysattr_value(hid_dev, "uevent"),
      &bus_type,
      &dev_vid,
      &dev_pid,
      &serial_number_utf8,
      &product_name_utf8);
    if (!result) {
      /* parse_uevent_info() failed for at least one field. */
      goto next;
    }
    if (bus_type != BUS_USB && bus_type != BUS_BLUETOOTH) {
      /* We only know how to handle USB and BT devices. */
      goto next;
    }
    /* Check the VID/PID against the arguments */
    if ((vendor_id == 0x0 || vendor_id == dev_vid) &&
        (product_id == 0x0 || product_id == dev_pid)) {
      struct hid_device_info *tmp;
      /* VID/PID match. Create the record. */
      tmp = malloc(sizeof(struct hid_device_info));
      if (cur_dev) {
        cur_dev->next = tmp;
      }
      else {
        root = tmp;
      }
      prev_dev = cur_dev;
      cur_dev = tmp;
      /* Fill out the record */
      cur_dev->next = NULL;
      cur_dev->path = dev_path? strdup(dev_path): NULL;
      /* VID/PID */
      cur_dev->vendor_id = dev_vid;
      cur_dev->product_id = dev_pid;
      /* Serial Number */
      cur_dev->serial_number = utf8_to_wchar_t(serial_number_utf8);
      /* Release Number */
      cur_dev->release_number = 0x0;
      /* Interface Number */
      cur_dev->interface_number = -1;
      switch (bus_type) {
        case BUS_USB:
          /* The device pointed to by raw_dev contains information about
             the hidraw device. In order to get information about the
             USB device, get the parent device with the
             subsystem/devtype pair of "usb"/"usb_device". This will
             be several levels up the tree, but the function will find
             it. */
          usb_dev = hid_wrapper_udev_device_get_parent_with_subsystem_devtype(
              raw_dev,
              "usb",
              "usb_device");
          if (!usb_dev) {
            /* Free this device */
            free(cur_dev->serial_number);
            free(cur_dev->path);
            free(cur_dev);
            /* Take it off the device list. */
            if (prev_dev) {
              prev_dev->next = NULL;
              cur_dev = prev_dev;
            }
            else {
              cur_dev = root = NULL;
            }
            goto next;
          }
          /* Manufacturer and Product strings */
          cur_dev->manufacturer_string = copy_udev_string(usb_dev, device_string_names[DEVICE_STRING_MANUFACTURER]);
          cur_dev->product_string = copy_udev_string(usb_dev, device_string_names[DEVICE_STRING_PRODUCT]);
          /* Release Number */
          str = hid_wrapper_udev_device_get_sysattr_value(usb_dev, "bcdDevice");
          cur_dev->release_number = (str)? strtol(str, NULL, 16): 0x0;
          /* Get a handle to the interface's udev node. */
          intf_dev = hid_wrapper_udev_device_get_parent_with_subsystem_devtype(
              raw_dev,
              "usb",
              "usb_interface");
          if (intf_dev) {
            str = hid_wrapper_udev_device_get_sysattr_value(intf_dev, "bInterfaceNumber");
            cur_dev->interface_number = (str)? strtol(str, NULL, 16): -1;
          }
          break;
        case BUS_BLUETOOTH:
          /* Manufacturer and Product strings */
          cur_dev->manufacturer_string = wcsdup(L"");
          cur_dev->product_string = utf8_to_wchar_t(product_name_utf8);
          break;
        default:
          /* Unknown device type - this should never happen, as we
           * check for USB and Bluetooth devices above */
          break;
      }
    }
  next:
    free(serial_number_utf8);
    free(product_name_utf8);
    hid_wrapper_udev_device_unref(raw_dev);
    /* hid_dev, usb_dev and intf_dev don't need to be (and can't be)
       unref()d.  It will cause a double-free() error.  I'm not
       sure why.  */
  }
  /* Free the enumerator and udev objects. */
  hid_wrapper_udev_enumerate_unref(enumerate);
  hid_wrapper_udev_unref(udev);
  return root;
}
References BUF_LEN, copy_udev_string(), DEVICE_STRING_MANUFACTURER, device_string_names, DEVICE_STRING_PRODUCT, dup_wcs(), FALSE, free(), get_int_property(), get_manufacturer_string(), get_product_id(), get_product_string(), get_serial_number(), get_vendor_id(), hid_init(), hid_mgr, hid_wrapper_udev_device_get_devnode, hid_wrapper_udev_device_get_parent_with_subsystem_devtype, hid_wrapper_udev_device_get_sysattr_value, hid_wrapper_udev_device_new_from_syspath, hid_wrapper_udev_device_unref, hid_wrapper_udev_enumerate_add_match_subsystem, hid_wrapper_udev_enumerate_get_list_entry, hid_wrapper_udev_enumerate_new, hid_wrapper_udev_enumerate_scan_devices, hid_wrapper_udev_enumerate_unref, hid_wrapper_udev_list_entry_get_name, hid_wrapper_udev_list_entry_get_next, hid_wrapper_udev_new, hid_wrapper_udev_unref, hidapi_IOHIDDeviceGetService(), HidD_FreePreparsedData, HidD_GetAttributes, HidD_GetManufacturerString, HidD_GetPreparsedData, HidD_GetProductString, HidD_GetSerialNumberString, HidP_GetCaps, HIDP_STATUS_SUCCESS, hid_device_info::interface_number, L, malloc(), hid_device_info::manufacturer_string, hid_device_info::next, open_device(), parse_uevent_info(), hid_device_info::path, process_pending_events(), hid_device_info::product_id, hid_device_info::product_string, HIDD_ATTRIBUTES::ProductID, hid_device_info::release_number, hid_device_info::serial_number, HIDD_ATTRIBUTES::Size, hid_device_info::usage, _HIDP_CAPS::Usage, hid_device_info::usage_page, _HIDP_CAPS::UsagePage, utf8_to_wchar_t(), hid_device_info::vendor_id, HIDD_ATTRIBUTES::VendorID, HIDD_ATTRIBUTES::VersionNumber, and WSTR_LEN.
Referenced by Slic3r::GUI::Mouse3DController::connect_device(), and hid_open().
hid_error()
HID_API_EXPORT const wchar_t *HID_API_CALL hid_error (hid_device * dev)
#include <src/hidapi/include/hidapi.h>
Get a string describing the last error which occurred.
Parameters
dev A device handle returned from hid_open().
Returns
This function returns a string containing the last error which occurred or NULL if none has occurred.
{
  return NULL;
}
References hid_device_::last_error_str.
hid_exit()
int HID_API_EXPORT HID_API_CALL hid_exit (void)
#include <src/hidapi/include/hidapi.h>
Finalize the HIDAPI library.
This function frees all of the static data associated with HIDAPI. It should be called at the end of execution to avoid memory leaks.
Returns
This function returns 0 on success and -1 on error.
{
  /* Nothing to do for this in the Linux/hidraw implementation. */
  hid_wrapper_udev_close();
  return 0;
}
References FALSE, hid_mgr, hid_wrapper_udev_close(), initialized, and lib_handle.
Referenced by hid_init(), and Slic3r::GUI::Mouse3DController::run().
hid_free_enumeration()
void HID_API_EXPORT HID_API_CALL hid_free_enumeration (struct hid_device_info * devs)
#include <src/hidapi/include/hidapi.h>
Free an enumeration Linked List.
This function frees a linked list created by hid_enumerate().
Parameters
devs Pointer to a list of struct_device returned from hid_enumerate().
{
  struct hid_device_info *d = devs;
  while (d) {
    struct hid_device_info *next = d->next;
    free(d->path);
    free(d->serial_number);
    free(d->manufacturer_string);
    free(d->product_string);
    free(d);
    d = next;
  }
}
References free(), and hid_device_info::next.
Referenced by Slic3r::GUI::Mouse3DController::connect_device(), and hid_open().
hid_get_feature_report()
int HID_API_EXPORT HID_API_CALL hid_get_feature_report (hid_device * dev, unsigned char * data, size_t length)
#include <src/hidapi/include/hidapi.h>
Get a feature report from a HID device.
Set the first byte of data[] to the Report ID of the report to be read. Make sure to allow space for this extra byte in data[]. Upon return, the first byte will still contain the Report ID, and the report data will start in data[1].
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into, including the Report ID. Set the first byte of data[] to the Report ID of the report to be read, or set it to zero if your device does not use numbered reports.
length The number of bytes to read, including an extra byte for the report ID. The buffer can be longer than the actual report.
Returns
This function returns the number of bytes read plus one for the report ID (which is still in the first byte), or -1 on error.
{
  int res;
  res = ioctl(dev->device_handle, HIDIOCGFEATURE(length), data);
  if (res < 0)
    perror("ioctl (GFEATURE)");
  return res;
}
References hid_device_::device_handle, hid_device_::disconnected, HidD_GetFeature, HIDIOCGFEATURE, IOCTL_HID_GET_FEATURE, register_error(), and TRUE.
hid_get_indexed_string()
int HID_API_EXPORT_CALL hid_get_indexed_string (hid_device * dev, int string_index, wchar_t * string, size_t maxlen)
#include <src/hidapi/include/hidapi.h>
Get a string from a HID device, based on its string index.
Parameters
dev A device handle returned from hid_open().
string_index The index of the string to get.
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
{
  return -1;
}
References hid_device_::device_handle, HidD_GetIndexedString, MAX_STRING_WCHARS, MIN, and register_error().
hid_get_manufacturer_string()
int HID_API_EXPORT_CALL hid_get_manufacturer_string (hid_device * dev, wchar_t * string, size_t maxlen)
#include <src/hidapi/include/hidapi.h>
Get The Manufacturer String from a HID device.
Parameters
dev A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
{
  return get_device_string(dev, DEVICE_STRING_MANUFACTURER, string, maxlen);
}
References hid_device_::device_handle, DEVICE_STRING_MANUFACTURER, get_device_string(), get_manufacturer_string(), HidD_GetManufacturerString, MAX_STRING_WCHARS, MIN, and register_error().
Referenced by Slic3r::GUI::Mouse3DController::connect_device().
hid_get_product_string()
int HID_API_EXPORT_CALL hid_get_product_string (hid_device * dev, wchar_t * string, size_t maxlen)
#include <src/hidapi/include/hidapi.h>
Get The Product String from a HID device.
Parameters
dev A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
{
  return get_device_string(dev, DEVICE_STRING_PRODUCT, string, maxlen);
}
References hid_device_::device_handle, DEVICE_STRING_PRODUCT, get_device_string(), get_product_string(), HidD_GetProductString, MAX_STRING_WCHARS, MIN, and register_error().
Referenced by Slic3r::GUI::Mouse3DController::connect_device().
hid_get_serial_number_string()
int HID_API_EXPORT_CALL hid_get_serial_number_string (hid_device * dev, wchar_t * string, size_t maxlen)
#include <src/hidapi/include/hidapi.h>
Get The Serial Number String from a HID device.
Parameters
dev A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
{
  return get_device_string(dev, DEVICE_STRING_SERIAL, string, maxlen);
}
References hid_device_::device_handle, DEVICE_STRING_SERIAL, get_device_string(), get_serial_number(), HidD_GetSerialNumberString, MAX_STRING_WCHARS, MIN, and register_error().
hid_init()
int HID_API_EXPORT HID_API_CALL hid_init (void)
#include <src/hidapi/include/hidapi.h>
Initialize the HIDAPI library.
This function initializes the HIDAPI library. Calling it is not strictly necessary, as it will be called automatically by hid_enumerate() and any of the hid_open_*() functions if it is needed. This function should be called at the beginning of execution however, if there is a chance of HIDAPI handles being opened by different threads simultaneously.
Returns
This function returns 0 on success and -1 on error.
{
  const char *locale;
  /* Set the locale if it's not set. */
  locale = setlocale(LC_CTYPE, NULL);
  if (!locale)
    setlocale(LC_CTYPE, "");
  kernel_version = detect_kernel_version();
  return hid_wrapper_udev_init();
}
References detect_kernel_version(), hid_exit(), hid_mgr, hid_wrapper_udev_init(), init_hid_manager(), initialized, kernel_version, lookup_functions(), and TRUE.
Referenced by hid_enumerate(), hid_open_path(), and Slic3r::GUI::Mouse3DController::run().
hid_open()
HID_API_EXPORT hid_device *HID_API_CALL hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t * serial_number)
#include <src/hidapi/include/hidapi.h>
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
If serial_number is NULL, the first device with the specified VID and PID is opened.
Parameters
vendor_id The Vendor ID (VID) of the device to open.
product_id The Product ID (PID) of the device to open.
serial_number The Serial Number of the device to open (Optionally NULL).
Returns
This function returns a pointer to a hid_device object on success or NULL on failure.
{
  struct hid_device_info *devs, *cur_dev;
  const char *path_to_open = NULL;
  hid_device *handle = NULL;
  devs = hid_enumerate(vendor_id, product_id);
  cur_dev = devs;
  while (cur_dev) {
    if (cur_dev->vendor_id == vendor_id &&
        cur_dev->product_id == product_id) {
      if (serial_number) {
        if (wcscmp(serial_number, cur_dev->serial_number) == 0) {
          path_to_open = cur_dev->path;
          break;
        }
      }
      else {
        path_to_open = cur_dev->path;
        break;
      }
    }
    cur_dev = cur_dev->next;
  }
  if (path_to_open) {
    /* Open the device */
    handle = hid_open_path(path_to_open);
  }
  hid_free_enumeration(devs);
  return handle;
}
References hid_enumerate(), hid_free_enumeration(), hid_open_path(), hid_device_info::next, hid_device_info::path, hid_device_info::product_id, hid_device_info::serial_number, and hid_device_info::vendor_id.
Referenced by Slic3r::GUI::Mouse3DController::connect_device().
hid_open_path()
HID_API_EXPORT hid_device *HID_API_CALL hid_open_path (const char * path)
#include <src/hidapi/include/hidapi.h>
Open a HID device by its path name.
The path name be determined by calling hid_enumerate(), or a platform-specific path name can be used (eg: /dev/hidraw0 on Linux).
Parameters
path The path name of the device to open
Returns
This function returns a pointer to a hid_device object on success or NULL on failure.
{
  hid_device *dev = NULL;
  hid_init();
  dev = new_hid_device();
  /* OPEN HERE */
  dev->device_handle = open(path, O_RDWR);
  /* If we have a good handle, return it. */
  if (dev->device_handle > 0) {
    /* Get the report descriptor */
    int res, desc_size = 0;
    struct hidraw_report_descriptor rpt_desc;
    memset(&rpt_desc, 0x0, sizeof(rpt_desc));
    /* Get Report Descriptor Size */
    res = ioctl(dev->device_handle, HIDIOCGRDESCSIZE, &desc_size);
    if (res < 0)
      perror("HIDIOCGRDESCSIZE");
    /* Get Report Descriptor */
    rpt_desc.size = desc_size;
    res = ioctl(dev->device_handle, HIDIOCGRDESC, &rpt_desc);
    if (res < 0) {
      perror("HIDIOCGRDESC");
    } else {
      /* Determine if this device uses numbered reports. */
      dev->uses_numbered_reports =
        uses_numbered_reports(rpt_desc.value,
                              rpt_desc.size);
    }
    return dev;
  }
  else {
    /* Unable to open any devices. */
    free(dev);
    return NULL;
  }
}
References hid_device_::barrier, hid_device_::device_handle, FALSE, free(), free_hid_device(), get_max_report_length(), hid_device_removal_callback(), hid_init(), hid_report_callback(), HidD_FreePreparsedData, HidD_GetPreparsedData, HidD_SetNumInputBuffers, HidP_GetCaps, HIDP_STATUS_SUCCESS, hid_device_::input_report_buf, hid_device_::input_report_length, _HIDP_CAPS::InputReportByteLength, malloc(), hid_device_::max_input_report_len, new_hid_device(), open_device(), hid_device_::output_report_length, _HIDP_CAPS::OutputReportByteLength, hid_device_info::path, pthread_barrier_wait(), hid_device_::read_buf, read_thread(), register_error(), hid_device_::run_loop_mode, hid_device_::thread, TRUE, hid_device_::uses_numbered_reports, and uses_numbered_reports().
Referenced by Slic3r::GUI::Mouse3DController::connect_device(), and hid_open().
hid_read()
int HID_API_EXPORT HID_API_CALL hid_read (hid_device * dev, unsigned char * data, size_t length)
#include <src/hidapi/include/hidapi.h>
Read an Input report from a HID device.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into.
length The number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
Returns
This function returns the actual number of bytes read and -1 on error. If no packet was available to be read and the handle is in non-blocking mode, this function returns 0.
{
  return hid_read_timeout(dev, data, length, (dev->blocking)? -1: 0);
}
References hid_device_::blocking, and hid_read_timeout().
hid_read_timeout()
int HID_API_EXPORT HID_API_CALL hid_read_timeout (hid_device * dev, unsigned char * data, size_t length, int milliseconds)
#include <src/hidapi/include/hidapi.h>
Read an Input report from a HID device with timeout.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into.
length The number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
milliseconds timeout in milliseconds or -1 for blocking wait.
Returns
This function returns the actual number of bytes read and -1 on error. If no packet was available to be read within the timeout period, this function returns 0.
{
  int bytes_read;
  if (milliseconds >= 0) {
    /* Milliseconds is either 0 (non-blocking) or > 0 (contains
       a valid timeout). In both cases we want to call poll()
       and wait for data to arrive.  Don't rely on non-blocking
       operation (O_NONBLOCK) since some kernels don't seem to
       properly report device disconnection through read() when
       in non-blocking mode.  */
    int ret;
    struct pollfd fds;
    fds.fd = dev->device_handle;
    fds.events = POLLIN;
    fds.revents = 0;
    ret = poll(&fds, 1, milliseconds);
    if (ret == -1 || ret == 0) {
      /* Error or timeout */
      return ret;
    }
    else {
      /* Check for errors on the file descriptor. This will
         indicate a device disconnection. */
      if (fds.revents & (POLLERR | POLLHUP | POLLNVAL))
        return -1;
    }
  }
  bytes_read = read(dev->device_handle, data, length);
  if (bytes_read < 0 && (errno == EAGAIN || errno == EINPROGRESS))
    bytes_read = 0;
  if (bytes_read >= 0 &&
      kernel_version != 0 &&
      kernel_version < KERNEL_VERSION(2,6,34) &&
      dev->uses_numbered_reports) {
    /* Work around a kernel bug. Chop off the first byte. */
    memmove(data, data+1, bytes_read);
    bytes_read--;
  }
  return bytes_read;
}
References cond_timedwait(), cond_wait(), hid_device_::condition, input_report::data, hid_device_::device_handle, hid_device_::disconnected, FALSE, gettimeofday(), hid_device_::input_report_length, hid_device_::input_reports, kernel_version, hid_device_::mutex, hid_device_::ol, hid_device_::read_buf, hid_device_::read_pending, register_error(), return_data(), hid_device_::shutdown_thread, TRUE, and hid_device_::uses_numbered_reports.
Referenced by Slic3r::GUI::Mouse3DController::collect_input(), and hid_read().
hid_send_feature_report()
int HID_API_EXPORT HID_API_CALL hid_send_feature_report (hid_device * dev, const unsigned char * data, size_t length)
#include <src/hidapi/include/hidapi.h>
Send a Feature report to the device.
Feature reports are sent over the Control endpoint as a Set_Report transfer. The first byte of data[] must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to hid_send_feature_report() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to hid_send_feature_report(): the Report ID (or 0x0, for devices which do not use numbered reports), followed by the report data (16 bytes). In this example, the length passed in would be 17.
Parameters
dev A device handle returned from hid_open().
data The data to send, including the report number as the first byte.
length The length in bytes of the data to send, including the report number.
Returns
This function returns the actual number of bytes written and -1 on error.
{
  int res;
  res = ioctl(dev->device_handle, HIDIOCSFEATURE(length), data);
  if (res < 0)
    perror("ioctl (SFEATURE)");
  return res;
}
References hid_device_::device_handle, HidD_SetFeature, HIDIOCSFEATURE, register_error(), and set_report().
hid_set_nonblocking()
int HID_API_EXPORT HID_API_CALL hid_set_nonblocking (hid_device * dev, int nonblock)
#include <src/hidapi/include/hidapi.h>
Set the device handle to be non-blocking.
In non-blocking mode calls to hid_read() will return immediately with a value of 0 if there is no data to be read. In blocking mode, hid_read() will wait (block) until there is data to read before returning.
Nonblocking can be turned on and off at any time.
Parameters
dev A device handle returned from hid_open().
nonblock enable or not the nonblocking reads
1 to enable nonblocking
0 to disable nonblocking.
Returns
This function returns 0 on success and -1 on error.
{
  /* Do all non-blocking in userspace using poll(), since it looks
     like there's a bug in the kernel in some versions where
     read() will not return -1 on disconnection of the USB device */
  dev->blocking = !nonblock;
  return 0; /* Success */
}
References hid_device_::blocking.
hid_write()
int HID_API_EXPORT HID_API_CALL hid_write (hid_device * dev, const unsigned char * data, size_t length)
#include <src/hidapi/include/hidapi.h>
Write an Output report to a HID device.
The first byte of data[] must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to hid_write() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to hid_write(), the Report ID (or 0x0, for devices with a single report), followed by the report data (16 bytes). In this example, the length passed in would be 17.
hid_write() will send the data on the first OUT endpoint, if one exists. If it does not, it will send the data through the Control Endpoint (Endpoint 0).
Parameters
dev A device handle returned from hid_open().
data The data to send, including the report number as the first byte.
length The length in bytes of the data to send.
Returns
This function returns the actual number of bytes written and -1 on error.
{
  int bytes_written;
  bytes_written = write(dev->device_handle, data, length);
  return bytes_written;
}
References input_report::data, hid_device_::device_handle, free(), malloc(), hid_device_::output_report_length, register_error(), set_report(), and TRUE.