Prusa Slicer: Eigen::UniformScaling< _Scalar > Class Template Reference
Eigen::UniformScaling< _Scalar > Class Template Reference
#include <src/eigen/Eigen/src/Geometry/Scaling.h>
Public Types
typedef _Scalar Scalar
Public Member Functions
UniformScaling ()
UniformScaling (const Scalar &s)
const Scalar & factor () const
Scalar & factor ()
UniformScaling operator* (const UniformScaling &other) const
template<int Dim>
Transform< Scalar, Dim, Affine > operator* (const Translation< Scalar, Dim > &t) const
template<int Dim, int Mode, int Options>
Transform< Scalar, Dim,(int(Mode)==int(Isometry)?Affine:Mode)> operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
template<typename Derived >
internal::plain_matrix_type< Derived >::type operator* (const MatrixBase< Derived > &other) const
template<typename Derived , int Dim>
Matrix< Scalar, Dim, Dim > operator* (const RotationBase< Derived, Dim > &r) const
UniformScaling inverse () const
template<typename NewScalarType >
UniformScaling< NewScalarType > cast () const
template<typename OtherScalarType >
UniformScaling (const UniformScaling< OtherScalarType > &other)
bool isApprox (const UniformScaling &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
Protected Attributes
Scalar m_factor
Related Symbols
(Note that these are not member symbols.)
template<typename Derived , typename Scalar >
operator* (const MatrixBase< Derived > &matrix, const UniformScaling< Scalar > &s)
Detailed Description
template<typename _Scalar>
class Eigen::UniformScaling< _Scalar >
Member Typedef Documentation
Scalar
template<typename _Scalar > typedef _Scalar Eigen::UniformScaling< _Scalar >::Scalar
the scalar type of the coefficients
Constructor & Destructor Documentation
UniformScaling() [1/3]
template<typename _Scalar > Eigen::UniformScaling< _Scalar >::UniformScaling () inline
Default constructor without initialization.
{}
Referenced by Eigen::UniformScaling< _Scalar >::inverse(), and Eigen::UniformScaling< _Scalar >::operator*().
UniformScaling() [2/3]
template<typename _Scalar > Eigen::UniformScaling< _Scalar >::UniformScaling (const Scalar & s) inline explicit
Constructs and initialize a uniform scaling transformation
: m_factor(s) {}
UniformScaling() [3/3]
template<typename _Scalar > template<typename OtherScalarType > Eigen::UniformScaling< _Scalar >::UniformScaling (const UniformScaling< OtherScalarType > & other) inline explicit
Copy constructor with scalar type conversion
  { m_factor = Scalar(other.factor()); }
References Eigen::UniformScaling< _Scalar >::factor(), and Eigen::UniformScaling< _Scalar >::m_factor.
Member Function Documentation
cast()
template<typename _Scalar > template<typename NewScalarType > UniformScaling< NewScalarType > Eigen::UniformScaling< _Scalar >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
  { return UniformScaling<NewScalarType>(NewScalarType(m_factor)); }
References Eigen::UniformScaling< _Scalar >::m_factor.
factor() [1/2]
template<typename _Scalar > Scalar & Eigen::UniformScaling< _Scalar >::factor () inline
{ return m_factor; }
References Eigen::UniformScaling< _Scalar >::m_factor.
factor() [2/2]
template<typename _Scalar > const Scalar & Eigen::UniformScaling< _Scalar >::factor () const inline
{ return m_factor; }
References Eigen::UniformScaling< _Scalar >::m_factor.
Referenced by Eigen::UniformScaling< _Scalar >::UniformScaling(), Eigen::UniformScaling< _Scalar >::isApprox(), Eigen::UniformScaling< _Scalar >::operator*(), Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Translation< _Scalar, _Dim >::operator*(), Eigen::RotationBase< Derived, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator*=(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=().
inverse()
template<typename _Scalar > UniformScaling Eigen::UniformScaling< _Scalar >::inverse () const inline
Returns
the inverse scaling
  { return UniformScaling(Scalar(1)/m_factor); }
References Eigen::UniformScaling< _Scalar >::UniformScaling(), and Eigen::UniformScaling< _Scalar >::m_factor.
isApprox()
template<typename _Scalar > bool Eigen::UniformScaling< _Scalar >::isApprox (const UniformScaling< _Scalar > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
  { return internal::isApprox(m_factor, other.factor(), prec); }
References Eigen::UniformScaling< _Scalar >::factor(), Eigen::internal::isApprox(), and Eigen::UniformScaling< _Scalar >::m_factor.
operator*() [1/5]
template<typename _Scalar > template<typename Derived > internal::plain_matrix_type< Derived >::type Eigen::UniformScaling< _Scalar >::operator* (const MatrixBase< Derived > & other) const inline
Concatenates a uniform scaling and a linear transformation matrix
  { return other * m_factor; }
References Eigen::UniformScaling< _Scalar >::m_factor.
operator*() [2/5]
template<typename _Scalar > template<typename Derived , int Dim> Matrix< Scalar, Dim, Dim > Eigen::UniformScaling< _Scalar >::operator* (const RotationBase< Derived, Dim > & r) const inline
  { return r.toRotationMatrix() * m_factor; }
References Eigen::UniformScaling< _Scalar >::m_factor, and Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
operator*() [3/5]
template<typename _Scalar > template<int Dim, int Mode, int Options> Transform< Scalar, Dim,(int(Mode)==int(Isometry)?Affine:Mode)> Eigen::UniformScaling< _Scalar >::operator* (const Transform< Scalar, Dim, Mode, Options > & t) const inline
Concatenates a uniform scaling and an affine transformation
                                                              :Mode)> operator* (const Transform<Scalar,Dim, Mode, Options>& t) const
  {
    Transform<Scalar,Dim,(int(Mode)==int(Isometry)?Affine:Mode)> res = t;
    res.prescale(factor());
    return res;
  }
References Eigen::Affine, Eigen::UniformScaling< _Scalar >::factor(), Eigen::Isometry, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::prescale().
operator*() [4/5]
template<typename Scalar > template<int Dim> Transform< Scalar, Dim, Affine > Eigen::UniformScaling< Scalar >::operator* (const Translation< Scalar, Dim > & t) const inline
Concatenates a uniform scaling and a translation
{
  Transform<Scalar,Dim,Affine> res;
  res.matrix().setZero();
  res.linear().diagonal().fill(factor());
  res.translation() = factor() * t.vector();
  res(Dim,Dim) = Scalar(1);
  return res;
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Eigen::PlainObjectBase< Derived >::setZero(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation(), and Eigen::Translation< _Scalar, _Dim >::vector().
operator*() [5/5]
template<typename _Scalar > UniformScaling Eigen::UniformScaling< _Scalar >::operator* (const UniformScaling< _Scalar > & other) const inline
Concatenates two uniform scaling
  { return UniformScaling(m_factor * other.factor()); }
References Eigen::UniformScaling< _Scalar >::UniformScaling(), Eigen::UniformScaling< _Scalar >::factor(), and Eigen::UniformScaling< _Scalar >::m_factor.
Friends And Related Symbol Documentation
operator*()
template<typename Derived , typename Scalar > operator* (const MatrixBase< Derived > & matrix, const UniformScaling< Scalar > & s) related
Concatenates a linear transformation matrix and a uniform scaling
{ return matrix.derived() * s.factor(); }
Member Data Documentation
m_factor
template<typename _Scalar > Scalar Eigen::UniformScaling< _Scalar >::m_factor protected
Referenced by Eigen::UniformScaling< _Scalar >::UniformScaling(), Eigen::UniformScaling< _Scalar >::cast(), Eigen::UniformScaling< _Scalar >::factor(), Eigen::UniformScaling< _Scalar >::factor(), Eigen::UniformScaling< _Scalar >::inverse(), Eigen::UniformScaling< _Scalar >::isApprox(), Eigen::UniformScaling< _Scalar >::operator*(), Eigen::UniformScaling< _Scalar >::operator*(), and Eigen::UniformScaling< _Scalar >::operator*().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/util/ForwardDeclarations.h
src/eigen/Eigen/src/Geometry/Scaling.h