Prusa Slicer: QuadricEdgeCollapse::SymMat Class Reference
QuadricEdgeCollapse::SymMat Class Reference
Public Member Functions
SymMat (ArithmeticOnly< T > c=T())
SymMat (T a, T b, T c, T d)
T operator[] (int c) const
T det (int a11, int a12, int a13, int a21, int a22, int a23, int a31, int a32, int a33) const
const SymMat & operator+= (const SymMat &n)
Private Types
using T = double
Private Attributes
T m [N]
Static Private Attributes
static const constexpr size_t N = 10
Detailed Description
Member Typedef Documentation
T
using QuadricEdgeCollapse::SymMat::T = double private
Constructor & Destructor Documentation
SymMat() [1/2]
QuadricEdgeCollapse::SymMat::SymMat (ArithmeticOnly< T > c = T()) inline explicit
{ std::fill(m, m + N, c); }
References m, and N.
SymMat() [2/2]
QuadricEdgeCollapse::SymMat::SymMat (T a, T b, T c, T d) inline
        {
            m[0] = a * a; m[1] = a * b; m[2] = a * c; m[3] = a * d;
            m[4] = b * b; m[5] = b * c; m[6] = b * d;
            m[7] = c * c; m[8] = c * d;
            m[9] = d * d;
        }
References m.
Member Function Documentation
det()
T QuadricEdgeCollapse::SymMat::det (int a11, int a12, int a13, int a21, int a22, int a23, int a31, int a32, int a33) const inline
        {
            T det = m[a11] * m[a22] * m[a33] + m[a13] * m[a21] * m[a32] +
                    m[a12] * m[a23] * m[a31] - m[a13] * m[a22] * m[a31] -
                    m[a11] * m[a23] * m[a32] - m[a12] * m[a21] * m[a33];
            return det;
        }
References det(), and m.
Referenced by QuadricEdgeCollapse::calculate_determinant(), QuadricEdgeCollapse::calculate_vertex(), and det().
operator+=()
const SymMat & QuadricEdgeCollapse::SymMat::operator+= (const SymMat & n) inline
        {
            for (size_t i = 0; i < N; ++i) m[i] += n[i];
            return *this;
        }
References m, and N.
operator[]()
T QuadricEdgeCollapse::SymMat::operator[] (int c) const inline
{ return m[c]; }
References m.
Member Data Documentation
m
T QuadricEdgeCollapse::SymMat::m[N] private
Referenced by SymMat(), SymMat(), det(), operator+=(), and operator[]().
N
const constexpr size_t QuadricEdgeCollapse::SymMat::N = 10 static constexpr private
Referenced by SymMat(), and operator+=().
The documentation for this class was generated from the following file:
src/libslic3r/QuadricEdgeCollapse.cpp