Prusa Slicer: Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
#include <src/eigen/Eigen/src/SVD/JacobiSVD.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime }
typedef MatrixType::Scalar Scalar
typedef Matrix< Scalar, 1, RowsAtCompileTime, RowMajor, 1, MaxRowsAtCompileTime > WorkspaceType
Public Member Functions
void allocate (const JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > &svd)
bool run (JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > &svd, const MatrixType &matrix)
Private Types
typedef FullPivHouseholderQR< MatrixType > QRType
Private Attributes
QRType m_qr
WorkspaceType m_workspace
Detailed Description
template<typename MatrixType>
class Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
Member Typedef Documentation
QRType
template<typename MatrixType > typedef FullPivHouseholderQR<MatrixType> Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::QRType private
Scalar
template<typename MatrixType > typedef MatrixType::Scalar Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::Scalar
WorkspaceType
template<typename MatrixType > typedef Matrix<Scalar, 1, RowsAtCompileTime, RowMajor, 1, MaxRowsAtCompileTime> Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::WorkspaceType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
MaxRowsAtCompileTime
  {
    RowsAtCompileTime = MatrixType::RowsAtCompileTime,
    MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime
  };
Member Function Documentation
allocate()
template<typename MatrixType > void Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate (const JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > & svd) inline
  {
    if (svd.rows() != m_qr.rows() || svd.cols() != m_qr.cols())
    {
      m_qr.~QRType();
      ::new (&m_qr) QRType(svd.rows(), svd.cols());
    }
    if (svd.m_computeFullU) m_workspace.resize(svd.rows());
  }
References Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::cols(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeFullU, and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::rows().
run()
template<typename MatrixType > bool Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run (JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > & svd, const MatrixType & matrix) inline
  {
    if(matrix.rows() > matrix.cols())
    {
      m_qr.compute(matrix);
      svd.m_workMatrix = m_qr.matrixQR().block(0,0,matrix.cols(),matrix.cols()).template triangularView<Upper>();
      if(svd.m_computeFullU) m_qr.matrixQ().evalTo(svd.m_matrixU, m_workspace);
      if(svd.computeV()) svd.m_matrixV = m_qr.colsPermutation();
      return true;
    }
    return false;
  }
References Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::computeV(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeFullU, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_matrixU, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_matrixV, and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_workMatrix.
Member Data Documentation
m_qr
template<typename MatrixType > QRType Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_qr private
m_workspace
template<typename MatrixType > WorkspaceType Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_workspace private
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SVD/JacobiSVD.h