Prusa Slicer: Slic3r::CLITransformConfigDef Class Reference
Slic3r::CLITransformConfigDef Class Reference
#include <src/libslic3r/PrintConfig.hpp>
Public Member Functions
CLITransformConfigDef ()
bool has (const t_config_option_key &opt_key) const
const ConfigOptionDef * get (const t_config_option_key &opt_key) const
std::vector< std::string > keys () const
std::ostream & print_cli_help (std::ostream &out, bool show_defaults, std::function< bool(const ConfigOptionDef &)> filter=[](const ConfigOptionDef &){ return true;}) const
Public Attributes
t_optiondef_map options
std::map< size_t, const ConfigOptionDef * > by_serialization_key_ordinal
Protected Member Functions
ConfigOptionDef * add (const t_config_option_key &opt_key, ConfigOptionType type)
ConfigOptionDef * add_nullable (const t_config_option_key &opt_key, ConfigOptionType type)
void finalize ()
Detailed Description
Constructor & Destructor Documentation
CLITransformConfigDef()
Slic3r::CLITransformConfigDef::CLITransformConfigDef ()
{
    ConfigOptionDef* def;
    // Transform options:
    def = this->add("align_xy", coPoint);
    def->label = L("Align XY");
    def->tooltip = L("Align the model to the given point.");
    def->set_default_value(new ConfigOptionPoint(Vec2d(100,100)));
    def = this->add("cut", coFloat);
    def->label = L("Cut");
    def->tooltip = L("Cut model at the given Z.");
    def->set_default_value(new ConfigOptionFloat(0));
/*
    def = this->add("cut_grid", coFloat);
    def->label = L("Cut");
    def->tooltip = L("Cut model in the XY plane into tiles of the specified max size.");
    def->set_default_value(new ConfigOptionPoint());
    def = this->add("cut_x", coFloat);
    def->label = L("Cut");
    def->tooltip = L("Cut model at the given X.");
    def->set_default_value(new ConfigOptionFloat(0));
    def = this->add("cut_y", coFloat);
    def->label = L("Cut");
    def->tooltip = L("Cut model at the given Y.");
    def->set_default_value(new ConfigOptionFloat(0));
*/
    def = this->add("center", coPoint);
    def->label = L("Center");
    def->tooltip = L("Center the print around the given center.");
    def->set_default_value(new ConfigOptionPoint(Vec2d(100,100)));
    def = this->add("dont_arrange", coBool);
    def->label = L("Don't arrange");
    def->tooltip = L("Do not rearrange the given models before merging and keep their original XY coordinates.");
    def = this->add("ensure_on_bed", coBool);
    def->label = L("Ensure on bed");
    def->tooltip = L("Lift the object above the bed when it is partially below. Enabled by default, use --no-ensure-on-bed to disable.");
    def->set_default_value(new ConfigOptionBool(true));
    def = this->add("duplicate", coInt);
    def->label = L("Duplicate");
    def->tooltip =L("Multiply copies by this factor.");
    def->min = 1;
    def = this->add("duplicate_grid", coPoint);
    def->label = L("Duplicate by grid");
    def->tooltip = L("Multiply copies by creating a grid.");
    def = this->add("merge", coBool);
    def->label = L("Merge");
    def->tooltip = L("Arrange the supplied models in a plate and merge them in a single model in order to perform actions once.");
    def->cli = "merge|m";
    def = this->add("repair", coBool);
    def->label = L("Repair");
    def->tooltip = L("Try to repair any non-manifold meshes (this option is implicitly added whenever we need to slice the model to perform the requested action).");
    def = this->add("rotate", coFloat);
    def->label = L("Rotate");
    def->tooltip = L("Rotation angle around the Z axis in degrees.");
    def->set_default_value(new ConfigOptionFloat(0));
    def = this->add("rotate_x", coFloat);
    def->label = L("Rotate around X");
    def->tooltip = L("Rotation angle around the X axis in degrees.");
    def->set_default_value(new ConfigOptionFloat(0));
    def = this->add("rotate_y", coFloat);
    def->label = L("Rotate around Y");
    def->tooltip = L("Rotation angle around the Y axis in degrees.");
    def->set_default_value(new ConfigOptionFloat(0));
    def = this->add("scale", coFloatOrPercent);
    def->label = L("Scale");
    def->tooltip = L("Scaling factor or percentage.");
    def->set_default_value(new ConfigOptionFloatOrPercent(1, false));
    def = this->add("split", coBool);
    def->label = L("Split");
    def->tooltip = L("Detect unconnected parts in the given model(s) and split them into separate objects.");
    def = this->add("scale_to_fit", coPoint3);
    def->label = L("Scale to Fit");
    def->tooltip = L("Scale to fit the given volume.");
    def->set_default_value(new ConfigOptionPoint3(Vec3d(0,0,0)));
    def = this->add("delete-after-load", coString);
    def->label = L("Delete files after loading");
    def->tooltip = L("Delete files after loading.");
}
References Slic3r::ConfigDef::add(), Slic3r::ConfigOptionDef::cli, Slic3r::coBool, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coInt, Slic3r::coPoint, Slic3r::coPoint3, Slic3r::coString, L, Slic3r::ConfigOptionDef::label, Slic3r::ConfigOptionDef::min, Slic3r::ConfigOptionDef::set_default_value(), and Slic3r::ConfigOptionDef::tooltip.
Member Function Documentation
add()
ConfigOptionDef * Slic3r::ConfigDef::add (const t_config_option_key & opt_key, ConfigOptionType type) protected inherited
{
  static size_t serialization_key_ordinal_last = 0;
    ConfigOptionDef *opt = &this->options[opt_key];
    opt->opt_key = opt_key;
    opt->type = type;
    opt->serialization_key_ordinal = ++ serialization_key_ordinal_last;
    this->by_serialization_key_ordinal[opt->serialization_key_ordinal] = opt;
    return opt;
}
References Slic3r::ConfigDef::by_serialization_key_ordinal, Slic3r::ConfigOptionDef::opt_key, Slic3r::ConfigDef::options, Slic3r::ConfigOptionDef::serialization_key_ordinal, and Slic3r::ConfigOptionDef::type.
Referenced by Slic3r::AnycubicSLAFormatConfigDef::AnycubicSLAFormatConfigDef(), Slic3r::CLIActionsConfigDef::CLIActionsConfigDef(), Slic3r::CLIMiscConfigDef::CLIMiscConfigDef(), CLITransformConfigDef(), Slic3r::ConfigDef::add_nullable(), Slic3r::PrintConfigDef::init_common_params(), Slic3r::PrintConfigDef::init_fff_params(), Slic3r::PrintConfigDef::init_sla_params(), and Slic3r::PrintConfigDef::init_sla_support_params().
add_nullable()
ConfigOptionDef * Slic3r::ConfigDef::add_nullable (const t_config_option_key & opt_key, ConfigOptionType type) protected inherited
{
  ConfigOptionDef *def = this->add(opt_key, type);
  def->nullable = true;
  return def;
}
References Slic3r::ConfigDef::add(), and Slic3r::ConfigOptionDef::nullable.
Referenced by Slic3r::PrintConfigDef::init_fff_params(), and Slic3r::PrintConfigDef::init_sla_params().
finalize()
void Slic3r::ConfigDef::finalize () protected inherited
{
    // Validate & finalize open & closed enums.
    for (std::pair<const t_config_option_key, ConfigOptionDef> &kvp : options) {
        ConfigOptionDef& def = kvp.second;
        if (def.type == coEnum) {
            assert(def.enum_def);
            assert(def.enum_def->is_valid_closed_enum());
            assert(def.gui_type != ConfigOptionDef::GUIType::i_enum_open &&
                   def.gui_type != ConfigOptionDef::GUIType::f_enum_open &&
                   def.gui_type != ConfigOptionDef::GUIType::select_open);
            def.enum_def->finalize_closed_enum();
        } else if (def.gui_type == ConfigOptionDef::GUIType::i_enum_open || def.gui_type == ConfigOptionDef::GUIType::f_enum_open ||
                   def.gui_type == ConfigOptionDef::GUIType::select_open) {
            assert(def.enum_def);
            assert(def.enum_def->is_valid_open_enum());
            assert(def.gui_type != ConfigOptionDef::GUIType::i_enum_open || def.type == coInt || def.type == coInts);
            assert(def.gui_type != ConfigOptionDef::GUIType::f_enum_open || def.type == coFloat || def.type == coPercent || def.type == coFloatOrPercent);
            assert(def.gui_type != ConfigOptionDef::GUIType::select_open || def.type == coString || def.type == coStrings);
        } else {
            assert(! def.enum_def);
        }
    }
}
References Slic3r::coEnum, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coInt, Slic3r::coInts, Slic3r::coPercent, Slic3r::coString, Slic3r::coStrings, Slic3r::ConfigOptionDef::enum_def, Slic3r::ConfigOptionDef::f_enum_open, Slic3r::ConfigOptionDef::gui_type, Slic3r::ConfigOptionDef::i_enum_open, Slic3r::ConfigDef::options, Slic3r::ConfigOptionDef::select_open, and Slic3r::ConfigOptionDef::type.
Referenced by Slic3r::PrintConfigDef::PrintConfigDef().
get()
const ConfigOptionDef * Slic3r::ConfigDef::get (const t_config_option_key & opt_key) const inline inherited
{
        t_optiondef_map::iterator it = const_cast<ConfigDef*>(this)->options.find(opt_key);
        return (it == this->options.end()) ? nullptr : &it->second;
    }
References Slic3r::ConfigDef::options.
Referenced by Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::PhysicalPrinterCollection::PhysicalPrinterCollection(), Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::change_opt_value(), Slic3r::StaticPrintConfig::StaticCache< T >::finalize(), Slic3r::ConfigBase::get_abs_value(), Slic3r::GUI::SettingsFactory::get_bundle(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_full_label(), Slic3r::GUI::get_full_settings_hierarchy(), Slic3r::GUI::ConfigOptionsGroup::get_option(), Slic3r::GUI::get_string_value(), Slic3r::ConfigBase::option_def(), Slic3r::DynamicConfig::optptr(), cereal::save(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::StaticConfig::set_defaults(), Slic3r::ConfigBase::set_deserialize_raw(), Slic3r::GUI::PageMaterials::sort_list_data(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GLVolumeCollection::update_colors_by_extruder(), Slic3r::GUI::TabSLAPrint::update_description_lines(), and Slic3r::validate().
has()
bool Slic3r::ConfigDef::has (const t_config_option_key & opt_key) const inline inherited
{ return this->options.count(opt_key) > 0; }
Referenced by Slic3r::PrintConfigDef::handle_legacy(), and Slic3r::CLI::setup().
keys()
std::vector< std::string > Slic3r::ConfigDef::keys () const inline inherited
{
        std::vector<std::string> out;
        out.reserve(options.size());
        for(auto const& kvp : options)
            out.push_back(kvp.first);
        return out;
    }
References Slic3r::ConfigDef::options.
print_cli_help()
std::ostream & Slic3r::ConfigDef::print_cli_help (std::ostream & out, bool show_defaults, std::function< bool(const ConfigOptionDef &)> filter = [](const ConfigOptionDef &){ return true; }) const inherited
{
    // prepare a function for wrapping text
    auto wrap = [](const std::string& text, size_t line_length) -> std::string {
        std::istringstream words(text);
        std::ostringstream wrapped;
        std::string word;
        if (words >> word) {
            wrapped << word;
            size_t space_left = line_length - word.length();
            while (words >> word) {
                if (space_left < word.length() + 1) {
                    wrapped << '\n' << word;
                    space_left = line_length - word.length();
                } else {
                    wrapped << ' ' << word;
                    space_left -= word.length() + 1;
                }
            }
        }
        return wrapped.str();
    };
    // get the unique categories
    std::set<std::string> categories;
    for (const auto& opt : this->options) {
        const ConfigOptionDef& def = opt.second;
        if (filter(def))
            categories.insert(def.category);
    }
    for (const std::string& category : categories) {
        if (category != "") {
            out << category << ":" << std::endl;
        } else if (categories.size() > 1) {
            out << "Misc options:" << std::endl;
        }
        for (const auto& opt : this->options) {
            const ConfigOptionDef& def = opt.second;
      if (def.category != category || def.cli == ConfigOptionDef::nocli || !filter(def))
                continue;
            // get all possible variations: --foo, --foobar, -f...
            std::vector<std::string> cli_args = def.cli_args(opt.first);
      if (cli_args.empty())
        continue;
            for (auto& arg : cli_args) {
                arg.insert(0, (arg.size() == 1) ? "-" : "--");
                if (def.type == coFloat || def.type == coInt || def.type == coFloatOrPercent
                    || def.type == coFloats || def.type == coInts) {
                    arg += " N";
                } else if (def.type == coPoint) {
                    arg += " X,Y";
                } else if (def.type == coPoint3) {
                    arg += " X,Y,Z";
                } else if (def.type == coString || def.type == coStrings) {
                    arg += " ABCD";
                }
            }
            // left: command line options
            const std::string cli = boost::algorithm::join(cli_args, ", ");
            out << " " << std::left << std::setw(20) << cli;
            // right: option description
            std::string descr = def.tooltip;
            bool show_defaults_this = show_defaults || def.opt_key == "config_compatibility";
            if (show_defaults_this && def.default_value && def.type != coBool
                && (def.type != coString || !def.default_value->serialize().empty())) {
                descr += " (";
                if (!def.sidetext.empty()) {
                    descr += def.sidetext + ", ";
                } else if (def.enum_def->has_values()) {
                    descr += boost::algorithm::join(def.enum_def->values(), ", ") + "; ";
                }
                descr += "default: " + def.default_value->serialize() + ")";
            }
            // wrap lines of description
            descr = wrap(descr, 80);
            std::vector<std::string> lines;
            boost::split(lines, descr, boost::is_any_of("\n"));
            // if command line options are too long, print description in new line
            for (size_t i = 0; i < lines.size(); ++i) {
                if (i == 0 && cli.size() > 19)
                    out << std::endl;
                if (i > 0 || cli.size() > 19)
                    out << std::string(21, ' ');
                out << lines[i] << std::endl;
            }
        }
    }
    return out;
}
References arg(), Slic3r::ConfigOptionDef::category, Slic3r::ConfigOptionDef::cli, Slic3r::ConfigOptionDef::cli_args(), Slic3r::coBool, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coFloats, Slic3r::coInt, Slic3r::coInts, Slic3r::coPoint, Slic3r::coPoint3, Slic3r::coString, Slic3r::coStrings, Slic3r::ConfigOptionDef::default_value, Slic3r::ConfigOptionDef::enum_def, Slic3r::ConfigOptionDef::nocli, Slic3r::ConfigOptionDef::opt_key, Slic3r::ConfigDef::options, Slic3r::ConfigOptionDef::sidetext, Slic3r::ConfigOptionDef::tooltip, and Slic3r::ConfigOptionDef::type.
Referenced by Slic3r::CLI::print_help().
Member Data Documentation
by_serialization_key_ordinal
std::map<size_t, const ConfigOptionDef*> Slic3r::ConfigDef::by_serialization_key_ordinal inherited
Referenced by Slic3r::DynamicPrintAndCLIConfig::PrintAndCLIConfigDef::PrintAndCLIConfigDef(), Slic3r::ConfigDef::add(), and cereal::load().
options
t_optiondef_map Slic3r::ConfigDef::options inherited
Referenced by Slic3r::DynamicPrintAndCLIConfig::PrintAndCLIConfigDef::PrintAndCLIConfigDef(), Slic3r::PrintConfigDef::PrintConfigDef(), Slic3r::DynamicPrintAndCLIConfig::PrintAndCLIConfigDef::~PrintAndCLIConfigDef(), Slic3r::ConfigDef::add(), Slic3r::AMFParserContext::endElement(), Slic3r::ConfigDef::finalize(), Slic3r::StaticPrintConfig::StaticCache< T >::finalize(), Slic3r::ConfigDef::get(), Slic3r::DynamicPrintAndCLIConfig::handle_legacy(), Slic3r::PrintConfigDef::init_fff_params(), Slic3r::ConfigDef::keys(), Slic3r::StaticConfig::keys(), Slic3r::ConfigDef::print_cli_help(), Slic3r::DynamicConfig::read_cli(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::CLI::setup().
The documentation for this class was generated from the following files:
src/libslic3r/PrintConfig.hpp
src/libslic3r/PrintConfig.cpp