Prusa Slicer: Slic3r::anonymous_namespace{AnycubicSLA.cpp} Namespace Reference
Slic3r::anonymous_namespace{AnycubicSLA.cpp} Namespace Reference
Functions
std::float_t get_cfg_value_f (const DynamicConfig &cfg, const std::string &key, const std::float_t &def=0.f)
int get_cfg_value_i (const DynamicConfig &cfg, const std::string &key, const int &def=0)
template<class T >
void crop_value (T &val, T val_min, T val_max)
void fill_preview (anycubicsla_format_preview &p, anycubicsla_format_misc &, const ThumbnailsList &thumbnails)
void fill_header (anycubicsla_format_header &h, anycubicsla_format_misc &m, const SLAPrint &print, std::uint32_t layer_count)
Function Documentation
crop_value()
template<class T > void Slic3r::anonymous_namespace{AnycubicSLA.cpp}::crop_value (T & val, T val_min, T val_max)
{
    if (val < val_min) {
        val = val_min;
    } else if (val > val_max) {
        val = val_max;
    }
}
References crop_value().
Referenced by crop_value(), and fill_header().
fill_header()
void Slic3r::anonymous_namespace{AnycubicSLA.cpp}::fill_header (anycubicsla_format_header & h, anycubicsla_format_misc & m, const SLAPrint & print, std::uint32_t layer_count)
{
    CNumericLocalesSetter locales_setter;
    std::float_t bottle_weight_g;
    std::float_t bottle_volume_ml;
    std::float_t bottle_cost;
    std::float_t material_density;
    auto        &cfg     = print.full_print_config();
    auto         mat_opt = cfg.option("material_notes");
    std::string  mnotes  = mat_opt? cfg.option("material_notes")->serialize() : "";
    // create a config parser from the material notes
    Slic3r::AnycubicSLAFormatDynamicConfig mat_cfg;
    SLAPrintStatistics              stats = print.print_statistics();
    // sanitize the string config
    boost::replace_all(mnotes, "\\n", "\n");
    boost::replace_all(mnotes, "\\r", "\r");
    mat_cfg.load_from_ini_string(mnotes,
                                 ForwardCompatibilitySubstitutionRule::Enable);
    h.layer_height_mm        = get_cfg_value_f(cfg, "layer_height");
    m.bottom_layer_height_mm = get_cfg_value_f(cfg, "initial_layer_height");
    h.exposure_time_s        = get_cfg_value_f(cfg, "exposure_time");
    h.bottom_exposure_time_s = get_cfg_value_f(cfg, "initial_exposure_time");
    h.bottom_layer_count =     get_cfg_value_i(cfg, "faded_layers");
    if (layer_count < h.bottom_layer_count) {
        h.bottom_layer_count = layer_count;
    }
    h.res_x     = get_cfg_value_i(cfg, "display_pixels_x");
    h.res_y     = get_cfg_value_i(cfg, "display_pixels_y");
    bottle_weight_g = get_cfg_value_f(cfg, "bottle_weight") * 1000.0f;
    bottle_volume_ml = get_cfg_value_f(cfg, "bottle_volume");
    bottle_cost = get_cfg_value_f(cfg, "bottle_cost");
    material_density = bottle_weight_g / bottle_volume_ml;
    h.volume_ml = (stats.objects_used_material + stats.support_used_material) / 1000;
    h.weight_g           = h.volume_ml * material_density;
    h.price              = (h.volume_ml * bottle_cost) /  bottle_volume_ml;
    h.price_currency     = '$';
    h.antialiasing       = 1;
    h.per_layer_override = 0;
    // TODO - expose these variables to the UI rather than using material notes
    if (mat_cfg.has(CFG_ANTIALIASING)) {
        h.antialiasing = get_cfg_value_i(mat_cfg, CFG_ANTIALIASING);
        crop_value(h.antialiasing, (uint32_t) 0, (uint32_t) 1);
    } else {
        h.antialiasing = 1;
    }
    h.delay_before_exposure_s = get_cfg_value_f(mat_cfg, CFG_DELAY_BEFORE_EXPOSURE, 0.5f);
    crop_value(h.delay_before_exposure_s, 0.0f, 1000.0f);
    h.lift_distance_mm = get_cfg_value_f(mat_cfg, CFG_LIFT_DISTANCE, 8.0f);
    crop_value(h.lift_distance_mm, 0.0f, 100.0f);
    if (mat_cfg.has(CFG_BOTTOM_LIFT_DISTANCE)) {
        m.bottom_lift_distance_mm = get_cfg_value_f(mat_cfg,
                                                    CFG_BOTTOM_LIFT_DISTANCE,
                                                    8.0f);
        crop_value(h.lift_distance_mm, 0.0f, 100.0f);
    } else {
        m.bottom_lift_distance_mm = h.lift_distance_mm;
    }
    h.lift_speed_mms = get_cfg_value_f(mat_cfg, CFG_LIFT_SPEED, 2.0f);
    crop_value(m.bottom_lift_speed_mms, 0.1f, 20.0f);
    if (mat_cfg.has(CFG_BOTTOM_LIFT_SPEED)) {
        m.bottom_lift_speed_mms = get_cfg_value_f(mat_cfg, CFG_BOTTOM_LIFT_SPEED, 2.0f);
        crop_value(m.bottom_lift_speed_mms, 0.1f, 20.0f);
    } else {
        m.bottom_lift_speed_mms = h.lift_speed_mms;
    }
    h.retract_speed_mms = get_cfg_value_f(mat_cfg, CFG_RETRACT_SPEED, 3.0f);
    crop_value(h.lift_speed_mms, 0.1f, 20.0f);
    h.print_time_s = (h.bottom_layer_count * h.bottom_exposure_time_s) +
                     ((layer_count - h.bottom_layer_count) *
                      h.exposure_time_s) +
                     (layer_count * h.lift_distance_mm / h.retract_speed_mms) +
                     (layer_count * h.lift_distance_mm / h.lift_speed_mms) +
                     (layer_count * h.delay_before_exposure_s);
    h.payload_size  = sizeof(h) - sizeof(h.tag) - sizeof(h.payload_size);
    h.pixel_size_um = 50;
}
References Slic3r::anycubicsla_format_header::antialiasing, Slic3r::anycubicsla_format_header::bottom_exposure_time_s, Slic3r::anycubicsla_format_header::bottom_layer_count, Slic3r::anycubicsla_format_misc::bottom_layer_height_mm, Slic3r::anycubicsla_format_misc::bottom_lift_distance_mm, Slic3r::anycubicsla_format_misc::bottom_lift_speed_mms, CFG_ANTIALIASING, CFG_BOTTOM_LIFT_DISTANCE, CFG_BOTTOM_LIFT_SPEED, CFG_DELAY_BEFORE_EXPOSURE, CFG_LIFT_DISTANCE, CFG_LIFT_SPEED, CFG_RETRACT_SPEED, crop_value(), Slic3r::anycubicsla_format_header::delay_before_exposure_s, Slic3r::Enable, Slic3r::anycubicsla_format_header::exposure_time_s, fill_header(), Slic3r::PrintBase::full_print_config(), get_cfg_value_f(), get_cfg_value_i(), Slic3r::ConfigOptionResolver::has(), Slic3r::anycubicsla_format_header::layer_height_mm, Slic3r::anycubicsla_format_header::lift_distance_mm, Slic3r::anycubicsla_format_header::lift_speed_mms, Slic3r::ConfigBase::load_from_ini_string(), Slic3r::SLAPrintStatistics::objects_used_material, Slic3r::ConfigBase::option(), Slic3r::anycubicsla_format_header::payload_size, Slic3r::anycubicsla_format_header::per_layer_override, Slic3r::anycubicsla_format_header::pixel_size_um, Slic3r::anycubicsla_format_header::price, Slic3r::anycubicsla_format_header::price_currency, Slic3r::SLAPrint::print_statistics(), Slic3r::anycubicsla_format_header::print_time_s, Slic3r::anycubicsla_format_header::res_x, Slic3r::anycubicsla_format_header::res_y, Slic3r::anycubicsla_format_header::retract_speed_mms, Slic3r::ConfigOption::serialize(), Slic3r::SLAPrintStatistics::support_used_material, Slic3r::anycubicsla_format_header::tag, Slic3r::anycubicsla_format_header::volume_ml, and Slic3r::anycubicsla_format_header::weight_g.
Referenced by fill_header().
fill_preview()
void Slic3r::anonymous_namespace{AnycubicSLA.cpp}::fill_preview (anycubicsla_format_preview & p, anycubicsla_format_misc & , const ThumbnailsList & thumbnails)
{
    p.preview_w    = PREV_W;
    p.preview_h    = PREV_H;
    p.preview_dpi  = PREV_DPI;
    p.payload_size = sizeof(p) - sizeof(p.tag) - sizeof(p.payload_size);
    std::memset(p.pixels, 0 , sizeof(p.pixels));
    if (!thumbnails.empty()) {
        std::uint32_t dst_index;
        std::uint32_t i = 0;
        size_t len;
        size_t pixel_x = 0;
        auto t = thumbnails[0]; //use the first thumbnail
        len = t.pixels.size();
        //sanity check
        if (len != PREV_W * PREV_H * 4)  {
            printf("incorrect thumbnail size. expected %ix%i\n", PREV_W, PREV_H);
            return;
        }
        // rearange pixels: they seem to be stored from bottom to top.
        dst_index = (PREV_W * (PREV_H - 1) * 2);
        while (i < len) {
            std::uint32_t pixel;
            std::uint32_t r = t.pixels[i++];
            std::uint32_t g = t.pixels[i++];
            std::uint32_t b = t.pixels[i++];
            i++; // Alpha
            // convert to BGRA565
            pixel = ((b >> 3) << 11) | ((g >>2) << 5) | (r >> 3);
            p.pixels[dst_index++] = pixel & 0xFF;
            p.pixels[dst_index++] = (pixel >> 8) & 0xFF;
            pixel_x++;
            if (pixel_x == PREV_W) {
                pixel_x = 0;
                dst_index -= (PREV_W * 4);
            }
        }
    }
}
References fill_preview(), Slic3r::anycubicsla_format_preview::payload_size, Slic3r::anycubicsla_format_preview::pixels, PREV_DPI, PREV_H, PREV_W, Slic3r::anycubicsla_format_preview::preview_dpi, Slic3r::anycubicsla_format_preview::preview_h, Slic3r::anycubicsla_format_preview::preview_w, and Slic3r::anycubicsla_format_preview::tag.
Referenced by fill_preview().
get_cfg_value_f()
std::float_t Slic3r::anonymous_namespace{AnycubicSLA.cpp}::get_cfg_value_f (const DynamicConfig & cfg, const std::string & key, const std::float_t & def = 0.f)
{
    if (cfg.has(key)) {
        if (auto opt = cfg.option(key))
            return opt->getFloat();
    }
    return def;
}
References get_cfg_value_f(), Slic3r::ConfigOptionResolver::has(), and Slic3r::ConfigBase::option().
Referenced by fill_header(), and get_cfg_value_f().
get_cfg_value_i()
int Slic3r::anonymous_namespace{AnycubicSLA.cpp}::get_cfg_value_i (const DynamicConfig & cfg, const std::string & key, const int & def = 0)
{
    if (cfg.has(key)) {
        if (auto opt = cfg.option(key))
            return opt->getInt();
    }
    return def;
}
References get_cfg_value_i(), Slic3r::ConfigOptionResolver::has(), and Slic3r::ConfigBase::option().
Referenced by fill_header(), and get_cfg_value_i().