Prusa Slicer: Slic3r::ConfigOptionBoolsTempl< NULLABLE > Class Template Reference
Slic3r::ConfigOptionBoolsTempl< NULLABLE > Class Template Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionBoolsTempl ()
ConfigOptionBoolsTempl (size_t n, bool value)
ConfigOptionBoolsTempl (std::initializer_list< bool > il)
ConfigOptionBoolsTempl (std::initializer_list< unsigned char > il)
ConfigOptionBoolsTempl (const std::vector< unsigned char > &vec)
ConfigOptionBoolsTempl (std::vector< unsigned char > &&vec)
ConfigOptionType type () const override
ConfigOption * clone () const override
ConfigOptionBoolsTempl & operator= (const ConfigOption *opt)
bool operator== (const ConfigOptionBoolsTempl &rhs) const throw ()
bool operator< (const ConfigOptionBoolsTempl &rhs) const throw ()
bool nullable () const override
bool is_nil () const override
bool is_nil (size_t idx) const override
bool & get_at (size_t i)
bool get_at (size_t i) const
std::string serialize () const override
std::vector< std::string > vserialize () const override
ConfigHelpers::DeserializationResult deserialize_with_substitutions (const std::string &str, bool append, ConfigHelpers::DeserializationSubstitution substitution)
bool deserialize (const std::string &str, bool append=false) override
void set (const ConfigOption *rhs) override
void set (const std::vector< const ConfigOption * > &rhs) override
void set_at (const ConfigOption *rhs, size_t i, size_t j) override
void resize (size_t n, const ConfigOption *opt_default=nullptr) override
void clear () override
size_t size () const override
bool empty () const override
bool operator== (const ConfigOption &rhs) const override
bool operator== (const std::vector< unsigned char > &rhs) const throw ()
bool operator!= (const std::vector< unsigned char > &rhs) const throw ()
bool operator!= (const ConfigOption &rhs) const
size_t hash () const override throw ()
bool overriden_by (const ConfigOption *rhs) const override
bool apply_override (const ConfigOption *rhs) override
virtual int getInt () const
virtual double getFloat () const
virtual bool getBool () const
virtual void setInt (int)
bool is_scalar () const
bool is_vector () const
Static Public Member Functions
static ConfigOptionType static_type ()
static unsigned char nil_value ()
Public Attributes
std::vector< unsigned char > values
Protected Member Functions
void serialize_single_value (std::ostringstream &ss, const unsigned char v) const
ConfigOptionType scalar_type () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
template<bool NULLABLE>
class Slic3r::ConfigOptionBoolsTempl< NULLABLE >
Constructor & Destructor Documentation
ConfigOptionBoolsTempl() [1/6]
template<bool NULLABLE> Slic3r::ConfigOptionBoolsTempl< NULLABLE >::ConfigOptionBoolsTempl () inline
: ConfigOptionVector<unsigned char>() {}
Referenced by Slic3r::ConfigOptionBoolsTempl< NULLABLE >::clone().
ConfigOptionBoolsTempl() [2/6]
template<bool NULLABLE> Slic3r::ConfigOptionBoolsTempl< NULLABLE >::ConfigOptionBoolsTempl (size_t n, bool value) inline explicit
: ConfigOptionVector<unsigned char>(n, (unsigned char)value) {}
ConfigOptionBoolsTempl() [3/6]
template<bool NULLABLE> Slic3r::ConfigOptionBoolsTempl< NULLABLE >::ConfigOptionBoolsTempl (std::initializer_list< bool > il) inline explicit
{ values.reserve(il.size()); for (bool b : il) values.emplace_back((unsigned char)b); }
References Slic3r::ConfigOptionVector< unsigned char >::values.
ConfigOptionBoolsTempl() [4/6]
template<bool NULLABLE> Slic3r::ConfigOptionBoolsTempl< NULLABLE >::ConfigOptionBoolsTempl (std::initializer_list< unsigned char > il) inline explicit
{ values.reserve(il.size()); for (unsigned char b : il) values.emplace_back(b); }
References Slic3r::ConfigOptionVector< unsigned char >::values.
ConfigOptionBoolsTempl() [5/6]
template<bool NULLABLE> Slic3r::ConfigOptionBoolsTempl< NULLABLE >::ConfigOptionBoolsTempl (const std::vector< unsigned char > & vec) inline explicit
: ConfigOptionVector<unsigned char>(vec) {}
ConfigOptionBoolsTempl() [6/6]
template<bool NULLABLE> Slic3r::ConfigOptionBoolsTempl< NULLABLE >::ConfigOptionBoolsTempl (std::vector< unsigned char > && vec) inline explicit
: ConfigOptionVector<unsigned char>(std::move(vec)) {}
Member Function Documentation
apply_override()
bool Slic3r::ConfigOptionVector< unsigned char >::apply_override (const ConfigOption * rhs) inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
      throw ConfigurationError("ConfigOptionVector.apply_override() applied to different types.");
    auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
    if (! rhs->nullable()) {
        // Overridding a non-nullable object with another non-nullable object.
        if (this->values != rhs_vec->values) {
          this->values = rhs_vec->values;
          return true;
        }
        return false;
      }
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      bool   modified = false;
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i]) {
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i)) {
          if (this->values.empty())
            this->values.resize(i + 1);
          else
            this->values.resize(i + 1, this->values.front());
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
        return modified;
    }
clear()
void Slic3r::ConfigOptionVector< unsigned char >::clear () inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ this->values.clear(); }
clone()
template<bool NULLABLE> ConfigOption * Slic3r::ConfigOptionBoolsTempl< NULLABLE >::clone () const inline override virtual
Implements Slic3r::ConfigOption.
{ return new ConfigOptionBoolsTempl(*this); }
References Slic3r::ConfigOptionBoolsTempl< NULLABLE >::ConfigOptionBoolsTempl().
deserialize()
template<bool NULLABLE> bool Slic3r::ConfigOptionBoolsTempl< NULLABLE >::deserialize (const std::string & str, bool append = false) inline override virtual
Implements Slic3r::ConfigOption.
    {
      return this->deserialize_with_substitutions(str, append, ConfigHelpers::DeserializationSubstitution::Disabled) == ConfigHelpers::DeserializationResult::Loaded;
    }
References Slic3r::append(), Slic3r::ConfigOptionBoolsTempl< NULLABLE >::deserialize_with_substitutions(), Slic3r::ConfigHelpers::Disabled, and Slic3r::ConfigHelpers::Loaded.
deserialize_with_substitutions()
template<bool NULLABLE> ConfigHelpers::DeserializationResult Slic3r::ConfigOptionBoolsTempl< NULLABLE >::deserialize_with_substitutions (const std::string & str, bool append, ConfigHelpers::DeserializationSubstitution substitution) inline
    {
        if (! append)
            this->values.clear();
        std::istringstream is(str);
        std::string item_str;
        bool substituted = false;
        while (std::getline(is, item_str, ',')) {
          boost::trim(item_str);
          unsigned char new_value = 0;
          if (item_str == "nil") {
            if (NULLABLE)
                    new_value = nil_value();
            else
                    throw ConfigurationError("Deserializing nil into a non-nullable object");
          } else if (item_str == "1") {
            new_value = true;
          } else if (item_str == "0") {
            new_value = false;
          } else if (substitution != ConfigHelpers::DeserializationSubstitution::Disabled && ConfigHelpers::looks_like_enum_value(item_str)) {
            new_value = ConfigHelpers::enum_looks_like_true_value(item_str) || substitution == ConfigHelpers::DeserializationSubstitution::DefaultsToTrue;
            substituted = true;
          } else
            return ConfigHelpers::DeserializationResult::Failed;
            this->values.push_back(new_value);
        }
        return substituted ? ConfigHelpers::DeserializationResult::Substituted : ConfigHelpers::DeserializationResult::Loaded;
    }
References Slic3r::append(), Slic3r::ConfigHelpers::DefaultsToTrue, Slic3r::ConfigHelpers::Disabled, Slic3r::ConfigHelpers::enum_looks_like_true_value(), Slic3r::ConfigHelpers::Failed, Slic3r::ConfigHelpers::Loaded, Slic3r::ConfigHelpers::looks_like_enum_value(), Slic3r::ConfigOptionBoolsTempl< NULLABLE >::nil_value(), and Slic3r::ConfigHelpers::Substituted.
Referenced by Slic3r::ConfigOptionBoolsTempl< NULLABLE >::deserialize().
empty()
bool Slic3r::ConfigOptionVector< unsigned char >::empty () const inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.empty(); }
get_at() [1/2]
template<bool NULLABLE> bool & Slic3r::ConfigOptionBoolsTempl< NULLABLE >::get_at (size_t i) inline
{
        assert(! this->values.empty());
        return *reinterpret_cast<bool*>(&((i < this->values.size()) ? this->values[i] : this->values.front()));
    }
Referenced by Slic3r::GUI::get_string_value().
get_at() [2/2]
template<bool NULLABLE> bool Slic3r::ConfigOptionBoolsTempl< NULLABLE >::get_at (size_t i) const inline
{ return ((i < this->values.size()) ? this->values[i] : this->values.front()) != 0; }
References Slic3r::ConfigOptionVector< unsigned char >::values.
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
virtual int Slic3r::ConfigOption::getInt () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::getInt on a non-int ConfigOption"); }
Referenced by Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
hash()
size_t Slic3r::ConfigOptionVector< unsigned char >::hash () const throw () inline override virtual inherited
Implements Slic3r::ConfigOption.
{
        std::hash<T> hasher;
        size_t seed = 0;
        for (const auto &v : this->values)
            boost::hash_combine(seed, hasher(v));
        return seed;
    }
is_nil() [1/2]
template<bool NULLABLE> bool Slic3r::ConfigOptionBoolsTempl< NULLABLE >::is_nil () const inline override virtual
Reimplemented from Slic3r::ConfigOption.
{ for (auto v : this->values) if (v != nil_value()) return false; return true; }
References Slic3r::ConfigOptionBoolsTempl< NULLABLE >::nil_value(), and Slic3r::ConfigOptionVector< unsigned char >::values.
is_nil() [2/2]
template<bool NULLABLE> bool Slic3r::ConfigOptionBoolsTempl< NULLABLE >::is_nil (size_t idx) const inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values[idx < values.size() ? idx : 0] == nil_value(); }
References Slic3r::ConfigOptionBoolsTempl< NULLABLE >::nil_value(), and Slic3r::ConfigOptionVector< unsigned char >::values.
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nil_value()
template<bool NULLABLE> static unsigned char Slic3r::ConfigOptionBoolsTempl< NULLABLE >::nil_value () inline static
{ return std::numeric_limits<unsigned char>::max(); }
Referenced by Slic3r::GUI::add_config_substitutions(), Slic3r::ConfigOptionBoolsTempl< NULLABLE >::deserialize_with_substitutions(), Slic3r::GUI::CheckBox::get_value(), Slic3r::ConfigOptionBoolsTempl< NULLABLE >::is_nil(), Slic3r::ConfigOptionBoolsTempl< NULLABLE >::is_nil(), Slic3r::ConfigOptionBoolsTempl< NULLABLE >::serialize_single_value(), and Slic3r::GUI::CheckBox::set_value().
nullable()
template<bool NULLABLE> bool Slic3r::ConfigOptionBoolsTempl< NULLABLE >::nullable () const inline override virtual
Reimplemented from Slic3r::ConfigOption.
{ return NULLABLE; }
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
bool Slic3r::ConfigOptionVector< unsigned char >::operator!= (const std::vector< unsigned char > & rhs) const throw () inline inherited
{ return this->values != rhs; }
operator<()
template<bool NULLABLE> bool Slic3r::ConfigOptionBoolsTempl< NULLABLE >::operator< (const ConfigOptionBoolsTempl< NULLABLE > & rhs) const throw () inline
{ return this->values <  rhs.values; }
operator=()
template<bool NULLABLE> ConfigOptionBoolsTempl & Slic3r::ConfigOptionBoolsTempl< NULLABLE >::operator= (const ConfigOption * opt) inline
{ this->set(opt); return *this; }
References Slic3r::ConfigOptionVector< unsigned char >::set().
operator==() [1/3]
bool Slic3r::ConfigOptionVector< unsigned char >::operator== (const ConfigOption & rhs) const inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionVector: Comparing incompatible types");
        assert(dynamic_cast<const ConfigOptionVector<T>*>(&rhs));
        return this->values == static_cast<const ConfigOptionVector<T>*>(&rhs)->values;
    }
operator==() [2/3]
template<bool NULLABLE> bool Slic3r::ConfigOptionBoolsTempl< NULLABLE >::operator== (const ConfigOptionBoolsTempl< NULLABLE > & rhs) const throw () inline
{ return this->values == rhs.values; }
operator==() [3/3]
bool Slic3r::ConfigOptionVector< unsigned char >::operator== (const std::vector< unsigned char > & rhs) const throw () inline inherited
{ return this->values == rhs; }
overriden_by()
bool Slic3r::ConfigOptionVector< unsigned char >::overriden_by (const ConfigOption * rhs) const inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector.overriden_by() applied to different types.");
      auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
      if (! rhs->nullable())
        // Overridding a non-nullable object with another non-nullable object.
        return this->values != rhs_vec->values;
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i])
          return true;
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i))
          return true;
      return false;
    }
resize()
void Slic3r::ConfigOptionVector< unsigned char >::resize (size_t n, const ConfigOption * opt_default = nullptr) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        assert(opt_default == nullptr || opt_default->is_vector());
//        assert(opt_default == nullptr || dynamic_cast<ConfigOptionVector<T>>(opt_default));
        assert(! this->values.empty() || opt_default != nullptr);
        if (n == 0)
            this->values.clear();
        else if (n < this->values.size())
            this->values.erase(this->values.begin() + n, this->values.end());
        else if (n > this->values.size()) {
            if (this->values.empty()) {
                if (opt_default == nullptr)
                    throw ConfigurationError("ConfigOptionVector::resize(): No default value provided.");
                if (opt_default->type() != this->type())
                    throw ConfigurationError("ConfigOptionVector::resize(): Extending with an incompatible type.");
                this->values.resize(n, static_cast<const ConfigOptionVector<T>*>(opt_default)->values.front());
            } else {
                // Resize by duplicating the last value.
                this->values.resize(n, this->values./*back*/front());
            }
        }
    }
scalar_type()
ConfigOptionType Slic3r::ConfigOptionVectorBase::scalar_type () const inline protected inherited
{ return static_cast<ConfigOptionType>(this->type() - coVectorType); }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::ConfigOptionVector< T >::set(), and Slic3r::ConfigOptionVector< T >::set_at().
serialize() [1/2]
template<bool NULLABLE> std::string Slic3r::ConfigOptionBoolsTempl< NULLABLE >::serialize () const inline override virtual
Implements Slic3r::ConfigOption.
    {
        std::ostringstream ss;
        for (const unsigned char &v : this->values) {
            if (&v != &this->values.front())
              ss << ",";
      this->serialize_single_value(ss, v);
    }
        return ss.str();
    }
References Slic3r::ConfigOptionBoolsTempl< NULLABLE >::serialize_single_value(), and Slic3r::ConfigOptionVector< unsigned char >::values.
serialize() [2/2]
template<bool NULLABLE> template<class Archive > void Slic3r::ConfigOptionBoolsTempl< NULLABLE >::serialize (Archive & ar) inline private
{ ar(cereal::base_class<ConfigOptionVector<unsigned char>>(this)); }
serialize_single_value()
template<bool NULLABLE> void Slic3r::ConfigOptionBoolsTempl< NULLABLE >::serialize_single_value (std::ostringstream & ss, const unsigned char v) const inline protected
{
          if (v == nil_value()) {
            if (NULLABLE)
              ss << "nil";
            else
                    throw ConfigurationError("Serializing NaN");
          } else
            ss << (v ? "1" : "0");
  }
References Slic3r::ConfigOptionBoolsTempl< NULLABLE >::nil_value().
Referenced by Slic3r::ConfigOptionBoolsTempl< NULLABLE >::serialize(), and Slic3r::ConfigOptionBoolsTempl< NULLABLE >::vserialize().
set() [1/2]
void Slic3r::ConfigOptionVector< unsigned char >::set (const ConfigOption * rhs) inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector: Assigning an incompatible type");
        assert(dynamic_cast<const ConfigOptionVector<T>*>(rhs));
        this->values = static_cast<const ConfigOptionVector<T>*>(rhs)->values;
    }
set() [2/2]
void Slic3r::ConfigOptionVector< unsigned char >::set (const std::vector< const ConfigOption * > & rhs) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        this->values.clear();
        this->values.reserve(rhs.size());
        for (const ConfigOption *opt : rhs) {
            if (opt->type() == this->type()) {
                auto other = static_cast<const ConfigOptionVector<T>*>(opt);
                if (other->values.empty())
                    throw ConfigurationError("ConfigOptionVector::set(): Assigning from an empty vector");
                this->values.emplace_back(other->values.front());
            } else if (opt->type() == this->scalar_type())
                this->values.emplace_back(static_cast<const ConfigOptionSingle<T>*>(opt)->value);
            else
                throw ConfigurationError("ConfigOptionVector::set():: Assigning an incompatible type");
        }
    }
set_at()
void Slic3r::ConfigOptionVector< unsigned char >::set_at (const ConfigOption * rhs, size_t i, size_t j) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        // It is expected that the vector value has at least one value, which is the default, if not overwritten.
        assert(! this->values.empty());
        if (this->values.size() <= i) {
            // Resize this vector, fill in the new vector fields with the copy of the first field.
            T v = this->values.front();
            this->values.resize(i + 1, v);
        }
        if (rhs->type() == this->type()) {
            // Assign the first value of the rhs vector.
            auto other = static_cast<const ConfigOptionVector<T>*>(rhs);
            if (other->values.empty())
                throw ConfigurationError("ConfigOptionVector::set_at(): Assigning from an empty vector");
            this->values[i] = other->get_at(j);
        } else if (rhs->type() == this->scalar_type())
            this->values[i] = static_cast<const ConfigOptionSingle<T>*>(rhs)->value;
        else
            throw ConfigurationError("ConfigOptionVector::set_at(): Assigning an incompatible type");
    }
setInt()
virtual void Slic3r::ConfigOption::setInt (int) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::setInt on a non-int ConfigOption"); }
size()
size_t Slic3r::ConfigOptionVector< unsigned char >::size () const inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.size(); }
static_type()
template<bool NULLABLE> static ConfigOptionType Slic3r::ConfigOptionBoolsTempl< NULLABLE >::static_type () inline static
{ return coBools; }
References Slic3r::coBools.
Referenced by Slic3r::ConfigOptionBoolsTempl< NULLABLE >::type().
type()
template<bool NULLABLE> ConfigOptionType Slic3r::ConfigOptionBoolsTempl< NULLABLE >::type () const inline override virtual
Implements Slic3r::ConfigOption.
{ return static_type(); }
References Slic3r::ConfigOptionBoolsTempl< NULLABLE >::static_type().
vserialize()
template<bool NULLABLE> std::vector< std::string > Slic3r::ConfigOptionBoolsTempl< NULLABLE >::vserialize () const inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
    {
        std::vector<std::string> vv;
        for (const unsigned char v : this->values) {
      std::ostringstream ss;
      this->serialize_single_value(ss, v);
            vv.push_back(ss.str());
        }
        return vv;
    }
References Slic3r::ConfigOptionBoolsTempl< NULLABLE >::serialize_single_value(), and Slic3r::ConfigOptionVector< unsigned char >::values.
Friends And Related Symbol Documentation
cereal::access
template<bool NULLABLE> friend class cereal::access friend
Member Data Documentation
values
std::vector<unsigned char > Slic3r::ConfigOptionVector< unsigned char >::values inherited
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp