Prusa Slicer: Slic3r::GUI::SLAImportDialog Class Reference
Slic3r::GUI::SLAImportDialog Class Reference
#include <src/slic3r/GUI/Jobs/SLAImportDialog.hpp>
Public Types
enum Sel { modelAndProfile , profileOnly , modelOnly }
Public Member Functions
SLAImportDialog (Plater *plater)
int ShowModal () override
Sel get_selection () const override
SLAImportQuality get_quality () const override
std::string get_path () const override
std::string get_archive_format () const override
Private Attributes
wxFilePickerCtrl * m_filepicker
wxComboBox * m_import_dropdown
wxComboBox * m_quality_dropdown
Detailed Description
Member Enumeration Documentation
Sel
enum Slic3r::GUI::SLAImportJobView::Sel inherited
Enumerator
modelAndProfile
profileOnly
modelOnly
{ modelAndProfile, profileOnly, modelOnly};
Constructor & Destructor Documentation
SLAImportDialog()
Slic3r::GUI::SLAImportDialog::SLAImportDialog (Plater * plater) inline
        : wxDialog{plater, wxID_ANY, "Import SLA archive"}
    {
        auto szvert = new wxBoxSizer{wxVERTICAL};
        auto szfilepck = new wxBoxSizer{wxHORIZONTAL};
        m_filepicker = new wxFilePickerCtrl(this, wxID_ANY,
                                            from_u8(wxGetApp().app_config->get_last_dir()), _(L("Choose SLA archive:")),
                                            get_readers_wildcard(),
                                            wxDefaultPosition, wxDefaultSize, wxFLP_DEFAULT_STYLE | wxFD_OPEN | wxFD_FILE_MUST_EXIST);
        szfilepck->Add(new wxStaticText(this, wxID_ANY, _L("Import file") + ": "), 0, wxALIGN_CENTER);
        szfilepck->Add(m_filepicker, 1);
        szvert->Add(szfilepck, 0, wxALL | wxEXPAND, 5);
        auto szchoices = new wxBoxSizer{wxHORIZONTAL};
        static const std::vector<wxString> inp_choices = {
            _(L("Import model and profile")),
            _(L("Import profile only")),
            _(L("Import model only"))
        };
        m_import_dropdown = new wxComboBox(
            this, wxID_ANY, inp_choices[0], wxDefaultPosition, wxDefaultSize,
            inp_choices.size(), inp_choices.data(), wxCB_READONLY | wxCB_DROPDOWN);
        szchoices->Add(m_import_dropdown);
        szchoices->AddStretchSpacer(1);
        szchoices->Add(new wxStaticText(this, wxID_ANY, _L("Quality") + ": "), 0, wxALIGN_CENTER | wxALL, 5);
        static const std::vector<wxString> qual_choices = {
            _(L("Accurate")),
            _(L("Balanced")),
            _(L("Quick"))
        };
        m_quality_dropdown = new wxComboBox(
            this, wxID_ANY, qual_choices[1], wxDefaultPosition, wxDefaultSize,
            qual_choices.size(), qual_choices.data(), wxCB_READONLY | wxCB_DROPDOWN);
        szchoices->Add(m_quality_dropdown, 1);
        m_import_dropdown->Bind(wxEVT_COMBOBOX, [this](wxCommandEvent &) {
            if (get_selection() == Sel::profileOnly)
                m_quality_dropdown->Disable();
            else m_quality_dropdown->Enable();
        });
        szvert->Add(szchoices, 1, wxEXPAND | wxALL, 5);
        auto szbtn = new wxBoxSizer(wxHORIZONTAL);
        szbtn->Add(new wxButton{this, wxID_CANCEL}, 0, wxRIGHT, 5);
        szbtn->Add(new wxButton{this, wxID_OK});
        szvert->Add(szbtn, 0, wxALIGN_RIGHT | wxALL, 5);
        SetSizerAndFit(szvert);
        wxGetApp().UpdateDlgDarkUI(this);
    }
References _, _L, Slic3r::GUI::from_u8(), Slic3r::GUI::get_readers_wildcard(), get_selection(), L, m_filepicker, m_import_dropdown, m_quality_dropdown, and Slic3r::GUI::SLAImportJobView::profileOnly.
Member Function Documentation
get_archive_format()
std::string Slic3r::GUI::SLAImportDialog::get_archive_format () const inline override virtual
Reimplemented from Slic3r::GUI::SLAImportJobView.
    {
        // TODO: the choosen format is inside the file dialog which is not
        // accessible from the file picker object. The file picker could be
        // changed to a custom file dialog.
        return {};
    }
get_path()
std::string Slic3r::GUI::SLAImportDialog::get_path () const inline override virtual
Implements Slic3r::GUI::SLAImportJobView.
    {
        return m_filepicker->GetPath().ToUTF8().data();
    }
References m_filepicker.
get_quality()
SLAImportQuality Slic3r::GUI::SLAImportDialog::get_quality () const inline override virtual
Implements Slic3r::GUI::SLAImportJobView.
    {
        switch(m_quality_dropdown->GetSelection())
        {
        case 2: return SLAImportQuality::Fast;
        case 1: return SLAImportQuality::Balanced;
        case 0: return SLAImportQuality::Accurate;
        default:
            return SLAImportQuality::Balanced;
        }
    }
References Slic3r::Accurate, Slic3r::Balanced, Slic3r::Fast, and m_quality_dropdown.
get_selection()
Sel Slic3r::GUI::SLAImportDialog::get_selection () const inline override virtual
Implements Slic3r::GUI::SLAImportJobView.
    {
        int sel = m_import_dropdown->GetSelection();
        return Sel(std::min(int(Sel::modelOnly), std::max(0, sel)));
    }
References m_import_dropdown, and Slic3r::GUI::SLAImportJobView::modelOnly.
Referenced by SLAImportDialog().
ShowModal()
int Slic3r::GUI::SLAImportDialog::ShowModal () inline override
    {
        CenterOnParent();
        return wxDialog::ShowModal();
    }
Member Data Documentation
m_filepicker
wxFilePickerCtrl* Slic3r::GUI::SLAImportDialog::m_filepicker private
Referenced by SLAImportDialog(), and get_path().
m_import_dropdown
wxComboBox* Slic3r::GUI::SLAImportDialog::m_import_dropdown private
Referenced by SLAImportDialog(), and get_selection().
m_quality_dropdown
wxComboBox * Slic3r::GUI::SLAImportDialog::m_quality_dropdown private
Referenced by SLAImportDialog(), and get_quality().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Jobs/SLAImportDialog.hpp