Prusa Slicer: libnest2d::selections::_FillerSelection< RawShape > Class Template Reference
libnest2d::selections::_FillerSelection< RawShape > Class Template Reference
#include <src/libnest2d/include/libnest2d/selections/filler.hpp>
Public Types
using Config = int
using Item = _Item< RawShape >
using ShapeType = RawShape
using PackGroup = _PackGroup< RawShape >
Public Member Functions
void configure (const Config &)
template<class TPlacer , class TIterator , class TBin = typename PlacementStrategyLike<TPlacer>::BinType, class PConfig = typename PlacementStrategyLike<TPlacer>::Config>
void packItems (TIterator first, TIterator last, TBin &&bin, PConfig &&pconfig=PConfig())
const PackGroup & getResult () const
int lastPackedBinId () const
void progressIndicator (ProgressFunction fn)
void stopCondition (StopCondition cond)
void clear ()
Protected Member Functions
template<class Placer , class Container , class Bin , class PCfg >
void remove_unpackable_items (Container &c, const Bin &bin, const PCfg &pcfg)
Protected Attributes
ProgressFunction progress_ = [](unsigned){}
StopCondition stopcond_ = [](){ return false; }
int last_packed_bin_id_ = -1
Private Types
using Base = SelectionBoilerplate< RawShape >
using Container = ItemGroup
using ItemGroup = _ItemGroup< RawShape >
Private Attributes
Container store_
PackGroup packed_bins_
Detailed Description
template<class RawShape>
class libnest2d::selections::_FillerSelection< RawShape >
Member Typedef Documentation
Base
template<class RawShape > using libnest2d::selections::_FillerSelection< RawShape >::Base = SelectionBoilerplate<RawShape> private
Config
template<class RawShape > using libnest2d::selections::_FillerSelection< RawShape >::Config = int
Container
template<class RawShape > using libnest2d::selections::_FillerSelection< RawShape >::Container = ItemGroup private
Item
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::Item = _Item<RawShape>
ItemGroup
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::ItemGroup = _ItemGroup<RawShape> private
PackGroup
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::PackGroup = _PackGroup<RawShape> inherited
ShapeType
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::ShapeType = RawShape inherited
Member Function Documentation
clear()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::clear () inline inherited
{ packed_bins_.clear(); }
References libnest2d::selections::SelectionBoilerplate< RawShape >::packed_bins_.
configure()
template<class RawShape > void libnest2d::selections::_FillerSelection< RawShape >::configure (const Config &) inline
{ }
getResult()
template<class RawShape > const PackGroup & libnest2d::selections::SelectionBoilerplate< RawShape >::getResult () const inline inherited
{
        return packed_bins_;
    }
References libnest2d::selections::SelectionBoilerplate< RawShape >::packed_bins_.
lastPackedBinId()
template<class RawShape > int libnest2d::selections::SelectionBoilerplate< RawShape >::lastPackedBinId () const inline inherited
{ return last_packed_bin_id_; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::last_packed_bin_id_.
packItems()
template<class RawShape > template<class TPlacer , class TIterator , class TBin = typename PlacementStrategyLike<TPlacer>::BinType, class PConfig = typename PlacementStrategyLike<TPlacer>::Config> void libnest2d::selections::_FillerSelection< RawShape >::packItems (TIterator first, TIterator last, TBin && bin, PConfig && pconfig = PConfig()) inline
    {
        using Placer = PlacementStrategyLike<TPlacer>;
        store_.clear();
        auto total = last-first;
        store_.reserve(total);
        // TODO: support preloading
        packed_bins_.clear();
        packed_bins_.emplace_back();
        auto makeProgress = [this, &total](
                PlacementStrategyLike<TPlacer>& placer)
        {
            packed_bins_.back() = placer.getItems();
#ifndef NDEBUG
            packed_bins_.back().insert(packed_bins_.back().end(),
                                       placer.getDebugItems().begin(),
                                       placer.getDebugItems().end());
#endif
            this->progress_(--total);
        };
        std::copy(first, last, std::back_inserter(store_));
        auto sortfunc = [](Item& i1, Item& i2) {
            return i1.area() > i2.area();
        };
        this->template remove_unpackable_items<Placer>(store_, bin, pconfig);
        std::sort(store_.begin(), store_.end(), sortfunc);
        Placer placer(bin);
        placer.configure(pconfig);
        auto it = store_.begin();
        while(it != store_.end() && !this->stopcond_()) {
            if(!placer.pack(*it, {std::next(it), store_.end()}))  {
                if(packed_bins_.back().empty()) ++it;
                placer.clearItems();
                packed_bins_.emplace_back();
            } else {
                makeProgress(placer);
                ++it;
            }
        }
    }
References libnest2d::_Item< RawShape >::area(), libnest2d::selections::_FillerSelection< RawShape >::packed_bins_, libnest2d::selections::SelectionBoilerplate< RawShape >::progress_, and libnest2d::selections::_FillerSelection< RawShape >::store_.
progressIndicator()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::progressIndicator (ProgressFunction fn) inline inherited
{ progress_ = fn; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::progress_.
remove_unpackable_items()
template<class RawShape > template<class Placer , class Container , class Bin , class PCfg > void libnest2d::selections::SelectionBoilerplate< RawShape >::remove_unpackable_items (Container & c, const Bin & bin, const PCfg & pcfg) inline protected inherited
    {
        // Safety test: try to pack each item into an empty bin. If it fails
        // then it should be removed from the list
        auto it = c.begin();
        while (it != c.end() && !stopcond_()) {
            // WARNING: The copy of itm needs to be created before Placer.
            // Placer is working with references and its destructor still
            // manipulates the item this is why the order of stack creation
            // matters here.
            const Item& itm = *it;
            Item cpy{itm};
            Placer p{bin};
            p.configure(pcfg);
            if (itm.area() <= 0 || !p.pack(cpy)) {
                static_cast<Item&>(*it).binId(BIN_ID_UNSET);
                it = c.erase(it);
            }
            else it++;
        }
    }
References libnest2d::_Item< RawShape >::area(), libnest2d::BIN_ID_UNSET, libnest2d::_Item< RawShape >::binId(), and libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_.
stopCondition()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::stopCondition (StopCondition cond) inline inherited
{ stopcond_ = cond; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_.
Member Data Documentation
last_packed_bin_id_
template<class RawShape > int libnest2d::selections::SelectionBoilerplate< RawShape >::last_packed_bin_id_ = -1 protected inherited
Referenced by libnest2d::selections::SelectionBoilerplate< RawShape >::lastPackedBinId(), and libnest2d::selections::_FirstFitSelection< RawShape >::packItems().
packed_bins_
template<class RawShape > PackGroup libnest2d::selections::SelectionBoilerplate< RawShape >::packed_bins_ private
Referenced by libnest2d::selections::_FillerSelection< RawShape >::packItems().
progress_
template<class RawShape > ProgressFunction libnest2d::selections::SelectionBoilerplate< RawShape >::progress_ = [](unsigned){} protected inherited
Referenced by libnest2d::selections::_DJDHeuristic< RawShape >::packItems(), libnest2d::selections::_FillerSelection< RawShape >::packItems(), libnest2d::selections::_FirstFitSelection< RawShape >::packItems(), and libnest2d::selections::SelectionBoilerplate< RawShape >::progressIndicator().
stopcond_
template<class RawShape > StopCondition libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_ = [](){ return false; } protected inherited
Referenced by libnest2d::selections::_DJDHeuristic< RawShape >::packItems(), libnest2d::selections::_FirstFitSelection< RawShape >::packItems(), libnest2d::selections::SelectionBoilerplate< RawShape >::remove_unpackable_items(), and libnest2d::selections::SelectionBoilerplate< RawShape >::stopCondition().
store_
template<class RawShape > Container libnest2d::selections::_FillerSelection< RawShape >::store_ private
Referenced by libnest2d::selections::_FillerSelection< RawShape >::packItems().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/selections/filler.hpp