Prusa Slicer: ImGuiStorage Struct Reference
ImGuiStorage Struct Reference
#include <src/imgui/imgui.h>
Classes
struct ImGuiStoragePair
union ImGuiStoragePair.__unnamed674__
Public Member Functions
void Clear ()
IMGUI_API int GetInt (ImGuiID key, int default_val=0) const
IMGUI_API void SetInt (ImGuiID key, int val)
IMGUI_API bool GetBool (ImGuiID key, bool default_val=false) const
IMGUI_API void SetBool (ImGuiID key, bool val)
IMGUI_API float GetFloat (ImGuiID key, float default_val=0.0f) const
IMGUI_API void SetFloat (ImGuiID key, float val)
IMGUI_API void * GetVoidPtr (ImGuiID key) const
IMGUI_API void SetVoidPtr (ImGuiID key, void *val)
IMGUI_API int * GetIntRef (ImGuiID key, int default_val=0)
IMGUI_API bool * GetBoolRef (ImGuiID key, bool default_val=false)
IMGUI_API float * GetFloatRef (ImGuiID key, float default_val=0.0f)
IMGUI_API void ** GetVoidPtrRef (ImGuiID key, void *default_val=NULL)
IMGUI_API void SetAllInt (int val)
IMGUI_API void BuildSortByKey ()
Public Attributes
ImVector< ImGuiStoragePair > Data
Detailed Description
Class Documentation
ImGuiStorage::ImGuiStoragePair.__unnamed674__
union ImGuiStorage::ImGuiStoragePair.__unnamed674__
Class Members
float val_f
int val_i
void * val_p
Member Function Documentation
BuildSortByKey()
void ImGuiStorage::BuildSortByKey ()
{
    struct StaticFunc
    {
        static int IMGUI_CDECL PairCompareByID(const void* lhs, const void* rhs)
        {
            // We can't just do a subtraction because qsort uses signed integers and subtracting our ID doesn't play well with that.
            if (((const ImGuiStoragePair*)lhs)->key > ((const ImGuiStoragePair*)rhs)->key) return +1;
            if (((const ImGuiStoragePair*)lhs)->key < ((const ImGuiStoragePair*)rhs)->key) return -1;
            return 0;
        }
    };
    if (Data.Size > 1)
        ImQsort(Data.Data, (size_t)Data.Size, sizeof(ImGuiStoragePair), StaticFunc::PairCompareByID);
}
References Data, IMGUI_CDECL, and ImQsort.
Clear()
void ImGuiStorage::Clear () inline
{ Data.clear(); }
References ImVector< T >::clear().
Referenced by ImPool< T >::Clear(), and ImGui::Shutdown().
GetBool()
bool ImGuiStorage::GetBool (ImGuiID key, bool default_val = false) const
{
    return GetInt(key, default_val ? 1 : 0) != 0;
}
References GetInt().
GetBoolRef()
bool * ImGuiStorage::GetBoolRef (ImGuiID key, bool default_val = false)
{
    return (bool*)GetIntRef(key, default_val ? 1 : 0);
}
References GetIntRef().
GetFloat()
float ImGuiStorage::GetFloat (ImGuiID key, float default_val = 0.0f) const
{
    ImGuiStoragePair* it = LowerBound(const_cast<ImVector<ImGuiStoragePair>&>(Data), key);
    if (it == Data.end() || it->key != key)
        return default_val;
    return it->val_f;
}
References Data, ImGuiStorage::ImGuiStoragePair::key, and LowerBound().
GetFloatRef()
float * ImGuiStorage::GetFloatRef (ImGuiID key, float default_val = 0.0f)
{
    ImGuiStoragePair* it = LowerBound(Data, key);
    if (it == Data.end() || it->key != key)
        it = Data.insert(it, ImGuiStoragePair(key, default_val));
    return &it->val_f;
}
References Data, ImGuiStorage::ImGuiStoragePair::key, and LowerBound().
GetInt()
int ImGuiStorage::GetInt (ImGuiID key, int default_val = 0) const
{
    ImGuiStoragePair* it = LowerBound(const_cast<ImVector<ImGuiStoragePair>&>(Data), key);
    if (it == Data.end() || it->key != key)
        return default_val;
    return it->val_i;
}
References Data, ImGuiStorage::ImGuiStoragePair::key, and LowerBound().
Referenced by GetBool(), ImPool< T >::GetByKey(), and ImGui::TreeNodeBehaviorIsOpen().
GetIntRef()
int * ImGuiStorage::GetIntRef (ImGuiID key, int default_val = 0)
{
    ImGuiStoragePair* it = LowerBound(Data, key);
    if (it == Data.end() || it->key != key)
        it = Data.insert(it, ImGuiStoragePair(key, default_val));
    return &it->val_i;
}
References Data, ImGuiStorage::ImGuiStoragePair::key, and LowerBound().
Referenced by GetBoolRef(), and ImPool< T >::GetOrAddByKey().
GetVoidPtr()
void * ImGuiStorage::GetVoidPtr (ImGuiID key) const
{
    ImGuiStoragePair* it = LowerBound(const_cast<ImVector<ImGuiStoragePair>&>(Data), key);
    if (it == Data.end() || it->key != key)
        return NULL;
    return it->val_p;
}
References Data, ImGuiStorage::ImGuiStoragePair::key, and LowerBound().
Referenced by ImGui::FindWindowByID().
GetVoidPtrRef()
void ** ImGuiStorage::GetVoidPtrRef (ImGuiID key, void * default_val = NULL)
{
    ImGuiStoragePair* it = LowerBound(Data, key);
    if (it == Data.end() || it->key != key)
        it = Data.insert(it, ImGuiStoragePair(key, default_val));
    return &it->val_p;
}
References Data, ImGuiStorage::ImGuiStoragePair::key, and LowerBound().
SetAllInt()
void ImGuiStorage::SetAllInt (int val)
{
    for (int i = 0; i < Data.Size; i++)
        Data[i].val_i = v;
}
References Data.
SetBool()
void ImGuiStorage::SetBool (ImGuiID key, bool val)
{
    SetInt(key, val ? 1 : 0);
}
References SetInt().
SetFloat()
void ImGuiStorage::SetFloat (ImGuiID key, float val)
{
    ImGuiStoragePair* it = LowerBound(Data, key);
    if (it == Data.end() || it->key != key)
    {
        Data.insert(it, ImGuiStoragePair(key, val));
        return;
    }
    it->val_f = val;
}
References Data, ImGuiStorage::ImGuiStoragePair::key, and LowerBound().
SetInt()
void ImGuiStorage::SetInt (ImGuiID key, int val)
{
    ImGuiStoragePair* it = LowerBound(Data, key);
    if (it == Data.end() || it->key != key)
    {
        Data.insert(it, ImGuiStoragePair(key, val));
        return;
    }
    it->val_i = val;
}
References Data, ImGuiStorage::ImGuiStoragePair::key, and LowerBound().
Referenced by ImPool< T >::Remove(), SetBool(), ImGui::TreeNodeBehavior(), and ImGui::TreeNodeBehaviorIsOpen().
SetVoidPtr()
void ImGuiStorage::SetVoidPtr (ImGuiID key, void * val)
{
    ImGuiStoragePair* it = LowerBound(Data, key);
    if (it == Data.end() || it->key != key)
    {
        Data.insert(it, ImGuiStoragePair(key, val));
        return;
    }
    it->val_p = val;
}
References Data, ImGuiStorage::ImGuiStoragePair::key, and LowerBound().
Referenced by CreateNewWindow().
Member Data Documentation
Data
ImVector<ImGuiStoragePair> ImGuiStorage::Data
Referenced by BuildSortByKey(), ImPool< T >::Clear(), ImGui::DebugNodeStorage(), GetFloat(), GetFloatRef(), GetInt(), GetIntRef(), GetVoidPtr(), GetVoidPtrRef(), ImPool< T >::Reserve(), SetAllInt(), SetFloat(), SetInt(), and SetVoidPtr().
The documentation for this struct was generated from the following files:
src/imgui/imgui.h
src/imgui/imgui.cpp