Prusa Slicer: Slic3r::GUI::LayerRangeEditor Class Reference
Slic3r::GUI::LayerRangeEditor Class Reference
#include <src/slic3r/GUI/GUI_ObjectLayers.hpp>
Public Member Functions
LayerRangeEditor (ObjectLayers *parent, const wxString &value=wxEmptyString, EditorType type=etUndef, std::function< void(EditorType)> set_focus_data_fn=[](EditorType) {;}, std::function< bool(coordf_t, bool, bool)> edit_fn=[](coordf_t, bool, bool) {return false;})
~LayerRangeEditor ()
EditorType type () const
void set_focus_data () const
void msw_rescale ()
Private Member Functions
coordf_t get_value ()
Private Attributes
bool m_enter_pressed { false }
bool m_call_kill_focus { false }
wxString m_valid_value
EditorType m_type
std::function< void(EditorType)> m_set_focus_data
Detailed Description
Constructor & Destructor Documentation
LayerRangeEditor()
Slic3r::GUI::LayerRangeEditor::LayerRangeEditor (ObjectLayers * parent, const wxString & value = wxEmptyString, EditorType type = etUndef, std::function< void(EditorType)> set_focus_data_fn = [](EditorType) {;}, std::function< bool(coordf_t, bool, bool)> edit_fn = [](coordf_t, bool, bool) {return false; })
                                      :
    m_valid_value(value),
    m_type(type),
    m_set_focus_data(set_focus_data_fn),
    wxTextCtrl(parent->m_parent, wxID_ANY, value, wxDefaultPosition,
               wxSize(8 * em_unit(parent->m_parent), wxDefaultCoord), wxTE_PROCESS_ENTER
#ifdef _WIN32
        | wxBORDER_SIMPLE
#endif
    )
{
    this->SetFont(wxGetApp().normal_font());
    wxGetApp().UpdateDarkUI(this);
    // Reset m_enter_pressed flag to _false_, when value is editing
    this->Bind(wxEVT_TEXT, [this](wxEvent&) { m_enter_pressed = false; }, this->GetId());
    this->Bind(wxEVT_TEXT_ENTER, [this, edit_fn](wxEvent&)
    {
        m_enter_pressed     = true;
        // Workaround! Under Linux we have to use CallAfter() to avoid crash after pressing ENTER key
        // see #7531, #8055, #8408
#ifdef __linux__
        wxTheApp->CallAfter([this, edit_fn]() {
#endif
            // If LayersList wasn't updated/recreated, we can call wxEVT_KILL_FOCUS.Skip()
            if (m_type & etLayerHeight) {
                if (!edit_fn(get_value(), true, false))
                    SetValue(m_valid_value);
                else
                    m_valid_value = double_to_string(get_value());
                m_call_kill_focus = true;
            }
            else if (!edit_fn(get_value(), true, false)) {
                SetValue(m_valid_value);
                m_call_kill_focus = true;
            }
#ifdef __linux__
        });
#endif
    }, this->GetId());
    this->Bind(wxEVT_KILL_FOCUS, [this, edit_fn](wxFocusEvent& e)
    {
        if (!m_enter_pressed) {
#ifndef __WXGTK__
            /* Update data for next editor selection.
             * But under GTK it looks like there is no information about selected control at e.GetWindow(),
             * so we'll take it from wxEVT_LEFT_DOWN event
             * */
            LayerRangeEditor* new_editor = dynamic_cast<LayerRangeEditor*>(e.GetWindow());
            if (new_editor)
                new_editor->set_focus_data();
#endif // not __WXGTK__
            // If LayersList wasn't updated/recreated, we should call e.Skip()
            if (m_type & etLayerHeight) {
                if (!edit_fn(get_value(), false, dynamic_cast<ObjectLayers::PlusMinusButton*>(e.GetWindow()) != nullptr))
                    SetValue(m_valid_value);
                else
                    m_valid_value = double_to_string(get_value());
                e.Skip();
            }
            else if (!edit_fn(get_value(), false, dynamic_cast<ObjectLayers::PlusMinusButton*>(e.GetWindow()) != nullptr)) {
                SetValue(m_valid_value);
                e.Skip();
            }
        }
        else if (m_call_kill_focus) {
            m_call_kill_focus = false;
            e.Skip();
        }
    }, this->GetId());
    this->Bind(wxEVT_SET_FOCUS, [this, parent](wxFocusEvent& e)
    {
        set_focus_data();
        parent->update_scene_from_editor_selection();
        e.Skip();
    }, this->GetId());
#ifdef __WXGTK__ // Workaround! To take information about selectable range
    this->Bind(wxEVT_LEFT_DOWN, [this](wxEvent& e)
    {
        set_focus_data();
        e.Skip();
    }, this->GetId());
#endif //__WXGTK__
    this->Bind(wxEVT_CHAR, ([this](wxKeyEvent& event)
    {
        // select all text using Ctrl+A
        if (wxGetKeyState(wxKeyCode('A')) && wxGetKeyState(WXK_CONTROL))
            this->SetSelection(-1, -1); //select all
        event.Skip();
    }));
}
References Slic3r::GUI::double_to_string(), Slic3r::GUI::etLayerHeight, get_value(), m_call_kill_focus, m_enter_pressed, m_type, m_valid_value, set_focus_data(), and Slic3r::GUI::ObjectLayers::update_scene_from_editor_selection().
~LayerRangeEditor()
Slic3r::GUI::LayerRangeEditor::~LayerRangeEditor () inline
{}
Member Function Documentation
get_value()
coordf_t Slic3r::GUI::LayerRangeEditor::get_value () private
{
    wxString str = GetValue();
    coordf_t layer_height;
    const char dec_sep = is_decimal_separator_point() ? '.' : ',';
    const char dec_sep_alt = dec_sep == '.' ? ',' : '.';
    // Replace the first incorrect separator in decimal number.
    str.Replace(dec_sep_alt, dec_sep, false);
    if (str == ".")
        layer_height = 0.0;
    else if (!str.ToDouble(&layer_height) || layer_height < 0.0f) {
        show_error(m_parent, _L("Invalid numeric input."));
        assert(m_valid_value.ToDouble(&layer_height));
    }
    return layer_height;
}
References _L, Slic3r::is_decimal_separator_point(), Slic3r::layer_height(), m_valid_value, and Slic3r::GUI::show_error().
Referenced by LayerRangeEditor().
msw_rescale()
void Slic3r::GUI::LayerRangeEditor::msw_rescale ()
{
    SetMinSize(wxSize(8 * wxGetApp().em_unit(), wxDefaultCoord));
}
References em_unit().
set_focus_data()
void Slic3r::GUI::LayerRangeEditor::set_focus_data () const inline
{ m_set_focus_data(m_type);}
References m_set_focus_data, and m_type.
Referenced by LayerRangeEditor().
type()
EditorType Slic3r::GUI::LayerRangeEditor::type () const inline
{return m_type;}
References m_type.
Referenced by Slic3r::GUI::ObjectLayers::select_editor().
Member Data Documentation
m_call_kill_focus
bool Slic3r::GUI::LayerRangeEditor::m_call_kill_focus { false } private
Referenced by LayerRangeEditor().
m_enter_pressed
bool Slic3r::GUI::LayerRangeEditor::m_enter_pressed { false } private
Referenced by LayerRangeEditor().
m_set_focus_data
std::function<void(EditorType)> Slic3r::GUI::LayerRangeEditor::m_set_focus_data private
Referenced by set_focus_data().
m_type
EditorType Slic3r::GUI::LayerRangeEditor::m_type private
Referenced by LayerRangeEditor(), set_focus_data(), and type().
m_valid_value
wxString Slic3r::GUI::LayerRangeEditor::m_valid_value private
Referenced by LayerRangeEditor(), and get_value().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectLayers.hpp
src/slic3r/GUI/GUI_ObjectLayers.cpp