Prusa Slicer: Slic3r::MeshBoolean Namespace Reference
Slic3r::MeshBoolean Namespace Reference
Namespaces
namespace cgal
Typedefs
using MapMatrixXfUnaligned = Eigen::Map< const Eigen::Matrix< float, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor|Eigen::DontAlign > >
using MapMatrixXiUnaligned = Eigen::Map< const Eigen::Matrix< int, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor|Eigen::DontAlign > >
using EigenMesh = std::pair< Eigen::MatrixXd, Eigen::MatrixXi >
Functions
TriangleMesh eigen_to_triangle_mesh (const EigenMesh &emesh)
EigenMesh triangle_mesh_to_eigen (const TriangleMesh &mesh)
void minus (EigenMesh &A, const EigenMesh &B)
void minus (TriangleMesh &A, const TriangleMesh &B)
void self_union (EigenMesh &A)
void self_union (TriangleMesh &mesh)
Typedef Documentation
EigenMesh
using Slic3r::MeshBoolean::EigenMesh = typedef std::pair<Eigen::MatrixXd, Eigen::MatrixXi>
MapMatrixXfUnaligned
using Slic3r::MeshBoolean::MapMatrixXfUnaligned = typedef Eigen::Map<const Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor | Eigen::DontAlign> >
MapMatrixXiUnaligned
using Slic3r::MeshBoolean::MapMatrixXiUnaligned = typedef Eigen::Map<const Eigen::Matrix<int, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor | Eigen::DontAlign> >
Function Documentation
eigen_to_triangle_mesh()
TriangleMesh Slic3r::MeshBoolean::eigen_to_triangle_mesh (const EigenMesh & emesh)
{
    auto &VC = emesh.first; auto &FC = emesh.second;
    indexed_triangle_set its;
    its.vertices.reserve(size_t(VC.rows()));
    its.indices.reserve(size_t(FC.rows()));
    for (Eigen::Index i = 0; i < VC.rows(); ++i)
        its.vertices.emplace_back(VC.row(i).cast<float>());
    for (Eigen::Index i = 0; i < FC.rows(); ++i)
        its.indices.emplace_back(FC.row(i));
    return TriangleMesh { std::move(its) };
}
References indexed_triangle_set::indices, and indexed_triangle_set::vertices.
Referenced by minus(), and self_union().
minus() [1/2]
void Slic3r::MeshBoolean::minus (EigenMesh & A, const EigenMesh & B)
{
    auto &[VA, FA] = A;
    auto &[VB, FB] = B;
    Eigen::MatrixXd VC;
    Eigen::MatrixXi FC;
    igl::MeshBooleanType boolean_type(igl::MESH_BOOLEAN_TYPE_MINUS);
    igl::copyleft::cgal::mesh_boolean(VA, FA, VB, FB, boolean_type, VC, FC);
    VA = std::move(VC); FA = std::move(FC);
}
References igl::copyleft::cgal::mesh_boolean(), and igl::MESH_BOOLEAN_TYPE_MINUS.
Referenced by minus().
minus() [2/2]
void Slic3r::MeshBoolean::minus (TriangleMesh & A, const TriangleMesh & B)
{
    EigenMesh eA = triangle_mesh_to_eigen(A);
    minus(eA, triangle_mesh_to_eigen(B));
    A = eigen_to_triangle_mesh(eA);
}
References eigen_to_triangle_mesh(), minus(), and triangle_mesh_to_eigen().
self_union() [1/2]
void Slic3r::MeshBoolean::self_union (EigenMesh & A)
{
    EigenMesh result;
    auto &[V, F] = A;
    auto &[VC, FC] = result;
    igl::MeshBooleanType boolean_type(igl::MESH_BOOLEAN_TYPE_UNION);
    igl::copyleft::cgal::mesh_boolean(V, F, Eigen::MatrixXd(), Eigen::MatrixXi(), boolean_type, VC, FC);
    A = std::move(result);
}
References Slic3r::F, igl::copyleft::cgal::mesh_boolean(), and igl::MESH_BOOLEAN_TYPE_UNION.
Referenced by self_union().
self_union() [2/2]
void Slic3r::MeshBoolean::self_union (TriangleMesh & mesh)
{
    auto eM = triangle_mesh_to_eigen(mesh);
    self_union(eM);
    mesh = eigen_to_triangle_mesh(eM);
}
References eigen_to_triangle_mesh(), self_union(), and triangle_mesh_to_eigen().
triangle_mesh_to_eigen()
EigenMesh Slic3r::MeshBoolean::triangle_mesh_to_eigen (const TriangleMesh & mesh)
{
    EigenMesh emesh;
    emesh.first = MapMatrixXfUnaligned(mesh.its.vertices.front().data(),
                                       Eigen::Index(mesh.its.vertices.size()),
                                       3).cast<double>();
    emesh.second = MapMatrixXiUnaligned(mesh.its.indices.front().data(),
                                        Eigen::Index(mesh.its.indices.size()),
                                        3);
    return emesh;
}
References indexed_triangle_set::indices, Slic3r::TriangleMesh::its, and indexed_triangle_set::vertices.
Referenced by minus(), and self_union().