Prusa Slicer: Slic3r::GUI::GCodeViewer::COG Class Reference
Slic3r::GUI::GCodeViewer::COG Class Reference
Public Member Functions
void render ()
void reset ()
bool is_visible () const
void set_visible (bool visible)
void add_segment (const Vec3d &v1, const Vec3d &v2, double mass)
Vec3d cog () const
Private Member Functions
void init ()
Private Attributes
GLModel m_model
bool m_visible { false }
bool m_fixed_size { true }
double m_total_mass { 0.0 }
Vec3d m_position { Vec3d::Zero() }
Detailed Description
Member Function Documentation
add_segment()
void Slic3r::GUI::GCodeViewer::COG::add_segment (const Vec3d & v1, const Vec3d & v2, double mass) inline
{
            assert(mass > 0.0);
            m_position += mass * 0.5 * (v1 + v2);
            m_total_mass += mass;
        }
References m_position, and m_total_mass.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
cog()
Vec3d Slic3r::GUI::GCodeViewer::COG::cog () const inline
{ return (m_total_mass > 0.0) ? (Vec3d)(m_position / m_total_mass) : Vec3d::Zero(); }
References m_position, and m_total_mass.
init()
void Slic3r::GUI::GCodeViewer::COG::init () inline private
                    {
            if (m_model.is_initialized())
                return;
            const float radius = m_fixed_size ? 10.0f : 1.0f;
            m_model.init_from(smooth_sphere(32, radius));
        }
References Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), m_fixed_size, m_model, and Slic3r::GUI::smooth_sphere().
is_visible()
bool Slic3r::GUI::GCodeViewer::COG::is_visible () const inline
{ return m_visible; }
References m_visible.
Referenced by Slic3r::GUI::GCodeViewer::get_options_visibility_flags().
render()
void Slic3r::GUI::GCodeViewer::COG::render ()
{
    if (!m_visible)
        return;
    init();
    GLShaderProgram* shader = wxGetApp().get_shader("toolpaths_cog");
    if (shader == nullptr)
        return;
    shader->start_using();
    glsafe(::glDisable(GL_DEPTH_TEST));
    const Camera& camera = wxGetApp().plater()->get_camera();
    Transform3d model_matrix = Geometry::translation_transform(cog());
    if (m_fixed_size) {
        const double inv_zoom = camera.get_inv_zoom();
        model_matrix = model_matrix * Geometry::scale_transform(inv_zoom);
    }
    const Transform3d& view_matrix = camera.get_view_matrix();
    shader->set_uniform("view_model_matrix", view_matrix * model_matrix);
    shader->set_uniform("projection_matrix", camera.get_projection_matrix());
    const Matrix3d view_normal_matrix = view_matrix.matrix().block(0, 0, 3, 3) * model_matrix.matrix().block(0, 0, 3, 3).inverse().transpose();
    shader->set_uniform("view_normal_matrix", view_normal_matrix);
    m_model.render();
    shader->stop_using();
    //static float last_window_width = 0.0f;
    //static size_t last_text_length = 0;
    //ImGuiWrapper& imgui = *wxGetApp().imgui();
    //const Size cnv_size = wxGetApp().plater()->get_current_canvas3D()->get_canvas_size();
    //imgui.set_next_window_pos(0.5f * static_cast<float>(cnv_size.get_width()), 0.0f, ImGuiCond_Always, 0.5f, 0.0f);
    //ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    //ImGui::SetNextWindowBgAlpha(0.25f);
    //imgui.begin(std::string("COG"), ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoMove);
    //imgui.text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, _u8L("Center of mass") + ":");
    //ImGui::SameLine();
    //char buf[1024];
    //const Vec3d position = cog();
    //sprintf(buf, "X: %.3f, Y: %.3f, Z: %.3f", position.x(), position.y(), position.z());
    //imgui.text(std::string(buf));
    //const float width = ImGui::GetWindowWidth();
    //const size_t length = strlen(buf);
    //if (width != last_window_width || length != last_text_length) {
    //    last_window_width = width;
    //    last_text_length = length;
    //    imgui.set_requires_extra_frame();
    //}
    //imgui.end();
    //ImGui::PopStyleVar();
}
References Slic3r::GUI::Camera::get_inv_zoom(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), glsafe, Slic3r::GUI::GCodeViewer::init(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::Geometry::scale_transform(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), and Slic3r::Geometry::translation_transform().
Referenced by Slic3r::GUI::GCodeViewer::render_cog().
reset()
void Slic3r::GUI::GCodeViewer::COG::reset () inline
                     {
            m_position = Vec3d::Zero();
            m_total_mass = 0.0;
        }
References m_position, and m_total_mass.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
set_visible()
void Slic3r::GUI::GCodeViewer::COG::set_visible (bool visible) inline
{ m_visible = visible; }
References m_visible.
Referenced by Slic3r::GUI::GCodeViewer::set_options_visibility_from_flags().
Member Data Documentation
m_fixed_size
bool Slic3r::GUI::GCodeViewer::COG::m_fixed_size { true } private
Referenced by init().
m_model
GLModel Slic3r::GUI::GCodeViewer::COG::m_model private
Referenced by init().
m_position
Vec3d Slic3r::GUI::GCodeViewer::COG::m_position { Vec3d::Zero() } private
Referenced by add_segment(), cog(), and reset().
m_total_mass
double Slic3r::GUI::GCodeViewer::COG::m_total_mass { 0.0 } private
Referenced by add_segment(), cog(), and reset().
m_visible
bool Slic3r::GUI::GCodeViewer::COG::m_visible { false } private
Referenced by is_visible(), and set_visible().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GCodeViewer.hpp
src/slic3r/GUI/GCodeViewer.cpp