Prusa Slicer: Slic3r::GUI::Rect Class Reference
Slic3r::GUI::Rect Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosManager.hpp>
Public Member Functions
Rect ()=default
Rect (float left, float top, float right, float bottom)
bool operator== (const Rect &other) const
bool operator!= (const Rect &other) const
float get_left () const
void set_left (float left)
float get_top () const
void set_top (float top)
float get_right () const
void set_right (float right)
float get_bottom () const
void set_bottom (float bottom)
float get_width () const
float get_height () const
Private Attributes
float m_left { 0.0f }
float m_top { 0.0f }
float m_right { 0.0f }
float m_bottom { 0.0f }
Detailed Description
Constructor & Destructor Documentation
Rect() [1/2]
Slic3r::GUI::Rect::Rect () default
Rect() [2/2]
Slic3r::GUI::Rect::Rect (float left, float top, float right, float bottom) inline
: m_left(left) , m_top(top) , m_right(right) , m_bottom(bottom) {}
Member Function Documentation
get_bottom()
float Slic3r::GUI::Rect::get_bottom () const inline
{ return m_bottom; }
References m_bottom.
Referenced by Slic3r::GUI::GLCanvas3D::_perform_layer_editing_action(), Slic3r::GUI::GLCanvas3D::LayersEditing::bar_rect_contains(), and Slic3r::GUI::GLCanvas3D::LayersEditing::get_cursor_z_relative().
get_height()
float Slic3r::GUI::Rect::get_height () const inline
{ return m_top - m_bottom; }
References m_bottom, and m_top.
get_left()
float Slic3r::GUI::Rect::get_left () const inline
{ return m_left; }
References m_left.
Referenced by Slic3r::GUI::GLCanvas3D::LayersEditing::bar_rect_contains(), and Slic3r::GUI::GLCanvas3D::LayersEditing::get_cursor_z_relative().
get_right()
float Slic3r::GUI::Rect::get_right () const inline
{ return m_right; }
References m_right.
Referenced by Slic3r::GUI::GLCanvas3D::LayersEditing::bar_rect_contains(), and Slic3r::GUI::GLCanvas3D::LayersEditing::get_cursor_z_relative().
get_top()
float Slic3r::GUI::Rect::get_top () const inline
{ return m_top; }
References m_top.
Referenced by Slic3r::GUI::GLCanvas3D::_perform_layer_editing_action(), Slic3r::GUI::GLCanvas3D::LayersEditing::bar_rect_contains(), and Slic3r::GUI::GLCanvas3D::LayersEditing::get_cursor_z_relative().
get_width()
float Slic3r::GUI::Rect::get_width () const inline
{ return m_right - m_left; }
References m_left, and m_right.
operator!=()
bool Slic3r::GUI::Rect::operator!= (const Rect & other) const inline
{ return !operator==(other); }
References operator==().
operator==()
bool Slic3r::GUI::Rect::operator== (const Rect & other) const inline
{
        if (std::abs(m_left - other.m_left) > EPSILON) return false;
        if (std::abs(m_top - other.m_top) > EPSILON) return false;
        if (std::abs(m_right - other.m_right) > EPSILON) return false;
        if (std::abs(m_bottom - other.m_bottom) > EPSILON) return false;
        return true;
    }
References EPSILON, m_bottom, m_left, m_right, and m_top.
Referenced by operator!=().
set_bottom()
void Slic3r::GUI::Rect::set_bottom (float bottom) inline
{ m_bottom = bottom; }
References m_bottom.
set_left()
void Slic3r::GUI::Rect::set_left (float left) inline
{ m_left = left; }
References m_left.
set_right()
void Slic3r::GUI::Rect::set_right (float right) inline
{ m_right = right; }
References m_right.
set_top()
void Slic3r::GUI::Rect::set_top (float top) inline
{ m_top = top; }
References m_top.
Member Data Documentation
m_bottom
float Slic3r::GUI::Rect::m_bottom { 0.0f } private
Referenced by get_bottom(), get_height(), operator==(), and set_bottom().
m_left
float Slic3r::GUI::Rect::m_left { 0.0f } private
Referenced by get_left(), get_width(), operator==(), and set_left().
m_right
float Slic3r::GUI::Rect::m_right { 0.0f } private
Referenced by get_right(), get_width(), operator==(), and set_right().
m_top
float Slic3r::GUI::Rect::m_top { 0.0f } private
Referenced by get_height(), get_top(), operator==(), and set_top().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Gizmos/GLGizmosManager.hpp