Prusa Slicer: src/avrdude/flip1.h File Reference
flip1.h File Reference
Functions
void flip1_initpgm (PROGRAMMER *pgm)
Variables
const char flip1_desc []
Function Documentation
flip1_initpgm()
void flip1_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "flip1");
  /* Mandatory Functions */
  pgm->initialize       = flip1_initialize;
  pgm->enable           = flip1_enable;
  pgm->disable          = flip1_disable;
  pgm->display          = flip1_display;
  pgm->program_enable   = flip1_program_enable;
  pgm->chip_erase       = flip1_chip_erase;
  pgm->open             = flip1_open;
  pgm->close            = flip1_close;
  pgm->paged_load       = flip1_paged_load;
  pgm->paged_write      = flip1_paged_write;
  pgm->read_byte        = flip1_read_byte;
  pgm->write_byte       = flip1_write_byte;
  pgm->read_sig_bytes   = flip1_read_sig_bytes;
  pgm->setup            = flip1_setup;
  pgm->teardown         = flip1_teardown;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, flip1_chip_erase(), flip1_close(), flip1_disable(), flip1_display(), flip1_enable(), flip1_initialize(), flip1_open(), flip1_paged_load(), flip1_paged_write(), flip1_program_enable(), flip1_read_byte(), flip1_read_sig_bytes(), flip1_setup(), flip1_teardown(), flip1_write_byte(), programmer_t::initialize, programmer_t::open, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::program_enable, programmer_t::read_byte, programmer_t::read_sig_bytes, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
Variable Documentation
flip1_desc
const char flip1_desc[] extern