Prusa Slicer: Slic3r::Geometry::VoronoiUtilsCgal Class Reference
Slic3r::Geometry::VoronoiUtilsCgal Class Reference
#include <src/libslic3r/Geometry/VoronoiUtilsCgal.hpp>
Static Public Member Functions
static bool is_voronoi_diagram_planar_intersection (const VoronoiDiagram &voronoi_diagram)
static bool is_voronoi_diagram_planar_angle (const VoronoiDiagram &voronoi_diagram, const std::vector< Arachne::VoronoiUtils::Segment > &segments)
Detailed Description
Member Function Documentation
is_voronoi_diagram_planar_angle()
bool Slic3r::Geometry::VoronoiUtilsCgal::is_voronoi_diagram_planar_angle (const VoronoiDiagram & voronoi_diagram, const std::vector< Arachne::VoronoiUtils::Segment > & segments) static
{
    for (const VD::vertex_type &vertex : voronoi_diagram.vertices()) {
        std::vector<const VD::edge_type *> edges;
        const VD::edge_type               *edge = vertex.incident_edge();
        do {
            if (edge->is_finite() && edge->vertex0() != nullptr && edge->vertex1() != nullptr &&
                VoronoiUtils::is_finite(*edge->vertex0()) && VoronoiUtils::is_finite(*edge->vertex1()))
                edges.emplace_back(edge);
            edge = edge->rot_next();
        } while (edge != vertex.incident_edge());
        // Checking for CCW make sense for three and more edges.
        if (edges.size() > 2) {
            for (auto edge_it = edges.begin() ; edge_it != edges.end(); ++edge_it) {
                const Geometry::VoronoiDiagram::edge_type *prev_edge = edge_it == edges.begin() ? edges.back() : *std::prev(edge_it);
                const Geometry::VoronoiDiagram::edge_type *curr_edge = *edge_it;
                const Geometry::VoronoiDiagram::edge_type *next_edge = std::next(edge_it) == edges.end() ? edges.front() : *std::next(edge_it);
                if (!check_if_three_edges_are_ccw(*prev_edge, *curr_edge, *next_edge, segments))
                    return false;
            }
        }
    }
    return true;
}
References Slic3r::Geometry::check_if_three_edges_are_ccw(), and Slic3r::Arachne::VoronoiUtils::is_finite().
Referenced by Slic3r::Arachne::detect_voronoi_diagram_known_issues().
is_voronoi_diagram_planar_intersection()
bool Slic3r::Geometry::VoronoiUtilsCgal::is_voronoi_diagram_planar_intersection (const VoronoiDiagram & voronoi_diagram) static
{
    using CGAL_Point  = CGAL::Exact_predicates_exact_constructions_kernel::Point_2;
    using CGAL_Segment = CGAL::Arr_segment_traits_2<CGAL::Exact_predicates_exact_constructions_kernel>::Curve_2;
    auto to_cgal_point = [](const VD::vertex_type &pt) -> CGAL_Point { return {pt.x(), pt.y()}; };
    assert(std::all_of(voronoi_diagram.edges().cbegin(), voronoi_diagram.edges().cend(),
                       [](const VD::edge_type &edge) { return edge.color() == 0; }));
    std::vector<CGAL_Segment> segments;
    segments.reserve(voronoi_diagram.num_edges());
    for (const VD::edge_type &edge : voronoi_diagram.edges()) {
        if (edge.color() != 0)
            continue;
        if (edge.is_finite() && edge.is_linear() && edge.vertex0() != nullptr && edge.vertex1() != nullptr &&
            VoronoiUtils::is_finite(*edge.vertex0()) && VoronoiUtils::is_finite(*edge.vertex1())) {
            segments.emplace_back(to_cgal_point(*edge.vertex0()), to_cgal_point(*edge.vertex1()));
            edge.color(1);
            assert(edge.twin() != nullptr);
            edge.twin()->color(1);
        }
    }
    for (const VD::edge_type &edge : voronoi_diagram.edges())
        edge.color(0);
    std::vector<CGAL_Point> intersections_pt;
    CGAL::compute_intersection_points(segments.begin(), segments.end(), std::back_inserter(intersections_pt));
    return intersections_pt.empty();
}
References Slic3r::Arachne::VoronoiUtils::is_finite(), and Slic3r::Geometry::to_cgal_point().
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::constructFromPolygons(), and Slic3r::Arachne::try_to_fix_degenerated_voronoi_diagram_by_rotation().
The documentation for this class was generated from the following files:
src/libslic3r/Geometry/VoronoiUtilsCgal.hpp
src/libslic3r/Geometry/VoronoiUtilsCgal.cpp