Prusa Slicer: src/avrdude/serbb_posix.c File Reference
serbb_posix.c File Reference
#include "ac_cfg.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <sys/ioctl.h>
#include <termios.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "bitbang.h"
#include "serbb.h"
Macros
#define DB9PINS 9
Functions
static int serbb_setpin (PROGRAMMER *pgm, int pinfunc, int value)
static int serbb_getpin (PROGRAMMER *pgm, int pinfunc)
static int serbb_highpulsepin (PROGRAMMER *pgm, int pinfunc)
static void serbb_display (PROGRAMMER *pgm, const char *p)
static void serbb_enable (PROGRAMMER *pgm)
static void serbb_disable (PROGRAMMER *pgm)
static void serbb_powerup (PROGRAMMER *pgm)
static void serbb_powerdown (PROGRAMMER *pgm)
static int serbb_open (PROGRAMMER *pgm, char *port)
static void serbb_close (PROGRAMMER *pgm)
void serbb_initpgm (PROGRAMMER *pgm)
Variables
static struct termios oldmode
static int serregbits [DB9PINS+1]
const char serbb_desc [] = "Serial port bitbanging"
Macro Definition Documentation
DB9PINS
#define DB9PINS 9
Function Documentation
serbb_close()
static void serbb_close (PROGRAMMER * pgm) static
{
  if (pgm->fd.ifd != -1)
  {
    (void)tcsetattr(pgm->fd.ifd, TCSANOW, &oldmode);
    pgm->setpin(pgm, PIN_AVR_RESET, 1);
    close(pgm->fd.ifd);
  }
  return;
}
References programmer_t::fd, filedescriptor::ifd, oldmode, pgm, PIN_AVR_RESET, programmer_t::setpin, and void().
Referenced by serbb_initpgm().
serbb_disable()
static void serbb_disable (PROGRAMMER * pgm) static
{
  /* nothing */
}
Referenced by serbb_initpgm().
serbb_display()
static void serbb_display (PROGRAMMER * pgm, const char * p) static
{
  /* MAYBE */
}
Referenced by serbb_initpgm().
serbb_enable()
static void serbb_enable (PROGRAMMER * pgm) static
{
  /* nothing */
}
Referenced by serbb_initpgm().
serbb_getpin()
static int serbb_getpin (PROGRAMMER * pgm, int pinfunc) static
{
  unsigned int  ctl;
  unsigned char invert;
  int           r;
  int pin = pgm->pinno[pinfunc]; // get its value
  if (pin & PIN_INVERSE)
  {
    invert = 1;
    pin   &= PIN_MASK;
  } else
    invert = 0;
  if ( pin < 1 || pin > DB9PINS )
    return(-1);
  switch ( pin )
  {
    case 2:  /* rxd, currently not implemented, FIXME */
             return(-1);
    case 1:  /* cd  */
    case 6:  /* dsr */
    case 8:  /* cts */
    case 9:  /* ri  */
             r = ioctl(pgm->fd.ifd, TIOCMGET, &ctl);
       if (r < 0) {
         perror("ioctl(\"TIOCMGET\")");
         return -1;
       }
             if ( !invert )
             {
#ifdef DEBUG
               printf("%s is %d\n",serpins[pin],(ctl & serregbits[pin]) ? 1 : 0 );
#endif
               return ( (ctl & serregbits[pin]) ? 1 : 0 );
             }
             else
             {
#ifdef DEBUG
               printf("%s is %d (~)\n",serpins[pin],(ctl & serregbits[pin]) ? 0 : 1 );
#endif
               return (( ctl & serregbits[pin]) ? 0 : 1 );
             }
    default: /* impossible */
             return(-1);
  }
}
References DB9PINS, programmer_t::fd, filedescriptor::ifd, pgm, PIN_INVERSE, PIN_MASK, programmer_t::pinno, and serregbits.
Referenced by serbb_initpgm().
serbb_highpulsepin()
static int serbb_highpulsepin (PROGRAMMER * pgm, int pinfunc) static
{
  int pin = pgm->pinno[pinfunc]; // replace pin name by its value
  if ( (pin & PIN_MASK) < 1 || (pin & PIN_MASK) > DB9PINS )
    return -1;
  serbb_setpin(pgm, pinfunc, 1);
  serbb_setpin(pgm, pinfunc, 0);
  return 0;
}
References DB9PINS, pgm, PIN_MASK, programmer_t::pinno, and serbb_setpin().
Referenced by serbb_initpgm().
serbb_initpgm()
void serbb_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "SERBB");
  pgm_fill_old_pins(pgm); // TODO to be removed if old pin data no longer needed
  pgm->rdy_led        = bitbang_rdy_led;
  pgm->err_led        = bitbang_err_led;
  pgm->pgm_led        = bitbang_pgm_led;
  pgm->vfy_led        = bitbang_vfy_led;
  pgm->initialize     = bitbang_initialize;
  pgm->display        = serbb_display;
  pgm->enable         = serbb_enable;
  pgm->disable        = serbb_disable;
  pgm->powerup        = serbb_powerup;
  pgm->powerdown      = serbb_powerdown;
  pgm->program_enable = bitbang_program_enable;
  pgm->chip_erase     = bitbang_chip_erase;
  pgm->cmd            = bitbang_cmd;
  pgm->cmd_tpi        = bitbang_cmd_tpi;
  pgm->open           = serbb_open;
  pgm->close          = serbb_close;
  pgm->setpin         = serbb_setpin;
  pgm->getpin         = serbb_getpin;
  pgm->highpulsepin   = serbb_highpulsepin;
  pgm->read_byte      = avr_read_byte_default;
  pgm->write_byte     = avr_write_byte_default;
}
References avr_read_byte_default(), avr_write_byte_default(), bitbang_chip_erase(), bitbang_cmd(), bitbang_cmd_tpi(), bitbang_err_led(), bitbang_initialize(), bitbang_pgm_led(), bitbang_program_enable(), bitbang_rdy_led(), bitbang_vfy_led(), programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::cmd_tpi, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::err_led, programmer_t::getpin, programmer_t::highpulsepin, programmer_t::initialize, programmer_t::open, pgm, pgm_fill_old_pins(), programmer_t::pgm_led, programmer_t::powerdown, programmer_t::powerup, programmer_t::program_enable, programmer_t::rdy_led, programmer_t::read_byte, serbb_close(), serbb_disable(), serbb_display(), serbb_enable(), serbb_getpin(), serbb_highpulsepin(), serbb_open(), serbb_powerdown(), serbb_powerup(), serbb_setpin(), programmer_t::setpin, programmer_t::type, programmer_t::vfy_led, and programmer_t::write_byte.
serbb_open()
static int serbb_open (PROGRAMMER * pgm, char * port) static
{
  struct termios mode;
  int flags;
  int r;
  if (bitbang_check_prerequisites(pgm) < 0)
    return -1;
  /* adapted from uisp code */
  pgm->fd.ifd = open(port, O_RDWR | O_NOCTTY | O_NONBLOCK);
  if (pgm->fd.ifd < 0) {
    perror(port);
    return(-1);
  }
  r = tcgetattr(pgm->fd.ifd, &mode);
  if (r < 0) {
    avrdude_message(MSG_INFO, "%s: ", port);
    perror("tcgetattr");
    return(-1);
  }
  oldmode = mode;
  mode.c_iflag = IGNBRK | IGNPAR;
  mode.c_oflag = 0;
  mode.c_cflag = CLOCAL | CREAD | CS8 | B9600;
  mode.c_cc [VMIN] = 1;
  mode.c_cc [VTIME] = 0;
  r = tcsetattr(pgm->fd.ifd, TCSANOW, &mode);
  if (r < 0) {
      avrdude_message(MSG_INFO, "%s: ", port);
      perror("tcsetattr");
      return(-1);
  }
  /* Clear O_NONBLOCK flag.  */
  flags = fcntl(pgm->fd.ifd, F_GETFL, 0);
  if (flags == -1)
    {
      avrdude_message(MSG_INFO, "%s: Can not get flags: %s\n",
        progname, strerror(errno));
      return(-1);
    }
  flags &= ~O_NONBLOCK;
  if (fcntl(pgm->fd.ifd, F_SETFL, flags) == -1)
    {
      avrdude_message(MSG_INFO, "%s: Can not clear nonblock flag: %s\n",
        progname, strerror(errno));
      return(-1);
    }
  return(0);
}
References avrdude_message(), bitbang_check_prerequisites(), programmer_t::fd, filedescriptor::ifd, MSG_INFO, oldmode, pgm, and progname.
Referenced by serbb_initpgm().
serbb_powerdown()
static void serbb_powerdown (PROGRAMMER * pgm) static
{
  /* nothing */
}
Referenced by serbb_initpgm().
serbb_powerup()
static void serbb_powerup (PROGRAMMER * pgm) static
{
  /* nothing */
}
Referenced by serbb_initpgm().
serbb_setpin()
static int serbb_setpin (PROGRAMMER * pgm, int pinfunc, int value) static
{
  unsigned int  ctl;
  int           r;
  int pin = pgm->pinno[pinfunc]; // get its value
  if (pin & PIN_INVERSE)
  {
    value  = !value;
    pin   &= PIN_MASK;
  }
  if ( pin < 1 || pin > DB9PINS )
    return -1;
#ifdef DEBUG
  printf("%s to %d\n",serpins[pin],value);
#endif
  switch ( pin )
  {
    case 3:  /* txd */
       r = ioctl(pgm->fd.ifd, value ? TIOCSBRK : TIOCCBRK, 0);
       if (r < 0) {
         perror("ioctl(\"TIOCxBRK\")");
         return -1;
       }
             break;
    case 4:  /* dtr */
    case 7:  /* rts */
             r = ioctl(pgm->fd.ifd, TIOCMGET, &ctl);
       if (r < 0) {
         perror("ioctl(\"TIOCMGET\")");
         return -1;
       }
             if ( value )
               ctl |= serregbits[pin];
             else
               ctl &= ~(serregbits[pin]);
       r = ioctl(pgm->fd.ifd, TIOCMSET, &ctl);
       if (r < 0) {
         perror("ioctl(\"TIOCMSET\")");
         return -1;
       }
             break;
    default: /* impossible */
             return -1;
  }
  if (pgm->ispdelay > 1)
    bitbang_delay(pgm->ispdelay);
  return 0;
}
References bitbang_delay(), DB9PINS, programmer_t::fd, filedescriptor::ifd, programmer_t::ispdelay, pgm, PIN_INVERSE, PIN_MASK, programmer_t::pinno, and serregbits.
Referenced by serbb_highpulsepin(), and serbb_initpgm().
Variable Documentation
oldmode
struct termios oldmode static
Referenced by serbb_close(), and serbb_open().
serbb_desc
const char serbb_desc[] = "Serial port bitbanging"
serregbits
int serregbits[DB9PINS+1] static
Initial value:
=
{ 0, TIOCM_CD, 0, 0, TIOCM_DTR, 0, TIOCM_DSR, TIOCM_RTS, TIOCM_CTS, TIOCM_RI }
Referenced by serbb_getpin(), and serbb_setpin().