Prusa Slicer: Slic3r::NSVGUtils Class Reference
Slic3r::NSVGUtils Class Reference
#include <src/libslic3r/NSVGUtils.hpp>
Public Member Functions
NSVGUtils ()=delete
Static Public Member Functions
static void flatten_cubic_bez (Polygon &polygon, float tessTol, Vec2f p1, Vec2f p2, Vec2f p3, Vec2f p4, int level)
static ExPolygons to_ExPolygons (NSVGimage *image, float tessTol=10., int max_level=10)
static Polygons to_polygons (NSVGimage *image, float tessTol=10., int max_level=10)
Detailed Description
Constructor & Destructor Documentation
NSVGUtils()
Slic3r::NSVGUtils::NSVGUtils () delete
Member Function Documentation
flatten_cubic_bez()
void NSVGUtils::flatten_cubic_bez (Polygon & polygon, float tessTol, Vec2f p1, Vec2f p2, Vec2f p3, Vec2f p4, int level) static
{
    Vec2f p12  = (p1 + p2) * 0.5f;
    Vec2f p23  = (p2 + p3) * 0.5f;
    Vec2f p34  = (p3 + p4) * 0.5f;
    Vec2f p123 = (p12 + p23) * 0.5f;
    Vec2f pd  = p4 - p1;
    Vec2f pd2 = p2 - p4;
    float d2  = std::abs(pd2.x() * pd.y() - pd2.y() * pd.x());
    Vec2f pd3 = p3 - p4;
    float d3  = std::abs(pd3.x() * pd.y() - pd3.y() * pd.x());
    float d23 = d2 + d3;
    if ((d23 * d23) < tessTol * (pd.x() * pd.x() + pd.y() * pd.y())) {
        polygon.points.emplace_back(p4.x(), p4.y());
        return;
    }
    --level;
    if (level == 0) return;
    Vec2f p234  = (p23 + p34) * 0.5f;
    Vec2f p1234 = (p123 + p234) * 0.5f;
    flatten_cubic_bez(polygon, tessTol, p1, p12, p123, p1234, level);
    flatten_cubic_bez(polygon, tessTol, p1234, p234, p34, p4, level);
}
References flatten_cubic_bez(), and Slic3r::MultiPoint::points.
Referenced by flatten_cubic_bez(), and to_polygons().
to_ExPolygons()
ExPolygons NSVGUtils::to_ExPolygons (NSVGimage * image, float tessTol = 10., int max_level = 10) static
{
    Polygons polygons = to_polygons(image, tessTol, max_level);
    // Fix Y axis
    for (Polygon &polygon : polygons)
        for (Point &p : polygon.points) p.y() *= -1;
    return Slic3r::union_ex(polygons);
}
References to_polygons(), and Slic3r::union_ex().
to_polygons()
Polygons NSVGUtils::to_polygons (NSVGimage * image, float tessTol = 10., int max_level = 10) static
{
    Polygons polygons;
    for (NSVGshape *shape = image->shapes; shape != NULL;
         shape            = shape->next) {
        if (!(shape->flags & NSVG_FLAGS_VISIBLE)) continue;
        Slic3r::Polygon polygon;
        if (shape->fill.type != NSVG_PAINT_NONE) {
            for (NSVGpath *path = shape->paths; path != NULL;
                 path           = path->next) {
                // Flatten path
                polygon.points.emplace_back(path->pts[0], path->pts[1]);
                size_t path_size = (path->npts > 1) ?
                    static_cast<size_t>(path->npts - 1) : 0;
                for (size_t i = 0; i < path_size; i += 3) {
                    float *p = &path->pts[i * 2];
                    Vec2f  p1(p[0], p[1]), p2(p[2], p[3]), p3(p[4], p[5]),
                        p4(p[6], p[7]);
                    flatten_cubic_bez(polygon, tessTol, p1, p2, p3, p4,
                                      max_level);
                }
                if (path->closed && !polygon.empty()) {
                    polygons.push_back(polygon);
                    polygon = Slic3r::Polygon();
                }
            }
        }
        if (!polygon.empty())
            polygons.push_back(polygon);
    }
    return polygons;
}
References Slic3r::MultiPoint::empty(), flatten_cubic_bez(), and Slic3r::MultiPoint::points.
Referenced by to_ExPolygons().
The documentation for this class was generated from the following files:
src/libslic3r/NSVGUtils.hpp
src/libslic3r/NSVGUtils.cpp