Prusa Slicer: wxCheckListBoxComboPopup Class Reference
wxCheckListBoxComboPopup Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
virtual bool Create (wxWindow *parent)
virtual wxWindow * GetControl ()
virtual void SetStringValue (const wxString &value)
virtual wxString GetStringValue () const
virtual wxSize GetAdjustedSize (int minWidth, int prefHeight, int maxHeight)
virtual void OnKeyEvent (wxKeyEvent &evt)
void OnCheckListBox (wxCommandEvent &evt)
void OnListBoxSelection (wxCommandEvent &evt)
Private Types
enum class OnCheckListBoxFunction { FreeToProceed , RefuseToProceed , WasRefusedLastTime }
Private Attributes
wxString m_text
enum wxCheckListBoxComboPopup::OnCheckListBoxFunction m_check_box_events_status = OnCheckListBoxFunction::FreeToProceed
Static Private Attributes
static const unsigned int DefaultWidth = 200
static const unsigned int DefaultHeight = 200
Detailed Description
Member Enumeration Documentation
OnCheckListBoxFunction
enum class wxCheckListBoxComboPopup::OnCheckListBoxFunction strong private
Enumerator
FreeToProceed
RefuseToProceed
WasRefusedLastTime
{
        FreeToProceed,
        RefuseToProceed,
        WasRefusedLastTime
    } m_check_box_events_status = OnCheckListBoxFunction::FreeToProceed;
Member Function Documentation
Create()
bool wxCheckListBoxComboPopup::Create (wxWindow * parent) virtual
{
    return wxCheckListBox::Create(parent, wxID_HIGHEST + 1, wxPoint(0, 0));
}
GetAdjustedSize()
wxSize wxCheckListBoxComboPopup::GetAdjustedSize (int minWidth, int prefHeight, int maxHeight) virtual
{
    // set width dinamically in dependence of items text
    // and set height dinamically in dependence of items count
    wxComboCtrl* cmb = GetComboCtrl();
    if (cmb != nullptr) {
        wxSize size = GetComboCtrl()->GetSize();
        unsigned int count = GetCount();
        if (count > 0) {
            int max_width = size.x;
            for (unsigned int i = 0; i < count; ++i) {
                max_width = std::max(max_width, 60 + GetTextExtent(GetString(i)).x);
            }
            size.SetWidth(max_width);
            size.SetHeight(count * cmb->GetCharHeight());
        }
        else
            size.SetHeight(DefaultHeight);
        return size;
    }
    else
        return wxSize(DefaultWidth, DefaultHeight);
}
References DefaultHeight, and DefaultWidth.
GetControl()
wxWindow * wxCheckListBoxComboPopup::GetControl () virtual
{
    return this;
}
GetStringValue()
wxString wxCheckListBoxComboPopup::GetStringValue () const virtual
{
    return m_text;
}
References m_text.
OnCheckListBox()
void wxCheckListBoxComboPopup::OnCheckListBox (wxCommandEvent & evt)
{
    // forwards the checklistbox event to the owner wxComboCtrl
    if (m_check_box_events_status == OnCheckListBoxFunction::FreeToProceed )
    {
        wxComboCtrl* cmb = GetComboCtrl();
        if (cmb != nullptr) {
            wxCommandEvent event(wxEVT_CHECKLISTBOX, cmb->GetId());
            event.SetEventObject(cmb);
            cmb->ProcessWindowEvent(event);
        }
    }
    evt.Skip();
    #ifndef _WIN32  // events are sent differently on OSX+Linux vs Win (more description in header file)
        if ( m_check_box_events_status == OnCheckListBoxFunction::RefuseToProceed )
            // this happens if the event was resent by OnListBoxSelection - next call to OnListBoxSelection is due to user clicking the text, so the function should
            // explicitly change the state on the checkbox
            m_check_box_events_status = OnCheckListBoxFunction::WasRefusedLastTime;
        else
            // if the user clicked the checkbox square, this event was sent before OnListBoxSelection was called, so we don't want it to resend it
            m_check_box_events_status = OnCheckListBoxFunction::RefuseToProceed;
    #endif
}
References FreeToProceed, m_check_box_events_status, RefuseToProceed, and WasRefusedLastTime.
Referenced by Slic3r::GUI::create_combochecklist().
OnKeyEvent()
void wxCheckListBoxComboPopup::OnKeyEvent (wxKeyEvent & evt) virtual
{
    // filters out all the keys which are not working properly
    switch (evt.GetKeyCode())
    {
    case WXK_LEFT:
    case WXK_UP:
    case WXK_RIGHT:
    case WXK_DOWN:
    case WXK_PAGEUP:
    case WXK_PAGEDOWN:
    case WXK_END:
    case WXK_HOME:
    case WXK_NUMPAD_LEFT:
    case WXK_NUMPAD_UP:
    case WXK_NUMPAD_RIGHT:
    case WXK_NUMPAD_DOWN:
    case WXK_NUMPAD_PAGEUP:
    case WXK_NUMPAD_PAGEDOWN:
    case WXK_NUMPAD_END:
    case WXK_NUMPAD_HOME:
    {
        break;
    }
    default:
    {
        evt.Skip();
        break;
    }
    }
}
Referenced by Slic3r::GUI::create_combochecklist().
OnListBoxSelection()
void wxCheckListBoxComboPopup::OnListBoxSelection (wxCommandEvent & evt)
{
    // transforms list box item selection event into checklistbox item toggle event
    int selId = GetSelection();
    if (selId != wxNOT_FOUND)
    {
        #ifndef _WIN32
            if (m_check_box_events_status == OnCheckListBoxFunction::RefuseToProceed)
        #endif
                Check((unsigned int)selId, !IsChecked((unsigned int)selId));
        m_check_box_events_status = OnCheckListBoxFunction::FreeToProceed; // so the checkbox reacts to square-click the next time
        SetSelection(wxNOT_FOUND);
        wxCommandEvent event(wxEVT_CHECKLISTBOX, GetId());
        event.SetInt(selId);
        event.SetEventObject(this);
        ProcessEvent(event);
    }
}
References FreeToProceed, m_check_box_events_status, and RefuseToProceed.
Referenced by Slic3r::GUI::create_combochecklist().
SetStringValue()
void wxCheckListBoxComboPopup::SetStringValue (const wxString & value) virtual
{
    m_text = value;
}
References m_text.
Referenced by Slic3r::GUI::create_combochecklist().
Member Data Documentation
DefaultHeight
const unsigned int wxCheckListBoxComboPopup::DefaultHeight = 200 static private
Referenced by GetAdjustedSize().
DefaultWidth
const unsigned int wxCheckListBoxComboPopup::DefaultWidth = 200 static private
Referenced by GetAdjustedSize().
m_check_box_events_status
enum wxCheckListBoxComboPopup::OnCheckListBoxFunction wxCheckListBoxComboPopup::m_check_box_events_status = OnCheckListBoxFunction::FreeToProceed private
Referenced by OnCheckListBox(), and OnListBoxSelection().
m_text
wxString wxCheckListBoxComboPopup::m_text private
Referenced by GetStringValue(), and SetStringValue().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp