Prusa Slicer: Slic3r::sla::anonymous_namespace{Pad.cpp} Namespace Reference
Slic3r::sla::anonymous_namespace{Pad.cpp} Namespace Reference
Classes
class _AroundPadSkeleton
class BelowPadSkeleton
struct DummyIntersector
class Intersector
struct PadConfig3D
struct PadSkeleton
Typedefs
using AroundPadSkeleton = _AroundPadSkeleton< Intersector >
using BrimPadSkeleton = _AroundPadSkeleton< DummyIntersector >
Functions
indexed_triangle_set walls (const Polygon &lower, const Polygon &upper, double lower_z_mm, double upper_z_mm)
indexed_triangle_set straight_walls (const Polygon &plate, double lo_z, double hi_z)
void breakstick_holes (Points &pts, double padding, double stride, double stick_width, double penetration)
template<class... Args>
ExPolygons breakstick_holes (const ExPolygons &input, Args...args)
static coord_t get_waffle_offset (const PadConfig &c)
static double get_merge_distance (const PadConfig &c)
PadSkeleton divide_blueprint (const ExPolygons &bp)
template<class... Args>
ExPolygon offset_contour_only (const ExPolygon &poly, coord_t delta, Args...args)
bool add_cavity (indexed_triangle_set &pad, ExPolygon &top_poly, const PadConfig3D &cfg, ThrowOnCancel thr)
indexed_triangle_set create_outer_pad_geometry (const ExPolygons &skeleton, const PadConfig3D &cfg, ThrowOnCancel thr)
indexed_triangle_set create_inner_pad_geometry (const ExPolygons &skeleton, const PadConfig3D &cfg, ThrowOnCancel thr)
indexed_triangle_set create_pad_geometry (const PadSkeleton &skelet, const PadConfig &cfg, ThrowOnCancel thr)
indexed_triangle_set create_pad_geometry (const ExPolygons &supp_bp, const ExPolygons &model_bp, const PadConfig &cfg, ThrowOnCancel thr)
Typedef Documentation
AroundPadSkeleton
using Slic3r::sla::anonymous_namespace{Pad.cpp}::AroundPadSkeleton = typedef _AroundPadSkeleton<Intersector>
BrimPadSkeleton
using Slic3r::sla::anonymous_namespace{Pad.cpp}::BrimPadSkeleton = typedef _AroundPadSkeleton<DummyIntersector>
Function Documentation
add_cavity()
bool Slic3r::sla::anonymous_namespace{Pad.cpp}::add_cavity (indexed_triangle_set & pad, ExPolygon & top_poly, const PadConfig3D & cfg, ThrowOnCancel thr)
{
    auto logerr = []{BOOST_LOG_TRIVIAL(error)<<"Could not create pad cavity";};
    double    wing_distance = cfg.wing_height / std::tan(cfg.slope);
    coord_t   delta_inner   = -scaled(cfg.thickness + wing_distance);
    coord_t   delta_middle  = -scaled(cfg.thickness);
    ExPolygon inner_base    = offset_contour_only(top_poly, delta_inner);
    ExPolygon middle_base   = offset_contour_only(top_poly, delta_middle);
    if (inner_base.empty() || middle_base.empty()) { logerr(); return false; }
    ExPolygons pdiff = diff_ex(top_poly, middle_base.contour);
    if (pdiff.size() != 1) { logerr(); return false; }
    top_poly = pdiff.front();
    double z_min = -cfg.wing_height, z_max = 0;
    its_merge(pad, walls(inner_base.contour, middle_base.contour, z_min, z_max));
    thr();
    its_merge(pad, triangulate_expolygon_3d(inner_base, z_min, NORMALS_UP));
    return true;
}
References add_cavity(), Slic3r::ExPolygon::contour, Slic3r::diff_ex(), Slic3r::ExPolygon::empty(), error, Slic3r::its_merge(), Slic3r::NORMALS_UP, offset_contour_only(), Slic3r::scaled(), Slic3r::sla::anonymous_namespace{Pad.cpp}::PadConfig3D::slope, Slic3r::sla::anonymous_namespace{Pad.cpp}::PadConfig3D::thickness, Slic3r::triangulate_expolygon_3d(), walls(), and Slic3r::sla::anonymous_namespace{Pad.cpp}::PadConfig3D::wing_height.
Referenced by add_cavity(), and create_outer_pad_geometry().
breakstick_holes() [1/2]
template<class... Args> ExPolygons Slic3r::sla::anonymous_namespace{Pad.cpp}::breakstick_holes (const ExPolygons & input, Args... args)
{
    ExPolygons ret = input;
    for (ExPolygon &p : ret) {
        breakstick_holes(p.contour.points, args...);
        for (auto &h : p.holes) breakstick_holes(h.points, args...);
    }
    return ret;
}
References breakstick_holes(), and input().
breakstick_holes() [2/2]
void Slic3r::sla::anonymous_namespace{Pad.cpp}::breakstick_holes (Points & pts, double padding, double stride, double stick_width, double penetration)
{
    if(stride <= EPSILON || stick_width <= EPSILON || padding <= EPSILON)
        return;
    // SVG svg("bridgestick_plate.svg");
    // svg.draw(poly);
    // The connector stick will be a small rectangle with dimensions
    // stick_width x (penetration + padding) to have some penetration
    // into the input polygon.
    Points out;
    out.reserve(2 * pts.size()); // output polygon points
    // stick bottom and right edge dimensions
    double sbottom = scaled(stick_width);
    double sright  = scaled(penetration + padding);
    // scaled stride distance
    double sstride = scaled(stride);
    double t       = 0;
    // process pairs of vertices as an edge, start with the last and
    // first point
    for (size_t i = pts.size() - 1, j = 0; j < pts.size(); i = j, ++j) {
        // Get vertices and the direction vectors
        const Point &a = pts[i], &b = pts[j];
        Vec2d        dir = b.cast<double>() - a.cast<double>();
        double       nrm = dir.norm();
        dir /= nrm;
        Vec2d dirp(-dir(Y), dir(X));
        // Insert start point
        out.emplace_back(a);
        // dodge the start point, do not make sticks on the joins
        while (t < sbottom) t += sbottom;
        double tend = nrm - sbottom;
        while (t < tend) { // insert the stick on the polygon perimeter
            // calculate the stick rectangle vertices and insert them
            // into the output.
            Point p1 = a + (t * dir).cast<coord_t>();
            Point p2 = p1 + (sright * dirp).cast<coord_t>();
            Point p3 = p2 + (sbottom * dir).cast<coord_t>();
            Point p4 = p3 + (sright * -dirp).cast<coord_t>();
            out.insert(out.end(), {p1, p2, p3, p4});
            // continue along the perimeter
            t += sstride;
        }
        t = t - nrm;
        // Insert edge endpoint
        out.emplace_back(b);
    }
    // move the new points
    out.shrink_to_fit();
    pts.swap(out);
}
References breakstick_holes(), EPSILON, Slic3r::scaled(), Slic3r::X, and Slic3r::Y.
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::_AroundPadSkeleton(), breakstick_holes(), and breakstick_holes().
create_inner_pad_geometry()
indexed_triangle_set Slic3r::sla::anonymous_namespace{Pad.cpp}::create_inner_pad_geometry (const ExPolygons & skeleton, const PadConfig3D & cfg, ThrowOnCancel thr)
{
    indexed_triangle_set ret;
    double z_max = 0., z_min = -cfg.height;
    for (const ExPolygon &pad_part : skeleton) {
        thr();
        its_merge(ret, straight_walls(pad_part.contour, z_max, z_min));
        for (auto &h : pad_part.holes)
            its_merge(ret, straight_walls(h, z_max, z_min));
        its_merge(ret, triangulate_expolygon_3d(pad_part, z_min, NORMALS_DOWN));
        its_merge(ret, triangulate_expolygon_3d(pad_part, z_max, NORMALS_UP));
    }
    return ret;
}
References create_inner_pad_geometry(), Slic3r::sla::anonymous_namespace{Pad.cpp}::PadConfig3D::height, Slic3r::its_merge(), Slic3r::NORMALS_DOWN, Slic3r::NORMALS_UP, Slic3r::straight_walls(), and Slic3r::triangulate_expolygon_3d().
Referenced by create_inner_pad_geometry(), and create_pad_geometry().
create_outer_pad_geometry()
indexed_triangle_set Slic3r::sla::anonymous_namespace{Pad.cpp}::create_outer_pad_geometry (const ExPolygons & skeleton, const PadConfig3D & cfg, ThrowOnCancel thr)
{
    indexed_triangle_set ret;
    for (const ExPolygon &pad_part : skeleton) {
        ExPolygon top_poly{pad_part};
        ExPolygon bottom_poly =
            offset_contour_only(pad_part, -scaled(cfg.bottom_offset()));
        if (bottom_poly.empty()) continue;
        thr();
        double z_min = -cfg.height, z_max = 0;
        its_merge(ret, walls(top_poly.contour, bottom_poly.contour, z_max, z_min));
        if (cfg.wing_height > 0. && add_cavity(ret, top_poly, cfg, thr))
            z_max = -cfg.wing_height;
        for (auto &h : bottom_poly.holes)
            its_merge(ret, straight_walls(h, z_max, z_min));
        its_merge(ret, triangulate_expolygon_3d(bottom_poly, z_min, NORMALS_DOWN));
        its_merge(ret, triangulate_expolygon_3d(top_poly, NORMALS_UP));
    }
    return ret;
}
References add_cavity(), Slic3r::sla::anonymous_namespace{Pad.cpp}::PadConfig3D::bottom_offset(), Slic3r::ExPolygon::contour, create_outer_pad_geometry(), Slic3r::ExPolygon::empty(), Slic3r::sla::anonymous_namespace{Pad.cpp}::PadConfig3D::height, Slic3r::ExPolygon::holes, Slic3r::its_merge(), Slic3r::NORMALS_DOWN, Slic3r::NORMALS_UP, offset_contour_only(), Slic3r::scaled(), Slic3r::straight_walls(), Slic3r::triangulate_expolygon_3d(), walls(), and Slic3r::sla::anonymous_namespace{Pad.cpp}::PadConfig3D::wing_height.
Referenced by create_outer_pad_geometry(), and create_pad_geometry().
create_pad_geometry() [1/2]
indexed_triangle_set Slic3r::sla::anonymous_namespace{Pad.cpp}::create_pad_geometry (const ExPolygons & supp_bp, const ExPolygons & model_bp, const PadConfig & cfg, ThrowOnCancel thr)
{
    PadSkeleton skelet;
    if (cfg.embed_object.enabled) {
        if (cfg.embed_object.everywhere)
            skelet = BrimPadSkeleton(supp_bp, model_bp, cfg, thr);
        else
            skelet = AroundPadSkeleton(supp_bp, model_bp, cfg, thr);
    } else
        skelet = BelowPadSkeleton(supp_bp, model_bp, cfg, thr);
    return create_pad_geometry(skelet, cfg, thr);
}
References create_pad_geometry(), Slic3r::sla::PadConfig::embed_object, Slic3r::sla::PadConfig::EmbedObject::enabled, and Slic3r::sla::PadConfig::EmbedObject::everywhere.
create_pad_geometry() [2/2]
indexed_triangle_set Slic3r::sla::anonymous_namespace{Pad.cpp}::create_pad_geometry (const PadSkeleton & skelet, const PadConfig & cfg, ThrowOnCancel thr)
{
#ifndef NDEBUG
    SVG svg("pad_skeleton.svg");
    svg.draw(skelet.outer, "green");
    svg.draw(skelet.inner, "blue");
    svg.Close();
#endif
    PadConfig3D cfg3d(cfg);
    auto pg = create_outer_pad_geometry(skelet.outer, cfg3d, thr);
    its_merge(pg, create_inner_pad_geometry(skelet.inner, cfg3d, thr));
    return pg;
}
References Slic3r::SVG::Close(), create_inner_pad_geometry(), create_outer_pad_geometry(), create_pad_geometry(), Slic3r::SVG::draw(), Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::inner, Slic3r::its_merge(), and Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::outer.
Referenced by create_pad_geometry(), and create_pad_geometry().
divide_blueprint()
PadSkeleton Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint (const ExPolygons & bp)
{
    ClipperLib::PolyTree ptree = union_pt(bp);
    PadSkeleton ret;
    ret.inner.reserve(size_t(ptree.Total()));
    ret.outer.reserve(size_t(ptree.Total()));
    for (ClipperLib::PolyTree::PolyNode *node : ptree.Childs) {
        ExPolygon poly;
        poly.contour.points = std::move(node->Contour);
        for (ClipperLib::PolyTree::PolyNode *child : node->Childs) {
            poly.holes.emplace_back(std::move(child->Contour));
            traverse_pt(child->Childs, &ret.inner);
        }
        ret.outer.emplace_back(poly);
    }
    return ret;
}
References ClipperLib::PolyNode::PolyNode(), ClipperLib::PolyNode::Childs, Slic3r::ExPolygon::contour, divide_blueprint(), Slic3r::ExPolygon::holes, Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::inner, Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::outer, Slic3r::MultiPoint::points, ClipperLib::PolyTree::Total(), Slic3r::traverse_pt(), and Slic3r::union_pt().
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::_AroundPadSkeleton(), and divide_blueprint().
get_merge_distance()
static double Slic3r::sla::anonymous_namespace{Pad.cpp}::get_merge_distance (const PadConfig & c) inline static
{
    return 2. * (1.8 * c.wall_thickness_mm) + c.max_merge_dist_mm;
}
References get_merge_distance().
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::BelowPadSkeleton::BelowPadSkeleton(), get_merge_distance(), and Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::wafflized_concave_hull().
get_waffle_offset()
static coord_t Slic3r::sla::anonymous_namespace{Pad.cpp}::get_waffle_offset (const PadConfig & c) inline static
{
    return scaled(c.brim_size_mm + c.wing_distance());
}
References get_waffle_offset(), and Slic3r::scaled().
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::BelowPadSkeleton::BelowPadSkeleton(), get_waffle_offset(), and Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::wafflized_concave_hull().
offset_contour_only()
template<class... Args> ExPolygon Slic3r::sla::anonymous_namespace{Pad.cpp}::offset_contour_only (const ExPolygon & poly, coord_t delta, Args... args)
{
    Polygons tmp = offset(poly.contour, float(delta), args...);
    if (tmp.empty()) return {};
    Polygons holes = poly.holes;
    for (auto &h : holes) h.reverse();
    ExPolygons tmp2 = diff_ex(tmp, holes);
    if (tmp2.empty()) return {};
    return std::move(tmp2.front());
}
References Slic3r::ExPolygon::contour, Slic3r::diff_ex(), Slic3r::ExPolygon::holes, Slic3r::holes(), Slic3r::offset(), and offset_contour_only().
Referenced by add_cavity(), create_outer_pad_geometry(), and offset_contour_only().
straight_walls()
indexed_triangle_set Slic3r::sla::anonymous_namespace{Pad.cpp}::straight_walls (const Polygon & plate, double lo_z, double hi_z) inline
{
    return wall_strip(plate, hi_z, lo_z); //walls(plate, plate, lo_z, hi_z);
}
References Slic3r::wall_strip().
walls()
indexed_triangle_set Slic3r::sla::anonymous_namespace{Pad.cpp}::walls (const Polygon & lower, const Polygon & upper, double lower_z_mm, double upper_z_mm)
{
    indexed_triangle_set w;
    triangulate_wall(w.vertices, w.indices, lower, upper, lower_z_mm,
                     upper_z_mm);
    return w;
}
References indexed_triangle_set::indices, Slic3r::triangulate_wall(), indexed_triangle_set::vertices, and walls().
Referenced by add_cavity(), create_outer_pad_geometry(), and walls().