Prusa Slicer: Slic3r::ClipperUtils::SurfacesPtrProvider Struct Reference
Slic3r::ClipperUtils::SurfacesPtrProvider Struct Reference
#include <src/libslic3r/ClipperUtils.hpp>
Classes
struct iterator
Public Member Functions
SurfacesPtrProvider (const SurfacesPtr &surfaces)
iterator cbegin () const
iterator begin () const
iterator cend () const
iterator end () const
size_t size () const
Private Attributes
const SurfacesPtr & m_surfaces
size_t m_size
Detailed Description
Constructor & Destructor Documentation
SurfacesPtrProvider()
Slic3r::ClipperUtils::SurfacesPtrProvider::SurfacesPtrProvider (const SurfacesPtr & surfaces) inline
                                                         : m_surfaces(surfaces) {
            m_size = 0;
            for (const Surface *surface : surfaces)
                m_size += surface->expolygon.holes.size() + 1;
        }
References m_size.
Member Function Documentation
begin()
iterator Slic3r::ClipperUtils::SurfacesPtrProvider::begin () const inline
{ return this->cbegin(); }
References cbegin().
cbegin()
iterator Slic3r::ClipperUtils::SurfacesPtrProvider::cbegin () const inline
{ return iterator(m_surfaces.cbegin()); }
References m_surfaces.
Referenced by begin().
cend()
iterator Slic3r::ClipperUtils::SurfacesPtrProvider::cend () const inline
{ return iterator(m_surfaces.cend()); }
References m_surfaces.
Referenced by end().
end()
iterator Slic3r::ClipperUtils::SurfacesPtrProvider::end () const inline
{ return this->cend(); }
References cend().
size()
size_t Slic3r::ClipperUtils::SurfacesPtrProvider::size () const inline
{ return m_size; }
References m_size.
Member Data Documentation
m_size
size_t Slic3r::ClipperUtils::SurfacesPtrProvider::m_size private
Referenced by SurfacesPtrProvider(), and size().
m_surfaces
const SurfacesPtr& Slic3r::ClipperUtils::SurfacesPtrProvider::m_surfaces private
Referenced by cbegin(), and cend().
The documentation for this struct was generated from the following file:
src/libslic3r/ClipperUtils.hpp