Prusa Slicer: Eigen::MatrixWrapper< ExpressionType > Class Template Reference
Eigen::MatrixWrapper< ExpressionType > Class Template Reference
Expression of an array as a mathematical vector or matrix.
#include <src/eigen/Eigen/src/Core/ArrayWrapper.h>
Public Types
typedef MatrixBase< MatrixWrapper< ExpressionType > > Base
typedef internal::remove_all< ExpressionType >::type NestedExpression
typedef internal::conditional< internal::is_lvalue< ExpressionType >::value, Scalar, constScalar >::type ScalarWithConstIfNotLvalue
typedef internal::ref_selector< ExpressionType >::non_const_type NestedExpressionType
enum
enum
typedef MatrixBase StorageBaseType
typedef internal::traits< MatrixWrapper< ExpressionType > >::StorageKind StorageKind
typedef internal::traits< MatrixWrapper< ExpressionType > >::StorageIndex StorageIndex
typedef internal::traits< MatrixWrapper< ExpressionType > >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Base::CoeffReturnType CoeffReturnType
typedef Base::ConstTransposeReturnType ConstTransposeReturnType
typedef Base::RowXpr RowXpr
typedef Base::ColXpr ColXpr
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef Base::PlainObject PlainObject
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, ConstTransposeReturnType >, ConstTransposeReturnType >::type AdjointReturnType
typedef Matrix< std::complex< RealScalar >, internal::traits< MatrixWrapper< ExpressionType > >::ColsAtCompileTime, 1, ColMajor > EigenvaluesReturnType
typedef CwiseNullaryOp< internal::scalar_identity_op< Scalar >, PlainObject > IdentityReturnType
typedef Block< const CwiseNullaryOp< internal::scalar_identity_op< Scalar >, SquareMatrixType >, internal::traits< MatrixWrapper< ExpressionType > >::RowsAtCompileTime, internal::traits< MatrixWrapper< ExpressionType > >::ColsAtCompileTime > BasisReturnType
typedef Diagonal< MatrixWrapper< ExpressionType > > DiagonalReturnType
typedef internal::add_const< Diagonal< constDerived > >::type ConstDiagonalReturnType
typedef Diagonal< MatrixWrapper< ExpressionType >, DynamicIndex > DiagonalDynamicIndexReturnType
typedef internal::add_const< Diagonal< constDerived, DynamicIndex > >::type ConstDiagonalDynamicIndexReturnType
typedef Homogeneous< MatrixWrapper< ExpressionType >, HomogeneousReturnTypeDirection > HomogeneousReturnType
typedef Block< const MatrixWrapper< ExpressionType >, internal::traits< MatrixWrapper< ExpressionType > >::ColsAtCompileTime==1 ? SizeMinusOne :1, internal::traits< MatrixWrapper< ExpressionType > >::ColsAtCompileTime==1 ? 1 :SizeMinusOne > ConstStartMinusOne
typedef internal::stem_function< Scalar >::type StemFunction
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime , Flags = internal::traits<Derived>::Flags ,
IsRowMajor = int(Flags) & RowMajorBit , InnerSizeAtCompileTime , InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret , OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef Scalar value_type
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > SequentialLinSpacedReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const_on_value_type< typenameinternal::eval< Derived >::type >::type EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
Public Member Functions
EIGEN_DEVICE_FUNC MatrixWrapper (ExpressionType &matrix)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Index innerStride () const
EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue * data ()
EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index index) const
EIGEN_DEVICE_FUNC const internal::remove_all< NestedExpressionType >::type & nestedExpression () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC Index diagonalSize () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & operator+= (const MatrixBase< OtherDerived > &other)
EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & operator+= (const MatrixBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC MatrixWrapper< ExpressionType > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & operator-= (const MatrixBase< OtherDerived > &other)
EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & operator-= (const MatrixBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC MatrixWrapper< ExpressionType > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const Product< MatrixWrapper< ExpressionType >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const Product< MatrixWrapper< ExpressionType >, DiagonalDerived, LazyProduct > operator* (const DiagonalBase< DiagonalDerived > &diagonal) const
const Product< MatrixWrapper< ExpressionType >, DiagonalDerived, LazyProduct > operator* (const DiagonalBase< DiagonalDerived > &a_diagonal) const
const Product< MatrixWrapper< ExpressionType >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC const Product< MatrixWrapper< ExpressionType >, OtherDerived, LazyProduct > lazyProduct (const MatrixBase< OtherDerived > &other) const
const Product< MatrixWrapper< ExpressionType >, OtherDerived, LazyProduct > lazyProduct (const MatrixBase< OtherDerived > &other) const
MatrixWrapper< ExpressionType > & operator*= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & operator*= (const Scalar &other)
void applyOnTheLeft (const EigenBase< OtherDerived > &other)
void applyOnTheLeft (Index p, Index q, const JacobiRotation< OtherScalar > &j)
void applyOnTheRight (const EigenBase< OtherDerived > &other)
void applyOnTheRight (Index p, Index q, const JacobiRotation< OtherScalar > &j)
EIGEN_DEVICE_FUNC ScalarBinaryOpTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar, typenameinternal::traits< OtherDerived >::Scalar >::ReturnType dot (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ScalarBinaryOpTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar, typenameinternal::traits< OtherDerived >::Scalar >::ReturnType dot (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC RealScalar squaredNorm () const
EIGEN_DEVICE_FUNC RealScalar norm () const
RealScalar stableNorm () const
RealScalar blueNorm () const
RealScalar hypotNorm () const
EIGEN_DEVICE_FUNC const PlainObject normalized () const
EIGEN_DEVICE_FUNC const PlainObject stableNormalized () const
EIGEN_DEVICE_FUNC void normalize ()
EIGEN_DEVICE_FUNC void stableNormalize ()
EIGEN_DEVICE_FUNC const AdjointReturnType adjoint () const
EIGEN_DEVICE_FUNC void adjointInPlace ()
EIGEN_DEVICE_FUNC DiagonalReturnType diagonal ()
EIGEN_DEVICE_FUNC ConstDiagonalReturnType diagonal () const
EIGEN_DEVICE_FUNC DiagonalIndexReturnType< Index >::Type diagonal ()
EIGEN_DEVICE_FUNC ConstDiagonalIndexReturnType< Index >::Type diagonal () const
EIGEN_DEVICE_FUNC DiagonalDynamicIndexReturnType diagonal (Index index)
EIGEN_DEVICE_FUNC ConstDiagonalDynamicIndexReturnType diagonal (Index index) const
EIGEN_DEVICE_FUNC TriangularViewReturnType< Mode >::Type triangularView ()
EIGEN_DEVICE_FUNC ConstTriangularViewReturnType< Mode >::Type triangularView () const
MatrixBase< MatrixWrapper< ExpressionType > >::template TriangularViewReturnType< Mode >::Type triangularView ()
MatrixBase< MatrixWrapper< ExpressionType > >::template ConstTriangularViewReturnType< Mode >::Type triangularView () const
EIGEN_DEVICE_FUNC SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
EIGEN_DEVICE_FUNC ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
MatrixBase< MatrixWrapper< ExpressionType > >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
MatrixBase< MatrixWrapper< ExpressionType > >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
const SparseView< MatrixWrapper< ExpressionType > > sparseView (const Scalar &m_reference=Scalar(0), const typename NumTraits< Scalar >::Real &m_epsilon=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC const DiagonalWrapper< const MatrixWrapper< ExpressionType > > asDiagonal () const
const PermutationWrapper< const MatrixWrapper< ExpressionType > > asPermutation () const
EIGEN_DEVICE_FUNC MatrixWrapper< ExpressionType > & setIdentity ()
EIGEN_DEVICE_FUNC MatrixWrapper< ExpressionType > & setIdentity (Index rows, Index cols)
Resizes to the given size, and writes the identity expression (not necessarily square) into *this.
bool isIdentity (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isDiagonal (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isUpperTriangular (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isLowerTriangular (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isOrthogonal (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isUnitary (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool operator== (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC bool operator!= (const MatrixBase< OtherDerived > &other) const
NoAlias< MatrixWrapper< ExpressionType >, Eigen::MatrixBase > noalias ()
const MatrixWrapper< ExpressionType > & forceAlignedAccess () const
MatrixWrapper< ExpressionType > & forceAlignedAccess ()
const MatrixWrapper< ExpressionType > & forceAlignedAccessIf () const
MatrixWrapper< ExpressionType > & forceAlignedAccessIf ()
internal::add_const_on_value_type< typenameinternal::conditional< Enable, ForceAlignedAccess< MatrixWrapper< ExpressionType > >, MatrixWrapper< ExpressionType > & >::type >::type forceAlignedAccessIf () const
internal::conditional< Enable, ForceAlignedAccess< MatrixWrapper< ExpressionType > >, MatrixWrapper< ExpressionType > & >::type forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC RealScalar lpNorm () const
NumTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar >::Real lpNorm () const
EIGEN_DEVICE_FUNC MatrixBase< MatrixWrapper< ExpressionType > > & matrix ()
EIGEN_DEVICE_FUNC const MatrixBase< MatrixWrapper< ExpressionType > > & matrix () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< MatrixWrapper< ExpressionType > > array ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArrayWrapper< const MatrixWrapper< ExpressionType > > array () const
const FullPivLU< PlainObject > fullPivLu () const
const PartialPivLU< PlainObject > partialPivLu () const
const PartialPivLU< PlainObject > lu () const
const Inverse< MatrixWrapper< ExpressionType > > inverse () const
void computeInverseAndDetWithCheck (ResultType &inverse, typename ResultType::Scalar &determinant, bool &invertible, const RealScalar &absDeterminantThreshold=NumTraits< Scalar >::dummy_precision()) const
void computeInverseWithCheck (ResultType &inverse, bool &invertible, const RealScalar &absDeterminantThreshold=NumTraits< Scalar >::dummy_precision()) const
Scalar determinant () const
const LLT< PlainObject > llt () const
const LDLT< PlainObject > ldlt () const
const HouseholderQR< PlainObject > householderQr () const
const ColPivHouseholderQR< PlainObject > colPivHouseholderQr () const
const FullPivHouseholderQR< PlainObject > fullPivHouseholderQr () const
const CompleteOrthogonalDecomposition< PlainObject > completeOrthogonalDecomposition () const
EigenvaluesReturnType eigenvalues () const
Computes the eigenvalues of a matrix.
RealScalar operatorNorm () const
Computes the L2 operator norm.
JacobiSVD< PlainObject > jacobiSvd (unsigned int computationOptions=0) const
BDCSVD< PlainObject > bdcSvd (unsigned int computationOptions=0) const
EIGEN_DEVICE_FUNC cross_product_return_type< OtherDerived >::type cross (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC MatrixBase< MatrixWrapper< ExpressionType > >::template cross_product_return_type< OtherDerived >::type cross (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC PlainObject cross3 (const MatrixBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC PlainObject unitOrthogonal (void) const
EIGEN_DEVICE_FUNC Matrix< Scalar, 3, 1 > eulerAngles (Index a0, Index a1, Index a2) const
EIGEN_DEVICE_FUNC HomogeneousReturnType homogeneous () const
typedef EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE (ConstStartMinusOne, Scalar, quotient) HNormalizedReturnType
EIGEN_DEVICE_FUNC const HNormalizedReturnType hnormalized () const
homogeneous normalization
void makeHouseholderInPlace (Scalar &tau, RealScalar &beta)
void makeHouseholder (EssentialPart &essential, Scalar &tau, RealScalar &beta) const
void applyHouseholderOnTheLeft (const EssentialPart &essential, const Scalar &tau, Scalar *workspace)
void applyHouseholderOnTheRight (const EssentialPart &essential, const Scalar &tau, Scalar *workspace)
EIGEN_STRONG_INLINE const SparseMatrixBase< OtherDerived >::template CwiseProductDenseReturnType< MatrixWrapper< ExpressionType > >::Type cwiseProduct (const SparseMatrixBase< OtherDerived > &other) const
const MatrixFunctionReturnValue< MatrixWrapper< ExpressionType > > matrixFunction (StemFunction f) const
Helper function for the unsupported MatrixFunctions module.
EIGEN_DEVICE_FUNC MatrixWrapper< ExpressionType > & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC Index nonZeros () const
EIGEN_DEVICE_FUNC Index outerSize () const
EIGEN_DEVICE_FUNC Index innerSize () const
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename Derived >
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename OtherDerived >
bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool hasNaN () const
bool allFinite () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar prod () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Func >
EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar redux (const Func &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, const typename ThenDerived::Scalar &elseScalar) const
template<typename ElseDerived >
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (const typename ElseDerived::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
template<int RowFactor, int ColFactor>
const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC const IdentityReturnType Identity ()
static EIGEN_DEVICE_FUNC const IdentityReturnType Identity (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const BasisReturnType Unit (Index size, Index i)
static EIGEN_DEVICE_FUNC const BasisReturnType Unit (Index i)
static EIGEN_DEVICE_FUNC const BasisReturnType UnitX ()
static EIGEN_DEVICE_FUNC const BasisReturnType UnitY ()
static EIGEN_DEVICE_FUNC const BasisReturnType UnitZ ()
static EIGEN_DEVICE_FUNC const BasisReturnType UnitW ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Protected Member Functions
MatrixWrapper< ExpressionType > & operator+= (const ArrayBase< OtherDerived > &)
MatrixWrapper< ExpressionType > & operator-= (const ArrayBase< OtherDerived > &)
Protected Attributes
NestedExpressionType m_expression
Related Symbols
(Note that these are not member symbols.)
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename ExpressionType>
class Eigen::MatrixWrapper< ExpressionType >
Expression of an array as a mathematical vector or matrix.
This class is the return type of ArrayBase::matrix(), and most of the time this is the only way it is use.
See also
MatrixBase::matrix(), class ArrayWrapper
Member Typedef Documentation
AdjointReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,ConstTransposeReturnType>,ConstTransposeReturnType>::type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::AdjointReturnType inherited
Base
template<typename ExpressionType > typedef MatrixBase<MatrixWrapper<ExpressionType> > Eigen::MatrixWrapper< ExpressionType >::Base
BasisReturnType
typedef Block<const CwiseNullaryOp<internal::scalar_identity_op<Scalar>, SquareMatrixType>, internal::traits<MatrixWrapper< ExpressionType > >::RowsAtCompileTime, internal::traits<MatrixWrapper< ExpressionType > >::ColsAtCompileTime> Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::BasisReturnType inherited
CoeffReturnType
typedef Base::CoeffReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::CoeffReturnType inherited
ColwiseReturnType
template<typename Derived > typedef VectorwiseOp<Derived, Vertical> Eigen::DenseBase< Derived >::ColwiseReturnType inherited
ColXpr
typedef Base::ColXpr Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::ColXpr inherited
ConstantReturnType
typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,PlainObject> Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::ConstantReturnType inherited
ConstColwiseReturnType
template<typename Derived > typedef const VectorwiseOp<const Derived, Vertical> Eigen::DenseBase< Derived >::ConstColwiseReturnType inherited
ConstDiagonalDynamicIndexReturnType
typedef internal::add_const<Diagonal<constDerived,DynamicIndex>>::type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::ConstDiagonalDynamicIndexReturnType inherited
ConstDiagonalReturnType
typedef internal::add_const<Diagonal<constDerived>>::type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::ConstDiagonalReturnType inherited
ConstReverseReturnType
template<typename Derived > typedef const Reverse<const Derived, BothDirections> Eigen::DenseBase< Derived >::ConstReverseReturnType inherited
ConstRowwiseReturnType
template<typename Derived > typedef const VectorwiseOp<const Derived, Horizontal> Eigen::DenseBase< Derived >::ConstRowwiseReturnType inherited
ConstStartMinusOne
typedef Block<const MatrixWrapper< ExpressionType > , internal::traits<MatrixWrapper< ExpressionType > >::ColsAtCompileTime==1 ? SizeMinusOne : 1, internal::traits<MatrixWrapper< ExpressionType > >::ColsAtCompileTime==1 ? 1 : SizeMinusOne> Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::ConstStartMinusOne inherited
ConstTransposeReturnType
typedef Base::ConstTransposeReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::ConstTransposeReturnType inherited
DiagonalDynamicIndexReturnType
typedef Diagonal<MatrixWrapper< ExpressionType > ,DynamicIndex> Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::DiagonalDynamicIndexReturnType inherited
DiagonalReturnType
typedef Diagonal<MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::DiagonalReturnType inherited
EigenvaluesReturnType
typedef Matrix<std::complex<RealScalar>, internal::traits<MatrixWrapper< ExpressionType > >::ColsAtCompileTime, 1, ColMajor> Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::EigenvaluesReturnType inherited
EvalReturnType
template<typename Derived > typedef internal::add_const_on_value_type<typenameinternal::eval<Derived>::type>::type Eigen::DenseBase< Derived >::EvalReturnType inherited
HomogeneousReturnType
typedef Homogeneous<MatrixWrapper< ExpressionType > , HomogeneousReturnTypeDirection> Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::HomogeneousReturnType inherited
IdentityReturnType
typedef CwiseNullaryOp<internal::scalar_identity_op<Scalar>,PlainObject> Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::IdentityReturnType inherited
InnerIterator
template<typename Derived > typedef Eigen::InnerIterator<Derived> Eigen::DenseBase< Derived >::InnerIterator inherited
Inner iterator type to iterate over the coefficients of a row or column.
See also
class InnerIterator
NestedExpression
template<typename ExpressionType > typedef internal::remove_all<ExpressionType>::type Eigen::MatrixWrapper< ExpressionType >::NestedExpression
NestedExpressionType
template<typename ExpressionType > typedef internal::ref_selector<ExpressionType>::non_const_type Eigen::MatrixWrapper< ExpressionType >::NestedExpressionType
PacketScalar
typedef internal::packet_traits<Scalar>::type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::PacketScalar inherited
PlainArray
template<typename Derived > typedef Array<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags&RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime > Eigen::DenseBase< Derived >::PlainArray inherited
The plain array type corresponding to this expression.
See also
PlainObject
PlainMatrix
template<typename Derived > typedef Matrix<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags&RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime > Eigen::DenseBase< Derived >::PlainMatrix inherited
The plain matrix type corresponding to this expression.
See also
PlainObject
PlainObject
typedef Base::PlainObject Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject inherited
RandomAccessLinSpacedReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::linspaced_op<Scalar,PacketScalar>,PlainObject> Eigen::DenseBase< Derived >::RandomAccessLinSpacedReturnType inherited
RandomReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_random_op<Scalar>,PlainObject> Eigen::DenseBase< Derived >::RandomReturnType inherited
RealScalar
typedef NumTraits<Scalar>::Real Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::RealScalar inherited
ReverseReturnType
template<typename Derived > typedef Reverse<Derived, BothDirections> Eigen::DenseBase< Derived >::ReverseReturnType inherited
RowwiseReturnType
template<typename Derived > typedef VectorwiseOp<Derived, Horizontal> Eigen::DenseBase< Derived >::RowwiseReturnType inherited
RowXpr
typedef Base::RowXpr Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::RowXpr inherited
Scalar
typedef internal::traits<MatrixWrapper< ExpressionType > >::Scalar Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::Scalar inherited
ScalarWithConstIfNotLvalue
template<typename ExpressionType > typedef internal::conditional<internal::is_lvalue<ExpressionType>::value,Scalar,constScalar>::type Eigen::MatrixWrapper< ExpressionType >::ScalarWithConstIfNotLvalue
SequentialLinSpacedReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::linspaced_op<Scalar,PacketScalar>,PlainObject> Eigen::DenseBase< Derived >::SequentialLinSpacedReturnType inherited
SquareMatrixType
typedef Matrix<Scalar,EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime)> Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::SquareMatrixType inherited
type of the equivalent square matrix
StemFunction
typedef internal::stem_function<Scalar>::type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::StemFunction inherited
StorageBaseType
typedef MatrixBase Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::StorageBaseType inherited
StorageIndex
typedef internal::traits<MatrixWrapper< ExpressionType > >::StorageIndex Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::StorageIndex inherited
StorageKind
typedef internal::traits<MatrixWrapper< ExpressionType > >::StorageKind Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::StorageKind inherited
TransposeReturnType
template<typename Derived > typedef Transpose<Derived> Eigen::DenseBase< Derived >::TransposeReturnType inherited
value_type
template<typename Derived > typedef Scalar Eigen::DenseBase< Derived >::value_type inherited
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
This value is equal to the maximum possible number of rows that this expression might have. If this expression might have an arbitrarily high number of rows, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
RowsAtCompileTime, MaxColsAtCompileTime, MaxSizeAtCompileTime
MaxColsAtCompileTime
This value is equal to the maximum possible number of columns that this expression might have. If this expression might have an arbitrarily high number of columns, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
ColsAtCompileTime, MaxRowsAtCompileTime, MaxSizeAtCompileTime
MaxSizeAtCompileTime
This value is equal to the maximum possible number of coefficients that this expression might have. If this expression might have an arbitrarily high number of coefficients, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
SizeAtCompileTime, MaxRowsAtCompileTime, MaxColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
True if this expression has row-major storage order.
InnerSizeAtCompileTime
InnerStrideAtCompileTime
OuterStrideAtCompileTime
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::MaxRowsAtCompileTime,
                                                      internal::traits<Derived>::MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime == 1
                           || internal::traits<Derived>::MaxColsAtCompileTime == 1,
      Flags = internal::traits<Derived>::Flags,
      IsRowMajor = int(Flags) & RowMajorBit,
      InnerSizeAtCompileTime = int(IsVectorAtCompileTime) ? int(SizeAtCompileTime)
                             : int(IsRowMajor) ? int(ColsAtCompileTime) : int(RowsAtCompileTime),
      InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret,
      OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
    };
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
IsPlainObjectBase
{ IsPlainObjectBase = 0 };
anonymous enum
anonymous enum inherited
         { HomogeneousReturnTypeDirection = ColsAtCompileTime==1&&RowsAtCompileTime==1 ? ((internal::traits<Derived>::Flags&RowMajorBit)==RowMajorBit ? Horizontal : Vertical)
                                          : ColsAtCompileTime==1 ? Vertical : Horizontal };
anonymous enum
anonymous enum inherited
         {
      SizeMinusOne = SizeAtCompileTime==Dynamic ? Dynamic : SizeAtCompileTime-1
    };
Constructor & Destructor Documentation
MatrixWrapper()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Eigen::MatrixWrapper< ExpressionType >::MatrixWrapper (ExpressionType & matrix) inline explicit
: m_expression(matrix) {}
Member Function Documentation
adjoint()
const MatrixBase< MatrixWrapper< ExpressionType > >::AdjointReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::adjoint inline inherited
Returns
an expression of the adjoint (i.e. conjugate transpose) of *this.
Example:
Output:
Warning
If you want to replace a matrix by its own adjoint, do NOT do this:
m = m.adjoint(); // bug!!! caused by aliasing effect
Instead, use the adjointInPlace() method:
m.adjointInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.adjoint().eval();
See also
adjointInPlace(), transpose(), conjugate(), class Transpose, class internal::scalar_conjugate_op
{
  return AdjointReturnType(this->transpose());
}
adjointInPlace()
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::adjointInPlace inline inherited
This is the "in place" version of adjoint(): it replaces *this by its own transpose. Thus, doing
m.adjointInPlace();
has the same effect on m as doing
m = m.adjoint().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own adjoint. If you just need the adjoint of a matrix, use adjoint().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See also
transpose(), adjoint(), transposeInPlace()
{
  derived() = adjoint().eval();
}
all()
template<typename Derived > bool Eigen::DenseBase< Derived >::all inline inherited
Returns
true if all coefficients are true
Example:
Output:
See also
any(), Cwise::operator<()
{
  typedef internal::evaluator<Derived> Evaluator;
  enum {
    unroll = SizeAtCompileTime != Dynamic
          && SizeAtCompileTime * (Evaluator::CoeffReadCost + NumTraits<Scalar>::AddCost) <= EIGEN_UNROLLING_LIMIT
  };
  Evaluator evaluator(derived());
  if(unroll)
    return internal::all_unroller<Evaluator, unroll ? int(SizeAtCompileTime) : Dynamic>::run(evaluator);
  else
  {
    for(Index j = 0; j < cols(); ++j)
      for(Index i = 0; i < rows(); ++i)
        if (!evaluator.coeff(i, j)) return false;
    return true;
  }
}
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
allFinite()
template<typename Derived > bool Eigen::DenseBase< Derived >::allFinite inline inherited
Returns
true if *this contains only finite numbers, i.e., no NaN and no +/-INF values.
See also
hasNaN()
{
#if EIGEN_COMP_MSVC || (defined __FAST_MATH__)
  return derived().array().isFinite().all();
#else
  return !((derived()-derived()).hasNaN());
#endif
}
any()
template<typename Derived > bool Eigen::DenseBase< Derived >::any inline inherited
Returns
true if at least one coefficient is true
See also
all()
{
  typedef internal::evaluator<Derived> Evaluator;
  enum {
    unroll = SizeAtCompileTime != Dynamic
          && SizeAtCompileTime * (Evaluator::CoeffReadCost + NumTraits<Scalar>::AddCost) <= EIGEN_UNROLLING_LIMIT
  };
  Evaluator evaluator(derived());
  if(unroll)
    return internal::any_unroller<Evaluator, unroll ? int(SizeAtCompileTime) : Dynamic>::run(evaluator);
  else
  {
    for(Index j = 0; j < cols(); ++j)
      for(Index i = 0; i < rows(); ++i)
        if (evaluator.coeff(i, j)) return true;
    return false;
  }
}
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
applyHouseholderOnTheLeft()
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::applyHouseholderOnTheLeft (const EssentialPart & essential, const Scalar & tau, Scalar * workspace) inherited
Apply the elementary reflector H given by with from the left to a vector or matrix.
On input:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
workspace a pointer to working space with at least this->cols() * essential.size() entries
See also
MatrixBase::makeHouseholder(), MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheRight()
{
  if(rows() == 1)
  {
    *this *= Scalar(1)-tau;
  }
  else if(tau!=Scalar(0))
  {
    Map<typename internal::plain_row_type<PlainObject>::type> tmp(workspace,cols());
    Block<Derived, EssentialPart::SizeAtCompileTime, Derived::ColsAtCompileTime> bottom(derived(), 1, 0, rows()-1, cols());
    tmp.noalias() = essential.adjoint() * bottom;
    tmp += this->row(0);
    this->row(0) -= tau * tmp;
    bottom.noalias() -= tau * essential * tmp;
  }
}
applyHouseholderOnTheRight()
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::applyHouseholderOnTheRight (const EssentialPart & essential, const Scalar & tau, Scalar * workspace) inherited
Apply the elementary reflector H given by with from the right to a vector or matrix.
On input:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
workspace a pointer to working space with at least this->cols() * essential.size() entries
See also
MatrixBase::makeHouseholder(), MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheLeft()
{
  if(cols() == 1)
  {
    *this *= Scalar(1)-tau;
  }
  else if(tau!=Scalar(0))
  {
    Map<typename internal::plain_col_type<PlainObject>::type> tmp(workspace,rows());
    Block<Derived, Derived::RowsAtCompileTime, EssentialPart::SizeAtCompileTime> right(derived(), 0, 1, rows(), cols()-1);
    tmp.noalias() = right * essential.conjugate();
    tmp += this->col(0);
    this->col(0) -= tau * tmp;
    right.noalias() -= tau * tmp * essential.transpose();
  }
}
applyOnTheLeft() [1/2]
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::applyOnTheLeft (const EigenBase< OtherDerived > & other) inline inherited
replaces *this by other * *this.
Example:
Output:
{
  other.derived().applyThisOnTheLeft(derived());
}
applyOnTheLeft() [2/2]
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::applyOnTheLeft (Index p, Index q, const JacobiRotation< OtherScalar > & j) inline inherited
\jacobi_module Applies the rotation in the plane j to the rows p and q of *this, i.e., it computes B = J * B, with .
See also
class JacobiRotation, MatrixBase::applyOnTheRight(), internal::apply_rotation_in_the_plane()
{
  RowXpr x(this->row(p));
  RowXpr y(this->row(q));
  internal::apply_rotation_in_the_plane(x, y, j);
}
applyOnTheRight() [1/2]
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::applyOnTheRight (const EigenBase< OtherDerived > & other) inline inherited
replaces *this by *this * other. It is equivalent to MatrixBase::operator*=().
Example:
Output:
{
  other.derived().applyThisOnTheRight(derived());
}
applyOnTheRight() [2/2]
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::applyOnTheRight (Index p, Index q, const JacobiRotation< OtherScalar > & j) inline inherited
Applies the rotation in the plane j to the columns p and q of *this, i.e., it computes B = B * J with .
See also
class JacobiRotation, MatrixBase::applyOnTheLeft(), internal::apply_rotation_in_the_plane()
{
  ColXpr x(this->col(p));
  ColXpr y(this->col(q));
  internal::apply_rotation_in_the_plane(x, y, j.transpose());
}
array() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ArrayWrapper< MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::array () inline inherited
Returns
an Array expression of this matrix
See also
ArrayBase::matrix()
{ return ArrayWrapper<Derived>(derived()); }
array() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const ArrayWrapper< const MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::array () const inline inherited
Returns
a const Array expression of this matrix
See also
ArrayBase::matrix()
{ return ArrayWrapper<const Derived>(derived()); }
asDiagonal()
const DiagonalWrapper< const MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::asDiagonal inline inherited
Returns
a pseudo-expression of a diagonal matrix with *this as vector of diagonal coefficients
\only_for_vectors
Example:
Output:
See also
class DiagonalWrapper, class DiagonalMatrix, diagonal(), isDiagonal()
{
  return DiagonalWrapper<const Derived>(derived());
}
asPermutation()
const PermutationWrapper< const MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::asPermutation inherited
{
  return derived();
}
bdcSvd()
BDCSVD< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::bdcSvd (unsigned int computationOptions = 0) const inline inherited
\svd_module
Returns
the singular value decomposition of *this computed by Divide & Conquer algorithm
See also
class BDCSVD
{
  return BDCSVD<PlainObject>(*this, computationOptions);
}
blueNorm()
NumTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar >::Real Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::blueNorm inline inherited
Returns
the l2 norm of *this using the Blue's algorithm. A Portable Fortran Program to Find the Euclidean Norm of a Vector, ACM TOMS, Vol 4, Issue 1, 1978.
For architecture/scalar types without vectorization, this version is much faster than stableNorm(). Otherwise the stableNorm() is faster.
See also
norm(), stableNorm(), hypotNorm()
{
  return internal::blueNorm_impl(*this);
}
coeffRef() [1/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC const Scalar & Eigen::MatrixWrapper< ExpressionType >::coeffRef (Index index) const inline
    {
      return m_expression.coeffRef(index);
    }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
coeffRef() [2/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC const Scalar & Eigen::MatrixWrapper< ExpressionType >::coeffRef (Index rowId, Index colId) const inline
    {
      return m_expression.derived().coeffRef(rowId, colId);
    }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
colPivHouseholderQr()
const ColPivHouseholderQR< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::colPivHouseholderQr inline inherited
Returns
the column-pivoting Householder QR decomposition of *this.
See also
class ColPivHouseholderQR
{
  return ColPivHouseholderQR<PlainObject>(eval());
}
cols()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::MatrixWrapper< ExpressionType >::cols () const inline
{ return m_expression.cols(); }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
Referenced by Eigen::MatrixWrapper< ExpressionType >::resize().
colwise() [1/2]
template<typename Derived > DenseBase< Derived >::ColwiseReturnType Eigen::DenseBase< Derived >::colwise inline inherited
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
  return ColwiseReturnType(derived());
}
colwise() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ConstColwiseReturnType Eigen::DenseBase< Derived >::colwise () const inline inherited
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
      return ConstColwiseReturnType(derived());
    }
Referenced by igl::bounding_box(), igl::copyleft::offset_surface(), and Eigen::umeyama().
completeOrthogonalDecomposition()
const CompleteOrthogonalDecomposition< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::completeOrthogonalDecomposition inline inherited
Returns
the complete orthogonal decomposition of *this.
See also
class CompleteOrthogonalDecomposition
{
  return CompleteOrthogonalDecomposition<PlainObject>(eval());
}
computeInverseAndDetWithCheck()
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::computeInverseAndDetWithCheck (ResultType & inverse, typename ResultType::Scalar & determinant, bool & invertible, const RealScalar & absDeterminantThreshold = NumTraits<Scalar>::dummy_precision()) const inline inherited
\lu_module
Computation of matrix inverse and determinant, with invertibility check.
This is only for fixed-size square matrices of size up to 4x4.
Parameters
inverse Reference to the matrix in which to store the inverse.
determinant Reference to the variable in which to store the determinant.
invertible Reference to the bool variable in which to store whether the matrix is invertible.
absDeterminantThreshold Optional parameter controlling the invertibility check. The matrix will be declared invertible if the absolute value of its determinant is greater than this threshold.
Example:
Output:
See also
inverse(), computeInverseWithCheck()
{
  // i'd love to put some static assertions there, but SFINAE means that they have no effect...
  eigen_assert(rows() == cols());
  // for 2x2, it's worth giving a chance to avoid evaluating.
  // for larger sizes, evaluating has negligible cost and limits code size.
  typedef typename internal::conditional<
    RowsAtCompileTime == 2,
    typename internal::remove_all<typename internal::nested_eval<Derived, 2>::type>::type,
    PlainObject
  >::type MatrixType;
  internal::compute_inverse_and_det_with_check<MatrixType, ResultType>::run
    (derived(), absDeterminantThreshold, inverse, determinant, invertible);
}
computeInverseWithCheck()
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::computeInverseWithCheck (ResultType & inverse, bool & invertible, const RealScalar & absDeterminantThreshold = NumTraits<Scalar>::dummy_precision()) const inline inherited
\lu_module
Computation of matrix inverse, with invertibility check.
This is only for fixed-size square matrices of size up to 4x4.
Parameters
inverse Reference to the matrix in which to store the inverse.
invertible Reference to the bool variable in which to store whether the matrix is invertible.
absDeterminantThreshold Optional parameter controlling the invertibility check. The matrix will be declared invertible if the absolute value of its determinant is greater than this threshold.
Example:
Output:
See also
inverse(), computeInverseAndDetWithCheck()
{
  Scalar determinant;
  // i'd love to put some static assertions there, but SFINAE means that they have no effect...
  eigen_assert(rows() == cols());
  computeInverseAndDetWithCheck(inverse,determinant,invertible,absDeterminantThreshold);
}
Constant() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (const Scalar & value) static inherited
Returns
an expression of a constant matrix of value value
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
  return DenseBase<Derived>::NullaryExpr(RowsAtCompileTime, ColsAtCompileTime, internal::scalar_constant_op<Scalar>(value));
}
References EIGEN_STATIC_ASSERT_FIXED_SIZE, and Eigen::DenseBase< Derived >::NullaryExpr().
Constant() [2/3]
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index rows, Index cols, const Scalar & value) static inherited
Returns
an expression of a constant matrix of value value
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  return DenseBase<Derived>::NullaryExpr(rows, cols, internal::scalar_constant_op<Scalar>(value));
}
References Eigen::DenseBase< Derived >::NullaryExpr().
Constant() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index size, const Scalar & value) static inherited
Returns
an expression of a constant matrix of value value
The parameter size is the size of the returned vector. Must be compatible with this DenseBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  return DenseBase<Derived>::NullaryExpr(size, internal::scalar_constant_op<Scalar>(value));
}
References Eigen::DenseBase< Derived >::NullaryExpr().
count()
template<typename Derived > Eigen::Index Eigen::DenseBase< Derived >::count inline inherited
Returns
the number of coefficients which evaluate to true
See also
all(), any()
{
  return derived().template cast<bool>().template cast<Index>().sum();
}
cross() [1/2]
EIGEN_DEVICE_FUNC cross_product_return_type< OtherDerived >::type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::cross (const MatrixBase< OtherDerived > & other) const inline inherited
cross() [2/2]
EIGEN_DEVICE_FUNC MatrixBase< MatrixWrapper< ExpressionType > >::template cross_product_return_type< OtherDerived >::type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::cross (const MatrixBase< OtherDerived > & other) const inline inherited
\geometry_module
Returns
the cross product of *this and other
Here is a very good explanation of cross-product: http://xkcd.com/199/
With complex numbers, the cross product is implemented as
See also
MatrixBase::cross3()
{
  EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(Derived,3)
  EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(OtherDerived,3)
  // Note that there is no need for an expression here since the compiler
  // optimize such a small temporary very well (even within a complex expression)
  typename internal::nested_eval<Derived,2>::type lhs(derived());
  typename internal::nested_eval<OtherDerived,2>::type rhs(other.derived());
  return typename cross_product_return_type<OtherDerived>::type(
    numext::conj(lhs.coeff(1) * rhs.coeff(2) - lhs.coeff(2) * rhs.coeff(1)),
    numext::conj(lhs.coeff(2) * rhs.coeff(0) - lhs.coeff(0) * rhs.coeff(2)),
    numext::conj(lhs.coeff(0) * rhs.coeff(1) - lhs.coeff(1) * rhs.coeff(0))
  );
}
cross3()
EIGEN_DEVICE_FUNC MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::cross3 (const MatrixBase< OtherDerived > & other) const inline inherited
\geometry_module
Returns
the cross product of *this and other using only the x, y, and z coefficients
The size of *this and other must be four. This function is especially useful when using 4D vectors instead of 3D ones to get advantage of SSE/AltiVec vectorization.
See also
MatrixBase::cross()
{
  EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(Derived,4)
  EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(OtherDerived,4)
  typedef typename internal::nested_eval<Derived,2>::type DerivedNested;
  typedef typename internal::nested_eval<OtherDerived,2>::type OtherDerivedNested;
  DerivedNested lhs(derived());
  OtherDerivedNested rhs(other.derived());
  return internal::cross3_impl<Architecture::Target,
                        typename internal::remove_all<DerivedNested>::type,
                        typename internal::remove_all<OtherDerivedNested>::type>::run(lhs,rhs);
}
cwiseProduct()
EIGEN_STRONG_INLINE const SparseMatrixBase< OtherDerived >::template CwiseProductDenseReturnType< MatrixWrapper< ExpressionType > >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::cwiseProduct (const SparseMatrixBase< OtherDerived > & other) const inline inherited
    {
      return other.cwiseProduct(derived());
    }
data() [1/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue * Eigen::MatrixWrapper< ExpressionType >::data () inline
{ return m_expression.data(); }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
data() [2/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC const Scalar * Eigen::MatrixWrapper< ExpressionType >::data () const inline
{ return m_expression.data(); }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
determinant()
internal::traits< MatrixWrapper< ExpressionType > >::Scalar Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::determinant inline inherited
\lu_module
Returns
the determinant of this matrix
{
  eigen_assert(rows() == cols());
  typedef typename internal::nested_eval<Derived,Base::RowsAtCompileTime>::type Nested;
  return internal::determinant_impl<typename internal::remove_all<Nested>::type>::run(derived());
}
diagonal() [1/6]
MatrixBase< MatrixWrapper< ExpressionType > >::template DiagonalIndexReturnType< Index_ >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::diagonal inline inherited
Returns
an expression of the main diagonal of the matrix *this
*this is not required to be square.
Example:
Output:
See also
class Diagonal
Returns
an expression of the DiagIndex-th sub or super diagonal of the matrix *this
*this is not required to be square.
The template parameter DiagIndex represent a super diagonal if DiagIndex > 0 and a sub diagonal otherwise. DiagIndex == 0 is equivalent to the main diagonal.
Example:
Output:
See also
MatrixBase::diagonal(), class Diagonal
{
  return DiagonalReturnType(derived());
}
diagonal() [2/6]
EIGEN_DEVICE_FUNC DiagonalIndexReturnType< Index >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::diagonal () inherited
diagonal() [3/6]
MatrixBase< MatrixWrapper< ExpressionType > >::template ConstDiagonalIndexReturnType< Index_ >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::diagonal inline inherited
This is the const version of diagonal().
This is the const version of diagonal<int>().
{
  return ConstDiagonalReturnType(derived());
}
diagonal() [4/6]
EIGEN_DEVICE_FUNC ConstDiagonalIndexReturnType< Index >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::diagonal () const inherited
diagonal() [5/6]
MatrixBase< MatrixWrapper< ExpressionType > >::DiagonalDynamicIndexReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::diagonal (Index index) inline inherited
Returns
an expression of the DiagIndex-th sub or super diagonal of the matrix *this
*this is not required to be square.
The template parameter DiagIndex represent a super diagonal if DiagIndex > 0 and a sub diagonal otherwise. DiagIndex == 0 is equivalent to the main diagonal.
Example:
Output:
See also
MatrixBase::diagonal(), class Diagonal
{
  return DiagonalDynamicIndexReturnType(derived(), index);
}
diagonal() [6/6]
MatrixBase< MatrixWrapper< ExpressionType > >::ConstDiagonalDynamicIndexReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::diagonal (Index index) const inline inherited
This is the const version of diagonal(Index).
{
  return ConstDiagonalDynamicIndexReturnType(derived(), index);
}
diagonalSize()
EIGEN_DEVICE_FUNC Index Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::diagonalSize () const inline inherited
Returns
the size of the main diagonal, which is min(rows(),cols()).
See also
rows(), cols(), SizeAtCompileTime.
{ return (numext::mini)(rows(),cols()); }
dot() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ScalarBinaryOpTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar, typenameinternal::traits< OtherDerived >::Scalar >::ReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::dot (const MatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
#if !(defined(EIGEN_NO_STATIC_ASSERT) && defined(EIGEN_NO_DEBUG))
  typedef internal::scalar_conj_product_op<Scalar,typename OtherDerived::Scalar> func;
  EIGEN_CHECK_BINARY_COMPATIBILIY(func,Scalar,typename OtherDerived::Scalar);
#endif
  eigen_assert(size() == other.size());
  return internal::dot_nocheck<Derived,OtherDerived>::run(*this, other);
}
dot() [2/2]
Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::dot (const MatrixBase< OtherDerived > & other) const inherited
Returns
the dot product of *this with other.
\only_for_vectors
Note
If the scalar type is complex numbers, then this function returns the hermitian (sesquilinear) dot product, conjugate-linear in the first variable and linear in the second variable.
See also
squaredNorm(), norm()
EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE()
typedef Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE (ConstStartMinusOne , Scalar , quotient) inherited
eigenvalues()
MatrixBase< MatrixWrapper< ExpressionType > >::EigenvaluesReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::eigenvalues inline inherited
Computes the eigenvalues of a matrix.
Returns
Column vector containing the eigenvalues.
\eigenvalues_module This function computes the eigenvalues with the help of the EigenSolver class (for real matrices) or the ComplexEigenSolver class (for complex matrices).
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix.
The SelfAdjointView class provides a better algorithm for selfadjoint matrices.
Example:
Output:
See also
EigenSolver::eigenvalues(), ComplexEigenSolver::eigenvalues(), SelfAdjointView::eigenvalues()
{
  return internal::eigenvalues_selector<Derived, NumTraits<Scalar>::IsComplex>::run(derived());
}
eulerAngles()
EIGEN_DEVICE_FUNC Matrix< typename MatrixBase< MatrixWrapper< ExpressionType > >::Scalar, 3, 1 > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::eulerAngles (Index a0, Index a1, Index a2) const inline inherited
\geometry_module
Returns
the Euler-angles of the rotation matrix *this using the convention defined by the triplet (a0,a1,a2)
Each of the three parameters a0,a1,a2 represents the respective rotation axis as an integer in {0,1,2}. For instance, in:
Vector3f ea = mat.eulerAngles(2, 0, 2);
"2" represents the z axis and "0" the x axis, etc. The returned angles are such that we have the following equality:
mat == AngleAxisf(ea[0], Vector3f::UnitZ())
     * AngleAxisf(ea[1], Vector3f::UnitX())
     * AngleAxisf(ea[2], Vector3f::UnitZ());
This corresponds to the right-multiply conventions (with right hand side frames).
The returned angles are in the ranges [0:pi]x[-pi:pi]x[-pi:pi].
See also
class AngleAxis
{
  EIGEN_USING_STD_MATH(atan2)
  EIGEN_USING_STD_MATH(sin)
  EIGEN_USING_STD_MATH(cos)
  /* Implemented from Graphics Gems IV */
  EIGEN_STATIC_ASSERT_MATRIX_SPECIFIC_SIZE(Derived,3,3)
  Matrix<Scalar,3,1> res;
  typedef Matrix<typename Derived::Scalar,2,1> Vector2;
  const Index odd = ((a0+1)%3 == a1) ? 0 : 1;
  const Index i = a0;
  const Index j = (a0 + 1 + odd)%3;
  const Index k = (a0 + 2 - odd)%3;
  if (a0==a2)
  {
    res[0] = atan2(coeff(j,i), coeff(k,i));
    if((odd && res[0]<Scalar(0)) || ((!odd) && res[0]>Scalar(0)))
    {
      if(res[0] > Scalar(0)) {
        res[0] -= Scalar(EIGEN_PI);
      }
      else {
        res[0] += Scalar(EIGEN_PI);
      }
      Scalar s2 = Vector2(coeff(j,i), coeff(k,i)).norm();
      res[1] = -atan2(s2, coeff(i,i));
    }
    else
    {
      Scalar s2 = Vector2(coeff(j,i), coeff(k,i)).norm();
      res[1] = atan2(s2, coeff(i,i));
    }
    // With a=(0,1,0), we have i=0; j=1; k=2, and after computing the first two angles,
    // we can compute their respective rotation, and apply its inverse to M. Since the result must
    // be a rotation around x, we have:
    //
    //  c2  s1.s2 c1.s2                   1  0   0
    //  0   c1    -s1       *    M    =   0  c3  s3
    //  -s2 s1.c2 c1.c2                   0 -s3  c3
    //
    //  Thus:  m11.c1 - m21.s1 = c3  &   m12.c1 - m22.s1 = s3
    Scalar s1 = sin(res[0]);
    Scalar c1 = cos(res[0]);
    res[2] = atan2(c1*coeff(j,k)-s1*coeff(k,k), c1*coeff(j,j) - s1 * coeff(k,j));
  }
  else
  {
    res[0] = atan2(coeff(j,k), coeff(k,k));
    Scalar c2 = Vector2(coeff(i,i), coeff(i,j)).norm();
    if((odd && res[0]<Scalar(0)) || ((!odd) && res[0]>Scalar(0))) {
      if(res[0] > Scalar(0)) {
        res[0] -= Scalar(EIGEN_PI);
      }
      else {
        res[0] += Scalar(EIGEN_PI);
      }
      res[1] = atan2(-coeff(i,k), -c2);
    }
    else
      res[1] = atan2(-coeff(i,k), c2);
    Scalar s1 = sin(res[0]);
    Scalar c1 = cos(res[0]);
    res[2] = atan2(s1*coeff(k,i)-c1*coeff(j,i), c1*coeff(j,j) - s1 * coeff(k,j));
  }
  if (!odd)
    res = -res;
  return res;
}
eval()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType Eigen::DenseBase< MatrixWrapper< ExpressionType > >::eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
Warning
Be carefull with eval() and the auto C++ keyword, as detailed in this page .
    {
      // Even though MSVC does not honor strong inlining when the return type
      // is a dynamic matrix, we desperately need strong inlining for fixed
      // size types on MSVC.
      return typename internal::eval<Derived>::type(derived());
    }
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::evalTo (Dest &) const inline inherited
    {
      EIGEN_STATIC_ASSERT((internal::is_same<Dest,void>::value),THE_EVAL_EVALTO_FUNCTION_SHOULD_NEVER_BE_CALLED_FOR_DENSE_OBJECTS);
    }
References EIGEN_STATIC_ASSERT.
fill()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DenseBase< Derived >::fill (const Scalar & val) inherited
Alias for setConstant(): sets all coefficients in this expression to val.
See also
setConstant(), Constant(), class CwiseNullaryOp
{
  setConstant(val);
}
flagged()
template<typename Derived > template<unsigned int Added, unsigned int Removed> EIGEN_DEPRECATED const Derived & Eigen::DenseBase< Derived >::flagged () const inline inherited
    { return derived(); }
forceAlignedAccess() [1/2]
ForceAlignedAccess< MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::forceAlignedAccess inline inherited
Returns
an expression of *this with forced aligned access
See also
forceAlignedAccessIf(), class ForceAlignedAccess
{ return derived(); }
forceAlignedAccess() [2/2]
const ForceAlignedAccess< MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::forceAlignedAccess inline inherited
Returns
an expression of *this with forced aligned access
See also
forceAlignedAccessIf(),class ForceAlignedAccess
{ return derived(); }
forceAlignedAccessIf() [1/4]
internal::conditional< Enable, ForceAlignedAccess< MatrixWrapper< ExpressionType > >, MatrixWrapper< ExpressionType > & >::type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::forceAlignedAccessIf () inline inherited
Returns
an expression of *this with forced aligned access if Enable is true.
See also
forceAlignedAccess(), class ForceAlignedAccess
{
  return derived();  // FIXME This should not work but apparently is never used
}
forceAlignedAccessIf() [2/4]
MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::forceAlignedAccessIf () inline inherited
{ return derived(); }
forceAlignedAccessIf() [3/4]
internal::add_const_on_value_type< typenameinternal::conditional< Enable, ForceAlignedAccess< MatrixWrapper< ExpressionType > >, MatrixWrapper< ExpressionType > & >::type >::type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::forceAlignedAccessIf () const inline inherited
Returns
an expression of *this with forced aligned access if Enable is true.
See also
forceAlignedAccess(), class ForceAlignedAccess
{
  return derived();  // FIXME This should not work but apparently is never used
}
forceAlignedAccessIf() [4/4]
const MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::forceAlignedAccessIf () const inline inherited
{ return derived(); }
format()
template<typename Derived > const WithFormat< Derived > Eigen::DenseBase< Derived >::format (const IOFormat & fmt) const inline inherited
Returns
a WithFormat proxy object allowing to print a matrix the with given format fmt.
See class IOFormat for some examples.
See also
class IOFormat, class WithFormat
    {
      return WithFormat<Derived>(derived(), fmt);
    }
Referenced by igl::matlab_format(), and igl::writeOBJ().
fullPivHouseholderQr()
const FullPivHouseholderQR< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::fullPivHouseholderQr inline inherited
Returns
the full-pivoting Householder QR decomposition of *this.
See also
class FullPivHouseholderQR
{
  return FullPivHouseholderQR<PlainObject>(eval());
}
fullPivLu()
const FullPivLU< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::fullPivLu inline inherited
\lu_module
Returns
the full-pivoting LU decomposition of *this.
See also
class FullPivLU
{
  return FullPivLU<PlainObject>(eval());
}
hasNaN()
template<typename Derived > bool Eigen::DenseBase< Derived >::hasNaN inline inherited
Returns
true is *this contains at least one Not A Number (NaN).
See also
allFinite()
{
#if EIGEN_COMP_MSVC || (defined __FAST_MATH__)
  return derived().array().isNaN().any();
#else
  return !((derived().array()==derived().array()).all());
#endif
}
hnormalized()
EIGEN_DEVICE_FUNC const MatrixBase< MatrixWrapper< ExpressionType > >::HNormalizedReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::hnormalized inline inherited
homogeneous normalization
\geometry_module
Returns
a vector expression of the N-1 first coefficients of *this divided by that last coefficient.
This can be used to convert homogeneous coordinates to affine coordinates.
It is essentially a shortcut for:
this->head(this->size()-1)/this->coeff(this->size()-1);
Example:
Output:
See also
VectorwiseOp::hnormalized()
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
  return ConstStartMinusOne(derived(),0,0,
    ColsAtCompileTime==1?size()-1:1,
    ColsAtCompileTime==1?1:size()-1) / coeff(size()-1);
}
homogeneous()
EIGEN_DEVICE_FUNC MatrixBase< MatrixWrapper< ExpressionType > >::HomogeneousReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::homogeneous inline inherited
\geometry_module
Returns
a vector expression that is one longer than the vector argument, with the value 1 symbolically appended as the last coefficient.
This can be used to convert affine coordinates to homogeneous coordinates.
\only_for_vectors
Example:
Output:
See also
VectorwiseOp::homogeneous(), class Homogeneous
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
  return HomogeneousReturnType(derived());
}
householderQr()
const HouseholderQR< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::householderQr inline inherited
Returns
the Householder QR decomposition of *this.
See also
class HouseholderQR
{
  return HouseholderQR<PlainObject>(eval());
}
hypotNorm()
NumTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar >::Real Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::hypotNorm inline inherited
Returns
the l2 norm of *this avoiding undeflow and overflow. This version use a concatenation of hypot() calls, and it is very slow.
See also
norm(), stableNorm()
{
  return this->cwiseAbs().redux(internal::scalar_hypot_op<RealScalar>());
}
Identity() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::IdentityReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::Identity static inherited
Returns
an expression of the identity matrix (not necessarily square).
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variant taking size arguments.
Example:
Output:
See also
Identity(Index,Index), setIdentity(), isIdentity()
{
  EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
  return MatrixBase<Derived>::NullaryExpr(RowsAtCompileTime, ColsAtCompileTime, internal::scalar_identity_op<Scalar>());
}
Identity() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::IdentityReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::Identity (Index rows, Index cols) static inherited
Returns
an expression of the identity matrix (not necessarily square).
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Identity() should be used instead.
Example:
Output:
See also
Identity(), setIdentity(), isIdentity()
{
  return DenseBase<Derived>::NullaryExpr(rows, cols, internal::scalar_identity_op<Scalar>());
}
innerSize()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::innerSize () const inline inherited
Returns
the inner size.
Note
For a vector, this is just the size. For a matrix (non-vector), this is the minor dimension with respect to the storage order, i.e., the number of rows for a column-major matrix, and the number of columns for a row-major matrix.
    {
      return IsVectorAtCompileTime ? this->size()
           : int(IsRowMajor) ? this->cols() : this->rows();
    }
References Eigen::DenseBase< Derived >::IsRowMajor, and Eigen::DenseBase< Derived >::IsVectorAtCompileTime.
innerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::MatrixWrapper< ExpressionType >::innerStride () const inline
{ return m_expression.innerStride(); }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
inverse()
const Inverse< MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::inverse inline inherited
\lu_module
Returns
the matrix inverse of this matrix.
For small fixed sizes up to 4x4, this method uses cofactors. In the general case, this method uses class PartialPivLU.
Note
This matrix must be invertible, otherwise the result is undefined. If you need an invertibility check, do the following:
for fixed sizes up to 4x4, use computeInverseAndDetWithCheck().
for the general case, use class FullPivLU.
Example:
Output:
See also
computeInverseAndDetWithCheck()
{
  EIGEN_STATIC_ASSERT(!NumTraits<Scalar>::IsInteger,THIS_FUNCTION_IS_NOT_FOR_INTEGER_NUMERIC_TYPES)
  eigen_assert(rows() == cols());
  return Inverse<Derived>(derived());
}
isApprox() [1/2]
template<typename Derived > template<typename OtherDerived > bool Eigen::DenseBase< Derived >::isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec) const inherited
Returns
true if *this is approximately equal to other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. Two vectors and are considered to be approximately equal within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm (aka Frobenius norm L2 norm).
Because of the multiplicativeness of this comparison, one can't use this function to check whether *this is approximately equal to the zero matrix or vector. Indeed, isApprox(zero) returns false unless *this itself is exactly the zero matrix or vector. If you want to test whether *this is zero, use internal::isMuchSmallerThan(const RealScalar&, RealScalar) instead.
See also
internal::isMuchSmallerThan(const RealScalar&, RealScalar) const
{
  return internal::isApprox_selector<Derived, OtherDerived>::run(derived(), other.derived(), prec);
}
References Eigen::internal::isApprox_selector< Derived, OtherDerived, is_integer >::run().
isApprox() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const inherited
isApproxToConstant()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApproxToConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if all coefficients in this matrix are approximately equal to val, to within precision prec
{
  typename internal::nested_eval<Derived,1>::type self(derived());
  for(Index j = 0; j < cols(); ++j)
    for(Index i = 0; i < rows(); ++i)
      if(!internal::isApprox(self.coeff(i, j), val, prec))
        return false;
  return true;
}
References Eigen::internal::isApprox().
isConstant()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
This is just an alias for isApproxToConstant().
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
{
  return isApproxToConstant(val, prec);
}
isDiagonal()
bool Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::isDiagonal (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to a diagonal matrix, within the precision given by prec.
Example:
Output:
See also
asDiagonal()
{
  if(cols() != rows()) return false;
  RealScalar maxAbsOnDiagonal = static_cast<RealScalar>(-1);
  for(Index j = 0; j < cols(); ++j)
  {
    RealScalar absOnDiagonal = numext::abs(coeff(j,j));
    if(absOnDiagonal > maxAbsOnDiagonal) maxAbsOnDiagonal = absOnDiagonal;
  }
  for(Index j = 0; j < cols(); ++j)
    for(Index i = 0; i < j; ++i)
    {
      if(!internal::isMuchSmallerThan(coeff(i, j), maxAbsOnDiagonal, prec)) return false;
      if(!internal::isMuchSmallerThan(coeff(j, i), maxAbsOnDiagonal, prec)) return false;
    }
  return true;
}
isIdentity()
bool Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::isIdentity (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to the identity matrix (not necessarily square), within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Identity(), Identity(Index,Index), setIdentity()
{
  typename internal::nested_eval<Derived,1>::type self(derived());
  for(Index j = 0; j < cols(); ++j)
  {
    for(Index i = 0; i < rows(); ++i)
    {
      if(i == j)
      {
        if(!internal::isApprox(self.coeff(i, j), static_cast<Scalar>(1), prec))
          return false;
      }
      else
      {
        if(!internal::isMuchSmallerThan(self.coeff(i, j), static_cast<RealScalar>(1), prec))
          return false;
      }
    }
  }
  return true;
}
isLowerTriangular()
bool Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::isLowerTriangular (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to a lower triangular matrix, within the precision given by prec.
See also
isUpperTriangular()
{
  RealScalar maxAbsOnLowerPart = static_cast<RealScalar>(-1);
  for(Index j = 0; j < cols(); ++j)
    for(Index i = j; i < rows(); ++i)
    {
      RealScalar absValue = numext::abs(coeff(i,j));
      if(absValue > maxAbsOnLowerPart) maxAbsOnLowerPart = absValue;
    }
  RealScalar threshold = maxAbsOnLowerPart * prec;
  for(Index j = 1; j < cols(); ++j)
  {
    Index maxi = numext::mini(j, rows()-1);
    for(Index i = 0; i < maxi; ++i)
      if(numext::abs(coeff(i, j)) > threshold) return false;
  }
  return true;
}
isMuchSmallerThan() [1/4]
template<typename Derived > template<typename OtherDerived > bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec) const inherited
Returns
true if the norm of *this is much smaller than the norm of other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than a vector within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm.
See also
isApprox(), isMuchSmallerThan(const RealScalar&, RealScalar) const
{
  return internal::isMuchSmallerThan_object_selector<Derived, OtherDerived>::run(derived(), other.derived(), prec);
}
References Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >::run().
isMuchSmallerThan() [2/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const inherited
isMuchSmallerThan() [3/4]
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const RealScalar & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const inherited
isMuchSmallerThan() [4/4]
template<typename Derived > template<typename Derived > bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const typename NumTraits< Scalar >::Real & other, const RealScalar & prec) const inherited
Returns
true if the norm of *this is much smaller than other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm. For this reason, the value of the reference scalar other should come from the Hilbert-Schmidt norm of a reference matrix of same dimensions.
See also
isApprox(), isMuchSmallerThan(const DenseBase<OtherDerived>&, RealScalar) const
{
  return internal::isMuchSmallerThan_scalar_selector<Derived>::run(derived(), other, prec);
}
References Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >::run().
isOnes()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isOnes (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to the matrix where all coefficients are equal to 1, within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Ones()
{
  return isApproxToConstant(Scalar(1), prec);
}
isOrthogonal()
bool Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::isOrthogonal (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately orthogonal to other, within the precision given by prec.
Example:
Output:
{
  typename internal::nested_eval<Derived,2>::type nested(derived());
  typename internal::nested_eval<OtherDerived,2>::type otherNested(other.derived());
  return numext::abs2(nested.dot(otherNested)) <= prec * prec * nested.squaredNorm() * otherNested.squaredNorm();
}
isUnitary()
bool Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::isUnitary (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately an unitary matrix, within the precision given by prec. In the case where the Scalar type is real numbers, a unitary matrix is an orthogonal matrix, whence the name.
Note
This can be used to check whether a family of vectors forms an orthonormal basis. Indeed, m.isUnitary() returns true if and only if the columns (equivalently, the rows) of m form an orthonormal basis.
Example:
Output:
{
  typename internal::nested_eval<Derived,1>::type self(derived());
  for(Index i = 0; i < cols(); ++i)
  {
    if(!internal::isApprox(self.col(i).squaredNorm(), static_cast<RealScalar>(1), prec))
      return false;
    for(Index j = 0; j < i; ++j)
      if(!internal::isMuchSmallerThan(self.col(i).dot(self.col(j)), static_cast<Scalar>(1), prec))
        return false;
  }
  return true;
}
isUpperTriangular()
bool Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::isUpperTriangular (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to an upper triangular matrix, within the precision given by prec.
See also
isLowerTriangular()
{
  RealScalar maxAbsOnUpperPart = static_cast<RealScalar>(-1);
  for(Index j = 0; j < cols(); ++j)
  {
    Index maxi = numext::mini(j, rows()-1);
    for(Index i = 0; i <= maxi; ++i)
    {
      RealScalar absValue = numext::abs(coeff(i,j));
      if(absValue > maxAbsOnUpperPart) maxAbsOnUpperPart = absValue;
    }
  }
  RealScalar threshold = maxAbsOnUpperPart * prec;
  for(Index j = 0; j < cols(); ++j)
    for(Index i = j+1; i < rows(); ++i)
      if(numext::abs(coeff(i, j)) > threshold) return false;
  return true;
}
isZero()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isZero (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to the zero matrix, within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Zero()
{
  typename internal::nested_eval<Derived,1>::type self(derived());
  for(Index j = 0; j < cols(); ++j)
    for(Index i = 0; i < rows(); ++i)
      if(!internal::isMuchSmallerThan(self.coeff(i, j), static_cast<Scalar>(1), prec))
        return false;
  return true;
}
References Eigen::internal::isMuchSmallerThan().
jacobiSvd()
JacobiSVD< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::jacobiSvd (unsigned int computationOptions = 0) const inline inherited
\svd_module
Returns
the singular value decomposition of *this computed by two-sided Jacobi transformations.
See also
class JacobiSVD
{
  return JacobiSVD<PlainObject>(*this, computationOptions);
}
lazyAssign() [1/2]
EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & Eigen::DenseBase< MatrixWrapper< ExpressionType > >::lazyAssign (const DenseBase< OtherDerived > & other) inherited
{
  enum{
    SameType = internal::is_same<typename Derived::Scalar,typename OtherDerived::Scalar>::value
  };
  EIGEN_STATIC_ASSERT_LVALUE(Derived)
  EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT(SameType,YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(rows() == other.rows() && cols() == other.cols());
  internal::call_assignment_no_alias(derived(),other.derived());
  return derived();
}
lazyAssign() [2/2]
EIGEN_DEVICE_FUNC MatrixWrapper< ExpressionType > & Eigen::DenseBase< MatrixWrapper< ExpressionType > >::lazyAssign (const DenseBase< OtherDerived > & other) inherited
lazyProduct() [1/2]
const Product< MatrixWrapper< ExpressionType > , OtherDerived, LazyProduct > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::lazyProduct (const MatrixBase< OtherDerived > & other) const inherited
Returns
an expression of the matrix product of *this and other without implicit evaluation.
The returned product will behave like any other expressions: the coefficients of the product will be computed once at a time as requested. This might be useful in some extremely rare cases when only a small and no coherent fraction of the result's coefficients have to be computed.
Warning
This version of the matrix product can be much much slower. So use it only if you know what you are doing and that you measured a true speed improvement.
See also
operator*(const MatrixBase&)
{
  enum {
    ProductIsValid =  Derived::ColsAtCompileTime==Dynamic
                   || OtherDerived::RowsAtCompileTime==Dynamic
                   || int(Derived::ColsAtCompileTime)==int(OtherDerived::RowsAtCompileTime),
    AreVectors = Derived::IsVectorAtCompileTime && OtherDerived::IsVectorAtCompileTime,
    SameSizes = EIGEN_PREDICATE_SAME_MATRIX_SIZE(Derived,OtherDerived)
  };
  // note to the lost user:
  //    * for a dot product use: v1.dot(v2)
  //    * for a coeff-wise product use: v1.cwiseProduct(v2)
  EIGEN_STATIC_ASSERT(ProductIsValid || !(AreVectors && SameSizes),
    INVALID_VECTOR_VECTOR_PRODUCT__IF_YOU_WANTED_A_DOT_OR_COEFF_WISE_PRODUCT_YOU_MUST_USE_THE_EXPLICIT_FUNCTIONS)
  EIGEN_STATIC_ASSERT(ProductIsValid || !(SameSizes && !AreVectors),
    INVALID_MATRIX_PRODUCT__IF_YOU_WANTED_A_COEFF_WISE_PRODUCT_YOU_MUST_USE_THE_EXPLICIT_FUNCTION)
  EIGEN_STATIC_ASSERT(ProductIsValid || SameSizes, INVALID_MATRIX_PRODUCT)
  return Product<Derived,OtherDerived,LazyProduct>(derived(), other.derived());
}
lazyProduct() [2/2]
EIGEN_DEVICE_FUNC const Product< MatrixWrapper< ExpressionType > , OtherDerived, LazyProduct > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::lazyProduct (const MatrixBase< OtherDerived > & other) const inherited
ldlt()
const LDLT< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::ldlt inline inherited
\cholesky_module
Returns
the Cholesky decomposition with full pivoting without square root of *this
See also
SelfAdjointView::ldlt()
{
  return LDLT<PlainObject>(derived());
}
LinSpaced() [1/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (const Scalar & low, const Scalar & high) static inherited
Special version for fixed size types which does not require the size parameter.
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
  return DenseBase<Derived>::NullaryExpr(Derived::SizeAtCompileTime, internal::linspaced_op<Scalar,PacketScalar>(low,high,Derived::SizeAtCompileTime));
}
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
LinSpaced() [2/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Index size, const Scalar & low, const Scalar & high) static inherited
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
Example:
Output:
For integer scalar types, an even spacing is possible if and only if the length of the range, i.e., high-low is a scalar multiple of size-1, or if size is a scalar multiple of the number of values high-low+1 (meaning each value can be repeated the same number of time). If one of these two considions is not satisfied, then high is lowered to the largest value satisfying one of this constraint. Here are some examples:
Example:
Output:
See also
setLinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return DenseBase<Derived>::NullaryExpr(size, internal::linspaced_op<Scalar,PacketScalar>(low,high,size));
}
LinSpaced() [3/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , const Scalar & low, const Scalar & high) static inherited
See also
LinSpaced(Scalar,Scalar)
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
  return DenseBase<Derived>::NullaryExpr(Derived::SizeAtCompileTime, internal::linspaced_op<Scalar,PacketScalar>(low,high,Derived::SizeAtCompileTime));
}
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
LinSpaced() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , Index size, const Scalar & low, const Scalar & high) static inherited
See also
LinSpaced(Index,Scalar,Scalar), setLinSpaced(Index,const Scalar&,const Scalar&)
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return DenseBase<Derived>::NullaryExpr(size, internal::linspaced_op<Scalar,PacketScalar>(low,high,size));
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
llt()
const LLT< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::llt inline inherited
\cholesky_module
Returns
the LLT decomposition of *this
See also
SelfAdjointView::llt()
{
  return LLT<PlainObject>(derived());
}
lpNorm() [1/2]
NumTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar >::Real Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::lpNorm () const inline inherited
Returns
the coefficient-wise norm of *this, that is, returns the p-th root of the sum of the p-th powers of the absolute values of the coefficients of *this. If p is the special value Eigen::Infinity, this function returns the norm, that is the maximum of the absolute values of the coefficients of *this.
In all cases, if *this is empty, then the value 0 is returned.
Note
For matrices, this function does not compute the operator-norm. That is, if *this is a matrix, then its coefficients are interpreted as a 1D vector. Nonetheless, you can easily compute the 1-norm and -norm matrix operator norms using partial reductions .
See also
norm()
{
  return internal::lpNorm_selector<Derived, p>::run(*this);
}
lpNorm() [2/2]
EIGEN_DEVICE_FUNC RealScalar Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::lpNorm () const inherited
lu()
const PartialPivLU< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::lu inline inherited
\lu_module
Synonym of partialPivLu().
Returns
the partial-pivoting LU decomposition of *this.
See also
class PartialPivLU
{
  return PartialPivLU<PlainObject>(eval());
}
makeHouseholder()
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::makeHouseholder (EssentialPart & essential, Scalar & tau, RealScalar & beta) const inherited
Computes the elementary reflector H such that: where the transformation H is: and the vector v is:
On output:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
beta the result of H * *this
See also
MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheLeft(), MatrixBase::applyHouseholderOnTheRight()
{
  using std::sqrt;
  using numext::conj;
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(EssentialPart)
  VectorBlock<const Derived, EssentialPart::SizeAtCompileTime> tail(derived(), 1, size()-1);
  RealScalar tailSqNorm = size()==1 ? RealScalar(0) : tail.squaredNorm();
  Scalar c0 = coeff(0);
  const RealScalar tol = (std::numeric_limits<RealScalar>::min)();
  if(tailSqNorm <= tol && numext::abs2(numext::imag(c0))<=tol)
  {
    tau = RealScalar(0);
    beta = numext::real(c0);
    essential.setZero();
  }
  else
  {
    beta = sqrt(numext::abs2(c0) + tailSqNorm);
    if (numext::real(c0)>=RealScalar(0))
      beta = -beta;
    essential = tail / (c0 - beta);
    tau = conj((beta - c0) / beta);
  }
}
makeHouseholderInPlace()
void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::makeHouseholderInPlace (Scalar & tau, RealScalar & beta) inherited
Computes the elementary reflector H such that: where the transformation H is: and the vector v is:
The essential part of the vector v is stored in *this.
On output:
Parameters
tau the scaling factor of the Householder transformation
beta the result of H * *this
See also
MatrixBase::makeHouseholder(), MatrixBase::applyHouseholderOnTheLeft(), MatrixBase::applyHouseholderOnTheRight()
{
  VectorBlock<Derived, internal::decrement_size<Base::SizeAtCompileTime>::ret> essentialPart(derived(), 1, size()-1);
  makeHouseholder(essentialPart, tau, beta);
}
matrix() [1/2]
EIGEN_DEVICE_FUNC MatrixBase< MatrixWrapper< ExpressionType > > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::matrix () inline inherited
{ return *this; }
matrix() [2/2]
EIGEN_DEVICE_FUNC const MatrixBase< MatrixWrapper< ExpressionType > > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::matrix () const inline inherited
{ return *this; }
matrixFunction()
const MatrixFunctionReturnValue< MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::matrixFunction (StemFunction f) const inherited
Helper function for the unsupported MatrixFunctions module.
maxCoeff() [1/3]
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff inherited
Returns
the maximum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
{
  return derived().redux(Eigen::internal::scalar_max_op<Scalar,Scalar>());
}
Referenced by igl::copyleft::cgal::half_space_box(), igl::isolines(), igl::min_quad_with_fixed_precompute(), igl::octree(), Eigen::internal::lpNorm_selector< Derived, Infinity >::run(), and igl::slice().
maxCoeff() [2/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * index) const inherited
Returns
the maximum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  internal::max_coeff_visitor<Derived> maxVisitor;
  this->visit(maxVisitor);
  *index = (RowsAtCompileTime==1) ? maxVisitor.col : maxVisitor.row;
  return maxVisitor.res;
}
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
maxCoeff() [3/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * rowId, IndexType * colId) const inherited
Returns
the maximum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::maxCoeff()
{
  internal::max_coeff_visitor<Derived> maxVisitor;
  this->visit(maxVisitor);
  *rowPtr = maxVisitor.row;
  if (colPtr) *colPtr = maxVisitor.col;
  return maxVisitor.res;
}
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
mean()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::mean inherited
Returns
the mean of all coefficients of *this
See also
trace(), prod(), sum()
{
#ifdef __INTEL_COMPILER
  #pragma warning push
  #pragma warning ( disable : 2259 )
#endif
  return Scalar(derived().redux(Eigen::internal::scalar_sum_op<Scalar,Scalar>())) / Scalar(this->size());
#ifdef __INTEL_COMPILER
  #pragma warning pop
#endif
}
minCoeff() [1/3]
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff inherited
Returns
the minimum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
{
  return derived().redux(Eigen::internal::scalar_min_op<Scalar,Scalar>());
}
Referenced by igl::copyleft::cgal::half_space_box(), igl::isolines(), igl::min_quad_with_fixed_precompute(), igl::octree(), and igl::slice().
minCoeff() [2/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * index) const inherited
Returns
the minimum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::minCoeff()
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  internal::min_coeff_visitor<Derived> minVisitor;
  this->visit(minVisitor);
  *index = IndexType((RowsAtCompileTime==1) ? minVisitor.col : minVisitor.row);
  return minVisitor.res;
}
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
minCoeff() [3/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * rowId, IndexType * colId) const inherited
Returns
the minimum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(Index*), DenseBase::maxCoeff(Index*,Index*), DenseBase::visit(), DenseBase::minCoeff()
{
  internal::min_coeff_visitor<Derived> minVisitor;
  this->visit(minVisitor);
  *rowId = minVisitor.row;
  if (colId) *colId = minVisitor.col;
  return minVisitor.res;
}
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
nestByValue()
template<typename Derived > const NestByValue< Derived > Eigen::DenseBase< Derived >::nestByValue inline inherited
Returns
an expression of the temporary version of *this.
{
  return NestByValue<Derived>(derived());
}
nestedExpression()
template<typename ExpressionType > EIGEN_DEVICE_FUNC const internal::remove_all< NestedExpressionType >::type & Eigen::MatrixWrapper< ExpressionType >::nestedExpression () const inline
    {
      return m_expression;
    }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
noalias()
NoAlias< MatrixWrapper< ExpressionType > , MatrixBase > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::noalias inherited
Returns
a pseudo expression of *this with an operator= assuming no aliasing between *this and the source expression.
More precisely, noalias() allows to bypass the EvalBeforeAssignBit flag. Currently, even though several expressions may alias, only product expressions have this flag. Therefore, noalias() is only usefull when the source expression contains a matrix product.
Here are some examples where noalias is usefull:
D.noalias()  = A * B;
D.noalias() += A.transpose() * B;
D.noalias() -= 2 * A * B.adjoint();
On the other hand the following example will lead to a wrong result:
A.noalias() = A * B;
because the result matrix A is also an operand of the matrix product. Therefore, there is no alternative than evaluating A * B in a temporary, that is the default behavior when you write:
A = A * B;
See also
class NoAlias
{
  return NoAlias<Derived, Eigen::MatrixBase >(derived());
}
nonZeros()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::nonZeros () const inline inherited
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
{ return size(); }
norm()
EIGEN_STRONG_INLINE NumTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar >::Real Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::norm inherited
Returns
, for vectors, the l2 norm of *this, and for matrices the Frobenius norm. In both cases, it consists in the square root of the sum of the square of all the matrix entries. For vectors, this is also equals to the square root of the dot product of *this with itself.
See also
lpNorm(), dot(), squaredNorm()
{
  return numext::sqrt(squaredNorm());
}
normalize()
EIGEN_STRONG_INLINE void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::normalize inherited
Normalizes the vector, i.e. divides it by its own norm.
\only_for_vectors
Warning
If the input vector is too small (i.e., this->norm()==0), then *this is left unchanged.
See also
norm(), normalized()
{
  RealScalar z = squaredNorm();
  // NOTE: after extensive benchmarking, this conditional does not impact performance, at least on recent x86 CPU
  if(z>RealScalar(0))
    derived() /= numext::sqrt(z);
}
normalized()
EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::normalized inherited
Returns
an expression of the quotient of *this by its own norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then this function returns a copy of the input.
\only_for_vectors
See also
norm(), normalize()
{
  typedef typename internal::nested_eval<Derived,2>::type _Nested;
  _Nested n(derived());
  RealScalar z = n.squaredNorm();
  // NOTE: after extensive benchmarking, this conditional does not impact performance, at least on recent x86 CPU
  if(z>RealScalar(0))
    return n / numext::sqrt(z);
  else
    return n;
}
NullaryExpr() [1/6]
template<typename Derived > template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func) inherited
Returns
an expression of a matrix defined by a custom functor func
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  return CwiseNullaryOp<CustomNullaryOp, PlainObject>(RowsAtCompileTime, ColsAtCompileTime, func);
}
NullaryExpr() [2/6]
template<typename Derived > template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func) static inherited
NullaryExpr() [3/6]
template<typename Derived > template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) inherited
Returns
an expression of a matrix defined by a custom functor func
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  return CwiseNullaryOp<CustomNullaryOp, PlainObject>(rows, cols, func);
}
NullaryExpr() [4/6]
template<typename Derived > template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) static inherited
Referenced by Eigen::DenseBase< Derived >::Constant(), Eigen::DenseBase< Derived >::Constant(), Eigen::DenseBase< Derived >::Constant(), Eigen::MatrixBase< Derived >::Identity(), Eigen::MatrixBase< Derived >::Identity(), Eigen::DenseBase< Derived >::LinSpaced(), Eigen::DenseBase< Derived >::LinSpaced(), and Eigen::DenseBase< Derived >::LinSpaced().
NullaryExpr() [5/6]
template<typename Derived > template<typename CustomNullaryOp > EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func) inherited
Returns
an expression of a matrix defined by a custom functor func
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
Here is an example with C++11 random generators:
Output:
See also
class CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  if(RowsAtCompileTime == 1) return CwiseNullaryOp<CustomNullaryOp, PlainObject>(1, size, func);
  else return CwiseNullaryOp<CustomNullaryOp, PlainObject>(size, 1, func);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
NullaryExpr() [6/6]
template<typename Derived > template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func) static inherited
Ones() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones static inherited
Returns
an expression of a fixed-size matrix or vector where all coefficients equal one.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See also
Ones(Index), Ones(Index,Index), isOnes(), class Ones
{
  return Constant(Scalar(1));
}
Ones() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index rows, Index cols) static inherited
Returns
an expression of a matrix where all coefficients equal one.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Ones() should be used instead.
Example:
Output:
See also
Ones(), Ones(Index), isOnes(), class Ones
{
  return Constant(rows, cols, Scalar(1));
}
Ones() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index newSize) static inherited
Returns
an expression of a vector where all coefficients equal one.
The parameter newSize is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Ones() should be used instead.
Example:
Output:
See also
Ones(), Ones(Index,Index), isOnes(), class Ones
{
  return Constant(newSize, Scalar(1));
}
operator!=()
EIGEN_DEVICE_FUNC bool Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator!= (const MatrixBase< OtherDerived > & other) const inline inherited
Returns
true if at least one pair of coefficients of *this and other are not exactly equal to each other.
Warning
When using floating point scalar values you probably should rather use a fuzzy comparison such as isApprox()
See also
isApprox(), operator==
    { return cwiseNotEqual(other).any(); }
operator*() [1/4]
const Product< MatrixWrapper< ExpressionType > , DiagonalDerived, LazyProduct > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator* (const DiagonalBase< DiagonalDerived > & a_diagonal) const inline inherited
Returns
the diagonal matrix product of *this by the diagonal matrix diagonal.
{
  return Product<Derived, DiagonalDerived, LazyProduct>(derived(),a_diagonal.derived());
}
operator*() [2/4]
EIGEN_DEVICE_FUNC const Product< MatrixWrapper< ExpressionType > , DiagonalDerived, LazyProduct > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator* (const DiagonalBase< DiagonalDerived > & diagonal) const inherited
operator*() [3/4]
const Product< MatrixWrapper< ExpressionType > , OtherDerived > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator* (const MatrixBase< OtherDerived > & other) const inline inherited
Returns
the matrix product of *this and other.
Note
If instead of the matrix product you want the coefficient-wise product, see Cwise::operator*().
See also
lazyProduct(), operator*=(const MatrixBase&), Cwise::operator*()
{
  // A note regarding the function declaration: In MSVC, this function will sometimes
  // not be inlined since DenseStorage is an unwindable object for dynamic
  // matrices and product types are holding a member to store the result.
  // Thus it does not help tagging this function with EIGEN_STRONG_INLINE.
  enum {
    ProductIsValid =  Derived::ColsAtCompileTime==Dynamic
                   || OtherDerived::RowsAtCompileTime==Dynamic
                   || int(Derived::ColsAtCompileTime)==int(OtherDerived::RowsAtCompileTime),
    AreVectors = Derived::IsVectorAtCompileTime && OtherDerived::IsVectorAtCompileTime,
    SameSizes = EIGEN_PREDICATE_SAME_MATRIX_SIZE(Derived,OtherDerived)
  };
  // note to the lost user:
  //    * for a dot product use: v1.dot(v2)
  //    * for a coeff-wise product use: v1.cwiseProduct(v2)
  EIGEN_STATIC_ASSERT(ProductIsValid || !(AreVectors && SameSizes),
    INVALID_VECTOR_VECTOR_PRODUCT__IF_YOU_WANTED_A_DOT_OR_COEFF_WISE_PRODUCT_YOU_MUST_USE_THE_EXPLICIT_FUNCTIONS)
  EIGEN_STATIC_ASSERT(ProductIsValid || !(SameSizes && !AreVectors),
    INVALID_MATRIX_PRODUCT__IF_YOU_WANTED_A_COEFF_WISE_PRODUCT_YOU_MUST_USE_THE_EXPLICIT_FUNCTION)
  EIGEN_STATIC_ASSERT(ProductIsValid || SameSizes, INVALID_MATRIX_PRODUCT)
#ifdef EIGEN_DEBUG_PRODUCT
  internal::product_type<Derived,OtherDerived>::debug();
#endif
  return Product<Derived, OtherDerived>(derived(), other.derived());
}
operator*() [4/4]
EIGEN_DEVICE_FUNC const Product< MatrixWrapper< ExpressionType > , OtherDerived > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator* (const MatrixBase< OtherDerived > & other) const inherited
operator*=() [1/2]
MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator*= (const EigenBase< OtherDerived > & other) inline inherited
replaces *this by *this * other.
Returns
a reference to *this
Example:
Output:
{
  other.derived().applyThisOnTheRight(derived());
  return derived();
}
operator*=() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & Eigen::DenseBase< MatrixWrapper< ExpressionType > >::operator*= (const Scalar & other) inherited
{
  internal::call_assignment(this->derived(), PlainObject::Constant(rows(),cols(),other), internal::mul_assign_op<Scalar,Scalar>());
  return derived();
}
operator+=() [1/4]
MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator+= (const ArrayBase< OtherDerived > &) inline protected inherited
    {EIGEN_STATIC_ASSERT(std::ptrdiff_t(sizeof(typename OtherDerived::Scalar))==-1,YOU_CANNOT_MIX_ARRAYS_AND_MATRICES); return *this;}
operator+=() [2/4]
EIGEN_DEVICE_FUNC MatrixWrapper< ExpressionType > & Eigen::DenseBase< MatrixWrapper< ExpressionType > >::operator+= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [3/4]
EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator+= (const MatrixBase< OtherDerived > & other) inherited
replaces *this by *this + other.
Returns
a reference to *this
{
  call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [4/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator+= (const MatrixBase< OtherDerived > & other) inherited
operator-=() [1/4]
MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator-= (const ArrayBase< OtherDerived > &) inline protected inherited
    {EIGEN_STATIC_ASSERT(std::ptrdiff_t(sizeof(typename OtherDerived::Scalar))==-1,YOU_CANNOT_MIX_ARRAYS_AND_MATRICES); return *this;}
operator-=() [2/4]
EIGEN_DEVICE_FUNC MatrixWrapper< ExpressionType > & Eigen::DenseBase< MatrixWrapper< ExpressionType > >::operator-= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::sub_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [3/4]
EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator-= (const MatrixBase< OtherDerived > & other) inherited
replaces *this by *this - other.
Returns
a reference to *this
{
  call_assignment(derived(), other.derived(), internal::sub_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [4/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator-= (const MatrixBase< OtherDerived > & other) inherited
operator/=()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & Eigen::DenseBase< MatrixWrapper< ExpressionType > >::operator/= (const Scalar & other) inherited
{
  internal::call_assignment(this->derived(), PlainObject::Constant(rows(),cols(),other), internal::div_assign_op<Scalar,Scalar>());
  return derived();
}
operator<<() [1/3]
template<typename Derived > template<typename OtherDerived > CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const DenseBase< OtherDerived > & other) inline inherited
See also
operator<<(const Scalar&)
{
  return CommaInitializer<Derived>(*static_cast<Derived *>(this), other);
}
operator<<() [2/3]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const DenseBase< OtherDerived > & other) inherited
operator<<() [3/3]
template<typename Derived > CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const Scalar & s) inline inherited
Convenient operator to set the coefficients of a matrix.
The coefficients must be provided in a row major order and exactly match the size of the matrix. Otherwise an assertion is raised.
Example:
Output:
Note
According the c++ standard, the argument expressions of this comma initializer are evaluated in arbitrary order.
See also
CommaInitializer::finished(), class CommaInitializer
{
  return CommaInitializer<Derived>(*static_cast<Derived*>(this), s);
}
operator==()
EIGEN_DEVICE_FUNC bool Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operator== (const MatrixBase< OtherDerived > & other) const inline inherited
Returns
true if each coefficients of *this and other are all exactly equal.
Warning
When using floating point scalar values you probably should rather use a fuzzy comparison such as isApprox()
See also
isApprox(), operator!=
    { return cwiseEqual(other).all(); }
operatorNorm()
MatrixBase< MatrixWrapper< ExpressionType > >::RealScalar Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::operatorNorm inline inherited
Computes the L2 operator norm.
Returns
Operator norm of the matrix.
\eigenvalues_module This function computes the L2 operator norm of a matrix, which is also known as the spectral norm. The norm of a matrix is defined to be
where the maximum is over all vectors and the norm on the right is the Euclidean vector norm. The norm equals the largest singular value, which is the square root of the largest eigenvalue of the positive semi-definite matrix .
The current implementation uses the eigenvalues of , as computed by SelfAdjointView::eigenvalues(), to compute the operator norm of a matrix. The SelfAdjointView class provides a better algorithm for selfadjoint matrices.
Example:
Output:
See also
SelfAdjointView::eigenvalues(), SelfAdjointView::operatorNorm()
{
  using std::sqrt;
  typename Derived::PlainObject m_eval(derived());
  // FIXME if it is really guaranteed that the eigenvalues are already sorted,
  // then we don't need to compute a maxCoeff() here, comparing the 1st and last ones is enough.
  return sqrt((m_eval*m_eval.adjoint())
                 .eval()
     .template selfadjointView<Lower>()
     .eigenvalues()
     .maxCoeff()
     );
}
outerSize()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::outerSize () const inline inherited
Returns
the outer size.
Note
For a vector, this returns just 1. For a matrix (non-vector), this is the major dimension with respect to the storage order, i.e., the number of columns for a column-major matrix, and the number of rows for a row-major matrix.
    {
      return IsVectorAtCompileTime ? 1
           : int(IsRowMajor) ? this->rows() : this->cols();
    }
References Eigen::DenseBase< Derived >::IsRowMajor, and Eigen::DenseBase< Derived >::IsVectorAtCompileTime.
outerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::MatrixWrapper< ExpressionType >::outerStride () const inline
{ return m_expression.outerStride(); }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
partialPivLu()
const PartialPivLU< typename MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::partialPivLu inline inherited
\lu_module
Returns
the partial-pivoting LU decomposition of *this.
See also
class PartialPivLU
{
  return PartialPivLU<PlainObject>(eval());
}
prod()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::prod inherited
Returns
the product of all coefficients of *this
Example:
Output:
See also
sum(), mean(), trace()
{
  if(SizeAtCompileTime==0 || (SizeAtCompileTime==Dynamic && size()==0))
    return Scalar(1);
  return derived().redux(Eigen::internal::scalar_product_op<Scalar>());
}
References Eigen::Dynamic.
Random() [1/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random inline static inherited
Returns
a fixed-size random matrix or vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
\not_reentrant
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random(Index)
{
  return NullaryExpr(RowsAtCompileTime, ColsAtCompileTime, internal::scalar_random_op<Scalar>());
}
Random() [2/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index rows, Index cols) inline static inherited
Returns
a random matrix expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
\not_reentrant
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See DenseBase::NullaryExpr(Index, const CustomNullaryOp&) for an example using C++11 random generators.
See also
DenseBase::setRandom(), DenseBase::Random(Index), DenseBase::Random()
{
  return NullaryExpr(rows, cols, internal::scalar_random_op<Scalar>());
}
Random() [3/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index size) inline static inherited
Returns
a random vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors \not_reentrant
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary vector whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random()
{
  return NullaryExpr(size, internal::scalar_random_op<Scalar>());
}
redux() [1/2]
template<typename Derived > template<typename BinaryOp > EIGEN_DEVICE_FUNC Scalar Eigen::DenseBase< Derived >::redux (const BinaryOp & func) const inherited
Referenced by Eigen::internal::member_redux< BinaryOp, Scalar >::operator()().
redux() [2/2]
template<typename Derived > template<typename Func > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::redux (const Func & func) const inherited
Returns
the result of a full redux operation on the whole matrix or vector using func
The template parameter BinaryOp is the type of the functor func which must be an associative operator. Both current C++98 and C++11 functor styles are handled.
See also
DenseBase::sum(), DenseBase::minCoeff(), DenseBase::maxCoeff(), MatrixBase::colwise(), MatrixBase::rowwise()
{
  eigen_assert(this->rows()>0 && this->cols()>0 && "you are using an empty matrix");
  typedef typename internal::redux_evaluator<Derived> ThisEvaluator;
  ThisEvaluator thisEval(derived());
  return internal::redux_impl<Func, ThisEvaluator>::run(thisEval, func);
}
References eigen_assert.
replicate() [1/3]
template<typename Derived > template<int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > Eigen::DenseBase< Derived >::replicate () const inherited
Referenced by igl::min_quad_with_fixed_solve().
replicate() [2/3]
template<typename Derived > template<int RowFactor, int ColFactor> const Replicate< Derived, RowFactor, ColFactor > Eigen::DenseBase< Derived >::replicate () const inherited
Returns
an expression of the replication of *this
Example:
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate(Index,Index), class Replicate
{
  return Replicate<Derived,RowFactor,ColFactor>(derived());
}
replicate() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > Eigen::DenseBase< Derived >::replicate (Index rowFactor, Index colFactor) const inline inherited
Returns
an expression of the replication of *this
Example:
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate<int,int>(), class Replicate
    {
      return Replicate<Derived, Dynamic, Dynamic>(derived(), rowFactor, colFactor);
    }
resize() [1/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC void Eigen::MatrixWrapper< ExpressionType >::resize (Index newSize) inline
Forwards the resizing request to the nested expression
See also
DenseBase::resize(Index)
{ m_expression.resize(newSize); }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
resize() [2/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC void Eigen::MatrixWrapper< ExpressionType >::resize (Index rows, Index cols) inline
Forwards the resizing request to the nested expression
See also
DenseBase::resize(Index,Index)
{ m_expression.resize(rows,cols); }
References Eigen::MatrixWrapper< ExpressionType >::cols(), Eigen::MatrixWrapper< ExpressionType >::m_expression, and Eigen::MatrixWrapper< ExpressionType >::rows().
reverse() [1/2]
template<typename Derived > DenseBase< Derived >::ReverseReturnType Eigen::DenseBase< Derived >::reverse inline inherited
Returns
an expression of the reverse of *this.
Example:
Output:
{
  return ReverseReturnType(derived());
}
reverse() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ConstReverseReturnType Eigen::DenseBase< Derived >::reverse () const inline inherited
This is the const version of reverse().
    {
      return ConstReverseReturnType(derived());
    }
reverseInPlace()
template<typename Derived > void Eigen::DenseBase< Derived >::reverseInPlace inline inherited
This is the "in place" version of reverse: it reverses *this.
In most cases it is probably better to simply use the reversed expression of a matrix. However, when reversing the matrix data itself is really needed, then this "in-place" version is probably the right choice because it provides the following additional benefits:
less error prone: doing the same operation with .reverse() requires special care:
m = m.reverse().eval();
this API enables reverse operations without the need for a temporary
it allows future optimizations (cache friendliness, etc.)
See also
VectorwiseOp::reverseInPlace(), reverse()
{
  if(cols()>rows())
  {
    Index half = cols()/2;
    leftCols(half).swap(rightCols(half).reverse());
    if((cols()%2)==1)
    {
      Index half2 = rows()/2;
      col(half).head(half2).swap(col(half).tail(half2).reverse());
    }
  }
  else
  {
    Index half = rows()/2;
    topRows(half).swap(bottomRows(half).reverse());
    if((rows()%2)==1)
    {
      Index half2 = cols()/2;
      row(half).head(half2).swap(row(half).tail(half2).reverse());
    }
  }
}
References bottomRows(), col(), leftCols(), rightCols(), row(), tail(), and topRows().
rows()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::MatrixWrapper< ExpressionType >::rows () const inline
{ return m_expression.rows(); }
References Eigen::MatrixWrapper< ExpressionType >::m_expression.
Referenced by Eigen::MatrixWrapper< ExpressionType >::resize().
rowwise() [1/2]
template<typename Derived > DenseBase< Derived >::RowwiseReturnType Eigen::DenseBase< Derived >::rowwise inline inherited
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
  return RowwiseReturnType(derived());
}
rowwise() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ConstRowwiseReturnType Eigen::DenseBase< Derived >::rowwise () const inline inherited
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
      return ConstRowwiseReturnType(derived());
    }
Referenced by igl::normalize_row_sums(), and Eigen::umeyama().
select() [1/3]
template<typename Derived > template<typename ThenDerived , typename ElseDerived > const Select< Derived, ThenDerived, ElseDerived > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline inherited
Returns
a matrix where each coefficient (i,j) is equal to thenMatrix(i,j) if *this(i,j), and elseMatrix(i,j) otherwise.
Example:
Output:
See also
class Select
{
  return Select<Derived,ThenDerived,ElseDerived>(derived(), thenMatrix.derived(), elseMatrix.derived());
}
select() [2/3]
template<typename Derived > template<typename ThenDerived > const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const typename ThenDerived::Scalar & elseScalar) const inline inherited
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the else expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
{
  return Select<Derived,ThenDerived,typename ThenDerived::ConstantReturnType>(
    derived(), thenMatrix.derived(), ThenDerived::Constant(rows(),cols(),elseScalar));
}
select() [3/3]
template<typename Derived > template<typename ElseDerived > const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > Eigen::DenseBase< Derived >::select (const typename ElseDerived::Scalar & thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline inherited
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the then expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
{
  return Select<Derived,typename ElseDerived::ConstantReturnType,ElseDerived>(
    derived(), ElseDerived::Constant(rows(),cols(),thenScalar), elseMatrix.derived());
}
selfadjointView() [1/4]
EIGEN_DEVICE_FUNC SelfAdjointViewReturnType< UpLo >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::selfadjointView () inherited
selfadjointView() [2/4]
MatrixBase< MatrixWrapper< ExpressionType > >::template SelfAdjointViewReturnType< UpLo >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::selfadjointView () inherited
Returns
an expression of a symmetric/self-adjoint view extracted from the upper or lower triangular part of the current matrix
The parameter UpLo can be either Upper or Lower
Example:
Output:
See also
class SelfAdjointView
{
  return typename SelfAdjointViewReturnType<UpLo>::Type(derived());
}
selfadjointView() [3/4]
EIGEN_DEVICE_FUNC ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::selfadjointView () const inherited
selfadjointView() [4/4]
MatrixBase< MatrixWrapper< ExpressionType > >::template ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::selfadjointView () const inherited
This is the const version of MatrixBase::selfadjointView()
{
  return typename ConstSelfAdjointViewReturnType<UpLo>::Type(derived());
}
setConstant()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setConstant (const Scalar & val) inherited
Sets all coefficients in this expression to value val.
See also
fill(), setConstant(Index,const Scalar&), setConstant(Index,Index,const Scalar&), setZero(), setOnes(), Constant(), class CwiseNullaryOp, setZero(), setOnes()
{
  return derived() = Constant(rows(), cols(), val);
}
Referenced by Eigen::ArrayBase< Derived >::operator=().
setIdentity() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::setIdentity inherited
Writes the identity expression (not necessarily square) into *this.
Example:
Output:
See also
class CwiseNullaryOp, Identity(), Identity(Index,Index), isIdentity()
{
  return internal::setIdentity_impl<Derived>::run(derived());
}
setIdentity() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE MatrixWrapper< ExpressionType > & Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::setIdentity (Index rows, Index cols) inherited
Resizes to the given size, and writes the identity expression (not necessarily square) into *this.
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See also
MatrixBase::setIdentity(), class CwiseNullaryOp, MatrixBase::Identity()
{
  derived().resize(rows, cols);
  return setIdentity();
}
setLinSpaced() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (const Scalar & low, const Scalar & high) inherited
Sets a linearly spaced vector.
The function fills *this with equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), setLinSpaced(Index, const Scalar&, const Scalar&), CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return setLinSpaced(size(), low, high);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
setLinSpaced() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (Index newSize, const Scalar & low, const Scalar & high) inherited
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
Example:
Output:
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return derived() = Derived::NullaryExpr(newSize, internal::linspaced_op<Scalar,PacketScalar>(low,high,newSize));
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
setOnes()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setOnes inherited
Sets all coefficients in this expression to one.
Example:
Output:
See also
class CwiseNullaryOp, Ones()
{
  return setConstant(Scalar(1));
}
setRandom()
template<typename Derived > Derived & Eigen::DenseBase< Derived >::setRandom inline inherited
Sets all coefficients in this expression to random values.
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
\not_reentrant
Example:
Output:
See also
class CwiseNullaryOp, setRandom(Index), setRandom(Index,Index)
{
  return *this = Random(rows(), cols());
}
setZero()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setZero inherited
Sets all coefficients in this expression to zero.
Example:
Output:
See also
class CwiseNullaryOp, Zero()
{
  return setConstant(Scalar(0));
}
Referenced by Eigen::SPQR< _MatrixType >::_solve_impl(), Eigen::PermutationBase< Derived >::evalTo(), and Eigen::InverseImpl< PermutationType, PermutationStorage >::evalTo().
sparseView()
const SparseView< MatrixWrapper< ExpressionType > > Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::sparseView (const Scalar & reference = Scalar(0), const typename NumTraits< Scalar >::Real & epsilon = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
a sparse expression of the dense expression *this with values smaller than reference * epsilon removed.
This method is typically used when prototyping to convert a quickly assembled dense Matrix D to a SparseMatrix S:
MatrixXd D(n,m);
SparseMatrix<double> S;
S = D.sparseView();             // suppress numerical zeros (exact)
S = D.sparseView(reference);
S = D.sparseView(reference,epsilon);
where reference is a meaningful non zero reference value, and epsilon is a tolerance factor defaulting to NumTraits<Scalar>::dummy_precision().
See also
SparseMatrixBase::pruned(), class SparseView
{
  return SparseView<Derived>(derived(), reference, epsilon);
}
squaredNorm()
EIGEN_STRONG_INLINE NumTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar >::Real Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::squaredNorm inherited
Returns
, for vectors, the squared l2 norm of *this, and for matrices the Frobenius norm. In both cases, it consists in the sum of the square of all the matrix entries. For vectors, this is also equals to the dot product of *this with itself.
See also
dot(), norm(), lpNorm()
{
  return numext::real((*this).cwiseAbs2().sum());
}
stableNorm()
NumTraits< typenameinternal::traits< MatrixWrapper< ExpressionType > >::Scalar >::Real Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::stableNorm inline inherited
Returns
the l2 norm of *this avoiding underflow and overflow. This version use a blockwise two passes algorithm: 1 - find the absolute largest coefficient s 2 - compute in a standard way
For architecture/scalar types supporting vectorization, this version is faster than blueNorm(). Otherwise the blueNorm() is much faster.
See also
norm(), blueNorm(), hypotNorm()
{
  using std::sqrt;
  using std::abs;
  const Index blockSize = 4096;
  RealScalar scale(0);
  RealScalar invScale(1);
  RealScalar ssq(0); // sum of square
  typedef typename internal::nested_eval<Derived,2>::type DerivedCopy;
  typedef typename internal::remove_all<DerivedCopy>::type DerivedCopyClean;
  const DerivedCopy copy(derived());
  enum {
    CanAlign = (   (int(DerivedCopyClean::Flags)&DirectAccessBit)
                || (int(internal::evaluator<DerivedCopyClean>::Alignment)>0) // FIXME Alignment)>0 might not be enough
               ) && (blockSize*sizeof(Scalar)*2<EIGEN_STACK_ALLOCATION_LIMIT)
                 && (EIGEN_MAX_STATIC_ALIGN_BYTES>0) // if we cannot allocate on the stack, then let's not bother about this optimization
  };
  typedef typename internal::conditional<CanAlign, Ref<const Matrix<Scalar,Dynamic,1,0,blockSize,1>, internal::evaluator<DerivedCopyClean>::Alignment>,
                                                   typename DerivedCopyClean::ConstSegmentReturnType>::type SegmentWrapper;
  Index n = size();
  if(n==1)
    return abs(this->coeff(0));
  Index bi = internal::first_default_aligned(copy);
  if (bi>0)
    internal::stable_norm_kernel(copy.head(bi), ssq, scale, invScale);
  for (; bi<n; bi+=blockSize)
    internal::stable_norm_kernel(SegmentWrapper(copy.segment(bi,numext::mini(blockSize, n - bi))), ssq, scale, invScale);
  return scale * sqrt(ssq);
}
stableNormalize()
EIGEN_STRONG_INLINE void Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::stableNormalize inherited
Normalizes the vector while avoid underflow and overflow
\only_for_vectors
This method is analogue to the normalize() method, but it reduces the risk of underflow and overflow when computing the norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then *this is left unchanged.
See also
stableNorm(), stableNormalized(), normalize()
{
  RealScalar w = cwiseAbs().maxCoeff();
  RealScalar z = (derived()/w).squaredNorm();
  if(z>RealScalar(0))
    derived() /= numext::sqrt(z)*w;
}
stableNormalized()
EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::stableNormalized inherited
Returns
an expression of the quotient of *this by its own norm while avoiding underflow and overflow.
\only_for_vectors
This method is analogue to the normalized() method, but it reduces the risk of underflow and overflow when computing the norm.
Warning
If the input vector is too small (i.e., this->norm()==0), then this function returns a copy of the input.
See also
stableNorm(), stableNormalize(), normalized()
{
  typedef typename internal::nested_eval<Derived,3>::type _Nested;
  _Nested n(derived());
  RealScalar w = n.cwiseAbs().maxCoeff();
  RealScalar z = (n/w).squaredNorm();
  if(z>RealScalar(0))
    return n / (numext::sqrt(z)*w);
  else
    return n;
}
sum()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::sum inherited
Returns
the sum of all coefficients of *this
If *this is empty, then the value 0 is returned.
See also
trace(), prod(), mean()
{
  if(SizeAtCompileTime==0 || (SizeAtCompileTime==Dynamic && size()==0))
    return Scalar(0);
  return derived().redux(Eigen::internal::scalar_sum_op<Scalar,Scalar>());
}
References Eigen::Dynamic.
Referenced by igl::normalize_row_sums(), and Eigen::internal::lpNorm_selector< Derived, 1 >::run().
swap() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::swap (const DenseBase< OtherDerived > & other) inline inherited
swaps *this with the expression other.
    {
      EIGEN_STATIC_ASSERT(!OtherDerived::IsPlainObjectBase,THIS_EXPRESSION_IS_NOT_A_LVALUE__IT_IS_READ_ONLY);
      eigen_assert(rows()==other.rows() && cols()==other.cols());
      call_assignment(derived(), other.const_cast_derived(), internal::swap_assign_op<Scalar>());
    }
References eigen_assert, and EIGEN_STATIC_ASSERT.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run(), and Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
swap() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::swap (PlainObjectBase< OtherDerived > & other) inline inherited
swaps *this with the matrix or array other.
    {
      eigen_assert(rows()==other.rows() && cols()==other.cols());
      call_assignment(derived(), other.derived(), internal::swap_assign_op<Scalar>());
    }
References Eigen::PlainObjectBase< Derived >::cols(), eigen_assert, and Eigen::PlainObjectBase< Derived >::rows().
trace()
EIGEN_STRONG_INLINE internal::traits< MatrixWrapper< ExpressionType > >::Scalar Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::trace inherited
Returns
the trace of *this, i.e. the sum of the coefficients on the main diagonal.
*this can be any matrix, not necessarily square.
See also
diagonal(), sum()
{
  return derived().diagonal().sum();
}
transpose() [1/2]
template<typename Derived > Transpose< Derived > Eigen::DenseBase< Derived >::transpose inline inherited
Returns
an expression of the transpose of *this.
Example:
Output:
Warning
If you want to replace a matrix by its own transpose, do NOT do this:
m = m.transpose(); // bug!!! caused by aliasing effect
Instead, use the transposeInPlace() method:
m.transposeInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.transpose().eval();
See also
transposeInPlace(), adjoint()
{
  return TransposeReturnType(derived());
}
Referenced by igl::AABB< DerivedV, DIM >::find(), igl::AABB< DerivedV, DIM >::init(), igl::project(), igl::signed_distance_winding_number(), and igl::unproject().
transpose() [2/2]
template<typename Derived > DenseBase< Derived >::ConstTransposeReturnType Eigen::DenseBase< Derived >::transpose inline inherited
This is the const version of transpose().
Make sure you read the warning for transpose() !
See also
transposeInPlace(), adjoint()
{
  return ConstTransposeReturnType(derived());
}
transposeInPlace()
template<typename Derived > void Eigen::DenseBase< Derived >::transposeInPlace inline inherited
This is the "in place" version of transpose(): it replaces *this by its own transpose. Thus, doing
m.transposeInPlace();
has the same effect on m as doing
m = m.transpose().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own transpose. If you just need the transpose of a matrix, use transpose().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See also
transpose(), adjoint(), adjointInPlace()
{
  eigen_assert((rows() == cols() || (RowsAtCompileTime == Dynamic && ColsAtCompileTime == Dynamic))
               && "transposeInPlace() called on a non-square non-resizable matrix");
  internal::inplace_transpose_selector<Derived>::run(derived());
}
References Eigen::Dynamic, and eigen_assert.
triangularView() [1/4]
EIGEN_DEVICE_FUNC TriangularViewReturnType< Mode >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::triangularView () inherited
triangularView() [2/4]
MatrixBase< MatrixWrapper< ExpressionType > >::template TriangularViewReturnType< Mode >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::triangularView () inherited
Returns
an expression of a triangular view extracted from the current matrix
The parameter Mode can have the following values: Upper, StrictlyUpper, UnitUpper, Lower, StrictlyLower, UnitLower.
Example:
Output:
See also
class TriangularView
{
  return typename TriangularViewReturnType<Mode>::Type(derived());
}
triangularView() [3/4]
EIGEN_DEVICE_FUNC ConstTriangularViewReturnType< Mode >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::triangularView () const inherited
triangularView() [4/4]
MatrixBase< MatrixWrapper< ExpressionType > >::template ConstTriangularViewReturnType< Mode >::Type Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::triangularView () const inherited
This is the const version of MatrixBase::triangularView()
{
  return typename ConstTriangularViewReturnType<Mode>::Type(derived());
}
Unit() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::BasisReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::Unit (Index i) static inherited
Returns
an expression of the i-th unit (basis) vector.
\only_for_vectors
This variant is for fixed-size vector only.
See also
MatrixBase::Unit(Index,Index), MatrixBase::UnitX(), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return BasisReturnType(SquareMatrixType::Identity(),i);
}
Unit() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::BasisReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::Unit (Index newSize, Index i) static inherited
Returns
an expression of the i-th unit (basis) vector.
\only_for_vectors
See also
MatrixBase::Unit(Index), MatrixBase::UnitX(), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return BasisReturnType(SquareMatrixType::Identity(newSize,newSize), i);
}
unitOrthogonal()
EIGEN_DEVICE_FUNC MatrixBase< MatrixWrapper< ExpressionType > >::PlainObject Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::unitOrthogonal (void) const inline inherited
\geometry_module
Returns
a unit vector which is orthogonal to *this
The size of *this must be at least 2. If the size is exactly 2, then the returned vector is a counter clock wise rotation of *this, i.e., (-y,x).normalized().
See also
cross()
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return internal::unitOrthogonal_selector<Derived>::run(derived());
}
UnitW()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::BasisReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::UnitW static inherited
Returns
an expression of the W axis unit vector (0,0,0,1)
\only_for_vectors
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{ return Derived::Unit(3); }
UnitX()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::BasisReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::UnitX static inherited
Returns
an expression of the X axis unit vector (1{,0}^*)
\only_for_vectors
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{ return Derived::Unit(0); }
UnitY()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::BasisReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::UnitY static inherited
Returns
an expression of the Y axis unit vector (0,1{,0}^*)
\only_for_vectors
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{ return Derived::Unit(1); }
UnitZ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const MatrixBase< MatrixWrapper< ExpressionType > >::BasisReturnType Eigen::MatrixBase< MatrixWrapper< ExpressionType > >::UnitZ static inherited
Returns
an expression of the Z axis unit vector (0,0,1{,0}^*)
\only_for_vectors
See also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
{ return Derived::Unit(2); }
value()
template<typename Derived > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::DenseBase< Derived >::value () const inline inherited
Returns
the unique coefficient of a 1x1 expression
    {
      EIGEN_STATIC_ASSERT_SIZE_1x1(Derived)
      eigen_assert(this->rows() == 1 && this->cols() == 1);
      return derived().coeff(0,0);
    }
References eigen_assert, and EIGEN_STATIC_ASSERT_SIZE_1x1.
Referenced by igl::find(), and Eigen::ArrayBase< Derived >::operator=().
visit()
template<typename Derived > template<typename Visitor > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::visit (Visitor & visitor) const inherited
Applies the visitor visitor to the whole coefficients of the matrix or vector.
The template parameter Visitor is the type of the visitor and provides the following interface:
struct MyVisitor {
  // called for the first coefficient
  void init(const Scalar& value, Index i, Index j);
  // called for all other coefficients
  void operator() (const Scalar& value, Index i, Index j);
};
Note
compared to one or two for loops, visitors offer automatic unrolling for small fixed size matrix.
See also
minCoeff(Index*,Index*), maxCoeff(Index*,Index*), DenseBase::redux()
{
  typedef typename internal::visitor_evaluator<Derived> ThisEvaluator;
  ThisEvaluator thisEval(derived());
  enum {
    unroll =  SizeAtCompileTime != Dynamic
           && SizeAtCompileTime * ThisEvaluator::CoeffReadCost + (SizeAtCompileTime-1) * internal::functor_traits<Visitor>::Cost <= EIGEN_UNROLLING_LIMIT
  };
  return internal::visitor_impl<Visitor, ThisEvaluator, unroll ? int(SizeAtCompileTime) : Dynamic>::run(thisEval, visitor);
}
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
Zero() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero static inherited
Returns
an expression of a fixed-size zero matrix or vector.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See also
Zero(Index), Zero(Index,Index)
{
  return Constant(Scalar(0));
}
Zero() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index rows, Index cols) static inherited
Returns
an expression of a zero matrix.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
Example:
Output:
See also
Zero(), Zero(Index)
{
  return Constant(rows, cols, Scalar(0));
}
Zero() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index size) static inherited
Returns
an expression of a zero vector.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
Example:
Output:
See also
Zero(), Zero(Index,Index)
{
  return Constant(size, Scalar(0));
}
Friends And Related Symbol Documentation
operator<<()
template<typename Derived > std::ostream & operator<< (std::ostream & s, const DenseBase< Derived > & m) related
Outputs the matrix, to the given stream.
If you wish to print the matrix with a format different than the default, use DenseBase::format().
It is also possible to change the default format by defining EIGEN_DEFAULT_IO_FORMAT before including Eigen headers. If not defined, this will automatically be defined to Eigen::IOFormat(), that is the Eigen::IOFormat with default parameters.
See also
DenseBase::format()
{
  return internal::print_matrix(s, m.eval(), EIGEN_DEFAULT_IO_FORMAT);
}
References EIGEN_DEFAULT_IO_FORMAT, and Eigen::internal::print_matrix().
Member Data Documentation
m_expression
template<typename ExpressionType > NestedExpressionType Eigen::MatrixWrapper< ExpressionType >::m_expression protected
Referenced by Eigen::MatrixWrapper< ExpressionType >::coeffRef(), Eigen::MatrixWrapper< ExpressionType >::coeffRef(), Eigen::MatrixWrapper< ExpressionType >::cols(), Eigen::MatrixWrapper< ExpressionType >::data(), Eigen::MatrixWrapper< ExpressionType >::data(), Eigen::MatrixWrapper< ExpressionType >::innerStride(), Eigen::MatrixWrapper< ExpressionType >::nestedExpression(), Eigen::MatrixWrapper< ExpressionType >::outerStride(), Eigen::MatrixWrapper< ExpressionType >::resize(), Eigen::MatrixWrapper< ExpressionType >::resize(), and Eigen::MatrixWrapper< ExpressionType >::rows().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/ArrayBase.h
src/eigen/Eigen/src/Core/ArrayWrapper.h