Prusa Slicer: Slic3r::GUI::PhysicalPrinterDialog Class Reference
Slic3r::GUI::PhysicalPrinterDialog Class Reference
#include <src/slic3r/GUI/PhysicalPrinterDialog.hpp>
Public Member Functions
PhysicalPrinterDialog (wxWindow *parent, wxString printer_name)
~PhysicalPrinterDialog ()
void update (bool printer_change=false)
void update_host_type (bool printer_change)
void update_printhost_buttons ()
void update_printers ()
wxString get_printer_name ()
void update_full_printer_names ()
PhysicalPrinter * get_printer ()
void set_printer_technology (PrinterTechnology pt)
PrinterTechnology get_printer_technology ()
void DeletePreset (PresetForPrinter *preset_for_printer)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
Protected Member Functions
void on_dpi_changed (const wxRect &suggested_rect) override
void on_sys_color_changed () override
Private Member Functions
void build_printhost_settings (ConfigOptionsGroup *optgroup)
void OnOK (wxEvent &event)
void AddPreset (wxEvent &event)
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
PhysicalPrinter m_printer
wxString m_default_name
DynamicPrintConfig * m_config { nullptr }
wxTextCtrl * m_printer_name { nullptr }
std::vector< PresetForPrinter * > m_presets
ConfigOptionsGroup * m_optgroup { nullptr }
ScalableButton * m_add_preset_btn {nullptr}
ScalableButton * m_printhost_browse_btn {nullptr}
ScalableButton * m_printhost_test_btn {nullptr}
ScalableButton * m_printhost_cafile_browse_btn {nullptr}
ScalableButton * m_printhost_port_browse_btn {nullptr}
wxBoxSizer * m_presets_sizer {nullptr}
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
PhysicalPrinterDialog()
Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog (wxWindow * parent, wxString printer_name)
                                                                                    :
    DPIDialog(parent, wxID_ANY, _L("Physical Printer"), wxDefaultPosition, wxSize(45 * wxGetApp().em_unit(), -1), wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
    m_printer("", wxGetApp().preset_bundle->physical_printers.default_config())
{
    SetFont(wxGetApp().normal_font());
#ifndef _WIN32
    SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW));
#endif
    m_default_name = _L("Type here the name of your printer device");
    bool new_printer = true;
    if (printer_name.IsEmpty())
        printer_name = m_default_name;
    else {
        std::string full_name = into_u8(printer_name);
        printer_name = from_u8(PhysicalPrinter::get_short_name(full_name));
        new_printer = false;
    }
    wxStaticText* label_top = new wxStaticText(this, wxID_ANY, _L("Descriptive name for the printer") + ":");
    m_add_preset_btn = new ScalableButton(this, wxID_ANY, "add_copies");
    m_add_preset_btn->SetFont(wxGetApp().normal_font());
    m_add_preset_btn->SetToolTip(_L("Add preset for this printer device"));
    m_add_preset_btn->Bind(wxEVT_BUTTON, &PhysicalPrinterDialog::AddPreset, this);
    m_printer_name    = new wxTextCtrl(this, wxID_ANY, printer_name, wxDefaultPosition, wxDefaultSize);
    wxGetApp().UpdateDarkUI(m_printer_name);
    m_printer_name->Bind(wxEVT_TEXT, [this](wxEvent&) { this->update_full_printer_names(); });
    PhysicalPrinterCollection& printers = wxGetApp().preset_bundle->physical_printers;
    PhysicalPrinter* printer = printers.find_printer(into_u8(printer_name));
    if (!printer) {
        const Preset& preset = wxGetApp().preset_bundle->printers.get_edited_preset();
        m_printer = PhysicalPrinter(into_u8(printer_name), m_printer.config, preset);
        // if printer_name is empty it means that new printer is created, so enable all items in the preset list
        m_presets.emplace_back(new PresetForPrinter(this, preset.name));
    }
    else
    {
        m_printer = *printer;
        const std::set<std::string>& preset_names = printer->get_preset_names();
        for (const std::string& preset_name : preset_names)
            m_presets.emplace_back(new PresetForPrinter(this, preset_name));
    }
    if (m_presets.size() == 1)
        m_presets.front()->SuppressDelete();
    update_full_printer_names();
    m_config = &m_printer.config;
    m_optgroup = new ConfigOptionsGroup(this, _L("Print Host upload"), m_config);
    build_printhost_settings(m_optgroup);
    wxStdDialogButtonSizer* btns = this->CreateStdDialogButtonSizer(wxOK | wxCANCEL);
    wxButton* btnOK = static_cast<wxButton*>(this->FindWindowById(wxID_OK, this));
    wxGetApp().UpdateDarkUI(btnOK);
    btnOK->Bind(wxEVT_BUTTON, &PhysicalPrinterDialog::OnOK, this);
    wxGetApp().UpdateDarkUI(static_cast<wxButton*>(this->FindWindowById(wxID_CANCEL, this)));
    wxBoxSizer* nameSizer = new wxBoxSizer(wxHORIZONTAL);
    nameSizer->Add(m_printer_name, 1, wxEXPAND);
    nameSizer->Add(m_add_preset_btn, 0, wxEXPAND | wxLEFT, BORDER_W);
    m_presets_sizer = new wxBoxSizer(wxVERTICAL);
    for (PresetForPrinter* preset : m_presets)
        m_presets_sizer->Add(preset->sizer(), 1, wxEXPAND | wxTOP, BORDER_W);
    wxBoxSizer* topSizer = new wxBoxSizer(wxVERTICAL);
    topSizer->Add(label_top           , 0, wxEXPAND | wxLEFT | wxTOP | wxRIGHT, BORDER_W);
    topSizer->Add(nameSizer           , 0, wxEXPAND | wxLEFT | wxRIGHT, BORDER_W);
    topSizer->Add(m_presets_sizer     , 0, wxEXPAND | wxLEFT | wxRIGHT, BORDER_W);
    topSizer->Add(m_optgroup->sizer   , 1, wxEXPAND | wxLEFT | wxTOP | wxRIGHT, BORDER_W);
    topSizer->Add(btns                , 0, wxEXPAND | wxALL, BORDER_W);
    SetSizer(topSizer);
    topSizer->SetSizeHints(this);
    if (new_printer) {
        m_printer_name->SetFocus();
        m_printer_name->SelectAll();
    }
    this->Fit();
    this->Layout();
    this->CenterOnScreen();
}
References _L, AddPreset(), Slic3r::GUI::BORDER_W, build_printhost_settings(), Slic3r::PhysicalPrinter::config, Slic3r::PhysicalPrinterCollection::find_printer(), Slic3r::GUI::from_u8(), Slic3r::PhysicalPrinter::get_preset_names(), Slic3r::PhysicalPrinter::get_short_name(), Slic3r::GUI::into_u8(), m_add_preset_btn, m_config, m_default_name, m_optgroup, m_presets, m_presets_sizer, m_printer, m_printer_name, Slic3r::Preset::name, Slic3r::GUI::DPIAware< P >::normal_font(), OnOK(), Slic3r::GUI::OptionsGroup::sizer, update_full_printer_names(), and wxEVT_BUTTON.
~PhysicalPrinterDialog()
Slic3r::GUI::PhysicalPrinterDialog::~PhysicalPrinterDialog ()
{
    for (PresetForPrinter* preset : m_presets) {
        delete preset;
        preset = nullptr;
    }
}
References m_presets.
Member Function Documentation
AddPreset()
void Slic3r::GUI::PhysicalPrinterDialog::AddPreset (wxEvent & event) private
{
    m_presets.emplace_back(new PresetForPrinter(this));
    // enable DELETE button for the first preset, if was disabled
    m_presets.front()->AllowDelete();
    m_presets_sizer->Add(m_presets.back()->sizer(), 1, wxEXPAND | wxTOP, BORDER_W);
    update_full_printer_names();
    this->Fit();
    update_host_type(true);
}
References Slic3r::GUI::BORDER_W, m_presets, m_presets_sizer, update_full_printer_names(), and update_host_type().
Referenced by PhysicalPrinterDialog().
build_printhost_settings()
void Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings (ConfigOptionsGroup * optgroup) private
{
    m_optgroup->m_on_change = [this](t_config_option_key opt_key, boost::any value) {
        if (opt_key == "host_type" || opt_key == "printhost_authorization_type")
            this->update();
        if (opt_key == "print_host")
            this->update_printhost_buttons();
    };
    m_optgroup->append_single_option_line("host_type");
    auto create_sizer_with_btn = [](wxWindow* parent, ScalableButton** btn, const std::string& icon_name, const wxString& label) {
        *btn = new ScalableButton(parent, wxID_ANY, icon_name, label, wxDefaultSize, wxDefaultPosition, wxBU_LEFT | wxBU_EXACTFIT);
        (*btn)->SetFont(wxGetApp().normal_font());
        auto sizer = new wxBoxSizer(wxHORIZONTAL);
        sizer->Add(*btn);
        return sizer;
    };
    auto printhost_browse = [=](wxWindow* parent)
    {
        auto sizer = create_sizer_with_btn(parent, &m_printhost_browse_btn, "browse", _L("Browse") + " " + dots);
        m_printhost_browse_btn->Bind(wxEVT_BUTTON, [=](wxCommandEvent& e) {
            BonjourDialog dialog(this, Preset::printer_technology(m_printer.config));
            if (dialog.show_and_lookup()) {
                m_optgroup->set_value("print_host", dialog.get_selected(), true);
                m_optgroup->get_field("print_host")->field_changed();
            }
        });
        return sizer;
    };
    auto print_host_test = [=](wxWindow* parent) {
        auto sizer = create_sizer_with_btn(parent, &m_printhost_test_btn, "test", _L("Test"));
        m_printhost_test_btn->Bind(wxEVT_BUTTON, [this](wxCommandEvent& e) {
            std::unique_ptr<PrintHost> host(PrintHost::get_print_host(m_config));
            if (!host) {
                const wxString text = _L("Could not get a valid Printer Host reference");
                show_error(this, text);
                return;
            }
            wxString msg;
            bool result;
            {
                // Show a wait cursor during the connection test, as it is blocking UI.
                wxBusyCursor wait;
                result = host->test(msg);
            }
            if (result)
                show_info(this, host->get_test_ok_msg(), _L("Success!"));
            else
                show_error(this, host->get_test_failed_msg(msg));
            });
        return sizer;
    };
    auto print_host_printers = [this, create_sizer_with_btn](wxWindow* parent) {
        //add_scaled_button(parent, &m_printhost_port_browse_btn, "browse", _(L("Refresh Printers")), wxBU_LEFT | wxBU_EXACTFIT);
        auto sizer = create_sizer_with_btn(parent, &m_printhost_port_browse_btn, "browse", _(L("Refresh Printers")));
        ScalableButton* btn = m_printhost_port_browse_btn;
        btn->SetFont(Slic3r::GUI::wxGetApp().normal_font());
        btn->Bind(wxEVT_BUTTON, [this](wxCommandEvent e) { update_printers(); });
        return sizer;
    };
    // Set a wider width for a better alignment
    Option option = m_optgroup->get_option("print_host");
    option.opt.width = Field::def_width_wider();
    Line host_line = m_optgroup->create_single_option_line(option);
    host_line.append_widget(printhost_browse);
    host_line.append_widget(print_host_test);
    m_optgroup->append_line(host_line);
    m_optgroup->append_single_option_line("printhost_authorization_type");
    option = m_optgroup->get_option("printhost_apikey");
    option.opt.width = Field::def_width_wider();
    m_optgroup->append_single_option_line(option);
    option = m_optgroup->get_option("printhost_port");
    option.opt.width = Field::def_width_wider();
    Line port_line = m_optgroup->create_single_option_line(option);
    port_line.append_widget(print_host_printers);
    m_optgroup->append_line(port_line);
    const auto ca_file_hint = _u8L("HTTPS CA file is optional. It is only needed if you use HTTPS with a self-signed certificate.");
    if (Http::ca_file_supported()) {
        option = m_optgroup->get_option("printhost_cafile");
        option.opt.width = Field::def_width_wider();
        Line cafile_line = m_optgroup->create_single_option_line(option);
        auto printhost_cafile_browse = [=](wxWindow* parent) {
            auto sizer = create_sizer_with_btn(parent, &m_printhost_cafile_browse_btn, "browse", _L("Browse") + " " + dots);
            m_printhost_cafile_browse_btn->Bind(wxEVT_BUTTON, [this, m_optgroup](wxCommandEvent e) {
                static const auto filemasks = _L("Certificate files (*.crt, *.pem)|*.crt;*.pem|All files|*.*");
                wxFileDialog openFileDialog(this, _L("Open CA certificate file"), "", "", filemasks, wxFD_OPEN | wxFD_FILE_MUST_EXIST);
                if (openFileDialog.ShowModal() != wxID_CANCEL) {
                    m_optgroup->set_value("printhost_cafile", openFileDialog.GetPath(), true);
                    m_optgroup->get_field("printhost_cafile")->field_changed();
                }
                });
            return sizer;
        };
        cafile_line.append_widget(printhost_cafile_browse);
        m_optgroup->append_line(cafile_line);
        Line cafile_hint{ "", "" };
        cafile_hint.full_width = 1;
        cafile_hint.widget = [ca_file_hint](wxWindow* parent) {
            auto txt = new wxStaticText(parent, wxID_ANY, ca_file_hint);
            auto sizer = new wxBoxSizer(wxHORIZONTAL);
            sizer->Add(txt);
            return sizer;
        };
        m_optgroup->append_line(cafile_hint);
    }
    else {
        Line line{ "", "" };
        line.full_width = 1;
        line.widget = [ca_file_hint](wxWindow* parent) {
            std::string info = _u8L("HTTPS CA File") + ":\n\t" +
                (boost::format(_u8L("On this system, %s uses HTTPS certificates from the system Certificate Store or Keychain.")) % SLIC3R_APP_NAME).str() +
                "\n\t" + _u8L("To use a custom CA file, please import your CA file into Certificate Store / Keychain.");
            //auto txt = new wxStaticText(parent, wxID_ANY, from_u8((boost::format("%1%\n\n\t%2%") % info % ca_file_hint).str()));
            auto txt = new wxStaticText(parent, wxID_ANY, from_u8((boost::format("%1%\n\t%2%") % info % ca_file_hint).str()));
            txt->SetFont(wxGetApp().normal_font());
            auto sizer = new wxBoxSizer(wxHORIZONTAL);
            sizer->Add(txt, 1, wxEXPAND);
            return sizer;
        };
        m_optgroup->append_line(line);
    }
    for (const std::string& opt_key : std::vector<std::string>{ "printhost_user", "printhost_password" }) {
        option = m_optgroup->get_option(opt_key);
        option.opt.width = Field::def_width_wider();
        m_optgroup->append_single_option_line(option);
    }
#ifdef WIN32
    option = m_optgroup->get_option("printhost_ssl_ignore_revoke");
    option.opt.width = Field::def_width_wider();
    m_optgroup->append_single_option_line(option);
#endif
    m_optgroup->activate();
    Field* printhost_field = m_optgroup->get_field("print_host");
    if (printhost_field)
    {
        wxTextCtrl* temp = dynamic_cast<wxTextCtrl*>(printhost_field->getWindow());
        if (temp)
            temp->Bind(wxEVT_TEXT, ([printhost_field, temp](wxEvent& e)
            {
#ifndef __WXGTK__
                e.Skip();
                temp->GetToolTip()->Enable(true);
#endif // __WXGTK__
                // Remove all leading and trailing spaces from the input
                std::string trimed_str, str = trimed_str = temp->GetValue().ToStdString();
                boost::trim(trimed_str);
                if (trimed_str != str)
                    temp->SetValue(trimed_str);
                TextCtrl* field = dynamic_cast<TextCtrl*>(printhost_field);
                if (field)
                    field->propagate_value();
            }), temp->GetId());
    }
    // Always fill in the "printhost_port" combo box from the config and select it.
    {
        Choice* choice = dynamic_cast<Choice*>(m_optgroup->get_field("printhost_port"));
        choice->set_values({ m_config->opt_string("printhost_port") });
        choice->set_selection();
    }
    update(true);
}
References _, _L, _u8L, Slic3r::GUI::OptionsGroup::activate(), Slic3r::GUI::OptionsGroup::append_line(), Slic3r::GUI::ConfigOptionsGroup::append_single_option_line(), Slic3r::GUI::Line::append_widget(), Slic3r::Http::ca_file_supported(), Slic3r::PhysicalPrinter::config, Slic3r::GUI::ConfigOptionsGroup::create_single_option_line(), Slic3r::GUI::Field::def_width_wider(), Slic3r::GUI::dots(), Slic3r::Enable, Slic3r::GUI::Field::field_changed(), Slic3r::GUI::from_u8(), Slic3r::GUI::Line::full_width, Slic3r::GUI::OptionsGroup::get_field(), Slic3r::GUI::ConfigOptionsGroup::get_option(), Slic3r::PrintHost::get_print_host(), Slic3r::BonjourDialog::get_selected(), Slic3r::GUI::Field::getWindow(), L, m_config, Slic3r::GUI::OptionsGroup::m_on_change, m_optgroup, m_printer, m_printhost_browse_btn, m_printhost_cafile_browse_btn, m_printhost_port_browse_btn, m_printhost_test_btn, Slic3r::GUI::DPIAware< P >::normal_font(), Slic3r::ConfigBase::opt_string(), Slic3r::Preset::printer_technology(), Slic3r::GUI::TextCtrl::propagate_value(), Slic3r::GUI::Choice::set_selection(), Slic3r::GUI::OptionsGroup::set_value(), Slic3r::GUI::Choice::set_values(), Slic3r::BonjourDialog::show_and_lookup(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), update(), update_printers(), update_printhost_buttons(), and wxEVT_BUTTON.
Referenced by PhysicalPrinterDialog().
DeletePreset()
void Slic3r::GUI::PhysicalPrinterDialog::DeletePreset (PresetForPrinter * preset_for_printer)
{
    if (m_presets.size() == 1) {
        wxString msg_text = _L("It's not possible to delete the last related preset for the printer.");
        //wxMessageDialog dialog(nullptr, msg_text, _L("Information"), wxICON_INFORMATION | wxOK);
        MessageDialog dialog(nullptr, msg_text, _L("Information"), wxICON_INFORMATION | wxOK);
        dialog.ShowModal();
        return;
    }
    assert(preset_for_printer);
    auto it = std::find(m_presets.begin(), m_presets.end(), preset_for_printer);
    if (it == m_presets.end())
        return;
    const int remove_id = it - m_presets.begin();
    m_presets_sizer->Remove(remove_id);
    delete preset_for_printer;
    m_presets.erase(it);
    if (m_presets.size() == 1)
        m_presets.front()->SuppressDelete();
    this->Layout();
    this->Fit();
    update_host_type(true);
}
References _L, m_presets, m_presets_sizer, and update_host_type().
Referenced by Slic3r::GUI::PresetForPrinter::DeletePreset().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::FileArchiveDialog::FileArchiveDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::ExtruderSequenceDialog::apply_extruder_sequence(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::DiffPresetDialog::complete_dialog_creation(), Slic3r::GUI::DiffPresetDialog::create_edit_sizer(), Slic3r::GUI::DiffPresetDialog::create_presets_sizer(), Slic3r::GUI::DiffPresetDialog::create_tree(), em_unit(), Slic3r::GUI::SavePresetDialog::Item::init_input_name_ctrl(), Slic3r::Search::SearchDialog::msw_rescale(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigSnapshotDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::FileArchiveDialog::on_dpi_changed(), Slic3r::FirmwareDialog::on_dpi_changed(), Slic3r::GUI::GalleryDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), on_dpi_changed(), Slic3r::GUI::LoadProjectsDialog::on_dpi_changed(), Slic3r::GUI::ProjectDropDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
Referenced by Slic3r::GUI::MainFrame::update_layout().
get_printer()
PhysicalPrinter * Slic3r::GUI::PhysicalPrinterDialog::get_printer () inline
{return &m_printer; }
References m_printer.
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter().
get_printer_name()
wxString Slic3r::GUI::PhysicalPrinterDialog::get_printer_name ()
{
    return m_printer_name->GetValue();
}
References m_printer_name.
Referenced by Slic3r::GUI::PresetForPrinter::update_full_printer_name().
get_printer_technology()
PrinterTechnology Slic3r::GUI::PhysicalPrinterDialog::get_printer_technology ()
{
    return m_printer.printer_technology();
}
References m_printer, and Slic3r::PhysicalPrinter::printer_technology().
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter(), and Slic3r::GUI::PresetForPrinter::AllowDelete().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigSnapshotDialog::ConfigSnapshotDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ExtruderSequenceDialog::ExtruderSequenceDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::LoadProjectsDialog::LoadProjectsDialog(), PhysicalPrinterDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), build_printhost_settings(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::MainFrame::init_tabpanel(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::MainFrame::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
on_dpi_changed()
void Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    const int& em = em_unit();
    m_optgroup->msw_rescale();
    msw_buttons_rescale(this, em, { wxID_OK, wxID_CANCEL });
    const wxSize& size = wxSize(45 * em, 35 * em);
    SetMinSize(size);
    Fit();
    Refresh();
}
References Slic3r::GUI::DPIAware< P >::em_unit(), m_optgroup, msw_buttons_rescale(), and Slic3r::GUI::ConfigOptionsGroup::msw_rescale().
on_sys_color_changed()
void Slic3r::GUI::PhysicalPrinterDialog::on_sys_color_changed () override protected virtual
Reimplemented from Slic3r::GUI::DPIAware< P >.
{
    m_add_preset_btn->sys_color_changed();
    m_printhost_browse_btn->sys_color_changed();
    m_printhost_test_btn->sys_color_changed();
    if (m_printhost_cafile_browse_btn)
        m_printhost_cafile_browse_btn->sys_color_changed();
    for (PresetForPrinter* preset : m_presets)
        preset->on_sys_color_changed();
}
References m_add_preset_btn, m_presets, m_printhost_browse_btn, m_printhost_cafile_browse_btn, m_printhost_test_btn, and ScalableButton::sys_color_changed().
OnOK()
void Slic3r::GUI::PhysicalPrinterDialog::OnOK (wxEvent & event) private
{
    wxString printer_name = m_printer_name->GetValue();
    if (printer_name.IsEmpty() || printer_name == m_default_name) {
        warning_catcher(this, _L("You have to enter a printer name."));
        return;
    }
    PhysicalPrinterCollection& printers = wxGetApp().preset_bundle->physical_printers;
    const PhysicalPrinter* existing = printers.find_printer(into_u8(printer_name), false);
    if (existing && into_u8(printer_name) != printers.get_selected_printer_name())
    {
        wxString msg_text = from_u8((boost::format(_u8L("Printer with name \"%1%\" already exists.")) % existing->name/*printer_name*/).str());
        msg_text += "\n" + _L("Replace?");
        //wxMessageDialog dialog(nullptr, msg_text, _L("Warning"), wxICON_WARNING | wxYES | wxNO);
        MessageDialog dialog(nullptr, msg_text, _L("Warning"), wxICON_WARNING | wxYES | wxNO);
        if (dialog.ShowModal() == wxID_NO)
            return;
        m_printer.name = existing->name;
    }
    std::set<std::string> repeat_presets;
    m_printer.reset_presets();
    for (PresetForPrinter* preset : m_presets) {
        if (!m_printer.add_preset(preset->get_preset_name()))
            repeat_presets.emplace(preset->get_preset_name());
    }
    if (!repeat_presets.empty())
    {
        wxString repeatable_presets = "\n";
        int repeat_cnt = 0;
        for (const std::string& preset_name : repeat_presets) {
            repeatable_presets += "    " + from_u8(preset_name) + "\n";
            repeat_cnt++;
        }
        repeatable_presets += "\n";
        wxString msg_text = format_wxstr(_L_PLURAL("Following printer preset is duplicated:%1%"
                                                   "The above preset for printer \"%2%\" will be used just once.",
                                                   "Following printer presets are duplicated:%1%"
                                                   "The above presets for printer \"%2%\" will be used just once.", repeat_cnt), repeatable_presets, printer_name);
        //wxMessageDialog dialog(nullptr, msg_text, _L("Warning"), wxICON_WARNING | wxOK | wxCANCEL);
        MessageDialog dialog(nullptr, msg_text, _L("Warning"), wxICON_WARNING | wxOK | wxCANCEL);
        if (dialog.ShowModal() == wxID_CANCEL)
            return;
    }
    std::string renamed_from;
    // temporary save previous printer name if it was edited
    if (m_printer.name != into_u8(m_default_name) &&
        m_printer.name != into_u8(printer_name))
        renamed_from = m_printer.name;
    //update printer name, if it was changed
    m_printer.set_name(into_u8(printer_name));
    // save new physical printer
    printers.save_printer(m_printer, renamed_from);
    if (m_printer.preset_names.find(printers.get_selected_printer_preset_name()) == m_printer.preset_names.end()) {
        // select first preset for this printer
        printers.select_printer(m_printer);
        // refresh preset list on Printer Settings Tab
        wxGetApp().get_tab(Preset::TYPE_PRINTER)->select_preset(printers.get_selected_printer_preset_name());
    }
    else
        wxGetApp().get_tab(Preset::TYPE_PRINTER)->update_preset_choice();
    event.Skip();
}
References _L, _L_PLURAL, _u8L, Slic3r::PhysicalPrinter::add_preset(), Slic3r::PhysicalPrinterCollection::find_printer(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::from_u8(), Slic3r::PhysicalPrinterCollection::get_selected_printer_name(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), Slic3r::GUI::into_u8(), m_default_name, m_presets, m_printer, m_printer_name, Slic3r::PhysicalPrinter::name, Slic3r::PhysicalPrinter::preset_names, Slic3r::PhysicalPrinter::reset_presets(), Slic3r::PhysicalPrinterCollection::save_printer(), Slic3r::PhysicalPrinterCollection::select_printer(), Slic3r::PhysicalPrinter::set_name(), Slic3r::Preset::TYPE_PRINTER, and Slic3r::GUI::warning_catcher().
Referenced by PhysicalPrinterDialog().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DiffPresetDialog::on_dpi_changed().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
set_printer_technology()
void Slic3r::GUI::PhysicalPrinterDialog::set_printer_technology (PrinterTechnology pt)
{
    m_config->set_key_value("printer_technology", new ConfigOptionEnum<PrinterTechnology>(pt));
    update(true);
}
References m_config, Slic3r::DynamicConfig::set_key_value(), and update().
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter().
update()
void Slic3r::GUI::PhysicalPrinterDialog::update (bool printer_change = false)
{
    m_optgroup->reload_config();
    const PrinterTechnology tech = Preset::printer_technology(*m_config);
    // Only offer the host type selection for FFF, for SLA it's always the SL1 printer (at the moment)
    bool supports_multiple_printers = false;
    if (tech == ptFFF) {
        update_host_type(printer_change);
        const auto opt = m_config->option<ConfigOptionEnum<PrintHostType>>("host_type");
        m_optgroup->show_field("host_type");
        // hide PrusaConnect address
        if (Field* printhost_field = m_optgroup->get_field("print_host"); printhost_field) {
            if (wxTextCtrl* temp = dynamic_cast<wxTextCtrl*>(printhost_field->getWindow()); temp && temp->GetValue() == L"https://connect.prusa3d.com") {
                temp->SetValue(wxString());
            }
        }
        if (opt->value == htPrusaLink) { // PrusaConnect does NOT allow http digest
            m_optgroup->show_field("printhost_authorization_type");
            AuthorizationType auth_type = m_config->option<ConfigOptionEnum<AuthorizationType>>("printhost_authorization_type")->value;
            m_optgroup->show_field("printhost_apikey", auth_type == AuthorizationType::atKeyPassword);
            for (const char* opt_key : { "printhost_user", "printhost_password" })
                m_optgroup->show_field(opt_key, auth_type == AuthorizationType::atUserPassword);
        } else {
            m_optgroup->hide_field("printhost_authorization_type");
            m_optgroup->show_field("printhost_apikey", true);
            for (const std::string& opt_key : std::vector<std::string>{ "printhost_user", "printhost_password" })
                m_optgroup->hide_field(opt_key);
            supports_multiple_printers = opt && opt->value == htRepetier;
            if (opt->value == htPrusaConnect) { // automatically show default prusaconnect address
                if (Field* printhost_field = m_optgroup->get_field("print_host"); printhost_field) {
                    if (wxTextCtrl* temp = dynamic_cast<wxTextCtrl*>(printhost_field->getWindow()); temp && temp->GetValue().IsEmpty()) {
                        temp->SetValue(L"https://connect.prusa3d.com");
                    }
                }
            }
        }
    }
    else {
        m_optgroup->set_value("host_type", int(PrintHostType::htOctoPrint), false);
        m_optgroup->hide_field("host_type");
        m_optgroup->show_field("printhost_authorization_type");
        AuthorizationType auth_type = m_config->option<ConfigOptionEnum<AuthorizationType>>("printhost_authorization_type")->value;
        m_optgroup->show_field("printhost_apikey", auth_type == AuthorizationType::atKeyPassword);
        for (const char *opt_key : { "printhost_user", "printhost_password" })
            m_optgroup->show_field(opt_key, auth_type == AuthorizationType::atUserPassword);
    }
    m_optgroup->show_field("printhost_port", supports_multiple_printers);
    m_printhost_port_browse_btn->Show(supports_multiple_printers);
    update_printhost_buttons();
    this->Fit();
    this->Layout();
#ifdef __WXMSW__
    this->Refresh();
#endif
}
References Slic3r::atKeyPassword, Slic3r::atUserPassword, Slic3r::GUI::OptionsGroup::get_field(), Slic3r::GUI::OptionsGroup::hide_field(), Slic3r::htOctoPrint, Slic3r::htPrusaConnect, Slic3r::htPrusaLink, Slic3r::htRepetier, L, m_config, m_optgroup, m_printhost_port_browse_btn, Slic3r::ConfigBase::option(), Slic3r::Preset::printer_technology(), Slic3r::ptFFF, Slic3r::GUI::ConfigOptionsGroup::reload_config(), Slic3r::GUI::OptionsGroup::set_value(), Slic3r::GUI::OptionsGroup::show_field(), update_host_type(), and update_printhost_buttons().
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter(), build_printhost_settings(), and set_printer_technology().
update_full_printer_names()
void Slic3r::GUI::PhysicalPrinterDialog::update_full_printer_names ()
{
    // check input symbols for usability
    const char* unusable_symbols = "<>[]:/\\|?*\"";
    wxString printer_name = m_printer_name->GetValue();
    for (size_t i = 0; i < std::strlen(unusable_symbols); i++) {
        size_t pos = printer_name.find_first_of(unusable_symbols[i]);
        if (pos != std::string::npos) {
            wxString str = printer_name.SubString(pos, 1);
            printer_name.Remove(pos, 1);
            InfoDialog(this, format_wxstr("%1%: \"%2%\" ", _L("Unexpected character"),  str),
                       _L("The following characters are not allowed in the name") + ": " + unusable_symbols).ShowModal();
            m_printer_name->SetValue(printer_name);
            m_printer_name->SetInsertionPointEnd();
            return;
        }
    }
    for (PresetForPrinter* preset : m_presets)
        preset->update_full_printer_name();
    this->Layout();
}
References _L, Slic3r::GUI::format_wxstr(), m_presets, and m_printer_name.
Referenced by PhysicalPrinterDialog(), and AddPreset().
update_host_type()
void Slic3r::GUI::PhysicalPrinterDialog::update_host_type (bool printer_change)
{
    if (m_presets.empty())
        return;
    struct {
        bool supported { true };
        wxString label;
    } link, connect;
    // allowed models are: all MINI, all MK3 and newer, MK2.5 and MK2.5S
    auto model_supports_prusalink = [](const std::string& model) {
        return model.size() >= 2 &&
                (( boost::starts_with(model, "MK") && model[2] > '2' && model[2] <= '9')
                || boost::starts_with(model, "MINI")
                || boost::starts_with(model, "MK2.5")
                || boost::starts_with(model, "XL")
                );
    };
    // allowed models are: all MK3/S and MK2.5/S
    auto model_supports_prusaconnect = [](const std::string& model) {
        return model.size() >= 2 &&
                ((boost::starts_with(model, "MK") && model[2] > '2' && model[2] <= '9')
                || boost::starts_with(model, "MK2.5")
                || boost::starts_with(model, "XL")
                );
    };
    // set all_presets_are_prusalink_supported
    for (PresetForPrinter* prstft : m_presets) {
        std::string preset_name = prstft->get_preset_name();
        if (Preset* preset = wxGetApp().preset_bundle->printers.find_preset(preset_name)) {
            std::string model_id = preset->config.opt_string("printer_model");
            if (preset->vendor) {
                if (preset->vendor->name == "Prusa Research") {
                    const std::vector<VendorProfile::PrinterModel>& models = preset->vendor->models;
                    auto it = std::find_if(models.begin(), models.end(),
                        [model_id](const VendorProfile::PrinterModel& model) { return model.id == model_id; });
                    if (it != models.end() && model_supports_prusalink(it->family))
                        continue;
                }
            }
            else if (model_supports_prusalink(model_id))
                continue;
        }
        link.supported = false;
        break;
    }
    // set all_presets_are_prusaconnect_supported
    for (PresetForPrinter* prstft : m_presets) {
        std::string preset_name = prstft->get_preset_name();
        Preset* preset = wxGetApp().preset_bundle->printers.find_preset(preset_name);
        if (!preset) {
            connect.supported = false;
            break;
        }
        std::string model_id = preset->config.opt_string("printer_model");
        if (preset->vendor && preset->vendor->name != "Prusa Research") {
            connect.supported = false;
            break;
        }
        if (preset->vendor && preset->vendor->name != "Prusa Research") {
            connect.supported = false;
            break;
        }
        // model id should be enough for this case
        if (!model_supports_prusaconnect(model_id)) {
            connect.supported = false;
            break;
        }
    }
    Field* ht = m_optgroup->get_field("host_type");
    wxArrayString types;
    int last_in_conf = m_config->option("host_type")->getInt(); //  this is real position in last choice
    // Append localized enum_labels
    assert(ht->m_opt.enum_def->labels().size() == ht->m_opt.enum_def->values().size());
    for (size_t i = 0; i < ht->m_opt.enum_def->labels().size(); ++ i) {
        wxString label = _(ht->m_opt.enum_def->label(i));
        if (const std::string &value = ht->m_opt.enum_def->value(i);
            value == "prusalink") {
            link.label = label;
            if (!link.supported)
                continue;
        } else if (value == "prusaconnect") {
            connect.label = label;
            if (!connect.supported)
                continue;
        }
        types.Add(label);
    }
    Choice* choice = dynamic_cast<Choice*>(ht);
    choice->set_values(types);
    int index_in_choice = (printer_change ? std::clamp(last_in_conf - ((int)ht->m_opt.enum_def->values().size() - (int)types.size()), 0, (int)ht->m_opt.enum_def->values().size() - 1) : last_in_conf);
    choice->set_value(index_in_choice);
    if (link.supported && link.label == _(ht->m_opt.enum_def->label(index_in_choice)))
        m_config->set_key_value("host_type", new ConfigOptionEnum<PrintHostType>(htPrusaLink));
    else if (connect.supported && connect.label == _(ht->m_opt.enum_def->label(index_in_choice)))
        m_config->set_key_value("host_type", new ConfigOptionEnum<PrintHostType>(htPrusaConnect));
    else {
        int host_type = std::clamp(index_in_choice + ((int)ht->m_opt.enum_def->values().size() - (int)types.size()), 0, (int)ht->m_opt.enum_def->values().size() - 1);
        PrintHostType type = static_cast<PrintHostType>(host_type);
        m_config->set_key_value("host_type", new ConfigOptionEnum<PrintHostType>(type));
    }
}
References _, Slic3r::Preset::config, Slic3r::ConfigOptionDef::enum_def, Slic3r::GUI::OptionsGroup::get_field(), Slic3r::ConfigOption::getInt(), Slic3r::htPrusaConnect, Slic3r::htPrusaLink, m_config, Slic3r::GUI::Field::m_opt, m_optgroup, m_presets, Slic3r::VendorProfile::name, Slic3r::ConfigBase::opt_string(), Slic3r::ConfigBase::option(), Slic3r::DynamicConfig::set_key_value(), Slic3r::GUI::Choice::set_value(), Slic3r::GUI::Choice::set_values(), and Slic3r::Preset::vendor.
Referenced by AddPreset(), DeletePreset(), and update().
update_printers()
void Slic3r::GUI::PhysicalPrinterDialog::update_printers ()
{
    wxBusyCursor wait;
    std::unique_ptr<PrintHost> host(PrintHost::get_print_host(m_config));
    wxArrayString printers;
    Field *rs = m_optgroup->get_field("printhost_port");
    try {
        if (! host->get_printers(printers))
            printers.clear();
    } catch (const HostNetworkError &err) {
        printers.clear();
        show_error(this, _L("Connection to printers connected via the print host failed.") + "\n\n" + from_u8(err.what()));
    }
    Choice *choice = dynamic_cast<Choice*>(rs);
    choice->set_values(printers);
    printers.empty() ? rs->disable() : rs->enable();
}
References _L, Slic3r::GUI::Field::disable(), Slic3r::GUI::Field::enable(), Slic3r::GUI::from_u8(), Slic3r::GUI::OptionsGroup::get_field(), Slic3r::PrintHost::get_print_host(), m_config, m_optgroup, Slic3r::GUI::Choice::set_values(), and Slic3r::GUI::show_error().
Referenced by build_printhost_settings().
update_printhost_buttons()
void Slic3r::GUI::PhysicalPrinterDialog::update_printhost_buttons ()
{
    std::unique_ptr<PrintHost> host(PrintHost::get_print_host(m_config));
    m_printhost_test_btn->Enable(!m_config->opt_string("print_host").empty() && host->can_test());
    m_printhost_browse_btn->Enable(host->has_auto_discovery());
}
References Slic3r::PrintHost::get_print_host(), m_config, m_printhost_browse_btn, m_printhost_test_btn, and Slic3r::ConfigBase::opt_string().
Referenced by build_printhost_settings(), and update().
Member Data Documentation
m_add_preset_btn
ScalableButton* Slic3r::GUI::PhysicalPrinterDialog::m_add_preset_btn {nullptr} private
Referenced by PhysicalPrinterDialog(), and on_sys_color_changed().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_config
DynamicPrintConfig* Slic3r::GUI::PhysicalPrinterDialog::m_config { nullptr } private
Referenced by PhysicalPrinterDialog(), build_printhost_settings(), set_printer_technology(), update(), update_host_type(), update_printers(), and update_printhost_buttons().
m_default_name
wxString Slic3r::GUI::PhysicalPrinterDialog::m_default_name private
Referenced by PhysicalPrinterDialog(), and OnOK().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_optgroup
ConfigOptionsGroup* Slic3r::GUI::PhysicalPrinterDialog::m_optgroup { nullptr } private
Referenced by PhysicalPrinterDialog(), build_printhost_settings(), on_dpi_changed(), update(), update_host_type(), and update_printers().
m_presets
std::vector<PresetForPrinter*> Slic3r::GUI::PhysicalPrinterDialog::m_presets private
Referenced by PhysicalPrinterDialog(), ~PhysicalPrinterDialog(), AddPreset(), DeletePreset(), on_sys_color_changed(), OnOK(), update_full_printer_names(), and update_host_type().
m_presets_sizer
wxBoxSizer* Slic3r::GUI::PhysicalPrinterDialog::m_presets_sizer {nullptr} private
Referenced by PhysicalPrinterDialog(), AddPreset(), and DeletePreset().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_printer
PhysicalPrinter Slic3r::GUI::PhysicalPrinterDialog::m_printer private
Referenced by PhysicalPrinterDialog(), build_printhost_settings(), get_printer(), get_printer_technology(), and OnOK().
m_printer_name
wxTextCtrl* Slic3r::GUI::PhysicalPrinterDialog::m_printer_name { nullptr } private
Referenced by PhysicalPrinterDialog(), get_printer_name(), OnOK(), and update_full_printer_names().
m_printhost_browse_btn
ScalableButton* Slic3r::GUI::PhysicalPrinterDialog::m_printhost_browse_btn {nullptr} private
Referenced by build_printhost_settings(), on_sys_color_changed(), and update_printhost_buttons().
m_printhost_cafile_browse_btn
ScalableButton* Slic3r::GUI::PhysicalPrinterDialog::m_printhost_cafile_browse_btn {nullptr} private
Referenced by build_printhost_settings(), and on_sys_color_changed().
m_printhost_port_browse_btn
ScalableButton* Slic3r::GUI::PhysicalPrinterDialog::m_printhost_port_browse_btn {nullptr} private
Referenced by build_printhost_settings(), and update().
m_printhost_test_btn
ScalableButton* Slic3r::GUI::PhysicalPrinterDialog::m_printhost_test_btn {nullptr} private
Referenced by build_printhost_settings(), on_sys_color_changed(), and update_printhost_buttons().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
The documentation for this class was generated from the following files:
src/slic3r/GUI/PhysicalPrinterDialog.hpp
src/slic3r/GUI/PhysicalPrinterDialog.cpp