Prusa Slicer: Slic3r::Timing::Timer Class Reference
Slic3r::Timing::Timer Class Reference
#include <src/libslic3r/Timer.hpp>
Public Member Functions
void start ()
uint64_t elapsed_nanoseconds () const
uint64_t elapsed_microseconds () const
unsigned int elapsed_milliseconds () const
double elapsed_seconds () const
Private Attributes
uint64_t m_nanoseconds = 0
Detailed Description
Member Function Documentation
elapsed_microseconds()
uint64_t Slic3r::Timing::Timer::elapsed_microseconds () const inline
{
            return elapsed_nanoseconds() / 1000;
        }
References elapsed_nanoseconds().
Referenced by elapsed_milliseconds(), and elapsed_seconds().
elapsed_milliseconds()
unsigned int Slic3r::Timing::Timer::elapsed_milliseconds () const inline
{
            return static_cast<unsigned int>(elapsed_microseconds()/1000);
        }
References elapsed_microseconds().
elapsed_nanoseconds()
uint64_t Slic3r::Timing::Timer::elapsed_nanoseconds () const inline
{
            return nanoseconds_since_epoch() - m_nanoseconds;
        }
References m_nanoseconds, and Slic3r::Timing::nanoseconds_since_epoch().
Referenced by Slic3r::Timing::TimeLimitAlarm::~TimeLimitAlarm(), and elapsed_microseconds().
elapsed_seconds()
double Slic3r::Timing::Timer::elapsed_seconds () const inline
{
            return elapsed_microseconds() / 1000000.0;
        }
References elapsed_microseconds().
Referenced by Slic3r::Timing::TimeLimitAlarm::report_time_exceeded().
start()
void Slic3r::Timing::Timer::start () inline
                     {
            m_nanoseconds = nanoseconds_since_epoch();
        }
References m_nanoseconds, and Slic3r::Timing::nanoseconds_since_epoch().
Referenced by Slic3r::Timing::TimeLimitAlarm::TimeLimitAlarm().
Member Data Documentation
m_nanoseconds
uint64_t Slic3r::Timing::Timer::m_nanoseconds = 0 private
Referenced by elapsed_nanoseconds(), and start().
The documentation for this class was generated from the following file:
src/libslic3r/Timer.hpp