Prusa Slicer: Slic3r::GUI::PageDownloader Struct Reference
Slic3r::GUI::PageDownloader Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
PageDownloader (ConfigWizard *parent)
bool on_finish_downloader () const
template<class T >
T * append (T *thing, int proportion=0, int flag=wxEXPAND|wxTOP|wxBOTTOM, int border=10)
wxStaticText * append_text (wxString text)
void append_spacer (int space)
ConfigWizard::priv * wizard_p () const
virtual void apply_custom_config (DynamicPrintConfig &config)
virtual void set_run_reason (ConfigWizard::RunReason run_reason)
virtual void on_activate ()
Public Attributes
DownloaderUtils::Worker * m_downloader { nullptr }
ConfigWizard * parent
const wxString shortname
wxBoxSizer * content
const unsigned indent
Detailed Description
Constructor & Destructor Documentation
PageDownloader()
Slic3r::GUI::PageDownloader::PageDownloader (ConfigWizard * parent)
    : ConfigWizardPage(parent, _L("Downloads from URL"), _L("Downloads"))
{
    const AppConfig* app_config = wxGetApp().app_config;
    auto boldfont = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
    boldfont.SetWeight(wxFONTWEIGHT_BOLD);
    append_spacer(VERTICAL_SPACING);
    auto* box_allow_downloads = new wxCheckBox(this, wxID_ANY, _L("Allow built-in downloader"));
    // TODO: Do we want it like this? The downloader is allowed for very first time the wizard is run.
    bool box_allow_value = (app_config->has("downloader_url_registered") ? app_config->get_bool("downloader_url_registered") : true);
    box_allow_downloads->SetValue(box_allow_value);
    append(box_allow_downloads);
    // TRN ConfigWizard : Downloader : %1% = "PrusaSlicer"
    append_text(format_wxstr(_L("If enabled, %1% registers to start on custom URL on www.printables.com."
        " You will be able to use button with %1% logo to open models in this %1%."
        " The model will be downloaded into folder you choose bellow."
    ), SLIC3R_APP_NAME));
#ifdef __linux__
    append_text(wxString::Format(_L(
        "On Linux systems the process of registration also creates desktop integration files for this version of application."
    )));
#endif
    box_allow_downloads->Bind(wxEVT_CHECKBOX, [this](wxCommandEvent& event) { this->m_downloader->allow(event.IsChecked()); });
    m_downloader = new DownloaderUtils::Worker(this);
    append(m_downloader);
    m_downloader->allow(box_allow_value);
}
References _L, Slic3r::GUI::DownloaderUtils::Worker::allow(), Slic3r::GUI::ConfigWizardPage::append(), Slic3r::GUI::ConfigWizardPage::append_spacer(), Slic3r::GUI::ConfigWizardPage::append_text(), Slic3r::GUI::format_wxstr(), Slic3r::AppConfig::get_bool(), Slic3r::AppConfig::has(), m_downloader, and Slic3r::GUI::VERTICAL_SPACING.
Member Function Documentation
append()
template<class T > T * Slic3r::GUI::ConfigWizardPage::append (T * thing, int proportion = 0, int flag = wxEXPAND|wxTOP|wxBOTTOM, int border = 10) inline inherited
    {
        content->Add(thing, proportion, flag, border);
        return thing;
    }
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PageDiameters::PageDiameters(), PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), Slic3r::GUI::PageVendors::PageVendors(), and Slic3r::GUI::ConfigWizardPage::append_text().
append_spacer()
void Slic3r::GUI::ConfigWizardPage::append_spacer (int space) inherited
{
    // FIXME: scaling
    content->AddSpacer(space);
}
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageDiameters::PageDiameters(), PageDownloader(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageTemperatures::PageTemperatures(), and Slic3r::GUI::PageUpdate::PageUpdate().
append_text()
wxStaticText * Slic3r::GUI::ConfigWizardPage::append_text (wxString text) inherited
{
    auto *widget = new wxStaticText(this, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    widget->Wrap(WRAP_WIDTH);
    widget->SetMinSize(wxSize(WRAP_WIDTH, -1));
    append(widget);
    return widget;
}
References Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::WRAP_WIDTH.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageDiameters::PageDiameters(), PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), and Slic3r::GUI::PageVendors::PageVendors().
apply_custom_config()
virtual void Slic3r::GUI::ConfigWizardPage::apply_custom_config (DynamicPrintConfig & config) inline virtual inherited
Reimplemented in Slic3r::GUI::PageFirmware, Slic3r::GUI::PageBedShape, Slic3r::GUI::PageBuildVolume, Slic3r::GUI::PageDiameters, and Slic3r::GUI::PageTemperatures.
{}
on_activate()
virtual void Slic3r::GUI::ConfigWizardPage::on_activate () inline virtual inherited
Reimplemented in Slic3r::GUI::PageMaterials.
{}
Referenced by Slic3r::GUI::PageMode::PageMode().
on_finish_downloader()
bool Slic3r::GUI::PageDownloader::on_finish_downloader () const
{
    return m_downloader->on_finish();
}
References m_downloader, and Slic3r::GUI::DownloaderUtils::Worker::on_finish().
set_run_reason()
virtual void Slic3r::GUI::ConfigWizardPage::set_run_reason (ConfigWizard::RunReason run_reason) inline virtual inherited
Reimplemented in Slic3r::GUI::PageWelcome, and Slic3r::GUI::PagePrinters.
{}
wizard_p()
ConfigWizard::priv * Slic3r::GUI::ConfigWizardPage::wizard_p () const inline inherited
{ return parent->p.get(); }
References Slic3r::GUI::ConfigWizard::p, and Slic3r::GUI::ConfigWizardPage::parent.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageVendors::PageVendors(), Slic3r::GUI::PageMaterials::on_activate(), Slic3r::GUI::PageMaterials::select_material(), and Slic3r::GUI::PageMaterials::update_lists().
Member Data Documentation
content
wxBoxSizer* Slic3r::GUI::ConfigWizardPage::content inherited
Referenced by Slic3r::GUI::ConfigWizardPage::ConfigWizardPage(), Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::ConfigWizardPage::append_spacer().
indent
const unsigned Slic3r::GUI::ConfigWizardPage::indent inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page().
m_downloader
DownloaderUtils::Worker* Slic3r::GUI::PageDownloader::m_downloader { nullptr }
Referenced by PageDownloader(), and on_finish_downloader().
parent
ConfigWizard* Slic3r::GUI::ConfigWizardPage::parent inherited
Referenced by Slic3r::GUI::PageMaterials::PageMaterials(), and Slic3r::GUI::ConfigWizardPage::wizard_p().
shortname
const wxString Slic3r::GUI::ConfigWizardPage::shortname inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page(), and Slic3r::GUI::ConfigWizard::priv::add_page().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp