Prusa Slicer: Slic3r::ClipperUtils::SinglePathProvider Class Reference
Slic3r::ClipperUtils::SinglePathProvider Class Reference
#include <src/libslic3r/ClipperUtils.hpp>
Classes
struct iterator
Public Member Functions
SinglePathProvider (const Points &points)
iterator cbegin () const
iterator begin () const
iterator cend () const
iterator end () const
size_t size () const
Private Attributes
const Points & m_points
Static Private Attributes
static Points s_end
Detailed Description
Constructor & Destructor Documentation
SinglePathProvider()
Slic3r::ClipperUtils::SinglePathProvider::SinglePathProvider (const Points & points) inline
: m_points(points) {}
Member Function Documentation
begin()
iterator Slic3r::ClipperUtils::SinglePathProvider::begin () const inline
{ return this->cbegin(); }
References cbegin().
cbegin()
iterator Slic3r::ClipperUtils::SinglePathProvider::cbegin () const inline
{ return iterator(m_points); }
References m_points.
Referenced by begin().
cend()
iterator Slic3r::ClipperUtils::SinglePathProvider::cend () const inline
{ return iterator(s_end); }
References s_end.
Referenced by end().
end()
iterator Slic3r::ClipperUtils::SinglePathProvider::end () const inline
{ return this->cend(); }
References cend().
size()
size_t Slic3r::ClipperUtils::SinglePathProvider::size () const inline
{ return 1; }
Member Data Documentation
m_points
const Points& Slic3r::ClipperUtils::SinglePathProvider::m_points private
Referenced by cbegin().
s_end
Points Slic3r::ClipperUtils::SinglePathProvider::s_end static private
Referenced by cend(), Slic3r::ClipperUtils::SinglePathProvider::iterator::operator++(), and Slic3r::ClipperUtils::SinglePathProvider::iterator::operator++().
The documentation for this class was generated from the following files:
src/libslic3r/ClipperUtils.hpp
src/libslic3r/ClipperUtils.cpp