Prusa Slicer: Slic3r::GUI::MainFrame Class Reference
Slic3r::GUI::MainFrame Class Reference
#include <src/slic3r/GUI/MainFrame.hpp>
Public Member Functions
MainFrame (const int font_point_size)
~MainFrame ()=default
void update_layout ()
void update_mode_markers ()
void shutdown ()
Plater * plater ()
GalleryDialog * gallery_dialog ()
void update_title ()
void init_tabpanel ()
void create_preset_tabs ()
void add_created_tab (Tab *panel, const std::string &bmp_name="")
bool is_active_and_shown_tab (Tab *tab)
void register_win32_callbacks ()
void init_menubar_as_editor ()
void init_menubar_as_gcodeviewer ()
void update_menubar ()
void open_menubar_item (const wxString &menu_name, const wxString &item_name)
void update_ui_from_settings ()
bool is_loaded () const
bool is_last_input_file () const
bool is_dlg_layout () const
void reslice_now ()
void repair_stl ()
void export_config ()
void load_config_file ()
bool load_config_file (const std::string &path)
void export_configbundle (bool export_physical_printers=false)
void load_configbundle (wxString file=wxEmptyString)
void load_config (const DynamicPrintConfig &config)
void select_tab (Tab *tab)
void select_tab (size_t tab=size_t(-1))
void select_view (const std::string &direction)
void on_config_changed (DynamicPrintConfig *cfg) const
bool can_save () const
bool can_save_as () const
void save_project ()
bool save_project_as (const wxString &filename=wxString())
void add_to_recent_projects (const wxString &filename)
void technology_changed ()
PrintHostQueueDialog * printhost_queue_dlg ()
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
Public Attributes
Plater * m_plater { nullptr }
wxBookCtrlBase * m_tabpanel { nullptr }
SettingsDialog m_settings_dialog
DiffPresetDialog diff_dialog
wxWindow * m_plater_page { nullptr }
PreferencesDialog * preferences_dialog { nullptr }
PrintHostQueueDialog * m_printhost_queue_dlg
GalleryDialog * m_gallery_dialog { nullptr }
Protected Member Functions
virtual void on_dpi_changed (const wxRect &suggested_rect) override
virtual void on_sys_color_changed () override
Private Types
enum MenuItems { miExport = 0 , miSend , miMaterialTab , miPrinterTab }
enum class ESettingsLayout {
Unknown , Old , New , Dlg ,
GCodeViewer
}
Private Member Functions
std::string get_base_name (const wxString &full_name, const char *extension=nullptr) const
std::string get_dir_name (const wxString &full_name) const
void on_presets_changed (SimpleEvent &)
void on_value_changed (wxCommandEvent &)
bool can_start_new_project () const
bool can_export_model () const
bool can_export_toolpaths () const
bool can_export_supports () const
bool can_export_gcode () const
bool can_send_gcode () const
bool can_export_gcode_sd () const
bool can_eject () const
bool can_slice () const
bool can_change_view () const
bool can_select () const
bool can_deselect () const
bool can_delete () const
bool can_delete_all () const
bool can_reslice () const
void bind_diff_dialog ()
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
bool m_loaded {false}
wxString m_qs_last_input_file = wxEmptyString
wxString m_qs_last_output_file = wxEmptyString
wxString m_last_config = wxEmptyString
wxMenuBar * m_menubar { nullptr }
wxMenuItem * m_menu_item_reslice_now { nullptr }
wxSizer * m_main_sizer { nullptr }
size_t m_last_selected_tab
std::vector< wxMenuItem * > m_changeable_menu_items
wxFileHistory m_recent_projects
ESettingsLayout m_layout { ESettingsLayout::Unknown }
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Member Enumeration Documentation
ESettingsLayout
enum class Slic3r::GUI::MainFrame::ESettingsLayout strong private
Enumerator
Unknown
Old
New
Dlg
GCodeViewer
    {
        Unknown,
        Old,
        New,
        Dlg,
        GCodeViewer
    };
MenuItems
enum Slic3r::GUI::MainFrame::MenuItems private
Enumerator
miExport
miSend
miMaterialTab
miPrinterTab
    {                   //   FFF                  SLA
        miExport = 0,   // Export G-code        Export
        miSend,         // Send G-code          Send to print
        miMaterialTab,  // Filament Settings    Material Settings
        miPrinterTab,   // Different bitmap for Printer Settings
    };
Constructor & Destructor Documentation
MainFrame()
Slic3r::GUI::MainFrame::MainFrame (const int font_point_size)
                                              :
DPIFrame(NULL, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxDEFAULT_FRAME_STYLE, "mainframe", font_point_size),
    m_printhost_queue_dlg(new PrintHostQueueDialog(this))
    , m_recent_projects(9)
    , m_settings_dialog(this)
    , diff_dialog(this)
{
    // Fonts were created by the DPIFrame constructor for the monitor, on which the window opened.
    wxGetApp().update_fonts(this);
/*
#ifndef __WXOSX__ // Don't call SetFont under OSX to avoid name cutting in ObjectList
    this->SetFont(this->normal_font());
#endif
    // Font is already set in DPIFrame constructor
*/
#ifdef __APPLE__
    // Initialize the docker task bar icon.
    switch (wxGetApp().get_app_mode()) {
    default:
    case GUI_App::EAppMode::Editor:
        m_taskbar_icon = std::make_unique<PrusaSlicerTaskBarIcon>(wxTBI_DOCK);
        m_taskbar_icon->SetIcon(wxIcon(Slic3r::var("PrusaSlicer-mac_128px.png"), wxBITMAP_TYPE_PNG), "PrusaSlicer");
        break;
    case GUI_App::EAppMode::GCodeViewer:
        m_taskbar_icon = std::make_unique<GCodeViewerTaskBarIcon>(wxTBI_DOCK);
        m_taskbar_icon->SetIcon(wxIcon(Slic3r::var("PrusaSlicer-gcodeviewer-mac_128px.png"), wxBITMAP_TYPE_PNG), "G-code Viewer");
        break;
    }
#endif // __APPLE__
    // Load the icon either from the exe, or from the ico file.
    SetIcon(main_frame_icon(wxGetApp().get_app_mode()));
  // initialize status bar
//    m_statusbar = std::make_shared<ProgressStatusBar>(this);
//    m_statusbar->set_font(GUI::wxGetApp().normal_font());
//    if (wxGetApp().is_editor())
//        m_statusbar->embed(this);
//    m_statusbar->set_status_text(_L("Version") + " " +
//        SLIC3R_VERSION + " - " +
//       _L("Remember to check for updates at https://github.com/prusa3d/PrusaSlicer/releases"));
    // initialize tabpanel and menubar
    init_tabpanel();
    if (wxGetApp().is_gcode_viewer())
        init_menubar_as_gcodeviewer();
    else
        init_menubar_as_editor();
#if _WIN32
    // This is needed on Windows to fake the CTRL+# of the window menu when using the numpad
    wxAcceleratorEntry entries[6];
    entries[0].Set(wxACCEL_CTRL, WXK_NUMPAD1, wxID_HIGHEST + 1);
    entries[1].Set(wxACCEL_CTRL, WXK_NUMPAD2, wxID_HIGHEST + 2);
    entries[2].Set(wxACCEL_CTRL, WXK_NUMPAD3, wxID_HIGHEST + 3);
    entries[3].Set(wxACCEL_CTRL, WXK_NUMPAD4, wxID_HIGHEST + 4);
    entries[4].Set(wxACCEL_CTRL, WXK_NUMPAD5, wxID_HIGHEST + 5);
    entries[5].Set(wxACCEL_CTRL, WXK_NUMPAD6, wxID_HIGHEST + 6);
    wxAcceleratorTable accel(6, entries);
    SetAcceleratorTable(accel);
#endif // _WIN32
    // set default tooltip timer in msec
    // SetAutoPop supposedly accepts long integers but some bug doesn't allow for larger values
    // (SetAutoPop is not available on GTK.)
    wxToolTip::SetAutoPop(32767);
    m_loaded = true;
    // initialize layout
    m_main_sizer = new wxBoxSizer(wxVERTICAL);
    wxSizer* sizer = new wxBoxSizer(wxVERTICAL);
    sizer->Add(m_main_sizer, 1, wxEXPAND);
    SetSizer(sizer);
    // initialize layout from config
    update_layout();
    sizer->SetSizeHints(this);
    Fit();
    const wxSize min_size = wxGetApp().get_min_size(); //wxSize(76*wxGetApp().em_unit(), 49*wxGetApp().em_unit());
#ifdef __APPLE__
    // Using SetMinSize() on Mac messes up the window position in some cases
    // cf. https://groups.google.com/forum/#!topic/wx-users/yUKPBBfXWO0
    SetSize(min_size/*wxSize(760, 490)*/);
#else
    SetMinSize(min_size/*wxSize(760, 490)*/);
    SetSize(GetMinSize());
#endif
    Layout();
    update_title();
    // declare events
    Bind(wxEVT_CLOSE_WINDOW, [this](wxCloseEvent& event) {
        if (event.CanVeto() && m_plater->canvas3D()->get_gizmos_manager().is_in_editing_mode(true)) {
            // prevents to open the save dirty project dialog
            event.Veto();
            return;
        }
        if (m_plater != nullptr) {
            int saved_project = m_plater->save_project_if_dirty(_L("Closing PrusaSlicer. Current project is modified."));
            if (saved_project == wxID_CANCEL) {
                event.Veto();
                return;
            }
            // check unsaved changes only if project wasn't saved
            else if (plater()->is_project_dirty() && saved_project == wxID_NO && event.CanVeto() &&
                     (plater()->is_presets_dirty() && !wxGetApp().check_and_save_current_preset_changes(_L("PrusaSlicer is closing"), _L("Closing PrusaSlicer while some presets are modified.")))) {
                event.Veto();
                return;
            }
        }
        if (event.CanVeto() && !wxGetApp().check_print_host_queue()) {
            event.Veto();
            return;
        }
        this->shutdown();
        // propagate event
        event.Skip();
    });
    //FIXME it seems this method is not called on application start-up, at least not on Windows. Why?
    // The same applies to wxEVT_CREATE, it is not being called on startup on Windows.
    Bind(wxEVT_ACTIVATE, [this](wxActivateEvent& event) {
        if (m_plater != nullptr && event.GetActive())
            m_plater->on_activate();
        event.Skip();
    });
// OSX specific issue:
// When we move application between Retina and non-Retina displays, The legend on a canvas doesn't redraw
// So, redraw explicitly canvas, when application is moved
//FIXME maybe this is useful for __WXGTK3__ as well?
#if __APPLE__
    Bind(wxEVT_MOVE, [](wxMoveEvent& event) {
        wxGetApp().plater()->get_current_canvas3D()->set_as_dirty();
        wxGetApp().plater()->get_current_canvas3D()->request_extra_frame();
        event.Skip();
    });
#endif
    wxGetApp().persist_window_geometry(this, true);
    wxGetApp().persist_window_geometry(&m_settings_dialog, true);
    update_ui_from_settings();    // FIXME (?)
    if (m_plater != nullptr) {
        m_plater->get_collapse_toolbar().set_enabled(wxGetApp().app_config->get_bool("show_collapse_button"));
        m_plater->show_action_buttons(true);
        preferences_dialog = new PreferencesDialog(this);
    }
    // bind events from DiffDlg
    bind_diff_dialog();
}
References _L, bind_diff_dialog(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GUI_App::Editor, Slic3r::GUI::GUI_App::GCodeViewer, Slic3r::GUI::Plater::get_collapse_toolbar(), Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), if(), init_menubar_as_editor(), init_menubar_as_gcodeviewer(), init_tabpanel(), Slic3r::GUI::GLGizmosManager::is_in_editing_mode(), m_loaded, m_main_sizer, m_plater, m_settings_dialog, Slic3r::GUI::main_frame_icon(), Slic3r::GUI::Plater::on_activate(), plater(), preferences_dialog, Slic3r::GUI::Plater::save_project_if_dirty(), Slic3r::GUI::GLToolbar::set_enabled(), Slic3r::GUI::Plater::show_action_buttons(), shutdown(), update_layout(), update_title(), update_ui_from_settings(), and Slic3r::var().
~MainFrame()
Slic3r::GUI::MainFrame::~MainFrame () default
Member Function Documentation
add_created_tab()
void Slic3r::GUI::MainFrame::add_created_tab (Tab * panel, const std::string & bmp_name = "")
{
    panel->create_preset_tab();
    const auto printer_tech = wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology();
    if (panel->supports_printer_technology(printer_tech))
#ifdef _MSW_DARK_MODE
        if (!wxGetApp().tabs_as_menu())
            dynamic_cast<Notebook*>(m_tabpanel)->AddPage(panel, panel->title(), bmp_name);
        else
#endif
        m_tabpanel->AddPage(panel, panel->title());
}
References Slic3r::GUI::Tab::create_preset_tab(), m_tabpanel, Slic3r::GUI::Tab::supports_printer_technology(), and Slic3r::GUI::Tab::title().
Referenced by create_preset_tabs().
add_to_recent_projects()
void Slic3r::GUI::MainFrame::add_to_recent_projects (const wxString & filename)
{
    if (wxFileExists(filename))
    {
        m_recent_projects.AddFileToHistory(filename);
        std::vector<std::string> recent_projects;
        size_t count = m_recent_projects.GetCount();
        for (size_t i = 0; i < count; ++i)
        {
            recent_projects.push_back(into_u8(m_recent_projects.GetHistoryFile(i)));
        }
        wxGetApp().app_config->set_recent_projects(recent_projects);
    }
}
References Slic3r::GUI::into_u8(), and m_recent_projects.
bind_diff_dialog()
void Slic3r::GUI::MainFrame::bind_diff_dialog () private
{
    auto get_tab = [](Preset::Type type) {
        Tab* null_tab = nullptr;
        for (Tab* tab : wxGetApp().tabs_list)
            if (tab->type() == type)
                return tab;
        return null_tab;
    };
    auto transfer = [this, get_tab](Preset::Type type) {
        get_tab(type)->transfer_options(diff_dialog.get_left_preset_name(type),
                                        diff_dialog.get_right_preset_name(type),
                                        diff_dialog.get_selected_options(type));
    };
    auto update_presets = [this, get_tab](Preset::Type type) {
        get_tab(type)->update_preset_choice();
        m_plater->sidebar().update_presets(type);
    };
    auto process_options = [this](std::function<void(Preset::Type)> process) {
        const Preset::Type diff_dlg_type = diff_dialog.view_type();
        if (diff_dlg_type == Preset::TYPE_INVALID) {
            for (const Preset::Type& type : diff_dialog.types_list() )
                process(type);
        }
        else
            process(diff_dlg_type);
    };
    diff_dialog.Bind(EVT_DIFF_DIALOG_TRANSFER,      [process_options, transfer](SimpleEvent&)         { process_options(transfer); });
    diff_dialog.Bind(EVT_DIFF_DIALOG_UPDATE_PRESETS,[process_options, update_presets](SimpleEvent&)   { process_options(update_presets); });
}
References diff_dialog, Slic3r::GUI::DiffPresetDialog::get_left_preset_name(), Slic3r::GUI::DiffPresetDialog::get_right_preset_name(), Slic3r::GUI::DiffPresetDialog::get_selected_options(), m_plater, Slic3r::GUI::Plater::sidebar(), Slic3r::GUI::Tab::transfer_options(), Slic3r::Preset::TYPE_INVALID, Slic3r::GUI::DiffPresetDialog::types_list(), Slic3r::GUI::Sidebar::update_presets(), Slic3r::GUI::DiffPresetDialog::view_type(), and void().
Referenced by MainFrame().
can_change_view()
bool Slic3r::GUI::MainFrame::can_change_view () const private
{
    switch (m_layout)
    {
    default:                   { return false; }
    case ESettingsLayout::New: { return m_plater->IsShown(); }
    case ESettingsLayout::Dlg: { return true; }
    case ESettingsLayout::Old: {
        int page_id = m_tabpanel->GetSelection();
        return page_id != wxNOT_FOUND && dynamic_cast<const Slic3r::GUI::Plater*>(m_tabpanel->GetPage((size_t)page_id)) != nullptr;
    }
    case ESettingsLayout::GCodeViewer: { return true; }
    }
}
References Dlg, GCodeViewer, m_layout, m_plater, m_tabpanel, New, and Old.
Referenced by Slic3r::GUI::add_common_view_menu_items(), init_menubar_as_editor(), and init_menubar_as_gcodeviewer().
can_delete()
bool Slic3r::GUI::MainFrame::can_delete () const private
{
    return (m_plater != nullptr) && !m_plater->is_selection_empty();
}
References Slic3r::GUI::Plater::is_selection_empty(), and m_plater.
Referenced by init_menubar_as_editor().
can_delete_all()
bool Slic3r::GUI::MainFrame::can_delete_all () const private
{
    return (m_plater != nullptr) && !m_plater->model().objects.empty();
}
References m_plater, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by init_menubar_as_editor().
can_deselect()
bool Slic3r::GUI::MainFrame::can_deselect () const private
{
    return (m_plater != nullptr) && !m_plater->is_selection_empty();
}
References Slic3r::GUI::Plater::is_selection_empty(), and m_plater.
Referenced by init_menubar_as_editor().
can_eject()
bool Slic3r::GUI::MainFrame::can_eject () const private
{
  return wxGetApp().removable_drive_manager()->status().has_eject;
}
Referenced by init_menubar_as_editor().
can_export_gcode()
bool Slic3r::GUI::MainFrame::can_export_gcode () const private
{
    if (m_plater == nullptr)
        return false;
    if (m_plater->model().objects.empty())
        return false;
    if (m_plater->is_export_gcode_scheduled())
        return false;
    // TODO:: add other filters
    return true;
}
References Slic3r::GUI::Plater::is_export_gcode_scheduled(), m_plater, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by init_menubar_as_editor().
can_export_gcode_sd()
bool Slic3r::GUI::MainFrame::can_export_gcode_sd () const private
{
  if (m_plater == nullptr)
    return false;
  if (m_plater->model().objects.empty())
    return false;
  if (m_plater->is_export_gcode_scheduled())
    return false;
  // TODO:: add other filters
  return wxGetApp().removable_drive_manager()->status().has_removable_drives;
}
References Slic3r::GUI::Plater::is_export_gcode_scheduled(), m_plater, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by init_menubar_as_editor().
can_export_model()
bool Slic3r::GUI::MainFrame::can_export_model () const private
{
    return (m_plater != nullptr) && !m_plater->model().objects.empty();
}
References m_plater, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by init_menubar_as_editor().
can_export_supports()
bool Slic3r::GUI::MainFrame::can_export_supports () const private
{
    if ((m_plater == nullptr) || (m_plater->printer_technology() != ptSLA) || m_plater->model().objects.empty())
        return false;
    bool can_export = false;
    const PrintObjects& objects = m_plater->sla_print().objects();
    for (const SLAPrintObject* object : objects)
    {
        if (!object->support_mesh().empty() || !object->pad_mesh().empty())
        {
            can_export = true;
            break;
        }
    }
    return can_export;
}
References m_plater, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::SLAPrint::objects(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptSLA, and Slic3r::GUI::Plater::sla_print().
Referenced by init_menubar_as_editor().
can_export_toolpaths()
bool Slic3r::GUI::MainFrame::can_export_toolpaths () const private
{
    return (m_plater != nullptr) && (m_plater->printer_technology() == ptFFF) && m_plater->is_preview_shown() && m_plater->is_preview_loaded() && m_plater->has_toolpaths_to_export();
}
References Slic3r::GUI::Plater::has_toolpaths_to_export(), Slic3r::GUI::Plater::is_preview_loaded(), Slic3r::GUI::Plater::is_preview_shown(), m_plater, Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptFFF.
Referenced by init_menubar_as_editor(), and init_menubar_as_gcodeviewer().
can_reslice()
bool Slic3r::GUI::MainFrame::can_reslice () const private
{
    return (m_plater != nullptr) && !m_plater->model().objects.empty();
}
References m_plater, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by init_menubar_as_editor().
can_save()
bool Slic3r::GUI::MainFrame::can_save () const
{
    return (m_plater != nullptr) &&
        !m_plater->canvas3D()->get_gizmos_manager().is_in_editing_mode(false) &&
        m_plater->is_project_dirty();
}
References Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmosManager::is_in_editing_mode(), Slic3r::GUI::Plater::is_project_dirty(), and m_plater.
Referenced by init_menubar_as_editor().
can_save_as()
bool Slic3r::GUI::MainFrame::can_save_as () const
{
    return (m_plater != nullptr) &&
        !m_plater->canvas3D()->get_gizmos_manager().is_in_editing_mode(false);
}
References Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmosManager::is_in_editing_mode(), and m_plater.
Referenced by init_menubar_as_editor(), and Slic3r::GUI::Plater::priv::save_project_if_dirty().
can_select()
bool Slic3r::GUI::MainFrame::can_select () const private
{
    return (m_plater != nullptr) && !m_plater->model().objects.empty();
}
References m_plater, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by init_menubar_as_editor().
can_send_gcode()
bool Slic3r::GUI::MainFrame::can_send_gcode () const private
{
    if (m_plater && ! m_plater->model().objects.empty())
        if (const DynamicPrintConfig *cfg = wxGetApp().preset_bundle->physical_printers.get_selected_printer_config(); cfg)
            if (const auto *print_host_opt = cfg->option<ConfigOptionString>("print_host"); print_host_opt)
                return ! print_host_opt->value.empty();
    return false;
}
References m_plater, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by init_menubar_as_editor().
can_slice()
bool Slic3r::GUI::MainFrame::can_slice () const private
{
    bool bg_proc = wxGetApp().app_config->get_bool("background_processing");
    return (m_plater != nullptr) ? !m_plater->model().objects.empty() && !bg_proc : false;
}
References m_plater, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
can_start_new_project()
bool Slic3r::GUI::MainFrame::can_start_new_project () const private
{
    return m_plater && (!m_plater->get_project_filename(".3mf").IsEmpty() ||
                        GetTitle().StartsWith('*')||
                        wxGetApp().has_current_preset_changes() ||
                        !m_plater->model().objects.empty() );
}
References Slic3r::GUI::Plater::get_project_filename(), m_plater, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by init_menubar_as_editor().
create_preset_tabs()
void Slic3r::GUI::MainFrame::create_preset_tabs ()
{
    add_created_tab(new TabPrint(m_tabpanel), "cog");
    add_created_tab(new TabFilament(m_tabpanel), "spool");
    add_created_tab(new TabSLAPrint(m_tabpanel), "cog");
    add_created_tab(new TabSLAMaterial(m_tabpanel), "resin");
    add_created_tab(new TabPrinter(m_tabpanel), wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptFFF ? "printer" : "sla_printer");
}
References add_created_tab(), m_tabpanel, and Slic3r::ptFFF.
Referenced by init_tabpanel().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::FileArchiveDialog::FileArchiveDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::ExtruderSequenceDialog::apply_extruder_sequence(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::DiffPresetDialog::complete_dialog_creation(), Slic3r::GUI::DiffPresetDialog::create_edit_sizer(), Slic3r::GUI::DiffPresetDialog::create_presets_sizer(), Slic3r::GUI::DiffPresetDialog::create_tree(), em_unit(), Slic3r::GUI::SavePresetDialog::Item::init_input_name_ctrl(), Slic3r::Search::SearchDialog::msw_rescale(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigSnapshotDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::FileArchiveDialog::on_dpi_changed(), Slic3r::FirmwareDialog::on_dpi_changed(), Slic3r::GUI::GalleryDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::LoadProjectsDialog::on_dpi_changed(), Slic3r::GUI::ProjectDropDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
Referenced by update_layout().
export_config()
void Slic3r::GUI::MainFrame::export_config ()
{
    // Generate a cummulative configuration for the selected print, filaments and printer.
    auto config = wxGetApp().preset_bundle->full_config();
    // Validate the cummulative configuration.
    auto valid = config.validate();
    if (! valid.empty()) {
        show_error(this, valid);
        return;
    }
    // Ask user for the file name for the config file.
    wxFileDialog dlg(this, _L("Save configuration as:"),
        !m_last_config.IsEmpty() ? get_dir_name(m_last_config) : wxGetApp().app_config->get_last_dir(),
        !m_last_config.IsEmpty() ? get_base_name(m_last_config) : "config.ini",
        file_wildcards(FT_INI), wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
    wxString file;
    if (dlg.ShowModal() == wxID_OK)
        file = dlg.GetPath();
    if (!file.IsEmpty()) {
        wxGetApp().app_config->update_config_dir(get_dir_name(file));
        m_last_config = file;
        config.save(file.ToUTF8().data());
    }
}
References _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_INI, get_base_name(), get_dir_name(), m_last_config, and Slic3r::GUI::show_error().
Referenced by init_menubar_as_editor().
export_configbundle()
void Slic3r::GUI::MainFrame::export_configbundle (bool export_physical_printers = false)
{
    if (!wxGetApp().check_and_save_current_preset_changes(_L("Exporting configuration bundle"),
                                                          _L("Some presets are modified and the unsaved changes will not be exported into configuration bundle."), false, true))
        return;
    // validate current configuration in case it's dirty
    auto err = wxGetApp().preset_bundle->full_config().validate();
    if (! err.empty()) {
        show_error(this, err);
        return;
    }
    // Ask user for a file name.
    wxFileDialog dlg(this, _L("Save presets bundle as:"),
        !m_last_config.IsEmpty() ? get_dir_name(m_last_config) : wxGetApp().app_config->get_last_dir(),
        SLIC3R_APP_KEY "_config_bundle.ini",
        file_wildcards(FT_INI), wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
    wxString file;
    if (dlg.ShowModal() == wxID_OK)
        file = dlg.GetPath();
    if (!file.IsEmpty()) {
        // Export the config bundle.
        wxGetApp().app_config->update_config_dir(get_dir_name(file));
        try {
            wxGetApp().preset_bundle->export_configbundle(file.ToUTF8().data(), false, export_physical_printers);
        } catch (const std::exception &ex) {
      show_error(this, ex.what());
        }
    }
}
References _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_INI, get_dir_name(), m_last_config, and Slic3r::GUI::show_error().
Referenced by init_menubar_as_editor().
gallery_dialog()
GalleryDialog * Slic3r::GUI::MainFrame::gallery_dialog ()
{
    if (!m_gallery_dialog)
        m_gallery_dialog = new GalleryDialog(this);
    return m_gallery_dialog;
}
References m_gallery_dialog.
Referenced by Slic3r::GUI::GUI_App::gallery_dialog(), and init_menubar_as_editor().
get_base_name()
std::string Slic3r::GUI::MainFrame::get_base_name (const wxString & full_name, const char * extension = nullptr) const private
{
    boost::filesystem::path filename = boost::filesystem::path(full_name.wx_str()).filename();
    if (extension != nullptr)
    filename = filename.replace_extension(extension);
    return filename.string();
}
Referenced by export_config(), and repair_stl().
get_dir_name()
std::string Slic3r::GUI::MainFrame::get_dir_name (const wxString & full_name) const private
{
    return boost::filesystem::path(full_name.wx_str()).parent_path().string();
}
Referenced by export_config(), export_configbundle(), load_config_file(), load_configbundle(), and repair_stl().
init_menubar_as_editor()
void Slic3r::GUI::MainFrame::init_menubar_as_editor ()
{
#ifdef __APPLE__
    wxMenuBar::SetAutoWindowMenu(false);
#endif
    // File menu
    wxMenu* fileMenu = new wxMenu;
    {
        append_menu_item(fileMenu, wxID_ANY, _L("&New Project") + "\tCtrl+N", _L("Start a new project"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->new_project(); }, "", nullptr,
            [this](){return m_plater != nullptr && can_start_new_project(); }, this);
        append_menu_item(fileMenu, wxID_ANY, _L("&Open Project") + dots + "\tCtrl+O", _L("Open a project file"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->load_project(); }, "open", nullptr,
            [this](){return m_plater != nullptr; }, this);
        wxMenu* recent_projects_menu = new wxMenu();
        wxMenuItem* recent_projects_submenu = append_submenu(fileMenu, recent_projects_menu, wxID_ANY, _L("Recent projects"), "");
        m_recent_projects.UseMenu(recent_projects_menu);
        Bind(wxEVT_MENU, [this](wxCommandEvent& evt) {
            size_t file_id = evt.GetId() - wxID_FILE1;
            wxString filename = m_recent_projects.GetHistoryFile(file_id);
            if (wxFileExists(filename)) {
                if (wxGetApp().can_load_project())
                    m_plater->load_project(filename);
            }
            else
            {
                //wxMessageDialog msg(this, _L("The selected project is no longer available.\nDo you want to remove it from the recent projects list?"), _L("Error"), wxYES_NO | wxYES_DEFAULT);
                MessageDialog msg(this, _L("The selected project is no longer available.\nDo you want to remove it from the recent projects list?"), _L("Error"), wxYES_NO | wxYES_DEFAULT);
                if (msg.ShowModal() == wxID_YES)
                {
                    m_recent_projects.RemoveFileFromHistory(file_id);
                        std::vector<std::string> recent_projects;
                        size_t count = m_recent_projects.GetCount();
                        for (size_t i = 0; i < count; ++i)
{
                            recent_projects.push_back(into_u8(m_recent_projects.GetHistoryFile(i)));
                        }
                    wxGetApp().app_config->set_recent_projects(recent_projects);
                }
            }
            }, wxID_FILE1, wxID_FILE9);
        std::vector<std::string> recent_projects = wxGetApp().app_config->get_recent_projects();
        std::reverse(recent_projects.begin(), recent_projects.end());
        for (const std::string& project : recent_projects)
        {
            m_recent_projects.AddFileToHistory(from_u8(project));
        }
        Bind(wxEVT_UPDATE_UI, [this](wxUpdateUIEvent& evt) { evt.Enable(m_recent_projects.GetCount() > 0); }, recent_projects_submenu->GetId());
        append_menu_item(fileMenu, wxID_ANY, _L("&Save Project") + "\tCtrl+S", _L("Save current project file"),
            [this](wxCommandEvent&) { save_project(); }, "save", nullptr,
            [this](){return m_plater != nullptr && can_save(); }, this);
#ifdef __APPLE__
        append_menu_item(fileMenu, wxID_ANY, _L("Save Project &as") + dots + "\tCtrl+Shift+S", _L("Save current project file as"),
#else
        append_menu_item(fileMenu, wxID_ANY, _L("Save Project &as") + dots + "\tCtrl+Alt+S", _L("Save current project file as"),
#endif // __APPLE__
            [this](wxCommandEvent&) { save_project_as(); }, "save", nullptr,
            [this](){return m_plater != nullptr && can_save_as(); }, this);
        fileMenu->AppendSeparator();
        wxMenu* import_menu = new wxMenu();
        append_menu_item(import_menu, wxID_ANY, _L("Import STL/3MF/STEP/OBJ/AM&F") + dots + "\tCtrl+I", _L("Load a model"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->add_model(); }, "import_plater", nullptr,
            [this](){return m_plater != nullptr; }, this);
        append_menu_item(import_menu, wxID_ANY, _L("Import STL (Imperial Units)"), _L("Load an model saved with imperial units"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->add_model(true); }, "import_plater", nullptr,
            [this](){return m_plater != nullptr; }, this);
        append_menu_item(import_menu, wxID_ANY, _L("Import SLA Archive") + dots, _L("Load an SLA archive"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->import_sl1_archive(); }, "import_plater", nullptr,
            [this](){return m_plater != nullptr && m_plater->get_ui_job_worker().is_idle(); }, this);
        append_menu_item(import_menu, wxID_ANY, _L("Import ZIP Archive") + dots, _L("Load a ZIP archive"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->import_zip_archive(); }, "import_plater", nullptr,
            [this]() {return m_plater != nullptr; }, this);
        import_menu->AppendSeparator();
        append_menu_item(import_menu, wxID_ANY, _L("Import &Config") + dots + "\tCtrl+L", _L("Load exported configuration file"),
            [this](wxCommandEvent&) { load_config_file(); }, "import_config", nullptr,
            []() {return true; }, this);
        append_menu_item(import_menu, wxID_ANY, _L("Import Config from &Project") + dots +"\tCtrl+Alt+L", _L("Load configuration from project file"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->extract_config_from_project(); }, "import_config", nullptr,
            []() {return true; }, this);
        import_menu->AppendSeparator();
        append_menu_item(import_menu, wxID_ANY, _L("Import Config &Bundle") + dots, _L("Load presets from a bundle"),
            [this](wxCommandEvent&) { load_configbundle(); }, "import_config_bundle", nullptr,
            []() {return true; }, this);
        append_submenu(fileMenu, import_menu, wxID_ANY, _L("&Import"), "");
        wxMenu* export_menu = new wxMenu();
        wxMenuItem* item_export_gcode = append_menu_item(export_menu, wxID_ANY, _L("Export &G-code") + dots + "\tCtrl+G", _L("Export current plate as G-code"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->export_gcode(false); }, "export_gcode", nullptr,
            [this](){return can_export_gcode(); }, this);
        m_changeable_menu_items.push_back(item_export_gcode);
        wxMenuItem* item_send_gcode = append_menu_item(export_menu, wxID_ANY, _L("S&end G-code") + dots + "\tCtrl+Shift+G", _L("Send to print current plate as G-code"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->send_gcode(); }, "export_gcode", nullptr,
            [this](){return can_send_gcode(); }, this);
        m_changeable_menu_items.push_back(item_send_gcode);
    append_menu_item(export_menu, wxID_ANY, _L("Export G-code to SD Card / Flash Drive") + dots + "\tCtrl+U", _L("Export current plate as G-code to SD card / Flash drive"),
      [this](wxCommandEvent&) { if (m_plater) m_plater->export_gcode(true); }, "export_to_sd", nullptr,
      [this]() {return can_export_gcode_sd(); }, this);
        export_menu->AppendSeparator();
        append_menu_item(export_menu, wxID_ANY, _L("Export Plate as &STL/OBJ") + dots, _L("Export current plate as STL/OBJ"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->export_stl_obj(); }, "export_plater", nullptr,
            [this](){return can_export_model(); }, this);
        append_menu_item(export_menu, wxID_ANY, _L("Export Plate as STL/OBJ &Including Supports") + dots, _L("Export current plate as STL/OBJ including supports"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->export_stl_obj(true); }, "export_plater", nullptr,
            [this](){return can_export_supports(); }, this);
// Deprecating AMF export. Let's wait for user feedback.
//        append_menu_item(export_menu, wxID_ANY, _L("Export Plate as &AMF") + dots, _L("Export current plate as AMF"),
//            [this](wxCommandEvent&) { if (m_plater) m_plater->export_amf(); }, "export_plater", nullptr,
//            [this](){return can_export_model(); }, this);
        export_menu->AppendSeparator();
        append_menu_item(export_menu, wxID_ANY, _L("Export &Toolpaths as OBJ") + dots, _L("Export toolpaths as OBJ"),
            [this](wxCommandEvent&) { if (m_plater) m_plater->export_toolpaths_to_obj(); }, "export_plater", nullptr,
            [this]() {return can_export_toolpaths(); }, this);
        export_menu->AppendSeparator();
        append_menu_item(export_menu, wxID_ANY, _L("Export &Config") + dots +"\tCtrl+E", _L("Export current configuration to file"),
            [this](wxCommandEvent&) { export_config(); }, "export_config", nullptr,
            []() {return true; }, this);
        append_menu_item(export_menu, wxID_ANY, _L("Export Config &Bundle") + dots, _L("Export all presets to file"),
            [this](wxCommandEvent&) { export_configbundle(); }, "export_config_bundle", nullptr,
            []() {return true; }, this);
        append_menu_item(export_menu, wxID_ANY, _L("Export Config Bundle With Physical Printers") + dots, _L("Export all presets including physical printers to file"),
            [this](wxCommandEvent&) { export_configbundle(true); }, "export_config_bundle", nullptr,
            []() {return true; }, this);
        append_submenu(fileMenu, export_menu, wxID_ANY, _L("&Export"), "");
    append_menu_item(fileMenu, wxID_ANY, _L("Ejec&t SD Card / Flash Drive") + dots + "\tCtrl+T", _L("Eject SD card / Flash drive after the G-code was exported to it."),
      [this](wxCommandEvent&) { if (m_plater) m_plater->eject_drive(); }, "eject_sd", nullptr,
      [this]() {return can_eject(); }, this);
        fileMenu->AppendSeparator();
#if 0
        m_menu_item_repeat = nullptr;
        append_menu_item(fileMenu, wxID_ANY, _L("Quick Slice") +dots+ "\tCtrl+U", _L("Slice a file into a G-code"),
            [this](wxCommandEvent&) {
                wxTheApp->CallAfter([this]() {
                    quick_slice();
                    m_menu_item_repeat->Enable(is_last_input_file());
                }); }, "cog_go.png");
        append_menu_item(fileMenu, wxID_ANY, _L("Quick Slice and Save As") +dots +"\tCtrl+Alt+U", _L("Slice a file into a G-code, save as"),
            [this](wxCommandEvent&) {
            wxTheApp->CallAfter([this]() {
                    quick_slice(qsSaveAs);
                    m_menu_item_repeat->Enable(is_last_input_file());
                }); }, "cog_go.png");
        m_menu_item_repeat = append_menu_item(fileMenu, wxID_ANY, _L("Repeat Last Quick Slice") +"\tCtrl+Shift+U", _L("Repeat last quick slice"),
            [this](wxCommandEvent&) {
            wxTheApp->CallAfter([this]() {
                quick_slice(qsReslice);
            }); }, "cog_go.png");
        m_menu_item_repeat->Enable(false);
        fileMenu->AppendSeparator();
#endif
        m_menu_item_reslice_now = append_menu_item(fileMenu, wxID_ANY, _L("(Re)Slice No&w") + "\tCtrl+R", _L("Start new slicing process"),
            [this](wxCommandEvent&) { reslice_now(); }, "re_slice", nullptr,
            [this]() { return m_plater != nullptr && can_reslice(); }, this);
        fileMenu->AppendSeparator();
        append_menu_item(fileMenu, wxID_ANY, _L("&Repair STL file") + dots, _L("Automatically repair an STL file"),
            [this](wxCommandEvent&) { repair_stl(); }, "wrench", nullptr,
            []() { return true; }, this);
        fileMenu->AppendSeparator();
        append_menu_item(fileMenu, wxID_ANY, _L("&G-code Preview") + dots, _L("Open G-code viewer"),
            [this](wxCommandEvent&) { start_new_gcodeviewer_open_file(this); }, "", nullptr);
        fileMenu->AppendSeparator();
        #ifdef _WIN32
            append_menu_item(fileMenu, wxID_EXIT, _L("E&xit"), wxString::Format(_L("Exit %s"), SLIC3R_APP_NAME),
        #else
            append_menu_item(fileMenu, wxID_EXIT, _L("&Quit"), wxString::Format(_L("Quit %s"), SLIC3R_APP_NAME),
        #endif
            [this](wxCommandEvent&) { Close(false); }, "exit");
    }
    // Edit menu
    wxMenu* editMenu = nullptr;
    if (m_plater != nullptr)
    {
        editMenu = new wxMenu();
    #ifdef __APPLE__
        // Backspace sign
        wxString hotkey_delete = "\u232b";
    #else
        wxString hotkey_delete = "Del";
    #endif
        append_menu_item(editMenu, wxID_ANY, _L("&Select All") + sep + GUI::shortkey_ctrl_prefix() + sep_space + "A",
            _L("Selects all objects"), [this](wxCommandEvent&) { m_plater->select_all(); },
            "", nullptr, [this](){return can_select(); }, this);
        append_menu_item(editMenu, wxID_ANY, _L("D&eselect All") + sep + "Esc",
            _L("Deselects all objects"), [this](wxCommandEvent&) { m_plater->deselect_all(); },
            "", nullptr, [this](){return can_deselect(); }, this);
        editMenu->AppendSeparator();
        append_menu_item(editMenu, wxID_ANY, _L("&Delete Selected") + sep + hotkey_delete,
            _L("Deletes the current selection"),[this](wxCommandEvent&) { m_plater->remove_selected(); },
            "remove_menu", nullptr, [this](){return can_delete(); }, this);
        append_menu_item(editMenu, wxID_ANY, _L("Delete &All") + sep + GUI::shortkey_ctrl_prefix() + sep_space + hotkey_delete,
            _L("Deletes all objects"), [this](wxCommandEvent&) { m_plater->reset_with_confirm(); },
            "delete_all_menu", nullptr, [this](){return can_delete_all(); }, this);
        editMenu->AppendSeparator();
        append_menu_item(editMenu, wxID_ANY, _L("&Undo") + sep + GUI::shortkey_ctrl_prefix() + sep_space + "Z",
            _L("Undo"), [this](wxCommandEvent&) { m_plater->undo(); },
            "undo_menu", nullptr, [this](){return m_plater->can_undo(); }, this);
        append_menu_item(editMenu, wxID_ANY, _L("&Redo") + sep + GUI::shortkey_ctrl_prefix() + sep_space + "Y",
            _L("Redo"), [this](wxCommandEvent&) { m_plater->redo(); },
            "redo_menu", nullptr, [this](){return m_plater->can_redo(); }, this);
        editMenu->AppendSeparator();
        append_menu_item(editMenu, wxID_ANY, _L("&Copy") + sep + GUI::shortkey_ctrl_prefix() + sep_space + "C",
            _L("Copy selection to clipboard"), [this](wxCommandEvent&) { m_plater->copy_selection_to_clipboard(); },
            "copy_menu", nullptr, [this](){return m_plater->can_copy_to_clipboard(); }, this);
        append_menu_item(editMenu, wxID_ANY, _L("&Paste") + sep + GUI::shortkey_ctrl_prefix() + sep_space + "V",
            _L("Paste clipboard"), [this](wxCommandEvent&) { m_plater->paste_from_clipboard(); },
            "paste_menu", nullptr, [this](){return m_plater->can_paste_from_clipboard(); }, this);
        editMenu->AppendSeparator();
#ifdef __APPLE__
        append_menu_item(editMenu, wxID_ANY, _L("Re&load from Disk") + dots + "\tCtrl+Shift+R",
            _L("Reload the plater from disk"), [this](wxCommandEvent&) { m_plater->reload_all_from_disk(); },
            "", nullptr, [this]() {return !m_plater->model().objects.empty(); }, this);
#else
        append_menu_item(editMenu, wxID_ANY, _L("Re&load from Disk") + sep + "F5",
            _L("Reload the plater from disk"), [this](wxCommandEvent&) { m_plater->reload_all_from_disk(); },
            "", nullptr, [this]() {return !m_plater->model().objects.empty(); }, this);
#endif // __APPLE__
        editMenu->AppendSeparator();
        append_menu_item(editMenu, wxID_ANY, _L("Searc&h") + "\tCtrl+F",
            _L("Search in settings"), [this](wxCommandEvent&) { m_plater->search(m_plater->IsShown()); },
            "search", nullptr, []() {return true; }, this);
    }
    // Window menu
    auto windowMenu = new wxMenu();
    {
        if (m_plater) {
            append_menu_item(windowMenu, wxID_HIGHEST + 1, _L("&Plater Tab") + "\tCtrl+1", _L("Show the plater"),
                [this](wxCommandEvent&) { select_tab(size_t(0)); }, "plater", nullptr,
                []() {return true; }, this);
            windowMenu->AppendSeparator();
        }
        append_menu_item(windowMenu, wxID_HIGHEST + 2, _L("P&rint Settings Tab") + "\tCtrl+2", _L("Show the print settings"),
            [this/*, tab_offset*/](wxCommandEvent&) { select_tab(1); }, "cog", nullptr,
            []() {return true; }, this);
        wxMenuItem* item_material_tab = append_menu_item(windowMenu, wxID_HIGHEST + 3, _L("&Filament Settings Tab") + "\tCtrl+3", _L("Show the filament settings"),
            [this/*, tab_offset*/](wxCommandEvent&) { select_tab(2); }, "spool", nullptr,
            []() {return true; }, this);
        m_changeable_menu_items.push_back(item_material_tab);
        wxMenuItem* item_printer_tab = append_menu_item(windowMenu, wxID_HIGHEST + 4, _L("Print&er Settings Tab") + "\tCtrl+4", _L("Show the printer settings"),
            [this/*, tab_offset*/](wxCommandEvent&) { select_tab(3); }, "printer", nullptr,
            []() {return true; }, this);
        m_changeable_menu_items.push_back(item_printer_tab);
        if (m_plater) {
            windowMenu->AppendSeparator();
            append_menu_item(windowMenu, wxID_HIGHEST + 5, _L("3&D") + "\tCtrl+5", _L("Show the 3D editing view"),
                [this](wxCommandEvent&) { m_plater->select_view_3D("3D"); }, "editor_menu", nullptr,
                [this](){return can_change_view(); }, this);
            append_menu_item(windowMenu, wxID_HIGHEST + 6, _L("Pre&view") + "\tCtrl+6", _L("Show the 3D slices preview"),
                [this](wxCommandEvent&) { m_plater->select_view_3D("Preview"); }, "preview_menu", nullptr,
                [this](){return can_change_view(); }, this);
        }
        windowMenu->AppendSeparator();
        append_menu_item(windowMenu, wxID_ANY, _L("Shape Gallery"), _L("Open the dialog to modify shape gallery"),
            [this](wxCommandEvent&) {
                if (gallery_dialog()->show(true) == wxID_OK) {
                    wxArrayString input_files;
                    m_gallery_dialog->get_input_files(input_files);
                    if (!input_files.IsEmpty())
                        m_plater->sidebar().obj_list()->load_shape_object_from_gallery(input_files);
                }
            }, "shape_gallery", nullptr, []() {return true; }, this);
        windowMenu->AppendSeparator();
        append_menu_item(windowMenu, wxID_ANY, _L("Print &Host Upload Queue") + "\tCtrl+J", _L("Display the Print Host Upload Queue window"),
            [this](wxCommandEvent&) { m_printhost_queue_dlg->Show(); }, "upload_queue", nullptr, []() {return true; }, this);
        windowMenu->AppendSeparator();
        append_menu_item(windowMenu, wxID_ANY, _L("Open New Instance") + "\tCtrl+Shift+I", _L("Open a new PrusaSlicer instance"),
            [](wxCommandEvent&) { start_new_slicer(); }, "", nullptr, [this]() {return m_plater != nullptr && !wxGetApp().app_config->get_bool("single_instance"); }, this);
        windowMenu->AppendSeparator();
        append_menu_item(windowMenu, wxID_ANY, _L("Compare Presets")/* + "\tCtrl+F"*/, _L("Compare presets"),
            [this](wxCommandEvent&) { diff_dialog.show();}, "compare", nullptr, []() {return true; }, this);
    }
    // View menu
    wxMenu* viewMenu = nullptr;
    if (m_plater) {
        viewMenu = new wxMenu();
        add_common_view_menu_items(viewMenu, this, std::bind(&MainFrame::can_change_view, this));
        viewMenu->AppendSeparator();
        append_menu_check_item(viewMenu, wxID_ANY, _L("Show &Labels") + sep + "E", _L("Show object/instance labels in 3D scene"),
            [this](wxCommandEvent&) { m_plater->show_view3D_labels(!m_plater->are_view3D_labels_shown()); }, this,
            [this]() { return m_plater->is_view3D_shown(); }, [this]() { return m_plater->are_view3D_labels_shown(); }, this);
        append_menu_check_item(viewMenu, wxID_ANY, _L("Show Legen&d") + sep + "L", _L("Show legend in preview"),
            [this](wxCommandEvent&) { m_plater->show_legend(!m_plater->is_legend_shown()); }, this,
            [this]() { return m_plater->is_preview_shown(); }, [this]() { return m_plater->is_legend_shown(); }, this);
        append_menu_check_item(viewMenu, wxID_ANY, _L("&Collapse Sidebar") + sep + "Shift+" + sep_space + "Tab", _L("Collapse sidebar"),
            [this](wxCommandEvent&) { m_plater->collapse_sidebar(!m_plater->is_sidebar_collapsed()); }, this,
            []() { return true; }, [this]() { return m_plater->is_sidebar_collapsed(); }, this);
#ifndef __APPLE__
        // OSX adds its own menu item to toggle fullscreen.
        append_menu_check_item(viewMenu, wxID_ANY, _L("&Fullscreen") + "\t" + "F11", _L("Fullscreen"),
            [this](wxCommandEvent&) { this->ShowFullScreen(!this->IsFullScreen(),
                // wxFULLSCREEN_ALL: wxFULLSCREEN_NOMENUBAR | wxFULLSCREEN_NOTOOLBAR | wxFULLSCREEN_NOSTATUSBAR | wxFULLSCREEN_NOBORDER | wxFULLSCREEN_NOCAPTION
                wxFULLSCREEN_NOSTATUSBAR | wxFULLSCREEN_NOBORDER | wxFULLSCREEN_NOCAPTION); },
            this, []() { return true; }, [this]() { return this->IsFullScreen(); }, this);
#endif // __APPLE__
    }
    // Help menu
    auto helpMenu = generate_help_menu();
    // menubar
    // assign menubar to frame after appending items, otherwise special items
    // will not be handled correctly
    m_menubar = new wxMenuBar();
    m_menubar->SetFont(this->normal_font());
    m_menubar->Append(fileMenu, _L("&File"));
    if (editMenu) m_menubar->Append(editMenu, _L("&Edit"));
    m_menubar->Append(windowMenu, _L("&Window"));
    if (viewMenu) m_menubar->Append(viewMenu, _L("&View"));
    // Add additional menus from C++
    wxGetApp().add_config_menu(m_menubar);
    m_menubar->Append(helpMenu, _L("&Help"));
#ifdef _MSW_DARK_MODE
    if (wxGetApp().tabs_as_menu()) {
        // Add separator
        m_menubar->Append(new wxMenu(), "          ");
        add_tabs_as_menu(m_menubar, this, this);
    }
#endif
    SetMenuBar(m_menubar);
#ifdef _MSW_DARK_MODE
    if (wxGetApp().tabs_as_menu())
        m_menubar->EnableTop(6, false);
#endif
#ifdef __APPLE__
    // This fixes a bug on Mac OS where the quit command doesn't emit window close events
    // wx bug: https://trac.wxwidgets.org/ticket/18328
    wxMenu* apple_menu = m_menubar->OSXGetAppleMenu();
    if (apple_menu != nullptr) {
        apple_menu->Bind(wxEVT_MENU, [this](wxCommandEvent &) {
            Close();
        }, wxID_EXIT);
    }
#endif // __APPLE__
    if (plater()->printer_technology() == ptSLA)
        update_menubar();
}
References _L, Slic3r::GUI::add_common_view_menu_items(), Slic3r::GUI::Plater::add_model(), append_menu_check_item(), append_menu_item(), append_submenu(), Slic3r::GUI::Plater::are_view3D_labels_shown(), can_change_view(), Slic3r::GUI::Plater::can_copy_to_clipboard(), can_delete(), can_delete_all(), can_deselect(), can_eject(), can_export_gcode(), can_export_gcode_sd(), can_export_model(), can_export_supports(), can_export_toolpaths(), Slic3r::GUI::Plater::can_paste_from_clipboard(), Slic3r::GUI::Plater::can_redo(), can_reslice(), can_save(), can_save_as(), can_select(), can_send_gcode(), can_start_new_project(), Slic3r::GUI::Plater::can_undo(), Slic3r::GUI::Plater::collapse_sidebar(), Slic3r::GUI::Plater::copy_selection_to_clipboard(), Slic3r::GUI::Plater::deselect_all(), diff_dialog, Slic3r::GUI::dots(), Slic3r::GUI::Plater::eject_drive(), export_config(), export_configbundle(), Slic3r::GUI::Plater::export_gcode(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::GUI::Plater::export_toolpaths_to_obj(), Slic3r::GUI::Plater::extract_config_from_project(), Slic3r::GUI::from_u8(), gallery_dialog(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::GalleryDialog::get_input_files(), Slic3r::GUI::Plater::get_ui_job_worker(), Slic3r::GUI::Plater::import_sl1_archive(), Slic3r::GUI::Plater::import_zip_archive(), Slic3r::GUI::into_u8(), Slic3r::GUI::Worker::is_idle(), is_last_input_file(), Slic3r::GUI::Plater::is_legend_shown(), Slic3r::GUI::Plater::is_preview_shown(), Slic3r::GUI::Plater::is_sidebar_collapsed(), Slic3r::GUI::Plater::is_view3D_shown(), load_config_file(), load_configbundle(), Slic3r::GUI::Plater::load_project(), Slic3r::GUI::ObjectList::load_shape_object_from_gallery(), m_changeable_menu_items, m_gallery_dialog, m_menu_item_reslice_now, m_menubar, m_plater, m_printhost_queue_dlg, m_recent_projects, Slic3r::GUI::Plater::model(), Slic3r::GUI::Plater::new_project(), Slic3r::GUI::DPIAware< P >::normal_font(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, Slic3r::GUI::Plater::paste_from_clipboard(), plater(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptSLA, Slic3r::GUI::qsReslice, Slic3r::GUI::qsSaveAs, Slic3r::GUI::Plater::redo(), Slic3r::GUI::Plater::reload_all_from_disk(), Slic3r::GUI::Plater::remove_selected(), repair_stl(), Slic3r::GUI::Plater::reset_with_confirm(), reslice_now(), save_project(), save_project_as(), Slic3r::GUI::Plater::search(), Slic3r::GUI::Plater::select_all(), select_tab(), Slic3r::GUI::Plater::select_view_3D(), Slic3r::GUI::Plater::send_gcode(), Slic3r::GUI::sep, Slic3r::GUI::sep_space, Slic3r::GUI::shortkey_ctrl_prefix(), Slic3r::GUI::PrintHostQueueDialog::Show(), Slic3r::GUI::DiffPresetDialog::show(), Slic3r::GUI::Plater::show_legend(), Slic3r::GUI::Plater::show_view3D_labels(), Slic3r::GUI::Plater::sidebar(), Slic3r::GUI::start_new_gcodeviewer_open_file(), Slic3r::GUI::start_new_slicer(), Slic3r::GUI::Plater::undo(), and update_menubar().
Referenced by MainFrame().
init_menubar_as_gcodeviewer()
void Slic3r::GUI::MainFrame::init_menubar_as_gcodeviewer ()
{
    wxMenu* fileMenu = new wxMenu;
    {
        append_menu_item(fileMenu, wxID_ANY, _L("&Open G-code") + dots + "\tCtrl+O", _L("Open a G-code file"),
            [this](wxCommandEvent&) { if (m_plater != nullptr) m_plater->load_gcode(); }, "open", nullptr,
            [this]() {return m_plater != nullptr; }, this);
#ifdef __APPLE__
        append_menu_item(fileMenu, wxID_ANY, _L("Re&load from Disk") + dots + "\tCtrl+Shift+R",
            _L("Reload the plater from disk"), [this](wxCommandEvent&) { m_plater->reload_gcode_from_disk(); },
            "", nullptr, [this]() { return !m_plater->get_last_loaded_gcode().empty(); }, this);
#else
        append_menu_item(fileMenu, wxID_ANY, _L("Re&load from Disk") + sep + "F5",
            _L("Reload the plater from disk"), [this](wxCommandEvent&) { m_plater->reload_gcode_from_disk(); },
            "", nullptr, [this]() { return !m_plater->get_last_loaded_gcode().empty(); }, this);
#endif // __APPLE__
        fileMenu->AppendSeparator();
        append_menu_item(fileMenu, wxID_ANY, _L("Export &Toolpaths as OBJ") + dots, _L("Export toolpaths as OBJ"),
            [this](wxCommandEvent&) { if (m_plater != nullptr) m_plater->export_toolpaths_to_obj(); }, "export_plater", nullptr,
            [this]() {return can_export_toolpaths(); }, this);
        append_menu_item(fileMenu, wxID_ANY, _L("Open &PrusaSlicer") + dots, _L("Open PrusaSlicer"),
            [](wxCommandEvent&) { start_new_slicer(); }, "", nullptr,
            []() {return true; }, this);
        fileMenu->AppendSeparator();
        append_menu_item(fileMenu, wxID_EXIT, _L("&Quit"), wxString::Format(_L("Quit %s"), SLIC3R_APP_NAME),
            [this](wxCommandEvent&) { Close(false); });
    }
    // View menu
    wxMenu* viewMenu = nullptr;
    if (m_plater != nullptr) {
        viewMenu = new wxMenu();
        add_common_view_menu_items(viewMenu, this, std::bind(&MainFrame::can_change_view, this));
        viewMenu->AppendSeparator();
        append_menu_check_item(viewMenu, wxID_ANY, _L("Show Legen&d") + sep + "L", _L("Show legend"),
            [this](wxCommandEvent&) { m_plater->show_legend(!m_plater->is_legend_shown()); }, this,
            [this]() { return m_plater->is_preview_shown(); }, [this]() { return m_plater->is_legend_shown(); }, this);
    }
    // helpmenu
    auto helpMenu = generate_help_menu();
    m_menubar = new wxMenuBar();
    m_menubar->Append(fileMenu, _L("&File"));
    if (viewMenu != nullptr) m_menubar->Append(viewMenu, _L("&View"));
    // Add additional menus from C++
    wxGetApp().add_config_menu(m_menubar);
    m_menubar->Append(helpMenu, _L("&Help"));
    SetMenuBar(m_menubar);
#ifdef __APPLE__
    // This fixes a bug on Mac OS where the quit command doesn't emit window close events
    // wx bug: https://trac.wxwidgets.org/ticket/18328
    wxMenu* apple_menu = m_menubar->OSXGetAppleMenu();
    if (apple_menu != nullptr) {
        apple_menu->Bind(wxEVT_MENU, [this](wxCommandEvent&) {
            Close();
            }, wxID_EXIT);
    }
#endif // __APPLE__
}
References _L, Slic3r::GUI::add_common_view_menu_items(), append_menu_check_item(), append_menu_item(), can_change_view(), can_export_toolpaths(), Slic3r::GUI::dots(), Slic3r::GUI::Plater::export_toolpaths_to_obj(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Plater::get_last_loaded_gcode(), Slic3r::GUI::Plater::is_legend_shown(), Slic3r::GUI::Plater::is_preview_shown(), Slic3r::GUI::Plater::load_gcode(), m_menubar, m_plater, Slic3r::GUI::Plater::reload_gcode_from_disk(), Slic3r::GUI::sep, Slic3r::GUI::Plater::show_legend(), and Slic3r::GUI::start_new_slicer().
Referenced by MainFrame().
init_tabpanel()
void Slic3r::GUI::MainFrame::init_tabpanel ()
{
    wxGetApp().update_ui_colours_from_appconfig();
    // wxNB_NOPAGETHEME: Disable Windows Vista theme for the Notebook background. The theme performance is terrible on Windows 10
    // with multiple high resolution displays connected.
#ifdef _MSW_DARK_MODE
    if (wxGetApp().tabs_as_menu()) {
        m_tabpanel = new wxSimplebook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_TOP | wxTAB_TRAVERSAL | wxNB_NOPAGETHEME);
        wxGetApp().UpdateDarkUI(m_tabpanel);
    }
    else
        m_tabpanel = new Notebook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_TOP | wxTAB_TRAVERSAL | wxNB_NOPAGETHEME, true);
#else
    m_tabpanel = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_TOP | wxTAB_TRAVERSAL | wxNB_NOPAGETHEME);
#endif
#ifndef __WXOSX__ // Don't call SetFont under OSX to avoid name cutting in ObjectList
    m_tabpanel->SetFont(Slic3r::GUI::wxGetApp().normal_font());
#endif
    m_tabpanel->Hide();
    m_settings_dialog.set_tabpanel(m_tabpanel);
#ifdef __WXMSW__
    m_tabpanel->Bind(wxEVT_BOOKCTRL_PAGE_CHANGED, [this](wxBookCtrlEvent& e) {
#else
    m_tabpanel->Bind(wxEVT_NOTEBOOK_PAGE_CHANGED, [this](wxBookCtrlEvent& e) {
#endif
        if (int old_selection = e.GetOldSelection();
            old_selection != wxNOT_FOUND && old_selection < static_cast<int>(m_tabpanel->GetPageCount())) {
            Tab* old_tab = dynamic_cast<Tab*>(m_tabpanel->GetPage(old_selection));
            if (old_tab)
                old_tab->validate_custom_gcodes();
        }
        wxWindow* panel = m_tabpanel->GetCurrentPage();
        Tab* tab = dynamic_cast<Tab*>(panel);
        // There shouldn't be a case, when we try to select a tab, which doesn't support a printer technology
        if (panel == nullptr || (tab != nullptr && !tab->supports_printer_technology(m_plater->printer_technology())))
            return;
        auto& tabs_list = wxGetApp().tabs_list;
        if (tab && std::find(tabs_list.begin(), tabs_list.end(), tab) != tabs_list.end()) {
            // On GTK, the wxEVT_NOTEBOOK_PAGE_CHANGED event is triggered
            // before the MainFrame is fully set up.
            tab->OnActivate();
            m_last_selected_tab = m_tabpanel->GetSelection();
#ifdef _MSW_DARK_MODE
            if (wxGetApp().tabs_as_menu())
                tab->SetFocus();
#endif
        }
        else
            select_tab(size_t(0)); // select Plater
    });
    m_plater = new Plater(this, this);
    m_plater->Hide();
    wxGetApp().plater_ = m_plater;
    if (wxGetApp().is_editor())
        create_preset_tabs();
    if (m_plater) {
        // load initial config
        auto full_config = wxGetApp().preset_bundle->full_config();
        m_plater->on_config_change(full_config);
        // Show a correct number of filament fields.
        // nozzle_diameter is undefined when SLA printer is selected
        if (full_config.has("nozzle_diameter")) {
            m_plater->on_extruders_change(full_config.option<ConfigOptionFloats>("nozzle_diameter")->values.size());
        }
    }
}
References create_preset_tabs(), error, m_last_selected_tab, m_plater, m_settings_dialog, m_tabpanel, Slic3r::GUI::DPIAware< P >::normal_font(), Slic3r::GUI::Plater::on_config_change(), Slic3r::GUI::Plater::on_extruders_change(), Slic3r::GUI::Tab::OnActivate(), Slic3r::GUI::Plater::printer_technology(), register_win32_callbacks(), select_tab(), Slic3r::GUI::SettingsDialog::set_tabpanel(), Slic3r::GUI::Tab::supports_printer_technology(), TRUE, Slic3r::GUI::Tab::validate_custom_gcodes(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by MainFrame().
is_active_and_shown_tab()
bool Slic3r::GUI::MainFrame::is_active_and_shown_tab (Tab * tab)
{
    int page_id = m_tabpanel->FindPage(tab);
    if (m_tabpanel->GetSelection() != page_id)
        return false;
    if (m_layout == ESettingsLayout::Dlg)
        return m_settings_dialog.IsShown();
    if (m_layout == ESettingsLayout::New)
        return m_main_sizer->IsShown(m_tabpanel);
    return true;
}
References Dlg, m_layout, m_main_sizer, m_settings_dialog, m_tabpanel, and New.
is_dlg_layout()
bool Slic3r::GUI::MainFrame::is_dlg_layout () const inline
{ return m_layout == ESettingsLayout::Dlg; }
References Dlg, and m_layout.
Referenced by Slic3r::GUI::GUI_App::update_ui_from_settings().
is_last_input_file()
bool Slic3r::GUI::MainFrame::is_last_input_file () const inline
{ return !m_qs_last_input_file.IsEmpty(); }
References m_qs_last_input_file.
Referenced by init_menubar_as_editor().
is_loaded()
bool Slic3r::GUI::MainFrame::is_loaded () const inline
{ return m_loaded; }
References m_loaded.
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
load_config()
void Slic3r::GUI::MainFrame::load_config (const DynamicPrintConfig & config)
{
  PrinterTechnology printer_technology = wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology();
  const auto       *opt_printer_technology = config.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
  if (opt_printer_technology != nullptr && opt_printer_technology->value != printer_technology) {
    printer_technology = opt_printer_technology->value;
    this->plater()->set_printer_technology(printer_technology);
  }
#if 0
  for (auto tab : wxGetApp().tabs_list)
    if (tab->supports_printer_technology(printer_technology)) {
      if (tab->type() == Slic3r::Preset::TYPE_PRINTER)
        static_cast<TabPrinter*>(tab)->update_pages();
      tab->load_config(config);
    }
    if (m_plater)
        m_plater->on_config_change(config);
#else
  // Load the currently selected preset into the GUI, update the preset selection box.
    //FIXME this is not quite safe for multi-extruder printers,
    // as the number of extruders is not adjusted for the vector values.
    // (see PresetBundle::update_multi_material_filament_presets())
    // Better to call PresetBundle::load_config() instead?
    for (auto tab : wxGetApp().tabs_list)
        if (tab->supports_printer_technology(printer_technology)) {
            // Only apply keys, which are present in the tab's config. Ignore the other keys.
      for (const std::string &opt_key : tab->get_config()->diff(config))
        // Ignore print_settings_id, printer_settings_id, filament_settings_id etc.
        if (! boost::algorithm::ends_with(opt_key, "_settings_id"))
          tab->get_config()->option(opt_key)->set(config.option(opt_key));
        }
    wxGetApp().load_current_presets();
#endif
}
References m_plater, Slic3r::GUI::Plater::on_config_change(), Slic3r::ConfigBase::option(), plater(), Slic3r::GUI::printer_technology(), Slic3r::GUI::Plater::set_printer_technology(), Slic3r::Preset::TYPE_PRINTER, and Slic3r::GUI::TabPrinter::update_pages().
Referenced by Slic3r::GUI::GUI_App::post_init().
load_config_file() [1/2]
void Slic3r::GUI::MainFrame::load_config_file ()
{
    if (!wxGetApp().check_and_save_current_preset_changes(_L("Loading of a configuration file"), "", false))
        return;
    wxFileDialog dlg(this, _L("Select configuration to load:"),
        !m_last_config.IsEmpty() ? get_dir_name(m_last_config) : wxGetApp().app_config->get_last_dir(),
        "config.ini", "INI files (*.ini, *.gcode)|*.ini;*.INI;*.gcode;*.g", wxFD_OPEN | wxFD_FILE_MUST_EXIST);
  wxString file;
    if (dlg.ShowModal() == wxID_OK)
        file = dlg.GetPath();
    if (! file.IsEmpty() && this->load_config_file(file.ToUTF8().data())) {
        wxGetApp().app_config->update_config_dir(get_dir_name(file));
        m_last_config = file;
    }
}
References _L, get_dir_name(), load_config_file(), and m_last_config.
Referenced by init_menubar_as_editor(), load_config_file(), and Slic3r::GUI::GUI_App::post_init().
load_config_file() [2/2]
bool Slic3r::GUI::MainFrame::load_config_file (const std::string & path)
{
    try {
        ConfigSubstitutions config_substitutions = wxGetApp().preset_bundle->load_config_file(path, ForwardCompatibilitySubstitutionRule::Enable);
        if (!config_substitutions.empty())
            show_substitutions_info(config_substitutions, path);
    } catch (const std::exception &ex) {
        show_error(this, ex.what());
        return false;
    }
    m_plater->check_selected_presets_visibility(ptFFF);
    wxGetApp().load_current_presets();
    return true;
}
References Slic3r::GUI::Plater::check_selected_presets_visibility(), Slic3r::Enable, m_plater, Slic3r::ptFFF, Slic3r::GUI::show_error(), and Slic3r::GUI::show_substitutions_info().
load_configbundle()
void Slic3r::GUI::MainFrame::load_configbundle (wxString file = wxEmptyString)
{
    if (!wxGetApp().check_and_save_current_preset_changes(_L("Loading of a configuration bundle"), "", false))
        return;
    if (file.IsEmpty()) {
        wxFileDialog dlg(this, _L("Select configuration to load:"),
            !m_last_config.IsEmpty() ? get_dir_name(m_last_config) : wxGetApp().app_config->get_last_dir(),
            "config.ini", file_wildcards(FT_INI), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
        if (dlg.ShowModal() != wxID_OK)
            return;
        file = dlg.GetPath();
  }
    wxGetApp().app_config->update_config_dir(get_dir_name(file));
    size_t presets_imported = 0;
    PresetsConfigSubstitutions config_substitutions;
    try {
        // Report all substitutions.
        std::tie(config_substitutions, presets_imported) = wxGetApp().preset_bundle->load_configbundle(
            file.ToUTF8().data(), PresetBundle::LoadConfigBundleAttribute::SaveImported, ForwardCompatibilitySubstitutionRule::Enable);
    } catch (const std::exception &ex) {
        show_error(this, ex.what());
        return;
    }
    if (! config_substitutions.empty())
        show_substitutions_info(config_substitutions);
    // Load the currently selected preset into the GUI, update the preset selection box.
  wxGetApp().load_current_presets();
    const auto message = wxString::Format(_L("%d presets successfully imported."), presets_imported);
    Slic3r::GUI::show_info(this, message, wxString("Info"));
}
References _L, Slic3r::Enable, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_INI, get_dir_name(), m_last_config, Slic3r::PresetBundle::SaveImported, Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), and Slic3r::GUI::show_substitutions_info().
Referenced by init_menubar_as_editor().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigSnapshotDialog::ConfigSnapshotDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ExtruderSequenceDialog::ExtruderSequenceDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::LoadProjectsDialog::LoadProjectsDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), init_menubar_as_editor(), init_tabpanel(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
on_config_changed()
void Slic3r::GUI::MainFrame::on_config_changed (DynamicPrintConfig * cfg) const
{
    if (m_plater)
        m_plater->on_config_change(*config); // propagate config change events to the plater
}
References m_plater, and Slic3r::GUI::Plater::on_config_change().
on_dpi_changed()
void Slic3r::GUI::MainFrame::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    wxGetApp().update_fonts(this);
    this->SetFont(this->normal_font());
#ifdef _MSW_DARK_MODE
    // update common mode sizer
    if (!wxGetApp().tabs_as_menu())
        dynamic_cast<Notebook*>(m_tabpanel)->Rescale();
#endif
    // update Plater
    wxGetApp().plater()->msw_rescale();
    // update Tabs
    if (m_layout != ESettingsLayout::Dlg) // Do not update tabs if the Settings are in the separated dialog
        for (auto tab : wxGetApp().tabs_list)
            tab->msw_rescale();
    // Workarounds for correct Window rendering after rescale
    /* Even if Window is maximized during moving,
     * first of all we should imitate Window resizing. So:
     * 1. cancel maximization, if it was set
     * 2. imitate resizing
     * 3. set maximization, if it was set
     */
    const bool is_maximized = this->IsMaximized();
    if (is_maximized)
        this->Maximize(false);
    /* To correct window rendering (especially redraw of a status bar)
     * we should imitate window resizing.
     */
    const wxSize& sz = this->GetSize();
    this->SetSize(sz.x + 1, sz.y + 1);
    this->SetSize(sz);
    this->Maximize(is_maximized);
}
References Dlg, m_layout, m_tabpanel, and Slic3r::GUI::DPIAware< P >::normal_font().
on_presets_changed()
void Slic3r::GUI::MainFrame::on_presets_changed (SimpleEvent & event) private
{
    auto *tab = dynamic_cast<Tab*>(event.GetEventObject());
    wxASSERT(tab != nullptr);
    if (tab == nullptr) {
        return;
    }
    // Update preset combo boxes(Print settings, Filament, Material, Printer) from their respective tabs.
    auto presets = tab->get_presets();
    if (m_plater != nullptr && presets != nullptr) {
        // FIXME: The preset type really should be a property of Tab instead
        Slic3r::Preset::Type preset_type = tab->type();
        if (preset_type == Slic3r::Preset::TYPE_INVALID) {
            wxASSERT(false);
            return;
        }
        m_plater->on_config_change(*tab->get_config());
        m_plater->sidebar().update_presets(preset_type);
    }
}
References m_plater, Slic3r::GUI::Plater::on_config_change(), Slic3r::GUI::Plater::sidebar(), Slic3r::Preset::TYPE_INVALID, and Slic3r::GUI::Sidebar::update_presets().
on_sys_color_changed()
void Slic3r::GUI::MainFrame::on_sys_color_changed () override protected virtual
Reimplemented from Slic3r::GUI::DPIAware< P >.
{
    wxBusyCursor wait;
    // update label colors in respect to the system mode
    wxGetApp().init_ui_colours();
    // but if there are some ui colors in appconfig, they have to be applied
    wxGetApp().update_ui_colours_from_appconfig();
#ifdef __WXMSW__
    wxGetApp().UpdateDarkUI(m_tabpanel);
 //   m_statusbar->update_dark_ui();
#ifdef _MSW_DARK_MODE
    // update common mode sizer
    if (!wxGetApp().tabs_as_menu())
        dynamic_cast<Notebook*>(m_tabpanel)->OnColorsChanged();
#endif
#endif
    // update Plater
    wxGetApp().plater()->sys_color_changed();
    // update Tabs
    for (auto tab : wxGetApp().tabs_list)
        tab->sys_color_changed();
    MenuFactory::sys_color_changed(m_menubar);
    this->Refresh();
}
References m_menubar, m_tabpanel, and Slic3r::GUI::MenuFactory::sys_color_changed().
on_value_changed()
void Slic3r::GUI::MainFrame::on_value_changed (wxCommandEvent & event) private
{
    auto *tab = dynamic_cast<Tab*>(event.GetEventObject());
    wxASSERT(tab != nullptr);
    if (tab == nullptr)
        return;
    auto opt_key = event.GetString();
    if (m_plater) {
        m_plater->on_config_change(*tab->get_config()); // propagate config change events to the plater
        if (opt_key == "extruders_count") {
            auto value = event.GetInt();
            m_plater->on_extruders_change(value);
        }
    }
}
References m_plater, Slic3r::GUI::Plater::on_config_change(), and Slic3r::GUI::Plater::on_extruders_change().
open_menubar_item()
void Slic3r::GUI::MainFrame::open_menubar_item (const wxString & menu_name, const wxString & item_name)
{
    if (m_menubar == nullptr)
        return;
    // Get menu object from menubar
    int     menu_index = m_menubar->FindMenu(menu_name);
    wxMenu* menu       = m_menubar->GetMenu(menu_index);
    if (menu == nullptr) {
        BOOST_LOG_TRIVIAL(error) << "Mainframe open_menubar_item function couldn't find menu: " << menu_name;
        return;
    }
    // Get item id from menu
    int     item_id   = menu->FindItem(item_name);
    if (item_id == wxNOT_FOUND)
    {
        // try adding three dots char
        item_id = menu->FindItem(item_name + dots);
    }
    if (item_id == wxNOT_FOUND)
    {
        BOOST_LOG_TRIVIAL(error) << "Mainframe open_menubar_item function couldn't find item: " << item_name;
        return;
    }
    // wxEVT_MENU will trigger item
    wxPostEvent((wxEvtHandler*)menu, wxCommandEvent(wxEVT_MENU, item_id));
}
References Slic3r::GUI::dots(), error, and m_menubar.
plater()
Plater * Slic3r::GUI::MainFrame::plater () inline
{ return m_plater; }
References m_plater.
Referenced by MainFrame(), Slic3r::GUI::SettingsDialog::SettingsDialog(), init_menubar_as_editor(), load_config(), technology_changed(), and update_menubar().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
printhost_queue_dlg()
PrintHostQueueDialog * Slic3r::GUI::MainFrame::printhost_queue_dlg () inline
{ return m_printhost_queue_dlg; }
References m_printhost_queue_dlg.
Referenced by Slic3r::GUI::GUI_App::recreate_GUI(), and Slic3r::GUI::GUI_App::update_ui_from_settings().
register_win32_callbacks()
void Slic3r::GUI::MainFrame::register_win32_callbacks ()
Referenced by init_tabpanel().
repair_stl()
void Slic3r::GUI::MainFrame::repair_stl ()
{
    wxString input_file;
    {
        wxFileDialog dlg(this, _L("Select the STL file to repair:"),
            wxGetApp().app_config->get_last_dir(), "",
            file_wildcards(FT_STL), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
        if (dlg.ShowModal() != wxID_OK)
            return;
        input_file = dlg.GetPath();
    }
    wxString output_file = input_file;
    {
        wxFileDialog dlg( this, L("Save OBJ file (less prone to coordinate errors than STL) as:"),
                                        get_dir_name(output_file), get_base_name(output_file, ".obj"),
                                        file_wildcards(FT_OBJ), wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
        if (dlg.ShowModal() != wxID_OK)
            return;
        output_file = dlg.GetPath();
    }
    Slic3r::TriangleMesh tmesh;
    tmesh.ReadSTLFile(input_file.ToUTF8().data());
    tmesh.WriteOBJFile(output_file.ToUTF8().data());
    Slic3r::GUI::show_info(this, L("Your file was repaired."), L("Repair"));
}
References _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_OBJ, Slic3r::GUI::FT_STL, get_base_name(), get_dir_name(), L, Slic3r::TriangleMesh::ReadSTLFile(), Slic3r::GUI::show_info(), and Slic3r::TriangleMesh::WriteOBJFile().
Referenced by init_menubar_as_editor().
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DiffPresetDialog::on_dpi_changed().
reslice_now()
void Slic3r::GUI::MainFrame::reslice_now ()
{
    if (m_plater)
        m_plater->reslice();
}
References m_plater, and Slic3r::GUI::Plater::reslice().
Referenced by init_menubar_as_editor().
save_project()
void Slic3r::GUI::MainFrame::save_project ()
{
    save_project_as(m_plater->get_project_filename(".3mf"));
}
References Slic3r::GUI::Plater::get_project_filename(), m_plater, and save_project_as().
Referenced by init_menubar_as_editor().
save_project_as()
bool Slic3r::GUI::MainFrame::save_project_as (const wxString & filename = wxString())
{
    bool ret = (m_plater != nullptr) ? m_plater->export_3mf(into_path(filename)) : false;
    if (ret) {
        // Make a copy of the active presets for detecting changes in preset values.
        wxGetApp().update_saved_preset_from_current_preset();
        // Save the names of active presets and project specific config into ProjectDirtyStateManager.
        // Reset ProjectDirtyStateManager's state as saved, mark active UndoRedo step as saved with project.
        m_plater->reset_project_dirty_after_save();
    }
    return ret;
}
References Slic3r::GUI::Plater::export_3mf(), Slic3r::GUI::into_path(), m_plater, and Slic3r::GUI::Plater::reset_project_dirty_after_save().
Referenced by init_menubar_as_editor(), save_project(), and Slic3r::GUI::Plater::priv::save_project_if_dirty().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
select_tab() [1/2]
void Slic3r::GUI::MainFrame::select_tab (size_t tab = size_t(-1))
{
    bool tabpanel_was_hidden = false;
    // Controls on page are created on active page of active tab now.
    // We should select/activate tab before its showing to avoid an UI-flickering
    auto select = [this, tab](bool was_hidden) {
        // when tab == -1, it means we should show the last selected tab
        size_t new_selection = tab == (size_t)(-1) ? m_last_selected_tab : (m_layout == ESettingsLayout::Dlg && tab != 0) ? tab - 1 : tab;
        if (m_tabpanel->GetSelection() != (int)new_selection)
            m_tabpanel->SetSelection(new_selection);
#ifdef _MSW_DARK_MODE
        if (wxGetApp().tabs_as_menu()) {
            if (Tab* cur_tab = dynamic_cast<Tab*>(m_tabpanel->GetPage(new_selection)))
                update_marker_for_tabs_menu((m_layout == ESettingsLayout::Old ? m_menubar : m_settings_dialog.menubar()), cur_tab->title(), m_layout == ESettingsLayout::Old);
            else if (tab == 0 && m_layout == ESettingsLayout::Old)
                m_plater->get_current_canvas3D()->render();
        }
#endif
        if (tab == 0 && m_layout == ESettingsLayout::Old)
            m_plater->canvas3D()->render();
        else if (was_hidden) {
            Tab* cur_tab = dynamic_cast<Tab*>(m_tabpanel->GetPage(new_selection));
            if (cur_tab)
                cur_tab->OnActivate();
        }
    };
    if (m_layout == ESettingsLayout::Dlg) {
        if (tab==0) {
            if (m_settings_dialog.IsShown())
                this->SetFocus();
            // plater should be focused for correct navigation inside search window
            if (m_plater->canvas3D()->is_search_pressed())
                m_plater->SetFocus();
            return;
        }
        // Show/Activate Settings Dialog
#ifdef __WXOSX__ // Don't call SetFont under OSX to avoid name cutting in ObjectList
        if (m_settings_dialog.IsShown())
            m_settings_dialog.Hide();
        else
            tabpanel_was_hidden = true;
        select(tabpanel_was_hidden);
        m_tabpanel->Show();
        m_settings_dialog.Show();
#else
        if (m_settings_dialog.IsShown()) {
            select(false);
            m_settings_dialog.SetFocus();
        }
        else {
            tabpanel_was_hidden = true;
            select(tabpanel_was_hidden);
            m_tabpanel->Show();
            m_settings_dialog.Show();
        }
#endif
        if (m_settings_dialog.IsIconized())
            m_settings_dialog.Iconize(false);
    }
    else if (m_layout == ESettingsLayout::New) {
        m_main_sizer->Show(m_plater, tab == 0);
        tabpanel_was_hidden = !m_main_sizer->IsShown(m_tabpanel);
        select(tabpanel_was_hidden);
        m_main_sizer->Show(m_tabpanel, tab != 0);
        // plater should be focused for correct navigation inside search window
        if (tab == 0)
            m_plater->SetFocus();
        Layout();
    }
    else {
        select(false);
#ifdef _MSW_DARK_MODE
        if (wxGetApp().tabs_as_menu() && tab == 0)
            m_plater->SetFocus();
#endif
    }
    // When we run application in ESettingsLayout::New or ESettingsLayout::Dlg mode, tabpanel is hidden from the very beginning
    // and as a result Tab::update_changed_tree_ui() function couldn't update m_is_nonsys_values values,
    // which are used for update TreeCtrl and "revert_buttons".
    // So, force the call of this function for Tabs, if tab panel was hidden
    if (tabpanel_was_hidden)
        for (auto cur_tab : wxGetApp().tabs_list)
            cur_tab->update_changed_tree_ui();
    //size_t new_selection = tab == (size_t)(-1) ? m_last_selected_tab : (m_layout == ESettingsLayout::Dlg && tab != 0) ? tab - 1 : tab;
    //if (m_tabpanel->GetSelection() != new_selection)
    //    m_tabpanel->SetSelection(new_selection);
    //if (tabpanel_was_hidden)
    //    static_cast<Tab*>(m_tabpanel->GetPage(new_selection))->OnActivate();
}
References Slic3r::GUI::Plater::canvas3D(), Dlg, Slic3r::GUI::Plater::get_current_canvas3D(), Slic3r::GUI::GLCanvas3D::is_search_pressed(), m_last_selected_tab, m_layout, m_main_sizer, m_menubar, m_plater, m_settings_dialog, m_tabpanel, Slic3r::GUI::SettingsDialog::menubar(), New, Old, Slic3r::GUI::Tab::OnActivate(), and Slic3r::GUI::GLCanvas3D::render().
select_tab() [2/2]
void Slic3r::GUI::MainFrame::select_tab (Tab * tab)
{
    if (!tab)
        return;
    int page_idx = m_tabpanel->FindPage(tab);
    if (page_idx != wxNOT_FOUND && m_layout == ESettingsLayout::Dlg)
        page_idx++;
    select_tab(size_t(page_idx));
}
References Dlg, m_layout, m_tabpanel, and select_tab().
Referenced by Slic3r::GUI::SettingsDialog::SettingsDialog(), init_menubar_as_editor(), init_tabpanel(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::GUI_App::recreate_GUI(), and select_tab().
select_view()
void Slic3r::GUI::MainFrame::select_view (const std::string & direction)
{
     if (m_plater)
         m_plater->select_view(direction);
}
References m_plater, and Slic3r::GUI::Plater::select_view().
Referenced by Slic3r::GUI::add_common_view_menu_items().
shutdown()
void Slic3r::GUI::MainFrame::shutdown ()
{
#ifdef _WIN32
  if (m_hDeviceNotify) {
    ::UnregisterDeviceNotification(HDEVNOTIFY(m_hDeviceNotify));
    m_hDeviceNotify = nullptr;
  }
  if (m_ulSHChangeNotifyRegister) {
        SHChangeNotifyDeregister(m_ulSHChangeNotifyRegister);
        m_ulSHChangeNotifyRegister = 0;
  }
#endif // _WIN32
    if (m_plater != nullptr) {
        m_plater->get_ui_job_worker().cancel_all();
        // Unbinding of wxWidgets event handling in canvases needs to be done here because on MAC,
        // when closing the application using Command+Q, a mouse event is triggered after this lambda is completed,
        // causing a crash
        m_plater->unbind_canvas_event_handlers();
        // Cleanup of canvases' volumes needs to be done here or a crash may happen on some Linux Debian flavours
        // see: https://github.com/prusa3d/PrusaSlicer/issues/3964
        m_plater->reset_canvas_volumes();
    }
    // Weird things happen as the Paint messages are floating around the windows being destructed.
    // Avoid the Paint messages by hiding the main window.
    // Also the application closes much faster without these unnecessary screen refreshes.
    // In addition, there were some crashes due to the Paint events sent to already destructed windows.
    this->Show(false);
    if (m_settings_dialog.IsShown())
        // call Close() to trigger call to lambda defined into GUI_App::persist_window_geometry()
        m_settings_dialog.Close();
    if (m_plater != nullptr) {
        // Stop the background thread (Windows and Linux).
        // Disconnect from a 3DConnextion driver (OSX).
        m_plater->get_mouse3d_controller().shutdown();
        // Store the device parameter database back to appconfig.
        m_plater->get_mouse3d_controller().save_config(*wxGetApp().app_config);
    }
    // Stop the background thread of the removable drive manager, so that no new updates will be sent to the Plater.
    wxGetApp().removable_drive_manager()->shutdown();
  //stop listening for messages from other instances
  wxGetApp().other_instance_message_handler()->shutdown(this);
    // Save the slic3r.ini.Usually the ini file is saved from "on idle" callback,
    // but in rare cases it may not have been called yet.
    if (wxGetApp().app_config->dirty())
        wxGetApp().app_config->save();
//         if (m_plater)
//             m_plater->print = undef;
//         Slic3r::GUI::deregister_on_request_update_callback();
    // set to null tabs and a plater
    // to avoid any manipulations with them from App->wxEVT_IDLE after of the mainframe closing
    wxGetApp().tabs_list.clear();
    wxGetApp().plater_ = nullptr;
}
References Slic3r::GUI::Worker::cancel_all(), Slic3r::GUI::Plater::get_mouse3d_controller(), Slic3r::GUI::Plater::get_ui_job_worker(), m_plater, m_settings_dialog, Slic3r::GUI::Plater::reset_canvas_volumes(), Slic3r::GUI::Mouse3DController::save_config(), Slic3r::GUI::Mouse3DController::shutdown(), and Slic3r::GUI::Plater::unbind_canvas_event_handlers().
Referenced by MainFrame(), and Slic3r::GUI::GUI_App::recreate_GUI().
technology_changed()
void Slic3r::GUI::MainFrame::technology_changed ()
{
    // update menu titles
    PrinterTechnology pt = plater()->printer_technology();
    if (int id = m_menubar->FindMenu(pt == ptFFF ? _L("Material Settings") : _L("Filament Settings")); id != wxNOT_FOUND)
        m_menubar->SetMenuLabel(id , pt == ptSLA ? _L("Material Settings") : _L("Filament Settings"));
    //if (wxGetApp().tab_panel()->GetSelection() != wxGetApp().tab_panel()->GetPageCount() - 1)
    //    wxGetApp().tab_panel()->SetSelection(wxGetApp().tab_panel()->GetPageCount() - 1);
}
References _L, m_menubar, plater(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptFFF, and Slic3r::ptSLA.
update_layout()
void Slic3r::GUI::MainFrame::update_layout ()
{
    auto restore_to_creation = [this]() {
        auto clean_sizer = [](wxSizer* sizer) {
            while (!sizer->GetChildren().IsEmpty()) {
                sizer->Detach(0);
            }
        };
        // On Linux m_plater needs to be removed from m_tabpanel before to reparent it
        int plater_page_id = m_tabpanel->FindPage(m_plater);
        if (plater_page_id != wxNOT_FOUND)
            m_tabpanel->RemovePage(plater_page_id);
        if (m_plater->GetParent() != this)
            m_plater->Reparent(this);
        if (m_tabpanel->GetParent() != this)
            m_tabpanel->Reparent(this);
        plater_page_id = (m_plater_page != nullptr) ? m_tabpanel->FindPage(m_plater_page) : wxNOT_FOUND;
        if (plater_page_id != wxNOT_FOUND) {
            m_tabpanel->DeletePage(plater_page_id);
            m_plater_page = nullptr;
        }
        clean_sizer(m_main_sizer);
        clean_sizer(m_settings_dialog.GetSizer());
        if (m_settings_dialog.IsShown())
            m_settings_dialog.Close();
        m_tabpanel->Hide();
        m_plater->Hide();
        Layout();
    };
    ESettingsLayout layout = wxGetApp().is_gcode_viewer() ? ESettingsLayout::GCodeViewer :
        (wxGetApp().app_config->get_bool("old_settings_layout_mode") ? ESettingsLayout::Old :
         wxGetApp().app_config->get_bool("new_settings_layout_mode") ? ( wxGetApp().tabs_as_menu() ? ESettingsLayout::Old : ESettingsLayout::New) :
         wxGetApp().app_config->get_bool("dlg_settings_layout_mode") ? ESettingsLayout::Dlg : ESettingsLayout::Old);
    if (m_layout == layout)
        return;
    wxBusyCursor busy;
    Freeze();
    // Remove old settings
    if (m_layout != ESettingsLayout::Unknown)
        restore_to_creation();
#ifdef __WXMSW__
    enum class State {
        noUpdate,
        fromDlg,
        toDlg
    };
    State update_scaling_state = //m_layout == ESettingsLayout::Unknown   ? State::noUpdate   : // don't scale settings dialog from the application start
                                 m_layout == ESettingsLayout::Dlg       ? State::fromDlg    :
                                 layout   == ESettingsLayout::Dlg       ? State::toDlg      : State::noUpdate;
#endif //__WXMSW__
    ESettingsLayout old_layout = m_layout;
    m_layout = layout;
    // From the very beginning the Print settings should be selected
    m_last_selected_tab = m_layout == ESettingsLayout::Dlg ? 0 : 1;
    // Set new settings
    switch (m_layout)
    {
    case ESettingsLayout::Unknown:
    {
        break;
    }
    case ESettingsLayout::Old:
    {
        m_plater->Reparent(m_tabpanel);
#ifdef _MSW_DARK_MODE
        m_plater->Layout();
        if (!wxGetApp().tabs_as_menu())
            dynamic_cast<Notebook*>(m_tabpanel)->InsertPage(0, m_plater, _L("Plater"), std::string("plater"), true);
        else
#endif
        m_tabpanel->InsertPage(0, m_plater, _L("Plater"));
        m_main_sizer->Add(m_tabpanel, 1, wxEXPAND | wxTOP, 1);
        m_plater->Show();
        m_tabpanel->Show();
        // update Tabs
        if (old_layout == ESettingsLayout::Dlg)
            if (int sel = m_tabpanel->GetSelection(); sel != wxNOT_FOUND)
                m_tabpanel->SetSelection(sel+1);// call SetSelection to correct layout after switching from Dlg to Old mode
#ifdef _MSW_DARK_MODE
        if (wxGetApp().tabs_as_menu())
            show_tabs_menu(true);
#endif
        break;
    }
    case ESettingsLayout::New:
    {
        m_main_sizer->Add(m_plater, 1, wxEXPAND);
        m_tabpanel->Hide();
        m_main_sizer->Add(m_tabpanel, 1, wxEXPAND);
        m_plater_page = new wxPanel(m_tabpanel);
#ifdef _MSW_DARK_MODE
        if (!wxGetApp().tabs_as_menu())
            dynamic_cast<Notebook*>(m_tabpanel)->InsertPage(0, m_plater_page, _L("Plater"), std::string("plater"), true);
        else
#endif
        m_tabpanel->InsertPage(0, m_plater_page, _L("Plater")); // empty panel just for Plater tab */
        m_plater->Show();
        break;
    }
    case ESettingsLayout::Dlg:
    {
        m_main_sizer->Add(m_plater, 1, wxEXPAND);
        m_tabpanel->Reparent(&m_settings_dialog);
        m_settings_dialog.GetSizer()->Add(m_tabpanel, 1, wxEXPAND | wxTOP, 2);
        m_tabpanel->Show();
        m_plater->Show();
#ifdef _MSW_DARK_MODE
        if (wxGetApp().tabs_as_menu())
            show_tabs_menu(false);
#endif
        break;
    }
    case ESettingsLayout::GCodeViewer:
    {
        m_main_sizer->Add(m_plater, 1, wxEXPAND);
        m_plater->set_default_bed_shape();
        m_plater->get_collapse_toolbar().set_enabled(false);
        m_plater->collapse_sidebar(true);
        m_plater->Show();
        break;
    }
    }
#ifdef _MSW_DARK_MODE
    // Sizer with buttons for mode changing
    m_plater->sidebar().show_mode_sizer(wxGetApp().tabs_as_menu() || m_layout != ESettingsLayout::Old);
#endif
#ifdef __WXMSW__
    if (update_scaling_state != State::noUpdate)
    {
        int mainframe_dpi   = get_dpi_for_window(this);
        int dialog_dpi      = get_dpi_for_window(&m_settings_dialog);
        if (mainframe_dpi != dialog_dpi) {
            wxSize oldDPI = update_scaling_state == State::fromDlg ? wxSize(dialog_dpi, dialog_dpi) : wxSize(mainframe_dpi, mainframe_dpi);
            wxSize newDPI = update_scaling_state == State::toDlg   ? wxSize(dialog_dpi, dialog_dpi) : wxSize(mainframe_dpi, mainframe_dpi);
            if (update_scaling_state == State::fromDlg)
                this->enable_force_rescale();
            else
                (&m_settings_dialog)->enable_force_rescale();
            wxWindow* win { nullptr };
            if (update_scaling_state == State::fromDlg)
                win = this;
            else
                win = &m_settings_dialog;
#if wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
            m_tabpanel->MSWUpdateOnDPIChange(oldDPI, newDPI);
            win->GetEventHandler()->AddPendingEvent(wxDPIChangedEvent(oldDPI, newDPI));
#else
            win->GetEventHandler()->AddPendingEvent(DpiChangedEvent(EVT_DPI_CHANGED_SLICER, newDPI, win->GetRect()));
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        }
    }
#endif //__WXMSW__
//#ifdef __APPLE__
//    // Using SetMinSize() on Mac messes up the window position in some cases
//    // cf. https://groups.google.com/forum/#!topic/wx-users/yUKPBBfXWO0
//    // So, if we haven't possibility to set MinSize() for the MainFrame,
//    // set the MinSize() as a half of regular  for the m_plater and m_tabpanel, when settings layout is in slNew mode
//    // Otherwise, MainFrame will be maximized by height
//    if (m_layout == ESettingsLayout::New) {
//        wxSize size = wxGetApp().get_min_size();
//        size.SetHeight(int(0.5 * size.GetHeight()));
//        m_plater->SetMinSize(size);
//        m_tabpanel->SetMinSize(size);
//    }
//#endif
#ifdef __APPLE__
    m_plater->sidebar().change_top_border_for_mode_sizer(m_layout != ESettingsLayout::Old);
#endif
    Layout();
    Thaw();
}
References _L, Slic3r::GUI::Sidebar::change_top_border_for_mode_sizer(), Slic3r::GUI::Plater::collapse_sidebar(), Dlg, Slic3r::GUI::DPIAware< P >::enable_force_rescale(), GCodeViewer, Slic3r::GUI::Plater::get_collapse_toolbar(), Slic3r::GUI::get_dpi_for_window(), m_last_selected_tab, m_layout, m_main_sizer, m_plater, m_plater_page, m_settings_dialog, m_tabpanel, New, Old, Slic3r::GUI::Plater::set_default_bed_shape(), Slic3r::GUI::GLToolbar::set_enabled(), Slic3r::GUI::Plater::sidebar(), and Unknown.
Referenced by MainFrame(), and Slic3r::GUI::GUI_App::open_preferences().
update_menubar()
void Slic3r::GUI::MainFrame::update_menubar ()
{
    if (wxGetApp().is_gcode_viewer())
        return;
    const bool is_fff = plater()->printer_technology() == ptFFF;
    m_changeable_menu_items[miExport]       ->SetItemLabel((is_fff ? _L("Export &G-code")         : _L("E&xport"))        + dots    + "\tCtrl+G");
    m_changeable_menu_items[miSend]         ->SetItemLabel((is_fff ? _L("S&end G-code")           : _L("S&end to print")) + dots    + "\tCtrl+Shift+G");
    m_changeable_menu_items[miMaterialTab]  ->SetItemLabel((is_fff ? _L("&Filament Settings Tab") : _L("Mate&rial Settings Tab"))   + "\tCtrl+3");
    m_changeable_menu_items[miMaterialTab]  ->SetBitmap(*get_bmp_bundle(is_fff ? "spool"   : "resin"));
    m_changeable_menu_items[miPrinterTab]   ->SetBitmap(*get_bmp_bundle(is_fff ? "printer" : "sla_printer"));
}
References _L, Slic3r::GUI::dots(), get_bmp_bundle(), m_changeable_menu_items, miExport, miMaterialTab, miPrinterTab, miSend, plater(), Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptFFF.
Referenced by init_menubar_as_editor().
update_mode_markers()
void Slic3r::GUI::MainFrame::update_mode_markers ()
{
#ifdef __WXMSW__
#ifdef _MSW_DARK_MODE
    // update markers in common mode sizer
    if (!wxGetApp().tabs_as_menu())
        dynamic_cast<Notebook*>(m_tabpanel)->UpdateModeMarkers();
#endif
#endif
    // update mode markers on side_bar
    wxGetApp().sidebar().update_mode_markers();
    // update mode markers in tabs
    for (auto tab : wxGetApp().tabs_list)
        tab->update_mode_markers();
}
References m_tabpanel.
Referenced by Slic3r::GUI::GUI_App::set_mode_palette().
update_title()
void Slic3r::GUI::MainFrame::update_title ()
{
    wxString title = wxEmptyString;
    if (m_plater != nullptr) {
        // m_plater->get_project_filename() produces file name including path, but excluding extension.
        // Don't try to remove the extension, it would remove part of the file name after the last dot!
        wxString project = from_path(into_path(m_plater->get_project_filename()).filename());
//        wxString dirty_marker = (!m_plater->model().objects.empty() && m_plater->is_project_dirty()) ? "*" : "";
        wxString dirty_marker = m_plater->is_project_dirty() ? "*" : "";
        if (!dirty_marker.empty() || !project.empty()) {
            if (!dirty_marker.empty() && project.empty())
                project = _L("Untitled");
            title = dirty_marker + project + " - ";
        }
    }
    std::string build_id = SLIC3R_BUILD_ID;
    if (! wxGetApp().is_editor())
        boost::replace_first(build_id, SLIC3R_APP_NAME, GCODEVIEWER_APP_NAME);
    size_t    idx_plus = build_id.find('+');
    if (idx_plus != build_id.npos) {
      // Parse what is behind the '+'. If there is a number, then it is a build number after the label, and full build ID is shown.
      int commit_after_label;
      if (! boost::starts_with(build_id.data() + idx_plus + 1, "UNKNOWN") &&
            (build_id.at(idx_plus + 1) == '-' || sscanf(build_id.data() + idx_plus + 1, "%d-", &commit_after_label) == 0)) {
        // It is a release build.
        build_id.erase(build_id.begin() + idx_plus, build_id.end());
#if defined(_WIN32) && ! defined(_WIN64)
        // People are using 32bit slicer on a 64bit machine by mistake. Make it explicit.
            build_id += " 32 bit";
#endif
      }
    }
    title += wxString(build_id);
    if (wxGetApp().is_editor())
        title += (" " + _L("based on Slic3r"));
    SetTitle(title);
}
References _L, Slic3r::GUI::from_path(), GCODEVIEWER_APP_NAME, Slic3r::GUI::Plater::get_project_filename(), Slic3r::GUI::into_path(), Slic3r::GUI::Plater::is_project_dirty(), and m_plater.
Referenced by MainFrame(), and Slic3r::GUI::ProjectDirtyStateManager::update_from_presets().
update_ui_from_settings()
void Slic3r::GUI::MainFrame::update_ui_from_settings ()
{
//    const bool bp_on = wxGetApp().app_config->get_bool("background_processing");
//     m_menu_item_reslice_now->Enable(!bp_on);
//    m_plater->sidebar().show_reslice(!bp_on);
//    m_plater->sidebar().show_export(bp_on);
//    m_plater->sidebar().Layout();
    if (m_plater)
        m_plater->update_ui_from_settings();
    for (auto tab: wxGetApp().tabs_list)
        tab->update_ui_from_settings();
}
References m_plater, and Slic3r::GUI::Plater::update_ui_from_settings().
Referenced by MainFrame(), and Slic3r::GUI::GUI_App::update_ui_from_settings().
Member Data Documentation
diff_dialog
DiffPresetDialog Slic3r::GUI::MainFrame::diff_dialog
Referenced by bind_diff_dialog(), init_menubar_as_editor(), and Slic3r::GUI::GUI_App::update_ui_from_settings().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_changeable_menu_items
std::vector<wxMenuItem*> Slic3r::GUI::MainFrame::m_changeable_menu_items private
Referenced by init_menubar_as_editor(), and update_menubar().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_gallery_dialog
GalleryDialog* Slic3r::GUI::MainFrame::m_gallery_dialog { nullptr }
Referenced by gallery_dialog(), and init_menubar_as_editor().
m_last_config
wxString Slic3r::GUI::MainFrame::m_last_config = wxEmptyString private
Referenced by export_config(), export_configbundle(), load_config_file(), and load_configbundle().
m_last_selected_tab
size_t Slic3r::GUI::MainFrame::m_last_selected_tab private
Referenced by init_tabpanel(), select_tab(), and update_layout().
m_layout
ESettingsLayout Slic3r::GUI::MainFrame::m_layout { ESettingsLayout::Unknown } private
Referenced by can_change_view(), is_active_and_shown_tab(), is_dlg_layout(), on_dpi_changed(), select_tab(), select_tab(), and update_layout().
m_loaded
bool Slic3r::GUI::MainFrame::m_loaded {false} private
Referenced by MainFrame(), and is_loaded().
m_main_sizer
wxSizer* Slic3r::GUI::MainFrame::m_main_sizer { nullptr } private
Referenced by MainFrame(), is_active_and_shown_tab(), select_tab(), and update_layout().
m_menu_item_reslice_now
wxMenuItem* Slic3r::GUI::MainFrame::m_menu_item_reslice_now { nullptr } private
Referenced by init_menubar_as_editor().
m_menubar
wxMenuBar* Slic3r::GUI::MainFrame::m_menubar { nullptr } private
Referenced by init_menubar_as_editor(), init_menubar_as_gcodeviewer(), on_sys_color_changed(), open_menubar_item(), select_tab(), and technology_changed().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_plater
Plater* Slic3r::GUI::MainFrame::m_plater { nullptr }
Referenced by MainFrame(), bind_diff_dialog(), can_change_view(), can_delete(), can_delete_all(), can_deselect(), can_export_gcode(), can_export_gcode_sd(), can_export_model(), can_export_supports(), can_export_toolpaths(), can_reslice(), can_save(), can_save_as(), can_select(), can_send_gcode(), can_slice(), can_start_new_project(), init_menubar_as_editor(), init_menubar_as_gcodeviewer(), init_tabpanel(), load_config(), load_config_file(), on_config_changed(), on_presets_changed(), on_value_changed(), plater(), reslice_now(), save_project(), save_project_as(), select_tab(), select_view(), shutdown(), update_layout(), update_title(), and update_ui_from_settings().
m_plater_page
wxWindow* Slic3r::GUI::MainFrame::m_plater_page { nullptr }
Referenced by update_layout().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_printhost_queue_dlg
PrintHostQueueDialog* Slic3r::GUI::MainFrame::m_printhost_queue_dlg
Referenced by Slic3r::GUI::GUI_App::check_print_host_queue(), init_menubar_as_editor(), and printhost_queue_dlg().
m_qs_last_input_file
wxString Slic3r::GUI::MainFrame::m_qs_last_input_file = wxEmptyString private
Referenced by is_last_input_file().
m_qs_last_output_file
wxString Slic3r::GUI::MainFrame::m_qs_last_output_file = wxEmptyString private
m_recent_projects
wxFileHistory Slic3r::GUI::MainFrame::m_recent_projects private
Referenced by add_to_recent_projects(), and init_menubar_as_editor().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_settings_dialog
SettingsDialog Slic3r::GUI::MainFrame::m_settings_dialog
Referenced by MainFrame(), init_tabpanel(), is_active_and_shown_tab(), select_tab(), shutdown(), update_layout(), and Slic3r::GUI::GUI_App::update_ui_from_settings().
m_tabpanel
wxBookCtrlBase* Slic3r::GUI::MainFrame::m_tabpanel { nullptr }
Referenced by add_created_tab(), can_change_view(), create_preset_tabs(), init_tabpanel(), is_active_and_shown_tab(), on_dpi_changed(), on_sys_color_changed(), select_tab(), select_tab(), Slic3r::GUI::GUI_App::tab_panel(), update_layout(), Slic3r::GUI::GUI_App::update_mode(), and update_mode_markers().
preferences_dialog
PreferencesDialog* Slic3r::GUI::MainFrame::preferences_dialog { nullptr }
Referenced by MainFrame(), Slic3r::GUI::GUI_App::open_preferences(), and Slic3r::GUI::GUI_App::update_ui_from_settings().
The documentation for this class was generated from the following files:
src/slic3r/GUI/MainFrame.hpp
src/slic3r/GUI/MainFrame.cpp