Prusa Slicer: src/eigen/Eigen/src/plugins/CommonCwiseUnaryOps.h File Reference
CommonCwiseUnaryOps.h File Reference
Classes
struct CastXpr< NewType >
Typedefs
typedef internal::conditional< NumTraits< Scalar >::IsComplex, constCwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, constDerived >, constDerived & >::type ConjugateReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, constCwiseUnaryOp< internal::scalar_real_op< Scalar >, constDerived >, constDerived & >::type RealReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryView< internal::scalar_real_ref_op< Scalar >, Derived >, Derived & >::type NonConstRealReturnType
typedef CwiseUnaryOp< internal::scalar_imag_op< Scalar >, const Derived > ImagReturnType
typedef CwiseUnaryView< internal::scalar_imag_ref_op< Scalar >, Derived > NonConstImagReturnType
typedef CwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const Derived > NegativeReturnType
Functions
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const
template<typename NewType >
EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC RealReturnType real () const
EIGEN_DEVICE_FUNC const ImagReturnType imag () const
template<typename CustomUnaryOp >
EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
Class Documentation
CastXpr
struct CastXpr
template<class NewType>
struct CastXpr< NewType >
Class Members
typedef cast_return_type< Derived, constCwiseUnaryOp< scalar_cast_op< Scalar, NewType >, constDerived > >::type Type
Typedef Documentation
ConjugateReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex,constCwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,constDerived>,constDerived&>::type ConjugateReturnType
ImagReturnType
typedef CwiseUnaryOp<internal::scalar_imag_op<Scalar>, const Derived> ImagReturnType
NegativeReturnType
typedef CwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const Derived> NegativeReturnType
NonConstImagReturnType
typedef CwiseUnaryView<internal::scalar_imag_ref_op<Scalar>, Derived> NonConstImagReturnType
NonConstRealReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryView<internal::scalar_real_ref_op<Scalar>,Derived>,Derived&>::type NonConstRealReturnType
RealReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex,constCwiseUnaryOp<internal::scalar_real_op<Scalar>,constDerived>,constDerived&>::type RealReturnType
Function Documentation
cast()
template<typename NewType > EIGEN_DEVICE_FUNC CastXpr< NewType >::Type cast () const
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See also
class CwiseUnaryOp
{
  return typename CastXpr<NewType>::Type(derived());
}
Referenced by boost::polygon::voronoi_visual_utils< CT >::discretize(), Slic3r::line_alg::distance_to_infinite_squared(), Slic3r::line_alg::distance_to_squared(), igl::doublearea(), boost::polygon::voronoi_visual_utils< CT >::get_point_projection(), Slic3r::line_alg::intersection(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::operator*(), and Eigen::operator*().
conjugate()
EIGEN_DEVICE_FUNC ConjugateReturnType conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See also
Math functions, MatrixBase::adjoint()
{
  return ConjugateReturnType(derived());
}
Referenced by Eigen::VectorwiseOp< ExpressionType, Direction >::cross(), Eigen::internal::TridiagonalizationMatrixTReturnType< MatrixType >::evalTo(), Eigen::QuaternionBase< Derived >::inverse(), and igl::Camera::look_at().
imag()
EIGEN_DEVICE_FUNC NonConstImagReturnType imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See also
real()
Returns
a non const expression of the imaginary part of *this.
See also
real()
{ return ImagReturnType(derived()); }
Referenced by Eigen::numext::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs(), Eigen::internal::scalar_sign_op< Scalar, true >::operator()(), Eigen::internal::pcplxflip(), Eigen::internal::pmul(), Eigen::internal::pmul(), Eigen::internal::imag_default_impl< Scalar, true >::run(), Eigen::internal::abs2_impl_default< Scalar, true >::run(), Eigen::internal::norm1_default_impl< Scalar, IsComplex >::run(), and Eigen::internal::random_default_impl< Scalar, true, false >::run().
operator-()
EIGEN_DEVICE_FUNC const NegativeReturnType operator- () const inline
Returns
an expression of the opposite of *this
{ return NegativeReturnType(derived()); }
real()
EIGEN_DEVICE_FUNC NonConstRealReturnType real () const inline
Returns
a read-only expression of the real part of *this.
See also
imag()
Returns
a non const expression of the real part of *this.
See also
imag()
{ return RealReturnType(derived()); }
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::numext::EIGEN_MATHFUNC_RETVAL(), igl::fast_winding_number(), igl::copyleft::cgal::fast_winding_number(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs(), Eigen::CholmodBase< _MatrixType, _UpLo, Derived >::logDeterminant(), Eigen::internal::scalar_sign_op< Scalar, true >::operator()(), Eigen::internal::pcplxflip(), Eigen::internal::pmul(), Eigen::internal::pmul(), igl::copyleft::cgal::point_areas(), Eigen::internal::real_default_impl< Scalar, true >::run(), Eigen::internal::abs2_impl_default< Scalar, true >::run(), Eigen::internal::norm1_default_impl< Scalar, IsComplex >::run(), Eigen::internal::random_default_impl< Scalar, true, false >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run(), and Eigen::Tridiagonalization< _MatrixType >::subDiagonal().
unaryExpr()
template<typename CustomUnaryOp > EIGEN_DEVICE_FUNC const CwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
Output:
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
Output:
See also
unaryViewExpr, binaryExpr, class CwiseUnaryOp
{
  return CwiseUnaryOp<CustomUnaryOp, const Derived>(derived(), func);
}
unaryViewExpr()
template<typename CustomViewOp > EIGEN_DEVICE_FUNC const CwiseUnaryView< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
Output:
unaryExpr, binaryExpr class CwiseUnaryOp
{
  return CwiseUnaryView<CustomViewOp, const Derived>(derived(), func);
}