Prusa Slicer: igl::geodesic::Point3D Class Reference
igl::geodesic::Point3D Class Reference
Public Member Functions
Point3D ()
Point3D (Point3D *p)
double * xyz ()
double & x ()
double & y ()
double & z ()
void set (double new_x, double new_y, double new_z)
void set (double *data)
double distance (double *v)
double distance (Point3D *v)
void add (Point3D *v)
void multiply (double v)
Private Attributes
double m_coordinates [3]
Detailed Description
Constructor & Destructor Documentation
Point3D() [1/2]
igl::geodesic::Point3D::Point3D () inline
{};
Point3D() [2/2]
igl::geodesic::Point3D::Point3D (Point3D * p) inline
  {
    x() = p->x();
    y() = p->y();
    z() = p->z();
  };
References x(), y(), and z().
Member Function Documentation
add()
void igl::geodesic::Point3D::add (Point3D * v) inline
  {
    x() += v->x();
    y() += v->y();
    z() += v->z();
  };
References x(), y(), and z().
Referenced by igl::geodesic::SurfacePoint::SurfacePoint().
distance() [1/2]
double igl::geodesic::Point3D::distance (double * v) inline
  {
    double dx = m_coordinates[0] - v[0];
    double dy = m_coordinates[1] - v[1];
    double dz = m_coordinates[2] - v[2];
    return sqrt(dx*dx + dy*dy + dz*dz);
  };
References m_coordinates, and sqrt().
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), distance(), igl::geodesic::Edge::local_coordinates(), igl::geodesic::GeodesicAlgorithmBase::set_stop_conditions(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
distance() [2/2]
double igl::geodesic::Point3D::distance (Point3D * v) inline
  {
    return distance(v->xyz());
  };
References distance(), and xyz().
multiply()
void igl::geodesic::Point3D::multiply (double v) inline
  {
    x() *= v;
    y() *= v;
    z() *= v;
  };
References x(), y(), and z().
Referenced by igl::geodesic::SurfacePoint::SurfacePoint().
set() [1/2]
void igl::geodesic::Point3D::set (double * data) inline
  {
    x() = *data;
    y() = *(data+1);
    z() = *(data+2);
  }
References x(), y(), and z().
set() [2/2]
void igl::geodesic::Point3D::set (double new_x, double new_y, double new_z) inline
  {
    x() = new_x;
    y() = new_y;
    z() = new_z;
  }
References x(), y(), and z().
Referenced by igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), and igl::geodesic::fill_surface_point_structure().
x()
double & igl::geodesic::Point3D::x () inline
{return *m_coordinates;};
References m_coordinates.
Referenced by Point3D(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), multiply(), igl::geodesic::SurfacePointWithIndex::operator()(), set(), set(), and igl::geodesic::Mesh::verify().
xyz()
double * igl::geodesic::Point3D::xyz () inline
{return m_coordinates;};
References m_coordinates.
Referenced by distance().
y()
double & igl::geodesic::Point3D::y () inline
{return *(m_coordinates+1);};
References m_coordinates.
Referenced by Point3D(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), multiply(), igl::geodesic::SurfacePointWithIndex::operator()(), set(), set(), and igl::geodesic::Mesh::verify().
z()
double & igl::geodesic::Point3D::z () inline
{return *(m_coordinates+2);};
References m_coordinates.
Referenced by Point3D(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), multiply(), set(), set(), and igl::geodesic::Mesh::verify().
Member Data Documentation
m_coordinates
double igl::geodesic::Point3D::m_coordinates[3] private
Referenced by distance(), x(), xyz(), y(), and z().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp