Prusa Slicer: Slic3r::branchingtree::Properties Class Reference
Slic3r::branchingtree::Properties Class Reference
#include <src/libslic3r/BranchingTree/BranchingTree.hpp>
Public Member Functions
Properties & max_slope (double val) noexcept
Properties & ground_level (double val) noexcept
Properties & sampling_radius (double val) noexcept
Properties & bed_shape (ExPolygons bed) noexcept
Properties & max_branch_length (double val) noexcept
double max_slope () const noexcept
double ground_level () const noexcept
double sampling_radius () const noexcept
double max_branch_length () const noexcept
const ExPolygons & bed_shape () const noexcept
Private Attributes
double m_max_slope = PI / 4.
double m_ground_level = 0.
double m_sampling_radius = .5
double m_max_branch_len = 10.
ExPolygons m_bed_shape
Detailed Description
Member Function Documentation
bed_shape() [1/2]
const ExPolygons & Slic3r::branchingtree::Properties::bed_shape () const inline noexcept
{ return m_bed_shape; }
References m_bed_shape.
bed_shape() [2/2]
Properties & Slic3r::branchingtree::Properties::bed_shape (ExPolygons bed) inline noexcept
    {
        m_bed_shape = std::move(bed);
        return *this;
    }
References m_bed_shape.
Referenced by Slic3r::sla::create_branching_tree().
ground_level() [1/2]
double Slic3r::branchingtree::Properties::ground_level () const inline noexcept
{ return m_ground_level; }
References m_ground_level.
ground_level() [2/2]
Properties & Slic3r::branchingtree::Properties::ground_level (double val) inline noexcept
    {
        m_ground_level = val;
        return *this;
    }
References m_ground_level.
Referenced by Slic3r::sla::create_branching_tree(), Slic3r::branchingtree::PointCloud::foreach_reachable(), Slic3r::branchingtree::PointCloud::get_distance(), and Slic3r::branchingtree::get_support_cone_bb().
max_branch_length() [1/2]
double Slic3r::branchingtree::Properties::max_branch_length () const inline noexcept
{ return m_max_branch_len; }
References m_max_branch_len.
max_branch_length() [2/2]
Properties & Slic3r::branchingtree::Properties::max_branch_length (double val) inline noexcept
    {
        m_max_branch_len = val;
        return *this;
    }
References m_max_branch_len.
Referenced by Slic3r::branchingtree::build_tree(), Slic3r::sla::create_branching_tree(), Slic3r::branchingtree::PointCloud::foreach_reachable(), Slic3r::branchingtree::PointCloud::get_distance(), and Slic3r::branchingtree::get_support_cone_bb().
max_slope() [1/2]
double Slic3r::branchingtree::Properties::max_slope () const inline noexcept
{ return m_max_slope; }
References m_max_slope.
max_slope() [2/2]
Properties & Slic3r::branchingtree::Properties::max_slope (double val) inline noexcept
    {
        m_max_slope = val;
        return *this;
    }
References m_max_slope.
Referenced by Slic3r::sla::create_branching_tree(), Slic3r::branchingtree::PointCloud::get_distance(), and Slic3r::branchingtree::get_support_cone_bb().
sampling_radius() [1/2]
double Slic3r::branchingtree::Properties::sampling_radius () const inline noexcept
{ return m_sampling_radius; }
References m_sampling_radius.
sampling_radius() [2/2]
Properties & Slic3r::branchingtree::Properties::sampling_radius (double val) inline noexcept
    {
        m_sampling_radius = val;
        return *this;
    }
References m_sampling_radius.
Member Data Documentation
m_bed_shape
ExPolygons Slic3r::branchingtree::Properties::m_bed_shape private
Referenced by bed_shape(), and bed_shape().
m_ground_level
double Slic3r::branchingtree::Properties::m_ground_level = 0. private
Referenced by ground_level(), and ground_level().
m_max_branch_len
double Slic3r::branchingtree::Properties::m_max_branch_len = 10. private
Referenced by max_branch_length(), and max_branch_length().
m_max_slope
double Slic3r::branchingtree::Properties::m_max_slope = PI / 4. private
Referenced by max_slope(), and max_slope().
m_sampling_radius
double Slic3r::branchingtree::Properties::m_sampling_radius = .5 private
Referenced by sampling_radius(), and sampling_radius().
The documentation for this class was generated from the following file:
src/libslic3r/BranchingTree/BranchingTree.hpp