Prusa Slicer: Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType > Class Template Reference
Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType > Class Template Reference
#include <src/libslic3r/ClipperUtils.hpp>
Classes
struct iterator
Public Member Functions
MultiPointsProvider (const MultiPointsType &multipoints)
iterator cbegin () const
iterator begin () const
iterator cend () const
iterator end () const
size_t size () const
Private Attributes
const MultiPointsType & m_multipoints
Detailed Description
template<typename MultiPointsType>
class Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >
Constructor & Destructor Documentation
MultiPointsProvider()
template<typename MultiPointsType > Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::MultiPointsProvider (const MultiPointsType & multipoints) inline
: m_multipoints(multipoints) {}
Member Function Documentation
begin()
template<typename MultiPointsType > iterator Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::begin () const inline
{ return this->cbegin(); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::cbegin().
cbegin()
template<typename MultiPointsType > iterator Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::cbegin () const inline
{ return iterator(m_multipoints.begin()); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::m_multipoints.
Referenced by Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::begin().
cend()
template<typename MultiPointsType > iterator Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::cend () const inline
{ return iterator(m_multipoints.end()); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::m_multipoints.
Referenced by Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::end().
end()
template<typename MultiPointsType > iterator Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::end () const inline
{ return this->cend(); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::cend().
size()
template<typename MultiPointsType > size_t Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::size () const inline
{ return m_multipoints.size(); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::m_multipoints.
Member Data Documentation
m_multipoints
template<typename MultiPointsType > const MultiPointsType& Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::m_multipoints private
Referenced by Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::cbegin(), Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::cend(), and Slic3r::ClipperUtils::MultiPointsProvider< MultiPointsType >::size().
The documentation for this class was generated from the following file:
src/libslic3r/ClipperUtils.hpp