Prusa Slicer: Slic3r::GUI::CommonGizmosDataBase Class Reference
Slic3r::GUI::CommonGizmosDataBase Class Reference abstract
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
CommonGizmosDataBase (CommonGizmosDataPool *cgdp)
virtual ~CommonGizmosDataBase ()
void update ()
void release ()
bool is_valid () const
virtual CommonGizmosDataID get_dependencies () const
Protected Member Functions
virtual void on_release ()=0
virtual void on_update ()=0
CommonGizmosDataPool * get_pool () const
Private Attributes
bool m_is_valid = false
CommonGizmosDataPool * m_common = nullptr
Detailed Description
Constructor & Destructor Documentation
CommonGizmosDataBase()
Slic3r::GUI::CommonGizmosDataBase::CommonGizmosDataBase (CommonGizmosDataPool * cgdp) inline explicit
        : m_common{cgdp} {}
~CommonGizmosDataBase()
virtual Slic3r::GUI::CommonGizmosDataBase::~CommonGizmosDataBase () inline virtual
{}
Member Function Documentation
get_dependencies()
virtual CommonGizmosDataID Slic3r::GUI::CommonGizmosDataBase::get_dependencies () const inline virtual
Reimplemented in Slic3r::GUI::CommonGizmosDataObjects::InstancesHider, Slic3r::GUI::CommonGizmosDataObjects::Raycaster, Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper, and Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper.
{ return CommonGizmosDataID::None; }
References Slic3r::GUI::None.
get_pool()
CommonGizmosDataPool * Slic3r::GUI::CommonGizmosDataBase::get_pool () const inline protected
{ return m_common; }
References m_common.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_release(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), and Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut().
is_valid()
bool Slic3r::GUI::CommonGizmosDataBase::is_valid () const inline
{ return m_is_valid; }
References m_is_valid.
Referenced by Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::GUI::CommonGizmosDataPool::supports_clipper().
on_release()
virtual void Slic3r::GUI::CommonGizmosDataBase::on_release () protected pure virtual
Implemented in Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo, Slic3r::GUI::CommonGizmosDataObjects::InstancesHider, Slic3r::GUI::CommonGizmosDataObjects::Raycaster, Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper, and Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper.
Referenced by release().
on_update()
virtual void Slic3r::GUI::CommonGizmosDataBase::on_update () protected pure virtual
Implemented in Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo, Slic3r::GUI::CommonGizmosDataObjects::InstancesHider, Slic3r::GUI::CommonGizmosDataObjects::Raycaster, Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper, and Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper.
Referenced by update().
release()
void Slic3r::GUI::CommonGizmosDataBase::release () inline
{ on_release(); m_is_valid = false; }
References m_is_valid, and on_release().
update()
void Slic3r::GUI::CommonGizmosDataBase::update () inline
{ on_update(); m_is_valid = true; }
References m_is_valid, and on_update().
Member Data Documentation
m_common
CommonGizmosDataPool* Slic3r::GUI::CommonGizmosDataBase::m_common = nullptr private
Referenced by get_pool().
m_is_valid
bool Slic3r::GUI::CommonGizmosDataBase::m_is_valid = false private
Referenced by is_valid(), release(), and update().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp