Prusa Slicer: src/avrdude/flip2.h File Reference
flip2.h File Reference
Functions
void flip2_initpgm (PROGRAMMER *pgm)
Variables
const char flip2_desc []
Function Documentation
flip2_initpgm()
void flip2_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "flip2");
  /* Mandatory Functions */
  pgm->initialize       = flip2_initialize;
  pgm->enable           = flip2_enable;
  pgm->disable          = flip2_disable;
  pgm->display          = flip2_display;
  pgm->program_enable   = flip2_program_enable;
  pgm->chip_erase       = flip2_chip_erase;
  pgm->open             = flip2_open;
  pgm->close            = flip2_close;
  pgm->paged_load       = flip2_paged_load;
  pgm->paged_write      = flip2_paged_write;
  pgm->read_byte        = flip2_read_byte;
  pgm->write_byte       = flip2_write_byte;
  pgm->read_sig_bytes   = flip2_read_sig_bytes;
  pgm->setup            = flip2_setup;
  pgm->teardown         = flip2_teardown;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, flip2_chip_erase(), flip2_close(), flip2_disable(), flip2_display(), flip2_enable(), flip2_initialize(), flip2_open(), flip2_paged_load(), flip2_paged_write(), flip2_program_enable(), flip2_read_byte(), flip2_read_sig_bytes(), flip2_setup(), flip2_teardown(), flip2_write_byte(), programmer_t::initialize, programmer_t::open, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::program_enable, programmer_t::read_byte, programmer_t::read_sig_bytes, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
Variable Documentation
flip2_desc
const char flip2_desc[] extern