Prusa Slicer: Eigen::CompleteOrthogonalDecomposition< _MatrixType > Class Template Reference
Eigen::CompleteOrthogonalDecomposition< _MatrixType > Class Template Reference
Complete orthogonal decomposition (COD) of a matrix.
#include <src/eigen/Eigen/src/QR/CompleteOrthogonalDecomposition.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime > PermutationType
typedef internal::plain_row_type< MatrixType, Index >::type IntRowVectorType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef internal::plain_row_type< MatrixType, RealScalar >::type RealRowVectorType
typedef HouseholderSequence< MatrixType, typename internal::remove_all< typename HCoeffsType::ConjugateReturnType >::type > HouseholderSequenceType
typedef MatrixType::PlainObject PlainObject
Public Member Functions
CompleteOrthogonalDecomposition ()
Default Constructor.
CompleteOrthogonalDecomposition (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
CompleteOrthogonalDecomposition (const EigenBase< InputType > &matrix)
Constructs a complete orthogonal decomposition from a given matrix.
template<typename InputType >
CompleteOrthogonalDecomposition (EigenBase< InputType > &matrix)
Constructs a complete orthogonal decomposition from a given matrix.
template<typename Rhs >
const Solve< CompleteOrthogonalDecomposition, Rhs > solve (const MatrixBase< Rhs > &b) const
HouseholderSequenceType householderQ (void) const
HouseholderSequenceType matrixQ (void) const
MatrixType matrixZ () const
const MatrixType & matrixQTZ () const
const MatrixType & matrixT () const
template<typename InputType >
CompleteOrthogonalDecomposition & compute (const EigenBase< InputType > &matrix)
const PermutationType & colsPermutation () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< CompleteOrthogonalDecomposition > pseudoInverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
const HCoeffsType & zCoeffs () const
CompleteOrthogonalDecomposition & setThreshold (const RealScalar &threshold)
CompleteOrthogonalDecomposition & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
ComputationInfo info () const
Reports whether the complete orthogonal decomposition was succesful.
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
Protected Member Functions
void computeInPlace ()
template<typename Rhs >
void applyZAdjointOnTheLeftInPlace (Rhs &rhs) const
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
ColPivHouseholderQR< MatrixType > m_cpqr
HCoeffsType m_zCoeffs
RowVectorType m_temp
Private Types
typedef PermutationType::Index PermIndexType
Detailed Description
template<typename _MatrixType>
class Eigen::CompleteOrthogonalDecomposition< _MatrixType >
Complete orthogonal decomposition (COD) of a matrix.
Parameters
MatrixType the type of the matrix of which we are computing the COD.
This class performs a rank-revealing complete orthogonal decomposition of a matrix A into matrices P, Q, T, and Z such that
by using Householder transformations. Here, P is a permutation matrix, Q and Z are unitary matrices and T an upper triangular matrix of size rank-by-rank. A may be rank deficient.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::completeOrthogonalDecomposition()
Member Typedef Documentation
HCoeffsType
template<typename _MatrixType > typedef internal::plain_diag_type<MatrixType>::type Eigen::CompleteOrthogonalDecomposition< _MatrixType >::HCoeffsType
HouseholderSequenceType
template<typename _MatrixType > typedef HouseholderSequence< MatrixType, typename internal::remove_all< typename HCoeffsType::ConjugateReturnType>::type> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::HouseholderSequenceType
IntRowVectorType
template<typename _MatrixType > typedef internal::plain_row_type<MatrixType,Index>::type Eigen::CompleteOrthogonalDecomposition< _MatrixType >::IntRowVectorType
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::MatrixType
PermIndexType
template<typename _MatrixType > typedef PermutationType::Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::PermIndexType private
PermutationType
template<typename _MatrixType > typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::PermutationType
PlainObject
template<typename _MatrixType > typedef MatrixType::PlainObject Eigen::CompleteOrthogonalDecomposition< _MatrixType >::PlainObject
RealRowVectorType
template<typename _MatrixType > typedef internal::plain_row_type<MatrixType,RealScalar>::type Eigen::CompleteOrthogonalDecomposition< _MatrixType >::RealRowVectorType
RealScalar
template<typename _MatrixType > typedef MatrixType::RealScalar Eigen::CompleteOrthogonalDecomposition< _MatrixType >::RealScalar
RowVectorType
template<typename _MatrixType > typedef internal::plain_row_type<MatrixType>::type Eigen::CompleteOrthogonalDecomposition< _MatrixType >::RowVectorType
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::CompleteOrthogonalDecomposition< _MatrixType >::Scalar
StorageIndex
template<typename _MatrixType > typedef MatrixType::StorageIndex Eigen::CompleteOrthogonalDecomposition< _MatrixType >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
       {
    RowsAtCompileTime = MatrixType::RowsAtCompileTime,
    ColsAtCompileTime = MatrixType::ColsAtCompileTime,
    MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
    MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
  };
Constructor & Destructor Documentation
CompleteOrthogonalDecomposition() [1/4]
template<typename _MatrixType > Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via CompleteOrthogonalDecomposition::compute(const* MatrixType&).
: m_cpqr(), m_zCoeffs(), m_temp() {}
CompleteOrthogonalDecomposition() [2/4]
template<typename _MatrixType > Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
CompleteOrthogonalDecomposition()
      : m_cpqr(rows, cols), m_zCoeffs((std::min)(rows, cols)), m_temp(cols) {}
CompleteOrthogonalDecomposition() [3/4]
template<typename _MatrixType > template<typename InputType > Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition (const EigenBase< InputType > & matrix) inline explicit
Constructs a complete orthogonal decomposition from a given matrix.
This constructor computes the complete orthogonal decomposition of the matrix matrix by calling the method compute(). The default threshold for rank determination will be used. It is a short cut for:
CompleteOrthogonalDecomposition<MatrixType> cod(matrix.rows(),
                                                matrix.cols());
cod.setThreshold(Default);
cod.compute(matrix);
See also
compute()
      : m_cpqr(matrix.rows(), matrix.cols()),
        m_zCoeffs((std::min)(matrix.rows(), matrix.cols())),
        m_temp(matrix.cols())
  {
    compute(matrix.derived());
  }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::compute(), and Eigen::EigenBase< Derived >::derived().
CompleteOrthogonalDecomposition() [4/4]
template<typename _MatrixType > template<typename InputType > Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition (EigenBase< InputType > & matrix) inline explicit
Constructs a complete orthogonal decomposition from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
CompleteOrthogonalDecomposition(const EigenBase&)
    : m_cpqr(matrix.derived()),
      m_zCoeffs((std::min)(matrix.rows(), matrix.cols())),
      m_temp(matrix.cols())
  {
    computeInPlace();
  }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::computeInPlace().
Member Function Documentation
_solve_impl() [1/2]
template<typename _MatrixType > template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::CompleteOrthogonalDecomposition< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
_solve_impl() [2/2]
template<typename _MatrixType > template<typename RhsType , typename DstType > void Eigen::CompleteOrthogonalDecomposition< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
  eigen_assert(rhs.rows() == this->rows());
  const Index rank = this->rank();
  if (rank == 0) {
    dst.setZero();
    return;
  }
  // Compute c = Q^* * rhs
  // Note that the matrix Q = H_0^* H_1^*... so its inverse is
  // Q^* = (H_0 H_1 ...)^T
  typename RhsType::PlainObject c(rhs);
  c.applyOnTheLeft(
      householderSequence(matrixQTZ(), hCoeffs()).setLength(rank).transpose());
  // Solve T z = c(1:rank, :)
  dst.topRows(rank) = matrixT()
                          .topLeftCorner(rank, rank)
                          .template triangularView<Upper>()
                          .solve(c.topRows(rank));
  const Index cols = this->cols();
  if (rank < cols) {
    // Compute y = Z^* * [ z ]
    //                   [ 0 ]
    dst.bottomRows(cols - rank).setZero();
    applyZAdjointOnTheLeftInPlace(dst);
  }
  // Undo permutation to get x = P^{-1} * y.
  dst = colsPermutation() * dst;
}
References eigen_assert, and Eigen::householderSequence().
absDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::CompleteOrthogonalDecomposition< MatrixType >::absDeterminant
Returns
the absolute value of the determinant of the matrix of which *this is the complete orthogonal decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the complete orthogonal decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
logAbsDeterminant(), MatrixBase::determinant()
{
  return m_cpqr.absDeterminant();
}
applyZAdjointOnTheLeftInPlace()
template<typename MatrixType > template<typename Rhs > void Eigen::CompleteOrthogonalDecomposition< MatrixType >::applyZAdjointOnTheLeftInPlace (Rhs & rhs) const protected
Overwrites rhs with .
                    {
  const Index cols = this->cols();
  const Index nrhs = rhs.cols();
  const Index rank = this->rank();
  Matrix<typename MatrixType::Scalar, Dynamic, 1> temp((std::max)(cols, nrhs));
  for (Index k = 0; k < rank; ++k) {
    if (k != rank - 1) {
      rhs.row(k).swap(rhs.row(rank - 1));
    }
    rhs.middleRows(rank - 1, cols - rank + 1)
        .applyHouseholderOnTheLeft(
            matrixQTZ().row(k).tail(cols - rank).adjoint(), zCoeffs()(k),
            &temp(0));
    if (k != rank - 1) {
      rhs.row(k).swap(rhs.row(rank - 1));
    }
  }
}
References row(), and tail().
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixZ().
check_template_parameters()
template<typename _MatrixType > static void Eigen::CompleteOrthogonalDecomposition< _MatrixType >::check_template_parameters () inline static protected
{
    EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
  }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
cols()
template<typename _MatrixType > Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::cols () const inline
{ return m_cpqr.cols(); }
References Eigen::ColPivHouseholderQR< _MatrixType >::cols(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
colsPermutation()
template<typename _MatrixType > const PermutationType & Eigen::CompleteOrthogonalDecomposition< _MatrixType >::colsPermutation () const inline
Returns
a const reference to the column permutation matrix
{
    return m_cpqr.colsPermutation();
  }
References Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
compute()
template<typename _MatrixType > template<typename InputType > CompleteOrthogonalDecomposition & Eigen::CompleteOrthogonalDecomposition< _MatrixType >::compute (const EigenBase< InputType > & matrix) inline
{
    // Compute the column pivoted QR factorization A P = Q R.
    m_cpqr.compute(matrix);
    computeInPlace();
    return *this;
  }
References Eigen::ColPivHouseholderQR< _MatrixType >::compute(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::computeInPlace(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition().
computeInPlace()
template<typename MatrixType > void Eigen::CompleteOrthogonalDecomposition< MatrixType >::computeInPlace protected
Performs the complete orthogonal decomposition of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class CompleteOrthogonalDecomposition, CompleteOrthogonalDecomposition(const MatrixType&)
{
  check_template_parameters();
  // the column permutation is stored as int indices, so just to be sure:
  eigen_assert(m_cpqr.cols() <= NumTraits<int>::highest());
  const Index rank = m_cpqr.rank();
  const Index cols = m_cpqr.cols();
  const Index rows = m_cpqr.rows();
  m_zCoeffs.resize((std::min)(rows, cols));
  m_temp.resize(cols);
  if (rank < cols) {
    // We have reduced the (permuted) matrix to the form
    //   [R11 R12]
    //   [ 0  R22]
    // where R11 is r-by-r (r = rank) upper triangular, R12 is
    // r-by-(n-r), and R22 is empty or the norm of R22 is negligible.
    // We now compute the complete orthogonal decomposition by applying
    // Householder transformations from the right to the upper trapezoidal
    // matrix X = [R11 R12] to zero out R12 and obtain the factorization
    // [R11 R12] = [T11 0] * Z, where T11 is r-by-r upper triangular and
    // Z = Z(0) * Z(1) ... Z(r-1) is an n-by-n orthogonal matrix.
    // We store the data representing Z in R12 and m_zCoeffs.
    for (Index k = rank - 1; k >= 0; --k) {
      if (k != rank - 1) {
        // Given the API for Householder reflectors, it is more convenient if
        // we swap the leading parts of columns k and r-1 (zero-based) to form
        // the matrix X_k = [X(0:k, k), X(0:k, r:n)]
        m_cpqr.m_qr.col(k).head(k + 1).swap(
            m_cpqr.m_qr.col(rank - 1).head(k + 1));
      }
      // Construct Householder reflector Z(k) to zero out the last row of X_k,
      // i.e. choose Z(k) such that
      // [X(k, k), X(k, r:n)] * Z(k) = [beta, 0, .., 0].
      RealScalar beta;
      m_cpqr.m_qr.row(k)
          .tail(cols - rank + 1)
          .makeHouseholderInPlace(m_zCoeffs(k), beta);
      m_cpqr.m_qr(k, rank - 1) = beta;
      if (k > 0) {
        // Apply Z(k) to the first k rows of X_k
        m_cpqr.m_qr.topRightCorner(k, cols - rank + 1)
            .applyHouseholderOnTheRight(
                m_cpqr.m_qr.row(k).tail(cols - rank).transpose(), m_zCoeffs(k),
                &m_temp(0));
      }
      if (k != rank - 1) {
        // Swap X(0:k,k) back to its proper location.
        m_cpqr.m_qr.col(k).head(k + 1).swap(
            m_cpqr.m_qr.col(rank - 1).head(k + 1));
      }
    }
  }
}
References eigen_assert.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::CompleteOrthogonalDecomposition(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::compute().
dimensionOfKernel()
template<typename _MatrixType > Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the complete orthogonal decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{ return m_cpqr.dimensionOfKernel(); }
References Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
hCoeffs()
template<typename _MatrixType > const HCoeffsType & Eigen::CompleteOrthogonalDecomposition< _MatrixType >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
{ return m_cpqr.hCoeffs(); }
References Eigen::ColPivHouseholderQR< _MatrixType >::hCoeffs(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
householderQ()
template<typename MatrixType > CompleteOrthogonalDecomposition< MatrixType >::HouseholderSequenceType Eigen::CompleteOrthogonalDecomposition< MatrixType >::householderQ (void) const
Returns
the matrix Q as a sequence of householder transformations
{
  return m_cpqr.householderQ();
}
info()
template<typename _MatrixType > ComputationInfo Eigen::CompleteOrthogonalDecomposition< _MatrixType >::info () const inline
Reports whether the complete orthogonal decomposition was succesful.
Note
This function always returns Success. It is provided for compatibility with other factorization routines.
Returns
Success
{
    eigen_assert(m_cpqr.m_isInitialized && "Decomposition is not initialized.");
    return Success;
  }
References eigen_assert, Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::Success.
isInjective()
template<typename _MatrixType > bool Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{ return m_cpqr.isInjective(); }
References Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
isInvertible()
template<typename _MatrixType > bool Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the complete orthogonal decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{ return m_cpqr.isInvertible(); }
References Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
isSurjective()
template<typename _MatrixType > bool Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{ return m_cpqr.isSurjective(); }
References Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
logAbsDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::CompleteOrthogonalDecomposition< MatrixType >::logAbsDeterminant
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the complete orthogonal decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the complete orthogonal decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
absDeterminant(), MatrixBase::determinant()
{
  return m_cpqr.logAbsDeterminant();
}
matrixQ()
template<typename _MatrixType > HouseholderSequenceType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixQ (void) const inline
{ return m_cpqr.householderQ(); }
References Eigen::ColPivHouseholderQR< _MatrixType >::householderQ(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
matrixQTZ()
template<typename _MatrixType > const MatrixType & Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixQTZ () const inline
Returns
a reference to the matrix where the complete orthogonal decomposition is stored
{ return m_cpqr.matrixQR(); }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, and Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR().
matrixT()
template<typename _MatrixType > const MatrixType & Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixT () const inline
Returns
a reference to the matrix where the complete orthogonal decomposition is stored.
Warning
The strict lower part and
cols() - rank()
right columns of this matrix contains internal values. Only the upper triangular part should be referenced. To get it, use
matrixT().template triangularView<Upper>()
For rank-deficient matrices, use
matrixR().topLeftCorner(rank(), rank()).template triangularView<Upper>()
{ return m_cpqr.matrixQR(); }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, and Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR().
matrixZ()
template<typename _MatrixType > MatrixType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixZ () const inline
Returns
the matrix Z.
{
    MatrixType Z = MatrixType::Identity(m_cpqr.cols(), m_cpqr.cols());
    applyZAdjointOnTheLeftInPlace(Z);
    return Z.adjoint();
  }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::applyZAdjointOnTheLeftInPlace(), Eigen::ColPivHouseholderQR< _MatrixType >::cols(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr.
maxPivot()
template<typename _MatrixType > RealScalar Eigen::CompleteOrthogonalDecomposition< _MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of R.
{ return m_cpqr.maxPivot(); }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, and Eigen::ColPivHouseholderQR< _MatrixType >::maxPivot().
nonzeroPivots()
template<typename _MatrixType > Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the complete orthogonal decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
{ return m_cpqr.nonzeroPivots(); }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, and Eigen::ColPivHouseholderQR< _MatrixType >::nonzeroPivots().
pseudoInverse()
template<typename _MatrixType > const Inverse< CompleteOrthogonalDecomposition > Eigen::CompleteOrthogonalDecomposition< _MatrixType >::pseudoInverse () const inline
Returns
the pseudo-inverse of the matrix of which *this is the complete orthogonal decomposition.
Warning
: Do not compute this->pseudoInverse()*rhs to solve a linear systems. It is more efficient and numerically stable to call this->solve(rhs).
  {
    return Inverse<CompleteOrthogonalDecomposition>(*this);
  }
rank()
template<typename _MatrixType > Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the complete orthogonal decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{ return m_cpqr.rank(); }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, and Eigen::ColPivHouseholderQR< _MatrixType >::rank().
rows()
template<typename _MatrixType > Index Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rows () const inline
{ return m_cpqr.rows(); }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, and Eigen::ColPivHouseholderQR< _MatrixType >::rows().
setThreshold() [1/2]
template<typename _MatrixType > CompleteOrthogonalDecomposition & Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. Most be called before calling compute().
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
{
    m_cpqr.setThreshold(threshold);
    return *this;
  }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::threshold().
setThreshold() [2/2]
template<typename _MatrixType > CompleteOrthogonalDecomposition & Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
{
    m_cpqr.setThreshold(Default);
    return *this;
  }
References Eigen::Default, Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, and Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold().
solve()
template<typename _MatrixType > template<typename Rhs > const Solve< CompleteOrthogonalDecomposition, Rhs > Eigen::CompleteOrthogonalDecomposition< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method computes the minimum-norm solution X to a least squares problem
where A is the matrix of which *this is the complete orthogonal decomposition.
Parameters
b the right-hand sides of the problem to solve.
Returns
a solution.
{
    eigen_assert(m_cpqr.m_isInitialized &&
                 "CompleteOrthogonalDecomposition is not initialized.");
    return Solve<CompleteOrthogonalDecomposition, Rhs>(*this, b.derived());
  }
References eigen_assert, Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, and Eigen::ColPivHouseholderQR< _MatrixType >::m_isInitialized.
threshold()
template<typename _MatrixType > RealScalar Eigen::CompleteOrthogonalDecomposition< _MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
{ return m_cpqr.threshold(); }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr, and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold().
zCoeffs()
template<typename _MatrixType > const HCoeffsType & Eigen::CompleteOrthogonalDecomposition< _MatrixType >::zCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Z.
For advanced uses only.
{ return m_zCoeffs; }
References Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_zCoeffs.
Member Data Documentation
m_cpqr
template<typename _MatrixType > ColPivHouseholderQR<MatrixType> Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_cpqr protected
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::cols(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::colsPermutation(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::compute(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::dimensionOfKernel(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::hCoeffs(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::info(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInjective(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isInvertible(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::isSurjective(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixQ(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixQTZ(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixT(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::matrixZ(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::maxPivot(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::nonzeroPivots(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rank(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::rows(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::setThreshold(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::solve(), and Eigen::CompleteOrthogonalDecomposition< _MatrixType >::threshold().
m_temp
template<typename _MatrixType > RowVectorType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_temp protected
m_zCoeffs
template<typename _MatrixType > HCoeffsType Eigen::CompleteOrthogonalDecomposition< _MatrixType >::m_zCoeffs protected
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::zCoeffs().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/util/ForwardDeclarations.h
src/eigen/Eigen/src/QR/CompleteOrthogonalDecomposition.h