Prusa Slicer: Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar > Class Template Reference
Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar > Class Template Reference
#include <src/eigen/Eigen/src/Core/products/GeneralMatrixMatrix.h>
Public Member Functions
level3_blocking ()
Index mc () const
Index nc () const
Index kc () const
LhsScalar * blockA ()
RhsScalar * blockB ()
Protected Attributes
LhsScalar * m_blockA
RhsScalar * m_blockB
Index m_mc
Index m_nc
Index m_kc
Private Types
typedef _LhsScalar LhsScalar
typedef _RhsScalar RhsScalar
Detailed Description
template<typename _LhsScalar, typename _RhsScalar>
class Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >
Member Typedef Documentation
LhsScalar
template<typename _LhsScalar , typename _RhsScalar > typedef _LhsScalar Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::LhsScalar private
RhsScalar
template<typename _LhsScalar , typename _RhsScalar > typedef _RhsScalar Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::RhsScalar private
Constructor & Destructor Documentation
level3_blocking()
template<typename _LhsScalar , typename _RhsScalar > Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::level3_blocking () inline
      : m_blockA(0), m_blockB(0), m_mc(0), m_nc(0), m_kc(0)
    {}
Member Function Documentation
blockA()
template<typename _LhsScalar , typename _RhsScalar > LhsScalar * Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA () inline
{ return m_blockA; }
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_blockA.
Referenced by Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run().
blockB()
template<typename _LhsScalar , typename _RhsScalar > RhsScalar * Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB () inline
{ return m_blockB; }
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_blockB.
Referenced by Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run().
kc()
template<typename _LhsScalar , typename _RhsScalar > Index Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc () const inline
{ return m_kc; }
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_kc.
Referenced by Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run().
mc()
template<typename _LhsScalar , typename _RhsScalar > Index Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc () const inline
{ return m_mc; }
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_mc.
Referenced by Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run().
nc()
template<typename _LhsScalar , typename _RhsScalar > Index Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::nc () const inline
{ return m_nc; }
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_nc.
Referenced by Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run().
Member Data Documentation
m_blockA
template<typename _LhsScalar , typename _RhsScalar > LhsScalar* Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_blockA protected
Referenced by Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA().
m_blockB
template<typename _LhsScalar , typename _RhsScalar > RhsScalar* Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_blockB protected
Referenced by Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB().
m_kc
template<typename _LhsScalar , typename _RhsScalar > Index Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_kc protected
Referenced by Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc().
m_mc
template<typename _LhsScalar , typename _RhsScalar > Index Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_mc protected
Referenced by Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc().
m_nc
template<typename _LhsScalar , typename _RhsScalar > Index Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_nc protected
Referenced by Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::nc().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/products/GeneralMatrixMatrix.h