Prusa Slicer: MyDocument Struct Reference
MyDocument Struct Reference
Public Member Functions
MyDocument (const char *name, bool open=true, const ImVec4 &color=ImVec4(1.0f, 1.0f, 1.0f, 1.0f))
void DoOpen ()
void DoQueueClose ()
void DoForceClose ()
void DoSave ()
Static Public Member Functions
static void DisplayContents (MyDocument *doc)
static void DisplayContextMenu (MyDocument *doc)
Public Attributes
const char * Name
bool Open
bool OpenPrev
bool Dirty
bool WantClose
ImVec4 Color
Detailed Description
Constructor & Destructor Documentation
MyDocument()
MyDocument::MyDocument (const char * name, bool open = true, const ImVec4 & color = ImVec4(1.0f, 1.0f, 1.0f, 1.0f)) inline
    {
        Name = name;
        Open = OpenPrev = open;
        Dirty = false;
        WantClose = false;
        Color = color;
    }
References Color, Dirty, Name, Open, OpenPrev, and WantClose.
Member Function Documentation
DisplayContents()
static void MyDocument::DisplayContents (MyDocument * doc) inline static
    {
        ImGui::PushID(doc);
        ImGui::Text("Document \"%s\"", doc->Name);
        ImGui::PushStyleColor(ImGuiCol_Text, doc->Color);
        ImGui::TextWrapped("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");
        ImGui::PopStyleColor();
        if (ImGui::Button("Modify", ImVec2(100, 0)))
            doc->Dirty = true;
        ImGui::SameLine();
        if (ImGui::Button("Save", ImVec2(100, 0)))
            doc->DoSave();
        ImGui::ColorEdit3("color", &doc->Color.x);  // Useful to test drag and drop and hold-dragged-to-open-tab behavior.
        ImGui::PopID();
    }
References ImGui::Button(), Color, ImGui::ColorEdit3(), Dirty, DoSave(), ImGuiCol_Text, Name, ImGui::PopID(), ImGui::PopStyleColor(), ImGui::PushID(), ImGui::PushStyleColor(), ImGui::SameLine(), ImGui::Text(), ImGui::TextWrapped(), and ImVec4::x.
Referenced by ShowExampleAppDocuments().
DisplayContextMenu()
static void MyDocument::DisplayContextMenu (MyDocument * doc) inline static
    {
        if (!ImGui::BeginPopupContextItem())
            return;
        char buf[256];
        sprintf(buf, "Save %s", doc->Name);
        if (ImGui::MenuItem(buf, "CTRL+S", false, doc->Open))
            doc->DoSave();
        if (ImGui::MenuItem("Close", "CTRL+W", false, doc->Open))
            doc->DoQueueClose();
        ImGui::EndPopup();
    }
References ImGui::BeginPopupContextItem(), DoQueueClose(), DoSave(), ImGui::EndPopup(), ImGui::MenuItem(), Name, and Open.
Referenced by ShowExampleAppDocuments().
DoForceClose()
void MyDocument::DoForceClose () inline
{ Open = false; Dirty = false; }
References Dirty, and Open.
Referenced by ShowExampleAppDocuments().
DoOpen()
void MyDocument::DoOpen () inline
{ Open = true; }
References Open.
Referenced by ShowExampleAppDocuments().
DoQueueClose()
void MyDocument::DoQueueClose () inline
{ WantClose = true; }
References WantClose.
Referenced by DisplayContextMenu(), and ShowExampleAppDocuments().
DoSave()
void MyDocument::DoSave () inline
{ Dirty = false; }
References Dirty.
Referenced by DisplayContents(), and DisplayContextMenu().
Member Data Documentation
Color
ImVec4 MyDocument::Color
Referenced by MyDocument(), and DisplayContents().
Dirty
bool MyDocument::Dirty
Referenced by MyDocument(), DisplayContents(), DoForceClose(), DoSave(), and ShowExampleAppDocuments().
Name
const char* MyDocument::Name
Referenced by MyDocument(), DisplayContents(), DisplayContextMenu(), NotifyOfDocumentsClosedElsewhere(), and ShowExampleAppDocuments().
Open
bool MyDocument::Open
Referenced by MyDocument(), DisplayContextMenu(), DoForceClose(), DoOpen(), NotifyOfDocumentsClosedElsewhere(), and ShowExampleAppDocuments().
OpenPrev
bool MyDocument::OpenPrev
Referenced by MyDocument(), and NotifyOfDocumentsClosedElsewhere().
WantClose
bool MyDocument::WantClose
Referenced by MyDocument(), DoQueueClose(), and ShowExampleAppDocuments().
The documentation for this struct was generated from the following file:
src/imgui/imgui_demo.cpp