Prusa Slicer: Slic3r::BonjourRequest Struct Reference
Slic3r::BonjourRequest Struct Reference
#include <src/slic3r/Utils/Bonjour.hpp>
Static Public Member Functions
static boost::optional< BonjourRequest > make_PTR (const std::string &service, const std::string &protocol)
static boost::optional< BonjourRequest > make_A (const std::string &hostname)
static boost::optional< BonjourRequest > make_AAAA (const std::string &hostname)
Public Attributes
std::vector< char > m_data
Static Public Attributes
static const boost::asio::ip::address_v4 MCAST_IP4 { 0xe00000fb }
static const boost::asio::ip::address_v6 MCAST_IP6 = asio::ip::make_address_v6("ff02::fb")
static const uint16_t MCAST_PORT = 5353
Private Member Functions
BonjourRequest (std::vector< char > &&data)
Detailed Description
Constructor & Destructor Documentation
BonjourRequest()
Slic3r::BonjourRequest::BonjourRequest (std::vector< char > && data) inline private
: m_data(std::move(data)) {}
Member Function Documentation
make_A()
optional< BonjourRequest > Slic3r::BonjourRequest::make_A (const std::string & hostname) static
{
  // todo: why is this and what is real max
  if (hostname.size() > 30) {
    return boost::none;
  }
  std::vector<char> data;
  data.reserve(hostname.size() + 18);
  // Add metadata
  static const unsigned char rq_meta[] = {
    0x00, 0x00, // Query ID (zero for mDNS)
    0x00, 0x00, // Flags
    0x00, 0x01, // One query
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00   // Zero Answer, Authority, and Additional RRs
  };
  std::copy(rq_meta, rq_meta + sizeof(rq_meta), std::back_inserter(data));
  // Add hostname without .local
  data.push_back(hostname.size());
  data.insert(data.end(), hostname.begin(), hostname.end());
  // Add the rest of A record
  static const unsigned char ptr_tail[] = {
    0x05, // length of "local"
    0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x00,// "local" string and terminator
    0x00, 0x01, // Type A
    0x00, 0xff, // Class - 01 is internet 0xff is any
  };
  std::copy(ptr_tail, ptr_tail + sizeof(ptr_tail), std::back_inserter(data));
  return BonjourRequest(std::move(data));
}
Referenced by Slic3r::ResolveSocket::create_requests().
make_AAAA()
optional< BonjourRequest > Slic3r::BonjourRequest::make_AAAA (const std::string & hostname) static
{
  // todo: why is this and what is real max
  if (hostname.size() > 30) {
    return boost::none;
  }
  std::vector<char> data;
  data.reserve(hostname.size() + 18);
  // Add metadata
  static const unsigned char rq_meta[] = {
    0x00, 0x00, // Query ID (zero for mDNS)
    0x00, 0x00, // Flags
    0x00, 0x01, // One query
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00   // Zero Answer, Authority, and Additional RRs
  };
  std::copy(rq_meta, rq_meta + sizeof(rq_meta), std::back_inserter(data));
  // Add hostname without .local
  data.push_back(hostname.size());
  data.insert(data.end(), hostname.begin(), hostname.end());
  // Add the rest of A record
  static const unsigned char ptr_tail[] = {
    0x05, // length of "local"
    0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x00, // "local" string and terminator
    0x00, 0x1c, // Type AAAA
    0x00, 0xff, // Class - 01 is internet 0xff is any
  };
  std::copy(ptr_tail, ptr_tail + sizeof(ptr_tail), std::back_inserter(data));
  return BonjourRequest(std::move(data));
}
Referenced by Slic3r::ResolveSocket::create_requests().
make_PTR()
optional< BonjourRequest > Slic3r::BonjourRequest::make_PTR (const std::string & service, const std::string & protocol) static
{
  if (service.size() > 15 || protocol.size() > 15) {
    return boost::none;
  }
  std::vector<char> data;
  data.reserve(service.size() + 18);
  // Add metadata
  static const unsigned char rq_meta[] = {
    0x00, 0x00, // Query ID (zero for mDNS)
    0x00, 0x00, // Flags
    0x00, 0x01, // One query
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00   // Zero Answer, Authority, and Additional RRs
  };
  std::copy(rq_meta, rq_meta + sizeof(rq_meta), std::back_inserter(data));
  // Add PTR query name
  data.push_back(service.size() + 1);
  data.push_back('_');
  data.insert(data.end(), service.begin(), service.end());
  data.push_back(protocol.size() + 1);
  data.push_back('_');
  data.insert(data.end(), protocol.begin(), protocol.end());
  // Add the rest of PTR record
  static const unsigned char ptr_tail[] = {
    0x05, // length of "label"
    0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x00, // "label" string and terminator
    0x00, 0x0c, // Type PTR
    0x00, 0xff, // Class ANY
  };
  std::copy(ptr_tail, ptr_tail + sizeof(ptr_tail), std::back_inserter(data));
  return BonjourRequest(std::move(data));
}
Referenced by Slic3r::LookupSocket::create_request().
Member Data Documentation
m_data
std::vector<char> Slic3r::BonjourRequest::m_data
MCAST_IP4
const asio::ip::address_v4 Slic3r::BonjourRequest::MCAST_IP4 { 0xe00000fb } static
Referenced by Slic3r::Bonjour::priv::lookup_perform(), and Slic3r::Bonjour::priv::resolve_perform().
MCAST_IP6
const asio::ip::address_v6 Slic3r::BonjourRequest::MCAST_IP6 = asio::ip::make_address_v6("ff02::fb") static
Referenced by Slic3r::Bonjour::priv::lookup_perform(), and Slic3r::Bonjour::priv::resolve_perform().
MCAST_PORT
const uint16_t Slic3r::BonjourRequest::MCAST_PORT = 5353 static
The documentation for this struct was generated from the following files:
src/slic3r/Utils/Bonjour.hpp
src/slic3r/Utils/Bonjour.cpp