Prusa Slicer: Slic3r::clonable_ptr< T > Class Template Reference
Slic3r::clonable_ptr< T > Class Template Reference
#include <src/libslic3r/clonable_ptr.hpp>
Public Types
typedef T element_type
The type of the managed object, aliased as member type.
Public Member Functions
clonable_ptr () noexcept
Default constructor.
clonable_ptr (T *p) noexcept
Constructor with the provided pointer to manage.
clonable_ptr (const clonable_ptr &rhs)
Copy constructor, clones by calling the rhs.clone() method.
clonable_ptr (clonable_ptr &&rhs) noexcept
Move constructor, never throws.
clonable_ptr & operator= (const clonable_ptr &rhs)
Assignment operator.
clonable_ptr & operator= (clonable_ptr &&rhs)
Move operator, never throws.
~clonable_ptr () noexcept
the destructor releases its ownership and destroy the object
void reset () noexcept
this reset releases its ownership and destroy the object
void reset (T *p) noexcept
this reset release its ownership and re-acquire another one
void swap (clonable_ptr &rhs) noexcept
Swap method for the copy-and-swap idiom (copy constructor and swap method)
void release () noexcept
release the ownership of the px pointer without destroying the object!
operator bool () const noexcept
T & operator* () const noexcept
T * operator-> () const noexcept
T * get () const noexcept
Private Member Functions
void destroy () noexcept
release the ownership of the px pointer and destroy the object
void release () const noexcept
hack: const-cast release the ownership of the px pointer without destroying the object!
Private Attributes
T * px
Native pointer.
Detailed Description
template<class T>
class Slic3r::clonable_ptr< T >
Member Typedef Documentation
element_type
template<class T > typedef T Slic3r::clonable_ptr< T >::element_type
The type of the managed object, aliased as member type.
Constructor & Destructor Documentation
clonable_ptr() [1/4]
template<class T > Slic3r::clonable_ptr< T >::clonable_ptr () inline noexcept
Default constructor.
                            :
        px(nullptr)
    {
    }
clonable_ptr() [2/4]
template<class T > Slic3r::clonable_ptr< T >::clonable_ptr (T * p) inline explicit noexcept
Constructor with the provided pointer to manage.
                                         :
        px(p)
    {
    }
clonable_ptr() [3/4]
template<class T > Slic3r::clonable_ptr< T >::clonable_ptr (const clonable_ptr< T > & rhs) inline
Copy constructor, clones by calling the rhs.clone() method.
                                          :
    px(rhs ? rhs.px->clone() : nullptr)
    {
    }
clonable_ptr() [4/4]
template<class T > Slic3r::clonable_ptr< T >::clonable_ptr (clonable_ptr< T > && rhs) inline noexcept
Move constructor, never throws.
                                              :
        px(rhs.px)
    {
        rhs.px = nullptr;
    }
~clonable_ptr()
template<class T > Slic3r::clonable_ptr< T >::~clonable_ptr () inline noexcept
the destructor releases its ownership and destroy the object
    {
        destroy();
    }
References Slic3r::clonable_ptr< T >::destroy().
Member Function Documentation
destroy()
template<class T > void Slic3r::clonable_ptr< T >::destroy () inline private noexcept
release the ownership of the px pointer and destroy the object
    {
        delete px;
        px = nullptr;
    }
References Slic3r::clonable_ptr< T >::px.
Referenced by Slic3r::clonable_ptr< T >::~clonable_ptr(), Slic3r::clonable_ptr< T >::reset(), and Slic3r::clonable_ptr< T >::reset().
get()
template<class T > T * Slic3r::clonable_ptr< T >::get () const inline noexcept
    {
        // no assert, can return nullptr
        return px;
    }
References Slic3r::clonable_ptr< T >::px.
Referenced by Slic3r::ConfigOptionDef::get_default_value().
operator bool()
template<class T > Slic3r::clonable_ptr< T >::operator bool () const inline noexcept
    {
        return (nullptr != px); // TODO nullptrptr
    }
References Slic3r::clonable_ptr< T >::px.
operator*()
template<class T > T & Slic3r::clonable_ptr< T >::operator* () const inline noexcept
    {
        assert(nullptr != px);
        return *px;
    }
References Slic3r::clonable_ptr< T >::px.
operator->()
template<class T > T * Slic3r::clonable_ptr< T >::operator-> () const inline noexcept
    {
        assert(nullptr != px);
        return px;
    }
References Slic3r::clonable_ptr< T >::px.
operator=() [1/2]
template<class T > clonable_ptr & Slic3r::clonable_ptr< T >::operator= (clonable_ptr< T > && rhs) inline
Move operator, never throws.
    {
    delete px;
        px = rhs.px;
        rhs.px = nullptr;
        return *this;
    }
References Slic3r::clonable_ptr< T >::px.
operator=() [2/2]
template<class T > clonable_ptr & Slic3r::clonable_ptr< T >::operator= (const clonable_ptr< T > & rhs) inline
Assignment operator.
    {
    delete px;
    px = rhs ? rhs.px->clone() : nullptr;
        return *this;
    }
References Slic3r::clonable_ptr< T >::px.
release() [1/2]
template<class T > void Slic3r::clonable_ptr< T >::release () const inline private noexcept
hack: const-cast release the ownership of the px pointer without destroying the object!
    {
        px = nullptr;
    }
References Slic3r::clonable_ptr< T >::px.
release() [2/2]
template<class T > void Slic3r::clonable_ptr< T >::release () inline noexcept
release the ownership of the px pointer without destroying the object!
    {
        px = nullptr;
    }
References Slic3r::clonable_ptr< T >::px.
reset() [1/2]
template<class T > void Slic3r::clonable_ptr< T >::reset () inline noexcept
this reset releases its ownership and destroy the object
    {
        destroy();
    }
References Slic3r::clonable_ptr< T >::destroy().
reset() [2/2]
template<class T > void Slic3r::clonable_ptr< T >::reset (T * p) inline noexcept
this reset release its ownership and re-acquire another one
    {
        assert((nullptr == p) || (px != p)); // auto-reset not allowed
        destroy();
        px = p;
    }
References Slic3r::clonable_ptr< T >::destroy(), and Slic3r::clonable_ptr< T >::px.
swap()
template<class T > void Slic3r::clonable_ptr< T >::swap (clonable_ptr< T > & rhs) inline noexcept
Swap method for the copy-and-swap idiom (copy constructor and swap method)
    {
        T *tmp = px;
        px = rhs.px;
        rhs.px = tmp;
    }
References Slic3r::clonable_ptr< T >::px.
Member Data Documentation
px
template<class T > T* Slic3r::clonable_ptr< T >::px private
Native pointer.
Referenced by Slic3r::clonable_ptr< T >::destroy(), Slic3r::clonable_ptr< T >::get(), Slic3r::clonable_ptr< T >::operator bool(), Slic3r::clonable_ptr< T >::operator*(), Slic3r::clonable_ptr< T >::operator->(), Slic3r::clonable_ptr< T >::operator=(), Slic3r::clonable_ptr< T >::operator=(), Slic3r::clonable_ptr< T >::release(), Slic3r::clonable_ptr< T >::release(), Slic3r::clonable_ptr< T >::reset(), and Slic3r::clonable_ptr< T >::swap().
The documentation for this class was generated from the following file:
src/libslic3r/clonable_ptr.hpp