Prusa Slicer: Slic3r::GUI::TransformHelper Class Reference
Slic3r::GUI::TransformHelper Class Reference
Classes
struct Cache
Static Public Member Functions
static Vec3d model_to_world (const Vec3d &model, const Transform3d &world_matrix)
static Vec4d world_to_clip (const Vec3d &world, const Matrix4d &projection_view_matrix)
static Vec3d clip_to_ndc (const Vec4d &clip)
static Vec2d ndc_to_ss (const Vec3d &ndc, const std::array< int, 4 > &viewport)
static Vec4d model_to_clip (const Vec3d &model, const Transform3d &world_matrix, const Matrix4d &projection_view_matrix)
static Vec3d model_to_ndc (const Vec3d &model, const Transform3d &world_matrix, const Matrix4d &projection_view_matrix)
static Vec2d model_to_ss (const Vec3d &model, const Transform3d &world_matrix, const Matrix4d &projection_view_matrix, const std::array< int, 4 > &viewport)
static Vec2d world_to_ss (const Vec3d &world, const Matrix4d &projection_view_matrix, const std::array< int, 4 > &viewport)
static const Matrix4d & ndc_to_ss_matrix (const std::array< int, 4 > &viewport)
static const Transform3d ndc_to_ss_matrix_inverse (const std::array< int, 4 > &viewport)
Static Private Member Functions
static void update (const std::array< int, 4 > &viewport)
Static Private Attributes
static Cache s_cache = { { 0, 0, 0, 0 }, Matrix4d::Identity(), Transform3d::Identity() }
Detailed Description
Class Documentation
Slic3r::GUI::TransformHelper::Cache
struct Slic3r::GUI::TransformHelper::Cache
Class Members
Matrix4d ndc_to_ss_matrix
Transform3d ndc_to_ss_matrix_inverse
array< int, 4 > viewport
Member Function Documentation
clip_to_ndc()
static Vec3d Slic3r::GUI::TransformHelper::clip_to_ndc (const Vec4d & clip) inline static
{
        return Vec3d(clip.x(), clip.y(), clip.z()) / clip.w();
    }
Referenced by model_to_ndc(), model_to_ss(), and world_to_ss().
model_to_clip()
static Vec4d Slic3r::GUI::TransformHelper::model_to_clip (const Vec3d & model, const Transform3d & world_matrix, const Matrix4d & projection_view_matrix) inline static
{
        return world_to_clip(model_to_world(model, world_matrix), projection_view_matrix);
    }
References model_to_world(), and world_to_clip().
model_to_ndc()
static Vec3d Slic3r::GUI::TransformHelper::model_to_ndc (const Vec3d & model, const Transform3d & world_matrix, const Matrix4d & projection_view_matrix) inline static
{
        return clip_to_ndc(world_to_clip(model_to_world(model, world_matrix), projection_view_matrix));
    }
References clip_to_ndc(), model_to_world(), and world_to_clip().
model_to_ss()
static Vec2d Slic3r::GUI::TransformHelper::model_to_ss (const Vec3d & model, const Transform3d & world_matrix, const Matrix4d & projection_view_matrix, const std::array< int, 4 > & viewport) inline static
{
        return ndc_to_ss(clip_to_ndc(world_to_clip(model_to_world(model, world_matrix), projection_view_matrix)), viewport);
    }
References clip_to_ndc(), model_to_world(), ndc_to_ss(), and world_to_clip().
model_to_world()
static Vec3d Slic3r::GUI::TransformHelper::model_to_world (const Vec3d & model, const Transform3d & world_matrix) inline static
{
        return world_matrix * model;
    }
Referenced by model_to_clip(), model_to_ndc(), and model_to_ss().
ndc_to_ss()
static Vec2d Slic3r::GUI::TransformHelper::ndc_to_ss (const Vec3d & ndc, const std::array< int, 4 > & viewport) inline static
{
        const double half_w = 0.5 * double(viewport[2]);
        const double half_h = 0.5 * double(viewport[3]);
        return { half_w * ndc.x() + double(viewport[0]) + half_w, half_h * ndc.y() + double(viewport[1]) + half_h };
    };
Referenced by model_to_ss(), and world_to_ss().
ndc_to_ss_matrix()
static const Matrix4d & Slic3r::GUI::TransformHelper::ndc_to_ss_matrix (const std::array< int, 4 > & viewport) inline static
{
        update(viewport);
        return s_cache.ndc_to_ss_matrix;
    }
References Slic3r::GUI::TransformHelper::Cache::ndc_to_ss_matrix, s_cache, and update().
ndc_to_ss_matrix_inverse()
static const Transform3d Slic3r::GUI::TransformHelper::ndc_to_ss_matrix_inverse (const std::array< int, 4 > & viewport) inline static
{
        update(viewport);
        return s_cache.ndc_to_ss_matrix_inverse;
    }
References Slic3r::GUI::TransformHelper::Cache::ndc_to_ss_matrix_inverse, s_cache, and update().
Referenced by Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
update()
static void Slic3r::GUI::TransformHelper::update (const std::array< int, 4 > & viewport) inline static private
{
        if (s_cache.viewport == viewport)
            return;
        const double half_w = 0.5 * double(viewport[2]);
        const double half_h = 0.5 * double(viewport[3]);
        s_cache.ndc_to_ss_matrix << half_w, 0.0, 0.0, double(viewport[0]) + half_w,
            0.0, half_h, 0.0, double(viewport[1]) + half_h,
            0.0, 0.0, 1.0, 0.0,
            0.0, 0.0, 0.0, 1.0;
        s_cache.ndc_to_ss_matrix_inverse = s_cache.ndc_to_ss_matrix.inverse();
        s_cache.viewport = viewport;
    }
References Slic3r::GUI::TransformHelper::Cache::ndc_to_ss_matrix, Slic3r::GUI::TransformHelper::Cache::ndc_to_ss_matrix_inverse, s_cache, and Slic3r::GUI::TransformHelper::Cache::viewport.
Referenced by ndc_to_ss_matrix(), and ndc_to_ss_matrix_inverse().
world_to_clip()
static Vec4d Slic3r::GUI::TransformHelper::world_to_clip (const Vec3d & world, const Matrix4d & projection_view_matrix) inline static
{
        return projection_view_matrix * Vec4d(world.x(), world.y(), world.z(), 1.0);
    }
Referenced by model_to_clip(), model_to_ndc(), model_to_ss(), and world_to_ss().
world_to_ss()
static Vec2d Slic3r::GUI::TransformHelper::world_to_ss (const Vec3d & world, const Matrix4d & projection_view_matrix, const std::array< int, 4 > & viewport) inline static
{
        return ndc_to_ss(clip_to_ndc(world_to_clip(world, projection_view_matrix)), viewport);
    }
References clip_to_ndc(), ndc_to_ss(), and world_to_clip().
Referenced by Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
Member Data Documentation
s_cache
TransformHelper::Cache Slic3r::GUI::TransformHelper::s_cache = { { 0, 0, 0, 0 }, Matrix4d::Identity(), Transform3d::Identity() } static private
Referenced by ndc_to_ss_matrix(), ndc_to_ss_matrix_inverse(), and update().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Gizmos/GLGizmoMeasure.cpp