Prusa Slicer: Slic3r::ConfigHelpers Namespace Reference
Slic3r::ConfigHelpers Namespace Reference
Enumerations
enum class DeserializationSubstitution { Disabled , DefaultsToFalse , DefaultsToTrue }
enum class DeserializationResult { Loaded , Substituted , Failed }
Functions
bool looks_like_enum_value (std::string value)
bool enum_looks_like_true_value (std::string value)
Enumeration Type Documentation
DeserializationResult
enum class Slic3r::ConfigHelpers::DeserializationResult strong
Enumerator
Loaded
Substituted
Failed
{
      Loaded,
      Substituted,
      Failed,
    };
DeserializationSubstitution
enum class Slic3r::ConfigHelpers::DeserializationSubstitution strong
Enumerator
Disabled
DefaultsToFalse
DefaultsToTrue
{
    Disabled,
    DefaultsToFalse,
    DefaultsToTrue
  };
Function Documentation
enum_looks_like_true_value()
bool Slic3r::ConfigHelpers::enum_looks_like_true_value (std::string value) inline
{
    boost::trim(value);
    return boost::iequals(value, "enabled") || boost::iequals(value, "on");
  }
Referenced by Slic3r::ConfigOptionBoolsTempl< NULLABLE >::deserialize_with_substitutions(), and Slic3r::ConfigBase::set_deserialize_raw().
looks_like_enum_value()
bool Slic3r::ConfigHelpers::looks_like_enum_value (std::string value) inline
  {
    boost::trim(value);
    if (value.empty() || value.size() > 64 || ! isalpha(value.front()))
      return false;
    for (const char c : value)
      if (! (isalnum(c) || c == '_' || c == '-'))
        return false;
    return true;
  }
Referenced by Slic3r::ConfigOptionBoolsTempl< NULLABLE >::deserialize_with_substitutions(), and Slic3r::ConfigBase::set_deserialize_raw().