Prusa Slicer: Slic3r::ClipperUtils::SurfacesProvider Struct Reference
Slic3r::ClipperUtils::SurfacesProvider Struct Reference
#include <src/libslic3r/ClipperUtils.hpp>
Classes
struct iterator
Public Member Functions
SurfacesProvider (const Surfaces &surfaces)
iterator cbegin () const
iterator begin () const
iterator cend () const
iterator end () const
size_t size () const
Private Attributes
const Surfaces & m_surfaces
size_t m_size
Detailed Description
Constructor & Destructor Documentation
SurfacesProvider()
Slic3r::ClipperUtils::SurfacesProvider::SurfacesProvider (const Surfaces & surfaces) inline
                                                   : m_surfaces(surfaces) {
            m_size = 0;
            for (const Surface &surface : surfaces)
                m_size += surface.expolygon.holes.size() + 1;
        }
References m_size.
Member Function Documentation
begin()
iterator Slic3r::ClipperUtils::SurfacesProvider::begin () const inline
{ return this->cbegin(); }
References cbegin().
cbegin()
iterator Slic3r::ClipperUtils::SurfacesProvider::cbegin () const inline
{ return iterator(m_surfaces.cbegin()); }
References m_surfaces.
Referenced by begin().
cend()
iterator Slic3r::ClipperUtils::SurfacesProvider::cend () const inline
{ return iterator(m_surfaces.cend()); }
References m_surfaces.
Referenced by end().
end()
iterator Slic3r::ClipperUtils::SurfacesProvider::end () const inline
{ return this->cend(); }
References cend().
size()
size_t Slic3r::ClipperUtils::SurfacesProvider::size () const inline
{ return m_size; }
References m_size.
Member Data Documentation
m_size
size_t Slic3r::ClipperUtils::SurfacesProvider::m_size private
Referenced by SurfacesProvider(), and size().
m_surfaces
const Surfaces& Slic3r::ClipperUtils::SurfacesProvider::m_surfaces private
Referenced by cbegin(), and cend().
The documentation for this struct was generated from the following file:
src/libslic3r/ClipperUtils.hpp