Prusa Slicer: Slic3r::GUI::SceneRaycaster Class Reference
Slic3r::GUI::SceneRaycaster Class Reference
#include <src/slic3r/GUI/SceneRaycaster.hpp>
Classes
struct HitResult
Public Types
enum class EType { None , Bed , Volume , Gizmo }
enum class EIdBase { Bed = 0 , Volume = 1000 , Gizmo = 1000000 }
Public Member Functions
SceneRaycaster ()
std::shared_ptr< SceneRaycasterItem > add_raycaster (EType type, int picking_id, const MeshRaycaster &raycaster, const Transform3d &trafo, bool use_back_faces=false)
void remove_raycasters (EType type, int id)
void remove_raycasters (EType type)
void remove_raycaster (std::shared_ptr< SceneRaycasterItem > item)
std::vector< std::shared_ptr< SceneRaycasterItem > > * get_raycasters (EType type)
const std::vector< std::shared_ptr< SceneRaycasterItem > > * get_raycasters (EType type) const
void set_gizmos_on_top (bool value)
HitResult hit (const Vec2d &mouse_pos, const Camera &camera, const ClippingPlane *clipping_plane=nullptr) const
Static Public Member Functions
static int decode_id (EType type, int id)
Static Private Member Functions
static int encode_id (EType type, int id)
static int base_id (EType type)
Private Attributes
std::vector< std::shared_ptr< SceneRaycasterItem > > m_bed
std::vector< std::shared_ptr< SceneRaycasterItem > > m_volumes
std::vector< std::shared_ptr< SceneRaycasterItem > > m_gizmos
bool m_gizmos_on_top { false }
Detailed Description
Member Enumeration Documentation
EIdBase
enum class Slic3r::GUI::SceneRaycaster::EIdBase strong
Enumerator
Bed
Volume
Gizmo
    {
        Bed    = 0,
        Volume = 1000,
        Gizmo  = 1000000
    };
EType
enum class Slic3r::GUI::SceneRaycaster::EType strong
Enumerator
None
Bed
Volume
Gizmo
    {
        None,
        Bed,
        Volume,
        Gizmo
    };
Constructor & Destructor Documentation
SceneRaycaster()
Slic3r::GUI::SceneRaycaster::SceneRaycaster ()
{
#if ENABLE_RAYCAST_PICKING_DEBUG
    // hit point
    m_sphere.init_from(its_make_sphere(1.0, double(PI) / 16.0));
    m_sphere.set_color(ColorRGBA::YELLOW());
    // hit normal
    GLModel::Geometry init_data;
    init_data.format = { GLModel::Geometry::EPrimitiveType::Lines, GLModel::Geometry::EVertexLayout::P3 };
    init_data.color = ColorRGBA::YELLOW();
    init_data.reserve_vertices(2);
    init_data.reserve_indices(2);
    // vertices
    init_data.add_vertex((Vec3f)Vec3f::Zero());
    init_data.add_vertex((Vec3f)Vec3f::UnitZ());
    // indices
    init_data.add_line(0, 1);
    m_line.init_from(std::move(init_data));
#endif // ENABLE_RAYCAST_PICKING_DEBUG
}
References Slic3r::GUI::GLModel::Geometry::add_line(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::GUI::GLModel::Geometry::color, Slic3r::GUI::GLModel::Geometry::format, Slic3r::its_make_sphere(), Slic3r::GUI::GLModel::Geometry::Lines, Slic3r::GUI::GLModel::Geometry::P3, PI, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), and Slic3r::ColorRGBA::YELLOW().
Member Function Documentation
add_raycaster()
std::shared_ptr< SceneRaycasterItem > Slic3r::GUI::SceneRaycaster::add_raycaster (EType type, int picking_id, const MeshRaycaster & raycaster, const Transform3d & trafo, bool use_back_faces = false)
{
    switch (type) {
    case EType::Bed:    { return m_bed.emplace_back(std::make_shared<SceneRaycasterItem>(encode_id(type, id), raycaster, trafo, use_back_faces)); }
    case EType::Volume: { return m_volumes.emplace_back(std::make_shared<SceneRaycasterItem>(encode_id(type, id), raycaster, trafo, use_back_faces)); }
    case EType::Gizmo:  { return m_gizmos.emplace_back(std::make_shared<SceneRaycasterItem>(encode_id(type, id), raycaster, trafo, use_back_faces)); }
    default:            { assert(false);  return nullptr; }
    };
}
References Bed, encode_id(), Gizmo, m_bed, m_gizmos, m_volumes, and Volume.
Referenced by Slic3r::GUI::GLCanvas3D::add_raycaster_for_picking().
base_id()
int Slic3r::GUI::SceneRaycaster::base_id (EType type) static private
{
    switch (type)
    {
    case EType::Bed:    { return int(EIdBase::Bed); }
    case EType::Volume: { return int(EIdBase::Volume); }
    case EType::Gizmo:  { return int(EIdBase::Gizmo); }
    default:            { break; }
    };
    assert(false);
    return -1;
}
References Bed, Gizmo, and Volume.
Referenced by decode_id(), and encode_id().
decode_id()
int Slic3r::GUI::SceneRaycaster::decode_id (EType type, int id) static
{ return id - base_id(type); }
References base_id().
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::create_meshes(), and hit().
encode_id()
int Slic3r::GUI::SceneRaycaster::encode_id (EType type, int id) static private
{ return base_id(type) + id; }
References base_id().
Referenced by add_raycaster(), and remove_raycasters().
get_raycasters() [1/2]
std::vector< std::shared_ptr< SceneRaycasterItem > > * Slic3r::GUI::SceneRaycaster::get_raycasters (EType type)
{
    std::vector<std::shared_ptr<SceneRaycasterItem>>* ret = nullptr;
    switch (type)
    {
    case EType::Bed:    { ret = &m_bed; break; }
    case EType::Volume: { ret = &m_volumes; break; }
    case EType::Gizmo:  { ret = &m_gizmos; break; }
    default:            { break; }
    }
    assert(ret != nullptr);
    return ret;
}
References Bed, Gizmo, m_bed, m_gizmos, m_volumes, and Volume.
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::GLCanvas3D::get_raycasters_for_picking(), hit(), and remove_raycasters().
get_raycasters() [2/2]
const std::vector< std::shared_ptr< SceneRaycasterItem > > * Slic3r::GUI::SceneRaycaster::get_raycasters (EType type) const
{
    const std::vector<std::shared_ptr<SceneRaycasterItem>>* ret = nullptr;
    switch (type)
    {
    case EType::Bed:    { ret = &m_bed; break; }
    case EType::Volume: { ret = &m_volumes; break; }
    case EType::Gizmo:  { ret = &m_gizmos; break; }
    default:            { break; }
    }
    assert(ret != nullptr);
    return ret;
}
References Bed, Gizmo, m_bed, m_gizmos, m_volumes, and Volume.
hit()
SceneRaycaster::HitResult Slic3r::GUI::SceneRaycaster::hit (const Vec2d & mouse_pos, const Camera & camera, const ClippingPlane * clipping_plane = nullptr) const
{
    // helper class used to return currently selected volume as hit when overlapping with other volumes
    // to allow the user to click and drag on a selected volume
    class VolumeKeeper
    {
        std::optional<unsigned int> m_selected_volume_id;
        Vec3f m_closest_hit_pos{ std::numeric_limits<float>::max(), std::numeric_limits<float>::max(), std::numeric_limits<float>::max() };
        bool m_selected_volume_already_found{ false };
    public:
        VolumeKeeper() {
            const Selection& selection = wxGetApp().plater()->get_selection();
            if (selection.is_single_volume() || selection.is_single_modifier()) {
                const GLVolume* volume = selection.get_first_volume();
                if (!volume->is_wipe_tower && !volume->is_sla_pad() && !volume->is_sla_support())
                    m_selected_volume_id = *selection.get_volume_idxs().begin();
            }
        }
        bool is_active() const { return m_selected_volume_id.has_value(); }
        const Vec3f& get_closest_hit_pos() const { return m_closest_hit_pos; }
        bool check_hit_result(const HitResult& hit) {
            assert(is_active());
            if (m_selected_volume_already_found && hit.type == SceneRaycaster::EType::Volume && hit.position.isApprox(m_closest_hit_pos))
                return false;
            if (hit.type == SceneRaycaster::EType::Volume)
                m_selected_volume_already_found = *m_selected_volume_id == (unsigned int)decode_id(hit.type, hit.raycaster_id);
            m_closest_hit_pos = hit.position;
            return true;
        }
    };
    VolumeKeeper volume_keeper;
    double closest_hit_squared_distance = std::numeric_limits<double>::max();
    auto is_closest = [&closest_hit_squared_distance, &volume_keeper](const Camera& camera, const Vec3f& hit) {
        const double hit_squared_distance = (camera.get_position() - hit.cast<double>()).squaredNorm();
        bool ret = hit_squared_distance < closest_hit_squared_distance;
        if (volume_keeper.is_active())
            ret |= hit.isApprox(volume_keeper.get_closest_hit_pos());
        if (ret)
            closest_hit_squared_distance = hit_squared_distance;
        return ret;
    };
#if ENABLE_RAYCAST_PICKING_DEBUG
    const_cast<std::optional<HitResult>*>(&m_last_hit)->reset();
#endif // ENABLE_RAYCAST_PICKING_DEBUG
    HitResult ret;
    auto test_raycasters = [this, is_closest, clipping_plane, &volume_keeper](EType type, const Vec2d& mouse_pos, const Camera& camera, HitResult& ret) {
        const ClippingPlane* clip_plane = (clipping_plane != nullptr && type == EType::Volume) ? clipping_plane : nullptr;
        const std::vector<std::shared_ptr<SceneRaycasterItem>>* raycasters = get_raycasters(type);
        const Vec3f camera_forward = camera.get_dir_forward().cast<float>();
        HitResult current_hit = { type };
        for (std::shared_ptr<SceneRaycasterItem> item : *raycasters) {
            if (!item->is_active())
                continue;
            current_hit.raycaster_id = item->get_id();
            const Transform3d& trafo = item->get_transform();
            if (item->get_raycaster()->closest_hit(mouse_pos, trafo, camera, current_hit.position, current_hit.normal, clip_plane)) {
                current_hit.position = (trafo * current_hit.position.cast<double>()).cast<float>();
                current_hit.normal = (trafo.matrix().block(0, 0, 3, 3).inverse().transpose() * current_hit.normal.cast<double>()).normalized().cast<float>();
                if (item->use_back_faces() || current_hit.normal.dot(camera_forward) < 0.0f) {
                    if (is_closest(camera, current_hit.position)) {
                        if (volume_keeper.is_active()) {
                            if (volume_keeper.check_hit_result(current_hit))
                                ret = current_hit;
                        }
                        else
                            ret = current_hit;
                    }
                }
            }
        }
    };
    if (!m_gizmos.empty())
        test_raycasters(EType::Gizmo, mouse_pos, camera, ret);
    if (!m_gizmos_on_top || !ret.is_valid()) {
        if (camera.is_looking_downward() && !m_bed.empty())
            test_raycasters(EType::Bed, mouse_pos, camera, ret);
        if (!m_volumes.empty())
            test_raycasters(EType::Volume, mouse_pos, camera, ret);
    }
    if (ret.is_valid())
        ret.raycaster_id = decode_id(ret.type, ret.raycaster_id);
#if ENABLE_RAYCAST_PICKING_DEBUG
    *const_cast<std::optional<HitResult>*>(&m_last_hit) = ret;
#endif // ENABLE_RAYCAST_PICKING_DEBUG
    return ret;
}
References Bed, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast(), decode_id(), Slic3r::GUI::Camera::get_dir_forward(), Slic3r::GUI::Selection::get_first_volume(), Slic3r::GUI::Camera::get_position(), get_raycasters(), Slic3r::GUI::Selection::get_volume_idxs(), Gizmo, hit(), Slic3r::GUI::Camera::is_looking_downward(), Slic3r::GUI::Selection::is_single_modifier(), Slic3r::GUI::Selection::is_single_volume(), Slic3r::GUI::SceneRaycaster::HitResult::is_valid(), m_bed, m_gizmos, m_gizmos_on_top, m_volumes, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::SceneRaycaster::HitResult::position, Slic3r::GUI::SceneRaycaster::HitResult::raycaster_id, Slic3r::GUI::SceneRaycaster::HitResult::type, and Volume.
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and hit().
remove_raycaster()
void Slic3r::GUI::SceneRaycaster::remove_raycaster (std::shared_ptr< SceneRaycasterItem > item)
{
    for (auto it = m_bed.begin(); it != m_bed.end(); ++it) {
        if (*it == item) {
            m_bed.erase(it);
            return;
        }
    }
    for (auto it = m_volumes.begin(); it != m_volumes.end(); ++it) {
        if (*it == item) {
            m_volumes.erase(it);
            return;
        }
    }
    for (auto it = m_gizmos.begin(); it != m_gizmos.end(); ++it) {
        if (*it == item) {
            m_gizmos.erase(it);
            return;
        }
    }
}
References m_bed, m_gizmos, and m_volumes.
remove_raycasters() [1/2]
void Slic3r::GUI::SceneRaycaster::remove_raycasters (EType type)
{
    switch (type) {
    case EType::Bed:    { m_bed.clear(); break; }
    case EType::Volume: { m_volumes.clear(); break; }
    case EType::Gizmo:  { m_gizmos.clear(); break; }
    default:            { break; }
    };
}
References Bed, Gizmo, m_bed, m_gizmos, m_volumes, and Volume.
remove_raycasters() [2/2]
void Slic3r::GUI::SceneRaycaster::remove_raycasters (EType type, int id)
{
    std::vector<std::shared_ptr<SceneRaycasterItem>>* raycasters = get_raycasters(type);
    auto it = raycasters->begin();
    while (it != raycasters->end()) {
        if ((*it)->get_id() == encode_id(type, id))
            it = raycasters->erase(it);
        else
            ++it;
    }
}
References encode_id(), and get_raycasters().
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::remove_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::remove_raycasters_for_picking().
set_gizmos_on_top()
void Slic3r::GUI::SceneRaycaster::set_gizmos_on_top (bool value) inline
{ m_gizmos_on_top = value; }
References m_gizmos_on_top.
Referenced by Slic3r::GUI::GLCanvas3D::set_raycaster_gizmos_on_top().
Member Data Documentation
m_bed
std::vector<std::shared_ptr<SceneRaycasterItem> > Slic3r::GUI::SceneRaycaster::m_bed private
Referenced by add_raycaster(), get_raycasters(), get_raycasters(), hit(), remove_raycaster(), and remove_raycasters().
m_gizmos
std::vector<std::shared_ptr<SceneRaycasterItem> > Slic3r::GUI::SceneRaycaster::m_gizmos private
Referenced by add_raycaster(), get_raycasters(), get_raycasters(), hit(), remove_raycaster(), and remove_raycasters().
m_gizmos_on_top
bool Slic3r::GUI::SceneRaycaster::m_gizmos_on_top { false } private
Referenced by hit(), and set_gizmos_on_top().
m_volumes
std::vector<std::shared_ptr<SceneRaycasterItem> > Slic3r::GUI::SceneRaycaster::m_volumes private
Referenced by add_raycaster(), get_raycasters(), get_raycasters(), hit(), remove_raycaster(), and remove_raycasters().
The documentation for this class was generated from the following files:
src/slic3r/GUI/SceneRaycaster.hpp
src/slic3r/GUI/SceneRaycaster.cpp