Prusa Slicer: Slic3r::GUI::SettingsDialog Class Reference
Slic3r::GUI::SettingsDialog Class Reference
#include <src/slic3r/GUI/MainFrame.hpp>
Public Member Functions
SettingsDialog (MainFrame *mainframe)
~SettingsDialog ()=default
void set_tabpanel (wxBookCtrlBase *tabpanel)
wxMenuBar * menubar ()
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
Protected Member Functions
void on_dpi_changed (const wxRect &suggested_rect) override
virtual void on_sys_color_changed ()
Private Member Functions
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
wxBookCtrlBase * m_tabpanel { nullptr }
MainFrame * m_main_frame { nullptr }
wxMenuBar * m_menubar { nullptr }
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
SettingsDialog()
Slic3r::GUI::SettingsDialog::SettingsDialog (MainFrame * mainframe)
:DPIFrame(NULL, wxID_ANY, wxString(SLIC3R_APP_NAME) + " - " + _L("Settings"), wxDefaultPosition, wxDefaultSize, wxDEFAULT_FRAME_STYLE, "settings_dialog", mainframe->normal_font().GetPointSize()),
//: DPIDialog(mainframe, wxID_ANY, wxString(SLIC3R_APP_NAME) + " - " + _L("Settings"), wxDefaultPosition, wxDefaultSize,
//        wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER | wxMINIMIZE_BOX | wxMAXIMIZE_BOX, "settings_dialog"),
    m_main_frame(mainframe)
{
    if (wxGetApp().is_gcode_viewer())
        return;
#if defined(__WXMSW__)
    // ys_FIXME! temporary workaround for correct font scaling
    // Because of from wxWidgets 3.1.3 auto rescaling is implemented for the Fonts,
    // From the very beginning set dialog font to the wxSYS_DEFAULT_GUI_FONT
    this->SetFont(wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT));
#else
    this->SetFont(wxGetApp().normal_font());
    this->SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW));
#endif // __WXMSW__
    // Load the icon either from the exe, or from the ico file.
#if _WIN32
    {
        TCHAR szExeFileName[MAX_PATH];
        GetModuleFileName(nullptr, szExeFileName, MAX_PATH);
        SetIcon(wxIcon(szExeFileName, wxBITMAP_TYPE_ICO));
    }
#else
    SetIcon(wxIcon(var("PrusaSlicer_128px.png"), wxBITMAP_TYPE_PNG));
#endif // _WIN32
    this->Bind(wxEVT_SHOW, [this](wxShowEvent& evt) {
        auto key_up_handker = [this](wxKeyEvent& evt) {
            if ((evt.GetModifiers() & wxMOD_CONTROL) != 0) {
                switch (evt.GetKeyCode()) {
                case '1': { m_main_frame->select_tab(size_t(0)); break; }
                case '2': { m_main_frame->select_tab(1); break; }
                case '3': { m_main_frame->select_tab(2); break; }
                case '4': { m_main_frame->select_tab(3); break; }
#ifdef __APPLE__
                case 'f':
#else /* __APPLE__ */
                case WXK_CONTROL_F:
#endif /* __APPLE__ */
                case 'F': { m_main_frame->plater()->search(false); break; }
                default:break;
                }
            }
        };
        if (evt.IsShown()) {
            if (m_tabpanel != nullptr)
                m_tabpanel->Bind(wxEVT_KEY_UP, key_up_handker);
        }
        else {
            if (m_tabpanel != nullptr)
                m_tabpanel->Unbind(wxEVT_KEY_UP, key_up_handker);
        }
        });
    //just hide the Frame on closing
    this->Bind(wxEVT_CLOSE_WINDOW, [this](wxCloseEvent& evt) { this->Hide(); });
#ifdef _MSW_DARK_MODE
    if (wxGetApp().tabs_as_menu()) {
        // menubar
        m_menubar = new wxMenuBar();
        add_tabs_as_menu(m_menubar, mainframe, this);
        this->SetMenuBar(m_menubar);
    }
#endif
    // initialize layout
    auto sizer = new wxBoxSizer(wxVERTICAL);
    sizer->SetSizeHints(this);
    SetSizer(sizer);
    Fit();
    const wxSize min_size = wxSize(85 * em_unit(), 50 * em_unit());
#ifdef __APPLE__
    // Using SetMinSize() on Mac messes up the window position in some cases
    // cf. https://groups.google.com/forum/#!topic/wx-users/yUKPBBfXWO0
    SetSize(min_size);
#else
    SetMinSize(min_size);
    SetSize(GetMinSize());
#endif
    Layout();
}
References Slic3r::GUI::DPIAware< P >::em_unit(), m_main_frame, m_menubar, m_tabpanel, Slic3r::GUI::DPIAware< P >::normal_font(), Slic3r::GUI::MainFrame::plater(), Slic3r::GUI::Plater::search(), Slic3r::GUI::MainFrame::select_tab(), and Slic3r::var().
~SettingsDialog()
Slic3r::GUI::SettingsDialog::~SettingsDialog () default
Member Function Documentation
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::FileArchiveDialog::FileArchiveDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::ExtruderSequenceDialog::apply_extruder_sequence(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::DiffPresetDialog::complete_dialog_creation(), Slic3r::GUI::DiffPresetDialog::create_edit_sizer(), Slic3r::GUI::DiffPresetDialog::create_presets_sizer(), Slic3r::GUI::DiffPresetDialog::create_tree(), em_unit(), Slic3r::GUI::SavePresetDialog::Item::init_input_name_ctrl(), Slic3r::Search::SearchDialog::msw_rescale(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigSnapshotDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::FileArchiveDialog::on_dpi_changed(), Slic3r::FirmwareDialog::on_dpi_changed(), Slic3r::GUI::GalleryDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::LoadProjectsDialog::on_dpi_changed(), Slic3r::GUI::ProjectDropDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
Referenced by Slic3r::GUI::MainFrame::update_layout().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
menubar()
wxMenuBar * Slic3r::GUI::SettingsDialog::menubar () inline
{ return m_menubar; }
References m_menubar.
Referenced by Slic3r::GUI::MainFrame::select_tab().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigSnapshotDialog::ConfigSnapshotDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ExtruderSequenceDialog::ExtruderSequenceDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::LoadProjectsDialog::LoadProjectsDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::MainFrame::init_tabpanel(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::MainFrame::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
on_dpi_changed()
void Slic3r::GUI::SettingsDialog::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    if (wxGetApp().is_gcode_viewer())
        return;
    const int& em = em_unit();
    const wxSize& size = wxSize(85 * em, 50 * em);
#ifdef _MSW_DARK_MODE
    // update common mode sizer
    if (!wxGetApp().tabs_as_menu())
        dynamic_cast<Notebook*>(m_tabpanel)->Rescale();
#endif
    // update Tabs
    for (auto tab : wxGetApp().tabs_list)
        tab->msw_rescale();
    SetMinSize(size);
    Fit();
    Refresh();
}
References Slic3r::GUI::DPIAware< P >::em_unit(), and m_tabpanel.
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::GalleryDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PreferencesDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::Search::SearchDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DiffPresetDialog::on_dpi_changed().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
set_tabpanel()
void Slic3r::GUI::SettingsDialog::set_tabpanel (wxBookCtrlBase * tabpanel) inline
{ m_tabpanel = tabpanel; }
References m_tabpanel.
Referenced by Slic3r::GUI::MainFrame::init_tabpanel().
Member Data Documentation
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_main_frame
MainFrame* Slic3r::GUI::SettingsDialog::m_main_frame { nullptr } private
Referenced by SettingsDialog().
m_menubar
wxMenuBar* Slic3r::GUI::SettingsDialog::m_menubar { nullptr } private
Referenced by SettingsDialog(), and menubar().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_tabpanel
wxBookCtrlBase* Slic3r::GUI::SettingsDialog::m_tabpanel { nullptr } private
Referenced by SettingsDialog(), on_dpi_changed(), and set_tabpanel().
The documentation for this class was generated from the following files:
src/slic3r/GUI/MainFrame.hpp
src/slic3r/GUI/MainFrame.cpp