Prusa Slicer: igl::geodesic::Edge Class Reference
igl::geodesic::Edge Class Reference
Public Types
typedef SimpleVector< vertex_pointer > vertex_pointer_vector
typedef SimpleVector< edge_pointer > edge_pointer_vector
typedef SimpleVector< face_pointer > face_pointer_vector
Public Member Functions
Edge ()
~Edge ()
double & length ()
face_pointer opposite_face (face_pointer f)
vertex_pointer opposite_vertex (vertex_pointer v)
bool belongs (vertex_pointer v)
bool is_boundary ()
vertex_pointer v0 ()
vertex_pointer v1 ()
void local_coordinates (Point3D *point, double &x, double &y)
vertex_pointer_vector & adjacent_vertices ()
edge_pointer_vector & adjacent_edges ()
face_pointer_vector & adjacent_faces ()
unsigned & id ()
PointType type ()
Protected Attributes
vertex_pointer_vector m_adjacent_vertices
edge_pointer_vector m_adjacent_edges
face_pointer_vector m_adjacent_faces
unsigned m_id
PointType m_type
Private Attributes
double m_length
Detailed Description
Member Typedef Documentation
edge_pointer_vector
typedef SimpleVector<edge_pointer> igl::geodesic::MeshElementBase::edge_pointer_vector inherited
face_pointer_vector
typedef SimpleVector<face_pointer> igl::geodesic::MeshElementBase::face_pointer_vector inherited
vertex_pointer_vector
typedef SimpleVector<vertex_pointer> igl::geodesic::MeshElementBase::vertex_pointer_vector inherited
Constructor & Destructor Documentation
Edge()
igl::geodesic::Edge::Edge () inline
  {
    m_type = EDGE;
  };
References igl::geodesic::EDGE, and igl::geodesic::MeshElementBase::m_type.
~Edge()
igl::geodesic::Edge::~Edge () inline
{};
Member Function Documentation
adjacent_edges()
edge_pointer_vector & igl::geodesic::MeshElementBase::adjacent_edges () inline inherited
{return m_adjacent_edges;};
References igl::geodesic::MeshElementBase::m_adjacent_edges.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::GeodesicAlgorithmExact::list_edges_visible_from_source(), igl::geodesic::Face::next_edge(), igl::geodesic::Face::opposite_edge(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), igl::geodesic::Mesh::verify(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
adjacent_faces()
face_pointer_vector & igl::geodesic::MeshElementBase::adjacent_faces () inline inherited
{return m_adjacent_faces;};
References igl::geodesic::MeshElementBase::m_adjacent_faces.
Referenced by igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::GeodesicAlgorithmExact::construct_propagated_intervals(), is_boundary(), opposite_face(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), and igl::geodesic::GeodesicAlgorithmExact::propagate().
adjacent_vertices()
vertex_pointer_vector & igl::geodesic::MeshElementBase::adjacent_vertices () inline inherited
{return m_adjacent_vertices;};
References igl::geodesic::MeshElementBase::m_adjacent_vertices.
Referenced by igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), belongs(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Face::opposite_vertex(), opposite_vertex(), v0(), v1(), igl::geodesic::Mesh::verify(), and igl::geodesic::Face::vertex_angle().
belongs()
bool igl::geodesic::Edge::belongs (vertex_pointer v) inline
  {
    return adjacent_vertices()[0]->id() == v->id() ||
         adjacent_vertices()[1]->id() == v->id();
  }
References igl::geodesic::MeshElementBase::adjacent_vertices(), and igl::geodesic::MeshElementBase::id().
Referenced by igl::geodesic::Face::next_edge(), igl::geodesic::Face::opposite_edge(), igl::geodesic::Face::opposite_vertex(), and opposite_vertex().
id()
unsigned & igl::geodesic::MeshElementBase::id () inline inherited
{return m_id;};
References igl::geodesic::MeshElementBase::m_id.
Referenced by belongs(), igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::GeodesicAlgorithmExact::construct_propagated_intervals(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Interval::initialize(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::GeodesicAlgorithmExact::intersect_intervals(), igl::geodesic::GeodesicAlgorithmExact::interval_list(), igl::geodesic::Face::next_edge(), opposite_face(), opposite_vertex(), igl::geodesic::GeodesicAlgorithmExact::propagate(), igl::geodesic::Mesh::verify(), igl::geodesic::Face::vertex_angle(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
is_boundary()
bool igl::geodesic::Edge::is_boundary () inline
{return adjacent_faces().size() == 1;};
References igl::geodesic::MeshElementBase::adjacent_faces(), and igl::geodesic::SimpleVector< Data >::size().
Referenced by igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::propagate(), and igl::geodesic::Mesh::verify().
length()
double & igl::geodesic::Edge::length () inline
{return m_length;};
References m_length.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::GeodesicAlgorithmExact::construct_propagated_intervals(), igl::geodesic::Interval::find_closest_point(), igl::geodesic::GeodesicAlgorithmExact::initialize_propagation_data(), igl::geodesic::GeodesicAlgorithmExact::intersect_intervals(), igl::geodesic::GeodesicAlgorithmExact::propagate(), igl::geodesic::Interval::stop(), igl::geodesic::GeodesicAlgorithmExact::trace_back(), igl::geodesic::GeodesicAlgorithmExact::update_list_and_queue(), igl::geodesic::Mesh::verify(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
local_coordinates()
void igl::geodesic::Edge::local_coordinates (Point3D * point, double & x, double & y) inline
  {
    double d0 = point->distance(v0());
    if(d0 < 1e-50)
    {
      x = 0.0;
      y = 0.0;
      return;
    }
    double d1 = point->distance(v1());
    if(d1 < 1e-50)
    {
      x = m_length;
      y = 0.0;
      return;
    }
    x = m_length/2.0 + (d0*d0 - d1*d1)/(2.0*m_length);
    y = sqrt(std::max(0.0, d0*d0 - x*x));
    return;
  }
References igl::geodesic::Point3D::distance(), m_length, sqrt(), v0(), and v1().
Referenced by igl::geodesic::IntervalList::find_closest_point(), and igl::geodesic::Interval::initialize().
opposite_face()
face_pointer igl::geodesic::Edge::opposite_face (face_pointer f) inline
  {
    if(adjacent_faces().size() == 1)
    {
      assert(adjacent_faces()[0]->id() == f->id());
      return NULL;
    }
    assert(adjacent_faces()[0]->id() == f->id() ||
         adjacent_faces()[1]->id() == f->id());
    return adjacent_faces()[0]->id() == f->id() ?
         adjacent_faces()[1] : adjacent_faces()[0];
  };
References igl::geodesic::MeshElementBase::adjacent_faces(), and igl::geodesic::MeshElementBase::id().
Referenced by igl::geodesic::Mesh::verify().
opposite_vertex()
vertex_pointer igl::geodesic::Edge::opposite_vertex (vertex_pointer v) inline
  {
    assert(belongs(v));
    return adjacent_vertices()[0]->id() == v->id() ?
         adjacent_vertices()[1] : adjacent_vertices()[0];
  };
References igl::geodesic::MeshElementBase::adjacent_vertices(), belongs(), and igl::geodesic::MeshElementBase::id().
type()
PointType igl::geodesic::MeshElementBase::type () inline inherited
{return m_type;};
References igl::geodesic::MeshElementBase::m_type.
Referenced by igl::geodesic::Interval::initialize(), igl::geodesic::GeodesicAlgorithmExact::list_edges_visible_from_source(), and igl::geodesic::SurfacePoint::type().
v0()
vertex_pointer igl::geodesic::Edge::v0 () inline
{return adjacent_vertices()[0];};
References igl::geodesic::MeshElementBase::adjacent_vertices().
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::Interval::initialize(), local_coordinates(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), igl::geodesic::GeodesicAlgorithmExact::propagate(), igl::geodesic::GeodesicAlgorithmExact::trace_back(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
v1()
vertex_pointer igl::geodesic::Edge::v1 () inline
{return adjacent_vertices()[1];};
References igl::geodesic::MeshElementBase::adjacent_vertices().
Referenced by igl::geodesic::Interval::initialize(), local_coordinates(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), igl::geodesic::GeodesicAlgorithmExact::propagate(), and igl::geodesic::GeodesicAlgorithmExact::trace_back().
Member Data Documentation
m_adjacent_edges
edge_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_edges protected inherited
Referenced by igl::geodesic::MeshElementBase::adjacent_edges().
m_adjacent_faces
face_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_faces protected inherited
Referenced by igl::geodesic::MeshElementBase::adjacent_faces().
m_adjacent_vertices
vertex_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_vertices protected inherited
Referenced by igl::geodesic::MeshElementBase::adjacent_vertices().
m_id
unsigned igl::geodesic::MeshElementBase::m_id protected inherited
Referenced by igl::geodesic::MeshElementBase::id().
m_length
double igl::geodesic::Edge::m_length private
Referenced by length(), and local_coordinates().
m_type
PointType igl::geodesic::MeshElementBase::m_type protected inherited
Referenced by Edge(), igl::geodesic::Face::Face(), igl::geodesic::Vertex::Vertex(), and igl::geodesic::MeshElementBase::type().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp