Prusa Slicer: Slic3r::ThreadData Class Reference
Slic3r::ThreadData Class Reference
#include <src/libslic3r/Thread.hpp>
Public Member Functions
std::mt19937 & random_generator ()
void tbb_worker_thread_set_c_locales ()
Private Attributes
std::mt19937 m_random_generator
bool m_random_generator_initialized { false }
bool m_tbb_worker_thread_c_locales_set { false }
Detailed Description
Member Function Documentation
random_generator()
std::mt19937 & Slic3r::ThreadData::random_generator () inline
{
        if (! m_random_generator_initialized) {
            std::random_device rd;
            m_random_generator.seed(rd());
            m_random_generator_initialized = true;
        }
        return m_random_generator;
    }
References m_random_generator, and m_random_generator_initialized.
tbb_worker_thread_set_c_locales()
void Slic3r::ThreadData::tbb_worker_thread_set_c_locales ()
{
//    static std::atomic<int> cnt = 0;
//    std::cout << "TBBLocalesSetter Entering " << cnt ++ << " ID " << std::this_thread::get_id() << "\n";
    if (! m_tbb_worker_thread_c_locales_set) {
        // Set locales of the worker thread to "C".
        set_c_locales();
        // OSX specific: Elevate QOS on Apple Silicon.
        set_current_thread_qos();
        m_tbb_worker_thread_c_locales_set = true;
    }
}
References m_tbb_worker_thread_c_locales_set, Slic3r::set_c_locales(), and Slic3r::set_current_thread_qos().
Referenced by Slic3r::TBBLocalesSetter::on_scheduler_entry().
Member Data Documentation
m_random_generator
std::mt19937 Slic3r::ThreadData::m_random_generator private
Referenced by random_generator().
m_random_generator_initialized
bool Slic3r::ThreadData::m_random_generator_initialized { false } private
Referenced by random_generator().
m_tbb_worker_thread_c_locales_set
bool Slic3r::ThreadData::m_tbb_worker_thread_c_locales_set { false } private
Referenced by tbb_worker_thread_set_c_locales().
The documentation for this class was generated from the following files:
src/libslic3r/Thread.hpp
src/libslic3r/Thread.cpp