Prusa Slicer: Slic3r::GUI::RotoptimizeJob Class Reference
Slic3r::GUI::RotoptimizeJob Class Reference
#include <src/slic3r/GUI/Jobs/RotoptimizeJob.hpp>
Classes
struct FindMethod
struct ObjRot
Public Member Functions
void prepare ()
void process (Ctl &ctl) override
RotoptimizeJob ()
void finalize (bool canceled, std::exception_ptr &) override
Static Public Member Functions
static constexpr size_t get_methods_count ()
static std::string get_method_name (size_t i)
static std::string get_method_description (size_t i)
Private Types
using FindFn = std::function< Vec2d(const ModelObject &mo, const sla::RotOptimizeParams &params)>
Private Attributes
size_t m_method_id = 0
float m_accuracy = 0.75
DynamicPrintConfig m_default_print_cfg
std::vector< ObjRot > m_selected_object_ids
Plater * m_plater
Static Private Attributes
static const FindMethod Methods []
Detailed Description
Class Documentation
Slic3r::GUI::RotoptimizeJob::FindMethod
struct Slic3r::GUI::RotoptimizeJob::FindMethod
Class Members
string descr
FindFn findfn
string name
Member Typedef Documentation
FindFn
using Slic3r::GUI::RotoptimizeJob::FindFn = std::function<Vec2d(const ModelObject & mo, const sla::RotOptimizeParams &params)> private
Constructor & Destructor Documentation
RotoptimizeJob()
Slic3r::GUI::RotoptimizeJob::RotoptimizeJob ()
: m_plater{wxGetApp().plater()} { prepare(); }
References prepare().
Member Function Documentation
finalize()
void Slic3r::GUI::RotoptimizeJob::finalize (bool canceled, std::exception_ptr & eptr) override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (canceled || eptr)
        return;
    for (const ObjRot &objrot : m_selected_object_ids) {
        ModelObject *o = m_plater->model().objects[size_t(objrot.idx)];
        if (!o) continue;
        for(ModelInstance * oi : o->instances) {
            if (objrot.rot)
                oi->set_rotation({objrot.rot->x(), objrot.rot->y(), 0.});
            auto    trmatrix = oi->get_transformation().get_matrix();
            Polygon trchull  = o->convex_hull_2d(trmatrix);
            if (!trchull.empty()) {
                MinAreaBoundigBox rotbb(trchull, MinAreaBoundigBox::pcConvex);
                double            phi = rotbb.angle_to_X();
                // The box should be landscape
                if(rotbb.width() < rotbb.height()) phi += PI / 2;
                Vec3d rt = oi->get_rotation(); rt(Z) += phi;
                oi->set_rotation(rt);
            }
        }
        // Correct the z offset of the object which was corrupted be
        // the rotation
        o->ensure_on_bed();
    }
    if (!canceled)
        m_plater->update();
}
References Slic3r::MinAreaBoundigBox::angle_to_X(), Slic3r::ModelObject::convex_hull_2d(), Slic3r::MultiPoint::empty(), Slic3r::ModelObject::ensure_on_bed(), Slic3r::MinAreaBoundigBox::height(), Slic3r::ModelObject::instances, m_plater, m_selected_object_ids, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::MinAreaBoundigBox::pcConvex, PI, Slic3r::GUI::Plater::update(), Slic3r::MinAreaBoundigBox::width(), and Slic3r::Z.
get_method_description()
std::string Slic3r::GUI::RotoptimizeJob::get_method_description (size_t i) static
{
    return into_u8(_(Methods[i].descr));
}
References _, Slic3r::GUI::into_u8(), and Methods.
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow().
get_method_name()
std::string Slic3r::GUI::RotoptimizeJob::get_method_name (size_t i) static
{
    return into_u8(_(Methods[i].name));
}
References _, Slic3r::GUI::into_u8(), and Methods.
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow().
get_methods_count()
static constexpr size_t Slic3r::GUI::RotoptimizeJob::get_methods_count () inline static constexpr
{ return std::size(Methods); }
References Methods.
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow(), Slic3r::GUI::GLGizmoRotate3D::load_rotoptimize_state(), and prepare().
prepare()
void Slic3r::GUI::RotoptimizeJob::prepare ()
{
    std::string accuracy_str =
        wxGetApp().app_config->get("sla_auto_rotate", "accuracy");
    std::string method_str =
        wxGetApp().app_config->get("sla_auto_rotate", "method_id");
    if (!accuracy_str.empty())
        m_accuracy = std::stof(accuracy_str);
    if (!method_str.empty())
        m_method_id = std::stoi(method_str);
    m_accuracy = std::max(0.f, std::min(m_accuracy, 1.f));
    m_method_id = std::max(size_t(0), std::min(get_methods_count() - 1, m_method_id));
    m_default_print_cfg = wxGetApp().preset_bundle->full_config();
    const auto &sel = m_plater->get_selection().get_content();
    m_selected_object_ids.clear();
    m_selected_object_ids.reserve(sel.size());
    for (const auto &s : sel) {
        int obj_id;
        std::tie(obj_id, std::ignore) = s;
        m_selected_object_ids.emplace_back(obj_id);
    }
}
References Slic3r::GUI::Selection::get_content(), get_methods_count(), Slic3r::GUI::Plater::get_selection(), m_accuracy, m_default_print_cfg, m_method_id, m_plater, and m_selected_object_ids.
Referenced by RotoptimizeJob().
process()
void Slic3r::GUI::RotoptimizeJob::process (Ctl & ctl) override virtual
Implements Slic3r::GUI::Job.
{
    int prev_status = 0;
    auto statustxt = _u8L("Searching for optimal orientation");
    ctl.update_status(0, statustxt);
    auto params =
        sla::RotOptimizeParams{}
            .accuracy(m_accuracy)
            .print_config(&m_default_print_cfg)
            .statucb([this, &prev_status, &ctl, &statustxt](int s)
        {
            if (s > 0 && s < 100)
                ctl.update_status(prev_status + s / m_selected_object_ids.size(),
                                  statustxt);
            return !ctl.was_canceled();
        });
    for (ObjRot &objrot : m_selected_object_ids) {
        ModelObject *o = m_plater->model().objects[size_t(objrot.idx)];
        if (!o) continue;
        if (Methods[m_method_id].findfn)
            objrot.rot = Methods[m_method_id].findfn(*o, params);
        prev_status += 100 / m_selected_object_ids.size();
        if (ctl.was_canceled()) break;
    }
    ctl.update_status(100, ctl.was_canceled() ?
                               _u8L("Orientation search canceled.") :
                               _u8L("Orientation found."));
}
References _u8L, Slic3r::sla::RotOptimizeParams::accuracy(), Slic3r::GUI::RotoptimizeJob::FindMethod::findfn, m_accuracy, m_default_print_cfg, m_method_id, m_plater, m_selected_object_ids, Methods, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::sla::RotOptimizeParams::print_config(), Slic3r::sla::RotOptimizeParams::statucb(), Slic3r::GUI::Job::Ctl::update_status(), and Slic3r::GUI::Job::Ctl::was_canceled().
Member Data Documentation
m_accuracy
float Slic3r::GUI::RotoptimizeJob::m_accuracy = 0.75 private
Referenced by prepare(), and process().
m_default_print_cfg
DynamicPrintConfig Slic3r::GUI::RotoptimizeJob::m_default_print_cfg private
Referenced by prepare(), and process().
m_method_id
size_t Slic3r::GUI::RotoptimizeJob::m_method_id = 0 private
Referenced by prepare(), and process().
m_plater
Plater* Slic3r::GUI::RotoptimizeJob::m_plater private
Referenced by finalize(), prepare(), and process().
m_selected_object_ids
std::vector<ObjRot> Slic3r::GUI::RotoptimizeJob::m_selected_object_ids private
Referenced by finalize(), prepare(), and process().
Methods
const FindMethod Slic3r::GUI::RotoptimizeJob::Methods[] inline static private
Initial value:
= {{L("Best surface quality"),
            sla::find_best_misalignment_rotation,
            L("Optimize object rotation for best surface quality.")},
           {L("Reduced overhang slopes"),
            sla::find_least_supports_rotation,
            L("Optimize object rotation to have minimum amount of overhangs needing support "
              "structures.\nNote that this method will try to find the best surface of the object "
              "for touching the print bed if no elevation is set.")},
           {L("Lowest Z height"),
            sla::find_min_z_height_rotation,
            L("Rotate the model to have the lowest z height for faster print time.")}}
Referenced by get_method_description(), get_method_name(), get_methods_count(), and process().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/RotoptimizeJob.hpp
src/slic3r/GUI/Jobs/RotoptimizeJob.cpp