Prusa Slicer: Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob Class Reference
Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob Class Reference
Public Member Functions
void process (Ctl &c) override
void finalize (bool canceled, std::exception_ptr &eptr) override
PlaterJob (Plater *p, std::unique_ptr< Job > j)
~PlaterJob () override
Private Attributes
std::unique_ptr< Job > m_job
Plater * m_plater
long long m_process_duration
Detailed Description
template<class WorkerSubclass>
class Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob
Constructor & Destructor Documentation
PlaterJob()
template<class WorkerSubclass > Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::PlaterJob (Plater * p, std::unique_ptr< Job > j) inline
            : m_job{std::move(j)}, m_plater{p}
        {
            // TODO: decide if disabling slice button during UI job is what we
            // want.
            //        if (m_plater)
            //            m_plater->sidebar().enable_buttons(false);
        }
~PlaterJob()
template<class WorkerSubclass > Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::~PlaterJob () inline override
        {
            // TODO: decide if disabling slice button during UI job is what we want.
            // Reload scene ensures that the slice button gets properly
            // enabled or disabled after the job finishes, depending on the
            // state of slicing. This might be an overkill but works for now.
            //        if (m_plater)
            //            m_plater->canvas3D()->reload_scene(false);
        }
Member Function Documentation
finalize()
template<class WorkerSubclass > void Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::finalize (bool canceled, std::exception_ptr & eptr) inline override virtual
Reimplemented from Slic3r::GUI::Job.
        {
            using namespace std::chrono;
            steady_clock::time_point finalize_start = steady_clock::now();
            m_job->finalize(canceled, eptr);
            steady_clock::time_point finalize_end = steady_clock::now();
            long long finalize_duration = duration_cast<milliseconds>(finalize_end - finalize_start).count();
            BOOST_LOG_TRIVIAL(info)
                << std::fixed // do not use scientific notations
                << "Job '" << typeid(*m_job).name() << "' "
                << "spend " << m_process_duration + finalize_duration << "ms "
                << "(process " << m_process_duration << "ms + finalize " << finalize_duration << "ms)";
            if (eptr) try {
                std::rethrow_exception(eptr);
            }  catch (std::exception &e) {
                show_error(m_plater, _L("An unexpected error occured: ") + e.what());
                eptr = nullptr;
            }
        }
References _L, Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::m_job, Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::m_plater, Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::m_process_duration, and Slic3r::GUI::show_error().
process()
template<class WorkerSubclass > void Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::process (Ctl & c) inline override virtual
Implements Slic3r::GUI::Job.
        {
            // Ensure that wxWidgets processing wakes up to handle outgoing
            // messages in plater's wxIdle handler. Otherwise it might happen
            // that the message will only be processed when an event like mouse
            // move comes along which might be too late.
            struct WakeUpCtl: Ctl {
                Ctl &ctl;
                WakeUpCtl(Ctl &c) : ctl{c} {}
                void update_status(int st, const std::string &msg = "") override
                {
                    ctl.update_status(st, msg);
                    wxWakeUpIdle();
                }
                bool was_canceled() const override { return ctl.was_canceled(); }
                std::future<void> call_on_main_thread(std::function<void()> fn) override
                {
                    auto ftr = ctl.call_on_main_thread(std::move(fn));
                    wxWakeUpIdle();
                    return ftr;
                }
            } wctl{c};
            CursorSetterRAII busycursor{wctl};
            using namespace std::chrono;
            steady_clock::time_point process_start = steady_clock::now();
            m_job->process(wctl);
            steady_clock::time_point process_end = steady_clock::now();
            m_process_duration = duration_cast<milliseconds>(process_end - process_start).count();
        }
References Slic3r::GUI::Job::Ctl::call_on_main_thread(), Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::m_job, Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::m_process_duration, Slic3r::GUI::Job::Ctl::update_status(), and Slic3r::GUI::Job::Ctl::was_canceled().
Member Data Documentation
m_job
template<class WorkerSubclass > std::unique_ptr<Job> Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::m_job private
Referenced by Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::finalize(), and Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::process().
m_plater
template<class WorkerSubclass > Plater* Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::m_plater private
Referenced by Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::finalize().
m_process_duration
template<class WorkerSubclass > long long Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::m_process_duration private
Referenced by Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::finalize(), and Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::process().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Jobs/PlaterWorker.hpp