Prusa Slicer: Slic3r::AppConfig Class Reference
Slic3r::AppConfig Class Reference
#include <src/libslic3r/AppConfig.hpp>
Public Types
enum class EAppMode : unsigned char { Editor , GCodeViewer }
typedef std::map< std::string, std::map< std::string, std::set< std::string > > > VendorMap
Public Member Functions
AppConfig (EAppMode mode)
void reset ()
void set_defaults ()
std::string load ()
std::string load (const std::string &path)
void save ()
bool dirty () const
bool get (const std::string &section, const std::string &key, std::string &value) const
std::string get (const std::string &section, const std::string &key) const
bool get_bool (const std::string &section, const std::string &key) const
std::string get (const std::string &key) const
bool get_bool (const std::string &key) const
bool set (const std::string &section, const std::string &key, const std::string &value)
bool set (const std::string &key, const std::string &value)
bool has (const std::string &section, const std::string &key) const
bool has (const std::string &key) const
bool erase (const std::string &section, const std::string &key)
bool has_section (const std::string &section) const
const std::map< std::string, std::string > & get_section (const std::string &section) const
bool set_section (const std::string &section, std::map< std::string, std::string > data)
bool clear_section (const std::string &section)
bool get_variant (const std::string &vendor, const std::string &model, const std::string &variant) const
bool set_variant (const std::string &vendor, const std::string &model, const std::string &variant, bool enable)
bool set_vendors (const AppConfig &from)
bool set_vendors (const VendorMap &vendors)
bool set_vendors (VendorMap &&vendors)
const VendorMap & vendors () const
std::string get_last_dir () const
bool update_config_dir (const std::string &dir)
bool update_skein_dir (const std::string &dir)
std::string get_last_output_dir (const std::string &alt, const bool removable=false) const
bool update_last_output_dir (const std::string &dir, const bool removable=false)
void reset_selections ()
std::string config_path () const
bool legacy_datadir () const
void set_legacy_datadir (bool value)
std::string version_check_url () const
std::string index_archive_url () const
std::string profile_folder_url () const
Semver orig_version () const
bool exists () const
std::vector< std::string > get_recent_projects () const
bool set_recent_projects (const std::vector< std::string > &recent_projects)
bool set_mouse_device (const std::string &name, double translation_speed, double translation_deadzone, float rotation_speed, float rotation_deadzone, double zoom_speed, bool swap_yz)
std::vector< std::string > get_mouse_device_names () const
bool get_mouse_device_translation_speed (const std::string &name, double &speed) const
bool get_mouse_device_translation_deadzone (const std::string &name, double &deadzone) const
bool get_mouse_device_rotation_speed (const std::string &name, float &speed) const
bool get_mouse_device_rotation_deadzone (const std::string &name, float &deadzone) const
bool get_mouse_device_zoom_speed (const std::string &name, double &speed) const
bool get_mouse_device_swap_yz (const std::string &name, bool &swap) const
Static Public Attributes
static const std::string SECTION_FILAMENTS = "filaments"
static const std::string SECTION_MATERIALS = "sla_materials"
static const std::string SECTION_EMBOSS_STYLE = "font"
Private Member Functions
template<typename T >
bool get_3dmouse_device_numeric_value (const std::string &device_name, const char *parameter_name, T &out) const
Private Attributes
EAppMode m_mode { EAppMode::Editor }
std::map< std::string, std::map< std::string, std::string > > m_storage
VendorMap m_vendors
bool m_dirty
Semver m_orig_version
bool m_legacy_datadir
Detailed Description
Member Typedef Documentation
VendorMap
typedef std::map<std::string, std::map<std::string, std::set<std::string> > > Slic3r::AppConfig::VendorMap
Member Enumeration Documentation
EAppMode
enum class Slic3r::AppConfig::EAppMode : unsigned char strong
Enumerator
Editor
GCodeViewer
  {
    Editor,
    GCodeViewer
  };
Constructor & Destructor Documentation
AppConfig()
Slic3r::AppConfig::AppConfig (EAppMode mode) inline explicit
                                    :
    m_mode(mode)
  {
    this->reset();
  }
References reset().
Member Function Documentation
clear_section()
bool Slic3r::AppConfig::clear_section (const std::string & section)
{
    if (auto it_section = m_storage.find(section); it_section != m_storage.end() && ! it_section->second.empty()) {
        it_section->second.clear();
        m_dirty = true;
        return true;
    }
    return false;
}
References m_dirty, and m_storage.
Referenced by Slic3r::PresetBundle::export_selections(), Slic3r::GUI::Config::Snapshot::export_selections(), and Slic3r::GUI::EmbossStylesSerializable::store_styles().
config_path()
std::string Slic3r::AppConfig::config_path () const
{
    std::string path = (m_mode == EAppMode::Editor) ?
        (boost::filesystem::path(Slic3r::data_dir()) / (SLIC3R_APP_KEY ".ini")).make_preferred().string() :
        (boost::filesystem::path(Slic3r::data_dir()) / (GCODEVIEWER_APP_KEY ".ini")).make_preferred().string();
    return path;
}
References Slic3r::data_dir(), Editor, GCODEVIEWER_APP_KEY, and m_mode.
Referenced by Slic3r::GUI::GUI_App::check_older_app_config(), exists(), Slic3r::GUI::GUI_App::init_app_config(), load(), and save().
dirty()
bool Slic3r::AppConfig::dirty () const inline
{ return m_dirty; }
References m_dirty.
Referenced by Slic3r::GUI::GUI_App::window_pos_save().
erase()
bool Slic3r::AppConfig::erase (const std::string & section, const std::string & key)
{
    if (auto it_storage = m_storage.find(section); it_storage != m_storage.end()) {
        auto &section = it_storage->second;
        auto it = section.find(key);
        if (it != section.end()) {
            section.erase(it);
            m_dirty = true;
            return true;
        }
    }
    return false;
}
References m_dirty, and m_storage.
Referenced by set_defaults().
exists()
bool Slic3r::AppConfig::exists () const
{
    return boost::filesystem::exists(config_path());
}
References config_path().
Referenced by Slic3r::GUI::GUI_App::init_app_config().
get() [1/3]
std::string Slic3r::AppConfig::get (const std::string & key) const inline
    { std::string value; this->get("", key, value); return value; }
References get().
get() [2/3]
std::string Slic3r::AppConfig::get (const std::string & section, const std::string & key) const inline
    { std::string value; this->get(section, key, value); return value; }
References get().
get() [3/3]
bool Slic3r::AppConfig::get (const std::string & section, const std::string & key, std::string & value) const inline
  {
    value.clear();
    auto it = m_storage.find(section);
    if (it == m_storage.end())
      return false;
    auto it2 = it->second.find(key);
    if (it2 == it->second.end())
      return false;
    value = it2->second;
    return true;
  }
References m_storage.
Referenced by Slic3r::GUI::PageUpdate::PageUpdate(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::GUI_App::add_config_menu(), get(), get(), get_bool(), get_bool(), Slic3r::GUI::GUI_App::get_mode(), Slic3r::GUI::OptionsGroup::get_url(), index_archive_url(), Slic3r::DoubleSlider::Control::is_lower_thumb_editable(), Slic3r::GUI::Config::SnapshotDB::is_on_snapshot(), load(), Slic3r::GUI::GUI_App::load_language(), Slic3r::GUI::ConfigWizard::priv::load_pages(), Slic3r::PresetBundle::load_selections(), Slic3r::GUI::GUI_App::on_init_inner(), Slic3r::GUI::GUI_App::on_version_read(), Slic3r::GUI::GUI_App::open_browser_with_warning_dialog(), profile_folder_url(), Slic3r::GUI::GUI_App::recreate_GUI(), Slic3r::GUI::PageMaterials::reload_presets(), set_defaults(), Slic3r::PresetUpdater::priv::set_download_prefs(), Slic3r::GUI::GUI_App::show_downloader_registration_dialog(), Slic3r::GUI::GUI_App::start_download(), Slic3r::GUI::Config::SnapshotDB::take_snapshot(), Slic3r::GUI::GUI_App::toolbar_icon_scale(), Slic3r::GUI::GUI_App::update_ui_colours_from_appconfig(), version_check_url(), and Slic3r::GUI::GUI_App::window_pos_restore().
get_3dmouse_device_numeric_value()
template<typename T > bool Slic3r::AppConfig::get_3dmouse_device_numeric_value (const std::string & device_name, const char * parameter_name, T & out) const inline private
  {
      std::string key = std::string("mouse_device:") + device_name;
      auto it = m_storage.find(key);
      if (it == m_storage.end())
          return false;
      auto it_val = it->second.find(parameter_name);
      if (it_val == it->second.end())
          return false;
        out = T(string_to_double_decimal_point(it_val->second));
      return true;
  }
References m_storage, and Slic3r::string_to_double_decimal_point().
Referenced by get_mouse_device_rotation_deadzone(), get_mouse_device_rotation_speed(), get_mouse_device_swap_yz(), get_mouse_device_translation_deadzone(), get_mouse_device_translation_speed(), and get_mouse_device_zoom_speed().
get_bool() [1/2]
bool Slic3r::AppConfig::get_bool (const std::string & key) const inline
    { return this->get(key) == "1"; }
References get().
get_bool() [2/2]
bool Slic3r::AppConfig::get_bool (const std::string & section, const std::string & key) const inline
    { return this->get(section, key) == "1"; }
References get().
Referenced by Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageUpdate::PageUpdate(), Slic3r::GUI::GUI_App::config_wizard_startup(), Slic3r::GUI::GUI_Run(), Slic3r::GUI::DownloaderUtils::Worker::on_finish(), Slic3r::GUI::GUI_App::on_init_inner(), Slic3r::GUI::OG_CustomCtrl::OnMotion(), Slic3r::GUI::GUI_App::open_browser_with_warning_dialog(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::GUI_App::post_init(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::render(), Slic3r::PresetUpdater::priv::set_download_prefs(), Slic3r::Preset::set_visible_from_appconfig(), Slic3r::GUI::PreferencesDialog::show(), Slic3r::GUI::GUI_App::tabs_as_menu(), Slic3r::Moonraker::upload(), Slic3r::OctoPrint::upload_inner_with_host(), Slic3r::PrusaLink::upload_inner_with_host(), and Slic3r::GUI::GUI_App::window_pos_restore().
get_last_dir()
std::string Slic3r::AppConfig::get_last_dir () const
{
    const auto it = m_storage.find("recent");
    if (it != m_storage.end()) {
        {
            const auto it2 = it->second.find("skein_directory");
            if (it2 != it->second.end() && ! it2->second.empty())
                return it2->second;
        }
        {
            const auto it2 = it->second.find("config_directory");
            if (it2 != it->second.end() && ! it2->second.empty())
                return it2->second;
        }
    }
    return std::string();
}
References m_storage.
Referenced by get_last_output_dir(), Slic3r::GUI::GUI_App::import_model(), Slic3r::GUI::GUI_App::import_zip(), Slic3r::GUI::GUI_App::load_gcode(), and Slic3r::GUI::GUI_App::load_project().
get_last_output_dir()
std::string Slic3r::AppConfig::get_last_output_dir (const std::string & alt, const bool removable = false) const
{
  std::string s1 = (removable ? "last_output_path_removable" : "last_output_path");
  std::string s2 = (removable ? "remember_output_path_removable" : "remember_output_path");
  const auto it = m_storage.find("");
  if (it != m_storage.end()) {
    const auto it2 = it->second.find(s1);
    const auto it3 = it->second.find(s2);
    if (it2 != it->second.end() && it3 != it->second.end() && !it2->second.empty() && it3->second == "1")
      return it2->second;
  }
  return is_shapes_dir(alt) ? get_last_dir() : alt;
}
References get_last_dir(), Slic3r::is_shapes_dir(), and m_storage.
Referenced by Slic3r::GUI::Plater::export_gcode().
get_mouse_device_names()
std::vector< std::string > Slic3r::AppConfig::get_mouse_device_names () const
{
    static constexpr const char   *prefix     = "mouse_device:";
    static const size_t  prefix_len = strlen(prefix);
    std::vector<std::string> out;
    for (const auto& key_value_pair : m_storage)
        if (boost::starts_with(key_value_pair.first, prefix) && key_value_pair.first.size() > prefix_len)
            out.emplace_back(key_value_pair.first.substr(prefix_len));
    return out;
}
References m_storage.
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_rotation_deadzone()
bool Slic3r::AppConfig::get_mouse_device_rotation_deadzone (const std::string & name, float & deadzone) const inline
    { return get_3dmouse_device_numeric_value(name, "rotation_deadzone", deadzone); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_rotation_speed()
bool Slic3r::AppConfig::get_mouse_device_rotation_speed (const std::string & name, float & speed) const inline
    { return get_3dmouse_device_numeric_value(name, "rotation_speed", speed); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_swap_yz()
bool Slic3r::AppConfig::get_mouse_device_swap_yz (const std::string & name, bool & swap) const inline
    { return get_3dmouse_device_numeric_value(name, "swap_yz", swap); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_translation_deadzone()
bool Slic3r::AppConfig::get_mouse_device_translation_deadzone (const std::string & name, double & deadzone) const inline
    { return get_3dmouse_device_numeric_value(name, "translation_deadzone", deadzone); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_translation_speed()
bool Slic3r::AppConfig::get_mouse_device_translation_speed (const std::string & name, double & speed) const inline
    { return get_3dmouse_device_numeric_value(name, "translation_speed", speed); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_zoom_speed()
bool Slic3r::AppConfig::get_mouse_device_zoom_speed (const std::string & name, double & speed) const inline
    { return get_3dmouse_device_numeric_value(name, "zoom_speed", speed); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_recent_projects()
std::vector< std::string > Slic3r::AppConfig::get_recent_projects () const
{
    std::vector<std::string> ret;
    const auto it = m_storage.find("recent_projects");
    if (it != m_storage.end())
    {
        for (const std::map<std::string, std::string>::value_type& item : it->second)
        {
            ret.push_back(item.second);
        }
    }
    return ret;
}
References m_storage.
get_section()
const std::map< std::string, std::string > & Slic3r::AppConfig::get_section (const std::string & section) const inline
    { auto it = m_storage.find(section); assert(it != m_storage.end()); return it->second; }
References m_storage.
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::EmbossStylesSerializable::load_style_index(), Slic3r::GUI::EmbossStylesSerializable::load_styles(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), and Slic3r::Preset::set_visible_from_appconfig().
get_variant()
bool Slic3r::AppConfig::get_variant (const std::string & vendor, const std::string & model, const std::string & variant) const
{
    const auto it_v = m_vendors.find(vendor);
    if (it_v == m_vendors.end()) { return false; }
    const auto it_m = it_v->second.find(model);
    return it_m == it_v->second.end() ? false : it_m->second.find(variant) != it_m->second.end();
}
References m_vendors.
Referenced by Slic3r::GUI::PrinterPicker::PrinterPicker(), set_variant(), and Slic3r::Preset::set_visible_from_appconfig().
has() [1/2]
bool Slic3r::AppConfig::has (const std::string & key) const inline
    { return this->has("", key); }
References has().
has() [2/2]
bool Slic3r::AppConfig::has (const std::string & section, const std::string & key) const inline
  {
    auto it = m_storage.find(section);
    if (it == m_storage.end())
      return false;
    auto it2 = it->second.find(key);
    return it2 != it->second.end() && ! it2->second.empty();
  }
References m_storage.
Referenced by Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::GUI_App::dark_mode(), Slic3r::GUI::GUI_App::get_mode(), has(), Slic3r::PresetBundle::load_selections(), Slic3r::GUI::GUI_App::on_init_inner(), Slic3r::GUI::GUI_App::recreate_GUI(), Slic3r::GUI::Config::SnapshotDB::take_snapshot(), Slic3r::GUI::PageMaterials::update_lists(), Slic3r::GUI::GUI_App::update_ui_colours_from_appconfig(), and Slic3r::GUI::GUI_App::window_pos_restore().
has_section()
bool Slic3r::AppConfig::has_section (const std::string & section) const inline
    { return m_storage.find(section) != m_storage.end(); }
References m_storage.
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::PresetBundle::load_installed_sla_materials(), Slic3r::GUI::EmbossStylesSerializable::load_style_index(), Slic3r::GUI::EmbossStylesSerializable::load_styles(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), Slic3r::Preset::set_visible_from_appconfig(), and Slic3r::GUI::EmbossStylesSerializable::store_styles().
index_archive_url()
std::string Slic3r::AppConfig::index_archive_url () const
{
#if 0
    // this code is for debug & testing purposes only - changed url wont get trough inner checks anyway.
    auto from_settings = get("index_archive_url");
    return from_settings.empty() ? INDEX_ARCHIVE_URL : from_settings;
#endif
    return INDEX_ARCHIVE_URL;
}
References get(), and Slic3r::INDEX_ARCHIVE_URL.
legacy_datadir()
bool Slic3r::AppConfig::legacy_datadir () const inline
{ return m_legacy_datadir; }
References m_legacy_datadir.
Referenced by Slic3r::GUI::ConfigWizard::priv::load_vendors(), and Slic3r::PresetUpdater::priv::set_download_prefs().
load() [1/2]
std::string Slic3r::AppConfig::load ()
{
    return this->load(AppConfig::config_path());
}
References config_path(), and load().
Referenced by Slic3r::GUI::GUI_App::check_older_app_config(), Slic3r::GUI::GUI_App::init_app_config(), and load().
load() [2/2]
std::string Slic3r::AppConfig::load (const std::string & path)
{
    this->reset();
    // 1) Read the complete config file into a boost::property_tree.
    namespace pt = boost::property_tree;
    pt::ptree tree;
    boost::nowide::ifstream ifs;
    bool                    recovered = false;
    try {
        ifs.open(path);
#ifdef WIN32
        // Verify the checksum of the config file without taking just for debugging purpose.
        const ConfigFileInfo config_file_info = check_config_file_and_verify_checksum(ifs);
        if (!config_file_info.correct_checksum)
            BOOST_LOG_TRIVIAL(info)
                << "The configuration file " << path
                << " has a wrong MD5 checksum or the checksum is missing. This may indicate a file corruption or a harmless user edit.";
        if (!config_file_info.correct_checksum && config_file_info.contains_null) {
            BOOST_LOG_TRIVIAL(info) << "The configuration file " + path + " is corrupted, because it is contains null characters.";
            throw Slic3r::CriticalException("The configuration file contains null characters.");
        }
        ifs.seekg(0, boost::nowide::ifstream::beg);
#endif
        try {
            pt::read_ini(ifs, tree);
        } catch (pt::ptree_error &ex) {
            throw Slic3r::CriticalException(ex.what());
        }
    } catch (Slic3r::CriticalException &ex) {
#ifdef WIN32
        // The configuration file is corrupted, try replacing it with the backup configuration.
        ifs.close();
        std::string backup_path = (boost::format("%1%.bak") % path).str();
        if (boost::filesystem::exists(backup_path)) {
            // Compute checksum of the configuration backup file and try to load configuration from it when the checksum is correct.
            boost::nowide::ifstream backup_ifs(backup_path);
            if (const ConfigFileInfo config_file_info = check_config_file_and_verify_checksum(backup_ifs); !config_file_info.correct_checksum || config_file_info.contains_null) {
                BOOST_LOG_TRIVIAL(error) << format(R"(Both "%1%" and "%2%" are corrupted. It isn't possible to restore configuration from the backup.)", path, backup_path);
                backup_ifs.close();
                boost::filesystem::remove(backup_path);
            } else if (std::string error_message; copy_file(backup_path, path, error_message, false) != SUCCESS) {
                BOOST_LOG_TRIVIAL(error) << format(R"(Configuration file "%1%" is corrupted. Failed to restore from backup "%2%": %3%)", path, backup_path, error_message);
                backup_ifs.close();
                boost::filesystem::remove(backup_path);
            } else {
                BOOST_LOG_TRIVIAL(info) << format(R"(Configuration file "%1%" was corrupted. It has been successfully restored from the backup "%2%".)", path, backup_path);
                // Try parse configuration file after restore from backup.
                try {
                    ifs.open(path);
                    pt::read_ini(ifs, tree);
                    recovered = true;
                } catch (pt::ptree_error& ex) {
                    BOOST_LOG_TRIVIAL(info) << format(R"(Failed to parse configuration file "%1%" after it has been restored from backup: %2%)", path, ex.what());
                }
            }
        } else
#endif // WIN32
            BOOST_LOG_TRIVIAL(info) << format(R"(Failed to parse configuration file "%1%": %2%)", path, ex.what());
        if (!recovered) {
            // Report the initial error of parsing PrusaSlicer.ini.
            // Error while parsing config file. We'll customize the error message and rethrow to be displayed.
            // ! But to avoid the use of _utf8 (related to use of wxWidgets)
            // we will rethrow this exception from the place of load() call, if returned value wouldn't be empty
            return ex.what();
        }
    }
    // 2) Parse the property_tree, extract the sections and key / value pairs.
    for (const auto &section : tree) {
      if (section.second.empty()) {
        // This may be a top level (no section) entry, or an empty section.
        std::string data = section.second.data();
        if (! data.empty())
          // If there is a non-empty data, then it must be a top-level (without a section) config entry.
          m_storage[""][section.first] = data;
      } else if (boost::starts_with(section.first, VENDOR_PREFIX)) {
            // This is a vendor section listing enabled model / variants
            const auto vendor_name = section.first.substr(VENDOR_PREFIX.size());
            auto &vendor = m_vendors[vendor_name];
            for (const auto &kvp : section.second) {
                if (! boost::starts_with(kvp.first, MODEL_PREFIX)) { continue; }
                const auto model_name = kvp.first.substr(MODEL_PREFIX.size());
                std::vector<std::string> variants;
                if (! unescape_strings_cstyle(kvp.second.data(), variants)) { continue; }
                for (const auto &variant : variants) {
                    vendor[model_name].insert(variant);
                }
            }
      } else {
        // This must be a section name. Read the entries of a section.
        std::map<std::string, std::string> &storage = m_storage[section.first];
            for (auto &kvp : section.second)
              storage[kvp.first] = kvp.second.data();
        }
    }
    // Figure out if datadir has legacy presets
    auto ini_ver = Semver::parse(get("version"));
    m_legacy_datadir = false;
    if (ini_ver) {
        m_orig_version = *ini_ver;
        // Make 1.40.0 alphas compare well
        ini_ver->set_metadata(boost::none);
        ini_ver->set_prerelease(boost::none);
        m_legacy_datadir = ini_ver < Semver(1, 40, 0);
    }
    // Legacy conversion
    if (m_mode == EAppMode::Editor) {
        // Convert [extras] "physical_printer" to [presets] "physical_printer",
        // remove the [extras] section if it becomes empty.
        if (auto it_section = m_storage.find("extras"); it_section != m_storage.end()) {
            if (auto it_physical_printer = it_section->second.find("physical_printer"); it_physical_printer != it_section->second.end()) {
                m_storage["presets"]["physical_printer"] = it_physical_printer->second;
                it_section->second.erase(it_physical_printer);
            }
            if (it_section->second.empty())
                m_storage.erase(it_section);
        }
    }
    // Override missing or keys with their defaults.
    this->set_defaults();
    m_dirty = false;
    return "";
}
References Slic3r::copy_file(), Editor, error, Slic3r::format(), get(), m_dirty, m_legacy_datadir, m_mode, m_orig_version, m_storage, m_vendors, Slic3r::MODEL_PREFIX, Slic3r::Semver::parse(), reset(), set_defaults(), Slic3r::Semver::set_metadata(), Slic3r::SUCCESS, Slic3r::unescape_strings_cstyle(), and Slic3r::VENDOR_PREFIX.
orig_version()
Semver Slic3r::AppConfig::orig_version () const inline
{ return m_orig_version; }
References m_orig_version.
Referenced by Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::GUI_App::on_init_inner(), and Slic3r::GUI::GUI_App::run_wizard().
profile_folder_url()
std::string Slic3r::AppConfig::profile_folder_url () const
{
#if 0
    // this code is for debug & testing purposes only - changed url wont get trough inner checks anyway.
    auto from_settings = get("profile_folder_url");
    return from_settings.empty() ? PROFILE_FOLDER_URL : from_settings;
#endif
    return PROFILE_FOLDER_URL;
}
References get(), and Slic3r::PROFILE_FOLDER_URL.
reset()
void Slic3r::AppConfig::reset ()
{
    m_storage.clear();
    m_vendors.clear();
    m_dirty = false;
    m_orig_version = Semver::invalid();
    m_legacy_datadir = false;
    set_defaults();
};
References Slic3r::Semver::invalid(), m_dirty, m_legacy_datadir, m_orig_version, m_storage, m_vendors, and set_defaults().
Referenced by AppConfig(), and load().
reset_selections()
void Slic3r::AppConfig::reset_selections ()
{
    auto it = m_storage.find("presets");
    if (it != m_storage.end()) {
        it->second.erase("print");
        it->second.erase("filament");
        it->second.erase("sla_print");
        it->second.erase("sla_material");
        it->second.erase("printer");
        it->second.erase("physical_printer");
        m_dirty = true;
    }
}
References m_dirty, and m_storage.
save()
void Slic3r::AppConfig::save ()
{
    if (! is_main_thread_active())
        throw CriticalException("Calling AppConfig::save() from a worker thread!");
    // The config is first written to a file with a PID suffix and then moved
    // to avoid race conditions with multiple instances of Slic3r
    const auto path = config_path();
    std::string path_pid = (boost::format("%1%.%2%") % path % get_current_pid()).str();
    std::stringstream config_ss;
    if (m_mode == EAppMode::Editor)
        config_ss << "# " << Slic3r::header_slic3r_generated() << std::endl;
    else
        config_ss << "# " << Slic3r::header_gcodeviewer_generated() << std::endl;
    // Make sure the "no" category is written first.
    for (const auto& kvp : m_storage[""])
        config_ss << kvp.first << " = " << kvp.second << std::endl;
    // Write the other categories.
    for (const auto& category : m_storage) {
      if (category.first.empty())
        continue;
        config_ss << std::endl << "[" << category.first << "]" << std::endl;
        for (const auto& kvp : category.second)
            config_ss << kvp.first << " = " << kvp.second << std::endl;
  }
    // Write vendor sections
    for (const auto &vendor : m_vendors) {
        size_t size_sum = 0;
        for (const auto &model : vendor.second) { size_sum += model.second.size(); }
        if (size_sum == 0) { continue; }
        config_ss << std::endl << "[" << VENDOR_PREFIX << vendor.first << "]" << std::endl;
        for (const auto &model : vendor.second) {
            if (model.second.empty()) { continue; }
            const std::vector<std::string> variants(model.second.begin(), model.second.end());
            const auto escaped = escape_strings_cstyle(variants);
            config_ss << MODEL_PREFIX << model.first << " = " << escaped << std::endl;
        }
    }
    // One empty line before the MD5 sum.
    config_ss << std::endl;
    std::string config_str = config_ss.str();
    boost::nowide::ofstream c;
    c.open(path_pid, std::ios::out | std::ios::trunc);
    c << config_str;
#ifdef WIN32
    // WIN32 specific: The final "rename_file()" call is not safe in case of an application crash, there is no atomic "rename file" API
    // provided by Windows (sic!). Therefore we save a MD5 checksum to be able to verify file corruption. In addition,
    // we save the config file into a backup first before moving it to the final destination.
    c << appconfig_md5_hash_line(config_str);
#endif
    c.close();
#ifdef WIN32
    // Make a backup of the configuration file before copying it to the final destination.
    std::string error_message;
    std::string backup_path = (boost::format("%1%.bak") % path).str();
    // Copy configuration file with PID suffix into the configuration file with "bak" suffix.
    if (copy_file(path_pid, backup_path, error_message, false) != SUCCESS)
        BOOST_LOG_TRIVIAL(error) << "Copying from " << path_pid << " to " << backup_path << " failed. Failed to create a backup configuration.";
#endif
    // Rename the config atomically.
    // On Windows, the rename is likely NOT atomic, thus it may fail if PrusaSlicer crashes on another thread in the meanwhile.
    // To cope with that, we already made a backup of the config on Windows.
    rename_file(path_pid, path);
    m_dirty = false;
}
References config_path(), Slic3r::copy_file(), Editor, error, Slic3r::escape_strings_cstyle(), Slic3r::get_current_pid(), Slic3r::header_gcodeviewer_generated(), Slic3r::header_slic3r_generated(), Slic3r::is_main_thread_active(), m_dirty, m_mode, m_storage, m_vendors, Slic3r::MODEL_PREFIX, Slic3r::rename_file(), Slic3r::SUCCESS, and Slic3r::VENDOR_PREFIX.
Referenced by Slic3r::GUI::GUI_App::on_init_inner(), Slic3r::GUI::GUI_App::window_pos_restore(), and Slic3r::GUI::GUI_App::window_pos_save().
set() [1/2]
bool Slic3r::AppConfig::set (const std::string & key, const std::string & value) inline
    { return this->set("", key, value);  }
References set().
set() [2/2]
bool Slic3r::AppConfig::set (const std::string & section, const std::string & key, const std::string & value) inline
  {
#ifndef NDEBUG
    {
      std::string key_trimmed = key;
      boost::trim_all(key_trimmed);
      assert(key_trimmed == key);
      assert(! key_trimmed.empty());
    }
#endif // NDEBUG
    std::string &old = m_storage[section][key];
    if (old != value) {
      old = value;
      m_dirty = true;
      return true;
    }
    return false;
  }
References m_dirty, and m_storage.
Referenced by Slic3r::GUI::GUI_App::add_config_menu(), Slic3r::GUI::GUI_App::app_updater(), Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::PreferencesDialog::build(), Slic3r::GUI::GUI_App::check_older_app_config(), Slic3r::GUI::PrintHostSendDialog::EndModal(), Slic3r::PresetBundle::export_selections(), Slic3r::GUI::Config::Snapshot::export_selections(), Slic3r::GUI::Config::SnapshotDB::is_on_snapshot(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::PresetBundle::load_installed_sla_materials(), Slic3r::GUI::DownloaderUtils::Worker::on_finish(), Slic3r::GUI::GUI_App::on_init_inner(), Slic3r::GUI::GUI_App::on_version_read(), Slic3r::GUI::GUI_App::open_browser_with_warning_dialog(), Slic3r::GUI::GUI_App::post_init(), Slic3r::GUI::GUI_App::save_mode(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::GUI_App::select_language(), Slic3r::GUI::PageMode::serialize_mode(), set(), Slic3r::GUI::GUI_App::set_auto_toolbar_icon_scale(), set_defaults(), Slic3r::GUI::GUI_App::set_label_clr_modified(), Slic3r::GUI::GUI_App::set_label_clr_sys(), Slic3r::GUI::GUI_App::set_mode_palette(), Slic3r::GUI::GUI_App::show_downloader_registration_dialog(), Slic3r::GUI::Plater::priv::undo_redo_to(), update_config_dir(), update_last_output_dir(), Slic3r::GUI::PageMaterials::update_lists(), update_skein_dir(), Slic3r::GUI::GUI_App::window_pos_restore(), and Slic3r::GUI::GUI_App::window_pos_save().
set_defaults()
void Slic3r::AppConfig::set_defaults ()
{
    if (m_mode == EAppMode::Editor) {
        // Reset the empty fields to defaults.
        if (get("autocenter").empty())
            set("autocenter", "0");
        // Disable background processing by default as it is not stable.
        if (get("background_processing").empty())
            set("background_processing", "0");
        // Enable support issues alerts by default
        if (get("alert_when_supports_needed").empty())
            set("alert_when_supports_needed", "1");
        // If set, the "Controller" tab for the control of the printer over serial line and the serial port settings are hidden.
        // By default, Prusa has the controller hidden.
        if (get("no_controller").empty())
            set("no_controller", "1");
        // If set, the "- default -" selections of print/filament/printer are suppressed, if there is a valid preset available.
        if (get("no_defaults").empty())
            set("no_defaults", "1");
        if (get("no_templates").empty())
            set("no_templates", "0");
        if (get("show_incompatible_presets").empty())
            set("show_incompatible_presets", "0");
        if (get("show_drop_project_dialog").empty())
            set("show_drop_project_dialog", "1");
        if (get("drop_project_action").empty())
            set("drop_project_action", "1");
        if (get("preset_update").empty())
            set("preset_update", "1");
        if (get("export_sources_full_pathnames").empty())
            set("export_sources_full_pathnames", "0");
#ifdef _WIN32
        if (get("associate_3mf").empty())
            set("associate_3mf", "0");
        if (get("associate_stl").empty())
            set("associate_stl", "0");
        if (get("tabs_as_menu").empty())
            set("tabs_as_menu", "0");
#endif // _WIN32
        // remove old 'use_legacy_opengl' parameter from this config, if present
        if (!get("use_legacy_opengl").empty())
            erase("", "use_legacy_opengl");
#ifdef __APPLE__
        if (get("use_retina_opengl").empty())
            set("use_retina_opengl", "1");
#endif
        if (get("single_instance").empty())
            set("single_instance",
#ifdef __APPLE__
                "1"
#else // __APPLE__
                "0"
#endif // __APPLE__
                );
        if (get("remember_output_path").empty())
            set("remember_output_path", "1");
        if (get("remember_output_path_removable").empty())
            set("remember_output_path_removable", "1");
        if (get("use_custom_toolbar_size").empty())
            set("use_custom_toolbar_size", "0");
        if (get("custom_toolbar_size").empty())
            set("custom_toolbar_size", "100");
        if (get("auto_toolbar_size").empty())
            set("auto_toolbar_size", "100");
       if (get("notify_release").empty())
           set("notify_release", "all"); // or "none" or "release"
#if ENABLE_ENVIRONMENT_MAP
        if (get("use_environment_map").empty())
            set("use_environment_map", "0");
#endif // ENABLE_ENVIRONMENT_MAP
        if (get("use_inches").empty())
            set("use_inches", "0");
        if (get("default_action_on_close_application").empty())
            set("default_action_on_close_application", "none"); // , "discard" or "save"
        if (get("default_action_on_select_preset").empty())
            set("default_action_on_select_preset", "none");     // , "transfer", "discard" or "save"
        if (get("default_action_on_new_project").empty())
            set("default_action_on_new_project", "none");       // , "keep(transfer)", "discard" or "save"
        if (get("color_mapinulation_panel").empty())
            set("color_mapinulation_panel", "0");
        if (get("order_volumes").empty())
            set("order_volumes", "1");
        if (get("non_manifold_edges").empty())
            set("non_manifold_edges", "1");
        if (get("clear_undo_redo_stack_on_new_project").empty())
            set("clear_undo_redo_stack_on_new_project", "1");
    }
    else {
#ifdef _WIN32
        if (get("associate_gcode").empty())
            set("associate_gcode", "0");
#endif // _WIN32
    }
    if (get("seq_top_layer_only").empty())
        set("seq_top_layer_only", "1");
    if (get("use_perspective_camera").empty())
        set("use_perspective_camera", "1");
    if (get("use_free_camera").empty())
        set("use_free_camera", "0");
    if (get("reverse_mouse_wheel_zoom").empty())
        set("reverse_mouse_wheel_zoom", "0");
    if (get("show_splash_screen").empty())
        set("show_splash_screen", "1");
    if (get("restore_win_position").empty())
        set("restore_win_position", "1");       // allowed values - "1", "0", "crashed_at_..."
    if (get("show_hints").empty())
        set("show_hints", "1");
    if (get("allow_auto_color_change").empty())
        set("allow_auto_color_change", "1");
    if (get("allow_ip_resolve").empty())
        set("allow_ip_resolve", "1");
#ifdef _WIN32
    if (get("use_legacy_3DConnexion").empty())
        set("use_legacy_3DConnexion", "0");
    if (get("dark_color_mode").empty())
        set("dark_color_mode", "0");
    if (get("sys_menu_enabled").empty())
        set("sys_menu_enabled", "1");
#endif // _WIN32
    // Remove legacy window positions/sizes
    erase("", "main_frame_maximized");
    erase("", "main_frame_pos");
    erase("", "main_frame_size");
    erase("", "object_settings_maximized");
    erase("", "object_settings_pos");
    erase("", "object_settings_size");
}
References Editor, Slic3r::empty(), erase(), get(), m_mode, and set().
Referenced by load(), and reset().
set_legacy_datadir()
void Slic3r::AppConfig::set_legacy_datadir (bool value) inline
{ m_legacy_datadir = value; }
References m_legacy_datadir.
Referenced by Slic3r::GUI::ConfigWizard::run().
set_mouse_device()
bool Slic3r::AppConfig::set_mouse_device (const std::string & name, double translation_speed, double translation_deadzone, float rotation_speed, float rotation_deadzone, double zoom_speed, bool swap_yz)
{
    const std::string key = std::string("mouse_device:") + name;
    auto it_section = m_storage.find(key);
    if (it_section == m_storage.end())
        it_section = m_storage.insert({ key, {} }).first;
    auto &dst = it_section->second;
    std::map<std::string, std::string> src;
    src["translation_speed"]    = float_to_string_decimal_point(translation_speed);
    src["translation_deadzone"] = float_to_string_decimal_point(translation_deadzone);
    src["rotation_speed"]       = float_to_string_decimal_point(rotation_speed);
    src["rotation_deadzone"]    = float_to_string_decimal_point(rotation_deadzone);
    src["zoom_speed"]           = float_to_string_decimal_point(zoom_speed);
    src["swap_yz"]              = swap_yz ? "1" : "0";
    if (src != dst) {
        dst = std::move(src);
        m_dirty = true;
        return true;
    } else
        return false;
}
References Slic3r::float_to_string_decimal_point(), m_dirty, and m_storage.
Referenced by Slic3r::GUI::Mouse3DController::save_config().
set_recent_projects()
bool Slic3r::AppConfig::set_recent_projects (const std::vector< std::string > & recent_projects)
{
    static constexpr const char *section = "recent_projects";
    auto it_section = m_storage.find(section);
    if (it_section == m_storage.end()) {
        if (recent_projects.empty())
            return false;
        it_section = m_storage.insert({ std::string(section), {} }).first;
    }
    auto &dst = it_section->second;
    std::map<std::string, std::string> src;
    for (unsigned int i = 0; i < (unsigned int)recent_projects.size(); ++i)
        src[std::to_string(i + 1)] = recent_projects[i];
    if (src != dst) {
        dst = std::move(src);
        m_dirty = true;
        return true;
    } else
        return false;
}
References m_dirty, and m_storage.
set_section()
bool Slic3r::AppConfig::set_section (const std::string & section, std::map< std::string, std::string > data)
{
    auto it_section = m_storage.find(section);
    if (it_section == m_storage.end()) {
        if (data.empty())
            return false;
        it_section = m_storage.insert({ section, {} }).first;
    }
    auto &dst = it_section->second;
    if (dst == data)
        return false;
    dst = std::move(data);
    m_dirty = true;
    return true;
}
References m_dirty, and m_storage.
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::EmbossStylesSerializable::store_style(), and Slic3r::GUI::EmbossStylesSerializable::store_style_index().
set_variant()
bool Slic3r::AppConfig::set_variant (const std::string & vendor, const std::string & model, const std::string & variant, bool enable)
{
    if (enable) {
        if (get_variant(vendor, model, variant))
            return false;
        m_vendors[vendor][model].insert(variant);
    } else {
        auto it_v = m_vendors.find(vendor);
        if (it_v == m_vendors.end())
            return false;
        auto it_m = it_v->second.find(model);
        if (it_m == it_v->second.end())
            return false;
        auto it_var = it_m->second.find(variant);
        if (it_var == it_m->second.end())
            return false;
        it_m->second.erase(it_var);
    }
    // If we got here, there was an update
    m_dirty = true;
    return true;
}
References get_variant(), m_dirty, and m_vendors.
Referenced by Slic3r::GUI::PagePrinters::PagePrinters().
set_vendors() [1/3]
bool Slic3r::AppConfig::set_vendors (const AppConfig & from) inline
{ return this->set_vendors(from.vendors()); }
References set_vendors(), and vendors().
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::Config::Snapshot::export_vendor_configs(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), and set_vendors().
set_vendors() [2/3]
bool Slic3r::AppConfig::set_vendors (const VendorMap & vendors)
{
    if (m_vendors != vendors) {
        m_vendors = vendors;
        m_dirty = true;
        return true;
    } else
        return false;
}
References m_dirty, m_vendors, and vendors().
set_vendors() [3/3]
bool Slic3r::AppConfig::set_vendors (VendorMap && vendors)
{
    if (m_vendors != vendors) {
        m_vendors = std::move(vendors);
        m_dirty = true;
        return true;
    } else
        return false;
}
References m_dirty, m_vendors, and vendors().
update_config_dir()
bool Slic3r::AppConfig::update_config_dir (const std::string & dir)
{
    return this->set("recent", "config_directory", dir);
}
References set().
update_last_output_dir()
bool Slic3r::AppConfig::update_last_output_dir (const std::string & dir, const bool removable = false)
{
  return this->set("", (removable ? "last_output_path_removable" : "last_output_path"), dir);
}
References set().
Referenced by Slic3r::GUI::Plater::export_gcode().
update_skein_dir()
bool Slic3r::AppConfig::update_skein_dir (const std::string & dir)
{
    if (is_shapes_dir(dir))
        return false; // do not save "shapes gallery" directory
    return this->set("recent", "skein_directory", dir);
}
References Slic3r::is_shapes_dir(), and set().
vendors()
const VendorMap & Slic3r::AppConfig::vendors () const inline
{ return m_vendors; }
References m_vendors.
Referenced by Slic3r::GUI::PageVendors::PageVendors(), Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::Config::Snapshot::equal_to_active(), set_vendors(), set_vendors(), set_vendors(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
version_check_url()
std::string Slic3r::AppConfig::version_check_url () const
{
    auto from_settings = get("version_check_url");
    return from_settings.empty() ? VERSION_CHECK_URL : from_settings;
}
References get(), and Slic3r::VERSION_CHECK_URL.
Referenced by Slic3r::GUI::GUI_App::app_version_check(), and Slic3r::PresetUpdater::priv::set_download_prefs().
Member Data Documentation
m_dirty
bool Slic3r::AppConfig::m_dirty private
Referenced by clear_section(), dirty(), erase(), load(), reset(), reset_selections(), save(), set(), set_mouse_device(), set_recent_projects(), set_section(), set_variant(), set_vendors(), and set_vendors().
m_legacy_datadir
bool Slic3r::AppConfig::m_legacy_datadir private
Referenced by legacy_datadir(), load(), reset(), and set_legacy_datadir().
m_mode
EAppMode Slic3r::AppConfig::m_mode { EAppMode::Editor } private
Referenced by config_path(), load(), save(), and set_defaults().
m_orig_version
Semver Slic3r::AppConfig::m_orig_version private
Referenced by load(), orig_version(), and reset().
m_storage
std::map<std::string, std::map<std::string, std::string> > Slic3r::AppConfig::m_storage private
Referenced by clear_section(), erase(), get(), get_3dmouse_device_numeric_value(), get_last_dir(), get_last_output_dir(), get_mouse_device_names(), get_recent_projects(), get_section(), has(), has_section(), load(), reset(), reset_selections(), save(), set(), set_mouse_device(), set_recent_projects(), and set_section().
m_vendors
VendorMap Slic3r::AppConfig::m_vendors private
Referenced by get_variant(), load(), reset(), save(), set_variant(), set_vendors(), set_vendors(), and vendors().
SECTION_EMBOSS_STYLE
const std::string Slic3r::AppConfig::SECTION_EMBOSS_STYLE = "font" static
Referenced by Slic3r::GUI::EmbossStylesSerializable::create_section_name(), Slic3r::GUI::EmbossStylesSerializable::load_style_index(), and Slic3r::GUI::EmbossStylesSerializable::store_style_index().
SECTION_FILAMENTS
const std::string Slic3r::AppConfig::SECTION_FILAMENTS = "filaments" static
Referenced by Slic3r::GUI::Materials::appconfig_section(), Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), Slic3r::Preset::set_visible_from_appconfig(), and Slic3r::GUI::ConfigWizard::priv::update_presets_in_config().
SECTION_MATERIALS
const std::string Slic3r::AppConfig::SECTION_MATERIALS = "sla_materials" static
Referenced by Slic3r::GUI::Materials::appconfig_section(), Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::PresetBundle::load_installed_sla_materials(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), and Slic3r::Preset::set_visible_from_appconfig().
The documentation for this class was generated from the following files:
src/libslic3r/AppConfig.hpp
src/libslic3r/AppConfig.cpp