Prusa Slicer: marchsq::_RasterTraits< Slic3r::png::ImageGreyscale > Struct Reference
marchsq::_RasterTraits< Slic3r::png::ImageGreyscale > Struct Reference
Public Types
using Rst = Slic3r::png::ImageGreyscale
using ValueType = uint8_t
Static Public Member Functions
static uint8_t get (const Rst &rst, size_t row, size_t col)
static size_t rows (const Rst &rst)
static size_t cols (const Rst &rst)
Detailed Description
Member Typedef Documentation
Rst
using marchsq::_RasterTraits< Slic3r::png::ImageGreyscale >::Rst = Slic3r::png::ImageGreyscale
ValueType
using marchsq::_RasterTraits< Slic3r::png::ImageGreyscale >::ValueType = uint8_t
Member Function Documentation
cols()
static size_t marchsq::_RasterTraits< Slic3r::png::ImageGreyscale >::cols (const Rst & rst) inline static
{ return rst.cols; }
References Slic3r::png::Image< PxT >::cols.
get()
static uint8_t marchsq::_RasterTraits< Slic3r::png::ImageGreyscale >::get (const Rst & rst, size_t row, size_t col) inline static
    {
        return rst.get(row, col);
    }
References col(), Slic3r::png::Image< PxT >::get(), and row().
rows()
static size_t marchsq::_RasterTraits< Slic3r::png::ImageGreyscale >::rows (const Rst & rst) inline static
{ return rst.rows; }
References Slic3r::png::Image< PxT >::rows.
The documentation for this struct was generated from the following file:
src/libslic3r/Format/SL1.cpp