Prusa Slicer: Slic3r::GCodeReader::GCodeLine Class Reference
Slic3r::GCodeReader::GCodeLine Class Reference
#include <src/libslic3r/GCodeReader.hpp>
Public Member Functions
GCodeLine ()
void reset ()
const std::string & raw () const
const std::string_view cmd () const
const std::string_view comment () const
bool has (Axis axis) const
float value (Axis axis) const
bool has (char axis) const
bool has_value (char axis, float &value) const
bool has_value (char axis, int &value) const
float new_X (const GCodeReader &reader) const
float new_Y (const GCodeReader &reader) const
float new_Z (const GCodeReader &reader) const
float new_E (const GCodeReader &reader) const
float new_F (const GCodeReader &reader) const
Point new_XY_scaled (const GCodeReader &reader) const
float dist_X (const GCodeReader &reader) const
float dist_Y (const GCodeReader &reader) const
float dist_Z (const GCodeReader &reader) const
float dist_E (const GCodeReader &reader) const
float dist_XY (const GCodeReader &reader) const
bool cmd_is (const char *cmd_test) const
bool extruding (const GCodeReader &reader) const
bool retracting (const GCodeReader &reader) const
bool travel () const
void set (const GCodeReader &reader, const Axis axis, const float new_value, const int decimal_digits=3)
bool has_x () const
bool has_y () const
bool has_z () const
bool has_e () const
bool has_f () const
bool has_unknown_axis () const
float x () const
float y () const
float z () const
float e () const
float f () const
Static Public Member Functions
static bool cmd_is (const std::string &gcode_line, const char *cmd_test)
static bool cmd_starts_with (const std::string &gcode_line, const char *cmd_test)
static std::string extract_cmd (const std::string &gcode_line)
Private Attributes
std::string m_raw
float m_axis [NUM_AXES]
uint32_t m_mask
Friends
class GCodeReader
Detailed Description
Constructor & Destructor Documentation
GCodeLine()
Slic3r::GCodeReader::GCodeLine::GCodeLine () inline
{ reset(); }
References reset().
Member Function Documentation
cmd()
const std::string_view Slic3r::GCodeReader::GCodeLine::cmd () const inline
{
            const char *cmd = GCodeReader::skip_whitespaces(m_raw.c_str());
            return std::string_view(cmd, GCodeReader::skip_word(cmd) - cmd);
        }
References cmd(), m_raw, Slic3r::GCodeReader::skip_whitespaces(), and Slic3r::GCodeReader::skip_word().
Referenced by cmd(), cmd_is(), extract_cmd(), Slic3r::GCodeProcessor::process_G28(), Slic3r::GCodeProcessor::process_gcode_line(), and Slic3r::GCodeProcessor::process_T().
cmd_is() [1/2]
bool Slic3r::GCodeReader::GCodeLine::cmd_is (const char * cmd_test) const inline
{ return cmd_is(m_raw, cmd_test); }
References cmd_is(), and m_raw.
Referenced by cmd_is(), extruding(), Slic3r::GCodeProcessor::post_process(), Slic3r::SpiralVase::process_layer(), retracting(), and travel().
cmd_is() [2/2]
static bool Slic3r::GCodeReader::GCodeLine::cmd_is (const std::string & gcode_line, const char * cmd_test) inline static
{
            const char *cmd = GCodeReader::skip_whitespaces(gcode_line.c_str());
            size_t len = strlen(cmd_test);
            return strncmp(cmd, cmd_test, len) == 0 && GCodeReader::is_end_of_word(cmd[len]);
        }
References cmd(), Slic3r::GCodeReader::is_end_of_word(), and Slic3r::GCodeReader::skip_whitespaces().
cmd_starts_with()
static bool Slic3r::GCodeReader::GCodeLine::cmd_starts_with (const std::string & gcode_line, const char * cmd_test) inline static
{
            return strncmp(GCodeReader::skip_whitespaces(gcode_line.c_str()), cmd_test, strlen(cmd_test)) == 0;
        }
References Slic3r::GCodeReader::skip_whitespaces().
Referenced by Slic3r::GCodeProcessor::post_process().
comment()
const std::string_view Slic3r::GCodeReader::GCodeLine::comment () const inline
            { size_t pos = m_raw.find(';'); return (pos == std::string::npos) ? std::string_view() : std::string_view(m_raw).substr(pos + 1); }
References m_raw.
Referenced by Slic3r::GCodeProcessor::process_G1().
dist_E()
float Slic3r::GCodeReader::GCodeLine::dist_E (const GCodeReader & reader) const inline
{ return this->has(E) ? (this->e() - reader.e()) : 0; }
References Slic3r::GCodeReader::e(), e(), Slic3r::E, and has().
Referenced by extruding(), and retracting().
dist_X()
float Slic3r::GCodeReader::GCodeLine::dist_X (const GCodeReader & reader) const inline
{ return this->has(X) ? (this->x() - reader.x()) : 0; }
References has(), Slic3r::GCodeReader::x(), x(), and Slic3r::X.
dist_XY()
float Slic3r::GCodeReader::GCodeLine::dist_XY (const GCodeReader & reader) const inline
{
            float x = this->has(X) ? (this->x() - reader.x()) : 0;
            float y = this->has(Y) ? (this->y() - reader.y()) : 0;
            return sqrt(x*x + y*y);
        }
References has(), sqrt(), Slic3r::GCodeReader::x(), x(), Slic3r::X, Slic3r::GCodeReader::y(), y(), and Slic3r::Y.
dist_Y()
float Slic3r::GCodeReader::GCodeLine::dist_Y (const GCodeReader & reader) const inline
{ return this->has(Y) ? (this->y() - reader.y()) : 0; }
References has(), Slic3r::GCodeReader::y(), y(), and Slic3r::Y.
dist_Z()
float Slic3r::GCodeReader::GCodeLine::dist_Z (const GCodeReader & reader) const inline
{ return this->has(Z) ? (this->z() - reader.z()) : 0; }
References has(), Slic3r::GCodeReader::z(), z(), and Slic3r::Z.
e()
float Slic3r::GCodeReader::GCodeLine::e () const inline
{ return m_axis[E]; }
References Slic3r::E, and m_axis.
Referenced by dist_E(), new_E(), Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G92(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M205(), and Slic3r::GCodeProcessor::process_M566().
extract_cmd()
static std::string Slic3r::GCodeReader::GCodeLine::extract_cmd (const std::string & gcode_line) inline static
{
            GCodeLine temp;
            temp.m_raw = gcode_line;
            const std::string_view cmd = temp.cmd();
            return { cmd.begin(), cmd.end() };
        }
References cmd(), and m_raw.
Referenced by Slic3r::GCodeProcessor::post_process().
extruding()
bool Slic3r::GCodeReader::GCodeLine::extruding (const GCodeReader & reader) const inline
{ return this->cmd_is("G1") && this->dist_E(reader) > 0; }
References cmd_is(), and dist_E().
f()
float Slic3r::GCodeReader::GCodeLine::f () const inline
{ return m_axis[F]; }
References Slic3r::F, and m_axis.
Referenced by new_F(), Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G2_G3(), and Slic3r::GCodeProcessor::process_G61().
has() [1/2]
bool Slic3r::GCodeReader::GCodeLine::has (Axis axis) const inline
{ return (m_mask & (1 << int(axis))) != 0; }
References m_mask.
Referenced by dist_E(), dist_X(), dist_XY(), dist_Y(), dist_Z(), Slic3r::GCodeProcessor::extract_absolute_position_on_axis(), has_e(), has_f(), has_unknown_axis(), has_x(), has_y(), has_z(), new_E(), new_F(), new_X(), new_Y(), new_Z(), Slic3r::GCodeReader::parse_line_internal(), Slic3r::GCodeProcessor::process_G28(), Slic3r::GCodeProcessor::process_G2_G3(), Slic3r::SpiralVase::process_layer(), Slic3r::GCodeProcessor::process_M106(), Slic3r::GCodeProcessor::process_M132(), Slic3r::GCodeProcessor::process_M220(), Slic3r::GCodeProcessor::process_M402(), Slic3r::GCodeProcessor::process_M702(), travel(), and Slic3r::GCodeReader::update_coordinates().
has() [2/2]
bool Slic3r::GCodeReader::GCodeLine::has (char axis) const
{
    const char *c = axis_pos(m_raw.c_str(), axis);
    return c != nullptr;
}
References Slic3r::GCodeReader::axis_pos(), and m_raw.
has_e()
bool Slic3r::GCodeReader::GCodeLine::has_e () const inline
{ return this->has(E); }
References Slic3r::E, and has().
Referenced by Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G2_G3(), Slic3r::GCodeProcessor::process_G61(), Slic3r::GCodeProcessor::process_G92(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M205(), and Slic3r::GCodeProcessor::process_M566().
has_f()
bool Slic3r::GCodeReader::GCodeLine::has_f () const inline
{ return this->has(F); }
References Slic3r::F, and has().
Referenced by Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G2_G3(), and Slic3r::GCodeProcessor::process_G61().
has_unknown_axis()
bool Slic3r::GCodeReader::GCodeLine::has_unknown_axis () const inline
{ return this->has(UNKNOWN_AXIS); }
References has(), and Slic3r::UNKNOWN_AXIS.
Referenced by Slic3r::GCodeProcessor::process_G92().
has_value() [1/2]
bool Slic3r::GCodeReader::GCodeLine::has_value (char axis, float & value) const
{
    assert(is_decimal_separator_point());
    const char *c = axis_pos(m_raw.c_str(), axis);
    if (c == nullptr)
        return false;
    // Try to parse the numeric value.
    double v = 0.;
    const char* end = m_raw.c_str() + m_raw.size();
    auto [pend, ec] = fast_float::from_chars(++c, end, v);
    if (pend != c && is_end_of_word(*pend)) {
        // The axis value has been parsed correctly.
        value = float(v);
        return true;
    }
    return false;
}
References Slic3r::GCodeReader::axis_pos(), fast_float::from_chars(), Slic3r::is_decimal_separator_point(), and Slic3r::GCodeReader::is_end_of_word().
Referenced by Slic3r::GCodeProcessor::post_process(), Slic3r::GCodeProcessor::process_G10(), Slic3r::GCodeProcessor::process_G2_G3(), Slic3r::GCodeProcessor::process_M104(), Slic3r::GCodeProcessor::process_M106(), Slic3r::GCodeProcessor::process_M109(), Slic3r::GCodeProcessor::process_M204(), Slic3r::GCodeProcessor::process_M205(), Slic3r::GCodeProcessor::process_M220(), Slic3r::GCodeProcessor::process_M221(), and Slic3r::GCodeProcessor::process_M402().
has_value() [2/2]
bool Slic3r::GCodeReader::GCodeLine::has_value (char axis, int & value) const
{
    const char *c = axis_pos(m_raw.c_str(), axis);
    if (c == nullptr)
        return false;
    // Try to parse the numeric value.
    char   *pend = nullptr;
    long    v = strtol(++ c, &pend, 10);
    if (pend != nullptr && is_end_of_word(*pend)) {
        // The axis value has been parsed correctly.
        value = int(v);
        return true;
    }
    return false;
}
References Slic3r::GCodeReader::axis_pos(), and Slic3r::GCodeReader::is_end_of_word().
has_x()
bool Slic3r::GCodeReader::GCodeLine::has_x () const inline
{ return this->has(X); }
References has(), and Slic3r::X.
Referenced by Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G61(), Slic3r::GCodeProcessor::process_G92(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M205(), and Slic3r::GCodeProcessor::process_M566().
has_y()
bool Slic3r::GCodeReader::GCodeLine::has_y () const inline
{ return this->has(Y); }
References has(), and Slic3r::Y.
Referenced by Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G61(), Slic3r::GCodeProcessor::process_G92(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M205(), and Slic3r::GCodeProcessor::process_M566().
has_z()
bool Slic3r::GCodeReader::GCodeLine::has_z () const inline
{ return this->has(Z); }
References has(), and Slic3r::Z.
Referenced by Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G61(), Slic3r::GCodeProcessor::process_G92(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M205(), and Slic3r::GCodeProcessor::process_M566().
new_E()
float Slic3r::GCodeReader::GCodeLine::new_E (const GCodeReader & reader) const inline
{ return this->has(E) ? this->e() : reader.e(); }
References Slic3r::GCodeReader::e(), e(), Slic3r::E, and has().
new_F()
float Slic3r::GCodeReader::GCodeLine::new_F (const GCodeReader & reader) const inline
{ return this->has(F) ? this->f() : reader.f(); }
References Slic3r::GCodeReader::f(), f(), Slic3r::F, and has().
new_X()
float Slic3r::GCodeReader::GCodeLine::new_X (const GCodeReader & reader) const inline
{ return this->has(X) ? this->x() : reader.x(); }
References has(), Slic3r::GCodeReader::x(), x(), and Slic3r::X.
Referenced by new_XY_scaled().
new_XY_scaled()
Point Slic3r::GCodeReader::GCodeLine::new_XY_scaled (const GCodeReader & reader) const inline
            { return Point::new_scale(this->new_X(reader), this->new_Y(reader)); }
References new_X(), and new_Y().
new_Y()
float Slic3r::GCodeReader::GCodeLine::new_Y (const GCodeReader & reader) const inline
{ return this->has(Y) ? this->y() : reader.y(); }
References has(), Slic3r::GCodeReader::y(), y(), and Slic3r::Y.
Referenced by new_XY_scaled().
new_Z()
float Slic3r::GCodeReader::GCodeLine::new_Z (const GCodeReader & reader) const inline
{ return this->has(Z) ? this->z() : reader.z(); }
References has(), Slic3r::GCodeReader::z(), z(), and Slic3r::Z.
raw()
const std::string & Slic3r::GCodeReader::GCodeLine::raw () const inline
{ return m_raw; }
References m_raw.
Referenced by Slic3r::GCodeProcessor::contains_reserved_tag(), Slic3r::GCodeProcessor::contains_reserved_tags(), Slic3r::GCodeProcessor::post_process(), Slic3r::GCodeProcessor::process_gcode_line(), Slic3r::GCodeProcessor::process_M108(), and Slic3r::GCodeProcessor::process_M135().
reset()
void Slic3r::GCodeReader::GCodeLine::reset () inline
{ m_mask = 0; memset(m_axis, 0, sizeof(m_axis)); m_raw.clear(); }
References m_axis, m_mask, and m_raw.
Referenced by GCodeLine(), Slic3r::GCodeReader::parse_buffer(), and Slic3r::GCodeReader::parse_file_internal().
retracting()
bool Slic3r::GCodeReader::GCodeLine::retracting (const GCodeReader & reader) const inline
{ return this->cmd_is("G1") && this->dist_E(reader) < 0; }
References cmd_is(), and dist_E().
set()
void Slic3r::GCodeReader::GCodeLine::set (const GCodeReader & reader, const Axis axis, const float new_value, const int decimal_digits = 3)
{
    std::ostringstream ss;
    ss << std::fixed << std::setprecision(decimal_digits) << new_value;
    char match[3] = " X";
    if (int(axis) < 3)
        match[1] += int(axis);
    else if (axis == F)
        match[1] = 'F';
    else {
        assert(axis == E);
        // Extruder axis is set.
        assert(reader.extrusion_axis() != 0);
        match[1] = reader.extrusion_axis();
    }
    if (this->has(axis)) {
        size_t pos = m_raw.find(match)+2;
        size_t end = m_raw.find(' ', pos+1);
        m_raw = m_raw.replace(pos, end-pos, ss.str());
    } else {
        size_t pos = m_raw.find(' ');
        if (pos == std::string::npos)
            m_raw += std::string(match) + ss.str();
        else
            m_raw = m_raw.replace(pos, 0, std::string(match) + ss.str());
    }
    m_axis[axis] = new_value;
    m_mask |= 1 << int(axis);
}
References Slic3r::E, Slic3r::GCodeReader::extrusion_axis(), and Slic3r::F.
travel()
bool Slic3r::GCodeReader::GCodeLine::travel () const inline
{ return this->cmd_is("G1") && ! this->has(E); }
References cmd_is(), Slic3r::E, and has().
value()
float Slic3r::GCodeReader::GCodeLine::value (Axis axis) const inline
{ return m_axis[axis]; }
References m_axis.
Referenced by Slic3r::GCodeProcessor::extract_absolute_position_on_axis(), and Slic3r::GCodeReader::update_coordinates().
x()
float Slic3r::GCodeReader::GCodeLine::x () const inline
{ return m_axis[X]; }
References m_axis, and Slic3r::X.
Referenced by dist_X(), dist_XY(), new_X(), Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G92(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M205(), and Slic3r::GCodeProcessor::process_M566().
y()
float Slic3r::GCodeReader::GCodeLine::y () const inline
{ return m_axis[Y]; }
References m_axis, and Slic3r::Y.
Referenced by dist_XY(), dist_Y(), new_Y(), Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G92(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M205(), and Slic3r::GCodeProcessor::process_M566().
z()
float Slic3r::GCodeReader::GCodeLine::z () const inline
{ return m_axis[Z]; }
References m_axis, and Slic3r::Z.
Referenced by dist_Z(), new_Z(), Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_G92(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M205(), and Slic3r::GCodeProcessor::process_M566().
Friends And Related Symbol Documentation
GCodeReader
friend class GCodeReader friend
Member Data Documentation
m_axis
float Slic3r::GCodeReader::GCodeLine::m_axis[NUM_AXES] private
Referenced by e(), f(), Slic3r::GCodeReader::parse_line_internal(), reset(), value(), x(), y(), and z().
m_mask
uint32_t Slic3r::GCodeReader::GCodeLine::m_mask private
Referenced by has(), Slic3r::GCodeReader::parse_line_internal(), and reset().
m_raw
std::string Slic3r::GCodeReader::GCodeLine::m_raw private
Referenced by cmd(), cmd_is(), comment(), extract_cmd(), has(), Slic3r::GCodeReader::parse_line_internal(), raw(), and reset().
The documentation for this class was generated from the following files:
src/libslic3r/GCodeReader.hpp
src/libslic3r/GCodeReader.cpp