Prusa Slicer: Slic3r::GUI::CameraUtils Class Reference
Slic3r::GUI::CameraUtils Class Reference
Help divide camera data and camera functions This utility work with camera data by static funtions.
#include <src/slic3r/GUI/CameraUtils.hpp>
Public Member Functions
CameraUtils ()=delete
Static Public Member Functions
static Points project (const Camera &camera, const std::vector< Vec3d > &points)
Project point throw camera to 2d coordinate into imgui window.
static Point project (const Camera &camera, const Vec3d &point)
static Polygon create_hull2d (const Camera &camera, const GLVolume &volume)
Create hull around GLVolume in 2d space of camera.
static void ray_from_screen_pos (const Camera &camera, const Vec2d &position, Vec3d &point, Vec3d &direction)
Create ray(point and direction) for screen coordinate.
static void ray_from_ortho_screen_pos (const Camera &camera, const Vec2d &position, Vec3d &point, Vec3d &direction)
static void ray_from_persp_screen_pos (const Camera &camera, const Vec2d &position, Vec3d &point, Vec3d &direction)
static Vec2d get_z0_position (const Camera &camera, const Vec2d &coor)
Unproject mouse coordinate to get position in space where z coor is zero Platter surface should be in z == 0.
static Vec3d screen_point (const Camera &camera, const Vec2d &position)
Create 3d screen point from 2d position.
Detailed Description
Help divide camera data and camera functions This utility work with camera data by static funtions.
Constructor & Destructor Documentation
CameraUtils()
Slic3r::GUI::CameraUtils::CameraUtils () delete
Member Function Documentation
create_hull2d()
Slic3r::Polygon CameraUtils::create_hull2d (const Camera & camera, const GLVolume & volume) static
Create hull around GLVolume in 2d space of camera.
Parameters
camera Projection params
volume Outline by 3d object
Returns
Polygon around object
{
    std::vector<Vec3d>  vertices;
    const TriangleMesh *hull = volume.convex_hull();
    if (hull != nullptr) {
        const indexed_triangle_set &its = hull->its;
        vertices.reserve(its.vertices.size());
        // cast vector
        for (const Vec3f &vertex : its.vertices)
            vertices.emplace_back(vertex.cast<double>());
    } else {
        // Negative volume doesn't have convex hull so use bounding box
        auto bb = volume.bounding_box();
        Vec3d &min = bb.min;
        Vec3d &max = bb.max;
        vertices   = {min,
                    Vec3d(min.x(), min.y(), max.z()),
                    Vec3d(min.x(), max.y(), min.z()),
                    Vec3d(min.x(), max.y(), max.z()),
                    Vec3d(max.x(), min.y(), min.z()),
                    Vec3d(max.x(), min.y(), max.z()),
                    Vec3d(max.x(), max.y(), min.z()),
                    max};
    }
    const Transform3d &trafoMat =
        volume.get_instance_transformation().get_matrix() *
        volume.get_volume_transformation().get_matrix();
    for (Vec3d &vertex : vertices)
        vertex = trafoMat * vertex.cast<double>();
    Points vertices_2d = project(camera, vertices);
    return Geometry::convex_hull(vertices_2d);
}
References Slic3r::Geometry::convex_hull(), Slic3r::TriangleMesh::its, project(), indexed_triangle_set::vertices, and Eigen::half_impl::__half_raw::x.
Referenced by priv::calc_fine_position(), and priv::find_closest_volume().
get_z0_position()
Vec2d CameraUtils::get_z0_position (const Camera & camera, const Vec2d & coor) static
Unproject mouse coordinate to get position in space where z coor is zero Platter surface should be in z == 0.
Parameters
camera Projection params
coor Mouse position
Returns
Position on platter under mouse
{
    Vec3d p0, dir;
    ray_from_screen_pos(camera, coor, p0, dir);
    // is approx zero
    if ((fabs(dir.z()) - 1e-4) < 0)
        return Vec2d(std::numeric_limits<double>::max(),
                     std::numeric_limits<double>::max());
    // find position of ray cross plane(z = 0)
    double t = p0.z() / dir.z();
    Vec3d p = p0 - t * dir;
    return Vec2d(p.x(), p.y());
}
References ray_from_screen_pos().
Referenced by Slic3r::GUI::Emboss::CreateObjectJob::process().
project() [1/2]
Points CameraUtils::project (const Camera & camera, const std::vector< Vec3d > & points) static
Project point throw camera to 2d coordinate into imgui window.
Parameters
camera Projection params
points Point to project.
Returns
projected points by camera into coordinate of camera. x(from left to right), y(from top to bottom)
{
    Vec4i viewport(camera.get_viewport().data());
    // Convert our std::vector to Eigen dynamic matrix.
    Eigen::Matrix<double, Eigen::Dynamic, 3, Eigen::DontAlign>
        pts(points.size(), 3);
    for (size_t i = 0; i < points.size(); ++i)
        pts.block<1, 3>(i, 0) = points[i];
    // Get the projections.
    Eigen::Matrix<double, Eigen::Dynamic, 3, Eigen::DontAlign> projections;
    igl::project(pts, camera.get_view_matrix().matrix(),
                    camera.get_projection_matrix().matrix(), viewport, projections);
    Points result;
    result.reserve(points.size());
    int window_height = viewport[3];
    // convert to points --> loss precision
    for (int i = 0; i < projections.rows(); ++i) {
        double x = projections(i, 0);
        double y = projections(i, 1);
        // opposit direction o Y
        result.emplace_back(x, window_height - y);
    }
    return result;
}
References Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), igl::project(), and Eigen::PlainObjectBase< Derived >::rows().
Referenced by Slic3r::GUI::GLSelectionRectangle::contains(), create_hull2d(), Slic3r::GUI::on_mouse_surface_drag(), and project().
project() [2/2]
Point CameraUtils::project (const Camera & camera, const Vec3d & point) static
{
    // IMPROVE: do it faster when you need it (inspire in project multi point)
    return project(camera, std::vector{point}).front();
}
References project().
ray_from_ortho_screen_pos()
void CameraUtils::ray_from_ortho_screen_pos (const Camera & camera, const Vec2d & position, Vec3d & point, Vec3d & direction) static
{
    assert(camera.get_type() == Camera::EType::Ortho);
    Matrix4d modelview  = camera.get_view_matrix().matrix();
    Matrix4d projection = camera.get_projection_matrix().matrix();
    Vec4i    viewport(camera.get_viewport().data());
    igl::unproject(screen_point(camera,position), modelview, projection, viewport, point);
    direction = camera.get_dir_forward();
}
References Slic3r::GUI::Camera::get_dir_forward(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_type(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::Camera::Ortho, screen_point(), and igl::unproject().
Referenced by ray_from_screen_pos().
ray_from_persp_screen_pos()
void CameraUtils::ray_from_persp_screen_pos (const Camera & camera, const Vec2d & position, Vec3d & point, Vec3d & direction) static
{
    assert(camera.get_type() == Camera::EType::Perspective);
    Matrix4d modelview  = camera.get_view_matrix().matrix();
    Matrix4d projection = camera.get_projection_matrix().matrix();
    Vec4i    viewport(camera.get_viewport().data());
    igl::unproject(screen_point(camera, position), modelview, projection, viewport, point);
    direction = point - camera.get_position();
}
References Slic3r::GUI::Camera::get_position(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_type(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::Camera::Perspective, screen_point(), and igl::unproject().
Referenced by ray_from_screen_pos().
ray_from_screen_pos()
void CameraUtils::ray_from_screen_pos (const Camera & camera, const Vec2d & position, Vec3d & point, Vec3d & direction) static
Create ray(point and direction) for screen coordinate.
Parameters
camera Definition of camera
position Position on screen(aka mouse position)
point OUT start of ray
direction OUT direction of ray
{
    switch (camera.get_type()) {
    case Camera::EType::Ortho:       return ray_from_ortho_screen_pos(camera, position, point, direction);
    case Camera::EType::Perspective: return ray_from_persp_screen_pos(camera, position, point, direction);
    default: break;
    }
}
References Slic3r::GUI::Camera::get_type(), Slic3r::GUI::Camera::Ortho, Slic3r::GUI::Camera::Perspective, ray_from_ortho_screen_pos(), and ray_from_persp_screen_pos().
Referenced by get_z0_position(), Slic3r::GUI::MeshRaycaster::line_from_mouse_pos(), Slic3r::GUI::ray_from_camera(), and Slic3r::GUI::MeshRaycaster::unproject_on_mesh().
screen_point()
Vec3d CameraUtils::screen_point (const Camera & camera, const Vec2d & position) static
Create 3d screen point from 2d position.
Parameters
camera Define camera viewport
position Position on screen(aka mouse position)
Returns
Point represented screen coor in 3d
{
    double height = camera.get_viewport().data()[3];
    // Y coordinate has opposit direction
    return Vec3d(position.x(), height - position.y(), 0.);
}
References Slic3r::GUI::Camera::get_viewport().
Referenced by ray_from_ortho_screen_pos(), and ray_from_persp_screen_pos().
The documentation for this class was generated from the following files:
src/slic3r/GUI/CameraUtils.hpp
src/slic3r/GUI/CameraUtils.cpp