Prusa Slicer: Slic3r::Emboss::IProject3d Class Reference
Slic3r::Emboss::IProject3d Class Reference abstract
Project spatial point.
#include <src/libslic3r/Emboss.hpp>
Public Member Functions
virtual ~IProject3d ()=default
virtual Vec3d project (const Vec3d &point) const =0
Move point with respect to projection direction e.g. Orthogonal projection will move with point by direction e.g. Spherical projection need to use center of projection.
Detailed Description
Project spatial point.
Constructor & Destructor Documentation
~IProject3d()
virtual Slic3r::Emboss::IProject3d::~IProject3d () virtual default
Member Function Documentation
project()
virtual Vec3d Slic3r::Emboss::IProject3d::project (const Vec3d & point) const pure virtual
Move point with respect to projection direction e.g. Orthogonal projection will move with point by direction e.g. Spherical projection need to use center of projection.
Parameters
point Spatial point coordinate
Returns
Projected spatial point
Implemented in Slic3r::Emboss::ProjectZ, Slic3r::Emboss::ProjectScale, Slic3r::Emboss::OrthoProject3d, and Slic3r::Emboss::OrthoProject.
Referenced by Slic3r::cut2model(), priv::is_patch_inside_of_model(), and priv::set_skip_by_angle().
The documentation for this class was generated from the following file:
src/libslic3r/Emboss.hpp