Prusa Slicer: Slic3r::GUI::MsgDataIncompatible Class Reference
Slic3r::GUI::MsgDataIncompatible Class Reference
#include <src/slic3r/GUI/UpdateDialogs.hpp>
Public Member Functions
MsgDataIncompatible (const std::unordered_map< std::string, wxString > &incompats)
MsgDataIncompatible (MsgDataIncompatible &&)=delete
MsgDataIncompatible (const MsgDataIncompatible &)=delete
MsgDataIncompatible & operator= (MsgDataIncompatible &&)=delete
MsgDataIncompatible & operator= (const MsgDataIncompatible &)=delete
~MsgDataIncompatible ()
void SetButtonLabel (wxWindowID btn_id, const wxString &label, bool set_focus=false)
Protected Types
enum {
CONTENT_WIDTH = 70 , CONTENT_MAX_HEIGHT = 60 , BORDER = 30 , VERT_SPACING = 15 ,
HORIZ_SPACING = 5
}
Protected Member Functions
wxButton * add_button (wxWindowID btn_id, bool set_focus=false, const wxString &label=wxString())
wxButton * get_button (wxWindowID btn_id)
void apply_style (long style)
void finalize ()
Protected Attributes
wxFont boldfont
wxBoxSizer * content_sizer
wxBoxSizer * btn_sizer
wxStaticBitmap * logo
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum protected inherited
Enumerator
CONTENT_WIDTH
CONTENT_MAX_HEIGHT
BORDER
VERT_SPACING
HORIZ_SPACING
       {
    CONTENT_WIDTH = 70,//50,
    CONTENT_MAX_HEIGHT = 60,
    BORDER = 30,
    VERT_SPACING = 15,
    HORIZ_SPACING = 5,
  };
Constructor & Destructor Documentation
MsgDataIncompatible() [1/3]
Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible (const std::unordered_map< std::string, wxString > & incompats)
                                                                                               :
    MsgDialog(nullptr, wxString::Format(_(L("%s incompatibility")), SLIC3R_APP_NAME),
                       wxString::Format(_(L("%s configuration is incompatible")), SLIC3R_APP_NAME), wxICON_ERROR)
{
  auto *text = new wxStaticText(this, wxID_ANY, wxString::Format(_(L(
    "This version of %s is not compatible with currently installed configuration bundles.\n"
    "This probably happened as a result of running an older %s after using a newer one.\n\n"
    "You may either exit %s and try again with a newer version, or you may re-run the initial configuration. "
    "Doing so will create a backup snapshot of the existing configuration before installing files compatible with this %s.")) + "\n",
    SLIC3R_APP_NAME, SLIC3R_APP_NAME, SLIC3R_APP_NAME, SLIC3R_APP_NAME));
  text->Wrap(CONTENT_WIDTH * wxGetApp().em_unit());
  content_sizer->Add(text);
  auto *text2 = new wxStaticText(this, wxID_ANY, wxString::Format(_(L("This %s version: %s")), SLIC3R_APP_NAME, SLIC3R_VERSION));
  text2->Wrap(CONTENT_WIDTH * wxGetApp().em_unit());
  content_sizer->Add(text2);
  content_sizer->AddSpacer(VERT_SPACING);
  auto *text3 = new wxStaticText(this, wxID_ANY, _(L("Incompatible bundles:")));
  text3->Wrap(CONTENT_WIDTH * wxGetApp().em_unit());
  content_sizer->Add(text3);
  content_sizer->AddSpacer(VERT_SPACING);
  auto *versions = new wxFlexGridSizer(2, 0, VERT_SPACING);
  for (const auto &incompat : incompats) {
    auto *text_vendor = new wxStaticText(this, wxID_ANY, incompat.first);
    text_vendor->SetFont(boldfont);
    versions->Add(text_vendor);
    versions->Add(new wxStaticText(this, wxID_ANY, incompat.second));
  }
  content_sizer->Add(versions);
  content_sizer->AddSpacer(2*VERT_SPACING);
  add_button(wxID_REPLACE, true, _L("Re-configure"));
  add_button(wxID_EXIT, false, wxString::Format(_L("Exit %s"), SLIC3R_APP_NAME));
  for (auto ID : {wxID_EXIT, wxID_REPLACE})
    get_button(ID)->Bind(wxEVT_BUTTON, [this](const wxCommandEvent& evt) { this->EndModal(evt.GetId()); });
  finalize();
}
References _, _L, Slic3r::GUI::MsgDialog::add_button(), Slic3r::GUI::MsgDialog::boldfont, Slic3r::GUI::MsgDialog::content_sizer, Slic3r::GUI::MsgDialog::CONTENT_WIDTH, em_unit(), Slic3r::GUI::MsgDialog::finalize(), Slic3r::GUI::MsgDialog::get_button(), L, Slic3r::GUI::MsgDialog::VERT_SPACING, and wxEVT_BUTTON.
MsgDataIncompatible() [2/3]
Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible (MsgDataIncompatible &&) delete
MsgDataIncompatible() [3/3]
Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible (const MsgDataIncompatible &) delete
~MsgDataIncompatible()
Slic3r::GUI::MsgDataIncompatible::~MsgDataIncompatible ()
{}
Member Function Documentation
add_button()
wxButton * Slic3r::GUI::MsgDialog::add_button (wxWindowID btn_id, bool set_focus = false, const wxString & label = wxString()) protected inherited
{
    wxButton* btn = new wxButton(this, btn_id, label);
    if (set_focus) {
        btn->SetFocus();
        // For non-MSW platforms SetFocus is not enought to use it as default, when the dialog is closed by ENTER
        // We have to set this button as the (permanently) default one in its dialog
        // See https://twitter.com/ZMelmed/status/1472678454168539146
        btn->SetDefault();
    }
    btn_sizer->Add(btn, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, HORIZ_SPACING);
    btn->Bind(wxEVT_BUTTON, [this, btn_id](wxCommandEvent&) { this->EndModal(btn_id); });
    return btn;
};
References Slic3r::GUI::MsgDialog::btn_sizer, Slic3r::GUI::MsgDialog::HORIZ_SPACING, and wxEVT_BUTTON.
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), MsgDataIncompatible(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::MsgDialog::apply_style().
apply_style()
void Slic3r::GUI::MsgDialog::apply_style (long style) protected inherited
{
    if (style & wxOK)       add_button(wxID_OK, true);
    if (style & wxYES)      add_button(wxID_YES,   !(style & wxNO_DEFAULT));
    if (style & wxNO)       add_button(wxID_NO,     (style & wxNO_DEFAULT));
    if (style & wxCANCEL)   add_button(wxID_CANCEL, (style & wxCANCEL_DEFAULT));
    std::string icon_name = style & wxICON_WARNING        ? "exclamation" :
                            style & wxICON_INFORMATION    ? "info"        :
                            style & wxICON_QUESTION       ? "question"    : "PrusaSlicer";
    logo->SetBitmap(*get_bmp_bundle(icon_name, 64));
}
References Slic3r::GUI::MsgDialog::add_button(), get_bmp_bundle(), Slic3r::GUI::MsgDialog::logo, and style.
Referenced by Slic3r::GUI::MsgDialog::MsgDialog().
finalize()
void Slic3r::GUI::MsgDialog::finalize () protected inherited
{
    wxGetApp().UpdateDlgDarkUI(this);
    Fit();
    this->CenterOnParent();
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
get_button()
wxButton * Slic3r::GUI::MsgDialog::get_button (wxWindowID btn_id) protected inherited
{
    return static_cast<wxButton*>(FindWindowById(btn_id, this));
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), MsgDataIncompatible(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), and Slic3r::GUI::MsgDialog::SetButtonLabel().
operator=() [1/2]
MsgDataIncompatible & Slic3r::GUI::MsgDataIncompatible::operator= (const MsgDataIncompatible &) delete
operator=() [2/2]
MsgDataIncompatible & Slic3r::GUI::MsgDataIncompatible::operator= (MsgDataIncompatible &&) delete
SetButtonLabel()
void Slic3r::GUI::MsgDialog::SetButtonLabel (wxWindowID btn_id, const wxString & label, bool set_focus = false) inherited
{
    if (wxButton* btn = get_button(btn_id)) {
        btn->SetLabel(label);
        if (set_focus)
            btn->SetFocus();
    }
}
References Slic3r::GUI::MsgDialog::get_button().
Referenced by Slic3r::GUI::GUI_App::check_older_app_config(), Slic3r::GUI::ObjectList::del_from_cut_object(), and Slic3r::GUI::Plater::priv::delete_object_from_model().
Member Data Documentation
boldfont
wxFont Slic3r::GUI::MsgDialog::boldfont protected inherited
Referenced by MsgDataIncompatible(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), and Slic3r::GUI::MsgUpdateForced::MsgUpdateForced().
btn_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::btn_sizer protected inherited
Referenced by Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::add_button().
content_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::content_sizer protected inherited
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
logo
wxStaticBitmap* Slic3r::GUI::MsgDialog::logo protected inherited
Referenced by Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::apply_style().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UpdateDialogs.hpp
src/slic3r/GUI/UpdateDialogs.cpp