Prusa Slicer: Slic3r::Arachne::PointMatrix Class Reference
Slic3r::Arachne::PointMatrix Class Reference
Public Member Functions
PointMatrix ()
PointMatrix (double rotation)
PointMatrix (const Point p)
Point apply (const Point p) const
Point unapply (const Point p) const
Static Public Member Functions
static PointMatrix scale (double s)
Public Attributes
double matrix [4]
Detailed Description
Constructor & Destructor Documentation
PointMatrix() [1/3]
Slic3r::Arachne::PointMatrix::PointMatrix () inline
    {
        matrix[0] = 1;
        matrix[1] = 0;
        matrix[2] = 0;
        matrix[3] = 1;
    }
References matrix.
PointMatrix() [2/3]
Slic3r::Arachne::PointMatrix::PointMatrix (double rotation) inline
    {
        rotation = rotation / 180 * M_PI;
        matrix[0] = cos(rotation);
        matrix[1] = -sin(rotation);
        matrix[2] = -matrix[1];
        matrix[3] = matrix[0];
    }
References cos(), M_PI, matrix, and sin().
PointMatrix() [3/3]
Slic3r::Arachne::PointMatrix::PointMatrix (const Point p) inline
    {
        matrix[0] = p.x();
        matrix[1] = p.y();
        double f = sqrt((matrix[0] * matrix[0]) + (matrix[1] * matrix[1]));
        matrix[0] /= f;
        matrix[1] /= f;
        matrix[2] = -matrix[1];
        matrix[3] = matrix[0];
    }
References Slic3r::f(), matrix, and sqrt().
Member Function Documentation
apply()
Point Slic3r::Arachne::PointMatrix::apply (const Point p) const inline
    {
        return Point(coord_t(p.x() * matrix[0] + p.y() * matrix[1]), coord_t(p.x() * matrix[2] + p.y() * matrix[3]));
    }
References matrix.
scale()
static PointMatrix Slic3r::Arachne::PointMatrix::scale (double s) inline static
    {
        PointMatrix ret;
        ret.matrix[0] = s;
        ret.matrix[3] = s;
        return ret;
    }
References matrix.
unapply()
Point Slic3r::Arachne::PointMatrix::unapply (const Point p) const inline
    {
        return Point(coord_t(p.x() * matrix[0] + p.y() * matrix[2]), coord_t(p.x() * matrix[1] + p.y() * matrix[3]));
    }
References matrix.
Referenced by Slic3r::Arachne::VoronoiUtils::discretizeParabola().
Member Data Documentation
matrix
double Slic3r::Arachne::PointMatrix::matrix[4]
Referenced by PointMatrix(), PointMatrix(), PointMatrix(), apply(), scale(), and unapply().
The documentation for this class was generated from the following file:
src/libslic3r/Arachne/utils/VoronoiUtils.cpp