Prusa Slicer: Slic3r::GUI::DiffModel Class Reference
Slic3r::GUI::DiffModel Class Reference
#include <src/slic3r/GUI/UnsavedChangesDialog.hpp>
Public Types
enum {
colToggle , colIconText , colOldValue , colModValue ,
colNewValue , colMax
}
Public Member Functions
DiffModel (wxWindow *parent)
~DiffModel () override=default
void SetAssociatedControl (wxDataViewCtrl *ctrl)
wxDataViewItem AddPreset (Preset::Type type, wxString preset_name, PrinterTechnology pt, wxString new_preset_name=wxString())
wxDataViewItem AddOption (Preset::Type type, wxString category_name, wxString group_name, wxString option_name, wxString old_value, wxString mod_value, wxString new_value, const std::string category_icon_name)
void UpdateItemEnabling (wxDataViewItem item)
bool IsEnabledItem (const wxDataViewItem &item)
unsigned int GetColumnCount () const override
wxString GetColumnType (unsigned int col) const override
void Rescale ()
wxDataViewItem Delete (const wxDataViewItem &item)
void Clear ()
wxDataViewItem GetParent (const wxDataViewItem &item) const override
unsigned int GetChildren (const wxDataViewItem &parent, wxDataViewItemArray &array) const override
void GetValue (wxVariant &variant, const wxDataViewItem &item, unsigned int col) const override
bool SetValue (const wxVariant &variant, const wxDataViewItem &item, unsigned int col) override
bool IsEnabled (const wxDataViewItem &item, unsigned int col) const override
bool IsContainer (const wxDataViewItem &item) const override
bool HasContainerColumns (const wxDataViewItem &WXUNUSED(item)) const override
Private Member Functions
ModelNode * AddOption (ModelNode *group_node, wxString option_name, wxString old_value, wxString mod_value, wxString new_value)
ModelNode * AddOptionWithGroup (ModelNode *category_node, wxString group_name, wxString option_name, wxString old_value, wxString mod_value, wxString new_value)
ModelNode * AddOptionWithGroupAndCategory (ModelNode *preset_node, wxString category_name, wxString group_name, wxString option_name, wxString old_value, wxString mod_value, wxString new_value, const std::string category_icon_name)
Private Attributes
wxWindow * m_parent_win { nullptr }
ModelNodePtrArray m_preset_nodes
wxDataViewCtrl * m_ctrl { nullptr }
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
colToggle
colIconText
colOldValue
colModValue
colNewValue
colMax
         {
        colToggle,
        colIconText,
        colOldValue,
        colModValue,
        colNewValue,
        colMax
    };
Constructor & Destructor Documentation
DiffModel()
Slic3r::GUI::DiffModel::DiffModel (wxWindow * parent)
                                     :
    m_parent_win(parent)
{
}
~DiffModel()
Slic3r::GUI::DiffModel::~DiffModel () override default
Member Function Documentation
AddOption() [1/2]
ModelNode * Slic3r::GUI::DiffModel::AddOption (ModelNode * group_node, wxString option_name, wxString old_value, wxString mod_value, wxString new_value) private
{
    group_node->Append(std::make_unique<ModelNode>(group_node, option_name, old_value, mod_value, new_value));
    ModelNode* option = group_node->GetChildren().back().get();
    wxDataViewItem group_item = wxDataViewItem((void*)group_node);
    ItemAdded(group_item, wxDataViewItem((void*)option));
    m_ctrl->Expand(group_item);
    return option;
}
References Slic3r::GUI::ModelNode::Append(), Slic3r::GUI::ModelNode::GetChildren(), and m_ctrl.
Referenced by AddOption(), AddOptionWithGroup(), and Slic3r::GUI::DiffViewCtrl::Append().
AddOption() [2/2]
wxDataViewItem Slic3r::GUI::DiffModel::AddOption (Preset::Type type, wxString category_name, wxString group_name, wxString option_name, wxString old_value, wxString mod_value, wxString new_value, const std::string category_icon_name)
{
    // "color" strings
    color_string(category_name, def_text_color());
    color_string(group_name,    def_text_color());
    color_string(option_name,   def_text_color());
    // "make" strings bold
    make_string_bold(category_name);
    make_string_bold(group_name);
    // add items
    for (std::unique_ptr<ModelNode>& preset : m_preset_nodes)
        if (preset->type() == type)
        {
            for (std::unique_ptr<ModelNode> &category : preset->GetChildren())
                if (category->text() == category_name)
                {
                    for (std::unique_ptr<ModelNode> &group : category->GetChildren())
                        if (group->text() == group_name)
                            return wxDataViewItem((void*)AddOption(group.get(), option_name, old_value, mod_value, new_value));
                    return wxDataViewItem((void*)AddOptionWithGroup(category.get(), group_name, option_name, old_value, mod_value, new_value));
                }
            return wxDataViewItem((void*)AddOptionWithGroupAndCategory(preset.get(), category_name, group_name, option_name, old_value, mod_value, new_value, category_icon_name));
        }
    return wxDataViewItem(nullptr);
}
References AddOption(), AddOptionWithGroup(), AddOptionWithGroupAndCategory(), Slic3r::GUI::color_string(), Slic3r::GUI::def_text_color(), m_preset_nodes, and Slic3r::GUI::make_string_bold().
AddOptionWithGroup()
ModelNode * Slic3r::GUI::DiffModel::AddOptionWithGroup (ModelNode * category_node, wxString group_name, wxString option_name, wxString old_value, wxString mod_value, wxString new_value) private
{
    category_node->Append(std::make_unique<ModelNode>(category_node, group_name));
    ModelNode* group_node = category_node->GetChildren().back().get();
    ItemAdded(wxDataViewItem((void*)category_node), wxDataViewItem((void*)group_node));
    return AddOption(group_node, option_name, old_value, mod_value, new_value);
}
References AddOption(), Slic3r::GUI::ModelNode::Append(), and Slic3r::GUI::ModelNode::GetChildren().
Referenced by AddOption(), and AddOptionWithGroupAndCategory().
AddOptionWithGroupAndCategory()
ModelNode * Slic3r::GUI::DiffModel::AddOptionWithGroupAndCategory (ModelNode * preset_node, wxString category_name, wxString group_name, wxString option_name, wxString old_value, wxString mod_value, wxString new_value, const std::string category_icon_name) private
{
    preset_node->Append(std::make_unique<ModelNode>(preset_node, category_name, category_icon_name));
    ModelNode* category_node = preset_node->GetChildren().back().get();
    ItemAdded(wxDataViewItem((void*)preset_node), wxDataViewItem((void*)category_node));
    return AddOptionWithGroup(category_node, group_name, option_name, old_value, mod_value, new_value);
}
References AddOptionWithGroup(), Slic3r::GUI::ModelNode::Append(), and Slic3r::GUI::ModelNode::GetChildren().
Referenced by AddOption().
AddPreset()
wxDataViewItem Slic3r::GUI::DiffModel::AddPreset (Preset::Type type, wxString preset_name, PrinterTechnology pt, wxString new_preset_name = wxString())
{
    // "color" strings
    color_string(preset_name, def_text_color());
    make_string_bold(preset_name);
    make_string_bold(new_preset_name);
    auto preset = new ModelNode(type, m_parent_win, preset_name, get_icon_name(type, pt), new_preset_name);
    m_preset_nodes.emplace_back(preset);
    wxDataViewItem child((void*)preset);
    wxDataViewItem parent(nullptr);
    ItemAdded(parent, child);
    return child;
}
References Slic3r::GUI::color_string(), Slic3r::GUI::def_text_color(), Slic3r::GUI::get_icon_name(), m_parent_win, m_preset_nodes, and Slic3r::GUI::make_string_bold().
Referenced by Slic3r::GUI::DiffPresetDialog::update_tree(), and Slic3r::GUI::UnsavedChangesDialog::update_tree().
Clear()
void Slic3r::GUI::DiffModel::Clear ()
{
    while (!m_preset_nodes.empty())
        Delete(wxDataViewItem(m_preset_nodes.back().get()));
}
References Slic3r::GUI::Delete, and m_preset_nodes.
Referenced by Slic3r::GUI::DiffViewCtrl::Clear().
Delete()
wxDataViewItem Slic3r::GUI::DiffModel::Delete (const wxDataViewItem & item)
{
    auto ret_item = wxDataViewItem(nullptr);
    ModelNode* node = static_cast<ModelNode*>(item.GetID());
    if (!node)      // happens if item.IsOk()==false
        return ret_item;
    // first remove the node from the parent's array of children;
    // NOTE: m_preset_nodes is only a vector of _pointers_
    //       thus removing the node from it doesn't result in freeing it
    ModelNodePtrArray& children = node->GetChildren();
    // Delete all children
    while (!children.empty())
        Delete(wxDataViewItem(children.back().get()));
    auto node_parent = node->GetParent();
    wxDataViewItem parent(node_parent);
    ModelNodePtrArray& parents_children = node_parent ? node_parent->GetChildren() : m_preset_nodes;
    auto it = find_if(parents_children.begin(), parents_children.end(),
                      [node](std::unique_ptr<ModelNode>& child) { return child.get() == node; });
    assert(it != parents_children.end());
    it = parents_children.erase(it);
    if (it != parents_children.end())
        ret_item = wxDataViewItem(it->get());
    // set m_container to FALSE if parent has no child
    if (node_parent) {
#ifndef __WXGTK__
        if (node_parent->GetChildCount() == 0)
            node_parent->m_container = false;
#endif //__WXGTK__
        ret_item = parent;
    }
    // notify control
    ItemDeleted(parent, item);
    return ret_item;
}
References Slic3r::GUI::Delete, Slic3r::GUI::ModelNode::GetChildren(), Slic3r::GUI::ModelNode::GetParent(), and m_preset_nodes.
GetChildren()
unsigned int Slic3r::GUI::DiffModel::GetChildren (const wxDataViewItem & parent, wxDataViewItemArray & array) const override
{
    ModelNode* parent_node = (ModelNode*)parent.GetID();
    const ModelNodePtrArray& children = parent_node ? parent_node->GetChildren() : m_preset_nodes;
    for (const std::unique_ptr<ModelNode>& child : children)
        array.Add(wxDataViewItem((void*)child.get()));
    return array.Count();
}
References Slic3r::GUI::ModelNode::GetChildren(), and m_preset_nodes.
GetColumnCount()
unsigned int Slic3r::GUI::DiffModel::GetColumnCount () const inline override
{ return colMax; }
References colMax.
GetColumnType()
wxString Slic3r::GUI::DiffModel::GetColumnType (unsigned int col) const override
{
    switch (col)
    {
    case colToggle:
        return "bool";
    case colIconText:
    case colOldValue:
    case colNewValue:
    default:
        return "DataViewBitmapText";//"string";
    }
}
References col(), colIconText, colNewValue, colOldValue, and colToggle.
GetParent()
wxDataViewItem Slic3r::GUI::DiffModel::GetParent (const wxDataViewItem & item) const override
{
    // the invisible root node has no parent
    if (!item.IsOk())
        return wxDataViewItem(nullptr);
    ModelNode* node = static_cast<ModelNode*>(item.GetID());
    if (node->IsRoot())
        return wxDataViewItem(nullptr);
    return wxDataViewItem((void*)node->GetParent());
}
References Slic3r::GUI::ModelNode::GetParent(), and Slic3r::GUI::ModelNode::IsRoot().
GetValue()
void Slic3r::GUI::DiffModel::GetValue (wxVariant & variant, const wxDataViewItem & item, unsigned int col) const override
{
    assert(item.IsOk());
    ModelNode* node = static_cast<ModelNode*>(item.GetID());
    switch (col)
    {
    case colToggle:
        variant = node->m_toggle;
        break;
#ifdef __linux__
    case colIconText:
        variant << wxDataViewIconText(node->m_text, node->m_icon);
        break;
    case colOldValue:
        variant << wxDataViewIconText(node->m_old_value, node->m_old_color_bmp);
        break;
    case colModValue:
        variant << wxDataViewIconText(node->m_mod_value, node->m_mod_color_bmp);
        break;
    case colNewValue:
        variant << wxDataViewIconText(node->m_new_value, node->m_new_color_bmp);
        break;
#else
    case colIconText:
        variant << DataViewBitmapText(node->m_text, node->m_icon);
        break;
    case colOldValue:
        variant << DataViewBitmapText(node->m_old_value, node->m_old_color_bmp);
        break;
    case colModValue:
        variant << DataViewBitmapText(node->m_mod_value, node->m_mod_color_bmp);
        break;
    case colNewValue:
        variant << DataViewBitmapText(node->m_new_value, node->m_new_color_bmp);
        break;
#endif //__linux__
    default:
        wxLogError("DiffModel::GetValue: wrong column %d", col);
    }
}
References col(), colIconText, colModValue, colNewValue, colOldValue, colToggle, Slic3r::GUI::ModelNode::m_icon, Slic3r::GUI::ModelNode::m_mod_color_bmp, Slic3r::GUI::ModelNode::m_mod_value, Slic3r::GUI::ModelNode::m_new_color_bmp, Slic3r::GUI::ModelNode::m_new_value, Slic3r::GUI::ModelNode::m_old_color_bmp, Slic3r::GUI::ModelNode::m_old_value, Slic3r::GUI::ModelNode::m_text, and Slic3r::GUI::ModelNode::m_toggle.
HasContainerColumns()
bool Slic3r::GUI::DiffModel::HasContainerColumns (const wxDataViewItem & WXUNUSEDitem) const inline override
{ return true; }
IsContainer()
bool Slic3r::GUI::DiffModel::IsContainer (const wxDataViewItem & item) const override
{
    // the invisble root node can have children
    if (!item.IsOk())
        return true;
    ModelNode* node = static_cast<ModelNode*>(item.GetID());
    return node->IsContainer();
}
References Slic3r::GUI::ModelNode::IsContainer().
IsEnabled()
bool Slic3r::GUI::DiffModel::IsEnabled (const wxDataViewItem & item, unsigned int col) const override
{
    assert(item.IsOk());
    if (col == colToggle)
        return true;
    // disable unchecked nodes
    return (static_cast<ModelNode*>(item.GetID()))->IsToggled();
}
References col(), and colToggle.
IsEnabledItem()
bool Slic3r::GUI::DiffModel::IsEnabledItem (const wxDataViewItem & item)
{
    assert(item.IsOk());
    ModelNode* node = static_cast<ModelNode*>(item.GetID());
    return node->IsToggled();
}
References Slic3r::GUI::ModelNode::IsToggled().
Referenced by Slic3r::GUI::DiffViewCtrl::has_unselected_options(), Slic3r::GUI::DiffViewCtrl::options(), and Slic3r::GUI::DiffViewCtrl::selected_options().
Rescale()
void Slic3r::GUI::DiffModel::Rescale ()
{
    for (std::unique_ptr<ModelNode> &node : m_preset_nodes) {
        node->UpdateIcons();
        rescale_children(node.get());
    }
}
References m_preset_nodes, and Slic3r::GUI::rescale_children().
Referenced by Slic3r::GUI::DiffViewCtrl::Rescale().
SetAssociatedControl()
void Slic3r::GUI::DiffModel::SetAssociatedControl (wxDataViewCtrl * ctrl) inline
{ m_ctrl = ctrl; }
References m_ctrl.
Referenced by Slic3r::GUI::DiffViewCtrl::DiffViewCtrl().
SetValue()
bool Slic3r::GUI::DiffModel::SetValue (const wxVariant & variant, const wxDataViewItem & item, unsigned int col) override
{
    assert(item.IsOk());
    ModelNode* node = static_cast<ModelNode*>(item.GetID());
    switch (col)
    {
    case colToggle:
        node->m_toggle = variant.GetBool();
        return true;
#ifdef __linux__
    case colIconText: {
        wxDataViewIconText data;
        data << variant;
        node->m_icon = data.GetIcon();
        node->m_text = data.GetText();
        return true; }
    case colOldValue: {
        wxDataViewIconText data;
        data << variant;
        node->m_old_color_bmp   = data.GetIcon();
        node->m_old_value       = data.GetText();
        return true; }
    case colNewValue: {
        wxDataViewIconText data;
        data << variant;
        node->m_new_color_bmp   = data.GetIcon();
        node->m_new_value       = data.GetText();
        return true; }
#else
    case colIconText: {
        DataViewBitmapText data;
        data << variant;
        node->m_icon = data.GetBitmap();
        node->m_text = data.GetText();
        return true; }
    case colOldValue: {
        DataViewBitmapText data;
        data << variant;
        node->m_old_color_bmp   = data.GetBitmap();
        node->m_old_value       = data.GetText();
        return true; }
    case colNewValue: {
        DataViewBitmapText data;
        data << variant;
        node->m_new_color_bmp   = data.GetBitmap();
        node->m_new_value       = data.GetText();
        return true; }
#endif //__linux__
    default:
        wxLogError("DiffModel::SetValue: wrong column");
    }
    return false;
}
References col(), colIconText, colNewValue, colOldValue, colToggle, Slic3r::GUI::ModelNode::m_icon, Slic3r::GUI::ModelNode::m_new_color_bmp, Slic3r::GUI::ModelNode::m_new_value, Slic3r::GUI::ModelNode::m_old_color_bmp, Slic3r::GUI::ModelNode::m_old_value, Slic3r::GUI::ModelNode::m_text, and Slic3r::GUI::ModelNode::m_toggle.
UpdateItemEnabling()
void Slic3r::GUI::DiffModel::UpdateItemEnabling (wxDataViewItem item)
{
    assert(item.IsOk());
    ModelNode* node = static_cast<ModelNode*>(item.GetID());
    node->UpdateEnabling();
    update_children(node);
    update_parents(node);
}
References Slic3r::GUI::update_children(), Slic3r::GUI::update_parents(), and Slic3r::GUI::ModelNode::UpdateEnabling().
Referenced by Slic3r::GUI::DiffViewCtrl::item_value_changed().
Member Data Documentation
m_ctrl
wxDataViewCtrl* Slic3r::GUI::DiffModel::m_ctrl { nullptr } private
Referenced by AddOption(), and SetAssociatedControl().
m_parent_win
wxWindow* Slic3r::GUI::DiffModel::m_parent_win { nullptr } private
Referenced by AddPreset().
m_preset_nodes
ModelNodePtrArray Slic3r::GUI::DiffModel::m_preset_nodes private
Referenced by AddOption(), AddPreset(), Clear(), Delete(), GetChildren(), and Rescale().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UnsavedChangesDialog.hpp
src/slic3r/GUI/UnsavedChangesDialog.cpp