Prusa Slicer: Slic3r::GUI::BedShapePanel Class Reference
Slic3r::GUI::BedShapePanel Class Reference
#include <src/slic3r/GUI/BedShapeDialog.hpp>
Public Member Functions
BedShapePanel (wxWindow *parent)
void build_panel (const ConfigOptionPoints &default_pt, const ConfigOptionString &custom_texture, const ConfigOptionString &custom_model)
const std::vector< Vec2d > & get_shape () const
const std::string & get_custom_texture () const
const std::string & get_custom_model () const
Private Member Functions
ConfigOptionsGroupShp init_shape_options_page (const wxString &title)
void activate_options_page (ConfigOptionsGroupShp options_group)
wxPanel * init_texture_panel ()
wxPanel * init_model_panel ()
void set_shape (const ConfigOptionPoints &points)
void update_preview ()
void update_shape ()
void load_stl ()
void load_texture ()
void load_model ()
Private Attributes
Bed_2D * m_canvas
std::vector< Vec2d > m_shape
std::vector< Vec2d > m_loaded_shape
std::string m_custom_texture
std::string m_custom_model
wxChoicebook * m_shape_options_book
std::vector< ConfigOptionsGroupShp > m_optgroups
Static Private Attributes
static const std::string NONE = "None"
static const std::string EMPTY_STRING = ""
Friends
class BedShapeDialog
Detailed Description
Constructor & Destructor Documentation
BedShapePanel()
Slic3r::GUI::BedShapePanel::BedShapePanel (wxWindow * parent) inline
: wxPanel(parent, wxID_ANY), m_custom_texture(NONE), m_custom_model(NONE) {}
Member Function Documentation
activate_options_page()
void Slic3r::GUI::BedShapePanel::activate_options_page (ConfigOptionsGroupShp options_group) private
{
    options_group->activate();
    options_group->parent()->SetSizerAndFit(options_group->sizer);
}
Referenced by build_panel().
build_panel()
void Slic3r::GUI::BedShapePanel::build_panel (const ConfigOptionPoints & default_pt, const ConfigOptionString & custom_texture, const ConfigOptionString & custom_model)
{
    wxGetApp().UpdateDarkUI(this);
    m_shape = default_pt.values;
    m_custom_texture = custom_texture.value.empty() ? NONE : custom_texture.value;
    m_custom_model = custom_model.value.empty() ? NONE : custom_model.value;
    auto sbsizer = new wxStaticBoxSizer(wxVERTICAL, this, _L("Shape"));
    sbsizer->GetStaticBox()->SetFont(wxGetApp().bold_font());
    wxGetApp().UpdateDarkUI(sbsizer->GetStaticBox());
  // shape options
    m_shape_options_book = new wxChoicebook(this, wxID_ANY, wxDefaultPosition, wxSize(25*wxGetApp().em_unit(), -1), wxCHB_TOP);
    wxGetApp().UpdateDarkUI(m_shape_options_book->GetChoiceCtrl());
    sbsizer->Add(m_shape_options_book);
    auto optgroup = init_shape_options_page(BedShape::get_name(BedShape::PageType::Rectangle));
    BedShape::append_option_line(optgroup, BedShape::Parameter::RectSize);
    BedShape::append_option_line(optgroup, BedShape::Parameter::RectOrigin);
    activate_options_page(optgroup);
    optgroup = init_shape_options_page(BedShape::get_name(BedShape::PageType::Circle));
    BedShape::append_option_line(optgroup, BedShape::Parameter::Diameter);
    activate_options_page(optgroup);
    optgroup = init_shape_options_page(BedShape::get_name(BedShape::PageType::Custom));
  Line line{ "", "" };
  line.full_width = 1;
  line.widget = [this](wxWindow* parent) {
        wxButton* shape_btn = new wxButton(parent, wxID_ANY, _L("Load shape from STL..."));
        wxSizer* shape_sizer = new wxBoxSizer(wxHORIZONTAL);
        shape_sizer->Add(shape_btn, 1, wxEXPAND);
        wxSizer* sizer = new wxBoxSizer(wxVERTICAL);
        sizer->Add(shape_sizer, 1, wxEXPAND);
        shape_btn->Bind(wxEVT_BUTTON, [this](wxCommandEvent& e) {
      load_stl();
    });
    return sizer;
  };
  optgroup->append_line(line);
    activate_options_page(optgroup);
    wxPanel* texture_panel = init_texture_panel();
    wxPanel* model_panel = init_model_panel();
    Bind(wxEVT_CHOICEBOOK_PAGE_CHANGED, ([this](wxCommandEvent& e) { update_shape(); }));
  // right pane with preview canvas
  m_canvas = new Bed_2D(this);
    m_canvas->Bind(wxEVT_PAINT, [this](wxPaintEvent& e) { m_canvas->repaint(m_shape); });
    m_canvas->Bind(wxEVT_SIZE, [this](wxSizeEvent& e) { m_canvas->Refresh(); });
    wxSizer* left_sizer = new wxBoxSizer(wxVERTICAL);
    left_sizer->Add(sbsizer, 0, wxEXPAND);
    left_sizer->Add(texture_panel, 1, wxEXPAND);
    left_sizer->Add(model_panel, 1, wxEXPAND);
    wxSizer* top_sizer = new wxBoxSizer(wxHORIZONTAL);
    top_sizer->Add(left_sizer, 0, wxEXPAND | wxLEFT | wxTOP | wxBOTTOM, 10);
    top_sizer->Add(m_canvas, 1, wxEXPAND | wxALL, 10);
  SetSizerAndFit(top_sizer);
  set_shape(default_pt);
  update_preview();
}
References _L, activate_options_page(), Slic3r::GUI::BedShape::append_option_line(), Slic3r::GUI::BedShape::Circle, Slic3r::GUI::BedShape::Custom, Slic3r::GUI::BedShape::Diameter, em_unit(), Slic3r::GUI::Line::full_width, Slic3r::GUI::BedShape::get_name(), init_model_panel(), init_shape_options_page(), init_texture_panel(), load_stl(), m_canvas, m_custom_model, m_custom_texture, m_shape, m_shape_options_book, NONE, Slic3r::GUI::BedShape::Rectangle, Slic3r::GUI::BedShape::RectOrigin, Slic3r::GUI::BedShape::RectSize, Slic3r::GUI::Bed_2D::repaint(), set_shape(), update_preview(), update_shape(), Slic3r::ConfigOptionSingle< T >::value, Slic3r::ConfigOptionVector< T >::values, and wxEVT_BUTTON.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), and Slic3r::GUI::BedShapeDialog::build_dialog().
get_custom_model()
const std::string & Slic3r::GUI::BedShapePanel::get_custom_model () const inline
{ return (m_custom_model != NONE) ? m_custom_model : EMPTY_STRING; }
References EMPTY_STRING, m_custom_model, and NONE.
Referenced by Slic3r::GUI::PageBedShape::apply_custom_config(), and Slic3r::GUI::BedShapeDialog::get_custom_model().
get_custom_texture()
const std::string & Slic3r::GUI::BedShapePanel::get_custom_texture () const inline
{ return (m_custom_texture != NONE) ? m_custom_texture : EMPTY_STRING; }
References EMPTY_STRING, m_custom_texture, and NONE.
Referenced by Slic3r::GUI::PageBedShape::apply_custom_config(), and Slic3r::GUI::BedShapeDialog::get_custom_texture().
get_shape()
const std::vector< Vec2d > & Slic3r::GUI::BedShapePanel::get_shape () const inline
{ return m_shape; }
References m_shape.
Referenced by Slic3r::GUI::PageBedShape::apply_custom_config(), and Slic3r::GUI::BedShapeDialog::get_shape().
init_model_panel()
wxPanel * Slic3r::GUI::BedShapePanel::init_model_panel () private
{
    wxPanel* panel = new wxPanel(this);
    wxGetApp().UpdateDarkUI(panel, true);
    ConfigOptionsGroupShp optgroup = std::make_shared<ConfigOptionsGroup>(panel, _L("Model"));
    optgroup->label_width = 10;
    optgroup->m_on_change = [this](t_config_option_key opt_key, boost::any value) {
        update_shape();
    };
    Line line{ "", "" };
    line.full_width = 1;
    line.widget = [this](wxWindow* parent) {
        wxButton* load_btn = new wxButton(parent, wxID_ANY, _L("Load..."));
        wxSizer* load_sizer = new wxBoxSizer(wxHORIZONTAL);
        load_sizer->Add(load_btn, 1, wxEXPAND);
        wxStaticText* filename_lbl = new wxStaticText(parent, wxID_ANY, _(NONE));
        wxSizer* filename_sizer = new wxBoxSizer(wxHORIZONTAL);
        filename_sizer->Add(filename_lbl, 1, wxEXPAND);
        wxButton* remove_btn = new wxButton(parent, wxID_ANY, _L("Remove"));
        wxSizer* remove_sizer = new wxBoxSizer(wxHORIZONTAL);
        remove_sizer->Add(remove_btn, 1, wxEXPAND);
        wxSizer* sizer = new wxBoxSizer(wxVERTICAL);
        sizer->Add(filename_sizer, 1, wxEXPAND);
        sizer->Add(load_sizer, 1, wxEXPAND);
        sizer->Add(remove_sizer, 1, wxEXPAND | wxTOP, 2);
        load_btn->Bind(wxEVT_BUTTON, ([this](wxCommandEvent& e) { load_model(); }));
        remove_btn->Bind(wxEVT_BUTTON, ([this](wxCommandEvent& e) {
                m_custom_model = NONE;
                update_shape();
            }));
        filename_lbl->Bind(wxEVT_UPDATE_UI, ([this](wxUpdateUIEvent& e) {
                e.SetText(_(boost::filesystem::path(m_custom_model).filename().string()));
                wxStaticText* lbl = dynamic_cast<wxStaticText*>(e.GetEventObject());
                if (lbl != nullptr) {
                    bool exists = (m_custom_model == NONE) || boost::filesystem::exists(m_custom_model);
                    lbl->SetForegroundColour(exists ? wxGetApp().get_label_clr_default() : wxColor(*wxRED));
                    wxString tooltip_text = "";
                    if (m_custom_model != NONE) {
                        if (!exists)
                            tooltip_text += _L("Not found:") + " ";
                        tooltip_text += _(m_custom_model);
                    }
                    wxToolTip* tooltip = lbl->GetToolTip();
                    if ((tooltip == nullptr) || (tooltip->GetTip() != tooltip_text))
                        lbl->SetToolTip(tooltip_text);
                }
            }));
        remove_btn->Bind(wxEVT_UPDATE_UI, ([this](wxUpdateUIEvent& e) { e.Enable(m_custom_model != NONE); }));
        return sizer;
    };
    optgroup->append_line(line);
    optgroup->activate();
    panel->SetSizerAndFit(optgroup->sizer);
    return panel;
}
References _, _L, exists(), Slic3r::GUI::Line::full_width, load_model(), m_custom_model, NONE, update_shape(), and wxEVT_BUTTON.
Referenced by build_panel().
init_shape_options_page()
ConfigOptionsGroupShp Slic3r::GUI::BedShapePanel::init_shape_options_page (const wxString & title) private
{
    wxPanel* panel = new wxPanel(m_shape_options_book);
    ConfigOptionsGroupShp optgroup = std::make_shared<ConfigOptionsGroup>(panel, _L("Settings"));
    optgroup->label_width = 10;
    optgroup->m_on_change = [this](t_config_option_key opt_key, boost::any value) {
        update_shape();
    };
    m_optgroups.push_back(optgroup);
//    panel->SetSizerAndFit(optgroup->sizer);
    m_shape_options_book->AddPage(panel, title);
    return optgroup;
}
References _L, m_optgroups, m_shape_options_book, and update_shape().
Referenced by build_panel().
init_texture_panel()
wxPanel * Slic3r::GUI::BedShapePanel::init_texture_panel () private
{
    wxPanel* panel = new wxPanel(this);
    wxGetApp().UpdateDarkUI(panel, true);
    ConfigOptionsGroupShp optgroup = std::make_shared<ConfigOptionsGroup>(panel, _L("Texture"));
    optgroup->label_width = 10;
    optgroup->m_on_change = [this](t_config_option_key opt_key, boost::any value) {
        update_shape();
    };
    Line line{ "", "" };
    line.full_width = 1;
    line.widget = [this](wxWindow* parent) {
        wxButton* load_btn = new wxButton(parent, wxID_ANY, _L("Load..."));
        wxSizer* load_sizer = new wxBoxSizer(wxHORIZONTAL);
        load_sizer->Add(load_btn, 1, wxEXPAND);
        wxStaticText* filename_lbl = new wxStaticText(parent, wxID_ANY, _(NONE));
        wxSizer* filename_sizer = new wxBoxSizer(wxHORIZONTAL);
        filename_sizer->Add(filename_lbl, 1, wxEXPAND);
        wxButton* remove_btn = new wxButton(parent, wxID_ANY, _L("Remove"));
        wxSizer* remove_sizer = new wxBoxSizer(wxHORIZONTAL);
        remove_sizer->Add(remove_btn, 1, wxEXPAND);
        wxSizer* sizer = new wxBoxSizer(wxVERTICAL);
        sizer->Add(filename_sizer, 1, wxEXPAND);
        sizer->Add(load_sizer, 1, wxEXPAND);
        sizer->Add(remove_sizer, 1, wxEXPAND | wxTOP, 2);
        load_btn->Bind(wxEVT_BUTTON, ([this](wxCommandEvent& e) { load_texture(); }));
        remove_btn->Bind(wxEVT_BUTTON, ([this](wxCommandEvent& e) {
                m_custom_texture = NONE;
                update_shape();
            }));
        filename_lbl->Bind(wxEVT_UPDATE_UI, ([this](wxUpdateUIEvent& e) {
                e.SetText(_(boost::filesystem::path(m_custom_texture).filename().string()));
                wxStaticText* lbl = dynamic_cast<wxStaticText*>(e.GetEventObject());
                if (lbl != nullptr) {
                    bool exists = (m_custom_texture == NONE) || boost::filesystem::exists(m_custom_texture);
                    lbl->SetForegroundColour(exists ? wxGetApp().get_label_clr_default() : wxColor(*wxRED));
                    wxString tooltip_text = "";
                    if (m_custom_texture != NONE) {
                        if (!exists)
                            tooltip_text += _L("Not found:") + " ";
                        tooltip_text += _(m_custom_texture);
                    }
                    wxToolTip* tooltip = lbl->GetToolTip();
                    if ((tooltip == nullptr) || (tooltip->GetTip() != tooltip_text))
                        lbl->SetToolTip(tooltip_text);
                }
            }));
        remove_btn->Bind(wxEVT_UPDATE_UI, ([this](wxUpdateUIEvent& e) { e.Enable(m_custom_texture != NONE); }));
        return sizer;
    };
    optgroup->append_line(line);
    optgroup->activate();
    panel->SetSizerAndFit(optgroup->sizer);
    return panel;
}
References _, _L, exists(), Slic3r::GUI::Line::full_width, load_texture(), m_custom_texture, NONE, update_shape(), and wxEVT_BUTTON.
Referenced by build_panel().
load_model()
void Slic3r::GUI::BedShapePanel::load_model () private
{
    wxFileDialog dialog(this, _L("Choose an STL file to import bed model from:"), "", "",
        file_wildcards(FT_STL), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() != wxID_OK)
        return;
    m_custom_model = NONE;
    std::string file_name = dialog.GetPath().ToUTF8().data();
    if (!boost::algorithm::iends_with(file_name, ".stl")) {
        show_error(this, _L("Invalid file format."));
        return;
    }
    wxBusyCursor wait;
    m_custom_model = file_name;
    update_shape();
}
References _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_STL, m_custom_model, NONE, Slic3r::GUI::show_error(), and update_shape().
Referenced by init_model_panel().
load_stl()
void Slic3r::GUI::BedShapePanel::load_stl () private
{
    wxFileDialog dialog(this, _L("Choose an STL file to import bed shape from:"), "", "", file_wildcards(FT_STL), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() != wxID_OK)
        return;
    std::string file_name = dialog.GetPath().ToUTF8().data();
    if (!boost::algorithm::iends_with(file_name, ".stl")) {
        show_error(this, _L("Invalid file format."));
        return;
    }
    wxBusyCursor wait;
  Model model;
  try {
        model = Model::read_from_file(file_name);
  }
  catch (std::exception &) {
        show_error(this, _L("Error! Invalid model"));
        return;
    }
  auto mesh = model.mesh();
  auto expolygons = mesh.horizontal_projection();
  if (expolygons.size() == 0) {
    show_error(this, _L("The selected file contains no geometry."));
    return;
  }
  if (expolygons.size() > 1) {
    show_error(this, _L("The selected file contains several disjoint areas. This is not supported."));
    return;
  }
  auto polygon = expolygons[0].contour;
  std::vector<Vec2d> points;
  for (auto pt : polygon.points)
    points.push_back(unscale(pt));
    m_loaded_shape = points;
    update_shape();
}
References _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_STL, Slic3r::TriangleMesh::horizontal_projection(), m_loaded_shape, Slic3r::Model::mesh(), Slic3r::Model::read_from_file(), Slic3r::GUI::show_error(), Slic3r::unscale(), and update_shape().
Referenced by build_panel().
load_texture()
void Slic3r::GUI::BedShapePanel::load_texture () private
{
    wxFileDialog dialog(this, _L("Choose a file to import bed texture from (PNG/SVG):"), "", "",
        file_wildcards(FT_TEX), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() != wxID_OK)
        return;
    m_custom_texture = NONE;
    std::string file_name = dialog.GetPath().ToUTF8().data();
    if (!boost::algorithm::iends_with(file_name, ".png") && !boost::algorithm::iends_with(file_name, ".svg")) {
        show_error(this, _L("Invalid file format."));
        return;
    }
    wxBusyCursor wait;
    m_custom_texture = file_name;
    update_shape();
}
References _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_TEX, m_custom_texture, NONE, Slic3r::GUI::show_error(), and update_shape().
Referenced by init_texture_panel().
set_shape()
void Slic3r::GUI::BedShapePanel::set_shape (const ConfigOptionPoints & points) private
{
    BedShape shape(points);
    m_shape_options_book->SetSelection(int(shape.get_page_type()));
    shape.apply_optgroup_values(m_optgroups[int(shape.get_page_type())]);
    // Copy the polygon to the canvas, make a copy of the array, if custom shape is selected
    if (shape.is_custom())
        m_loaded_shape = points.values;
    update_shape();
}
References Slic3r::GUI::BedShape::apply_optgroup_values(), Slic3r::GUI::BedShape::get_page_type(), Slic3r::GUI::BedShape::is_custom(), m_loaded_shape, m_optgroups, m_shape_options_book, update_shape(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by build_panel().
update_preview()
void Slic3r::GUI::BedShapePanel::update_preview () private
{
  if (m_canvas) m_canvas->Refresh();
  Refresh();
}
References m_canvas.
Referenced by build_panel(), and update_shape().
update_shape()
void Slic3r::GUI::BedShapePanel::update_shape () private
{
  auto page_idx = m_shape_options_book->GetSelection();
    auto opt_group = m_optgroups[page_idx];
    switch (static_cast<BedShape::PageType>(page_idx)) {
    case BedShape::PageType::Rectangle:
    {
        Vec2d rect_size(Vec2d::Zero());
    Vec2d rect_origin(Vec2d::Zero());
    try { rect_size = boost::any_cast<Vec2d>(opt_group->get_value("rect_size")); }
        catch (const std::exception& /* e */) { return; }
        try { rect_origin = boost::any_cast<Vec2d>(opt_group->get_value("rect_origin")); }
    catch (const std::exception & /* e */)  { return; }
    auto x = rect_size(0);
    auto y = rect_size(1);
    // empty strings or '-' or other things
    if (x == 0 || y == 0) return;
    double x0 = 0.0;
    double y0 = 0.0;
    double x1 = x;
    double y1 = y;
    auto dx = rect_origin(0);
    auto dy = rect_origin(1);
    x0 -= dx;
    x1 -= dx;
    y0 -= dy;
    y1 -= dy;
        m_shape = { Vec2d(x0, y0),
                    Vec2d(x1, y0),
                    Vec2d(x1, y1),
                    Vec2d(x0, y1) };
        break;
    }
    case BedShape::PageType::Circle:
    {
        double diameter;
    try { diameter = boost::any_cast<double>(opt_group->get_value("diameter")); }
    catch (const std::exception & /* e */) { return; }
    if (diameter == 0.0) return ;
    auto r = diameter / 2;
    auto twopi = 2 * PI;
        // Don't change this value without adjusting BuildVolume constructor detecting circle diameter!
        auto edges = 72;
        std::vector<Vec2d> points;
        for (int i = 1; i <= edges; ++i) {
            auto angle = i * twopi / edges;
      points.push_back(Vec2d(r*cos(angle), r*sin(angle)));
    }
        m_shape = points;
        break;
    }
    case BedShape::PageType::Custom:
        m_shape = m_loaded_shape;
        break;
    }
    update_preview();
}
References Slic3r::angle(), Slic3r::GUI::BedShape::Circle, cos(), Slic3r::GUI::BedShape::Custom, m_loaded_shape, m_optgroups, m_shape, m_shape_options_book, PI, Slic3r::GUI::BedShape::Rectangle, sin(), and update_preview().
Referenced by build_panel(), init_model_panel(), init_shape_options_page(), init_texture_panel(), load_model(), load_stl(), load_texture(), and set_shape().
Friends And Related Symbol Documentation
BedShapeDialog
friend class BedShapeDialog friend
Member Data Documentation
EMPTY_STRING
const std::string Slic3r::GUI::BedShapePanel::EMPTY_STRING = "" static private
Referenced by get_custom_model(), and get_custom_texture().
m_canvas
Bed_2D* Slic3r::GUI::BedShapePanel::m_canvas private
Referenced by build_panel(), and update_preview().
m_custom_model
std::string Slic3r::GUI::BedShapePanel::m_custom_model private
Referenced by build_panel(), get_custom_model(), init_model_panel(), and load_model().
m_custom_texture
std::string Slic3r::GUI::BedShapePanel::m_custom_texture private
Referenced by build_panel(), get_custom_texture(), init_texture_panel(), and load_texture().
m_loaded_shape
std::vector<Vec2d> Slic3r::GUI::BedShapePanel::m_loaded_shape private
Referenced by load_stl(), set_shape(), and update_shape().
m_optgroups
std::vector<ConfigOptionsGroupShp> Slic3r::GUI::BedShapePanel::m_optgroups private
Referenced by init_shape_options_page(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), set_shape(), and update_shape().
m_shape
std::vector<Vec2d> Slic3r::GUI::BedShapePanel::m_shape private
Referenced by build_panel(), get_shape(), and update_shape().
m_shape_options_book
wxChoicebook* Slic3r::GUI::BedShapePanel::m_shape_options_book private
Referenced by build_panel(), init_shape_options_page(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), set_shape(), and update_shape().
NONE
const std::string Slic3r::GUI::BedShapePanel::NONE = "None" static private
Referenced by build_panel(), get_custom_model(), get_custom_texture(), init_model_panel(), init_texture_panel(), load_model(), and load_texture().
The documentation for this class was generated from the following files:
src/slic3r/GUI/BedShapeDialog.hpp
src/slic3r/GUI/BedShapeDialog.cpp