Prusa Slicer: src/avrdude/butterfly.h File Reference
butterfly.h File Reference
Functions
void butterfly_initpgm (PROGRAMMER *pgm)
void butterfly_mk_initpgm (PROGRAMMER *pgm)
Variables
const char butterfly_desc []
const char butterfly_mk_desc []
Function Documentation
butterfly_initpgm()
void butterfly_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "butterfly");
  /*
   * mandatory functions
   */
  pgm->rdy_led        = butterfly_rdy_led;
  pgm->err_led        = butterfly_err_led;
  pgm->pgm_led        = butterfly_pgm_led;
  pgm->vfy_led        = butterfly_vfy_led;
  pgm->initialize     = butterfly_initialize;
  pgm->display        = butterfly_display;
  pgm->enable         = butterfly_enable;
  pgm->disable        = butterfly_disable;
  pgm->powerup        = butterfly_powerup;
  pgm->powerdown      = butterfly_powerdown;
  pgm->program_enable = butterfly_program_enable;
  pgm->chip_erase     = butterfly_chip_erase;
  pgm->open           = butterfly_open;
  pgm->close          = butterfly_close;
  pgm->read_byte      = butterfly_read_byte;
  pgm->write_byte     = butterfly_write_byte;
  /*
   * optional functions
   */
  pgm->page_erase = butterfly_page_erase;
  pgm->paged_write = butterfly_paged_write;
  pgm->paged_load = butterfly_paged_load;
  pgm->read_sig_bytes = butterfly_read_sig_bytes;
  pgm->setup          = butterfly_setup;
  pgm->teardown       = butterfly_teardown;
  pgm->flag = 0;
}
References butterfly_chip_erase(), butterfly_close(), butterfly_disable(), butterfly_display(), butterfly_enable(), butterfly_err_led(), butterfly_initialize(), butterfly_open(), butterfly_page_erase(), butterfly_paged_load(), butterfly_paged_write(), butterfly_pgm_led(), butterfly_powerdown(), butterfly_powerup(), butterfly_program_enable(), butterfly_rdy_led(), butterfly_read_byte(), butterfly_read_sig_bytes(), butterfly_setup(), butterfly_teardown(), butterfly_vfy_led(), butterfly_write_byte(), programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::err_led, programmer_t::flag, programmer_t::initialize, programmer_t::open, programmer_t::page_erase, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::pgm_led, programmer_t::powerdown, programmer_t::powerup, programmer_t::program_enable, programmer_t::rdy_led, programmer_t::read_byte, programmer_t::read_sig_bytes, programmer_t::setup, programmer_t::teardown, programmer_t::type, programmer_t::vfy_led, and programmer_t::write_byte.
Referenced by butterfly_mk_initpgm().
butterfly_mk_initpgm()
void butterfly_mk_initpgm (PROGRAMMER * pgm)
{
  butterfly_initpgm(pgm);
  strcpy(pgm->type, "butterfly_mk");
  pgm->flag = IS_BUTTERFLY_MK;
}
References butterfly_initpgm(), programmer_t::flag, IS_BUTTERFLY_MK, pgm, and programmer_t::type.
Variable Documentation
butterfly_desc
const char butterfly_desc[] extern
butterfly_mk_desc
const char butterfly_mk_desc[] extern