Prusa Slicer: Slic3r::GUI::anonymous_namespace{Downloader.cpp} Namespace Reference
Slic3r::GUI::anonymous_namespace{Downloader.cpp} Namespace Reference
Functions
void open_folder (const std::string &path)
std::string filename_from_url (const std::string &url)
Function Documentation
filename_from_url()
std::string Slic3r::GUI::anonymous_namespace{Downloader.cpp}::filename_from_url (const std::string & url)
{
  // TODO: can it be done with curl?
  size_t slash = url.find_last_of("/");
  if (slash == std::string::npos && slash != url.size() - 1)
    return std::string();
  return url.substr(slash + 1, url.size() - slash + 1);
}
References filename_from_url().
Referenced by filename_from_url().
open_folder()
void Slic3r::GUI::anonymous_namespace{Downloader.cpp}::open_folder (const std::string & path)
{
  // Code taken from NotificationManager.cpp
  // Execute command to open a file explorer, platform dependent.
  // FIXME: The const_casts aren't needed in wxWidgets 3.1, remove them when we upgrade.
#ifdef _WIN32
  const wxString widepath = from_u8(path);
  const wchar_t* argv[] = { L"explorer", widepath.GetData(), nullptr };
  ::wxExecute(const_cast<wchar_t**>(argv), wxEXEC_ASYNC, nullptr);
#elif __APPLE__
  const char* argv[] = { "open", path.data(), nullptr };
  ::wxExecute(const_cast<char**>(argv), wxEXEC_ASYNC, nullptr);
#else
  const char* argv[] = { "xdg-open", path.data(), nullptr };
  // Check if we're running in an AppImage container, if so, we need to remove AppImage's env vars,
  // because they may mess up the environment expected by the file manager.
  // Mostly this is about LD_LIBRARY_PATH, but we remove a few more too for good measure.
  if (wxGetEnv("APPIMAGE", nullptr)) {
    // We're running from AppImage
    wxEnvVariableHashMap env_vars;
    wxGetEnvMap(&env_vars);
    env_vars.erase("APPIMAGE");
    env_vars.erase("APPDIR");
    env_vars.erase("LD_LIBRARY_PATH");
    env_vars.erase("LD_PRELOAD");
    env_vars.erase("UNION_PRELOAD");
    wxExecuteEnv exec_env;
    exec_env.env = std::move(env_vars);
    wxString owd;
    if (wxGetEnv("OWD", &owd)) {
      // This is the original work directory from which the AppImage image was run,
      // set it as CWD for the child process:
      exec_env.cwd = std::move(owd);
    }
    ::wxExecute(const_cast<char**>(argv), wxEXEC_ASYNC, nullptr, &exec_env);
  }
  else {
    // Looks like we're NOT running from AppImage, we'll make no changes to the environment.
    ::wxExecute(const_cast<char**>(argv), wxEXEC_ASYNC, nullptr, nullptr);
  }
#endif
}
References Slic3r::GUI::from_u8(), L, and open_folder().
Referenced by open_folder().