Prusa Slicer: Eigen::HouseholderSequence< VectorsType, CoeffsType, Side > Class Template Reference
Eigen::HouseholderSequence< VectorsType, CoeffsType, Side > Class Template Reference
Sequence of Householder reflections acting on subspaces with decreasing size.
#include <src/eigen/Eigen/src/Householder/HouseholderSequence.h>
Public Types
enum { RowsAtCompileTime = internal::traits<HouseholderSequence>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<HouseholderSequence>::ColsAtCompileTime , MaxRowsAtCompileTime = internal::traits<HouseholderSequence>::MaxRowsAtCompileTime , MaxColsAtCompileTime = internal::traits<HouseholderSequence>::MaxColsAtCompileTime }
typedef internal::traits< HouseholderSequence >::Scalar Scalar
typedef HouseholderSequence< typename internal::conditional< NumTraits< Scalar >::IsComplex, typename internal::remove_all< typename VectorsType::ConjugateReturnType >::type, VectorsType >::type, typename internal::conditional< NumTraits< Scalar >::IsComplex, typename internal::remove_all< typename CoeffsType::ConjugateReturnType >::type, CoeffsType >::type, Side > ConjugateReturnType
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< HouseholderSequence< VectorsType, CoeffsType, Side > >::StorageKind StorageKind
Public Member Functions
HouseholderSequence (const VectorsType &v, const CoeffsType &h)
Constructor.
HouseholderSequence (const HouseholderSequence &other)
Copy constructor.
Index rows () const
Number of rows of transformation viewed as a matrix.
Index cols () const
Number of columns of transformation viewed as a matrix.
const EssentialVectorType essentialVector (Index k) const
Essential part of a Householder vector.
HouseholderSequence transpose () const
Transpose of the Householder sequence.
ConjugateReturnType conjugate () const
Complex conjugate of the Householder sequence.
ConjugateReturnType adjoint () const
Adjoint (conjugate transpose) of the Householder sequence.
ConjugateReturnType inverse () const
Inverse of the Householder sequence (equals the adjoint).
template<typename DestType >
void evalTo (DestType &dst) const
template<typename Dest , typename Workspace >
void evalTo (Dest &dst, Workspace &workspace) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest , typename Workspace >
void applyThisOnTheRight (Dest &dst, Workspace &workspace) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
template<typename Dest , typename Workspace >
void applyThisOnTheLeft (Dest &dst, Workspace &workspace) const
template<typename OtherDerived >
internal::matrix_type_times_scalar_type< Scalar, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other) const
Computes the product of a Householder sequence with a matrix.
HouseholderSequence & setLength (Index length)
Sets the length of the Householder sequence.
HouseholderSequence & setShift (Index shift)
Sets the shift of the Householder sequence.
Index length () const
Returns the length of the Householder sequence.
Index shift () const
Returns the shift of the Householder sequence.
EIGEN_DEVICE_FUNC HouseholderSequence< VectorsType, CoeffsType, Side > & derived ()
EIGEN_DEVICE_FUNC const HouseholderSequence< VectorsType, CoeffsType, Side > & derived () const
EIGEN_DEVICE_FUNC HouseholderSequence< VectorsType, CoeffsType, Side > & const_cast_derived () const
EIGEN_DEVICE_FUNC const HouseholderSequence< VectorsType, CoeffsType, Side > & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
Protected Member Functions
HouseholderSequence & setTrans (bool trans)
Sets the transpose flag.
bool trans () const
Returns the transpose flag.
Protected Attributes
VectorsType::Nested m_vectors
CoeffsType::Nested m_coeffs
bool m_trans
Index m_length
Index m_shift
Private Types
typedef internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::EssentialVectorType EssentialVectorType
Friends
template<typename _VectorsType , typename _CoeffsType , int _Side>
struct internal::hseq_side_dependent_impl
template<typename VectorsType2 , typename CoeffsType2 , int Side2>
class HouseholderSequence
Detailed Description
template<typename VectorsType, typename CoeffsType, int Side>
class Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >
Sequence of Householder reflections acting on subspaces with decreasing size.
\householder_module
Template Parameters
VectorsType type of matrix containing the Householder vectors
CoeffsType type of vector containing the Householder coefficients
Side either OnTheLeft (the default) or OnTheRight
This class represents a product sequence of Householder reflections where the first Householder reflection acts on the whole space, the second Householder reflection leaves the one-dimensional subspace spanned by the first unit vector invariant, the third Householder reflection leaves the two-dimensional subspace spanned by the first two unit vectors invariant, and so on up to the last reflection which leaves all but one dimensions invariant and acts only on the last dimension. Such sequences of Householder reflections are used in several algorithms to zero out certain parts of a matrix. Indeed, the methods HessenbergDecomposition::matrixQ(), Tridiagonalization::matrixQ(), HouseholderQR::householderQ(), and ColPivHouseholderQR::householderQ() all return a HouseholderSequence.
More precisely, the class HouseholderSequence represents an matrix of the form where the i-th Householder reflection is . The i-th Householder coefficient is a scalar and the i-th Householder vector is a vector of the form
The last entries of are called the essential part of the Householder vector.
Typical usages are listed below, where H is a HouseholderSequence:
A.applyOnTheRight(H);             // A = A * H
A.applyOnTheLeft(H);              // A = H * A
A.applyOnTheRight(H.adjoint());   // A = A * H^*
A.applyOnTheLeft(H.adjoint());    // A = H^* * A
MatrixXd Q = H;                   // conversion to a dense matrix
In addition to the adjoint, you can also apply the inverse (=adjoint), the transpose, and the conjugate operators.
See the documentation for HouseholderSequence(const VectorsType&, const CoeffsType&) for an example.
See also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Member Typedef Documentation
ConjugateReturnType
template<typename VectorsType , typename CoeffsType , int Side> typedef HouseholderSequence< typename internal::conditional<NumTraits<Scalar>::IsComplex, typename internal::remove_all<typename VectorsType::ConjugateReturnType>::type, VectorsType>::type, typename internal::conditional<NumTraits<Scalar>::IsComplex, typename internal::remove_all<typename CoeffsType::ConjugateReturnType>::type, CoeffsType>::type, Side > Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::ConjugateReturnType
EssentialVectorType
template<typename VectorsType , typename CoeffsType , int Side> typedef internal::hseq_side_dependent_impl<VectorsType,CoeffsType,Side>::EssentialVectorType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::EssentialVectorType private
Index
typedef Eigen::Index Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
Scalar
template<typename VectorsType , typename CoeffsType , int Side> typedef internal::traits<HouseholderSequence>::Scalar Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::Scalar
StorageKind
typedef internal::traits<HouseholderSequence< VectorsType, CoeffsType, Side > >::StorageKind Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::StorageKind inherited
Member Enumeration Documentation
anonymous enum
template<typename VectorsType , typename CoeffsType , int Side> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
         {
      RowsAtCompileTime = internal::traits<HouseholderSequence>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<HouseholderSequence>::ColsAtCompileTime,
      MaxRowsAtCompileTime = internal::traits<HouseholderSequence>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<HouseholderSequence>::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
HouseholderSequence() [1/2]
template<typename VectorsType , typename CoeffsType , int Side> Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::HouseholderSequence (const VectorsType & v, const CoeffsType & h) inline
Constructor.
Parameters
[in] v Matrix containing the essential parts of the Householder vectors
[in] h Vector containing the Householder coefficients
Constructs the Householder sequence with coefficients given by h and vectors given by v. The i-th Householder coefficient is given by h(i) and the essential part of the i-th Householder vector is given by v(k,i) with k > i (the subdiagonal part of the i-th column). If v has fewer columns than rows, then the Householder sequence contains as many Householder reflections as there are columns.
Note
The HouseholderSequence object stores v and h by reference.
Example:
Output:
See also
setLength(), setShift()
      : m_vectors(v), m_coeffs(h), m_trans(false), m_length(v.diagonalSize()),
        m_shift(0)
    {
    }
HouseholderSequence() [2/2]
template<typename VectorsType , typename CoeffsType , int Side> Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::HouseholderSequence (const HouseholderSequence< VectorsType, CoeffsType, Side > & other) inline
Copy constructor.
      : m_vectors(other.m_vectors),
        m_coeffs(other.m_coeffs),
        m_trans(other.m_trans),
        m_length(other.m_length),
        m_shift(other.m_shift)
    {
    }
Member Function Documentation
addTo()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
template<typename VectorsType , typename CoeffsType , int Side> ConjugateReturnType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint () const inline
Adjoint (conjugate transpose) of the Householder sequence.
    {
      return conjugate().setTrans(!m_trans);
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setTrans().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::inverse().
applyThisOnTheLeft() [1/2]
template<typename VectorsType , typename CoeffsType , int Side> template<typename Dest > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft (Dest & dst) const inline
    {
      Matrix<Scalar,1,Dest::ColsAtCompileTime,RowMajor,1,Dest::MaxColsAtCompileTime> workspace;
      applyThisOnTheLeft(dst, workspace);
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::operator*().
applyThisOnTheLeft() [2/2]
template<typename VectorsType , typename CoeffsType , int Side> template<typename Dest , typename Workspace > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft (Dest & dst, Workspace & workspace) const inline
    {
      const Index BlockSize = 48;
      // if the entries are large enough, then apply the reflectors by block
      if(m_length>=BlockSize && dst.cols()>1)
      {
        for(Index i = 0; i < m_length; i+=BlockSize)
        {
          Index end = m_trans ? (std::min)(m_length,i+BlockSize) : m_length-i;
          Index k = m_trans ? i : (std::max)(Index(0),end-BlockSize);
          Index bs = end-k;
          Index start = k + m_shift;
          typedef Block<typename internal::remove_all<VectorsType>::type,Dynamic,Dynamic> SubVectorsType;
          SubVectorsType sub_vecs1(m_vectors.const_cast_derived(), Side==OnTheRight ? k : start,
                                                                   Side==OnTheRight ? start : k,
                                                                   Side==OnTheRight ? bs : m_vectors.rows()-start,
                                                                   Side==OnTheRight ? m_vectors.cols()-start : bs);
          typename internal::conditional<Side==OnTheRight, Transpose<SubVectorsType>, SubVectorsType&>::type sub_vecs(sub_vecs1);
          Block<Dest,Dynamic,Dynamic> sub_dst(dst,dst.rows()-rows()+m_shift+k,0, rows()-m_shift-k,dst.cols());
          apply_block_householder_on_the_left(sub_dst, sub_vecs, m_coeffs.segment(k, bs), !m_trans);
        }
      }
      else
      {
        workspace.resize(dst.cols());
        for(Index k = 0; k < m_length; ++k)
        {
          Index actual_k = m_trans ? k : m_length-k-1;
          dst.bottomRows(rows()-m_shift-actual_k)
            .applyHouseholderOnTheLeft(essentialVector(actual_k), m_coeffs.coeff(actual_k), workspace.data());
        }
      }
    }
References Eigen::Dynamic, Eigen::end(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors, Eigen::OnTheRight, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
applyThisOnTheRight() [1/2]
template<typename VectorsType , typename CoeffsType , int Side> template<typename Dest > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight (Dest & dst) const inline
    {
      Matrix<Scalar,1,Dest::RowsAtCompileTime,RowMajor,1,Dest::MaxRowsAtCompileTime> workspace(dst.rows());
      applyThisOnTheRight(dst, workspace);
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), and Eigen::operator*().
applyThisOnTheRight() [2/2]
template<typename VectorsType , typename CoeffsType , int Side> template<typename Dest , typename Workspace > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight (Dest & dst, Workspace & workspace) const inline
    {
      workspace.resize(dst.rows());
      for(Index k = 0; k < m_length; ++k)
      {
        Index actual_k = m_trans ? m_length-k-1 : k;
        dst.rightCols(rows()-m_shift-actual_k)
           .applyHouseholderOnTheRight(essentialVector(actual_k), m_coeffs.coeff(actual_k), workspace.data());
      }
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
cols()
template<typename VectorsType , typename CoeffsType , int Side> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::cols () const inline
Number of columns of transformation viewed as a matrix.
Returns
Number of columns
This equals the dimension of the space that the transformation acts on.
{ return rows(); }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo().
conjugate()
template<typename VectorsType , typename CoeffsType , int Side> ConjugateReturnType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate () const inline
Complex conjugate of the Householder sequence.
    {
      return ConjugateReturnType(m_vectors.conjugate(), m_coeffs.conjugate())
             .setTrans(m_trans)
             .setLength(m_length)
             .setShift(m_shift);
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint().
const_cast_derived()
EIGEN_DEVICE_FUNC HouseholderSequence< VectorsType, CoeffsType, Side > & Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
const_derived()
EIGEN_DEVICE_FUNC const HouseholderSequence< VectorsType, CoeffsType, Side > & Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
EIGEN_DEVICE_FUNC HouseholderSequence< VectorsType, CoeffsType, Side > & Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::derived () inline inherited
Returns
a reference to the derived object
{ return *static_cast<Derived*>(this); }
derived() [2/2]
EIGEN_DEVICE_FUNC const HouseholderSequence< VectorsType, CoeffsType, Side > & Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::derived () const inline inherited
Returns
a const reference to the derived object
{ return *static_cast<const Derived*>(this); }
essentialVector()
template<typename VectorsType , typename CoeffsType , int Side> const EssentialVectorType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector (Index k) const inline
Essential part of a Householder vector.
Parameters
[in] k Index of Householder reflection
Returns
Vector containing non-trivial entries of k-th Householder vector
This function returns the essential part of the Householder vector . This is a vector of length containing the last entries of the vector
The index equals k + shift(), corresponding to the k-th column of the matrix v passed to the constructor.
See also
setShift(), shift()
    {
      eigen_assert(k >= 0 && k < m_length);
      return internal::hseq_side_dependent_impl<VectorsType,CoeffsType,Side>::essentialVector(*this, k);
    }
References eigen_assert, Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo().
evalTo() [1/3]
EIGEN_DEVICE_FUNC void Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
evalTo() [2/3]
template<typename VectorsType , typename CoeffsType , int Side> template<typename Dest , typename Workspace > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo (Dest & dst, Workspace & workspace) const inline
    {
      workspace.resize(rows());
      Index vecs = m_length;
      if(internal::is_same_dense(dst,m_vectors))
      {
        // in-place
        dst.diagonal().setOnes();
        dst.template triangularView<StrictlyUpper>().setZero();
        for(Index k = vecs-1; k >= 0; --k)
        {
          Index cornerSize = rows() - k - m_shift;
          if(m_trans)
            dst.bottomRightCorner(cornerSize, cornerSize)
               .applyHouseholderOnTheRight(essentialVector(k), m_coeffs.coeff(k), workspace.data());
          else
            dst.bottomRightCorner(cornerSize, cornerSize)
               .applyHouseholderOnTheLeft(essentialVector(k), m_coeffs.coeff(k), workspace.data());
          // clear the off diagonal vector
          dst.col(k).tail(rows()-k-1).setZero();
        }
        // clear the remaining columns if needed
        for(Index k = 0; k<cols()-vecs ; ++k)
          dst.col(k).tail(rows()-k-1).setZero();
      }
      else
      {
        dst.setIdentity(rows(), rows());
        for(Index k = vecs-1; k >= 0; --k)
        {
          Index cornerSize = rows() - k - m_shift;
          if(m_trans)
            dst.bottomRightCorner(cornerSize, cornerSize)
               .applyHouseholderOnTheRight(essentialVector(k), m_coeffs.coeff(k), &workspace.coeffRef(0));
          else
            dst.bottomRightCorner(cornerSize, cornerSize)
               .applyHouseholderOnTheLeft(essentialVector(k), m_coeffs.coeff(k), &workspace.coeffRef(0));
        }
      }
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::cols(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::internal::is_same_dense(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
evalTo() [3/3]
template<typename VectorsType , typename CoeffsType , int Side> template<typename DestType > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo (DestType & dst) const inline
    {
      Matrix<Scalar, DestType::RowsAtCompileTime, 1,
             AutoAlign|ColMajor, DestType::MaxRowsAtCompileTime, 1> workspace(rows());
      evalTo(dst, workspace);
    }
References Eigen::AutoAlign, Eigen::ColMajor, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo().
inverse()
template<typename VectorsType , typename CoeffsType , int Side> ConjugateReturnType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::inverse () const inline
Inverse of the Householder sequence (equals the adjoint).
{ return adjoint(); }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint().
length()
template<typename VectorsType , typename CoeffsType , int Side> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::length () const inline
Returns the length of the Householder sequence.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength().
operator*()
template<typename VectorsType , typename CoeffsType , int Side> template<typename OtherDerived > internal::matrix_type_times_scalar_type< Scalar, OtherDerived >::Type Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::operator* (const MatrixBase< OtherDerived > & other) const inline
Computes the product of a Householder sequence with a matrix.
Parameters
[in] other Matrix being multiplied.
Returns
Expression object representing the product.
This function computes where is the Householder sequence represented by *this and is the matrix other.
    {
      typename internal::matrix_type_times_scalar_type<Scalar, OtherDerived>::Type
        res(other.template cast<typename internal::matrix_type_times_scalar_type<Scalar,OtherDerived>::ResultScalar>());
      applyThisOnTheLeft(res);
      return res;
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), and cast().
rows()
template<typename VectorsType , typename CoeffsType , int Side> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows () const inline
Number of rows of transformation viewed as a matrix.
Returns
Number of rows
This equals the dimension of the space that the transformation acts on.
{ return Side==OnTheLeft ? m_vectors.rows() : m_vectors.cols(); }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors, and Eigen::OnTheLeft.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::cols(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo().
setLength()
template<typename VectorsType , typename CoeffsType , int Side> HouseholderSequence & Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength (Index length) inline
Sets the length of the Householder sequence.
Parameters
[in] length New value for the length.
By default, the length of the Householder sequence is set to the number of columns of the matrix v passed to the constructor, or the number of rows if that is smaller. After this function is called, the length equals length.
See also
length()
    {
      m_length = length;
      return *this;
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::length(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length.
Referenced by Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run().
setShift()
template<typename VectorsType , typename CoeffsType , int Side> HouseholderSequence & Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setShift (Index shift) inline
Sets the shift of the Householder sequence.
Parameters
[in] shift New value for the shift.
By default, a HouseholderSequence object represents and the i-th column of the matrix v passed to the constructor corresponds to the i-th Householder reflection. After this function is called, the object represents and the i-th column of v corresponds to the (shift+i)-th Householder reflection.
See also
shift()
    {
      m_shift = shift;
      return *this;
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::shift().
Referenced by Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run().
setTrans()
template<typename VectorsType , typename CoeffsType , int Side> HouseholderSequence & Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setTrans (bool trans) inline protected
Sets the transpose flag.
Parameters
[in] trans New value of the transpose flag.
By default, the transpose flag is not set. If the transpose flag is set, then this object represents instead of .
See also
trans()
    {
      m_trans = trans;
      return *this;
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::trans().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint().
shift()
template<typename VectorsType , typename CoeffsType , int Side> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::shift () const inline
Returns the shift of the Householder sequence.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setShift().
size()
EIGEN_DEVICE_FUNC Index Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
subTo()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
trans()
template<typename VectorsType , typename CoeffsType , int Side> bool Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::trans () const inline protected
Returns the transpose flag.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setTrans().
transpose()
template<typename VectorsType , typename CoeffsType , int Side> HouseholderSequence Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::transpose () const inline
Transpose of the Householder sequence.
    {
      return HouseholderSequence(*this).setTrans(!m_trans);
    }
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::HouseholderSequence, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans.
Referenced by igl::per_vertex_point_to_plane_quadrics().
Friends And Related Symbol Documentation
HouseholderSequence
template<typename VectorsType , typename CoeffsType , int Side> template<typename VectorsType2 , typename CoeffsType2 , int Side2> friend class HouseholderSequence friend
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::transpose().
internal::hseq_side_dependent_impl
template<typename VectorsType , typename CoeffsType , int Side> template<typename _VectorsType , typename _CoeffsType , int _Side> friend struct internal::hseq_side_dependent_impl friend
Member Data Documentation
m_coeffs
template<typename VectorsType , typename CoeffsType , int Side> CoeffsType::Nested Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs protected
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo().
m_length
template<typename VectorsType , typename CoeffsType , int Side> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length protected
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::length(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength().
m_shift
template<typename VectorsType , typename CoeffsType , int Side> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift protected
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setShift(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::shift().
m_trans
template<typename VectorsType , typename CoeffsType , int Side> bool Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans protected
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setTrans(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::trans(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::transpose().
m_vectors
template<typename VectorsType , typename CoeffsType , int Side> VectorsType::Nested Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors protected
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/util/ForwardDeclarations.h
src/eigen/Eigen/src/Householder/HouseholderSequence.h