Prusa Slicer: Slic3r::GUI::AppUpdateDownloadDialog Class Reference
Slic3r::GUI::AppUpdateDownloadDialog Class Reference
#include <src/slic3r/GUI/UpdateDialogs.hpp>
Public Member Functions
AppUpdateDownloadDialog (const Semver &ver_online, boost::filesystem::path &path)
AppUpdateDownloadDialog (AppUpdateDownloadDialog &&)=delete
AppUpdateDownloadDialog (const AppUpdateDownloadDialog &)=delete
AppUpdateDownloadDialog & operator= (AppUpdateDownloadDialog &&)=delete
AppUpdateDownloadDialog & operator= (const AppUpdateDownloadDialog &)=delete
virtual ~AppUpdateDownloadDialog ()
bool run_after_download () const
boost::filesystem::path get_download_path () const
void SetButtonLabel (wxWindowID btn_id, const wxString &label, bool set_focus=false)
Protected Types
enum {
CONTENT_WIDTH = 70 , CONTENT_MAX_HEIGHT = 60 , BORDER = 30 , VERT_SPACING = 15 ,
HORIZ_SPACING = 5
}
Protected Member Functions
wxButton * add_button (wxWindowID btn_id, bool set_focus=false, const wxString &label=wxString())
wxButton * get_button (wxWindowID btn_id)
void apply_style (long style)
void finalize ()
Protected Attributes
wxFont boldfont
wxBoxSizer * content_sizer
wxBoxSizer * btn_sizer
wxStaticBitmap * logo
Private Attributes
wxCheckBox * cbox_run
wxTextCtrl * txtctrl_path
wxString filename
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum protected inherited
Enumerator
CONTENT_WIDTH
CONTENT_MAX_HEIGHT
BORDER
VERT_SPACING
HORIZ_SPACING
       {
    CONTENT_WIDTH = 70,//50,
    CONTENT_MAX_HEIGHT = 60,
    BORDER = 30,
    VERT_SPACING = 15,
    HORIZ_SPACING = 5,
  };
Constructor & Destructor Documentation
AppUpdateDownloadDialog() [1/3]
Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog (const Semver & ver_online, boost::filesystem::path & path)
  : MsgDialog(nullptr, _L("App Update download"), format_wxstr(_L("New version of %1% is available."), SLIC3R_APP_NAME))
{
  auto* versions = new wxFlexGridSizer(2, 0, VERT_SPACING);
  versions->Add(new wxStaticText(this, wxID_ANY, _L("New version") + ":"));
  versions->Add(new wxStaticText(this, wxID_ANY, ver_online.to_string()));
  content_sizer->Add(versions);
  content_sizer->AddSpacer(VERT_SPACING);
#ifndef __linux__
  cbox_run = new wxCheckBox(this, wxID_ANY, _(L("Run installer after download. (Otherwise file explorer will be opened)")));
  content_sizer->Add(cbox_run);
#endif
  content_sizer->AddSpacer(VERT_SPACING);
  content_sizer->AddSpacer(VERT_SPACING);
  content_sizer->Add(new wxStaticText(this, wxID_ANY, _L("Target directory") + ":"));
  content_sizer->AddSpacer(VERT_SPACING);
  txtctrl_path = new wxTextCtrl(this, wxID_ANY, GUI::format_wxstr(path.parent_path().string()));
  filename = GUI::format_wxstr(path.filename().string());
  content_sizer->Add(txtctrl_path, 1, wxEXPAND);
  content_sizer->AddSpacer(VERT_SPACING);
  wxButton* btn = new wxButton(this, wxID_ANY, _L("Select directory"));
  content_sizer->Add(btn/*, 1, wxEXPAND*/);
  // button to open file dialog
  btn->Bind(wxEVT_BUTTON, ([this, path](wxCommandEvent& e) {
    std::string extension = path.filename().extension().string();
    wxString wildcard;
    if (!extension.empty()) {
      extension = extension.substr(1);
      wxString wxext = boost::nowide::widen(extension);
      wildcard = GUI::format_wxstr("%1% Files (*.%2%)|*.%2%", wxext.Upper(), wxext);
    }
    boost::system::error_code ec;
    boost::filesystem::path dir = boost::filesystem::absolute(boost::filesystem::path(GUI::format(txtctrl_path->GetValue())), ec);
    if (ec)
      dir = GUI::format(txtctrl_path->GetValue());
    wxDirDialog save_dlg(
      this
      , _L("Select directory") + ":"
      , GUI::format_wxstr(dir.string())
      /*
      , filename //boost::nowide::widen(AppUpdater::get_filename_from_url(txtctrl_path->GetValue().ToUTF8().data()))
      , wildcard
      , wxFD_SAVE | wxFD_OVERWRITE_PROMPT*/
    );
    if (save_dlg.ShowModal() == wxID_OK) {
      txtctrl_path->SetValue(save_dlg.GetPath());
    }
  }));
  content_sizer->SetMinSize(AppUpdateAvailableDialog::AUAD_size);
  add_button(wxID_CANCEL);
  if (auto* btn_ok = get_button(wxID_OK); btn_ok != NULL) {
    btn_ok->SetLabel(_L("Download"));
    btn_ok->Bind(wxEVT_BUTTON, ([this, path](wxCommandEvent& e){
      boost::system::error_code ec;
      std::string input = GUI::into_u8(txtctrl_path->GetValue());
      boost::filesystem::path dir = boost::filesystem::absolute(boost::filesystem::path(input), ec);
      if (ec)
        dir = boost::filesystem::path(input);
      bool show_change = (dir.string() != input);
      boost::filesystem::path path = dir / GUI::format(filename);
      ec.clear();
      if (dir.string().empty()) {
        MessageDialog msgdlg(nullptr, _L("Directory path is empty."), _L("Notice"), wxOK);
        msgdlg.ShowModal();
        return;
      }
      ec.clear();
      if (!boost::filesystem::exists(dir, ec) || !boost::filesystem::is_directory(dir,ec) || ec) {
        ec.clear();
        if (!boost::filesystem::exists(dir.parent_path(), ec) || !boost::filesystem::is_directory(dir.parent_path(), ec) || ec) {
          MessageDialog msgdlg(nullptr, _L("Directory path is incorrect."), _L("Notice"), wxOK);
          msgdlg.ShowModal();
          return;
        }
        show_change = false;
        MessageDialog msgdlg(nullptr, GUI::format_wxstr(_L("Directory %1% doesn't exists. Do you wish to create it?"), dir.string()), _L("Notice"), wxYES_NO);
        if (msgdlg.ShowModal() != wxID_YES)
          return;
        ec.clear();
        if(!boost::filesystem::create_directory(dir, ec) || ec) {
          MessageDialog msgdlg(nullptr, _L("Failed to create directory."), _L("Notice"), wxOK);
          msgdlg.ShowModal();
          return;
        }
      }
      if (boost::filesystem::exists(path)) {
        show_change = false;
        MessageDialog msgdlg(nullptr, GUI::format_wxstr(_L("File %1% already exists. Do you wish to overwrite it?"), path.string()),_L("Notice"), wxYES_NO);
        if (msgdlg.ShowModal() != wxID_YES)
          return;
      }
      if (show_change) {
        MessageDialog msgdlg(nullptr, GUI::format_wxstr(_L("Download path is %1%. Do you wish to continue?"), path.string()), _L("Notice"), wxYES_NO);
        if (msgdlg.ShowModal() != wxID_YES)
          return;
      }
      this->EndModal(wxID_OK);
    }));
  }
  finalize();
}
References _, _L, Slic3r::GUI::MsgDialog::add_button(), Slic3r::GUI::AppUpdateAvailableDialog::AUAD_size, cbox_run, Slic3r::GUI::MsgDialog::content_sizer, filename, Slic3r::GUI::MsgDialog::finalize(), Slic3r::GUI::format(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::MsgDialog::get_button(), input(), Slic3r::GUI::into_u8(), L, Slic3r::Semver::to_string(), txtctrl_path, Slic3r::GUI::MsgDialog::VERT_SPACING, and wxEVT_BUTTON.
AppUpdateDownloadDialog() [2/3]
Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog (AppUpdateDownloadDialog &&) delete
AppUpdateDownloadDialog() [3/3]
Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog (const AppUpdateDownloadDialog &) delete
~AppUpdateDownloadDialog()
Slic3r::GUI::AppUpdateDownloadDialog::~AppUpdateDownloadDialog () virtual
{}
Member Function Documentation
add_button()
wxButton * Slic3r::GUI::MsgDialog::add_button (wxWindowID btn_id, bool set_focus = false, const wxString & label = wxString()) protected inherited
{
    wxButton* btn = new wxButton(this, btn_id, label);
    if (set_focus) {
        btn->SetFocus();
        // For non-MSW platforms SetFocus is not enought to use it as default, when the dialog is closed by ENTER
        // We have to set this button as the (permanently) default one in its dialog
        // See https://twitter.com/ZMelmed/status/1472678454168539146
        btn->SetDefault();
    }
    btn_sizer->Add(btn, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, HORIZ_SPACING);
    btn->Bind(wxEVT_BUTTON, [this, btn_id](wxCommandEvent&) { this->EndModal(btn_id); });
    return btn;
};
References Slic3r::GUI::MsgDialog::btn_sizer, Slic3r::GUI::MsgDialog::HORIZ_SPACING, and wxEVT_BUTTON.
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), AppUpdateDownloadDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::MsgDialog::apply_style().
apply_style()
void Slic3r::GUI::MsgDialog::apply_style (long style) protected inherited
{
    if (style & wxOK)       add_button(wxID_OK, true);
    if (style & wxYES)      add_button(wxID_YES,   !(style & wxNO_DEFAULT));
    if (style & wxNO)       add_button(wxID_NO,     (style & wxNO_DEFAULT));
    if (style & wxCANCEL)   add_button(wxID_CANCEL, (style & wxCANCEL_DEFAULT));
    std::string icon_name = style & wxICON_WARNING        ? "exclamation" :
                            style & wxICON_INFORMATION    ? "info"        :
                            style & wxICON_QUESTION       ? "question"    : "PrusaSlicer";
    logo->SetBitmap(*get_bmp_bundle(icon_name, 64));
}
References Slic3r::GUI::MsgDialog::add_button(), get_bmp_bundle(), Slic3r::GUI::MsgDialog::logo, and style.
Referenced by Slic3r::GUI::MsgDialog::MsgDialog().
finalize()
void Slic3r::GUI::MsgDialog::finalize () protected inherited
{
    wxGetApp().UpdateDlgDarkUI(this);
    Fit();
    this->CenterOnParent();
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
get_button()
wxButton * Slic3r::GUI::MsgDialog::get_button (wxWindowID btn_id) protected inherited
{
    return static_cast<wxButton*>(FindWindowById(btn_id, this));
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), AppUpdateDownloadDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), and Slic3r::GUI::MsgDialog::SetButtonLabel().
get_download_path()
boost::filesystem::path Slic3r::GUI::AppUpdateDownloadDialog::get_download_path () const
{
  boost::system::error_code ec;
  std::string input = GUI::into_u8(txtctrl_path->GetValue());
  boost::filesystem::path dir = boost::filesystem::absolute(boost::filesystem::path(input), ec);
  if (ec)
    dir = boost::filesystem::path(input);
  return dir / GUI::format(filename);
}
References filename, Slic3r::GUI::format(), input(), Slic3r::GUI::into_u8(), and txtctrl_path.
Referenced by Slic3r::GUI::GUI_App::app_updater().
operator=() [1/2]
AppUpdateDownloadDialog & Slic3r::GUI::AppUpdateDownloadDialog::operator= (AppUpdateDownloadDialog &&) delete
operator=() [2/2]
AppUpdateDownloadDialog & Slic3r::GUI::AppUpdateDownloadDialog::operator= (const AppUpdateDownloadDialog &) delete
run_after_download()
bool Slic3r::GUI::AppUpdateDownloadDialog::run_after_download () const
{
#ifndef __linux__
  return cbox_run->GetValue();
#endif
  return false;
}
References cbox_run.
Referenced by Slic3r::GUI::GUI_App::app_updater().
SetButtonLabel()
void Slic3r::GUI::MsgDialog::SetButtonLabel (wxWindowID btn_id, const wxString & label, bool set_focus = false) inherited
{
    if (wxButton* btn = get_button(btn_id)) {
        btn->SetLabel(label);
        if (set_focus)
            btn->SetFocus();
    }
}
References Slic3r::GUI::MsgDialog::get_button().
Referenced by Slic3r::GUI::GUI_App::check_older_app_config(), Slic3r::GUI::ObjectList::del_from_cut_object(), and Slic3r::GUI::Plater::priv::delete_object_from_model().
Member Data Documentation
boldfont
wxFont Slic3r::GUI::MsgDialog::boldfont protected inherited
Referenced by Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), and Slic3r::GUI::MsgUpdateForced::MsgUpdateForced().
btn_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::btn_sizer protected inherited
Referenced by Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::add_button().
cbox_run
wxCheckBox* Slic3r::GUI::AppUpdateDownloadDialog::cbox_run private
Referenced by AppUpdateDownloadDialog(), and run_after_download().
content_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::content_sizer protected inherited
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
filename
wxString Slic3r::GUI::AppUpdateDownloadDialog::filename private
Referenced by AppUpdateDownloadDialog(), and get_download_path().
logo
wxStaticBitmap* Slic3r::GUI::MsgDialog::logo protected inherited
Referenced by Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::apply_style().
txtctrl_path
wxTextCtrl* Slic3r::GUI::AppUpdateDownloadDialog::txtctrl_path private
Referenced by AppUpdateDownloadDialog(), and get_download_path().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UpdateDialogs.hpp
src/slic3r/GUI/UpdateDialogs.cpp