Prusa Slicer: Slic3r::RetractWhenCrossingPerimeters Class Reference
Slic3r::RetractWhenCrossingPerimeters Class Reference
#include <src/libslic3r/GCode/RetractWhenCrossingPerimeters.hpp>
Public Member Functions
bool travel_inside_internal_regions (const Layer &layer, const Polyline &travel)
Private Types
using AABBTree = AABBTreeIndirect::Tree< 2, coord_t >
Private Attributes
const Layer * m_layer
std::vector< const ExPolygon * > m_internal_islands
AABBTree m_aabbtree_internal_islands
Detailed Description
Member Typedef Documentation
AABBTree
using Slic3r::RetractWhenCrossingPerimeters::AABBTree = AABBTreeIndirect::Tree<2, coord_t> private
Member Function Documentation
travel_inside_internal_regions()
bool Slic3r::RetractWhenCrossingPerimeters::travel_inside_internal_regions (const Layer & layer, const Polyline & travel)
{
    if (m_layer != &layer) {
        // Update cache.
        m_layer = &layer;
        m_internal_islands.clear();
        m_aabbtree_internal_islands.clear();
        // Collect expolygons of internal slices.
        for (const LayerRegion *layerm : layer.regions())
            for (const Surface &surface : layerm->slices().surfaces)
                if (surface.is_internal())
                    m_internal_islands.emplace_back(&surface.expolygon);
        // Calculate bounding boxes of internal slices.
        std::vector<AABBTreeIndirect::BoundingBoxWrapper> bboxes;
        bboxes.reserve(m_internal_islands.size());
        for (size_t i = 0; i < m_internal_islands.size(); ++ i)
            bboxes.emplace_back(i, get_extents(*m_internal_islands[i]));
        // Build AABB tree over bounding boxes of internal slices.
        m_aabbtree_internal_islands.build_modify_input(bboxes);
    }
    BoundingBox           bbox_travel = get_extents(travel);
    AABBTree::BoundingBox bbox_travel_eigen{ bbox_travel.min, bbox_travel.max };
    int result = -1;
    bbox_travel.offset(SCALED_EPSILON);
    AABBTreeIndirect::traverse(m_aabbtree_internal_islands,
        [&bbox_travel_eigen](const AABBTree::Node &node) {
            return bbox_travel_eigen.intersects(node.bbox);
        },
        [&travel, &bbox_travel, &result, &islands = m_internal_islands](const AABBTree::Node &node) {
            assert(node.is_leaf());
            assert(node.is_valid());
            Polygons clipped = ClipperUtils::clip_clipper_polygons_with_subject_bbox(*islands[node.idx], bbox_travel);
            if (diff_pl(travel, clipped).empty()) {
                // Travel path is completely inside an "internal" island. Don't retract.
                result = int(node.idx);
                // Stop traversal.
                return false;
            }
            // Continue traversal.
            return true;
        });
    return result != -1;
}
References Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::build_modify_input(), Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::clear(), Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox(), Slic3r::diff_pl(), Slic3r::empty(), Slic3r::get_extents(), m_aabbtree_internal_islands, m_internal_islands, m_layer, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::BoundingBoxBase< PointType, APointsType >::offset(), Slic3r::Layer::regions(), SCALED_EPSILON, and Slic3r::AABBTreeIndirect::traverse().
Referenced by Slic3r::GCode::needs_retraction().
Member Data Documentation
m_aabbtree_internal_islands
AABBTree Slic3r::RetractWhenCrossingPerimeters::m_aabbtree_internal_islands private
Referenced by travel_inside_internal_regions().
m_internal_islands
std::vector<const ExPolygon*> Slic3r::RetractWhenCrossingPerimeters::m_internal_islands private
Referenced by travel_inside_internal_regions().
m_layer
const Layer* Slic3r::RetractWhenCrossingPerimeters::m_layer private
Referenced by travel_inside_internal_regions().
The documentation for this class was generated from the following files:
src/libslic3r/GCode/RetractWhenCrossingPerimeters.hpp
src/libslic3r/GCode/RetractWhenCrossingPerimeters.cpp