Prusa Slicer: Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape > Struct Template Reference
Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape > Struct Template Reference
#include <src/eigen/Eigen/src/Core/ProductEvaluators.h>
Public Types
enum { StorageOrder = int(Lhs::Flags) & RowMajorBit ? RowMajor : ColMajor }
typedef diagonal_product_evaluator_base< Lhs, typename Rhs::DiagonalVectorType, Product< Lhs, Rhs, LazyProduct >, OnTheRight > Base
typedef Base::Scalar Scalar
typedef Product< Lhs, Rhs, ProductKind > XprType
typedef XprType::PlainObject PlainObject
enum
enum { Alignment = 0 }
typedef traits< ExpressionType > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC product_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index idx) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar coeff (Index idx) const
Public Attributes
evaluator< DiagonalType > m_diagImpl
evaluator< MatrixType > m_matImpl
Protected Member Functions
EIGEN_STRONG_INLINE PacketType packet_impl (Index row, Index col, Index id, internal::true_type) const
EIGEN_STRONG_INLINE PacketType packet_impl (Index row, Index col, Index id, internal::false_type) const
Detailed Description
template<typename Lhs, typename Rhs, int ProductKind, int ProductTag>
struct Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >
Member Typedef Documentation
Base
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef diagonal_product_evaluator_base<Lhs, typename Rhs::DiagonalVectorType, Product<Lhs, Rhs, LazyProduct>, OnTheRight> Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::Base
ExpressionTraits
template<typename ExpressionType > typedef traits<ExpressionType> Eigen::internal::evaluator_base< ExpressionType >::ExpressionTraits inherited
PlainObject
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef XprType::PlainObject Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::PlainObject
Scalar
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef Base::Scalar Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::Scalar
XprType
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> typedef Product<Lhs, Rhs, ProductKind> Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ExpressionType > anonymous enum inherited
Enumerator
Alignment
       {
    Alignment = 0
  };
anonymous enum
anonymous enum inherited
       {
    CoeffReadCost = NumTraits<Scalar>::MulCost + evaluator<MatrixType>::CoeffReadCost + evaluator<DiagonalType>::CoeffReadCost,
    MatrixFlags = evaluator<MatrixType>::Flags,
    DiagFlags = evaluator<DiagonalType>::Flags,
    _StorageOrder = MatrixFlags & RowMajorBit ? RowMajor : ColMajor,
    _ScalarAccessOnDiag =  !((int(_StorageOrder) == ColMajor && int(ProductOrder) == OnTheLeft)
                           ||(int(_StorageOrder) == RowMajor && int(ProductOrder) == OnTheRight)),
    _SameTypes = is_same<typename MatrixType::Scalar, typename DiagonalType::Scalar>::value,
    // FIXME currently we need same types, but in the future the next rule should be the one
    //_Vectorizable = bool(int(MatrixFlags)&PacketAccessBit) && ((!_PacketOnDiag) || (_SameTypes && bool(int(DiagFlags)&PacketAccessBit))),
    _Vectorizable = bool(int(MatrixFlags)&PacketAccessBit) && _SameTypes && (_ScalarAccessOnDiag || (bool(int(DiagFlags)&PacketAccessBit))),
    _LinearAccessMask = (MatrixType::RowsAtCompileTime==1 || MatrixType::ColsAtCompileTime==1) ? LinearAccessBit : 0,
    Flags = ((HereditaryBits|_LinearAccessMask) & (unsigned int)(MatrixFlags)) | (_Vectorizable ? PacketAccessBit : 0),
    Alignment = evaluator<MatrixType>::Alignment,
    AsScalarProduct =     (DiagonalType::SizeAtCompileTime==1)
                      ||  (DiagonalType::SizeAtCompileTime==Dynamic && MatrixType::RowsAtCompileTime==1 && ProductOrder==OnTheLeft)
                      ||  (DiagonalType::SizeAtCompileTime==Dynamic && MatrixType::ColsAtCompileTime==1 && ProductOrder==OnTheRight)
  };
anonymous enum
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> anonymous enum
Enumerator
StorageOrder
{ StorageOrder = int(Lhs::Flags) & RowMajorBit ? RowMajor : ColMajor };
Constructor & Destructor Documentation
product_evaluator()
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::product_evaluator (const XprType & xpr) inline explicit
    : Base(xpr.lhs(), xpr.rhs().diagonal())
  {
  }
Member Function Documentation
coeff() [1/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::coeff (Index idx) const inline
  {
    if(AsScalarProduct)
      return m_diagImpl.coeff(0) * m_matImpl.coeff(idx);
    else
      return m_diagImpl.coeff(idx) * m_matImpl.coeff(idx);
  }
coeff() [2/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::coeff (Index row, Index col) const inline
  {
    return m_matImpl.coeff(row, col) * m_diagImpl.coeff(col);
  }
References col(), and row().
packet() [1/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet (Index idx) const inline
  {
    return packet<LoadMode,PacketType>(int(StorageOrder)==ColMajor?idx:0,int(StorageOrder)==ColMajor?0:idx);
  }
References Eigen::ColMajor.
packet() [2/2]
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet (Index row, Index col) const inline
  {
    return this->template packet_impl<LoadMode,PacketType>(row,col, col,
                                 typename internal::conditional<int(StorageOrder)==ColMajor, internal::true_type, internal::false_type>::type());
  }
References col(), Eigen::ColMajor, and row().
packet_impl() [1/2]
EIGEN_STRONG_INLINE PacketType Eigen::internal::diagonal_product_evaluator_base< Lhs , Rhs::DiagonalVectorType , Product< Lhs, Rhs, LazyProduct > , ProductOrder >::packet_impl (Index row, Index col, Index id, internal::false_type) const inline protected inherited
  {
    enum {
      InnerSize = (MatrixType::Flags & RowMajorBit) ? MatrixType::ColsAtCompileTime : MatrixType::RowsAtCompileTime,
      DiagonalPacketLoadMode = EIGEN_PLAIN_ENUM_MIN(LoadMode,((InnerSize%16) == 0) ? int(Aligned16) : int(evaluator<DiagonalType>::Alignment)) // FIXME hardcoded 16!!
    };
    return internal::pmul(m_matImpl.template packet<LoadMode,PacketType>(row, col),
                          m_diagImpl.template packet<DiagonalPacketLoadMode,PacketType>(id));
  }
packet_impl() [2/2]
EIGEN_STRONG_INLINE PacketType Eigen::internal::diagonal_product_evaluator_base< Lhs , Rhs::DiagonalVectorType , Product< Lhs, Rhs, LazyProduct > , ProductOrder >::packet_impl (Index row, Index col, Index id, internal::true_type) const inline protected inherited
  {
    return internal::pmul(m_matImpl.template packet<LoadMode,PacketType>(row, col),
                          internal::pset1<PacketType>(m_diagImpl.coeff(id)));
  }
Member Data Documentation
m_diagImpl
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> evaluator<DiagonalType> Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::m_diagImpl
m_matImpl
template<typename Lhs , typename Rhs , int ProductKind, int ProductTag> evaluator<MatrixType> Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::m_matImpl
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/ProductEvaluators.h