Prusa Slicer: Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs > Struct Template Reference
Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs > Struct Template Reference
#include <src/eigen/Eigen/src/Core/util/BlasUtil.h>
Public Types
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType Scalar
Public Member Functions
EIGEN_STRONG_INLINE Scalar pmadd (const LhsScalar &x, const RhsScalar &y, const Scalar &c) const
EIGEN_STRONG_INLINE Scalar pmul (const LhsScalar &x, const RhsScalar &y) const
Detailed Description
template<typename LhsScalar, typename RhsScalar, bool ConjLhs, bool ConjRhs>
struct Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >
Member Typedef Documentation
Scalar
template<typename LhsScalar , typename RhsScalar , bool ConjLhs, bool ConjRhs> typedef ScalarBinaryOpTraits<LhsScalar,RhsScalar>::ReturnType Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::Scalar
Member Function Documentation
pmadd()
template<typename LhsScalar , typename RhsScalar , bool ConjLhs, bool ConjRhs> EIGEN_STRONG_INLINE Scalar Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmadd (const LhsScalar & x, const RhsScalar & y, const Scalar & c) const inline
  { return padd(c, pmul(x,y)); }
References Eigen::internal::padd(), Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmul(), and Eigen::internal::y.
Referenced by Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), and Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run().
pmul()
template<typename LhsScalar , typename RhsScalar , bool ConjLhs, bool ConjRhs> EIGEN_STRONG_INLINE Scalar Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmul (const LhsScalar & x, const RhsScalar & y) const inline
  { return conj_if<ConjLhs>()(x) *  conj_if<ConjRhs>()(y); }
References Eigen::internal::y.
Referenced by Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::pdiv< Packet1cd >(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, true >::pmadd(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, false, true >::pmadd(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cd, Packet2cd, true, true >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, false, true >::pmadd(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, false >::pmadd(), Eigen::internal::conj_helper< Packet4cf, Packet4cf, true, true >::pmadd(), Eigen::internal::conj_helper< RealScalar, std::complex< RealScalar >, false, Conj >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, RealScalar, Conj, false >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >::pmadd(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), and Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/util/BlasUtil.h