Prusa Slicer: Slic3r::GUI::PlaterPresetComboBox Class Reference
Slic3r::GUI::PlaterPresetComboBox Class Reference
#include <src/slic3r/GUI/PresetComboBoxes.hpp>
Public Types
enum LabelItemType {
LABEL_ITEM_PHYSICAL_PRINTER = 0xffffff01 , LABEL_ITEM_DISABLED , LABEL_ITEM_MARKER , LABEL_ITEM_PHYSICAL_PRINTERS ,
LABEL_ITEM_WIZARD_PRINTERS , LABEL_ITEM_WIZARD_FILAMENTS , LABEL_ITEM_WIZARD_MATERIALS , LABEL_ITEM_MAX
}
Public Member Functions
PlaterPresetComboBox (wxWindow *parent, Preset::Type preset_type)
~PlaterPresetComboBox ()
void set_extruder_idx (const int extr_idx)
int get_extruder_idx () const
void switch_to_tab ()
void change_extruder_color ()
void show_add_menu ()
void show_edit_menu ()
wxString get_preset_name (const Preset &preset) override
void update () override
void msw_rescale () override
void sys_color_changed () override
void OnSelect (wxCommandEvent &evt) override
std::string get_selected_ph_printer_name () const
void set_label_marker (int item, LabelItemType label_item_type=LABEL_ITEM_MARKER)
bool set_printer_technology (PrinterTechnology pt)
void set_selection_changed_function (std::function< void(int)> sel_changed)
bool is_selected_physical_printer ()
bool selection_is_changed_according_to_physical_printers ()
void update (std::string select_preset)
void update_from_bundle ()
void edit_physical_printer ()
void add_physical_printer ()
void open_physical_printer_url ()
bool del_physical_printer (const wxString &note_string=wxEmptyString)
void show_modif_preset_separately ()
Preset::Type get_type ()
void show_all (bool show_all)
int Append (const wxString &item, const wxBitmapBundle &bitmap)
Public Attributes
ScalableButton * edit_btn { nullptr }
Protected Types
typedef std::size_t Marker
Protected Member Functions
void invalidate_selection ()
void validate_selection (bool predicate=false)
void update_selection ()
wxBitmapBundle * get_bmp (std::string bitmap_key, bool wide_icons, const std::string &main_icon_name, bool is_compatible=true, bool is_system=false, bool is_single_bar=false, const std::string &filament_rgb="", const std::string &extruder_rgb="", const std::string &material_rgb="")
wxBitmapBundle * get_bmp (std::string bitmap_key, const std::string &main_icon_name, const std::string &next_icon_name, bool is_enabled=true, bool is_compatible=true, bool is_system=false)
wxBitmapBundle NullBitmapBndl ()
Static Protected Member Functions
static BitmapCache & bitmap_cache ()
static const char * separator_head ()
static const char * separator_tail ()
static wxString separator (const std::string &label)
Protected Attributes
std::function< void(int)> on_selection_changed { nullptr }
Preset::Type m_type
std::string m_main_bitmap_name
PresetBundle * m_preset_bundle {nullptr}
PresetCollection * m_collection {nullptr}
wxBitmapBundle * m_bitmapCompatible
wxBitmapBundle * m_bitmapIncompatible
int m_last_selected
int m_em_unit
bool m_suppress_change { true }
int icon_height
int norm_icon_width
int null_icon_width
int thin_icon_width
int wide_icon_width
int space_icon_width
int thin_space_icon_width
int wide_space_icon_width
PrinterTechnology printer_technology {ptAny}
Private Member Functions
void fill_width_height ()
Private Attributes
int m_extruder_idx = -1
bool m_show_all { false }
bool m_show_modif_preset_separately { false }
Detailed Description
Member Typedef Documentation
Marker
typedef std::size_t Slic3r::GUI::PresetComboBox::Marker protected inherited
Member Enumeration Documentation
LabelItemType
enum Slic3r::GUI::PresetComboBox::LabelItemType inherited
Enumerator
LABEL_ITEM_PHYSICAL_PRINTER
LABEL_ITEM_DISABLED
LABEL_ITEM_MARKER
LABEL_ITEM_PHYSICAL_PRINTERS
LABEL_ITEM_WIZARD_PRINTERS
LABEL_ITEM_WIZARD_FILAMENTS
LABEL_ITEM_WIZARD_MATERIALS
LABEL_ITEM_MAX
                     {
    LABEL_ITEM_PHYSICAL_PRINTER = 0xffffff01,
    LABEL_ITEM_DISABLED,
    LABEL_ITEM_MARKER,
    LABEL_ITEM_PHYSICAL_PRINTERS,
    LABEL_ITEM_WIZARD_PRINTERS,
        LABEL_ITEM_WIZARD_FILAMENTS,
        LABEL_ITEM_WIZARD_MATERIALS,
        LABEL_ITEM_MAX,
  };
Constructor & Destructor Documentation
PlaterPresetComboBox()
Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox (wxWindow * parent, Preset::Type preset_type)
                                                                                   :
    PresetComboBox(parent, preset_type, wxSize(15 * wxGetApp().em_unit(), -1))
{
    if (m_type == Preset::TYPE_FILAMENT)
    {
        Bind(wxEVT_LEFT_DOWN, [this](wxMouseEvent &event) {
            const Filament* selected_filament = m_preset_bundle->extruders_filaments[m_extruder_idx].get_selected_filament();
            // Wide icons are shown if the currently selected preset is not compatible with the current printer,
            // and red flag is drown in front of the selected preset.
            const bool wide_icons = selected_filament && !selected_filament->is_compatible;
            float scale = m_em_unit*0.1f;
            int shifl_Left = wide_icons ? int(scale * 16 + 0.5) : 0;
#if defined(wxBITMAPCOMBOBOX_OWNERDRAWN_BASED)
            shifl_Left  += int(scale * 4 + 0.5f); // IMAGE_SPACING_RIGHT = 4 for wxBitmapComboBox -> Space left of image
#endif
            int icon_right_pos = shifl_Left + int(scale * (24+4) + 0.5);
            int mouse_pos = event.GetLogicalPosition(wxClientDC(this)).x;
            if (mouse_pos < shifl_Left || mouse_pos > icon_right_pos ) {
                // Let the combo box process the mouse click.
                event.Skip();
                return;
            }
            // Swallow the mouse click and open the color picker.
            change_extruder_color();
        });
    }
    edit_btn = new ScalableButton(parent, wxID_ANY, "cog");
    edit_btn->SetToolTip(_L("Click to edit preset"));
    edit_btn->Bind(wxEVT_BUTTON, [this](wxCommandEvent)
    {
        if (m_type == Preset::TYPE_PRINTER || m_type == Preset::TYPE_FILAMENT)
            show_edit_menu();
        else
            switch_to_tab();
    });
}
References _L, change_extruder_color(), edit_btn, Slic3r::PresetBundle::extruders_filaments, Slic3r::Filament::is_compatible, Slic3r::GUI::PresetComboBox::m_em_unit, m_extruder_idx, Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, scale(), show_edit_menu(), switch_to_tab(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINTER, and wxEVT_BUTTON.
~PlaterPresetComboBox()
Slic3r::GUI::PlaterPresetComboBox::~PlaterPresetComboBox ()
{
    if (edit_btn)
        edit_btn->Destroy();
}
References edit_btn.
Member Function Documentation
add_physical_printer()
void Slic3r::GUI::PresetComboBox::add_physical_printer () inherited
{
    if (PhysicalPrinterDialog(this->GetParent(), wxEmptyString).ShowModal() == wxID_OK)
        update();
}
References Slic3r::GUI::PresetComboBox::update().
Referenced by show_edit_menu().
Append()
int Slic3r::GUI::BitmapComboBox::Append (const wxString & item, const wxBitmapBundle & bitmap) inline inherited
    {
        return wxBitmapComboBox::Append(item, bitmap);
    }
Referenced by Slic3r::GUI::ModePaletteComboBox::ModePaletteComboBox(), BitmapChoiceRenderer::CreateEditorCtrl(), update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
bitmap_cache()
BitmapCache & Slic3r::GUI::PresetComboBox::bitmap_cache () static protected inherited
{
    static BitmapCache bmps;
    return bmps;
}
Referenced by Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::get_bmp().
change_extruder_color()
void Slic3r::GUI::PlaterPresetComboBox::change_extruder_color ()
{
    // get current color
    DynamicPrintConfig* cfg = wxGetApp().get_tab(Preset::TYPE_PRINTER)->get_config();
    auto colors = static_cast<ConfigOptionStrings*>(cfg->option("extruder_colour")->clone());
    wxColour clr(colors->values[m_extruder_idx]);
    if (!clr.IsOk())
        clr = wxColour(0, 0, 0); // Don't set alfa to transparence
    auto data = new wxColourData();
    data->SetChooseFull(1);
    data->SetColour(clr);
    wxColourDialog dialog(this, data);
    dialog.CenterOnParent();
    if (dialog.ShowModal() == wxID_OK)
    {
        colors->values[m_extruder_idx] = dialog.GetColourData().GetColour().GetAsString(wxC2S_HTML_SYNTAX).ToStdString();
        DynamicPrintConfig cfg_new = *cfg;
        cfg_new.set_key_value("extruder_colour", colors);
        wxGetApp().get_tab(Preset::TYPE_PRINTER)->load_config(cfg_new);
        this->update();
        wxGetApp().plater()->on_config_change(cfg_new);
    }
}
References Slic3r::ConfigOption::clone(), m_extruder_idx, Slic3r::ConfigBase::option(), Slic3r::DynamicConfig::set_key_value(), Slic3r::Preset::TYPE_PRINTER, and update().
Referenced by PlaterPresetComboBox(), and show_edit_menu().
del_physical_printer()
bool Slic3r::GUI::PresetComboBox::del_physical_printer (const wxString & note_string = wxEmptyString) inherited
{
    const std::string& printer_name = m_preset_bundle->physical_printers.get_selected_full_printer_name();
    if (printer_name.empty())
        return false;
    wxString msg;
    if (!note_string.IsEmpty())
        msg += note_string + "\n";
    msg += format_wxstr(_L("Are you sure you want to delete \"%1%\" printer?"), printer_name);
    if (MessageDialog(this, msg, _L("Delete Physical Printer"), wxYES_NO | wxNO_DEFAULT | wxICON_QUESTION).ShowModal() != wxID_YES)
        return false;
    m_preset_bundle->physical_printers.delete_selected_printer();
    this->update();
    if (dynamic_cast<PlaterPresetComboBox*>(this) != nullptr)
        wxGetApp().get_tab(m_type)->update_preset_choice();
    else if (dynamic_cast<TabPresetComboBox*>(this) != nullptr)
    {
        wxGetApp().get_tab(m_type)->update_btns_enabling();
        wxGetApp().plater()->sidebar().update_presets(m_type);
    }
    return true;
}
References _L, Slic3r::PhysicalPrinterCollection::delete_selected_printer(), Slic3r::GUI::format_wxstr(), Slic3r::PhysicalPrinterCollection::get_selected_full_printer_name(), Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::PresetBundle::physical_printers, and Slic3r::GUI::PresetComboBox::update().
Referenced by show_edit_menu().
edit_physical_printer()
void Slic3r::GUI::PresetComboBox::edit_physical_printer () inherited
{
    if (!m_preset_bundle->physical_printers.has_selection())
        return;
    PhysicalPrinterDialog dlg(this->GetParent(),this->GetString(this->GetSelection()));
    if (dlg.ShowModal() == wxID_OK)
        update();
}
References Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::PresetBundle::physical_printers, and Slic3r::GUI::PresetComboBox::update().
Referenced by show_edit_menu().
fill_width_height()
void Slic3r::GUI::PresetComboBox::fill_width_height () private inherited
{
    icon_height     = 16;
    norm_icon_width = 16;
    thin_icon_width = 8;
    wide_icon_width = norm_icon_width + thin_icon_width;
    null_icon_width = 2 * norm_icon_width;
    space_icon_width      = 2;
    thin_space_icon_width = 4;
    wide_space_icon_width = 6;
}
References Slic3r::GUI::PresetComboBox::icon_height, Slic3r::GUI::PresetComboBox::norm_icon_width, Slic3r::GUI::PresetComboBox::null_icon_width, Slic3r::GUI::PresetComboBox::space_icon_width, Slic3r::GUI::PresetComboBox::thin_icon_width, Slic3r::GUI::PresetComboBox::thin_space_icon_width, Slic3r::GUI::PresetComboBox::wide_icon_width, and Slic3r::GUI::PresetComboBox::wide_space_icon_width.
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox().
get_bmp() [1/2]
wxBitmapBundle * Slic3r::GUI::PresetComboBox::get_bmp (std::string bitmap_key, bool wide_icons, const std::string & main_icon_name, bool is_compatible = true, bool is_system = false, bool is_single_bar = false, const std::string & filament_rgb = "", const std::string & extruder_rgb = "", const std::string & material_rgb = "") protected inherited
{
    // If the filament preset is not compatible and there is a "red flag" icon loaded, show it left
    // to the filament color image.
    if (wide_icons)
        bitmap_key += is_compatible ? ",cmpt" : ",ncmpt";
    bitmap_key += is_system ? ",syst" : ",nsyst";
    bitmap_key += ",h" + std::to_string(icon_height);
    bool dark_mode = wxGetApp().dark_mode();
    if (dark_mode)
        bitmap_key += ",dark";
    bitmap_key += material_rgb;
    wxBitmapBundle* bmp_bndl = bitmap_cache().find_bndl(bitmap_key);
    if (bmp_bndl == nullptr) {
        // Create the bitmap with color bars.
        std::vector<wxBitmapBundle*> bmps;
        if (wide_icons)
            // Paint a red flag for incompatible presets.
            bmps.emplace_back(is_compatible ? get_empty_bmp_bundle(norm_icon_width, icon_height) : m_bitmapIncompatible);
        if (m_type == Preset::TYPE_FILAMENT && !filament_rgb.empty()) {
            // Paint the color bars.
            bmps.emplace_back(get_solid_bmp_bundle(is_single_bar ? wide_icon_width : norm_icon_width, icon_height, filament_rgb));
            if (!is_single_bar)
                bmps.emplace_back(get_solid_bmp_bundle(thin_icon_width, icon_height, extruder_rgb));
            // Paint a lock at the system presets.
            bmps.emplace_back(get_empty_bmp_bundle(space_icon_width, icon_height));
        }
        else
        {
            // Paint the color bars.
            bmps.emplace_back(get_empty_bmp_bundle(thin_space_icon_width, icon_height));
            if (m_type == Preset::TYPE_SLA_MATERIAL)
                bmps.emplace_back(bitmap_cache().from_svg(main_icon_name, 16, 16, dark_mode, material_rgb));
            else
                bmps.emplace_back(get_bmp_bundle(main_icon_name));
            // Paint a lock at the system presets.
            bmps.emplace_back(get_empty_bmp_bundle(wide_space_icon_width, icon_height));
        }
        bmps.emplace_back(is_system ? get_bmp_bundle("lock_closed") : get_empty_bmp_bundle(norm_icon_width, icon_height));
        bmp_bndl = bitmap_cache().insert_bndl(bitmap_key, bmps);
    }
    return bmp_bndl;
}
References Slic3r::GUI::PresetComboBox::bitmap_cache(), Slic3r::GUI::BitmapCache::find_bndl(), Slic3r::GUI::BitmapCache::from_svg(), get_bmp_bundle(), get_empty_bmp_bundle(), get_solid_bmp_bundle(), Slic3r::GUI::PresetComboBox::icon_height, Slic3r::GUI::BitmapCache::insert_bndl(), Slic3r::GUI::PresetComboBox::m_bitmapIncompatible, Slic3r::GUI::PresetComboBox::m_type, Slic3r::GUI::PresetComboBox::norm_icon_width, Slic3r::GUI::PresetComboBox::space_icon_width, Slic3r::GUI::PresetComboBox::thin_icon_width, Slic3r::GUI::PresetComboBox::thin_space_icon_width, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::GUI::PresetComboBox::wide_icon_width, and Slic3r::GUI::PresetComboBox::wide_space_icon_width.
Referenced by update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
get_bmp() [2/2]
wxBitmapBundle * Slic3r::GUI::PresetComboBox::get_bmp (std::string bitmap_key, const std::string & main_icon_name, const std::string & next_icon_name, bool is_enabled = true, bool is_compatible = true, bool is_system = false) protected inherited
{
    bitmap_key += !is_enabled ? "_disabled" : "";
    bitmap_key += is_compatible ? ",cmpt" : ",ncmpt";
    bitmap_key += is_system ? ",syst" : ",nsyst";
    bitmap_key += ",h" + std::to_string(icon_height);
    if (wxGetApp().dark_mode())
        bitmap_key += ",dark";
    wxBitmapBundle* bmp = bitmap_cache().find_bndl(bitmap_key);
    if (bmp == nullptr) {
        // Create the bitmap with color bars.
        std::vector<wxBitmapBundle*> bmps;
        bmps.emplace_back(m_type == Preset::TYPE_PRINTER ? get_bmp_bundle(main_icon_name) :
                          is_compatible ? m_bitmapCompatible : m_bitmapIncompatible);
        // Paint a lock at the system presets.
        bmps.emplace_back(is_system ? get_bmp_bundle(next_icon_name) : get_empty_bmp_bundle(norm_icon_width, icon_height));
        bmp = bitmap_cache().insert_bndl(bitmap_key, bmps);
    }
    return bmp;
}
References Slic3r::GUI::PresetComboBox::bitmap_cache(), Slic3r::GUI::BitmapCache::find_bndl(), get_bmp_bundle(), get_empty_bmp_bundle(), Slic3r::GUI::PresetComboBox::icon_height, Slic3r::GUI::BitmapCache::insert_bndl(), Slic3r::GUI::PresetComboBox::m_bitmapCompatible, Slic3r::GUI::PresetComboBox::m_bitmapIncompatible, Slic3r::GUI::PresetComboBox::m_type, Slic3r::GUI::PresetComboBox::norm_icon_width, and Slic3r::Preset::TYPE_PRINTER.
get_extruder_idx()
int Slic3r::GUI::PlaterPresetComboBox::get_extruder_idx () const inline
{ return m_extruder_idx; }
References m_extruder_idx.
Referenced by Slic3r::GUI::Plater::priv::on_select_preset().
get_preset_name()
wxString Slic3r::GUI::PlaterPresetComboBox::get_preset_name (const Preset & preset) override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    std::string name = preset.alias.empty() ? preset.name : (preset.vendor && preset.vendor->templates_profile ? preset.name : preset.alias);
    return from_u8(name + suffix(preset));
}
References Slic3r::Preset::alias, Slic3r::GUI::from_u8(), Slic3r::Preset::name, Slic3r::GUI::suffix(), Slic3r::VendorProfile::templates_profile, and Slic3r::Preset::vendor.
Referenced by update().
get_selected_ph_printer_name()
std::string Slic3r::GUI::PlaterPresetComboBox::get_selected_ph_printer_name () const
{
    if (m_type != Preset::TYPE_PRINTER)
        return {};
    const PhysicalPrinterCollection& physical_printers = m_preset_bundle->physical_printers;
    if (physical_printers.has_selection())
        return physical_printers.get_selected_full_printer_name();
    return {};
}
References Slic3r::PhysicalPrinterCollection::get_selected_full_printer_name(), Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::PresetBundle::physical_printers, and Slic3r::Preset::TYPE_PRINTER.
Referenced by Slic3r::GUI::Plater::priv::on_select_preset().
get_type()
Preset::Type Slic3r::GUI::PresetComboBox::get_type () inline inherited
{ return m_type; }
References Slic3r::GUI::PresetComboBox::m_type.
Referenced by Slic3r::GUI::DiffPresetDialog::create_presets_sizer(), Slic3r::GUI::Plater::priv::on_select_preset(), and Slic3r::GUI::DiffPresetDialog::update_compatibility().
invalidate_selection()
void Slic3r::GUI::PresetComboBox::invalidate_selection () protected inherited
{
    m_last_selected = INT_MAX; // this value means that no one item is selected
}
References Slic3r::GUI::PresetComboBox::m_last_selected.
Referenced by update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
is_selected_physical_printer()
bool Slic3r::GUI::PresetComboBox::is_selected_physical_printer () inherited
{
    auto selected_item = this->GetSelection();
    auto marker = reinterpret_cast<Marker>(this->GetClientData(selected_item));
    return marker == LABEL_ITEM_PHYSICAL_PRINTER;
}
References Slic3r::GUI::PresetComboBox::LABEL_ITEM_PHYSICAL_PRINTER.
Referenced by Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), and show_edit_menu().
msw_rescale()
void Slic3r::GUI::PlaterPresetComboBox::msw_rescale () override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    PresetComboBox::msw_rescale();
#ifdef __WXMSW__
    // Use this part of code just on Windows to avoid of some layout issues on Linux
    // see https://github.com/prusa3d/PrusaSlicer/issues/5163 and https://github.com/prusa3d/PrusaSlicer/issues/5505
    // Update control min size after rescale (changed Display DPI under MSW)
    if (GetMinWidth() != 20 * m_em_unit)
        SetMinSize(wxSize(20 * m_em_unit, GetSize().GetHeight()));
#endif //__WXMSW__
}
References Slic3r::GUI::PresetComboBox::m_em_unit, and Slic3r::GUI::PresetComboBox::msw_rescale().
NullBitmapBndl()
wxBitmapBundle Slic3r::GUI::PresetComboBox::NullBitmapBndl () protected inherited
{
    assert(null_icon_width > 0);
    return *get_empty_bmp_bundle(null_icon_width, icon_height);
}
References get_empty_bmp_bundle(), Slic3r::GUI::PresetComboBox::icon_height, and Slic3r::GUI::PresetComboBox::null_icon_width.
Referenced by update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
OnSelect()
void Slic3r::GUI::PlaterPresetComboBox::OnSelect (wxCommandEvent & evt) override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    auto selected_item = evt.GetSelection();
    auto marker = reinterpret_cast<Marker>(this->GetClientData(selected_item));
    if (marker >= LABEL_ITEM_MARKER && marker < LABEL_ITEM_MAX) {
        this->SetSelection(m_last_selected);
        evt.StopPropagation();
        if (marker == LABEL_ITEM_MARKER)
            return;
        if (marker == LABEL_ITEM_WIZARD_PRINTERS)
            show_add_menu();
        else {
            ConfigWizard::StartPage sp = ConfigWizard::SP_WELCOME;
            switch (marker) {
            case LABEL_ITEM_WIZARD_FILAMENTS: sp = ConfigWizard::SP_FILAMENTS; break;
            case LABEL_ITEM_WIZARD_MATERIALS: sp = ConfigWizard::SP_MATERIALS; break;
            default: break;
            }
            wxTheApp->CallAfter([sp]() { run_wizard(sp); });
        }
        return;
    }
    else if (marker == LABEL_ITEM_PHYSICAL_PRINTER || m_last_selected != selected_item || m_collection->current_is_dirty())
        m_last_selected = selected_item;
    evt.Skip();
}
References Slic3r::PresetCollection::current_is_dirty(), Slic3r::GUI::PresetComboBox::LABEL_ITEM_MARKER, Slic3r::GUI::PresetComboBox::LABEL_ITEM_MAX, Slic3r::GUI::PresetComboBox::LABEL_ITEM_PHYSICAL_PRINTER, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_FILAMENTS, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_MATERIALS, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_PRINTERS, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_last_selected, Slic3r::GUI::run_wizard(), show_add_menu(), Slic3r::GUI::ConfigWizard::SP_FILAMENTS, Slic3r::GUI::ConfigWizard::SP_MATERIALS, and Slic3r::GUI::ConfigWizard::SP_WELCOME.
open_physical_printer_url()
void Slic3r::GUI::PresetComboBox::open_physical_printer_url () inherited
{
    const PhysicalPrinter& pp = m_preset_bundle->physical_printers.get_selected_printer();
    std::string host = pp.config.opt_string("print_host");
    assert(!host.empty());
    wxGetApp().open_browser_with_warning_dialog(host);
}
References Slic3r::PhysicalPrinter::config, Slic3r::PhysicalPrinterCollection::get_selected_printer(), Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::ConfigBase::opt_string(), and Slic3r::PresetBundle::physical_printers.
Referenced by show_edit_menu().
selection_is_changed_according_to_physical_printers()
bool Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers () inherited
{
    if (m_type != Preset::TYPE_PRINTER)
        return false;
    const std::string           selected_string     = into_u8(this->GetString(this->GetSelection()));
    PhysicalPrinterCollection&  physical_printers   = m_preset_bundle->physical_printers;
    Tab*                        tab                 = wxGetApp().get_tab(Preset::TYPE_PRINTER);
    if (!is_selected_physical_printer()) {
        if (!physical_printers.has_selection())
            return false;
        const bool is_changed = selected_string == physical_printers.get_selected_printer_preset_name();
        physical_printers.unselect_printer();
        if (is_changed)
            tab->select_preset(selected_string);
        return is_changed;
    }
    std::string old_printer_full_name, old_printer_preset;
    if (physical_printers.has_selection()) {
        old_printer_full_name = physical_printers.get_selected_full_printer_name();
        old_printer_preset = physical_printers.get_selected_printer_preset_name();
    }
    else
        old_printer_preset = m_collection->get_edited_preset().name;
    // Select related printer preset on the Printer Settings Tab
    physical_printers.select_printer(selected_string);
    std::string preset_name = physical_printers.get_selected_printer_preset_name();
    // if new preset wasn't selected, there is no need to call update preset selection
    if (old_printer_preset == preset_name) {
        tab->update_preset_choice();
        // update action buttons to show/hide "Send to" button
        wxGetApp().plater()->show_action_buttons();
        // we need just to update according Plater<->Tab PresetComboBox
        if (dynamic_cast<PlaterPresetComboBox*>(this)!=nullptr) {
            // Synchronize config.ini with the current selections.
            m_preset_bundle->export_selections(*wxGetApp().app_config);
            this->update();
        }
        else if (dynamic_cast<TabPresetComboBox*>(this)!=nullptr)
            wxGetApp().sidebar().update_presets(m_type);
        return true;
    }
    if (tab)
        tab->select_preset(preset_name, false, old_printer_full_name);
    return true;
}
References Slic3r::PresetBundle::export_selections(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PhysicalPrinterCollection::get_selected_full_printer_name(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::GUI::into_u8(), Slic3r::GUI::PresetComboBox::is_selected_physical_printer(), Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::Preset::name, Slic3r::PresetBundle::physical_printers, Slic3r::GUI::Tab::select_preset(), Slic3r::PhysicalPrinterCollection::select_printer(), Slic3r::Preset::TYPE_PRINTER, Slic3r::PhysicalPrinterCollection::unselect_printer(), Slic3r::GUI::PresetComboBox::update(), and Slic3r::GUI::Tab::update_preset_choice().
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Plater::priv::on_select_preset().
separator()
wxString Slic3r::GUI::PresetComboBox::separator (const std::string & label) static protected inherited
{
    return wxString::FromUTF8(separator_head()) + _(label) + wxString::FromUTF8(separator_tail());
}
References _, Slic3r::GUI::PresetComboBox::separator_head(), and Slic3r::GUI::PresetComboBox::separator_tail().
Referenced by update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
separator_head()
static const char * Slic3r::GUI::PresetComboBox::separator_head () inline static protected inherited
{ return " "; }
Referenced by Slic3r::GUI::PresetComboBox::separator().
separator_tail()
static const char * Slic3r::GUI::PresetComboBox::separator_tail () inline static protected inherited
{ return " "; }
Referenced by Slic3r::GUI::PresetComboBox::separator().
set_extruder_idx()
void Slic3r::GUI::PlaterPresetComboBox::set_extruder_idx (const int extr_idx) inline
{ m_extruder_idx = extr_idx; }
References m_extruder_idx.
set_label_marker()
void Slic3r::GUI::PresetComboBox::set_label_marker (int item, LabelItemType label_item_type = LABEL_ITEM_MARKER) inherited
{
    this->SetClientData(item, (void*)label_item_type);
}
Referenced by update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
set_printer_technology()
bool Slic3r::GUI::PresetComboBox::set_printer_technology (PrinterTechnology pt) inherited
{
    if (printer_technology != pt) {
        printer_technology = pt;
        return true;
    }
    return false;
}
References Slic3r::GUI::PresetComboBox::printer_technology.
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter(), Slic3r::GUI::PresetForPrinter::AllowDelete(), and Slic3r::GUI::PresetForPrinter::SuppressDelete().
set_selection_changed_function()
void Slic3r::GUI::PresetComboBox::set_selection_changed_function (std::function< void(int)> sel_changed) inline inherited
{ on_selection_changed = sel_changed; }
References Slic3r::GUI::PresetComboBox::on_selection_changed.
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter(), Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::DiffPresetDialog::create_presets_sizer().
show_add_menu()
void Slic3r::GUI::PlaterPresetComboBox::show_add_menu ()
{
    wxMenu* menu = new wxMenu();
    append_menu_item(menu, wxID_ANY, _L("Add/Remove presets"), "",
        [](wxCommandEvent&) {
            wxTheApp->CallAfter([]() { run_wizard(ConfigWizard::SP_PRINTERS); });
        }, "edit_uni", menu, []() { return true; }, wxGetApp().plater());
    append_menu_item(menu, wxID_ANY, _L("Add physical printer"), "",
        [this](wxCommandEvent&) {
            PhysicalPrinterDialog dlg(this->GetParent(), wxEmptyString);
            if (dlg.ShowModal() == wxID_OK)
                update();
        }, "edit_uni", menu, []() { return true; }, wxGetApp().plater());
    wxGetApp().plater()->PopupMenu(menu);
}
References _L, append_menu_item(), Slic3r::GUI::run_wizard(), Slic3r::GUI::ConfigWizard::SP_PRINTERS, and update().
Referenced by OnSelect().
show_all()
void Slic3r::GUI::PresetComboBox::show_all (bool show_all) inherited
{
    m_show_all = show_all;
    update();
}
References Slic3r::GUI::PresetComboBox::m_show_all, Slic3r::GUI::PresetComboBox::show_all(), and Slic3r::GUI::PresetComboBox::update().
Referenced by Slic3r::GUI::PresetComboBox::show_all().
show_edit_menu()
void Slic3r::GUI::PlaterPresetComboBox::show_edit_menu ()
{
    wxMenu* menu = new wxMenu();
    append_menu_item(menu, wxID_ANY, _L("Edit preset"), "",
        [this](wxCommandEvent&) { this->switch_to_tab(); }, "cog", menu, []() { return true; }, wxGetApp().plater());
    if (m_type == Preset::TYPE_FILAMENT) {
#ifdef __linux__
        // To edit extruder color from the sidebar
        append_menu_item(menu, wxID_ANY, _L("Change extruder color"), "",
            [this](wxCommandEvent&) { this->change_extruder_color(); }, "funnel", menu, []() { return true; }, wxGetApp().plater());
#endif //__linux__
        append_menu_item(menu, wxID_ANY, _L("Show/Hide template presets"), "",
            [this](wxCommandEvent&) { wxGetApp().open_preferences("no_templates", "General"); }, "spool", menu, []() { return true; }, wxGetApp().plater());
        wxGetApp().plater()->PopupMenu(menu);
        return;
    }
    if (this->is_selected_physical_printer()) {
        append_menu_item(menu, wxID_ANY, _L("Edit physical printer"), "",
            [this](wxCommandEvent&) { this->edit_physical_printer(); }, "cog", menu, []() { return true; }, wxGetApp().plater());
        const PhysicalPrinter& pp = m_preset_bundle->physical_printers.get_selected_printer();
        std::string host = pp.config.opt_string("print_host");
        if (!host.empty()) {
            append_menu_item(menu, wxID_ANY, _L("Open the physical printer URL"), "",
                [this](wxCommandEvent&) { this->open_physical_printer_url(); }, "open_browser", menu, []() { return true; }, wxGetApp().plater());
        }
        append_menu_item(menu, wxID_ANY, _L("Delete physical printer"), "",
            [this](wxCommandEvent&) { this->del_physical_printer(); }, "cross", menu, []() { return true; }, wxGetApp().plater());
    }
    else
        append_menu_item(menu, wxID_ANY, _L("Add/Remove presets"), "",
            [](wxCommandEvent&) {
                wxTheApp->CallAfter([]() { run_wizard(ConfigWizard::SP_PRINTERS); });
            }, "edit_uni", menu, []() { return true; }, wxGetApp().plater());
    append_menu_item(menu, wxID_ANY, _L("Add physical printer"), "",
        [this](wxCommandEvent&) { this->add_physical_printer(); }, "edit_uni", menu, []() { return true; }, wxGetApp().plater());
    wxGetApp().plater()->PopupMenu(menu);
}
References _L, Slic3r::GUI::PresetComboBox::add_physical_printer(), append_menu_item(), change_extruder_color(), Slic3r::PhysicalPrinter::config, Slic3r::GUI::PresetComboBox::del_physical_printer(), Slic3r::GUI::PresetComboBox::edit_physical_printer(), Slic3r::PhysicalPrinterCollection::get_selected_printer(), Slic3r::GUI::PresetComboBox::is_selected_physical_printer(), Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::GUI::PresetComboBox::open_physical_printer_url(), Slic3r::ConfigBase::opt_string(), Slic3r::PresetBundle::physical_printers, Slic3r::GUI::run_wizard(), Slic3r::GUI::ConfigWizard::SP_PRINTERS, switch_to_tab(), and Slic3r::Preset::TYPE_FILAMENT.
Referenced by PlaterPresetComboBox().
show_modif_preset_separately()
void Slic3r::GUI::PresetComboBox::show_modif_preset_separately () inline inherited
{ m_show_modif_preset_separately = true; }
References Slic3r::GUI::PresetComboBox::m_show_modif_preset_separately.
Referenced by Slic3r::GUI::DiffPresetDialog::create_presets_sizer().
switch_to_tab()
void Slic3r::GUI::PlaterPresetComboBox::switch_to_tab ()
{
    Tab* tab = wxGetApp().get_tab(m_type);
    if (!tab)
        return;
    if (int page_id = wxGetApp().tab_panel()->FindPage(tab); page_id != wxNOT_FOUND)
    {
        //In a case of a multi-material printing, for editing another Filament Preset
        //it's needed to select this preset for the "Filament settings" Tab
        if (m_type == Preset::TYPE_FILAMENT && wxGetApp().extruders_edited_cnt() > 1 &&
            !dynamic_cast<TabFilament*>(wxGetApp().get_tab(m_type))->set_active_extruder(m_extruder_idx))
            // do nothing, if we can't set new extruder and select new preset
            return;
        wxGetApp().tab_panel()->SetSelection(page_id);
        // Switch to Settings NotePad
        wxGetApp().mainframe->select_tab();
    }
}
References m_extruder_idx, Slic3r::GUI::PresetComboBox::m_type, and Slic3r::Preset::TYPE_FILAMENT.
Referenced by PlaterPresetComboBox(), and show_edit_menu().
sys_color_changed()
void Slic3r::GUI::PlaterPresetComboBox::sys_color_changed () override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    PresetComboBox::sys_color_changed();
    edit_btn->sys_color_changed();
}
References edit_btn, Slic3r::GUI::PresetComboBox::sys_color_changed(), and ScalableButton::sys_color_changed().
update() [1/2]
void Slic3r::GUI::PlaterPresetComboBox::update () override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    if (m_type == Preset::TYPE_FILAMENT &&
        (m_preset_bundle->printers.get_edited_preset().printer_technology() == ptSLA ||
        m_preset_bundle->extruders_filaments.size() <= (size_t)m_extruder_idx) )
        return;
    // Otherwise fill in the list from scratch.
    this->Freeze();
    this->Clear();
    invalidate_selection();
    const ExtruderFilaments& extruder_filaments  = m_preset_bundle->extruders_filaments[m_extruder_idx >= 0 ? m_extruder_idx : 0];
    const Preset* selected_filament_preset = nullptr;
    std::string extruder_color;
    if (m_type == Preset::TYPE_FILAMENT) {
        extruder_color = m_preset_bundle->printers.get_edited_preset().config.opt_string("extruder_colour", (unsigned int)m_extruder_idx);
        if (!can_decode_color(extruder_color))
            // Extruder color is not defined.
            extruder_color.clear();
        selected_filament_preset = extruder_filaments.get_selected_preset();
        if (selected_filament_preset->is_dirty)
            selected_filament_preset = &m_preset_bundle->filaments.get_edited_preset();
        assert(selected_filament_preset);
    }
    // Show wide icons if the currently selected preset is not compatible with the current printer,
    // and draw a red flag in front of the selected preset.
    bool wide_icons = m_type == Preset::TYPE_FILAMENT ?
                      extruder_filaments.get_selected_filament()     && !extruder_filaments.get_selected_filament()->is_compatible :
                      m_collection->get_selected_idx() != size_t(-1) && !m_collection->get_selected_preset().is_compatible;
    null_icon_width = (wide_icons ? 3 : 2) * norm_icon_width + thin_space_icon_width + wide_space_icon_width;
    struct PresetData {
        wxString        name;
        wxString        lower_name;
        wxBitmapBundle* bitmap;
    };
    std::vector<PresetData> system_presets;
    std::vector<PresetData>  nonsys_presets;
    std::vector<PresetData>  template_presets;
    const bool allow_templates = !wxGetApp().app_config->get_bool("no_templates");
    wxString selected_user_preset;
    wxString tooltip;
    const std::deque<Preset>& presets = m_collection->get_presets();
    if (!presets.front().is_visible)
        this->set_label_marker(this->Append(separator(L("System presets")), NullBitmapBndl()));
    for (size_t i = presets.front().is_visible ? 0 : m_collection->num_default_presets(); i < presets.size(); ++i)
    {
        const Preset& preset = presets[i];
        const bool is_selected =  m_type == Preset::TYPE_FILAMENT ?
                            selected_filament_preset->name == preset.name :
                            // The case, when some physical printer is selected
                            m_type == Preset::TYPE_PRINTER && m_preset_bundle->physical_printers.has_selection() ? false :
                            i == m_collection->get_selected_idx();
        const bool is_compatible = m_type == Preset::TYPE_FILAMENT ? extruder_filaments.filament(i).is_compatible : preset.is_compatible;
        if (!preset.is_visible || (!is_compatible && !is_selected))
            continue;
        std::string bitmap_key, filament_rgb, extruder_rgb, material_rgb;
        std::string bitmap_type_name = bitmap_key = m_type == Preset::TYPE_PRINTER && preset.printer_technology() == ptSLA ? "sla_printer" : m_main_bitmap_name;
        bool single_bar = false;
        if (m_type == Preset::TYPE_FILAMENT)
        {
            // Assign an extruder color to the selected item if the extruder color is defined.
            filament_rgb = is_selected ? selected_filament_preset->config.opt_string("filament_colour", 0) :
                                         preset.config.opt_string("filament_colour", 0);
            extruder_rgb = (is_selected && !extruder_color.empty()) ? extruder_color : filament_rgb;
            single_bar = filament_rgb == extruder_rgb;
            bitmap_key += single_bar ? filament_rgb : filament_rgb + extruder_rgb;
        }
        else if (m_type == Preset::TYPE_SLA_MATERIAL) {
            material_rgb = is_selected ? m_preset_bundle->sla_materials.get_edited_preset().config.opt_string("material_colour") : preset.config.opt_string("material_colour");
            if (material_rgb.empty())
                material_rgb = print_config_def.get("material_colour")->get_default_value<ConfigOptionString>()->value;
        }
        auto bmp = get_bmp(bitmap_key, wide_icons, bitmap_type_name,
                                is_compatible, preset.is_system || preset.is_default,
                                single_bar, filament_rgb, extruder_rgb, material_rgb);
        assert(bmp);
        const std::string name = preset.alias.empty() ? preset.name : preset.alias;
        if (preset.is_default || preset.is_system) {
            if (preset.vendor && preset.vendor->templates_profile) {
                if (allow_templates) {
                    template_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp});
                    if (is_selected) {
                        selected_user_preset = get_preset_name(preset);
                        tooltip = from_u8(preset.name);
                    }
                }
            } else {
                system_presets.push_back({ get_preset_name(preset), get_preset_name(preset).Lower(), bmp });
                if (is_selected) {
                    selected_user_preset = get_preset_name(preset);
                    tooltip = from_u8(preset.name);
                }
            }
        }
        else
        {
            nonsys_presets.push_back({ get_preset_name(preset), get_preset_name(preset).Lower(), bmp });
            if (is_selected) {
                selected_user_preset = get_preset_name(preset);
                tooltip = from_u8(preset.name);
            }
        }
        if (i + 1 == m_collection->num_default_presets())
            set_label_marker(Append(separator(L("System presets")), NullBitmapBndl()));
    }
    if(!system_presets.empty())
    {
        std::sort(system_presets.begin(), system_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        for (std::vector<PresetData>::iterator it = system_presets.begin(); it != system_presets.end(); ++it) {
            Append(it->name, *it->bitmap);
            validate_selection(it->name == selected_user_preset);
        }
    }
    if (!nonsys_presets.empty())
    {
        std::sort(nonsys_presets.begin(), nonsys_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        set_label_marker(Append(separator(L("User presets")), NullBitmapBndl()));
        for (std::vector<PresetData>::iterator it = nonsys_presets.begin(); it != nonsys_presets.end(); ++it) {
            Append(it->name, *it->bitmap);
            validate_selection(it->name == selected_user_preset);
        }
    }
    if (!template_presets.empty()) {
        std::sort(template_presets.begin(), template_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        set_label_marker(Append(separator(L("Template presets")), wxNullBitmap));
        for (std::vector<PresetData>::iterator it = template_presets.begin(); it != template_presets.end(); ++it) {
            Append(it->name, *it->bitmap);
            validate_selection(it->name == selected_user_preset);
        }
    }
    if (m_type == Preset::TYPE_PRINTER)
    {
        // add Physical printers, if any exists
        if (!m_preset_bundle->physical_printers.empty()) {
            set_label_marker(Append(separator(L("Physical printers")), NullBitmapBndl()));
            const PhysicalPrinterCollection& ph_printers = m_preset_bundle->physical_printers;
            // Sort Physical printers in preset_data vector and than Append it in correct order
            struct PhysicalPrinterPresetData
            {
                wxString lower_name; // just for sorting
                std::string name; // preset_name
                std::string fullname; // full name
                bool selected; // is selected
            };
            std::vector<PhysicalPrinterPresetData> preset_data;
            for (PhysicalPrinterCollection::ConstIterator it = ph_printers.begin(); it != ph_printers.end(); ++it) {
                for (const std::string& preset_name : it->get_preset_names()) {
                    preset_data.push_back({ wxString::FromUTF8(it->get_full_name(preset_name)).Lower(), preset_name, it->get_full_name(preset_name), ph_printers.is_selected(it, preset_name) });
                }
            }
            std::sort(preset_data.begin(), preset_data.end(), [](const PhysicalPrinterPresetData& a, const PhysicalPrinterPresetData& b) {
                return a.lower_name < b.lower_name;
                });
            for (const PhysicalPrinterPresetData& data : preset_data)
            {
                Preset* preset = m_collection->find_preset(data.name);
                if (!preset || !preset->is_visible)
                    continue;
                std::string main_icon_name = preset->printer_technology() == ptSLA ? "sla_printer" : m_main_bitmap_name;
                auto bmp = get_bmp(main_icon_name, main_icon_name, "", true, true, false);
                assert(bmp);
                set_label_marker(Append(from_u8(data.fullname + suffix(preset)), *bmp), LABEL_ITEM_PHYSICAL_PRINTER);
                validate_selection(data.selected);
            }
        }
    }
    if (m_type == Preset::TYPE_PRINTER || m_type == Preset::TYPE_FILAMENT || m_type == Preset::TYPE_SLA_MATERIAL) {
        auto bmp = get_bmp("edit_preset_list", wide_icons, "edit_uni");
        assert(bmp);
        if (m_type == Preset::TYPE_FILAMENT)
            set_label_marker(Append(separator(L("Add/Remove filaments")), *bmp), LABEL_ITEM_WIZARD_FILAMENTS);
        else if (m_type == Preset::TYPE_SLA_MATERIAL)
            set_label_marker(Append(separator(L("Add/Remove materials")), *bmp), LABEL_ITEM_WIZARD_MATERIALS);
        else
            set_label_marker(Append(separator(L("Add/Remove printers")), *bmp), LABEL_ITEM_WIZARD_PRINTERS);
    }
    update_selection();
    Thaw();
    if (!tooltip.IsEmpty()) {
#ifdef __WXMSW__
        // From the Windows 2004 the tooltip for preset combobox doesn't work after next call of SetTooltip()
        // (There was an issue, when tooltip doesn't appears after changing of the preset selection)
        // But this workaround seems to work: We should to kill tooltip and than set new tooltip value
        // See, https://groups.google.com/g/wx-users/c/mOEe3fgHrzk
        SetToolTip(NULL);
#endif
        SetToolTip(tooltip);
    }
#ifdef __WXMSW__
    // Use this part of code just on Windows to avoid of some layout issues on Linux
    // see https://github.com/prusa3d/PrusaSlicer/issues/5163 and https://github.com/prusa3d/PrusaSlicer/issues/5505
    // Update control min size after rescale (changed Display DPI under MSW)
    if (GetMinWidth() != 20 * m_em_unit)
        SetMinSize(wxSize(20 * m_em_unit, GetSize().GetHeight()));
#endif //__WXMSW__
}
References Slic3r::Preset::alias, Slic3r::GUI::BitmapComboBox::Append(), Slic3r::PhysicalPrinterCollection::begin(), Slic3r::can_decode_color(), Slic3r::Preset::config, Slic3r::PhysicalPrinterCollection::empty(), Slic3r::PhysicalPrinterCollection::end(), Slic3r::PresetBundle::extruders_filaments, Slic3r::ExtruderFilaments::filament(), Slic3r::PresetBundle::filaments, Slic3r::PresetCollection::find_preset(), Slic3r::GUI::from_u8(), Slic3r::ConfigDef::get(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::ConfigOptionDef::get_default_value(), Slic3r::PresetCollection::get_edited_preset(), get_preset_name(), Slic3r::PresetCollection::get_presets(), Slic3r::ExtruderFilaments::get_selected_filament(), Slic3r::PresetCollection::get_selected_idx(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::ExtruderFilaments::get_selected_preset(), Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::GUI::PresetComboBox::invalidate_selection(), Slic3r::Preset::is_compatible, Slic3r::Filament::is_compatible, Slic3r::Preset::is_default, Slic3r::Preset::is_dirty, Slic3r::PhysicalPrinterCollection::is_selected(), Slic3r::Preset::is_system, Slic3r::Preset::is_visible, L, Slic3r::GUI::PresetComboBox::LABEL_ITEM_PHYSICAL_PRINTER, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_FILAMENTS, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_MATERIALS, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_PRINTERS, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_em_unit, m_extruder_idx, Slic3r::GUI::PresetComboBox::m_main_bitmap_name, Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::Preset::name, Slic3r::GUI::PresetComboBox::norm_icon_width, Slic3r::GUI::PresetComboBox::null_icon_width, Slic3r::GUI::PresetComboBox::NullBitmapBndl(), Slic3r::PresetCollection::num_default_presets(), Slic3r::ConfigBase::opt_string(), Slic3r::PresetBundle::physical_printers, Slic3r::print_config_def, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptSLA, Slic3r::GUI::PresetComboBox::separator(), Slic3r::GUI::PresetComboBox::set_label_marker(), Slic3r::PresetBundle::sla_materials, Slic3r::GUI::suffix(), Slic3r::VendorProfile::templates_profile, Slic3r::GUI::PresetComboBox::thin_space_icon_width, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::GUI::PresetComboBox::update_selection(), Slic3r::GUI::PresetComboBox::validate_selection(), Slic3r::Preset::vendor, and Slic3r::GUI::PresetComboBox::wide_space_icon_width.
Referenced by change_extruder_color(), Slic3r::GUI::Plater::on_extruders_change(), Slic3r::GUI::Plater::priv::on_select_preset(), and show_add_menu().
update() [2/2]
void Slic3r::GUI::PresetComboBox::update (std::string select_preset) inherited
{
    Freeze();
    Clear();
    invalidate_selection();
    const std::deque<Preset>& presets = m_collection->get_presets();
    struct PresetData {
        wxString        name;
        wxString        lower_name;
        wxBitmapBundle* bitmap;
        bool            enabled; // not used in incomp_presets
    };
    std::vector<PresetData> system_presets;
    std::vector<PresetData> nonsys_presets;
    std::vector<PresetData> incomp_presets;
    wxString selected = "";
    if (!presets.front().is_visible)
        set_label_marker(Append(separator(L("System presets")), NullBitmapBndl()));
    for (size_t i = presets.front().is_visible ? 0 : m_collection->num_default_presets(); i < presets.size(); ++i)
    {
        const Preset& preset = presets[i];
        if (!m_show_all && (!preset.is_visible || !preset.is_compatible))
            continue;
        // marker used for disable incompatible printer models for the selected physical printer
        bool is_enabled = m_type == Preset::TYPE_PRINTER && printer_technology != ptAny ? preset.printer_technology() == printer_technology : true;
        if (select_preset_name.empty() && is_enabled)
            select_preset_name = preset.name;
        std::string   bitmap_key = "cb";
        if (m_type == Preset::TYPE_PRINTER) {
            bitmap_key += "_printer";
            if (preset.printer_technology() == ptSLA)
                bitmap_key += "_sla";
        }
        std::string main_icon_name = m_type == Preset::TYPE_PRINTER && preset.printer_technology() == ptSLA ? "sla_printer" : m_main_bitmap_name;
        auto bmp = get_bmp(bitmap_key, main_icon_name, "lock_closed", is_enabled, preset.is_compatible, preset.is_system || preset.is_default);
        assert(bmp);
        if (!is_enabled) {
            incomp_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp, false});
            if (preset.is_dirty && m_show_modif_preset_separately)
                incomp_presets.push_back({get_preset_name_with_suffix(preset), get_preset_name_with_suffix(preset).Lower(), bmp, false});
        }
        else if (preset.is_default || preset.is_system)
        {
            system_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp, is_enabled});
            if (preset.name == select_preset_name)
                selected = preset.name;
            if (preset.is_dirty && m_show_modif_preset_separately) {
                wxString preset_name = get_preset_name_with_suffix(preset);
                system_presets.push_back({preset_name, preset_name.Lower(), bmp, is_enabled});
                if (into_u8(preset_name) == select_preset_name)
                    selected = preset_name;
            }
        }
        else
        {
            nonsys_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp, is_enabled});
            if (preset.name == select_preset_name || (select_preset_name.empty() && is_enabled))
                selected = get_preset_name(preset);
            if (preset.is_dirty && m_show_modif_preset_separately) {
                wxString preset_name = get_preset_name_with_suffix(preset);
                nonsys_presets.push_back({preset_name, preset_name.Lower(), bmp, is_enabled});
                if (preset_name == select_preset_name || (select_preset_name.empty() && is_enabled))
                    selected = preset_name;
            }
        }
        if (i + 1 == m_collection->num_default_presets())
            set_label_marker(Append(separator(L("System presets")), NullBitmapBndl()));
    }
    if (!system_presets.empty())
    {
        std::sort(system_presets.begin(), system_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        for (std::vector<PresetData>::iterator it = system_presets.begin(); it != system_presets.end(); ++it) {
            int item_id = Append(it->name, *it->bitmap);
            if (!it->enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->name == selected);
        }
    }
    if (!nonsys_presets.empty())
    {
        std::sort(nonsys_presets.begin(), nonsys_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        set_label_marker(Append(separator(L("User presets")), NullBitmapBndl()));
        for (std::vector<PresetData>::iterator it = nonsys_presets.begin(); it != nonsys_presets.end(); ++it) {
            int item_id = Append(it->name, *it->bitmap);
            if (!it->enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->name == selected);
        }
    }
    if (!incomp_presets.empty())
    {
        std::sort(incomp_presets.begin(), incomp_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        set_label_marker(Append(separator(L("Incompatible presets")), NullBitmapBndl()));
        for (std::vector<PresetData>  ::iterator it = incomp_presets.begin(); it != incomp_presets.end(); ++it) {
            set_label_marker(Append(it->name, *it->bitmap), LABEL_ITEM_DISABLED);
        }
    }
    update_selection();
    Thaw();
}
References Slic3r::GUI::BitmapComboBox::Append(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_preset_name(), Slic3r::GUI::get_preset_name_with_suffix(), Slic3r::PresetCollection::get_presets(), Slic3r::GUI::into_u8(), Slic3r::GUI::PresetComboBox::invalidate_selection(), Slic3r::Preset::is_compatible, Slic3r::Preset::is_default, Slic3r::Preset::is_dirty, Slic3r::Preset::is_system, Slic3r::Preset::is_visible, L, Slic3r::GUI::PresetComboBox::LABEL_ITEM_DISABLED, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_main_bitmap_name, Slic3r::GUI::PresetComboBox::m_show_all, Slic3r::GUI::PresetComboBox::m_show_modif_preset_separately, Slic3r::GUI::PresetComboBox::m_type, Slic3r::Preset::name, Slic3r::GUI::PresetComboBox::NullBitmapBndl(), Slic3r::PresetCollection::num_default_presets(), Slic3r::Preset::printer_technology(), Slic3r::GUI::PresetComboBox::printer_technology, Slic3r::ptAny, Slic3r::ptSLA, Slic3r::GUI::PresetComboBox::separator(), Slic3r::GUI::PresetComboBox::set_label_marker(), Slic3r::Preset::TYPE_PRINTER, Slic3r::GUI::PresetComboBox::update_selection(), and Slic3r::GUI::PresetComboBox::validate_selection().
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter(), Slic3r::GUI::PresetForPrinter::AllowDelete(), Slic3r::GUI::DiffPresetDialog::create_presets_sizer(), Slic3r::GUI::PresetForPrinter::SuppressDelete(), and Slic3r::GUI::DiffPresetDialog::update_compatibility().
update_from_bundle()
void Slic3r::GUI::PresetComboBox::update_from_bundle () inherited
{
    this->update(m_collection->get_selected_preset().name);
}
References Slic3r::PresetCollection::get_selected_preset(), Slic3r::GUI::PresetComboBox::m_collection, Slic3r::Preset::name, and Slic3r::GUI::PresetComboBox::update().
update_selection()
void Slic3r::GUI::PresetComboBox::update_selection () protected inherited
{
    /* If selected_preset_item is still equal to INT_MAX, it means that
     * there is no presets added to the list.
     * So, select last combobox item ("Add/Remove preset")
     */
    validate_selection();
    SetSelection(m_last_selected);
#ifdef __WXMSW__
    // From the Windows 2004 the tooltip for preset combobox doesn't work after next call of SetTooltip()
    // (There was an issue, when tooltip doesn't appears after changing of the preset selection)
    // But this workaround seems to work: We should to kill tooltip and than set new tooltip value
    SetToolTip(NULL);
#endif
    SetToolTip(GetString(m_last_selected));
// A workaround for a set of issues related to text fitting into gtk widgets:
// See e.g.: https://github.com/prusa3d/PrusaSlicer/issues/4584
#if defined(__WXGTK20__) || defined(__WXGTK3__)
    GList* cells = gtk_cell_layout_get_cells(GTK_CELL_LAYOUT(m_widget));
    // 'cells' contains the GtkCellRendererPixBuf for the icon,
    // 'cells->next' contains GtkCellRendererText for the text we need to ellipsize
    if (!cells || !cells->next) return;
    auto cell = static_cast<GtkCellRendererText *>(cells->next->data);
    if (!cell) return;
    g_object_set(G_OBJECT(cell), "ellipsize", PANGO_ELLIPSIZE_END, (char*)NULL);
    // Only the list of cells must be freed, the renderer isn't ours to free
    g_list_free(cells);
#endif
}
References Slic3r::GUI::PresetComboBox::m_last_selected, and Slic3r::GUI::PresetComboBox::validate_selection().
Referenced by update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
validate_selection()
void Slic3r::GUI::PresetComboBox::validate_selection (bool predicate = false) protected inherited
{
    if (predicate ||
        // just in case: mark m_last_selected as a first added element
        m_last_selected == INT_MAX)
        m_last_selected = GetCount() - 1;
}
References Slic3r::GUI::PresetComboBox::m_last_selected.
Referenced by update(), Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::PresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update_selection().
Member Data Documentation
edit_btn
ScalableButton* Slic3r::GUI::PlaterPresetComboBox::edit_btn { nullptr }
Referenced by PlaterPresetComboBox(), ~PlaterPresetComboBox(), and sys_color_changed().
icon_height
int Slic3r::GUI::PresetComboBox::icon_height protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::NullBitmapBndl().
m_bitmapCompatible
wxBitmapBundle* Slic3r::GUI::PresetComboBox::m_bitmapCompatible protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::sys_color_changed().
m_bitmapIncompatible
wxBitmapBundle* Slic3r::GUI::PresetComboBox::m_bitmapIncompatible protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::sys_color_changed().
m_collection
PresetCollection* Slic3r::GUI::PresetComboBox::m_collection {nullptr} protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::OnSelect(), OnSelect(), Slic3r::GUI::TabPresetComboBox::OnSelect(), Slic3r::GUI::TabPresetComboBox::presets(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), update(), Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::PresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update_dirty(), and Slic3r::GUI::PresetComboBox::update_from_bundle().
m_em_unit
int Slic3r::GUI::PresetComboBox::m_em_unit protected inherited
Referenced by PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::msw_rescale(), msw_rescale(), Slic3r::GUI::TabPresetComboBox::msw_rescale(), and update().
m_extruder_idx
int Slic3r::GUI::PlaterPresetComboBox::m_extruder_idx = -1 private
Referenced by PlaterPresetComboBox(), change_extruder_color(), get_extruder_idx(), set_extruder_idx(), switch_to_tab(), and update().
m_last_selected
int Slic3r::GUI::PresetComboBox::m_last_selected protected inherited
Referenced by Slic3r::GUI::PresetComboBox::invalidate_selection(), Slic3r::GUI::PresetComboBox::OnSelect(), OnSelect(), Slic3r::GUI::TabPresetComboBox::OnSelect(), Slic3r::GUI::PresetComboBox::update_selection(), and Slic3r::GUI::PresetComboBox::validate_selection().
m_main_bitmap_name
std::string Slic3r::GUI::PresetComboBox::m_main_bitmap_name protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
m_preset_bundle
PresetBundle* Slic3r::GUI::PresetComboBox::m_preset_bundle {nullptr} protected inherited
Referenced by PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::del_physical_printer(), Slic3r::GUI::PresetComboBox::edit_physical_printer(), get_selected_ph_printer_name(), Slic3r::GUI::PresetComboBox::open_physical_printer_url(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), show_edit_menu(), update(), and Slic3r::GUI::TabPresetComboBox::update().
m_show_all
bool Slic3r::GUI::PresetComboBox::m_show_all { false } private inherited
Referenced by Slic3r::GUI::PresetComboBox::show_all(), and Slic3r::GUI::PresetComboBox::update().
m_show_modif_preset_separately
bool Slic3r::GUI::PresetComboBox::m_show_modif_preset_separately { false } private inherited
Referenced by Slic3r::GUI::PresetComboBox::show_modif_preset_separately(), and Slic3r::GUI::PresetComboBox::update().
m_suppress_change
bool Slic3r::GUI::PresetComboBox::m_suppress_change { true } protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox().
m_type
Preset::Type Slic3r::GUI::PresetComboBox::m_type protected inherited
Referenced by PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::del_physical_printer(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), get_selected_ph_printer_name(), Slic3r::GUI::PresetComboBox::get_type(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), show_edit_menu(), switch_to_tab(), Slic3r::GUI::TabPresetComboBox::type(), update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
norm_icon_width
int Slic3r::GUI::PresetComboBox::norm_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), and update().
null_icon_width
int Slic3r::GUI::PresetComboBox::null_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::NullBitmapBndl(), and update().
on_selection_changed
std::function<void(int)> Slic3r::GUI::PresetComboBox::on_selection_changed { nullptr } protected inherited
Referenced by Slic3r::GUI::PresetComboBox::OnSelect(), Slic3r::GUI::TabPresetComboBox::OnSelect(), and Slic3r::GUI::PresetComboBox::set_selection_changed_function().
printer_technology
PrinterTechnology Slic3r::GUI::PresetComboBox::printer_technology {ptAny} protected inherited
Referenced by Slic3r::GUI::PresetComboBox::set_printer_technology(), and Slic3r::GUI::PresetComboBox::update().
space_icon_width
int Slic3r::GUI::PresetComboBox::space_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
thin_icon_width
int Slic3r::GUI::PresetComboBox::thin_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
thin_space_icon_width
int Slic3r::GUI::PresetComboBox::thin_space_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), and update().
wide_icon_width
int Slic3r::GUI::PresetComboBox::wide_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
wide_space_icon_width
int Slic3r::GUI::PresetComboBox::wide_space_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), and update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/PresetComboBoxes.hpp
src/slic3r/GUI/PresetComboBoxes.cpp