Prusa Slicer: src/imgui/imgui_internal.h File Reference
imgui_internal.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include "imstb_textedit.h"
Classes
struct ImVec1
struct ImVec2ih
struct ImRect
struct ImBitArray< BITCOUNT >
struct ImBitVector
struct ImSpan< T >
struct ImSpanAllocator< CHUNKS >
struct ImPool< T >
struct ImChunkStream< T >
struct ImDrawListSharedData
struct ImDrawDataBuilder
struct ImGuiDataTypeTempStorage
struct ImGuiDataTypeInfo
struct ImGuiColorMod
struct ImGuiStyleMod
struct ImGuiGroupData
struct ImGuiMenuColumns
struct ImGuiInputTextState
struct ImGuiPopupData
struct ImGuiNavItemData
struct ImGuiNextWindowData
struct ImGuiNextItemData
struct ImGuiShrinkWidthItem
struct ImGuiPtrOrIndex
struct ImGuiOldColumnData
struct ImGuiOldColumns
struct ImGuiViewportP
struct ImGuiWindowSettings
struct ImGuiSettingsHandler
struct ImGuiMetricsConfig
struct ImGuiStackSizes
struct ImGuiContextHook
struct ImGuiContext
struct ImGuiWindowTempData
struct ImGuiWindow
struct ImGuiLastItemDataBackup
struct ImGuiTabItem
struct ImGuiTabBar
struct ImGuiTableColumn
struct ImGuiTableCellData
struct ImGuiTable
struct ImGuiTableTempData
struct ImGuiTableColumnSettings
struct ImGuiTableSettings
struct ImFontBuilderIO
union ImGuiStyleMod.__unnamed672__
Namespaces
namespace ImStb
namespace ImGui
Macros
#define IMGUI_ENABLE_STB_TRUETYPE
#define STB_TEXTEDIT_STRING ImGuiInputTextState
#define STB_TEXTEDIT_CHARTYPE ImWchar
#define STB_TEXTEDIT_GETWIDTH_NEWLINE (-1.0f)
#define STB_TEXTEDIT_UNDOSTATECOUNT 99
#define STB_TEXTEDIT_UNDOCHARCOUNT 999
#define IMGUI_DEBUG_LOG(_FMT, ...) printf("[%05d] " _FMT, GImGui->FrameCount, __VA_ARGS__)
#define IMGUI_DEBUG_LOG_POPUP(...) ((void)0)
#define IMGUI_DEBUG_LOG_NAV(...) ((void)0)
#define IM_STATIC_ASSERT(_COND) typedef char static_assertion_##__line__[(_COND)?1:-1]
#define IM_ASSERT_PARANOID(_EXPR)
#define IM_ASSERT_USER_ERROR(_EXP, _MSG) IM_ASSERT((_EXP) && _MSG)
#define IM_PI 3.14159265358979323846f
#define IM_NEWLINE "\n"
#define IM_TABSIZE (4)
#define IM_MEMALIGN(_OFF, _ALIGN) (((_OFF) + (_ALIGN - 1)) & ~(_ALIGN - 1))
#define IM_F32_TO_INT8_UNBOUND(_VAL) ((int)((_VAL) * 255.0f + ((_VAL)>=0 ? 0.5f : -0.5f)))
#define IM_F32_TO_INT8_SAT(_VAL) ((int)(ImSaturate(_VAL) * 255.0f + 0.5f))
#define IM_FLOOR(_VAL) ((float)(int)(_VAL))
#define IM_ROUND(_VAL) ((float)(int)((_VAL) + 0.5f))
#define IMGUI_CDECL
#define IM_MSVC_WARNING_SUPPRESS(XXXX)
#define IM_DEBUG_BREAK() IM_ASSERT(0)
#define ImQsort qsort
#define ImFabs(X) fabsf(X)
#define ImSqrt(X) sqrtf(X)
#define ImFmod(X, Y) fmodf((X), (Y))
#define ImCos(X) cosf(X)
#define ImSin(X) sinf(X)
#define ImAcos(X) acosf(X)
#define ImAtan2(Y, X) atan2f((Y), (X))
#define ImAtof(STR) atof(STR)
#define ImCeil(X) ceilf(X)
#define IM_ROUNDUP_TO_EVEN(_V) ((((_V) + 1) / 2) * 2)
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN 4
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX 512
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC(_RAD, _MAXERROR) ImClamp(IM_ROUNDUP_TO_EVEN((int)ImCeil(IM_PI / ImAcos(1 - ImMin((_MAXERROR), (_RAD)) / (_RAD)))), IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN, IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX)
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_R(_N, _MAXERROR) ((_MAXERROR) / (1 - ImCos(IM_PI / ImMax((float)(_N), IM_PI))))
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_ERROR(_N, _RAD) ((1 - ImCos(IM_PI / ImMax((float)(_N), IM_PI))) / (_RAD))
#define IM_DRAWLIST_ARCFAST_TABLE_SIZE 48
#define IM_DRAWLIST_ARCFAST_SAMPLE_MAX IM_DRAWLIST_ARCFAST_TABLE_SIZE
#define IM_COL32_DISABLE IM_COL32(0,0,0,1)
#define IMGUI_TABLE_MAX_COLUMNS 64
#define IMGUI_TABLE_MAX_DRAW_CHANNELS (4 + 64 * 2)
#define IMGUI_TEST_ENGINE_ITEM_ADD(_BB, _ID) do { } while (0)
#define IMGUI_TEST_ENGINE_ITEM_INFO(_ID, _LABEL, _FLAGS) do { } while (0)
#define IMGUI_TEST_ENGINE_LOG(_FMT, ...) do { } while (0)
#define IMGUI_TEST_ENGINE_ID_INFO(_ID, _TYPE, _DATA) do { } while (0)
#define IMGUI_TEST_ENGINE_ID_INFO2(_ID, _TYPE, _DATA, _DATA2) do { } while (0)
Typedefs
typedef int ImGuiLayoutType
typedef int ImGuiItemFlags
typedef int ImGuiItemAddFlags
typedef int ImGuiItemStatusFlags
typedef int ImGuiOldColumnFlags
typedef int ImGuiNavHighlightFlags
typedef int ImGuiNavDirSourceFlags
typedef int ImGuiNavMoveFlags
typedef int ImGuiNextItemDataFlags
typedef int ImGuiNextWindowDataFlags
typedef int ImGuiSeparatorFlags
typedef int ImGuiTextFlags
typedef int ImGuiTooltipFlags
typedef void(* ImGuiErrorLogCallback) (void *user_data, const char *fmt,...)
typedef FILE * ImFileHandle
typedef int ImPoolIdx
typedef void(* ImGuiContextHookCallback) (ImGuiContext *ctx, ImGuiContextHook *hook)
typedef ImS8 ImGuiTableColumnIdx
typedef ImU8 ImGuiTableDrawChannelIdx
Enumerations
enum ImGuiItemFlags_ {
ImGuiItemFlags_None = 0 , ImGuiItemFlags_NoTabStop = 1 << 0 , ImGuiItemFlags_ButtonRepeat = 1 << 1 , ImGuiItemFlags_Disabled = 1 << 2 ,
ImGuiItemFlags_NoNav = 1 << 3 , ImGuiItemFlags_NoNavDefaultFocus = 1 << 4 , ImGuiItemFlags_SelectableDontClosePopup = 1 << 5 , ImGuiItemFlags_MixedValue = 1 << 6 ,
ImGuiItemFlags_ReadOnly = 1 << 7
}
enum ImGuiItemAddFlags_ { ImGuiItemAddFlags_None = 0 , ImGuiItemAddFlags_Focusable = 1 << 0 }
enum ImGuiItemStatusFlags_ {
ImGuiItemStatusFlags_None = 0 , ImGuiItemStatusFlags_HoveredRect = 1 << 0 , ImGuiItemStatusFlags_HasDisplayRect = 1 << 1 , ImGuiItemStatusFlags_Edited = 1 << 2 ,
ImGuiItemStatusFlags_ToggledSelection = 1 << 3 , ImGuiItemStatusFlags_ToggledOpen = 1 << 4 , ImGuiItemStatusFlags_HasDeactivated = 1 << 5 , ImGuiItemStatusFlags_Deactivated = 1 << 6 ,
ImGuiItemStatusFlags_HoveredWindow = 1 << 7 , ImGuiItemStatusFlags_FocusedByCode = 1 << 8 , ImGuiItemStatusFlags_FocusedByTabbing = 1 << 9 , ImGuiItemStatusFlags_Focused = ImGuiItemStatusFlags_FocusedByCode | ImGuiItemStatusFlags_FocusedByTabbing
}
enum ImGuiInputTextFlagsPrivate_ { ImGuiInputTextFlags_Multiline = 1 << 26 , ImGuiInputTextFlags_NoMarkEdited = 1 << 27 , ImGuiInputTextFlags_MergedItem = 1 << 28 }
enum ImGuiButtonFlagsPrivate_ {
ImGuiButtonFlags_PressedOnClick = 1 << 4 , ImGuiButtonFlags_PressedOnClickRelease = 1 << 5 , ImGuiButtonFlags_PressedOnClickReleaseAnywhere = 1 << 6 , ImGuiButtonFlags_PressedOnRelease = 1 << 7 ,
ImGuiButtonFlags_PressedOnDoubleClick = 1 << 8 , ImGuiButtonFlags_PressedOnDragDropHold = 1 << 9 , ImGuiButtonFlags_Repeat = 1 << 10 , ImGuiButtonFlags_FlattenChildren = 1 << 11 ,
ImGuiButtonFlags_AllowItemOverlap = 1 << 12 , ImGuiButtonFlags_DontClosePopups = 1 << 13 , ImGuiButtonFlags_Disabled = 1 << 14 , ImGuiButtonFlags_AlignTextBaseLine = 1 << 15 ,
ImGuiButtonFlags_NoKeyModifiers = 1 << 16 , ImGuiButtonFlags_NoHoldingActiveId = 1 << 17 , ImGuiButtonFlags_NoNavFocus = 1 << 18 , ImGuiButtonFlags_NoHoveredOnFocus = 1 << 19 ,
ImGuiButtonFlags_PressedOnMask_ = ImGuiButtonFlags_PressedOnClick | ImGuiButtonFlags_PressedOnClickRelease | ImGuiButtonFlags_PressedOnClickReleaseAnywhere | ImGuiButtonFlags_PressedOnRelease | ImGuiButtonFlags_PressedOnDoubleClick | ImGuiButtonFlags_PressedOnDragDropHold , ImGuiButtonFlags_PressedOnDefault_ = ImGuiButtonFlags_PressedOnClickRelease
}
enum ImGuiSliderFlagsPrivate_ { ImGuiSliderFlags_Vertical = 1 << 20 , ImGuiSliderFlags_ReadOnly = 1 << 21 }
enum ImGuiSelectableFlagsPrivate_ {
ImGuiSelectableFlags_NoHoldingActiveID = 1 << 20 , ImGuiSelectableFlags_SelectOnClick = 1 << 21 , ImGuiSelectableFlags_SelectOnRelease = 1 << 22 , ImGuiSelectableFlags_SpanAvailWidth = 1 << 23 ,
ImGuiSelectableFlags_DrawHoveredWhenHeld = 1 << 24 , ImGuiSelectableFlags_SetNavIdOnHover = 1 << 25 , ImGuiSelectableFlags_NoPadWithHalfSpacing = 1 << 26
}
enum ImGuiTreeNodeFlagsPrivate_ { ImGuiTreeNodeFlags_ClipLabelForTrailingButton = 1 << 20 }
enum ImGuiSeparatorFlags_ { ImGuiSeparatorFlags_None = 0 , ImGuiSeparatorFlags_Horizontal = 1 << 0 , ImGuiSeparatorFlags_Vertical = 1 << 1 , ImGuiSeparatorFlags_SpanAllColumns = 1 << 2 }
enum ImGuiTextFlags_ { ImGuiTextFlags_None = 0 , ImGuiTextFlags_NoWidthForLargeClippedText = 1 << 0 }
enum ImGuiTooltipFlags_ { ImGuiTooltipFlags_None = 0 , ImGuiTooltipFlags_OverridePreviousTooltip = 1 << 0 }
enum ImGuiLayoutType_ { ImGuiLayoutType_Horizontal = 0 , ImGuiLayoutType_Vertical = 1 }
enum ImGuiLogType {
ImGuiLogType_None = 0 , ImGuiLogType_TTY , ImGuiLogType_File , ImGuiLogType_Buffer ,
ImGuiLogType_Clipboard
}
enum ImGuiAxis { ImGuiAxis_None = -1 , ImGuiAxis_X = 0 , ImGuiAxis_Y = 1 }
enum ImGuiPlotType { ImGuiPlotType_Lines , ImGuiPlotType_Histogram }
enum ImGuiInputSource {
ImGuiInputSource_None = 0 , ImGuiInputSource_Mouse , ImGuiInputSource_Keyboard , ImGuiInputSource_Gamepad ,
ImGuiInputSource_Nav , ImGuiInputSource_Clipboard , ImGuiInputSource_COUNT
}
enum ImGuiInputReadMode {
ImGuiInputReadMode_Down , ImGuiInputReadMode_Pressed , ImGuiInputReadMode_Released , ImGuiInputReadMode_Repeat ,
ImGuiInputReadMode_RepeatSlow , ImGuiInputReadMode_RepeatFast
}
enum ImGuiNavHighlightFlags_ {
ImGuiNavHighlightFlags_None = 0 , ImGuiNavHighlightFlags_TypeDefault = 1 << 0 , ImGuiNavHighlightFlags_TypeThin = 1 << 1 , ImGuiNavHighlightFlags_AlwaysDraw = 1 << 2 ,
ImGuiNavHighlightFlags_NoRounding = 1 << 3
}
enum ImGuiNavDirSourceFlags_ { ImGuiNavDirSourceFlags_None = 0 , ImGuiNavDirSourceFlags_Keyboard = 1 << 0 , ImGuiNavDirSourceFlags_PadDPad = 1 << 1 , ImGuiNavDirSourceFlags_PadLStick = 1 << 2 }
enum ImGuiNavMoveFlags_ {
ImGuiNavMoveFlags_None = 0 , ImGuiNavMoveFlags_LoopX = 1 << 0 , ImGuiNavMoveFlags_LoopY = 1 << 1 , ImGuiNavMoveFlags_WrapX = 1 << 2 ,
ImGuiNavMoveFlags_WrapY = 1 << 3 , ImGuiNavMoveFlags_AllowCurrentNavId = 1 << 4 , ImGuiNavMoveFlags_AlsoScoreVisibleSet = 1 << 5 , ImGuiNavMoveFlags_ScrollToEdge = 1 << 6
}
enum ImGuiNavForward { ImGuiNavForward_None , ImGuiNavForward_ForwardQueued , ImGuiNavForward_ForwardActive }
enum ImGuiNavLayer { ImGuiNavLayer_Main = 0 , ImGuiNavLayer_Menu = 1 , ImGuiNavLayer_COUNT }
enum ImGuiPopupPositionPolicy { ImGuiPopupPositionPolicy_Default , ImGuiPopupPositionPolicy_ComboBox , ImGuiPopupPositionPolicy_Tooltip }
enum ImGuiDataTypePrivate_ { ImGuiDataType_String = ImGuiDataType_COUNT + 1 , ImGuiDataType_Pointer , ImGuiDataType_ID }
enum ImGuiNextWindowDataFlags_ {
ImGuiNextWindowDataFlags_None = 0 , ImGuiNextWindowDataFlags_HasPos = 1 << 0 , ImGuiNextWindowDataFlags_HasSize = 1 << 1 , ImGuiNextWindowDataFlags_HasContentSize = 1 << 2 ,
ImGuiNextWindowDataFlags_HasCollapsed = 1 << 3 , ImGuiNextWindowDataFlags_HasSizeConstraint = 1 << 4 , ImGuiNextWindowDataFlags_HasFocus = 1 << 5 , ImGuiNextWindowDataFlags_HasBgAlpha = 1 << 6 ,
ImGuiNextWindowDataFlags_HasScroll = 1 << 7
}
enum ImGuiNextItemDataFlags_ { ImGuiNextItemDataFlags_None = 0 , ImGuiNextItemDataFlags_HasWidth = 1 << 0 , ImGuiNextItemDataFlags_HasOpen = 1 << 1 }
enum ImGuiOldColumnFlags_ {
ImGuiOldColumnFlags_None = 0 , ImGuiOldColumnFlags_NoBorder = 1 << 0 , ImGuiOldColumnFlags_NoResize = 1 << 1 , ImGuiOldColumnFlags_NoPreserveWidths = 1 << 2 ,
ImGuiOldColumnFlags_NoForceWithinWindow = 1 << 3 , ImGuiOldColumnFlags_GrowParentContentsSize = 1 << 4 , ImGuiColumnsFlags_None = ImGuiOldColumnFlags_None , ImGuiColumnsFlags_NoBorder = ImGuiOldColumnFlags_NoBorder ,
ImGuiColumnsFlags_NoResize = ImGuiOldColumnFlags_NoResize , ImGuiColumnsFlags_NoPreserveWidths = ImGuiOldColumnFlags_NoPreserveWidths , ImGuiColumnsFlags_NoForceWithinWindow = ImGuiOldColumnFlags_NoForceWithinWindow , ImGuiColumnsFlags_GrowParentContentsSize = ImGuiOldColumnFlags_GrowParentContentsSize
}
enum ImGuiContextHookType {
ImGuiContextHookType_NewFramePre , ImGuiContextHookType_NewFramePost , ImGuiContextHookType_EndFramePre , ImGuiContextHookType_EndFramePost ,
ImGuiContextHookType_RenderPre , ImGuiContextHookType_RenderPost , ImGuiContextHookType_Shutdown , ImGuiContextHookType_PendingRemoval_
}
enum ImGuiTabBarFlagsPrivate_ { ImGuiTabBarFlags_DockNode = 1 << 20 , ImGuiTabBarFlags_IsFocused = 1 << 21 , ImGuiTabBarFlags_SaveSettings = 1 << 22 }
enum ImGuiTabItemFlagsPrivate_ { ImGuiTabItemFlags_SectionMask_ = ImGuiTabItemFlags_Leading | ImGuiTabItemFlags_Trailing , ImGuiTabItemFlags_NoCloseButton = 1 << 20 , ImGuiTabItemFlags_Button = 1 << 21 }
Functions
IMGUI_API ImGuiID ImHashData (const void *data, size_t data_size, ImU32 seed=0)
IMGUI_API ImGuiID ImHashStr (const char *data, size_t data_size=0, ImU32 seed=0)
static ImGuiID ImHash (const void *data, int size, ImU32 seed=0)
IMGUI_API ImU32 ImAlphaBlendColors (ImU32 col_a, ImU32 col_b)
static bool ImIsPowerOfTwo (int v)
static bool ImIsPowerOfTwo (ImU64 v)
static int ImUpperPowerOfTwo (int v)
IMGUI_API int ImStricmp (const char *str1, const char *str2)
IMGUI_API int ImStrnicmp (const char *str1, const char *str2, size_t count)
IMGUI_API void ImStrncpy (char *dst, const char *src, size_t count)
IMGUI_API char * ImStrdup (const char *str)
IMGUI_API char * ImStrdupcpy (char *dst, size_t *p_dst_size, const char *str)
IMGUI_API const char * ImStrchrRange (const char *str_begin, const char *str_end, char c)
IMGUI_API int ImStrlenW (const ImWchar *str)
IMGUI_API const char * ImStreolRange (const char *str, const char *str_end)
IMGUI_API const ImWchar * ImStrbolW (const ImWchar *buf_mid_line, const ImWchar *buf_begin)
IMGUI_API const char * ImStristr (const char *haystack, const char *haystack_end, const char *needle, const char *needle_end)
IMGUI_API void ImStrTrimBlanks (char *str)
IMGUI_API const char * ImStrSkipBlank (const char *str)
IMGUI_API int ImFormatString (char *buf, size_t buf_size, const char *fmt,...) IM_FMTARGS(3)
IMGUI_API int ImFormatStringV (char *buf, size_t buf_size, const char *fmt, va_list args) IM_FMTLIST(3)
IMGUI_API const char * ImParseFormatFindStart (const char *format)
IMGUI_API const char * ImParseFormatFindEnd (const char *format)
IMGUI_API const char * ImParseFormatTrimDecorations (const char *format, char *buf, size_t buf_size)
IMGUI_API int ImParseFormatPrecision (const char *format, int default_value)
static bool ImCharIsBlankA (char c)
static bool ImCharIsBlankW (unsigned int c)
IMGUI_API int ImTextStrToUtf8 (char *buf, int buf_size, const ImWchar *in_text, const ImWchar *in_text_end)
IMGUI_API int ImTextCharFromUtf8 (unsigned int *out_char, const char *in_text, const char *in_text_end)
IMGUI_API int ImTextStrFromUtf8 (ImWchar *buf, int buf_size, const char *in_text, const char *in_text_end, const char **in_remaining=NULL)
IMGUI_API int ImTextCountCharsFromUtf8 (const char *in_text, const char *in_text_end)
IMGUI_API int ImTextCountUtf8BytesFromChar (const char *in_text, const char *in_text_end)
IMGUI_API int ImTextCountUtf8BytesFromStr (const ImWchar *in_text, const ImWchar *in_text_end)
IMGUI_API ImFileHandle ImFileOpen (const char *filename, const char *mode)
IMGUI_API bool ImFileClose (ImFileHandle file)
IMGUI_API ImU64 ImFileGetSize (ImFileHandle file)
IMGUI_API ImU64 ImFileRead (void *data, ImU64 size, ImU64 count, ImFileHandle file)
IMGUI_API ImU64 ImFileWrite (const void *data, ImU64 size, ImU64 count, ImFileHandle file)
IMGUI_API void * ImFileLoadToMemory (const char *filename, const char *mode, size_t *out_file_size=NULL, int padding_bytes=0)
static float ImPow (float x, float y)
static double ImPow (double x, double y)
static float ImLog (float x)
static double ImLog (double x)
static int ImAbs (int x)
static float ImAbs (float x)
static double ImAbs (double x)
static float ImSign (float x)
static double ImSign (double x)
static float ImRsqrt (float x)
static double ImRsqrt (double x)
template<typename T >
static T ImMin (T lhs, T rhs)
template<typename T >
static T ImMax (T lhs, T rhs)
template<typename T >
static T ImClamp (T v, T mn, T mx)
template<typename T >
static T ImLerp (T a, T b, float t)
template<typename T >
static void ImSwap (T &a, T &b)
template<typename T >
static T ImAddClampOverflow (T a, T b, T mn, T mx)
template<typename T >
static T ImSubClampOverflow (T a, T b, T mn, T mx)
static ImVec2 ImMin (const ImVec2 &lhs, const ImVec2 &rhs)
static ImVec2 ImMax (const ImVec2 &lhs, const ImVec2 &rhs)
static ImVec2 ImClamp (const ImVec2 &v, const ImVec2 &mn, ImVec2 mx)
static ImVec2 ImLerp (const ImVec2 &a, const ImVec2 &b, float t)
static ImVec2 ImLerp (const ImVec2 &a, const ImVec2 &b, const ImVec2 &t)
static ImVec4 ImLerp (const ImVec4 &a, const ImVec4 &b, float t)
static float ImSaturate (float f)
static float ImLengthSqr (const ImVec2 &lhs)
static float ImLengthSqr (const ImVec4 &lhs)
static float ImInvLength (const ImVec2 &lhs, float fail_value)
static float ImFloor (float f)
static float ImFloorSigned (float f)
static ImVec2 ImFloor (const ImVec2 &v)
static int ImModPositive (int a, int b)
static float ImDot (const ImVec2 &a, const ImVec2 &b)
static ImVec2 ImRotate (const ImVec2 &v, float cos_a, float sin_a)
static float ImLinearSweep (float current, float target, float speed)
static ImVec2 ImMul (const ImVec2 &lhs, const ImVec2 &rhs)
IM_MSVC_RUNTIME_CHECKS_RESTORE IMGUI_API ImVec2 ImBezierCubicCalc (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, const ImVec2 &p4, float t)
IMGUI_API ImVec2 ImBezierCubicClosestPoint (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, const ImVec2 &p4, const ImVec2 &p, int num_segments)
IMGUI_API ImVec2 ImBezierCubicClosestPointCasteljau (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, const ImVec2 &p4, const ImVec2 &p, float tess_tol)
IMGUI_API ImVec2 ImBezierQuadraticCalc (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, float t)
IMGUI_API ImVec2 ImLineClosestPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &p)
IMGUI_API bool ImTriangleContainsPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)
IMGUI_API ImVec2 ImTriangleClosestPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)
IMGUI_API void ImTriangleBarycentricCoords (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p, float &out_u, float &out_v, float &out_w)
float ImTriangleArea (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c)
IMGUI_API ImGuiDir ImGetDirQuadrantFromDelta (float dx, float dy)
IM_MSVC_RUNTIME_CHECKS_RESTORE bool ImBitArrayTestBit (const ImU32 *arr, int n)
void ImBitArrayClearBit (ImU32 *arr, int n)
void ImBitArraySetBit (ImU32 *arr, int n)
void ImBitArraySetBitRange (ImU32 *arr, int n, int n2)
ImGuiWindow * ImGui::GetCurrentWindowRead ()
ImGuiWindow * ImGui::GetCurrentWindow ()
IMGUI_API ImGuiWindow * ImGui::FindWindowByID (ImGuiID id)
IMGUI_API ImGuiWindow * ImGui::FindWindowByName (const char *name)
IMGUI_API void ImGui::UpdateWindowParentAndRootLinks (ImGuiWindow *window, ImGuiWindowFlags flags, ImGuiWindow *parent_window)
IMGUI_API ImVec2 ImGui::CalcWindowNextAutoFitSize (ImGuiWindow *window)
IMGUI_API bool ImGui::IsWindowChildOf (ImGuiWindow *window, ImGuiWindow *potential_parent)
IMGUI_API bool ImGui::IsWindowAbove (ImGuiWindow *potential_above, ImGuiWindow *potential_below)
IMGUI_API bool ImGui::IsWindowNavFocusable (ImGuiWindow *window)
IMGUI_API ImRect ImGui::GetWindowAllowedExtentRect (ImGuiWindow *window)
IMGUI_API void ImGui::SetWindowPos (ImGuiWindow *window, const ImVec2 &pos, ImGuiCond cond=0)
IMGUI_API void ImGui::SetWindowSize (ImGuiWindow *window, const ImVec2 &size, ImGuiCond cond=0)
IMGUI_API void ImGui::SetWindowCollapsed (ImGuiWindow *window, bool collapsed, ImGuiCond cond=0)
IMGUI_API void ImGui::SetWindowHitTestHole (ImGuiWindow *window, const ImVec2 &pos, const ImVec2 &size)
IMGUI_API void ImGui::FocusWindow (ImGuiWindow *window)
IMGUI_API void ImGui::FocusTopMostWindowUnderOne (ImGuiWindow *under_this_window, ImGuiWindow *ignore_window)
IMGUI_API void ImGui::BringWindowToFocusFront (ImGuiWindow *window)
IMGUI_API void ImGui::BringWindowToDisplayFront (ImGuiWindow *window)
IMGUI_API void ImGui::BringWindowToDisplayBack (ImGuiWindow *window)
IMGUI_API void ImGui::SetCurrentFont (ImFont *font)
ImFont * ImGui::GetDefaultFont ()
ImDrawList * ImGui::GetForegroundDrawList (ImGuiWindow *window)
IMGUI_API ImDrawList * ImGui::GetBackgroundDrawList (ImGuiViewport *viewport)
IMGUI_API ImDrawList * ImGui::GetForegroundDrawList (ImGuiViewport *viewport)
IMGUI_API void ImGui::Initialize (ImGuiContext *context)
IMGUI_API void ImGui::Shutdown (ImGuiContext *context)
IMGUI_API void ImGui::UpdateHoveredWindowAndCaptureFlags ()
IMGUI_API void ImGui::StartMouseMovingWindow (ImGuiWindow *window)
IMGUI_API void ImGui::UpdateMouseMovingWindowNewFrame ()
IMGUI_API void ImGui::UpdateMouseMovingWindowEndFrame ()
IMGUI_API ImGuiID ImGui::AddContextHook (ImGuiContext *context, const ImGuiContextHook *hook)
IMGUI_API void ImGui::RemoveContextHook (ImGuiContext *context, ImGuiID hook_to_remove)
IMGUI_API void ImGui::CallContextHooks (ImGuiContext *context, ImGuiContextHookType type)
IMGUI_API void ImGui::MarkIniSettingsDirty ()
IMGUI_API void ImGui::MarkIniSettingsDirty (ImGuiWindow *window)
IMGUI_API void ImGui::ClearIniSettings ()
IMGUI_API ImGuiWindowSettings * ImGui::CreateNewWindowSettings (const char *name)
IMGUI_API ImGuiWindowSettings * ImGui::FindWindowSettings (ImGuiID id)
IMGUI_API ImGuiWindowSettings * ImGui::FindOrCreateWindowSettings (const char *name)
IMGUI_API ImGuiSettingsHandler * ImGui::FindSettingsHandler (const char *type_name)
IMGUI_API void ImGui::SetNextWindowScroll (const ImVec2 &scroll)
IMGUI_API void ImGui::SetScrollX (ImGuiWindow *window, float scroll_x)
IMGUI_API void ImGui::SetScrollY (ImGuiWindow *window, float scroll_y)
IMGUI_API void ImGui::SetScrollFromPosX (ImGuiWindow *window, float local_x, float center_x_ratio)
IMGUI_API void ImGui::SetScrollFromPosY (ImGuiWindow *window, float local_y, float center_y_ratio)
IMGUI_API ImVec2 ImGui::ScrollToBringRectIntoView (ImGuiWindow *window, const ImRect &item_rect)
ImGuiID ImGui::GetItemID ()
ImGuiItemStatusFlags ImGui::GetItemStatusFlags ()
ImGuiID ImGui::GetActiveID ()
ImGuiID ImGui::GetFocusID ()
ImGuiItemFlags ImGui::GetItemFlags ()
IMGUI_API void ImGui::SetActiveID (ImGuiID id, ImGuiWindow *window)
IMGUI_API void ImGui::SetFocusID (ImGuiID id, ImGuiWindow *window)
IMGUI_API void ImGui::ClearActiveID ()
IMGUI_API ImGuiID ImGui::GetHoveredID ()
IMGUI_API void ImGui::SetHoveredID (ImGuiID id)
IMGUI_API void ImGui::KeepAliveID (ImGuiID id)
IMGUI_API void ImGui::MarkItemEdited (ImGuiID id)
IMGUI_API void ImGui::PushOverrideID (ImGuiID id)
IMGUI_API ImGuiID ImGui::GetIDWithSeed (const char *str_id_begin, const char *str_id_end, ImGuiID seed)
IMGUI_API void ImGui::ItemSize (const ImVec2 &size, float text_baseline_y=-1.0f)
IMGUI_API void ImGui::ItemSize (const ImRect &bb, float text_baseline_y=-1.0f)
IMGUI_API bool ImGui::ItemAdd (const ImRect &bb, ImGuiID id, const ImRect *nav_bb=NULL, ImGuiItemAddFlags flags=0)
IMGUI_API bool ImGui::ItemHoverable (const ImRect &bb, ImGuiID id)
IMGUI_API void ImGui::ItemFocusable (ImGuiWindow *window, ImGuiID id)
IMGUI_API bool ImGui::IsClippedEx (const ImRect &bb, ImGuiID id, bool clip_even_when_logged)
IMGUI_API void ImGui::SetLastItemData (ImGuiWindow *window, ImGuiID item_id, ImGuiItemStatusFlags status_flags, const ImRect &item_rect)
IMGUI_API ImVec2 ImGui::CalcItemSize (ImVec2 size, float default_w, float default_h)
IMGUI_API float ImGui::CalcWrapWidthForPos (const ImVec2 &pos, float wrap_pos_x)
IMGUI_API void ImGui::PushMultiItemsWidths (int components, float width_full)
IMGUI_API void ImGui::PushItemFlag (ImGuiItemFlags option, bool enabled)
IMGUI_API void ImGui::PopItemFlag ()
IMGUI_API bool ImGui::IsItemToggledSelection ()
IMGUI_API ImVec2 ImGui::GetContentRegionMaxAbs ()
IMGUI_API void ImGui::ShrinkWidths (ImGuiShrinkWidthItem *items, int count, float width_excess)
bool ImGui::FocusableItemRegister (ImGuiWindow *window, ImGuiID id)
void ImGui::FocusableItemUnregister (ImGuiWindow *window)
IMGUI_API void ImGui::LogBegin (ImGuiLogType type, int auto_open_depth)
IMGUI_API void ImGui::LogToBuffer (int auto_open_depth=-1)
IMGUI_API void ImGui::LogRenderedText (const ImVec2 *ref_pos, const char *text, const char *text_end=NULL)
IMGUI_API void ImGui::LogSetNextTextDecoration (const char *prefix, const char *suffix)
IMGUI_API bool ImGui::BeginChildEx (const char *name, ImGuiID id, const ImVec2 &size_arg, bool border, ImGuiWindowFlags flags)
IMGUI_API void ImGui::OpenPopupEx (ImGuiID id, ImGuiPopupFlags popup_flags=ImGuiPopupFlags_None)
IMGUI_API void ImGui::ClosePopupToLevel (int remaining, bool restore_focus_to_window_under_popup)
IMGUI_API void ImGui::ClosePopupsOverWindow (ImGuiWindow *ref_window, bool restore_focus_to_window_under_popup)
IMGUI_API bool ImGui::IsPopupOpen (ImGuiID id, ImGuiPopupFlags popup_flags)
IMGUI_API bool ImGui::BeginPopupEx (ImGuiID id, ImGuiWindowFlags extra_flags)
IMGUI_API void ImGui::BeginTooltipEx (ImGuiWindowFlags extra_flags, ImGuiTooltipFlags tooltip_flags)
IMGUI_API ImGuiWindow * ImGui::GetTopMostPopupModal ()
IMGUI_API ImVec2 ImGui::FindBestWindowPosForPopup (ImGuiWindow *window)
IMGUI_API ImVec2 ImGui::FindBestWindowPosForPopupEx (const ImVec2 &ref_pos, const ImVec2 &size, ImGuiDir *last_dir, const ImRect &r_outer, const ImRect &r_avoid, ImGuiPopupPositionPolicy policy)
IMGUI_API bool ImGui::BeginViewportSideBar (const char *name, ImGuiViewport *viewport, ImGuiDir dir, float size, ImGuiWindowFlags window_flags)
IMGUI_API void ImGui::NavInitWindow (ImGuiWindow *window, bool force_reinit)
IMGUI_API bool ImGui::NavMoveRequestButNoResultYet ()
IMGUI_API void ImGui::NavMoveRequestCancel ()
IMGUI_API void ImGui::NavMoveRequestForward (ImGuiDir move_dir, ImGuiDir clip_dir, const ImRect &bb_rel, ImGuiNavMoveFlags move_flags)
IMGUI_API void ImGui::NavMoveRequestTryWrapping (ImGuiWindow *window, ImGuiNavMoveFlags move_flags)
IMGUI_API float ImGui::GetNavInputAmount (ImGuiNavInput n, ImGuiInputReadMode mode)
IMGUI_API ImVec2 ImGui::GetNavInputAmount2d (ImGuiNavDirSourceFlags dir_sources, ImGuiInputReadMode mode, float slow_factor=0.0f, float fast_factor=0.0f)
IMGUI_API int ImGui::CalcTypematicRepeatAmount (float t0, float t1, float repeat_delay, float repeat_rate)
IMGUI_API void ImGui::ActivateItem (ImGuiID id)
IMGUI_API void ImGui::SetNavID (ImGuiID id, ImGuiNavLayer nav_layer, ImGuiID focus_scope_id, const ImRect &rect_rel)
IMGUI_API void ImGui::PushFocusScope (ImGuiID id)
IMGUI_API void ImGui::PopFocusScope ()
ImGuiID ImGui::GetFocusedFocusScope ()
ImGuiID ImGui::GetFocusScope ()
IMGUI_API void ImGui::SetItemUsingMouseWheel ()
bool ImGui::IsActiveIdUsingNavDir (ImGuiDir dir)
bool ImGui::IsActiveIdUsingNavInput (ImGuiNavInput input)
bool ImGui::IsActiveIdUsingKey (ImGuiKey key)
IMGUI_API bool ImGui::IsMouseDragPastThreshold (ImGuiMouseButton button, float lock_threshold=-1.0f)
bool ImGui::IsKeyPressedMap (ImGuiKey key, bool repeat=true)
bool ImGui::IsNavInputDown (ImGuiNavInput n)
bool ImGui::IsNavInputTest (ImGuiNavInput n, ImGuiInputReadMode rm)
IMGUI_API ImGuiKeyModFlags ImGui::GetMergedKeyModFlags ()
IMGUI_API bool ImGui::BeginDragDropTargetCustom (const ImRect &bb, ImGuiID id)
IMGUI_API void ImGui::ClearDragDrop ()
IMGUI_API bool ImGui::IsDragDropPayloadBeingAccepted ()
IMGUI_API void ImGui::SetWindowClipRectBeforeSetChannel (ImGuiWindow *window, const ImRect &clip_rect)
IMGUI_API void ImGui::BeginColumns (const char *str_id, int count, ImGuiOldColumnFlags flags=0)
IMGUI_API void ImGui::EndColumns ()
IMGUI_API void ImGui::PushColumnClipRect (int column_index)
IMGUI_API void ImGui::PushColumnsBackground ()
IMGUI_API void ImGui::PopColumnsBackground ()
IMGUI_API ImGuiID ImGui::GetColumnsID (const char *str_id, int count)
IMGUI_API ImGuiOldColumns * ImGui::FindOrCreateColumns (ImGuiWindow *window, ImGuiID id)
IMGUI_API float ImGui::GetColumnOffsetFromNorm (const ImGuiOldColumns *columns, float offset_norm)
IMGUI_API float ImGui::GetColumnNormFromOffset (const ImGuiOldColumns *columns, float offset)
IMGUI_API void ImGui::TableOpenContextMenu (int column_n=-1)
IMGUI_API void ImGui::TableSetColumnWidth (int column_n, float width)
IMGUI_API void ImGui::TableSetColumnSortDirection (int column_n, ImGuiSortDirection sort_direction, bool append_to_sort_specs)
IMGUI_API int ImGui::TableGetHoveredColumn ()
IMGUI_API float ImGui::TableGetHeaderRowHeight ()
IMGUI_API void ImGui::TablePushBackgroundChannel ()
IMGUI_API void ImGui::TablePopBackgroundChannel ()
ImGuiTable * ImGui::GetCurrentTable ()
IMGUI_API ImGuiTable * ImGui::TableFindByID (ImGuiID id)
IMGUI_API bool ImGui::BeginTableEx (const char *name, ImGuiID id, int columns_count, ImGuiTableFlags flags=0, const ImVec2 &outer_size=ImVec2(0, 0), float inner_width=0.0f)
IMGUI_API void ImGui::TableBeginInitMemory (ImGuiTable *table, int columns_count)
IMGUI_API void ImGui::TableBeginApplyRequests (ImGuiTable *table)
IMGUI_API void ImGui::TableSetupDrawChannels (ImGuiTable *table)
IMGUI_API void ImGui::TableUpdateLayout (ImGuiTable *table)
IMGUI_API void ImGui::TableUpdateBorders (ImGuiTable *table)
IMGUI_API void ImGui::TableUpdateColumnsWeightFromWidth (ImGuiTable *table)
IMGUI_API void ImGui::TableDrawBorders (ImGuiTable *table)
IMGUI_API void ImGui::TableDrawContextMenu (ImGuiTable *table)
IMGUI_API void ImGui::TableMergeDrawChannels (ImGuiTable *table)
IMGUI_API void ImGui::TableSortSpecsSanitize (ImGuiTable *table)
IMGUI_API void ImGui::TableSortSpecsBuild (ImGuiTable *table)
IMGUI_API ImGuiSortDirection ImGui::TableGetColumnNextSortDirection (ImGuiTableColumn *column)
IMGUI_API void ImGui::TableFixColumnSortDirection (ImGuiTable *table, ImGuiTableColumn *column)
IMGUI_API float ImGui::TableGetColumnWidthAuto (ImGuiTable *table, ImGuiTableColumn *column)
IMGUI_API void ImGui::TableBeginRow (ImGuiTable *table)
IMGUI_API void ImGui::TableEndRow (ImGuiTable *table)
IMGUI_API void ImGui::TableBeginCell (ImGuiTable *table, int column_n)
IMGUI_API void ImGui::TableEndCell (ImGuiTable *table)
IMGUI_API ImRect ImGui::TableGetCellBgRect (const ImGuiTable *table, int column_n)
IMGUI_API const char * ImGui::TableGetColumnName (const ImGuiTable *table, int column_n)
IMGUI_API ImGuiID ImGui::TableGetColumnResizeID (const ImGuiTable *table, int column_n, int instance_no=0)
IMGUI_API float ImGui::TableGetMaxColumnWidth (const ImGuiTable *table, int column_n)
IMGUI_API void ImGui::TableSetColumnWidthAutoSingle (ImGuiTable *table, int column_n)
IMGUI_API void ImGui::TableSetColumnWidthAutoAll (ImGuiTable *table)
IMGUI_API void ImGui::TableRemove (ImGuiTable *table)
IMGUI_API void ImGui::TableGcCompactTransientBuffers (ImGuiTable *table)
IMGUI_API void ImGui::TableGcCompactTransientBuffers (ImGuiTableTempData *table)
IMGUI_API void ImGui::TableGcCompactSettings ()
IMGUI_API void ImGui::TableLoadSettings (ImGuiTable *table)
IMGUI_API void ImGui::TableSaveSettings (ImGuiTable *table)
IMGUI_API void ImGui::TableResetSettings (ImGuiTable *table)
IMGUI_API ImGuiTableSettings * ImGui::TableGetBoundSettings (ImGuiTable *table)
IMGUI_API void ImGui::TableSettingsInstallHandler (ImGuiContext *context)
IMGUI_API ImGuiTableSettings * ImGui::TableSettingsCreate (ImGuiID id, int columns_count)
IMGUI_API ImGuiTableSettings * ImGui::TableSettingsFindByID (ImGuiID id)
IMGUI_API bool ImGui::BeginTabBarEx (ImGuiTabBar *tab_bar, const ImRect &bb, ImGuiTabBarFlags flags)
IMGUI_API ImGuiTabItem * ImGui::TabBarFindTabByID (ImGuiTabBar *tab_bar, ImGuiID tab_id)
IMGUI_API void ImGui::TabBarRemoveTab (ImGuiTabBar *tab_bar, ImGuiID tab_id)
IMGUI_API void ImGui::TabBarCloseTab (ImGuiTabBar *tab_bar, ImGuiTabItem *tab)
IMGUI_API void ImGui::TabBarQueueReorder (ImGuiTabBar *tab_bar, const ImGuiTabItem *tab, int offset)
IMGUI_API void ImGui::TabBarQueueReorderFromMousePos (ImGuiTabBar *tab_bar, const ImGuiTabItem *tab, ImVec2 mouse_pos)
IMGUI_API bool ImGui::TabBarProcessReorder (ImGuiTabBar *tab_bar)
IMGUI_API bool ImGui::TabItemEx (ImGuiTabBar *tab_bar, const char *label, bool *p_open, ImGuiTabItemFlags flags)
IMGUI_API ImVec2 ImGui::TabItemCalcSize (const char *label, bool has_close_button)
IMGUI_API void ImGui::TabItemBackground (ImDrawList *draw_list, const ImRect &bb, ImGuiTabItemFlags flags, ImU32 col)
IMGUI_API void ImGui::TabItemLabelAndCloseButton (ImDrawList *draw_list, const ImRect &bb, ImGuiTabItemFlags flags, ImVec2 frame_padding, const char *label, ImGuiID tab_id, ImGuiID close_button_id, bool is_contents_visible, bool *out_just_closed, bool *out_text_clipped)
IMGUI_API void ImGui::RenderText (ImVec2 pos, const char *text, const char *text_end=NULL, bool hide_text_after_hash=true)
IMGUI_API void ImGui::RenderTextWrapped (ImVec2 pos, const char *text, const char *text_end, float wrap_width)
IMGUI_API void ImGui::RenderTextClipped (const ImVec2 &pos_min, const ImVec2 &pos_max, const char *text, const char *text_end, const ImVec2 *text_size_if_known, const ImVec2 &align=ImVec2(0, 0), const ImRect *clip_rect=NULL)
IMGUI_API void ImGui::RenderTextClippedEx (ImDrawList *draw_list, const ImVec2 &pos_min, const ImVec2 &pos_max, const char *text, const char *text_end, const ImVec2 *text_size_if_known, const ImVec2 &align=ImVec2(0, 0), const ImRect *clip_rect=NULL)
IMGUI_API void ImGui::RenderTextEllipsis (ImDrawList *draw_list, const ImVec2 &pos_min, const ImVec2 &pos_max, float clip_max_x, float ellipsis_max_x, const char *text, const char *text_end, const ImVec2 *text_size_if_known)
IMGUI_API void ImGui::RenderFrame (ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, bool border=true, float rounding=0.0f)
IMGUI_API void ImGui::RenderFrameBorder (ImVec2 p_min, ImVec2 p_max, float rounding=0.0f)
IMGUI_API void ImGui::RenderColorRectWithAlphaCheckerboard (ImDrawList *draw_list, ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, float grid_step, ImVec2 grid_off, float rounding=0.0f, ImDrawFlags flags=0)
IMGUI_API void ImGui::RenderNavHighlight (const ImRect &bb, ImGuiID id, ImGuiNavHighlightFlags flags=ImGuiNavHighlightFlags_TypeDefault)
IMGUI_API const char * ImGui::FindRenderedTextEnd (const char *text, const char *text_end=NULL)
IMGUI_API void ImGui::RenderArrow (ImDrawList *draw_list, ImVec2 pos, ImU32 col, ImGuiDir dir, float scale=1.0f)
IMGUI_API void ImGui::RenderBullet (ImDrawList *draw_list, ImVec2 pos, ImU32 col)
IMGUI_API void ImGui::RenderCheckMark (ImDrawList *draw_list, ImVec2 pos, ImU32 col, float sz)
IMGUI_API void ImGui::RenderMouseCursor (ImDrawList *draw_list, ImVec2 pos, float scale, ImGuiMouseCursor mouse_cursor, ImU32 col_fill, ImU32 col_border, ImU32 col_shadow)
IMGUI_API void ImGui::RenderArrowPointingAt (ImDrawList *draw_list, ImVec2 pos, ImVec2 half_sz, ImGuiDir direction, ImU32 col)
IMGUI_API void ImGui::RenderRectFilledRangeH (ImDrawList *draw_list, const ImRect &rect, ImU32 col, float x_start_norm, float x_end_norm, float rounding)
IMGUI_API void ImGui::RenderRectFilledWithHole (ImDrawList *draw_list, ImRect outer, ImRect inner, ImU32 col, float rounding)
void ImGui::RenderArrow (ImVec2 pos, ImGuiDir dir, float scale=1.0f)
void ImGui::RenderBullet (ImVec2 pos)
IMGUI_API void ImGui::TextEx (const char *text, const char *text_end=NULL, ImGuiTextFlags flags=0)
IMGUI_API bool ImGui::ButtonEx (const char *label, const ImVec2 &size_arg=ImVec2(0, 0), ImGuiButtonFlags flags=0)
IMGUI_API bool ImGui::CloseButton (ImGuiID id, const ImVec2 &pos)
IMGUI_API bool ImGui::CollapseButton (ImGuiID id, const ImVec2 &pos)
IMGUI_API bool ImGui::ArrowButtonEx (const char *str_id, ImGuiDir dir, ImVec2 size_arg, ImGuiButtonFlags flags=0)
IMGUI_API void ImGui::Scrollbar (ImGuiAxis axis)
IMGUI_API bool ImGui::ScrollbarEx (const ImRect &bb, ImGuiID id, ImGuiAxis axis, float *p_scroll_v, float avail_v, float contents_v, ImDrawFlags flags)
IMGUI_API bool ImGui::ImageButtonEx (ImGuiID id, ImTextureID texture_id, const ImVec2 &size, const ImVec2 &uv0, const ImVec2 &uv1, const ImVec2 &padding, const ImVec4 &bg_col, const ImVec4 &tint_col)
IMGUI_API ImRect ImGui::GetWindowScrollbarRect (ImGuiWindow *window, ImGuiAxis axis)
IMGUI_API ImGuiID ImGui::GetWindowScrollbarID (ImGuiWindow *window, ImGuiAxis axis)
IMGUI_API ImGuiID ImGui::GetWindowResizeCornerID (ImGuiWindow *window, int n)
IMGUI_API ImGuiID ImGui::GetWindowResizeBorderID (ImGuiWindow *window, ImGuiDir dir)
IMGUI_API void ImGui::SeparatorEx (ImGuiSeparatorFlags flags)
IMGUI_API bool ImGui::CheckboxFlags (const char *label, ImS64 *flags, ImS64 flags_value)
IMGUI_API bool ImGui::CheckboxFlags (const char *label, ImU64 *flags, ImU64 flags_value)
IMGUI_API bool ImGui::ButtonBehavior (const ImRect &bb, ImGuiID id, bool *out_hovered, bool *out_held, ImGuiButtonFlags flags=0)
IMGUI_API bool ImGui::DragBehavior (ImGuiID id, ImGuiDataType data_type, void *p_v, float v_speed, const void *p_min, const void *p_max, const char *format, ImGuiSliderFlags flags)
IMGUI_API bool ImGui::SliderBehavior (const ImRect &bb, ImGuiID id, ImGuiDataType data_type, void *p_v, const void *p_min, const void *p_max, const char *format, ImGuiSliderFlags flags, ImRect *out_grab_bb)
IMGUI_API bool ImGui::SplitterBehavior (const ImRect &bb, ImGuiID id, ImGuiAxis axis, float *size1, float *size2, float min_size1, float min_size2, float hover_extend=0.0f, float hover_visibility_delay=0.0f)
IMGUI_API bool ImGui::TreeNodeBehavior (ImGuiID id, ImGuiTreeNodeFlags flags, const char *label, const char *label_end=NULL)
IMGUI_API bool ImGui::TreeNodeBehaviorIsOpen (ImGuiID id, ImGuiTreeNodeFlags flags=0)
IMGUI_API void ImGui::TreePushOverrideID (ImGuiID id)
template<typename T , typename SIGNED_T , typename FLOAT_T >
IMGUI_API float ImGui::ScaleRatioFromValueT (ImGuiDataType data_type, T v, T v_min, T v_max, bool is_logarithmic, float logarithmic_zero_epsilon, float zero_deadzone_size)
template<typename T , typename SIGNED_T , typename FLOAT_T >
IMGUI_API T ImGui::ScaleValueFromRatioT (ImGuiDataType data_type, float t, T v_min, T v_max, bool is_logarithmic, float logarithmic_zero_epsilon, float zero_deadzone_size)
template<typename T , typename SIGNED_T , typename FLOAT_T >
IMGUI_API bool ImGui::DragBehaviorT (ImGuiDataType data_type, T *v, float v_speed, T v_min, T v_max, const char *format, ImGuiSliderFlags flags)
template<typename T , typename SIGNED_T , typename FLOAT_T >
IMGUI_API bool ImGui::SliderBehaviorT (const ImRect &bb, ImGuiID id, ImGuiDataType data_type, T *v, T v_min, T v_max, const char *format, ImGuiSliderFlags flags, ImRect *out_grab_bb)
template<typename T , typename SIGNED_T >
IMGUI_API T ImGui::RoundScalarWithFormatT (const char *format, ImGuiDataType data_type, T v)
template<typename T >
IMGUI_API bool ImGui::CheckboxFlagsT (const char *label, T *flags, T flags_value)
IMGUI_API const ImGuiDataTypeInfo * ImGui::DataTypeGetInfo (ImGuiDataType data_type)
IMGUI_API int ImGui::DataTypeFormatString (char *buf, int buf_size, ImGuiDataType data_type, const void *p_data, const char *format)
IMGUI_API void ImGui::DataTypeApplyOp (ImGuiDataType data_type, int op, void *output, const void *arg_1, const void *arg_2)
IMGUI_API bool ImGui::DataTypeApplyOpFromText (const char *buf, const char *initial_value_buf, ImGuiDataType data_type, void *p_data, const char *format)
IMGUI_API int ImGui::DataTypeCompare (ImGuiDataType data_type, const void *arg_1, const void *arg_2)
IMGUI_API bool ImGui::DataTypeClamp (ImGuiDataType data_type, void *p_data, const void *p_min, const void *p_max)
IMGUI_API bool ImGui::InputTextEx (const char *label, const char *hint, char *buf, int buf_size, const ImVec2 &size_arg, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback=NULL, void *user_data=NULL)
IMGUI_API bool ImGui::TempInputText (const ImRect &bb, ImGuiID id, const char *label, char *buf, int buf_size, ImGuiInputTextFlags flags)
IMGUI_API bool ImGui::TempInputScalar (const ImRect &bb, ImGuiID id, const char *label, ImGuiDataType data_type, void *p_data, const char *format, const void *p_clamp_min=NULL, const void *p_clamp_max=NULL)
bool ImGui::TempInputIsActive (ImGuiID id)
ImGuiInputTextState * ImGui::GetInputTextState (ImGuiID id)
IMGUI_API void ImGui::ColorTooltip (const char *text, const float *col, ImGuiColorEditFlags flags)
IMGUI_API void ImGui::ColorEditOptionsPopup (const float *col, ImGuiColorEditFlags flags)
IMGUI_API void ImGui::ColorPickerOptionsPopup (const float *ref_col, ImGuiColorEditFlags flags)
IMGUI_API int ImGui::PlotEx (ImGuiPlotType plot_type, const char *label, float(*values_getter)(void *data, int idx), void *data, int values_count, int values_offset, const char *overlay_text, float scale_min, float scale_max, ImVec2 frame_size)
IMGUI_API void ImGui::ShadeVertsLinearColorGradientKeepAlpha (ImDrawList *draw_list, int vert_start_idx, int vert_end_idx, ImVec2 gradient_p0, ImVec2 gradient_p1, ImU32 col0, ImU32 col1)
IMGUI_API void ImGui::ShadeVertsLinearUV (ImDrawList *draw_list, int vert_start_idx, int vert_end_idx, const ImVec2 &a, const ImVec2 &b, const ImVec2 &uv_a, const ImVec2 &uv_b, bool clamp)
IMGUI_API void ImGui::GcCompactTransientMiscBuffers ()
IMGUI_API void ImGui::GcCompactTransientWindowBuffers (ImGuiWindow *window)
IMGUI_API void ImGui::GcAwakeTransientWindowBuffers (ImGuiWindow *window)
IMGUI_API void ImGui::ErrorCheckEndFrameRecover (ImGuiErrorLogCallback log_callback, void *user_data=NULL)
void ImGui::DebugDrawItemRect (ImU32 col=IM_COL32(255, 0, 0, 255))
void ImGui::DebugStartItemPicker ()
IMGUI_API void ImGui::DebugNodeColumns (ImGuiOldColumns *columns)
IMGUI_API void ImGui::DebugNodeDrawList (ImGuiWindow *window, const ImDrawList *draw_list, const char *label)
IMGUI_API void ImGui::DebugNodeDrawCmdShowMeshAndBoundingBox (ImDrawList *out_draw_list, const ImDrawList *draw_list, const ImDrawCmd *draw_cmd, bool show_mesh, bool show_aabb)
IMGUI_API void ImGui::DebugNodeStorage (ImGuiStorage *storage, const char *label)
IMGUI_API void ImGui::DebugNodeTabBar (ImGuiTabBar *tab_bar, const char *label)
IMGUI_API void ImGui::DebugNodeTable (ImGuiTable *table)
IMGUI_API void ImGui::DebugNodeTableSettings (ImGuiTableSettings *settings)
IMGUI_API void ImGui::DebugNodeWindow (ImGuiWindow *window, const char *label)
IMGUI_API void ImGui::DebugNodeWindowSettings (ImGuiWindowSettings *settings)
IMGUI_API void ImGui::DebugNodeWindowsList (ImVector< ImGuiWindow * > *windows, const char *label)
IMGUI_API void ImGui::DebugNodeViewport (ImGuiViewportP *viewport)
IMGUI_API void ImGui::DebugRenderViewportThumbnail (ImDrawList *draw_list, ImGuiViewportP *viewport, const ImRect &bb)
IMGUI_API const ImFontBuilderIO * ImFontAtlasGetBuilderForStbTruetype ()
IMGUI_API void ImFontAtlasBuildInit (ImFontAtlas *atlas)
IMGUI_API void ImFontAtlasBuildSetupFont (ImFontAtlas *atlas, ImFont *font, ImFontConfig *font_config, float ascent, float descent)
IMGUI_API void ImFontAtlasBuildPackCustomRects (ImFontAtlas *atlas, void *stbrp_context_opaque)
IMGUI_API void ImFontAtlasBuildFinish (ImFontAtlas *atlas)
IMGUI_API void ImFontAtlasBuildRender8bppRectFromString (ImFontAtlas *atlas, int x, int y, int w, int h, const char *in_str, char in_marker_char, unsigned char in_marker_pixel_value)
IMGUI_API void ImFontAtlasBuildRender32bppRectFromString (ImFontAtlas *atlas, int x, int y, int w, int h, const char *in_str, char in_marker_char, unsigned int in_marker_pixel_value)
IMGUI_API void ImFontAtlasBuildMultiplyCalcLookupTable (unsigned char out_table[256], float in_multiply_factor)
IMGUI_API void ImFontAtlasBuildMultiplyRectAlpha8 (const unsigned char table[256], unsigned char *pixels, int x, int y, int w, int h, int stride)
Variables
IMGUI_API ImGuiContext * GImGui
Class Documentation
ImGuiDataTypeTempStorage
struct ImGuiDataTypeTempStorage
Class Members
ImU8 Data[8]
ImGuiDataTypeInfo
struct ImGuiDataTypeInfo
Class Members
const char * Name
const char * PrintFmt
const char * ScanFmt
size_t Size
ImGuiColorMod
struct ImGuiColorMod
Class Members
ImVec4 BackupValue
ImGuiCol Col
ImGuiGroupData
struct ImGuiGroupData
Class Members
ImGuiID BackupActiveIdIsAlive
bool BackupActiveIdPreviousFrameIsAlive
ImVec2 BackupCurrLineSize
float BackupCurrLineTextBaseOffset
ImVec2 BackupCursorMaxPos
ImVec2 BackupCursorPos
ImVec1 BackupGroupOffset
bool BackupHoveredIdIsAlive
ImVec1 BackupIndent
bool EmitItem
ImGuiID WindowID
ImGuiShrinkWidthItem
struct ImGuiShrinkWidthItem
Class Members
int Index
float Width
ImGuiWindowTempData
struct ImGuiWindowTempData
Class Members
ImVector< ImGuiWindow * > ChildWindows
ImVec1 ColumnsOffset
ImGuiOldColumns * CurrentColumns
int CurrentTableIdx
ImVec2 CurrLineSize
float CurrLineTextBaseOffset
ImVec2 CursorMaxPos
ImVec2 CursorPos
ImVec2 CursorPosPrevLine
ImVec2 CursorStartPos
int FocusCounterRegular
int FocusCounterTabStop
ImVec1 GroupOffset
ImVec2 IdealMaxPos
ImVec1 Indent
float ItemWidth
ImVector< float > ItemWidthStack
ImRect LastItemDisplayRect
ImGuiID LastItemId
ImRect LastItemRect
ImGuiItemStatusFlags LastItemStatusFlags
ImGuiLayoutType LayoutType
bool MenuBarAppending
ImVec2 MenuBarOffset
ImGuiMenuColumns MenuColumns
ImGuiID NavFocusScopeIdCurrent
bool NavHasScroll
bool NavHideHighlightOneFrame
ImGuiNavLayer NavLayerCurrent
short NavLayersActiveMask
short NavLayersActiveMaskNext
ImGuiLayoutType ParentLayoutType
ImVec2 PrevLineSize
float PrevLineTextBaseOffset
ImGuiStackSizes StackSizesOnBegin
ImGuiStorage * StateStorage
float TextWrapPos
ImVector< float > TextWrapPosStack
int TreeDepth
ImU32 TreeJumpToParentOnPopMask
ImGuiTableCellData
struct ImGuiTableCellData
Class Members
ImU32 BgColor
ImGuiTableColumnIdx Column
ImGuiStyleMod.__unnamed672__
union ImGuiStyleMod.__unnamed672__
Class Members
float BackupFloat[2]
int BackupInt[2]
Macro Definition Documentation
IM_ASSERT_PARANOID
#define IM_ASSERT_PARANOID (_EXPR)
IM_ASSERT_USER_ERROR
#define IM_ASSERT_USER_ERROR (_EXP, _MSG) IM_ASSERT((_EXP) && _MSG)
IM_COL32_DISABLE
#define IM_COL32_DISABLE IM_COL32(0,0,0,1)
IM_DEBUG_BREAK
#define IM_DEBUG_BREAK () IM_ASSERT(0)
IM_DRAWLIST_ARCFAST_SAMPLE_MAX
#define IM_DRAWLIST_ARCFAST_SAMPLE_MAX IM_DRAWLIST_ARCFAST_TABLE_SIZE
IM_DRAWLIST_ARCFAST_TABLE_SIZE
#define IM_DRAWLIST_ARCFAST_TABLE_SIZE 48
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC (_RAD, _MAXERROR) ImClamp(IM_ROUNDUP_TO_EVEN((int)ImCeil(IM_PI / ImAcos(1 - ImMin((_MAXERROR), (_RAD)) / (_RAD)))), IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN, IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX)
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_ERROR
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_ERROR (_N, _RAD) ((1 - ImCos(IM_PI / ImMax((float)(_N), IM_PI))) / (_RAD))
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_R
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_R (_N, _MAXERROR) ((_MAXERROR) / (1 - ImCos(IM_PI / ImMax((float)(_N), IM_PI))))
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX 512
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN 4
IM_F32_TO_INT8_SAT
#define IM_F32_TO_INT8_SAT (_VAL) ((int)(ImSaturate(_VAL) * 255.0f + 0.5f))
IM_F32_TO_INT8_UNBOUND
#define IM_F32_TO_INT8_UNBOUND (_VAL) ((int)((_VAL) * 255.0f + ((_VAL)>=0 ? 0.5f : -0.5f)))
IM_FLOOR
#define IM_FLOOR (_VAL) ((float)(int)(_VAL))
IM_MEMALIGN
#define IM_MEMALIGN (_OFF, _ALIGN) (((_OFF) + (_ALIGN - 1)) & ~(_ALIGN - 1))
IM_MSVC_WARNING_SUPPRESS
#define IM_MSVC_WARNING_SUPPRESS (XXXX)
IM_NEWLINE
#define IM_NEWLINE "\n"
IM_PI
#define IM_PI 3.14159265358979323846f
IM_ROUND
#define IM_ROUND (_VAL) ((float)(int)((_VAL) + 0.5f))
IM_ROUNDUP_TO_EVEN
#define IM_ROUNDUP_TO_EVEN (_V) ((((_V) + 1) / 2) * 2)
IM_STATIC_ASSERT
#define IM_STATIC_ASSERT (_COND) typedef char static_assertion_##__line__[(_COND)?1:-1]
IM_TABSIZE
#define IM_TABSIZE (4)
ImAcos
#define ImAcos (X) acosf(X)
ImAtan2
#define ImAtan2 (Y, X) atan2f((Y), (X))
ImAtof
#define ImAtof (STR) atof(STR)
ImCeil
#define ImCeil (X) ceilf(X)
ImCos
#define ImCos (X) cosf(X)
ImFabs
#define ImFabs (X) fabsf(X)
ImFmod
#define ImFmod (X, Y) fmodf((X), (Y))
IMGUI_CDECL
#define IMGUI_CDECL
IMGUI_DEBUG_LOG
#define IMGUI_DEBUG_LOG (_FMT, ...) printf("[%05d] " _FMT, GImGui->FrameCount, __VA_ARGS__)
IMGUI_DEBUG_LOG_NAV
#define IMGUI_DEBUG_LOG_NAV (...) ((void)0)
IMGUI_DEBUG_LOG_POPUP
#define IMGUI_DEBUG_LOG_POPUP (...) ((void)0)
IMGUI_ENABLE_STB_TRUETYPE
#define IMGUI_ENABLE_STB_TRUETYPE
IMGUI_TABLE_MAX_COLUMNS
#define IMGUI_TABLE_MAX_COLUMNS 64
IMGUI_TABLE_MAX_DRAW_CHANNELS
#define IMGUI_TABLE_MAX_DRAW_CHANNELS (4 + 64 * 2)
IMGUI_TEST_ENGINE_ID_INFO
#define IMGUI_TEST_ENGINE_ID_INFO (_ID, _TYPE, _DATA) do { } while (0)
IMGUI_TEST_ENGINE_ID_INFO2
#define IMGUI_TEST_ENGINE_ID_INFO2 (_ID, _TYPE, _DATA, _DATA2) do { } while (0)
IMGUI_TEST_ENGINE_ITEM_ADD
#define IMGUI_TEST_ENGINE_ITEM_ADD (_BB, _ID) do { } while (0)
IMGUI_TEST_ENGINE_ITEM_INFO
#define IMGUI_TEST_ENGINE_ITEM_INFO (_ID, _LABEL, _FLAGS) do { } while (0)
IMGUI_TEST_ENGINE_LOG
#define IMGUI_TEST_ENGINE_LOG (_FMT, ...) do { } while (0)
ImQsort
#define ImQsort qsort
ImSin
#define ImSin (X) sinf(X)
ImSqrt
#define ImSqrt (X) sqrtf(X)
STB_TEXTEDIT_CHARTYPE
#define STB_TEXTEDIT_CHARTYPE ImWchar
STB_TEXTEDIT_GETWIDTH_NEWLINE
#define STB_TEXTEDIT_GETWIDTH_NEWLINE (-1.0f)
STB_TEXTEDIT_STRING
#define STB_TEXTEDIT_STRING ImGuiInputTextState
STB_TEXTEDIT_UNDOCHARCOUNT
#define STB_TEXTEDIT_UNDOCHARCOUNT 999
STB_TEXTEDIT_UNDOSTATECOUNT
#define STB_TEXTEDIT_UNDOSTATECOUNT 99
Typedef Documentation
ImFileHandle
typedef FILE* ImFileHandle
ImGuiContextHookCallback
typedef void(* ImGuiContextHookCallback) (ImGuiContext *ctx, ImGuiContextHook *hook)
ImGuiErrorLogCallback
typedef void(* ImGuiErrorLogCallback) (void *user_data, const char *fmt,...)
ImGuiItemAddFlags
typedef int ImGuiItemAddFlags
ImGuiItemFlags
typedef int ImGuiItemFlags
ImGuiItemStatusFlags
typedef int ImGuiItemStatusFlags
ImGuiLayoutType
typedef int ImGuiLayoutType
ImGuiNavDirSourceFlags
typedef int ImGuiNavDirSourceFlags
ImGuiNavHighlightFlags
typedef int ImGuiNavHighlightFlags
ImGuiNavMoveFlags
typedef int ImGuiNavMoveFlags
ImGuiNextItemDataFlags
typedef int ImGuiNextItemDataFlags
ImGuiNextWindowDataFlags
typedef int ImGuiNextWindowDataFlags
ImGuiOldColumnFlags
typedef int ImGuiOldColumnFlags
ImGuiSeparatorFlags
typedef int ImGuiSeparatorFlags
ImGuiTableColumnIdx
typedef ImS8 ImGuiTableColumnIdx
ImGuiTableDrawChannelIdx
typedef ImU8 ImGuiTableDrawChannelIdx
ImGuiTextFlags
typedef int ImGuiTextFlags
ImGuiTooltipFlags
typedef int ImGuiTooltipFlags
ImPoolIdx
typedef int ImPoolIdx
Enumeration Type Documentation
ImGuiAxis
enum ImGuiAxis
Enumerator
ImGuiAxis_None
ImGuiAxis_X
ImGuiAxis_Y
{
    ImGuiAxis_None = -1,
    ImGuiAxis_X = 0,
    ImGuiAxis_Y = 1
};
ImGuiButtonFlagsPrivate_
enum ImGuiButtonFlagsPrivate_
Enumerator
ImGuiButtonFlags_PressedOnClick
ImGuiButtonFlags_PressedOnClickRelease
ImGuiButtonFlags_PressedOnClickReleaseAnywhere
ImGuiButtonFlags_PressedOnRelease
ImGuiButtonFlags_PressedOnDoubleClick
ImGuiButtonFlags_PressedOnDragDropHold
ImGuiButtonFlags_Repeat
ImGuiButtonFlags_FlattenChildren
ImGuiButtonFlags_AllowItemOverlap
ImGuiButtonFlags_DontClosePopups
ImGuiButtonFlags_Disabled
ImGuiButtonFlags_AlignTextBaseLine
ImGuiButtonFlags_NoKeyModifiers
ImGuiButtonFlags_NoHoldingActiveId
ImGuiButtonFlags_NoNavFocus
ImGuiButtonFlags_NoHoveredOnFocus
ImGuiButtonFlags_PressedOnMask_
ImGuiButtonFlags_PressedOnDefault_
{
    ImGuiButtonFlags_PressedOnClick         = 1 << 4,   // return true on click (mouse down event)
    ImGuiButtonFlags_PressedOnClickRelease  = 1 << 5,   // [Default] return true on click + release on same item <-- this is what the majority of Button are using
    ImGuiButtonFlags_PressedOnClickReleaseAnywhere = 1 << 6, // return true on click + release even if the release event is not done while hovering the item
    ImGuiButtonFlags_PressedOnRelease       = 1 << 7,   // return true on release (default requires click+release)
    ImGuiButtonFlags_PressedOnDoubleClick   = 1 << 8,   // return true on double-click (default requires click+release)
    ImGuiButtonFlags_PressedOnDragDropHold  = 1 << 9,   // return true when held into while we are drag and dropping another item (used by e.g. tree nodes, collapsing headers)
    ImGuiButtonFlags_Repeat                 = 1 << 10,  // hold to repeat
    ImGuiButtonFlags_FlattenChildren        = 1 << 11,  // allow interactions even if a child window is overlapping
    ImGuiButtonFlags_AllowItemOverlap       = 1 << 12,  // require previous frame HoveredId to either match id or be null before being usable, use along with SetItemAllowOverlap()
    ImGuiButtonFlags_DontClosePopups        = 1 << 13,  // disable automatically closing parent popup on press // [UNUSED]
    ImGuiButtonFlags_Disabled               = 1 << 14,  // disable interactions
    ImGuiButtonFlags_AlignTextBaseLine      = 1 << 15,  // vertically align button to match text baseline - ButtonEx() only // FIXME: Should be removed and handled by SmallButton(), not possible currently because of DC.CursorPosPrevLine
    ImGuiButtonFlags_NoKeyModifiers         = 1 << 16,  // disable mouse interaction if a key modifier is held
    ImGuiButtonFlags_NoHoldingActiveId      = 1 << 17,  // don't set ActiveId while holding the mouse (ImGuiButtonFlags_PressedOnClick only)
    ImGuiButtonFlags_NoNavFocus             = 1 << 18,  // don't override navigation focus when activated
    ImGuiButtonFlags_NoHoveredOnFocus       = 1 << 19,  // don't report as hovered when nav focus is on this item
    ImGuiButtonFlags_PressedOnMask_         = ImGuiButtonFlags_PressedOnClick | ImGuiButtonFlags_PressedOnClickRelease | ImGuiButtonFlags_PressedOnClickReleaseAnywhere | ImGuiButtonFlags_PressedOnRelease | ImGuiButtonFlags_PressedOnDoubleClick | ImGuiButtonFlags_PressedOnDragDropHold,
    ImGuiButtonFlags_PressedOnDefault_      = ImGuiButtonFlags_PressedOnClickRelease
};
ImGuiContextHookType
enum ImGuiContextHookType
Enumerator
ImGuiContextHookType_NewFramePre
ImGuiContextHookType_NewFramePost
ImGuiContextHookType_EndFramePre
ImGuiContextHookType_EndFramePost
ImGuiContextHookType_RenderPre
ImGuiContextHookType_RenderPost
ImGuiContextHookType_Shutdown
ImGuiContextHookType_PendingRemoval_
{ ImGuiContextHookType_NewFramePre, ImGuiContextHookType_NewFramePost, ImGuiContextHookType_EndFramePre, ImGuiContextHookType_EndFramePost, ImGuiContextHookType_RenderPre, ImGuiContextHookType_RenderPost, ImGuiContextHookType_Shutdown, ImGuiContextHookType_PendingRemoval_ };
ImGuiDataTypePrivate_
enum ImGuiDataTypePrivate_
Enumerator
ImGuiDataType_String
ImGuiDataType_Pointer
ImGuiDataType_ID
{
    ImGuiDataType_String = ImGuiDataType_COUNT + 1,
    ImGuiDataType_Pointer,
    ImGuiDataType_ID
};
ImGuiInputReadMode
enum ImGuiInputReadMode
Enumerator
ImGuiInputReadMode_Down
ImGuiInputReadMode_Pressed
ImGuiInputReadMode_Released
ImGuiInputReadMode_Repeat
ImGuiInputReadMode_RepeatSlow
ImGuiInputReadMode_RepeatFast
{
    ImGuiInputReadMode_Down,
    ImGuiInputReadMode_Pressed,
    ImGuiInputReadMode_Released,
    ImGuiInputReadMode_Repeat,
    ImGuiInputReadMode_RepeatSlow,
    ImGuiInputReadMode_RepeatFast
};
ImGuiInputSource
enum ImGuiInputSource
Enumerator
ImGuiInputSource_None
ImGuiInputSource_Mouse
ImGuiInputSource_Keyboard
ImGuiInputSource_Gamepad
ImGuiInputSource_Nav
ImGuiInputSource_Clipboard
ImGuiInputSource_COUNT
{
    ImGuiInputSource_None = 0,
    ImGuiInputSource_Mouse,
    ImGuiInputSource_Keyboard,
    ImGuiInputSource_Gamepad,
    ImGuiInputSource_Nav,               // Stored in g.ActiveIdSource only
    ImGuiInputSource_Clipboard,         // Currently only used by InputText()
    ImGuiInputSource_COUNT
};
ImGuiInputTextFlagsPrivate_
enum ImGuiInputTextFlagsPrivate_
Enumerator
ImGuiInputTextFlags_Multiline
ImGuiInputTextFlags_NoMarkEdited
ImGuiInputTextFlags_MergedItem
{
    // [Internal]
    ImGuiInputTextFlags_Multiline           = 1 << 26,  // For internal use by InputTextMultiline()
    ImGuiInputTextFlags_NoMarkEdited        = 1 << 27,  // For internal use by functions using InputText() before reformatting data
    ImGuiInputTextFlags_MergedItem          = 1 << 28   // For internal use by TempInputText(), will skip calling ItemAdd(). Require bounding-box to strictly match.
};
ImGuiItemAddFlags_
enum ImGuiItemAddFlags_
Enumerator
ImGuiItemAddFlags_None
ImGuiItemAddFlags_Focusable
{
    ImGuiItemAddFlags_None                  = 0,
    ImGuiItemAddFlags_Focusable             = 1 << 0    // FIXME-NAV: In current/legacy scheme, Focusable+TabStop support are opt-in by widgets. We will transition it toward being opt-out, so this flag is expected to eventually disappear.
};
ImGuiItemFlags_
enum ImGuiItemFlags_
Enumerator
ImGuiItemFlags_None
ImGuiItemFlags_NoTabStop
ImGuiItemFlags_ButtonRepeat
ImGuiItemFlags_Disabled
ImGuiItemFlags_NoNav
ImGuiItemFlags_NoNavDefaultFocus
ImGuiItemFlags_SelectableDontClosePopup
ImGuiItemFlags_MixedValue
ImGuiItemFlags_ReadOnly
{
    ImGuiItemFlags_None                     = 0,
    ImGuiItemFlags_NoTabStop                = 1 << 0,  // false
    ImGuiItemFlags_ButtonRepeat             = 1 << 1,  // false    // Button() will return true multiple times based on io.KeyRepeatDelay and io.KeyRepeatRate settings.
    ImGuiItemFlags_Disabled                 = 1 << 2,  // false    // [BETA] Disable interactions but doesn't affect visuals yet. See github.com/ocornut/imgui/issues/211
    ImGuiItemFlags_NoNav                    = 1 << 3,  // false
    ImGuiItemFlags_NoNavDefaultFocus        = 1 << 4,  // false
    ImGuiItemFlags_SelectableDontClosePopup = 1 << 5,  // false    // MenuItem/Selectable() automatically closes current Popup window
    ImGuiItemFlags_MixedValue               = 1 << 6,  // false    // [BETA] Represent a mixed/indeterminate value, generally multi-selection where values differ. Currently only supported by Checkbox() (later should support all sorts of widgets)
    ImGuiItemFlags_ReadOnly                 = 1 << 7   // false    // [ALPHA] Allow hovering interactions but underlying value is not changed.
};
ImGuiItemStatusFlags_
enum ImGuiItemStatusFlags_
Enumerator
ImGuiItemStatusFlags_None
ImGuiItemStatusFlags_HoveredRect
ImGuiItemStatusFlags_HasDisplayRect
ImGuiItemStatusFlags_Edited
ImGuiItemStatusFlags_ToggledSelection
ImGuiItemStatusFlags_ToggledOpen
ImGuiItemStatusFlags_HasDeactivated
ImGuiItemStatusFlags_Deactivated
ImGuiItemStatusFlags_HoveredWindow
ImGuiItemStatusFlags_FocusedByCode
ImGuiItemStatusFlags_FocusedByTabbing
ImGuiItemStatusFlags_Focused
{
    ImGuiItemStatusFlags_None               = 0,
    ImGuiItemStatusFlags_HoveredRect        = 1 << 0,   // Mouse position is within item rectangle (does NOT mean that the window is in correct z-order and can be hovered!, this is only one part of the most-common IsItemHovered test)
    ImGuiItemStatusFlags_HasDisplayRect     = 1 << 1,   // window->DC.LastItemDisplayRect is valid
    ImGuiItemStatusFlags_Edited             = 1 << 2,   // Value exposed by item was edited in the current frame (should match the bool return value of most widgets)
    ImGuiItemStatusFlags_ToggledSelection   = 1 << 3,   // Set when Selectable(), TreeNode() reports toggling a selection. We can't report "Selected", only state changes, in order to easily handle clipping with less issues.
    ImGuiItemStatusFlags_ToggledOpen        = 1 << 4,   // Set when TreeNode() reports toggling their open state.
    ImGuiItemStatusFlags_HasDeactivated     = 1 << 5,   // Set if the widget/group is able to provide data for the ImGuiItemStatusFlags_Deactivated flag.
    ImGuiItemStatusFlags_Deactivated        = 1 << 6,   // Only valid if ImGuiItemStatusFlags_HasDeactivated is set.
    ImGuiItemStatusFlags_HoveredWindow      = 1 << 7,   // Override the HoveredWindow test to allow cross-window hover testing.
    ImGuiItemStatusFlags_FocusedByCode      = 1 << 8,   // Set when the Focusable item just got focused from code.
    ImGuiItemStatusFlags_FocusedByTabbing   = 1 << 9,   // Set when the Focusable item just got focused by Tabbing.
    ImGuiItemStatusFlags_Focused            = ImGuiItemStatusFlags_FocusedByCode | ImGuiItemStatusFlags_FocusedByTabbing
#ifdef IMGUI_ENABLE_TEST_ENGINE
    , // [imgui_tests only]
    ImGuiItemStatusFlags_Openable           = 1 << 20,  //
    ImGuiItemStatusFlags_Opened             = 1 << 21,  //
    ImGuiItemStatusFlags_Checkable          = 1 << 22,  //
    ImGuiItemStatusFlags_Checked            = 1 << 23   //
#endif
};
ImGuiLayoutType_
enum ImGuiLayoutType_
Enumerator
ImGuiLayoutType_Horizontal
ImGuiLayoutType_Vertical
{
    ImGuiLayoutType_Horizontal = 0,
    ImGuiLayoutType_Vertical = 1
};
ImGuiLogType
enum ImGuiLogType
Enumerator
ImGuiLogType_None
ImGuiLogType_TTY
ImGuiLogType_File
ImGuiLogType_Buffer
ImGuiLogType_Clipboard
{
    ImGuiLogType_None = 0,
    ImGuiLogType_TTY,
    ImGuiLogType_File,
    ImGuiLogType_Buffer,
    ImGuiLogType_Clipboard
};
ImGuiNavDirSourceFlags_
enum ImGuiNavDirSourceFlags_
Enumerator
ImGuiNavDirSourceFlags_None
ImGuiNavDirSourceFlags_Keyboard
ImGuiNavDirSourceFlags_PadDPad
ImGuiNavDirSourceFlags_PadLStick
{
    ImGuiNavDirSourceFlags_None         = 0,
    ImGuiNavDirSourceFlags_Keyboard     = 1 << 0,
    ImGuiNavDirSourceFlags_PadDPad      = 1 << 1,
    ImGuiNavDirSourceFlags_PadLStick    = 1 << 2
};
ImGuiNavForward
enum ImGuiNavForward
Enumerator
ImGuiNavForward_None
ImGuiNavForward_ForwardQueued
ImGuiNavForward_ForwardActive
{
    ImGuiNavForward_None,
    ImGuiNavForward_ForwardQueued,
    ImGuiNavForward_ForwardActive
};
ImGuiNavHighlightFlags_
enum ImGuiNavHighlightFlags_
Enumerator
ImGuiNavHighlightFlags_None
ImGuiNavHighlightFlags_TypeDefault
ImGuiNavHighlightFlags_TypeThin
ImGuiNavHighlightFlags_AlwaysDraw
ImGuiNavHighlightFlags_NoRounding
{
    ImGuiNavHighlightFlags_None         = 0,
    ImGuiNavHighlightFlags_TypeDefault  = 1 << 0,
    ImGuiNavHighlightFlags_TypeThin     = 1 << 1,
    ImGuiNavHighlightFlags_AlwaysDraw   = 1 << 2,       // Draw rectangular highlight if (g.NavId == id) _even_ when using the mouse.
    ImGuiNavHighlightFlags_NoRounding   = 1 << 3
};
ImGuiNavLayer
enum ImGuiNavLayer
Enumerator
ImGuiNavLayer_Main
ImGuiNavLayer_Menu
ImGuiNavLayer_COUNT
{
    ImGuiNavLayer_Main  = 0,    // Main scrolling layer
    ImGuiNavLayer_Menu  = 1,    // Menu layer (access with Alt/ImGuiNavInput_Menu)
    ImGuiNavLayer_COUNT
};
ImGuiNavMoveFlags_
enum ImGuiNavMoveFlags_
Enumerator
ImGuiNavMoveFlags_None
ImGuiNavMoveFlags_LoopX
ImGuiNavMoveFlags_LoopY
ImGuiNavMoveFlags_WrapX
ImGuiNavMoveFlags_WrapY
ImGuiNavMoveFlags_AllowCurrentNavId
ImGuiNavMoveFlags_AlsoScoreVisibleSet
ImGuiNavMoveFlags_ScrollToEdge
{
    ImGuiNavMoveFlags_None                  = 0,
    ImGuiNavMoveFlags_LoopX                 = 1 << 0,   // On failed request, restart from opposite side
    ImGuiNavMoveFlags_LoopY                 = 1 << 1,
    ImGuiNavMoveFlags_WrapX                 = 1 << 2,   // On failed request, request from opposite side one line down (when NavDir==right) or one line up (when NavDir==left)
    ImGuiNavMoveFlags_WrapY                 = 1 << 3,   // This is not super useful for provided for completeness
    ImGuiNavMoveFlags_AllowCurrentNavId     = 1 << 4,   // Allow scoring and considering the current NavId as a move target candidate. This is used when the move source is offset (e.g. pressing PageDown actually needs to send a Up move request, if we are pressing PageDown from the bottom-most item we need to stay in place)
    ImGuiNavMoveFlags_AlsoScoreVisibleSet   = 1 << 5,   // Store alternate result in NavMoveResultLocalVisibleSet that only comprise elements that are already fully visible.
    ImGuiNavMoveFlags_ScrollToEdge          = 1 << 6
};
ImGuiNextItemDataFlags_
enum ImGuiNextItemDataFlags_
Enumerator
ImGuiNextItemDataFlags_None
ImGuiNextItemDataFlags_HasWidth
ImGuiNextItemDataFlags_HasOpen
{
    ImGuiNextItemDataFlags_None     = 0,
    ImGuiNextItemDataFlags_HasWidth = 1 << 0,
    ImGuiNextItemDataFlags_HasOpen  = 1 << 1
};
ImGuiNextWindowDataFlags_
enum ImGuiNextWindowDataFlags_
Enumerator
ImGuiNextWindowDataFlags_None
ImGuiNextWindowDataFlags_HasPos
ImGuiNextWindowDataFlags_HasSize
ImGuiNextWindowDataFlags_HasContentSize
ImGuiNextWindowDataFlags_HasCollapsed
ImGuiNextWindowDataFlags_HasSizeConstraint
ImGuiNextWindowDataFlags_HasFocus
ImGuiNextWindowDataFlags_HasBgAlpha
ImGuiNextWindowDataFlags_HasScroll
{
    ImGuiNextWindowDataFlags_None               = 0,
    ImGuiNextWindowDataFlags_HasPos             = 1 << 0,
    ImGuiNextWindowDataFlags_HasSize            = 1 << 1,
    ImGuiNextWindowDataFlags_HasContentSize     = 1 << 2,
    ImGuiNextWindowDataFlags_HasCollapsed       = 1 << 3,
    ImGuiNextWindowDataFlags_HasSizeConstraint  = 1 << 4,
    ImGuiNextWindowDataFlags_HasFocus           = 1 << 5,
    ImGuiNextWindowDataFlags_HasBgAlpha         = 1 << 6,
    ImGuiNextWindowDataFlags_HasScroll          = 1 << 7
};
ImGuiOldColumnFlags_
enum ImGuiOldColumnFlags_
Enumerator
ImGuiOldColumnFlags_None
ImGuiOldColumnFlags_NoBorder
ImGuiOldColumnFlags_NoResize
ImGuiOldColumnFlags_NoPreserveWidths
ImGuiOldColumnFlags_NoForceWithinWindow
ImGuiOldColumnFlags_GrowParentContentsSize
ImGuiColumnsFlags_None
ImGuiColumnsFlags_NoBorder
ImGuiColumnsFlags_NoResize
ImGuiColumnsFlags_NoPreserveWidths
ImGuiColumnsFlags_NoForceWithinWindow
ImGuiColumnsFlags_GrowParentContentsSize
{
    ImGuiOldColumnFlags_None                    = 0,
    ImGuiOldColumnFlags_NoBorder                = 1 << 0,   // Disable column dividers
    ImGuiOldColumnFlags_NoResize                = 1 << 1,   // Disable resizing columns when clicking on the dividers
    ImGuiOldColumnFlags_NoPreserveWidths        = 1 << 2,   // Disable column width preservation when adjusting columns
    ImGuiOldColumnFlags_NoForceWithinWindow     = 1 << 3,   // Disable forcing columns to fit within window
    ImGuiOldColumnFlags_GrowParentContentsSize  = 1 << 4    // (WIP) Restore pre-1.51 behavior of extending the parent window contents size but _without affecting the columns width at all_. Will eventually remove.
    // Obsolete names (will be removed)
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    , ImGuiColumnsFlags_None                    = ImGuiOldColumnFlags_None,
    ImGuiColumnsFlags_NoBorder                  = ImGuiOldColumnFlags_NoBorder,
    ImGuiColumnsFlags_NoResize                  = ImGuiOldColumnFlags_NoResize,
    ImGuiColumnsFlags_NoPreserveWidths          = ImGuiOldColumnFlags_NoPreserveWidths,
    ImGuiColumnsFlags_NoForceWithinWindow       = ImGuiOldColumnFlags_NoForceWithinWindow,
    ImGuiColumnsFlags_GrowParentContentsSize    = ImGuiOldColumnFlags_GrowParentContentsSize
#endif
};
ImGuiPlotType
enum ImGuiPlotType
Enumerator
ImGuiPlotType_Lines
ImGuiPlotType_Histogram
{
    ImGuiPlotType_Lines,
    ImGuiPlotType_Histogram
};
ImGuiPopupPositionPolicy
enum ImGuiPopupPositionPolicy
Enumerator
ImGuiPopupPositionPolicy_Default
ImGuiPopupPositionPolicy_ComboBox
ImGuiPopupPositionPolicy_Tooltip
{
    ImGuiPopupPositionPolicy_Default,
    ImGuiPopupPositionPolicy_ComboBox,
    ImGuiPopupPositionPolicy_Tooltip
};
ImGuiSelectableFlagsPrivate_
enum ImGuiSelectableFlagsPrivate_
Enumerator
ImGuiSelectableFlags_NoHoldingActiveID
ImGuiSelectableFlags_SelectOnClick
ImGuiSelectableFlags_SelectOnRelease
ImGuiSelectableFlags_SpanAvailWidth
ImGuiSelectableFlags_DrawHoveredWhenHeld
ImGuiSelectableFlags_SetNavIdOnHover
ImGuiSelectableFlags_NoPadWithHalfSpacing
{
    // NB: need to be in sync with last value of ImGuiSelectableFlags_
    ImGuiSelectableFlags_NoHoldingActiveID      = 1 << 20,
    ImGuiSelectableFlags_SelectOnClick          = 1 << 21,  // Override button behavior to react on Click (default is Click+Release)
    ImGuiSelectableFlags_SelectOnRelease        = 1 << 22,  // Override button behavior to react on Release (default is Click+Release)
    ImGuiSelectableFlags_SpanAvailWidth         = 1 << 23,  // Span all avail width even if we declared less for layout purpose. FIXME: We may be able to remove this (added in 6251d379, 2bcafc86 for menus)
    ImGuiSelectableFlags_DrawHoveredWhenHeld    = 1 << 24,  // Always show active when held, even is not hovered. This concept could probably be renamed/formalized somehow.
    ImGuiSelectableFlags_SetNavIdOnHover        = 1 << 25,  // Set Nav/Focus ID on mouse hover (used by MenuItem)
    ImGuiSelectableFlags_NoPadWithHalfSpacing   = 1 << 26   // Disable padding each side with ItemSpacing * 0.5f
};
ImGuiSeparatorFlags_
enum ImGuiSeparatorFlags_
Enumerator
ImGuiSeparatorFlags_None
ImGuiSeparatorFlags_Horizontal
ImGuiSeparatorFlags_Vertical
ImGuiSeparatorFlags_SpanAllColumns
{
    ImGuiSeparatorFlags_None                = 0,
    ImGuiSeparatorFlags_Horizontal          = 1 << 0,   // Axis default to current layout type, so generally Horizontal unless e.g. in a menu bar
    ImGuiSeparatorFlags_Vertical            = 1 << 1,
    ImGuiSeparatorFlags_SpanAllColumns      = 1 << 2
};
ImGuiSliderFlagsPrivate_
enum ImGuiSliderFlagsPrivate_
Enumerator
ImGuiSliderFlags_Vertical
ImGuiSliderFlags_ReadOnly
{
    ImGuiSliderFlags_Vertical               = 1 << 20,  // Should this slider be orientated vertically?
    ImGuiSliderFlags_ReadOnly               = 1 << 21
};
ImGuiTabBarFlagsPrivate_
enum ImGuiTabBarFlagsPrivate_
Enumerator
ImGuiTabBarFlags_DockNode
ImGuiTabBarFlags_IsFocused
ImGuiTabBarFlags_SaveSettings
{
    ImGuiTabBarFlags_DockNode                   = 1 << 20,  // Part of a dock node [we don't use this in the master branch but it facilitate branch syncing to keep this around]
    ImGuiTabBarFlags_IsFocused                  = 1 << 21,
    ImGuiTabBarFlags_SaveSettings               = 1 << 22   // FIXME: Settings are handled by the docking system, this only request the tab bar to mark settings dirty when reordering tabs
};
ImGuiTabItemFlagsPrivate_
enum ImGuiTabItemFlagsPrivate_
Enumerator
ImGuiTabItemFlags_SectionMask_
ImGuiTabItemFlags_NoCloseButton
ImGuiTabItemFlags_Button
{
    ImGuiTabItemFlags_SectionMask_              = ImGuiTabItemFlags_Leading | ImGuiTabItemFlags_Trailing,
    ImGuiTabItemFlags_NoCloseButton             = 1 << 20,  // Track whether p_open was set or not (we'll need this info on the next frame to recompute ContentWidth during layout)
    ImGuiTabItemFlags_Button                    = 1 << 21   // Used by TabItemButton, change the tab item behavior to mimic a button
};
ImGuiTextFlags_
enum ImGuiTextFlags_
Enumerator
ImGuiTextFlags_None
ImGuiTextFlags_NoWidthForLargeClippedText
{
    ImGuiTextFlags_None = 0,
    ImGuiTextFlags_NoWidthForLargeClippedText = 1 << 0
};
ImGuiTooltipFlags_
enum ImGuiTooltipFlags_
Enumerator
ImGuiTooltipFlags_None
ImGuiTooltipFlags_OverridePreviousTooltip
{
    ImGuiTooltipFlags_None = 0,
    ImGuiTooltipFlags_OverridePreviousTooltip = 1 << 0      // Override will clear/ignore previously submitted tooltip (defaults to append)
};
ImGuiTreeNodeFlagsPrivate_
enum ImGuiTreeNodeFlagsPrivate_
Enumerator
ImGuiTreeNodeFlags_ClipLabelForTrailingButton
{
    ImGuiTreeNodeFlags_ClipLabelForTrailingButton = 1 << 20
};
Function Documentation
ImAbs() [1/3]
static double ImAbs (double x) inline static
{ return fabs(x); }
ImAbs() [2/3]
static float ImAbs (float x) inline static
{ return fabsf(x); }
ImAbs() [3/3]
static int ImAbs (int x) inline static
{ return x < 0 ? -x : x; }
Referenced by ImDrawList::_PathArcToFastEx(), and ImDrawList::PathArcTo().
ImAddClampOverflow()
template<typename T > static T ImAddClampOverflow (T a, T b, T mn, T mx) inline static
{ if (b < 0 && (a < mn - b)) return mn; if (b > 0 && (a > mx - b)) return mx; return a + b; }
Referenced by ImGui::DataTypeApplyOp().
ImAlphaBlendColors()
IMGUI_API ImU32 ImAlphaBlendColors (ImU32 col_a, ImU32 col_b)
{
    float t = ((col_b >> IM_COL32_A_SHIFT) & 0xFF) / 255.f;
    int r = ImLerp((int)(col_a >> IM_COL32_R_SHIFT) & 0xFF, (int)(col_b >> IM_COL32_R_SHIFT) & 0xFF, t);
    int g = ImLerp((int)(col_a >> IM_COL32_G_SHIFT) & 0xFF, (int)(col_b >> IM_COL32_G_SHIFT) & 0xFF, t);
    int b = ImLerp((int)(col_a >> IM_COL32_B_SHIFT) & 0xFF, (int)(col_b >> IM_COL32_B_SHIFT) & 0xFF, t);
    return IM_COL32(r, g, b, 0xFF);
}
References IM_COL32, IM_COL32_A_SHIFT, IM_COL32_B_SHIFT, IM_COL32_G_SHIFT, IM_COL32_R_SHIFT, and ImLerp().
Referenced by ImGui::RenderColorRectWithAlphaCheckerboard().
ImBezierCubicCalc()
IM_MSVC_RUNTIME_CHECKS_RESTORE IMGUI_API ImVec2 ImBezierCubicCalc (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, const ImVec2 & p4, float t)
{
    float u = 1.0f - t;
    float w1 = u * u * u;
    float w2 = 3 * u * u * t;
    float w3 = 3 * u * t * t;
    float w4 = t * t * t;
    return ImVec2(w1 * p1.x + w2 * p2.x + w3 * p3.x + w4 * p4.x, w1 * p1.y + w2 * p2.y + w3 * p3.y + w4 * p4.y);
}
References ImVec2::x, and ImVec2::y.
Referenced by ImBezierCubicClosestPoint(), and ImDrawList::PathBezierCubicCurveTo().
ImBezierCubicClosestPoint()
IMGUI_API ImVec2 ImBezierCubicClosestPoint (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, const ImVec2 & p4, const ImVec2 & p, int num_segments)
{
    IM_ASSERT(num_segments > 0); // Use ImBezierCubicClosestPointCasteljau()
    ImVec2 p_last = p1;
    ImVec2 p_closest;
    float p_closest_dist2 = FLT_MAX;
    float t_step = 1.0f / (float)num_segments;
    for (int i_step = 1; i_step <= num_segments; i_step++)
    {
        ImVec2 p_current = ImBezierCubicCalc(p1, p2, p3, p4, t_step * i_step);
        ImVec2 p_line = ImLineClosestPoint(p_last, p_current, p);
        float dist2 = ImLengthSqr(p - p_line);
        if (dist2 < p_closest_dist2)
        {
            p_closest = p_line;
            p_closest_dist2 = dist2;
        }
        p_last = p_current;
    }
    return p_closest;
}
References IM_ASSERT, ImBezierCubicCalc(), ImLengthSqr(), and ImLineClosestPoint().
ImBezierCubicClosestPointCasteljau()
IMGUI_API ImVec2 ImBezierCubicClosestPointCasteljau (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, const ImVec2 & p4, const ImVec2 & p, float tess_tol)
{
    IM_ASSERT(tess_tol > 0.0f);
    ImVec2 p_last = p1;
    ImVec2 p_closest;
    float p_closest_dist2 = FLT_MAX;
    ImBezierCubicClosestPointCasteljauStep(p, p_closest, p_last, p_closest_dist2, p1.x, p1.y, p2.x, p2.y, p3.x, p3.y, p4.x, p4.y, tess_tol, 0);
    return p_closest;
}
References IM_ASSERT, ImBezierCubicClosestPointCasteljauStep(), ImVec2::x, and ImVec2::y.
ImBezierQuadraticCalc()
IMGUI_API ImVec2 ImBezierQuadraticCalc (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, float t)
{
    float u = 1.0f - t;
    float w1 = u * u;
    float w2 = 2 * u * t;
    float w3 = t * t;
    return ImVec2(w1 * p1.x + w2 * p2.x + w3 * p3.x, w1 * p1.y + w2 * p2.y + w3 * p3.y);
}
References ImVec2::x, and ImVec2::y.
Referenced by ImDrawList::PathBezierQuadraticCurveTo().
ImBitArrayClearBit()
void ImBitArrayClearBit (ImU32 * arr, int n) inline
{ ImU32 mask = (ImU32)1 << (n & 31); arr[n >> 5] &= ~mask; }
Referenced by ImBitArray< BITCOUNT >::ClearBit(), and ImBitVector::ClearBit().
ImBitArraySetBit()
void ImBitArraySetBit (ImU32 * arr, int n) inline
{ ImU32 mask = (ImU32)1 << (n & 31); arr[n >> 5] |= mask; }
Referenced by ImBitArray< BITCOUNT >::SetBit(), and ImBitVector::SetBit().
ImBitArraySetBitRange()
void ImBitArraySetBitRange (ImU32 * arr, int n, int n2) inline
{
    n2--;
    while (n <= n2)
    {
        int a_mod = (n & 31);
        int b_mod = (n2 > (n | 31) ? 31 : (n2 & 31)) + 1;
        ImU32 mask = (ImU32)(((ImU64)1 << b_mod) - 1) & ~(ImU32)(((ImU64)1 << a_mod) - 1);
        arr[n >> 5] |= mask;
        n = (n + 32) & ~31;
    }
}
Referenced by ImBitArray< BITCOUNT >::SetBitRange().
ImBitArrayTestBit()
IM_MSVC_RUNTIME_CHECKS_RESTORE bool ImBitArrayTestBit (const ImU32 * arr, int n) inline
{ ImU32 mask = (ImU32)1 << (n & 31); return (arr[n >> 5] & mask) != 0; }
Referenced by ImBitArray< BITCOUNT >::TestBit(), and ImBitVector::TestBit().
ImCharIsBlankA()
static bool ImCharIsBlankA (char c) inline static
{ return c == ' ' || c == '\t'; }
Referenced by ImGuiTextFilter::Build(), ImFont::CalcTextSizeA(), ImGui::ColorEdit4(), ImGui::DataTypeApplyOpFromText(), ImFont::RenderText(), and ImGui::RenderTextEllipsis().
ImCharIsBlankW()
static bool ImCharIsBlankW (unsigned int c) inline static
{ return c == ' ' || c == '\t' || c == 0x3000; }
Referenced by ImFont::CalcWordWrapPositionA(), InputTextFilterCharacter(), and ImStb::is_separator().
ImClamp() [1/2]
static ImVec2 ImClamp (const ImVec2 & v, const ImVec2 & mn, ImVec2 mx) inline static
{ return ImVec2((v.x < mn.x) ? mn.x : (v.x > mx.x) ? mx.x : v.x, (v.y < mn.y) ? mn.y : (v.y > mx.y) ? mx.y : v.y); }
References ImVec2::x, and ImVec2::y.
ImClamp() [2/2]
template<typename T > static T ImClamp (T v, T mn, T mx) inline static
{ return (v < mn) ? mn : (v > mx) ? mx : v; }
Referenced by ImDrawList::_PathArcToFastEx(), ImDrawList::AddCircle(), ImDrawList::AddCircleFilled(), ImFont::AddGlyph(), ImGui::BeginMenu(), ImGui::CalcListClipping(), CalcWindowAutoFitSize(), CalcWindowSizeAfterConstraint(), ClampWindowRect(), ImRect::ClipWithFull(), ImGui::ColorEdit4(), ImGui::ColorPicker4(), ImGui::DataTypeApplyOpFromText(), ImGui::FindBestWindowPosForPopupEx(), Slic3r::GUI::image_button_ex(), ImGui::ImageButtonEx(), ImGui::InputTextEx(), ImGuiInputTextCallbackData::InsertChars(), ImGui::NavCalcPreferredRefPos(), NavClampRectToVisibleAreaForMoveDir(), ImGui::NavProcessItem(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::RenderColorRectWithAlphaCheckerboard(), ImGui::RenderRectFilledRangeH(), ImGui::ScrollbarEx(), ImGui::ShadeVertsLinearColorGradientKeepAlpha(), ImGui::ShadeVertsLinearUV(), ImStb::STB_TEXTEDIT_INSERTCHARS(), ImGui::TableSetColumnWidth(), ImGui::TableUpdateLayout(), ImGui::UpdateMouseWheel(), and ImGui::UpdateWindowManualResize().
ImDot()
static float ImDot (const ImVec2 & a, const ImVec2 & b) inline static
{ return a.x * b.x + a.y * b.y; }
Referenced by ImGui::ShadeVertsLinearColorGradientKeepAlpha().
ImFileClose()
IMGUI_API bool ImFileClose (ImFileHandle file)
{ return fclose(f) == 0; }
Referenced by ImFileLoadToMemory(), ImGui::LogFinish(), ImGui::SaveIniSettingsToDisk(), and ImGui::Shutdown().
ImFileGetSize()
IMGUI_API ImU64 ImFileGetSize (ImFileHandle file)
{ long off = 0, sz = 0; return ((off = ftell(f)) != -1 && !fseek(f, 0, SEEK_END) && (sz = ftell(f)) != -1 && !fseek(f, off, SEEK_SET)) ? (ImU64)sz : (ImU64)-1; }
References SEEK_SET.
Referenced by ImFileLoadToMemory().
ImFileLoadToMemory()
IMGUI_API void * ImFileLoadToMemory (const char * filename, const char * mode, size_t * out_file_size = NULL, int padding_bytes = 0)
{
    IM_ASSERT(filename && mode);
    if (out_file_size)
        *out_file_size = 0;
    ImFileHandle f;
    if ((f = ImFileOpen(filename, mode)) == NULL)
        return NULL;
    size_t file_size = (size_t)ImFileGetSize(f);
    if (file_size == (size_t)-1)
    {
        ImFileClose(f);
        return NULL;
    }
    void* file_data = IM_ALLOC(file_size + padding_bytes);
    if (file_data == NULL)
    {
        ImFileClose(f);
        return NULL;
    }
    if (ImFileRead(file_data, 1, file_size, f) != file_size)
    {
        ImFileClose(f);
        IM_FREE(file_data);
        return NULL;
    }
    if (padding_bytes > 0)
        memset((void*)(((char*)file_data) + file_size), 0, (size_t)padding_bytes);
    ImFileClose(f);
    if (out_file_size)
        *out_file_size = file_size;
    return file_data;
}
References IM_ALLOC, IM_ASSERT, IM_FREE, ImFileClose(), ImFileGetSize(), ImFileOpen(), and ImFileRead().
Referenced by ImFontAtlas::AddFontFromFileTTF(), and ImGui::LoadIniSettingsFromDisk().
ImFileOpen()
IMGUI_API ImFileHandle ImFileOpen (const char * filename, const char * mode)
{
#if defined(_WIN32) && !defined(IMGUI_DISABLE_WIN32_FUNCTIONS) && !defined(__CYGWIN__) && !defined(__GNUC__)
    // We need a fopen() wrapper because MSVC/Windows fopen doesn't handle UTF-8 filenames.
    // Previously we used ImTextCountCharsFromUtf8/ImTextStrFromUtf8 here but we now need to support ImWchar16 and ImWchar32!
    const int filename_wsize = ::MultiByteToWideChar(CP_UTF8, 0, filename, -1, NULL, 0);
    const int mode_wsize = ::MultiByteToWideChar(CP_UTF8, 0, mode, -1, NULL, 0);
    ImVector<ImWchar> buf;
    buf.resize(filename_wsize + mode_wsize);
    ::MultiByteToWideChar(CP_UTF8, 0, filename, -1, (wchar_t*)&buf[0], filename_wsize);
    ::MultiByteToWideChar(CP_UTF8, 0, mode, -1, (wchar_t*)&buf[filename_wsize], mode_wsize);
    return ::_wfopen((const wchar_t*)&buf[0], (const wchar_t*)&buf[filename_wsize]);
#else
    return fopen(filename, mode);
#endif
}
References ImVector< T >::resize().
Referenced by ImFileLoadToMemory(), ImGui::LogToFile(), and ImGui::SaveIniSettingsToDisk().
ImFileRead()
IMGUI_API ImU64 ImFileRead (void * data, ImU64 size, ImU64 count, ImFileHandle file)
{ return fread(data, (size_t)sz, (size_t)count, f); }
Referenced by ImFileLoadToMemory().
ImFileWrite()
IMGUI_API ImU64 ImFileWrite (const void * data, ImU64 size, ImU64 count, ImFileHandle file)
{ return fwrite(data, (size_t)sz, (size_t)count, f); }
Referenced by LogTextV(), and ImGui::SaveIniSettingsToDisk().
ImFloor() [1/2]
static ImVec2 ImFloor (const ImVec2 & v) inline static
{ return ImVec2((float)(int)(v.x), (float)(int)(v.y)); }
References ImVec2::x, and ImVec2::y.
ImFloor() [2/2]
static float ImFloor (float f) inline static
{ return (float)(int)(f); }
Referenced by ImFont::AddGlyph(), ApplyWindowSettings(), ImGui::Begin(), ImGui::BeginChildEx(), ImGui::BeginColumns(), ImGui::BeginListBox(), ImGui::CloseButton(), ImGui::DebugNodeDrawCmdShowMeshAndBoundingBox(), ImGui::DebugRenderViewportThumbnail(), ImGui::EndTable(), ImFontAtlasBuildWithStbTruetype(), ImGui::InputTextEx(), ImGui::NavCalcPreferredRefPos(), ImGui::NavUpdate(), ImGui::NavUpdateWindowing(), ImGuiStyle::ScaleAllSizes(), ImGui::SetNextWindowContentSize(), ImGui::SetWindowPos(), ImGui::ShrinkWidths(), ImGui::TableHeader(), ImGui::TableUpdateLayout(), ImGui::UpdateMouseInputs(), ImGui::UpdateMouseWheel(), and ImGui::UpdateWindowManualResize().
ImFloorSigned()
static float ImFloorSigned (float f) inline static
{ return (float)((f >= 0 || (int)f == f) ? (int)f : (int)f - 1); } // Decent replacement for floorf()
Referenced by ImDrawList::PathArcTo().
ImFontAtlasBuildFinish()
IMGUI_API void ImFontAtlasBuildFinish (ImFontAtlas * atlas)
{
    // Render into our custom data blocks
    IM_ASSERT(atlas->TexPixelsAlpha8 != NULL || atlas->TexPixelsRGBA32 != NULL);
    ImFontAtlasBuildRenderDefaultTexData(atlas);
    ImFontAtlasBuildRenderLinesTexData(atlas);
    // Register custom rectangle glyphs
    for (int i = 0; i < atlas->CustomRects.Size; i++)
    {
        const ImFontAtlasCustomRect* r = &atlas->CustomRects[i];
        if (r->Font == NULL || r->GlyphID == 0)
            continue;
        // Will ignore ImFontConfig settings: GlyphMinAdvanceX, GlyphMinAdvanceY, GlyphExtraSpacing, PixelSnapH
        IM_ASSERT(r->Font->ContainerAtlas == atlas);
        ImVec2 uv0, uv1;
        atlas->CalcCustomRectUV(r, &uv0, &uv1);
        r->Font->AddGlyph(NULL, (ImWchar)r->GlyphID, r->GlyphOffset.x, r->GlyphOffset.y, r->GlyphOffset.x + r->Width, r->GlyphOffset.y + r->Height, uv0.x, uv0.y, uv1.x, uv1.y, r->GlyphAdvanceX);
    }
    // Build all fonts lookup tables
    for (int i = 0; i < atlas->Fonts.Size; i++)
        if (atlas->Fonts[i]->DirtyLookupTables)
            atlas->Fonts[i]->BuildLookupTable();
    // Ellipsis character is required for rendering elided text. We prefer using U+2026 (horizontal ellipsis).
    // However some old fonts may contain ellipsis at U+0085. Here we auto-detect most suitable ellipsis character.
    // FIXME: Also note that 0x2026 is currently seldom included in our font ranges. Because of this we are more likely to use three individual dots.
    for (int i = 0; i < atlas->Fonts.size(); i++)
    {
        ImFont* font = atlas->Fonts[i];
        if (font->EllipsisChar != (ImWchar)-1)
            continue;
        const ImWchar ellipsis_variants[] = { (ImWchar)0x2026, (ImWchar)0x0085 };
        for (int j = 0; j < IM_ARRAYSIZE(ellipsis_variants); j++)
            if (font->FindGlyphNoFallback(ellipsis_variants[j]) != NULL) // Verify glyph exists
            {
                font->EllipsisChar = ellipsis_variants[j];
                break;
            }
    }
}
References ImFont::AddGlyph(), ImFontAtlas::CalcCustomRectUV(), ImFont::ContainerAtlas, ImFontAtlas::CustomRects, ImFont::EllipsisChar, ImFont::FindGlyphNoFallback(), ImFontAtlasCustomRect::Font, ImFontAtlas::Fonts, ImFontAtlasCustomRect::GlyphAdvanceX, ImFontAtlasCustomRect::GlyphID, ImFontAtlasCustomRect::GlyphOffset, ImFontAtlasCustomRect::Height, IM_ARRAYSIZE, IM_ASSERT, ImFontAtlasBuildRenderDefaultTexData(), ImFontAtlasBuildRenderLinesTexData(), ImVector< T >::Size, ImVector< T >::size(), ImFontAtlas::TexPixelsAlpha8, ImFontAtlas::TexPixelsRGBA32, ImFontAtlasCustomRect::Width, ImVec2::x, and ImVec2::y.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildInit()
IMGUI_API void ImFontAtlasBuildInit (ImFontAtlas * atlas)
{
    // Register texture region for mouse cursors or standard white pixels
    if (atlas->PackIdMouseCursors < 0)
    {
        if (!(atlas->Flags & ImFontAtlasFlags_NoMouseCursors))
            atlas->PackIdMouseCursors = atlas->AddCustomRectRegular(FONT_ATLAS_DEFAULT_TEX_DATA_W * 2 + 1, FONT_ATLAS_DEFAULT_TEX_DATA_H);
        else
            atlas->PackIdMouseCursors = atlas->AddCustomRectRegular(2, 2);
    }
    // Register texture region for thick lines
    // The +2 here is to give space for the end caps, whilst height +1 is to accommodate the fact we have a zero-width row
    if (atlas->PackIdLines < 0)
    {
        if (!(atlas->Flags & ImFontAtlasFlags_NoBakedLines))
            atlas->PackIdLines = atlas->AddCustomRectRegular(IM_DRAWLIST_TEX_LINES_WIDTH_MAX + 2, IM_DRAWLIST_TEX_LINES_WIDTH_MAX + 1);
    }
}
References ImFontAtlas::AddCustomRectRegular(), ImFontAtlas::Flags, FONT_ATLAS_DEFAULT_TEX_DATA_H, FONT_ATLAS_DEFAULT_TEX_DATA_W, IM_DRAWLIST_TEX_LINES_WIDTH_MAX, ImFontAtlasFlags_NoBakedLines, ImFontAtlasFlags_NoMouseCursors, ImFontAtlas::PackIdLines, and ImFontAtlas::PackIdMouseCursors.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildMultiplyCalcLookupTable()
IMGUI_API void ImFontAtlasBuildMultiplyCalcLookupTable (unsigned char out_table[256], float in_multiply_factor)
{
    for (unsigned int i = 0; i < 256; i++)
    {
        unsigned int value = (unsigned int)(i * in_brighten_factor);
        out_table[i] = value > 255 ? 255 : (value & 0xFF);
    }
}
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildMultiplyRectAlpha8()
IMGUI_API void ImFontAtlasBuildMultiplyRectAlpha8 (const unsigned char table[256], unsigned char * pixels, int x, int y, int w, int h, int stride)
{
    unsigned char* data = pixels + x + y * stride;
    for (int j = h; j > 0; j--, data += stride)
        for (int i = 0; i < w; i++)
            data[i] = table[data[i]];
}
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildPackCustomRects()
IMGUI_API void ImFontAtlasBuildPackCustomRects (ImFontAtlas * atlas, void * stbrp_context_opaque)
{
    stbrp_context* pack_context = (stbrp_context*)stbrp_context_opaque;
    IM_ASSERT(pack_context != NULL);
    ImVector<ImFontAtlasCustomRect>& user_rects = atlas->CustomRects;
    IM_ASSERT(user_rects.Size >= 1); // We expect at least the default custom rects to be registered, else something went wrong.
    ImVector<stbrp_rect> pack_rects;
    pack_rects.resize(user_rects.Size);
    memset(pack_rects.Data, 0, (size_t)pack_rects.size_in_bytes());
    for (int i = 0; i < user_rects.Size; i++)
    {
        pack_rects[i].w = user_rects[i].Width;
        pack_rects[i].h = user_rects[i].Height;
    }
    stbrp_pack_rects(pack_context, &pack_rects[0], pack_rects.Size);
    for (int i = 0; i < pack_rects.Size; i++)
        if (pack_rects[i].was_packed)
        {
            user_rects[i].X = pack_rects[i].x;
            user_rects[i].Y = pack_rects[i].y;
            IM_ASSERT(pack_rects[i].w == user_rects[i].Width && pack_rects[i].h == user_rects[i].Height);
            atlas->TexHeight = ImMax(atlas->TexHeight, pack_rects[i].y + pack_rects[i].h);
        }
}
References ImFontAtlas::CustomRects, ImVector< T >::Data, IM_ASSERT, ImMax(), ImVector< T >::resize(), ImVector< T >::Size, ImVector< T >::size_in_bytes(), stbrp_pack_rects(), and ImFontAtlas::TexHeight.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildRender32bppRectFromString()
IMGUI_API void ImFontAtlasBuildRender32bppRectFromString (ImFontAtlas * atlas, int x, int y, int w, int h, const char * in_str, char in_marker_char, unsigned int in_marker_pixel_value)
{
    IM_ASSERT(x >= 0 && x + w <= atlas->TexWidth);
    IM_ASSERT(y >= 0 && y + h <= atlas->TexHeight);
    unsigned int* out_pixel = atlas->TexPixelsRGBA32 + x + (y * atlas->TexWidth);
    for (int off_y = 0; off_y < h; off_y++, out_pixel += atlas->TexWidth, in_str += w)
        for (int off_x = 0; off_x < w; off_x++)
            out_pixel[off_x] = (in_str[off_x] == in_marker_char) ? in_marker_pixel_value : IM_COL32_BLACK_TRANS;
}
References IM_ASSERT, IM_COL32_BLACK_TRANS, ImFontAtlas::TexPixelsRGBA32, and ImFontAtlas::TexWidth.
Referenced by ImFontAtlasBuildRenderDefaultTexData().
ImFontAtlasBuildRender8bppRectFromString()
IMGUI_API void ImFontAtlasBuildRender8bppRectFromString (ImFontAtlas * atlas, int x, int y, int w, int h, const char * in_str, char in_marker_char, unsigned char in_marker_pixel_value)
{
    IM_ASSERT(x >= 0 && x + w <= atlas->TexWidth);
    IM_ASSERT(y >= 0 && y + h <= atlas->TexHeight);
    unsigned char* out_pixel = atlas->TexPixelsAlpha8 + x + (y * atlas->TexWidth);
    for (int off_y = 0; off_y < h; off_y++, out_pixel += atlas->TexWidth, in_str += w)
        for (int off_x = 0; off_x < w; off_x++)
            out_pixel[off_x] = (in_str[off_x] == in_marker_char) ? in_marker_pixel_value : 0x00;
}
References IM_ASSERT, ImFontAtlas::TexPixelsAlpha8, and ImFontAtlas::TexWidth.
Referenced by ImFontAtlasBuildRenderDefaultTexData().
ImFontAtlasBuildSetupFont()
IMGUI_API void ImFontAtlasBuildSetupFont (ImFontAtlas * atlas, ImFont * font, ImFontConfig * font_config, float ascent, float descent)
{
    if (!font_config->MergeMode)
    {
        font->ClearOutputData();
        font->FontSize = font_config->SizePixels;
        font->ConfigData = font_config;
        font->ConfigDataCount = 0;
        font->ContainerAtlas = atlas;
        font->Ascent = ascent;
        font->Descent = descent;
    }
    font->ConfigDataCount++;
}
References ImFont::Ascent, ImFont::ClearOutputData(), ImFont::ConfigData, ImFont::ConfigDataCount, ImFont::ContainerAtlas, ImFont::Descent, ImFont::FontSize, ImFontConfig::MergeMode, and ImFontConfig::SizePixels.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasGetBuilderForStbTruetype()
IMGUI_API const ImFontBuilderIO * ImFontAtlasGetBuilderForStbTruetype ()
{
    static ImFontBuilderIO io;
    io.FontBuilder_Build = ImFontAtlasBuildWithStbTruetype;
    return &io;
}
References ImFontBuilderIO::FontBuilder_Build, and ImFontAtlasBuildWithStbTruetype().
Referenced by ImFontAtlas::Build().
ImFormatString()
IMGUI_API int ImFormatString (char * buf, size_t buf_size, const char * fmt, ...)
{
    va_list args;
    va_start(args, fmt);
#ifdef IMGUI_USE_STB_SPRINTF
    int w = stbsp_vsnprintf(buf, (int)buf_size, fmt, args);
#else
    int w = vsnprintf(buf, buf_size, fmt, args);
#endif
    va_end(args);
    if (buf == NULL)
        return w;
    if (w == -1 || w >= (int)buf_size)
        w = (int)buf_size - 1;
    buf[w] = 0;
    return w;
}
Referenced by ImFontAtlas::AddFontDefault(), ImFontAtlas::AddFontFromFileTTF(), ImGui::BeginChildEx(), ImGui::BeginCombo(), ImGui::BeginPopupEx(), ImGui::BeginTooltipEx(), ImGui::ColorEdit4(), ImGui::ColorEditOptionsPopup(), ImGui::DataTypeFormatString(), ImGui::DebugNodeDrawList(), ImGui::DebugNodeTabBar(), ImGui::DebugNodeTable(), ImGui::NavScoreItem(), ImGui::NavUpdate(), PatchFormatStringFloatToInt(), ImGui::ProgressBar(), ImGui::ShowMetricsWindow(), ImGui::TableHeader(), ImGui::TableMergeDrawChannels(), and ImGui::Value().
ImFormatStringV()
IMGUI_API int ImFormatStringV (char * buf, size_t buf_size, const char * fmt, va_list args)
{
#ifdef IMGUI_USE_STB_SPRINTF
    int w = stbsp_vsnprintf(buf, (int)buf_size, fmt, args);
#else
    int w = vsnprintf(buf, buf_size, fmt, args);
#endif
    if (buf == NULL)
        return w;
    if (w == -1 || w >= (int)buf_size)
        w = (int)buf_size - 1;
    buf[w] = 0;
    return w;
}
Referenced by ImGuiTextBuffer::appendfv(), ImGui::BulletTextV(), ImGui::LabelTextV(), ImGui::TextV(), ImGui::TreeNodeExV(), and ImGui::TreeNodeExV().
ImGetDirQuadrantFromDelta()
IMGUI_API ImGuiDir ImGetDirQuadrantFromDelta (float dx, float dy)
{
    if (ImFabs(dx) > ImFabs(dy))
        return (dx > 0.0f) ? ImGuiDir_Right : ImGuiDir_Left;
    return (dy > 0.0f) ? ImGuiDir_Down : ImGuiDir_Up;
}
References ImFabs, ImGuiDir_Down, ImGuiDir_Left, ImGuiDir_Right, and ImGuiDir_Up.
Referenced by ImGui::NavScoreItem().
ImHash()
static ImGuiID ImHash (const void * data, int size, ImU32 seed = 0) inline static
{ return size ? ImHashData(data, (size_t)size, seed) : ImHashStr((const char*)data, 0, seed); } // [moved to ImHashStr/ImHashData in 1.68]
References ImHashData(), and ImHashStr().
ImHashData()
IMGUI_API ImGuiID ImHashData (const void * data, size_t data_size, ImU32 seed = 0)
{
    ImU32 crc = ~seed;
    const unsigned char* data = (const unsigned char*)data_p;
    const ImU32* crc32_lut = GCrc32LookupTable;
    while (data_size-- != 0)
        crc = (crc >> 8) ^ crc32_lut[(crc & 0xFF) ^ *data++];
    return ~crc;
}
References GCrc32LookupTable.
Referenced by ImGuiWindow::GetID(), ImGuiWindow::GetID(), ImGuiWindow::GetIDFromRectangle(), ImGuiWindow::GetIDNoKeepAlive(), ImGuiWindow::GetIDNoKeepAlive(), ImGui::GetWindowResizeBorderID(), ImGui::GetWindowResizeCornerID(), and ImHash().
ImHashStr()
IMGUI_API ImGuiID ImHashStr (const char * data, size_t data_size = 0, ImU32 seed = 0)
{
    seed = ~seed;
    ImU32 crc = seed;
    const unsigned char* data = (const unsigned char*)data_p;
    const ImU32* crc32_lut = GCrc32LookupTable;
    if (data_size != 0)
    {
        while (data_size-- != 0)
        {
            unsigned char c = *data++;
            if (c == '#' && data_size >= 2 && data[0] == '#' && data[1] == '#')
                crc = seed;
            crc = (crc >> 8) ^ crc32_lut[(crc & 0xFF) ^ c];
        }
    }
    else
    {
        while (unsigned char c = *data++)
        {
            if (c == '#' && data[0] == '#' && data[1] == '#')
                crc = seed;
            crc = (crc >> 8) ^ crc32_lut[(crc & 0xFF) ^ c];
        }
    }
    return ~crc;
}
References GCrc32LookupTable.
Referenced by ImGuiWindow::ImGuiWindow(), ImGui::BeginCombo(), ImGui::BeginDragDropSource(), ImGui::CreateNewWindowSettings(), ImGui::FindOrCreateWindowSettings(), ImGui::FindSettingsHandler(), ImGui::FindWindowByName(), ImGuiWindow::GetID(), ImGuiWindow::GetIDNoKeepAlive(), ImGui::GetIDWithSeed(), ImGui::GetWindowResizeBorderID(), ImGui::GetWindowResizeCornerID(), ImHash(), ImGui::Initialize(), ImGui::TabBarCalcTabID(), ImGui::TableOpenContextMenu(), ImGui::TableSettingsInstallHandler(), and ImGui::TableUpdateLayout().
ImInvLength()
static float ImInvLength (const ImVec2 & lhs, float fail_value) inline static
{ float d = (lhs.x * lhs.x) + (lhs.y * lhs.y); if (d > 0.0f) return ImRsqrt(d); return fail_value; }
References ImRsqrt(), ImVec2::x, and ImVec2::y.
ImIsPowerOfTwo() [1/2]
static bool ImIsPowerOfTwo (ImU64 v) inline static
{ return v != 0 && (v & (v - 1)) == 0; }
ImIsPowerOfTwo() [2/2]
static bool ImIsPowerOfTwo (int v) inline static
{ return v != 0 && (v & (v - 1)) == 0; }
Referenced by ImGui::BeginCombo(), ImGui::ColorEdit4(), ImGui::ColorPicker4(), ImGui::SeparatorEx(), ImGui::SetColorEditOptions(), ImGui::SetNextWindowCollapsed(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), ImGui::SetWindowPos(), ImGui::SetWindowSize(), and TableSetupColumnFlags().
ImLengthSqr() [1/2]
static float ImLengthSqr (const ImVec2 & lhs) inline static
{ return (lhs.x * lhs.x) + (lhs.y * lhs.y); }
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), ImGui::ColorPicker4(), ImGui::EndFrame(), ImBezierCubicClosestPoint(), ImBezierCubicClosestPointCasteljauStep(), ImTriangleClosestPoint(), ImGui::ShadeVertsLinearColorGradientKeepAlpha(), ImGui::UpdateMouseInputs(), and ImGui::UpdateMouseWheel().
ImLengthSqr() [2/2]
static float ImLengthSqr (const ImVec4 & lhs) inline static
{ return (lhs.x * lhs.x) + (lhs.y * lhs.y) + (lhs.z * lhs.z) + (lhs.w * lhs.w); }
References ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
ImLerp() [1/4]
static ImVec2 ImLerp (const ImVec2 & a, const ImVec2 & b, const ImVec2 & t) inline static
{ return ImVec2(a.x + (b.x - a.x) * t.x, a.y + (b.y - a.y) * t.y); }
References ImVec2::x, and ImVec2::y.
ImLerp() [2/4]
static ImVec2 ImLerp (const ImVec2 & a, const ImVec2 & b, float t) inline static
{ return ImVec2(a.x + (b.x - a.x) * t, a.y + (b.y - a.y) * t); }
ImLerp() [3/4]
static ImVec4 ImLerp (const ImVec4 & a, const ImVec4 & b, float t) inline static
{ return ImVec4(a.x + (b.x - a.x) * t, a.y + (b.y - a.y) * t, a.z + (b.z - a.z) * t, a.w + (b.w - a.w) * t); }
ImLerp() [4/4]
template<typename T > static T ImLerp (T a, T b, float t) inline static
{ return (T)(a + (b - a) * t); }
Referenced by CalcResizePosSizeFromAnyCorner(), CalcScrollEdgeSnap(), ImGui::ColorPicker4(), ImGui::GetColumnOffset(), ImAlphaBlendColors(), ImGui::NavScoreItem(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::RenderRectFilledRangeH(), ImGui::RenderWindowDecorations(), ImGui::RenderWindowOuterBorders(), ImGui::ScrollbarEx(), ImGui::SetScrollHereX(), ImGui::SetScrollHereY(), ImGui::StyleColorsClassic(), ImGui::StyleColorsDark(), ImGui::StyleColorsLight(), ImGui::TabItemEx(), and ImGui::UpdateWindowManualResize().
ImLinearSweep()
static float ImLinearSweep (float current, float target, float speed) inline static
{ if (current < target) return ImMin(current + speed, target); if (current > target) return ImMax(current - speed, target); return current; }
References ImMax(), and ImMin().
Referenced by ImGui::TabBarLayout().
ImLineClosestPoint()
IMGUI_API ImVec2 ImLineClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & p)
{
    ImVec2 ap = p - a;
    ImVec2 ab_dir = b - a;
    float dot = ap.x * ab_dir.x + ap.y * ab_dir.y;
    if (dot < 0.0f)
        return a;
    float ab_len_sqr = ab_dir.x * ab_dir.x + ab_dir.y * ab_dir.y;
    if (dot > ab_len_sqr)
        return b;
    return a + ab_dir * dot / ab_len_sqr;
}
References ImVec2::x, and ImVec2::y.
Referenced by ImBezierCubicClosestPoint(), ImBezierCubicClosestPointCasteljauStep(), and ImTriangleClosestPoint().
ImLog() [1/2]
static double ImLog (double x) inline static
{ return log(x); }
References log().
ImLog() [2/2]
static float ImLog (float x) inline static
{ return logf(x); }             // DragBehaviorT/SliderBehaviorT uses ImLog with either float/double and need the precision
ImMax() [1/2]
static ImVec2 ImMax (const ImVec2 & lhs, const ImVec2 & rhs) inline static
{ return ImVec2(lhs.x >= rhs.x ? lhs.x : rhs.x, lhs.y >= rhs.y ? lhs.y : rhs.y); }
References ImVec2::x, and ImVec2::y.
ImMax() [2/2]
template<typename T > static T ImMax (T lhs, T rhs) inline static
{ return lhs >= rhs ? lhs : rhs; }
Referenced by ImDrawList::AddPolyline(), ImDrawList::AddText(), ImGui::AlignTextToFramePadding(), ImGui::ArrowButtonEx(), ImGui::Begin(), ImGui::BeginChildEx(), ImGui::BeginColumns(), ImGui::BeginCombo(), ImGui::BeginListBox(), ImGui::BeginMainMenuBar(), ImGui::BeginMenu(), ImGui::BeginMenuBar(), ImGui::BeginTableEx(), ImFont::BuildLookupTable(), ImGui::Bullet(), ImGuiMenuColumns::CalcExtraSpace(), ImGui::CalcItemSize(), ImGui::CalcItemWidth(), CalcNextScrollFromScrollTargetAndClamp(), ImFont::CalcTextSizeA(), CalcWindowAutoFitSize(), CalcWindowContentSizes(), CalcWindowSizeAfterConstraint(), ImGuiViewportP::CalcWorkRectSize(), ImGui::CalcWrapWidthForPos(), ImGui::Checkbox(), ImRect::ClipWith(), ImGui::CloseButton(), ImGui::CollapsingHeader(), ImGui::ColorEdit4(), ImGui::ColorPicker4(), ImGui::ColorPickerOptionsPopup(), ImGuiMenuColumns::DeclColumns(), ImGui::DragFloatRange2(), ImGui::DragIntRange2(), ImGui::EndChild(), ImGui::EndColumns(), ImGui::EndGroup(), ImGui::EndTabBar(), ImGui::EndTable(), ImGui::FindBestWindowPosForPopupEx(), GetDraggedColumnOffset(), ImGui::GetWindowScrollbarRect(), ImFontAtlasBuildPackCustomRects(), ImFontAtlasBuildWithStbTruetype(), ImLinearSweep(), ImGui::InputScalar(), InputTextCalcTextSizeW(), ImGui::InputTextEx(), ImGuiInputTextCallbackData::InsertChars(), ImGui::ItemSize(), ImGui::LabelTextV(), ImGui::MenuItem(), ImGui::NavEndFrame(), ImGui::NavUpdatePageUpPageDown(), ImGui::NavUpdateWindowing(), ImGui::NewFrame(), ImGui::NextColumn(), ImDrawList::PathArcTo(), ImGui::PlotEx(), ImDrawList::PushClipRect(), ImGui::PushMultiItemsWidths(), ImGui::RadioButton(), ImGui::RenderCheckMark(), ImGui::RenderRectFilledRangeH(), ImGui::RenderTextClippedEx(), ImGui::RenderTextEllipsis(), ImGui::RenderWindowOuterBorders(), ImGui::RenderWindowTitleBarContents(), ImGui::ScrollbarEx(), Slic3r::GUI::selectable(), ImGui::Selectable(), ImGui::SetColumnOffset(), ImGui::SetCurrentFont(), ImGui::SetCursorPos(), ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), SetCursorPosYAndSetupForPrevLine(), ImGui::SetCursorScreenPos(), ImGui::SetScrollHereX(), ImGui::SetScrollHereY(), ImGui::ShadeVertsLinearUV(), ImGui::ShrinkWidths(), ImGui::SplitterBehavior(), ImStb::STB_TEXTEDIT_INSERTCHARS(), ImGui::TabBarLayout(), ImGui::TabBarScrollClamp(), ImGui::TabBarScrollingButtons(), ImGui::TabBarScrollToTab(), ImGui::TabItemBackground(), ImGui::TabItemEx(), ImGui::TableBeginCell(), ImGui::TableEndCell(), ImGui::TableEndRow(), ImGui::TableGetColumnWidthAuto(), ImGui::TableGetHeaderRowHeight(), ImGui::TableHeader(), ImGui::TableMergeDrawChannels(), ImGui::TableNextRow(), ImGui::TableSetColumnSortDirection(), ImGui::TableSetColumnWidth(), ImGui::TableUpdateBorders(), ImGui::TableUpdateLayout(), ImGui::TextEx(), ImGui::TreeNodeBehavior(), ImGui::UpdateHoveredWindowAndCaptureFlags(), ImGui::UpdateMouseInputs(), and ImGui::UpdateWindowManualResize().
ImMin() [1/2]
static ImVec2 ImMin (const ImVec2 & lhs, const ImVec2 & rhs) inline static
{ return ImVec2(lhs.x < rhs.x ? lhs.x : rhs.x, lhs.y < rhs.y ? lhs.y : rhs.y); }
References ImVec2::x, and ImVec2::y.
ImMin() [2/2]
template<typename T > static T ImMin (T lhs, T rhs) inline static
{ return lhs < rhs ? lhs : rhs; }
Referenced by ImDrawList::AddText(), ImGui::BeginColumns(), ImGui::BeginMenu(), ImGui::BeginTableEx(), ImGui::Bullet(), CalcNextScrollFromScrollTargetAndClamp(), CalcWindowAutoFitSize(), ImRect::ClipWith(), ImGui::ColorButton(), ImGuiInputTextState::CursorClamp(), ImGui::DragFloatRange2(), ImGui::DragIntRange2(), ImGui::EndColumns(), ImGui::EndTable(), ImGui::FindBestWindowPosForPopupEx(), GetDraggedColumnOffset(), Slic3r::GUI::image_button_ex(), ImGui::ImageButtonEx(), ImLinearSweep(), ImParseFormatTrimDecorations(), ImTextCharFromUtf8(), ImTriangleClosestPoint(), ImGui::InputTextEx(), ImGui::ListBoxHeader(), ImGui::NavCalcPreferredRefPos(), ImGui::NavUpdate(), ImGui::NavUpdateWindowing(), ImGui::NewFrame(), ImDrawList::PathRect(), ImGui::PlotEx(), ImGui::RenderColorRectWithAlphaCheckerboard(), ImGui::RenderRectFilledRangeH(), ImGui::RenderWindowTitleBarContents(), ImGui::SetColumnOffset(), ImGui::ShadeVertsLinearUV(), ImGui::ShrinkWidths(), ImGui::TabBarLayout(), ImGui::TabBarScrollClamp(), ImGui::TabItemBackground(), ImGui::TabItemCalcSize(), ImGui::TabItemLabelAndCloseButton(), ImGui::TableDrawBorders(), ImGui::TableEndRow(), ImGui::TableMergeDrawChannels(), ImGui::TableUpdateLayout(), ImGui::TreeNodeBehavior(), ImGui::UpdateMouseWheel(), and ImGui::UpdateWindowManualResize().
ImModPositive()
static int ImModPositive (int a, int b) inline static
{ return (a + b) % b; }
Referenced by ImGui::UpdateTabFocus().
ImMul()
static ImVec2 ImMul (const ImVec2 & lhs, const ImVec2 & rhs) inline static
{ return ImVec2(lhs.x * rhs.x, lhs.y * rhs.y); }
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShadeVertsLinearUV().
ImParseFormatFindEnd()
IMGUI_API const char * ImParseFormatFindEnd (const char * format)
{
    // Printf/scanf types modifiers: I/L/h/j/l/t/w/z. Other uppercase letters qualify as types aka end of the format.
    if (fmt[0] != '%')
        return fmt;
    const unsigned int ignored_uppercase_mask = (1 << ('I'-'A')) | (1 << ('L'-'A'));
    const unsigned int ignored_lowercase_mask = (1 << ('h'-'a')) | (1 << ('j'-'a')) | (1 << ('l'-'a')) | (1 << ('t'-'a')) | (1 << ('w'-'a')) | (1 << ('z'-'a'));
    for (char c; (c = *fmt) != 0; fmt++)
    {
        if (c >= 'A' && c <= 'Z' && ((1 << (c - 'A')) & ignored_uppercase_mask) == 0)
            return fmt + 1;
        if (c >= 'a' && c <= 'z' && ((1 << (c - 'a')) & ignored_lowercase_mask) == 0)
            return fmt + 1;
    }
    return fmt;
}
Referenced by ImParseFormatTrimDecorations(), PatchFormatStringFloatToInt(), and SanitizeFormatString().
ImParseFormatFindStart()
IMGUI_API const char * ImParseFormatFindStart (const char * format)
{
    while (char c = fmt[0])
    {
        if (c == '%' && fmt[1] != '%')
            return fmt;
        else if (c == '%')
            fmt++;
        fmt++;
    }
    return fmt;
}
Referenced by ImParseFormatPrecision(), ImParseFormatTrimDecorations(), and PatchFormatStringFloatToInt().
ImParseFormatPrecision()
IMGUI_API int ImParseFormatPrecision (const char * format, int default_value)
{
    fmt = ImParseFormatFindStart(fmt);
    if (fmt[0] != '%')
        return default_precision;
    fmt++;
    while (*fmt >= '0' && *fmt <= '9')
        fmt++;
    int precision = INT_MAX;
    if (*fmt == '.')
    {
        fmt = ImAtoi<int>(fmt + 1, &precision);
        if (precision < 0 || precision > 99)
            precision = default_precision;
    }
    if (*fmt == 'e' || *fmt == 'E') // Maximum precision with scientific notation
        precision = -1;
    if ((*fmt == 'g' || *fmt == 'G') && precision == INT_MAX)
        precision = -1;
    return (precision == INT_MAX) ? default_precision : precision;
}
References ImParseFormatFindStart().
ImParseFormatTrimDecorations()
IMGUI_API const char * ImParseFormatTrimDecorations (const char * format, char * buf, size_t buf_size)
{
    const char* fmt_start = ImParseFormatFindStart(fmt);
    if (fmt_start[0] != '%')
        return fmt;
    const char* fmt_end = ImParseFormatFindEnd(fmt_start);
    if (fmt_end[0] == 0) // If we only have leading decoration, we don't need to copy the data.
        return fmt_start;
    ImStrncpy(buf, fmt_start, ImMin((size_t)(fmt_end - fmt_start) + 1, buf_size));
    return buf;
}
References ImMin(), ImParseFormatFindEnd(), ImParseFormatFindStart(), and ImStrncpy().
Referenced by ImGui::TempInputScalar().
ImPow() [1/2]
static double ImPow (double x, double y) inline static
{ return pow(x, y); }
ImPow() [2/2]
static float ImPow (float x, float y) inline static
{ return powf(x, y); }          // DragBehaviorT/SliderBehaviorT uses ImPow with either float/double and need the precision
Referenced by GetMinimumStepAtDecimalPrecision().
ImRotate()
static ImVec2 ImRotate (const ImVec2 & v, float cos_a, float sin_a) inline static
{ return ImVec2(v.x * cos_a - v.y * sin_a, v.x * sin_a + v.y * cos_a); }
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ColorPicker4().
ImRsqrt() [1/2]
static double ImRsqrt (double x) inline static
{ return 1.0 / sqrt(x); }
References sqrt().
ImRsqrt() [2/2]
static float ImRsqrt (float x) inline static
{ return 1.0f / sqrtf(x); }
Referenced by ImInvLength().
ImSaturate()
static float ImSaturate (float f) inline static
{ return (f < 0.0f) ? 0.0f : (f > 1.0f) ? 1.0f : f; }
Referenced by ImGui::ColorPicker4(), ImGui::NavUpdateWindowing(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::RenderWindowTitleBarContents(), ImGui::ScrollbarEx(), and ImGui::TabItemEx().
ImSign() [1/2]
static double ImSign (double x) inline static
{ return (x < 0.0) ? -1.0 : ((x > 0.0) ? 1.0 : 0.0); }
ImSign() [2/2]
static float ImSign (float x) inline static
{ return (x < 0.0f) ? -1.0f : ((x > 0.0f) ? 1.0f : 0.0f); } // Sign operator - returns -1, 0 or 1 based on sign of argument
ImStrbolW()
IMGUI_API const ImWchar * ImStrbolW (const ImWchar * buf_mid_line, const ImWchar * buf_begin)
{
    while (buf_mid_line > buf_begin && buf_mid_line[-1] != '\n')
        buf_mid_line--;
    return buf_mid_line;
}
Referenced by ImGui::InputTextEx().
ImStrchrRange()
IMGUI_API const char * ImStrchrRange (const char * str_begin, const char * str_end, char c)
{
    const char* p = (const char*)memchr(str, (int)c, str_end - str);
    return p;
}
Referenced by ImGui::LoadIniSettingsFromMemory().
ImStrdup()
IMGUI_API char * ImStrdup (const char * str)
{
    size_t len = strlen(str);
    void* buf = IM_ALLOC(len + 1);
    return (char*)memcpy(buf, (const void*)str, len + 1);
}
References IM_ALLOC.
Referenced by ImGuiWindow::ImGuiWindow().
ImStrdupcpy()
IMGUI_API char * ImStrdupcpy (char * dst, size_t * p_dst_size, const char * str)
{
    size_t dst_buf_size = p_dst_size ? *p_dst_size : strlen(dst) + 1;
    size_t src_size = strlen(src) + 1;
    if (dst_buf_size < src_size)
    {
        IM_FREE(dst);
        dst = (char*)IM_ALLOC(src_size);
        if (p_dst_size)
            *p_dst_size = src_size;
    }
    return (char*)memcpy(dst, (const void*)src, src_size);
}
References IM_ALLOC, and IM_FREE.
Referenced by ImGui::Begin().
ImStreolRange()
IMGUI_API const char * ImStreolRange (const char * str, const char * str_end)
{
    const char* p = (const char*)memchr(str, '\n', str_end - str);
    return p ? p : str_end;
}
Referenced by ImGui::LogRenderedText().
ImStricmp()
IMGUI_API int ImStricmp (const char * str1, const char * str2)
{
    int d;
    while ((d = toupper(*str2) - toupper(*str1)) == 0 && *str1) { str1++; str2++; }
    return d;
}
ImStristr()
IMGUI_API const char * ImStristr (const char * haystack, const char * haystack_end, const char * needle, const char * needle_end)
{
    if (!needle_end)
        needle_end = needle + strlen(needle);
    const char un0 = (char)toupper(*needle);
    while ((!haystack_end && *haystack) || (haystack_end && haystack < haystack_end))
    {
        if (toupper(*haystack) == un0)
        {
            const char* b = needle + 1;
            for (const char* a = haystack + 1; b < needle_end; a++, b++)
                if (toupper(*a) != toupper(*b))
                    break;
            if (b == needle_end)
                return haystack;
        }
        haystack++;
    }
    return NULL;
}
Referenced by ImGuiTextFilter::PassFilter().
ImStrlenW()
IMGUI_API int ImStrlenW (const ImWchar * str)
{
    //return (int)wcslen((const wchar_t*)str);  // FIXME-OPT: Could use this when wchar_t are 16-bit
    int n = 0;
    while (*str++) n++;
    return n;
}
ImStrncpy()
IMGUI_API void ImStrncpy (char * dst, const char * src, size_t count)
{
    if (count < 1)
        return;
    if (count > 1)
        strncpy(dst, src, count - 1);
    dst[count - 1] = 0;
}
Referenced by ImGuiTextFilter::ImGuiTextFilter(), ImParseFormatTrimDecorations(), ImGui::InputTextEx(), and ImGui::SetDragDropPayload().
ImStrnicmp()
IMGUI_API int ImStrnicmp (const char * str1, const char * str2, size_t count)
{
    int d = 0;
    while (count > 0 && (d = toupper(*str2) - toupper(*str1)) == 0 && *str1) { str1++; str2++; count--; }
    return d;
}
ImStrSkipBlank()
IMGUI_API const char * ImStrSkipBlank (const char * str)
{
    while (str[0] == ' ' || str[0] == '\t')
        str++;
    return str;
}
Referenced by TableSettingsHandler_ReadLine().
ImStrTrimBlanks()
IMGUI_API void ImStrTrimBlanks (char * str)
{
    char* p = buf;
    while (p[0] == ' ' || p[0] == '\t')     // Leading blanks
        p++;
    char* p_start = p;
    while (*p != 0)                         // Find end of string
        p++;
    while (p > p_start && (p[-1] == ' ' || p[-1] == '\t'))  // Trailing blanks
        p--;
    if (p_start != buf)                     // Copy memory if we had leading blanks
        memmove(buf, p_start, p - p_start);
    buf[p - p_start] = 0;                   // Zero terminate
}
Referenced by ImGui::TempInputScalar().
ImSubClampOverflow()
template<typename T > static T ImSubClampOverflow (T a, T b, T mn, T mx) inline static
{ if (b > 0 && (a < mn + b)) return mn; if (b < 0 && (a > mx + b)) return mx; return a - b; }
Referenced by ImGui::DataTypeApplyOp().
ImSwap()
template<typename T > static void ImSwap (T & a, T & b) inline static
{ T tmp = a; a = b; b = tmp; }
Referenced by ImGui::ColorConvertRGBtoHSV(), ImGui::RenderRectFilledRangeH(), ImGui::TempInputScalar(), and ImGui::UpdateWindowManualResize().
ImTextCharFromUtf8()
IMGUI_API int ImTextCharFromUtf8 (unsigned int * out_char, const char * in_text, const char * in_text_end)
{
    static const char lengths[32] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 3, 3, 4, 0 };
    static const int masks[]  = { 0x00, 0x7f, 0x1f, 0x0f, 0x07 };
    static const uint32_t mins[] = { 0x400000, 0, 0x80, 0x800, 0x10000 };
    static const int shiftc[] = { 0, 18, 12, 6, 0 };
    static const int shifte[] = { 0, 6, 4, 2, 0 };
    int len = lengths[*(const unsigned char*)in_text >> 3];
    int wanted = len + !len;
    if (in_text_end == NULL)
        in_text_end = in_text + wanted; // Max length, nulls will be taken into account.
    // Copy at most 'len' bytes, stop copying at 0 or past in_text_end. Branch predictor does a good job here,
    // so it is fast even with excessive branching.
    unsigned char s[4];
    s[0] = in_text + 0 < in_text_end ? in_text[0] : 0;
    s[1] = in_text + 1 < in_text_end ? in_text[1] : 0;
    s[2] = in_text + 2 < in_text_end ? in_text[2] : 0;
    s[3] = in_text + 3 < in_text_end ? in_text[3] : 0;
    // Assume a four-byte character and load four bytes. Unused bits are shifted out.
    *out_char  = (uint32_t)(s[0] & masks[len]) << 18;
    *out_char |= (uint32_t)(s[1] & 0x3f) << 12;
    *out_char |= (uint32_t)(s[2] & 0x3f) <<  6;
    *out_char |= (uint32_t)(s[3] & 0x3f) <<  0;
    *out_char >>= shiftc[len];
    // Accumulate the various error conditions.
    int e = 0;
    e  = (*out_char < mins[len]) << 6; // non-canonical encoding
    e |= ((*out_char >> 11) == 0x1b) << 7;  // surrogate half?
    e |= (*out_char > IM_UNICODE_CODEPOINT_MAX) << 8;  // out of range?
    e |= (s[1] & 0xc0) >> 2;
    e |= (s[2] & 0xc0) >> 4;
    e |= (s[3]       ) >> 6;
    e ^= 0x2a; // top two bits of each tail byte correct?
    e >>= shifte[len];
    if (e)
    {
        // No bytes are consumed when *in_text == 0 || in_text == in_text_end.
        // One byte is consumed in case of invalid first byte of in_text.
        // All available bytes (at most `len` bytes) are consumed on incomplete/invalid second to last bytes.
        // Invalid or incomplete input may consume less bytes than wanted, therefore every byte has to be inspected in s.
        wanted = ImMin(wanted, !!s[0] + !!s[1] + !!s[2] + !!s[3]);
        *out_char = IM_UNICODE_CODEPOINT_INVALID;
    }
    return wanted;
}
References IM_UNICODE_CODEPOINT_INVALID, IM_UNICODE_CODEPOINT_MAX, and ImMin().
Referenced by ImGuiIO::AddInputCharactersUTF8(), ImFontGlyphRangesBuilder::AddText(), ImFont::CalcTextSizeA(), ImFont::CalcWordWrapPositionA(), ImTextCountCharsFromUtf8(), ImTextCountUtf8BytesFromChar(), ImTextStrFromUtf8(), ImGui::InputTextEx(), Slic3r::GUI::ImGuiWrapper::is_chars_in_ranges(), and ImFont::RenderText().
ImTextCountCharsFromUtf8()
IMGUI_API int ImTextCountCharsFromUtf8 (const char * in_text, const char * in_text_end)
{
    int char_count = 0;
    while ((!in_text_end || in_text < in_text_end) && *in_text)
    {
        unsigned int c;
        in_text += ImTextCharFromUtf8(&c, in_text, in_text_end);
        if (c == 0)
            break;
        char_count++;
    }
    return char_count;
}
References ImTextCharFromUtf8().
Referenced by ImGui::InputTextEx().
ImTextCountUtf8BytesFromChar()
IMGUI_API int ImTextCountUtf8BytesFromChar (const char * in_text, const char * in_text_end)
{
    unsigned int unused = 0;
    return ImTextCharFromUtf8(&unused, in_text, in_text_end);
}
References ImTextCharFromUtf8().
Referenced by ImTextCountUtf8BytesFromStr(), and ImGui::RenderTextEllipsis().
ImTextCountUtf8BytesFromStr()
IMGUI_API int ImTextCountUtf8BytesFromStr (const ImWchar * in_text, const ImWchar * in_text_end)
{
    int bytes_count = 0;
    while ((!in_text_end || in_text < in_text_end) && *in_text)
    {
        unsigned int c = (unsigned int)(*in_text++);
        if (c < 0x80)
            bytes_count++;
        else
            bytes_count += ImTextCountUtf8BytesFromChar(c);
    }
    return bytes_count;
}
References ImTextCountUtf8BytesFromChar().
Referenced by ImGui::InputTextEx(), ImStb::STB_TEXTEDIT_DELETECHARS(), and ImStb::STB_TEXTEDIT_INSERTCHARS().
ImTextStrFromUtf8()
IMGUI_API int ImTextStrFromUtf8 (ImWchar * buf, int buf_size, const char * in_text, const char * in_text_end, const char ** in_remaining = NULL)
{
    ImWchar* buf_out = buf;
    ImWchar* buf_end = buf + buf_size;
    while (buf_out < buf_end - 1 && (!in_text_end || in_text < in_text_end) && *in_text)
    {
        unsigned int c;
        in_text += ImTextCharFromUtf8(&c, in_text, in_text_end);
        if (c == 0)
            break;
        *buf_out++ = (ImWchar)c;
    }
    *buf_out = 0;
    if (in_text_remaining)
        *in_text_remaining = in_text;
    return (int)(buf_out - buf);
}
References ImTextCharFromUtf8().
Referenced by ImGui::InputTextEx().
ImTextStrToUtf8()
IMGUI_API int ImTextStrToUtf8 (char * buf, int buf_size, const ImWchar * in_text, const ImWchar * in_text_end)
{
    char* buf_out = buf;
    const char* buf_end = buf + buf_size;
    while (buf_out < buf_end - 1 && (!in_text_end || in_text < in_text_end) && *in_text)
    {
        unsigned int c = (unsigned int)(*in_text++);
        if (c < 0x80)
            *buf_out++ = (char)c;
        else
            buf_out += ImTextCharToUtf8(buf_out, (int)(buf_end - buf_out - 1), c);
    }
    *buf_out = 0;
    return (int)(buf_out - buf);
}
References ImTextCharToUtf8().
Referenced by ImGui::InputTextEx().
ImTriangleArea()
float ImTriangleArea (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c) inline
{ return ImFabs((a.x * (b.y - c.y)) + (b.x * (c.y - a.y)) + (c.x * (a.y - b.y))) * 0.5f; }
References ImFabs.
Referenced by ImGui::DebugNodeDrawList().
ImTriangleBarycentricCoords()
IMGUI_API void ImTriangleBarycentricCoords (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p, float & out_u, float & out_v, float & out_w)
{
    ImVec2 v0 = b - a;
    ImVec2 v1 = c - a;
    ImVec2 v2 = p - a;
    const float denom = v0.x * v1.y - v1.x * v0.y;
    out_v = (v2.x * v1.y - v1.x * v2.y) / denom;
    out_w = (v0.x * v2.y - v2.x * v0.y) / denom;
    out_u = 1.0f - out_v - out_w;
}
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ColorPicker4().
ImTriangleClosestPoint()
IMGUI_API ImVec2 ImTriangleClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)
{
    ImVec2 proj_ab = ImLineClosestPoint(a, b, p);
    ImVec2 proj_bc = ImLineClosestPoint(b, c, p);
    ImVec2 proj_ca = ImLineClosestPoint(c, a, p);
    float dist2_ab = ImLengthSqr(p - proj_ab);
    float dist2_bc = ImLengthSqr(p - proj_bc);
    float dist2_ca = ImLengthSqr(p - proj_ca);
    float m = ImMin(dist2_ab, ImMin(dist2_bc, dist2_ca));
    if (m == dist2_ab)
        return proj_ab;
    if (m == dist2_bc)
        return proj_bc;
    return proj_ca;
}
References ImLengthSqr(), ImLineClosestPoint(), and ImMin().
Referenced by ImGui::ColorPicker4().
ImTriangleContainsPoint()
IMGUI_API bool ImTriangleContainsPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)
{
    bool b1 = ((p.x - b.x) * (a.y - b.y) - (p.y - b.y) * (a.x - b.x)) < 0.0f;
    bool b2 = ((p.x - c.x) * (b.y - c.y) - (p.y - c.y) * (b.x - c.x)) < 0.0f;
    bool b3 = ((p.x - a.x) * (c.y - a.y) - (p.y - a.y) * (c.x - a.x)) < 0.0f;
    return ((b1 == b2) && (b2 == b3));
}
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::BeginMenu(), and ImGui::ColorPicker4().
ImUpperPowerOfTwo()
static int ImUpperPowerOfTwo (int v) inline static
{ v--; v |= v >> 1; v |= v >> 2; v |= v >> 4; v |= v >> 8; v |= v >> 16; v++; return v; }
Referenced by ImFontAtlasBuildWithStbTruetype().
Variable Documentation
GImGui
IMGUI_API ImGuiContext* GImGui extern
Referenced by ImGui::AcceptDragDropPayload(), ImGui::ActivateItem(), AddWindowToDrawData(), ImGui::AlignTextToFramePadding(), ImGui::ArrowButtonEx(), ImGuiLastItemDataBackup::Backup(), ImGui::Begin(), ImGuiListClipper::Begin(), ImGui::BeginChildEx(), ImGui::BeginChildFrame(), ImGui::BeginColumns(), ImGui::BeginCombo(), ImGui::BeginDragDropSource(), ImGui::BeginDragDropTarget(), ImGui::BeginDragDropTargetCustom(), ImGui::BeginGroup(), ImGui::BeginListBox(), ImGui::BeginMainMenuBar(), ImGui::BeginMenu(), ImGui::BeginPopup(), ImGui::BeginPopupContextItem(), ImGui::BeginPopupContextVoid(), ImGui::BeginPopupContextWindow(), ImGui::BeginPopupEx(), ImGui::BeginPopupModal(), ImGui::BeginTabBar(), ImGui::BeginTabBarEx(), ImGui::BeginTabItem(), ImGui::BeginTableEx(), ImGui::BeginTooltipEx(), ImGui::BringWindowToDisplayBack(), ImGui::BringWindowToDisplayFront(), ImGui::BringWindowToFocusFront(), ImGui::Bullet(), ImGui::BulletTextV(), ImGui::ButtonBehavior(), ImGui::ButtonEx(), Slic3r::GUI::ImGuiWrapper::calc_button_size(), ImGuiWindow::CalcFontSize(), ImGui::CalcItemSize(), ImGui::CalcItemWidth(), ImGui::CalcListClipping(), CalcMaxPopupHeightFromItemCount(), ImGui::CalcTextSize(), CalcWindowAutoFitSize(), CalcWindowSizeAfterConstraint(), ImGui::CalcWrapWidthForPos(), ImGui::CaptureKeyboardFromApp(), ImGui::CaptureMouseFromApp(), ImGui::Checkbox(), ClampWindowRect(), ImGui::ClearDragDrop(), ImGui::ClearIniSettings(), ImGui::CloseButton(), ImGui::CloseCurrentPopup(), ImGui::ClosePopupsOverWindow(), ImGui::ClosePopupToLevel(), ImGui::CollapseButton(), ImGui::CollapsingHeader(), ImGui::ColorButton(), ImGui::ColorEdit4(), ImGui::ColorEditOptionsPopup(), ImGui::ColorPicker4(), ImGui::ColorPickerOptionsPopup(), ImGui::ColorTooltip(), ImGuiStackSizes::CompareWithCurrentState(), ImGui::CreateContext(), CreateNewWindow(), ImGui::CreateNewWindowSettings(), ImGui::DebugDrawItemRect(), ImGui::DebugNodeDrawList(), ImGui::DebugNodeWindow(), ImGui::DebugRenderViewportThumbnail(), ImGui::DebugStartItemPicker(), ImGui::DestroyContext(), Slic3r::GUI::ImGuiWrapper::disable_background_fadeout_animation(), ImGui::DragBehavior(), ImGui::DragFloatRange2(), ImGui::DragIntRange2(), ImGui::DragScalar(), ImGui::DragScalarN(), Slic3r::GUI::ImGuiWrapper::draw_radio_button(), ImGui::End(), ImGui::EndChild(), ImGui::EndColumns(), ImGui::EndDragDropSource(), ImGui::EndDragDropTarget(), ImGui::EndFrame(), ImGui::EndGroup(), ImGui::EndListBox(), ImGui::EndMainMenuBar(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndPopup(), ImGui::EndTabBar(), ImGui::EndTabItem(), ImGui::EndTable(), ImGui::ErrorCheckEndFrameRecover(), ImGui::ErrorCheckEndFrameSanityChecks(), ImGui::ErrorCheckNewFrameSanityChecks(), ImGui::FindBestWindowPosForPopup(), FindHoveredWindow(), ImGui::FindSettingsHandler(), ImGui::FindWindowByID(), ImGui::FindWindowFocusIndex(), FindWindowNavFocusable(), ImGui::FindWindowSettings(), ImGui::FocusTopMostWindowUnderOne(), ImGui::FocusWindow(), ImGui::GcCompactTransientMiscBuffers(), Slic3r::GUI::ImGuiWrapper::get_item_spacing(), Slic3r::GUI::ImGuiWrapper::get_slider_float_height(), ImGui::GetActiveID(), ImGui::GetBackgroundDrawList(), ImGui::GetClipboardText(), GetClipboardTextFn_DefaultImpl(), ImGui::GetColorU32(), ImGui::GetColorU32(), ImGui::GetColorU32(), ImGui::GetColumnWidth(), ImGui::GetContentRegionAvail(), ImGui::GetContentRegionMax(), ImGui::GetContentRegionMaxAbs(), ImGui::GetCurrentContext(), ImGui::GetCurrentTable(), ImGui::GetCurrentWindow(), ImGui::GetCurrentWindowRead(), ImGui::GetDefaultFont(), ImGui::GetDragDropPayload(), GetDraggedColumnOffset(), ImGui::GetDrawData(), ImGui::GetDrawListSharedData(), ImGui::GetFocusedFocusScope(), ImGui::GetFocusID(), ImGui::GetFocusScope(), ImGui::GetFont(), ImGui::GetFontSize(), ImGui::GetFontTexUvWhitePixel(), ImGui::GetForegroundDrawList(), ImGui::GetFrameCount(), ImGui::GetFrameHeight(), ImGui::GetFrameHeightWithSpacing(), ImGui::GetHoveredID(), ImGuiWindow::GetID(), ImGui::GetID(), ImGui::GetID(), ImGuiWindow::GetID(), ImGui::GetID(), ImGuiWindow::GetID(), ImGuiWindow::GetIDNoKeepAlive(), ImGuiWindow::GetIDNoKeepAlive(), ImGuiWindow::GetIDNoKeepAlive(), ImGui::GetIDWithSeed(), ImGui::GetInputTextState(), ImGui::GetIO(), ImGui::GetItemFlags(), ImGui::GetItemID(), ImGui::GetItemStatusFlags(), ImGui::GetKeyIndex(), ImGui::GetKeyPressedAmount(), ImGui::GetMainViewport(), ImGui::GetMergedKeyModFlags(), ImGui::GetMouseCursor(), ImGui::GetMouseDragDelta(), ImGui::GetMousePos(), ImGui::GetMousePosOnOpeningCurrentPopup(), ImGui::GetNavInputAmount(), ImGui::GetScrollMaxX(), ImGui::GetScrollMaxY(), ImGui::GetScrollX(), ImGui::GetScrollY(), GetSkipItemForListClipping(), ImGui::GetStateStorage(), ImGui::GetStyle(), ImGui::GetStyleColorVec4(), GetTabBarFromTabBarRef(), GetTabBarRefFromTabBar(), ImGui::GetTextLineHeight(), ImGui::GetTextLineHeightWithSpacing(), ImGui::GetTime(), ImGui::GetTopMostPopupModal(), ImGui::GetTreeNodeToLabelSpacing(), GetViewportDrawList(), ImGui::GetWindowAllowedExtentRect(), ImGui::GetWindowContentRegionMax(), ImGui::GetWindowContentRegionMin(), ImGui::GetWindowContentRegionWidth(), ImGui::GetWindowHeight(), ImGui::GetWindowPos(), ImGui::GetWindowWidth(), Slic3r::GUI::ImGuiWrapper::image_button(), Slic3r::GUI::image_button_ex(), ImGui::ImageButton(), ImGui::ImageButtonEx(), ImGui::Indent(), ImGui::InputScalar(), ImGui::InputScalarN(), InputTextCalcTextSizeW(), ImGui::InputTextEx(), InputTextFilterCharacter(), ImGuiInputTextCallbackData::InsertChars(), ImGui::IsActiveIdUsingKey(), ImGui::IsActiveIdUsingNavDir(), ImGui::IsActiveIdUsingNavInput(), ImGui::IsAnyItemActive(), ImGui::IsAnyItemFocused(), ImGui::IsAnyItemHovered(), ImGui::IsAnyMouseDown(), ImGui::IsClippedEx(), ImGui::IsDragDropPayloadBeingAccepted(), ImGui::IsItemActivated(), ImGui::IsItemActive(), ImGui::IsItemDeactivated(), ImGui::IsItemDeactivatedAfterEdit(), ImGui::IsItemFocused(), ImGui::IsItemHovered(), ImGui::IsItemToggledOpen(), ImGui::IsItemToggledSelection(), ImGui::IsKeyDown(), ImGui::IsKeyPressed(), ImGui::IsKeyPressedMap(), ImGui::IsKeyReleased(), ImGui::IsMouseClicked(), ImGui::IsMouseDoubleClicked(), ImGui::IsMouseDown(), ImGui::IsMouseDragging(), ImGui::IsMouseDragPastThreshold(), ImGui::IsMouseHoveringRect(), ImGui::IsMousePosValid(), ImGui::IsMouseReleased(), ImGui::IsNavInputDown(), ImGui::IsPopupOpen(), ImGui::IsPopupOpen(), ImGui::IsRectVisible(), ImGui::IsRectVisible(), ImGui::IsWindowAbove(), IsWindowContentHoverable(), ImGui::IsWindowFocused(), ImGui::IsWindowHovered(), ImGui::ItemAdd(), ImGui::ItemFocusable(), ImGui::ItemHoverable(), ImGui::ItemSize(), ImGui::KeepAliveID(), ImGui::LabelTextV(), ImGui::ListBoxHeader(), ImGui::LoadIniSettingsFromMemory(), ImGui::LogBegin(), ImGui::LogButtons(), ImGui::LogFinish(), ImGui::LogRenderedText(), ImGui::LogSetNextTextDecoration(), ImGui::LogText(), ImGui::LogTextV(), ImGui::LogToBuffer(), ImGui::LogToClipboard(), ImGui::LogToFile(), ImGui::LogToTTY(), ImGui::MarkIniSettingsDirty(), ImGui::MarkIniSettingsDirty(), ImGui::MarkItemEdited(), ImGui::MemAlloc(), ImGui::MemFree(), ImGuiWindow::MenuBarHeight(), ImGui::MenuItem(), ImGui::NavCalcPreferredRefPos(), ImGui::NavEndFrame(), ImGui::NavInitWindow(), ImGui::NavMoveRequestButNoResultYet(), ImGui::NavMoveRequestCancel(), ImGui::NavMoveRequestForward(), ImGui::NavMoveRequestTryWrapping(), ImGui::NavProcessItem(), ImGui::NavRestoreLayer(), ImGui::NavScoreItem(), ImGui::NavUpdate(), ImGui::NavUpdateAnyRequestFlag(), ImGui::NavUpdateInitResult(), ImGui::NavUpdateMoveResult(), ImGui::NavUpdatePageUpPageDown(), ImGui::NavUpdateWindowing(), NavUpdateWindowingHighlightWindow(), ImGui::NavUpdateWindowingOverlay(), ImGui::NewFrame(), ImGui::NewLine(), ImGui::NextColumn(), ImGui::OpenPopup(), ImGui::OpenPopupEx(), ImGui::OpenPopupOnItemClick(), PatchFormatStringFloatToInt(), ImGui::PlotEx(), ImGui::PopFocusScope(), ImGui::PopFont(), ImGui::PopID(), ImGui::PopItemFlag(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), Slic3r::GUI::process_key_down(), ImGui::ProgressBar(), ImGui::PushFocusScope(), ImGui::PushFont(), ImGui::PushID(), ImGui::PushID(), ImGui::PushID(), ImGui::PushID(), ImGui::PushItemFlag(), ImGui::PushItemWidth(), ImGui::PushMultiItemsWidths(), ImGui::PushOverrideID(), ImGui::PushStyleColor(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::PushStyleVar(), ImGui::RadioButton(), ImGui::Render(), ImGui::RenderFrame(), ImGui::RenderFrameBorder(), ImGui::RenderNavHighlight(), ImGui::RenderText(), ImGui::RenderTextClipped(), ImGui::RenderTextEllipsis(), ImGui::RenderTextWrapped(), RenderViewportsThumbnails(), ImGui::RenderWindowDecorations(), ImGui::RenderWindowOuterBorders(), ImGui::RenderWindowTitleBarContents(), ImGui::ResetMouseDragDelta(), ImGuiLastItemDataBackup::Restore(), ImGui::SameLine(), ImGui::SaveIniSettingsToDisk(), ImGui::SaveIniSettingsToMemory(), Slic3r::GUI::scroll_down(), Slic3r::GUI::scroll_up(), Slic3r::GUI::scroll_y(), ImGui::Scrollbar(), ImGui::ScrollbarEx(), ImGui::ScrollToBringRectIntoView(), Slic3r::GUI::ImGuiWrapper::search_list(), Slic3r::GUI::selectable(), ImGui::Selectable(), ImGui::Separator(), ImGui::SeparatorEx(), ImGui::SetActiveID(), ImGui::SetClipboardText(), SetClipboardTextFn_DefaultImpl(), ImGui::SetColorEditOptions(), ImGui::SetColumnOffset(), ImGui::SetCurrentContext(), ImGui::SetCurrentFont(), SetCurrentWindow(), SetCursorPosYAndSetupForPrevLine(), ImGui::SetDragDropPayload(), ImGui::SetFocusID(), ImGui::SetHoveredID(), ImGui::SetItemAllowOverlap(), ImGui::SetItemDefaultFocus(), ImGui::SetItemUsingMouseWheel(), ImGui::SetKeyboardFocusHere(), ImGui::SetMouseCursor(), ImGui::SetNavID(), ImGui::SetNextItemOpen(), ImGui::SetNextItemWidth(), ImGui::SetNextWindowBgAlpha(), ImGui::SetNextWindowCollapsed(), ImGui::SetNextWindowContentSize(), ImGui::SetNextWindowFocus(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowScroll(), ImGui::SetNextWindowSize(), ImGui::SetNextWindowSizeConstraints(), ImGui::SetScrollFromPosX(), ImGui::SetScrollFromPosY(), ImGui::SetScrollHereX(), ImGui::SetScrollHereY(), ImGui::SetScrollX(), ImGui::SetScrollY(), ImGui::SetStateStorage(), ImGui::SetTabItemClosed(), ImGuiStackSizes::SetToCurrentState(), ImGui::SetWindowCollapsed(), ImGui::SetWindowFocus(), ImGui::SetWindowFontScale(), ImGui::SetWindowSize(), ImGui::ShowMetricsWindow(), ImGui::Shutdown(), ImGui::SliderBehavior(), ImGui::SliderScalar(), ImGui::SliderScalarN(), ImGui::SmallButton(), ImGui::SplitterBehavior(), StartLockWheelingWindow(), ImGui::StartMouseMovingWindow(), ImStb::STB_TEXTEDIT_GETWIDTH(), ImGuiListClipper::Step(), ImGui::TabBarCalcMaxTabWidth(), ImGui::TabBarCalcTabID(), ImGui::TabBarLayout(), ImGui::TabBarQueueReorderFromMousePos(), ImGui::TabBarScrollingButtons(), ImGui::TabBarScrollToTab(), ImGui::TabBarTabListPopupButton(), ImGui::TabItemBackground(), ImGui::TabItemButton(), ImGui::TabItemCalcSize(), ImGui::TabItemEx(), ImGui::TabItemLabelAndCloseButton(), ImGui::TableBeginCell(), ImGui::TableDrawContextMenu(), ImGui::TableEndRow(), ImGui::TableFindByID(), ImGui::TableGcCompactSettings(), ImGui::TableGcCompactTransientBuffers(), ImGui::TableGetBoundSettings(), ImGui::TableGetColumnCount(), ImGui::TableGetColumnFlags(), ImGui::TableGetColumnIndex(), ImGui::TableGetColumnName(), ImGui::TableGetHoveredColumn(), ImGui::TableGetRowIndex(), ImGui::TableGetSortSpecs(), ImGui::TableHeader(), ImGui::TableHeadersRow(), ImGui::TableLoadSettings(), ImGui::TableMergeDrawChannels(), ImGui::TableNextColumn(), ImGui::TableNextRow(), ImGui::TableOpenContextMenu(), ImGui::TablePopBackgroundChannel(), ImGui::TablePushBackgroundChannel(), ImGui::TableRemove(), ImGui::TableSaveSettings(), ImGui::TableSetBgColor(), ImGui::TableSetColumnEnabled(), ImGui::TableSetColumnIndex(), ImGui::TableSetColumnSortDirection(), ImGui::TableSetColumnWidth(), ImGui::TableSettingsCreate(), ImGui::TableSettingsFindByID(), ImGui::TableSetupColumn(), ImGui::TableSetupScrollFreeze(), ImGui::TableUpdateBorders(), ImGui::TableUpdateLayout(), ImGui::TempInputIsActive(), ImGui::TempInputScalar(), ImGui::TempInputText(), ImGui::TextDisabledV(), ImGui::TextEx(), ImGui::TextV(), ImGui::TextWrappedV(), ImGuiWindow::TitleBarHeight(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeBehaviorIsOpen(), ImGui::TreeNodeExV(), ImGui::TreeNodeExV(), ImGui::TreePop(), ImGui::TreePushOverrideID(), ImGui::Unindent(), ImGui::UpdateDebugToolItemPicker(), ImGui::UpdateHoveredWindowAndCaptureFlags(), ImGui::UpdateMouseInputs(), ImGui::UpdateMouseMovingWindowEndFrame(), ImGui::UpdateMouseMovingWindowNewFrame(), ImGui::UpdateMouseWheel(), ImGui::UpdateSettings(), ImGui::UpdateTabFocus(), ImGui::UpdateViewportsNewFrame(), ImGui::UpdateWindowManualResize(), and ImGui::VSliderScalar().