Prusa Slicer: Slic3r::GUI::IconManager Class Reference
Slic3r::GUI::IconManager Class Reference
Keep texture with icons for UI Manage texture live -> create and destruct texture by live of icon shared pointers.
#include <src/slic3r/GUI/IconManager.hpp>
Classes
struct Icon
Data for render texture with icon.
struct InitType
Public Types
enum class RasterType : int { color = 1 << 1 , white_only_data = 1 << 2 , gray_only_data = 1 << 3 , color_wite_gray = color | white_only_data | gray_only_data }
Define way to convert svg data to raster.
using InitTypes = std::vector< InitType >
using Icons = std::vector< std::shared_ptr< Icon > >
using VIcons = std::vector< Icons >
Public Member Functions
~IconManager ()
Release texture Set shared pointers to invalid texture.
VIcons init (const InitTypes &input)
Initialize raster texture on GPU with given images NOTE: Have to be called after OpenGL initialization.
VIcons init (const std::vector< std::string > &file_paths, const ImVec2 &size, RasterType type=RasterType::color)
Initialize multiple icons with same settings for size and type NOTE: Have to be called after OpenGL initialization.
void release ()
Release icons which are hold only by this manager May change texture and position of icons.
Private Attributes
GLTexture m_icons_texture
Icons m_icons
Detailed Description
Keep texture with icons for UI Manage texture live -> create and destruct texture by live of icon shared pointers.
Class Documentation
Slic3r::GUI::IconManager::InitType
struct Slic3r::GUI::IconManager::InitType
Class Members
string filepath
ImVec2 size
RasterType type = RasterType::color
Member Typedef Documentation
Icons
using Slic3r::GUI::IconManager::Icons = std::vector<std::shared_ptr<Icon> >
InitTypes
using Slic3r::GUI::IconManager::InitTypes = std::vector<InitType>
VIcons
using Slic3r::GUI::IconManager::VIcons = std::vector<Icons>
Member Enumeration Documentation
RasterType
enum class Slic3r::GUI::IconManager::RasterType : int strong
Define way to convert svg data to raster.
Enumerator
color
white_only_data
gray_only_data
color_wite_gray
                         : int{
        color           = 1 << 1,
        white_only_data = 1 << 2,
        gray_only_data  = 1 << 3,
        color_wite_gray = color | white_only_data | gray_only_data
        // TODO: add type with backgrounds
    };
Constructor & Destructor Documentation
~IconManager()
IconManager::~IconManager ()
Release texture Set shared pointers to invalid texture.
{
  priv::clear(m_icons);
  // release opengl texture is made in ~GLTexture()
}
References priv::clear(), and m_icons.
Member Function Documentation
init() [1/2]
std::vector< IconManager::Icons > IconManager::init (const InitTypes & input)
Initialize raster texture on GPU with given images NOTE: Have to be called after OpenGL initialization.
Parameters
input Define files and its
Returns
Rasterized icons stored on GPU, Same size and order as input, each item of vector is set of texture in order by RasterType
{
    BOOST_LOG_TRIVIAL(error) << "Not implemented yet";
    return {};
}
References error.
Referenced by Slic3r::GUI::GLGizmoEmboss::init_icons().
init() [2/2]
std::vector< IconManager::Icons > IconManager::init (const std::vector< std::string > & file_paths, const ImVec2 & size, RasterType type = RasterType::color)
Initialize multiple icons with same settings for size and type NOTE: Have to be called after OpenGL initialization.
Parameters
file_paths Define files with icon
size Size of stored texture[in px], float will be rounded
type Define way to rasterize icon, together color, white and gray = RasterType::color | RasterType::white_only_data | RasterType::gray_only_data
Returns
Rasterized icons stored on GPU, Same size and order as file_paths, each item of vector is set of texture in order by RasterType
{
    // TODO: remove in future
    if (!m_icons.empty()) {
        // not first initialization
        priv::clear(m_icons);
        m_icons.clear();
        m_icons_texture.reset();
    }
    // only rectangle are supported
    assert(size.x == size.y);
    // no subpixel supported
    unsigned int width = static_cast<unsigned int>(std::abs(std::round(size.x)));
    assert(size.x == static_cast<float>(width));
    // state order has to match the enum IconState
    const auto& states = priv::get_states(type);
    bool compress  = false;
    bool is_loaded = m_icons_texture.load_from_svg_files_as_sprites_array(file_paths, states, width, compress);
    if (!is_loaded || (size_t) m_icons_texture.get_width() < (states.size() * width) ||
        (size_t) m_icons_texture.get_height() < (file_paths.size() * width)) {
        // bad load of icons, but all usage of m_icons_texture check that texture is initialized
        assert(false);
        m_icons_texture.reset();
        return {};
    }
    unsigned count_files = file_paths.size();
    // count icons per file
    unsigned count = states.size();
    // create result
    std::vector<Icons> result;
    result.reserve(count_files);
    Icon def_icon;
    def_icon.tex_id = m_icons_texture.get_id();
    def_icon.size   = size;
    // float beacouse of dividing
    float tex_height = static_cast<float>(m_icons_texture.get_height());
    float tex_width = static_cast<float>(m_icons_texture.get_width());
    //for (const auto &f: file_paths) {
    for (unsigned f = 0; f < count_files; ++f) {
        // NOTE: there are space between icons
        unsigned start_y = static_cast<unsigned>(f) * (width + 1) + 1;
        float y1 = start_y / tex_height;
        float y2 = (start_y + width) / tex_height;
        Icons file_icons;
        file_icons.reserve(count);
        //for (const auto &s : states) {
        for (unsigned j = 0; j < count; ++j) {
            auto icon = std::make_shared<Icon>(def_icon);
            // NOTE: there are space between icons
            unsigned start_x = static_cast<unsigned>(j) * (width + 1) + 1;
            float x1 = start_x / tex_width;
            float x2 = (start_x + width) / tex_width;
            icon->tl = ImVec2(x1, y1);
            icon->br = ImVec2(x2, y2);
            file_icons.push_back(icon);
            m_icons.push_back(std::move(icon));
        }
        result.emplace_back(std::move(file_icons));
    }
  return result;
}
References priv::clear(), compress, Slic3r::f(), Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_id(), priv::get_states(), Slic3r::GUI::GLTexture::get_width(), Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), m_icons, m_icons_texture, Slic3r::GUI::GLTexture::reset(), Slic3r::GUI::IconManager::Icon::size, and Slic3r::GUI::IconManager::Icon::tex_id.
release()
void IconManager::release ()
Release icons which are hold only by this manager May change texture and position of icons.
{
  BOOST_LOG_TRIVIAL(error) << "Not implemented yet";
}
References error.
Member Data Documentation
m_icons
Icons Slic3r::GUI::IconManager::m_icons private
Referenced by ~IconManager(), and init().
m_icons_texture
GLTexture Slic3r::GUI::IconManager::m_icons_texture private
Referenced by init().
The documentation for this class was generated from the following files:
src/slic3r/GUI/IconManager.hpp
src/slic3r/GUI/IconManager.cpp