Prusa Slicer: Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true > Struct Template Reference
Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true > Struct Template Reference
#include <src/eigen/Eigen/src/SparseCore/SparseDenseProduct.h>
Public Types
typedef internal::remove_all< SparseLhsType >::type Lhs
typedef internal::remove_all< DenseRhsType >::type Rhs
typedef internal::remove_all< DenseResType >::type Res
typedef evaluator< Lhs >::InnerIterator LhsInnerIterator
typedef evaluator< Lhs > LhsEval
Static Public Member Functions
static void run (const SparseLhsType &lhs, const DenseRhsType &rhs, DenseResType &res, const typename Res::Scalar &alpha)
static void processRow (const LhsEval &lhsEval, const DenseRhsType &rhs, DenseResType &res, const typename Res::Scalar &alpha, Index i, Index col)
Detailed Description
template<typename SparseLhsType, typename DenseRhsType, typename DenseResType>
struct Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >
Member Typedef Documentation
Lhs
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef internal::remove_all<SparseLhsType>::type Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::Lhs
LhsEval
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef evaluator<Lhs> Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::LhsEval
LhsInnerIterator
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef evaluator<Lhs>::InnerIterator Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::LhsInnerIterator
Res
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef internal::remove_all<DenseResType>::type Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::Res
Rhs
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > typedef internal::remove_all<DenseRhsType>::type Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::Rhs
Member Function Documentation
processRow()
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > static void Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::processRow (const LhsEval & lhsEval, const DenseRhsType & rhs, DenseResType & res, const typename Res::Scalar & alpha, Index i, Index col) inline static
  {
    typename Res::Scalar tmp(0);
    for(LhsInnerIterator it(lhsEval,i); it ;++it)
      tmp += it.value() * rhs.coeff(it.index(),col);
    res.coeffRef(i,col) += alpha * tmp;
  }
References col().
run()
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType > static void Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::run (const SparseLhsType & lhs, const DenseRhsType & rhs, DenseResType & res, const typename Res::Scalar & alpha) inline static
  {
    LhsEval lhsEval(lhs);
    Index n = lhs.outerSize();
#ifdef EIGEN_HAS_OPENMP
    Eigen::initParallel();
    Index threads = Eigen::nbThreads();
#endif
    for(Index c=0; c<rhs.cols(); ++c)
    {
#ifdef EIGEN_HAS_OPENMP
      // This 20000 threshold has been found experimentally on 2D and 3D Poisson problems.
      // It basically represents the minimal amount of work to be done to be worth it.
      if(threads>1 && lhsEval.nonZerosEstimate() > 20000)
      {
        #pragma omp parallel for schedule(dynamic,(n+threads*4-1)/(threads*4)) num_threads(threads)
        for(Index i=0; i<n; ++i)
          processRow(lhsEval,rhs,res,alpha,i,c);
      }
      else
#endif
      {
        for(Index i=0; i<n; ++i)
          processRow(lhsEval,rhs,res,alpha,i,c);
      }
    }
  }
References Eigen::initParallel(), and Eigen::nbThreads().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseDenseProduct.h