Prusa Slicer: Slic3r::GUI::Camera Struct Reference
Slic3r::GUI::Camera Struct Reference
#include <src/slic3r/GUI/Camera.hpp>
Public Types
enum class EType : unsigned char { Unknown , Ortho , Perspective , Num_types }
Public Member Functions
Camera ()
EType get_type () const
std::string get_type_as_string () const
void set_type (EType type)
void set_type (const std::string &type)
void select_next_type ()
void enable_update_config_on_type_change (bool enable)
const Vec3d & get_target () const
void set_target (const Vec3d &target)
double get_distance () const
double get_gui_scale () const
double get_zoom () const
double get_inv_zoom () const
void update_zoom (double delta_zoom)
void set_zoom (double zoom)
const BoundingBoxf3 & get_scene_box () const
void set_scene_box (const BoundingBoxf3 &box)
void select_view (const std::string &direction)
const std::array< int, 4 > & get_viewport () const
const Transform3d & get_view_matrix () const
const Transform3d & get_projection_matrix () const
Vec3d get_dir_right () const
Vec3d get_dir_up () const
Vec3d get_dir_forward () const
Vec3d get_position () const
double get_near_z () const
double get_far_z () const
const std::pair< double, double > & get_z_range () const
double get_near_left () const
double get_near_right () const
double get_near_top () const
double get_near_bottom () const
double get_near_width () const
double get_near_height () const
double get_fov () const
void set_viewport (int x, int y, unsigned int w, unsigned int h)
void apply_viewport () const
void apply_projection (const BoundingBoxf3 &box, double near_z=-1.0, double far_z=-1.0)
void apply_projection (double left, double right, double bottom, double top, double near_z, double far_z)
void zoom_to_box (const BoundingBoxf3 &box, double margin_factor=DefaultZoomToBoxMarginFactor)
void zoom_to_volumes (const GLVolumePtrs &volumes, double margin_factor=DefaultZoomToVolumesMarginFactor)
void translate_world (const Vec3d &displacement)
void rotate_on_sphere (double delta_azimut_rad, double delta_zenit_rad, bool apply_limits)
void rotate_local_around_target (const Vec3d &rotation_rad)
bool is_looking_downward () const
void recover_from_free_camera ()
void look_at (const Vec3d &position, const Vec3d &target, const Vec3d &up)
double max_zoom () const
double min_zoom () const
Public Attributes
bool requires_zoom_to_bed { false }
Static Public Attributes
static const double DefaultDistance = 1000.0
static const double DefaultZoomToBoxMarginFactor = 1.025
static const double DefaultZoomToVolumesMarginFactor = 1.025
static double FrustrumMinZRange = 50.0
static double FrustrumMinNearZ = 100.0
static double FrustrumZMargin = 10.0
static double MaxFovDeg = 60.0
Private Member Functions
std::pair< double, double > calc_tight_frustrum_zs_around (const BoundingBoxf3 &box)
double calc_zoom_to_bounding_box_factor (const BoundingBoxf3 &box, double margin_factor=DefaultZoomToBoxMarginFactor) const
double calc_zoom_to_volumes_factor (const GLVolumePtrs &volumes, Vec3d &center, double margin_factor=DefaultZoomToVolumesMarginFactor) const
void set_distance (double distance)
void set_default_orientation ()
Vec3d validate_target (const Vec3d &target) const
void update_zenit ()
Private Attributes
EType m_type { EType::Perspective }
bool m_update_config_on_type_change_enabled { false }
Vec3d m_target { Vec3d::Zero() }
float m_zenit { 45.0f }
double m_zoom { 1.0 }
double m_distance { DefaultDistance }
double m_gui_scale { 1.0 }
std::array< int, 4 > m_viewport
Transform3d m_view_matrix { Transform3d::Identity() }
Eigen::Quaterniond m_view_rotation { 1.0, 0.0, 0.0, 0.0 }
Transform3d m_projection_matrix { Transform3d::Identity() }
std::pair< double, double > m_frustrum_zs
BoundingBoxf3 m_scene_box
Detailed Description
Member Enumeration Documentation
EType
enum class Slic3r::GUI::Camera::EType : unsigned char strong
Enumerator
Unknown
Ortho
Perspective
Num_types
    {
        Unknown,
        Ortho,
        Perspective,
        Num_types
    };
Constructor & Destructor Documentation
Camera()
Slic3r::GUI::Camera::Camera () inline
{ set_default_orientation(); }
References set_default_orientation().
Member Function Documentation
apply_projection() [1/2]
void Slic3r::GUI::Camera::apply_projection (const BoundingBoxf3 & box, double near_z = -1.0, double far_z = -1.0)
{
    double w = 0.0;
    double h = 0.0;
    m_frustrum_zs = calc_tight_frustrum_zs_around(box);
    if (near_z > 0.0)
        m_frustrum_zs.first = std::max(std::min(m_frustrum_zs.first, near_z), FrustrumMinNearZ);
    if (far_z > 0.0)
        m_frustrum_zs.second = std::max(m_frustrum_zs.second, far_z);
    w = 0.5 * (double)m_viewport[2];
    h = 0.5 * (double)m_viewport[3];
    const double inv_zoom = get_inv_zoom();
    w *= inv_zoom;
    h *= inv_zoom;
    switch (m_type)
    {
    default:
    case EType::Ortho:
    {
        m_gui_scale = 1.0;
        break;
    }
    case EType::Perspective:
    {
        // scale near plane to keep w and h constant on the plane at z = m_distance
        const double scale = m_frustrum_zs.first / m_distance;
        w *= scale;
        h *= scale;
        m_gui_scale = scale;
        break;
    }
    }
    apply_projection(-w, w, -h, h, m_frustrum_zs.first, m_frustrum_zs.second);
}
References apply_projection(), calc_tight_frustrum_zs_around(), FrustrumMinNearZ, get_inv_zoom(), m_distance, m_frustrum_zs, m_gui_scale, m_type, m_viewport, Ortho, Perspective, and scale().
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), apply_projection(), and Slic3r::GUI::GLCanvas3D::render().
apply_projection() [2/2]
void Slic3r::GUI::Camera::apply_projection (double left, double right, double bottom, double top, double near_z, double far_z)
{
    assert(left != right && bottom != top && near_z != far_z);
    const double inv_dx = 1.0 / (right - left);
    const double inv_dy = 1.0 / (top - bottom);
    const double inv_dz = 1.0 / (far_z - near_z);
    switch (m_type)
    {
    default:
    case EType::Ortho:
    {
        m_projection_matrix.matrix() << 2.0 * inv_dx,          0.0,           0.0,   -(left + right) * inv_dx,
                                                 0.0, 2.0 * inv_dy,           0.0,   -(bottom + top) * inv_dy,
                                                 0.0,          0.0, -2.0 * inv_dz, -(near_z + far_z) * inv_dz,
                                                 0.0,          0.0,           0.0,                        1.0;
        break;
    }
    case EType::Perspective:
    {
        m_projection_matrix.matrix() << 2.0 * near_z * inv_dx,                   0.0,    (left + right) * inv_dx,                            0.0,
                                                          0.0, 2.0 * near_z * inv_dy,    (bottom + top) * inv_dy,                            0.0,
                                                          0.0,                   0.0, -(near_z + far_z) * inv_dz, -2.0 * near_z * far_z * inv_dz,
                                                          0.0,                   0.0,                       -1.0,                            0.0;
        break;
    }
    }
}
References m_projection_matrix, m_type, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Ortho, and Perspective.
apply_viewport()
void Slic3r::GUI::Camera::apply_viewport () const
{
    glsafe(::glViewport(m_viewport[0], m_viewport[1], m_viewport[2], m_viewport[3]));
}
References glsafe, and m_viewport.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), and Slic3r::GUI::GLCanvas3D::render().
calc_tight_frustrum_zs_around()
std::pair< double, double > Slic3r::GUI::Camera::calc_tight_frustrum_zs_around (const BoundingBoxf3 & box) private
{
    std::pair<double, double> ret;
    auto& [near_z, far_z] = ret;
    // box in eye space
    const BoundingBoxf3 eye_box = box.transformed(m_view_matrix);
    near_z = -eye_box.max.z();
    far_z  = -eye_box.min.z();
    // apply margin
    near_z -= FrustrumZMargin;
    far_z += FrustrumZMargin;
    // ensure min size
    if (far_z - near_z < FrustrumMinZRange) {
        const double mid_z = 0.5 * (near_z + far_z);
        const double half_size = 0.5 * FrustrumMinZRange;
        near_z = mid_z - half_size;
        far_z = mid_z + half_size;
    }
    if (near_z < FrustrumMinNearZ) {
        const double delta = FrustrumMinNearZ - near_z;
        set_distance(m_distance + delta);
        near_z += delta;
        far_z += delta;
    }
// The following is commented out because it causes flickering of the 3D scene GUI
// when the bounding box of the scene gets large enough
// We need to introduce some smarter code to move the camera back and forth in such case
//    else if (near_z > 2.0 * FrustrumMinNearZ && m_distance > DefaultDistance) {
//        float delta = m_distance - DefaultDistance;
//        set_distance(DefaultDistance);
//        near_z -= delta;
//        far_z -= delta;
//    }
    return ret;
}
References FrustrumMinNearZ, FrustrumMinZRange, FrustrumZMargin, m_distance, m_view_matrix, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, set_distance(), and Slic3r::BoundingBoxf3::transformed().
Referenced by apply_projection().
calc_zoom_to_bounding_box_factor()
double Slic3r::GUI::Camera::calc_zoom_to_bounding_box_factor (const BoundingBoxf3 & box, double margin_factor = DefaultZoomToBoxMarginFactor) const private
{
    const double max_bb_size = box.max_size();
    if (max_bb_size == 0.0)
        return -1.0;
    // project the box vertices on a plane perpendicular to the camera forward axis
    // then calculates the vertices coordinate on this plane along the camera xy axes
    const Vec3d right = get_dir_right();
    const Vec3d up = get_dir_up();
    const Vec3d forward = get_dir_forward();
    const Vec3d bb_center = box.center();
    // box vertices in world space
    const std::vector<Vec3d> vertices = {
        box.min,
        { box.max(0), box.min(1), box.min(2) },
        { box.max(0), box.max(1), box.min(2) },
        { box.min(0), box.max(1), box.min(2) },
        { box.min(0), box.min(1), box.max(2) },
        { box.max(0), box.min(1), box.max(2) },
        box.max,
        { box.min(0), box.max(1), box.max(2) }
    };
    double min_x = DBL_MAX;
    double min_y = DBL_MAX;
    double max_x = -DBL_MAX;
    double max_y = -DBL_MAX;
    for (const Vec3d& v : vertices) {
        // project vertex on the plane perpendicular to camera forward axis
        const Vec3d pos = v - bb_center;
        const Vec3d proj_on_plane = pos - pos.dot(forward) * forward;
        // calculates vertex coordinate along camera xy axes
        const double x_on_plane = proj_on_plane.dot(right);
        const double y_on_plane = proj_on_plane.dot(up);
        min_x = std::min(min_x, x_on_plane);
        min_y = std::min(min_y, y_on_plane);
        max_x = std::max(max_x, x_on_plane);
        max_y = std::max(max_y, y_on_plane);
    }
    double dx = max_x - min_x;
    double dy = max_y - min_y;
    if (dx <= 0.0 || dy <= 0.0)
        return -1.0f;
    dx *= margin_factor;
    dy *= margin_factor;
    return std::min((double)m_viewport[2] / dx, (double)m_viewport[3] / dy);
}
References Slic3r::BoundingBox3Base< PointType >::center(), get_dir_forward(), get_dir_right(), get_dir_up(), m_viewport, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBox3Base< PointType >::max_size(), and Slic3r::BoundingBoxBase< PointType, APointsType >::min.
Referenced by min_zoom(), and zoom_to_box().
calc_zoom_to_volumes_factor()
double Slic3r::GUI::Camera::calc_zoom_to_volumes_factor (const GLVolumePtrs & volumes, Vec3d & center, double margin_factor = DefaultZoomToVolumesMarginFactor) const private
{
    if (volumes.empty())
        return -1.0;
    // project the volumes vertices on a plane perpendicular to the camera forward axis
    // then calculates the vertices coordinate on this plane along the camera xy axes
    const Vec3d right = get_dir_right();
    const Vec3d up = get_dir_up();
    const Vec3d forward = get_dir_forward();
    BoundingBoxf3 box;
    for (const GLVolume* volume : volumes) {
        box.merge(volume->transformed_bounding_box());
    }
    center = box.center();
    double min_x = DBL_MAX;
    double min_y = DBL_MAX;
    double max_x = -DBL_MAX;
    double max_y = -DBL_MAX;
    for (const GLVolume* volume : volumes) {
        const Transform3d& transform = volume->world_matrix();
        const TriangleMesh* hull = volume->convex_hull();
        if (hull == nullptr)
            continue;
        for (const Vec3f& vertex : hull->its.vertices) {
            const Vec3d v = transform * vertex.cast<double>();
            // project vertex on the plane perpendicular to camera forward axis
            const Vec3d pos = v - center;
            const Vec3d proj_on_plane = pos - pos.dot(forward) * forward;
            // calculates vertex coordinate along camera xy axes
            const double x_on_plane = proj_on_plane.dot(right);
            const double y_on_plane = proj_on_plane.dot(up);
            min_x = std::min(min_x, x_on_plane);
            min_y = std::min(min_y, y_on_plane);
            max_x = std::max(max_x, x_on_plane);
            max_y = std::max(max_y, y_on_plane);
        }
    }
    center += 0.5 * (max_x + min_x) * right + 0.5 * (max_y + min_y) * up;
    const double dx = margin_factor * (max_x - min_x);
    const double dy = margin_factor * (max_y - min_y);
    if (dx <= 0.0 || dy <= 0.0)
        return -1.0f;
    return std::min((double)m_viewport[2] / dx, (double)m_viewport[3] / dy);
}
References Slic3r::BoundingBox3Base< PointType >::center(), get_dir_forward(), get_dir_right(), get_dir_up(), Slic3r::TriangleMesh::its, m_viewport, Slic3r::BoundingBox3Base< PointType >::merge(), Slic3r::transform(), and indexed_triangle_set::vertices.
Referenced by zoom_to_volumes().
enable_update_config_on_type_change()
void Slic3r::GUI::Camera::enable_update_config_on_type_change (bool enable) inline
{ m_update_config_on_type_change_enabled = enable; }
References m_update_config_on_type_change_enabled.
get_dir_forward()
Vec3d Slic3r::GUI::Camera::get_dir_forward () const inline
{ return -m_view_matrix.matrix().block(0, 0, 3, 3).row(2); }
References m_view_matrix, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix().
Referenced by priv::apply_camera_dir(), calc_zoom_to_bounding_box_factor(), calc_zoom_to_volumes_factor(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::GUI::SceneRaycaster::hit(), is_looking_downward(), Slic3r::GUI::GLGizmoCut3D::is_looking_forward(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::CameraUtils::ray_from_ortho_screen_pos(), Slic3r::GUI::GLGizmoCut3D::PartSelection::render(), set_distance(), and update_zenit().
get_dir_right()
Vec3d Slic3r::GUI::Camera::get_dir_right () const inline
{ return m_view_matrix.matrix().block(0, 0, 3, 3).row(0); }
References m_view_matrix, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix().
Referenced by Slic3r::GUI::Mouse3DController::State::apply(), calc_zoom_to_bounding_box_factor(), calc_zoom_to_volumes_factor(), Slic3r::GUI::GLCanvas3D::on_mouse(), recover_from_free_camera(), and rotate_on_sphere().
get_dir_up()
Vec3d Slic3r::GUI::Camera::get_dir_up () const inline
{ return m_view_matrix.matrix().block(0, 0, 3, 3).row(1); }
References m_view_matrix, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix().
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::Mouse3DController::State::apply(), calc_zoom_to_bounding_box_factor(), calc_zoom_to_volumes_factor(), and Slic3r::GUI::GLCanvas3D::on_mouse().
get_distance()
double Slic3r::GUI::Camera::get_distance () const inline
{ return (get_position() - m_target).norm(); }
References get_position(), and m_target.
get_far_z()
double Slic3r::GUI::Camera::get_far_z () const inline
{ return m_frustrum_zs.second; }
References m_frustrum_zs.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass().
get_fov()
double Slic3r::GUI::Camera::get_fov () const
{
    switch (m_type)
    {
    case EType::Perspective:
        return 2.0 * Geometry::rad2deg(std::atan(1.0 / m_projection_matrix.matrix()(1, 1)));
    default:
    case EType::Ortho:
        return 0.0;
    };
}
References m_projection_matrix, m_type, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Ortho, Perspective, and Slic3r::Geometry::rad2deg().
get_gui_scale()
double Slic3r::GUI::Camera::get_gui_scale () const inline
{ return m_gui_scale; }
References m_gui_scale.
get_inv_zoom()
double Slic3r::GUI::Camera::get_inv_zoom () const inline
{ assert(m_zoom != 0.0); return 1.0 / m_zoom; }
References m_zoom.
Referenced by apply_projection(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GCodeViewer::COG::render(), Slic3r::GUI::CoordAxes::render(), and Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
get_near_bottom()
double Slic3r::GUI::Camera::get_near_bottom () const
{
    switch (m_type)
    {
    case EType::Perspective:
        return m_frustrum_zs.first * (m_projection_matrix.matrix()(1, 2) - 1.0) / m_projection_matrix.matrix()(1, 1);
    default:
    case EType::Ortho:
        return -1.0 / m_projection_matrix.matrix()(1, 1) - 0.5 * m_projection_matrix.matrix()(1, 1) * m_projection_matrix.matrix()(1, 3);
    }
}
References m_frustrum_zs, m_projection_matrix, m_type, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Ortho, and Perspective.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass().
get_near_height()
double Slic3r::GUI::Camera::get_near_height () const
{
    switch (m_type)
    {
    case EType::Perspective:
        return 2.0 * m_frustrum_zs.first / m_projection_matrix.matrix()(1, 1);
    default:
    case EType::Ortho:
        return 2.0 / m_projection_matrix.matrix()(1, 1);
    }
}
References m_frustrum_zs, m_projection_matrix, m_type, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Ortho, and Perspective.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass().
get_near_left()
double Slic3r::GUI::Camera::get_near_left () const
{
    switch (m_type)
    {
    case EType::Perspective:
        return m_frustrum_zs.first * (m_projection_matrix.matrix()(0, 2) - 1.0) / m_projection_matrix.matrix()(0, 0);
    default:
    case EType::Ortho:
        return -1.0 / m_projection_matrix.matrix()(0, 0) - 0.5 * m_projection_matrix.matrix()(0, 0) * m_projection_matrix.matrix()(0, 3);
    }
}
References m_frustrum_zs, m_projection_matrix, m_type, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Ortho, and Perspective.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass().
get_near_right()
double Slic3r::GUI::Camera::get_near_right () const
{
    switch (m_type)
    {
    case EType::Perspective:
        return m_frustrum_zs.first * (m_projection_matrix.matrix()(0, 2) + 1.0) / m_projection_matrix.matrix()(0, 0);
    default:
    case EType::Ortho:
        return 1.0 / m_projection_matrix.matrix()(0, 0) - 0.5 * m_projection_matrix.matrix()(0, 0) * m_projection_matrix.matrix()(0, 3);
    }
}
References m_frustrum_zs, m_projection_matrix, m_type, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Ortho, and Perspective.
get_near_top()
double Slic3r::GUI::Camera::get_near_top () const
{
    switch (m_type)
    {
    case EType::Perspective:
        return m_frustrum_zs.first * (m_projection_matrix.matrix()(1, 2) + 1.0) / m_projection_matrix.matrix()(1, 1);
    default:
    case EType::Ortho:
        return 1.0 / m_projection_matrix.matrix()(1, 1) - 0.5 * m_projection_matrix.matrix()(1, 1) * m_projection_matrix.matrix()(1, 3);
    }
}
References m_frustrum_zs, m_projection_matrix, m_type, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Ortho, and Perspective.
get_near_width()
double Slic3r::GUI::Camera::get_near_width () const
{
    switch (m_type)
    {
    case EType::Perspective:
        return 2.0 * m_frustrum_zs.first / m_projection_matrix.matrix()(0, 0);
    default:
    case EType::Ortho:
        return 2.0 / m_projection_matrix.matrix()(0, 0);
    }
}
References m_frustrum_zs, m_projection_matrix, m_type, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Ortho, and Perspective.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass().
get_near_z()
double Slic3r::GUI::Camera::get_near_z () const inline
{ return m_frustrum_zs.first; }
References m_frustrum_zs.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass().
get_position()
Vec3d Slic3r::GUI::Camera::get_position () const inline
{ return m_view_matrix.matrix().inverse().block(0, 3, 3, 1); }
References m_view_matrix, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix().
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), get_distance(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::SceneRaycaster::hit(), Slic3r::GUI::CameraUtils::ray_from_persp_screen_pos(), recover_from_free_camera(), Slic3r::GUI::GLGizmoCut3D::PartSelection::toggle_selection(), and Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache().
get_projection_matrix()
const Transform3d & Slic3r::GUI::Camera::get_projection_matrix () const inline
{ return m_projection_matrix; }
References m_projection_matrix.
Referenced by Slic3r::GUI::GLCanvas3D::_mouse_to_3d(), Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::_render_volumes_for_picking(), Slic3r::GUI::Selection::get_screen_space_bounding_box(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::CameraUtils::project(), Slic3r::GUI::CameraUtils::ray_from_ortho_screen_pos(), Slic3r::GUI::CameraUtils::ray_from_persp_screen_pos(), Slic3r::GLVolume::SinkingContours::render(), Slic3r::GLVolume::NonManifoldEdges::render(), Slic3r::GUI::GCodeViewer::COG::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::render(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::CoordAxes::render(), Slic3r::GUI::GLGizmoCut3D::PartSelection::render(), Slic3r::GUI::GLGizmoBase::Grabber::render(), Slic3r::GUI::TriangleSelectorMmGui::render(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::MeshClipper::render_contour(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere(), Slic3r::GUI::MeshClipper::render_cut(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::TriangleSelectorGUI::render_paint_contour(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::GCodeViewer::render_shells(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::GUI::Selection::render_sidebar_position_hints(), Slic3r::GUI::Selection::render_sidebar_rotation_hints(), Slic3r::GUI::Selection::render_sidebar_scale_hints(), Slic3r::GUI::GCodeViewer::render_toolpaths(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_volumes().
get_scene_box()
const BoundingBoxf3 & Slic3r::GUI::Camera::get_scene_box () const inline
{ return m_scene_box; }
References m_scene_box.
get_target()
const Vec3d & Slic3r::GUI::Camera::get_target () const inline
{ return m_target; }
References m_target.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::Mouse3DController::State::apply(), and Slic3r::GUI::GLCanvas3D::on_mouse().
get_type()
EType Slic3r::GUI::Camera::get_type () const inline
{ return m_type; }
References m_type.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::CameraUtils::ray_from_ortho_screen_pos(), Slic3r::GUI::CameraUtils::ray_from_persp_screen_pos(), Slic3r::GUI::CameraUtils::ray_from_screen_pos(), and Slic3r::GUI::GLCanvas3D::Labels::render().
get_type_as_string()
std::string Slic3r::GUI::Camera::get_type_as_string () const
{
    switch (m_type)
    {
    case EType::Unknown:     return "unknown";
    case EType::Perspective: return "perspective";
    default:
    case EType::Ortho:       return "orthographic";
    };
}
References m_type, Ortho, Perspective, and Unknown.
get_view_matrix()
const Transform3d & Slic3r::GUI::Camera::get_view_matrix () const inline
{ return m_view_matrix; }
References m_view_matrix.
Referenced by Slic3r::GUI::GLCanvas3D::_mouse_to_3d(), Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::_render_volumes_for_picking(), Slic3r::GUI::Selection::get_screen_space_bounding_box(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::CameraUtils::project(), Slic3r::GUI::CameraUtils::ray_from_ortho_screen_pos(), Slic3r::GUI::CameraUtils::ray_from_persp_screen_pos(), Slic3r::GLVolume::SinkingContours::render(), Slic3r::GLVolume::NonManifoldEdges::render(), Slic3r::GUI::GCodeViewer::COG::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::render(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::CoordAxes::render(), Slic3r::GUI::GLGizmoCut3D::PartSelection::render(), Slic3r::GUI::GLGizmoBase::Grabber::render(), Slic3r::GUI::TriangleSelectorMmGui::render(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::MeshClipper::render_contour(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere(), Slic3r::GUI::MeshClipper::render_cut(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::TriangleSelectorGUI::render_paint_contour(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::GCodeViewer::render_shells(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::GUI::Selection::render_sidebar_position_hints(), Slic3r::GUI::Selection::render_sidebar_rotation_hints(), Slic3r::GUI::Selection::render_sidebar_scale_hints(), Slic3r::GUI::GCodeViewer::render_toolpaths(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_volumes().
get_viewport()
const std::array< int, 4 > & Slic3r::GUI::Camera::get_viewport () const inline
{ return m_viewport; }
References m_viewport.
Referenced by Slic3r::GUI::GLCanvas3D::_mouse_to_3d(), Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::Selection::get_screen_space_bounding_box(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::CameraUtils::project(), Slic3r::GUI::CameraUtils::ray_from_ortho_screen_pos(), Slic3r::GUI::CameraUtils::ray_from_persp_screen_pos(), Slic3r::GLVolume::NonManifoldEdges::render(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::render(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GCodeViewer::render_toolpaths(), and Slic3r::GUI::CameraUtils::screen_point().
get_z_range()
const std::pair< double, double > & Slic3r::GUI::Camera::get_z_range () const inline
{ return m_frustrum_zs; }
References m_frustrum_zs.
get_zoom()
double Slic3r::GUI::Camera::get_zoom () const inline
{ return m_zoom; }
References m_zoom.
Referenced by Slic3r::GUI::Mouse3DController::State::apply(), Slic3r::GUI::GCodeViewer::render_toolpaths(), and Slic3r::GUI::GLCanvas3D::update_ui_from_settings().
is_looking_downward()
bool Slic3r::GUI::Camera::is_looking_downward () const inline
{ return get_dir_forward().dot(Vec3d::UnitZ()) < 0.0; }
References get_dir_forward().
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), Slic3r::GUI::SceneRaycaster::hit(), and Slic3r::GUI::GLCanvas3D::render().
look_at()
void Slic3r::GUI::Camera::look_at (const Vec3d & position, const Vec3d & target, const Vec3d & up)
{
    const Vec3d unit_z = (position - target).normalized();
    const Vec3d unit_x = up.cross(unit_z).normalized();
    const Vec3d unit_y = unit_z.cross(unit_x).normalized();
    m_target = target;
    m_distance = (position - target).norm();
    const Vec3d new_position = m_target + m_distance * unit_z;
    m_view_matrix(0, 0) = unit_x.x();
    m_view_matrix(0, 1) = unit_x.y();
    m_view_matrix(0, 2) = unit_x.z();
    m_view_matrix(0, 3) = -unit_x.dot(new_position);
    m_view_matrix(1, 0) = unit_y.x();
    m_view_matrix(1, 1) = unit_y.y();
    m_view_matrix(1, 2) = unit_y.z();
    m_view_matrix(1, 3) = -unit_y.dot(new_position);
    m_view_matrix(2, 0) = unit_z.x();
    m_view_matrix(2, 1) = unit_z.y();
    m_view_matrix(2, 2) = unit_z.z();
    m_view_matrix(2, 3) = -unit_z.dot(new_position);
    m_view_matrix(3, 0) = 0.0;
    m_view_matrix(3, 1) = 0.0;
    m_view_matrix(3, 2) = 0.0;
    m_view_matrix(3, 3) = 1.0;
    // Initialize the rotation quaternion from the rotation submatrix of of m_view_matrix.
    m_view_rotation = Eigen::Quaterniond(m_view_matrix.matrix().template block<3, 3>(0, 0));
    m_view_rotation.normalize();
    update_zenit();
}
References m_distance, m_target, m_view_matrix, m_view_rotation, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Eigen::QuaternionBase< Derived >::normalize(), and update_zenit().
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), recover_from_free_camera(), and select_view().
max_zoom()
double Slic3r::GUI::Camera::max_zoom () const inline
{ return 250.0; }
Referenced by set_zoom().
min_zoom()
double Slic3r::GUI::Camera::min_zoom () const inline
{ return 0.7 * calc_zoom_to_bounding_box_factor(m_scene_box); }
References calc_zoom_to_bounding_box_factor(), and m_scene_box.
Referenced by Slic3r::GUI::Mouse3DController::State::apply(), and set_zoom().
recover_from_free_camera()
void Slic3r::GUI::Camera::recover_from_free_camera () inline
{
        if (std::abs(get_dir_right()(2)) > EPSILON)
            look_at(get_position(), m_target, Vec3d::UnitZ());
    }
References EPSILON, get_dir_right(), get_position(), look_at(), and m_target.
Referenced by Slic3r::GUI::Mouse3DController::disconnect_device(), and Slic3r::GUI::GLCanvas3D::on_mouse().
rotate_local_around_target()
void Slic3r::GUI::Camera::rotate_local_around_target (const Vec3d & rotation_rad)
{
    const double angle = rotation_rad.norm();
    if (std::abs(angle) > EPSILON) {
        const Vec3d translation = m_view_matrix.translation() + m_view_rotation * m_target;
        const Vec3d axis = m_view_rotation.conjugate() * rotation_rad.normalized();
        m_view_rotation *= Eigen::Quaterniond(Eigen::AngleAxisd(angle, axis));
        m_view_rotation.normalize();
      m_view_matrix.fromPositionOrientationScale(m_view_rotation * (-m_target) + translation, m_view_rotation, Vec3d(1., 1., 1.));
      update_zenit();
  }
}
References Slic3r::angle(), Eigen::QuaternionBase< Derived >::conjugate(), EPSILON, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::fromPositionOrientationScale(), m_target, m_view_matrix, m_view_rotation, Eigen::QuaternionBase< Derived >::normalize(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation(), and update_zenit().
Referenced by Slic3r::GUI::Mouse3DController::State::apply().
rotate_on_sphere()
void Slic3r::GUI::Camera::rotate_on_sphere (double delta_azimut_rad, double delta_zenit_rad, bool apply_limits)
{
    m_zenit += Geometry::rad2deg(delta_zenit_rad);
    if (apply_limits) {
        if (m_zenit > 90.0f) {
            delta_zenit_rad -= Geometry::deg2rad(m_zenit - 90.0f);
            m_zenit = 90.0f;
        }
        else if (m_zenit < -90.0f) {
            delta_zenit_rad -= Geometry::deg2rad(m_zenit + 90.0f);
            m_zenit = -90.0f;
        }
    }
    const Vec3d translation = m_view_matrix.translation() + m_view_rotation * m_target;
    const auto rot_z = Eigen::AngleAxisd(delta_azimut_rad, Vec3d::UnitZ());
    m_view_rotation *= rot_z * Eigen::AngleAxisd(delta_zenit_rad, rot_z.inverse() * get_dir_right());
    m_view_rotation.normalize();
    m_view_matrix.fromPositionOrientationScale(m_view_rotation * (- m_target) + translation, m_view_rotation, Vec3d(1., 1., 1.));
}
References Slic3r::Geometry::deg2rad(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::fromPositionOrientationScale(), get_dir_right(), m_target, m_view_matrix, m_view_rotation, m_zenit, Eigen::QuaternionBase< Derived >::normalize(), Slic3r::Geometry::rad2deg(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse().
select_next_type()
void Slic3r::GUI::Camera::select_next_type ()
{
    unsigned char next = (unsigned char)m_type + 1;
    if (next == (unsigned char)EType::Num_types)
        next = 1;
    set_type((EType)next);
}
References m_type, Num_types, and set_type().
select_view()
void Slic3r::GUI::Camera::select_view (const std::string & direction)
{
    if (direction == "iso")
        set_default_orientation();
    else if (direction == "left")
        look_at(m_target - m_distance * Vec3d::UnitX(), m_target, Vec3d::UnitZ());
    else if (direction == "right")
        look_at(m_target + m_distance * Vec3d::UnitX(), m_target, Vec3d::UnitZ());
    else if (direction == "top")
        look_at(m_target + m_distance * Vec3d::UnitZ(), m_target, Vec3d::UnitY());
    else if (direction == "bottom")
        look_at(m_target - m_distance * Vec3d::UnitZ(), m_target, -Vec3d::UnitY());
    else if (direction == "front")
        look_at(m_target - m_distance * Vec3d::UnitY(), m_target, Vec3d::UnitZ());
    else if (direction == "rear")
        look_at(m_target + m_distance * Vec3d::UnitY(), m_target, Vec3d::UnitZ());
}
References look_at(), m_distance, m_target, and set_default_orientation().
set_default_orientation()
void Slic3r::GUI::Camera::set_default_orientation () private
{
    m_zenit = 45.0f;
    const double theta_rad = Geometry::deg2rad(-(double)m_zenit);
    const double phi_rad = Geometry::deg2rad(45.0);
    const double sin_theta = ::sin(theta_rad);
    const Vec3d camera_pos = m_target + m_distance * Vec3d(sin_theta * ::sin(phi_rad), sin_theta * ::cos(phi_rad), ::cos(theta_rad));
    m_view_rotation = Eigen::AngleAxisd(theta_rad, Vec3d::UnitX()) * Eigen::AngleAxisd(phi_rad, Vec3d::UnitZ());
    m_view_rotation.normalize();
    m_view_matrix.fromPositionOrientationScale(m_view_rotation * (-camera_pos), m_view_rotation, Vec3d::Ones());
}
References cos(), Slic3r::Geometry::deg2rad(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::fromPositionOrientationScale(), m_distance, m_target, m_view_matrix, m_view_rotation, m_zenit, Eigen::QuaternionBase< Derived >::normalize(), and sin().
Referenced by Camera(), and select_view().
set_distance()
void Slic3r::GUI::Camera::set_distance (double distance) private
{
    if (m_distance != distance) {
        m_view_matrix.translate((distance - m_distance) * get_dir_forward());
        m_distance = distance;
    }
}
References get_dir_forward(), m_distance, m_view_matrix, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate().
Referenced by calc_tight_frustrum_zs_around().
set_scene_box()
void Slic3r::GUI::Camera::set_scene_box (const BoundingBoxf3 & box) inline
{ m_scene_box = box; }
References m_scene_box.
Referenced by Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal().
set_target()
void Slic3r::GUI::Camera::set_target (const Vec3d & target)
{
    const Vec3d new_target = validate_target(target);
    const Vec3d new_displacement = new_target - m_target;
    if (!new_displacement.isApprox(Vec3d::Zero())) {
        m_target = new_target;
        m_view_matrix.translate(-new_displacement);
    }
}
References m_target, m_view_matrix, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), and validate_target().
Referenced by Slic3r::GUI::Mouse3DController::State::apply(), Slic3r::GUI::GLCanvas3D::on_mouse(), translate_world(), zoom_to_box(), and zoom_to_volumes().
set_type() [1/2]
void Slic3r::GUI::Camera::set_type (const std::string & type) inline
{ set_type((type == "1") ? EType::Perspective : EType::Ortho); }
References Ortho, Perspective, and set_type().
Referenced by set_type().
set_type() [2/2]
void Slic3r::GUI::Camera::set_type (EType type)
{
    if (m_type != type && (type == EType::Ortho || type == EType::Perspective)) {
        m_type = type;
        if (m_update_config_on_type_change_enabled)
            wxGetApp().app_config->set("use_perspective_camera", (m_type == EType::Perspective) ? "1" : "0");
    }
}
References m_type, m_update_config_on_type_change_enabled, Ortho, and Perspective.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), and select_next_type().
set_viewport()
void Slic3r::GUI::Camera::set_viewport (int x, int y, unsigned int w, unsigned int h)
{
    m_viewport = { 0, 0, int(w), int(h) };
}
References m_viewport.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), and Slic3r::GUI::GLCanvas3D::render().
set_zoom()
void Slic3r::GUI::Camera::set_zoom (double zoom)
{
    // Don't allow to zoom too far outside the scene.
    const double zoom_min = min_zoom();
    if (zoom_min > 0.0)
        zoom = std::max(zoom, zoom_min);
    // Don't allow to zoom too close to the scene.
    m_zoom = std::min(zoom, max_zoom());
}
References m_zoom, max_zoom(), and min_zoom().
Referenced by Slic3r::GUI::GLCanvas3D::update_ui_from_settings(), and update_zoom().
translate_world()
void Slic3r::GUI::Camera::translate_world (const Vec3d & displacement) inline
{ set_target(m_target + displacement); }
References m_target, and set_target().
update_zenit()
void Slic3r::GUI::Camera::update_zenit () private
{
    m_zenit = Geometry::rad2deg(0.5 * M_PI - std::acos(std::clamp(-get_dir_forward().dot(Vec3d::UnitZ()), -1.0, 1.0)));
}
References Slic3r::dot(), get_dir_forward(), M_PI, m_zenit, and Slic3r::Geometry::rad2deg().
Referenced by look_at(), and rotate_local_around_target().
update_zoom()
void Slic3r::GUI::Camera::update_zoom (double delta_zoom) inline
{ set_zoom(m_zoom / (1.0 - std::max(std::min(delta_zoom, 4.0), -4.0) * 0.1)); }
References m_zoom, and set_zoom().
Referenced by Slic3r::GUI::Mouse3DController::State::apply().
validate_target()
Vec3d Slic3r::GUI::Camera::validate_target (const Vec3d & target) const private
{
    BoundingBoxf3 test_box = m_scene_box;
    test_box.translate(-m_scene_box.center());
    // We may let this factor be customizable
    static const double ScaleFactor = 1.5;
    test_box.scale(ScaleFactor);
    test_box.translate(m_scene_box.center());
    return { std::clamp(target(0), test_box.min(0), test_box.max(0)),
             std::clamp(target(1), test_box.min(1), test_box.max(1)),
             std::clamp(target(2), test_box.min(2), test_box.max(2)) };
}
References Slic3r::BoundingBox3Base< PointType >::center(), m_scene_box, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::BoundingBoxBase< PointType, APointsType >::scale(), and Slic3r::BoundingBox3Base< PointType >::translate().
Referenced by set_target().
zoom_to_box()
void Slic3r::GUI::Camera::zoom_to_box (const BoundingBoxf3 & box, double margin_factor = DefaultZoomToBoxMarginFactor)
{
    // Calculate the zoom factor needed to adjust the view around the given box.
    const double zoom = calc_zoom_to_bounding_box_factor(box, margin_factor);
    if (zoom > 0.0) {
        m_zoom = zoom;
        // center view around box center
        set_target(box.center());
    }
}
References calc_zoom_to_bounding_box_factor(), Slic3r::BoundingBox3Base< PointType >::center(), m_zoom, and set_target().
Referenced by Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal().
zoom_to_volumes()
void Slic3r::GUI::Camera::zoom_to_volumes (const GLVolumePtrs & volumes, double margin_factor = DefaultZoomToVolumesMarginFactor)
{
    Vec3d center;
    const double zoom = calc_zoom_to_volumes_factor(volumes, center, margin_factor);
    if (zoom > 0.0) {
        m_zoom = zoom;
        // center view around the calculated center
        set_target(center);
    }
}
References calc_zoom_to_volumes_factor(), m_zoom, and set_target().
Member Data Documentation
DefaultDistance
const double Slic3r::GUI::Camera::DefaultDistance = 1000.0 static
DefaultZoomToBoxMarginFactor
const double Slic3r::GUI::Camera::DefaultZoomToBoxMarginFactor = 1.025 static
DefaultZoomToVolumesMarginFactor
const double Slic3r::GUI::Camera::DefaultZoomToVolumesMarginFactor = 1.025 static
FrustrumMinNearZ
double Slic3r::GUI::Camera::FrustrumMinNearZ = 100.0 static
Referenced by apply_projection(), and calc_tight_frustrum_zs_around().
FrustrumMinZRange
double Slic3r::GUI::Camera::FrustrumMinZRange = 50.0 static
Referenced by calc_tight_frustrum_zs_around().
FrustrumZMargin
double Slic3r::GUI::Camera::FrustrumZMargin = 10.0 static
Referenced by calc_tight_frustrum_zs_around().
m_distance
double Slic3r::GUI::Camera::m_distance { DefaultDistance } private
Referenced by apply_projection(), calc_tight_frustrum_zs_around(), look_at(), select_view(), set_default_orientation(), and set_distance().
m_frustrum_zs
std::pair<double, double> Slic3r::GUI::Camera::m_frustrum_zs private
Referenced by apply_projection(), get_far_z(), get_near_bottom(), get_near_height(), get_near_left(), get_near_right(), get_near_top(), get_near_width(), get_near_z(), and get_z_range().
m_gui_scale
double Slic3r::GUI::Camera::m_gui_scale { 1.0 } private
Referenced by apply_projection(), and get_gui_scale().
m_projection_matrix
Transform3d Slic3r::GUI::Camera::m_projection_matrix { Transform3d::Identity() } private
Referenced by apply_projection(), get_fov(), get_near_bottom(), get_near_height(), get_near_left(), get_near_right(), get_near_top(), get_near_width(), and get_projection_matrix().
m_scene_box
BoundingBoxf3 Slic3r::GUI::Camera::m_scene_box private
Referenced by get_scene_box(), min_zoom(), set_scene_box(), and validate_target().
m_target
Vec3d Slic3r::GUI::Camera::m_target { Vec3d::Zero() } private
Referenced by get_distance(), get_target(), look_at(), recover_from_free_camera(), rotate_local_around_target(), rotate_on_sphere(), select_view(), set_default_orientation(), set_target(), and translate_world().
m_type
EType Slic3r::GUI::Camera::m_type { EType::Perspective } private
Referenced by apply_projection(), apply_projection(), get_fov(), get_near_bottom(), get_near_height(), get_near_left(), get_near_right(), get_near_top(), get_near_width(), get_type(), get_type_as_string(), select_next_type(), and set_type().
m_update_config_on_type_change_enabled
bool Slic3r::GUI::Camera::m_update_config_on_type_change_enabled { false } private
Referenced by enable_update_config_on_type_change(), and set_type().
m_view_matrix
Transform3d Slic3r::GUI::Camera::m_view_matrix { Transform3d::Identity() } private
Referenced by calc_tight_frustrum_zs_around(), get_dir_forward(), get_dir_right(), get_dir_up(), get_position(), get_view_matrix(), look_at(), rotate_local_around_target(), rotate_on_sphere(), set_default_orientation(), set_distance(), and set_target().
m_view_rotation
Eigen::Quaterniond Slic3r::GUI::Camera::m_view_rotation { 1.0, 0.0, 0.0, 0.0 } private
Referenced by look_at(), rotate_local_around_target(), rotate_on_sphere(), and set_default_orientation().
m_viewport
std::array<int, 4> Slic3r::GUI::Camera::m_viewport private
Referenced by apply_projection(), apply_viewport(), calc_zoom_to_bounding_box_factor(), calc_zoom_to_volumes_factor(), get_viewport(), and set_viewport().
m_zenit
float Slic3r::GUI::Camera::m_zenit { 45.0f } private
Referenced by rotate_on_sphere(), set_default_orientation(), and update_zenit().
m_zoom
double Slic3r::GUI::Camera::m_zoom { 1.0 } private
Referenced by get_inv_zoom(), get_zoom(), set_zoom(), update_zoom(), zoom_to_box(), and zoom_to_volumes().
MaxFovDeg
double Slic3r::GUI::Camera::MaxFovDeg = 60.0 static
requires_zoom_to_bed
bool Slic3r::GUI::Camera::requires_zoom_to_bed { false }
Referenced by Slic3r::GUI::GLCanvas3D::render().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/Camera.hpp
src/slic3r/GUI/Camera.cpp