Prusa Slicer: WipingDialog Class Reference
WipingDialog Class Reference
#include <src/slic3r/GUI/WipeTowerDialog.hpp>
Public Member Functions
WipingDialog (wxWindow *parent, const std::vector< float > &matrix, const std::vector< float > &extruders, const std::vector< std::string > &extruder_colours)
std::vector< float > get_matrix () const
std::vector< float > get_extruders () const
Private Attributes
WipingPanel * m_panel_wiping = nullptr
std::vector< float > m_output_matrix
std::vector< float > m_output_extruders
Detailed Description
Constructor & Destructor Documentation
WipingDialog()
WipingDialog::WipingDialog (wxWindow * parent, const std::vector< float > & matrix, const std::vector< float > & extruders, const std::vector< std::string > & extruder_colours)
: wxDialog(parent, wxID_ANY, _(L("Wipe tower - Purging volume adjustment")), wxDefaultPosition, wxDefaultSize, wxDEFAULT_DIALOG_STYLE/* | wxRESIZE_BORDER*/)
{
    update_ui(this);
    auto widget_button = new wxButton(this,wxID_ANY,"-",wxPoint(0,0),wxDefaultSize);
    update_ui(widget_button);
    m_panel_wiping  = new WipingPanel(this,matrix,extruders, extruder_colours, widget_button);
    auto main_sizer = new wxBoxSizer(wxVERTICAL);
  // set min sizer width according to extruders count
  const auto sizer_width = (int)((sqrt(matrix.size()) + 2.8)*ITEM_WIDTH());
  main_sizer->SetMinSize(wxSize(sizer_width, -1));
    main_sizer->Add(m_panel_wiping, 0, wxEXPAND | wxALL, 5);
  main_sizer->Add(widget_button, 0, wxALIGN_CENTER_HORIZONTAL | wxCENTER | wxBOTTOM, 5);
    main_sizer->Add(CreateButtonSizer(wxOK | wxCANCEL), 0, wxALIGN_CENTER_HORIZONTAL | wxBOTTOM, 10);
    SetSizer(main_sizer);
    main_sizer->SetSizeHints(this);
    update_ui(static_cast<wxButton*>(this->FindWindowById(wxID_OK, this)));
    update_ui(static_cast<wxButton*>(this->FindWindowById(wxID_CANCEL, this)));
    this->Bind(wxEVT_CLOSE_WINDOW, [this](wxCloseEvent& e) { EndModal(wxCANCEL); });
    this->Bind(wxEVT_BUTTON,[this](wxCommandEvent&) {                 // if OK button is clicked..
        m_output_matrix    = m_panel_wiping->read_matrix_values();    // ..query wiping panel and save returned values
        m_output_extruders = m_panel_wiping->read_extruders_values(); // so they can be recovered later by calling get_...()
        EndModal(wxID_OK);
        },wxID_OK);
    this->Show();
}
References ITEM_WIDTH(), m_output_extruders, m_output_matrix, m_panel_wiping, WipingPanel::read_extruders_values(), WipingPanel::read_matrix_values(), sqrt(), update_ui(), and wxEVT_BUTTON.
Member Function Documentation
get_extruders()
std::vector< float > WipingDialog::get_extruders () const inline
{ return m_output_extruders; }
References m_output_extruders.
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams().
get_matrix()
std::vector< float > WipingDialog::get_matrix () const inline
{ return m_output_matrix; }
References m_output_matrix.
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams().
Member Data Documentation
m_output_extruders
std::vector<float> WipingDialog::m_output_extruders private
Referenced by WipingDialog(), and get_extruders().
m_output_matrix
std::vector<float> WipingDialog::m_output_matrix private
Referenced by WipingDialog(), and get_matrix().
m_panel_wiping
WipingPanel* WipingDialog::m_panel_wiping = nullptr private
Referenced by WipingDialog().
The documentation for this class was generated from the following files:
src/slic3r/GUI/WipeTowerDialog.hpp
src/slic3r/GUI/WipeTowerDialog.cpp