Prusa Slicer: Eigen::SparseSolverBase< Derived > Class Template Reference
Eigen::SparseSolverBase< Derived > Class Template Reference
A base class for sparse solvers.
#include <src/eigen/Eigen/src/SparseCore/SparseSolverBase.h>
Inherits Eigen::internal::noncopyable.
Inherited by Eigen::CholmodBase< _MatrixType, Lower, CholmodDecomposition< _MatrixType, Lower > >, Eigen::CholmodBase< _MatrixType, Lower, CholmodSimplicialLDLT< _MatrixType, Lower > >, Eigen::CholmodBase< _MatrixType, Lower, CholmodSimplicialLLT< _MatrixType, Lower > >, Eigen::CholmodBase< _MatrixType, Lower, CholmodSupernodalLLT< _MatrixType, Lower > >, Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >, Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >, Eigen::IterativeSolverBase< LeastSquaresConjugateGradient< _MatrixType, _Preconditioner > >, Eigen::PardisoImpl< PardisoLDLT< MatrixType, Options > >, Eigen::PardisoImpl< PardisoLLT< MatrixType, _UpLo > >, Eigen::PardisoImpl< PardisoLU< MatrixType > >, Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >, Eigen::PastixBase< PastixLLT< _MatrixType, _UpLo > >, Eigen::PastixBase< PastixLU< _MatrixType > >, Eigen::SimplicialCholeskyBase< SimplicialCholesky< _MatrixType, _UpLo, _Ordering > >, Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >, Eigen::SimplicialCholeskyBase< SimplicialLLT< _MatrixType, _UpLo, _Ordering > >, Eigen::SimplicialCholeskyBase< SimplicialLLT< Eigen::SparseMatrix< double >, _UpLo, _Ordering > >, Eigen::SimplicialCholeskyBase< SimplicialLDLT< Eigen::SparseMatrix< double >, _UpLo, _Ordering > >, Eigen::SimplicialCholeskyBase< SimplicialCholesky< Eigen::SparseMatrix< double >, _UpLo, _Ordering > >, Eigen::SimplicialCholeskyBase< SimplicialLDLT< Eigen::SparseMatrix< typename DerivedV::Scalar >, _UpLo, _Ordering > >, Eigen::SimplicialCholeskyBase< SimplicialLLT< Eigen::SparseMatrix< T >, _UpLo, _Ordering > >, Eigen::SimplicialCholeskyBase< SimplicialLDLT< Eigen::SparseMatrix< T >, _UpLo, _Ordering > >, Eigen::SparseLU< Eigen::SparseMatrix< double, Eigen::ColMajor >, Eigen::COLAMDOrdering< int > >, Eigen::SparseLU< Eigen::SparseMatrix< T, Eigen::ColMajor >, Eigen::COLAMDOrdering< int > >, Eigen::SparseQR< Eigen::SparseMatrix< double >, Eigen::COLAMDOrdering< int > >, Eigen::SparseQR< Eigen::SparseMatrix< T >, Eigen::COLAMDOrdering< int > >, Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >, Eigen::CholmodBase< _MatrixType, _UpLo, Derived >, Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >, Eigen::IncompleteLUT< _Scalar, _StorageIndex >, Eigen::IterativeSolverBase< Derived >, Eigen::PardisoImpl< Derived >, Eigen::PastixBase< Derived >, Eigen::SimplicialCholeskyBase< Derived >, and Eigen::SuperLUBase< _MatrixType, Derived >.
Public Member Functions
SparseSolverBase ()
~SparseSolverBase ()
Derived & derived ()
const Derived & derived () const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
template<typename Rhs , typename Dest >
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Attributes
bool m_isInitialized
Detailed Description
template<typename Derived>
class Eigen::SparseSolverBase< Derived >
A base class for sparse solvers.
Template Parameters
Derived the actual type of the solver.
Constructor & Destructor Documentation
SparseSolverBase()
template<typename Derived > Eigen::SparseSolverBase< Derived >::SparseSolverBase () inline
Default constructor
      : m_isInitialized(false)
    {}
~SparseSolverBase()
template<typename Derived > Eigen::SparseSolverBase< Derived >::~SparseSolverBase () inline
    {}
Member Function Documentation
_solve_impl()
template<typename Derived > template<typename Rhs , typename Dest > void Eigen::SparseSolverBase< Derived >::_solve_impl (const SparseMatrixBase< Rhs > & b, SparseMatrixBase< Dest > & dest) const inline
    {
      internal::solve_sparse_through_dense_panels(derived(), b.derived(), dest.derived());
    }
References Eigen::SparseSolverBase< Derived >::derived(), Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::internal::solve_sparse_through_dense_panels().
derived() [1/2]
template<typename Derived > Derived & Eigen::SparseSolverBase< Derived >::derived () inline
{ return *static_cast<Derived*>(this); }
Referenced by Eigen::SparseSolverBase< Derived >::_solve_impl(), and Eigen::SparseSolverBase< Derived >::solve().
derived() [2/2]
template<typename Derived > const Derived & Eigen::SparseSolverBase< Derived >::derived () const inline
{ return *static_cast<const Derived*>(this); }
solve() [1/2]
template<typename Derived > template<typename Rhs > const Solve< Derived, Rhs > Eigen::SparseSolverBase< Derived >::solve (const MatrixBase< Rhs > & b) const inline
Returns
an expression of the solution x of using the current decomposition of A.
See also
compute()
    {
      eigen_assert(m_isInitialized && "Solver is not initialized.");
      eigen_assert(derived().rows()==b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
      return Solve<Derived, Rhs>(derived(), b.derived());
    }
References Eigen::SparseSolverBase< Derived >::derived(), eigen_assert, and Eigen::SparseSolverBase< Derived >::m_isInitialized.
Referenced by igl::embree::bone_heat(), igl::Frame_field_deformer::compute_optimal_positions(), igl::eigs(), igl::copyleft::comiso::FrameInterpolator::interpolateSymmetric(), igl::slim::solve_weighted_arap(), and igl::copyleft::comiso::NRosyField::solveNoRoundings().
solve() [2/2]
template<typename Derived > template<typename Rhs > const Solve< Derived, Rhs > Eigen::SparseSolverBase< Derived >::solve (const SparseMatrixBase< Rhs > & b) const inline
Returns
an expression of the solution x of using the current decomposition of A.
See also
compute()
    {
      eigen_assert(m_isInitialized && "Solver is not initialized.");
      eigen_assert(derived().rows()==b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
      return Solve<Derived, Rhs>(derived(), b.derived());
    }
Member Data Documentation
m_isInitialized
template<typename Derived > bool Eigen::SparseSolverBase< Derived >::m_isInitialized mutable protected
Referenced by Eigen::SparseSolverBase< Derived >::solve().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseSolverBase.h