Prusa Slicer: Slic3r::TriangleSelector::ClippingPlane Struct Reference
Slic3r::TriangleSelector::ClippingPlane Struct Reference
#include <src/libslic3r/TriangleSelector.hpp>
Public Member Functions
ClippingPlane ()
ClippingPlane (const std::array< float, 4 > &clp)
bool is_active () const
bool is_mesh_point_clipped (const Vec3f &point) const
Public Attributes
Vec3f normal
float offset
Detailed Description
Constructor & Destructor Documentation
ClippingPlane() [1/2]
Slic3r::TriangleSelector::ClippingPlane::ClippingPlane () inline
: normal{0.f, 0.f, 1.f}, offset{FLT_MAX} {};
ClippingPlane() [2/2]
Slic3r::TriangleSelector::ClippingPlane::ClippingPlane (const std::array< float, 4 > & clp) inline explicit
: normal{clp[0], clp[1], clp[2]}, offset{clp[3]} {}
Member Function Documentation
is_active()
bool Slic3r::TriangleSelector::ClippingPlane::is_active () const inline
{ return offset != FLT_MAX; }
References offset.
Referenced by Slic3r::TriangleSelector::bucket_fill_select_triangles(), Slic3r::TriangleSelector::is_facet_clipped(), Slic3r::is_mesh_point_not_clipped(), and Slic3r::TriangleSelector::seed_fill_select_triangles().
is_mesh_point_clipped()
bool Slic3r::TriangleSelector::ClippingPlane::is_mesh_point_clipped (const Vec3f & point) const inline
{ return normal.dot(point) - offset > 0.f; }
References normal, and offset.
Referenced by Slic3r::TriangleSelector::is_facet_clipped(), and Slic3r::is_mesh_point_not_clipped().
Member Data Documentation
normal
Vec3f Slic3r::TriangleSelector::ClippingPlane::normal
Referenced by is_mesh_point_clipped().
offset
float Slic3r::TriangleSelector::ClippingPlane::offset
Referenced by is_active(), and is_mesh_point_clipped().
The documentation for this struct was generated from the following file:
src/libslic3r/TriangleSelector.hpp