Prusa Slicer: Eigen::NestByValue< ExpressionType > Class Template Reference
Eigen::NestByValue< ExpressionType > Class Template Reference
Expression which must be nested by value.
#include <src/eigen/Eigen/src/Core/NestByValue.h>
Public Types
typedef internal::dense_xpr_base< NestByValue >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC NestByValue (const ExpressionType &matrix)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Index innerStride () const
EIGEN_DEVICE_FUNC const CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC const CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index index)
template<int LoadMode>
const PacketScalar packet (Index row, Index col) const
template<int LoadMode>
void writePacket (Index row, Index col, const PacketScalar &x)
template<int LoadMode>
const PacketScalar packet (Index index) const
template<int LoadMode>
void writePacket (Index index, const PacketScalar &x)
EIGEN_DEVICE_FUNC operator const ExpressionType & () const
Protected Attributes
const ExpressionType m_expression
Detailed Description
template<typename ExpressionType>
class Eigen::NestByValue< ExpressionType >
Expression which must be nested by value.
Template Parameters
ExpressionType the type of the object of which we are requiring nesting-by-value
This class is the return type of MatrixBase::nestByValue() and most of the time this is the only way it is used.
See also
MatrixBase::nestByValue()
Member Typedef Documentation
Base
template<typename ExpressionType > typedef internal::dense_xpr_base<NestByValue>::type Eigen::NestByValue< ExpressionType >::Base
Constructor & Destructor Documentation
NestByValue()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Eigen::NestByValue< ExpressionType >::NestByValue (const ExpressionType & matrix) inline explicit
: m_expression(matrix) {}
Member Function Documentation
coeff() [1/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC const CoeffReturnType Eigen::NestByValue< ExpressionType >::coeff (Index index) const inline
    {
      return m_expression.coeff(index);
    }
References Eigen::NestByValue< ExpressionType >::m_expression.
coeff() [2/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC const CoeffReturnType Eigen::NestByValue< ExpressionType >::coeff (Index row, Index col) const inline
    {
      return m_expression.coeff(row, col);
    }
References col(), Eigen::NestByValue< ExpressionType >::m_expression, and row().
coeffRef() [1/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC Scalar & Eigen::NestByValue< ExpressionType >::coeffRef (Index index) inline
    {
      return m_expression.const_cast_derived().coeffRef(index);
    }
References Eigen::NestByValue< ExpressionType >::m_expression.
coeffRef() [2/2]
template<typename ExpressionType > EIGEN_DEVICE_FUNC Scalar & Eigen::NestByValue< ExpressionType >::coeffRef (Index row, Index col) inline
    {
      return m_expression.const_cast_derived().coeffRef(row, col);
    }
References col(), Eigen::NestByValue< ExpressionType >::m_expression, and row().
cols()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::NestByValue< ExpressionType >::cols () const inline
{ return m_expression.cols(); }
References Eigen::NestByValue< ExpressionType >::m_expression.
innerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::NestByValue< ExpressionType >::innerStride () const inline
{ return m_expression.innerStride(); }
References Eigen::NestByValue< ExpressionType >::m_expression.
operator const ExpressionType &()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Eigen::NestByValue< ExpressionType >::operator const ExpressionType & () const inline
{ return m_expression; }
References Eigen::NestByValue< ExpressionType >::m_expression.
outerStride()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::NestByValue< ExpressionType >::outerStride () const inline
{ return m_expression.outerStride(); }
References Eigen::NestByValue< ExpressionType >::m_expression.
packet() [1/2]
template<typename ExpressionType > template<int LoadMode> const PacketScalar Eigen::NestByValue< ExpressionType >::packet (Index index) const inline
    {
      return m_expression.template packet<LoadMode>(index);
    }
References Eigen::NestByValue< ExpressionType >::m_expression.
packet() [2/2]
template<typename ExpressionType > template<int LoadMode> const PacketScalar Eigen::NestByValue< ExpressionType >::packet (Index row, Index col) const inline
    {
      return m_expression.template packet<LoadMode>(row, col);
    }
References col(), Eigen::NestByValue< ExpressionType >::m_expression, and row().
rows()
template<typename ExpressionType > EIGEN_DEVICE_FUNC Index Eigen::NestByValue< ExpressionType >::rows () const inline
{ return m_expression.rows(); }
References Eigen::NestByValue< ExpressionType >::m_expression.
writePacket() [1/2]
template<typename ExpressionType > template<int LoadMode> void Eigen::NestByValue< ExpressionType >::writePacket (Index index, const PacketScalar & x) inline
    {
      m_expression.const_cast_derived().template writePacket<LoadMode>(index, x);
    }
References Eigen::NestByValue< ExpressionType >::m_expression.
writePacket() [2/2]
template<typename ExpressionType > template<int LoadMode> void Eigen::NestByValue< ExpressionType >::writePacket (Index row, Index col, const PacketScalar & x) inline
    {
      m_expression.const_cast_derived().template writePacket<LoadMode>(row, col, x);
    }
References col(), Eigen::NestByValue< ExpressionType >::m_expression, and row().
Member Data Documentation
m_expression
template<typename ExpressionType > const ExpressionType Eigen::NestByValue< ExpressionType >::m_expression protected
Referenced by Eigen::NestByValue< ExpressionType >::coeff(), Eigen::NestByValue< ExpressionType >::coeff(), Eigen::NestByValue< ExpressionType >::coeffRef(), Eigen::NestByValue< ExpressionType >::coeffRef(), Eigen::NestByValue< ExpressionType >::cols(), Eigen::NestByValue< ExpressionType >::innerStride(), Eigen::NestByValue< ExpressionType >::operator const ExpressionType &(), Eigen::NestByValue< ExpressionType >::outerStride(), Eigen::NestByValue< ExpressionType >::packet(), Eigen::NestByValue< ExpressionType >::packet(), Eigen::NestByValue< ExpressionType >::rows(), Eigen::NestByValue< ExpressionType >::writePacket(), and Eigen::NestByValue< ExpressionType >::writePacket().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/NestByValue.h