Prusa Slicer: agg::trans_affine_translation Class Reference
agg::trans_affine_translation Class Reference
#include <src/agg/agg_trans_affine.h>
Public Member Functions
trans_affine_translation (double x, double y)
const trans_affine & parl_to_parl (const double *src, const double *dst)
const trans_affine & rect_to_parl (double x1, double y1, double x2, double y2, const double *parl)
const trans_affine & parl_to_rect (const double *parl, double x1, double y1, double x2, double y2)
const trans_affine & reset ()
const trans_affine & translate (double x, double y)
const trans_affine & rotate (double a)
const trans_affine & scale (double s)
const trans_affine & scale (double x, double y)
double scale () const
const trans_affine & multiply (const trans_affine &m)
const trans_affine & premultiply (const trans_affine &m)
const trans_affine & multiply_inv (const trans_affine &m)
const trans_affine & premultiply_inv (const trans_affine &m)
const trans_affine & invert ()
const trans_affine & flip_x ()
const trans_affine & flip_y ()
void store_to (double *m) const
const trans_affine & load_from (const double *m)
const trans_affine & operator*= (const trans_affine &m)
const trans_affine & operator/= (const trans_affine &m)
trans_affine operator* (const trans_affine &m) const
trans_affine operator/ (const trans_affine &m) const
trans_affine operator~ () const
bool operator== (const trans_affine &m) const
bool operator!= (const trans_affine &m) const
void transform (double *x, double *y) const
void transform_2x2 (double *x, double *y) const
void inverse_transform (double *x, double *y) const
double determinant () const
double determinant_reciprocal () const
bool is_valid (double epsilon=affine_epsilon) const
bool is_identity (double epsilon=affine_epsilon) const
bool is_equal (const trans_affine &m, double epsilon=affine_epsilon) const
double rotation () const
void translation (double *dx, double *dy) const
void scaling (double *x, double *y) const
void scaling_abs (double *x, double *y) const
Public Attributes
double sx
double shy
double shx
double sy
double tx
double ty
Detailed Description
Constructor & Destructor Documentation
trans_affine_translation()
agg::trans_affine_translation::trans_affine_translation (double x, double y) inline
                                                     :
          trans_affine(1.0, 0.0, 0.0, 1.0, x, y)
        {}
Member Function Documentation
determinant()
double agg::trans_affine::determinant () const inline inherited
        {
            return sx * sy - shy * shx;
        }
References agg::trans_affine::shx, agg::trans_affine::shy, agg::trans_affine::sx, and agg::trans_affine::sy.
determinant_reciprocal()
double agg::trans_affine::determinant_reciprocal () const inline inherited
        {
            return 1.0 / (sx * sy - shy * shx);
        }
References agg::trans_affine::shx, agg::trans_affine::shy, agg::trans_affine::sx, and agg::trans_affine::sy.
Referenced by agg::trans_affine::inverse_transform().
flip_x()
const trans_affine & agg::trans_affine::flip_x () inherited
flip_y()
const trans_affine & agg::trans_affine::flip_y () inherited
inverse_transform()
void agg::trans_affine::inverse_transform (double * x, double * y) const inline inherited
    {
        double d = determinant_reciprocal();
        double a = (*x - tx) * d;
        double b = (*y - ty) * d;
        *x = a * sy - b * shx;
        *y = b * sx - a * shy;
    }
References agg::trans_affine::determinant_reciprocal(), agg::trans_affine::shx, agg::trans_affine::shy, agg::trans_affine::sx, agg::trans_affine::sy, agg::trans_affine::tx, and agg::trans_affine::ty.
invert()
const trans_affine & agg::trans_affine::invert () inherited
Referenced by agg::trans_affine::multiply_inv(), agg::trans_affine::operator~(), and agg::trans_affine::premultiply_inv().
is_equal()
bool agg::trans_affine::is_equal (const trans_affine & m, double epsilon = affine_epsilon) const inherited
Referenced by agg::trans_affine::operator!=(), and agg::trans_affine::operator==().
is_identity()
bool agg::trans_affine::is_identity (double epsilon = affine_epsilon) const inherited
is_valid()
bool agg::trans_affine::is_valid (double epsilon = affine_epsilon) const inherited
load_from()
const trans_affine & agg::trans_affine::load_from (const double * m) inline inherited
        {
            sx = *m++; shy = *m++; shx = *m++; sy = *m++; tx = *m++;  ty = *m++;
            return *this;
        }
References agg::trans_affine::shx, agg::trans_affine::shy, agg::trans_affine::sx, agg::trans_affine::sy, agg::trans_affine::tx, and agg::trans_affine::ty.
multiply()
const trans_affine & agg::trans_affine::multiply (const trans_affine & m) inherited
Referenced by agg::trans_affine_line_segment::trans_affine_line_segment(), agg::trans_affine::multiply_inv(), agg::trans_affine::operator*=(), agg::trans_affine::premultiply(), and agg::trans_affine::premultiply_inv().
multiply_inv()
const trans_affine & agg::trans_affine::multiply_inv (const trans_affine & m) inline inherited
    {
        trans_affine t = m;
        t.invert();
        return multiply(t);
    }
References agg::trans_affine::invert(), and agg::trans_affine::multiply().
Referenced by agg::trans_affine::operator/=().
operator!=()
bool agg::trans_affine::operator!= (const trans_affine & m) const inline inherited
        {
            return !is_equal(m, affine_epsilon);
        }
References agg::affine_epsilon, and agg::trans_affine::is_equal().
operator*()
trans_affine agg::trans_affine::operator* (const trans_affine & m) const inline inherited
        {
            return trans_affine(*this).multiply(m);
        }
References agg::trans_affine::trans_affine().
operator*=()
const trans_affine & agg::trans_affine::operator*= (const trans_affine & m) inline inherited
        {
            return multiply(m);
        }
References agg::trans_affine::multiply().
operator/()
trans_affine agg::trans_affine::operator/ (const trans_affine & m) const inline inherited
        {
            return trans_affine(*this).multiply_inv(m);
        }
References agg::trans_affine::trans_affine().
operator/=()
const trans_affine & agg::trans_affine::operator/= (const trans_affine & m) inline inherited
        {
            return multiply_inv(m);
        }
References agg::trans_affine::multiply_inv().
operator==()
bool agg::trans_affine::operator== (const trans_affine & m) const inline inherited
        {
            return is_equal(m, affine_epsilon);
        }
References agg::affine_epsilon, and agg::trans_affine::is_equal().
operator~()
trans_affine agg::trans_affine::operator~ () const inline inherited
        {
            trans_affine ret = *this;
            return ret.invert();
        }
References agg::trans_affine::invert().
parl_to_parl()
const trans_affine & agg::trans_affine::parl_to_parl (const double * src, const double * dst) inherited
Referenced by agg::trans_affine::trans_affine().
parl_to_rect()
const trans_affine & agg::trans_affine::parl_to_rect (const double * parl, double x1, double y1, double x2, double y2) inherited
Referenced by agg::trans_affine::trans_affine().
premultiply()
const trans_affine & agg::trans_affine::premultiply (const trans_affine & m) inline inherited
    {
        trans_affine t = m;
        return *this = t.multiply(*this);
    }
References agg::trans_affine::multiply().
premultiply_inv()
const trans_affine & agg::trans_affine::premultiply_inv (const trans_affine & m) inline inherited
    {
        trans_affine t = m;
        t.invert();
        return *this = t.multiply(*this);
    }
References agg::trans_affine::invert(), and agg::trans_affine::multiply().
rect_to_parl()
const trans_affine & agg::trans_affine::rect_to_parl (double x1, double y1, double x2, double y2, const double * parl) inherited
Referenced by agg::trans_affine::trans_affine().
reset()
const trans_affine & agg::trans_affine::reset () inherited
rotate()
const trans_affine & agg::trans_affine::rotate (double a) inline inherited
    {
        double ca = cos(a);
        double sa = sin(a);
        double t0 = sx  * ca - shy * sa;
        double t2 = shx * ca - sy * sa;
        double t4 = tx  * ca - ty * sa;
        shy = sx  * sa + shy * ca;
        sy  = shx * sa + sy * ca;
        ty  = tx  * sa + ty * ca;
        sx  = t0;
        shx = t2;
        tx  = t4;
        return *this;
    }
References cos(), agg::trans_affine::shx, agg::trans_affine::shy, sin(), agg::trans_affine::sx, agg::trans_affine::sy, agg::trans_affine::tx, and agg::trans_affine::ty.
rotation()
double agg::trans_affine::rotation () const inherited
scale() [1/3]
double agg::trans_affine::scale () const inline inherited
    {
        double x = 0.707106781 * sx  + 0.707106781 * shx;
        double y = 0.707106781 * shy + 0.707106781 * sy;
        return sqrt(x*x + y*y);
    }
References agg::trans_affine::shx, agg::trans_affine::shy, sqrt(), agg::trans_affine::sx, and agg::trans_affine::sy.
scale() [2/3]
const trans_affine & agg::trans_affine::scale (double s) inline inherited
    {
        double m = s; // Possible hint for the optimizer
        sx  *= m;
        shx *= m;
        tx  *= m;
        shy *= m;
        sy  *= m;
        ty  *= m;
        return *this;
    }
References agg::trans_affine::shx, agg::trans_affine::shy, agg::trans_affine::sx, agg::trans_affine::sy, agg::trans_affine::tx, and agg::trans_affine::ty.
scale() [3/3]
const trans_affine & agg::trans_affine::scale (double x, double y) inline inherited
    {
        double mm0 = x; // Possible hint for the optimizer
        double mm3 = y;
        sx  *= mm0;
        shx *= mm0;
        tx  *= mm0;
        shy *= mm3;
        sy  *= mm3;
        ty  *= mm3;
        return *this;
    }
References agg::trans_affine::shx, agg::trans_affine::shy, agg::trans_affine::sx, agg::trans_affine::sy, agg::trans_affine::tx, and agg::trans_affine::ty.
scaling()
void agg::trans_affine::scaling (double * x, double * y) const inherited
scaling_abs()
void agg::trans_affine::scaling_abs (double * x, double * y) const inline inherited
    {
        // Used to calculate scaling coefficients in image resampling.
        // When there is considerable shear this method gives us much
        // better estimation than just sx, sy.
        *x = sqrt(sx  * sx  + shx * shx);
        *y = sqrt(shy * shy + sy  * sy);
    }
References agg::trans_affine::shx, agg::trans_affine::shy, sqrt(), agg::trans_affine::sx, and agg::trans_affine::sy.
store_to()
void agg::trans_affine::store_to (double * m) const inline inherited
        {
            *m++ = sx; *m++ = shy; *m++ = shx; *m++ = sy; *m++ = tx; *m++ = ty;
        }
References agg::trans_affine::shx, agg::trans_affine::shy, agg::trans_affine::sx, agg::trans_affine::sy, agg::trans_affine::tx, and agg::trans_affine::ty.
transform()
void agg::trans_affine::transform (double * x, double * y) const inline inherited
    {
        double tmp = *x;
        *x = tmp * sx  + *y * shx + tx;
        *y = tmp * shy + *y * sy  + ty;
    }
References agg::trans_affine::shx, agg::trans_affine::shy, agg::trans_affine::sx, agg::trans_affine::sy, agg::trans_affine::tx, and agg::trans_affine::ty.
transform_2x2()
void agg::trans_affine::transform_2x2 (double * x, double * y) const inline inherited
    {
        double tmp = *x;
        *x = tmp * sx  + *y * shx;
        *y = tmp * shy + *y * sy;
    }
References agg::trans_affine::shx, agg::trans_affine::shy, agg::trans_affine::sx, and agg::trans_affine::sy.
translate()
const trans_affine & agg::trans_affine::translate (double x, double y) inline inherited
    {
        tx += x;
        ty += y;
        return *this;
    }
References agg::trans_affine::tx, and agg::trans_affine::ty.
translation()
void agg::trans_affine::translation (double * dx, double * dy) const inherited
Member Data Documentation
shx
double agg::trans_affine::shx inherited
Referenced by agg::trans_affine::determinant(), agg::trans_affine::determinant_reciprocal(), agg::trans_affine::inverse_transform(), agg::trans_affine::load_from(), agg::trans_affine::rotate(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::scaling_abs(), agg::trans_affine::store_to(), agg::trans_affine::transform(), and agg::trans_affine::transform_2x2().
shy
double agg::trans_affine::shy inherited
Referenced by agg::trans_affine::determinant(), agg::trans_affine::determinant_reciprocal(), agg::trans_affine::inverse_transform(), agg::trans_affine::load_from(), agg::trans_affine::rotate(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::scaling_abs(), agg::trans_affine::store_to(), agg::trans_affine::transform(), and agg::trans_affine::transform_2x2().
sx
double agg::trans_affine::sx inherited
Referenced by agg::trans_affine::determinant(), agg::trans_affine::determinant_reciprocal(), agg::trans_affine::inverse_transform(), agg::trans_affine::load_from(), agg::trans_affine::rotate(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::scaling_abs(), agg::trans_affine::store_to(), agg::trans_affine::transform(), and agg::trans_affine::transform_2x2().
sy
double agg::trans_affine::sy inherited
Referenced by agg::trans_affine::determinant(), agg::trans_affine::determinant_reciprocal(), agg::trans_affine::inverse_transform(), agg::trans_affine::load_from(), agg::trans_affine::rotate(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::scaling_abs(), agg::trans_affine::store_to(), agg::trans_affine::transform(), and agg::trans_affine::transform_2x2().
tx
double agg::trans_affine::tx inherited
Referenced by agg::trans_affine::inverse_transform(), agg::trans_affine::load_from(), agg::trans_affine::rotate(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::store_to(), agg::trans_affine::transform(), and agg::trans_affine::translate().
ty
double agg::trans_affine::ty inherited
Referenced by agg::trans_affine::inverse_transform(), agg::trans_affine::load_from(), agg::trans_affine::rotate(), agg::trans_affine::scale(), agg::trans_affine::scale(), agg::trans_affine::store_to(), agg::trans_affine::transform(), and agg::trans_affine::translate().
The documentation for this class was generated from the following file:
src/agg/agg_trans_affine.h