Prusa Slicer: Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false > Struct Reference
Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false > Struct Reference
#include <src/eigen/Eigen/src/Core/arch/SSE/Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet1cd pmadd (const Packet1cd &x, const Packet1cd &y, const Packet1cd &c) const
EIGEN_STRONG_INLINE Packet1cd pmul (const Packet1cd &a, const Packet1cd &b) const
EIGEN_STRONG_INLINE Packet1cd pmadd (const Packet1cd &x, const Packet1cd &y, const Packet1cd &c) const
EIGEN_STRONG_INLINE Packet1cd pmul (const Packet1cd &a, const Packet1cd &b) const
Detailed Description
Member Function Documentation
pmadd() [1/2]
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmadd (const Packet1cd & x, const Packet1cd & y, const Packet1cd & c) const inline
  { return padd(pmul(x,y),c); }
References Eigen::internal::padd(), Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmul(), and Eigen::internal::y.
pmadd() [2/2]
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmadd (const Packet1cd & x, const Packet1cd & y, const Packet1cd & c) const inline
  { return padd(pmul(x,y),c); }
References Eigen::internal::padd(), Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmul(), and Eigen::internal::y.
pmul() [1/2]
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmul (const Packet1cd & a, const Packet1cd & b) const inline
  {
    #ifdef EIGEN_VECTORIZE_SSE3
    return internal::pmul(pconj(a), b);
    #else
    const __m128d mask = _mm_castsi128_pd(_mm_set_epi32(0x80000000,0x0,0x0,0x0));
    return Packet1cd(_mm_add_pd(_mm_mul_pd(vec2d_swizzle1(a.v, 0, 0), b.v),
                                _mm_xor_pd(_mm_mul_pd(vec2d_swizzle1(a.v, 1, 1),
                                                      vec2d_swizzle1(b.v, 1, 0)), mask)));
    #endif
  }
References Eigen::internal::pconj(), Eigen::internal::pmul(), and vec2d_swizzle1.
pmul() [2/2]
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmul (const Packet1cd & a, const Packet1cd & b) const inline
  {
    return internal::pmul(pconj(a), b);
  }
References Eigen::internal::pconj(), and Eigen::internal::pmul().
The documentation for this struct was generated from the following files:
src/eigen/Eigen/src/Core/arch/SSE/Complex.h
src/eigen/Eigen/src/Core/arch/ZVector/Complex.h