Prusa Slicer: Slic3r::MinAreaBoundigBox Class Reference
Slic3r::MinAreaBoundigBox Class Reference
A class that holds a rotated bounding box. If instantiated with a polygon type it will hold the minimum area bounding box for the given polygon. If the input polygon is convex, the complexity is linear to the number of points. Otherwise a convex hull of O(n*log(n)) has to be performed.
#include <src/libslic3r/MinAreaBoundingBox.hpp>
Public Types
enum PolygonLevel { pcConvex , pcSimple }
Public Member Functions
MinAreaBoundigBox (const Polygon &, PolygonLevel=pcSimple)
MinAreaBoundigBox (const ExPolygon &, PolygonLevel=pcSimple)
MinAreaBoundigBox (const Points &, PolygonLevel=pcSimple)
double angle_to_X () const
long double width () const
long double height () const
long double area () const
const Point & axis () const
Private Attributes
Point m_axis
long double m_bottom = 0.0l
long double m_right = 0.0l
Detailed Description
A class that holds a rotated bounding box. If instantiated with a polygon type it will hold the minimum area bounding box for the given polygon. If the input polygon is convex, the complexity is linear to the number of points. Otherwise a convex hull of O(n*log(n)) has to be performed.
Member Enumeration Documentation
PolygonLevel
enum Slic3r::MinAreaBoundigBox::PolygonLevel
Enumerator
pcConvex
pcSimple
                      {
        pcConvex, pcSimple
    };
Constructor & Destructor Documentation
MinAreaBoundigBox() [1/3]
Slic3r::MinAreaBoundigBox::MinAreaBoundigBox (const Polygon & p, PolygonLevel pc = pcSimple) explicit
{
    libnest2d::RotatedBox<Point, Unit> box = minAreaBoundigBox_(p, pc);
    m_right  = libnest2d::cast<long double>(box.right_extent());
    m_bottom = libnest2d::cast<long double>(box.bottom_extent());
    m_axis   = box.axis();
}
References libnest2d::RotatedBox< Pt, Unit >::axis(), libnest2d::RotatedBox< Pt, Unit >::bottom_extent(), m_axis, m_bottom, m_right, Slic3r::minAreaBoundigBox_(), and libnest2d::RotatedBox< Pt, Unit >::right_extent().
MinAreaBoundigBox() [2/3]
Slic3r::MinAreaBoundigBox::MinAreaBoundigBox (const ExPolygon & p, PolygonLevel pc = pcSimple) explicit
{
    libnest2d::RotatedBox<Point, Unit> box = minAreaBoundigBox_(p, pc);
    m_right  = libnest2d::cast<long double>(box.right_extent());
    m_bottom = libnest2d::cast<long double>(box.bottom_extent());
    m_axis   = box.axis();
}
References libnest2d::RotatedBox< Pt, Unit >::axis(), libnest2d::RotatedBox< Pt, Unit >::bottom_extent(), m_axis, m_bottom, m_right, Slic3r::minAreaBoundigBox_(), and libnest2d::RotatedBox< Pt, Unit >::right_extent().
MinAreaBoundigBox() [3/3]
Slic3r::MinAreaBoundigBox::MinAreaBoundigBox (const Points & pts, PolygonLevel pc = pcSimple) explicit
{
    libnest2d::RotatedBox<Point, Unit> box = minAreaBoundigBox_(pts, pc);
    m_right  = libnest2d::cast<long double>(box.right_extent());
    m_bottom = libnest2d::cast<long double>(box.bottom_extent());
    m_axis   = box.axis();
}
References libnest2d::RotatedBox< Pt, Unit >::axis(), libnest2d::RotatedBox< Pt, Unit >::bottom_extent(), m_axis, m_bottom, m_right, Slic3r::minAreaBoundigBox_(), and libnest2d::RotatedBox< Pt, Unit >::right_extent().
Member Function Documentation
angle_to_X()
double Slic3r::MinAreaBoundigBox::angle_to_X () const
{
    double ret = std::atan2(m_axis.y(), m_axis.x());
    auto   s   = std::signbit(ret);
    if (s) ret += 2 * PI;
    return -ret;
}
References m_axis, and PI.
Referenced by Slic3r::GUI::RotoptimizeJob::finalize().
area()
long double Slic3r::MinAreaBoundigBox::area () const
{
    long double asq = libnest2d::pl::magnsq<Point, long double>(m_axis);
    return m_bottom * m_right / asq;
}
References m_axis, m_bottom, and m_right.
axis()
const Point & Slic3r::MinAreaBoundigBox::axis () const inline
{ return m_axis; }
References m_axis.
height()
long double Slic3r::MinAreaBoundigBox::height () const
{
    return std::abs(m_right) /
           std::sqrt(libnest2d::pl::magnsq<Point, long double>(m_axis));
}
References m_axis, and m_right.
Referenced by Slic3r::GUI::RotoptimizeJob::finalize().
width()
long double Slic3r::MinAreaBoundigBox::width () const
{
    return std::abs(m_bottom) /
           std::sqrt(libnest2d::pl::magnsq<Point, long double>(m_axis));
}
References m_axis, and m_bottom.
Referenced by Slic3r::GUI::RotoptimizeJob::finalize().
Member Data Documentation
m_axis
Point Slic3r::MinAreaBoundigBox::m_axis private
Referenced by MinAreaBoundigBox(), MinAreaBoundigBox(), MinAreaBoundigBox(), angle_to_X(), area(), axis(), height(), and width().
m_bottom
long double Slic3r::MinAreaBoundigBox::m_bottom = 0.0l private
Referenced by MinAreaBoundigBox(), MinAreaBoundigBox(), MinAreaBoundigBox(), area(), and width().
m_right
long double Slic3r::MinAreaBoundigBox::m_right = 0.0l private
Referenced by MinAreaBoundigBox(), MinAreaBoundigBox(), MinAreaBoundigBox(), area(), and height().
The documentation for this class was generated from the following files:
src/libslic3r/MinAreaBoundingBox.hpp
src/libslic3r/MinAreaBoundingBox.cpp