Prusa Slicer: Slic3r::GUI::GLModel::Geometry Struct Reference
Slic3r::GUI::GLModel::Geometry Struct Reference
#include <src/slic3r/GUI/GLModel.hpp>
Classes
struct Format
Public Types
enum class EPrimitiveType : unsigned char {
Points , Triangles , TriangleStrip , TriangleFan ,
Lines , LineStrip , LineLoop
}
enum class EVertexLayout : unsigned char {
P2 , P2T2 , P3 , P3T2 ,
P3N3 , P3N3T2 , P4
}
enum class EIndexType : unsigned char { UINT , USHORT , UBYTE }
Public Member Functions
void reserve_vertices (size_t vertices_count)
void reserve_more_vertices (size_t vertices_count)
void reserve_indices (size_t indices_count)
void reserve_more_indices (size_t indices_count)
void add_vertex (const Vec2f &position)
void add_vertex (const Vec2f &position, const Vec2f &tex_coord)
void add_vertex (const Vec3f &position)
void add_vertex (const Vec3f &position, const Vec2f &tex_coord)
void add_vertex (const Vec3f &position, const Vec3f &normal)
void add_vertex (const Vec3f &position, const Vec3f &normal, const Vec2f &tex_coord)
void add_vertex (const Vec4f &position)
void set_vertex (size_t id, const Vec3f &position, const Vec3f &normal)
void set_index (size_t id, unsigned int index)
void add_index (unsigned int id)
void add_line (unsigned int id1, unsigned int id2)
void add_triangle (unsigned int id1, unsigned int id2, unsigned int id3)
Vec2f extract_position_2 (size_t id) const
Vec3f extract_position_3 (size_t id) const
Vec3f extract_normal_3 (size_t id) const
Vec2f extract_tex_coord_2 (size_t id) const
unsigned int extract_index (size_t id) const
void remove_vertex (size_t id)
bool is_empty () const
size_t vertices_count () const
size_t indices_count () const
size_t vertices_size_floats () const
size_t vertices_size_bytes () const
size_t indices_size_bytes () const
indexed_triangle_set get_as_indexed_triangle_set () const
Static Public Member Functions
static size_t vertex_stride_floats (const Format &format)
static size_t vertex_stride_bytes (const Format &format)
static size_t position_stride_floats (const Format &format)
static size_t position_stride_bytes (const Format &format)
static size_t position_offset_floats (const Format &format)
static size_t position_offset_bytes (const Format &format)
static size_t normal_stride_floats (const Format &format)
static size_t normal_stride_bytes (const Format &format)
static size_t normal_offset_floats (const Format &format)
static size_t normal_offset_bytes (const Format &format)
static size_t tex_coord_stride_floats (const Format &format)
static size_t tex_coord_stride_bytes (const Format &format)
static size_t tex_coord_offset_floats (const Format &format)
static size_t tex_coord_offset_bytes (const Format &format)
static size_t index_stride_bytes (const Geometry &data)
static bool has_position (const Format &format)
static bool has_normal (const Format &format)
static bool has_tex_coord (const Format &format)
Public Attributes
Format format
std::vector< float > vertices
std::vector< unsigned int > indices
EIndexType index_type { EIndexType::UINT }
ColorRGBA color { ColorRGBA::BLACK() }
Detailed Description
Class Documentation
Slic3r::GUI::GLModel::Geometry::Format
struct Slic3r::GUI::GLModel::Geometry::Format
Class Members
EPrimitiveType type { EPrimitiveType::Triangles }
EVertexLayout vertex_layout { EVertexLayout::P3N3 }
Member Enumeration Documentation
EIndexType
enum class Slic3r::GUI::GLModel::Geometry::EIndexType : unsigned char strong
Enumerator
UINT
USHORT
UBYTE
            {
                UINT,   // unsigned int
                USHORT, // unsigned short
                UBYTE   // unsigned byte
            };
EPrimitiveType
enum class Slic3r::GUI::GLModel::Geometry::EPrimitiveType : unsigned char strong
Enumerator
Points
Triangles
TriangleStrip
TriangleFan
Lines
LineStrip
LineLoop
            {
                Points,
                Triangles,
                TriangleStrip,
                TriangleFan,
                Lines,
                LineStrip,
                LineLoop
            };
EVertexLayout
enum class Slic3r::GUI::GLModel::Geometry::EVertexLayout : unsigned char strong
Enumerator
P2
P2T2
P3
P3T2
P3N3
P3N3T2
P4
            {
                P2,     // position 2 floats
                P2T2,   // position 2 floats + texture coords 2 floats
                P3,     // position 3 floats
                P3T2,   // position 3 floats + texture coords 2 floats
                P3N3,   // position 3 floats + normal 3 floats
                P3N3T2, // position 3 floats + normal 3 floats + texture coords 2 floats
#if ENABLE_OPENGL_ES
                P3N3E3, // position 3 floats + normal 3 floats + extra 3 floats
#endif // ENABLE_OPENGL_ES
                P4,     // position 4 floats
            };
Member Function Documentation
add_index()
void Slic3r::GUI::GLModel::Geometry::add_index (unsigned int id)
{
    indices.emplace_back(id);
}
Referenced by Slic3r::GUI::init_from_angle_arc(), Slic3r::GUI::init_from_circle(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLGizmoRotate::render_angle_arc(), Slic3r::GUI::GLGizmoRotate::render_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile().
add_line()
void Slic3r::GUI::GLModel::Geometry::add_line (unsigned int id1, unsigned int id2)
{
    indices.emplace_back(id1);
    indices.emplace_back(id2);
}
Referenced by Slic3r::GUI::SceneRaycaster::SceneRaycaster(), Slic3r::GUI::Bed3D::init_contourlines(), Slic3r::GUI::init_from_scale(), Slic3r::GUI::init_from_snap_radii(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::GUI::its_make_line(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLGizmoRotate::render_reference_radius(), Slic3r::GUI::GLGizmoRotate::render_scale(), Slic3r::GUI::GLGizmoRotate::render_snap_radii(), Slic3r::GLVolume::NonManifoldEdges::update(), and Slic3r::GUI::TriangleSelectorGUI::update_paint_contour().
add_triangle()
void Slic3r::GUI::GLModel::Geometry::add_triangle (unsigned int id1, unsigned int id2, unsigned int id3) inline
{
                indices.emplace_back(id1);
                indices.emplace_back(id2);
                indices.emplace_back(id3);
            }
References indices.
Referenced by Slic3r::GUI::GLCanvas3D::_render_background(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::init_plane_data(), Slic3r::GUI::Bed3D::init_triangles(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours(), Slic3r::thick_lines_to_geometry(), Slic3r::thick_lines_to_geometry(), Slic3r::GLVolume::SinkingContours::update(), and Slic3r::GUI::GLGizmoSimplify::update_model().
add_vertex() [1/7]
void Slic3r::GUI::GLModel::Geometry::add_vertex (const Vec2f & position)
{
    assert(format.vertex_layout == EVertexLayout::P2);
    vertices.emplace_back(position.x());
    vertices.emplace_back(position.y());
}
References format, P2, Slic3r::GUI::GLModel::Geometry::Format::vertex_layout, and vertices.
Referenced by Slic3r::GUI::SceneRaycaster::SceneRaycaster(), Slic3r::GUI::GLCanvas3D::_render_background(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::Bed3D::init_contourlines(), Slic3r::GUI::init_from_angle_arc(), Slic3r::GUI::init_from_circle(), Slic3r::GUI::init_from_scale(), Slic3r::GUI::init_from_snap_radii(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::GUI::init_plane_data(), Slic3r::GUI::Bed3D::init_triangles(), Slic3r::GUI::its_make_line(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::GLGizmoRotate::render_angle_arc(), Slic3r::GUI::GLGizmoRotate::render_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLGizmoRotate::render_reference_radius(), Slic3r::GUI::GLGizmoRotate::render_scale(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::GUI::GLGizmoRotate::render_snap_radii(), Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours(), Slic3r::thick_lines_to_geometry(), Slic3r::thick_lines_to_geometry(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GLVolume::NonManifoldEdges::update(), Slic3r::GUI::GLGizmoSimplify::update_model(), and Slic3r::GUI::TriangleSelectorGUI::update_paint_contour().
add_vertex() [2/7]
void Slic3r::GUI::GLModel::Geometry::add_vertex (const Vec2f & position, const Vec2f & tex_coord)
{
    assert(format.vertex_layout == EVertexLayout::P2T2);
    vertices.emplace_back(position.x());
    vertices.emplace_back(position.y());
    vertices.emplace_back(tex_coord.x());
    vertices.emplace_back(tex_coord.y());
}
References Slic3r::GUI::format().
add_vertex() [3/7]
void Slic3r::GUI::GLModel::Geometry::add_vertex (const Vec3f & position)
{
    assert(format.vertex_layout == EVertexLayout::P3);
    vertices.emplace_back(position.x());
    vertices.emplace_back(position.y());
    vertices.emplace_back(position.z());
}
References Slic3r::GUI::format().
add_vertex() [4/7]
void Slic3r::GUI::GLModel::Geometry::add_vertex (const Vec3f & position, const Vec2f & tex_coord)
{
    assert(format.vertex_layout == EVertexLayout::P3T2);
    vertices.insert(vertices.end(), position.data(), position.data() + 3);
    vertices.insert(vertices.end(), tex_coord.data(), tex_coord.data() + 2);
}
References Eigen::PlainObjectBase< Derived >::data(), and Slic3r::GUI::format().
add_vertex() [5/7]
void Slic3r::GUI::GLModel::Geometry::add_vertex (const Vec3f & position, const Vec3f & normal) inline
                                                                        {                        // EVertexLayout::P3N3
                assert(format.vertex_layout == EVertexLayout::P3N3);
                vertices.insert(vertices.end(), position.data(), position.data() + 3);
                vertices.insert(vertices.end(), normal.data(), normal.data() + 3);
            }
References Eigen::PlainObjectBase< Derived >::data(), format, P3N3, Slic3r::GUI::GLModel::Geometry::Format::vertex_layout, and vertices.
add_vertex() [6/7]
void Slic3r::GUI::GLModel::Geometry::add_vertex (const Vec3f & position, const Vec3f & normal, const Vec2f & tex_coord)
{
    assert(format.vertex_layout == EVertexLayout::P3N3T2);
    vertices.emplace_back(position.x());
    vertices.emplace_back(position.y());
    vertices.emplace_back(position.z());
    vertices.emplace_back(normal.x());
    vertices.emplace_back(normal.y());
    vertices.emplace_back(normal.z());
    vertices.emplace_back(tex_coord.x());
    vertices.emplace_back(tex_coord.y());
}
References Slic3r::GUI::format().
add_vertex() [7/7]
void Slic3r::GUI::GLModel::Geometry::add_vertex (const Vec4f & position)
{
    assert(format.vertex_layout == EVertexLayout::P4);
    vertices.emplace_back(position.x());
    vertices.emplace_back(position.y());
    vertices.emplace_back(position.z());
    vertices.emplace_back(position.w());
}
References Slic3r::GUI::format().
extract_index()
unsigned int Slic3r::GUI::GLModel::Geometry::extract_index (size_t id) const
{
    if (indices_count() <= id) {
        assert(false);
        return -1;
    }
    return indices[id];
}
References Slic3r::GUI::GLModel::indices_count().
Referenced by Slic3r::GUI::Bed3D::register_raycasters_for_picking(), Slic3r::thick_lines_to_geometry(), and Slic3r::thick_lines_to_geometry().
extract_normal_3()
Vec3f Slic3r::GUI::GLModel::Geometry::extract_normal_3 (size_t id) const
{
    const size_t n_stride = normal_stride_floats(format);
    if (n_stride != 3) {
        assert(false);
        return { FLT_MAX, FLT_MAX, FLT_MAX };
    }
    if (vertices_count() <= id) {
        assert(false);
        return { FLT_MAX, FLT_MAX, FLT_MAX };
    }
    const float* start = &vertices[id * vertex_stride_floats(format) + normal_offset_floats(format)];
    return { *(start + 0), *(start + 1), *(start + 2) };
}
References Slic3r::GUI::format(), and Slic3r::GUI::GLModel::vertices_count().
Referenced by Slic3r::thick_lines_to_geometry(), and Slic3r::thick_lines_to_geometry().
extract_position_2()
Vec2f Slic3r::GUI::GLModel::Geometry::extract_position_2 (size_t id) const
{
    const size_t p_stride = position_stride_floats(format);
    if (p_stride != 2) {
        assert(false);
        return { FLT_MAX, FLT_MAX };
    }
    if (vertices_count() <= id) {
        assert(false);
        return { FLT_MAX, FLT_MAX };
    }
    const float* start = &vertices[id * vertex_stride_floats(format) + position_offset_floats(format)];
    return { *(start + 0), *(start + 1) };
}
References Slic3r::GUI::format(), and Slic3r::GUI::GLModel::vertices_count().
Referenced by Slic3r::GUI::GLModel::init_from().
extract_position_3()
Vec3f Slic3r::GUI::GLModel::Geometry::extract_position_3 (size_t id) const
{
    const size_t p_stride = position_stride_floats(format);
    if (p_stride != 3) {
        assert(false);
        return { FLT_MAX, FLT_MAX, FLT_MAX };
    }
    if (vertices_count() <= id) {
        assert(false);
        return { FLT_MAX, FLT_MAX, FLT_MAX };
    }
    const float* start = &vertices[id * vertex_stride_floats(format) + position_offset_floats(format)];
    return { *(start + 0), *(start + 1), *(start + 2) };
}
References Slic3r::GUI::format(), and Slic3r::GUI::GLModel::vertices_count().
Referenced by Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::Bed3D::register_raycasters_for_picking(), Slic3r::thick_lines_to_geometry(), and Slic3r::thick_lines_to_geometry().
extract_tex_coord_2()
Vec2f Slic3r::GUI::GLModel::Geometry::extract_tex_coord_2 (size_t id) const
{
    const size_t t_stride = tex_coord_stride_floats(format);
    if (t_stride != 2) {
        assert(false);
        return { FLT_MAX, FLT_MAX };
    }
    if (vertices_count() <= id) {
        assert(false);
        return { FLT_MAX, FLT_MAX };
    }
    const float* start = &vertices[id * vertex_stride_floats(format) + tex_coord_offset_floats(format)];
    return { *(start + 0), *(start + 1) };
}
References Slic3r::GUI::format(), and Slic3r::GUI::GLModel::vertices_count().
get_as_indexed_triangle_set()
indexed_triangle_set Slic3r::GUI::GLModel::Geometry::get_as_indexed_triangle_set () const
{
    indexed_triangle_set its;
    its.vertices.reserve(vertices_count());
    for (size_t i = 0; i < vertices_count(); ++i) {
        its.vertices.emplace_back(extract_position_3(i));
    }
    its.indices.reserve(indices_count() / 3);
    for (size_t i = 0; i < indices_count() / 3; ++i) {
        const size_t tri_id = i * 3;
        its.indices.emplace_back(extract_index(tri_id), extract_index(tri_id + 1), extract_index(tri_id + 2));
    }
    return its;
}
References indexed_triangle_set::indices, Slic3r::GUI::GLModel::indices_count(), indexed_triangle_set::vertices, and Slic3r::GUI::GLModel::vertices_count().
Referenced by Slic3r::GUI::GLGizmoMeasure::GLGizmoMeasure(), and Slic3r::GUI::GLGizmoMeasure::on_render().
has_normal()
bool Slic3r::GUI::GLModel::Geometry::has_normal (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P2:
    case EVertexLayout::P2T2:
    case EVertexLayout::P3:
    case EVertexLayout::P3T2:
    case EVertexLayout::P4:     { return false; }
    case EVertexLayout::P3N3:
#if ENABLE_OPENGL_ES
    case EVertexLayout::P3N3T2:
    case EVertexLayout::P3N3E3: { return true; }
#else
    case EVertexLayout::P3N3T2: { return true; }
#endif // ENABLE_OPENGL_ES
    default:                    { assert(false); return false; }
    };
}
References Slic3r::GUI::format().
Referenced by Slic3r::GUI::GLModel::render(), and Slic3r::GUI::GLModel::render_instanced().
has_position()
bool Slic3r::GUI::GLModel::Geometry::has_position (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P2:
    case EVertexLayout::P2T2:
    case EVertexLayout::P3:
    case EVertexLayout::P3T2:
    case EVertexLayout::P3N3:
    case EVertexLayout::P3N3T2:
#if ENABLE_OPENGL_ES
    case EVertexLayout::P3N3E3:
#endif // ENABLE_OPENGL_ES
    case EVertexLayout::P4:   { return true; }
    default:                  { assert(false); return false; }
    };
}
References Slic3r::GUI::format().
Referenced by Slic3r::GUI::GLModel::render(), and Slic3r::GUI::GLModel::render_instanced().
has_tex_coord()
bool Slic3r::GUI::GLModel::Geometry::has_tex_coord (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P2T2:
    case EVertexLayout::P3T2:
    case EVertexLayout::P3N3T2: { return true; }
    case EVertexLayout::P2:
    case EVertexLayout::P3:
    case EVertexLayout::P3N3:
#if ENABLE_OPENGL_ES
    case EVertexLayout::P3N3E3:
#endif // ENABLE_OPENGL_ES
    case EVertexLayout::P4:     { return false; }
    default:                    { assert(false); return false; }
    };
}
References Slic3r::GUI::format().
Referenced by Slic3r::GUI::GLModel::render().
index_stride_bytes()
size_t Slic3r::GUI::GLModel::Geometry::index_stride_bytes (const Geometry & data) static
{
    switch (data.index_type)
    {
    case EIndexType::UINT:   { return sizeof(unsigned int); }
    case EIndexType::USHORT: { return sizeof(unsigned short); }
    case EIndexType::UBYTE:  { return sizeof(unsigned char); }
    default:                 { assert(false); return 0; }
    };
}
Referenced by indices_size_bytes(), Slic3r::GUI::GLModel::indices_size_bytes(), and Slic3r::GUI::GLModel::render().
indices_count()
size_t Slic3r::GUI::GLModel::Geometry::indices_count () const inline
{ return indices.size(); }
References indices.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::GUI::GLModel::indices_count(), is_empty(), Slic3r::GUI::Bed3D::register_raycasters_for_picking(), Slic3r::GUI::GLModel::render(), Slic3r::GUI::GCodeViewer::render_toolpaths(), reserve_indices(), reserve_more_indices(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours(), Slic3r::thick_lines_to_geometry(), Slic3r::thick_lines_to_geometry(), and Slic3r::GLVolume::SinkingContours::update().
indices_size_bytes()
size_t Slic3r::GUI::GLModel::Geometry::indices_size_bytes () const inline
{ return indices.size() * index_stride_bytes(*this); }
References index_stride_bytes(), and indices.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
is_empty()
bool Slic3r::GUI::GLModel::Geometry::is_empty () const inline
{ return vertices_count() == 0 || indices_count() == 0; }
References indices_count(), and vertices_count().
Referenced by Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::GLModel::is_empty(), Slic3r::GUI::MeshClipper::recalculate_triangles(), and Slic3r::GUI::TriangleSelectorGUI::update_paint_contour().
normal_offset_bytes()
static size_t Slic3r::GUI::GLModel::Geometry::normal_offset_bytes (const Format & format) inline static
{ return normal_offset_floats(format) * sizeof(float); }
References format, and normal_offset_floats().
Referenced by Slic3r::GUI::GLModel::render(), and Slic3r::GUI::GLModel::render_instanced().
normal_offset_floats()
size_t Slic3r::GUI::GLModel::Geometry::normal_offset_floats (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P3N3:
#if ENABLE_OPENGL_ES
    case EVertexLayout::P3N3T2:
    case EVertexLayout::P3N3E3: { return 3; }
#else
    case EVertexLayout::P3N3T2: { return 3; }
#endif // ENABLE_OPENGL_ES
    default:                    { assert(false); return 0; }
    };
}
References Slic3r::GUI::format().
Referenced by normal_offset_bytes().
normal_stride_bytes()
static size_t Slic3r::GUI::GLModel::Geometry::normal_stride_bytes (const Format & format) inline static
{ return normal_stride_floats(format) * sizeof(float); }
References format, and normal_stride_floats().
normal_stride_floats()
size_t Slic3r::GUI::GLModel::Geometry::normal_stride_floats (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P3N3:
#if ENABLE_OPENGL_ES
    case EVertexLayout::P3N3T2:
    case EVertexLayout::P3N3E3: { return 3; }
#else
    case EVertexLayout::P3N3T2: { return 3; }
#endif // ENABLE_OPENGL_ES
    default:                    { assert(false); return 0; }
    };
}
References Slic3r::GUI::format().
Referenced by normal_stride_bytes(), Slic3r::GUI::GLModel::render(), and Slic3r::GUI::GLModel::render_instanced().
position_offset_bytes()
static size_t Slic3r::GUI::GLModel::Geometry::position_offset_bytes (const Format & format) inline static
{ return position_offset_floats(format) * sizeof(float); }
References format, and position_offset_floats().
Referenced by Slic3r::GUI::GLModel::render(), and Slic3r::GUI::GLModel::render_instanced().
position_offset_floats()
size_t Slic3r::GUI::GLModel::Geometry::position_offset_floats (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P2:
    case EVertexLayout::P2T2:
    case EVertexLayout::P3:
    case EVertexLayout::P3T2:
    case EVertexLayout::P3N3:
    case EVertexLayout::P3N3T2:
#if ENABLE_OPENGL_ES
    case EVertexLayout::P3N3E3:
#endif // ENABLE_OPENGL_ES
    case EVertexLayout::P4:   { return 0; }
    default:                  { assert(false); return 0; }
    };
}
References Slic3r::GUI::format().
Referenced by Slic3r::GUI::all_vertices_inside(), and position_offset_bytes().
position_stride_bytes()
static size_t Slic3r::GUI::GLModel::Geometry::position_stride_bytes (const Format & format) inline static
{ return position_stride_floats(format) * sizeof(float); }
References format, and position_stride_floats().
position_stride_floats()
size_t Slic3r::GUI::GLModel::Geometry::position_stride_floats (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P2:
    case EVertexLayout::P2T2:   { return 2; }
    case EVertexLayout::P3:
    case EVertexLayout::P3T2:
    case EVertexLayout::P3N3:
#if ENABLE_OPENGL_ES
    case EVertexLayout::P3N3T2:
    case EVertexLayout::P3N3E3: { return 3; }
#else
    case EVertexLayout::P3N3T2: { return 3; }
#endif // ENABLE_OPENGL_ES
    case EVertexLayout::P4:     { return 4; }
    default:                    { assert(false); return 0; }
    };
}
References Slic3r::GUI::format().
Referenced by Slic3r::GUI::all_vertices_inside(), Slic3r::GUI::GLModel::init_from(), position_stride_bytes(), Slic3r::GUI::GLModel::render(), and Slic3r::GUI::GLModel::render_instanced().
remove_vertex()
void Slic3r::GUI::GLModel::Geometry::remove_vertex (size_t id)
{
    assert(id < vertices_count());
    if (id < vertices_count()) {
        const size_t stride = vertex_stride_floats(format);
        std::vector<float>::const_iterator it = vertices.begin() + id * stride;
        vertices.erase(it, it + stride);
    }
}
References Slic3r::GUI::format(), and Slic3r::GUI::GLModel::vertices_count().
Referenced by Slic3r::thick_lines_to_geometry(), and Slic3r::thick_lines_to_geometry().
reserve_indices()
void Slic3r::GUI::GLModel::Geometry::reserve_indices (size_t indices_count) inline
{ indices.reserve(indices_count); }
References indices, and indices_count().
Referenced by Slic3r::GUI::SceneRaycaster::SceneRaycaster(), Slic3r::GUI::GLCanvas3D::_render_background(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::Bed3D::init_contourlines(), Slic3r::GUI::init_from_angle_arc(), Slic3r::GUI::init_from_circle(), Slic3r::GUI::init_from_scale(), Slic3r::GUI::init_from_snap_radii(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::GUI::Bed3D::init_triangles(), Slic3r::GUI::its_make_line(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::GLGizmoRotate::render_angle_arc(), Slic3r::GUI::GLGizmoRotate::render_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLGizmoRotate::render_reference_radius(), Slic3r::GUI::GLGizmoRotate::render_scale(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::GUI::GLGizmoRotate::render_snap_radii(), Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GLVolume::NonManifoldEdges::update(), Slic3r::GUI::GLGizmoSimplify::update_model(), and Slic3r::GUI::TriangleSelectorGUI::update_paint_contour().
reserve_more_indices()
void Slic3r::GUI::GLModel::Geometry::reserve_more_indices (size_t indices_count) inline
{ indices.reserve(next_highest_power_of_2(indices.size() + indices_count)); }
References indices, indices_count(), and Slic3r::next_highest_power_of_2().
Referenced by Slic3r::thick_lines_to_geometry().
reserve_more_vertices()
void Slic3r::GUI::GLModel::Geometry::reserve_more_vertices (size_t vertices_count) inline
{ vertices.reserve(next_highest_power_of_2(vertices.size() + vertices_count * vertex_stride_floats(format))); }
References format, Slic3r::next_highest_power_of_2(), vertex_stride_floats(), vertices, and vertices_count().
Referenced by Slic3r::thick_lines_to_geometry().
reserve_vertices()
void Slic3r::GUI::GLModel::Geometry::reserve_vertices (size_t vertices_count) inline
{ vertices.reserve(vertices_count * vertex_stride_floats(format)); }
References format, vertex_stride_floats(), vertices, and vertices_count().
Referenced by Slic3r::GUI::SceneRaycaster::SceneRaycaster(), Slic3r::GUI::GLCanvas3D::_render_background(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::Bed3D::init_contourlines(), Slic3r::GUI::init_from_angle_arc(), Slic3r::GUI::init_from_circle(), Slic3r::GUI::init_from_scale(), Slic3r::GUI::init_from_snap_radii(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::GUI::Bed3D::init_triangles(), Slic3r::GUI::its_make_line(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::GLGizmoRotate::render_angle_arc(), Slic3r::GUI::GLGizmoRotate::render_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLGizmoRotate::render_reference_radius(), Slic3r::GUI::GLGizmoRotate::render_scale(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::GUI::GLGizmoRotate::render_snap_radii(), Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GLVolume::NonManifoldEdges::update(), Slic3r::GUI::GLGizmoSimplify::update_model(), and Slic3r::GUI::TriangleSelectorGUI::update_paint_contour().
set_index()
void Slic3r::GUI::GLModel::Geometry::set_index (size_t id, unsigned int index)
{
    assert(id < indices_count());
    if (id < indices_count())
        indices[id] = index;
}
References Slic3r::GUI::GLModel::indices_count().
Referenced by Slic3r::thick_lines_to_geometry(), and Slic3r::thick_lines_to_geometry().
set_vertex()
void Slic3r::GUI::GLModel::Geometry::set_vertex (size_t id, const Vec3f & position, const Vec3f & normal)
{
    assert(format.vertex_layout == EVertexLayout::P3N3);
    assert(id < vertices_count());
    if (id < vertices_count()) {
        float* start = &vertices[id * vertex_stride_floats(format)];
        *(start + 0) = position.x();
        *(start + 1) = position.y();
        *(start + 2) = position.z();
        *(start + 3) = normal.x();
        *(start + 4) = normal.y();
        *(start + 5) = normal.z();
    }
}
References Slic3r::GUI::format(), and Slic3r::GUI::GLModel::vertices_count().
Referenced by Slic3r::thick_lines_to_geometry(), and Slic3r::thick_lines_to_geometry().
tex_coord_offset_bytes()
static size_t Slic3r::GUI::GLModel::Geometry::tex_coord_offset_bytes (const Format & format) inline static
{ return tex_coord_offset_floats(format) * sizeof(float); }
References format, and tex_coord_offset_floats().
Referenced by Slic3r::GUI::GLModel::render().
tex_coord_offset_floats()
size_t Slic3r::GUI::GLModel::Geometry::tex_coord_offset_floats (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P2T2:   { return 2; }
    case EVertexLayout::P3T2:   { return 3; }
    case EVertexLayout::P3N3T2: { return 6; }
    default:                    { assert(false); return 0; }
    };
}
References Slic3r::GUI::format().
Referenced by tex_coord_offset_bytes().
tex_coord_stride_bytes()
static size_t Slic3r::GUI::GLModel::Geometry::tex_coord_stride_bytes (const Format & format) inline static
{ return tex_coord_stride_floats(format) * sizeof(float); }
References format, and tex_coord_stride_floats().
tex_coord_stride_floats()
size_t Slic3r::GUI::GLModel::Geometry::tex_coord_stride_floats (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P2T2:
    case EVertexLayout::P3T2:
    case EVertexLayout::P3N3T2: { return 2; }
    default:                    { assert(false); return 0; }
    };
}
References Slic3r::GUI::format().
Referenced by Slic3r::GUI::GLModel::render(), and tex_coord_stride_bytes().
vertex_stride_bytes()
static size_t Slic3r::GUI::GLModel::Geometry::vertex_stride_bytes (const Format & format) inline static
{ return vertex_stride_floats(format) * sizeof(float); }
References format, and vertex_stride_floats().
Referenced by Slic3r::GUI::GLModel::render(), and Slic3r::GUI::GLModel::render_instanced().
vertex_stride_floats()
size_t Slic3r::GUI::GLModel::Geometry::vertex_stride_floats (const Format & format) static
{
    switch (format.vertex_layout)
    {
    case EVertexLayout::P2:     { return 2; }
    case EVertexLayout::P2T2:   { return 4; }
    case EVertexLayout::P3:     { return 3; }
    case EVertexLayout::P3T2:   { return 5; }
    case EVertexLayout::P3N3:   { return 6; }
    case EVertexLayout::P3N3T2: { return 8; }
#if ENABLE_OPENGL_ES
    case EVertexLayout::P3N3E3: { return 9; }
#endif // ENABLE_OPENGL_ES
    case EVertexLayout::P4:     { return 4; }
    default:                    { assert(false); return 0; }
    };
}
References Slic3r::GUI::format().
Referenced by Slic3r::GUI::all_vertices_inside(), reserve_more_vertices(), reserve_vertices(), vertex_stride_bytes(), vertices_count(), and Slic3r::GUI::GLModel::vertices_size_floats().
vertices_count()
size_t Slic3r::GUI::GLModel::Geometry::vertices_count () const inline
{ return vertices.size() / vertex_stride_floats(format); }
References format, vertex_stride_floats(), and vertices.
Referenced by Slic3r::GUI::Bed3D::init_contourlines(), Slic3r::GUI::Bed3D::init_gridlines(), is_empty(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::Bed3D::register_raycasters_for_picking(), Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), reserve_more_vertices(), reserve_vertices(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours(), Slic3r::thick_lines_to_geometry(), Slic3r::thick_lines_to_geometry(), Slic3r::GLVolume::SinkingContours::update(), and Slic3r::GUI::GLModel::vertices_count().
vertices_size_bytes()
size_t Slic3r::GUI::GLModel::Geometry::vertices_size_bytes () const inline
{ return vertices_size_floats() * sizeof(float); }
References vertices_size_floats().
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), and Slic3r::GUI::GCodeViewer::load_toolpaths().
vertices_size_floats()
size_t Slic3r::GUI::GLModel::Geometry::vertices_size_floats () const inline
{ return vertices.size(); }
References vertices.
Referenced by vertices_size_bytes().
Member Data Documentation
color
ColorRGBA Slic3r::GUI::GLModel::Geometry::color { ColorRGBA::BLACK() }
Referenced by Slic3r::GUI::SceneRaycaster::SceneRaycaster(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::GLModel::get_color(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLModel::set_color(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours(), Slic3r::GLVolume::SinkingContours::update(), and Slic3r::GUI::TriangleSelectorGUI::update_paint_contour().
format
Format Slic3r::GUI::GLModel::Geometry::format
Referenced by Slic3r::GUI::SceneRaycaster::SceneRaycaster(), Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::GUI::GLCanvas3D::_render_background(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), add_vertex(), add_vertex(), Slic3r::GUI::all_vertices_inside(), Slic3r::GUI::Bed3D::init_contourlines(), Slic3r::GUI::init_from_angle_arc(), Slic3r::GUI::init_from_circle(), Slic3r::GUI::init_from_scale(), Slic3r::GUI::init_from_snap_radii(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::GUI::init_plane_data(), Slic3r::GUI::Bed3D::init_triangles(), Slic3r::GUI::its_make_line(), normal_offset_bytes(), normal_stride_bytes(), Slic3r::GUI::GLGizmoMove3D::on_render(), position_offset_bytes(), position_stride_bytes(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::GLGizmoRotate::render_angle_arc(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::GLGizmoRotate::render_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLGizmoRotate::render_reference_radius(), Slic3r::GUI::GLGizmoRotate::render_scale(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::GUI::GLGizmoRotate::render_snap_radii(), Slic3r::GUI::GLTexture::render_sub_texture(), reserve_more_vertices(), reserve_vertices(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours(), tex_coord_offset_bytes(), tex_coord_stride_bytes(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GLVolume::NonManifoldEdges::update(), Slic3r::GUI::GLGizmoSimplify::update_model(), Slic3r::GUI::TriangleSelectorGUI::update_paint_contour(), Slic3r::GUI::TriangleSelectorGUI::update_render_data(), vertex_stride_bytes(), vertices_count(), and Slic3r::GUI::GLModel::vertices_size_floats().
index_type
EIndexType Slic3r::GUI::GLModel::Geometry::index_type { EIndexType::UINT }
indices
std::vector<unsigned int> Slic3r::GUI::GLModel::Geometry::indices
Referenced by add_triangle(), Slic3r::GUI::GLModel::cpu_memory_used(), Slic3r::GUI::GLModel::gpu_memory_used(), Slic3r::GUI::GCodeViewer::TBuffer::has_data(), indices_count(), indices_size_bytes(), Slic3r::GUI::GLGizmoMove3D::on_render(), reserve_indices(), reserve_more_indices(), and Slic3r::GUI::GLModel::reset().
vertices
std::vector<float> Slic3r::GUI::GLModel::Geometry::vertices
Referenced by add_vertex(), add_vertex(), Slic3r::GUI::all_vertices_inside(), Slic3r::GUI::GLModel::cpu_memory_used(), Slic3r::GUI::GLModel::gpu_memory_used(), Slic3r::GUI::GCodeViewer::TBuffer::has_data(), Slic3r::GUI::GLGizmoMove3D::on_render(), reserve_more_vertices(), reserve_vertices(), Slic3r::GUI::GLModel::reset(), vertices_count(), and vertices_size_floats().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GLModel.hpp
src/slic3r/GUI/GLModel.cpp