Prusa Slicer: ClipperLib::PolyTree Class Reference
ClipperLib::PolyTree Class Reference
#include <src/clipper/clipper.hpp>
Public Member Functions
PolyTree ()
PolyTree (PolyTree &&src)
virtual ~PolyTree ()
PolyTree & operator= (PolyTree &&src)
PolyNode * GetFirst () const
void Clear ()
int Total () const
void RemoveOutermostPolygon ()
PolyNode * GetNext () const
bool IsHole () const
bool IsOpen () const
int ChildCount () const
Public Attributes
Path Contour
PolyNodes Childs
PolyNode * Parent
Private Member Functions
PolyTree (const PolyTree &src)=delete
PolyTree & operator= (const PolyTree &src)=delete
PolyNode * GetNextSiblingUp () const
void AddChild (PolyNode &child)
Private Attributes
std::vector< PolyNode, Allocator< PolyNode > > AllNodes
unsigned Index
bool m_IsOpen
JoinType m_jointype
EndType m_endtype
Friends
class Clipper
Detailed Description
Constructor & Destructor Documentation
PolyTree() [1/3]
ClipperLib::PolyTree::PolyTree () inline
{}
PolyTree() [2/3]
ClipperLib::PolyTree::PolyTree (PolyTree && src) inline
{ *this = std::move(src); }
~PolyTree()
virtual ClipperLib::PolyTree::~PolyTree () inline virtual
{Clear();};
PolyTree() [3/3]
ClipperLib::PolyTree::PolyTree (const PolyTree & src) private delete
Member Function Documentation
AddChild()
void ClipperLib::PolyNode::AddChild (PolyNode & child) private inherited
{
  unsigned cnt = (unsigned)Childs.size();
  Childs.emplace_back(&child);
  child.Parent = this;
  child.Index = cnt;
}
References ClipperLib::PolyNode::Index, and ClipperLib::PolyNode::Parent.
Referenced by ClipperLib::ClipperOffset::AddPath(), and ClipperLib::Clipper::BuildResult2().
ChildCount()
int ClipperLib::PolyNode::ChildCount () const inline inherited
{ return (int)Childs.size(); }
Referenced by ClipperLib::ClipperOffset::AddPath(), ClipperLib::AddPolyNodeToPaths(), ClipperLib::ClipperOffset::Clear(), ClipperLib::ClipperOffset::DoOffset(), ClipperLib::ClipperOffset::FixOrientations(), Slic3r::has_duplicate_points(), ClipperLib::OpenPathsFromPolyTree(), Slic3r::PolyTreeToExPolygons(), RemoveOutermostPolygon(), and Slic3r::top_level_islands().
Clear()
void ClipperLib::PolyTree::Clear () inline
{  AllNodes.clear(); Childs.clear(); }
Referenced by ClipperLib::Clipper::BuildResult2(), and ClipperLib::ClipperOffset::Execute().
GetFirst()
PolyNode * ClipperLib::PolyTree::GetFirst () const inline
{ return Childs.empty() ? nullptr : Childs.front(); }
GetNext()
PolyNode * ClipperLib::PolyNode::GetNext () const inline inherited
{ return Childs.empty() ? GetNextSiblingUp() : Childs.front(); }
GetNextSiblingUp()
PolyNode * ClipperLib::PolyNode::GetNextSiblingUp () const inline private inherited
{ return Parent ? ((Index == Parent->Childs.size() - 1) ? Parent->GetNextSiblingUp() : Parent->Childs[Index + 1]) : nullptr; }
References ClipperLib::PolyNode::Childs, and ClipperLib::PolyNode::GetNextSiblingUp().
Referenced by ClipperLib::PolyNode::GetNextSiblingUp().
IsHole()
bool ClipperLib::PolyNode::IsHole () const inherited
{
  bool result = true;
  PolyNode* node = Parent;
  while (node)
  {
      result = !result;
      node = node->Parent;
  }
  return result;
}
References ClipperLib::PolyNode::Parent.
Referenced by Slic3r::traverse_pt(), and Slic3r::traverse_pt_noholes().
IsOpen()
bool ClipperLib::PolyNode::IsOpen () const inline inherited
{ return m_IsOpen; }
Referenced by ClipperLib::AddPolyNodeToPaths().
operator=() [1/2]
PolyTree & ClipperLib::PolyTree::operator= (const PolyTree & src) private delete
operator=() [2/2]
PolyTree & ClipperLib::PolyTree::operator= (PolyTree && src) inline
{
        AllNodes   = std::move(src.AllNodes);
        Contour    = std::move(src.Contour);
        Childs     = std::move(src.Childs);
        Parent     = nullptr;
        Index      = src.Index;
        m_IsOpen   = src.m_IsOpen;
        m_jointype = src.m_jointype;
        m_endtype  = src.m_endtype;
        for (size_t i = 0; i < Childs.size(); ++ i)
          Childs[i]->Parent = this;
        return *this;
    }
RemoveOutermostPolygon()
void ClipperLib::PolyTree::RemoveOutermostPolygon ()
{
    if (this->ChildCount() == 1 && this->Childs[0]->ChildCount() > 0) {
        PolyNode *outerNode = this->Childs[0];
        this->Childs.reserve(outerNode->ChildCount());
        this->Childs[0] = outerNode->Childs[0];
        this->Childs[0]->Parent = outerNode->Parent;
        for (int i = 1; i < outerNode->ChildCount(); ++i)
            this->AddChild(*outerNode->Childs[i]);
    } else
        this->Clear();
}
References ClipperLib::PolyNode::ChildCount(), ClipperLib::PolyNode::Childs, and ClipperLib::PolyNode::Parent.
Referenced by ClipperLib::ClipperOffset::Execute(), and Slic3r::remove_outermost_polygon< ClipperLib::PolyTree >().
Total()
int ClipperLib::PolyTree::Total () const
{
  int result = (int)AllNodes.size();
  //with negative offsets, ignore the hidden outer polygon ...
  if (result > 0 && Childs.front() != &AllNodes.front()) result--;
  return result;
}
Referenced by ClipperLib::ClosedPathsFromPolyTree(), Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint(), ClipperLib::OpenPathsFromPolyTree(), and ClipperLib::PolyTreeToPaths().
Friends And Related Symbol Documentation
Clipper
friend class Clipper friend
Member Data Documentation
AllNodes
std::vector<PolyNode, Allocator<PolyNode> > ClipperLib::PolyTree::AllNodes private
Referenced by ClipperLib::Clipper::BuildResult2().
Childs
PolyNodes ClipperLib::PolyNode::Childs inherited
Referenced by ClipperLib::ClipperOffset::AddPath(), ClipperLib::AddPolyNodeToPaths(), ClipperLib::Clipper::BuildResult2(), ClipperLib::ClipperOffset::Clear(), Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint(), ClipperLib::ClipperOffset::DoOffset(), ClipperLib::ClipperOffset::FixOrientations(), ClipperLib::PolyNode::GetNextSiblingUp(), Slic3r::has_duplicate_points(), ClipperLib::OpenPathsFromPolyTree(), Slic3r::PolyTreeToExPolygons(), Slic3r::PolyTreeToPolylines(), RemoveOutermostPolygon(), Slic3r::top_level_islands(), Slic3r::traverse_pt(), Slic3r::traverse_pt(), and Slic3r::traverse_pt_noholes().
Contour
Path ClipperLib::PolyNode::Contour inherited
Referenced by ClipperLib::ClipperOffset::AddPath(), ClipperLib::AddPolyNodeToPaths(), ClipperLib::Clipper::BuildResult2(), ClipperLib::ClipperOffset::DoOffset(), ClipperLib::ClipperOffset::FixOrientations(), Slic3r::has_duplicate_points(), Slic3r::PolyTreeToPolylines(), Slic3r::traverse_pt(), Slic3r::traverse_pt(), and Slic3r::traverse_pt_noholes().
Index
unsigned ClipperLib::PolyNode::Index private inherited
Referenced by ClipperLib::PolyNode::AddChild(), and ClipperLib::Clipper::BuildResult2().
m_endtype
EndType ClipperLib::PolyNode::m_endtype private inherited
Referenced by ClipperLib::ClipperOffset::AddPath(), ClipperLib::ClipperOffset::DoOffset(), and ClipperLib::ClipperOffset::FixOrientations().
m_IsOpen
bool ClipperLib::PolyNode::m_IsOpen private inherited
m_jointype
JoinType ClipperLib::PolyNode::m_jointype private inherited
Referenced by ClipperLib::ClipperOffset::AddPath(), and ClipperLib::ClipperOffset::DoOffset().
Parent
PolyNode* ClipperLib::PolyNode::Parent inherited
Referenced by ClipperLib::PolyNode::AddChild(), ClipperLib::Clipper::BuildResult2(), ClipperLib::PolyNode::IsHole(), and RemoveOutermostPolygon().
The documentation for this class was generated from the following files:
src/clipper/clipper.hpp
src/clipper/clipper.cpp