Prusa Slicer: Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased > Struct Template Reference
#include <src/eigen/Eigen/src/Core/CoreEvaluators.h>
Public Types
enum { CoeffReadCost = evaluator<ArgType>::CoeffReadCost + functor_traits<UnaryOp>::Cost , Flags , Alignment = evaluator<ArgType>::Alignment }
typedef CwiseUnaryOp< UnaryOp, ArgType > XprType
typedef XprType::CoeffReturnType CoeffReturnType
enum
typedef traits< CwiseUnaryOp< UnaryOp, ArgType > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE unary_evaluator (const XprType &op)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
Protected Attributes
const UnaryOp m_functor
evaluator< ArgType > m_argImpl
Detailed Description
template<typename UnaryOp, typename ArgType>
struct Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >
Member Typedef Documentation
CoeffReturnType
template<typename UnaryOp , typename ArgType > typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::CoeffReturnType
ExpressionTraits
typedef traits<CwiseUnaryOp< UnaryOp, ArgType > > Eigen::internal::evaluator_base< CwiseUnaryOp< UnaryOp, ArgType > >::ExpressionTraits inherited
XprType
template<typename UnaryOp , typename ArgType > typedef CwiseUnaryOp<UnaryOp, ArgType> Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    Alignment = 0
  };
anonymous enum
template<typename UnaryOp , typename ArgType > anonymous enum
Enumerator
CoeffReadCost
Flags
Alignment
       {
    CoeffReadCost = evaluator<ArgType>::CoeffReadCost + functor_traits<UnaryOp>::Cost,
    Flags = evaluator<ArgType>::Flags
          & (HereditaryBits | LinearAccessBit | (functor_traits<UnaryOp>::PacketAccess ? PacketAccessBit : 0)),
    Alignment = evaluator<ArgType>::Alignment
  };
Constructor & Destructor Documentation
unary_evaluator()
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::unary_evaluator (const XprType & op) inline explicit
    : m_functor(op.functor()),
      m_argImpl(op.nestedExpression())
  {
    EIGEN_INTERNAL_CHECK_COST_VALUE(functor_traits<UnaryOp>::Cost);
    EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
  }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::coeff (Index index) const inline
  {
    return m_functor(m_argImpl.coeff(index));
  }
coeff() [2/2]
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::coeff (Index row, Index col) const inline
  {
    return m_functor(m_argImpl.coeff(row, col));
  }
References col(), and row().
packet() [1/2]
template<typename UnaryOp , typename ArgType > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::packet (Index index) const inline
  {
    return m_functor.packetOp(m_argImpl.template packet<LoadMode, PacketType>(index));
  }
packet() [2/2]
template<typename UnaryOp , typename ArgType > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::packet (Index row, Index col) const inline
  {
    return m_functor.packetOp(m_argImpl.template packet<LoadMode, PacketType>(row, col));
  }
References col(), and row().
Member Data Documentation
m_argImpl
template<typename UnaryOp , typename ArgType > evaluator<ArgType> Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::m_argImpl protected
m_functor
template<typename UnaryOp , typename ArgType > const UnaryOp Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::m_functor protected
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/CoreEvaluators.h