Prusa Slicer: Slic3r::anonymous_namespace{SL1_SVG.cpp} Namespace Reference
Slic3r::anonymous_namespace{SL1_SVG.cpp} Namespace Reference
Functions
char const * decimal_from (coord_t snumber, char *buffer)
std::string coord2str (coord_t crd)
void transform (ExPolygon &ep, const sla::RasterBase::Trafo &tr, const BoundingBox &bb)
void append_svg (std::string &buf, const Polygon &poly)
Variables
size_t constexpr coord_t_bufsize = 40
Function Documentation
append_svg()
void Slic3r::anonymous_namespace{SL1_SVG.cpp}::append_svg (std::string & buf, const Polygon & poly)
{
    if (poly.points.empty())
        return;
    Point c = poly.points.front();
    char intbuf[coord_t_bufsize];
    buf += "<path d=\"M "sv;
    buf += decimal_from(c.x(), intbuf);
    buf += " "sv;
    buf += decimal_from(c.y(), intbuf);
    buf += " l "sv;
    for (const Point &p : poly) {
        Point d = p - c;
        if (d.x() == 0 && d.y() == 0)
            continue;
        buf += " "sv;
        buf += decimal_from(d.x(), intbuf);
        buf += " "sv;
        buf += decimal_from(d.y(), intbuf);
        c = p;
    }
    buf += " z\""sv; // mark path as closed
    buf += " />\n"sv;
}
References append_svg(), coord_t_bufsize, decimal_from(), and Slic3r::MultiPoint::points.
Referenced by append_svg().
coord2str()
std::string Slic3r::anonymous_namespace{SL1_SVG.cpp}::coord2str (coord_t crd) inline
{
    char buf[coord_t_bufsize];
    return decimal_from(crd, buf);
}
References coord2str(), coord_t_bufsize, and decimal_from().
Referenced by coord2str().
decimal_from()
char const * Slic3r::anonymous_namespace{SL1_SVG.cpp}::decimal_from (coord_t snumber, char * buffer)
{
    std::make_unsigned_t<coord_t> number = 0;
    char* ret = buffer;
    if( snumber < 0 ) {
        *buffer++ = '-';
        number = -snumber;
    } else
        number = snumber;
    if( number == 0 ) {
        *buffer++ = '0';
    } else {
        char* p_first = buffer;
        while( number != 0 ) {
            *buffer++ = '0' + number % 10;
            number /= 10;
        }
        std::reverse( p_first, buffer );
    }
    *buffer = '\0';
    return ret;
}
References decimal_from(), and number().
Referenced by append_svg(), coord2str(), and decimal_from().
transform()
void Slic3r::anonymous_namespace{SL1_SVG.cpp}::transform (ExPolygon & ep, const sla::RasterBase::Trafo & tr, const BoundingBox & bb)
{
    if (tr.flipXY) {
        for (auto &p : ep.contour.points) std::swap(p.x(), p.y());
        for (auto &h : ep.holes)
            for (auto &p : h.points) std::swap(p.x(), p.y());
    }
    if (tr.mirror_x){
        for (auto &p : ep.contour.points) p.x() = bb.max.x() - p.x() + bb.min.x();
        for (auto &h : ep.holes)
            for (auto &p : h.points) p.x() = bb.max.x() - p.x() + bb.min.x();
    }
    if (tr.mirror_y){
        for (auto &p : ep.contour.points) p.y() = bb.max.y() - p.y() + bb.min.y();
        for (auto &h : ep.holes)
            for (auto &p : h.points) p.y() = bb.max.y() - p.y() + bb.min.y();
    }
}
References Slic3r::ExPolygon::contour, Slic3r::sla::RasterBase::Trafo::flipXY, Slic3r::ExPolygon::holes, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::sla::RasterBase::Trafo::mirror_x, Slic3r::sla::RasterBase::Trafo::mirror_y, and Slic3r::MultiPoint::points.
Variable Documentation
coord_t_bufsize
size_t constexpr Slic3r::anonymous_namespace{SL1_SVG.cpp}::coord_t_bufsize = 40 constexpr
Referenced by append_svg(), and coord2str().