Prusa Slicer: Slic3r::MeshSlicingParamsEx Struct Reference
Slic3r::MeshSlicingParamsEx Struct Reference
#include <src/libslic3r/TriangleMeshSlicer.hpp>
Public Types
enum class SlicingMode : uint32_t { Regular , EvenOdd , Positive , PositiveLargestContour }
Public Attributes
float closing_radius { 0 }
float extra_offset { 0 }
double resolution { 0 }
SlicingMode mode { SlicingMode::Regular }
size_t slicing_mode_normal_below_layer { 0 }
SlicingMode mode_below { SlicingMode::Regular }
Transform3d trafo { Transform3d::Identity() }
Detailed Description
Member Enumeration Documentation
SlicingMode
enum class Slic3r::MeshSlicingParams::SlicingMode : uint32_t strong inherited
Enumerator
Regular
EvenOdd
Positive
PositiveLargestContour
                           : uint32_t {
        // Regular slicing, maintain all contours and their orientation.
        // slice_mesh_ex() applies ClipperLib::pftNonZero rule to the result of slice_mesh().
        Regular,
        // For slicing 3DLabPrints plane models (aka to be compatible with S3D default strategy).
        // slice_mesh_ex() applies ClipperLib::pftEvenOdd rule. slice_mesh() slices EvenOdd as Regular.
        EvenOdd,
        // Maintain all contours, orient all contours CCW.
        // slice_mesh_ex() applies ClipperLib::pftNonZero rule, thus holes will be closed.
        Positive,
        // Orient all contours CCW and keep only the contour with the largest area.
        // This mode is useful for slicing complex objects in vase mode.
        PositiveLargestContour,
    };
Member Data Documentation
closing_radius
float Slic3r::MeshSlicingParamsEx::closing_radius { 0 }
Referenced by Slic3r::SLAPrint::Steps::slice_model(), Slic3r::slice_volumes_inner(), and Slic3r::SLAPrint::Steps::support_points().
extra_offset
float Slic3r::MeshSlicingParamsEx::extra_offset { 0 }
Referenced by Slic3r::slice_volumes_inner().
mode
SlicingMode Slic3r::MeshSlicingParams::mode { SlicingMode::Regular } inherited
Referenced by Slic3r::FFFTreeSupport::organic_draw_branches(), Slic3r::slice_mesh_ex(), Slic3r::SLAPrint::Steps::slice_model(), and Slic3r::slice_volumes_inner().
mode_below
SlicingMode Slic3r::MeshSlicingParams::mode_below { SlicingMode::Regular } inherited
Referenced by Slic3r::slice_mesh_ex(), and Slic3r::slice_volumes_inner().
resolution
double Slic3r::MeshSlicingParamsEx::resolution { 0 }
Referenced by Slic3r::slice_volumes_inner().
slicing_mode_normal_below_layer
size_t Slic3r::MeshSlicingParams::slicing_mode_normal_below_layer { 0 } inherited
Referenced by Slic3r::slice_volumes_inner().
trafo
Transform3d Slic3r::MeshSlicingParams::trafo { Transform3d::Identity() } inherited
Referenced by Slic3r::mmu_segmentation_top_and_bottom_layers(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::slice_mesh(), Slic3r::slice_mesh(), Slic3r::PrintObject::slice_support_volumes(), Slic3r::slice_volume(), Slic3r::slice_volumes_inner(), and Slic3r::GLVolume::SinkingContours::update().
The documentation for this struct was generated from the following file:
src/libslic3r/TriangleMeshSlicer.hpp