Prusa Slicer: Slic3r::BoundaryInfillGraph Struct Reference
Slic3r::BoundaryInfillGraph Struct Reference
Public Types
enum Direction {
Left , Right , Up , Down ,
Taken
}
Public Member Functions
const Point & point (const ContourIntersectionPoint &cp) const
const Point & infill_end_point (size_t infill_end_point_idx) const
const Point interpolate_contour_point (const ContourIntersectionPoint &cp, double param)
const Direction dir_prev (const ContourIntersectionPoint &cp) const
const Direction dir_next (const ContourIntersectionPoint &cp) const
bool first (const ContourIntersectionPoint &cp) const
const ContourIntersectionPoint & other (const ContourIntersectionPoint &cp) const
ContourIntersectionPoint & other (const ContourIntersectionPoint &cp)
bool prev_vertical (const ContourIntersectionPoint &cp) const
bool next_vertical (const ContourIntersectionPoint &cp) const
Static Public Member Functions
static Direction dir (const Point &p1, const Point &p2)
Public Attributes
std::vector< Points > boundary
std::vector< std::vector< double > > boundary_params
std::vector< ContourIntersectionPoint > map_infill_end_point_to_boundary
Detailed Description
Member Enumeration Documentation
Direction
enum Slic3r::BoundaryInfillGraph::Direction
Enumerator
Left
Right
Up
Down
Taken
                   {
        Left,
        Right,
        Up,
        Down,
        Taken,
    };
Member Function Documentation
dir()
static Direction Slic3r::BoundaryInfillGraph::dir (const Point & p1, const Point & p2) inline static
{
        return p1.x() == p2.x() ?
            (p1.y() < p2.y() ? Up : Down) :
            (p1.x() < p2.x() ? Right : Left);
    }
References Down, Left, Right, and Up.
Referenced by dir_next(), and dir_prev().
dir_next()
const Direction Slic3r::BoundaryInfillGraph::dir_next (const ContourIntersectionPoint & cp) const inline
{
        assert(cp.next_on_contour);
        return cp.could_take_next() ?
            dir(this->point(cp), this->point(*cp.next_on_contour)) :
            Taken;
    }
References Slic3r::ContourIntersectionPoint::could_take_next(), dir(), Slic3r::ContourIntersectionPoint::next_on_contour, point(), and Taken.
Referenced by Slic3r::Fill::connect_base_support().
dir_prev()
const Direction Slic3r::BoundaryInfillGraph::dir_prev (const ContourIntersectionPoint & cp) const inline
{
        assert(cp.prev_on_contour);
        return cp.could_take_prev() ?
            dir(this->point(cp), this->point(*cp.prev_on_contour)) :
            Taken;
    }
References Slic3r::ContourIntersectionPoint::could_take_prev(), dir(), point(), Slic3r::ContourIntersectionPoint::prev_on_contour, and Taken.
Referenced by Slic3r::Fill::connect_base_support().
first()
bool Slic3r::BoundaryInfillGraph::first (const ContourIntersectionPoint & cp) const inline
{
        return ((&cp - this->map_infill_end_point_to_boundary.data()) & 1) == 0;
    }
Referenced by Slic3r::base_support_extend_infill_lines(), and Slic3r::Fill::connect_base_support().
infill_end_point()
const Point & Slic3r::BoundaryInfillGraph::infill_end_point (size_t infill_end_point_idx) const inline
{
        return this->point(this->map_infill_end_point_to_boundary[infill_end_point_idx]);
    }
References point().
interpolate_contour_point()
const Point Slic3r::BoundaryInfillGraph::interpolate_contour_point (const ContourIntersectionPoint & cp, double param) inline
{
        const Points                &contour        = this->boundary[cp.contour_idx];
        const std::vector<double>   &contour_params = this->boundary_params[cp.contour_idx];
        // Find the start of a contour segment with param.
        auto it = std::lower_bound(contour_params.begin(), contour_params.end(), param);
        if (*it != param) {
            assert(it != contour_params.begin());
            -- it;
        }
        size_t i = it - contour_params.begin();
        if (i == contour.size())
            i = 0;
        double t1 = contour_params[i];
        double t2 = next_value_modulo(i, contour_params);
        return lerp(contour[i], next_value_modulo(i, contour), (param - t1) / (t2 - t1));
    }
References Slic3r::contour(), Slic3r::ContourIntersectionPoint::contour_idx, Slic3r::lerp(), Slic3r::next_value_modulo(), and Slic3r::MultiPoint::size().
next_vertical()
bool Slic3r::BoundaryInfillGraph::next_vertical (const ContourIntersectionPoint & cp) const inline
{
        return this->point(cp).x() == this->point(*cp.next_on_contour).x();
    }
References Slic3r::ContourIntersectionPoint::next_on_contour, and point().
Referenced by Slic3r::base_support_extend_infill_lines().
other() [1/2]
ContourIntersectionPoint & Slic3r::BoundaryInfillGraph::other (const ContourIntersectionPoint & cp) inline
{
        return this->map_infill_end_point_to_boundary[((&cp - this->map_infill_end_point_to_boundary.data()) ^ 1)];
    }
other() [2/2]
const ContourIntersectionPoint & Slic3r::BoundaryInfillGraph::other (const ContourIntersectionPoint & cp) const inline
{
        return this->map_infill_end_point_to_boundary[((&cp - this->map_infill_end_point_to_boundary.data()) ^ 1)];
    }
Referenced by Slic3r::Fill::connect_base_support().
point()
const Point & Slic3r::BoundaryInfillGraph::point (const ContourIntersectionPoint & cp) const inline
{
        assert(cp.contour_idx != size_t(-1));
        assert(cp.point_idx != size_t(-1));
        return this->boundary[cp.contour_idx][cp.point_idx];
    }
References Slic3r::ContourIntersectionPoint::contour_idx, and Slic3r::ContourIntersectionPoint::point_idx.
Referenced by Slic3r::Fill::connect_base_support(), dir_next(), dir_prev(), Slic3r::evaluate_support_arches(), infill_end_point(), next_vertical(), and prev_vertical().
prev_vertical()
bool Slic3r::BoundaryInfillGraph::prev_vertical (const ContourIntersectionPoint & cp) const inline
{
        return this->point(cp).x() == this->point(*cp.prev_on_contour).x();
    }
References point(), and Slic3r::ContourIntersectionPoint::prev_on_contour.
Referenced by Slic3r::base_support_extend_infill_lines().
Member Data Documentation
boundary
std::vector<Points> Slic3r::BoundaryInfillGraph::boundary
Referenced by Slic3r::base_support_extend_infill_lines(), Slic3r::Fill::connect_base_support(), Slic3r::Fill::connect_infill(), Slic3r::create_boundary_infill_graph(), Slic3r::evaluate_support_arches(), and Slic3r::mark_boundary_segments_overlapping_infill().
boundary_params
std::vector<std::vector<double> > Slic3r::BoundaryInfillGraph::boundary_params
Referenced by Slic3r::base_support_extend_infill_lines(), Slic3r::Fill::connect_base_support(), Slic3r::Fill::connect_infill(), Slic3r::create_boundary_infill_graph(), Slic3r::evaluate_support_arches(), and Slic3r::mark_boundary_segments_overlapping_infill().
map_infill_end_point_to_boundary
std::vector<ContourIntersectionPoint> Slic3r::BoundaryInfillGraph::map_infill_end_point_to_boundary
Referenced by Slic3r::base_support_extend_infill_lines(), Slic3r::Fill::connect_base_support(), Slic3r::Fill::connect_infill(), Slic3r::create_boundary_infill_graph(), Slic3r::evaluate_support_arches(), and Slic3r::mark_boundary_segments_overlapping_infill().
The documentation for this struct was generated from the following file:
src/libslic3r/Fill/FillBase.cpp