Prusa Slicer: Slic3r::GUI::GCodeViewer Class Reference
Slic3r::GUI::GCodeViewer Class Reference
#include <src/slic3r/GUI/GCodeViewer.hpp>
Classes
class COG
struct Extrusions
struct IBuffer
struct InstanceVBuffer
class Layers
struct LegendResizer
struct Path
struct RenderPath
struct RenderPathPropertyEqual
struct RenderPathPropertyLower
struct SequentialRangeCap
struct SequentialView
struct Shells
struct TBuffer
struct VBuffer
Public Types
enum class EViewType : unsigned char {
FeatureType , Height , Width , Feedrate ,
FanSpeed , Temperature , VolumetricRate , LayerTimeLinear ,
LayerTimeLogarithmic , Tool , ColorPrint , Count
}
Public Member Functions
GCodeViewer ()
~GCodeViewer ()
void init ()
void load (const GCodeProcessorResult &gcode_result, const Print &print)
void refresh (const GCodeProcessorResult &gcode_result, const std::vector< std::string > &str_tool_colors)
void refresh_render_paths (bool keep_sequential_current_first, bool keep_sequential_current_last) const
void update_shells_color_by_extruder (const DynamicPrintConfig *config)
void reset ()
void render ()
void render_cog ()
bool has_data () const
bool can_export_toolpaths () const
const BoundingBoxf3 & get_paths_bounding_box () const
const BoundingBoxf3 & get_max_bounding_box () const
const std::vector< double > & get_layers_zs () const
const SequentialView & get_sequential_view () const
void update_sequential_view_current (unsigned int first, unsigned int last)
bool is_contained_in_bed () const
EViewType get_view_type () const
void set_view_type (EViewType type)
bool is_toolpath_move_type_visible (EMoveType type) const
void set_toolpath_move_type_visible (EMoveType type, bool visible)
unsigned int get_toolpath_role_visibility_flags () const
void set_toolpath_role_visibility_flags (unsigned int flags)
unsigned int get_options_visibility_flags () const
void set_options_visibility_from_flags (unsigned int flags)
void set_layers_z_range (const std::array< unsigned int, 2 > &layers_z_range)
bool is_legend_enabled () const
void enable_legend (bool enable)
void export_toolpaths_to_obj (const char *filename) const
void toggle_gcode_window_visibility ()
std::vector< CustomGCode::Item > & get_custom_gcode_per_print_z ()
size_t get_extruders_count ()
void invalidate_legend ()
const ConflictResultOpt & get_conflict_result () const
Private Types
enum class EOptionsColors : unsigned char {
Retractions , Unretractions , Seams , ToolChanges ,
ColorChanges , PausePrints , CustomGCodes
}
using IBufferType = unsigned short
using VertexBuffer = std::vector< float >
using MultiVertexBuffer = std::vector< VertexBuffer >
using IndexBuffer = std::vector< IBufferType >
using MultiIndexBuffer = std::vector< IndexBuffer >
using InstanceBuffer = std::vector< float >
using InstanceIdBuffer = std::vector< size_t >
using InstancesOffsets = std::vector< Vec3f >
Private Member Functions
void load_toolpaths (const GCodeProcessorResult &gcode_result)
void load_shells (const Print &print)
void render_toolpaths ()
void render_shells ()
void render_legend (float &legend_height)
bool is_visible (GCodeExtrusionRole role) const
bool is_visible (const Path &path) const
void log_memory_used (const std::string &label, int64_t additional=0) const
ColorRGBA option_color (EMoveType move_type) const
Private Attributes
bool m_gl_data_initialized { false }
unsigned int m_last_result_id { 0 }
EViewType m_last_view_type { EViewType::Count }
size_t m_moves_count { 0 }
std::vector< TBuffer > m_buffers { static_cast<size_t>(EMoveType::Extrude) }
BoundingBoxf3 m_paths_bounding_box
BoundingBoxf3 m_max_bounding_box
float m_max_print_height { 0.0f }
std::vector< ColorRGBA > m_tool_colors
Layers m_layers
std::array< unsigned int, 2 > m_layers_z_range
std::vector< GCodeExtrusionRole > m_roles
size_t m_extruders_count
std::vector< unsigned char > m_extruder_ids
std::vector< float > m_filament_diameters
std::vector< float > m_filament_densities
Extrusions m_extrusions
SequentialView m_sequential_view
Shells m_shells
COG m_cog
EViewType m_view_type { EViewType::FeatureType }
bool m_legend_enabled { true }
LegendResizer m_legend_resizer
PrintEstimatedStatistics m_print_statistics
PrintEstimatedStatistics::ETimeMode m_time_estimate_mode { PrintEstimatedStatistics::ETimeMode::Normal }
GCodeProcessorResult::SettingsIds m_settings_ids
std::array< SequentialRangeCap, 2 > m_sequential_range_caps
std::array< std::vector< float >, static_cast< size_t >(PrintEstimatedStatistics::ETimeMode::Count)> m_layers_times
std::vector< CustomGCode::Item > m_custom_gcode_per_print_z
bool m_contained_in_bed { true }
ConflictResultOpt m_conflict_result
Static Private Attributes
static const std::array< ColorRGBA, static_cast< size_t >(GCodeExtrusionRole::Count)> Extrusion_Role_Colors
static const std::vector< ColorRGBA > Options_Colors
static const std::vector< ColorRGBA > Travel_Colors
static const std::vector< ColorRGBA > Range_Colors
static const ColorRGBA Wipe_Color = ColorRGBA::YELLOW()
static const ColorRGBA Neutral_Color = ColorRGBA::DARK_GRAY()
Detailed Description
Class Documentation
Slic3r::GUI::GCodeViewer::Shells
struct Slic3r::GUI::GCodeViewer::Shells
Class Members
bool visible { false }
GLVolumeCollection volumes
Member Typedef Documentation
IBufferType
using Slic3r::GUI::GCodeViewer::IBufferType = unsigned short private
IndexBuffer
using Slic3r::GUI::GCodeViewer::IndexBuffer = std::vector<IBufferType> private
InstanceBuffer
using Slic3r::GUI::GCodeViewer::InstanceBuffer = std::vector<float> private
InstanceIdBuffer
using Slic3r::GUI::GCodeViewer::InstanceIdBuffer = std::vector<size_t> private
InstancesOffsets
using Slic3r::GUI::GCodeViewer::InstancesOffsets = std::vector<Vec3f> private
MultiIndexBuffer
using Slic3r::GUI::GCodeViewer::MultiIndexBuffer = std::vector<IndexBuffer> private
MultiVertexBuffer
using Slic3r::GUI::GCodeViewer::MultiVertexBuffer = std::vector<VertexBuffer> private
VertexBuffer
using Slic3r::GUI::GCodeViewer::VertexBuffer = std::vector<float> private
Member Enumeration Documentation
EOptionsColors
enum class Slic3r::GUI::GCodeViewer::EOptionsColors : unsigned char strong private
Enumerator
Retractions
Unretractions
Seams
ToolChanges
ColorChanges
PausePrints
CustomGCodes
    {
        Retractions,
        Unretractions,
        Seams,
        ToolChanges,
        ColorChanges,
        PausePrints,
        CustomGCodes
    };
EViewType
enum class Slic3r::GUI::GCodeViewer::EViewType : unsigned char strong
Enumerator
FeatureType
Height
Width
Feedrate
FanSpeed
Temperature
VolumetricRate
LayerTimeLinear
LayerTimeLogarithmic
Tool
ColorPrint
Count
    {
        FeatureType,
        Height,
        Width,
        Feedrate,
        FanSpeed,
        Temperature,
        VolumetricRate,
        LayerTimeLinear,
        LayerTimeLogarithmic,
        Tool,
        ColorPrint,
        Count
    };
Constructor & Destructor Documentation
GCodeViewer()
Slic3r::GUI::GCodeViewer::GCodeViewer ()
{
    m_extrusions.reset_role_visibility_flags();
    m_shells.volumes.set_use_raycasters(false);
//    m_sequential_view.skip_invisible_moves = true;
}
References m_extrusions, m_shells, Slic3r::GUI::GCodeViewer::Extrusions::reset_role_visibility_flags(), Slic3r::GLVolumeCollection::set_use_raycasters(), and Slic3r::GUI::GCodeViewer::Shells::volumes.
~GCodeViewer()
Slic3r::GUI::GCodeViewer::~GCodeViewer () inline
{ reset(); }
References reset().
Member Function Documentation
can_export_toolpaths()
bool Slic3r::GUI::GCodeViewer::can_export_toolpaths () const
{
    return has_data() && m_buffers[buffer_id(EMoveType::Extrude)].render_primitive_type == TBuffer::ERenderPrimitiveType::Triangle;
}
References Slic3r::GUI::buffer_id(), Slic3r::Extrude, has_data(), m_buffers, and Slic3r::GUI::GCodeViewer::TBuffer::Triangle.
Referenced by Slic3r::GUI::GLCanvas3D::has_toolpaths_to_export().
enable_legend()
void Slic3r::GUI::GCodeViewer::enable_legend (bool enable) inline
{ m_legend_enabled = enable; }
References m_legend_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::enable_legend_texture(), and Slic3r::GUI::GLCanvas3D::show_legend().
export_toolpaths_to_obj()
void Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj (const char * filename) const
{
    if (filename == nullptr)
        return;
    if (!has_data())
        return;
    wxBusyCursor busy;
    // the data needed is contained into the Extrude TBuffer
    const TBuffer& t_buffer = m_buffers[buffer_id(EMoveType::Extrude)];
    if (!t_buffer.has_data())
        return;
    if (t_buffer.render_primitive_type != TBuffer::ERenderPrimitiveType::Triangle)
        return;
    // collect color information to generate materials
    std::vector<ColorRGBA> colors;
    for (const RenderPath& path : t_buffer.render_paths) {
        colors.push_back(path.color);
    }
    sort_remove_duplicates(colors);
    // save materials file
    boost::filesystem::path mat_filename(filename);
    mat_filename.replace_extension("mtl");
    CNumericLocalesSetter locales_setter;
    FILE* fp = boost::nowide::fopen(mat_filename.string().c_str(), "w");
    if (fp == nullptr) {
        BOOST_LOG_TRIVIAL(error) << "GCodeViewer::export_toolpaths_to_obj: Couldn't open " << mat_filename.string().c_str() << " for writing";
        return;
    }
    fprintf(fp, "# G-Code Toolpaths Materials\n");
    fprintf(fp, "# Generated by %s-%s based on Slic3r\n", SLIC3R_APP_NAME, SLIC3R_VERSION);
    unsigned int colors_count = 1;
    for (const ColorRGBA& color : colors) {
        fprintf(fp, "\nnewmtl material_%d\n", colors_count++);
        fprintf(fp, "Ka 1 1 1\n");
        fprintf(fp, "Kd %g %g %g\n", color.r(), color.g(), color.b());
        fprintf(fp, "Ks 0 0 0\n");
    }
    fclose(fp);
    // save geometry file
    fp = boost::nowide::fopen(filename, "w");
    if (fp == nullptr) {
        BOOST_LOG_TRIVIAL(error) << "GCodeViewer::export_toolpaths_to_obj: Couldn't open " << filename << " for writing";
        return;
    }
    fprintf(fp, "# G-Code Toolpaths\n");
    fprintf(fp, "# Generated by %s-%s based on Slic3r\n", SLIC3R_APP_NAME, SLIC3R_VERSION);
    fprintf(fp, "\nmtllib ./%s\n", mat_filename.filename().string().c_str());
    const size_t floats_per_vertex = t_buffer.vertices.vertex_size_floats();
    std::vector<Vec3f> out_vertices;
    std::vector<Vec3f> out_normals;
    struct VerticesOffset
    {
        unsigned int vbo;
        size_t offset;
    };
    std::vector<VerticesOffset> vertices_offsets;
    vertices_offsets.push_back({ t_buffer.vertices.vbos.front(), 0 });
    // get vertices/normals data from vertex buffers on gpu
    for (size_t i = 0; i < t_buffer.vertices.vbos.size(); ++i) {
        const size_t floats_count = t_buffer.vertices.sizes[i] / sizeof(float);
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, t_buffer.vertices.vbos[i]));
#if ENABLE_OPENGL_ES
        const VertexBuffer vertices = *static_cast<VertexBuffer*>(::glMapBufferRange(GL_ARRAY_BUFFER, 0,
            static_cast<GLsizeiptr>(t_buffer.vertices.sizes[i]), GL_MAP_READ_BIT));
        glcheck();
        glsafe(::glUnmapBuffer(GL_ARRAY_BUFFER));
#else
        VertexBuffer vertices(floats_count);
        glsafe(::glGetBufferSubData(GL_ARRAY_BUFFER, 0, static_cast<GLsizeiptr>(t_buffer.vertices.sizes[i]), static_cast<void*>(vertices.data())));
#endif // ENABLE_OPENGL_ES
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
        const size_t vertices_count = floats_count / floats_per_vertex;
        for (size_t j = 0; j < vertices_count; ++j) {
            const size_t base = j * floats_per_vertex;
            out_vertices.push_back({ vertices[base + 0], vertices[base + 1], vertices[base + 2] });
            out_normals.push_back({ vertices[base + 3], vertices[base + 4], vertices[base + 5] });
        }
        if (i < t_buffer.vertices.vbos.size() - 1)
            vertices_offsets.push_back({ t_buffer.vertices.vbos[i + 1], vertices_offsets.back().offset + vertices_count });
    }
    // save vertices to file
    fprintf(fp, "\n# vertices\n");
    for (const Vec3f& v : out_vertices) {
        fprintf(fp, "v %g %g %g\n", v.x(), v.y(), v.z());
    }
    // save normals to file
    fprintf(fp, "\n# normals\n");
    for (const Vec3f& n : out_normals) {
        fprintf(fp, "vn %g %g %g\n", n.x(), n.y(), n.z());
    }
    size_t i = 0;
    for (const ColorRGBA& color : colors) {
        // save material triangles to file
        fprintf(fp, "\nusemtl material_%zu\n", i + 1);
        fprintf(fp, "# triangles material %zu\n", i + 1);
        for (const RenderPath& render_path : t_buffer.render_paths) {
            if (render_path.color != color)
                continue;
            const IBuffer& ibuffer = t_buffer.indices[render_path.ibuffer_id];
            size_t vertices_offset = 0;
            for (size_t j = 0; j < vertices_offsets.size(); ++j) {
                const VerticesOffset& offset = vertices_offsets[j];
                if (offset.vbo == ibuffer.vbo) {
                    vertices_offset = offset.offset;
                    break;
                }
            }
            // get indices data from index buffer on gpu
            glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ibuffer.ibo));
            for (size_t j = 0; j < render_path.sizes.size(); ++j) {
#if ENABLE_OPENGL_ES
                const IndexBuffer indices = *static_cast<IndexBuffer*>(::glMapBufferRange(GL_ELEMENT_ARRAY_BUFFER,
                    static_cast<GLintptr>(render_path.offsets[j]), static_cast<GLsizeiptr>(render_path.sizes[j] * sizeof(IBufferType)),
                    GL_MAP_READ_BIT));
                glcheck();
                glsafe(::glUnmapBuffer(GL_ELEMENT_ARRAY_BUFFER));
#else
                IndexBuffer indices(render_path.sizes[j]);
                glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>(render_path.offsets[j]),
                    static_cast<GLsizeiptr>(render_path.sizes[j] * sizeof(IBufferType)), static_cast<void*>(indices.data())));
#endif // ENABLE_OPENGL_ES
                const size_t triangles_count = render_path.sizes[j] / 3;
                for (size_t k = 0; k < triangles_count; ++k) {
                    const size_t base = k * 3;
                    const size_t v1 = 1 + static_cast<size_t>(indices[base + 0]) + vertices_offset;
                    const size_t v2 = 1 + static_cast<size_t>(indices[base + 1]) + vertices_offset;
                    const size_t v3 = 1 + static_cast<size_t>(indices[base + 2]) + vertices_offset;
                    if (v1 != v2)
                        // do not export dummy triangles
                        fprintf(fp, "f %zu//%zu %zu//%zu %zu//%zu\n", v1, v1, v2, v2, v3, v3);
                }
            }
            glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
        }
        ++i;
    }
    fclose(fp);
}
References Slic3r::GUI::buffer_id(), error, Slic3r::Extrude, glcheck, glsafe, Slic3r::GUI::GCodeViewer::TBuffer::has_data(), has_data(), Slic3r::GUI::GCodeViewer::IBuffer::ibo, Slic3r::GUI::GCodeViewer::TBuffer::indices, m_buffers, Slic3r::offset(), Slic3r::GUI::GCodeViewer::TBuffer::render_paths, Slic3r::GUI::GCodeViewer::TBuffer::render_primitive_type, Slic3r::GUI::GCodeViewer::VBuffer::sizes, Slic3r::sort_remove_duplicates(), Slic3r::GUI::GCodeViewer::TBuffer::Triangle, Slic3r::GUI::GCodeViewer::IBuffer::vbo, Slic3r::GUI::GCodeViewer::VBuffer::vbos, Slic3r::GUI::GCodeViewer::VBuffer::vertex_size_floats(), and Slic3r::GUI::GCodeViewer::TBuffer::vertices.
Referenced by Slic3r::GUI::GLCanvas3D::export_toolpaths_to_obj().
get_conflict_result()
const ConflictResultOpt & Slic3r::GUI::GCodeViewer::get_conflict_result () const inline
{ return m_conflict_result; }
References m_conflict_result.
get_custom_gcode_per_print_z()
std::vector< CustomGCode::Item > & Slic3r::GUI::GCodeViewer::get_custom_gcode_per_print_z () inline
{ return m_custom_gcode_per_print_z; }
References m_custom_gcode_per_print_z.
Referenced by Slic3r::GUI::GLCanvas3D::get_custom_gcode_per_print_z().
get_extruders_count()
size_t Slic3r::GUI::GCodeViewer::get_extruders_count () inline
{ return m_extruders_count; }
References m_extruders_count.
Referenced by Slic3r::GUI::GLCanvas3D::get_gcode_extruders_count().
get_layers_zs()
const std::vector< double > & Slic3r::GUI::GCodeViewer::get_layers_zs () const inline
{ return m_layers.get_zs(); }
References Slic3r::GUI::GCodeViewer::Layers::get_zs(), and m_layers.
Referenced by Slic3r::GUI::GLCanvas3D::get_gcode_layers_zs().
get_max_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::GCodeViewer::get_max_bounding_box () const inline
{ return m_max_bounding_box; }
References m_max_bounding_box.
Referenced by Slic3r::GUI::GLCanvas3D::_max_bounding_box().
get_options_visibility_flags()
unsigned int Slic3r::GUI::GCodeViewer::get_options_visibility_flags () const
{
    auto set_flag = [](unsigned int flags, unsigned int flag, bool active) {
        return active ? (flags | (1 << flag)) : flags;
    };
    unsigned int flags = 0;
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::Travel), is_toolpath_move_type_visible(EMoveType::Travel));
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::Wipe), is_toolpath_move_type_visible(EMoveType::Wipe));
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::Retractions), is_toolpath_move_type_visible(EMoveType::Retract));
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::Unretractions), is_toolpath_move_type_visible(EMoveType::Unretract));
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::Seams), is_toolpath_move_type_visible(EMoveType::Seam));
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::ToolChanges), is_toolpath_move_type_visible(EMoveType::Tool_change));
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::ColorChanges), is_toolpath_move_type_visible(EMoveType::Color_change));
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::PausePrints), is_toolpath_move_type_visible(EMoveType::Pause_Print));
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::CustomGCodes), is_toolpath_move_type_visible(EMoveType::Custom_GCode));
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::CenterOfGravity), m_cog.is_visible());
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::Shells), m_shells.visible);
    flags = set_flag(flags, static_cast<unsigned int>(Preview::OptionType::ToolMarker), m_sequential_view.marker.is_visible());
    return flags;
}
References Slic3r::GUI::Preview::CenterOfGravity, Slic3r::Color_change, Slic3r::GUI::Preview::ColorChanges, Slic3r::Custom_GCode, Slic3r::GUI::Preview::CustomGCodes, is_toolpath_move_type_visible(), Slic3r::GUI::GCodeViewer::COG::is_visible(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::is_visible(), m_cog, m_sequential_view, m_shells, Slic3r::GUI::GCodeViewer::SequentialView::marker, Slic3r::Pause_Print, Slic3r::GUI::Preview::PausePrints, Slic3r::Retract, Slic3r::GUI::Preview::Retractions, Slic3r::Seam, Slic3r::GUI::Preview::Seams, Slic3r::GUI::Preview::Shells, Slic3r::Tool_change, Slic3r::GUI::Preview::ToolChanges, Slic3r::GUI::Preview::ToolMarker, Slic3r::Travel, Slic3r::GUI::Preview::Travel, Slic3r::Unretract, Slic3r::GUI::Preview::Unretractions, Slic3r::GUI::GCodeViewer::Shells::visible, Slic3r::Wipe, and Slic3r::GUI::Preview::Wipe.
Referenced by Slic3r::GUI::GLCanvas3D::get_gcode_options_visibility_flags(), and render_legend().
get_paths_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::GCodeViewer::get_paths_bounding_box () const inline
{ return m_paths_bounding_box; }
References m_paths_bounding_box.
Referenced by Slic3r::GUI::GLCanvas3D::on_char(), and Slic3r::GUI::GLCanvas3D::zoom_to_gcode().
get_sequential_view()
const SequentialView & Slic3r::GUI::GCodeViewer::get_sequential_view () const inline
{ return m_sequential_view; }
References m_sequential_view.
Referenced by Slic3r::GUI::GLCanvas3D::get_gcode_sequential_view().
get_toolpath_role_visibility_flags()
unsigned int Slic3r::GUI::GCodeViewer::get_toolpath_role_visibility_flags () const inline
{ return m_extrusions.role_visibility_flags; }
References m_extrusions, and Slic3r::GUI::GCodeViewer::Extrusions::role_visibility_flags.
Referenced by Slic3r::GUI::GLCanvas3D::get_toolpath_role_visibility_flags().
get_view_type()
EViewType Slic3r::GUI::GCodeViewer::get_view_type () const inline
{ return m_view_type; }
References m_view_type.
Referenced by Slic3r::GUI::GLCanvas3D::get_gcode_view_preview_type(), Slic3r::GUI::GLCanvas3D::get_gcode_view_type(), and render_legend().
has_data()
bool Slic3r::GUI::GCodeViewer::has_data () const inline
{ return !m_roles.empty(); }
References m_roles.
Referenced by can_export_toolpaths(), export_toolpaths_to_obj(), and Slic3r::GUI::GLCanvas3D::set_toolpaths_z_range().
init()
void Slic3r::GUI::GCodeViewer::init ()
{
    if (m_gl_data_initialized)
        return;
    // initializes opengl data of TBuffers
    for (size_t i = 0; i < m_buffers.size(); ++i) {
        TBuffer& buffer = m_buffers[i];
        EMoveType type = buffer_type(i);
        switch (type)
        {
        default: { break; }
        case EMoveType::Tool_change:
        case EMoveType::Color_change:
        case EMoveType::Pause_Print:
        case EMoveType::Custom_GCode:
        case EMoveType::Retract:
        case EMoveType::Unretract:
        case EMoveType::Seam: {
#if !DISABLE_GCODEVIEWER_INSTANCED_MODELS
            if (wxGetApp().is_gl_version_greater_or_equal_to(3, 3)) {
                buffer.render_primitive_type = TBuffer::ERenderPrimitiveType::InstancedModel;
                buffer.shader = "gouraud_light_instanced";
                buffer.model.model.init_from(diamond(16));
                buffer.model.color = option_color(type);
                buffer.model.instances.format = InstanceVBuffer::EFormat::InstancedModel;
            }
            else {
#endif // !DISABLE_GCODEVIEWER_INSTANCED_MODELS
                buffer.render_primitive_type = TBuffer::ERenderPrimitiveType::BatchedModel;
                buffer.vertices.format = VBuffer::EFormat::PositionNormal3;
                buffer.shader = "gouraud_light";
                buffer.model.data = diamond(16);
                buffer.model.color = option_color(type);
                buffer.model.instances.format = InstanceVBuffer::EFormat::BatchedModel;
#if !DISABLE_GCODEVIEWER_INSTANCED_MODELS
            }
#endif // !DISABLE_GCODEVIEWER_INSTANCED_MODELS
                break;
        }
        case EMoveType::Wipe:
        case EMoveType::Extrude: {
            buffer.render_primitive_type = TBuffer::ERenderPrimitiveType::Triangle;
            buffer.vertices.format = VBuffer::EFormat::PositionNormal3;
            buffer.shader = "gouraud_light";
            break;
        }
        case EMoveType::Travel: {
            buffer.render_primitive_type = TBuffer::ERenderPrimitiveType::Line;
            buffer.vertices.format = VBuffer::EFormat::Position;
#if ENABLE_GL_CORE_PROFILE
            // on MAC using the geometry shader of dashed_thick_lines is too slow
            buffer.shader = "flat";
//            buffer.shader = OpenGLManager::get_gl_info().is_core_profile() ? "dashed_thick_lines" : "flat";
#else
            buffer.shader = "flat";
#endif // ENABLE_GL_CORE_PROFILE
            break;
        }
        }
        set_toolpath_move_type_visible(EMoveType::Extrude, true);
    }
    // initializes tool marker
    m_sequential_view.marker.init();
    m_gl_data_initialized = true;
}
References Slic3r::GUI::GCodeViewer::InstanceVBuffer::BatchedModel, Slic3r::GUI::GCodeViewer::TBuffer::BatchedModel, Slic3r::GUI::buffer_type(), Slic3r::GUI::GCodeViewer::TBuffer::Model::color, Slic3r::Color_change, Slic3r::Custom_GCode, Slic3r::GUI::GCodeViewer::TBuffer::Model::data, Slic3r::GUI::diamond(), Slic3r::Extrude, Slic3r::GUI::GCodeViewer::VBuffer::format, Slic3r::GUI::GCodeViewer::InstanceVBuffer::format, Slic3r::GUI::GCodeViewer::SequentialView::Marker::init(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GCodeViewer::InstanceVBuffer::InstancedModel, Slic3r::GUI::GCodeViewer::TBuffer::InstancedModel, Slic3r::GUI::GCodeViewer::TBuffer::Model::instances, Slic3r::GUI::GCodeViewer::TBuffer::Line, m_buffers, m_gl_data_initialized, m_sequential_view, Slic3r::GUI::GCodeViewer::SequentialView::marker, Slic3r::GUI::GCodeViewer::TBuffer::Model::model, Slic3r::GUI::GCodeViewer::TBuffer::model, option_color(), Slic3r::Pause_Print, Slic3r::GUI::GCodeViewer::VBuffer::Position, Slic3r::GUI::GCodeViewer::VBuffer::PositionNormal3, Slic3r::GUI::GCodeViewer::TBuffer::render_primitive_type, Slic3r::Retract, Slic3r::Seam, set_toolpath_move_type_visible(), Slic3r::GUI::GCodeViewer::TBuffer::shader, Slic3r::Tool_change, Slic3r::Travel, Slic3r::GUI::GCodeViewer::TBuffer::Triangle, Slic3r::Unretract, Slic3r::GUI::GCodeViewer::TBuffer::vertices, and Slic3r::Wipe.
Referenced by Slic3r::GUI::GLCanvas3D::init_gcode_viewer(), Slic3r::GUI::GCodeViewer::COG::render(), and Slic3r::GUI::GLCanvas3D::render().
invalidate_legend()
void Slic3r::GUI::GCodeViewer::invalidate_legend () inline
{ m_legend_resizer.reset(); }
References m_legend_resizer, and Slic3r::GUI::GCodeViewer::LegendResizer::reset().
Referenced by Slic3r::GUI::GLCanvas3D::msw_rescale().
is_contained_in_bed()
bool Slic3r::GUI::GCodeViewer::is_contained_in_bed () const inline
{ return m_contained_in_bed; }
References m_contained_in_bed.
is_legend_enabled()
bool Slic3r::GUI::GCodeViewer::is_legend_enabled () const inline
{ return m_legend_enabled; }
References m_legend_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::is_gcode_legend_enabled(), and Slic3r::GUI::GLCanvas3D::is_legend_shown().
is_toolpath_move_type_visible()
bool Slic3r::GUI::GCodeViewer::is_toolpath_move_type_visible (EMoveType type) const
{
    size_t id = static_cast<size_t>(buffer_id(type));
    return (id < m_buffers.size()) ? m_buffers[id].visible : false;
}
References Slic3r::GUI::buffer_id(), and m_buffers.
Referenced by get_options_visibility_flags().
is_visible() [1/2]
bool Slic3r::GUI::GCodeViewer::is_visible (const Path & path) const inline private
{ return is_visible(path.role); }
References is_visible(), and Slic3r::GUI::GCodeViewer::Path::role.
Referenced by is_visible().
is_visible() [2/2]
bool Slic3r::GUI::GCodeViewer::is_visible (GCodeExtrusionRole role) const inline private
{
        return role < GCodeExtrusionRole::Count && (m_extrusions.role_visibility_flags & (1 << int(role))) != 0;
    }
References Slic3r::Count, m_extrusions, and Slic3r::GUI::GCodeViewer::Extrusions::role_visibility_flags.
Referenced by refresh(), refresh_render_paths(), render_legend(), and update_sequential_view_current().
load()
void Slic3r::GUI::GCodeViewer::load (const GCodeProcessorResult & gcode_result, const Print & print)
{
    // avoid processing if called with the same gcode_result
    if (m_last_result_id == gcode_result.id &&
        (m_last_view_type == m_view_type || (m_last_view_type != EViewType::VolumetricRate && m_view_type != EViewType::VolumetricRate)))
        return;
    m_last_result_id = gcode_result.id;
    m_last_view_type = m_view_type;
    // release gpu memory, if used
    reset();
    m_sequential_view.gcode_window.load_gcode(gcode_result.filename, gcode_result.lines_ends);
    if (wxGetApp().is_gcode_viewer())
        m_custom_gcode_per_print_z = gcode_result.custom_gcode_per_print_z;
    m_max_print_height = gcode_result.max_print_height;
    load_toolpaths(gcode_result);
    if (m_layers.empty())
        return;
    m_settings_ids = gcode_result.settings_ids;
    m_filament_diameters = gcode_result.filament_diameters;
    m_filament_densities = gcode_result.filament_densities;
    if (wxGetApp().is_editor())
        load_shells(print);
    else {
        Pointfs bed_shape;
        std::string texture;
        std::string model;
        if (!gcode_result.bed_shape.empty()) {
            // bed shape detected in the gcode
            bed_shape = gcode_result.bed_shape;
            const auto bundle = wxGetApp().preset_bundle;
            if (bundle != nullptr && !m_settings_ids.printer.empty()) {
                const Preset* preset = bundle->printers.find_preset(m_settings_ids.printer);
                if (preset != nullptr) {
                    model = PresetUtils::system_printer_bed_model(*preset);
                    texture = PresetUtils::system_printer_bed_texture(*preset);
                }
            }
        }
        else {
            // adjust printbed size in dependence of toolpaths bbox
            const double margin = 10.0;
            const Vec2d min(m_paths_bounding_box.min.x() - margin, m_paths_bounding_box.min.y() - margin);
            const Vec2d max(m_paths_bounding_box.max.x() + margin, m_paths_bounding_box.max.y() + margin);
            const Vec2d size = max - min;
            bed_shape = {
                { min.x(), min.y() },
                { max.x(), min.y() },
                { max.x(), min.y() + 0.442265 * size.y()},
                { max.x() - 10.0, min.y() + 0.4711325 * size.y()},
                { max.x() + 10.0, min.y() + 0.5288675 * size.y()},
                { max.x(), min.y() + 0.557735 * size.y()},
                { max.x(), max.y() },
                { min.x() + 0.557735 * size.x(), max.y()},
                { min.x() + 0.5288675 * size.x(), max.y() - 10.0},
                { min.x() + 0.4711325 * size.x(), max.y() + 10.0},
                { min.x() + 0.442265 * size.x(), max.y()},
                { min.x(), max.y() } };
        }
        wxGetApp().plater()->set_bed_shape(bed_shape, gcode_result.max_print_height, texture, model, gcode_result.bed_shape.empty());
    }
    m_print_statistics = gcode_result.print_statistics;
    if (m_time_estimate_mode != PrintEstimatedStatistics::ETimeMode::Normal) {
        const float time = m_print_statistics.modes[static_cast<size_t>(m_time_estimate_mode)].time;
        if (time == 0.0f ||
            short_time(get_time_dhms(time)) == short_time(get_time_dhms(m_print_statistics.modes[static_cast<size_t>(PrintEstimatedStatistics::ETimeMode::Normal)].time)))
            m_time_estimate_mode = PrintEstimatedStatistics::ETimeMode::Normal;
    }
    m_conflict_result = gcode_result.conflict_result;
    if (m_conflict_result.has_value()) { m_conflict_result->layer = m_layers.get_l_at(m_conflict_result->_height); }
}
References Slic3r::GCodeProcessorResult::bed_shape, Slic3r::GCodeProcessorResult::conflict_result, Slic3r::GCodeProcessorResult::custom_gcode_per_print_z, Slic3r::GUI::GCodeViewer::Layers::empty(), Slic3r::GCodeProcessorResult::filament_densities, Slic3r::GCodeProcessorResult::filament_diameters, Slic3r::GCodeProcessorResult::filename, Slic3r::GUI::GCodeViewer::SequentialView::gcode_window, Slic3r::GUI::GCodeViewer::Layers::get_l_at(), Slic3r::get_time_dhms(), Slic3r::GCodeProcessorResult::id, Slic3r::GCodeProcessorResult::lines_ends, Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::load_gcode(), load_shells(), load_toolpaths(), m_conflict_result, m_custom_gcode_per_print_z, m_filament_densities, m_filament_diameters, m_last_result_id, m_last_view_type, m_layers, m_max_print_height, m_paths_bounding_box, m_print_statistics, m_sequential_view, m_settings_ids, m_time_estimate_mode, m_view_type, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::GCodeProcessorResult::max_print_height, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::PrintEstimatedStatistics::modes, Slic3r::PrintEstimatedStatistics::Normal, Slic3r::GCodeProcessorResult::print_statistics, Slic3r::GCodeProcessorResult::SettingsIds::printer, reset(), Slic3r::GCodeProcessorResult::settings_ids, Slic3r::short_time(), Slic3r::PresetUtils::system_printer_bed_model(), Slic3r::PresetUtils::system_printer_bed_texture(), VolumetricRate, and Eigen::half_impl::__half_raw::x.
Referenced by Slic3r::GUI::GLCanvas3D::load_gcode_preview().
load_shells()
void Slic3r::GUI::GCodeViewer::load_shells (const Print & print) private
{
    if (print.objects().empty())
        // no shells, return
        return;
    // adds objects' volumes
    int object_id = 0;
    for (const PrintObject* obj : print.objects()) {
        const ModelObject* model_obj = obj->model_object();
        std::vector<int> instance_ids(model_obj->instances.size());
        for (int i = 0; i < (int)model_obj->instances.size(); ++i) {
            instance_ids[i] = i;
        }
        size_t current_volumes_count = m_shells.volumes.volumes.size();
        m_shells.volumes.load_object(model_obj, object_id, instance_ids);
        // adjust shells' z if raft is present
        const SlicingParameters& slicing_parameters = obj->slicing_parameters();
        if (slicing_parameters.object_print_z_min != 0.0) {
            const Vec3d z_offset = slicing_parameters.object_print_z_min * Vec3d::UnitZ();
            for (size_t i = current_volumes_count; i < m_shells.volumes.volumes.size(); ++i) {
                GLVolume* v = m_shells.volumes.volumes[i];
                v->set_volume_offset(v->get_volume_offset() + z_offset);
            }
        }
        ++object_id;
    }
    if (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptFFF) {
        // adds wipe tower's volume
        const double max_z = print.objects()[0]->model_object()->get_model()->max_z();
        const PrintConfig& config = print.config();
        const size_t extruders_count = config.nozzle_diameter.size();
        if (extruders_count > 1 && config.wipe_tower && !config.complete_objects) {
            const WipeTowerData& wipe_tower_data = print.wipe_tower_data(extruders_count);
            const float depth = wipe_tower_data.depth;
            const std::vector<std::pair<float, float>> z_and_depth_pairs = print.wipe_tower_data(extruders_count).z_and_depth_pairs;
            const float brim_width = wipe_tower_data.brim_width;
            if (depth != 0.)
                m_shells.volumes.load_wipe_tower_preview(config.wipe_tower_x, config.wipe_tower_y, config.wipe_tower_width, depth, z_and_depth_pairs, max_z, config.wipe_tower_cone_angle, config.wipe_tower_rotation_angle,
                    !print.is_step_done(psWipeTower), brim_width);
        }
    }
    // remove modifiers
    while (true) {
        GLVolumePtrs::iterator it = std::find_if(m_shells.volumes.volumes.begin(), m_shells.volumes.volumes.end(), [](GLVolume* volume) { return volume->is_modifier; });
        if (it != m_shells.volumes.volumes.end()) {
            delete (*it);
            m_shells.volumes.volumes.erase(it);
        }
        else
            break;
    }
    for (GLVolume* volume : m_shells.volumes.volumes) {
        volume->zoom_to_volumes = false;
        volume->color.a(0.25f);
        volume->force_native_color = true;
        volume->set_render_color(true);
    }
}
References Slic3r::WipeTowerData::brim_width, Slic3r::Print::config(), Slic3r::WipeTowerData::depth, Slic3r::GUI::extruders_count(), Slic3r::GLVolume::get_volume_offset(), Slic3r::ModelObject::instances, Slic3r::Print::is_step_done(), Slic3r::GLVolumeCollection::load_object(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), m_shells, Slic3r::SlicingParameters::object_print_z_min, Slic3r::Print::objects(), Slic3r::psWipeTower, Slic3r::ptFFF, Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolumeCollection::volumes, Slic3r::GUI::GCodeViewer::Shells::volumes, Slic3r::Print::wipe_tower_data(), and Slic3r::WipeTowerData::z_and_depth_pairs.
Referenced by load().
load_toolpaths()
void Slic3r::GUI::GCodeViewer::load_toolpaths (const GCodeProcessorResult & gcode_result) private
{
    // max index buffer size, in bytes
    static const size_t IBUFFER_THRESHOLD_BYTES = 64 * 1024 * 1024;
    auto log_memory_usage = [this](const std::string& label, const std::vector<MultiVertexBuffer>& vertices, const std::vector<MultiIndexBuffer>& indices) {
        int64_t vertices_size = 0;
        for (const MultiVertexBuffer& buffers : vertices) {
            for (const VertexBuffer& buffer : buffers) {
                vertices_size += SLIC3R_STDVEC_MEMSIZE(buffer, float);
            }
        }
        int64_t indices_size = 0;
        for (const MultiIndexBuffer& buffers : indices) {
            for (const IndexBuffer& buffer : buffers) {
                indices_size += SLIC3R_STDVEC_MEMSIZE(buffer, IBufferType);
            }
        }
        log_memory_used(label, vertices_size + indices_size);
    };
    // format data into the buffers to be rendered as lines
    auto add_vertices_as_line = [](const GCodeProcessorResult::MoveVertex& prev, const GCodeProcessorResult::MoveVertex& curr, VertexBuffer& vertices) {
        auto add_vertex = [&vertices](const GCodeProcessorResult::MoveVertex& vertex) {
            // add position
            vertices.push_back(vertex.position.x());
            vertices.push_back(vertex.position.y());
            vertices.push_back(vertex.position.z());
        };
        // add previous vertex
        add_vertex(prev);
        // add current vertex
        add_vertex(curr);
    };
    auto add_indices_as_line = [](const GCodeProcessorResult::MoveVertex& prev, const GCodeProcessorResult::MoveVertex& curr, TBuffer& buffer,
        unsigned int ibuffer_id, IndexBuffer& indices, size_t move_id, bool account_for_volumetric_rate) {
            if (buffer.paths.empty() || prev.type != curr.type || !buffer.paths.back().matches(curr, account_for_volumetric_rate)) {
                // add starting index
                indices.push_back(static_cast<IBufferType>(indices.size()));
                buffer.add_path(curr, ibuffer_id, indices.size() - 1, move_id - 1);
                buffer.paths.back().sub_paths.front().first.position = prev.position;
            }
            Path& last_path = buffer.paths.back();
            if (last_path.sub_paths.front().first.i_id != last_path.sub_paths.back().last.i_id) {
                // add previous index
                indices.push_back(static_cast<IBufferType>(indices.size()));
            }
            // add current index
            indices.push_back(static_cast<IBufferType>(indices.size()));
            last_path.sub_paths.back().last = { ibuffer_id, indices.size() - 1, move_id, curr.position };
    };
    // format data into the buffers to be rendered as solid
    auto add_vertices_as_solid = [](const GCodeProcessorResult::MoveVertex& prev, const GCodeProcessorResult::MoveVertex& curr, TBuffer& buffer,
        unsigned int vbuffer_id, VertexBuffer& vertices, size_t move_id, bool account_for_volumetric_rate) {
        auto store_vertex = [](VertexBuffer& vertices, const Vec3f& position, const Vec3f& normal) {
            // append position
            vertices.push_back(position.x());
            vertices.push_back(position.y());
            vertices.push_back(position.z());
            // append normal
            vertices.push_back(normal.x());
            vertices.push_back(normal.y());
            vertices.push_back(normal.z());
        };
        if (buffer.paths.empty() || prev.type != curr.type || !buffer.paths.back().matches(curr, account_for_volumetric_rate)) {
            buffer.add_path(curr, vbuffer_id, vertices.size(), move_id - 1);
            buffer.paths.back().sub_paths.back().first.position = prev.position;
        }
        Path& last_path = buffer.paths.back();
        const Vec3f dir = (curr.position - prev.position).normalized();
        const Vec3f right = Vec3f(dir.y(), -dir.x(), 0.0f).normalized();
        const Vec3f left = -right;
        const Vec3f up = right.cross(dir);
        const Vec3f down = -up;
        const float half_width = 0.5f * last_path.width;
        const float half_height = 0.5f * last_path.height;
        const Vec3f prev_pos = prev.position - half_height * up;
        const Vec3f curr_pos = curr.position - half_height * up;
        const Vec3f d_up = half_height * up;
        const Vec3f d_down = -half_height * up;
        const Vec3f d_right = half_width * right;
        const Vec3f d_left = -half_width * right;
        // vertices 1st endpoint
        if (last_path.vertices_count() == 1 || vertices.empty()) {
            // 1st segment or restart into a new vertex buffer
            // ===============================================
            store_vertex(vertices, prev_pos + d_up, up);
            store_vertex(vertices, prev_pos + d_right, right);
            store_vertex(vertices, prev_pos + d_down, down);
            store_vertex(vertices, prev_pos + d_left, left);
        }
        else {
            // any other segment
            // =================
            store_vertex(vertices, prev_pos + d_right, right);
            store_vertex(vertices, prev_pos + d_left, left);
        }
        // vertices 2nd endpoint
        store_vertex(vertices, curr_pos + d_up, up);
        store_vertex(vertices, curr_pos + d_right, right);
        store_vertex(vertices, curr_pos + d_down, down);
        store_vertex(vertices, curr_pos + d_left, left);
        last_path.sub_paths.back().last = { vbuffer_id, vertices.size(), move_id, curr.position };
    };
    auto add_indices_as_solid = [&](const GCodeProcessorResult::MoveVertex& prev, const GCodeProcessorResult::MoveVertex& curr,
        const GCodeProcessorResult::MoveVertex* next, TBuffer& buffer, size_t& vbuffer_size, unsigned int ibuffer_id,
        IndexBuffer& indices, size_t move_id, bool account_for_volumetric_rate) {
            static Vec3f prev_dir;
            static Vec3f prev_up;
            static float sq_prev_length;
            auto store_triangle = [](IndexBuffer& indices, IBufferType i1, IBufferType i2, IBufferType i3) {
                indices.push_back(i1);
                indices.push_back(i2);
                indices.push_back(i3);
            };
            auto append_dummy_cap = [store_triangle](IndexBuffer& indices, IBufferType id) {
                store_triangle(indices, id, id, id);
                store_triangle(indices, id, id, id);
            };
            auto convert_vertices_offset = [](size_t vbuffer_size, const std::array<int, 8>& v_offsets) {
                std::array<IBufferType, 8> ret = {
                    static_cast<IBufferType>(static_cast<int>(vbuffer_size) + v_offsets[0]),
                    static_cast<IBufferType>(static_cast<int>(vbuffer_size) + v_offsets[1]),
                    static_cast<IBufferType>(static_cast<int>(vbuffer_size) + v_offsets[2]),
                    static_cast<IBufferType>(static_cast<int>(vbuffer_size) + v_offsets[3]),
                    static_cast<IBufferType>(static_cast<int>(vbuffer_size) + v_offsets[4]),
                    static_cast<IBufferType>(static_cast<int>(vbuffer_size) + v_offsets[5]),
                    static_cast<IBufferType>(static_cast<int>(vbuffer_size) + v_offsets[6]),
                    static_cast<IBufferType>(static_cast<int>(vbuffer_size) + v_offsets[7])
                };
                return ret;
            };
            auto append_starting_cap_triangles = [&](IndexBuffer& indices, const std::array<IBufferType, 8>& v_offsets) {
                store_triangle(indices, v_offsets[0], v_offsets[2], v_offsets[1]);
                store_triangle(indices, v_offsets[0], v_offsets[3], v_offsets[2]);
            };
            auto append_stem_triangles = [&](IndexBuffer& indices, const std::array<IBufferType, 8>& v_offsets) {
                store_triangle(indices, v_offsets[0], v_offsets[1], v_offsets[4]);
                store_triangle(indices, v_offsets[1], v_offsets[5], v_offsets[4]);
                store_triangle(indices, v_offsets[1], v_offsets[2], v_offsets[5]);
                store_triangle(indices, v_offsets[2], v_offsets[6], v_offsets[5]);
                store_triangle(indices, v_offsets[2], v_offsets[3], v_offsets[6]);
                store_triangle(indices, v_offsets[3], v_offsets[7], v_offsets[6]);
                store_triangle(indices, v_offsets[3], v_offsets[0], v_offsets[7]);
                store_triangle(indices, v_offsets[0], v_offsets[4], v_offsets[7]);
            };
            auto append_ending_cap_triangles = [&](IndexBuffer& indices, const std::array<IBufferType, 8>& v_offsets) {
                store_triangle(indices, v_offsets[4], v_offsets[6], v_offsets[7]);
                store_triangle(indices, v_offsets[4], v_offsets[5], v_offsets[6]);
            };
            if (buffer.paths.empty() || prev.type != curr.type || !buffer.paths.back().matches(curr, account_for_volumetric_rate)) {
                buffer.add_path(curr, ibuffer_id, indices.size(), move_id - 1);
                buffer.paths.back().sub_paths.back().first.position = prev.position;
            }
            Path& last_path = buffer.paths.back();
            const Vec3f dir = (curr.position - prev.position).normalized();
            const Vec3f right = Vec3f(dir.y(), -dir.x(), 0.0f).normalized();
            const Vec3f up = right.cross(dir);
            const float sq_length = (curr.position - prev.position).squaredNorm();
            const std::array<IBufferType, 8> first_seg_v_offsets = convert_vertices_offset(vbuffer_size, { 0, 1, 2, 3, 4, 5, 6, 7 });
            const std::array<IBufferType, 8> non_first_seg_v_offsets = convert_vertices_offset(vbuffer_size, { -4, 0, -2, 1, 2, 3, 4, 5 });
            const bool is_first_segment = (last_path.vertices_count() == 1);
            if (is_first_segment || vbuffer_size == 0) {
                // 1st segment or restart into a new vertex buffer
                // ===============================================
                if (is_first_segment)
                    // starting cap triangles
                    append_starting_cap_triangles(indices, first_seg_v_offsets);
                // dummy triangles outer corner cap
                append_dummy_cap(indices, vbuffer_size);
                // stem triangles
                append_stem_triangles(indices, first_seg_v_offsets);
                vbuffer_size += 8;
            }
            else {
                // any other segment
                // =================
                float displacement = 0.0f;
                const float cos_dir = prev_dir.dot(dir);
                if (cos_dir > -0.9998477f) {
                    // if the angle between adjacent segments is smaller than 179 degrees
                    const Vec3f med_dir = (prev_dir + dir).normalized();
                    const float half_width = 0.5f * last_path.width;
                    displacement = half_width * ::tan(::acos(std::clamp(dir.dot(med_dir), -1.0f, 1.0f)));
                }
                const float sq_displacement = sqr(displacement);
                const bool can_displace = displacement > 0.0f && sq_displacement < sq_prev_length && sq_displacement < sq_length;
                const bool is_right_turn = prev_up.dot(prev_dir.cross(dir)) <= 0.0f;
                // whether the angle between adjacent segments is greater than 45 degrees
                const bool is_sharp = cos_dir < 0.7071068f;
                bool right_displaced = false;
                bool left_displaced = false;
                if (!is_sharp && can_displace) {
                    if (is_right_turn)
                        left_displaced = true;
                    else
                        right_displaced = true;
                }
                // triangles outer corner cap
                if (is_right_turn) {
                    if (left_displaced)
                        // dummy triangles
                        append_dummy_cap(indices, vbuffer_size);
                    else {
                        store_triangle(indices, vbuffer_size - 4, vbuffer_size + 1, vbuffer_size - 1);
                        store_triangle(indices, vbuffer_size + 1, vbuffer_size - 2, vbuffer_size - 1);
                    }
                }
                else {
                    if (right_displaced)
                        // dummy triangles
                        append_dummy_cap(indices, vbuffer_size);
                    else {
                        store_triangle(indices, vbuffer_size - 4, vbuffer_size - 3, vbuffer_size + 0);
                        store_triangle(indices, vbuffer_size - 3, vbuffer_size - 2, vbuffer_size + 0);
                    }
                }
                // stem triangles
                append_stem_triangles(indices, non_first_seg_v_offsets);
                vbuffer_size += 6;
            }
            if (next != nullptr && (curr.type != next->type || !last_path.matches(*next, account_for_volumetric_rate)))
                // ending cap triangles
                append_ending_cap_triangles(indices, is_first_segment ? first_seg_v_offsets : non_first_seg_v_offsets);
            last_path.sub_paths.back().last = { ibuffer_id, indices.size() - 1, move_id, curr.position };
            prev_dir = dir;
            prev_up = up;
            sq_prev_length = sq_length;
    };
    // format data into the buffers to be rendered as instanced model
    auto add_model_instance = [](const GCodeProcessorResult::MoveVertex& curr, InstanceBuffer& instances, InstanceIdBuffer& instances_ids, size_t move_id) {
        // append position
        instances.push_back(curr.position.x());
        instances.push_back(curr.position.y());
        instances.push_back(curr.position.z());
        // append width
        instances.push_back(curr.width);
        // append height
        instances.push_back(curr.height);
        // append id
        instances_ids.push_back(move_id);
    };
    // format data into the buffers to be rendered as batched model
    auto add_vertices_as_model_batch = [](const GCodeProcessorResult::MoveVertex& curr, const GLModel::Geometry& data, VertexBuffer& vertices, InstanceBuffer& instances, InstanceIdBuffer& instances_ids, size_t move_id) {
        const double width = static_cast<double>(1.5f * curr.width);
        const double height = static_cast<double>(1.5f * curr.height);
        const Transform3d trafo = Geometry::translation_transform((curr.position - 0.5f * curr.height * Vec3f::UnitZ()).cast<double>()) *
          Geometry::scale_transform({ width, width, height });
        const Eigen::Matrix<double, 3, 3, Eigen::DontAlign> normal_matrix = trafo.matrix().template block<3, 3>(0, 0).inverse().transpose();
        // append vertices
        const size_t vertices_count = data.vertices_count();
        for (size_t i = 0; i < vertices_count; ++i) {
            // append position
            const Vec3d position = trafo * data.extract_position_3(i).cast<double>();
            vertices.push_back(float(position.x()));
            vertices.push_back(float(position.y()));
            vertices.push_back(float(position.z()));
            // append normal
            const Vec3d normal = normal_matrix * data.extract_normal_3(i).cast<double>();
            vertices.push_back(float(normal.x()));
            vertices.push_back(float(normal.y()));
            vertices.push_back(float(normal.z()));
        }
        // append instance position
        instances.push_back(curr.position.x());
        instances.push_back(curr.position.y());
        instances.push_back(curr.position.z());
        // append instance id
        instances_ids.push_back(move_id);
    };
    auto add_indices_as_model_batch = [](const GLModel::Geometry& data, IndexBuffer& indices, IBufferType base_index) {
        const size_t indices_count = data.indices_count();
        for (size_t i = 0; i < indices_count; ++i) {
            indices.push_back(static_cast<IBufferType>(data.extract_index(i) + base_index));
        }
    };
#if ENABLE_GCODE_VIEWER_STATISTICS
    auto start_time = std::chrono::high_resolution_clock::now();
    m_statistics.results_size = SLIC3R_STDVEC_MEMSIZE(gcode_result.moves, GCodeProcessorResult::MoveVertex);
    m_statistics.results_time = gcode_result.time;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    m_moves_count = gcode_result.moves.size();
    if (m_moves_count == 0)
        return;
    m_extruders_count = gcode_result.extruders_count;
    unsigned int progress_count = 0;
    static const unsigned int progress_threshold = 1000;
    wxProgressDialog* progress_dialog = wxGetApp().is_gcode_viewer() ?
        new wxProgressDialog(_L("Generating toolpaths"), "...",
            100, wxGetApp().mainframe, wxPD_AUTO_HIDE | wxPD_APP_MODAL) : nullptr;
    wxBusyCursor busy;
    // extract approximate paths bounding box from result
    for (const GCodeProcessorResult::MoveVertex& move : gcode_result.moves) {
        if (wxGetApp().is_gcode_viewer())
            // for the gcode viewer we need to take in account all moves to correctly size the printbed
            m_paths_bounding_box.merge(move.position.cast<double>());
        else {
            if (move.type == EMoveType::Extrude && move.extrusion_role != GCodeExtrusionRole::Custom && move.width != 0.0f && move.height != 0.0f)
                m_paths_bounding_box.merge(move.position.cast<double>());
        }
    }
    // set approximate max bounding box (take in account also the tool marker)
    m_max_bounding_box = m_paths_bounding_box;
    m_max_bounding_box.merge(m_paths_bounding_box.max + m_sequential_view.marker.get_bounding_box().size().z() * Vec3d::UnitZ());
    if (wxGetApp().is_editor())
        m_contained_in_bed = wxGetApp().plater()->build_volume().all_paths_inside(gcode_result, m_paths_bounding_box);
    m_cog.reset();
    m_sequential_view.gcode_ids.clear();
    for (size_t i = 0; i < gcode_result.moves.size(); ++i) {
        const GCodeProcessorResult::MoveVertex& move = gcode_result.moves[i];
        if (move.type != EMoveType::Seam)
            m_sequential_view.gcode_ids.push_back(move.gcode_id);
    }
    bool account_for_volumetric_rate = m_view_type == EViewType::VolumetricRate;
    std::vector<MultiVertexBuffer> vertices(m_buffers.size());
    std::vector<MultiIndexBuffer> indices(m_buffers.size());
    std::vector<InstanceBuffer> instances(m_buffers.size());
    std::vector<InstanceIdBuffer> instances_ids(m_buffers.size());
    std::vector<InstancesOffsets> instances_offsets(m_buffers.size());
    std::vector<float> options_zs;
    std::vector<size_t> biased_seams_ids;
    // toolpaths data -> extract vertices from result
    for (size_t i = 0; i < m_moves_count; ++i) {
        const GCodeProcessorResult::MoveVertex& curr = gcode_result.moves[i];
        if (curr.type == EMoveType::Seam)
            biased_seams_ids.push_back(i - biased_seams_ids.size() - 1);
        const size_t move_id = i - biased_seams_ids.size();
        // skip first vertex
        if (i == 0)
            continue;
        const GCodeProcessorResult::MoveVertex& prev = gcode_result.moves[i - 1];
        if (curr.type == EMoveType::Extrude &&
            curr.extrusion_role != GCodeExtrusionRole::Skirt &&
            curr.extrusion_role != GCodeExtrusionRole::SupportMaterial &&
            curr.extrusion_role != GCodeExtrusionRole::SupportMaterialInterface &&
            curr.extrusion_role != GCodeExtrusionRole::WipeTower &&
            curr.extrusion_role != GCodeExtrusionRole::Custom) {
            const Vec3d curr_pos = curr.position.cast<double>();
            const Vec3d prev_pos = prev.position.cast<double>();
            m_cog.add_segment(curr_pos, prev_pos, curr.mm3_per_mm * (curr_pos - prev_pos).norm());
        }
        // update progress dialog
        ++progress_count;
        if (progress_dialog != nullptr && progress_count % progress_threshold == 0) {
            progress_dialog->Update(int(100.0f * float(i) / (2.0f * float(m_moves_count))),
                _L("Generating vertex buffer") + ": " + wxNumberFormatter::ToString(100.0 * double(i) / double(m_moves_count), 0, wxNumberFormatter::Style_None) + "%");
            progress_dialog->Fit();
            progress_count = 0;
        }
        const unsigned char id = buffer_id(curr.type);
        TBuffer& t_buffer = m_buffers[id];
        MultiVertexBuffer& v_multibuffer = vertices[id];
        InstanceBuffer& inst_buffer = instances[id];
        InstanceIdBuffer& inst_id_buffer = instances_ids[id];
        InstancesOffsets& inst_offsets = instances_offsets[id];
        // ensure there is at least one vertex buffer
        if (v_multibuffer.empty())
            v_multibuffer.push_back(VertexBuffer());
        // if adding the vertices for the current segment exceeds the threshold size of the current vertex buffer
        // add another vertex buffer
        size_t vertices_size_to_add = (t_buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::BatchedModel) ? t_buffer.model.data.vertices_size_bytes() : t_buffer.max_vertices_per_segment_size_bytes();
        if (v_multibuffer.back().size() * sizeof(float) > t_buffer.vertices.max_size_bytes() - vertices_size_to_add) {
            v_multibuffer.push_back(VertexBuffer());
            if (t_buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::Triangle) {
                Path& last_path = t_buffer.paths.back();
                if (prev.type == curr.type && last_path.matches(curr, account_for_volumetric_rate))
                    last_path.add_sub_path(prev, static_cast<unsigned int>(v_multibuffer.size()) - 1, 0, move_id - 1);
            }
        }
        VertexBuffer& v_buffer = v_multibuffer.back();
        switch (t_buffer.render_primitive_type)
        {
        case TBuffer::ERenderPrimitiveType::Line:     { add_vertices_as_line(prev, curr, v_buffer); break; }
        case TBuffer::ERenderPrimitiveType::Triangle: { add_vertices_as_solid(prev, curr, t_buffer, static_cast<unsigned int>(v_multibuffer.size()) - 1, v_buffer, move_id, account_for_volumetric_rate); break; }
        case TBuffer::ERenderPrimitiveType::InstancedModel:
        {
            add_model_instance(curr, inst_buffer, inst_id_buffer, move_id);
            inst_offsets.push_back(prev.position - curr.position);
#if ENABLE_GCODE_VIEWER_STATISTICS
            ++m_statistics.instances_count;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
            break;
        }
        case TBuffer::ERenderPrimitiveType::BatchedModel:
        {
            add_vertices_as_model_batch(curr, t_buffer.model.data, v_buffer, inst_buffer, inst_id_buffer, move_id);
            inst_offsets.push_back(prev.position - curr.position);
#if ENABLE_GCODE_VIEWER_STATISTICS
            ++m_statistics.batched_count;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
            break;
        }
        }
        // collect options zs for later use
        if (curr.type == EMoveType::Pause_Print || curr.type == EMoveType::Custom_GCode) {
            const float* const last_z = options_zs.empty() ? nullptr : &options_zs.back();
            if (last_z == nullptr || curr.position[2] < *last_z - EPSILON || *last_z + EPSILON < curr.position[2])
                options_zs.emplace_back(curr.position[2]);
        }
    }
    // smooth toolpaths corners for the given TBuffer using triangles
    auto smooth_triangle_toolpaths_corners = [&gcode_result, &biased_seams_ids](const TBuffer& t_buffer, MultiVertexBuffer& v_multibuffer) {
        auto extract_position_at = [](const VertexBuffer& vertices, size_t offset) {
            return Vec3f(vertices[offset + 0], vertices[offset + 1], vertices[offset + 2]);
        };
        auto update_position_at = [](VertexBuffer& vertices, size_t offset, const Vec3f& position) {
            vertices[offset + 0] = position.x();
            vertices[offset + 1] = position.y();
            vertices[offset + 2] = position.z();
        };
        auto match_right_vertices = [&](const Path::Sub_Path& prev_sub_path, const Path::Sub_Path& next_sub_path,
            size_t curr_s_id, size_t vertex_size_floats, const Vec3f& displacement_vec) {
                if (&prev_sub_path == &next_sub_path) { // previous and next segment are both contained into to the same vertex buffer
                    VertexBuffer& vbuffer = v_multibuffer[prev_sub_path.first.b_id];
                    // offset into the vertex buffer of the next segment 1st vertex
                    const size_t next_1st_offset = (prev_sub_path.last.s_id - curr_s_id) * 6 * vertex_size_floats;
                    // offset into the vertex buffer of the right vertex of the previous segment
                    const size_t prev_right_offset = prev_sub_path.last.i_id - next_1st_offset - 3 * vertex_size_floats;
                    // new position of the right vertices
                    const Vec3f shared_vertex = extract_position_at(vbuffer, prev_right_offset) + displacement_vec;
                    // update previous segment
                    update_position_at(vbuffer, prev_right_offset, shared_vertex);
                    // offset into the vertex buffer of the right vertex of the next segment
                    const size_t next_right_offset = next_sub_path.last.i_id - next_1st_offset;
                    // update next segment
                    update_position_at(vbuffer, next_right_offset, shared_vertex);
                }
                else { // previous and next segment are contained into different vertex buffers
                    VertexBuffer& prev_vbuffer = v_multibuffer[prev_sub_path.first.b_id];
                    VertexBuffer& next_vbuffer = v_multibuffer[next_sub_path.first.b_id];
                    // offset into the previous vertex buffer of the right vertex of the previous segment
                    const size_t prev_right_offset = prev_sub_path.last.i_id - 3 * vertex_size_floats;
                    // new position of the right vertices
                    const Vec3f shared_vertex = extract_position_at(prev_vbuffer, prev_right_offset) + displacement_vec;
                    // update previous segment
                    update_position_at(prev_vbuffer, prev_right_offset, shared_vertex);
                    // offset into the next vertex buffer of the right vertex of the next segment
                    const size_t next_right_offset = next_sub_path.first.i_id + 1 * vertex_size_floats;
                    // update next segment
                    update_position_at(next_vbuffer, next_right_offset, shared_vertex);
                }
        };
        auto match_left_vertices = [&](const Path::Sub_Path& prev_sub_path, const Path::Sub_Path& next_sub_path,
            size_t curr_s_id, size_t vertex_size_floats, const Vec3f& displacement_vec) {
                if (&prev_sub_path == &next_sub_path) { // previous and next segment are both contained into to the same vertex buffer
                    VertexBuffer& vbuffer = v_multibuffer[prev_sub_path.first.b_id];
                    // offset into the vertex buffer of the next segment 1st vertex
                    const size_t next_1st_offset = (prev_sub_path.last.s_id - curr_s_id) * 6 * vertex_size_floats;
                    // offset into the vertex buffer of the left vertex of the previous segment
                    const size_t prev_left_offset = prev_sub_path.last.i_id - next_1st_offset - 1 * vertex_size_floats;
                    // new position of the left vertices
                    const Vec3f shared_vertex = extract_position_at(vbuffer, prev_left_offset) + displacement_vec;
                    // update previous segment
                    update_position_at(vbuffer, prev_left_offset, shared_vertex);
                    // offset into the vertex buffer of the left vertex of the next segment
                    const size_t next_left_offset = next_sub_path.last.i_id - next_1st_offset + 1 * vertex_size_floats;
                    // update next segment
                    update_position_at(vbuffer, next_left_offset, shared_vertex);
                }
                else { // previous and next segment are contained into different vertex buffers
                    VertexBuffer& prev_vbuffer = v_multibuffer[prev_sub_path.first.b_id];
                    VertexBuffer& next_vbuffer = v_multibuffer[next_sub_path.first.b_id];
                    // offset into the previous vertex buffer of the left vertex of the previous segment
                    const size_t prev_left_offset = prev_sub_path.last.i_id - 1 * vertex_size_floats;
                    // new position of the left vertices
                    const Vec3f shared_vertex = extract_position_at(prev_vbuffer, prev_left_offset) + displacement_vec;
                    // update previous segment
                    update_position_at(prev_vbuffer, prev_left_offset, shared_vertex);
                    // offset into the next vertex buffer of the left vertex of the next segment
                    const size_t next_left_offset = next_sub_path.first.i_id + 3 * vertex_size_floats;
                    // update next segment
                    update_position_at(next_vbuffer, next_left_offset, shared_vertex);
                }
        };
        auto extract_move_id = [&biased_seams_ids](size_t id) {
            size_t new_id = size_t(-1);
            auto it = std::lower_bound(biased_seams_ids.begin(), biased_seams_ids.end(), id);
            if (it == biased_seams_ids.end())
                new_id = id + biased_seams_ids.size();
            else {
                if (it == biased_seams_ids.begin() && *it < id)
                    new_id = id;
                else if (it != biased_seams_ids.begin())
                    new_id = id + std::distance(biased_seams_ids.begin(), it);
            }
            return (new_id == size_t(-1)) ? id : new_id;
        };
        const size_t vertex_size_floats = t_buffer.vertices.vertex_size_floats();
        for (const Path& path : t_buffer.paths) {
            // the two segments of the path sharing the current vertex may belong
            // to two different vertex buffers
            size_t prev_sub_path_id = 0;
            size_t next_sub_path_id = 0;
            const size_t path_vertices_count = path.vertices_count();
            const float half_width = 0.5f * path.width;
            for (size_t j = 1; j < path_vertices_count - 1; ++j) {
                const size_t curr_s_id = path.sub_paths.front().first.s_id + j;
                const size_t move_id = extract_move_id(curr_s_id);
                const Vec3f& prev = gcode_result.moves[move_id - 1].position;
                const Vec3f& curr = gcode_result.moves[move_id].position;
                const Vec3f& next = gcode_result.moves[move_id + 1].position;
                // select the subpaths which contains the previous/next segments
                if (!path.sub_paths[prev_sub_path_id].contains(curr_s_id))
                    ++prev_sub_path_id;
                if (!path.sub_paths[next_sub_path_id].contains(curr_s_id + 1))
                    ++next_sub_path_id;
                const Path::Sub_Path& prev_sub_path = path.sub_paths[prev_sub_path_id];
                const Path::Sub_Path& next_sub_path = path.sub_paths[next_sub_path_id];
                const Vec3f prev_dir = (curr - prev).normalized();
                const Vec3f prev_right = Vec3f(prev_dir.y(), -prev_dir.x(), 0.0f).normalized();
                const Vec3f prev_up = prev_right.cross(prev_dir);
                const Vec3f next_dir = (next - curr).normalized();
                const bool is_right_turn = prev_up.dot(prev_dir.cross(next_dir)) <= 0.0f;
                const float cos_dir = prev_dir.dot(next_dir);
                // whether the angle between adjacent segments is greater than 45 degrees
                const bool is_sharp = cos_dir < 0.7071068f;
                float displacement = 0.0f;
                if (cos_dir > -0.9998477f) {
                    // if the angle between adjacent segments is smaller than 179 degrees
                    const Vec3f med_dir = (prev_dir + next_dir).normalized();
                    displacement = half_width * ::tan(::acos(std::clamp(next_dir.dot(med_dir), -1.0f, 1.0f)));
                }
                const float sq_prev_length = (curr - prev).squaredNorm();
                const float sq_next_length = (next - curr).squaredNorm();
                const float sq_displacement = sqr(displacement);
                const bool can_displace = displacement > 0.0f && sq_displacement < sq_prev_length && sq_displacement < sq_next_length;
                if (can_displace) {
                    // displacement to apply to the vertices to match
                    const Vec3f displacement_vec = displacement * prev_dir;
                    // matches inner corner vertices
                    if (is_right_turn)
                        match_right_vertices(prev_sub_path, next_sub_path, curr_s_id, vertex_size_floats, -displacement_vec);
                    else
                        match_left_vertices(prev_sub_path, next_sub_path, curr_s_id, vertex_size_floats, -displacement_vec);
                    if (!is_sharp) {
                        // matches outer corner vertices
                        if (is_right_turn)
                            match_left_vertices(prev_sub_path, next_sub_path, curr_s_id, vertex_size_floats, displacement_vec);
                        else
                            match_right_vertices(prev_sub_path, next_sub_path, curr_s_id, vertex_size_floats, displacement_vec);
                    }
                }
            }
        }
    };
#if ENABLE_GCODE_VIEWER_STATISTICS
    auto load_vertices_time = std::chrono::high_resolution_clock::now();
    m_statistics.load_vertices = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - start_time).count();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    // smooth toolpaths corners for TBuffers using triangles
    for (size_t i = 0; i < m_buffers.size(); ++i) {
        const TBuffer& t_buffer = m_buffers[i];
        if (t_buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::Triangle)
            smooth_triangle_toolpaths_corners(t_buffer, vertices[i]);
    }
    // dismiss, no more needed
    std::vector<size_t>().swap(biased_seams_ids);
    for (MultiVertexBuffer& v_multibuffer : vertices) {
        for (VertexBuffer& v_buffer : v_multibuffer) {
            v_buffer.shrink_to_fit();
        }
    }
    // move the wipe toolpaths half height up to render them on proper position
    MultiVertexBuffer& wipe_vertices = vertices[buffer_id(EMoveType::Wipe)];
    for (VertexBuffer& v_buffer : wipe_vertices) {
        for (size_t i = 2; i < v_buffer.size(); i += 3) {
            v_buffer[i] += 0.5f * GCodeProcessor::Wipe_Height;
        }
    }
    // send vertices data to gpu, where needed
    for (size_t i = 0; i < m_buffers.size(); ++i) {
        TBuffer& t_buffer = m_buffers[i];
        if (t_buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::InstancedModel) {
            const InstanceBuffer& inst_buffer = instances[i];
            if (!inst_buffer.empty()) {
                t_buffer.model.instances.buffer = inst_buffer;
                t_buffer.model.instances.s_ids = instances_ids[i];
                t_buffer.model.instances.offsets = instances_offsets[i];
            }
        }
        else {
            if (t_buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::BatchedModel) {
                const InstanceBuffer& inst_buffer = instances[i];
                if (!inst_buffer.empty()) {
                    t_buffer.model.instances.buffer = inst_buffer;
                    t_buffer.model.instances.s_ids = instances_ids[i];
                    t_buffer.model.instances.offsets = instances_offsets[i];
                }
            }
            const MultiVertexBuffer& v_multibuffer = vertices[i];
            for (const VertexBuffer& v_buffer : v_multibuffer) {
                const size_t size_elements = v_buffer.size();
                const size_t size_bytes = size_elements * sizeof(float);
                const size_t vertices_count = size_elements / t_buffer.vertices.vertex_size_floats();
                t_buffer.vertices.count += vertices_count;
#if ENABLE_GCODE_VIEWER_STATISTICS
                m_statistics.total_vertices_gpu_size += static_cast<int64_t>(size_bytes);
                m_statistics.max_vbuffer_gpu_size = std::max(m_statistics.max_vbuffer_gpu_size, static_cast<int64_t>(size_bytes));
                ++m_statistics.vbuffers_count;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
#if ENABLE_GL_CORE_PROFILE
                GLuint vao_id = 0;
                if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0)) {
                    glsafe(::glGenVertexArrays(1, &vao_id));
                    glsafe(::glBindVertexArray(vao_id));
                }
#endif // ENABLE_GL_CORE_PROFILE
                GLuint vbo_id = 0;
                glsafe(::glGenBuffers(1, &vbo_id));
                glsafe(::glBindBuffer(GL_ARRAY_BUFFER, vbo_id));
                glsafe(::glBufferData(GL_ARRAY_BUFFER, size_bytes, v_buffer.data(), GL_STATIC_DRAW));
                glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
#if ENABLE_GL_CORE_PROFILE
                if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0)) {
                    glsafe(::glBindVertexArray(0));
                    t_buffer.vertices.vaos.push_back(static_cast<unsigned int>(vao_id));
                }
#endif // ENABLE_GL_CORE_PROFILE
                t_buffer.vertices.vbos.push_back(static_cast<unsigned int>(vbo_id));
                t_buffer.vertices.sizes.push_back(size_bytes);
            }
        }
    }
#if ENABLE_GCODE_VIEWER_STATISTICS
    auto smooth_vertices_time = std::chrono::high_resolution_clock::now();
    m_statistics.smooth_vertices = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - load_vertices_time).count();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    log_memory_usage("Loaded G-code generated vertex buffers ", vertices, indices);
    // dismiss vertices data, no more needed
    std::vector<MultiVertexBuffer>().swap(vertices);
    std::vector<InstanceBuffer>().swap(instances);
    std::vector<InstanceIdBuffer>().swap(instances_ids);
    // toolpaths data -> extract indices from result
    // paths may have been filled while extracting vertices,
    // so reset them, they will be filled again while extracting indices
    for (TBuffer& buffer : m_buffers) {
        buffer.paths.clear();
    }
    // variable used to keep track of the current vertex buffers index and size
    using CurrVertexBuffer = std::pair<unsigned int, size_t>;
    std::vector<CurrVertexBuffer> curr_vertex_buffers(m_buffers.size(), { 0, 0 });
#if ENABLE_GL_CORE_PROFILE
    // variable used to keep track of the vertex buffers ids
    using VIndexList = std::vector<unsigned int>;
    std::vector<VIndexList> vao_indices(m_buffers.size());
    std::vector<VIndexList> vbo_indices(m_buffers.size());
#else
    // variable used to keep track of the vertex buffers ids
    using VboIndexList = std::vector<unsigned int>;
    std::vector<VboIndexList> vbo_indices(m_buffers.size());
#endif // ENABLE_GL_CORE_PROFILE
    size_t seams_count = 0;
    for (size_t i = 0; i < m_moves_count; ++i) {
        const GCodeProcessorResult::MoveVertex& curr = gcode_result.moves[i];
        if (curr.type == EMoveType::Seam)
            ++seams_count;
        const size_t move_id = i - seams_count;
        // skip first vertex
        if (i == 0)
            continue;
        const GCodeProcessorResult::MoveVertex& prev = gcode_result.moves[i - 1];
        const GCodeProcessorResult::MoveVertex* next = nullptr;
        if (i < m_moves_count - 1)
            next = &gcode_result.moves[i + 1];
        ++progress_count;
        if (progress_dialog != nullptr && progress_count % progress_threshold == 0) {
            progress_dialog->Update(int(100.0f * float(m_moves_count + i) / (2.0f * float(m_moves_count))),
                _L("Generating index buffers") + ": " + wxNumberFormatter::ToString(100.0 * double(i) / double(m_moves_count), 0, wxNumberFormatter::Style_None) + "%");
            progress_dialog->Fit();
            progress_count = 0;
        }
        const unsigned char id = buffer_id(curr.type);
        TBuffer& t_buffer = m_buffers[id];
        MultiIndexBuffer& i_multibuffer = indices[id];
        CurrVertexBuffer& curr_vertex_buffer = curr_vertex_buffers[id];
#if ENABLE_GL_CORE_PROFILE
        VIndexList& vao_index_list = vao_indices[id];
        VIndexList& vbo_index_list = vbo_indices[id];
#else
        VboIndexList& vbo_index_list = vbo_indices[id];
#endif // ENABLE_GL_CORE_PROFILE
        // ensure there is at least one index buffer
        if (i_multibuffer.empty()) {
            i_multibuffer.push_back(IndexBuffer());
#if ENABLE_GL_CORE_PROFILE
            if (!t_buffer.vertices.vaos.empty() && OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                vao_index_list.push_back(t_buffer.vertices.vaos[curr_vertex_buffer.first]);
            if (!t_buffer.vertices.vbos.empty())
                vbo_index_list.push_back(t_buffer.vertices.vbos[curr_vertex_buffer.first]);
#else
            if (!t_buffer.vertices.vbos.empty())
                vbo_index_list.push_back(t_buffer.vertices.vbos[curr_vertex_buffer.first]);
#endif // ENABLE_GL_CORE_PROFILE
        }
        // if adding the indices for the current segment exceeds the threshold size of the current index buffer
        // create another index buffer
        size_t indiced_size_to_add = (t_buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::BatchedModel) ? t_buffer.model.data.indices_size_bytes() : t_buffer.max_indices_per_segment_size_bytes();
        if (i_multibuffer.back().size() * sizeof(IBufferType) >= IBUFFER_THRESHOLD_BYTES - indiced_size_to_add) {
            i_multibuffer.push_back(IndexBuffer());
#if ENABLE_GL_CORE_PROFILE
            if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                vao_index_list.push_back(t_buffer.vertices.vaos[curr_vertex_buffer.first]);
#endif // ENABLE_GL_CORE_PROFILE
            vbo_index_list.push_back(t_buffer.vertices.vbos[curr_vertex_buffer.first]);
            if (t_buffer.render_primitive_type != TBuffer::ERenderPrimitiveType::BatchedModel) {
                Path& last_path = t_buffer.paths.back();
                last_path.add_sub_path(prev, static_cast<unsigned int>(i_multibuffer.size()) - 1, 0, move_id - 1);
            }
        }
        // if adding the vertices for the current segment exceeds the threshold size of the current vertex buffer
        // create another index buffer
        size_t vertices_size_to_add = (t_buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::BatchedModel) ? t_buffer.model.data.vertices_size_bytes() : t_buffer.max_vertices_per_segment_size_bytes();
        if (curr_vertex_buffer.second * t_buffer.vertices.vertex_size_bytes() > t_buffer.vertices.max_size_bytes() - vertices_size_to_add) {
            i_multibuffer.push_back(IndexBuffer());
            ++curr_vertex_buffer.first;
            curr_vertex_buffer.second = 0;
#if ENABLE_GL_CORE_PROFILE
            if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                vao_index_list.push_back(t_buffer.vertices.vaos[curr_vertex_buffer.first]);
#endif // ENABLE_GL_CORE_PROFILE
            vbo_index_list.push_back(t_buffer.vertices.vbos[curr_vertex_buffer.first]);
            if (t_buffer.render_primitive_type != TBuffer::ERenderPrimitiveType::BatchedModel) {
                Path& last_path = t_buffer.paths.back();
                last_path.add_sub_path(prev, static_cast<unsigned int>(i_multibuffer.size()) - 1, 0, move_id - 1);
            }
        }
        IndexBuffer& i_buffer = i_multibuffer.back();
        switch (t_buffer.render_primitive_type)
        {
        case TBuffer::ERenderPrimitiveType::Line: {
            add_indices_as_line(prev, curr, t_buffer, static_cast<unsigned int>(i_multibuffer.size()) - 1, i_buffer, move_id, account_for_volumetric_rate);
            curr_vertex_buffer.second += t_buffer.max_vertices_per_segment();
            break;
        }
        case TBuffer::ERenderPrimitiveType::Triangle: {
            add_indices_as_solid(prev, curr, next, t_buffer, curr_vertex_buffer.second, static_cast<unsigned int>(i_multibuffer.size()) - 1, i_buffer, move_id, account_for_volumetric_rate);
            break;
        }
        case TBuffer::ERenderPrimitiveType::BatchedModel: {
            add_indices_as_model_batch(t_buffer.model.data, i_buffer, curr_vertex_buffer.second);
            curr_vertex_buffer.second += t_buffer.model.data.vertices_count();
            break;
        }
        default: { break; }
        }
    }
    for (MultiIndexBuffer& i_multibuffer : indices) {
        for (IndexBuffer& i_buffer : i_multibuffer) {
            i_buffer.shrink_to_fit();
        }
    }
    // toolpaths data -> send indices data to gpu
    for (size_t i = 0; i < m_buffers.size(); ++i) {
        TBuffer& t_buffer = m_buffers[i];
        if (t_buffer.render_primitive_type != TBuffer::ERenderPrimitiveType::InstancedModel) {
            const MultiIndexBuffer& i_multibuffer = indices[i];
            for (const IndexBuffer& i_buffer : i_multibuffer) {
                const size_t size_elements = i_buffer.size();
                const size_t size_bytes = size_elements * sizeof(IBufferType);
                // stores index buffer informations into TBuffer
                t_buffer.indices.push_back(IBuffer());
                IBuffer& ibuf = t_buffer.indices.back();
                ibuf.count = size_elements;
#if ENABLE_GL_CORE_PROFILE
                if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                    ibuf.vao = vao_indices[i][t_buffer.indices.size() - 1];
#endif // ENABLE_GL_CORE_PROFILE
                ibuf.vbo = vbo_indices[i][t_buffer.indices.size() - 1];
#if ENABLE_GCODE_VIEWER_STATISTICS
                m_statistics.total_indices_gpu_size += static_cast<int64_t>(size_bytes);
                m_statistics.max_ibuffer_gpu_size = std::max(m_statistics.max_ibuffer_gpu_size, static_cast<int64_t>(size_bytes));
                ++m_statistics.ibuffers_count;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
                glsafe(::glGenBuffers(1, &ibuf.ibo));
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ibuf.ibo));
                glsafe(::glBufferData(GL_ELEMENT_ARRAY_BUFFER, size_bytes, i_buffer.data(), GL_STATIC_DRAW));
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
            }
        }
    }
    if (progress_dialog != nullptr) {
        progress_dialog->Update(100, "");
        progress_dialog->Fit();
    }
#if ENABLE_GCODE_VIEWER_STATISTICS
    for (const TBuffer& buffer : m_buffers) {
        m_statistics.paths_size += SLIC3R_STDVEC_MEMSIZE(buffer.paths, Path);
    }
    auto update_segments_count = [&](EMoveType type, int64_t& count) {
        unsigned int id = buffer_id(type);
        const MultiIndexBuffer& buffers = indices[id];
        int64_t indices_count = 0;
        for (const IndexBuffer& buffer : buffers) {
            indices_count += buffer.size();
        }
        const TBuffer& t_buffer = m_buffers[id];
        if (t_buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::Triangle)
            indices_count -= static_cast<int64_t>(12 * t_buffer.paths.size()); // remove the starting + ending caps = 4 triangles
        count += indices_count / t_buffer.indices_per_segment();
    };
    update_segments_count(EMoveType::Travel, m_statistics.travel_segments_count);
    update_segments_count(EMoveType::Wipe, m_statistics.wipe_segments_count);
    update_segments_count(EMoveType::Extrude, m_statistics.extrude_segments_count);
    m_statistics.load_indices = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - smooth_vertices_time).count();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    log_memory_usage("Loaded G-code generated indices buffers ", vertices, indices);
    // dismiss indices data, no more needed
    std::vector<MultiIndexBuffer>().swap(indices);
    // layers zs / roles / extruder ids -> extract from result
    size_t last_travel_s_id = 0;
    size_t first_travel_s_id = 0;
    seams_count = 0;
    for (size_t i = 0; i < m_moves_count; ++i) {
        const GCodeProcessorResult::MoveVertex& move = gcode_result.moves[i];
        if (move.type == EMoveType::Seam)
            ++seams_count;
        size_t move_id = i - seams_count;
        if (move.type == EMoveType::Extrude) {
            if (!move.internal_only) {
                // layers zs
                const double* const last_z = m_layers.empty() ? nullptr : &m_layers.get_zs().back();
                const double z = static_cast<double>(move.position.z());
                if (last_z == nullptr || z < *last_z - EPSILON || *last_z + EPSILON < z) {
                    const size_t start_it = (m_layers.empty() && first_travel_s_id != 0) ? first_travel_s_id : last_travel_s_id;
                    m_layers.append(z, { start_it, move_id });
                }
                else
                    m_layers.get_ranges().back().last = move_id;
            }
            // extruder ids
            m_extruder_ids.emplace_back(move.extruder_id);
            // roles
            if (i > 0)
                m_roles.emplace_back(move.extrusion_role);
        }
        else if (move.type == EMoveType::Travel) {
            if (move_id - last_travel_s_id > 1 && !m_layers.empty())
                m_layers.get_ranges().back().last = move_id;
            else if (m_layers.empty() && first_travel_s_id == 0)
                first_travel_s_id = move_id;
            last_travel_s_id = move_id;
        }
    }
    // roles -> remove duplicates
    sort_remove_duplicates(m_roles);
    m_roles.shrink_to_fit();
    // extruder ids -> remove duplicates
    sort_remove_duplicates(m_extruder_ids);
    m_extruder_ids.shrink_to_fit();
    // replace layers for spiral vase mode
    if (!gcode_result.spiral_vase_layers.empty()) {
        m_layers.reset();
        for (const auto& layer : gcode_result.spiral_vase_layers) {
            m_layers.append(layer.first, { layer.second.first, layer.second.second });
        }
    }
    // set layers z range
    if (!m_layers.empty())
        m_layers_z_range = { 0, static_cast<unsigned int>(m_layers.size() - 1) };
    // change color of paths whose layer contains option points
    if (!options_zs.empty()) {
        TBuffer& extrude_buffer = m_buffers[buffer_id(EMoveType::Extrude)];
        for (Path& path : extrude_buffer.paths) {
            const float z = path.sub_paths.front().first.position.z();
            if (std::find_if(options_zs.begin(), options_zs.end(), [z](float f) { return f - EPSILON <= z && z <= f + EPSILON; }) != options_zs.end())
                path.cp_color_id = 255 - path.cp_color_id;
        }
    }
#if ENABLE_GCODE_VIEWER_STATISTICS
    m_statistics.load_time = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - start_time).count();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    if (progress_dialog != nullptr)
        progress_dialog->Destroy();
}
References _L, acos(), Slic3r::GUI::GCodeViewer::COG::add_segment(), Slic3r::GUI::GCodeViewer::Path::add_sub_path(), Slic3r::GUI::GCodeViewer::Layers::append(), Slic3r::GUI::GCodeViewer::Path::Endpoint::b_id, Slic3r::GUI::GCodeViewer::TBuffer::BatchedModel, Slic3r::GUI::GCodeViewer::InstanceVBuffer::buffer, Slic3r::GUI::buffer_id(), Slic3r::GUI::GCodeViewer::VBuffer::count, Slic3r::GUI::GCodeViewer::IBuffer::count, Slic3r::Custom, Slic3r::Custom_GCode, Slic3r::GUI::GCodeViewer::TBuffer::Model::data, Slic3r::GUI::GCodeViewer::Layers::empty(), EPSILON, Slic3r::Extrude, Slic3r::GCodeProcessorResult::MoveVertex::extruder_id, Slic3r::GCodeProcessorResult::extruders_count, Slic3r::GCodeProcessorResult::MoveVertex::extrusion_role, Slic3r::GUI::GCodeViewer::Path::Sub_Path::first, Slic3r::GCodeProcessorResult::MoveVertex::gcode_id, Slic3r::GUI::GCodeViewer::SequentialView::gcode_ids, Slic3r::GUI::GCodeViewer::SequentialView::Marker::get_bounding_box(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::GCodeViewer::Layers::get_ranges(), Slic3r::GUI::GCodeViewer::Layers::get_zs(), glsafe, Slic3r::GUI::GCodeViewer::Path::height, Slic3r::GUI::GCodeViewer::Path::Endpoint::i_id, Slic3r::GUI::GCodeViewer::IBuffer::ibo, Slic3r::GUI::GCodeViewer::TBuffer::indices, Slic3r::GUI::GCodeViewer::TBuffer::indices_per_segment(), Slic3r::GUI::GLModel::Geometry::indices_size_bytes(), Slic3r::GUI::GCodeViewer::TBuffer::InstancedModel, Slic3r::GUI::GCodeViewer::TBuffer::Model::instances, Slic3r::GCodeProcessorResult::MoveVertex::internal_only, Slic3r::GUI::OpenGLManager::GLInfo::is_version_greater_or_equal_to(), Slic3r::GUI::GCodeViewer::Path::Sub_Path::last, Slic3r::GUI::GCodeViewer::TBuffer::Line, log_memory_used(), m_buffers, m_cog, m_contained_in_bed, m_extruder_ids, m_extruders_count, m_layers, m_max_bounding_box, m_moves_count, m_paths_bounding_box, m_roles, m_sequential_view, m_view_type, Slic3r::GUI::GCodeViewer::SequentialView::marker, Slic3r::GUI::GCodeViewer::Path::matches(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::GUI::GCodeViewer::TBuffer::max_indices_per_segment_size_bytes(), Slic3r::GUI::GCodeViewer::VBuffer::max_size_bytes(), Slic3r::GUI::GCodeViewer::TBuffer::max_vertices_per_segment(), Slic3r::GUI::GCodeViewer::TBuffer::max_vertices_per_segment_size_bytes(), Slic3r::BoundingBox3Base< PointType >::merge(), Slic3r::GCodeProcessorResult::MoveVertex::mm3_per_mm, Slic3r::GUI::GCodeViewer::TBuffer::model, Slic3r::GCodeProcessorResult::moves, Slic3r::offset(), Slic3r::GUI::GCodeViewer::InstanceVBuffer::offsets, Slic3r::GUI::GCodeViewer::TBuffer::paths, Slic3r::Pause_Print, Slic3r::GCodeProcessorResult::MoveVertex::position, Slic3r::GUI::GCodeViewer::TBuffer::render_primitive_type, Slic3r::GUI::GCodeViewer::COG::reset(), Slic3r::GUI::GCodeViewer::Layers::reset(), Slic3r::GUI::GCodeViewer::Path::Endpoint::s_id, Slic3r::GUI::GCodeViewer::InstanceVBuffer::s_ids, Slic3r::Geometry::scale_transform(), Slic3r::Seam, Slic3r::BoundingBox3Base< PointType >::size(), Slic3r::GUI::GCodeViewer::VBuffer::sizes, Slic3r::Skirt, SLIC3R_STDVEC_MEMSIZE, Slic3r::sort_remove_duplicates(), Slic3r::GCodeProcessorResult::spiral_vase_layers, Slic3r::sqr(), Slic3r::GUI::GCodeViewer::Path::sub_paths, Slic3r::SupportMaterial, Slic3r::SupportMaterialInterface, tan(), Slic3r::Geometry::translation_transform(), Slic3r::Travel, Slic3r::GUI::GCodeViewer::TBuffer::Triangle, Slic3r::GCodeProcessorResult::MoveVertex::type, Slic3r::GUI::GCodeViewer::IBuffer::vbo, Slic3r::GUI::GCodeViewer::VBuffer::vbos, Slic3r::GUI::GCodeViewer::VBuffer::vertex_size_bytes(), Slic3r::GUI::GCodeViewer::VBuffer::vertex_size_floats(), Slic3r::GUI::GCodeViewer::TBuffer::vertices, Slic3r::GUI::GCodeViewer::Path::vertices_count(), Slic3r::GUI::GLModel::Geometry::vertices_count(), Slic3r::GUI::GLModel::Geometry::vertices_size_bytes(), VolumetricRate, Slic3r::GUI::GCodeViewer::Path::width, Slic3r::Wipe, Slic3r::GCodeProcessor::Wipe_Height, and Slic3r::WipeTower.
Referenced by load().
log_memory_used()
void Slic3r::GUI::GCodeViewer::log_memory_used (const std::string & label, int64_t additional = 0) const private
{
    if (Slic3r::get_logging_level() >= 5) {
        int64_t paths_size = 0;
        int64_t render_paths_size = 0;
        for (const TBuffer& buffer : m_buffers) {
            paths_size += SLIC3R_STDVEC_MEMSIZE(buffer.paths, Path);
            render_paths_size += SLIC3R_STDUNORDEREDSET_MEMSIZE(buffer.render_paths, RenderPath);
            for (const RenderPath& path : buffer.render_paths) {
                render_paths_size += SLIC3R_STDVEC_MEMSIZE(path.sizes, unsigned int);
                render_paths_size += SLIC3R_STDVEC_MEMSIZE(path.offsets, size_t);
            }
        }
        int64_t layers_size = SLIC3R_STDVEC_MEMSIZE(m_layers.get_zs(), double);
        layers_size += SLIC3R_STDVEC_MEMSIZE(m_layers.get_ranges(), Layers::Range);
        BOOST_LOG_TRIVIAL(trace) << label
            << "(" << format_memsize_MB(additional + paths_size + render_paths_size + layers_size) << ");"
            << log_memory_info();
    }
}
References Slic3r::format_memsize_MB(), Slic3r::get_logging_level(), Slic3r::GUI::GCodeViewer::Layers::get_ranges(), Slic3r::GUI::GCodeViewer::Layers::get_zs(), Slic3r::log_memory_info(), m_buffers, m_layers, Slic3r::GUI::GCodeViewer::TBuffer::paths, Slic3r::GUI::GCodeViewer::TBuffer::render_paths, SLIC3R_STDUNORDEREDSET_MEMSIZE, and SLIC3R_STDVEC_MEMSIZE.
Referenced by load_toolpaths(), and refresh().
option_color()
ColorRGBA Slic3r::GUI::GCodeViewer::option_color (EMoveType move_type) const private
{
    switch (move_type)
    {
    case EMoveType::Tool_change:  { return Options_Colors[static_cast<unsigned int>(EOptionsColors::ToolChanges)]; }
    case EMoveType::Color_change: { return Options_Colors[static_cast<unsigned int>(EOptionsColors::ColorChanges)]; }
    case EMoveType::Pause_Print:  { return Options_Colors[static_cast<unsigned int>(EOptionsColors::PausePrints)]; }
    case EMoveType::Custom_GCode: { return Options_Colors[static_cast<unsigned int>(EOptionsColors::CustomGCodes)]; }
    case EMoveType::Retract:      { return Options_Colors[static_cast<unsigned int>(EOptionsColors::Retractions)]; }
    case EMoveType::Unretract:    { return Options_Colors[static_cast<unsigned int>(EOptionsColors::Unretractions)]; }
    case EMoveType::Seam:         { return Options_Colors[static_cast<unsigned int>(EOptionsColors::Seams)]; }
    default:                      { return { 0.0f, 0.0f, 0.0f, 1.0f }; }
    }
}
References Slic3r::Color_change, ColorChanges, Slic3r::Custom_GCode, CustomGCodes, Options_Colors, Slic3r::Pause_Print, PausePrints, Slic3r::Retract, Retractions, Slic3r::Seam, Seams, Slic3r::Tool_change, ToolChanges, Slic3r::Unretract, and Unretractions.
Referenced by init(), and refresh_render_paths().
refresh()
void Slic3r::GUI::GCodeViewer::refresh (const GCodeProcessorResult & gcode_result, const std::vector< std::string > & str_tool_colors)
{
#if ENABLE_GCODE_VIEWER_STATISTICS
    auto start_time = std::chrono::high_resolution_clock::now();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    if (m_moves_count == 0)
        return;
    wxBusyCursor busy;
    if (m_view_type == EViewType::Tool && !gcode_result.extruder_colors.empty())
        // update tool colors from config stored in the gcode
        decode_colors(gcode_result.extruder_colors, m_tool_colors);
    else
        // update tool colors
        decode_colors(str_tool_colors, m_tool_colors);
    ColorRGBA default_color;
    decode_color("#FF8000", default_color);
    // ensure there are enough colors defined
    while (m_tool_colors.size() < std::max(size_t(1), gcode_result.extruders_count))
        m_tool_colors.push_back(default_color);
    // update ranges for coloring / legend
    m_extrusions.reset_ranges();
    for (size_t i = 0; i < m_moves_count; ++i) {
        // skip first vertex
        if (i == 0)
            continue;
        const GCodeProcessorResult::MoveVertex& curr = gcode_result.moves[i];
        switch (curr.type)
        {
        case EMoveType::Extrude:
        {
            m_extrusions.ranges.height.update_from(round_to_bin(curr.height));
            if (curr.extrusion_role != GCodeExtrusionRole::Custom || is_visible(GCodeExtrusionRole::Custom))
                m_extrusions.ranges.width.update_from(round_to_bin(curr.width));
            m_extrusions.ranges.fan_speed.update_from(curr.fan_speed);
            m_extrusions.ranges.temperature.update_from(curr.temperature);
            if (curr.extrusion_role != GCodeExtrusionRole::Custom || is_visible(GCodeExtrusionRole::Custom))
                m_extrusions.ranges.volumetric_rate.update_from(round_to_bin(curr.volumetric_rate()));
            [[fallthrough]];
        }
        case EMoveType::Travel:
        {
            if (m_buffers[buffer_id(curr.type)].visible)
                m_extrusions.ranges.feedrate.update_from(curr.feedrate);
            break;
        }
        default: { break; }
        }
    }
    for (size_t i = 0; i < gcode_result.print_statistics.modes.size(); ++i) {
        m_layers_times[i] = gcode_result.print_statistics.modes[i].layers_times;
    }
    for (size_t i = 0; i < m_layers_times.size(); ++i) {
        for (float time : m_layers_times[i]) {
            m_extrusions.ranges.layer_time[i].update_from(time);
        }
    }
#if ENABLE_GCODE_VIEWER_STATISTICS
    m_statistics.refresh_time = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - start_time).count();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    // update buffers' render paths
    refresh_render_paths(false, false);
    log_memory_used("Refreshed G-code extrusion paths, ");
}
References Slic3r::GUI::buffer_id(), Slic3r::Custom, Slic3r::decode_color(), Slic3r::decode_colors(), Slic3r::Extrude, Slic3r::GCodeProcessorResult::extruder_colors, Slic3r::GCodeProcessorResult::extruders_count, Slic3r::GCodeProcessorResult::MoveVertex::extrusion_role, Slic3r::GCodeProcessorResult::MoveVertex::fan_speed, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::fan_speed, Slic3r::GCodeProcessorResult::MoveVertex::feedrate, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::feedrate, Slic3r::GCodeProcessorResult::MoveVertex::height, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::height, is_visible(), Slic3r::GUI::GCodeViewer::Extrusions::Ranges::layer_time, log_memory_used(), m_buffers, m_extrusions, m_layers_times, m_moves_count, m_tool_colors, m_view_type, Slic3r::PrintEstimatedStatistics::modes, Slic3r::GCodeProcessorResult::moves, Slic3r::GCodeProcessorResult::print_statistics, Slic3r::GUI::GCodeViewer::Extrusions::ranges, refresh_render_paths(), Slic3r::GUI::GCodeViewer::Extrusions::reset_ranges(), Slic3r::GUI::round_to_bin(), Slic3r::GCodeProcessorResult::MoveVertex::temperature, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::temperature, Tool, Slic3r::Travel, Slic3r::GCodeProcessorResult::MoveVertex::type, Slic3r::GUI::GCodeViewer::Extrusions::Range::update_from(), Slic3r::GCodeProcessorResult::MoveVertex::volumetric_rate(), Slic3r::GUI::GCodeViewer::Extrusions::Ranges::volumetric_rate, Slic3r::GCodeProcessorResult::MoveVertex::width, and Slic3r::GUI::GCodeViewer::Extrusions::Ranges::width.
Referenced by Slic3r::GUI::GLCanvas3D::load_gcode_preview().
refresh_render_paths()
void Slic3r::GUI::GCodeViewer::refresh_render_paths (bool keep_sequential_current_first, bool keep_sequential_current_last) const
{
#if ENABLE_GCODE_VIEWER_STATISTICS
    auto start_time = std::chrono::high_resolution_clock::now();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    auto extrusion_color = [this](const Path& path) {
        ColorRGBA color;
        switch (m_view_type)
        {
        case EViewType::FeatureType:    { color = Extrusion_Role_Colors[static_cast<unsigned int>(path.role)]; break; }
        case EViewType::Height:         { color = m_extrusions.ranges.height.get_color_at(path.height); break; }
        case EViewType::Width:          { color = m_extrusions.ranges.width.get_color_at(path.width); break; }
        case EViewType::Feedrate:       { color = m_extrusions.ranges.feedrate.get_color_at(path.feedrate); break; }
        case EViewType::FanSpeed:       { color = m_extrusions.ranges.fan_speed.get_color_at(path.fan_speed); break; }
        case EViewType::Temperature:    { color = m_extrusions.ranges.temperature.get_color_at(path.temperature); break; }
        case EViewType::LayerTimeLinear:
        case EViewType::LayerTimeLogarithmic: {
            const Path::Sub_Path& sub_path = path.sub_paths.front();
            double z = static_cast<double>(sub_path.first.position.z());
            const std::vector<double>& zs = m_layers.get_zs();
            const std::vector<Layers::Range>& ranges = m_layers.get_ranges();
            size_t time_mode_id = static_cast<size_t>(m_time_estimate_mode);
            for (size_t i = 0; i < zs.size(); ++i) {
                if (std::abs(zs[i] - z) < EPSILON) {
                    if (ranges[i].contains(sub_path.first.s_id)) {
                        color = m_extrusions.ranges.layer_time[time_mode_id].get_color_at(m_layers_times[time_mode_id][i],
                            (m_view_type == EViewType::LayerTimeLinear) ? Extrusions::Range::EType::Linear : Extrusions::Range::EType::Logarithmic);
                        break;
                    }
                }
            }
            break;
        }
        case EViewType::VolumetricRate: { color = m_extrusions.ranges.volumetric_rate.get_color_at(path.volumetric_rate); break; }
        case EViewType::Tool:           { color = m_tool_colors[path.extruder_id]; break; }
        case EViewType::ColorPrint:     {
            if (path.cp_color_id >= static_cast<unsigned char>(m_tool_colors.size()))
                color = ColorRGBA::GRAY();
            else
                color = m_tool_colors[path.cp_color_id];
            break;
        }
        default: { color = ColorRGBA::WHITE(); break; }
        }
        return color;
    };
    auto travel_color = [](const Path& path) {
        return (path.delta_extruder < 0.0f) ? Travel_Colors[2] /* Retract */ :
            ((path.delta_extruder > 0.0f) ? Travel_Colors[1] /* Extrude */ :
                Travel_Colors[0] /* Move */);
    };
    auto is_in_layers_range = [this](const Path& path, size_t min_id, size_t max_id) {
        auto in_layers_range = [this, min_id, max_id](size_t id) {
            return m_layers.get_range_at(min_id).first <= id && id <= m_layers.get_range_at(max_id).last;
        };
        return in_layers_range(path.sub_paths.front().first.s_id) && in_layers_range(path.sub_paths.back().last.s_id);
    };
    auto is_travel_in_layers_range = [this](size_t path_id, size_t min_id, size_t max_id) {
        const TBuffer& buffer = m_buffers[buffer_id(EMoveType::Travel)];
        if (path_id >= buffer.paths.size())
            return false;
        Path path = buffer.paths[path_id];
        size_t first = path_id;
        size_t last = path_id;
        // check adjacent paths
        while (first > 0) {
            const Path& ref_path = buffer.paths[first - 1];
            if (!path.sub_paths.front().first.position.isApprox(ref_path.sub_paths.back().last.position) ||
                path.role != ref_path.role)
                break;
            path.sub_paths.front().first = ref_path.sub_paths.front().first;
            --first;
        }
        while (last < buffer.paths.size() - 1) {
            const Path& ref_path = buffer.paths[last + 1];
            if (!path.sub_paths.back().last.position.isApprox(ref_path.sub_paths.front().first.position) ||
                path.role != ref_path.role)
                break;
            path.sub_paths.back().last = ref_path.sub_paths.back().last;
            ++last;
        }
        const size_t min_s_id = m_layers.get_range_at(min_id).first;
        const size_t max_s_id = m_layers.get_range_at(max_id).last;
        return (min_s_id <= path.sub_paths.front().first.s_id && path.sub_paths.front().first.s_id <= max_s_id) ||
            (min_s_id <= path.sub_paths.back().last.s_id && path.sub_paths.back().last.s_id <= max_s_id);
    };
#if ENABLE_GCODE_VIEWER_STATISTICS
    Statistics* statistics = const_cast<Statistics*>(&m_statistics);
    statistics->render_paths_size = 0;
    statistics->models_instances_size = 0;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    const bool top_layer_only = get_app_config()->get_bool("seq_top_layer_only");
    SequentialView::Endpoints global_endpoints = { m_moves_count , 0 };
    SequentialView::Endpoints top_layer_endpoints = global_endpoints;
    SequentialView* sequential_view = const_cast<SequentialView*>(&m_sequential_view);
    if (top_layer_only || !keep_sequential_current_first) sequential_view->current.first = 0;
    if (!keep_sequential_current_last) sequential_view->current.last = m_moves_count;
    // first pass: collect visible paths and update sequential view data
    std::vector<std::tuple<unsigned char, unsigned int, unsigned int, unsigned int>> paths;
    for (size_t b = 0; b < m_buffers.size(); ++b) {
        TBuffer& buffer = const_cast<TBuffer&>(m_buffers[b]);
        // reset render paths
        buffer.render_paths.clear();
        if (!buffer.visible)
            continue;
        if (buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::InstancedModel ||
            buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::BatchedModel) {
            for (size_t id : buffer.model.instances.s_ids) {
                if (id < m_layers.get_range_at(m_layers_z_range[0]).first || m_layers.get_range_at(m_layers_z_range[1]).last < id)
                    continue;
                global_endpoints.first = std::min(global_endpoints.first, id);
                global_endpoints.last = std::max(global_endpoints.last, id);
                if (top_layer_only) {
                    if (id < m_layers.get_range_at(m_layers_z_range[1]).first || m_layers.get_range_at(m_layers_z_range[1]).last < id)
                        continue;
                    top_layer_endpoints.first = std::min(top_layer_endpoints.first, id);
                    top_layer_endpoints.last = std::max(top_layer_endpoints.last, id);
                }
            }
        }
        else {
            for (size_t i = 0; i < buffer.paths.size(); ++i) {
                const Path& path = buffer.paths[i];
                if (path.type == EMoveType::Travel) {
                    if (path.sub_paths.front().first.s_id > m_layers_z_range[0]) {
                        if (!is_travel_in_layers_range(i, m_layers_z_range[0], m_layers_z_range[1]))
                            continue;
                    }
                }
                else if (!is_in_layers_range(path, m_layers_z_range[0], m_layers_z_range[1]))
                    continue;
                if (path.type == EMoveType::Extrude && !is_visible(path))
                    continue;
                // store valid path
                for (size_t j = 0; j < path.sub_paths.size(); ++j) {
                    paths.push_back({ static_cast<unsigned char>(b), path.sub_paths[j].first.b_id, static_cast<unsigned int>(i), static_cast<unsigned int>(j) });
                }
                global_endpoints.first = std::min(global_endpoints.first, path.sub_paths.front().first.s_id);
                global_endpoints.last = std::max(global_endpoints.last, path.sub_paths.back().last.s_id);
                if (top_layer_only) {
                    if (path.type == EMoveType::Travel) {
                        if (is_travel_in_layers_range(i, m_layers_z_range[1], m_layers_z_range[1])) {
                            top_layer_endpoints.first = std::min(top_layer_endpoints.first, path.sub_paths.front().first.s_id);
                            top_layer_endpoints.last = std::max(top_layer_endpoints.last, path.sub_paths.back().last.s_id);
                        }
                    }
                    else if (is_in_layers_range(path, m_layers_z_range[1], m_layers_z_range[1])) {
                        top_layer_endpoints.first = std::min(top_layer_endpoints.first, path.sub_paths.front().first.s_id);
                        top_layer_endpoints.last = std::max(top_layer_endpoints.last, path.sub_paths.back().last.s_id);
                    }
                }
            }
        }
    }
    // update current sequential position
    sequential_view->current.first = !top_layer_only && keep_sequential_current_first ? std::clamp(sequential_view->current.first, global_endpoints.first, global_endpoints.last) : global_endpoints.first;
    sequential_view->current.last = keep_sequential_current_last ? std::clamp(sequential_view->current.last, global_endpoints.first, global_endpoints.last) : global_endpoints.last;
    // get the world position from the vertex buffer
    bool found = false;
    for (const TBuffer& buffer : m_buffers) {
        if (buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::InstancedModel ||
            buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::BatchedModel) {
            for (size_t i = 0; i < buffer.model.instances.s_ids.size(); ++i) {
                if (buffer.model.instances.s_ids[i] == m_sequential_view.current.last) {
                    size_t offset = i * buffer.model.instances.instance_size_floats();
                    sequential_view->current_position.x() = buffer.model.instances.buffer[offset + 0];
                    sequential_view->current_position.y() = buffer.model.instances.buffer[offset + 1];
                    sequential_view->current_position.z() = buffer.model.instances.buffer[offset + 2];
                    sequential_view->current_offset = buffer.model.instances.offsets[i];
                    found = true;
                    break;
                }
            }
        }
        else {
            // searches the path containing the current position
            for (const Path& path : buffer.paths) {
                if (path.contains(m_sequential_view.current.last)) {
                    const int sub_path_id = path.get_id_of_sub_path_containing(m_sequential_view.current.last);
                    if (sub_path_id != -1) {
                        const Path::Sub_Path& sub_path = path.sub_paths[sub_path_id];
                        unsigned int offset = static_cast<unsigned int>(m_sequential_view.current.last - sub_path.first.s_id);
                        if (offset > 0) {
                            if (buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::Line)
                                offset = 2 * offset - 1;
                            else if (buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::Triangle) {
                                unsigned int indices_count = buffer.indices_per_segment();
                                offset = indices_count * (offset - 1) + (indices_count - 2);
                                if (sub_path_id == 0)
                                    offset += 6; // add 2 triangles for starting cap
                            }
                        }
                        offset += static_cast<unsigned int>(sub_path.first.i_id);
                        // gets the vertex index from the index buffer on gpu
                        const IBuffer& i_buffer = buffer.indices[sub_path.first.b_id];
                        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, i_buffer.ibo));
#if ENABLE_OPENGL_ES
                        IBufferType index = *static_cast<IBufferType*>(::glMapBufferRange(GL_ELEMENT_ARRAY_BUFFER,
                            static_cast<GLintptr>(offset * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)),
                            GL_MAP_READ_BIT));
                        glcheck();
                        glsafe(::glUnmapBuffer(GL_ELEMENT_ARRAY_BUFFER));
#else
                        IBufferType index = 0;
                        glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>(offset * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)), static_cast<void*>(&index)));
#endif // ENABLE_OPENGL_ES
                        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
                        // gets the position from the vertices buffer on gpu
                        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, i_buffer.vbo));
#if ENABLE_OPENGL_ES
                        sequential_view->current_position = *static_cast<Vec3f*>(::glMapBufferRange(GL_ARRAY_BUFFER,
                            static_cast<GLintptr>(index * buffer.vertices.vertex_size_bytes()),
                            static_cast<GLsizeiptr>(buffer.vertices.position_size_bytes()), GL_MAP_READ_BIT));
                        glcheck();
                        glsafe(::glUnmapBuffer(GL_ARRAY_BUFFER));
#else
                        glsafe(::glGetBufferSubData(GL_ARRAY_BUFFER, static_cast<GLintptr>(index * buffer.vertices.vertex_size_bytes()), static_cast<GLsizeiptr>(3 * sizeof(float)), static_cast<void*>(sequential_view->current_position.data())));
#endif // ENABLE_OPENGL_ES
                        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
                        sequential_view->current_offset = Vec3f::Zero();
                        found = true;
                        break;
                    }
                }
            }
        }
        if (found)
            break;
    }
    // second pass: filter paths by sequential data and collect them by color
    RenderPath* render_path = nullptr;
    for (const auto& [tbuffer_id, ibuffer_id, path_id, sub_path_id] : paths) {
        TBuffer& buffer = const_cast<TBuffer&>(m_buffers[tbuffer_id]);
        const Path& path = buffer.paths[path_id];
        const Path::Sub_Path& sub_path = path.sub_paths[sub_path_id];
        if (m_sequential_view.current.last < sub_path.first.s_id || sub_path.last.s_id < m_sequential_view.current.first)
            continue;
        ColorRGBA color;
        switch (path.type)
        {
        case EMoveType::Tool_change:
        case EMoveType::Color_change:
        case EMoveType::Pause_Print:
        case EMoveType::Custom_GCode:
        case EMoveType::Retract:
        case EMoveType::Unretract:
        case EMoveType::Seam: { color = option_color(path.type); break; }
        case EMoveType::Extrude: {
            if (!top_layer_only ||
                m_sequential_view.current.last == global_endpoints.last ||
                is_in_layers_range(path, m_layers_z_range[1], m_layers_z_range[1]))
                color = extrusion_color(path);
            else
                color = Neutral_Color;
            break;
        }
        case EMoveType::Travel: {
            if (!top_layer_only || m_sequential_view.current.last == global_endpoints.last || is_travel_in_layers_range(path_id, m_layers_z_range[1], m_layers_z_range[1]))
                color = (m_view_type == EViewType::Feedrate || m_view_type == EViewType::Tool || m_view_type == EViewType::ColorPrint) ? extrusion_color(path) : travel_color(path);
            else
                color = Neutral_Color;
            break;
        }
        case EMoveType::Wipe: { color = Wipe_Color; break; }
        default: { color = { 0.0f, 0.0f, 0.0f, 1.0f }; break; }
        }
        RenderPath key{ tbuffer_id, color, static_cast<unsigned int>(ibuffer_id), path_id };
        if (render_path == nullptr || !RenderPathPropertyEqual()(*render_path, key)) {
            buffer.render_paths.emplace_back(key);
            render_path = const_cast<RenderPath*>(&buffer.render_paths.back());
        }
        unsigned int delta_1st = 0;
        if (sub_path.first.s_id < m_sequential_view.current.first && m_sequential_view.current.first <= sub_path.last.s_id)
            delta_1st = static_cast<unsigned int>(m_sequential_view.current.first - sub_path.first.s_id);
        unsigned int size_in_indices = 0;
        switch (buffer.render_primitive_type)
        {
        case TBuffer::ERenderPrimitiveType::Line:
        case TBuffer::ERenderPrimitiveType::Triangle: {
            unsigned int segments_count = std::min(m_sequential_view.current.last, sub_path.last.s_id) - std::max(m_sequential_view.current.first, sub_path.first.s_id);
            size_in_indices = buffer.indices_per_segment() * segments_count;
            break;
        }
        default: { break; }
        }
        if (size_in_indices == 0)
            continue;
        if (buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::Triangle) {
            if (sub_path_id == 0 && delta_1st == 0)
                size_in_indices += 6; // add 2 triangles for starting cap
            if (sub_path_id == path.sub_paths.size() - 1 && path.sub_paths.back().last.s_id <= m_sequential_view.current.last)
                size_in_indices += 6; // add 2 triangles for ending cap
            if (delta_1st > 0)
                size_in_indices -= 6; // remove 2 triangles for corner cap
        }
        render_path->sizes.push_back(size_in_indices);
        if (buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::Triangle) {
            delta_1st *= buffer.indices_per_segment();
            if (delta_1st > 0) {
                delta_1st += 6; // skip 2 triangles for corner cap
                if (sub_path_id == 0)
                    delta_1st += 6; // skip 2 triangles for starting cap
            }
        }
        render_path->offsets.push_back(static_cast<size_t>((sub_path.first.i_id + delta_1st) * sizeof(IBufferType)));
#if 0
        // check sizes and offsets against index buffer size on gpu
        GLint buffer_size;
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, buffer->indices[render_path->ibuffer_id].ibo));
        glsafe(::glGetBufferParameteriv(GL_ELEMENT_ARRAY_BUFFER, GL_BUFFER_SIZE, &buffer_size));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
        if (render_path->offsets.back() + render_path->sizes.back() * sizeof(IBufferType) > buffer_size)
            BOOST_LOG_TRIVIAL(error) << "GCodeViewer::refresh_render_paths: Invalid render path data";
#endif
    }
    // Removes empty render paths and sort.
    for (size_t b = 0; b < m_buffers.size(); ++b) {
        TBuffer* buffer = const_cast<TBuffer*>(&m_buffers[b]);
        buffer->render_paths.erase(std::remove_if(buffer->render_paths.begin(), buffer->render_paths.end(),
            [](const auto &path){ return path.sizes.empty() || path.offsets.empty(); }),
            buffer->render_paths.end());
    }
    // second pass: for buffers using instanced and batched models, update the instances render ranges
    for (size_t b = 0; b < m_buffers.size(); ++b) {
        TBuffer& buffer = const_cast<TBuffer&>(m_buffers[b]);
        if (buffer.render_primitive_type != TBuffer::ERenderPrimitiveType::InstancedModel &&
            buffer.render_primitive_type != TBuffer::ERenderPrimitiveType::BatchedModel)
            continue;
        buffer.model.instances.render_ranges.reset();
        if (!buffer.visible || buffer.model.instances.s_ids.empty())
            continue;
        buffer.model.instances.render_ranges.ranges.push_back({ 0, 0, 0, buffer.model.color });
        bool has_second_range = top_layer_only && m_sequential_view.current.last != m_sequential_view.global.last;
        if (has_second_range)
            buffer.model.instances.render_ranges.ranges.push_back({ 0, 0, 0, Neutral_Color });
        if (m_sequential_view.current.first <= buffer.model.instances.s_ids.back() && buffer.model.instances.s_ids.front() <= m_sequential_view.current.last) {
            for (size_t id : buffer.model.instances.s_ids) {
                if (has_second_range) {
                    if (id < m_sequential_view.endpoints.first) {
                        ++buffer.model.instances.render_ranges.ranges.front().offset;
                        if (id <= m_sequential_view.current.first)
                            ++buffer.model.instances.render_ranges.ranges.back().offset;
                        else
                            ++buffer.model.instances.render_ranges.ranges.back().count;
                    }
                    else if (id <= m_sequential_view.current.last)
                        ++buffer.model.instances.render_ranges.ranges.front().count;
                    else
                        break;
                }
                else {
                    if (id <= m_sequential_view.current.first)
                        ++buffer.model.instances.render_ranges.ranges.front().offset;
                    else if (id <= m_sequential_view.current.last)
                        ++buffer.model.instances.render_ranges.ranges.front().count;
                    else
                        break;
                }
            }
        }
    }
    // set sequential data to their final value
    sequential_view->endpoints = top_layer_only ? top_layer_endpoints : global_endpoints;
    sequential_view->current.first = !top_layer_only && keep_sequential_current_first ? std::clamp(sequential_view->current.first, sequential_view->endpoints.first, sequential_view->endpoints.last) : sequential_view->endpoints.first;
    sequential_view->global = global_endpoints;
    // updates sequential range caps
    std::array<SequentialRangeCap, 2>* sequential_range_caps = const_cast<std::array<SequentialRangeCap, 2>*>(&m_sequential_range_caps);
    (*sequential_range_caps)[0].reset();
    (*sequential_range_caps)[1].reset();
    if (m_sequential_view.current.first != m_sequential_view.current.last) {
        for (const auto& [tbuffer_id, ibuffer_id, path_id, sub_path_id] : paths) {
            TBuffer& buffer = const_cast<TBuffer&>(m_buffers[tbuffer_id]);
            if (buffer.render_primitive_type != TBuffer::ERenderPrimitiveType::Triangle)
                continue;
            const Path& path = buffer.paths[path_id];
            const Path::Sub_Path& sub_path = path.sub_paths[sub_path_id];
            if (m_sequential_view.current.last <= sub_path.first.s_id || sub_path.last.s_id <= m_sequential_view.current.first)
                continue;
            // update cap for first endpoint of current range
            if (m_sequential_view.current.first > sub_path.first.s_id) {
                SequentialRangeCap& cap = (*sequential_range_caps)[0];
                const IBuffer& i_buffer = buffer.indices[ibuffer_id];
                cap.buffer = &buffer;
#if ENABLE_GL_CORE_PROFILE
                if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                    cap.vao = i_buffer.vao;
#endif // ENABLE_GL_CORE_PROFILE
                cap.vbo = i_buffer.vbo;
                // calculate offset into the index buffer
                unsigned int offset = sub_path.first.i_id;
                offset += 6; // add 2 triangles for corner cap
                offset += static_cast<unsigned int>(m_sequential_view.current.first - sub_path.first.s_id) * buffer.indices_per_segment();
                if (sub_path_id == 0)
                    offset += 6; // add 2 triangles for starting cap
                // extract indices from index buffer
                std::array<IBufferType, 6> indices{ 0, 0, 0, 0, 0, 0 };
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, i_buffer.ibo));
#if ENABLE_OPENGL_ES
                IBufferType* index_ptr = static_cast<IBufferType*>(::glMapBufferRange(GL_ELEMENT_ARRAY_BUFFER,
                    static_cast<GLintptr>(offset * sizeof(IBufferType)), static_cast<GLsizeiptr>(14 * sizeof(IBufferType)),
                    GL_MAP_READ_BIT));
                glcheck();
                indices[0] = *(index_ptr + 0);
                indices[1] = *(index_ptr + 7);
                indices[2] = *(index_ptr + 1);
                indices[4] = *(index_ptr + 13);
                glsafe(::glUnmapBuffer(GL_ELEMENT_ARRAY_BUFFER));
#else
                glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>((offset + 0) * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)), static_cast<void*>(&indices[0])));
                glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>((offset + 7) * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)), static_cast<void*>(&indices[1])));
                glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>((offset + 1) * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)), static_cast<void*>(&indices[2])));
                glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>((offset + 13) * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)), static_cast<void*>(&indices[4])));
#endif // ENABLE_OPENGL_ES
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
                indices[3] = indices[0];
                indices[5] = indices[1];
                // send indices to gpu
                glsafe(::glGenBuffers(1, &cap.ibo));
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, cap.ibo));
                glsafe(::glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(IBufferType), indices.data(), GL_STATIC_DRAW));
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
                // extract color from render path
                size_t offset_bytes = offset * sizeof(IBufferType);
                for (const RenderPath& render_path : buffer.render_paths) {
                    if (render_path.ibuffer_id == ibuffer_id) {
                        for (size_t j = 0; j < render_path.offsets.size(); ++j) {
                            if (render_path.contains(offset_bytes)) {
                                cap.color = render_path.color;
                                break;
                            }
                        }
                    }
                }
            }
            // update cap for last endpoint of current range
            if (m_sequential_view.current.last < sub_path.last.s_id) {
                SequentialRangeCap& cap = (*sequential_range_caps)[1];
                const IBuffer& i_buffer = buffer.indices[ibuffer_id];
                cap.buffer = &buffer;
#if ENABLE_GL_CORE_PROFILE
                if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                    cap.vao = i_buffer.vao;
#endif // ENABLE_GL_CORE_PROFILE
                cap.vbo = i_buffer.vbo;
                // calculate offset into the index buffer
                unsigned int offset = sub_path.first.i_id;
                offset += 6; // add 2 triangles for corner cap
                offset += static_cast<unsigned int>(m_sequential_view.current.last - 1 - sub_path.first.s_id) * buffer.indices_per_segment();
                if (sub_path_id == 0)
                    offset += 6; // add 2 triangles for starting cap
                // extract indices from index buffer
                std::array<IBufferType, 6> indices{ 0, 0, 0, 0, 0, 0 };
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, i_buffer.ibo));
#if ENABLE_OPENGL_ES
                IBufferType* index_ptr = static_cast<IBufferType*>(::glMapBufferRange(GL_ELEMENT_ARRAY_BUFFER,
                    static_cast<GLintptr>(offset * sizeof(IBufferType)), static_cast<GLsizeiptr>(17 * sizeof(IBufferType)),
                    GL_MAP_READ_BIT));
                glcheck();
                indices[0] = *(index_ptr + 2);
                indices[1] = *(index_ptr + 4);
                indices[2] = *(index_ptr + 10);
                indices[5] = *(index_ptr + 16);
                glsafe(::glUnmapBuffer(GL_ELEMENT_ARRAY_BUFFER));
#else
                glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>((offset + 2) * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)), static_cast<void*>(&indices[0])));
                glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>((offset + 4) * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)), static_cast<void*>(&indices[1])));
                glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>((offset + 10) * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)), static_cast<void*>(&indices[2])));
                glsafe(::glGetBufferSubData(GL_ELEMENT_ARRAY_BUFFER, static_cast<GLintptr>((offset + 16) * sizeof(IBufferType)), static_cast<GLsizeiptr>(sizeof(IBufferType)), static_cast<void*>(&indices[5])));
#endif // ENABLE_OPENGL_ES
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
                indices[3] = indices[0];
                indices[4] = indices[2];
                // send indices to gpu
                glsafe(::glGenBuffers(1, &cap.ibo));
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, cap.ibo));
                glsafe(::glBufferData(GL_ELEMENT_ARRAY_BUFFER, 6 * sizeof(IBufferType), indices.data(), GL_STATIC_DRAW));
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
                // extract color from render path
                size_t offset_bytes = offset * sizeof(IBufferType);
                for (const RenderPath& render_path : buffer.render_paths) {
                    if (render_path.ibuffer_id == ibuffer_id) {
                        for (size_t j = 0; j < render_path.offsets.size(); ++j) {
                            if (render_path.contains(offset_bytes)) {
                                cap.color = render_path.color;
                                break;
                            }
                        }
                    }
                }
            }
            if ((*sequential_range_caps)[0].is_renderable() && (*sequential_range_caps)[1].is_renderable())
                break;
        }
    }
    wxGetApp().plater()->enable_preview_moves_slider(!paths.empty());
#if ENABLE_GCODE_VIEWER_STATISTICS
    for (const TBuffer& buffer : m_buffers) {
        statistics->render_paths_size += SLIC3R_STDUNORDEREDSET_MEMSIZE(buffer.render_paths, RenderPath);
        for (const RenderPath& path : buffer.render_paths) {
            statistics->render_paths_size += SLIC3R_STDVEC_MEMSIZE(path.sizes, unsigned int);
            statistics->render_paths_size += SLIC3R_STDVEC_MEMSIZE(path.offsets, size_t);
        }
        statistics->models_instances_size += SLIC3R_STDVEC_MEMSIZE(buffer.model.instances.buffer, float);
        statistics->models_instances_size += SLIC3R_STDVEC_MEMSIZE(buffer.model.instances.s_ids, size_t);
        statistics->models_instances_size += SLIC3R_STDVEC_MEMSIZE(buffer.model.instances.render_ranges.ranges, InstanceVBuffer::Ranges::Range);
    }
    statistics->refresh_paths_time = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - start_time).count();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
}
References Slic3r::GUI::GCodeViewer::Path::Endpoint::b_id, Slic3r::GUI::GCodeViewer::TBuffer::BatchedModel, Slic3r::GUI::GCodeViewer::SequentialRangeCap::buffer, Slic3r::GUI::buffer_id(), Slic3r::GUI::GCodeViewer::RenderPath::color, Slic3r::GUI::GCodeViewer::TBuffer::Model::color, Slic3r::GUI::GCodeViewer::SequentialRangeCap::color, Slic3r::Color_change, ColorPrint, Slic3r::Geometry::contains(), Slic3r::GUI::GCodeViewer::RenderPath::contains(), Slic3r::GUI::GCodeViewer::Path::contains(), Slic3r::GUI::GCodeViewer::SequentialView::current, Slic3r::GUI::GCodeViewer::SequentialView::current_offset, Slic3r::GUI::GCodeViewer::SequentialView::current_position, Slic3r::Custom_GCode, Eigen::PlainObjectBase< Derived >::data(), Slic3r::GUI::GCodeViewer::SequentialView::endpoints, EPSILON, error, Slic3r::Extrude, Extrusion_Role_Colors, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::fan_speed, FanSpeed, FeatureType, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::feedrate, Feedrate, Slic3r::GUI::GCodeViewer::Path::Sub_Path::first, Slic3r::GUI::GCodeViewer::Layers::Range::first, Slic3r::GUI::GCodeViewer::SequentialView::Endpoints::first, Slic3r::GUI::get_app_config(), Slic3r::AppConfig::get_bool(), Slic3r::GUI::GCodeViewer::Extrusions::Range::get_color_at(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::GCodeViewer::Path::get_id_of_sub_path_containing(), Slic3r::GUI::GCodeViewer::Layers::get_range_at(), Slic3r::GUI::GCodeViewer::Layers::get_ranges(), Slic3r::GUI::GCodeViewer::Layers::get_zs(), glcheck, Slic3r::GUI::GCodeViewer::SequentialView::global, glsafe, Slic3r::ColorRGBA::GRAY(), Slic3r::GUI::GCodeViewer::Extrusions::Ranges::height, Height, Slic3r::GUI::GCodeViewer::Path::Endpoint::i_id, Slic3r::GUI::GCodeViewer::IBuffer::ibo, Slic3r::GUI::GCodeViewer::SequentialRangeCap::ibo, Slic3r::GUI::GCodeViewer::RenderPath::ibuffer_id, Slic3r::GUI::GCodeViewer::TBuffer::indices, Slic3r::GUI::GCodeViewer::TBuffer::indices_per_segment(), Slic3r::GUI::GCodeViewer::TBuffer::InstancedModel, Slic3r::GUI::GCodeViewer::TBuffer::Model::instances, Slic3r::GUI::OpenGLManager::GLInfo::is_version_greater_or_equal_to(), is_visible(), Slic3r::GUI::GCodeViewer::Path::Sub_Path::last, Slic3r::GUI::GCodeViewer::Layers::Range::last, Slic3r::GUI::GCodeViewer::SequentialView::Endpoints::last, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::layer_time, LayerTimeLinear, LayerTimeLogarithmic, Slic3r::GUI::GCodeViewer::TBuffer::Line, Slic3r::GUI::GCodeViewer::Extrusions::Range::Linear, Slic3r::GUI::GCodeViewer::Extrusions::Range::Logarithmic, m_buffers, m_extrusions, m_layers, m_layers_times, m_layers_z_range, m_moves_count, m_sequential_range_caps, m_sequential_view, m_time_estimate_mode, m_tool_colors, m_view_type, Slic3r::GUI::GCodeViewer::TBuffer::model, Neutral_Color, Slic3r::offset(), Slic3r::GUI::GCodeViewer::RenderPath::offsets, option_color(), Slic3r::GUI::GCodeViewer::TBuffer::paths, Slic3r::Pause_Print, Slic3r::GUI::GCodeViewer::Path::Endpoint::position, Slic3r::GUI::GCodeViewer::InstanceVBuffer::Ranges::ranges, Slic3r::GUI::GCodeViewer::Extrusions::ranges, Slic3r::GUI::GCodeViewer::TBuffer::render_paths, Slic3r::GUI::GCodeViewer::TBuffer::render_primitive_type, Slic3r::GUI::GCodeViewer::InstanceVBuffer::render_ranges, Slic3r::GUI::GCodeViewer::InstanceVBuffer::Ranges::reset(), Slic3r::Retract, Slic3r::GUI::GCodeViewer::Path::role, Slic3r::GUI::GCodeViewer::Path::Endpoint::s_id, Slic3r::GUI::GCodeViewer::InstanceVBuffer::s_ids, Slic3r::Seam, Slic3r::GUI::GCodeViewer::RenderPath::sizes, SLIC3R_STDUNORDEREDSET_MEMSIZE, SLIC3R_STDVEC_MEMSIZE, Slic3r::GUI::GCodeViewer::Path::sub_paths, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::temperature, Temperature, Tool, Slic3r::Tool_change, Slic3r::Travel, Travel_Colors, Slic3r::GUI::GCodeViewer::TBuffer::Triangle, Slic3r::GUI::GCodeViewer::Path::type, Slic3r::Unretract, Slic3r::GUI::GCodeViewer::IBuffer::vbo, Slic3r::GUI::GCodeViewer::SequentialRangeCap::vbo, Slic3r::GUI::GCodeViewer::TBuffer::visible, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::volumetric_rate, VolumetricRate, Slic3r::ColorRGBA::WHITE(), Slic3r::GUI::GCodeViewer::Extrusions::Ranges::width, Width, Slic3r::Wipe, and Wipe_Color.
Referenced by refresh(), Slic3r::GUI::GLCanvas3D::refresh_gcode_preview_render_paths(), render_legend(), set_layers_z_range(), and update_sequential_view_current().
render()
void Slic3r::GUI::GCodeViewer::render ()
{
#if ENABLE_GCODE_VIEWER_STATISTICS
    m_statistics.reset_opengl();
    m_statistics.total_instances_gpu_size = 0;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    if (m_roles.empty())
        return;
    glsafe(::glEnable(GL_DEPTH_TEST));
    render_toolpaths();
    render_shells();
    float legend_height = 0.0f;
    if (!m_layers.empty()) {
        render_legend(legend_height);
        if (m_sequential_view.current.last != m_sequential_view.endpoints.last) {
            m_sequential_view.marker.set_world_position(m_sequential_view.current_position);
            m_sequential_view.marker.set_world_offset(m_sequential_view.current_offset);
            m_sequential_view.render(legend_height);
        }
    }
#if ENABLE_GCODE_VIEWER_STATISTICS
    render_statistics();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
}
References Slic3r::GUI::GCodeViewer::SequentialView::current, Slic3r::GUI::GCodeViewer::SequentialView::current_offset, Slic3r::GUI::GCodeViewer::SequentialView::current_position, Slic3r::GUI::GCodeViewer::Layers::empty(), Slic3r::GUI::GCodeViewer::SequentialView::endpoints, glsafe, Slic3r::GUI::GCodeViewer::SequentialView::Endpoints::last, m_layers, m_roles, m_sequential_view, Slic3r::GUI::GCodeViewer::SequentialView::marker, Slic3r::GUI::GCodeViewer::SequentialView::render(), render_legend(), render_shells(), render_toolpaths(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::set_world_offset(), and Slic3r::GUI::GCodeViewer::SequentialView::Marker::set_world_position().
render_cog()
void Slic3r::GUI::GCodeViewer::render_cog () inline
{ m_cog.render(); }
References m_cog, and Slic3r::GUI::GCodeViewer::COG::render().
render_legend()
void Slic3r::GUI::GCodeViewer::render_legend (float & legend_height) private
{
    if (!m_legend_enabled)
        return;
    const Size cnv_size = wxGetApp().plater()->get_current_canvas3D()->get_canvas_size();
    ImGuiWrapper& imgui = *wxGetApp().imgui();
    imgui.set_next_window_pos(0.0f, 0.0f, ImGuiCond_Always);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    ImGui::SetNextWindowBgAlpha(0.6f);
    const float max_height = 0.75f * static_cast<float>(cnv_size.get_height());
    const float child_height = 0.3333f * max_height;
    ImGui::SetNextWindowSizeConstraints({ 0.0f, 0.0f }, { -1.0f, max_height });
    imgui.begin(std::string("Legend"), ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove);
    enum class EItemType : unsigned char
    {
        Rect,
        Circle,
        Hexagon,
        Line
    };
    const PrintEstimatedStatistics::Mode& time_mode = m_print_statistics.modes[static_cast<size_t>(m_time_estimate_mode)];
    bool show_estimated_time = time_mode.time > 0.0f && (m_view_type == EViewType::FeatureType ||
        m_view_type == EViewType::LayerTimeLinear || m_view_type == EViewType::LayerTimeLogarithmic ||
        (m_view_type == EViewType::ColorPrint && !time_mode.custom_gcode_times.empty()));
    const float icon_size = ImGui::GetTextLineHeight();
    const float percent_bar_size = 2.0f * ImGui::GetTextLineHeight();
    bool imperial_units = wxGetApp().app_config->get_bool("use_inches");
    auto append_item = [icon_size, percent_bar_size, &imgui, imperial_units](EItemType type, const ColorRGBA& color, const std::string& label,
        bool visible = true, const std::string& time = "", float percent = 0.0f, float max_percent = 0.0f, const std::array<float, 4>& offsets = { 0.0f, 0.0f, 0.0f, 0.0f },
        double used_filament_m = 0.0, double used_filament_g = 0.0,
        std::function<void()> callback = nullptr) {
        if (!visible)
            ImGui::PushStyleVar(ImGuiStyleVar_Alpha, 0.3333f);
        ImDrawList* draw_list = ImGui::GetWindowDrawList();
        ImVec2 pos = ImGui::GetCursorScreenPos();
        switch (type) {
        default:
        case EItemType::Rect: {
            draw_list->AddRectFilled({ pos.x + 1.0f, pos.y + 1.0f }, { pos.x + icon_size - 1.0f, pos.y + icon_size - 1.0f },
                ImGuiWrapper::to_ImU32(color));
            break;
        }
        case EItemType::Circle: {
            ImVec2 center(0.5f * (pos.x + pos.x + icon_size), 0.5f * (pos.y + pos.y + icon_size));
            draw_list->AddCircleFilled(center, 0.5f * icon_size, ImGuiWrapper::to_ImU32(color), 16);
            break;
        }
        case EItemType::Hexagon: {
            ImVec2 center(0.5f * (pos.x + pos.x + icon_size), 0.5f * (pos.y + pos.y + icon_size));
            draw_list->AddNgonFilled(center, 0.5f * icon_size, ImGuiWrapper::to_ImU32(color), 6);
            break;
        }
        case EItemType::Line: {
            draw_list->AddLine({ pos.x + 1, pos.y + icon_size - 1 }, { pos.x + icon_size - 1, pos.y + 1 }, ImGuiWrapper::to_ImU32(color), 3.0f);
            break;
        }
        }
        // draw text
        ImGui::Dummy({ icon_size, icon_size });
        ImGui::SameLine();
        // localize "g" and "m" units
        const std::string& grams  = _u8L("g");
        const std::string& inches = _u8L("in");
        const std::string& metres = _CTX_utf8(L_CONTEXT("m", "Metre"), "Metre");
        if (callback != nullptr) {
            if (ImGui::MenuItem(label.c_str()))
                callback();
            else {
                // show tooltip
                if (ImGui::IsItemHovered()) {
                    if (!visible)
                        ImGui::PopStyleVar();
                    ImGui::PushStyleColor(ImGuiCol_PopupBg, ImGuiWrapper::COL_WINDOW_BACKGROUND);
                    ImGui::BeginTooltip();
                    imgui.text(visible ? _u8L("Click to hide") : _u8L("Click to show"));
                    ImGui::EndTooltip();
                    ImGui::PopStyleColor();
                    if (!visible)
                        ImGui::PushStyleVar(ImGuiStyleVar_Alpha, 0.3333f);
                    // to avoid the tooltip to change size when moving the mouse
                    imgui.set_requires_extra_frame();
                }
            }
            if (!time.empty()) {
                ImGui::SameLine(offsets[0]);
                imgui.text(time);
                ImGui::SameLine(offsets[1]);
                pos = ImGui::GetCursorScreenPos();
                const float width = std::max(1.0f, percent_bar_size * percent / max_percent);
                draw_list->AddRectFilled({ pos.x, pos.y + 2.0f }, { pos.x + width, pos.y + icon_size - 2.0f },
                    ImGui::GetColorU32(ImGuiWrapper::COL_ORANGE_LIGHT));
                ImGui::Dummy({ percent_bar_size, icon_size });
                ImGui::SameLine();
                char buf[64];
                ::sprintf(buf, "%.1f%%", 100.0f * percent);
                ImGui::TextUnformatted((percent > 0.0f) ? buf : "");
                ImGui::SameLine(offsets[2]);
                imgui.text(format("%1$.2f %2%", used_filament_m, (imperial_units ? inches : metres)));
                ImGui::SameLine(offsets[3]);
                imgui.text(format("%1$.2f %2%", used_filament_g, grams));
            }
        }
        else {
            imgui.text(label);
            if (!time.empty()) {
                ImGui::SameLine(offsets[0]);
                imgui.text(time);
                ImGui::SameLine(offsets[1]);
                pos = ImGui::GetCursorScreenPos();
                const float width = std::max(1.0f, percent_bar_size * percent / max_percent);
                draw_list->AddRectFilled({ pos.x, pos.y + 2.0f }, { pos.x + width, pos.y + icon_size - 2.0f },
                    ImGui::GetColorU32(ImGuiWrapper::COL_ORANGE_LIGHT));
                ImGui::Dummy({ percent_bar_size, icon_size });
                ImGui::SameLine();
                char buf[64];
                ::sprintf(buf, "%.1f%%", 100.0f * percent);
                ImGui::TextUnformatted((percent > 0.0f) ? buf : "");
            }
            else if (used_filament_m > 0.0) {
                ImGui::SameLine(offsets[0]);
                imgui.text(format("%1$.2f %2%", used_filament_m, (imperial_units ? inches : metres)));
                ImGui::SameLine(offsets[1]);
                imgui.text(format("%1$.2f %2%", used_filament_g, grams));
            }
        }
        if (!visible)
            ImGui::PopStyleVar();
    };
    auto append_range = [append_item](const Extrusions::Range& range, unsigned int decimals) {
        auto append_range_item = [append_item](int i, float value, unsigned int decimals) {
            char buf[1024];
            ::sprintf(buf, "%.*f", decimals, value);
            append_item(EItemType::Rect, Range_Colors[i], buf);
        };
        if (range.count == 1)
            // single item use case
            append_range_item(0, range.min, decimals);
        else if (range.count == 2) {
            // two items use case
            append_range_item(static_cast<int>(Range_Colors.size()) - 1, range.max, decimals);
            append_range_item(0, range.min, decimals);
        }
        else {
            const float step_size = range.step_size();
            for (int i = static_cast<int>(Range_Colors.size()) - 1; i >= 0; --i) {
                append_range_item(i, range.min + static_cast<float>(i) * step_size, decimals);
            }
        }
    };
    auto append_time_range = [append_item](const Extrusions::Range& range, Extrusions::Range::EType type) {
        auto append_range_item = [append_item](int i, float value) {
            std::string str_value = get_time_dhms(value);
            if (str_value == "0s")
                str_value = "< 1s";
            append_item(EItemType::Rect, Range_Colors[i], str_value);
        };
        if (range.count == 1)
            // single item use case
            append_range_item(0, range.min);
        else if (range.count == 2) {
            // two items use case
            append_range_item(static_cast<int>(Range_Colors.size()) - 1, range.max);
            append_range_item(0, range.min);
        }
        else {
            float step_size = range.step_size(type);
            for (int i = static_cast<int>(Range_Colors.size()) - 1; i >= 0; --i) {
                float value = 0.0f;
                switch (type)
                {
                default:
                case Extrusions::Range::EType::Linear:      { value = range.min + static_cast<float>(i) * step_size; break; }
                case Extrusions::Range::EType::Logarithmic: { value = ::exp(::log(range.min) + static_cast<float>(i) * step_size);  break; }
                }
                append_range_item(i, value);
            }
        }
    };
    auto append_headers = [&imgui](const std::array<std::string, 5>& texts, const std::array<float, 4>& offsets) {
        size_t i = 0;
        for (; i < offsets.size(); i++) {
            imgui.text(texts[i]);
            ImGui::SameLine(offsets[i]);
        }
        imgui.text(texts[i]);
        ImGui::Separator();
    };
    auto max_width = [](const std::vector<std::string>& items, const std::string& title, float extra_size = 0.0f) {
        float ret = ImGui::CalcTextSize(title.c_str()).x;
        for (const std::string& item : items) {
            ret = std::max(ret, extra_size + ImGui::CalcTextSize(item.c_str()).x);
        }
        return ret;
    };
    auto calculate_offsets = [max_width](const std::vector<std::string>& labels, const std::vector<std::string>& times,
        const std::array<std::string, 4>& titles, float extra_size = 0.0f) {
            const ImGuiStyle& style = ImGui::GetStyle();
            std::array<float, 4> ret = { 0.0f, 0.0f, 0.0f, 0.0f };
            ret[0] = max_width(labels, titles[0], extra_size) + 3.0f * style.ItemSpacing.x;
            for (size_t i = 1; i < titles.size(); i++)
                ret[i] = ret[i-1] + max_width(times, titles[i]) + style.ItemSpacing.x;
            return ret;
    };
    auto color_print_ranges = [this](unsigned char extruder_id, const std::vector<CustomGCode::Item>& custom_gcode_per_print_z) {
        std::vector<std::pair<ColorRGBA, std::pair<double, double>>> ret;
        ret.reserve(custom_gcode_per_print_z.size());
        for (const auto& item : custom_gcode_per_print_z) {
            if (extruder_id + 1 != static_cast<unsigned char>(item.extruder))
                continue;
            if (item.type != ColorChange)
                continue;
            const std::vector<double> zs = m_layers.get_zs();
            auto lower_b = std::lower_bound(zs.begin(), zs.end(), item.print_z - Slic3r::DoubleSlider::epsilon());
            if (lower_b == zs.end())
                continue;
            const double current_z = *lower_b;
            const double previous_z = (lower_b == zs.begin()) ? 0.0 : *(--lower_b);
            // to avoid duplicate values, check adding values
            if (ret.empty() || !(ret.back().second.first == previous_z && ret.back().second.second == current_z)) {
                ColorRGBA color;
                decode_color(item.color, color);
                ret.push_back({ color, { previous_z, current_z } });
            }
        }
        return ret;
    };
    auto upto_label = [](double z) {
        char buf[64];
        ::sprintf(buf, "%.2f", z);
        return _u8L("up to") + " " + std::string(buf) + " " + _u8L("mm");
    };
    auto above_label = [](double z) {
        char buf[64];
        ::sprintf(buf, "%.2f", z);
        return _u8L("above") + " " + std::string(buf) + " " + _u8L("mm");
    };
    auto fromto_label = [](double z1, double z2) {
        char buf1[64];
        ::sprintf(buf1, "%.2f", z1);
        char buf2[64];
        ::sprintf(buf2, "%.2f", z2);
        return _u8L("from") + " " + std::string(buf1) + " " + _u8L("to") + " " + std::string(buf2) + " " + _u8L("mm");
    };
    auto role_time_and_percent = [time_mode](GCodeExtrusionRole role) {
        auto it = std::find_if(time_mode.roles_times.begin(), time_mode.roles_times.end(), [role](const std::pair<GCodeExtrusionRole, float>& item) { return role == item.first; });
        return (it != time_mode.roles_times.end()) ? std::make_pair(it->second, it->second / time_mode.time) : std::make_pair(0.0f, 0.0f);
    };
    auto used_filament_per_role = [this, imperial_units](GCodeExtrusionRole role) {
        auto it = m_print_statistics.used_filaments_per_role.find(role);
        if (it == m_print_statistics.used_filaments_per_role.end())
            return std::make_pair(0.0, 0.0);
        double koef = imperial_units ? 1000.0 / ObjectManipulation::in_to_mm : 1.0;
        return std::make_pair(it->second.first * koef, it->second.second);
    };
    // data used to properly align items in columns when showing time
    std::array<float, 4> offsets = { 0.0f, 0.0f, 0.0f, 0.0f };
    std::vector<std::string> labels;
    std::vector<std::string> times;
    std::vector<float> percents;
    std::vector<double> used_filaments_m;
    std::vector<double> used_filaments_g;
    float max_time_percent = 0.0f;
    if (m_view_type == EViewType::FeatureType) {
        // calculate offsets to align time/percentage data
        for (GCodeExtrusionRole role : m_roles) {
            assert(role < GCodeExtrusionRole::Count);
            if (role < GCodeExtrusionRole::Count) {
                labels.push_back(_u8L(gcode_extrusion_role_to_string(role)));
                auto [time, percent] = role_time_and_percent(role);
                times.push_back((time > 0.0f) ? short_time_ui(get_time_dhms(time)) : "");
                percents.push_back(percent);
                max_time_percent = std::max(max_time_percent, percent);
                auto [used_filament_m, used_filament_g] = used_filament_per_role(role);
                used_filaments_m.push_back(used_filament_m);
                used_filaments_g.push_back(used_filament_g);
            }
        }
        std::string longest_percentage_string;
        for (double item : percents) {
            char buffer[64];
            ::sprintf(buffer, "%.2f %%", item);
            if (::strlen(buffer) > longest_percentage_string.length())
                longest_percentage_string = buffer;
        }
        longest_percentage_string += "            ";
        if (_u8L("Percentage").length() > longest_percentage_string.length())
            longest_percentage_string = _u8L("Percentage");
        std::string longest_used_filament_string;
        for (double item : used_filaments_m) {
            char buffer[64];
            ::sprintf(buffer, imperial_units ? "%.2f in" : "%.2f m", item);
            if (::strlen(buffer) > longest_used_filament_string.length())
                longest_used_filament_string = buffer;
        }
        offsets = calculate_offsets(labels, times, { _u8L("Feature type"), _u8L("Time"), longest_percentage_string, longest_used_filament_string }, icon_size);
    }
    // get used filament (meters and grams) from used volume in respect to the active extruder
    auto get_used_filament_from_volume = [this, imperial_units](double volume, int extruder_id) {
        double koef = imperial_units ? 1.0 / ObjectManipulation::in_to_mm : 0.001;
        std::pair<double, double> ret = { koef * volume / (PI * sqr(0.5 * m_filament_diameters[extruder_id])),
                                          volume * m_filament_densities[extruder_id] * 0.001 };
        return ret;
    };
    if (m_view_type == EViewType::Tool) {
        // calculate used filaments data
        used_filaments_m = std::vector<double>(m_extruders_count, 0.0);
        used_filaments_g = std::vector<double>(m_extruders_count, 0.0);
        for (size_t extruder_id : m_extruder_ids) {
            if (m_print_statistics.volumes_per_extruder.find(extruder_id) == m_print_statistics.volumes_per_extruder.end())
                continue;
            double volume = m_print_statistics.volumes_per_extruder.at(extruder_id);
            auto [used_filament_m, used_filament_g] = get_used_filament_from_volume(volume, extruder_id);
            used_filaments_m[extruder_id] = used_filament_m;
            used_filaments_g[extruder_id] = used_filament_g;
        }
        std::string longest_used_filament_string;
        for (double item : used_filaments_m) {
            char buffer[64];
            ::sprintf(buffer, imperial_units ? "%.2f in" : "%.2f m", item);
            if (::strlen(buffer) > longest_used_filament_string.length())
                longest_used_filament_string = buffer;
        }
        offsets = calculate_offsets(labels, times, { "Extruder NNN", longest_used_filament_string }, icon_size);
    }
    // selection section
    bool view_type_changed = false;
    int old_view_type = static_cast<int>(get_view_type());
    int view_type = old_view_type;
    ImGui::PushStyleColor(ImGuiCol_FrameBg, { 0.1f, 0.1f, 0.1f, 0.8f });
    ImGui::PushStyleColor(ImGuiCol_FrameBgHovered, { 0.2f, 0.2f, 0.2f, 0.8f });
    imgui.combo(std::string(), { _u8L("Feature type"),
                      _u8L("Height (mm)"),
                      _u8L("Width (mm)"),
                      _u8L("Speed (mm/s)"),
                      _u8L("Fan speed (%)"),
                      _u8L("Temperature (C)"),
                      _u8L("Volumetric flow rate (mm/s)"),
                      _u8L("Layer time (linear)"),
                      _u8L("Layer time (logarithmic)"),
                      _u8L("Tool"),
                      _u8L("Color Print") }, view_type, ImGuiComboFlags_HeightLargest, 0.0f, -1.0f);
    ImGui::PopStyleColor(2);
    if (old_view_type != view_type) {
        set_view_type(static_cast<EViewType>(view_type));
        wxGetApp().plater()->set_keep_current_preview_type(true);
        wxGetApp().plater()->refresh_print();
        view_type_changed = true;
    }
    // extrusion paths section -> title
    if (m_view_type == EViewType::FeatureType)
        append_headers({ "", _u8L("Time"), _u8L("Percentage"), _u8L("Used filament") }, offsets);
    else if (m_view_type == EViewType::Tool)
        append_headers({ "", _u8L("Used filament"), "", ""}, offsets);
    else
        ImGui::Separator();
    if (!view_type_changed) {
        // extrusion paths section -> items
        switch (m_view_type)
        {
        case EViewType::FeatureType:
        {
            max_time_percent = std::max(max_time_percent, time_mode.travel_time / time_mode.time);
            for (size_t i = 0; i < m_roles.size(); ++i) {
                GCodeExtrusionRole role = m_roles[i];
                if (role >= GCodeExtrusionRole::Count)
                    continue;
                const bool visible = is_visible(role);
                append_item(EItemType::Rect, Extrusion_Role_Colors[static_cast<unsigned int>(role)], labels[i],
                    visible, times[i], percents[i], max_time_percent, offsets, used_filaments_m[i], used_filaments_g[i], [this, role, visible]() {
                        m_extrusions.role_visibility_flags = visible ? m_extrusions.role_visibility_flags & ~(1 << int(role)) : m_extrusions.role_visibility_flags | (1 << int(role));
                        // update buffers' render paths
                        refresh_render_paths(false, false);
                        wxGetApp().plater()->update_preview_moves_slider();
                        wxGetApp().plater()->get_current_canvas3D()->set_as_dirty();
                    }
                );
            }
            if (m_buffers[buffer_id(EMoveType::Travel)].visible)
                append_item(EItemType::Line, Travel_Colors[0], _u8L("Travel"), true, short_time_ui(get_time_dhms(time_mode.travel_time)),
                    time_mode.travel_time / time_mode.time, max_time_percent, offsets, 0.0f, 0.0f);
            break;
        }
        case EViewType::Height:               { append_range(m_extrusions.ranges.height, 3); break; }
        case EViewType::Width:                { append_range(m_extrusions.ranges.width, 3); break; }
        case EViewType::Feedrate:             { append_range(m_extrusions.ranges.feedrate, 1); break; }
        case EViewType::FanSpeed:             { append_range(m_extrusions.ranges.fan_speed, 0); break; }
        case EViewType::Temperature:          { append_range(m_extrusions.ranges.temperature, 0); break; }
        case EViewType::VolumetricRate:       { append_range(m_extrusions.ranges.volumetric_rate, 3); break; }
        case EViewType::LayerTimeLinear:      { append_time_range(m_extrusions.ranges.layer_time[static_cast<size_t>(m_time_estimate_mode)], Extrusions::Range::EType::Linear); break; }
        case EViewType::LayerTimeLogarithmic: { append_time_range(m_extrusions.ranges.layer_time[static_cast<size_t>(m_time_estimate_mode)], Extrusions::Range::EType::Logarithmic); break; }
        case EViewType::Tool:                 {
            // shows only extruders actually used
            for (unsigned char extruder_id : m_extruder_ids) {
                if (used_filaments_m[extruder_id] > 0.0 && used_filaments_g[extruder_id] > 0.0)
                    append_item(EItemType::Rect, m_tool_colors[extruder_id], _u8L("Extruder") + " " + std::to_string(extruder_id + 1),
                        true, "", 0.0f, 0.0f, offsets, used_filaments_m[extruder_id], used_filaments_g[extruder_id]);
            }
            break;
        }
        case EViewType::ColorPrint:
        {
            const std::vector<CustomGCode::Item>& custom_gcode_per_print_z = wxGetApp().is_editor() ? wxGetApp().plater()->model().custom_gcode_per_print_z.gcodes : m_custom_gcode_per_print_z;
            size_t total_items = 1;
            for (unsigned char i : m_extruder_ids) {
                total_items += color_print_ranges(i, custom_gcode_per_print_z).size();
            }
            const bool need_scrollable = static_cast<float>(total_items) * icon_size + (static_cast<float>(total_items) - 1.0f) * ImGui::GetStyle().ItemSpacing.y > child_height;
            // add scrollable region, if needed
            if (need_scrollable)
                ImGui::BeginChild("color_prints", { -1.0f, child_height }, false);
            if (m_extruders_count == 1) { // single extruder use case
                const std::vector<std::pair<ColorRGBA, std::pair<double, double>>> cp_values = color_print_ranges(0, custom_gcode_per_print_z);
                const int items_cnt = static_cast<int>(cp_values.size());
                if (items_cnt == 0)  // There are no color changes, but there are some pause print or custom Gcode
                    append_item(EItemType::Rect, m_tool_colors.front(), _u8L("Default color"));
                else {
                    for (int i = items_cnt; i >= 0; --i) {
                        // create label for color change item
                        if (i == 0) {
                            append_item(EItemType::Rect, m_tool_colors[0], upto_label(cp_values.front().second.first));
                            break;
                        }
                        else if (i == items_cnt) {
                            append_item(EItemType::Rect, cp_values[i - 1].first, above_label(cp_values[i - 1].second.second));
                            continue;
                        }
                        append_item(EItemType::Rect, cp_values[i - 1].first, fromto_label(cp_values[i - 1].second.second, cp_values[i].second.first));
                    }
                }
            }
            else { // multi extruder use case
                // shows only extruders actually used
                for (unsigned char i : m_extruder_ids) {
                    const std::vector<std::pair<ColorRGBA, std::pair<double, double>>> cp_values = color_print_ranges(i, custom_gcode_per_print_z);
                    const int items_cnt = static_cast<int>(cp_values.size());
                    if (items_cnt == 0)
                        // There are no color changes, but there are some pause print or custom Gcode
                        append_item(EItemType::Rect, m_tool_colors[i], _u8L("Extruder") + " " + std::to_string(i + 1) + " " + _u8L("default color"));
                    else {
                        for (int j = items_cnt; j >= 0; --j) {
                            // create label for color change item
                            std::string label = _u8L("Extruder") + " " + std::to_string(i + 1);
                            if (j == 0) {
                                label += " " + upto_label(cp_values.front().second.first);
                                append_item(EItemType::Rect, m_tool_colors[i], label);
                                break;
                            }
                            else if (j == items_cnt) {
                                label += " " + above_label(cp_values[j - 1].second.second);
                                append_item(EItemType::Rect, cp_values[j - 1].first, label);
                                continue;
                            }
                            label += " " + fromto_label(cp_values[j - 1].second.second, cp_values[j].second.first);
                            append_item(EItemType::Rect, cp_values[j - 1].first, label);
                        }
                    }
                }
            }
            if (need_scrollable)
                ImGui::EndChild();
            break;
        }
        default: { break; }
        }
    }
    // partial estimated printing time section
    if (m_view_type == EViewType::ColorPrint) {
        using Times = std::pair<float, float>;
        using TimesList = std::vector<std::pair<CustomGCode::Type, Times>>;
        // helper structure containig the data needed to render the time items
        struct PartialTime
        {
            enum class EType : unsigned char
            {
                Print,
                ColorChange,
                Pause
            };
            EType type;
            int extruder_id;
            ColorRGBA color1;
            ColorRGBA color2;
            Times times;
            std::pair<double, double> used_filament{ 0.0f, 0.0f };
        };
        using PartialTimes = std::vector<PartialTime>;
        auto generate_partial_times = [this, get_used_filament_from_volume](const TimesList& times, const std::vector<double>& used_filaments) {
            PartialTimes items;
            std::vector<CustomGCode::Item> custom_gcode_per_print_z = wxGetApp().is_editor() ? wxGetApp().plater()->model().custom_gcode_per_print_z.gcodes : m_custom_gcode_per_print_z;
            std::vector<ColorRGBA> last_color(m_extruders_count);
            for (size_t i = 0; i < m_extruders_count; ++i) {
                last_color[i] = m_tool_colors[i];
            }
            int last_extruder_id = 1;
            int color_change_idx = 0;
            for (const auto& time_rec : times) {
                switch (time_rec.first)
                {
                case CustomGCode::PausePrint: {
                    auto it = std::find_if(custom_gcode_per_print_z.begin(), custom_gcode_per_print_z.end(), [time_rec](const CustomGCode::Item& item) { return item.type == time_rec.first; });
                    if (it != custom_gcode_per_print_z.end()) {
                        items.push_back({ PartialTime::EType::Print, it->extruder, last_color[it->extruder - 1], ColorRGBA::BLACK(), time_rec.second });
                        items.push_back({ PartialTime::EType::Pause, it->extruder, ColorRGBA::BLACK(), ColorRGBA::BLACK(), time_rec.second });
                        custom_gcode_per_print_z.erase(it);
                    }
                    break;
                }
                case CustomGCode::ColorChange: {
                    auto it = std::find_if(custom_gcode_per_print_z.begin(), custom_gcode_per_print_z.end(), [time_rec](const CustomGCode::Item& item) { return item.type == time_rec.first; });
                    if (it != custom_gcode_per_print_z.end()) {
                        items.push_back({ PartialTime::EType::Print, it->extruder, last_color[it->extruder - 1], ColorRGBA::BLACK(), time_rec.second, get_used_filament_from_volume(used_filaments[color_change_idx++], it->extruder - 1) });
                        ColorRGBA color;
                        decode_color(it->color, color);
                        items.push_back({ PartialTime::EType::ColorChange, it->extruder, last_color[it->extruder - 1], color, time_rec.second });
                        last_color[it->extruder - 1] = color;
                        last_extruder_id = it->extruder;
                        custom_gcode_per_print_z.erase(it);
                    }
                    else
                        items.push_back({ PartialTime::EType::Print, last_extruder_id, last_color[last_extruder_id - 1], ColorRGBA::BLACK(), time_rec.second, get_used_filament_from_volume(used_filaments[color_change_idx++], last_extruder_id - 1) });
                    break;
                }
                default: { break; }
                }
            }
            return items;
        };
        auto append_color_change = [&imgui](const ColorRGBA& color1, const ColorRGBA& color2, const std::array<float, 4>& offsets, const Times& times) {
            imgui.text(_u8L("Color change"));
            ImGui::SameLine();
            float icon_size = ImGui::GetTextLineHeight();
            ImDrawList* draw_list = ImGui::GetWindowDrawList();
            ImVec2 pos = ImGui::GetCursorScreenPos();
            pos.x -= 0.5f * ImGui::GetStyle().ItemSpacing.x;
            draw_list->AddRectFilled({ pos.x + 1.0f, pos.y + 1.0f }, { pos.x + icon_size - 1.0f, pos.y + icon_size - 1.0f },
                ImGuiWrapper::to_ImU32(color1));
            pos.x += icon_size;
            draw_list->AddRectFilled({ pos.x + 1.0f, pos.y + 1.0f }, { pos.x + icon_size - 1.0f, pos.y + icon_size - 1.0f },
                ImGuiWrapper::to_ImU32(color2));
            ImGui::SameLine(offsets[0]);
            imgui.text(short_time_ui(get_time_dhms(times.second - times.first)));
        };
        auto append_print = [&imgui, imperial_units](const ColorRGBA& color, const std::array<float, 4>& offsets, const Times& times, std::pair<double, double> used_filament) {
            imgui.text(_u8L("Print"));
            ImGui::SameLine();
            float icon_size = ImGui::GetTextLineHeight();
            ImDrawList* draw_list = ImGui::GetWindowDrawList();
            ImVec2 pos = ImGui::GetCursorScreenPos();
            pos.x -= 0.5f * ImGui::GetStyle().ItemSpacing.x;
            draw_list->AddRectFilled({ pos.x + 1.0f, pos.y + 1.0f }, { pos.x + icon_size - 1.0f, pos.y + icon_size - 1.0f },
                ImGuiWrapper::to_ImU32(color));
            ImGui::SameLine(offsets[0]);
            imgui.text(short_time_ui(get_time_dhms(times.second)));
            ImGui::SameLine(offsets[1]);
            imgui.text(short_time_ui(get_time_dhms(times.first)));
            if (used_filament.first > 0.0f) {
                char buffer[64];
                ImGui::SameLine(offsets[2]);
                ::sprintf(buffer, imperial_units ? "%.2f in" : "%.2f m", used_filament.first);
                imgui.text(buffer);
                ImGui::SameLine(offsets[3]);
                ::sprintf(buffer, "%.2f g", used_filament.second);
                imgui.text(buffer);
            }
        };
        PartialTimes partial_times = generate_partial_times(time_mode.custom_gcode_times, m_print_statistics.volumes_per_color_change);
        if (!partial_times.empty()) {
            labels.clear();
            times.clear();
            for (const PartialTime& item : partial_times) {
                switch (item.type)
                {
                case PartialTime::EType::Print:       { labels.push_back(_u8L("Print")); break; }
                case PartialTime::EType::Pause:       { labels.push_back(_u8L("Pause")); break; }
                case PartialTime::EType::ColorChange: { labels.push_back(_u8L("Color change")); break; }
                }
                times.push_back(short_time_ui(get_time_dhms(item.times.second)));
            }
            std::string longest_used_filament_string;
            for (const PartialTime& item : partial_times) {
                if (item.used_filament.first > 0.0f) {
                    char buffer[64];
                    ::sprintf(buffer, imperial_units ? "%.2f in" : "%.2f m", item.used_filament.first);
                    if (::strlen(buffer) > longest_used_filament_string.length())
                        longest_used_filament_string = buffer;
                }
            }
            offsets = calculate_offsets(labels, times, { _u8L("Event"), _u8L("Remaining time"), _u8L("Duration"), longest_used_filament_string }, 2.0f * icon_size);
            ImGui::Spacing();
            append_headers({ _u8L("Event"), _u8L("Remaining time"), _u8L("Duration"), _u8L("Used filament") }, offsets);
            const bool need_scrollable = static_cast<float>(partial_times.size()) * icon_size + (static_cast<float>(partial_times.size()) - 1.0f) * ImGui::GetStyle().ItemSpacing.y > child_height;
            if (need_scrollable)
                // add scrollable region
                ImGui::BeginChild("events", { -1.0f, child_height }, false);
            for (const PartialTime& item : partial_times) {
                switch (item.type)
                {
                case PartialTime::EType::Print: {
                    append_print(item.color1, offsets, item.times, item.used_filament);
                    break;
                }
                case PartialTime::EType::Pause: {
                    imgui.text(_u8L("Pause"));
                    ImGui::SameLine(offsets[0]);
                    imgui.text(short_time_ui(get_time_dhms(item.times.second - item.times.first)));
                    break;
                }
                case PartialTime::EType::ColorChange: {
                    append_color_change(item.color1, item.color2, offsets, item.times);
                    break;
                }
                }
            }
            if (need_scrollable)
                ImGui::EndChild();
        }
    }
    auto add_strings_row_to_table = [&imgui](const std::string& col_1, const ImVec4& col_1_color, const std::string& col_2, const ImVec4& col_2_color) {
        ImGui::TableNextRow();
        ImGui::TableSetColumnIndex(0);
        imgui.text_colored(col_1_color, col_1.c_str());
        ImGui::TableSetColumnIndex(1);
        imgui.text_colored(col_2_color, col_2.c_str());
    };
    // settings section
    bool has_settings = false;
    has_settings |= !m_settings_ids.print.empty();
    has_settings |= !m_settings_ids.printer.empty();
    bool has_filament_settings = true;
    has_filament_settings &= !m_settings_ids.filament.empty();
    for (const std::string& fs : m_settings_ids.filament) {
        has_filament_settings &= !fs.empty();
    }
    has_settings |= has_filament_settings;
    bool show_settings = wxGetApp().is_gcode_viewer();
    show_settings &= (m_view_type == EViewType::FeatureType || m_view_type == EViewType::Tool);
    show_settings &= has_settings;
    if (show_settings) {
        ImGui::Spacing();
        imgui.title(_u8L("Settings"));
        auto trim_text_if_needed = [](const std::string& txt) {
            const float max_length = 250.0f;
            const float length = ImGui::CalcTextSize(txt.c_str()).x;
            if (length > max_length) {
                const size_t new_len = txt.length() * max_length / length;
                return txt.substr(0, new_len) + "...";
            }
            return txt;
        };
        if (ImGui::BeginTable("Settings", 2)) {
            if (!m_settings_ids.printer.empty())
                add_strings_row_to_table(_u8L("Printer") + ":", ImGuiWrapper::COL_ORANGE_LIGHT,
                    trim_text_if_needed(m_settings_ids.printer), ImGuiWrapper::to_ImVec4(ColorRGBA::WHITE()));
            if (!m_settings_ids.print.empty())
                add_strings_row_to_table(_u8L("Print settings") + ":", ImGuiWrapper::COL_ORANGE_LIGHT,
                    trim_text_if_needed(m_settings_ids.print), ImGuiWrapper::to_ImVec4(ColorRGBA::WHITE()));
            if (!m_settings_ids.filament.empty()) {
                for (unsigned char i : m_extruder_ids) {
                    if (i < static_cast<unsigned char>(m_settings_ids.filament.size()) && !m_settings_ids.filament[i].empty()) {
                        std::string txt = _u8L("Filament");
                        txt += (m_extruder_ids.size() == 1) ? ":" : " " + std::to_string(i + 1);
                        add_strings_row_to_table(txt, ImGuiWrapper::COL_ORANGE_LIGHT,
                            trim_text_if_needed(m_settings_ids.filament[i]), ImGuiWrapper::to_ImVec4(ColorRGBA::WHITE()));
                    }
                }
            }
            ImGui::EndTable();
        }
    }
    if (m_view_type == EViewType::Width || m_view_type == EViewType::VolumetricRate) {
      const auto custom_it = std::find(m_roles.begin(), m_roles.end(), GCodeExtrusionRole::Custom);
      if (custom_it != m_roles.end()) {
          const bool custom_visible = is_visible(GCodeExtrusionRole::Custom);
          const wxString btn_text = custom_visible ? _L("Hide Custom G-code") : _L("Show Custom G-code");
          ImGui::Separator();
          if (imgui.button(btn_text, ImVec2(-1.0f, 0.0f), true)) {
              m_extrusions.role_visibility_flags = custom_visible ? m_extrusions.role_visibility_flags & ~(1 << int(GCodeExtrusionRole::Custom)) :
                  m_extrusions.role_visibility_flags | (1 << int(GCodeExtrusionRole::Custom));
              wxGetApp().plater()->refresh_print();
          }
        }
    }
    // total estimated printing time section
    if (show_estimated_time) {
        ImGui::Spacing();
        std::string time_title = _u8L("Estimated printing times");
        auto can_show_mode_button = [this](PrintEstimatedStatistics::ETimeMode mode) {
            bool show = false;
            if (m_print_statistics.modes.size() > 1 && m_print_statistics.modes[static_cast<size_t>(mode)].roles_times.size() > 0) {
                for (size_t i = 0; i < m_print_statistics.modes.size(); ++i) {
                    if (i != static_cast<size_t>(mode) &&
                        m_print_statistics.modes[i].time > 0.0f &&
                        short_time(get_time_dhms(m_print_statistics.modes[static_cast<size_t>(mode)].time)) != short_time(get_time_dhms(m_print_statistics.modes[i].time))) {
                        show = true;
                        break;
                    }
                }
            }
            return show;
        };
        if (can_show_mode_button(m_time_estimate_mode)) {
            switch (m_time_estimate_mode)
            {
            case PrintEstimatedStatistics::ETimeMode::Normal:  { time_title += " [" + _u8L("Normal mode") + "]"; break; }
            case PrintEstimatedStatistics::ETimeMode::Stealth: { time_title += " [" + _u8L("Stealth mode") + "]"; break; }
            default: { assert(false); break; }
            }
        }
        imgui.title(time_title + ":");
        if (ImGui::BeginTable("Times", 2)) {
            if (!time_mode.layers_times.empty()) {
                add_strings_row_to_table(_u8L("First layer") + ":", ImGuiWrapper::COL_ORANGE_LIGHT,
                    short_time_ui(get_time_dhms(time_mode.layers_times.front())), ImGuiWrapper::to_ImVec4(ColorRGBA::WHITE()));
            }
            add_strings_row_to_table(_u8L("Total") + ":", ImGuiWrapper::COL_ORANGE_LIGHT,
                short_time_ui(get_time_dhms(time_mode.time)), ImGuiWrapper::to_ImVec4(ColorRGBA::WHITE()));
            ImGui::EndTable();
        }
        auto show_mode_button = [this, &imgui, can_show_mode_button](const wxString& label, PrintEstimatedStatistics::ETimeMode mode) {
            if (can_show_mode_button(mode)) {
                if (imgui.button(label)) {
                    m_time_estimate_mode = mode;
                    if (m_view_type == EViewType::LayerTimeLinear || m_view_type == EViewType::LayerTimeLogarithmic)
                        refresh_render_paths(false, false);
                    imgui.set_requires_extra_frame();
                }
            }
        };
        switch (m_time_estimate_mode) {
        case PrintEstimatedStatistics::ETimeMode::Normal: {
            show_mode_button(_L("Show stealth mode"), PrintEstimatedStatistics::ETimeMode::Stealth);
            break;
        }
        case PrintEstimatedStatistics::ETimeMode::Stealth: {
            show_mode_button(_L("Show normal mode"), PrintEstimatedStatistics::ETimeMode::Normal);
            break;
        }
        default : { assert(false); break; }
        }
    }
    // toolbar section
    auto toggle_button = [this, &imgui, icon_size](Preview::OptionType type, const std::string& name,
        std::function<void(ImGuiWindow& window, const ImVec2& pos, float size)> draw_callback) {
            auto is_flag_set = [](unsigned int flags, unsigned int flag) {
            return (flags & (1 << flag)) != 0;
        };
        auto set_flag = [](unsigned int flags, unsigned int flag, bool active) {
            return active ? (flags | (1 << flag)) : (flags & ~(1 << flag));
        };
        unsigned int flags = get_options_visibility_flags();
        unsigned int flag = static_cast<unsigned int>(type);
        bool active = is_flag_set(flags, flag);
        if (imgui.draw_radio_button(name, 1.5f * icon_size, active, draw_callback)) {
            unsigned int new_flags = set_flag(flags, flag, !active);
            set_options_visibility_from_flags(new_flags);
            const unsigned int diff_flags = flags ^ new_flags;
            if (m_view_type == GCodeViewer::EViewType::Feedrate && is_flag_set(diff_flags, static_cast<unsigned int>(Preview::OptionType::Travel)))
                wxGetApp().plater()->refresh_print();
            else {
                bool keep_first = m_sequential_view.current.first != m_sequential_view.global.first;
                bool keep_last = m_sequential_view.current.last != m_sequential_view.global.last;
                wxGetApp().plater()->get_current_canvas3D()->refresh_gcode_preview_render_paths(keep_first, keep_last);
            }
            wxGetApp().plater()->update_preview_moves_slider();
        }
        if (ImGui::IsItemHovered()) {
            ImGui::PushStyleColor(ImGuiCol_PopupBg, ImGuiWrapper::COL_WINDOW_BACKGROUND);
            ImGui::BeginTooltip();
            imgui.text(name);
            ImGui::EndTooltip();
            ImGui::PopStyleColor();
        }
    };
    ImGui::Spacing();
    ImGui::Separator();
    ImGui::Spacing();
    ImGui::Spacing();
    toggle_button(Preview::OptionType::Travel, _u8L("Travel"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendTravel);
        });
    ImGui::SameLine();
    toggle_button(Preview::OptionType::Wipe, _u8L("Wipe"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendWipe);
        });
    ImGui::SameLine();
    toggle_button(Preview::OptionType::Retractions, _u8L("Retractions"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendRetract);
        });
    ImGui::SameLine();
    toggle_button(Preview::OptionType::Unretractions, _u8L("Deretractions"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendDeretract);
        });
    ImGui::SameLine();
    toggle_button(Preview::OptionType::Seams, _u8L("Seams"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendSeams);
        });
    ImGui::SameLine();
    toggle_button(Preview::OptionType::ToolChanges, _u8L("Tool changes"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendToolChanges);
        });
    ImGui::SameLine();
    toggle_button(Preview::OptionType::ColorChanges, _u8L("Color changes"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendColorChanges);
        });
    ImGui::SameLine();
    toggle_button(Preview::OptionType::PausePrints, _u8L("Print pauses"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendPausePrints);
        });
    ImGui::SameLine();
    toggle_button(Preview::OptionType::CustomGCodes, _u8L("Custom G-codes"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendCustomGCodes);
        });
    ImGui::SameLine();
    toggle_button(Preview::OptionType::CenterOfGravity, _u8L("Center of gravity"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendCOG);
        });
    ImGui::SameLine();
    if (!wxGetApp().is_gcode_viewer()) {
        toggle_button(Preview::OptionType::Shells, _u8L("Shells"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
            imgui.draw_icon(window, pos, size, ImGui::LegendShells);
            });
        ImGui::SameLine();
    }
    toggle_button(Preview::OptionType::ToolMarker, _u8L("Tool marker"), [&imgui](ImGuiWindow& window, const ImVec2& pos, float size) {
        imgui.draw_icon(window, pos, size, ImGui::LegendToolMarker);
        });
    bool size_dirty = !ImGui::GetCurrentWindow()->ScrollbarY && ImGui::CalcWindowNextAutoFitSize(ImGui::GetCurrentWindow()).x != ImGui::GetWindowWidth();
    if (m_legend_resizer.dirty || size_dirty != m_legend_resizer.dirty) {
        wxGetApp().plater()->get_current_canvas3D()->set_as_dirty();
        wxGetApp().plater()->get_current_canvas3D()->request_extra_frame();
    }
    m_legend_resizer.dirty = size_dirty;
    legend_height = ImGui::GetWindowHeight();
    imgui.end();
    ImGui::PopStyleVar();
}
References _CTX_utf8, _L, _u8L, Slic3r::GUI::add_strings_row_to_table(), ImDrawList::AddCircleFilled(), ImDrawList::AddLine(), ImDrawList::AddNgonFilled(), ImDrawList::AddRectFilled(), Slic3r::GUI::ImGuiWrapper::begin(), ImGui::BeginChild(), ImGui::BeginTable(), ImGui::BeginTooltip(), Slic3r::ColorRGBA::BLACK(), Slic3r::GUI::buffer_id(), Slic3r::GUI::ImGuiWrapper::button(), ImGui::CalcTextSize(), ImGui::CalcWindowNextAutoFitSize(), Slic3r::GUI::Preview::CenterOfGravity, Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, Slic3r::GUI::ImGuiWrapper::COL_WINDOW_BACKGROUND, Slic3r::CustomGCode::ColorChange, Slic3r::GUI::Preview::ColorChanges, ColorPrint, Slic3r::GUI::ImGuiWrapper::combo(), Slic3r::Count, Slic3r::GUI::GCodeViewer::SequentialView::current, Slic3r::Custom, Slic3r::PrintEstimatedStatistics::Mode::custom_gcode_times, Slic3r::GUI::Preview::CustomGCodes, Slic3r::decode_color(), Slic3r::GUI::GCodeViewer::LegendResizer::dirty, Slic3r::GUI::ImGuiWrapper::draw_icon(), Slic3r::GUI::ImGuiWrapper::draw_radio_button(), ImGui::Dummy(), Slic3r::GUI::ImGuiWrapper::end(), ImGui::EndChild(), ImGui::EndTable(), ImGui::EndTooltip(), Slic3r::DoubleSlider::epsilon(), exp(), Extrusion_Role_Colors, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::fan_speed, FanSpeed, FeatureType, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::feedrate, Feedrate, Slic3r::GCodeProcessorResult::SettingsIds::filament, Slic3r::GUI::GCodeViewer::SequentialView::Endpoints::first, Slic3r::GUI::format(), Slic3r::gcode_extrusion_role_to_string(), Slic3r::GUI::Size::get_height(), get_options_visibility_flags(), Slic3r::get_time_dhms(), get_view_type(), Slic3r::GUI::GCodeViewer::Layers::get_zs(), ImGui::GetColorU32(), ImGui::GetCurrentWindow(), ImGui::GetCursorScreenPos(), ImGui::GetStyle(), ImGui::GetTextLineHeight(), ImGui::GetWindowDrawList(), ImGui::GetWindowHeight(), ImGui::GetWindowWidth(), Slic3r::GUI::GCodeViewer::SequentialView::global, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::height, Height, Slic3r::Hexagon, ImGuiCol_FrameBg, ImGuiCol_FrameBgHovered, ImGuiCol_PopupBg, ImGuiComboFlags_HeightLargest, ImGuiCond_Always, ImGuiStyleVar_Alpha, ImGuiStyleVar_WindowRounding, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, Slic3r::GUI::ObjectManipulation::in_to_mm, is_visible(), ImGui::IsItemHovered(), ImGuiStyle::ItemSpacing, L_CONTEXT, Slic3r::GUI::GCodeViewer::SequentialView::Endpoints::last, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::layer_time, Slic3r::PrintEstimatedStatistics::Mode::layers_times, LayerTimeLinear, LayerTimeLogarithmic, ImGui::LegendCOG, ImGui::LegendColorChanges, ImGui::LegendCustomGCodes, ImGui::LegendDeretract, ImGui::LegendPausePrints, ImGui::LegendRetract, ImGui::LegendSeams, ImGui::LegendShells, ImGui::LegendToolChanges, ImGui::LegendToolMarker, ImGui::LegendTravel, ImGui::LegendWipe, Slic3r::length(), Slic3r::GUI::GCodeViewer::Extrusions::Range::Linear, log(), Slic3r::GUI::GCodeViewer::Extrusions::Range::Logarithmic, m_buffers, m_custom_gcode_per_print_z, m_extruder_ids, m_extruders_count, m_extrusions, m_filament_densities, m_filament_diameters, m_layers, m_legend_enabled, m_legend_resizer, m_print_statistics, m_roles, m_sequential_view, m_settings_ids, m_time_estimate_mode, m_tool_colors, m_view_type, ImGui::MenuItem(), Slic3r::PrintEstimatedStatistics::modes, Slic3r::PrintEstimatedStatistics::Normal, Slic3r::CustomGCode::PausePrint, Slic3r::GUI::Preview::PausePrints, PI, ImGui::PopStyleColor(), ImGui::PopStyleVar(), Slic3r::GCodeProcessorResult::SettingsIds::print, Slic3r::GCodeProcessorResult::SettingsIds::printer, ImGui::PushStyleColor(), ImGui::PushStyleVar(), Slic3r::range(), Range_Colors, Slic3r::GUI::GCodeViewer::Extrusions::ranges, refresh_render_paths(), Slic3r::GUI::Preview::Retractions, Slic3r::GUI::GCodeViewer::Extrusions::role_visibility_flags, Slic3r::PrintEstimatedStatistics::Mode::roles_times, ImGui::SameLine(), ImGuiWindow::ScrollbarY, Slic3r::GUI::Preview::Seams, ImGui::Separator(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), set_options_visibility_from_flags(), Slic3r::GUI::ImGuiWrapper::set_requires_extra_frame(), set_view_type(), ImGui::SetNextWindowBgAlpha(), ImGui::SetNextWindowSizeConstraints(), Slic3r::GUI::Preview::Shells, Slic3r::short_time(), Slic3r::short_time_ui(), ImGui::Spacing(), Slic3r::sqr(), Slic3r::PrintEstimatedStatistics::Stealth, style, ImGui::TableNextRow(), ImGui::TableSetColumnIndex(), Slic3r::GUI::GCodeViewer::Extrusions::Ranges::temperature, Temperature, Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), ImGui::TextUnformatted(), Slic3r::PrintEstimatedStatistics::Mode::time, Slic3r::GUI::ImGuiWrapper::title(), Slic3r::GUI::ImGuiWrapper::to_ImU32(), Slic3r::GUI::ImGuiWrapper::to_ImVec4(), Tool, Slic3r::GUI::Preview::ToolChanges, Slic3r::GUI::Preview::ToolMarker, Slic3r::Travel, Slic3r::GUI::Preview::Travel, Travel_Colors, Slic3r::PrintEstimatedStatistics::Mode::travel_time, Slic3r::GUI::Preview::Unretractions, Slic3r::PrintEstimatedStatistics::used_filaments_per_role, void(), Slic3r::PrintEstimatedStatistics::volumes_per_color_change, Slic3r::PrintEstimatedStatistics::volumes_per_extruder, Slic3r::GUI::GCodeViewer::Extrusions::Ranges::volumetric_rate, VolumetricRate, Slic3r::ColorRGBA::WHITE(), Slic3r::GUI::GCodeViewer::Extrusions::Ranges::width, Width, Slic3r::GUI::Preview::Wipe, ImVec2::x, and ImVec2::y.
Referenced by render().
render_shells()
void Slic3r::GUI::GCodeViewer::render_shells () private
{
    if (!m_shells.visible || m_shells.volumes.empty())
        return;
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    const Camera& camera = wxGetApp().plater()->get_camera();
    m_shells.volumes.render(GLVolumeCollection::ERenderType::Transparent, true, camera.get_view_matrix(), camera.get_projection_matrix());
    shader->stop_using();
}
References Slic3r::GLVolumeCollection::empty(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), m_shells, Slic3r::GLVolumeCollection::render(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::GLVolumeCollection::Transparent, Slic3r::GUI::GCodeViewer::Shells::visible, and Slic3r::GUI::GCodeViewer::Shells::volumes.
Referenced by render().
render_toolpaths()
void Slic3r::GUI::GCodeViewer::render_toolpaths () private
{
    const Camera& camera = wxGetApp().plater()->get_camera();
#if !ENABLE_GL_CORE_PROFILE
    const double zoom = camera.get_zoom();
#endif // !ENABLE_GL_CORE_PROFILE
    auto render_as_lines = [
#if ENABLE_GCODE_VIEWER_STATISTICS
        this
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    ](std::vector<RenderPath>::iterator it_path, std::vector<RenderPath>::iterator it_end, GLShaderProgram& shader, int uniform_color) {
        for (auto it = it_path; it != it_end && it_path->ibuffer_id == it->ibuffer_id; ++it) {
            const RenderPath& path = *it;
            // Some OpenGL drivers crash on empty glMultiDrawElements, see GH #7415.
            assert(! path.sizes.empty());
            assert(! path.offsets.empty());
            shader.set_uniform(uniform_color, path.color);
#if ENABLE_GL_CORE_PROFILE
            const Camera& camera = wxGetApp().plater()->get_camera();
            const std::array<int, 4>& viewport = camera.get_viewport();
            const float zoom = float(camera.get_zoom());
            shader.set_uniform("viewport_size", Vec2d(double(viewport[2]), double(viewport[3])));
            shader.set_uniform("width", (zoom < 5.0f) ? 0.5f : (0.5f + 5.0f * (zoom - 5.0f) / (100.0f - 5.0f)));
            shader.set_uniform("gap_size", 0.0f);
#endif // ENABLE_GL_CORE_PROFILE
#if ENABLE_OPENGL_ES
            for (size_t i = 0; i < path.sizes.size(); ++i) {
                glsafe(::glDrawElements(GL_LINES, (GLsizei)path.sizes[i], GL_UNSIGNED_SHORT, (const void*)path.offsets[i]));
            }
#else
            glsafe(::glMultiDrawElements(GL_LINES, (const GLsizei*)path.sizes.data(), GL_UNSIGNED_SHORT, (const void* const*)path.offsets.data(), (GLsizei)path.sizes.size()));
#endif // ENABLE_OPENGL_ES
#if ENABLE_GCODE_VIEWER_STATISTICS
            ++m_statistics.gl_multi_lines_calls_count;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
        }
    };
    auto render_as_triangles = [
#if ENABLE_GCODE_VIEWER_STATISTICS
        this
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    ](std::vector<RenderPath>::iterator it_path, std::vector<RenderPath>::iterator it_end, GLShaderProgram& shader, int uniform_color) {
        for (auto it = it_path; it != it_end && it_path->ibuffer_id == it->ibuffer_id; ++it) {
            const RenderPath& path = *it;
            // Some OpenGL drivers crash on empty glMultiDrawElements, see GH #7415.
            assert(! path.sizes.empty());
            assert(! path.offsets.empty());
            shader.set_uniform(uniform_color, path.color);
#if ENABLE_OPENGL_ES
            for (size_t i = 0; i < path.sizes.size(); ++i) {
                glsafe(::glDrawElements(GL_TRIANGLES, (GLsizei)path.sizes[i], GL_UNSIGNED_SHORT, (const void*)path.offsets[i]));
            }
#else
            glsafe(::glMultiDrawElements(GL_TRIANGLES, (const GLsizei*)path.sizes.data(), GL_UNSIGNED_SHORT, (const void* const*)path.offsets.data(), (GLsizei)path.sizes.size()));
#endif // ENABLE_OPENGL_ES
#if ENABLE_GCODE_VIEWER_STATISTICS
            ++m_statistics.gl_multi_triangles_calls_count;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
        }
    };
    auto render_as_instanced_model = [
#if ENABLE_GCODE_VIEWER_STATISTICS
        this
#endif // ENABLE_GCODE_VIEWER_STATISTICS
        ](TBuffer& buffer, GLShaderProgram & shader) {
        for (auto& range : buffer.model.instances.render_ranges.ranges) {
            if (range.vbo == 0 && range.count > 0) {
                glsafe(::glGenBuffers(1, &range.vbo));
                glsafe(::glBindBuffer(GL_ARRAY_BUFFER, range.vbo));
                glsafe(::glBufferData(GL_ARRAY_BUFFER, range.count * buffer.model.instances.instance_size_bytes(), (const void*)&buffer.model.instances.buffer[range.offset * buffer.model.instances.instance_size_floats()], GL_STATIC_DRAW));
                glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
            }
            if (range.vbo > 0) {
                buffer.model.model.set_color(range.color);
                buffer.model.model.render_instanced(range.vbo, range.count);
#if ENABLE_GCODE_VIEWER_STATISTICS
                ++m_statistics.gl_instanced_models_calls_count;
                m_statistics.total_instances_gpu_size += static_cast<int64_t>(range.count * buffer.model.instances.instance_size_bytes());
#endif // ENABLE_GCODE_VIEWER_STATISTICS
            }
        }
    };
#if ENABLE_GCODE_VIEWER_STATISTICS
        auto render_as_batched_model = [this](TBuffer& buffer, GLShaderProgram& shader, int position_id, int normal_id) {
#else
        auto render_as_batched_model = [](TBuffer& buffer, GLShaderProgram& shader, int position_id, int normal_id) {
#endif // ENABLE_GCODE_VIEWER_STATISTICS
        struct Range
        {
            unsigned int first;
            unsigned int last;
            bool intersects(const Range& other) const { return (other.last < first || other.first > last) ? false : true; }
        };
        Range buffer_range = { 0, 0 };
        const size_t indices_per_instance = buffer.model.data.indices_count();
        for (size_t j = 0; j < buffer.indices.size(); ++j) {
            const IBuffer& i_buffer = buffer.indices[j];
            buffer_range.last = buffer_range.first + i_buffer.count / indices_per_instance;
#if ENABLE_GL_CORE_PROFILE
            if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                glsafe(::glBindVertexArray(i_buffer.vao));
#endif // ENABLE_GL_CORE_PROFILE
            glsafe(::glBindBuffer(GL_ARRAY_BUFFER, i_buffer.vbo));
            if (position_id != -1) {
                glsafe(::glVertexAttribPointer(position_id, buffer.vertices.position_size_floats(), GL_FLOAT, GL_FALSE, buffer.vertices.vertex_size_bytes(), (const void*)buffer.vertices.position_offset_bytes()));
                glsafe(::glEnableVertexAttribArray(position_id));
            }
            const bool has_normals = buffer.vertices.normal_size_floats() > 0;
            if (has_normals) {
                if (normal_id != -1) {
                    glsafe(::glVertexAttribPointer(normal_id, buffer.vertices.normal_size_floats(), GL_FLOAT, GL_FALSE, buffer.vertices.vertex_size_bytes(), (const void*)buffer.vertices.normal_offset_bytes()));
                    glsafe(::glEnableVertexAttribArray(normal_id));
                }
            }
            glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, i_buffer.ibo));
            for (auto& range : buffer.model.instances.render_ranges.ranges) {
                const Range range_range = { range.offset, range.offset + range.count };
                if (range_range.intersects(buffer_range)) {
                    shader.set_uniform("uniform_color", range.color);
                    const unsigned int offset = (range_range.first > buffer_range.first) ? range_range.first - buffer_range.first : 0;
                    const size_t offset_bytes = static_cast<size_t>(offset) * indices_per_instance * sizeof(IBufferType);
                    const Range render_range = { std::max(range_range.first, buffer_range.first), std::min(range_range.last, buffer_range.last) };
                    const size_t count = static_cast<size_t>(render_range.last - render_range.first) * indices_per_instance;
                    if (count > 0) {
                        glsafe(::glDrawElements(GL_TRIANGLES, (GLsizei)count, GL_UNSIGNED_SHORT, (const void*)offset_bytes));
#if ENABLE_GCODE_VIEWER_STATISTICS
                        ++m_statistics.gl_batched_models_calls_count;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
                    }
                }
            }
            glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
            if (normal_id != -1)
                glsafe(::glDisableVertexAttribArray(normal_id));
            if (position_id != -1)
                glsafe(::glDisableVertexAttribArray(position_id));
            glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
#if ENABLE_GL_CORE_PROFILE
            if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                glsafe(::glBindVertexArray(0));
#endif // ENABLE_GL_CORE_PROFILE
            buffer_range.first = buffer_range.last;
        }
    };
    auto line_width = [](double zoom) {
        return (zoom < 5.0) ? 1.0 : (1.0 + 5.0 * (zoom - 5.0) / (100.0 - 5.0));
    };
    const unsigned char begin_id = buffer_id(EMoveType::Retract);
    const unsigned char end_id   = buffer_id(EMoveType::Count);
    for (unsigned char i = begin_id; i < end_id; ++i) {
        TBuffer& buffer = m_buffers[i];
        if (!buffer.visible || !buffer.has_data())
            continue;
        GLShaderProgram* shader = wxGetApp().get_shader(buffer.shader.c_str());
        if (shader == nullptr)
            continue;
        shader->start_using();
        shader->set_uniform("view_model_matrix", camera.get_view_matrix());
        shader->set_uniform("projection_matrix", camera.get_projection_matrix());
        shader->set_uniform("view_normal_matrix", (Matrix3d)Matrix3d::Identity());
        if (buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::InstancedModel) {
            shader->set_uniform("emission_factor", 0.25f);
            render_as_instanced_model(buffer, *shader);
            shader->set_uniform("emission_factor", 0.0f);
        }
        else if (buffer.render_primitive_type == TBuffer::ERenderPrimitiveType::BatchedModel) {
            shader->set_uniform("emission_factor", 0.25f);
            const int position_id = shader->get_attrib_location("v_position");
            const int normal_id   = shader->get_attrib_location("v_normal");
            render_as_batched_model(buffer, *shader, position_id, normal_id);
            shader->set_uniform("emission_factor", 0.0f);
        }
        else {
            shader->set_uniform("emission_factor", 0.15f);
            const int position_id = shader->get_attrib_location("v_position");
            const int normal_id   = shader->get_attrib_location("v_normal");
            const int uniform_color = shader->get_uniform_location("uniform_color");
            auto it_path = buffer.render_paths.begin();
            for (unsigned int ibuffer_id = 0; ibuffer_id < static_cast<unsigned int>(buffer.indices.size()); ++ibuffer_id) {
                const IBuffer& i_buffer = buffer.indices[ibuffer_id];
                // Skip all paths with ibuffer_id < ibuffer_id.
                for (; it_path != buffer.render_paths.end() && it_path->ibuffer_id < ibuffer_id; ++it_path);
                if (it_path == buffer.render_paths.end() || it_path->ibuffer_id > ibuffer_id)
                    // Not found. This shall not happen.
                    continue;
#if ENABLE_GL_CORE_PROFILE
                if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                    glsafe(::glBindVertexArray(i_buffer.vao));
#endif // ENABLE_GL_CORE_PROFILE
                glsafe(::glBindBuffer(GL_ARRAY_BUFFER, i_buffer.vbo));
                if (position_id != -1) {
                    glsafe(::glVertexAttribPointer(position_id, buffer.vertices.position_size_floats(), GL_FLOAT, GL_FALSE, buffer.vertices.vertex_size_bytes(), (const void*)buffer.vertices.position_offset_bytes()));
                    glsafe(::glEnableVertexAttribArray(position_id));
                }
                const bool has_normals = buffer.vertices.normal_size_floats() > 0;
                if (has_normals) {
                    if (normal_id != -1) {
                        glsafe(::glVertexAttribPointer(normal_id, buffer.vertices.normal_size_floats(), GL_FLOAT, GL_FALSE, buffer.vertices.vertex_size_bytes(), (const void*)buffer.vertices.normal_offset_bytes()));
                        glsafe(::glEnableVertexAttribArray(normal_id));
                    }
                }
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, i_buffer.ibo));
                // Render all elements with it_path->ibuffer_id == ibuffer_id, possible with varying colors.
                switch (buffer.render_primitive_type)
                {
                case TBuffer::ERenderPrimitiveType::Line: {
#if ENABLE_GL_CORE_PROFILE
                    if (!OpenGLManager::get_gl_info().is_core_profile())
                        glsafe(::glLineWidth(static_cast<GLfloat>(line_width(camera.get_zoom()))));
#else
                    glsafe(::glLineWidth(static_cast<GLfloat>(line_width(zoom))));
#endif // ENABLE_GL_CORE_PROFILE
                    render_as_lines(it_path, buffer.render_paths.end(), *shader, uniform_color);
                    break;
                }
                case TBuffer::ERenderPrimitiveType::Triangle: {
                    render_as_triangles(it_path, buffer.render_paths.end(), *shader, uniform_color);
                    break;
                }
                default: { break; }
                }
                glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
                if (normal_id != -1)
                    glsafe(::glDisableVertexAttribArray(normal_id));
                if (position_id != -1)
                    glsafe(::glDisableVertexAttribArray(position_id));
                glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
#if ENABLE_GL_CORE_PROFILE
                if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
                    glsafe(::glBindVertexArray(0));
#endif // ENABLE_GL_CORE_PROFILE
            }
        }
        shader->stop_using();
    }
#if ENABLE_GCODE_VIEWER_STATISTICS
    auto render_sequential_range_cap = [this, &camera]
#else
    auto render_sequential_range_cap = [&camera]
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    (const SequentialRangeCap& cap) {
        const TBuffer* buffer = cap.buffer;
        GLShaderProgram* shader = wxGetApp().get_shader(buffer->shader.c_str());
        if (shader == nullptr)
            return;
        shader->start_using();
        shader->set_uniform("view_model_matrix", camera.get_view_matrix());
        shader->set_uniform("projection_matrix", camera.get_projection_matrix());
        shader->set_uniform("view_normal_matrix", (Matrix3d)Matrix3d::Identity());
        const int position_id = shader->get_attrib_location("v_position");
        const int normal_id   = shader->get_attrib_location("v_normal");
#if ENABLE_GL_CORE_PROFILE
        if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
            glsafe(::glBindVertexArray(cap.vao));
#endif // ENABLE_GL_CORE_PROFILE
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, cap.vbo));
        if (position_id != -1) {
            glsafe(::glVertexAttribPointer(position_id, buffer->vertices.position_size_floats(), GL_FLOAT, GL_FALSE, buffer->vertices.vertex_size_bytes(), (const void*)buffer->vertices.position_offset_bytes()));
            glsafe(::glEnableVertexAttribArray(position_id));
        }
        const bool has_normals = buffer->vertices.normal_size_floats() > 0;
        if (has_normals) {
            if (normal_id != -1) {
                glsafe(::glVertexAttribPointer(normal_id, buffer->vertices.normal_size_floats(), GL_FLOAT, GL_FALSE, buffer->vertices.vertex_size_bytes(), (const void*)buffer->vertices.normal_offset_bytes()));
                glsafe(::glEnableVertexAttribArray(normal_id));
            }
        }
        shader->set_uniform("uniform_color", cap.color);
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, cap.ibo));
        glsafe(::glDrawElements(GL_TRIANGLES, (GLsizei)cap.indices_count(), GL_UNSIGNED_SHORT, nullptr));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
#if ENABLE_GCODE_VIEWER_STATISTICS
        ++m_statistics.gl_triangles_calls_count;
#endif // ENABLE_GCODE_VIEWER_STATISTICS
        if (normal_id != -1)
            glsafe(::glDisableVertexAttribArray(normal_id));
        if (position_id != -1)
            glsafe(::glDisableVertexAttribArray(position_id));
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
#if ENABLE_GL_CORE_PROFILE
        if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
            glsafe(::glBindVertexArray(0));
#endif // ENABLE_GL_CORE_PROFILE
        shader->stop_using();
    };
    for (unsigned int i = 0; i < 2; ++i) {
        if (m_sequential_range_caps[i].is_renderable())
            render_sequential_range_cap(m_sequential_range_caps[i]);
    }
}
References Slic3r::GUI::GCodeViewer::TBuffer::BatchedModel, Slic3r::GUI::GCodeViewer::InstanceVBuffer::buffer, Slic3r::GUI::buffer_id(), Slic3r::GUI::GCodeViewer::RenderPath::color, Slic3r::Count, Slic3r::GUI::GCodeViewer::IBuffer::count, Slic3r::GUI::GCodeViewer::TBuffer::Model::data, Slic3r::GLShaderProgram::get_attrib_location(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GLShaderProgram::get_uniform_location(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), Slic3r::GUI::Camera::get_zoom(), GL_FALSE, GL_TRIANGLES, glsafe, Slic3r::GUI::GCodeViewer::TBuffer::has_data(), Slic3r::GUI::GCodeViewer::IBuffer::ibo, Slic3r::GUI::GCodeViewer::TBuffer::indices, Slic3r::GUI::GLModel::Geometry::indices_count(), Slic3r::GUI::GCodeViewer::InstanceVBuffer::instance_size_bytes(), Slic3r::GUI::GCodeViewer::InstanceVBuffer::instance_size_floats(), Slic3r::GUI::GCodeViewer::TBuffer::InstancedModel, Slic3r::GUI::GCodeViewer::TBuffer::Model::instances, Slic3r::GUI::OpenGLManager::GLInfo::is_version_greater_or_equal_to(), Slic3r::GUI::GCodeViewer::TBuffer::Line, m_buffers, m_sequential_range_caps, Slic3r::GUI::GCodeViewer::TBuffer::Model::model, Slic3r::GUI::GCodeViewer::TBuffer::model, Slic3r::GUI::GCodeViewer::VBuffer::normal_offset_bytes(), Slic3r::GUI::GCodeViewer::VBuffer::normal_size_floats(), Slic3r::offset(), Slic3r::GUI::GCodeViewer::RenderPath::offsets, Slic3r::GUI::GCodeViewer::VBuffer::position_offset_bytes(), Slic3r::GUI::GCodeViewer::VBuffer::position_size_floats(), Slic3r::range(), Slic3r::GUI::GCodeViewer::InstanceVBuffer::Ranges::ranges, Slic3r::GUI::GLModel::render_instanced(), Slic3r::GUI::GCodeViewer::TBuffer::render_paths, Slic3r::GUI::GCodeViewer::TBuffer::render_primitive_type, Slic3r::GUI::GCodeViewer::InstanceVBuffer::render_ranges, Slic3r::Retract, Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GUI::GCodeViewer::TBuffer::shader, Slic3r::GUI::GCodeViewer::RenderPath::sizes, Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::GUI::GCodeViewer::TBuffer::Triangle, Slic3r::GUI::GCodeViewer::IBuffer::vbo, Slic3r::GUI::GCodeViewer::VBuffer::vertex_size_bytes(), Slic3r::GUI::GCodeViewer::TBuffer::vertices, and Slic3r::GUI::GCodeViewer::TBuffer::visible.
Referenced by render().
reset()
void Slic3r::GUI::GCodeViewer::reset ()
{
    m_moves_count = 0;
    for (TBuffer& buffer : m_buffers) {
        buffer.reset();
    }
    m_paths_bounding_box = BoundingBoxf3();
    m_max_bounding_box = BoundingBoxf3();
    m_max_print_height = 0.0f;
    m_tool_colors = std::vector<ColorRGBA>();
    m_extruders_count = 0;
    m_extruder_ids = std::vector<unsigned char>();
    m_filament_diameters = std::vector<float>();
    m_filament_densities = std::vector<float>();
    m_extrusions.reset_ranges();
    m_shells.volumes.clear();
    m_layers.reset();
    m_layers_z_range = { 0, 0 };
    m_roles = std::vector<GCodeExtrusionRole>();
    m_print_statistics.reset();
    for (size_t i = 0; i < static_cast<size_t>(PrintEstimatedStatistics::ETimeMode::Count); ++i) {
        m_layers_times[i] = std::vector<float>();
    }
    m_custom_gcode_per_print_z = std::vector<CustomGCode::Item>();
    m_sequential_view.gcode_window.reset();
#if ENABLE_GCODE_VIEWER_STATISTICS
    m_statistics.reset_all();
#endif // ENABLE_GCODE_VIEWER_STATISTICS
    m_contained_in_bed = true;
    m_legend_resizer.reset();
}
References Slic3r::GLVolumeCollection::clear(), Slic3r::PrintEstimatedStatistics::Count, Slic3r::GUI::GCodeViewer::SequentialView::gcode_window, m_buffers, m_contained_in_bed, m_custom_gcode_per_print_z, m_extruder_ids, m_extruders_count, m_extrusions, m_filament_densities, m_filament_diameters, m_layers, m_layers_times, m_layers_z_range, m_legend_resizer, m_max_bounding_box, m_max_print_height, m_moves_count, m_paths_bounding_box, m_print_statistics, m_roles, m_sequential_view, m_shells, m_tool_colors, Slic3r::PrintEstimatedStatistics::reset(), Slic3r::GUI::GCodeViewer::Layers::reset(), Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::reset(), Slic3r::GUI::GCodeViewer::LegendResizer::reset(), Slic3r::GUI::GCodeViewer::Extrusions::reset_ranges(), and Slic3r::GUI::GCodeViewer::Shells::volumes.
Referenced by ~GCodeViewer(), load(), Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::load_gcode(), and Slic3r::GUI::GLCanvas3D::reset_gcode_toolpaths().
set_layers_z_range()
void Slic3r::GUI::GCodeViewer::set_layers_z_range (const std::array< unsigned int, 2 > & layers_z_range)
{
    bool keep_sequential_current_first = layers_z_range[0] >= m_layers_z_range[0];
    bool keep_sequential_current_last = layers_z_range[1] <= m_layers_z_range[1];
    m_layers_z_range = layers_z_range;
    refresh_render_paths(keep_sequential_current_first, keep_sequential_current_last);
    wxGetApp().plater()->update_preview_moves_slider();
}
References m_layers_z_range, and refresh_render_paths().
Referenced by Slic3r::GUI::GLCanvas3D::set_toolpaths_z_range().
set_options_visibility_from_flags()
void Slic3r::GUI::GCodeViewer::set_options_visibility_from_flags (unsigned int flags)
{
    auto is_flag_set = [flags](unsigned int flag) {
        return (flags & (1 << flag)) != 0;
    };
    set_toolpath_move_type_visible(EMoveType::Travel, is_flag_set(static_cast<unsigned int>(Preview::OptionType::Travel)));
    set_toolpath_move_type_visible(EMoveType::Wipe, is_flag_set(static_cast<unsigned int>(Preview::OptionType::Wipe)));
    set_toolpath_move_type_visible(EMoveType::Retract, is_flag_set(static_cast<unsigned int>(Preview::OptionType::Retractions)));
    set_toolpath_move_type_visible(EMoveType::Unretract, is_flag_set(static_cast<unsigned int>(Preview::OptionType::Unretractions)));
    set_toolpath_move_type_visible(EMoveType::Seam, is_flag_set(static_cast<unsigned int>(Preview::OptionType::Seams)));
    set_toolpath_move_type_visible(EMoveType::Tool_change, is_flag_set(static_cast<unsigned int>(Preview::OptionType::ToolChanges)));
    set_toolpath_move_type_visible(EMoveType::Color_change, is_flag_set(static_cast<unsigned int>(Preview::OptionType::ColorChanges)));
    set_toolpath_move_type_visible(EMoveType::Pause_Print, is_flag_set(static_cast<unsigned int>(Preview::OptionType::PausePrints)));
    set_toolpath_move_type_visible(EMoveType::Custom_GCode, is_flag_set(static_cast<unsigned int>(Preview::OptionType::CustomGCodes)));
    m_cog.set_visible(is_flag_set(static_cast<unsigned int>(Preview::OptionType::CenterOfGravity)));
    m_shells.visible = is_flag_set(static_cast<unsigned int>(Preview::OptionType::Shells));
    m_sequential_view.marker.set_visible(is_flag_set(static_cast<unsigned int>(Preview::OptionType::ToolMarker)));
}
References Slic3r::GUI::Preview::CenterOfGravity, Slic3r::Color_change, Slic3r::GUI::Preview::ColorChanges, Slic3r::Custom_GCode, Slic3r::GUI::Preview::CustomGCodes, m_cog, m_sequential_view, m_shells, Slic3r::GUI::GCodeViewer::SequentialView::marker, Slic3r::Pause_Print, Slic3r::GUI::Preview::PausePrints, Slic3r::Retract, Slic3r::GUI::Preview::Retractions, Slic3r::Seam, Slic3r::GUI::Preview::Seams, set_toolpath_move_type_visible(), Slic3r::GUI::GCodeViewer::COG::set_visible(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::set_visible(), Slic3r::GUI::Preview::Shells, Slic3r::Tool_change, Slic3r::GUI::Preview::ToolChanges, Slic3r::GUI::Preview::ToolMarker, Slic3r::Travel, Slic3r::GUI::Preview::Travel, Slic3r::Unretract, Slic3r::GUI::Preview::Unretractions, Slic3r::GUI::GCodeViewer::Shells::visible, Slic3r::Wipe, and Slic3r::GUI::Preview::Wipe.
Referenced by render_legend(), and Slic3r::GUI::GLCanvas3D::set_gcode_options_visibility_from_flags().
set_toolpath_move_type_visible()
void Slic3r::GUI::GCodeViewer::set_toolpath_move_type_visible (EMoveType type, bool visible)
{
    size_t id = static_cast<size_t>(buffer_id(type));
    if (id < m_buffers.size())
        m_buffers[id].visible = visible;
}
References Slic3r::GUI::buffer_id(), and m_buffers.
Referenced by init(), and set_options_visibility_from_flags().
set_toolpath_role_visibility_flags()
void Slic3r::GUI::GCodeViewer::set_toolpath_role_visibility_flags (unsigned int flags) inline
{ m_extrusions.role_visibility_flags = flags; }
References m_extrusions, and Slic3r::GUI::GCodeViewer::Extrusions::role_visibility_flags.
Referenced by Slic3r::GUI::GLCanvas3D::set_toolpath_role_visibility_flags().
set_view_type()
void Slic3r::GUI::GCodeViewer::set_view_type (EViewType type) inline
{
        if (type == EViewType::Count)
            type = EViewType::FeatureType;
        m_view_type = type;
    }
References Count, FeatureType, and m_view_type.
Referenced by render_legend(), Slic3r::GUI::GLCanvas3D::set_gcode_view_preview_type(), and Slic3r::GUI::GLCanvas3D::set_toolpath_view_type().
toggle_gcode_window_visibility()
void Slic3r::GUI::GCodeViewer::toggle_gcode_window_visibility () inline
{ m_sequential_view.gcode_window.toggle_visibility(); }
References Slic3r::GUI::GCodeViewer::SequentialView::gcode_window, m_sequential_view, and Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::toggle_visibility().
Referenced by Slic3r::GUI::GLCanvas3D::on_char().
update_sequential_view_current()
void Slic3r::GUI::GCodeViewer::update_sequential_view_current (unsigned int first, unsigned int last)
{
    auto is_visible = [this](unsigned int id) {
        for (const TBuffer& buffer : m_buffers) {
            if (buffer.visible) {
                for (const Path& path : buffer.paths) {
                    if (path.sub_paths.front().first.s_id <= id && id <= path.sub_paths.back().last.s_id)
                        return true;
                }
            }
        }
        return false;
    };
    const int first_diff = static_cast<int>(first) - static_cast<int>(m_sequential_view.last_current.first);
    const int last_diff = static_cast<int>(last) - static_cast<int>(m_sequential_view.last_current.last);
    unsigned int new_first = first;
    unsigned int new_last = last;
    if (m_sequential_view.skip_invisible_moves) {
        while (!is_visible(new_first)) {
            if (first_diff > 0)
                ++new_first;
            else
                --new_first;
        }
        while (!is_visible(new_last)) {
            if (last_diff > 0)
                ++new_last;
            else
                --new_last;
        }
    }
    m_sequential_view.current.first = new_first;
    m_sequential_view.current.last = new_last;
    m_sequential_view.last_current = m_sequential_view.current;
    refresh_render_paths(true, true);
    if (new_first != first || new_last != last)
        wxGetApp().plater()->update_preview_moves_slider();
}
References Slic3r::GUI::GCodeViewer::SequentialView::current, Slic3r::GUI::GCodeViewer::SequentialView::Endpoints::first, is_visible(), Slic3r::GUI::GCodeViewer::SequentialView::Endpoints::last, Slic3r::GUI::GCodeViewer::SequentialView::last_current, m_buffers, m_sequential_view, refresh_render_paths(), and Slic3r::GUI::GCodeViewer::SequentialView::skip_invisible_moves.
Referenced by Slic3r::GUI::GLCanvas3D::update_gcode_sequential_view_current().
update_shells_color_by_extruder()
void Slic3r::GUI::GCodeViewer::update_shells_color_by_extruder (const DynamicPrintConfig * config)
{
    if (config != nullptr)
        m_shells.volumes.update_colors_by_extruder(config);
}
References m_shells, Slic3r::GLVolumeCollection::update_colors_by_extruder(), and Slic3r::GUI::GCodeViewer::Shells::volumes.
Referenced by Slic3r::GUI::GLCanvas3D::load_gcode_preview().
Member Data Documentation
Extrusion_Role_Colors
const std::array< ColorRGBA, static_cast< size_t >(GCodeExtrusionRole::Count)> Slic3r::GUI::GCodeViewer::Extrusion_Role_Colors static private
Initial value:
{ {
    { 0.90f, 0.70f, 0.70f, 1.0f },
    { 1.00f, 0.90f, 0.30f, 1.0f },
    { 1.00f, 0.49f, 0.22f, 1.0f },
    { 0.12f, 0.12f, 1.00f, 1.0f },
    { 0.69f, 0.19f, 0.16f, 1.0f },
    { 0.59f, 0.33f, 0.80f, 1.0f },
    { 0.94f, 0.25f, 0.25f, 1.0f },
    { 1.00f, 0.55f, 0.41f, 1.0f },
    { 0.30f, 0.50f, 0.73f, 1.0f },
    { 1.00f, 1.00f, 1.00f, 1.0f },
    { 0.00f, 0.53f, 0.43f, 1.0f },
    { 0.00f, 1.00f, 0.00f, 1.0f },
    { 0.00f, 0.50f, 0.00f, 1.0f },
    { 0.70f, 0.89f, 0.67f, 1.0f },
    { 0.37f, 0.82f, 0.58f, 1.0f },
}}
Referenced by refresh_render_paths(), and render_legend().
m_buffers
std::vector<TBuffer> Slic3r::GUI::GCodeViewer::m_buffers { static_cast<size_t>(EMoveType::Extrude) } private
Referenced by can_export_toolpaths(), export_toolpaths_to_obj(), init(), is_toolpath_move_type_visible(), load_toolpaths(), log_memory_used(), refresh(), refresh_render_paths(), render_legend(), render_toolpaths(), reset(), set_toolpath_move_type_visible(), and update_sequential_view_current().
m_cog
COG Slic3r::GUI::GCodeViewer::m_cog private
Referenced by get_options_visibility_flags(), load_toolpaths(), render_cog(), and set_options_visibility_from_flags().
m_conflict_result
ConflictResultOpt Slic3r::GUI::GCodeViewer::m_conflict_result private
Referenced by get_conflict_result(), and load().
m_contained_in_bed
bool Slic3r::GUI::GCodeViewer::m_contained_in_bed { true } private
Referenced by is_contained_in_bed(), load_toolpaths(), and reset().
m_custom_gcode_per_print_z
std::vector<CustomGCode::Item> Slic3r::GUI::GCodeViewer::m_custom_gcode_per_print_z private
Referenced by get_custom_gcode_per_print_z(), load(), render_legend(), and reset().
m_extruder_ids
std::vector<unsigned char> Slic3r::GUI::GCodeViewer::m_extruder_ids private
Referenced by load_toolpaths(), render_legend(), and reset().
m_extruders_count
size_t Slic3r::GUI::GCodeViewer::m_extruders_count private
Referenced by get_extruders_count(), load_toolpaths(), render_legend(), and reset().
m_extrusions
Extrusions Slic3r::GUI::GCodeViewer::m_extrusions private
Referenced by GCodeViewer(), get_toolpath_role_visibility_flags(), is_visible(), refresh(), refresh_render_paths(), render_legend(), reset(), and set_toolpath_role_visibility_flags().
m_filament_densities
std::vector<float> Slic3r::GUI::GCodeViewer::m_filament_densities private
Referenced by load(), render_legend(), and reset().
m_filament_diameters
std::vector<float> Slic3r::GUI::GCodeViewer::m_filament_diameters private
Referenced by load(), render_legend(), and reset().
m_gl_data_initialized
bool Slic3r::GUI::GCodeViewer::m_gl_data_initialized { false } private
Referenced by init().
m_last_result_id
unsigned int Slic3r::GUI::GCodeViewer::m_last_result_id { 0 } private
Referenced by load().
m_last_view_type
EViewType Slic3r::GUI::GCodeViewer::m_last_view_type { EViewType::Count } private
Referenced by load().
m_layers
Layers Slic3r::GUI::GCodeViewer::m_layers private
Referenced by get_layers_zs(), load(), load_toolpaths(), log_memory_used(), refresh_render_paths(), render(), render_legend(), and reset().
m_layers_times
std::array<std::vector<float>, static_cast<size_t>(PrintEstimatedStatistics::ETimeMode::Count)> Slic3r::GUI::GCodeViewer::m_layers_times private
Referenced by refresh(), refresh_render_paths(), and reset().
m_layers_z_range
std::array<unsigned int, 2> Slic3r::GUI::GCodeViewer::m_layers_z_range private
Referenced by refresh_render_paths(), reset(), and set_layers_z_range().
m_legend_enabled
bool Slic3r::GUI::GCodeViewer::m_legend_enabled { true } private
Referenced by enable_legend(), is_legend_enabled(), and render_legend().
m_legend_resizer
LegendResizer Slic3r::GUI::GCodeViewer::m_legend_resizer private
Referenced by invalidate_legend(), render_legend(), and reset().
m_max_bounding_box
BoundingBoxf3 Slic3r::GUI::GCodeViewer::m_max_bounding_box private
Referenced by get_max_bounding_box(), load_toolpaths(), and reset().
m_max_print_height
float Slic3r::GUI::GCodeViewer::m_max_print_height { 0.0f } private
Referenced by load(), and reset().
m_moves_count
size_t Slic3r::GUI::GCodeViewer::m_moves_count { 0 } private
Referenced by load_toolpaths(), refresh(), refresh_render_paths(), and reset().
m_paths_bounding_box
BoundingBoxf3 Slic3r::GUI::GCodeViewer::m_paths_bounding_box private
Referenced by get_paths_bounding_box(), load(), load_toolpaths(), and reset().
m_print_statistics
PrintEstimatedStatistics Slic3r::GUI::GCodeViewer::m_print_statistics private
Referenced by load(), render_legend(), and reset().
m_roles
std::vector<GCodeExtrusionRole> Slic3r::GUI::GCodeViewer::m_roles private
Referenced by has_data(), load_toolpaths(), render(), render_legend(), and reset().
m_sequential_range_caps
std::array<SequentialRangeCap, 2> Slic3r::GUI::GCodeViewer::m_sequential_range_caps private
Referenced by refresh_render_paths(), and render_toolpaths().
m_sequential_view
SequentialView Slic3r::GUI::GCodeViewer::m_sequential_view private
Referenced by get_options_visibility_flags(), get_sequential_view(), init(), load(), load_toolpaths(), refresh_render_paths(), render(), render_legend(), reset(), set_options_visibility_from_flags(), toggle_gcode_window_visibility(), and update_sequential_view_current().
m_settings_ids
GCodeProcessorResult::SettingsIds Slic3r::GUI::GCodeViewer::m_settings_ids private
Referenced by load(), and render_legend().
m_shells
Shells Slic3r::GUI::GCodeViewer::m_shells private
Referenced by GCodeViewer(), get_options_visibility_flags(), load_shells(), render_shells(), reset(), set_options_visibility_from_flags(), and update_shells_color_by_extruder().
m_time_estimate_mode
PrintEstimatedStatistics::ETimeMode Slic3r::GUI::GCodeViewer::m_time_estimate_mode { PrintEstimatedStatistics::ETimeMode::Normal } private
Referenced by load(), refresh_render_paths(), and render_legend().
m_tool_colors
std::vector<ColorRGBA> Slic3r::GUI::GCodeViewer::m_tool_colors private
Referenced by refresh(), refresh_render_paths(), render_legend(), and reset().
m_view_type
EViewType Slic3r::GUI::GCodeViewer::m_view_type { EViewType::FeatureType } private
Referenced by get_view_type(), load(), load_toolpaths(), refresh(), refresh_render_paths(), render_legend(), and set_view_type().
Neutral_Color
const ColorRGBA Slic3r::GUI::GCodeViewer::Neutral_Color = ColorRGBA::DARK_GRAY() static private
Referenced by refresh_render_paths().
Options_Colors
const std::vector< ColorRGBA > Slic3r::GUI::GCodeViewer::Options_Colors static private
Initial value:
{ {
    { 0.803f, 0.135f, 0.839f, 1.0f },
    { 0.287f, 0.679f, 0.810f, 1.0f },
    { 0.900f, 0.900f, 0.900f, 1.0f },
    { 0.758f, 0.744f, 0.389f, 1.0f },
    { 0.856f, 0.582f, 0.546f, 1.0f },
    { 0.322f, 0.942f, 0.512f, 1.0f },
    { 0.886f, 0.825f, 0.262f, 1.0f }
}}
Referenced by option_color().
Range_Colors
const std::vector< ColorRGBA > Slic3r::GUI::GCodeViewer::Range_Colors static private
Initial value:
{ {
    { 0.043f, 0.173f, 0.478f, 1.0f },
    { 0.075f, 0.349f, 0.522f, 1.0f },
    { 0.110f, 0.533f, 0.569f, 1.0f },
    { 0.016f, 0.839f, 0.059f, 1.0f },
    { 0.667f, 0.949f, 0.000f, 1.0f },
    { 0.988f, 0.975f, 0.012f, 1.0f },
    { 0.961f, 0.808f, 0.039f, 1.0f },
    { 0.890f, 0.533f, 0.125f, 1.0f },
    { 0.820f, 0.408f, 0.188f, 1.0f },
    { 0.761f, 0.322f, 0.235f, 1.0f },
    { 0.581f, 0.149f, 0.087f, 1.0f }
}}
Referenced by Slic3r::GUI::GCodeViewer::Extrusions::Range::get_color_at(), render_legend(), and Slic3r::GUI::GCodeViewer::Extrusions::Range::step_size().
Travel_Colors
const std::vector< ColorRGBA > Slic3r::GUI::GCodeViewer::Travel_Colors static private
Initial value:
{ {
    { 0.219f, 0.282f, 0.609f, 1.0f },
    { 0.112f, 0.422f, 0.103f, 1.0f },
    { 0.505f, 0.064f, 0.028f, 1.0f }
}}
Referenced by refresh_render_paths(), and render_legend().
Wipe_Color
const ColorRGBA Slic3r::GUI::GCodeViewer::Wipe_Color = ColorRGBA::YELLOW() static private
Referenced by refresh_render_paths().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GCodeViewer.hpp
src/slic3r/GUI/GCodeViewer.cpp