Prusa Slicer: Slic3r::TriangleMeshDataAdapter Class Reference
Slic3r::TriangleMeshDataAdapter Class Reference
Public Member Functions
size_t polygonCount () const
size_t pointCount () const
size_t vertexCount (size_t) const
void getIndexSpacePoint (size_t n, size_t v, openvdb::Vec3d &pos) const
TriangleMeshDataAdapter (const indexed_triangle_set &m, const Transform3d tr=Transform3d::Identity())
Public Attributes
const indexed_triangle_set & its
Transform3d trafo
Detailed Description
Constructor & Destructor Documentation
TriangleMeshDataAdapter()
Slic3r::TriangleMeshDataAdapter::TriangleMeshDataAdapter (const indexed_triangle_set & m, const Transform3d tr = Transform3d::Identity()) inline
        : its{m}, trafo{tr} {}
Member Function Documentation
getIndexSpacePoint()
void Slic3r::TriangleMeshDataAdapter::getIndexSpacePoint (size_t n, size_t v, openvdb::Vec3d & pos) const inline
    {
        auto vidx = size_t(its.indices[n](Eigen::Index(v)));
        Slic3r::Vec3d p = trafo * its.vertices[vidx].cast<double>();
        pos = {p.x(), p.y(), p.z()};
    }
References indexed_triangle_set::indices, its, trafo, and indexed_triangle_set::vertices.
Referenced by Slic3r::mesh_to_grid().
pointCount()
size_t Slic3r::TriangleMeshDataAdapter::pointCount () const inline
{ return its.vertices.size(); }
References its, and indexed_triangle_set::vertices.
Referenced by Slic3r::mesh_to_grid().
polygonCount()
size_t Slic3r::TriangleMeshDataAdapter::polygonCount () const inline
{ return its.indices.size(); }
References indexed_triangle_set::indices, and its.
Referenced by Slic3r::mesh_to_grid().
vertexCount()
size_t Slic3r::TriangleMeshDataAdapter::vertexCount (size_t) const inline
{ return 3; }
Referenced by Slic3r::mesh_to_grid().
Member Data Documentation
its
const indexed_triangle_set& Slic3r::TriangleMeshDataAdapter::its
Referenced by getIndexSpacePoint(), Slic3r::mesh_to_grid(), pointCount(), and polygonCount().
trafo
Transform3d Slic3r::TriangleMeshDataAdapter::trafo
Referenced by getIndexSpacePoint().
The documentation for this class was generated from the following file:
src/libslic3r/OpenVDBUtils.cpp