Prusa Slicer: src/avrdude/jtag3.h File Reference
jtag3.h File Reference
Functions
int jtag3_open_common (PROGRAMMER *pgm, char *port)
int jtag3_send (PROGRAMMER *pgm, unsigned char *data, size_t len)
int jtag3_recv (PROGRAMMER *pgm, unsigned char **msg)
void jtag3_close (PROGRAMMER *pgm)
int jtag3_getsync (PROGRAMMER *pgm, int mode)
int jtag3_getparm (PROGRAMMER *pgm, unsigned char scope, unsigned char section, unsigned char parm, unsigned char *value, unsigned char length)
int jtag3_setparm (PROGRAMMER *pgm, unsigned char scope, unsigned char section, unsigned char parm, unsigned char *value, unsigned char length)
int jtag3_command (PROGRAMMER *pgm, unsigned char *cmd, unsigned int cmdlen, unsigned char **resp, const char *descr)
void jtag3_initpgm (PROGRAMMER *pgm)
void jtag3_dw_initpgm (PROGRAMMER *pgm)
void jtag3_pdi_initpgm (PROGRAMMER *pgm)
void jtag3_setup (PROGRAMMER *pgm)
void jtag3_teardown (PROGRAMMER *pgm)
Variables
const char jtag3_desc []
const char jtag3_dw_desc []
const char jtag3_pdi_desc []
Function Documentation
jtag3_close()
void jtag3_close (PROGRAMMER * pgm)
{
  unsigned char buf[4], *resp;
  avrdude_message(MSG_NOTICE2, "%s: jtag3_close()\n", progname);
  buf[0] = SCOPE_AVR;
  buf[1] = CMD3_SIGN_OFF;
  buf[2] = buf[3] = 0;
  if (jtag3_command(pgm, buf, 3, &resp, "AVR sign-off") >= 0)
    free(resp);
  buf[0] = SCOPE_GENERAL;
  buf[1] = CMD3_SIGN_OFF;
  if (jtag3_command(pgm, buf, 4, &resp, "sign-off") >= 0)
    free(resp);
  if (pgm->flag & PGM_FL_IS_EDBG)
    jtag3_edbg_signoff(pgm);
  serial_close(&pgm->fd);
  pgm->fd.ifd = -1;
}
References avrdude_message(), CMD3_SIGN_OFF, programmer_t::fd, programmer_t::flag, free(), filedescriptor::ifd, jtag3_command(), jtag3_edbg_signoff(), MSG_NOTICE2, pgm, PGM_FL_IS_EDBG, progname, SCOPE_AVR, SCOPE_GENERAL, and serial_close.
Referenced by jtag3_dw_initpgm(), jtag3_initpgm(), and jtag3_pdi_initpgm().
jtag3_command()
int jtag3_command (PROGRAMMER * pgm, unsigned char * cmd, unsigned int cmdlen, unsigned char ** resp, const char * descr)
{
  int status;
  unsigned char c;
  avrdude_message(MSG_NOTICE2, "%s: Sending %s command: ",
      progname, descr);
  jtag3_send(pgm, cmd, cmdlen);
  status = jtag3_recv(pgm, resp);
  if (status <= 0) {
    if (verbose >= 2)
      putc('\n', stderr);
    avrdude_message(MSG_NOTICE2, "%s: %s command: timeout/error communicating with programmer (status %d)\n",
                    progname, descr, status);
    return -1;
  } else if (verbose >= 3) {
    putc('\n', stderr);
    jtag3_prmsg(pgm, *resp, status);
  } else {
    avrdude_message(MSG_NOTICE2, "0x%02x (%d bytes msg)\n", (*resp)[1], status);
  }
  c = (*resp)[1];
  if ((c & RSP3_STATUS_MASK) != RSP3_OK) {
    avrdude_message(MSG_INFO, "%s: bad response to %s command: 0x%02x\n",
                    progname, descr, c);
    free(*resp);
    resp = 0;
    return -1;
  }
  return status;
}
References avrdude_message(), cmd, free(), jtag3_prmsg(), jtag3_recv(), jtag3_send(), MSG_INFO, MSG_NOTICE2, pgm, progname, RSP3_OK, RSP3_STATUS_MASK, and verbose.
Referenced by jtag3_chip_erase(), jtag3_close(), jtag3_display(), jtag3_getparm(), jtag3_getsync(), jtag3_initialize(), jtag3_page_erase(), jtag3_paged_load(), jtag3_paged_write(), jtag3_program_disable(), jtag3_program_enable(), jtag3_read_byte(), jtag3_setparm(), and jtag3_write_byte().
jtag3_dw_initpgm()
void jtag3_dw_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAGICE3_DW");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtag3_initialize;
  pgm->display        = jtag3_display;
  pgm->enable         = jtag3_enable;
  pgm->disable        = jtag3_disable;
  pgm->program_enable = jtag3_program_enable_dummy;
  pgm->chip_erase     = jtag3_chip_erase_dw;
  pgm->open           = jtag3_open_dw;
  pgm->close          = jtag3_close;
  pgm->read_byte      = jtag3_read_byte;
  pgm->write_byte     = jtag3_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtag3_paged_write;
  pgm->paged_load     = jtag3_paged_load;
  pgm->print_parms    = jtag3_print_parms;
  pgm->setup          = jtag3_setup;
  pgm->teardown       = jtag3_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_DW;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtag3_chip_erase_dw(), jtag3_close(), jtag3_disable(), jtag3_display(), jtag3_enable(), jtag3_initialize(), jtag3_open_dw(), jtag3_paged_load(), jtag3_paged_write(), jtag3_print_parms(), jtag3_program_enable_dummy(), jtag3_read_byte(), jtag3_setup(), jtag3_teardown(), jtag3_write_byte(), programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, PGM_FL_IS_DW, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtag3_getparm()
int jtag3_getparm (PROGRAMMER * pgm, unsigned char scope, unsigned char section, unsigned char parm, unsigned char * value, unsigned char length)
{
  int status;
  unsigned char buf[6], *resp, c;
  char descr[60];
  avrdude_message(MSG_NOTICE2, "%s: jtag3_getparm()\n", progname);
  buf[0] = scope;
  buf[1] = CMD3_GET_PARAMETER;
  buf[2] = 0;
  buf[3] = section;
  buf[4] = parm;
  buf[5] = length;
  sprintf(descr, "get parameter (scope 0x%02x, section %d, parm %d)",
    scope, section, parm);
  if ((status = jtag3_command(pgm, buf, 6, &resp, descr)) < 0)
    return -1;
  c = resp[1];
  if (c != RSP3_DATA || status < 3) {
    avrdude_message(MSG_INFO, "%s: jtag3_getparm(): "
                    "bad response to %s\n",
                    progname, descr);
    free(resp);
    return -1;
  }
  status -= 3;
  memcpy(value, resp + 3, (length < status? length: status));
  free(resp);
  return 0;
}
References avrdude_message(), CMD3_GET_PARAMETER, free(), jtag3_command(), MSG_INFO, MSG_NOTICE2, pgm, progname, and RSP3_DATA.
Referenced by jtag3_display(), jtag3_initialize(), and jtag3_print_parms1().
jtag3_getsync()
int jtag3_getsync (PROGRAMMER * pgm, int mode)
{
  unsigned char buf[3], *resp;
  avrdude_message(MSG_DEBUG, "%s: jtag3_getsync()\n", progname);
  if (pgm->flag & PGM_FL_IS_EDBG) {
    if (jtag3_edbg_prepare(pgm) < 0)
      return -1;
  }
  /* Get the sign-on information. */
  buf[0] = SCOPE_GENERAL;
  buf[1] = CMD3_SIGN_ON;
  buf[2] = 0;
  if (jtag3_command(pgm, buf, 3, &resp, "sign-on") < 0)
    return -1;
  free(resp);
  return 0;
}
References avrdude_message(), CMD3_SIGN_ON, programmer_t::flag, free(), jtag3_command(), jtag3_edbg_prepare(), MSG_DEBUG, pgm, PGM_FL_IS_EDBG, progname, and SCOPE_GENERAL.
Referenced by jtag3_open(), jtag3_open_dw(), and jtag3_open_pdi().
jtag3_initpgm()
void jtag3_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAGICE3");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtag3_initialize;
  pgm->display        = jtag3_display;
  pgm->enable         = jtag3_enable;
  pgm->disable        = jtag3_disable;
  pgm->program_enable = jtag3_program_enable_dummy;
  pgm->chip_erase     = jtag3_chip_erase;
  pgm->open           = jtag3_open;
  pgm->close          = jtag3_close;
  pgm->read_byte      = jtag3_read_byte;
  pgm->write_byte     = jtag3_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtag3_paged_write;
  pgm->paged_load     = jtag3_paged_load;
  pgm->page_erase     = jtag3_page_erase;
  pgm->print_parms    = jtag3_print_parms;
  pgm->set_sck_period = jtag3_set_sck_period;
  pgm->parseextparams = jtag3_parseextparms;
  pgm->setup          = jtag3_setup;
  pgm->teardown       = jtag3_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_JTAG;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtag3_chip_erase(), jtag3_close(), jtag3_disable(), jtag3_display(), jtag3_enable(), jtag3_initialize(), jtag3_open(), jtag3_page_erase(), jtag3_paged_load(), jtag3_paged_write(), jtag3_parseextparms(), jtag3_print_parms(), jtag3_program_enable_dummy(), jtag3_read_byte(), jtag3_set_sck_period(), jtag3_setup(), jtag3_teardown(), jtag3_write_byte(), programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, programmer_t::parseextparams, pgm, PGM_FL_IS_JTAG, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_sck_period, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtag3_open_common()
int jtag3_open_common (PROGRAMMER * pgm, char * port)
{
  union pinfo pinfo;
  LNODEID usbpid;
  int rv = -1;
#if !defined(HAVE_LIBUSB) && !defined(HAVE_LIBHIDAPI)
  avrdude_message(MSG_INFO, "avrdude was compiled without USB or HIDAPI support.\n");
  return -1;
#endif
  if (strncmp(port, "usb", 3) != 0) {
    avrdude_message(MSG_INFO, "%s: jtag3_open_common(): JTAGICE3/EDBG port names must start with \"usb\"\n",
                    progname);
    return -1;
  }
  if (pgm->usbvid)
    pinfo.usbinfo.vid = pgm->usbvid;
  else
    pinfo.usbinfo.vid = USB_VENDOR_ATMEL;
  /* If the config entry did not specify a USB PID, insert the default one. */
  if (lfirst(pgm->usbpid) == NULL)
    ladd(pgm->usbpid, (void *)USB_DEVICE_JTAGICE3);
#if defined(HAVE_LIBHIDAPI)
  /*
   * Try HIDAPI first.  LibUSB is more generic, but might then cause
   * troubles for HID-class devices in some OSes (like Windows).
   */
  serdev = &usbhid_serdev;
  for (usbpid = lfirst(pgm->usbpid); rv < 0 && usbpid != NULL; usbpid = lnext(usbpid)) {
    pinfo.usbinfo.flags = PINFO_FL_SILENT;
    pinfo.usbinfo.pid = *(int *)(ldata(usbpid));
    pgm->fd.usb.max_xfer = USBDEV_MAX_XFER_3;
    pgm->fd.usb.rep = USBDEV_BULK_EP_READ_3;
    pgm->fd.usb.wep = USBDEV_BULK_EP_WRITE_3;
    pgm->fd.usb.eep = 0;
    strcpy(pgm->port, port);
    rv = serial_open(port, pinfo, &pgm->fd);
  }
  if (rv < 0) {
#endif  /* HAVE_LIBHIDAPI */
#if defined(HAVE_LIBUSB)
    serdev = &usb_serdev_frame;
    for (usbpid = lfirst(pgm->usbpid); rv < 0 && usbpid != NULL; usbpid = lnext(usbpid)) {
      pinfo.usbinfo.flags = PINFO_FL_SILENT;
      pinfo.usbinfo.pid = *(int *)(ldata(usbpid));
      pgm->fd.usb.max_xfer = USBDEV_MAX_XFER_3;
      pgm->fd.usb.rep = USBDEV_BULK_EP_READ_3;
      pgm->fd.usb.wep = USBDEV_BULK_EP_WRITE_3;
      pgm->fd.usb.eep = USBDEV_EVT_EP_READ_3;
      strcpy(pgm->port, port);
      rv = serial_open(port, pinfo, &pgm->fd);
    }
#endif  /* HAVE_LIBUSB */
#if defined(HAVE_LIBHIDAPI)
  }
#endif
  if (rv < 0) {
    avrdude_message(MSG_INFO, "%s: jtag3_open_common(): Did not find any device matching VID 0x%04x and PID list: ",
                    progname, (unsigned)pinfo.usbinfo.vid);
    int notfirst = 0;
    for (usbpid = lfirst(pgm->usbpid); usbpid != NULL; usbpid = lnext(usbpid)) {
      if (notfirst)
        avrdude_message(MSG_INFO, ", ");
      avrdude_message(MSG_INFO, "0x%04x", (unsigned int)(*(int *)(ldata(usbpid))));
      notfirst = 1;
    }
    fputc('\n', stderr);
    return -1;
  }
  if (pgm->fd.usb.eep == 0)
  {
    /* The event EP has been deleted by usb_open(), so we are
       running on a CMSIS-DAP device, using EDBG protocol */
    pgm->flag |= PGM_FL_IS_EDBG;
    avrdude_message(MSG_NOTICE, "%s: Found CMSIS-DAP compliant device, using EDBG protocol\n",
                      progname);
  }
  /*
   * drain any extraneous input
   */
  jtag3_drain(pgm, 0);
  return 0;
}
References avrdude_message(), programmer_t::fd, programmer_t::flag, jtag3_drain(), ladd(), ldata(), lfirst(), lnext(), MSG_INFO, MSG_NOTICE, pgm, PGM_FL_IS_EDBG, PINFO_FL_SILENT, programmer_t::port, progname, serdev, serial_open, filedescriptor::usb, USB_DEVICE_JTAGICE3, usb_serdev_frame, USB_VENDOR_ATMEL, USBDEV_BULK_EP_READ_3, USBDEV_BULK_EP_WRITE_3, USBDEV_EVT_EP_READ_3, USBDEV_MAX_XFER_3, usbhid_serdev, pinfo::usbinfo, programmer_t::usbpid, and programmer_t::usbvid.
Referenced by jtag3_open(), jtag3_open_dw(), and jtag3_open_pdi().
jtag3_pdi_initpgm()
void jtag3_pdi_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAGICE3_PDI");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtag3_initialize;
  pgm->display        = jtag3_display;
  pgm->enable         = jtag3_enable;
  pgm->disable        = jtag3_disable;
  pgm->program_enable = jtag3_program_enable_dummy;
  pgm->chip_erase     = jtag3_chip_erase;
  pgm->open           = jtag3_open_pdi;
  pgm->close          = jtag3_close;
  pgm->read_byte      = jtag3_read_byte;
  pgm->write_byte     = jtag3_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtag3_paged_write;
  pgm->paged_load     = jtag3_paged_load;
  pgm->page_erase     = jtag3_page_erase;
  pgm->print_parms    = jtag3_print_parms;
  pgm->set_sck_period = jtag3_set_sck_period;
  pgm->setup          = jtag3_setup;
  pgm->teardown       = jtag3_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_PDI;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtag3_chip_erase(), jtag3_close(), jtag3_disable(), jtag3_display(), jtag3_enable(), jtag3_initialize(), jtag3_open_pdi(), jtag3_page_erase(), jtag3_paged_load(), jtag3_paged_write(), jtag3_print_parms(), jtag3_program_enable_dummy(), jtag3_read_byte(), jtag3_set_sck_period(), jtag3_setup(), jtag3_teardown(), jtag3_write_byte(), programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, PGM_FL_IS_PDI, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_sck_period, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtag3_recv()
int jtag3_recv (PROGRAMMER * pgm, unsigned char ** msg)
{
  unsigned short r_seqno;
  int rv;
  for (;;) {
    if ((rv = jtag3_recv_frame(pgm, msg)) <= 0)
      return rv;
    if ((rv & USB_RECV_FLAG_EVENT) != 0) {
      if (verbose >= 3)
  jtag3_prevent(pgm, *msg, rv & USB_RECV_LENGTH_MASK);
      free(*msg);
      continue;
    }
    rv &= USB_RECV_LENGTH_MASK;
    r_seqno = ((*msg)[2] << 8) | (*msg)[1];
    avrdude_message(MSG_DEBUG, "%s: jtag3_recv(): "
        "Got message seqno %d (command_sequence == %d)\n",
        progname, r_seqno, PDATA(pgm)->command_sequence);
    if (r_seqno == PDATA(pgm)->command_sequence) {
      if (++(PDATA(pgm)->command_sequence) == 0xffff)
  PDATA(pgm)->command_sequence = 0;
      /*
       * We move the payload to the beginning of the buffer, to make
       * the job easier for the caller.  We have to return the
       * original pointer though, as the caller must free() it.
       */
      rv -= 3;
      memmove(*msg, *msg + 3, rv);
      return rv;
    }
    avrdude_message(MSG_NOTICE2, "%s: jtag3_recv(): "
        "got wrong sequence number, %u != %u\n",
        progname, r_seqno, PDATA(pgm)->command_sequence);
    free(*msg);
  }
}
References avrdude_message(), free(), jtag3_prevent(), jtag3_recv_frame(), MSG_DEBUG, MSG_NOTICE2, PDATA, pgm, progname, USB_RECV_FLAG_EVENT, USB_RECV_LENGTH_MASK, and verbose.
Referenced by jtag3_command().
jtag3_send()
int jtag3_send (PROGRAMMER * pgm, unsigned char * data, size_t len)
{
  unsigned char *buf;
  if (pgm->flag & PGM_FL_IS_EDBG)
    return jtag3_edbg_send(pgm, data, len);
  avrdude_message(MSG_DEBUG, "\n%s: jtag3_send(): sending %lu bytes\n",
      progname, (unsigned long)len);
  if ((buf = malloc(len + 4)) == NULL)
    {
      avrdude_message(MSG_INFO, "%s: jtag3_send(): out of memory",
        progname);
      return -1;
    }
  buf[0] = TOKEN;
  buf[1] = 0;                   /* dummy */
  u16_to_b2(buf + 2, PDATA(pgm)->command_sequence);
  memcpy(buf + 4, data, len);
  if (serial_send(&pgm->fd, buf, len + 4) != 0) {
    avrdude_message(MSG_INFO, "%s: jtag3_send(): failed to send command to serial port\n",
                    progname);
    return -1;
  }
  free(buf);
  return 0;
}
References avrdude_message(), programmer_t::fd, programmer_t::flag, free(), jtag3_edbg_send(), malloc(), MSG_DEBUG, MSG_INFO, PDATA, pgm, PGM_FL_IS_EDBG, progname, serial_send, TOKEN, and u16_to_b2().
Referenced by jtag3_command().
jtag3_setparm()
int jtag3_setparm (PROGRAMMER * pgm, unsigned char scope, unsigned char section, unsigned char parm, unsigned char * value, unsigned char length)
{
  int status;
  unsigned char *buf, *resp;
  char descr[60];
  avrdude_message(MSG_NOTICE2, "%s: jtag3_setparm()\n", progname);
  sprintf(descr, "set parameter (scope 0x%02x, section %d, parm %d)",
    scope, section, parm);
  if ((buf = malloc(6 + length)) == NULL)
  {
    avrdude_message(MSG_INFO, "%s: jtag3_setparm(): Out of memory\n",
      progname);
    return -1;
  }
  buf[0] = scope;
  buf[1] = CMD3_SET_PARAMETER;
  buf[2] = 0;
  buf[3] = section;
  buf[4] = parm;
  buf[5] = length;
  memcpy(buf + 6, value, length);
  status = jtag3_command(pgm, buf, length + 6, &resp, descr);
  free(buf);
  if (status > 0)
    free(resp);
  return status;
}
References avrdude_message(), CMD3_SET_PARAMETER, free(), jtag3_command(), malloc(), MSG_INFO, MSG_NOTICE2, pgm, and progname.
Referenced by jtag3_initialize(), jtag3_set_sck_mega_jtag(), jtag3_set_sck_xmega_jtag(), and jtag3_set_sck_xmega_pdi().
jtag3_setup()
void jtag3_setup (PROGRAMMER * pgm)
{
  if ((pgm->cookie = malloc(sizeof(struct pdata))) == 0) {
    avrdude_message(MSG_INFO, "%s: jtag3_setup(): Out of memory allocating private data\n",
                    progname);
    exit(1);
  }
  memset(pgm->cookie, 0, sizeof(struct pdata));
}
References avrdude_message(), programmer_t::cookie, malloc(), MSG_INFO, pgm, and progname.
Referenced by jtag3_dw_initpgm(), jtag3_initpgm(), and jtag3_pdi_initpgm().
jtag3_teardown()
void jtag3_teardown (PROGRAMMER * pgm)
{
  free(pgm->cookie);
}
References programmer_t::cookie, free(), and pgm.
Referenced by jtag3_dw_initpgm(), jtag3_initpgm(), and jtag3_pdi_initpgm().
Variable Documentation
jtag3_desc
const char jtag3_desc[] extern
jtag3_dw_desc
const char jtag3_dw_desc[] extern
jtag3_pdi_desc
const char jtag3_pdi_desc[] extern