Prusa Slicer: Slic3r::GUI::GLCanvas3D::ToolbarHighlighter Struct Reference
Slic3r::GUI::GLCanvas3D::ToolbarHighlighter Struct Reference
Public Member Functions
void set_timer_owner (wxEvtHandler *owner, int timerid=wxID_ANY)
void init (GLToolbarItem *toolbar_item, GLCanvas3D *canvas)
void blink ()
void invalidate ()
Public Attributes
bool m_render_arrow { false }
GLToolbarItem * m_toolbar_item { nullptr }
Private Attributes
GLCanvas3D * m_canvas { nullptr }
int m_blink_counter { 0 }
ToolbarHighlighterTimer m_timer
Detailed Description
Member Function Documentation
blink()
void Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::blink ()
{
    if (m_toolbar_item) {
        char state = m_toolbar_item->get_highlight();
        if (state != (char)GLToolbarItem::EHighlightState::HighlightedShown)
            m_toolbar_item->set_highlight(GLToolbarItem::EHighlightState::HighlightedShown);
        else
            m_toolbar_item->set_highlight(GLToolbarItem::EHighlightState::HighlightedHidden);
        m_render_arrow = !m_render_arrow;
        m_canvas->set_as_dirty();
    }
    else
        invalidate();
    if ((++m_blink_counter) >= 11)
        invalidate();
}
References Slic3r::GUI::GLCanvas3D::set_as_dirty().
Referenced by Slic3r::GUI::GLCanvas3D::bind_event_handlers().
init()
void Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::init (GLToolbarItem * toolbar_item, GLCanvas3D * canvas)
{
    if (m_timer.IsRunning())
        invalidate();
    if (!toolbar_item || !canvas)
        return;
    m_timer.Start(300, false);
    m_toolbar_item = toolbar_item;
    m_canvas       = canvas;
}
invalidate()
void Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::invalidate ()
{
    m_timer.Stop();
    if (m_toolbar_item) {
        m_toolbar_item->set_highlight(GLToolbarItem::EHighlightState::NotHighlighted);
    }
    m_toolbar_item = nullptr;
    m_blink_counter = 0;
    m_render_arrow = false;
}
set_timer_owner()
void Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::set_timer_owner (wxEvtHandler * owner, int timerid = wxID_ANY)
{
    m_timer.SetOwner(owner, timerid);
}
Referenced by Slic3r::GUI::GLCanvas3D::bind_event_handlers().
Member Data Documentation
m_blink_counter
int Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::m_blink_counter { 0 } private
m_canvas
GLCanvas3D* Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::m_canvas { nullptr } private
m_render_arrow
bool Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::m_render_arrow { false }
m_timer
ToolbarHighlighterTimer Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::m_timer private
m_toolbar_item
GLToolbarItem* Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::m_toolbar_item { nullptr }
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GLCanvas3D.hpp
src/slic3r/GUI/GLCanvas3D.cpp