Prusa Slicer: Slic3r::UndoRedo::ObjectHistoryBase Class Reference
Slic3r::UndoRedo::ObjectHistoryBase Class Reference abstract
Public Member Functions
virtual ~ObjectHistoryBase ()
virtual bool is_mutable () const =0
virtual bool is_immutable () const =0
virtual bool is_optional () const
virtual const void * immutable_object_ptr () const
virtual bool empty ()=0
virtual size_t release_before_timestamp (size_t timestamp)=0
virtual size_t release_after_timestamp (size_t timestamp)=0
virtual size_t release_between_timestamps (size_t timestamp_start, size_t timestamp_end)=0
virtual size_t release_optional ()=0
virtual void restore_optional ()=0
virtual size_t memsize () const =0
virtual bool valid ()=0
Detailed Description
Constructor & Destructor Documentation
~ObjectHistoryBase()
virtual Slic3r::UndoRedo::ObjectHistoryBase::~ObjectHistoryBase () inline virtual
{}
Member Function Documentation
empty()
virtual bool Slic3r::UndoRedo::ObjectHistoryBase::empty () pure virtual
Implemented in Slic3r::UndoRedo::ObjectHistory< T >, Slic3r::UndoRedo::ObjectHistory< Interval >, and Slic3r::UndoRedo::ObjectHistory< MutableHistoryInterval >.
immutable_object_ptr()
virtual const void * Slic3r::UndoRedo::ObjectHistoryBase::immutable_object_ptr () const inline virtual
Reimplemented in Slic3r::UndoRedo::ImmutableObjectHistory< T >.
{ return nullptr; }
is_immutable()
virtual bool Slic3r::UndoRedo::ObjectHistoryBase::is_immutable () const pure virtual
Implemented in Slic3r::UndoRedo::ImmutableObjectHistory< T >, and Slic3r::UndoRedo::MutableObjectHistory< T >.
is_mutable()
virtual bool Slic3r::UndoRedo::ObjectHistoryBase::is_mutable () const pure virtual
Implemented in Slic3r::UndoRedo::ImmutableObjectHistory< T >, and Slic3r::UndoRedo::MutableObjectHistory< T >.
is_optional()
virtual bool Slic3r::UndoRedo::ObjectHistoryBase::is_optional () const inline virtual
Reimplemented in Slic3r::UndoRedo::ImmutableObjectHistory< T >.
{ return false; }
memsize()
virtual size_t Slic3r::UndoRedo::ObjectHistoryBase::memsize () const pure virtual
Implemented in Slic3r::UndoRedo::ImmutableObjectHistory< T >, and Slic3r::UndoRedo::MutableObjectHistory< T >.
release_after_timestamp()
virtual size_t Slic3r::UndoRedo::ObjectHistoryBase::release_after_timestamp (size_t timestamp) pure virtual
Implemented in Slic3r::UndoRedo::ObjectHistory< T >, Slic3r::UndoRedo::ObjectHistory< Interval >, and Slic3r::UndoRedo::ObjectHistory< MutableHistoryInterval >.
release_before_timestamp()
virtual size_t Slic3r::UndoRedo::ObjectHistoryBase::release_before_timestamp (size_t timestamp) pure virtual
Implemented in Slic3r::UndoRedo::ObjectHistory< T >, Slic3r::UndoRedo::ObjectHistory< Interval >, and Slic3r::UndoRedo::ObjectHistory< MutableHistoryInterval >.
release_between_timestamps()
virtual size_t Slic3r::UndoRedo::ObjectHistoryBase::release_between_timestamps (size_t timestamp_start, size_t timestamp_end) pure virtual
Implemented in Slic3r::UndoRedo::ObjectHistory< T >, Slic3r::UndoRedo::ObjectHistory< Interval >, and Slic3r::UndoRedo::ObjectHistory< MutableHistoryInterval >.
release_optional()
virtual size_t Slic3r::UndoRedo::ObjectHistoryBase::release_optional () pure virtual
Implemented in Slic3r::UndoRedo::ImmutableObjectHistory< T >, and Slic3r::UndoRedo::MutableObjectHistory< T >.
restore_optional()
virtual void Slic3r::UndoRedo::ObjectHistoryBase::restore_optional () pure virtual
Implemented in Slic3r::UndoRedo::ImmutableObjectHistory< T >, and Slic3r::UndoRedo::MutableObjectHistory< T >.
valid()
virtual bool Slic3r::UndoRedo::ObjectHistoryBase::valid () pure virtual
Implemented in Slic3r::UndoRedo::ImmutableObjectHistory< T >, and Slic3r::UndoRedo::MutableObjectHistory< T >.
Referenced by Slic3r::UndoRedo::ObjectHistory< T >::release_after_timestamp(), Slic3r::UndoRedo::ObjectHistory< T >::release_before_timestamp(), and Slic3r::UndoRedo::ObjectHistory< T >::release_between_timestamps().
The documentation for this class was generated from the following file:
src/slic3r/Utils/UndoRedo.cpp