Prusa Slicer: src/avrdude/usbasp.c File Reference
usbasp.c File Reference
#include "ac_cfg.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <sys/time.h>
#include <unistd.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "usbasp.h"
#include "usbdevs.h"
Functions
static int usbasp_nousb_open (struct programmer_t *pgm, char *name)
void usbasp_initpgm (PROGRAMMER *pgm)
Variables
const char usbasp_desc [] = "USBasp programmer, see http://www.fischl.de/usbasp/"
Function Documentation
usbasp_initpgm()
void usbasp_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "usbasp");
  pgm->open           = usbasp_nousb_open;
}
References programmer_t::open, pgm, programmer_t::type, and usbasp_nousb_open().
usbasp_nousb_open()
static int usbasp_nousb_open (struct programmer_t * pgm, char * name) static
{
  avrdude_message(MSG_INFO, "%s: error: no usb support. please compile again with libusb installed.\n",
    progname);
  return -1;
}
References avrdude_message(), MSG_INFO, and progname.
Referenced by usbasp_initpgm().
Variable Documentation
usbasp_desc
const char usbasp_desc[] = "USBasp programmer, see http://www.fischl.de/usbasp/"