Prusa Slicer: marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA > Struct Reference
marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA > Struct Reference
Public Types
using Rst = Slic3r::sla::RasterGrayscaleAA
using ValueType = uint8_t
Static Public Member Functions
static uint8_t get (const Rst &rst, size_t row, size_t col)
static size_t rows (const Rst &rst)
static size_t cols (const Rst &rst)
Detailed Description
Member Typedef Documentation
Rst
using marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA >::Rst = Slic3r::sla::RasterGrayscaleAA
ValueType
using marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA >::ValueType = uint8_t
Member Function Documentation
cols()
static size_t marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA >::cols (const Rst & rst) inline static
{ return rst.resolution().width_px; }
References Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::resolution(), and Slic3r::sla::Resolution::width_px.
get()
static uint8_t marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA >::get (const Rst & rst, size_t row, size_t col) inline static
{ return rst.read_pixel(col, row); }
References col(), Slic3r::sla::RasterGrayscaleAA::read_pixel(), and row().
rows()
static size_t marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA >::rows (const Rst & rst) inline static
{ return rst.resolution().height_px; }
References Slic3r::sla::Resolution::height_px, and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::resolution().
The documentation for this struct was generated from the following file:
src/libslic3r/SLA/RasterToPolygons.cpp