Prusa Slicer: Slic3r::FFFTreeSupport::RichInterfacePlacer Class Reference
Slic3r::FFFTreeSupport::RichInterfacePlacer Class Reference
Public Member Functions
RichInterfacePlacer (const InterfacePlacer &interface_placer, const TreeModelVolumes &volumes, bool force_tip_to_roof, size_t num_support_layers, std::vector< SupportElements > &move_bounds)
void add_points_along_lines (LineInformations lines, LayerIndex insert_layer_idx, size_t roof_tip_layers, size_t supports_roof_layers, size_t dont_move_until)
SupportGeneratorLayersPtr & top_contacts_mutable ()
void add_roofs (std::vector< Polygons > &&new_roofs, const size_t insert_layer_idx)
void add_roof (Polygons &&new_roof, const size_t insert_layer_idx, const size_t dtt_tip)
void add_roof_build_plate (Polygons &&overhang_areas, size_t dtt_roof)
void add_roof_unguarded (Polygons &&new_roofs, const size_t insert_layer_idx, const size_t dtt_roof)
Public Attributes
const TreeModelVolumes & volumes
const bool force_tip_to_roof
bool min_xy_dist
const SlicingParameters & slicing_parameters
const SupportParameters & support_parameters
const TreeSupportSettings & config
Private Member Functions
void add_point_as_influence_area (std::pair< Point, LineStatus > p, LayerIndex insert_layer, size_t dont_move_until, bool roof, bool skip_ovalisation)
Private Attributes
std::vector< SupportElements > & move_bounds
const Polygon m_base_circle { make_circle(m_base_radius, SUPPORT_TREE_CIRCLE_RESOLUTION) }
std::mutex m_mutex_movebounds
std::vector< std::unordered_set< Point, PointHash > > m_already_inserted
SupportGeneratorLayerStorage & layer_storage
SupportGeneratorLayersPtr & top_contacts
SupportGeneratorLayersPtr & top_interfaces
SupportGeneratorLayersPtr & top_base_interfaces
std::mutex m_mutex_layer_storage
Static Private Attributes
static constexpr const auto m_base_radius = scaled<int>(0.01)
Detailed Description
Constructor & Destructor Documentation
RichInterfacePlacer()
Slic3r::FFFTreeSupport::RichInterfacePlacer::RichInterfacePlacer (const InterfacePlacer & interface_placer, const TreeModelVolumes & volumes, bool force_tip_to_roof, size_t num_support_layers, std::vector< SupportElements > & move_bounds) inline
    :
        InterfacePlacer(interface_placer),
        volumes(volumes), force_tip_to_roof(force_tip_to_roof), move_bounds(move_bounds)
    {
        m_already_inserted.assign(num_support_layers, {});
        this->min_xy_dist = this->config.xy_distance > this->config.xy_min_distance;
    }
References m_already_inserted, min_xy_dist, Slic3r::FFFTreeSupport::TreeSupportSettings::xy_distance, and Slic3r::FFFTreeSupport::TreeSupportSettings::xy_min_distance.
Member Function Documentation
add_point_as_influence_area()
void Slic3r::FFFTreeSupport::RichInterfacePlacer::add_point_as_influence_area (std::pair< Point, LineStatus > p, LayerIndex insert_layer, size_t dont_move_until, bool roof, bool skip_ovalisation) inline private
    {
        bool to_bp = p.second == LineStatus::TO_BP || p.second == LineStatus::TO_BP_SAFE;
        bool gracious = to_bp || p.second == LineStatus::TO_MODEL_GRACIOUS || p.second == LineStatus::TO_MODEL_GRACIOUS_SAFE;
        bool safe_radius = p.second == LineStatus::TO_BP_SAFE || p.second == LineStatus::TO_MODEL_GRACIOUS_SAFE;
        if (! config.support_rests_on_model && ! to_bp) {
            BOOST_LOG_TRIVIAL(warning) << "Tried to add an invalid support point";
            tree_supports_show_error("Unable to add tip. Some overhang may not be supported correctly."sv, true);
            return;
        }
        Polygons circle{ m_base_circle };
        circle.front().translate(p.first);
        {
            Point hash_pos = p.first / ((config.min_radius + 1) / 10);
            std::lock_guard<std::mutex> critical_section_movebounds(m_mutex_movebounds);
            if (!m_already_inserted[insert_layer].count(hash_pos)) {
                // normalize the point a bit to also catch points which are so close that inserting it would achieve nothing
                m_already_inserted[insert_layer].emplace(hash_pos);
                static constexpr const size_t dtt = 0;
                SupportElementState state;
                state.target_height = insert_layer;
                state.target_position = p.first;
                state.next_position = p.first;
                state.layer_idx = insert_layer;
                state.effective_radius_height = dtt;
                state.to_buildplate = to_bp;
                state.distance_to_top = dtt;
                state.result_on_layer = p.first;
                assert(state.result_on_layer_is_set());
                state.increased_to_model_radius = 0;
                state.to_model_gracious = gracious;
                state.elephant_foot_increases = 0;
                state.use_min_xy_dist = min_xy_dist;
                state.supports_roof = roof;
                state.dont_move_until = dont_move_until;
                state.can_use_safe_radius = safe_radius;
                state.missing_roof_layers = force_tip_to_roof ? dont_move_until : 0;
                state.skip_ovalisation = skip_ovalisation;
                move_bounds[insert_layer].emplace_back(state, std::move(circle));
            }
        }
    }
References Slic3r::FFFTreeSupport::SupportElementStateBits::can_use_safe_radius, Slic3r::FFFTreeSupport::InterfacePlacer::config, Slic3r::FFFTreeSupport::SupportElementState::distance_to_top, Slic3r::FFFTreeSupport::SupportElementState::dont_move_until, Slic3r::FFFTreeSupport::SupportElementState::effective_radius_height, Slic3r::FFFTreeSupport::SupportElementState::elephant_foot_increases, force_tip_to_roof, Slic3r::MultiPoint::front(), Slic3r::FFFTreeSupport::SupportElementState::increased_to_model_radius, Slic3r::FFFTreeSupport::SupportElementState::layer_idx, m_already_inserted, m_base_circle, m_mutex_movebounds, Slic3r::FFFTreeSupport::TreeSupportSettings::min_radius, min_xy_dist, Slic3r::FFFTreeSupport::SupportElementState::missing_roof_layers, move_bounds, Slic3r::FFFTreeSupport::SupportElementState::next_position, Slic3r::FFFTreeSupport::SupportElementState::result_on_layer, Slic3r::FFFTreeSupport::SupportElementState::result_on_layer_is_set(), Slic3r::FFFTreeSupport::SupportElementStateBits::skip_ovalisation, Slic3r::FFFTreeSupport::TreeSupportSettings::support_rests_on_model, Slic3r::FFFTreeSupport::SupportElementStateBits::supports_roof, Slic3r::FFFTreeSupport::SupportElementState::target_height, Slic3r::FFFTreeSupport::SupportElementState::target_position, Slic3r::FFFTreeSupport::TO_BP, Slic3r::FFFTreeSupport::TO_BP_SAFE, Slic3r::FFFTreeSupport::SupportElementStateBits::to_buildplate, Slic3r::FFFTreeSupport::TO_MODEL_GRACIOUS, Slic3r::FFFTreeSupport::SupportElementStateBits::to_model_gracious, Slic3r::FFFTreeSupport::TO_MODEL_GRACIOUS_SAFE, Slic3r::FFFTreeSupport::tree_supports_show_error(), and Slic3r::FFFTreeSupport::SupportElementStateBits::use_min_xy_dist.
Referenced by add_points_along_lines().
add_points_along_lines()
void Slic3r::FFFTreeSupport::RichInterfacePlacer::add_points_along_lines (LineInformations lines, LayerIndex insert_layer_idx, size_t roof_tip_layers, size_t supports_roof_layers, size_t dont_move_until) inline
    {
        validate_range(lines);
        // Add tip area as roof (happens when minimum roof area > minimum tip area) if possible
        size_t dtt_roof_tip;
        for (dtt_roof_tip = 0; dtt_roof_tip < roof_tip_layers && insert_layer_idx - dtt_roof_tip >= 1; ++ dtt_roof_tip) {
            size_t this_layer_idx = insert_layer_idx - dtt_roof_tip;
            auto evaluateRoofWillGenerate = [&](const std::pair<Point, LineStatus> &p) {
                //FIXME Vojtech: The circle is just shifted, it has a known size, the infill should fit all the time!
    #if 0
                Polygon roof_circle;
                for (Point corner : base_circle)
                    roof_circle.points.emplace_back(p.first + corner * config.min_radius);
                return !generate_support_infill_lines({ roof_circle }, config, true, insert_layer_idx - dtt_roof_tip, config.support_roof_line_distance).empty();
    #else
                return true;
    #endif
            };
            {
                std::pair<LineInformations, LineInformations> split =
                    // keep all lines that are still valid on the next layer
                    split_lines(lines, [this, this_layer_idx](const std::pair<Point, LineStatus> &p)
                        { return evaluate_point_for_next_layer_function(volumes, config, this_layer_idx, p); });
                LineInformations points = std::move(split.second);
                // Not all roofs are guaranteed to actually generate lines, so filter these out and add them as points.
                split = split_lines(split.first, evaluateRoofWillGenerate);
                lines = std::move(split.first);
                append(points, split.second);
                // add all points that would not be valid
                for (const LineInformation &line : points)
                    for (const std::pair<Point, LineStatus> &point_data : line)
                        add_point_as_influence_area(point_data, this_layer_idx,
                            // don't move until
                            roof_tip_layers - dtt_roof_tip,
                            // supports roof
                            dtt_roof_tip + supports_roof_layers > 0,
                            // disable ovalization
                            false);
            }
            // add all tips as roof to the roof storage
            Polygons new_roofs;
            for (const LineInformation &line : lines)
                //FIXME sweep the tip radius along the line?
                for (const std::pair<Point, LineStatus> &p : line) {
                    Polygon roof_circle{ m_base_circle };
                    roof_circle.scale(config.min_radius / m_base_radius);
                    roof_circle.translate(p.first);
                    new_roofs.emplace_back(std::move(roof_circle));
                }
            this->add_roof(std::move(new_roofs), this_layer_idx, dtt_roof_tip + supports_roof_layers);
        }
        for (const LineInformation &line : lines) {
            // If a line consists of enough tips, the assumption is that it is not a single tip, but part of a simulated support pattern.
            // Ovalisation should be disabled for these to improve the quality of the lines when tip_diameter=line_width
            bool disable_ovalistation = config.min_radius < 3 * config.support_line_width && roof_tip_layers == 0 && dtt_roof_tip == 0 && line.size() > 5;
            for (const std::pair<Point, LineStatus> &point_data : line)
                add_point_as_influence_area(point_data, insert_layer_idx - dtt_roof_tip,
                    // don't move until
                    dont_move_until > dtt_roof_tip ? dont_move_until - dtt_roof_tip : 0,
                    // supports roof
                    dtt_roof_tip + supports_roof_layers > 0,
                    disable_ovalistation);
        }
    }
References add_point_as_influence_area(), Slic3r::FFFTreeSupport::InterfacePlacer::add_roof(), Slic3r::append(), Slic3r::FFFTreeSupport::InterfacePlacer::config, Slic3r::empty(), Slic3r::FFFTreeSupport::evaluate_point_for_next_layer_function(), Slic3r::FFFTreeSupport::generate_support_infill_lines(), m_base_circle, m_base_radius, Slic3r::FFFTreeSupport::TreeSupportSettings::min_radius, Slic3r::MultiPoint::points, Slic3r::MultiPoint::scale(), Slic3r::FFFTreeSupport::split_lines(), Slic3r::FFFTreeSupport::TreeSupportSettings::support_line_width, Slic3r::FFFTreeSupport::TreeSupportSettings::support_roof_line_distance, Slic3r::FFFTreeSupport::validate_range(), and volumes.
Referenced by Slic3r::FFFTreeSupport::sample_overhang_area().
add_roof()
void Slic3r::FFFTreeSupport::InterfacePlacer::add_roof (Polygons && new_roof, const size_t insert_layer_idx, const size_t dtt_tip) inline inherited
    {
        std::lock_guard<std::mutex> lock(m_mutex_layer_storage);
        add_roof_unguarded(std::move(new_roof), insert_layer_idx, dtt_tip);
    }
References Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded(), and Slic3r::FFFTreeSupport::InterfacePlacer::m_mutex_layer_storage.
Referenced by add_points_along_lines().
add_roof_build_plate()
void Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_build_plate (Polygons && overhang_areas, size_t dtt_roof) inline inherited
    {
        std::lock_guard<std::mutex> lock(m_mutex_layer_storage);
        this->add_roof_unguarded(std::move(overhang_areas), 0, std::min(dtt_roof, this->support_parameters.num_top_interface_layers));
    }
References Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded(), Slic3r::FFFTreeSupport::InterfacePlacer::m_mutex_layer_storage, and Slic3r::FFFSupport::SupportParameters::num_top_interface_layers.
Referenced by Slic3r::FFFTreeSupport::sample_overhang_area().
add_roof_unguarded()
void Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded (Polygons && new_roofs, const size_t insert_layer_idx, const size_t dtt_roof) inline inherited
    {
        assert(support_parameters.has_top_contacts);
        assert(dtt_roof <= support_parameters.num_top_interface_layers);
        SupportGeneratorLayersPtr &layers =
            dtt_roof == 0 ? this->top_contacts :
            dtt_roof <= support_parameters.num_top_interface_layers_only() ? this->top_interfaces : this->top_base_interfaces;
        SupportGeneratorLayer*& l = layers[insert_layer_idx];
        if (l == nullptr)
            l = &layer_allocate_unguarded(layer_storage, dtt_roof == 0 ? SupporLayerType::TopContact : SupporLayerType::TopInterface,
                    slicing_parameters, config, insert_layer_idx);
        // will be unioned in finalize_interface_and_support_areas()
        append(l->polygons, std::move(new_roofs));
    }
References Slic3r::append(), Slic3r::FFFTreeSupport::InterfacePlacer::config, Slic3r::FFFSupport::SupportParameters::has_top_contacts, Slic3r::FFFTreeSupport::layer_allocate_unguarded(), Slic3r::FFFTreeSupport::InterfacePlacer::layer_storage, Slic3r::FFFSupport::SupportParameters::num_top_interface_layers, Slic3r::FFFSupport::SupportParameters::num_top_interface_layers_only(), Slic3r::FFFSupport::SupportGeneratorLayer::polygons, Slic3r::FFFTreeSupport::InterfacePlacer::slicing_parameters, Slic3r::FFFTreeSupport::InterfacePlacer::support_parameters, Slic3r::FFFTreeSupport::InterfacePlacer::top_base_interfaces, Slic3r::FFFTreeSupport::InterfacePlacer::top_contacts, and Slic3r::FFFTreeSupport::InterfacePlacer::top_interfaces.
Referenced by Slic3r::FFFTreeSupport::InterfacePlacer::add_roof(), Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_build_plate(), Slic3r::FFFTreeSupport::InterfacePlacer::add_roofs(), and Slic3r::FFFTreeSupport::generate_raft_contact().
add_roofs()
void Slic3r::FFFTreeSupport::InterfacePlacer::add_roofs (std::vector< Polygons > && new_roofs, const size_t insert_layer_idx) inline inherited
    {
        if (! new_roofs.empty()) {
            std::lock_guard<std::mutex> lock(m_mutex_layer_storage);
            for (size_t idx = 0; idx < new_roofs.size(); ++ idx)
                if (! new_roofs[idx].empty())
                    add_roof_unguarded(std::move(new_roofs[idx]), insert_layer_idx - idx, idx);
        }
    }
References Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded(), Slic3r::empty(), and Slic3r::FFFTreeSupport::InterfacePlacer::m_mutex_layer_storage.
Referenced by Slic3r::FFFTreeSupport::sample_overhang_area().
top_contacts_mutable()
SupportGeneratorLayersPtr & Slic3r::FFFTreeSupport::InterfacePlacer::top_contacts_mutable () inline inherited
{ return this->top_contacts; }
References Slic3r::FFFTreeSupport::InterfacePlacer::top_contacts.
Member Data Documentation
config
const TreeSupportSettings& Slic3r::FFFTreeSupport::InterfacePlacer::config inherited
Referenced by add_point_as_influence_area(), add_points_along_lines(), Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded(), and Slic3r::FFFTreeSupport::sample_overhang_area().
force_tip_to_roof
const bool Slic3r::FFFTreeSupport::RichInterfacePlacer::force_tip_to_roof
Referenced by add_point_as_influence_area(), and Slic3r::FFFTreeSupport::sample_overhang_area().
layer_storage
SupportGeneratorLayerStorage& Slic3r::FFFTreeSupport::InterfacePlacer::layer_storage private inherited
Referenced by Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded().
m_already_inserted
std::vector<std::unordered_set<Point, PointHash> > Slic3r::FFFTreeSupport::RichInterfacePlacer::m_already_inserted private
Referenced by RichInterfacePlacer(), and add_point_as_influence_area().
m_base_circle
const Polygon Slic3r::FFFTreeSupport::RichInterfacePlacer::m_base_circle { make_circle(m_base_radius, SUPPORT_TREE_CIRCLE_RESOLUTION) } private
Referenced by add_point_as_influence_area(), and add_points_along_lines().
m_base_radius
constexpr const auto Slic3r::FFFTreeSupport::RichInterfacePlacer::m_base_radius = scaled<int>(0.01) static constexpr private
Referenced by add_points_along_lines().
m_mutex_layer_storage
std::mutex Slic3r::FFFTreeSupport::InterfacePlacer::m_mutex_layer_storage private inherited
Referenced by Slic3r::FFFTreeSupport::InterfacePlacer::add_roof(), Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_build_plate(), and Slic3r::FFFTreeSupport::InterfacePlacer::add_roofs().
m_mutex_movebounds
std::mutex Slic3r::FFFTreeSupport::RichInterfacePlacer::m_mutex_movebounds private
Referenced by add_point_as_influence_area().
min_xy_dist
bool Slic3r::FFFTreeSupport::RichInterfacePlacer::min_xy_dist
Referenced by RichInterfacePlacer(), and add_point_as_influence_area().
move_bounds
std::vector<SupportElements>& Slic3r::FFFTreeSupport::RichInterfacePlacer::move_bounds private
Referenced by add_point_as_influence_area().
slicing_parameters
const SlicingParameters& Slic3r::FFFTreeSupport::InterfacePlacer::slicing_parameters inherited
Referenced by Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded(), and Slic3r::FFFTreeSupport::generate_support_areas().
support_parameters
const SupportParameters& Slic3r::FFFTreeSupport::InterfacePlacer::support_parameters inherited
Referenced by Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded(), Slic3r::FFFTreeSupport::generate_initial_areas(), and Slic3r::FFFTreeSupport::sample_overhang_area().
top_base_interfaces
SupportGeneratorLayersPtr& Slic3r::FFFTreeSupport::InterfacePlacer::top_base_interfaces private inherited
Referenced by Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded().
top_contacts
SupportGeneratorLayersPtr& Slic3r::FFFTreeSupport::InterfacePlacer::top_contacts private inherited
Referenced by Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded(), and Slic3r::FFFTreeSupport::InterfacePlacer::top_contacts_mutable().
top_interfaces
SupportGeneratorLayersPtr& Slic3r::FFFTreeSupport::InterfacePlacer::top_interfaces private inherited
Referenced by Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded().
volumes
const TreeModelVolumes& Slic3r::FFFTreeSupport::RichInterfacePlacer::volumes
Referenced by add_points_along_lines(), and Slic3r::FFFTreeSupport::sample_overhang_area().
The documentation for this class was generated from the following file:
src/libslic3r/Support/TreeSupport.cpp