Prusa Slicer: Slic3r::FirmwareDialog Class Reference
Slic3r::FirmwareDialog Class Reference
#include <src/slic3r/GUI/FirmwareDialog.hpp>
Classes
struct priv
Public Member Functions
FirmwareDialog (wxWindow *parent)
FirmwareDialog (FirmwareDialog &&)=delete
FirmwareDialog (const FirmwareDialog &)=delete
FirmwareDialog & operator= (FirmwareDialog &&)=delete
FirmwareDialog & operator= (const FirmwareDialog &)=delete
~FirmwareDialog ()
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
Static Public Member Functions
static void run (wxWindow *parent)
Protected Member Functions
void on_dpi_changed (const wxRect &suggested_rect) override
virtual void on_sys_color_changed ()
Private Types
enum {
DIALOG_MARGIN = 15 , SPACING = 10 , MIN_WIDTH = 50 , MIN_HEIGHT = 25 ,
MIN_HEIGHT_EXPANDED = 40
}
Private Member Functions
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
std::unique_ptr< priv > p
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
DIALOG_MARGIN
SPACING
MIN_WIDTH
MIN_HEIGHT
MIN_HEIGHT_EXPANDED
         {
        DIALOG_MARGIN = 15,
        SPACING = 10,
        MIN_WIDTH = 50,
        MIN_HEIGHT = /*18*/25,
        MIN_HEIGHT_EXPANDED = 40,
    };
Constructor & Destructor Documentation
FirmwareDialog() [1/3]
Slic3r::FirmwareDialog::FirmwareDialog (wxWindow * parent)
                                               :
  GUI::DPIDialog(parent, wxID_ANY, _(L("Firmware flasher")), wxDefaultPosition, wxDefaultSize, wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
  p(new priv(this))
{
  const int em = GUI::wxGetApp().em_unit();
  p->min_width = MIN_WIDTH * em;
  p->min_height = MIN_HEIGHT * em;
  p->min_height_expanded = MIN_HEIGHT_EXPANDED * em;
    /* get current font from application,
     * because of wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT) function
     * returns font for primary Display
     */
    const wxFont& font = GUI::wxGetApp().normal_font();
    SetFont(font);
    wxFont status_font = font;//wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
  status_font.MakeBold();
  wxFont mono_font = GUI::wxGetApp().code_font();
  mono_font.MakeSmaller();
  // Create GUI components and layout
  auto *panel = new wxPanel(this);
  wxBoxSizer *vsizer = new wxBoxSizer(wxVERTICAL);
  panel->SetSizer(vsizer);
  auto *label_hex_picker = new wxStaticText(panel, wxID_ANY, _(L("Firmware image:")));
  p->hex_picker = new wxFilePickerCtrl(panel, wxID_ANY, wxEmptyString, /*wxFileSelectorPromptStr*/_L("Select a file"),
    "Hex files (*.hex)|*.hex|All files|*.*");
  p->hex_picker->GetPickerCtrl()->SetLabelText(_(L("Browse")));
  auto *label_port_picker = new wxStaticText(panel, wxID_ANY, _(L("Serial port:")));
  p->port_picker = new wxComboBox(panel, wxID_ANY);
  p->txt_port_autodetect = new wxStaticText(panel, wxID_ANY, _(L("Autodetected")));
  p->btn_rescan = new wxButton(panel, wxID_ANY, _(L("Rescan")));
  auto *port_sizer = new wxBoxSizer(wxHORIZONTAL);
  port_sizer->Add(p->port_picker, 1, wxEXPAND | wxRIGHT, SPACING);
  port_sizer->Add(p->btn_rescan, 0);
  port_sizer->Add(p->txt_port_autodetect, 1, wxEXPAND);
  p->set_autodetect(false);
  auto *label_progress = new wxStaticText(panel, wxID_ANY, _(L("Progress:")));
  p->progressbar = new wxGauge(panel, wxID_ANY, 1, wxDefaultPosition, wxDefaultSize, wxGA_HORIZONTAL | wxGA_SMOOTH);
  auto *label_status = new wxStaticText(panel, wxID_ANY, _(L("Status:")));
  p->txt_status = new wxStaticText(panel, wxID_ANY, _(L("Ready")));
  p->txt_status->SetFont(status_font);
  auto *grid = new wxFlexGridSizer(2, SPACING, SPACING);
  grid->AddGrowableCol(1);
  grid->Add(label_hex_picker, 0, wxALIGN_CENTER_VERTICAL);
  grid->Add(p->hex_picker, 0, wxEXPAND);
  grid->Add(label_port_picker, 0, wxALIGN_CENTER_VERTICAL);
  grid->Add(port_sizer, 0, wxEXPAND);
  grid->Add(label_progress, 0, wxALIGN_CENTER_VERTICAL);
  grid->Add(p->progressbar, 1, wxEXPAND | wxALIGN_CENTER_VERTICAL);
  grid->Add(label_status, 0, wxALIGN_CENTER_VERTICAL);
  grid->Add(p->txt_status, 0, wxEXPAND);
  vsizer->Add(grid, 0, wxEXPAND | wxTOP | wxBOTTOM, SPACING);
  p->spoiler = new wxCollapsiblePane(panel, wxID_ANY, _(L("Advanced: Output log")), wxDefaultPosition, wxDefaultSize, wxCP_DEFAULT_STYLE | wxCP_NO_TLW_RESIZE);
  auto *spoiler_pane = p->spoiler->GetPane();
  auto *spoiler_sizer = new wxBoxSizer(wxVERTICAL);
  p->txt_stdout = new wxTextCtrl(spoiler_pane, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE | wxTE_READONLY);
  p->txt_stdout->SetFont(mono_font);
  spoiler_sizer->Add(p->txt_stdout, 1, wxEXPAND);
  spoiler_pane->SetSizer(spoiler_sizer);
  // The doc says proportion need to be 0 for wxCollapsiblePane.
  // Experience says it needs to be 1, otherwise things won't get sized properly.
  vsizer->Add(p->spoiler, 1, wxEXPAND | wxBOTTOM, SPACING);
  p->btn_close = new wxButton(panel, wxID_CLOSE, _(L("Close")));   // Note: The label needs to be present, otherwise we get accelerator bugs on Mac
  p->btn_flash = new wxButton(panel, wxID_ANY, p->btn_flash_label_ready);
  p->btn_flash->Disable();
  auto *bsizer = new wxBoxSizer(wxHORIZONTAL);
  bsizer->Add(p->btn_close);
  bsizer->AddStretchSpacer();
  bsizer->Add(p->btn_flash);
  vsizer->Add(bsizer, 0, wxEXPAND);
  GUI::wxGetApp().UpdateDlgDarkUI(this);
  auto *topsizer = new wxBoxSizer(wxVERTICAL);
  topsizer->Add(panel, 1, wxEXPAND | wxALL, DIALOG_MARGIN);
  SetMinSize(wxSize(p->min_width, p->min_height));
  SetSizerAndFit(topsizer);
  const auto size = GetSize();
  SetSize(std::max(size.GetWidth(), static_cast<int>(p->min_width)), std::max(size.GetHeight(), static_cast<int>(p->min_height)));
  Layout();
  SetEscapeId(wxID_CLOSE); // To close the dialog using "Esc" button
  // Bind events
  p->hex_picker->Bind(wxEVT_FILEPICKER_CHANGED, [this](wxFileDirPickerEvent& evt) {
    if (wxFileExists(evt.GetPath())) {
      this->p->load_hex_file(evt.GetPath());
    }
    p->update_flash_enabled();
  });
  p->port_picker->Bind(wxEVT_COMBOBOX, [this](wxCommandEvent &) { p->update_flash_enabled(); });
  p->port_picker->Bind(wxEVT_TEXT, [this](wxCommandEvent &) { p->update_flash_enabled(); });
  p->spoiler->Bind(wxEVT_COLLAPSIBLEPANE_CHANGED, [=](wxCollapsiblePaneEvent &evt) {
    if (evt.GetCollapsed()) {
      this->SetMinSize(wxSize(p->min_width, p->min_height));
      const auto new_height = this->GetSize().GetHeight() - this->p->txt_stdout->GetSize().GetHeight();
      this->SetSize(this->GetSize().GetWidth(), new_height);
    } else {
      this->SetMinSize(wxSize(p->min_width, p->min_height_expanded));
    }
    this->Layout();
    this->p->fit_no_shrink();
  });
  p->btn_rescan->Bind(wxEVT_BUTTON, [this](wxCommandEvent &) { this->p->find_serial_ports(); });
  p->btn_flash->Bind(wxEVT_BUTTON, [this](wxCommandEvent &) {
    if (this->p->avrdude) {
      // Flashing is in progress, ask the user if they're really sure about canceling it
      //wxMessageDialog dlg(this,
      GUI::MessageDialog dlg(this,
        _(L("Are you sure you want to cancel firmware flashing?\nThis could leave your printer in an unusable state!")),
        _(L("Confirmation")),
        wxYES_NO | wxNO_DEFAULT | wxICON_QUESTION);
      if (dlg.ShowModal() == wxID_YES) {
        this->p->set_txt_status(_(L("Cancelling...")));
        this->p->user_cancel();
      }
    } else {
      // Start a flashing task
      this->p->perform_upload();
    }
  });
  Bind(wxEVT_TIMER, [this](wxTimerEvent &evt) { this->p->progressbar->Pulse(); });
  Bind(EVT_AVRDUDE, [this](wxCommandEvent &evt) { this->p->on_avrdude(evt); });
  Bind(EVT_ASYNC_DIALOG, [this](wxCommandEvent &evt) { this->p->on_async_dialog(evt); });
  Bind(wxEVT_CLOSE_WINDOW, [this](wxCloseEvent &evt) {
    if (this->p->avrdude) {
      evt.Veto();
    } else {
            this->EndModal(wxID_CLOSE);
      evt.Skip();
    }
  });
  p->find_serial_ports();
}
References _, _L, DIALOG_MARGIN, Slic3r::grid(), L, MIN_HEIGHT, MIN_HEIGHT_EXPANDED, MIN_WIDTH, p, SPACING, and wxEVT_BUTTON.
FirmwareDialog() [2/3]
Slic3r::FirmwareDialog::FirmwareDialog (FirmwareDialog &&) delete
FirmwareDialog() [3/3]
Slic3r::FirmwareDialog::FirmwareDialog (const FirmwareDialog &) delete
~FirmwareDialog()
Slic3r::FirmwareDialog::~FirmwareDialog ()
{
  // Needed bacuse of forward defs
}
Member Function Documentation
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::FileArchiveDialog::FileArchiveDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::ExtruderSequenceDialog::apply_extruder_sequence(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::DiffPresetDialog::complete_dialog_creation(), Slic3r::GUI::DiffPresetDialog::create_edit_sizer(), Slic3r::GUI::DiffPresetDialog::create_presets_sizer(), Slic3r::GUI::DiffPresetDialog::create_tree(), em_unit(), Slic3r::GUI::SavePresetDialog::Item::init_input_name_ctrl(), Slic3r::Search::SearchDialog::msw_rescale(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigSnapshotDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::FileArchiveDialog::on_dpi_changed(), on_dpi_changed(), Slic3r::GUI::GalleryDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::LoadProjectsDialog::on_dpi_changed(), Slic3r::GUI::ProjectDropDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
Referenced by Slic3r::GUI::MainFrame::update_layout().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigSnapshotDialog::ConfigSnapshotDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ExtruderSequenceDialog::ExtruderSequenceDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::LoadProjectsDialog::LoadProjectsDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::MainFrame::init_tabpanel(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::MainFrame::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
on_dpi_changed()
void Slic3r::FirmwareDialog::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    const int& em = em_unit();
    msw_buttons_rescale(this, em, { p->btn_close->GetId(),
                                    p->btn_rescan->GetId(),
                                    p->btn_flash->GetId(),
                                    p->hex_picker->GetPickerCtrl()->GetId()
                                                            });
    p->min_width = MIN_WIDTH * em;
    p->min_height = MIN_HEIGHT * em;
    p->min_height_expanded = MIN_HEIGHT_EXPANDED * em;
    const int min_height = p->spoiler->IsExpanded() ? p->min_height_expanded : p->min_height;
    SetMinSize(wxSize(p->min_width, min_height));
    Fit();
    Refresh();
}
References Slic3r::GUI::DPIAware< P >::em_unit(), MIN_HEIGHT, MIN_HEIGHT_EXPANDED, MIN_WIDTH, msw_buttons_rescale(), and p.
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::GalleryDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PreferencesDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::Search::SearchDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
operator=() [1/2]
FirmwareDialog & Slic3r::FirmwareDialog::operator= (const FirmwareDialog &) delete
operator=() [2/2]
FirmwareDialog & Slic3r::FirmwareDialog::operator= (FirmwareDialog &&) delete
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DiffPresetDialog::on_dpi_changed().
run()
void Slic3r::FirmwareDialog::run (wxWindow * parent) static
{
  FirmwareDialog dialog(parent);
  dialog.ShowModal();
}
Referenced by Slic3r::GUI::GUI_App::add_config_menu(), and Slic3r::FirmwareDialog::priv::perform_upload().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
Member Data Documentation
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
p
std::unique_ptr<priv> Slic3r::FirmwareDialog::p private
Referenced by FirmwareDialog(), and on_dpi_changed().
The documentation for this class was generated from the following files:
src/slic3r/GUI/FirmwareDialog.hpp
src/slic3r/GUI/FirmwareDialog.cpp