Prusa Slicer: Slic3r::opt::detail::NLoptOpt< M, class > Class Template Reference
Slic3r::opt::detail::NLoptOpt< M, class > Class Template Reference
#include <src/libslic3r/Optimize/NLoptOptimizer.hpp>
Classes
struct OptData
Public Member Functions
template<class Fn , size_t N, class... EqFns, class... IneqFns>
Result< N > optimize (Fn &&f, const Input< N > &initvals, const Bounds< N > &bounds, const std::tuple< EqFns... > &equalities, const std::tuple< IneqFns... > &inequalities)
NLoptOpt (const StopCriteria &stopcr_glob={})
void set_criteria (const StopCriteria &cr)
const StopCriteria & get_criteria () const noexcept
void set_loc_criteria (const StopCriteria &cr)
const StopCriteria & get_loc_criteria () const noexcept
void set_dir (OptDir dir) noexcept
void seed (long s)
Private Member Functions
template<class Fn , size_t N, class... EqFns, class... IneqFns>
Result< N > optimize (NLoptRAII &nl, Fn &&fn, const Input< N > &initvals, const std::tuple< EqFns... > &equalities, const std::tuple< IneqFns... > &inequalities)
Static Private Member Functions
template<class Fn , size_t N>
static double optfunc (unsigned n, const double *params, double *gradient, void *data)
template<class Fn , size_t N>
static double constrain_func (unsigned n, const double *params, double *gradient, void *data)
template<size_t N>
static void set_up (NLoptRAII &nl, const Bounds< N > &bounds, const StopCriteria &stopcr)
Private Attributes
StopCriteria m_stopcr
StopCriteria m_loc_stopcr
OptDir m_dir = OptDir::MIN
Static Private Attributes
static constexpr double ConstraintEps = 1e-6
Detailed Description
template<class M, class = NLoptOnly<M>>
class Slic3r::opt::detail::NLoptOpt< M, class >
Constructor & Destructor Documentation
NLoptOpt()
template<class M , class = NLoptOnly<M>> Slic3r::opt::detail::NLoptOpt< M, class >::NLoptOpt (const StopCriteria & stopcr_glob = {}) inline explicit
                                                        {})
        : m_stopcr(stopcr_glob)
    {}
Member Function Documentation
constrain_func()
template<class M , class = NLoptOnly<M>> template<class Fn , size_t N> static double Slic3r::opt::detail::NLoptOpt< M, class >::constrain_func (unsigned n, const double * params, double * gradient, void * data) inline static private
    {
        assert(n == N);
        auto tdata = static_cast<OptData<Fn>*>(data);
        auto funval = to_arr<N>(params);
        return tdata->fn(funval);
    }
get_criteria()
template<class M , class = NLoptOnly<M>> const StopCriteria & Slic3r::opt::detail::NLoptOpt< M, class >::get_criteria () const inline noexcept
{ return m_stopcr; }
References Slic3r::opt::detail::NLoptOpt< M, class >::m_stopcr.
Referenced by Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::get_criteria(), and Slic3r::opt::detail::NLoptOpt< M, class >::optimize().
get_loc_criteria()
template<class M , class = NLoptOnly<M>> const StopCriteria & Slic3r::opt::detail::NLoptOpt< M, class >::get_loc_criteria () const inline noexcept
{ return m_loc_stopcr; }
References Slic3r::opt::detail::NLoptOpt< M, class >::m_loc_stopcr.
Referenced by Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::get_loc_criteria().
optfunc()
template<class M , class = NLoptOnly<M>> template<class Fn , size_t N> static double Slic3r::opt::detail::NLoptOpt< M, class >::optfunc (unsigned n, const double * params, double * gradient, void * data) inline static private
    {
        assert(n == N);
        auto tdata = static_cast<OptData<Fn>*>(data);
        if (tdata->self->m_stopcr.stop_condition())
            nlopt_force_stop(tdata->opt_raw);
        auto funval = to_arr<N>(params);
        double scoreval = 0.;
        using RetT = decltype(tdata->fn(funval));
        if constexpr (std::is_convertible_v<RetT, ScoreGradient<N>>) {
            ScoreGradient<N> score = tdata->fn(funval);
            for (size_t i = 0; i < n; ++i) gradient[i] = (*score.gradient)[i];
            scoreval = score.score;
        } else {
            scoreval = tdata->fn(funval);
        }
        return scoreval;
    }
References Slic3r::opt::ScoreGradient< N >::gradient, and Slic3r::opt::ScoreGradient< N >::score.
optimize() [1/2]
template<class M , class = NLoptOnly<M>> template<class Fn , size_t N, class... EqFns, class... IneqFns> Result< N > Slic3r::opt::detail::NLoptOpt< M, class >::optimize (Fn && f, const Input< N > & initvals, const Bounds< N > & bounds, const std::tuple< EqFns... > & equalities, const std::tuple< IneqFns... > & inequalities) inline
    {
        if constexpr (IsAUGLAG<M>) {
            NLoptRAII nl_wrap{NLOPT_AUGLAG, N};
            set_up(nl_wrap, bounds, get_criteria());
            NLoptRAII nl_glob{GetNLoptAlg_Global<M>, N};
            set_up(nl_glob, bounds, get_criteria());
            nlopt_set_local_optimizer(nl_wrap.ptr, nl_glob.ptr);
            if constexpr (GetNLoptAlg_Local<M> < NLOPT_NUM_ALGORITHMS) {
                NLoptRAII nl_loc{GetNLoptAlg_Local<M>, N};
                set_up(nl_loc, bounds, m_loc_stopcr);
                nlopt_set_local_optimizer(nl_glob.ptr, nl_loc.ptr);
                return optimize(nl_wrap, std::forward<Fn>(f), initvals,
                                equalities, inequalities);
            } else {
                return optimize(nl_wrap, std::forward<Fn>(f), initvals,
                                equalities, inequalities);
            }
        } else {
            NLoptRAII nl_glob{GetNLoptAlg_Global<M>, N};
            set_up(nl_glob, bounds, get_criteria());
            if constexpr (GetNLoptAlg_Local<M> < NLOPT_NUM_ALGORITHMS) {
                NLoptRAII nl_loc{GetNLoptAlg_Local<M>, N};
                set_up(nl_loc, bounds, m_loc_stopcr);
                nlopt_set_local_optimizer(nl_glob.ptr, nl_loc.ptr);
                return optimize(nl_glob, std::forward<Fn>(f), initvals,
                                equalities, inequalities);
            } else {
                return optimize(nl_glob, std::forward<Fn>(f), initvals,
                                equalities, inequalities);
            }
        }
        assert(false);
        return {};
    }
References Slic3r::opt::bounds(), Slic3r::f(), Slic3r::opt::detail::NLoptOpt< M, class >::get_criteria(), Slic3r::opt::detail::NLoptOpt< M, class >::m_loc_stopcr, Slic3r::opt::detail::NLoptOpt< M, class >::optimize(), and Slic3r::opt::detail::NLoptOpt< M, class >::set_up().
optimize() [2/2]
template<class M , class = NLoptOnly<M>> template<class Fn , size_t N, class... EqFns, class... IneqFns> Result< N > Slic3r::opt::detail::NLoptOpt< M, class >::optimize (NLoptRAII & nl, Fn && fn, const Input< N > & initvals, const std::tuple< EqFns... > & equalities, const std::tuple< IneqFns... > & inequalities) inline private
    {
        Result<N> r;
        OptData<Fn> data {fn, this, nl.ptr};
        auto do_for_each_eq = [this, &nl](auto &arg) {
            arg.self = this;
            arg.opt_raw = nl.ptr;
            using F = decltype(arg.fn);
            nlopt_add_equality_constraint (nl.ptr, constrain_func<F, N>, &arg, ConstraintEps);
        };
        auto do_for_each_ineq = [this, &nl](auto &arg) {
            arg.self = this;
            arg.opt_raw = nl.ptr;
            using F = decltype(arg.fn);
            nlopt_add_inequality_constraint (nl.ptr, constrain_func<F, N>, &arg, ConstraintEps);
        };
        auto eq_data = wrap_tup<OptData>(equalities);
        for_each_in_tuple(do_for_each_eq, eq_data);
        auto ineq_data = wrap_tup<OptData>(inequalities);
        for_each_in_tuple(do_for_each_ineq, ineq_data);
        switch(m_dir) {
        case OptDir::MIN:
            nlopt_set_min_objective(nl.ptr, optfunc<Fn, N>, &data); break;
        case OptDir::MAX:
            nlopt_set_max_objective(nl.ptr, optfunc<Fn, N>, &data); break;
        }
        r.optimum = initvals;
        r.resultcode = nlopt_optimize(nl.ptr, r.optimum.data(), &r.score);
        return r;
    }
References arg(), Slic3r::opt::detail::NLoptOpt< M, class >::ConstraintEps, Slic3r::F, Slic3r::opt::detail::for_each_in_tuple(), Slic3r::opt::detail::NLoptOpt< M, class >::m_dir, Slic3r::opt::detail::MAX, Slic3r::opt::detail::MIN, Slic3r::opt::Result< N >::optimum, Slic3r::opt::detail::NLoptRAII::ptr, Slic3r::opt::Result< N >::resultcode, and Slic3r::opt::Result< N >::score.
Referenced by Slic3r::opt::detail::NLoptOpt< M, class >::optimize().
seed()
template<class M , class = NLoptOnly<M>> void Slic3r::opt::detail::NLoptOpt< M, class >::seed (long s) inline
{ nlopt_srand(s); }
Referenced by Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::seed().
set_criteria()
template<class M , class = NLoptOnly<M>> void Slic3r::opt::detail::NLoptOpt< M, class >::set_criteria (const StopCriteria & cr) inline
{ m_stopcr = cr; }
References Slic3r::opt::detail::NLoptOpt< M, class >::m_stopcr.
Referenced by Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::set_criteria().
set_dir()
template<class M , class = NLoptOnly<M>> void Slic3r::opt::detail::NLoptOpt< M, class >::set_dir (OptDir dir) inline noexcept
{ m_dir = dir; }
References Slic3r::opt::detail::NLoptOpt< M, class >::m_dir.
Referenced by Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::to_max(), and Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::to_min().
set_loc_criteria()
template<class M , class = NLoptOnly<M>> void Slic3r::opt::detail::NLoptOpt< M, class >::set_loc_criteria (const StopCriteria & cr) inline
{ m_loc_stopcr = cr; }
References Slic3r::opt::detail::NLoptOpt< M, class >::m_loc_stopcr.
Referenced by Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::set_loc_criteria().
set_up()
template<class M , class = NLoptOnly<M>> template<size_t N> static void Slic3r::opt::detail::NLoptOpt< M, class >::set_up (NLoptRAII & nl, const Bounds< N > & bounds, const StopCriteria & stopcr) inline static private
    {
        std::array<double, N> lb, ub;
        for (size_t i = 0; i < N; ++i) {
            lb[i] = bounds[i].min();
            ub[i] = bounds[i].max();
        }
        nlopt_set_lower_bounds(nl.ptr, lb.data());
        nlopt_set_upper_bounds(nl.ptr, ub.data());
        double abs_diff = stopcr.abs_score_diff();
        double rel_diff = stopcr.rel_score_diff();
        double stopval = stopcr.stop_score();
        if(!std::isnan(abs_diff)) nlopt_set_ftol_abs(nl.ptr, abs_diff);
        if(!std::isnan(rel_diff)) nlopt_set_ftol_rel(nl.ptr, rel_diff);
        if(!std::isnan(stopval))  nlopt_set_stopval(nl.ptr, stopval);
        if(stopcr.max_iterations() > 0)
            nlopt_set_maxeval(nl.ptr, stopcr.max_iterations());
    }
References Slic3r::opt::StopCriteria::abs_score_diff(), Slic3r::opt::bounds(), Slic3r::opt::StopCriteria::max_iterations(), Slic3r::opt::detail::NLoptRAII::ptr, Slic3r::opt::StopCriteria::rel_score_diff(), and Slic3r::opt::StopCriteria::stop_score().
Referenced by Slic3r::opt::detail::NLoptOpt< M, class >::optimize().
Member Data Documentation
ConstraintEps
template<class M , class = NLoptOnly<M>> constexpr double Slic3r::opt::detail::NLoptOpt< M, class >::ConstraintEps = 1e-6 static constexpr private
Referenced by Slic3r::opt::detail::NLoptOpt< M, class >::optimize().
m_dir
template<class M , class = NLoptOnly<M>> OptDir Slic3r::opt::detail::NLoptOpt< M, class >::m_dir = OptDir::MIN private
Referenced by Slic3r::opt::detail::NLoptOpt< M, class >::optimize(), and Slic3r::opt::detail::NLoptOpt< M, class >::set_dir().
m_loc_stopcr
template<class M , class = NLoptOnly<M>> StopCriteria Slic3r::opt::detail::NLoptOpt< M, class >::m_loc_stopcr private
Referenced by Slic3r::opt::detail::NLoptOpt< M, class >::get_loc_criteria(), Slic3r::opt::detail::NLoptOpt< M, class >::optimize(), and Slic3r::opt::detail::NLoptOpt< M, class >::set_loc_criteria().
m_stopcr
template<class M , class = NLoptOnly<M>> StopCriteria Slic3r::opt::detail::NLoptOpt< M, class >::m_stopcr private
Referenced by Slic3r::opt::detail::NLoptOpt< M, class >::get_criteria(), and Slic3r::opt::detail::NLoptOpt< M, class >::set_criteria().
The documentation for this class was generated from the following file:
src/libslic3r/Optimize/NLoptOptimizer.hpp