Prusa Slicer: Slic3r::Geometry::CircleSq< Vector > Struct Template Reference
Slic3r::Geometry::CircleSq< Vector > Struct Template Reference
#include <src/libslic3r/Geometry/Circle.hpp>
Public Types
using Scalar = typename Vector::Scalar
Public Member Functions
CircleSq ()
CircleSq (const Vector &center, const Scalar radius2)
CircleSq (const Vector &a, const Vector &b)
CircleSq (const Vector &a, const Vector &b, const Vector &c, Scalar epsilon)
bool invalid () const
bool valid () const
bool contains (const Vector &p) const
bool contains (const Vector &p, const Scalar epsilon2) const
CircleSq inflated (Scalar epsilon) const
Static Public Member Functions
static CircleSq make_invalid ()
Public Attributes
Vector center
Scalar radius2
Detailed Description
template<typename Vector>
struct Slic3r::Geometry::CircleSq< Vector >
Member Typedef Documentation
Scalar
template<typename Vector > using Slic3r::Geometry::CircleSq< Vector >::Scalar = typename Vector::Scalar
Constructor & Destructor Documentation
CircleSq() [1/4]
template<typename Vector > Slic3r::Geometry::CircleSq< Vector >::CircleSq () inline
{}
CircleSq() [2/4]
template<typename Vector > Slic3r::Geometry::CircleSq< Vector >::CircleSq (const Vector & center, const Scalar radius2) inline
: center(center), radius2(radius2) {}
CircleSq() [3/4]
template<typename Vector > Slic3r::Geometry::CircleSq< Vector >::CircleSq (const Vector & a, const Vector & b) inline
: center(Scalar(0.5) * (a + b)) { radius2 = (a - center).squaredNorm(); }
References Slic3r::Geometry::CircleSq< Vector >::center, and Slic3r::Geometry::CircleSq< Vector >::radius2.
CircleSq() [4/4]
template<typename Vector > Slic3r::Geometry::CircleSq< Vector >::CircleSq (const Vector & a, const Vector & b, const Vector & c, Scalar epsilon) inline
{
        this->center = circle_center(a, b, c, epsilon);
    this->radius2 = (a - this->center).squaredNorm();
    }
References Slic3r::Geometry::CircleSq< Vector >::center, and Slic3r::Geometry::circle_center().
Member Function Documentation
contains() [1/2]
template<typename Vector > bool Slic3r::Geometry::CircleSq< Vector >::contains (const Vector & p) const inline
{ return (p - this->center).squaredNorm() < this->radius2; }
References Slic3r::Geometry::CircleSq< Vector >::radius2.
Referenced by Slic3r::Geometry::smallest_enclosing_circle2_welzl().
contains() [2/2]
template<typename Vector > bool Slic3r::Geometry::CircleSq< Vector >::contains (const Vector & p, const Scalar epsilon2) const inline
{ return (p - this->center).squaredNorm() < this->radius2 + epsilon2; }
inflated()
template<typename Vector > CircleSq Slic3r::Geometry::CircleSq< Vector >::inflated (Scalar epsilon) const inline
      { assert(this->radius2 >= 0); Scalar r = sqrt(this->radius2) + epsilon; return { this->center, r * r }; }
References Slic3r::Geometry::CircleSq< Vector >::center, and sqrt().
Referenced by Slic3r::Geometry::smallest_enclosing_circle2_welzl().
invalid()
template<typename Vector > bool Slic3r::Geometry::CircleSq< Vector >::invalid () const inline
{ return this->radius2 < 0; }
Referenced by Slic3r::Geometry::CircleSq< Vector >::valid().
make_invalid()
template<typename Vector > static CircleSq Slic3r::Geometry::CircleSq< Vector >::make_invalid () inline static
{ return CircleSq { { 0, 0 }, -1 }; }
valid()
template<typename Vector > bool Slic3r::Geometry::CircleSq< Vector >::valid () const inline
{ return ! this->invalid(); }
References Slic3r::Geometry::CircleSq< Vector >::invalid().
Member Data Documentation
center
template<typename Vector > Vector Slic3r::Geometry::CircleSq< Vector >::center
Referenced by Slic3r::Geometry::CircleSq< Vector >::CircleSq(), Slic3r::Geometry::CircleSq< Vector >::CircleSq(), Slic3r::Geometry::CircleSq< Vector >::inflated(), and Slic3r::Geometry::smallest_enclosing_circle2_welzl().
radius2
template<typename Vector > Scalar Slic3r::Geometry::CircleSq< Vector >::radius2
Referenced by Slic3r::Geometry::CircleSq< Vector >::CircleSq(), Slic3r::Geometry::CircleSq< Vector >::contains(), and Slic3r::Geometry::smallest_enclosing_circle2_welzl().
The documentation for this struct was generated from the following file:
src/libslic3r/Geometry/Circle.hpp