Prusa Slicer: agg::row_accessor< T > Class Template Reference
agg::row_accessor< T > Class Template Reference
#include <src/agg/agg_rendering_buffer.h>
Public Types
typedef const_row_info< T > row_data
Public Member Functions
row_accessor ()
row_accessor (T *buf, unsigned width, unsigned height, int stride)
void attach (T *buf, unsigned width, unsigned height, int stride)
AGG_INLINE T * buf ()
AGG_INLINE const T * buf () const
AGG_INLINE unsigned width () const
AGG_INLINE unsigned height () const
AGG_INLINE int stride () const
AGG_INLINE unsigned stride_abs () const
AGG_INLINE T * row_ptr (int, int y, unsigned)
AGG_INLINE T * row_ptr (int y)
AGG_INLINE const T * row_ptr (int y) const
AGG_INLINE row_data row (int y) const
template<class RenBuf >
void copy_from (const RenBuf &src)
void clear (T value)
Private Attributes
T * m_buf
T * m_start
unsigned m_width
unsigned m_height
int m_stride
Detailed Description
template<class T>
class agg::row_accessor< T >
Member Typedef Documentation
row_data
template<class T > typedef const_row_info<T> agg::row_accessor< T >::row_data
Constructor & Destructor Documentation
row_accessor() [1/2]
template<class T > agg::row_accessor< T >::row_accessor () inline
                       :
            m_buf(0),
            m_start(0),
            m_width(0),
            m_height(0),
            m_stride(0)
        {
        }
row_accessor() [2/2]
template<class T > agg::row_accessor< T >::row_accessor (T * buf, unsigned width, unsigned height, int stride) inline
                                                                          :
            m_buf(0),
            m_start(0),
            m_width(0),
            m_height(0),
            m_stride(0)
        {
            attach(buf, width, height, stride);
        }
References agg::row_accessor< T >::attach(), agg::row_accessor< T >::buf(), agg::row_accessor< T >::height(), agg::row_accessor< T >::stride(), and agg::row_accessor< T >::width().
Member Function Documentation
attach()
template<class T > void agg::row_accessor< T >::attach (T * buf, unsigned width, unsigned height, int stride) inline
        {
            m_buf = m_start = buf;
            m_width = width;
            m_height = height;
            m_stride = stride;
            if(stride < 0)
            {
                m_start = m_buf - int(height - 1) * stride;
            }
        }
References agg::row_accessor< T >::buf(), agg::row_accessor< T >::height(), agg::row_accessor< T >::m_buf, agg::row_accessor< T >::m_height, agg::row_accessor< T >::m_start, agg::row_accessor< T >::m_stride, agg::row_accessor< T >::m_width, agg::row_accessor< T >::stride(), and agg::row_accessor< T >::width().
Referenced by agg::row_accessor< T >::row_accessor().
buf() [1/2]
template<class T > AGG_INLINE T * agg::row_accessor< T >::buf () inline
{ return m_buf;    }
References agg::row_accessor< T >::m_buf.
Referenced by agg::row_accessor< T >::row_accessor(), and agg::row_accessor< T >::attach().
buf() [2/2]
template<class T > AGG_INLINE const T * agg::row_accessor< T >::buf () const inline
{ return m_buf;    }
References agg::row_accessor< T >::m_buf.
clear()
template<class T > void agg::row_accessor< T >::clear (T value) inline
        {
            unsigned y;
            unsigned w = width();
            unsigned stride = stride_abs();
            for(y = 0; y < height(); y++)
            {
                T* p = row_ptr(0, y, w);
                unsigned x;
                for(x = 0; x < stride; x++)
                {
                    *p++ = value;
                }
            }
        }
References agg::row_accessor< T >::height(), agg::row_accessor< T >::row_ptr(), agg::row_accessor< T >::stride(), agg::row_accessor< T >::stride_abs(), and agg::row_accessor< T >::width().
copy_from()
template<class T > template<class RenBuf > void agg::row_accessor< T >::copy_from (const RenBuf & src) inline
        {
            unsigned h = height();
            if(src.height() < h) h = src.height();
            unsigned l = stride_abs();
            if(src.stride_abs() < l) l = src.stride_abs();
            l *= sizeof(T);
            unsigned y;
            unsigned w = width();
            for (y = 0; y < h; y++)
            {
                memcpy(row_ptr(0, y, w), src.row_ptr(y), l);
            }
        }
References agg::row_accessor< T >::height(), agg::row_accessor< T >::row_ptr(), agg::row_accessor< T >::stride_abs(), and agg::row_accessor< T >::width().
height()
template<class T > AGG_INLINE unsigned agg::row_accessor< T >::height () const inline
{ return m_height; }
References agg::row_accessor< T >::m_height.
Referenced by agg::row_accessor< T >::row_accessor(), agg::row_accessor< T >::attach(), agg::row_accessor< T >::clear(), and agg::row_accessor< T >::copy_from().
row()
template<class T > AGG_INLINE row_data agg::row_accessor< T >::row (int y) const inline
        {
            return row_data(0, m_width-1, row_ptr(y));
        }
References agg::row_accessor< T >::m_width, and agg::row_accessor< T >::row_ptr().
row_ptr() [1/3]
template<class T > AGG_INLINE T * agg::row_accessor< T >::row_ptr (int y) inline
{ return m_start + y * m_stride; }
References agg::row_accessor< T >::m_start, and agg::row_accessor< T >::m_stride.
row_ptr() [2/3]
template<class T > AGG_INLINE const T * agg::row_accessor< T >::row_ptr (int y) const inline
{ return m_start + y * m_stride; }
References agg::row_accessor< T >::m_start, and agg::row_accessor< T >::m_stride.
row_ptr() [3/3]
template<class T > AGG_INLINE T * agg::row_accessor< T >::row_ptr (int , int y, unsigned) inline
        {
            return m_start + y * m_stride;
        }
References agg::row_accessor< T >::m_start, and agg::row_accessor< T >::m_stride.
Referenced by agg::row_accessor< T >::clear(), agg::row_accessor< T >::copy_from(), and agg::row_accessor< T >::row().
stride()
template<class T > AGG_INLINE int agg::row_accessor< T >::stride () const inline
{ return m_stride; }
References agg::row_accessor< T >::m_stride.
Referenced by agg::row_accessor< T >::row_accessor(), agg::row_accessor< T >::attach(), and agg::row_accessor< T >::clear().
stride_abs()
template<class T > AGG_INLINE unsigned agg::row_accessor< T >::stride_abs () const inline
        {
            return (m_stride < 0) ? unsigned(-m_stride) : unsigned(m_stride);
        }
References agg::row_accessor< T >::m_stride.
Referenced by agg::row_accessor< T >::clear(), and agg::row_accessor< T >::copy_from().
width()
template<class T > AGG_INLINE unsigned agg::row_accessor< T >::width () const inline
{ return m_width;  }
References agg::row_accessor< T >::m_width.
Referenced by agg::row_accessor< T >::row_accessor(), agg::row_accessor< T >::attach(), agg::row_accessor< T >::clear(), and agg::row_accessor< T >::copy_from().
Member Data Documentation
m_buf
template<class T > T* agg::row_accessor< T >::m_buf private
Referenced by agg::row_accessor< T >::attach(), agg::row_accessor< T >::buf(), and agg::row_accessor< T >::buf().
m_height
template<class T > unsigned agg::row_accessor< T >::m_height private
Referenced by agg::row_accessor< T >::attach(), and agg::row_accessor< T >::height().
m_start
template<class T > T* agg::row_accessor< T >::m_start private
Referenced by agg::row_accessor< T >::attach(), agg::row_accessor< T >::row_ptr(), agg::row_accessor< T >::row_ptr(), and agg::row_accessor< T >::row_ptr().
m_stride
template<class T > int agg::row_accessor< T >::m_stride private
Referenced by agg::row_accessor< T >::attach(), agg::row_accessor< T >::row_ptr(), agg::row_accessor< T >::row_ptr(), agg::row_accessor< T >::row_ptr(), agg::row_accessor< T >::stride(), and agg::row_accessor< T >::stride_abs().
m_width
template<class T > unsigned agg::row_accessor< T >::m_width private
Referenced by agg::row_accessor< T >::attach(), agg::row_accessor< T >::row(), and agg::row_accessor< T >::width().
The documentation for this class was generated from the following file:
src/agg/agg_rendering_buffer.h