Prusa Slicer: src/avrdude/windows/giveio.c File Reference
giveio.c File Reference
#include <ntddk.h>
Macros
#define DEVICE_NAME_STRING L"giveio"
#define IOPM_SIZE 0x2000
Typedefs
typedef UCHAR IOPM[IOPM_SIZE]
Functions
void Ke386SetIoAccessMap (int, IOPM *)
void Ke386QueryIoAccessMap (int, IOPM *)
void Ke386IoSetAccessProcess (PEPROCESS, int)
VOID GiveioUnload (IN PDRIVER_OBJECT DriverObject)
VOID SetIOPermissionMap (int OnFlag)
void GiveIO (void)
NTSTATUS GiveioCreateDispatch (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTSTATUS DriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
Variables
IOPM * IOPM_local = 0
Macro Definition Documentation
DEVICE_NAME_STRING
#define DEVICE_NAME_STRING L"giveio"
IOPM_SIZE
#define IOPM_SIZE 0x2000
Typedef Documentation
IOPM
typedef UCHAR IOPM[IOPM_SIZE]
Function Documentation
DriverEntry()
NTSTATUS DriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
{
  PDEVICE_OBJECT deviceObject;
  NTSTATUS status;
  WCHAR NameBuffer[] = L"\\Device\\" DEVICE_NAME_STRING;
  WCHAR DOSNameBuffer[] = L"\\DosDevices\\" DEVICE_NAME_STRING;
  UNICODE_STRING uniNameString, uniDOSString;
  //
  //  Allocate a buffer for the local IOPM and zero it.
  //
  IOPM_local = MmAllocateNonCachedMemory(sizeof(IOPM));
  if(IOPM_local == 0)
    return STATUS_INSUFFICIENT_RESOURCES;
  RtlZeroMemory(IOPM_local, sizeof(IOPM));
  //
  //  Set up device driver name and device object.
  //
  RtlInitUnicodeString(&uniNameString, NameBuffer);
  RtlInitUnicodeString(&uniDOSString, DOSNameBuffer);
  status = IoCreateDevice(DriverObject, 0,
          &uniNameString,
          FILE_DEVICE_UNKNOWN,
          0, FALSE, &deviceObject);
  if(!NT_SUCCESS(status))
    return status;
  status = IoCreateSymbolicLink (&uniDOSString, &uniNameString);
  if (!NT_SUCCESS(status))
    return status;
    //
    //  Initialize the Driver Object with driver's entry points.
  // All we require are the Create and Unload operations.
    //
    DriverObject->MajorFunction[IRP_MJ_CREATE] = GiveioCreateDispatch;
  DriverObject->DriverUnload = GiveioUnload;
    return STATUS_SUCCESS;
}
References DEVICE_NAME_STRING, FALSE, GiveioCreateDispatch(), GiveioUnload(), IOPM_local, and L.
GiveIO()
void GiveIO (void)
{
  SetIOPermissionMap(1);
}
References SetIOPermissionMap().
Referenced by GiveioCreateDispatch().
GiveioCreateDispatch()
NTSTATUS GiveioCreateDispatch (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
{
  GiveIO();     // give the calling process I/O access
    Irp->IoStatus.Information = 0;
    Irp->IoStatus.Status = STATUS_SUCCESS;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return STATUS_SUCCESS;
}
References GiveIO().
Referenced by DriverEntry().
GiveioUnload()
VOID GiveioUnload (IN PDRIVER_OBJECT DriverObject)
{
  WCHAR DOSNameBuffer[] = L"\\DosDevices\\" DEVICE_NAME_STRING;
  UNICODE_STRING uniDOSString;
  if(IOPM_local)
    MmFreeNonCachedMemory(IOPM_local, sizeof(IOPM));
  RtlInitUnicodeString(&uniDOSString, DOSNameBuffer);
  IoDeleteSymbolicLink (&uniDOSString);
  IoDeleteDevice(DriverObject->DeviceObject);
}
References DEVICE_NAME_STRING, IOPM_local, and L.
Referenced by DriverEntry().
Ke386IoSetAccessProcess()
void Ke386IoSetAccessProcess (PEPROCESS , int)
Referenced by SetIOPermissionMap().
Ke386QueryIoAccessMap()
void Ke386QueryIoAccessMap (int , IOPM *)
Ke386SetIoAccessMap()
void Ke386SetIoAccessMap (int , IOPM *)
Referenced by SetIOPermissionMap().
SetIOPermissionMap()
VOID SetIOPermissionMap (int OnFlag)
{
  Ke386IoSetAccessProcess(PsGetCurrentProcess(), OnFlag);
  Ke386SetIoAccessMap(1, IOPM_local);
}
References IOPM_local, Ke386IoSetAccessProcess(), and Ke386SetIoAccessMap().
Referenced by GiveIO().
Variable Documentation
IOPM_local
IOPM* IOPM_local = 0
Referenced by DriverEntry(), GiveioUnload(), and SetIOPermissionMap().