Prusa Slicer: Eigen::SVDBase< Derived > Class Template Reference
Eigen::SVDBase< Derived > Class Template Reference
Base class of SVD algorithms.
#include <src/eigen/Eigen/src/SVD/SVDBase.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , DiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime) , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime , MaxDiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_FIXED(MaxRowsAtCompileTime,MaxColsAtCompileTime) , MatrixOptions = MatrixType::Options
}
typedef internal::traits< Derived >::MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typenameMatrixType::Scalar >::Real RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef Eigen::Index Index
typedef Matrix< Scalar, RowsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MaxRowsAtCompileTime > MatrixUType
typedef Matrix< Scalar, ColsAtCompileTime, ColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxColsAtCompileTime > MatrixVType
typedef internal::plain_diag_type< MatrixType, RealScalar >::type SingularValuesType
Public Member Functions
Derived & derived ()
const Derived & derived () const
const MatrixUType & matrixU () const
const MatrixVType & matrixV () const
const SingularValuesType & singularValues () const
Index nonzeroSingularValues () const
Index rank () const
Derived & setThreshold (const RealScalar &threshold)
Derived & setThreshold (Default_t)
RealScalar threshold () const
bool computeU () const
bool computeV () const
Index rows () const
Index cols () const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
Protected Member Functions
bool allocate (Index rows, Index cols, unsigned int computationOptions)
SVDBase ()
Default Constructor.
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixUType m_matrixU
MatrixVType m_matrixV
SingularValuesType m_singularValues
bool m_isInitialized
bool m_isAllocated
bool m_usePrescribedThreshold
bool m_computeFullU
bool m_computeThinU
bool m_computeFullV
bool m_computeThinV
unsigned int m_computationOptions
Index m_nonzeroSingularValues
Index m_rows
Index m_cols
Index m_diagSize
RealScalar m_prescribedThreshold
Detailed Description
template<typename Derived>
class Eigen::SVDBase< Derived >
Base class of SVD algorithms.
Template Parameters
Derived the type of the actual SVD decomposition
SVD decomposition consists in decomposing any n-by-p matrix A as a product
where U is a n-by-n unitary, V is a p-by-p unitary, and S is a n-by-p real positive matrix which is zero outside of its main diagonal; the diagonal entries of S are known as the singular values of A and the columns of U and V are known as the left and right singular vectors of A respectively.
Singular values are always sorted in decreasing order.
You can ask for only thin U or V to be computed, meaning the following. In case of a rectangular n-by-p matrix, letting m be the smaller value among n and p, there are only m singular vectors; the remaining columns of U and V do not correspond to actual singular vectors. Asking for thin U or V means asking for only their m first columns to be formed. So U is then a n-by-m matrix, and V is then a p-by-m matrix. Notice that thin U and V are all you need for (least squares) solving.
If the input matrix has inf or nan coefficients, the result of the computation is undefined, but the computation is guaranteed to terminate in finite (and reasonable) time.
See also
class BDCSVD, class JacobiSVD
Member Typedef Documentation
Index
template<typename Derived > typedef Eigen::Index Eigen::SVDBase< Derived >::Index
MatrixType
template<typename Derived > typedef internal::traits<Derived>::MatrixType Eigen::SVDBase< Derived >::MatrixType
MatrixUType
template<typename Derived > typedef Matrix<Scalar, RowsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MaxRowsAtCompileTime> Eigen::SVDBase< Derived >::MatrixUType
MatrixVType
template<typename Derived > typedef Matrix<Scalar, ColsAtCompileTime, ColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxColsAtCompileTime> Eigen::SVDBase< Derived >::MatrixVType
RealScalar
template<typename Derived > typedef NumTraits<typenameMatrixType::Scalar>::Real Eigen::SVDBase< Derived >::RealScalar
Scalar
template<typename Derived > typedef MatrixType::Scalar Eigen::SVDBase< Derived >::Scalar
SingularValuesType
template<typename Derived > typedef internal::plain_diag_type<MatrixType,RealScalar>::type Eigen::SVDBase< Derived >::SingularValuesType
StorageIndex
template<typename Derived > typedef MatrixType::StorageIndex Eigen::SVDBase< Derived >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
DiagSizeAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxDiagSizeAtCompileTime
MatrixOptions
       {
    RowsAtCompileTime = MatrixType::RowsAtCompileTime,
    ColsAtCompileTime = MatrixType::ColsAtCompileTime,
    DiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime),
    MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
    MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime,
    MaxDiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_FIXED(MaxRowsAtCompileTime,MaxColsAtCompileTime),
    MatrixOptions = MatrixType::Options
  };
Constructor & Destructor Documentation
SVDBase()
template<typename Derived > Eigen::SVDBase< Derived >::SVDBase () inline protected
Default Constructor.
Default constructor of SVDBase
    : m_isInitialized(false),
      m_isAllocated(false),
      m_usePrescribedThreshold(false),
      m_computationOptions(0),
      m_rows(-1), m_cols(-1), m_diagSize(0)
  {
    check_template_parameters();
  }
References Eigen::SVDBase< Derived >::check_template_parameters().
Member Function Documentation
_solve_impl() [1/2]
template<typename Derived > template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::SVDBase< Derived >::_solve_impl (const RhsType & rhs, DstType & dst) const
_solve_impl() [2/2]
template<typename Derived > template<typename RhsType , typename DstType > void Eigen::SVDBase< Derived >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
  eigen_assert(rhs.rows() == rows());
  // A = U S V^*
  // So A^{-1} = V S^{-1} U^*
  Matrix<Scalar, Dynamic, RhsType::ColsAtCompileTime, 0, MatrixType::MaxRowsAtCompileTime, RhsType::MaxColsAtCompileTime> tmp;
  Index l_rank = rank();
  tmp.noalias() =  m_matrixU.leftCols(l_rank).adjoint() * rhs;
  tmp = m_singularValues.head(l_rank).asDiagonal().inverse() * tmp;
  dst = m_matrixV.leftCols(l_rank) * tmp;
}
References eigen_assert.
allocate()
template<typename MatrixType > bool Eigen::SVDBase< MatrixType >::allocate (Index rows, Index cols, unsigned int computationOptions) protected
{
  eigen_assert(rows >= 0 && cols >= 0);
  if (m_isAllocated &&
      rows == m_rows &&
      cols == m_cols &&
      computationOptions == m_computationOptions)
  {
    return true;
  }
  m_rows = rows;
  m_cols = cols;
  m_isInitialized = false;
  m_isAllocated = true;
  m_computationOptions = computationOptions;
  m_computeFullU = (computationOptions & ComputeFullU) != 0;
  m_computeThinU = (computationOptions & ComputeThinU) != 0;
  m_computeFullV = (computationOptions & ComputeFullV) != 0;
  m_computeThinV = (computationOptions & ComputeThinV) != 0;
  eigen_assert(!(m_computeFullU && m_computeThinU) && "SVDBase: you can't ask for both full and thin U");
  eigen_assert(!(m_computeFullV && m_computeThinV) && "SVDBase: you can't ask for both full and thin V");
  eigen_assert(EIGEN_IMPLIES(m_computeThinU || m_computeThinV, MatrixType::ColsAtCompileTime==Dynamic) &&
         "SVDBase: thin U and V are only available when your matrix has a dynamic number of columns.");
  m_diagSize = (std::min)(m_rows, m_cols);
  m_singularValues.resize(m_diagSize);
  if(RowsAtCompileTime==Dynamic)
    m_matrixU.resize(m_rows, m_computeFullU ? m_rows : m_computeThinU ? m_diagSize : 0);
  if(ColsAtCompileTime==Dynamic)
    m_matrixV.resize(m_cols, m_computeFullV ? m_cols : m_computeThinV ? m_diagSize : 0);
  return false;
}
References Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, Eigen::Dynamic, eigen_assert, and EIGEN_IMPLIES.
check_template_parameters()
template<typename Derived > static void Eigen::SVDBase< Derived >::check_template_parameters () inline static protected
  {
    EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
  }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
Referenced by Eigen::SVDBase< Derived >::SVDBase().
cols()
template<typename Derived > Index Eigen::SVDBase< Derived >::cols () const inline
{ return m_cols; }
References Eigen::SVDBase< Derived >::m_cols.
computeU()
template<typename Derived > bool Eigen::SVDBase< Derived >::computeU () const inline
Returns
true if U (full or thin) is asked for in this SVD decomposition
{ return m_computeFullU || m_computeThinU; }
References Eigen::SVDBase< Derived >::m_computeFullU, and Eigen::SVDBase< Derived >::m_computeThinU.
Referenced by Eigen::SVDBase< Derived >::matrixU(), and Eigen::SVDBase< Derived >::solve().
computeV()
template<typename Derived > bool Eigen::SVDBase< Derived >::computeV () const inline
Returns
true if V (full or thin) is asked for in this SVD decomposition
{ return m_computeFullV || m_computeThinV; }
References Eigen::SVDBase< Derived >::m_computeFullV, and Eigen::SVDBase< Derived >::m_computeThinV.
Referenced by Eigen::SVDBase< Derived >::matrixV(), and Eigen::SVDBase< Derived >::solve().
derived() [1/2]
template<typename Derived > Derived & Eigen::SVDBase< Derived >::derived () inline
{ return *static_cast<Derived*>(this); }
Referenced by Eigen::SVDBase< Derived >::setThreshold(), Eigen::SVDBase< Derived >::setThreshold(), and Eigen::SVDBase< Derived >::solve().
derived() [2/2]
template<typename Derived > const Derived & Eigen::SVDBase< Derived >::derived () const inline
{ return *static_cast<const Derived*>(this); }
matrixU()
template<typename Derived > const MatrixUType & Eigen::SVDBase< Derived >::matrixU () const inline
Returns
the U matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the U matrix is n-by-n if you asked for ComputeFullU , and is n-by-m if you asked for ComputeThinU .
The m first columns of U are the left singular vectors of the matrix being decomposed.
This method asserts that you asked for U to be computed.
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    eigen_assert(computeU() && "This SVD decomposition didn't compute U. Did you ask for it?");
    return m_matrixU;
  }
References Eigen::SVDBase< Derived >::computeU(), eigen_assert, Eigen::SVDBase< Derived >::m_isInitialized, and Eigen::SVDBase< Derived >::m_matrixU.
Referenced by Slic3r::Geometry::TransformationSVD::TransformationSVD(), Eigen::BDCSVD< _MatrixType >::compute(), igl::Frame_field_deformer::compute_optimal_rotations(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeRotationScaling(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeScalingRotation(), igl::frame_to_cross_field(), igl::min_quad_dense_precompute(), igl::orth(), igl::pinv(), igl::polar_svd(), igl::copyleft::comiso::FrameInterpolator::PolarDecomposition(), igl::shapeup_regular_face_projection(), and Eigen::umeyama().
matrixV()
template<typename Derived > const MatrixVType & Eigen::SVDBase< Derived >::matrixV () const inline
Returns
the V matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the V matrix is p-by-p if you asked for ComputeFullV , and is p-by-m if you asked for ComputeThinV .
The m first columns of V are the right singular vectors of the matrix being decomposed.
This method asserts that you asked for V to be computed.
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    eigen_assert(computeV() && "This SVD decomposition didn't compute V. Did you ask for it?");
    return m_matrixV;
  }
References Eigen::SVDBase< Derived >::computeV(), eigen_assert, Eigen::SVDBase< Derived >::m_isInitialized, and Eigen::SVDBase< Derived >::m_matrixV.
Referenced by Slic3r::Geometry::TransformationSVD::TransformationSVD(), Eigen::BDCSVD< _MatrixType >::compute(), igl::Frame_field_deformer::compute_idealWarp(), igl::Frame_field_deformer::compute_optimal_rotations(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeRotationScaling(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeScalingRotation(), igl::frame_to_cross_field(), igl::min_quad_dense_precompute(), igl::null(), igl::pinv(), igl::polar_svd(), igl::copyleft::comiso::FrameInterpolator::PolarDecomposition(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), igl::shapeup_regular_face_projection(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::Through(), and Eigen::umeyama().
nonzeroSingularValues()
template<typename Derived > Index Eigen::SVDBase< Derived >::nonzeroSingularValues () const inline
Returns
the number of singular values that are not exactly 0
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    return m_nonzeroSingularValues;
  }
References eigen_assert, Eigen::SVDBase< Derived >::m_isInitialized, and Eigen::SVDBase< Derived >::m_nonzeroSingularValues.
Referenced by Eigen::BDCSVD< _MatrixType >::compute().
rank()
template<typename Derived > Index Eigen::SVDBase< Derived >::rank () const inline
Returns
the rank of the matrix of which *this is the SVD.
Note
This method has to determine which singular values should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
  {
    using std::abs;
    eigen_assert(m_isInitialized && "JacobiSVD is not initialized.");
    if(m_singularValues.size()==0) return 0;
    RealScalar premultiplied_threshold = numext::maxi<RealScalar>(m_singularValues.coeff(0) * threshold(), (std::numeric_limits<RealScalar>::min)());
    Index i = m_nonzeroSingularValues-1;
    while(i>=0 && m_singularValues.coeff(i) < premultiplied_threshold) --i;
    return i+1;
  }
References eigen_assert, Eigen::SVDBase< Derived >::m_isInitialized, Eigen::SVDBase< Derived >::m_nonzeroSingularValues, Eigen::SVDBase< Derived >::m_singularValues, and Eigen::SVDBase< Derived >::threshold().
rows()
template<typename Derived > Index Eigen::SVDBase< Derived >::rows () const inline
{ return m_rows; }
References Eigen::SVDBase< Derived >::m_rows.
setThreshold() [1/2]
template<typename Derived > Derived & Eigen::SVDBase< Derived >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank() and solve(), which need to determine when singular values are to be considered nonzero. This is not used for the SVD decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). The default is NumTraits<Scalar>::epsilon()
Parameters
threshold The new value to use as the threshold.
A singular value will be considered nonzero if its value is strictly greater than .
If you want to come back to the default behavior, call setThreshold(Default_t)
  {
    m_usePrescribedThreshold = true;
    m_prescribedThreshold = threshold;
    return derived();
  }
References Eigen::SVDBase< Derived >::derived(), Eigen::SVDBase< Derived >::m_prescribedThreshold, Eigen::SVDBase< Derived >::m_usePrescribedThreshold, and Eigen::SVDBase< Derived >::threshold().
Referenced by igl::null().
setThreshold() [2/2]
template<typename Derived > Derived & Eigen::SVDBase< Derived >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
svd.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
  {
    m_usePrescribedThreshold = false;
    return derived();
  }
References Eigen::SVDBase< Derived >::derived(), and Eigen::SVDBase< Derived >::m_usePrescribedThreshold.
singularValues()
template<typename Derived > const SingularValuesType & Eigen::SVDBase< Derived >::singularValues () const inline
Returns
the vector of singular values.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the returned vector has size m. Singular values are always sorted in decreasing order.
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    return m_singularValues;
  }
References eigen_assert, Eigen::SVDBase< Derived >::m_isInitialized, and Eigen::SVDBase< Derived >::m_singularValues.
Referenced by Slic3r::Geometry::TransformationSVD::TransformationSVD(), Eigen::BDCSVD< _MatrixType >::compute(), igl::Frame_field_deformer::compute_idealWarp(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeRotationScaling(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::computeScalingRotation(), Eigen::BDCSVD< _MatrixType >::computeSVDofM(), igl::min_quad_dense_precompute(), igl::null(), igl::orth(), igl::pinv(), igl::polar_svd(), igl::copyleft::comiso::FrameInterpolator::PolarDecomposition(), and Eigen::umeyama().
solve()
template<typename Derived > template<typename Rhs > const Solve< Derived, Rhs > Eigen::SVDBase< Derived >::solve (const MatrixBase< Rhs > & b) const inline
Returns
a (least squares) solution of using the current SVD decomposition of A.
Parameters
b the right-hand-side of the equation to solve.
Note
Solving requires both U and V to be computed. Thin U and V are enough, there is no need for full U or V.
SVD solving is implicitly least-squares. Thus, this method serves both purposes of exact solving and least-squares solving. In other words, the returned solution is guaranteed to minimize the Euclidean norm .
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    eigen_assert(computeU() && computeV() && "SVD::solve() requires both unitaries U and V to be computed (thin unitaries suffice).");
    return Solve<Derived, Rhs>(derived(), b.derived());
  }
References Eigen::SVDBase< Derived >::computeU(), Eigen::SVDBase< Derived >::computeV(), Eigen::SVDBase< Derived >::derived(), eigen_assert, and Eigen::SVDBase< Derived >::m_isInitialized.
threshold()
template<typename Derived > RealScalar Eigen::SVDBase< Derived >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
  {
    eigen_assert(m_isInitialized || m_usePrescribedThreshold);
    // this temporary is needed to workaround a MSVC issue
    Index diagSize = (std::max<Index>)(1,m_diagSize);
    return m_usePrescribedThreshold ? m_prescribedThreshold
                                    : diagSize*NumTraits<Scalar>::epsilon();
  }
References eigen_assert, Eigen::SVDBase< Derived >::m_diagSize, Eigen::SVDBase< Derived >::m_isInitialized, Eigen::SVDBase< Derived >::m_prescribedThreshold, and Eigen::SVDBase< Derived >::m_usePrescribedThreshold.
Referenced by Eigen::SVDBase< Derived >::rank(), and Eigen::SVDBase< Derived >::setThreshold().
Member Data Documentation
m_cols
template<typename Derived > Index Eigen::SVDBase< Derived >::m_cols protected
Referenced by Eigen::SVDBase< Derived >::cols().
m_computationOptions
template<typename Derived > unsigned int Eigen::SVDBase< Derived >::m_computationOptions protected
m_computeFullU
template<typename Derived > bool Eigen::SVDBase< Derived >::m_computeFullU protected
Referenced by Eigen::SVDBase< Derived >::computeU().
m_computeFullV
template<typename Derived > bool Eigen::SVDBase< Derived >::m_computeFullV protected
Referenced by Eigen::SVDBase< Derived >::computeV().
m_computeThinU
template<typename Derived > bool Eigen::SVDBase< Derived >::m_computeThinU protected
Referenced by Eigen::SVDBase< Derived >::computeU().
m_computeThinV
template<typename Derived > bool Eigen::SVDBase< Derived >::m_computeThinV protected
Referenced by Eigen::SVDBase< Derived >::computeV().
m_diagSize
template<typename Derived > Index Eigen::SVDBase< Derived >::m_diagSize protected
Referenced by Eigen::SVDBase< Derived >::threshold().
m_isAllocated
template<typename Derived > bool Eigen::SVDBase< Derived >::m_isAllocated protected
m_isInitialized
template<typename Derived > bool Eigen::SVDBase< Derived >::m_isInitialized protected
Referenced by Eigen::SVDBase< Derived >::matrixU(), Eigen::SVDBase< Derived >::matrixV(), Eigen::SVDBase< Derived >::nonzeroSingularValues(), Eigen::SVDBase< Derived >::rank(), Eigen::SVDBase< Derived >::singularValues(), Eigen::SVDBase< Derived >::solve(), and Eigen::SVDBase< Derived >::threshold().
m_matrixU
template<typename Derived > MatrixUType Eigen::SVDBase< Derived >::m_matrixU protected
Referenced by Eigen::SVDBase< Derived >::matrixU().
m_matrixV
template<typename Derived > MatrixVType Eigen::SVDBase< Derived >::m_matrixV protected
Referenced by Eigen::SVDBase< Derived >::matrixV().
m_nonzeroSingularValues
template<typename Derived > Index Eigen::SVDBase< Derived >::m_nonzeroSingularValues protected
Referenced by Eigen::SVDBase< Derived >::nonzeroSingularValues(), and Eigen::SVDBase< Derived >::rank().
m_prescribedThreshold
template<typename Derived > RealScalar Eigen::SVDBase< Derived >::m_prescribedThreshold protected
Referenced by Eigen::SVDBase< Derived >::setThreshold(), and Eigen::SVDBase< Derived >::threshold().
m_rows
template<typename Derived > Index Eigen::SVDBase< Derived >::m_rows protected
Referenced by Eigen::SVDBase< Derived >::rows().
m_singularValues
template<typename Derived > SingularValuesType Eigen::SVDBase< Derived >::m_singularValues protected
Referenced by Eigen::SVDBase< Derived >::rank(), and Eigen::SVDBase< Derived >::singularValues().
m_usePrescribedThreshold
template<typename Derived > bool Eigen::SVDBase< Derived >::m_usePrescribedThreshold protected
Referenced by Eigen::SVDBase< Derived >::setThreshold(), Eigen::SVDBase< Derived >::setThreshold(), and Eigen::SVDBase< Derived >::threshold().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SVD/SVDBase.h