Prusa Slicer: Slic3r::AABBMesh::hit_result Class Reference
Slic3r::AABBMesh::hit_result Class Reference
#include <src/libslic3r/AABBMesh.hpp>
Public Member Functions
hit_result (double val=infty())
double distance () const
const Vec3d & direction () const
const Vec3d & source () const
Vec3d position () const
int face () const
bool is_valid () const
bool is_hit () const
const Vec3d & normal () const
bool is_inside () const
Static Public Member Functions
static constexpr double infty ()
Private Member Functions
hit_result (const AABBMesh &em)
Private Attributes
double m_t = infty()
int m_face_id = -1
const AABBMesh * m_mesh = nullptr
Vec3d m_dir = Vec3d::Zero()
Vec3d m_source = Vec3d::Zero()
Vec3d m_normal = Vec3d::Zero()
Friends
class AABBMesh
Detailed Description
Constructor & Destructor Documentation
hit_result() [1/2]
Slic3r::AABBMesh::hit_result::hit_result (const AABBMesh & em) inline explicit private
: m_mesh(&em) {}
hit_result() [2/2]
Slic3r::AABBMesh::hit_result::hit_result (double val = infty()) inline explicit
: m_t(val) {}
Member Function Documentation
direction()
const Vec3d & Slic3r::AABBMesh::hit_result::direction () const inline
{ return m_dir; }
References m_dir.
distance()
double Slic3r::AABBMesh::hit_result::distance () const inline
{ return m_t; }
References m_t.
Referenced by Slic3r::sla::DefaultSupportTree::add_pinheads(), Slic3r::sla::DefaultSupportTree::bridge_mesh_distance(), Slic3r::sla::connect_to_ground(), Slic3r::sla::DefaultSupportTree::connect_to_model_body(), Slic3r::sla::create_ground_pillar(), Slic3r::sla::min_hit(), Slic3r::sla::optimize_anchor_placement(), Slic3r::sla::optimize_pinhead_placement(), Slic3r::sla::search_ground_route(), and Slic3r::sla::search_widening_path().
face()
int Slic3r::AABBMesh::hit_result::face () const inline
{ return m_face_id; }
References m_face_id.
Referenced by Slic3r::GUI::MeshRaycaster::closest_hit(), and Slic3r::GUI::RaycastManager::first_hit().
infty()
static constexpr double Slic3r::AABBMesh::hit_result::infty () inline static constexpr
{ return std::numeric_limits<double>::infinity(); }
Referenced by Slic3r::sla::DrainHole::get_intersections().
is_hit()
bool Slic3r::AABBMesh::hit_result::is_hit () const inline
{ return m_face_id >= 0 && !std::isinf(m_t); }
References m_face_id, and m_t.
Referenced by is_inside().
is_inside()
bool Slic3r::AABBMesh::hit_result::is_inside () const inline
{
            return is_hit() && normal().dot(m_dir) > 0;
        }
References is_hit(), m_dir, and normal().
is_valid()
bool Slic3r::AABBMesh::hit_result::is_valid () const inline
{ return m_mesh != nullptr; }
References m_mesh.
Referenced by normal().
normal()
const Vec3d & Slic3r::AABBMesh::hit_result::normal () const inline
{
            assert(is_valid());
            return m_normal;
        }
References is_valid(), and m_normal.
Referenced by Slic3r::GUI::MeshRaycaster::closest_hit(), and is_inside().
position()
Vec3d Slic3r::AABBMesh::hit_result::position () const inline
{ return m_source + m_dir * m_t; }
References m_dir, m_source, and m_t.
Referenced by Slic3r::GUI::MeshRaycaster::closest_hit(), and Slic3r::GUI::RaycastManager::first_hit().
source()
const Vec3d & Slic3r::AABBMesh::hit_result::source () const inline
{ return m_source; }
References m_source.
Friends And Related Symbol Documentation
AABBMesh
friend class AABBMesh friend
Member Data Documentation
m_dir
Vec3d Slic3r::AABBMesh::hit_result::m_dir = Vec3d::Zero() private
Referenced by direction(), is_inside(), position(), and Slic3r::AABBMesh::query_ray_hit().
m_face_id
int Slic3r::AABBMesh::hit_result::m_face_id = -1 private
Referenced by face(), is_hit(), and Slic3r::AABBMesh::query_ray_hit().
m_mesh
const AABBMesh* Slic3r::AABBMesh::hit_result::m_mesh = nullptr private
Referenced by is_valid().
m_normal
Vec3d Slic3r::AABBMesh::hit_result::m_normal = Vec3d::Zero() private
Referenced by normal(), and Slic3r::AABBMesh::query_ray_hit().
m_source
Vec3d Slic3r::AABBMesh::hit_result::m_source = Vec3d::Zero() private
Referenced by position(), Slic3r::AABBMesh::query_ray_hit(), and source().
m_t
double Slic3r::AABBMesh::hit_result::m_t = infty() private
Referenced by distance(), is_hit(), position(), and Slic3r::AABBMesh::query_ray_hit().
The documentation for this class was generated from the following file:
src/libslic3r/AABBMesh.hpp