Prusa Slicer: Eigen::SparseQR_QProduct< SparseQRType, Derived > Struct Template Reference
Eigen::SparseQR_QProduct< SparseQRType, Derived > Struct Template Reference
#include <src/eigen/Eigen/src/SparseQR/SparseQR.h>
Public Types
typedef SparseQRType::QRMatrixType MatrixType
typedef SparseQRType::Scalar Scalar
typedef internal::traits< SparseQR_QProduct< SparseQRType, Derived > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
SparseQR_QProduct (const SparseQRType &qr, const Derived &other, bool transpose)
Index rows () const
Index cols () const
template<typename DesType >
void evalTo (DesType &res) const
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Public Attributes
const SparseQRType & m_qr
const Derived & m_other
bool m_transpose
Detailed Description
template<typename SparseQRType, typename Derived>
struct Eigen::SparseQR_QProduct< SparseQRType, Derived >
Member Typedef Documentation
Base
typedef internal::dense_xpr_base<ReturnByValue>::type Eigen::ReturnByValue< SparseQR_QProduct< SparseQRType, Derived > >::Base inherited
MatrixType
template<typename SparseQRType , typename Derived > typedef SparseQRType::QRMatrixType Eigen::SparseQR_QProduct< SparseQRType, Derived >::MatrixType
ReturnType
typedef internal::traits<SparseQR_QProduct< SparseQRType, Derived > >::ReturnType Eigen::ReturnByValue< SparseQR_QProduct< SparseQRType, Derived > >::ReturnType inherited
Scalar
template<typename SparseQRType , typename Derived > typedef SparseQRType::Scalar Eigen::SparseQR_QProduct< SparseQRType, Derived >::Scalar
Constructor & Destructor Documentation
SparseQR_QProduct()
template<typename SparseQRType , typename Derived > Eigen::SparseQR_QProduct< SparseQRType, Derived >::SparseQR_QProduct (const SparseQRType & qr, const Derived & other, bool transpose) inline
                                                                                  :
  m_qr(qr),m_other(other),m_transpose(transpose) {}
Member Function Documentation
coeff() [1/2]
const Unusable & Eigen::ReturnByValue< SparseQR_QProduct< SparseQRType, Derived > >::coeff (Index) const inline inherited
{ return *reinterpret_cast<const Unusable*>(this); }
coeff() [2/2]
const Unusable & Eigen::ReturnByValue< SparseQR_QProduct< SparseQRType, Derived > >::coeff (Index , Index) const inline inherited
{ return *reinterpret_cast<const Unusable*>(this); }
coeffRef() [1/2]
Unusable & Eigen::ReturnByValue< SparseQR_QProduct< SparseQRType, Derived > >::coeffRef (Index) inline inherited
{ return *reinterpret_cast<Unusable*>(this); }
coeffRef() [2/2]
Unusable & Eigen::ReturnByValue< SparseQR_QProduct< SparseQRType, Derived > >::coeffRef (Index , Index) inline inherited
{ return *reinterpret_cast<Unusable*>(this); }
cols()
template<typename SparseQRType , typename Derived > Index Eigen::SparseQR_QProduct< SparseQRType, Derived >::cols () const inline
{ return m_other.cols(); }
References Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_other.
Referenced by Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo().
evalTo() [1/2]
EIGEN_DEVICE_FUNC void Eigen::ReturnByValue< SparseQR_QProduct< SparseQRType, Derived > >::evalTo (Dest & dst) const inline inherited
    { static_cast<const Derived*>(this)->evalTo(dst); }
evalTo() [2/2]
template<typename SparseQRType , typename Derived > template<typename DesType > void Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo (DesType & res) const inline
  {
    Index m = m_qr.rows();
    Index n = m_qr.cols();
    Index diagSize = (std::min)(m,n);
    res = m_other;
    if (m_transpose)
    {
      eigen_assert(m_qr.m_Q.rows() == m_other.rows() && "Non conforming object sizes");
      //Compute res = Q' * other column by column
      for(Index j = 0; j < res.cols(); j++){
        for (Index k = 0; k < diagSize; k++)
        {
          Scalar tau = Scalar(0);
          tau = m_qr.m_Q.col(k).dot(res.col(j));
          if(tau==Scalar(0)) continue;
          tau = tau * m_qr.m_hcoeffs(k);
          res.col(j) -= tau * m_qr.m_Q.col(k);
        }
      }
    }
    else
    {
      eigen_assert(m_qr.matrixQ().cols() == m_other.rows() && "Non conforming object sizes");
      res.conservativeResize(rows(), cols());
      // Compute res = Q * other column by column
      for(Index j = 0; j < res.cols(); j++)
      {
        for (Index k = diagSize-1; k >=0; k--)
        {
          Scalar tau = Scalar(0);
          tau = m_qr.m_Q.col(k).dot(res.col(j));
          if(tau==Scalar(0)) continue;
          tau = tau * numext::conj(m_qr.m_hcoeffs(k));
          res.col(j) -= tau * m_qr.m_Q.col(k);
        }
      }
    }
  }
References Eigen::SparseQR_QProduct< SparseQRType, Derived >::cols(), eigen_assert, Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_other, Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_qr, Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_transpose, and Eigen::SparseQR_QProduct< SparseQRType, Derived >::rows().
rows()
template<typename SparseQRType , typename Derived > Index Eigen::SparseQR_QProduct< SparseQRType, Derived >::rows () const inline
{ return m_qr.matrixQ().rows(); }
References Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_qr.
Referenced by Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo().
Member Data Documentation
m_other
template<typename SparseQRType , typename Derived > const Derived& Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_other
Referenced by Eigen::SparseQR_QProduct< SparseQRType, Derived >::cols(), and Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo().
m_qr
template<typename SparseQRType , typename Derived > const SparseQRType& Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_qr
Referenced by Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo(), and Eigen::SparseQR_QProduct< SparseQRType, Derived >::rows().
m_transpose
template<typename SparseQRType , typename Derived > bool Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_transpose
Referenced by Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/SparseQR/SparseQR.h