Prusa Slicer: Slic3r::GUI::GLTexture Class Reference
Slic3r::GUI::GLTexture Class Reference
#include <src/slic3r/GUI/GLTexture.hpp>
Classes
class Compressor
struct Quad_UVs
struct UV
Public Types
enum ECompressionType : unsigned char { None , SingleThreaded , MultiThreaded }
Public Member Functions
GLTexture ()
virtual ~GLTexture ()
bool load_from_file (const std::string &filename, bool use_mipmaps, ECompressionType compression_type, bool apply_anisotropy)
bool load_from_svg_file (const std::string &filename, bool use_mipmaps, bool compress, bool apply_anisotropy, unsigned int max_size_px)
bool load_from_svg_files_as_sprites_array (const std::vector< std::string > &filenames, const std::vector< std::pair< int, bool > > &states, unsigned int sprite_size_px, bool compress)
void reset ()
unsigned int get_id () const
int get_width () const
int get_height () const
const std::string & get_source () const
bool unsent_compressed_data_available () const
void send_compressed_data_to_gpu ()
bool all_compressed_data_sent_to_gpu () const
Static Public Member Functions
static void render_texture (unsigned int tex_id, float left, float right, float bottom, float top)
static void render_sub_texture (unsigned int tex_id, float left, float right, float bottom, float top, const Quad_UVs &uvs)
Static Public Attributes
static Quad_UVs FullTextureUVs = { { 0.0f, 1.0f }, { 1.0f, 1.0f }, { 1.0f, 0.0f }, { 0.0f, 0.0f } }
Protected Attributes
unsigned int m_id { 0 }
int m_width { 0 }
int m_height { 0 }
std::string m_source
Compressor m_compressor
Private Member Functions
bool load_from_png (const std::string &filename, bool use_mipmaps, ECompressionType compression_type, bool apply_anisotropy)
bool load_from_svg (const std::string &filename, bool use_mipmaps, bool compress, bool apply_anisotropy, unsigned int max_size_px)
Friends
class Compressor
Detailed Description
Class Documentation
Slic3r::GUI::GLTexture::Quad_UVs
struct Slic3r::GUI::GLTexture::Quad_UVs
Class Members
UV left_bottom
UV left_top
UV right_bottom
UV right_top
Slic3r::GUI::GLTexture::UV
struct Slic3r::GUI::GLTexture::UV
Class Members
float u { 0.0f }
float v { 0.0f }
Member Enumeration Documentation
ECompressionType
enum Slic3r::GUI::GLTexture::ECompressionType : unsigned char
Enumerator
None
SingleThreaded
MultiThreaded
        {
            None,
            SingleThreaded,
            MultiThreaded
        };
Constructor & Destructor Documentation
GLTexture()
Slic3r::GUI::GLTexture::GLTexture ()
    : m_compressor(*this)
{
}
~GLTexture()
Slic3r::GUI::GLTexture::~GLTexture () virtual
{
    reset();
}
References reset().
Member Function Documentation
all_compressed_data_sent_to_gpu()
bool Slic3r::GUI::GLTexture::all_compressed_data_sent_to_gpu () const inline
{ return m_compressor.all_compressed_data_sent_to_gpu(); }
References Slic3r::GUI::GLTexture::Compressor::all_compressed_data_sent_to_gpu(), and m_compressor.
get_height()
int Slic3r::GUI::GLTexture::get_height () const inline
{ return m_height; }
References m_height.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::IconManager::init(), Slic3r::GUI::GLGizmosManager::render_arrow(), Slic3r::GUI::GLToolbar::render_arrow(), Slic3r::GUI::GLGizmosManager::render_background(), Slic3r::GUI::GLToolbar::render_background(), Slic3r::GUI::GLToolbar::render_horizontal(), and Slic3r::GUI::GLToolbar::render_vertical().
get_id()
unsigned int Slic3r::GUI::GLTexture::get_id () const inline
{ return m_id; }
References m_id.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLToolbar::init(), Slic3r::GUI::IconManager::init(), Slic3r::GUI::GLGizmosManager::init_arrow(), Slic3r::GUI::GLToolbar::init_arrow(), Slic3r::GUI::GLGizmosManager::render_arrow(), Slic3r::GUI::GLToolbar::render_arrow(), Slic3r::GUI::GLGizmosManager::render_background(), Slic3r::GUI::GLToolbar::render_background(), Slic3r::GUI::GLToolbar::render_horizontal(), Slic3r::GUI::Bed3D::render_texture(), and Slic3r::GUI::GLToolbar::render_vertical().
get_source()
const std::string & Slic3r::GUI::GLTexture::get_source () const inline
{ return m_source; }
References m_source.
Referenced by Slic3r::GUI::Bed3D::render_texture().
get_width()
int Slic3r::GUI::GLTexture::get_width () const inline
{ return m_width; }
References m_width.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::IconManager::init(), Slic3r::GUI::GLGizmosManager::render_arrow(), Slic3r::GUI::GLToolbar::render_arrow(), Slic3r::GUI::GLGizmosManager::render_background(), Slic3r::GUI::GLToolbar::render_background(), Slic3r::GUI::GLToolbar::render_horizontal(), and Slic3r::GUI::GLToolbar::render_vertical().
load_from_file()
bool Slic3r::GUI::GLTexture::load_from_file (const std::string & filename, bool use_mipmaps, ECompressionType compression_type, bool apply_anisotropy)
{
    reset();
    if (!boost::filesystem::exists(filename))
        return false;
    if (boost::algorithm::iends_with(filename, ".png"))
        return load_from_png(filename, use_mipmaps, compression_type, apply_anisotropy);
    else
        return false;
}
References load_from_png(), and reset().
Referenced by Slic3r::GUI::GLGizmosManager::init(), Slic3r::GUI::GLToolbar::init(), and Slic3r::GUI::Bed3D::render_texture().
load_from_png()
bool Slic3r::GUI::GLTexture::load_from_png (const std::string & filename, bool use_mipmaps, ECompressionType compression_type, bool apply_anisotropy) private
{
    const bool compression_enabled = (compression_type != None) && OpenGLManager::are_compressed_textures_supported();
    // Load a PNG with an alpha channel.
    wxImage image;
    if (!image.LoadFile(wxString::FromUTF8(filename.c_str()), wxBITMAP_TYPE_PNG)) {
        reset();
        return false;
    }
    m_width = image.GetWidth();
    m_height = image.GetHeight();
    bool requires_rescale = false;
    if (use_mipmaps && compression_enabled && OpenGLManager::force_power_of_two_textures()) {
        if (to_squared_power_of_two(boost::filesystem::path(filename).filename().string(), OpenGLManager::get_gl_info().get_max_tex_size(), m_width, m_height))
            requires_rescale = true;
    }
    if (compression_enabled && compression_type == MultiThreaded) {
        // the stb_dxt compression library seems to like only texture sizes which are a multiple of 4
        int width_rem = m_width % 4;
        int height_rem = m_height % 4;
        if (width_rem != 0) {
            m_width += (4 - width_rem);
            requires_rescale = true;
        }
        if (height_rem != 0) {
            m_height += (4 - height_rem);
            requires_rescale = true;
        }
    }
    if (requires_rescale)
        image = image.ResampleBicubic(m_width, m_height);
    int n_pixels = m_width * m_height;
    if (n_pixels <= 0) {
        reset();
        return false;
    }
    // Get RGB & alpha raw data from wxImage, pack them into an array.
    unsigned char* img_rgb = image.GetData();
    if (img_rgb == nullptr) {
        reset();
        return false;
    }
    unsigned char* img_alpha = image.GetAlpha();
    std::vector<unsigned char> data(n_pixels * 4, 0);
    for (int i = 0; i < n_pixels; ++i) {
        int data_id = i * 4;
        int img_id = i * 3;
        data[data_id + 0] = img_rgb[img_id + 0];
        data[data_id + 1] = img_rgb[img_id + 1];
        data[data_id + 2] = img_rgb[img_id + 2];
        data[data_id + 3] = (img_alpha != nullptr) ? img_alpha[i] : 255;
    }
    // sends data to gpu
    glsafe(::glPixelStorei(GL_UNPACK_ALIGNMENT, 1));
    glsafe(::glGenTextures(1, &m_id));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_id));
    if (apply_anisotropy) {
        GLfloat max_anisotropy = OpenGLManager::get_gl_info().get_max_anisotropy();
        if (max_anisotropy > 1.0f)
            glsafe(::glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAX_ANISOTROPY_EXT, max_anisotropy));
    }
    if (compression_enabled) {
        if (compression_type == SingleThreaded)
            glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, (GLsizei)m_width, (GLsizei)m_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, (const void*)data.data()));
        else {
            // initializes the texture on GPU
            glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, (GLsizei)m_width, (GLsizei)m_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, 0));
            // and send the uncompressed data to the compressor
            m_compressor.add_level((unsigned int)m_width, (unsigned int)m_height, data);
        }
    }
    else
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, (GLsizei)m_width, (GLsizei)m_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, (const void*)data.data()));
    if (use_mipmaps) {
        // we manually generate mipmaps because glGenerateMipmap() function is not reliable on all graphics cards
        int lod_w = m_width;
        int lod_h = m_height;
        GLint level = 0;
        while (lod_w > 1 || lod_h > 1) {
            ++level;
            lod_w = std::max(lod_w / 2, 1);
            lod_h = std::max(lod_h / 2, 1);
            n_pixels = lod_w * lod_h;
            image = image.ResampleBicubic(lod_w, lod_h);
            data.resize(n_pixels * 4);
            img_rgb = image.GetData();
            img_alpha = image.GetAlpha();
            for (int i = 0; i < n_pixels; ++i) {
                int data_id = i * 4;
                int img_id = i * 3;
                data[data_id + 0] = img_rgb[img_id + 0];
                data[data_id + 1] = img_rgb[img_id + 1];
                data[data_id + 2] = img_rgb[img_id + 2];
                data[data_id + 3] = (img_alpha != nullptr) ? img_alpha[i] : 255;
            }
            if (compression_enabled) {
                if (compression_type == SingleThreaded)
                    glsafe(::glTexImage2D(GL_TEXTURE_2D, level, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, (GLsizei)m_width, (GLsizei)m_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, (const void*)data.data()));
                else {
                    // initializes the texture on GPU
                    glsafe(::glTexImage2D(GL_TEXTURE_2D, level, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, (GLsizei)lod_w, (GLsizei)lod_h, 0, GL_RGBA, GL_UNSIGNED_BYTE, 0));
                    // and send the uncompressed data to the compressor
                    m_compressor.add_level((unsigned int)lod_w, (unsigned int)lod_h, data);
                }
            }
            else
                glsafe(::glTexImage2D(GL_TEXTURE_2D, level, GL_RGBA, (GLsizei)lod_w, (GLsizei)lod_h, 0, GL_RGBA, GL_UNSIGNED_BYTE, (const void*)data.data()));
        }
        if (!compression_enabled) {
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAX_LEVEL, level));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR));
        }
    }
    else {
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAX_LEVEL, 0));
    }
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
    glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
    m_source = filename;
    if (compression_type == MultiThreaded)
        // start asynchronous compression
        m_compressor.start_compressing();
    return true;
}
References Slic3r::GUI::GLTexture::Compressor::add_level(), Slic3r::GUI::OpenGLManager::are_compressed_textures_supported(), Slic3r::GUI::OpenGLManager::force_power_of_two_textures(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::get_max_anisotropy(), glsafe, m_compressor, m_height, m_id, m_source, m_width, MultiThreaded, None, reset(), SingleThreaded, Slic3r::GUI::GLTexture::Compressor::start_compressing(), and Slic3r::GUI::to_squared_power_of_two().
Referenced by load_from_file().
load_from_svg()
bool Slic3r::GUI::GLTexture::load_from_svg (const std::string & filename, bool use_mipmaps, bool compress, bool apply_anisotropy, unsigned int max_size_px) private
{
    const bool compression_enabled = compress && OpenGLManager::are_compressed_textures_supported();
    NSVGimage* image = BitmapCache::nsvgParseFromFileWithReplace(filename.c_str(), "px", 96.0f, {});
    if (image == nullptr) {
        reset();
        return false;
    }
    const float scale = (float)max_size_px / std::max(image->width, image->height);
    m_width = (int)(scale * image->width);
    m_height = (int)(scale * image->height);
    if (use_mipmaps && compression_enabled && OpenGLManager::force_power_of_two_textures())
        to_squared_power_of_two(boost::filesystem::path(filename).filename().string(), max_size_px, m_width, m_height);
    float scale_w = (float)m_width / image->width;
    float scale_h = (float)m_height / image->height;
    if (compression_enabled) {
        // the stb_dxt compression library seems to like only texture sizes which are a multiple of 4
        int width_rem = m_width % 4;
        int height_rem = m_height % 4;
        if (width_rem != 0)
            m_width += (4 - width_rem);
        if (height_rem != 0)
            m_height += (4 - height_rem);
    }
    const int n_pixels = m_width * m_height;
    if (n_pixels <= 0) {
        reset();
        nsvgDelete(image);
        return false;
    }
    NSVGrasterizer* rast = nsvgCreateRasterizer();
    if (rast == nullptr) {
        nsvgDelete(image);
        reset();
        return false;
    }
    // creates the temporary buffer only once, with max size, and reuse it for all the levels, if generating mipmaps
    std::vector<unsigned char> data(n_pixels * 4, 0);
    nsvgRasterizeXY(rast, image, 0, 0, scale_w, scale_h, data.data(), m_width, m_height, m_width * 4);
    // sends data to gpu
    glsafe(::glPixelStorei(GL_UNPACK_ALIGNMENT, 1));
    glsafe(::glGenTextures(1, &m_id));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_id));
    if (apply_anisotropy) {
        GLfloat max_anisotropy = OpenGLManager::get_gl_info().get_max_anisotropy();
        if (max_anisotropy > 1.0f)
            glsafe(::glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAX_ANISOTROPY_EXT, max_anisotropy));
    }
    if (compression_enabled) {
        // initializes the texture on GPU
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, (GLsizei)m_width, (GLsizei)m_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, 0));
        // and send the uncompressed data to the compressor
        m_compressor.add_level((unsigned int)m_width, (unsigned int)m_height, data);
    }
    else
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, (GLsizei)m_width, (GLsizei)m_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, (const void*)data.data()));
    if (use_mipmaps) {
        // we manually generate mipmaps because glGenerateMipmap() function is not reliable on all graphics cards
        int lod_w = m_width;
        int lod_h = m_height;
        GLint level = 0;
        while (lod_w > 1 || lod_h > 1) {
            ++level;
            lod_w = std::max(lod_w / 2, 1);
            lod_h = std::max(lod_h / 2, 1);
            scale_w /= 2.0f;
            scale_h /= 2.0f;
            data.resize(lod_w * lod_h * 4);
            nsvgRasterizeXY(rast, image, 0, 0, scale_w, scale_h, data.data(), lod_w, lod_h, lod_w * 4);
            if (compression_enabled) {
                // initializes the texture on GPU
                glsafe(::glTexImage2D(GL_TEXTURE_2D, level, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, (GLsizei)lod_w, (GLsizei)lod_h, 0, GL_RGBA, GL_UNSIGNED_BYTE, 0));
                // and send the uncompressed data to the compressor
                m_compressor.add_level((unsigned int)lod_w, (unsigned int)lod_h, data);
            }
            else
                glsafe(::glTexImage2D(GL_TEXTURE_2D, level, GL_RGBA, (GLsizei)lod_w, (GLsizei)lod_h, 0, GL_RGBA, GL_UNSIGNED_BYTE, (const void*)data.data()));
        }
        if (!compression_enabled) {
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAX_LEVEL, level));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR));
        }
    }
    else {
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAX_LEVEL, 0));
    }
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
    glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
    m_source = filename;
    if (compression_enabled)
        // start asynchronous compression
        m_compressor.start_compressing();
    nsvgDeleteRasterizer(rast);
    nsvgDelete(image);
    return true;
}
References Slic3r::GUI::GLTexture::Compressor::add_level(), Slic3r::GUI::OpenGLManager::are_compressed_textures_supported(), compress, Slic3r::GUI::OpenGLManager::force_power_of_two_textures(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::get_max_anisotropy(), glsafe, m_compressor, m_height, m_id, m_source, m_width, Slic3r::GUI::BitmapCache::nsvgParseFromFileWithReplace(), reset(), scale(), Slic3r::GUI::GLTexture::Compressor::start_compressing(), and Slic3r::GUI::to_squared_power_of_two().
Referenced by load_from_svg_file().
load_from_svg_file()
bool Slic3r::GUI::GLTexture::load_from_svg_file (const std::string & filename, bool use_mipmaps, bool compress, bool apply_anisotropy, unsigned int max_size_px)
{
    reset();
    if (!boost::filesystem::exists(filename))
        return false;
    if (boost::algorithm::iends_with(filename, ".svg"))
        return load_from_svg(filename, use_mipmaps, compress, apply_anisotropy, max_size_px);
    else
        return false;
}
References compress, load_from_svg(), and reset().
Referenced by Slic3r::GUI::GLGizmosManager::init_arrow(), Slic3r::GUI::GLToolbar::init_arrow(), and Slic3r::GUI::Bed3D::render_texture().
load_from_svg_files_as_sprites_array()
bool Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array (const std::vector< std::string > & filenames, const std::vector< std::pair< int, bool > > & states, unsigned int sprite_size_px, bool compress)
{
    reset();
    if (filenames.empty() || states.empty() || sprite_size_px == 0)
        return false;
    // every tile needs to have a 1px border around it to avoid artifacts when linear sampling on its edges
    unsigned int sprite_size_px_ex = sprite_size_px + 1;
    m_width = 1 + (int)(sprite_size_px_ex * states.size());
    m_height = 1 + (int)(sprite_size_px_ex * filenames.size());
    int n_pixels = m_width * m_height;
    int sprite_n_pixels = sprite_size_px_ex * sprite_size_px_ex;
    int sprite_stride = sprite_size_px_ex * 4;
    int sprite_bytes = sprite_n_pixels * 4;
    if (n_pixels <= 0) {
        reset();
        return false;
    }
    std::vector<unsigned char> data(n_pixels * 4, 0);
    std::vector<unsigned char> sprite_data(sprite_bytes, 0);
    std::vector<unsigned char> sprite_white_only_data(sprite_bytes, 0);
    std::vector<unsigned char> sprite_gray_only_data(sprite_bytes, 0);
    std::vector<unsigned char> output_data(sprite_bytes, 0);
    NSVGrasterizer* rast = nsvgCreateRasterizer();
    if (rast == nullptr) {
        reset();
        return false;
    }
    int sprite_id = -1;
    for (const std::string& filename : filenames) {
        ++sprite_id;
        if (!boost::filesystem::exists(filename))
            continue;
        if (!boost::algorithm::iends_with(filename, ".svg"))
            continue;
        NSVGimage* image = BitmapCache::nsvgParseFromFileWithReplace(filename.c_str(), "px", 96.0f, {});
        if (image == nullptr)
            continue;
        float scale = (float)sprite_size_px / std::max(image->width, image->height);
        // offset by 1 to leave the first pixel empty (both in x and y)
        nsvgRasterize(rast, image, 1, 1, scale, sprite_data.data(), sprite_size_px_ex, sprite_size_px_ex, sprite_stride);
        // makes white only copy of the sprite
        ::memcpy((void*)sprite_white_only_data.data(), (const void*)sprite_data.data(), sprite_bytes);
        for (int i = 0; i < sprite_n_pixels; ++i) {
            int offset = i * 4;
            if (sprite_white_only_data.data()[offset] != 0)
                ::memset((void*)&sprite_white_only_data.data()[offset], 255, 3);
        }
        // makes gray only copy of the sprite
        ::memcpy((void*)sprite_gray_only_data.data(), (const void*)sprite_data.data(), sprite_bytes);
        for (int i = 0; i < sprite_n_pixels; ++i) {
            int offset = i * 4;
            if (sprite_gray_only_data.data()[offset] != 0)
                ::memset((void*)&sprite_gray_only_data.data()[offset], 128, 3);
        }
        int sprite_offset_px = sprite_id * (int)sprite_size_px_ex * m_width;
        int state_id = -1;
        for (const std::pair<int, bool>& state : states) {
            ++state_id;
            // select the sprite variant
            std::vector<unsigned char>* src = nullptr;
            switch (state.first)
            {
            case 1:  { src = &sprite_white_only_data; break; }
            case 2:  { src = &sprite_gray_only_data; break; }
            default: { src = &sprite_data; break; }
            }
            ::memcpy((void*)output_data.data(), (const void*)src->data(), sprite_bytes);
            // applies background, if needed
            if (state.second) {
                float inv_255 = 1.0f / 255.0f;
                // offset by 1 to leave the first pixel empty (both in x and y)
                for (unsigned int r = 1; r <= sprite_size_px; ++r) {
                    unsigned int offset_r = r * sprite_size_px_ex;
                    for (unsigned int c = 1; c <= sprite_size_px; ++c) {
                        unsigned int offset = (offset_r + c) * 4;
                        float alpha = (float)output_data.data()[offset + 3] * inv_255;
                        output_data.data()[offset + 0] = (unsigned char)(output_data.data()[offset + 0] * alpha);
                        output_data.data()[offset + 1] = (unsigned char)(output_data.data()[offset + 1] * alpha);
                        output_data.data()[offset + 2] = (unsigned char)(output_data.data()[offset + 2] * alpha);
                        output_data.data()[offset + 3] = (unsigned char)(128 * (1.0f - alpha) + output_data.data()[offset + 3] * alpha);
                    }
                }
            }
            int state_offset_px = sprite_offset_px + state_id * sprite_size_px_ex;
            for (int j = 0; j < (int)sprite_size_px_ex; ++j) {
                ::memcpy((void*)&data.data()[(state_offset_px + j * m_width) * 4], (const void*)&output_data.data()[j * sprite_stride], sprite_stride);
            }
        }
        nsvgDelete(image);
    }
    nsvgDeleteRasterizer(rast);
    // sends data to gpu
    glsafe(::glPixelStorei(GL_UNPACK_ALIGNMENT, 1));
    glsafe(::glGenTextures(1, &m_id));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_id));
    if (compress && OpenGLManager::are_compressed_textures_supported())
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, (GLsizei)m_width, (GLsizei)m_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, (const void*)data.data()));
    else
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, (GLsizei)m_width, (GLsizei)m_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, (const void*)data.data()));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAX_LEVEL, 0));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
    glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
    m_source = filenames.front();
#if 0
    // debug output
    static int pass = 0;
    ++pass;
    wxImage output(m_width, m_height);
    output.InitAlpha();
    for (int h = 0; h < m_height; ++h) {
        int px_h = h * m_width;
        for (int w = 0; w < m_width; ++w) {
            int offset = (px_h + w) * 4;
            output.SetRGB(w, h, data.data()[offset + 0], data.data()[offset + 1], data.data()[offset + 2]);
            output.SetAlpha(w, h, data.data()[offset + 3]);
        }
    }
    std::string out_filename = resources_dir() + "/icons/test_" + std::to_string(pass) + ".png";
    output.SaveFile(out_filename, wxBITMAP_TYPE_PNG);
#endif // 0
    return true;
}
References Slic3r::GUI::OpenGLManager::are_compressed_textures_supported(), compress, glsafe, m_height, m_id, m_source, m_width, Slic3r::GUI::BitmapCache::nsvgParseFromFileWithReplace(), Slic3r::offset(), reset(), Slic3r::resources_dir(), and scale().
Referenced by Slic3r::GUI::GLGizmosManager::generate_icons_texture(), Slic3r::GUI::GLToolbar::generate_icons_texture(), and Slic3r::GUI::IconManager::init().
render_sub_texture()
void Slic3r::GUI::GLTexture::render_sub_texture (unsigned int tex_id, float left, float right, float bottom, float top, const Quad_UVs & uvs) static
{
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
#if !ENABLE_GL_CORE_PROFILE && !ENABLE_OPENGL_ES
    glsafe(::glEnable(GL_TEXTURE_2D));
    glsafe(::glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE));
#endif // !ENABLE_GL_CORE_PROFILE && !ENABLE_OPENGL_ES
    glsafe(::glBindTexture(GL_TEXTURE_2D, (GLuint)tex_id));
    GLModel::Geometry init_data;
    init_data.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P2T2 };
    init_data.reserve_vertices(4);
    init_data.reserve_indices(6);
    // vertices
    init_data.add_vertex(Vec2f(left, bottom),  Vec2f(uvs.left_bottom.u, uvs.left_bottom.v));
    init_data.add_vertex(Vec2f(right, bottom), Vec2f(uvs.right_bottom.u, uvs.right_bottom.v));
    init_data.add_vertex(Vec2f(right, top),    Vec2f(uvs.right_top.u, uvs.right_top.v));
    init_data.add_vertex(Vec2f(left, top),     Vec2f(uvs.left_top.u, uvs.left_top.v));
        // indices
    init_data.add_triangle(0, 1, 2);
    init_data.add_triangle(2, 3, 0);
    GLModel model;
    model.init_from(std::move(init_data));
    GLShaderProgram* shader = wxGetApp().get_shader("flat_texture");
    if (shader != nullptr) {
        shader->start_using();
        shader->set_uniform("view_model_matrix", Transform3d::Identity());
        shader->set_uniform("projection_matrix", Transform3d::Identity());
        model.render();
        shader->stop_using();
    }
    glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
#if !ENABLE_GL_CORE_PROFILE && !ENABLE_OPENGL_ES
    glsafe(::glDisable(GL_TEXTURE_2D));
#endif // !ENABLE_GL_CORE_PROFILE && !ENABLE_OPENGL_ES
    glsafe(::glDisable(GL_BLEND));
}
References Slic3r::GUI::GLModel::Geometry::add_triangle(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::GUI::GLModel::Geometry::format, glsafe, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLTexture::Quad_UVs::left_bottom, Slic3r::GUI::GLTexture::Quad_UVs::left_top, Slic3r::GUI::GLModel::Geometry::P2T2, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLTexture::Quad_UVs::right_bottom, Slic3r::GUI::GLTexture::Quad_UVs::right_top, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::GUI::GLModel::Geometry::Triangles, Slic3r::GUI::GLTexture::UV::u, and Slic3r::GUI::GLTexture::UV::v.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLToolbarItem::render(), Slic3r::GUI::GLGizmosManager::render_arrow(), Slic3r::GUI::GLToolbar::render_arrow(), Slic3r::GUI::GLGizmosManager::render_background(), Slic3r::GUI::GLToolbar::render_background(), and render_texture().
render_texture()
void Slic3r::GUI::GLTexture::render_texture (unsigned int tex_id, float left, float right, float bottom, float top) static
{
    render_sub_texture(tex_id, left, right, bottom, top, FullTextureUVs);
}
References FullTextureUVs, and render_sub_texture().
reset()
void Slic3r::GUI::GLTexture::reset ()
{
    if (m_id != 0)
        glsafe(::glDeleteTextures(1, &m_id));
    m_id = 0;
    m_width = 0;
    m_height = 0;
    m_source = "";
    m_compressor.reset();
}
References glsafe, m_compressor, m_height, m_id, m_source, m_width, and Slic3r::GUI::GLTexture::Compressor::reset().
Referenced by ~GLTexture(), Slic3r::GUI::IconManager::init(), load_from_file(), load_from_png(), load_from_svg(), load_from_svg_file(), load_from_svg_files_as_sprites_array(), Slic3r::GUI::Bed3D::render_default(), Slic3r::GUI::Bed3D::render_texture(), Slic3r::GUI::GLTexture::Compressor::send_compressed_data_to_gpu(), and Slic3r::GUI::Bed3D::set_shape().
send_compressed_data_to_gpu()
void Slic3r::GUI::GLTexture::send_compressed_data_to_gpu () inline
{ m_compressor.send_compressed_data_to_gpu(); }
References m_compressor, and Slic3r::GUI::GLTexture::Compressor::send_compressed_data_to_gpu().
Referenced by Slic3r::GUI::Bed3D::render_texture().
unsent_compressed_data_available()
bool Slic3r::GUI::GLTexture::unsent_compressed_data_available () const inline
{ return m_compressor.unsent_compressed_data_available(); }
References m_compressor, and Slic3r::GUI::GLTexture::Compressor::unsent_compressed_data_available().
Referenced by Slic3r::GUI::Bed3D::render_texture().
Friends And Related Symbol Documentation
Compressor
friend class Compressor friend
Member Data Documentation
FullTextureUVs
GLTexture::Quad_UVs Slic3r::GUI::GLTexture::FullTextureUVs = { { 0.0f, 1.0f }, { 1.0f, 1.0f }, { 1.0f, 0.0f }, { 0.0f, 0.0f } } static
Referenced by render_texture().
m_compressor
Compressor Slic3r::GUI::GLTexture::m_compressor protected
Referenced by all_compressed_data_sent_to_gpu(), load_from_png(), load_from_svg(), reset(), send_compressed_data_to_gpu(), and unsent_compressed_data_available().
m_height
int Slic3r::GUI::GLTexture::m_height { 0 } protected
Referenced by get_height(), load_from_png(), load_from_svg(), load_from_svg_files_as_sprites_array(), and reset().
m_id
unsigned int Slic3r::GUI::GLTexture::m_id { 0 } protected
Referenced by get_id(), load_from_png(), load_from_svg(), load_from_svg_files_as_sprites_array(), and reset().
m_source
std::string Slic3r::GUI::GLTexture::m_source protected
Referenced by get_source(), load_from_png(), load_from_svg(), load_from_svg_files_as_sprites_array(), and reset().
m_width
int Slic3r::GUI::GLTexture::m_width { 0 } protected
Referenced by get_width(), load_from_png(), load_from_svg(), load_from_svg_files_as_sprites_array(), and reset().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLTexture.hpp
src/slic3r/GUI/GLTexture.cpp