Prusa Slicer: src/avrdude/term.h File Reference
term.h File Reference
#include "libavrdude.h"
Functions
int terminal_mode (PROGRAMMER *pgm, struct avrpart *p)
char * terminal_get_input (const char *prompt)
Function Documentation
terminal_get_input()
char * terminal_get_input (const char * prompt)
{
#if defined(HAVE_LIBREADLINE) && !defined(WIN32NATIVE)
  char *input;
  input = readline(prompt);
  if ((input != NULL) && (strlen(input) >= 1))
    add_history(input);
  return input;
#else
  char input[256];
  printf("%s", prompt);
  if (fgets(input, sizeof(input), stdin))
  {
    /* FIXME: readline strips the '\n', should this too? */
    return strdup(input);
  }
  else
    return NULL;
#endif
}
References input().
Referenced by avrdude_main(), and terminal_mode().
terminal_mode()
int terminal_mode (PROGRAMMER * pgm, struct avrpart * p)
{
  char  * cmdbuf;
  int     i;
  char  * q;
  int     rc;
  int     argc;
  char ** argv;
  rc = 0;
  while ((cmdbuf = terminal_get_input("avrdude> ")) != NULL) {
    /*
     * find the start of the command, skipping any white space
     */
    q = cmdbuf;
    while (*q && isspace((int)*q))
      q++;
    /* skip blank lines and comments */
    if (!*q || (*q == '#'))
      continue;
    /* tokenize command line */
    argc = tokenize(q, &argv);
    fprintf(stdout, ">>> ");
    for (i=0; i<argc; i++)
      fprintf(stdout, "%s ", argv[i]);
    fprintf(stdout, "\n");
    /* run the command */
    rc = do_cmd(pgm, p, argc, argv);
    free(argv);
    if (rc > 0) {
      rc = 0;
      break;
    }
    free(cmdbuf);
  }
  return rc;
}
References do_cmd(), free(), pgm, terminal_get_input(), and tokenize().
Referenced by avrdude_main().