Prusa Slicer: Slic3r::ClipperUtils::ExPolygonsProvider Struct Reference
Slic3r::ClipperUtils::ExPolygonsProvider Struct Reference
#include <src/libslic3r/ClipperUtils.hpp>
Classes
struct iterator
Public Member Functions
ExPolygonsProvider (const ExPolygons &expolygons)
iterator cbegin () const
iterator begin () const
iterator cend () const
iterator end () const
size_t size () const
Private Attributes
const ExPolygons & m_expolygons
size_t m_size
Detailed Description
Constructor & Destructor Documentation
ExPolygonsProvider()
Slic3r::ClipperUtils::ExPolygonsProvider::ExPolygonsProvider (const ExPolygons & expolygons) inline
                                                         : m_expolygons(expolygons) {
            m_size = 0;
            for (const ExPolygon &expoly : expolygons)
                m_size += expoly.holes.size() + 1;
        }
References m_size.
Member Function Documentation
begin()
iterator Slic3r::ClipperUtils::ExPolygonsProvider::begin () const inline
{ return this->cbegin(); }
References cbegin().
cbegin()
iterator Slic3r::ClipperUtils::ExPolygonsProvider::cbegin () const inline
{ return iterator(m_expolygons.cbegin()); }
References m_expolygons.
Referenced by begin().
cend()
iterator Slic3r::ClipperUtils::ExPolygonsProvider::cend () const inline
{ return iterator(m_expolygons.cend()); }
References m_expolygons.
Referenced by end().
end()
iterator Slic3r::ClipperUtils::ExPolygonsProvider::end () const inline
{ return this->cend(); }
References cend().
size()
size_t Slic3r::ClipperUtils::ExPolygonsProvider::size () const inline
{ return m_size; }
References m_size.
Member Data Documentation
m_expolygons
const ExPolygons& Slic3r::ClipperUtils::ExPolygonsProvider::m_expolygons private
Referenced by cbegin(), and cend().
m_size
size_t Slic3r::ClipperUtils::ExPolygonsProvider::m_size private
Referenced by ExPolygonsProvider(), and size().
The documentation for this struct was generated from the following file:
src/libslic3r/ClipperUtils.hpp