Prusa Slicer: Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator Class Reference
Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator Class Reference
#include <src/eigen/unsupported/Eigen/src/SparseExtra/BlockSparseMatrix.h>
Public Member Functions
BlockInnerIterator (const BlockSparseMatrix &mat, const Index outer)
BlockInnerIterator & operator++ ()
const Map< const BlockScalar > value () const
Map< BlockScalar > valueRef ()
Index index () const
Index outer () const
Index row () const
Index col () const
Index rows () const
Index cols () const
operator bool () const
Protected Attributes
const BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, StorageIndex > & m_mat
const Index m_outer
Index m_id
Index m_end
Detailed Description
template<typename _Scalar, int _BlockAtCompileTime, int _Options, typename _StorageIndex>
class Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator
Constructor & Destructor Documentation
BlockInnerIterator()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::BlockInnerIterator (const BlockSparseMatrix & mat, const Index outer) inline
    : m_mat(mat),m_outer(outer),
      m_id(mat.m_outerIndex[outer]),
      m_end(mat.m_outerIndex[outer+1])
    {
    }
Member Function Documentation
col()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Index Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::col () const inline
{return outer(); }
cols()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Index Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::cols () const inline
{ return (m_mat.m_blockSize==Dynamic) ? (m_mat.m_outerOffset[m_outer+1]-m_mat.m_outerOffset[m_outer]) : m_mat.m_blockSize;}
References Eigen::Dynamic.
index()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Index Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::index () const inline
{return m_mat.m_indices[m_id]; }
operator bool()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::operator bool () const inline
{ return (m_id < m_end); }
operator++()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > BlockInnerIterator & Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::operator++ () inline
{m_id++; return *this; }
outer()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Index Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::outer () const inline
{ return m_outer; }
row()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Index Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::row () const inline
{return index(); }
rows()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Index Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::rows () const inline
{ return (m_mat.m_blockSize==Dynamic) ? (m_mat.m_innerOffset[index()+1] - m_mat.m_innerOffset[index()]) : m_mat.m_blockSize; }
References Eigen::Dynamic.
value()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > const Map< const BlockScalar > Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::value () const inline
    {
      return Map<const BlockScalar>(&(m_mat.m_values[m_mat.blockPtr(m_id)]),
          rows(),cols());
    }
References Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::cols(), and Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::rows().
valueRef()
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Map< BlockScalar > Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::valueRef () inline
    {
      return Map<BlockScalar>(&(m_mat.m_values[m_mat.blockPtr(m_id)]),
          rows(),cols());
    }
References Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::cols(), and Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::rows().
Member Data Documentation
m_end
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Index Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::m_end protected
m_id
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > Index Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::m_id protected
m_mat
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > const BlockSparseMatrix<_Scalar, _BlockAtCompileTime, _Options, StorageIndex>& Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::m_mat protected
m_outer
template<typename _Scalar , int _BlockAtCompileTime, int _Options, typename _StorageIndex > const Index Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >::BlockInnerIterator::m_outer protected
The documentation for this class was generated from the following file:
src/eigen/unsupported/Eigen/src/SparseExtra/BlockSparseMatrix.h