Prusa Slicer: Slic3r::GUI::ObjectManipulation Class Reference
Slic3r::GUI::ObjectManipulation Class Reference
#include <src/slic3r/GUI/GUI_ObjectManipulation.hpp>
Classes
struct Cache
Public Member Functions
ObjectManipulation (wxWindow *parent)
~ObjectManipulation ()
void Show (const bool show) override
bool IsShown () override
void UpdateAndShow (const bool show) override
void Enable (const bool enadle=true)
void Disable ()
void DisableScale ()
void DisableUnuniformScale ()
void update_ui_from_settings ()
bool use_colors ()
void set_dirty ()
void update_if_dirty ()
void set_uniform_scaling (const bool use_uniform_scale)
bool get_uniform_scaling () const
void set_coordinates_type (ECoordinatesType type)
ECoordinatesType get_coordinates_type () const
bool is_world_coordinates () const
bool is_instance_coordinates () const
bool is_local_coordinates () const
void reset_cache ()
void emulate_kill_focus ()
void update_item_name (const wxString &item_name)
void update_warning_icon_state (const MeshErrorsInfo &warning)
void msw_rescale ()
void sys_color_changed ()
void on_change (const std::string &opt_key, int axis, double new_value)
void set_focused_editor (ManipulationEditor *focused_editor)
ManipulationEditor * get_focused_editor ()
bool is_enabled () const
bool is_enabled_size_and_scale () const
virtual void Hide ()
virtual wxSizer * get_sizer ()
ConfigOptionsGroup * get_og ()
const ConfigOptionsGroup * get_og () const
wxWindow * parent () const
Static Public Member Functions
static wxString coordinate_type_str (ECoordinatesType type)
Static Public Attributes
static const double in_to_mm = 25.4
static const double mm_to_in = 1 / ObjectManipulation::in_to_mm
Protected Attributes
std::shared_ptr< ConfigOptionsGroup > m_og
wxWindow * m_parent
Private Member Functions
void reset_settings_value ()
void update_settings_value (const Selection &selection)
void update_reset_buttons_visibility ()
void update_mirror_buttons_visibility ()
void change_position_value (int axis, double value)
void change_rotation_value (int axis, double value)
void change_scale_value (int axis, double value)
void change_size_value (int axis, double value)
void do_scale (int axis, const Vec3d &scale) const
void do_size (int axis, const Vec3d &scale) const
void set_coordinates_type (const wxString &type_string)
Private Attributes
Cache m_cache
wxStaticText * m_move_Label = nullptr
wxStaticText * m_scale_Label = nullptr
wxStaticText * m_rotate_Label = nullptr
bool m_imperial_units { false }
bool m_use_colors { false }
wxStaticText * m_position_unit { nullptr }
wxStaticText * m_size_unit { nullptr }
wxStaticText * m_item_name = nullptr
wxStaticText * m_empty_str = nullptr
ScalableButton * m_reset_scale_button { nullptr }
ScalableButton * m_reset_rotation_button { nullptr }
ScalableButton * m_reset_skew_button { nullptr }
ScalableButton * m_drop_to_bed_button { nullptr }
wxCheckBox * m_check_inch {nullptr}
std::array< ScalableButton *, 3 > m_mirror_buttons
ScalableBitmap m_mirror_bitmap_on
bool m_dirty = false
std::string m_new_move_label_string
std::string m_new_rotate_label_string
std::string m_new_scale_label_string
Vec3d m_new_position
Vec3d m_new_rotation
Vec3d m_new_scale
Vec3d m_new_size
bool m_new_enabled {true}
bool m_uniform_scale {true}
ECoordinatesType m_coordinates_type { ECoordinatesType::World }
LockButton * m_lock_bnt { nullptr }
choice_ctrl * m_word_local_combo { nullptr }
ScalableBitmap m_manifold_warning_bmp
wxStaticBitmap * m_fix_throught_netfab_bitmap { nullptr }
wxStaticBitmap * m_mirror_warning_bitmap { nullptr }
ManipulationEditor * m_focused_editor { nullptr }
wxFlexGridSizer * m_main_grid_sizer
wxFlexGridSizer * m_labels_grid_sizer
wxStaticText * m_skew_label { nullptr }
wxBoxSizer * m_word_local_combo_sizer
std::vector< wxBoxSizer * > m_rescalable_sizers
std::vector< ManipulationEditor * > m_editors
bool m_is_enabled { true }
bool m_is_enabled_size_and_scale { true }
Detailed Description
Constructor & Destructor Documentation
ObjectManipulation()
Slic3r::GUI::ObjectManipulation::ObjectManipulation (wxWindow * parent)
                                                       :
    OG_Settings(parent, true)
{
    m_imperial_units = wxGetApp().app_config->get_bool("use_inches");
    m_use_colors     = wxGetApp().app_config->get_bool("color_mapinulation_panel");
    m_manifold_warning_bmp = ScalableBitmap(parent, "exclamation");
    // Load bitmaps to be used for the mirroring buttons:
    m_mirror_bitmap_on     = ScalableBitmap(parent, "mirroring_on");
    const int border = wxOSX ? 0 : 4;
    const int em = wxGetApp().em_unit();
    m_main_grid_sizer = new wxFlexGridSizer(2, 3, 3); // "Name/label", "String name / Editors"
    m_main_grid_sizer->SetFlexibleDirection(wxBOTH);
    // Add "Name" label with warning icon
    auto sizer = new wxBoxSizer(wxHORIZONTAL);
    m_fix_throught_netfab_bitmap = new wxStaticBitmap(parent, wxID_ANY, wxNullBitmap);
    if (is_windows10())
        m_fix_throught_netfab_bitmap->Bind(wxEVT_CONTEXT_MENU, [this](wxCommandEvent& e)
            {
                // if object/sub-object has no errors
                if (m_fix_throught_netfab_bitmap->GetBitmap().GetRefData() == wxNullBitmap.GetRefData())
                    return;
                wxGetApp().obj_list()->fix_through_netfabb();
                update_warning_icon_state(wxGetApp().obj_list()->get_mesh_errors_info());
            });
    sizer->Add(m_fix_throught_netfab_bitmap);
    auto name_label = new wxStaticText(m_parent, wxID_ANY, _L("Name")+":");
    set_font_and_background_style(name_label, wxGetApp().normal_font());
    name_label->SetToolTip(_L("Object name"));
    sizer->Add(name_label);
    m_main_grid_sizer->Add(sizer);
    // Add name of the item
    const wxSize name_size = wxSize(20 * em, wxDefaultCoord);
    m_item_name = new wxStaticText(m_parent, wxID_ANY, "", wxDefaultPosition, name_size, wxST_ELLIPSIZE_MIDDLE);
    set_font_and_background_style(m_item_name, wxGetApp().bold_font());
    m_main_grid_sizer->Add(m_item_name, 0, wxEXPAND);
    // Add labels grid sizer
    m_labels_grid_sizer = new wxFlexGridSizer(1, 3, 3); // "Name/label", "String name / Editors"
    m_labels_grid_sizer->SetFlexibleDirection(wxBOTH);
    // Add world local combobox
    m_word_local_combo = create_word_local_combo(parent);
    m_word_local_combo->Bind(wxEVT_COMBOBOX, ([this](wxCommandEvent& evt) { this->set_coordinates_type(evt.GetString()); }), m_word_local_combo->GetId());
    // Small trick to correct layouting in different view_mode :
    // Show empty string of a same height as a m_word_local_combo, when m_word_local_combo is hidden
    m_word_local_combo_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_empty_str = new wxStaticText(parent, wxID_ANY, "");
    m_word_local_combo_sizer->Add(m_word_local_combo);
    m_word_local_combo_sizer->Add(m_empty_str);
    m_word_local_combo_sizer->SetMinSize(wxSize(-1, m_word_local_combo->GetBestHeight(-1)));
    m_labels_grid_sizer->Add(m_word_local_combo_sizer);
    // Text trick to grid sizer layout:
    // Height of labels should be equivalent to the edit boxes
    int height = wxTextCtrl(parent, wxID_ANY, "Br").GetBestHeight(-1);
#ifdef __WXGTK__
    // On Linux button with bitmap has bigger height then regular button or regular TextCtrl
    // It can cause a wrong alignment on show/hide of a reset buttons
    const int bmp_btn_height = ScalableButton(parent, wxID_ANY, "undo") .GetBestHeight(-1);
    if (bmp_btn_height > height)
        height = bmp_btn_height;
#endif //__WXGTK__
    auto add_label = [this, height](wxStaticText** label, const std::string& name, wxSizer* reciver = nullptr)
    {
        *label = new wxStaticText(m_parent, wxID_ANY, _(name) + ":");
        set_font_and_background_style(*label, wxGetApp().normal_font());
        wxBoxSizer* sizer = new wxBoxSizer(wxHORIZONTAL);
        sizer->SetMinSize(wxSize(-1, height));
        sizer->Add(*label, 0, wxALIGN_CENTER_VERTICAL);
        if (reciver)
            reciver->Add(sizer);
        else
            m_labels_grid_sizer->Add(sizer);
        m_rescalable_sizers.push_back(sizer);
    };
    // Add labels
    add_label(&m_move_Label,    L("Position"));
    add_label(&m_rotate_Label,  L("Rotation"));
    // additional sizer for lock and labels "Scale" & "Size"
    sizer = new wxBoxSizer(wxHORIZONTAL);
    m_lock_bnt = new LockButton(parent, wxID_ANY);
    m_lock_bnt->Bind(wxEVT_BUTTON, [this](wxCommandEvent& event) {
        event.Skip();
        wxTheApp->CallAfter([this]() { set_uniform_scaling(m_lock_bnt->IsLocked()); });
    });
    sizer->Add(m_lock_bnt, 0, wxALIGN_CENTER_VERTICAL);
    auto v_sizer = new wxGridSizer(1, 3, 3);
    add_label(&m_scale_Label,   L("Scale"), v_sizer);
    wxStaticText* size_Label {nullptr};
    add_label(&size_Label, L("Size [World]"), v_sizer);
    if (wxOSX) set_font_and_background_style(size_Label, wxGetApp().normal_font());
    sizer->Add(v_sizer, 0, wxLEFT, border);
    m_labels_grid_sizer->Add(sizer);
    m_main_grid_sizer->Add(m_labels_grid_sizer, 0, wxEXPAND);
    // Add editors grid sizer
    wxFlexGridSizer* editors_grid_sizer = new wxFlexGridSizer(5, 3, 3); // "Name/label", "String name / Editors"
    editors_grid_sizer->SetFlexibleDirection(wxBOTH);
    // Add Axes labels with icons
    static const char axes[] = { 'X', 'Y', 'Z' };
//    std::vector<wxString> axes_color = {"#EE0000", "#00EE00", "#0000EE"};
    for (size_t axis_idx = 0; axis_idx < sizeof(axes); axis_idx++) {
        const char label = axes[axis_idx];
        wxStaticText* axis_name = new wxStaticText(m_parent, wxID_ANY, wxString(label));
        set_font_and_background_style(axis_name, wxGetApp().bold_font());
        //if (m_use_colors)
        //    axis_name->SetForegroundColour(wxColour(axes_color_text[axis_idx]));
        sizer = new wxBoxSizer(wxHORIZONTAL);
        // Under OSX or Linux with GTK3 we use font, smaller than default font, so
        // there is a next trick for an equivalent layout of coordinates combobox and axes labels in they own sizers
        if (wxOSX || wxGTK3)
            sizer->SetMinSize(-1, m_word_local_combo->GetBestHeight(-1));
        sizer->Add(axis_name, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, border);
        // We will add a button to toggle mirroring to each axis:
        auto btn = new ScalableButton(parent, wxID_ANY, "mirroring_off", wxEmptyString, wxDefaultSize, wxDefaultPosition, wxBU_EXACTFIT | wxNO_BORDER | wxTRANSPARENT_WINDOW);
        btn->SetToolTip(format_wxstr(_L("Mirror along %1% axis"), label));
        m_mirror_buttons[axis_idx] = btn;
        sizer->AddStretchSpacer(2);
        sizer->Add(btn, 0, wxALIGN_CENTER_VERTICAL);
        btn->Bind(wxEVT_BUTTON, [this, axis_idx](wxCommandEvent&) {
            GLCanvas3D* canvas = wxGetApp().plater()->canvas3D();
            Selection& selection = canvas->get_selection();
            TransformationType transformation_type;
            if (is_local_coordinates())
                transformation_type.set_local();
            else if (is_instance_coordinates())
                transformation_type.set_instance();
            transformation_type.set_relative();
            selection.setup_cache();
            selection.mirror((Axis)axis_idx, transformation_type);
            // Copy mirroring values from GLVolumes into Model (ModelInstance / ModelVolume), trigger background processing.
            canvas->do_mirror(L("Set Mirror"));
            UpdateAndShow(true);
        });
        editors_grid_sizer->Add(sizer, 0, wxALIGN_CENTER_HORIZONTAL);
    }
    m_mirror_warning_bitmap = new wxStaticBitmap(parent, wxID_ANY, wxNullBitmap);
    editors_grid_sizer->Add(m_mirror_warning_bitmap, 0, wxALIGN_CENTER_VERTICAL);
    editors_grid_sizer->AddStretchSpacer(1);
    // add EditBoxes
    auto add_edit_boxes = [this, editors_grid_sizer](const std::string& opt_key, int axis)
    {
        ManipulationEditor* editor = new ManipulationEditor(this, opt_key, axis);
        m_editors.push_back(editor);
        editors_grid_sizer->Add(editor, 0, wxALIGN_CENTER_VERTICAL);
    };
    // add Units
    auto add_unit_text = [this, parent, editors_grid_sizer, height](std::string unit, wxStaticText** unit_text)
    {
        *unit_text = new wxStaticText(parent, wxID_ANY, _(unit));
        set_font_and_background_style(*unit_text, wxGetApp().normal_font());
        // Unit text should be the same height as labels
        wxBoxSizer* sizer = new wxBoxSizer(wxHORIZONTAL);
        sizer->SetMinSize(wxSize(-1, height));
        sizer->Add(*unit_text, 0, wxALIGN_CENTER_VERTICAL);
        editors_grid_sizer->Add(sizer);
        m_rescalable_sizers.push_back(sizer);
    };
    for (size_t axis_idx = 0; axis_idx < sizeof(axes); axis_idx++)
        add_edit_boxes("position", axis_idx);
    add_unit_text(m_imperial_units ? L("in") : L("mm"), &m_position_unit);
    // Add drop to bed button
    m_drop_to_bed_button = new ScalableButton(parent, wxID_ANY, ScalableBitmap(parent, "drop_to_bed"));
    m_drop_to_bed_button->SetToolTip(_L("Drop to bed"));
    m_drop_to_bed_button->Bind(wxEVT_BUTTON, [=](wxCommandEvent& e) {
        // ???
        GLCanvas3D* canvas = wxGetApp().plater()->canvas3D();
        Selection& selection = canvas->get_selection();
        if (selection.is_single_volume_or_modifier()) {
            const GLVolume* volume = selection.get_first_volume();
            const double min_z = get_volume_min_z(*volume);
            if (!is_world_coordinates()) {
                const Vec3d diff = m_cache.position - volume->get_instance_transformation().get_matrix_no_offset().inverse() * (min_z * Vec3d::UnitZ());
                Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Drop to bed"));
                change_position_value(0, diff.x());
                change_position_value(1, diff.y());
                change_position_value(2, diff.z());
            }
            else {
                Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Drop to bed"));
                change_position_value(2, m_cache.position.z() - min_z);
            }
        }
        else if (selection.is_single_full_instance()) {
            const double min_z = selection.get_scaled_instance_bounding_box().min.z();
            if (!is_world_coordinates()) {
                const GLVolume* volume = selection.get_first_volume();
                const Vec3d diff = m_cache.position - volume->get_instance_transformation().get_matrix_no_offset().inverse() * (min_z * Vec3d::UnitZ());
                Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Drop to bed"));
                change_position_value(0, diff.x());
                change_position_value(1, diff.y());
                change_position_value(2, diff.z());
            }
            else {
                Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Drop to bed"));
                change_position_value(2, m_cache.position.z() - min_z);
            }
        }
        });
    editors_grid_sizer->Add(m_drop_to_bed_button);
    for (size_t axis_idx = 0; axis_idx < sizeof(axes); axis_idx++)
        add_edit_boxes("rotation", axis_idx);
    wxStaticText* rotation_unit{ nullptr };
    add_unit_text("", &rotation_unit);
    // Add reset rotation button
    m_reset_rotation_button = new ScalableButton(parent, wxID_ANY, ScalableBitmap(parent, "undo"));
    m_reset_rotation_button->SetToolTip(_L("Reset rotation"));
    m_reset_rotation_button->Bind(wxEVT_BUTTON, [this](wxCommandEvent& e) {
        GLCanvas3D* canvas = wxGetApp().plater()->canvas3D();
        Selection& selection = canvas->get_selection();
        selection.setup_cache();
        if (selection.is_single_volume_or_modifier()) {
            GLVolume* vol = const_cast<GLVolume*>(selection.get_first_volume());
            Geometry::Transformation trafo = vol->get_volume_transformation();
            trafo.reset_rotation();
            vol->set_volume_transformation(trafo);
        }
        else if (selection.is_single_full_instance()) {
            Geometry::Transformation trafo = selection.get_first_volume()->get_instance_transformation();
            trafo.reset_rotation();
            for (unsigned int idx : selection.get_volume_idxs()) {
                const_cast<GLVolume*>(selection.get_volume(idx))->set_instance_transformation(trafo);
            }
        }
        else
            return;
        // Synchronize instances/volumes.
        selection.synchronize_unselected_instances(Selection::SyncRotationType::RESET);
        selection.synchronize_unselected_volumes();
        // Copy rotation values from GLVolumes into Model (ModelInstance / ModelVolume), trigger background processing.
        canvas->do_rotate(L("Reset Rotation"));
        UpdateAndShow(true);
    });
    editors_grid_sizer->Add(m_reset_rotation_button);
    for (size_t axis_idx = 0; axis_idx < sizeof(axes); axis_idx++)
        add_edit_boxes("scale", axis_idx);
    wxStaticText* scale_unit{ nullptr };
    add_unit_text("%", &scale_unit);
    // Add reset scale button
    m_reset_scale_button = new ScalableButton(parent, wxID_ANY, ScalableBitmap(parent, "undo"));
    m_reset_scale_button->SetToolTip(_L("Reset scale"));
    m_reset_scale_button->Bind(wxEVT_BUTTON, [this](wxCommandEvent& e) {
        GLCanvas3D* canvas = wxGetApp().plater()->canvas3D();
        Selection& selection = canvas->get_selection();
        selection.setup_cache();
        if (selection.is_single_volume_or_modifier()) {
            GLVolume* vol = const_cast<GLVolume*>(selection.get_first_volume());
            Geometry::Transformation trafo = vol->get_volume_transformation();
            trafo.reset_scaling_factor();
            vol->set_volume_transformation(trafo);
        }
        else if (selection.is_single_full_instance()) {
            Geometry::Transformation trafo = selection.get_first_volume()->get_instance_transformation();
            trafo.reset_scaling_factor();
            for (unsigned int idx : selection.get_volume_idxs()) {
                const_cast<GLVolume*>(selection.get_volume(idx))->set_instance_transformation(trafo);
            }
        }
        else
            return;
        // Synchronize instances/volumes.
        selection.synchronize_unselected_instances(Selection::SyncRotationType::GENERAL);
        selection.synchronize_unselected_volumes();
        canvas->do_scale(L("Reset scale"));
        UpdateAndShow(true);
        });
    editors_grid_sizer->Add(m_reset_scale_button);
    for (size_t axis_idx = 0; axis_idx < sizeof(axes); axis_idx++)
        add_edit_boxes("size", axis_idx);
    add_unit_text(m_imperial_units ? L("in") : L("mm"), &m_size_unit);
    editors_grid_sizer->AddStretchSpacer(1);
    m_main_grid_sizer->Add(editors_grid_sizer, 1, wxEXPAND);
    m_skew_label = new wxStaticText(parent, wxID_ANY, _L("Skew [World]"));
    m_main_grid_sizer->Add(m_skew_label, 1, wxEXPAND);
    m_reset_skew_button = new ScalableButton(parent, wxID_ANY, ScalableBitmap(parent, "undo"));
    m_reset_skew_button->SetToolTip(_L("Reset skew"));
    m_reset_skew_button->Bind(wxEVT_BUTTON, [this](wxCommandEvent& e) {
        GLCanvas3D* canvas = wxGetApp().plater()->canvas3D();
        Selection& selection = canvas->get_selection();
        if (selection.is_single_full_instance() || selection.is_single_volume_or_modifier()) {
            selection.setup_cache();
            selection.reset_skew();
            canvas->do_reset_skew(L("Reset skew"));
            UpdateAndShow(true);
        }
        });
    m_main_grid_sizer->Add(m_reset_skew_button);
    m_check_inch = new wxCheckBox(parent, wxID_ANY, _L("Inches"));
    m_check_inch->SetFont(wxGetApp().normal_font());
    m_check_inch->SetValue(m_imperial_units);
    m_check_inch->Bind(wxEVT_CHECKBOX, [this](wxCommandEvent&) {
        wxGetApp().app_config->set("use_inches", m_check_inch->GetValue() ? "1" : "0");
        wxGetApp().sidebar().update_ui_from_settings();
    });
    m_main_grid_sizer->Add(m_check_inch, 1, wxEXPAND);
    m_og->activate();
    m_og->sizer->Clear(true);
    m_og->sizer->Add(m_main_grid_sizer, 1, wxEXPAND | wxALL, border);
}
References _, _L, Slic3r::GUI::axes, change_position_value(), Slic3r::GUI::create_word_local_combo(), Slic3r::diff(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_reset_skew(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::Selection::GENERAL, Slic3r::GUI::Selection::get_first_volume(), Slic3r::GLVolume::get_instance_transformation(), Slic3r::GUI::Selection::get_scaled_instance_bounding_box(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::get_volume_min_z(), Slic3r::GLVolume::get_volume_transformation(), is_instance_coordinates(), is_local_coordinates(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_volume_or_modifier(), Slic3r::is_windows10(), is_world_coordinates(), LockButton::IsLocked(), L, m_cache, m_check_inch, m_drop_to_bed_button, m_editors, m_empty_str, m_fix_throught_netfab_bitmap, m_imperial_units, m_item_name, m_labels_grid_sizer, m_lock_bnt, m_main_grid_sizer, m_manifold_warning_bmp, m_mirror_bitmap_on, m_mirror_buttons, m_mirror_warning_bitmap, m_move_Label, Slic3r::GUI::OG_Settings::m_og, Slic3r::GUI::OG_Settings::m_parent, m_position_unit, m_rescalable_sizers, m_reset_rotation_button, m_reset_scale_button, m_reset_skew_button, m_rotate_Label, m_scale_Label, m_size_unit, m_skew_label, m_use_colors, m_word_local_combo, m_word_local_combo_sizer, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::GUI::Selection::mirror(), Slic3r::GUI::obj_list(), Slic3r::GUI::OG_Settings::parent(), Slic3r::GUI::plater(), Slic3r::GUI::ObjectManipulation::Cache::position, Slic3r::GUI::Selection::RESET, Slic3r::Geometry::Transformation::reset_rotation(), Slic3r::Geometry::Transformation::reset_scaling_factor(), Slic3r::GUI::Selection::reset_skew(), set_coordinates_type(), Slic3r::GUI::set_font_and_background_style(), Slic3r::GUI::TransformationType::set_instance(), Slic3r::GUI::TransformationType::set_local(), Slic3r::GUI::TransformationType::set_relative(), set_uniform_scaling(), Slic3r::GLVolume::set_volume_transformation(), Slic3r::GUI::Selection::setup_cache(), Slic3r::GUI::Selection::synchronize_unselected_instances(), Slic3r::GUI::Selection::synchronize_unselected_volumes(), update_warning_icon_state(), UpdateAndShow(), wxEVT_BUTTON, wxGTK3, and wxOSX.
~ObjectManipulation()
Slic3r::GUI::ObjectManipulation::~ObjectManipulation () inline
{}
Member Function Documentation
change_position_value()
void Slic3r::GUI::ObjectManipulation::change_position_value (int axis, double value) private
{
    if (std::abs(m_cache.position_rounded(axis) - value) < EPSILON)
        return;
    Vec3d position = m_cache.position;
    position(axis) = value;
    auto canvas = wxGetApp().plater()->canvas3D();
    Selection& selection = canvas->get_selection();
    selection.setup_cache();
    TransformationType trafo_type;
    trafo_type.set_relative();
    switch (get_coordinates_type())
    {
    case ECoordinatesType::Instance: { trafo_type.set_instance(); break; }
    case ECoordinatesType::Local:    { trafo_type.set_local(); break; }
    default:                         { break; }
    }
    selection.translate(position - m_cache.position, trafo_type);
    canvas->do_move(L("Set Position"));
    m_cache.position = position;
  m_cache.position_rounded(axis) = DBL_MAX;
    this->UpdateAndShow(true);
}
References EPSILON, get_coordinates_type(), Slic3r::GUI::Instance, L, Slic3r::GUI::Local, m_cache, Slic3r::GUI::ObjectManipulation::Cache::position, Slic3r::GUI::ObjectManipulation::Cache::position_rounded, Slic3r::GUI::TransformationType::set_instance(), Slic3r::GUI::TransformationType::set_local(), Slic3r::GUI::TransformationType::set_relative(), Slic3r::GUI::Selection::setup_cache(), Slic3r::GUI::Selection::translate(), and UpdateAndShow().
Referenced by ObjectManipulation(), and on_change().
change_rotation_value()
void Slic3r::GUI::ObjectManipulation::change_rotation_value (int axis, double value) private
{
    if (std::abs(m_cache.rotation_rounded(axis) - value) < EPSILON)
        return;
    Vec3d rotation = m_cache.rotation;
    rotation(axis) = value;
    GLCanvas3D* canvas = wxGetApp().plater()->canvas3D();
    Selection& selection = canvas->get_selection();
    TransformationType transformation_type;
    transformation_type.set_relative();
    if (selection.is_single_full_instance())
        transformation_type.set_independent();
    if (is_local_coordinates())
        transformation_type.set_local();
    if (is_instance_coordinates())
        transformation_type.set_instance();
    selection.setup_cache();
  selection.rotate(
    (M_PI / 180.0) * (transformation_type.absolute() ? rotation : rotation - m_cache.rotation),
    transformation_type);
    canvas->do_rotate(L("Set Orientation"));
    m_cache.rotation = rotation;
  m_cache.rotation_rounded(axis) = DBL_MAX;
    this->UpdateAndShow(true);
}
References Slic3r::GUI::TransformationType::absolute(), Slic3r::GUI::GLCanvas3D::do_rotate(), EPSILON, Slic3r::GUI::GLCanvas3D::get_selection(), is_instance_coordinates(), is_local_coordinates(), Slic3r::GUI::Selection::is_single_full_instance(), L, m_cache, M_PI, Slic3r::GUI::Selection::rotate(), Slic3r::GUI::ObjectManipulation::Cache::rotation, Slic3r::GUI::ObjectManipulation::Cache::rotation_rounded, Slic3r::GUI::TransformationType::set_independent(), Slic3r::GUI::TransformationType::set_instance(), Slic3r::GUI::TransformationType::set_local(), Slic3r::GUI::TransformationType::set_relative(), Slic3r::GUI::Selection::setup_cache(), and UpdateAndShow().
Referenced by on_change().
change_scale_value()
void Slic3r::GUI::ObjectManipulation::change_scale_value (int axis, double value) private
{
    if (value <= 0.0)
        return;
    if (std::abs(m_cache.scale_rounded(axis) - value) < EPSILON)
        return;
    Vec3d scale = m_cache.scale;
    scale(axis) = value;
    const Selection& selection = wxGetApp().plater()->canvas3D()->get_selection();
    Vec3d ref_scale = m_cache.scale;
    if (selection.is_single_volume_or_modifier()) {
        scale = scale.cwiseQuotient(ref_scale);
        ref_scale = Vec3d::Ones();
    }
    else if (selection.is_single_full_instance())
        ref_scale = 100.0 * Vec3d::Ones();
    this->do_scale(axis, scale.cwiseQuotient(ref_scale));
    m_cache.scale = scale;
    m_cache.scale_rounded(axis) = DBL_MAX;
    this->UpdateAndShow(true);
}
References do_scale(), EPSILON, Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_volume_or_modifier(), m_cache, Slic3r::GUI::ObjectManipulation::Cache::scale, scale(), Slic3r::GUI::ObjectManipulation::Cache::scale_rounded, and UpdateAndShow().
Referenced by on_change().
change_size_value()
void Slic3r::GUI::ObjectManipulation::change_size_value (int axis, double value) private
{
    if (value <= 0.0)
        return;
    if (m_imperial_units) {
        if (std::abs(m_cache.size_inches(axis) - value) < EPSILON)
            return;
        m_cache.size_inches(axis) = value;
        value *= in_to_mm;
    }
    if (std::abs(m_cache.size_rounded(axis) - value) < EPSILON)
        return;
    Vec3d size = m_cache.size;
    size(axis) = value;
    const Selection& selection = wxGetApp().plater()->canvas3D()->get_selection();
    Vec3d ref_size = m_cache.size;
    if (selection.is_single_volume_or_modifier()) {
        size = size.cwiseQuotient(ref_size);
        ref_size = Vec3d::Ones();
    }
    else if (selection.is_single_full_instance()) {
        if (is_world_coordinates())
            ref_size = selection.get_full_unscaled_instance_bounding_box().size();
        else
            ref_size = selection.get_full_unscaled_instance_local_bounding_box().size();
    }
    this->do_size(axis, size.cwiseQuotient(ref_size));
    m_cache.size = size;
    m_cache.size_rounded(axis) = DBL_MAX;
    this->UpdateAndShow(true);
}
References do_size(), EPSILON, Slic3r::GUI::Selection::get_full_unscaled_instance_bounding_box(), Slic3r::GUI::Selection::get_full_unscaled_instance_local_bounding_box(), in_to_mm, Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_volume_or_modifier(), is_world_coordinates(), m_cache, m_imperial_units, Slic3r::BoundingBox3Base< PointType >::size(), Slic3r::GUI::ObjectManipulation::Cache::size, Slic3r::GUI::ObjectManipulation::Cache::size_inches, Slic3r::GUI::ObjectManipulation::Cache::size_rounded, and UpdateAndShow().
Referenced by on_change().
coordinate_type_str()
wxString Slic3r::GUI::ObjectManipulation::coordinate_type_str (ECoordinatesType type) static
{
    switch (type)
    {
    case ECoordinatesType::World:    { return _L("World coordinates"); }
    case ECoordinatesType::Instance: { return _L("Object coordinates"); }
    case ECoordinatesType::Local:    { return _L("Part coordinates"); }
    default:                         { assert(false); return _L("Unknown"); }
    }
}
References _L, Slic3r::GUI::Instance, Slic3r::GUI::Local, and Slic3r::GUI::World.
Referenced by Slic3r::GUI::create_word_local_combo(), Slic3r::GUI::msw_rescale_word_local_combo(), set_coordinates_type(), and Show().
Disable()
void Slic3r::GUI::ObjectManipulation::Disable () inline
{ Enable(false); }
References Slic3r::Enable.
DisableScale()
void Slic3r::GUI::ObjectManipulation::DisableScale ()
{
    m_is_enabled = true;
    m_is_enabled_size_and_scale = false;
    for (wxWindow* win : std::initializer_list<wxWindow*>{ m_reset_scale_button, m_lock_bnt, m_reset_skew_button })
        win->Enable(false);
}
References m_is_enabled, m_is_enabled_size_and_scale, m_lock_bnt, m_reset_scale_button, and m_reset_skew_button.
DisableUnuniformScale()
void Slic3r::GUI::ObjectManipulation::DisableUnuniformScale ()
{
    m_lock_bnt->Enable(false);
}
References m_lock_bnt.
do_scale()
void Slic3r::GUI::ObjectManipulation::do_scale (int axis, const Vec3d & scale) const private
{
    TransformationType transformation_type;
    if (is_local_coordinates())
        transformation_type.set_local();
    else if (is_instance_coordinates())
        transformation_type.set_instance();
    Selection& selection = wxGetApp().plater()->canvas3D()->get_selection();
    if (selection.is_single_volume_or_modifier() && !is_local_coordinates())
        transformation_type.set_relative();
    const Vec3d scaling_factor = m_uniform_scale ? scale(axis) * Vec3d::Ones() : scale;
    selection.setup_cache();
    selection.scale(scaling_factor, transformation_type);
    wxGetApp().plater()->canvas3D()->do_scale(L("Set Scale"));
}
References is_instance_coordinates(), is_local_coordinates(), Slic3r::GUI::Selection::is_single_volume_or_modifier(), L, m_uniform_scale, scale(), Slic3r::GUI::Selection::scale(), Slic3r::GUI::TransformationType::set_instance(), Slic3r::GUI::TransformationType::set_local(), Slic3r::GUI::TransformationType::set_relative(), and Slic3r::GUI::Selection::setup_cache().
Referenced by change_scale_value().
do_size()
void Slic3r::GUI::ObjectManipulation::do_size (int axis, const Vec3d & scale) const private
{
    Selection& selection = wxGetApp().plater()->canvas3D()->get_selection();
    TransformationType transformation_type;
    if (is_local_coordinates())
        transformation_type.set_local();
    else if (is_instance_coordinates())
        transformation_type.set_instance();
    const Vec3d scaling_factor = m_uniform_scale ? scale(axis) * Vec3d::Ones() : scale;
    selection.setup_cache();
    selection.scale(scaling_factor, transformation_type);
    wxGetApp().plater()->canvas3D()->do_scale(L("Set Size"));
}
References is_instance_coordinates(), is_local_coordinates(), L, m_uniform_scale, scale(), Slic3r::GUI::Selection::scale(), Slic3r::GUI::TransformationType::set_instance(), Slic3r::GUI::TransformationType::set_local(), and Slic3r::GUI::Selection::setup_cache().
Referenced by change_size_value().
emulate_kill_focus()
void Slic3r::GUI::ObjectManipulation::emulate_kill_focus ()
{
    if (!m_focused_editor)
        return;
    m_focused_editor->kill_focus(this);
}
References Slic3r::GUI::ManipulationEditor::kill_focus(), and m_focused_editor.
Enable()
void Slic3r::GUI::ObjectManipulation::Enable (const bool enadle = true)
{
    m_is_enabled = m_is_enabled_size_and_scale = enable;
    for (wxWindow* win : std::initializer_list<wxWindow*>{ m_reset_scale_button, m_reset_rotation_button, m_drop_to_bed_button, m_check_inch, m_lock_bnt
      , m_reset_skew_button })
        win->Enable(enable);
}
References m_check_inch, m_drop_to_bed_button, m_is_enabled, m_is_enabled_size_and_scale, m_lock_bnt, m_reset_rotation_button, m_reset_scale_button, and m_reset_skew_button.
get_coordinates_type()
ECoordinatesType Slic3r::GUI::ObjectManipulation::get_coordinates_type () const
{
    return m_coordinates_type;
}
References m_coordinates_type.
Referenced by change_position_value().
get_focused_editor()
ManipulationEditor * Slic3r::GUI::ObjectManipulation::get_focused_editor () inline
{ return m_focused_editor; }
References m_focused_editor.
get_og() [1/2]
ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () inline inherited
{ return m_og.get(); }
References Slic3r::GUI::OG_Settings::m_og.
Referenced by msw_rescale(), and sys_color_changed().
get_og() [2/2]
const ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () const inline inherited
{ return m_og.get(); }
References Slic3r::GUI::OG_Settings::m_og.
get_sizer()
wxSizer * Slic3r::GUI::OG_Settings::get_sizer () virtual inherited
Reimplemented in Slic3r::GUI::FreqChangedParams.
{
    return m_og->sizer;
}
References Slic3r::GUI::OG_Settings::m_og.
get_uniform_scaling()
bool Slic3r::GUI::ObjectManipulation::get_uniform_scaling () const inline
{ return m_uniform_scale; }
References m_uniform_scale.
Hide()
void Slic3r::GUI::OG_Settings::Hide () virtual inherited
{
    Show(false);
}
References Slic3r::GUI::OG_Settings::Show().
is_enabled()
bool Slic3r::GUI::ObjectManipulation::is_enabled () const inline
{ return m_is_enabled; }
References m_is_enabled.
Referenced by Slic3r::GUI::ManipulationEditor::ManipulationEditor().
is_enabled_size_and_scale()
bool Slic3r::GUI::ObjectManipulation::is_enabled_size_and_scale () const inline
{ return m_is_enabled_size_and_scale; }
References m_is_enabled_size_and_scale.
Referenced by Slic3r::GUI::ManipulationEditor::ManipulationEditor().
is_instance_coordinates()
bool Slic3r::GUI::ObjectManipulation::is_instance_coordinates () const inline
{ return m_coordinates_type == ECoordinatesType::Instance; }
References Slic3r::GUI::Instance, and m_coordinates_type.
Referenced by ObjectManipulation(), change_rotation_value(), do_scale(), and do_size().
is_local_coordinates()
bool Slic3r::GUI::ObjectManipulation::is_local_coordinates () const inline
{ return m_coordinates_type == ECoordinatesType::Local; }
References Slic3r::GUI::Local, and m_coordinates_type.
Referenced by ObjectManipulation(), change_rotation_value(), do_scale(), do_size(), and update_settings_value().
is_world_coordinates()
bool Slic3r::GUI::ObjectManipulation::is_world_coordinates () const inline
{ return m_coordinates_type == ECoordinatesType::World; }
References m_coordinates_type, and Slic3r::GUI::World.
Referenced by ObjectManipulation(), change_size_value(), and update_settings_value().
IsShown()
bool Slic3r::GUI::ObjectManipulation::IsShown () override virtual
Reimplemented from Slic3r::GUI::OG_Settings.
{
  return dynamic_cast<const wxStaticBoxSizer*>(m_og->sizer)->GetStaticBox()->IsShown(); //  m_og->get_grid_sizer()->IsShown(2);
}
References Slic3r::GUI::OG_Settings::m_og.
Referenced by Show(), Slic3r::GUI::Plater::priv::update(), and update_reset_buttons_visibility().
msw_rescale()
void Slic3r::GUI::ObjectManipulation::msw_rescale ()
{
    const int em = wxGetApp().em_unit();
    m_item_name->SetMinSize(wxSize(20*em, wxDefaultCoord));
    msw_rescale_word_local_combo(m_word_local_combo);
    m_word_local_combo_sizer->SetMinSize(wxSize(-1, m_word_local_combo->GetBestHeight(-1)));
    const wxString& tooltip = m_fix_throught_netfab_bitmap->GetToolTipText();
    m_fix_throught_netfab_bitmap->SetBitmap(tooltip.IsEmpty() ? wxNullBitmap : m_manifold_warning_bmp.bmp());
    m_fix_throught_netfab_bitmap->SetMinSize(tooltip.IsEmpty() ? wxSize(0, 0) : m_manifold_warning_bmp.GetSize());
    // rescale label-heights
    // Text trick to grid sizer layout:
    // Height of labels should be equivalent to the edit boxes
    const int height = wxTextCtrl(parent(), wxID_ANY, "Br").GetBestHeight(-1);
    for (wxBoxSizer* sizer : m_rescalable_sizers)
        sizer->SetMinSize(wxSize(-1, height));
    // rescale edit-boxes
    for (ManipulationEditor* editor : m_editors)
        editor->msw_rescale();
    // rescale "inches" checkbox
    m_check_inch->SetInitialSize(m_check_inch->GetBestSize());
    get_og()->msw_rescale();
}
References ScalableBitmap::bmp(), Slic3r::GUI::OG_Settings::get_og(), ScalableBitmap::GetSize(), m_check_inch, m_editors, m_fix_throught_netfab_bitmap, m_item_name, m_manifold_warning_bmp, m_rescalable_sizers, m_word_local_combo, m_word_local_combo_sizer, Slic3r::GUI::ConfigOptionsGroup::msw_rescale(), Slic3r::GUI::msw_rescale_word_local_combo(), and Slic3r::GUI::OG_Settings::parent().
on_change()
void Slic3r::GUI::ObjectManipulation::on_change (const std::string & opt_key, int axis, double new_value)
{
    if (!m_cache.is_valid())
        return;
    if (opt_key == "position") {
        if (m_imperial_units)
            new_value *= in_to_mm;
        change_position_value(axis, new_value);
    }
    else if (opt_key == "rotation")
        change_rotation_value(axis, new_value);
    else if (opt_key == "scale") {
        if (new_value > 0.0)
            change_scale_value(axis, new_value);
        else {
            new_value = m_cache.scale(axis);
            m_cache.scale(axis) = 0.0;
            m_cache.scale_rounded(axis) = DBL_MAX;
            change_scale_value(axis, new_value);
        }
    }
    else if (opt_key == "size") {
        if (new_value > 0.0)
            change_size_value(axis, new_value);
        else {
            Vec3d& size = m_imperial_units ? m_cache.size_inches : m_cache.size;
            new_value = size(axis);
            size(axis) = 0.0;
            m_cache.size_rounded(axis) = DBL_MAX;
            change_size_value(axis, new_value);
        }
    }
}
References change_position_value(), change_rotation_value(), change_scale_value(), change_size_value(), in_to_mm, Slic3r::GUI::ObjectManipulation::Cache::is_valid(), m_cache, m_imperial_units, Slic3r::GUI::ObjectManipulation::Cache::scale, Slic3r::GUI::ObjectManipulation::Cache::scale_rounded, Slic3r::GUI::ObjectManipulation::Cache::size, Slic3r::GUI::ObjectManipulation::Cache::size_inches, and Slic3r::GUI::ObjectManipulation::Cache::size_rounded.
Referenced by Slic3r::GUI::ManipulationEditor::ManipulationEditor(), and Slic3r::GUI::ManipulationEditor::kill_focus().
parent()
wxWindow * Slic3r::GUI::OG_Settings::parent () const inline inherited
{return m_parent; }
References Slic3r::GUI::OG_Settings::m_parent.
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), Slic3r::GUI::ObjectLayers::ObjectLayers(), ObjectManipulation(), Slic3r::GUI::ObjectSettings::ObjectSettings(), Slic3r::GUI::OG_Settings::OG_Settings(), msw_rescale(), and Slic3r::GUI::ObjectSettings::update_settings_list().
reset_cache()
void Slic3r::GUI::ObjectManipulation::reset_cache () inline
{ m_cache.reset(); }
References m_cache, and Slic3r::GUI::ObjectManipulation::Cache::reset().
reset_settings_value()
void Slic3r::GUI::ObjectManipulation::reset_settings_value () private
{
    m_new_position = Vec3d::Zero();
    m_new_rotation = Vec3d::Zero();
    m_new_scale = Vec3d::Ones() * 100.;
    m_new_size = Vec3d::Zero();
    m_new_enabled = false;
    // no need to set the dirty flag here as this method is called from update_settings_value(),
    // which is called from update_if_dirty(), which resets the dirty flag anyways.
//    m_dirty = true;
}
References m_new_enabled, m_new_position, m_new_rotation, m_new_scale, and m_new_size.
Referenced by update_settings_value().
set_coordinates_type() [1/2]
void Slic3r::GUI::ObjectManipulation::set_coordinates_type (const wxString & type_string) private
{
  if (type_string == coordinate_type_str(ECoordinatesType::Instance))
      this->set_coordinates_type(ECoordinatesType::Instance);
  else if (type_string == coordinate_type_str(ECoordinatesType::Local))
      this->set_coordinates_type(ECoordinatesType::Local);
  else
      this->set_coordinates_type(ECoordinatesType::World);
}
References coordinate_type_str(), Slic3r::GUI::Instance, Slic3r::GUI::Local, set_coordinates_type(), and Slic3r::GUI::World.
set_coordinates_type() [2/2]
void Slic3r::GUI::ObjectManipulation::set_coordinates_type (ECoordinatesType type)
{
    if (wxGetApp().get_mode() == comSimple)
        type = ECoordinatesType::World;
    if (m_coordinates_type == type)
        return;
    m_coordinates_type = type;
    m_word_local_combo->SetSelection((int)m_coordinates_type);
    this->UpdateAndShow(true);
    GLCanvas3D* canvas = wxGetApp().plater()->canvas3D();
    canvas->get_gizmos_manager().update_data();
    canvas->set_as_dirty();
    canvas->request_extra_frame();
}
References Slic3r::comSimple, Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), m_coordinates_type, m_word_local_combo, Slic3r::GUI::GLCanvas3D::request_extra_frame(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::GLGizmosManager::update_data(), UpdateAndShow(), and Slic3r::GUI::World.
Referenced by ObjectManipulation(), and set_coordinates_type().
set_dirty()
void Slic3r::GUI::ObjectManipulation::set_dirty () inline
{ m_dirty = true; }
References m_dirty.
Referenced by set_uniform_scaling(), and UpdateAndShow().
set_focused_editor()
void Slic3r::GUI::ObjectManipulation::set_focused_editor (ManipulationEditor * focused_editor) inline
{
        m_focused_editor = focused_editor;
    }
References m_focused_editor.
Referenced by Slic3r::GUI::ManipulationEditor::ManipulationEditor().
set_uniform_scaling()
void Slic3r::GUI::ObjectManipulation::set_uniform_scaling (const bool use_uniform_scale)
{
    if (!use_uniform_scale)
        // Recalculate cached values at this panel, refresh the screen.
        this->UpdateAndShow(true);
    m_uniform_scale = use_uniform_scale;
    set_dirty();
}
References m_uniform_scale, set_dirty(), and UpdateAndShow().
Referenced by ObjectManipulation().
Show()
void Slic3r::GUI::ObjectManipulation::Show (const bool show) override virtual
Reimplemented from Slic3r::GUI::OG_Settings.
{
    if (show != IsShown()) {
        // Show all lines of the panel. Some of these lines will be hidden in the lines below.
        m_og->Show(show);
        if (show && wxGetApp().get_mode() != comSimple) {
            // Show the label and the name of the STL in simple mode only.
            // Label "Name: "
            m_main_grid_sizer->Show(size_t(0), false);
            // The actual name of the STL.
            m_main_grid_sizer->Show(size_t(1), false);
        }
    }
    if (show) {
        ECoordinatesType coordinates_type = m_coordinates_type;
        // Show the "World Coordinates" / "Local Coordintes" Combo in Advanced / Expert mode only.
        const Selection& selection = wxGetApp().plater()->canvas3D()->get_selection();
        bool show_world_local_combo = wxGetApp().get_mode() != comSimple && (selection.is_single_full_instance() || selection.is_single_volume_or_modifier());
        if (selection.is_single_volume_or_modifier() && m_word_local_combo->GetCount() < 3) {
#ifdef __linux__
            m_word_local_combo->Insert(coordinate_type_str(ECoordinatesType::Local), 2);
#else
            m_word_local_combo->Insert(coordinate_type_str(ECoordinatesType::Local), wxNullBitmap, 2);
#endif // __linux__
        }
        else if (selection.is_single_full_instance() && m_word_local_combo->GetCount() > 2) {
            m_word_local_combo->Delete(2);
            if (coordinates_type > ECoordinatesType::Instance)
                coordinates_type = ECoordinatesType::World;
        }
        m_word_local_combo->Show(show_world_local_combo);
        m_empty_str->Show(!show_world_local_combo);
    }
}
References Slic3r::comSimple, coordinate_type_str(), Slic3r::GUI::Selection::get_mode(), Slic3r::GUI::Instance, Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_volume_or_modifier(), IsShown(), Slic3r::GUI::Local, m_coordinates_type, m_empty_str, m_main_grid_sizer, Slic3r::GUI::OG_Settings::m_og, m_word_local_combo, and Slic3r::GUI::World.
sys_color_changed()
void Slic3r::GUI::ObjectManipulation::sys_color_changed ()
{
#ifdef _WIN32
    get_og()->sys_color_changed();
    wxGetApp().UpdateDarkUI(m_word_local_combo);
    wxGetApp().UpdateDarkUI(m_check_inch);
#endif
    for (ManipulationEditor* editor : m_editors)
        editor->sys_color_changed(this);
    m_mirror_bitmap_on.sys_color_changed();
    m_reset_scale_button->sys_color_changed();
    m_reset_rotation_button->sys_color_changed();
    m_drop_to_bed_button->sys_color_changed();
    m_lock_bnt->sys_color_changed();
    for (int id = 0; id < 3; ++id) {
        m_mirror_buttons[id]->sys_color_changed();
    }
}
References Slic3r::GUI::OG_Settings::get_og(), m_check_inch, m_drop_to_bed_button, m_editors, m_lock_bnt, m_mirror_bitmap_on, m_mirror_buttons, m_reset_rotation_button, m_reset_scale_button, m_word_local_combo, Slic3r::GUI::ConfigOptionsGroup::sys_color_changed(), ScalableBitmap::sys_color_changed(), LockButton::sys_color_changed(), and ScalableButton::sys_color_changed().
update_if_dirty()
void Slic3r::GUI::ObjectManipulation::update_if_dirty ()
{
    if (! m_dirty)
        return;
    const Selection &selection = wxGetApp().plater()->canvas3D()->get_selection();
    this->update_settings_value(selection);
    auto update_label = [](wxString &label_cache, const std::string &new_label, wxStaticText *widget) {
        wxString new_label_localized = _(new_label) + ":";
        if (label_cache != new_label_localized) {
            label_cache = new_label_localized;
            widget->SetLabel(new_label_localized);
            if (wxOSX) set_font_and_background_style(widget, wxGetApp().normal_font());
        }
    };
    update_label(m_cache.move_label_string,   m_new_move_label_string,   m_move_Label);
    update_label(m_cache.rotate_label_string, m_new_rotate_label_string, m_rotate_Label);
    update_label(m_cache.scale_label_string,  m_new_scale_label_string,  m_scale_Label);
    enum ManipulationEditorKey
    {
        mePosition = 0,
        meRotation,
        meScale,
        meSize
    };
    for (int i = 0; i < 3; ++ i) {
        auto update = [this, i](Vec3d &cached, Vec3d &cached_rounded, ManipulationEditorKey key_id, const Vec3d &new_value) {
      wxString new_text = double_to_string(new_value(i), m_imperial_units && key_id == meSize ? 4 : 2);
      double new_rounded;
      new_text.ToDouble(&new_rounded);
      if (std::abs(cached_rounded(i) - new_rounded) > EPSILON) {
        cached_rounded(i) = new_rounded;
                const int id = key_id*3+i;
                if (m_imperial_units) {
                    double inch_value = new_value(i) * mm_to_in;
                    if (key_id == mePosition)
                        new_text = double_to_string(inch_value, 2);
                    if (key_id == meSize) {
                        if(std::abs(m_cache.size_inches(i) - inch_value) > EPSILON)
                            m_cache.size_inches(i) = inch_value;
                        new_text = double_to_string(inch_value, 4);
                    }
                }
                if (id >= 0) m_editors[id]->set_value(new_text);
            }
      cached(i) = new_value(i);
    };
        update(m_cache.position, m_cache.position_rounded, mePosition, m_new_position);
        update(m_cache.scale,    m_cache.scale_rounded,    meScale,    m_new_scale);
        update(m_cache.size,     m_cache.size_rounded,     meSize,     m_new_size);
        update(m_cache.rotation, m_cache.rotation_rounded, meRotation, m_new_rotation);
    }
    m_lock_bnt->SetLock(m_uniform_scale);
    m_lock_bnt->SetToolTip(wxEmptyString);
    m_lock_bnt->enable();
    if (m_new_enabled)
        m_og->enable();
    else
        m_og->disable();
    if (!wxGetApp().plater()->canvas3D()->is_dragging()) {
        update_reset_buttons_visibility();
        update_mirror_buttons_visibility();
    }
    m_dirty = false;
}
References _, Slic3r::GUI::double_to_string(), LockButton::enable(), EPSILON, m_cache, m_dirty, m_editors, m_imperial_units, m_lock_bnt, m_move_Label, m_new_enabled, m_new_move_label_string, m_new_position, m_new_rotate_label_string, m_new_rotation, m_new_scale, m_new_scale_label_string, m_new_size, Slic3r::GUI::OG_Settings::m_og, m_rotate_Label, m_scale_Label, m_uniform_scale, mm_to_in, Slic3r::GUI::ObjectManipulation::Cache::move_label_string, Slic3r::GUI::plater(), Slic3r::GUI::ObjectManipulation::Cache::position, Slic3r::GUI::ObjectManipulation::Cache::position_rounded, Slic3r::GUI::ObjectManipulation::Cache::rotate_label_string, Slic3r::GUI::ObjectManipulation::Cache::rotation, Slic3r::GUI::ObjectManipulation::Cache::rotation_rounded, Slic3r::GUI::ObjectManipulation::Cache::scale, Slic3r::GUI::ObjectManipulation::Cache::scale_label_string, Slic3r::GUI::ObjectManipulation::Cache::scale_rounded, Slic3r::GUI::set_font_and_background_style(), LockButton::SetLock(), Slic3r::GUI::ObjectManipulation::Cache::size, Slic3r::GUI::ObjectManipulation::Cache::size_inches, Slic3r::GUI::ObjectManipulation::Cache::size_rounded, update_mirror_buttons_visibility(), update_reset_buttons_visibility(), update_settings_value(), and wxOSX.
Referenced by UpdateAndShow().
update_item_name()
void Slic3r::GUI::ObjectManipulation::update_item_name (const wxString & item_name)
{
    m_item_name->SetLabel(item_name);
}
References m_item_name.
update_mirror_buttons_visibility()
void Slic3r::GUI::ObjectManipulation::update_mirror_buttons_visibility () private
{
    const bool can_mirror = wxGetApp().plater()->can_mirror();
    for (ScalableButton* button : m_mirror_buttons) {
        button->Enable(can_mirror);
    }
}
References Slic3r::GUI::button(), and m_mirror_buttons.
Referenced by update_if_dirty().
update_reset_buttons_visibility()
void Slic3r::GUI::ObjectManipulation::update_reset_buttons_visibility () private
{
    GLCanvas3D* canvas = wxGetApp().plater()->canvas3D();
    if (!canvas)
        return;
    bool show_drop_to_bed = false;
    bool show_rotation = false;
    bool show_scale = false;
    bool show_mirror = false;
    bool show_skew = false;
    const Selection& selection = canvas->get_selection();
    if (selection.is_single_full_instance() || selection.is_single_volume_or_modifier()) {
        const double min_z = selection.is_single_full_instance() ? selection.get_scaled_instance_bounding_box().min.z() :
            get_volume_min_z(*selection.get_first_volume());
        show_drop_to_bed = std::abs(min_z) > EPSILON;
        const GLVolume* volume = selection.get_first_volume();
        const Geometry::Transformation trafo = selection.is_single_full_instance() ? volume->get_instance_transformation() : volume->get_volume_transformation();
        const Geometry::TransformationSVD trafo_svd(trafo);
        show_rotation = trafo_svd.rotation;
        show_scale    = trafo_svd.scale;
        show_mirror   = trafo_svd.mirror;
        show_skew     = Geometry::TransformationSVD(volume->world_matrix()).skew;
    }
    wxGetApp().CallAfter([this, show_drop_to_bed, show_rotation, show_scale, show_mirror, show_skew] {
        // There is a case (under OSX), when this function is called after the Manipulation panel is hidden
        // So, let check if Manipulation panel is still shown for this moment
        if (!this->IsShown())
            return;
        m_drop_to_bed_button->Show(show_drop_to_bed);
        m_reset_rotation_button->Show(show_rotation);
        m_reset_scale_button->Show(show_scale);
        m_mirror_warning_bitmap->SetBitmap(show_mirror ? m_manifold_warning_bmp.bmp() : wxNullBitmap);
        m_mirror_warning_bitmap->SetMinSize(show_mirror ? m_manifold_warning_bmp.GetSize() : wxSize(0, 0));
        m_mirror_warning_bitmap->SetToolTip(show_mirror ? _L("Left handed") : "");
        m_reset_skew_button->Show(show_skew);
        m_skew_label->Show(show_skew);
        // Because of CallAfter we need to layout sidebar after Show/hide of reset buttons one more time
        Sidebar& panel = wxGetApp().sidebar();
        if (!panel.IsFrozen()) {
            panel.Freeze();
            panel.Layout();
            panel.Thaw();
        }
    });
}
References _L, ScalableBitmap::bmp(), EPSILON, Slic3r::GUI::Selection::get_first_volume(), Slic3r::GUI::Selection::get_scaled_instance_bounding_box(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::get_volume_min_z(), ScalableBitmap::GetSize(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_volume_or_modifier(), IsShown(), m_drop_to_bed_button, m_manifold_warning_bmp, m_mirror_warning_bitmap, m_reset_rotation_button, m_reset_scale_button, m_reset_skew_button, m_skew_label, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::Geometry::TransformationSVD::mirror, Slic3r::Geometry::TransformationSVD::rotation, Slic3r::Geometry::TransformationSVD::scale, and Slic3r::Geometry::TransformationSVD::skew.
Referenced by update_if_dirty().
update_settings_value()
void Slic3r::GUI::ObjectManipulation::update_settings_value (const Selection & selection) private
{
    if (selection.is_empty()) {
        // No selection, reset the cache.
        reset_settings_value();
        return;
    }
    m_new_move_label_string   = L("Position");
    m_new_rotate_label_string = L("Rotation");
    m_new_scale_label_string  = L("Scale factors");
    ObjectList* obj_list = wxGetApp().obj_list();
    if (selection.is_single_full_instance()) {
        // all volumes in the selection belongs to the same instance, any of them contains the needed instance data, so we take the first one
        const GLVolume* volume = selection.get_first_volume();
        if (is_world_coordinates()) {
            m_new_position = volume->get_instance_offset();
            m_new_size = selection.get_bounding_box_in_current_reference_system().first.size();
            m_new_scale = m_new_size.cwiseQuotient(selection.get_unscaled_instance_bounding_box().size()) * 100.0;
            m_new_rotate_label_string = L("Rotate (relative)");
            m_new_rotation = Vec3d::Zero();
        }
        else {
            m_new_move_label_string = L("Translate (relative) [World]");
            m_new_rotate_label_string = L("Rotate (relative)");
            m_new_position = Vec3d::Zero();
            m_new_rotation = Vec3d::Zero();
            m_new_size = selection.get_bounding_box_in_current_reference_system().first.size();
            m_new_scale = m_new_size.cwiseQuotient(selection.get_full_unscaled_instance_local_bounding_box().size()) * 100.0;
        }
        m_new_enabled  = true;
    }
    else if (selection.is_single_full_object() && obj_list->is_selected(itObject)) {
        const BoundingBoxf3& box = selection.get_bounding_box();
        m_new_position = box.center();
        m_new_rotation = Vec3d::Zero();
        m_new_scale    = Vec3d(100.0, 100.0, 100.0);
        m_new_size = selection.get_bounding_box_in_current_reference_system().first.size();
        m_new_rotate_label_string = L("Rotate");
        m_new_scale_label_string  = L("Scale");
        m_new_enabled  = true;
    }
    else if (selection.is_single_volume_or_modifier()) {
        // the selection contains a single volume
        const GLVolume* volume = selection.get_first_volume();
        if (is_world_coordinates()) {
            const Geometry::Transformation trafo(volume->world_matrix());
            const Vec3d& offset = trafo.get_offset();
            m_new_position = offset;
            m_new_rotate_label_string = L("Rotate (relative)");
            m_new_scale_label_string = L("Scale");
            m_new_scale = Vec3d(100.0, 100.0, 100.0);
            m_new_rotation = Vec3d::Zero();
            m_new_size = selection.get_bounding_box_in_current_reference_system().first.size();
        }
        else if (is_local_coordinates()) {
            m_new_move_label_string = L("Translate (relative) [World]");
            m_new_rotate_label_string = L("Rotate (relative)");
            m_new_position = Vec3d::Zero();
            m_new_rotation = Vec3d::Zero();
            m_new_scale = volume->get_volume_scaling_factor() * 100.0;
            m_new_size = selection.get_bounding_box_in_current_reference_system().first.size();
        }
        else {
            m_new_position = volume->get_volume_offset();
            m_new_rotate_label_string = L("Rotate (relative)");
            m_new_rotation = Vec3d::Zero();
            m_new_scale_label_string = L("Scale");
            m_new_scale = Vec3d(100.0, 100.0, 100.0);
            m_new_size = selection.get_bounding_box_in_current_reference_system().first.size();
        }
        m_new_enabled = true;
    }
    else if (obj_list->is_connectors_item_selected() || obj_list->multiple_selection() || obj_list->is_selected(itInstanceRoot)) {
        reset_settings_value();
        m_new_move_label_string   = L("Translate");
        m_new_rotate_label_string = L("Rotate");
        m_new_scale_label_string  = L("Scale");
        m_new_size = selection.get_bounding_box_in_current_reference_system().first.size();
        m_new_enabled  = true;
    }
}
References Slic3r::BoundingBox3Base< PointType >::center(), Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::Selection::get_bounding_box_in_current_reference_system(), Slic3r::GUI::Selection::get_first_volume(), Slic3r::GUI::Selection::get_full_unscaled_instance_local_bounding_box(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::GUI::Selection::get_unscaled_instance_bounding_box(), Slic3r::GUI::ObjectList::is_connectors_item_selected(), Slic3r::GUI::Selection::is_empty(), is_local_coordinates(), Slic3r::GUI::ObjectList::is_selected(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_volume_or_modifier(), is_world_coordinates(), Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itObject, L, m_new_enabled, m_new_move_label_string, m_new_position, m_new_rotate_label_string, m_new_rotation, m_new_scale, m_new_scale_label_string, m_new_size, Slic3r::GUI::ObjectList::multiple_selection(), Slic3r::GUI::obj_list(), Slic3r::offset(), reset_settings_value(), and Slic3r::BoundingBox3Base< PointType >::size().
Referenced by update_if_dirty().
update_ui_from_settings()
void Slic3r::GUI::ObjectManipulation::update_ui_from_settings ()
{
    if (m_imperial_units != wxGetApp().app_config->get_bool("use_inches")) {
        m_imperial_units  = wxGetApp().app_config->get_bool("use_inches");
        auto update_unit_text = [](const wxString& new_unit_text, wxStaticText* widget) {
            widget->SetLabel(new_unit_text);
            if (wxOSX) set_font_and_background_style(widget, wxGetApp().normal_font());
        };
        update_unit_text(m_imperial_units ? _L("in") : _L("mm"), m_position_unit);
        update_unit_text(m_imperial_units ? _L("in") : _L("mm"), m_size_unit);
        for (int i = 0; i < 3; ++i) {
            auto update = [this, i](/*ManipulationEditorKey*/int key_id, const Vec3d& new_value) {
                double value = new_value(i);
                if (m_imperial_units)
                    value *= mm_to_in;
                wxString new_text = double_to_string(value, m_imperial_units && key_id == 3/*meSize*/ ? 4 : 2);
                const int id = key_id * 3 + i;
                if (id >= 0) m_editors[id]->set_value(new_text);
            };
            update(0/*mePosition*/, m_new_position);
            update(3/*meSize*/,     m_new_size);
        }
    }
    m_check_inch->SetValue(m_imperial_units);
    if (m_use_colors != wxGetApp().app_config->get_bool("color_mapinulation_panel")) {
        m_use_colors  = wxGetApp().app_config->get_bool("color_mapinulation_panel");
        // update colors for edit-boxes
        int axis_id = 0;
        for (ManipulationEditor* editor : m_editors) {
//            editor->SetForegroundColour(m_use_colors ? wxColour(axes_color_text[axis_id]) : wxGetApp().get_label_clr_default());
            if (m_use_colors) {
                editor->SetBackgroundColour(wxColour(axes_color_back[axis_id]));
                if (wxGetApp().dark_mode())
                    editor->SetForegroundColour(*wxBLACK);
            }
            else {
#ifdef _WIN32
                wxGetApp().UpdateDarkUI(editor);
#else
                editor->SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW));
                editor->SetForegroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOWTEXT));
#endif /* _WIN32 */
            }
            editor->Refresh();
            if (++axis_id == 3)
                axis_id = 0;
        }
    }
}
References _L, Slic3r::GUI::axes_color_back, Slic3r::GUI::double_to_string(), m_check_inch, m_editors, m_imperial_units, m_new_position, m_new_size, m_position_unit, m_size_unit, m_use_colors, mm_to_in, Slic3r::GUI::set_font_and_background_style(), and wxOSX.
Referenced by Slic3r::GUI::ConfigWizard::run().
update_warning_icon_state()
void Slic3r::GUI::ObjectManipulation::update_warning_icon_state (const MeshErrorsInfo & warning)
{
    if (const std::string& warning_icon_name = warning.warning_icon_name;
        !warning_icon_name.empty())
        m_manifold_warning_bmp = ScalableBitmap(m_parent, warning_icon_name);
    const wxString& tooltip = warning.tooltip;
    m_fix_throught_netfab_bitmap->SetBitmap(tooltip.IsEmpty() ? wxNullBitmap : m_manifold_warning_bmp.bmp());
    m_fix_throught_netfab_bitmap->SetMinSize(tooltip.IsEmpty() ? wxSize(0,0) : m_manifold_warning_bmp.GetSize());
    m_fix_throught_netfab_bitmap->SetToolTip(tooltip);
}
References ScalableBitmap::bmp(), ScalableBitmap::GetSize(), m_fix_throught_netfab_bitmap, m_manifold_warning_bmp, Slic3r::GUI::OG_Settings::m_parent, Slic3r::GUI::MeshErrorsInfo::tooltip, and Slic3r::GUI::MeshErrorsInfo::warning_icon_name.
Referenced by ObjectManipulation().
UpdateAndShow()
void Slic3r::GUI::ObjectManipulation::UpdateAndShow (const bool show) override virtual
Reimplemented from Slic3r::GUI::OG_Settings.
{
  if (show) {
        this->set_dirty();
    this->update_if_dirty();
  }
    OG_Settings::UpdateAndShow(show);
}
References set_dirty(), update_if_dirty(), and Slic3r::GUI::OG_Settings::UpdateAndShow().
Referenced by ObjectManipulation(), change_position_value(), change_rotation_value(), change_scale_value(), change_size_value(), set_coordinates_type(), set_uniform_scaling(), and Slic3r::GUI::Plater::priv::update().
use_colors()
bool Slic3r::GUI::ObjectManipulation::use_colors () inline
{ return m_use_colors; }
References m_use_colors.
Referenced by Slic3r::GUI::ManipulationEditor::ManipulationEditor(), and Slic3r::GUI::ManipulationEditor::sys_color_changed().
Member Data Documentation
in_to_mm
const double Slic3r::GUI::ObjectManipulation::in_to_mm = 25.4 static
Referenced by change_size_value(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::Emboss::StyleManager::init_style_images(), on_change(), Slic3r::GUI::GLGizmoCut3D::render_double_input(), Slic3r::GUI::GCodeViewer::render_legend(), Slic3r::GUI::GLGizmoCut3D::render_move_center_input(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoEmboss::rev_input_mm(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
m_cache
Cache Slic3r::GUI::ObjectManipulation::m_cache private
Referenced by ObjectManipulation(), change_position_value(), change_rotation_value(), change_scale_value(), change_size_value(), on_change(), reset_cache(), and update_if_dirty().
m_check_inch
wxCheckBox* Slic3r::GUI::ObjectManipulation::m_check_inch {nullptr} private
Referenced by ObjectManipulation(), Enable(), msw_rescale(), sys_color_changed(), and update_ui_from_settings().
m_coordinates_type
ECoordinatesType Slic3r::GUI::ObjectManipulation::m_coordinates_type { ECoordinatesType::World } private
Referenced by get_coordinates_type(), is_instance_coordinates(), is_local_coordinates(), is_world_coordinates(), set_coordinates_type(), and Show().
m_dirty
bool Slic3r::GUI::ObjectManipulation::m_dirty = false private
Referenced by set_dirty(), and update_if_dirty().
m_drop_to_bed_button
ScalableButton* Slic3r::GUI::ObjectManipulation::m_drop_to_bed_button { nullptr } private
Referenced by ObjectManipulation(), Enable(), sys_color_changed(), and update_reset_buttons_visibility().
m_editors
std::vector<ManipulationEditor*> Slic3r::GUI::ObjectManipulation::m_editors private
Referenced by ObjectManipulation(), msw_rescale(), sys_color_changed(), update_if_dirty(), and update_ui_from_settings().
m_empty_str
wxStaticText* Slic3r::GUI::ObjectManipulation::m_empty_str = nullptr private
Referenced by ObjectManipulation(), and Show().
m_fix_throught_netfab_bitmap
wxStaticBitmap* Slic3r::GUI::ObjectManipulation::m_fix_throught_netfab_bitmap { nullptr } private
Referenced by ObjectManipulation(), msw_rescale(), and update_warning_icon_state().
m_focused_editor
ManipulationEditor* Slic3r::GUI::ObjectManipulation::m_focused_editor { nullptr } private
Referenced by emulate_kill_focus(), get_focused_editor(), and set_focused_editor().
m_imperial_units
bool Slic3r::GUI::ObjectManipulation::m_imperial_units { false } private
Referenced by ObjectManipulation(), change_size_value(), on_change(), update_if_dirty(), and update_ui_from_settings().
m_is_enabled
bool Slic3r::GUI::ObjectManipulation::m_is_enabled { true } private
Referenced by DisableScale(), Enable(), and is_enabled().
m_is_enabled_size_and_scale
bool Slic3r::GUI::ObjectManipulation::m_is_enabled_size_and_scale { true } private
Referenced by DisableScale(), Enable(), and is_enabled_size_and_scale().
m_item_name
wxStaticText* Slic3r::GUI::ObjectManipulation::m_item_name = nullptr private
Referenced by ObjectManipulation(), msw_rescale(), and update_item_name().
m_labels_grid_sizer
wxFlexGridSizer* Slic3r::GUI::ObjectManipulation::m_labels_grid_sizer private
Referenced by ObjectManipulation().
m_lock_bnt
LockButton* Slic3r::GUI::ObjectManipulation::m_lock_bnt { nullptr } private
Referenced by ObjectManipulation(), DisableScale(), DisableUnuniformScale(), Enable(), sys_color_changed(), and update_if_dirty().
m_main_grid_sizer
wxFlexGridSizer* Slic3r::GUI::ObjectManipulation::m_main_grid_sizer private
Referenced by ObjectManipulation(), and Show().
m_manifold_warning_bmp
ScalableBitmap Slic3r::GUI::ObjectManipulation::m_manifold_warning_bmp private
Referenced by ObjectManipulation(), msw_rescale(), update_reset_buttons_visibility(), and update_warning_icon_state().
m_mirror_bitmap_on
ScalableBitmap Slic3r::GUI::ObjectManipulation::m_mirror_bitmap_on private
Referenced by ObjectManipulation(), and sys_color_changed().
m_mirror_buttons
std::array<ScalableButton*, 3> Slic3r::GUI::ObjectManipulation::m_mirror_buttons private
Referenced by ObjectManipulation(), sys_color_changed(), and update_mirror_buttons_visibility().
m_mirror_warning_bitmap
wxStaticBitmap* Slic3r::GUI::ObjectManipulation::m_mirror_warning_bitmap { nullptr } private
Referenced by ObjectManipulation(), and update_reset_buttons_visibility().
m_move_Label
wxStaticText* Slic3r::GUI::ObjectManipulation::m_move_Label = nullptr private
Referenced by ObjectManipulation(), and update_if_dirty().
m_new_enabled
bool Slic3r::GUI::ObjectManipulation::m_new_enabled {true} private
Referenced by reset_settings_value(), update_if_dirty(), and update_settings_value().
m_new_move_label_string
std::string Slic3r::GUI::ObjectManipulation::m_new_move_label_string private
Referenced by update_if_dirty(), and update_settings_value().
m_new_position
Vec3d Slic3r::GUI::ObjectManipulation::m_new_position private
Referenced by reset_settings_value(), update_if_dirty(), update_settings_value(), and update_ui_from_settings().
m_new_rotate_label_string
std::string Slic3r::GUI::ObjectManipulation::m_new_rotate_label_string private
Referenced by update_if_dirty(), and update_settings_value().
m_new_rotation
Vec3d Slic3r::GUI::ObjectManipulation::m_new_rotation private
Referenced by reset_settings_value(), update_if_dirty(), and update_settings_value().
m_new_scale
Vec3d Slic3r::GUI::ObjectManipulation::m_new_scale private
Referenced by reset_settings_value(), update_if_dirty(), and update_settings_value().
m_new_scale_label_string
std::string Slic3r::GUI::ObjectManipulation::m_new_scale_label_string private
Referenced by update_if_dirty(), and update_settings_value().
m_new_size
Vec3d Slic3r::GUI::ObjectManipulation::m_new_size private
Referenced by reset_settings_value(), update_if_dirty(), update_settings_value(), and update_ui_from_settings().
m_og
std::shared_ptr<ConfigOptionsGroup> Slic3r::GUI::OG_Settings::m_og protected inherited
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), Slic3r::GUI::ObjectLayers::ObjectLayers(), ObjectManipulation(), Slic3r::GUI::ObjectSettings::ObjectSettings(), Slic3r::GUI::OG_Settings::OG_Settings(), Slic3r::GUI::OG_Settings::get_og(), Slic3r::GUI::OG_Settings::get_og(), Slic3r::GUI::FreqChangedParams::get_og(), Slic3r::GUI::OG_Settings::get_sizer(), Slic3r::GUI::OG_Settings::IsShown(), IsShown(), Slic3r::GUI::FreqChangedParams::msw_rescale(), Slic3r::GUI::FreqChangedParams::Show(), Slic3r::GUI::OG_Settings::Show(), Show(), Slic3r::GUI::ObjectSettings::sys_color_changed(), Slic3r::GUI::FreqChangedParams::sys_color_changed(), update_if_dirty(), and Slic3r::GUI::ObjectSettings::update_settings_list().
m_parent
wxWindow* Slic3r::GUI::OG_Settings::m_parent protected inherited
Referenced by Slic3r::GUI::ObjectLayers::ObjectLayers(), ObjectManipulation(), Slic3r::GUI::OG_Settings::parent(), Slic3r::GUI::ObjectSettings::update_config_values(), Slic3r::GUI::ObjectSettings::update_settings_list(), and update_warning_icon_state().
m_position_unit
wxStaticText* Slic3r::GUI::ObjectManipulation::m_position_unit { nullptr } private
Referenced by ObjectManipulation(), and update_ui_from_settings().
m_rescalable_sizers
std::vector<wxBoxSizer*> Slic3r::GUI::ObjectManipulation::m_rescalable_sizers private
Referenced by ObjectManipulation(), and msw_rescale().
m_reset_rotation_button
ScalableButton* Slic3r::GUI::ObjectManipulation::m_reset_rotation_button { nullptr } private
Referenced by ObjectManipulation(), Enable(), sys_color_changed(), and update_reset_buttons_visibility().
m_reset_scale_button
ScalableButton* Slic3r::GUI::ObjectManipulation::m_reset_scale_button { nullptr } private
Referenced by ObjectManipulation(), DisableScale(), Enable(), sys_color_changed(), and update_reset_buttons_visibility().
m_reset_skew_button
ScalableButton* Slic3r::GUI::ObjectManipulation::m_reset_skew_button { nullptr } private
Referenced by ObjectManipulation(), DisableScale(), Enable(), and update_reset_buttons_visibility().
m_rotate_Label
wxStaticText* Slic3r::GUI::ObjectManipulation::m_rotate_Label = nullptr private
Referenced by ObjectManipulation(), and update_if_dirty().
m_scale_Label
wxStaticText* Slic3r::GUI::ObjectManipulation::m_scale_Label = nullptr private
Referenced by ObjectManipulation(), and update_if_dirty().
m_size_unit
wxStaticText* Slic3r::GUI::ObjectManipulation::m_size_unit { nullptr } private
Referenced by ObjectManipulation(), and update_ui_from_settings().
m_skew_label
wxStaticText* Slic3r::GUI::ObjectManipulation::m_skew_label { nullptr } private
Referenced by ObjectManipulation(), and update_reset_buttons_visibility().
m_uniform_scale
bool Slic3r::GUI::ObjectManipulation::m_uniform_scale {true} private
Referenced by do_scale(), do_size(), get_uniform_scaling(), set_uniform_scaling(), and update_if_dirty().
m_use_colors
bool Slic3r::GUI::ObjectManipulation::m_use_colors { false } private
Referenced by ObjectManipulation(), update_ui_from_settings(), and use_colors().
m_word_local_combo
choice_ctrl* Slic3r::GUI::ObjectManipulation::m_word_local_combo { nullptr } private
Referenced by ObjectManipulation(), msw_rescale(), set_coordinates_type(), Show(), and sys_color_changed().
m_word_local_combo_sizer
wxBoxSizer* Slic3r::GUI::ObjectManipulation::m_word_local_combo_sizer private
Referenced by ObjectManipulation(), and msw_rescale().
mm_to_in
const double Slic3r::GUI::ObjectManipulation::mm_to_in = 1 / ObjectManipulation::in_to_mm static
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_build_size(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoCut3D::render_double_input(), Slic3r::GUI::GLGizmoCut3D::render_move_center_input(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoEmboss::rev_input_mm(), Slic3r::GUI::Sidebar::show_info_sizer(), update_if_dirty(), Slic3r::GUI::Sidebar::update_sliced_info_sizer(), and update_ui_from_settings().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectManipulation.hpp
src/slic3r/GUI/GUI_ObjectManipulation.cpp