Prusa Slicer: Slic3r::GUI::DataList< T, D > Struct Template Reference
Slic3r::GUI::DataList< T, D > Struct Template Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
DataList (wxWindow *parent)
DataList (wxWindow *parent, int style)
int append (const std::string &label, const D *data)
int append (const wxString &label, const D *data)
const D & get_data (int n)
int find (const D &data)
int size ()
void on_mouse_move (const wxPoint &position)
Detailed Description
template<class T, class D>
struct Slic3r::GUI::DataList< T, D >
Constructor & Destructor Documentation
DataList() [1/2]
template<class T , class D > Slic3r::GUI::DataList< T, D >::DataList (wxWindow * parent) inline
: T(parent, wxID_ANY) {}
DataList() [2/2]
template<class T , class D > Slic3r::GUI::DataList< T, D >::DataList (wxWindow * parent, int style) inline
: T(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, NULL, style) {}
Member Function Documentation
append() [1/2]
template<class T , class D > int Slic3r::GUI::DataList< T, D >::append (const std::string & label, const D * data) inline
{
        void *ptr = reinterpret_cast<void*>(const_cast<D*>(data));
        return this->Append(from_u8(label), ptr);
    }
References Slic3r::GUI::from_u8().
Referenced by Slic3r::GUI::PageMaterials::reload_presets(), Slic3r::GUI::PageMaterials::sort_list_data(), Slic3r::GUI::PageMaterials::sort_list_data(), and Slic3r::GUI::PageMaterials::update_lists().
append() [2/2]
template<class T , class D > int Slic3r::GUI::DataList< T, D >::append (const wxString & label, const D * data) inline
{
        void *ptr = reinterpret_cast<void*>(const_cast<D*>(data));
        return this->Append(label, ptr);
    }
find()
template<class T , class D > int Slic3r::GUI::DataList< T, D >::find (const D & data) inline
{
        for (unsigned i = 0; i < this->GetCount(); i++) {
            if (get_data(i) == data) { return i; }
        }
        return wxNOT_FOUND;
    }
References Slic3r::GUI::DataList< T, D >::get_data().
Referenced by Slic3r::GUI::PageMaterials::update_lists().
get_data()
template<class T , class D > const D & Slic3r::GUI::DataList< T, D >::get_data (int n) inline
{
        return *reinterpret_cast<const D*>(this->GetClientData(n));
    }
Referenced by Slic3r::GUI::DataList< T, D >::find(), Slic3r::GUI::PageMaterials::on_material_highlighted(), Slic3r::GUI::PageMaterials::select_material(), Slic3r::GUI::PageMaterials::sort_list_data(), and Slic3r::GUI::PageMaterials::update_lists().
on_mouse_move()
template<class T , class D > void Slic3r::GUI::DataList< T, D >::on_mouse_move (const wxPoint & position) inline
{
        int item = T::HitTest(position);
        if(item == wxHitTest::wxHT_WINDOW_INSIDE)
            BOOST_LOG_TRIVIAL(error) << "hit test wxHT_WINDOW_INSIDE";
        else if (item == wxHitTest::wxHT_WINDOW_OUTSIDE)
            BOOST_LOG_TRIVIAL(error) << "hit test wxHT_WINDOW_OUTSIDE";
        else if(item == wxHitTest::wxHT_WINDOW_CORNER)
            BOOST_LOG_TRIVIAL(error) << "hit test wxHT_WINDOW_CORNER";
        else if (item == wxHitTest::wxHT_WINDOW_VERT_SCROLLBAR)
            BOOST_LOG_TRIVIAL(error) << "hit test wxHT_WINDOW_VERT_SCROLLBAR";
       else if (item == wxHitTest::wxHT_NOWHERE)
            BOOST_LOG_TRIVIAL(error) << "hit test wxHT_NOWHERE";
       else if (item == wxHitTest::wxHT_MAX)
            BOOST_LOG_TRIVIAL(error) << "hit test wxHT_MAX";
       else
            BOOST_LOG_TRIVIAL(error) << "hit test: " << item;
    }
References error.
size()
template<class T , class D > int Slic3r::GUI::DataList< T, D >::size () inline
{ return this->GetCount(); }
Referenced by Slic3r::GUI::PageMaterials::sort_list_data(), and Slic3r::GUI::PageMaterials::update_lists().
The documentation for this struct was generated from the following file:
src/slic3r/GUI/ConfigWizard_private.hpp