Prusa Slicer: Eigen::internal::evaluator< PlainObjectBase< Derived > > Struct Template Reference
Eigen::internal::evaluator< PlainObjectBase< Derived > > Struct Template Reference
#include <src/eigen/Eigen/src/Core/CoreEvaluators.h>
Public Types
enum {
IsRowMajor = PlainObjectType::IsRowMajor , IsVectorAtCompileTime = PlainObjectType::IsVectorAtCompileTime , RowsAtCompileTime = PlainObjectType::RowsAtCompileTime , ColsAtCompileTime = PlainObjectType::ColsAtCompileTime ,
CoeffReadCost = NumTraits<Scalar>::ReadCost , Flags = traits<Derived>::EvaluatorFlags , Alignment = traits<Derived>::Alignment
}
typedef PlainObjectBase< Derived > PlainObjectType
typedef PlainObjectType::Scalar Scalar
typedef PlainObjectType::CoeffReturnType CoeffReturnType
enum
typedef traits< Derived > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC evaluator ()
EIGEN_DEVICE_FUNC evaluator (const PlainObjectType &m)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Protected Attributes
const Scalar * m_data
variable_if_dynamic< Index, IsVectorAtCompileTime ? 0 :int(IsRowMajor) ? ColsAtCompileTime :RowsAtCompileTime > m_outerStride
Detailed Description
template<typename Derived>
struct Eigen::internal::evaluator< PlainObjectBase< Derived > >
Member Typedef Documentation
CoeffReturnType
template<typename Derived > typedef PlainObjectType::CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::CoeffReturnType
ExpressionTraits
typedef traits<Derived > Eigen::internal::evaluator_base< Derived >::ExpressionTraits inherited
PlainObjectType
template<typename Derived > typedef PlainObjectBase<Derived> Eigen::internal::evaluator< PlainObjectBase< Derived > >::PlainObjectType
Scalar
template<typename Derived > typedef PlainObjectType::Scalar Eigen::internal::evaluator< PlainObjectBase< Derived > >::Scalar
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    Alignment = 0
  };
anonymous enum
template<typename Derived > anonymous enum
Enumerator
IsRowMajor
IsVectorAtCompileTime
RowsAtCompileTime
ColsAtCompileTime
CoeffReadCost
Flags
Alignment
       {
    IsRowMajor = PlainObjectType::IsRowMajor,
    IsVectorAtCompileTime = PlainObjectType::IsVectorAtCompileTime,
    RowsAtCompileTime = PlainObjectType::RowsAtCompileTime,
    ColsAtCompileTime = PlainObjectType::ColsAtCompileTime,
    CoeffReadCost = NumTraits<Scalar>::ReadCost,
    Flags = traits<Derived>::EvaluatorFlags,
    Alignment = traits<Derived>::Alignment
  };
Constructor & Destructor Documentation
evaluator() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::internal::evaluator< PlainObjectBase< Derived > >::evaluator () inline
    : m_data(0),
      m_outerStride(IsVectorAtCompileTime  ? 0
                                           : int(IsRowMajor) ? ColsAtCompileTime
                                           : RowsAtCompileTime)
  {
    EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
  }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
evaluator() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::internal::evaluator< PlainObjectBase< Derived > >::evaluator (const PlainObjectType & m) inline explicit
    : m_data(m.data()), m_outerStride(IsVectorAtCompileTime ? 0 : m.outerStride())
  {
    EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
  }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff (Index index) const inline
  {
    return m_data[index];
  }
coeff() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff (Index row, Index col) const inline
  {
    if (IsRowMajor)
      return m_data[row * m_outerStride.value() + col];
    else
      return m_data[row + col * m_outerStride.value()];
  }
References col(), and row().
coeffRef() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef (Index index) inline
  {
    return const_cast<Scalar*>(m_data)[index];
  }
coeffRef() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef (Index row, Index col) inline
  {
    if (IsRowMajor)
      return const_cast<Scalar*>(m_data)[row * m_outerStride.value() + col];
    else
      return const_cast<Scalar*>(m_data)[row + col * m_outerStride.value()];
  }
References col(), and row().
packet() [1/2]
template<typename Derived > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet (Index index) const inline
  {
    return ploadt<PacketType, LoadMode>(m_data + index);
  }
packet() [2/2]
template<typename Derived > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet (Index row, Index col) const inline
  {
    if (IsRowMajor)
      return ploadt<PacketType, LoadMode>(m_data + row * m_outerStride.value() + col);
    else
      return ploadt<PacketType, LoadMode>(m_data + row + col * m_outerStride.value());
  }
References col(), and row().
writePacket() [1/2]
template<typename Derived > template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket (Index index, const PacketType & x) inline
  {
    return pstoret<Scalar, PacketType, StoreMode>(const_cast<Scalar*>(m_data) + index, x);
  }
writePacket() [2/2]
template<typename Derived > template<int StoreMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket (Index row, Index col, const PacketType & x) inline
  {
    if (IsRowMajor)
      return pstoret<Scalar, PacketType, StoreMode>
              (const_cast<Scalar*>(m_data) + row * m_outerStride.value() + col, x);
    else
      return pstoret<Scalar, PacketType, StoreMode>
                    (const_cast<Scalar*>(m_data) + row + col * m_outerStride.value(), x);
  }
References col(), and row().
Member Data Documentation
m_data
template<typename Derived > const Scalar* Eigen::internal::evaluator< PlainObjectBase< Derived > >::m_data protected
m_outerStride
template<typename Derived > variable_if_dynamic<Index, IsVectorAtCompileTime ? 0 : int(IsRowMajor) ? ColsAtCompileTime : RowsAtCompileTime> Eigen::internal::evaluator< PlainObjectBase< Derived > >::m_outerStride protected
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/CoreEvaluators.h