Prusa Slicer: igl::Serializable Class Reference
igl::Serializable Class Reference abstract
#include <src/libigl/igl/serialize.h>
Classes
struct SerializationObject
Public Member Functions
virtual void InitSerialization ()=0
virtual bool PreSerialization () const
virtual void PostSerialization () const
virtual bool PreDeserialization ()
virtual void PostDeserialization ()
void Serialize (std::vector< char > &buffer) const override final
void Deserialize (const std::vector< char > &buffer) override final
Serializable ()
Serializable (const Serializable &obj)
~Serializable ()
Serializable & operator= (const Serializable &obj)
template<typename T >
void Add (T &obj, std::string name, bool binary=false)
Private Attributes
bool initialized
std::vector< SerializableBase * > objects
Detailed Description
Constructor & Destructor Documentation
Serializable() [1/2]
igl::Serializable::Serializable () inline
  {
    initialized = false;
  }
References initialized.
Serializable() [2/2]
igl::Serializable::Serializable (const Serializable & obj) inline
  {
    initialized = false;
    objects.clear();
  }
References initialized, and objects.
~Serializable()
igl::Serializable::~Serializable () inline
  {
    initialized = false;
    objects.clear();
  }
References initialized, and objects.
Member Function Documentation
Add()
template<typename T > void igl::Serializable::Add (T & obj, std::string name, bool binary = false) inline
  {
    auto object = new SerializationObject<T>();
    object->Binary = binary;
    object->Name = name;
    object->Object = std::unique_ptr<T>(&obj);
    objects.push_back(object);
  }
References binary, and objects.
Deserialize()
void igl::Serializable::Deserialize (const std::vector< char > & buffer) inline final override virtual
Implements igl::SerializableBase.
  {
    if(this->PreDeserialization())
    {
      if(initialized == false)
      {
        objects.clear();
        (const_cast<Serializable*>(this))->InitSerialization();
        initialized = true;
      }
      for(auto& v : objects)
      {
        v->Deserialize(buffer);
      }
      this->PostDeserialization();
    }
  }
References initialized, objects, PostDeserialization(), and PreDeserialization().
InitSerialization()
virtual void igl::Serializable::InitSerialization () pure virtual
operator=()
Serializable & igl::Serializable::operator= (const Serializable & obj) inline
  {
    if(this != &obj)
    {
      if(initialized)
      {
        initialized = false;
        objects.clear();
      }
    }
    return *this;
  }
References initialized, and objects.
PostDeserialization()
void igl::Serializable::PostDeserialization () inline virtual
  {
  }
Referenced by Deserialize().
PostSerialization()
void igl::Serializable::PostSerialization () const inline virtual
  {
  }
Referenced by Serialize().
PreDeserialization()
bool igl::Serializable::PreDeserialization () inline virtual
  {
    return true;
  }
Referenced by Deserialize().
PreSerialization()
bool igl::Serializable::PreSerialization () const inline virtual
  {
    return true;
  }
Referenced by Serialize().
Serialize()
void igl::Serializable::Serialize (std::vector< char > & buffer) const inline final override virtual
Implements igl::SerializableBase.
  {
    if(this->PreSerialization())
    {
      if(initialized == false)
      {
        objects.clear();
        (const_cast<Serializable*>(this))->InitSerialization();
        initialized = true;
      }
      for(const auto& v : objects)
      {
        v->Serialize(buffer);
      }
      this->PostSerialization();
    }
  }
References initialized, objects, PostSerialization(), and PreSerialization().
Member Data Documentation
initialized
bool igl::Serializable::initialized mutable private
Referenced by Serializable(), Serializable(), ~Serializable(), Deserialize(), operator=(), and Serialize().
objects
std::vector<SerializableBase*> igl::Serializable::objects mutable private
Referenced by Serializable(), ~Serializable(), Add(), Deserialize(), operator=(), and Serialize().
The documentation for this class was generated from the following file:
src/libigl/igl/serialize.h