Prusa Slicer: Slic3r::GUI::ModePaletteComboBox Class Reference
Slic3r::GUI::ModePaletteComboBox Class Reference
#include <src/slic3r/GUI/ButtonsDescription.hpp>
Public Member Functions
ModePaletteComboBox (wxWindow *parent)
~ModePaletteComboBox ()=default
void UpdateSelection (const std::vector< wxColour > &palette_in)
int Append (const wxString &item, const wxBitmapBundle &bitmap)
Protected Member Functions
wxBitmapBundle * get_bmp (const std::vector< std::string > &palette)
Static Protected Member Functions
static BitmapCache & bitmap_cache ()
Detailed Description
Constructor & Destructor Documentation
ModePaletteComboBox()
Slic3r::GUI::ModePaletteComboBox::ModePaletteComboBox (wxWindow * parent)
                                                         :
  BitmapComboBox(parent, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0, nullptr, wxCB_READONLY)
{
  for (const auto& palette : MODE_PALETTES)
    Append(_(palette.first), *get_bmp(palette.second));
}
References _, Slic3r::GUI::BitmapComboBox::Append(), get_bmp(), and Slic3r::GUI::MODE_PALETTES.
~ModePaletteComboBox()
Slic3r::GUI::ModePaletteComboBox::~ModePaletteComboBox () default
Member Function Documentation
Append()
int Slic3r::GUI::BitmapComboBox::Append (const wxString & item, const wxBitmapBundle & bitmap) inline inherited
    {
        return wxBitmapComboBox::Append(item, bitmap);
    }
Referenced by ModePaletteComboBox(), BitmapChoiceRenderer::CreateEditorCtrl(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
bitmap_cache()
BitmapCache & Slic3r::GUI::ModePaletteComboBox::bitmap_cache () static protected
{
  static BitmapCache bmps;
  return bmps;
}
Referenced by get_bmp().
get_bmp()
wxBitmapBundle * Slic3r::GUI::ModePaletteComboBox::get_bmp (const std::vector< std::string > & palette) protected
{
  std::string bitmap_key;
  for (const auto& color : palette)
      bitmap_key += color + "+";
  const int icon_height = wxOSX ? 10 : 12;
  wxBitmapBundle* bmp_bndl = bitmap_cache().find_bndl(bitmap_key);
  if (bmp_bndl == nullptr) {
    // Create the bitmap with color bars.
    std::vector<wxBitmapBundle*> bmps;
    for (const auto& color : palette) {
      bmps.emplace_back(get_bmp_bundle("mode", icon_height, color));
      bmps.emplace_back(get_empty_bmp_bundle(wxOSX ? 5 : 6, icon_height));
    }
    bmp_bndl = bitmap_cache().insert_bndl(bitmap_key, bmps);
  }
  return bmp_bndl;
}
References bitmap_cache(), Slic3r::GUI::BitmapCache::find_bndl(), get_bmp_bundle(), get_empty_bmp_bundle(), Slic3r::GUI::BitmapCache::insert_bndl(), and wxOSX.
Referenced by ModePaletteComboBox().
UpdateSelection()
void Slic3r::GUI::ModePaletteComboBox::UpdateSelection (const std::vector< wxColour > & palette_in)
{
  for (size_t idx = 0; idx < MODE_PALETTES.size(); ++idx ) {
    const auto& palette = MODE_PALETTES[idx].second;
    bool is_selected = true;
    for (size_t mode = 0; mode < palette_in.size(); mode++)
      if (wxColour(palette[mode]) != palette_in[mode]) {
        is_selected = false;
        break;
      }
    if (is_selected) {
      Select(int(idx));
      return;
    }
  }
  Select(-1);
}
References Slic3r::GUI::MODE_PALETTES.
The documentation for this class was generated from the following files:
src/slic3r/GUI/ButtonsDescription.hpp
src/slic3r/GUI/ButtonsDescription.cpp