Prusa Slicer: Slic3r::GUI::BitmapCache Class Reference
Slic3r::GUI::BitmapCache Class Reference
#include <src/slic3r/GUI/BitmapCache.hpp>
Public Member Functions
BitmapCache ()
~BitmapCache ()
void clear ()
double scale ()
wxBitmapBundle * find_bndl (const std::string &name)
const wxBitmapBundle * find_bndl (const std::string &name) const
wxBitmap * find (const std::string &name)
const wxBitmap * find (const std::string &name) const
wxBitmapBundle * insert_bndl (const std::string &bitmap_key, const char *data, size_t width, size_t height)
wxBitmapBundle * insert_bndl (const std::string &bitmap_key, const wxBitmapBundle &bmp)
wxBitmapBundle * insert_bndl (const std::string &bitmap_key, const wxVector< wxBitmap > &bmps)
wxBitmapBundle * insert_bndl (const std::string &name, const std::vector< wxBitmapBundle * > &bmps)
wxBitmapBundle * insert_raw_rgba_bndl (const std::string &bitmap_key, unsigned width, unsigned height, const unsigned char *raw_data, const bool grayscale=false)
wxBitmap * insert (const std::string &name, size_t width, size_t height, double scale=-1.0)
wxBitmap * insert (const std::string &name, const wxBitmap &bmp)
wxBitmap * insert_raw_rgba (const std::string &bitmap_key, unsigned width, unsigned height, const unsigned char *raw_data, const bool grayscale=false)
wxBitmap * load_png (const std::string &bitmap_key, unsigned width=0, unsigned height=0, const bool grayscale=false)
wxBitmapBundle * from_svg (const std::string &bitmap_name, unsigned target_width, unsigned target_height, const bool dark_mode, const std::string &new_color="")
wxBitmapBundle * from_png (const std::string &bitmap_name, unsigned width, unsigned height)
wxBitmap * load_svg (const std::string &bitmap_key, unsigned width=0, unsigned height=0, const bool grayscale=false, const bool dark_mode=false, const std::string &new_color="")
wxBitmapBundle mksolid (size_t width, size_t height, unsigned char r, unsigned char g, unsigned char b, unsigned char transparency, size_t border_width=0, bool dark_mode=false)
wxBitmapBundle * mksolid_bndl (size_t width, size_t height, const std::string &color=std::string(), size_t border_width=0, bool dark_mode=false)
wxBitmapBundle * mkclear_bndl (size_t width, size_t height)
Static Public Member Functions
static NSVGimage * nsvgParseFromFileWithReplace (const char *filename, const char *units, float dpi, const std::map< std::string, std::string > &replaces)
static void nsvgGetDataFromFileWithReplace (const char *filename, std::string &data_str, const std::map< std::string, std::string > &replaces)
Private Attributes
std::map< std::string, wxBitmap * > m_map
std::map< std::string, wxBitmapBundle * > m_bndl_map
double m_gs = 0.2
double m_scale = 1.0
Detailed Description
Constructor & Destructor Documentation
BitmapCache()
Slic3r::GUI::BitmapCache::BitmapCache ()
{
#ifdef __APPLE__
    // Note: win->GetContentScaleFactor() is not used anymore here because it tends to
    // return bogus results quite often (such as 1.0 on Retina or even 0.0).
    // We're using the max scaling factor across all screens because it's very likely to be good enough.
    m_scale = mac_max_scaling_factor();
#endif
}
References m_scale, and Slic3r::GUI::mac_max_scaling_factor().
~BitmapCache()
Slic3r::GUI::BitmapCache::~BitmapCache () inline
{ clear(); }
References clear().
Member Function Documentation
clear()
void Slic3r::GUI::BitmapCache::clear ()
{
    for (std::pair<const std::string, wxBitmap*> &bitmap : m_map)
        delete bitmap.second;
    m_map.clear();
    for (std::pair<const std::string, wxBitmapBundle*> &bitmap_bundle : m_bndl_map)
        delete bitmap_bundle.second;
    m_bndl_map.clear();
}
References m_bndl_map, and m_map.
Referenced by ~BitmapCache().
find() [1/2]
wxBitmap * Slic3r::GUI::BitmapCache::find (const std::string & name) inline
{ auto it = m_map.find(name); return (it == m_map.end()) ? nullptr : it->second; }
References m_map.
find() [2/2]
const wxBitmap * Slic3r::GUI::BitmapCache::find (const std::string & name) const inline
{ return const_cast<BitmapCache*>(this)->find(name); }
References find().
Referenced by find().
find_bndl() [1/2]
wxBitmapBundle * Slic3r::GUI::BitmapCache::find_bndl (const std::string & name) inline
{ auto it = m_bndl_map.find(name); return (it == m_bndl_map.end()) ? nullptr : it->second; }
References m_bndl_map.
Referenced by Slic3r::GUI::find_bndl(), Slic3r::GUI::ModePaletteComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::get_bmp().
find_bndl() [2/2]
const wxBitmapBundle * Slic3r::GUI::BitmapCache::find_bndl (const std::string & name) const inline
{ return const_cast<BitmapCache*>(this)->find_bndl(name); }
References find_bndl().
Referenced by find_bndl().
from_png()
wxBitmapBundle * Slic3r::GUI::BitmapCache::from_png (const std::string & bitmap_name, unsigned width, unsigned height)
{
    std::string bitmap_key = bitmap_name + (height != 0 ?
        "-h" + std::to_string(height) :
        "-w" + std::to_string(width));
    auto it = m_bndl_map.find(bitmap_key);
    if (it != m_bndl_map.end())
        return it->second;
    wxImage image;
    if (!image.LoadFile(Slic3r::GUI::from_u8(Slic3r::var(bitmap_name + ".png")), wxBITMAP_TYPE_PNG) ||
        image.GetWidth() == 0 || image.GetHeight() == 0)
        return nullptr;
    if (height != 0 && unsigned(image.GetHeight()) != height)
        width = unsigned(0.5f + float(image.GetWidth()) * height / image.GetHeight());
    else if (width != 0 && unsigned(image.GetWidth()) != width)
        height = unsigned(0.5f + float(image.GetHeight()) * width / image.GetWidth());
    if (height != 0 && width != 0)
        image.Rescale(width, height, wxIMAGE_QUALITY_BILINEAR);
    return this->insert_bndl(bitmap_key, wxImage_to_wxBitmap_with_alpha(std::move(image)));
}
References Slic3r::GUI::from_u8(), insert_bndl(), m_bndl_map, Slic3r::var(), and Slic3r::GUI::wxImage_to_wxBitmap_with_alpha().
Referenced by get_bmp_bundle().
from_svg()
wxBitmapBundle * Slic3r::GUI::BitmapCache::from_svg (const std::string & bitmap_name, unsigned target_width, unsigned target_height, const bool dark_mode, const std::string & new_color = "")
{
    if (target_width == 0)
        target_width = target_height;
    std::string bitmap_key = bitmap_name + (target_height != 0 ?
        "-h" + std::to_string(target_height) :
        "-w" + std::to_string(target_width))
        + (dark_mode ? "-dm" : "")
        + new_color;
    auto it = m_bndl_map.find(bitmap_key);
    if (it != m_bndl_map.end())
        return it->second;
    // map of color replaces
    std::map<std::string, std::string> replaces;
    if (dark_mode)
        replaces["\"#808080\""] = "\"#FFFFFF\"";
    if (!new_color.empty())
        replaces["\"#ED6B21\""] = "\"" + new_color + "\"";
    std::string str;
    nsvgGetDataFromFileWithReplace(Slic3r::var(bitmap_name + ".svg").c_str(), str, replaces);
    if (str.empty())
        return nullptr;
    return insert_bndl(bitmap_key, str.data(), target_width, target_height);
}
References insert_bndl(), m_bndl_map, nsvgGetDataFromFileWithReplace(), and Slic3r::var().
Referenced by Slic3r::GUI::PresetComboBox::get_bmp(), and get_bmp_bundle().
insert() [1/2]
wxBitmap * Slic3r::GUI::BitmapCache::insert (const std::string & name, const wxBitmap & bmp)
{
    wxBitmap *bitmap = nullptr;
    auto      it     = m_map.find(bitmap_key);
    if (it == m_map.end()) {
        bitmap = new wxBitmap(bmp);
        m_map[bitmap_key] = bitmap;
    } else {
        bitmap = it->second;
        *bitmap = bmp;
    }
    return bitmap;
}
References m_map.
insert() [2/2]
wxBitmap * Slic3r::GUI::BitmapCache::insert (const std::string & name, size_t width, size_t height, double scale = -1.0)
{
    wxBitmap *bitmap = nullptr;
    auto      it     = m_map.find(bitmap_key);
    if (it == m_map.end()) {
        bitmap = new wxBitmap(width, height
#ifdef __WXGTK3__
            , 32
#endif
            );
#ifdef __APPLE__
        // Contrary to intuition, the `scale` argument isn't "please scale this to such and such"
        // but rather "the wxImage is sized for backing scale such and such".
        // So, We need to let the Mac OS wxBitmap implementation
        // know that the image may already be scaled appropriately for Retina,
        // and thereby that it's not supposed to upscale it.
        bitmap->CreateScaled(width, height, -1, scale < 0.0 ? m_scale : scale);
#endif
        m_map[bitmap_key] = bitmap;
    } else {
        bitmap = it->second;
        if (size_t(bitmap->GetWidth()) != width || size_t(bitmap->GetHeight()) != height)
            bitmap->Create(width, height);
    }
#if defined(WIN32) || defined(__APPLE__)
    // Not needed or harmful for GTK2 and GTK3.
    bitmap->UseAlpha();
#endif
    return bitmap;
}
References m_map, m_scale, and scale().
Referenced by insert_bndl(), insert_raw_rgba(), and load_png().
insert_bndl() [1/4]
wxBitmapBundle * Slic3r::GUI::BitmapCache::insert_bndl (const std::string & bitmap_key, const char * data, size_t width, size_t height)
{
    wxBitmapBundle* bndl = nullptr;
    auto it = m_bndl_map.find(bitmap_key);
    if (it == m_bndl_map.end()) {
        bndl = new wxBitmapBundle(wxBitmapBundle::FromSVG(data, wxSize(width, height)));
        m_bndl_map[bitmap_key] = bndl;
    }
    else {
        bndl = it->second;
        *bndl = wxBitmapBundle::FromSVG(data, wxSize(width, height));
    }
    return bndl;
}
References m_bndl_map.
Referenced by from_png(), from_svg(), Slic3r::GUI::ModePaletteComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), insert_bndl(), Slic3r::GUI::ObjectDataViewModelNode::update_settings_digest_bitmaps(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
insert_bndl() [2/4]
wxBitmapBundle * Slic3r::GUI::BitmapCache::insert_bndl (const std::string & bitmap_key, const wxBitmapBundle & bmp)
{
    wxBitmapBundle* bndl = nullptr;
    auto it = m_bndl_map.find(bitmap_key);
    if (it == m_bndl_map.end()) {
        bndl = new wxBitmapBundle(bmp);
        m_bndl_map[bitmap_key] = bndl;
    }
    else {
        bndl = it->second;
        *bndl = wxBitmapBundle(bmp);
    }
    return bndl;
}
References m_bndl_map.
insert_bndl() [3/4]
wxBitmapBundle * Slic3r::GUI::BitmapCache::insert_bndl (const std::string & bitmap_key, const wxVector< wxBitmap > & bmps)
{
    wxBitmapBundle* bndl = nullptr;
    auto it = m_bndl_map.find(bitmap_key);
    if (it == m_bndl_map.end()) {
        bndl = new wxBitmapBundle(wxBitmapBundle::FromBitmaps(bmps));
        m_bndl_map[bitmap_key] = bndl;
    }
    else {
        bndl = it->second;
        *bndl = wxBitmapBundle::FromBitmaps(bmps);
    }
    return bndl;
}
References m_bndl_map.
insert_bndl() [4/4]
wxBitmapBundle * Slic3r::GUI::BitmapCache::insert_bndl (const std::string & name, const std::vector< wxBitmapBundle * > & bmps)
{
    wxVector<wxBitmap> bitmaps;
    std::set<double> scales = {1.0};
#ifndef __linux__
#ifdef __APPLE__
    scales.emplace(m_scale);
#else
    size_t disp_cnt = wxDisplay::GetCount();
    for (size_t disp = 0; disp < disp_cnt; ++disp)
        scales.emplace(wxDisplay(disp).GetScaleFactor());
#endif
#endif // !__linux__
    for (double scale : scales) {
        size_t width = 0;
        size_t height = 0;
        for (const wxBitmapBundle* bmp_bndl : bmps) {
#ifdef __APPLE__
            wxSize size = bmp_bndl->GetDefaultSize();
#else
            wxSize size = bmp_bndl->GetPreferredBitmapSizeAtScale(scale);
#endif
            width += size.GetWidth();
            height = std::max<size_t>(height, size.GetHeight());
        }
        std::string bitmap_key = name + "," +float_to_string_decimal_point(scale);
#ifdef __WXGTK2__
        // Broken alpha workaround
        wxImage image(width, height);
        image.InitAlpha();
        // Fill in with a white color.
        memset(image.GetData(), 0x0ff, width * height * 3);
        // Fill in with full transparency.
        memset(image.GetAlpha(), 0, width * height);
        size_t x = 0;
        for (const wxBitmapBundle* bmp_bndl : bmps) {
            wxBitmap bmp = bmp_bndl->GetBitmap(bmp_bndl->GetDefaultSize());
            if (bmp.GetWidth() > 0) {
                if (bmp.GetDepth() == 32) {
                    wxAlphaPixelData data(bmp);
                    //FIXME The following method is missing from wxWidgets 3.1.1.
                    // It looks like the wxWidgets 3.0.3 called the wrapped bitmap's UseAlpha().
                    //data.UseAlpha();
                    if (data) {
                        for (int r = 0; r < bmp.GetHeight(); ++r) {
                            wxAlphaPixelData::Iterator src(data);
                            src.Offset(data, 0, r);
                            unsigned char* dst_pixels = image.GetData() + (x + r * width) * 3;
                            unsigned char* dst_alpha = image.GetAlpha() + x + r * width;
                            for (int c = 0; c < bmp.GetWidth(); ++c, ++src) {
                                *dst_pixels++ = src.Red();
                                *dst_pixels++ = src.Green();
                                *dst_pixels++ = src.Blue();
                                *dst_alpha++ = src.Alpha();
                            }
                        }
                    }
                }
                else if (bmp.GetDepth() == 24) {
                    wxNativePixelData data(bmp);
                    if (data) {
                        for (int r = 0; r < bmp.GetHeight(); ++r) {
                            wxNativePixelData::Iterator src(data);
                            src.Offset(data, 0, r);
                            unsigned char* dst_pixels = image.GetData() + (x + r * width) * 3;
                            unsigned char* dst_alpha = image.GetAlpha() + x + r * width;
                            for (int c = 0; c < bmp.GetWidth(); ++c, ++src) {
                                *dst_pixels++ = src.Red();
                                *dst_pixels++ = src.Green();
                                *dst_pixels++ = src.Blue();
                                *dst_alpha++ = wxALPHA_OPAQUE;
                            }
                        }
                    }
                }
            }
            x += bmp.GetScaledWidth();
        }
        bitmaps.push_back(* this->insert(bitmap_key, wxImage_to_wxBitmap_with_alpha(std::move(image))));
#else
        wxBitmap* bitmap = this->insert(bitmap_key, width, height, scale);
        wxMemoryDC memDC;
        memDC.SelectObject(*bitmap);
        memDC.SetBackground(*wxTRANSPARENT_BRUSH);
        memDC.Clear();
        size_t x = 0;
        for (const wxBitmapBundle* bmp_bndl : bmps) {
            wxBitmap bmp = bmp_bndl->GetBitmap(bmp_bndl->GetPreferredBitmapSizeAtScale(scale));
            if (bmp.GetWidth() > 0)
                memDC.DrawBitmap(bmp, x, 0, true);
            // we should "move" with step equal to non-scaled width
#ifdef __APPLE__
            x += bmp.GetScaledWidth();
#else
            x += bmp.GetWidth();
#endif
        }
        memDC.SelectObject(wxNullBitmap);
        bitmaps.push_back(*bitmap);
#endif
    }
    return insert_bndl(name, bitmaps);
}
References Slic3r::float_to_string_decimal_point(), insert(), insert_bndl(), m_scale, scale(), and Slic3r::GUI::wxImage_to_wxBitmap_with_alpha().
insert_raw_rgba()
wxBitmap * Slic3r::GUI::BitmapCache::insert_raw_rgba (const std::string & bitmap_key, unsigned width, unsigned height, const unsigned char * raw_data, const bool grayscale = false)
{
    wxImage image(width, height);
    image.InitAlpha();
    unsigned char *rgb   = image.GetData();
    unsigned char *alpha = image.GetAlpha();
    unsigned int pixels = width * height;
    for (unsigned int i = 0; i < pixels; ++ i) {
        *rgb   ++ = *raw_data ++;
        *rgb   ++ = *raw_data ++;
        *rgb   ++ = *raw_data ++;
        *alpha ++ = *raw_data ++;
    }
    if (grayscale)
        image = image.ConvertToGreyscale(m_gs, m_gs, m_gs);
    return this->insert(bitmap_key, wxImage_to_wxBitmap_with_alpha(std::move(image), m_scale));
}
References insert(), m_gs, m_scale, and Slic3r::GUI::wxImage_to_wxBitmap_with_alpha().
Referenced by load_svg().
insert_raw_rgba_bndl()
wxBitmapBundle * Slic3r::GUI::BitmapCache::insert_raw_rgba_bndl (const std::string & bitmap_key, unsigned width, unsigned height, const unsigned char * raw_data, const bool grayscale = false)
load_png()
wxBitmap * Slic3r::GUI::BitmapCache::load_png (const std::string & bitmap_key, unsigned width = 0, unsigned height = 0, const bool grayscale = false)
{
    std::string bitmap_key = bitmap_name + ( height !=0 ?
                                           "-h" + std::to_string(height) :
                                           "-w" + std::to_string(width))
                                         + (grayscale ? "-gs" : "");
    auto it = m_map.find(bitmap_key);
    if (it != m_map.end())
        return it->second;
    wxImage image;
    if (! image.LoadFile(Slic3r::GUI::from_u8(Slic3r::var(bitmap_name + ".png")), wxBITMAP_TYPE_PNG) ||
        image.GetWidth() == 0 || image.GetHeight() == 0)
        return nullptr;
    if (height != 0 && unsigned(image.GetHeight()) != height)
        width   = unsigned(0.5f + float(image.GetWidth()) * height / image.GetHeight());
    else if (width != 0 && unsigned(image.GetWidth()) != width)
        height  = unsigned(0.5f + float(image.GetHeight()) * width / image.GetWidth());
    if (height != 0 && width != 0)
        image.Rescale(width, height, wxIMAGE_QUALITY_BILINEAR);
    if (grayscale)
        image = image.ConvertToGreyscale(m_gs, m_gs, m_gs);
    return this->insert(bitmap_key, wxImage_to_wxBitmap_with_alpha(std::move(image)));
}
References Slic3r::GUI::from_u8(), insert(), m_gs, m_map, Slic3r::var(), and Slic3r::GUI::wxImage_to_wxBitmap_with_alpha().
load_svg()
wxBitmap * Slic3r::GUI::BitmapCache::load_svg (const std::string & bitmap_key, unsigned width = 0, unsigned height = 0, const bool grayscale = false, const bool dark_mode = false, const std::string & new_color = "")
{
    std::string bitmap_key = bitmap_name + ( target_height !=0 ?
                                           "-h" + std::to_string(target_height) :
                                           "-w" + std::to_string(target_width))
                                         + (m_scale != 1.0f ? "-s" + float_to_string_decimal_point(m_scale) : "")
                                         + (dark_mode ? "-dm" : "")
                                         + (grayscale ? "-gs" : "")
                                         + new_color;
    auto it = m_map.find(bitmap_key);
    if (it != m_map.end())
        return it->second;
    // map of color replaces
    std::map<std::string, std::string> replaces;
    if (dark_mode)
        replaces["\"#808080\""] = "\"#FFFFFF\"";
    if (!new_color.empty())
        replaces["\"#ED6B21\""] = "\"" + new_color + "\"";
    NSVGimage *image =  nsvgParseFromFileWithReplace(Slic3r::var(bitmap_name + ".svg").c_str(), "px", 96.0f, replaces);
    if (image == nullptr)
        return nullptr;
    target_height != 0 ? target_height *= m_scale : target_width *= m_scale;
    float svg_scale = target_height != 0 ?
                  (float)target_height / image->height  : target_width != 0 ?
                  (float)target_width / image->width    : 1;
    int   width    = (int)(svg_scale * image->width + 0.5f);
    int   height   = (int)(svg_scale * image->height + 0.5f);
    int   n_pixels = width * height;
    if (n_pixels <= 0) {
        ::nsvgDelete(image);
        return nullptr;
    }
    NSVGrasterizer *rast = ::nsvgCreateRasterizer();
    if (rast == nullptr) {
        ::nsvgDelete(image);
        return nullptr;
    }
    std::vector<unsigned char> data(n_pixels * 4, 0);
    ::nsvgRasterize(rast, image, 0, 0, svg_scale, data.data(), width, height, width * 4);
    ::nsvgDeleteRasterizer(rast);
    ::nsvgDelete(image);
    return this->insert_raw_rgba(bitmap_key, width, height, data.data(), grayscale);
}
References Slic3r::float_to_string_decimal_point(), insert_raw_rgba(), m_map, m_scale, nsvgParseFromFileWithReplace(), and Slic3r::var().
Referenced by Slic3r::GUI::SplashScreen::Decorate().
mkclear_bndl()
wxBitmapBundle * Slic3r::GUI::BitmapCache::mkclear_bndl (size_t width, size_t height) inline
{ return  mksolid_bndl(width, height); }
References mksolid_bndl().
Referenced by get_empty_bmp_bundle().
mksolid()
wxBitmapBundle Slic3r::GUI::BitmapCache::mksolid (size_t width, size_t height, unsigned char r, unsigned char g, unsigned char b, unsigned char transparency, size_t border_width = 0, bool dark_mode = false)
{
    wxVector<wxBitmap> bitmaps;
    std::set<double> scales = { 1.0 };
#ifndef __linux__
#ifdef __APPLE__
    scales.emplace(m_scale);
#else
    size_t disp_cnt = wxDisplay::GetCount();
    for (size_t disp = 0; disp < disp_cnt; ++disp)
        scales.emplace(wxDisplay(disp).GetScaleFactor());
#endif
#endif // !__linux__
    for (double scale : scales) {
        size_t width = width_in * scale;
        size_t height = height_in * scale;
        wxImage image(width, height);
        image.InitAlpha();
        unsigned char* imgdata = image.GetData();
        unsigned char* imgalpha = image.GetAlpha();
        for (size_t i = 0; i < width * height; ++i) {
            *imgdata++ = r;
            *imgdata++ = g;
            *imgdata++ = b;
            *imgalpha++ = transparency;
        }
        // Add border, make white/light spools easier to see
        if (border_width > 0) {
            // Restrict to width of image
            if (border_width > height) border_width = height - 1;
            if (border_width > width) border_width = width - 1;
            auto px_data = (uint8_t*)image.GetData();
            auto a_data = (uint8_t*)image.GetAlpha();
            for (size_t x = 0; x < width; ++x) {
                for (size_t y = 0; y < height; ++y) {
                    if (x < border_width || y < border_width ||
                        x >= (width - border_width) || y >= (height - border_width)) {
                        const size_t idx = (x + y * width);
                        const size_t idx_rgb = (x + y * width) * 3;
                        px_data[idx_rgb] = px_data[idx_rgb + 1] = px_data[idx_rgb + 2] = dark_mode ? 245u : 110u;
                        a_data[idx] = 255u;
                    }
                }
            }
        }
        bitmaps.push_back(wxImage_to_wxBitmap_with_alpha(std::move(image), scale));
    }
    return wxBitmapBundle::FromBitmaps(bitmaps);
}
References m_scale, scale(), and Slic3r::GUI::wxImage_to_wxBitmap_with_alpha().
Referenced by mksolid_bndl().
mksolid_bndl()
wxBitmapBundle * Slic3r::GUI::BitmapCache::mksolid_bndl (size_t width, size_t height, const std::string & color = std::string(), size_t border_width = 0, bool dark_mode = false)
{
    std::string bitmap_key = (color.empty() ? "empty" : color) + "-h" + std::to_string(height) + "-w" + std::to_string(width) + (dark_mode ? "-dm" : "");
    wxBitmapBundle* bndl = nullptr;
    auto it = m_bndl_map.find(bitmap_key);
    if (it == m_bndl_map.end()) {
        if (color.empty())
            bndl = new wxBitmapBundle(mksolid(width, height, 0, 0, 0, wxALPHA_TRANSPARENT, size_t(0)));
        else {
            ColorRGB rgb;// [3] ;
            decode_color(color, rgb);
            bndl = new wxBitmapBundle(mksolid(width, height, rgb.r_uchar(), rgb.g_uchar(), rgb.b_uchar(), wxALPHA_OPAQUE, border_width, dark_mode));
        }
        m_bndl_map[bitmap_key] = bndl;
    }
    else
        return it->second;
    return bndl;
}
References Slic3r::ColorRGB::b_uchar(), Slic3r::decode_color(), Slic3r::ColorRGB::g_uchar(), m_bndl_map, mksolid(), and Slic3r::ColorRGB::r_uchar().
Referenced by get_solid_bmp_bundle(), and mkclear_bndl().
nsvgGetDataFromFileWithReplace()
void Slic3r::GUI::BitmapCache::nsvgGetDataFromFileWithReplace (const char * filename, std::string & data_str, const std::map< std::string, std::string > & replaces) static
{
    FILE* fp = NULL;
    size_t size;
    char* data = NULL;
    fp = boost::nowide::fopen(filename, "rb");
    if (!fp) goto error;
    fseek(fp, 0, SEEK_END);
    size = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    data = (char*)malloc(size + 1);
    if (data == NULL) goto error;
    if (fread(data, 1, size, fp) != size) goto error;
    data[size] = '\0';  // Must be null terminated.
    fclose(fp);
    data_str.assign(data);
    for (auto val : replaces)
        boost::replace_all(data_str, val.first, val.second);
    free(data);
    return;
error:
    if (fp) fclose(fp);
    if (data) free(data);
    return;
}
References error, free(), malloc(), and SEEK_SET.
Referenced by from_svg().
nsvgParseFromFileWithReplace()
NSVGimage * Slic3r::GUI::BitmapCache::nsvgParseFromFileWithReplace (const char * filename, const char * units, float dpi, const std::map< std::string, std::string > & replaces) static
{
    std::string str;
    FILE* fp = NULL;
    size_t size;
    char* data = NULL;
    NSVGimage* image = NULL;
    fp = boost::nowide::fopen(filename, "rb");
    if (!fp) goto error;
    fseek(fp, 0, SEEK_END);
    size = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    data = (char*)malloc(size + 1);
    if (data == NULL) goto error;
    if (fread(data, 1, size, fp) != size) goto error;
    data[size] = '\0';  // Must be null terminated.
    fclose(fp);
    if (replaces.empty())
        image = nsvgParse(data, units, dpi);
    else {
        str.assign(data);
        for (auto val : replaces)
            boost::replace_all(str, val.first, val.second);
        image = nsvgParse(str.data(), units, dpi);
    }
    free(data);
    return image;
error:
    if (fp) fclose(fp);
    if (data) free(data);
    if (image) nsvgDelete(image);
    return NULL;
}
References error, free(), malloc(), and SEEK_SET.
Referenced by Slic3r::GUI::GLTexture::load_from_svg(), Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), load_svg(), and Slic3r::GUI::ImGuiWrapper::load_svg().
scale()
double Slic3r::GUI::BitmapCache::scale () inline
{ return m_scale; }
References m_scale.
Referenced by insert(), insert_bndl(), and mksolid().
Member Data Documentation
m_bndl_map
std::map<std::string, wxBitmapBundle*> Slic3r::GUI::BitmapCache::m_bndl_map private
Referenced by clear(), find_bndl(), from_png(), from_svg(), insert_bndl(), insert_bndl(), insert_bndl(), and mksolid_bndl().
m_gs
double Slic3r::GUI::BitmapCache::m_gs = 0.2 private
Referenced by insert_raw_rgba(), and load_png().
m_map
std::map<std::string, wxBitmap*> Slic3r::GUI::BitmapCache::m_map private
Referenced by clear(), find(), insert(), insert(), load_png(), and load_svg().
m_scale
double Slic3r::GUI::BitmapCache::m_scale = 1.0 private
Referenced by BitmapCache(), insert(), insert_bndl(), insert_raw_rgba(), load_svg(), mksolid(), and scale().
The documentation for this class was generated from the following files:
src/slic3r/GUI/BitmapCache.hpp
src/slic3r/GUI/BitmapCache.cpp