Prusa Slicer: Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense > Class Template Reference
Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense > Class Template Reference
Base class for a triangular part in a dense matrix.
#include <src/eigen/Eigen/src/Core/TriangularMatrix.h>
Public Types
enum { Mode = _Mode , Flags = internal::traits<TriangularViewType>::Flags }
typedef TriangularView< _MatrixType, _Mode > TriangularViewType
typedef TriangularBase< TriangularViewType > Base
typedef internal::traits< TriangularViewType >::Scalar Scalar
typedef _MatrixType MatrixType
typedef MatrixType::PlainObject DenseMatrixType
typedef DenseMatrixType PlainObject
typedef internal::traits< TriangularViewType >::StorageKind StorageKind
enum
typedef internal::traits< TriangularView< _MatrixType, _Mode > >::StorageIndex StorageIndex
typedef DenseMatrixType DenseType
typedef TriangularView< _MatrixType, _Mode > const & Nested
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Index innerStride () const
template<typename Other >
EIGEN_DEVICE_FUNC TriangularViewType & operator+= (const DenseBase< Other > &other)
template<typename Other >
EIGEN_DEVICE_FUNC TriangularViewType & operator-= (const DenseBase< Other > &other)
EIGEN_DEVICE_FUNC TriangularViewType & operator*= (const typename internal::traits< MatrixType >::Scalar &other)
EIGEN_DEVICE_FUNC TriangularViewType & operator/= (const typename internal::traits< MatrixType >::Scalar &other)
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC TriangularViewType & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC TriangularViewType & setZero ()
EIGEN_DEVICE_FUNC TriangularViewType & setOnes ()
EIGEN_DEVICE_FUNC Scalar coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC TriangularViewType & operator= (const TriangularBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC TriangularViewType & operator= (const MatrixBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TriangularViewType & operator= (const TriangularViewImpl &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void lazyAssign (const TriangularBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void lazyAssign (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< TriangularViewType, OtherDerived > operator* (const MatrixBase< OtherDerived > &rhs) const
template<int Side, typename Other >
EIGEN_DEVICE_FUNC const internal::triangular_solve_retval< Side, TriangularViewType, Other > solve (const MatrixBase< Other > &other) const
template<int Side, typename OtherDerived >
EIGEN_DEVICE_FUNC void solveInPlace (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void solveInPlace (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (TriangularBase< OtherDerived > const &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (MatrixBase< OtherDerived > const &other)
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename ProductType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TriangularViewType & _assignProduct (const ProductType &prod, const Scalar &alpha, bool beta)
template<typename DenseDerived >
EIGEN_DEVICE_FUNC void evalToLazy (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
void evalToLazy (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, Other &other)
EIGEN_DEVICE_FUNC Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & operator() (Index row, Index col)
EIGEN_DEVICE_FUNC void evalTo (MatrixBase< DenseDerived > &other) const
void evalTo (MatrixBase< DenseDerived > &other) const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
Friends
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< OtherDerived, TriangularViewType > operator* (const MatrixBase< OtherDerived > &lhs, const TriangularViewImpl &rhs)
Detailed Description
template<typename _MatrixType, unsigned int _Mode>
class Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >
Base class for a triangular part in a dense matrix.
This class is an abstract base class of class TriangularView, and objects of type TriangularViewImpl cannot be instantiated. It extends class TriangularView with additional methods which available for dense expressions only.
See also
class TriangularView, MatrixBase::triangularView()
Member Typedef Documentation
Base
template<typename _MatrixType , unsigned int _Mode> typedef TriangularBase<TriangularViewType> Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::Base
DenseMatrixType
template<typename _MatrixType , unsigned int _Mode> typedef MatrixType::PlainObject Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::DenseMatrixType
DenseType
typedef DenseMatrixType Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::DenseType inherited
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
MatrixType
template<typename _MatrixType , unsigned int _Mode> typedef _MatrixType Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::MatrixType
Nested
typedef TriangularView< _MatrixType, _Mode > const& Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::Nested inherited
PlainObject
template<typename _MatrixType , unsigned int _Mode> typedef DenseMatrixType Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::PlainObject
Scalar
template<typename _MatrixType , unsigned int _Mode> typedef internal::traits<TriangularViewType>::Scalar Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::Scalar
StorageIndex
typedef internal::traits<TriangularView< _MatrixType, _Mode > >::StorageIndex Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::StorageIndex inherited
StorageKind
template<typename _MatrixType , unsigned int _Mode> typedef internal::traits<TriangularViewType>::StorageKind Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::StorageKind
TriangularViewType
template<typename _MatrixType , unsigned int _Mode> typedef TriangularView<_MatrixType, _Mode> Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::TriangularViewType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
         {
      Mode = internal::traits<Derived>::Mode,
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxSizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::MaxRowsAtCompileTime,
                                                   internal::traits<Derived>::MaxColsAtCompileTime>::ret)
    };
anonymous enum
template<typename _MatrixType , unsigned int _Mode> anonymous enum
Enumerator
Mode
Flags
         {
      Mode = _Mode,
      Flags = internal::traits<TriangularViewType>::Flags
    };
Member Function Documentation
_assignProduct()
template<typename _MatrixType , unsigned int _Mode> template<typename ProductType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::_assignProduct (const ProductType & prod, const Scalar & alpha, bool beta)
_solve_impl()
template<typename _MatrixType , unsigned int _Mode> template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::_solve_impl (const RhsType & rhs, DstType & dst) const inline
{
      if(!internal::is_same_dense(dst,rhs))
        dst = rhs;
      this->solveInPlace(dst);
    }
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
check_coordinates()
void Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::check_coordinates (Index row, Index col) const inline protected inherited
    {
      EIGEN_ONLY_USED_FOR_DEBUG(row);
      EIGEN_ONLY_USED_FOR_DEBUG(col);
      eigen_assert(col>=0 && col<cols() && row>=0 && row<rows());
      const int mode = int(Mode) & ~SelfAdjoint;
      EIGEN_ONLY_USED_FOR_DEBUG(mode);
      eigen_assert((mode==Upper && col>=row)
                || (mode==Lower && col<=row)
                || ((mode==StrictlyUpper || mode==UnitUpper) && col>row)
                || ((mode==StrictlyLower || mode==UnitLower) && col<row));
    }
check_coordinates_internal()
void Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::check_coordinates_internal (Index , Index) const inline protected inherited
{}
coeff()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC Scalar Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::coeff (Index row, Index col) const inline
See also
MatrixBase::coeff()
Warning
the coordinates must fit into the referenced triangular part
    {
      Base::check_coordinates_internal(row, col);
      return derived().nestedExpression().coeff(row, col);
    }
References col(), and row().
coeffRef()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC Scalar & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::coeffRef (Index row, Index col) inline
See also
MatrixBase::coeffRef()
Warning
the coordinates must fit into the referenced triangular part
    {
      EIGEN_STATIC_ASSERT_LVALUE(TriangularViewType);
      Base::check_coordinates_internal(row, col);
      return derived().nestedExpression().coeffRef(row, col);
    }
References col(), EIGEN_STATIC_ASSERT_LVALUE, and row().
cols()
EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::cols () const inline inherited
{ return derived().cols(); }
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
copyCoeff()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::copyCoeff (Index row, Index col, Other & other) inline inherited
See also
MatrixBase::copyCoeff(row,col)
    {
      derived().coeffRef(row, col) = other.coeff(row, col);
    }
derived() [1/2]
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC Derived & Eigen::TriangularBase< Derived >::derived () inline
{ return *static_cast<Derived*>(this); }
derived() [2/2]
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC const Derived & Eigen::TriangularBase< Derived >::derived () const inline
{ return *static_cast<const Derived*>(this); }
evalTo() [1/3]
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
Referenced by Eigen::EigenBase< Derived >::subTo().
evalTo() [2/3]
EIGEN_DEVICE_FUNC void Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::evalTo (MatrixBase< DenseDerived > & other) const inherited
evalTo() [3/3]
void Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::evalTo (MatrixBase< DenseDerived > & other) const inherited
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
{
  evalToLazy(other.derived());
}
evalToLazy() [1/2]
template<typename _MatrixType , unsigned int _Mode> template<typename DenseDerived > void Eigen::TriangularBase< Derived >::evalToLazy (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
{
  other.derived().resize(this->rows(), this->cols());
  internal::call_triangular_assignment_loop<Derived::Mode,(Derived::Mode&SelfAdjoint)==0 /* SetOpposite */>(other.derived(), derived().nestedExpression());
}
evalToLazy() [2/2]
template<typename _MatrixType , unsigned int _Mode> template<typename DenseDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularBase< Derived >::evalToLazy (MatrixBase< DenseDerived > & other) const
fill()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::fill (const Scalar & value) inline
See also
MatrixBase::fill()
{ setConstant(value); }
innerStride()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC Index Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::innerStride () const inline
Returns
the inner-stride of the underlying dense matrix
See also
DenseCoeffsBase::innerStride()
{ return derived().nestedExpression().innerStride(); }
lazyAssign() [1/2]
template<typename _MatrixType , unsigned int _Mode> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::lazyAssign (const MatrixBase< OtherDerived > & other)
lazyAssign() [2/2]
template<typename _MatrixType , unsigned int _Mode> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::lazyAssign (const TriangularBase< OtherDerived > & other)
operator()() [1/2]
EIGEN_DEVICE_FUNC Scalar & Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::operator() (Index row, Index col) inline inherited
    {
      check_coordinates(row, col);
      return coeffRef(row,col);
    }
operator()() [2/2]
EIGEN_DEVICE_FUNC Scalar Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::operator() (Index row, Index col) const inline inherited
    {
      check_coordinates(row, col);
      return coeff(row,col);
    }
operator*()
template<typename _MatrixType , unsigned int _Mode> template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product< TriangularViewType, OtherDerived > Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient triangular matrix times vector/matrix product
    {
      return Product<TriangularViewType,OtherDerived>(derived(), rhs.derived());
    }
operator*=()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator*= (const typename internal::traits< MatrixType >::Scalar & other) inline
See also
MatrixBase::operator*=()
{ return *this = derived().nestedExpression() * other; }
References Eigen::TriangularView< _MatrixType, _Mode >::nestedExpression().
operator+=()
template<typename _MatrixType , unsigned int _Mode> template<typename Other > EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator+= (const DenseBase< Other > & other) inline
See also
MatrixBase::operator+=()
{
      internal::call_assignment_no_alias(derived(), other.derived(), internal::add_assign_op<Scalar,typename Other::Scalar>());
      return derived();
    }
operator-=()
template<typename _MatrixType , unsigned int _Mode> template<typename Other > EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator-= (const DenseBase< Other > & other) inline
See also
MatrixBase::operator-=()
{
      internal::call_assignment_no_alias(derived(), other.derived(), internal::sub_assign_op<Scalar,typename Other::Scalar>());
      return derived();
    }
operator/=()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator/= (const typename internal::traits< MatrixType >::Scalar & other) inline
See also
DenseBase::operator/=()
{ return *this = derived().nestedExpression() / other; }
References Eigen::TriangularView< _MatrixType, _Mode >::nestedExpression().
operator=() [1/3]
template<typename _MatrixType , unsigned int _Mode> template<typename OtherDerived > EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator= (const MatrixBase< OtherDerived > & other)
Shortcut for
*this = other.other.triangularView<(*this)::Mode>()
operator=() [2/3]
template<typename _MatrixType , unsigned int _Mode> template<typename OtherDerived > EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator= (const TriangularBase< OtherDerived > & other)
Assigns a triangular matrix to a triangular part of a dense matrix
operator=() [3/3]
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::operator= (const TriangularViewImpl< _MatrixType, _Mode, Dense > & other) inline
    { return *this = other.derived().nestedExpression(); }
outerStride()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC Index Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::outerStride () const inline
Returns
the outer-stride of the underlying dense matrix
See also
DenseCoeffsBase::outerStride()
{ return derived().nestedExpression().outerStride(); }
resize()
void Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::resize (Index rows, Index cols) inline inherited
    {
      EIGEN_UNUSED_VARIABLE(rows);
      EIGEN_UNUSED_VARIABLE(cols);
      eigen_assert(rows==this->rows() && cols==this->cols());
    }
rows()
EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::rows () const inline inherited
{ return derived().rows(); }
setConstant()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::setConstant (const Scalar & value) inline
See also
MatrixBase::setConstant()
    { return *this = MatrixType::Constant(derived().rows(), derived().cols(), value); }
setOnes()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::setOnes () inline
See also
MatrixBase::setOnes()
{ return setConstant(Scalar(1)); }
setZero()
template<typename _MatrixType , unsigned int _Mode> EIGEN_DEVICE_FUNC TriangularViewType & Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::setZero () inline
See also
MatrixBase::setZero()
{ return setConstant(Scalar(0)); }
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
References Eigen::EigenBase< Derived >::cols(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
solve()
template<typename _MatrixType , unsigned int _Mode> template<int Side, typename Other > EIGEN_DEVICE_FUNC const internal::triangular_solve_retval< Side, TriangularViewType, Other > Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::solve (const MatrixBase< Other > & other) const inline
Returns
the product of the inverse of *this with other, *this being triangular.
This function computes the inverse-matrix matrix product inverse(*this) * other if Side==OnTheLeft (the default), or the right-inverse-multiply other * inverse(*this) if Side==OnTheRight.
Note that the template parameter Side can be ommitted, in which case Side==OnTheLeft
The matrix *this must be triangular and invertible (i.e., all the coefficients of the diagonal must be non zero). It works as a forward (resp. backward) substitution if *this is an upper (resp. lower) triangular matrix.
Example:
Output:
This function returns an expression of the inverse-multiply and can works in-place if it is assigned to the same matrix or vector other.
For users coming from BLAS, this function (and more specifically solveInPlace()) offer all the operations supported by the *TRSV and *TRSM BLAS routines.
See also
TriangularView::solveInPlace()
solveInPlace() [1/2]
template<typename _MatrixType , unsigned int _Mode> template<int Side, typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::solveInPlace (const MatrixBase< OtherDerived > & other) const
"in-place" version of TriangularView::solve() where the result is written in other
Warning
The parameter is only marked 'const' to make the C++ compiler accept a temporary expression here. This function will const_cast it, so constness isn't honored here.
Note that the template parameter Side can be ommitted, in which case Side==OnTheLeft
See TriangularView:solve() for the details.
solveInPlace() [2/2]
template<typename _MatrixType , unsigned int _Mode> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::solveInPlace (const MatrixBase< OtherDerived > & other) const inline
    { return solveInPlace<OnTheLeft>(other); }
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
swap() [1/2]
template<typename _MatrixType , unsigned int _Mode> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap (MatrixBase< OtherDerived > const & other) inline
(*this).swap(other.triangularView<(*this)::Mode>())
    {
      EIGEN_STATIC_ASSERT_LVALUE(OtherDerived);
      call_assignment(derived(), other.const_cast_derived(), internal::swap_assign_op<Scalar>());
    }
References EIGEN_STATIC_ASSERT_LVALUE.
swap() [2/2]
template<typename _MatrixType , unsigned int _Mode> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap (TriangularBase< OtherDerived > const & other) inline
Swaps the coefficients of the common triangular parts of two matrices
    {
      EIGEN_STATIC_ASSERT_LVALUE(OtherDerived);
      call_assignment(derived(), other.const_cast_derived(), internal::swap_assign_op<Scalar>());
    }
References Eigen::EigenBase< Derived >::const_cast_derived(), and EIGEN_STATIC_ASSERT_LVALUE.
toDenseMatrix()
EIGEN_DEVICE_FUNC DenseMatrixType Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >::toDenseMatrix () const inline inherited
    {
      DenseMatrixType res(rows(), cols());
      evalToLazy(res);
      return res;
    }
Friends And Related Symbol Documentation
operator*
template<typename _MatrixType , unsigned int _Mode> template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product< OtherDerived, TriangularViewType > operator* (const MatrixBase< OtherDerived > & lhs, const TriangularViewImpl< _MatrixType, _Mode, Dense > & rhs) friend
Efficient vector/matrix times triangular matrix product
    {
      return Product<OtherDerived,TriangularViewType>(lhs.derived(),rhs.derived());
    }
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/TriangularMatrix.h