Prusa Slicer: Slic3r::GUI::Config Namespace Reference
Slic3r::GUI::Config Namespace Reference
Classes
class Index
class Snapshot
class SnapshotDB
struct Version
Functions
static std::string reason_string (const Snapshot::Reason reason)
static void copy_config_dir_single_level (const boost::filesystem::path &path_src, const boost::filesystem::path &path_dst)
static void delete_existing_ini_files (const boost::filesystem::path &path)
const Snapshot * take_config_snapshot_report_error (const AppConfig &app_config, Snapshot::Reason reason, const std::string &comment)
bool take_config_snapshot_cancel_on_error (const AppConfig &app_config, Snapshot::Reason reason, const std::string &comment, const std::string &message, Snapshot const **psnapshot)
static int compare_prerelease (const char *p1, const char *p2)
char * left_trim (char *c)
char * right_trim (char *start)
std::string unquote_value (char *value, char *end, const std::string &path, int idx_line)
std::string unquote_version_comment (char *value, char *end, const std::string &path, int idx_line)
Variables
static constexpr auto snapshot_subdirs = { "print", "sla_print", "filament", "sla_material", "printer", "physical_printer", "vendor" }
Function Documentation
compare_prerelease()
static int Slic3r::GUI::Config::compare_prerelease (const char * p1, const char * p2) static
{
  for (;;) {
    char c1 = *p1 ++;
    char c2 = *p2 ++;
    bool a1 = std::isalpha(c1) && c1 != 0;
    bool a2 = std::isalpha(c2) && c2 != 0;
    if (a1) {
      if (a2) {
        if (c1 != c2)
          return (c1 < c2) ? -1 : 1;
      } else
        return 1;
    } else {
      if (a2)
        return -1;
      else
        return 0;
    }
  }
  // This shall never happen.
  return 0;
}
Referenced by Slic3r::GUI::Config::Version::is_slic3r_supported().
copy_config_dir_single_level()
static void Slic3r::GUI::Config::copy_config_dir_single_level (const boost::filesystem::path & path_src, const boost::filesystem::path & path_dst) static
{
    if (! boost::filesystem::is_directory(path_dst) &&
        ! boost::filesystem::create_directory(path_dst))
        throw Slic3r::RuntimeError(std::string("PrusaSlicer was unable to create a directory at ") + path_dst.string());
    for (auto &dir_entry : boost::filesystem::directory_iterator(path_src))
        if (Slic3r::is_ini_file(dir_entry))
            if (std::string error_message; copy_file(dir_entry.path().string(), (path_dst / dir_entry.path().filename()).string(), error_message, false) != SUCCESS)
                throw Slic3r::RuntimeError(format("Failed copying \"%1%\" to \"%2%\": %3%", path_src.string(), path_dst.string(), error_message));
}
References Slic3r::copy_file(), Slic3r::GUI::format(), Slic3r::is_ini_file(), and Slic3r::SUCCESS.
Referenced by Slic3r::GUI::Config::SnapshotDB::restore_snapshot(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
delete_existing_ini_files()
static void Slic3r::GUI::Config::delete_existing_ini_files (const boost::filesystem::path & path) static
{
    if (! boost::filesystem::is_directory(path))
      return;
    for (auto &dir_entry : boost::filesystem::directory_iterator(path))
        if (boost::filesystem::is_regular_file(dir_entry.status()) && boost::algorithm::iends_with(dir_entry.path().filename().string(), ".ini"))
        boost::filesystem::remove(dir_entry.path());
}
Referenced by Slic3r::GUI::Config::SnapshotDB::restore_snapshot().
left_trim()
char * Slic3r::GUI::Config::left_trim (char * c) inline
{
  for (; *c == ' ' || *c == '\t'; ++ c);
  return c;
}
Referenced by Slic3r::GUI::Config::Index::load().
reason_string()
static std::string Slic3r::GUI::Config::reason_string (const Snapshot::Reason reason) static
{
    switch (reason) {
    case Snapshot::SNAPSHOT_UPGRADE:
        return "upgrade";
    case Snapshot::SNAPSHOT_DOWNGRADE:
        return "downgrade";
    case Snapshot::SNAPSHOT_BEFORE_ROLLBACK:
        return "before_rollback";
    case Snapshot::SNAPSHOT_USER:
        return "user";
    case Snapshot::SNAPSHOT_UNKNOWN:
    default:
        return "unknown";
    }
}
References Slic3r::GUI::Config::Snapshot::SNAPSHOT_BEFORE_ROLLBACK, Slic3r::GUI::Config::Snapshot::SNAPSHOT_DOWNGRADE, Slic3r::GUI::Config::Snapshot::SNAPSHOT_UNKNOWN, Slic3r::GUI::Config::Snapshot::SNAPSHOT_UPGRADE, and Slic3r::GUI::Config::Snapshot::SNAPSHOT_USER.
Referenced by Slic3r::GUI::Config::Snapshot::save_ini().
right_trim()
char * Slic3r::GUI::Config::right_trim (char * start) inline
{
  char *end = start + strlen(start) - 1;
  for (; end >= start && (*end == ' ' || *end == '\t'); -- end);
  *(++ end) = 0;
  return end;
}
Referenced by Slic3r::GUI::Config::Index::load().
take_config_snapshot_cancel_on_error()
bool Slic3r::GUI::Config::take_config_snapshot_cancel_on_error (const AppConfig & app_config, Snapshot::Reason reason, const std::string & comment, const std::string & message, Snapshot const ** psnapshot)
{
    try {
        const Snapshot *snapshot = &SnapshotDB::singleton().take_snapshot(app_config, reason, comment);
        if (psnapshot)
            *psnapshot = snapshot;
        return true;
    } catch (std::exception &err) {
        RichMessageDialog dlg(static_cast<wxWindow*>(wxGetApp().mainframe),
            _L("PrusaSlicer has encountered an error while taking a configuration snapshot.") + "\n\n" + from_u8(err.what()) + "\n\n" + from_u8(message),
            _L("PrusaSlicer error"),
            wxYES_NO);
        dlg.SetYesNoLabels(_L("Continue"), _L("Abort"));
        return dlg.ShowModal() == wxID_YES;
    }
}
References _L, comment, Slic3r::GUI::from_u8(), Slic3r::GUI::Config::SnapshotDB::singleton(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
Referenced by Slic3r::GUI::GUI_App::add_config_menu(), Slic3r::GUI::GUI_App::check_older_app_config(), and Slic3r::PresetUpdater::priv::perform_updates().
take_config_snapshot_report_error()
const Snapshot * Slic3r::GUI::Config::take_config_snapshot_report_error (const AppConfig & app_config, Snapshot::Reason reason, const std::string & comment)
{
    try {
        return &SnapshotDB::singleton().take_snapshot(app_config, reason, comment);
    } catch (std::exception &err) {
        show_error(static_cast<wxWindow*>(wxGetApp().mainframe),
            _L("Taking a configuration snapshot failed.") + "\n\n" + from_u8(err.what()));
        return nullptr;
    }
}
References _L, comment, Slic3r::GUI::from_u8(), Slic3r::GUI::show_error(), Slic3r::GUI::Config::SnapshotDB::singleton(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
Referenced by Slic3r::GUI::GUI_App::add_config_menu().
unquote_value()
std::string Slic3r::GUI::Config::unquote_value (char * value, char * end, const std::string & path, int idx_line) inline
{
  std::string svalue;
  if (value == end) {
    // Empty string is a valid string.
  } else if (*value == '"') {
    if (++ value > -- end || *end != '"')
      throw file_parser_error("String not enquoted correctly", path, idx_line);
    *end = 0;
    if (! unescape_string_cstyle(value, svalue))
      throw file_parser_error("Invalid escape sequence inside a quoted string", path, idx_line);
  } else
    svalue.assign(value, end);
  return svalue;
}
References Slic3r::unescape_string_cstyle().
Referenced by Slic3r::GUI::Config::Index::load().
unquote_version_comment()
std::string Slic3r::GUI::Config::unquote_version_comment (char * value, char * end, const std::string & path, int idx_line) inline
{
  std::string svalue;
  if (value == end) {
    // Empty string is a valid string.
  } else if (*value == '"') {
    if (++ value > -- end || *end != '"')
      throw file_parser_error("Version comment not enquoted correctly", path, idx_line);
    *end = 0;
    if (! unescape_string_cstyle(value, svalue))
      throw file_parser_error("Invalid escape sequence inside a quoted version comment", path, idx_line);
  } else
    svalue.assign(value, end);
  return svalue;
}
References Slic3r::unescape_string_cstyle().
Referenced by Slic3r::GUI::Config::Index::load().
Variable Documentation
snapshot_subdirs
constexpr auto Slic3r::GUI::Config::snapshot_subdirs = { "print", "sla_print", "filament", "sla_material", "printer", "physical_printer", "vendor" } static constexpr
Referenced by Slic3r::GUI::Config::Snapshot::equal_to_active(), Slic3r::GUI::Config::SnapshotDB::restore_snapshot(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().