Prusa Slicer: Slic3r::UndoRedo::Interval Struct Reference
Slic3r::UndoRedo::Interval Struct Reference
Public Member Functions
Interval (size_t begin, size_t end)
size_t begin () const
size_t end () const
bool is_valid () const
bool strictly_before (const Interval &rhs) const
bool strictly_after (const Interval &rhs) const
bool operator< (const Interval &rhs) const
bool operator== (const Interval &rhs) const
void trim_begin (size_t new_begin)
void trim_end (size_t new_end)
void extend_begin (size_t new_begin)
void extend_end (size_t new_end)
size_t memsize () const
Private Attributes
size_t m_begin
size_t m_end
Detailed Description
Constructor & Destructor Documentation
Interval()
Slic3r::UndoRedo::Interval::Interval (size_t begin, size_t end) inline
: m_begin(begin), m_end(end) {}
Member Function Documentation
begin()
size_t Slic3r::UndoRedo::Interval::begin () const inline
{ return m_begin; }
References m_begin.
Referenced by Slic3r::UndoRedo::MutableHistoryInterval::begin().
end()
size_t Slic3r::UndoRedo::Interval::end () const inline
{ return m_end; }
References m_end.
Referenced by Slic3r::UndoRedo::MutableHistoryInterval::end().
extend_begin()
void Slic3r::UndoRedo::Interval::extend_begin (size_t new_begin) inline
{ assert(new_begin <= m_begin); m_begin = new_begin; }
References m_begin.
Referenced by Slic3r::UndoRedo::MutableHistoryInterval::extend_begin().
extend_end()
void Slic3r::UndoRedo::Interval::extend_end (size_t new_end) inline
{ assert(new_end >= m_end); m_end = new_end; }
References m_end.
Referenced by Slic3r::UndoRedo::MutableHistoryInterval::extend_end().
is_valid()
bool Slic3r::UndoRedo::Interval::is_valid () const inline
{ return m_begin >= 0 && m_begin < m_end; }
References m_begin, and m_end.
Referenced by strictly_after(), and strictly_before().
memsize()
size_t Slic3r::UndoRedo::Interval::memsize () const inline
{ return sizeof(this); }
operator<()
bool Slic3r::UndoRedo::Interval::operator< (const Interval & rhs) const inline
{ return (m_begin < rhs.m_begin) || (m_begin == rhs.m_begin && m_end < rhs.m_end); }
References m_begin, and m_end.
operator==()
bool Slic3r::UndoRedo::Interval::operator== (const Interval & rhs) const inline
{ return m_begin == rhs.m_begin && m_end == rhs.m_end; }
References m_begin, and m_end.
strictly_after()
bool Slic3r::UndoRedo::Interval::strictly_after (const Interval & rhs) const inline
{ return this->is_valid() && rhs.is_valid() && rhs.m_end <= m_begin; }
References is_valid(), m_begin, and m_end.
strictly_before()
bool Slic3r::UndoRedo::Interval::strictly_before (const Interval & rhs) const inline
{ return this->is_valid() && rhs.is_valid() && m_end <= rhs.m_begin; }
References is_valid(), m_begin, and m_end.
trim_begin()
void Slic3r::UndoRedo::Interval::trim_begin (size_t new_begin) inline
{ m_begin = std::max(m_begin, new_begin); }
References m_begin.
Referenced by Slic3r::UndoRedo::MutableHistoryInterval::trim_begin().
trim_end()
void Slic3r::UndoRedo::Interval::trim_end (size_t new_end) inline
{ m_end = std::min(m_end, new_end); }
References m_end.
Referenced by Slic3r::UndoRedo::MutableHistoryInterval::trim_end().
Member Data Documentation
m_begin
size_t Slic3r::UndoRedo::Interval::m_begin private
Referenced by begin(), extend_begin(), is_valid(), operator<(), operator==(), strictly_after(), strictly_before(), and trim_begin().
m_end
size_t Slic3r::UndoRedo::Interval::m_end private
Referenced by end(), extend_end(), is_valid(), operator<(), operator==(), strictly_after(), strictly_before(), and trim_end().
The documentation for this struct was generated from the following file:
src/slic3r/Utils/UndoRedo.cpp