Prusa Slicer: src/libigl/igl/opengl/glfw/Viewer.cpp File Reference
Viewer.cpp File Reference
#include "Viewer.h"
#include <chrono>
#include <thread>
#include <Eigen/LU>
#include "../gl.h"
#include <GLFW/glfw3.h>
#include <cmath>
#include <cstdio>
#include <sstream>
#include <iomanip>
#include <iostream>
#include <fstream>
#include <algorithm>
#include <limits>
#include <cassert>
#include <igl/project.h>
#include <igl/get_seconds.h>
#include <igl/readOBJ.h>
#include <igl/readOFF.h>
#include <igl/adjacency_list.h>
#include <igl/writeOBJ.h>
#include <igl/writeOFF.h>
#include <igl/massmatrix.h>
#include <igl/file_dialog_open.h>
#include <igl/file_dialog_save.h>
#include <igl/quat_mult.h>
#include <igl/axis_angle_to_quat.h>
#include <igl/trackball.h>
#include <igl/two_axis_valuator_fixed_up.h>
#include <igl/snap_to_canonical_view_quat.h>
#include <igl/unproject.h>
#include <igl/serialize.h>
Namespaces
namespace igl
namespace igl::opengl
namespace igl::opengl::glfw
Functions
static void glfw_mouse_press (GLFWwindow *window, int button, int action, int modifier)
static void glfw_error_callback (int error, const char *description)
static void glfw_char_mods_callback (GLFWwindow *window, unsigned int codepoint, int modifier)
static void glfw_key_callback (GLFWwindow *window, int key, int scancode, int action, int modifier)
static void glfw_window_size (GLFWwindow *window, int width, int height)
static void glfw_mouse_move (GLFWwindow *window, double x, double y)
static void glfw_mouse_scroll (GLFWwindow *window, double x, double y)
static void glfw_drop_callback (GLFWwindow *window, int count, const char **filenames)
Variables
static igl::opengl::glfw::Viewer * __viewer
static double highdpi = 1
static double scroll_x = 0
static double scroll_y = 0
Function Documentation
glfw_char_mods_callback()
static void glfw_char_mods_callback (GLFWwindow * window, unsigned int codepoint, int modifier) static
{
  __viewer->key_pressed(codepoint, modifier);
}
References __viewer, and igl::opengl::glfw::Viewer::key_pressed().
Referenced by igl::opengl::glfw::Viewer::launch_init().
glfw_drop_callback()
static void glfw_drop_callback (GLFWwindow * window, int count, const char ** filenames) static
{
}
Referenced by igl::opengl::glfw::Viewer::launch_init().
glfw_error_callback()
static void glfw_error_callback (int error, const char * description) static
{
  fputs(description, stderr);
}
Referenced by igl::opengl::glfw::Viewer::launch_init().
glfw_key_callback()
static void glfw_key_callback (GLFWwindow * window, int key, int scancode, int action, int modifier) static
{
  if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
    glfwSetWindowShouldClose(window, GL_TRUE);
  if (action == GLFW_PRESS)
    __viewer->key_down(key, modifier);
  else if(action == GLFW_RELEASE)
    __viewer->key_up(key, modifier);
}
References __viewer, GL_TRUE, igl::opengl::glfw::Viewer::key_down(), and igl::opengl::glfw::Viewer::key_up().
Referenced by igl::opengl::glfw::Viewer::launch_init().
glfw_mouse_move()
static void glfw_mouse_move (GLFWwindow * window, double x, double y) static
{
  __viewer->mouse_move(x*highdpi, y*highdpi);
}
References __viewer, highdpi, and igl::opengl::glfw::Viewer::mouse_move().
Referenced by igl::opengl::glfw::Viewer::launch_init().
glfw_mouse_press()
static void glfw_mouse_press (GLFWwindow * window, int button, int action, int modifier) static
{
  igl::opengl::glfw::Viewer::MouseButton mb;
  if (button == GLFW_MOUSE_BUTTON_1)
    mb = igl::opengl::glfw::Viewer::MouseButton::Left;
  else if (button == GLFW_MOUSE_BUTTON_2)
    mb = igl::opengl::glfw::Viewer::MouseButton::Right;
  else //if (button == GLFW_MOUSE_BUTTON_3)
    mb = igl::opengl::glfw::Viewer::MouseButton::Middle;
  if (action == GLFW_PRESS)
    __viewer->mouse_down(mb,modifier);
  else
    __viewer->mouse_up(mb,modifier);
}
References __viewer, igl::opengl::glfw::Viewer::Left, igl::opengl::glfw::Viewer::Middle, igl::opengl::glfw::Viewer::mouse_down(), igl::opengl::glfw::Viewer::mouse_up(), and igl::opengl::glfw::Viewer::Right.
Referenced by igl::opengl::glfw::Viewer::launch_init().
glfw_mouse_scroll()
static void glfw_mouse_scroll (GLFWwindow * window, double x, double y) static
{
  using namespace std;
  scroll_x += x;
  scroll_y += y;
  __viewer->mouse_scroll(y);
}
References __viewer, igl::opengl::glfw::Viewer::mouse_scroll(), scroll_x, and scroll_y.
Referenced by igl::opengl::glfw::Viewer::launch_init().
glfw_window_size()
static void glfw_window_size (GLFWwindow * window, int width, int height) static
{
  int w = width*highdpi;
  int h = height*highdpi;
  __viewer->post_resize(w, h);
}
References __viewer, highdpi, and igl::opengl::glfw::Viewer::post_resize().
Referenced by igl::opengl::glfw::Viewer::launch_init().
Variable Documentation
__viewer
igl::opengl::glfw::Viewer* __viewer static
Referenced by glfw_char_mods_callback(), glfw_key_callback(), glfw_mouse_move(), glfw_mouse_press(), glfw_mouse_scroll(), glfw_window_size(), and igl::opengl::glfw::Viewer::launch_init().
highdpi
double highdpi = 1 static
Referenced by igl::opengl::glfw::Viewer::draw(), glfw_mouse_move(), glfw_window_size(), igl::opengl::glfw::Viewer::launch_init(), and igl::opengl::glfw::Viewer::resize().
scroll_x
double scroll_x = 0 static
Referenced by glfw_mouse_scroll(), ImGui::SetScrollX(), ImGui::SetScrollX(), and ShowDemoWindowLayout().
scroll_y
double scroll_y = 0 static
Referenced by glfw_mouse_scroll(), ImGui::InputTextEx(), Slic3r::GUI::ImGuiWrapper::search_list(), ImGui::SetScrollY(), ImGui::SetScrollY(), and ShowDemoWindowLayout().