Prusa Slicer: Slic3r::GUI::Selection::VolumeCache Struct Reference
Slic3r::GUI::Selection::VolumeCache Struct Reference
Classes
struct TransformCache
Public Member Functions
VolumeCache ()=default
VolumeCache (const Geometry::Transformation &volume_transform, const Geometry::Transformation &instance_transform)
const Vec3d & get_volume_position () const
const Transform3d & get_volume_rotation_matrix () const
const Transform3d & get_volume_scale_matrix () const
const Transform3d & get_volume_mirror_matrix () const
const Transform3d & get_volume_full_matrix () const
const Geometry::Transformation & get_volume_transform () const
const Vec3d & get_instance_position () const
const Vec3d & get_instance_rotation () const
const Vec3d & get_instance_scaling_factor () const
const Vec3d & get_instance_mirror () const
const Transform3d & get_instance_rotation_matrix () const
const Transform3d & get_instance_scale_matrix () const
const Transform3d & get_instance_mirror_matrix () const
const Transform3d & get_instance_full_matrix () const
const Geometry::Transformation & get_instance_transform () const
Private Attributes
TransformCache m_volume
TransformCache m_instance
Detailed Description
Constructor & Destructor Documentation
VolumeCache() [1/2]
Slic3r::GUI::Selection::VolumeCache::VolumeCache () default
VolumeCache() [2/2]
Slic3r::GUI::Selection::VolumeCache::VolumeCache (const Geometry::Transformation & volume_transform, const Geometry::Transformation & instance_transform)
    : m_volume(volume_transform)
    , m_instance(instance_transform)
{
}
Member Function Documentation
get_instance_full_matrix()
const Transform3d & Slic3r::GUI::Selection::VolumeCache::get_instance_full_matrix () const inline
{ return m_instance.full_matrix; }
References Slic3r::GUI::Selection::VolumeCache::TransformCache::full_matrix, and m_instance.
get_instance_mirror()
const Vec3d & Slic3r::GUI::Selection::VolumeCache::get_instance_mirror () const inline
{ return m_instance.mirror; }
References m_instance, and Slic3r::GUI::Selection::VolumeCache::TransformCache::mirror.
get_instance_mirror_matrix()
const Transform3d & Slic3r::GUI::Selection::VolumeCache::get_instance_mirror_matrix () const inline
{ return m_instance.mirror_matrix; }
References m_instance, and Slic3r::GUI::Selection::VolumeCache::TransformCache::mirror_matrix.
get_instance_position()
const Vec3d & Slic3r::GUI::Selection::VolumeCache::get_instance_position () const inline
{ return m_instance.position; }
References m_instance, and Slic3r::GUI::Selection::VolumeCache::TransformCache::position.
get_instance_rotation()
const Vec3d & Slic3r::GUI::Selection::VolumeCache::get_instance_rotation () const inline
{ return m_instance.rotation; }
References m_instance, and Slic3r::GUI::Selection::VolumeCache::TransformCache::rotation.
get_instance_rotation_matrix()
const Transform3d & Slic3r::GUI::Selection::VolumeCache::get_instance_rotation_matrix () const inline
{ return m_instance.rotation_matrix; }
References m_instance, and Slic3r::GUI::Selection::VolumeCache::TransformCache::rotation_matrix.
get_instance_scale_matrix()
const Transform3d & Slic3r::GUI::Selection::VolumeCache::get_instance_scale_matrix () const inline
{ return m_instance.scale_matrix; }
References m_instance, and Slic3r::GUI::Selection::VolumeCache::TransformCache::scale_matrix.
Referenced by Slic3r::GUI::Selection::translate().
get_instance_scaling_factor()
const Vec3d & Slic3r::GUI::Selection::VolumeCache::get_instance_scaling_factor () const inline
{ return m_instance.scaling_factor; }
References m_instance, and Slic3r::GUI::Selection::VolumeCache::TransformCache::scaling_factor.
get_instance_transform()
const Geometry::Transformation & Slic3r::GUI::Selection::VolumeCache::get_instance_transform () const inline
{ return m_instance.transform; }
References m_instance, and Slic3r::GUI::Selection::VolumeCache::TransformCache::transform.
Referenced by Slic3r::GUI::Selection::reset_skew(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale_and_translate(), Slic3r::GUI::Selection::transform_instance_relative(), Slic3r::GUI::Selection::transform_volume_relative(), and Slic3r::GUI::Selection::translate().
get_volume_full_matrix()
const Transform3d & Slic3r::GUI::Selection::VolumeCache::get_volume_full_matrix () const inline
{ return m_volume.full_matrix; }
References Slic3r::GUI::Selection::VolumeCache::TransformCache::full_matrix, and m_volume.
get_volume_mirror_matrix()
const Transform3d & Slic3r::GUI::Selection::VolumeCache::get_volume_mirror_matrix () const inline
{ return m_volume.mirror_matrix; }
References m_volume, and Slic3r::GUI::Selection::VolumeCache::TransformCache::mirror_matrix.
get_volume_position()
const Vec3d & Slic3r::GUI::Selection::VolumeCache::get_volume_position () const inline
{ return m_volume.position; }
References m_volume, and Slic3r::GUI::Selection::VolumeCache::TransformCache::position.
get_volume_rotation_matrix()
const Transform3d & Slic3r::GUI::Selection::VolumeCache::get_volume_rotation_matrix () const inline
{ return m_volume.rotation_matrix; }
References m_volume, and Slic3r::GUI::Selection::VolumeCache::TransformCache::rotation_matrix.
get_volume_scale_matrix()
const Transform3d & Slic3r::GUI::Selection::VolumeCache::get_volume_scale_matrix () const inline
{ return m_volume.scale_matrix; }
References m_volume, and Slic3r::GUI::Selection::VolumeCache::TransformCache::scale_matrix.
get_volume_transform()
const Geometry::Transformation & Slic3r::GUI::Selection::VolumeCache::get_volume_transform () const inline
{ return m_volume.transform; }
References m_volume, and Slic3r::GUI::Selection::VolumeCache::TransformCache::transform.
Referenced by Slic3r::GUI::Selection::reset_skew(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale_and_translate(), Slic3r::GUI::Selection::transform_volume_relative(), and Slic3r::GUI::Selection::translate().
Member Data Documentation
m_instance
TransformCache Slic3r::GUI::Selection::VolumeCache::m_instance private
Referenced by get_instance_full_matrix(), get_instance_mirror(), get_instance_mirror_matrix(), get_instance_position(), get_instance_rotation(), get_instance_rotation_matrix(), get_instance_scale_matrix(), get_instance_scaling_factor(), and get_instance_transform().
m_volume
TransformCache Slic3r::GUI::Selection::VolumeCache::m_volume private
Referenced by get_volume_full_matrix(), get_volume_mirror_matrix(), get_volume_position(), get_volume_rotation_matrix(), get_volume_scale_matrix(), and get_volume_transform().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/Selection.hpp
src/slic3r/GUI/Selection.cpp