Prusa Slicer: Slic3r::GUI::Emboss::UpdateSurfaceVolumeJob Class Reference
Slic3r::GUI::Emboss::UpdateSurfaceVolumeJob Class Reference
Update text volume to use surface from object.
#include <src/slic3r/GUI/Jobs/EmbossJob.hpp>
Public Member Functions
UpdateSurfaceVolumeJob (UpdateSurfaceVolumeData &&input)
Cut Surface.
void process (Ctl &ctl) override
void finalize (bool canceled, std::exception_ptr &eptr) override
Private Attributes
UpdateSurfaceVolumeData m_input
TriangleMesh m_result
Detailed Description
Update text volume to use surface from object.
Constructor & Destructor Documentation
UpdateSurfaceVolumeJob()
UpdateSurfaceVolumeJob::UpdateSurfaceVolumeJob (UpdateSurfaceVolumeData && input)
Cut Surface.
    : m_input(std::move(input))
{
    assert(priv::check(m_input, true));
}
References priv::check(), and m_input.
Member Function Documentation
finalize()
void UpdateSurfaceVolumeJob::finalize (bool canceled, std::exception_ptr & eptr) override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (!priv::finalize(canceled, eptr, m_input))
        return;
    // when start using surface it is wanted to move text origin on surface of model
    // also when repeteadly move above surface result position should match
    Transform3d *tr = &m_input.text_tr;
    priv::update_volume(std::move(m_result), m_input, tr);
}
References priv::finalize(), m_input, m_result, Slic3r::GUI::Emboss::SurfaceVolumeData::text_tr, and priv::update_volume().
process()
void UpdateSurfaceVolumeJob::process (Ctl & ctl) override virtual
Implements Slic3r::GUI::Job.
{
    if (!priv::check(m_input))
        throw std::runtime_error("Bad input data for UseSurfaceJob.");
    // check cancelation of process
    auto was_canceled = [&ctl, &cancel = m_input.cancel]()->bool {
        if (cancel->load()) return true;
        return ctl.was_canceled();
    };
    m_result = priv::cut_surface(m_input, m_input, was_canceled);
}
References Slic3r::GUI::Emboss::DataBase::cancel, priv::check(), priv::cut_surface(), m_input, m_result, and Slic3r::GUI::Job::Ctl::was_canceled().
Member Data Documentation
m_input
UpdateSurfaceVolumeData Slic3r::GUI::Emboss::UpdateSurfaceVolumeJob::m_input private
Referenced by UpdateSurfaceVolumeJob(), finalize(), and process().
m_result
TriangleMesh Slic3r::GUI::Emboss::UpdateSurfaceVolumeJob::m_result private
Referenced by finalize(), and process().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/EmbossJob.hpp
src/slic3r/GUI/Jobs/EmbossJob.cpp