Prusa Slicer: Slic3r::OozePrevention Class Reference
Slic3r::OozePrevention Class Reference
#include <src/libslic3r/GCode.hpp>
Public Member Functions
OozePrevention ()
std::string pre_toolchange (GCode &gcodegen)
std::string post_toolchange (GCode &gcodegen)
Public Attributes
bool enable
Private Member Functions
int _get_temp (const GCode &gcodegen) const
Detailed Description
Constructor & Destructor Documentation
OozePrevention()
Slic3r::OozePrevention::OozePrevention () inline
: enable(false) {}
Member Function Documentation
_get_temp()
int Slic3r::OozePrevention::_get_temp (const GCode & gcodegen) const private
    {
        return (gcodegen.layer() == nullptr || gcodegen.layer()->id() == 0)
            ? gcodegen.config().first_layer_temperature.get_at(gcodegen.writer().extruder()->id())
            : gcodegen.config().temperature.get_at(gcodegen.writer().extruder()->id());
    }
References Slic3r::GCode::config(), Slic3r::GCodeWriter::extruder(), Slic3r::Extruder::id(), Slic3r::Layer::id(), Slic3r::GCode::layer(), and Slic3r::GCode::writer().
Referenced by post_toolchange(), and pre_toolchange().
post_toolchange()
std::string Slic3r::OozePrevention::post_toolchange (GCode & gcodegen)
    {
        return (gcodegen.config().standby_temperature_delta.value != 0) ?
            gcodegen.writer().set_temperature(this->_get_temp(gcodegen), true, gcodegen.writer().extruder()->id()) :
            std::string();
    }
References _get_temp(), Slic3r::GCode::config(), Slic3r::GCodeWriter::extruder(), Slic3r::Extruder::id(), Slic3r::GCodeWriter::set_temperature(), and Slic3r::GCode::writer().
Referenced by Slic3r::GCode::set_extruder().
pre_toolchange()
std::string Slic3r::OozePrevention::pre_toolchange (GCode & gcodegen)
    {
        std::string gcode;
        unsigned int extruder_id = gcodegen.writer().extruder()->id();
        const ConfigOptionIntsNullable& filament_idle_temp = gcodegen.config().idle_temperature;
        if (filament_idle_temp.is_nil(extruder_id)) {
            // There is no idle temperature defined in filament settings.
            // Use the delta value from print config.
            if (gcodegen.config().standby_temperature_delta.value != 0) {
                // we assume that heating is always slower than cooling, so no need to block
                gcode += gcodegen.writer().set_temperature
                (this->_get_temp(gcodegen) + gcodegen.config().standby_temperature_delta.value, false, extruder_id);
                gcode.pop_back();
                gcode += " ;cooldown\n"; // this is a marker for GCodeProcessor, so it can supress the commands when needed
            }
        } else {
            // Use the value from filament settings. That one is absolute, not delta.
            gcode += gcodegen.writer().set_temperature(filament_idle_temp.get_at(extruder_id), false, extruder_id);
            gcode.pop_back();
            gcode += " ;cooldown\n"; // this is a marker for GCodeProcessor, so it can supress the commands when needed
        }
        return gcode;
    }
References _get_temp(), Slic3r::GCode::config(), Slic3r::GCodeWriter::extruder(), Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::Extruder::id(), Slic3r::ConfigOptionIntsTempl< NULLABLE >::is_nil(), Slic3r::GCodeWriter::set_temperature(), and Slic3r::GCode::writer().
Referenced by Slic3r::GCode::set_extruder().
Member Data Documentation
enable
bool Slic3r::OozePrevention::enable
Referenced by Slic3r::DoExport::init_ooze_prevention(), Slic3r::GCode::process_layer(), and Slic3r::GCode::set_extruder().
The documentation for this class was generated from the following files:
src/libslic3r/GCode.hpp
src/libslic3r/GCode.cpp