Prusa Slicer: Slic3r::DoubleSlider Namespace Reference
Slic3r::DoubleSlider Namespace Reference
Classes
class Control
struct ExtrudersSequence
struct TickCode
class TickCodeInfo
Enumerations
enum SelectedSlider { ssUndef , ssLower , ssHigher }
enum FocusedItem {
fiNone , fiRevertIcon , fiOneLayerIcon , fiCogIcon ,
fiColorBand , fiActionIcon , fiLowerThumb , fiHigherThumb ,
fiSmartWipeTower , fiTick
}
enum ConflictType {
ctNone , ctModeConflict , ctMeaninglessColorChange , ctMeaninglessToolChange ,
ctRedundant
}
enum MouseAction {
maNone , maAddMenu , maEditMenu , maCogIconMenu ,
maForceColorEdit , maAddTick , maDeleteTick , maCogIconClick ,
maOneLayerIconClick , maRevertIconClick
}
enum DrawMode { dmRegular , dmSlaPrint , dmSequentialFffPrint , dmSequentialGCodeView }
enum LabelType { ltHeightWithLayer , ltHeight , ltEstimatedTime }
Functions
bool equivalent_areas (const double &bottom_area, const double &top_area)
wxDEFINE_EVENT (wxCUSTOMEVT_TICKSCHANGED, wxEvent)
static std::string gcode (Type type)
static wxString short_and_splitted_time (const std::string &time)
bool check_color_change (const PrintObject *object, size_t frst_layer_id, size_t layers_cnt, bool check_overhangs, std::function< bool(const Layer *)> break_condition)
static std::string get_new_color (const std::string &color)
static void upgrade_text_entry_dialog (wxTextEntryDialog *dlg, double min=-1.0, double max=-1.0)
static std::string get_custom_code (const std::string &code_in, double height)
static std::string get_pause_print_msg (const std::string &msg_in, double height)
static double get_value_to_jump (double active_value, double min_z, double max_z, DrawMode mode)
constexpr double epsilon ()
wxDECLARE_EVENT (wxCUSTOMEVT_TICKSCHANGED, wxEvent)
Variables
constexpr double min_delta_area = scale_(scale_(25))
constexpr double miscalculation = scale_(scale_(1))
Enumeration Type Documentation
ConflictType
enum Slic3r::DoubleSlider::ConflictType
Enumerator
ctNone
ctModeConflict
ctMeaninglessColorChange
ctMeaninglessToolChange
ctRedundant
{
    ctNone,
    ctModeConflict,
    ctMeaninglessColorChange,
    ctMeaninglessToolChange,
    ctRedundant
};
DrawMode
enum Slic3r::DoubleSlider::DrawMode
Enumerator
dmRegular
dmSlaPrint
dmSequentialFffPrint
dmSequentialGCodeView
{
    dmRegular,
    dmSlaPrint,
    dmSequentialFffPrint,
    dmSequentialGCodeView,
};
FocusedItem
enum Slic3r::DoubleSlider::FocusedItem
Enumerator
fiNone
fiRevertIcon
fiOneLayerIcon
fiCogIcon
fiColorBand
fiActionIcon
fiLowerThumb
fiHigherThumb
fiSmartWipeTower
fiTick
                 {
    fiNone,
    fiRevertIcon,
    fiOneLayerIcon,
    fiCogIcon,
    fiColorBand,
    fiActionIcon,
    fiLowerThumb,
    fiHigherThumb,
    fiSmartWipeTower,
    fiTick
};
LabelType
enum Slic3r::DoubleSlider::LabelType
Enumerator
ltHeightWithLayer
ltHeight
ltEstimatedTime
{
    ltHeightWithLayer,
    ltHeight,
    ltEstimatedTime,
};
MouseAction
enum Slic3r::DoubleSlider::MouseAction
Enumerator
maNone
maAddMenu
maEditMenu
maCogIconMenu
maForceColorEdit
maAddTick
maDeleteTick
maCogIconClick
maOneLayerIconClick
maRevertIconClick
{
    maNone,
    maAddMenu,                  // show "Add"  context menu for NOTexist active tick
    maEditMenu,                 // show "Edit" context menu for exist active tick
    maCogIconMenu,              // show context for "cog" icon
    maForceColorEdit,           // force color editing from colored band
    maAddTick,                  // force tick adding
    maDeleteTick,               // force tick deleting
    maCogIconClick,             // LeftMouseClick on "cog" icon
    maOneLayerIconClick,        // LeftMouseClick on "one_layer" icon
    maRevertIconClick,          // LeftMouseClick on "revert" icon
};
SelectedSlider
enum Slic3r::DoubleSlider::SelectedSlider
Enumerator
ssUndef
ssLower
ssHigher
                    {
    ssUndef,
    ssLower,
    ssHigher
};
Function Documentation
check_color_change()
bool Slic3r::DoubleSlider::check_color_change (const PrintObject * object, size_t frst_layer_id, size_t layers_cnt, bool check_overhangs, std::function< bool(const Layer *)> break_condition)
{
    double prev_area = area(object->get_layer(frst_layer_id)->lslices);
    bool detected = false;
    for (size_t i = frst_layer_id+1; i < layers_cnt; i++) {
        const Layer* layer = object->get_layer(i);
        double cur_area = area(layer->lslices);
        // check for overhangs
        if (check_overhangs && cur_area > prev_area && !equivalent_areas(prev_area, cur_area))
            break;
        // Check percent of the area decrease.
        // This value have to be more than min_delta_area and more then 10%
        if ((prev_area - cur_area > min_delta_area) && (cur_area / prev_area < 0.9)) {
            detected = true;
            if (break_condition(layer))
                break;
        }
        prev_area = cur_area;
    }
    return detected;
}
References Slic3r::area(), equivalent_areas(), Slic3r::PrintObject::get_layer(), Slic3r::Layer::lslices, and min_delta_area.
Referenced by Slic3r::DoubleSlider::Control::auto_color_change(), and Slic3r::GUI::Preview::update_layers_slider().
epsilon()
constexpr double Slic3r::DoubleSlider::epsilon () constexpr
{ return 0.0011; }
Referenced by Slic3r::DoubleSlider::Control::get_label(), Slic3r::DoubleSlider::Control::get_tick_from_value(), Slic3r::GUI::GCodeViewer::render_legend(), Slic3r::DoubleSlider::Control::Ruler::update(), Slic3r::GUI::Preview::update_layers_slider(), and upgrade_text_entry_dialog().
equivalent_areas()
bool Slic3r::DoubleSlider::equivalent_areas (const double & bottom_area, const double & top_area)
{
    return fabs(bottom_area - top_area) <= miscalculation;
}
References miscalculation.
Referenced by check_color_change(), and Slic3r::GUI::Preview::update_layers_slider().
gcode()
static std::string Slic3r::DoubleSlider::gcode (Type type) static
{
    const PrintConfig& config = GUI::wxGetApp().plater()->fff_print().config();
    switch (type) {
    case ColorChange: return config.color_change_gcode;
    case PausePrint:  return config.pause_print_gcode;
    case Template:    return config.template_custom_gcode;
    default:          return "";
    }
}
References Slic3r::CustomGCode::ColorChange, Slic3r::CustomGCode::PausePrint, and Slic3r::CustomGCode::Template.
Referenced by Slic3r::DoubleSlider::Control::add_code_as_tick(), Slic3r::DoubleSlider::Control::append_add_color_change_menu_item(), Slic3r::DoubleSlider::TickCodeInfo::edit_tick(), Slic3r::DoubleSlider::Control::get_tooltip(), and Slic3r::DoubleSlider::Control::show_add_context_menu().
get_custom_code()
static std::string Slic3r::DoubleSlider::get_custom_code (const std::string & code_in, double height) static
{
    wxString msg_text = _L("Enter custom G-code used on current layer") + ":";
    wxString msg_header = format_wxstr(_L("Custom G-code on current layer (%1% mm)."), height);
    // get custom gcode
    wxTextEntryDialog dlg(nullptr, msg_text, msg_header, code_in,
        wxTextEntryDialogStyle | wxTE_MULTILINE);
    upgrade_text_entry_dialog(&dlg);
    bool valid = true;
    std::string value;
    do {
        if (dlg.ShowModal() != wxID_OK)
            return "";
        value = into_u8(dlg.GetValue());
        valid = GUI::Tab::validate_custom_gcode("Custom G-code", value);
    } while (!valid);
    return value;
}
References _L, upgrade_text_entry_dialog(), and Slic3r::GUI::Tab::validate_custom_gcode().
Referenced by Slic3r::DoubleSlider::TickCodeInfo::add_tick(), and Slic3r::DoubleSlider::TickCodeInfo::edit_tick().
get_new_color()
static std::string Slic3r::DoubleSlider::get_new_color (const std::string & color) static
{
    wxColour clr(color);
    if (!clr.IsOk())
        clr = wxColour(0, 0, 0); // Don't set alfa to transparence
    auto data = new wxColourData();
    data->SetChooseFull(1);
    data->SetColour(clr);
    wxColourDialog dialog(nullptr, data);
    dialog.CenterOnParent();
    if (dialog.ShowModal() == wxID_OK)
        return dialog.GetColourData().GetColour().GetAsString(wxC2S_HTML_SYNTAX).ToStdString();
    return "";
}
Referenced by Slic3r::DoubleSlider::TickCodeInfo::edit_tick(), and Slic3r::DoubleSlider::TickCodeInfo::get_color_for_tick().
get_pause_print_msg()
static std::string Slic3r::DoubleSlider::get_pause_print_msg (const std::string & msg_in, double height) static
{
    wxString msg_text = _L("Enter short message shown on Printer display when a print is paused") + ":";
    wxString msg_header = format_wxstr(_L("Message for pause print on current layer (%1% mm)."), height);
    // get custom gcode
    wxTextEntryDialog dlg(nullptr, msg_text, msg_header, from_u8(msg_in),
        wxTextEntryDialogStyle);
    upgrade_text_entry_dialog(&dlg);
    if (dlg.ShowModal() != wxID_OK || dlg.GetValue().IsEmpty())
        return "";
    return into_u8(dlg.GetValue());
}
References _L, and upgrade_text_entry_dialog().
Referenced by Slic3r::DoubleSlider::TickCodeInfo::add_tick(), and Slic3r::DoubleSlider::TickCodeInfo::edit_tick().
get_value_to_jump()
static double Slic3r::DoubleSlider::get_value_to_jump (double active_value, double min_z, double max_z, DrawMode mode) static
{
    wxString msg_text = (mode == dmSequentialGCodeView) ? _L("Enter the move you want to jump to") + ":" : _L("Enter the height you want to jump to") + ":";
    wxString msg_header = (mode == dmSequentialGCodeView) ? _L("Jump to move") : _L("Jump to height");
    wxString msg_in = GUI::double_to_string(active_value);
    // get custom gcode
    wxTextEntryDialog dlg(nullptr, msg_text, msg_header, msg_in, wxTextEntryDialogStyle);
    upgrade_text_entry_dialog(&dlg, min_z, max_z);
    if (dlg.ShowModal() != wxID_OK || dlg.GetValue().IsEmpty())
        return -1.0;
    double value = -1.0;
    return dlg.GetValue().ToDouble(&value) ? value : -1.0;
}
References _L, dmSequentialGCodeView, Slic3r::GUI::double_to_string(), and upgrade_text_entry_dialog().
Referenced by Slic3r::DoubleSlider::Control::jump_to_value().
short_and_splitted_time()
static wxString Slic3r::DoubleSlider::short_and_splitted_time (const std::string & time) static
{
    // Parse the dhms time format.
    int days = 0;
    int hours = 0;
    int minutes = 0;
    int seconds = 0;
    if (time.find('d') != std::string::npos)
        ::sscanf(time.c_str(), "%dd %dh %dm %ds", &days, &hours, &minutes, &seconds);
    else if (time.find('h') != std::string::npos)
        ::sscanf(time.c_str(), "%dh %dm %ds", &hours, &minutes, &seconds);
    else if (time.find('m') != std::string::npos)
        ::sscanf(time.c_str(), "%dm %ds", &minutes, &seconds);
    else if (time.find('s') != std::string::npos)
        ::sscanf(time.c_str(), "%ds", &seconds);
    // Format the dhm time.
    auto get_d = [days]()   { return format(_u8L("%1%d"), days); };
    auto get_h = [hours]()  { return format(_u8L("%1%h"), hours); };
    auto get_m = [minutes](){ return format(_u8L("%1%m"), minutes); };
    auto get_s = [seconds](){ return format(_u8L("%1%s"), seconds); };
    if (days > 0)
        return format_wxstr("%1%%2%\n%3%", get_d(), get_h(), get_m());
    if (hours > 0) {
        if (hours < 10 && minutes < 10 && seconds < 10)
            return format_wxstr("%1%%2%%3%", get_h(), get_m(), get_s());
        if (hours > 10 && minutes > 10 && seconds > 10)
            return format_wxstr("%1%\n%2%\n%3%", get_h(), get_m(), get_s());
        if ((minutes < 10 && seconds > 10) || (minutes > 10 && seconds < 10))
            return format_wxstr("%1%\n%2%%3%", get_h(), get_m(), get_s());
        return format_wxstr("%1%%2%\n%3%", get_h(), get_m(), get_s());
    }
    if (minutes > 0) {
        if (minutes > 10 && seconds > 10)
            return format_wxstr("%1%\n%2%", get_m(), get_s());
        return format_wxstr("%1%%2%", get_m(), get_s());
    }
    return from_u8(get_s());
}
References _u8L, and Slic3r::format().
Referenced by Slic3r::DoubleSlider::Control::get_label().
upgrade_text_entry_dialog()
static void Slic3r::DoubleSlider::upgrade_text_entry_dialog (wxTextEntryDialog * dlg, double min = -1.0, double max = -1.0) static
{
    GUI::wxGetApp().UpdateDlgDarkUI(dlg);
    // detect TextCtrl and OK button
    wxTextCtrl* textctrl {nullptr};
    wxWindowList& dlg_items = dlg->GetChildren();
    for (auto item : dlg_items) {
        textctrl = dynamic_cast<wxTextCtrl*>(item);
        if (textctrl)
            break;
    }
    if (!textctrl)
        return;
    textctrl->SetInsertionPointEnd();
    wxButton* btn_OK = static_cast<wxButton*>(dlg->FindWindowById(wxID_OK));
    btn_OK->Bind(wxEVT_UPDATE_UI, [textctrl, min, max](wxUpdateUIEvent& evt)
    {
        bool disable = textctrl->IsEmpty();
        if (!disable && min >= 0.0 && max >= 0.0) {
            double value = -1.0;
            if (!textctrl->GetValue().ToDouble(&value))    // input value couldn't be converted to double
                disable = true;
            else
                disable = value < min - epsilon() || value > max + epsilon();       // is input value is out of valid range ?
        }
        evt.Enable(!disable);
    }, btn_OK->GetId());
}
References epsilon().
Referenced by get_custom_code(), get_pause_print_msg(), and get_value_to_jump().
wxDECLARE_EVENT()
Slic3r::DoubleSlider::wxDECLARE_EVENT (wxCUSTOMEVT_TICKSCHANGED , wxEvent)
wxDEFINE_EVENT()
Slic3r::DoubleSlider::wxDEFINE_EVENT (wxCUSTOMEVT_TICKSCHANGED , wxEvent)
Variable Documentation
min_delta_area
constexpr double Slic3r::DoubleSlider::min_delta_area = scale_(scale_(25)) constexpr
Referenced by check_color_change().
miscalculation
constexpr double Slic3r::DoubleSlider::miscalculation = scale_(scale_(1)) constexpr
Referenced by equivalent_areas().