Prusa Slicer: Slic3r::GUI::MsgUpdateSlic3r Class Reference
Slic3r::GUI::MsgUpdateSlic3r Class Reference
#include <src/slic3r/GUI/UpdateDialogs.hpp>
Public Member Functions
MsgUpdateSlic3r (const Semver &ver_current, const Semver &ver_online)
MsgUpdateSlic3r (MsgUpdateSlic3r &&)=delete
MsgUpdateSlic3r (const MsgUpdateSlic3r &)=delete
MsgUpdateSlic3r & operator= (MsgUpdateSlic3r &&)=delete
MsgUpdateSlic3r & operator= (const MsgUpdateSlic3r &)=delete
virtual ~MsgUpdateSlic3r ()
bool disable_version_check () const
void on_hyperlink (wxHyperlinkEvent &evt)
void SetButtonLabel (wxWindowID btn_id, const wxString &label, bool set_focus=false)
Protected Types
enum {
CONTENT_WIDTH = 70 , CONTENT_MAX_HEIGHT = 60 , BORDER = 30 , VERT_SPACING = 15 ,
HORIZ_SPACING = 5
}
Protected Member Functions
wxButton * add_button (wxWindowID btn_id, bool set_focus=false, const wxString &label=wxString())
wxButton * get_button (wxWindowID btn_id)
void apply_style (long style)
void finalize ()
Protected Attributes
wxFont boldfont
wxBoxSizer * content_sizer
wxBoxSizer * btn_sizer
wxStaticBitmap * logo
Private Attributes
wxCheckBox * cbox
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum protected inherited
Enumerator
CONTENT_WIDTH
CONTENT_MAX_HEIGHT
BORDER
VERT_SPACING
HORIZ_SPACING
       {
    CONTENT_WIDTH = 70,//50,
    CONTENT_MAX_HEIGHT = 60,
    BORDER = 30,
    VERT_SPACING = 15,
    HORIZ_SPACING = 5,
  };
Constructor & Destructor Documentation
MsgUpdateSlic3r() [1/3]
Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r (const Semver & ver_current, const Semver & ver_online)
  : MsgDialog(nullptr, _(L("Update available")), wxString::Format(_(L("New version of %s is available")), SLIC3R_APP_NAME))
{
  const bool dev_version = ver_online.prerelease() != nullptr;
  auto *versions = new wxFlexGridSizer(2, 0, VERT_SPACING);
  versions->Add(new wxStaticText(this, wxID_ANY, _(L("Current version:"))));
  versions->Add(new wxStaticText(this, wxID_ANY, ver_current.to_string()));
  versions->Add(new wxStaticText(this, wxID_ANY, _(L("New version:"))));
  versions->Add(new wxStaticText(this, wxID_ANY, ver_online.to_string()));
  content_sizer->Add(versions);
  content_sizer->AddSpacer(VERT_SPACING);
  if (dev_version) {
    const std::string url = (boost::format(URL_DEV) % ver_online.to_string()).str();
    const wxString url_wx = from_u8(url);
    auto *link = new wxHyperlinkCtrl(this, wxID_ANY, _(L("Changelog & Download")), url_wx);
    content_sizer->Add(link);
  } else {
    const auto lang_code = wxGetApp().current_language_code_safe().ToStdString();
    const std::string url_log = (boost::format(URL_CHANGELOG) % lang_code).str();
    const wxString url_log_wx = from_u8(url_log);
    auto *link_log = new wxHyperlinkCtrl(this, wxID_ANY, _(L("Open changelog page")), url_log_wx);
    link_log->Bind(wxEVT_HYPERLINK, &MsgUpdateSlic3r::on_hyperlink, this);
    content_sizer->Add(link_log);
    const std::string url_dw = (boost::format(URL_DOWNLOAD) % lang_code).str();
    const wxString url_dw_wx = from_u8(url_dw);
    auto *link_dw = new wxHyperlinkCtrl(this, wxID_ANY, _(L("Open download page")), url_dw_wx);
    link_dw->Bind(wxEVT_HYPERLINK, &MsgUpdateSlic3r::on_hyperlink, this);
    content_sizer->Add(link_dw);
  }
  content_sizer->AddSpacer(2*VERT_SPACING);
  cbox = new wxCheckBox(this, wxID_ANY, _(L("Don't notify about new releases any more")));
  content_sizer->Add(cbox);
  content_sizer->AddSpacer(VERT_SPACING);
  finalize();
}
References _, cbox, Slic3r::GUI::MsgDialog::content_sizer, Slic3r::GUI::MsgDialog::finalize(), Slic3r::GUI::from_u8(), L, on_hyperlink(), Slic3r::Semver::prerelease(), Slic3r::Semver::to_string(), Slic3r::GUI::URL_CHANGELOG, Slic3r::GUI::URL_DEV, Slic3r::GUI::URL_DOWNLOAD, and Slic3r::GUI::MsgDialog::VERT_SPACING.
MsgUpdateSlic3r() [2/3]
Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r (MsgUpdateSlic3r &&) delete
MsgUpdateSlic3r() [3/3]
Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r (const MsgUpdateSlic3r &) delete
~MsgUpdateSlic3r()
Slic3r::GUI::MsgUpdateSlic3r::~MsgUpdateSlic3r () virtual
{}
Member Function Documentation
add_button()
wxButton * Slic3r::GUI::MsgDialog::add_button (wxWindowID btn_id, bool set_focus = false, const wxString & label = wxString()) protected inherited
{
    wxButton* btn = new wxButton(this, btn_id, label);
    if (set_focus) {
        btn->SetFocus();
        // For non-MSW platforms SetFocus is not enought to use it as default, when the dialog is closed by ENTER
        // We have to set this button as the (permanently) default one in its dialog
        // See https://twitter.com/ZMelmed/status/1472678454168539146
        btn->SetDefault();
    }
    btn_sizer->Add(btn, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, HORIZ_SPACING);
    btn->Bind(wxEVT_BUTTON, [this, btn_id](wxCommandEvent&) { this->EndModal(btn_id); });
    return btn;
};
References Slic3r::GUI::MsgDialog::btn_sizer, Slic3r::GUI::MsgDialog::HORIZ_SPACING, and wxEVT_BUTTON.
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::MsgDialog::apply_style().
apply_style()
void Slic3r::GUI::MsgDialog::apply_style (long style) protected inherited
{
    if (style & wxOK)       add_button(wxID_OK, true);
    if (style & wxYES)      add_button(wxID_YES,   !(style & wxNO_DEFAULT));
    if (style & wxNO)       add_button(wxID_NO,     (style & wxNO_DEFAULT));
    if (style & wxCANCEL)   add_button(wxID_CANCEL, (style & wxCANCEL_DEFAULT));
    std::string icon_name = style & wxICON_WARNING        ? "exclamation" :
                            style & wxICON_INFORMATION    ? "info"        :
                            style & wxICON_QUESTION       ? "question"    : "PrusaSlicer";
    logo->SetBitmap(*get_bmp_bundle(icon_name, 64));
}
References Slic3r::GUI::MsgDialog::add_button(), get_bmp_bundle(), Slic3r::GUI::MsgDialog::logo, and style.
Referenced by Slic3r::GUI::MsgDialog::MsgDialog().
disable_version_check()
bool Slic3r::GUI::MsgUpdateSlic3r::disable_version_check () const
{
  return cbox->GetValue();
}
References cbox.
Referenced by Slic3r::PresetUpdater::slic3r_update_notify().
finalize()
void Slic3r::GUI::MsgDialog::finalize () protected inherited
{
    wxGetApp().UpdateDlgDarkUI(this);
    Fit();
    this->CenterOnParent();
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), MsgUpdateSlic3r(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
get_button()
wxButton * Slic3r::GUI::MsgDialog::get_button (wxWindowID btn_id) protected inherited
{
    return static_cast<wxButton*>(FindWindowById(btn_id, this));
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), and Slic3r::GUI::MsgDialog::SetButtonLabel().
on_hyperlink()
void Slic3r::GUI::MsgUpdateSlic3r::on_hyperlink (wxHyperlinkEvent & evt)
{
  wxGetApp().open_browser_with_warning_dialog(evt.GetURL());
}
Referenced by MsgUpdateSlic3r().
operator=() [1/2]
MsgUpdateSlic3r & Slic3r::GUI::MsgUpdateSlic3r::operator= (const MsgUpdateSlic3r &) delete
operator=() [2/2]
MsgUpdateSlic3r & Slic3r::GUI::MsgUpdateSlic3r::operator= (MsgUpdateSlic3r &&) delete
SetButtonLabel()
void Slic3r::GUI::MsgDialog::SetButtonLabel (wxWindowID btn_id, const wxString & label, bool set_focus = false) inherited
{
    if (wxButton* btn = get_button(btn_id)) {
        btn->SetLabel(label);
        if (set_focus)
            btn->SetFocus();
    }
}
References Slic3r::GUI::MsgDialog::get_button().
Referenced by Slic3r::GUI::GUI_App::check_older_app_config(), Slic3r::GUI::ObjectList::del_from_cut_object(), and Slic3r::GUI::Plater::priv::delete_object_from_model().
Member Data Documentation
boldfont
wxFont Slic3r::GUI::MsgDialog::boldfont protected inherited
Referenced by Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), and Slic3r::GUI::MsgUpdateForced::MsgUpdateForced().
btn_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::btn_sizer protected inherited
Referenced by Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::add_button().
cbox
wxCheckBox* Slic3r::GUI::MsgUpdateSlic3r::cbox private
Referenced by MsgUpdateSlic3r(), and disable_version_check().
content_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::content_sizer protected inherited
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), MsgUpdateSlic3r(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
logo
wxStaticBitmap* Slic3r::GUI::MsgDialog::logo protected inherited
Referenced by Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::apply_style().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UpdateDialogs.hpp
src/slic3r/GUI/UpdateDialogs.cpp