Prusa Slicer: TCB_SPAN_NAMESPACE_NAME Namespace Reference
TCB_SPAN_NAMESPACE_NAME Namespace Reference
Namespaces
namespace detail
Classes
class span
Typedefs
using byte = unsigned char
Functions
template<typename ElementType , std::size_t Extent>
constexpr span< ElementType, Extent > make_span (span< ElementType, Extent > s) noexcept
template<typename T , std::size_t N>
constexpr span< T, N > make_span (T(&arr)[N]) noexcept
template<typename T , std::size_t N>
TCB_SPAN_ARRAY_CONSTEXPR span< T, N > make_span (std::array< T, N > &arr) noexcept
template<typename T , std::size_t N>
TCB_SPAN_ARRAY_CONSTEXPR span< const T, N > make_span (const std::array< T, N > &arr) noexcept
template<typename Container >
constexpr span< typenamestd::remove_reference< decltype(*detail::data(std::declval< Container & >()))>::type make_span (Container &cont)
template<typename Container >
constexpr span< const typename Container::value_type > make_span (const Container &cont)
template<typename ElementType , std::size_t Extent>
span< const byte,((Extent==dynamic_extent) ? dynamic_extent :sizeof(ElementType) *Extent)> as_bytes (span< ElementType, Extent > s) noexcept
template<class ElementType , size_t Extent, typename std::enable_if<!std::is_const< ElementType >::value, int >::type = 0>
span< byte,((Extent==dynamic_extent) ? dynamic_extent :sizeof(ElementType) *Extent)> as_writable_bytes (span< ElementType, Extent > s) noexcept
template<std::size_t N, typename E , std::size_t S>
constexpr auto get (span< E, S > s) -> decltype(s[N])
Variables
TCB_SPAN_INLINE_VAR constexpr std::size_t dynamic_extent = SIZE_MAX
Typedef Documentation
byte
using TCB_SPAN_NAMESPACE_NAME::byte = typedef unsigned char
Function Documentation
as_bytes()
template<typename ElementType , std::size_t Extent> span< const byte,((Extent==dynamic_extent) ? dynamic_extent :sizeof(ElementType) *Extent)> TCB_SPAN_NAMESPACE_NAME::as_bytes (span< ElementType, Extent > s) noexcept
{
    return {reinterpret_cast<const byte*>(s.data()), s.size_bytes()};
}
References as_bytes().
Referenced by as_bytes().
as_writable_bytes()
template<class ElementType , size_t Extent, typename std::enable_if<!std::is_const< ElementType >::value, int >::type = 0> span< byte,((Extent==dynamic_extent) ? dynamic_extent :sizeof(ElementType) *Extent)> TCB_SPAN_NAMESPACE_NAME::as_writable_bytes (span< ElementType, Extent > s) noexcept
{
    return {reinterpret_cast<byte*>(s.data()), s.size_bytes()};
}
References as_writable_bytes().
Referenced by as_writable_bytes().
get()
template<std::size_t N, typename E , std::size_t S> constexpr auto TCB_SPAN_NAMESPACE_NAME::get (span< E, S > s) -> decltype(s[N]) constexpr
{
    return s[N];
}
References get().
Referenced by get().
make_span() [1/6]
template<typename Container > constexpr span< const typename Container::value_type > TCB_SPAN_NAMESPACE_NAME::make_span (const Container & cont) constexpr
{
    return {cont};
}
References make_span().
make_span() [2/6]
template<typename T , std::size_t N> TCB_SPAN_ARRAY_CONSTEXPR span< const T, N > TCB_SPAN_NAMESPACE_NAME::make_span (const std::array< T, N > & arr) noexcept
{
    return {arr};
}
References make_span().
make_span() [3/6]
template<typename Container > constexpr span< typenamestd::remove_reference< decltype(*detail::data(std::declval< Container & >()))>::type TCB_SPAN_NAMESPACE_NAME::make_span (Container & cont) constexpr
{
    return {cont};
}
References make_span().
make_span() [4/6]
template<typename ElementType , std::size_t Extent> constexpr span< ElementType, Extent > TCB_SPAN_NAMESPACE_NAME::make_span (span< ElementType, Extent > s) constexpr noexcept
{
    return s;
}
References make_span().
Referenced by make_span(), make_span(), make_span(), make_span(), make_span(), and make_span().
make_span() [5/6]
template<typename T , std::size_t N> TCB_SPAN_ARRAY_CONSTEXPR span< T, N > TCB_SPAN_NAMESPACE_NAME::make_span (std::array< T, N > & arr) noexcept
{
    return {arr};
}
References make_span().
make_span() [6/6]
template<typename T , std::size_t N> constexpr span< T, N > TCB_SPAN_NAMESPACE_NAME::make_span (T(&) arr[N]) constexpr noexcept
{
    return {arr};
}
References make_span().
Variable Documentation
dynamic_extent
TCB_SPAN_INLINE_VAR constexpr std::size_t TCB_SPAN_NAMESPACE_NAME::dynamic_extent = SIZE_MAX constexpr
Referenced by TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::span(), TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::subspan(), and TCB_SPAN_NAMESPACE_NAME::span< ElementType, Extent >::subspan().