Prusa Slicer: agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset > Class Template Reference
agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset > Class Template Reference
#include <src/agg/agg_pixfmt_gray.h>
Classes
struct pixel_type
Public Types
enum { num_components = 1 , pix_width = sizeof(value_type) * Step , pix_step = Step , pix_offset = Offset }
typedef pixfmt_gray_tag pixfmt_category
typedef RenBuf rbuf_type
typedef rbuf_type::row_data row_data
typedef Blender blender_type
typedef blender_type::color_type color_type
typedef int order_type
typedef color_type::value_type value_type
typedef color_type::calc_type calc_type
Public Member Functions
pixfmt_alpha_blend_gray (rbuf_type &rb)
void attach (rbuf_type &rb)
template<class PixFmt >
bool attach (PixFmt &pixf, int x1, int y1, int x2, int y2)
AGG_INLINE unsigned width () const
AGG_INLINE unsigned height () const
AGG_INLINE int stride () const
int8u * row_ptr (int y)
const int8u * row_ptr (int y) const
row_data row (int y) const
AGG_INLINE int8u * pix_ptr (int x, int y)
AGG_INLINE const int8u * pix_ptr (int x, int y) const
AGG_INLINE pixel_type * pix_value_ptr (int x, int y, unsigned len)
AGG_INLINE const pixel_type * pix_value_ptr (int x, int y) const
AGG_INLINE color_type pixel (int x, int y) const
AGG_INLINE void copy_pixel (int x, int y, const color_type &c)
AGG_INLINE void blend_pixel (int x, int y, const color_type &c, int8u cover)
AGG_INLINE void copy_hline (int x, int y, unsigned len, const color_type &c)
AGG_INLINE void copy_vline (int x, int y, unsigned len, const color_type &c)
void blend_hline (int x, int y, unsigned len, const color_type &c, int8u cover)
void blend_vline (int x, int y, unsigned len, const color_type &c, int8u cover)
void blend_solid_hspan (int x, int y, unsigned len, const color_type &c, const int8u *covers)
void blend_solid_vspan (int x, int y, unsigned len, const color_type &c, const int8u *covers)
void copy_color_hspan (int x, int y, unsigned len, const color_type *colors)
void copy_color_vspan (int x, int y, unsigned len, const color_type *colors)
void blend_color_hspan (int x, int y, unsigned len, const color_type *colors, const int8u *covers, int8u cover)
void blend_color_vspan (int x, int y, unsigned len, const color_type *colors, const int8u *covers, int8u cover)
template<class Function >
void for_each_pixel (Function f)
template<class GammaLut >
void apply_gamma_dir (const GammaLut &g)
template<class GammaLut >
void apply_gamma_inv (const GammaLut &g)
template<class RenBuf2 >
void copy_from (const RenBuf2 &from, int xdst, int ydst, int xsrc, int ysrc, unsigned len)
template<class SrcPixelFormatRenderer >
void blend_from_color (const SrcPixelFormatRenderer &from, const color_type &color, int xdst, int ydst, int xsrc, int ysrc, unsigned len, int8u cover)
template<class SrcPixelFormatRenderer >
void blend_from_lut (const SrcPixelFormatRenderer &from, const color_type *color_lut, int xdst, int ydst, int xsrc, int ysrc, unsigned len, int8u cover)
Static Public Member Functions
static AGG_INLINE pixel_type * pix_value_ptr (void *p)
static AGG_INLINE const pixel_type * pix_value_ptr (const void *p)
static AGG_INLINE void write_plain_color (void *p, color_type c)
static AGG_INLINE color_type read_plain_color (const void *p)
static AGG_INLINE void make_pix (int8u *p, const color_type &c)
Private Member Functions
AGG_INLINE void blend_pix (pixel_type *p, value_type v, value_type a, unsigned cover)
AGG_INLINE void blend_pix (pixel_type *p, value_type v, value_type a)
AGG_INLINE void blend_pix (pixel_type *p, const color_type &c, unsigned cover)
AGG_INLINE void blend_pix (pixel_type *p, const color_type &c)
AGG_INLINE void copy_or_blend_pix (pixel_type *p, const color_type &c, unsigned cover)
AGG_INLINE void copy_or_blend_pix (pixel_type *p, const color_type &c)
Private Attributes
rbuf_type * m_rbuf
Detailed Description
template<class Blender, class RenBuf, unsigned Step = 1, unsigned Offset = 0>
class agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >
Member Typedef Documentation
blender_type
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> typedef Blender agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blender_type
calc_type
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> typedef color_type::calc_type agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::calc_type
color_type
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> typedef blender_type::color_type agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::color_type
order_type
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> typedef int agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::order_type
pixfmt_category
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> typedef pixfmt_gray_tag agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixfmt_category
rbuf_type
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> typedef RenBuf agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::rbuf_type
row_data
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> typedef rbuf_type::row_data agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::row_data
value_type
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> typedef color_type::value_type agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::value_type
Member Enumeration Documentation
anonymous enum
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> anonymous enum
Enumerator
num_components
pix_width
pix_step
pix_offset
        {
            num_components = 1,
            pix_width = sizeof(value_type) * Step,
            pix_step = Step,
            pix_offset = Offset,
        };
Constructor & Destructor Documentation
pixfmt_alpha_blend_gray()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixfmt_alpha_blend_gray (rbuf_type & rb) inline explicit
                                                        :
            m_rbuf(&rb)
        {}
Member Function Documentation
apply_gamma_dir()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> template<class GammaLut > void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::apply_gamma_dir (const GammaLut & g) inline
        {
            for_each_pixel(apply_gamma_dir_gray<color_type, GammaLut>(g));
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::for_each_pixel().
apply_gamma_inv()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> template<class GammaLut > void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::apply_gamma_inv (const GammaLut & g) inline
        {
            for_each_pixel(apply_gamma_inv_gray<color_type, GammaLut>(g));
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::for_each_pixel().
attach() [1/2]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> template<class PixFmt > bool agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::attach (PixFmt & pixf, int x1, int y1, int x2, int y2) inline
        {
            rect_i r(x1, y1, x2, y2);
            if (r.clip(rect_i(0, 0, pixf.width()-1, pixf.height()-1)))
            {
                int stride = pixf.stride();
                m_rbuf->attach(pixf.pix_ptr(r.x1, stride < 0 ? r.y2 : r.y1),
                               (r.x2 - r.x1) + 1,
                               (r.y2 - r.y1) + 1,
                               stride);
                return true;
            }
            return false;
        }
References agg::rect_base< T >::clip(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::stride(), agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
attach() [2/2]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::attach (rbuf_type & rb) inline
{ m_rbuf = &rb; }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf.
blend_color_hspan()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_color_hspan (int x, int y, unsigned len, const color_type * colors, const int8u * covers, int8u cover) inline
        {
            pixel_type* p = pix_value_ptr(x, y, len);
            if (covers)
            {
                do
                {
                    copy_or_blend_pix(p, *colors++, *covers++);
                    p = p->next();
                }
                while (--len);
            }
            else
            {
                if (cover == cover_mask)
                {
                    do
                    {
                        copy_or_blend_pix(p, *colors++);
                        p = p->next();
                    }
                    while (--len);
                }
                else
                {
                    do
                    {
                        copy_or_blend_pix(p, *colors++, cover);
                        p = p->next();
                    }
                    while (--len);
                }
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_or_blend_pix(), agg::cover_mask, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::next(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr().
blend_color_vspan()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_color_vspan (int x, int y, unsigned len, const color_type * colors, const int8u * covers, int8u cover) inline
        {
            if (covers)
            {
                do
                {
                    copy_or_blend_pix(pix_value_ptr(x, y++, 1), *colors++, *covers++);
                }
                while (--len);
            }
            else
            {
                if (cover == cover_mask)
                {
                    do
                    {
                        copy_or_blend_pix(pix_value_ptr(x, y++, 1), *colors++);
                    }
                    while (--len);
                }
                else
                {
                    do
                    {
                        copy_or_blend_pix(pix_value_ptr(x, y++, 1), *colors++, cover);
                    }
                    while (--len);
                }
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_or_blend_pix(), agg::cover_mask, and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr().
blend_from_color()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> template<class SrcPixelFormatRenderer > void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_from_color (const SrcPixelFormatRenderer & from, const color_type & color, int xdst, int ydst, int xsrc, int ysrc, unsigned len, int8u cover) inline
        {
            typedef typename SrcPixelFormatRenderer::pixel_type src_pixel_type;
            typedef typename SrcPixelFormatRenderer::color_type src_color_type;
            if (const src_pixel_type* psrc = from.pix_value_ptr(xsrc, ysrc))
            {
                pixel_type* pdst = pix_value_ptr(xdst, ydst, len);
                do
                {
                    copy_or_blend_pix(pdst, color, src_color_type::scale_cover(cover, psrc->c[0]));
                    psrc = psrc->next();
                    pdst = pdst->next();
                }
                while (--len);
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_or_blend_pix(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::next(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr().
blend_from_lut()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> template<class SrcPixelFormatRenderer > void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_from_lut (const SrcPixelFormatRenderer & from, const color_type * color_lut, int xdst, int ydst, int xsrc, int ysrc, unsigned len, int8u cover) inline
        {
            typedef typename SrcPixelFormatRenderer::pixel_type src_pixel_type;
            if (const src_pixel_type* psrc = from.pix_value_ptr(xsrc, ysrc))
            {
                pixel_type* pdst = pix_value_ptr(xdst, ydst, len);
                do
                {
                    copy_or_blend_pix(pdst, color_lut[psrc->c[0]], cover);
                    psrc = psrc->next();
                    pdst = pdst->next();
                }
                while (--len);
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_or_blend_pix(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::next(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr().
blend_hline()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_hline (int x, int y, unsigned len, const color_type & c, int8u cover) inline
        {
            if (!c.is_transparent())
            {
                pixel_type* p = pix_value_ptr(x, y, len);
                if (c.is_opaque() && cover == cover_mask)
                {
                    do
                    {
                        p->set(c);
                        p = p->next();
                    }
                    while (--len);
                }
                else
                {
                    do
                    {
                        blend_pix(p, c, cover);
                        p = p->next();
                    }
                    while (--len);
                }
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix(), agg::cover_mask, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::next(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
blend_pix() [1/4]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix (pixel_type * p, const color_type & c) inline private
        {
            blender_type::blend_pix(p->c, c.v, c.a);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::c.
blend_pix() [2/4]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix (pixel_type * p, const color_type & c, unsigned cover) inline private
        {
            blender_type::blend_pix(p->c, c.v, c.a, cover);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::c.
blend_pix() [3/4]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix (pixel_type * p, value_type v, value_type a) inline private
        {
            blender_type::blend_pix(p->c, v, a);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::c.
blend_pix() [4/4]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix (pixel_type * p, value_type v, value_type a, unsigned cover) inline private
        {
            blender_type::blend_pix(p->c, v, a, cover);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::c.
Referenced by agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_hline(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_solid_hspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_solid_vspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_vline(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_or_blend_pix(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_or_blend_pix().
blend_pixel()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pixel (int x, int y, const color_type & c, int8u cover) inline
        {
            copy_or_blend_pix(pix_value_ptr(x, y, 1), c, cover);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_or_blend_pix(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr().
blend_solid_hspan()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_solid_hspan (int x, int y, unsigned len, const color_type & c, const int8u * covers) inline
        {
            if (!c.is_transparent())
            {
                pixel_type* p = pix_value_ptr(x, y, len);
                do
                {
                    if (c.is_opaque() && *covers == cover_mask)
                    {
                        p->set(c);
                    }
                    else
                    {
                        blend_pix(p, c, *covers);
                    }
                    p = p->next();
                    ++covers;
                }
                while (--len);
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix(), agg::cover_mask, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::next(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
blend_solid_vspan()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_solid_vspan (int x, int y, unsigned len, const color_type & c, const int8u * covers) inline
        {
            if (!c.is_transparent())
            {
                do
                {
                    pixel_type* p = pix_value_ptr(x, y++, 1);
                    if (c.is_opaque() && *covers == cover_mask)
                    {
                        p->set(c);
                    }
                    else
                    {
                        blend_pix(p, c, *covers);
                    }
                    ++covers;
                }
                while (--len);
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix(), agg::cover_mask, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
blend_vline()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_vline (int x, int y, unsigned len, const color_type & c, int8u cover) inline
        {
            if (!c.is_transparent())
            {
                if (c.is_opaque() && cover == cover_mask)
                {
                    do
                    {
                        pix_value_ptr(x, y++, 1)->set(c);
                    }
                    while (--len);
                }
                else
                {
                    do
                    {
                        blend_pix(pix_value_ptr(x, y++, 1), c, cover);
                    }
                    while (--len);
                }
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix(), agg::cover_mask, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
copy_color_hspan()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_color_hspan (int x, int y, unsigned len, const color_type * colors) inline
        {
            pixel_type* p = pix_value_ptr(x, y, len);
            do
            {
                p->set(*colors++);
                p = p->next();
            }
            while (--len);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::next(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
copy_color_vspan()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_color_vspan (int x, int y, unsigned len, const color_type * colors) inline
        {
            do
            {
                pix_value_ptr(x, y++, 1)->set(*colors++);
            }
            while (--len);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
copy_from()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> template<class RenBuf2 > void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_from (const RenBuf2 & from, int xdst, int ydst, int xsrc, int ysrc, unsigned len) inline
        {
            if (const int8u* p = from.row_ptr(ysrc))
            {
                memmove(m_rbuf->row_ptr(xdst, ydst, len) + xdst * pix_width,
                        p + xsrc * pix_width,
                        len * pix_width);
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf, and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_width.
copy_hline()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_hline (int x, int y, unsigned len, const color_type & c) inline
        {
            pixel_type* p = pix_value_ptr(x, y, len);
            do
            {
                p->set(c);
                p = p->next();
            }
            while(--len);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::next(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
copy_or_blend_pix() [1/2]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_or_blend_pix (pixel_type * p, const color_type & c) inline private
        {
            if (!c.is_transparent())
            {
                if (c.is_opaque())
                {
                    p->set(c);
                }
                else
                {
                    blend_pix(p, c);
                }
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
copy_or_blend_pix() [2/2]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_or_blend_pix (pixel_type * p, const color_type & c, unsigned cover) inline private
        {
            if (!c.is_transparent())
            {
                if (c.is_opaque() && cover == cover_mask)
                {
                    p->set(c);
                }
                else
                {
                    blend_pix(p, c, cover);
                }
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pix(), agg::cover_mask, and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
Referenced by agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_color_hspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_color_vspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_from_color(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_from_lut(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pixel().
copy_pixel()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_pixel (int x, int y, const color_type & c) inline
        {
            pix_value_ptr(x, y, 1)->set(c);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
copy_vline()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_vline (int x, int y, unsigned len, const color_type & c) inline
        {
            do
            {
                pix_value_ptr(x, y++, 1)->set(c);
            }
            while (--len);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
for_each_pixel()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> template<class Function > void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::for_each_pixel (Function f) inline
        {
            unsigned y;
            for (y = 0; y < height(); ++y)
            {
                row_data r = m_rbuf->row(y);
                if (r.ptr)
                {
                    unsigned len = r.x2 - r.x1 + 1;
                    pixel_type* p = pix_value_ptr(r.x1, y, len);
                    do
                    {
                        f(p->c);
                        p = p->next();
                    }
                    while (--len);
                }
            }
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::c, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::height(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::next(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr().
Referenced by agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::apply_gamma_dir(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::apply_gamma_inv().
height()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE unsigned agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::height () const inline
{ return m_rbuf->height(); }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf.
Referenced by agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::for_each_pixel().
make_pix()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> static AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::make_pix (int8u * p, const color_type & c) inline static
        {
            ((pixel_type*)p)->set(c);
        }
pix_ptr() [1/2]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE int8u * agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_ptr (int x, int y) inline
        {
            return m_rbuf->row_ptr(y) + sizeof(value_type) * (x * pix_step + pix_offset);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_offset, and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_step.
pix_ptr() [2/2]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE const int8u * agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_ptr (int x, int y) const inline
        {
            return m_rbuf->row_ptr(y) + sizeof(value_type) * (x * pix_step + pix_offset);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_offset, and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_step.
pix_value_ptr() [1/4]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> static AGG_INLINE const pixel_type * agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr (const void * p) inline static
        {
            return (const pixel_type*)((const value_type*)p + pix_offset);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_offset.
pix_value_ptr() [2/4]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE const pixel_type * agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr (int x, int y) const inline
        {
            int8u* p = m_rbuf->row_ptr(y);
            return p ? (pixel_type*)(p + sizeof(value_type) * (x * pix_step + pix_offset)) : 0;
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_offset, and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_step.
pix_value_ptr() [3/4]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE pixel_type * agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr (int x, int y, unsigned len) inline
        {
            return (pixel_type*)(m_rbuf->row_ptr(x, y, len) + sizeof(value_type) * (x * pix_step + pix_offset));
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf, agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_offset, and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_step.
Referenced by agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_color_hspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_color_vspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_from_color(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_from_lut(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_hline(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_pixel(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_solid_hspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_solid_vspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::blend_vline(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_color_hspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_color_vspan(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_hline(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_pixel(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_vline(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::for_each_pixel(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::read_plain_color(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::write_plain_color().
pix_value_ptr() [4/4]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> static AGG_INLINE pixel_type * agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr (void * p) inline static
        {
            return (pixel_type*)((value_type*)p + pix_offset);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_offset.
pixel()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE color_type agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel (int x, int y) const inline
        {
            if (const pixel_type* p = pix_value_ptr(x, y))
            {
                return p->get();
            }
            return color_type::no_color();
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr().
read_plain_color()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> static AGG_INLINE color_type agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::read_plain_color (const void * p) inline static
        {
            return pix_value_ptr(p)->get();
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::get(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr().
row()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> row_data agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::row (int y) const inline
{ return m_rbuf->row(y); }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf.
row_ptr() [1/2]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> int8u * agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::row_ptr (int y) inline
{ return m_rbuf->row_ptr(y); }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf.
row_ptr() [2/2]
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> const int8u * agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::row_ptr (int y) const inline
{ return m_rbuf->row_ptr(y); }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf.
stride()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE int agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::stride () const inline
{ return m_rbuf->stride(); }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf.
Referenced by agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::attach().
width()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> AGG_INLINE unsigned agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::width () const inline
{ return m_rbuf->width();  }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf.
write_plain_color()
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> static AGG_INLINE void agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::write_plain_color (void * p, color_type c) inline static
        {
            // Grayscale formats are implicitly premultiplied.
            c.premultiply();
            pix_value_ptr(p)->set(c);
        }
References agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pixel_type::set().
Member Data Documentation
m_rbuf
template<class Blender , class RenBuf , unsigned Step = 1, unsigned Offset = 0> rbuf_type* agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::m_rbuf private
Referenced by agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::attach(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::attach(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::copy_from(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::for_each_pixel(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::height(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_ptr(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_ptr(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::pix_value_ptr(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::row(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::row_ptr(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::row_ptr(), agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::stride(), and agg::pixfmt_alpha_blend_gray< Blender, RenBuf, Step, Offset >::width().
The documentation for this class was generated from the following file:
src/agg/agg_pixfmt_gray.h