Prusa Slicer: Slic3r::GUI::GLCanvas3D::Slope Class Reference
Slic3r::GUI::GLCanvas3D::Slope Class Reference
Public Member Functions
Slope (GLVolumeCollection &volumes)
void enable (bool enable)
bool is_enabled () const
void use (bool use)
bool is_used () const
void set_normal_angle (float angle_in_deg) const
Private Attributes
bool m_enabled { false }
GLVolumeCollection & m_volumes
Detailed Description
Constructor & Destructor Documentation
Slope()
Slic3r::GUI::GLCanvas3D::Slope::Slope (GLVolumeCollection & volumes) inline
: m_volumes(volumes) {}
Member Function Documentation
enable()
void Slic3r::GUI::GLCanvas3D::Slope::enable (bool enable) inline
{ m_enabled = enable; }
References enable(), and m_enabled.
Referenced by enable(), and Slic3r::GUI::GLCanvas3D::enable_slope().
is_enabled()
bool Slic3r::GUI::GLCanvas3D::Slope::is_enabled () const inline
{ return m_enabled; }
References m_enabled.
is_used()
bool Slic3r::GUI::GLCanvas3D::Slope::is_used () const inline
{ return m_volumes.is_slope_active(); }
References Slic3r::GLVolumeCollection::is_slope_active(), and m_volumes.
Referenced by Slic3r::GUI::GLCanvas3D::is_using_slope().
set_normal_angle()
void Slic3r::GUI::GLCanvas3D::Slope::set_normal_angle (float angle_in_deg) const inline
{
            m_volumes.set_slope_normal_z(-::cos(Geometry::deg2rad(90.0f - angle_in_deg)));
        }
References cos(), Slic3r::Geometry::deg2rad(), m_volumes, and Slic3r::GLVolumeCollection::set_slope_normal_z().
Referenced by Slic3r::GUI::GLCanvas3D::set_slope_normal_angle().
use()
void Slic3r::GUI::GLCanvas3D::Slope::use (bool use) inline
{ m_volumes.set_slope_active(m_enabled ? use : false); }
References m_enabled, m_volumes, Slic3r::GLVolumeCollection::set_slope_active(), and use().
Referenced by use(), and Slic3r::GUI::GLCanvas3D::use_slope().
Member Data Documentation
m_enabled
bool Slic3r::GUI::GLCanvas3D::Slope::m_enabled { false } private
Referenced by enable(), is_enabled(), and use().
m_volumes
GLVolumeCollection& Slic3r::GUI::GLCanvas3D::Slope::m_volumes private
Referenced by is_used(), set_normal_angle(), and use().
The documentation for this class was generated from the following file:
src/slic3r/GUI/GLCanvas3D.hpp