Prusa Slicer: src/avrdude/flip1.c File Reference
flip1.c File Reference
#include "ac_cfg.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <unistd.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "flip1.h"
#include "dfu.h"
#include "usbdevs.h"
Classes
struct flip1
struct flip1_cmd
struct flip1_cmd_header
struct flip1_prog_footer
Macros
#define FLIP1(pgm) ((struct flip1 *)(pgm->cookie))
#define FLIP1_CMD_PROG_START 0x01
#define FLIP1_CMD_DISPLAY_DATA 0x03
#define FLIP1_CMD_WRITE_COMMAND 0x04
#define FLIP1_CMD_READ_COMMAND 0x05
#define FLIP1_CMD_CHANGE_BASE_ADDRESS 0x06
#define FLIP1_READ_BOOTLOADER_VERSION { 0x00, 0x00 }
#define FLIP1_READ_DEVICE_BOOT_ID1 { 0x00, 0x01 }
#define FLIP1_READ_DEVICE_BOOT_ID2 { 0x00, 0x02 }
#define FLIP1_READ_MANUFACTURER_CODE { 0x01, 0x30 }
#define FLIP1_READ_FAMILY_CODE { 0x01, 0x31 }
#define FLIP1_READ_PRODUCT_NAME { 0x01, 0x60 }
#define FLIP1_READ_PRODUCT_REVISION { 0x01, 0x61 }
#define STATE_dfuERROR 10 /* bState; requires a DFU_CLRSTATUS */
#define LONG_DFU_TIMEOUT 10000 /* 10 s for program and erase */
Enumerations
enum flip1_mem_unit { FLIP1_MEM_UNIT_FLASH = 0x00 , FLIP1_MEM_UNIT_EEPROM = 0x01 , FLIP1_MEM_UNIT_UNKNOWN = -1 }
Functions
static int flip1_open (PROGRAMMER *pgm, char *port_spec)
static int flip1_initialize (PROGRAMMER *pgm, AVRPART *part)
static void flip1_close (PROGRAMMER *pgm)
static void flip1_enable (PROGRAMMER *pgm)
static void flip1_disable (PROGRAMMER *pgm)
static void flip1_display (PROGRAMMER *pgm, const char *prefix)
static int flip1_program_enable (PROGRAMMER *pgm, AVRPART *part)
static int flip1_chip_erase (PROGRAMMER *pgm, AVRPART *part)
static int flip1_read_byte (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem, unsigned long addr, unsigned char *value)
static int flip1_write_byte (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem, unsigned long addr, unsigned char value)
static int flip1_paged_load (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem, unsigned int page_size, unsigned int addr, unsigned int n_bytes)
static int flip1_paged_write (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem, unsigned int page_size, unsigned int addr, unsigned int n_bytes)
static int flip1_read_sig_bytes (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem)
static void flip1_setup (PROGRAMMER *pgm)
static void flip1_teardown (PROGRAMMER *pgm)
void flip1_initpgm (PROGRAMMER *pgm)
Variables
const char flip1_desc [] = "FLIP USB DFU protocol version 1 (doc7618)"
Class Documentation
flip1
struct flip1
Class Members
unsigned char boot_ver
struct dfu_dev * dfu
unsigned char part_rev
unsigned char part_sig[3]
unsigned char security_mode_flag
flip1_cmd
struct flip1_cmd
Class Members
unsigned char args[5]
unsigned char cmd
flip1_cmd_header
struct flip1_cmd_header
Class Members
unsigned char cmd
unsigned char end_addr[2]
unsigned char memtype
unsigned char padding[26]
unsigned char start_addr[2]
flip1_prog_footer
struct flip1_prog_footer
Class Members
unsigned char bcdversion[2]
unsigned char crc[4]
unsigned char device[2]
unsigned char ftr_length
unsigned char product[2]
unsigned char signature[3]
unsigned char vendor[2]
Macro Definition Documentation
FLIP1
#define FLIP1 (pgm) ((struct flip1 *)(pgm->cookie))
FLIP1_CMD_CHANGE_BASE_ADDRESS
#define FLIP1_CMD_CHANGE_BASE_ADDRESS 0x06
FLIP1_CMD_DISPLAY_DATA
#define FLIP1_CMD_DISPLAY_DATA 0x03
FLIP1_CMD_PROG_START
#define FLIP1_CMD_PROG_START 0x01
FLIP1_CMD_READ_COMMAND
#define FLIP1_CMD_READ_COMMAND 0x05
FLIP1_CMD_WRITE_COMMAND
#define FLIP1_CMD_WRITE_COMMAND 0x04
FLIP1_READ_BOOTLOADER_VERSION
#define FLIP1_READ_BOOTLOADER_VERSION { 0x00, 0x00 }
FLIP1_READ_DEVICE_BOOT_ID1
#define FLIP1_READ_DEVICE_BOOT_ID1 { 0x00, 0x01 }
FLIP1_READ_DEVICE_BOOT_ID2
#define FLIP1_READ_DEVICE_BOOT_ID2 { 0x00, 0x02 }
FLIP1_READ_FAMILY_CODE
#define FLIP1_READ_FAMILY_CODE { 0x01, 0x31 }
FLIP1_READ_MANUFACTURER_CODE
#define FLIP1_READ_MANUFACTURER_CODE { 0x01, 0x30 }
FLIP1_READ_PRODUCT_NAME
#define FLIP1_READ_PRODUCT_NAME { 0x01, 0x60 }
FLIP1_READ_PRODUCT_REVISION
#define FLIP1_READ_PRODUCT_REVISION { 0x01, 0x61 }
LONG_DFU_TIMEOUT
#define LONG_DFU_TIMEOUT 10000 /* 10 s for program and erase */
STATE_dfuERROR
#define STATE_dfuERROR 10 /* bState; requires a DFU_CLRSTATUS */
Enumeration Type Documentation
flip1_mem_unit
enum flip1_mem_unit
Enumerator
FLIP1_MEM_UNIT_FLASH
FLIP1_MEM_UNIT_EEPROM
FLIP1_MEM_UNIT_UNKNOWN
                    {
  FLIP1_MEM_UNIT_FLASH = 0x00,
  FLIP1_MEM_UNIT_EEPROM = 0x01,
  FLIP1_MEM_UNIT_UNKNOWN = -1
};
Function Documentation
flip1_chip_erase()
int flip1_chip_erase (PROGRAMMER * pgm, AVRPART * part) static
{
  return -1;
}
Referenced by flip1_initpgm().
flip1_close()
void flip1_close (PROGRAMMER * pgm) static
{
}
Referenced by flip1_initpgm().
flip1_disable()
void flip1_disable (PROGRAMMER * pgm) static
{
}
Referenced by flip1_initpgm().
flip1_display()
void flip1_display (PROGRAMMER * pgm, const char * prefix) static
{
}
Referenced by flip1_initpgm().
flip1_enable()
void flip1_enable (PROGRAMMER * pgm) static
{
}
Referenced by flip1_initpgm().
flip1_initialize()
int flip1_initialize (PROGRAMMER * pgm, AVRPART * part) static
{
  return -1;
}
Referenced by flip1_initpgm().
flip1_initpgm()
void flip1_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "flip1");
  /* Mandatory Functions */
  pgm->initialize       = flip1_initialize;
  pgm->enable           = flip1_enable;
  pgm->disable          = flip1_disable;
  pgm->display          = flip1_display;
  pgm->program_enable   = flip1_program_enable;
  pgm->chip_erase       = flip1_chip_erase;
  pgm->open             = flip1_open;
  pgm->close            = flip1_close;
  pgm->paged_load       = flip1_paged_load;
  pgm->paged_write      = flip1_paged_write;
  pgm->read_byte        = flip1_read_byte;
  pgm->write_byte       = flip1_write_byte;
  pgm->read_sig_bytes   = flip1_read_sig_bytes;
  pgm->setup            = flip1_setup;
  pgm->teardown         = flip1_teardown;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, flip1_chip_erase(), flip1_close(), flip1_disable(), flip1_display(), flip1_enable(), flip1_initialize(), flip1_open(), flip1_paged_load(), flip1_paged_write(), flip1_program_enable(), flip1_read_byte(), flip1_read_sig_bytes(), flip1_setup(), flip1_teardown(), flip1_write_byte(), programmer_t::initialize, programmer_t::open, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::program_enable, programmer_t::read_byte, programmer_t::read_sig_bytes, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
flip1_open()
int flip1_open (PROGRAMMER * pgm, char * port_spec) static
{
  fprintf(stderr, "%s: Error: No USB support in this compile of avrdude\n",
    progname);
  return -1;
}
References progname.
Referenced by flip1_initpgm().
flip1_paged_load()
int flip1_paged_load (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem, unsigned int page_size, unsigned int addr, unsigned int n_bytes) static
{
  return -1;
}
Referenced by flip1_initpgm().
flip1_paged_write()
int flip1_paged_write (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem, unsigned int page_size, unsigned int addr, unsigned int n_bytes) static
{
  return -1;
}
Referenced by flip1_initpgm().
flip1_program_enable()
int flip1_program_enable (PROGRAMMER * pgm, AVRPART * part) static
{
  return -1;
}
Referenced by flip1_initpgm().
flip1_read_byte()
int flip1_read_byte (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem, unsigned long addr, unsigned char * value) static
{
  return -1;
}
Referenced by flip1_initpgm().
flip1_read_sig_bytes()
int flip1_read_sig_bytes (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem) static
{
  return -1;
}
Referenced by flip1_initpgm().
flip1_setup()
void flip1_setup (PROGRAMMER * pgm) static
{
}
Referenced by flip1_initpgm().
flip1_teardown()
void flip1_teardown (PROGRAMMER * pgm) static
{
}
Referenced by flip1_initpgm().
flip1_write_byte()
int flip1_write_byte (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem, unsigned long addr, unsigned char value) static
{
  return -1;
}
Referenced by flip1_initpgm().
Variable Documentation
flip1_desc
const char flip1_desc[] = "FLIP USB DFU protocol version 1 (doc7618)"