Prusa Slicer: Slic3r::Semver Class Reference
Slic3r::Semver Class Reference
#include <src/libslic3r/Semver.hpp>
Classes
struct Major
struct Minor
struct Patch
Public Member Functions
Semver ()
Semver (int major, int minor, int patch, boost::optional< const std::string & > metadata, boost::optional< const std::string & > prerelease)
Semver (int major, int minor, int patch, const char *metadata=nullptr, const char *prerelease=nullptr)
Semver (const std::string &str)
Semver (Semver &&other)
Semver (const Semver &other)
Semver & operator= (Semver &&other)
Semver & operator= (const Semver &other)
~Semver ()
int maj () const
int min () const
int patch () const
const char * prerelease () const
const char * metadata () const
void set_maj (int maj)
void set_min (int min)
void set_patch (int patch)
void set_metadata (boost::optional< const std::string & > meta)
void set_metadata (const char *meta)
void set_prerelease (boost::optional< const std::string & > pre)
void set_prerelease (const char *pre)
bool operator< (const Semver &b) const
bool operator<= (const Semver &b) const
bool operator== (const Semver &b) const
bool operator!= (const Semver &b) const
bool operator>= (const Semver &b) const
bool operator> (const Semver &b) const
bool operator& (const Semver &b) const
bool operator^ (const Semver &b) const
bool in_range (const Semver &low, const Semver &high) const
bool valid () const
std::string to_string () const
Semver & operator+= (const Major &b)
Semver & operator+= (const Minor &b)
Semver & operator+= (const Patch &b)
Semver & operator-= (const Major &b)
Semver & operator-= (const Minor &b)
Semver & operator-= (const Patch &b)
Semver operator+ (const Major &b) const
Semver operator+ (const Minor &b) const
Semver operator+ (const Patch &b) const
Semver operator- (const Major &b) const
Semver operator- (const Minor &b) const
Semver operator- (const Patch &b) const
Static Public Member Functions
static boost::optional< Semver > parse (const std::string &str)
static const Semver zero ()
static const Semver inf ()
static const Semver invalid ()
Private Member Functions
Semver (semver_t ver)
Static Private Member Functions
static semver_t semver_zero ()
static char * strdup (const std::string &str)
Private Attributes
semver_t ver
Friends
std::ostream & operator<< (std::ostream &os, const Semver &self)
Detailed Description
Constructor & Destructor Documentation
Semver() [1/7]
Slic3r::Semver::Semver () inline
: ver(semver_zero()) {}
Referenced by inf(), invalid(), parse(), and zero().
Semver() [2/7]
Slic3r::Semver::Semver (int major, int minor, int patch, boost::optional< const std::string & > metadata, boost::optional< const std::string & > prerelease) inline
    : ver(semver_zero())
  {
    ver.major = major;
    ver.minor = minor;
    ver.patch = patch;
    set_metadata(metadata);
    set_prerelease(prerelease);
  }
References semver_version_s::major, metadata(), semver_version_s::minor, patch(), semver_version_s::patch, prerelease(), set_metadata(), set_prerelease(), and ver.
Semver() [3/7]
Slic3r::Semver::Semver (int major, int minor, int patch, const char * metadata = nullptr, const char * prerelease = nullptr) inline
    : ver(semver_zero())
  {
    ver.major = major;
    ver.minor = minor;
    ver.patch = patch;
    set_metadata(metadata);
    set_prerelease(prerelease);
  }
References semver_version_s::major, metadata(), semver_version_s::minor, patch(), semver_version_s::patch, prerelease(), set_metadata(), set_prerelease(), and ver.
Semver() [4/7]
Slic3r::Semver::Semver (const std::string & str) inline
                               : ver(semver_zero())
  {
    auto parsed = parse(str);
    if (! parsed) {
      throw Slic3r::RuntimeError(std::string("Could not parse version string: ") + str);
    }
    ver = parsed->ver;
    parsed->ver = semver_zero();
  }
References parse(), semver_zero(), and ver.
Semver() [5/7]
Slic3r::Semver::Semver (Semver && other) inline
: ver(other.ver) { other.ver = semver_zero(); }
References semver_zero().
Semver() [6/7]
Slic3r::Semver::Semver (const Semver & other) inline
: ver(::semver_copy(&other.ver)) {}
~Semver()
Slic3r::Semver::~Semver () inline
{ ::semver_free(&ver); }
References semver_free(), and ver.
Semver() [7/7]
Slic3r::Semver::Semver (semver_t ver) inline private
: ver(ver) {}
Member Function Documentation
in_range()
bool Slic3r::Semver::in_range (const Semver & low, const Semver & high) const inline
{ return low <= *this && *this <= high; }
Referenced by Slic3r::GUI::Config::Version::is_slic3r_supported().
inf()
static const Semver Slic3r::Semver::inf () inline static
  {
    static semver_t ver = { std::numeric_limits<int>::max(), std::numeric_limits<int>::max(), std::numeric_limits<int>::max(), nullptr, nullptr };
    return Semver(ver);
  }
References Semver(), and ver.
Referenced by Slic3r::PresetUpdater::config_update(), Slic3r::GUI::generate_html_row(), and valid().
invalid()
static const Semver Slic3r::Semver::invalid () inline static
  {
    static semver_t ver = { -1, 0, 0, nullptr, nullptr };
    return Semver(ver);
  }
References Semver(), and ver.
Referenced by Slic3r::GUI::Config::Snapshot::clear(), Slic3r::GUI::parse_version_string(), Slic3r::AppConfig::reset(), and valid().
maj()
int Slic3r::Semver::maj () const inline
{ return ver.major; }
References semver_version_s::major, and ver.
Referenced by Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), set_maj(), and Slic3r::GUI::should_dialog_be_shown().
metadata()
const char * Slic3r::Semver::metadata () const inline
{ return ver.metadata; }
References semver_version_s::metadata, and ver.
Referenced by Semver(), and Semver().
min()
int Slic3r::Semver::min () const inline
{ return ver.minor; }
References semver_version_s::minor, and ver.
Referenced by Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), set_min(), and Slic3r::GUI::should_dialog_be_shown().
operator!=()
bool Slic3r::Semver::operator!= (const Semver & b) const inline
{ return ::semver_compare(ver, b.ver) != 0; }
References ver.
operator&()
bool Slic3r::Semver::operator& (const Semver & b) const inline
{ return ::semver_satisfies_patch(ver, b.ver) != 0; }
References ver.
operator+() [1/3]
Semver Slic3r::Semver::operator+ (const Major & b) const inline
{ Semver res(*this); return res += b; }
operator+() [2/3]
Semver Slic3r::Semver::operator+ (const Minor & b) const inline
{ Semver res(*this); return res += b; }
operator+() [3/3]
Semver Slic3r::Semver::operator+ (const Patch & b) const inline
{ Semver res(*this); return res += b; }
operator+=() [1/3]
Semver & Slic3r::Semver::operator+= (const Major & b) inline
{ ver.major += b.i; return *this; }
References semver_version_s::major, and ver.
operator+=() [2/3]
Semver & Slic3r::Semver::operator+= (const Minor & b) inline
{ ver.minor += b.i; return *this; }
References semver_version_s::minor, and ver.
operator+=() [3/3]
Semver & Slic3r::Semver::operator+= (const Patch & b) inline
{ ver.patch += b.i; return *this; }
References semver_version_s::patch, and ver.
operator-() [1/3]
Semver Slic3r::Semver::operator- (const Major & b) const inline
{ Semver res(*this); return res -= b; }
operator-() [2/3]
Semver Slic3r::Semver::operator- (const Minor & b) const inline
{ Semver res(*this); return res -= b; }
operator-() [3/3]
Semver Slic3r::Semver::operator- (const Patch & b) const inline
{ Semver res(*this); return res -= b; }
operator-=() [1/3]
Semver & Slic3r::Semver::operator-= (const Major & b) inline
{ ver.major -= b.i; return *this; }
References semver_version_s::major, and ver.
operator-=() [2/3]
Semver & Slic3r::Semver::operator-= (const Minor & b) inline
{ ver.minor -= b.i; return *this; }
References semver_version_s::minor, and ver.
operator-=() [3/3]
Semver & Slic3r::Semver::operator-= (const Patch & b) inline
{ ver.patch -= b.i; return *this; }
References semver_version_s::patch, and ver.
operator<()
bool Slic3r::Semver::operator< (const Semver & b) const inline
{ return ::semver_compare(ver, b.ver) == -1; }
References ver.
operator<=()
bool Slic3r::Semver::operator<= (const Semver & b) const inline
{ return ::semver_compare(ver, b.ver) <= 0; }
References ver.
operator=() [1/2]
Semver & Slic3r::Semver::operator= (const Semver & other) inline
  {
    ::semver_free(&ver);
    ver = ::semver_copy(&other.ver);
    return *this;
  }
References semver_copy(), semver_free(), and ver.
operator=() [2/2]
Semver & Slic3r::Semver::operator= (Semver && other) inline
  {
    ::semver_free(&ver);
    ver = other.ver;
    other.ver = semver_zero();
    return *this;
  }
References semver_free(), semver_zero(), and ver.
operator==()
bool Slic3r::Semver::operator== (const Semver & b) const inline
{ return ::semver_compare(ver, b.ver) == 0; }
References ver.
operator>()
bool Slic3r::Semver::operator> (const Semver & b) const inline
{ return ::semver_compare(ver, b.ver) == 1; }
References ver.
operator>=()
bool Slic3r::Semver::operator>= (const Semver & b) const inline
{ return ::semver_compare(ver, b.ver) >= 0; }
References ver.
operator^()
bool Slic3r::Semver::operator^ (const Semver & b) const inline
{ return ::semver_satisfies_caret(ver, b.ver) != 0; }
References ver.
parse()
static boost::optional< Semver > Slic3r::Semver::parse (const std::string & str) inline static
  {
    semver_t ver = semver_zero();
    if (::semver_parse(str.c_str(), &ver) == 0) {
      return Semver(ver);
    } else {
      return boost::none;
    }
  }
References Semver(), semver_parse(), semver_zero(), and ver.
Referenced by Semver(), Slic3r::GUI::GUI_App::app_updater(), Slic3r::GUI::Config::Index::load(), Slic3r::AppConfig::load(), Slic3r::GUI::Config::Snapshot::load_ini(), Slic3r::GUI::GUI_App::on_init_inner(), Slic3r::GUI::GUI_App::on_version_read(), Slic3r::GUI::parse_semver_from_ini(), Slic3r::AppUpdater::priv::parse_version_string(), and Slic3r::PresetUpdater::slic3r_update_notify().
patch()
int Slic3r::Semver::patch () const inline
{ return ver.patch; }
References semver_version_s::patch, and ver.
Referenced by Semver(), Semver(), and set_patch().
prerelease()
const char * Slic3r::Semver::prerelease () const inline
{ return ver.prerelease; }
References semver_version_s::prerelease, and ver.
Referenced by Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), Semver(), Semver(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Config::Version::is_slic3r_supported(), and Slic3r::GUI::should_dialog_be_shown().
semver_zero()
static semver_t Slic3r::Semver::semver_zero () inline static private
{ return { 0, 0, 0, nullptr, nullptr }; }
Referenced by Semver(), Semver(), operator=(), parse(), and zero().
set_maj()
void Slic3r::Semver::set_maj (int maj) inline
{ ver.major = maj; }
References maj(), semver_version_s::major, and ver.
set_metadata() [1/2]
void Slic3r::Semver::set_metadata (boost::optional< const std::string & > meta) inline
    {
        if (ver.metadata)
            free(ver.metadata);
        ver.metadata = meta ? strdup(*meta) : nullptr;
    }
References free(), semver_version_s::metadata, strdup(), and ver.
Referenced by Semver(), Semver(), and Slic3r::AppConfig::load().
set_metadata() [2/2]
void Slic3r::Semver::set_metadata (const char * meta) inline
    {
        if (ver.metadata)
            free(ver.metadata);
        ver.metadata = meta ? strdup(meta) : nullptr;
    }
References free(), semver_version_s::metadata, strdup(), and ver.
set_min()
void Slic3r::Semver::set_min (int min) inline
{ ver.minor = min; }
References min(), semver_version_s::minor, and ver.
set_patch()
void Slic3r::Semver::set_patch (int patch) inline
{ ver.patch = patch; }
References patch(), semver_version_s::patch, and ver.
set_prerelease() [1/2]
void Slic3r::Semver::set_prerelease (boost::optional< const std::string & > pre) inline
    {
        if (ver.prerelease)
            free(ver.prerelease);
        ver.prerelease = pre ? strdup(*pre) : nullptr;
    }
References free(), semver_version_s::prerelease, strdup(), and ver.
Referenced by Semver(), and Semver().
set_prerelease() [2/2]
void Slic3r::Semver::set_prerelease (const char * pre) inline
    {
        if (ver.prerelease)
            free(ver.prerelease);
        ver.prerelease = pre ? strdup(pre) : nullptr;
    }
References free(), semver_version_s::prerelease, strdup(), and ver.
strdup()
static char * Slic3r::Semver::strdup (const std::string & str) inline static private
{ return ::semver_strdup(str.data()); }
Referenced by set_metadata(), set_metadata(), set_prerelease(), and set_prerelease().
to_string()
std::string Slic3r::Semver::to_string () const inline
{
    auto res = (boost::format("%1%.%2%.%3%") % ver.major % ver.minor % ver.patch).str();
    if (ver.prerelease != nullptr) { res += '-'; res += ver.prerelease; }
    if (ver.metadata != nullptr)   { res += '+'; res += ver.metadata; }
    return res;
  }
References semver_version_s::major, semver_version_s::metadata, semver_version_s::minor, semver_version_s::patch, semver_version_s::prerelease, and ver.
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), Slic3r::GUI::GUI_App::check_older_app_config(), Slic3r::GUI::generate_html_row(), Slic3r::PresetUpdater::priv::get_config_updates(), Slic3r::AppUpdater::priv::parse_version_string(), Slic3r::GUI::Config::Snapshot::save_ini(), Slic3r::PresetUpdater::priv::sync_config(), and Slic3r::GUI::Tab::update_preset_description_line().
valid()
bool Slic3r::Semver::valid () const inline
{ return *this != zero() && *this != inf() && *this != invalid(); }
References inf(), invalid(), and zero().
Referenced by Slic3r::GUI::GUI_App::on_init_inner(), and Slic3r::VendorProfile::valid().
zero()
static const Semver Slic3r::Semver::zero () inline static
{ return Semver(semver_zero()); }
References Semver(), and semver_zero().
Referenced by Slic3r::PresetUpdater::config_update(), Slic3r::PresetUpdater::install_bundles_rsrc_or_cache_vendor(), valid(), and Slic3r::GUI::Config::Index::version().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Semver & self) friend
{
    os << self.to_string();
    return os;
  }
Member Data Documentation
ver
semver_t Slic3r::Semver::ver private
Referenced by Semver(), Semver(), Semver(), ~Semver(), inf(), invalid(), maj(), metadata(), min(), operator!=(), operator&(), operator+=(), operator+=(), operator+=(), operator-=(), operator-=(), operator-=(), operator<(), operator<=(), operator=(), operator=(), operator==(), operator>(), operator>=(), operator^(), parse(), patch(), prerelease(), set_maj(), set_metadata(), set_metadata(), set_min(), set_patch(), set_prerelease(), set_prerelease(), and to_string().
The documentation for this class was generated from the following file:
src/libslic3r/Semver.hpp