Prusa Slicer: Slic3r::GUI::I18N Namespace Reference
Slic3r::GUI::I18N Namespace Reference
Functions
wxString translate (const char *s)
wxString translate (const wchar_t *s)
wxString translate (const std::string &s)
wxString translate (const std::wstring &s)
wxString translate (const wxString &s)
wxString translate (const char *s, const char *plural, unsigned int n)
wxString translate (const wchar_t *s, const wchar_t *plural, unsigned int n)
wxString translate (const std::string &s, const std::string &plural, unsigned int n)
wxString translate (const std::wstring &s, const std::wstring &plural, unsigned int n)
wxString translate (const wxString &s, const wxString &plural, unsigned int n)
std::string translate_utf8 (const char *s)
std::string translate_utf8 (const wchar_t *s)
std::string translate_utf8 (const std::string &s)
std::string translate_utf8 (const std::wstring &s)
std::string translate_utf8 (const wxString &s)
std::string translate_utf8 (const char *s, const char *plural, unsigned int n)
std::string translate_utf8 (const wchar_t *s, const wchar_t *plural, unsigned int n)
std::string translate_utf8 (const std::string &s, const std::string &plural, unsigned int n)
std::string translate_utf8 (const std::wstring &s, const std::wstring &plural, unsigned int n)
std::string translate_utf8 (const wxString &s, const wxString &plural, unsigned int n)
wxString translate (const char *s, const char *ctx)
wxString translate (const wchar_t *s, const char *ctx)
wxString translate (const std::string &s, const char *ctx)
wxString translate (const std::wstring &s, const char *ctx)
wxString translate (const wxString &s, const char *ctx)
std::string translate_utf8 (const char *s, const char *ctx)
std::string translate_utf8 (const wchar_t *s, const char *ctx)
std::string translate_utf8 (const std::string &s, const char *ctx)
std::string translate_utf8 (const std::wstring &s, const char *ctx)
std::string translate_utf8 (const wxString &s, const char *ctx)
Function Documentation
translate() [1/15]
wxString Slic3r::GUI::I18N::translate (const char * s) inline
{ return wxGetTranslation(wxString(s, wxConvUTF8)); }
Referenced by translate_utf8(), translate_utf8(), translate_utf8(), translate_utf8(), and translate_utf8().
translate() [2/15]
wxString Slic3r::GUI::I18N::translate (const char * s, const char * ctx) inline
{ return _wxGetTranslation_ctx(wxString(s, wxConvUTF8), ctx); }
References _wxGetTranslation_ctx.
translate() [3/15]
wxString Slic3r::GUI::I18N::translate (const char * s, const char * plural, unsigned int n) inline
{ return wxGetTranslation(wxString(s, wxConvUTF8), wxString(plural, wxConvUTF8), n); }
translate() [4/15]
wxString Slic3r::GUI::I18N::translate (const std::string & s) inline
{ return wxGetTranslation(wxString(s.c_str(), wxConvUTF8)); }
translate() [5/15]
wxString Slic3r::GUI::I18N::translate (const std::string & s, const char * ctx) inline
{ return _wxGetTranslation_ctx(wxString(s.c_str(), wxConvUTF8), ctx); }
References _wxGetTranslation_ctx.
translate() [6/15]
wxString Slic3r::GUI::I18N::translate (const std::string & s, const std::string & plural, unsigned int n) inline
{ return wxGetTranslation(wxString(s.c_str(), wxConvUTF8), wxString(plural.c_str(), wxConvUTF8), n); }
translate() [7/15]
wxString Slic3r::GUI::I18N::translate (const std::wstring & s) inline
{ return wxGetTranslation(s.c_str()); }
translate() [8/15]
wxString Slic3r::GUI::I18N::translate (const std::wstring & s, const char * ctx) inline
{ return _wxGetTranslation_ctx(s.c_str(), ctx); }
References _wxGetTranslation_ctx.
translate() [9/15]
wxString Slic3r::GUI::I18N::translate (const std::wstring & s, const std::wstring & plural, unsigned int n) inline
{ return wxGetTranslation(s.c_str(), plural.c_str(), n); }
translate() [10/15]
wxString Slic3r::GUI::I18N::translate (const wchar_t * s) inline
{ return wxGetTranslation(s); }
translate() [11/15]
wxString Slic3r::GUI::I18N::translate (const wchar_t * s, const char * ctx) inline
{ return _wxGetTranslation_ctx(s, ctx); }
References _wxGetTranslation_ctx.
translate() [12/15]
wxString Slic3r::GUI::I18N::translate (const wchar_t * s, const wchar_t * plural, unsigned int n) inline
{ return wxGetTranslation(s, plural, n); }
translate() [13/15]
wxString Slic3r::GUI::I18N::translate (const wxString & s) inline
{ return wxGetTranslation(s); }
translate() [14/15]
wxString Slic3r::GUI::I18N::translate (const wxString & s, const char * ctx) inline
{ return _wxGetTranslation_ctx(s, ctx); }
References _wxGetTranslation_ctx.
translate() [15/15]
wxString Slic3r::GUI::I18N::translate (const wxString & s, const wxString & plural, unsigned int n) inline
{ return wxGetTranslation(s, plural, n); }
translate_utf8() [1/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const char * s) inline
{ return wxGetTranslation(wxString(s, wxConvUTF8)).ToUTF8().data(); }
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::sla_wildcards().
translate_utf8() [2/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const char * s, const char * ctx) inline
{ return _wxGetTranslation_ctx(wxString(s, wxConvUTF8), ctx).ToUTF8().data(); }
References _wxGetTranslation_ctx.
translate_utf8() [3/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const char * s, const char * plural, unsigned int n) inline
{ return translate(s, plural, n).ToUTF8().data(); }
References translate().
translate_utf8() [4/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const std::string & s) inline
{ return wxGetTranslation(wxString(s.c_str(), wxConvUTF8)).ToUTF8().data(); }
translate_utf8() [5/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const std::string & s, const char * ctx) inline
{ return _wxGetTranslation_ctx(wxString(s.c_str(), wxConvUTF8), ctx).ToUTF8().data(); }
References _wxGetTranslation_ctx.
translate_utf8() [6/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const std::string & s, const std::string & plural, unsigned int n) inline
{ return translate(s, plural, n).ToUTF8().data(); }
References translate().
translate_utf8() [7/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const std::wstring & s) inline
{ return wxGetTranslation(s.c_str()).ToUTF8().data(); }
translate_utf8() [8/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const std::wstring & s, const char * ctx) inline
{ return _wxGetTranslation_ctx(s.c_str(), ctx).ToUTF8().data(); }
References _wxGetTranslation_ctx.
translate_utf8() [9/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const std::wstring & s, const std::wstring & plural, unsigned int n) inline
{ return translate(s, plural, n).ToUTF8().data(); }
References translate().
translate_utf8() [10/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const wchar_t * s) inline
{ return wxGetTranslation(s).ToUTF8().data(); }
translate_utf8() [11/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const wchar_t * s, const char * ctx) inline
{ return _wxGetTranslation_ctx(s, ctx).ToUTF8().data(); }
References _wxGetTranslation_ctx.
translate_utf8() [12/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const wchar_t * s, const wchar_t * plural, unsigned int n) inline
{ return translate(s, plural, n).ToUTF8().data(); }
References translate().
translate_utf8() [13/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const wxString & s) inline
{ return wxGetTranslation(s).ToUTF8().data(); }
translate_utf8() [14/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const wxString & s, const char * ctx) inline
{ return _wxGetTranslation_ctx(s, ctx).ToUTF8().data(); }
References _wxGetTranslation_ctx.
translate_utf8() [15/15]
std::string Slic3r::GUI::I18N::translate_utf8 (const wxString & s, const wxString & plural, unsigned int n) inline
{ return translate(s, plural, n).ToUTF8().data(); }
References translate().