Prusa Slicer: Eigen::FullPivHouseholderQR< _MatrixType > Class Template Reference
Eigen::FullPivHouseholderQR< _MatrixType > Class Template Reference
Householder rank-revealing QR decomposition of a matrix with full pivoting.
#include <src/eigen/Eigen/src/QR/FullPivHouseholderQR.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef internal::FullPivHouseholderQRMatrixQReturnType< MatrixType > MatrixQReturnType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef Matrix< StorageIndex, 1, EIGEN_SIZE_MIN_PREFER_DYNAMIC(ColsAtCompileTime, RowsAtCompileTime), RowMajor, 1, EIGEN_SIZE_MIN_PREFER_FIXED(MaxColsAtCompileTime, MaxRowsAtCompileTime)> IntDiagSizeVectorType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime > PermutationType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef internal::plain_col_type< MatrixType >::type ColVectorType
typedef MatrixType::PlainObject PlainObject
Public Member Functions
FullPivHouseholderQR ()
Default Constructor.
FullPivHouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
FullPivHouseholderQR (const EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename InputType >
FullPivHouseholderQR (EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename Rhs >
const Solve< FullPivHouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
MatrixQReturnType matrixQ (void) const
const MatrixType & matrixQR () const
template<typename InputType >
FullPivHouseholderQR & compute (const EigenBase< InputType > &matrix)
const PermutationType & colsPermutation () const
const IntDiagSizeVectorType & rowsTranspositions () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< FullPivHouseholderQR > inverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
FullPivHouseholderQR & setThreshold (const RealScalar &threshold)
FullPivHouseholderQR & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename InputType >
FullPivHouseholderQR< MatrixType > & compute (const EigenBase< InputType > &matrix)
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
Protected Member Functions
void computeInPlace ()
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
IntDiagSizeVectorType m_rows_transpositions
IntDiagSizeVectorType m_cols_transpositions
PermutationType m_cols_permutation
RowVectorType m_temp
bool m_isInitialized
bool m_usePrescribedThreshold
RealScalar m_prescribedThreshold
RealScalar m_maxpivot
Index m_nonzero_pivots
RealScalar m_precision
Index m_det_pq
Detailed Description
template<typename _MatrixType>
class Eigen::FullPivHouseholderQR< _MatrixType >
Householder rank-revealing QR decomposition of a matrix with full pivoting.
Template Parameters
_MatrixType the type of the matrix of which we are computing the QR decomposition
This class performs a rank-revealing QR decomposition of a matrix A into matrices P, P', Q and R such that
by using Householder transformations. Here, P and P' are permutation matrices, Q a unitary matrix and R an upper triangular matrix.
This decomposition performs a very prudent full pivoting in order to be rank-revealing and achieve optimal numerical stability. The trade-off is that it is slower than HouseholderQR and ColPivHouseholderQR.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::fullPivHouseholderQr()
Member Typedef Documentation
ColVectorType
template<typename _MatrixType > typedef internal::plain_col_type<MatrixType>::type Eigen::FullPivHouseholderQR< _MatrixType >::ColVectorType
HCoeffsType
template<typename _MatrixType > typedef internal::plain_diag_type<MatrixType>::type Eigen::FullPivHouseholderQR< _MatrixType >::HCoeffsType
IntDiagSizeVectorType
template<typename _MatrixType > typedef Matrix<StorageIndex, 1, EIGEN_SIZE_MIN_PREFER_DYNAMIC(ColsAtCompileTime,RowsAtCompileTime), RowMajor, 1, EIGEN_SIZE_MIN_PREFER_FIXED(MaxColsAtCompileTime,MaxRowsAtCompileTime)> Eigen::FullPivHouseholderQR< _MatrixType >::IntDiagSizeVectorType
MatrixQReturnType
template<typename _MatrixType > typedef internal::FullPivHouseholderQRMatrixQReturnType<MatrixType> Eigen::FullPivHouseholderQR< _MatrixType >::MatrixQReturnType
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::FullPivHouseholderQR< _MatrixType >::MatrixType
PermutationType
template<typename _MatrixType > typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::FullPivHouseholderQR< _MatrixType >::PermutationType
PlainObject
template<typename _MatrixType > typedef MatrixType::PlainObject Eigen::FullPivHouseholderQR< _MatrixType >::PlainObject
RealScalar
template<typename _MatrixType > typedef MatrixType::RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::RealScalar
RowVectorType
template<typename _MatrixType > typedef internal::plain_row_type<MatrixType>::type Eigen::FullPivHouseholderQR< _MatrixType >::RowVectorType
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::FullPivHouseholderQR< _MatrixType >::Scalar
StorageIndex
template<typename _MatrixType > typedef MatrixType::StorageIndex Eigen::FullPivHouseholderQR< _MatrixType >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
         {
      RowsAtCompileTime = MatrixType::RowsAtCompileTime,
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
FullPivHouseholderQR() [1/4]
template<typename _MatrixType > Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via FullPivHouseholderQR::compute(const MatrixType&).
      : m_qr(),
        m_hCoeffs(),
        m_rows_transpositions(),
        m_cols_transpositions(),
        m_cols_permutation(),
        m_temp(),
        m_isInitialized(false),
        m_usePrescribedThreshold(false) {}
FullPivHouseholderQR() [2/4]
template<typename _MatrixType > Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
FullPivHouseholderQR()
      : m_qr(rows, cols),
        m_hCoeffs((std::min)(rows,cols)),
        m_rows_transpositions((std::min)(rows,cols)),
        m_cols_transpositions((std::min)(rows,cols)),
        m_cols_permutation(cols),
        m_temp(cols),
        m_isInitialized(false),
        m_usePrescribedThreshold(false) {}
FullPivHouseholderQR() [3/4]
template<typename _MatrixType > template<typename InputType > Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR (const EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This constructor computes the QR factorization of the matrix matrix by calling the method compute(). It is a short cut for:
FullPivHouseholderQR<MatrixType> qr(matrix.rows(), matrix.cols());
qr.compute(matrix);
See also
compute()
      : m_qr(matrix.rows(), matrix.cols()),
        m_hCoeffs((std::min)(matrix.rows(), matrix.cols())),
        m_rows_transpositions((std::min)(matrix.rows(), matrix.cols())),
        m_cols_transpositions((std::min)(matrix.rows(), matrix.cols())),
        m_cols_permutation(matrix.cols()),
        m_temp(matrix.cols()),
        m_isInitialized(false),
        m_usePrescribedThreshold(false)
    {
      compute(matrix.derived());
    }
References Eigen::FullPivHouseholderQR< _MatrixType >::compute(), and Eigen::EigenBase< Derived >::derived().
FullPivHouseholderQR() [4/4]
template<typename _MatrixType > template<typename InputType > Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR (EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
FullPivHouseholderQR(const EigenBase&)
      : m_qr(matrix.derived()),
        m_hCoeffs((std::min)(matrix.rows(), matrix.cols())),
        m_rows_transpositions((std::min)(matrix.rows(), matrix.cols())),
        m_cols_transpositions((std::min)(matrix.rows(), matrix.cols())),
        m_cols_permutation(matrix.cols()),
        m_temp(matrix.cols()),
        m_isInitialized(false),
        m_usePrescribedThreshold(false)
    {
      computeInPlace();
    }
References Eigen::FullPivHouseholderQR< _MatrixType >::computeInPlace().
Member Function Documentation
_solve_impl() [1/2]
template<typename _MatrixType > template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::FullPivHouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
_solve_impl() [2/2]
template<typename _MatrixType > template<typename RhsType , typename DstType > void Eigen::FullPivHouseholderQR< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
  eigen_assert(rhs.rows() == rows());
  const Index l_rank = rank();
  // FIXME introduce nonzeroPivots() and use it here. and more generally,
  // make the same improvements in this dec as in FullPivLU.
  if(l_rank==0)
  {
    dst.setZero();
    return;
  }
  typename RhsType::PlainObject c(rhs);
  Matrix<Scalar,1,RhsType::ColsAtCompileTime> temp(rhs.cols());
  for (Index k = 0; k < l_rank; ++k)
  {
    Index remainingSize = rows()-k;
    c.row(k).swap(c.row(m_rows_transpositions.coeff(k)));
    c.bottomRightCorner(remainingSize, rhs.cols())
      .applyHouseholderOnTheLeft(m_qr.col(k).tail(remainingSize-1),
                               m_hCoeffs.coeff(k), &temp.coeffRef(0));
  }
  m_qr.topLeftCorner(l_rank, l_rank)
      .template triangularView<Upper>()
      .solveInPlace(c.topRows(l_rank));
  for(Index i = 0; i < l_rank; ++i) dst.row(m_cols_permutation.indices().coeff(i)) = c.row(i);
  for(Index i = l_rank; i < cols(); ++i) dst.row(m_cols_permutation.indices().coeff(i)).setZero();
}
References Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::coeffRef(), and eigen_assert.
absDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType >::absDeterminant
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
logAbsDeterminant(), MatrixBase::determinant()
{
  using std::abs;
  eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
  eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
  return abs(m_qr.diagonal().prod());
}
References eigen_assert.
check_template_parameters()
template<typename _MatrixType > static void Eigen::FullPivHouseholderQR< _MatrixType >::check_template_parameters () inline static protected
    {
      EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
    }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
cols()
template<typename _MatrixType > Index Eigen::FullPivHouseholderQR< _MatrixType >::cols () const inline
{ return m_qr.cols(); }
References Eigen::FullPivHouseholderQR< _MatrixType >::m_qr.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::dimensionOfKernel(), and Eigen::FullPivHouseholderQR< _MatrixType >::isInjective().
colsPermutation()
template<typename _MatrixType > const PermutationType & Eigen::FullPivHouseholderQR< _MatrixType >::colsPermutation () const inline
Returns
a const reference to the column permutation matrix
    {
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      return m_cols_permutation;
    }
References eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::m_cols_permutation, and Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized.
compute() [1/2]
template<typename _MatrixType > template<typename InputType > FullPivHouseholderQR & Eigen::FullPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR().
compute() [2/2]
template<typename _MatrixType > template<typename InputType > FullPivHouseholderQR< MatrixType > & Eigen::FullPivHouseholderQR< _MatrixType >::compute (const EigenBase< InputType > & matrix)
Performs the QR factorization of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class FullPivHouseholderQR, FullPivHouseholderQR(const MatrixType&)
{
  m_qr = matrix.derived();
  computeInPlace();
  return *this;
}
References Eigen::EigenBase< Derived >::derived().
computeInPlace()
template<typename MatrixType > void Eigen::FullPivHouseholderQR< MatrixType >::computeInPlace protected
{
  check_template_parameters();
  using std::abs;
  Index rows = m_qr.rows();
  Index cols = m_qr.cols();
  Index size = (std::min)(rows,cols);
  m_hCoeffs.resize(size);
  m_temp.resize(cols);
  m_precision = NumTraits<Scalar>::epsilon() * RealScalar(size);
  m_rows_transpositions.resize(size);
  m_cols_transpositions.resize(size);
  Index number_of_transpositions = 0;
  RealScalar biggest(0);
  m_nonzero_pivots = size; // the generic case is that in which all pivots are nonzero (invertible case)
  m_maxpivot = RealScalar(0);
  for (Index k = 0; k < size; ++k)
  {
    Index row_of_biggest_in_corner, col_of_biggest_in_corner;
    typedef internal::scalar_score_coeff_op<Scalar> Scoring;
    typedef typename Scoring::result_type Score;
    Score score = m_qr.bottomRightCorner(rows-k, cols-k)
                      .unaryExpr(Scoring())
                      .maxCoeff(&row_of_biggest_in_corner, &col_of_biggest_in_corner);
    row_of_biggest_in_corner += k;
    col_of_biggest_in_corner += k;
    RealScalar biggest_in_corner = internal::abs_knowing_score<Scalar>()(m_qr(row_of_biggest_in_corner, col_of_biggest_in_corner), score);
    if(k==0) biggest = biggest_in_corner;
    // if the corner is negligible, then we have less than full rank, and we can finish early
    if(internal::isMuchSmallerThan(biggest_in_corner, biggest, m_precision))
    {
      m_nonzero_pivots = k;
      for(Index i = k; i < size; i++)
      {
        m_rows_transpositions.coeffRef(i) = i;
        m_cols_transpositions.coeffRef(i) = i;
        m_hCoeffs.coeffRef(i) = Scalar(0);
      }
      break;
    }
    m_rows_transpositions.coeffRef(k) = row_of_biggest_in_corner;
    m_cols_transpositions.coeffRef(k) = col_of_biggest_in_corner;
    if(k != row_of_biggest_in_corner) {
      m_qr.row(k).tail(cols-k).swap(m_qr.row(row_of_biggest_in_corner).tail(cols-k));
      ++number_of_transpositions;
    }
    if(k != col_of_biggest_in_corner) {
      m_qr.col(k).swap(m_qr.col(col_of_biggest_in_corner));
      ++number_of_transpositions;
    }
    RealScalar beta;
    m_qr.col(k).tail(rows-k).makeHouseholderInPlace(m_hCoeffs.coeffRef(k), beta);
    m_qr.coeffRef(k,k) = beta;
    // remember the maximum absolute value of diagonal coefficients
    if(abs(beta) > m_maxpivot) m_maxpivot = abs(beta);
    m_qr.bottomRightCorner(rows-k, cols-k-1)
        .applyHouseholderOnTheLeft(m_qr.col(k).tail(rows-k-1), m_hCoeffs.coeffRef(k), &m_temp.coeffRef(k+1));
  }
  m_cols_permutation.setIdentity(cols);
  for(Index k = 0; k < size; ++k)
    m_cols_permutation.applyTranspositionOnTheRight(k, m_cols_transpositions.coeff(k));
  m_det_pq = (number_of_transpositions%2) ? -1 : 1;
  m_isInitialized = true;
}
References Eigen::internal::isMuchSmallerThan().
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR().
dimensionOfKernel()
template<typename _MatrixType > Index Eigen::FullPivHouseholderQR< _MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      return cols() - rank();
    }
References Eigen::FullPivHouseholderQR< _MatrixType >::cols(), eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::FullPivHouseholderQR< _MatrixType >::rank().
hCoeffs()
template<typename _MatrixType > const HCoeffsType & Eigen::FullPivHouseholderQR< _MatrixType >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
{ return m_hCoeffs; }
References Eigen::FullPivHouseholderQR< _MatrixType >::m_hCoeffs.
inverse()
template<typename _MatrixType > const Inverse< FullPivHouseholderQR > Eigen::FullPivHouseholderQR< _MatrixType >::inverse () const inline
Returns
the inverse of the matrix of which *this is the QR decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
    {
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      return Inverse<FullPivHouseholderQR>(*this);
    }
References eigen_assert, and Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized.
isInjective()
template<typename _MatrixType > bool Eigen::FullPivHouseholderQR< _MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      return rank() == cols();
    }
References Eigen::FullPivHouseholderQR< _MatrixType >::cols(), eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::FullPivHouseholderQR< _MatrixType >::rank().
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::isInvertible().
isInvertible()
template<typename _MatrixType > bool Eigen::FullPivHouseholderQR< _MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the QR decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      return isInjective() && isSurjective();
    }
References eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::isInjective(), Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective(), and Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized.
isSurjective()
template<typename _MatrixType > bool Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      return rank() == rows();
    }
References eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized, Eigen::FullPivHouseholderQR< _MatrixType >::rank(), and Eigen::FullPivHouseholderQR< _MatrixType >::rows().
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::isInvertible().
logAbsDeterminant()
template<typename MatrixType > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType >::logAbsDeterminant
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
absDeterminant(), MatrixBase::determinant()
{
  eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
  eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
  return m_qr.diagonal().cwiseAbs().array().log().sum();
}
References eigen_assert.
matrixQ()
template<typename MatrixType > FullPivHouseholderQR< MatrixType >::MatrixQReturnType Eigen::FullPivHouseholderQR< MatrixType >::matrixQ (void) const inline
Returns
Expression object representing the matrix Q
{
  eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
  return MatrixQReturnType(m_qr, m_hCoeffs, m_rows_transpositions);
}
References eigen_assert.
matrixQR()
template<typename _MatrixType > const MatrixType & Eigen::FullPivHouseholderQR< _MatrixType >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored
    {
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      return m_qr;
    }
References eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::FullPivHouseholderQR< _MatrixType >::m_qr.
maxPivot()
template<typename _MatrixType > RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of U.
{ return m_maxpivot; }
References Eigen::FullPivHouseholderQR< _MatrixType >::m_maxpivot.
nonzeroPivots()
template<typename _MatrixType > Index Eigen::FullPivHouseholderQR< _MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the QR decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return m_nonzero_pivots;
    }
References eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::FullPivHouseholderQR< _MatrixType >::m_nonzero_pivots.
rank()
template<typename _MatrixType > Index Eigen::FullPivHouseholderQR< _MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      using std::abs;
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      RealScalar premultiplied_threshold = abs(m_maxpivot) * threshold();
      Index result = 0;
      for(Index i = 0; i < m_nonzero_pivots; ++i)
        result += (abs(m_qr.coeff(i,i)) > premultiplied_threshold);
      return result;
    }
References eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized, Eigen::FullPivHouseholderQR< _MatrixType >::m_maxpivot, Eigen::FullPivHouseholderQR< _MatrixType >::m_nonzero_pivots, Eigen::FullPivHouseholderQR< _MatrixType >::m_qr, and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::FullPivHouseholderQR< _MatrixType >::isInjective(), and Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective().
rows()
template<typename _MatrixType > Index Eigen::FullPivHouseholderQR< _MatrixType >::rows () const inline
{ return m_qr.rows(); }
References Eigen::FullPivHouseholderQR< _MatrixType >::m_qr.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective().
rowsTranspositions()
template<typename _MatrixType > const IntDiagSizeVectorType & Eigen::FullPivHouseholderQR< _MatrixType >::rowsTranspositions () const inline
Returns
a const reference to the vector of indices representing the rows transpositions
    {
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      return m_rows_transpositions;
    }
References eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized, and Eigen::FullPivHouseholderQR< _MatrixType >::m_rows_transpositions.
setThreshold() [1/2]
template<typename _MatrixType > FullPivHouseholderQR & Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the QR decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
    {
      m_usePrescribedThreshold = true;
      m_prescribedThreshold = threshold;
      return *this;
    }
References Eigen::FullPivHouseholderQR< _MatrixType >::m_prescribedThreshold, Eigen::FullPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold, and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
setThreshold() [2/2]
template<typename _MatrixType > FullPivHouseholderQR & Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
    {
      m_usePrescribedThreshold = false;
      return *this;
    }
References Eigen::FullPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold.
solve()
template<typename _MatrixType > template<typename Rhs > const Solve< FullPivHouseholderQR, Rhs > Eigen::FullPivHouseholderQR< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method finds a solution x to the equation Ax=b, where A is the matrix of which *this is the QR decomposition.
Parameters
b the right-hand-side of the equation to solve.
Returns
the exact or least-square solution if the rank is greater or equal to the number of columns of A, and an arbitrary solution otherwise.
\note_about_checking_solutions
\note_about_arbitrary_choice_of_solution
Example:
Output:
    {
      eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
      return Solve<FullPivHouseholderQR, Rhs>(*this, b.derived());
    }
References eigen_assert, and Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized.
threshold()
template<typename _MatrixType > RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized || m_usePrescribedThreshold);
      return m_usePrescribedThreshold ? m_prescribedThreshold
      // this formula comes from experimenting (see "LU precision tuning" thread on the list)
      // and turns out to be identical to Higham's formula used already in LDLt.
                                      : NumTraits<Scalar>::epsilon() * RealScalar(m_qr.diagonalSize());
    }
References eigen_assert, Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized, Eigen::FullPivHouseholderQR< _MatrixType >::m_prescribedThreshold, Eigen::FullPivHouseholderQR< _MatrixType >::m_qr, and Eigen::FullPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::rank(), and Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold().
Member Data Documentation
m_cols_permutation
template<typename _MatrixType > PermutationType Eigen::FullPivHouseholderQR< _MatrixType >::m_cols_permutation protected
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::colsPermutation().
m_cols_transpositions
template<typename _MatrixType > IntDiagSizeVectorType Eigen::FullPivHouseholderQR< _MatrixType >::m_cols_transpositions protected
m_det_pq
template<typename _MatrixType > Index Eigen::FullPivHouseholderQR< _MatrixType >::m_det_pq protected
m_hCoeffs
template<typename _MatrixType > HCoeffsType Eigen::FullPivHouseholderQR< _MatrixType >::m_hCoeffs protected
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::hCoeffs().
m_isInitialized
template<typename _MatrixType > bool Eigen::FullPivHouseholderQR< _MatrixType >::m_isInitialized protected
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::colsPermutation(), Eigen::FullPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::FullPivHouseholderQR< _MatrixType >::inverse(), Eigen::FullPivHouseholderQR< _MatrixType >::isInjective(), Eigen::FullPivHouseholderQR< _MatrixType >::isInvertible(), Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective(), Eigen::FullPivHouseholderQR< _MatrixType >::matrixQR(), Eigen::FullPivHouseholderQR< _MatrixType >::nonzeroPivots(), Eigen::FullPivHouseholderQR< _MatrixType >::rank(), Eigen::FullPivHouseholderQR< _MatrixType >::rowsTranspositions(), Eigen::FullPivHouseholderQR< _MatrixType >::solve(), and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
m_maxpivot
template<typename _MatrixType > RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::m_maxpivot protected
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::maxPivot(), and Eigen::FullPivHouseholderQR< _MatrixType >::rank().
m_nonzero_pivots
template<typename _MatrixType > Index Eigen::FullPivHouseholderQR< _MatrixType >::m_nonzero_pivots protected
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::nonzeroPivots(), and Eigen::FullPivHouseholderQR< _MatrixType >::rank().
m_precision
template<typename _MatrixType > RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::m_precision protected
m_prescribedThreshold
template<typename _MatrixType > RealScalar Eigen::FullPivHouseholderQR< _MatrixType >::m_prescribedThreshold protected
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold(), and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
m_qr
template<typename _MatrixType > MatrixType Eigen::FullPivHouseholderQR< _MatrixType >::m_qr protected
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::cols(), Eigen::FullPivHouseholderQR< _MatrixType >::matrixQR(), Eigen::FullPivHouseholderQR< _MatrixType >::rank(), Eigen::FullPivHouseholderQR< _MatrixType >::rows(), and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
m_rows_transpositions
template<typename _MatrixType > IntDiagSizeVectorType Eigen::FullPivHouseholderQR< _MatrixType >::m_rows_transpositions protected
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::rowsTranspositions().
m_temp
template<typename _MatrixType > RowVectorType Eigen::FullPivHouseholderQR< _MatrixType >::m_temp protected
m_usePrescribedThreshold
template<typename _MatrixType > bool Eigen::FullPivHouseholderQR< _MatrixType >::m_usePrescribedThreshold protected
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold(), Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold(), and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/util/ForwardDeclarations.h
src/eigen/Eigen/src/QR/FullPivHouseholderQR.h