Prusa Slicer: src/slic3r/GUI/WipeTowerDialog.cpp File Reference
WipeTowerDialog.cpp File Reference
#include <algorithm>
#include <sstream>
#include "WipeTowerDialog.hpp"
#include "BitmapCache.hpp"
#include "GUI.hpp"
#include "I18N.hpp"
#include "GUI_App.hpp"
#include "MsgDialog.hpp"
#include "libslic3r/Color.hpp"
#include <wx/sizer.h>
Macros
#define style wxSP_ARROW_KEYS
Functions
int scale (const int val)
int ITEM_WIDTH ()
static void update_ui (wxWindow *window)
Macro Definition Documentation
style
#define style wxSP_ARROW_KEYS
Function Documentation
ITEM_WIDTH()
int ITEM_WIDTH ()
{ return scale(6); }
References scale().
Referenced by RammingPanel::RammingPanel(), WipingDialog::WipingDialog(), and WipingPanel::WipingPanel().
scale()
int scale (const int val)
{ return val * Slic3r::GUI::wxGetApp().em_unit(); }
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), RammingPanel::RammingPanel(), Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), Slic3r::GUI::GLCanvas3D::_render_gizmos_overlay(), Slic3r::GUI::GLCanvas3D::_render_view_toolbar(), Slic3r::GUI::Camera::apply_projection(), Slic3r::GUI::GLCanvas3D::apply_retina_scale(), Slic3r::Geometry::assemble_transform(), Slic3r::Geometry::assemble_transform(), Slic3r::Geometry::assemble_transform(), Slic3r::Geometry::assemble_transform(), ImGuiWindow::CalcFontSize(), ImFont::CalcTextSizeA(), Slic3r::GUI::GLGizmoEmboss::calculate_scale(), ImFont::CalcWordWrapPositionA(), Slic3r::GUI::ObjectManipulation::change_scale_value(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::compute(), Eigen::BDCSVD< _MatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Slic3r::Geometry::contains_skew(), Slic3r::GUI::Emboss::StyleManager::create_imgui_font(), ImGui::DebugRenderViewportThumbnail(), Slic3r::dilate_grid(), Slic3r::GUI::ObjectManipulation::do_scale(), Slic3r::GUI::ObjectManipulation::do_size(), Slic3r::SVG::draw(), Slic3r::SVG::draw(), Slic3r::GUI::GLGizmoEmboss::draw_text_input(), Slic3r::dump_voronoi_to_svg(), Slic3r::Geometry::extract_rotation_matrix(), Slic3r::Geometry::extract_rotation_scale(), Slic3r::Geometry::extract_scale(), Slic3r::format_memsize_MB(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::fromPositionOrientationScale(), Slic3r::gcode_paint_bitmap(), get_bmp_bundle(), get_empty_bmp_bundle(), Slic3r::GUI::Emboss::StyleManager::get_imgui_font_size(), Slic3r::Geometry::Transformation::get_mirror(), Slic3r::Geometry::Transformation::get_mirror_matrix(), Slic3r::SVG::get_path_d(), Slic3r::Geometry::Transformation::get_scaling_factor(), Slic3r::Geometry::Transformation::get_scaling_factor_matrix(), Slic3r::Emboss::get_shape_scale(), get_solid_bmp_bundle(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::get_voxel_scale(), ImFontAtlasBuildWithStbTruetype(), InputTextCalcTextSizeW(), Slic3r::Geometry::Transformation::is_scaling_uniform(), ITEM_WIDTH(), Slic3r::GUI::GLTexture::load_from_svg(), Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::on_mouse_wheel(), Slic3r::GUI::ObjectList::part_selection_changed(), Slic3r::GUI::CreateFontImageJob::process(), Slic3r::GUI::Emboss::CreateFontStyleImagesJob::process(), igl::procrustes(), igl::procrustes(), igl::procrustes(), ImGui::RenderArrow(), ImGui::RenderArrow(), ImFont::RenderChar(), ImGui::RenderMouseCursor(), ImFont::RenderText(), Slic3r::rescale_grid(), Slic3r::GUI::GLGizmoEmboss::rev_input_mm(), Slic3r::GUI::round_to_bin(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Slic3r::EdgeGrid::save_png(), Slic3r::GUI::SplashScreen::scale_bitmap(), Slic3r::GUI::SplashScreen::scale_font(), Slic3r::ModelVolume::scale_geometry_after_creation(), Slic3r::ModelObject::scale_mesh_after_creation(), Slic3r::ModelObject::scale_to_fit(), Slic3r::Geometry::scale_transform(), Slic3r::Geometry::scale_transform(), Slic3r::Geometry::scale_transform(), Slic3r::Geometry::scale_transform(), libnest2d::shapelike::serialize< libnest2d::Formats::SVG >(), Slic3r::GUI::GUI_App::set_auto_toolbar_icon_scale(), Slic3r::Geometry::Transformation::set_mirror(), Slic3r::Geometry::Transformation::set_mirror(), Slic3r::GUI::GLGizmosManager::set_overlay_scale(), Slic3r::Geometry::Transformation::set_rotation(), Slic3r::GUI::GLGizmoScale3D::set_scale(), Slic3r::GUI::GLToolbar::set_scale(), Slic3r::Geometry::Transformation::set_scaling_factor(), Eigen::SimplicialCholeskyBase< Derived >::setShift(), ImGui::SetWindowFontScale(), ImGui::ShadeVertsLinearUV(), igl::shapeup_regular_face_projection(), Eigen::internal::stable_norm_kernel(), Eigen::MatrixBase< Derived >::stableNorm(), Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform(), ImGui::UpdateMouseWheel(), Slic3r::png::write_gray_to_file_scaled(), Slic3r::png::write_gray_to_file_scaled(), Slic3r::png::write_gray_to_file_scaled(), Slic3r::png::write_rgb_or_gray_to_file_scaled(), Slic3r::png::write_rgb_to_file_scaled(), Slic3r::png::write_rgb_to_file_scaled(), Slic3r::png::write_rgb_to_file_scaled(), and Slic3r::GUI::wxImage_to_wxBitmap_with_alpha().
update_ui()
static void update_ui (wxWindow * window) static
{
    Slic3r::GUI::wxGetApp().UpdateDarkUI(window);
}
Referenced by RammingDialog::RammingDialog(), RammingPanel::RammingPanel(), WipingDialog::WipingDialog(), and WipingPanel::WipingPanel().