Prusa Slicer: Slic3r::GUI::GLGizmoSimplify Class Reference
Slic3r::GUI::GLGizmoSimplify Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoSimplify.hpp>
Classes
struct Configuration
struct GuiCfg
class SimplifyCanceledException
struct State
Public Types
enum class EGrabberExtension {
None = 0 , PosX = 1 << 0 , NegX = 1 << 1 , PosY = 1 << 2 ,
NegY = 1 << 3 , PosZ = 1 << 4 , NegZ = 1 << 5
}
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoSimplify (GLCanvas3D &parent)
virtual ~GLGizmoSimplify ()
bool on_esc_key_down ()
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
virtual bool wants_enter_leave_snapshots () const
virtual std::string get_gizmo_entering_text () const
virtual std::string get_gizmo_leaving_text () const
virtual std::string get_action_snapshot_name () const
void set_common_data_pool (CommonGizmosDataPool *ptr)
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
bool is_dragging () const
bool update_items_state ()
void render ()
void render_input_window (float x, float y, float bottom_limit)
virtual std::string get_tooltip () const
Mouse tooltip text.
virtual void data_changed (bool is_serializing)
Is called when data (Selection) is changed.
virtual bool on_mouse (const wxMouseEvent &mouse_event)
Implement when want to process mouse events in gizmo Click, Right click, move, drag, ...
void register_raycasters_for_picking ()
void unregister_raycasters_for_picking ()
virtual bool is_in_editing_mode () const
virtual bool is_selection_rectangle_dragging () const
Static Public Member Functions
static void add_simplify_suggestion_notification (const std::vector< size_t > &object_ids, const std::vector< ModelObject * > &objects, NotificationManager &manager)
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static const unsigned int GRABBER_ELEMENTS_MAX_COUNT = 7
static const int NO_SHORTCUT_KEY_VALUE = 0
Protected Member Functions
virtual std::string on_get_name () const override
virtual void on_render_input_window (float x, float y, float bottom_limit) override
virtual bool on_is_activable () const override
virtual bool on_is_selectable () const override
virtual void on_set_state () override
virtual bool on_init () override
virtual void on_render () override
CommonGizmosDataID on_get_requirements () const override
virtual void on_load (cereal::BinaryInputArchive &ar)
virtual void on_save (cereal::BinaryOutputArchive &ar) const
virtual void on_set_hover_id ()
virtual void on_enable_grabber (unsigned int id)
virtual void on_disable_grabber (unsigned int id)
virtual void on_start_dragging ()
virtual void on_stop_dragging ()
virtual void on_dragging (const UpdateData &data)
void register_grabbers_for_picking ()
void unregister_grabbers_for_picking ()
virtual void on_register_raycasters_for_picking ()
virtual void on_unregister_raycasters_for_picking ()
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers (size_t first, size_t last, float size, bool force_hover) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
bool use_grabbers (const wxMouseEvent &mouse_event)
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
void do_stop_dragging (bool perform_mouse_cleanup)
Protected Attributes
GLCanvas3D & m_parent
int m_group_id
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id { -1 }
bool m_dragging { false }
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render { true }
CommonGizmosDataPool * m_c { nullptr }
Private Member Functions
void apply_simplify ()
void close ()
void process ()
bool stop_worker_thread_request ()
void worker_finished ()
void create_gui_cfg ()
void request_rerender (bool force=false)
void set_center_position ()
void init_model ()
void update_model (const State::Data &data)
Private Attributes
Configuration m_configuration
bool m_move_to_center
std::set< ObjectID > m_volume_ids
std::string m_volumes_name
size_t m_original_triangle_count
bool m_show_wireframe
std::map< ObjectID, GLModel > m_glmodels
size_t m_triangle_count
int64_t m_last_rerender_timestamp = std::numeric_limits<int64_t>::min()
std::thread m_worker
std::mutex m_state_mutex
State m_state
std::optional< GuiCfg > m_gui_cfg
const std::string tr_mesh_name
const std::string tr_triangles
const std::string tr_detail_level
const std::string tr_decimate_ratio
bool m_dirty { false }
Static Private Attributes
static const std::string M_ICON_FILENAME = "cut.svg"
Detailed Description
Class Documentation
Slic3r::GUI::GLGizmoSimplify::GuiCfg
struct Slic3r::GUI::GLGizmoSimplify::GuiCfg
Class Members
int bottom_left_width = 100
int input_width = 100
size_t max_char_in_name = 30
duration< long int, milli > prcess_delay = std::chrono::milliseconds(250)
int top_left_width = 100
int window_offset_x = 100
int window_offset_y = 100
int window_padding = 0
Member Enumeration Documentation
EGrabberExtension
enum class Slic3r::GUI::GLGizmoBase::EGrabberExtension strong inherited
Enumerator
None
PosX
NegX
PosY
NegY
PosZ
NegZ
    {
        None = 0,
        PosX = 1 << 0,
        NegX = 1 << 1,
        PosY = 1 << 2,
        NegY = 1 << 3,
        PosZ = 1 << 4,
        NegZ = 1 << 5,
    };
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
Constructor & Destructor Documentation
GLGizmoSimplify()
Slic3r::GUI::GLGizmoSimplify::GLGizmoSimplify (GLCanvas3D & parent)
    : GLGizmoBase(parent, M_ICON_FILENAME, -1)
    , m_show_wireframe(false)
    , m_move_to_center(false)
    , m_original_triangle_count(0)
    , m_triangle_count(0)
    // translation for GUI size
    , tr_mesh_name(_u8L("Mesh name"))
    , tr_triangles(_u8L("Triangles"))
    , tr_detail_level(_u8L("Level of detail"))
    , tr_decimate_ratio(_u8L("Decimate ratio"))
{}
~GLGizmoSimplify()
Slic3r::GUI::GLGizmoSimplify::~GLGizmoSimplify () virtual
{
    stop_worker_thread_request();
    if (m_worker.joinable())
        m_worker.join();
}
References m_worker, and stop_worker_thread_request().
Member Function Documentation
add_simplify_suggestion_notification()
void Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification (const std::vector< size_t > & object_ids, const std::vector< ModelObject * > & objects, NotificationManager & manager) static
{
    std::vector<size_t> big_ids;
    big_ids.reserve(object_ids.size());
    auto is_big_object = [&objects](size_t object_id) {
        const uint32_t triangles_to_suggest_simplify = 1000000;
        if (object_id >= objects.size()) return false; // out of object index
        ModelVolumePtrs &volumes = objects[object_id]->volumes;
        if (volumes.size() != 1) return false; // not only one volume
        size_t triangle_count = volumes.front()->mesh().its.indices.size();
        if (triangle_count < triangles_to_suggest_simplify)
            return false; // small volume
        return true;
    };
    std::copy_if(object_ids.begin(), object_ids.end(),
                 std::back_inserter(big_ids), is_big_object);
    if (big_ids.empty()) return;
    for (size_t object_id : big_ids) {
        std::string t = GUI::format(_L(
            "Processing model \"%1%\" with more than 1M triangles "
            "could be slow. It is highly recommended to reduce "
            "amount of triangles."), objects[object_id]->name);
        std::string hypertext = _u8L("Simplify model");
        std::function<bool(wxEvtHandler *)> open_simplify =
            [object_id](wxEvtHandler *) {
                auto plater = wxGetApp().plater();
                if (object_id >= plater->model().objects.size()) return true;
                Selection &selection = plater->canvas3D()->get_selection();
                selection.clear();
                selection.add_object((unsigned int) object_id);
                auto &manager = plater->canvas3D()->get_gizmos_manager();
                bool  close_notification = true;
                if(!manager.open_gizmo(GLGizmosManager::Simplify))
                    return close_notification;
                GLGizmoSimplify* simplify = dynamic_cast<GLGizmoSimplify*>(manager.get_current());
                if (simplify == nullptr) return close_notification;
                simplify->set_center_position();
                return close_notification;
            };
        manager.push_simplify_suggestion_notification(
            t, objects[object_id]->id(), hypertext, open_simplify);
    }
}
References _L, _u8L, Slic3r::GUI::Selection::add_object(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::Selection::clear(), Slic3r::GUI::format(), Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::plater(), Slic3r::GUI::NotificationManager::push_simplify_suggestion_notification(), and Slic3r::GUI::GLGizmosManager::Simplify.
Referenced by Slic3r::GUI::Plater::priv::load_files().
apply_simplify()
void Slic3r::GUI::GLGizmoSimplify::apply_simplify () private
{
    // worker must be stopped
    assert(m_state.status == State::Status::idle);
    // check that there is NO change of volume
    assert(m_state.volume_ids == m_volume_ids);
    const Selection& selection = m_parent.get_selection();
    auto plater = wxGetApp().plater();
    // TRN %1% = volumes name
    plater->take_snapshot(Slic3r::format(_u8L("Simplify %1%"), create_volumes_name(m_volume_ids, selection)));
    plater->clear_before_change_mesh(selection.get_object_idx(), _u8L("Custom supports, seams and multimaterial painting were "
                                                                      "removed after simplifying the mesh."));
    // After removing custom supports, seams, and multimaterial painting, we have to update info about the object to remove information about
    // custom supports, seams, and multimaterial painting in the right panel.
    wxGetApp().obj_list()->update_info_items(selection.get_object_idx());
    for (const auto &item: m_state.result) {
        const ObjectID &id = item.first;
        const indexed_triangle_set &its = *item.second;
        ModelVolume *volume = get_volume(id, selection);
        assert(volume != nullptr);
        ModelObject *obj = volume->get_object();
        volume->set_mesh(std::move(its));
        volume->calculate_convex_hull();
        volume->set_new_unique_id();
        obj->invalidate_bounding_box();
        obj->ensure_on_bed(true); // allow negative z
    }
    m_state.result.clear();
    // fix hollowing, sla support points, modifiers, ...
    int object_idx = selection.get_object_idx();
    plater->changed_mesh(object_idx);
    // Fix warning icon in object list
    wxGetApp().obj_list()->update_item_error_icon(object_idx, -1);
    close();
}
References _u8L, Slic3r::GUI::Plater::changed_mesh(), Slic3r::GUI::Plater::clear_before_change_mesh(), close(), Slic3r::GUI::create_volumes_name(), Slic3r::ModelObject::ensure_on_bed(), Slic3r::format(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::get_volume(), Slic3r::GUI::GLGizmoSimplify::State::idle, Slic3r::ModelObject::invalidate_bounding_box(), Slic3r::GUI::GLGizmoBase::m_parent, m_state, m_volume_ids, Slic3r::GUI::plater(), Slic3r::GUI::GLGizmoSimplify::State::result, Slic3r::GUI::GLGizmoSimplify::State::status, Slic3r::GUI::Plater::take_snapshot(), and Slic3r::GUI::GLGizmoSimplify::State::volume_ids.
Referenced by on_render_input_window().
close()
void Slic3r::GUI::GLGizmoSimplify::close () private
{
    // close gizmo == open it again
    GLGizmosManager &gizmos_mgr = m_parent.get_gizmos_manager();
    gizmos_mgr.open_gizmo(GLGizmosManager::EType::Simplify);
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmosManager::open_gizmo(), and Slic3r::GUI::GLGizmosManager::Simplify.
Referenced by apply_simplify(), and on_render_input_window().
create_gui_cfg()
void Slic3r::GUI::GLGizmoSimplify::create_gui_cfg () private
{
    if (m_gui_cfg.has_value()) return;
    int    space_size = m_imgui->calc_text_size(std::string_view{":MM"}).x;
    GuiCfg cfg;
    cfg.top_left_width = std::max(m_imgui->calc_text_size(tr_mesh_name).x,
                                  m_imgui->calc_text_size(tr_triangles).x)
        + space_size;
    const float radio_size = ImGui::GetFrameHeight();
    cfg.bottom_left_width =
        std::max(m_imgui->calc_text_size(tr_detail_level).x,
                 m_imgui->calc_text_size(tr_decimate_ratio).x) +
        space_size + radio_size;
    cfg.input_width   = cfg.bottom_left_width * 1.5;
    cfg.window_offset_x = (cfg.bottom_left_width + cfg.input_width)/2;
    cfg.window_offset_y = ImGui::GetTextLineHeightWithSpacing() * 5;
    m_gui_cfg = cfg;
}
References Slic3r::GUI::GLGizmoSimplify::GuiCfg::bottom_left_width, Slic3r::GUI::ImGuiWrapper::calc_text_size(), ImGui::GetFrameHeight(), ImGui::GetTextLineHeightWithSpacing(), Slic3r::GUI::GLGizmoSimplify::GuiCfg::input_width, m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::GLGizmoSimplify::GuiCfg::top_left_width, tr_decimate_ratio, tr_detail_level, tr_mesh_name, tr_triangles, Slic3r::GUI::GLGizmoSimplify::GuiCfg::window_offset_x, Slic3r::GUI::GLGizmoSimplify::GuiCfg::window_offset_y, and ImVec2::x.
Referenced by on_render_input_window().
data_changed()
virtual void Slic3r::GUI::GLGizmoBase::data_changed (bool is_serializing) inline virtual inherited
Is called when data (Selection) is changed.
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{};
do_stop_dragging()
void Slic3r::GUI::GLGizmoBase::do_stop_dragging (bool perform_mouse_cleanup) protected inherited
{
    for (auto& grabber : m_grabbers) grabber.dragging = false;
    m_dragging = false;
    // NOTE: This should be part of GLCanvas3D
    // Reset hover_id when leave window
    if (perform_mouse_cleanup) m_parent.mouse_up_cleanup();
    on_stop_dragging();
    // There is prediction that after draggign, data are changed
    // Data are updated twice also by canvas3D::reload_scene.
    // Should be fixed.
    m_parent.get_gizmos_manager().update_data();
    wxGetApp().obj_manipul()->set_dirty();
    // Let the plater know that the dragging finished, so a delayed
    // refresh of the scene with the background processing data should
    // be performed.
    m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED));
    // updates camera target constraints
    m_parent.refresh_camera_scene_box();
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_up_cleanup(), Slic3r::GUI::GLGizmoBase::on_stop_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::refresh_camera_scene_box(), and Slic3r::GUI::GLGizmosManager::update_data().
Referenced by Slic3r::GUI::GLGizmoBase::use_grabbers().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoEmboss::init_font_name_texture(), on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoEmboss::rev_input(), Slic3r::GUI::GLGizmoEmboss::rev_input_mm(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
get_action_snapshot_name()
std::string Slic3r::GUI::GLGizmoBase::get_action_snapshot_name () const virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
{
    return _u8L("Gizmo action");
}
References _u8L.
Referenced by Slic3r::GUI::Plater::priv::take_snapshot().
get_gizmo_entering_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_entering_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
get_gizmo_leaving_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_leaving_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmosManager::grabber_contains_mouse(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), and Slic3r::GUI::GLGizmoSlaSupports::on_mouse().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    std::string out = on_get_name();
    if (!include_shortcut) return out;
    int key = get_shortcut_key();
    assert(key==NO_SHORTCUT_KEY_VALUE || (key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z));
    out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE, and Slic3r::GUI::GLGizmoBase::on_get_name().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay().
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLCanvas3D::on_mouse().
get_tooltip()
virtual std::string Slic3r::GUI::GLGizmoBase::get_tooltip () const inline virtual inherited
Mouse tooltip text.
Returns
Text to be visible in mouse tooltip
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoScale3D.
{ return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::get_tooltip().
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_init().
init_model()
void Slic3r::GUI::GLGizmoSimplify::init_model () private
{
    // volume ids must be set before init model
    assert(!m_volume_ids.empty());
    m_parent.toggle_model_objects_visibility(true); // selected volume may have changed
    const auto info = m_c->selection_info();
    const Selection &selection = m_parent.get_selection();
    Model &          model     = *selection.get_model();
    const Selection::IndicesList &volume_ids = selection.get_volume_idxs();
    const ModelObjectPtrs &model_objects = model.objects;
    m_glmodels.clear();
    //m_glmodels.reserve(volume_ids.size());
    m_triangle_count = 0;
    for (const ObjectID& id: m_volume_ids) {
        const GLVolume *selected_volume;
        const ModelVolume *volume = nullptr;
        for (auto volume_id : volume_ids) {
            selected_volume = selection.get_volume(volume_id);
            const GLVolume::CompositeID &cid = selected_volume->composite_id;
            ModelObject *                obj = model_objects[cid.object_id];
            ModelVolume *                act_volume = obj->volumes[cid.volume_id];
            if (id == act_volume->id()) {
                volume = act_volume;
                break;
            }
        }
        assert(volume != nullptr);
        // set actual triangle count
        m_triangle_count += volume->mesh().its.indices.size();
        assert(m_glmodels.find(id) == m_glmodels.end());
        GLModel &glmodel = m_glmodels[id]; // create new glmodel
        glmodel.init_from(volume->mesh());
        glmodel.set_color(selected_volume->color);
        m_parent.toggle_model_objects_visibility(false, info->model_object(),
                                                 info->get_active_instance(),
                                                 volume);
    }
}
References Slic3r::GLVolume::color, Slic3r::GLVolume::composite_id, Slic3r::GUI::Selection::get_model(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::ObjectBase::id(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLGizmoBase::m_c, m_glmodels, Slic3r::GUI::GLGizmoBase::m_parent, m_triangle_count, m_volume_ids, Slic3r::GLVolume::CompositeID::object_id, Slic3r::Model::objects, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLModel::set_color(), Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility(), Slic3r::GLVolume::CompositeID::volume_id, and Slic3r::ModelObject::volumes.
Referenced by on_render_input_window().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmosManager::handle_shortcut(), Slic3r::GUI::GLGizmoEmboss::init_create(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
Referenced by Slic3r::GUI::GLGizmoCut3D::gizmo_event(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate().
is_in_editing_mode()
virtual bool Slic3r::GUI::GLGizmoBase::is_in_editing_mode () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::on_key().
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
is_selection_rectangle_dragging()
virtual bool Slic3r::GUI::GLGizmoBase::is_selection_rectangle_dragging () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoHollow, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::on_key().
load()
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
on_disable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_disable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_dragging()
virtual void Slic3r::GUI::GLGizmoBase::on_dragging (const UpdateData & data) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::use_grabbers().
on_enable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_enable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_esc_key_down()
bool Slic3r::GUI::GLGizmoSimplify::on_esc_key_down ()
{
    //close();
    return stop_worker_thread_request();
}
References stop_worker_thread_request().
on_get_name()
std::string Slic3r::GUI::GLGizmoSimplify::on_get_name () const override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    return _u8L("Simplify");
}
References _u8L.
Referenced by on_render_input_window().
on_get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoSimplify::on_get_requirements () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return CommonGizmosDataID(
        int(CommonGizmosDataID::SelectionInfo));
}
References Slic3r::GUI::SelectionInfo.
on_init()
virtual bool Slic3r::GUI::GLGizmoSimplify::on_init () inline override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{ return true;};
on_is_activable()
bool Slic3r::GUI::GLGizmoSimplify::on_is_activable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return !m_parent.get_selection().is_empty();
}
References Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_empty(), and Slic3r::GUI::GLGizmoBase::m_parent.
on_is_selectable()
virtual bool Slic3r::GUI::GLGizmoSimplify::on_is_selectable () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return false; }
on_load()
virtual void Slic3r::GUI::GLGizmoBase::on_load (cereal::BinaryInputArchive & ar) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::load().
on_mouse()
virtual bool Slic3r::GUI::GLGizmoBase::on_mouse (const wxMouseEvent & mouse_event) inline virtual inherited
Implement when want to process mouse events in gizmo Click, Right click, move, drag, ...
Parameters
mouse_event Keep information about mouse click
Returns
Return True when use the information and don't want to propagate it otherwise False.
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
on_register_raycasters_for_picking()
virtual void Slic3r::GUI::GLGizmoBase::on_register_raycasters_for_picking () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking().
on_render()
void Slic3r::GUI::GLGizmoSimplify::on_render () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    if (m_glmodels.empty()) return;
    const Selection &             selection  = m_parent.get_selection();
    // Check that the GLVolume still belongs to the ModelObject we work on.
    if (m_volume_ids != get_volume_ids(selection)) return;
    const ModelObjectPtrs &model_objects = selection.get_model()->objects;
    const Selection::IndicesList &volume_idxs = selection.get_volume_idxs();
    // no need to render nothing
    if (volume_idxs.empty()) return;
    // Iteration over selection because of world transformation matrix of object
    for (auto volume_id : volume_idxs) {
        const GLVolume *selected_volume = selection.get_volume(volume_id);
        const GLVolume::CompositeID &cid = selected_volume->composite_id;
        ModelObject *obj    = model_objects[cid.object_id];
        ModelVolume *volume = obj->volumes[cid.volume_id];
        auto it = m_glmodels.find(volume->id());
        assert(it != m_glmodels.end());
        GLModel &glmodel = it->second;
        const Transform3d trafo_matrix = selected_volume->world_matrix();
        auto* gouraud_shader = wxGetApp().get_shader("gouraud_light");
#if ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
        bool depth_test_enabled = ::glIsEnabled(GL_DEPTH_TEST);
#else
        glsafe(::glPushAttrib(GL_DEPTH_TEST));
#endif // ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
        glsafe(::glEnable(GL_DEPTH_TEST));
        gouraud_shader->start_using();
        const Camera& camera = wxGetApp().plater()->get_camera();
        const Transform3d& view_matrix = camera.get_view_matrix();
        const Transform3d view_model_matrix = view_matrix * trafo_matrix;
        gouraud_shader->set_uniform("view_model_matrix", view_model_matrix);
        gouraud_shader->set_uniform("projection_matrix", camera.get_projection_matrix());
        const Matrix3d view_normal_matrix = view_matrix.matrix().block(0, 0, 3, 3) * trafo_matrix.matrix().block(0, 0, 3, 3).inverse().transpose();
        gouraud_shader->set_uniform("view_normal_matrix", view_normal_matrix);
        glmodel.render();
        gouraud_shader->stop_using();
        if (m_show_wireframe) {
#if ENABLE_OPENGL_ES
            auto* contour_shader = wxGetApp().get_shader("wireframe");
#else
            auto *contour_shader = wxGetApp().get_shader("mm_contour");
#endif // ENABLE_OPENGL_ES
            contour_shader->start_using();
            contour_shader->set_uniform("offset", OpenGLManager::get_gl_info().is_mesa() ? 0.0005 : 0.00001);
            contour_shader->set_uniform("view_model_matrix", view_model_matrix);
            contour_shader->set_uniform("projection_matrix", camera.get_projection_matrix());
            const ColorRGBA color = glmodel.get_color();
            glmodel.set_color(ColorRGBA::WHITE());
#if ENABLE_GL_CORE_PROFILE
            if (!OpenGLManager::get_gl_info().is_core_profile())
#endif // ENABLE_GL_CORE_PROFILE
                glsafe(::glLineWidth(1.0f));
#if !ENABLE_OPENGL_ES
            glsafe(::glPolygonMode(GL_FRONT_AND_BACK, GL_LINE));
#endif // !ENABLE_OPENGL_ES
            glmodel.render();
#if !ENABLE_OPENGL_ES
            glsafe(::glPolygonMode(GL_FRONT_AND_BACK, GL_FILL));
#endif // !ENABLE_OPENGL_ES
            glmodel.set_color(color);
            contour_shader->stop_using();
        }
#if ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
        if (depth_test_enabled)
            glsafe(::glEnable(GL_DEPTH_TEST));
#else
        glsafe(::glPopAttrib());
#endif // ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
    }
}
References Slic3r::GLVolume::composite_id, Slic3r::GUI::GLModel::get_color(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::get_volume_ids(), Slic3r::GUI::Selection::get_volume_idxs(), glsafe, Slic3r::GUI::OpenGLManager::GLInfo::is_core_profile(), m_glmodels, Slic3r::GUI::GLGizmoBase::m_parent, m_show_wireframe, m_volume_ids, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GLVolume::CompositeID::object_id, Slic3r::Model::objects, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLVolume::CompositeID::volume_id, Slic3r::ModelObject::volumes, Slic3r::ColorRGBA::WHITE(), and Slic3r::GLVolume::world_matrix().
on_render_input_window()
void Slic3r::GUI::GLGizmoSimplify::on_render_input_window (float x, float y, float bottom_limit) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    create_gui_cfg();
    const Selection &selection = m_parent.get_selection();
    auto act_volume_ids = get_volume_ids(selection);
    if (act_volume_ids.empty()) {
        stop_worker_thread_request();
        close();
        if (! m_parent.get_selection().is_single_volume()) {
            MessageDialog msg((wxWindow*)wxGetApp().mainframe,
                _L("Simplification is currently only allowed when a single part is selected"),
                _L("Error"));
            msg.ShowModal();
        }
        return;
    }
    bool is_cancelling = false;
    bool is_worker_running = false;
    bool is_result_ready = false;
    int progress = 0;
    {
        std::lock_guard lk(m_state_mutex);
        is_cancelling = m_state.status == State::cancelling;
        is_worker_running = m_state.status == State::running;
        is_result_ready = !m_state.result.empty();
        progress = m_state.progress;
    }
    // Whether to trigger calculation after rendering is done.
    bool start_process = false;
    // Check selection of new volume (or change)
    // Do not reselect object when processing
    if (m_volume_ids != act_volume_ids) {
        bool change_window_position = m_volume_ids.empty();
        // select different model
        // close suggestion notification
        auto notification_manager = wxGetApp().plater()->get_notification_manager();
        for (const auto &id : act_volume_ids)
            notification_manager->remove_simplify_suggestion_with_id(id);
        m_volume_ids = std::move(act_volume_ids);
        init_model();
        // triangle count is calculated in init model
        m_original_triangle_count = m_triangle_count;
        // Default value of configuration
        m_configuration.decimate_ratio = 50.; // default value
        m_configuration.fix_count_by_ratio(m_original_triangle_count);
        m_configuration.use_count = false;
        // Create volumes name to describe what will be simplified
        std::string name = create_volumes_name(m_volume_ids, selection);
        if (name.length() > m_gui_cfg->max_char_in_name)
            name = name.substr(0, m_gui_cfg->max_char_in_name - 3) + "...";
        m_volumes_name = name;
        // Start processing. If we switched from another object, process will
        // stop the background thread and it will restart itself later.
        start_process = true;
        // set window position
        if (change_window_position) {
            ImVec2 pos;
            Size parent_size = m_parent.get_canvas_size();
            if (m_move_to_center) {
                m_move_to_center   = false;
                pos = ImVec2(parent_size.get_width() / 2 - m_gui_cfg->window_offset_x,
                             parent_size.get_height() / 2 - m_gui_cfg->window_offset_y);
            } else {
                // keep window wisible on canvas and close to mouse click
                pos = ImGui::GetMousePos();
                pos.x -= m_gui_cfg->window_offset_x;
                pos.y -= m_gui_cfg->window_offset_y;
                // minimal top left value
                ImVec2 tl(m_gui_cfg->window_padding,
                          m_gui_cfg->window_padding + m_parent.get_main_toolbar_height());
                if (pos.x < tl.x) pos.x = tl.x;
                if (pos.y < tl.y) pos.y = tl.y;
                // maximal bottom right value
                ImVec2 br(parent_size.get_width() - (2 * m_gui_cfg->window_offset_x + m_gui_cfg->window_padding),
                          parent_size.get_height() -(2 * m_gui_cfg->window_offset_y + m_gui_cfg->window_padding));
                if (pos.x > br.x) pos.x = br.x;
                if (pos.y > br.y) pos.y = br.y;
            }
            ImGui::SetNextWindowPos(pos, ImGuiCond_Always);
        }
    }
    bool is_multipart = (m_volume_ids.size() > 1);
    int flag = ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoResize |
               ImGuiWindowFlags_NoCollapse;
    m_imgui->begin(on_get_name(), flag);
    m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, tr_mesh_name + ":");
    ImGui::SameLine(m_gui_cfg->top_left_width);
    m_imgui->text(m_volumes_name);
    m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, tr_triangles + ":");
    ImGui::SameLine(m_gui_cfg->top_left_width);
    m_imgui->text(std::to_string(m_original_triangle_count));
    ImGui::Separator();
    if(ImGui::RadioButton("##use_error", !m_configuration.use_count) && !is_multipart) {
        m_configuration.use_count = !m_configuration.use_count;
        start_process = true;
    }
    ImGui::SameLine();
    m_imgui->disabled_begin(m_configuration.use_count);
    ImGui::Text("%s", tr_detail_level.c_str());
    std::vector<std::string> reduce_captions = {
        static_cast<std::string>(_u8L("Extra high")),
        static_cast<std::string>(_u8L("High")),
        static_cast<std::string>(_u8L("Medium")),
        static_cast<std::string>(_u8L("Low")),
        static_cast<std::string>(_u8L("Extra low"))
    };
    ImGui::SameLine(m_gui_cfg->bottom_left_width);
    ImGui::SetNextItemWidth(m_gui_cfg->input_width);
    static int reduction = 2;
    if(ImGui::SliderInt("##ReductionLevel", &reduction, 0, 4, reduce_captions[reduction].c_str())) {
        if (reduction < 0) reduction = 0;
        if (reduction > 4) reduction = 4;
        switch (reduction) {
        case 0: m_configuration.max_error = 1e-3f; break;
        case 1: m_configuration.max_error = 1e-2f; break;
        case 2: m_configuration.max_error = 0.1f; break;
        case 3: m_configuration.max_error = 0.5f; break;
        case 4: m_configuration.max_error = 1.f; break;
        }
        start_process = true;
    }
    m_imgui->disabled_end(); // !use_count
    if (ImGui::RadioButton("##use_count", m_configuration.use_count) && !is_multipart) {
        m_configuration.use_count = !m_configuration.use_count;
        start_process = true;
    } else if (ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled) && is_multipart)
        ImGui::SetTooltip("%s", _u8L("A multipart object can be simplified using only a Level of detail. "
                                     "If you want to enter a Decimate ratio, do the simplification separately.").c_str());
    ImGui::SameLine();
    // show preview result triangle count (percent)
    if (!m_configuration.use_count) {
        m_configuration.wanted_count = static_cast<uint32_t>(m_triangle_count);
        m_configuration.decimate_ratio =
            (1.0f - (m_configuration.wanted_count / (float) m_original_triangle_count)) * 100.f;
    }
    m_imgui->disabled_begin(!m_configuration.use_count);
    ImGui::Text("%s", tr_decimate_ratio.c_str());
    ImGui::SameLine(m_gui_cfg->bottom_left_width);
    ImGui::SetNextItemWidth(m_gui_cfg->input_width);
    const char * format = (m_configuration.decimate_ratio > 10)? "%.0f %%":
        ((m_configuration.decimate_ratio > 1)? "%.1f %%":"%.2f %%");
    if(m_imgui->slider_float("##decimate_ratio",  &m_configuration.decimate_ratio, 0.f, 100.f, format)){
        if (m_configuration.decimate_ratio < 0.f)
            m_configuration.decimate_ratio = 0.01f;
        if (m_configuration.decimate_ratio > 100.f)
            m_configuration.decimate_ratio = 100.f;
        m_configuration.fix_count_by_ratio(m_original_triangle_count);
        start_process = true;
    }
    ImGui::NewLine();
    ImGui::SameLine(m_gui_cfg->bottom_left_width);
    ImGui::Text(_u8L("%d triangles").c_str(), m_configuration.wanted_count);
    m_imgui->disabled_end(); // use_count
    ImGui::Checkbox(_u8L("Show wireframe").c_str(), &m_show_wireframe);
    m_imgui->disabled_begin(is_cancelling);
    if (m_imgui->button(_L("Close"))) {
        close();
    } else if (ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled) && is_cancelling)
        ImGui::SetTooltip("%s", _u8L("Operation already cancelling. Please wait few seconds.").c_str());
    m_imgui->disabled_end(); // state cancelling
    ImGui::SameLine();
    m_imgui->disabled_begin(is_worker_running || ! is_result_ready);
    if (m_imgui->button(_L("Apply"))) {
        apply_simplify();
    } else if (ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled) && is_worker_running)
        ImGui::SetTooltip("%s", _u8L("Can't apply when proccess preview.").c_str());
    m_imgui->disabled_end(); // state !settings
    // draw progress bar
    if (is_worker_running) { // apply or preview
        ImGui::SameLine(m_gui_cfg->bottom_left_width);
        // draw progress bar
        std::string progress_text = GUI::format(_L("Process %1% / 100"), std::to_string(progress));
        ImVec2 progress_size(m_gui_cfg->input_width, 0.f);
        ImGui::ProgressBar(progress / 100., progress_size, progress_text.c_str());
    }
    m_imgui->end();
    if (start_process)
        process();
}
References _L, _u8L, apply_simplify(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::GLGizmoSimplify::State::cancelling, ImGui::Checkbox(), close(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, create_gui_cfg(), Slic3r::GUI::create_volumes_name(), Slic3r::GUI::GLGizmoSimplify::Configuration::decimate_ratio, Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLGizmoSimplify::Configuration::fix_count_by_ratio(), Slic3r::GUI::format(), Slic3r::GUI::GLGizmoBase::format(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::GLCanvas3D::get_main_toolbar_height(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::get_volume_ids(), Slic3r::GUI::Size::get_width(), ImGui::GetMousePos(), ImGuiCond_Always, ImGuiHoveredFlags_AllowWhenDisabled, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoResize, init_model(), Slic3r::GUI::Selection::is_single_volume(), ImGui::IsItemHovered(), m_configuration, m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_imgui, m_move_to_center, m_original_triangle_count, Slic3r::GUI::GLGizmoBase::m_parent, m_show_wireframe, m_state, m_state_mutex, m_triangle_count, m_volume_ids, m_volumes_name, Slic3r::GUI::GLGizmoSimplify::Configuration::max_error, ImGui::NewLine(), on_get_name(), process(), Slic3r::GUI::GLGizmoSimplify::State::progress, ImGui::ProgressBar(), ImGui::RadioButton(), Slic3r::GUI::GLGizmoSimplify::State::result, Slic3r::GUI::GLGizmoSimplify::State::running, ImGui::SameLine(), ImGui::Separator(), ImGui::SetNextItemWidth(), ImGui::SetNextWindowPos(), ImGui::SetTooltip(), Slic3r::GUI::ImGuiWrapper::slider_float(), ImGui::SliderInt(), Slic3r::GUI::GLGizmoSimplify::State::status, stop_worker_thread_request(), ImGui::Text(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), tr_decimate_ratio, tr_detail_level, tr_mesh_name, tr_triangles, Slic3r::GUI::GLGizmoSimplify::Configuration::use_count, Slic3r::GUI::GLGizmoSimplify::Configuration::wanted_count, ImVec2::x, and ImVec2::y.
on_save()
virtual void Slic3r::GUI::GLGizmoBase::on_save (cereal::BinaryOutputArchive & ar) const inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::save().
on_set_hover_id()
virtual void Slic3r::GUI::GLGizmoBase::on_set_hover_id () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::set_hover_id().
on_set_state()
void Slic3r::GUI::GLGizmoSimplify::on_set_state () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    // Closing gizmo. e.g. selecting another one
    if (GLGizmoBase::m_state == GLGizmoBase::Off) {
        m_parent.toggle_model_objects_visibility(true);
        stop_worker_thread_request();
        m_volume_ids.clear(); // invalidate selected model
        m_glmodels.clear(); // free gpu memory
    } else if (GLGizmoBase::m_state == GLGizmoBase::On) {
        // when open by hyperlink it needs to show up
        request_rerender();
    }
}
References m_glmodels, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::m_state, m_volume_ids, Slic3r::GUI::GLGizmoBase::Off, Slic3r::GUI::GLGizmoBase::On, request_rerender(), stop_worker_thread_request(), and Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility().
on_start_dragging()
virtual void Slic3r::GUI::GLGizmoBase::on_start_dragging () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::use_grabbers().
on_stop_dragging()
virtual void Slic3r::GUI::GLGizmoBase::on_stop_dragging () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::do_stop_dragging(), and Slic3r::GUI::GLGizmoRotate::stop_dragging().
on_unregister_raycasters_for_picking()
virtual void Slic3r::GUI::GLGizmoBase::on_unregister_raycasters_for_picking () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking().
process()
void Slic3r::GUI::GLGizmoSimplify::process () private
{
    if (m_volume_ids.empty()) return;
    // m_volume->mesh().its.indices.empty()
    bool configs_match = false;
    bool result_valid  = false;
    bool is_worker_running = false;
    {
        std::lock_guard lk(m_state_mutex);
        configs_match = (m_volume_ids == m_state.volume_ids && m_state.config == m_configuration);
        result_valid = !m_state.result.empty();
        is_worker_running = m_state.status == State::running;
    }
    if ((result_valid || is_worker_running) && configs_match) {
        // Either finished or waiting for result already. Nothing to do.
        return;
    }
    if (is_worker_running && ! configs_match) {
        // Worker is running with outdated config. Stop it. It will
        // restart itself when cancellation is done.
        stop_worker_thread_request();
        return;
    }
    if (m_worker.joinable()) {
        // This can happen when process() is called after previous worker terminated,
        // but before the worker_finished callback was called. In this case, just join the thread,
        // the callback will check this and do nothing.
        m_worker.join();
    }
    // Copy configuration that will be used.
    m_state.config = m_configuration;
    m_state.volume_ids = m_volume_ids;
    m_state.status = State::running;
    // Create a copy of current meshes to pass to the worker thread.
    // Using unique_ptr instead of pass-by-value to avoid an extra
    // copy (which would happen when passing to std::thread).
    const Selection& selection = m_parent.get_selection();
    State::Data its;
    for (const auto &id : m_volume_ids) {
        const ModelVolume *volume = get_volume(id, selection);
        its[id] = std::make_unique<indexed_triangle_set>(volume->mesh().its); // copy
    }
    m_worker = std::thread([this](State::Data its) {
        // Checks that the UI thread did not request cancellation, throws if so.
        std::function<void(void)> throw_on_cancel = [this]() {
            std::lock_guard lk(m_state_mutex);
            if (m_state.status == State::cancelling)
                throw SimplifyCanceledException();
        };
        // Called by worker thread, updates progress bar.
        // Using CallAfter so the rerequest function is run in UI thread.
        std::function<void(int)> statusfn = [this](int percent) {
            std::lock_guard lk(m_state_mutex);
            m_state.progress = percent;
            call_after_if_active([this]() { request_rerender(); });
        };
        // Initialize.
        uint32_t triangle_count = 0;
        float    max_error = std::numeric_limits<float>::max();
        {
            std::lock_guard lk(m_state_mutex);
            if (m_state.config.use_count)
                triangle_count = m_state.config.wanted_count;
            if (! m_state.config.use_count)
                max_error = m_state.config.max_error;
            m_state.progress = 0;
            m_state.result.clear();
            m_state.status = State::Status::running;
        }
        // Start the actual calculation.
        try {
            for (const auto& it : its) {
                float me = max_error;
                its_quadric_edge_collapse(*it.second, triangle_count, &me, throw_on_cancel, statusfn);
            }
        } catch (SimplifyCanceledException &) {
            std::lock_guard lk(m_state_mutex);
            m_state.status = State::idle;
        }
        std::lock_guard lk(m_state_mutex);
        if (m_state.status == State::Status::running) {
            // We were not cancelled, the result is valid.
            m_state.status = State::Status::idle;
            m_state.result = std::move(its);
        }
        // Update UI. Use CallAfter so the function is run on UI thread.
        call_after_if_active([this]() { worker_finished(); });
    }, std::move(its));
}
References Slic3r::GUI::call_after_if_active(), Slic3r::GUI::GLGizmoSimplify::State::cancelling, Slic3r::GUI::GLGizmoSimplify::State::config, Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::get_volume(), Slic3r::GUI::GLGizmoSimplify::State::idle, Slic3r::its_quadric_edge_collapse(), m_configuration, Slic3r::GUI::GLGizmoBase::m_parent, m_state, m_state_mutex, m_volume_ids, m_worker, Slic3r::GUI::GLGizmoSimplify::Configuration::max_error, Slic3r::GUI::GLGizmoSimplify::State::progress, request_rerender(), Slic3r::GUI::GLGizmoSimplify::State::result, Slic3r::GUI::GLGizmoSimplify::State::running, Slic3r::GUI::GLGizmoSimplify::State::status, stop_worker_thread_request(), Slic3r::GUI::GLGizmoSimplify::Configuration::use_count, void(), Slic3r::GUI::GLGizmoSimplify::State::volume_ids, Slic3r::GUI::GLGizmoSimplify::Configuration::wanted_count, and worker_finished().
Referenced by on_render_input_window(), and worker_finished().
register_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].register_raycasters_for_picking((m_group_id >= 0) ? m_group_id : i);
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking().
register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking () inline inherited
{ register_grabbers_for_picking(); on_register_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_register_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_register_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ on_render(); }
References Slic3r::GUI::GLGizmoBase::on_render().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_render().
render_grabbers() [1/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
}
References Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointType >::size().
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    render_grabbers(0, m_grabbers.size() - 1, size, false);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [3/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (size_t first, size_t last, float size, bool force_hover) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    glsafe(::glDisable(GL_CULL_FACE));
    for (size_t i = first; i <= last; ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(force_hover ? true : m_hover_id == (int)i, size);
    }
    glsafe(::glEnable(GL_CULL_FACE));
    shader->stop_using();
}
References glsafe, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // imgui windows that don't have an initial size needs to be processed once to get one
        // and are not rendered in the first frame
        // so, we forces to render another frame the first time the imgui window is shown
        // https://github.com/ocornut/imgui/issues/2949
        m_parent.set_as_dirty();
        m_parent.request_extra_frame();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), Slic3r::GUI::GLCanvas3D::request_extra_frame(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
request_rerender()
void Slic3r::GUI::GLGizmoSimplify::request_rerender (bool force = false) private
{
    int64_t now = m_parent.timestamp_now();
    if (force || now > m_last_rerender_timestamp + 250) { // 250 ms
        set_dirty();
        m_parent.schedule_extra_frame(0);
        m_last_rerender_timestamp = now;
    }
}
References m_last_rerender_timestamp, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::schedule_extra_frame(), Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLCanvas3D::timestamp_now().
Referenced by on_set_state(), process(), and worker_finished().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
set_center_position()
void Slic3r::GUI::GLGizmoSimplify::set_center_position () private
{
    m_move_to_center = true;
}
References m_move_to_center.
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c.
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by Slic3r::GUI::GLGizmoCut3D::process_cut_line(), and request_rerender().
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    // do not change hover id during dragging
    assert(!m_dragging);
    // allow empty grabbers when not using grabbers but use hover_id - flatten, rotate
//    if (!m_grabbers.empty() && id >= (int) m_grabbers.size())
//        return;
    m_hover_id = id;
    on_set_hover_id();
}
References Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLGizmoEmboss::on_set_state().
stop_worker_thread_request()
bool Slic3r::GUI::GLGizmoSimplify::stop_worker_thread_request () private
{
    std::lock_guard lk(m_state_mutex);
    if (m_state.status != State::running) return false;
    m_state.status = State::Status::cancelling;
    return true;
}
References Slic3r::GUI::GLGizmoSimplify::State::cancelling, m_state, m_state_mutex, Slic3r::GUI::GLGizmoSimplify::State::running, and Slic3r::GUI::GLGizmoSimplify::State::status.
Referenced by ~GLGizmoSimplify(), on_esc_key_down(), on_render_input_window(), on_set_state(), and process().
unregister_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].unregister_raycasters_for_picking();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers.
Referenced by Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking().
unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking () inline inherited
{ unregister_grabbers_for_picking(); on_unregister_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
update_model()
void Slic3r::GUI::GLGizmoSimplify::update_model (const State::Data & data) private
{
    // check that model exist
    if (m_glmodels.empty()) return;
    // check that result is for actual gl models
    size_t model_count = m_glmodels.size();
    if (data.size() != model_count) return;
    m_triangle_count = 0;
    for (const auto &item : data) {
        const indexed_triangle_set &its = *item.second;
        auto it = m_glmodels.find(item.first);
        assert(it != m_glmodels.end());
        GLModel &glmodel = it->second;
        auto color = glmodel.get_color();
        // when not reset it keeps old shape
        glmodel.reset();
#if ENABLE_OPENGL_ES
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P3N3E3 };
        init_data.reserve_vertices(3 * its.indices.size());
        init_data.reserve_indices(3 * its.indices.size());
        // vertices + indices
        std::array<Vec3f, 3> barycentric_coords = { Vec3f::UnitX(), Vec3f::UnitY(), Vec3f::UnitZ() };
        unsigned int vertices_counter = 0;
        for (uint32_t i = 0; i < its.indices.size(); ++i) {
            const stl_triangle_vertex_indices face = its.indices[i];
            const stl_vertex                  vertex[3] = { its.vertices[face[0]], its.vertices[face[1]], its.vertices[face[2]] };
            const stl_vertex                  n = face_normal_normalized(vertex);
            for (size_t j = 0; j < 3; ++j) {
                init_data.add_vertex(vertex[j], n, barycentric_coords[j]);
            }
            vertices_counter += 3;
            init_data.add_triangle(vertices_counter - 3, vertices_counter - 2, vertices_counter - 1);
        }
        glmodel.init_from(std::move(init_data));
#else
        glmodel.init_from(its);
#endif // ENABLE_OPENGL_ES
        glmodel.set_color(color);
        m_triangle_count += its.indices.size();
    }
}
References Slic3r::GUI::GLModel::Geometry::add_triangle(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::face_normal_normalized(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::GLModel::get_color(), indexed_triangle_set::indices, Slic3r::GUI::GLModel::init_from(), m_glmodels, m_triangle_count, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::reset(), Slic3r::GUI::GLModel::set_color(), Slic3r::GUI::GLModel::Geometry::Triangles, and indexed_triangle_set::vertices.
Referenced by worker_finished().
use_grabbers()
bool Slic3r::GUI::GLGizmoBase::use_grabbers (const wxMouseEvent & mouse_event) protected inherited
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
Parameters
mouse_event Keep information about mouse click
Returns
same as on_mouse
{
    bool is_dragging_finished = false;
    if (mouse_event.Moving()) {
        // it should not happen but for sure
        assert(!m_dragging);
        if (m_dragging) is_dragging_finished = true;
        else return false;
    }
    if (mouse_event.LeftDown()) {
        Selection &selection = m_parent.get_selection();
        if (!selection.is_empty() && m_hover_id != -1 /* &&
            (m_grabbers.empty() || m_hover_id < static_cast<int>(m_grabbers.size()))*/) {
            selection.setup_cache();
            m_dragging = true;
            for (auto &grabber : m_grabbers) grabber.dragging = false;
//            if (!m_grabbers.empty() && m_hover_id < int(m_grabbers.size()))
//                m_grabbers[m_hover_id].dragging = true;
            on_start_dragging();
            // Let the plater know that the dragging started
            m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_STARTED));
            m_parent.set_as_dirty();
            return true;
        }
    } else if (m_dragging) {
        // when mouse cursor leave window than finish actual dragging operation
        bool is_leaving = mouse_event.Leaving();
        if (mouse_event.Dragging()) {
            Point      mouse_coord(mouse_event.GetX(), mouse_event.GetY());
            auto       ray = m_parent.mouse_ray(mouse_coord);
            UpdateData data(ray, mouse_coord);
            on_dragging(data);
            wxGetApp().obj_manipul()->set_dirty();
            m_parent.set_as_dirty();
            return true;
        }
        else if (mouse_event.LeftUp() || is_leaving || is_dragging_finished) {
            do_stop_dragging(is_leaving);
            return true;
        }
    }
    return false;
}
References Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_ray(), Slic3r::GUI::GLGizmoBase::on_dragging(), Slic3r::GUI::GLGizmoBase::on_start_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::Selection::setup_cache().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_mouse(), Slic3r::GUI::GLGizmoRotate::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation().
wants_enter_leave_snapshots()
virtual bool Slic3r::GUI::GLGizmoBase::wants_enter_leave_snapshots () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
worker_finished()
void Slic3r::GUI::GLGizmoSimplify::worker_finished () private
{
    {
        std::lock_guard lk(m_state_mutex);
        if (m_state.status == State::running) {
            // Someone started the worker again, before this callback
            // was called. Do nothing.
            return;
        }
    }
    if (m_worker.joinable())
        m_worker.join();
    if (GLGizmoBase::m_state == Off)
        return;
    const auto &result = m_state.result;
    if (!result.empty())
        update_model(result);
    if (m_state.config != m_configuration || m_state.volume_ids != m_volume_ids) {
        // Settings were changed, restart the worker immediately.
        process();
    }
    request_rerender(true);
}
References Slic3r::GUI::GLGizmoSimplify::State::config, m_configuration, Slic3r::GUI::GLGizmoBase::m_state, m_state, m_state_mutex, m_volume_ids, m_worker, Slic3r::GUI::GLGizmoBase::Off, process(), request_rerender(), Slic3r::GUI::GLGizmoSimplify::State::result, Slic3r::GUI::GLGizmoSimplify::State::running, Slic3r::GUI::GLGizmoSimplify::State::status, update_model(), and Slic3r::GUI::GLGizmoSimplify::State::volume_ids.
Referenced by process().
Member Data Documentation
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
GRABBER_ELEMENTS_MAX_COUNT
const unsigned int Slic3r::GUI::GLGizmoBase::GRABBER_ELEMENTS_MAX_COUNT = 7 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c { nullptr } protected inherited
Referenced by Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoFdmSupports::auto_generate(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::GLGizmoCut3D::check_and_update_connectors_state(), Slic3r::GUI::GLGizmoCut3D::data_changed(), Slic3r::GUI::GLGizmoFdmSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoCut3D::has_valid_contour(), init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoCut3D::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::GLGizmoCut3D::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoHollow::reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), Slic3r::GUI::GLGizmoCut3D::render_clipper_cut(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::GLGizmoCut3D::reset_connectors(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut3D::update_bb(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_configuration
Configuration Slic3r::GUI::GLGizmoSimplify::m_configuration private
Referenced by on_render_input_window(), process(), and worker_finished().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty { false } private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging { false } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::GLGizmoBase::set_hover_id(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render { true } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_glmodels
std::map<ObjectID, GLModel> Slic3r::GUI::GLGizmoSimplify::m_glmodels private
Referenced by init_model(), on_render(), on_set_state(), and update_model().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoRotate::disable_grabber(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoRotate::enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLGizmoRotate::start_dragging(), Slic3r::GUI::GLGizmoRotate::stop_dragging(), Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate::GLGizmoRotate(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), and Slic3r::GUI::GLGizmoRotate::set_group_id().
m_gui_cfg
std::optional<GuiCfg> Slic3r::GUI::GLGizmoSimplify::m_gui_cfg private
Referenced by create_gui_cfg(), and on_render_input_window().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id { -1 } protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_xy(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_z(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoCut3D::is_selection_changed(), Slic3r::GUI::GLGizmoCut3D::on_dragging(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_dragging(), Slic3r::GUI::GLGizmoScale3D::on_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging(), Slic3r::GUI::GLGizmoCut3D::on_stop_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename().
M_ICON_FILENAME
const std::string Slic3r::GUI::GLGizmoSimplify::M_ICON_FILENAME = "cut.svg" static private
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), Slic3r::GUI::GLGizmoCut3D::add_horizontal_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::add_vertical_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::adjust_window_position(), create_gui_cfg(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_style_add_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_popup(), Slic3r::GUI::GLGizmoEmboss::draw_style_save_as_popup(), Slic3r::GUI::GLGizmoEmboss::draw_text_input(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::GLGizmoCut3D::init_input_window_data(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_build_size(), Slic3r::GUI::GLGizmoCut3D::render_combo(), Slic3r::GUI::GLGizmoCut3D::render_connectors_input_window(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoCut3D::render_double_input(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoCut3D::render_input_window_warning(), Slic3r::GUI::GLGizmoCut3D::render_move_center_input(), Slic3r::GUI::GLGizmoCut3D::render_reset_button(), Slic3r::GUI::GLGizmoCut3D::render_shortcuts(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
m_last_rerender_timestamp
int64_t Slic3r::GUI::GLGizmoSimplify::m_last_rerender_timestamp = std::numeric_limits<int64_t>::min() private
Referenced by request_rerender().
m_move_to_center
bool Slic3r::GUI::GLGizmoSimplify::m_move_to_center private
Referenced by on_render_input_window(), and set_center_position().
m_original_triangle_count
size_t Slic3r::GUI::GLGizmoSimplify::m_original_triangle_count private
Referenced by on_render_input_window().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::add_connector(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), apply_simplify(), Slic3r::GUI::GLGizmoCut3D::bounding_box(), Slic3r::GUI::GLGizmoEmboss::calculate_scale(), Slic3r::GUI::GLGizmoEmboss::close(), close(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoFlatten::data_changed(), Slic3r::GUI::GLGizmoMeasure::data_changed(), Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoRotate3D::data_changed(), Slic3r::GUI::GLGizmoCut3D::delete_selected_connectors(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoEmboss::do_rotate(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoEmboss::do_translate(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeasure::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), init_model(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeasure::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoCut3D::on_load(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_shortcut_key(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoEmboss::on_stop_dragging(), Slic3r::GUI::GLGizmoMove3D::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoScale3D::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::GLGizmoEmboss::process(), process(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_cut_line(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::register_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::remove_selected_sphere_raycaster(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), request_rerender(), Slic3r::GUI::GLGizmoCut3D::reset_cut_by_contours(), Slic3r::GUI::GLGizmoCut3D::reset_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), Slic3r::GUI::GLGizmoCut3D::set_volumes_picking_state(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoCut3D::transformed_bounding_box(), Slic3r::GUI::GLGizmoHollow::unregister_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::unregister_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoCut3D::on_init(), Slic3r::GUI::GLGizmoEmboss::on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), Slic3r::GUI::GLGizmoHollow::on_init(), Slic3r::GUI::GLGizmoMeasure::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), and Slic3r::GUI::GLGizmoSlaSupports::on_init().
m_show_wireframe
bool Slic3r::GUI::GLGizmoSimplify::m_show_wireframe private
Referenced by on_render(), and on_render_input_window().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_state
State Slic3r::GUI::GLGizmoSimplify::m_state private
Referenced by apply_simplify(), on_render_input_window(), process(), stop_worker_thread_request(), and worker_finished().
m_state_mutex
std::mutex Slic3r::GUI::GLGizmoSimplify::m_state_mutex private
Referenced by on_render_input_window(), process(), stop_worker_thread_request(), and worker_finished().
m_triangle_count
size_t Slic3r::GUI::GLGizmoSimplify::m_triangle_count private
Referenced by init_model(), on_render_input_window(), and update_model().
m_volume_ids
std::set<ObjectID> Slic3r::GUI::GLGizmoSimplify::m_volume_ids private
Referenced by apply_simplify(), init_model(), on_render(), on_render_input_window(), on_set_state(), process(), and worker_finished().
m_volumes_name
std::string Slic3r::GUI::GLGizmoSimplify::m_volumes_name private
Referenced by on_render_input_window().
m_worker
std::thread Slic3r::GUI::GLGizmoSimplify::m_worker private
Referenced by ~GLGizmoSimplify(), process(), and worker_finished().
NO_SHORTCUT_KEY_VALUE
const int Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE = 0 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
tr_decimate_ratio
const std::string Slic3r::GUI::GLGizmoSimplify::tr_decimate_ratio private
Referenced by create_gui_cfg(), and on_render_input_window().
tr_detail_level
const std::string Slic3r::GUI::GLGizmoSimplify::tr_detail_level private
Referenced by create_gui_cfg(), and on_render_input_window().
tr_mesh_name
const std::string Slic3r::GUI::GLGizmoSimplify::tr_mesh_name private
Referenced by create_gui_cfg(), and on_render_input_window().
tr_triangles
const std::string Slic3r::GUI::GLGizmoSimplify::tr_triangles private
Referenced by create_gui_cfg(), and on_render_input_window().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoSimplify.hpp
src/slic3r/GUI/Gizmos/GLGizmoSimplify.cpp