Prusa Slicer: Slic3r::PrintObjectStatusDB Class Reference
Slic3r::PrintObjectStatusDB Class Reference
Classes
struct iterator_range
Public Types
using iterator = std::multiset< PrintObjectStatus >::iterator
using const_iterator = std::multiset< PrintObjectStatus >::const_iterator
Public Member Functions
PrintObjectStatusDB (const PrintObjectPtrs &print_objects)
iterator_range get_range (const ModelObject &model_object) const
iterator_range get_range (const ModelObjectStatus &model_object_status) const
size_t count (const ModelObject &model_object)
std::multiset< PrintObjectStatus >::iterator begin ()
std::multiset< PrintObjectStatus >::iterator end ()
void clear ()
Private Attributes
std::multiset< PrintObjectStatus > m_db
Detailed Description
Member Typedef Documentation
const_iterator
using Slic3r::PrintObjectStatusDB::const_iterator = std::multiset<PrintObjectStatus>::const_iterator
iterator
using Slic3r::PrintObjectStatusDB::iterator = std::multiset<PrintObjectStatus>::iterator
Constructor & Destructor Documentation
PrintObjectStatusDB()
Slic3r::PrintObjectStatusDB::PrintObjectStatusDB (const PrintObjectPtrs & print_objects) inline
{
        for (PrintObject *print_object : print_objects)
            m_db.emplace(PrintObjectStatus(print_object));
    }
Member Function Documentation
begin()
std::multiset< PrintObjectStatus >::iterator Slic3r::PrintObjectStatusDB::begin () inline
{ return m_db.begin(); }
clear()
void Slic3r::PrintObjectStatusDB::clear () inline
                 {
        m_db.clear();
    }
Referenced by Slic3r::Print::apply().
count()
size_t Slic3r::PrintObjectStatusDB::count (const ModelObject & model_object) inline
{
        return m_db.count(PrintObjectStatus(model_object.id()));
    }
References Slic3r::ObjectBase::id().
Referenced by Slic3r::Print::apply().
end()
std::multiset< PrintObjectStatus >::iterator Slic3r::PrintObjectStatusDB::end () inline
{ return m_db.end(); }
get_range() [1/2]
iterator_range Slic3r::PrintObjectStatusDB::get_range (const ModelObject & model_object) const inline
{
        return m_db.equal_range(PrintObjectStatus(model_object.id()));
    }
References Slic3r::ObjectBase::id().
Referenced by Slic3r::Print::apply().
get_range() [2/2]
iterator_range Slic3r::PrintObjectStatusDB::get_range (const ModelObjectStatus & model_object_status) const inline
{
        return m_db.equal_range(PrintObjectStatus(model_object_status.id));
    }
References Slic3r::ModelObjectStatus::id.
Member Data Documentation
m_db
std::multiset<PrintObjectStatus> Slic3r::PrintObjectStatusDB::m_db private
The documentation for this class was generated from the following file:
src/libslic3r/PrintApply.cpp