Prusa Slicer: libnest2d::selections::SelectionBoilerplate< RawShape > Class Template Reference
libnest2d::selections::SelectionBoilerplate< RawShape > Class Template Reference
#include <src/libnest2d/include/libnest2d/selections/selection_boilerplate.hpp>
Public Types
using ShapeType = RawShape
using Item = _Item< RawShape >
using ItemGroup = _ItemGroup< RawShape >
using PackGroup = _PackGroup< RawShape >
Public Member Functions
const PackGroup & getResult () const
int lastPackedBinId () const
void progressIndicator (ProgressFunction fn)
void stopCondition (StopCondition cond)
void clear ()
Protected Member Functions
template<class Placer , class Container , class Bin , class PCfg >
void remove_unpackable_items (Container &c, const Bin &bin, const PCfg &pcfg)
Protected Attributes
PackGroup packed_bins_
ProgressFunction progress_ = [](unsigned){}
StopCondition stopcond_ = [](){ return false; }
int last_packed_bin_id_ = -1
Detailed Description
template<class RawShape>
class libnest2d::selections::SelectionBoilerplate< RawShape >
Member Typedef Documentation
Item
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::Item = _Item<RawShape>
ItemGroup
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::ItemGroup = _ItemGroup<RawShape>
PackGroup
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::PackGroup = _PackGroup<RawShape>
ShapeType
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::ShapeType = RawShape
Member Function Documentation
clear()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::clear () inline
{ packed_bins_.clear(); }
References libnest2d::selections::SelectionBoilerplate< RawShape >::packed_bins_.
getResult()
template<class RawShape > const PackGroup & libnest2d::selections::SelectionBoilerplate< RawShape >::getResult () const inline
{
        return packed_bins_;
    }
References libnest2d::selections::SelectionBoilerplate< RawShape >::packed_bins_.
lastPackedBinId()
template<class RawShape > int libnest2d::selections::SelectionBoilerplate< RawShape >::lastPackedBinId () const inline
{ return last_packed_bin_id_; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::last_packed_bin_id_.
progressIndicator()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::progressIndicator (ProgressFunction fn) inline
{ progress_ = fn; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::progress_.
remove_unpackable_items()
template<class RawShape > template<class Placer , class Container , class Bin , class PCfg > void libnest2d::selections::SelectionBoilerplate< RawShape >::remove_unpackable_items (Container & c, const Bin & bin, const PCfg & pcfg) inline protected
    {
        // Safety test: try to pack each item into an empty bin. If it fails
        // then it should be removed from the list
        auto it = c.begin();
        while (it != c.end() && !stopcond_()) {
            // WARNING: The copy of itm needs to be created before Placer.
            // Placer is working with references and its destructor still
            // manipulates the item this is why the order of stack creation
            // matters here.
            const Item& itm = *it;
            Item cpy{itm};
            Placer p{bin};
            p.configure(pcfg);
            if (itm.area() <= 0 || !p.pack(cpy)) {
                static_cast<Item&>(*it).binId(BIN_ID_UNSET);
                it = c.erase(it);
            }
            else it++;
        }
    }
References libnest2d::_Item< RawShape >::area(), libnest2d::BIN_ID_UNSET, libnest2d::_Item< RawShape >::binId(), and libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_.
stopCondition()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::stopCondition (StopCondition cond) inline
{ stopcond_ = cond; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_.
Member Data Documentation
last_packed_bin_id_
template<class RawShape > int libnest2d::selections::SelectionBoilerplate< RawShape >::last_packed_bin_id_ = -1 protected
Referenced by libnest2d::selections::SelectionBoilerplate< RawShape >::lastPackedBinId(), and libnest2d::selections::_FirstFitSelection< RawShape >::packItems().
packed_bins_
template<class RawShape > PackGroup libnest2d::selections::SelectionBoilerplate< RawShape >::packed_bins_ protected
Referenced by libnest2d::selections::SelectionBoilerplate< RawShape >::clear(), and libnest2d::selections::SelectionBoilerplate< RawShape >::getResult().
progress_
template<class RawShape > ProgressFunction libnest2d::selections::SelectionBoilerplate< RawShape >::progress_ = [](unsigned){} protected
Referenced by libnest2d::selections::_DJDHeuristic< RawShape >::packItems(), libnest2d::selections::_FillerSelection< RawShape >::packItems(), libnest2d::selections::_FirstFitSelection< RawShape >::packItems(), and libnest2d::selections::SelectionBoilerplate< RawShape >::progressIndicator().
stopcond_
template<class RawShape > StopCondition libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_ = [](){ return false; } protected
Referenced by libnest2d::selections::_DJDHeuristic< RawShape >::packItems(), libnest2d::selections::_FirstFitSelection< RawShape >::packItems(), libnest2d::selections::SelectionBoilerplate< RawShape >::remove_unpackable_items(), and libnest2d::selections::SelectionBoilerplate< RawShape >::stopCondition().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/selections/selection_boilerplate.hpp