Prusa Slicer: Slic3r::internal::format Namespace Reference
Slic3r::internal::format Namespace Reference
Classes
struct utf8_buffer
Functions
template<typename T >
T && cook (T &&arg)
std::string format_recursive (boost::format &message)
template<typename TValue , typename... TArgs>
std::string format_recursive (boost::format &message, TValue &&arg, TArgs &&... args)
std::ostream & operator<< (std::ostream &os, const utf8_buffer &v)
const utf8_buffer cook (const wxString &arg)
const utf8_buffer cook (wxString &arg)
const utf8_buffer cook (wxString &&arg)
Class Documentation
Slic3r::internal::format::utf8_buffer
struct Slic3r::internal::format::utf8_buffer
Class Members
wxScopedCharBuffer data
Function Documentation
cook() [1/4]
const utf8_buffer Slic3r::internal::format::cook (const wxString & arg) inline
{
    return utf8_buffer{ arg.ToUTF8() };
  }
References arg().
cook() [2/4]
template<typename T > T && Slic3r::internal::format::cook (T && arg) inline
{
        return std::forward<T>(arg);
    }
References arg().
Referenced by format_recursive().
cook() [3/4]
const utf8_buffer Slic3r::internal::format::cook (wxString && arg) inline
{
    return utf8_buffer{ arg.ToUTF8() };
  }
References arg().
cook() [4/4]
const utf8_buffer Slic3r::internal::format::cook (wxString & arg) inline
{
    return utf8_buffer{ arg.ToUTF8() };
  }
References arg().
format_recursive() [1/2]
std::string Slic3r::internal::format::format_recursive (boost::format & message) inline
{
        return message.str();
    }
Referenced by Slic3r::format(), Slic3r::format(), format_recursive(), Slic3r::GUI::format_wxstr(), and Slic3r::GUI::format_wxstr().
format_recursive() [2/2]
template<typename TValue , typename... TArgs> std::string Slic3r::internal::format::format_recursive (boost::format & message, TValue && arg, TArgs &&... args)
{
      // Format, possibly convert the argument by the "cook" function.
        message % cook(std::forward<TValue>(arg));
        return format_recursive(message, std::forward<TArgs>(args)...);
    }
References arg(), cook(), and format_recursive().
operator<<()
std::ostream & Slic3r::internal::format::operator<< (std::ostream & os, const utf8_buffer & v) inline
{
    os << v.data.data();
    return os;
  }
References Slic3r::internal::format::utf8_buffer::data.