Prusa Slicer: marchsq::_RasterTraits< T, Enable > Struct Template Reference
marchsq::_RasterTraits< T, Enable > Struct Template Reference
#include <src/libslic3r/MarchingSquares.hpp>
Public Types
using ValueType = typename T::ValueType
Static Public Member Functions
static ValueType get (const T &raster, size_t row, size_t col)
static size_t rows (const T &raster)
static size_t cols (const T &raster)
Detailed Description
template<class T, class Enable = void>
struct marchsq::_RasterTraits< T, Enable >
Member Typedef Documentation
ValueType
template<class T , class Enable = void> using marchsq::_RasterTraits< T, Enable >::ValueType = typename T::ValueType
Member Function Documentation
cols()
template<class T , class Enable = void> static size_t marchsq::_RasterTraits< T, Enable >::cols (const T & raster) static
Referenced by marchsq::__impl::cols().
get()
template<class T , class Enable = void> static ValueType marchsq::_RasterTraits< T, Enable >::get (const T & raster, size_t row, size_t col) static
Referenced by marchsq::__impl::isoval().
rows()
template<class T , class Enable = void> static size_t marchsq::_RasterTraits< T, Enable >::rows (const T & raster) static
Referenced by marchsq::__impl::rows().
The documentation for this struct was generated from the following file:
src/libslic3r/MarchingSquares.hpp