Prusa Slicer: Slic3r::MKS Class Reference
Slic3r::MKS Class Reference
#include <src/slic3r/Utils/MKS.hpp>
Public Types
typedef Http::ProgressFn ProgressFn
typedef std::function< void(wxString)> ErrorFn
typedef std::function< void(wxString, wxString)> InfoFn
Public Member Functions
MKS (DynamicPrintConfig *config)
~MKS () override=default
const char * get_name () const override
bool test (wxString &curl_msg) const override
wxString get_test_ok_msg () const override
wxString get_test_failed_msg (wxString &msg) const override
bool upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const override
bool has_auto_discovery () const override
bool can_test () const override
PrintHostPostUploadActions get_post_upload_actions () const override
std::string get_host () const override
virtual bool supports_multiple_printers () const
virtual bool get_groups (wxArrayString &) const
virtual bool get_printers (wxArrayString &) const
virtual bool get_storage (wxArrayString &, wxArrayString &) const
Static Public Member Functions
static PrintHost * get_print_host (DynamicPrintConfig *config)
Protected Member Functions
virtual wxString format_error (const std::string &body, const std::string &error, unsigned status) const
Private Member Functions
std::string get_upload_url (const std::string &filename) const
bool start_print (wxString &msg, const std::string &filename) const
int get_err_code_from_body (const std::string &body) const
Private Attributes
std::string m_host
std::string m_console_port
Detailed Description
Member Typedef Documentation
ErrorFn
typedef std::function<void(wxString)> Slic3r::PrintHost::ErrorFn inherited
InfoFn
typedef std::function<void(wxString , wxString)> Slic3r::PrintHost::InfoFn inherited
ProgressFn
typedef Http::ProgressFn Slic3r::PrintHost::ProgressFn inherited
Constructor & Destructor Documentation
MKS()
Slic3r::MKS::MKS (DynamicPrintConfig * config) explicit
                                   :
  m_host(config->opt_string("print_host")), m_console_port("8080")
{}
~MKS()
Slic3r::MKS::~MKS () override default
Member Function Documentation
can_test()
bool Slic3r::MKS::can_test () const inline override virtual
Implements Slic3r::PrintHost.
{ return true; }
format_error()
wxString Slic3r::PrintHost::format_error (const std::string & body, const std::string & error, unsigned status) const protected virtual inherited
{
    if (status != 0) {
        auto wxbody = wxString::FromUTF8(body.data());
        return wxString::Format("HTTP %u: %s", status, wxbody);
    } else {
        return wxString::FromUTF8(error.data());
    }
}
References error.
Referenced by Slic3r::Duet::connect(), Slic3r::PrusaLink::post_inner(), Slic3r::PrusaLink::put_inner(), Slic3r::Duet::start_print(), Slic3r::AstroBox::test(), Slic3r::FlashAir::test(), Slic3r::Moonraker::test(), Slic3r::OctoPrint::test(), Slic3r::PrusaLink::test(), Slic3r::Repetier::test(), Slic3r::PrusaLink::test_with_method_check(), Slic3r::AstroBox::upload(), Slic3r::Duet::upload(), Slic3r::FlashAir::upload(), upload(), Slic3r::Moonraker::upload(), Slic3r::Repetier::upload(), and Slic3r::OctoPrint::upload_inner_with_host().
get_err_code_from_body()
int Slic3r::MKS::get_err_code_from_body (const std::string & body) const private
{
  pt::ptree root;
  std::istringstream iss(body); // wrap returned json to istringstream
  pt::read_json(iss, root);
  return root.get<int>("err", 0);
}
Referenced by upload().
get_groups()
virtual bool Slic3r::PrintHost::get_groups (wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
get_host()
std::string Slic3r::MKS::get_host () const inline override virtual
Implements Slic3r::PrintHost.
{ return m_host; }
References m_host.
get_name()
const char * Slic3r::MKS::get_name () const override virtual
Implements Slic3r::PrintHost.
{ return "MKS"; }
get_post_upload_actions()
PrintHostPostUploadActions Slic3r::MKS::get_post_upload_actions () const inline override virtual
Implements Slic3r::PrintHost.
{ return PrintHostPostUploadAction::StartPrint; }
References Slic3r::StartPrint.
get_print_host()
PrintHost * Slic3r::PrintHost::get_print_host (DynamicPrintConfig * config) static inherited
{
    PrinterTechnology tech = ptFFF;
    {
        const auto opt = config->option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
        if (opt != nullptr) {
            tech = opt->value;
        }
    }
    if (tech == ptFFF) {
        const auto opt = config->option<ConfigOptionEnum<PrintHostType>>("host_type");
        const auto host_type = opt != nullptr ? opt->value : htOctoPrint;
        switch (host_type) {
            case htOctoPrint: return new OctoPrint(config);
            case htDuet:      return new Duet(config);
            case htFlashAir:  return new FlashAir(config);
            case htAstroBox:  return new AstroBox(config);
            case htRepetier:  return new Repetier(config);
            case htPrusaLink: return new PrusaLink(config);
            case htPrusaConnect: return new PrusaConnect(config);
            case htMKS:       return new MKS(config);
            case htMoonraker: return new Moonraker(config);
            default:          return nullptr;
        }
    } else {
        return new SL1Host(config);
    }
}
References Slic3r::htAstroBox, Slic3r::htDuet, Slic3r::htFlashAir, Slic3r::htMKS, Slic3r::htMoonraker, Slic3r::htOctoPrint, Slic3r::htPrusaConnect, Slic3r::htPrusaLink, Slic3r::htRepetier, Slic3r::ConfigBase::option(), Slic3r::ptFFF, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::PhysicalPrinterDialog::update_printers(), and Slic3r::GUI::PhysicalPrinterDialog::update_printhost_buttons().
get_printers()
virtual bool Slic3r::PrintHost::get_printers (wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
get_storage()
virtual bool Slic3r::PrintHost::get_storage (wxArrayString & , wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::PrusaLink, and Slic3r::PrusaConnect.
{ return false; }
get_test_failed_msg()
wxString Slic3r::MKS::get_test_failed_msg (wxString & msg) const override virtual
Implements Slic3r::PrintHost.
{
  return GUI::format_wxstr("%s: %s", _L("Could not connect to MKS"), msg);
}
References _L, and Slic3r::GUI::format_wxstr().
get_test_ok_msg()
wxString Slic3r::MKS::get_test_ok_msg () const override virtual
Implements Slic3r::PrintHost.
{
  return _(L("Connection to MKS works correctly."));
}
References _, and L.
get_upload_url()
std::string Slic3r::MKS::get_upload_url (const std::string & filename) const private
{
  return (boost::format("http://%1%/upload?X-Filename=%2%")
    % m_host
    % Http::url_encode(filename)).str();
}
References m_host, and Slic3r::Http::url_encode().
Referenced by upload().
has_auto_discovery()
bool Slic3r::MKS::has_auto_discovery () const inline override virtual
Implements Slic3r::PrintHost.
{ return false; }
start_print()
bool Slic3r::MKS::start_print (wxString & msg, const std::string & filename) const private
{
  // For some reason printer firmware does not want to respond on gcode commands immediately after file upload.
  // So we just introduce artificial delay to workaround it.
  // TODO: Inspect reasons
  std::this_thread::sleep_for(std::chrono::milliseconds(1500));
  Utils::TCPConsole console(m_host, m_console_port);
  console.enqueue_cmd(std::string("M23 ") + filename);
  console.enqueue_cmd("M24");
  bool ret = console.run_queue();
  if (!ret)
    msg = wxString::FromUTF8(console.error_message().c_str());
  return ret;
}
References Slic3r::Utils::TCPConsole::enqueue_cmd(), Slic3r::Utils::TCPConsole::error_message(), m_console_port, m_host, and Slic3r::Utils::TCPConsole::run_queue().
Referenced by upload().
supports_multiple_printers()
virtual bool Slic3r::PrintHost::supports_multiple_printers () const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
test()
bool Slic3r::MKS::test (wxString & curl_msg) const override virtual
Implements Slic3r::PrintHost.
{
  Utils::TCPConsole console(m_host, m_console_port);
  console.enqueue_cmd("M105");
  bool ret = console.run_queue();
  if (!ret)
    msg = wxString::FromUTF8(console.error_message().c_str());
  return ret;
}
References Slic3r::Utils::TCPConsole::enqueue_cmd(), Slic3r::Utils::TCPConsole::error_message(), m_console_port, m_host, and Slic3r::Utils::TCPConsole::run_queue().
upload()
bool Slic3r::MKS::upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const override virtual
Implements Slic3r::PrintHost.
{
  bool res = true;
  auto upload_cmd = get_upload_url(upload_data.upload_path.string());
  BOOST_LOG_TRIVIAL(info) << boost::format("MKS: Uploading file %1%, filepath: %2%, print: %3%, command: %4%")
    % upload_data.source_path
    % upload_data.upload_path
    % (upload_data.post_action == PrintHostPostUploadAction::StartPrint)
    % upload_cmd;
  auto http = Http::post(std::move(upload_cmd));
  http.set_post_body(upload_data.source_path);
  http.on_complete([&](std::string body, unsigned status) {
    BOOST_LOG_TRIVIAL(debug) << boost::format("MKS: File uploaded: HTTP %1%: %2%") % status % body;
    int err_code = get_err_code_from_body(body);
    if (err_code != 0) {
      BOOST_LOG_TRIVIAL(error) << boost::format("MKS: Request completed but error code was received: %1%") % err_code;
      error_fn(format_error(body, L("Unknown error occured"), 0));
      res = false;
    }
    else if (upload_data.post_action == PrintHostPostUploadAction::StartPrint) {
      wxString errormsg;
      res = start_print(errormsg, upload_data.upload_path.string());
      if (!res) {
        error_fn(std::move(errormsg));
      }
    }
    })
    .on_error([&](std::string body, std::string error, unsigned status) {
      BOOST_LOG_TRIVIAL(error) << boost::format("MKS: Error uploading file: %1%, HTTP %2%, body: `%3%`") % error % status % body;
      error_fn(format_error(body, error, status));
      res = false;
    })
    .on_progress([&](Http::Progress progress, bool& cancel) {
      prorgess_fn(std::move(progress), cancel);
      if (cancel) {
        // Upload was canceled
        BOOST_LOG_TRIVIAL(info) << "MKS: Upload canceled";
        res = false;
      }
    }).perform_sync();
  return res;
}
References error, Slic3r::PrintHost::format_error(), get_err_code_from_body(), get_upload_url(), L, Slic3r::Http::post(), Slic3r::PrintHostUpload::post_action, Slic3r::PrintHostUpload::source_path, start_print(), Slic3r::StartPrint, and Slic3r::PrintHostUpload::upload_path.
Member Data Documentation
m_console_port
std::string Slic3r::MKS::m_console_port private
Referenced by start_print(), and test().
m_host
std::string Slic3r::MKS::m_host private
Referenced by get_host(), get_upload_url(), start_print(), and test().
The documentation for this class was generated from the following files:
src/slic3r/Utils/MKS.hpp
src/slic3r/Utils/MKS.cpp