Prusa Slicer: Slic3r::ConfigOptionString Class Reference
Slic3r::ConfigOptionString Class Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionString ()
ConfigOptionString (std::string value)
ConfigOptionType type () const override
ConfigOption * clone () const override
ConfigOptionString & operator= (const ConfigOption *opt)
bool operator== (const ConfigOptionString &rhs) const throw ()
bool operator< (const ConfigOptionString &rhs) const throw ()
bool empty () const
std::string serialize () const override
bool deserialize (const std::string &str, bool append=false) override
operator std::string () const
void set (const ConfigOption *rhs) override
bool operator== (const ConfigOption &rhs) const override
bool operator== (const std::string &rhs) const throw ()
bool operator!= (const std::string &rhs) const throw ()
bool operator!= (const ConfigOption &rhs) const
bool operator< (const std::string &rhs) const throw ()
size_t hash () const override throw ()
virtual int getInt () const
virtual double getFloat () const
virtual bool getBool () const
virtual void setInt (int)
bool is_scalar () const
bool is_vector () const
virtual bool nullable () const
virtual bool is_nil () const
virtual bool overriden_by (const ConfigOption *rhs) const
virtual bool apply_override (const ConfigOption *rhs)
Static Public Member Functions
static ConfigOptionType static_type ()
Public Attributes
std::string value
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
Constructor & Destructor Documentation
ConfigOptionString() [1/2]
Slic3r::ConfigOptionString::ConfigOptionString () inline
: ConfigOptionSingle<std::string>(std::string{}) {}
Referenced by clone().
ConfigOptionString() [2/2]
Slic3r::ConfigOptionString::ConfigOptionString (std::string value) inline explicit
: ConfigOptionSingle<std::string>(std::move(value)) {}
Member Function Documentation
apply_override()
virtual bool Slic3r::ConfigOption::apply_override (const ConfigOption * rhs) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      if (*this == *rhs)
        return false;
      *this = *rhs;
      return true;
    }
Referenced by Slic3r::print_config_diffs().
clone()
ConfigOption * Slic3r::ConfigOptionString::clone () const inline override virtual
Implements Slic3r::ConfigOption.
{ return new ConfigOptionString(*this); }
References ConfigOptionString().
deserialize()
bool Slic3r::ConfigOptionString::deserialize (const std::string & str, bool append = false) inline override virtual
Implements Slic3r::ConfigOption.
    {
        UNUSED(append);
        return unescape_string_cstyle(str, this->value);
    }
References Slic3r::append(), Slic3r::unescape_string_cstyle(), and UNUSED.
empty()
bool Slic3r::ConfigOptionString::empty () const inline
{ return this->value.empty(); }
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
virtual int Slic3r::ConfigOption::getInt () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::getInt on a non-int ConfigOption"); }
Referenced by Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
hash()
size_t Slic3r::ConfigOptionSingle< std::string >::hash () const throw () inline override virtual inherited
Implements Slic3r::ConfigOption.
{ return std::hash<T>{}(this->value); }
is_nil()
virtual bool Slic3r::ConfigOption::is_nil () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVectorBase, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::GCode::append_full_config(), Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_full_label(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::print_config_diffs(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::validate(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nullable()
virtual bool Slic3r::ConfigOption::nullable () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::ConfigBase::null_nullables(), Slic3r::ConfigOption::overriden_by(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::validate().
operator std::string()
Slic3r::ConfigOptionSingle< std::string >::operator std::string () const inline inherited
{ return this->value; }
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
bool Slic3r::ConfigOptionSingle< std::string >::operator!= (const std::string & rhs) const throw () inline inherited
{ return this->value != rhs; }
operator<() [1/2]
bool Slic3r::ConfigOptionString::operator< (const ConfigOptionString & rhs) const throw () inline
{ return this->value <  rhs.value; }
operator<() [2/2]
bool Slic3r::ConfigOptionSingle< std::string >::operator< (const std::string & rhs) const throw () inline inherited
{ return this->value < rhs; }
operator=()
ConfigOptionString & Slic3r::ConfigOptionString::operator= (const ConfigOption * opt) inline
{ this->set(opt); return *this; }
References Slic3r::ConfigOptionSingle< std::string >::set().
operator==() [1/3]
bool Slic3r::ConfigOptionSingle< std::string >::operator== (const ConfigOption & rhs) const inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionSingle: Comparing incompatible types");
        assert(dynamic_cast<const ConfigOptionSingle<T>*>(&rhs));
        return this->value == static_cast<const ConfigOptionSingle<T>*>(&rhs)->value;
    }
operator==() [2/3]
bool Slic3r::ConfigOptionString::operator== (const ConfigOptionString & rhs) const throw () inline
{ return this->value == rhs.value; }
operator==() [3/3]
bool Slic3r::ConfigOptionSingle< std::string >::operator== (const std::string & rhs) const throw () inline inherited
{ return this->value == rhs; }
overriden_by()
virtual bool Slic3r::ConfigOption::overriden_by (const ConfigOption * rhs) const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      assert(! this->nullable() && ! rhs->nullable());
      return *this != *rhs;
    }
References Slic3r::ConfigOption::nullable().
Referenced by Slic3r::print_config_diffs().
serialize() [1/2]
std::string Slic3r::ConfigOptionString::serialize () const inline override virtual
Implements Slic3r::ConfigOption.
    {
        return escape_string_cstyle(this->value);
    }
References Slic3r::escape_string_cstyle().
serialize() [2/2]
template<class Archive > void Slic3r::ConfigOptionString::serialize (Archive & ar) inline private
{ ar(cereal::base_class<ConfigOptionSingle<std::string>>(this)); }
set()
void Slic3r::ConfigOptionSingle< std::string >::set (const ConfigOption * rhs) inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionSingle: Assigning an incompatible type");
        assert(dynamic_cast<const ConfigOptionSingle<T>*>(rhs));
        this->value = static_cast<const ConfigOptionSingle<T>*>(rhs)->value;
    }
setInt()
virtual void Slic3r::ConfigOption::setInt (int) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::setInt on a non-int ConfigOption"); }
static_type()
static ConfigOptionType Slic3r::ConfigOptionString::static_type () inline static
{ return coString; }
References Slic3r::coString.
Referenced by type().
type()
ConfigOptionType Slic3r::ConfigOptionString::type () const inline override virtual
Implements Slic3r::ConfigOption.
{ return static_type(); }
References static_type().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
value
std::string Slic3r::ConfigOptionSingle< std::string >::value inherited
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp