Prusa Slicer: Slic3r::GUI::Downloader Class Reference
Slic3r::GUI::Downloader Class Reference
#include <src/slic3r/GUI/Downloader.hpp>
Public Member Functions
Downloader ()
bool get_initialized ()
void init (const boost::filesystem::path &dest_folder)
void start_download (const std::string &full_url)
bool user_action_callback (DownloaderUserAction action, int id)
Private Member Functions
size_t get_next_id ()
void on_progress (wxCommandEvent &event)
void on_error (wxCommandEvent &event)
void on_complete (wxCommandEvent &event)
void on_name_change (wxCommandEvent &event)
void on_paused (wxCommandEvent &event)
void on_canceled (wxCommandEvent &event)
void set_download_state (int id, DownloadState state)
Private Attributes
bool m_initialized { false }
std::vector< std::unique_ptr< Download > > m_downloads
boost::filesystem::path m_dest_folder
size_t m_next_id { 0 }
Detailed Description
Constructor & Destructor Documentation
Downloader()
Slic3r::GUI::Downloader::Downloader ()
  : wxEvtHandler()
{
  //Bind(EVT_DWNLDR_FILE_COMPLETE, [](const wxCommandEvent& evt) {});
  //Bind(EVT_DWNLDR_FILE_PROGRESS, [](const wxCommandEvent& evt) {});
  //Bind(EVT_DWNLDR_FILE_ERROR, [](const wxCommandEvent& evt) {});
  //Bind(EVT_DWNLDR_FILE_NAME_CHANGE, [](const wxCommandEvent& evt) {});
  Bind(EVT_DWNLDR_FILE_COMPLETE, &Downloader::on_complete, this);
  Bind(EVT_DWNLDR_FILE_PROGRESS, &Downloader::on_progress, this);
  Bind(EVT_DWNLDR_FILE_ERROR, &Downloader::on_error, this);
  Bind(EVT_DWNLDR_FILE_NAME_CHANGE, &Downloader::on_name_change, this);
  Bind(EVT_DWNLDR_FILE_PAUSED, &Downloader::on_paused, this);
  Bind(EVT_DWNLDR_FILE_CANCELED, &Downloader::on_canceled, this);
}
References on_canceled(), on_complete(), on_error(), on_name_change(), on_paused(), and on_progress().
Member Function Documentation
get_initialized()
bool Slic3r::GUI::Downloader::get_initialized () inline
{ return m_initialized; }
References m_initialized.
get_next_id()
size_t Slic3r::GUI::Downloader::get_next_id () inline private
{ return ++m_next_id; }
References m_next_id.
Referenced by start_download().
init()
void Slic3r::GUI::Downloader::init (const boost::filesystem::path & dest_folder) inline
    {
        m_dest_folder = dest_folder;
        m_initialized = true;
    }
References m_dest_folder, and m_initialized.
on_canceled()
void Slic3r::GUI::Downloader::on_canceled (wxCommandEvent & event) private
{
  size_t id = event.GetInt();
  NotificationManager* ntf_mngr = wxGetApp().notification_manager();
  ntf_mngr->set_download_URL_canceled(id);
}
References Slic3r::GUI::NotificationManager::set_download_URL_canceled().
Referenced by Downloader().
on_complete()
void Slic3r::GUI::Downloader::on_complete (wxCommandEvent & event) private
{
  // TODO: is this always true? :
  // here we open the file itself, notification should get 1.f progress from on progress.
    set_download_state(event.GetInt(), DownloadState::DownloadDone);
  wxArrayString paths;
  paths.Add(event.GetString());
  wxGetApp().plater()->load_files(paths);
}
References Slic3r::GUI::DownloadDone, and set_download_state().
Referenced by Downloader().
on_error()
void Slic3r::GUI::Downloader::on_error (wxCommandEvent & event) private
{
  size_t id = event.GetInt();
    set_download_state(event.GetInt(), DownloadState::DownloadError);
    BOOST_LOG_TRIVIAL(error) << "Download error: " << event.GetString();
  NotificationManager* ntf_mngr = wxGetApp().notification_manager();
  ntf_mngr->set_download_URL_error(id, boost::nowide::narrow(event.GetString()));
  show_error(nullptr, format_wxstr(L"%1%\n%2%", _L("The download has failed") + ":", event.GetString()));
}
References _L, Slic3r::GUI::DownloadError, error, Slic3r::GUI::format_wxstr(), L, boost::nowide::narrow(), set_download_state(), Slic3r::GUI::NotificationManager::set_download_URL_error(), and Slic3r::GUI::show_error().
Referenced by Downloader().
on_name_change()
void Slic3r::GUI::Downloader::on_name_change (wxCommandEvent & event) private
{
}
Referenced by Downloader().
on_paused()
void Slic3r::GUI::Downloader::on_paused (wxCommandEvent & event) private
{
  size_t id = event.GetInt();
  NotificationManager* ntf_mngr = wxGetApp().notification_manager();
  ntf_mngr->set_download_URL_paused(id);
}
References Slic3r::GUI::NotificationManager::set_download_URL_paused().
Referenced by Downloader().
on_progress()
void Slic3r::GUI::Downloader::on_progress (wxCommandEvent & event) private
{
  size_t id = event.GetInt();
  float percent = (float)std::stoi(boost::nowide::narrow(event.GetString())) / 100.f;
  //BOOST_LOG_TRIVIAL(error) << "progress " << id << ": " << percent;
  NotificationManager* ntf_mngr = wxGetApp().notification_manager();
  BOOST_LOG_TRIVIAL(trace) << "Download "<< id << ": " << percent;
  ntf_mngr->set_download_URL_progress(id, percent);
}
References boost::nowide::narrow(), and Slic3r::GUI::NotificationManager::set_download_URL_progress().
Referenced by Downloader().
set_download_state()
void Slic3r::GUI::Downloader::set_download_state (int id, DownloadState state) private
{
    for (size_t i = 0; i < m_downloads.size(); ++i) {
        if (m_downloads[i]->get_id() == id) {
            m_downloads[i]->set_state(state);
            return;
        }
    }
}
References m_downloads.
Referenced by on_complete(), and on_error().
start_download()
void Slic3r::GUI::Downloader::start_download (const std::string & full_url)
{
  assert(m_initialized);
  // TODO: There is a misterious slash appearing in recieved msg on windows
#ifdef _WIN32
  if (!boost::starts_with(full_url, "prusaslicer://open/?file=")) {
#else
    if (!boost::starts_with(full_url, "prusaslicer://open?file=")) {
#endif
    BOOST_LOG_TRIVIAL(error) << "Could not start download due to wrong URL: " << full_url;
    // TODO: show error?
    return;
  }
    size_t id = get_next_id();
    // TODO: still same mistery
#ifdef _WIN32
    std::string escaped_url = FileGet::escape_url(full_url.substr(25));
#else
    std::string escaped_url = FileGet::escape_url(full_url.substr(24));
#endif
  if (!boost::starts_with(escaped_url, "https://") || !FileGet::is_subdomain(escaped_url, "printables.com")) {
    std::string msg = format(_L("Download won't start. Download URL doesn't point to https://printables.com : %1%"), escaped_url);
    BOOST_LOG_TRIVIAL(error) << msg;
    NotificationManager* ntf_mngr = wxGetApp().notification_manager();
    ntf_mngr->push_notification(NotificationType::CustomNotification, NotificationManager::NotificationLevel::RegularNotificationLevel, msg);
    return;
  }
  std::string text(escaped_url);
    m_downloads.emplace_back(std::make_unique<Download>(id, std::move(escaped_url), this, m_dest_folder));
  NotificationManager* ntf_mngr = wxGetApp().notification_manager();
  ntf_mngr->push_download_URL_progress_notification(id, m_downloads.back()->get_filename(), std::bind(&Downloader::user_action_callback, this, std::placeholders::_1, std::placeholders::_2));
  m_downloads.back()->start();
  BOOST_LOG_TRIVIAL(debug) << "started download";
}
References _L, Slic3r::GUI::CustomNotification, error, Slic3r::GUI::FileGet::escape_url(), Slic3r::GUI::format(), get_next_id(), Slic3r::GUI::FileGet::is_subdomain(), m_dest_folder, m_downloads, m_initialized, Slic3r::GUI::NotificationManager::push_download_URL_progress_notification(), Slic3r::GUI::NotificationManager::push_notification(), Slic3r::GUI::NotificationManager::RegularNotificationLevel, and user_action_callback().
user_action_callback()
bool Slic3r::GUI::Downloader::user_action_callback (DownloaderUserAction action, int id)
{
  for (size_t i = 0; i < m_downloads.size(); ++i) {
    if (m_downloads[i]->get_id() == id) {
      switch (action) {
      case DownloadUserCanceled:
        m_downloads[i]->cancel();
        return true;
      case DownloadUserPaused:
        m_downloads[i]->pause();
        return true;
      case DownloadUserContinued:
        m_downloads[i]->resume();
        return true;
      case DownloadUserOpenedFolder:
        open_folder(m_downloads[i]->get_dest_folder());
        return true;
      default:
        return false;
      }
    }
  }
  return false;
}
References Slic3r::GUI::DownloadUserCanceled, Slic3r::GUI::DownloadUserContinued, Slic3r::GUI::DownloadUserOpenedFolder, Slic3r::GUI::DownloadUserPaused, and m_downloads.
Referenced by start_download().
Member Data Documentation
m_dest_folder
boost::filesystem::path Slic3r::GUI::Downloader::m_dest_folder private
Referenced by init(), and start_download().
m_downloads
std::vector<std::unique_ptr<Download> > Slic3r::GUI::Downloader::m_downloads private
Referenced by set_download_state(), start_download(), and user_action_callback().
m_initialized
bool Slic3r::GUI::Downloader::m_initialized { false } private
Referenced by get_initialized(), init(), and start_download().
m_next_id
size_t Slic3r::GUI::Downloader::m_next_id { 0 } private
Referenced by get_next_id().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Downloader.hpp
src/slic3r/GUI/Downloader.cpp