Prusa Slicer: Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode > Struct Template Reference
Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode > Struct Template Reference
#include <src/eigen/Eigen/src/Core/ProductEvaluators.h>
Public Types
typedef Product< Lhs, Rhs >::Scalar Scalar
Static Public Member Functions
template<typename Dst >
static EIGEN_STRONG_INLINE void evalTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_STRONG_INLINE void addTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_STRONG_INLINE void subTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
Detailed Description
template<typename Lhs, typename Rhs>
struct Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >
Member Typedef Documentation
Scalar
template<typename Lhs , typename Rhs > typedef Product<Lhs,Rhs>::Scalar Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::Scalar
Member Function Documentation
addTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::addTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
  {
    // dst.noalias() += lhs.lazyProduct(rhs);
    call_assignment_no_alias(dst, lhs.lazyProduct(rhs), internal::add_assign_op<typename Dst::Scalar,Scalar>());
  }
References Eigen::internal::call_assignment_no_alias().
evalTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::evalTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
  {
    // Same as: dst.noalias() = lhs.lazyProduct(rhs);
    // but easier on the compiler side
    call_assignment_no_alias(dst, lhs.lazyProduct(rhs), internal::assign_op<typename Dst::Scalar,Scalar>());
  }
References Eigen::internal::call_assignment_no_alias().
subTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::subTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
  {
    // dst.noalias() -= lhs.lazyProduct(rhs);
    call_assignment_no_alias(dst, lhs.lazyProduct(rhs), internal::sub_assign_op<typename Dst::Scalar,Scalar>());
  }
References Eigen::internal::call_assignment_no_alias().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/ProductEvaluators.h