Prusa Slicer: igl::opengl2::TranslateWidget Class Reference
igl::opengl2::TranslateWidget Class Reference
#include <src/libigl/igl/opengl2/TranslateWidget.h>
Public Types
enum DownType {
DOWN_TYPE_X = 0 , DOWN_TYPE_Y = 1 , DOWN_TYPE_Z = 2 , DOWN_TYPE_CENTER = 3 ,
DOWN_TYPE_NONE = 4 , NUM_DOWN_TYPES = 5
}
Public Member Functions
TranslateWidget (const Eigen::Vector3d &pos=Eigen::Vector3d(0, 0, 0))
bool down (const int x, const int y)
bool drag (const int x, const int y)
bool up (const int x, const int y)
bool is_down () const
void draw () const
Public Attributes
Eigen::Vector3d m_pos
Eigen::Vector3d m_trans
Eigen::Vector3d m_down_trans
Eigen::Vector2d m_down_xy
Eigen::Vector2d m_drag_xy
bool m_is_enabled
double m_len
enum igl::opengl2::TranslateWidget::DownType m_down_type
enum igl::opengl2::TranslateWidget::DownType m_selected_type
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Detailed Description
Member Enumeration Documentation
DownType
enum igl::opengl2::TranslateWidget::DownType
Enumerator
DOWN_TYPE_X
DOWN_TYPE_Y
DOWN_TYPE_Z
DOWN_TYPE_CENTER
DOWN_TYPE_NONE
NUM_DOWN_TYPES
      {
        DOWN_TYPE_X = 0,
        DOWN_TYPE_Y = 1,
        DOWN_TYPE_Z = 2,
        DOWN_TYPE_CENTER = 3,
        DOWN_TYPE_NONE = 4,
        NUM_DOWN_TYPES = 5
      } m_down_type, m_selected_type;
Constructor & Destructor Documentation
TranslateWidget()
igl::opengl2::TranslateWidget::TranslateWidget (const Eigen::Vector3d & pos = Eigen::Vector3d(0,0,0)) inline
                            :
  m_pos(pos),
  m_trans(0,0,0),
  m_down_xy(-1,-1),
  m_drag_xy(-1,-1),
  m_is_enabled(true),
  m_len(50),
  m_down_type(DOWN_TYPE_NONE),
  m_selected_type(DOWN_TYPE_NONE)
{
}
Member Function Documentation
down()
bool igl::opengl2::TranslateWidget::down (const int x, const int y) inline
{
  using namespace Eigen;
  using namespace std;
  if(!m_is_enabled)
  {
    return false;
  }
  m_down_trans = m_trans;
  m_down_xy = Vector2d(x,y);
  m_drag_xy = m_down_xy;
  m_down_type = DOWN_TYPE_NONE;
  m_selected_type = DOWN_TYPE_NONE;
  Vector3d ppos = project((m_pos+m_trans).eval());
  const double r = (ppos.head(2) - m_down_xy).norm();
  const double center_thresh = 10;
  if(r < center_thresh)
  {
    m_down_type = DOWN_TYPE_CENTER;
    m_selected_type = m_down_type;
    return true;
  }else if(r < m_len)
  {
    // Might be hit on lines
  }
  return false;
}
References igl::opengl2::project().
drag()
bool igl::opengl2::TranslateWidget::drag (const int x, const int y) inline
{
  using namespace std;
  using namespace Eigen;
  if(!m_is_enabled)
  {
    return false;
  }
  m_drag_xy = Vector2d(x,y);
  switch(m_down_type)
  {
    case DOWN_TYPE_NONE:
      return false;
    default:
    {
      Vector3d ppos = project((m_pos+m_trans).eval());
      Vector3d drag3(m_drag_xy(0),m_drag_xy(1),ppos(2));
      Vector3d down3(m_down_xy(0),m_down_xy(1),ppos(2));
      m_trans = m_down_trans + unproject(drag3)-unproject(down3);
      return true;
    }
  }
}
References igl::opengl2::project(), and igl::opengl2::unproject().
draw()
void igl::opengl2::TranslateWidget::draw () const inline
{
  using namespace Eigen;
  using namespace std;
  glPushAttrib(GL_ENABLE_BIT | GL_LIGHTING_BIT | GL_DEPTH_BUFFER_BIT | GL_LINE_BIT);
  glDisable(GL_LIGHTING);
  glDisable(GL_DEPTH_TEST);
  glLineWidth(2.0);
  auto draw_axes = [&]()
  {
    glBegin(GL_LINES);
    glColor3f(1,0,0);
    glVertex3f(0,0,0);
    glVertex3f(1,0,0);
    glColor3f(0,1,0);
    glVertex3f(0,0,0);
    glVertex3f(0,1,0);
    glColor3f(0,0,1);
    glVertex3f(0,0,0);
    glVertex3f(0,0,1);
    glEnd();
  };
  auto draw_cube = []
  {
    glBegin(GL_LINES);
    glVertex3f(-1.0f, 1.0f, 1.0f);
    glVertex3f(1.0f, 1.0f, 1.0f);
    glVertex3f(1.0f, 1.0f, 1.0f);
    glVertex3f(1.0f, -1.0f, 1.0f);
    glVertex3f(1.0f, -1.0f, 1.0f);
    glVertex3f(-1.0f, -1.0f, 1.0f);
    glVertex3f(-1.0f, -1.0f, 1.0f);
    glVertex3f(-1.0f, 1.0f, 1.0f);
    glVertex3f(1.0f, 1.0f, 1.0f);
    glVertex3f(1.0f, 1.0f, -1.0f);
    glVertex3f(1.0f, 1.0f, -1.0f);
    glVertex3f(1.0f, -1.0f, -1.0f);
    glVertex3f(1.0f, -1.0f, -1.0f);
    glVertex3f(1.0f, -1.0f, 1.0f);
    glVertex3f(1.0f, 1.0f, -1.0f);
    glVertex3f(-1.0f, 1.0f, -1.0f);
    glVertex3f(-1.0f, -1.0f, -1.0f);
    glVertex3f(1.0f, -1.0f, -1.0f);
    glVertex3f(-1.0f, -1.0f, -1.0f);
    glVertex3f(-1.0f, 1.0f, -1.0f);
    glVertex3f(-1.0f, 1.0f, -1.0f);
    glVertex3f(-1.0f, 1.0f, 1.0f);
    glVertex3f(-1.0f, -1.0f, 1.0f);
    glVertex3f(-1.0f, -1.0f, -1.0f);
    glEnd();
  };
  glPushMatrix();
  glTranslated( m_pos(0)+m_trans(0), m_pos(1)+m_trans(1), m_pos(2)+m_trans(2));
  {
    Vector3d off,ppos,ppos_off,pos_off;
    project((m_pos+m_trans).eval(),ppos);
    ppos_off = ppos;
    ppos_off(0) += m_len;
    unproject(ppos_off,pos_off);
    const double r = (m_pos+m_trans-pos_off).norm();
    glScaled(r,r,r);
  }
  draw_axes();
  glScaled(0.05,0.05,0.05);
  if(m_selected_type == DOWN_TYPE_CENTER)
  {
    glColor3fv(MAYA_YELLOW.data());
  }else
  {
    glColor3fv(MAYA_GREY.data());
  }
  draw_cube();
  glPopMatrix();
  glPopAttrib();
}
References igl::MAYA_GREY(), igl::MAYA_YELLOW(), igl::opengl2::project(), and igl::opengl2::unproject().
is_down()
bool igl::opengl2::TranslateWidget::is_down () const inline
{
  return m_down_type != DOWN_TYPE_NONE;
}
Referenced by igl::opengl2::MouseController::is_trans_widget_down().
up()
bool igl::opengl2::TranslateWidget::up (const int x, const int y) inline
{
  // even if disabled process up
  m_down_type = DOWN_TYPE_NONE;
  return false;
}
Member Data Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
igl::opengl2::TranslateWidget::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
m_down_trans
Eigen::Vector3d igl::opengl2::TranslateWidget::m_down_trans
m_down_type
enum igl::opengl2::TranslateWidget::DownType igl::opengl2::TranslateWidget::m_down_type
m_down_xy
Eigen::Vector2d igl::opengl2::TranslateWidget::m_down_xy
m_drag_xy
Eigen::Vector2d igl::opengl2::TranslateWidget::m_drag_xy
m_is_enabled
bool igl::opengl2::TranslateWidget::m_is_enabled
m_len
double igl::opengl2::TranslateWidget::m_len
m_pos
Eigen::Vector3d igl::opengl2::TranslateWidget::m_pos
m_selected_type
enum igl::opengl2::TranslateWidget::DownType igl::opengl2::TranslateWidget::m_selected_type
m_trans
Eigen::Vector3d igl::opengl2::TranslateWidget::m_trans
The documentation for this class was generated from the following file:
src/libigl/igl/opengl2/TranslateWidget.h