Prusa Slicer: Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode > Struct Template Reference
Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode > Struct Template Reference
#include <src/eigen/Eigen/src/Core/ProductEvaluators.h>
Static Public Member Functions
static EIGEN_STRONG_INLINE void run (Index row, Index col, const Lhs &lhs, const Rhs &rhs, Index innerDim, Packet &res)
Detailed Description
template<int UnrollingIndex, typename Lhs, typename Rhs, typename Packet, int LoadMode>
struct Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >
Member Function Documentation
run()
template<int UnrollingIndex, typename Lhs , typename Rhs , typename Packet , int LoadMode> static EIGEN_STRONG_INLINE void Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run (Index row, Index col, const Lhs & lhs, const Rhs & rhs, Index innerDim, Packet & res) inline static
  {
    etor_product_packet_impl<ColMajor, UnrollingIndex-1, Lhs, Rhs, Packet, LoadMode>::run(row, col, lhs, rhs, innerDim, res);
    res =  pmadd(lhs.template packet<LoadMode,Packet>(row, Index(UnrollingIndex-1)), pset1<Packet>(rhs.coeff(Index(UnrollingIndex-1), col)), res);
  }
References col(), Eigen::internal::pmadd(), and row().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/ProductEvaluators.h