Prusa Slicer: src/avrdude/ser_posix.c File Reference
ser_posix.c File Reference
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <fcntl.h>
#include <termios.h>
#include <unistd.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "ac_cfg.h"
Classes
struct baud_mapping
Macros
#define MAX_ZERO_READS 512
Functions
static speed_t serial_baud_lookup (long baud)
static int ser_setspeed (union filedescriptor *fd, long baud)
ssize_t read_timeout (int fd, void *buf, size_t count, long timeout)
ssize_t write_timeout (int fd, const void *buf, size_t count, long timeout)
static int net_open (const char *port, union filedescriptor *fdp)
static int ser_set_dtr_rts (union filedescriptor *fdp, int is_on)
static int ser_open (char *port, union pinfo pinfo, union filedescriptor *fdp)
static void ser_close (union filedescriptor *fd)
static int ser_send (union filedescriptor *fd, const unsigned char *buf, size_t buflen)
static int ser_recv (union filedescriptor *fd, unsigned char *buf, size_t buflen)
static int ser_drain (union filedescriptor *fd, int display)
Variables
long serial_recv_timeout = 4000
static struct baud_mapping baud_lookup_table []
static struct termios original_termios
static int saved_original_termios
struct serial_device serial_serdev
struct serial_device * serdev = &serial_serdev
Class Documentation
baud_mapping
struct baud_mapping
Class Members
long baud
speed_t speed
Macro Definition Documentation
MAX_ZERO_READS
#define MAX_ZERO_READS 512
Function Documentation
net_open()
static int net_open (const char * port, union filedescriptor * fdp) static
{
#ifdef HAVE_GETADDRINFO
  char *hp, *hstr, *pstr;
  int s, fd, ret = -1;
  struct addrinfo hints;
  struct addrinfo *result, *rp;
  if ((hstr = hp = strdup(port)) == NULL) {
    avrdude_message(MSG_INFO, "%s: net_open(): Out of memory!\n",
      progname);
    return -1;
  }
  /*
   * As numeric IPv6 addresses use colons as separators, we need to
   * look for the last colon here, which separates the port number or
   * service name from the host or IP address.
   */
  if (((pstr = strrchr(hstr, ':')) == NULL) || (pstr == hstr)) {
    avrdude_message(MSG_INFO, "%s: net_open(): Mangled host:port string \"%s\"\n",
      progname, hstr);
    goto error;
  }
  /*
   * Remove brackets from the host part, if present.
   */
  if (*hstr == '[' && *(pstr-1) == ']') {
    hstr++;
    *(pstr-1) = '\0';
  }
  /*
   * Terminate the host section of the description.
   */
  *pstr++ = '\0';
  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_UNSPEC;
  hints.ai_socktype = SOCK_STREAM;
  s = getaddrinfo(hstr, pstr, &hints, &result);
  if (s != 0) {
    avrdude_message(MSG_INFO,
      "%s: net_open(): Cannot resolve "
      "host=\"%s\", port=\"%s\": %s\n",
      progname, hstr, pstr, gai_strerror(s));
    goto error;
  }
  for (rp = result; rp != NULL; rp = rp->ai_next) {
    fd = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
    if (fd == -1) {
      /* This one failed, loop over */
      continue;
    }
    if (connect(fd, rp->ai_addr, rp->ai_addrlen) != -1) {
      /* Success, we are connected */
      break;
    }
    close(fd);
  }
  if (rp == NULL) {
    avrdude_message(MSG_INFO, "%s: net_open(): Cannot connect: %s\n",
      progname, strerror(errno));
  }
  else {
    fdp->ifd = fd;
    ret = 0;
  }
  freeaddrinfo(result);
error:
  free(hp);
  return ret;
#else
  avrdude_message(MSG_INFO,
    "%s: Networking is not supported on your platform.\n"
    "If you need it, please open a bug report.\n", progname);
  return -1;
#endif /* HAVE_GETADDRINFO */
}
References avrdude_message(), error, free(), filedescriptor::ifd, MSG_INFO, and progname.
Referenced by ser_open().
read_timeout()
ssize_t read_timeout (int fd, void * buf, size_t count, long timeout)
{
  struct timeval tm, tm2;
  fd_set rfds;
  int nfds;
  tm.tv_sec  = timeout / 1000L;
  tm.tv_usec = (timeout % 1000L) * 1000;
  while (1) {
    FD_ZERO(&rfds);
    FD_SET(fd, &rfds);
    tm2 = tm;
    nfds = select(fd + 1, &rfds, NULL, NULL, &tm2);
    if (nfds == 0) {
      return -2;
    } else if (nfds == -1) {
      if (errno == EINTR || errno == EAGAIN) {
        continue;
      } else {
        return -1;
      }
    } else {
      return read(fd, buf, count);
    }
  }
}
Referenced by ser_drain(), and ser_recv().
ser_close()
static void ser_close (union filedescriptor * fd) static
{
  /*
   * restore original termios settings from ser_open
   */
  if (saved_original_termios) {
    int rc = tcsetattr(fd->ifd, TCSANOW | TCSADRAIN, &original_termios);
    if (rc) {
      avrdude_message(MSG_INFO, "%s: ser_close(): can't reset attributes for device: %s\n",
                      progname, strerror(errno));
    }
    saved_original_termios = 0;
  }
  close(fd->ifd);
}
References avrdude_message(), filedescriptor::ifd, MSG_INFO, original_termios, progname, and saved_original_termios.
ser_drain()
static int ser_drain (union filedescriptor * fd, int display) static
{
  int rc;
  unsigned char buf;
  unsigned zero_reads = 0;
  if (display) {
    avrdude_message(MSG_INFO, "drain>");
  }
  while (1) {
    RETURN_IF_CANCEL();
    rc = read_timeout(fd->ifd, &buf, 1, 250);   // Note: timeout needs to be kept low to not timeout in programmers
    if (rc == -2) {
      if (display) {
        avrdude_message(MSG_INFO, "<drain\n");
      }
      break;
    } else if (rc == -1) {
      avrdude_message(MSG_INFO, "%s: ser_drain(): read error: %s\n", progname, strerror(errno));
      return -1;
    } else if (rc == 0) {
      zero_reads++;
      if (zero_reads > MAX_ZERO_READS) {
        avrdude_message(MSG_NOTICE2, "%s: ser_drain(): programmer is not responding (too many zero reads)\n",
                progname);
        return -1;
      }
    } else {
      zero_reads = 0;
    }
    if (display) {
      avrdude_message(MSG_INFO, "%02x ", buf);
    }
  }
  return 0;
}
References avrdude_message(), filedescriptor::ifd, MAX_ZERO_READS, MSG_INFO, MSG_NOTICE2, progname, read_timeout(), and RETURN_IF_CANCEL.
ser_open()
static int ser_open (char * port, union pinfo pinfo, union filedescriptor * fdp) static
{
  int rc;
  int fd;
  /*
   * If the port is of the form "net:<host>:<port>", then
   * handle it as a TCP connection to a terminal server.
   */
  if (strncmp(port, "net:", strlen("net:")) == 0) {
    return net_open(port + strlen("net:"), fdp);
  }
  /*
   * open the serial port
   */
  fd = open(port, O_RDWR | O_NOCTTY | O_NONBLOCK);
  if (fd < 0) {
    avrdude_message(MSG_INFO, "%s: ser_open(): can't open device \"%s\": %s\n",
            progname, port, strerror(errno));
    return -1;
  }
  fdp->ifd = fd;
  /*
   * set serial line attributes
   */
  rc = ser_setspeed(fdp, pinfo.baud);
  if (rc) {
    avrdude_message(MSG_INFO, "%s: ser_open(): can't set attributes for device \"%s\": %s\n",
                    progname, port, strerror(-rc));
    close(fd);
    return -1;
  }
  return 0;
}
References avrdude_message(), pinfo::baud, filedescriptor::ifd, MSG_INFO, net_open(), progname, and ser_setspeed().
ser_recv()
static int ser_recv (union filedescriptor * fd, unsigned char * buf, size_t buflen) static
{
  int rc;
  unsigned char * p = buf;
  size_t len = 0;
  unsigned zero_reads = 0;
  while (len < buflen) {
    RETURN_IF_CANCEL();
    rc = read_timeout(fd->ifd, p, (buflen - len > 1024) ? 1024 : buflen - len, serial_recv_timeout);
    if (rc == -2) {
      avrdude_message(MSG_NOTICE2, "%s: ser_recv(): programmer is not responding\n", progname);
      return -1;
    } else if (rc == -1) {
      avrdude_message(MSG_INFO, "%s: ser_recv(): read error: %s\n", progname, strerror(errno));
      return -1;
    } else if (rc == 0) {
      zero_reads++;
      if (zero_reads > MAX_ZERO_READS) {
        avrdude_message(MSG_NOTICE2, "%s: ser_recv(): programmer is not responding (too many zero reads)\n",
                progname);
        return -1;
      }
    } else {
      zero_reads = 0;
      p += rc;
      len += rc;
    }
  }
  p = buf;
  if (verbose > 3)
  {
      avrdude_message(MSG_TRACE, "%s: Recv: ", progname);
      while (len) {
        unsigned char c = *p;
        if (isprint(c)) {
          avrdude_message(MSG_TRACE, "%c ", c);
        }
        else {
          avrdude_message(MSG_TRACE, ". ");
        }
        avrdude_message(MSG_TRACE, "[%02x] ", c);
        p++;
        len--;
      }
      avrdude_message(MSG_TRACE, "\n");
  }
  return 0;
}
References avrdude_message(), filedescriptor::ifd, MAX_ZERO_READS, MSG_INFO, MSG_NOTICE2, MSG_TRACE, progname, read_timeout(), RETURN_IF_CANCEL, serial_recv_timeout, and verbose.
ser_send()
static int ser_send (union filedescriptor * fd, const unsigned char * buf, size_t buflen) static
{
  int rc;
  const unsigned char * p = buf;
  size_t len = buflen;
  unsigned zero_writes = 0;
  if (!len)
    return 0;
  if (verbose > 3)
  {
      avrdude_message(MSG_TRACE, "%s: Send: ", progname);
      while (buflen) {
        unsigned char c = *buf;
        if (isprint(c)) {
          avrdude_message(MSG_TRACE, "%c ", c);
        }
        else {
          avrdude_message(MSG_TRACE, ". ");
        }
        avrdude_message(MSG_TRACE, "[%02x] ", c);
        buf++;
        buflen--;
      }
      avrdude_message(MSG_TRACE, "\n");
  }
  while (len) {
    RETURN_IF_CANCEL();
    rc = write_timeout(fd->ifd, p, (len > 1024) ? 1024 : len, serial_recv_timeout);
    if (rc == -2) {
      avrdude_message(MSG_NOTICE2, "%s: ser_send(): programmer is not responding\n", progname);
      return -1;
    } else if (rc == -1) {
      avrdude_message(MSG_INFO, "%s: ser_send(): write error: %s\n", progname, strerror(errno));
      return -1;
    } else if (rc == 0) {
      zero_writes++;
      if (zero_writes > MAX_ZERO_READS) {
        avrdude_message(MSG_NOTICE2, "%s: ser_send(): programmer is not responding (too many zero writes)\n",
                progname);
        return -1;
      }
    } else {
      zero_writes = 0;
      p += rc;
      len -= rc;
    }
  }
  return 0;
}
References avrdude_message(), filedescriptor::ifd, MAX_ZERO_READS, MSG_INFO, MSG_NOTICE2, MSG_TRACE, progname, RETURN_IF_CANCEL, serial_recv_timeout, verbose, and write_timeout().
ser_set_dtr_rts()
static int ser_set_dtr_rts (union filedescriptor * fdp, int is_on) static
{
  unsigned int  ctl;
  int           r;
  r = ioctl(fdp->ifd, TIOCMGET, &ctl);
  if (r < 0) {
    perror("ioctl(\"TIOCMGET\")");
    return -1;
  }
  if (is_on) {
    /* Set DTR and RTS */
    ctl |= (TIOCM_DTR | TIOCM_RTS);
  }
  else {
    /* Clear DTR and RTS */
    ctl &= ~(TIOCM_DTR | TIOCM_RTS);
  }
  r = ioctl(fdp->ifd, TIOCMSET, &ctl);
  if (r < 0) {
    perror("ioctl(\"TIOCMSET\")");
    return -1;
  }
  return 0;
}
References filedescriptor::ifd.
ser_setspeed()
static int ser_setspeed (union filedescriptor * fd, long baud) static
{
  int rc;
  struct termios termios;
  speed_t speed = serial_baud_lookup (baud);
  if (!isatty(fd->ifd))
    return -ENOTTY;
  /*
   * initialize terminal modes
   */
  rc = tcgetattr(fd->ifd, &termios);
  if (rc < 0) {
    avrdude_message(MSG_INFO, "%s: ser_setspeed(): tcgetattr() failed\n",
            progname);
    return -errno;
  }
  /*
   * copy termios for ser_close if we haven't already
   */
  if (! saved_original_termios++) {
    original_termios = termios;
  }
  termios.c_iflag = IGNBRK;
  termios.c_oflag = 0;
  termios.c_lflag = 0;
  termios.c_cflag = (CS8 | CREAD | CLOCAL);
  termios.c_cc[VMIN]  = 1;
  termios.c_cc[VTIME] = 0;
  cfsetospeed(&termios, speed);
  cfsetispeed(&termios, speed);
  rc = tcsetattr(fd->ifd, TCSANOW, &termios);
  if (rc < 0) {
    avrdude_message(MSG_INFO, "%s: ser_setspeed(): tcsetattr() failed\n",
            progname);
    return -errno;
  }
  /*
   * Everything is now set up for a local line without modem control
   * or flow control, so clear O_NONBLOCK again.
   */
  rc = fcntl(fd->ifd, F_GETFL, 0);
  if (rc != -1)
    fcntl(fd->ifd, F_SETFL, rc & ~O_NONBLOCK);
  return 0;
}
References avrdude_message(), filedescriptor::ifd, isatty, MSG_INFO, original_termios, progname, saved_original_termios, and serial_baud_lookup().
Referenced by ser_open().
serial_baud_lookup()
static speed_t serial_baud_lookup (long baud) static
{
  struct baud_mapping *map = baud_lookup_table;
  while (map->baud) {
    if (map->baud == baud)
      return map->speed;
    map++;
  }
  /*
   * If a non-standard BAUD rate is used, issue
   * a warning (if we are verbose) and return the raw rate
   */
  avrdude_message(MSG_NOTICE, "%s: serial_baud_lookup(): Using non-standard baud rate: %ld\n",
              progname, baud);
  return baud;
}
References avrdude_message(), baud_mapping::baud, baud_lookup_table, MSG_NOTICE, progname, and baud_mapping::speed.
Referenced by ser_setspeed().
write_timeout()
ssize_t write_timeout (int fd, const void * buf, size_t count, long timeout)
{
  struct timeval tm, tm2;
  fd_set wfds;
  int nfds;
  tm.tv_sec  = timeout / 1000L;
  tm.tv_usec = (timeout % 1000L) * 1000;
  while (1) {
    FD_ZERO(&wfds);
    FD_SET(fd, &wfds);
    tm2 = tm;
    nfds = select(fd + 1, NULL, &wfds, NULL, &tm2);
    if (nfds == 0) {
      return -2;
    } else if (nfds == -1) {
      if (errno == EINTR || errno == EAGAIN) {
        continue;
      } else {
        return -1;
      }
    } else {
      return write(fd, buf, count);
    }
  }
}
Referenced by ser_send().
Variable Documentation
baud_lookup_table
struct baud_mapping baud_lookup_table[] static
Initial value:
= {
  { 1200,   B1200 },
  { 2400,   B2400 },
  { 4800,   B4800 },
  { 9600,   B9600 },
  { 19200,  B19200 },
  { 38400,  B38400 },
  { 0,      0 }
}
Referenced by serial_baud_lookup().
original_termios
struct termios original_termios static
Referenced by ser_close(), and ser_setspeed().
saved_original_termios
int saved_original_termios static
Referenced by ser_close(), and ser_setspeed().
serdev
struct serial_device* serdev = &serial_serdev
Referenced by jtag3_open_common(), jtagmkI_close(), jtagmkI_initialize(), jtagmkII_dragon_open(), jtagmkII_dragon_open_dw(), jtagmkII_dragon_open_pdi(), jtagmkII_initialize(), jtagmkII_open(), jtagmkII_open32(), jtagmkII_open_dw(), jtagmkII_open_pdi(), stk500v2_open(), and stk600_open().
serial_recv_timeout
long serial_recv_timeout = 4000
Referenced by buspirate_disable(), buspirate_parseextparms(), buspirate_readline_noexit(), jtag3_paged_load(), jtag3_paged_write(), jtagmkI_paged_load(), jtagmkI_paged_write(), jtagmkI_resync(), jtagmkII_page_erase(), jtagmkII_paged_load(), jtagmkII_paged_load32(), jtagmkII_paged_write(), jtagmkII_paged_write32(), jtagmkII_read_SABaddr(), ser_recv(), and ser_send().
serial_serdev
struct serial_device serial_serdev
Initial value:
=
{
  .open = ser_open,
  .setspeed = ser_setspeed,
  .close = ser_close,
  .send = ser_send,
  .recv = ser_recv,
  .drain = ser_drain,
  .set_dtr_rts = ser_set_dtr_rts,
  .flags = SERDEV_FL_CANSETSPEED,
}