Prusa Slicer: Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > Class Template Reference
Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > Class Template Reference
A sparse matrix class designed for matrix assembly purpose.
#include <src/eigen/unsupported/Eigen/src/SparseExtra/DynamicSparseMatrix.h>
Classes
class InnerIterator
class ReverseInnerIterator
Public Types
enum { Options = _Options }
typedef MappedSparseMatrix< Scalar, Flags > Map
enum
typedef internal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageKind StorageKind
typedef internal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typenameinternal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< constDerived > >, Transpose< constDerived > >::type AdjointReturnType
typedef Transpose< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > > TransposeReturnType
typedef internal::add_const< Transpose< constDerived > >::type ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional< _HasDirectAccess, constScalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef Block< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > InnerVectorReturnType
typedef Block< const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > ConstInnerVectorReturnType
typedef Block< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >, Dynamic, Dynamic, true > InnerVectorsReturnType
typedef Block< const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >, Dynamic, Dynamic, true > ConstInnerVectorsReturnType
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
Index rows () const
Index cols () const
Index innerSize () const
Index outerSize () const
Index innerNonZeros (Index j) const
std::vector< internal::CompressedStorage< Scalar, StorageIndex > > & _data ()
const std::vector< internal::CompressedStorage< Scalar, StorageIndex > > & _data () const
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
void setZero ()
Index nonZeros () const
void reserve (Index reserveSize=1000)
void startVec (Index)
Scalar & insertBack (Index row, Index col)
Scalar & insertBackByOuterInner (Index outer, Index inner)
Scalar & insert (Index row, Index col)
void finalize ()
void prune (Scalar reference, RealScalar epsilon=NumTraits< RealScalar >::dummy_precision())
void resize (Index rows, Index cols)
void resizeAndKeepData (Index rows, Index cols)
EIGEN_DEPRECATED DynamicSparseMatrix ()
EIGEN_DEPRECATED DynamicSparseMatrix (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEPRECATED DynamicSparseMatrix (const SparseMatrixBase< OtherDerived > &other)
DynamicSparseMatrix (const DynamicSparseMatrix &other)
void swap (DynamicSparseMatrix &other)
DynamicSparseMatrix & operator= (const DynamicSparseMatrix &other)
~DynamicSparseMatrix ()
EIGEN_DEPRECATED void startFill (Index reserveSize=1000)
EIGEN_DEPRECATED Scalar & fill (Index row, Index col)
EIGEN_DEPRECATED Scalar & fillrand (Index row, Index col)
EIGEN_DEPRECATED void endFill ()
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator= (const Derived &other)
const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & derived () const
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & derived ()
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & const_cast_derived () const
Index size () const
bool isVector () const
bool isRValue () const
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & markAsRValue ()
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator+= (const SparseMatrixBase< OtherDerived > &other)
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator+= (const DiagonalBase< OtherDerived > &other)
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator+= (const SparseMatrixBase< OtherDerived > &other)
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator-= (const SparseMatrixBase< OtherDerived > &other)
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator-= (const DiagonalBase< OtherDerived > &other)
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator-= (const SparseMatrixBase< OtherDerived > &other)
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator*= (const Scalar &other)
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator*= (const SparseMatrixBase< OtherDerived > &other)
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
internal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar dot (const MatrixBase< OtherDerived > &other) const
internal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
InnerVectorReturnType innerVector (Index outer)
const ConstInnerVectorReturnType innerVector (Index outer) const
InnerVectorsReturnType innerVectors (Index outerStart, Index outerSize)
const ConstInnerVectorsReturnType innerVectors (Index outerStart, Index outerSize) const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::type eval () const
Scalar sum () const
const SparseView< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Types
typedef DynamicSparseMatrix< Scalar,(Flags &~RowMajorBit)|(IsRowMajor?RowMajorBit:0), StorageIndex > TransposedSparseMatrix
Protected Member Functions
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Protected Attributes
Index m_innerSize
std::vector< internal::CompressedStorage< Scalar, StorageIndex > > m_data
bool m_isRValue
Private Types
typedef SparseMatrixBase< DynamicSparseMatrix > Base
Private Member Functions
void evalTo (Dest &) const
Static Private Member Functions
static StorageIndex convert_index (const Index idx)
Detailed Description
template<typename _Scalar, int _Options, typename _StorageIndex>
class Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >
A sparse matrix class designed for matrix assembly purpose.
Parameters
_Scalar the scalar type, i.e. the type of the coefficients
Unlike SparseMatrix, this class provides a much higher degree of flexibility. In particular, it allows random read/write accesses in log(rho*outer_size) where rho is the probability that a coefficient is nonzero and outer_size is the number of columns if the matrix is column-major and the number of rows otherwise.
Internally, the data are stored as a std::vector of compressed vector. The performances of random writes might decrease as the number of nonzeros per inner-vector increase. In practice, we observed very good performance till about 100 nonzeros/vector, and the performance remains relatively good till 500 nonzeros/vectors.
See also
SparseMatrix
Member Typedef Documentation
AdjointReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,Eigen::Transpose<constDerived>>,Transpose<constDerived>>::type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::AdjointReturnType inherited
Base
template<typename _Scalar , int _Options, typename _StorageIndex > typedef SparseMatrixBase<DynamicSparseMatrix> Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::Base private
CoeffReturnType
typedef internal::conditional<_HasDirectAccess,constScalar&,Scalar>::type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::CoeffReturnType inherited
ConstantReturnType
typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,Matrix<Scalar,Dynamic,Dynamic> > Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::ConstantReturnType inherited
ConstInnerVectorReturnType
typedef Block<const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > ,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::ConstInnerVectorReturnType inherited
ConstInnerVectorsReturnType
typedef Block<const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > ,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::ConstInnerVectorsReturnType inherited
ConstTransposeReturnType
typedef internal::add_const<Transpose<constDerived>>::type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::ConstTransposeReturnType inherited
DenseMatrixType
typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime> Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::DenseMatrixType inherited
type of the equivalent dense matrix
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
IndexVector
typedef Matrix<StorageIndex,Dynamic,1> Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::IndexVector inherited
InnerVectorReturnType
typedef Block<DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > ,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::InnerVectorReturnType inherited
InnerVectorsReturnType
typedef Block<DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > ,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::InnerVectorsReturnType inherited
Map
template<typename _Scalar , int _Options, typename _StorageIndex > typedef MappedSparseMatrix<Scalar,Flags> Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::Map
PacketReturnType
typedef internal::add_const_on_value_type_if_arithmetic<typenameinternal::packet_traits<Scalar>::type>::type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::PacketReturnType inherited
PacketScalar
typedef internal::packet_traits<Scalar>::type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::PacketScalar inherited
PlainObject
typedef SparseMatrix<Scalar, Flags&RowMajorBit ? RowMajor : ColMajor, StorageIndex> Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::PlainObject inherited
RealScalar
typedef NumTraits<Scalar>::Real Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::RealScalar inherited
This is the "real scalar" type; if the Scalar type is already real numbers (e.g. int, float or double) then RealScalar is just the same as Scalar. If Scalar is std::complex<T> then RealScalar is T.
See also
class NumTraits
Scalar
typedef internal::traits<DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar inherited
ScalarVector
typedef Matrix<Scalar,Dynamic,1> Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::ScalarVector inherited
SquareMatrixType
typedef Matrix<Scalar,EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime)> Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::SquareMatrixType inherited
type of the equivalent square matrix
StorageBaseType
typedef SparseMatrixBase Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageBaseType inherited
StorageIndex
typedef internal::traits<DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageIndex Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageIndex inherited
The integer type used to store indices within a SparseMatrix. For a SparseMatrix<Scalar,Options,IndexType> it an alias of the third template parameter IndexType.
StorageKind
typedef internal::traits<DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageKind Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::StorageKind inherited
TransposedSparseMatrix
template<typename _Scalar , int _Options, typename _StorageIndex > typedef DynamicSparseMatrix<Scalar,(Flags&~RowMajorBit)|(IsRowMajor?RowMajorBit:0), StorageIndex> Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::TransposedSparseMatrix protected
TransposeReturnType
typedef Transpose<DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > > Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::TransposeReturnType inherited
value_type
typedef Scalar Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::value_type inherited
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = RowsAtCompileTime,
      MaxColsAtCompileTime = ColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<MaxRowsAtCompileTime,
                                                      MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1,
      Flags = internal::traits<Derived>::Flags,
      IsRowMajor = Flags&RowMajorBit ? 1 : 0,
      InnerSizeAtCompileTime = int(IsVectorAtCompileTime) ? int(SizeAtCompileTime)
                             : int(IsRowMajor) ? int(ColsAtCompileTime) : int(RowsAtCompileTime),
      #ifndef EIGEN_PARSED_BY_DOXYGEN
      _HasDirectAccess = (int(Flags)&DirectAccessBit) ? 1 : 0 // workaround sunCC
      #endif
    };
anonymous enum
template<typename _Scalar , int _Options, typename _StorageIndex > anonymous enum
Enumerator
Options
         {
      Options = _Options
    };
Constructor & Destructor Documentation
DynamicSparseMatrix() [1/4]
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DEPRECATED Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix () inline
The class DynamicSparseMatrix is deprectaed
      : m_innerSize(0), m_data(0)
    {
      #ifdef EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
        EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
      #endif
      eigen_assert(innerSize()==0 && outerSize()==0);
    }
References eigen_assert, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::innerSize(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize().
DynamicSparseMatrix() [2/4]
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DEPRECATED Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix (Index rows, Index cols) inline
The class DynamicSparseMatrix is deprectaed
      : m_innerSize(0)
    {
      #ifdef EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
        EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
      #endif
      resize(rows, cols);
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
DynamicSparseMatrix() [3/4]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > EIGEN_DEPRECATED Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix (const SparseMatrixBase< OtherDerived > & other) inline explicit
The class DynamicSparseMatrix is deprectaed
      : m_innerSize(0)
    {
      #ifdef EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
        EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
      #endif
      Base::operator=(other.derived());
    }
References Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::operator=().
DynamicSparseMatrix() [4/4]
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix (const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & other) inline
      : Base(), m_innerSize(0)
    {
      #ifdef EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
        EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
      #endif
      *this = other.derived();
    }
References Eigen::SparseMatrixBase< Derived >::derived().
~DynamicSparseMatrix()
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::~DynamicSparseMatrix () inline
Destructor
{}
Member Function Documentation
_data() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > std::vector< internal::CompressedStorage< Scalar, StorageIndex > > & Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::_data () inline
{ return m_data; }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data.
_data() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > const std::vector< internal::CompressedStorage< Scalar, StorageIndex > > & Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::_data () const inline
{ return m_data; }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data.
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
const AdjointReturnType Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::adjoint () const inline inherited
{ return AdjointReturnType(transpose()); }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
assign()
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::assign (const OtherDerived & other) inline protected inherited
assignGeneric()
void Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::assignGeneric (const OtherDerived & other) inline protected inherited
blueNorm()
NumTraits< typenameinternal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar >::Real Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::blueNorm inline inherited
{
  return internal::blueNorm_impl(*this);
}
coeff()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeff (Index row, Index col) const inline
Returns
the coefficient value at given position row, col This operation involes a log(rho*outer_size) binary search.
    {
      const Index outer = IsRowMajor ? row : col;
      const Index inner = IsRowMajor ? col : row;
      return m_data[outer].at(inner);
    }
References col(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, and row().
coeffRef()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar & Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef (Index row, Index col) inline
Returns
a reference to the coefficient value at given position row, col This operation involes a log(rho*outer_size) binary search. If the coefficient does not exist yet, then a sorted insertion into a sequential buffer is performed.
    {
      const Index outer = IsRowMajor ? row : col;
      const Index inner = IsRowMajor ? col : row;
      return m_data[outer].atWithInsertion(inner);
    }
References col(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, and row().
Referenced by igl::cat(), igl::diag(), igl::diag(), igl::slice(), and igl::slice_into().
cols()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::cols () const inline
{ return IsRowMajor ? m_innerSize : outerSize(); }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize().
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resizeAndKeepData(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run().
const_cast_derived()
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::const_cast_derived () const inline inherited
    { return *static_cast<Derived*>(const_cast<SparseMatrixBase*>(this)); }
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
convert_index()
template<typename _Scalar , int _Options, typename _StorageIndex > static StorageIndex Eigen::SparseMatrixBase< Derived >::convert_index (const Index idx) inline static private
{
      return internal::convert_index<StorageIndex>(idx);
    }
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize().
cwiseProduct() [1/2]
EIGEN_STRONG_INLINE const SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::template CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
{
  return typename CwiseProductDenseReturnType<OtherDerived>::Type(derived(), other.derived());
}
cwiseProduct() [2/2]
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
derived() [1/2]
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::derived () inline inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::derived () const inline inherited
{ return *static_cast<const Derived*>(this); }
dot() [1/4]
internal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::dot (const MatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  eigen_assert(other.size()>0 && "you are using a non initialized vector");
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  Scalar res(0);
  while (i)
  {
    res += numext::conj(i.value()) * other.coeff(i.index());
    ++i;
  }
  return res;
}
dot() [2/4]
Scalar Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::dot (const MatrixBase< OtherDerived > & other) const inherited
dot() [3/4]
internal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  internal::evaluator<OtherDerived>  otherEval(other.derived());
  typename internal::evaluator<OtherDerived>::InnerIterator j(otherEval, 0);
  Scalar res(0);
  while (i && j)
  {
    if (i.index()==j.index())
    {
      res += numext::conj(i.value()) * j.value();
      ++i; ++j;
    }
    else if (i.index()<j.index())
      ++i;
    else
      ++j;
  }
  return res;
}
dot() [4/4]
Scalar Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
endFill()
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DEPRECATED void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::endFill () inline
{}
eval()
const internal::eval< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
    { return typename internal::eval<Derived>::type(derived()); }
evalTo()
void Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::evalTo (Dest &) const private inherited
fill()
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DEPRECATED Scalar & Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fill (Index row, Index col) inline
See also
fillrand(), coeffRef()
    {
      const Index outer = IsRowMajor ? row : col;
      const Index inner = IsRowMajor ? col : row;
      return insertBack(outer,inner);
    }
References col(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, and row().
fillrand()
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DEPRECATED Scalar & Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fillrand (Index row, Index col) inline
    {
      return insert(row,col);
    }
References col(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), and row().
finalize()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::finalize () inline
Does nothing: provided for compatibility with SparseMatrix
{}
innerNonZeros()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::innerNonZeros (Index j) const inline
{ return m_data[j].size(); }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data.
innerSize()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::innerSize () const inline
{ return m_innerSize; }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize.
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resizeAndKeepData().
innerVector() [1/2]
SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::InnerVectorReturnType Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::innerVector (Index outer) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{ return InnerVectorReturnType(derived(), outer); }
innerVector() [2/2]
const SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::ConstInnerVectorReturnType Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::innerVector (Index outer) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{ return ConstInnerVectorReturnType(derived(), outer); }
innerVectors() [1/2]
SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::InnerVectorsReturnType Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::innerVectors (Index outerStart, Index outerSize) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{
  return Block<Derived,Dynamic,Dynamic,true>(derived(),
                                             IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                             IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
innerVectors() [2/2]
const SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::ConstInnerVectorsReturnType Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::innerVectors (Index outerStart, Index outerSize) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{
  return Block<const Derived,Dynamic,Dynamic,true>(derived(),
                                                  IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                                  IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
insert()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar & Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insert (Index row, Index col) inline
    {
      const Index outer = IsRowMajor ? row : col;
      const Index inner = IsRowMajor ? col : row;
      Index startId = 0;
      Index id = static_cast<Index>(m_data[outer].size()) - 1;
      m_data[outer].resize(id+2,1);
      while ( (id >= startId) && (m_data[outer].index(id) > inner) )
      {
        m_data[outer].index(id+1) = m_data[outer].index(id);
        m_data[outer].value(id+1) = m_data[outer].value(id);
        --id;
      }
      m_data[outer].index(id+1) = inner;
      m_data[outer].value(id+1) = 0;
      return m_data[outer].value(id+1);
    }
References col(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, and row().
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fillrand().
insertBack()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar & Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack (Index row, Index col) inline
Returns
a reference to the non zero coefficient at position row, col assuming that:
the nonzero does not already exist
the new coefficient is the last one of the given inner vector.
See also
insert, insertBackByOuterInner
    {
      return insertBackByOuterInner(IsRowMajor?row:col, IsRowMajor?col:row);
    }
References col(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, and row().
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fill().
insertBackByOuterInner()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar & Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner (Index outer, Index inner) inline
See also
insertBack
    {
      eigen_assert(outer<Index(m_data.size()) && inner<m_innerSize && "out of range");
      eigen_assert(((m_data[outer].size()==0) || (m_data[outer].index(m_data[outer].size()-1)<inner))
                && "wrong sorted insertion");
      m_data[outer].append(0, inner);
      return m_data[outer].value(m_data[outer].size()-1);
    }
References eigen_assert, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, and Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::size().
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack().
isApprox() [1/2]
bool Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::isApprox (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inline inherited
    { return toDense().isApprox(other,prec); }
isApprox() [2/2]
bool Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::isApprox (const SparseMatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
{
  const typename internal::nested_eval<Derived,2,PlainObject>::type actualA(derived());
  typename internal::conditional<bool(IsRowMajor)==bool(OtherDerived::IsRowMajor),
    const typename internal::nested_eval<OtherDerived,2,PlainObject>::type,
    const PlainObject>::type actualB(other.derived());
  return (actualA - actualB).squaredNorm() <= prec * prec * numext::mini(actualA.squaredNorm(), actualB.squaredNorm());
}
isRValue()
bool Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::isRValue () const inline inherited
{ return m_isRValue; }
isVector()
bool Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::isVector () const inline inherited
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See also
rows(), cols(), IsVectorAtCompileTime.
{ return rows()==1 || cols()==1; }
markAsRValue()
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::markAsRValue () inline inherited
{ m_isRValue = true; return derived(); }
nonZeros()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::nonZeros () const inline
Returns
the number of non zero coefficients
    {
      Index res = 0;
      for (Index j=0; j<outerSize(); ++j)
        res += m_data[j].size();
      return res;
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), and Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::size().
norm()
NumTraits< typenameinternal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar >::Real Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::norm inline inherited
{
  using std::sqrt;
  return sqrt(squaredNorm());
}
operator*() [1/3]
const Product< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > , OtherDerived > Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator* (const DiagonalBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
operator*() [2/3]
const Product< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > , OtherDerived > Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator* (const MatrixBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
operator*() [3/3]
const Product< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > , OtherDerived, AliasFreeProduct > Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator* (const SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the product of two sparse matrices. By default a conservative product preserving the symbolic non zeros is performed. The automatic pruning of the small values can be achieved by calling the pruned() function in which case a totally different product algorithm is employed:
C = (A*B).pruned();             // supress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return Product<Derived,OtherDerived,AliasFreeProduct>(derived(), other.derived());
}
operator*=() [1/2]
EIGEN_STRONG_INLINE DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator*= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() *= other;
  return derived();
}
operator*=() [2/2]
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator*= (const SparseMatrixBase< OtherDerived > & other) inherited
operator+=() [1/4]
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator+= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [2/4]
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator+= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [3/4]
EIGEN_STRONG_INLINE DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() + other.derived();
}
operator+=() [4/4]
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
operator-=() [1/4]
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator-= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::sub_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [2/4]
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator-= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [3/4]
EIGEN_STRONG_INLINE DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() - other.derived();
}
operator-=() [4/4]
DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
operator/=()
EIGEN_STRONG_INLINE DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator/= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() /= other;
  return derived();
}
operator=() [1/5]
template<typename _Scalar , int _Options, typename _StorageIndex > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const Derived & other) inline
{
  internal::call_assignment_no_alias(derived(), other.derived());
  return derived();
}
operator=() [2/5]
template<typename _Scalar , int _Options, typename _StorageIndex > DynamicSparseMatrix & Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator= (const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & other) inline
    {
      if (other.isRValue())
      {
        swap(other.const_cast_derived());
      }
      else
      {
        resize(other.rows(), other.cols());
        m_data = other.m_data;
      }
      return *this;
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::SparseMatrixBase< Derived >::const_cast_derived(), Eigen::SparseMatrixBase< Derived >::isRValue(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::swap().
operator=() [3/5]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
{
  internal::call_assignment_no_alias(derived(), other.derived());
  return derived();
}
operator=() [4/5]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
{
  // TODO use the evaluator mechanism
  other.evalTo(derived());
  return derived();
}
operator=() [5/5]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const SparseMatrixBase< OtherDerived > & other) inline
{
  // by default sparse evaluation do not alias, so we can safely bypass the generic call_assignment routine
  internal::Assignment<Derived,OtherDerived,internal::assign_op<Scalar,typename OtherDerived::Scalar> >
          ::run(derived(), other.derived(), internal::assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
outerSize()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize () const inline
{ return convert_index(m_data.size()); }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::convert_index(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data.
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::nonZeros(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::reserve(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resizeAndKeepData(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::setZero().
prune()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::prune (Scalar reference, RealScalar epsilon = NumTraits<RealScalar>::dummy_precision()) inline
Suppress all nonzeros which are smaller than reference under the tolerence epsilon
    {
      for (Index j=0; j<outerSize(); ++j)
        m_data[j].prune(reference,epsilon);
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::prune().
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::prune().
pruned()
const SparseView< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > > Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::pruned (const Scalar & reference = Scalar(0), const RealScalar & epsilon = NumTraits<Scalar>::dummy_precision()) const inline inherited
Returns
an expression of *this with values smaller than reference * epsilon removed.
This method is typically used in conjunction with the product of two sparse matrices to automatically prune the smallest values as follows:
C = (A*B).pruned();             // suppress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return SparseView<Derived>(derived(), reference, epsilon);
}
reserve()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::reserve (Index reserveSize = 1000) inline
    {
      if (outerSize()>0)
      {
        Index reserveSizePerVector = (std::max)(reserveSize/outerSize(),Index(4));
        for (Index j=0; j<outerSize(); ++j)
        {
          m_data[j].reserve(reserveSizePerVector);
        }
      }
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize().
Referenced by igl::cat(), igl::diag(), igl::diag(), igl::slice(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::startFill().
resize()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize (Index rows, Index cols) inline
Resize the matrix without preserving the data (the matrix is set to zero)
    {
      const Index outerSize = IsRowMajor ? rows : cols;
      m_innerSize = convert_index(IsRowMajor ? cols : rows);
      setZero();
      if (Index(m_data.size()) != outerSize)
      {
        m_data.resize(outerSize);
      }
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::convert_index(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::setZero().
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), igl::cat(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=().
resizeAndKeepData()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resizeAndKeepData (Index rows, Index cols) inline
    {
      const Index outerSize = IsRowMajor ? rows : cols;
      const Index innerSize = IsRowMajor ? cols : rows;
      if (m_innerSize>innerSize)
      {
        // remove all coefficients with innerCoord>=innerSize
        // TODO
        //std::cerr << "not implemented yet\n";
        exit(2);
      }
      if (m_data.size() != outerSize)
      {
        m_data.resize(outerSize);
      }
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::innerSize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
rows()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::rows () const inline
{ return IsRowMajor ? outerSize() : m_innerSize; }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize().
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resizeAndKeepData(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run().
selfadjointView() [1/4]
SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::selfadjointView () inline inherited
selfadjointView() [2/4]
SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::template SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::selfadjointView () inherited
{
  return SparseSelfAdjointView<Derived, UpLo>(derived());
}
selfadjointView() [3/4]
ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::selfadjointView () const inline inherited
selfadjointView() [4/4]
SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::template ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::selfadjointView () const inherited
{
  return SparseSelfAdjointView<const Derived, UpLo>(derived());
}
setZero()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::setZero () inline
    {
      for (Index j=0; j<outerSize(); ++j)
        m_data[j].clear();
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize().
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::startFill().
size()
Index Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols().
{ return rows() * cols(); }
squaredNorm()
NumTraits< typenameinternal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar >::Real Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::squaredNorm inline inherited
{
  return numext::real((*this).cwiseAbs2().sum());
}
startFill()
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DEPRECATED void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::startFill (Index reserveSize = 1000) inline
    {
      setZero();
      reserve(reserveSize);
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::reserve(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::setZero().
startVec()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::startVec (Index) inline
Does nothing: provided for compatibility with SparseMatrix
{}
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
sum()
internal::traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::sum inherited
{
  eigen_assert(rows()>0 && cols()>0 && "you are using a non initialized matrix");
  Scalar res(0);
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (typename internal::evaluator<Derived>::InnerIterator iter(thisEval,j); iter; ++iter)
      res += iter.value();
  return res;
}
swap()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::swap (DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > & other) inline
    {
      //EIGEN_DBG_SPARSE(std::cout << "SparseMatrix:: swap\n");
      std::swap(m_innerSize, other.m_innerSize);
      //std::swap(m_outerSize, other.m_outerSize);
      m_data.swap(other.m_data);
    }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize.
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=().
toDense()
DenseMatrixType Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::toDense () const inline inherited
    {
      return DenseMatrixType(derived());
    }
transpose() [1/2]
TransposeReturnType Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::transpose () inline inherited
{ return TransposeReturnType(derived()); }
transpose() [2/2]
const ConstTransposeReturnType Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::transpose () const inline inherited
{ return ConstTransposeReturnType(derived()); }
triangularView()
const TriangularView< const DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > , Mode > Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::triangularView inline inherited
{
  return TriangularView<const Derived, Mode>(derived());
}
twistedBy()
SparseSymmetricPermutationProduct< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > , Upper|Lower > Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline inherited
Returns
an expression of P H P^-1 where H is the matrix represented by *this
    {
      return SparseSymmetricPermutationProduct<Derived,Upper|Lower>(derived(), perm);
    }
Member Data Documentation
m_data
template<typename _Scalar , int _Options, typename _StorageIndex > std::vector<internal::CompressedStorage<Scalar,StorageIndex> > Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_data protected
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::_data(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::_data(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::innerNonZeros(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::nonZeros(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::reserve(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resizeAndKeepData(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::setZero(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::swap().
m_innerSize
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize protected
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::innerSize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::resizeAndKeepData(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::swap().
m_isRValue
bool Eigen::SparseMatrixBase< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::m_isRValue protected inherited
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/SparseCore/SparseUtil.h
src/eigen/unsupported/Eigen/src/SparseExtra/DynamicSparseMatrix.h