Prusa Slicer: Slic3r::GUI::SplashScreen Class Reference
Slic3r::GUI::SplashScreen Class Reference
Classes
struct ConstantText
Public Member Functions
SplashScreen (const wxBitmap &bitmap, long splashStyle, int milliseconds, wxPoint pos=wxDefaultPosition)
void SetText (const wxString &text)
void Decorate (wxBitmap &bmp)
Static Public Member Functions
static wxBitmap MakeBitmap (wxBitmap bmp)
Private Member Functions
void init_constant_text ()
void set_bitmap (wxBitmap &bmp)
void scale_bitmap (wxBitmap &bmp, float scale)
void scale_font (wxFont &font, float scale)
int word_wrap_string (wxString &input)
Private Attributes
wxBitmap m_main_bitmap
wxFont m_action_font
int m_action_line_y_position
float m_scale {1.0}
struct Slic3r::GUI::SplashScreen::ConstantText m_constant_text
Detailed Description
Constructor & Destructor Documentation
SplashScreen()
Slic3r::GUI::SplashScreen::SplashScreen (const wxBitmap & bitmap, long splashStyle, int milliseconds, wxPoint pos = wxDefaultPosition) inline
        : wxSplashScreen(bitmap, splashStyle, milliseconds, static_cast<wxWindow*>(wxGetApp().mainframe), wxID_ANY, wxDefaultPosition, wxDefaultSize,
#ifdef __APPLE__
            wxSIMPLE_BORDER | wxFRAME_NO_TASKBAR | wxSTAY_ON_TOP
#else
            wxSIMPLE_BORDER | wxFRAME_NO_TASKBAR
#endif // !__APPLE__
        )
    {
        wxASSERT(bitmap.IsOk());
//        int init_dpi = get_dpi_for_window(this);
        this->SetPosition(pos);
        // The size of the SplashScreen can be hanged after its moving to another display
        // So, update it from a bitmap size
        this->SetClientSize(bitmap.GetWidth(), bitmap.GetHeight());
        this->CenterOnScreen();
//        int new_dpi = get_dpi_for_window(this);
//        m_scale         = (float)(new_dpi) / (float)(init_dpi);
        m_main_bitmap   = bitmap;
//        scale_bitmap(m_main_bitmap, m_scale);
        // init constant texts and scale fonts
        init_constant_text();
        // this font will be used for the action string
        m_action_font = m_constant_text.credits_font.Bold();
        // draw logo and constant info text
        Decorate(m_main_bitmap);
    }
References Slic3r::GUI::SplashScreen::ConstantText::credits_font, Decorate(), init_constant_text(), m_action_font, m_constant_text, and m_main_bitmap.
Member Function Documentation
Decorate()
void Slic3r::GUI::SplashScreen::Decorate (wxBitmap & bmp) inline
    {
        if (!bmp.IsOk())
            return;
        // draw text to the box at the left of the splashscreen.
        // this box will be 2/5 of the weight of the bitmap, and be at the left.
        int width = lround(bmp.GetWidth() * 0.4);
        // load bitmap for logo
        BitmapCache bmp_cache;
        int logo_size = lround(width * 0.25);
        wxBitmap* logo_bmp_ptr = bmp_cache.load_svg(wxGetApp().logo_name(), logo_size, logo_size);
        if (logo_bmp_ptr == nullptr)
            return;
        wxBitmap logo_bmp = *logo_bmp_ptr;
        wxCoord margin = int(m_scale * 20);
        wxRect banner_rect(wxPoint(0, logo_size), wxPoint(width, bmp.GetHeight()));
        banner_rect.Deflate(margin, 2 * margin);
        // use a memory DC to draw directly onto the bitmap
        wxMemoryDC memDc(bmp);
        // draw logo
        memDc.DrawBitmap(logo_bmp, margin, margin, true);
        // draw the (white) labels inside of our black box (at the left of the splashscreen)
        memDc.SetTextForeground(wxColour(255, 255, 255));
        memDc.SetFont(m_constant_text.title_font);
        memDc.DrawLabel(m_constant_text.title,   banner_rect, wxALIGN_TOP | wxALIGN_LEFT);
        int title_height = memDc.GetTextExtent(m_constant_text.title).GetY();
        banner_rect.SetTop(banner_rect.GetTop() + title_height);
        banner_rect.SetHeight(banner_rect.GetHeight() - title_height);
        memDc.SetFont(m_constant_text.version_font);
        memDc.DrawLabel(m_constant_text.version, banner_rect, wxALIGN_TOP | wxALIGN_LEFT);
        int version_height = memDc.GetTextExtent(m_constant_text.version).GetY();
        memDc.SetFont(m_constant_text.credits_font);
        memDc.DrawLabel(m_constant_text.credits, banner_rect, wxALIGN_BOTTOM | wxALIGN_LEFT);
        int credits_height = memDc.GetMultiLineTextExtent(m_constant_text.credits).GetY();
        int text_height    = memDc.GetTextExtent("text").GetY();
        // calculate position for the dynamic text
        int logo_and_header_height = margin + logo_size + title_height + version_height;
        m_action_line_y_position = logo_and_header_height + 0.5 * (bmp.GetHeight() - margin - credits_height - logo_and_header_height - text_height);
    }
References Slic3r::GUI::SplashScreen::ConstantText::credits, Slic3r::GUI::SplashScreen::ConstantText::credits_font, Slic3r::GUI::BitmapCache::load_svg(), m_action_line_y_position, m_constant_text, m_scale, Slic3r::GUI::SplashScreen::ConstantText::title, Slic3r::GUI::SplashScreen::ConstantText::title_font, Slic3r::GUI::SplashScreen::ConstantText::version, and Slic3r::GUI::SplashScreen::ConstantText::version_font.
Referenced by SplashScreen().
init_constant_text()
void Slic3r::GUI::SplashScreen::init_constant_text () inline private
    {
        m_constant_text.init(get_default_font(this));
        // As default we use a system font for current display.
        // Scale fonts in respect to banner width
        int text_banner_width = lround(0.4 * m_main_bitmap.GetWidth()) - roundl(m_scale * 50); // banner_width - margins
        float title_font_scale = (float)text_banner_width / GetTextExtent(m_constant_text.title).GetX();
        scale_font(m_constant_text.title_font, title_font_scale > 3.5f ? 3.5f : title_font_scale);
        float version_font_scale = (float)text_banner_width / GetTextExtent(m_constant_text.version).GetX();
        scale_font(m_constant_text.version_font, version_font_scale > 2.f ? 2.f : version_font_scale);
        // The width of the credits information string doesn't respect to the banner width some times.
        // So, scale credits_font in the respect to the longest string width
        int   longest_string_width = word_wrap_string(m_constant_text.credits);
        float font_scale = (float)text_banner_width / longest_string_width;
        scale_font(m_constant_text.credits_font, font_scale);
    }
References Slic3r::GUI::SplashScreen::ConstantText::credits, Slic3r::GUI::SplashScreen::ConstantText::credits_font, Slic3r::GUI::get_default_font(), Slic3r::GUI::SplashScreen::ConstantText::init(), m_constant_text, m_main_bitmap, m_scale, scale_font(), Slic3r::GUI::SplashScreen::ConstantText::title, Slic3r::GUI::SplashScreen::ConstantText::title_font, Slic3r::GUI::SplashScreen::ConstantText::version, Slic3r::GUI::SplashScreen::ConstantText::version_font, and word_wrap_string().
Referenced by SplashScreen().
MakeBitmap()
static wxBitmap Slic3r::GUI::SplashScreen::MakeBitmap (wxBitmap bmp) inline static
    {
        if (!bmp.IsOk())
            return wxNullBitmap;
        // create dark grey background for the splashscreen
        // It will be 5/3 of the weight of the bitmap
        int width = lround((double)5 / 3 * bmp.GetWidth());
        int height = bmp.GetHeight();
        wxImage image(width, height);
        unsigned char* imgdata_ = image.GetData();
        for (int i = 0; i < width * height; ++i) {
            *imgdata_++ = 51;
            *imgdata_++ = 51;
            *imgdata_++ = 51;
        }
        wxBitmap new_bmp(image);
        wxMemoryDC memDC;
        memDC.SelectObject(new_bmp);
        memDC.DrawBitmap(bmp, width - bmp.GetWidth(), 0, true);
        return new_bmp;
    }
Referenced by Slic3r::GUI::GUI_App::on_init_inner().
scale_bitmap()
void Slic3r::GUI::SplashScreen::scale_bitmap (wxBitmap & bmp, float scale) inline private
    {
        if (scale == 1.0)
            return;
        wxImage image = bmp.ConvertToImage();
        if (!image.IsOk() || image.GetWidth() == 0 || image.GetHeight() == 0)
            return;
        int width   = int(scale * image.GetWidth());
        int height  = int(scale * image.GetHeight());
        image.Rescale(width, height, wxIMAGE_QUALITY_BILINEAR);
        bmp = wxBitmap(std::move(image));
    }
References scale().
scale_font()
void Slic3r::GUI::SplashScreen::scale_font (wxFont & font, float scale) inline private
    {
#ifdef __WXMSW__
        // Workaround for the font scaling in respect to the current active display,
        // not for the primary display, as it's implemented in Font.cpp
        // See https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/font.cpp
        // void wxNativeFontInfo::SetFractionalPointSize(float pointSizeNew)
        wxNativeFontInfo nfi= *font.GetNativeFontInfo();
        float pointSizeNew  = wxDisplay(this).GetScaleFactor() * scale * font.GetPointSize();
        nfi.lf.lfHeight     = nfi.GetLogFontHeightAtPPI(pointSizeNew, get_dpi_for_window(this));
        nfi.pointSize       = pointSizeNew;
        font = wxFont(nfi);
#else
        font.Scale(scale);
#endif //__WXMSW__
    }
References Slic3r::GUI::get_dpi_for_window(), and scale().
Referenced by init_constant_text().
set_bitmap()
void Slic3r::GUI::SplashScreen::set_bitmap (wxBitmap & bmp) inline private
    {
        m_window->SetBitmap(bmp);
        m_window->Refresh();
        m_window->Update();
    }
Referenced by SetText().
SetText()
void Slic3r::GUI::SplashScreen::SetText (const wxString & text) inline
    {
        set_bitmap(m_main_bitmap);
        if (!text.empty()) {
            wxBitmap bitmap(m_main_bitmap);
            wxMemoryDC memDC;
            memDC.SelectObject(bitmap);
            memDC.SetFont(m_action_font);
            memDC.SetTextForeground(wxColour(237, 107, 33));
            memDC.DrawText(text, int(m_scale * 60), m_action_line_y_position);
            memDC.SelectObject(wxNullBitmap);
            set_bitmap(bitmap);
#ifdef __WXOSX__
            // without this code splash screen wouldn't be updated under OSX
            wxYield();
#endif
        }
    }
References m_action_font, m_action_line_y_position, m_main_bitmap, m_scale, and set_bitmap().
Referenced by Slic3r::GUI::GUI_App::on_init_inner().
word_wrap_string()
int Slic3r::GUI::SplashScreen::word_wrap_string (wxString & input) inline private
    {
        size_t line_len = 55;// count of symbols in one line
        int idx = -1;
        size_t cur_len = 0;
        wxString longest_sub_string;
        auto get_longest_sub_string = [input](wxString &longest_sub_str, size_t cur_len, size_t i) {
            if (cur_len > longest_sub_str.Len())
                longest_sub_str = input.SubString(i - cur_len + 1, i);
        };
        for (size_t i = 0; i < input.Len(); i++)
        {
            cur_len++;
            if (input[i] == ' ')
                idx = i;
            if (input[i] == '\n')
            {
                get_longest_sub_string(longest_sub_string, cur_len, i);
                idx = -1;
                cur_len = 0;
            }
            if (cur_len >= line_len && idx >= 0)
            {
                get_longest_sub_string(longest_sub_string, cur_len, i);
                input[idx] = '\n';
                cur_len = i - static_cast<size_t>(idx);
            }
        }
        return GetTextExtent(longest_sub_string).GetX();
    }
References input().
Referenced by init_constant_text().
Member Data Documentation
m_action_font
wxFont Slic3r::GUI::SplashScreen::m_action_font private
Referenced by SplashScreen(), and SetText().
m_action_line_y_position
int Slic3r::GUI::SplashScreen::m_action_line_y_position private
Referenced by Decorate(), and SetText().
m_constant_text
struct Slic3r::GUI::SplashScreen::ConstantText Slic3r::GUI::SplashScreen::m_constant_text private
Referenced by SplashScreen(), Decorate(), and init_constant_text().
m_main_bitmap
wxBitmap Slic3r::GUI::SplashScreen::m_main_bitmap private
Referenced by SplashScreen(), init_constant_text(), and SetText().
m_scale
float Slic3r::GUI::SplashScreen::m_scale {1.0} private
Referenced by Decorate(), init_constant_text(), and SetText().
The documentation for this class was generated from the following file:
src/slic3r/GUI/GUI_App.cpp