Prusa Slicer: Slic3r::UndoRedo Namespace Reference
Slic3r::UndoRedo Namespace Reference
Classes
class ImmutableObjectHistory
struct Interval
struct MutableHistoryInterval
class MutableObjectHistory
class ObjectHistory
class ObjectHistoryBase
struct Selection
struct Snapshot
struct SnapshotData
class Stack
class StackImpl
Typedefs
using InputArchive = cereal::UserDataAdapter< StackImpl, cereal::BinaryInputArchive >
using OutputArchive = cereal::UserDataAdapter< StackImpl, cereal::BinaryOutputArchive >
Enumerations
enum class SnapshotType : unsigned char {
Action , GizmoAction , Selection , ProjectSeparator ,
EnteringGizmo , LeavingGizmoNoAction , LeavingGizmoWithAction
}
Functions
static bool snapshot_modifies_project (SnapshotType type)
static bool snapshot_modifies_project (const Snapshot &snapshot)
Variables
static std::string topmost_snapshot_name = "@@@ Topmost @@@"
Typedef Documentation
InputArchive
using Slic3r::UndoRedo::InputArchive = typedef cereal::UserDataAdapter<StackImpl, cereal::BinaryInputArchive>
OutputArchive
using Slic3r::UndoRedo::OutputArchive = typedef cereal::UserDataAdapter<StackImpl, cereal::BinaryOutputArchive>
Enumeration Type Documentation
SnapshotType
enum class Slic3r::UndoRedo::SnapshotType : unsigned char strong
Enumerator
Action
GizmoAction
Selection
ProjectSeparator
EnteringGizmo
LeavingGizmoNoAction
LeavingGizmoWithAction
                        : unsigned char {
  // Some action modifying project state, outside any EnteringGizmo / LeavingGizmo interval.
  Action,
  // Some action modifying project state, inside some EnteringGizmo / LeavingGizmo interval.
  GizmoAction,
  // Selection change at the Plater.
  Selection,
  // New project, Reset project, Load project ...
  ProjectSeparator,
  // Entering a Gizmo, which opens a secondary Undo / Redo stack.
  EnteringGizmo,
  // Leaving a Gizmo, which closes a secondary Undo / Redo stack.
  // No action modifying a project state was done between EnteringGizmo / LeavingGizmo.
  LeavingGizmoNoAction,
  // Leaving a Gizmo, which closes a secondary Undo / Redo stack.
  // Some action modifying a project state was done between EnteringGizmo / LeavingGizmo.
  LeavingGizmoWithAction,
};
Function Documentation
snapshot_modifies_project() [1/2]
static bool Slic3r::UndoRedo::snapshot_modifies_project (const Snapshot & snapshot) inline static
{
  return snapshot_modifies_project(snapshot.snapshot_data.snapshot_type);
}
References Slic3r::UndoRedo::Snapshot::snapshot_data, snapshot_modifies_project(), and Slic3r::UndoRedo::SnapshotData::snapshot_type.
snapshot_modifies_project() [2/2]
static bool Slic3r::UndoRedo::snapshot_modifies_project (SnapshotType type) inline static
{
  return type == SnapshotType::Action || type == SnapshotType::GizmoAction || type == SnapshotType::ProjectSeparator;
}
References Action, GizmoAction, and ProjectSeparator.
Referenced by Slic3r::UndoRedo::StackImpl::project_modified(), Slic3r::UndoRedo::StackImpl::release_snapshots(), and snapshot_modifies_project().
Variable Documentation
topmost_snapshot_name
std::string Slic3r::UndoRedo::topmost_snapshot_name = "@@@ Topmost @@@" static
Referenced by Slic3r::UndoRedo::Snapshot::is_topmost(), Slic3r::UndoRedo::StackImpl::release_least_recently_used(), and Slic3r::UndoRedo::StackImpl::take_snapshot().