Prusa Slicer: Eigen::JacobiSVD< _MatrixType, QRPreconditioner > Class Template Reference
Eigen::JacobiSVD< _MatrixType, QRPreconditioner > Class Template Reference
Two-sided Jacobi SVD decomposition of a rectangular matrix.
#include <src/eigen/Eigen/src/SVD/JacobiSVD.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , DiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime) , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime , MaxDiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_FIXED(MaxRowsAtCompileTime,MaxColsAtCompileTime) , MatrixOptions = MatrixType::Options
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typenameMatrixType::Scalar >::Real RealScalar
typedef Base::MatrixUType MatrixUType
typedef Base::MatrixVType MatrixVType
typedef Base::SingularValuesType SingularValuesType
typedef internal::plain_row_type< MatrixType >::type RowType
typedef internal::plain_col_type< MatrixType >::type ColType
typedef Matrix< Scalar, DiagSizeAtCompileTime, DiagSizeAtCompileTime, MatrixOptions, MaxDiagSizeAtCompileTime, MaxDiagSizeAtCompileTime > WorkMatrixType
enum
typedef MatrixType::StorageIndex StorageIndex
typedef Eigen::Index Index
Public Member Functions
JacobiSVD ()
Default Constructor.
JacobiSVD (Index rows, Index cols, unsigned int computationOptions=0)
Default Constructor with memory preallocation.
JacobiSVD (const MatrixType &matrix, unsigned int computationOptions=0)
Constructor performing the decomposition of given matrix.
JacobiSVD & compute (const MatrixType &matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
JacobiSVD & compute (const MatrixType &matrix)
Method performing the decomposition of given matrix using current options.
bool computeU () const
bool computeV () const
Index rows () const
Index cols () const
Index rank () const
JacobiSVD< _MatrixType, QRPreconditioner > & derived ()
const JacobiSVD< _MatrixType, QRPreconditioner > & derived () const
const MatrixUType & matrixU () const
const MatrixVType & matrixV () const
const SingularValuesType & singularValues () const
Index nonzeroSingularValues () const
JacobiSVD< _MatrixType, QRPreconditioner > & setThreshold (const RealScalar &threshold)
JacobiSVD< _MatrixType, QRPreconditioner > & setThreshold (Default_t)
RealScalar threshold () const
const Solve< JacobiSVD< _MatrixType, QRPreconditioner >, Rhs > solve (const MatrixBase< Rhs > &b) const
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
void _solve_impl (const RhsType &rhs, DstType &dst) const
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
WorkMatrixType m_workMatrix
internal::qr_preconditioner_impl< MatrixType, QRPreconditioner, internal::PreconditionIfMoreColsThanRows > m_qr_precond_morecols
internal::qr_preconditioner_impl< MatrixType, QRPreconditioner, internal::PreconditionIfMoreRowsThanCols > m_qr_precond_morerows
MatrixType m_scaledMatrix
MatrixUType m_matrixU
MatrixVType m_matrixV
SingularValuesType m_singularValues
bool m_isInitialized
bool m_isAllocated
bool m_usePrescribedThreshold
bool m_computeFullU
bool m_computeThinU
bool m_computeFullV
bool m_computeThinV
unsigned int m_computationOptions
Index m_nonzeroSingularValues
Index m_rows
Index m_cols
Index m_diagSize
RealScalar m_prescribedThreshold
Private Types
typedef SVDBase< JacobiSVD > Base
Private Member Functions
void allocate (Index rows, Index cols, unsigned int computationOptions)
Friends
template<typename __MatrixType , int _QRPreconditioner, bool _IsComplex>
struct internal::svd_precondition_2x2_block_to_be_real
template<typename __MatrixType , int _QRPreconditioner, int _Case, bool _DoAnything>
struct internal::qr_preconditioner_impl
Detailed Description
template<typename _MatrixType, int QRPreconditioner>
class Eigen::JacobiSVD< _MatrixType, QRPreconditioner >
Two-sided Jacobi SVD decomposition of a rectangular matrix.
Template Parameters
_MatrixType the type of the matrix of which we are computing the SVD decomposition
QRPreconditioner this optional parameter allows to specify the type of QR decomposition that will be used internally for the R-SVD step for non-square matrices. See discussion of possible values below.
SVD decomposition consists in decomposing any n-by-p matrix A as a product
where U is a n-by-n unitary, V is a p-by-p unitary, and S is a n-by-p real positive matrix which is zero outside of its main diagonal; the diagonal entries of S are known as the singular values of A and the columns of U and V are known as the left and right singular vectors of A respectively.
Singular values are always sorted in decreasing order.
This JacobiSVD decomposition computes only the singular values by default. If you want U or V, you need to ask for them explicitly.
You can ask for only thin U or V to be computed, meaning the following. In case of a rectangular n-by-p matrix, letting m be the smaller value among n and p, there are only m singular vectors; the remaining columns of U and V do not correspond to actual singular vectors. Asking for thin U or V means asking for only their m first columns to be formed. So U is then a n-by-m matrix, and V is then a p-by-m matrix. Notice that thin U and V are all you need for (least squares) solving.
Here's an example demonstrating basic usage:
Output:
This JacobiSVD class is a two-sided Jacobi R-SVD decomposition, ensuring optimal reliability and accuracy. The downside is that it's slower than bidiagonalizing SVD algorithms for large square matrices; however its complexity is still where n is the smaller dimension and p is the greater dimension, meaning that it is still of the same order of complexity as the faster bidiagonalizing R-SVD algorithms. In particular, like any R-SVD, it takes advantage of non-squareness in that its complexity is only linear in the greater dimension.
If the input matrix has inf or nan coefficients, the result of the computation is undefined, but the computation is guaranteed to terminate in finite (and reasonable) time.
The possible values for QRPreconditioner are:
ColPivHouseholderQRPreconditioner is the default. In practice it's very safe. It uses column-pivoting QR.
FullPivHouseholderQRPreconditioner, is the safest and slowest. It uses full-pivoting QR. Contrary to other QRs, it doesn't allow computing thin unitaries.
HouseholderQRPreconditioner is the fastest, and less safe and accurate than the pivoting variants. It uses non-pivoting QR. This is very similar in safety and accuracy to the bidiagonalization process used by bidiagonalizing SVD algorithms (since bidiagonalization is inherently non-pivoting). However the resulting SVD is still more reliable than bidiagonalizing SVDs because the Jacobi-based iterarive process is more reliable than the optimized bidiagonal SVD iterations.
NoQRPreconditioner allows not to use a QR preconditioner at all. This is useful if you know that you will only be computing JacobiSVD decompositions of square matrices. Non-square matrices require a QR preconditioner. Using this option will result in faster compilation and smaller executable code. It won't significantly speed up computation, since JacobiSVD is always checking if QR preconditioning is needed before applying it anyway.
See also
MatrixBase::jacobiSvd()
Member Typedef Documentation
Base
template<typename _MatrixType , int QRPreconditioner> typedef SVDBase<JacobiSVD> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::Base private
ColType
template<typename _MatrixType , int QRPreconditioner> typedef internal::plain_col_type<MatrixType>::type Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::ColType
Index
typedef Eigen::Index Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::Index inherited
MatrixType
template<typename _MatrixType , int QRPreconditioner> typedef _MatrixType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::MatrixType
MatrixUType
template<typename _MatrixType , int QRPreconditioner> typedef Base::MatrixUType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::MatrixUType
MatrixVType
template<typename _MatrixType , int QRPreconditioner> typedef Base::MatrixVType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::MatrixVType
RealScalar
template<typename _MatrixType , int QRPreconditioner> typedef NumTraits<typenameMatrixType::Scalar>::Real Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::RealScalar
RowType
template<typename _MatrixType , int QRPreconditioner> typedef internal::plain_row_type<MatrixType>::type Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::RowType
Scalar
template<typename _MatrixType , int QRPreconditioner> typedef MatrixType::Scalar Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::Scalar
SingularValuesType
template<typename _MatrixType , int QRPreconditioner> typedef Base::SingularValuesType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::SingularValuesType
StorageIndex
typedef MatrixType::StorageIndex Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::StorageIndex inherited
WorkMatrixType
template<typename _MatrixType , int QRPreconditioner> typedef Matrix<Scalar, DiagSizeAtCompileTime, DiagSizeAtCompileTime, MatrixOptions, MaxDiagSizeAtCompileTime, MaxDiagSizeAtCompileTime> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::WorkMatrixType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    RowsAtCompileTime = MatrixType::RowsAtCompileTime,
    ColsAtCompileTime = MatrixType::ColsAtCompileTime,
    DiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime),
    MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
    MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime,
    MaxDiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_FIXED(MaxRowsAtCompileTime,MaxColsAtCompileTime),
    MatrixOptions = MatrixType::Options
  };
anonymous enum
template<typename _MatrixType , int QRPreconditioner> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
DiagSizeAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxDiagSizeAtCompileTime
MatrixOptions
         {
      RowsAtCompileTime = MatrixType::RowsAtCompileTime,
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      DiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime),
      MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime,
      MaxDiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_FIXED(MaxRowsAtCompileTime,MaxColsAtCompileTime),
      MatrixOptions = MatrixType::Options
    };
Constructor & Destructor Documentation
JacobiSVD() [1/3]
template<typename _MatrixType , int QRPreconditioner> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::JacobiSVD () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via JacobiSVD::compute(const MatrixType&).
    {}
JacobiSVD() [2/3]
template<typename _MatrixType , int QRPreconditioner> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::JacobiSVD (Index rows, Index cols, unsigned int computationOptions = 0) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
JacobiSVD()
    {
      allocate(rows, cols, computationOptions);
    }
JacobiSVD() [3/3]
template<typename _MatrixType , int QRPreconditioner> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::JacobiSVD (const MatrixType & matrix, unsigned int computationOptions = 0) inline explicit
Constructor performing the decomposition of given matrix.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit-field, the possible bits are ComputeFullU, ComputeThinU, ComputeFullV, ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non-default) FullPivHouseholderQR preconditioner.
    {
      compute(matrix, computationOptions);
    }
Member Function Documentation
_solve_impl() [1/2]
EIGEN_DEVICE_FUNC void Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::_solve_impl (const RhsType & rhs, DstType & dst) const inherited
_solve_impl() [2/2]
void Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::_solve_impl (const RhsType & rhs, DstType & dst) const inherited
{
  eigen_assert(rhs.rows() == rows());
  // A = U S V^*
  // So A^{-1} = V S^{-1} U^*
  Matrix<Scalar, Dynamic, RhsType::ColsAtCompileTime, 0, MatrixType::MaxRowsAtCompileTime, RhsType::MaxColsAtCompileTime> tmp;
  Index l_rank = rank();
  tmp.noalias() =  m_matrixU.leftCols(l_rank).adjoint() * rhs;
  tmp = m_singularValues.head(l_rank).asDiagonal().inverse() * tmp;
  dst = m_matrixV.leftCols(l_rank) * tmp;
}
allocate()
template<typename MatrixType , int QRPreconditioner> void Eigen::JacobiSVD< MatrixType, QRPreconditioner >::allocate (Index rows, Index cols, unsigned int computationOptions) private
{
  eigen_assert(rows >= 0 && cols >= 0);
  if (m_isAllocated &&
      rows == m_rows &&
      cols == m_cols &&
      computationOptions == m_computationOptions)
  {
    return;
  }
  m_rows = rows;
  m_cols = cols;
  m_isInitialized = false;
  m_isAllocated = true;
  m_computationOptions = computationOptions;
  m_computeFullU = (computationOptions & ComputeFullU) != 0;
  m_computeThinU = (computationOptions & ComputeThinU) != 0;
  m_computeFullV = (computationOptions & ComputeFullV) != 0;
  m_computeThinV = (computationOptions & ComputeThinV) != 0;
  eigen_assert(!(m_computeFullU && m_computeThinU) && "JacobiSVD: you can't ask for both full and thin U");
  eigen_assert(!(m_computeFullV && m_computeThinV) && "JacobiSVD: you can't ask for both full and thin V");
  eigen_assert(EIGEN_IMPLIES(m_computeThinU || m_computeThinV, MatrixType::ColsAtCompileTime==Dynamic) &&
              "JacobiSVD: thin U and V are only available when your matrix has a dynamic number of columns.");
  if (QRPreconditioner == FullPivHouseholderQRPreconditioner)
  {
      eigen_assert(!(m_computeThinU || m_computeThinV) &&
              "JacobiSVD: can't compute thin U or thin V with the FullPivHouseholderQR preconditioner. "
              "Use the ColPivHouseholderQR preconditioner instead.");
  }
  m_diagSize = (std::min)(m_rows, m_cols);
  m_singularValues.resize(m_diagSize);
  if(RowsAtCompileTime==Dynamic)
    m_matrixU.resize(m_rows, m_computeFullU ? m_rows
                            : m_computeThinU ? m_diagSize
                            : 0);
  if(ColsAtCompileTime==Dynamic)
    m_matrixV.resize(m_cols, m_computeFullV ? m_cols
                            : m_computeThinV ? m_diagSize
                            : 0);
  m_workMatrix.resize(m_diagSize, m_diagSize);
  if(m_cols>m_rows)   m_qr_precond_morecols.allocate(*this);
  if(m_rows>m_cols)   m_qr_precond_morerows.allocate(*this);
  if(m_rows!=m_cols)  m_scaledMatrix.resize(rows,cols);
}
References Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, Eigen::Dynamic, eigen_assert, EIGEN_IMPLIES, and Eigen::FullPivHouseholderQRPreconditioner.
check_template_parameters()
static void Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::check_template_parameters () inline static protected inherited
  {
    EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
  }
cols()
template<typename _MatrixType , int QRPreconditioner> Index Eigen::SVDBase< Derived >::cols () const inline
{ return m_cols; }
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate().
compute() [1/2]
template<typename _MatrixType , int QRPreconditioner> JacobiSVD & Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute (const MatrixType & matrix) inline
Method performing the decomposition of given matrix using current options.
Parameters
matrix the matrix to decompose
This method uses the current computationOptions, as already passed to the constructor or to compute(const MatrixType&, unsigned int).
    {
      return compute(matrix, m_computationOptions);
    }
compute() [2/2]
template<typename MatrixType , int QRPreconditioner> JacobiSVD< MatrixType, QRPreconditioner > & Eigen::JacobiSVD< MatrixType, QRPreconditioner >::compute (const MatrixType & matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit-field, the possible bits are ComputeFullU, ComputeThinU, ComputeFullV, ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non-default) FullPivHouseholderQR preconditioner.
{
  using std::abs;
  allocate(matrix.rows(), matrix.cols(), computationOptions);
  // currently we stop when we reach precision 2*epsilon as the last bit of precision can require an unreasonable number of iterations,
  // only worsening the precision of U and V as we accumulate more rotations
  const RealScalar precision = RealScalar(2) * NumTraits<Scalar>::epsilon();
  // limit for denormal numbers to be considered zero in order to avoid infinite loops (see bug 286)
  const RealScalar considerAsZero = (std::numeric_limits<RealScalar>::min)();
  // Scaling factor to reduce over/under-flows
  RealScalar scale = matrix.cwiseAbs().maxCoeff();
  if(scale==RealScalar(0)) scale = RealScalar(1);
  /*** step 1. The R-SVD step: we use a QR decomposition to reduce to the case of a square matrix */
  if(m_rows!=m_cols)
  {
    m_scaledMatrix = matrix / scale;
    m_qr_precond_morecols.run(*this, m_scaledMatrix);
    m_qr_precond_morerows.run(*this, m_scaledMatrix);
  }
  else
  {
    m_workMatrix = matrix.block(0,0,m_diagSize,m_diagSize) / scale;
    if(m_computeFullU) m_matrixU.setIdentity(m_rows,m_rows);
    if(m_computeThinU) m_matrixU.setIdentity(m_rows,m_diagSize);
    if(m_computeFullV) m_matrixV.setIdentity(m_cols,m_cols);
    if(m_computeThinV) m_matrixV.setIdentity(m_cols, m_diagSize);
  }
  /*** step 2. The main Jacobi SVD iteration. ***/
  RealScalar maxDiagEntry = m_workMatrix.cwiseAbs().diagonal().maxCoeff();
  bool finished = false;
  while(!finished)
  {
    finished = true;
    // do a sweep: for all index pairs (p,q), perform SVD of the corresponding 2x2 sub-matrix
    for(Index p = 1; p < m_diagSize; ++p)
    {
      for(Index q = 0; q < p; ++q)
      {
        // if this 2x2 sub-matrix is not diagonal already...
        // notice that this comparison will evaluate to false if any NaN is involved, ensuring that NaN's don't
        // keep us iterating forever. Similarly, small denormal numbers are considered zero.
        RealScalar threshold = numext::maxi<RealScalar>(considerAsZero, precision * maxDiagEntry);
        if(abs(m_workMatrix.coeff(p,q))>threshold || abs(m_workMatrix.coeff(q,p)) > threshold)
        {
          finished = false;
          // perform SVD decomposition of 2x2 sub-matrix corresponding to indices p,q to make it diagonal
          // the complex to real operation returns true if the updated 2x2 block is not already diagonal
          if(internal::svd_precondition_2x2_block_to_be_real<MatrixType, QRPreconditioner>::run(m_workMatrix, *this, p, q, maxDiagEntry))
          {
            JacobiRotation<RealScalar> j_left, j_right;
            internal::real_2x2_jacobi_svd(m_workMatrix, p, q, &j_left, &j_right);
            // accumulate resulting Jacobi rotations
            m_workMatrix.applyOnTheLeft(p,q,j_left);
            if(computeU()) m_matrixU.applyOnTheRight(p,q,j_left.transpose());
            m_workMatrix.applyOnTheRight(p,q,j_right);
            if(computeV()) m_matrixV.applyOnTheRight(p,q,j_right);
            // keep track of the largest diagonal coefficient
            maxDiagEntry = numext::maxi<RealScalar>(maxDiagEntry,numext::maxi<RealScalar>(abs(m_workMatrix.coeff(p,p)), abs(m_workMatrix.coeff(q,q))));
          }
        }
      }
    }
  }
  /*** step 3. The work matrix is now diagonal, so ensure it's positive so its diagonal entries are the singular values ***/
  for(Index i = 0; i < m_diagSize; ++i)
  {
    // For a complex matrix, some diagonal coefficients might note have been
    // treated by svd_precondition_2x2_block_to_be_real, and the imaginary part
    // of some diagonal entry might not be null.
    if(NumTraits<Scalar>::IsComplex && abs(numext::imag(m_workMatrix.coeff(i,i)))>considerAsZero)
    {
      RealScalar a = abs(m_workMatrix.coeff(i,i));
      m_singularValues.coeffRef(i) = abs(a);
      if(computeU()) m_matrixU.col(i) *= m_workMatrix.coeff(i,i)/a;
    }
    else
    {
      // m_workMatrix.coeff(i,i) is already real, no difficulty:
      RealScalar a = numext::real(m_workMatrix.coeff(i,i));
      m_singularValues.coeffRef(i) = abs(a);
      if(computeU() && (a<RealScalar(0))) m_matrixU.col(i) = -m_matrixU.col(i);
    }
  }
  m_singularValues *= scale;
  /*** step 4. Sort singular values in descending order and compute the number of nonzero singular values ***/
  m_nonzeroSingularValues = m_diagSize;
  for(Index i = 0; i < m_diagSize; i++)
  {
    Index pos;
    RealScalar maxRemainingSingularValue = m_singularValues.tail(m_diagSize-i).maxCoeff(&pos);
    if(maxRemainingSingularValue == RealScalar(0))
    {
      m_nonzeroSingularValues = i;
      break;
    }
    if(pos)
    {
      pos += i;
      std::swap(m_singularValues.coeffRef(i), m_singularValues.coeffRef(pos));
      if(computeU()) m_matrixU.col(pos).swap(m_matrixU.col(i));
      if(computeV()) m_matrixV.col(pos).swap(m_matrixV.col(i));
    }
  }
  m_isInitialized = true;
  return *this;
}
References Eigen::internal::real_2x2_jacobi_svd(), scale(), and Eigen::JacobiRotation< Scalar >::transpose().
Referenced by igl::min_quad_dense_precompute(), and igl::polar_svd().
computeU()
template<typename _MatrixType , int QRPreconditioner> bool Eigen::SVDBase< Derived >::computeU () const inline
Returns
true if U (full or thin) is asked for in this SVD decomposition
{ return m_computeFullU || m_computeThinU; }
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), and Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run().
computeV()
template<typename _MatrixType , int QRPreconditioner> bool Eigen::SVDBase< Derived >::computeV () const inline
Returns
true if V (full or thin) is asked for in this SVD decomposition
{ return m_computeFullV || m_computeThinV; }
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), and Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run().
derived() [1/2]
JacobiSVD< _MatrixType, QRPreconditioner > & Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::derived () inline inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
const JacobiSVD< _MatrixType, QRPreconditioner > & Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::derived () const inline inherited
{ return *static_cast<const Derived*>(this); }
matrixU()
const MatrixUType & Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixU () const inline inherited
Returns
the U matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the U matrix is n-by-n if you asked for ComputeFullU , and is n-by-m if you asked for ComputeThinU .
The m first columns of U are the left singular vectors of the matrix being decomposed.
This method asserts that you asked for U to be computed.
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    eigen_assert(computeU() && "This SVD decomposition didn't compute U. Did you ask for it?");
    return m_matrixU;
  }
matrixV()
const MatrixVType & Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::matrixV () const inline inherited
Returns
the V matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the V matrix is p-by-p if you asked for ComputeFullV , and is p-by-m if you asked for ComputeThinV .
The m first columns of V are the right singular vectors of the matrix being decomposed.
This method asserts that you asked for V to be computed.
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    eigen_assert(computeV() && "This SVD decomposition didn't compute V. Did you ask for it?");
    return m_matrixV;
  }
nonzeroSingularValues()
Index Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::nonzeroSingularValues () const inline inherited
Returns
the number of singular values that are not exactly 0
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    return m_nonzeroSingularValues;
  }
rank()
template<typename _MatrixType , int QRPreconditioner> Index Eigen::SVDBase< Derived >::rank () const inline
Returns
the rank of the matrix of which *this is the SVD.
Note
This method has to determine which singular values should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
  {
    using std::abs;
    eigen_assert(m_isInitialized && "JacobiSVD is not initialized.");
    if(m_singularValues.size()==0) return 0;
    RealScalar premultiplied_threshold = numext::maxi<RealScalar>(m_singularValues.coeff(0) * threshold(), (std::numeric_limits<RealScalar>::min)());
    Index i = m_nonzeroSingularValues-1;
    while(i>=0 && m_singularValues.coeff(i) < premultiplied_threshold) --i;
    return i+1;
  }
Referenced by igl::null().
rows()
template<typename _MatrixType , int QRPreconditioner> Index Eigen::SVDBase< Derived >::rows () const inline
{ return m_rows; }
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate().
setThreshold() [1/2]
JacobiSVD< _MatrixType, QRPreconditioner > & Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::setThreshold (const RealScalar & threshold) inline inherited
Allows to prescribe a threshold to be used by certain methods, such as rank() and solve(), which need to determine when singular values are to be considered nonzero. This is not used for the SVD decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). The default is NumTraits<Scalar>::epsilon()
Parameters
threshold The new value to use as the threshold.
A singular value will be considered nonzero if its value is strictly greater than .
If you want to come back to the default behavior, call setThreshold(Default_t)
  {
    m_usePrescribedThreshold = true;
    m_prescribedThreshold = threshold;
    return derived();
  }
setThreshold() [2/2]
JacobiSVD< _MatrixType, QRPreconditioner > & Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::setThreshold (Default_t) inline inherited
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
svd.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
  {
    m_usePrescribedThreshold = false;
    return derived();
  }
singularValues()
const SingularValuesType & Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::singularValues () const inline inherited
Returns
the vector of singular values.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the returned vector has size m. Singular values are always sorted in decreasing order.
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    return m_singularValues;
  }
solve()
const Solve< JacobiSVD< _MatrixType, QRPreconditioner > , Rhs > Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::solve (const MatrixBase< Rhs > & b) const inline inherited
Returns
a (least squares) solution of using the current SVD decomposition of A.
Parameters
b the right-hand-side of the equation to solve.
Note
Solving requires both U and V to be computed. Thin U and V are enough, there is no need for full U or V.
SVD solving is implicitly least-squares. Thus, this method serves both purposes of exact solving and least-squares solving. In other words, the returned solution is guaranteed to minimize the Euclidean norm .
  {
    eigen_assert(m_isInitialized && "SVD is not initialized.");
    eigen_assert(computeU() && computeV() && "SVD::solve() requires both unitaries U and V to be computed (thin unitaries suffice).");
    return Solve<Derived, Rhs>(derived(), b.derived());
  }
threshold()
RealScalar Eigen::SVDBase< JacobiSVD< _MatrixType, QRPreconditioner > >::threshold () const inline inherited
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
  {
    eigen_assert(m_isInitialized || m_usePrescribedThreshold);
    // this temporary is needed to workaround a MSVC issue
    Index diagSize = (std::max<Index>)(1,m_diagSize);
    return m_usePrescribedThreshold ? m_prescribedThreshold
                                    : diagSize*NumTraits<Scalar>::epsilon();
  }
Friends And Related Symbol Documentation
internal::qr_preconditioner_impl
template<typename _MatrixType , int QRPreconditioner> template<typename __MatrixType , int _QRPreconditioner, int _Case, bool _DoAnything> friend struct internal::qr_preconditioner_impl friend
internal::svd_precondition_2x2_block_to_be_real
template<typename _MatrixType , int QRPreconditioner> template<typename __MatrixType , int _QRPreconditioner, bool _IsComplex> friend struct internal::svd_precondition_2x2_block_to_be_real friend
Member Data Documentation
m_cols
template<typename _MatrixType , int QRPreconditioner> Index Eigen::SVDBase< Derived >::m_cols protected
m_computationOptions
template<typename _MatrixType , int QRPreconditioner> unsigned int Eigen::SVDBase< Derived >::m_computationOptions protected
m_computeFullU
template<typename _MatrixType , int QRPreconditioner> bool Eigen::SVDBase< Derived >::m_computeFullU protected
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run().
m_computeFullV
template<typename _MatrixType , int QRPreconditioner> bool Eigen::SVDBase< Derived >::m_computeFullV protected
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run().
m_computeThinU
template<typename _MatrixType , int QRPreconditioner> bool Eigen::SVDBase< Derived >::m_computeThinU protected
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run().
m_computeThinV
template<typename _MatrixType , int QRPreconditioner> bool Eigen::SVDBase< Derived >::m_computeThinV protected
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run().
m_diagSize
template<typename _MatrixType , int QRPreconditioner> Index Eigen::SVDBase< Derived >::m_diagSize protected
m_isAllocated
template<typename _MatrixType , int QRPreconditioner> bool Eigen::SVDBase< Derived >::m_isAllocated protected
m_isInitialized
template<typename _MatrixType , int QRPreconditioner> bool Eigen::SVDBase< Derived >::m_isInitialized protected
m_matrixU
template<typename _MatrixType , int QRPreconditioner> MatrixUType Eigen::SVDBase< Derived >::m_matrixU protected
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), and Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run().
m_matrixV
template<typename _MatrixType , int QRPreconditioner> MatrixVType Eigen::SVDBase< Derived >::m_matrixV protected
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), and Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run().
m_nonzeroSingularValues
template<typename _MatrixType , int QRPreconditioner> Index Eigen::SVDBase< Derived >::m_nonzeroSingularValues protected
m_prescribedThreshold
template<typename _MatrixType , int QRPreconditioner> RealScalar Eigen::SVDBase< Derived >::m_prescribedThreshold protected
m_qr_precond_morecols
template<typename _MatrixType , int QRPreconditioner> internal::qr_preconditioner_impl<MatrixType, QRPreconditioner, internal::PreconditionIfMoreColsThanRows> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_qr_precond_morecols protected
m_qr_precond_morerows
template<typename _MatrixType , int QRPreconditioner> internal::qr_preconditioner_impl<MatrixType, QRPreconditioner, internal::PreconditionIfMoreRowsThanCols> Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_qr_precond_morerows protected
m_rows
template<typename _MatrixType , int QRPreconditioner> Index Eigen::SVDBase< Derived >::m_rows protected
m_scaledMatrix
template<typename _MatrixType , int QRPreconditioner> MatrixType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_scaledMatrix protected
m_singularValues
template<typename _MatrixType , int QRPreconditioner> SingularValuesType Eigen::SVDBase< Derived >::m_singularValues protected
m_usePrescribedThreshold
template<typename _MatrixType , int QRPreconditioner> bool Eigen::SVDBase< Derived >::m_usePrescribedThreshold protected
m_workMatrix
template<typename _MatrixType , int QRPreconditioner> WorkMatrixType Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_workMatrix protected
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/util/ForwardDeclarations.h
src/eigen/Eigen/src/SVD/JacobiSVD.h