Prusa Slicer: Slic3r::sla::BoxIndex Class Reference
Slic3r::sla::BoxIndex Class Reference
#include <src/libslic3r/SLA/SpatIndex.hpp>
Classes
class Impl
Public Types
enum QueryType { qtIntersects , qtWithin }
Public Member Functions
BoxIndex ()
~BoxIndex ()
BoxIndex (const BoxIndex &)
BoxIndex (BoxIndex &&)
BoxIndex & operator= (const BoxIndex &)
BoxIndex & operator= (BoxIndex &&)
void insert (const BoxIndexEl &)
void insert (const BoundingBox &bb, unsigned idx)
bool remove (const BoxIndexEl &)
std::vector< BoxIndexEl > query (const BoundingBox &, QueryType qt)
size_t size () const
bool empty () const
void foreach (std::function< void(const BoxIndexEl &el)> fn)
Private Attributes
std::unique_ptr< Impl > m_impl
Detailed Description
Class Documentation
Slic3r::sla::BoxIndex::Impl
class Slic3r::sla::BoxIndex::Impl
Class Members
typedef rtree< BoxIndexEl, rstar< 16, 4 > > BoostIndex
Class Members
BoostIndex m_store
Member Enumeration Documentation
QueryType
enum Slic3r::sla::BoxIndex::QueryType
Enumerator
qtIntersects
qtWithin
{ qtIntersects, qtWithin };
Constructor & Destructor Documentation
BoxIndex() [1/3]
Slic3r::sla::BoxIndex::BoxIndex ()
: m_impl(new Impl()) {}
~BoxIndex()
Slic3r::sla::BoxIndex::~BoxIndex ()
{}
BoxIndex() [2/3]
Slic3r::sla::BoxIndex::BoxIndex (const BoxIndex & cpy)
: m_impl(new Impl(*cpy.m_impl)) {}
BoxIndex() [3/3]
Slic3r::sla::BoxIndex::BoxIndex (BoxIndex && cpy)
: m_impl(std::move(cpy.m_impl)) {}
Member Function Documentation
empty()
bool Slic3r::sla::BoxIndex::empty () const inline
{ return size() == 0; }
References size().
foreach()
void Slic3r::sla::BoxIndex::foreach (std::function< void(const BoxIndexEl &el)> fn)
{
    for(auto& el : m_impl->m_store) fn(el);
}
References m_impl.
insert() [1/2]
void Slic3r::sla::BoxIndex::insert (const BoundingBox & bb, unsigned idx) inline
    {
        insert(std::make_pair(bb, unsigned(idx)));
    }
References insert().
insert() [2/2]
void Slic3r::sla::BoxIndex::insert (const BoxIndexEl & el)
{
    m_impl->m_store.insert(el);
}
References m_impl.
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::add(), and insert().
operator=() [1/2]
BoxIndex & Slic3r::sla::BoxIndex::operator= (BoxIndex && cpy)
{
    m_impl.swap(cpy.m_impl);
    return *this;
}
References m_impl.
operator=() [2/2]
BoxIndex & Slic3r::sla::BoxIndex::operator= (const BoxIndex & cpy)
{
    m_impl.reset(new Impl(*cpy.m_impl));
    return *this;
}
References m_impl.
query()
std::vector< BoxIndexEl > Slic3r::sla::BoxIndex::query (const BoundingBox & qrbb, BoxIndex::QueryType qt)
{
    namespace bgi = boost::geometry::index;
    std::vector<BoxIndexEl> ret; ret.reserve(m_impl->m_store.size());
    switch (qt) {
    case qtIntersects:
        m_impl->m_store.query(bgi::intersects(qrbb), std::back_inserter(ret));
        break;
    case qtWithin:
        m_impl->m_store.query(bgi::within(qrbb), std::back_inserter(ret));
    }
    return ret;
}
References m_impl, qtIntersects, and qtWithin.
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::intersects().
remove()
bool Slic3r::sla::BoxIndex::remove (const BoxIndexEl & el)
{
    return m_impl->m_store.remove(el) == 1;
}
References m_impl.
size()
size_t Slic3r::sla::BoxIndex::size () const
{
    return m_impl->m_store.size();
}
References m_impl.
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::add(), and empty().
Member Data Documentation
m_impl
std::unique_ptr<Impl> Slic3r::sla::BoxIndex::m_impl private
Referenced by foreach(), insert(), operator=(), operator=(), query(), remove(), and size().
The documentation for this class was generated from the following files:
src/libslic3r/SLA/SpatIndex.hpp
src/libslic3r/SLA/SpatIndex.cpp