Prusa Slicer: Slic3r::VertexFaceIndex Struct Reference
Slic3r::VertexFaceIndex Struct Reference
#include <src/libslic3r/TriangleMesh.hpp>
Public Types
using iterator = std::vector< size_t >::const_iterator
Public Member Functions
VertexFaceIndex (const indexed_triangle_set &its)
VertexFaceIndex ()
void create (const indexed_triangle_set &its)
void clear ()
iterator begin (size_t vertex_id) const throw ()
iterator end (size_t vertex_id) const throw ()
size_t count (size_t vertex_id) const throw ()
const Range< iterator > operator[] (size_t vertex_id) const
Private Attributes
std::vector< size_t > m_vertex_to_face_start
std::vector< size_t > m_vertex_faces_all
Detailed Description
Member Typedef Documentation
iterator
using Slic3r::VertexFaceIndex::iterator = std::vector<size_t>::const_iterator
Constructor & Destructor Documentation
VertexFaceIndex() [1/2]
Slic3r::VertexFaceIndex::VertexFaceIndex (const indexed_triangle_set & its) inline
{ this->create(its); }
References create().
VertexFaceIndex() [2/2]
Slic3r::VertexFaceIndex::VertexFaceIndex () inline
{}
Member Function Documentation
begin()
iterator Slic3r::VertexFaceIndex::begin (size_t vertex_id) const throw () inline
{ return m_vertex_faces_all.begin() + m_vertex_to_face_start[vertex_id]; }
References m_vertex_faces_all, and m_vertex_to_face_start.
Referenced by operator[]().
clear()
void Slic3r::VertexFaceIndex::clear () inline
{ m_vertex_to_face_start.clear(); m_vertex_faces_all.clear(); }
References m_vertex_faces_all, and m_vertex_to_face_start.
count()
size_t Slic3r::VertexFaceIndex::count (size_t vertex_id) const throw () inline
{ return m_vertex_to_face_start[vertex_id + 1] - m_vertex_to_face_start[vertex_id]; }
References m_vertex_to_face_start.
create()
void Slic3r::VertexFaceIndex::create (const indexed_triangle_set & its)
{
    m_vertex_to_face_start.assign(its.vertices.size() + 1, 0);
    // 1) Calculate vertex incidence by scatter.
    for (auto &face : its.indices) {
        ++ m_vertex_to_face_start[face(0) + 1];
        ++ m_vertex_to_face_start[face(1) + 1];
        ++ m_vertex_to_face_start[face(2) + 1];
    }
    // 2) Prefix sum to calculate offsets to m_vertex_faces_all.
    for (size_t i = 2; i < m_vertex_to_face_start.size(); ++ i)
        m_vertex_to_face_start[i] += m_vertex_to_face_start[i - 1];
    // 3) Scatter indices of faces incident to a vertex into m_vertex_faces_all.
    m_vertex_faces_all.assign(m_vertex_to_face_start.back(), 0);
    for (size_t face_idx = 0; face_idx < its.indices.size(); ++ face_idx) {
        auto &face = its.indices[face_idx];
        for (int i = 0; i < 3; ++ i)
            m_vertex_faces_all[m_vertex_to_face_start[face(i)] ++] = face_idx;
    }
    // 4) The previous loop modified m_vertex_to_face_start. Revert the change.
    for (auto i = int(m_vertex_to_face_start.size()) - 1; i > 0; -- i)
        m_vertex_to_face_start[i] = m_vertex_to_face_start[i - 1];
    m_vertex_to_face_start.front() = 0;
}
References indexed_triangle_set::indices, and indexed_triangle_set::vertices.
Referenced by VertexFaceIndex().
end()
iterator Slic3r::VertexFaceIndex::end (size_t vertex_id) const throw () inline
{ return m_vertex_faces_all.begin() + m_vertex_to_face_start[vertex_id + 1]; }
References m_vertex_faces_all, and m_vertex_to_face_start.
Referenced by operator[]().
operator[]()
const Range< iterator > Slic3r::VertexFaceIndex::operator[] (size_t vertex_id) const inline
{ return {begin(vertex_id), end(vertex_id)}; }
References begin(), and end().
Member Data Documentation
m_vertex_faces_all
std::vector<size_t> Slic3r::VertexFaceIndex::m_vertex_faces_all private
Referenced by begin(), clear(), and end().
m_vertex_to_face_start
std::vector<size_t> Slic3r::VertexFaceIndex::m_vertex_to_face_start private
Referenced by begin(), clear(), count(), and end().
The documentation for this struct was generated from the following files:
src/libslic3r/TriangleMesh.hpp
src/libslic3r/TriangleMesh.cpp