Prusa Slicer: Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT > Class Template Reference
Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT > Class Template Reference
#include <src/libslic3r/PrintBase.hpp>
Public Types
using PrintObjectStepEnum = PrintObjectStepEnumType
typedef PrintState< PrintObjectStepEnum, COUNT > PrintObjectState
using Timestamp = uint64_t
Public Member Functions
PrintType * print ()
const PrintType * print () const
bool is_step_done (PrintObjectStepEnum step) const
PrintStateBase::StateWithTimeStamp step_state_with_timestamp (PrintObjectStepEnum step) const
PrintStateBase::StateWithWarnings step_state_with_warnings (PrintObjectStepEnum step) const
auto last_completed_step () const
const ModelObject * model_object () const
ModelObject * model_object ()
ObjectID id () const
virtual Timestamp timestamp () const
Static Public Attributes
static constexpr const size_t PrintObjectStepEnumSize = COUNT
Protected Member Functions
PrintObjectBaseWithState (PrintType *print, ModelObject *model_object)
bool set_started (PrintObjectStepEnum step)
PrintStateBase::TimeStamp set_done (PrintObjectStepEnum step)
bool invalidate_step (PrintObjectStepEnum step)
template<typename StepTypeIterator >
bool invalidate_steps (StepTypeIterator step_begin, StepTypeIterator step_end)
bool invalidate_steps (std::initializer_list< PrintObjectStepEnum > il)
bool invalidate_all_steps ()
bool is_step_started_unguarded (PrintObjectStepEnum step) const
bool is_step_done_unguarded (PrintObjectStepEnum step) const
bool is_step_enabled_unguarded (PrintObjectStepEnum step) const
void enable_step_unguarded (PrintObjectStepEnum step, bool enable)
void enable_all_steps_unguarded (bool enable)
void finalize_impl ()
bool query_reset_dirty_step_unguarded (PrintObjectStepEnum step)
void active_step_add_warning (PrintStateBase::WarningLevel warning_level, const std::string &message, int message_id=0)
void throw_if_canceled ()
void status_update_warnings (PrintBase *print, int step, PrintStateBase::WarningLevel warning_level, const std::string &message)
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Static Protected Member Functions
static std::mutex & state_mutex (PrintBase *print)
static std::function< void()> cancel_callback (PrintBase *print)
Protected Attributes
friend PrintType
PrintType * m_print
ModelObject * m_model_object
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
PrintState< PrintObjectStepEnum, COUNT > m_state
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Detailed Description
template<typename PrintType, typename PrintObjectStepEnumType, const size_t COUNT>
class Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >
Member Typedef Documentation
PrintObjectState
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> typedef PrintState<PrintObjectStepEnum, COUNT> Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::PrintObjectState
PrintObjectStepEnum
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> using Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::PrintObjectStepEnum = PrintObjectStepEnumType
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
PrintObjectBaseWithState()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::PrintObjectBaseWithState (PrintType * print, ModelObject * model_object) inline protected
: PrintObjectBase(model_object), m_print(print) {}
Member Function Documentation
active_step_add_warning()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> void Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::active_step_add_warning (PrintStateBase::WarningLevel warning_level, const std::string & message, int message_id = 0) inline protected
{
      std::pair<PrintObjectStepEnum, bool> active_step = m_state.active_step_add_warning(warning_level, message, message_id, PrintObjectBase::state_mutex(m_print));
      if (active_step.second)
        this->status_update_warnings(m_print, static_cast<int>(active_step.first), warning_level, message);
    }
References Slic3r::PrintState< StepType, COUNT >::active_step_add_warning(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state, Slic3r::PrintObjectBase::state_mutex(), and Slic3r::PrintObjectBase::status_update_warnings().
Referenced by Slic3r::SLAPrint::Steps::generate_preview().
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
cancel_callback()
std::function< void()> Slic3r::PrintObjectBase::cancel_callback (PrintBase * print) static protected inherited
{
  return print->cancel_callback();
}
References Slic3r::PrintBase::cancel_callback().
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_all_steps(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_step(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_steps(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_steps().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
enable_all_steps_unguarded()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> void Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::enable_all_steps_unguarded (bool enable) inline protected
{ m_state.enable_all_unguarded(enable); }
References Slic3r::PrintState< StepType, COUNT >::enable_all_unguarded(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state.
enable_step_unguarded()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> void Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::enable_step_unguarded (PrintObjectStepEnum step, bool enable) inline protected
{ m_state.enable_unguarded(step, enable); }
References Slic3r::PrintState< StepType, COUNT >::enable_unguarded(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state.
Referenced by Slic3r::PrintBaseWithState< PrintStepEnumType, COUNT >::set_task_impl().
finalize_impl()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> void Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::finalize_impl () inline protected
{ m_state.enable_all_unguarded(true); m_state.mark_canceled_unguarded(); }
References Slic3r::PrintState< StepType, COUNT >::enable_all_unguarded(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state, and Slic3r::PrintState< StepType, COUNT >::mark_canceled_unguarded().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::ModelVolume::check(), Slic3r::check_model_ids_equal(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), anonymous_namespace{RaycastManager.cpp}::create_key(), priv::create_volume(), Slic3r::GUI::Emboss::create_volume_sources(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::Model::delete_object(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::ModelObjectStatusDB::get(), Slic3r::GUI::get_arrange_poly(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::inner_brim_area(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ObjectBase::load_and_construct(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::GLGizmoEmboss::process(), Slic3r::GUI::processed_objects_idxs(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::top_level_outer_brim_area(), Slic3r::GUI::update_object_cut_id(), and anonymous_namespace{EmbossJob.cpp}::update_volume_name().
invalidate_all_steps()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_all_steps () inline protected
        { return m_state.invalidate_all(PrintObjectBase::cancel_callback(m_print)); }
References Slic3r::PrintObjectBase::cancel_callback(), Slic3r::PrintState< StepType, COUNT >::invalidate_all(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state.
Referenced by Slic3r::SLAPrintObject::invalidate_all_steps().
invalidate_step()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_step (PrintObjectStepEnum step) inline protected
        { return m_state.invalidate(step, PrintObjectBase::cancel_callback(m_print)); }
References Slic3r::PrintObjectBase::cancel_callback(), Slic3r::PrintState< StepType, COUNT >::invalidate(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state.
Referenced by Slic3r::SLAPrintObject::invalidate_step().
invalidate_steps() [1/2]
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_steps (std::initializer_list< PrintObjectStepEnum > il) inline protected
        { return m_state.invalidate_multiple(il.begin(), il.end(), PrintObjectBase::cancel_callback(m_print)); }
References Slic3r::PrintObjectBase::cancel_callback(), Slic3r::PrintState< StepType, COUNT >::invalidate_multiple(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state.
invalidate_steps() [2/2]
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> template<typename StepTypeIterator > bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_steps (StepTypeIterator step_begin, StepTypeIterator step_end) inline protected
        { return m_state.invalidate_multiple(step_begin, step_end, PrintObjectBase::cancel_callback(m_print)); }
References Slic3r::PrintObjectBase::cancel_callback(), Slic3r::PrintState< StepType, COUNT >::invalidate_multiple(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state.
Referenced by Slic3r::SLAPrintObject::invalidate_step().
is_step_done()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_done (PrintObjectStepEnum step) const inline
{ return m_state.is_done(step, PrintObjectBase::state_mutex(m_print)); }
References Slic3r::PrintState< StepType, COUNT >::is_done(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state, and Slic3r::PrintObjectBase::state_mutex().
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::SLAPrintObject::pad_mesh(), and Slic3r::SLAPrintObject::support_mesh().
is_step_done_unguarded()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_done_unguarded (PrintObjectStepEnum step) const inline protected
{ return m_state.is_done_unguarded(step); }
References Slic3r::PrintState< StepType, COUNT >::is_done_unguarded(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state.
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::last_completed_step().
is_step_enabled_unguarded()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_enabled_unguarded (PrintObjectStepEnum step) const inline protected
{ return m_state.is_enabled_unguarded(step); }
References Slic3r::PrintState< StepType, COUNT >::is_enabled_unguarded(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state.
Referenced by Slic3r::PrintBaseWithState< PrintStepEnumType, COUNT >::set_task_impl().
is_step_started_unguarded()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_started_unguarded (PrintObjectStepEnum step) const inline protected
{ return m_state.is_started_unguarded(step); }
References Slic3r::PrintState< StepType, COUNT >::is_started_unguarded(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state.
Referenced by Slic3r::PrintBaseWithState< PrintStepEnumType, COUNT >::set_task_impl().
last_completed_step()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> auto Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::last_completed_step () const inline
    {
        static_assert(COUNT > 0, "Step count should be > 0");
        auto s = int(COUNT) - 1;
        std::lock_guard lk(state_mutex(m_print));
        while (s >= 0 && ! is_step_done_unguarded(PrintObjectStepEnum(s)))
            --s;
        if (s < 0)
            s = COUNT;
        return PrintObjectStepEnum(s);
    }
References Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_done_unguarded(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, and Slic3r::PrintObjectBase::state_mutex().
Referenced by Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::SLAPrintObject::get_mesh_to_print(), Slic3r::SLAPrintObject::get_parts_to_slice(), Slic3r::GUI::update_arrangepoly_slaprint(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
model_object() [1/2]
ModelObject * Slic3r::PrintObjectBase::model_object () inline inherited
{ return m_model_object; }
References Slic3r::PrintObjectBase::m_model_object.
model_object() [2/2]
const ModelObject * Slic3r::PrintObjectBase::model_object () const inline inherited
{ return m_model_object; }
References Slic3r::PrintObjectBase::m_model_object.
Referenced by Slic3r::PrintObject::PrintObject(), Slic3r::GUI::GLCanvas3D::_set_warning_notification(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::SeamPlacerImpl::compute_global_occlusion(), Slic3r::SLAPrint::Steps::drill_holes(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::SeamPlacerImpl::gather_enforcers_blockers(), Slic3r::PrintObject::is_mm_painted(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::SLAPrint::Steps::mesh_assembly(), Slic3r::mmu_segmentation_top_and_bottom_layers(), Slic3r::multi_material_segmentation_by_painting(), Slic3r::GCode::process_layer_single_object(), Slic3r::SLAPrint::Steps::slice_model(), Slic3r::SLAPrint::Steps::support_points(), Slic3r::SLAPrintObject::transformed_drainhole_points(), Slic3r::SLAPrintObject::transformed_support_points(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::Print::validate().
print() [1/2]
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> PrintType * Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::print () inline
{ return m_print; }
References Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print.
Referenced by Slic3r::FillLightning::Generator::Generator(), Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::TreeSupportMeshGroupSettings(), Slic3r::FillAdaptive::adaptive_fill_line_spacing(), Slic3r::LayerRegion::bridging_flow(), Slic3r::fff_tree_support_generate(), Slic3r::FFFTreeSupport::generate_overhangs(), Slic3r::get_boundary_external(), Slic3r::get_default_perimeter_spacing(), Slic3r::get_perimeter_spacing_external(), Slic3r::LayerRegion::make_perimeters(), Slic3r::mmu_segmentation_top_and_bottom_layers(), Slic3r::multi_material_segmentation_by_painting(), Slic3r::GCode::process_layer_single_object(), Slic3r::support_material_flow(), and Slic3r::support_material_interface_flow().
print() [2/2]
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> const PrintType * Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::print () const inline
{ return m_print; }
References Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print.
query_reset_dirty_step_unguarded()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::query_reset_dirty_step_unguarded (PrintObjectStepEnum step) inline protected
{ return m_state.query_reset_dirty_unguarded(step); }
References Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state, and Slic3r::PrintState< StepType, COUNT >::query_reset_dirty_unguarded().
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_done()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> PrintStateBase::TimeStamp Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_done (PrintObjectStepEnum step) inline protected
{
    std::pair<PrintStateBase::TimeStamp, bool> status = m_state.set_done(step, PrintObjectBase::state_mutex(m_print), [this](){ this->throw_if_canceled(); });
        if (status.second)
            this->status_update_warnings(m_print, static_cast<int>(step), PrintStateBase::WarningLevel::NON_CRITICAL, std::string());
        return status.first;
  }
References Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state, Slic3r::PrintStateBase::NON_CRITICAL, Slic3r::PrintState< StepType, COUNT >::set_done(), Slic3r::PrintObjectBase::state_mutex(), Slic3r::PrintObjectBase::status_update_warnings(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::throw_if_canceled().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_started()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> bool Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_started (PrintObjectStepEnum step) inline protected
        { return m_state.set_started(step, PrintObjectBase::state_mutex(m_print), [this](){ this->throw_if_canceled(); }); }
References Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state, Slic3r::PrintState< StepType, COUNT >::set_started(), Slic3r::PrintObjectBase::state_mutex(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::throw_if_canceled().
state_mutex()
std::mutex & Slic3r::PrintObjectBase::state_mutex (PrintBase * print) static protected inherited
{
  return print->state_mutex();
}
References Slic3r::PrintBase::state_mutex().
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::active_step_add_warning(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_done(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::last_completed_step(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_done(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_started(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::step_state_with_timestamp(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::step_state_with_warnings().
status_update_warnings()
void Slic3r::PrintObjectBase::status_update_warnings (PrintBase * print, int step, PrintStateBase::WarningLevel warning_level, const std::string & message) protected inherited
{
    print->status_update_warnings(step, warning_level, message, this);
}
References Slic3r::PrintBase::status_update_warnings().
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::active_step_add_warning(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_done().
step_state_with_timestamp()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> PrintStateBase::StateWithTimeStamp Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::step_state_with_timestamp (PrintObjectStepEnum step) const inline
{ return m_state.state_with_timestamp(step, PrintObjectBase::state_mutex(m_print)); }
References Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state, Slic3r::PrintObjectBase::state_mutex(), and Slic3r::PrintState< StepType, COUNT >::state_with_timestamp().
step_state_with_warnings()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> PrintStateBase::StateWithWarnings Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::step_state_with_warnings (PrintObjectStepEnum step) const inline
{ return m_state.state_with_warnings(step, PrintObjectBase::state_mutex(m_print)); }
References Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state, Slic3r::PrintObjectBase::state_mutex(), and Slic3r::PrintState< StepType, COUNT >::state_with_warnings().
Referenced by Slic3r::GUI::Plater::priv::on_slicing_update().
throw_if_canceled()
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> void Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::throw_if_canceled () inline protected
{ if (m_print->canceled()) throw CanceledException(); }
References Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print.
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_done(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_started().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
Referenced by Slic3r::GUI::Plater::priv::undo_redo_to().
Member Data Documentation
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_model_object
ModelObject* Slic3r::PrintObjectBase::m_model_object protected inherited
Referenced by Slic3r::SLAPrint::Steps::generate_preview(), Slic3r::PrintObjectBase::model_object(), Slic3r::PrintObjectBase::model_object(), and Slic3r::SLAPrint::Steps::support_points().
m_print
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> PrintType* Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_print protected
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::active_step_add_warning(), Slic3r::SLAPrint::Steps::generate_preview_vdb(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_all_steps(), Slic3r::SLAPrintObject::invalidate_all_steps(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_step(), Slic3r::SLAPrintObject::invalidate_step(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_steps(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_steps(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_done(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::last_completed_step(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::print(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::print(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_done(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_started(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::step_state_with_timestamp(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::step_state_with_warnings(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::throw_if_canceled().
m_state
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> PrintState<PrintObjectStepEnum, COUNT> Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::m_state private
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::active_step_add_warning(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::enable_all_steps_unguarded(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::enable_step_unguarded(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::finalize_impl(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_all_steps(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_step(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_steps(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::invalidate_steps(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_done(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_done_unguarded(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_enabled_unguarded(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_started_unguarded(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::query_reset_dirty_step_unguarded(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_done(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::set_started(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::step_state_with_timestamp(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::step_state_with_warnings().
PrintObjectStepEnumSize
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> constexpr const size_t Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::PrintObjectStepEnumSize = COUNT static constexpr
PrintType
template<typename PrintType , typename PrintObjectStepEnumType , const size_t COUNT> friend Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::PrintType protected
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
The documentation for this class was generated from the following file:
src/libslic3r/PrintBase.hpp