Prusa Slicer: Slic3r::Arachne::PathsPointIndex< Paths > Class Template Reference
Slic3r::Arachne::PathsPointIndex< Paths > Class Template Reference
#include <src/libslic3r/Arachne/utils/PolygonsPointIndex.hpp>
Public Member Functions
PathsPointIndex ()
PathsPointIndex (const Paths *polygons, unsigned int poly_idx, unsigned int point_idx)
PathsPointIndex (const PathsPointIndex &original)=default
Point p () const
bool initialized () const
Returns whether this point is initialised.
const Polygon & getPolygon () const
bool operator== (const PathsPointIndex &other) const
bool operator!= (const PathsPointIndex &other) const
bool operator< (const PathsPointIndex &other) const
PathsPointIndex & operator= (const PathsPointIndex &other)
PathsPointIndex & operator++ ()
move the iterator forward (and wrap around at the end)
PathsPointIndex & operator-- ()
move the iterator backward (and wrap around at the beginning)
PathsPointIndex next () const
move the iterator forward (and wrap around at the end)
PathsPointIndex prev () const
move the iterator backward (and wrap around at the beginning)
Public Attributes
const Paths * polygons
unsigned int poly_idx
The index of the polygon in PolygonsPointIndex::polygons.
unsigned int point_idx
The index of the point in the polygon in PolygonsPointIndex::polygons.
Detailed Description
template<typename Paths>
class Slic3r::Arachne::PathsPointIndex< Paths >
A class for iterating over the points in one of the polygons in a Polygons object
Constructor & Destructor Documentation
PathsPointIndex() [1/3]
template<typename Paths > Slic3r::Arachne::PathsPointIndex< Paths >::PathsPointIndex () inline
Constructs an empty point index to no polygon.
This is used as a placeholder for when there is a zero-construction needed. Since the polygons field is const you can't ever make this initialisation useful.
: polygons(nullptr), poly_idx(0), point_idx(0) {}
PathsPointIndex() [2/3]
template<typename Paths > Slic3r::Arachne::PathsPointIndex< Paths >::PathsPointIndex (const Paths * polygons, unsigned int poly_idx, unsigned int point_idx) inline
Constructs a new point index to a vertex of a polygon.
Parameters
polygons The Polygons instance to which this index points.
poly_idx The index of the sub-polygon to point to.
point_idx The index of the vertex in the sub-polygon.
: polygons(polygons), poly_idx(poly_idx), point_idx(point_idx) {}
PathsPointIndex() [3/3]
template<typename Paths > Slic3r::Arachne::PathsPointIndex< Paths >::PathsPointIndex (const PathsPointIndex< Paths > & original) default
Copy constructor to copy these indices.
Member Function Documentation
getPolygon()
template<typename Paths > const Polygon & Slic3r::Arachne::PathsPointIndex< Paths >::getPolygon () const inline
Get the polygon to which this PolygonsPointIndex refers
{ return (*polygons)[poly_idx]; }
References Slic3r::Arachne::PathsPointIndex< Paths >::poly_idx, and Slic3r::Arachne::PathsPointIndex< Paths >::polygons.
initialized()
template<typename Paths > bool Slic3r::Arachne::PathsPointIndex< Paths >::initialized () const inline
Returns whether this point is initialised.
{ return polygons; }
References Slic3r::Arachne::PathsPointIndex< Paths >::polygons.
Referenced by Slic3r::Arachne::PolylineStitcher< Paths, Path, Junction >::stitch().
next()
template<typename Paths > PathsPointIndex Slic3r::Arachne::PathsPointIndex< Paths >::next () const inline
move the iterator forward (and wrap around at the end)
    {
        PathsPointIndex ret(*this);
        ++ret;
        return ret;
    }
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::computePointCellRange(), boost::polygon::segment_traits< Slic3r::Arachne::PolygonsSegmentIndex >::get(), and Slic3r::Arachne::PolygonsSegmentIndex::to().
operator!=()
template<typename Paths > bool Slic3r::Arachne::PathsPointIndex< Paths >::operator!= (const PathsPointIndex< Paths > & other) const inline
    {
        return !(*this == other);
    }
operator++()
template<typename Paths > PathsPointIndex & Slic3r::Arachne::PathsPointIndex< Paths >::operator++ () inline
move the iterator forward (and wrap around at the end)
    {
        point_idx = (point_idx + 1) % (*polygons)[poly_idx].size();
        return *this;
    }
References Slic3r::Arachne::PathsPointIndex< Paths >::point_idx, Slic3r::Arachne::PathsPointIndex< Paths >::poly_idx, and Slic3r::Arachne::PathsPointIndex< Paths >::polygons.
operator--()
template<typename Paths > PathsPointIndex & Slic3r::Arachne::PathsPointIndex< Paths >::operator-- () inline
move the iterator backward (and wrap around at the beginning)
    {
        if (point_idx == 0)
            point_idx = (*polygons)[poly_idx].size();
        point_idx--;
        return *this;
    }
References Slic3r::Arachne::PathsPointIndex< Paths >::point_idx, and Slic3r::Arachne::PathsPointIndex< Paths >::poly_idx.
operator<()
template<typename Paths > bool Slic3r::Arachne::PathsPointIndex< Paths >::operator< (const PathsPointIndex< Paths > & other) const inline
    {
        return this->p() < other.p();
    }
References Slic3r::Arachne::PathsPointIndex< Paths >::p().
operator=()
template<typename Paths > PathsPointIndex & Slic3r::Arachne::PathsPointIndex< Paths >::operator= (const PathsPointIndex< Paths > & other) inline
    {
        polygons  = other.polygons;
        poly_idx  = other.poly_idx;
        point_idx = other.point_idx;
        return *this;
    }
References Slic3r::Arachne::PathsPointIndex< Paths >::point_idx, Slic3r::Arachne::PathsPointIndex< Paths >::poly_idx, and Slic3r::Arachne::PathsPointIndex< Paths >::polygons.
operator==()
template<typename Paths > bool Slic3r::Arachne::PathsPointIndex< Paths >::operator== (const PathsPointIndex< Paths > & other) const inline
Test whether two iterators refer to the same polygon in the same polygon list.
Parameters
other The PolygonsPointIndex to test for equality
Returns
Wether the right argument refers to the same polygon in the same ListPolygon as the left argument.
    {
        return polygons == other.polygons && poly_idx == other.poly_idx && point_idx == other.point_idx;
    }
References Slic3r::Arachne::PathsPointIndex< Paths >::point_idx, Slic3r::Arachne::PathsPointIndex< Paths >::poly_idx, and Slic3r::Arachne::PathsPointIndex< Paths >::polygons.
p()
template<typename Paths > Point Slic3r::Arachne::PathsPointIndex< Paths >::p () const inline
    {
        if (!polygons)
            return {0, 0};
        return make_point((*polygons)[poly_idx][point_idx]);
    }
References Slic3r::Arachne::make_point(), Slic3r::Arachne::PathsPointIndex< Paths >::point_idx, Slic3r::Arachne::PathsPointIndex< Paths >::poly_idx, and Slic3r::Arachne::PathsPointIndex< Paths >::polygons.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::computePointCellRange(), Slic3r::Arachne::PolygonsSegmentIndex::from(), boost::polygon::segment_traits< Slic3r::Arachne::PolygonsSegmentIndex >::get(), Slic3r::Arachne::PathsPointIndexLocator< Paths >::operator()(), std::hash< Slic3r::Arachne::PolygonsPointIndex >::operator()(), Slic3r::Arachne::PathsPointIndex< Paths >::operator<(), Slic3r::Arachne::PolylineStitcher< Paths, Path, Junction >::stitch(), and Slic3r::Arachne::PolygonsSegmentIndex::to().
prev()
template<typename Paths > PathsPointIndex Slic3r::Arachne::PathsPointIndex< Paths >::prev () const inline
move the iterator backward (and wrap around at the beginning)
    {
        PathsPointIndex ret(*this);
        --ret;
        return ret;
    }
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::computePointCellRange().
Member Data Documentation
point_idx
template<typename Paths > unsigned int Slic3r::Arachne::PathsPointIndex< Paths >::point_idx
The index of the point in the polygon in PolygonsPointIndex::polygons.
Referenced by Slic3r::Arachne::PolygonsPointIndexSegmentLocator::operator()(), Slic3r::Arachne::PathsPointIndex< Paths >::operator++(), Slic3r::Arachne::PathsPointIndex< Paths >::operator--(), Slic3r::Arachne::PathsPointIndex< Paths >::operator=(), Slic3r::Arachne::PathsPointIndex< Paths >::operator==(), Slic3r::Arachne::PathsPointIndex< Paths >::p(), and Slic3r::Arachne::PolylineStitcher< Paths, Path, Junction >::stitch().
poly_idx
template<typename Paths > unsigned int Slic3r::Arachne::PathsPointIndex< Paths >::poly_idx
The index of the polygon in PolygonsPointIndex::polygons.
Referenced by Slic3r::Arachne::PolylineStitcher< Paths, Path, Junction >::canReverse(), Slic3r::Arachne::PathsPointIndex< Paths >::getPolygon(), Slic3r::Arachne::PolygonsPointIndexSegmentLocator::operator()(), Slic3r::Arachne::PathsPointIndex< Paths >::operator++(), Slic3r::Arachne::PathsPointIndex< Paths >::operator--(), Slic3r::Arachne::PathsPointIndex< Paths >::operator=(), Slic3r::Arachne::PathsPointIndex< Paths >::operator==(), Slic3r::Arachne::PathsPointIndex< Paths >::p(), and Slic3r::Arachne::PolylineStitcher< Paths, Path, Junction >::stitch().
polygons
template<typename Paths > const Paths* Slic3r::Arachne::PathsPointIndex< Paths >::polygons
The polygons into which this index is indexing.
Referenced by Slic3r::Arachne::PolylineStitcher< Paths, Path, Junction >::canReverse(), Slic3r::Arachne::PathsPointIndex< Paths >::getPolygon(), Slic3r::Arachne::PathsPointIndex< Paths >::initialized(), Slic3r::Arachne::PolygonsPointIndexSegmentLocator::operator()(), Slic3r::Arachne::PathsPointIndex< Paths >::operator++(), Slic3r::Arachne::PathsPointIndex< Paths >::operator=(), Slic3r::Arachne::PathsPointIndex< Paths >::operator==(), Slic3r::Arachne::PathsPointIndex< Paths >::p(), and Slic3r::Arachne::PolylineStitcher< Paths, Path, Junction >::stitch().
The documentation for this class was generated from the following file:
src/libslic3r/Arachne/utils/PolygonsPointIndex.hpp