Prusa Slicer: Slic3r::PrintRegion Class Reference
Slic3r::PrintRegion Class Reference
#include <src/libslic3r/Print.hpp>
Public Member Functions
PrintRegion ()=default
PrintRegion (const PrintRegionConfig &config)
PrintRegion (const PrintRegionConfig &config, const size_t config_hash, int print_object_region_id=-1)
PrintRegion (PrintRegionConfig &&config)
PrintRegion (PrintRegionConfig &&config, const size_t config_hash, int print_object_region_id=-1)
~PrintRegion ()=default
const PrintRegionConfig & config () const throw ()
size_t config_hash () const throw ()
int print_region_id () const throw ()
int print_object_region_id () const throw ()
unsigned int extruder (FlowRole role) const
Flow flow (const PrintObject &object, FlowRole role, double layer_height, bool first_layer=false) const
coordf_t nozzle_dmr_avg (const PrintConfig &print_config) const
coordf_t bridging_height_avg (const PrintConfig &print_config) const
void collect_object_printing_extruders (const Print &print, std::vector< unsigned int > &object_extruders) const
void set_config (const PrintRegionConfig &config)
void set_config (PrintRegionConfig &&config)
void config_apply_only (const ConfigBase &other, const t_config_option_keys &keys, bool ignore_nonexistent=false)
Static Public Member Functions
static void collect_object_printing_extruders (const PrintConfig &print_config, const PrintRegionConfig &region_config, const bool has_brim, std::vector< unsigned int > &object_extruders)
Private Attributes
friend Print
PrintRegionConfig m_config
size_t m_config_hash
int m_print_region_id { -1 }
int m_print_object_region_id { -1 }
int m_ref_cnt { 0 }
Friends
void print_region_ref_inc (PrintRegion &)
void print_region_ref_reset (PrintRegion &)
int print_region_ref_cnt (const PrintRegion &)
Detailed Description
Constructor & Destructor Documentation
PrintRegion() [1/5]
Slic3r::PrintRegion::PrintRegion () default
PrintRegion() [2/5]
Slic3r::PrintRegion::PrintRegion (const PrintRegionConfig & config)
: PrintRegion(config, config.hash()) {}
PrintRegion() [3/5]
Slic3r::PrintRegion::PrintRegion (const PrintRegionConfig & config, const size_t config_hash, int print_object_region_id = -1) inline
: m_config(config), m_config_hash(config_hash), m_print_object_region_id(print_object_region_id) {}
PrintRegion() [4/5]
Slic3r::PrintRegion::PrintRegion (PrintRegionConfig && config)
: PrintRegion(std::move(config), config.hash()) {}
PrintRegion() [5/5]
Slic3r::PrintRegion::PrintRegion (PrintRegionConfig && config, const size_t config_hash, int print_object_region_id = -1) inline
: m_config(std::move(config)), m_config_hash(config_hash), m_print_object_region_id(print_object_region_id) {}
~PrintRegion()
Slic3r::PrintRegion::~PrintRegion () default
Member Function Documentation
bridging_height_avg()
coordf_t Slic3r::PrintRegion::bridging_height_avg (const PrintConfig & print_config) const
{
    return this->nozzle_dmr_avg(print_config) * sqrt(m_config.bridge_flow_ratio.value);
}
References m_config, nozzle_dmr_avg(), and sqrt().
collect_object_printing_extruders() [1/2]
void Slic3r::PrintRegion::collect_object_printing_extruders (const Print & print, std::vector< unsigned int > & object_extruders) const
{
    // PrintRegion, if used by some PrintObject, shall have all the extruders set to an existing printer extruder.
    // If not, then there must be something wrong with the Print::apply() function.
#ifndef NDEBUG
    auto num_extruders = int(print.config().nozzle_diameter.size());
    assert(this->config().perimeter_extruder    <= num_extruders);
    assert(this->config().infill_extruder       <= num_extruders);
    assert(this->config().solid_infill_extruder <= num_extruders);
#endif
    collect_object_printing_extruders(print.config(), this->config(), print.has_brim(), object_extruders);
}
References collect_object_printing_extruders(), config(), Slic3r::Print::config(), Slic3r::Print::has_brim(), Slic3r::perimeter_extruder(), and Slic3r::solid_infill_extruder().
Referenced by collect_object_printing_extruders().
collect_object_printing_extruders() [2/2]
void Slic3r::PrintRegion::collect_object_printing_extruders (const PrintConfig & print_config, const PrintRegionConfig & region_config, const bool has_brim, std::vector< unsigned int > & object_extruders) static
{
    // These checks reflect the same logic used in the GUI for enabling/disabling extruder selection fields.
    auto num_extruders = (int)print_config.nozzle_diameter.size();
    auto emplace_extruder = [num_extruders, &object_extruders](int extruder_id) {
      int i = std::max(0, extruder_id - 1);
        object_extruders.emplace_back((i >= num_extruders) ? 0 : i);
    };
    if (region_config.perimeters.value > 0 || has_brim)
      emplace_extruder(region_config.perimeter_extruder);
    if (region_config.fill_density.value > 0)
      emplace_extruder(region_config.infill_extruder);
    if (region_config.top_solid_layers.value > 0 || region_config.bottom_solid_layers.value > 0)
      emplace_extruder(region_config.solid_infill_extruder);
}
config()
const PrintRegionConfig & Slic3r::PrintRegion::config () const throw () inline
{ return m_config; }
References m_config.
Referenced by Slic3r::FFFSupport::SupportParameters::SupportParameters(), Slic3r::FillAdaptive::adaptive_fill_line_spacing(), Slic3r::Print::apply(), Slic3r::DoExport::autospeed_volumetric_limit(), Slic3r::LayerRegion::bridging_flow(), Slic3r::ToolOrdering::collect_extruders(), collect_object_printing_extruders(), Slic3r::PrintObject::combine_infill(), Slic3r::PrintObject::discover_horizontal_shells(), Slic3r::PrintObject::discover_vertical_shells(), Slic3r::LayerTools::extruder(), Slic3r::group_fills(), Slic3r::LayerTools::infill_extruder(), Slic3r::is_overriddable(), Slic3r::Layer::make_perimeters(), Slic3r::PrintObject::make_perimeters(), Slic3r::LayerRegion::make_perimeters(), Slic3r::mmu_segmentation_top_and_bottom_layers(), Slic3r::operator==(), Slic3r::LayerTools::perimeter_extruder(), Slic3r::GCode::process_layer_single_object(), Slic3r::FFFSupport::remove_bridges_from_contacts(), set_config(), set_config(), Slic3r::LayerTools::solid_infill_extruder(), Slic3r::Layer::sort_perimeters_into_islands(), and Slic3r::verify_update_print_object_regions().
config_apply_only()
void Slic3r::PrintRegion::config_apply_only (const ConfigBase & other, const t_config_option_keys & keys, bool ignore_nonexistent = false) inline
                                        { m_config.apply_only(other, keys, ignore_nonexistent); m_config_hash = m_config.hash(); }
References m_config, and m_config_hash.
config_hash()
size_t Slic3r::PrintRegion::config_hash () const throw () inline
{ return m_config_hash; }
References m_config_hash.
Referenced by Slic3r::Print::apply(), and Slic3r::operator==().
extruder()
unsigned int Slic3r::PrintRegion::extruder (FlowRole role) const
{
    size_t extruder = 0;
    if (role == frPerimeter || role == frExternalPerimeter)
        extruder = m_config.perimeter_extruder;
    else if (role == frInfill)
        extruder = m_config.infill_extruder;
    else if (role == frSolidInfill || role == frTopSolidInfill)
        extruder = m_config.solid_infill_extruder;
    else
        throw Slic3r::InvalidArgument("Unknown role");
    return extruder;
}
References extruder(), Slic3r::frExternalPerimeter, Slic3r::frInfill, Slic3r::frPerimeter, Slic3r::frSolidInfill, Slic3r::frTopSolidInfill, and m_config.
Referenced by Slic3r::LayerRegion::bridging_flow(), extruder(), and Slic3r::group_fills().
flow()
Flow Slic3r::PrintRegion::flow (const PrintObject & object, FlowRole role, double layer_height, bool first_layer = false) const
{
    const PrintConfig          &print_config = object.print()->config();
    ConfigOptionFloatOrPercent  config_width;
    // Get extrusion width from configuration.
    // (might be an absolute value, or a percent value, or zero for auto)
    if (first_layer && print_config.first_layer_extrusion_width.value > 0) {
        config_width = print_config.first_layer_extrusion_width;
    } else if (role == frExternalPerimeter) {
        config_width = m_config.external_perimeter_extrusion_width;
    } else if (role == frPerimeter) {
        config_width = m_config.perimeter_extrusion_width;
    } else if (role == frInfill) {
        config_width = m_config.infill_extrusion_width;
    } else if (role == frSolidInfill) {
        config_width = m_config.solid_infill_extrusion_width;
    } else if (role == frTopSolidInfill) {
        config_width = m_config.top_infill_extrusion_width;
    } else {
        throw Slic3r::InvalidArgument("Unknown role");
    }
    if (config_width.value == 0)
        config_width = object.config().extrusion_width;
    // Get the configured nozzle_diameter for the extruder associated to the flow role requested.
    // Here this->extruder(role) - 1 may underflow to MAX_INT, but then the get_at() will follback to zero'th element, so everything is all right.
    auto nozzle_diameter = float(print_config.nozzle_diameter.get_at(this->extruder(role) - 1));
    return Flow::new_from_config_width(role, config_width, nozzle_diameter, float(layer_height));
}
References Slic3r::frExternalPerimeter, Slic3r::frInfill, Slic3r::frPerimeter, Slic3r::frSolidInfill, Slic3r::frTopSolidInfill, Slic3r::layer_height(), m_config, Slic3r::Flow::new_from_config_width(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::FFFSupport::SupportParameters::SupportParameters(), Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::TreeSupportMeshGroupSettings(), Slic3r::GCode::_do_export(), Slic3r::LayerRegion::flow(), and Slic3r::group_fills().
nozzle_dmr_avg()
coordf_t Slic3r::PrintRegion::nozzle_dmr_avg (const PrintConfig & print_config) const
{
    return (print_config.nozzle_diameter.get_at(m_config.perimeter_extruder.value    - 1) +
            print_config.nozzle_diameter.get_at(m_config.infill_extruder.value       - 1) +
            print_config.nozzle_diameter.get_at(m_config.solid_infill_extruder.value - 1)) / 3.;
}
References m_config.
Referenced by bridging_height_avg().
print_object_region_id()
int Slic3r::PrintRegion::print_object_region_id () const throw () inline
{ return m_print_object_region_id; }
References m_print_object_region_id.
Referenced by Slic3r::slices_to_regions().
print_region_id()
int Slic3r::PrintRegion::print_region_id () const throw () inline
{ return m_print_region_id; }
References m_print_region_id.
Referenced by Slic3r::GCode::process_layer_single_object().
set_config() [1/2]
void Slic3r::PrintRegion::set_config (const PrintRegionConfig & config) inline
{ m_config = config; m_config_hash = m_config.hash(); }
References config(), m_config, and m_config_hash.
set_config() [2/2]
void Slic3r::PrintRegion::set_config (PrintRegionConfig && config) inline
{ m_config = std::move(config); m_config_hash = m_config.hash(); }
References config(), m_config, and m_config_hash.
Friends And Related Symbol Documentation
print_region_ref_cnt
int print_region_ref_cnt (const PrintRegion & r) friend
{ return r.m_ref_cnt; }
print_region_ref_inc
void print_region_ref_inc (PrintRegion & r) friend
{ ++ r.m_ref_cnt; }
print_region_ref_reset
void print_region_ref_reset (PrintRegion & r) friend
{ r.m_ref_cnt = 0; }
Member Data Documentation
m_config
PrintRegionConfig Slic3r::PrintRegion::m_config private
Referenced by bridging_height_avg(), config(), config_apply_only(), extruder(), flow(), nozzle_dmr_avg(), set_config(), and set_config().
m_config_hash
size_t Slic3r::PrintRegion::m_config_hash private
Referenced by config_apply_only(), config_hash(), set_config(), and set_config().
m_print_object_region_id
int Slic3r::PrintRegion::m_print_object_region_id { -1 } private
Referenced by print_object_region_id().
m_print_region_id
int Slic3r::PrintRegion::m_print_region_id { -1 } private
Referenced by print_region_id().
m_ref_cnt
int Slic3r::PrintRegion::m_ref_cnt { 0 } private
Print
friend Slic3r::PrintRegion::Print private
The documentation for this class was generated from the following files:
src/libslic3r/Print.hpp
src/libslic3r/Print.cpp
src/libslic3r/PrintRegion.cpp