Prusa Slicer: Slic3r::GUI::Plater::priv Struct Reference
Slic3r::GUI::Plater::priv Struct Reference
Public Types
enum UpdateBackgroundProcessReturnState {
UPDATE_BACKGROUND_PROCESS_RESTART = 1 , UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE = 2 , UPDATE_BACKGROUND_PROCESS_INVALID = 4 , UPDATE_BACKGROUND_PROCESS_FORCE_RESTART = 8 ,
UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT = 16
}
Public Member Functions
priv (Plater *q, MainFrame *main_frame)
~priv ()
bool is_project_dirty () const
bool is_presets_dirty () const
void update_project_dirty_from_presets ()
int save_project_if_dirty (const wxString &reason)
void reset_project_dirty_after_save ()
void reset_project_dirty_initial_presets ()
void update (unsigned int flags=0)
void select_view (const std::string &direction)
void select_view_3D (const std::string &name)
void select_next_view_3D ()
bool is_preview_shown () const
bool is_preview_loaded () const
bool is_view3D_shown () const
bool are_view3D_labels_shown () const
void show_view3D_labels (bool show)
bool is_legend_shown () const
void show_legend (bool show)
bool is_sidebar_collapsed () const
void collapse_sidebar (bool collapse)
bool is_view3D_layers_editing_enabled () const
void set_current_canvas_as_dirty ()
GLCanvas3D * get_current_canvas3D ()
void unbind_canvas_event_handlers ()
void reset_canvas_volumes ()
bool init_view_toolbar ()
bool init_collapse_toolbar ()
void set_preview_layers_slider_values_range (int bottom, int top)
void update_preview_moves_slider ()
void enable_preview_moves_slider (bool enable)
void reset_gcode_toolpaths ()
void reset_all_gizmos ()
void apply_free_camera_correction (bool apply=true)
void update_ui_from_settings ()
void update_main_toolbar_tooltips ()
bool get_config_bool (const std::string &key) const
std::vector< size_t > load_files (const std::vector< fs::path > &input_files, bool load_model, bool load_config, bool used_inches=false)
std::vector< size_t > load_model_objects (const ModelObjectPtrs &model_objects, bool allow_negative_z=false, bool call_selection_changed=true)
fs::path get_export_file_path (GUI::FileType file_type)
wxString get_export_file (GUI::FileType file_type)
const Selection & get_selection () const
Selection & get_selection ()
int get_selected_object_idx () const
int get_selected_instance_idx () const
int get_selected_volume_idx () const
void selection_changed ()
void object_list_changed ()
void select_all ()
void deselect_all ()
void remove (size_t obj_idx)
bool delete_object_from_model (size_t obj_idx)
void delete_all_objects_from_model ()
void reset ()
void mirror (Axis axis)
void split_object ()
void split_volume ()
void scale_selection_to_fit_print_volume ()
Slic3r::UndoRedo::Stack & undo_redo_stack ()
Slic3r::UndoRedo::Stack & undo_redo_stack_main ()
void enter_gizmos_stack ()
void leave_gizmos_stack ()
void take_snapshot (const std::string &snapshot_name, UndoRedo::SnapshotType snapshot_type=UndoRedo::SnapshotType::Action)
void take_snapshot (const wxString &snapshot_name, UndoRedo::SnapshotType snapshot_type=UndoRedo::SnapshotType::Action)
int get_active_snapshot_index ()
void undo ()
void redo ()
void undo_redo_to (size_t time_to_load)
void suppress_snapshots ()
void allow_snapshots ()
void process_validation_warning (const std::vector< std::string > &warning) const
bool background_processing_enabled () const
void update_print_volume_state ()
void schedule_background_process ()
unsigned int update_background_process (bool force_validation=false, bool postpone_error_messages=false)
bool restart_background_process (unsigned int state)
unsigned int update_restart_background_process (bool force_scene_update, bool force_preview_update)
void show_delayed_error_message ()
void export_gcode (fs::path output_path, bool output_path_on_removable_media, PrintHostJob upload_job)
void reload_from_disk ()
bool replace_volume_with_stl (int object_idx, int volume_idx, const fs::path &new_path, const wxString &snapshot="")
void replace_with_stl ()
void reload_all_from_disk ()
void set_current_panel (wxPanel *panel)
void on_select_preset (wxCommandEvent &)
void on_slicing_update (SlicingStatusEvent &)
void on_slicing_completed (wxCommandEvent &)
void on_process_completed (SlicingProcessCompletedEvent &)
void on_export_began (wxCommandEvent &)
void on_layer_editing_toggled (bool enable)
void on_slicing_began ()
void clear_warnings ()
void add_warning (const Slic3r::PrintStateBase::Warning &warning, size_t oid)
void actualize_slicing_warnings (const PrintBase &print)
void actualize_object_warnings (const PrintBase &print)
bool warnings_dialog ()
void on_action_add (SimpleEvent &)
void on_action_split_objects (SimpleEvent &)
void on_action_split_volumes (SimpleEvent &)
void on_action_layersediting (SimpleEvent &)
void on_object_select (SimpleEvent &)
void on_right_click (RBtnEvent &)
void on_wipetower_moved (Vec3dEvent &)
void on_wipetower_rotated (Vec3dEvent &)
void on_update_geometry (Vec3dsEvent< 2 > &)
void on_3dcanvas_mouse_dragging_started (SimpleEvent &)
void on_3dcanvas_mouse_dragging_finished (SimpleEvent &)
void show_action_buttons (const bool is_ready_to_slice) const
void set_bed_shape (const Pointfs &shape, const double max_print_height, const std::string &custom_texture, const std::string &custom_model, bool force_as_custom=false)
bool can_delete () const
bool can_delete_all () const
bool can_increase_instances () const
bool can_decrease_instances (int obj_idx=-1) const
bool can_split_to_objects () const
bool can_split_to_volumes () const
bool can_arrange () const
bool can_layers_editing () const
bool can_fix_through_netfabb () const
bool can_simplify () const
bool can_set_instance_to_object () const
bool can_mirror () const
bool can_reload_from_disk () const
bool can_replace_with_stl () const
bool can_split (bool to_objects) const
bool can_scale_to_print_volume () const
void generate_thumbnail (ThumbnailData &data, unsigned int w, unsigned int h, const ThumbnailsParams &thumbnail_params, Camera::EType camera_type)
ThumbnailsList generate_thumbnails (const ThumbnailsParams &params, Camera::EType camera_type)
void bring_instance_forward () const
wxString get_project_filename (const wxString &extension=wxEmptyString) const
void set_project_filename (const wxString &filename)
void init_notification_manager ()
bool inside_snapshot_capture ()
Public Attributes
Plater * q
MainFrame * main_frame
MenuFactory menus
Slic3r::DynamicPrintConfig * config
Slic3r::Print fff_print
Slic3r::SLAPrint sla_print
Slic3r::Model model
PrinterTechnology printer_technology = ptFFF
Slic3r::GCodeProcessorResult gcode_result
wxSizer * panel_sizer { nullptr }
wxPanel * current_panel { nullptr }
std::vector< wxPanel * > panels
Sidebar * sidebar
Bed3D bed
Camera camera
Mouse3DController mouse3d_controller
View3D * view3D
GLToolbar view_toolbar
GLToolbar collapse_toolbar
Preview * preview
std::unique_ptr< NotificationManager > notification_manager
ProjectDirtyStateManager dirty_state
BackgroundSlicingProcess background_process
bool suppressed_backround_processing_update { false }
PlaterWorker< BoostThreadWorker > m_worker
SLAImportDialog * m_sla_import_dlg
bool delayed_scene_refresh
std::string delayed_error_message
wxTimer background_process_timer
std::string label_btn_export
std::string label_btn_send
bool show_render_statistic_dialog { false }
bool ready_to_slice = { false }
ExportingStatus exporting_status { NOT_EXPORTING }
std::string last_output_path
std::string last_output_dir_path
bool process_completed_with_error { false }
Static Public Attributes
static const std::regex pattern_bundle
static const std::regex pattern_3mf
static const std::regex pattern_zip_amf
static const std::regex pattern_any_amf
static const std::regex pattern_prusa
static const std::regex pattern_zip
Private Member Functions
bool layers_height_allowed () const
void update_fff_scene ()
void update_sla_scene ()
void undo_redo_to (std::vector< UndoRedo::Snapshot >::const_iterator it_snapshot)
void update_after_undo_redo (const UndoRedo::Snapshot &snapshot, bool temp_snapshot_was_taken=false)
Private Attributes
wxString m_project_filename
Slic3r::UndoRedo::Stack m_undo_redo_stack_main
Slic3r::UndoRedo::Stack m_undo_redo_stack_gizmos
Slic3r::UndoRedo::Stack * m_undo_redo_stack_active = &m_undo_redo_stack_main
int m_prevent_snapshots = 0
std::string m_last_fff_printer_profile_name
std::string m_last_sla_printer_profile_name
std::vector< std::pair< Slic3r::PrintStateBase::Warning, size_t > > current_warnings
bool show_warning_dialog { false }
Detailed Description
Member Enumeration Documentation
UpdateBackgroundProcessReturnState
enum Slic3r::GUI::Plater::priv::UpdateBackgroundProcessReturnState
Enumerator
UPDATE_BACKGROUND_PROCESS_RESTART
UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE
UPDATE_BACKGROUND_PROCESS_INVALID
UPDATE_BACKGROUND_PROCESS_FORCE_RESTART
UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT
{
        // update_background_process() reports, that the Print / SLAPrint was updated in a way,
        // that the background process was invalidated and it needs to be re-run.
        UPDATE_BACKGROUND_PROCESS_RESTART = 1,
        // update_background_process() reports, that the Print / SLAPrint was updated in a way,
        // that a scene needs to be refreshed (you should call _3DScene::reload_scene(canvas3Dwidget, false))
        UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE = 2,
        // update_background_process() reports, that the Print / SLAPrint is invalid, and the error message
        // was sent to the status line.
        UPDATE_BACKGROUND_PROCESS_INVALID = 4,
        // Restart even if the background processing is disabled.
        UPDATE_BACKGROUND_PROCESS_FORCE_RESTART = 8,
        // Restart for G-code (or SLA zip) export or upload.
        UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT = 16,
    };
Constructor & Destructor Documentation
priv()
Slic3r::GUI::Plater::priv::priv (Plater * q, MainFrame * main_frame)
    : q(q)
    , main_frame(main_frame)
    , config(Slic3r::DynamicPrintConfig::new_from_defaults_keys({
        "bed_shape", "bed_custom_texture", "bed_custom_model", "complete_objects", "duplicate_distance", "extruder_clearance_radius", "skirts", "skirt_distance",
        "brim_width", "brim_separation", "brim_type", "variable_layer_height", "nozzle_diameter", "single_extruder_multi_material",
        "wipe_tower", "wipe_tower_x", "wipe_tower_y", "wipe_tower_width", "wipe_tower_rotation_angle", "wipe_tower_brim_width", "wipe_tower_cone_angle", "wipe_tower_extra_spacing", "wipe_tower_extruder",
        "extruder_colour", "filament_colour", "material_colour", "max_print_height", "printer_model", "printer_notes", "printer_technology",
        // These values are necessary to construct SlicingParameters by the Canvas3D variable layer height editor.
        "layer_height", "first_layer_height", "min_layer_height", "max_layer_height",
        "brim_width", "perimeters", "perimeter_extruder", "fill_density", "infill_extruder", "top_solid_layers",
        "support_material", "support_material_extruder", "support_material_interface_extruder",
        "support_material_contact_distance", "support_material_bottom_contact_distance", "raft_layers"
        }))
    , sidebar(new Sidebar(q))
    , notification_manager(std::make_unique<NotificationManager>(q))
    , m_worker{q, std::make_unique<NotificationProgressIndicator>(notification_manager.get()), "ui_worker"}
    , m_sla_import_dlg{new SLAImportDialog{q}}
    , delayed_scene_refresh(false)
    , view_toolbar(GLToolbar::Radio, "View")
    , collapse_toolbar(GLToolbar::Normal, "Collapse")
    , m_project_filename(wxEmptyString)
{
    this->q->SetFont(Slic3r::GUI::wxGetApp().normal_font());
    background_process.set_fff_print(&fff_print);
    background_process.set_sla_print(&sla_print);
    background_process.set_gcode_result(&gcode_result);
    background_process.set_thumbnail_cb([this](const ThumbnailsParams& params) { return this->generate_thumbnails(params, Camera::EType::Ortho); });
    background_process.set_slicing_completed_event(EVT_SLICING_COMPLETED);
    background_process.set_finished_event(EVT_PROCESS_COMPLETED);
  background_process.set_export_began_event(EVT_EXPORT_BEGAN);
    // Default printer technology for default config.
    background_process.select_technology(this->printer_technology);
    // Register progress callback from the Print class to the Plater.
    auto statuscb = [this](const Slic3r::PrintBase::SlicingStatus &status) {
        wxQueueEvent(this->q, new Slic3r::SlicingStatusEvent(EVT_SLICING_UPDATE, 0, status));
    };
    fff_print.set_status_callback(statuscb);
    sla_print.set_status_callback(statuscb);
    this->q->Bind(EVT_SLICING_UPDATE, &priv::on_slicing_update, this);
    view3D = new View3D(q, bed, &model, config, &background_process);
    preview = new Preview(q, bed, &model, config, &background_process, &gcode_result, [this]() { schedule_background_process(); });
#ifdef __APPLE__
    // set default view_toolbar icons size equal to GLGizmosManager::Default_Icons_Size
    view_toolbar.set_icons_size(GLGizmosManager::Default_Icons_Size);
#endif // __APPLE__
    panels.push_back(view3D);
    panels.push_back(preview);
    this->background_process_timer.SetOwner(this->q, 0);
    this->q->Bind(wxEVT_TIMER, [this](wxTimerEvent &evt)
    {
        if (!this->suppressed_backround_processing_update)
            this->update_restart_background_process(false, false);
    });
    update();
    auto *hsizer = new wxBoxSizer(wxHORIZONTAL);
    panel_sizer = new wxBoxSizer(wxHORIZONTAL);
    panel_sizer->Add(view3D, 1, wxEXPAND | wxALL, 0);
    panel_sizer->Add(preview, 1, wxEXPAND | wxALL, 0);
    hsizer->Add(panel_sizer, 1, wxEXPAND | wxALL, 0);
    hsizer->Add(sidebar, 0, wxEXPAND | wxLEFT | wxRIGHT, 0);
    q->SetSizer(hsizer);
    menus.init(q);
    // Events:
    if (wxGetApp().is_editor()) {
        // Preset change event
        sidebar->Bind(wxEVT_COMBOBOX, &priv::on_select_preset, this);
        sidebar->Bind(EVT_OBJ_LIST_OBJECT_SELECT, [this](wxEvent&) { priv::selection_changed(); });
        sidebar->Bind(EVT_SCHEDULE_BACKGROUND_PROCESS, [this](SimpleEvent&) { this->schedule_background_process(); });
        // jump to found option from SearchDialog
        q->Bind(wxCUSTOMEVT_JUMP_TO_OPTION, [this](wxCommandEvent& evt) { sidebar->jump_to_option(evt.GetInt()); });
    }
    wxGLCanvas* view3D_canvas = view3D->get_wxglcanvas();
    if (wxGetApp().is_editor()) {
        // 3DScene events:
        view3D_canvas->Bind(EVT_GLCANVAS_SCHEDULE_BACKGROUND_PROCESS, [this](SimpleEvent&) { this->schedule_background_process(); });
        view3D_canvas->Bind(EVT_GLCANVAS_OBJECT_SELECT, &priv::on_object_select, this);
        view3D_canvas->Bind(EVT_GLCANVAS_RIGHT_CLICK, &priv::on_right_click, this);
        view3D_canvas->Bind(EVT_GLCANVAS_REMOVE_OBJECT, [q](SimpleEvent&) { q->remove_selected(); });
        view3D_canvas->Bind(EVT_GLCANVAS_ARRANGE, [this](SimpleEvent&) { this->q->arrange(); });
        view3D_canvas->Bind(EVT_GLCANVAS_SELECT_ALL, [this](SimpleEvent&) { this->q->select_all(); });
        view3D_canvas->Bind(EVT_GLCANVAS_QUESTION_MARK, [](SimpleEvent&) { wxGetApp().keyboard_shortcuts(); });
        view3D_canvas->Bind(EVT_GLCANVAS_INCREASE_INSTANCES, [this](Event<int>& evt)
            { if (evt.data == 1) this->q->increase_instances(); else if (this->can_decrease_instances()) this->q->decrease_instances(); });
        view3D_canvas->Bind(EVT_GLCANVAS_INSTANCE_MOVED, [this](SimpleEvent&) { update(); });
        view3D_canvas->Bind(EVT_GLCANVAS_FORCE_UPDATE, [this](SimpleEvent&) { update(); });
        view3D_canvas->Bind(EVT_GLCANVAS_WIPETOWER_MOVED, &priv::on_wipetower_moved, this);
        view3D_canvas->Bind(EVT_GLCANVAS_WIPETOWER_ROTATED, &priv::on_wipetower_rotated, this);
        view3D_canvas->Bind(EVT_GLCANVAS_INSTANCE_ROTATED, [this](SimpleEvent&) { update(); });
        view3D_canvas->Bind(EVT_GLCANVAS_RESET_SKEW, [this](SimpleEvent&) { update(); });
        view3D_canvas->Bind(EVT_GLCANVAS_INSTANCE_SCALED, [this](SimpleEvent&) { update(); });
        view3D_canvas->Bind(EVT_GLCANVAS_ENABLE_ACTION_BUTTONS, [this](Event<bool>& evt) { this->sidebar->enable_buttons(evt.data); });
        view3D_canvas->Bind(EVT_GLCANVAS_UPDATE_GEOMETRY, &priv::on_update_geometry, this);
        view3D_canvas->Bind(EVT_GLCANVAS_MOUSE_DRAGGING_STARTED, &priv::on_3dcanvas_mouse_dragging_started, this);
        view3D_canvas->Bind(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED, &priv::on_3dcanvas_mouse_dragging_finished, this);
        view3D_canvas->Bind(EVT_GLCANVAS_TAB, [this](SimpleEvent&) { select_next_view_3D(); });
        view3D_canvas->Bind(EVT_GLCANVAS_RESETGIZMOS, [this](SimpleEvent&) { reset_all_gizmos(); });
        view3D_canvas->Bind(EVT_GLCANVAS_UNDO, [this](SimpleEvent&) { this->undo(); });
        view3D_canvas->Bind(EVT_GLCANVAS_REDO, [this](SimpleEvent&) { this->redo(); });
        view3D_canvas->Bind(EVT_GLCANVAS_COLLAPSE_SIDEBAR, [this](SimpleEvent&) { this->q->collapse_sidebar(!this->q->is_sidebar_collapsed());  });
        view3D_canvas->Bind(EVT_GLCANVAS_RESET_LAYER_HEIGHT_PROFILE, [this](SimpleEvent&) { this->view3D->get_canvas3d()->reset_layer_height_profile(); });
        view3D_canvas->Bind(EVT_GLCANVAS_ADAPTIVE_LAYER_HEIGHT_PROFILE, [this](Event<float>& evt) { this->view3D->get_canvas3d()->adaptive_layer_height_profile(evt.data); });
        view3D_canvas->Bind(EVT_GLCANVAS_SMOOTH_LAYER_HEIGHT_PROFILE, [this](HeightProfileSmoothEvent& evt) { this->view3D->get_canvas3d()->smooth_layer_height_profile(evt.data); });
        view3D_canvas->Bind(EVT_GLCANVAS_RELOAD_FROM_DISK, [this](SimpleEvent&) { this->reload_all_from_disk(); });
        // 3DScene/Toolbar:
        view3D_canvas->Bind(EVT_GLTOOLBAR_ADD, &priv::on_action_add, this);
        view3D_canvas->Bind(EVT_GLTOOLBAR_DELETE, [q](SimpleEvent&) { q->remove_selected(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_DELETE_ALL, [this](SimpleEvent&) { delete_all_objects_from_model(); });
//        view3D_canvas->Bind(EVT_GLTOOLBAR_DELETE_ALL, [q](SimpleEvent&) { q->reset_with_confirm(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_ARRANGE, [this](SimpleEvent&) { this->q->arrange(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_COPY, [q](SimpleEvent&) { q->copy_selection_to_clipboard(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_PASTE, [q](SimpleEvent&) { q->paste_from_clipboard(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_MORE, [q](SimpleEvent&) { q->increase_instances(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_FEWER, [q](SimpleEvent&) { q->decrease_instances(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_SPLIT_OBJECTS, &priv::on_action_split_objects, this);
        view3D_canvas->Bind(EVT_GLTOOLBAR_SPLIT_VOLUMES, &priv::on_action_split_volumes, this);
        view3D_canvas->Bind(EVT_GLTOOLBAR_LAYERSEDITING, &priv::on_action_layersediting, this);
    }
    view3D_canvas->Bind(EVT_GLCANVAS_UPDATE_BED_SHAPE, [q](SimpleEvent&) { q->set_bed_shape(); });
    // Preview events:
    preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_QUESTION_MARK, [](SimpleEvent&) { wxGetApp().keyboard_shortcuts(); });
    preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_UPDATE_BED_SHAPE, [q](SimpleEvent&) { q->set_bed_shape(); });
    if (wxGetApp().is_editor()) {
        preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_TAB, [this](SimpleEvent&) { select_next_view_3D(); });
        preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_COLLAPSE_SIDEBAR, [this](SimpleEvent&) { this->q->collapse_sidebar(!this->q->is_sidebar_collapsed());  });
    }
    preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_JUMP_TO, [this](wxKeyEvent& evt) { preview->jump_layers_slider(evt); });
    preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_MOVE_SLIDERS, [this](wxKeyEvent& evt) {
        preview->move_layers_slider(evt);
        preview->move_moves_slider(evt);
        });
    preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_EDIT_COLOR_CHANGE, [this](wxKeyEvent& evt) { preview->edit_layers_slider(evt); });
    if (wxGetApp().is_gcode_viewer())
        preview->Bind(EVT_GLCANVAS_RELOAD_FROM_DISK, [this](SimpleEvent&) { this->q->reload_gcode_from_disk(); });
    if (wxGetApp().is_editor()) {
        q->Bind(EVT_SLICING_COMPLETED, &priv::on_slicing_completed, this);
        q->Bind(EVT_PROCESS_COMPLETED, &priv::on_process_completed, this);
        q->Bind(EVT_EXPORT_BEGAN, &priv::on_export_began, this);
        q->Bind(EVT_GLVIEWTOOLBAR_3D, [q](SimpleEvent&) { q->select_view_3D("3D"); });
        q->Bind(EVT_GLVIEWTOOLBAR_PREVIEW, [q](SimpleEvent&) { q->select_view_3D("Preview"); });
    }
    // Drop target:
    main_frame->SetDropTarget(new PlaterDropTarget(*main_frame, *q));   // if my understanding is right, wxWindow takes the owenership
    q->Layout();
    set_current_panel(wxGetApp().is_editor() ? static_cast<wxPanel*>(view3D) : static_cast<wxPanel*>(preview));
    if (wxGetApp().is_gcode_viewer())
        preview->hide_layers_slider();
    // updates camera type from .ini file
    camera.enable_update_config_on_type_change(true);
    camera.set_type(wxGetApp().app_config->get("use_perspective_camera"));
    // Load the 3DConnexion device database.
    mouse3d_controller.load_config(*wxGetApp().app_config);
  // Start the background thread to detect and connect to a HID device (Windows and Linux).
  // Connect to a 3DConnextion driver (OSX).
    mouse3d_controller.init();
#ifdef _WIN32
    // Register an USB HID (Human Interface Device) attach event. evt contains Win32 path to the USB device containing VID, PID and other info.
    // This event wakes up the Mouse3DController's background thread to enumerate HID devices, if the VID of the callback event
    // is one of the 3D Mouse vendors (3DConnexion or Logitech).
    this->q->Bind(EVT_HID_DEVICE_ATTACHED, [this](HIDDeviceAttachedEvent &evt) {
      mouse3d_controller.device_attached(evt.data);
        });
    this->q->Bind(EVT_HID_DEVICE_DETACHED, [this](HIDDeviceAttachedEvent& evt) {
        mouse3d_controller.device_detached(evt.data);
        });
#endif /* _WIN32 */
  //notification_manager = new NotificationManager(this->q);
    if (wxGetApp().is_editor()) {
        this->q->Bind(EVT_EJECT_DRIVE_NOTIFICAION_CLICKED, [this](EjectDriveNotificationClickedEvent&) { this->q->eject_drive(); });
        this->q->Bind(EVT_EXPORT_GCODE_NOTIFICAION_CLICKED, [this](ExportGcodeNotificationClickedEvent&) { this->q->export_gcode(true); });
        this->q->Bind(EVT_PRESET_UPDATE_AVAILABLE_CLICKED, [](PresetUpdateAvailableClickedEvent&) {  wxGetApp().get_preset_updater()->on_update_notification_confirm(); });
        this->q->Bind(EVT_REMOVABLE_DRIVE_EJECTED, [this, q](RemovableDriveEjectEvent &evt) {
        if (evt.data.second) {
          q->show_action_buttons();
                notification_manager->close_notification_of_type(NotificationType::ExportFinished);
                notification_manager->push_notification(NotificationType::CustomNotification,
                                                        NotificationManager::NotificationLevel::RegularNotificationLevel,
                                                        format(_L("Successfully unmounted. The device %s(%s) can now be safely removed from the computer."), evt.data.first.name, evt.data.first.path)
                    );
            } else {
                notification_manager->close_notification_of_type(NotificationType::ExportFinished);
                notification_manager->push_notification(NotificationType::CustomNotification,
                                                        NotificationManager::NotificationLevel::ErrorNotificationLevel,
                                                        format(_L("Ejecting of device %s(%s) has failed."), evt.data.first.name, evt.data.first.path)
                    );
            }
      });
        this->q->Bind(EVT_REMOVABLE_DRIVES_CHANGED, [this, q](RemovableDrivesChangedEvent &) {
        q->show_action_buttons();
        // Close notification ExportingFinished but only if last export was to removable
        notification_manager->device_ejected();
      });
        // Start the background thread and register this window as a target for update events.
        wxGetApp().removable_drive_manager()->init(this->q);
#ifdef _WIN32
        // Trigger enumeration of removable media on Win32 notification.
        this->q->Bind(EVT_VOLUME_ATTACHED, [this](VolumeAttachedEvent &evt) { wxGetApp().removable_drive_manager()->volumes_changed(); });
        this->q->Bind(EVT_VOLUME_DETACHED, [this](VolumeDetachedEvent &evt) { wxGetApp().removable_drive_manager()->volumes_changed(); });
#endif /* _WIN32 */
    }
    // Initialize the Undo / Redo stack with a first snapshot.
    this->take_snapshot(_L("New Project"), UndoRedo::SnapshotType::ProjectSeparator);
    // Reset the "dirty project" flag.
    m_undo_redo_stack_main.mark_current_as_saved();
    dirty_state.update_from_undo_redo_stack(false);
    this->q->Bind(EVT_LOAD_MODEL_OTHER_INSTANCE, [this](LoadFromOtherInstanceEvent& evt) {
        BOOST_LOG_TRIVIAL(trace) << "Received load from other instance event.";
        wxArrayString input_files;
        for (size_t i = 0; i < evt.data.size(); ++i) {
            input_files.push_back(from_u8(evt.data[i].string()));
        }
        wxGetApp().mainframe->Raise();
        this->q->load_files(input_files);
    });
    this->q->Bind(EVT_START_DOWNLOAD_OTHER_INSTANCE, [](StartDownloadOtherInstanceEvent& evt) {
        BOOST_LOG_TRIVIAL(trace) << "Received url from other instance event.";
        wxGetApp().mainframe->Raise();
        for (size_t i = 0; i < evt.data.size(); ++i) {
            wxGetApp().start_download(evt.data[i]);
        }
    });
    this->q->Bind(EVT_INSTANCE_GO_TO_FRONT, [this](InstanceGoToFrontEvent &) {
        bring_instance_forward();
    });
  wxGetApp().other_instance_message_handler()->init(this->q);
    // collapse sidebar according to saved value
    if (wxGetApp().is_editor()) {
        bool is_collapsed = get_config_bool("collapsed_sidebar");
        sidebar->collapse(is_collapsed);
    }
 }
~priv()
Slic3r::GUI::Plater::priv::~priv ()
{
    if (config != nullptr)
        delete config;
    // Saves the database of visited (already shown) hints into hints.ini.
    notification_manager->deactivate_loaded_hints();
}
References Slic3r::GUI::Plater::config().
Member Function Documentation
actualize_object_warnings()
void Slic3r::GUI::Plater::priv::actualize_object_warnings (const PrintBase & print)
{
    std::vector<ObjectID> ids;
    for (const ModelObject* object : print.model().objects )
    {
        ids.push_back(object->id());
    }
    std::sort(ids.begin(), ids.end());
    notification_manager->remove_simplify_suggestion_of_released_objects(ids);
}
References Slic3r::PrintBase::model(), and Slic3r::Model::objects.
actualize_slicing_warnings()
void Slic3r::GUI::Plater::priv::actualize_slicing_warnings (const PrintBase & print)
{
    std::vector<ObjectID> ids = print.print_object_ids();
    if (ids.empty()) {
        clear_warnings();
        return;
    }
    ids.emplace_back(print.id());
    std::sort(ids.begin(), ids.end());
  notification_manager->remove_slicing_warnings_of_released_objects(ids);
    notification_manager->set_all_slicing_warnings_gray(true);
}
References Slic3r::ObjectBase::id(), and Slic3r::PrintBase::print_object_ids().
add_warning()
void Slic3r::GUI::Plater::priv::add_warning (const Slic3r::PrintStateBase::Warning & warning, size_t oid)
{
  for (auto const& it : current_warnings) {
    if (warning.message_id == it.first.message_id) {
      if (warning.message_id != 0 || (warning.message_id == 0 && warning.message == it.first.message))
        return;
    }
  }
  current_warnings.emplace_back(std::pair<Slic3r::PrintStateBase::Warning, size_t>(warning, oid));
}
References Slic3r::PrintStateBase::Warning::message, and Slic3r::PrintStateBase::Warning::message_id.
allow_snapshots()
void Slic3r::GUI::Plater::priv::allow_snapshots () inline
{ m_prevent_snapshots--; }
apply_free_camera_correction()
void Slic3r::GUI::Plater::priv::apply_free_camera_correction (bool apply = true)
{
    camera.set_type(wxGetApp().app_config->get("use_perspective_camera"));
    if (apply && !wxGetApp().app_config->get_bool("use_free_camera"))
        camera.recover_from_free_camera();
}
are_view3D_labels_shown()
bool Slic3r::GUI::Plater::priv::are_view3D_labels_shown () const inline
{ return (current_panel == view3D) && view3D->get_canvas3d()->are_labels_shown(); }
References Slic3r::GUI::GLCanvas3D::are_labels_shown(), and Slic3r::GUI::View3D::get_canvas3d().
background_processing_enabled()
bool Slic3r::GUI::Plater::priv::background_processing_enabled () const inline
{ return this->get_config_bool("background_processing"); }
bring_instance_forward()
void Slic3r::GUI::Plater::priv::bring_instance_forward () const
{
#ifdef __APPLE__
    wxGetApp().other_instance_message_handler()->bring_instance_forward();
    return;
#endif //__APPLE__
    if (main_frame == nullptr) {
        BOOST_LOG_TRIVIAL(debug) << "Couldnt bring instance forward - mainframe is null";
        return;
    }
    BOOST_LOG_TRIVIAL(debug) << "prusaslicer window going forward";
    //this code maximize app window on Fedora
    {
        main_frame->Iconize(false);
        if (main_frame->IsMaximized())
            main_frame->Maximize(true);
        else
            main_frame->Maximize(false);
    }
    //this code maximize window on Ubuntu
    {
        main_frame->Restore();
        wxGetApp().GetTopWindow()->SetFocus();  // focus on my window
        wxGetApp().GetTopWindow()->Raise();  // bring window to front
        wxGetApp().GetTopWindow()->Show(true); // show the window
    }
}
can_arrange()
bool Slic3r::GUI::Plater::priv::can_arrange () const
{
    if (model.objects.empty() || !m_worker.is_idle()) return false;
    return q->canvas3D()->get_gizmos_manager().get_current_type() == GLGizmosManager::Undefined;
}
References Slic3r::GUI::Plater::model(), Slic3r::Model::objects, and Slic3r::GUI::GLGizmosManager::Undefined.
can_decrease_instances()
bool Slic3r::GUI::Plater::priv::can_decrease_instances (int obj_idx = -1) const
{
    if (!m_worker.is_idle()
     || q->canvas3D()->get_gizmos_manager().is_in_editing_mode())
            return false;
    if (obj_idx < 0)
        obj_idx = get_selected_object_idx();
    if (obj_idx < 0) {
        if (const auto obj_ids = get_selection().get_object_idxs(); !obj_ids.empty())
            for (const size_t obj_id : obj_ids)
                if (can_decrease_instances(obj_id))
                    return true;
        return false;
    }
    return  obj_idx < (int)model.objects.size() &&
            (model.objects[obj_idx]->instances.size() > 1) &&
            !sidebar->obj_list()->has_selected_cut_object();
}
References Slic3r::GUI::Plater::can_decrease_instances(), Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, and Slic3r::GUI::Plater::sidebar().
can_delete()
bool Slic3r::GUI::Plater::priv::can_delete () const
{
    return !get_selection().is_empty() && !get_selection().is_wipe_tower() && !sidebar->obj_list()->is_editing();
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::ObjectList::is_editing(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::Selection::is_wipe_tower(), Slic3r::GUI::Sidebar::obj_list(), and Slic3r::GUI::Plater::sidebar().
can_delete_all()
bool Slic3r::GUI::Plater::priv::can_delete_all () const
{
    return !model.objects.empty() && !sidebar->obj_list()->is_editing();
}
References Slic3r::GUI::ObjectList::is_editing(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, and Slic3r::GUI::Plater::sidebar().
can_fix_through_netfabb()
bool Slic3r::GUI::Plater::priv::can_fix_through_netfabb () const
{
    std::vector<int> obj_idxs, vol_idxs;
    sidebar->obj_list()->get_selection_indexes(obj_idxs, vol_idxs);
#if FIX_THROUGH_NETFABB_ALWAYS
    // Fixing always.
    return ! obj_idxs.empty() || ! vol_idxs.empty();
#else // FIX_THROUGH_NETFABB_ALWAYS
    // Fixing only if the model is not manifold.
    if (vol_idxs.empty()) {
        for (auto obj_idx : obj_idxs)
            if (model.objects[obj_idx]->get_repaired_errors_count() > 0)
                return true;
        return false;
    }
    int obj_idx = obj_idxs.front();
    for (auto vol_idx : vol_idxs)
        if (model.objects[obj_idx]->get_repaired_errors_count(vol_idx) > 0)
            return true;
    return false;
#endif // FIX_THROUGH_NETFABB_ALWAYS
}
References Slic3r::GUI::ObjectList::get_selection_indexes(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, and Slic3r::GUI::Plater::sidebar().
can_increase_instances()
bool Slic3r::GUI::Plater::priv::can_increase_instances () const
{
    if (!m_worker.is_idle()
     || q->canvas3D()->get_gizmos_manager().is_in_editing_mode())
            return false;
    // Disallow arrange and add instance when emboss gizmo is opend
    // Prevent strobo effect during editing emboss parameters.
    if (q->canvas3D()->get_gizmos_manager().get_current_type() == GLGizmosManager::Emboss) return false;
    const auto obj_idxs = get_selection().get_object_idxs();
    return !obj_idxs.empty() && !get_selection().is_wipe_tower() && !sidebar->obj_list()->has_selected_cut_object();
}
References Slic3r::GUI::GLGizmosManager::Emboss, Slic3r::GUI::Selection::get_object_idxs(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::Selection::is_wipe_tower(), Slic3r::GUI::Sidebar::obj_list(), and Slic3r::GUI::Plater::sidebar().
can_layers_editing()
bool Slic3r::GUI::Plater::priv::can_layers_editing () const
{
    return layers_height_allowed();
}
can_mirror()
bool Slic3r::GUI::Plater::priv::can_mirror () const
{
    return !sidebar->obj_list()->has_selected_cut_object();
}
References Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::Sidebar::obj_list(), and Slic3r::GUI::Plater::sidebar().
can_reload_from_disk()
bool Slic3r::GUI::Plater::priv::can_reload_from_disk () const
{
    if (sidebar->obj_list()->has_selected_cut_object())
        return false;
    // collect selected reloadable ModelVolumes
    std::vector<std::pair<int, int>> selected_volumes = reloadable_volumes(model, get_selection());
    // nothing to reload, return
    if (selected_volumes.empty())
        return false;
    std::sort(selected_volumes.begin(), selected_volumes.end(), [](const std::pair<int, int>& v1, const std::pair<int, int>& v2) {
        return (v1.first < v2.first) || (v1.first == v2.first && v1.second < v2.second);
        });
    selected_volumes.erase(std::unique(selected_volumes.begin(), selected_volumes.end(), [](const std::pair<int, int>& v1, const std::pair<int, int>& v2) {
        return (v1.first == v2.first) && (v1.second == v2.second); }), selected_volumes.end());
    // collects paths of files to load
    std::vector<fs::path> paths;
    for (auto [obj_idx, vol_idx] : selected_volumes) {
        paths.push_back(model.objects[obj_idx]->volumes[vol_idx]->source.input_file);
    }
    std::sort(paths.begin(), paths.end());
    paths.erase(std::unique(paths.begin(), paths.end()), paths.end());
    return !paths.empty();
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, Slic3r::GUI::reloadable_volumes(), and Slic3r::GUI::Plater::sidebar().
can_replace_with_stl()
bool Slic3r::GUI::Plater::priv::can_replace_with_stl () const
{
    return !sidebar->obj_list()->has_selected_cut_object() && get_selection().get_volume_idxs().size() == 1;
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::Sidebar::obj_list(), and Slic3r::GUI::Plater::sidebar().
can_scale_to_print_volume()
bool Slic3r::GUI::Plater::priv::can_scale_to_print_volume () const
{
    const BuildVolume::Type type = this->bed.build_volume().type();
    return  !sidebar->obj_list()->has_selected_cut_object() &&
            !view3D->get_canvas3d()->get_selection().is_empty() && (type == BuildVolume::Type::Rectangle || type == BuildVolume::Type::Circle);
}
References Slic3r::BuildVolume::Circle, Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::BuildVolume::Rectangle, and Slic3r::GUI::Plater::sidebar().
can_set_instance_to_object()
bool Slic3r::GUI::Plater::priv::can_set_instance_to_object () const
{
    const int obj_idx = get_selected_object_idx();
    return 0 <= obj_idx && obj_idx < (int)model.objects.size() && model.objects[obj_idx]->instances.size() > 1;
}
References Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
can_simplify()
bool Slic3r::GUI::Plater::priv::can_simplify () const
{
    const int obj_idx = get_selected_object_idx();
    // is object for simplification selected
    // cut object can't be simplify
    if (obj_idx < 0 || model.objects[obj_idx]->is_cut())
        return false;
    // is already opened?
    if (q->canvas3D()->get_gizmos_manager().get_current_type() ==
        GLGizmosManager::EType::Simplify)
        return false;
    return true;
}
References Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, and Slic3r::GUI::GLGizmosManager::Simplify.
can_split()
bool Slic3r::GUI::Plater::priv::can_split (bool to_objects) const
{
    return sidebar->obj_list()->is_splittable(to_objects);
}
References Slic3r::GUI::ObjectList::is_splittable(), Slic3r::GUI::Sidebar::obj_list(), and Slic3r::GUI::Plater::sidebar().
can_split_to_objects()
bool Slic3r::GUI::Plater::priv::can_split_to_objects () const
{
    return q->can_split(true);
}
can_split_to_volumes()
bool Slic3r::GUI::Plater::priv::can_split_to_volumes () const
{
    return q->can_split(false);
}
clear_warnings()
void Slic3r::GUI::Plater::priv::clear_warnings ()
{
  notification_manager->close_slicing_errors_and_warnings();
  this->current_warnings.clear();
}
collapse_sidebar()
void Slic3r::GUI::Plater::priv::collapse_sidebar (bool collapse)
{
    sidebar->collapse(collapse);
    // Now update the tooltip in the toolbar.
    std::string new_tooltip = collapse
                              ? _u8L("Expand sidebar")
                              : _u8L("Collapse sidebar");
    new_tooltip += " [Shift+Tab]";
    int id = collapse_toolbar.get_item_id("collapse_sidebar");
    collapse_toolbar.set_tooltip(id, new_tooltip);
    notification_manager->set_sidebar_collapsed(collapse);
}
References _u8L, Slic3r::GUI::Sidebar::collapse(), and Slic3r::GUI::Plater::sidebar().
delete_all_objects_from_model()
void Slic3r::GUI::Plater::priv::delete_all_objects_from_model ()
{
    Plater::TakeSnapshot snapshot(q, _L("Delete All Objects"));
    if (view3D->is_layers_editing_enabled())
        view3D->enable_layers_editing(false);
    reset_gcode_toolpaths();
    gcode_result.reset();
    view3D->get_canvas3d()->reset_sequential_print_clearance();
    view3D->get_canvas3d()->reset_all_gizmos();
    m_worker.cancel_all();
    // Stop and reset the Print content.
    background_process.reset();
    model.clear_objects();
    update();
    // Delete object from Sidebar list. Do it after update, so that the GLScene selection is updated with the modified model.
    sidebar->obj_list()->delete_all_objects_from_list();
    object_list_changed();
    // The hiding of the slicing results, if shown, is not taken care by the background process, so we do it here
    sidebar->show_sliced_info_sizer(false);
    model.custom_gcode_per_print_z.gcodes.clear();
}
References _L, Slic3r::Model::clear_objects(), Slic3r::Model::custom_gcode_per_print_z, Slic3r::GUI::ObjectList::delete_all_objects_from_list(), Slic3r::CustomGCode::Info::gcodes, Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::reset_gcode_toolpaths(), Slic3r::GUI::Sidebar::show_sliced_info_sizer(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Plater::update().
delete_object_from_model()
bool Slic3r::GUI::Plater::priv::delete_object_from_model (size_t obj_idx)
{
    // check if object isn't cut
    // show warning message that "cut consistancy" will not be supported any more
    ModelObject* obj = model.objects[obj_idx];
    if (obj->is_cut()) {
        InfoDialog dialog(q, _L("Delete object which is a part of cut object"),
                             _L("You try to delete an object which is a part of a cut object.") + "\n" +
                                _L("This action will break a cut information.\n"
                                "After that PrusaSlicer can't guarantee model consistency"),
                                false, wxYES | wxCANCEL | wxCANCEL_DEFAULT | wxICON_WARNING);
        dialog.SetButtonLabel(wxID_YES, _L("Delete object"));
        if (dialog.ShowModal() == wxID_CANCEL)
            return false;
    }
    wxString snapshot_label = _L("Delete Object");
    if (!obj->name.empty())
        snapshot_label += ": " + wxString::FromUTF8(obj->name.c_str());
    Plater::TakeSnapshot snapshot(q, snapshot_label);
    m_worker.cancel_all();
    if (obj->is_cut())
        sidebar->obj_list()->invalidate_cut_info_for_object(obj_idx);
    model.delete_object(obj_idx);
    update();
    object_list_changed();
    return true;
}
References _L, Slic3r::Model::delete_object(), Slic3r::GUI::ObjectList::invalidate_cut_info_for_object(), Slic3r::ModelObject::is_cut(), Slic3r::GUI::Plater::model(), Slic3r::ModelObject::name, Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, Slic3r::GUI::MsgDialog::SetButtonLabel(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Plater::update().
deselect_all()
void Slic3r::GUI::Plater::priv::deselect_all ()
{
    view3D->deselect_all();
}
enable_preview_moves_slider()
void Slic3r::GUI::Plater::priv::enable_preview_moves_slider (bool enable)
{
    preview->enable_moves_slider(enable);
}
enter_gizmos_stack()
void Slic3r::GUI::Plater::priv::enter_gizmos_stack ()
{
    assert(m_undo_redo_stack_active == &m_undo_redo_stack_main);
    if (m_undo_redo_stack_active == &m_undo_redo_stack_main) {
        m_undo_redo_stack_active = &m_undo_redo_stack_gizmos;
        assert(m_undo_redo_stack_active->empty());
        // Take the initial snapshot of the gizmos.
        // Not localized on purpose, the text will never be shown to the user.
        this->take_snapshot(std::string("Gizmos-Initial"));
    }
}
References Slic3r::GUI::Plater::take_snapshot().
export_gcode()
void Slic3r::GUI::Plater::priv::export_gcode (fs::path output_path, bool output_path_on_removable_media, PrintHostJob upload_job)
{
    wxCHECK_RET(!(output_path.empty() && upload_job.empty()), "export_gcode: output_path and upload_job empty");
    if (model.objects.empty())
        return;
    if (background_process.is_export_scheduled()) {
        GUI::show_error(q, _L("Another export job is currently running."));
        return;
    }
    // bitmask of UpdateBackgroundProcessReturnState
    unsigned int state = update_background_process(true);
    if (state & priv::UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE)
        view3D->reload_scene(false);
    if ((state & priv::UPDATE_BACKGROUND_PROCESS_INVALID) != 0)
        return;
    show_warning_dialog = true;
    if (! output_path.empty()) {
        background_process.schedule_export(output_path.string(), output_path_on_removable_media);
        notification_manager->push_delayed_notification(NotificationType::ExportOngoing, []() {return true; }, 1000, 0);
    } else {
        background_process.schedule_upload(std::move(upload_job));
    }
    // If the SLA processing of just a single object's supports is running, restart slicing for the whole object.
    this->background_process.set_task(PrintBase::TaskParams());
    this->restart_background_process(priv::UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT);
}
References _L, Slic3r::PrintHostJob::empty(), Slic3r::GUI::ExportOngoing, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::show_error(), UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT, UPDATE_BACKGROUND_PROCESS_INVALID, and UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE.
generate_thumbnail()
void Slic3r::GUI::Plater::priv::generate_thumbnail (ThumbnailData & data, unsigned int w, unsigned int h, const ThumbnailsParams & thumbnail_params, Camera::EType camera_type)
{
    view3D->get_canvas3d()->render_thumbnail(data, w, h, thumbnail_params, camera_type);
}
generate_thumbnails()
ThumbnailsList Slic3r::GUI::Plater::priv::generate_thumbnails (const ThumbnailsParams & params, Camera::EType camera_type)
{
    ThumbnailsList thumbnails;
    for (const Vec2d& size : params.sizes) {
        thumbnails.push_back(ThumbnailData());
        Point isize(size); // round to ints
        generate_thumbnail(thumbnails.back(), isize.x(), isize.y(), params, camera_type);
        if (!thumbnails.back().is_valid())
            thumbnails.pop_back();
    }
    return thumbnails;
}
References Slic3r::ThumbnailsParams::sizes.
get_active_snapshot_index()
int Slic3r::GUI::Plater::priv::get_active_snapshot_index ()
{
    const size_t active_snapshot_time = this->undo_redo_stack().active_snapshot_time();
    const std::vector<UndoRedo::Snapshot>& ss_stack = this->undo_redo_stack().snapshots();
    const auto it = std::lower_bound(ss_stack.begin(), ss_stack.end(), UndoRedo::Snapshot(active_snapshot_time));
    return it - ss_stack.begin();
}
get_config_bool()
bool Slic3r::GUI::Plater::priv::get_config_bool (const std::string & key) const
{
    return wxGetApp().app_config->get_bool(key);
}
Referenced by reload_from_disk().
get_current_canvas3D()
GLCanvas3D * Slic3r::GUI::Plater::priv::get_current_canvas3D ()
{
    return (current_panel == view3D) ? view3D->get_canvas3d() : ((current_panel == preview) ? preview->get_canvas3d() : nullptr);
}
get_export_file()
wxString Slic3r::GUI::Plater::priv::get_export_file (GUI::FileType file_type)
{
    wxString wildcard;
    switch (file_type) {
        case FT_STL:
        case FT_AMF:
        case FT_3MF:
        case FT_GCODE:
        case FT_OBJ:
        case FT_OBJECT:
            wildcard = file_wildcards(file_type);
        break;
        default:
            wildcard = file_wildcards(FT_MODEL);
        break;
    }
    fs::path output_file = get_export_file_path(file_type);
    wxString dlg_title;
    switch (file_type) {
        case FT_STL:
        {
            output_file.replace_extension("stl");
            dlg_title = _L("Export STL file:");
            break;
        }
        case FT_AMF:
        {
            // XXX: Problem on OS X with double extension?
            output_file.replace_extension("zip.amf");
            dlg_title = _L("Export AMF file:");
            break;
        }
        case FT_3MF:
        {
            output_file.replace_extension("3mf");
            dlg_title = _L("Save file as:");
            break;
        }
        case FT_OBJ:
        {
            output_file.replace_extension("obj");
            dlg_title = _L("Export OBJ file:");
            break;
        }
        default: break;
    }
    std::string out_dir = (boost::filesystem::path(output_file).parent_path()).string();
    std::string temp_dir = wxStandardPaths::Get().GetTempDir().utf8_str().data();
    wxFileDialog dlg(q, dlg_title,
        out_dir == temp_dir ? from_u8(wxGetApp().app_config->get("last_output_path"))  : (is_shapes_dir(out_dir) ? from_u8(wxGetApp().app_config->get_last_dir()) : from_path(output_file.parent_path())), from_path(output_file.filename()),
        wildcard, wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
    if (dlg.ShowModal() != wxID_OK)
        return wxEmptyString;
    wxString out_path = dlg.GetPath();
    fs::path path(into_path(out_path));
    wxGetApp().app_config->update_last_output_dir(path.parent_path().string());
    return out_path;
}
References _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::from_path(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_3MF, Slic3r::GUI::FT_AMF, Slic3r::GUI::FT_GCODE, Slic3r::GUI::FT_MODEL, Slic3r::GUI::FT_OBJ, Slic3r::GUI::FT_OBJECT, Slic3r::GUI::FT_STL, Slic3r::GUI::into_path(), and Slic3r::is_shapes_dir().
get_export_file_path()
fs::path Slic3r::GUI::Plater::priv::get_export_file_path (GUI::FileType file_type)
{
    // Update printbility state of each of the ModelInstances.
    this->update_print_volume_state();
    const Selection& selection = get_selection();
    int obj_idx = selection.get_object_idx();
    fs::path output_file;
    if (file_type == FT_3MF)
        // for 3mf take the path from the project filename, if any
        output_file = into_path(get_project_filename(".3mf"));
    if (output_file.empty())
    {
        // first try to get the file name from the current selection
        if ((0 <= obj_idx) && (obj_idx < (int)this->model.objects.size()))
            output_file = this->model.objects[obj_idx]->get_export_filename();
        if (output_file.empty())
            // Find the file name of the first printable object.
            output_file = this->model.propose_export_file_name_and_path();
        if (output_file.empty() && !model.objects.empty())
            // Find the file name of the first object.
            output_file = this->model.objects[0]->get_export_filename();
        if (output_file.empty())
            // Use _L("Untitled") name
            output_file = into_path(_L("Untitled"));
    }
    return output_file;
}
References _L, Slic3r::GUI::FT_3MF, Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::Plater::get_project_filename(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::into_path(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, and Slic3r::Model::propose_export_file_name_and_path().
get_project_filename()
wxString Slic3r::GUI::Plater::priv::get_project_filename (const wxString & extension = wxEmptyString) const
{
    return m_project_filename.empty() ? "" : m_project_filename + extension;
}
get_selected_instance_idx()
int Slic3r::GUI::Plater::priv::get_selected_instance_idx () const
{
    const int obj_idx = get_selected_object_idx();
    if (obj_idx >= 0) {
        const int inst_idx = get_selection().get_instance_idx();
        return (0 <= inst_idx && inst_idx < int(model.objects[obj_idx]->instances.size())) ? inst_idx : -1;
    }
    else
        return -1;
}
References Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
get_selected_object_idx()
int Slic3r::GUI::Plater::priv::get_selected_object_idx () const
{
    const int idx = get_selection().get_object_idx();
    return (0 <= idx && idx < int(model.objects.size())) ? idx : -1;
}
References Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
get_selected_volume_idx()
int Slic3r::GUI::Plater::priv::get_selected_volume_idx () const
{
    auto& selection = get_selection();
    const int idx = selection.get_object_idx();
    if (idx < 0 || int(model.objects.size()) <= idx)
        return-1;
    const GLVolume* v = selection.get_first_volume();
    if (model.objects[idx]->volumes.size() > 1)
        return v->volume_idx();
    return -1;
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, and Slic3r::GLVolume::volume_idx().
get_selection() [1/2]
Selection & Slic3r::GUI::Plater::priv::get_selection ()
{
    return view3D->get_canvas3d()->get_selection();
}
get_selection() [2/2]
const Selection & Slic3r::GUI::Plater::priv::get_selection () const
{
    return view3D->get_canvas3d()->get_selection();
}
Referenced by reload_from_disk().
init_collapse_toolbar()
bool Slic3r::GUI::Plater::priv::init_collapse_toolbar ()
{
    if (wxGetApp().is_gcode_viewer())
        return true;
    if (collapse_toolbar.get_items_count() > 0)
        // already initialized
        return true;
    BackgroundTexture::Metadata background_data;
    background_data.filename = "toolbar_background.png";
    background_data.left = 16;
    background_data.top = 16;
    background_data.right = 16;
    background_data.bottom = 16;
    if (!collapse_toolbar.init(background_data))
        return false;
    collapse_toolbar.set_layout_type(GLToolbar::Layout::Vertical);
    collapse_toolbar.set_horizontal_orientation(GLToolbar::Layout::HO_Right);
    collapse_toolbar.set_vertical_orientation(GLToolbar::Layout::VO_Top);
    collapse_toolbar.set_border(5.0f);
    collapse_toolbar.set_separator_size(5);
    collapse_toolbar.set_gap_size(2);
    GLToolbarItem::Data item;
    item.name = "collapse_sidebar";
    item.icon_filename = "collapse.svg";
    item.sprite_id = 0;
    item.left.action_callback = []() {
        wxGetApp().plater()->collapse_sidebar(!wxGetApp().plater()->is_sidebar_collapsed());
    };
    if (!collapse_toolbar.add_item(item))
        return false;
    // Now "collapse" sidebar to current state. This is done so the tooltip
    // is updated before the toolbar is first used.
    wxGetApp().plater()->collapse_sidebar(wxGetApp().plater()->is_sidebar_collapsed());
    return true;
}
References Slic3r::GUI::GLToolbarItem::Data::Option::action_callback, Slic3r::GUI::BackgroundTexture::Metadata::bottom, Slic3r::GUI::BackgroundTexture::Metadata::filename, Slic3r::GUI::GLToolbar::Layout::HO_Right, Slic3r::GUI::GLToolbarItem::Data::icon_filename, Slic3r::GUI::Plater::is_sidebar_collapsed(), Slic3r::GUI::GLToolbarItem::Data::left, Slic3r::GUI::BackgroundTexture::Metadata::left, Slic3r::GUI::GLToolbarItem::Data::name, Slic3r::GUI::plater(), Slic3r::GUI::BackgroundTexture::Metadata::right, Slic3r::GUI::GLToolbarItem::Data::sprite_id, Slic3r::GUI::BackgroundTexture::Metadata::top, Slic3r::GUI::GLToolbar::Layout::Vertical, and Slic3r::GUI::GLToolbar::Layout::VO_Top.
init_notification_manager()
void Slic3r::GUI::Plater::priv::init_notification_manager ()
{
    if (!notification_manager)
        return;
    notification_manager->init();
    auto cancel_callback = [this]() {
        if (this->background_process.idle())
            return false;
        this->background_process.stop();
        return true;
    };
    notification_manager->init_slicing_progress_notification(cancel_callback);
    notification_manager->set_fff(printer_technology == ptFFF);
    notification_manager->init_progress_indicator();
}
References Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptFFF.
init_view_toolbar()
bool Slic3r::GUI::Plater::priv::init_view_toolbar ()
{
    if (wxGetApp().is_gcode_viewer())
        return true;
    if (view_toolbar.get_items_count() > 0)
        // already initialized
        return true;
    BackgroundTexture::Metadata background_data;
    background_data.filename = "toolbar_background.png";
    background_data.left = 16;
    background_data.top = 16;
    background_data.right = 16;
    background_data.bottom = 16;
    if (!view_toolbar.init(background_data))
        return false;
    view_toolbar.set_horizontal_orientation(GLToolbar::Layout::HO_Left);
    view_toolbar.set_vertical_orientation(GLToolbar::Layout::VO_Bottom);
    view_toolbar.set_border(5.0f);
    view_toolbar.set_gap_size(1.0f);
    GLToolbarItem::Data item;
    item.name = "3D";
    item.icon_filename = "editor.svg";
    item.tooltip = _u8L("3D editor view") + " [" + GUI::shortkey_ctrl_prefix() + "5]";
    item.sprite_id = 0;
    item.left.action_callback = [this]() { if (this->q != nullptr) wxPostEvent(this->q, SimpleEvent(EVT_GLVIEWTOOLBAR_3D)); };
    if (!view_toolbar.add_item(item))
        return false;
    item.name = "Preview";
    item.icon_filename = "preview.svg";
    item.tooltip = _u8L("Preview") + " [" + GUI::shortkey_ctrl_prefix() + "6]";
    item.sprite_id = 1;
    item.left.action_callback = [this]() { if (this->q != nullptr) wxPostEvent(this->q, SimpleEvent(EVT_GLVIEWTOOLBAR_PREVIEW)); };
    if (!view_toolbar.add_item(item))
        return false;
    view_toolbar.select_item("3D");
    view_toolbar.set_enabled(true);
    return true;
}
References _u8L, Slic3r::GUI::GLToolbarItem::Data::Option::action_callback, Slic3r::GUI::BackgroundTexture::Metadata::bottom, Slic3r::GUI::BackgroundTexture::Metadata::filename, Slic3r::GUI::GLToolbar::Layout::HO_Left, Slic3r::GUI::GLToolbarItem::Data::icon_filename, Slic3r::GUI::GLToolbarItem::Data::left, Slic3r::GUI::BackgroundTexture::Metadata::left, Slic3r::GUI::GLToolbarItem::Data::name, Slic3r::GUI::BackgroundTexture::Metadata::right, Slic3r::GUI::shortkey_ctrl_prefix(), Slic3r::GUI::GLToolbarItem::Data::sprite_id, Slic3r::GUI::GLToolbarItem::Data::tooltip, Slic3r::GUI::BackgroundTexture::Metadata::top, and Slic3r::GUI::GLToolbar::Layout::VO_Bottom.
inside_snapshot_capture()
bool Slic3r::GUI::Plater::priv::inside_snapshot_capture () inline
{ return m_prevent_snapshots != 0; }
is_legend_shown()
bool Slic3r::GUI::Plater::priv::is_legend_shown () const inline
{ return (current_panel == preview) && preview->get_canvas3d()->is_legend_shown(); }
References Slic3r::GUI::Preview::get_canvas3d(), and Slic3r::GUI::GLCanvas3D::is_legend_shown().
is_presets_dirty()
bool Slic3r::GUI::Plater::priv::is_presets_dirty () const inline
{ return dirty_state.is_presets_dirty(); }
References Slic3r::GUI::ProjectDirtyStateManager::is_presets_dirty().
is_preview_loaded()
bool Slic3r::GUI::Plater::priv::is_preview_loaded () const inline
{ return preview->is_loaded(); }
References Slic3r::GUI::Preview::is_loaded().
is_preview_shown()
bool Slic3r::GUI::Plater::priv::is_preview_shown () const inline
{ return current_panel == preview; }
is_project_dirty()
bool Slic3r::GUI::Plater::priv::is_project_dirty () const inline
{ return dirty_state.is_dirty(); }
References Slic3r::GUI::ProjectDirtyStateManager::is_dirty().
is_sidebar_collapsed()
bool Slic3r::GUI::Plater::priv::is_sidebar_collapsed () const inline
{ return sidebar->is_collapsed(); }
References Slic3r::GUI::Sidebar::is_collapsed().
is_view3D_layers_editing_enabled()
bool Slic3r::GUI::Plater::priv::is_view3D_layers_editing_enabled () const inline
{ return (current_panel == view3D) && view3D->get_canvas3d()->is_layers_editing_enabled(); }
References Slic3r::GUI::View3D::get_canvas3d(), and Slic3r::GUI::GLCanvas3D::is_layers_editing_enabled().
is_view3D_shown()
bool Slic3r::GUI::Plater::priv::is_view3D_shown () const inline
{ return current_panel == view3D; }
layers_height_allowed()
bool Slic3r::GUI::Plater::priv::layers_height_allowed () const private
{
    if (printer_technology != ptFFF)
        return false;
    int obj_idx = get_selected_object_idx();
    return 0 <= obj_idx && obj_idx < (int)model.objects.size() && model.objects[obj_idx]->max_z() > SINKING_Z_THRESHOLD &&
        config->opt_bool("variable_layer_height") && view3D->is_layers_editing_allowed();
}
References Slic3r::GUI::Plater::config(), Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::ConfigBase::opt_bool(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptFFF, and Slic3r::SINKING_Z_THRESHOLD.
leave_gizmos_stack()
void Slic3r::GUI::Plater::priv::leave_gizmos_stack ()
{
    assert(m_undo_redo_stack_active == &m_undo_redo_stack_gizmos);
    if (m_undo_redo_stack_active == &m_undo_redo_stack_gizmos) {
        assert(! m_undo_redo_stack_active->empty());
        m_undo_redo_stack_active->clear();
        m_undo_redo_stack_active = &m_undo_redo_stack_main;
    }
}
load_files()
std::vector< size_t > Slic3r::GUI::Plater::priv::load_files (const std::vector< fs::path > & input_files, bool load_model, bool load_config, bool used_inches = false)
{
     if (input_files.empty()) { return std::vector<size_t>(); }
    auto *nozzle_dmrs = config->opt<ConfigOptionFloats>("nozzle_diameter");
    PlaterAfterLoadAutoArrange plater_after_load_auto_arrange;
    bool one_by_one = input_files.size() == 1 || printer_technology == ptSLA || nozzle_dmrs->values.size() <= 1;
    if (! one_by_one) {
        for (const auto &path : input_files) {
            if (std::regex_match(path.string(), pattern_bundle)) {
                one_by_one = true;
                break;
            }
        }
    }
    const auto loading = _L("Loading") + dots;
    // The situation with wxProgressDialog is quite interesting here.
    // On Linux (only), there are issues when FDM/SLA is switched during project file loading (disabling of controls,
    // see a comment below). This can be bypassed by creating the wxProgressDialog on heap and destroying it
    // when loading a project file. However, creating the dialog on heap causes issues on macOS, where it does not
    // appear at all. Therefore, we create the dialog on stack on Win and macOS, and on heap on Linux, which
    // is the only system that needed the workarounds in the first place.
#ifdef __linux__
    auto progress_dlg = new wxProgressDialog(loading, "", 100, find_toplevel_parent(q), wxPD_APP_MODAL | wxPD_AUTO_HIDE);
    Slic3r::ScopeGuard([&progress_dlg](){ if (progress_dlg) progress_dlg->Destroy(); progress_dlg = nullptr; });
#else
    wxProgressDialog progress_dlg_stack(loading, "", 100, find_toplevel_parent(q), wxPD_APP_MODAL | wxPD_AUTO_HIDE);
    wxProgressDialog* progress_dlg = &progress_dlg_stack;
#endif
    wxBusyCursor busy;
    auto *new_model = (!load_model || one_by_one) ? nullptr : new Slic3r::Model();
    std::vector<size_t> obj_idxs;
    int answer_convert_from_meters          = wxOK_DEFAULT;
    int answer_convert_from_imperial_units  = wxOK_DEFAULT;
    bool in_temp = false;
    const fs::path temp_path = wxStandardPaths::Get().GetTempDir().utf8_str().data();
    size_t input_files_size = input_files.size();
    for (size_t i = 0; i < input_files_size; ++i) {
#ifdef _WIN32
        auto path = input_files[i];
        // On Windows, we swap slashes to back slashes, see GH #6803 as read_from_file() does not understand slashes on Windows thus it assignes full path to names of loaded objects.
        path.make_preferred();
#else // _WIN32
        // Don't make a copy on Posix. Slash is a path separator, back slashes are not accepted as a substitute.
        const auto &path = input_files[i];
#endif // _WIN32
        in_temp = (path.parent_path() == temp_path);
        const auto filename = path.filename();
        if (progress_dlg) {
            progress_dlg->Update(static_cast<int>(100.0f * static_cast<float>(i) / static_cast<float>(input_files.size())), _L("Loading file") + ": " + from_path(filename));
            progress_dlg->Fit();
        }
        const bool type_3mf = std::regex_match(path.string(), pattern_3mf) || std::regex_match(path.string(), pattern_zip);
        const bool type_zip_amf = !type_3mf && std::regex_match(path.string(), pattern_zip_amf);
        const bool type_any_amf = !type_3mf && std::regex_match(path.string(), pattern_any_amf);
        const bool type_prusa = std::regex_match(path.string(), pattern_prusa);
        Slic3r::Model model;
        bool is_project_file = type_prusa;
        try {
            if (type_3mf || type_zip_amf) {
#ifdef __linux__
                // On Linux Constructor of the ProgressDialog calls DisableOtherWindows() function which causes a disabling of all children of the find_toplevel_parent(q)
                // And a destructor of the ProgressDialog calls ReenableOtherWindows() function which revert previously disabled children.
                // But if printer technology will be changes during project loading,
                // then related SLA Print and Materials Settings or FFF Print and Filaments Settings will be unparent from the wxNoteBook
                // and that is why they will never be enabled after destruction of the ProgressDialog.
                // So, distroy progress_gialog if we are loading project file
                if (input_files_size == 1 && progress_dlg) {
                    progress_dlg->Destroy();
                    progress_dlg = nullptr;
                }
#endif
                DynamicPrintConfig config;
                PrinterTechnology loaded_printer_technology {ptFFF};
                {
                    DynamicPrintConfig config_loaded;
                    ConfigSubstitutionContext config_substitutions{ ForwardCompatibilitySubstitutionRule::Enable };
                    model = Slic3r::Model::read_from_archive(path.string(), &config_loaded, &config_substitutions, only_if(load_config, Model::LoadAttribute::CheckVersion));
                    if (load_config && !config_loaded.empty()) {
                        // Based on the printer technology field found in the loaded config, select the base for the config,
                        loaded_printer_technology = Preset::printer_technology(config_loaded);
                        // We can't to load SLA project if there is at least one multi-part object on the bed
                        if (loaded_printer_technology == ptSLA) {
                            const ModelObjectPtrs& objects = q->model().objects;
                            for (auto object : objects)
                                if (object->volumes.size() > 1) {
                                    Slic3r::GUI::show_info(nullptr,
                                        _L("You cannot load SLA project with a multi-part object on the bed") + "\n\n" +
                                        _L("Please check your object list before preset changing."),
                                        _L("Attention!"));
                                    return obj_idxs;
                                }
                        }
                        config.apply(loaded_printer_technology == ptFFF ?
                            static_cast<const ConfigBase&>(FullPrintConfig::defaults()) :
                            static_cast<const ConfigBase&>(SLAFullPrintConfig::defaults()));
                        // and place the loaded config over the base.
                        config += std::move(config_loaded);
                    }
                    if (! config_substitutions.empty())
                        show_substitutions_info(config_substitutions.substitutions, filename.string());
                    this->model.custom_gcode_per_print_z = model.custom_gcode_per_print_z;
                }
                if (load_config) {
                    if (!config.empty()) {
                        Preset::normalize(config);
                        PresetBundle* preset_bundle = wxGetApp().preset_bundle;
                        preset_bundle->load_config_model(filename.string(), std::move(config));
                        q->check_selected_presets_visibility(loaded_printer_technology);
                        if (loaded_printer_technology == ptFFF)
                            CustomGCode::update_custom_gcode_per_print_z_from_config(model.custom_gcode_per_print_z, &preset_bundle->project_config);
                        // For exporting from the amf/3mf we shouldn't check printer_presets for the containing information about "Print Host upload"
                        wxGetApp().load_current_presets(false);
                        // Update filament colors for the MM-printer profile in the full config
                        // to avoid black (default) colors for Extruders in the ObjectList,
                        // when for extruder colors are used filament colors
                        q->update_filament_colors_in_full_config();
                        is_project_file = true;
                    }
                    if (!in_temp)
                        wxGetApp().app_config->update_config_dir(path.parent_path().string());
                }
            }
            else {
                model = Slic3r::Model::read_from_file(path.string(), nullptr, nullptr, only_if(load_config, Model::LoadAttribute::CheckVersion));
                for (auto obj : model.objects)
                    if (obj->name.empty())
                        obj->name = fs::path(obj->input_file).filename().string();
            }
        } catch (const ConfigurationError &e) {
            std::string message = GUI::format(_L("Failed loading file \"%1%\" due to an invalid configuration."), filename.string()) + "\n\n" + e.what();
            GUI::show_error(q, message);
            continue;
        } catch (const std::exception &e) {
            GUI::show_error(q, e.what());
            continue;
        }
        if (load_model) {
            // The model should now be initialized
            auto convert_from_imperial_units = [](Model& model, bool only_small_volumes) {
                model.convert_from_imperial_units(only_small_volumes);
//                wxGetApp().app_config->set("use_inches", "1");
//                wxGetApp().sidebar().update_ui_from_settings();
            };
            if (!is_project_file) {
                if (int deleted_objects = model.removed_objects_with_zero_volume(); deleted_objects > 0) {
                    MessageDialog(q, format_wxstr(_L_PLURAL(
                        "Object size from file %s appears to be zero.\n"
                        "This object has been removed from the model",
                        "Objects size from file %s appears to be zero.\n"
                        "These objects have been removed from the model", deleted_objects), from_path(filename)) + "\n",
                        _L("The size of the object is zero"), wxICON_INFORMATION | wxOK).ShowModal();
                }
                if (imperial_units)
                    // Convert even if the object is big.
                    convert_from_imperial_units(model, false);
                else if (model.looks_like_saved_in_meters()) {
                    auto convert_model_if = [](Model& model, bool condition) {
                        if (condition)
                            //FIXME up-scale only the small parts?
                            model.convert_from_meters(true);
                    };
                    if (answer_convert_from_meters == wxOK_DEFAULT) {
                        RichMessageDialog dlg(q, format_wxstr(_L_PLURAL(
                            "The dimensions of the object from file %s seem to be defined in meters.\n"
                            "The internal unit of PrusaSlicer is a millimeter. Do you want to recalculate the dimensions of the object?",
                            "The dimensions of some objects from file %s seem to be defined in meters.\n"
                            "The internal unit of PrusaSlicer is a millimeter. Do you want to recalculate the dimensions of these objects?", model.objects.size()), from_path(filename)) + "\n",
                            _L("The object is too small"), wxICON_QUESTION | wxYES_NO);
                        dlg.ShowCheckBox(_L("Apply to all the remaining small objects being loaded."));
                        int answer = dlg.ShowModal();
                        if (dlg.IsCheckBoxChecked())
                            answer_convert_from_meters = answer;
                        else
                            convert_model_if(model, answer == wxID_YES);
                    }
                    convert_model_if(model, answer_convert_from_meters == wxID_YES);
                }
                else if (model.looks_like_imperial_units()) {
                    auto convert_model_if = [convert_from_imperial_units](Model& model, bool condition) {
                        if (condition)
                            //FIXME up-scale only the small parts?
                            convert_from_imperial_units(model, true);
                    };
                    if (answer_convert_from_imperial_units == wxOK_DEFAULT) {
                        RichMessageDialog dlg(q, format_wxstr(_L_PLURAL(
                            "The dimensions of the object from file %s seem to be defined in inches.\n"
                            "The internal unit of PrusaSlicer is a millimeter. Do you want to recalculate the dimensions of the object?",
                            "The dimensions of some objects from file %s seem to be defined in inches.\n"
                            "The internal unit of PrusaSlicer is a millimeter. Do you want to recalculate the dimensions of these objects?", model.objects.size()), from_path(filename)) + "\n",
                            _L("The object is too small"), wxICON_QUESTION | wxYES_NO);
                        dlg.ShowCheckBox(_L("Apply to all the remaining small objects being loaded."));
                        int answer = dlg.ShowModal();
                        if (dlg.IsCheckBoxChecked())
                            answer_convert_from_imperial_units = answer;
                        else
                            convert_model_if(model, answer == wxID_YES);
                    }
                    convert_model_if(model, answer_convert_from_imperial_units == wxID_YES);
                }
                if (model.looks_like_multipart_object()) {
                    MessageDialog msg_dlg(q, _L(
                        "This file contains several objects positioned at multiple heights.\n"
                        "Instead of considering them as multiple objects, should \n"
                        "the file be loaded as a single object having multiple parts?") + "\n",
                        _L("Multi-part object detected"), wxICON_WARNING | wxYES | wxNO);
                    if (msg_dlg.ShowModal() == wxID_YES) {
                        model.convert_multipart_object(nozzle_dmrs->values.size());
                    }
                }
            }
            if ((wxGetApp().get_mode() == comSimple) && (type_3mf || type_any_amf) && model_has_advanced_features(model)) {
                MessageDialog msg_dlg(q, _L("This file cannot be loaded in a simple mode. Do you want to switch to an advanced mode?")+"\n",
                    _L("Detected advanced data"), wxICON_WARNING | wxOK | wxCANCEL);
                if (msg_dlg.ShowModal() == wxID_OK) {
                    if (wxGetApp().save_mode(comAdvanced))
                        view3D->set_as_dirty();
                }
                else
                    return obj_idxs;
            }
            for (ModelObject* model_object : model.objects) {
                if (!type_3mf && !type_zip_amf) {
                    model_object->center_around_origin(false);
                    if (type_any_amf && model_object->instances.empty()) {
                        ModelInstance* instance = model_object->add_instance();
                        instance->set_offset(-model_object->origin_translation);
                    }
                }
                if (!model_object->instances.empty())
                  model_object->ensure_on_bed(is_project_file);
            }
            if (one_by_one) {
                if ((type_3mf && !is_project_file) || (type_any_amf && !type_zip_amf))
                    model.center_instances_around_point(this->bed.build_volume().bed_center());
                auto loaded_idxs = load_model_objects(model.objects, is_project_file);
                obj_idxs.insert(obj_idxs.end(), loaded_idxs.begin(), loaded_idxs.end());
            } else {
                // This must be an .stl or .obj file, which may contain a maximum of one volume.
                for (const ModelObject* model_object : model.objects) {
                    new_model->add_object(*model_object);
                }
            }
            if (is_project_file)
                plater_after_load_auto_arrange.disable();
        }
    }
    if (new_model != nullptr && new_model->objects.size() > 1) {
        //wxMessageDialog msg_dlg(q, _L(
        MessageDialog msg_dlg(q, _L(
                "Multiple objects were loaded for a multi-material printer.\n"
                "Instead of considering them as multiple objects, should I consider\n"
                "these files to represent a single object having multiple parts?") + "\n",
                _L("Multi-part object detected"), wxICON_WARNING | wxYES | wxNO);
        if (msg_dlg.ShowModal() == wxID_YES) {
            new_model->convert_multipart_object(nozzle_dmrs->values.size());
        }
        auto loaded_idxs = load_model_objects(new_model->objects);
        obj_idxs.insert(obj_idxs.end(), loaded_idxs.begin(), loaded_idxs.end());
    }
    if (load_model && !in_temp) {
        wxGetApp().app_config->update_skein_dir(input_files[input_files.size() - 1].parent_path().make_preferred().string());
        // XXX: Plater.pm had @loaded_files, but didn't seem to fill them with the filenames...
        // statusbar()->set_status_text(_L("Loaded"));
    }
    // automatic selection of added objects
    if (!obj_idxs.empty() && view3D != nullptr) {
        // update printable state for new volumes on canvas3D
        wxGetApp().plater()->canvas3D()->update_instance_printable_state_for_objects(obj_idxs);
        Selection& selection = view3D->get_canvas3d()->get_selection();
        selection.clear();
        for (size_t idx : obj_idxs) {
            selection.add_object((unsigned int)idx, false);
        }
        if (view3D->get_canvas3d()->get_gizmos_manager().is_enabled())
            // this is required because the selected object changed and the flatten on face an sla support gizmos need to be updated accordingly
            view3D->get_canvas3d()->update_gizmos_on_off_state();
    }
    GLGizmoSimplify::add_simplify_suggestion_notification(
        obj_idxs, model.objects, *notification_manager);
    return obj_idxs;
}
References _L, _L_PLURAL, Slic3r::GUI::Selection::add_object(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), Slic3r::ConfigBase::apply(), Slic3r::Model::center_instances_around_point(), Slic3r::Model::CheckVersion, Slic3r::GUI::Selection::clear(), Slic3r::comAdvanced, Slic3r::comSimple, Slic3r::GUI::Plater::config(), Slic3r::Model::convert_from_imperial_units(), Slic3r::Model::convert_from_meters(), Slic3r::Model::convert_multipart_object(), Slic3r::Model::custom_gcode_per_print_z, Slic3r::GUI::dots(), Slic3r::DynamicConfig::empty(), Slic3r::Enable, Slic3r::GUI::find_toplevel_parent(), Slic3r::GUI::format(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::from_path(), Slic3r::PresetBundle::load_config_model(), Slic3r::Model::looks_like_imperial_units(), Slic3r::Model::looks_like_multipart_object(), Slic3r::Model::looks_like_saved_in_meters(), Slic3r::GUI::Plater::model(), Slic3r::model_has_advanced_features(), Slic3r::Preset::normalize(), Slic3r::Model::objects, Slic3r::only_if(), Slic3r::ConfigBase::opt(), Slic3r::Preset::printer_technology(), Slic3r::GUI::Plater::printer_technology(), Slic3r::PresetBundle::project_config, Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::Model::read_from_archive(), Slic3r::Model::read_from_file(), Slic3r::Model::removed_objects_with_zero_volume(), Slic3r::ModelInstance::set_offset(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::show_substitutions_info(), and Slic3r::CustomGCode::update_custom_gcode_per_print_z_from_config().
load_model_objects()
std::vector< size_t > Slic3r::GUI::Plater::priv::load_model_objects (const ModelObjectPtrs & model_objects, bool allow_negative_z = false, bool call_selection_changed = true)
{
    const Vec3d bed_size = Slic3r::to_3d(this->bed.build_volume().bounding_volume2d().size(), 1.0) - 2.0 * Vec3d::Ones();
#ifndef AUTOPLACEMENT_ON_LOAD
    // bool need_arrange = false;
#endif /* AUTOPLACEMENT_ON_LOAD */
    bool scaled_down = false;
    std::vector<size_t> obj_idxs;
    unsigned int obj_count = model.objects.size();
#ifdef AUTOPLACEMENT_ON_LOAD
    ModelInstancePtrs new_instances;
#endif /* AUTOPLACEMENT_ON_LOAD */
    for (ModelObject *model_object : model_objects) {
        auto *object = model.add_object(*model_object);
        object->sort_volumes(get_config_bool("order_volumes"));
        std::string object_name = object->name.empty() ? fs::path(object->input_file).filename().string() : object->name;
        obj_idxs.push_back(obj_count++);
        if (model_object->instances.empty()) {
#ifdef AUTOPLACEMENT_ON_LOAD
            object->center_around_origin();
            new_instances.emplace_back(object->add_instance());
#else /* AUTOPLACEMENT_ON_LOAD */
            // if object has no defined position(s) we need to rearrange everything after loading
            // need_arrange = true;
             // add a default instance and center object around origin
            object->center_around_origin();  // also aligns object to Z = 0
            ModelInstance* instance = object->add_instance();
            instance->set_offset(Slic3r::to_3d(this->bed.build_volume().bed_center(), -object->origin_translation(2)));
#endif /* AUTOPLACEMENT_ON_LOAD */
        }
        for (size_t i = 0; i < object->instances.size(); ++i) {
            ModelInstance* instance = object->instances[i];
            const Vec3d size = object->instance_bounding_box(i).size();
            const Vec3d ratio = size.cwiseQuotient(bed_size);
            const double max_ratio = std::max(ratio(0), ratio(1));
            if (max_ratio > 10000) {
                // the size of the object is too big -> this could lead to overflow when moving to clipper coordinates,
                // so scale down the mesh
                object->scale_mesh_after_creation(1. / max_ratio);
                object->origin_translation = Vec3d::Zero();
                object->center_around_origin();
                scaled_down = true;
                break;
            }
            else if (max_ratio > 5) {
                instance->set_scaling_factor(instance->get_scaling_factor() / max_ratio);
                scaled_down = true;
            }
        }
        object->ensure_on_bed(allow_negative_z);
    }
#ifdef AUTOPLACEMENT_ON_LOAD
    // FIXME distance should be a config value /////////////////////////////////
    auto min_obj_distance = static_cast<coord_t>(6/SCALING_FACTOR);
    const auto *bed_shape_opt = config->opt<ConfigOptionPoints>("bed_shape");
    assert(bed_shape_opt);
    auto& bedpoints = bed_shape_opt->values;
    Polyline bed; bed.points.reserve(bedpoints.size());
    for(auto& v : bedpoints) bed.append(Point::new_scale(v(0), v(1)));
    std::pair<bool, GLCanvas3D::WipeTowerInfo> wti = view3D->get_canvas3d()->get_wipe_tower_info();
    arr::find_new_position(model, new_instances, min_obj_distance, bed, wti);
    // it remains to move the wipe tower:
    view3D->get_canvas3d()->arrange_wipe_tower(wti);
#endif /* AUTOPLACEMENT_ON_LOAD */
    if (scaled_down) {
        GUI::show_info(q,
            _L("Your object appears to be too large, so it was automatically scaled down to fit your print bed."),
            _L("Object too large?"));
    }
    notification_manager->close_notification_of_type(NotificationType::UpdatedItemsInfo);
    for (const size_t idx : obj_idxs) {
        wxGetApp().obj_list()->add_object_to_list(idx, call_selection_changed);
    }
    if (call_selection_changed) {
        update();
        // Update InfoItems in ObjectList after update() to use of a correct value of the GLCanvas3D::is_sinking(),
        // which is updated after a view3D->reload_scene(false, flags & (unsigned int)UpdateParams::FORCE_FULL_SCREEN_REFRESH) call
        for (const size_t idx : obj_idxs)
            wxGetApp().obj_list()->update_info_items(idx);
        object_list_changed();
    }
    this->schedule_background_process();
    return obj_idxs;
}
References _L, Slic3r::Model::add_object(), Slic3r::Polyline::append(), Slic3r::GUI::Plater::config(), Slic3r::ModelInstance::get_scaling_factor(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::ConfigBase::opt(), Slic3r::MultiPoint::points, SCALING_FACTOR, Slic3r::GUI::Plater::schedule_background_process(), Slic3r::ModelInstance::set_offset(), Slic3r::ModelInstance::set_scaling_factor(), Slic3r::GUI::show_info(), Slic3r::ModelObject::sort_volumes(), Slic3r::to_3d(), Slic3r::GUI::Plater::update(), and Slic3r::GUI::UpdatedItemsInfo.
mirror()
void Slic3r::GUI::Plater::priv::mirror (Axis axis)
{
    view3D->mirror_selection(axis);
}
object_list_changed()
void Slic3r::GUI::Plater::priv::object_list_changed ()
{
    const bool export_in_progress = this->background_process.is_export_scheduled(); // || ! send_gcode_file.empty());
    // XXX: is this right?
    const bool model_fits = view3D->get_canvas3d()->check_volumes_outside_state() == ModelInstancePVS_Inside;
    sidebar->enable_buttons(!model.objects.empty() && !export_in_progress && model_fits);
}
References Slic3r::GUI::Sidebar::enable_buttons(), Slic3r::GUI::Plater::model(), Slic3r::ModelInstancePVS_Inside, Slic3r::Model::objects, and Slic3r::GUI::Plater::sidebar().
on_3dcanvas_mouse_dragging_finished()
void Slic3r::GUI::Plater::priv::on_3dcanvas_mouse_dragging_finished (SimpleEvent &)
{
    if (delayed_scene_refresh) {
        delayed_scene_refresh = false;
        update_sla_scene();
    }
}
on_3dcanvas_mouse_dragging_started()
void Slic3r::GUI::Plater::priv::on_3dcanvas_mouse_dragging_started (SimpleEvent &)
{
}
on_action_add()
void Slic3r::GUI::Plater::priv::on_action_add (SimpleEvent &)
{
    if (q != nullptr)
        q->add_model();
}
on_action_layersediting()
void Slic3r::GUI::Plater::priv::on_action_layersediting (SimpleEvent &)
{
    const bool enable_layersediting = !view3D->is_layers_editing_enabled();
    view3D->enable_layers_editing(enable_layersediting);
    if (enable_layersediting)
        view3D->get_canvas3d()->reset_all_gizmos();
    notification_manager->set_move_from_overlay(view3D->is_layers_editing_enabled());
}
on_action_split_objects()
void Slic3r::GUI::Plater::priv::on_action_split_objects (SimpleEvent &)
{
    split_object();
}
References Slic3r::GUI::Plater::split_object().
on_action_split_volumes()
void Slic3r::GUI::Plater::priv::on_action_split_volumes (SimpleEvent &)
{
    split_volume();
}
References Slic3r::GUI::Plater::split_volume().
on_export_began()
void Slic3r::GUI::Plater::priv::on_export_began (wxCommandEvent & evt)
{
  if (show_warning_dialog)
    warnings_dialog();
}
on_layer_editing_toggled()
void Slic3r::GUI::Plater::priv::on_layer_editing_toggled (bool enable)
{
    view3D->enable_layers_editing(enable);
    view3D->set_as_dirty();
}
on_object_select()
void Slic3r::GUI::Plater::priv::on_object_select (SimpleEvent & evt)
{
    wxGetApp().obj_list()->update_selections();
    selection_changed();
}
on_process_completed()
void Slic3r::GUI::Plater::priv::on_process_completed (SlicingProcessCompletedEvent & evt)
{
    // Stop the background task, wait until the thread goes into the "Idle" state.
    // At this point of time the thread should be either finished or canceled,
    // so the following call just confirms, that the produced data were consumed.
    this->background_process.stop();
//    this->statusbar()->reset_cancel_callback();
//    this->statusbar()->stop_busy();
    notification_manager->set_slicing_progress_export_possible();
    // Reset the "export G-code path" name, so that the automatic background processing will be enabled again.
    this->background_process.reset_export();
    // This bool stops showing export finished notification even when process_completed_with_error is false
    bool has_error = false;
    if (evt.error()) {
        std::pair<std::string, bool> message = evt.format_error_message();
        if (evt.critical_error()) {
            if (q->m_tracking_popup_menu) {
                // We don't want to pop-up a message box when tracking a pop-up menu.
                // We postpone the error message instead.
                q->m_tracking_popup_menu_error_message = message.first;
            } else {
                show_error(q, message.first, message.second);
                notification_manager->set_slicing_progress_hidden();
                notification_manager->stop_delayed_notifications_of_type(NotificationType::ExportOngoing);
            }
        } else
            notification_manager->push_slicing_error_notification(message.first);
//        this->statusbar()->set_status_text(from_u8(message.first));
        if (evt.invalidate_plater())
        {
            const wxString invalid_str = _L("Invalid data");
            for (auto btn : { ActionButtonType::abReslice, ActionButtonType::abSendGCode, ActionButtonType::abExport })
                sidebar->set_btn_label(btn, invalid_str);
            process_completed_with_error = true;
        }
        has_error = true;
    }
    if (evt.cancelled()) {
//        this->statusbar()->set_status_text(_L("Cancelled"));
        this->notification_manager->set_slicing_progress_canceled(_u8L("Slicing Cancelled."));
    }
    this->sidebar->show_sliced_info_sizer(evt.success());
    // This updates the "Slice now", "Export G-code", "Arrange" buttons status.
    // Namely, it refreshes the "Out of print bed" property of all the ModelObjects, and it enables
    // the "Slice now" and "Export G-code" buttons based on their "out of bed" status.
    this->object_list_changed();
    // refresh preview
    if (view3D->is_dragging()) // updating scene now would interfere with the gizmo dragging
        delayed_scene_refresh = true;
    else {
        if (this->printer_technology == ptFFF)
            this->update_fff_scene();
        else
            this->update_sla_scene();
    }
    if (evt.cancelled()) {
        if (wxGetApp().get_mode() == comSimple)
            sidebar->set_btn_label(ActionButtonType::abReslice, "Slice now");
        show_action_buttons(true);
    } else {
        if(wxGetApp().get_mode() == comSimple) {
            show_action_buttons(false);
        }
        if (exporting_status != ExportingStatus::NOT_EXPORTING && !has_error) {
            notification_manager->stop_delayed_notifications_of_type(NotificationType::ExportOngoing);
            notification_manager->close_notification_of_type(NotificationType::ExportOngoing);
        }
        // If writing to removable drive was scheduled, show notification with eject button
        if (exporting_status == ExportingStatus::EXPORTING_TO_REMOVABLE && !has_error) {
            show_action_buttons(false);
            notification_manager->push_exporting_finished_notification(last_output_path, last_output_dir_path,
                // Don't offer the "Eject" button on ChromeOS, the Linux side has no control over it.
                platform_flavor() != PlatformFlavor::LinuxOnChromium);
            wxGetApp().removable_drive_manager()->set_exporting_finished(true);
        }else if (exporting_status == ExportingStatus::EXPORTING_TO_LOCAL && !has_error)
            notification_manager->push_exporting_finished_notification(last_output_path, last_output_dir_path, false);
    }
    exporting_status = ExportingStatus::NOT_EXPORTING;
}
References _L, _u8L, Slic3r::GUI::abExport, Slic3r::GUI::abReslice, Slic3r::GUI::abSendGCode, Slic3r::SlicingProcessCompletedEvent::cancelled(), Slic3r::comSimple, Slic3r::SlicingProcessCompletedEvent::critical_error(), Slic3r::SlicingProcessCompletedEvent::error(), Slic3r::GUI::EXPORTING_TO_LOCAL, Slic3r::GUI::EXPORTING_TO_REMOVABLE, Slic3r::GUI::ExportOngoing, Slic3r::SlicingProcessCompletedEvent::format_error_message(), Slic3r::SlicingProcessCompletedEvent::invalidate_plater(), Slic3r::LinuxOnChromium, Slic3r::GUI::NOT_EXPORTING, Slic3r::platform_flavor(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptFFF, Slic3r::GUI::Sidebar::set_btn_label(), Slic3r::GUI::Plater::show_action_buttons(), Slic3r::GUI::show_error(), Slic3r::GUI::Sidebar::show_sliced_info_sizer(), Slic3r::GUI::Plater::sidebar(), and Slic3r::SlicingProcessCompletedEvent::success().
on_right_click()
void Slic3r::GUI::Plater::priv::on_right_click (RBtnEvent & evt)
{
    int obj_idx = get_selected_object_idx();
    wxMenu* menu = nullptr;
    if (obj_idx == -1) { // no one or several object are selected
        if (evt.data.second) { // right button was clicked on empty space
            if (!get_selection().is_empty()) // several objects are selected in 3DScene
                return;
            menu = menus.default_menu();
        }
        else
            menu = menus.multi_selection_menu();
    }
    else {
        // If in 3DScene is(are) selected volume(s), but right button was clicked on empty space
        if (evt.data.second)
            return;
        // Each context menu respects to the selected item in ObjectList,
        // so this selection should be updated before menu creation
        wxGetApp().obj_list()->update_selections();
//        if (printer_technology == ptSLA)
//            menu = menus.sla_object_menu();
//        else {
            const Selection& selection = get_selection();
            // show "Object menu" for each one or several FullInstance instead of FullObject
            const bool is_some_full_instances = selection.is_single_full_instance() ||
                                                selection.is_single_full_object() ||
                                                selection.is_multiple_full_instance();
            const bool is_part = selection.is_single_volume_or_modifier() && ! selection.is_any_connector();
            if (is_some_full_instances)
                menu = printer_technology == ptSLA ? menus.sla_object_menu() : menus.object_menu();
            else if (is_part)
                menu = selection.is_single_text() ? menus.text_part_menu() : menus.part_menu();
            else
                menu = menus.multi_selection_menu();
//        }
    }
    if (q != nullptr && menu) {
        Vec2d mouse_position = evt.data.first;
        wxPoint position(static_cast<int>(mouse_position.x()),
                         static_cast<int>(mouse_position.y()));
#ifdef __linux__
        // For some reason on Linux the menu isn't displayed if position is
        // specified (even though the position is sane).
        position = wxDefaultPosition;
#endif
        GLCanvas3D &canvas = *q->canvas3D();
        canvas.apply_retina_scale(mouse_position);
        canvas.set_popup_menu_position(mouse_position);
        q->PopupMenu(menu, position);
        canvas.clear_popup_menu_position();
    }
}
References Slic3r::GUI::GLCanvas3D::apply_retina_scale(), Slic3r::GUI::GLCanvas3D::clear_popup_menu_position(), Slic3r::GUI::Event< T >::data, Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::is_any_connector(), Slic3r::GUI::Selection::is_multiple_full_instance(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_text(), Slic3r::GUI::Selection::is_single_volume_or_modifier(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptSLA, and Slic3r::GUI::GLCanvas3D::set_popup_menu_position().
on_select_preset()
void Slic3r::GUI::Plater::priv::on_select_preset (wxCommandEvent & evt)
Because of The MSW and GTK version of wxBitmapComboBox derived from wxComboBox, but the OSX version derived from wxOwnerDrawnCombo. So, to get selected string we do combo->GetString(combo->GetSelection()) instead of combo->GetStringSelection().ToUTF8().data());
{
    PlaterPresetComboBox* combo = static_cast<PlaterPresetComboBox*>(evt.GetEventObject());
    Preset::Type preset_type    = combo->get_type();
    // see https://github.com/prusa3d/PrusaSlicer/issues/3889
    // Under OSX: in case of use of a same names written in different case (like "ENDER" and "Ender"),
    // m_presets_choice->GetSelection() will return first item, because search in PopupListCtrl is case-insensitive.
    // So, use GetSelection() from event parameter
    int selection = evt.GetSelection();
    auto idx = combo->get_extruder_idx();
    std::string preset_name = wxGetApp().preset_bundle->get_preset_name_by_alias(preset_type,
        Preset::remove_suffix_modified(into_u8(combo->GetString(selection))), idx);
    std::string last_selected_ph_printer_name = combo->get_selected_ph_printer_name();
    bool select_preset = !combo->selection_is_changed_according_to_physical_printers();
    // TODO: ?
    if (preset_type == Preset::TYPE_FILAMENT) {
        wxGetApp().preset_bundle->set_filament_preset(idx, preset_name);
        TabFilament* tab = dynamic_cast<TabFilament*>(wxGetApp().get_tab(Preset::TYPE_FILAMENT));
        if (tab && combo->get_extruder_idx() == tab->get_active_extruder() && !tab->select_preset(preset_name)) {
            // revert previously selection
            const std::string& old_name = wxGetApp().preset_bundle->filaments.get_edited_preset().name;
            wxGetApp().preset_bundle->set_filament_preset(idx, old_name);
        }
        else
            // Synchronize config.ini with the current selections.
            wxGetApp().preset_bundle->export_selections(*wxGetApp().app_config);
        combo->update();
    }
    else if (select_preset) {
        wxWindowUpdateLocker noUpdates(sidebar->presets_panel());
        wxGetApp().get_tab(preset_type)->select_preset(preset_name, false, last_selected_ph_printer_name);
    }
    if (preset_type != Preset::TYPE_PRINTER || select_preset) {
        // update plater with new config
        q->on_config_change(wxGetApp().preset_bundle->full_config());
    }
    if (preset_type == Preset::TYPE_PRINTER) {
    /* Settings list can be changed after printer preset changing, so
     * update all settings items for all item had it.
     * Furthermore, Layers editing is implemented only for FFF printers
     * and for SLA presets they should be deleted
     */
        wxGetApp().obj_list()->update_object_list_by_printer_technology();
    }
#ifdef __WXMSW__
    // From the Win 2004 preset combobox lose a focus after change the preset selection
    // and that is why the up/down arrow doesn't work properly
    // (see https://github.com/prusa3d/PrusaSlicer/issues/5531 ).
    // So, set the focus to the combobox explicitly
    combo->SetFocus();
#endif
}
References Slic3r::GUI::TabFilament::get_active_extruder(), Slic3r::GUI::PlaterPresetComboBox::get_extruder_idx(), Slic3r::GUI::PlaterPresetComboBox::get_selected_ph_printer_name(), Slic3r::GUI::PresetComboBox::get_type(), Slic3r::GUI::into_u8(), Slic3r::GUI::Tab::name(), Slic3r::GUI::Sidebar::presets_panel(), Slic3r::Preset::remove_suffix_modified(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::Plater::sidebar(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINTER, and Slic3r::GUI::PlaterPresetComboBox::update().
on_slicing_began()
void Slic3r::GUI::Plater::priv::on_slicing_began ()
{
  clear_warnings();
    notification_manager->close_notification_of_type(NotificationType::SignDetected);
    notification_manager->close_notification_of_type(NotificationType::ExportFinished);
    notification_manager->set_slicing_progress_began();
}
References Slic3r::GUI::ExportFinished, and Slic3r::GUI::SignDetected.
on_slicing_completed()
void Slic3r::GUI::Plater::priv::on_slicing_completed (wxCommandEvent & evt)
{
    if (view3D->is_dragging()) // updating scene now would interfere with the gizmo dragging
        delayed_scene_refresh = true;
    else {
        if (this->printer_technology == ptFFF)
            this->update_fff_scene();
        else
            this->update_sla_scene();
    }
}
References Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptFFF.
on_slicing_update()
void Slic3r::GUI::Plater::priv::on_slicing_update (SlicingStatusEvent & evt)
{
    if (evt.status.percent >= -1) {
        if (!m_worker.is_idle()) {
            // Avoid a race condition
            return;
        }
        notification_manager->set_slicing_progress_percentage(evt.status.text, (float)evt.status.percent / 100.0f);
    }
    // Check template filaments and add warning
    // This is more convinient to do here than in slicing backend, so it happens on "Slicing complete".
    if (evt.status.percent >= 100 && this->printer_technology == ptFFF) {
        size_t templ_cnt = 0;
        const auto& preset_bundle = wxGetApp().preset_bundle;
        std::string names;
        for (const auto& extruder_filaments : preset_bundle->extruders_filaments) {
            const Preset* preset = extruder_filaments.get_selected_preset();
            if (preset && preset->vendor && preset->vendor->templates_profile) {
                names += "\n" + preset->name;
                templ_cnt++;
            }
        }
        if (templ_cnt > 0) {
            const std::string message_notif = GUI::format("%1%\n%2%\n\n%3%\n\n%4% "
                , _L_PLURAL("You are using template filament preset.", "You are using template filament presets.", templ_cnt)
                , names
                , _u8L("Please note that template presets are not customized for specific printer and should only be used as a starting point for creating your own user presets.")
                ,_u8L("More info at"));
            // warning dialog proccessing cuts text at first '/n' - pass the text without new lines (and without filament names).
            const std::string message_dial = GUI::format("%1% %2% %3%"
                , _L_PLURAL("You are using template filament preset.", "You are using template filament presets.", templ_cnt)
                , _u8L("Please note that template presets are not customized for specific printer and should only be used as a starting point for creating your own user presets.")
                , "<a href=https://help.prusa3d.com/article/template-filaments_467599>https://help.prusa3d.com/</a>"
            );
            BOOST_LOG_TRIVIAL(warning) << message_notif;
            notification_manager->push_slicing_warning_notification(message_notif, false, 0, 0, "https://help.prusa3d.com/",
                [](wxEvtHandler* evnthndlr) { wxGetApp().open_browser_with_warning_dialog("https://help.prusa3d.com/article/template-filaments_467599"); return false; }
                );
            add_warning({ PrintStateBase::WarningLevel::CRITICAL, true, message_dial, 0}, 0);
        }
    }
    if (evt.status.flags & (PrintBase::SlicingStatus::RELOAD_SCENE | PrintBase::SlicingStatus::RELOAD_SLA_SUPPORT_POINTS)) {
        switch (this->printer_technology) {
        case ptFFF:
            this->update_fff_scene();
            break;
        case ptSLA:
            // If RELOAD_SLA_SUPPORT_POINTS, then the SLA gizmo is updated (reload_scene calls update_gizmos_data)
            if (view3D->is_dragging())
                delayed_scene_refresh = true;
            else {
                view3D->get_canvas3d()->enable_sla_view_type_detection();
                this->update_sla_scene();
            }
            break;
        default: break;
        }
    } else if (evt.status.flags & PrintBase::SlicingStatus::RELOAD_SLA_PREVIEW) {
        // Update the SLA preview. Only called if not RELOAD_SLA_SUPPORT_POINTS, as the block above will refresh the preview anyways.
        this->preview->reload_print();
    }
    if ((evt.status.flags & PrintBase::SlicingStatus::UPDATE_PRINT_STEP_WARNINGS) &&
        static_cast<PrintStep>(evt.status.warning_step) == psAlertWhenSupportsNeeded &&
        !get_app_config()->get_bool("alert_when_supports_needed")) {
        // This alerts are from psAlertWhenSupportsNeeded and the respective app settings is not Enabled, so discard the alerts.
    } else if (evt.status.flags &
               (PrintBase::SlicingStatus::UPDATE_PRINT_STEP_WARNINGS | PrintBase::SlicingStatus::UPDATE_PRINT_OBJECT_STEP_WARNINGS)) {
        // Update notification center with warnings of object_id and its warning_step.
        ObjectID object_id = evt.status.warning_object_id;
        int warning_step = evt.status.warning_step;
        PrintStateBase::StateWithWarnings state;
        if (evt.status.flags & PrintBase::SlicingStatus::UPDATE_PRINT_STEP_WARNINGS) {
            state = this->printer_technology == ptFFF ?
                this->fff_print.step_state_with_warnings(static_cast<PrintStep>(warning_step)) :
                this->sla_print.step_state_with_warnings(static_cast<SLAPrintStep>(warning_step));
        } else if (this->printer_technology == ptFFF) {
            const PrintObject *print_object = this->fff_print.get_object(object_id);
            if (print_object)
                state = print_object->step_state_with_warnings(static_cast<PrintObjectStep>(warning_step));
        } else {
            const SLAPrintObject *print_object = this->sla_print.get_object(object_id);
            if (print_object)
                state = print_object->step_state_with_warnings(static_cast<SLAPrintObjectStep>(warning_step));
        }
        // Now process state.warnings.
    for (auto const& warning : state.warnings) {
      if (warning.current) {
                notification_manager->push_slicing_warning_notification(warning.message, false, object_id, warning_step);
                add_warning(warning, object_id.id);
      }
    }
    }
}
References _L_PLURAL, _u8L, Slic3r::PrintStateBase::CRITICAL, Slic3r::GUI::Plater::fff_print(), Slic3r::PrintBase::SlicingStatus::flags, Slic3r::GUI::format(), Slic3r::GUI::get_app_config(), Slic3r::SLAPrint::get_object(), Slic3r::Print::get_object(), Slic3r::ObjectID::id, Slic3r::Preset::name, Slic3r::PrintBase::SlicingStatus::percent, Slic3r::GUI::Plater::printer_technology(), Slic3r::psAlertWhenSupportsNeeded, Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::PrintBase::SlicingStatus::RELOAD_SCENE, Slic3r::PrintBase::SlicingStatus::RELOAD_SLA_PREVIEW, Slic3r::PrintBase::SlicingStatus::RELOAD_SLA_SUPPORT_POINTS, Slic3r::GUI::Plater::sla_print(), Slic3r::SlicingStatusEvent::status, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::step_state_with_warnings(), Slic3r::PrintBaseWithState< PrintStepEnumType, COUNT >::step_state_with_warnings(), Slic3r::VendorProfile::templates_profile, Slic3r::PrintBase::SlicingStatus::text, Slic3r::PrintBase::SlicingStatus::UPDATE_PRINT_OBJECT_STEP_WARNINGS, Slic3r::PrintBase::SlicingStatus::UPDATE_PRINT_STEP_WARNINGS, Slic3r::Preset::vendor, Slic3r::PrintBase::SlicingStatus::warning_object_id, Slic3r::PrintBase::SlicingStatus::warning_step, and Slic3r::PrintStateBase::StateWithWarnings::warnings.
on_update_geometry()
void Slic3r::GUI::Plater::priv::on_update_geometry (Vec3dsEvent< 2 > &)
{
    // TODO
}
on_wipetower_moved()
void Slic3r::GUI::Plater::priv::on_wipetower_moved (Vec3dEvent & evt)
{
    DynamicPrintConfig cfg;
    cfg.opt<ConfigOptionFloat>("wipe_tower_x", true)->value = evt.data(0);
    cfg.opt<ConfigOptionFloat>("wipe_tower_y", true)->value = evt.data(1);
    wxGetApp().get_tab(Preset::TYPE_PRINT)->load_config(cfg);
}
References Slic3r::GUI::Event< T >::data, Slic3r::ConfigBase::opt(), and Slic3r::Preset::TYPE_PRINT.
on_wipetower_rotated()
void Slic3r::GUI::Plater::priv::on_wipetower_rotated (Vec3dEvent & evt)
{
    DynamicPrintConfig cfg;
    cfg.opt<ConfigOptionFloat>("wipe_tower_x", true)->value = evt.data(0);
    cfg.opt<ConfigOptionFloat>("wipe_tower_y", true)->value = evt.data(1);
    cfg.opt<ConfigOptionFloat>("wipe_tower_rotation_angle", true)->value = Geometry::rad2deg(evt.data(2));
    wxGetApp().get_tab(Preset::TYPE_PRINT)->load_config(cfg);
}
References Slic3r::GUI::Event< T >::data, Slic3r::ConfigBase::opt(), Slic3r::Geometry::rad2deg(), and Slic3r::Preset::TYPE_PRINT.
process_validation_warning()
void Slic3r::GUI::Plater::priv::process_validation_warning (const std::vector< std::string > & warning) const
{
    if (warnings.empty())
        notification_manager->close_notification_of_type(NotificationType::ValidateWarning);
    for (std::string text :  warnings) {
        std::string hypertext = "";
        std::function<bool(wxEvtHandler*)> action_fn = [](wxEvtHandler*){ return false; };
        if (text == "_SUPPORTS_OFF") {
            text = _u8L("An object has custom support enforcers which will not be used "
                        "because supports are disabled.")+"\n";
            hypertext = _u8L("Enable supports for enforcers only");
            action_fn = [](wxEvtHandler*) {
                Tab* print_tab = wxGetApp().get_tab(Preset::TYPE_PRINT);
                assert(print_tab);
                DynamicPrintConfig& config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
                config.set_key_value("support_material", new ConfigOptionBool(true));
                config.set_key_value("support_material_auto", new ConfigOptionBool(false));
                print_tab->on_value_change("support_material", config.opt_bool("support_material"));
                print_tab->on_value_change("support_material_auto", config.opt_bool("support_material_auto"));
                return true;
            };
        }
        if (text == "_BED_TEMPS_DIFFER")
            text = _u8L("Bed temperatures for the used filaments differ significantly.");
        notification_manager->push_notification(
            NotificationType::ValidateWarning,
            NotificationManager::NotificationLevel::WarningNotificationLevel,
            _u8L("WARNING:") + "\n" + text, hypertext, action_fn
        );
    }
}
References _u8L, Slic3r::GUI::Plater::config(), Slic3r::GUI::Tab::on_value_change(), Slic3r::ConfigBase::opt_bool(), Slic3r::DynamicConfig::set_key_value(), Slic3r::Preset::TYPE_PRINT, Slic3r::GUI::ValidateWarning, and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
redo()
void Slic3r::GUI::Plater::priv::redo ()
{
    const std::vector<UndoRedo::Snapshot> &snapshots = this->undo_redo_stack().snapshots();
    auto it_current = std::lower_bound(snapshots.begin(), snapshots.end(), UndoRedo::Snapshot(this->undo_redo_stack().active_snapshot_time()));
    if (++ it_current != snapshots.end())
        this->undo_redo_to(it_current);
}
reload_all_from_disk()
void Slic3r::GUI::Plater::priv::reload_all_from_disk ()
{
    if (model.objects.empty())
        return;
    Plater::TakeSnapshot snapshot(q, _L("Reload all from disk"));
    Plater::SuppressSnapshots suppress(q);
    Selection& selection = get_selection();
    Selection::IndicesList curr_idxs = selection.get_volume_idxs();
    // reload from disk uses selection
    select_all();
    reload_from_disk();
    // restore previous selection
    selection.clear();
    for (unsigned int idx : curr_idxs) {
        selection.add(idx, false);
    }
}
References _L, Slic3r::GUI::Selection::add(), Slic3r::GUI::Selection::clear(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::Plater::reload_from_disk(), and Slic3r::GUI::Plater::select_all().
reload_from_disk()
void Slic3r::GUI::Plater::priv::reload_from_disk ()
{
    // collect selected reloadable ModelVolumes
    std::vector<std::pair<int, int>> selected_volumes = reloadable_volumes(model, get_selection());
    // nothing to reload, return
    if (selected_volumes.empty())
        return;
    std::sort(selected_volumes.begin(), selected_volumes.end(), [](const std::pair<int, int>& v1, const std::pair<int, int>& v2) {
        return (v1.first < v2.first) || (v1.first == v2.first && v1.second < v2.second);
        });
    selected_volumes.erase(std::unique(selected_volumes.begin(), selected_volumes.end(), [](const std::pair<int, int>& v1, const std::pair<int, int>& v2) {
        return (v1.first == v2.first) && (v1.second == v2.second); }), selected_volumes.end());
    // collects paths of files to load
    std::vector<fs::path> input_paths;
    std::vector<fs::path> missing_input_paths;
    std::vector<std::pair<fs::path, fs::path>> replace_paths;
    for (auto [obj_idx, vol_idx] : selected_volumes) {
        const ModelObject* object = model.objects[obj_idx];
        const ModelVolume* volume = object->volumes[vol_idx];
        if (fs::exists(volume->source.input_file))
            input_paths.push_back(volume->source.input_file);
        else {
            // searches the source in the same folder containing the object
            bool found = false;
            if (!object->input_file.empty()) {
                fs::path object_path = fs::path(object->input_file).remove_filename();
                if (!object_path.empty()) {
                    object_path /= fs::path(volume->source.input_file).filename();
                    if (fs::exists(object_path)) {
                        input_paths.push_back(object_path);
                        found = true;
                    }
                }
            }
            if (!found)
                missing_input_paths.push_back(volume->source.input_file);
        }
    }
    std::sort(missing_input_paths.begin(), missing_input_paths.end());
    missing_input_paths.erase(std::unique(missing_input_paths.begin(), missing_input_paths.end()), missing_input_paths.end());
    while (!missing_input_paths.empty()) {
        // ask user to select the missing file
        fs::path search = missing_input_paths.back();
        wxString title = _L("Please select the file to reload");
#if defined(__APPLE__)
        title += " (" + from_u8(search.filename().string()) + ")";
#endif // __APPLE__
        title += ":";
        wxFileDialog dialog(q, title, "", from_u8(search.filename().string()), file_wildcards(FT_MODEL), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
        if (dialog.ShowModal() != wxID_OK)
            return;
        std::string sel_filename_path = dialog.GetPath().ToUTF8().data();
        std::string sel_filename = fs::path(sel_filename_path).filename().string();
        if (boost::algorithm::iequals(search.filename().string(), sel_filename)) {
            input_paths.push_back(sel_filename_path);
            missing_input_paths.pop_back();
            fs::path sel_path = fs::path(sel_filename_path).remove_filename().string();
            std::vector<fs::path>::iterator it = missing_input_paths.begin();
            while (it != missing_input_paths.end()) {
                // try to use the path of the selected file with all remaining missing files
                fs::path repathed_filename = sel_path;
                repathed_filename /= it->filename();
                if (fs::exists(repathed_filename)) {
                    input_paths.push_back(repathed_filename.string());
                    it = missing_input_paths.erase(it);
                }
                else
                    ++it;
            }
        }
        else {
            wxString message = _L("The selected file") + " (" + from_u8(sel_filename) + ") " +
                _L("differs from the original file") + " (" + from_u8(search.filename().string()) + ").\n" + _L("Do you want to replace it") + " ?";
            //wxMessageDialog dlg(q, message, wxMessageBoxCaptionStr, wxYES_NO | wxYES_DEFAULT | wxICON_QUESTION);
            MessageDialog dlg(q, message, wxMessageBoxCaptionStr, wxYES_NO | wxYES_DEFAULT | wxICON_QUESTION);
            if (dlg.ShowModal() == wxID_YES)
                replace_paths.emplace_back(search, sel_filename_path);
            missing_input_paths.pop_back();
        }
    }
    std::sort(input_paths.begin(), input_paths.end());
    input_paths.erase(std::unique(input_paths.begin(), input_paths.end()), input_paths.end());
    std::sort(replace_paths.begin(), replace_paths.end());
    replace_paths.erase(std::unique(replace_paths.begin(), replace_paths.end()), replace_paths.end());
    Plater::TakeSnapshot snapshot(q, _L("Reload from disk"));
    std::vector<wxString> fail_list;
    Busy busy(_L("Reload from:"), q->get_current_canvas3D()->get_wxglcanvas());
    // load one file at a time
    for (size_t i = 0; i < input_paths.size(); ++i) {
        const auto& path = input_paths[i].string();
        busy.update(_L("Reload from:") + " " + from_u8(path));
        Model new_model;
        try
        {
            new_model = Model::read_from_file(path, nullptr, nullptr, Model::LoadAttribute::AddDefaultInstances);
            for (ModelObject* model_object : new_model.objects) {
                model_object->center_around_origin();
                model_object->ensure_on_bed();
            }
        }
        catch (std::exception& e)
        {
            // error while loading
            busy.reset();
            GUI::show_error(q, e.what());
            return;
        }
        // update the selected volumes whose source is the current file
        for (auto [obj_idx, vol_idx] : selected_volumes) {
            ModelObject* old_model_object = model.objects[obj_idx];
            ModelVolume* old_volume = old_model_object->volumes[vol_idx];
            bool sinking = old_model_object->min_z() < SINKING_Z_THRESHOLD;
            bool has_source = !old_volume->source.input_file.empty() && boost::algorithm::iequals(fs::path(old_volume->source.input_file).filename().string(), fs::path(path).filename().string());
            bool has_name = !old_volume->name.empty() && boost::algorithm::iequals(old_volume->name, fs::path(path).filename().string());
            if (has_source || has_name) {
                int new_volume_idx = -1;
                int new_object_idx = -1;
                bool match_found = false;
                // take idxs from the matching volume
                if (has_source && old_volume->source.object_idx < int(new_model.objects.size())) {
                    const ModelObject* obj = new_model.objects[old_volume->source.object_idx];
                    if (old_volume->source.volume_idx < int(obj->volumes.size())) {
                        if (obj->volumes[old_volume->source.volume_idx]->name == old_volume->name) {
                            new_volume_idx = old_volume->source.volume_idx;
                            new_object_idx = old_volume->source.object_idx;
                            match_found = true;
                        }
                    }
                }
                if (!match_found && has_name) {
                    // take idxs from the 1st matching volume
                    for (size_t o = 0; o < new_model.objects.size(); ++o) {
                        ModelObject* obj = new_model.objects[o];
                        bool found = false;
                        for (size_t v = 0; v < obj->volumes.size(); ++v) {
                            if (obj->volumes[v]->name == old_volume->name) {
                                new_volume_idx = (int)v;
                                new_object_idx = (int)o;
                                found = true;
                                break;
                            }
                        }
                        if (found)
                            break;
                    }
                }
                if (new_object_idx < 0 || int(new_model.objects.size()) <= new_object_idx) {
                    fail_list.push_back(from_u8(has_source ? old_volume->source.input_file : old_volume->name));
                    continue;
                }
                ModelObject* new_model_object = new_model.objects[new_object_idx];
                if (new_volume_idx < 0 || int(new_model_object->volumes.size()) <= new_volume_idx) {
                    fail_list.push_back(from_u8(has_source ? old_volume->source.input_file : old_volume->name));
                    continue;
                }
                old_model_object->add_volume(*new_model_object->volumes[new_volume_idx]);
                ModelVolume* new_volume = old_model_object->volumes.back();
                new_volume->set_new_unique_id();
                new_volume->config.apply(old_volume->config);
                new_volume->set_type(old_volume->type());
                new_volume->set_material_id(old_volume->material_id());
                new_volume->set_transformation(
                    old_volume->get_transformation().get_matrix() *
                    old_volume->source.transform.get_matrix_no_offset() *
                    Geometry::translation_transform(new_volume->source.mesh_offset - old_volume->source.mesh_offset) *
                    new_volume->source.transform.get_matrix_no_offset().inverse()
                    );
                new_volume->source.object_idx = old_volume->source.object_idx;
                new_volume->source.volume_idx = old_volume->source.volume_idx;
                assert(!old_volume->source.is_converted_from_inches || !old_volume->source.is_converted_from_meters);
                if (old_volume->source.is_converted_from_inches)
                    new_volume->convert_from_imperial_units();
                else if (old_volume->source.is_converted_from_meters)
                    new_volume->convert_from_meters();
                std::swap(old_model_object->volumes[vol_idx], old_model_object->volumes.back());
                old_model_object->delete_volume(old_model_object->volumes.size() - 1);
                if (!sinking)
                    old_model_object->ensure_on_bed();
                old_model_object->sort_volumes(get_config_bool("order_volumes"));
                sla::reproject_points_and_holes(old_model_object);
                // Fix warning icon in object list
                wxGetApp().obj_list()->update_item_error_icon(obj_idx, vol_idx);
            }
        }
    }
    busy.reset();
    for (auto [src, dest] : replace_paths) {
        for (auto [obj_idx, vol_idx] : selected_volumes) {
            if (boost::algorithm::iequals(model.objects[obj_idx]->volumes[vol_idx]->source.input_file, src.string()))
                replace_volume_with_stl(obj_idx, vol_idx, dest, "");
        }
    }
    if (!fail_list.empty()) {
        wxString message = _L("Unable to reload:") + "\n";
        for (const wxString& s : fail_list) {
            message += s + "\n";
        }
        //wxMessageDialog dlg(q, message, _L("Error during reload"), wxOK | wxOK_DEFAULT | wxICON_WARNING);
        MessageDialog dlg(q, message, _L("Error during reload"), wxOK | wxOK_DEFAULT | wxICON_WARNING);
        dlg.ShowModal();
    }
    // update 3D scene
    update();
    // new GLVolumes have been created at this point, so update their printable state
    for (size_t i = 0; i < model.objects.size(); ++i) {
        view3D->get_canvas3d()->update_instance_printable_state_for_object(i);
    }
}
References _L, Slic3r::ModelObject::add_volume(), Slic3r::Model::AddDefaultInstances, Slic3r::ModelConfig::apply(), Slic3r::ModelVolume::config, Slic3r::ModelVolume::convert_from_imperial_units(), Slic3r::ModelVolume::convert_from_meters(), Slic3r::ModelObject::delete_volume(), Slic3r::ModelObject::ensure_on_bed(), Slic3r::GUI::file_wildcards(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_MODEL, Slic3r::GUI::View3D::get_canvas3d(), get_config_bool(), Slic3r::GUI::Plater::get_current_canvas3D(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_matrix_no_offset(), get_selection(), Slic3r::ModelVolume::get_transformation(), Slic3r::GUI::GLCanvas3D::get_wxglcanvas(), Slic3r::ModelObject::input_file, Slic3r::ModelVolume::Source::input_file, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::ModelVolume::Source::is_converted_from_inches, Slic3r::ModelVolume::Source::is_converted_from_meters, Slic3r::ModelVolume::material_id(), Slic3r::ModelVolume::Source::mesh_offset, Slic3r::ModelObject::min_z(), model, Slic3r::ModelVolume::name, Slic3r::ModelVolume::Source::object_idx, Slic3r::Model::objects, q, Slic3r::Model::read_from_file(), Slic3r::GUI::reloadable_volumes(), replace_volume_with_stl(), Slic3r::sla::reproject_points_and_holes(), Slic3r::GUI::Busy::reset(), Slic3r::GUI::Plater::search(), Slic3r::ModelVolume::set_material_id(), Slic3r::ModelVolume::set_new_unique_id(), Slic3r::ModelVolume::set_transformation(), Slic3r::ModelVolume::set_type(), Slic3r::GUI::show_error(), Slic3r::SINKING_Z_THRESHOLD, Slic3r::ModelObject::sort_volumes(), Slic3r::ModelVolume::source, Slic3r::ModelVolume::Source::transform, Slic3r::Geometry::translation_transform(), Slic3r::ModelVolume::type(), Slic3r::GUI::Busy::update(), update(), Slic3r::GUI::GLCanvas3D::update_instance_printable_state_for_object(), view3D, Slic3r::ModelVolume::Source::volume_idx, and Slic3r::ModelObject::volumes.
remove()
void Slic3r::GUI::Plater::priv::remove (size_t obj_idx)
{
    if (view3D->is_layers_editing_enabled())
        view3D->enable_layers_editing(false);
    m_worker.cancel_all();
    model.delete_object(obj_idx);
    update();
    // Delete object from Sidebar list. Do it after update, so that the GLScene selection is updated with the modified model.
    sidebar->obj_list()->delete_object_from_list(obj_idx);
    object_list_changed();
}
References Slic3r::Model::delete_object(), Slic3r::GUI::ObjectList::delete_object_from_list(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Plater::update().
replace_volume_with_stl()
bool Slic3r::GUI::Plater::priv::replace_volume_with_stl (int object_idx, int volume_idx, const fs::path & new_path, const wxString & snapshot = "")
{
    const std::string path = new_path.string();
    Busy busy(_L("Replace from:") + " " + from_u8(path), q->get_current_canvas3D()->get_wxglcanvas());
    Model new_model;
    try {
        new_model = Model::read_from_file(path, nullptr, nullptr, Model::LoadAttribute::AddDefaultInstances);
        for (ModelObject* model_object : new_model.objects) {
            model_object->center_around_origin();
            model_object->ensure_on_bed();
        }
    }
    catch (std::exception& e) {
        // error while loading
        busy.reset();
        GUI::show_error(q, e.what());
        return false;
    }
    if (new_model.objects.size() > 1 || new_model.objects.front()->volumes.size() > 1) {
        MessageDialog dlg(q, _L("Unable to replace with more than one volume"), _L("Error during replace"), wxOK | wxOK_DEFAULT | wxICON_WARNING);
        dlg.ShowModal();
        return false;
    }
    if (!snapshot.empty())
        q->take_snapshot(snapshot);
    ModelObject* old_model_object = model.objects[object_idx];
    ModelVolume* old_volume = old_model_object->volumes[volume_idx];
    bool sinking = old_model_object->min_z() < SINKING_Z_THRESHOLD;
    ModelObject* new_model_object = new_model.objects.front();
    old_model_object->add_volume(*new_model_object->volumes.front());
    ModelVolume* new_volume = old_model_object->volumes.back();
    new_volume->set_new_unique_id();
    new_volume->config.apply(old_volume->config);
    new_volume->set_type(old_volume->type());
    new_volume->set_material_id(old_volume->material_id());
    new_volume->set_transformation(old_volume->get_transformation());
    new_volume->translate(new_volume->get_transformation().get_matrix_no_offset() * (new_volume->source.mesh_offset - old_volume->source.mesh_offset));
    assert(!old_volume->source.is_converted_from_inches || !old_volume->source.is_converted_from_meters);
    if (old_volume->source.is_converted_from_inches)
        new_volume->convert_from_imperial_units();
    else if (old_volume->source.is_converted_from_meters)
        new_volume->convert_from_meters();
    new_volume->supported_facets.assign(old_volume->supported_facets);
    new_volume->seam_facets.assign(old_volume->seam_facets);
    new_volume->mmu_segmentation_facets.assign(old_volume->mmu_segmentation_facets);
    std::swap(old_model_object->volumes[volume_idx], old_model_object->volumes.back());
    old_model_object->delete_volume(old_model_object->volumes.size() - 1);
    if (!sinking)
        old_model_object->ensure_on_bed();
    old_model_object->sort_volumes(get_config_bool("order_volumes"));
    // if object has just one volume, rename object too
    if (old_model_object->volumes.size() == 1)
        old_model_object->name = old_model_object->volumes.front()->name;
    // update new name in ObjectList
    sidebar->obj_list()->update_name_in_list(object_idx, volume_idx);
    sla::reproject_points_and_holes(old_model_object);
    return true;
}
References _L, Slic3r::ModelObject::add_volume(), Slic3r::Model::AddDefaultInstances, Slic3r::ModelConfig::apply(), Slic3r::FacetsAnnotation::assign(), Slic3r::ModelVolume::config, Slic3r::ModelVolume::convert_from_imperial_units(), Slic3r::ModelVolume::convert_from_meters(), Slic3r::ModelObject::delete_volume(), Slic3r::ModelObject::ensure_on_bed(), Slic3r::GUI::from_u8(), Slic3r::Geometry::Transformation::get_matrix_no_offset(), Slic3r::ModelVolume::get_transformation(), Slic3r::ModelVolume::Source::is_converted_from_inches, Slic3r::ModelVolume::Source::is_converted_from_meters, Slic3r::ModelVolume::material_id(), Slic3r::ModelVolume::Source::mesh_offset, Slic3r::ModelObject::min_z(), Slic3r::ModelVolume::mmu_segmentation_facets, Slic3r::GUI::Plater::model(), Slic3r::ModelObject::name, Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, Slic3r::Model::read_from_file(), Slic3r::sla::reproject_points_and_holes(), Slic3r::GUI::Busy::reset(), Slic3r::ModelVolume::seam_facets, Slic3r::ModelVolume::set_material_id(), Slic3r::ModelVolume::set_new_unique_id(), Slic3r::ModelVolume::set_transformation(), Slic3r::ModelVolume::set_type(), Slic3r::GUI::show_error(), Slic3r::GUI::Plater::sidebar(), Slic3r::SINKING_Z_THRESHOLD, Slic3r::ModelObject::sort_volumes(), Slic3r::ModelVolume::source, Slic3r::ModelVolume::supported_facets, Slic3r::ModelVolume::translate(), Slic3r::ModelVolume::type(), Slic3r::GUI::ObjectList::update_name_in_list(), and Slic3r::ModelObject::volumes.
Referenced by reload_from_disk().
replace_with_stl()
void Slic3r::GUI::Plater::priv::replace_with_stl ()
{
    if (! q->canvas3D()->get_gizmos_manager().check_gizmos_closed_except(GLGizmosManager::EType::Undefined))
        return;
    const Selection& selection = get_selection();
    if (selection.is_wipe_tower() || get_selection().get_volume_idxs().size() != 1)
        return;
    const GLVolume* v = selection.get_first_volume();
    int object_idx = v->object_idx();
    int volume_idx = v->volume_idx();
    // collects paths of files to load
    const ModelObject* object = model.objects[object_idx];
    const ModelVolume* volume = object->volumes[volume_idx];
    fs::path input_path;
    if (!volume->source.input_file.empty() && fs::exists(volume->source.input_file))
        input_path = volume->source.input_file;
    wxString title = _L("Select the new file");
    title += ":";
    wxFileDialog dialog(q, title, "", from_u8(input_path.filename().string()), file_wildcards(FT_MODEL), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() != wxID_OK)
        return;
    fs::path out_path = dialog.GetPath().ToUTF8().data();
    if (out_path.empty()) {
        MessageDialog dlg(q, _L("File for the replace wasn't selected"), _L("Error during replace"), wxOK | wxOK_DEFAULT | wxICON_WARNING);
        dlg.ShowModal();
        return;
    }
    if (!replace_volume_with_stl(object_idx, volume_idx, out_path, _L("Replace with STL")))
        return;
    // update 3D scene
    update();
    // new GLVolumes have been created at this point, so update their printable state
    for (size_t i = 0; i < model.objects.size(); ++i) {
        view3D->get_canvas3d()->update_instance_printable_state_for_object(i);
    }
}
References _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_MODEL, Slic3r::GUI::Selection::get_first_volume(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::is_wipe_tower(), Slic3r::GUI::Plater::model(), Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, Slic3r::GUI::GLGizmosManager::Undefined, Slic3r::GUI::Plater::update(), and Slic3r::GLVolume::volume_idx().
reset()
void Slic3r::GUI::Plater::priv::reset ()
{
    Plater::TakeSnapshot snapshot(q, _L("Reset Project"), UndoRedo::SnapshotType::ProjectSeparator);
  clear_warnings();
    set_project_filename(wxEmptyString);
    if (view3D->is_layers_editing_enabled())
        view3D->enable_layers_editing(false);
    reset_gcode_toolpaths();
    gcode_result.reset();
    view3D->get_canvas3d()->reset_sequential_print_clearance();
    m_worker.cancel_all();
    // Stop and reset the Print content.
    this->background_process.reset();
    model.clear_objects();
    update();
    // Delete object from Sidebar list. Do it after update, so that the GLScene selection is updated with the modified model.
    sidebar->obj_list()->delete_all_objects_from_list();
    object_list_changed();
    // The hiding of the slicing results, if shown, is not taken care by the background process, so we do it here
    this->sidebar->show_sliced_info_sizer(false);
    model.custom_gcode_per_print_z.gcodes.clear();
}
References _L, Slic3r::Model::clear_objects(), Slic3r::Model::custom_gcode_per_print_z, Slic3r::GUI::ObjectList::delete_all_objects_from_list(), Slic3r::CustomGCode::Info::gcodes, Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::UndoRedo::ProjectSeparator, Slic3r::GUI::Plater::reset_gcode_toolpaths(), Slic3r::GUI::Plater::set_project_filename(), Slic3r::GUI::Sidebar::show_sliced_info_sizer(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Plater::update().
reset_all_gizmos()
void Slic3r::GUI::Plater::priv::reset_all_gizmos ()
{
    view3D->get_canvas3d()->reset_all_gizmos();
}
reset_canvas_volumes()
void Slic3r::GUI::Plater::priv::reset_canvas_volumes ()
{
    if (view3D != nullptr)
        view3D->get_canvas3d()->reset_volumes();
    if (preview != nullptr)
        preview->get_canvas3d()->reset_volumes();
}
reset_gcode_toolpaths()
void Slic3r::GUI::Plater::priv::reset_gcode_toolpaths ()
{
    preview->get_canvas3d()->reset_gcode_toolpaths();
}
reset_project_dirty_after_save()
void Slic3r::GUI::Plater::priv::reset_project_dirty_after_save () inline
{ m_undo_redo_stack_main.mark_current_as_saved(); dirty_state.reset_after_save(); }
References Slic3r::GUI::ProjectDirtyStateManager::reset_after_save().
reset_project_dirty_initial_presets()
void Slic3r::GUI::Plater::priv::reset_project_dirty_initial_presets () inline
{ dirty_state.reset_initial_presets(); }
References Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets().
restart_background_process()
bool Slic3r::GUI::Plater::priv::restart_background_process (unsigned int state)
{
    if (!m_worker.is_idle()) {
        // Avoid a race condition
        return false;
    }
    if ( ! this->background_process.empty() &&
         (state & priv::UPDATE_BACKGROUND_PROCESS_INVALID) == 0 &&
         ( ((state & UPDATE_BACKGROUND_PROCESS_FORCE_RESTART) != 0 && ! this->background_process.finished()) ||
           (state & UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT) != 0 ||
           (state & UPDATE_BACKGROUND_PROCESS_RESTART) != 0 ) ) {
        // The print is valid and it can be started.
        if (this->background_process.start()) {
//            this->statusbar()->set_cancel_callback([this]() {
//                this->statusbar()->set_status_text(_L("Cancelling"));
//                this->background_process.stop();
//            });
      if (!show_warning_dialog)
        on_slicing_began();
            return true;
        }
    }
    return false;
}
References UPDATE_BACKGROUND_PROCESS_INVALID.
save_project_if_dirty()
int Slic3r::GUI::Plater::priv::save_project_if_dirty (const wxString & reason) inline
{
        int res = wxID_NO;
        if (dirty_state.is_dirty()) {
            MainFrame* mainframe = wxGetApp().mainframe;
            if (mainframe->can_save_as()) {
                wxString suggested_project_name;
                wxString project_name = suggested_project_name = get_project_filename(".3mf");
                if (suggested_project_name.IsEmpty()) {
                    fs::path output_file = get_export_file_path(FT_3MF);
                    suggested_project_name = output_file.empty() ? _L("Untitled") : from_u8(output_file.stem().string());
                }
                std::string act_key = "default_action_on_dirty_project";
                std::string act = wxGetApp().app_config->get(act_key);
                if (act.empty()) {
                    RichMessageDialog dialog(mainframe, reason + "\n" + format_wxstr(_L("Do you want to save the changes to \"%1%\"?"), suggested_project_name), wxString(SLIC3R_APP_NAME), wxYES_NO | wxCANCEL);
                    dialog.SetYesNoLabels(_L("Save"), _L("Discard"));
                    dialog.ShowCheckBox(_L("Remember my choice"));
                    res = dialog.ShowModal();
                    if (res != wxID_CANCEL)
                        if (dialog.IsCheckBoxChecked()) {
                            wxString preferences_item = _L("Ask for unsaved changes in project");
                            wxString msg =
                                _L("PrusaSlicer will remember your choice.") + "\n\n" +
                                _L("You will not be asked about it again, when: \n"
                                    "- Closing PrusaSlicer,\n"
                                    "- Loading or creating a new project") + "\n\n" +
                                format_wxstr(_L("Visit \"Preferences\" and check \"%1%\"\nto changes your choice."), preferences_item);
                            MessageDialog msg_dlg(mainframe, msg, _L("PrusaSlicer: Don't ask me again"), wxOK | wxCANCEL | wxICON_INFORMATION);
                            if (msg_dlg.ShowModal() == wxID_CANCEL)
                                return wxID_CANCEL;
                            get_app_config()->set(act_key, res == wxID_YES ? "1" : "0");
                        }
                }
                else
                    res = (act == "1") ? wxID_YES : wxID_NO;
                if (res == wxID_YES)
                    if (!mainframe->save_project_as(project_name)) {
                        // Return Cancel only, when we don't remember a choice for closing the application.
                        // Elsewhere it can causes an impossibility to close the application at all.
                        res = act.empty() ? wxID_CANCEL : wxID_NO;
                    }
            }
        }
        return res;
    }
References _L, Slic3r::GUI::MainFrame::can_save_as(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_3MF, Slic3r::GUI::get_app_config(), Slic3r::GUI::ProjectDirtyStateManager::is_dirty(), Slic3r::GUI::MainFrame::save_project_as(), and Slic3r::AppConfig::set().
scale_selection_to_fit_print_volume()
void Slic3r::GUI::Plater::priv::scale_selection_to_fit_print_volume ()
{
    this->view3D->get_canvas3d()->get_selection().scale_to_fit_print_volume(this->bed.build_volume());
}
schedule_background_process()
void Slic3r::GUI::Plater::priv::schedule_background_process ()
{
    delayed_error_message.clear();
    // Trigger the timer event after 0.5s
    this->background_process_timer.Start(500, wxTIMER_ONE_SHOT);
    // Notify the Canvas3D that something has changed, so it may invalidate some of the layer editing stuff.
    this->view3D->get_canvas3d()->set_config(this->config);
}
References Slic3r::GUI::Plater::config().
select_all()
void Slic3r::GUI::Plater::priv::select_all ()
{
    view3D->select_all();
    this->sidebar->obj_list()->update_selections();
}
References Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::ObjectList::update_selections().
select_next_view_3D()
void Slic3r::GUI::Plater::priv::select_next_view_3D ()
{
    if (current_panel == view3D)
        set_current_panel(preview);
    else if (current_panel == preview)
        set_current_panel(view3D);
}
select_view()
void Slic3r::GUI::Plater::priv::select_view (const std::string & direction)
{
    if (current_panel == view3D)
        view3D->select_view(direction);
    else if (current_panel == preview)
        preview->select_view(direction);
}
select_view_3D()
void Slic3r::GUI::Plater::priv::select_view_3D (const std::string & name)
{
    if (name == "3D")
        set_current_panel(view3D);
    else if (name == "Preview")
        set_current_panel(preview);
    apply_free_camera_correction(false);
}
selection_changed()
void Slic3r::GUI::Plater::priv::selection_changed ()
{
    // if the selection is not valid to allow for layer editing, we need to turn off the tool if it is running
    if (!layers_height_allowed() && view3D->is_layers_editing_enabled()) {
        SimpleEvent evt(EVT_GLTOOLBAR_LAYERSEDITING);
        on_action_layersediting(evt);
    }
    // forces a frame render to update the view (to avoid a missed update if, for example, the context menu appears)
    view3D->render();
}
set_bed_shape()
void Slic3r::GUI::Plater::priv::set_bed_shape (const Pointfs & shape, const double max_print_height, const std::string & custom_texture, const std::string & custom_model, bool force_as_custom = false)
{
    bool new_shape = bed.set_shape(shape, max_print_height, custom_texture, custom_model, force_as_custom);
    if (new_shape) {
        if (view3D) view3D->bed_shape_changed();
        if (preview) preview->bed_shape_changed();
    }
}
References Slic3r::max_print_height().
set_current_canvas_as_dirty()
void Slic3r::GUI::Plater::priv::set_current_canvas_as_dirty ()
{
    if (current_panel == view3D)
        view3D->set_as_dirty();
    else if (current_panel == preview)
        preview->set_as_dirty();
}
set_current_panel()
void Slic3r::GUI::Plater::priv::set_current_panel (wxPanel * panel)
{
    if (std::find(panels.begin(), panels.end(), panel) == panels.end())
        return;
#ifdef __WXMAC__
    bool force_render = (current_panel != nullptr);
#endif // __WXMAC__
    if (current_panel == panel)
        return;
    wxPanel* old_panel = current_panel;
    current_panel = panel;
    // to reduce flickering when changing view, first set as visible the new current panel
    for (wxPanel* p : panels) {
        if (p == current_panel) {
#ifdef __WXMAC__
            // On Mac we need also to force a render to avoid flickering when changing view
            if (force_render) {
                if (p == view3D)
                    dynamic_cast<View3D*>(p)->get_canvas3d()->render();
                else if (p == preview)
                    dynamic_cast<Preview*>(p)->get_canvas3d()->render();
            }
#endif // __WXMAC__
            p->Show();
        }
    }
    // then set to invisible the other
    for (wxPanel* p : panels) {
        if (p != current_panel)
            p->Hide();
    }
    panel_sizer->Layout();
    if (current_panel == view3D) {
        if (old_panel == preview)
            preview->get_canvas3d()->unbind_event_handlers();
        view3D->get_canvas3d()->bind_event_handlers();
        if (view3D->is_reload_delayed()) {
            // Delayed loading of the 3D scene.
            if (printer_technology == ptSLA) {
                // Update the SLAPrint from the current Model, so that the reload_scene()
                // pulls the correct data.
                update_restart_background_process(true, false);
            } else
                view3D->reload_scene(true);
        }
        // sets the canvas as dirty to force a render at the 1st idle event (wxWidgets IsShownOnScreen() is buggy and cannot be used reliably)
        view3D->set_as_dirty();
        // reset cached size to force a resize on next call to render() to keep imgui in synch with canvas size
        view3D->get_canvas3d()->reset_old_size();
        view_toolbar.select_item("3D");
        if (notification_manager != nullptr)
            notification_manager->set_in_preview(false);
    }
    else if (current_panel == preview) {
        if (old_panel == view3D)
            view3D->get_canvas3d()->unbind_event_handlers();
        preview->get_canvas3d()->bind_event_handlers();
        if (wxGetApp().is_editor()) {
            // see: Plater::priv::object_list_changed()
            // FIXME: it may be better to have a single function making this check and let it be called wherever needed
            bool export_in_progress = this->background_process.is_export_scheduled();
            bool model_fits = view3D->get_canvas3d()->check_volumes_outside_state() != ModelInstancePVS_Partly_Outside;
            if (!model.objects.empty() && !export_in_progress && model_fits) {
                preview->get_canvas3d()->init_gcode_viewer();
                q->reslice();
            }
            // keeps current gcode preview, if any
            preview->reload_print(true);
        }
        preview->set_as_dirty();
        // reset cached size to force a resize on next call to render() to keep imgui in synch with canvas size
        preview->get_canvas3d()->reset_old_size();
        view_toolbar.select_item("Preview");
        if (notification_manager != nullptr)
            notification_manager->set_in_preview(true);
    }
    current_panel->SetFocusFromKbd();
}
References Slic3r::GUI::Plater::model(), Slic3r::ModelInstancePVS_Partly_Outside, Slic3r::Model::objects, Slic3r::GUI::Plater::p, Slic3r::GUI::Plater::printer_technology(), Slic3r::ptSLA, and Slic3r::GUI::View3D::render().
set_preview_layers_slider_values_range()
void Slic3r::GUI::Plater::priv::set_preview_layers_slider_values_range (int bottom, int top)
{
    preview->set_layers_slider_values_range(bottom, top);
}
set_project_filename()
void Slic3r::GUI::Plater::priv::set_project_filename (const wxString & filename)
{
    boost::filesystem::path full_path = into_path(filename);
    boost::filesystem::path ext = full_path.extension();
    if (boost::iequals(ext.string(), ".amf")) {
        // Remove the first extension.
        full_path.replace_extension("");
        // It may be ".zip.amf".
        if (boost::iequals(full_path.extension().string(), ".zip"))
            // Remove the 2nd extension.
            full_path.replace_extension("");
    } else {
        // Remove just one extension.
        full_path.replace_extension("");
    }
    m_project_filename = from_path(full_path);
    wxGetApp().mainframe->update_title();
    const fs::path temp_path = wxStandardPaths::Get().GetTempDir().utf8_str().data();
    bool in_temp = (temp_path == full_path.parent_path().make_preferred());
    if (!filename.empty() && !in_temp)
        wxGetApp().mainframe->add_to_recent_projects(filename);
}
References Slic3r::GUI::from_path(), and Slic3r::GUI::into_path().
show_action_buttons()
void Slic3r::GUI::Plater::priv::show_action_buttons (const bool is_ready_to_slice) const
{
  // Cache this value, so that the callbacks from the RemovableDriveManager may repeat that value when calling show_action_buttons().
    this->ready_to_slice = ready_to_slice_;
    wxWindowUpdateLocker noUpdater(sidebar);
    DynamicPrintConfig* selected_printer_config = wxGetApp().preset_bundle->physical_printers.get_selected_printer_config();
    const auto print_host_opt = selected_printer_config ? selected_printer_config->option<ConfigOptionString>("print_host") : nullptr;
    const bool send_gcode_shown = print_host_opt != nullptr && !print_host_opt->value.empty();
    // when a background processing is ON, export_btn and/or send_btn are showing
    if (get_config_bool("background_processing"))
    {
      RemovableDriveManager::RemovableDrivesStatus removable_media_status = wxGetApp().removable_drive_manager()->status();
    if (sidebar->show_reslice(false) |
      sidebar->show_export(true) |
      sidebar->show_send(send_gcode_shown) |
      sidebar->show_export_removable(removable_media_status.has_removable_drives))
//      sidebar->show_eject(removable_media_status.has_eject))
            sidebar->Layout();
    }
    else
    {
      RemovableDriveManager::RemovableDrivesStatus removable_media_status;
      if (! ready_to_slice)
        removable_media_status = wxGetApp().removable_drive_manager()->status();
        if (sidebar->show_reslice(ready_to_slice) |
            sidebar->show_export(!ready_to_slice) |
            sidebar->show_send(send_gcode_shown && !ready_to_slice) |
      sidebar->show_export_removable(!ready_to_slice && removable_media_status.has_removable_drives))
//            sidebar->show_eject(!ready_to_slice && removable_media_status.has_eject))
            sidebar->Layout();
    }
}
References Slic3r::GUI::RemovableDriveManager::RemovableDrivesStatus::has_removable_drives, Slic3r::ConfigBase::option(), Slic3r::GUI::Sidebar::show_export(), Slic3r::GUI::Sidebar::show_export_removable(), Slic3r::GUI::Sidebar::show_reslice(), Slic3r::GUI::Sidebar::show_send(), and Slic3r::GUI::Plater::sidebar().
show_delayed_error_message()
void Slic3r::GUI::Plater::priv::show_delayed_error_message () inline
{
    if (!this->delayed_error_message.empty()) {
      std::string msg = std::move(this->delayed_error_message);
      this->delayed_error_message.clear();
      GUI::show_error(this->q, msg);
    }
  }
show_legend()
void Slic3r::GUI::Plater::priv::show_legend (bool show) inline
{ if (current_panel == preview) preview->get_canvas3d()->show_legend(show); }
References Slic3r::GUI::Preview::get_canvas3d(), and Slic3r::GUI::GLCanvas3D::show_legend().
show_view3D_labels()
void Slic3r::GUI::Plater::priv::show_view3D_labels (bool show) inline
{ if (current_panel == view3D) view3D->get_canvas3d()->show_labels(show); }
References Slic3r::GUI::View3D::get_canvas3d(), and Slic3r::GUI::GLCanvas3D::show_labels().
split_object()
void Slic3r::GUI::Plater::priv::split_object ()
{
    int obj_idx = get_selected_object_idx();
    if (obj_idx == -1)
        return;
    // we clone model object because split_object() adds the split volumes
    // into the same model object, thus causing duplicates when we call load_model_objects()
    Model new_model = model;
    ModelObject* current_model_object = new_model.objects[obj_idx];
    // Before splitting object we have to remove all custom supports, seams, and multimaterial painting.
    wxGetApp().plater()->clear_before_change_mesh(obj_idx, _u8L("Custom supports, seams and multimaterial painting were "
                                                                "removed after splitting the object."));
    wxBusyCursor wait;
    ModelObjectPtrs new_objects;
    current_model_object->split(&new_objects);
    if (new_objects.size() == 1)
        // #ysFIXME use notification
        Slic3r::GUI::warning_catcher(q, _L("The selected object couldn't be split because it contains only one solid part."));
    else
    {
        // If we splited object which is contain some parts/modifiers then all non-solid parts (modifiers) were deleted
        if (current_model_object->volumes.size() > 1 && current_model_object->volumes.size() != new_objects.size())
            notification_manager->push_notification(NotificationType::CustomNotification,
                NotificationManager::NotificationLevel::PrintInfoNotificationLevel,
                _u8L("All non-solid parts (modifiers) were deleted"));
        Plater::TakeSnapshot snapshot(q, _L("Split to Objects"));
        remove(obj_idx);
        // load all model objects at once, otherwise the plate would be rearranged after each one
        // causing original positions not to be kept
        std::vector<size_t> idxs = load_model_objects(new_objects);
        // clear previosli selection
        get_selection().clear();
        // select newly added objects
        for (size_t idx : idxs)
        {
            get_selection().add_object((unsigned int)idx, false);
            // update printable state for new volumes on canvas3D
            q->canvas3D()->update_instance_printable_state_for_object(idx);
        }
    }
}
References _L, _u8L, Slic3r::GUI::Selection::add_object(), Slic3r::GUI::Selection::clear(), Slic3r::GUI::CustomNotification, Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::NotificationManager::PrintInfoNotificationLevel, Slic3r::GUI::Plater::remove(), Slic3r::ModelObject::split(), Slic3r::ModelObject::volumes, and Slic3r::GUI::warning_catcher().
split_volume()
void Slic3r::GUI::Plater::priv::split_volume ()
{
    wxGetApp().obj_list()->split();
}
suppress_snapshots()
void Slic3r::GUI::Plater::priv::suppress_snapshots () inline
{ m_prevent_snapshots++; }
take_snapshot() [1/2]
void Slic3r::GUI::Plater::priv::take_snapshot (const std::string & snapshot_name, UndoRedo::SnapshotType snapshot_type = UndoRedo::SnapshotType::Action)
{
    if (m_prevent_snapshots > 0)
        return;
    assert(m_prevent_snapshots >= 0);
    UndoRedo::SnapshotData snapshot_data;
    snapshot_data.snapshot_type      = snapshot_type;
    snapshot_data.printer_technology = this->printer_technology;
    if (this->view3D->is_layers_editing_enabled())
        snapshot_data.flags |= UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE;
    if (this->sidebar->obj_list()->is_selected(itSettings)) {
        snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR;
        snapshot_data.layer_range_idx = this->sidebar->obj_list()->get_selected_layers_range_idx();
    }
    else if (this->sidebar->obj_list()->is_selected(itLayer)) {
        snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR;
        snapshot_data.layer_range_idx = this->sidebar->obj_list()->get_selected_layers_range_idx();
    }
    else if (this->sidebar->obj_list()->is_selected(itLayerRoot))
        snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR;
    // If SLA gizmo is active, ask it if it wants to trigger support generation
    // on loading this snapshot.
    if (view3D->get_canvas3d()->get_gizmos_manager().wants_reslice_supports_on_undo())
        snapshot_data.flags |= UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS;
    //FIXME updating the Wipe tower config values at the ModelWipeTower from the Print config.
    // This is a workaround until we refactor the Wipe Tower position / orientation to live solely inside the Model, not in the Print config.
    if (this->printer_technology == ptFFF) {
        const DynamicPrintConfig &config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
        model.wipe_tower.position = Vec2d(config.opt_float("wipe_tower_x"), config.opt_float("wipe_tower_y"));
        model.wipe_tower.rotation = config.opt_float("wipe_tower_rotation_angle");
    }
    const GLGizmosManager& gizmos = view3D->get_canvas3d()->get_gizmos_manager();
    if (snapshot_type == UndoRedo::SnapshotType::ProjectSeparator && get_config_bool("clear_undo_redo_stack_on_new_project"))
        this->undo_redo_stack().clear();
    this->undo_redo_stack().take_snapshot(snapshot_name, model, view3D->get_canvas3d()->get_selection(), gizmos, snapshot_data);
    if (snapshot_type == UndoRedo::SnapshotType::LeavingGizmoWithAction) {
        // Filter all but the last UndoRedo::SnapshotType::GizmoAction in a row between the last UndoRedo::SnapshotType::EnteringGizmo and UndoRedo::SnapshotType::LeavingGizmoWithAction.
        // The remaining snapshot will be renamed to a more generic name,
        // depending on what gizmo is being left.
        assert(gizmos.get_current() != nullptr);
        std::string new_name = gizmos.get_current()->get_action_snapshot_name();
        this->undo_redo_stack().reduce_noisy_snapshots(new_name);
    } else if (snapshot_type == UndoRedo::SnapshotType::ProjectSeparator) {
        // Reset the "dirty project" flag.
        m_undo_redo_stack_main.mark_current_as_saved();
    }
    this->undo_redo_stack().release_least_recently_used();
    dirty_state.update_from_undo_redo_stack(m_undo_redo_stack_main.project_modified());
    // Save the last active preset name of a particular printer technology.
    ((this->printer_technology == ptFFF) ? m_last_fff_printer_profile_name : m_last_sla_printer_profile_name) = wxGetApp().preset_bundle->printers.get_selected_preset_name();
    BOOST_LOG_TRIVIAL(info) << "Undo / Redo snapshot taken: " << snapshot_name << ", Undo / Redo stack memory: " << Slic3r::format_memsize_MB(this->undo_redo_stack().memsize()) << log_memory_info();
}
References Slic3r::GUI::Plater::config(), Slic3r::UndoRedo::SnapshotData::flags, Slic3r::format_memsize_MB(), Slic3r::GUI::GLGizmoBase::get_action_snapshot_name(), Slic3r::GUI::GLGizmosManager::get_current(), Slic3r::GUI::ObjectList::get_selected_layers_range_idx(), Slic3r::GUI::ObjectList::is_selected(), Slic3r::GUI::itLayer, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itSettings, Slic3r::UndoRedo::SnapshotData::layer_range_idx, Slic3r::UndoRedo::LeavingGizmoWithAction, Slic3r::log_memory_info(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::ConfigBase::opt_float(), Slic3r::ModelWipeTower::position, Slic3r::GUI::Plater::printer_technology(), Slic3r::UndoRedo::SnapshotData::printer_technology, Slic3r::UndoRedo::ProjectSeparator, Slic3r::ptFFF, Slic3r::UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS, Slic3r::ModelWipeTower::rotation, Slic3r::UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR, Slic3r::UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR, Slic3r::UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR, Slic3r::GUI::Plater::sidebar(), Slic3r::UndoRedo::SnapshotData::snapshot_type, Slic3r::UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE, and Slic3r::Model::wipe_tower.
take_snapshot() [2/2]
void Slic3r::GUI::Plater::priv::take_snapshot (const wxString & snapshot_name, UndoRedo::SnapshotType snapshot_type = UndoRedo::SnapshotType::Action) inline
        { this->take_snapshot(std::string(snapshot_name.ToUTF8().data()), snapshot_type); }
unbind_canvas_event_handlers()
void Slic3r::GUI::Plater::priv::unbind_canvas_event_handlers ()
{
    if (view3D != nullptr)
        view3D->get_canvas3d()->unbind_event_handlers();
    if (preview != nullptr)
        preview->get_canvas3d()->unbind_event_handlers();
}
undo()
void Slic3r::GUI::Plater::priv::undo ()
{
    const std::vector<UndoRedo::Snapshot> &snapshots = this->undo_redo_stack().snapshots();
    auto it_current = std::lower_bound(snapshots.begin(), snapshots.end(), UndoRedo::Snapshot(this->undo_redo_stack().active_snapshot_time()));
    if (-- it_current != snapshots.begin())
        this->undo_redo_to(it_current);
}
undo_redo_stack()
Slic3r::UndoRedo::Stack & Slic3r::GUI::Plater::priv::undo_redo_stack () inline
{ assert(m_undo_redo_stack_active != nullptr); return *m_undo_redo_stack_active; }
undo_redo_stack_main()
Slic3r::UndoRedo::Stack & Slic3r::GUI::Plater::priv::undo_redo_stack_main () inline
{ return m_undo_redo_stack_main; }
undo_redo_to() [1/2]
void Slic3r::GUI::Plater::priv::undo_redo_to (size_t time_to_load)
{
    const std::vector<UndoRedo::Snapshot> &snapshots = this->undo_redo_stack().snapshots();
    auto it_current = std::lower_bound(snapshots.begin(), snapshots.end(), UndoRedo::Snapshot(time_to_load));
    assert(it_current != snapshots.end());
    this->undo_redo_to(it_current);
}
undo_redo_to() [2/2]
void Slic3r::GUI::Plater::priv::undo_redo_to (std::vector< UndoRedo::Snapshot >::const_iterator it_snapshot) private
{
    // Make sure that no updating function calls take_snapshot until we are done.
    SuppressSnapshots snapshot_supressor(q);
    bool        temp_snapshot_was_taken   = this->undo_redo_stack().temp_snapshot_active();
    PrinterTechnology   new_printer_technology    = it_snapshot->snapshot_data.printer_technology;
    bool        printer_technology_changed  = this->printer_technology != new_printer_technology;
    if (printer_technology_changed) {
        // Switching the printer technology when jumping forwards / backwards in time. Switch to the last active printer profile of the other type.
        std::string s_pt = (it_snapshot->snapshot_data.printer_technology == ptFFF) ? "FFF" : "SLA";
        if (!wxGetApp().check_and_save_current_preset_changes(_L("Undo / Redo is processing"),
//            format_wxstr(_L("%1% printer was active at the time the target Undo / Redo snapshot was taken. Switching to %1% printer requires reloading of %1% presets."), s_pt)))
            format_wxstr(_L("Switching the printer technology from %1% to %2%.\n"
                            "Some %1% presets were modified, which will be lost after switching the printer technology."), s_pt =="FFF" ? "SLA" : "FFF", s_pt), false))
            // Don't switch the profiles.
            return;
    }
    // Save the last active preset name of a particular printer technology.
    ((this->printer_technology == ptFFF) ? m_last_fff_printer_profile_name : m_last_sla_printer_profile_name) = wxGetApp().preset_bundle->printers.get_selected_preset_name();
    //FIXME updating the Wipe tower config values at the ModelWipeTower from the Print config.
    // This is a workaround until we refactor the Wipe Tower position / orientation to live solely inside the Model, not in the Print config.
    if (this->printer_technology == ptFFF) {
        const DynamicPrintConfig &config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
                model.wipe_tower.position = Vec2d(config.opt_float("wipe_tower_x"), config.opt_float("wipe_tower_y"));
                model.wipe_tower.rotation = config.opt_float("wipe_tower_rotation_angle");
    }
    const int layer_range_idx = it_snapshot->snapshot_data.layer_range_idx;
    // Flags made of Snapshot::Flags enum values.
    unsigned int new_flags = it_snapshot->snapshot_data.flags;
    UndoRedo::SnapshotData top_snapshot_data;
    top_snapshot_data.printer_technology = this->printer_technology;
    if (this->view3D->is_layers_editing_enabled())
        top_snapshot_data.flags |= UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE;
    if (this->sidebar->obj_list()->is_selected(itSettings)) {
        top_snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR;
        top_snapshot_data.layer_range_idx = this->sidebar->obj_list()->get_selected_layers_range_idx();
    }
    else if (this->sidebar->obj_list()->is_selected(itLayer)) {
        top_snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR;
        top_snapshot_data.layer_range_idx = this->sidebar->obj_list()->get_selected_layers_range_idx();
    }
    else if (this->sidebar->obj_list()->is_selected(itLayerRoot))
        top_snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR;
    bool       new_variable_layer_editing_active = (new_flags & UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE) != 0;
    bool         new_selected_settings_on_sidebar  = (new_flags & UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR) != 0;
    bool         new_selected_layer_on_sidebar     = (new_flags & UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR) != 0;
    bool         new_selected_layerroot_on_sidebar = (new_flags & UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR) != 0;
    if (this->view3D->get_canvas3d()->get_gizmos_manager().wants_reslice_supports_on_undo())
        top_snapshot_data.flags |= UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS;
    // Disable layer editing before the Undo / Redo jump.
    if (!new_variable_layer_editing_active && view3D->is_layers_editing_enabled())
        view3D->get_canvas3d()->force_main_toolbar_left_action(view3D->get_canvas3d()->get_main_toolbar_item_id("layersediting"));
    // Make a copy of the snapshot, undo/redo could invalidate the iterator
    const UndoRedo::Snapshot snapshot_copy = *it_snapshot;
    // Do the jump in time.
    if (it_snapshot->timestamp < this->undo_redo_stack().active_snapshot_time() ?
        this->undo_redo_stack().undo(model, this->view3D->get_canvas3d()->get_selection(), this->view3D->get_canvas3d()->get_gizmos_manager(), top_snapshot_data, it_snapshot->timestamp) :
        this->undo_redo_stack().redo(model, this->view3D->get_canvas3d()->get_gizmos_manager(), it_snapshot->timestamp)) {
        if (printer_technology_changed) {
            // Switch to the other printer technology. Switch to the last printer active for that particular technology.
            AppConfig *app_config = wxGetApp().app_config;
            app_config->set("presets", "printer", (new_printer_technology == ptFFF) ? m_last_fff_printer_profile_name : m_last_sla_printer_profile_name);
            //FIXME Why are we reloading the whole preset bundle here? Please document. This is fishy and it is unnecessarily expensive.
            // Anyways, don't report any config value substitutions, they have been already reported to the user at application start up.
            wxGetApp().preset_bundle->load_presets(*app_config, ForwardCompatibilitySubstitutionRule::EnableSilent);
      // load_current_presets() calls Tab::load_current_preset() -> TabPrint::update() -> Object_list::update_and_show_object_settings_item(),
      // but the Object list still keeps pointer to the old Model. Avoid a crash by removing selection first.
      this->sidebar->obj_list()->unselect_objects();
            // Load the currently selected preset into the GUI, update the preset selection box.
            // This also switches the printer technology based on the printer technology of the active printer profile.
            wxGetApp().load_current_presets();
        }
        //FIXME updating the Print config from the Wipe tower config values at the ModelWipeTower.
        // This is a workaround until we refactor the Wipe Tower position / orientation to live solely inside the Model, not in the Print config.
        if (this->printer_technology == ptFFF) {
            const DynamicPrintConfig &current_config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
            Vec2d             current_position(current_config.opt_float("wipe_tower_x"), current_config.opt_float("wipe_tower_y"));
            double            current_rotation = current_config.opt_float("wipe_tower_rotation_angle");
            if (current_position != model.wipe_tower.position || current_rotation != model.wipe_tower.rotation) {
                DynamicPrintConfig new_config;
                new_config.set_key_value("wipe_tower_x", new ConfigOptionFloat(model.wipe_tower.position.x()));
                new_config.set_key_value("wipe_tower_y", new ConfigOptionFloat(model.wipe_tower.position.y()));
                new_config.set_key_value("wipe_tower_rotation_angle", new ConfigOptionFloat(model.wipe_tower.rotation));
                Tab *tab_print = wxGetApp().get_tab(Preset::TYPE_PRINT);
                tab_print->load_config(new_config);
                tab_print->update_dirty();
            }
        }
        // set selection mode for ObjectList on sidebar
        this->sidebar->obj_list()->set_selection_mode(new_selected_settings_on_sidebar  ? ObjectList::SELECTION_MODE::smSettings :
                                                      new_selected_layer_on_sidebar     ? ObjectList::SELECTION_MODE::smLayer :
                                                      new_selected_layerroot_on_sidebar ? ObjectList::SELECTION_MODE::smLayerRoot :
                                                                                          ObjectList::SELECTION_MODE::smUndef);
        if (new_selected_settings_on_sidebar || new_selected_layer_on_sidebar)
            this->sidebar->obj_list()->set_selected_layers_range_idx(layer_range_idx);
        this->update_after_undo_redo(snapshot_copy, temp_snapshot_was_taken);
        // Enable layer editing after the Undo / Redo jump.
        if (! view3D->is_layers_editing_enabled() && this->layers_height_allowed() && new_variable_layer_editing_active)
            view3D->get_canvas3d()->force_main_toolbar_left_action(view3D->get_canvas3d()->get_main_toolbar_item_id("layersediting"));
    }
    dirty_state.update_from_undo_redo_stack(m_undo_redo_stack_main.project_modified());
}
References _L, Slic3r::GUI::Plater::config(), Slic3r::EnableSilent, Slic3r::UndoRedo::SnapshotData::flags, Slic3r::GUI::format_wxstr(), Slic3r::GUI::ObjectList::get_selected_layers_range_idx(), Slic3r::GUI::ObjectList::is_selected(), Slic3r::GUI::itLayer, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itSettings, Slic3r::UndoRedo::SnapshotData::layer_range_idx, Slic3r::GUI::Tab::load_config(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::ConfigBase::opt_float(), Slic3r::ModelWipeTower::position, Slic3r::GUI::Plater::printer_technology(), Slic3r::UndoRedo::SnapshotData::printer_technology, Slic3r::ptFFF, Slic3r::UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS, Slic3r::ModelWipeTower::rotation, Slic3r::UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR, Slic3r::UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR, Slic3r::UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR, Slic3r::AppConfig::set(), Slic3r::DynamicConfig::set_key_value(), Slic3r::GUI::ObjectList::set_selected_layers_range_idx(), Slic3r::GUI::ObjectList::set_selection_mode(), Slic3r::GUI::Plater::sidebar(), Slic3r::GUI::ObjectList::smLayer, Slic3r::GUI::ObjectList::smLayerRoot, Slic3r::GUI::ObjectList::smSettings, Slic3r::GUI::ObjectList::smUndef, Slic3r::ObjectBase::timestamp(), Slic3r::Preset::TYPE_PRINT, Slic3r::GUI::ObjectList::unselect_objects(), Slic3r::GUI::Tab::update_dirty(), Slic3r::UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE, and Slic3r::Model::wipe_tower.
update()
void Slic3r::GUI::Plater::priv::update (unsigned int flags = 0)
{
    // the following line, when enabled, causes flickering on NVIDIA graphics cards
//    wxWindowUpdateLocker freeze_guard(q);
    if (get_config_bool("autocenter"))
        model.center_instances_around_point(this->bed.build_volume().bed_center());
    unsigned int update_status = 0;
    const bool force_background_processing_restart = this->printer_technology == ptSLA || (flags & (unsigned int)UpdateParams::FORCE_BACKGROUND_PROCESSING_UPDATE);
    if (force_background_processing_restart)
        // Update the SLAPrint from the current Model, so that the reload_scene()
        // pulls the correct data.
        update_status = this->update_background_process(false, flags & (unsigned int)UpdateParams::POSTPONE_VALIDATION_ERROR_MESSAGE);
    this->view3D->reload_scene(false, flags & (unsigned int)UpdateParams::FORCE_FULL_SCREEN_REFRESH);
    this->preview->reload_print();
    if (force_background_processing_restart)
        this->restart_background_process(update_status);
    else
        this->schedule_background_process();
    if (get_config_bool("autocenter") && this->sidebar->obj_manipul()->IsShown())
        this->sidebar->obj_manipul()->UpdateAndShow(true);
}
References Slic3r::Model::center_instances_around_point(), Slic3r::GUI::Plater::FORCE_BACKGROUND_PROCESSING_UPDATE, Slic3r::GUI::Plater::FORCE_FULL_SCREEN_REFRESH, Slic3r::GUI::ObjectManipulation::IsShown(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_manipul(), Slic3r::GUI::Plater::POSTPONE_VALIDATION_ERROR_MESSAGE, Slic3r::GUI::Plater::printer_technology(), Slic3r::ptSLA, Slic3r::GUI::Plater::schedule_background_process(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::ObjectManipulation::UpdateAndShow().
Referenced by reload_from_disk().
update_after_undo_redo()
void Slic3r::GUI::Plater::priv::update_after_undo_redo (const UndoRedo::Snapshot & snapshot, bool temp_snapshot_was_taken = false) private
{
    this->view3D->get_canvas3d()->get_selection().clear();
    // Update volumes from the deserializd model, always stop / update the background processing (for both the SLA and FFF technologies).
    this->update((unsigned int)UpdateParams::FORCE_BACKGROUND_PROCESSING_UPDATE | (unsigned int)UpdateParams::POSTPONE_VALIDATION_ERROR_MESSAGE);
    // Release old snapshots if the memory allocated is excessive. This may remove the top most snapshot if jumping to the very first snapshot.
    //if (temp_snapshot_was_taken)
    // Release the old snapshots always, as it may have happened, that some of the triangle meshes got deserialized from the snapshot, while some
    // triangle meshes may have gotten released from the scene or the background processing, therefore now being calculated into the Undo / Redo stack size.
        this->undo_redo_stack().release_least_recently_used();
    //YS_FIXME update obj_list from the deserialized model (maybe store ObjectIDs into the tree?) (no selections at this point of time)
    this->view3D->get_canvas3d()->get_selection().set_deserialized(GUI::Selection::EMode(this->undo_redo_stack().selection_deserialized().mode), this->undo_redo_stack().selection_deserialized().volumes_and_instances);
    this->view3D->get_canvas3d()->get_gizmos_manager().update_after_undo_redo(snapshot);
    wxGetApp().obj_list()->update_after_undo_redo();
    if (wxGetApp().get_mode() == comSimple && model_has_advanced_features(this->model)) {
        // If the user jumped to a snapshot that require user interface with advanced features, switch to the advanced mode without asking.
        // There is a little risk of surprising the user, as he already must have had the advanced or expert mode active for such a snapshot to be taken.
        if (wxGetApp().save_mode(comAdvanced))
            view3D->set_as_dirty();
    }
  // this->update() above was called with POSTPONE_VALIDATION_ERROR_MESSAGE, so that if an error message was generated when updating the back end, it would not open immediately,
  // but it would be saved to be show later. Let's do it now. We do not want to display the message box earlier, because on Windows & OSX the message box takes over the message
  // queue pump, which in turn executes the rendering function before a full update after the Undo / Redo jump.
  this->show_delayed_error_message();
    //FIXME what about the state of the manipulators?
    //FIXME what about the focus? Cursor in the side panel?
    BOOST_LOG_TRIVIAL(info) << "Undo / Redo snapshot reloaded. Undo / Redo stack memory: " << Slic3r::format_memsize_MB(this->undo_redo_stack().memsize()) << log_memory_info();
}
References Slic3r::comAdvanced, Slic3r::comSimple, Slic3r::GUI::Plater::FORCE_BACKGROUND_PROCESSING_UPDATE, Slic3r::format_memsize_MB(), Slic3r::log_memory_info(), Slic3r::GUI::Plater::model(), Slic3r::model_has_advanced_features(), Slic3r::GUI::Plater::POSTPONE_VALIDATION_ERROR_MESSAGE, and Slic3r::GUI::Plater::update().
update_background_process()
unsigned int Slic3r::GUI::Plater::priv::update_background_process (bool force_validation = false, bool postpone_error_messages = false)
{
    // bitmap of enum UpdateBackgroundProcessReturnState
    unsigned int return_state = 0;
    // If the update_background_process() was not called by the timer, kill the timer,
    // so the update_restart_background_process() will not be called again in vain.
    background_process_timer.Stop();
    // Update the "out of print bed" state of ModelInstances.
    update_print_volume_state();
    // Apply new config to the possibly running background task.
    bool               was_running = background_process.running();
    Print::ApplyStatus invalidated = background_process.apply(q->model(), wxGetApp().preset_bundle->full_config());
    // Just redraw the 3D canvas without reloading the scene to consume the update of the layer height profile.
    if (view3D->is_layers_editing_enabled())
        view3D->get_wxglcanvas()->Refresh();
    if (invalidated == Print::APPLY_STATUS_CHANGED || background_process.empty())
        view3D->get_canvas3d()->reset_sequential_print_clearance();
    if (invalidated == Print::APPLY_STATUS_INVALIDATED) {
        // Some previously calculated data on the Print was invalidated.
        // Hide the slicing results, as the current slicing status is no more valid.
        sidebar->show_sliced_info_sizer(false);
        // Reset preview canvases. If the print has been invalidated, the preview canvases will be cleared.
        // Otherwise they will be just refreshed.
        if (preview != nullptr) {
            // If the preview is not visible, the following line just invalidates the preview,
            // but the G-code paths or SLA preview are calculated first once the preview is made visible.
            reset_gcode_toolpaths();
            preview->reload_print();
        }
        // In FDM mode, we need to reload the 3D scene because of the wipe tower preview box.
        // In SLA mode, we need to reload the 3D scene every time to show the support structures.
        if (printer_technology == ptSLA || (printer_technology == ptFFF && config->opt_bool("wipe_tower")))
            return_state |= UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE;
        notification_manager->set_slicing_progress_hidden();
    }
    if ((invalidated != Print::APPLY_STATUS_UNCHANGED || force_validation) && ! background_process.empty()) {
    // The delayed error message is no more valid.
    delayed_error_message.clear();
    // The state of the Print changed, and it is non-zero. Let's validate it and give the user feedback on errors.
        std::vector<std::string> warnings;
        std::string err = background_process.validate(&warnings);
        if (err.empty()) {
      notification_manager->set_all_slicing_errors_gray(true);
            notification_manager->close_notification_of_type(NotificationType::ValidateError);
            if (invalidated != Print::APPLY_STATUS_UNCHANGED && background_processing_enabled())
                return_state |= UPDATE_BACKGROUND_PROCESS_RESTART;
            // Pass a warning from validation and either show a notification,
            // or hide the old one.
            process_validation_warning(warnings);
            if (printer_technology == ptFFF) {
                GLCanvas3D* canvas = view3D->get_canvas3d();
                canvas->reset_sequential_print_clearance();
                canvas->set_as_dirty();
                canvas->request_extra_frame();
            }
        }
        else {
            // The print is not valid.
            // Show error as notification.
            notification_manager->push_validate_error_notification(err);
            return_state |= UPDATE_BACKGROUND_PROCESS_INVALID;
            if (printer_technology == ptFFF) {
                GLCanvas3D* canvas = view3D->get_canvas3d();
                if (canvas->is_sequential_print_clearance_empty() || canvas->is_sequential_print_clearance_evaluating()) {
                    GLCanvas3D::ContoursList contours;
                    contours.contours = background_process.fff_print()->get_sequential_print_clearance_contours();
                    canvas->set_sequential_print_clearance_contours(contours, true);
                    canvas->set_as_dirty();
                    canvas->request_extra_frame();
                }
            }
        }
    }
    else {
        if (invalidated == Print::APPLY_STATUS_UNCHANGED && !background_process.empty()) {
            if (printer_technology == ptFFF) {
                // Object manipulation with gizmos may end up in a null transformation.
                // In this case, we need to trigger the completion of the sequential print clearance contours evaluation
                GLCanvas3D* canvas = view3D->get_canvas3d();
                if (canvas->is_sequential_print_clearance_evaluating()) {
                    GLCanvas3D::ContoursList contours;
                    contours.contours = background_process.fff_print()->get_sequential_print_clearance_contours();
                    canvas->set_sequential_print_clearance_contours(contours, true);
                    canvas->set_as_dirty();
                    canvas->request_extra_frame();
                }
            }
            std::vector<std::string> warnings;
            std::string err = background_process.validate(&warnings);
            if (!err.empty())
                return return_state;
        }
        if (! this->delayed_error_message.empty())
      // Reusing the old state.
        return_state |= UPDATE_BACKGROUND_PROCESS_INVALID;
    }
  //actualizate warnings
  if (invalidated != Print::APPLY_STATUS_UNCHANGED || background_process.empty()) {
        if (background_process.empty())
            process_validation_warning(std::vector<std::string>());
    actualize_slicing_warnings(*this->background_process.current_print());
        actualize_object_warnings(*this->background_process.current_print());
    show_warning_dialog = false;
    process_completed_with_error = false;
  }
    if (invalidated != Print::APPLY_STATUS_UNCHANGED && was_running && ! this->background_process.running() &&
        (return_state & UPDATE_BACKGROUND_PROCESS_RESTART) == 0) {
        // The background processing was killed and it will not be restarted.
        // Post the "canceled" callback message, so that it will be processed after any possible pending status bar update messages.
        wxQueueEvent(GUI::wxGetApp().mainframe->m_plater, new SlicingProcessCompletedEvent(EVT_PROCESS_COMPLETED, 0, SlicingProcessCompletedEvent::Cancelled, std::exception_ptr{}));
    }
    if ((return_state & UPDATE_BACKGROUND_PROCESS_INVALID) != 0)
    {
        // Validation of the background data failed.
        const wxString invalid_str = _L("Invalid data");
        for (auto btn : {ActionButtonType::abReslice, ActionButtonType::abSendGCode, ActionButtonType::abExport})
            sidebar->set_btn_label(btn, invalid_str);
        process_completed_with_error = true;
    }
    else
    {
        // Background data is valid.
//        if ((return_state & UPDATE_BACKGROUND_PROCESS_RESTART) != 0 ||
//            (return_state & UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE) != 0)
//            this->statusbar()->set_status_text(_L("Ready to slice"));
        if ((return_state & UPDATE_BACKGROUND_PROCESS_RESTART) != 0 ||
            (return_state & UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE) != 0 )
            notification_manager->set_slicing_progress_hidden();
        sidebar->set_btn_label(ActionButtonType::abExport, _(label_btn_export));
        sidebar->set_btn_label(ActionButtonType::abSendGCode, _(label_btn_send));
        dirty_state.update_from_preview();
        const wxString slice_string = background_process.running() && wxGetApp().get_mode() == comSimple ?
                                      _L("Slicing") + dots : _L("Slice now");
        sidebar->set_btn_label(ActionButtonType::abReslice, slice_string);
        if (background_process.finished())
            show_action_buttons(false);
        else if (!background_process.empty() &&
                 !background_process.running()) /* Do not update buttons if background process is running
                                                 * This condition is important for SLA mode especially,
                                                 * when this function is called several times during calculations
                                                 * */
            show_action_buttons(true);
    }
    return return_state;
}
References _, _L, Slic3r::GUI::abExport, Slic3r::GUI::abReslice, Slic3r::GUI::abSendGCode, Slic3r::PrintBase::APPLY_STATUS_CHANGED, Slic3r::PrintBase::APPLY_STATUS_INVALIDATED, Slic3r::PrintBase::APPLY_STATUS_UNCHANGED, Slic3r::SlicingProcessCompletedEvent::Cancelled, Slic3r::comSimple, Slic3r::GUI::Plater::config(), Slic3r::GUI::GLCanvas3D::ContoursList::contours, Slic3r::GUI::dots(), Slic3r::GUI::GLCanvas3D::is_sequential_print_clearance_empty(), Slic3r::GUI::GLCanvas3D::is_sequential_print_clearance_evaluating(), Slic3r::ConfigBase::opt_bool(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::GUI::GLCanvas3D::request_extra_frame(), Slic3r::GUI::Plater::reset_gcode_toolpaths(), Slic3r::GUI::GLCanvas3D::reset_sequential_print_clearance(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::Sidebar::set_btn_label(), Slic3r::GUI::GLCanvas3D::set_sequential_print_clearance_contours(), Slic3r::GUI::Plater::show_action_buttons(), Slic3r::GUI::Sidebar::show_sliced_info_sizer(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::ValidateError.
update_fff_scene()
void Slic3r::GUI::Plater::priv::update_fff_scene () private
{
    if (this->preview != nullptr)
        this->preview->reload_print();
    // In case this was MM print, wipe tower bounding box on 3D tab might need redrawing with exact depth:
    view3D->reload_scene(true);
}
update_main_toolbar_tooltips()
void Slic3r::GUI::Plater::priv::update_main_toolbar_tooltips ()
{
    view3D->get_canvas3d()->update_tooltip_for_settings_item_in_main_toolbar();
}
update_preview_moves_slider()
void Slic3r::GUI::Plater::priv::update_preview_moves_slider ()
{
    preview->update_moves_slider();
}
update_print_volume_state()
void Slic3r::GUI::Plater::priv::update_print_volume_state ()
{
    this->q->model().update_print_volume_state(this->bed.build_volume());
}
update_project_dirty_from_presets()
void Slic3r::GUI::Plater::priv::update_project_dirty_from_presets () inline
{ dirty_state.update_from_presets(); }
References Slic3r::GUI::ProjectDirtyStateManager::update_from_presets().
update_restart_background_process()
unsigned int Slic3r::GUI::Plater::priv::update_restart_background_process (bool force_scene_update, bool force_preview_update)
{
    // bitmask of UpdateBackgroundProcessReturnState
    unsigned int state = this->update_background_process(false);
    if (force_update_scene || (state & UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE) != 0)
        view3D->reload_scene(false);
    if (force_update_preview)
        this->preview->reload_print();
    this->restart_background_process(state);
    return state;
}
update_sla_scene()
void Slic3r::GUI::Plater::priv::update_sla_scene () private
{
    // Update the SLAPrint from the current Model, so that the reload_scene()
    // pulls the correct data.
    delayed_scene_refresh = false;
    this->update_restart_background_process(true, true);
}
update_ui_from_settings()
void Slic3r::GUI::Plater::priv::update_ui_from_settings ()
{
    apply_free_camera_correction();
    view3D->get_canvas3d()->update_ui_from_settings();
    preview->get_canvas3d()->update_ui_from_settings();
    sidebar->update_ui_from_settings();
}
References Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Sidebar::update_ui_from_settings().
warnings_dialog()
bool Slic3r::GUI::Plater::priv::warnings_dialog ()
{
    std::vector<std::pair<Slic3r::PrintStateBase::Warning, size_t>> current_critical_warnings{};
    for (const auto& w : current_warnings) {
        if (w.first.level == PrintStateBase::WarningLevel::CRITICAL) {
            current_critical_warnings.push_back(w);
        }
    }
  if (current_critical_warnings.empty())
    return true;
  std::string text = _u8L("There are active warnings concerning sliced models:") + "\n";
  for (auto const& it : current_critical_warnings) {
        size_t next_n = it.first.message.find_first_of('\n', 0);
    text += "\n";
    if (next_n != std::string::npos)
      text += it.first.message.substr(0, next_n);
    else
      text += it.first.message;
  }
  //MessageDialog msg_wingow(this->q, from_u8(text), wxString(SLIC3R_APP_NAME " ") + _L("generated warnings"), wxOK);
    // Changed to InfoDialog so it can show hyperlinks
    InfoDialog msg_wingow(this->q, format_wxstr("%1% %2%", SLIC3R_APP_NAME, _L("generated warnings")), from_u8(text), true);
  const auto res = msg_wingow.ShowModal();
  return res == wxID_OK;
}
References _L, _u8L, Slic3r::PrintStateBase::CRITICAL, Slic3r::GUI::format_wxstr(), and Slic3r::GUI::from_u8().
Member Data Documentation
background_process
BackgroundSlicingProcess Slic3r::GUI::Plater::priv::background_process
background_process_timer
wxTimer Slic3r::GUI::Plater::priv::background_process_timer
bed
Bed3D Slic3r::GUI::Plater::priv::bed
camera
Camera Slic3r::GUI::Plater::priv::camera
collapse_toolbar
GLToolbar Slic3r::GUI::Plater::priv::collapse_toolbar
config
Slic3r::DynamicPrintConfig* Slic3r::GUI::Plater::priv::config
current_panel
wxPanel* Slic3r::GUI::Plater::priv::current_panel { nullptr }
current_warnings
std::vector<std::pair<Slic3r::PrintStateBase::Warning, size_t> > Slic3r::GUI::Plater::priv::current_warnings private
delayed_error_message
std::string Slic3r::GUI::Plater::priv::delayed_error_message
delayed_scene_refresh
bool Slic3r::GUI::Plater::priv::delayed_scene_refresh
dirty_state
ProjectDirtyStateManager Slic3r::GUI::Plater::priv::dirty_state
exporting_status
ExportingStatus Slic3r::GUI::Plater::priv::exporting_status { NOT_EXPORTING }
fff_print
Slic3r::Print Slic3r::GUI::Plater::priv::fff_print
gcode_result
Slic3r::GCodeProcessorResult Slic3r::GUI::Plater::priv::gcode_result
label_btn_export
std::string Slic3r::GUI::Plater::priv::label_btn_export
label_btn_send
std::string Slic3r::GUI::Plater::priv::label_btn_send
last_output_dir_path
std::string Slic3r::GUI::Plater::priv::last_output_dir_path
last_output_path
std::string Slic3r::GUI::Plater::priv::last_output_path
m_last_fff_printer_profile_name
std::string Slic3r::GUI::Plater::priv::m_last_fff_printer_profile_name private
m_last_sla_printer_profile_name
std::string Slic3r::GUI::Plater::priv::m_last_sla_printer_profile_name private
m_prevent_snapshots
int Slic3r::GUI::Plater::priv::m_prevent_snapshots = 0 private
m_project_filename
wxString Slic3r::GUI::Plater::priv::m_project_filename private
m_sla_import_dlg
SLAImportDialog* Slic3r::GUI::Plater::priv::m_sla_import_dlg
m_undo_redo_stack_active
Slic3r::UndoRedo::Stack* Slic3r::GUI::Plater::priv::m_undo_redo_stack_active = &m_undo_redo_stack_main private
m_undo_redo_stack_gizmos
Slic3r::UndoRedo::Stack Slic3r::GUI::Plater::priv::m_undo_redo_stack_gizmos private
m_undo_redo_stack_main
Slic3r::UndoRedo::Stack Slic3r::GUI::Plater::priv::m_undo_redo_stack_main private
m_worker
PlaterWorker<BoostThreadWorker> Slic3r::GUI::Plater::priv::m_worker
main_frame
MainFrame* Slic3r::GUI::Plater::priv::main_frame
menus
MenuFactory Slic3r::GUI::Plater::priv::menus
model
Slic3r::Model Slic3r::GUI::Plater::priv::model
Referenced by reload_from_disk().
mouse3d_controller
Mouse3DController Slic3r::GUI::Plater::priv::mouse3d_controller
notification_manager
std::unique_ptr<NotificationManager> Slic3r::GUI::Plater::priv::notification_manager
panel_sizer
wxSizer* Slic3r::GUI::Plater::priv::panel_sizer { nullptr }
panels
std::vector<wxPanel*> Slic3r::GUI::Plater::priv::panels
pattern_3mf
const std::regex Slic3r::GUI::Plater::priv::pattern_3mf static
pattern_any_amf
const std::regex Slic3r::GUI::Plater::priv::pattern_any_amf static
pattern_bundle
const std::regex Slic3r::GUI::Plater::priv::pattern_bundle static
pattern_prusa
const std::regex Slic3r::GUI::Plater::priv::pattern_prusa static
pattern_zip
const std::regex Slic3r::GUI::Plater::priv::pattern_zip static
pattern_zip_amf
const std::regex Slic3r::GUI::Plater::priv::pattern_zip_amf static
preview
Preview* Slic3r::GUI::Plater::priv::preview
printer_technology
PrinterTechnology Slic3r::GUI::Plater::priv::printer_technology = ptFFF
process_completed_with_error
bool Slic3r::GUI::Plater::priv::process_completed_with_error { false }
q
Plater* Slic3r::GUI::Plater::priv::q
Referenced by reload_from_disk().
ready_to_slice
bool Slic3r::GUI::Plater::priv::ready_to_slice = { false } mutable
show_render_statistic_dialog
bool Slic3r::GUI::Plater::priv::show_render_statistic_dialog { false }
show_warning_dialog
bool Slic3r::GUI::Plater::priv::show_warning_dialog { false } private
sidebar
Sidebar* Slic3r::GUI::Plater::priv::sidebar
sla_print
Slic3r::SLAPrint Slic3r::GUI::Plater::priv::sla_print
suppressed_backround_processing_update
bool Slic3r::GUI::Plater::priv::suppressed_backround_processing_update { false }
view3D
View3D* Slic3r::GUI::Plater::priv::view3D
Referenced by reload_from_disk().
view_toolbar
GLToolbar Slic3r::GUI::Plater::priv::view_toolbar
The documentation for this struct was generated from the following file:
src/slic3r/GUI/Plater.cpp