Prusa Slicer: Eigen::PartialPivLU< _MatrixType > Class Template Reference
Eigen::PartialPivLU< _MatrixType > Class Template Reference
LU decomposition of a matrix with partial pivoting, and related features.
#include <src/eigen/Eigen/src/LU/PartialPivLU.h>
Public Types
enum { MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef SolverBase< PartialPivLU > Base
typedef PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime > PermutationType
typedef Transpositions< RowsAtCompileTime, MaxRowsAtCompileTime > TranspositionType
typedef MatrixType::PlainObject PlainObject
enum
typedef internal::traits< PartialPivLU< _MatrixType > >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef internal::add_const< Transpose< constDerived > >::type ConstTransposeReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, ConstTransposeReturnType >, ConstTransposeReturnType >::type AdjointReturnType
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
PartialPivLU ()
Default Constructor.
PartialPivLU (Index size)
Default Constructor with memory preallocation.
template<typename InputType >
PartialPivLU (const EigenBase< InputType > &matrix)
template<typename InputType >
PartialPivLU (EigenBase< InputType > &matrix)
template<typename InputType >
PartialPivLU & compute (const EigenBase< InputType > &matrix)
const MatrixType & matrixLU () const
const PermutationType & permutationP () const
template<typename Rhs >
const Solve< PartialPivLU, Rhs > solve (const MatrixBase< Rhs > &b) const
RealScalar rcond () const
const Inverse< PartialPivLU > inverse () const
Scalar determinant () const
MatrixType reconstructedMatrix () const
Index rows () const
Index cols () const
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<bool Conjugate, typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
ConstTransposeReturnType transpose () const
AdjointReturnType adjoint () const
EIGEN_DEVICE_FUNC PartialPivLU< _MatrixType > & derived ()
EIGEN_DEVICE_FUNC const PartialPivLU< _MatrixType > & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
void compute ()
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_lu
PermutationType m_p
TranspositionType m_rowsTranspositions
RealScalar m_l1_norm
signed char m_det_p
bool m_isInitialized
Detailed Description
template<typename _MatrixType>
class Eigen::PartialPivLU< _MatrixType >
LU decomposition of a matrix with partial pivoting, and related features.
Template Parameters
_MatrixType the type of the matrix of which we are computing the LU decomposition
This class represents a LU decomposition of a square invertible matrix, with partial pivoting: the matrix A is decomposed as A = PLU where L is unit-lower-triangular, U is upper-triangular, and P is a permutation matrix.
Typically, partial pivoting LU decomposition is only considered numerically stable for square invertible matrices. Thus LAPACK's dgesv and dgesvx require the matrix to be square and invertible. The present class does the same. It will assert that the matrix is square, but it won't (actually it can't) check that the matrix is invertible: it is your task to check that you only use this decomposition on invertible matrices.
The guaranteed safe alternative, working for all matrices, is the full pivoting LU decomposition, provided by class FullPivLU.
This is not a rank-revealing LU decomposition. Many features are intentionally absent from this class, such as rank computation. If you need these features, use class FullPivLU.
This LU decomposition is suitable to invert invertible matrices. It is what MatrixBase::inverse() uses in the general case. On the other hand, it is not suitable to determine whether a given matrix is invertible.
The data of the LU decomposition can be directly accessed through the methods matrixLU(), permutationP().
This class supports the inplace decomposition mechanism.
See also
MatrixBase::partialPivLu(), MatrixBase::determinant(), MatrixBase::inverse(), MatrixBase::computeInverse(), class FullPivLU
Member Typedef Documentation
AdjointReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,ConstTransposeReturnType>,ConstTransposeReturnType>::type Eigen::SolverBase< PartialPivLU< _MatrixType > >::AdjointReturnType inherited
Base
template<typename _MatrixType > typedef SolverBase<PartialPivLU> Eigen::PartialPivLU< _MatrixType >::Base
CoeffReturnType
typedef Scalar Eigen::SolverBase< PartialPivLU< _MatrixType > >::CoeffReturnType inherited
ConstTransposeReturnType
typedef internal::add_const<Transpose<constDerived>>::type Eigen::SolverBase< PartialPivLU< _MatrixType > >::ConstTransposeReturnType inherited
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::PartialPivLU< _MatrixType >::MatrixType
PermutationType
template<typename _MatrixType > typedef PermutationMatrix<RowsAtCompileTime, MaxRowsAtCompileTime> Eigen::PartialPivLU< _MatrixType >::PermutationType
PlainObject
template<typename _MatrixType > typedef MatrixType::PlainObject Eigen::PartialPivLU< _MatrixType >::PlainObject
Scalar
typedef internal::traits<PartialPivLU< _MatrixType > >::Scalar Eigen::SolverBase< PartialPivLU< _MatrixType > >::Scalar inherited
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::EigenBase< Derived >::StorageKind inherited
TranspositionType
template<typename _MatrixType > typedef Transpositions<RowsAtCompileTime, MaxRowsAtCompileTime> Eigen::PartialPivLU< _MatrixType >::TranspositionType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                          internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::MaxRowsAtCompileTime,
                                                             internal::traits<Derived>::MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime == 1
                           || internal::traits<Derived>::MaxColsAtCompileTime == 1
    };
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
MaxRowsAtCompileTime
MaxColsAtCompileTime
         {
      MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
PartialPivLU() [1/4]
template<typename MatrixType > Eigen::PartialPivLU< MatrixType >::PartialPivLU
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via PartialPivLU::compute(const MatrixType&).
  : m_lu(),
    m_p(),
    m_rowsTranspositions(),
    m_l1_norm(0),
    m_det_p(0),
    m_isInitialized(false)
{
}
PartialPivLU() [2/4]
template<typename MatrixType > Eigen::PartialPivLU< MatrixType >::PartialPivLU (Index size) explicit
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
PartialPivLU()
  : m_lu(size, size),
    m_p(size),
    m_rowsTranspositions(size),
    m_l1_norm(0),
    m_det_p(0),
    m_isInitialized(false)
{
}
PartialPivLU() [3/4]
template<typename MatrixType > template<typename InputType > Eigen::PartialPivLU< MatrixType >::PartialPivLU (const EigenBase< InputType > & matrix) explicit
Constructor.
Parameters
matrix the matrix of which to compute the LU decomposition.
Warning
The matrix should have full rank (e.g. if it's square, it should be invertible). If you need to deal with non-full rank, use class FullPivLU instead.
  : m_lu(matrix.rows(),matrix.cols()),
    m_p(matrix.rows()),
    m_rowsTranspositions(matrix.rows()),
    m_l1_norm(0),
    m_det_p(0),
    m_isInitialized(false)
{
  compute(matrix.derived());
}
References Eigen::PartialPivLU< _MatrixType >::compute(), and Eigen::EigenBase< Derived >::derived().
PartialPivLU() [4/4]
template<typename MatrixType > template<typename InputType > Eigen::PartialPivLU< MatrixType >::PartialPivLU (EigenBase< InputType > & matrix) explicit
Constructor for inplace decomposition
Parameters
matrix the matrix of which to compute the LU decomposition.
Warning
The matrix should have full rank (e.g. if it's square, it should be invertible). If you need to deal with non-full rank, use class FullPivLU instead.
  : m_lu(matrix.derived()),
    m_p(matrix.rows()),
    m_rowsTranspositions(matrix.rows()),
    m_l1_norm(0),
    m_det_p(0),
    m_isInitialized(false)
{
  compute();
}
References Eigen::PartialPivLU< _MatrixType >::compute().
Member Function Documentation
_solve_impl()
template<typename _MatrixType > template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::PartialPivLU< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const inline
{
     /* The decomposition PA = LU can be rewritten as A = P^{-1} L U.
      * So we proceed as follows:
      * Step 1: compute c = Pb.
      * Step 2: replace c by the solution x to Lx = c.
      * Step 3: replace c by the solution x to Ux = c.
      */
      eigen_assert(rhs.rows() == m_lu.rows());
      // Step 1
      dst = permutationP() * rhs;
      // Step 2
      m_lu.template triangularView<UnitLower>().solveInPlace(dst);
      // Step 3
      m_lu.template triangularView<Upper>().solveInPlace(dst);
    }
References eigen_assert, Eigen::PartialPivLU< _MatrixType >::m_lu, and Eigen::PartialPivLU< _MatrixType >::permutationP().
_solve_impl_transposed()
template<typename _MatrixType > template<bool Conjugate, typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::PartialPivLU< _MatrixType >::_solve_impl_transposed (const RhsType & rhs, DstType & dst) const inline
{
     /* The decomposition PA = LU can be rewritten as A = P^{-1} L U.
      * So we proceed as follows:
      * Step 1: compute c = Pb.
      * Step 2: replace c by the solution x to Lx = c.
      * Step 3: replace c by the solution x to Ux = c.
      */
      eigen_assert(rhs.rows() == m_lu.cols());
      if (Conjugate) {
        // Step 1
        dst = m_lu.template triangularView<Upper>().adjoint().solve(rhs);
        // Step 2
        m_lu.template triangularView<UnitLower>().adjoint().solveInPlace(dst);
      } else {
        // Step 1
        dst = m_lu.template triangularView<Upper>().transpose().solve(rhs);
        // Step 2
        m_lu.template triangularView<UnitLower>().transpose().solveInPlace(dst);
      }
      // Step 3
      dst = permutationP().transpose() * dst;
    }
References eigen_assert, Eigen::PartialPivLU< _MatrixType >::m_lu, Eigen::PartialPivLU< _MatrixType >::permutationP(), and Eigen::PermutationBase< Derived >::transpose().
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
AdjointReturnType Eigen::SolverBase< PartialPivLU< _MatrixType > >::adjoint () const inline inherited
Returns
an expression of the adjoint of the factored matrix
A typical usage is to solve for the adjoint problem A' x = b:
x = dec.adjoint().solve(b);
For real scalar types, this function is equivalent to transpose().
See also
transpose(), solve()
    {
      return AdjointReturnType(derived().transpose());
    }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
check_template_parameters()
template<typename _MatrixType > static void Eigen::PartialPivLU< _MatrixType >::check_template_parameters () inline static protected
    {
      EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
    }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
cols()
template<typename _MatrixType > Index Eigen::PartialPivLU< _MatrixType >::cols () const inline
{ return m_lu.cols(); }
References Eigen::PartialPivLU< _MatrixType >::m_lu.
compute() [1/2]
template<typename MatrixType > void Eigen::PartialPivLU< MatrixType >::compute protected
{
  check_template_parameters();
  // the row permutation is stored as int indices, so just to be sure:
  eigen_assert(m_lu.rows()<NumTraits<int>::highest());
  m_l1_norm = m_lu.cwiseAbs().colwise().sum().maxCoeff();
  eigen_assert(m_lu.rows() == m_lu.cols() && "PartialPivLU is only for square (and moreover invertible) matrices");
  const Index size = m_lu.rows();
  m_rowsTranspositions.resize(size);
  typename TranspositionType::StorageIndex nb_transpositions;
  internal::partial_lu_inplace(m_lu, m_rowsTranspositions, nb_transpositions);
  m_det_p = (nb_transpositions%2) ? -1 : 1;
  m_p = m_rowsTranspositions;
  m_isInitialized = true;
}
References eigen_assert, and Eigen::internal::partial_lu_inplace().
Referenced by Eigen::PartialPivLU< _MatrixType >::PartialPivLU(), Eigen::PartialPivLU< _MatrixType >::PartialPivLU(), and Eigen::PartialPivLU< _MatrixType >::compute().
compute() [2/2]
template<typename _MatrixType > template<typename InputType > PartialPivLU & Eigen::PartialPivLU< _MatrixType >::compute (const EigenBase< InputType > & matrix) inline
{
      m_lu = matrix.derived();
      compute();
      return *this;
    }
References Eigen::PartialPivLU< _MatrixType >::compute(), Eigen::EigenBase< Derived >::derived(), and Eigen::PartialPivLU< _MatrixType >::m_lu.
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
EIGEN_DEVICE_FUNC PartialPivLU< _MatrixType > & Eigen::EigenBase< PartialPivLU< _MatrixType > >::derived () inline inherited
Returns
a reference to the derived object
{ return *static_cast<Derived*>(this); }
derived() [2/2]
EIGEN_DEVICE_FUNC const PartialPivLU< _MatrixType > & Eigen::EigenBase< PartialPivLU< _MatrixType > >::derived () const inline inherited
Returns
a const reference to the derived object
{ return *static_cast<const Derived*>(this); }
determinant()
template<typename MatrixType > PartialPivLU< MatrixType >::Scalar Eigen::PartialPivLU< MatrixType >::determinant
Returns
the determinant of the matrix of which *this is the LU decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the LU decomposition has already been computed.
Note
For fixed-size matrices of size up to 4, MatrixBase::determinant() offers optimized paths.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow.
See also
MatrixBase::determinant()
{
  eigen_assert(m_isInitialized && "PartialPivLU is not initialized.");
  return Scalar(m_det_p) * m_lu.diagonal().prod();
}
References eigen_assert.
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
Referenced by Eigen::EigenBase< Derived >::subTo().
inverse()
template<typename _MatrixType > const Inverse< PartialPivLU > Eigen::PartialPivLU< _MatrixType >::inverse () const inline
Returns
the inverse of the matrix of which *this is the LU decomposition.
Warning
The matrix being decomposed here is assumed to be invertible. If you need to check for invertibility, use class FullPivLU instead.
See also
MatrixBase::inverse(), LU::inverse()
    {
      eigen_assert(m_isInitialized && "PartialPivLU is not initialized.");
      return Inverse<PartialPivLU>(*this);
    }
References eigen_assert, and Eigen::PartialPivLU< _MatrixType >::m_isInitialized.
matrixLU()
template<typename _MatrixType > const MatrixType & Eigen::PartialPivLU< _MatrixType >::matrixLU () const inline
Returns
the LU decomposition matrix: the upper-triangular part is U, the unit-lower-triangular part is L (at least for square matrices; in the non-square case, special care is needed, see the documentation of class FullPivLU).
See also
matrixL(), matrixU()
    {
      eigen_assert(m_isInitialized && "PartialPivLU is not initialized.");
      return m_lu;
    }
References eigen_assert, Eigen::PartialPivLU< _MatrixType >::m_isInitialized, and Eigen::PartialPivLU< _MatrixType >::m_lu.
permutationP()
template<typename _MatrixType > const PermutationType & Eigen::PartialPivLU< _MatrixType >::permutationP () const inline
Returns
the permutation matrix P.
    {
      eigen_assert(m_isInitialized && "PartialPivLU is not initialized.");
      return m_p;
    }
References eigen_assert, Eigen::PartialPivLU< _MatrixType >::m_isInitialized, and Eigen::PartialPivLU< _MatrixType >::m_p.
Referenced by Eigen::PartialPivLU< _MatrixType >::_solve_impl(), and Eigen::PartialPivLU< _MatrixType >::_solve_impl_transposed().
rcond()
template<typename _MatrixType > RealScalar Eigen::PartialPivLU< _MatrixType >::rcond () const inline
Returns
an estimate of the reciprocal condition number of the matrix of which *this is the LU decomposition.
    {
      eigen_assert(m_isInitialized && "PartialPivLU is not initialized.");
      return internal::rcond_estimate_helper(m_l1_norm, *this);
    }
References eigen_assert, Eigen::PartialPivLU< _MatrixType >::m_isInitialized, Eigen::PartialPivLU< _MatrixType >::m_l1_norm, and Eigen::internal::rcond_estimate_helper().
reconstructedMatrix()
template<typename MatrixType > MatrixType Eigen::PartialPivLU< MatrixType >::reconstructedMatrix
Returns
the matrix represented by the decomposition, i.e., it returns the product: P^{-1} L U. This function is provided for debug purpose.
{
  eigen_assert(m_isInitialized && "LU is not initialized.");
  // LU
  MatrixType res = m_lu.template triangularView<UnitLower>().toDenseMatrix()
                 * m_lu.template triangularView<Upper>();
  // P^{-1}(LU)
  res = m_p.inverse() * res;
  return res;
}
References eigen_assert.
rows()
template<typename _MatrixType > Index Eigen::PartialPivLU< _MatrixType >::rows () const inline
{ return m_lu.rows(); }
References Eigen::PartialPivLU< _MatrixType >::m_lu.
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
References Eigen::EigenBase< Derived >::cols(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
solve()
template<typename _MatrixType > template<typename Rhs > const Solve< PartialPivLU, Rhs > Eigen::PartialPivLU< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method returns the solution x to the equation Ax=b, where A is the matrix of which *this is the LU decomposition.
Parameters
b the right-hand-side of the equation to solve. Can be a vector or a matrix, the only requirement in order for the equation to make sense is that b.rows()==A.rows(), where A is the matrix of which *this is the LU decomposition.
Returns
the solution.
Example:
Output:
Since this PartialPivLU class assumes anyway that the matrix A is invertible, the solution theoretically exists and is unique regardless of b.
See also
TriangularView::solve(), inverse(), computeInverse()
    {
      eigen_assert(m_isInitialized && "PartialPivLU is not initialized.");
      return Solve<PartialPivLU, Rhs>(*this, b.derived());
    }
References eigen_assert, and Eigen::PartialPivLU< _MatrixType >::m_isInitialized.
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
transpose()
ConstTransposeReturnType Eigen::SolverBase< PartialPivLU< _MatrixType > >::transpose () const inline inherited
Returns
an expression of the transposed of the factored matrix.
A typical usage is to solve for the transposed problem A^T x = b:
x = dec.transpose().solve(b);
See also
adjoint(), solve()
    {
      return ConstTransposeReturnType(derived());
    }
Member Data Documentation
m_det_p
template<typename _MatrixType > signed char Eigen::PartialPivLU< _MatrixType >::m_det_p protected
m_isInitialized
template<typename _MatrixType > bool Eigen::PartialPivLU< _MatrixType >::m_isInitialized protected
Referenced by Eigen::PartialPivLU< _MatrixType >::inverse(), Eigen::PartialPivLU< _MatrixType >::matrixLU(), Eigen::PartialPivLU< _MatrixType >::permutationP(), Eigen::PartialPivLU< _MatrixType >::rcond(), and Eigen::PartialPivLU< _MatrixType >::solve().
m_l1_norm
template<typename _MatrixType > RealScalar Eigen::PartialPivLU< _MatrixType >::m_l1_norm protected
Referenced by Eigen::PartialPivLU< _MatrixType >::rcond().
m_lu
template<typename _MatrixType > MatrixType Eigen::PartialPivLU< _MatrixType >::m_lu protected
Referenced by Eigen::PartialPivLU< _MatrixType >::_solve_impl(), Eigen::PartialPivLU< _MatrixType >::_solve_impl_transposed(), Eigen::PartialPivLU< _MatrixType >::cols(), Eigen::PartialPivLU< _MatrixType >::compute(), Eigen::PartialPivLU< _MatrixType >::matrixLU(), and Eigen::PartialPivLU< _MatrixType >::rows().
m_p
template<typename _MatrixType > PermutationType Eigen::PartialPivLU< _MatrixType >::m_p protected
Referenced by Eigen::PartialPivLU< _MatrixType >::permutationP().
m_rowsTranspositions
template<typename _MatrixType > TranspositionType Eigen::PartialPivLU< _MatrixType >::m_rowsTranspositions protected
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/util/ForwardDeclarations.h
src/eigen/Eigen/src/LU/PartialPivLU.h