Prusa Slicer: Slic3r::GUI::Config::Index Class Reference
Slic3r::GUI::Config::Index Class Reference
#include <src/slic3r/Config/Version.hpp>
Public Types
typedef std::vector< Version >::const_iterator const_iterator
Public Member Functions
size_t load (const boost::filesystem::path &path)
const std::string & vendor () const
Semver version () const
const_iterator begin () const
const_iterator end () const
const_iterator find (const Semver &ver) const
const std::vector< Version > & configs () const
const_iterator recommended () const
const_iterator recommended (const Semver &slic3r_version) const
const boost::filesystem::path & path () const
Static Public Member Functions
static std::vector< Index > load_db ()
Private Attributes
std::string m_vendor
std::vector< Version > m_configs
boost::filesystem::path m_path
Detailed Description
Member Typedef Documentation
const_iterator
typedef std::vector<Version>::const_iterator Slic3r::GUI::Config::Index::const_iterator
Member Function Documentation
begin()
const_iterator Slic3r::GUI::Config::Index::begin () const inline
{ return m_configs.begin(); }
References m_configs.
Referenced by recommended().
configs()
const std::vector< Version > & Slic3r::GUI::Config::Index::configs () const inline
{ return m_configs; }
References m_configs.
end()
const_iterator Slic3r::GUI::Config::Index::end () const inline
{ return m_configs.end(); }
References m_configs.
Referenced by Slic3r::PresetUpdater::priv::get_config_updates(), Slic3r::GUI::BundleMap::load(), load(), recommended(), Slic3r::PresetUpdater::priv::sync_config(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
find()
Index::const_iterator Slic3r::GUI::Config::Index::find (const Semver & ver) const
{
  Version key;
  key.config_version = ver;
  auto it = std::lower_bound(m_configs.begin(), m_configs.end(), key,
    [](const Version &v1, const Version &v2) { return v1.config_version < v2.config_version; });
  return (it == m_configs.end() || it->config_version == ver) ? it : m_configs.end();
}
References Slic3r::GUI::Config::Version::config_version, and m_configs.
Referenced by Slic3r::GUI::Config::SnapshotDB::take_snapshot().
load()
size_t Slic3r::GUI::Config::Index::load (const boost::filesystem::path & path)
{
  m_configs.clear();
  m_vendor = path.stem().string();
  m_path = path;
    boost::nowide::ifstream ifs(path.string());
    std::string line;
    size_t idx_line = 0;
    Version ver;
    while (std::getline(ifs, line)) {
#ifndef _MSVCVER
    // On a Unix system, getline does not remove the trailing carriage returns, if the index is shared over a Windows filesystem. Remove them manually.
    while (! line.empty() && line.back() == '\r')
      line.pop_back();
#endif
      ++ idx_line;
      // Skip the initial white spaces.
      char *key = left_trim(line.data());
    if (*key == '#')
      // Skip a comment line.
      continue;
    // Right trim the line.
    char *end = right_trim(key);
        if (key == end)
            // Skip an empty line.
            continue;
    // Keyword may only contain alphanumeric characters. Semantic version may in addition contain "+.-".
      char *key_end = key;
      bool  maybe_semver = true;
    for (; *key_end != 0; ++ key_end) {
      if (std::isalnum(*key_end) || strchr("+.-", *key_end) != nullptr) {
        // It may be a semver.
      } else if (*key_end == '_') {
        // Cannot be a semver, but it may be a key.
        maybe_semver = false;
      } else
        // End of semver or keyword.
        break;
      }
        if (*key_end != 0 && *key_end != ' ' && *key_end != '\t' && *key_end != '=')
        throw file_parser_error("Invalid keyword or semantic version", path, idx_line);
        char *value = left_trim(key_end);
    bool  key_value_pair = *value == '=';
    if (key_value_pair)
      value = left_trim(value + 1);
    *key_end = 0;
      boost::optional<Semver> semver;
        if (maybe_semver)
        semver = Semver::parse(key);
        if (key_value_pair) {
        if (semver)
          throw file_parser_error("Key cannot be a semantic version", path, idx_line);\
        // Verify validity of the key / value pair.
      std::string svalue = unquote_value(value, end, path.string(), idx_line);
        if (strcmp(key, "min_slic3r_version") == 0 || strcmp(key, "max_slic3r_version") == 0) {
          if (! svalue.empty())
          semver = Semver::parse(svalue);
                if (! semver)
            throw file_parser_error(std::string(key) + " must referece a valid semantic version", path, idx_line);
                if (strcmp(key, "min_slic3r_version") == 0)
            ver.min_slic3r_version = *semver;
                else
            ver.max_slic3r_version = *semver;
        } else {
          // Ignore unknown keys, as there may come new keys in the future.
        }
      continue;
      }
    if (! semver)
      throw file_parser_error("Invalid semantic version", path, idx_line);
    ver.config_version = *semver;
    ver.comment = (end <= key_end) ? "" : unquote_version_comment(value, end, path.string(), idx_line);
    m_configs.emplace_back(ver);
    }
    // Sort the configs by their version.
    std::sort(m_configs.begin(), m_configs.end(), [](const Version &v1, const Version &v2) { return v1.config_version < v2.config_version; });
    return m_configs.size();
}
References Slic3r::GUI::Config::Version::comment, Slic3r::GUI::Config::Version::config_version, end(), Slic3r::GUI::Config::left_trim(), m_configs, m_path, m_vendor, Slic3r::GUI::Config::Version::max_slic3r_version, Slic3r::GUI::Config::Version::min_slic3r_version, Slic3r::Semver::parse(), path(), Slic3r::GUI::Config::right_trim(), Slic3r::GUI::Config::unquote_value(), and Slic3r::GUI::Config::unquote_version_comment().
Referenced by Slic3r::PresetUpdater::priv::check_install_indices(), Slic3r::PresetUpdater::priv::get_config_updates(), Slic3r::PresetUpdater::install_bundles_rsrc_or_cache_vendor(), Slic3r::GUI::BundleMap::load(), load_db(), Slic3r::PresetUpdater::priv::sync_config(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
load_db()
std::vector< Index > Slic3r::GUI::Config::Index::load_db () static
{
    boost::filesystem::path cache_dir = boost::filesystem::path(Slic3r::data_dir()) / "cache";
    std::vector<Index> index_db;
    std::string errors_cummulative;
  for (auto &dir_entry : boost::filesystem::directory_iterator(cache_dir))
        if (Slic3r::is_idx_file(dir_entry)) {
          Index idx;
            try {
              idx.load(dir_entry.path());
            } catch (const std::runtime_error &err) {
                errors_cummulative += err.what();
                errors_cummulative += "\n";
                continue;
      }
            index_db.emplace_back(std::move(idx));
        }
    if (! errors_cummulative.empty())
        throw Slic3r::RuntimeError(errors_cummulative);
    return index_db;
}
References Slic3r::data_dir(), Slic3r::is_idx_file(), and load().
Referenced by Slic3r::GUI::Config::SnapshotDB::singleton().
path()
const boost::filesystem::path & Slic3r::GUI::Config::Index::path () const inline
{ return m_path; }
References m_path.
Referenced by load().
recommended() [1/2]
Index::const_iterator Slic3r::GUI::Config::Index::recommended () const
{
  return this->recommended(Slic3r::SEMVER);
}
References recommended(), and Slic3r::SEMVER.
Referenced by Slic3r::PresetUpdater::priv::get_config_updates(), Slic3r::PresetUpdater::install_bundles_rsrc_or_cache_vendor(), Slic3r::GUI::BundleMap::load(), recommended(), and Slic3r::PresetUpdater::priv::sync_config().
recommended() [2/2]
Index::const_iterator Slic3r::GUI::Config::Index::recommended (const Semver & slic3r_version) const
{
  const_iterator highest = this->end();
  for (const_iterator it = this->begin(); it != this->end(); ++ it)
    if (it->is_slic3r_supported(slic3r_version) &&
      (highest == this->end() || highest->config_version < it->config_version))
      highest = it;
  return highest;
}
References begin(), and end().
vendor()
const std::string & Slic3r::GUI::Config::Index::vendor () const inline
{ return m_vendor; }
References m_vendor.
version()
Semver Slic3r::GUI::Config::Index::version () const
{
    Semver ver = Semver::zero();
    for (const Version &cv : m_configs)
        if (cv.config_version >= ver)
            ver = cv.config_version;
    return ver;
}
References m_configs, and Slic3r::Semver::zero().
Referenced by Slic3r::PresetUpdater::priv::check_install_indices(), and Slic3r::PresetUpdater::priv::sync_config().
Member Data Documentation
m_configs
std::vector<Version> Slic3r::GUI::Config::Index::m_configs private
Referenced by begin(), configs(), end(), find(), load(), and version().
m_path
boost::filesystem::path Slic3r::GUI::Config::Index::m_path private
Referenced by load(), and path().
m_vendor
std::string Slic3r::GUI::Config::Index::m_vendor private
Referenced by load(), and vendor().
The documentation for this class was generated from the following files:
src/slic3r/Config/Version.hpp
src/slic3r/Config/Version.cpp