Prusa Slicer: src/glu-libtess/src/tess.h File Reference
tess.h File Reference
#include "glu-libtess.h"
#include <setjmp.h>
#include "mesh.h"
#include "dict.h"
#include "priorityq.h"
Classes
struct CachedVertex
struct GLUtesselator
Macros
#define TESS_MAX_CACHE 100
#define CALL_BEGIN_OR_BEGIN_DATA(a)
#define CALL_VERTEX_OR_VERTEX_DATA(a)
#define CALL_EDGE_FLAG_OR_EDGE_FLAG_DATA(a)
#define CALL_END_OR_END_DATA()
#define CALL_COMBINE_OR_COMBINE_DATA(a, b, c, d)
#define CALL_ERROR_OR_ERROR_DATA(a)
Typedefs
typedef struct CachedVertex CachedVertex
Enumerations
enum TessState { T_DORMANT , T_IN_POLYGON , T_IN_CONTOUR }
Functions
void GLAPIENTRY __gl_noBeginData (GLenum type, void *polygonData)
void GLAPIENTRY __gl_noEdgeFlagData (GLboolean boundaryEdge, void *polygonData)
void GLAPIENTRY __gl_noVertexData (void *data, void *polygonData)
void GLAPIENTRY __gl_noEndData (void *polygonData)
void GLAPIENTRY __gl_noErrorData (GLenum errnum, void *polygonData)
void GLAPIENTRY __gl_noCombineData (GLdouble coords[3], void *data[4], GLfloat weight[4], void **outData, void *polygonData)
Class Documentation
CachedVertex
struct CachedVertex
Class Members
GLdouble coords[3]
void * data
Macro Definition Documentation
CALL_BEGIN_OR_BEGIN_DATA
#define CALL_BEGIN_OR_BEGIN_DATA (a)
Value:
   if (tess->callBeginData != &__gl_noBeginData) \
      (*tess->callBeginData)((a),tess->polygonData); \
   else (*tess->callBegin)((a));
CALL_COMBINE_OR_COMBINE_DATA
#define CALL_COMBINE_OR_COMBINE_DATA (a, b, c, d)
Value:
   if (tess->callCombineData != &__gl_noCombineData) \
      (*tess->callCombineData)((a),(b),(c),(d),tess->polygonData); \
   else (*tess->callCombine)((a),(b),(c),(d));
CALL_EDGE_FLAG_OR_EDGE_FLAG_DATA
#define CALL_EDGE_FLAG_OR_EDGE_FLAG_DATA (a)
Value:
   if (tess->callEdgeFlagData != &__gl_noEdgeFlagData) \
      (*tess->callEdgeFlagData)((a),tess->polygonData); \
   else (*tess->callEdgeFlag)((a));
CALL_END_OR_END_DATA
#define CALL_END_OR_END_DATA ()
Value:
   if (tess->callEndData != &__gl_noEndData) \
      (*tess->callEndData)(tess->polygonData); \
   else (*tess->callEnd)();
CALL_ERROR_OR_ERROR_DATA
#define CALL_ERROR_OR_ERROR_DATA (a)
Value:
   if (tess->callErrorData != &__gl_noErrorData) \
      (*tess->callErrorData)((a),tess->polygonData); \
   else (*tess->callError)((a));
CALL_VERTEX_OR_VERTEX_DATA
#define CALL_VERTEX_OR_VERTEX_DATA (a)
Value:
   if (tess->callVertexData != &__gl_noVertexData) \
      (*tess->callVertexData)((a),tess->polygonData); \
   else (*tess->callVertex)((a));
TESS_MAX_CACHE
#define TESS_MAX_CACHE 100
Typedef Documentation
CachedVertex
typedef struct CachedVertex CachedVertex
Enumeration Type Documentation
TessState
enum TessState
Enumerator
T_DORMANT
T_IN_POLYGON
T_IN_CONTOUR
{ T_DORMANT, T_IN_POLYGON, T_IN_CONTOUR };
Function Documentation
__gl_noBeginData()
void GLAPIENTRY __gl_noBeginData (GLenum type, void * polygonData)
                                   {}
Referenced by gluNewTess(), gluTessCallback(), and gluTessEndPolygon().
__gl_noCombineData()
void GLAPIENTRY __gl_noCombineData (GLdouble coords[3], void * data[4], GLfloat weight[4], void ** outData, void * polygonData)
                                     {}
Referenced by gluNewTess(), and gluTessCallback().
__gl_noEdgeFlagData()
void GLAPIENTRY __gl_noEdgeFlagData (GLboolean boundaryEdge, void * polygonData)
                                   {}
Referenced by gluNewTess(), gluTessCallback(), and gluTessEndPolygon().
__gl_noEndData()
void GLAPIENTRY __gl_noEndData (void * polygonData)
{}
Referenced by gluNewTess(), gluTessCallback(), and gluTessEndPolygon().
__gl_noErrorData()
void GLAPIENTRY __gl_noErrorData (GLenum errnum, void * polygonData)
                                   {}
Referenced by gluNewTess(), and gluTessCallback().
__gl_noVertexData()
void GLAPIENTRY __gl_noVertexData (void * data, void * polygonData)
                                    {}
Referenced by gluNewTess(), gluTessCallback(), and gluTessEndPolygon().