Prusa Slicer: Slic3r::GUI::ObjectSettings Class Reference
Slic3r::GUI::ObjectSettings Class Reference
#include <src/slic3r/GUI/GUI_ObjectSettings.hpp>
Public Member Functions
ObjectSettings (wxWindow *parent)
~ObjectSettings ()
bool update_settings_list ()
bool add_missed_options (ModelConfig *config_to, const DynamicPrintConfig &config_from)
void update_config_values (ModelConfig *config)
void UpdateAndShow (const bool show) override
void sys_color_changed ()
virtual bool IsShown ()
virtual void Show (const bool show)
virtual void Hide ()
virtual wxSizer * get_sizer ()
ConfigOptionsGroup * get_og ()
const ConfigOptionsGroup * get_og () const
wxWindow * parent () const
Protected Attributes
std::shared_ptr< ConfigOptionsGroup > m_og
wxWindow * m_parent
Private Attributes
wxBoxSizer * m_settings_list_sizer { nullptr }
std::vector< std::shared_ptr< ConfigOptionsGroup > > m_og_settings
ScalableBitmap m_bmp_delete
ScalableBitmap m_bmp_delete_focus
Detailed Description
Constructor & Destructor Documentation
ObjectSettings()
Slic3r::GUI::ObjectSettings::ObjectSettings (wxWindow * parent)
                                               :
    OG_Settings(parent, true)
{
    m_og->activate();
    m_og->set_name(_(L("Additional Settings")));
    m_settings_list_sizer = new wxBoxSizer(wxVERTICAL);
    m_og->sizer->Add(m_settings_list_sizer, 1, wxEXPAND | wxLEFT, 5);
    m_bmp_delete = ScalableBitmap(parent, "cross");
    m_bmp_delete_focus = ScalableBitmap(parent, "cross_focus");
}
References _, L, m_bmp_delete, m_bmp_delete_focus, Slic3r::GUI::OG_Settings::m_og, m_settings_list_sizer, and Slic3r::GUI::OG_Settings::parent().
~ObjectSettings()
Slic3r::GUI::ObjectSettings::~ObjectSettings () inline
{}
Member Function Documentation
add_missed_options()
bool Slic3r::GUI::ObjectSettings::add_missed_options (ModelConfig * config_to, const DynamicPrintConfig & config_from)
{
    const DynamicPrintConfig& print_config = wxGetApp().plater()->printer_technology() == ptFFF ?
                                             wxGetApp().preset_bundle->prints.get_edited_preset().config :
                                             wxGetApp().preset_bundle->sla_prints.get_edited_preset().config;
    bool is_added = false;
    for (auto opt_key : config_from.diff(print_config))
        if (!config_to->has(opt_key)) {
            config_to->set_key_value(opt_key, config_from.option(opt_key)->clone());
            is_added = true;
        }
    return is_added;
}
References Slic3r::ConfigOption::clone(), Slic3r::DynamicConfig::diff(), Slic3r::ModelConfig::has(), Slic3r::ConfigBase::option(), Slic3r::ptFFF, and Slic3r::ModelConfig::set_key_value().
Referenced by update_config_values().
get_og() [1/2]
ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () inline inherited
{ return m_og.get(); }
References Slic3r::GUI::OG_Settings::m_og.
Referenced by Slic3r::GUI::ObjectManipulation::msw_rescale(), and Slic3r::GUI::ObjectManipulation::sys_color_changed().
get_og() [2/2]
const ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () const inline inherited
{ return m_og.get(); }
References Slic3r::GUI::OG_Settings::m_og.
get_sizer()
wxSizer * Slic3r::GUI::OG_Settings::get_sizer () virtual inherited
Reimplemented in Slic3r::GUI::FreqChangedParams.
{
    return m_og->sizer;
}
References Slic3r::GUI::OG_Settings::m_og.
Hide()
void Slic3r::GUI::OG_Settings::Hide () virtual inherited
{
    Show(false);
}
References Slic3r::GUI::OG_Settings::Show().
IsShown()
bool Slic3r::GUI::OG_Settings::IsShown () virtual inherited
Reimplemented in Slic3r::GUI::ObjectManipulation.
{
    return m_og->sizer->IsEmpty() ? false : m_og->sizer->IsShown(size_t(0));
}
References Slic3r::GUI::OG_Settings::m_og.
parent()
wxWindow * Slic3r::GUI::OG_Settings::parent () const inline inherited
{return m_parent; }
References Slic3r::GUI::OG_Settings::m_parent.
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), ObjectSettings(), Slic3r::GUI::OG_Settings::OG_Settings(), Slic3r::GUI::ObjectManipulation::msw_rescale(), and update_settings_list().
Show()
void Slic3r::GUI::OG_Settings::Show (const bool show) virtual inherited
Reimplemented in Slic3r::GUI::FreqChangedParams, and Slic3r::GUI::ObjectManipulation.
{
    m_og->Show(show);
}
References Slic3r::GUI::OG_Settings::m_og.
Referenced by Slic3r::GUI::OG_Settings::Hide(), and Slic3r::GUI::OG_Settings::UpdateAndShow().
sys_color_changed()
void Slic3r::GUI::ObjectSettings::sys_color_changed ()
{
    m_og->sys_color_changed();
    for (auto group : m_og_settings)
        group->sys_color_changed();
}
References Slic3r::GUI::OG_Settings::m_og, and m_og_settings.
update_config_values()
void Slic3r::GUI::ObjectSettings::update_config_values (ModelConfig * config)
{
    const auto objects_model        = wxGetApp().obj_list()->GetModel();
    const auto item                 = wxGetApp().obj_list()->GetSelection();
    const auto printer_technology   = wxGetApp().plater()->printer_technology();
    const bool is_object_settings   = objects_model->GetItemType(objects_model->GetParent(item)) == itObject;
    if (!item || !objects_model->IsSettingsItem(item) || !config)
        return;
    // update config values according to configuration hierarchy
    DynamicPrintConfig  main_config   = printer_technology == ptFFF ?
                                        wxGetApp().preset_bundle->prints.get_edited_preset().config :
                                        wxGetApp().preset_bundle->sla_prints.get_edited_preset().config;
    auto load_config = [this, config, &main_config]()
    {
        /* Additional check for overrided options.
         * There is a case, when some options should to be added,
         * to avoid check loop in the next configuration update
         */
        bool is_added = add_missed_options(config, main_config);
        // load checked values from main_config to config
        config->apply_only(main_config, config->keys(), true);
        // Initialize UI components with the config values.
        for (auto og : m_og_settings)
            og->reload_config();
        // next config check
        update_config_values(config);
        if (is_added) {
// #ysFIXME - Delete after testing! Very likely this CallAfret is no needed
//            wxTheApp->CallAfter([this]() {
                wxWindowUpdateLocker noUpdates(m_parent);
                update_settings_list();
                m_parent->Layout();
//            });
        }
    };
    auto toggle_field = [this](const t_config_option_key & opt_key, bool toggle, int opt_index)
    {
        Field* field = nullptr;
        for (auto og : m_og_settings) {
            field = og->get_fieldc(opt_key, opt_index);
            if (field != nullptr)
                break;
        }
        if (field)
            field->toggle(toggle);
    };
    ConfigManipulation config_manipulation(load_config, toggle_field, nullptr, config);
    if (!is_object_settings)
    {
        const int obj_idx = objects_model->GetObjectIdByItem(item);
        assert(obj_idx >= 0);
        // for object's part first of all update konfiguration from object
        main_config.apply(wxGetApp().model().objects[obj_idx]->config.get(), true);
        // and then from its own config
    }
    main_config.apply(config->get(), true);
    printer_technology == ptFFF  ?  config_manipulation.update_print_fff_config(&main_config) :
                                    config_manipulation.update_print_sla_config(&main_config) ;
    printer_technology == ptFFF  ?  config_manipulation.toggle_print_fff_options(&main_config) :
                                    config_manipulation.toggle_print_sla_options(&main_config) ;
}
References add_missed_options(), Slic3r::ConfigBase::apply(), Slic3r::ModelConfig::apply_only(), Slic3r::ModelConfig::get(), Slic3r::GUI::itObject, Slic3r::ModelConfig::keys(), m_og_settings, Slic3r::GUI::OG_Settings::m_parent, Slic3r::GUI::printer_technology(), Slic3r::ptFFF, Slic3r::GUI::Field::toggle(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::ConfigManipulation::toggle_print_sla_options(), update_config_values(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), and update_settings_list().
Referenced by update_config_values(), and update_settings_list().
update_settings_list()
bool Slic3r::GUI::ObjectSettings::update_settings_list ()
{
    m_settings_list_sizer->Clear(true);
    m_og_settings.resize(0);
    auto objects_ctrl   = wxGetApp().obj_list();
    auto objects_model  = wxGetApp().obj_list()->GetModel();
    auto config         = wxGetApp().obj_list()->config();
    const auto item = objects_ctrl->GetSelection();
    if (!item || !objects_model->IsSettingsItem(item) || !config || objects_ctrl->multiple_selection())
        return false;
    const bool is_object_settings = objects_model->GetItemType(objects_model->GetParent(item)) == itObject;
    SettingsFactory::Bundle cat_options = SettingsFactory::get_bundle(&config->get(), is_object_settings);
    if (!cat_options.empty())
    {
      std::vector<std::string> categories;
        categories.reserve(cat_options.size());
        auto extra_column = [config, this](wxWindow* parent, const Line& line)
    {
      auto opt_key = (line.get_options())[0].opt_id;  //we assume that we have one option per line
      auto btn = new ScalableButton(parent, wxID_ANY, m_bmp_delete);
            btn->SetToolTip(_(L("Remove parameter")));
            btn->SetBitmapFocus(m_bmp_delete_focus.bmp());
            btn->SetBitmapCurrent(m_bmp_delete_focus.bmp());
      btn->Bind(wxEVT_BUTTON, [opt_key, config, this](wxEvent &event) {
                wxGetApp().plater()->take_snapshot(format_wxstr(_L("Delete Option %s"), opt_key));
        config->erase(opt_key);
                wxGetApp().obj_list()->changed_object();
                wxTheApp->CallAfter([this]() {
                    wxWindowUpdateLocker noUpdates(m_parent);
                    update_settings_list();
                    m_parent->Layout();
                });
      });
      return btn;
    };
        for (auto& cat : cat_options)
        {
            categories.push_back(cat.first);
            auto optgroup = std::make_shared<ConfigOptionsGroup>(m_og->ctrl_parent(), _(cat.first), config, false, extra_column);
            optgroup->label_width = 15;
            optgroup->sidetext_width = 5;
            optgroup->m_on_change = [this, config](const t_config_option_key& opt_id, const boost::any& value) {
                                    this->update_config_values(config);
                                    wxGetApp().obj_list()->changed_object(); };
            // call back for rescaling of the extracolumn control
            optgroup->rescale_extra_column_item = [this](wxWindow* win) {
                auto *ctrl = dynamic_cast<ScalableButton*>(win);
                if (ctrl == nullptr)
                    return;
                ctrl->SetBitmap_(m_bmp_delete);
                ctrl->SetBitmapFocus(m_bmp_delete_focus.bmp());
                ctrl->SetBitmapCurrent(m_bmp_delete_focus.bmp());
            };
            const bool is_extruders_cat = cat.first == "Extruders";
            for (auto& opt : cat.second)
            {
                Option option = optgroup->get_option(opt);
                option.opt.width = 12;
                if (!option.opt.full_label.empty())
                    option.opt.label = option.opt.full_label;
                if (is_extruders_cat)
                    option.opt.max = wxGetApp().extruders_edited_cnt();
                optgroup->append_single_option_line(option);
            }
            optgroup->activate();
            for (auto& opt : cat.second)
                optgroup->get_field(opt)->m_on_change = [optgroup](const std::string& opt_id, const boost::any& value) {
                    // first of all take a snapshot and then change value in configuration
                    wxGetApp().plater()->take_snapshot(format_wxstr(_L("Change Option %s"), opt_id));
                    optgroup->on_change_OG(opt_id, value);
                };
            optgroup->reload_config();
            m_settings_list_sizer->Add(optgroup->sizer, 0, wxEXPAND | wxALL, 0);
            m_og_settings.push_back(optgroup);
        }
        if (!categories.empty()) {
            objects_model->UpdateSettingsDigest(item, categories);
            update_config_values(config);
        }
    }
    else
    {
        objects_ctrl->select_item(objects_model->Delete(item));
        return false;
    }
    return true;
}
References _, _L, ScalableBitmap::bmp(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::SettingsFactory::get_bundle(), Slic3r::GUI::itObject, L, m_bmp_delete, m_bmp_delete_focus, Slic3r::GUI::OG_Settings::m_og, m_og_settings, Slic3r::GUI::OG_Settings::m_parent, m_settings_list_sizer, Slic3r::GUI::OG_Settings::parent(), ScalableButton::SetBitmap_(), update_config_values(), update_settings_list(), and wxEVT_BUTTON.
Referenced by update_config_values(), update_settings_list(), and UpdateAndShow().
UpdateAndShow()
void Slic3r::GUI::ObjectSettings::UpdateAndShow (const bool show) override virtual
Reimplemented from Slic3r::GUI::OG_Settings.
{
    OG_Settings::UpdateAndShow(show ? update_settings_list() : false);
}
References update_settings_list(), and Slic3r::GUI::OG_Settings::UpdateAndShow().
Referenced by Slic3r::GUI::ObjectList::update_settings_item_and_selection().
Member Data Documentation
m_bmp_delete
ScalableBitmap Slic3r::GUI::ObjectSettings::m_bmp_delete private
Referenced by ObjectSettings(), and update_settings_list().
m_bmp_delete_focus
ScalableBitmap Slic3r::GUI::ObjectSettings::m_bmp_delete_focus private
Referenced by ObjectSettings(), and update_settings_list().
m_og
std::shared_ptr<ConfigOptionsGroup> Slic3r::GUI::OG_Settings::m_og protected inherited
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), ObjectSettings(), Slic3r::GUI::OG_Settings::OG_Settings(), Slic3r::GUI::OG_Settings::get_og(), Slic3r::GUI::OG_Settings::get_og(), Slic3r::GUI::FreqChangedParams::get_og(), Slic3r::GUI::OG_Settings::get_sizer(), Slic3r::GUI::OG_Settings::IsShown(), Slic3r::GUI::ObjectManipulation::IsShown(), Slic3r::GUI::FreqChangedParams::msw_rescale(), Slic3r::GUI::FreqChangedParams::Show(), Slic3r::GUI::OG_Settings::Show(), Slic3r::GUI::ObjectManipulation::Show(), sys_color_changed(), Slic3r::GUI::FreqChangedParams::sys_color_changed(), Slic3r::GUI::ObjectManipulation::update_if_dirty(), and update_settings_list().
m_og_settings
std::vector<std::shared_ptr<ConfigOptionsGroup> > Slic3r::GUI::ObjectSettings::m_og_settings private
Referenced by sys_color_changed(), update_config_values(), and update_settings_list().
m_parent
wxWindow* Slic3r::GUI::OG_Settings::m_parent protected inherited
Referenced by Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::OG_Settings::parent(), update_config_values(), update_settings_list(), and Slic3r::GUI::ObjectManipulation::update_warning_icon_state().
m_settings_list_sizer
wxBoxSizer* Slic3r::GUI::ObjectSettings::m_settings_list_sizer { nullptr } private
Referenced by ObjectSettings(), and update_settings_list().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectSettings.hpp
src/slic3r/GUI/GUI_ObjectSettings.cpp