Prusa Slicer: Eigen::internal::CompressedStorage< _Scalar, _StorageIndex > Class Template Reference
Eigen::internal::CompressedStorage< _Scalar, _StorageIndex > Class Template Reference
#include <src/eigen/Eigen/src/SparseCore/CompressedStorage.h>
Public Types
typedef _Scalar Scalar
typedef _StorageIndex StorageIndex
Public Member Functions
CompressedStorage ()
CompressedStorage (Index size)
CompressedStorage (const CompressedStorage &other)
CompressedStorage & operator= (const CompressedStorage &other)
void swap (CompressedStorage &other)
~CompressedStorage ()
void reserve (Index size)
void squeeze ()
void resize (Index size, double reserveSizeFactor=0)
void append (const Scalar &v, Index i)
Index size () const
Index allocatedSize () const
void clear ()
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * indexPtr () const
StorageIndex * indexPtr ()
Scalar & value (Index i)
const Scalar & value (Index i) const
StorageIndex & index (Index i)
const StorageIndex & index (Index i) const
Index searchLowerIndex (Index key) const
Index searchLowerIndex (Index start, Index end, Index key) const
Scalar at (Index key, const Scalar &defaultValue=Scalar(0)) const
Scalar atInRange (Index start, Index end, Index key, const Scalar &defaultValue=Scalar(0)) const
Scalar & atWithInsertion (Index key, const Scalar &defaultValue=Scalar(0))
void prune (const Scalar &reference, const RealScalar &epsilon=NumTraits< RealScalar >::dummy_precision())
Protected Types
typedef NumTraits< Scalar >::Real RealScalar
Protected Member Functions
void reallocate (Index size)
Protected Attributes
Scalar * m_values
StorageIndex * m_indices
Index m_size
Index m_allocatedSize
Detailed Description
template<typename _Scalar, typename _StorageIndex>
class Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >
Member Typedef Documentation
RealScalar
template<typename _Scalar , typename _StorageIndex > typedef NumTraits<Scalar>::Real Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::RealScalar protected
Scalar
template<typename _Scalar , typename _StorageIndex > typedef _Scalar Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::Scalar
StorageIndex
template<typename _Scalar , typename _StorageIndex > typedef _StorageIndex Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::StorageIndex
Constructor & Destructor Documentation
CompressedStorage() [1/3]
template<typename _Scalar , typename _StorageIndex > Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::CompressedStorage () inline
      : m_values(0), m_indices(0), m_size(0), m_allocatedSize(0)
    {}
CompressedStorage() [2/3]
template<typename _Scalar , typename _StorageIndex > Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::CompressedStorage (Index size) inline explicit
      : m_values(0), m_indices(0), m_size(0), m_allocatedSize(0)
    {
      resize(size);
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size().
CompressedStorage() [3/3]
template<typename _Scalar , typename _StorageIndex > Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::CompressedStorage (const CompressedStorage< _Scalar, _StorageIndex > & other) inline
      : m_values(0), m_indices(0), m_size(0), m_allocatedSize(0)
    {
      *this = other;
    }
~CompressedStorage()
template<typename _Scalar , typename _StorageIndex > Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::~CompressedStorage () inline
    {
      delete[] m_values;
      delete[] m_indices;
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values.
Member Function Documentation
allocatedSize()
template<typename _Scalar , typename _StorageIndex > Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::allocatedSize () const inline
{ return m_allocatedSize; }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_allocatedSize.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed().
append()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append (const Scalar & v, Index i) inline
    {
      Index id = m_size;
      resize(m_size+1, 1);
      m_values[id] = v;
      m_indices[id] = internal::convert_index<StorageIndex>(i);
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize().
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInnerUnordered().
at()
template<typename _Scalar , typename _StorageIndex > Scalar Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::at (Index key, const Scalar & defaultValue = Scalar(0)) const inline
Returns
the stored value at index key If the value does not exist, then the value defaultValue is returned without any insertion.
    {
      if (m_size==0)
        return defaultValue;
      else if (key==m_indices[m_size-1])
        return m_values[m_size-1];
      // ^^  optimization: let's first check if it is the last coefficient
      // (very common in high level algorithms)
      const Index id = searchLowerIndex(0,m_size-1,key);
      return ((id<m_size) && (m_indices[id]==key)) ? m_values[id] : defaultValue;
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex().
atInRange()
template<typename _Scalar , typename _StorageIndex > Scalar Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atInRange (Index start, Index end, Index key, const Scalar & defaultValue = Scalar(0)) const inline
Like at(), but the search is performed in the range [start,end)
    {
      if (start>=end)
        return defaultValue;
      else if (end>start && key==m_indices[end-1])
        return m_values[end-1];
      // ^^  optimization: let's first check if it is the last coefficient
      // (very common in high level algorithms)
      const Index id = searchLowerIndex(start,end-1,key);
      return ((id<end) && (m_indices[id]==key)) ? m_values[id] : defaultValue;
    }
References Eigen::end(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex().
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff().
atWithInsertion()
template<typename _Scalar , typename _StorageIndex > Scalar & Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atWithInsertion (Index key, const Scalar & defaultValue = Scalar(0)) inline
Returns
a reference to the value at index key If the value does not exist, then the value defaultValue is inserted such that the keys are sorted.
    {
      Index id = searchLowerIndex(0,m_size,key);
      if (id>=m_size || m_indices[id]!=key)
      {
        if (m_allocatedSize<m_size+1)
        {
          m_allocatedSize = 2*(m_size+1);
          internal::scoped_array<Scalar> newValues(m_allocatedSize);
          internal::scoped_array<StorageIndex> newIndices(m_allocatedSize);
          // copy first chunk
          internal::smart_copy(m_values,  m_values +id, newValues.ptr());
          internal::smart_copy(m_indices, m_indices+id, newIndices.ptr());
          // copy the rest
          if(m_size>id)
          {
            internal::smart_copy(m_values +id,  m_values +m_size, newValues.ptr() +id+1);
            internal::smart_copy(m_indices+id,  m_indices+m_size, newIndices.ptr()+id+1);
          }
          std::swap(m_values,newValues.ptr());
          std::swap(m_indices,newIndices.ptr());
        }
        else if(m_size>id)
        {
          internal::smart_memmove(m_values +id, m_values +m_size, m_values +id+1);
          internal::smart_memmove(m_indices+id, m_indices+m_size, m_indices+id+1);
        }
        m_size++;
        m_indices[id] = internal::convert_index<StorageIndex>(key);
        m_values[id] = defaultValue;
      }
      return m_values[id];
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_allocatedSize, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values, Eigen::internal::scoped_array< T >::ptr(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex(), Eigen::internal::smart_copy(), and Eigen::internal::smart_memmove().
clear()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::clear () inline
{ m_size = 0; }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero().
index() [1/2]
template<typename _Scalar , typename _StorageIndex > StorageIndex & Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index (Index i) inline
{ eigen_internal_assert(m_indices!=0); return m_indices[i]; }
References eigen_internal_assert, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::collapseDuplicates(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::prune(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors().
index() [2/2]
template<typename _Scalar , typename _StorageIndex > const StorageIndex & Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index (Index i) const inline
{ eigen_internal_assert(m_indices!=0); return m_indices[i]; }
References eigen_internal_assert, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices.
indexPtr() [1/2]
template<typename _Scalar , typename _StorageIndex > StorageIndex * Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::indexPtr () inline
{ return m_indices; }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices.
indexPtr() [2/2]
template<typename _Scalar , typename _StorageIndex > const StorageIndex * Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::indexPtr () const inline
{ return m_indices; }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setIdentity().
operator=()
template<typename _Scalar , typename _StorageIndex > CompressedStorage & Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::operator= (const CompressedStorage< _Scalar, _StorageIndex > & other) inline
    {
      resize(other.size());
      if(other.size()>0)
      {
        internal::smart_copy(other.m_values,  other.m_values  + m_size, m_values);
        internal::smart_copy(other.m_indices, other.m_indices + m_size, m_indices);
      }
      return *this;
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), and Eigen::internal::smart_copy().
prune()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::prune (const Scalar & reference, const RealScalar & epsilon = NumTraits<RealScalar>::dummy_precision()) inline
    {
      Index k = 0;
      Index n = size();
      for (Index i=0; i<n; ++i)
      {
        if (!internal::isMuchSmallerThan(value(i), reference, epsilon))
        {
          value(k) = value(i);
          index(k) = index(i);
          ++k;
        }
      }
      resize(k,0);
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::internal::isMuchSmallerThan(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
reallocate()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate (Index size) inline protected
    {
      #ifdef EIGEN_SPARSE_COMPRESSED_STORAGE_REALLOCATE_PLUGIN
        EIGEN_SPARSE_COMPRESSED_STORAGE_REALLOCATE_PLUGIN
      #endif
      eigen_internal_assert(size!=m_allocatedSize);
      internal::scoped_array<Scalar> newValues(size);
      internal::scoped_array<StorageIndex> newIndices(size);
      Index copySize = (std::min)(size, m_size);
      if (copySize>0) {
        internal::smart_copy(m_values, m_values+copySize, newValues.ptr());
        internal::smart_copy(m_indices, m_indices+copySize, newIndices.ptr());
      }
      std::swap(m_values,newValues.ptr());
      std::swap(m_indices,newIndices.ptr());
      m_allocatedSize = size;
    }
References eigen_internal_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_allocatedSize, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values, Eigen::internal::scoped_array< T >::ptr(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), and Eigen::internal::smart_copy().
Referenced by Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::squeeze().
reserve()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve (Index size) inline
    {
      Index newAllocatedSize = m_size + size;
      if (newAllocatedSize > m_allocatedSize)
        reallocate(newAllocatedSize);
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_allocatedSize, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size().
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserve(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors().
resize()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize (Index size, double reserveSizeFactor = 0) inline
    {
      if (m_allocatedSize<size)
      {
        Index realloc_size = (std::min<Index>)(NumTraits<StorageIndex>::highest(),  size + Index(reserveSizeFactor*double(size)));
        if(realloc_size<size)
          internal::throw_std_bad_alloc();
        reallocate(realloc_size);
      }
      m_size = size;
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_allocatedSize, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), and Eigen::internal::throw_std_bad_alloc().
Referenced by Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::CompressedStorage(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::collapseDuplicates(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::prune(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resizeNonZeros(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setIdentity().
searchLowerIndex() [1/2]
template<typename _Scalar , typename _StorageIndex > Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex (Index key) const inline
Returns
the largest k such that for all j in [0,k) index[j]<key
    {
      return searchLowerIndex(0, m_size, key);
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex().
Referenced by Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::at(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atInRange(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atWithInsertion(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex().
searchLowerIndex() [2/2]
template<typename _Scalar , typename _StorageIndex > Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex (Index start, Index end, Index key) const inline
Returns
the largest k in [start,end) such that for all j in [start,k) index[j]<key
    {
      while(end>start)
      {
        Index mid = (end+start)>>1;
        if (m_indices[mid]<key)
          start = mid+1;
        else
          end = mid;
      }
      return start;
    }
References Eigen::end(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices.
size()
template<typename _Scalar , typename _StorageIndex > Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size () const inline
{ return m_size; }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size.
Referenced by Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::CompressedStorage(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::operator=(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::prune(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::startVec().
squeeze()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::squeeze () inline
    {
      if (m_allocatedSize>m_size)
        reallocate(m_size);
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_allocatedSize, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate().
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed().
swap()
template<typename _Scalar , typename _StorageIndex > void Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::swap (CompressedStorage< _Scalar, _StorageIndex > & other) inline
    {
      std::swap(m_values, other.m_values);
      std::swap(m_indices, other.m_indices);
      std::swap(m_size, other.m_size);
      std::swap(m_allocatedSize, other.m_allocatedSize);
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_allocatedSize, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::swap().
value() [1/2]
template<typename _Scalar , typename _StorageIndex > Scalar & Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value (Index i) inline
{ eigen_internal_assert(m_values!=0); return m_values[i]; }
References eigen_internal_assert, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::collapseDuplicates(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInnerUnordered(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::prune(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors().
value() [2/2]
template<typename _Scalar , typename _StorageIndex > const Scalar & Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value (Index i) const inline
{ eigen_internal_assert(m_values!=0); return m_values[i]; }
References eigen_internal_assert, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values.
valuePtr() [1/2]
template<typename _Scalar , typename _StorageIndex > Scalar * Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::valuePtr () inline
{ return m_values; }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values.
valuePtr() [2/2]
template<typename _Scalar , typename _StorageIndex > const Scalar * Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::valuePtr () const inline
{ return m_values; }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setIdentity(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr().
Member Data Documentation
m_allocatedSize
template<typename _Scalar , typename _StorageIndex > Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_allocatedSize protected
Referenced by Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::allocatedSize(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::squeeze(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::swap().
m_indices
template<typename _Scalar , typename _StorageIndex > StorageIndex* Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_indices protected
Referenced by Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::~CompressedStorage(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::at(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atInRange(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::indexPtr(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::indexPtr(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::operator=(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::swap().
m_size
template<typename _Scalar , typename _StorageIndex > Index Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_size protected
Referenced by Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::at(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::clear(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::operator=(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::squeeze(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::swap().
m_values
template<typename _Scalar , typename _StorageIndex > Scalar* Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::m_values protected
Referenced by Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::~CompressedStorage(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::at(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atInRange(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atWithInsertion(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::operator=(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reallocate(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::swap(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::valuePtr(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::valuePtr().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SparseCore/CompressedStorage.h