Prusa Slicer: agg::renderer_base< PixelFormat > Class Template Reference
agg::renderer_base< PixelFormat > Class Template Reference
#include <src/agg/agg_renderer_base.h>
Public Types
typedef PixelFormat pixfmt_type
typedef pixfmt_type::color_type color_type
typedef pixfmt_type::row_data row_data
Public Member Functions
renderer_base ()
renderer_base (pixfmt_type &ren)
void attach (pixfmt_type &ren)
const pixfmt_type & ren () const
pixfmt_type & ren ()
unsigned width () const
unsigned height () const
bool clip_box (int x1, int y1, int x2, int y2)
void reset_clipping (bool visibility)
void clip_box_naked (int x1, int y1, int x2, int y2)
bool inbox (int x, int y) const
const rect_i & clip_box () const
int xmin () const
int ymin () const
int xmax () const
int ymax () const
const rect_i & bounding_clip_box () const
int bounding_xmin () const
int bounding_ymin () const
int bounding_xmax () const
int bounding_ymax () const
void clear (const color_type &c)
void fill (const color_type &c)
void copy_pixel (int x, int y, const color_type &c)
void blend_pixel (int x, int y, const color_type &c, cover_type cover)
color_type pixel (int x, int y) const
void copy_hline (int x1, int y, int x2, const color_type &c)
void copy_vline (int x, int y1, int y2, const color_type &c)
void blend_hline (int x1, int y, int x2, const color_type &c, cover_type cover)
void blend_vline (int x, int y1, int y2, const color_type &c, cover_type cover)
void copy_bar (int x1, int y1, int x2, int y2, const color_type &c)
void blend_bar (int x1, int y1, int x2, int y2, const color_type &c, cover_type cover)
void blend_solid_hspan (int x, int y, int len, const color_type &c, const cover_type *covers)
void blend_solid_vspan (int x, int y, int len, const color_type &c, const cover_type *covers)
void copy_color_hspan (int x, int y, int len, const color_type *colors)
void copy_color_vspan (int x, int y, int len, const color_type *colors)
void blend_color_hspan (int x, int y, int len, const color_type *colors, const cover_type *covers, cover_type cover=agg::cover_full)
void blend_color_vspan (int x, int y, int len, const color_type *colors, const cover_type *covers, cover_type cover=agg::cover_full)
rect_i clip_rect_area (rect_i &dst, rect_i &src, int wsrc, int hsrc) const
template<class RenBuf >
void copy_from (const RenBuf &src, const rect_i *rect_src_ptr=0, int dx=0, int dy=0)
template<class SrcPixelFormatRenderer >
void blend_from (const SrcPixelFormatRenderer &src, const rect_i *rect_src_ptr=0, int dx=0, int dy=0, cover_type cover=agg::cover_full)
template<class SrcPixelFormatRenderer >
void blend_from_color (const SrcPixelFormatRenderer &src, const color_type &color, const rect_i *rect_src_ptr=0, int dx=0, int dy=0, cover_type cover=agg::cover_full)
template<class SrcPixelFormatRenderer >
void blend_from_lut (const SrcPixelFormatRenderer &src, const color_type *color_lut, const rect_i *rect_src_ptr=0, int dx=0, int dy=0, cover_type cover=agg::cover_full)
Private Attributes
pixfmt_type * m_ren
rect_i m_clip_box
Detailed Description
template<class PixelFormat>
class agg::renderer_base< PixelFormat >
Member Typedef Documentation
color_type
template<class PixelFormat > typedef pixfmt_type::color_type agg::renderer_base< PixelFormat >::color_type
pixfmt_type
template<class PixelFormat > typedef PixelFormat agg::renderer_base< PixelFormat >::pixfmt_type
row_data
template<class PixelFormat > typedef pixfmt_type::row_data agg::renderer_base< PixelFormat >::row_data
Constructor & Destructor Documentation
renderer_base() [1/2]
template<class PixelFormat > agg::renderer_base< PixelFormat >::renderer_base () inline
: m_ren(0), m_clip_box(1, 1, 0, 0) {}
renderer_base() [2/2]
template<class PixelFormat > agg::renderer_base< PixelFormat >::renderer_base (pixfmt_type & ren) inline explicit
                                                 :
            m_ren(&ren),
            m_clip_box(0, 0, ren.width() - 1, ren.height() - 1)
        {}
Member Function Documentation
attach()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::attach (pixfmt_type & ren) inline
        {
            m_ren = &ren;
            m_clip_box = rect_i(0, 0, ren.width() - 1, ren.height() - 1);
        }
References agg::renderer_base< PixelFormat >::m_clip_box, agg::renderer_base< PixelFormat >::m_ren, and agg::renderer_base< PixelFormat >::ren().
blend_bar()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::blend_bar (int x1, int y1, int x2, int y2, const color_type & c, cover_type cover) inline
        {
            rect_i rc(x1, y1, x2, y2);
            rc.normalize();
            if(rc.clip(clip_box()))
            {
                int y;
                for(y = rc.y1; y <= rc.y2; y++)
                {
                    m_ren->blend_hline(rc.x1,
                                       y,
                                       unsigned(rc.x2 - rc.x1 + 1),
                                       c,
                                       cover);
                }
            }
        }
References agg::rect_base< T >::clip(), agg::renderer_base< PixelFormat >::clip_box(), agg::renderer_base< PixelFormat >::m_ren, agg::rect_base< T >::normalize(), agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
blend_color_hspan()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::blend_color_hspan (int x, int y, int len, const color_type * colors, const cover_type * covers, cover_type cover = agg::cover_full) inline
        {
            if(y > ymax()) return;
            if(y < ymin()) return;
            if(x < xmin())
            {
                int d = xmin() - x;
                len -= d;
                if(len <= 0) return;
                if(covers) covers += d;
                colors += d;
                x = xmin();
            }
            if(x + len > xmax())
            {
                len = xmax() - x + 1;
                if(len <= 0) return;
            }
            m_ren->blend_color_hspan(x, y, len, colors, covers, cover);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
blend_color_vspan()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::blend_color_vspan (int x, int y, int len, const color_type * colors, const cover_type * covers, cover_type cover = agg::cover_full) inline
        {
            if(x > xmax()) return;
            if(x < xmin()) return;
            if(y < ymin())
            {
                int d = ymin() - y;
                len -= d;
                if(len <= 0) return;
                if(covers) covers += d;
                colors += d;
                y = ymin();
            }
            if(y + len > ymax())
            {
                len = ymax() - y + 1;
                if(len <= 0) return;
            }
            m_ren->blend_color_vspan(x, y, len, colors, covers, cover);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
blend_from()
template<class PixelFormat > template<class SrcPixelFormatRenderer > void agg::renderer_base< PixelFormat >::blend_from (const SrcPixelFormatRenderer & src, const rect_i * rect_src_ptr = 0, int dx = 0, int dy = 0, cover_type cover = agg::cover_full) inline
        {
            rect_i rsrc(0, 0, src.width(), src.height());
            if(rect_src_ptr)
            {
                rsrc.x1 = rect_src_ptr->x1;
                rsrc.y1 = rect_src_ptr->y1;
                rsrc.x2 = rect_src_ptr->x2 + 1;
                rsrc.y2 = rect_src_ptr->y2 + 1;
            }
            // Version with xdst, ydst (absolute positioning)
            //rect_i rdst(xdst, ydst, xdst + rsrc.x2 - rsrc.x1, ydst + rsrc.y2 - rsrc.y1);
            // Version with dx, dy (relative positioning)
            rect_i rdst(rsrc.x1 + dx, rsrc.y1 + dy, rsrc.x2 + dx, rsrc.y2 + dy);
            rect_i rc = clip_rect_area(rdst, rsrc, src.width(), src.height());
            if(rc.x2 > 0)
            {
                int incy = 1;
                if(rdst.y1 > rsrc.y1)
                {
                    rsrc.y1 += rc.y2 - 1;
                    rdst.y1 += rc.y2 - 1;
                    incy = -1;
                }
                while(rc.y2 > 0)
                {
                    typename SrcPixelFormatRenderer::row_data rw = src.row(rsrc.y1);
                    if(rw.ptr)
                    {
                        int x1src = rsrc.x1;
                        int x1dst = rdst.x1;
                        int len   = rc.x2;
                        if(rw.x1 > x1src)
{
                            x1dst += rw.x1 - x1src;
                            len   -= rw.x1 - x1src;
                            x1src  = rw.x1;
                        }
                        if(len > 0)
{
                            if(x1src + len-1 > rw.x2)
{
                                len -= x1src + len - rw.x2 - 1;
                            }
                            if(len > 0)
{
                                m_ren->blend_from(src,
                                                  x1dst, rdst.y1,
                                                  x1src, rsrc.y1,
                                                  len,
                                                  cover);
                            }
                        }
                    }
                    rdst.y1 += incy;
                    rsrc.y1 += incy;
                    --rc.y2;
                }
            }
        }
References agg::renderer_base< PixelFormat >::clip_rect_area(), agg::renderer_base< PixelFormat >::m_ren, agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
blend_from_color()
template<class PixelFormat > template<class SrcPixelFormatRenderer > void agg::renderer_base< PixelFormat >::blend_from_color (const SrcPixelFormatRenderer & src, const color_type & color, const rect_i * rect_src_ptr = 0, int dx = 0, int dy = 0, cover_type cover = agg::cover_full) inline
        {
            rect_i rsrc(0, 0, src.width(), src.height());
            if(rect_src_ptr)
            {
                rsrc.x1 = rect_src_ptr->x1;
                rsrc.y1 = rect_src_ptr->y1;
                rsrc.x2 = rect_src_ptr->x2 + 1;
                rsrc.y2 = rect_src_ptr->y2 + 1;
            }
            // Version with xdst, ydst (absolute positioning)
            //rect_i rdst(xdst, ydst, xdst + rsrc.x2 - rsrc.x1, ydst + rsrc.y2 - rsrc.y1);
            // Version with dx, dy (relative positioning)
            rect_i rdst(rsrc.x1 + dx, rsrc.y1 + dy, rsrc.x2 + dx, rsrc.y2 + dy);
            rect_i rc = clip_rect_area(rdst, rsrc, src.width(), src.height());
            if(rc.x2 > 0)
            {
                int incy = 1;
                if(rdst.y1 > rsrc.y1)
                {
                    rsrc.y1 += rc.y2 - 1;
                    rdst.y1 += rc.y2 - 1;
                    incy = -1;
                }
                while(rc.y2 > 0)
                {
                    typename SrcPixelFormatRenderer::row_data rw = src.row(rsrc.y1);
                    if(rw.ptr)
                    {
                        int x1src = rsrc.x1;
                        int x1dst = rdst.x1;
                        int len   = rc.x2;
                        if(rw.x1 > x1src)
{
                            x1dst += rw.x1 - x1src;
                            len   -= rw.x1 - x1src;
                            x1src  = rw.x1;
                        }
                        if(len > 0)
{
                            if(x1src + len-1 > rw.x2)
{
                                len -= x1src + len - rw.x2 - 1;
                            }
                            if(len > 0)
{
                                m_ren->blend_from_color(src,
                                                        color,
                                                        x1dst, rdst.y1,
                                                        x1src, rsrc.y1,
                                                        len,
                                                        cover);
                            }
                        }
                    }
                    rdst.y1 += incy;
                    rsrc.y1 += incy;
                    --rc.y2;
                }
            }
        }
References agg::renderer_base< PixelFormat >::clip_rect_area(), agg::renderer_base< PixelFormat >::m_ren, agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
blend_from_lut()
template<class PixelFormat > template<class SrcPixelFormatRenderer > void agg::renderer_base< PixelFormat >::blend_from_lut (const SrcPixelFormatRenderer & src, const color_type * color_lut, const rect_i * rect_src_ptr = 0, int dx = 0, int dy = 0, cover_type cover = agg::cover_full) inline
        {
            rect_i rsrc(0, 0, src.width(), src.height());
            if(rect_src_ptr)
            {
                rsrc.x1 = rect_src_ptr->x1;
                rsrc.y1 = rect_src_ptr->y1;
                rsrc.x2 = rect_src_ptr->x2 + 1;
                rsrc.y2 = rect_src_ptr->y2 + 1;
            }
            // Version with xdst, ydst (absolute positioning)
            //rect_i rdst(xdst, ydst, xdst + rsrc.x2 - rsrc.x1, ydst + rsrc.y2 - rsrc.y1);
            // Version with dx, dy (relative positioning)
            rect_i rdst(rsrc.x1 + dx, rsrc.y1 + dy, rsrc.x2 + dx, rsrc.y2 + dy);
            rect_i rc = clip_rect_area(rdst, rsrc, src.width(), src.height());
            if(rc.x2 > 0)
            {
                int incy = 1;
                if(rdst.y1 > rsrc.y1)
                {
                    rsrc.y1 += rc.y2 - 1;
                    rdst.y1 += rc.y2 - 1;
                    incy = -1;
                }
                while(rc.y2 > 0)
                {
                    typename SrcPixelFormatRenderer::row_data rw = src.row(rsrc.y1);
                    if(rw.ptr)
                    {
                        int x1src = rsrc.x1;
                        int x1dst = rdst.x1;
                        int len   = rc.x2;
                        if(rw.x1 > x1src)
{
                            x1dst += rw.x1 - x1src;
                            len   -= rw.x1 - x1src;
                            x1src  = rw.x1;
                        }
                        if(len > 0)
{
                            if(x1src + len-1 > rw.x2)
{
                                len -= x1src + len - rw.x2 - 1;
                            }
                            if(len > 0)
{
                                m_ren->blend_from_lut(src,
                                                      color_lut,
                                                      x1dst, rdst.y1,
                                                      x1src, rsrc.y1,
                                                      len,
                                                      cover);
                            }
                        }
                    }
                    rdst.y1 += incy;
                    rsrc.y1 += incy;
                    --rc.y2;
                }
            }
        }
References agg::renderer_base< PixelFormat >::clip_rect_area(), agg::renderer_base< PixelFormat >::m_ren, agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
blend_hline()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::blend_hline (int x1, int y, int x2, const color_type & c, cover_type cover) inline
        {
            if(x1 > x2) { int t = x2; x2 = x1; x1 = t; }
            if(y  > ymax()) return;
            if(y  < ymin()) return;
            if(x1 > xmax()) return;
            if(x2 < xmin()) return;
            if(x1 < xmin()) x1 = xmin();
            if(x2 > xmax()) x2 = xmax();
            m_ren->blend_hline(x1, y, x2 - x1 + 1, c, cover);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
blend_pixel()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::blend_pixel (int x, int y, const color_type & c, cover_type cover) inline
        {
            if(inbox(x, y))
            {
                m_ren->blend_pixel(x, y, c, cover);
            }
        }
References agg::renderer_base< PixelFormat >::inbox(), and agg::renderer_base< PixelFormat >::m_ren.
blend_solid_hspan()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::blend_solid_hspan (int x, int y, int len, const color_type & c, const cover_type * covers) inline
        {
            if(y > ymax()) return;
            if(y < ymin()) return;
            if(x < xmin())
            {
                len -= xmin() - x;
                if(len <= 0) return;
                covers += xmin() - x;
                x = xmin();
            }
            if(x + len > xmax())
            {
                len = xmax() - x + 1;
                if(len <= 0) return;
            }
            m_ren->blend_solid_hspan(x, y, len, c, covers);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
blend_solid_vspan()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::blend_solid_vspan (int x, int y, int len, const color_type & c, const cover_type * covers) inline
        {
            if(x > xmax()) return;
            if(x < xmin()) return;
            if(y < ymin())
            {
                len -= ymin() - y;
                if(len <= 0) return;
                covers += ymin() - y;
                y = ymin();
            }
            if(y + len > ymax())
            {
                len = ymax() - y + 1;
                if(len <= 0) return;
            }
            m_ren->blend_solid_vspan(x, y, len, c, covers);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
blend_vline()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::blend_vline (int x, int y1, int y2, const color_type & c, cover_type cover) inline
        {
            if(y1 > y2) { int t = y2; y2 = y1; y1 = t; }
            if(x  > xmax()) return;
            if(x  < xmin()) return;
            if(y1 > ymax()) return;
            if(y2 < ymin()) return;
            if(y1 < ymin()) y1 = ymin();
            if(y2 > ymax()) y2 = ymax();
            m_ren->blend_vline(x, y1, y2 - y1 + 1, c, cover);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
bounding_clip_box()
template<class PixelFormat > const rect_i & agg::renderer_base< PixelFormat >::bounding_clip_box () const inline
{ return m_clip_box;    }
References agg::renderer_base< PixelFormat >::m_clip_box.
bounding_xmax()
template<class PixelFormat > int agg::renderer_base< PixelFormat >::bounding_xmax () const inline
{ return m_clip_box.x2; }
References agg::renderer_base< PixelFormat >::m_clip_box, and agg::rect_base< T >::x2.
bounding_xmin()
template<class PixelFormat > int agg::renderer_base< PixelFormat >::bounding_xmin () const inline
{ return m_clip_box.x1; }
References agg::renderer_base< PixelFormat >::m_clip_box, and agg::rect_base< T >::x1.
bounding_ymax()
template<class PixelFormat > int agg::renderer_base< PixelFormat >::bounding_ymax () const inline
{ return m_clip_box.y2; }
References agg::renderer_base< PixelFormat >::m_clip_box, and agg::rect_base< T >::y2.
bounding_ymin()
template<class PixelFormat > int agg::renderer_base< PixelFormat >::bounding_ymin () const inline
{ return m_clip_box.y1; }
References agg::renderer_base< PixelFormat >::m_clip_box, and agg::rect_base< T >::y1.
clear()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::clear (const color_type & c) inline
        {
            unsigned y;
            if(width())
            {
                for(y = 0; y < height(); y++)
                {
                    m_ren->copy_hline(0, y, width(), c);
                }
            }
        }
References agg::renderer_base< PixelFormat >::height(), agg::renderer_base< PixelFormat >::m_ren, and agg::renderer_base< PixelFormat >::width().
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::clear(), and Slic3r::rasterize_polygons().
clip_box() [1/2]
template<class PixelFormat > const rect_i & agg::renderer_base< PixelFormat >::clip_box () const inline
{ return m_clip_box;    }
References agg::renderer_base< PixelFormat >::m_clip_box.
Referenced by agg::renderer_base< PixelFormat >::blend_bar(), agg::renderer_base< PixelFormat >::clip_rect_area(), and agg::renderer_base< PixelFormat >::copy_bar().
clip_box() [2/2]
template<class PixelFormat > bool agg::renderer_base< PixelFormat >::clip_box (int x1, int y1, int x2, int y2) inline
        {
            rect_i cb(x1, y1, x2, y2);
            cb.normalize();
            if(cb.clip(rect_i(0, 0, width() - 1, height() - 1)))
            {
                m_clip_box = cb;
                return true;
            }
            m_clip_box.x1 = 1;
            m_clip_box.y1 = 1;
            m_clip_box.x2 = 0;
            m_clip_box.y2 = 0;
            return false;
        }
References agg::rect_base< T >::clip(), agg::renderer_base< PixelFormat >::height(), agg::renderer_base< PixelFormat >::m_clip_box, agg::rect_base< T >::normalize(), agg::renderer_base< PixelFormat >::width(), agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
clip_box_naked()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::clip_box_naked (int x1, int y1, int x2, int y2) inline
        {
            m_clip_box.x1 = x1;
            m_clip_box.y1 = y1;
            m_clip_box.x2 = x2;
            m_clip_box.y2 = y2;
        }
References agg::renderer_base< PixelFormat >::m_clip_box, agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
clip_rect_area()
template<class PixelFormat > rect_i agg::renderer_base< PixelFormat >::clip_rect_area (rect_i & dst, rect_i & src, int wsrc, int hsrc) const inline
        {
            rect_i rc(0,0,0,0);
            rect_i cb = clip_box();
            ++cb.x2;
            ++cb.y2;
            if(src.x1 < 0)
            {
                dst.x1 -= src.x1;
                src.x1 = 0;
            }
            if(src.y1 < 0)
            {
                dst.y1 -= src.y1;
                src.y1 = 0;
            }
            if(src.x2 > wsrc) src.x2 = wsrc;
            if(src.y2 > hsrc) src.y2 = hsrc;
            if(dst.x1 < cb.x1)
            {
                src.x1 += cb.x1 - dst.x1;
                dst.x1 = cb.x1;
            }
            if(dst.y1 < cb.y1)
            {
                src.y1 += cb.y1 - dst.y1;
                dst.y1 = cb.y1;
            }
            if(dst.x2 > cb.x2) dst.x2 = cb.x2;
            if(dst.y2 > cb.y2) dst.y2 = cb.y2;
            rc.x2 = dst.x2 - dst.x1;
            rc.y2 = dst.y2 - dst.y1;
            if(rc.x2 > src.x2 - src.x1) rc.x2 = src.x2 - src.x1;
            if(rc.y2 > src.y2 - src.y1) rc.y2 = src.y2 - src.y1;
            return rc;
        }
References agg::renderer_base< PixelFormat >::clip_box(), agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
Referenced by agg::renderer_base< PixelFormat >::blend_from(), agg::renderer_base< PixelFormat >::blend_from_color(), agg::renderer_base< PixelFormat >::blend_from_lut(), and agg::renderer_base< PixelFormat >::copy_from().
copy_bar()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::copy_bar (int x1, int y1, int x2, int y2, const color_type & c) inline
        {
            rect_i rc(x1, y1, x2, y2);
            rc.normalize();
            if(rc.clip(clip_box()))
            {
                int y;
                for(y = rc.y1; y <= rc.y2; y++)
                {
                    m_ren->copy_hline(rc.x1, y, unsigned(rc.x2 - rc.x1 + 1), c);
                }
            }
        }
References agg::rect_base< T >::clip(), agg::renderer_base< PixelFormat >::clip_box(), agg::renderer_base< PixelFormat >::m_ren, agg::rect_base< T >::normalize(), agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
copy_color_hspan()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::copy_color_hspan (int x, int y, int len, const color_type * colors) inline
        {
            if(y > ymax()) return;
            if(y < ymin()) return;
            if(x < xmin())
            {
                int d = xmin() - x;
                len -= d;
                if(len <= 0) return;
                colors += d;
                x = xmin();
            }
            if(x + len > xmax())
            {
                len = xmax() - x + 1;
                if(len <= 0) return;
            }
            m_ren->copy_color_hspan(x, y, len, colors);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
copy_color_vspan()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::copy_color_vspan (int x, int y, int len, const color_type * colors) inline
        {
            if(x > xmax()) return;
            if(x < xmin()) return;
            if(y < ymin())
            {
                int d = ymin() - y;
                len -= d;
                if(len <= 0) return;
                colors += d;
                y = ymin();
            }
            if(y + len > ymax())
            {
                len = ymax() - y + 1;
                if(len <= 0) return;
            }
            m_ren->copy_color_vspan(x, y, len, colors);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
copy_from()
template<class PixelFormat > template<class RenBuf > void agg::renderer_base< PixelFormat >::copy_from (const RenBuf & src, const rect_i * rect_src_ptr = 0, int dx = 0, int dy = 0) inline
        {
            rect_i rsrc(0, 0, src.width(), src.height());
            if(rect_src_ptr)
            {
                rsrc.x1 = rect_src_ptr->x1;
                rsrc.y1 = rect_src_ptr->y1;
                rsrc.x2 = rect_src_ptr->x2 + 1;
                rsrc.y2 = rect_src_ptr->y2 + 1;
            }
            // Version with xdst, ydst (absolute positioning)
            //rect_i rdst(xdst, ydst, xdst + rsrc.x2 - rsrc.x1, ydst + rsrc.y2 - rsrc.y1);
            // Version with dx, dy (relative positioning)
            rect_i rdst(rsrc.x1 + dx, rsrc.y1 + dy, rsrc.x2 + dx, rsrc.y2 + dy);
            rect_i rc = clip_rect_area(rdst, rsrc, src.width(), src.height());
            if(rc.x2 > 0)
            {
                int incy = 1;
                if(rdst.y1 > rsrc.y1)
                {
                    rsrc.y1 += rc.y2 - 1;
                    rdst.y1 += rc.y2 - 1;
                    incy = -1;
                }
                while(rc.y2 > 0)
                {
                    m_ren->copy_from(src,
                                     rdst.x1, rdst.y1,
                                     rsrc.x1, rsrc.y1,
                                     rc.x2);
                    rdst.y1 += incy;
                    rsrc.y1 += incy;
                    --rc.y2;
                }
            }
        }
References agg::renderer_base< PixelFormat >::clip_rect_area(), agg::renderer_base< PixelFormat >::m_ren, agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
copy_hline()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::copy_hline (int x1, int y, int x2, const color_type & c) inline
        {
            if(x1 > x2) { int t = x2; x2 = x1; x1 = t; }
            if(y  > ymax()) return;
            if(y  < ymin()) return;
            if(x1 > xmax()) return;
            if(x2 < xmin()) return;
            if(x1 < xmin()) x1 = xmin();
            if(x2 > xmax()) x2 = xmax();
            m_ren->copy_hline(x1, y, x2 - x1 + 1, c);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
copy_pixel()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::copy_pixel (int x, int y, const color_type & c) inline
        {
            if(inbox(x, y))
            {
                m_ren->copy_pixel(x, y, c);
            }
        }
References agg::renderer_base< PixelFormat >::inbox(), and agg::renderer_base< PixelFormat >::m_ren.
copy_vline()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::copy_vline (int x, int y1, int y2, const color_type & c) inline
        {
            if(y1 > y2) { int t = y2; y2 = y1; y1 = t; }
            if(x  > xmax()) return;
            if(x  < xmin()) return;
            if(y1 > ymax()) return;
            if(y2 < ymin()) return;
            if(y1 < ymin()) y1 = ymin();
            if(y2 > ymax()) y2 = ymax();
            m_ren->copy_vline(x, y1, y2 - y1 + 1, c);
        }
References agg::renderer_base< PixelFormat >::m_ren, agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
fill()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::fill (const color_type & c) inline
        {
            unsigned y;
            if(width())
            {
                for(y = 0; y < height(); y++)
                {
                    m_ren->blend_hline(0, y, width(), c, cover_mask);
                }
            }
        }
References agg::cover_mask, agg::renderer_base< PixelFormat >::height(), agg::renderer_base< PixelFormat >::m_ren, and agg::renderer_base< PixelFormat >::width().
height()
template<class PixelFormat > unsigned agg::renderer_base< PixelFormat >::height () const inline
{ return m_ren->height(); }
References agg::renderer_base< PixelFormat >::m_ren.
Referenced by agg::renderer_base< PixelFormat >::clear(), agg::renderer_base< PixelFormat >::clip_box(), agg::renderer_base< PixelFormat >::fill(), and agg::renderer_base< PixelFormat >::reset_clipping().
inbox()
template<class PixelFormat > bool agg::renderer_base< PixelFormat >::inbox (int x, int y) const inline
        {
            return x >= m_clip_box.x1 && y >= m_clip_box.y1 &&
                   x <= m_clip_box.x2 && y <= m_clip_box.y2;
        }
References agg::renderer_base< PixelFormat >::m_clip_box, agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
Referenced by agg::renderer_base< PixelFormat >::blend_pixel(), agg::renderer_base< PixelFormat >::copy_pixel(), and agg::renderer_base< PixelFormat >::pixel().
pixel()
template<class PixelFormat > color_type agg::renderer_base< PixelFormat >::pixel (int x, int y) const inline
        {
            return inbox(x, y) ?
                   m_ren->pixel(x, y) :
                   color_type::no_color();
        }
References agg::renderer_base< PixelFormat >::inbox(), and agg::renderer_base< PixelFormat >::m_ren.
ren() [1/2]
template<class PixelFormat > pixfmt_type & agg::renderer_base< PixelFormat >::ren () inline
{ return *m_ren;  }
References agg::renderer_base< PixelFormat >::m_ren.
ren() [2/2]
template<class PixelFormat > const pixfmt_type & agg::renderer_base< PixelFormat >::ren () const inline
{ return *m_ren;  }
References agg::renderer_base< PixelFormat >::m_ren.
Referenced by agg::renderer_base< PixelFormat >::attach().
reset_clipping()
template<class PixelFormat > void agg::renderer_base< PixelFormat >::reset_clipping (bool visibility) inline
        {
            if(visibility)
            {
                m_clip_box.x1 = 0;
                m_clip_box.y1 = 0;
                m_clip_box.x2 = width() - 1;
                m_clip_box.y2 = height() - 1;
            }
            else
            {
                m_clip_box.x1 = 1;
                m_clip_box.y1 = 1;
                m_clip_box.x2 = 0;
                m_clip_box.y2 = 0;
            }
        }
References agg::renderer_base< PixelFormat >::height(), agg::renderer_base< PixelFormat >::m_clip_box, agg::renderer_base< PixelFormat >::width(), agg::rect_base< T >::x1, agg::rect_base< T >::x2, agg::rect_base< T >::y1, and agg::rect_base< T >::y2.
width()
template<class PixelFormat > unsigned agg::renderer_base< PixelFormat >::width () const inline
{ return m_ren->width();  }
References agg::renderer_base< PixelFormat >::m_ren.
Referenced by agg::renderer_base< PixelFormat >::clear(), agg::renderer_base< PixelFormat >::clip_box(), agg::renderer_base< PixelFormat >::fill(), and agg::renderer_base< PixelFormat >::reset_clipping().
xmax()
template<class PixelFormat > int agg::renderer_base< PixelFormat >::xmax () const inline
{ return m_clip_box.x2; }
References agg::renderer_base< PixelFormat >::m_clip_box, and agg::rect_base< T >::x2.
Referenced by agg::renderer_base< PixelFormat >::blend_color_hspan(), agg::renderer_base< PixelFormat >::blend_color_vspan(), agg::renderer_base< PixelFormat >::blend_hline(), agg::renderer_base< PixelFormat >::blend_solid_hspan(), agg::renderer_base< PixelFormat >::blend_solid_vspan(), agg::renderer_base< PixelFormat >::blend_vline(), agg::renderer_base< PixelFormat >::copy_color_hspan(), agg::renderer_base< PixelFormat >::copy_color_vspan(), agg::renderer_base< PixelFormat >::copy_hline(), and agg::renderer_base< PixelFormat >::copy_vline().
xmin()
template<class PixelFormat > int agg::renderer_base< PixelFormat >::xmin () const inline
{ return m_clip_box.x1; }
References agg::renderer_base< PixelFormat >::m_clip_box, and agg::rect_base< T >::x1.
Referenced by agg::renderer_base< PixelFormat >::blend_color_hspan(), agg::renderer_base< PixelFormat >::blend_color_vspan(), agg::renderer_base< PixelFormat >::blend_hline(), agg::renderer_base< PixelFormat >::blend_solid_hspan(), agg::renderer_base< PixelFormat >::blend_solid_vspan(), agg::renderer_base< PixelFormat >::blend_vline(), agg::renderer_base< PixelFormat >::copy_color_hspan(), agg::renderer_base< PixelFormat >::copy_color_vspan(), agg::renderer_base< PixelFormat >::copy_hline(), and agg::renderer_base< PixelFormat >::copy_vline().
ymax()
template<class PixelFormat > int agg::renderer_base< PixelFormat >::ymax () const inline
{ return m_clip_box.y2; }
References agg::renderer_base< PixelFormat >::m_clip_box, and agg::rect_base< T >::y2.
Referenced by agg::renderer_base< PixelFormat >::blend_color_hspan(), agg::renderer_base< PixelFormat >::blend_color_vspan(), agg::renderer_base< PixelFormat >::blend_hline(), agg::renderer_base< PixelFormat >::blend_solid_hspan(), agg::renderer_base< PixelFormat >::blend_solid_vspan(), agg::renderer_base< PixelFormat >::blend_vline(), agg::renderer_base< PixelFormat >::copy_color_hspan(), agg::renderer_base< PixelFormat >::copy_color_vspan(), agg::renderer_base< PixelFormat >::copy_hline(), and agg::renderer_base< PixelFormat >::copy_vline().
ymin()
template<class PixelFormat > int agg::renderer_base< PixelFormat >::ymin () const inline
{ return m_clip_box.y1; }
References agg::renderer_base< PixelFormat >::m_clip_box, and agg::rect_base< T >::y1.
Referenced by agg::renderer_base< PixelFormat >::blend_color_hspan(), agg::renderer_base< PixelFormat >::blend_color_vspan(), agg::renderer_base< PixelFormat >::blend_hline(), agg::renderer_base< PixelFormat >::blend_solid_hspan(), agg::renderer_base< PixelFormat >::blend_solid_vspan(), agg::renderer_base< PixelFormat >::blend_vline(), agg::renderer_base< PixelFormat >::copy_color_hspan(), agg::renderer_base< PixelFormat >::copy_color_vspan(), agg::renderer_base< PixelFormat >::copy_hline(), and agg::renderer_base< PixelFormat >::copy_vline().
Member Data Documentation
m_clip_box
template<class PixelFormat > rect_i agg::renderer_base< PixelFormat >::m_clip_box private
Referenced by agg::renderer_base< PixelFormat >::attach(), agg::renderer_base< PixelFormat >::bounding_clip_box(), agg::renderer_base< PixelFormat >::bounding_xmax(), agg::renderer_base< PixelFormat >::bounding_xmin(), agg::renderer_base< PixelFormat >::bounding_ymax(), agg::renderer_base< PixelFormat >::bounding_ymin(), agg::renderer_base< PixelFormat >::clip_box(), agg::renderer_base< PixelFormat >::clip_box(), agg::renderer_base< PixelFormat >::clip_box_naked(), agg::renderer_base< PixelFormat >::inbox(), agg::renderer_base< PixelFormat >::reset_clipping(), agg::renderer_base< PixelFormat >::xmax(), agg::renderer_base< PixelFormat >::xmin(), agg::renderer_base< PixelFormat >::ymax(), and agg::renderer_base< PixelFormat >::ymin().
m_ren
template<class PixelFormat > pixfmt_type* agg::renderer_base< PixelFormat >::m_ren private
Referenced by agg::renderer_base< PixelFormat >::attach(), agg::renderer_base< PixelFormat >::blend_bar(), agg::renderer_base< PixelFormat >::blend_color_hspan(), agg::renderer_base< PixelFormat >::blend_color_vspan(), agg::renderer_base< PixelFormat >::blend_from(), agg::renderer_base< PixelFormat >::blend_from_color(), agg::renderer_base< PixelFormat >::blend_from_lut(), agg::renderer_base< PixelFormat >::blend_hline(), agg::renderer_base< PixelFormat >::blend_pixel(), agg::renderer_base< PixelFormat >::blend_solid_hspan(), agg::renderer_base< PixelFormat >::blend_solid_vspan(), agg::renderer_base< PixelFormat >::blend_vline(), agg::renderer_base< PixelFormat >::clear(), agg::renderer_base< PixelFormat >::copy_bar(), agg::renderer_base< PixelFormat >::copy_color_hspan(), agg::renderer_base< PixelFormat >::copy_color_vspan(), agg::renderer_base< PixelFormat >::copy_from(), agg::renderer_base< PixelFormat >::copy_hline(), agg::renderer_base< PixelFormat >::copy_pixel(), agg::renderer_base< PixelFormat >::copy_vline(), agg::renderer_base< PixelFormat >::fill(), agg::renderer_base< PixelFormat >::height(), agg::renderer_base< PixelFormat >::pixel(), agg::renderer_base< PixelFormat >::ren(), agg::renderer_base< PixelFormat >::ren(), and agg::renderer_base< PixelFormat >::width().
The documentation for this class was generated from the following file:
src/agg/agg_renderer_base.h