Prusa Slicer: Slic3r::GUI::Config::Version Struct Reference
Slic3r::GUI::Config::Version Struct Reference
#include <src/slic3r/Config/Version.hpp>
Public Member Functions
bool is_slic3r_supported (const Semver &slicer_version) const
bool is_current_slic3r_supported () const
bool is_current_slic3r_downgrade () const
Public Attributes
Semver config_version = Semver::invalid()
Semver min_slic3r_version = Semver::zero()
Semver max_slic3r_version = Semver::inf()
std::string comment
Detailed Description
Member Function Documentation
is_current_slic3r_downgrade()
bool Slic3r::GUI::Config::Version::is_current_slic3r_downgrade () const
{
  return Slic3r::SEMVER < min_slic3r_version;
}
References min_slic3r_version, and Slic3r::SEMVER.
is_current_slic3r_supported()
bool Slic3r::GUI::Config::Version::is_current_slic3r_supported () const
{
  return this->is_slic3r_supported(Slic3r::SEMVER);
}
References is_slic3r_supported(), and Slic3r::SEMVER.
is_slic3r_supported()
bool Slic3r::GUI::Config::Version::is_slic3r_supported (const Semver & slicer_version) const
{
  if (! slic3r_version.in_range(min_slic3r_version, max_slic3r_version))
    return false;
  // Now verify, whether the configuration pre-release status is compatible with the Slic3r's pre-release status.
  // Alpha Slic3r will happily load any configuration, while beta Slic3r will ignore alpha configurations etc.
  const char *prerelease_slic3r = slic3r_version.prerelease();
  const char *prerelease_config = this->config_version.prerelease();
  if (prerelease_config == nullptr)
    // Released config is always supported.
    return true;
  else if (prerelease_slic3r == nullptr)
    // Released slic3r only supports released configs.
    return false;
  // Compare the pre-release status of Slic3r against the config.
  // If the prerelease status of slic3r is lexicographically lower or equal
  // to the prerelease status of the config, accept it.
  return compare_prerelease(prerelease_slic3r, prerelease_config) != 1;
}
References Slic3r::GUI::Config::compare_prerelease(), config_version, Slic3r::Semver::in_range(), max_slic3r_version, min_slic3r_version, and Slic3r::Semver::prerelease().
Referenced by is_current_slic3r_supported().
Member Data Documentation
comment
std::string Slic3r::GUI::Config::Version::comment
Referenced by Slic3r::GUI::Config::Index::load().
config_version
Semver Slic3r::GUI::Config::Version::config_version = Semver::invalid()
Referenced by Slic3r::GUI::Config::Index::find(), is_slic3r_supported(), Slic3r::GUI::Config::Index::load(), Slic3r::GUI::Config::Snapshot::load_ini(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
max_slic3r_version
Semver Slic3r::GUI::Config::Version::max_slic3r_version = Semver::inf()
Referenced by is_slic3r_supported(), Slic3r::GUI::Config::Index::load(), Slic3r::GUI::Config::Snapshot::load_ini(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
min_slic3r_version
Semver Slic3r::GUI::Config::Version::min_slic3r_version = Semver::zero()
Referenced by is_current_slic3r_downgrade(), is_slic3r_supported(), Slic3r::GUI::Config::Index::load(), Slic3r::GUI::Config::Snapshot::load_ini(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
The documentation for this struct was generated from the following files:
src/slic3r/Config/Version.hpp
src/slic3r/Config/Version.cpp