Prusa Slicer: Slic3r::FFFSupport::SupportGeneratorLayerExtruded Struct Reference
Slic3r::FFFSupport::SupportGeneratorLayerExtruded Struct Reference
Public Member Functions
SupportGeneratorLayerExtruded & operator= (SupportGeneratorLayerExtruded &&rhs)
bool empty () const
void set_polygons_to_extrude (Polygons &&polygons)
Polygons & polygons_to_extrude ()
const Polygons & polygons_to_extrude () const
bool could_merge (const SupportGeneratorLayerExtruded &other) const
void merge (SupportGeneratorLayerExtruded &&other)
void polygons_append (Polygons &dst) const
Public Attributes
SupportGeneratorLayer * layer { nullptr }
ExtrusionEntitiesPtr extrusions
Private Attributes
std::unique_ptr< Polygons > m_polygons_to_extrude
Detailed Description
Member Function Documentation
could_merge()
bool Slic3r::FFFSupport::SupportGeneratorLayerExtruded::could_merge (const SupportGeneratorLayerExtruded & other) const inline
{
        return ! this->empty() && ! other.empty() &&
            std::abs(this->layer->height - other.layer->height) < EPSILON &&
            this->layer->bridging == other.layer->bridging;
    }
References Slic3r::FFFSupport::SupportGeneratorLayer::bridging, empty(), Slic3r::empty(), EPSILON, Slic3r::FFFSupport::SupportGeneratorLayer::height, and layer.
empty()
bool Slic3r::FFFSupport::SupportGeneratorLayerExtruded::empty () const inline
                       {
        return layer == nullptr || layer->polygons.empty();
    }
Referenced by could_merge(), and Slic3r::FFFSupport::LoopInterfaceProcessor::generate().
merge()
void Slic3r::FFFSupport::SupportGeneratorLayerExtruded::merge (SupportGeneratorLayerExtruded && other) inline
{
        assert(this->could_merge(other));
        // 1) Merge the rest polygons to extrude, if there are any.
        if (other.m_polygons_to_extrude != nullptr) {
            if (m_polygons_to_extrude == nullptr) {
                // This layer has no extrusions generated yet, if it has no m_polygons_to_extrude (its area to extrude was not reduced yet).
                assert(this->extrusions.empty());
                m_polygons_to_extrude = std::make_unique<Polygons>(this->layer->polygons);
            }
            Slic3r::polygons_append(*m_polygons_to_extrude, std::move(*other.m_polygons_to_extrude));
            *m_polygons_to_extrude = union_safety_offset(*m_polygons_to_extrude);
            other.m_polygons_to_extrude.reset();
        } else if (m_polygons_to_extrude != nullptr) {
            assert(other.m_polygons_to_extrude == nullptr);
            // The other layer has no extrusions generated yet, if it has no m_polygons_to_extrude (its area to extrude was not reduced yet).
            assert(other.extrusions.empty());
            Slic3r::polygons_append(*m_polygons_to_extrude, other.layer->polygons);
            *m_polygons_to_extrude = union_safety_offset(*m_polygons_to_extrude);
        }
        // 2) Merge the extrusions.
        this->extrusions.insert(this->extrusions.end(), other.extrusions.begin(), other.extrusions.end());
        other.extrusions.clear();
        // 3) Merge the infill polygons.
        Slic3r::polygons_append(this->layer->polygons, std::move(other.layer->polygons));
        this->layer->polygons = union_safety_offset(this->layer->polygons);
        other.layer->polygons.clear();
    }
References Slic3r::polygons_append(), and Slic3r::union_safety_offset().
operator=()
SupportGeneratorLayerExtruded & Slic3r::FFFSupport::SupportGeneratorLayerExtruded::operator= (SupportGeneratorLayerExtruded && rhs) inline
{
        this->layer = rhs.layer;
        this->extrusions = std::move(rhs.extrusions);
        m_polygons_to_extrude = std::move(rhs.m_polygons_to_extrude);
        rhs.layer = nullptr;
        return *this;
    }
References layer.
polygons_append()
void Slic3r::FFFSupport::SupportGeneratorLayerExtruded::polygons_append (Polygons & dst) const inline
{
        if (layer != NULL && ! layer->polygons.empty())
            Slic3r::polygons_append(dst, layer->polygons);
    }
References Slic3r::polygons_append().
polygons_to_extrude() [1/2]
Polygons & Slic3r::FFFSupport::SupportGeneratorLayerExtruded::polygons_to_extrude () inline
{ return (m_polygons_to_extrude == nullptr) ? layer->polygons : *m_polygons_to_extrude; }
polygons_to_extrude() [2/2]
const Polygons & Slic3r::FFFSupport::SupportGeneratorLayerExtruded::polygons_to_extrude () const inline
{ return (m_polygons_to_extrude == nullptr) ? layer->polygons : *m_polygons_to_extrude; }
set_polygons_to_extrude()
void Slic3r::FFFSupport::SupportGeneratorLayerExtruded::set_polygons_to_extrude (Polygons && polygons) inline
{
        if (m_polygons_to_extrude == nullptr)
            m_polygons_to_extrude = std::make_unique<Polygons>(std::move(polygons));
        else
            *m_polygons_to_extrude = std::move(polygons);
    }
Referenced by Slic3r::FFFSupport::LoopInterfaceProcessor::generate().
Member Data Documentation
extrusions
ExtrusionEntitiesPtr Slic3r::FFFSupport::SupportGeneratorLayerExtruded::extrusions
Referenced by Slic3r::FFFSupport::LoopInterfaceProcessor::generate().
layer
SupportGeneratorLayer* Slic3r::FFFSupport::SupportGeneratorLayerExtruded::layer { nullptr }
Referenced by could_merge(), Slic3r::FFFSupport::LoopInterfaceProcessor::generate(), and operator=().
m_polygons_to_extrude
std::unique_ptr<Polygons> Slic3r::FFFSupport::SupportGeneratorLayerExtruded::m_polygons_to_extrude private
The documentation for this struct was generated from the following file:
src/libslic3r/Support/SupportCommon.cpp