Prusa Slicer: Slic3r::GUI::PageBuildVolume Struct Reference
Slic3r::GUI::PageBuildVolume Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
PageBuildVolume (ConfigWizard *parent)
virtual void apply_custom_config (DynamicPrintConfig &config)
template<class T >
T * append (T *thing, int proportion=0, int flag=wxEXPAND|wxTOP|wxBOTTOM, int border=10)
wxStaticText * append_text (wxString text)
void append_spacer (int space)
ConfigWizard::priv * wizard_p () const
virtual void set_run_reason (ConfigWizard::RunReason run_reason)
virtual void on_activate ()
Public Attributes
wxTextCtrl * build_volume
ConfigWizard * parent
const wxString shortname
wxBoxSizer * content
const unsigned indent
Detailed Description
Constructor & Destructor Documentation
PageBuildVolume()
Slic3r::GUI::PageBuildVolume::PageBuildVolume (ConfigWizard * parent)
    : ConfigWizardPage(parent, _L("Build Volume"), _L("Build Volume"), 1)
    , build_volume(new DiamTextCtrl(this))
{
    append_text(_L("Set the printer height."));
    wxString value = "200";
    build_volume->SetValue(value);
    build_volume->Bind(wxEVT_KILL_FOCUS, [this](wxFocusEvent& e) {
        double def_value = 200.0;
        double max_value = 1200.0;
        e.Skip();
        wxString str = build_volume->GetValue();
        const char dec_sep = is_decimal_separator_point() ? '.' : ',';
        const char dec_sep_alt = dec_sep == '.' ? ',' : '.';
        // Replace the first incorrect separator in decimal number.
        bool was_replaced = str.Replace(dec_sep_alt, dec_sep, false) != 0;
        double val = 0.0;
        if (!str.ToDouble(&val)) {
            val = def_value;
            build_volume->SetValue(double_to_string(val));
            show_error(nullptr, _L("Invalid numeric input."));
            //build_volume->SetFocus();
        } else if (val < 0.0) {
            val  = def_value;
            build_volume->SetValue(double_to_string(val));
            show_error(nullptr, _L("Invalid numeric input."));
            //build_volume->SetFocus();
        } else if (val > max_value) {
            val = max_value;
            build_volume->SetValue(double_to_string(val));
            show_error(nullptr, _L("Invalid numeric input."));
            //build_volume->SetFocus();
        } else if (was_replaced)
            build_volume->SetValue(double_to_string(val));
    }, build_volume->GetId());
    auto* sizer_volume = new wxFlexGridSizer(3, 5, 5);
    auto* text_volume = new wxStaticText(this, wxID_ANY, _L("Max print height") + ":");
    auto* unit_volume = new wxStaticText(this, wxID_ANY, _L("mm"));
    sizer_volume->AddGrowableCol(0, 1);
    sizer_volume->Add(text_volume, 0, wxALIGN_CENTRE_VERTICAL);
    sizer_volume->Add(build_volume);
    sizer_volume->Add(unit_volume, 0, wxALIGN_CENTRE_VERTICAL);
    append(sizer_volume);
}
References _L, Slic3r::GUI::ConfigWizardPage::append(), Slic3r::GUI::ConfigWizardPage::append_text(), build_volume, Slic3r::GUI::double_to_string(), Slic3r::is_decimal_separator_point(), and Slic3r::GUI::show_error().
Member Function Documentation
append()
template<class T > T * Slic3r::GUI::ConfigWizardPage::append (T * thing, int proportion = 0, int flag = wxEXPAND|wxTOP|wxBOTTOM, int border = 10) inline inherited
    {
        content->Add(thing, proportion, flag, border);
        return thing;
    }
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), PageBuildVolume(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), Slic3r::GUI::PageVendors::PageVendors(), and Slic3r::GUI::ConfigWizardPage::append_text().
append_spacer()
void Slic3r::GUI::ConfigWizardPage::append_spacer (int space) inherited
{
    // FIXME: scaling
    content->AddSpacer(space);
}
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageTemperatures::PageTemperatures(), and Slic3r::GUI::PageUpdate::PageUpdate().
append_text()
wxStaticText * Slic3r::GUI::ConfigWizardPage::append_text (wxString text) inherited
{
    auto *widget = new wxStaticText(this, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    widget->Wrap(WRAP_WIDTH);
    widget->SetMinSize(wxSize(WRAP_WIDTH, -1));
    append(widget);
    return widget;
}
References Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::WRAP_WIDTH.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), PageBuildVolume(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), and Slic3r::GUI::PageVendors::PageVendors().
apply_custom_config()
void Slic3r::GUI::PageBuildVolume::apply_custom_config (DynamicPrintConfig & config) virtual
Reimplemented from Slic3r::GUI::ConfigWizardPage.
{
    double val = 0.0;
    build_volume->GetValue().ToDouble(&val);
    auto* opt_volume = new ConfigOptionFloat(val);
    config.set_key_value("max_print_height", opt_volume);
}
References build_volume, and Slic3r::DynamicConfig::set_key_value().
on_activate()
virtual void Slic3r::GUI::ConfigWizardPage::on_activate () inline virtual inherited
Reimplemented in Slic3r::GUI::PageMaterials.
{}
Referenced by Slic3r::GUI::PageMode::PageMode().
set_run_reason()
virtual void Slic3r::GUI::ConfigWizardPage::set_run_reason (ConfigWizard::RunReason run_reason) inline virtual inherited
Reimplemented in Slic3r::GUI::PageWelcome, and Slic3r::GUI::PagePrinters.
{}
wizard_p()
ConfigWizard::priv * Slic3r::GUI::ConfigWizardPage::wizard_p () const inline inherited
{ return parent->p.get(); }
References Slic3r::GUI::ConfigWizard::p, and Slic3r::GUI::ConfigWizardPage::parent.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageVendors::PageVendors(), Slic3r::GUI::PageMaterials::on_activate(), Slic3r::GUI::PageMaterials::select_material(), and Slic3r::GUI::PageMaterials::update_lists().
Member Data Documentation
build_volume
wxTextCtrl* Slic3r::GUI::PageBuildVolume::build_volume
Referenced by PageBuildVolume(), and apply_custom_config().
content
wxBoxSizer* Slic3r::GUI::ConfigWizardPage::content inherited
Referenced by Slic3r::GUI::ConfigWizardPage::ConfigWizardPage(), Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::ConfigWizardPage::append_spacer().
indent
const unsigned Slic3r::GUI::ConfigWizardPage::indent inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page().
parent
ConfigWizard* Slic3r::GUI::ConfigWizardPage::parent inherited
Referenced by Slic3r::GUI::PageMaterials::PageMaterials(), and Slic3r::GUI::ConfigWizardPage::wizard_p().
shortname
const wxString Slic3r::GUI::ConfigWizardPage::shortname inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page(), and Slic3r::GUI::ConfigWizard::priv::add_page().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp