Prusa Slicer: agg::saturation< Limit > Struct Template Reference
agg::saturation< Limit > Struct Template Reference
#include <src/agg/agg_basics.h>
Static Public Member Functions
static AGG_INLINE int iround (double v)
Detailed Description
template<int Limit>
struct agg::saturation< Limit >
Member Function Documentation
iround()
template<int Limit> static AGG_INLINE int agg::saturation< Limit >::iround (double v) inline static
        {
            if(v < double(-Limit)) return -Limit;
            if(v > double( Limit)) return  Limit;
            return agg::iround(v);
        }
References agg::iround().
Referenced by agg::ras_conv_int_sat::mul_div(), and agg::ras_conv_int_sat::upscale().
The documentation for this struct was generated from the following file:
src/agg/agg_basics.h