Prusa Slicer: agg::row_ptr_cache< T > Class Template Reference
agg::row_ptr_cache< T > Class Template Reference
#include <src/agg/agg_rendering_buffer.h>
Public Types
typedef const_row_info< T > row_data
Public Member Functions
row_ptr_cache ()
row_ptr_cache (T *buf, unsigned width, unsigned height, int stride)
void attach (T *buf, unsigned width, unsigned height, int stride)
AGG_INLINE T * buf ()
AGG_INLINE const T * buf () const
AGG_INLINE unsigned width () const
AGG_INLINE unsigned height () const
AGG_INLINE int stride () const
AGG_INLINE unsigned stride_abs () const
AGG_INLINE T * row_ptr (int, int y, unsigned)
AGG_INLINE T * row_ptr (int y)
AGG_INLINE const T * row_ptr (int y) const
AGG_INLINE row_data row (int y) const
T const *const * rows () const
template<class RenBuf >
void copy_from (const RenBuf &src)
void clear (T value)
Private Attributes
T * m_buf
pod_array< T * > m_rows
unsigned m_width
unsigned m_height
int m_stride
Detailed Description
template<class T>
class agg::row_ptr_cache< T >
Member Typedef Documentation
row_data
template<class T > typedef const_row_info<T> agg::row_ptr_cache< T >::row_data
Constructor & Destructor Documentation
row_ptr_cache() [1/2]
template<class T > agg::row_ptr_cache< T >::row_ptr_cache () inline
                        :
            m_buf(0),
            m_rows(),
            m_width(0),
            m_height(0),
            m_stride(0)
        {
        }
row_ptr_cache() [2/2]
template<class T > agg::row_ptr_cache< T >::row_ptr_cache (T * buf, unsigned width, unsigned height, int stride) inline
                                                                           :
            m_buf(0),
            m_rows(),
            m_width(0),
            m_height(0),
            m_stride(0)
        {
            attach(buf, width, height, stride);
        }
References agg::row_ptr_cache< T >::attach(), agg::row_ptr_cache< T >::buf(), agg::row_ptr_cache< T >::height(), agg::row_ptr_cache< T >::stride(), and agg::row_ptr_cache< T >::width().
Member Function Documentation
attach()
template<class T > void agg::row_ptr_cache< T >::attach (T * buf, unsigned width, unsigned height, int stride) inline
        {
            m_buf = buf;
            m_width = width;
            m_height = height;
            m_stride = stride;
            if(height > m_rows.size())
            {
                m_rows.resize(height);
            }
            T* row_ptr = m_buf;
            if(stride < 0)
            {
                row_ptr = m_buf - int(height - 1) * stride;
            }
            T** rows = &m_rows[0];
            while(height--)
            {
                *rows++ = row_ptr;
                row_ptr += stride;
            }
        }
References agg::row_ptr_cache< T >::buf(), agg::row_ptr_cache< T >::height(), agg::row_ptr_cache< T >::m_buf, agg::row_ptr_cache< T >::m_height, agg::row_ptr_cache< T >::m_rows, agg::row_ptr_cache< T >::m_stride, agg::row_ptr_cache< T >::m_width, agg::pod_array< T >::resize(), agg::row_ptr_cache< T >::row_ptr(), agg::row_ptr_cache< T >::rows(), agg::pod_array< T >::size(), agg::row_ptr_cache< T >::stride(), and agg::row_ptr_cache< T >::width().
Referenced by agg::row_ptr_cache< T >::row_ptr_cache().
buf() [1/2]
template<class T > AGG_INLINE T * agg::row_ptr_cache< T >::buf () inline
{ return m_buf;    }
References agg::row_ptr_cache< T >::m_buf.
Referenced by agg::row_ptr_cache< T >::row_ptr_cache(), and agg::row_ptr_cache< T >::attach().
buf() [2/2]
template<class T > AGG_INLINE const T * agg::row_ptr_cache< T >::buf () const inline
{ return m_buf;    }
References agg::row_ptr_cache< T >::m_buf.
clear()
template<class T > void agg::row_ptr_cache< T >::clear (T value) inline
        {
            unsigned y;
            unsigned w = width();
            unsigned stride = stride_abs();
            for(y = 0; y < height(); y++)
            {
                T* p = row_ptr(0, y, w);
                unsigned x;
                for(x = 0; x < stride; x++)
                {
                    *p++ = value;
                }
            }
        }
References agg::row_ptr_cache< T >::height(), agg::row_ptr_cache< T >::row_ptr(), agg::row_ptr_cache< T >::stride(), agg::row_ptr_cache< T >::stride_abs(), and agg::row_ptr_cache< T >::width().
copy_from()
template<class T > template<class RenBuf > void agg::row_ptr_cache< T >::copy_from (const RenBuf & src) inline
        {
            unsigned h = height();
            if(src.height() < h) h = src.height();
            unsigned l = stride_abs();
            if(src.stride_abs() < l) l = src.stride_abs();
            l *= sizeof(T);
            unsigned y;
            unsigned w = width();
            for (y = 0; y < h; y++)
            {
                memcpy(row_ptr(0, y, w), src.row_ptr(y), l);
            }
        }
References agg::row_ptr_cache< T >::height(), agg::row_ptr_cache< T >::row_ptr(), agg::row_ptr_cache< T >::stride_abs(), and agg::row_ptr_cache< T >::width().
height()
template<class T > AGG_INLINE unsigned agg::row_ptr_cache< T >::height () const inline
{ return m_height; }
References agg::row_ptr_cache< T >::m_height.
Referenced by agg::row_ptr_cache< T >::row_ptr_cache(), agg::row_ptr_cache< T >::attach(), agg::row_ptr_cache< T >::clear(), and agg::row_ptr_cache< T >::copy_from().
row()
template<class T > AGG_INLINE row_data agg::row_ptr_cache< T >::row (int y) const inline
        {
            return row_data(0, m_width-1, m_rows[y]);
        }
References agg::row_ptr_cache< T >::m_rows, and agg::row_ptr_cache< T >::m_width.
row_ptr() [1/3]
template<class T > AGG_INLINE T * agg::row_ptr_cache< T >::row_ptr (int y) inline
{ return m_rows[y]; }
References agg::row_ptr_cache< T >::m_rows.
row_ptr() [2/3]
template<class T > AGG_INLINE const T * agg::row_ptr_cache< T >::row_ptr (int y) const inline
{ return m_rows[y]; }
References agg::row_ptr_cache< T >::m_rows.
row_ptr() [3/3]
template<class T > AGG_INLINE T * agg::row_ptr_cache< T >::row_ptr (int , int y, unsigned) inline
        {
            return m_rows[y];
        }
References agg::row_ptr_cache< T >::m_rows.
Referenced by agg::row_ptr_cache< T >::attach(), agg::row_ptr_cache< T >::clear(), and agg::row_ptr_cache< T >::copy_from().
rows()
template<class T > T const *const * agg::row_ptr_cache< T >::rows () const inline
{ return &m_rows[0]; }
References agg::row_ptr_cache< T >::m_rows.
Referenced by agg::row_ptr_cache< T >::attach().
stride()
template<class T > AGG_INLINE int agg::row_ptr_cache< T >::stride () const inline
{ return m_stride; }
References agg::row_ptr_cache< T >::m_stride.
Referenced by agg::row_ptr_cache< T >::row_ptr_cache(), agg::row_ptr_cache< T >::attach(), and agg::row_ptr_cache< T >::clear().
stride_abs()
template<class T > AGG_INLINE unsigned agg::row_ptr_cache< T >::stride_abs () const inline
        {
            return (m_stride < 0) ? unsigned(-m_stride) : unsigned(m_stride);
        }
References agg::row_ptr_cache< T >::m_stride.
Referenced by agg::row_ptr_cache< T >::clear(), and agg::row_ptr_cache< T >::copy_from().
width()
template<class T > AGG_INLINE unsigned agg::row_ptr_cache< T >::width () const inline
{ return m_width;  }
References agg::row_ptr_cache< T >::m_width.
Referenced by agg::row_ptr_cache< T >::row_ptr_cache(), agg::row_ptr_cache< T >::attach(), agg::row_ptr_cache< T >::clear(), and agg::row_ptr_cache< T >::copy_from().
Member Data Documentation
m_buf
template<class T > T* agg::row_ptr_cache< T >::m_buf private
Referenced by agg::row_ptr_cache< T >::attach(), agg::row_ptr_cache< T >::buf(), and agg::row_ptr_cache< T >::buf().
m_height
template<class T > unsigned agg::row_ptr_cache< T >::m_height private
Referenced by agg::row_ptr_cache< T >::attach(), and agg::row_ptr_cache< T >::height().
m_rows
template<class T > pod_array<T*> agg::row_ptr_cache< T >::m_rows private
Referenced by agg::row_ptr_cache< T >::attach(), agg::row_ptr_cache< T >::row(), agg::row_ptr_cache< T >::row_ptr(), agg::row_ptr_cache< T >::row_ptr(), agg::row_ptr_cache< T >::row_ptr(), and agg::row_ptr_cache< T >::rows().
m_stride
template<class T > int agg::row_ptr_cache< T >::m_stride private
Referenced by agg::row_ptr_cache< T >::attach(), agg::row_ptr_cache< T >::stride(), and agg::row_ptr_cache< T >::stride_abs().
m_width
template<class T > unsigned agg::row_ptr_cache< T >::m_width private
Referenced by agg::row_ptr_cache< T >::attach(), agg::row_ptr_cache< T >::row(), and agg::row_ptr_cache< T >::width().
The documentation for this class was generated from the following file:
src/agg/agg_rendering_buffer.h