Prusa Slicer: Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > > Struct Template Reference
Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > > Struct Template Reference
#include <src/eigen/Eigen/src/Core/CoreEvaluators.h>
Public Types
enum { CoeffReadCost = evaluator<ArgType>::CoeffReadCost , Flags = (unsigned int)(evaluator<ArgType>::Flags & (HereditaryBits | DirectAccessBit) & ~RowMajorBit) | LinearAccessBit , Alignment = 0 }
typedef Diagonal< ArgType, DiagIndex > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
enum
typedef traits< Diagonal< ArgType, DiagIndex > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC evaluator (const XprType &diagonal)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
Protected Attributes
evaluator< ArgType > m_argImpl
const internal::variable_if_dynamicindex< Index, XprType::DiagIndex > m_index
Private Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowOffset () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colOffset () const
Detailed Description
template<typename ArgType, int DiagIndex>
struct Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >
Member Typedef Documentation
CoeffReturnType
template<typename ArgType , int DiagIndex> typedef XprType::CoeffReturnType Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::CoeffReturnType
ExpressionTraits
typedef traits<Diagonal< ArgType, DiagIndex > > Eigen::internal::evaluator_base< Diagonal< ArgType, DiagIndex > >::ExpressionTraits inherited
Scalar
template<typename ArgType , int DiagIndex> typedef XprType::Scalar Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::Scalar
XprType
template<typename ArgType , int DiagIndex> typedef Diagonal<ArgType, DiagIndex> Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::XprType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    Alignment = 0
  };
anonymous enum
template<typename ArgType , int DiagIndex> anonymous enum
Enumerator
CoeffReadCost
Flags
Alignment
       {
    CoeffReadCost = evaluator<ArgType>::CoeffReadCost,
    Flags = (unsigned int)(evaluator<ArgType>::Flags & (HereditaryBits | DirectAccessBit) & ~RowMajorBit) | LinearAccessBit,
    Alignment = 0
  };
Constructor & Destructor Documentation
evaluator()
template<typename ArgType , int DiagIndex> EIGEN_DEVICE_FUNC Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::evaluator (const XprType & diagonal) inline explicit
    : m_argImpl(diagonal.nestedExpression()),
      m_index(diagonal.index())
  { }
Member Function Documentation
coeff() [1/2]
template<typename ArgType , int DiagIndex> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::coeff (Index index) const inline
  {
    return m_argImpl.coeff(index + rowOffset(), index + colOffset());
  }
coeff() [2/2]
template<typename ArgType , int DiagIndex> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::coeff (Index row, Index) const inline
  {
    return m_argImpl.coeff(row + rowOffset(), row + colOffset());
  }
References row().
coeffRef() [1/2]
template<typename ArgType , int DiagIndex> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::coeffRef (Index index) inline
  {
    return m_argImpl.coeffRef(index + rowOffset(), index + colOffset());
  }
coeffRef() [2/2]
template<typename ArgType , int DiagIndex> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::coeffRef (Index row, Index) inline
  {
    return m_argImpl.coeffRef(row + rowOffset(), row + colOffset());
  }
References row().
colOffset()
template<typename ArgType , int DiagIndex> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::colOffset () const inline private
{ return m_index.value() > 0 ? m_index.value() : 0; }
References Eigen::internal::variable_if_dynamicindex< T, Value >::value().
rowOffset()
template<typename ArgType , int DiagIndex> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::rowOffset () const inline private
{ return m_index.value() > 0 ? 0 : -m_index.value(); }
References Eigen::internal::variable_if_dynamicindex< T, Value >::value().
Member Data Documentation
m_argImpl
template<typename ArgType , int DiagIndex> evaluator<ArgType> Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::m_argImpl protected
m_index
template<typename ArgType , int DiagIndex> const internal::variable_if_dynamicindex<Index, XprType::DiagIndex> Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::m_index protected
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/CoreEvaluators.h