Prusa Slicer: Slic3r::GUI::CancellableJob< JobSubclass > Class Template Reference
Slic3r::GUI::CancellableJob< JobSubclass > Class Template Reference
#include <src/slic3r/GUI/Jobs/CancellableJob.hpp>
Public Member Functions
template<class... Args>
CancellableJob (std::atomic_bool &flag, Args &&...args)
void process (Ctl &ctl) override
void finalize (bool canceled, std::exception_ptr &eptr) override
Private Attributes
JobSubclass m_job
std::atomic_bool & m_flag
Detailed Description
template<class JobSubclass>
class Slic3r::GUI::CancellableJob< JobSubclass >
Constructor & Destructor Documentation
CancellableJob()
template<class JobSubclass > template<class... Args> Slic3r::GUI::CancellableJob< JobSubclass >::CancellableJob (std::atomic_bool & flag, Args &&... args) inline
        : m_job{std::forward<Args>(args)...}, m_flag{flag}
    {}
Member Function Documentation
finalize()
template<class JobSubclass > void Slic3r::GUI::CancellableJob< JobSubclass >::finalize (bool canceled, std::exception_ptr & eptr) inline override virtual
Reimplemented from Slic3r::GUI::Job.
    {
        m_job.finalize(m_flag.load() || canceled, eptr);
    }
References Slic3r::GUI::CancellableJob< JobSubclass >::m_flag, and Slic3r::GUI::CancellableJob< JobSubclass >::m_job.
process()
template<class JobSubclass > void Slic3r::GUI::CancellableJob< JobSubclass >::process (Ctl & ctl) inline override virtual
Implements Slic3r::GUI::Job.
    {
        m_flag.store(false);
        struct CancelCtl : public Ctl
        {
            Ctl              &basectl;
            std::atomic_bool &cflag;
            CancelCtl (Ctl &c, std::atomic_bool &f): basectl{c}, cflag{f} {}
            void update_status(int st, const std::string &msg = "") override
            {
                basectl.update_status(st, msg);
            }
            bool was_canceled() const override
            {
                return cflag.load() || basectl.was_canceled();
            }
            std::future<void> call_on_main_thread(
                std::function<void()> fn) override
            {
                return basectl.call_on_main_thread(fn);
            }
        } cctl(ctl, m_flag);
        m_job.process(cctl);
    }
References Slic3r::GUI::Job::Ctl::call_on_main_thread(), Slic3r::GUI::CancellableJob< JobSubclass >::m_flag, Slic3r::GUI::CancellableJob< JobSubclass >::m_job, Slic3r::GUI::Job::Ctl::update_status(), and Slic3r::GUI::Job::Ctl::was_canceled().
Member Data Documentation
m_flag
template<class JobSubclass > std::atomic_bool& Slic3r::GUI::CancellableJob< JobSubclass >::m_flag private
Referenced by Slic3r::GUI::CancellableJob< JobSubclass >::finalize(), and Slic3r::GUI::CancellableJob< JobSubclass >::process().
m_job
template<class JobSubclass > JobSubclass Slic3r::GUI::CancellableJob< JobSubclass >::m_job private
Referenced by Slic3r::GUI::CancellableJob< JobSubclass >::finalize(), and Slic3r::GUI::CancellableJob< JobSubclass >::process().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Jobs/CancellableJob.hpp