Prusa Slicer: Eigen::internal::kernel_retval< FullPivLU< _MatrixType > > Struct Template Reference
Eigen::internal::kernel_retval< FullPivLU< _MatrixType > > Struct Template Reference
#include <src/eigen/Eigen/src/LU/FullPivLU.h>
Public Types
enum { MaxSmallDimAtCompileTime }
typedef FullPivLU< _MatrixType > DecompositionType
typedef ReturnByValue< kernel_retval_base > Base
typedef internal::traits< Derived >::ReturnType ReturnType
Public Member Functions
template<typename Dest >
void evalTo (Dest &dst) const
Index rows () const
Index cols () const
Index rank () const
const DecompositionType & dec () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
const DecompositionType & m_dec
Index m_rank
Index m_cols
Detailed Description
template<typename _MatrixType>
struct Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >
Member Typedef Documentation
Base
typedef ReturnByValue<kernel_retval_base> Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >::Base inherited
DecompositionType
typedef FullPivLU< _MatrixType > Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >::DecompositionType inherited
ReturnType
template<typename Derived > typedef internal::traits<Derived>::ReturnType Eigen::ReturnByValue< Derived >::ReturnType inherited
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
MaxSmallDimAtCompileTime
       { MaxSmallDimAtCompileTime = EIGEN_SIZE_MIN_PREFER_FIXED(
            MatrixType::MaxColsAtCompileTime,
            MatrixType::MaxRowsAtCompileTime)
  };
Member Function Documentation
coeff() [1/2]
template<typename Derived > const Unusable & Eigen::ReturnByValue< Derived >::coeff (Index) const inline inherited
{ return *reinterpret_cast<const Unusable*>(this); }
coeff() [2/2]
template<typename Derived > const Unusable & Eigen::ReturnByValue< Derived >::coeff (Index , Index) const inline inherited
{ return *reinterpret_cast<const Unusable*>(this); }
coeffRef() [1/2]
template<typename Derived > Unusable & Eigen::ReturnByValue< Derived >::coeffRef (Index) inline inherited
{ return *reinterpret_cast<Unusable*>(this); }
coeffRef() [2/2]
template<typename Derived > Unusable & Eigen::ReturnByValue< Derived >::coeffRef (Index , Index) inline inherited
{ return *reinterpret_cast<Unusable*>(this); }
cols()
Index Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >::cols () const inline inherited
{ return m_cols; }
dec()
const DecompositionType & Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >::dec () const inline inherited
{ return m_dec; }
evalTo()
template<typename _MatrixType > template<typename Dest > void Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo (Dest & dst) const inline
  {
    using std::abs;
    const Index cols = dec().matrixLU().cols(), dimker = cols - rank();
    if(dimker == 0)
    {
      // The Kernel is just {0}, so it doesn't have a basis properly speaking, but let's
      // avoid crashing/asserting as that depends on floating point calculations. Let's
      // just return a single column vector filled with zeros.
      dst.setZero();
      return;
    }
    /* Let us use the following lemma:
      *
      * Lemma: If the matrix A has the LU decomposition PAQ = LU,
      * then Ker A = Q(Ker U).
      *
      * Proof: trivial: just keep in mind that P, Q, L are invertible.
      */
    /* Thus, all we need to do is to compute Ker U, and then apply Q.
      *
      * U is upper triangular, with eigenvalues sorted so that any zeros appear at the end.
      * Thus, the diagonal of U ends with exactly
      * dimKer zero's. Let us use that to construct dimKer linearly
      * independent vectors in Ker U.
      */
    Matrix<Index, Dynamic, 1, 0, MaxSmallDimAtCompileTime, 1> pivots(rank());
    RealScalar premultiplied_threshold = dec().maxPivot() * dec().threshold();
    Index p = 0;
    for(Index i = 0; i < dec().nonzeroPivots(); ++i)
      if(abs(dec().matrixLU().coeff(i,i)) > premultiplied_threshold)
        pivots.coeffRef(p++) = i;
    eigen_internal_assert(p == rank());
    // we construct a temporaty trapezoid matrix m, by taking the U matrix and
    // permuting the rows and cols to bring the nonnegligible pivots to the top of
    // the main diagonal. We need that to be able to apply our triangular solvers.
    // FIXME when we get triangularView-for-rectangular-matrices, this can be simplified
    Matrix<typename MatrixType::Scalar, Dynamic, Dynamic, MatrixType::Options,
           MaxSmallDimAtCompileTime, MatrixType::MaxColsAtCompileTime>
      m(dec().matrixLU().block(0, 0, rank(), cols));
    for(Index i = 0; i < rank(); ++i)
    {
      if(i) m.row(i).head(i).setZero();
      m.row(i).tail(cols-i) = dec().matrixLU().row(pivots.coeff(i)).tail(cols-i);
    }
    m.block(0, 0, rank(), rank());
    m.block(0, 0, rank(), rank()).template triangularView<StrictlyLower>().setZero();
    for(Index i = 0; i < rank(); ++i)
      m.col(i).swap(m.col(pivots.coeff(i)));
    // ok, we have our trapezoid matrix, we can apply the triangular solver.
    // notice that the math behind this suggests that we should apply this to the
    // negative of the RHS, but for performance we just put the negative sign elsewhere, see below.
    m.topLeftCorner(rank(), rank())
     .template triangularView<Upper>().solveInPlace(
        m.topRightCorner(rank(), dimker)
      );
    // now we must undo the column permutation that we had applied!
    for(Index i = rank()-1; i >= 0; --i)
      m.col(i).swap(m.col(pivots.coeff(i)));
    // see the negative sign in the next line, that's what we were talking about above.
    for(Index i = 0; i < rank(); ++i) dst.row(dec().permutationQ().indices().coeff(i)) = -m.row(i).tail(dimker);
    for(Index i = rank(); i < cols; ++i) dst.row(dec().permutationQ().indices().coeff(i)).setZero();
    for(Index k = 0; k < dimker; ++k) dst.coeffRef(dec().permutationQ().indices().coeff(rank()+k), k) = Scalar(1);
  }
References block(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::coeffRef(), Eigen::Dynamic, and eigen_internal_assert.
rank()
Index Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >::rank () const inline inherited
{ return m_rank; }
rows()
Index Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >::rows () const inline inherited
{ return m_dec.cols(); }
Member Data Documentation
m_cols
Index Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >::m_cols protected inherited
m_dec
const DecompositionType& Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >::m_dec protected inherited
m_rank
Index Eigen::internal::kernel_retval_base< FullPivLU< _MatrixType > >::m_rank protected inherited
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/LU/FullPivLU.h