Prusa Slicer: Slic3r::GUI::CoordAxes Class Reference
Slic3r::GUI::CoordAxes Class Reference
#include <src/slic3r/GUI/CoordAxes.hpp>
Public Member Functions
const Vec3d & get_origin () const
void set_origin (const Vec3d &origin)
void set_stem_radius (float radius)
void set_stem_length (float length)
void set_tip_radius (float radius)
void set_tip_length (float length)
float get_stem_radius () const
float get_stem_length () const
float get_tip_radius () const
float get_tip_length () const
float get_total_length () const
void render (const Transform3d &trafo, float emission_factor=0.0f)
Static Public Attributes
static const float DefaultStemRadius = 0.5f
static const float DefaultStemLength = 25.0f
static const float DefaultTipRadius = 2.5f * CoordAxes::DefaultStemRadius
static const float DefaultTipLength = 5.0f
Private Attributes
Vec3d m_origin { Vec3d::Zero() }
float m_stem_radius { DefaultStemRadius }
float m_stem_length { DefaultStemLength }
float m_tip_radius { DefaultTipRadius }
float m_tip_length { DefaultTipLength }
GLModel m_arrow
Detailed Description
Member Function Documentation
get_origin()
const Vec3d & Slic3r::GUI::CoordAxes::get_origin () const inline
{ return m_origin; }
References m_origin.
Referenced by Slic3r::GUI::Bed3D::calc_extended_bounding_box().
get_stem_length()
float Slic3r::GUI::CoordAxes::get_stem_length () const inline
{ return m_stem_length; }
References m_stem_length.
get_stem_radius()
float Slic3r::GUI::CoordAxes::get_stem_radius () const inline
{ return m_stem_radius; }
References m_stem_radius.
get_tip_length()
float Slic3r::GUI::CoordAxes::get_tip_length () const inline
{ return m_tip_length; }
References m_tip_length.
get_tip_radius()
float Slic3r::GUI::CoordAxes::get_tip_radius () const inline
{ return m_tip_radius; }
References m_tip_radius.
Referenced by Slic3r::GUI::Bed3D::calc_extended_bounding_box().
get_total_length()
float Slic3r::GUI::CoordAxes::get_total_length () const inline
{ return m_stem_length + m_tip_length; }
References m_stem_length, and m_tip_length.
Referenced by Slic3r::GUI::Bed3D::calc_extended_bounding_box().
render()
void Slic3r::GUI::CoordAxes::render (const Transform3d & trafo, float emission_factor = 0.0f)
{
    auto render_axis = [this](GLShaderProgram& shader, const Transform3d& transform) {
        const Camera& camera = wxGetApp().plater()->get_camera();
        const Transform3d& view_matrix = camera.get_view_matrix();
        const Transform3d matrix = view_matrix * transform;
        shader.set_uniform("view_model_matrix", matrix);
        shader.set_uniform("projection_matrix", camera.get_projection_matrix());
        shader.set_uniform("view_normal_matrix", (Matrix3d)(view_matrix.matrix().block(0, 0, 3, 3) * transform.matrix().block(0, 0, 3, 3).inverse().transpose()));
        m_arrow.render();
    };
    if (!m_arrow.is_initialized())
        m_arrow.init_from(stilized_arrow(16, m_tip_radius, m_tip_length, m_stem_radius, m_stem_length));
    GLShaderProgram* curr_shader = wxGetApp().get_current_shader();
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    if (curr_shader != nullptr)
        curr_shader->stop_using();
    shader->start_using();
    shader->set_uniform("emission_factor", emission_factor);
    // Scale the axes if the camera is close to them to avoid issues
    // such as https://github.com/prusa3d/PrusaSlicer/issues/9483
    const Camera& camera = wxGetApp().plater()->get_camera();
    Transform3d scale_tr = Transform3d::Identity();
    scale_tr.scale(std::min(1., camera.get_inv_zoom() * 10.));
    // x axis
    m_arrow.set_color(ColorRGBA::X());
    render_axis(*shader, trafo * Geometry::translation_transform(m_origin) * Geometry::rotation_transform({ 0.0, 0.5 * M_PI, 0.0 }) * scale_tr);
    // y axis
    m_arrow.set_color(ColorRGBA::Y());
    render_axis(*shader, trafo * Geometry::translation_transform(m_origin) * Geometry::rotation_transform({ -0.5 * M_PI, 0.0, 0.0 }) * scale_tr);
    // z axis
    m_arrow.set_color(ColorRGBA::Z());
    render_axis(*shader, trafo * Geometry::translation_transform(m_origin) * scale_tr);
    shader->stop_using();
    if (curr_shader != nullptr)
        curr_shader->start_using();
}
References Slic3r::GUI::Camera::get_inv_zoom(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), m_arrow, m_origin, M_PI, m_stem_length, m_stem_radius, m_tip_length, m_tip_radius, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::GLModel::render(), Slic3r::Geometry::rotation_transform(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::scale(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GUI::stilized_arrow(), Slic3r::GLShaderProgram::stop_using(), Slic3r::transform(), Slic3r::Geometry::translation_transform(), Slic3r::ColorRGBA::X(), Slic3r::ColorRGBA::Y(), and Slic3r::ColorRGBA::Z().
Referenced by Slic3r::GUI::Bed3D::render_axes(), and Slic3r::GUI::Selection::render_sidebar_hints().
set_origin()
void Slic3r::GUI::CoordAxes::set_origin (const Vec3d & origin) inline
{ m_origin = origin; }
References m_origin.
Referenced by Slic3r::GUI::Bed3D::set_shape().
set_stem_length()
void Slic3r::GUI::CoordAxes::set_stem_length (float length) inline
{
        m_stem_length = length;
        m_arrow.reset();
    }
References Slic3r::length(), m_arrow, m_stem_length, and Slic3r::GUI::GLModel::reset().
Referenced by Slic3r::GUI::Selection::Selection(), and Slic3r::GUI::Bed3D::set_shape().
set_stem_radius()
void Slic3r::GUI::CoordAxes::set_stem_radius (float radius) inline
{
        m_stem_radius = radius;
        m_arrow.reset();
    }
References m_arrow, m_stem_radius, and Slic3r::GUI::GLModel::reset().
Referenced by Slic3r::GUI::Selection::Selection().
set_tip_length()
void Slic3r::GUI::CoordAxes::set_tip_length (float length) inline
{
        m_tip_length = length;
        m_arrow.reset();
    }
References Slic3r::length(), m_arrow, m_tip_length, and Slic3r::GUI::GLModel::reset().
Referenced by Slic3r::GUI::Selection::Selection().
set_tip_radius()
void Slic3r::GUI::CoordAxes::set_tip_radius (float radius) inline
{
        m_tip_radius = radius;
        m_arrow.reset();
    }
References m_arrow, m_tip_radius, and Slic3r::GUI::GLModel::reset().
Referenced by Slic3r::GUI::Selection::Selection().
Member Data Documentation
DefaultStemLength
const float Slic3r::GUI::CoordAxes::DefaultStemLength = 25.0f static
DefaultStemRadius
const float Slic3r::GUI::CoordAxes::DefaultStemRadius = 0.5f static
DefaultTipLength
const float Slic3r::GUI::CoordAxes::DefaultTipLength = 5.0f static
DefaultTipRadius
const float Slic3r::GUI::CoordAxes::DefaultTipRadius = 2.5f * CoordAxes::DefaultStemRadius static
m_arrow
GLModel Slic3r::GUI::CoordAxes::m_arrow private
Referenced by render(), set_stem_length(), set_stem_radius(), set_tip_length(), and set_tip_radius().
m_origin
Vec3d Slic3r::GUI::CoordAxes::m_origin { Vec3d::Zero() } private
Referenced by get_origin(), render(), and set_origin().
m_stem_length
float Slic3r::GUI::CoordAxes::m_stem_length { DefaultStemLength } private
Referenced by get_stem_length(), get_total_length(), render(), and set_stem_length().
m_stem_radius
float Slic3r::GUI::CoordAxes::m_stem_radius { DefaultStemRadius } private
Referenced by get_stem_radius(), render(), and set_stem_radius().
m_tip_length
float Slic3r::GUI::CoordAxes::m_tip_length { DefaultTipLength } private
Referenced by get_tip_length(), get_total_length(), render(), and set_tip_length().
m_tip_radius
float Slic3r::GUI::CoordAxes::m_tip_radius { DefaultTipRadius } private
Referenced by get_tip_radius(), render(), and set_tip_radius().
The documentation for this class was generated from the following files:
src/slic3r/GUI/CoordAxes.hpp
src/slic3r/GUI/CoordAxes.cpp