Prusa Slicer: ImColor Struct Reference
ImColor Struct Reference
#include <src/imgui/imgui.h>
Public Member Functions
ImColor ()
ImColor (int r, int g, int b, int a=255)
ImColor (ImU32 rgba)
ImColor (float r, float g, float b, float a=1.0f)
ImColor (const ImVec4 &col)
operator ImU32 () const
operator ImVec4 () const
void SetHSV (float h, float s, float v, float a=1.0f)
Static Public Member Functions
static ImColor HSV (float h, float s, float v, float a=1.0f)
Public Attributes
ImVec4 Value
Detailed Description
Constructor & Destructor Documentation
ImColor() [1/5]
ImColor::ImColor () inline
{ Value.x = Value.y = Value.z = Value.w = 0.0f; }
ImColor() [2/5]
ImColor::ImColor (int r, int g, int b, int a = 255) inline
{ float sc = 1.0f / 255.0f; Value.x = (float)r * sc; Value.y = (float)g * sc; Value.z = (float)b * sc; Value.w = (float)a * sc; }
ImColor() [3/5]
ImColor::ImColor (ImU32 rgba) inline
{ float sc = 1.0f / 255.0f; Value.x = (float)((rgba >> IM_COL32_R_SHIFT) & 0xFF) * sc; Value.y = (float)((rgba >> IM_COL32_G_SHIFT) & 0xFF) * sc; Value.z = (float)((rgba >> IM_COL32_B_SHIFT) & 0xFF) * sc; Value.w = (float)((rgba >> IM_COL32_A_SHIFT) & 0xFF) * sc; }
References IM_COL32_A_SHIFT, IM_COL32_B_SHIFT, IM_COL32_G_SHIFT, and IM_COL32_R_SHIFT.
ImColor() [4/5]
ImColor::ImColor (float r, float g, float b, float a = 1.0f) inline
{ Value.x = r; Value.y = g; Value.z = b; Value.w = a; }
ImColor() [5/5]
ImColor::ImColor (const ImVec4 & col) inline
{ Value = col; }
References col().
Member Function Documentation
HSV()
static ImColor ImColor::HSV (float h, float s, float v, float a = 1.0f) inline static
{ float r, g, b; ImGui::ColorConvertHSVtoRGB(h, s, v, r, g, b); return ImColor(r, g, b, a); }
References ImGui::ColorConvertHSVtoRGB().
Referenced by ShowDemoWindowLayout(), and ShowDemoWindowWidgets().
operator ImU32()
ImColor::operator ImU32 () const inline
{ return ImGui::ColorConvertFloat4ToU32(Value); }
References ImGui::ColorConvertFloat4ToU32().
operator ImVec4()
ImColor::operator ImVec4 () const inline
{ return Value; }
SetHSV()
void ImColor::SetHSV (float h, float s, float v, float a = 1.0f) inline
{ ImGui::ColorConvertHSVtoRGB(h, s, v, Value.x, Value.y, Value.z); Value.w = a; }
References ImGui::ColorConvertHSVtoRGB().
Member Data Documentation
Value
ImVec4 ImColor::Value
The documentation for this struct was generated from the following file:
src/imgui/imgui.h