Prusa Slicer: Slic3r::ConfigOptionEnumGeneric Class Reference
Slic3r::ConfigOptionEnumGeneric Class Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionEnumGeneric (const t_config_enum_values *keys_map=nullptr)
ConfigOptionEnumGeneric (const t_config_enum_values *keys_map, int value)
ConfigOptionType type () const override
ConfigOption * clone () const override
ConfigOptionEnumGeneric & operator= (const ConfigOption *opt)
bool operator== (const ConfigOptionEnumGeneric &rhs) const throw ()
bool operator< (const ConfigOptionEnumGeneric &rhs) const throw ()
bool operator== (const ConfigOption &rhs) const override
void set (const ConfigOption *rhs) override
std::string serialize () const override
bool deserialize (const std::string &str, bool append=false) override
int getInt () const override
void setInt (int val) override
bool operator== (const ConfigOptionInt &rhs) const throw ()
bool operator== (const int &rhs) const throw ()
operator int () const
bool operator!= (const int &rhs) const throw ()
bool operator!= (const ConfigOption &rhs) const
bool operator< (const int &rhs) const throw ()
size_t hash () const override throw ()
virtual double getFloat () const
virtual bool getBool () const
bool is_scalar () const
bool is_vector () const
virtual bool nullable () const
virtual bool is_nil () const
virtual bool overriden_by (const ConfigOption *rhs) const
virtual bool apply_override (const ConfigOption *rhs)
Static Public Member Functions
static ConfigOptionType static_type ()
Public Attributes
const t_config_enum_values * keys_map
int value
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
Constructor & Destructor Documentation
ConfigOptionEnumGeneric() [1/2]
Slic3r::ConfigOptionEnumGeneric::ConfigOptionEnumGeneric (const t_config_enum_values * keys_map = nullptr) inline
: keys_map(keys_map) {}
ConfigOptionEnumGeneric() [2/2]
Slic3r::ConfigOptionEnumGeneric::ConfigOptionEnumGeneric (const t_config_enum_values * keys_map, int value) inline explicit
: ConfigOptionInt(value), keys_map(keys_map) {}
Member Function Documentation
apply_override()
virtual bool Slic3r::ConfigOption::apply_override (const ConfigOption * rhs) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      if (*this == *rhs)
        return false;
      *this = *rhs;
      return true;
    }
Referenced by Slic3r::print_config_diffs().
clone()
ConfigOption * Slic3r::ConfigOptionEnumGeneric::clone () const inline override virtual
Implements Slic3r::ConfigOption.
{ return new ConfigOptionEnumGeneric(*this); }
deserialize()
bool Slic3r::ConfigOptionEnumGeneric::deserialize (const std::string & str, bool append = false) inline override virtual
Implements Slic3r::ConfigOption.
    {
        UNUSED(append);
        auto it = this->keys_map->find(str);
        if (it == this->keys_map->end())
            return false;
        this->value = it->second;
        return true;
    }
References Slic3r::append(), and UNUSED.
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
int Slic3r::ConfigOptionInt::getInt () const inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{ return this->value; }
References Slic3r::ConfigOptionSingle< int >::value.
hash()
size_t Slic3r::ConfigOptionSingle< int >::hash () const throw () inline override virtual inherited
Implements Slic3r::ConfigOption.
{ return std::hash<T>{}(this->value); }
is_nil()
virtual bool Slic3r::ConfigOption::is_nil () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVectorBase, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::GCode::append_full_config(), Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_full_label(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::print_config_diffs(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::validate(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nullable()
virtual bool Slic3r::ConfigOption::nullable () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::ConfigBase::null_nullables(), Slic3r::ConfigOption::overriden_by(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::validate().
operator int()
Slic3r::ConfigOptionSingle< int >::operator int () const inline inherited
{ return this->value; }
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
bool Slic3r::ConfigOptionSingle< int >::operator!= (const int & rhs) const throw () inline inherited
{ return this->value != rhs; }
operator<() [1/2]
bool Slic3r::ConfigOptionEnumGeneric::operator< (const ConfigOptionEnumGeneric & rhs) const throw () inline
{ return this->value <  rhs.value; }
operator<() [2/2]
bool Slic3r::ConfigOptionSingle< int >::operator< (const int & rhs) const throw () inline inherited
{ return this->value < rhs; }
operator=()
ConfigOptionEnumGeneric & Slic3r::ConfigOptionEnumGeneric::operator= (const ConfigOption * opt) inline
{ this->set(opt); return *this; }
References set().
operator==() [1/4]
bool Slic3r::ConfigOptionEnumGeneric::operator== (const ConfigOption & rhs) const inline override virtual
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionEnumGeneric: Comparing incompatible types");
        // rhs could be of the following type: ConfigOptionEnumGeneric or ConfigOptionEnum<T>
        return this->value == rhs.getInt();
    }
References Slic3r::ConfigOption::getInt(), and Slic3r::ConfigOption::type().
operator==() [2/4]
bool Slic3r::ConfigOptionEnumGeneric::operator== (const ConfigOptionEnumGeneric & rhs) const throw () inline
{ return this->value == rhs.value; }
operator==() [3/4]
bool Slic3r::ConfigOptionInt::operator== (const ConfigOptionInt & rhs) const throw () inline inherited
{ return this->value == rhs.value; }
operator==() [4/4]
bool Slic3r::ConfigOptionSingle< int >::operator== (const int & rhs) const throw () inline inherited
{ return this->value == rhs; }
overriden_by()
virtual bool Slic3r::ConfigOption::overriden_by (const ConfigOption * rhs) const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      assert(! this->nullable() && ! rhs->nullable());
      return *this != *rhs;
    }
References Slic3r::ConfigOption::nullable().
Referenced by Slic3r::print_config_diffs().
serialize() [1/2]
std::string Slic3r::ConfigOptionEnumGeneric::serialize () const inline override virtual
Implements Slic3r::ConfigOption.
    {
        for (const auto &kvp : *this->keys_map)
            if (kvp.second == this->value)
                return kvp.first;
        return std::string();
    }
References keys_map.
serialize() [2/2]
template<class Archive > void Slic3r::ConfigOptionEnumGeneric::serialize (Archive & ar) inline private
{ ar(cereal::base_class<ConfigOptionInt>(this)); }
set()
void Slic3r::ConfigOptionEnumGeneric::set (const ConfigOption * rhs) inline override virtual
Implements Slic3r::ConfigOption.
{
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionEnumGeneric: Assigning an incompatible type");
        // rhs could be of the following type: ConfigOptionEnumGeneric or ConfigOptionEnum<T>
        this->value = rhs->getInt();
    }
References Slic3r::ConfigOption::getInt(), and Slic3r::ConfigOption::type().
Referenced by operator=().
setInt()
void Slic3r::ConfigOptionInt::setInt (int val) inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{ this->value = val; }
Referenced by Slic3r::apply_to_print_region_config().
static_type()
static ConfigOptionType Slic3r::ConfigOptionEnumGeneric::static_type () inline static
{ return coEnum; }
References Slic3r::coEnum.
Referenced by type().
type()
ConfigOptionType Slic3r::ConfigOptionEnumGeneric::type () const inline override virtual
Implements Slic3r::ConfigOption.
{ return static_type(); }
References static_type().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
keys_map
const t_config_enum_values* Slic3r::ConfigOptionEnumGeneric::keys_map
Referenced by serialize().
value
int Slic3r::ConfigOptionSingle< int >::value inherited
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp