Prusa Slicer: Slic3r::GUI::Mouse3DController::State Class Reference
Slic3r::GUI::Mouse3DController::State Class Reference
Classes
struct QueueItem
Public Member Functions
void append_translation (const Vec3d &translation, size_t input_queue_max_size)
void append_rotation (const Vec3f &rotation, size_t input_queue_max_size)
void append_button (unsigned int id, size_t input_queue_max_size)
bool apply (const Params &params, Camera &camera)
Private Attributes
std::deque< QueueItem > m_input_queue
std::mutex m_input_queue_mutex
Detailed Description
Member Function Documentation
append_button()
void Slic3r::GUI::Mouse3DController::State::append_button (unsigned int id, size_t input_queue_max_size)
{
    std::scoped_lock<std::mutex> lock(m_input_queue_mutex);
    m_input_queue.emplace_back(QueueItem::buttons(id));
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    update_maximum(input_queue_max_size_achieved, m_input_queue.size());
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
}
Referenced by Slic3r::GUI::Mouse3DController::handle_packet_button().
append_rotation()
void Slic3r::GUI::Mouse3DController::State::append_rotation (const Vec3f & rotation, size_t input_queue_max_size)
{
    std::scoped_lock<std::mutex> lock(m_input_queue_mutex);
    while (m_input_queue.size() >= input_queue_max_size)
        m_input_queue.pop_front();
    m_input_queue.emplace_back(QueueItem::rotation(rotation.cast<double>()));
#ifdef WIN32
  if (rotation.x() != 0.0f)
        ++ m_mouse_wheel_counter;
#endif // WIN32
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    update_maximum(input_queue_max_size_achieved, m_input_queue.size());
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
}
Referenced by Slic3r::GUI::Mouse3DController::handle_packet_rotation().
append_translation()
void Slic3r::GUI::Mouse3DController::State::append_translation (const Vec3d & translation, size_t input_queue_max_size)
{
    std::scoped_lock<std::mutex> lock(m_input_queue_mutex);
    while (m_input_queue.size() >= input_queue_max_size)
        m_input_queue.pop_front();
    m_input_queue.emplace_back(QueueItem::translation(translation));
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    update_maximum(input_queue_max_size_achieved, m_input_queue.size());
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
}
References m_input_queue, m_input_queue_mutex, and Slic3r::GUI::Mouse3DController::State::QueueItem::translation().
Referenced by Slic3r::GUI::Mouse3DController::handle_packet_translation().
apply()
bool Slic3r::GUI::Mouse3DController::State::apply (const Params & params, Camera & camera)
{
    if (! wxGetApp().IsActive())
        return false;
    std::deque<QueueItem> input_queue;
    {
      // Atomically move m_input_queue to input_queue.
      std::scoped_lock<std::mutex> lock(m_input_queue_mutex);
      input_queue = std::move(m_input_queue);
        m_input_queue.clear();
    }
    for (const QueueItem &input_queue_item : input_queue) {
      if (input_queue_item.is_translation()) {
            Vec3d translation = params.swap_yz ? Vec3d(input_queue_item.vector.x(), - input_queue_item.vector.z(), input_queue_item.vector.y()) : input_queue_item.vector;
            double zoom_factor = camera.min_zoom() / camera.get_zoom();
          camera.set_target(camera.get_target() + zoom_factor * params.translation.scale * (translation.x() * camera.get_dir_right() + translation.z() * camera.get_dir_up()));
            if (translation.y() != 0.0)
                camera.update_zoom(params.zoom.scale * translation.y());
        } else if (input_queue_item.is_rotation()) {
            Vec3d rot = params.rotation.scale * input_queue_item.vector * (PI / 180.);
            if (params.swap_yz)
                rot = Vec3d(rot.x(), -rot.z(), rot.y());
            camera.rotate_local_around_target(Vec3d(rot.x(), - rot.z(), rot.y()));
      } else {
        assert(input_queue_item.is_buttons());
          switch (input_queue_item.type_or_buttons) {
          case 0: camera.update_zoom(1.0); break;
          case 1: camera.update_zoom(-1.0); break;
            default: break;
          }
      }
    }
    return ! input_queue.empty();
}
References Slic3r::GUI::Camera::get_dir_right(), Slic3r::GUI::Camera::get_dir_up(), Slic3r::GUI::Camera::get_target(), Slic3r::GUI::Camera::get_zoom(), Slic3r::GUI::Camera::min_zoom(), PI, Slic3r::GUI::Camera::rotate_local_around_target(), Slic3r::GUI::Mouse3DController::Params::rotation, Slic3r::GUI::Mouse3DController::Params::CustomParameters< Number >::scale, Slic3r::GUI::Camera::set_target(), Slic3r::GUI::Mouse3DController::Params::swap_yz, Slic3r::GUI::Mouse3DController::Params::translation, Slic3r::GUI::Camera::update_zoom(), and Slic3r::GUI::Mouse3DController::Params::zoom.
Referenced by Slic3r::GUI::Mouse3DController::apply().
Member Data Documentation
m_input_queue
std::deque<QueueItem> Slic3r::GUI::Mouse3DController::State::m_input_queue private
Referenced by append_translation().
m_input_queue_mutex
std::mutex Slic3r::GUI::Mouse3DController::State::m_input_queue_mutex mutable private
Referenced by append_translation().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Mouse3DController.hpp
src/slic3r/GUI/Mouse3DController.cpp