Prusa Slicer: Slic3r::sla::Bridge Struct Reference
Slic3r::sla::Bridge Struct Reference
#include <src/libslic3r/SLA/SupportTreeBuilder.hpp>
Public Member Functions
Bridge (const Vec3d &j1, const Vec3d &j2, double r_mm=0.8)
double get_length () const
Vec3d get_dir () const
Public Attributes
double r = 0.8
Vec3d startp = Vec3d::Zero()
Vec3d endp = Vec3d::Zero()
long id = ID_UNSET
Static Public Attributes
static const constexpr long ID_UNSET = -1
Detailed Description
Constructor & Destructor Documentation
Bridge()
Slic3r::sla::Bridge::Bridge (const Vec3d & j1, const Vec3d & j2, double r_mm = 0.8) inline
                                    : r{r_mm}, startp{j1}, endp{j2}
    {}
Member Function Documentation
get_dir()
Vec3d Slic3r::sla::Bridge::get_dir () const inline
{ return (endp - startp).normalized(); }
References endp, and startp.
Referenced by Slic3r::sla::get_mesh().
get_length()
double Slic3r::sla::Bridge::get_length () const inline
{ return (endp - startp).norm(); }
References endp, and startp.
Referenced by Slic3r::sla::get_mesh().
Member Data Documentation
endp
Vec3d Slic3r::sla::Bridge::endp = Vec3d::Zero()
Referenced by get_dir(), get_length(), and Slic3r::sla::get_mesh().
id
long Slic3r::sla::SupportTreeNode::id = ID_UNSET inherited
Referenced by Slic3r::sla::SupportTreeBuilder::add_pillar(), Slic3r::sla::DefaultSupportTree::add_pinheads(), Slic3r::sla::DefaultSupportTree::connect_to_model_body(), Slic3r::sla::create_ground_pillar(), Slic3r::sla::DefaultSupportTree::interconnect_pillars(), Slic3r::sla::Head::junction(), and Slic3r::sla::DefaultSupportTree::routing_to_ground().
ID_UNSET
const constexpr long Slic3r::sla::SupportTreeNode::ID_UNSET = -1 static constexpr inherited
Referenced by Slic3r::sla::connect_to_ground(), Slic3r::sla::DefaultSupportTree::connect_to_model_body(), Slic3r::sla::create_ground_pillar(), Slic3r::sla::Head::invalidate(), and Slic3r::sla::DefaultSupportTree::search_pillar_and_connect().
r
double Slic3r::sla::Bridge::r = 0.8
Referenced by Slic3r::sla::get_mesh(), and Slic3r::sla::get_mesh().
startp
Vec3d Slic3r::sla::Bridge::startp = Vec3d::Zero()
Referenced by get_dir(), get_length(), Slic3r::sla::get_mesh(), and Slic3r::sla::get_mesh().
The documentation for this struct was generated from the following file:
src/libslic3r/SLA/SupportTreeBuilder.hpp