Prusa Slicer: programmer_t Struct Reference
programmer_t Struct Reference
#include <src/avrdude/libavrdude.h>
Public Attributes
LISTID id
char desc [PGM_DESCLEN]
char type [PGM_TYPELEN]
char port [PGM_PORTLEN]
void(* initpgm)(struct programmer_t *pgm)
unsigned int pinno [N_PINS]
struct pindef_t pin [N_PINS]
exit_vcc_t exit_vcc
exit_reset_t exit_reset
exit_datahigh_t exit_datahigh
conntype_t conntype
int ppidata
int ppictrl
int baudrate
int usbvid
LISTID usbpid
char usbdev [PGM_USBSTRINGLEN]
char usbsn [PGM_USBSTRINGLEN]
char usbvendor [PGM_USBSTRINGLEN]
char usbproduct [PGM_USBSTRINGLEN]
double bitclock
int ispdelay
union filedescriptor fd
int page_size
int(* rdy_led)(struct programmer_t *pgm, int value)
int(* err_led)(struct programmer_t *pgm, int value)
int(* pgm_led)(struct programmer_t *pgm, int value)
int(* vfy_led)(struct programmer_t *pgm, int value)
int(* initialize)(struct programmer_t *pgm, AVRPART *p)
void(* display)(struct programmer_t *pgm, const char *p)
void(* enable)(struct programmer_t *pgm)
void(* disable)(struct programmer_t *pgm)
void(* powerup)(struct programmer_t *pgm)
void(* powerdown)(struct programmer_t *pgm)
int(* program_enable)(struct programmer_t *pgm, AVRPART *p)
int(* chip_erase)(struct programmer_t *pgm, AVRPART *p)
int(* cmd)(struct programmer_t *pgm, const unsigned char *cmd, unsigned char *res)
int(* cmd_tpi)(struct programmer_t *pgm, const unsigned char *cmd, int cmd_len, unsigned char res[], int res_len)
int(* spi)(struct programmer_t *pgm, const unsigned char *cmd, unsigned char *res, int count)
int(* open)(struct programmer_t *pgm, char *port)
void(* close)(struct programmer_t *pgm)
int(* paged_write)(struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned int page_size, unsigned int baseaddr, unsigned int n_bytes)
int(* paged_load)(struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned int page_size, unsigned int baseaddr, unsigned int n_bytes)
int(* page_erase)(struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned int baseaddr)
void(* write_setup)(struct programmer_t *pgm, AVRPART *p, AVRMEM *m)
int(* write_byte)(struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned long addr, unsigned char value)
int(* read_byte)(struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned long addr, unsigned char *value)
int(* read_sig_bytes)(struct programmer_t *pgm, AVRPART *p, AVRMEM *m)
void(* print_parms)(struct programmer_t *pgm)
int(* set_vtarget)(struct programmer_t *pgm, double v)
int(* set_varef)(struct programmer_t *pgm, unsigned int chan, double v)
int(* set_fosc)(struct programmer_t *pgm, double v)
int(* set_sck_period)(struct programmer_t *pgm, double v)
int(* setpin)(struct programmer_t *pgm, int pinfunc, int value)
int(* getpin)(struct programmer_t *pgm, int pinfunc)
int(* highpulsepin)(struct programmer_t *pgm, int pinfunc)
int(* parseexitspecs)(struct programmer_t *pgm, char *s)
int(* perform_osccal)(struct programmer_t *pgm)
int(* parseextparams)(struct programmer_t *pgm, LISTID xparams)
void(* setup)(struct programmer_t *pgm)
void(* teardown)(struct programmer_t *pgm)
void(* set_upload_size)(struct programmer_t *pgm, int size)
char config_file [PATH_MAX]
int lineno
void * cookie
char flag
Detailed Description
Member Data Documentation
baudrate
int programmer_t::baudrate
Referenced by arduino_open(), avr910_open(), avrdude_main(), buspirate_open(), butterfly_open(), jtagmkI_close(), jtagmkI_initialize(), jtagmkII_initialize(), pgm_new(), stk500_open(), stk500v2_open(), stk600_open(), wiring_open(), and yyparse().
bitclock
double programmer_t::bitclock
Referenced by avrdude_main(), jtag3_initialize(), jtagmkI_initialize(), jtagmkII_initialize(), stk500v2_open(), and stk600_open().
chip_erase
int(* programmer_t::chip_erase) (struct programmer_t *pgm, AVRPART *p)
Referenced by avr910_initpgm(), avr_chip_erase(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), cmd_erase(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), serbb_initpgm(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600_setup_isp(), stk600_setup_xprog(), stk600hvsp_initpgm(), and stk600pp_initpgm().
close
void(* programmer_t::close) (struct programmer_t *pgm)
Referenced by arduino_initpgm(), avr910_initpgm(), avrdude_main(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), serbb_initpgm(), stk500_initpgm(), stk500generic_open(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), stk600pp_initpgm(), and wiring_initpgm().
cmd
int(* programmer_t::cmd) (struct programmer_t *pgm, const unsigned char *cmd, unsigned char *res)
Referenced by avr910_initpgm(), avr_read_byte_default(), avr_write_byte_default(), avr_write_page(), bitbang_check_prerequisites(), bitbang_chip_erase(), bitbang_program_enable(), buspirate_bb_initpgm(), buspirate_chip_erase(), buspirate_initpgm(), buspirate_program_enable(), cmd_send(), pgm_new(), serbb_initpgm(), stk500_chip_erase(), stk500_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), and stk600_initpgm().
cmd_tpi
int(* programmer_t::cmd_tpi) (struct programmer_t *pgm, const unsigned char *cmd, int cmd_len, unsigned char res[], int res_len)
Referenced by avr_read(), avr_read_byte_default(), avr_tpi_chip_erase(), avr_tpi_poll_nvmbsy(), avr_tpi_program_enable(), avr_tpi_setup_rw(), avr_write(), avr_write_byte_default(), bitbang_initialize(), buspirate_bb_initpgm(), pgm_new(), and serbb_initpgm().
config_file
char programmer_t::config_file[PATH_MAX]
Referenced by pgm_new(), walk_programmers(), and yyparse().
conntype
conntype_t programmer_t::conntype
Referenced by avrdude_main(), and yyparse().
cookie
void* programmer_t::cookie
Referenced by avr910_setup(), avr910_teardown(), buspirate_setup(), buspirate_teardown(), butterfly_setup(), butterfly_teardown(), jtag3_setup(), jtag3_teardown(), jtagmkI_setup(), jtagmkI_teardown(), jtagmkII_setup(), jtagmkII_teardown(), stk500_setup(), stk500_teardown(), stk500v2_setup(), and stk500v2_teardown().
desc
char programmer_t::desc[PGM_DESCLEN]
Referenced by pgm_new(), programmer_display(), walk_programmers(), and yyparse().
disable
void(* programmer_t::disable) (struct programmer_t *pgm)
Referenced by avr910_initpgm(), avrdude_main(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), serbb_initpgm(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initialize(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600_set_vtarget(), stk600_setup_isp(), stk600_setup_xprog(), stk600hvsp_initpgm(), and stk600pp_initpgm().
display
void(* programmer_t::display) (struct programmer_t *pgm, const char *p)
Referenced by avr910_initpgm(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), programmer_display(), serbb_initpgm(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), and stk600pp_initpgm().
enable
void(* programmer_t::enable) (struct programmer_t *pgm)
Referenced by avr910_initpgm(), avrdude_main(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), serbb_initpgm(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), and stk600pp_initpgm().
err_led
int(* programmer_t::err_led) (struct programmer_t *pgm, int value)
Referenced by avr_read_byte_default(), avr_write(), avr_write_byte_default(), avr_write_page(), avrdude_main(), buspirate_bb_initpgm(), buspirate_paged_write(), butterfly_initpgm(), cmd_send(), cmd_write(), do_op(), pgm_new(), and serbb_initpgm().
exit_datahigh
exit_datahigh_t programmer_t::exit_datahigh
exit_reset
exit_reset_t programmer_t::exit_reset
exit_vcc
exit_vcc_t programmer_t::exit_vcc
fd
union filedescriptor programmer_t::fd
Referenced by arduino_close(), arduino_open(), arduino_read_sig_bytes(), avr910_close(), avr910_drain(), avr910_open(), avr910_recv(), avr910_send(), buspirate_bb_enable(), buspirate_close(), buspirate_enable(), buspirate_expect(), buspirate_getc(), buspirate_open(), buspirate_recv_bin(), buspirate_send(), buspirate_send_bin(), buspirate_start_mode_bin(), butterfly_close(), butterfly_drain(), butterfly_open(), butterfly_recv(), butterfly_send(), jtag3_close(), jtag3_drain(), jtag3_edbg_prepare(), jtag3_edbg_recv_frame(), jtag3_edbg_send(), jtag3_edbg_signoff(), jtag3_initialize(), jtag3_open_common(), jtag3_recv_frame(), jtag3_send(), jtagmkI_close(), jtagmkI_drain(), jtagmkI_initialize(), jtagmkI_open(), jtagmkI_program_disable(), jtagmkI_recv(), jtagmkI_resync(), jtagmkI_send(), jtagmkII_close(), jtagmkII_close32(), jtagmkII_dragon_open(), jtagmkII_dragon_open_dw(), jtagmkII_dragon_open_pdi(), jtagmkII_drain(), jtagmkII_initialize(), jtagmkII_open(), jtagmkII_open32(), jtagmkII_open_dw(), jtagmkII_open_pdi(), jtagmkII_recv_frame(), jtagmkII_send(), prusa_init_external_flash(), serbb_close(), serbb_getpin(), serbb_open(), serbb_setpin(), stk500_close(), stk500_drain(), stk500_open(), stk500_recv(), stk500_send(), stk500v2_close(), stk500v2_drain(), stk500v2_open(), stk500v2_recv(), stk500v2_recv_mk2(), stk500v2_send(), stk500v2_send_mk2(), stk600_open(), wiring_close(), and wiring_open().
flag
char programmer_t::flag
Referenced by buspirate_bb_enable(), buspirate_cmd(), buspirate_disable(), buspirate_enable(), buspirate_expect_bin(), buspirate_getc(), buspirate_paged_load(), buspirate_paged_write(), buspirate_parseextparms(), buspirate_powerdown(), buspirate_powerup(), buspirate_program_enable(), buspirate_reset_from_binmode(), buspirate_send(), buspirate_start_mode_bin(), buspirate_uses_ascii(), buspirate_verifyconfig(), butterfly_initialize(), butterfly_initpgm(), butterfly_mk_initpgm(), jtag3_close(), jtag3_dw_initpgm(), jtag3_getsync(), jtag3_initialize(), jtag3_initpgm(), jtag3_open_common(), jtag3_paged_load(), jtag3_paged_write(), jtag3_pdi_initpgm(), jtag3_read_byte(), jtag3_recv_frame(), jtag3_send(), jtag3_write_byte(), jtagmkII_avr32_initpgm(), jtagmkII_close(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initialize(), jtagmkII_initpgm(), jtagmkII_page_erase(), jtagmkII_paged_load(), jtagmkII_paged_write(), jtagmkII_pdi_initpgm(), jtagmkII_print_parms1(), jtagmkII_read_byte(), jtagmkII_reset(), and jtagmkII_write_byte().
getpin
int(* programmer_t::getpin) (struct programmer_t *pgm, int pinfunc)
Referenced by bitbang_initialize(), bitbang_tpi_clk(), bitbang_txrx(), buspirate_bb_initpgm(), and serbb_initpgm().
highpulsepin
int(* programmer_t::highpulsepin) (struct programmer_t *pgm, int pinfunc)
Referenced by bitbang_initialize(), buspirate_bb_initpgm(), and serbb_initpgm().
id
LISTID programmer_t::id
Referenced by locate_programmer(), pgm_dup(), pgm_free(), pgm_new(), sort_programmer_compare(), stk500_close(), stk500_initialize(), stk500_open(), stk500_paged_load(), stk500_paged_write(), walk_programmers(), and yyparse().
initialize
int(* programmer_t::initialize) (struct programmer_t *pgm, AVRPART *p)
Referenced by avr910_initpgm(), avr_write_byte_default(), avrdude_main(), bitbang_chip_erase(), buspirate_bb_initpgm(), buspirate_chip_erase(), buspirate_initpgm(), butterfly_initpgm(), cmd_pgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_chip_erase(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_chip_erase(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), serbb_initpgm(), stk500_chip_erase(), stk500_initpgm(), stk500hv_chip_erase(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_chip_erase(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), and stk600pp_initpgm().
initpgm
void(* programmer_t::initpgm) (struct programmer_t *pgm)
Referenced by avrdude_main(), pgm_new(), and yyparse().
ispdelay
int programmer_t::ispdelay
Referenced by avrdude_main(), and serbb_setpin().
lineno
int programmer_t::lineno
Referenced by pgm_new(), walk_programmers(), and yyparse().
open
int(* programmer_t::open) (struct programmer_t *pgm, char *port)
Referenced by arduino_initpgm(), avr910_initpgm(), avrdude_main(), avrftdi_initpgm(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), ft245r_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), pickit2_initpgm(), serbb_initpgm(), stk500_initpgm(), stk500generic_initpgm(), stk500generic_open(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), stk600pp_initpgm(), usbasp_initpgm(), usbtiny_initpgm(), and wiring_initpgm().
page_erase
int(* programmer_t::page_erase) (struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned int baseaddr)
Referenced by avr_write(), avrdude_main(), butterfly_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600_setup_isp(), and stk600_setup_xprog().
page_size
int programmer_t::page_size
Referenced by jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_paged_load32(), jtagmkII_paged_write32(), jtagmkII_pdi_initpgm(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), and stk600pp_initpgm().
paged_load
int(* programmer_t::paged_load) (struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned int page_size, unsigned int baseaddr, unsigned int n_bytes)
Referenced by avr910_initpgm(), avr_read(), buspirate_initpgm(), buspirate_start_mode_bin(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600_setup_isp(), stk600_setup_xprog(), stk600hvsp_initpgm(), and stk600pp_initpgm().
paged_write
int(* programmer_t::paged_write) (struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned int page_size, unsigned int baseaddr, unsigned int n_bytes)
Referenced by avr910_initpgm(), avr_write(), buspirate_initpgm(), buspirate_start_mode_bin(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600_setup_isp(), stk600_setup_xprog(), stk600hvsp_initpgm(), and stk600pp_initpgm().
parseexitspecs
int(* programmer_t::parseexitspecs) (struct programmer_t *pgm, char *s)
Referenced by avrdude_main().
parseextparams
int(* programmer_t::parseextparams) (struct programmer_t *pgm, LISTID xparams)
Referenced by avr910_initpgm(), avrdude_main(), buspirate_initpgm(), jtag3_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_initpgm(), pgm_new(), and wiring_initpgm().
perform_osccal
int(* programmer_t::perform_osccal) (struct programmer_t *pgm)
Referenced by avrdude_main(), pgm_new(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), and stk600_initpgm().
pgm_led
int(* programmer_t::pgm_led) (struct programmer_t *pgm, int value)
Referenced by avr_read_byte_default(), avr_tpi_chip_erase(), avr_write_byte_default(), avr_write_page(), avrdude_main(), bitbang_chip_erase(), bitbang_cmd_tpi(), buspirate_bb_initpgm(), buspirate_chip_erase(), buspirate_paged_write(), butterfly_initpgm(), pgm_new(), serbb_initpgm(), stk500_chip_erase(), stk500hv_chip_erase(), and stk500v2_chip_erase().
pin
struct pindef_t programmer_t::pin[N_PINS]
Referenced by assign_pin(), assign_pin_list(), pgm_display_generic_mask(), pgm_fill_old_pins(), pgm_new(), pins_check(), and yyparse().
pinno
unsigned int programmer_t::pinno[N_PINS]
Referenced by assign_pin_list(), avr_write_byte_default(), buspirate_bb_getpin(), buspirate_bb_setpin(), pgm_fill_old_pins(), pgm_new(), serbb_getpin(), serbb_highpulsepin(), serbb_setpin(), and verify_pin_assigned().
port
char programmer_t::port[PGM_PORTLEN]
Referenced by arduino_open(), avr910_open(), buspirate_open(), butterfly_open(), jtag3_open_common(), jtagmkI_open(), jtagmkII_dragon_open(), jtagmkII_dragon_open_dw(), jtagmkII_dragon_open_pdi(), jtagmkII_open(), jtagmkII_open32(), jtagmkII_open_dw(), jtagmkII_open_pdi(), stk500_open(), stk500v2_open(), stk600_open(), and wiring_open().
powerdown
void(* programmer_t::powerdown) (struct programmer_t *pgm)
Referenced by avr_write_byte_default(), avrdude_main(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), pgm_new(), and serbb_initpgm().
powerup
void(* programmer_t::powerup) (struct programmer_t *pgm)
Referenced by bitbang_initialize(), buspirate_bb_initpgm(), buspirate_initialize(), buspirate_initpgm(), butterfly_initpgm(), pgm_new(), and serbb_initpgm().
ppictrl
int programmer_t::ppictrl
ppidata
int programmer_t::ppidata
Referenced by avrdude_main().
print_parms
void(* programmer_t::print_parms) (struct programmer_t *pgm)
Referenced by cmd_parms(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), and stk600pp_initpgm().
program_enable
int(* programmer_t::program_enable) (struct programmer_t *pgm, AVRPART *p)
Referenced by avr910_initpgm(), bitbang_initialize(), buspirate_bb_initpgm(), buspirate_initialize(), buspirate_initpgm(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), serbb_initpgm(), stk500_initialize(), stk500_initpgm(), stk500hv_initialize(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initialize(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600_set_vtarget(), stk600_setup_isp(), stk600_setup_xprog(), stk600hvsp_initpgm(), and stk600pp_initpgm().
rdy_led
int(* programmer_t::rdy_led) (struct programmer_t *pgm, int value)
Referenced by avrdude_main(), buspirate_bb_initpgm(), butterfly_initpgm(), pgm_new(), and serbb_initpgm().
read_byte
int(* programmer_t::read_byte) (struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned long addr, unsigned char *value)
Referenced by avr910_initpgm(), avr_get_cycle_count(), avr_read(), avr_write_byte_default(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), cmd_dump(), cmd_write(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), safemode_readfuses(), safemode_writefuse(), serbb_initpgm(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600_setup_isp(), stk600_setup_xprog(), stk600hvsp_initpgm(), and stk600pp_initpgm().
read_sig_bytes
int(* programmer_t::read_sig_bytes) (struct programmer_t *pgm, AVRPART *p, AVRMEM *m)
Referenced by arduino_initpgm(), avr910_initpgm(), avr_read(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), and pgm_new().
set_fosc
int(* programmer_t::set_fosc) (struct programmer_t *pgm, double v)
Referenced by cmd_fosc(), pgm_new(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), and stk600pp_initpgm().
set_sck_period
int(* programmer_t::set_sck_period) (struct programmer_t *pgm, double v)
Referenced by cmd_sck(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_initpgm(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk500v2_open(), stk600_initpgm(), stk600_open(), stk600hvsp_initpgm(), and stk600pp_initpgm().
set_upload_size
void(* programmer_t::set_upload_size) (struct programmer_t *pgm, int size)
Referenced by do_op(), and stk500v2_initpgm().
set_varef
int(* programmer_t::set_varef) (struct programmer_t *pgm, unsigned int chan, double v)
Referenced by cmd_varef(), pgm_new(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), and stk600pp_initpgm().
set_vtarget
int(* programmer_t::set_vtarget) (struct programmer_t *pgm, double v)
Referenced by cmd_vtarg(), pgm_new(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), and stk600pp_initpgm().
setpin
int(* programmer_t::setpin) (struct programmer_t *pgm, int pinfunc, int value)
Referenced by bitbang_err_led(), bitbang_initialize(), bitbang_pgm_led(), bitbang_rdy_led(), bitbang_spi(), bitbang_tpi_clk(), bitbang_tpi_rx(), bitbang_tpi_tx(), bitbang_txrx(), bitbang_vfy_led(), buspirate_bb_initpgm(), cmd_pgm(), cmd_spi(), serbb_close(), and serbb_initpgm().
setup
void(* programmer_t::setup) (struct programmer_t *pgm)
Referenced by avr910_initpgm(), avrdude_main(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), stk500_initpgm(), stk500generic_initpgm(), stk500generic_setup(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), stk600pp_initpgm(), and wiring_initpgm().
spi
int(* programmer_t::spi) (struct programmer_t *pgm, const unsigned char *cmd, unsigned char *res, int count)
Referenced by cmd_send(), and pgm_new().
teardown
void(* programmer_t::teardown) (struct programmer_t *pgm)
Referenced by avr910_initpgm(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), cleanup_main(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), stk500_initpgm(), stk500generic_initpgm(), stk500generic_teardown(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), stk600pp_initpgm(), and wiring_initpgm().
type
char programmer_t::type[PGM_TYPELEN]
Referenced by arduino_initpgm(), avr910_initpgm(), avr_read_byte_default(), avr_write_byte_default(), avr_write_page(), avrdude_main(), avrftdi_initpgm(), bitbang_initialize(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), butterfly_mk_initpgm(), cmd_fosc(), cmd_parms(), cmd_sck(), cmd_send(), cmd_varef(), cmd_vtarg(), do_op(), flip1_initpgm(), flip2_initpgm(), ft245r_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_getsync(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), pickit2_initpgm(), programmer_display(), serbb_initpgm(), stk500_chip_erase(), stk500_initpgm(), stk500generic_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), stk600pp_initpgm(), usbasp_initpgm(), usbtiny_initpgm(), and wiring_initpgm().
usbdev
char programmer_t::usbdev[PGM_USBSTRINGLEN]
Referenced by yyparse().
usbpid
LISTID programmer_t::usbpid
Referenced by jtag3_open_common(), pgm_dup(), pgm_free(), pgm_new(), and yyparse().
usbproduct
char programmer_t::usbproduct[PGM_USBSTRINGLEN]
Referenced by yyparse().
usbsn
char programmer_t::usbsn[PGM_USBSTRINGLEN]
Referenced by yyparse().
usbvendor
char programmer_t::usbvendor[PGM_USBSTRINGLEN]
Referenced by yyparse().
usbvid
int programmer_t::usbvid
Referenced by jtag3_open_common(), and yyparse().
vfy_led
int(* programmer_t::vfy_led) (struct programmer_t *pgm, int value)
Referenced by avrdude_main(), buspirate_bb_initpgm(), butterfly_initpgm(), do_op(), pgm_new(), and serbb_initpgm().
write_byte
int(* programmer_t::write_byte) (struct programmer_t *pgm, AVRPART *p, AVRMEM *m, unsigned long addr, unsigned char value)
Referenced by avr910_initpgm(), avr_write_byte(), buspirate_bb_initpgm(), buspirate_initpgm(), butterfly_initpgm(), flip1_initpgm(), flip2_initpgm(), jtag3_dw_initpgm(), jtag3_initpgm(), jtag3_pdi_initpgm(), jtagmkI_initpgm(), jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), jtagmkII_pdi_initpgm(), pgm_new(), serbb_initpgm(), stk500_initpgm(), stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_dragon_hvsp_initpgm(), stk500v2_dragon_isp_initpgm(), stk500v2_dragon_pp_initpgm(), stk500v2_initpgm(), stk500v2_jtag3_initpgm(), stk500v2_jtagmkII_initpgm(), stk600_initpgm(), stk600_setup_isp(), stk600_setup_xprog(), stk600hvsp_initpgm(), and stk600pp_initpgm().
write_setup
void(* programmer_t::write_setup) (struct programmer_t *pgm, AVRPART *p, AVRMEM *m)
Referenced by avr_write(), and pgm_new().
The documentation for this struct was generated from the following file:
src/avrdude/libavrdude.h