Prusa Slicer: Slic3r::GUI::GCodeViewer::Layers Class Reference
Slic3r::GUI::GCodeViewer::Layers Class Reference
Classes
struct Range
Public Member Functions
void append (double z, const Range &range)
void reset ()
size_t size () const
bool empty () const
const std::vector< double > & get_zs () const
const std::vector< Range > & get_ranges () const
std::vector< Range > & get_ranges ()
double get_z_at (unsigned int id) const
Range get_range_at (unsigned int id) const
int get_l_at (double z) const
bool operator!= (const Layers &other) const
Private Attributes
std::vector< double > m_zs
std::vector< Range > m_ranges
Detailed Description
Member Function Documentation
append()
void Slic3r::GUI::GCodeViewer::Layers::append (double z, const Range & range) inline
{
            m_zs.emplace_back(z);
            m_ranges.emplace_back(range);
        }
References m_ranges, m_zs, and Slic3r::range().
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
empty()
bool Slic3r::GUI::GCodeViewer::Layers::empty () const inline
{ return m_zs.empty(); }
References m_zs.
Referenced by Slic3r::GUI::GCodeViewer::load(), Slic3r::GUI::GCodeViewer::load_toolpaths(), and Slic3r::GUI::GCodeViewer::render().
get_l_at()
int Slic3r::GUI::GCodeViewer::Layers::get_l_at (double z) const inline
{
            auto iter = std::upper_bound(m_zs.begin(), m_zs.end(), z);
            return std::distance(m_zs.begin(), iter);
        }
References m_zs.
Referenced by Slic3r::GUI::GCodeViewer::load().
get_range_at()
Range Slic3r::GUI::GCodeViewer::Layers::get_range_at (unsigned int id) const inline
{ return (id < m_ranges.size()) ? m_ranges[id] : Range(); }
References m_ranges.
Referenced by Slic3r::GUI::GCodeViewer::refresh_render_paths().
get_ranges() [1/2]
std::vector< Range > & Slic3r::GUI::GCodeViewer::Layers::get_ranges () inline
{ return m_ranges; }
References m_ranges.
get_ranges() [2/2]
const std::vector< Range > & Slic3r::GUI::GCodeViewer::Layers::get_ranges () const inline
{ return m_ranges; }
References m_ranges.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::GCodeViewer::log_memory_used(), and Slic3r::GUI::GCodeViewer::refresh_render_paths().
get_z_at()
double Slic3r::GUI::GCodeViewer::Layers::get_z_at (unsigned int id) const inline
{ return (id < m_zs.size()) ? m_zs[id] : 0.0; }
References m_zs.
get_zs()
const std::vector< double > & Slic3r::GUI::GCodeViewer::Layers::get_zs () const inline
{ return m_zs; }
References m_zs.
Referenced by Slic3r::GUI::GCodeViewer::get_layers_zs(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::GCodeViewer::log_memory_used(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), and Slic3r::GUI::GCodeViewer::render_legend().
operator!=()
bool Slic3r::GUI::GCodeViewer::Layers::operator!= (const Layers & other) const inline
{
            if (m_zs != other.m_zs)
                return true;
            if (m_ranges != other.m_ranges)
                return true;
            return false;
        }
References m_ranges, and m_zs.
reset()
void Slic3r::GUI::GCodeViewer::Layers::reset () inline
                     {
            m_zs = std::vector<double>();
            m_ranges = std::vector<Range>();
        }
References m_ranges, and m_zs.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths(), and Slic3r::GUI::GCodeViewer::reset().
size()
size_t Slic3r::GUI::GCodeViewer::Layers::size () const inline
{ return m_zs.size(); }
References m_zs.
Member Data Documentation
m_ranges
std::vector<Range> Slic3r::GUI::GCodeViewer::Layers::m_ranges private
Referenced by append(), get_range_at(), get_ranges(), get_ranges(), operator!=(), and reset().
m_zs
std::vector<double> Slic3r::GUI::GCodeViewer::Layers::m_zs private
Referenced by append(), empty(), get_l_at(), get_z_at(), get_zs(), operator!=(), reset(), and size().
The documentation for this class was generated from the following file:
src/slic3r/GUI/GCodeViewer.hpp