Prusa Slicer: src/avrdude/avr910.h File Reference
avr910.h File Reference
Functions
void avr910_initpgm (PROGRAMMER *pgm)
Variables
const char avr910_desc []
Function Documentation
avr910_initpgm()
void avr910_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "avr910");
  /*
   * mandatory functions
   */
  pgm->initialize     = avr910_initialize;
  pgm->display        = avr910_display;
  pgm->enable         = avr910_enable;
  pgm->disable        = avr910_disable;
  pgm->program_enable = avr910_program_enable;
  pgm->chip_erase     = avr910_chip_erase;
  pgm->cmd            = avr910_cmd;
  pgm->open           = avr910_open;
  pgm->close          = avr910_close;
  /*
   * optional functions
   */
  pgm->write_byte = avr910_write_byte;
  pgm->read_byte = avr910_read_byte;
  pgm->paged_write = avr910_paged_write;
  pgm->paged_load = avr910_paged_load;
  pgm->read_sig_bytes = avr910_read_sig_bytes;
  pgm->parseextparams = avr910_parseextparms;
  pgm->setup          = avr910_setup;
  pgm->teardown       = avr910_teardown;
}
References avr910_chip_erase(), avr910_close(), avr910_cmd(), avr910_disable(), avr910_display(), avr910_enable(), avr910_initialize(), avr910_open(), avr910_paged_load(), avr910_paged_write(), avr910_parseextparms(), avr910_program_enable(), avr910_read_byte(), avr910_read_sig_bytes(), avr910_setup(), avr910_teardown(), avr910_write_byte(), programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::paged_load, programmer_t::paged_write, programmer_t::parseextparams, pgm, programmer_t::program_enable, programmer_t::read_byte, programmer_t::read_sig_bytes, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
Variable Documentation
avr910_desc
const char avr910_desc[] extern