Prusa Slicer: Slic3r::Flow Class Reference
Slic3r::Flow Class Reference
#include <src/libslic3r/Flow.hpp>
Public Member Functions
Flow ()=default
Flow (float width, float height, float nozzle_diameter)
float width () const
coord_t scaled_width () const
float height () const
float spacing () const
coord_t scaled_spacing () const
float nozzle_diameter () const
bool bridge () const
double mm3_per_mm () const
coord_t scaled_elephant_foot_spacing () const
bool operator== (const Flow &rhs) const
Flow with_width (float width) const
Flow with_height (float height) const
Flow with_spacing (float spacing) const
Flow with_cross_section (float area) const
Flow with_flow_ratio (double ratio) const
Static Public Member Functions
static Flow bridging_flow (float dmr, float nozzle_diameter)
static Flow new_from_config_width (FlowRole role, const ConfigOptionFloatOrPercent &width, float nozzle_diameter, float height)
static float rounded_rectangle_extrusion_spacing (float width, float height)
static float rounded_rectangle_extrusion_width_from_spacing (float spacing, float height)
static float bridge_extrusion_spacing (float dmr)
static float auto_extrusion_width (FlowRole role, float nozzle_diameter)
static double extrusion_width (const std::string &opt_key, const ConfigOptionFloatOrPercent *opt, const ConfigOptionResolver &config, const unsigned int first_printing_extruder=0)
static double extrusion_width (const std::string &opt_key, const ConfigOptionResolver &config, const unsigned int first_printing_extruder=0)
Private Member Functions
Flow (float width, float height, float spacing, float nozzle_diameter, bool bridge)
Private Attributes
float m_width { 0 }
float m_height { 0 }
float m_spacing { 0 }
float m_nozzle_diameter { 0 }
bool m_bridge { false }
Detailed Description
Constructor & Destructor Documentation
Flow() [1/3]
Slic3r::Flow::Flow () default
Referenced by new_from_config_width(), with_cross_section(), with_height(), and with_width().
Flow() [2/3]
Slic3r::Flow::Flow (float width, float height, float nozzle_diameter) inline
                                                           :
        Flow(width, height, rounded_rectangle_extrusion_spacing(width, height), nozzle_diameter, false) {}
Flow() [3/3]
Slic3r::Flow::Flow (float width, float height, float spacing, float nozzle_diameter, bool bridge) inline private
                                                                                       :
        m_width(width), m_height(height), m_spacing(spacing), m_nozzle_diameter(nozzle_diameter), m_bridge(bridge)
        {
            // Gap fill violates this condition.
            //assert(width >= height);
        }
Member Function Documentation
auto_extrusion_width()
float Slic3r::Flow::auto_extrusion_width (FlowRole role, float nozzle_diameter) static
{
    switch (role) {
    case frSupportMaterial:
    case frSupportMaterialInterface:
    case frTopSolidInfill:
        return nozzle_diameter;
    default:
    case frExternalPerimeter:
    case frPerimeter:
    case frSolidInfill:
    case frInfill:
        return 1.125f * nozzle_diameter;
    }
}
References Slic3r::frExternalPerimeter, Slic3r::frInfill, Slic3r::frPerimeter, Slic3r::frSolidInfill, Slic3r::frSupportMaterial, Slic3r::frSupportMaterialInterface, Slic3r::frTopSolidInfill, and nozzle_diameter().
Referenced by Slic3r::FillLightning::Generator::Generator(), Slic3r::FillAdaptive::adaptive_fill_line_spacing(), extrusion_width(), and new_from_config_width().
bridge()
bool Slic3r::Flow::bridge () const inline
{ return m_bridge; }
References m_bridge.
Referenced by Slic3r::PerimeterGenerator::thick_polyline_to_multi_path().
bridge_extrusion_spacing()
float Slic3r::Flow::bridge_extrusion_spacing (float dmr) static
{
    return dmr + BRIDGE_EXTRA_SPACING;
}
References BRIDGE_EXTRA_SPACING.
Referenced by bridging_flow().
bridging_flow()
static Flow Slic3r::Flow::bridging_flow (float dmr, float nozzle_diameter) inline static
{ return Flow { dmr, dmr, bridge_extrusion_spacing(dmr), nozzle_diameter, true }; }
References bridge_extrusion_spacing(), and nozzle_diameter().
Referenced by Slic3r::FFFSupport::SupportParameters::SupportParameters(), Slic3r::LayerRegion::bridging_flow(), Slic3r::PresetHints::maximum_volumetric_flow_description(), and Slic3r::ExtrusionPath::polygons_covered_by_spacing().
extrusion_width() [1/2]
double Slic3r::Flow::extrusion_width (const std::string & opt_key, const ConfigOptionFloatOrPercent * opt, const ConfigOptionResolver & config, const unsigned int first_printing_extruder = 0) static
{
  assert(opt != nullptr);
  bool first_layer = boost::starts_with(opt_key, "first_layer_");
#if 0
// This is the logic used for skit / brim, but not for the rest of the 1st layer.
  if (opt->value == 0. && first_layer) {
    // The "first_layer_extrusion_width" was set to zero, try a substitute.
    opt = config.option<ConfigOptionFloatOrPercent>("perimeter_extrusion_width");
    if (opt == nullptr)
        throw_on_missing_variable(opt_key, "perimeter_extrusion_width");
  }
#endif
  if (opt->value == 0.) {
    // The role specific extrusion width value was set to zero, try the role non-specific extrusion width.
    opt = config.option<ConfigOptionFloatOrPercent>("extrusion_width");
    if (opt == nullptr)
        throw_on_missing_variable(opt_key, "extrusion_width");
      // Use the "layer_height" instead of "first_layer_height".
      first_layer = false;
  }
  if (opt->percent) {
    auto opt_key_layer_height = first_layer ? "first_layer_height" : "layer_height";
        auto opt_layer_height = config.option(opt_key_layer_height);
      if (opt_layer_height == nullptr)
        throw_on_missing_variable(opt_key, opt_key_layer_height);
        assert(! first_layer || ! static_cast<const ConfigOptionFloatOrPercent*>(opt_layer_height)->percent);
    return opt->get_abs_value(opt_layer_height->getFloat());
  }
  if (opt->value == 0.) {
        // If user left option to 0, calculate a sane default width.
      auto opt_nozzle_diameters = config.option<ConfigOptionFloats>("nozzle_diameter");
      if (opt_nozzle_diameters == nullptr)
        throw_on_missing_variable(opt_key, "nozzle_diameter");
        return auto_extrusion_width(opt_key_to_flow_role(opt_key), float(opt_nozzle_diameters->get_at(first_printing_extruder)));
    }
  return opt->value;
}
References auto_extrusion_width(), Slic3r::ConfigOptionFloatOrPercent::get_abs_value(), Slic3r::opt_key_to_flow_role(), Slic3r::ConfigOptionResolver::option(), Slic3r::ConfigOptionFloatOrPercent::percent, Slic3r::throw_on_missing_variable(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by extrusion_width(), and Slic3r::client::MyContext::scalar_variable_to_expr().
extrusion_width() [2/2]
double Slic3r::Flow::extrusion_width (const std::string & opt_key, const ConfigOptionResolver & config, const unsigned int first_printing_extruder = 0) static
{
    return extrusion_width(opt_key, config.option<ConfigOptionFloatOrPercent>(opt_key), config, first_printing_extruder);
}
References extrusion_width(), and Slic3r::ConfigOptionResolver::option().
height()
float Slic3r::Flow::height () const inline
{ return m_height; }
References m_height.
Referenced by Slic3r::FFFSupport::fill_expolygon_generate_paths(), Slic3r::FFFSupport::fill_expolygons_with_sheath_generate_paths(), Slic3r::FFFSupport::LoopInterfaceProcessor::generate(), Slic3r::generate_extra_perimeters_over_overhangs(), new_from_config_width(), Slic3r::SurfaceFillParams::operator<(), Slic3r::GCode::process_layer(), rounded_rectangle_extrusion_spacing(), rounded_rectangle_extrusion_width_from_spacing(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), Slic3r::traverse_loops_classic(), Slic3r::FFFSupport::tree_supports_generate_paths(), with_cross_section(), and with_height().
mm3_per_mm()
double Slic3r::Flow::mm3_per_mm () const
{
    float res = m_bridge ?
        // Area of a circle with dmr of this->width.
        float((m_width * m_width) * 0.25 * PI) :
        // Rectangle with semicircles at the ends. ~ h (w - 0.215 h)
        float(m_height * (m_width - m_height * (1. - 0.25 * PI)));
    //assert(res > 0.);
  if (res <= 0.)
    throw FlowErrorNegativeFlow();
    return res;
}
References m_bridge, m_height, m_width, and PI.
Referenced by Slic3r::Print::_make_skirt(), Slic3r::FFFSupport::fill_expolygon_generate_paths(), Slic3r::FFFSupport::fill_expolygons_with_sheath_generate_paths(), Slic3r::FFFSupport::LoopInterfaceProcessor::generate(), Slic3r::generate_extra_perimeters_over_overhangs(), Slic3r::Layer::make_fills(), Slic3r::PresetHints::maximum_volumetric_flow_description(), Slic3r::FFFSupport::modulate_extrusion_by_overlapping_layers(), Slic3r::GCode::process_layer(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), Slic3r::FFFSupport::tree_supports_generate_paths(), with_cross_section(), and with_flow_ratio().
new_from_config_width()
Flow Slic3r::Flow::new_from_config_width (FlowRole role, const ConfigOptionFloatOrPercent & width, float nozzle_diameter, float height) static
{
    if (height <= 0)
        throw Slic3r::InvalidArgument("Invalid flow height supplied to new_from_config_width()");
    float w;
    if (! width.percent && width.value == 0.) {
        // If user left option to 0, calculate a sane default width.
        w = auto_extrusion_width(role, nozzle_diameter);
    } else {
        // If user set a manual value, use it.
        w = float(width.get_abs_value(height));
    }
    return Flow(w, height, rounded_rectangle_extrusion_spacing(w, height), nozzle_diameter, false);
}
References Flow(), auto_extrusion_width(), height(), nozzle_diameter(), rounded_rectangle_extrusion_spacing(), and width().
Referenced by Slic3r::Print::brim_flow(), Slic3r::PrintRegion::flow(), Slic3r::PresetHints::maximum_volumetric_flow_description(), Slic3r::PresetHints::recommended_thin_wall_thickness(), Slic3r::Print::skirt_flow(), Slic3r::support_material_1st_layer_flow(), Slic3r::support_material_flow(), and Slic3r::support_material_interface_flow().
nozzle_diameter()
float Slic3r::Flow::nozzle_diameter () const inline
{ return m_nozzle_diameter; }
References m_nozzle_diameter.
Referenced by Slic3r::FFFSupport::SupportParameters::SupportParameters(), auto_extrusion_width(), bridging_flow(), Slic3r::FFFSupport::generate_support_toolpaths(), new_from_config_width(), Slic3r::SurfaceFillParams::operator<(), Slic3r::PerimeterGenerator::process_classic(), and Slic3r::SeamPlacerImpl::process_perimeter_polygon().
operator==()
bool Slic3r::Flow::operator== (const Flow & rhs) const inline
{ return m_width == rhs.m_width && m_height == rhs.m_height && m_nozzle_diameter == rhs.m_nozzle_diameter && m_bridge == rhs.m_bridge; }
References m_bridge, m_height, m_nozzle_diameter, and m_width.
rounded_rectangle_extrusion_spacing()
float Slic3r::Flow::rounded_rectangle_extrusion_spacing (float width, float height) static
{
    auto out = width - height * float(1. - 0.25 * PI);
    if (out <= 0.f)
        throw FlowErrorNegativeSpacing();
    return out;
}
References height(), PI, and width().
Referenced by new_from_config_width(), with_height(), and with_width().
rounded_rectangle_extrusion_width_from_spacing()
float Slic3r::Flow::rounded_rectangle_extrusion_width_from_spacing (float spacing, float height) static
{
    return float(spacing + height * (1. - 0.25 * PI));
}
References height(), PI, and spacing().
Referenced by Slic3r::Arachne::WallToolPaths::generate(), and with_cross_section().
scaled_elephant_foot_spacing()
coord_t Slic3r::Flow::scaled_elephant_foot_spacing () const inline
{ return coord_t(0.5f * float(this->scaled_width() + 0.6f * this->scaled_spacing())); }
References scaled_spacing(), and scaled_width().
scaled_spacing()
coord_t Slic3r::Flow::scaled_spacing () const inline
{ return coord_t(scale_(m_spacing)); }
References m_spacing, and scale_.
Referenced by Slic3r::PrintObject::discover_vertical_shells(), Slic3r::FFFSupport::fill_expolygons_with_sheath_generate_paths(), Slic3r::FFFSupport::LoopInterfaceProcessor::generate(), Slic3r::generate_extra_perimeters_over_overhangs(), Slic3r::FFFSupport::generate_interface_layers(), Slic3r::make_brim(), Slic3r::make_inner_brim(), Slic3r::PerimeterGenerator::process_arachne(), Slic3r::PerimeterGenerator::process_classic(), Slic3r::LayerRegion::process_external_surfaces(), Slic3r::FFFSupport::remove_bridges_from_contacts(), scaled_elephant_foot_spacing(), and Slic3r::FFFSupport::tree_supports_generate_paths().
scaled_width()
coord_t Slic3r::Flow::scaled_width () const inline
{ return coord_t(scale_(m_width)); }
References m_width, and scale_.
Referenced by Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::TreeSupportMeshGroupSettings(), Slic3r::detect_overhangs(), Slic3r::PrintObject::detect_surfaces_type(), Slic3r::PrintObject::discover_vertical_shells(), Slic3r::FFFSupport::fill_expolygons_with_sheath_generate_paths(), Slic3r::FFFSupport::LoopInterfaceProcessor::generate(), Slic3r::generate_extra_perimeters_over_overhangs(), Slic3r::FFFSupport::generate_raft_base(), Slic3r::FFFSupport::generate_support_toolpaths(), Slic3r::PerimeterGenerator::process_arachne(), Slic3r::PerimeterGenerator::process_classic(), Slic3r::LayerRegion::process_external_surfaces(), Slic3r::FFFSupport::remove_bridges_from_contacts(), scaled_elephant_foot_spacing(), and Slic3r::FFFSupport::tree_supports_generate_paths().
spacing()
float Slic3r::Flow::spacing () const inline
{ return m_spacing; }
References m_spacing.
Referenced by Slic3r::FFFSupport::SupportParameters::SupportParameters(), Slic3r::Print::_make_skirt(), Slic3r::elephant_foot_compensation(), Slic3r::FFFTreeSupport::generate_support_infill_lines(), Slic3r::FFFSupport::generate_support_toolpaths(), Slic3r::group_fills(), Slic3r::make_brim(), Slic3r::PerimeterGenerator::process_arachne(), Slic3r::PerimeterGenerator::process_classic(), Slic3r::PresetHints::recommended_thin_wall_thickness(), and rounded_rectangle_extrusion_width_from_spacing().
width()
float Slic3r::Flow::width () const inline
{ return m_width; }
References m_width.
Referenced by Slic3r::FFFSupport::SupportParameters::SupportParameters(), Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::TreeSupportMeshGroupSettings(), Slic3r::GCode::_do_export(), Slic3r::Print::_make_skirt(), Slic3r::elephant_foot_compensation(), Slic3r::PrintObject::estimate_curled_extrusions(), Slic3r::FFFSupport::fill_expolygon_generate_paths(), Slic3r::FFFSupport::fill_expolygons_with_sheath_generate_paths(), Slic3r::FFFSupport::LoopInterfaceProcessor::generate(), Slic3r::generate_extra_perimeters_over_overhangs(), Slic3r::FFFSupport::generate_support_toolpaths(), Slic3r::SupportSpotsGenerator::get_flow_width(), Slic3r::Layer::make_fills(), new_from_config_width(), Slic3r::SurfaceFillParams::operator<(), Slic3r::SeamPlacerImpl::process_perimeter_polygon(), Slic3r::PresetHints::recommended_thin_wall_thickness(), rounded_rectangle_extrusion_spacing(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), Slic3r::traverse_loops_classic(), Slic3r::FFFSupport::tree_supports_generate_paths(), and with_width().
with_cross_section()
Flow Slic3r::Flow::with_cross_section (float area) const
{
    assert(! m_bridge);
    assert(m_width >= m_height);
    // Adjust for bridge_flow_ratio, maintain the extrusion spacing.
    float area = this->mm3_per_mm();
    if (area_new > area + EPSILON) {
        // Increasing the flow rate.
        float new_full_spacing = area_new / m_height;
        if (new_full_spacing > m_spacing) {
            // Filling up the spacing without an air gap. Grow the extrusion in height.
            float height = area_new / m_spacing;
            return Flow(rounded_rectangle_extrusion_width_from_spacing(m_spacing, height), height, m_spacing, m_nozzle_diameter, false);
        } else {
            return this->with_width(rounded_rectangle_extrusion_width_from_spacing(area / m_height, m_height));
        }
    } else if (area_new < area - EPSILON) {
        // Decreasing the flow rate.
        float width_new = m_width - (area - area_new) / m_height;
        assert(width_new > 0);
        if (width_new > m_height) {
            // Shrink the extrusion width.
            return this->with_width(width_new);
        } else {
            // Create a rounded extrusion.
            auto dmr = 2.0 * float(sqrt(area_new / M_PI));
            return Flow(dmr, dmr, m_spacing, m_nozzle_diameter, false);
        }
    } else
        return *this;
}
References Flow(), Slic3r::area(), EPSILON, height(), m_bridge, m_height, m_nozzle_diameter, M_PI, m_spacing, m_width, mm3_per_mm(), rounded_rectangle_extrusion_width_from_spacing(), sqrt(), and with_width().
Referenced by with_flow_ratio().
with_flow_ratio()
Flow Slic3r::Flow::with_flow_ratio (double ratio) const inline
{ return this->with_cross_section(this->mm3_per_mm() * ratio); }
References mm3_per_mm(), and with_cross_section().
Referenced by Slic3r::FFFSupport::SupportParameters::SupportParameters(), and Slic3r::LayerRegion::bridging_flow().
with_height()
Flow Slic3r::Flow::with_height (float height) const inline
{
        assert(! m_bridge);
        return Flow(m_width, height, rounded_rectangle_extrusion_spacing(m_width, height), m_nozzle_diameter, m_bridge);
    }
References Flow(), height(), m_bridge, m_nozzle_diameter, m_width, and rounded_rectangle_extrusion_spacing().
Referenced by Slic3r::FFFSupport::LoopInterfaceProcessor::generate(), and Slic3r::GCode::process_layer().
with_spacing()
Flow Slic3r::Flow::with_spacing (float spacing) const
{
    Flow out = *this;
    if (m_bridge) {
        // Diameter of the rounded extrusion.
        assert(m_width == m_height);
        float gap          = m_spacing - m_width;
        auto  new_diameter = new_spacing - gap;
        out.m_width        = out.m_height = new_diameter;
    } else {
        assert(m_width >= m_height);
        out.m_width += new_spacing - m_spacing;
        if (out.m_width < out.m_height)
            throw Slic3r::InvalidArgument("Invalid spacing supplied to Flow::with_spacing()");
    }
    out.m_spacing = new_spacing;
    return out;
}
References m_bridge, m_height, m_spacing, and m_width.
Referenced by Slic3r::Layer::make_fills().
with_width()
Flow Slic3r::Flow::with_width (float width) const inline
{
        assert(! m_bridge);
        return Flow(width, m_height, rounded_rectangle_extrusion_spacing(width, m_height), m_nozzle_diameter, m_bridge);
    }
References Flow(), m_bridge, m_height, m_nozzle_diameter, rounded_rectangle_extrusion_spacing(), and width().
Referenced by Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), and with_cross_section().
Member Data Documentation
m_bridge
bool Slic3r::Flow::m_bridge { false } private
Referenced by bridge(), mm3_per_mm(), operator==(), with_cross_section(), with_height(), with_spacing(), and with_width().
m_height
float Slic3r::Flow::m_height { 0 } private
Referenced by height(), mm3_per_mm(), operator==(), with_cross_section(), with_spacing(), and with_width().
m_nozzle_diameter
float Slic3r::Flow::m_nozzle_diameter { 0 } private
Referenced by nozzle_diameter(), operator==(), with_cross_section(), with_height(), and with_width().
m_spacing
float Slic3r::Flow::m_spacing { 0 } private
Referenced by scaled_spacing(), spacing(), with_cross_section(), and with_spacing().
m_width
float Slic3r::Flow::m_width { 0 } private
Referenced by mm3_per_mm(), operator==(), scaled_width(), width(), with_cross_section(), with_height(), and with_spacing().
The documentation for this class was generated from the following files:
src/libslic3r/Flow.hpp
src/libslic3r/Flow.cpp