Prusa Slicer: igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU > Class Template Reference
igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU > Class Template Reference
Public Member Functions
IGL_INLINE MIQ_class (const Eigen::PlainObjectBase< DerivedV > &V_, const Eigen::PlainObjectBase< DerivedF > &F_, const Eigen::PlainObjectBase< DerivedV > &PD1_combed, const Eigen::PlainObjectBase< DerivedV > &PD2_combed, const Eigen::Matrix< int, Eigen::Dynamic, 3 > &Handle_MMatch, const Eigen::Matrix< int, Eigen::Dynamic, 1 > &Handle_Singular, const Eigen::Matrix< int, Eigen::Dynamic, 3 > &Handle_Seams, Eigen::PlainObjectBase< DerivedU > &UV, Eigen::PlainObjectBase< DerivedF > &FUV, double GradientSize=30.0, double Stiffness=5.0, bool DirectRound=false, int iter=5, int localIter=5, bool DoRound=true, bool SingularityRound=true, std::vector< int > roundVertices=std::vector< int >(), std::vector< std::vector< int > > hardFeatures=std::vector< std::vector< int > >())
IGL_INLINE void extractUV (Eigen::PlainObjectBase< DerivedU > &UV_out, Eigen::PlainObjectBase< DerivedF > &FUV_out)
Private Member Functions
IGL_INLINE int NumFlips (const Eigen::MatrixXd &WUV)
IGL_INLINE double Distortion (int f, double h, const Eigen::MatrixXd &WUV)
IGL_INLINE double LaplaceDistortion (const int f, double h, const Eigen::MatrixXd &WUV)
IGL_INLINE bool updateStiffeningJacobianDistorsion (double grad_size, const Eigen::MatrixXd &WUV)
IGL_INLINE bool IsFlipped (const Eigen::Vector2d &uv0, const Eigen::Vector2d &uv1, const Eigen::Vector2d &uv2)
IGL_INLINE bool IsFlipped (const int i, const Eigen::MatrixXd &WUV)
Private Attributes
const Eigen::PlainObjectBase< DerivedV > & V
const Eigen::PlainObjectBase< DerivedF > & F
DerivedV Vcut
DerivedF Fcut
Eigen::MatrixXd UV_out
DerivedF FUV_out
DerivedF TT
DerivedF TTi
Eigen::VectorXd Handle_Stiffness
DerivedV B1
DerivedV B2
DerivedV B3
Detailed Description
template<typename DerivedV, typename DerivedF, typename DerivedU>
class igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >
Constructor & Destructor Documentation
MIQ_class()
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class (const Eigen::PlainObjectBase< DerivedV > & V_, const Eigen::PlainObjectBase< DerivedF > & F_, const Eigen::PlainObjectBase< DerivedV > & PD1_combed, const Eigen::PlainObjectBase< DerivedV > & PD2_combed, const Eigen::Matrix< int, Eigen::Dynamic, 3 > & Handle_MMatch, const Eigen::Matrix< int, Eigen::Dynamic, 1 > & Handle_Singular, const Eigen::Matrix< int, Eigen::Dynamic, 3 > & Handle_Seams, Eigen::PlainObjectBase< DerivedU > & UV, Eigen::PlainObjectBase< DerivedF > & FUV, double GradientSize = 30.0, double Stiffness = 5.0, bool DirectRound = false, int iter = 5, int localIter = 5, bool DoRound = true, bool SingularityRound = true, std::vector< int > roundVertices = std::vector<int>(), std::vector< std::vector< int > > hardFeatures = std::vector<std::vector<int> >())
                                                                                                           :
V(V_),
F(F_)
{
  igl::cut_mesh(V, F, Handle_Seams, Vcut, Fcut);
  igl::local_basis(V,F,B1,B2,B3);
  igl::triangle_triangle_adjacency(F,TT,TTi);
  // Prepare indexing for the linear system
  VertexIndexing<DerivedV, DerivedF> VInd(V, F, Vcut, Fcut, TT, TTi, Handle_MMatch, Handle_Singular, Handle_Seams);
  VInd.InitSeamInfo();
  // Assemble the system and solve
  PoissonSolver<DerivedV, DerivedF> PSolver(V,
                                            F,
                                            Vcut,
                                            Fcut,
                                            TT,
                                            TTi,
                                            PD1_combed,
                                            PD2_combed,
                                            Handle_Singular,
                                            VInd.Handle_SystemInfo);
  Handle_Stiffness = Eigen::VectorXd::Constant(F.rows(),1);
  if (iter > 0) // do stiffening
  {
    for (int i=0;i<iter;i++)
    {
      PSolver.SolvePoisson(Handle_Stiffness, GradientSize,1.f,DirectRound,localIter,DoRound,SingularityRound,roundVertices,hardFeatures);
      int nflips=NumFlips(PSolver.WUV);
      bool folded = updateStiffeningJacobianDistorsion(GradientSize,PSolver.WUV);
      printf("ITERATION %d FLIPS %d \n",i,nflips);
      if (!folded)break;
    }
  }
  else
  {
    PSolver.SolvePoisson(Handle_Stiffness,GradientSize,1.f,DirectRound,localIter,DoRound,SingularityRound,roundVertices,hardFeatures);
  }
  int nflips=NumFlips(PSolver.WUV);
  printf("**** END OPTIMIZING #FLIPS %d  ****\n",nflips);
  UV_out = PSolver.UV_out;
  FUV_out = PSolver.Fcut;
  fflush(stdout);
}
References igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::B1, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::B2, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::B3, igl::cut_mesh(), igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::F, igl::copyleft::comiso::PoissonSolver< DerivedV, DerivedF >::Fcut, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::Fcut, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::FUV_out, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::Handle_Stiffness, igl::copyleft::comiso::VertexIndexing< DerivedV, DerivedF >::Handle_SystemInfo, igl::copyleft::comiso::VertexIndexing< DerivedV, DerivedF >::InitSeamInfo(), igl::local_basis(), igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::NumFlips(), Eigen::PlainObjectBase< Derived >::rows(), igl::copyleft::comiso::PoissonSolver< DerivedV, DerivedF >::SolvePoisson(), igl::triangle_triangle_adjacency(), igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::TT, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::TTi, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::updateStiffeningJacobianDistorsion(), igl::copyleft::comiso::PoissonSolver< DerivedV, DerivedF >::UV_out, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::UV_out, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::V, igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::Vcut, and igl::copyleft::comiso::PoissonSolver< DerivedV, DerivedF >::WUV.
Member Function Documentation
Distortion()
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE double igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::Distortion (int f, double h, const Eigen::MatrixXd & WUV) private
{
  assert(h > 0);
  Eigen::Vector2d uv0,uv1,uv2;
  uv0 << WUV(f,0), WUV(f,1);
  uv1 << WUV(f,2), WUV(f,3);
  uv2 << WUV(f,4), WUV(f,5);
  Eigen::Matrix<typename DerivedV::Scalar, 3, 1> p0 = Vcut.row(Fcut(f,0));
  Eigen::Matrix<typename DerivedV::Scalar, 3, 1> p1 = Vcut.row(Fcut(f,1));
  Eigen::Matrix<typename DerivedV::Scalar, 3, 1> p2 = Vcut.row(Fcut(f,2));
  Eigen::Matrix<typename DerivedV::Scalar, 3, 1> norm = (p1 - p0).cross(p2 - p0);
  double area2 = norm.norm();
  double area2_inv  = 1.0 / area2;
  norm *= area2_inv;
  if (area2 > 0)
  {
    // Singular values of the Jacobian
    Eigen::Matrix<typename DerivedV::Scalar, 3, 1> neg_t0 = norm.cross(p2 - p1);
    Eigen::Matrix<typename DerivedV::Scalar, 3, 1> neg_t1 = norm.cross(p0 - p2);
    Eigen::Matrix<typename DerivedV::Scalar, 3, 1> neg_t2 = norm.cross(p1 - p0);
    Eigen::Matrix<typename DerivedV::Scalar, 3, 1> diffu =  (neg_t0 * uv0(0) +neg_t1 *uv1(0) +  neg_t2 * uv2(0) )*area2_inv;
    Eigen::Matrix<typename DerivedV::Scalar, 3, 1> diffv = (neg_t0 * uv0(1) + neg_t1*uv1(1) +  neg_t2*uv2(1) )*area2_inv;
    // first fundamental form
    double I00 = diffu.dot(diffu);  // guaranteed non-neg
    double I01 = diffu.dot(diffv);  // I01 = I10
    double I11 = diffv.dot(diffv);  // guaranteed non-neg
    // eigenvalues of a 2x2 matrix
    // [a00 a01]
    // [a10 a11]
    // 1/2 * [ (a00 + a11) +/- sqrt((a00 - a11)^2 + 4 a01 a10) ]
    double trI = I00 + I11;                     // guaranteed non-neg
    double diffDiag = I00 - I11;                // guaranteed non-neg
    double sqrtDet = sqrt(std::max(0.0, diffDiag*diffDiag +
                                   4 * I01 * I01)); // guaranteed non-neg
    double sig1 = 0.5 * (trI + sqrtDet); // higher singular value
    double sig2 = 0.5 * (trI - sqrtDet); // lower singular value
    // Avoid sig2 < 0 due to numerical error
    if (fabs(sig2) < 1.0e-8)
      sig2 = 0;
    assert(sig1 >= 0);
    assert(sig2 >= 0);
    if (sig2 < 0) {
      printf("Distortion will be NaN! sig1^2 is negative (%lg)\n",
             sig2);
    }
    // The singular values of the Jacobian are the sqrts of the
    // eigenvalues of the first fundamental form.
    sig1 = sqrt(sig1);
    sig2 = sqrt(sig2);
    // distortion
    double tao = IsFlipped(f,WUV) ? -1 : 1;
    double factor = tao / h;
    double lam = fabs(factor * sig1 - 1) + fabs(factor * sig2 - 1);
    return lam;
  }
  else {
    return 10; // something "large"
  }
}
References igl::cross(), and sqrt().
extractUV()
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE void igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::extractUV (Eigen::PlainObjectBase< DerivedU > & UV_out, Eigen::PlainObjectBase< DerivedF > & FUV_out)
{
  UV_out = this->UV_out;
  FUV_out = this->FUV_out;
}
IsFlipped() [1/2]
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE bool igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::IsFlipped (const Eigen::Vector2d & uv0, const Eigen::Vector2d & uv1, const Eigen::Vector2d & uv2) private
{
  Eigen::Vector2d e0 = (uv1-uv0);
  Eigen::Vector2d e1 = (uv2-uv0);
  double Area = e0(0)*e1(1) - e0(1)*e1(0);
  return (Area<=0);
}
IsFlipped() [2/2]
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE bool igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::IsFlipped (const int i, const Eigen::MatrixXd & WUV) private
{
  Eigen::Vector2d uv0,uv1,uv2;
  uv0 << WUV(i,0), WUV(i,1);
  uv1 << WUV(i,2), WUV(i,3);
  uv2 << WUV(i,4), WUV(i,5);
  return (IsFlipped(uv0,uv1,uv2));
}
LaplaceDistortion()
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE double igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::LaplaceDistortion (const int f, double h, const Eigen::MatrixXd & WUV) private
{
  double mydist = Distortion(f, h, WUV);
  double lapl=0;
  for (int i=0;i<3;i++)
  {
    if (TT(f,i) != -1)
      lapl += (mydist - Distortion(TT(f,i), h, WUV));
  }
  return lapl;
}
NumFlips()
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE int igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::NumFlips (const Eigen::MatrixXd & WUV) private
{
  int numFl=0;
  for (unsigned int i=0;i<F.rows();i++)
  {
    if (IsFlipped(i, WUV))
      numFl++;
  }
  return numFl;
}
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
updateStiffeningJacobianDistorsion()
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE bool igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::updateStiffeningJacobianDistorsion (double grad_size, const Eigen::MatrixXd & WUV) private
{
  bool flipped = NumFlips(WUV)>0;
  if (!flipped)
    return false;
  double maxL=0;
  double maxD=0;
  if (flipped)
  {
    const double c = 1.0;
    const double d = 5.0;
    for (unsigned int i = 0; i < Fcut.rows(); ++i)
    {
      double dist=Distortion(i,grad_size,WUV);
      if (dist > maxD)
        maxD=dist;
      double absLap=fabs(LaplaceDistortion(i, grad_size,WUV));
      if (absLap > maxL)
        maxL = absLap;
      double stiffDelta = std::min(c * absLap, d);
      Handle_Stiffness[i]+=stiffDelta;
    }
  }
  printf("Maximum Distorsion %4.4f \n",maxD);
  printf("Maximum Laplacian %4.4f \n",maxL);
  return flipped;
}
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
Member Data Documentation
B1
template<typename DerivedV , typename DerivedF , typename DerivedU > DerivedV igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::B1 private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
B2
template<typename DerivedV , typename DerivedF , typename DerivedU > DerivedV igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::B2 private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
B3
template<typename DerivedV , typename DerivedF , typename DerivedU > DerivedV igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::B3 private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
F
template<typename DerivedV , typename DerivedF , typename DerivedU > const Eigen::PlainObjectBase<DerivedF>& igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::F private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
Fcut
template<typename DerivedV , typename DerivedF , typename DerivedU > DerivedF igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::Fcut private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
FUV_out
template<typename DerivedV , typename DerivedF , typename DerivedU > DerivedF igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::FUV_out private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
Handle_Stiffness
template<typename DerivedV , typename DerivedF , typename DerivedU > Eigen::VectorXd igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::Handle_Stiffness private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
TT
template<typename DerivedV , typename DerivedF , typename DerivedU > DerivedF igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::TT private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
TTi
template<typename DerivedV , typename DerivedF , typename DerivedU > DerivedF igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::TTi private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
UV_out
template<typename DerivedV , typename DerivedF , typename DerivedU > Eigen::MatrixXd igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::UV_out private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
V
template<typename DerivedV , typename DerivedF , typename DerivedU > const Eigen::PlainObjectBase<DerivedV>& igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::V private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
Vcut
template<typename DerivedV , typename DerivedF , typename DerivedU > DerivedV igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::Vcut private
Referenced by igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class().
The documentation for this class was generated from the following file:
src/libigl/igl/copyleft/comiso/miq.cpp