Prusa Slicer: igl::copyleft::comiso Namespace Reference
igl::copyleft::comiso Namespace Reference
Classes
class FrameInterpolator
struct MeshSystemInfo
class MIQ_class
class NRosyField
class PoissonSolver
struct SeamInfo
class VertexIndexing
Functions
IGL_INLINE void frame_field (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F, const Eigen::VectorXi &b, const Eigen::MatrixXd &bc1, const Eigen::MatrixXd &bc2, Eigen::MatrixXd &FF1, Eigen::MatrixXd &FF2)
template<typename DerivedV , typename DerivedF , typename DerivedU >
IGL_INLINE void miq (const Eigen::PlainObjectBase< DerivedV > &V, const Eigen::PlainObjectBase< DerivedF > &F, const Eigen::PlainObjectBase< DerivedV > &PD1, const Eigen::PlainObjectBase< DerivedV > &PD2, Eigen::PlainObjectBase< DerivedU > &UV, Eigen::PlainObjectBase< DerivedF > &FUV, double scale=30.0, double stiffness=5.0, bool direct_round=false, int iter=5, int local_iter=5, bool DoRound=true, bool SingularityRound=true, std::vector< int > round_vertices=std::vector< int >(), std::vector< std::vector< int > > hard_features=std::vector< std::vector< int > >())
template<typename DerivedV , typename DerivedF , typename DerivedU >
IGL_INLINE void miq (const Eigen::PlainObjectBase< DerivedV > &V, const Eigen::PlainObjectBase< DerivedF > &F, const Eigen::PlainObjectBase< DerivedV > &PD1_combed, const Eigen::PlainObjectBase< DerivedV > &PD2_combed, const Eigen::Matrix< int, Eigen::Dynamic, 3 > &MMatch, const Eigen::Matrix< int, Eigen::Dynamic, 1 > &Singular, const Eigen::Matrix< int, Eigen::Dynamic, 3 > &Seams, Eigen::PlainObjectBase< DerivedU > &UV, Eigen::PlainObjectBase< DerivedF > &FUV, double GradientSize=30.0, double Stiffness=5.0, bool DirectRound=false, int iter=5, int localIter=5, bool DoRound=true, bool SingularityRound=true, std::vector< int > roundVertices=std::vector< int >(), std::vector< std::vector< int > > hardFeatures=std::vector< std::vector< int > >())
IGL_INLINE void nrosy (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F, const Eigen::VectorXi &b, const Eigen::MatrixXd &bc, const Eigen::VectorXi &b_soft, const Eigen::VectorXd &w_soft, const Eigen::MatrixXd &bc_soft, const int N, const double soft, Eigen::MatrixXd &R, Eigen::VectorXd &S)
IGL_INLINE void nrosy (const Eigen::MatrixXd &V, const Eigen::MatrixXi &F, const Eigen::VectorXi &b, const Eigen::MatrixXd &bc, const int N, Eigen::MatrixXd &R, Eigen::VectorXd &S)
Class Documentation
igl::copyleft::comiso::MeshSystemInfo
struct igl::copyleft::comiso::MeshSystemInfo
Class Members
vector< SeamInfo > EdgeSeamInfo this are used for drawing purposes
int num_integer_cuts num of integer for cuts
int num_vert_variables
Function Documentation
frame_field()
IGL_INLINE void igl::copyleft::comiso::frame_field (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F, const Eigen::VectorXi & b, const Eigen::MatrixXd & bc1, const Eigen::MatrixXd & bc2, Eigen::MatrixXd & FF1, Eigen::MatrixXd & FF2)
{
  using namespace std;
  using namespace Eigen;
  assert(b.size() > 0);
  // Init Solver
  FrameInterpolator field(V,F);
  for (unsigned i=0; i<b.size(); ++i)
  {
    VectorXd t(6); t << bc1.row(i).transpose(), bc2.row(i).transpose();
    field.setConstraint(b(i), t);
  }
  // Solve
  field.solve();
  // Copy back
  MatrixXd R = field.getFieldPerFace();
  FF1 = R.block(0, 0, R.rows(), 3);
  FF2 = R.block(0, 3, R.rows(), 3);
}
References igl::copyleft::comiso::FrameInterpolator::getFieldPerFace(), igl::copyleft::comiso::FrameInterpolator::setConstraint(), and igl::copyleft::comiso::FrameInterpolator::solve().
miq() [1/2]
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE void igl::copyleft::comiso::miq (const Eigen::PlainObjectBase< DerivedV > & V, const Eigen::PlainObjectBase< DerivedF > & F, const Eigen::PlainObjectBase< DerivedV > & PD1, const Eigen::PlainObjectBase< DerivedV > & PD2, Eigen::PlainObjectBase< DerivedU > & UV, Eigen::PlainObjectBase< DerivedF > & FUV, double scale = 30.0, double stiffness = 5.0, bool direct_round = false, int iter = 5, int local_iter = 5, bool DoRound = true, bool SingularityRound = true, std::vector< int > round_vertices = std::vector<int>(), std::vector< std::vector< int > > hard_features = std::vector<std::vector<int> >())
{
  DerivedV BIS1, BIS2;
  igl::compute_frame_field_bisectors(V, F, PD1, PD2, BIS1, BIS2);
  DerivedV BIS1_combed, BIS2_combed;
  igl::comb_cross_field(V, F, BIS1, BIS2, BIS1_combed, BIS2_combed);
  DerivedF Handle_MMatch;
  igl::cross_field_missmatch(V, F, BIS1_combed, BIS2_combed, true, Handle_MMatch);
  Eigen::Matrix<int, Eigen::Dynamic, 1> isSingularity, singularityIndex;
  igl::find_cross_field_singularities(V, F, Handle_MMatch, isSingularity, singularityIndex);
  Eigen::Matrix<int, Eigen::Dynamic, 3> Handle_Seams;
  igl::cut_mesh_from_singularities(V, F, Handle_MMatch, Handle_Seams);
  DerivedV PD1_combed, PD2_combed;
  igl::comb_frame_field(V, F, PD1, PD2, BIS1_combed, BIS2_combed, PD1_combed, PD2_combed);
  igl::copyleft::comiso::miq(V,
           F,
           PD1_combed,
           PD2_combed,
           Handle_MMatch,
           isSingularity,
           Handle_Seams,
           UV,
           FUV,
           GradientSize,
           Stiffness,
           DirectRound,
           iter,
           localIter,
           DoRound,
           SingularityRound,
           roundVertices,
           hardFeatures);
}
References igl::comb_cross_field(), igl::comb_frame_field(), igl::compute_frame_field_bisectors(), igl::cross_field_missmatch(), igl::cut_mesh_from_singularities(), igl::find_cross_field_singularities(), and miq().
Referenced by miq(), and miq().
miq() [2/2]
template<typename DerivedV , typename DerivedF , typename DerivedU > IGL_INLINE void igl::copyleft::comiso::miq (const Eigen::PlainObjectBase< DerivedV > & V, const Eigen::PlainObjectBase< DerivedF > & F, const Eigen::PlainObjectBase< DerivedV > & PD1_combed, const Eigen::PlainObjectBase< DerivedV > & PD2_combed, const Eigen::Matrix< int, Eigen::Dynamic, 3 > & MMatch, const Eigen::Matrix< int, Eigen::Dynamic, 1 > & Singular, const Eigen::Matrix< int, Eigen::Dynamic, 3 > & Seams, Eigen::PlainObjectBase< DerivedU > & UV, Eigen::PlainObjectBase< DerivedF > & FUV, double GradientSize = 30.0, double Stiffness = 5.0, bool DirectRound = false, int iter = 5, int localIter = 5, bool DoRound = true, bool SingularityRound = true, std::vector< int > roundVertices = std::vector<int>(), std::vector< std::vector< int > > hardFeatures = std::vector<std::vector<int> >())
{
  GradientSize = GradientSize/(V.colwise().maxCoeff()-V.colwise().minCoeff()).norm();
  igl::copyleft::comiso::MIQ_class<DerivedV, DerivedF, DerivedU> miq(V,
    F,
    PD1_combed,
    PD2_combed,
    Handle_MMatch,
    Handle_Singular,
    Handle_Seams,
    UV,
    FUV,
    GradientSize,
    Stiffness,
    DirectRound,
    iter,
    localIter,
    DoRound,
    SingularityRound,
    roundVertices,
    hardFeatures);
  miq.extractUV(UV,FUV);
}
References miq().
nrosy() [1/2]
IGL_INLINE void igl::copyleft::comiso::nrosy (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F, const Eigen::VectorXi & b, const Eigen::MatrixXd & bc, const Eigen::VectorXi & b_soft, const Eigen::VectorXd & w_soft, const Eigen::MatrixXd & bc_soft, const int N, const double soft, Eigen::MatrixXd & R, Eigen::VectorXd & S)
{
  // Init solver
  igl::copyleft::comiso::NRosyField solver(V,F);
  // Add hard constraints
  for (unsigned i=0; i<b.size();++i)
    solver.setConstraintHard(b(i),bc.row(i));
  // Add soft constraints
  for (unsigned i=0; i<b_soft.size();++i)
    solver.setConstraintSoft(b_soft(i),w_soft(i),bc_soft.row(i));
  // Set the soft constraints global weight
  solver.setSoftAlpha(soft);
  // Interpolate
  solver.solve(N);
  // Copy the result back
  R = solver.getFieldPerFace();
  // Extract singularity indices
  S = solver.getSingularityIndexPerVertex();
}
References igl::copyleft::comiso::NRosyField::getFieldPerFace(), igl::copyleft::comiso::NRosyField::getSingularityIndexPerVertex(), igl::copyleft::comiso::NRosyField::setConstraintHard(), igl::copyleft::comiso::NRosyField::setConstraintSoft(), igl::copyleft::comiso::NRosyField::setSoftAlpha(), and igl::copyleft::comiso::NRosyField::solve().
Referenced by igl::copyleft::comiso::FrameInterpolator::interpolateCross().
nrosy() [2/2]
IGL_INLINE void igl::copyleft::comiso::nrosy (const Eigen::MatrixXd & V, const Eigen::MatrixXi & F, const Eigen::VectorXi & b, const Eigen::MatrixXd & bc, const int N, Eigen::MatrixXd & R, Eigen::VectorXd & S)
{
  // Init solver
  igl::copyleft::comiso::NRosyField solver(V,F);
  // Add hard constraints
  for (unsigned i=0; i<b.size();++i)
    solver.setConstraintHard(b(i),bc.row(i));
  // Interpolate
  solver.solve(N);
  // Copy the result back
  R = solver.getFieldPerFace();
  // Extract singularity indices
  S = solver.getSingularityIndexPerVertex();
}
References igl::copyleft::comiso::NRosyField::getFieldPerFace(), igl::copyleft::comiso::NRosyField::getSingularityIndexPerVertex(), igl::copyleft::comiso::NRosyField::setConstraintHard(), and igl::copyleft::comiso::NRosyField::solve().