Prusa Slicer: Slic3r::sla::RotfinderBoilerplate< MAX_ITER > Struct Template Reference
Slic3r::sla::RotfinderBoilerplate< MAX_ITER > Struct Template Reference
Public Member Functions
RotfinderBoilerplate (const ModelObject &mo, const RotOptimizeParams &p)
void statusfn ()
bool stopcond ()
Static Public Member Functions
static TriangleMesh get_mesh_to_rotate (const ModelObject &mo)
Public Attributes
int status = 0
int prev_status = 0
TriangleMesh mesh
unsigned max_tries
const RotOptimizeParams & params
Static Public Attributes
static constexpr unsigned MAX_TRIES = MAX_ITER
Detailed Description
template<unsigned MAX_ITER>
struct Slic3r::sla::RotfinderBoilerplate< MAX_ITER >
Constructor & Destructor Documentation
RotfinderBoilerplate()
template<unsigned MAX_ITER> Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::RotfinderBoilerplate (const ModelObject & mo, const RotOptimizeParams & p) inline
        : mesh{get_mesh_to_rotate(mo)}
        , max_tries(p.accuracy() * MAX_TRIES)
        , params{p}
    {}
Member Function Documentation
get_mesh_to_rotate()
template<unsigned MAX_ITER> static TriangleMesh Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::get_mesh_to_rotate (const ModelObject & mo) inline static
    {
        TriangleMesh mesh = mo.raw_mesh();
        ModelInstance *mi = mo.instances[0];
        const Geometry::Transformation trafo = mi->get_transformation();
        Transform3d trafo_instance = trafo.get_scaling_factor_matrix() * trafo.get_mirror_matrix();
        mesh.transform(trafo_instance);
        return mesh;
    }
References Slic3r::Geometry::Transformation::get_mirror_matrix(), Slic3r::Geometry::Transformation::get_scaling_factor_matrix(), Slic3r::ModelInstance::get_transformation(), Slic3r::ModelObject::instances, Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::mesh, Slic3r::ModelObject::raw_mesh(), and Slic3r::TriangleMesh::transform().
statusfn()
template<unsigned MAX_ITER> void Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::statusfn () inline
                    {
        int s = status * 100 / max_tries;
        if (s != prev_status) {
            params.statuscb()(s);
            prev_status = s;
        }
        ++status;
    }
References Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::max_tries, Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::params, Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::prev_status, Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::status, and Slic3r::sla::RotOptimizeParams::statuscb().
stopcond()
template<unsigned MAX_ITER> bool Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::stopcond () inline
{ return ! params.statuscb()(-1); }
References Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::params, and Slic3r::sla::RotOptimizeParams::statuscb().
Member Data Documentation
MAX_TRIES
template<unsigned MAX_ITER> constexpr unsigned Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::MAX_TRIES = MAX_ITER static constexpr
max_tries
template<unsigned MAX_ITER> unsigned Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::max_tries
Referenced by Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::statusfn().
mesh
template<unsigned MAX_ITER> TriangleMesh Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::mesh
Referenced by Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::get_mesh_to_rotate().
params
template<unsigned MAX_ITER> const RotOptimizeParams& Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::params
Referenced by Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::statusfn(), and Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::stopcond().
prev_status
template<unsigned MAX_ITER> int Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::prev_status = 0
Referenced by Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::statusfn().
status
template<unsigned MAX_ITER> int Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::status = 0
Referenced by Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::statusfn().
The documentation for this struct was generated from the following file:
src/libslic3r/SLA/Rotfinder.cpp