Prusa Slicer: Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType > Struct Template Reference
Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType > Struct Template Reference
Expression type for return value of HessenbergDecomposition::matrixH()
#include <src/eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h>
Public Types
typedef internal::traits< HessenbergDecompositionMatrixHReturnType< MatrixType > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
HessenbergDecompositionMatrixHReturnType (const HessenbergDecomposition< MatrixType > &hess)
Constructor.
template<typename ResultType >
void evalTo (ResultType &result) const
Hessenberg matrix in decomposition.
Index rows () const
Index cols () const
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
const HessenbergDecomposition< MatrixType > & m_hess
Detailed Description
template<typename MatrixType>
struct Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >
Expression type for return value of HessenbergDecomposition::matrixH()
\eigenvalues_module
Template Parameters
MatrixType type of matrix in the Hessenberg decomposition
Objects of this type represent the Hessenberg matrix in the Hessenberg decomposition of some matrix. The object holds a reference to the HessenbergDecomposition class until the it is assigned or evaluated for some other reason (the reference should remain valid during the life time of this object). This class is the return type of HessenbergDecomposition::matrixH(); there is probably no other use for this class.
Member Typedef Documentation
Base
typedef internal::dense_xpr_base<ReturnByValue>::type Eigen::ReturnByValue< HessenbergDecompositionMatrixHReturnType< MatrixType > >::Base inherited
ReturnType
typedef internal::traits<HessenbergDecompositionMatrixHReturnType< MatrixType > >::ReturnType Eigen::ReturnByValue< HessenbergDecompositionMatrixHReturnType< MatrixType > >::ReturnType inherited
Constructor & Destructor Documentation
HessenbergDecompositionMatrixHReturnType()
template<typename MatrixType > Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::HessenbergDecompositionMatrixHReturnType (const HessenbergDecomposition< MatrixType > & hess) inline
Constructor.
Parameters
[in] hess Hessenberg decomposition
: m_hess(hess) { }
Member Function Documentation
coeff() [1/2]
const Unusable & Eigen::ReturnByValue< HessenbergDecompositionMatrixHReturnType< MatrixType > >::coeff (Index) const inline inherited
{ return *reinterpret_cast<const Unusable*>(this); }
coeff() [2/2]
const Unusable & Eigen::ReturnByValue< HessenbergDecompositionMatrixHReturnType< MatrixType > >::coeff (Index , Index) const inline inherited
{ return *reinterpret_cast<const Unusable*>(this); }
coeffRef() [1/2]
Unusable & Eigen::ReturnByValue< HessenbergDecompositionMatrixHReturnType< MatrixType > >::coeffRef (Index) inline inherited
{ return *reinterpret_cast<Unusable*>(this); }
coeffRef() [2/2]
Unusable & Eigen::ReturnByValue< HessenbergDecompositionMatrixHReturnType< MatrixType > >::coeffRef (Index , Index) inline inherited
{ return *reinterpret_cast<Unusable*>(this); }
cols()
template<typename MatrixType > Index Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::cols () const inline
{ return m_hess.packedMatrix().cols(); }
References Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::m_hess, and Eigen::HessenbergDecomposition< _MatrixType >::packedMatrix().
evalTo() [1/2]
EIGEN_DEVICE_FUNC void Eigen::ReturnByValue< HessenbergDecompositionMatrixHReturnType< MatrixType > >::evalTo (Dest & dst) const inline inherited
    { static_cast<const Derived*>(this)->evalTo(dst); }
evalTo() [2/2]
template<typename MatrixType > template<typename ResultType > void Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::evalTo (ResultType & result) const inline
Hessenberg matrix in decomposition.
Parameters
[out] result Hessenberg matrix in decomposition hess which was passed to the constructor
    {
      result = m_hess.packedMatrix();
      Index n = result.rows();
      if (n>2)
        result.bottomLeftCorner(n-2, n-2).template triangularView<Lower>().setZero();
    }
References Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::m_hess, and Eigen::HessenbergDecomposition< _MatrixType >::packedMatrix().
rows()
template<typename MatrixType > Index Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::rows () const inline
{ return m_hess.packedMatrix().rows(); }
References Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::m_hess, and Eigen::HessenbergDecomposition< _MatrixType >::packedMatrix().
Member Data Documentation
m_hess
template<typename MatrixType > const HessenbergDecomposition<MatrixType>& Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::m_hess protected
Referenced by Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::cols(), Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::evalTo(), and Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::rows().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h