Prusa Slicer: Slic3r::SeamPlacerImpl::SeamComparator Struct Reference
Slic3r::SeamPlacerImpl::SeamComparator Struct Reference
Public Member Functions
SeamComparator (SeamPosition setup)
bool is_first_better (const SeamCandidate &a, const SeamCandidate &b, const Vec2f &preffered_location=Vec2f { 0.0f, 0.0f }) const
bool is_first_not_much_worse (const SeamCandidate &a, const SeamCandidate &b) const
bool are_similar (const SeamCandidate &a, const SeamCandidate &b) const
Public Attributes
SeamPosition setup
float angle_importance
Detailed Description
Constructor & Destructor Documentation
SeamComparator()
Slic3r::SeamPlacerImpl::SeamComparator::SeamComparator (SeamPosition setup) inline explicit
                                                :
            setup(setup) {
        angle_importance =
                setup == spNearest ? SeamPlacer::angle_importance_nearest : SeamPlacer::angle_importance_aligned;
    }
References Slic3r::spNearest.
Member Function Documentation
are_similar()
bool Slic3r::SeamPlacerImpl::SeamComparator::are_similar (const SeamCandidate & a, const SeamCandidate & b) const inline
{
        return is_first_not_much_worse(a, b) && is_first_not_much_worse(b, a);
    }
is_first_better()
bool Slic3r::SeamPlacerImpl::SeamComparator::is_first_better (const SeamCandidate & a, const SeamCandidate & b, const Vec2f & preffered_location = Vec2f { 0.0f, 0.0f }) const inline
                                                                                                                 { 0.0f,
            0.0f }) const {
        if (setup == SeamPosition::spAligned && a.central_enforcer != b.central_enforcer) {
            return a.central_enforcer;
        }
        // Blockers/Enforcers discrimination, top priority
        if (a.type != b.type) {
            return a.type > b.type;
        }
        //avoid overhangs
        if (a.overhang > 0.0f || b.overhang > 0.0f) {
            return a.overhang < b.overhang;
        }
        // prefer hidden points (more than 0.5 mm inside)
        if (a.embedded_distance < -0.5f && b.embedded_distance > -0.5f) {
            return true;
        }
        if (b.embedded_distance < -0.5f && a.embedded_distance > -0.5f) {
            return false;
        }
        if (setup == SeamPosition::spRear && a.position.y() != b.position.y()) {
            return a.position.y() > b.position.y();
        }
        float distance_penalty_a = 0.0f;
        float distance_penalty_b = 0.0f;
        if (setup == spNearest) {
            distance_penalty_a = 1.0f - gauss((a.position.head<2>() - preffered_location).norm(), 0.0f, 1.0f, 0.005f);
            distance_penalty_b = 1.0f - gauss((b.position.head<2>() - preffered_location).norm(), 0.0f, 1.0f, 0.005f);
        }
        // the penalites are kept close to range [0-1.x] however, it should not be relied upon
        float penalty_a = a.overhang + a.visibility +
                angle_importance * compute_angle_penalty(a.local_ccw_angle)
                + distance_penalty_a;
        float penalty_b = b.overhang + b.visibility +
                angle_importance * compute_angle_penalty(b.local_ccw_angle)
                + distance_penalty_b;
        return penalty_a < penalty_b;
    }
Referenced by Slic3r::SeamPlacer::find_next_seam_in_layer(), and Slic3r::SeamPlacerImpl::pick_seam_point().
is_first_not_much_worse()
bool Slic3r::SeamPlacerImpl::SeamComparator::is_first_not_much_worse (const SeamCandidate & a, const SeamCandidate & b) const inline
{
        // Blockers/Enforcers discrimination, top priority
        if (setup == SeamPosition::spAligned && a.central_enforcer != b.central_enforcer) {
            // Prefer centers of enforcers.
            return a.central_enforcer;
        }
        if (a.type == EnforcedBlockedSeamPoint::Enforced) {
            return true;
        }
        if (a.type == EnforcedBlockedSeamPoint::Blocked) {
            return false;
        }
        if (a.type != b.type) {
            return a.type > b.type;
        }
        //avoid overhangs
        if ((a.overhang > 0.0f || b.overhang > 0.0f)
                && abs(a.overhang - b.overhang) > (0.1f * a.perimeter.flow_width)) {
            return a.overhang < b.overhang;
        }
        // prefer hidden points (more than 0.5 mm inside)
        if (a.embedded_distance < -0.5f && b.embedded_distance > -0.5f) {
            return true;
        }
        if (b.embedded_distance < -0.5f && a.embedded_distance > -0.5f) {
            return false;
        }
        if (setup == SeamPosition::spRandom) {
            return true;
        }
        if (setup == SeamPosition::spRear) {
            return a.position.y() + SeamPlacer::seam_align_score_tolerance * 5.0f > b.position.y();
        }
        float penalty_a = a.overhang + a.visibility
                + angle_importance * compute_angle_penalty(a.local_ccw_angle);
        float penalty_b = b.overhang + b.visibility +
                angle_importance * compute_angle_penalty(b.local_ccw_angle);
        return penalty_a <= penalty_b || penalty_a - penalty_b < SeamPlacer::seam_align_score_tolerance;
    }
References Slic3r::SeamPlacerImpl::compute_angle_penalty().
Referenced by Slic3r::SeamPlacer::find_next_seam_in_layer().
Member Data Documentation
angle_importance
float Slic3r::SeamPlacerImpl::SeamComparator::angle_importance
setup
SeamPosition Slic3r::SeamPlacerImpl::SeamComparator::setup
Referenced by Slic3r::SeamPlacer::align_seam_points().
The documentation for this struct was generated from the following file:
src/libslic3r/GCode/SeamPlacer.cpp