Prusa Slicer: Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse > Class Template Reference
Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse > Class Template Reference
#include <src/eigen/Eigen/src/SparseCore/SparseBlock.h>
Public Types
enum { IsRowMajor = internal::traits<BlockType>::IsRowMajor }
typedef internal::remove_all< typenameXprType::Nested >::type _MatrixTypeNested
enum
typedef internal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::StorageKind StorageKind
typedef internal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typenameinternal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< constDerived > >, Transpose< constDerived > >::type AdjointReturnType
typedef Transpose< Block< XprType, BlockRows, BlockCols, InnerPanel > > TransposeReturnType
typedef internal::add_const< Transpose< constDerived > >::type ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional< _HasDirectAccess, constScalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef Block< Block< XprType, BlockRows, BlockCols, InnerPanel >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > InnerVectorReturnType
typedef Block< const Block< XprType, BlockRows, BlockCols, InnerPanel >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > ConstInnerVectorReturnType
typedef Block< Block< XprType, BlockRows, BlockCols, InnerPanel >, Dynamic, Dynamic, true > InnerVectorsReturnType
typedef Block< const Block< XprType, BlockRows, BlockCols, InnerPanel >, Dynamic, Dynamic, true > ConstInnerVectorsReturnType
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
BlockImpl (XprType &xpr, Index i)
BlockImpl (XprType &xpr, Index startRow, Index startCol, Index blockRows, Index blockCols)
Index rows () const
Index cols () const
Scalar & coeffRef (Index row, Index col)
const Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index index)
const Scalar coeff (Index index) const
const XprType & nestedExpression () const
XprType & nestedExpression ()
Index startRow () const
Index startCol () const
Index blockRows () const
Index blockCols () const
const Block< XprType, BlockRows, BlockCols, InnerPanel > & derived () const
Block< XprType, BlockRows, BlockCols, InnerPanel > & derived ()
Block< XprType, BlockRows, BlockCols, InnerPanel > & const_cast_derived () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Block< XprType, BlockRows, BlockCols, InnerPanel > & markAsRValue ()
Block< XprType, BlockRows, BlockCols, InnerPanel > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, InnerPanel > & operator+= (const DiagonalBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, InnerPanel > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Block< XprType, BlockRows, BlockCols, InnerPanel > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, InnerPanel > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, InnerPanel > & operator-= (const DiagonalBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, InnerPanel > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Block< XprType, BlockRows, BlockCols, InnerPanel > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, InnerPanel > & operator*= (const Scalar &other)
Block< XprType, BlockRows, BlockCols, InnerPanel > & operator*= (const SparseMatrixBase< OtherDerived > &other)
Block< XprType, BlockRows, BlockCols, InnerPanel > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< Block< XprType, BlockRows, BlockCols, InnerPanel >, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< Block< XprType, BlockRows, BlockCols, InnerPanel >, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< Block< XprType, BlockRows, BlockCols, InnerPanel >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Block< XprType, BlockRows, BlockCols, InnerPanel >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const Block< XprType, BlockRows, BlockCols, InnerPanel >, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
internal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar dot (const MatrixBase< OtherDerived > &other) const
internal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
InnerVectorReturnType innerVector (Index outer)
const ConstInnerVectorReturnType innerVector (Index outer) const
InnerVectorsReturnType innerVectors (Index outerStart, Index outerSize)
const ConstInnerVectorsReturnType innerVectors (Index outerStart, Index outerSize) const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Block< XprType, BlockRows, BlockCols, InnerPanel > >::type eval () const
Scalar sum () const
const SparseView< Block< XprType, BlockRows, BlockCols, InnerPanel > > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
Index nonZeros () const
template<typename T >
BlockImpl & operator= (const T &)
Block< XprType, BlockRows, BlockCols, InnerPanel > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Protected Attributes
internal::ref_selector< XprType >::non_const_type m_matrix
const internal::variable_if_dynamic< Index, XprType::RowsAtCompileTime==1 ? 0 :Dynamic > m_startRow
const internal::variable_if_dynamic< Index, XprType::ColsAtCompileTime==1 ? 0 :Dynamic > m_startCol
const internal::variable_if_dynamic< Index, RowsAtCompileTime > m_blockRows
const internal::variable_if_dynamic< Index, ColsAtCompileTime > m_blockCols
bool m_isRValue
Private Types
typedef Block< XprType, BlockRows, BlockCols, InnerPanel > BlockType
typedef SparseMatrixBase< BlockType > Base
Private Member Functions
void evalTo (Dest &) const
Static Private Member Functions
static StorageIndex convert_index (const Index idx)
Friends
struct internal::unary_evaluator< Block< XprType, BlockRows, BlockCols, InnerPanel >, internal::IteratorBased, Scalar >
Detailed Description
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel>
class Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >
Generic implementation of sparse Block expression. Real-only.
Member Typedef Documentation
_MatrixTypeNested
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> typedef internal::remove_all<typenameXprType::Nested>::type Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::_MatrixTypeNested
AdjointReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,Eigen::Transpose<constDerived>>,Transpose<constDerived>>::type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::AdjointReturnType inherited
Base
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> typedef SparseMatrixBase<BlockType> Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::Base private
BlockType
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> typedef Block<XprType, BlockRows, BlockCols, InnerPanel> Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::BlockType private
CoeffReturnType
typedef internal::conditional<_HasDirectAccess,constScalar&,Scalar>::type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::CoeffReturnType inherited
ConstantReturnType
typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,Matrix<Scalar,Dynamic,Dynamic> > Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::ConstantReturnType inherited
ConstInnerVectorReturnType
typedef Block<const Block< XprType, BlockRows, BlockCols, InnerPanel > ,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::ConstInnerVectorReturnType inherited
ConstInnerVectorsReturnType
typedef Block<const Block< XprType, BlockRows, BlockCols, InnerPanel > ,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::ConstInnerVectorsReturnType inherited
ConstTransposeReturnType
typedef internal::add_const<Transpose<constDerived>>::type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::ConstTransposeReturnType inherited
DenseMatrixType
typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime> Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::DenseMatrixType inherited
type of the equivalent dense matrix
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
IndexVector
typedef Matrix<StorageIndex,Dynamic,1> Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::IndexVector inherited
InnerVectorReturnType
typedef Block<Block< XprType, BlockRows, BlockCols, InnerPanel > ,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::InnerVectorReturnType inherited
InnerVectorsReturnType
typedef Block<Block< XprType, BlockRows, BlockCols, InnerPanel > ,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::InnerVectorsReturnType inherited
PacketReturnType
typedef internal::add_const_on_value_type_if_arithmetic<typenameinternal::packet_traits<Scalar>::type>::type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::PacketReturnType inherited
PacketScalar
typedef internal::packet_traits<Scalar>::type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::PacketScalar inherited
PlainObject
typedef SparseMatrix<Scalar, Flags&RowMajorBit ? RowMajor : ColMajor, StorageIndex> Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::PlainObject inherited
RealScalar
typedef NumTraits<Scalar>::Real Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::RealScalar inherited
This is the "real scalar" type; if the Scalar type is already real numbers (e.g. int, float or double) then RealScalar is just the same as Scalar. If Scalar is std::complex<T> then RealScalar is T.
See also
class NumTraits
Scalar
typedef internal::traits<Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar inherited
ScalarVector
typedef Matrix<Scalar,Dynamic,1> Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::ScalarVector inherited
SquareMatrixType
typedef Matrix<Scalar,EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime)> Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::SquareMatrixType inherited
type of the equivalent square matrix
StorageBaseType
typedef SparseMatrixBase Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::StorageBaseType inherited
StorageIndex
typedef internal::traits<Block< XprType, BlockRows, BlockCols, InnerPanel > >::StorageIndex Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::StorageIndex inherited
The integer type used to store indices within a SparseMatrix. For a SparseMatrix<Scalar,Options,IndexType> it an alias of the third template parameter IndexType.
StorageKind
typedef internal::traits<Block< XprType, BlockRows, BlockCols, InnerPanel > >::StorageKind Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::StorageKind inherited
TransposeReturnType
typedef Transpose<Block< XprType, BlockRows, BlockCols, InnerPanel > > Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::TransposeReturnType inherited
value_type
typedef Scalar Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::value_type inherited
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
anonymous enum
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> anonymous enum
Enumerator
IsRowMajor
{ IsRowMajor = internal::traits<BlockType>::IsRowMajor };
anonymous enum
anonymous enum inherited
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = RowsAtCompileTime,
      MaxColsAtCompileTime = ColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<MaxRowsAtCompileTime,
                                                      MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1,
      Flags = internal::traits<Derived>::Flags,
      IsRowMajor = Flags&RowMajorBit ? 1 : 0,
      InnerSizeAtCompileTime = int(IsVectorAtCompileTime) ? int(SizeAtCompileTime)
                             : int(IsRowMajor) ? int(ColsAtCompileTime) : int(RowsAtCompileTime),
      #ifndef EIGEN_PARSED_BY_DOXYGEN
      _HasDirectAccess = (int(Flags)&DirectAccessBit) ? 1 : 0 // workaround sunCC
      #endif
    };
Constructor & Destructor Documentation
BlockImpl() [1/2]
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::BlockImpl (XprType & xpr, Index i) inline
Column or Row constructor
      : m_matrix(xpr),
        m_startRow( (BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) ? convert_index(i) : 0),
        m_startCol( (BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) ? convert_index(i) : 0),
        m_blockRows(BlockRows==1 ? 1 : xpr.rows()),
        m_blockCols(BlockCols==1 ? 1 : xpr.cols())
    {}
BlockImpl() [2/2]
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::BlockImpl (XprType & xpr, Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Dynamic-size constructor
      : m_matrix(xpr), m_startRow(convert_index(startRow)), m_startCol(convert_index(startCol)), m_blockRows(convert_index(blockRows)), m_blockCols(convert_index(blockCols))
    {}
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
const AdjointReturnType Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::adjoint () const inline inherited
{ return AdjointReturnType(transpose()); }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
assign()
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::assign (const OtherDerived & other) inline protected inherited
assignGeneric()
void Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::assignGeneric (const OtherDerived & other) inline protected inherited
blockCols()
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::blockCols () const inline
{ return m_blockCols.value(); }
blockRows()
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::blockRows () const inline
{ return m_blockRows.value(); }
blueNorm()
NumTraits< typenameinternal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar >::Real Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::blueNorm inline inherited
{
  return internal::blueNorm_impl(*this);
}
coeff() [1/2]
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> const Scalar Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeff (Index index) const inline
    {
      return m_matrix.coeff(m_startRow.value() + (RowsAtCompileTime == 1 ? 0 : index),
                            m_startCol.value() + (RowsAtCompileTime == 1 ? index : 0));
    }
coeff() [2/2]
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> const Scalar Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeff (Index row, Index col) const inline
    {
      return m_matrix.coeff(row + m_startRow.value(), col + m_startCol.value());
    }
References col(), and row().
coeffRef() [1/2]
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Scalar & Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeffRef (Index index) inline
    {
      return m_matrix.coeffRef(m_startRow.value() + (RowsAtCompileTime == 1 ? 0 : index),
                               m_startCol.value() + (RowsAtCompileTime == 1 ? index : 0));
    }
coeffRef() [2/2]
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Scalar & Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeffRef (Index row, Index col) inline
    {
      return m_matrix.coeffRef(row + m_startRow.value(), col + m_startCol.value());
    }
References col(), and row().
cols()
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::cols () const inline
{ return m_blockCols.value(); }
const_cast_derived()
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::const_cast_derived () const inline inherited
    { return *static_cast<Derived*>(const_cast<SparseMatrixBase*>(this)); }
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
convert_index()
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> static StorageIndex Eigen::SparseMatrixBase< Derived >::convert_index (const Index idx) inline static private
{
      return internal::convert_index<StorageIndex>(idx);
    }
cwiseProduct() [1/2]
EIGEN_STRONG_INLINE const SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::template CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
{
  return typename CwiseProductDenseReturnType<OtherDerived>::Type(derived(), other.derived());
}
cwiseProduct() [2/2]
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
derived() [1/2]
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::derived () inline inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
const Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::derived () const inline inherited
{ return *static_cast<const Derived*>(this); }
dot() [1/4]
internal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::dot (const MatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  eigen_assert(other.size()>0 && "you are using a non initialized vector");
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  Scalar res(0);
  while (i)
  {
    res += numext::conj(i.value()) * other.coeff(i.index());
    ++i;
  }
  return res;
}
dot() [2/4]
Scalar Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::dot (const MatrixBase< OtherDerived > & other) const inherited
dot() [3/4]
internal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  internal::evaluator<OtherDerived>  otherEval(other.derived());
  typename internal::evaluator<OtherDerived>::InnerIterator j(otherEval, 0);
  Scalar res(0);
  while (i && j)
  {
    if (i.index()==j.index())
    {
      res += numext::conj(i.value()) * j.value();
      ++i; ++j;
    }
    else if (i.index()<j.index())
      ++i;
    else
      ++j;
  }
  return res;
}
dot() [4/4]
Scalar Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
eval()
const internal::eval< Block< XprType, BlockRows, BlockCols, InnerPanel > >::type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
    { return typename internal::eval<Derived>::type(derived()); }
evalTo()
void Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::evalTo (Dest &) const private inherited
innerSize()
Index Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::innerSize () const inline inherited
Returns
the size of the inner dimension according to the storage order, i.e., the number of rows for a columns major matrix, and the number of cols otherwise
{ return (int(Flags)&RowMajorBit) ? this->cols() : this->rows(); }
innerVector() [1/2]
SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::InnerVectorReturnType Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::innerVector (Index outer) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{ return InnerVectorReturnType(derived(), outer); }
innerVector() [2/2]
const SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::ConstInnerVectorReturnType Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::innerVector (Index outer) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{ return ConstInnerVectorReturnType(derived(), outer); }
innerVectors() [1/2]
SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::InnerVectorsReturnType Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::innerVectors (Index outerStart, Index outerSize) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{
  return Block<Derived,Dynamic,Dynamic,true>(derived(),
                                             IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                             IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
innerVectors() [2/2]
const SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::ConstInnerVectorsReturnType Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::innerVectors (Index outerStart, Index outerSize) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{
  return Block<const Derived,Dynamic,Dynamic,true>(derived(),
                                                  IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                                  IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
isApprox() [1/2]
bool Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::isApprox (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inline inherited
    { return toDense().isApprox(other,prec); }
isApprox() [2/2]
bool Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::isApprox (const SparseMatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
{
  const typename internal::nested_eval<Derived,2,PlainObject>::type actualA(derived());
  typename internal::conditional<bool(IsRowMajor)==bool(OtherDerived::IsRowMajor),
    const typename internal::nested_eval<OtherDerived,2,PlainObject>::type,
    const PlainObject>::type actualB(other.derived());
  return (actualA - actualB).squaredNorm() <= prec * prec * numext::mini(actualA.squaredNorm(), actualB.squaredNorm());
}
isRValue()
bool Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::isRValue () const inline inherited
{ return m_isRValue; }
isVector()
bool Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::isVector () const inline inherited
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See also
rows(), cols(), IsVectorAtCompileTime.
{ return rows()==1 || cols()==1; }
markAsRValue()
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::markAsRValue () inline inherited
{ m_isRValue = true; return derived(); }
nestedExpression() [1/2]
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> XprType & Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::nestedExpression () inline
{ return m_matrix; }
nestedExpression() [2/2]
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> const XprType & Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::nestedExpression () const inline
{ return m_matrix; }
nonZeros()
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::nonZeros () const inline protected
{ return Dynamic; }
References Eigen::Dynamic.
norm()
NumTraits< typenameinternal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar >::Real Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::norm inline inherited
{
  using std::sqrt;
  return sqrt(squaredNorm());
}
operator*() [1/3]
const Product< Block< XprType, BlockRows, BlockCols, InnerPanel > , OtherDerived > Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator* (const DiagonalBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
operator*() [2/3]
const Product< Block< XprType, BlockRows, BlockCols, InnerPanel > , OtherDerived > Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator* (const MatrixBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
operator*() [3/3]
const Product< Block< XprType, BlockRows, BlockCols, InnerPanel > , OtherDerived, AliasFreeProduct > Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator* (const SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the product of two sparse matrices. By default a conservative product preserving the symbolic non zeros is performed. The automatic pruning of the small values can be achieved by calling the pruned() function in which case a totally different product algorithm is employed:
C = (A*B).pruned();             // supress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return Product<Derived,OtherDerived,AliasFreeProduct>(derived(), other.derived());
}
operator*=() [1/2]
EIGEN_STRONG_INLINE Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator*= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() *= other;
  return derived();
}
operator*=() [2/2]
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator*= (const SparseMatrixBase< OtherDerived > & other) inherited
operator+=() [1/4]
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator+= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [2/4]
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator+= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [3/4]
EIGEN_STRONG_INLINE Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() + other.derived();
}
operator+=() [4/4]
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
operator-=() [1/4]
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator-= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::sub_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [2/4]
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator-= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [3/4]
EIGEN_STRONG_INLINE Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() - other.derived();
}
operator-=() [4/4]
Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
operator/=()
EIGEN_STRONG_INLINE Block< XprType, BlockRows, BlockCols, InnerPanel > & Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::operator/= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() /= other;
  return derived();
}
operator=()
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> template<typename T > BlockImpl & Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::operator= (const T &) inline protected
    {
      EIGEN_STATIC_ASSERT(sizeof(T)==0, THIS_SPARSE_BLOCK_SUBEXPRESSION_IS_READ_ONLY);
      return *this;
    }
References EIGEN_STATIC_ASSERT.
outerSize()
Index Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::outerSize () const inline inherited
Returns
the size of the storage major dimension, i.e., the number of columns for a columns major matrix, and the number of rows otherwise
{ return (int(Flags)&RowMajorBit) ? this->rows() : this->cols(); }
pruned()
const SparseView< Block< XprType, BlockRows, BlockCols, InnerPanel > > Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::pruned (const Scalar & reference = Scalar(0), const RealScalar & epsilon = NumTraits<Scalar>::dummy_precision()) const inline inherited
Returns
an expression of *this with values smaller than reference * epsilon removed.
This method is typically used in conjunction with the product of two sparse matrices to automatically prune the smallest values as follows:
C = (A*B).pruned();             // suppress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return SparseView<Derived>(derived(), reference, epsilon);
}
rows()
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::rows () const inline
{ return m_blockRows.value(); }
selfadjointView() [1/4]
SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::selfadjointView () inline inherited
selfadjointView() [2/4]
SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::template SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::selfadjointView () inherited
{
  return SparseSelfAdjointView<Derived, UpLo>(derived());
}
selfadjointView() [3/4]
ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::selfadjointView () const inline inherited
selfadjointView() [4/4]
SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::template ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::selfadjointView () const inherited
{
  return SparseSelfAdjointView<const Derived, UpLo>(derived());
}
size()
Index Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols().
{ return rows() * cols(); }
squaredNorm()
NumTraits< typenameinternal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar >::Real Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::squaredNorm inline inherited
{
  return numext::real((*this).cwiseAbs2().sum());
}
startCol()
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::startCol () const inline
{ return m_startCol.value(); }
startRow()
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> Index Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::startRow () const inline
{ return m_startRow.value(); }
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
sum()
internal::traits< Block< XprType, BlockRows, BlockCols, InnerPanel > >::Scalar Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::sum inherited
{
  eigen_assert(rows()>0 && cols()>0 && "you are using a non initialized matrix");
  Scalar res(0);
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (typename internal::evaluator<Derived>::InnerIterator iter(thisEval,j); iter; ++iter)
      res += iter.value();
  return res;
}
toDense()
DenseMatrixType Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::toDense () const inline inherited
    {
      return DenseMatrixType(derived());
    }
transpose() [1/2]
TransposeReturnType Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::transpose () inline inherited
{ return TransposeReturnType(derived()); }
transpose() [2/2]
const ConstTransposeReturnType Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::transpose () const inline inherited
{ return ConstTransposeReturnType(derived()); }
triangularView()
const TriangularView< const Block< XprType, BlockRows, BlockCols, InnerPanel > , Mode > Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::triangularView inline inherited
{
  return TriangularView<const Derived, Mode>(derived());
}
twistedBy()
SparseSymmetricPermutationProduct< Block< XprType, BlockRows, BlockCols, InnerPanel > , Upper|Lower > Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline inherited
Returns
an expression of P H P^-1 where H is the matrix represented by *this
    {
      return SparseSymmetricPermutationProduct<Derived,Upper|Lower>(derived(), perm);
    }
Friends And Related Symbol Documentation
internal::unary_evaluator< Block< XprType, BlockRows, BlockCols, InnerPanel >, internal::IteratorBased, Scalar >
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> friend struct internal::unary_evaluator< Block< XprType, BlockRows, BlockCols, InnerPanel >, internal::IteratorBased, Scalar > friend
Member Data Documentation
m_blockCols
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> const internal::variable_if_dynamic<Index, ColsAtCompileTime> Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::m_blockCols protected
m_blockRows
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> const internal::variable_if_dynamic<Index, RowsAtCompileTime> Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::m_blockRows protected
m_isRValue
bool Eigen::SparseMatrixBase< Block< XprType, BlockRows, BlockCols, InnerPanel > >::m_isRValue protected inherited
m_matrix
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> internal::ref_selector<XprType>::non_const_type Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::m_matrix protected
m_startCol
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> const internal::variable_if_dynamic<Index, XprType::ColsAtCompileTime == 1 ? 0 : Dynamic> Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::m_startCol protected
m_startRow
template<typename XprType , int BlockRows, int BlockCols, bool InnerPanel> const internal::variable_if_dynamic<Index, XprType::RowsAtCompileTime == 1 ? 0 : Dynamic> Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::m_startRow protected
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseBlock.h