Prusa Slicer: Eigen::NumTraits< Eigen::half > Struct Reference
Eigen::NumTraits< Eigen::half > Struct Reference
#include <src/eigen/Eigen/src/Core/arch/CUDA/Half.h>
Public Types
enum { IsSigned = true , IsInteger = false , IsComplex = false , RequireInitialization = false }
enum
typedef Eigen::half Real
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half epsilon ()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half dummy_precision ()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half highest ()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half lowest ()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half infinity ()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half quiet_NaN ()
Detailed Description
Member Typedef Documentation
Real
typedef Eigen::half Eigen::GenericNumTraits< Eigen::half >::Real inherited
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    IsInteger = std::numeric_limits<T>::is_integer,
    IsSigned = std::numeric_limits<T>::is_signed,
    IsComplex = 0,
    RequireInitialization = internal::is_arithmetic<T>::value ? 0 : 1,
    ReadCost = 1,
    AddCost = 1,
    MulCost = 1
  };
anonymous enum
anonymous enum
Enumerator
IsSigned
IsInteger
IsComplex
RequireInitialization
       {
    IsSigned = true,
    IsInteger = false,
    IsComplex = false,
    RequireInitialization = false
  };
Member Function Documentation
dummy_precision()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::dummy_precision () inline static
{ return Eigen::half(1e-2f); }
epsilon()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::epsilon () inline static
{
    return half_impl::raw_uint16_to_half(0x0800);
  }
References Eigen::half_impl::raw_uint16_to_half().
highest()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::highest () inline static
{
    return half_impl::raw_uint16_to_half(0x7bff);
  }
References Eigen::half_impl::raw_uint16_to_half().
infinity()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::infinity () inline static
{
    return half_impl::raw_uint16_to_half(0x7c00);
  }
References Eigen::half_impl::raw_uint16_to_half().
lowest()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::lowest () inline static
{
    return half_impl::raw_uint16_to_half(0xfbff);
  }
References Eigen::half_impl::raw_uint16_to_half().
quiet_NaN()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::half Eigen::NumTraits< Eigen::half >::quiet_NaN () inline static
{
    return half_impl::raw_uint16_to_half(0x7c01);
  }
References Eigen::half_impl::raw_uint16_to_half().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/arch/CUDA/Half.h