Prusa Slicer: Slic3r::InfillPolylineClipper Class Reference
Slic3r::InfillPolylineClipper Class Reference
Public Member Functions
InfillPolylineClipper (const BoundingBox bbox, const double scale_out)
void add_point (const Vec2d &pt)
Points && result ()
bool clips () const override
void reserve (size_t n)
Protected Member Functions
const Point scaled (const Vec2d &fpt) const
Protected Attributes
Points m_out
Private Types
enum class Side { Left = 1 , Right = 2 , Top = 4 , Bottom = 8 }
Private Member Functions
int sides (const Point &p) const
Private Attributes
BoundingBox m_bbox
int m_sides_prev
int m_sides_this
double m_scale_out
Detailed Description
Member Enumeration Documentation
Side
enum class Slic3r::InfillPolylineClipper::Side strong private
Enumerator
Left
Right
Top
Bottom
                    {
        Left   = 1,
        Right  = 2,
        Top    = 4,
        Bottom = 8
    };
Constructor & Destructor Documentation
InfillPolylineClipper()
Slic3r::InfillPolylineClipper::InfillPolylineClipper (const BoundingBox bbox, const double scale_out) inline
: FillPlanePath::InfillPolylineOutput(scale_out), m_bbox(bbox) {}
Member Function Documentation
add_point()
void Slic3r::InfillPolylineClipper::add_point (const Vec2d & pt)
{
    const Point pt{ this->scaled(fpt) };
    if (m_out.size() < 2) {
        // Collect the two first points and their status.
        (m_out.empty() ? m_sides_prev : m_sides_this) = sides(pt);
        m_out.emplace_back(pt);
    } else {
        // Classify the last inserted point, possibly remove it.
        int sides_next = sides(pt);
        if (// This point is inside. Take it.
            m_sides_this == 0 ||
            // Either this point is outside and previous or next is inside, or
            // the edge possibly cuts corner of the bounding box.
            (m_sides_prev & m_sides_this & sides_next) == 0) {
            // Keep the last point.
            m_sides_prev = m_sides_this;
        } else {
            // All the three points (this, prev, next) are outside at the same side.
            // Ignore the last point.
            m_out.pop_back();
        }
        // And save the current point.
        m_out.emplace_back(pt);
        m_sides_this = sides_next;
    }
}
References Slic3r::FillPlanePath::InfillPolylineOutput::m_out, m_sides_prev, m_sides_this, Slic3r::FillPlanePath::InfillPolylineOutput::scaled(), and sides().
clips()
bool Slic3r::InfillPolylineClipper::clips () const inline override virtual
Reimplemented from Slic3r::FillPlanePath::InfillPolylineOutput.
{ return true; }
reserve()
void Slic3r::FillPlanePath::InfillPolylineOutput::reserve (size_t n) inline inherited
{ m_out.reserve(n); }
References Slic3r::FillPlanePath::InfillPolylineOutput::m_out.
result()
Points && Slic3r::InfillPolylineClipper::result () inline
{ return std::move(m_out); }
References Slic3r::FillPlanePath::InfillPolylineOutput::m_out.
Referenced by Slic3r::FillPlanePath::_fill_surface_single().
scaled()
const Point Slic3r::FillPlanePath::InfillPolylineOutput::scaled (const Vec2d & fpt) const inline protected inherited
{ return { coord_t(floor(fpt.x() * m_scale_out + 0.5)), coord_t(floor(fpt.y() * m_scale_out + 0.5)) }; }
References floor(), and Slic3r::FillPlanePath::InfillPolylineOutput::m_scale_out.
Referenced by add_point(), and Slic3r::FillPlanePath::InfillPolylineOutput::add_point().
sides()
int Slic3r::InfillPolylineClipper::sides (const Point & p) const inline private
{
        return int(p.x() < m_bbox.min.x()) * int(Side::Left) +
               int(p.x() > m_bbox.max.x()) * int(Side::Right) +
               int(p.y() < m_bbox.min.y()) * int(Side::Bottom) +
               int(p.y() > m_bbox.max.y()) * int(Side::Top);
    };
References Bottom, Left, m_bbox, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Right, and Top.
Referenced by add_point().
Member Data Documentation
m_bbox
BoundingBox Slic3r::InfillPolylineClipper::m_bbox private
Referenced by sides().
m_out
Points Slic3r::FillPlanePath::InfillPolylineOutput::m_out protected inherited
Referenced by add_point(), Slic3r::FillPlanePath::InfillPolylineOutput::add_point(), Slic3r::FillPlanePath::InfillPolylineOutput::reserve(), result(), and Slic3r::FillPlanePath::InfillPolylineOutput::result().
m_scale_out
double Slic3r::FillPlanePath::InfillPolylineOutput::m_scale_out private inherited
Referenced by Slic3r::FillPlanePath::InfillPolylineOutput::scaled().
m_sides_prev
int Slic3r::InfillPolylineClipper::m_sides_prev private
Referenced by add_point().
m_sides_this
int Slic3r::InfillPolylineClipper::m_sides_this private
Referenced by add_point().
The documentation for this class was generated from the following file:
src/libslic3r/Fill/FillPlanePath.cpp