Prusa Slicer: Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false > Struct Template Reference
Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false > Struct Template Reference
#include <src/eigen/Eigen/src/Core/MathFunctions.h>
Public Types
typedef NumTraits< Scalar >::Real RealScalar
Static Public Member Functions
template<typename OtherScalar >
static EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const Scalar &x, const OtherScalar &y, const RealScalar &prec)
static EIGEN_DEVICE_FUNC bool isApprox (const Scalar &x, const Scalar &y, const RealScalar &prec)
static EIGEN_DEVICE_FUNC bool isApproxOrLessThan (const Scalar &x, const Scalar &y, const RealScalar &prec)
Detailed Description
template<typename Scalar>
struct Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >
Member Typedef Documentation
RealScalar
template<typename Scalar > typedef NumTraits<Scalar>::Real Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >::RealScalar
Member Function Documentation
isApprox()
template<typename Scalar > static EIGEN_DEVICE_FUNC bool Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >::isApprox (const Scalar & x, const Scalar & y, const RealScalar & prec) inline static
  {
    return numext::abs(x - y) <= numext::mini(numext::abs(x), numext::abs(y)) * prec;
  }
References Eigen::numext::abs(), Eigen::numext::mini(), and Eigen::internal::y.
isApproxOrLessThan()
template<typename Scalar > static EIGEN_DEVICE_FUNC bool Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >::isApproxOrLessThan (const Scalar & x, const Scalar & y, const RealScalar & prec) inline static
  {
    return x <= y || isApprox(x, y, prec);
  }
References Eigen::internal::isApprox(), and Eigen::internal::y.
isMuchSmallerThan()
template<typename Scalar > template<typename OtherScalar > static EIGEN_DEVICE_FUNC bool Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >::isMuchSmallerThan (const Scalar & x, const OtherScalar & y, const RealScalar & prec) inline static
  {
    return numext::abs(x) <= numext::abs(y) * prec;
  }
References Eigen::numext::abs(), and Eigen::internal::y.
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/MathFunctions.h