Prusa Slicer: Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double > Struct Template Reference
Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double > Struct Template Reference
#include <src/eigen/Eigen/src/Geometry/arch/Geometry_SSE.h>
Public Types
enum { BAlignment = traits<OtherDerived>::Alignment , ResAlignment = traits<Quaternion<double> >::Alignment }
Static Public Member Functions
static Quaternion< double > run (const QuaternionBase< Derived > &_a, const QuaternionBase< OtherDerived > &_b)
Detailed Description
template<class Derived, class OtherDerived>
struct Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >
Member Enumeration Documentation
anonymous enum
template<class Derived , class OtherDerived > anonymous enum
Enumerator
BAlignment
ResAlignment
       {
    BAlignment = traits<OtherDerived>::Alignment,
    ResAlignment = traits<Quaternion<double> >::Alignment
  };
Member Function Documentation
run()
template<class Derived , class OtherDerived > static Quaternion< double > Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double >::run (const QuaternionBase< Derived > & _a, const QuaternionBase< OtherDerived > & _b) inline static
  {
  const Packet2d mask = _mm_castsi128_pd(_mm_set_epi32(0x0,0x0,0x80000000,0x0));
  Quaternion<double> res;
  const double* a = _a.coeffs().data();
  Packet2d b_xy = _b.coeffs().template packet<BAlignment>(0);
  Packet2d b_zw = _b.coeffs().template packet<BAlignment>(2);
  Packet2d a_xx = pset1<Packet2d>(a[0]);
  Packet2d a_yy = pset1<Packet2d>(a[1]);
  Packet2d a_zz = pset1<Packet2d>(a[2]);
  Packet2d a_ww = pset1<Packet2d>(a[3]);
  // two temporaries:
  Packet2d t1, t2;
  /*
   * t1 = ww*xy + yy*zw
   * t2 = zz*xy - xx*zw
   * res.xy = t1 +/- swap(t2)
   */
  t1 = padd(pmul(a_ww, b_xy), pmul(a_yy, b_zw));
  t2 = psub(pmul(a_zz, b_xy), pmul(a_xx, b_zw));
#ifdef EIGEN_VECTORIZE_SSE3
  EIGEN_UNUSED_VARIABLE(mask)
  pstoret<double,Packet2d,ResAlignment>(&res.x(), _mm_addsub_pd(t1, preverse(t2)));
#else
  pstoret<double,Packet2d,ResAlignment>(&res.x(), padd(t1, pxor(mask,preverse(t2))));
#endif
  /*
   * t1 = ww*zw - yy*xy
   * t2 = zz*zw + xx*xy
   * res.zw = t1 -/+ swap(t2) = swap( swap(t1) +/- t2)
   */
  t1 = psub(pmul(a_ww, b_zw), pmul(a_yy, b_xy));
  t2 = padd(pmul(a_zz, b_zw), pmul(a_xx, b_xy));
#ifdef EIGEN_VECTORIZE_SSE3
  EIGEN_UNUSED_VARIABLE(mask)
  pstoret<double,Packet2d,ResAlignment>(&res.z(), preverse(_mm_addsub_pd(preverse(t1), t2)));
#else
  pstoret<double,Packet2d,ResAlignment>(&res.z(), psub(t1, pxor(mask,preverse(t2))));
#endif
  return res;
}
References Eigen::QuaternionBase< Derived >::coeffs(), EIGEN_UNUSED_VARIABLE, Eigen::internal::padd(), Eigen::internal::pmul(), Eigen::internal::preverse(), Eigen::internal::pset1< Packet2d >(), Eigen::internal::psub(), Eigen::internal::pxor(), Eigen::QuaternionBase< Derived >::x(), and Eigen::QuaternionBase< Derived >::z().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Geometry/arch/Geometry_SSE.h