Prusa Slicer: igl::geodesic::Face Class Reference
igl::geodesic::Face Class Reference
Public Types
typedef SimpleVector< vertex_pointer > vertex_pointer_vector
typedef SimpleVector< edge_pointer > edge_pointer_vector
typedef SimpleVector< face_pointer > face_pointer_vector
Public Member Functions
Face ()
~Face ()
edge_pointer opposite_edge (vertex_pointer v)
vertex_pointer opposite_vertex (edge_pointer e)
edge_pointer next_edge (edge_pointer e, vertex_pointer v)
double vertex_angle (vertex_pointer v)
double * corner_angles ()
vertex_pointer_vector & adjacent_vertices ()
edge_pointer_vector & adjacent_edges ()
face_pointer_vector & adjacent_faces ()
unsigned & id ()
PointType type ()
Protected Attributes
vertex_pointer_vector m_adjacent_vertices
edge_pointer_vector m_adjacent_edges
face_pointer_vector m_adjacent_faces
unsigned m_id
PointType m_type
Private Attributes
double m_corner_angles [3]
Detailed Description
Member Typedef Documentation
edge_pointer_vector
typedef SimpleVector<edge_pointer> igl::geodesic::MeshElementBase::edge_pointer_vector inherited
face_pointer_vector
typedef SimpleVector<face_pointer> igl::geodesic::MeshElementBase::face_pointer_vector inherited
vertex_pointer_vector
typedef SimpleVector<vertex_pointer> igl::geodesic::MeshElementBase::vertex_pointer_vector inherited
Constructor & Destructor Documentation
Face()
igl::geodesic::Face::Face () inline
  {
    m_type = FACE;
  };
References igl::geodesic::FACE, and igl::geodesic::MeshElementBase::m_type.
~Face()
igl::geodesic::Face::~Face () inline
{};
Member Function Documentation
adjacent_edges()
edge_pointer_vector & igl::geodesic::MeshElementBase::adjacent_edges () inline inherited
{return m_adjacent_edges;};
References igl::geodesic::MeshElementBase::m_adjacent_edges.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::GeodesicAlgorithmExact::list_edges_visible_from_source(), next_edge(), opposite_edge(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), igl::geodesic::Mesh::verify(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
adjacent_faces()
face_pointer_vector & igl::geodesic::MeshElementBase::adjacent_faces () inline inherited
{return m_adjacent_faces;};
References igl::geodesic::MeshElementBase::m_adjacent_faces.
Referenced by igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::GeodesicAlgorithmExact::construct_propagated_intervals(), igl::geodesic::Edge::is_boundary(), igl::geodesic::Edge::opposite_face(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), and igl::geodesic::GeodesicAlgorithmExact::propagate().
adjacent_vertices()
vertex_pointer_vector & igl::geodesic::MeshElementBase::adjacent_vertices () inline inherited
{return m_adjacent_vertices;};
References igl::geodesic::MeshElementBase::m_adjacent_vertices.
Referenced by igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::Edge::belongs(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::Mesh::initialize_mesh_data(), opposite_vertex(), igl::geodesic::Edge::opposite_vertex(), igl::geodesic::Edge::v0(), igl::geodesic::Edge::v1(), igl::geodesic::Mesh::verify(), and vertex_angle().
corner_angles()
double * igl::geodesic::Face::corner_angles () inline
{return m_corner_angles;};
References m_corner_angles.
Referenced by igl::geodesic::Mesh::build_adjacencies(), and igl::geodesic::Mesh::verify().
id()
unsigned & igl::geodesic::MeshElementBase::id () inline inherited
{return m_id;};
References igl::geodesic::MeshElementBase::m_id.
Referenced by igl::geodesic::Edge::belongs(), igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::GeodesicAlgorithmExact::construct_propagated_intervals(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Interval::initialize(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::GeodesicAlgorithmExact::intersect_intervals(), igl::geodesic::GeodesicAlgorithmExact::interval_list(), next_edge(), igl::geodesic::Edge::opposite_face(), igl::geodesic::Edge::opposite_vertex(), igl::geodesic::GeodesicAlgorithmExact::propagate(), igl::geodesic::Mesh::verify(), vertex_angle(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
next_edge()
edge_pointer igl::geodesic::Face::next_edge (edge_pointer e, vertex_pointer v) inline
{
  assert(e->belongs(v));
  for(unsigned i=0; i<3; ++i)
  {
    edge_pointer next = adjacent_edges()[i];
    if(e->id() != next->id() && next->belongs(v))
    {
      return next;
    }
  }
  assert(0);
  return NULL;
}
References igl::geodesic::MeshElementBase::adjacent_edges(), igl::geodesic::Edge::belongs(), and igl::geodesic::MeshElementBase::id().
Referenced by igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), and igl::geodesic::GeodesicAlgorithmExact::propagate().
opposite_edge()
edge_pointer igl::geodesic::Face::opposite_edge (vertex_pointer v) inline
{
  for(unsigned i=0; i<3; ++i)
  {
    edge_pointer e = adjacent_edges()[i];
    if(!e->belongs(v))
    {
      return e;
    }
  }
  assert(0);
  return NULL;
}
References igl::geodesic::MeshElementBase::adjacent_edges(), and igl::geodesic::Edge::belongs().
Referenced by igl::geodesic::Mesh::build_adjacencies(), and igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges().
opposite_vertex()
vertex_pointer igl::geodesic::Face::opposite_vertex (edge_pointer e) inline
{
  for(unsigned i=0; i<3; ++i)
  {
    vertex_pointer v = adjacent_vertices()[i];
    if(!e->belongs(v))
    {
      return v;
    }
  }
  assert(0);
  return NULL;
}
References igl::geodesic::MeshElementBase::adjacent_vertices(), and igl::geodesic::Edge::belongs().
Referenced by igl::geodesic::Mesh::closest_vertices().
type()
PointType igl::geodesic::MeshElementBase::type () inline inherited
{return m_type;};
References igl::geodesic::MeshElementBase::m_type.
Referenced by igl::geodesic::Interval::initialize(), igl::geodesic::GeodesicAlgorithmExact::list_edges_visible_from_source(), and igl::geodesic::SurfacePoint::type().
vertex_angle()
double igl::geodesic::Face::vertex_angle (vertex_pointer v) inline
  {
    for(unsigned i=0; i<3; ++i)
    {
      if(adjacent_vertices()[i]->id() == v->id())
      {
        return m_corner_angles[i];
      }
    }
    assert(0);
    return 0;
  }
References igl::geodesic::MeshElementBase::adjacent_vertices(), igl::geodesic::MeshElementBase::id(), and m_corner_angles.
Referenced by igl::geodesic::GeodesicAlgorithmExact::propagate().
Member Data Documentation
m_adjacent_edges
edge_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_edges protected inherited
Referenced by igl::geodesic::MeshElementBase::adjacent_edges().
m_adjacent_faces
face_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_faces protected inherited
Referenced by igl::geodesic::MeshElementBase::adjacent_faces().
m_adjacent_vertices
vertex_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_vertices protected inherited
Referenced by igl::geodesic::MeshElementBase::adjacent_vertices().
m_corner_angles
double igl::geodesic::Face::m_corner_angles[3] private
Referenced by corner_angles(), and vertex_angle().
m_id
unsigned igl::geodesic::MeshElementBase::m_id protected inherited
Referenced by igl::geodesic::MeshElementBase::id().
m_type
PointType igl::geodesic::MeshElementBase::m_type protected inherited
Referenced by igl::geodesic::Edge::Edge(), Face(), igl::geodesic::Vertex::Vertex(), and igl::geodesic::MeshElementBase::type().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp