Prusa Slicer: src/avrdude/windows/getopt.c File Reference
getopt.c File Reference
#include <stdio.h>
#include "getopt.h"
#include <strings.h>
Macros
#define _NO_PROTO
#define const
#define GETOPT_INTERFACE_VERSION 2
#define _(msgid) (msgid)
#define SWAP_FLAGS(ch1, ch2)
#define NONOPTION_P (argv[optind][0] != '-' || argv[optind][1] == '\0')
Enumerations
enum { REQUIRE_ORDER , PERMUTE , RETURN_IN_ORDER }
Functions
char * getenv ()
static char * my_index (char *str, int chr) const
static void exchange (char **argv)
static const char * _getopt_initialize (int argc, char *const *argv, const char *optstring)
int _getopt_internal (int argc, char *const *argv, const char *optstring, const struct option *longopts, int *longind, int long_only)
int getopt (int argc, char *const *argv, const char *optstring)
Variables
char * optarg
int optind = 1
int __getopt_initialized
static char * nextchar
int opterr = 1
int optopt = '?'
static enum { ... } ordering
static char * posixly_correct
static int first_nonopt
static int last_nonopt
Macro Definition Documentation
_
#define _ (msgid) (msgid)
_NO_PROTO
#define _NO_PROTO
const
#define const
GETOPT_INTERFACE_VERSION
#define GETOPT_INTERFACE_VERSION 2
NONOPTION_P
#define NONOPTION_P (argv[optind][0] != '-' || argv[optind][1] == '\0')
SWAP_FLAGS
#define SWAP_FLAGS (ch1, ch2)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
REQUIRE_ORDER
PERMUTE
RETURN_IN_ORDER
{
  REQUIRE_ORDER, PERMUTE, RETURN_IN_ORDER
} ordering;
Function Documentation
_getopt_initialize()
static const char * _getopt_initialize (int argc, char *const * argv, const char * optstring) static
{
  /* Start processing options with ARGV-element 1 (since ARGV-element 0
     is the program name); the sequence of previously skipped
     non-option ARGV-elements is empty.  */
  first_nonopt = last_nonopt = optind;
  nextchar = NULL;
  posixly_correct = getenv ("POSIXLY_CORRECT");
  /* Determine how to handle the ordering of options and nonoptions.  */
  if (optstring[0] == '-')
    {
      ordering = RETURN_IN_ORDER;
      ++optstring;
    }
  else if (optstring[0] == '+')
    {
      ordering = REQUIRE_ORDER;
      ++optstring;
    }
  else if (posixly_correct != NULL)
    ordering = REQUIRE_ORDER;
  else
    ordering = PERMUTE;
#if defined _LIBC && defined USE_NONOPTION_FLAGS
  if (posixly_correct == NULL
      && argc == __libc_argc && argv == __libc_argv)
    {
      if (nonoption_flags_max_len == 0)
        {
          if (__getopt_nonoption_flags == NULL
              || __getopt_nonoption_flags[0] == '\0')
            nonoption_flags_max_len = -1;
          else
            {
              const char *orig_str = __getopt_nonoption_flags;
              int len = nonoption_flags_max_len = strlen (orig_str);
              if (nonoption_flags_max_len < argc)
                nonoption_flags_max_len = argc;
              __getopt_nonoption_flags =
                (char *) malloc (nonoption_flags_max_len);
              if (__getopt_nonoption_flags == NULL)
                nonoption_flags_max_len = -1;
              else
                memset (__mempcpy (__getopt_nonoption_flags, orig_str, len),
                        '\0', nonoption_flags_max_len - len);
            }
        }
      nonoption_flags_len = nonoption_flags_max_len;
    }
  else
    nonoption_flags_len = 0;
#endif
  return optstring;
}
References first_nonopt, getenv(), last_nonopt, malloc(), nextchar, optind, ordering, PERMUTE, posixly_correct, REQUIRE_ORDER, and RETURN_IN_ORDER.
Referenced by _getopt_internal().
_getopt_internal()
int _getopt_internal (int argc, char *const * argv, const char * optstring, const struct option * longopts, int * longind, int long_only)
{
  int print_errors = opterr;
  if (optstring[0] == ':')
    print_errors = 0;
  if (argc < 1)
    return -1;
  optarg = NULL;
  if (optind == 0 || !__getopt_initialized)
    {
      if (optind == 0)
        optind = 1;     /* Don't scan ARGV[0], the program name.  */
      optstring = _getopt_initialize (argc, argv, optstring);
      __getopt_initialized = 1;
    }
  /* Test whether ARGV[optind] points to a non-option argument.
     Either it does not have option syntax, or there is an environment flag
     from the shell indicating it is not an option.  The later information
     is only used when the used in the GNU libc.  */
#if defined _LIBC && defined USE_NONOPTION_FLAGS
# define NONOPTION_P (argv[optind][0] != '-' || argv[optind][1] == '\0'       \
                      || (optind < nonoption_flags_len                        \
                          && __getopt_nonoption_flags[optind] == '1'))
#else
# define NONOPTION_P (argv[optind][0] != '-' || argv[optind][1] == '\0')
#endif
  if (nextchar == NULL || *nextchar == '\0')
    {
      /* Advance to the next ARGV-element.  */
      /* Give FIRST_NONOPT and LAST_NONOPT rational values if OPTIND has been
         moved back by the user (who may also have changed the arguments).  */
      if (last_nonopt > optind)
        last_nonopt = optind;
      if (first_nonopt > optind)
        first_nonopt = optind;
      if (ordering == PERMUTE)
        {
          /* If we have just processed some options following some non-options,
             exchange them so that the options come first.  */
          if (first_nonopt != last_nonopt && last_nonopt != optind)
            exchange ((char **) argv);
          else if (last_nonopt != optind)
            first_nonopt = optind;
          /* Skip any additional non-options
             and extend the range of non-options previously skipped.  */
          while (optind < argc && NONOPTION_P)
            optind++;
          last_nonopt = optind;
        }
      /* The special ARGV-element `--' means premature end of options.
         Skip it like a null option,
         then exchange with previous non-options as if it were an option,
         then skip everything else like a non-option.  */
      if (optind != argc && !strcmp (argv[optind], "--"))
        {
          optind++;
          if (first_nonopt != last_nonopt && last_nonopt != optind)
            exchange ((char **) argv);
          else if (first_nonopt == last_nonopt)
            first_nonopt = optind;
          last_nonopt = argc;
          optind = argc;
        }
      /* If we have done all the ARGV-elements, stop the scan
         and back over any non-options that we skipped and permuted.  */
      if (optind == argc)
        {
          /* Set the next-arg-index to point at the non-options
             that we previously skipped, so the caller will digest them.  */
          if (first_nonopt != last_nonopt)
            optind = first_nonopt;
          return -1;
        }
      /* If we have come to a non-option and did not permute it,
         either stop the scan or describe it to the caller and pass it by.  */
      if (NONOPTION_P)
        {
          if (ordering == REQUIRE_ORDER)
            return -1;
          optarg = argv[optind++];
          return 1;
        }
      /* We have found another option-ARGV-element.
         Skip the initial punctuation.  */
      nextchar = (argv[optind] + 1
                  + (longopts != NULL && argv[optind][1] == '-'));
    }
  /* Decode the current option-ARGV-element.  */
  /* Check whether the ARGV-element is a long option.
     If long_only and the ARGV-element has the form "-f", where f is
     a valid short option, don't consider it an abbreviated form of
     a long option that starts with f.  Otherwise there would be no
     way to give the -f short option.
     On the other hand, if there's a long option "fubar" and
     the ARGV-element is "-fu", do consider that an abbreviation of
     the long option, just like "--fu", and not "-f" with arg "u".
     This distinction seems to be the most useful approach.  */
  if (longopts != NULL
      && (argv[optind][1] == '-'
          || (long_only && (argv[optind][2] || !my_index (optstring, argv[optind][1])))))
    {
      char *nameend;
      const struct option *p;
      const struct option *pfound = NULL;
      int exact = 0;
      int ambig = 0;
      int indfound = -1;
      int option_index;
      for (nameend = nextchar; *nameend && *nameend != '='; nameend++)
        /* Do nothing.  */ ;
      /* Test all long options for either exact match
         or abbreviated matches.  */
      for (p = longopts, option_index = 0; p->name; p++, option_index++)
        if (!strncmp (p->name, nextchar, nameend - nextchar))
          {
            if ((unsigned int) (nameend - nextchar)
                == (unsigned int) strlen (p->name))
              {
                /* Exact match found.  */
                pfound = p;
                indfound = option_index;
                exact = 1;
                break;
              }
            else if (pfound == NULL)
              {
                /* First nonexact match found.  */
                pfound = p;
                indfound = option_index;
              }
            else if (long_only
                     || pfound->has_arg != p->has_arg
                     || pfound->flag != p->flag
                     || pfound->val != p->val)
              /* Second or later nonexact match found.  */
              ambig = 1;
          }
      if (ambig && !exact)
        {
          if (print_errors)
            {
#if defined _LIBC && defined USE_IN_LIBIO
              char *buf;
              __asprintf (&buf, _("%s: option `%s' is ambiguous\n"),
                          argv[0], argv[optind]);
              if (_IO_fwide (stderr, 0) > 0)
                __fwprintf (stderr, L"%s", buf);
              else
                fputs (buf, stderr);
              free (buf);
#else
              fprintf (stderr, _("%s: option `%s' is ambiguous\n"),
                       argv[0], argv[optind]);
#endif
            }
          nextchar += strlen (nextchar);
          optind++;
          optopt = 0;
          return '?';
        }
      if (pfound != NULL)
        {
          option_index = indfound;
          optind++;
          if (*nameend)
            {
              /* Don't test has_arg with >, because some C compilers don't
                 allow it to be used on enums.  */
              if (pfound->has_arg)
                optarg = nameend + 1;
              else
                {
                  if (print_errors)
                    {
#if defined _LIBC && defined USE_IN_LIBIO
                      char *buf;
#endif
                      if (argv[optind - 1][1] == '-')
{
                          /* --option */
#if defined _LIBC && defined USE_IN_LIBIO
                          __asprintf (&buf, _("\
%s: option `--%s' doesn't allow an argument\n"),
                                      argv[0], pfound->name);
#else
                          fprintf (stderr, _("\
%s: option `--%s' doesn't allow an argument\n"),
                                   argv[0], pfound->name);
#endif
                        }
                      else
{
                          /* +option or -option */
#if defined _LIBC && defined USE_IN_LIBIO
                          __asprintf (&buf, _("\
%s: option `%c%s' doesn't allow an argument\n"),
                                      argv[0], argv[optind - 1][0],
                                      pfound->name);
#else
                          fprintf (stderr, _("\
%s: option `%c%s' doesn't allow an argument\n"),
                                   argv[0], argv[optind - 1][0], pfound->name);
#endif
                        }
#if defined _LIBC && defined USE_IN_LIBIO
                      if (_IO_fwide (stderr, 0) > 0)
                        __fwprintf (stderr, L"%s", buf);
                      else
                        fputs (buf, stderr);
                      free (buf);
#endif
                    }
                  nextchar += strlen (nextchar);
                  optopt = pfound->val;
                  return '?';
                }
            }
          else if (pfound->has_arg == 1)
            {
              if (optind < argc)
                optarg = argv[optind++];
              else
                {
                  if (print_errors)
                    {
#if defined _LIBC && defined USE_IN_LIBIO
                      char *buf;
                      __asprintf (&buf,
                                  _("%s: option `%s' requires an argument\n"),
                                  argv[0], argv[optind - 1]);
                      if (_IO_fwide (stderr, 0) > 0)
                        __fwprintf (stderr, L"%s", buf);
                      else
                        fputs (buf, stderr);
                      free (buf);
#else
                      fprintf (stderr,
                               _("%s: option `%s' requires an argument\n"),
                               argv[0], argv[optind - 1]);
#endif
                    }
                  nextchar += strlen (nextchar);
                  optopt = pfound->val;
                  return optstring[0] == ':' ? ':' : '?';
                }
            }
          nextchar += strlen (nextchar);
          if (longind != NULL)
            *longind = option_index;
          if (pfound->flag)
            {
              *(pfound->flag) = pfound->val;
              return 0;
            }
          return pfound->val;
        }
      /* Can't find it as a long option.  If this is not getopt_long_only,
         or the option starts with '--' or is not a valid short
         option, then it's an error.
         Otherwise interpret it as a short option.  */
      if (!long_only || argv[optind][1] == '-'
          || my_index (optstring, *nextchar) == NULL)
        {
          if (print_errors)
            {
#if defined _LIBC && defined USE_IN_LIBIO
              char *buf;
#endif
              if (argv[optind][1] == '-')
                {
                  /* --option */
#if defined _LIBC && defined USE_IN_LIBIO
                  __asprintf (&buf, _("%s: unrecognized option `--%s'\n"),
                              argv[0], nextchar);
#else
                  fprintf (stderr, _("%s: unrecognized option `--%s'\n"),
                           argv[0], nextchar);
#endif
                }
              else
                {
                  /* +option or -option */
#if defined _LIBC && defined USE_IN_LIBIO
                  __asprintf (&buf, _("%s: unrecognized option `%c%s'\n"),
                              argv[0], argv[optind][0], nextchar);
#else
                  fprintf (stderr, _("%s: unrecognized option `%c%s'\n"),
                           argv[0], argv[optind][0], nextchar);
#endif
                }
#if defined _LIBC && defined USE_IN_LIBIO
              if (_IO_fwide (stderr, 0) > 0)
                __fwprintf (stderr, L"%s", buf);
              else
                fputs (buf, stderr);
              free (buf);
#endif
            }
          nextchar = (char *) "";
          optind++;
          optopt = 0;
          return '?';
        }
    }
  /* Look at and handle the next short option-character.  */
  {
    char c = *nextchar++;
    char *temp = my_index (optstring, c);
    /* Increment `optind' when we start to process its last character.  */
    if (*nextchar == '\0')
      ++optind;
    if (temp == NULL || c == ':')
      {
        if (print_errors)
          {
#if defined _LIBC && defined USE_IN_LIBIO
              char *buf;
#endif
            if (posixly_correct)
              {
                /* 1003.2 specifies the format of this message.  */
#if defined _LIBC && defined USE_IN_LIBIO
                __asprintf (&buf, _("%s: illegal option -- %c\n"),
                            argv[0], c);
#else
                fprintf (stderr, _("%s: illegal option -- %c\n"), argv[0], c);
#endif
              }
            else
              {
#if defined _LIBC && defined USE_IN_LIBIO
                __asprintf (&buf, _("%s: invalid option -- %c\n"),
                            argv[0], c);
#else
                fprintf (stderr, _("%s: invalid option -- %c\n"), argv[0], c);
#endif
              }
#if defined _LIBC && defined USE_IN_LIBIO
            if (_IO_fwide (stderr, 0) > 0)
              __fwprintf (stderr, L"%s", buf);
            else
              fputs (buf, stderr);
            free (buf);
#endif
          }
        optopt = c;
        return '?';
      }
    /* Convenience. Treat POSIX -W foo same as long option --foo */
    if (temp[0] == 'W' && temp[1] == ';')
      {
        char *nameend;
        const struct option *p;
        const struct option *pfound = NULL;
        int exact = 0;
        int ambig = 0;
        int indfound = 0;
        int option_index;
        /* This is an option that requires an argument.  */
        if (*nextchar != '\0')
          {
            optarg = nextchar;
            /* If we end this ARGV-element by taking the rest as an arg,
               we must advance to the next element now.  */
            optind++;
          }
        else if (optind == argc)
          {
            if (print_errors)
              {
                /* 1003.2 specifies the format of this message.  */
#if defined _LIBC && defined USE_IN_LIBIO
                char *buf;
                __asprintf (&buf, _("%s: option requires an argument -- %c\n"),
                            argv[0], c);
                if (_IO_fwide (stderr, 0) > 0)
                  __fwprintf (stderr, L"%s", buf);
                else
                  fputs (buf, stderr);
                free (buf);
#else
                fprintf (stderr, _("%s: option requires an argument -- %c\n"),
                         argv[0], c);
#endif
              }
            optopt = c;
            if (optstring[0] == ':')
              c = ':';
            else
              c = '?';
            return c;
          }
        else
          /* We already incremented `optind' once;
             increment it again when taking next ARGV-elt as argument.  */
          optarg = argv[optind++];
        /* optarg is now the argument, see if it's in the
           table of longopts.  */
        for (nextchar = nameend = optarg; *nameend && *nameend != '='; nameend++)
          /* Do nothing.  */ ;
        /* Test all long options for either exact match
           or abbreviated matches.  */
        for (p = longopts, option_index = 0; p->name; p++, option_index++)
          if (!strncmp (p->name, nextchar, nameend - nextchar))
            {
              if ((unsigned int) (nameend - nextchar) == strlen (p->name))
                {
                  /* Exact match found.  */
                  pfound = p;
                  indfound = option_index;
                  exact = 1;
                  break;
                }
              else if (pfound == NULL)
                {
                  /* First nonexact match found.  */
                  pfound = p;
                  indfound = option_index;
                }
              else
                /* Second or later nonexact match found.  */
                ambig = 1;
            }
        if (ambig && !exact)
          {
            if (print_errors)
              {
#if defined _LIBC && defined USE_IN_LIBIO
                char *buf;
                __asprintf (&buf, _("%s: option `-W %s' is ambiguous\n"),
                            argv[0], argv[optind]);
                if (_IO_fwide (stderr, 0) > 0)
                  __fwprintf (stderr, L"%s", buf);
                else
                  fputs (buf, stderr);
                free (buf);
#else
                fprintf (stderr, _("%s: option `-W %s' is ambiguous\n"),
                         argv[0], argv[optind]);
#endif
              }
            nextchar += strlen (nextchar);
            optind++;
            return '?';
          }
        if (pfound != NULL)
          {
            option_index = indfound;
            if (*nameend)
              {
                /* Don't test has_arg with >, because some C compilers don't
                   allow it to be used on enums.  */
                if (pfound->has_arg)
                  optarg = nameend + 1;
                else
                  {
                    if (print_errors)
                      {
#if defined _LIBC && defined USE_IN_LIBIO
                        char *buf;
                        __asprintf (&buf, _("\
%s: option `-W %s' doesn't allow an argument\n"),
                                    argv[0], pfound->name);
                        if (_IO_fwide (stderr, 0) > 0)
                          __fwprintf (stderr, L"%s", buf);
                        else
                          fputs (buf, stderr);
                        free (buf);
#else
                        fprintf (stderr, _("\
%s: option `-W %s' doesn't allow an argument\n"),
                                 argv[0], pfound->name);
#endif
                      }
                    nextchar += strlen (nextchar);
                    return '?';
                  }
              }
            else if (pfound->has_arg == 1)
              {
                if (optind < argc)
                  optarg = argv[optind++];
                else
                  {
                    if (print_errors)
                      {
#if defined _LIBC && defined USE_IN_LIBIO
                        char *buf;
                        __asprintf (&buf, _("\
%s: option `%s' requires an argument\n"),
                                    argv[0], argv[optind - 1]);
                        if (_IO_fwide (stderr, 0) > 0)
                          __fwprintf (stderr, L"%s", buf);
                        else
                          fputs (buf, stderr);
                        free (buf);
#else
                        fprintf (stderr,
                                 _("%s: option `%s' requires an argument\n"),
                                 argv[0], argv[optind - 1]);
#endif
                      }
                    nextchar += strlen (nextchar);
                    return optstring[0] == ':' ? ':' : '?';
                  }
              }
            nextchar += strlen (nextchar);
            if (longind != NULL)
              *longind = option_index;
            if (pfound->flag)
              {
                *(pfound->flag) = pfound->val;
                return 0;
              }
            return pfound->val;
          }
          nextchar = NULL;
          return 'W';   /* Let the application handle it.   */
      }
    if (temp[1] == ':')
      {
        if (temp[2] == ':')
          {
            /* This is an option that accepts an argument optionally.  */
            if (*nextchar != '\0')
              {
                optarg = nextchar;
                optind++;
              }
            else
              optarg = NULL;
            nextchar = NULL;
          }
        else
          {
            /* This is an option that requires an argument.  */
            if (*nextchar != '\0')
              {
                optarg = nextchar;
                /* If we end this ARGV-element by taking the rest as an arg,
                   we must advance to the next element now.  */
                optind++;
              }
            else if (optind == argc)
              {
                if (print_errors)
                  {
                    /* 1003.2 specifies the format of this message.  */
#if defined _LIBC && defined USE_IN_LIBIO
                    char *buf;
                    __asprintf (&buf,
                                _("%s: option requires an argument -- %c\n"),
                                argv[0], c);
                    if (_IO_fwide (stderr, 0) > 0)
                      __fwprintf (stderr, L"%s", buf);
                    else
                      fputs (buf, stderr);
                    free (buf);
#else
                    fprintf (stderr,
                             _("%s: option requires an argument -- %c\n"),
                             argv[0], c);
#endif
                  }
                optopt = c;
                if (optstring[0] == ':')
                  c = ':';
                else
                  c = '?';
              }
            else
              /* We already incremented `optind' once;
                 increment it again when taking next ARGV-elt as argument.  */
              optarg = argv[optind++];
            nextchar = NULL;
          }
      }
    return c;
  }
}
References _, __getopt_initialized, _getopt_initialize(), exchange(), first_nonopt, option::flag, free(), option::has_arg, L, last_nonopt, my_index(), option::name, nextchar, NONOPTION_P, optarg, opterr, optind, optopt, ordering, PERMUTE, posixly_correct, REQUIRE_ORDER, and option::val.
exchange()
static void exchange (char ** argv) static
{
  int bottom = first_nonopt;
  int middle = last_nonopt;
  int top = optind;
  char *tem;
  /* Exchange the shorter segment with the far end of the longer segment.
     That puts the shorter segment into the right place.
     It leaves the longer segment in the right place overall,
     but it consists of two parts that need to be swapped next.  */
#if defined _LIBC && defined USE_NONOPTION_FLAGS
  /* First make sure the handling of the `__getopt_nonoption_flags'
     string can work normally.  Our top argument must be in the range
     of the string.  */
  if (nonoption_flags_len > 0 && top >= nonoption_flags_max_len)
    {
      /* We must extend the array.  The user plays games with us and
         presents new arguments.  */
      char *new_str = malloc (top + 1);
      if (new_str == NULL)
        nonoption_flags_len = nonoption_flags_max_len = 0;
      else
        {
          memset (__mempcpy (new_str, __getopt_nonoption_flags,
                             nonoption_flags_max_len),
                  '\0', top + 1 - nonoption_flags_max_len);
          nonoption_flags_max_len = top + 1;
          __getopt_nonoption_flags = new_str;
        }
    }
#endif
  while (top > middle && middle > bottom)
    {
      if (top - middle > middle - bottom)
        {
          /* Bottom segment is the short one.  */
          int len = middle - bottom;
          register int i;
          /* Swap it with the top part of the top segment.  */
          for (i = 0; i < len; i++)
            {
              tem = argv[bottom + i];
              argv[bottom + i] = argv[top - (middle - bottom) + i];
              argv[top - (middle - bottom) + i] = tem;
              SWAP_FLAGS (bottom + i, top - (middle - bottom) + i);
            }
          /* Exclude the moved bottom segment from further swapping.  */
          top -= len;
        }
      else
        {
          /* Top segment is the short one.  */
          int len = top - middle;
          register int i;
          /* Swap it with the bottom part of the bottom segment.  */
          for (i = 0; i < len; i++)
            {
              tem = argv[bottom + i];
              argv[bottom + i] = argv[middle + i];
              argv[middle + i] = tem;
              SWAP_FLAGS (bottom + i, middle + i);
            }
          /* Exclude the moved top segment from further swapping.  */
          bottom += len;
        }
    }
  /* Update records for the slots the non-options now occupy.  */
  first_nonopt += (optind - last_nonopt);
  last_nonopt = optind;
}
References first_nonopt, last_nonopt, malloc(), optind, and SWAP_FLAGS.
Referenced by _getopt_internal().
getenv()
char * getenv ()
Referenced by Slic3r::CurlGlobalInit::CurlGlobalInit(), _getopt_initialize(), Slic3r::detect_platform(), run_script(), and Slic3r::Http::tls_system_cert_store().
getopt()
int getopt (int argc, char *const * argv, const char * optstring)
{
  return _getopt_internal (argc, argv, optstring,
                           (const struct option *) 0,
                           (int *) 0,
                           0);
}
References _getopt_internal().
my_index()
static char * my_index (char * str, int chr) const static
{
  while (*str)
    {
      if (*str == chr)
        return (char *) str;
      str++;
    }
  return 0;
}
Referenced by _getopt_internal().
Variable Documentation
__getopt_initialized
int __getopt_initialized
Referenced by _getopt_internal().
first_nonopt
int first_nonopt static
Referenced by _getopt_initialize(), _getopt_internal(), and exchange().
last_nonopt
int last_nonopt static
Referenced by _getopt_initialize(), _getopt_internal(), and exchange().
nextchar
char* nextchar static
Referenced by _getopt_initialize(), and _getopt_internal().
optarg
char* optarg
Referenced by _getopt_internal(), and avrdude_main().
opterr
int opterr = 1
Referenced by _getopt_internal().
optind
int optind = 1
Referenced by _getopt_initialize(), _getopt_internal(), avrdude_main(), and exchange().
optopt
int optopt = '?'
Referenced by _getopt_internal().
[]
enum { ... } ordering
Referenced by _getopt_initialize(), _getopt_internal(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::analyzePattern(), Eigen::SimplicialCholeskyBase< Derived >::analyzePattern(), Slic3r::GCode::collect_layers_to_print(), Eigen::SimplicialCholeskyBase< Derived >::compute(), Eigen::SimplicialCholeskyBase< Derived >::ordering(), Slic3r::GCode::process_layer(), and Slic3r::GCode::sort_print_object_instances().
posixly_correct
char* posixly_correct static
Referenced by _getopt_initialize(), and _getopt_internal().