Prusa Slicer: Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex > Struct Template Reference
Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex > Struct Template Reference
#include <src/eigen/Eigen/src/Eigenvalues/ComplexSchur.h>
Static Public Member Functions
static void run (ComplexSchur< MatrixType > &_this, const MatrixType &matrix, bool computeU)
Detailed Description
template<typename MatrixType, bool IsComplex>
struct Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >
Member Function Documentation
run()
template<typename MatrixType , bool IsComplex> static void Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run (ComplexSchur< MatrixType > & _this, const MatrixType & matrix, bool computeU) inline static
  {
    _this.m_hess.compute(matrix);
    _this.m_matT = _this.m_hess.matrixH();
    if(computeU)  _this.m_matU = _this.m_hess.matrixQ();
  }
References Eigen::HessenbergDecomposition< _MatrixType >::compute(), Eigen::ComplexSchur< _MatrixType >::m_hess, Eigen::ComplexSchur< _MatrixType >::m_matT, Eigen::ComplexSchur< _MatrixType >::m_matU, Eigen::HessenbergDecomposition< _MatrixType >::matrixH(), and Eigen::HessenbergDecomposition< _MatrixType >::matrixQ().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Eigenvalues/ComplexSchur.h