Prusa Slicer: Slic3r::GUI::ObjectLayers Class Reference
Slic3r::GUI::ObjectLayers Class Reference
#include <src/slic3r/GUI/GUI_ObjectLayers.hpp>
Classes
class PlusMinusButton
Public Member Functions
ObjectLayers (wxWindow *parent)
~ObjectLayers ()
void select_editor (LayerRangeEditor *editor, const bool is_last_edited_range)
wxSizer * create_layer (const t_layer_height_range &range, PlusMinusButton *delete_button, PlusMinusButton *add_button)
void create_layers_list ()
void update_layers_list ()
void update_scene_from_editor_selection () const
void UpdateAndShow (const bool show) override
void msw_rescale ()
void sys_color_changed ()
void reset_selection ()
void set_selectable_range (const t_layer_height_range &range)
virtual bool IsShown ()
virtual void Show (const bool show)
virtual void Hide ()
virtual wxSizer * get_sizer ()
ConfigOptionsGroup * get_og ()
const ConfigOptionsGroup * get_og () const
wxWindow * parent () const
Protected Attributes
std::shared_ptr< ConfigOptionsGroup > m_og
wxWindow * m_parent
Private Attributes
ScalableBitmap m_bmp_delete
ScalableBitmap m_bmp_add
ModelObject * m_object {nullptr}
wxFlexGridSizer * m_grid_sizer
t_layer_height_range m_selectable_range
EditorType m_selection_type {etUndef}
Friends
class LayerRangeEditor
Detailed Description
Constructor & Destructor Documentation
ObjectLayers()
Slic3r::GUI::ObjectLayers::ObjectLayers (wxWindow * parent)
                                           :
    OG_Settings(parent, true)
{
    m_grid_sizer = new wxFlexGridSizer(3, 5, wxGetApp().em_unit()); // "Min Z", "Max Z", "Layer height" & buttons sizer
    m_grid_sizer->SetFlexibleDirection(wxHORIZONTAL);
    // Legend for object layers
    for (const std::string col : { L("Start at height"), L("Stop at height"), L("Layer height") }) {
        auto temp = new wxStaticText(m_parent, wxID_ANY, _(col), wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_MIDDLE);
        temp->SetBackgroundStyle(wxBG_STYLE_PAINT);
        temp->SetFont(wxGetApp().bold_font());
        m_grid_sizer->Add(temp);
    }
    m_og->activate();
    m_og->sizer->Clear(true);
    m_og->sizer->Add(m_grid_sizer, 0, wxEXPAND | wxALL, wxOSX ? 0 : 5);
    m_bmp_delete    = ScalableBitmap(parent, "remove_copies"/*"cross"*/);
    m_bmp_add       = ScalableBitmap(parent, "add_copies");
}
References _, col(), em_unit(), L, m_bmp_add, m_bmp_delete, m_grid_sizer, Slic3r::GUI::OG_Settings::m_og, Slic3r::GUI::OG_Settings::m_parent, Slic3r::GUI::OG_Settings::parent(), and wxOSX.
~ObjectLayers()
Slic3r::GUI::ObjectLayers::~ObjectLayers () inline
{}
Member Function Documentation
create_layer()
wxSizer * Slic3r::GUI::ObjectLayers::create_layer (const t_layer_height_range & range, PlusMinusButton * delete_button, PlusMinusButton * add_button)
{
    const bool is_last_edited_range = range == m_selectable_range;
    auto set_focus_data = [range, this](const EditorType type)
    {
        m_selectable_range = range;
        m_selection_type = type;
    };
    auto update_focus_data = [range, this](const t_layer_height_range& new_range, EditorType type, bool enter_pressed)
    {
        // change selectable range for new one, if enter was pressed or if same range was selected
        if (enter_pressed || m_selectable_range == range)
            m_selectable_range = new_range;
        if (enter_pressed)
            m_selection_type = type;
    };
    // Add control for the "Min Z"
    auto editor = new LayerRangeEditor(this, double_to_string(range.first), etMinZ, set_focus_data,
        [range, update_focus_data, this, delete_button, add_button](coordf_t min_z, bool enter_pressed, bool dont_update_ui)
    {
        if (fabs(min_z - range.first) < EPSILON) {
            m_selection_type = etUndef;
            return false;
        }
        // data for next focusing
        coordf_t max_z = min_z < range.second ? range.second : min_z + 0.5;
        const t_layer_height_range new_range = { min_z, max_z };
        if (delete_button)
            delete_button->range = new_range;
        if (add_button)
            add_button->range = new_range;
        update_focus_data(new_range, etMinZ, enter_pressed);
        return wxGetApp().obj_list()->edit_layer_range(range, new_range, dont_update_ui);
    });
    select_editor(editor, is_last_edited_range);
    m_grid_sizer->Add(editor);
    // Add control for the "Max Z"
    editor = new LayerRangeEditor(this, double_to_string(range.second), etMaxZ, set_focus_data,
        [range, update_focus_data, this, delete_button, add_button](coordf_t max_z, bool enter_pressed, bool dont_update_ui)
    {
        if (fabs(max_z - range.second) < EPSILON || range.first > max_z) {
            m_selection_type = etUndef;
            return false;       // LayersList would not be updated/recreated
        }
        // data for next focusing
        const t_layer_height_range& new_range = { range.first, max_z };
        if (delete_button)
            delete_button->range = new_range;
        if (add_button)
            add_button->range = new_range;
        update_focus_data(new_range, etMaxZ, enter_pressed);
        return wxGetApp().obj_list()->edit_layer_range(range, new_range, dont_update_ui);
    });
    select_editor(editor, is_last_edited_range);
    m_grid_sizer->Add(editor);
    // Add control for the "Layer height"
    editor = new LayerRangeEditor(this, double_to_string(m_object->layer_config_ranges[range].option("layer_height")->getFloat()), etLayerHeight, set_focus_data,
        [range](coordf_t layer_height, bool, bool)
    {
        return wxGetApp().obj_list()->edit_layer_range(range, layer_height);
    });
    select_editor(editor, is_last_edited_range);
    auto sizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->Add(editor);
    auto temp = new wxStaticText(m_parent, wxID_ANY, _L("mm"));
    temp->SetBackgroundStyle(wxBG_STYLE_PAINT);
    temp->SetFont(wxGetApp().normal_font());
    sizer->Add(temp, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, wxGetApp().em_unit());
    m_grid_sizer->Add(sizer);
    return sizer;
}
References Slic3r::GUI::double_to_string(), Slic3r::GUI::etMinZ, LayerRangeEditor, m_selectable_range, m_selection_type, Slic3r::range(), and Slic3r::GUI::ObjectLayers::PlusMinusButton::range.
create_layers_list()
void Slic3r::GUI::ObjectLayers::create_layers_list ()
{
    for (const auto &layer : m_object->layer_config_ranges) {
        const t_layer_height_range& range = layer.first;
        auto del_btn = new PlusMinusButton(m_parent, m_bmp_delete, range);
        del_btn->SetToolTip(_L("Remove layer range"));
        auto add_btn = new PlusMinusButton(m_parent, m_bmp_add, range);
        wxString tooltip = wxGetApp().obj_list()->can_add_new_range_after_current(range);
        add_btn->SetToolTip(tooltip.IsEmpty() ? _L("Add layer range") : tooltip);
        add_btn->Enable(tooltip.IsEmpty());
        auto sizer = create_layer(range, del_btn, add_btn);
        sizer->Add(del_btn, 0, wxRIGHT | wxLEFT, em_unit(m_parent));
        sizer->Add(add_btn);
        del_btn->Bind(wxEVT_BUTTON, [del_btn](wxEvent &) {
            wxGetApp().obj_list()->del_layer_range(del_btn->range);
        });
        add_btn->Bind(wxEVT_BUTTON, [add_btn](wxEvent &) {
            wxGetApp().obj_list()->add_layer_range_after_current(add_btn->range);
        });
    }
}
References _L, em_unit(), Slic3r::range(), and wxEVT_BUTTON.
get_og() [1/2]
ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () inline inherited
{ return m_og.get(); }
References Slic3r::GUI::OG_Settings::m_og.
Referenced by Slic3r::GUI::ObjectManipulation::msw_rescale(), and Slic3r::GUI::ObjectManipulation::sys_color_changed().
get_og() [2/2]
const ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () const inline inherited
{ return m_og.get(); }
References Slic3r::GUI::OG_Settings::m_og.
get_sizer()
wxSizer * Slic3r::GUI::OG_Settings::get_sizer () virtual inherited
Reimplemented in Slic3r::GUI::FreqChangedParams.
{
    return m_og->sizer;
}
References Slic3r::GUI::OG_Settings::m_og.
Hide()
void Slic3r::GUI::OG_Settings::Hide () virtual inherited
{
    Show(false);
}
References Slic3r::GUI::OG_Settings::Show().
IsShown()
bool Slic3r::GUI::OG_Settings::IsShown () virtual inherited
Reimplemented in Slic3r::GUI::ObjectManipulation.
{
    return m_og->sizer->IsEmpty() ? false : m_og->sizer->IsShown(size_t(0));
}
References Slic3r::GUI::OG_Settings::m_og.
msw_rescale()
void Slic3r::GUI::ObjectLayers::msw_rescale ()
{
    //m_bmp_delete.msw_rescale();
    //m_bmp_add.msw_rescale();
    //m_grid_sizer->SetHGap(wxGetApp().em_unit());
    //const int cells_cnt = m_grid_sizer->GetCols() * m_grid_sizer->GetEffectiveRowsCount();
    //for (int i = 0; i < cells_cnt; ++i) {
    //    const wxSizerItem* item = m_grid_sizer->GetItem(i);
    //    if (item->IsWindow()) {
    //        LayerRangeEditor* editor = dynamic_cast<LayerRangeEditor*>(item->GetWindow());
    //        if (editor != nullptr)
    //            editor->msw_rescale();
    //    }
    //    else if (item->IsSizer()) // case when we have editor with buttons
    //    {
    //        wxSizerItem* e_item = item->GetSizer()->GetItem(size_t(0)); // editor
    //        if (e_item->IsWindow()) {
    //            LayerRangeEditor* editor = dynamic_cast<LayerRangeEditor*>(e_item->GetWindow());
    //            if (editor != nullptr)
    //                editor->msw_rescale();
    //        }
    //        if (item->GetSizer()->GetItemCount() > 2) // if there are Add/Del buttons
    //            for (size_t btn : {2, 3}) { // del_btn, add_btn
    //                wxSizerItem* b_item = item->GetSizer()->GetItem(btn);
    //                if (b_item->IsWindow()) {
    //                    auto button = dynamic_cast<PlusMinusButton*>(b_item->GetWindow());
    //                    if (button != nullptr)
    //                        button->msw_rescale();
    //                }
    //            }
    //    }
    //}
    m_grid_sizer->Layout();
}
parent()
wxWindow * Slic3r::GUI::OG_Settings::parent () const inline inherited
{return m_parent; }
References Slic3r::GUI::OG_Settings::m_parent.
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectSettings::ObjectSettings(), Slic3r::GUI::OG_Settings::OG_Settings(), Slic3r::GUI::ObjectManipulation::msw_rescale(), and Slic3r::GUI::ObjectSettings::update_settings_list().
reset_selection()
void Slic3r::GUI::ObjectLayers::reset_selection ()
{
    m_selectable_range = { 0.0, 0.0 };
    m_selection_type = etLayerHeight;
}
References Slic3r::GUI::etLayerHeight.
select_editor()
void Slic3r::GUI::ObjectLayers::select_editor (LayerRangeEditor * editor, const bool is_last_edited_range)
{
    if (is_last_edited_range && m_selection_type == editor->type()) {
    /* Workaround! Under OSX we should use CallAfter() for SetFocus() after LayerEditors "reorganizations",
     * because of selected control's strange behavior:
     * cursor is set to the control, but blue border - doesn't.
     * And as a result we couldn't edit this control.
     * */
#ifdef __WXOSX__
        wxTheApp->CallAfter([editor]() {
#endif
        editor->SetFocus();
        editor->SetInsertionPointEnd();
#ifdef __WXOSX__
        });
#endif
    }
}
References m_selection_type, and Slic3r::GUI::LayerRangeEditor::type().
set_selectable_range()
void Slic3r::GUI::ObjectLayers::set_selectable_range (const t_layer_height_range & range) inline
{ m_selectable_range = range; }
References m_selectable_range, and Slic3r::range().
Show()
void Slic3r::GUI::OG_Settings::Show (const bool show) virtual inherited
Reimplemented in Slic3r::GUI::FreqChangedParams, and Slic3r::GUI::ObjectManipulation.
{
    m_og->Show(show);
}
References Slic3r::GUI::OG_Settings::m_og.
Referenced by Slic3r::GUI::OG_Settings::Hide(), and Slic3r::GUI::OG_Settings::UpdateAndShow().
sys_color_changed()
void Slic3r::GUI::ObjectLayers::sys_color_changed ()
{
    m_bmp_delete.sys_color_changed();
    m_bmp_add.sys_color_changed();
    // rescale edit-boxes
    const int cells_cnt = m_grid_sizer->GetCols() * m_grid_sizer->GetEffectiveRowsCount();
    for (int i = 0; i < cells_cnt; ++i) {
        const wxSizerItem* item = m_grid_sizer->GetItem(i);
        if (item->IsSizer()) {// case when we have editor with buttons
            for (size_t btn : {2, 3}) { // del_btn, add_btn
                wxSizerItem* b_item = item->GetSizer()->GetItem(btn);
                if (b_item->IsWindow()) {
                    auto button = dynamic_cast<PlusMinusButton*>(b_item->GetWindow());
                    if (button != nullptr)
                        button->sys_color_changed();
                }
            }
        }
    }
#ifdef _WIN32
    m_og->sys_color_changed();
    for (int i = 0; i < cells_cnt; ++i) {
        const wxSizerItem* item = m_grid_sizer->GetItem(i);
        if (item->IsWindow()) {
            if (LayerRangeEditor* editor = dynamic_cast<LayerRangeEditor*>(item->GetWindow()))
                wxGetApp().UpdateDarkUI(editor);
        }
        else if (item->IsSizer()) {// case when we have editor with buttons
            if (wxSizerItem* e_item = item->GetSizer()->GetItem(size_t(0)); e_item->IsWindow()) {
                if (LayerRangeEditor* editor = dynamic_cast<LayerRangeEditor*>(e_item->GetWindow()))
                    wxGetApp().UpdateDarkUI(editor);
            }
        }
    }
#endif
}
References Slic3r::GUI::button().
update_layers_list()
void Slic3r::GUI::ObjectLayers::update_layers_list ()
{
    ObjectList* objects_ctrl   = wxGetApp().obj_list();
    if (objects_ctrl->multiple_selection()) return;
    const auto item = objects_ctrl->GetSelection();
    if (!item) return;
    const int obj_idx = objects_ctrl->get_selected_obj_idx();
    if (obj_idx < 0) return;
    const ItemType type = objects_ctrl->GetModel()->GetItemType(item);
    if (!(type & (itLayerRoot | itLayer))) return;
    m_object = objects_ctrl->object(obj_idx);
    if (!m_object || m_object->layer_config_ranges.empty()) return;
    // Delete all controls from options group except of the legends
    const int cols = m_grid_sizer->GetEffectiveColsCount();
    const int rows = m_grid_sizer->GetEffectiveRowsCount();
    for (int idx = cols*rows-1; idx >= cols; idx--) {
        wxSizerItem* t = m_grid_sizer->GetItem(idx);
        if (t->IsSizer())
            t->GetSizer()->Clear(true);
        else
            t->DeleteWindows();
        m_grid_sizer->Remove(idx);
    }
    // Add new control according to the selected item
    if (type & itLayerRoot)
        create_layers_list();
    else
        create_layer(objects_ctrl->GetModel()->GetLayerRangeByItem(item), nullptr, nullptr);
    m_parent->Layout();
}
References Slic3r::GUI::ObjectList::get_selected_obj_idx(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectDataViewModel::GetLayerRangeByItem(), Slic3r::GUI::ObjectList::GetModel(), Slic3r::GUI::itLayer, Slic3r::GUI::itLayerRoot, Slic3r::GUI::ObjectList::multiple_selection(), and Slic3r::GUI::ObjectList::object().
update_scene_from_editor_selection()
void Slic3r::GUI::ObjectLayers::update_scene_from_editor_selection () const
{
    // needed to show the visual hints in 3D scene
    wxGetApp().plater()->canvas3D()->handle_layers_data_focus_event(m_selectable_range, m_selection_type);
}
Referenced by Slic3r::GUI::LayerRangeEditor::LayerRangeEditor().
UpdateAndShow()
void Slic3r::GUI::ObjectLayers::UpdateAndShow (const bool show) override virtual
Reimplemented from Slic3r::GUI::OG_Settings.
{
    if (show)
        update_layers_list();
    OG_Settings::UpdateAndShow(show);
}
Friends And Related Symbol Documentation
LayerRangeEditor
friend class LayerRangeEditor friend
Referenced by create_layer().
Member Data Documentation
m_bmp_add
ScalableBitmap Slic3r::GUI::ObjectLayers::m_bmp_add private
Referenced by ObjectLayers().
m_bmp_delete
ScalableBitmap Slic3r::GUI::ObjectLayers::m_bmp_delete private
Referenced by ObjectLayers().
m_grid_sizer
wxFlexGridSizer* Slic3r::GUI::ObjectLayers::m_grid_sizer private
Referenced by ObjectLayers().
m_object
ModelObject* Slic3r::GUI::ObjectLayers::m_object {nullptr} private
m_og
std::shared_ptr<ConfigOptionsGroup> Slic3r::GUI::OG_Settings::m_og protected inherited
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectSettings::ObjectSettings(), Slic3r::GUI::OG_Settings::OG_Settings(), Slic3r::GUI::OG_Settings::get_og(), Slic3r::GUI::OG_Settings::get_og(), Slic3r::GUI::FreqChangedParams::get_og(), Slic3r::GUI::OG_Settings::get_sizer(), Slic3r::GUI::OG_Settings::IsShown(), Slic3r::GUI::ObjectManipulation::IsShown(), Slic3r::GUI::FreqChangedParams::msw_rescale(), Slic3r::GUI::FreqChangedParams::Show(), Slic3r::GUI::OG_Settings::Show(), Slic3r::GUI::ObjectManipulation::Show(), Slic3r::GUI::ObjectSettings::sys_color_changed(), Slic3r::GUI::FreqChangedParams::sys_color_changed(), Slic3r::GUI::ObjectManipulation::update_if_dirty(), and Slic3r::GUI::ObjectSettings::update_settings_list().
m_parent
wxWindow* Slic3r::GUI::OG_Settings::m_parent protected inherited
Referenced by ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::OG_Settings::parent(), Slic3r::GUI::ObjectSettings::update_config_values(), Slic3r::GUI::ObjectSettings::update_settings_list(), and Slic3r::GUI::ObjectManipulation::update_warning_icon_state().
m_selectable_range
t_layer_height_range Slic3r::GUI::ObjectLayers::m_selectable_range private
Referenced by create_layer(), and set_selectable_range().
m_selection_type
EditorType Slic3r::GUI::ObjectLayers::m_selection_type {etUndef} private
Referenced by create_layer(), and select_editor().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectLayers.hpp
src/slic3r/GUI/GUI_ObjectLayers.cpp