Prusa Slicer: Slic3r::GUI::GLCanvas3D::SLAView Class Reference
Slic3r::GUI::GLCanvas3D::SLAView Class Reference
Public Member Functions
SLAView (GLCanvas3D &parent)
void detect_type_from_volumes (const GLVolumePtrs &volumes)
void set_type (ESLAViewType type)
void set_type (const GLVolume::CompositeID &id, ESLAViewType type)
void update_volumes_visibility (GLVolumePtrs &volumes)
void update_instances_cache (const std::vector< std::pair< GLVolume::CompositeID, GLVolume::CompositeID > > &new_to_old_ids_map)
void render_switch_button ()
Private Types
typedef std::pair< GLVolume::CompositeID, ESLAViewType > InstancesCacheItem
Private Member Functions
InstancesCacheItem * find_instance_item (const GLVolume::CompositeID &id)
void select_full_instance (const GLVolume::CompositeID &id)
Private Attributes
GLCanvas3D & m_parent
std::vector< InstancesCacheItem > m_instances_cache
bool m_use_instance_bbox { true }
Detailed Description
Member Typedef Documentation
InstancesCacheItem
typedef std::pair<GLVolume::CompositeID, ESLAViewType> Slic3r::GUI::GLCanvas3D::SLAView::InstancesCacheItem private
Constructor & Destructor Documentation
SLAView()
Slic3r::GUI::GLCanvas3D::SLAView::SLAView (GLCanvas3D & parent) inline explicit
: m_parent(parent) {}
Member Function Documentation
detect_type_from_volumes()
void Slic3r::GUI::GLCanvas3D::SLAView::detect_type_from_volumes (const GLVolumePtrs & volumes)
{
    for (auto& [id, type] : m_instances_cache) {
        type = ESLAViewType::Original;
    }
    for (const GLVolume* v : volumes) {
        if (v->volume_idx() == -(int)slaposDrillHoles) {
            if (object_contains_negative_volumes(*m_parent.get_model(), v->composite_id.object_id) ||
                object_has_sla_drain_holes(*m_parent.get_model(), v->composite_id.object_id)) {
                const InstancesCacheItem* instance = find_instance_item(v->composite_id);
                assert(instance != nullptr);
                set_type(instance->first, ESLAViewType::Processed);
            }
        }
    }
}
References Slic3r::GUI::object_contains_negative_volumes(), Slic3r::GUI::object_has_sla_drain_holes(), Slic3r::GUI::GLCanvas3D::Original, Slic3r::GUI::GLCanvas3D::Processed, and Slic3r::slaposDrillHoles.
Referenced by Slic3r::GUI::GLCanvas3D::detect_sla_view_type(), and Slic3r::GUI::GLCanvas3D::reload_scene().
find_instance_item()
GLCanvas3D::SLAView::InstancesCacheItem * Slic3r::GUI::GLCanvas3D::SLAView::find_instance_item (const GLVolume::CompositeID & id) private
{
    auto it = std::find_if(m_instances_cache.begin(), m_instances_cache.end(),
        [&id](const InstancesCacheItem& item) { return composite_id_match(item.first, id); });
    return (it == m_instances_cache.end()) ? nullptr : &(*it);
}
render_switch_button()
void Slic3r::GUI::GLCanvas3D::SLAView::render_switch_button ()
{
    const SLAPrint* sla_print = m_parent.sla_print();
    if (sla_print == nullptr)
        return;
    const std::vector<int> mo_idxs = processed_objects_idxs(*m_parent.get_model(), *sla_print, m_parent.get_volumes().volumes);
    if (mo_idxs.empty())
        return;
    Selection& selection = m_parent.get_selection();
    const int obj_idx = selection.get_object_idx();
    if (std::find(mo_idxs.begin(), mo_idxs.end(), obj_idx) == mo_idxs.end())
        return;
    if (!object_contains_negative_volumes(*m_parent.get_model(), obj_idx))
        return;
    const int inst_idx = selection.get_instance_idx();
    if (inst_idx < 0)
        return;
    const GLVolume::CompositeID composite_id(obj_idx, 0, inst_idx);
    const InstancesCacheItem* sel_instance = find_instance_item(composite_id);
    if (sel_instance == nullptr)
        return;
    const ESLAViewType type = sel_instance->second;
    BoundingBoxf ss_box;
    if (m_use_instance_bbox) {
        const Selection::EMode mode = selection.get_mode();
        if (obj_idx >= 0 && inst_idx >= 0) {
            const Selection::IndicesList selected_idxs = selection.get_volume_idxs();
            std::vector<unsigned int> idxs_as_vector;
            idxs_as_vector.assign(selected_idxs.begin(), selected_idxs.end());
            selection.add_instance(obj_idx, inst_idx, true);
            ss_box = selection.get_screen_space_bounding_box();
            selection.add_volumes(mode, idxs_as_vector, true);
        }
    }
    if (!ss_box.defined)
        ss_box = selection.get_screen_space_bounding_box();
    assert(ss_box.defined);
    ImGuiWrapper& imgui = *wxGetApp().imgui();
    ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(0.0f, 0.0f, 0.0f, 0.0f));
    ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(0.0f, 0.0f, 0.0f, 0.0f));
    ImGui::SetNextWindowPos(ImVec2((float)ss_box.max.x(), (float)ss_box.center().y()), ImGuiCond_Always, ImVec2(0.0, 0.5));
    imgui.begin(std::string("SLAViewSwitch"), ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoDecoration);
    const float icon_size = 1.5 * ImGui::GetTextLineHeight();
    if (imgui.draw_radio_button(_u8L("SLA view"), 1.5f * icon_size, true,
        [&imgui, sel_instance](ImGuiWindow& window, const ImVec2& pos, float size) {
            const wchar_t icon_id = (sel_instance->second == ESLAViewType::Original) ? ImGui::SlaViewProcessed : ImGui::SlaViewOriginal;
            imgui.draw_icon(window, pos, size, icon_id);
        })) {
        switch (sel_instance->second)
        {
        case ESLAViewType::Original:  { m_parent.set_sla_view_type(sel_instance->first, ESLAViewType::Processed); break; }
        case ESLAViewType::Processed: { m_parent.set_sla_view_type(sel_instance->first, ESLAViewType::Original); break; }
        default: { assert(false); break; }
        }
    }
    if (ImGui::IsItemHovered()) {
        ImGui::PushStyleColor(ImGuiCol_PopupBg, ImGuiWrapper::COL_WINDOW_BACKGROUND);
        ImGui::BeginTooltip();
        wxString tooltip;
        switch (type)
        {
        case ESLAViewType::Original:  { tooltip = _L("Show as processed"); break; }
        case ESLAViewType::Processed: { tooltip = _L("Show as original"); break; }
        default: { assert(false); break; }
        }
        imgui.text(tooltip);
        ImGui::EndTooltip();
        ImGui::PopStyleColor();
    }
    imgui.end();
    ImGui::PopStyleColor(2);
}
References _L, _u8L, Slic3r::GUI::Selection::add_instance(), Slic3r::GUI::Selection::add_volumes(), Slic3r::GUI::ImGuiWrapper::begin(), ImGui::BeginTooltip(), Slic3r::BoundingBoxBase< PointType, APointsType >::center(), Slic3r::GUI::ImGuiWrapper::COL_WINDOW_BACKGROUND, Slic3r::BoundingBoxBase< PointType, APointsType >::defined, Slic3r::GUI::ImGuiWrapper::draw_icon(), Slic3r::GUI::ImGuiWrapper::draw_radio_button(), Slic3r::GUI::ImGuiWrapper::end(), ImGui::EndTooltip(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_mode(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::Selection::get_screen_space_bounding_box(), Slic3r::GUI::Selection::get_volume_idxs(), ImGui::GetTextLineHeight(), ImGuiCol_Border, ImGuiCol_PopupBg, ImGuiCol_WindowBg, ImGuiCond_Always, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoDecoration, ImGui::IsItemHovered(), Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::GUI::object_contains_negative_volumes(), Slic3r::GUI::GLCanvas3D::Original, ImGui::PopStyleColor(), Slic3r::GUI::GLCanvas3D::Processed, Slic3r::GUI::processed_objects_idxs(), ImGui::PushStyleColor(), ImGui::SetNextWindowPos(), Slic3r::GUI::GLCanvas3D::sla_print(), ImGui::SlaViewOriginal, ImGui::SlaViewProcessed, and Slic3r::GUI::ImGuiWrapper::text().
Referenced by Slic3r::GUI::GLCanvas3D::render().
select_full_instance()
void Slic3r::GUI::GLCanvas3D::SLAView::select_full_instance (const GLVolume::CompositeID & id) private
{
    bool extended_selection = false;
    Selection& selection = m_parent.get_selection();
    const Selection::ObjectIdxsToInstanceIdxsMap& sel_cache = selection.get_content();
    auto obj_it = sel_cache.find(id.object_id);
    if (obj_it != sel_cache.end()) {
        auto inst_it = std::find(obj_it->second.begin(), obj_it->second.end(), id.instance_id);
        if (inst_it != obj_it->second.end()) {
            selection.add_instance(id.object_id, id.instance_id);
            extended_selection = true;
        }
    }
    if (extended_selection)
        m_parent.post_event(SimpleEvent(EVT_GLCANVAS_OBJECT_SELECT));
}
References Slic3r::GUI::Selection::add_instance(), and Slic3r::GUI::Selection::get_content().
set_type() [1/2]
void Slic3r::GUI::GLCanvas3D::SLAView::set_type (const GLVolume::CompositeID & id, ESLAViewType type)
{
    InstancesCacheItem* instance = find_instance_item(id);
    assert(instance != nullptr);
    instance->second = new_type;
    if (new_type == ESLAViewType::Processed)
        select_full_instance(id);
}
References Slic3r::GUI::GLCanvas3D::Processed.
set_type() [2/2]
void Slic3r::GUI::GLCanvas3D::SLAView::set_type (ESLAViewType type)
{
    for (auto& [id, type] : m_instances_cache) {
        type = new_type;
        if (new_type == ESLAViewType::Processed)
            select_full_instance(id);
    }
}
References Slic3r::GUI::GLCanvas3D::Processed.
Referenced by Slic3r::GUI::GLCanvas3D::set_sla_view_type(), and Slic3r::GUI::GLCanvas3D::set_sla_view_type().
update_instances_cache()
void Slic3r::GUI::GLCanvas3D::SLAView::update_instances_cache (const std::vector< std::pair< GLVolume::CompositeID, GLVolume::CompositeID > > & new_to_old_ids_map)
{
    // First, extract current instances list from the volumes
    const GLVolumePtrs& volumes = m_parent.get_volumes().volumes;
    std::vector<InstancesCacheItem> new_instances_cache;
    for (const GLVolume* v : volumes) {
        new_instances_cache.emplace_back(v->composite_id, ESLAViewType::Original);
    }
    std::sort(new_instances_cache.begin(), new_instances_cache.end(),
        [](const InstancesCacheItem& i1, const InstancesCacheItem& i2) {
            return i1.first.object_id < i2.first.object_id || (i1.first.object_id == i2.first.object_id && i1.first.instance_id < i2.first.instance_id); });
    new_instances_cache.erase(std::unique(new_instances_cache.begin(), new_instances_cache.end(),
        [](const InstancesCacheItem& i1, const InstancesCacheItem& i2) {
            return composite_id_match(i1.first, i2.first); }), new_instances_cache.end());
    // Second, update instances type from previous state
    for (auto& inst_type : new_instances_cache) {
        const auto map_to_old_it = std::find_if(new_to_old_ids_map.begin(), new_to_old_ids_map.end(), [&inst_type](const std::pair<GLVolume::CompositeID, GLVolume::CompositeID>& item) {
            return composite_id_match(inst_type.first, item.first); });
        const GLVolume::CompositeID old_inst_id = (map_to_old_it != new_to_old_ids_map.end()) ? map_to_old_it->second : inst_type.first;
        const InstancesCacheItem* old_instance = find_instance_item(old_inst_id);
        if (old_instance != nullptr)
            inst_type.second = old_instance->second;
    }
    m_instances_cache = new_instances_cache;
}
References Slic3r::GUI::GLCanvas3D::Original.
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene().
update_volumes_visibility()
void Slic3r::GUI::GLCanvas3D::SLAView::update_volumes_visibility (GLVolumePtrs & volumes)
{
    const SLAPrint* sla_print = m_parent.sla_print();
    const std::vector<int> mo_idxs = (sla_print != nullptr) ? processed_objects_idxs(*m_parent.get_model(), *sla_print, volumes) : std::vector<int>();
    std::vector<std::shared_ptr<SceneRaycasterItem>>* raycasters = m_parent.get_raycasters_for_picking(SceneRaycaster::EType::Volume);
    for (GLVolume* v : volumes) {
        const int obj_idx = v->object_idx();
        bool active = std::find(mo_idxs.begin(), mo_idxs.end(), obj_idx) == mo_idxs.end();
        if (!active) {
            const InstancesCacheItem* instance = find_instance_item(v->composite_id);
            assert(instance != nullptr);
            active = (instance->second == ESLAViewType::Processed) ? v->volume_idx() < 0 : v->volume_idx() != -(int)slaposDrillHoles;
        }
        v->is_active = active;
        auto it = std::find_if(raycasters->begin(), raycasters->end(), [v](std::shared_ptr<SceneRaycasterItem> item) { return item->get_raycaster() == v->mesh_raycaster.get(); });
        if (it != raycasters->end())
            (*it)->set_active(v->is_active);
    }
}
References Slic3r::GUI::GLCanvas3D::Processed, Slic3r::GUI::processed_objects_idxs(), Slic3r::GUI::GLCanvas3D::sla_print(), Slic3r::slaposDrillHoles, and Slic3r::GUI::SceneRaycaster::Volume.
Referenced by Slic3r::GUI::GLCanvas3D::detect_sla_view_type(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::set_sla_view_type(), and Slic3r::GUI::GLCanvas3D::set_sla_view_type().
Member Data Documentation
m_instances_cache
std::vector<InstancesCacheItem> Slic3r::GUI::GLCanvas3D::SLAView::m_instances_cache private
m_parent
GLCanvas3D& Slic3r::GUI::GLCanvas3D::SLAView::m_parent private
m_use_instance_bbox
bool Slic3r::GUI::GLCanvas3D::SLAView::m_use_instance_bbox { true } private
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLCanvas3D.hpp
src/slic3r/GUI/GLCanvas3D.cpp