Prusa Slicer: Slic3r::LookupSocket Class Reference
Slic3r::LookupSocket Class Reference
#include <src/slic3r/Utils/Bonjour.hpp>
Public Member Functions
LookupSocket (Bonjour::TxtKeys txt_keys, std::string service, std::string service_dn, std::string protocol, Bonjour::ReplyFn replyfn, const boost::asio::ip::address &multicast_address, const boost::asio::ip::address &interface_address, std::shared_ptr< boost::asio::io_service > io_service)
LookupSocket (Bonjour::TxtKeys txt_keys, std::string service, std::string service_dn, std::string protocol, Bonjour::ReplyFn replyfn, const boost::asio::ip::address &multicast_address, std::shared_ptr< boost::asio::io_service > io_service)
const Bonjour::TxtKeys get_txt_keys () const
const std::string get_service () const
const std::string get_service_dn () const
void send ()
void async_receive ()
void cancel ()
Protected Member Functions
SharedSession create_session () const override
void create_request ()
void receive_handler (SharedSession session, const boost::system::error_code &error, size_t bytes)
Protected Attributes
boost::optional< BonjourRequest > request
Bonjour::TxtKeys txt_keys
std::string service
std::string service_dn
std::string protocol
Bonjour::ReplyFn replyfn
boost::asio::ip::address multicast_address
boost::asio::ip::udp::socket socket
boost::asio::ip::udp::endpoint mcast_endpoint
std::shared_ptr< boost::asio::io_service > io_service
std::vector< BonjourRequest > requests
Detailed Description
Constructor & Destructor Documentation
LookupSocket() [1/2]
Slic3r::LookupSocket::LookupSocket (Bonjour::TxtKeys txt_keys, std::string service, std::string service_dn, std::string protocol, Bonjour::ReplyFn replyfn, const boost::asio::ip::address & multicast_address, const boost::asio::ip::address & interface_address, std::shared_ptr< boost::asio::io_service > io_service) inline
    : UdpSocket(replyfn, multicast_address, interface_address, io_service)
    , txt_keys(txt_keys)
    , service(service)
    , service_dn(service_dn)
    , protocol(protocol)
  {
    assert(!service.empty() && replyfn);
    create_request();
  }
References create_request(), Slic3r::UdpSocket::replyfn, and service.
LookupSocket() [2/2]
Slic3r::LookupSocket::LookupSocket (Bonjour::TxtKeys txt_keys, std::string service, std::string service_dn, std::string protocol, Bonjour::ReplyFn replyfn, const boost::asio::ip::address & multicast_address, std::shared_ptr< boost::asio::io_service > io_service) inline
    : UdpSocket(replyfn, multicast_address, io_service)
    , txt_keys(txt_keys)
    , service(service)
    , service_dn(service_dn)
    , protocol(protocol)
  {
    assert(!service.empty() && replyfn);
    create_request();
  }
References create_request(), Slic3r::UdpSocket::replyfn, and service.
Member Function Documentation
async_receive()
void Slic3r::UdpSocket::async_receive () inherited
{
  try {
    // our session to hold the buffer + endpoint
    auto session = create_session();
    socket.async_receive_from(asio::buffer(session->buffer, session->buffer.size())
      , session->remote_endpoint
      , boost::bind(&UdpSocket::receive_handler, this, session, asio::placeholders::error, asio::placeholders::bytes_transferred));
  }
  catch (std::exception& e) {
    BOOST_LOG_TRIVIAL(error) << e.what();
  }
}
References Slic3r::UdpSocket::create_session(), error, Slic3r::UdpSocket::receive_handler(), and Slic3r::UdpSocket::socket.
Referenced by Slic3r::UdpSocket::receive_handler(), and Slic3r::UdpSocket::send().
cancel()
void Slic3r::UdpSocket::cancel () inline inherited
{ socket.cancel(); }
References Slic3r::UdpSocket::socket.
create_request()
void Slic3r::LookupSocket::create_request () inline protected
  {
    requests.clear();
    // create PTR request
    if (auto rqst = BonjourRequest::make_PTR(service, protocol); rqst)
      requests.push_back(std::move(rqst.get()));
  }
References Slic3r::BonjourRequest::make_PTR(), protocol, Slic3r::UdpSocket::requests, and service.
Referenced by LookupSocket(), and LookupSocket().
create_session()
SharedSession Slic3r::LookupSocket::create_session () const override protected virtual
Implements Slic3r::UdpSocket.
{
  return std::shared_ptr< LookupSession >(new LookupSession(this, replyfn));
}
References Slic3r::UdpSocket::replyfn.
get_service()
const std::string Slic3r::LookupSocket::get_service () const inline
{ return service; }
References service.
get_service_dn()
const std::string Slic3r::LookupSocket::get_service_dn () const inline
{ return service_dn; }
References service_dn.
Referenced by Slic3r::LookupSession::handle_receive().
get_txt_keys()
const Bonjour::TxtKeys Slic3r::LookupSocket::get_txt_keys () const inline
{ return txt_keys; }
References txt_keys.
Referenced by Slic3r::LookupSession::handle_receive().
receive_handler()
void Slic3r::UdpSocket::receive_handler (SharedSession session, const boost::system::error_code & error, size_t bytes) protected inherited
{
  // let io_service to handle the datagram on session
  // from boost documentation io_service::post:
  // The io_service guarantees that the handler will only be called in a thread in which the run(), run_one(), poll() or poll_one() member functions is currently being invoked.
  io_service->post(boost::bind(&UdpSession::handle_receive, session, error, bytes));
  // immediately accept new datagrams
  async_receive();
}
References Slic3r::UdpSocket::async_receive(), error, Slic3r::UdpSession::handle_receive(), and Slic3r::UdpSocket::io_service.
Referenced by Slic3r::UdpSocket::async_receive().
send()
void Slic3r::UdpSocket::send () inherited
{
  try {
    for (const auto& request : requests)
      socket.send_to(asio::buffer(request.m_data), mcast_endpoint);
    // Should we care if this is called while already receiving? (async_receive call from receive_handler)
    async_receive();
  }
  catch (std::exception& e) {
    BOOST_LOG_TRIVIAL(error) << e.what();
  }
}
References Slic3r::UdpSocket::async_receive(), error, Slic3r::UdpSocket::mcast_endpoint, Slic3r::UdpSocket::requests, and Slic3r::UdpSocket::socket.
Member Data Documentation
io_service
std::shared_ptr< boost::asio::io_service > Slic3r::UdpSocket::io_service protected inherited
Referenced by Slic3r::UdpSocket::receive_handler().
mcast_endpoint
boost::asio::ip::udp::endpoint Slic3r::UdpSocket::mcast_endpoint protected inherited
Referenced by Slic3r::UdpSocket::send().
multicast_address
boost::asio::ip::address Slic3r::UdpSocket::multicast_address protected inherited
protocol
std::string Slic3r::LookupSocket::protocol protected
Referenced by create_request().
replyfn
Bonjour::ReplyFn Slic3r::UdpSocket::replyfn protected inherited
Referenced by LookupSocket(), LookupSocket(), Slic3r::ResolveSocket::ResolveSocket(), Slic3r::ResolveSocket::ResolveSocket(), create_session(), and Slic3r::ResolveSocket::create_session().
request
boost::optional<BonjourRequest> Slic3r::LookupSocket::request protected
requests
std::vector<BonjourRequest> Slic3r::UdpSocket::requests protected inherited
Referenced by create_request(), Slic3r::ResolveSocket::create_requests(), and Slic3r::UdpSocket::send().
service
std::string Slic3r::LookupSocket::service protected
Referenced by LookupSocket(), LookupSocket(), create_request(), and get_service().
service_dn
std::string Slic3r::LookupSocket::service_dn protected
Referenced by get_service_dn().
socket
boost::asio::ip::udp::socket Slic3r::UdpSocket::socket protected inherited
Referenced by Slic3r::UdpSocket::async_receive(), Slic3r::UdpSocket::cancel(), and Slic3r::UdpSocket::send().
txt_keys
Bonjour::TxtKeys Slic3r::LookupSocket::txt_keys protected
Referenced by get_txt_keys().
The documentation for this class was generated from the following files:
src/slic3r/Utils/Bonjour.hpp
src/slic3r/Utils/Bonjour.cpp