Prusa Slicer: libnest2d::pointlike Namespace Reference
libnest2d::pointlike Namespace Reference
Functions
template<class P >
TCoord< P > x (const P &p)
template<class P >
TCoord< P > y (const P &p)
template<class P >
TCoord< P > & x (P &p)
template<class P >
TCoord< P > & y (P &p)
template<class P , class Unit = TCompute<P>>
Unit squaredDistance (const P &p1, const P &p2)
template<class P >
double distance (const P &p1, const P &p2)
template<class Pt >
Pt perp (const Pt &p)
template<class Pt , class Unit = TCompute<Pt>>
Unit dotperp (const Pt &a, const Pt &b)
template<class Pt , class Unit = TCompute<Pt>>
Unit dot (const Pt &a, const Pt &b)
template<class Pt , class Unit = TCompute<Pt>>
Unit magnsq (const Pt &p)
template<class P , class Unit = TCompute<P>>
std::pair< Unit, bool > horizontalDistance (const P &p, const _Segment< P > &s)
template<class P , class Unit = TCompute<P>>
std::pair< Unit, bool > verticalDistance (const P &p, const _Segment< P > &s)
Function Documentation
distance()
template<class P > double libnest2d::pointlike::distance (const P & p1, const P & p2) inline
{
    return std::sqrt(squaredDistance<P, double>(p1, p2));
}
Referenced by libnest2d::placers::minimizeCircle(), Slic3r::arrangement::AutoArranger< TBin >::objfunc(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::trypack().
dot()
template<class Pt , class Unit = TCompute<Pt>> Unit libnest2d::pointlike::dot (const Pt & a, const Pt & b) inline
{
    return Unit(x(a)) * x(b) + Unit(y(a)) * y(b);
}
References x(), and y().
Referenced by libnest2d::nfp::nfpConvexOnly(), and libnest2d::rotcalipers().
dotperp()
template<class Pt , class Unit = TCompute<Pt>> Unit libnest2d::pointlike::dotperp (const Pt & a, const Pt & b) inline
{
    return Unit(x(a)) * Unit(y(b)) - Unit(y(a)) * Unit(x(b));
}
References x(), and y().
Referenced by libnest2d::nfp::nfpConvexOnly().
horizontalDistance()
template<class P , class Unit = TCompute<P>> std::pair< Unit, bool > libnest2d::pointlike::horizontalDistance (const P & p, const _Segment< P > & s) inline
{
    namespace pl = pointlike;
    auto x = Unit(pl::x(p)), y = Unit(pl::y(p));
    auto x1 = Unit(pl::x(s.first())), y1 = Unit(pl::y(s.first()));
    auto x2 = Unit(pl::x(s.second())), y2 = Unit(pl::y(s.second()));
    Unit ret;
    if( (y < y1 && y < y2) || (y > y1 && y > y2) )
        return {0, false};
    if ((y == y1 && y == y2) && (x > x1 && x > x2))
        ret = std::min( x-x1, x -x2);
    else if( (y == y1 && y == y2) && (x < x1 && x < x2))
        ret = -std::min(x1 - x, x2 - x);
    else if(y == y1 && y == y2)
        ret = 0;
    else
        ret = x - x1 + (x1 - x2)*(y1 - y)/(y1 - y2);
    return {ret, true};
}
References libnest2d::_Segment< P >::first(), libnest2d::_Segment< P >::second(), x(), and y().
magnsq()
template<class Pt , class Unit = TCompute<Pt>> Unit libnest2d::pointlike::magnsq (const Pt & p) inline
{
    return  Unit(x(p)) * x(p) + Unit(y(p)) * y(p);
}
References x(), and y().
Referenced by libnest2d::nfp::nfpConvexOnly(), and libnest2d::rotcalipers().
perp()
template<class Pt > Pt libnest2d::pointlike::perp (const Pt & p) inline
{
    return Pt(y(p), -x(p));
}
References x(), and y().
Referenced by libnest2d::rectarea(), and libnest2d::rotcalipers().
squaredDistance()
template<class P , class Unit = TCompute<P>> Unit libnest2d::pointlike::squaredDistance (const P & p1, const P & p2) inline
{
    auto x1 = Unit(x(p1)), y1 = Unit(y(p1)), x2 = Unit(x(p2)), y2 = Unit(y(p2));
    Unit a = (x2 - x1), b = (y2 - y1);
    return a * a + b * b;
}
References x(), and y().
Referenced by libnest2d::shapelike::isInside().
verticalDistance()
template<class P , class Unit = TCompute<P>> std::pair< Unit, bool > libnest2d::pointlike::verticalDistance (const P & p, const _Segment< P > & s) inline
{
    namespace pl = pointlike;
    auto x = Unit(pl::x(p)), y = Unit(pl::y(p));
    auto x1 = Unit(pl::x(s.first())), y1 = Unit(pl::y(s.first()));
    auto x2 = Unit(pl::x(s.second())), y2 = Unit(pl::y(s.second()));
    Unit ret;
    if( (x < x1 && x < x2) || (x > x1 && x > x2) )
        return {0, false};
    if ((x == x1 && x == x2) && (y > y1 && y > y2))
        ret = std::min( y-y1, y -y2);
    else if( (x == x1 && x == x2) && (y < y1 && y < y2))
        ret = -std::min(y1 - y, y2 - y);
    else if(x == x1 && x == x2)
        ret = 0;
    else
        ret = y - y1 + (y1 - y2)*(x1 - x)/(x1 - x2);
    return {ret, true};
}
References libnest2d::_Segment< P >::first(), libnest2d::_Segment< P >::second(), x(), and y().
x() [1/2]
template<class P > TCoord< P > libnest2d::pointlike::x (const P & p) inline
{
    return p.x();
}
Referenced by dot(), dotperp(), horizontalDistance(), magnsq(), perp(), squaredDistance(), verticalDistance(), and libnest2d::_Box< P >::width().
x() [2/2]
template<class P > TCoord< P > & libnest2d::pointlike::x (P & p) inline
{
    return p.x();
}
y() [1/2]
template<class P > TCoord< P > libnest2d::pointlike::y (const P & p) inline
{
    return p.y();
}
Referenced by dot(), dotperp(), libnest2d::_Box< P >::height(), horizontalDistance(), magnsq(), perp(), squaredDistance(), and verticalDistance().
y() [2/2]
template<class P > TCoord< P > & libnest2d::pointlike::y (P & p) inline
{
    return p.y();
}