Prusa Slicer: src/avrdude/serbb.h File Reference
serbb.h File Reference
Functions
void serbb_initpgm (PROGRAMMER *pgm)
Variables
const char serbb_desc []
Function Documentation
serbb_initpgm()
void serbb_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "SERBB");
  pgm_fill_old_pins(pgm); // TODO to be removed if old pin data no longer needed
  pgm->rdy_led        = bitbang_rdy_led;
  pgm->err_led        = bitbang_err_led;
  pgm->pgm_led        = bitbang_pgm_led;
  pgm->vfy_led        = bitbang_vfy_led;
  pgm->initialize     = bitbang_initialize;
  pgm->display        = serbb_display;
  pgm->enable         = serbb_enable;
  pgm->disable        = serbb_disable;
  pgm->powerup        = serbb_powerup;
  pgm->powerdown      = serbb_powerdown;
  pgm->program_enable = bitbang_program_enable;
  pgm->chip_erase     = bitbang_chip_erase;
  pgm->cmd            = bitbang_cmd;
  pgm->cmd_tpi        = bitbang_cmd_tpi;
  pgm->open           = serbb_open;
  pgm->close          = serbb_close;
  pgm->setpin         = serbb_setpin;
  pgm->getpin         = serbb_getpin;
  pgm->highpulsepin   = serbb_highpulsepin;
  pgm->read_byte      = avr_read_byte_default;
  pgm->write_byte     = avr_write_byte_default;
}
References avr_read_byte_default(), avr_write_byte_default(), bitbang_chip_erase(), bitbang_cmd(), bitbang_cmd_tpi(), bitbang_err_led(), bitbang_initialize(), bitbang_pgm_led(), bitbang_program_enable(), bitbang_rdy_led(), bitbang_vfy_led(), programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::cmd_tpi, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::err_led, programmer_t::getpin, programmer_t::highpulsepin, programmer_t::initialize, programmer_t::open, pgm, pgm_fill_old_pins(), programmer_t::pgm_led, programmer_t::powerdown, programmer_t::powerup, programmer_t::program_enable, programmer_t::rdy_led, programmer_t::read_byte, serbb_close(), serbb_disable(), serbb_display(), serbb_enable(), serbb_getpin(), serbb_highpulsepin(), serbb_open(), serbb_powerdown(), serbb_powerup(), serbb_setpin(), programmer_t::setpin, programmer_t::type, programmer_t::vfy_led, and programmer_t::write_byte.
Variable Documentation
serbb_desc
const char serbb_desc[] extern