Prusa Slicer: Slic3r::GUI::FileGet Class Reference
Slic3r::GUI::FileGet Class Reference
#include <src/slic3r/GUI/DownloaderFileGet.hpp>
Classes
struct priv
Public Member Functions
FileGet (int ID, std::string url, const std::string &filename, wxEvtHandler *evt_handler, const boost::filesystem::path &dest_folder)
FileGet (FileGet &&other)
~FileGet ()
void get ()
void cancel ()
void pause ()
void resume ()
Static Public Member Functions
static std::string escape_url (const std::string &url)
static bool is_subdomain (const std::string &url, const std::string &domain)
Private Attributes
std::unique_ptr< priv > p
Detailed Description
Constructor & Destructor Documentation
FileGet() [1/2]
Slic3r::GUI::FileGet::FileGet (int ID, std::string url, const std::string & filename, wxEvtHandler * evt_handler, const boost::filesystem::path & dest_folder)
  : p(new priv(ID, std::move(url), filename, evt_handler, dest_folder))
{}
FileGet() [2/2]
Slic3r::GUI::FileGet::FileGet (FileGet && other)
: p(std::move(other.p)) {}
~FileGet()
Slic3r::GUI::FileGet::~FileGet ()
{
  if (p && p->m_io_thread.joinable()) {
    p->m_cancel = true;
    p->m_io_thread.join();
  }
}
References p.
Member Function Documentation
cancel()
void Slic3r::GUI::FileGet::cancel ()
{
  if(p && p->m_stopped) {
    if (p->m_io_thread.joinable()) {
      p->m_cancel = true;
      p->m_io_thread.join();
      wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_CANCELED);
      evt->SetInt(p->m_id);
      p->m_evt_handler->QueueEvent(evt);
    }
  }
  if (p)
    p->m_cancel = true;
}
References p.
Referenced by Slic3r::GUI::FileGet::priv::get_perform().
escape_url()
std::string Slic3r::GUI::FileGet::escape_url (const std::string & url) static
{
  std::string ret_val;
  CURL* curl = curl_easy_init();
  if (curl) {
    int decodelen;
    char* decoded = curl_easy_unescape(curl, unescaped.c_str(), unescaped.size(), &decodelen);
    if (decoded) {
      ret_val = std::string(decoded);
      curl_free(decoded);
    }
    curl_easy_cleanup(curl);
  }
  return ret_val;
}
Referenced by Slic3r::GUI::Downloader::start_download().
get()
void Slic3r::GUI::FileGet::get ()
{
  assert(p);
  if (p->m_io_thread.joinable()) {
      // This will stop transfers being done by the thread, if any.
      // Cancelling takes some time, but should complete soon enough.
      p->m_cancel = true;
      p->m_io_thread.join();
  }
  p->m_cancel = false;
  p->m_pause = false;
  p->m_io_thread = std::thread([this]() {
    p->get_perform();
    });
}
References p.
is_subdomain()
bool Slic3r::GUI::FileGet::is_subdomain (const std::string & url, const std::string & domain) static
{
  // domain should be f.e. printables.com (.com including)
  char* host;
  std::string host_string;
  CURLUcode rc;
  CURLU* curl = curl_url();
  if (!curl) {
    BOOST_LOG_TRIVIAL(error) << "Failed to init Curl library in function is_domain.";
    return false;
  }
  rc = curl_url_set(curl, CURLUPART_URL, url.c_str(), 0);
  if (rc != CURLUE_OK) {
    curl_url_cleanup(curl);
    return false;
  }
  rc = curl_url_get(curl, CURLUPART_HOST, &host, 0);
  if (rc != CURLUE_OK || !host) {
    curl_url_cleanup(curl);
    return false;
  }
  host_string = std::string(host);
  curl_free(host);
  // now host should be subdomain.domain or just domain
  if (domain == host_string) {
    curl_url_cleanup(curl);
    return true;
  }
  if(boost::ends_with(host_string, "." + domain)) {
    curl_url_cleanup(curl);
    return true;
  }
  curl_url_cleanup(curl);
  return false;
}
References error.
Referenced by Slic3r::GUI::Downloader::start_download().
pause()
void Slic3r::GUI::FileGet::pause ()
{
  if (p) {
    p->m_pause = true;
  }
}
References p.
resume()
void Slic3r::GUI::FileGet::resume ()
{
  assert(p);
  if (p->m_io_thread.joinable()) {
    // This will stop transfers being done by the thread, if any.
    // Cancelling takes some time, but should complete soon enough.
    p->m_cancel = true;
    p->m_io_thread.join();
  }
  p->m_cancel = false;
  p->m_pause = false;
  p->m_io_thread = std::thread([this]() {
    p->get_perform();
    });
}
References p.
Member Data Documentation
p
std::unique_ptr<priv> Slic3r::GUI::FileGet::p private
Referenced by ~FileGet(), cancel(), get(), pause(), and resume().
The documentation for this class was generated from the following files:
src/slic3r/GUI/DownloaderFileGet.hpp
src/slic3r/GUI/DownloaderFileGet.cpp