Prusa Slicer: src/avrdude/lexer.c File Reference
lexer.c File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "config.h"
#include "config_gram.h"
#include <unistd.h>
Classes
struct yy_buffer_state
struct yy_trans_info
Macros
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define SIZE_MAX (~(size_t)0)
#define yyconst const
#define yynoreturn
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
#define BEGIN (yy_start) = 1 + 2 *
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE yyrestart(yyin)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_SIZE_T
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)
#define yyless(n)
#define unput(c) yyunput(c, (yytext_ptr))
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER)
#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define yytext_ptr yytext
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 156
#define YY_END_OF_BUFFER 157
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YYERRCODE 256
#define INITIAL 0
#define strng 1
#define incl 2
#define comment 3
#define YY_EXTRA_TYPE void *
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(yytext, (size_t) yyleng, 1, yyout)) {} } while (0)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
#define YY_DECL_IS_OURS 1
#define YY_DECL int yylex (void)
#define YY_USER_ACTION
#define YY_BREAK /*LINTED*/break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef flex_uint8_t YY_CHAR
typedef int yy_state_type
Functions
void yyrestart (FILE *input_file)
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
YY_BUFFER_STATE yy_create_buffer (FILE *file, int size)
void yy_delete_buffer (YY_BUFFER_STATE b)
void yy_flush_buffer (YY_BUFFER_STATE b)
void yypush_buffer_state (YY_BUFFER_STATE new_buffer)
void yypop_buffer_state (void)
static void yyensure_buffer_stack (void)
static void yy_load_buffer_state (void)
static void yy_init_buffer (YY_BUFFER_STATE b, FILE *file)
YY_BUFFER_STATE yy_scan_buffer (char *base, yy_size_t size)
YY_BUFFER_STATE yy_scan_string (const char *yy_str)
YY_BUFFER_STATE yy_scan_bytes (const char *bytes, int len)
void * yyalloc (yy_size_t)
void * yyrealloc (void *, yy_size_t)
void yyfree (void *)
static yy_state_type yy_get_previous_state (void)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state)
static int yy_get_next_buffer (void)
static void yynoreturn yy_fatal_error (const char *msg)
static int yy_init_globals (void)
int yylex_destroy (void)
int yyget_debug (void)
void yyset_debug (int debug_flag)
YY_EXTRA_TYPE yyget_extra (void)
void yyset_extra (YY_EXTRA_TYPE user_defined)
FILE * yyget_in (void)
void yyset_in (FILE *_in_str)
FILE * yyget_out (void)
void yyset_out (FILE *_out_str)
int yyget_leng (void)
char * yyget_text (void)
int yyget_lineno (void)
void yyset_lineno (int _line_number)
int yywrap (void)
static int input (void)
int yylex (void)
if (!(yy_init))
Variables
int yyleng
FILE * yyin = NULL
FILE * yyout = NULL
static size_t yy_buffer_stack_top = 0
static size_t yy_buffer_stack_max = 0
static YY_BUFFER_STATE * yy_buffer_stack = NULL
static char yy_hold_char
static int yy_n_chars
static char * yy_c_buf_p = NULL
static int yy_init = 0
static int yy_start = 0
static int yy_did_buffer_switch_on_eof
int yylineno = 1
char * yytext
static const flex_int16_t yy_accept [877]
static const YY_CHAR yy_ec [256]
static const YY_CHAR yy_meta [52]
static const flex_int16_t yy_base [885]
static const flex_int16_t yy_def [885]
static const flex_int16_t yy_nxt [1032]
static const flex_int16_t yy_chk [1032]
static yy_state_type yy_last_accepting_state
static char * yy_last_accepting_cpos
int yy_flex_debug = 0
YY_DECL
char * yy_cp
char * yy_bp
int yy_act
Class Documentation
yy_buffer_state
struct yy_buffer_state
Class Members
int yy_at_bol
int yy_bs_column
The column count.
int yy_bs_lineno
The line count.
char * yy_buf_pos
int yy_buf_size
int yy_buffer_status
char * yy_ch_buf
int yy_fill_buffer
FILE * yy_input_file
int yy_is_interactive
int yy_is_our_buffer
int yy_n_chars
yy_trans_info
struct yy_trans_info
Class Members
flex_int32_t yy_nxt
flex_int32_t yy_verify
Macro Definition Documentation
BEGIN
#define BEGIN (yy_start) = 1 + 2 *
comment
#define comment 3
ECHO
#define ECHO do { if (fwrite(yytext, (size_t) yyleng, 1, yyout)) {} } while (0)
EOB_ACT_CONTINUE_SCAN
#define EOB_ACT_CONTINUE_SCAN 0
EOB_ACT_END_OF_FILE
#define EOB_ACT_END_OF_FILE 1
EOB_ACT_LAST_MATCH
#define EOB_ACT_LAST_MATCH 2
FLEX_SCANNER
#define FLEX_SCANNER
FLEXINT_H
#define FLEXINT_H
incl
#define incl 2
INITIAL
#define INITIAL 0
INT16_MAX
#define INT16_MAX (32767)
INT16_MIN
#define INT16_MIN (-32767-1)
INT32_MAX
#define INT32_MAX (2147483647)
INT32_MIN
#define INT32_MIN (-2147483647-1)
INT8_MAX
#define INT8_MAX (127)
INT8_MIN
#define INT8_MIN (-128)
REJECT
#define REJECT reject_used_but_not_detected
SIZE_MAX
#define SIZE_MAX (~(size_t)0)
strng
#define strng 1
UINT16_MAX
#define UINT16_MAX (65535U)
UINT32_MAX
#define UINT32_MAX (4294967295U)
UINT8_MAX
#define UINT8_MAX (255U)
unput
#define unput (c) yyunput(c, (yytext_ptr))
YY_AT_BOL
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
YY_BREAK
#define YY_BREAK /*LINTED*/break;
YY_BUF_SIZE
#define YY_BUF_SIZE 16384
YY_BUFFER_EOF_PENDING
#define YY_BUFFER_EOF_PENDING 2
YY_BUFFER_NEW
#define YY_BUFFER_NEW 0
YY_BUFFER_NORMAL
#define YY_BUFFER_NORMAL 1
YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER
Value:
                          ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
YY_CURRENT_BUFFER_LVALUE
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
YY_DECL
#define YY_DECL int yylex (void)
YY_DECL_IS_OURS
#define YY_DECL_IS_OURS 1
YY_DO_BEFORE_ACTION
#define YY_DO_BEFORE_ACTION
Value:
  (yytext_ptr) = yy_bp; \
  yyleng = (int) (yy_cp - yy_bp); \
  (yy_hold_char) = *yy_cp; \
  *yy_cp = '\0'; \
  (yy_c_buf_p) = yy_cp;
YY_END_OF_BUFFER
#define YY_END_OF_BUFFER 157
YY_END_OF_BUFFER_CHAR
#define YY_END_OF_BUFFER_CHAR 0
YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
YY_FATAL_ERROR
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg)
YY_FLEX_MAJOR_VERSION
#define YY_FLEX_MAJOR_VERSION 2
YY_FLEX_MINOR_VERSION
#define YY_FLEX_MINOR_VERSION 6
YY_FLEX_SUBMINOR_VERSION
#define YY_FLEX_SUBMINOR_VERSION 4
YY_FLUSH_BUFFER
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER)
YY_INPUT
#define YY_INPUT (buf, result, max_size)
Value:
  if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
    { \
    int c = '*'; \
    int n; \
    for ( n = 0; n < max_size && \
           (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
      buf[n] = (char) c; \
    if ( c == '\n' ) \
      buf[n++] = (char) c; \
    if ( c == EOF && ferror( yyin ) ) \
      YY_FATAL_ERROR( "input in flex scanner failed" ); \
    result = n; \
    } \
  else \
    { \
    errno=0; \
    while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
      { \
      if( errno != EINTR) \
        { \
        YY_FATAL_ERROR( "input in flex scanner failed" ); \
        break; \
        } \
      errno=0; \
      clearerr(yyin); \
      } \
    }\
\
YY_INT_ALIGNED
#define YY_INT_ALIGNED short int
YY_LESS_LINENO
#define YY_LESS_LINENO (n)
YY_LINENO_REWIND_TO
#define YY_LINENO_REWIND_TO (ptr)
YY_MORE_ADJ
#define YY_MORE_ADJ 0
yy_new_buffer
#define yy_new_buffer yy_create_buffer
YY_NEW_FILE
#define YY_NEW_FILE yyrestart(yyin)
YY_NULL
#define YY_NULL 0
YY_NUM_RULES
#define YY_NUM_RULES 156
YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
YY_RESTORE_YY_MORE_OFFSET
#define YY_RESTORE_YY_MORE_OFFSET
YY_RULE_SETUP
#define YY_RULE_SETUP YY_USER_ACTION
YY_SC_TO_UI
#define YY_SC_TO_UI (c) ((YY_CHAR) (c))
yy_set_bol
#define yy_set_bol (at_bol)
Value:
  { \
  if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
    YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
  } \
  YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
  }
yy_set_interactive
#define yy_set_interactive (is_interactive)
Value:
  { \
  if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
    YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
  } \
  YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
  }
YY_START
#define YY_START (((yy_start) - 1) / 2)
YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
YY_STATE_BUF_SIZE
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
YY_STATE_EOF
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
YY_USER_ACTION
#define YY_USER_ACTION
yyconst
#define yyconst const
YYERRCODE
#define YYERRCODE 256
yyless [1/2]
#define yyless (n)
Value:
  do \
    { \
    /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
    *yy_cp = (yy_hold_char); \
    YY_RESTORE_YY_MORE_OFFSET \
    (yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
    YY_DO_BEFORE_ACTION; /* set up yytext again */ \
    } \
  while ( 0 )
yyless [2/2]
#define yyless (n)
Value:
  do \
    { \
    /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
    yytext[yyleng] = (yy_hold_char); \
    (yy_c_buf_p) = yytext + yyless_macro_arg; \
    (yy_hold_char) = *(yy_c_buf_p); \
    *(yy_c_buf_p) = '\0'; \
    yyleng = yyless_macro_arg; \
    } \
  while ( 0 )
yymore
#define yymore () yymore_used_but_not_detected
yynoreturn
#define yynoreturn
YYSTATE
#define YYSTATE YY_START
YYTABLES_NAME
#define YYTABLES_NAME "yytables"
yyterminate
#define yyterminate () return YY_NULL
yytext_ptr
#define yytext_ptr yytext
Typedef Documentation
flex_int16_t
typedef short int flex_int16_t
flex_int32_t
typedef int flex_int32_t
flex_int8_t
typedef signed char flex_int8_t
flex_uint16_t
typedef unsigned short int flex_uint16_t
flex_uint32_t
typedef unsigned int flex_uint32_t
flex_uint8_t
typedef unsigned char flex_uint8_t
YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE
YY_CHAR
typedef flex_uint8_t YY_CHAR
yy_size_t
typedef size_t yy_size_t
yy_state_type
typedef int yy_state_type
Function Documentation
if()
if (! yy_init)
    {
    (yy_init) = 1;
#ifdef YY_USER_INIT
    YY_USER_INIT;
#endif
    if ( ! (yy_start) )
      (yy_start) = 1; /* first start state */
    if ( ! yyin )
      yyin = stdin;
    if ( ! yyout )
      yyout = stdout;
    if ( ! YY_CURRENT_BUFFER ) {
      yyensure_buffer_stack ();
      YY_CURRENT_BUFFER_LVALUE =
        yy_create_buffer( yyin, YY_BUF_SIZE );
    }
    yy_load_buffer_state(  );
    }
References YY_BUF_SIZE, yy_create_buffer(), YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init, yy_load_buffer_state(), yy_start, yyensure_buffer_stack(), yyin, and yyout.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::sla::BranchingTreeBuilder::build_subtree(), Slic3r::GUI::create_freq_settings_popupmenu(), Slic3r::AppUpdater::priv::download_file(), Slic3r::GUI::Field::PostInitialize(), Slic3r::SpiralVase::process_layer(), Slic3r::sla::DefaultSupportTree::routing_to_model(), and Slic3r::AvrDude::run().
input()
static int input (void) static
Referenced by Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), anonymous_namespace{RaycastManager.cpp}::actualize(), Slic3r::sla::DefaultSupportTree::add_pinheads(), Slic3r::apply_arrange_polys(), Slic3r::arrange_objects(), Slic3r::sla::anonymous_namespace{Pad.cpp}::breakstick_holes(), Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::build(), Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::build(), Slic3r::AABBTreeLines::build_aabb_tree_over_indexed_lines(), Slic3r::AABBTreeIndirect::build_aabb_tree_over_indexed_triangle_set(), Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::build_modify_input(), Slic3r::KDTreeIndirect< ANumDimensions, ACoordType, ACoordinateFn >::build_recursive(), Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::build_recursive(), priv::check(), priv::check(), priv::check(), priv::check(), priv::check(), priv::check(), Slic3r::Geometry::circle_center_taubin_newton(), Slic3r::Geometry::circle_center_taubin_newton(), Slic3r::Geometry::circle_ransac(), Slic3r::Geometry::circle_taubin_newton(), Slic3r::ClipperPaths_to_Slic3rExPolygons(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert(), Slic3r::SLAPrintObject::SupportData::create_pad(), Slic3r::SLAPrintObject::SupportData::create_support_tree(), Slic3r::sla::deepsearch_ground_connection(), Slic3r::GUI::GLGizmoEmboss::draw_text_input(), Slic3r::elephant_foot_compensation(), Slic3r::elephant_foot_compensation(), Slic3r::elephant_foot_compensation(), Slic3r::FFFTreeSupport::ensure_maximum_distance_polyline(), igl::example_fun(), priv::finalize(), Slic3r::fix_after_inner_offset(), Slic3r::fix_after_outer_offset(), Slic3r::get_arrange_polys(), Slic3r::GUI::AppUpdateDownloadDialog::get_download_path(), Slic3r::Arachne::WallToolPaths::getRegionOrder(), ImGui::IsActiveIdUsingNavInput(), Eigen::loadMarket(), Slic3r::sla::optimize_anchor_placement(), Slic3r::sla::optimize_pinhead_placement(), Slic3r::KDTreeIndirect< ANumDimensions, ACoordType, ACoordinateFn >::partition_input(), Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::partition_input(), Slic3r::PressureEqualizer::process_layer(), Eigen::internal::simplicial_cholesky_grab_input< CholMatrixType, InputMatrixType >::run(), Eigen::internal::simplicial_cholesky_grab_input< MatrixType, MatrixType >::run(), Slic3r::sla::search_ground_route(), Slic3r::sla::search_widening_path(), stb_decompress_length(), terminal_get_input(), ClipperLib::TranslatePath(), and Slic3r::GUI::SplashScreen::word_wrap_string().
yy_create_buffer()
YY_BUFFER_STATE yy_create_buffer (FILE * file, int size)
Referenced by if().
yy_delete_buffer()
void yy_delete_buffer (YY_BUFFER_STATE b)
yy_fatal_error()
static void yynoreturn yy_fatal_error (const char * msg) static
yy_flush_buffer()
void yy_flush_buffer (YY_BUFFER_STATE b)
yy_get_next_buffer()
static int yy_get_next_buffer (void) static
yy_get_previous_state()
static yy_state_type yy_get_previous_state (void) static
yy_init_buffer()
static void yy_init_buffer (YY_BUFFER_STATE b, FILE * file) static
yy_init_globals()
static int yy_init_globals (void) static
yy_load_buffer_state()
static void yy_load_buffer_state (void) static
Referenced by if().
yy_scan_buffer()
YY_BUFFER_STATE yy_scan_buffer (char * base, yy_size_t size)
yy_scan_bytes()
YY_BUFFER_STATE yy_scan_bytes (const char * bytes, int len)
yy_scan_string()
YY_BUFFER_STATE yy_scan_string (const char * yy_str)
yy_switch_to_buffer()
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
yy_try_NUL_trans()
static yy_state_type yy_try_NUL_trans (yy_state_type current_state) static
yyalloc()
void * yyalloc (yy_size_t)
yyensure_buffer_stack()
static void yyensure_buffer_stack (void) static
Referenced by if().
yyfree()
void yyfree (void *)
yyget_debug()
int yyget_debug (void)
yyget_extra()
YY_EXTRA_TYPE yyget_extra (void)
yyget_in()
FILE * yyget_in (void)
yyget_leng()
int yyget_leng (void)
yyget_lineno()
int yyget_lineno (void)
yyget_out()
FILE * yyget_out (void)
yyget_text()
char * yyget_text (void)
yylex()
int yylex (void)
 {SIGN}*{DIGIT}+            { yylval = number(yytext); return TKN_NUMBER; }
#{SIGN}*{DIGIT}+"."{DIGIT}* { yylval = number_real(yytext); return TKN_NUMBER_REAL; }
#{SIGN}*"."{DIGIT}*         { yylval = number_real(yytext); return TKN_NUMBER_REAL; }
{DIGIT}+            { yylval = number(yytext); return TKN_NUMBER; }
{DIGIT}+"."{DIGIT}* { yylval = number_real(yytext); return TKN_NUMBER_REAL; }
"."{DIGIT}+         { yylval = number_real(yytext); return TKN_NUMBER_REAL; }
"\""      { string_buf_ptr = string_buf; BEGIN(strng); }
0x{HEXDIGIT}+ { yylval = hexnumber(yytext); return TKN_NUMBER; }
#   { /* The following eats '#' style comments to end of line */
       BEGIN(comment); }
yylex_destroy()
int yylex_destroy (void)
yypop_buffer_state()
void yypop_buffer_state (void)
yypush_buffer_state()
void yypush_buffer_state (YY_BUFFER_STATE new_buffer)
yyrealloc()
void * yyrealloc (void * , yy_size_t)
yyrestart()
void yyrestart (FILE * input_file)
yyset_debug()
void yyset_debug (int debug_flag)
yyset_extra()
void yyset_extra (YY_EXTRA_TYPE user_defined)
yyset_in()
void yyset_in (FILE * _in_str)
yyset_lineno()
void yyset_lineno (int _line_number)
yyset_out()
void yyset_out (FILE * _out_str)
yywrap()
int yywrap (void)
{
  return 1;
}
Variable Documentation
yy_accept
const flex_int16_t yy_accept[877] static
yy_act
int yy_act
yy_base
const flex_int16_t yy_base[885] static
yy_bp
char * yy_bp
yy_buffer_stack
YY_BUFFER_STATE* yy_buffer_stack = NULL static
Stack as an array.
yy_buffer_stack_max
size_t yy_buffer_stack_max = 0 static
capacity of stack.
yy_buffer_stack_top
size_t yy_buffer_stack_top = 0 static
index of top of stack.
yy_c_buf_p
char* yy_c_buf_p = NULL static
yy_chk
const flex_int16_t yy_chk[1032] static
yy_cp
char* yy_cp
YY_DECL
YY_DECL
Initial value:
{
  yy_state_type yy_current_state
The main scanner function which does all the work.
yy_def
const flex_int16_t yy_def[885] static
yy_did_buffer_switch_on_eof
int yy_did_buffer_switch_on_eof static
yy_ec
const YY_CHAR yy_ec[256] static
yy_flex_debug
int yy_flex_debug = 0
yy_hold_char
char yy_hold_char static
yy_init
int yy_init = 0 static
Referenced by if().
yy_last_accepting_cpos
char* yy_last_accepting_cpos static
yy_last_accepting_state
yy_state_type yy_last_accepting_state static
yy_meta
const YY_CHAR yy_meta[52] static
Initial value:
=
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    3,    1,
        4,    1,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    6,    2,    1,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    1,    1,
        1
    }
yy_n_chars
int yy_n_chars static
yy_nxt
const flex_int16_t yy_nxt[1032] static
yy_start
int yy_start = 0 static
Referenced by if().
yyin
FILE* yyin = NULL
Referenced by if(), and read_config().
yyleng
int yyleng
yylineno
int yylineno = 1
yyout
FILE * yyout = NULL
Referenced by if().
yytext
char* yytext
Referenced by pyytext().