Prusa Slicer: ImGuiLastItemDataBackup Struct Reference
ImGuiLastItemDataBackup Struct Reference
#include <src/imgui/imgui_internal.h>
Public Member Functions
ImGuiLastItemDataBackup ()
void Backup ()
void Restore () const
Public Attributes
ImGuiID LastItemId
ImGuiItemStatusFlags LastItemStatusFlags
ImRect LastItemRect
ImRect LastItemDisplayRect
Detailed Description
Constructor & Destructor Documentation
ImGuiLastItemDataBackup()
ImGuiLastItemDataBackup::ImGuiLastItemDataBackup () inline
{ Backup(); }
References Backup().
Member Function Documentation
Backup()
void ImGuiLastItemDataBackup::Backup () inline
{ ImGuiWindow* window = GImGui->CurrentWindow; LastItemId = window->DC.LastItemId; LastItemStatusFlags = window->DC.LastItemStatusFlags; LastItemRect = window->DC.LastItemRect; LastItemDisplayRect = window->DC.LastItemDisplayRect; }
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, ImGuiWindowTempData::LastItemDisplayRect, LastItemDisplayRect, ImGuiWindowTempData::LastItemId, LastItemId, ImGuiWindowTempData::LastItemRect, LastItemRect, ImGuiWindowTempData::LastItemStatusFlags, and LastItemStatusFlags.
Referenced by ImGuiLastItemDataBackup().
Restore()
void ImGuiLastItemDataBackup::Restore () const inline
{ ImGuiWindow* window = GImGui->CurrentWindow; window->DC.LastItemId = LastItemId; window->DC.LastItemStatusFlags = LastItemStatusFlags; window->DC.LastItemRect = LastItemRect; window->DC.LastItemDisplayRect = LastItemDisplayRect; }
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, ImGuiWindowTempData::LastItemDisplayRect, LastItemDisplayRect, ImGuiWindowTempData::LastItemId, LastItemId, ImGuiWindowTempData::LastItemRect, LastItemRect, ImGuiWindowTempData::LastItemStatusFlags, and LastItemStatusFlags.
Referenced by ImGui::CollapsingHeader(), and ImGui::TabItemLabelAndCloseButton().
Member Data Documentation
LastItemDisplayRect
ImRect ImGuiLastItemDataBackup::LastItemDisplayRect
Referenced by Backup(), and Restore().
LastItemId
ImGuiID ImGuiLastItemDataBackup::LastItemId
Referenced by Backup(), and Restore().
LastItemRect
ImRect ImGuiLastItemDataBackup::LastItemRect
Referenced by Backup(), and Restore().
LastItemStatusFlags
ImGuiItemStatusFlags ImGuiLastItemDataBackup::LastItemStatusFlags
Referenced by Backup(), and Restore().
The documentation for this struct was generated from the following file:
src/imgui/imgui_internal.h