Prusa Slicer: ExampleAppLog Struct Reference
ExampleAppLog Struct Reference
Public Member Functions
ExampleAppLog ()
void Clear ()
void AddLog (const char *fmt,...) IM_FMTARGS(2)
void Draw (const char *title, bool *p_open=NULL)
Public Attributes
ImGuiTextBuffer Buf
ImGuiTextFilter Filter
ImVector< int > LineOffsets
bool AutoScroll
Detailed Description
Constructor & Destructor Documentation
ExampleAppLog()
ExampleAppLog::ExampleAppLog () inline
    {
        AutoScroll = true;
        Clear();
    }
References AutoScroll, and Clear().
Member Function Documentation
AddLog()
void ExampleAppLog::AddLog (const char * fmt, ...) inline
    {
        int old_size = Buf.size();
        va_list args;
        va_start(args, fmt);
        Buf.appendfv(fmt, args);
        va_end(args);
        for (int new_size = Buf.size(); old_size < new_size; old_size++)
            if (Buf[old_size] == '\n')
                LineOffsets.push_back(old_size + 1);
    }
References ImGuiTextBuffer::appendfv(), Buf, LineOffsets, ImVector< T >::push_back(), and ImGuiTextBuffer::size().
Clear()
void ExampleAppLog::Clear () inline
    {
        Buf.clear();
        LineOffsets.clear();
        LineOffsets.push_back(0);
    }
References Buf, ImVector< T >::clear(), ImGuiTextBuffer::clear(), LineOffsets, and ImVector< T >::push_back().
Referenced by ExampleAppLog(), and Draw().
Draw()
void ExampleAppLog::Draw (const char * title, bool * p_open = NULL) inline
    {
        if (!ImGui::Begin(title, p_open))
        {
            ImGui::End();
            return;
        }
        // Options menu
        if (ImGui::BeginPopup("Options"))
        {
            ImGui::Checkbox("Auto-scroll", &AutoScroll);
            ImGui::EndPopup();
        }
        // Main window
        if (ImGui::Button("Options"))
            ImGui::OpenPopup("Options");
        ImGui::SameLine();
        bool clear = ImGui::Button("Clear");
        ImGui::SameLine();
        bool copy = ImGui::Button("Copy");
        ImGui::SameLine();
        Filter.Draw("Filter", -100.0f);
        ImGui::Separator();
        ImGui::BeginChild("scrolling", ImVec2(0, 0), false, ImGuiWindowFlags_HorizontalScrollbar);
        if (clear)
            Clear();
        if (copy)
            ImGui::LogToClipboard();
        ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));
        const char* buf = Buf.begin();
        const char* buf_end = Buf.end();
        if (Filter.IsActive())
        {
            // In this example we don't use the clipper when Filter is enabled.
            // This is because we don't have a random access on the result on our filter.
            // A real application processing logs with ten of thousands of entries may want to store the result of
            // search/filter.. especially if the filtering function is not trivial (e.g. reg-exp).
            for (int line_no = 0; line_no < LineOffsets.Size; line_no++)
            {
                const char* line_start = buf + LineOffsets[line_no];
                const char* line_end = (line_no + 1 < LineOffsets.Size) ? (buf + LineOffsets[line_no + 1] - 1) : buf_end;
                if (Filter.PassFilter(line_start, line_end))
                    ImGui::TextUnformatted(line_start, line_end);
            }
        }
        else
        {
            // The simplest and easy way to display the entire buffer:
            //   ImGui::TextUnformatted(buf_begin, buf_end);
            // And it'll just work. TextUnformatted() has specialization for large blob of text and will fast-forward
            // to skip non-visible lines. Here we instead demonstrate using the clipper to only process lines that are
            // within the visible area.
            // If you have tens of thousands of items and their processing cost is non-negligible, coarse clipping them
            // on your side is recommended. Using ImGuiListClipper requires
            // - A) random access into your data
            // - B) items all being the  same height,
            // both of which we can handle since we an array pointing to the beginning of each line of text.
            // When using the filter (in the block of code above) we don't have random access into the data to display
            // anymore, which is why we don't use the clipper. Storing or skimming through the search result would make
            // it possible (and would be recommended if you want to search through tens of thousands of entries).
            ImGuiListClipper clipper;
            clipper.Begin(LineOffsets.Size);
            while (clipper.Step())
            {
                for (int line_no = clipper.DisplayStart; line_no < clipper.DisplayEnd; line_no++)
                {
                    const char* line_start = buf + LineOffsets[line_no];
                    const char* line_end = (line_no + 1 < LineOffsets.Size) ? (buf + LineOffsets[line_no + 1] - 1) : buf_end;
                    ImGui::TextUnformatted(line_start, line_end);
                }
            }
            clipper.End();
        }
        ImGui::PopStyleVar();
        if (AutoScroll && ImGui::GetScrollY() >= ImGui::GetScrollMaxY())
            ImGui::SetScrollHereY(1.0f);
        ImGui::EndChild();
        ImGui::End();
    }
References AutoScroll, ImGuiTextBuffer::begin(), ImGui::Begin(), ImGuiListClipper::Begin(), ImGui::BeginChild(), ImGui::BeginPopup(), Buf, ImGui::Button(), ImGui::Checkbox(), Clear(), ImGuiListClipper::DisplayEnd, ImGuiListClipper::DisplayStart, ImGuiTextFilter::Draw(), ImGui::End(), ImGuiListClipper::End(), ImGuiTextBuffer::end(), ImGui::EndChild(), ImGui::EndPopup(), Filter, ImGui::GetScrollMaxY(), ImGui::GetScrollY(), ImGuiStyleVar_ItemSpacing, ImGuiWindowFlags_HorizontalScrollbar, ImGuiTextFilter::IsActive(), LineOffsets, ImGui::LogToClipboard(), ImGui::OpenPopup(), ImGuiTextFilter::PassFilter(), ImGui::PopStyleVar(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::Separator(), ImGui::SetScrollHereY(), ImVector< T >::Size, ImGuiListClipper::Step(), and ImGui::TextUnformatted().
Member Data Documentation
AutoScroll
bool ExampleAppLog::AutoScroll
Referenced by ExampleAppLog(), and Draw().
Buf
ImGuiTextBuffer ExampleAppLog::Buf
Referenced by AddLog(), Clear(), and Draw().
Filter
ImGuiTextFilter ExampleAppLog::Filter
Referenced by Draw().
LineOffsets
ImVector<int> ExampleAppLog::LineOffsets
Referenced by AddLog(), Clear(), and Draw().
The documentation for this struct was generated from the following file:
src/imgui/imgui_demo.cpp