Prusa Slicer: Slic3r::GUI::Emboss::CreateFontStyleImagesJob Class Reference
Slic3r::GUI::Emboss::CreateFontStyleImagesJob Class Reference
Create texture with name of styles written by its style NOTE: Access to glyph cache is possible only from job.
#include <src/slic3r/GUI/Jobs/CreateFontStyleImagesJob.hpp>
Public Member Functions
CreateFontStyleImagesJob (StyleManager::StyleImagesData &&input)
void process (Ctl &ctl) override
void finalize (bool canceled, std::exception_ptr &) override
Private Attributes
StyleManager::StyleImagesData m_input
int m_width
int m_height
std::vector< unsigned char > m_pixels
std::vector< StyleManager::StyleImage > m_images
Detailed Description
Create texture with name of styles written by its style NOTE: Access to glyph cache is possible only from job.
Constructor & Destructor Documentation
CreateFontStyleImagesJob()
CreateFontStyleImagesJob::CreateFontStyleImagesJob (StyleManager::StyleImagesData && input)
    : m_input(std::move(input)), m_width(0), m_height(0)
{
    assert(m_input.result != nullptr);
    assert(!m_input.styles.empty());
    assert(!m_input.text.empty());
    assert(m_input.max_size.x() > 1);
    assert(m_input.max_size.y() > 1);
    assert(m_input.ppm > 1e-5);
}
References m_input, Slic3r::GUI::Emboss::StyleManager::StyleImagesData::max_size, Slic3r::GUI::Emboss::StyleManager::StyleImagesData::ppm, Slic3r::GUI::Emboss::StyleManager::StyleImagesData::result, Slic3r::GUI::Emboss::StyleManager::StyleImagesData::styles, and Slic3r::GUI::Emboss::StyleManager::StyleImagesData::text.
Member Function Documentation
finalize()
void CreateFontStyleImagesJob::finalize (bool canceled, std::exception_ptr &) override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (canceled) return;
    // upload texture on GPU
    GLuint tex_id;
    GLenum target = GL_TEXTURE_2D, format = GL_RGBA, type = GL_UNSIGNED_BYTE;
    GLint  level = 0, border = 0;
    glsafe(::glGenTextures(1, &tex_id));
    glsafe(::glBindTexture(target, tex_id));
    glsafe(::glTexParameteri(target, GL_TEXTURE_MIN_FILTER, GL_NEAREST));
    glsafe(::glTexParameteri(target, GL_TEXTURE_MAG_FILTER, GL_NEAREST));
    GLint w = m_width, h = m_height;
    glsafe(::glTexImage2D(target, level, GL_RGBA, w, h, border, format, type,
                          (const void *) m_pixels.data()));
    // set up texture id
    void *texture_id = (void *) (intptr_t) tex_id;
    for (StyleManager::StyleImage &image : m_images)
        image.texture_id = texture_id;
    // move to result
    m_input.result->styles = std::move(m_input.styles);
    m_input.result->images = std::move(m_images);
    // bind default texture
    GLuint no_texture_id = 0;
    glsafe(::glBindTexture(target, no_texture_id));
    // show rendered texture
    wxGetApp().plater()->canvas3D()->schedule_extra_frame(0);
}
References Slic3r::GUI::format(), glsafe, m_height, m_images, m_input, m_pixels, m_width, Slic3r::GUI::Emboss::StyleManager::StyleImagesData::result, and Slic3r::GUI::Emboss::StyleManager::StyleImagesData::styles.
process()
void CreateFontStyleImagesJob::process (Ctl & ctl) override virtual
Implements Slic3r::GUI::Job.
{
    // create shapes and calc size (bounding boxes)
    std::vector<ExPolygons> name_shapes(m_input.styles.size());
    std::vector<double> scales(m_input.styles.size());
    m_images = std::vector<StyleManager::StyleImage>(m_input.styles.size());
    for (auto &item : m_input.styles) {
        size_t index = &item - &m_input.styles.front();
        ExPolygons &shapes = name_shapes[index];
        shapes = text2shapes(item.font, m_input.text.c_str(), item.prop);
        // create image description
        StyleManager::StyleImage &image = m_images[index];
        BoundingBox &bounding_box = image.bounding_box;
        for (ExPolygon &shape : shapes)
            bounding_box.merge(BoundingBox(shape.contour.points));
        for (ExPolygon &shape : shapes) shape.translate(-bounding_box.min);
        // calculate conversion from FontPoint to screen pixels by size of font
        const auto  &cn  = item.prop.collection_number;
        unsigned int font_index  = (cn.has_value()) ? *cn : 0;
        double unit_per_em = item.font.font_file->infos[font_index].unit_per_em;
        double scale = item.prop.size_in_mm / unit_per_em * SHAPE_SCALE * m_input.ppm;
        scales[index] = scale;
        //double scale = font_prop.size_in_mm * SCALING_FACTOR;
        BoundingBoxf bb2(bounding_box.min.cast<double>(),
                         bounding_box.max.cast<double>());
        bb2.scale(scale);
        image.tex_size.x = std::ceil(bb2.max.x() - bb2.min.x());
        image.tex_size.y = std::ceil(bb2.max.y() - bb2.min.y());
        // crop image width
        if (image.tex_size.x > m_input.max_size.x())
            image.tex_size.x = m_input.max_size.x();
        // crop image height
        if (image.tex_size.y > m_input.max_size.y())
            image.tex_size.y = m_input.max_size.y();
    }
    // arrange bounding boxes
    int offset_y = 0;
    m_width      = 0;
    for (StyleManager::StyleImage &image : m_images) {
        image.offset.y() = offset_y;
        offset_y += image.tex_size.y+1;
        if (m_width < image.tex_size.x)
            m_width = image.tex_size.x;
    }
    m_height = offset_y;
    for (StyleManager::StyleImage &image : m_images) {
        const Point &o = image.offset;
        const ImVec2 &s = image.tex_size;
        image.uv0 = ImVec2(o.x() / (double) m_width,
                           o.y() / (double) m_height);
        image.uv1 = ImVec2((o.x() + s.x) / (double) m_width,
                           (o.y() + s.y) / (double) m_height);
    }
    // Set up result
    m_pixels = std::vector<unsigned char>(4 * m_width * m_height, {255});
    // upload sub textures
    for (StyleManager::StyleImage &image : m_images) {
        sla::Resolution resolution(image.tex_size.x, image.tex_size.y);
        size_t index = &image - &m_images.front();
        double pixel_dim = SCALING_FACTOR / scales[index];
        sla::PixelDim dim(pixel_dim, pixel_dim);
        double gamma = 1.;
        std::unique_ptr<sla::RasterBase> r =
            sla::create_raster_grayscale_aa(resolution, dim, gamma);
        for (const ExPolygon &shape : name_shapes[index]) r->draw(shape);
        // copy rastered data to pixels
        sla::RasterEncoder encoder = [&offset = image.offset, &pix = m_pixels, w=m_width,h=m_height]
        (const void *ptr, size_t width, size_t height, size_t num_components) {
            // bigger value create darker image
            unsigned char gray_level = 5;
            size_t size {static_cast<size_t>(w*h)};
            assert((offset.x() + width) <= (size_t)w);
            assert((offset.y() + height) <= (size_t)h);
            const unsigned char *ptr2 = (const unsigned char *) ptr;
            for (size_t x = 0; x < width; ++x)
                for (size_t y = 0; y < height; ++y) {
                    size_t index = (offset.y() + y)*w + offset.x() + x;
                    assert(index < size);
                    if (index >= size) continue;
                    pix[4*index+3] = ptr2[y * width + x] / gray_level;
                }
            return sla::EncodedRaster();
        };
        r->encode(encoder);
    }
}
References Slic3r::bounding_box(), Slic3r::GUI::Emboss::StyleManager::StyleImage::bounding_box, Slic3r::sla::create_raster_grayscale_aa(), m_height, m_images, m_input, m_pixels, m_width, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::GUI::Emboss::StyleManager::StyleImagesData::max_size, Slic3r::BoundingBox3Base< PointType >::merge(), Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::offset(), Slic3r::GUI::Emboss::StyleManager::StyleImagesData::ppm, scale(), Slic3r::BoundingBoxBase< PointType, APointsType >::scale(), SCALING_FACTOR, Slic3r::Emboss::SHAPE_SCALE, Slic3r::GUI::Emboss::StyleManager::StyleImagesData::styles, Slic3r::GUI::Emboss::StyleManager::StyleImage::tex_size, Slic3r::GUI::Emboss::StyleManager::StyleImagesData::text, Slic3r::Emboss::text2shapes(), ImVec2::x, and ImVec2::y.
Member Data Documentation
m_height
int Slic3r::GUI::Emboss::CreateFontStyleImagesJob::m_height private
Referenced by finalize(), and process().
m_images
std::vector<StyleManager::StyleImage> Slic3r::GUI::Emboss::CreateFontStyleImagesJob::m_images private
Referenced by finalize(), and process().
m_input
StyleManager::StyleImagesData Slic3r::GUI::Emboss::CreateFontStyleImagesJob::m_input private
Referenced by CreateFontStyleImagesJob(), finalize(), and process().
m_pixels
std::vector<unsigned char> Slic3r::GUI::Emboss::CreateFontStyleImagesJob::m_pixels private
Referenced by finalize(), and process().
m_width
int Slic3r::GUI::Emboss::CreateFontStyleImagesJob::m_width private
Referenced by finalize(), and process().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/CreateFontStyleImagesJob.hpp
src/slic3r/GUI/Jobs/CreateFontStyleImagesJob.cpp