Prusa Slicer: Slic3r::Linef3 Class Reference
Slic3r::Linef3 Class Reference
#include <src/libslic3r/Line.hpp>
Public Types
using Scalar = Vec3d::Scalar
Public Member Functions
Linef3 ()
Linef3 (const Vec3d &_a, const Vec3d &_b)
Vec3d intersect_plane (double z) const
void scale (double factor)
Vec3d vector () const
Vec3d unit_vector () const
double length () const
Public Attributes
Vec3d a
Vec3d b
Static Public Attributes
static const constexpr int Dim = 3
Detailed Description
Member Typedef Documentation
Scalar
using Slic3r::Linef3::Scalar = Vec3d::Scalar
Constructor & Destructor Documentation
Linef3() [1/2]
Slic3r::Linef3::Linef3 () inline
: a(Vec3d::Zero()), b(Vec3d::Zero()) {}
Linef3() [2/2]
Slic3r::Linef3::Linef3 (const Vec3d & _a, const Vec3d & _b) inline
: a(_a), b(_b) {}
Member Function Documentation
intersect_plane()
Vec3d Slic3r::Linef3::intersect_plane (double z) const
{
    auto   v = (this->b - this->a).cast<double>();
    double t = (z - this->a(2)) / v(2);
    return Vec3d(this->a(0) + v(0) * t, this->a(1) + v(1) * t, z);
}
References a, b, and vector().
Referenced by Slic3r::GUI::GLCanvas3D::_mouse_to_bed_3d(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), Slic3r::GUI::GLGizmoCut3D::mouse_position_in_local_plane(), and Slic3r::GUI::GLCanvas3D::on_mouse().
length()
double Slic3r::Linef3::length () const inline
{ return vector().norm(); }
References vector().
Referenced by unit_vector().
scale()
void Slic3r::Linef3::scale (double factor) inline
{ this->a *= factor; this->b *= factor; }
References a, and b.
Referenced by Slic3r::Geometry::assemble_transform(), and Slic3r::Geometry::scale_transform().
unit_vector()
Vec3d Slic3r::Linef3::unit_vector () const inline
{ return (length() == 0.0) ? Vec3d::Zero() : vector().normalized(); }
References length(), and vector().
Referenced by Slic3r::GUI::GLCanvas3D::_mouse_to_bed_3d(), and Slic3r::GUI::GLCanvas3D::on_mouse().
vector()
Vec3d Slic3r::Linef3::vector () const inline
{ return this->b - this->a; }
References a, and b.
Referenced by intersect_plane(), length(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), and unit_vector().
Member Data Documentation
a
Vec3d Slic3r::Linef3::a
Referenced by Slic3r::GUI::GLCanvas3D::_mouse_to_bed_3d(), intersect_plane(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), Slic3r::GUI::GLCanvas3D::on_mouse(), scale(), Slic3r::transform(), and vector().
b
Vec3d Slic3r::Linef3::b
Referenced by intersect_plane(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), scale(), Slic3r::transform(), and vector().
Dim
const constexpr int Slic3r::Linef3::Dim = 3 static constexpr
The documentation for this class was generated from the following files:
src/libslic3r/Line.hpp
src/libslic3r/Line.cpp