Prusa Slicer: Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings Struct Reference
Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings Struct Reference
#include <src/libslic3r/Support/TreeSupportCommon.hpp>
Public Member Functions
TreeSupportMeshGroupSettings ()=default
TreeSupportMeshGroupSettings (const PrintObject &print_object)
Public Attributes
coord_t layer_height { scaled<coord_t>(0.15) }
coord_t resolution { scaled<coord_t>(0.025) }
coord_t min_feature_size { scaled<coord_t>(0.1) }
double support_angle { 50. * M_PI / 180. }
coord_t support_line_width { scaled<coord_t>(0.4) }
coord_t support_roof_line_width { scaled<coord_t>(0.4) }
bool support_bottom_enable { false }
coord_t support_bottom_height { scaled<coord_t>(1.) }
bool support_material_buildplate_only { false }
coord_t support_xy_distance { scaled<coord_t>(0.7) }
coord_t support_xy_distance_overhang { scaled<coord_t>(0.2) }
coord_t support_top_distance { scaled<coord_t>(0.1) }
coord_t support_bottom_distance { scaled<coord_t>(0.1) }
coord_t support_interface_skip_height { scaled<coord_t>(0.3) }
bool support_roof_enable { false }
coord_t support_roof_layers { 2 }
bool support_floor_enable { false }
coord_t support_floor_layers { 2 }
double minimum_roof_area { scaled<double>(scaled<double>(1.)) }
std::vector< double > support_roof_angles {}
SupportMaterialInterfacePattern support_roof_pattern { smipAuto }
SupportMaterialPattern support_pattern { smpRectilinear }
coord_t support_line_spacing { scaled<coord_t>(2.66 - 0.4) }
coord_t support_bottom_offset { scaled<coord_t>(0.) }
int support_wall_count { 1 }
coord_t support_roof_line_distance { scaled<coord_t>(0.4) }
coord_t minimum_support_area { scaled<coord_t>(0.) }
coord_t minimum_bottom_area { scaled<coord_t>(1.0) }
coord_t support_offset { scaled<coord_t>(0.) }
double support_tree_angle { 60. * M_PI / 180. }
double support_tree_branch_diameter_angle { 5. * M_PI / 180. }
coord_t support_tree_branch_distance { scaled<coord_t>(1.) }
coord_t support_tree_branch_diameter { scaled<coord_t>(2.) }
double support_tree_angle_slow { 50. * M_PI / 180. }
coord_t support_tree_max_diameter_increase_by_merges_when_support_to_model { scaled<coord_t>(1.0) }
coord_t support_tree_min_height_to_model { scaled<coord_t>(1.0) }
coord_t support_tree_bp_diameter { scaled<coord_t>(7.5) }
double support_tree_top_rate { 15. }
coord_t support_tree_tip_diameter { scaled<coord_t>(0.4) }
Detailed Description
Constructor & Destructor Documentation
TreeSupportMeshGroupSettings() [1/2]
Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::TreeSupportMeshGroupSettings () default
TreeSupportMeshGroupSettings() [2/2]
Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::TreeSupportMeshGroupSettings (const PrintObject & print_object) explicit
{
    const PrintConfig       &print_config       = print_object.print()->config();
    const PrintObjectConfig &config             = print_object.config();
    const SlicingParameters &slicing_params     = print_object.slicing_parameters();
//    const std::vector<unsigned int>  printing_extruders = print_object.object_extruders();
    // Support must be enabled and set to Tree style.
    assert(config.support_material || config.support_material_enforce_layers > 0);
    assert(config.support_material_style == smsTree || config.support_material_style == smsOrganic);
    // Calculate maximum external perimeter width over all printing regions, taking into account the default layer height.
    coordf_t external_perimeter_width = 0.;
    for (size_t region_id = 0; region_id < print_object.num_printing_regions(); ++ region_id) {
        const PrintRegion &region = print_object.printing_region(region_id);
        external_perimeter_width = std::max<coordf_t>(external_perimeter_width, region.flow(print_object, frExternalPerimeter, config.layer_height).width());
    }
    this->layer_height              = scaled<coord_t>(config.layer_height.value);
    this->resolution                = scaled<coord_t>(print_config.gcode_resolution.value);
    // Arache feature
    this->min_feature_size          = scaled<coord_t>(config.min_feature_size.value);
    // +1 makes the threshold inclusive
    this->support_angle             = 0.5 * M_PI - std::clamp<double>((config.support_material_threshold + 1) * M_PI / 180., 0., 0.5 * M_PI);
    this->support_line_width        = support_material_flow(&print_object, config.layer_height).scaled_width();
    this->support_roof_line_width   = support_material_interface_flow(&print_object, config.layer_height).scaled_width();
    //FIXME add it to SlicingParameters and reuse in both tree and normal supports?
    this->support_bottom_enable     = config.support_material_interface_layers.value > 0 && config.support_material_bottom_interface_layers.value != 0;
    this->support_bottom_height     = this->support_bottom_enable ?
        (config.support_material_bottom_interface_layers.value > 0 ?
            config.support_material_bottom_interface_layers.value :
            config.support_material_interface_layers.value) * this->layer_height :
        0;
    this->support_material_buildplate_only = config.support_material_buildplate_only;
    this->support_xy_distance       = scaled<coord_t>(config.support_material_xy_spacing.get_abs_value(external_perimeter_width));
    // Separation of interfaces, it is likely smaller than support_xy_distance.
    this->support_xy_distance_overhang = std::min(this->support_xy_distance, scaled<coord_t>(0.5 * external_perimeter_width));
    this->support_top_distance      = scaled<coord_t>(slicing_params.gap_support_object);
    this->support_bottom_distance   = scaled<coord_t>(slicing_params.gap_object_support);
//    this->support_interface_skip_height =
//    this->support_infill_angles     =
    this->support_roof_enable       = config.support_material_interface_layers.value > 0;
    this->support_roof_layers       = this->support_roof_enable ? config.support_material_interface_layers.value : 0;
    this->support_floor_enable      = config.support_material_interface_layers.value > 0 && config.support_material_bottom_interface_layers.value > 0;
    this->support_floor_layers      = this->support_floor_enable ? config.support_material_bottom_interface_layers.value : 0;
//    this->minimum_roof_area         =
//    this->support_roof_angles       =
    this->support_roof_pattern      = config.support_material_interface_pattern;
    this->support_pattern           = config.support_material_pattern;
    this->support_line_spacing      = scaled<coord_t>(config.support_material_spacing.value);
//    this->support_bottom_offset     =
//    this->support_wall_count        = config.support_material_with_sheath ? 1 : 0;
    this->support_wall_count        = 1;
    this->support_roof_line_distance = scaled<coord_t>(config.support_material_interface_spacing.value) + this->support_roof_line_width;
//    this->minimum_support_area      =
//    this->minimum_bottom_area       =
//    this->support_offset            =
    this->support_tree_branch_distance = scaled<coord_t>(config.support_tree_branch_distance.value);
    this->support_tree_angle          = std::clamp<double>(config.support_tree_angle * M_PI / 180., 0., 0.5 * M_PI - EPSILON);
    this->support_tree_angle_slow     = std::clamp<double>(config.support_tree_angle_slow * M_PI / 180., 0., this->support_tree_angle - EPSILON);
    this->support_tree_branch_diameter = scaled<coord_t>(config.support_tree_branch_diameter.value);
    this->support_tree_branch_diameter_angle = std::clamp<double>(config.support_tree_branch_diameter_angle * M_PI / 180., 0., 0.5 * M_PI - EPSILON);
    this->support_tree_top_rate       = config.support_tree_top_rate.value; // percent
//    this->support_tree_tip_diameter = this->support_line_width;
    this->support_tree_tip_diameter = std::clamp(scaled<coord_t>(config.support_tree_tip_diameter.value), 0, this->support_tree_branch_diameter);
}
References Slic3r::PrintObject::config(), Slic3r::Print::config(), EPSILON, Slic3r::PrintRegion::flow(), Slic3r::frExternalPerimeter, Slic3r::SlicingParameters::gap_object_support, Slic3r::SlicingParameters::gap_support_object, layer_height, M_PI, min_feature_size, Slic3r::PrintObject::num_printing_regions(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::print(), Slic3r::PrintObject::printing_region(), Slic3r::PrintObjectConfig, resolution, Slic3r::Flow::scaled_width(), Slic3r::PrintObject::slicing_parameters(), Slic3r::smsOrganic, Slic3r::smsTree, support_angle, support_bottom_distance, support_bottom_enable, support_bottom_height, support_floor_enable, support_floor_layers, support_line_spacing, support_line_width, support_material_buildplate_only, Slic3r::support_material_flow(), Slic3r::support_material_interface_flow(), support_pattern, support_roof_enable, support_roof_layers, support_roof_line_distance, support_roof_line_width, support_roof_pattern, support_top_distance, support_tree_angle, support_tree_angle_slow, support_tree_branch_diameter, support_tree_branch_diameter_angle, support_tree_branch_distance, support_tree_tip_diameter, support_tree_top_rate, support_wall_count, support_xy_distance, support_xy_distance_overhang, and Slic3r::Flow::width().
Member Data Documentation
layer_height
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::layer_height { scaled<coord_t>(0.15) }
Referenced by TreeSupportMeshGroupSettings(), and Slic3r::FFFTreeSupport::TreeModelVolumes::calculateCollision().
min_feature_size
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::min_feature_size { scaled<coord_t>(0.1) }
Referenced by TreeSupportMeshGroupSettings().
minimum_bottom_area
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::minimum_bottom_area { scaled<coord_t>(1.0) }
minimum_roof_area
double Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::minimum_roof_area { scaled<double>(scaled<double>(1.)) }
Referenced by Slic3r::FFFTreeSupport::generate_initial_areas(), and Slic3r::FFFTreeSupport::sample_overhang_area().
minimum_support_area
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::minimum_support_area { scaled<coord_t>(0.) }
resolution
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::resolution { scaled<coord_t>(0.025) }
Referenced by Slic3r::FFFTreeSupport::TreeModelVolumes::TreeModelVolumes(), and TreeSupportMeshGroupSettings().
support_angle
double Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_angle { 50. * M_PI / 180. }
Referenced by TreeSupportMeshGroupSettings(), and Slic3r::FFFTreeSupport::generate_initial_areas().
support_bottom_distance
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_bottom_distance { scaled<coord_t>(0.1) }
Referenced by TreeSupportMeshGroupSettings(), and Slic3r::FFFTreeSupport::TreeModelVolumes::calculateCollision().
support_bottom_enable
bool Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_bottom_enable { false }
Referenced by TreeSupportMeshGroupSettings().
support_bottom_height
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_bottom_height { scaled<coord_t>(1.) }
Referenced by TreeSupportMeshGroupSettings().
support_bottom_offset
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_bottom_offset { scaled<coord_t>(0.) }
support_floor_enable
bool Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_floor_enable { false }
Referenced by TreeSupportMeshGroupSettings().
support_floor_layers
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_floor_layers { 2 }
Referenced by TreeSupportMeshGroupSettings().
support_interface_skip_height
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_interface_skip_height { scaled<coord_t>(0.3) }
support_line_spacing
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_line_spacing { scaled<coord_t>(2.66 - 0.4) }
Referenced by TreeSupportMeshGroupSettings().
support_line_width
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_line_width { scaled<coord_t>(0.4) }
Referenced by TreeSupportMeshGroupSettings().
support_material_buildplate_only
bool Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_material_buildplate_only { false }
Referenced by TreeSupportMeshGroupSettings().
support_offset
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_offset { scaled<coord_t>(0.) }
support_pattern
SupportMaterialPattern Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_pattern { smpRectilinear }
Referenced by TreeSupportMeshGroupSettings().
support_roof_angles
std::vector<double> Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_roof_angles {}
support_roof_enable
bool Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_roof_enable { false }
Referenced by TreeSupportMeshGroupSettings().
support_roof_layers
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_roof_layers { 2 }
Referenced by TreeSupportMeshGroupSettings(), and Slic3r::FFFTreeSupport::generate_initial_areas().
support_roof_line_distance
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_roof_line_distance { scaled<coord_t>(0.4) }
Referenced by TreeSupportMeshGroupSettings(), and Slic3r::FFFTreeSupport::sample_overhang_area().
support_roof_line_width
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_roof_line_width { scaled<coord_t>(0.4) }
Referenced by TreeSupportMeshGroupSettings().
support_roof_pattern
SupportMaterialInterfacePattern Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_roof_pattern { smipAuto }
Referenced by TreeSupportMeshGroupSettings().
support_top_distance
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_top_distance { scaled<coord_t>(0.1) }
Referenced by TreeSupportMeshGroupSettings(), and Slic3r::FFFTreeSupport::TreeModelVolumes::calculateCollision().
support_tree_angle
double Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_angle { 60. * M_PI / 180. }
Referenced by TreeSupportMeshGroupSettings().
support_tree_angle_slow
double Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_angle_slow { 50. * M_PI / 180. }
Referenced by TreeSupportMeshGroupSettings().
support_tree_bp_diameter
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_bp_diameter { scaled<coord_t>(7.5) }
support_tree_branch_diameter
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_branch_diameter { scaled<coord_t>(2.) }
Referenced by TreeSupportMeshGroupSettings().
support_tree_branch_diameter_angle
double Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_branch_diameter_angle { 5. * M_PI / 180. }
Referenced by TreeSupportMeshGroupSettings().
support_tree_branch_distance
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_branch_distance { scaled<coord_t>(1.) }
Referenced by TreeSupportMeshGroupSettings(), and Slic3r::FFFTreeSupport::sample_overhang_area().
support_tree_max_diameter_increase_by_merges_when_support_to_model
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_max_diameter_increase_by_merges_when_support_to_model { scaled<coord_t>(1.0) }
support_tree_min_height_to_model
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_min_height_to_model { scaled<coord_t>(1.0) }
support_tree_tip_diameter
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_tip_diameter { scaled<coord_t>(0.4) }
Referenced by TreeSupportMeshGroupSettings().
support_tree_top_rate
double Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_tree_top_rate { 15. }
Referenced by TreeSupportMeshGroupSettings(), and Slic3r::FFFTreeSupport::generate_initial_areas().
support_wall_count
int Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_wall_count { 1 }
Referenced by TreeSupportMeshGroupSettings().
support_xy_distance
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_xy_distance { scaled<coord_t>(0.7) }
Referenced by TreeSupportMeshGroupSettings(), and Slic3r::FFFTreeSupport::TreeModelVolumes::calculateCollision().
support_xy_distance_overhang
coord_t Slic3r::FFFTreeSupport::TreeSupportMeshGroupSettings::support_xy_distance_overhang { scaled<coord_t>(0.2) }
Referenced by TreeSupportMeshGroupSettings().
The documentation for this struct was generated from the following files:
src/libslic3r/Support/TreeSupportCommon.hpp
src/libslic3r/Support/TreeSupportCommon.cpp