Prusa Slicer: Slic3r::GUI::ManipulationEditor Class Reference
Slic3r::GUI::ManipulationEditor Class Reference
#include <src/slic3r/GUI/GUI_ObjectManipulation.hpp>
Public Member Functions
ManipulationEditor (ObjectManipulation *parent, const std::string &opt_key, int axis)
~ManipulationEditor ()
void msw_rescale ()
void sys_color_changed (ObjectManipulation *parent)
void set_value (const wxString &new_value)
void kill_focus (ObjectManipulation *parent)
const std::string & get_full_opt_name () const
bool has_opt_key (const std::string &key)
Private Member Functions
double get_value ()
Private Attributes
std::string m_opt_key
int m_axis
bool m_enter_pressed { false }
wxString m_valid_value {wxEmptyString}
std::string m_full_opt_name
Detailed Description
Constructor & Destructor Documentation
ManipulationEditor()
Slic3r::GUI::ManipulationEditor::ManipulationEditor (ObjectManipulation * parent, const std::string & opt_key, int axis)
                                                 :
    wxTextCtrl(parent->parent(), wxID_ANY, wxEmptyString, wxDefaultPosition,
        wxSize((wxOSX ? 5 : 6)*int(wxGetApp().em_unit()), wxDefaultCoord), wxTE_PROCESS_ENTER
#ifdef _WIN32
        | wxBORDER_SIMPLE
#endif
    ),
    m_opt_key(opt_key),
    m_axis(axis)
{
    set_font_and_background_style(this, wxGetApp().normal_font());
#ifdef __WXOSX__
    this->OSXDisableAllSmartSubstitutions();
#endif // __WXOSX__
    if (parent->use_colors()) {
        this->SetBackgroundColour(wxColour(axes_color_back[axis]));
        this->SetForegroundColour(*wxBLACK);
    } else {
        wxGetApp().UpdateDarkUI(this);
    }
    // A name used to call handle_sidebar_focus_event()
    m_full_opt_name = m_opt_key+"_"+axes[axis];
    // Reset m_enter_pressed flag to _false_, when value is editing
    this->Bind(wxEVT_TEXT, [this](wxEvent&) { m_enter_pressed = false; }, this->GetId());
    this->Bind(wxEVT_TEXT_ENTER, [this, parent](wxEvent&)
    {
        m_enter_pressed = true;
        parent->on_change(m_opt_key, m_axis, get_value());
    }, this->GetId());
    this->Bind(wxEVT_KILL_FOCUS, [this, parent](wxFocusEvent& e)
    {
        parent->set_focused_editor(nullptr);
        if (!m_enter_pressed)
            kill_focus(parent);
        e.Skip();
    }, this->GetId());
    this->Bind(wxEVT_SET_FOCUS, [this, parent](wxFocusEvent& e)
    {
        parent->set_focused_editor(this);
        // needed to show the visual hints in 3D scene
        wxGetApp().plater()->canvas3D()->handle_sidebar_focus_event(m_full_opt_name, true);
        e.Skip();
    }, this->GetId());
    this->Bind(wxEVT_CHAR, ([this](wxKeyEvent& event)
    {
        // select all text using Ctrl+A
        if (wxGetKeyState(wxKeyCode('A')) && wxGetKeyState(WXK_CONTROL))
            this->SetSelection(-1, -1); //select all
        event.Skip();
    }));
    this->Bind(wxEVT_UPDATE_UI, [parent, this](wxUpdateUIEvent& evt) {
        const bool is_gizmo_in_editing_mode = wxGetApp().plater()->canvas3D()->get_gizmos_manager().is_in_editing_mode();
        const bool is_enabled_editing       = has_opt_key("scale") || has_opt_key("size") ? parent->is_enabled_size_and_scale() : true;
        evt.Enable(!is_gizmo_in_editing_mode && parent->is_enabled() && is_enabled_editing);
    });
}
References Slic3r::GUI::axes, Slic3r::GUI::axes_color_back, get_value(), has_opt_key(), Slic3r::GUI::ObjectManipulation::is_enabled(), Slic3r::GUI::ObjectManipulation::is_enabled_size_and_scale(), kill_focus(), m_axis, m_enter_pressed, m_full_opt_name, m_opt_key, Slic3r::GUI::ObjectManipulation::on_change(), Slic3r::GUI::ObjectManipulation::set_focused_editor(), Slic3r::GUI::set_font_and_background_style(), and Slic3r::GUI::ObjectManipulation::use_colors().
~ManipulationEditor()
Slic3r::GUI::ManipulationEditor::~ManipulationEditor () inline
{}
Member Function Documentation
get_full_opt_name()
const std::string & Slic3r::GUI::ManipulationEditor::get_full_opt_name () const inline
{ return m_full_opt_name; }
References m_full_opt_name.
Referenced by Slic3r::GUI::ObjectList::part_selection_changed().
get_value()
double Slic3r::GUI::ManipulationEditor::get_value () private
{
    wxString str = GetValue();
    double value;
    const char dec_sep = is_decimal_separator_point() ? '.' : ',';
    const char dec_sep_alt = dec_sep == '.' ? ',' : '.';
    // Replace the first incorrect separator in decimal number.
    if (str.Replace(dec_sep_alt, dec_sep, false) != 0)
        SetValue(str);
    if (str == ".")
        value = 0.0;
    if ((str.IsEmpty() || !str.ToDouble(&value)) && !m_valid_value.IsEmpty()) {
        str = m_valid_value;
        SetValue(str);
        str.ToDouble(&value);
    }
    return value;
}
References Slic3r::is_decimal_separator_point(), and m_valid_value.
Referenced by ManipulationEditor(), and kill_focus().
has_opt_key()
bool Slic3r::GUI::ManipulationEditor::has_opt_key (const std::string & key) inline
{ return m_opt_key == key; }
References m_opt_key.
Referenced by ManipulationEditor().
kill_focus()
void Slic3r::GUI::ManipulationEditor::kill_focus (ObjectManipulation * parent)
{
    parent->on_change(m_opt_key, m_axis, get_value());
    // if the change does not come from the user pressing the ENTER key
    // we need to hide the visual hints in 3D scene
    wxGetApp().plater()->canvas3D()->handle_sidebar_focus_event(m_full_opt_name, false);
}
References get_value(), m_axis, m_full_opt_name, m_opt_key, and Slic3r::GUI::ObjectManipulation::on_change().
Referenced by ManipulationEditor(), and Slic3r::GUI::ObjectManipulation::emulate_kill_focus().
msw_rescale()
void Slic3r::GUI::ManipulationEditor::msw_rescale ()
{
    const int em = wxGetApp().em_unit();
    SetMinSize(wxSize(5 * em, wxDefaultCoord));
}
set_value()
void Slic3r::GUI::ManipulationEditor::set_value (const wxString & new_value)
{
    if (new_value.IsEmpty())
        return;
    m_valid_value = new_value;
    SetValue(m_valid_value);
}
References m_valid_value.
sys_color_changed()
void Slic3r::GUI::ManipulationEditor::sys_color_changed (ObjectManipulation * parent)
{
    if (parent->use_colors())
        SetForegroundColour(*wxBLACK);
    else
#ifdef _WIN32
        wxGetApp().UpdateDarkUI(this);
#else
        SetForegroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOWTEXT));
#endif // _WIN32
}
References Slic3r::GUI::ObjectManipulation::use_colors().
Member Data Documentation
m_axis
int Slic3r::GUI::ManipulationEditor::m_axis private
Referenced by ManipulationEditor(), and kill_focus().
m_enter_pressed
bool Slic3r::GUI::ManipulationEditor::m_enter_pressed { false } private
Referenced by ManipulationEditor().
m_full_opt_name
std::string Slic3r::GUI::ManipulationEditor::m_full_opt_name private
Referenced by ManipulationEditor(), get_full_opt_name(), and kill_focus().
m_opt_key
std::string Slic3r::GUI::ManipulationEditor::m_opt_key private
Referenced by ManipulationEditor(), has_opt_key(), and kill_focus().
m_valid_value
wxString Slic3r::GUI::ManipulationEditor::m_valid_value {wxEmptyString} private
Referenced by get_value(), and set_value().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectManipulation.hpp
src/slic3r/GUI/GUI_ObjectManipulation.cpp