Prusa Slicer: src/avrdude/windows/unistd.cpp File Reference
unistd.cpp File Reference
#include "unistd.h"
#include <cstdint>
#include <chrono>
#include <thread>
#include <windows.h>
Functions
int usleep (unsigned usec)
int gettimeofday (struct timeval *tp, struct timezone *tzp)
Function Documentation
gettimeofday()
int gettimeofday (struct timeval * tp, struct timezone * tzp)
{
    // Note: some broken versions only have 8 trailing zero's, the correct epoch has 9 trailing zero's
    // This magic number is the number of 100 nanosecond intervals since January 1, 1601 (UTC)
    // until 00:00:00 January 1, 1970
    static const std::uint64_t EPOCH = ((std::uint64_t) 116444736000000000ULL);
    SYSTEMTIME  system_time;
    FILETIME    file_time;
    std::uint64_t    time;
    GetSystemTime(&system_time);
    SystemTimeToFileTime(&system_time, &file_time);
    time = ((std::uint64_t)file_time.dwLowDateTime);
    time += ((std::uint64_t)file_time.dwHighDateTime) << 32;
    tp->tv_sec  = (long)((time - EPOCH) / 10000000L);
    tp->tv_usec = (long)(system_time.wMilliseconds * 1000);
    return 0;
}
References long.
Referenced by avr_write_byte_default(), igl::Timer::getElapsedTimeInMicroSec(), hid_read_timeout(), jtagmkII_recv_frame(), report_progress(), igl::Timer::start(), stk500v2_recv(), and igl::Timer::stop().
usleep()
int usleep (unsigned usec)
{
  std::this_thread::sleep_for(std::chrono::microseconds(usec));
  return 0;
}
Referenced by arduino_open(), avr910_chip_erase(), avr910_paged_write_eeprom(), avr910_paged_write_flash(), avr_write_byte_default(), avr_write_page(), avrdude_main(), bitbang_chip_erase(), bitbang_initialize(), buspirate_chip_erase(), buspirate_start_mode_bin(), butterfly_initialize(), butterfly_paged_write(), jtagmkII_smc_init32(), stk500_chip_erase(), stk500hv_chip_erase(), stk500isp_write_byte(), stk500v2_chip_erase(), stk500v2_initialize(), and wiring_open().