Prusa Slicer: Slic3r::SegmentPoint Struct Reference
Slic3r::SegmentPoint Struct Reference
Public Member Functions
bool valid () const
Public Attributes
size_t idx_segment = std::numeric_limits<size_t>::max()
double t
Vec2d point
Detailed Description
Member Function Documentation
valid()
bool Slic3r::SegmentPoint::valid () const inline
{ return idx_segment != std::numeric_limits<size_t>::max(); }
References idx_segment.
Referenced by Slic3r::mark_boundary_segments_touching_infill().
Member Data Documentation
idx_segment
size_t Slic3r::SegmentPoint::idx_segment = std::numeric_limits<size_t>::max()
Referenced by Slic3r::clip_end_segment_and_point(), Slic3r::clip_start_segment_and_point(), Slic3r::mark_boundary_segments_touching_infill(), and valid().
point
Vec2d Slic3r::SegmentPoint::point
Referenced by Slic3r::clip_end_segment_and_point(), Slic3r::clip_start_segment_and_point(), and Slic3r::mark_boundary_segments_touching_infill().
t
double Slic3r::SegmentPoint::t
Referenced by Slic3r::clip_end_segment_and_point(), Slic3r::clip_start_segment_and_point(), and Slic3r::mark_boundary_segments_touching_infill().
The documentation for this struct was generated from the following file:
src/libslic3r/Fill/FillBase.cpp