Prusa Slicer: Slic3r::PhysicalPrinterCollection Class Reference
Slic3r::PhysicalPrinterCollection Class Reference
#include <src/libslic3r/Preset.hpp>
Public Types
typedef std::deque< PhysicalPrinter >::iterator Iterator
typedef std::deque< PhysicalPrinter >::const_iterator ConstIterator
Public Member Functions
PhysicalPrinterCollection (const std::vector< std::string > &keys)
Iterator begin ()
ConstIterator begin () const
ConstIterator cbegin () const
Iterator end ()
ConstIterator end () const
ConstIterator cend () const
bool empty () const
void reset (bool delete_files)
const std::deque< PhysicalPrinter > & operator() () const
void load_printers (const std::string &dir_path, const std::string &subdir, PresetsConfigSubstitutions &substitutions, ForwardCompatibilitySubstitutionRule rule)
void load_printers_from_presets (PrinterPresetCollection &printer_presets)
void load_printer (const std::string &path, const std::string &name, DynamicPrintConfig &&config, bool select, bool save=false)
void save_printer (PhysicalPrinter &printer, const std::string &renamed_from="")
bool delete_printer (const std::string &name)
bool delete_selected_printer ()
bool delete_preset_from_printers (const std::string &preset_name)
void rename_preset_in_printers (const std::string &old_name, const std::string &new_name)
std::vector< std::string > get_printers_with_preset (const std::string &preset_name, bool respect_only_preset=true)
std::vector< std::string > get_printers_with_only_preset (const std::string &preset_name)
PhysicalPrinter & get_selected_printer ()
const PhysicalPrinter & get_selected_printer () const
size_t get_selected_idx () const
std::string get_selected_printer_name () const
DynamicPrintConfig * get_selected_printer_config ()
PrinterTechnology get_selected_printer_technology ()
std::string get_selected_full_printer_name () const
std::string get_selected_printer_preset_name () const
void select_printer (const std::string &full_name)
void select_printer (const PhysicalPrinter &printer)
void select_printer (const std::string &printer_name, const std::string &preset_name)
bool has_selection () const
void unselect_printer ()
bool is_selected (ConstIterator it, const std::string &preset_name) const
PhysicalPrinter & printer (size_t idx)
const PhysicalPrinter & printer (size_t idx) const
PhysicalPrinter * find_printer (const std::string &name, bool case_sensitive_search=true)
const PhysicalPrinter * find_printer (const std::string &name, bool case_sensitive_search=true) const
std::string path_from_name (const std::string &new_name) const
const DynamicPrintConfig & default_config () const
Private Member Functions
PhysicalPrinterCollection ()=default
PhysicalPrinterCollection & operator= (const PhysicalPrinterCollection &other)=default
std::deque< PhysicalPrinter >::iterator find_printer_internal (const std::string &name, bool case_sensitive_search=true)
std::deque< PhysicalPrinter >::const_iterator find_printer_internal (const std::string &name, bool case_sensitive_search=true) const
PhysicalPrinter * find_printer_with_same_config (const DynamicPrintConfig &config)
Private Attributes
std::deque< PhysicalPrinter > m_printers
DynamicPrintConfig m_default_config
size_t m_idx_selected = size_t(-1)
std::string m_selected_preset
std::string m_dir_path
Friends
class PresetBundle
Detailed Description
Member Typedef Documentation
ConstIterator
typedef std::deque<PhysicalPrinter>::const_iterator Slic3r::PhysicalPrinterCollection::ConstIterator
Iterator
typedef std::deque<PhysicalPrinter>::iterator Slic3r::PhysicalPrinterCollection::Iterator
Constructor & Destructor Documentation
PhysicalPrinterCollection() [1/2]
Slic3r::PhysicalPrinterCollection::PhysicalPrinterCollection (const std::vector< std::string > & keys)
{
    // Default config for a physical printer containing all key/value pairs of PhysicalPrinter::printer_options().
    for (const std::string &key : keys) {
        const ConfigOptionDef *opt = print_config_def.get(key);
        assert(opt);
        assert(opt->default_value);
        m_default_config.set_key_value(key, opt->default_value->clone());
    }
}
References Slic3r::ConfigOptionDef::default_value, Slic3r::ConfigDef::get(), m_default_config, Slic3r::print_config_def, and Slic3r::DynamicConfig::set_key_value().
PhysicalPrinterCollection() [2/2]
Slic3r::PhysicalPrinterCollection::PhysicalPrinterCollection () private default
Member Function Documentation
begin() [1/2]
Iterator Slic3r::PhysicalPrinterCollection::begin () inline
{ return m_printers.begin(); }
References m_printers.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), and Slic3r::GUI::TabPresetComboBox::update().
begin() [2/2]
ConstIterator Slic3r::PhysicalPrinterCollection::begin () const inline
{ return m_printers.cbegin(); }
References m_printers.
cbegin()
ConstIterator Slic3r::PhysicalPrinterCollection::cbegin () const inline
{ return m_printers.cbegin(); }
References m_printers.
cend()
ConstIterator Slic3r::PhysicalPrinterCollection::cend () const inline
{ return m_printers.cend(); }
References m_printers.
default_config()
const DynamicPrintConfig & Slic3r::PhysicalPrinterCollection::default_config () const inline
{ return m_default_config; }
References m_default_config.
Referenced by Slic3r::PresetBundle::load_configbundle(), load_printers(), and load_printers_from_presets().
delete_preset_from_printers()
bool Slic3r::PhysicalPrinterCollection::delete_preset_from_printers (const std::string & preset_name)
{
    std::vector<std::string> printers_for_delete;
    for (PhysicalPrinter& printer : m_printers) {
        if (printer.preset_names.size() == 1 && *printer.preset_names.begin() == preset_name)
            printers_for_delete.emplace_back(printer.name);
        else if (printer.delete_preset(preset_name))
            save_printer(printer);
    }
    if (!printers_for_delete.empty())
        for (const std::string& printer_name : printers_for_delete)
            delete_printer(printer_name);
    unselect_printer();
    return true;
}
References Slic3r::PhysicalPrinter::delete_preset(), delete_printer(), m_printers, Slic3r::PhysicalPrinter::name, Slic3r::PhysicalPrinter::preset_names, printer(), save_printer(), and unselect_printer().
Referenced by Slic3r::GUI::Tab::delete_preset().
delete_printer()
bool Slic3r::PhysicalPrinterCollection::delete_printer (const std::string & name)
{
    auto it = this->find_printer_internal(name);
    if (it == m_printers.end())
        return false;
    const PhysicalPrinter& printer = *it;
    // Erase the preset file.
    boost::nowide::remove(printer.file.c_str());
    m_printers.erase(it);
    return true;
}
References Slic3r::PhysicalPrinter::file, find_printer_internal(), m_printers, and printer().
Referenced by delete_preset_from_printers().
delete_selected_printer()
bool Slic3r::PhysicalPrinterCollection::delete_selected_printer ()
{
    if (!has_selection())
        return false;
    const PhysicalPrinter& printer = this->get_selected_printer();
    // Erase the preset file.
    boost::nowide::remove(printer.file.c_str());
    // Remove the preset from the list.
    m_printers.erase(m_printers.begin() + m_idx_selected);
    // unselect all printers
    unselect_printer();
    return true;
}
References Slic3r::PhysicalPrinter::file, get_selected_printer(), has_selection(), m_idx_selected, m_printers, printer(), and unselect_printer().
Referenced by Slic3r::GUI::PresetComboBox::del_physical_printer().
empty()
bool Slic3r::PhysicalPrinterCollection::empty () const inline
{return m_printers.empty(); }
References m_printers.
Referenced by Slic3r::GUI::Tab::delete_preset(), Slic3r::GUI::PlaterPresetComboBox::update(), and Slic3r::GUI::TabPresetComboBox::update().
end() [1/2]
Iterator Slic3r::PhysicalPrinterCollection::end () inline
{ return m_printers.end(); }
References m_printers.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), and Slic3r::GUI::TabPresetComboBox::update().
end() [2/2]
ConstIterator Slic3r::PhysicalPrinterCollection::end () const inline
{ return m_printers.cend(); }
References m_printers.
find_printer() [1/2]
PhysicalPrinter * Slic3r::PhysicalPrinterCollection::find_printer (const std::string & name, bool case_sensitive_search = true)
{
    auto it = this->find_printer_internal(name, case_sensitive_search);
    // Ensure that a temporary copy is returned if the preset found is currently selected.
    auto is_equal_name = [name, case_sensitive_search](const std::string& in_name) {
        if (case_sensitive_search)
            return in_name == name;
        return boost::to_lower_copy<std::string>(in_name) == boost::to_lower_copy<std::string>(name);
    };
    if (it == m_printers.end() || !is_equal_name(it->name))
        return nullptr;
    return &this->printer(it - m_printers.begin());
}
References find_printer_internal(), m_printers, and printer().
Referenced by Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), find_printer(), find_printer_with_same_config(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetBundle::load_configbundle(), load_printers(), load_printers_from_presets(), and Slic3r::GUI::PhysicalPrinterDialog::OnOK().
find_printer() [2/2]
const PhysicalPrinter * Slic3r::PhysicalPrinterCollection::find_printer (const std::string & name, bool case_sensitive_search = true) const inline
    {
        return const_cast<PhysicalPrinterCollection*>(this)->find_printer(name, case_sensitive_search);
    }
References find_printer().
find_printer_internal() [1/2]
std::deque< PhysicalPrinter >::iterator Slic3r::PhysicalPrinterCollection::find_printer_internal (const std::string & name, bool case_sensitive_search = true) private
{
    if (case_sensitive_search)
        return Slic3r::lower_bound_by_predicate(m_printers.begin(), m_printers.end(), [&name](const auto& l) { return l.name < name;  });
    std::string low_name = boost::to_lower_copy<std::string>(name);
    size_t i = 0;
    for (const PhysicalPrinter& printer : m_printers) {
        if (boost::to_lower_copy<std::string>(printer.name) == low_name)
            break;
        i++;
    }
    if (i == m_printers.size())
        return m_printers.end();
    return m_printers.begin() + i;
}
References Slic3r::lower_bound_by_predicate(), m_printers, Slic3r::PhysicalPrinter::name, and printer().
Referenced by delete_printer(), find_printer(), find_printer_internal(), load_printer(), save_printer(), and select_printer().
find_printer_internal() [2/2]
std::deque< PhysicalPrinter >::const_iterator Slic3r::PhysicalPrinterCollection::find_printer_internal (const std::string & name, bool case_sensitive_search = true) const inline private
    {
        return const_cast<PhysicalPrinterCollection*>(this)->find_printer_internal(name);
    }
References find_printer_internal().
find_printer_with_same_config()
PhysicalPrinter * Slic3r::PhysicalPrinterCollection::find_printer_with_same_config (const DynamicPrintConfig & config) private
{
    for (const PhysicalPrinter& printer :*this) {
        bool is_equal = true;
        for (const char *opt : legacy_print_host_options)
            if (is_equal && printer.config.opt_string(opt) != config.opt_string(opt))
                is_equal = false;
        if (is_equal)
            return find_printer(printer.name);
    }
    return nullptr;
}
References Slic3r::PhysicalPrinter::config, find_printer(), Slic3r::legacy_print_host_options, Slic3r::PhysicalPrinter::name, Slic3r::ConfigBase::opt_string(), and printer().
Referenced by load_printers_from_presets().
get_printers_with_only_preset()
std::vector< std::string > Slic3r::PhysicalPrinterCollection::get_printers_with_only_preset (const std::string & preset_name)
{
    std::vector<std::string> printers;
    for (const PhysicalPrinter& printer : m_printers)
        if (printer.preset_names.size() == 1 && *printer.preset_names.begin() == preset_name)
            printers.emplace_back(printer.name);
    return printers;
}
References m_printers, Slic3r::PhysicalPrinter::name, Slic3r::PhysicalPrinter::preset_names, and printer().
Referenced by Slic3r::GUI::Tab::delete_preset().
get_printers_with_preset()
std::vector< std::string > Slic3r::PhysicalPrinterCollection::get_printers_with_preset (const std::string & preset_name, bool respect_only_preset = true)
{
    std::vector<std::string> printers;
    for (auto printer : m_printers) {
        if (!respect_only_preset && printer.preset_names.size() == 1)
            continue;
        if (printer.preset_names.find(preset_name) != printer.preset_names.end())
            printers.emplace_back(printer.name);
    }
    return printers;
}
References m_printers, Slic3r::PhysicalPrinter::name, Slic3r::PhysicalPrinter::preset_names, and printer().
Referenced by Slic3r::GUI::Tab::delete_preset().
get_selected_full_printer_name()
std::string Slic3r::PhysicalPrinterCollection::get_selected_full_printer_name () const
{
    return (m_idx_selected == size_t(-1)) ? std::string() : this->get_selected_printer().get_full_name(m_selected_preset);
}
References Slic3r::PhysicalPrinter::get_full_name(), get_selected_printer(), m_idx_selected, and m_selected_preset.
Referenced by Slic3r::GUI::PresetComboBox::del_physical_printer(), Slic3r::PresetBundle::export_selections(), Slic3r::GUI::PlaterPresetComboBox::get_selected_ph_printer_name(), and Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers().
get_selected_idx()
size_t Slic3r::PhysicalPrinterCollection::get_selected_idx () const inline
{ return m_idx_selected; }
References m_idx_selected.
get_selected_printer() [1/2]
PhysicalPrinter & Slic3r::PhysicalPrinterCollection::get_selected_printer () inline
{ return m_printers[m_idx_selected]; }
References m_idx_selected, and m_printers.
Referenced by Slic3r::GUI::Tab::delete_preset(), delete_selected_printer(), get_selected_full_printer_name(), get_selected_printer_config(), get_selected_printer_name(), get_selected_printer_technology(), Slic3r::GUI::PresetComboBox::open_physical_printer_url(), Slic3r::GUI::PlaterPresetComboBox::show_edit_menu(), and Slic3r::GUI::SavePresetDialog::update_physical_printers().
get_selected_printer() [2/2]
const PhysicalPrinter & Slic3r::PhysicalPrinterCollection::get_selected_printer () const inline
{ return m_printers[m_idx_selected]; }
References m_idx_selected, and m_printers.
get_selected_printer_config()
DynamicPrintConfig * Slic3r::PhysicalPrinterCollection::get_selected_printer_config () inline
{ return (m_idx_selected == size_t(-1)) ? nullptr : &(this->get_selected_printer().config); }
References Slic3r::PhysicalPrinter::config, get_selected_printer(), and m_idx_selected.
get_selected_printer_name()
std::string Slic3r::PhysicalPrinterCollection::get_selected_printer_name () const inline
{ return (m_idx_selected == size_t(-1)) ? std::string() : this->get_selected_printer().name; }
References get_selected_printer(), m_idx_selected, and Slic3r::PhysicalPrinter::name.
Referenced by Slic3r::GUI::SavePresetDialog::add_info_for_edit_ph_printer(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::full_sla_config(), and Slic3r::GUI::PhysicalPrinterDialog::OnOK().
get_selected_printer_preset_name()
std::string Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name () const inline
{ return (m_idx_selected == size_t(-1)) ? std::string() : m_selected_preset; }
References m_idx_selected, and m_selected_preset.
Referenced by Slic3r::GUI::SavePresetDialog::add_info_for_edit_ph_printer(), Slic3r::GUI::Tab::delete_preset(), Slic3r::GUI::PhysicalPrinterDialog::OnOK(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::SavePresetDialog::update_physical_printers().
get_selected_printer_technology()
PrinterTechnology Slic3r::PhysicalPrinterCollection::get_selected_printer_technology () inline
{ return (m_idx_selected == size_t(-1)) ? PrinterTechnology::ptAny : this->get_selected_printer().printer_technology(); }
References get_selected_printer(), m_idx_selected, Slic3r::PhysicalPrinter::printer_technology(), and Slic3r::ptAny.
has_selection()
bool Slic3r::PhysicalPrinterCollection::has_selection () const
{
    return m_idx_selected != size_t(-1);
}
References m_idx_selected.
Referenced by delete_selected_printer(), Slic3r::GUI::PresetComboBox::edit_physical_printer(), Slic3r::GUI::PlaterPresetComboBox::get_selected_ph_printer_name(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::SavePresetDialog::update_physical_printers().
is_selected()
bool Slic3r::PhysicalPrinterCollection::is_selected (PhysicalPrinterCollection::ConstIterator it, const std::string & preset_name) const
{
    return  m_idx_selected      == size_t(it - m_printers.begin()) &&
            m_selected_preset   == preset_name;
}
References m_idx_selected, m_printers, and m_selected_preset.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), and Slic3r::GUI::TabPresetComboBox::update().
load_printer()
void Slic3r::PhysicalPrinterCollection::load_printer (const std::string & path, const std::string & name, DynamicPrintConfig && config, bool select, bool save = false)
{
    auto it = this->find_printer_internal(name);
    if (it == m_printers.end() || it->name != name) {
        // The preset was not found. Create a new preset.
        it = m_printers.emplace(it, PhysicalPrinter(name, config));
    }
    it->file = path;
    it->config = std::move(config);
    it->loaded = true;
    if (select)
        this->select_printer(*it);
    if (save)
        it->save();
}
References find_printer_internal(), m_printers, save(), and select_printer().
Referenced by Slic3r::PresetBundle::load_configbundle().
load_printers()
void Slic3r::PhysicalPrinterCollection::load_printers (const std::string & dir_path, const std::string & subdir, PresetsConfigSubstitutions & substitutions, ForwardCompatibilitySubstitutionRule rule)
{
    // Don't use boost::filesystem::canonical() on Windows, it is broken in regard to reparse points,
    // see https://github.com/prusa3d/PrusaSlicer/issues/732
    boost::filesystem::path dir = boost::filesystem::absolute(boost::filesystem::path(dir_path) / subdir).make_preferred();
    m_dir_path = dir.string();
    std::string errors_cummulative;
    // Store the loaded printers into a new vector, otherwise the binary search for already existing presets would be broken.
    std::deque<PhysicalPrinter> printers_loaded;
    for (auto& dir_entry : boost::filesystem::directory_iterator(dir))
        if (Slic3r::is_ini_file(dir_entry)) {
            std::string name = dir_entry.path().filename().string();
            // Remove the .ini suffix.
            name.erase(name.size() - 4);
            if (this->find_printer(name, false)) {
                // This happens when there's is a preset (most likely legacy one) with the same name as a system preset
                // that's already been loaded from a bundle.
                BOOST_LOG_TRIVIAL(warning) << "Printer already present, not loading: " << name;
                continue;
            }
            try {
                PhysicalPrinter printer(name, this->default_config());
                printer.file = dir_entry.path().string();
                // Load the preset file, apply preset values on top of defaults.
                try {
                    DynamicPrintConfig config;
                    ConfigSubstitutions config_substitutions = config.load_from_ini(printer.file, substitution_rule);
                    if (! config_substitutions.empty())
                        substitutions.push_back({ name, Preset::TYPE_PHYSICAL_PRINTER, PresetConfigSubstitutions::Source::UserFile, printer.file, std::move(config_substitutions) });
                    printer.update_from_config(config);
                    printer.loaded = true;
                }
                catch (const std::ifstream::failure& err) {
                    throw Slic3r::RuntimeError(std::string("The selected preset cannot be loaded: ") + printer.file + "\n\tReason: " + err.what());
                }
                catch (const std::runtime_error& err) {
                    throw Slic3r::RuntimeError(std::string("Failed loading the preset file: ") + printer.file + "\n\tReason: " + err.what());
                }
                printers_loaded.emplace_back(printer);
            }
            catch (const std::runtime_error& err) {
                errors_cummulative += err.what();
                errors_cummulative += "\n";
            }
        }
    m_printers.insert(m_printers.end(), std::make_move_iterator(printers_loaded.begin()), std::make_move_iterator(printers_loaded.end()));
    std::sort(m_printers.begin(), m_printers.end());
    if (!errors_cummulative.empty())
        throw Slic3r::RuntimeError(errors_cummulative);
}
References default_config(), Slic3r::PhysicalPrinter::file, find_printer(), Slic3r::is_ini_file(), Slic3r::ConfigBase::load_from_ini(), Slic3r::PhysicalPrinter::loaded, m_dir_path, m_printers, printer(), Slic3r::Preset::TYPE_PHYSICAL_PRINTER, Slic3r::PhysicalPrinter::update_from_config(), and Slic3r::PresetConfigSubstitutions::UserFile.
Referenced by Slic3r::PresetBundle::load_presets().
load_printers_from_presets()
void Slic3r::PhysicalPrinterCollection::load_printers_from_presets (PrinterPresetCollection & printer_presets)
{
    int cnt=0;
    for (Preset& preset: printer_presets) {
        DynamicPrintConfig& config = preset.config;
        for(const char* option : legacy_print_host_options) {
            if (!config.opt_string(option).empty()) {
                // check if printer with those "Print Host upload" options already exist
                PhysicalPrinter* existed_printer = find_printer_with_same_config(config);
                if (existed_printer)
                    // just add preset for this printer
                    existed_printer->add_preset(preset.name);
                else {
                    std::string new_printer_name = (boost::format("Printer %1%") % ++cnt ).str();
                    while (find_printer(new_printer_name))
                        new_printer_name = (boost::format("Printer %1%") % ++cnt).str();
                    // create new printer from this preset
                    PhysicalPrinter printer(new_printer_name, this->default_config(), preset);
                    printer.loaded = true;
                    save_printer(printer);
                }
                // erase "Print Host upload" information from the preset
                for (const char *opt : legacy_print_host_options)
                    config.opt_string(opt).clear();
                // save changes for preset
                preset.save();
                // update those changes for edited preset if it's equal to the preset
                Preset& edited = printer_presets.get_edited_preset();
                if (preset.name == edited.name) {
                    for (const char *opt : legacy_print_host_options)
                        edited.config.opt_string(opt).clear();
                }
                break;
            }
        }
    }
}
References Slic3r::PhysicalPrinter::add_preset(), Slic3r::Preset::config, default_config(), find_printer(), find_printer_with_same_config(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::legacy_print_host_options, Slic3r::PhysicalPrinter::loaded, Slic3r::Preset::name, Slic3r::ConfigBase::opt_string(), printer(), and save_printer().
Referenced by Slic3r::GUI::GUI_App::check_printer_presets().
operator()()
const std::deque< PhysicalPrinter > & Slic3r::PhysicalPrinterCollection::operator() () const inline
{ return m_printers; }
References m_printers.
operator=()
PhysicalPrinterCollection & Slic3r::PhysicalPrinterCollection::operator= (const PhysicalPrinterCollection & other) private default
path_from_name()
std::string Slic3r::PhysicalPrinterCollection::path_from_name (const std::string & new_name) const
{
    std::string file_name = boost::iends_with(new_name, ".ini") ? new_name : (new_name + ".ini");
    return (boost::filesystem::path(m_dir_path) / file_name).make_preferred().string();
}
References m_dir_path.
Referenced by save_printer().
printer() [1/2]
PhysicalPrinter & Slic3r::PhysicalPrinterCollection::printer (size_t idx) inline
{ return m_printers[idx]; }
References m_printers.
Referenced by delete_preset_from_printers(), delete_printer(), delete_selected_printer(), find_printer(), find_printer_internal(), find_printer_with_same_config(), get_printers_with_only_preset(), get_printers_with_preset(), load_printers(), load_printers_from_presets(), rename_preset_in_printers(), save_printer(), and select_printer().
printer() [2/2]
const PhysicalPrinter & Slic3r::PhysicalPrinterCollection::printer (size_t idx) const inline
{ return const_cast<PhysicalPrinterCollection*>(this)->printer(idx); }
References printer().
Referenced by printer().
rename_preset_in_printers()
void Slic3r::PhysicalPrinterCollection::rename_preset_in_printers (const std::string & old_name, const std::string & new_name)
{
    for (PhysicalPrinter& printer : m_printers)
        if (printer.delete_preset(old_preset_name)) {
            printer.add_preset(new_preset_name);
            printer.update_preset_names_in_config();
            printer.save();
        }
}
References Slic3r::PhysicalPrinter::add_preset(), Slic3r::PhysicalPrinter::delete_preset(), m_printers, printer(), Slic3r::PhysicalPrinter::save(), and Slic3r::PhysicalPrinter::update_preset_names_in_config().
reset()
void Slic3r::PhysicalPrinterCollection::reset (bool delete_files) inline
{};
save_printer()
void Slic3r::PhysicalPrinterCollection::save_printer (PhysicalPrinter & printer, const std::string & renamed_from = "")
{
    // controll and update preset_names in edited_printer config
    edited_printer.update_preset_names_in_config();
    std::string name = renamed_from.empty() ? edited_printer.name : renamed_from;
    // 1) Find the printer with a new_name or create a new one,
    // initialize it with the edited config.
    auto it = this->find_printer_internal(name);
    if (it != m_printers.end() && it->name == name) {
        // Printer with the same name found.
        // Overwriting an existing preset.
        it->config = std::move(edited_printer.config);
        it->name = edited_printer.name;
        it->preset_names = edited_printer.preset_names;
        // sort printers and get new it
        std::sort(m_printers.begin(), m_printers.end());
        it = this->find_printer_internal(edited_printer.name);
    }
    else {
        // Creating a new printer.
        it = m_printers.emplace(it, edited_printer);
    }
    assert(it != m_printers.end());
    // 2) Save printer
    PhysicalPrinter& printer = *it;
    if (printer.file.empty())
        printer.file = this->path_from_name(printer.name);
    if (printer.file == this->path_from_name(printer.name))
        printer.save();
    else
        // if printer was renamed, we should rename a file and than save the config
        printer.save(printer.file, this->path_from_name(printer.name));
    // update idx_selected
    m_idx_selected = it - m_printers.begin();
}
References Slic3r::PhysicalPrinter::config, Slic3r::PhysicalPrinter::file, find_printer_internal(), m_idx_selected, m_printers, Slic3r::PhysicalPrinter::name, path_from_name(), Slic3r::PhysicalPrinter::preset_names, printer(), Slic3r::PhysicalPrinter::save(), and Slic3r::PhysicalPrinter::update_preset_names_in_config().
Referenced by delete_preset_from_printers(), load_printers_from_presets(), Slic3r::GUI::PhysicalPrinterDialog::OnOK(), and Slic3r::GUI::SavePresetDialog::update_physical_printers().
select_printer() [1/3]
void Slic3r::PhysicalPrinterCollection::select_printer (const PhysicalPrinter & printer)
{
    return select_printer(printer.name);
}
References Slic3r::PhysicalPrinter::name, printer(), and select_printer().
select_printer() [2/3]
void Slic3r::PhysicalPrinterCollection::select_printer (const std::string & full_name)
{
    std::string printer_name = PhysicalPrinter::get_short_name(full_name);
    auto it = this->find_printer_internal(printer_name);
    if (it == m_printers.end()) {
        unselect_printer();
        return;
    }
    // update idx_selected
    m_idx_selected = it - m_printers.begin();
    // update name of the currently selected preset
    if (printer_name == full_name)
        // use first preset in the list
        m_selected_preset = *it->preset_names.begin();
    else
        m_selected_preset = it->get_preset_name(full_name);
}
References find_printer_internal(), Slic3r::PhysicalPrinter::get_short_name(), m_idx_selected, m_printers, m_selected_preset, and unselect_printer().
Referenced by Slic3r::GUI::Tab::delete_preset(), Slic3r::PresetBundle::load_config_file_config(), load_printer(), Slic3r::PresetBundle::load_selections(), Slic3r::GUI::PhysicalPrinterDialog::OnOK(), select_printer(), select_printer(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), and Slic3r::GUI::SavePresetDialog::update_physical_printers().
select_printer() [3/3]
void Slic3r::PhysicalPrinterCollection::select_printer (const std::string & printer_name, const std::string & preset_name)
{
    if (preset_name.empty())
        return select_printer(printer_name);
    return select_printer(printer_name + PhysicalPrinter::separator() + preset_name);
}
References select_printer(), and Slic3r::PhysicalPrinter::separator().
unselect_printer()
void Slic3r::PhysicalPrinterCollection::unselect_printer ()
{
    m_idx_selected = size_t(-1);
    m_selected_preset.clear();
}
References m_idx_selected, and m_selected_preset.
Referenced by delete_preset_from_printers(), delete_selected_printer(), Slic3r::PresetBundle::load_config_file_config(), select_printer(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::SavePresetDialog::update_physical_printers().
Friends And Related Symbol Documentation
PresetBundle
friend class PresetBundle friend
Member Data Documentation
m_default_config
DynamicPrintConfig Slic3r::PhysicalPrinterCollection::m_default_config private
Referenced by PhysicalPrinterCollection(), and default_config().
m_dir_path
std::string Slic3r::PhysicalPrinterCollection::m_dir_path private
Referenced by load_printers(), and path_from_name().
m_idx_selected
size_t Slic3r::PhysicalPrinterCollection::m_idx_selected = size_t(-1) private
Referenced by delete_selected_printer(), get_selected_full_printer_name(), get_selected_idx(), get_selected_printer(), get_selected_printer(), get_selected_printer_config(), get_selected_printer_name(), get_selected_printer_preset_name(), get_selected_printer_technology(), has_selection(), is_selected(), save_printer(), select_printer(), and unselect_printer().
m_printers
std::deque<PhysicalPrinter> Slic3r::PhysicalPrinterCollection::m_printers private
Referenced by begin(), begin(), cbegin(), cend(), delete_preset_from_printers(), delete_printer(), delete_selected_printer(), empty(), end(), end(), find_printer(), find_printer_internal(), get_printers_with_only_preset(), get_printers_with_preset(), get_selected_printer(), get_selected_printer(), is_selected(), load_printer(), load_printers(), operator()(), printer(), rename_preset_in_printers(), save_printer(), and select_printer().
m_selected_preset
std::string Slic3r::PhysicalPrinterCollection::m_selected_preset private
Referenced by get_selected_full_printer_name(), get_selected_printer_preset_name(), is_selected(), select_printer(), and unselect_printer().
The documentation for this class was generated from the following files:
src/libslic3r/Preset.hpp
src/libslic3r/Preset.cpp