Prusa Slicer: Slic3r::GLVolume Class Reference
Slic3r::GLVolume Class Reference
#include <src/slic3r/GUI/3DScene.hpp>
Classes
struct CompositeID
class NonManifoldEdges
class SinkingContours
Public Types
enum EHoverState : unsigned char { HS_None , HS_Hover , HS_Select , HS_Deselect }
Public Member Functions
GLVolume (float r=1.0f, float g=1.0f, float b=1.0f, float a=1.0f)
GLVolume (const ColorRGBA &color)
BoundingBoxf3 bounding_box () const
void set_color (const ColorRGBA &rgba)
void set_render_color (const ColorRGBA &rgba)
void set_render_color (bool force_transparent)
void set_color_from_model_volume (const ModelVolume &model_volume)
const Geometry::Transformation & get_instance_transformation () const
void set_instance_transformation (const Geometry::Transformation &transformation)
void set_instance_transformation (const Transform3d &transform)
Vec3d get_instance_offset () const
double get_instance_offset (Axis axis) const
void set_instance_offset (const Vec3d &offset)
void set_instance_offset (Axis axis, double offset)
Vec3d get_instance_rotation () const
double get_instance_rotation (Axis axis) const
void set_instance_rotation (const Vec3d &rotation)
void set_instance_rotation (Axis axis, double rotation)
Vec3d get_instance_scaling_factor () const
double get_instance_scaling_factor (Axis axis) const
void set_instance_scaling_factor (const Vec3d &scaling_factor)
void set_instance_scaling_factor (Axis axis, double scaling_factor)
Vec3d get_instance_mirror () const
double get_instance_mirror (Axis axis) const
void set_instance_mirror (const Vec3d &mirror)
void set_instance_mirror (Axis axis, double mirror)
const Geometry::Transformation & get_volume_transformation () const
void set_volume_transformation (const Geometry::Transformation &transformation)
void set_volume_transformation (const Transform3d &transform)
Vec3d get_volume_offset () const
double get_volume_offset (Axis axis) const
void set_volume_offset (const Vec3d &offset)
void set_volume_offset (Axis axis, double offset)
Vec3d get_volume_rotation () const
double get_volume_rotation (Axis axis) const
void set_volume_rotation (const Vec3d &rotation)
void set_volume_rotation (Axis axis, double rotation)
Vec3d get_volume_scaling_factor () const
double get_volume_scaling_factor (Axis axis) const
void set_volume_scaling_factor (const Vec3d &scaling_factor)
void set_volume_scaling_factor (Axis axis, double scaling_factor)
Vec3d get_volume_mirror () const
double get_volume_mirror (Axis axis) const
void set_volume_mirror (const Vec3d &mirror)
void set_volume_mirror (Axis axis, double mirror)
double get_sla_shift_z () const
void set_sla_shift_z (double z)
void set_convex_hull (std::shared_ptr< const TriangleMesh > convex_hull)
void set_convex_hull (const TriangleMesh &convex_hull)
void set_convex_hull (TriangleMesh &&convex_hull)
int object_idx () const
int volume_idx () const
int instance_idx () const
Transform3d world_matrix () const
bool is_left_handed () const
const BoundingBoxf3 & transformed_bounding_box () const
BoundingBoxf3 transformed_convex_hull_bounding_box (const Transform3d &trafo) const
const BoundingBoxf3 & transformed_convex_hull_bounding_box () const
BoundingBoxf3 transformed_non_sinking_bounding_box (const Transform3d &trafo) const
const BoundingBoxf3 & transformed_non_sinking_bounding_box () const
const TriangleMesh * convex_hull () const
bool empty () const
void set_range (double low, double high)
void render ()
void set_bounding_boxes_as_dirty ()
bool is_sla_support () const
bool is_sla_pad () const
bool is_sinking () const
bool is_below_printbed () const
void render_sinking_contours ()
void render_non_manifold_edges ()
size_t cpu_memory_used () const
size_t gpu_memory_used () const
size_t total_memory_used () const
Public Attributes
ColorRGBA color
ColorRGBA render_color
CompositeID composite_id
std::pair< size_t, size_t > geometry_id
int extruder_id
struct {
bool selected: 1
bool disabled: 1
bool printable: 1
bool is_active: 1
bool zoom_to_volumes: 1
bool shader_outside_printer_detection_enabled: 1
bool is_outside: 1
bool is_modifier: 1
bool is_wipe_tower: 1
bool is_extrusion_path: 1
bool force_native_color: 1
bool force_neutral_color: 1
bool force_sinking_contours: 1
};
EHoverState hover
GUI::GLModel model
std::unique_ptr< GUI::MeshRaycaster > mesh_raycaster
std::pair< size_t, size_t > tverts_range
std::vector< coordf_t > print_zs
std::vector< size_t > offsets
Static Public Attributes
static const ColorRGBA SELECTED_COLOR = ColorRGBA::GREEN()
static const ColorRGBA HOVER_SELECT_COLOR = { 0.4f, 0.9f, 0.1f, 1.0f }
static const ColorRGBA HOVER_DESELECT_COLOR = { 1.0f, 0.75f, 0.75f, 1.0f }
static const ColorRGBA OUTSIDE_COLOR = { 0.0f, 0.38f, 0.8f, 1.0f }
static const ColorRGBA SELECTED_OUTSIDE_COLOR = { 0.19f, 0.58f, 1.0f, 1.0f }
static const ColorRGBA DISABLED_COLOR = ColorRGBA::DARK_GRAY()
static const ColorRGBA SLA_SUPPORT_COLOR = ColorRGBA::LIGHT_GRAY()
static const ColorRGBA SLA_PAD_COLOR = { 0.0f, 0.2f, 0.0f, 1.0f }
static const ColorRGBA NEUTRAL_COLOR = { 0.9f, 0.9f, 0.9f, 1.0f }
static const std::array< ColorRGBA, 4 > MODEL_COLOR
Private Attributes
Geometry::Transformation m_instance_transformation
Geometry::Transformation m_volume_transformation
double m_sla_shift_z
std::optional< BoundingBoxf3 > m_transformed_bounding_box
std::shared_ptr< const TriangleMesh > m_convex_hull
std::optional< BoundingBoxf3 > m_transformed_convex_hull_bounding_box
std::optional< BoundingBoxf3 > m_transformed_non_sinking_bounding_box
SinkingContours m_sinking_contours
NonManifoldEdges m_non_manifold_edges
Detailed Description
Member Enumeration Documentation
EHoverState
enum Slic3r::GLVolume::EHoverState : unsigned char
Enumerator
HS_None
HS_Hover
HS_Select
HS_Deselect
    {
        HS_None,
        HS_Hover,
        HS_Select,
        HS_Deselect
    };
Constructor & Destructor Documentation
GLVolume() [1/2]
Slic3r::GLVolume::GLVolume (float r = 1.0f, float g = 1.0f, float b = 1.0f, float a = 1.0f)
    : m_sla_shift_z(0.0)
    , m_sinking_contours(*this)
    , m_non_manifold_edges(*this)
    // geometry_id == 0 -> invalid
    , geometry_id(std::pair<size_t, size_t>(0, 0))
    , extruder_id(0)
    , selected(false)
    , disabled(false)
    , printable(true)
    , is_active(true)
    , zoom_to_volumes(true)
    , shader_outside_printer_detection_enabled(false)
    , is_outside(false)
    , hover(HS_None)
    , is_modifier(false)
    , is_wipe_tower(false)
    , is_extrusion_path(false)
    , force_native_color(false)
    , force_neutral_color(false)
    , force_sinking_contours(false)
    , tverts_range(0, size_t(-1))
{
    color = { r, g, b, a };
    set_render_color(color);
}
References color, and set_render_color().
GLVolume() [2/2]
Slic3r::GLVolume::GLVolume (const ColorRGBA & color) inline
: GLVolume(color.r(), color.g(), color.b(), color.a()) {}
Member Function Documentation
bounding_box()
BoundingBoxf3 Slic3r::GLVolume::bounding_box () const inline
{
        return this->model.get_bounding_box();
    }
References Slic3r::GUI::GLModel::get_bounding_box().
Referenced by Slic3r::GUI::Selection::render_synchronized_volumes(), transformed_bounding_box(), and transformed_convex_hull_bounding_box().
convex_hull()
const TriangleMesh * Slic3r::GLVolume::convex_hull () const inline
{ return m_convex_hull.get(); }
References m_convex_hull.
Referenced by Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::GUI::Selection::scale_to_fit_print_volume(), set_convex_hull(), set_convex_hull(), and set_convex_hull().
cpu_memory_used()
size_t Slic3r::GLVolume::cpu_memory_used () const inline
{
          return sizeof(*this) + this->model.cpu_memory_used() + this->print_zs.capacity() * sizeof(coordf_t) +
               this->offsets.capacity() * sizeof(size_t);
    }
References Slic3r::GUI::GLModel::cpu_memory_used().
Referenced by total_memory_used().
empty()
bool Slic3r::GLVolume::empty () const inline
{ return this->model.is_empty(); }
References Slic3r::GUI::GLModel::is_empty().
get_instance_mirror() [1/2]
Vec3d Slic3r::GLVolume::get_instance_mirror () const inline
{ return m_instance_transformation.get_mirror(); }
References Slic3r::Geometry::Transformation::get_mirror(), and m_instance_transformation.
get_instance_mirror() [2/2]
double Slic3r::GLVolume::get_instance_mirror (Axis axis) const inline
{ return m_instance_transformation.get_mirror(axis); }
References Slic3r::Geometry::Transformation::get_mirror(), and m_instance_transformation.
get_instance_offset() [1/2]
Vec3d Slic3r::GLVolume::get_instance_offset () const inline
{ return m_instance_transformation.get_offset(); }
References Slic3r::Geometry::Transformation::get_offset(), and m_instance_transformation.
Referenced by Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::GLGizmoCut3D::process_cut_line(), and Slic3r::GUI::GLGizmoScale3D::update_render_data().
get_instance_offset() [2/2]
double Slic3r::GLVolume::get_instance_offset (Axis axis) const inline
{ return m_instance_transformation.get_offset(axis); }
References Slic3r::Geometry::Transformation::get_offset(), and m_instance_transformation.
get_instance_rotation() [1/2]
Vec3d Slic3r::GLVolume::get_instance_rotation () const inline
{ return m_instance_transformation.get_rotation(); }
References Slic3r::Geometry::Transformation::get_rotation(), and m_instance_transformation.
get_instance_rotation() [2/2]
double Slic3r::GLVolume::get_instance_rotation (Axis axis) const inline
{ return m_instance_transformation.get_rotation(axis); }
References Slic3r::Geometry::Transformation::get_rotation(), and m_instance_transformation.
get_instance_scaling_factor() [1/2]
Vec3d Slic3r::GLVolume::get_instance_scaling_factor () const inline
{ return m_instance_transformation.get_scaling_factor(); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and m_instance_transformation.
get_instance_scaling_factor() [2/2]
double Slic3r::GLVolume::get_instance_scaling_factor (Axis axis) const inline
{ return m_instance_transformation.get_scaling_factor(axis); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and m_instance_transformation.
get_instance_transformation()
const Geometry::Transformation & Slic3r::GLVolume::get_instance_transformation () const inline
{ return m_instance_transformation; }
References m_instance_transformation.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::Selection::flattening_rotate(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::GLGizmoMove3D::local_transform(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::Selection::render_synchronized_volumes(), Slic3r::GUI::Selection::set_caches(), priv::start_create_volume_on_surface_job(), Slic3r::GUI::Selection::synchronize_unselected_instances(), Slic3r::GUI::Selection::translate(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
get_sla_shift_z()
double Slic3r::GLVolume::get_sla_shift_z () const inline
{ return m_sla_shift_z; }
References m_sla_shift_z.
Referenced by Slic3r::GUI::GLGizmoCut3D::get_cut_matrix(), Slic3r::GUI::on_mouse_surface_drag(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::GLGizmoCut3D::process_cut_line(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
get_volume_mirror() [1/2]
Vec3d Slic3r::GLVolume::get_volume_mirror () const inline
{ return m_volume_transformation.get_mirror(); }
References Slic3r::Geometry::Transformation::get_mirror(), and m_volume_transformation.
get_volume_mirror() [2/2]
double Slic3r::GLVolume::get_volume_mirror (Axis axis) const inline
{ return m_volume_transformation.get_mirror(axis); }
References Slic3r::Geometry::Transformation::get_mirror(), and m_volume_transformation.
get_volume_offset() [1/2]
Vec3d Slic3r::GLVolume::get_volume_offset () const inline
{ return m_volume_transformation.get_offset(); }
References Slic3r::Geometry::Transformation::get_offset(), and m_volume_transformation.
Referenced by Slic3r::GUI::GCodeViewer::load_shells().
get_volume_offset() [2/2]
double Slic3r::GLVolume::get_volume_offset (Axis axis) const inline
{ return m_volume_transformation.get_offset(axis); }
References Slic3r::Geometry::Transformation::get_offset(), and m_volume_transformation.
get_volume_rotation() [1/2]
Vec3d Slic3r::GLVolume::get_volume_rotation () const inline
{ return m_volume_transformation.get_rotation(); }
References Slic3r::Geometry::Transformation::get_rotation(), and m_volume_transformation.
get_volume_rotation() [2/2]
double Slic3r::GLVolume::get_volume_rotation (Axis axis) const inline
{ return m_volume_transformation.get_rotation(axis); }
References Slic3r::Geometry::Transformation::get_rotation(), and m_volume_transformation.
get_volume_scaling_factor() [1/2]
Vec3d Slic3r::GLVolume::get_volume_scaling_factor () const inline
{ return m_volume_transformation.get_scaling_factor(); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and m_volume_transformation.
get_volume_scaling_factor() [2/2]
double Slic3r::GLVolume::get_volume_scaling_factor (Axis axis) const inline
{ return m_volume_transformation.get_scaling_factor(axis); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and m_volume_transformation.
get_volume_transformation()
const Geometry::Transformation & Slic3r::GLVolume::get_volume_transformation () const inline
{ return m_volume_transformation; }
References m_volume_transformation.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), priv::apply_camera_dir(), Slic3r::GUI::GLGizmoMove3D::local_transform(), Slic3r::GUI::on_mouse_surface_drag(), Slic3r::GUI::Selection::render_synchronized_volumes(), Slic3r::GUI::Selection::set_caches(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
gpu_memory_used()
size_t Slic3r::GLVolume::gpu_memory_used () const inline
{ return this->model.gpu_memory_used(); }
References Slic3r::GUI::GLModel::gpu_memory_used().
Referenced by total_memory_used().
instance_idx()
int Slic3r::GLVolume::instance_idx () const inline
{ return this->composite_id.instance_id; }
References Slic3r::GLVolume::CompositeID::instance_id.
Referenced by Slic3r::GUI::GLCanvas3D::_update_selection_from_hover(), Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::Selection::do_remove_instance(), Slic3r::GUI::get_model_instance(), Slic3r::GUI::get_model_instance(), Slic3r::GUI::Selection::get_volume_idxs_from_instance(), Slic3r::GUI::Selection::get_volume_idxs_from_volume(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::processed_objects_idxs(), Slic3r::GUI::Selection::synchronize_unselected_instances(), Slic3r::GUI::Selection::translate(), and Slic3r::GUI::GLGizmoMeasure::update_if_needed().
is_below_printbed()
bool Slic3r::GLVolume::is_below_printbed () const
{
    return transformed_convex_hull_bounding_box().max.z() < 0.0;
}
References Slic3r::BoundingBoxBase< PointType, APointsType >::max, and transformed_convex_hull_bounding_box().
Referenced by set_render_color().
is_left_handed()
bool Slic3r::GLVolume::is_left_handed () const
{
    const Vec3d &m1 = m_instance_transformation.get_mirror();
    const Vec3d &m2 = m_volume_transformation.get_mirror();
    return m1.x() * m1.y() * m1.z() * m2.x() * m2.y() * m2.z() < 0.;
}
References Slic3r::Geometry::Transformation::get_mirror(), m_instance_transformation, and m_volume_transformation.
Referenced by render().
is_sinking()
bool Slic3r::GLVolume::is_sinking () const
{
    if (is_modifier || GUI::wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptSLA)
        return false;
    const BoundingBoxf3& box = transformed_convex_hull_bounding_box();
    return box.min.z() < SINKING_Z_THRESHOLD && box.max.z() >= SINKING_Z_THRESHOLD;
}
References Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::ptSLA, Slic3r::SINKING_Z_THRESHOLD, and transformed_convex_hull_bounding_box().
Referenced by Slic3r::GUI::Selection::set_caches().
is_sla_pad()
bool Slic3r::GLVolume::is_sla_pad () const
{ return this->composite_id.volume_id == -int(slaposPad); }
References composite_id, Slic3r::slaposPad, and Slic3r::GLVolume::CompositeID::volume_id.
Referenced by Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking().
is_sla_support()
bool Slic3r::GLVolume::is_sla_support () const
{ return this->composite_id.volume_id == -int(slaposSupportTree); }
References composite_id, Slic3r::slaposSupportTree, and Slic3r::GLVolume::CompositeID::volume_id.
Referenced by Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking().
object_idx()
int Slic3r::GLVolume::object_idx () const inline
{ return this->composite_id.object_id; }
References Slic3r::GLVolume::CompositeID::object_id.
Referenced by Slic3r::GUI::GLCanvas3D::_update_selection_from_hover(), Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), Slic3r::GUI::MenuFactory::append_menu_item_edit_text(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::Selection::do_remove_instance(), Slic3r::GUI::Selection::do_remove_object(), Slic3r::GUI::Selection::erase(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::GUI::get_model_object(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::Selection::get_volume_idxs_from_instance(), Slic3r::GUI::Selection::get_volume_idxs_from_object(), Slic3r::GUI::Selection::get_volume_idxs_from_volume(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_text(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::processed_objects_idxs(), Slic3r::GUI::reloadable_volumes(), Slic3r::GUI::Selection::remove_volume(), Slic3r::GUI::Selection::render_synchronized_volumes(), Slic3r::GUI::Plater::priv::replace_with_stl(), priv::start_create_volume_on_surface_job(), Slic3r::GUI::Selection::synchronize_unselected_instances(), Slic3r::GUI::Selection::synchronize_unselected_volumes(), transformed_non_sinking_bounding_box(), Slic3r::GUI::Selection::translate(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GLVolume::NonManifoldEdges::update(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::Selection::update_type().
render()
void Slic3r::GLVolume::render ()
{
    if (!is_active)
        return;
    GLShaderProgram* shader = GUI::wxGetApp().get_current_shader();
    if (shader == nullptr)
        return;
    const bool is_left_handed = this->is_left_handed();
    if (is_left_handed)
        glsafe(::glFrontFace(GL_CW));
    glsafe(::glCullFace(GL_BACK));
    if (tverts_range == std::make_pair<size_t, size_t>(0, -1))
        model.render();
    else
        model.render(this->tverts_range);
    if (is_left_handed)
        glsafe(::glFrontFace(GL_CCW));
}
References glsafe, is_left_handed(), model, Slic3r::GUI::GLModel::render(), and tverts_range.
render_non_manifold_edges()
void Slic3r::GLVolume::render_non_manifold_edges ()
{
    m_non_manifold_edges.render();
}
References m_non_manifold_edges, and Slic3r::GLVolume::NonManifoldEdges::render().
render_sinking_contours()
void Slic3r::GLVolume::render_sinking_contours ()
{
    m_sinking_contours.render();
}
References m_sinking_contours, and Slic3r::GLVolume::SinkingContours::render().
set_bounding_boxes_as_dirty()
void Slic3r::GLVolume::set_bounding_boxes_as_dirty () inline
{
        m_transformed_bounding_box.reset();
        m_transformed_convex_hull_bounding_box.reset();
        m_transformed_non_sinking_bounding_box.reset();
    }
References m_transformed_bounding_box, m_transformed_convex_hull_bounding_box, and m_transformed_non_sinking_bounding_box.
Referenced by set_instance_mirror(), set_instance_mirror(), set_instance_offset(), set_instance_offset(), set_instance_rotation(), set_instance_rotation(), set_instance_scaling_factor(), set_instance_scaling_factor(), set_instance_transformation(), set_instance_transformation(), set_volume_mirror(), set_volume_mirror(), set_volume_offset(), set_volume_offset(), set_volume_rotation(), set_volume_rotation(), set_volume_scaling_factor(), set_volume_scaling_factor(), set_volume_transformation(), and set_volume_transformation().
set_color()
void Slic3r::GLVolume::set_color (const ColorRGBA & rgba) inline
{ color = rgba; }
References color.
Referenced by Slic3r::GLVolumeCollection::load_object_volume(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
set_color_from_model_volume()
void Slic3r::GLVolume::set_color_from_model_volume (const ModelVolume & model_volume)
set_convex_hull() [1/3]
void Slic3r::GLVolume::set_convex_hull (const TriangleMesh & convex_hull) inline
{ m_convex_hull = std::make_shared<const TriangleMesh>(convex_hull); }
References convex_hull(), and m_convex_hull.
set_convex_hull() [2/3]
void Slic3r::GLVolume::set_convex_hull (std::shared_ptr< const TriangleMesh > convex_hull) inline
{ m_convex_hull = std::move(convex_hull); }
References convex_hull(), and m_convex_hull.
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), and Slic3r::GLVolumeCollection::load_wipe_tower_preview().
set_convex_hull() [3/3]
void Slic3r::GLVolume::set_convex_hull (TriangleMesh && convex_hull) inline
{ m_convex_hull = std::make_shared<const TriangleMesh>(std::move(convex_hull)); }
References convex_hull(), and m_convex_hull.
set_instance_mirror() [1/2]
void Slic3r::GLVolume::set_instance_mirror (Axis axis, double mirror) inline
{ m_instance_transformation.set_mirror(axis, mirror); set_bounding_boxes_as_dirty(); }
References m_instance_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_mirror().
set_instance_mirror() [2/2]
void Slic3r::GLVolume::set_instance_mirror (const Vec3d & mirror) inline
{ m_instance_transformation.set_mirror(mirror); set_bounding_boxes_as_dirty(); }
References m_instance_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_mirror().
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells().
set_instance_offset() [1/2]
void Slic3r::GLVolume::set_instance_offset (Axis axis, double offset) inline
{ m_instance_transformation.set_offset(axis, offset); set_bounding_boxes_as_dirty(); }
References m_instance_transformation, Slic3r::offset(), set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_offset().
set_instance_offset() [2/2]
void Slic3r::GLVolume::set_instance_offset (const Vec3d & offset) inline
{ m_instance_transformation.set_offset(offset); set_bounding_boxes_as_dirty(); }
References m_instance_transformation, Slic3r::offset(), set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_offset().
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), and Slic3r::GUI::Selection::translate().
set_instance_rotation() [1/2]
void Slic3r::GLVolume::set_instance_rotation (Axis axis, double rotation) inline
{ m_instance_transformation.set_rotation(axis, rotation); set_bounding_boxes_as_dirty(); }
References m_instance_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_rotation().
set_instance_rotation() [2/2]
void Slic3r::GLVolume::set_instance_rotation (const Vec3d & rotation) inline
{ m_instance_transformation.set_rotation(rotation); set_bounding_boxes_as_dirty(); }
References m_instance_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_rotation().
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells().
set_instance_scaling_factor() [1/2]
void Slic3r::GLVolume::set_instance_scaling_factor (Axis axis, double scaling_factor) inline
{ m_instance_transformation.set_scaling_factor(axis, scaling_factor); set_bounding_boxes_as_dirty(); }
References m_instance_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_scaling_factor().
set_instance_scaling_factor() [2/2]
void Slic3r::GLVolume::set_instance_scaling_factor (const Vec3d & scaling_factor) inline
{ m_instance_transformation.set_scaling_factor(scaling_factor); set_bounding_boxes_as_dirty(); }
References m_instance_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_scaling_factor().
set_instance_transformation() [1/2]
void Slic3r::GLVolume::set_instance_transformation (const Geometry::Transformation & transformation) inline
{ m_instance_transformation = transformation; set_bounding_boxes_as_dirty(); }
References m_instance_transformation, and set_bounding_boxes_as_dirty().
Referenced by Slic3r::GUI::Selection::flattening_rotate(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::Selection::reset_skew(), Slic3r::GUI::Selection::scale_and_translate(), Slic3r::GUI::Selection::synchronize_unselected_instances(), Slic3r::GUI::Selection::translate(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
set_instance_transformation() [2/2]
void Slic3r::GLVolume::set_instance_transformation (const Transform3d & transform) inline
{ m_instance_transformation.set_matrix(transform); set_bounding_boxes_as_dirty(); }
References m_instance_transformation, set_bounding_boxes_as_dirty(), Slic3r::Geometry::Transformation::set_matrix(), and Slic3r::transform().
set_range()
void Slic3r::GLVolume::set_range (double low, double high)
{
    this->tverts_range.first = 0;
    this->tverts_range.second = this->model.indices_count();
    if (!this->print_zs.empty()) {
        // The Z layer range is specified.
        // First test whether the Z span of this object is not out of (min_z, max_z) completely.
        if (this->print_zs.front() > max_z || this->print_zs.back() < min_z)
            this->tverts_range.second = 0;
        else {
            // Then find the lowest layer to be displayed.
            size_t i = 0;
            for (; i < this->print_zs.size() && this->print_zs[i] < min_z; ++i);
            if (i == this->print_zs.size())
                // This shall not happen.
                this->tverts_range.second = 0;
            else {
                // Remember start of the layer.
                this->tverts_range.first = this->offsets[i];
                // Some layers are above $min_z. Which?
                for (; i < this->print_zs.size() && this->print_zs[i] <= max_z; ++i);
                if (i < this->print_zs.size())
                    this->tverts_range.second = this->offsets[i];
            }
        }
    }
}
References Slic3r::GUI::GLModel::indices_count(), model, offsets, print_zs, and tverts_range.
set_render_color() [1/2]
void Slic3r::GLVolume::set_render_color (bool force_transparent)
{
    bool outside = is_outside || is_below_printbed();
    if (force_native_color || force_neutral_color) {
        if (outside && shader_outside_printer_detection_enabled)
            set_render_color(OUTSIDE_COLOR);
        else {
            if (force_native_color)
                set_render_color(color);
            else
                set_render_color(NEUTRAL_COLOR);
        }
    }
    else {
        if (hover == HS_Select)
            set_render_color(HOVER_SELECT_COLOR);
        else if (hover == HS_Deselect)
            set_render_color(HOVER_DESELECT_COLOR);
        else if (selected)
            set_render_color(outside ? SELECTED_OUTSIDE_COLOR : SELECTED_COLOR);
        else if (disabled)
            set_render_color(DISABLED_COLOR);
        else if (outside && shader_outside_printer_detection_enabled)
            set_render_color(OUTSIDE_COLOR);
        else
            set_render_color(color);
    }
    if (!printable)
        render_color = saturate(render_color, 0.25f);
    if (force_transparent)
        render_color.a(color.a());
}
References Slic3r::ColorRGBA::a(), color, DISABLED_COLOR, hover, HOVER_DESELECT_COLOR, HOVER_SELECT_COLOR, HS_Deselect, HS_Select, is_below_printbed(), NEUTRAL_COLOR, OUTSIDE_COLOR, render_color, Slic3r::saturate(), SELECTED_COLOR, SELECTED_OUTSIDE_COLOR, and set_render_color().
set_render_color() [2/2]
void Slic3r::GLVolume::set_render_color (const ColorRGBA & rgba) inline
{ render_color = rgba; }
References render_color.
Referenced by GLVolume(), and set_render_color().
set_sla_shift_z()
void Slic3r::GLVolume::set_sla_shift_z (double z) inline
{ m_sla_shift_z = z; }
References m_sla_shift_z.
Referenced by Slic3r::GUI::GLGizmoSlaBase::update_volumes().
set_volume_mirror() [1/2]
void Slic3r::GLVolume::set_volume_mirror (Axis axis, double mirror) inline
{ m_volume_transformation.set_mirror(axis, mirror); set_bounding_boxes_as_dirty(); }
References m_volume_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_mirror().
set_volume_mirror() [2/2]
void Slic3r::GLVolume::set_volume_mirror (const Vec3d & mirror) inline
{ m_volume_transformation.set_mirror(mirror); set_bounding_boxes_as_dirty(); }
References m_volume_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_mirror().
set_volume_offset() [1/2]
void Slic3r::GLVolume::set_volume_offset (Axis axis, double offset) inline
{ m_volume_transformation.set_offset(axis, offset); set_bounding_boxes_as_dirty(); }
References m_volume_transformation, Slic3r::offset(), set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_offset().
set_volume_offset() [2/2]
void Slic3r::GLVolume::set_volume_offset (const Vec3d & offset) inline
{ m_volume_transformation.set_offset(offset); set_bounding_boxes_as_dirty(); }
References m_volume_transformation, Slic3r::offset(), set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_offset().
Referenced by Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), and Slic3r::GUI::Selection::translate().
set_volume_rotation() [1/2]
void Slic3r::GLVolume::set_volume_rotation (Axis axis, double rotation) inline
{ m_volume_transformation.set_rotation(axis, rotation); set_bounding_boxes_as_dirty(); }
References m_volume_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_rotation().
set_volume_rotation() [2/2]
void Slic3r::GLVolume::set_volume_rotation (const Vec3d & rotation) inline
{ m_volume_transformation.set_rotation(rotation); set_bounding_boxes_as_dirty(); }
References m_volume_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_rotation().
Referenced by Slic3r::GLVolumeCollection::load_wipe_tower_preview().
set_volume_scaling_factor() [1/2]
void Slic3r::GLVolume::set_volume_scaling_factor (Axis axis, double scaling_factor) inline
{ m_volume_transformation.set_scaling_factor(axis, scaling_factor); set_bounding_boxes_as_dirty(); }
References m_volume_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_scaling_factor().
set_volume_scaling_factor() [2/2]
void Slic3r::GLVolume::set_volume_scaling_factor (const Vec3d & scaling_factor) inline
{ m_volume_transformation.set_scaling_factor(scaling_factor); set_bounding_boxes_as_dirty(); }
References m_volume_transformation, set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_scaling_factor().
set_volume_transformation() [1/2]
void Slic3r::GLVolume::set_volume_transformation (const Geometry::Transformation & transformation) inline
{ m_volume_transformation = transformation; set_bounding_boxes_as_dirty(); }
References m_volume_transformation, and set_bounding_boxes_as_dirty().
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), priv::apply_camera_dir(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::Selection::reset_skew(), Slic3r::GUI::Selection::synchronize_unselected_volumes(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
set_volume_transformation() [2/2]
void Slic3r::GLVolume::set_volume_transformation (const Transform3d & transform) inline
{ m_volume_transformation.set_matrix(transform); set_bounding_boxes_as_dirty(); }
References m_volume_transformation, set_bounding_boxes_as_dirty(), Slic3r::Geometry::Transformation::set_matrix(), and Slic3r::transform().
total_memory_used()
size_t Slic3r::GLVolume::total_memory_used () const inline
{ return this->cpu_memory_used() + this->gpu_memory_used(); }
References cpu_memory_used(), and gpu_memory_used().
transformed_bounding_box()
const BoundingBoxf3 & Slic3r::GLVolume::transformed_bounding_box () const
{
    if (!m_transformed_bounding_box.has_value()) {
        const BoundingBoxf3& box = bounding_box();
        assert(box.defined || box.min.x() >= box.max.x() || box.min.y() >= box.max.y() || box.min.z() >= box.max.z());
        std::optional<BoundingBoxf3>* trans_box = const_cast<std::optional<BoundingBoxf3>*>(&m_transformed_bounding_box);
        *trans_box = box.transformed(world_matrix());
    }
    return *m_transformed_bounding_box;
}
References bounding_box(), Slic3r::BoundingBoxBase< PointType, APointsType >::defined, m_transformed_bounding_box, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::BoundingBoxf3::transformed(), and world_matrix().
transformed_convex_hull_bounding_box() [1/2]
const BoundingBoxf3 & Slic3r::GLVolume::transformed_convex_hull_bounding_box () const
{
    if (!m_transformed_convex_hull_bounding_box.has_value()) {
        std::optional<BoundingBoxf3>* trans_box = const_cast<std::optional<BoundingBoxf3>*>(&m_transformed_convex_hull_bounding_box);
        *trans_box = transformed_convex_hull_bounding_box(world_matrix());
    }
    return *m_transformed_convex_hull_bounding_box;
}
References m_transformed_convex_hull_bounding_box, transformed_convex_hull_bounding_box(), and world_matrix().
Referenced by is_below_printbed(), is_sinking(), and transformed_convex_hull_bounding_box().
transformed_convex_hull_bounding_box() [2/2]
BoundingBoxf3 Slic3r::GLVolume::transformed_convex_hull_bounding_box (const Transform3d & trafo) const
{
  return (m_convex_hull && ! m_convex_hull->empty()) ?
    m_convex_hull->transformed_bounding_box(trafo) :
        bounding_box().transformed(trafo);
}
References bounding_box(), m_convex_hull, and Slic3r::BoundingBoxf3::transformed().
Referenced by Slic3r::GUI::Selection::render_synchronized_volumes().
transformed_non_sinking_bounding_box() [1/2]
const BoundingBoxf3 & Slic3r::GLVolume::transformed_non_sinking_bounding_box () const
{
    if (!m_transformed_non_sinking_bounding_box.has_value()) {
        std::optional<BoundingBoxf3>* trans_box = const_cast<std::optional<BoundingBoxf3>*>(&m_transformed_non_sinking_bounding_box);
        const Transform3d& trafo = world_matrix();
        *trans_box = transformed_non_sinking_bounding_box(trafo);
    }
    return *m_transformed_non_sinking_bounding_box;
}
References m_transformed_non_sinking_bounding_box, transformed_non_sinking_bounding_box(), and world_matrix().
Referenced by transformed_non_sinking_bounding_box().
transformed_non_sinking_bounding_box() [2/2]
BoundingBoxf3 Slic3r::GLVolume::transformed_non_sinking_bounding_box (const Transform3d & trafo) const
{
    return GUI::wxGetApp().plater()->model().objects[object_idx()]->volumes[volume_idx()]->mesh().transformed_bounding_box(trafo, 0.0);
}
References object_idx(), and volume_idx().
volume_idx()
int Slic3r::GLVolume::volume_idx () const inline
{ return this->composite_id.volume_id; }
References Slic3r::GLVolume::CompositeID::volume_id.
Referenced by Slic3r::GUI::GLCanvas3D::_update_selection_from_hover(), Slic3r::GUI::MenuFactory::append_menu_item_edit_text(), Slic3r::GUI::Selection::erase(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::Plater::priv::get_selected_volume_idx(), Slic3r::GUI::Selection::get_volume_idxs_from_object(), Slic3r::GUI::Selection::get_volume_idxs_from_volume(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_text(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::reloadable_volumes(), Slic3r::GUI::Selection::remove_volume(), Slic3r::GUI::Selection::render_synchronized_volumes(), Slic3r::GUI::Plater::priv::replace_with_stl(), priv::start_create_volume_on_surface_job(), Slic3r::GUI::Selection::synchronize_unselected_volumes(), transformed_non_sinking_bounding_box(), Slic3r::GLVolume::NonManifoldEdges::update(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
world_matrix()
Transform3d Slic3r::GLVolume::world_matrix () const
{
    Transform3d m = m_instance_transformation.get_matrix() * m_volume_transformation.get_matrix();
    m.translation()(2) += m_sla_shift_z;
    return m;
}
References Slic3r::Geometry::Transformation::get_matrix(), m_instance_transformation, m_sla_shift_z, m_volume_transformation, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by Slic3r::GUI::GLGizmoEmboss::calculate_scale(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoEmboss::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::Selection::render_synchronized_volumes(), Slic3r::GUI::Selection::scale_to_fit_print_volume(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), transformed_bounding_box(), transformed_convex_hull_bounding_box(), transformed_non_sinking_bounding_box(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), and Slic3r::GUI::world_matrix_fixed().
Member Data Documentation
[struct]
struct { ... } Slic3r::GLVolume
color
ColorRGBA Slic3r::GLVolume::color
Referenced by GLVolume(), Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::GUI::GLGizmoSimplify::init_model(), set_color(), and set_render_color().
composite_id
CompositeID Slic3r::GLVolume::composite_id
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GUI::get_selected_gl_volume(), Slic3r::GUI::get_volume(), Slic3r::GUI::get_volume_ids(), Slic3r::GUI::GLGizmoSimplify::init_model(), is_sla_pad(), is_sla_support(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_render(), and Slic3r::GUI::GLCanvas3D::reload_scene().
DISABLED_COLOR
const ColorRGBA Slic3r::GLVolume::DISABLED_COLOR = ColorRGBA::DARK_GRAY() static
Referenced by set_render_color().
extruder_id
int Slic3r::GLVolume::extruder_id
Referenced by Slic3r::GLVolumeCollection::load_object_volume().
geometry_id
std::pair<size_t, size_t> Slic3r::GLVolume::geometry_id
Referenced by Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::GLCanvas3D::reload_scene(), and Slic3r::UndoRedo::StackImpl::take_snapshot().
hover
EHoverState Slic3r::GLVolume::hover
Referenced by Slic3r::GUI::Selection::do_add_volume(), and set_render_color().
HOVER_DESELECT_COLOR
const ColorRGBA Slic3r::GLVolume::HOVER_DESELECT_COLOR = { 1.0f, 0.75f, 0.75f, 1.0f } static
Referenced by set_render_color().
HOVER_SELECT_COLOR
const ColorRGBA Slic3r::GLVolume::HOVER_SELECT_COLOR = { 0.4f, 0.9f, 0.1f, 1.0f } static
Referenced by set_render_color().
m_convex_hull
std::shared_ptr<const TriangleMesh> Slic3r::GLVolume::m_convex_hull private
Referenced by convex_hull(), set_convex_hull(), set_convex_hull(), set_convex_hull(), and transformed_convex_hull_bounding_box().
m_instance_transformation
Geometry::Transformation Slic3r::GLVolume::m_instance_transformation private
Referenced by get_instance_mirror(), get_instance_mirror(), get_instance_offset(), get_instance_offset(), get_instance_rotation(), get_instance_rotation(), get_instance_scaling_factor(), get_instance_scaling_factor(), get_instance_transformation(), is_left_handed(), set_instance_mirror(), set_instance_mirror(), set_instance_offset(), set_instance_offset(), set_instance_rotation(), set_instance_rotation(), set_instance_scaling_factor(), set_instance_scaling_factor(), set_instance_transformation(), set_instance_transformation(), and world_matrix().
m_non_manifold_edges
NonManifoldEdges Slic3r::GLVolume::m_non_manifold_edges private
Referenced by render_non_manifold_edges().
m_sinking_contours
SinkingContours Slic3r::GLVolume::m_sinking_contours private
Referenced by render_sinking_contours().
m_sla_shift_z
double Slic3r::GLVolume::m_sla_shift_z private
Referenced by get_sla_shift_z(), set_sla_shift_z(), and world_matrix().
m_transformed_bounding_box
std::optional<BoundingBoxf3> Slic3r::GLVolume::m_transformed_bounding_box private
Referenced by set_bounding_boxes_as_dirty(), and transformed_bounding_box().
m_transformed_convex_hull_bounding_box
std::optional<BoundingBoxf3> Slic3r::GLVolume::m_transformed_convex_hull_bounding_box private
Referenced by set_bounding_boxes_as_dirty(), and transformed_convex_hull_bounding_box().
m_transformed_non_sinking_bounding_box
std::optional<BoundingBoxf3> Slic3r::GLVolume::m_transformed_non_sinking_bounding_box private
Referenced by set_bounding_boxes_as_dirty(), and transformed_non_sinking_bounding_box().
m_volume_transformation
Geometry::Transformation Slic3r::GLVolume::m_volume_transformation private
Referenced by get_volume_mirror(), get_volume_mirror(), get_volume_offset(), get_volume_offset(), get_volume_rotation(), get_volume_rotation(), get_volume_scaling_factor(), get_volume_scaling_factor(), get_volume_transformation(), is_left_handed(), set_volume_mirror(), set_volume_mirror(), set_volume_offset(), set_volume_offset(), set_volume_rotation(), set_volume_rotation(), set_volume_scaling_factor(), set_volume_scaling_factor(), set_volume_transformation(), set_volume_transformation(), and world_matrix().
mesh_raycaster
std::unique_ptr<GUI::MeshRaycaster> Slic3r::GLVolume::mesh_raycaster
Referenced by Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLCanvas3D::reload_scene(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
model
GUI::GLModel Slic3r::GLVolume::model
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), render(), set_range(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GLVolume::NonManifoldEdges::update(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
MODEL_COLOR
const std::array< ColorRGBA, 4 > Slic3r::GLVolume::MODEL_COLOR static
Initial value:
= { {
    ColorRGBA::YELLOW(),
    { 1.0f, 0.5f, 0.5f, 1.0f },
    { 0.5f, 1.0f, 0.5f, 1.0f },
    { 0.5f, 0.5f, 1.0f, 1.0f }
} }
Referenced by Slic3r::GLVolumeCollection::load_object_auxiliary().
NEUTRAL_COLOR
const ColorRGBA Slic3r::GLVolume::NEUTRAL_COLOR = { 0.9f, 0.9f, 0.9f, 1.0f } static
Referenced by Slic3r::GUI::TriangleSelectorGUI::render(), and set_render_color().
offsets
std::vector<size_t> Slic3r::GLVolume::offsets
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), and set_range().
OUTSIDE_COLOR
const ColorRGBA Slic3r::GLVolume::OUTSIDE_COLOR = { 0.0f, 0.38f, 0.8f, 1.0f } static
Referenced by set_render_color().
print_zs
std::vector<coordf_t> Slic3r::GLVolume::print_zs
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), and set_range().
render_color
ColorRGBA Slic3r::GLVolume::render_color
Referenced by set_render_color(), and set_render_color().
SELECTED_COLOR
const ColorRGBA Slic3r::GLVolume::SELECTED_COLOR = ColorRGBA::GREEN() static
Referenced by Slic3r::GUI::GLGizmoMeasure::on_render(), and set_render_color().
SELECTED_OUTSIDE_COLOR
const ColorRGBA Slic3r::GLVolume::SELECTED_OUTSIDE_COLOR = { 0.19f, 0.58f, 1.0f, 1.0f } static
Referenced by set_render_color().
SLA_PAD_COLOR
const ColorRGBA Slic3r::GLVolume::SLA_PAD_COLOR = { 0.0f, 0.2f, 0.0f, 1.0f } static
Referenced by Slic3r::GLVolumeCollection::load_object_auxiliary().
SLA_SUPPORT_COLOR
const ColorRGBA Slic3r::GLVolume::SLA_SUPPORT_COLOR = ColorRGBA::LIGHT_GRAY() static
Referenced by Slic3r::GLVolumeCollection::load_object_auxiliary().
tverts_range
std::pair<size_t, size_t> Slic3r::GLVolume::tverts_range
Referenced by render(), and set_range().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DScene.hpp
src/slic3r/GUI/3DScene.cpp