Prusa Slicer: Slic3r::GUI::GCodeViewer::InstanceVBuffer Struct Reference
Slic3r::GUI::GCodeViewer::InstanceVBuffer Struct Reference
Classes
struct Ranges
Public Types
enum class EFormat : unsigned char { InstancedModel , BatchedModel }
Public Member Functions
size_t data_size_bytes () const
size_t instance_size_floats () const
size_t instance_size_bytes () const
void reset ()
Public Attributes
EFormat format
InstanceBuffer buffer
std::vector< size_t > s_ids
InstancesOffsets offsets
Ranges render_ranges
Detailed Description
Member Enumeration Documentation
EFormat
enum class Slic3r::GUI::GCodeViewer::InstanceVBuffer::EFormat : unsigned char strong
Enumerator
InstancedModel
BatchedModel
        {
            InstancedModel,
            BatchedModel
        };
Member Function Documentation
data_size_bytes()
size_t Slic3r::GUI::GCodeViewer::InstanceVBuffer::data_size_bytes () const inline
{ return s_ids.size() * instance_size_bytes(); }
References instance_size_bytes(), and s_ids.
instance_size_bytes()
size_t Slic3r::GUI::GCodeViewer::InstanceVBuffer::instance_size_bytes () const inline
{ return instance_size_floats() * sizeof(float); }
References instance_size_floats().
Referenced by data_size_bytes(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
instance_size_floats()
size_t Slic3r::GUI::GCodeViewer::InstanceVBuffer::instance_size_floats () const inline
{
            switch (format)
            {
            case EFormat::InstancedModel: { return 5; }
            case EFormat::BatchedModel: { return 3; }
            default: { return 0; }
            }
        }
References BatchedModel, format, and InstancedModel.
Referenced by instance_size_bytes(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
reset()
void Slic3r::GUI::GCodeViewer::InstanceVBuffer::reset ()
{
    s_ids.clear();
    buffer.clear();
    render_ranges.reset();
}
Member Data Documentation
buffer
InstanceBuffer Slic3r::GUI::GCodeViewer::InstanceVBuffer::buffer
Referenced by Slic3r::GUI::GCodeViewer::TBuffer::has_data(), Slic3r::GUI::GCodeViewer::load_toolpaths(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
format
EFormat Slic3r::GUI::GCodeViewer::InstanceVBuffer::format
Referenced by Slic3r::GUI::GCodeViewer::init(), and instance_size_floats().
offsets
InstancesOffsets Slic3r::GUI::GCodeViewer::InstanceVBuffer::offsets
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
render_ranges
Ranges Slic3r::GUI::GCodeViewer::InstanceVBuffer::render_ranges
Referenced by Slic3r::GUI::GCodeViewer::refresh_render_paths(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
s_ids
std::vector<size_t> Slic3r::GUI::GCodeViewer::InstanceVBuffer::s_ids
Referenced by data_size_bytes(), Slic3r::GUI::GCodeViewer::load_toolpaths(), and Slic3r::GUI::GCodeViewer::refresh_render_paths().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GCodeViewer.hpp
src/slic3r/GUI/GCodeViewer.cpp