Prusa Slicer: Slic3r::Geometry::rotcalip Namespace Reference
Slic3r::Geometry::rotcalip Namespace Reference
Classes
class Idx
Typedefs
using int256_t = boost::multiprecision::int256_t
using int128_t = boost::multiprecision::int128_t
Enumerations
enum class AntipodalVisitMode { Full , EdgesOnly }
Functions
template<class Scalar = int64_t>
Scalar magnsq (const Point &p)
template<class Scalar = int64_t>
Scalar dot (const Point &a, const Point &b)
template<class Scalar = int64_t>
Scalar dotperp (const Point &a, const Point &b)
int cmp_angles (const Point &dir, const Point &dirA, const Point &dirB)
template<AntipodalVisitMode mode = AntipodalVisitMode::Full, class Fn >
void visit_antipodals (Idx &ia, Idx &ib, Fn &&fn)
Typedef Documentation
int128_t
using Slic3r::Geometry::rotcalip::int128_t = typedef boost::multiprecision::int128_t
int256_t
using Slic3r::Geometry::rotcalip::int256_t = typedef boost::multiprecision::int256_t
Enumeration Type Documentation
AntipodalVisitMode
enum class Slic3r::Geometry::rotcalip::AntipodalVisitMode strong
Enumerator
Full
EdgesOnly
{ Full, EdgesOnly };
Function Documentation
cmp_angles()
int Slic3r::Geometry::rotcalip::cmp_angles (const Point & dir, const Point & dirA, const Point & dirB)
{
    int128_t dotA = dot(dir, dirA);
    int128_t dotB = dot(-dir, dirB);
    int256_t dcosa = int256_t(magnsq(dirB)) * int256_t(abs(dotA)) * dotA;
    int256_t dcosb = int256_t(magnsq(dirA)) * int256_t(abs(dotB)) * dotB;
    int256_t diff = dcosa - dcosb;
    return diff > 0? -1 : (diff < 0 ? 1 : 0);
}
References Slic3r::diff(), dot(), and magnsq().
Referenced by visit_antipodals().
dot()
template<class Scalar = int64_t> Scalar Slic3r::Geometry::rotcalip::dot (const Point & a, const Point & b) inline
{
    return Scalar(a.x()) * b.x() + Scalar(a.y()) * b.y();
}
Referenced by cmp_angles().
dotperp()
template<class Scalar = int64_t> Scalar Slic3r::Geometry::rotcalip::dotperp (const Point & a, const Point & b) inline
{
    return Scalar(a.x()) * b.y() - Scalar(a.y()) * b.x();
}
magnsq()
template<class Scalar = int64_t> Scalar Slic3r::Geometry::rotcalip::magnsq (const Point & p) inline
{
    return Scalar(p.x()) * p.x() + Scalar(p.y()) * p.y();
}
Referenced by cmp_angles().
visit_antipodals()
template<AntipodalVisitMode mode = AntipodalVisitMode::Full, class Fn > void Slic3r::Geometry::rotcalip::visit_antipodals (Idx & ia, Idx & ib, Fn && fn)
{
    // Set current caliper direction to be the lower edge angle from X axis
    int cmp = cmp_angles(ia.prev_dir(), ia.dir(), ib.dir());
    Idx *current = cmp <= 0 ? &ia : &ib, *other = cmp <= 0 ? &ib : &ia;
    Idx *initial = current;
    bool visitor_continue = true;
    size_t start = initial->idx();
    bool finished = false;
    while (visitor_continue && !finished) {
        Point current_dir_a = current == &ia ? current->dir() : -current->dir();
        visitor_continue = fn(ia.idx(), ib.idx(), current_dir_a);
        // Parallel edges encountered. An additional pair of antipodals
        // can be yielded.
        if constexpr (mode == AntipodalVisitMode::Full)
            if (cmp == 0 && visitor_continue) {
                visitor_continue = fn(current == &ia ? ia.idx() : ia.next(),
                                      current == &ib ? ib.idx() : ib.next(),
                                      current_dir_a);
            }
        cmp = cmp_angles(current->dir(), current->next_dir(), other->dir());
        current->inc();
        if (cmp > 0) {
            std::swap(current, other);
        }
        if (initial->idx() == start) finished = true;
    }
}
References cmp_angles(), Slic3r::Geometry::rotcalip::Idx::dir(), Full, Slic3r::Geometry::rotcalip::Idx::idx(), Slic3r::Geometry::rotcalip::Idx::inc(), Slic3r::Geometry::rotcalip::Idx::next(), Slic3r::Geometry::rotcalip::Idx::next_dir(), and Slic3r::Geometry::rotcalip::Idx::prev_dir().