Prusa Slicer: Slic3r::Utils::TCPConsole Class Reference
Slic3r::Utils::TCPConsole Class Reference
#include <src/slic3r/Utils/TCPConsole.hpp>
Public Member Functions
TCPConsole ()
TCPConsole (const std::string &host_name, const std::string &port_name)
~TCPConsole ()=default
void set_defaults ()
void set_line_delimiter (const std::string &newline)
void set_command_done_string (const std::string &done_string)
void set_remote (const std::string &host_name, const std::string &port_name)
bool enqueue_cmd (const std::string &cmd)
bool run_queue ()
std::string error_message () const
Private Member Functions
void handle_connect (const boost::system::error_code &ec)
void handle_read (const boost::system::error_code &ec, std::size_t bytes_transferred)
void handle_write (const boost::system::error_code &ec, std::size_t bytes_transferred)
void transmit_next_command ()
void wait_next_line ()
std::string extract_next_line ()
void set_deadline_in (std::chrono::steady_clock::duration)
bool is_deadline_over () const
Private Attributes
std::string m_host_name
std::string m_port_name
std::string m_newline
std::string m_done_string
std::chrono::steady_clock::duration m_connect_timeout
std::chrono::steady_clock::duration m_write_timeout
std::chrono::steady_clock::duration m_read_timeout
std::deque< std::string > m_cmd_queue
boost::asio::io_context m_io_context
tcp::resolver m_resolver
tcp::socket m_socket
boost::asio::streambuf m_recv_buffer
std::string m_send_buffer
bool m_is_connected
boost::system::error_code m_error_code
std::chrono::steady_clock::time_point m_deadline
Detailed Description
Constructor & Destructor Documentation
TCPConsole() [1/2]
Slic3r::Utils::TCPConsole::TCPConsole () inline
: m_resolver(m_io_context), m_socket(m_io_context) { set_defaults(); }
References set_defaults().
TCPConsole() [2/2]
Slic3r::Utils::TCPConsole::TCPConsole (const std::string & host_name, const std::string & port_name) inline
                                                                       : m_resolver(m_io_context), m_socket(m_io_context)
        { set_defaults(); set_remote(host_name, port_name); }
References set_defaults(), and set_remote().
~TCPConsole()
Slic3r::Utils::TCPConsole::~TCPConsole () default
Member Function Documentation
enqueue_cmd()
bool Slic3r::Utils::TCPConsole::enqueue_cmd (const std::string & cmd) inline
{
        // TODO: Add multithread protection to queue
        m_cmd_queue.push_back(cmd);
        return true;
    }
References cmd, and m_cmd_queue.
Referenced by Slic3r::MKS::start_print(), and Slic3r::MKS::test().
error_message()
std::string Slic3r::Utils::TCPConsole::error_message () const inline
{ return m_error_code.message(); }
References m_error_code.
Referenced by Slic3r::MKS::start_print(), and Slic3r::MKS::test().
extract_next_line()
std::string Slic3r::Utils::TCPConsole::extract_next_line () private
{
    char linebuf[1024];
    std::istream is(&m_recv_buffer);
    is.getline(linebuf, sizeof(linebuf));
    return is.good() ? linebuf : std::string{};
}
References m_recv_buffer.
Referenced by handle_read().
handle_connect()
void Slic3r::Utils::TCPConsole::handle_connect (const boost::system::error_code & ec) private
{
    m_error_code = ec;
    if (ec) {
        BOOST_LOG_TRIVIAL(error) << boost::format("TCPConsole: Can't connect to %1%:%2%: %3%")
            % m_host_name
            % m_port_name
            % ec.message();
        m_io_context.stop();
    }
    else {
        m_is_connected = true;
        BOOST_LOG_TRIVIAL(info) << boost::format("TCPConsole: connected to %1%:%2%")
            % m_host_name
            % m_port_name;
        transmit_next_command();
    }
}
References error, m_error_code, m_host_name, m_io_context, m_is_connected, m_port_name, and transmit_next_command().
Referenced by run_queue().
handle_read()
void Slic3r::Utils::TCPConsole::handle_read (const boost::system::error_code & ec, std::size_t bytes_transferred) private
{
    m_error_code = ec;
    if (ec) {
        BOOST_LOG_TRIVIAL(error) << boost::format("TCPConsole: Can't read from %1%:%2%: %3%")
            % m_host_name
            % m_port_name
            % ec.message();
        m_io_context.stop();
    }
    else {
        std::string line = extract_next_line();
        boost::trim(line);
        BOOST_LOG_TRIVIAL(debug) << boost::format("TCPConsole: received '%3%' from %1%:%2%")
            % m_host_name
            % m_port_name
            % line;
        boost::to_lower(line);
        if (line == m_done_string)
            transmit_next_command();
        else
            wait_next_line();
    }
}
References error, extract_next_line(), m_done_string, m_error_code, m_host_name, m_io_context, m_port_name, transmit_next_command(), and wait_next_line().
Referenced by wait_next_line().
handle_write()
void Slic3r::Utils::TCPConsole::handle_write (const boost::system::error_code & ec, std::size_t bytes_transferred) private
{
    m_error_code = ec;
    if (ec) {
        BOOST_LOG_TRIVIAL(error) << boost::format("TCPConsole: Can't write to %1%:%2%: %3%")
            % m_host_name
            % m_port_name
            % ec.message();
        m_io_context.stop();
    }
    else {
        wait_next_line();
    }
}
References error, m_error_code, m_host_name, m_io_context, m_port_name, and wait_next_line().
Referenced by transmit_next_command().
is_deadline_over()
bool Slic3r::Utils::TCPConsole::is_deadline_over () const private
{
    return m_deadline < std::chrono::steady_clock::now();
}
References m_deadline.
Referenced by run_queue().
run_queue()
bool Slic3r::Utils::TCPConsole::run_queue ()
{
    try {
        // TODO: Add more resets and initializations after previous run (reset() method?..)
        set_deadline_in(m_connect_timeout);
        m_is_connected = false;
        m_io_context.restart();
        auto endpoints = m_resolver.resolve(m_host_name, m_port_name);
        m_socket.async_connect(endpoints->endpoint(),
            boost::bind(&TCPConsole::handle_connect, this, boost::placeholders::_1)
        );
        // Loop until we get any reasonable result. Negative result is also result.
        // TODO: Rewrite to more graceful way using deadlime_timer
        bool timeout = false;
        while (!(timeout = is_deadline_over()) && !m_io_context.stopped()) {
            if (m_error_code) {
                m_io_context.stop();
            }
            m_io_context.run_for(boost::asio::chrono::milliseconds(100));
        }
        // Override error message if timeout is set
        if (timeout)
            m_error_code = make_error_code(boost::asio::error::timed_out);
        // Socket is not closed automatically by boost
        m_socket.close();
        if (m_error_code) {
            // We expect that message is logged in handler
            return false;
        }
        // It's expected to have empty queue after successful exchange
        if (!m_cmd_queue.empty()) {
            BOOST_LOG_TRIVIAL(error) << "TCPConsole: command queue is not empty after end of exchange";
            return false;
        }
    }
    catch (std::exception& e)
    {
        BOOST_LOG_TRIVIAL(error) << boost::format("TCPConsole: Exception while talking with %1%:%2%: %3%")
            % m_host_name
            % m_port_name
            % e.what();
        return false;
    }
    return true;
}
References error, handle_connect(), is_deadline_over(), m_cmd_queue, m_connect_timeout, m_error_code, m_host_name, m_io_context, m_is_connected, m_port_name, m_resolver, m_socket, and set_deadline_in().
Referenced by Slic3r::MKS::start_print(), and Slic3r::MKS::test().
set_command_done_string()
void Slic3r::Utils::TCPConsole::set_command_done_string (const std::string & done_string) inline
{
        m_done_string = done_string;
    }
References m_done_string.
set_deadline_in()
void Slic3r::Utils::TCPConsole::set_deadline_in (std::chrono::steady_clock::duration d) private
{
    m_deadline = std::chrono::steady_clock::now() + d;
}
References m_deadline.
Referenced by run_queue(), transmit_next_command(), and wait_next_line().
set_defaults()
void Slic3r::Utils::TCPConsole::set_defaults () inline
    {
        m_newline = "\n";
        m_done_string = "ok";
        m_connect_timeout = std::chrono::milliseconds(5000);
        m_write_timeout = std::chrono::milliseconds(10000);
        m_read_timeout = std::chrono::milliseconds(10000);
    }
References m_connect_timeout, m_done_string, m_newline, m_read_timeout, and m_write_timeout.
Referenced by TCPConsole(), and TCPConsole().
set_line_delimiter()
void Slic3r::Utils::TCPConsole::set_line_delimiter (const std::string & newline) inline
{
        m_newline = newline;
    }
References m_newline.
set_remote()
void Slic3r::Utils::TCPConsole::set_remote (const std::string & host_name, const std::string & port_name) inline
    {
        m_host_name = host_name;
        m_port_name = port_name;
    }
References m_host_name, and m_port_name.
Referenced by TCPConsole().
transmit_next_command()
void Slic3r::Utils::TCPConsole::transmit_next_command () private
{
    if (m_cmd_queue.empty()) {
        m_io_context.stop();
        return;
    }
    std::string cmd = m_cmd_queue.front();
    m_cmd_queue.pop_front();
    BOOST_LOG_TRIVIAL(debug) << boost::format("TCPConsole: transmitting '%3%' to %1%:%2%")
        % m_host_name
        % m_port_name
        % cmd;
    m_send_buffer = cmd + m_newline;
    set_deadline_in(m_write_timeout);
    boost::asio::async_write(
        m_socket,
        boost::asio::buffer(m_send_buffer),
        boost::bind(&TCPConsole::handle_write, this, boost::placeholders::_1, boost::placeholders::_2)
    );
}
References cmd, handle_write(), m_cmd_queue, m_host_name, m_io_context, m_newline, m_port_name, m_send_buffer, m_socket, m_write_timeout, and set_deadline_in().
Referenced by handle_connect(), and handle_read().
wait_next_line()
void Slic3r::Utils::TCPConsole::wait_next_line () private
{
    set_deadline_in(m_read_timeout);
    boost::asio::async_read_until(
        m_socket,
        m_recv_buffer,
        m_newline,
        boost::bind(&TCPConsole::handle_read, this, boost::placeholders::_1, boost::placeholders::_2)
    );
}
References handle_read(), m_newline, m_read_timeout, m_recv_buffer, m_socket, and set_deadline_in().
Referenced by handle_read(), and handle_write().
Member Data Documentation
m_cmd_queue
std::deque<std::string> Slic3r::Utils::TCPConsole::m_cmd_queue private
Referenced by enqueue_cmd(), run_queue(), and transmit_next_command().
m_connect_timeout
std::chrono::steady_clock::duration Slic3r::Utils::TCPConsole::m_connect_timeout private
Referenced by run_queue(), and set_defaults().
m_deadline
std::chrono::steady_clock::time_point Slic3r::Utils::TCPConsole::m_deadline private
Referenced by is_deadline_over(), and set_deadline_in().
m_done_string
std::string Slic3r::Utils::TCPConsole::m_done_string private
Referenced by handle_read(), set_command_done_string(), and set_defaults().
m_error_code
boost::system::error_code Slic3r::Utils::TCPConsole::m_error_code private
Referenced by error_message(), handle_connect(), handle_read(), handle_write(), and run_queue().
m_host_name
std::string Slic3r::Utils::TCPConsole::m_host_name private
Referenced by handle_connect(), handle_read(), handle_write(), run_queue(), set_remote(), and transmit_next_command().
m_io_context
boost::asio::io_context Slic3r::Utils::TCPConsole::m_io_context private
Referenced by handle_connect(), handle_read(), handle_write(), run_queue(), and transmit_next_command().
m_is_connected
bool Slic3r::Utils::TCPConsole::m_is_connected private
Referenced by handle_connect(), and run_queue().
m_newline
std::string Slic3r::Utils::TCPConsole::m_newline private
Referenced by set_defaults(), set_line_delimiter(), transmit_next_command(), and wait_next_line().
m_port_name
std::string Slic3r::Utils::TCPConsole::m_port_name private
Referenced by handle_connect(), handle_read(), handle_write(), run_queue(), set_remote(), and transmit_next_command().
m_read_timeout
std::chrono::steady_clock::duration Slic3r::Utils::TCPConsole::m_read_timeout private
Referenced by set_defaults(), and wait_next_line().
m_recv_buffer
boost::asio::streambuf Slic3r::Utils::TCPConsole::m_recv_buffer private
Referenced by extract_next_line(), and wait_next_line().
m_resolver
tcp::resolver Slic3r::Utils::TCPConsole::m_resolver private
Referenced by run_queue().
m_send_buffer
std::string Slic3r::Utils::TCPConsole::m_send_buffer private
Referenced by transmit_next_command().
m_socket
tcp::socket Slic3r::Utils::TCPConsole::m_socket private
Referenced by run_queue(), transmit_next_command(), and wait_next_line().
m_write_timeout
std::chrono::steady_clock::duration Slic3r::Utils::TCPConsole::m_write_timeout private
Referenced by set_defaults(), and transmit_next_command().
The documentation for this class was generated from the following files:
src/slic3r/Utils/TCPConsole.hpp
src/slic3r/Utils/TCPConsole.cpp