Prusa Slicer: Slic3r::LayerHeightProfile Class Reference
Slic3r::LayerHeightProfile Class Reference final
#include <src/libslic3r/Model.hpp>
Public Types
using Timestamp = uint64_t
Public Member Functions
void assign (const LayerHeightProfile &rhs)
void assign (LayerHeightProfile &&rhs)
const std::vector< coordf_t > & get () const throw ()
bool empty () const throw ()
void set (const std::vector< coordf_t > &data)
void set (std::vector< coordf_t > &&data)
void clear ()
template<class Archive >
void serialize (Archive &ar)
Timestamp timestamp () const override throw ()
bool timestamp_matches (const ObjectWithTimestamp &rhs) const throw ()
bool object_id_and_timestamp_match (const ObjectWithTimestamp &rhs) const throw ()
void touch ()
ObjectID id () const
Protected Member Functions
void copy_timestamp (const ObjectWithTimestamp &rhs)
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Private Member Functions
LayerHeightProfile ()=default
LayerHeightProfile (int)
LayerHeightProfile (const LayerHeightProfile &rhs)=default
LayerHeightProfile (LayerHeightProfile &&rhs)=default
LayerHeightProfile & operator= (const LayerHeightProfile &rhs)=default
LayerHeightProfile & operator= (LayerHeightProfile &&rhs)=default
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
std::vector< coordf_t > m_data
Timestamp m_timestamp { 1 }
ObjectID m_id
Static Private Attributes
static Timestamp s_last_timestamp = 1
static size_t s_last_id = 0
Friends
class ModelObject
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
LayerHeightProfile() [1/4]
Slic3r::LayerHeightProfile::LayerHeightProfile () explicit private default
LayerHeightProfile() [2/4]
Slic3r::LayerHeightProfile::LayerHeightProfile (int) inline explicit private
: ObjectWithTimestamp(-1) {}
LayerHeightProfile() [3/4]
Slic3r::LayerHeightProfile::LayerHeightProfile (const LayerHeightProfile & rhs) explicit private default
LayerHeightProfile() [4/4]
Slic3r::LayerHeightProfile::LayerHeightProfile (LayerHeightProfile && rhs) explicit private default
Member Function Documentation
assign() [1/2]
void Slic3r::LayerHeightProfile::assign (const LayerHeightProfile & rhs) inline
{ if (! this->timestamp_matches(rhs)) { m_data = rhs.m_data; this->copy_timestamp(rhs); } }
References Slic3r::ObjectWithTimestamp::copy_timestamp(), m_data, and Slic3r::ObjectWithTimestamp::timestamp_matches().
Referenced by Slic3r::GUI::Selection::copy_to_clipboard().
assign() [2/2]
void Slic3r::LayerHeightProfile::assign (LayerHeightProfile && rhs) inline
{ if (! this->timestamp_matches(rhs)) { m_data = std::move(rhs.m_data); this->copy_timestamp(rhs); } }
References Slic3r::ObjectWithTimestamp::copy_timestamp(), m_data, and Slic3r::ObjectWithTimestamp::timestamp_matches().
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
clear()
void Slic3r::LayerHeightProfile::clear () inline
{ m_data.clear(); this->touch(); }
References m_data, and Slic3r::ObjectWithTimestamp::touch().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
copy_timestamp()
void Slic3r::ObjectWithTimestamp::copy_timestamp (const ObjectWithTimestamp & rhs) inline protected inherited
{ m_timestamp = rhs.m_timestamp; }
References Slic3r::ObjectWithTimestamp::m_timestamp.
Referenced by Slic3r::FacetsAnnotation::assign(), assign(), Slic3r::FacetsAnnotation::assign(), and assign().
empty()
bool Slic3r::LayerHeightProfile::empty () const throw () inline
{ return m_data.empty(); }
References m_data.
Referenced by Slic3r::Print::apply(), Slic3r::ModelObject::has_custom_layering(), and Slic3r::GUI::ObjectList::update_info_items().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get()
const std::vector< coordf_t > & Slic3r::LayerHeightProfile::get () const throw () inline
{ return m_data; }
References m_data.
Referenced by Slic3r::PrintObject::update_layer_height_profile().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::ModelVolume::check(), Slic3r::check_model_ids_equal(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), anonymous_namespace{RaycastManager.cpp}::create_key(), priv::create_volume(), Slic3r::GUI::Emboss::create_volume_sources(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::Model::delete_object(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::ModelObjectStatusDB::get(), Slic3r::GUI::get_arrange_poly(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::inner_brim_area(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ObjectBase::load_and_construct(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::GLGizmoEmboss::process(), Slic3r::GUI::processed_objects_idxs(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::top_level_outer_brim_area(), Slic3r::GUI::update_object_cut_id(), and anonymous_namespace{EmbossJob.cpp}::update_volume_name().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
object_id_and_timestamp_match()
bool Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match (const ObjectWithTimestamp & rhs) const throw () inline inherited
{ return this->id() == rhs.id() && m_timestamp == rhs.m_timestamp; }
References Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), and Slic3r::ObjectWithTimestamp::m_timestamp.
operator=() [1/2]
LayerHeightProfile & Slic3r::LayerHeightProfile::operator= (const LayerHeightProfile & rhs) private default
operator=() [2/2]
LayerHeightProfile & Slic3r::LayerHeightProfile::operator= (LayerHeightProfile && rhs) private default
serialize()
template<class Archive > void Slic3r::LayerHeightProfile::serialize (Archive & ar) inline
    {
        ar(cereal::base_class<ObjectWithTimestamp>(this), m_data);
    }
References m_data.
set() [1/2]
void Slic3r::LayerHeightProfile::set (const std::vector< coordf_t > & data) inline
{ if (m_data != data) { m_data = data; this->touch(); } }
References m_data, and Slic3r::ObjectWithTimestamp::touch().
Referenced by Slic3r::_3MF_Importer::_load_model_from_file(), and Slic3r::AMFParserContext::endElement().
set() [2/2]
void Slic3r::LayerHeightProfile::set (std::vector< coordf_t > && data) inline
{ if (m_data != data) { m_data = std::move(data); this->touch(); } }
References m_data, and Slic3r::ObjectWithTimestamp::touch().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
timestamp()
Timestamp Slic3r::ObjectWithTimestamp::timestamp () const throw () inline override virtual inherited
Reimplemented from Slic3r::ObjectBase.
{ return m_timestamp; }
References Slic3r::ObjectWithTimestamp::m_timestamp.
timestamp_matches()
bool Slic3r::ObjectWithTimestamp::timestamp_matches (const ObjectWithTimestamp & rhs) const throw () inline inherited
{ return m_timestamp == rhs.m_timestamp; }
References Slic3r::ObjectWithTimestamp::m_timestamp.
Referenced by Slic3r::Print::apply(), Slic3r::FacetsAnnotation::assign(), assign(), Slic3r::FacetsAnnotation::assign(), assign(), Slic3r::model_custom_seam_data_changed(), Slic3r::model_custom_supports_data_changed(), and Slic3r::model_mmu_segmentation_data_changed().
touch()
void Slic3r::ObjectWithTimestamp::touch () inline inherited
{ m_timestamp = ++ s_last_timestamp; }
References Slic3r::ObjectWithTimestamp::m_timestamp, and Slic3r::ObjectWithTimestamp::s_last_timestamp.
Referenced by clear(), set(), and set().
Friends And Related Symbol Documentation
ModelObject
friend class ModelObject friend
Member Data Documentation
m_data
std::vector<coordf_t> Slic3r::LayerHeightProfile::m_data private
Referenced by assign(), assign(), clear(), empty(), get(), serialize(), set(), and set().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_timestamp
Timestamp Slic3r::ObjectWithTimestamp::m_timestamp { 1 } private inherited
Referenced by Slic3r::ObjectWithTimestamp::copy_timestamp(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::serialize(), Slic3r::ObjectWithTimestamp::timestamp(), Slic3r::ObjectWithTimestamp::timestamp_matches(), and Slic3r::ObjectWithTimestamp::touch().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
s_last_timestamp
ObjectWithTimestamp::Timestamp Slic3r::ObjectWithTimestamp::s_last_timestamp = 1 static private inherited
Referenced by Slic3r::ObjectWithTimestamp::touch().
The documentation for this class was generated from the following file:
src/libslic3r/Model.hpp