Prusa Slicer: Slic3r::GCode::ObjectLayerToPrint Struct Reference
Slic3r::GCode::ObjectLayerToPrint Struct Reference
#include <src/libslic3r/GCode.hpp>
Public Member Functions
ObjectLayerToPrint ()
const Layer * layer () const
const PrintObject * object () const
coordf_t print_z () const
Public Attributes
const Layer * object_layer
const SupportLayer * support_layer
Detailed Description
Constructor & Destructor Documentation
ObjectLayerToPrint()
Slic3r::GCode::ObjectLayerToPrint::ObjectLayerToPrint () inline
: object_layer(nullptr), support_layer(nullptr) {}
Member Function Documentation
layer()
const Layer * Slic3r::GCode::ObjectLayerToPrint::layer () const inline
{ return (object_layer != nullptr) ? object_layer : support_layer; }
References object_layer, and support_layer.
Referenced by Slic3r::GCode::collect_layers_to_print(), object(), print_z(), and Slic3r::GCode::process_layer_single_object().
object()
const PrintObject * Slic3r::GCode::ObjectLayerToPrint::object () const inline
{ return (this->layer() != nullptr) ? this->layer()->object() : nullptr; }
References layer(), and Slic3r::Layer::object().
print_z()
coordf_t Slic3r::GCode::ObjectLayerToPrint::print_z () const inline
{ return (object_layer != nullptr && support_layer != nullptr) ? 0.5 * (object_layer->print_z + support_layer->print_z) : this->layer()->print_z; }
References layer(), object_layer, Slic3r::Layer::print_z, and support_layer.
Referenced by Slic3r::GCode::collect_layers_to_print().
Member Data Documentation
object_layer
const Layer* Slic3r::GCode::ObjectLayerToPrint::object_layer
Referenced by Slic3r::GCode::collect_layers_to_print(), layer(), print_z(), and Slic3r::GCode::process_layer_single_object().
support_layer
const SupportLayer* Slic3r::GCode::ObjectLayerToPrint::support_layer
Referenced by Slic3r::GCode::collect_layers_to_print(), layer(), print_z(), and Slic3r::GCode::process_layer_single_object().
The documentation for this struct was generated from the following file:
src/libslic3r/GCode.hpp