Prusa Slicer: Slic3r::GUI::ObjectList::Clipboard Struct Reference
Slic3r::GUI::ObjectList::Clipboard Struct Reference
#include <src/slic3r/GUI/GUI_ObjectList.hpp>
Public Member Functions
void reset ()
bool empty () const
ItemType get_type () const
void set_type (ItemType type)
t_layer_config_ranges & get_ranges_cache ()
DynamicPrintConfig & get_config_cache ()
Private Attributes
ItemType m_type {itUndef}
t_layer_config_ranges m_layer_config_ranges_cache
DynamicPrintConfig m_config_cache
Detailed Description
Member Function Documentation
empty()
bool Slic3r::GUI::ObjectList::Clipboard::empty () const inline
{ return m_type == itUndef; }
References Slic3r::GUI::itUndef, and m_type.
Referenced by Slic3r::GUI::ObjectList::clipboard_is_empty().
get_config_cache()
DynamicPrintConfig & Slic3r::GUI::ObjectList::Clipboard::get_config_cache () inline
{ return m_config_cache; }
References m_config_cache.
Referenced by Slic3r::GUI::ObjectList::copy_settings_to_clipboard(), and Slic3r::GUI::ObjectList::paste_settings_into_list().
get_ranges_cache()
t_layer_config_ranges & Slic3r::GUI::ObjectList::Clipboard::get_ranges_cache () inline
{ return m_layer_config_ranges_cache; }
References m_layer_config_ranges_cache.
Referenced by Slic3r::GUI::ObjectList::copy_layers_to_clipboard(), and Slic3r::GUI::ObjectList::paste_layers_into_list().
get_type()
ItemType Slic3r::GUI::ObjectList::Clipboard::get_type () const inline
{ return m_type; }
References m_type.
Referenced by Slic3r::GUI::ObjectList::paste_from_clipboard().
reset()
void Slic3r::GUI::ObjectList::Clipboard::reset () inline
                     {
            m_type = itUndef;
            m_layer_config_ranges_cache .clear();
            m_config_cache.clear();
        }
References Slic3r::DynamicConfig::clear(), Slic3r::GUI::itUndef, m_config_cache, m_layer_config_ranges_cache, and m_type.
Referenced by Slic3r::GUI::ObjectList::copy_to_clipboard(), and Slic3r::GUI::ObjectList::paste_from_clipboard().
set_type()
void Slic3r::GUI::ObjectList::Clipboard::set_type (ItemType type) inline
{ m_type = type; }
References m_type.
Referenced by Slic3r::GUI::ObjectList::copy_to_clipboard().
Member Data Documentation
m_config_cache
DynamicPrintConfig Slic3r::GUI::ObjectList::Clipboard::m_config_cache private
Referenced by get_config_cache(), and reset().
m_layer_config_ranges_cache
t_layer_config_ranges Slic3r::GUI::ObjectList::Clipboard::m_layer_config_ranges_cache private
Referenced by get_ranges_cache(), and reset().
m_type
ItemType Slic3r::GUI::ObjectList::Clipboard::m_type {itUndef} private
Referenced by empty(), get_type(), reset(), and set_type().
The documentation for this struct was generated from the following file:
src/slic3r/GUI/GUI_ObjectList.hpp