Prusa Slicer: Slic3r::LinesBucket Class Reference
Slic3r::LinesBucket Class Reference
#include <src/libslic3r/GCode/ConflictChecker.hpp>
Public Member Functions
LinesBucket (std::vector< ExtrusionPaths > &&paths, int id, Points offsets)
LinesBucket (LinesBucket &&)=default
bool valid () const
void raise ()
double curHeight () const
LineWithIDs curLines () const
Private Attributes
double _curHeight = 0.0
unsigned _curPileIdx = 0
std::vector< ExtrusionPaths > _piles
int _id
Points _offsets
Friends
bool operator> (const LinesBucket &left, const LinesBucket &right)
bool operator< (const LinesBucket &left, const LinesBucket &right)
bool operator== (const LinesBucket &left, const LinesBucket &right)
Detailed Description
Constructor & Destructor Documentation
LinesBucket() [1/2]
Slic3r::LinesBucket::LinesBucket (std::vector< ExtrusionPaths > && paths, int id, Points offsets) inline
: _piles(paths), _id(id), _offsets(offsets) {}
LinesBucket() [2/2]
Slic3r::LinesBucket::LinesBucket (LinesBucket &&) default
Member Function Documentation
curHeight()
double Slic3r::LinesBucket::curHeight () const inline
{ return _curHeight; }
References _curHeight.
curLines()
LineWithIDs Slic3r::LinesBucket::curLines () const inline
    {
        LineWithIDs lines;
        for (const ExtrusionPath &path : _piles[_curPileIdx]) {
            Polyline check_polyline;
            for (int i = 0; i < (int)_offsets.size(); ++i) {
                check_polyline = path.polyline;
                check_polyline.translate(_offsets[i]);
                Lines tmpLines = check_polyline.lines();
                for (const Line& line : tmpLines) { lines.emplace_back(line, _id, i, path.role()); }
            }
        }
        return lines;
    }
References _curPileIdx, _id, _offsets, _piles, Slic3r::Polyline::lines(), and Slic3r::MultiPoint::translate().
raise()
void Slic3r::LinesBucket::raise () inline
    {
        if (valid()) {
            if (_piles[_curPileIdx].empty() == false) { _curHeight += _piles[_curPileIdx].front().height; }
            _curPileIdx++;
        }
    }
References _curHeight, _curPileIdx, _piles, Slic3r::empty(), and valid().
valid()
bool Slic3r::LinesBucket::valid () const inline
{ return _curPileIdx < _piles.size(); }
References _curPileIdx, and _piles.
Referenced by raise().
Friends And Related Symbol Documentation
operator<
bool operator< (const LinesBucket & left, const LinesBucket & right) friend
{ return left._curHeight < right._curHeight; }
operator==
bool operator== (const LinesBucket & left, const LinesBucket & right) friend
{ return left._curHeight == right._curHeight; }
operator>
bool operator> (const LinesBucket & left, const LinesBucket & right) friend
{ return left._curHeight > right._curHeight; }
Member Data Documentation
_curHeight
double Slic3r::LinesBucket::_curHeight = 0.0 private
Referenced by curHeight(), and raise().
_curPileIdx
unsigned Slic3r::LinesBucket::_curPileIdx = 0 private
Referenced by curLines(), raise(), and valid().
_id
int Slic3r::LinesBucket::_id private
Referenced by curLines().
_offsets
Points Slic3r::LinesBucket::_offsets private
Referenced by curLines().
_piles
std::vector<ExtrusionPaths> Slic3r::LinesBucket::_piles private
Referenced by curLines(), raise(), and valid().
The documentation for this class was generated from the following file:
src/libslic3r/GCode/ConflictChecker.hpp