Prusa Slicer: fast_float::binary_format< T > Struct Template Reference
fast_float::binary_format< T > Struct Template Reference
#include <src/fast_float/fast_float.h>
Public Member Functions
constexpr int mantissa_explicit_bits ()
constexpr int mantissa_explicit_bits ()
constexpr int max_exponent_round_to_even ()
constexpr int max_exponent_round_to_even ()
constexpr int min_exponent_round_to_even ()
constexpr int min_exponent_round_to_even ()
constexpr int minimum_exponent ()
constexpr int minimum_exponent ()
constexpr int infinite_power ()
constexpr int infinite_power ()
constexpr int sign_index ()
constexpr int sign_index ()
constexpr int min_exponent_fast_path ()
constexpr int min_exponent_fast_path ()
constexpr int max_exponent_fast_path ()
constexpr int max_exponent_fast_path ()
constexpr uint64_t max_mantissa_fast_path ()
constexpr uint64_t max_mantissa_fast_path ()
constexpr double exact_power_of_ten (int64_t power)
constexpr float exact_power_of_ten (int64_t power)
constexpr int largest_power_of_ten ()
constexpr int largest_power_of_ten ()
constexpr int smallest_power_of_ten ()
constexpr int smallest_power_of_ten ()
Static Public Member Functions
static constexpr int mantissa_explicit_bits ()
static constexpr int minimum_exponent ()
static constexpr int infinite_power ()
static constexpr int sign_index ()
static constexpr int min_exponent_fast_path ()
static constexpr int max_exponent_fast_path ()
static constexpr int max_exponent_round_to_even ()
static constexpr int min_exponent_round_to_even ()
static constexpr uint64_t max_mantissa_fast_path ()
static constexpr int largest_power_of_ten ()
static constexpr int smallest_power_of_ten ()
static constexpr T exact_power_of_ten (int64_t power)
Detailed Description
template<typename T>
struct fast_float::binary_format< T >
Member Function Documentation
exact_power_of_ten() [1/3]
template<typename T > static constexpr T fast_float::binary_format< T >::exact_power_of_ten (int64_t power) inline static constexpr
Referenced by fast_float::from_chars_advanced().
exact_power_of_ten() [2/3]
constexpr double fast_float::binary_format< double >::exact_power_of_ten (int64_t power) inline constexpr
{
  return powers_of_ten_double[power];
}
References fast_float::powers_of_ten_double.
exact_power_of_ten() [3/3]
constexpr float fast_float::binary_format< float >::exact_power_of_ten (int64_t power) inline constexpr
{
  return powers_of_ten_float[power];
}
References fast_float::powers_of_ten_float.
infinite_power() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::infinite_power () inline static constexpr
infinite_power() [2/3]
constexpr int fast_float::binary_format< double >::infinite_power () inline constexpr
{
  return 0x7FF;
}
infinite_power() [3/3]
constexpr int fast_float::binary_format< float >::infinite_power () inline constexpr
{
  return 0xFF;
}
largest_power_of_ten() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::largest_power_of_ten () inline static constexpr
largest_power_of_ten() [2/3]
constexpr int fast_float::binary_format< double >::largest_power_of_ten () inline constexpr
{
  return 308;
}
largest_power_of_ten() [3/3]
constexpr int fast_float::binary_format< float >::largest_power_of_ten () inline constexpr
{
  return 38;
}
mantissa_explicit_bits() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::mantissa_explicit_bits () inline static constexpr
Referenced by fast_float::detail::to_float().
mantissa_explicit_bits() [2/3]
constexpr int fast_float::binary_format< double >::mantissa_explicit_bits () inline constexpr
{
  return 52;
}
mantissa_explicit_bits() [3/3]
constexpr int fast_float::binary_format< float >::mantissa_explicit_bits () inline constexpr
{
  return 23;
}
max_exponent_fast_path() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::max_exponent_fast_path () inline static constexpr
max_exponent_fast_path() [2/3]
constexpr int fast_float::binary_format< double >::max_exponent_fast_path () inline constexpr
{
  return 22;
}
max_exponent_fast_path() [3/3]
constexpr int fast_float::binary_format< float >::max_exponent_fast_path () inline constexpr
{
  return 10;
}
max_exponent_round_to_even() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::max_exponent_round_to_even () inline static constexpr
max_exponent_round_to_even() [2/3]
constexpr int fast_float::binary_format< double >::max_exponent_round_to_even () inline constexpr
{
  return 23;
}
max_exponent_round_to_even() [3/3]
constexpr int fast_float::binary_format< float >::max_exponent_round_to_even () inline constexpr
{
  return 10;
}
max_mantissa_fast_path() [1/3]
template<typename T > static constexpr uint64_t fast_float::binary_format< T >::max_mantissa_fast_path () inline static constexpr
max_mantissa_fast_path() [2/3]
constexpr uint64_t fast_float::binary_format< double >::max_mantissa_fast_path () inline constexpr
{
  return uint64_t(2) << mantissa_explicit_bits();
}
max_mantissa_fast_path() [3/3]
constexpr uint64_t fast_float::binary_format< float >::max_mantissa_fast_path () inline constexpr
{
  return uint64_t(2) << mantissa_explicit_bits();
}
min_exponent_fast_path() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::min_exponent_fast_path () inline static constexpr
min_exponent_fast_path() [2/3]
constexpr int fast_float::binary_format< double >::min_exponent_fast_path () inline constexpr
{
#if (FLT_EVAL_METHOD != 1) && (FLT_EVAL_METHOD != 0)
  return 0;
#else
  return -22;
#endif
}
min_exponent_fast_path() [3/3]
constexpr int fast_float::binary_format< float >::min_exponent_fast_path () inline constexpr
{
#if (FLT_EVAL_METHOD != 1) && (FLT_EVAL_METHOD != 0)
  return 0;
#else
  return -10;
#endif
}
min_exponent_round_to_even() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::min_exponent_round_to_even () inline static constexpr
min_exponent_round_to_even() [2/3]
constexpr int fast_float::binary_format< double >::min_exponent_round_to_even () inline constexpr
{
  return -4;
}
min_exponent_round_to_even() [3/3]
constexpr int fast_float::binary_format< float >::min_exponent_round_to_even () inline constexpr
{
  return -17;
}
minimum_exponent() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::minimum_exponent () inline static constexpr
minimum_exponent() [2/3]
constexpr int fast_float::binary_format< double >::minimum_exponent () inline constexpr
{
  return -1023;
}
minimum_exponent() [3/3]
constexpr int fast_float::binary_format< float >::minimum_exponent () inline constexpr
{
  return -127;
}
sign_index() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::sign_index () inline static constexpr
Referenced by fast_float::detail::to_float().
sign_index() [2/3]
constexpr int fast_float::binary_format< double >::sign_index () inline constexpr
{ return 63; }
sign_index() [3/3]
constexpr int fast_float::binary_format< float >::sign_index () inline constexpr
{ return 31; }
smallest_power_of_ten() [1/3]
template<typename T > static constexpr int fast_float::binary_format< T >::smallest_power_of_ten () inline static constexpr
smallest_power_of_ten() [2/3]
constexpr int fast_float::binary_format< double >::smallest_power_of_ten () inline constexpr
{
  return -342;
}
smallest_power_of_ten() [3/3]
constexpr int fast_float::binary_format< float >::smallest_power_of_ten () inline constexpr
{
  return -65;
}
The documentation for this struct was generated from the following file:
src/fast_float/fast_float.h