Prusa Slicer: CurvatureCalculator::Quadric Class Reference
CurvatureCalculator::Quadric Class Reference
Public Member Functions
IGL_INLINE Quadric ()
IGL_INLINE Quadric (double av, double bv, double cv, double dv, double ev)
IGL_INLINE double & a ()
IGL_INLINE double & b ()
IGL_INLINE double & c ()
IGL_INLINE double & d ()
IGL_INLINE double & e ()
IGL_INLINE double evaluate (double u, double v)
IGL_INLINE double du (double u, double v)
IGL_INLINE double dv (double u, double v)
IGL_INLINE double duv (double u, double v)
IGL_INLINE double duu (double u, double v)
IGL_INLINE double dvv (double u, double v)
Static Public Member Functions
static IGL_INLINE Quadric fit (const std::vector< Eigen::Vector3d > &VV)
Public Attributes
double data [5]
Detailed Description
Constructor & Destructor Documentation
Quadric() [1/2]
IGL_INLINE CurvatureCalculator::Quadric::Quadric () inline
    {
      a() = b() = c() = d() = e() = 1.0;
    }
References a(), b(), c(), d(), and e().
Referenced by fit().
Quadric() [2/2]
IGL_INLINE CurvatureCalculator::Quadric::Quadric (double av, double bv, double cv, double dv, double ev) inline
    {
      a() = av;
      b() = bv;
      c() = cv;
      d() = dv;
      e() = ev;
    }
References a(), b(), c(), d(), dv(), and e().
Member Function Documentation
a()
IGL_INLINE double & CurvatureCalculator::Quadric::a () inline
{ return data[0];}
References data.
Referenced by Quadric(), Quadric(), du(), duu(), evaluate(), and CurvatureCalculator::finalEigenStuff().
b()
IGL_INLINE double & CurvatureCalculator::Quadric::b () inline
{ return data[1];}
References data.
Referenced by Quadric(), Quadric(), du(), duv(), dv(), evaluate(), CurvatureCalculator::finalEigenStuff(), and fit().
c()
IGL_INLINE double & CurvatureCalculator::Quadric::c () inline
{ return data[2];}
References data.
Referenced by Quadric(), Quadric(), dv(), dvv(), evaluate(), CurvatureCalculator::finalEigenStuff(), and fit().
d()
IGL_INLINE double & CurvatureCalculator::Quadric::d () inline
{ return data[3];}
References data.
Referenced by Quadric(), Quadric(), du(), evaluate(), and CurvatureCalculator::finalEigenStuff().
du()
IGL_INLINE double CurvatureCalculator::Quadric::du (double u, double v) inline
    {
      return 2.0*a()*u + b()*v + d();
    }
References a(), b(), and d().
duu()
IGL_INLINE double CurvatureCalculator::Quadric::duu (double u, double v) inline
    {
      return 2.0*a();
    }
References a().
duv()
IGL_INLINE double CurvatureCalculator::Quadric::duv (double u, double v) inline
    {
      return b();
    }
References b().
dv()
IGL_INLINE double CurvatureCalculator::Quadric::dv (double u, double v) inline
    {
      return 2.0*c()*v + b()*u + e();
    }
References b(), c(), and e().
Referenced by Quadric().
dvv()
IGL_INLINE double CurvatureCalculator::Quadric::dvv (double u, double v) inline
    {
      return 2.0*c();
    }
References c().
e()
IGL_INLINE double & CurvatureCalculator::Quadric::e () inline
{ return data[4];}
References data.
Referenced by Quadric(), Quadric(), dv(), evaluate(), and CurvatureCalculator::finalEigenStuff().
evaluate()
IGL_INLINE double CurvatureCalculator::Quadric::evaluate (double u, double v) inline
    {
      return a()*u*u + b()*u*v + c()*v*v + d()*u + e()*v;
    }
References a(), b(), c(), d(), and e().
fit()
static IGL_INLINE Quadric CurvatureCalculator::Quadric::fit (const std::vector< Eigen::Vector3d > & VV) inline static
    {
      assert(VV.size() >= 5);
      if (VV.size() < 5)
      {
        std::cerr << "ASSERT FAILED! fit function requires at least 5 points: Only " << VV.size() << " were given." << std::endl;
        exit(0);
      }
      Eigen::MatrixXd A(VV.size(),5);
      Eigen::MatrixXd b(VV.size(),1);
      Eigen::MatrixXd sol(5,1);
      for(unsigned int c=0; c < VV.size(); ++c)
      {
        double u = VV[c][0];
        double v = VV[c][1];
        double n = VV[c][2];
        A(c,0) = u*u;
        A(c,1) = u*v;
        A(c,2) = v*v;
        A(c,3) = u;
        A(c,4) = v;
        b(c) = n;
      }
      sol=A.jacobiSvd(Eigen::ComputeThinU | Eigen::ComputeThinV).solve(b);
      return Quadric(sol(0),sol(1),sol(2),sol(3),sol(4));
    }
References Quadric(), b(), c(), Eigen::ComputeThinU, and Eigen::ComputeThinV.
Referenced by CurvatureCalculator::fitQuadric().
Member Data Documentation
data
double CurvatureCalculator::Quadric::data[5]
Referenced by a(), b(), c(), d(), and e().
The documentation for this class was generated from the following file:
src/libigl/igl/principal_curvature.cpp