Prusa Slicer: Slic3r::DoubleSlider::Control Class Reference
Slic3r::DoubleSlider::Control Class Reference
#include <src/slic3r/GUI/DoubleSlider.hpp>
Classes
class Ruler
Public Member Functions
Control (wxWindow *parent, wxWindowID id, int lowerValue, int higherValue, int minValue, int maxValue, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxSL_VERTICAL, const wxValidator &val=wxDefaultValidator, const wxString &name=wxEmptyString)
~Control ()
void msw_rescale ()
void sys_color_changed ()
int GetMinValue () const
int GetMaxValue () const
double GetMinValueD ()
double GetMaxValueD ()
int GetLowerValue () const
int GetHigherValue () const
int GetActiveValue () const
double GetLowerValueD ()
double GetHigherValueD ()
wxSize DoGetBestSize () const override
wxSize get_min_size () const
void SetLowerValue (const int lower_val)
void SetHigherValue (const int higher_val)
void SetSelectionSpan (const int lower_val, const int higher_val)
void SetMaxValue (const int max_value)
void SetKoefForLabels (const double koef)
void SetSliderValues (const std::vector< double > &values)
void ChangeOneLayerLock ()
void SetSliderAlternateValues (const std::vector< double > &values)
Info GetTicksValues () const
void SetTicksValues (const Info &custom_gcode_per_print_z)
void SetLayersTimes (const std::vector< float > &layers_times, float total_time)
void SetLayersTimes (const std::vector< double > &layers_times)
void SetDrawMode (bool is_sla_print, bool is_sequential_print)
void SetDrawMode (DrawMode mode)
void SetManipulationMode (Mode mode)
Mode GetManipulationMode () const
void SetModeAndOnlyExtruder (const bool is_one_extruder_printed_model, const int only_extruder)
void SetExtruderColors (const std::vector< std::string > &extruder_colors)
bool IsNewPrint ()
void set_render_as_disabled (bool value)
bool is_rendering_as_disabled () const
bool is_horizontal () const
bool is_one_layer () const
bool is_lower_at_min () const
bool is_higher_at_max () const
bool is_full_span () const
void OnPaint (wxPaintEvent &)
void OnLeftDown (wxMouseEvent &event)
void OnMotion (wxMouseEvent &event)
void OnLeftUp (wxMouseEvent &event)
void OnEnterWin (wxMouseEvent &event)
void OnLeaveWin (wxMouseEvent &event)
void UseDefaultColors (bool def_colors_on)
void OnWheel (wxMouseEvent &event)
void OnKeyDown (wxKeyEvent &event)
void OnKeyUp (wxKeyEvent &event)
void OnChar (wxKeyEvent &event)
void OnRightDown (wxMouseEvent &event)
void OnRightUp (wxMouseEvent &event)
void add_code_as_tick (Type type, int selected_extruder=-1)
void add_current_tick (bool call_from_keyboard=false)
void delete_current_tick ()
void edit_tick (int tick=-1)
void switch_one_layer_mode ()
void discard_all_thicks ()
void move_current_thumb_to_pos (wxPoint pos)
void edit_extruder_sequence ()
void jump_to_value ()
void enable_action_icon (bool enable)
void show_add_context_menu ()
void show_edit_context_menu ()
void show_cog_icon_context_menu ()
void auto_color_change ()
Public Attributes
ExtrudersSequence m_extruders_sequence
Protected Member Functions
void render ()
void draw_focus_rect (wxDC &dc)
void draw_action_icon (wxDC &dc, const wxPoint pt_beg, const wxPoint pt_end)
void draw_scroll_line (wxDC &dc, const int lower_pos, const int higher_pos)
void draw_thumb (wxDC &dc, const wxCoord &pos_coord, const SelectedSlider &selection)
void draw_thumbs (wxDC &dc, const wxCoord &lower_pos, const wxCoord &higher_pos)
void draw_ticks_pair (wxDC &dc, wxCoord pos, wxCoord mid, int tick_len)
void draw_ticks (wxDC &dc)
void draw_colored_band (wxDC &dc)
void draw_ruler (wxDC &dc)
void draw_one_layer_icon (wxDC &dc)
void draw_revert_icon (wxDC &dc)
void draw_cog_icon (wxDC &dc)
void draw_thumb_item (wxDC &dc, const wxPoint &pos, const SelectedSlider &selection)
void draw_info_line_with_icon (wxDC &dc, const wxPoint &pos, SelectedSlider selection)
void draw_tick_on_mouse_position (wxDC &dc)
void draw_tick_text (wxDC &dc, const wxPoint &pos, int tick, LabelType label_type=ltHeight, bool right_side=true) const
void draw_thumb_text (wxDC &dc, const wxPoint &pos, const SelectedSlider &selection) const
void update_thumb_rect (const wxCoord begin_x, const wxCoord begin_y, const SelectedSlider &selection)
bool is_lower_thumb_editable ()
bool detect_selected_slider (const wxPoint &pt)
void correct_lower_value ()
void correct_higher_value ()
void move_current_thumb (const bool condition)
void enter_window (wxMouseEvent &event, const bool enter)
bool is_wipe_tower_layer (int tick) const
Private Member Functions
bool is_point_in_rect (const wxPoint &pt, const wxRect &rect)
int get_tick_near_point (const wxPoint &pt)
double get_scroll_step ()
wxString get_label (int tick, LabelType label_type=ltHeightWithLayer) const
void get_lower_and_higher_position (int &lower_pos, int &higher_pos)
int get_value_from_position (const wxCoord x, const wxCoord y)
int get_value_from_position (const wxPoint pos)
wxCoord get_position_from_value (const int value)
wxSize get_size () const
void get_size (int *w, int *h) const
double get_double_value (const SelectedSlider &selection)
int get_tick_from_value (double value, bool force_lower_bound=false)
wxString get_tooltip (int tick=-1)
int get_edited_tick_for_position (wxPoint pos, Type type=ColorChange)
std::string get_color_for_tool_change_tick (std::set< TickCode >::const_iterator it) const
std::string get_color_for_color_change_tick (std::set< TickCode >::const_iterator it) const
wxRect get_colored_band_rect ()
std::array< int, 2 > get_active_extruders_for_tick (int tick) const
void post_ticks_changed_event (Type type=Custom)
bool check_ticks_changed_event (Type type)
void append_change_extruder_menu_item (wxMenu *, bool switch_current_code=false)
void append_add_color_change_menu_item (wxMenu *, bool switch_current_code=false)
Private Attributes
bool is_osx { false }
wxFont m_font
int m_min_value
int m_max_value
int m_lower_value
int m_higher_value
bool m_render_as_disabled { false }
ScalableBitmap m_bmp_thumb_higher
ScalableBitmap m_bmp_thumb_lower
ScalableBitmap m_bmp_add_tick_on
ScalableBitmap m_bmp_add_tick_off
ScalableBitmap m_bmp_del_tick_on
ScalableBitmap m_bmp_del_tick_off
ScalableBitmap m_bmp_one_layer_lock_on
ScalableBitmap m_bmp_one_layer_lock_off
ScalableBitmap m_bmp_one_layer_unlock_on
ScalableBitmap m_bmp_one_layer_unlock_off
ScalableBitmap m_bmp_revert
ScalableBitmap m_bmp_cog
SelectedSlider m_selection
bool m_is_left_down = false
bool m_is_right_down = false
bool m_is_one_layer = false
bool m_is_focused = false
bool m_force_mode_apply = true
bool m_enable_action_icon = true
bool m_is_wipe_tower = false
DrawMode m_draw_mode = dmRegular
Mode m_mode = SingleExtruder
int m_only_extruder = -1
MouseAction m_mouse = maNone
FocusedItem m_focus = fiNone
wxPoint m_moving_pos = wxDefaultPosition
wxRect m_rect_lower_thumb
wxRect m_rect_higher_thumb
wxRect m_rect_tick_action
wxRect m_rect_one_layer_icon
wxRect m_rect_revert_icon
wxRect m_rect_cog_icon
wxSize m_thumb_size
int m_tick_icon_dim
int m_lock_icon_dim
int m_revert_icon_dim
int m_cog_icon_dim
long m_style
long m_extra_style
float m_label_koef { 1.0 }
std::vector< double > m_values
TickCodeInfo m_ticks
std::vector< double > m_layers_times
std::vector< double > m_layers_values
std::vector< std::string > m_extruder_colors
std::string m_print_obj_idxs
std::vector< double > m_alternate_values
wxCoord SLIDER_MARGIN
wxPen DARK_ORANGE_PEN
wxPen ORANGE_PEN
wxPen LIGHT_ORANGE_PEN
wxPen DARK_GREY_PEN
wxPen GREY_PEN
wxPen LIGHT_GREY_PEN
wxPen FOCUS_RECT_PEN
wxBrush FOCUS_RECT_BRUSH
std::vector< wxPen * > m_line_pens
std::vector< wxPen * > m_segm_pens
class Slic3r::DoubleSlider::Control::Ruler m_ruler
Detailed Description
Constructor & Destructor Documentation
Control()
Slic3r::DoubleSlider::Control::Control (wxWindow * parent, wxWindowID id, int lowerValue, int higherValue, int minValue, int maxValue, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxSL_VERTICAL, const wxValidator & val = wxDefaultValidator, const wxString & name = wxEmptyString)
                                        :
    wxControl(parent, id, pos, size, wxWANTS_CHARS | wxBORDER_NONE),
    m_lower_value(lowerValue),
    m_higher_value (higherValue),
    m_min_value(minValue),
    m_max_value(maxValue),
    m_style(style == wxSL_HORIZONTAL || style == wxSL_VERTICAL ? style: wxSL_HORIZONTAL),
    m_extra_style(style == wxSL_VERTICAL ? wxSL_AUTOTICKS | wxSL_VALUE_LABEL : 0)
{
#ifdef __WXOSX__
    is_osx = true;
#endif //__WXOSX__
    if (!is_osx)
        SetDoubleBuffered(true);// SetDoubleBuffered exists on Win and Linux/GTK, but is missing on OSX
    m_bmp_thumb_higher = (style == wxSL_HORIZONTAL ? ScalableBitmap(this, "thumb_right") : ScalableBitmap(this, "thumb_up"));
    m_bmp_thumb_lower  = (style == wxSL_HORIZONTAL ? ScalableBitmap(this, "thumb_left")  : ScalableBitmap(this, "thumb_down"));
    m_thumb_size = m_bmp_thumb_lower.GetSize();
    m_bmp_add_tick_on  = ScalableBitmap(this, "colorchange_add");
    m_bmp_add_tick_off = ScalableBitmap(this, "colorchange_add_f");
    m_bmp_del_tick_on  = ScalableBitmap(this, "colorchange_del");
    m_bmp_del_tick_off = ScalableBitmap(this, "colorchange_del_f");
    m_tick_icon_dim = m_bmp_add_tick_on.GetWidth();
    m_bmp_one_layer_lock_on    = ScalableBitmap(this, "lock_closed");
    m_bmp_one_layer_lock_off   = ScalableBitmap(this, "lock_closed_f");
    m_bmp_one_layer_unlock_on  = ScalableBitmap(this, "lock_open");
    m_bmp_one_layer_unlock_off = ScalableBitmap(this, "lock_open_f");
    m_lock_icon_dim   = m_bmp_one_layer_lock_on.GetWidth();
    m_bmp_revert               = ScalableBitmap(this, "undo");
    m_revert_icon_dim = m_bmp_revert.GetWidth();
    m_bmp_cog                  = ScalableBitmap(this, "cog");
    m_cog_icon_dim    = m_bmp_cog.GetWidth();
    m_selection = ssUndef;
    m_ticks.set_pause_print_msg(_u8L("Place bearings in slots and resume printing"));
    m_ticks.set_extruder_colors(&m_extruder_colors);
    // slider events
    this->Bind(wxEVT_PAINT,       &Control::OnPaint,    this);
    this->Bind(wxEVT_CHAR,        &Control::OnChar,     this);
    this->Bind(wxEVT_LEFT_DOWN,   &Control::OnLeftDown, this);
    this->Bind(wxEVT_MOTION,      &Control::OnMotion,   this);
    this->Bind(wxEVT_LEFT_UP,     &Control::OnLeftUp,   this);
    this->Bind(wxEVT_MOUSEWHEEL,  &Control::OnWheel,    this);
    this->Bind(wxEVT_ENTER_WINDOW,&Control::OnEnterWin, this);
    this->Bind(wxEVT_LEAVE_WINDOW,&Control::OnLeaveWin, this);
    this->Bind(wxEVT_KEY_DOWN,    &Control::OnKeyDown,  this);
    this->Bind(wxEVT_KEY_UP,      &Control::OnKeyUp,    this);
    this->Bind(wxEVT_RIGHT_DOWN,  &Control::OnRightDown,this);
    this->Bind(wxEVT_RIGHT_UP,    &Control::OnRightUp,  this);
    this->Bind(wxEVT_SIZE, [this](wxSizeEvent& event) {
        m_ruler.update(m_layers_values.empty() ? m_values : m_layers_values, get_scroll_step());
        event.Skip();
    });
    // control's view variables
    SLIDER_MARGIN     = 4 + GUI::wxGetApp().em_unit();
    DARK_ORANGE_PEN   = wxPen(wxColour(237, 107, 33));
    ORANGE_PEN        = wxPen(wxColour(253, 126, 66));
    LIGHT_ORANGE_PEN  = wxPen(wxColour(254, 177, 139));
    DARK_GREY_PEN     = wxPen(wxColour(128, 128, 128));
    GREY_PEN          = wxPen(wxColour(164, 164, 164));
    LIGHT_GREY_PEN    = wxPen(wxColour(204, 204, 204));
    m_line_pens = { &DARK_GREY_PEN, &GREY_PEN, &LIGHT_GREY_PEN };
    m_segm_pens = { &DARK_ORANGE_PEN, &ORANGE_PEN, &LIGHT_ORANGE_PEN };
    FOCUS_RECT_PEN   = wxPen(wxColour(128, 128, 10), 1, wxPENSTYLE_DOT);
    FOCUS_RECT_BRUSH = wxBrush(wxColour(0, 0, 0), wxBRUSHSTYLE_TRANSPARENT);
    m_font = GetFont();
    this->SetMinSize(get_min_size());
    if (style == wxSL_VERTICAL)
        m_ruler.set_parent(this->GetParent());
}
References _u8L, DARK_GREY_PEN, DARK_ORANGE_PEN, FOCUS_RECT_BRUSH, FOCUS_RECT_PEN, get_min_size(), get_scroll_step(), ScalableBitmap::GetSize(), ScalableBitmap::GetWidth(), GREY_PEN, is_osx, LIGHT_GREY_PEN, LIGHT_ORANGE_PEN, m_bmp_add_tick_off, m_bmp_add_tick_on, m_bmp_cog, m_bmp_del_tick_off, m_bmp_del_tick_on, m_bmp_one_layer_lock_off, m_bmp_one_layer_lock_on, m_bmp_one_layer_unlock_off, m_bmp_one_layer_unlock_on, m_bmp_revert, m_bmp_thumb_higher, m_bmp_thumb_lower, m_cog_icon_dim, m_extruder_colors, m_font, m_layers_values, m_line_pens, m_lock_icon_dim, m_revert_icon_dim, m_ruler, m_segm_pens, m_selection, m_thumb_size, m_tick_icon_dim, m_ticks, m_values, OnChar(), OnEnterWin(), OnKeyDown(), OnKeyUp(), OnLeaveWin(), OnLeftDown(), OnLeftUp(), OnMotion(), OnPaint(), OnRightDown(), OnRightUp(), OnWheel(), ORANGE_PEN, Slic3r::DoubleSlider::TickCodeInfo::set_extruder_colors(), Slic3r::DoubleSlider::Control::Ruler::set_parent(), Slic3r::DoubleSlider::TickCodeInfo::set_pause_print_msg(), SLIDER_MARGIN, Slic3r::DoubleSlider::ssUndef, style, and Slic3r::DoubleSlider::Control::Ruler::update().
~Control()
Slic3r::DoubleSlider::Control::~Control () inline
{}
Member Function Documentation
add_code_as_tick()
void Slic3r::DoubleSlider::Control::add_code_as_tick (Type type, int selected_extruder = -1)
{
    if (m_selection == ssUndef)
        return;
    const int tick = m_selection == ssLower ? m_lower_value : m_higher_value;
    if ( !check_ticks_changed_event(type) )
        return;
    if (type == ColorChange && gcode(ColorChange).empty())
        GUI::wxGetApp().plater()->get_notification_manager()->push_notification(GUI::NotificationType::EmptyColorChangeCode);
    const int extruder = selected_extruder > 0 ? selected_extruder : std::max<int>(1, m_only_extruder);
    const auto it = m_ticks.ticks.find(TickCode{ tick });
    if ( it == m_ticks.ticks.end() ) {
        // try to add tick
        if (!m_ticks.add_tick(tick, type, extruder, m_values[tick]))
            return;
    }
    else if (type == ToolChange || type == ColorChange) {
        // try to switch tick code to ToolChange or ColorChange accordingly
        if (!m_ticks.switch_code_for_tick(it, type, extruder))
            return;
    }
    else
        return;
    post_ticks_changed_event(type);
}
References Slic3r::DoubleSlider::TickCodeInfo::add_tick(), check_ticks_changed_event(), Slic3r::CustomGCode::ColorChange, Slic3r::empty(), Slic3r::GUI::EmptyColorChangeCode, Slic3r::DoubleSlider::gcode(), m_higher_value, m_lower_value, m_only_extruder, m_selection, m_ticks, m_values, post_ticks_changed_event(), Slic3r::DoubleSlider::ssLower, Slic3r::DoubleSlider::ssUndef, Slic3r::DoubleSlider::TickCodeInfo::switch_code_for_tick(), Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
Referenced by add_current_tick(), append_add_color_change_menu_item(), append_change_extruder_menu_item(), and show_add_context_menu().
add_current_tick()
void Slic3r::DoubleSlider::Control::add_current_tick (bool call_from_keyboard = false)
{
    if (m_selection == ssUndef)
        return;
    const int tick = m_selection == ssLower ? m_lower_value : m_higher_value;
    auto it = m_ticks.ticks.find(TickCode{ tick });
    if (it != m_ticks.ticks.end() ||    // this tick is already exist
        !check_ticks_changed_event(m_mode == MultiAsSingle ? ToolChange : ColorChange))
        return;
    if (m_mode == SingleExtruder)
        add_code_as_tick(ColorChange);
    else
    {
        wxMenu menu;
        if (m_mode == MultiAsSingle)
            append_change_extruder_menu_item(&menu);
        else
            append_add_color_change_menu_item(&menu);
        wxPoint pos = wxDefaultPosition;
        /* Menu position will be calculated from mouse click position, but...
         * if function is called from keyboard (pressing "+"), we should to calculate it
         * */
        if (call_from_keyboard) {
            int width, height;
            get_size(&width, &height);
            const wxCoord coord = 0.75 * (is_horizontal() ? height : width);
            this->GetPosition(&width, &height);
            pos = is_horizontal() ?
                  wxPoint(get_position_from_value(tick), height + coord) :
                  wxPoint(width + coord, get_position_from_value(tick));
        }
        GUI::wxGetApp().plater()->PopupMenu(&menu, pos);
    }
}
References add_code_as_tick(), append_add_color_change_menu_item(), append_change_extruder_menu_item(), check_ticks_changed_event(), Slic3r::CustomGCode::ColorChange, get_position_from_value(), get_size(), is_horizontal(), m_higher_value, m_lower_value, m_mode, m_selection, m_ticks, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::SingleExtruder, Slic3r::DoubleSlider::ssLower, Slic3r::DoubleSlider::ssUndef, Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
Referenced by OnChar(), OnKeyDown(), and OnLeftUp().
append_add_color_change_menu_item()
void Slic3r::DoubleSlider::Control::append_add_color_change_menu_item (wxMenu * menu, bool switch_current_code = false) private
{
    const int extruders_cnt = GUI::wxGetApp().extruders_edited_cnt();
    if (extruders_cnt > 1) {
        int tick = m_selection == ssLower ? m_lower_value : m_higher_value;
        std::set<int> used_extruders_for_tick = m_ticks.get_used_extruders_for_tick(tick, m_only_extruder, m_values[tick]);
        wxMenu* add_color_change_menu = new wxMenu();
        for (int i = 1; i <= extruders_cnt; i++) {
            const bool is_used_extruder = used_extruders_for_tick.empty() ? true : // #ys_FIXME till used_extruders_for_tick doesn't filled correct for mmMultiExtruder
                                          used_extruders_for_tick.find(i) != used_extruders_for_tick.end();
            const wxString item_name = wxString::Format(_L("Extruder %d"), i) +
                                       (is_used_extruder ? " (" + _L("used") + ")" : "");
            append_menu_item(add_color_change_menu, wxID_ANY, item_name, "",
                [this, i](wxCommandEvent&) { add_code_as_tick(ColorChange, i); }, "", menu,
                []() { return true; }, GUI::wxGetApp().plater());
        }
        const wxString menu_name = switch_current_code ?
                                   format_wxstr(_L("Switch code to Color change (%1%) for:"), gcode(ColorChange)) :
                                   format_wxstr(_L("Add color change (%1%) for:"), gcode(ColorChange));
        wxMenuItem* add_color_change_menu_item = menu->AppendSubMenu(add_color_change_menu, menu_name, "");
        add_color_change_menu_item->SetBitmap(*get_bmp_bundle("colorchange_add_m"));
    }
}
References _L, add_code_as_tick(), append_menu_item(), Slic3r::CustomGCode::ColorChange, Slic3r::DoubleSlider::gcode(), get_bmp_bundle(), Slic3r::DoubleSlider::TickCodeInfo::get_used_extruders_for_tick(), m_higher_value, m_lower_value, m_only_extruder, m_selection, m_ticks, m_values, and Slic3r::DoubleSlider::ssLower.
Referenced by add_current_tick(), show_add_context_menu(), and show_edit_context_menu().
append_change_extruder_menu_item()
void Slic3r::DoubleSlider::Control::append_change_extruder_menu_item (wxMenu * menu, bool switch_current_code = false) private
{
    const int extruders_cnt = GUI::wxGetApp().extruders_edited_cnt();
    if (extruders_cnt > 1) {
        std::array<int, 2> active_extruders = get_active_extruders_for_tick(m_selection == ssLower ? m_lower_value : m_higher_value);
        std::vector<wxBitmapBundle*> icons = get_extruder_color_icons(true);
        wxMenu* change_extruder_menu = new wxMenu();
        for (int i = 1; i <= extruders_cnt; i++) {
            const bool is_active_extruder = i == active_extruders[0] || i == active_extruders[1];
            const wxString item_name = wxString::Format(_L("Extruder %d"), i) +
                                       (is_active_extruder ? " (" + _L("active") + ")" : "");
            if (m_mode == MultiAsSingle)
                append_menu_item(change_extruder_menu, wxID_ANY, item_name, "",
                    [this, i](wxCommandEvent&) { add_code_as_tick(ToolChange, i); }, icons[i-1], menu,
                    [is_active_extruder]() { return !is_active_extruder; }, GUI::wxGetApp().plater());
        }
        const wxString change_extruder_menu_name = m_mode == MultiAsSingle ?
                                                   (switch_current_code ? _L("Switch code to Change extruder") : _L("Change extruder") ) :
                                                   _L("Change extruder (N/A)");
        append_submenu(menu, change_extruder_menu, wxID_ANY, change_extruder_menu_name, _L("Use another extruder"),
            active_extruders[1] > 0 ? "edit_uni" : "change_extruder",
            [this]() {return m_mode == MultiAsSingle && !GUI::wxGetApp().obj_list()->has_paint_on_segmentation(); }, GUI::wxGetApp().plater());
    }
}
References _L, add_code_as_tick(), append_menu_item(), append_submenu(), get_active_extruders_for_tick(), get_extruder_color_icons(), m_higher_value, m_lower_value, m_mode, m_selection, Slic3r::CustomGCode::MultiAsSingle, Slic3r::DoubleSlider::ssLower, and Slic3r::CustomGCode::ToolChange.
Referenced by add_current_tick(), show_add_context_menu(), and show_edit_context_menu().
auto_color_change()
void Slic3r::DoubleSlider::Control::auto_color_change ()
{
    if (!m_ticks.empty()) {
        wxString msg_text = _L("This action will cause deletion of all ticks on vertical slider.") + "\n\n" +
                            _L("This action is not revertible.\nDo you want to proceed?");
        GUI::WarningDialog dialog(m_parent, msg_text, _L("Warning"), wxYES | wxNO);
        if (dialog.ShowModal() == wxID_NO)
            return;
        m_ticks.ticks.clear();
    }
    int extruders_cnt = GUI::wxGetApp().extruders_edited_cnt();
//    int extruder = 2;
    const Print& print = GUI::wxGetApp().plater()->fff_print();
    for (auto object : print.objects()) {
        // An object should to have at least 2 layers to apply an auto color change
        if (object->layer_count() < 2)
            continue;
        check_color_change(object, 1, object->layers().size(), false, [this, extruders_cnt](const Layer* layer)
        {
            int tick = get_tick_from_value(layer->print_z);
            if (tick >= 0 && !m_ticks.has_tick(tick)) {
                if (m_mode == SingleExtruder) {
                    m_ticks.set_default_colors(true);
                    m_ticks.add_tick(tick, ColorChange, 1, layer->print_z);
                }
                else {
                    int extruder = 2;
                    if (!m_ticks.empty()) {
                        auto it = m_ticks.ticks.end();
                        it--;
                        extruder = it->extruder + 1;
                        if (extruder > extruders_cnt)
                            extruder = 1;
                    }
                    m_ticks.add_tick(tick, ToolChange, extruder, layer->print_z);
                }
            }
            // allow max 3 auto color changes
            return m_ticks.ticks.size() > 2;
        });
    }
    if (m_ticks.empty())
        GUI::wxGetApp().plater()->get_notification_manager()->push_notification(GUI::NotificationType::EmptyAutoColorChange);
    post_ticks_changed_event();
}
References _L, Slic3r::DoubleSlider::check_color_change(), Slic3r::DoubleSlider::TickCodeInfo::empty(), Slic3r::PrintObject::layer_count(), Slic3r::PrintObject::layers(), m_ticks, Slic3r::Print::objects(), and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by show_cog_icon_context_menu(), and Slic3r::GUI::Preview::update_layers_slider().
ChangeOneLayerLock()
void Slic3r::DoubleSlider::Control::ChangeOneLayerLock ()
{
    m_is_one_layer = !m_is_one_layer;
    m_selection == ssLower ? correct_lower_value() : correct_higher_value();
    if (!m_selection) m_selection = ssHigher;
    Refresh();
    Update();
    wxCommandEvent e(wxEVT_SCROLL_CHANGED);
    e.SetEventObject(this);
    ProcessWindowEvent(e);
}
References correct_higher_value(), correct_lower_value(), m_is_one_layer, m_selection, Slic3r::DoubleSlider::ssHigher, and Slic3r::DoubleSlider::ssLower.
Referenced by Slic3r::GUI::Preview::update_layers_slider_from_canvas().
check_ticks_changed_event()
bool Slic3r::DoubleSlider::Control::check_ticks_changed_event (Type type) private
{
    if ( m_ticks.mode == m_mode                                                     ||
        (type != ColorChange && type != ToolChange)                       ||
        (m_ticks.mode == SingleExtruder && m_mode == MultiAsSingle) || // All ColorChanges will be applied for 1st extruder
        (m_ticks.mode == MultiExtruder  && m_mode == MultiAsSingle) )  // Just mark ColorChanges for all unused extruders
        return true;
    if ((m_ticks.mode == SingleExtruder && m_mode == MultiExtruder ) ||
        (m_ticks.mode == MultiExtruder  && m_mode == SingleExtruder)    )
    {
        if (!m_ticks.has_tick_with_code(ColorChange))
            return true;
        wxString message = (m_ticks.mode == SingleExtruder ?
                            _L("The last color change data was saved for a single extruder printing.") :
                            _L("The last color change data was saved for a multi extruder printing.")
                            ) + "\n" +
                            _L("Your current changes will delete all saved color changes.") + "\n\n\t" +
                            _L("Are you sure you want to continue?");
        //wxMessageDialog msg(this, message, _L("Notice"), wxYES_NO);
        GUI::MessageDialog msg(this, message, _L("Notice"), wxYES_NO);
        if (msg.ShowModal() == wxID_YES) {
            m_ticks.erase_all_ticks_with_code(ColorChange);
            post_ticks_changed_event(ColorChange);
        }
        return false;
    }
    //          m_ticks_mode == MultiAsSingle
    if( m_ticks.has_tick_with_code(ToolChange) ) {
        wxString message =  m_mode == SingleExtruder ?                          (
                            _L("The last color change data was saved for a multi extruder printing.") + "\n\n" +
                            _L("Select YES if you want to delete all saved tool changes, \n"
                               "NO if you want all tool changes switch to color changes, \n"
                               "or CANCEL to leave it unchanged.") + "\n\n\t" +
                            _L("Do you want to delete all saved tool changes?")
                            ): ( // MultiExtruder
                            _L("The last color change data was saved for a multi extruder printing with tool changes for whole print.") + "\n\n" +
                            _L("Your current changes will delete all saved extruder (tool) changes.") + "\n\n\t" +
                            _L("Are you sure you want to continue?")                  ) ;
        //wxMessageDialog msg(this, message, _L("Notice"), wxYES_NO | (m_mode == SingleExtruder ? wxCANCEL : 0));
        GUI::MessageDialog msg(this, message, _L("Notice"), wxYES_NO | (m_mode == SingleExtruder ? wxCANCEL : 0));
        const int answer = msg.ShowModal();
        if (answer == wxID_YES) {
            m_ticks.erase_all_ticks_with_code(ToolChange);
            post_ticks_changed_event(ToolChange);
        }
        else if (m_mode == SingleExtruder && answer == wxID_NO) {
            m_ticks.switch_code(ToolChange, ColorChange);
            post_ticks_changed_event(ColorChange);
        }
        return false;
    }
    return true;
}
References _L, Slic3r::CustomGCode::ColorChange, Slic3r::DoubleSlider::TickCodeInfo::erase_all_ticks_with_code(), Slic3r::DoubleSlider::TickCodeInfo::has_tick_with_code(), m_mode, m_ticks, Slic3r::DoubleSlider::TickCodeInfo::mode, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::MultiExtruder, post_ticks_changed_event(), Slic3r::CustomGCode::SingleExtruder, Slic3r::DoubleSlider::TickCodeInfo::switch_code(), and Slic3r::CustomGCode::ToolChange.
Referenced by add_code_as_tick(), add_current_tick(), delete_current_tick(), edit_extruder_sequence(), and edit_tick().
correct_higher_value()
void Slic3r::DoubleSlider::Control::correct_higher_value () protected
{
    if (m_higher_value > m_max_value)
        m_higher_value = m_max_value;
    else if (m_higher_value < m_min_value)
        m_higher_value = m_min_value;
    if ((m_higher_value <= m_lower_value && m_higher_value >= m_min_value) || m_is_one_layer)
        m_lower_value = m_higher_value;
}
References m_higher_value, m_is_one_layer, m_lower_value, m_max_value, and m_min_value.
Referenced by ChangeOneLayerLock(), discard_all_thicks(), get_double_value(), move_current_thumb(), move_current_thumb_to_pos(), OnMotion(), SetHigherValue(), and switch_one_layer_mode().
correct_lower_value()
void Slic3r::DoubleSlider::Control::correct_lower_value () protected
{
    if (m_lower_value < m_min_value)
        m_lower_value = m_min_value;
    else if (m_lower_value > m_max_value)
        m_lower_value = m_max_value;
    if ((m_lower_value >= m_higher_value && m_lower_value <= m_max_value) || m_is_one_layer)
        m_higher_value = m_lower_value;
}
References m_higher_value, m_is_one_layer, m_lower_value, m_max_value, and m_min_value.
Referenced by ChangeOneLayerLock(), discard_all_thicks(), move_current_thumb(), move_current_thumb_to_pos(), OnMotion(), SetLowerValue(), and switch_one_layer_mode().
delete_current_tick()
void Slic3r::DoubleSlider::Control::delete_current_tick ()
{
    if (m_selection == ssUndef)
        return;
    auto it = m_ticks.ticks.find(TickCode{ m_selection == ssLower ? m_lower_value : m_higher_value });
    if (it == m_ticks.ticks.end() ||
        !check_ticks_changed_event(it->type))
        return;
    Type type = it->type;
    m_ticks.ticks.erase(it);
    post_ticks_changed_event(type);
}
References check_ticks_changed_event(), m_higher_value, m_lower_value, m_selection, m_ticks, post_ticks_changed_event(), Slic3r::DoubleSlider::ssLower, Slic3r::DoubleSlider::ssUndef, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by OnChar(), OnKeyDown(), OnLeftUp(), and show_edit_context_menu().
detect_selected_slider()
bool Slic3r::DoubleSlider::Control::detect_selected_slider (const wxPoint & pt) protected
{
    if (is_point_in_rect(pt, m_rect_lower_thumb))
        m_selection = is_lower_thumb_editable() ? ssLower : ssUndef;
    else if(is_point_in_rect(pt, m_rect_higher_thumb))
        m_selection = ssHigher;
    else
        return false; // pt doesn't referenced to any thumb
    return true;
}
References is_lower_thumb_editable(), is_point_in_rect(), m_rect_higher_thumb, m_rect_lower_thumb, m_selection, Slic3r::DoubleSlider::ssHigher, Slic3r::DoubleSlider::ssLower, and Slic3r::DoubleSlider::ssUndef.
Referenced by OnLeftDown(), and OnRightDown().
discard_all_thicks()
void Slic3r::DoubleSlider::Control::discard_all_thicks ()
{
    SetLowerValue(m_min_value);
    SetHigherValue(m_max_value);
    m_selection == ssLower ? correct_lower_value() : correct_higher_value();
    if (m_selection == ssUndef) m_selection = ssHigher;
    m_ticks.ticks.clear();
    post_ticks_changed_event();
}
References correct_higher_value(), correct_lower_value(), m_max_value, m_min_value, m_selection, m_ticks, post_ticks_changed_event(), SetHigherValue(), SetLowerValue(), Slic3r::DoubleSlider::ssHigher, Slic3r::DoubleSlider::ssLower, Slic3r::DoubleSlider::ssUndef, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by OnLeftUp().
DoGetBestSize()
wxSize Slic3r::DoubleSlider::Control::DoGetBestSize () const override
{
    const wxSize size = wxControl::DoGetBestSize();
    if (size.x > 1 && size.y > 1)
        return size;
    return get_min_size();
}
References get_min_size().
draw_action_icon()
void Slic3r::DoubleSlider::Control::draw_action_icon (wxDC & dc, const wxPoint pt_beg, const wxPoint pt_end) protected
{
    const int tick = m_selection == ssLower ? m_lower_value : m_higher_value;
    if (!m_enable_action_icon)
        return;
    // suppress add tick on first layer
    if (tick == 0)
        return;
    if (is_wipe_tower_layer(tick)) {
        m_rect_tick_action = wxRect();
        return;
    }
    //wxBitmap* icon = m_focus == fiActionIcon ? &m_bmp_add_tick_off.bmp() : &m_bmp_add_tick_on.bmp();
    //if (m_ticks.ticks.find(TickCode{tick}) != m_ticks.ticks.end())
    //    icon = m_focus == fiActionIcon ? &m_bmp_del_tick_off.bmp() : &m_bmp_del_tick_on.bmp();
    ScalableBitmap* icon = m_focus == fiActionIcon ? &m_bmp_add_tick_off : &m_bmp_add_tick_on;
    if (m_ticks.ticks.find(TickCode{tick}) != m_ticks.ticks.end())
        icon = m_focus == fiActionIcon ? &m_bmp_del_tick_off : &m_bmp_del_tick_on;
    wxCoord x_draw, y_draw;
    is_horizontal() ? x_draw = pt_beg.x - 0.5*m_tick_icon_dim : y_draw = pt_beg.y - 0.5*m_tick_icon_dim;
    if (m_selection == ssLower)
        is_horizontal() ? y_draw = pt_end.y + 3 : x_draw = pt_beg.x - m_tick_icon_dim-2;
    else
        is_horizontal() ? y_draw = pt_beg.y - m_tick_icon_dim-2 : x_draw = pt_end.x + 3;
    if (m_draw_mode == dmSequentialFffPrint) {
        wxBitmap disabled_add = get_bmp_bundle("colorchange_add")->GetBitmapFor(this).ConvertToDisabled();
        dc.DrawBitmap(disabled_add, x_draw, y_draw);
    }
    else
        dc.DrawBitmap((*icon).get_bitmap(), x_draw, y_draw);
    //update rect of the tick action icon
    m_rect_tick_action = wxRect(x_draw, y_draw, m_tick_icon_dim, m_tick_icon_dim);
}
References Slic3r::DoubleSlider::dmSequentialFffPrint, Slic3r::DoubleSlider::fiActionIcon, get_bmp_bundle(), is_horizontal(), is_wipe_tower_layer(), m_bmp_add_tick_off, m_bmp_add_tick_on, m_bmp_del_tick_off, m_bmp_del_tick_on, m_draw_mode, m_enable_action_icon, m_focus, m_higher_value, m_lower_value, m_rect_tick_action, m_selection, m_tick_icon_dim, m_ticks, Slic3r::DoubleSlider::ssLower, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by draw_info_line_with_icon().
draw_cog_icon()
void Slic3r::DoubleSlider::Control::draw_cog_icon (wxDC & dc) protected
{
    if (m_draw_mode == dmSequentialGCodeView)
        return;
    int width, height;
    get_size(&width, &height);
    wxCoord x_draw, y_draw;
    if (m_draw_mode == dmSequentialGCodeView) {
        is_horizontal() ? x_draw = width - 2 : x_draw = 0.5 * width - 0.5 * m_cog_icon_dim;
        is_horizontal() ? y_draw = 0.5 * height - 0.5 * m_cog_icon_dim : y_draw = height - 2;
    }
    else {
        is_horizontal() ? x_draw = width - 2 : x_draw = width - m_cog_icon_dim - 2;
        is_horizontal() ? y_draw = height - m_cog_icon_dim - 2 : y_draw = height - 2;
    }
    dc.DrawBitmap(m_bmp_cog.get_bitmap(), x_draw, y_draw);
    //update rect of the lock/unlock icon
    m_rect_cog_icon = wxRect(x_draw, y_draw, m_cog_icon_dim, m_cog_icon_dim);
}
References Slic3r::DoubleSlider::dmSequentialGCodeView, ScalableBitmap::get_bitmap(), get_size(), is_horizontal(), m_bmp_cog, m_cog_icon_dim, m_draw_mode, and m_rect_cog_icon.
Referenced by render().
draw_colored_band()
void Slic3r::DoubleSlider::Control::draw_colored_band (wxDC & dc) protected
{
    if (m_draw_mode != dmRegular)
        return;
    auto draw_band = [](wxDC& dc, const wxColour& clr, const wxRect& band_rc)
    {
        dc.SetPen(clr);
        dc.SetBrush(clr);
        dc.DrawRectangle(band_rc);
    };
    wxRect main_band = get_colored_band_rect();
    // don't color a band for MultiExtruder mode
    if (m_ticks.empty() || m_mode == MultiExtruder) {
        draw_band(dc, GetParent()->GetBackgroundColour(), main_band);
        return;
    }
    const int default_color_idx = m_mode==MultiAsSingle ? std::max<int>(m_only_extruder - 1, 0) : 0;
    draw_band(dc, wxColour(m_extruder_colors[default_color_idx]), main_band);
    std::set<TickCode>::const_iterator tick_it = m_ticks.ticks.begin();
    while (tick_it != m_ticks.ticks.end())
    {
        if ( (m_mode == SingleExtruder &&  tick_it->type == ColorChange  ) ||
             (m_mode == MultiAsSingle  && (tick_it->type == ToolChange || tick_it->type == ColorChange)) )
        {
            const wxCoord pos = get_position_from_value(tick_it->tick);
            is_horizontal() ? main_band.SetLeft(SLIDER_MARGIN + pos) :
                              main_band.SetBottom(pos - 1);
            const std::string clr_str = m_mode == SingleExtruder ? tick_it->color :
                                        tick_it->type == ToolChange ?
                                        get_color_for_tool_change_tick(tick_it) :
                                        get_color_for_color_change_tick(tick_it);
            if (!clr_str.empty())
                draw_band(dc, wxColour(clr_str), main_band);
        }
        ++tick_it;
    }
}
References Slic3r::CustomGCode::ColorChange, Slic3r::DoubleSlider::dmRegular, Slic3r::DoubleSlider::TickCodeInfo::empty(), get_color_for_color_change_tick(), get_color_for_tool_change_tick(), get_colored_band_rect(), get_position_from_value(), is_horizontal(), m_draw_mode, m_extruder_colors, m_mode, m_only_extruder, m_ticks, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::MultiExtruder, Slic3r::CustomGCode::SingleExtruder, SLIDER_MARGIN, Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
Referenced by render().
draw_focus_rect()
void Slic3r::DoubleSlider::Control::draw_focus_rect (wxDC & dc) protected
{
    if (!m_is_focused)
        return;
    const wxSize sz = GetSize();
//    wxPaintDC dc(this);
    //const wxPen pen = wxPen(wxColour(128, 128, 10), 1, wxPENSTYLE_DOT);
    //dc.SetPen(pen);
    //dc.SetBrush(wxBrush(wxColour(0, 0, 0), wxBRUSHSTYLE_TRANSPARENT));
    dc.SetPen(FOCUS_RECT_PEN);
    dc.SetBrush(FOCUS_RECT_BRUSH);
    dc.DrawRectangle(1, 1, sz.x - 2, sz.y - 2);
}
References FOCUS_RECT_BRUSH, FOCUS_RECT_PEN, and m_is_focused.
Referenced by render().
draw_info_line_with_icon()
void Slic3r::DoubleSlider::Control::draw_info_line_with_icon (wxDC & dc, const wxPoint & pos, SelectedSlider selection) protected
{
    if (m_selection == selection) {
        //draw info line
        dc.SetPen(DARK_ORANGE_PEN);
        const wxPoint pt_beg = is_horizontal() ? wxPoint(pos.x, pos.y - m_thumb_size.y) : wxPoint(pos.x - m_thumb_size.x, pos.y/* - 1*/);
        const wxPoint pt_end = is_horizontal() ? wxPoint(pos.x, pos.y + m_thumb_size.y) : wxPoint(pos.x + m_thumb_size.x, pos.y/* - 1*/);
        dc.DrawLine(pt_beg, pt_end);
        //draw action icon
        if (m_draw_mode == dmRegular || m_draw_mode == dmSequentialFffPrint)
            draw_action_icon(dc, pt_beg, pt_end);
    }
}
References DARK_ORANGE_PEN, Slic3r::DoubleSlider::dmRegular, Slic3r::DoubleSlider::dmSequentialFffPrint, draw_action_icon(), is_horizontal(), m_draw_mode, m_selection, and m_thumb_size.
Referenced by draw_thumb(), and draw_thumbs().
draw_one_layer_icon()
void Slic3r::DoubleSlider::Control::draw_one_layer_icon (wxDC & dc) protected
{
    if (m_draw_mode == dmSequentialGCodeView)
        return;
    //const wxBitmap& icon = m_is_one_layer ?
    //                 m_focus == fiOneLayerIcon ? m_bmp_one_layer_lock_off.bmp()   : m_bmp_one_layer_lock_on.bmp() :
    //                 m_focus == fiOneLayerIcon ? m_bmp_one_layer_unlock_off.bmp() : m_bmp_one_layer_unlock_on.bmp();
    const ScalableBitmap& icon = m_is_one_layer ?
                     m_focus == fiOneLayerIcon ? m_bmp_one_layer_lock_off   : m_bmp_one_layer_lock_on :
                     m_focus == fiOneLayerIcon ? m_bmp_one_layer_unlock_off : m_bmp_one_layer_unlock_on;
    int width, height;
    get_size(&width, &height);
    wxCoord x_draw, y_draw;
    is_horizontal() ? x_draw = width-2 : x_draw = 0.5*width - 0.5*m_lock_icon_dim;
    is_horizontal() ? y_draw = 0.5*height - 0.5*m_lock_icon_dim : y_draw = height-2;
    dc.DrawBitmap(icon.bmp().GetBitmapFor(this), x_draw, y_draw);
    //update rect of the lock/unlock icon
    m_rect_one_layer_icon = wxRect(x_draw, y_draw, m_lock_icon_dim, m_lock_icon_dim);
}
References ScalableBitmap::bmp(), Slic3r::DoubleSlider::dmSequentialGCodeView, Slic3r::DoubleSlider::fiOneLayerIcon, get_size(), is_horizontal(), m_bmp_one_layer_lock_off, m_bmp_one_layer_lock_on, m_bmp_one_layer_unlock_off, m_bmp_one_layer_unlock_on, m_draw_mode, m_focus, m_is_one_layer, m_lock_icon_dim, and m_rect_one_layer_icon.
Referenced by render().
draw_revert_icon()
void Slic3r::DoubleSlider::Control::draw_revert_icon (wxDC & dc) protected
{
    if (m_ticks.empty() || m_draw_mode != dmRegular)
        return;
    int width, height;
    get_size(&width, &height);
    wxCoord x_draw, y_draw;
    is_horizontal() ? x_draw = width-2 : x_draw = 0.25*SLIDER_MARGIN;
    is_horizontal() ? y_draw = 0.25*SLIDER_MARGIN: y_draw = height-2;
    dc.DrawBitmap(m_bmp_revert.get_bitmap(), x_draw, y_draw);
    //update rect of the lock/unlock icon
    m_rect_revert_icon = wxRect(x_draw, y_draw, m_revert_icon_dim, m_revert_icon_dim);
}
References Slic3r::DoubleSlider::dmRegular, Slic3r::DoubleSlider::TickCodeInfo::empty(), ScalableBitmap::get_bitmap(), get_size(), is_horizontal(), m_bmp_revert, m_draw_mode, m_rect_revert_icon, m_revert_icon_dim, m_ticks, and SLIDER_MARGIN.
Referenced by render().
draw_ruler()
void Slic3r::DoubleSlider::Control::draw_ruler (wxDC & dc) protected
{
    if (m_values.empty() || !m_ruler.can_draw())
        return;
    // When "No sparce layer" is enabled, use m_layers_values for ruler update.
    // Because of m_values has duplicate values in this case.
//    m_ruler.update(this->GetParent(), m_layers_values.empty() ? m_values : m_layers_values, get_scroll_step());
    int height, width;
    get_size(&width, &height);
    const wxCoord mid = is_horizontal() ? 0.5 * height : 0.5 * width;
    dc.SetPen(GREY_PEN);
    wxColour old_clr = dc.GetTextForeground();
    dc.SetTextForeground(GREY_PEN.GetColour());
    auto draw_short_ticks = [this, mid](wxDC& dc, double& current_tick, int max_tick) {
        if (m_ruler.short_step <= 0.0)
            return;
        while (current_tick < max_tick) {
            wxCoord pos = get_position_from_value(lround(current_tick));
            draw_ticks_pair(dc, pos, mid, 2);
            current_tick += m_ruler.short_step;
            if (current_tick > m_max_value)
                break;
        }
    };
    double short_tick = NaNd;
    int tick = 0;
    double value = 0.0;
    size_t sequence = 0;
    int prev_y_pos = -1;
    wxCoord label_height = dc.GetMultiLineTextExtent("0").y - 2;
    int values_size = (int)m_values.size();
    if (m_ruler.long_step < 0) {
        // sequential print when long_step wasn't detected because of a lot of printed objects
        if (m_ruler.max_values.size() > 1) {
            while (tick <= m_max_value && sequence < m_ruler.count()) {
                // draw just ticks with max value
                value = m_ruler.max_values[sequence];
                short_tick = tick;
                for (; tick < values_size; tick++) {
                    if (m_values[tick] == value)
                        break;
                    if (m_values[tick] > value) {
                        if (tick > 0)
                            tick--;
                        break;
                    }
                }
                if (tick > m_max_value)
                    break;
                wxCoord pos = get_position_from_value(tick);
                draw_ticks_pair(dc, pos, mid, 5);
                if (prev_y_pos < 0 || prev_y_pos - pos >= label_height) {
                    draw_tick_text(dc, wxPoint(mid, pos), tick);
                    prev_y_pos = pos;
                }
                draw_short_ticks(dc, short_tick, tick);
                sequence++;
                tick++;
            }
        }
        // very short object or some non-trivial ruler with non-regular step (see https://github.com/prusa3d/PrusaSlicer/issues/7263)
        else {
            if (get_scroll_step() < 1) // step less then 1 px indicates very tall object with non-regular laayer step (probably in vase mode)
                return;
            for (size_t tick = 1; tick < m_values.size(); tick++) {
                wxCoord pos = get_position_from_value(tick);
                draw_ticks_pair(dc, pos, mid, 5);
                draw_tick_text(dc, wxPoint(mid, pos), tick);
            }
        }
    }
    else {
        while (tick <= m_max_value) {
            value += m_ruler.long_step;
            if (sequence < m_ruler.count() && value > m_ruler.max_values[sequence])
                value = m_ruler.max_values[sequence];
            short_tick = tick;
            for (; tick < values_size; tick++) {
                if (m_values[tick] == value)
                    break;
                if (m_values[tick] > value) {
                    if (tick > 0)
                        tick--;
                    break;
                }
            }
            if (tick > m_max_value)
                break;
            wxCoord pos = get_position_from_value(tick);
            draw_ticks_pair(dc, pos, mid, 5);
            if (prev_y_pos < 0 || prev_y_pos - pos >= label_height) {
                draw_tick_text(dc, wxPoint(mid, pos), tick);
                prev_y_pos = pos;
            }
            draw_short_ticks(dc, short_tick, tick);
            if (sequence < m_ruler.count() && value == m_ruler.max_values[sequence]) {
                value = 0.0;
                sequence++;
                tick++;
            }
        }
        // short ticks from the last tick to the end
        draw_short_ticks(dc, short_tick, m_max_value);
    }
    dc.SetTextForeground(old_clr);
}
References Slic3r::DoubleSlider::Control::Ruler::can_draw(), Slic3r::DoubleSlider::Control::Ruler::count(), draw_tick_text(), draw_ticks_pair(), get_position_from_value(), get_scroll_step(), get_size(), GREY_PEN, is_horizontal(), Slic3r::DoubleSlider::Control::Ruler::long_step, m_max_value, m_ruler, m_values, Slic3r::DoubleSlider::Control::Ruler::max_values, Slic3r::NaNd, and Slic3r::DoubleSlider::Control::Ruler::short_step.
Referenced by render().
draw_scroll_line()
void Slic3r::DoubleSlider::Control::draw_scroll_line (wxDC & dc, const int lower_pos, const int higher_pos) protected
{
    int width;
    int height;
    get_size(&width, &height);
    wxCoord line_beg_x = is_horizontal() ? SLIDER_MARGIN : width*0.5 - 1;
    wxCoord line_beg_y = is_horizontal() ? height*0.5 - 1 : SLIDER_MARGIN;
    wxCoord line_end_x = is_horizontal() ? width - SLIDER_MARGIN + 1 : width*0.5 - 1;
    wxCoord line_end_y = is_horizontal() ? height*0.5 - 1 : height - SLIDER_MARGIN + 1;
    wxCoord segm_beg_x = is_horizontal() ? lower_pos : width*0.5 - 1;
    wxCoord segm_beg_y = is_horizontal() ? height*0.5 - 1 : lower_pos/*-1*/;
    wxCoord segm_end_x = is_horizontal() ? higher_pos : width*0.5 - 1;
    wxCoord segm_end_y = is_horizontal() ? height*0.5 - 1 : higher_pos-1;
    for (size_t id = 0; id < m_line_pens.size(); id++) {
        dc.SetPen(*m_line_pens[id]);
        dc.DrawLine(line_beg_x, line_beg_y, line_end_x, line_end_y);
        dc.SetPen(*m_segm_pens[id]);
        dc.DrawLine(segm_beg_x, segm_beg_y, segm_end_x, segm_end_y);
        if (is_horizontal())
            line_beg_y = line_end_y = segm_beg_y = segm_end_y += 1;
        else
            line_beg_x = line_end_x = segm_beg_x = segm_end_x += 1;
    }
}
References get_size(), is_horizontal(), m_line_pens, m_segm_pens, and SLIDER_MARGIN.
Referenced by render().
draw_thumb()
void Slic3r::DoubleSlider::Control::draw_thumb (wxDC & dc, const wxCoord & pos_coord, const SelectedSlider & selection) protected
{
    //calculate thumb position on slider line
    int width, height;
    get_size(&width, &height);
    const wxPoint pos = is_horizontal() ? wxPoint(pos_coord, height*0.5) : wxPoint(0.5*width, pos_coord);
    // Draw thumb
    draw_thumb_item(dc, pos, selection);
    // Draw info_line
    draw_info_line_with_icon(dc, pos, selection);
    // Draw thumb text
    draw_thumb_text(dc, pos, selection);
}
References draw_info_line_with_icon(), draw_thumb_item(), draw_thumb_text(), get_size(), and is_horizontal().
draw_thumb_item()
void Slic3r::DoubleSlider::Control::draw_thumb_item (wxDC & dc, const wxPoint & pos, const SelectedSlider & selection) protected
{
    wxCoord x_draw = pos.x - int(0.5 * m_thumb_size.x);
    wxCoord y_draw = pos.y - int(0.5 * m_thumb_size.y);
    dc.DrawBitmap(selection == ssLower ? m_bmp_thumb_lower.get_bitmap() : m_bmp_thumb_higher.get_bitmap(), x_draw, y_draw);
    // Update thumb rect
    update_thumb_rect(x_draw, y_draw, selection);
}
References ScalableBitmap::get_bitmap(), m_bmp_thumb_higher, m_bmp_thumb_lower, m_thumb_size, Slic3r::DoubleSlider::ssLower, and update_thumb_rect().
Referenced by draw_thumb(), and draw_thumbs().
draw_thumb_text()
void Slic3r::DoubleSlider::Control::draw_thumb_text (wxDC & dc, const wxPoint & pos, const SelectedSlider & selection) const protected
{
    draw_tick_text(dc, pos, selection == ssLower ? m_lower_value : m_higher_value, ltHeightWithLayer, selection == ssLower);
}
References draw_tick_text(), Slic3r::DoubleSlider::ltHeightWithLayer, m_higher_value, m_lower_value, and Slic3r::DoubleSlider::ssLower.
Referenced by draw_thumb(), and draw_thumbs().
draw_thumbs()
void Slic3r::DoubleSlider::Control::draw_thumbs (wxDC & dc, const wxCoord & lower_pos, const wxCoord & higher_pos) protected
{
    //calculate thumb position on slider line
    int width, height;
    get_size(&width, &height);
    const wxPoint pos_l = is_horizontal() ? wxPoint(lower_pos, height*0.5) : wxPoint(0.5*width, lower_pos);
    const wxPoint pos_h = is_horizontal() ? wxPoint(higher_pos, height*0.5) : wxPoint(0.5*width, higher_pos);
    // Draw lower thumb
    draw_thumb_item(dc, pos_l, ssLower);
    // Draw lower info_line
    draw_info_line_with_icon(dc, pos_l, ssLower);
    // Draw higher thumb
    draw_thumb_item(dc, pos_h, ssHigher);
    // Draw higher info_line
    draw_info_line_with_icon(dc, pos_h, ssHigher);
    // Draw higher thumb text
    draw_thumb_text(dc, pos_h, ssHigher);
    // Draw lower thumb text
    draw_thumb_text(dc, pos_l, ssLower);
}
References draw_info_line_with_icon(), draw_thumb_item(), draw_thumb_text(), get_size(), is_horizontal(), Slic3r::DoubleSlider::ssHigher, and Slic3r::DoubleSlider::ssLower.
Referenced by render().
draw_tick_on_mouse_position()
void Slic3r::DoubleSlider::Control::draw_tick_on_mouse_position (wxDC & dc) protected
{
    if (!m_is_focused || m_moving_pos == wxDefaultPosition)
        return;
    //calculate thumb position on slider line
    int width, height;
    get_size(&width, &height);
    int tick = get_tick_near_point(m_moving_pos);
    if (tick == m_higher_value || tick == m_lower_value)
        return ;
    auto draw_ticks = [this](wxDC& dc, wxPoint pos, int margin=0 )
    {
        wxPoint pt_beg = is_horizontal() ? wxPoint(pos.x+margin, pos.y - m_thumb_size.y) : wxPoint(pos.x - m_thumb_size.x          , pos.y+margin);
        wxPoint pt_end = is_horizontal() ? wxPoint(pos.x+margin, pos.y + m_thumb_size.y) : wxPoint(pos.x - 0.5 * m_thumb_size.x + 1, pos.y+margin);
        dc.DrawLine(pt_beg, pt_end);
        pt_beg = is_horizontal() ? wxPoint(pos.x + margin, pos.y - m_thumb_size.y) : wxPoint(pos.x + 0.5 * m_thumb_size.x, pos.y+margin);
        pt_end = is_horizontal() ? wxPoint(pos.x + margin, pos.y + m_thumb_size.y) : wxPoint(pos.x + m_thumb_size.x + 1,   pos.y+margin);
        dc.DrawLine(pt_beg, pt_end);
    };
    auto draw_touch = [this](wxDC& dc, wxPoint pos, int margin, bool right_side )
    {
        int mult = right_side ? 1 : -1;
        wxPoint pt_beg = is_horizontal() ? wxPoint(pos.x - margin, pos.y + mult * m_thumb_size.y) : wxPoint(pos.x + mult * m_thumb_size.x, pos.y - margin);
        wxPoint pt_end = is_horizontal() ? wxPoint(pos.x + margin, pos.y + mult * m_thumb_size.y) : wxPoint(pos.x + mult * m_thumb_size.x, pos.y + margin);
        dc.DrawLine(pt_beg, pt_end);
    };
    if (tick > 0) // this tick exists and should be marked as a focused
    {
        wxCoord new_pos = get_position_from_value(tick);
        const wxPoint pos = is_horizontal() ? wxPoint(new_pos, height * 0.5) : wxPoint(0.5 * width, new_pos);
        dc.SetPen(DARK_ORANGE_PEN);
        draw_ticks(dc, pos, -2);
        draw_ticks(dc, pos, 2 );
        draw_touch(dc, pos, 2, true);
        draw_touch(dc, pos, 2, false);
        return;
    }
    tick = get_value_from_position(m_moving_pos);
    if (tick > m_max_value || tick < m_min_value || tick == m_higher_value || tick == m_lower_value)
        return;
    wxCoord new_pos = get_position_from_value(tick);
    const wxPoint pos = is_horizontal() ? wxPoint(new_pos, height * 0.5) : wxPoint(0.5 * width, new_pos);
    //draw info line
    dc.SetPen(LIGHT_GREY_PEN);
    draw_ticks(dc, pos);
    if (m_extra_style & wxSL_VALUE_LABEL) {
        wxColour old_clr = dc.GetTextForeground();
        dc.SetTextForeground(GREY_PEN.GetColour());
        draw_tick_text(dc, pos, tick, ltEstimatedTime, false);
        dc.SetTextForeground(old_clr);
    }
}
References DARK_ORANGE_PEN, draw_tick_text(), draw_ticks(), get_position_from_value(), get_size(), get_tick_near_point(), get_value_from_position(), GREY_PEN, is_horizontal(), LIGHT_GREY_PEN, Slic3r::DoubleSlider::ltEstimatedTime, m_extra_style, m_higher_value, m_is_focused, m_lower_value, m_max_value, m_min_value, m_moving_pos, and m_thumb_size.
Referenced by render().
draw_tick_text()
void Slic3r::DoubleSlider::Control::draw_tick_text (wxDC & dc, const wxPoint & pos, int tick, LabelType label_type = ltHeight, bool right_side = true) const protected
{
    wxCoord text_width, text_height;
    const wxString label = get_label(tick, label_type);
    dc.GetMultiLineTextExtent(label, &text_width, &text_height);
    wxPoint text_pos;
    if (right_side) {
        if (is_horizontal()) {
            int width;
            int height;
            get_size(&width, &height);
            int x_right = pos.x + 1 + text_width;
            int xx = (x_right < width) ? pos.x + 1 : pos.x - text_width - 1;
            text_pos = wxPoint(xx, pos.y + m_thumb_size.x / 2 + 1);
        }
        else
            text_pos = wxPoint(pos.x + m_thumb_size.x + 1, pos.y - 0.5 * text_height - 1);
    }
    else {
        if (is_horizontal()) {
            int x = pos.x - text_width - 1;
            int xx = (x > 0) ? x : pos.x + 1;
            text_pos = wxPoint(xx, pos.y - m_thumb_size.x / 2 - text_height - 1);
        }
        else
            text_pos = wxPoint(std::max(2, pos.x - text_width - 1 - m_thumb_size.x), pos.y - 0.5 * text_height + 1);
    }
    wxColour old_clr = dc.GetTextForeground();
    const wxPen& pen = is_wipe_tower_layer(tick) && (tick == m_lower_value || tick == m_higher_value) ? DARK_ORANGE_PEN : /*wxPen(old_clr)*/GREY_PEN;
    dc.SetPen(pen);
    dc.SetTextForeground(pen.GetColour());
    if (label_type == ltEstimatedTime)
        dc.DrawLabel(label, wxRect(text_pos, wxSize(text_width, text_height)), wxALIGN_RIGHT);
    else
        dc.DrawText(label, text_pos);
    dc.SetTextForeground(old_clr);
}
References DARK_ORANGE_PEN, get_label(), get_size(), GREY_PEN, is_horizontal(), is_wipe_tower_layer(), Slic3r::DoubleSlider::ltEstimatedTime, m_higher_value, m_lower_value, and m_thumb_size.
Referenced by draw_ruler(), draw_thumb_text(), and draw_tick_on_mouse_position().
draw_ticks()
void Slic3r::DoubleSlider::Control::draw_ticks (wxDC & dc) protected
{
    if (m_draw_mode == dmSlaPrint)
        return;
    dc.SetPen(m_draw_mode == dmRegular ? DARK_GREY_PEN : LIGHT_GREY_PEN );
    int height, width;
    get_size(&width, &height);
    const wxCoord mid = is_horizontal() ? 0.5*height : 0.5*width;
    for (const TickCode& tick : m_ticks.ticks) {
        if (size_t(tick.tick) >= m_values.size()) {
            // The case when OnPaint is called before m_ticks.ticks data are updated (specific for the vase mode)
            break;
        }
        const wxCoord pos = get_position_from_value(tick.tick);
        draw_ticks_pair(dc, pos, mid, 7);
        // if current tick if focused, we should to use a specific "focused" icon
        bool focused_tick = m_moving_pos != wxDefaultPosition && tick.tick == get_tick_near_point(m_moving_pos);
        // get icon name if it is
        std::string icon_name;
        // if we have non-regular draw mode, all ticks should be marked with error icon
        if (m_draw_mode != dmRegular)
            icon_name = focused_tick ? "error_tick_f" : "error_tick";
        else if (tick.type == ColorChange || tick.type == ToolChange) {
            if (m_ticks.is_conflict_tick(tick, m_mode, m_only_extruder, m_values[tick.tick]))
                icon_name = focused_tick ? "error_tick_f" : "error_tick";
        }
        else if (tick.type == PausePrint)
            icon_name = focused_tick ? "pause_print_f" : "pause_print";
        else
            icon_name = focused_tick ? "edit_gcode_f" : "edit_gcode";
        // Draw icon for "Pause print", "Custom Gcode" or conflict tick
        if (!icon_name.empty())  {
            wxBitmapBundle* icon = get_bmp_bundle(icon_name);
            wxCoord x_draw, y_draw;
            is_horizontal() ? x_draw = pos - 0.5 * m_tick_icon_dim : y_draw = pos - 0.5 * m_tick_icon_dim;
            is_horizontal() ? y_draw = mid + 22 : x_draw = mid + m_thumb_size.x + 3;
            dc.DrawBitmap(icon->GetBitmapFor(this), x_draw, y_draw);
        }
    }
}
References Slic3r::CustomGCode::ColorChange, DARK_GREY_PEN, Slic3r::DoubleSlider::dmRegular, Slic3r::DoubleSlider::dmSlaPrint, draw_ticks_pair(), get_bmp_bundle(), get_position_from_value(), get_size(), get_tick_near_point(), Slic3r::DoubleSlider::TickCodeInfo::is_conflict_tick(), is_horizontal(), LIGHT_GREY_PEN, m_draw_mode, m_mode, m_moving_pos, m_only_extruder, m_thumb_size, m_tick_icon_dim, m_ticks, m_values, Slic3r::CustomGCode::PausePrint, Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
Referenced by draw_tick_on_mouse_position(), and render().
draw_ticks_pair()
void Slic3r::DoubleSlider::Control::draw_ticks_pair (wxDC & dc, wxCoord pos, wxCoord mid, int tick_len) protected
{
    int mid_space = 9;
    is_horizontal() ? dc.DrawLine(pos, mid - (mid_space + tick_len), pos, mid - mid_space) :
        dc.DrawLine(mid - (mid_space + tick_len), pos, mid - mid_space, pos);
    is_horizontal() ? dc.DrawLine(pos, mid + (mid_space + tick_len), pos, mid + mid_space) :
        dc.DrawLine(mid + (mid_space + tick_len), pos, mid + mid_space, pos);
}
References is_horizontal().
Referenced by draw_ruler(), and draw_ticks().
edit_extruder_sequence()
void Slic3r::DoubleSlider::Control::edit_extruder_sequence ()
{
    if (!check_ticks_changed_event(ToolChange))
        return;
    GUI::ExtruderSequenceDialog dlg(m_extruders_sequence);
    if (dlg.ShowModal() != wxID_OK)
        return;
    m_extruders_sequence = dlg.GetValue();
    m_ticks.erase_all_ticks_with_code(ToolChange);
    const int extr_cnt = m_extruders_sequence.extruders.size();
    if (extr_cnt == 1)
        return;
    int tick = 0;
    double value = 0.0;
    int extruder = -1;
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> distrib(0, extr_cnt-1);
    while (tick <= m_max_value)
    {
        bool color_repetition = false;
        if (m_extruders_sequence.random_sequence) {
            int rand_extr = distrib(gen);
            if (m_extruders_sequence.color_repetition)
                color_repetition = rand_extr == extruder;
            else
                while (rand_extr == extruder)
                    rand_extr = distrib(gen);
            extruder = rand_extr;
        }
        else {
            extruder++;
            if (extruder == extr_cnt)
                extruder = 0;
        }
        const int cur_extruder = m_extruders_sequence.extruders[extruder];
        bool meaningless_tick = tick == 0.0 && cur_extruder == extruder;
        if (!meaningless_tick && !color_repetition)
            m_ticks.ticks.emplace(TickCode{tick, ToolChange,cur_extruder + 1, m_extruder_colors[cur_extruder]});
        if (m_extruders_sequence.is_mm_intervals) {
            value += m_extruders_sequence.interval_by_mm;
            tick = get_tick_from_value(value, true);
            if (tick < 0)
                break;
        }
        else
            tick += m_extruders_sequence.interval_by_layers;
    }
    post_ticks_changed_event(ToolChange);
}
References check_ticks_changed_event(), Slic3r::DoubleSlider::ExtrudersSequence::color_repetition, Slic3r::DoubleSlider::TickCodeInfo::erase_all_ticks_with_code(), Slic3r::DoubleSlider::ExtrudersSequence::extruders, get_tick_from_value(), Slic3r::GUI::ExtruderSequenceDialog::GetValue(), Slic3r::DoubleSlider::ExtrudersSequence::interval_by_layers, Slic3r::DoubleSlider::ExtrudersSequence::interval_by_mm, Slic3r::DoubleSlider::ExtrudersSequence::is_mm_intervals, m_extruder_colors, m_extruders_sequence, m_max_value, m_ticks, post_ticks_changed_event(), Slic3r::DoubleSlider::ExtrudersSequence::random_sequence, Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
Referenced by show_cog_icon_context_menu().
edit_tick()
void Slic3r::DoubleSlider::Control::edit_tick (int tick = -1)
{
    if (tick < 0)
        tick = m_selection == ssLower ? m_lower_value : m_higher_value;
    const std::set<TickCode>::iterator it = m_ticks.ticks.find(TickCode{ tick });
    if (it == m_ticks.ticks.end() ||
        !check_ticks_changed_event(it->type))
        return;
    Type type = it->type;
    if (m_ticks.edit_tick(it, m_values[it->tick]))
        post_ticks_changed_event(type);
}
References check_ticks_changed_event(), Slic3r::DoubleSlider::TickCodeInfo::edit_tick(), m_higher_value, m_lower_value, m_selection, m_ticks, m_values, post_ticks_changed_event(), Slic3r::DoubleSlider::ssLower, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by OnRightUp(), and show_edit_context_menu().
enable_action_icon()
void Slic3r::DoubleSlider::Control::enable_action_icon (bool enable) inline
{ m_enable_action_icon = enable; }
References m_enable_action_icon.
Referenced by Slic3r::GUI::Preview::create_layers_slider_sizer().
enter_window()
void Slic3r::DoubleSlider::Control::enter_window (wxMouseEvent & event, const bool enter) protected
{
    m_is_focused = enter;
    Refresh();
    Update();
    event.Skip();
}
References m_is_focused.
Referenced by OnEnterWin(), and OnLeaveWin().
get_active_extruders_for_tick()
std::array< int, 2 > Slic3r::DoubleSlider::Control::get_active_extruders_for_tick (int tick) const private
{
    int default_initial_extruder = m_mode == MultiAsSingle ? std::max<int>(1, m_only_extruder) : 1;
    std::array<int, 2> extruders = { default_initial_extruder, -1 };
    if (m_ticks.empty())
        return extruders;
    auto it = m_ticks.ticks.lower_bound(TickCode{tick});
    if (it != m_ticks.ticks.end() && it->tick == tick) // current tick exists
        extruders[1] = it->extruder;
    while (it != m_ticks.ticks.begin()) {
        --it;
        if(it->type == ToolChange) {
            extruders[0] = it->extruder;
            break;
        }
    }
    return extruders;
}
References Slic3r::DoubleSlider::TickCodeInfo::empty(), m_mode, m_only_extruder, m_ticks, Slic3r::CustomGCode::MultiAsSingle, Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
Referenced by append_change_extruder_menu_item().
get_color_for_color_change_tick()
std::string Slic3r::DoubleSlider::Control::get_color_for_color_change_tick (std::set< TickCode >::const_iterator it) const private
{
    const int def_extruder = std::max<int>(1, m_only_extruder);
    auto it_n = it;
    bool is_tool_change = false;
    while (it_n != m_ticks.ticks.begin()) {
        --it_n;
        if (it_n->type == ToolChange) {
            is_tool_change = true;
            if (it_n->extruder == it->extruder)
                return it->color;
            break;
        }
        if (it_n->type == ColorChange && it_n->extruder == it->extruder)
            return it->color;
    }
    if (!is_tool_change && it->extruder == def_extruder)
        return it->color;
    return "";
}
References Slic3r::CustomGCode::ColorChange, m_only_extruder, m_ticks, Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
Referenced by draw_colored_band().
get_color_for_tool_change_tick()
std::string Slic3r::DoubleSlider::Control::get_color_for_tool_change_tick (std::set< TickCode >::const_iterator it) const private
{
    const int current_extruder = it->extruder == 0 ? std::max<int>(m_only_extruder, 1) : it->extruder;
    auto it_n = it;
    while (it_n != m_ticks.ticks.begin()) {
        --it_n;
        if (it_n->type == ColorChange && it_n->extruder == current_extruder)
            return it_n->color;
    }
    return m_extruder_colors[current_extruder-1]; // return a color for a specific extruder from the colors list
}
References Slic3r::CustomGCode::ColorChange, m_extruder_colors, m_only_extruder, m_ticks, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by draw_colored_band().
get_colored_band_rect()
wxRect Slic3r::DoubleSlider::Control::get_colored_band_rect () private
{
    int height, width;
    get_size(&width, &height);
    const wxCoord mid = is_horizontal() ? 0.5 * height : 0.5 * width;
    return is_horizontal() ?
           wxRect(SLIDER_MARGIN, lround(mid - 0.375 * m_thumb_size.y),
                  width - 2 * SLIDER_MARGIN + 1, lround(0.75 * m_thumb_size.y)) :
           wxRect(lround(mid - 0.375 * m_thumb_size.x), SLIDER_MARGIN,
                  lround(0.75 * m_thumb_size.x), height - 2 * SLIDER_MARGIN + 1);
}
References get_size(), is_horizontal(), m_thumb_size, and SLIDER_MARGIN.
Referenced by draw_colored_band(), OnMotion(), and OnRightDown().
get_double_value()
double Slic3r::DoubleSlider::Control::get_double_value (const SelectedSlider & selection) private
{
    if (m_values.empty() || m_lower_value<0)
        return 0.0;
    if (m_values.size() <= size_t(m_higher_value)) {
        correct_higher_value();
        return m_values.back();
    }
    return m_values[selection == ssLower ? m_lower_value : m_higher_value];
}
References correct_higher_value(), m_higher_value, m_lower_value, m_values, and Slic3r::DoubleSlider::ssLower.
Referenced by GetHigherValueD(), and GetLowerValueD().
get_edited_tick_for_position()
int Slic3r::DoubleSlider::Control::get_edited_tick_for_position (wxPoint pos, Type type = ColorChange) private
{
    if (m_ticks.empty())
        return -1;
    int tick = get_value_from_position(pos);
    auto it = std::lower_bound(m_ticks.ticks.begin(), m_ticks.ticks.end(), TickCode{ tick });
    while (it != m_ticks.ticks.begin()) {
        --it;
        if (it->type == type)
            return it->tick;
    }
    return -1;
}
References Slic3r::DoubleSlider::TickCodeInfo::empty(), get_value_from_position(), m_ticks, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by OnMotion(), and OnRightUp().
get_label()
wxString Slic3r::DoubleSlider::Control::get_label (int tick, LabelType label_type = ltHeightWithLayer) const private
{
    const size_t value = tick;
    if (m_label_koef == 1.0 && m_values.empty())
        return wxString::Format("%lu", static_cast<unsigned long>(value));
    if (value >= m_values.size())
        return "ErrVal";
    // When "Print Settings -> Multiple Extruders -> No sparse layer" is enabled, then "Smart" Wipe Tower is used for wiping.
    // As a result, each layer with tool changes is splited for min 3 parts: first tool, wiping, second tool ...
    // So, vertical slider have to respect to this case.
    // see https://github.com/prusa3d/PrusaSlicer/issues/6232.
    // m_values contains data for all layer's parts,
    // but m_layers_values contains just unique Z values.
    // Use this function for correct conversion slider position to number of printed layer
    auto get_layer_number = [this](int value, LabelType label_type) {
        if (label_type == ltEstimatedTime && m_layers_times.empty())
            return size_t(-1);
        double layer_print_z = m_values[is_wipe_tower_layer(value) ? std::max<int>(value - 1, 0) : value];
        auto it = std::lower_bound(m_layers_values.begin(), m_layers_values.end(), layer_print_z - epsilon());
        if (it == m_layers_values.end()) {
            it = std::lower_bound(m_values.begin(), m_values.end(), layer_print_z - epsilon());
            if (it == m_values.end())
                return size_t(-1);
            return size_t(value);
        }
        return size_t(it - m_layers_values.begin());
    };
    if (m_draw_mode == dmSequentialGCodeView)
        return wxString::Format("%lu", static_cast<unsigned long>(m_alternate_values[value]));
    else {
        if (label_type == ltEstimatedTime) {
            if (m_is_wipe_tower) {
                size_t layer_number = get_layer_number(value, label_type);
                return (layer_number == size_t(-1) || layer_number == m_layers_times.size()) ? "" : short_and_splitted_time(get_time_dhms(m_layers_times[layer_number]));
            }
            return value < m_layers_times.size() ? short_and_splitted_time(get_time_dhms(m_layers_times[value])) : "";
        }
        wxString str = m_values.empty() ?
            wxString::Format("%.*f", 2, m_label_koef * value) :
            wxString::Format("%.*f", 2, m_values[value]);
        if (label_type == ltHeight)
            return str;
        if (label_type == ltHeightWithLayer) {
            size_t layer_number = m_is_wipe_tower ? get_layer_number(value, label_type) + 1 : (m_values.empty() ? value : value + 1);
            return format_wxstr("%1%\n(%2%)", str, layer_number);
        }
    }
    return wxEmptyString;
}
References Slic3r::DoubleSlider::dmSequentialGCodeView, Slic3r::DoubleSlider::epsilon(), Slic3r::get_time_dhms(), is_wipe_tower_layer(), Slic3r::DoubleSlider::ltEstimatedTime, Slic3r::DoubleSlider::ltHeight, Slic3r::DoubleSlider::ltHeightWithLayer, m_alternate_values, m_draw_mode, m_is_wipe_tower, m_label_koef, m_layers_times, m_layers_values, m_values, and Slic3r::DoubleSlider::short_and_splitted_time().
Referenced by draw_tick_text().
get_lower_and_higher_position()
void Slic3r::DoubleSlider::Control::get_lower_and_higher_position (int & lower_pos, int & higher_pos) private
{
    const double step = get_scroll_step();
    if (is_horizontal()) {
        lower_pos = SLIDER_MARGIN + int(m_lower_value*step + 0.5);
        higher_pos = SLIDER_MARGIN + int(m_higher_value*step + 0.5);
    }
    else {
        lower_pos = SLIDER_MARGIN + int((m_max_value - m_lower_value)*step + 0.5);
        higher_pos = SLIDER_MARGIN + int((m_max_value - m_higher_value)*step + 0.5);
    }
}
References get_scroll_step(), is_horizontal(), m_higher_value, m_lower_value, m_max_value, and SLIDER_MARGIN.
get_min_size()
wxSize Slic3r::DoubleSlider::Control::get_min_size () const
{
    const int min_side = GUI::wxGetApp().em_unit() * ( is_horizontal() ? 5 : 11 );
    return wxSize(min_side, min_side);
}
References is_horizontal().
Referenced by Control(), DoGetBestSize(), and msw_rescale().
get_position_from_value()
wxCoord Slic3r::DoubleSlider::Control::get_position_from_value (const int value) private
{
    const double step = get_scroll_step();
    const int val = is_horizontal() ? value : m_max_value - value;
    return wxCoord(SLIDER_MARGIN + int(val*step + 0.5));
}
References get_scroll_step(), is_horizontal(), m_max_value, and SLIDER_MARGIN.
Referenced by add_current_tick(), draw_colored_band(), draw_ruler(), draw_tick_on_mouse_position(), draw_ticks(), get_tick_near_point(), and render().
get_scroll_step()
double Slic3r::DoubleSlider::Control::get_scroll_step () private
{
    const wxSize sz = get_size();
    const int& slider_len = m_style == wxSL_HORIZONTAL ? sz.x : sz.y;
    return double(slider_len - SLIDER_MARGIN * 2) / (m_max_value - m_min_value);
}
References get_size(), m_max_value, m_min_value, m_style, and SLIDER_MARGIN.
Referenced by Control(), draw_ruler(), get_lower_and_higher_position(), get_position_from_value(), get_value_from_position(), msw_rescale(), SetLayersTimes(), and SetSliderValues().
get_size() [1/2]
wxSize Slic3r::DoubleSlider::Control::get_size () const private
{
    int w, h;
    get_size(&w, &h);
    return wxSize(w, h);
}
References get_size().
Referenced by add_current_tick(), draw_cog_icon(), draw_one_layer_icon(), draw_revert_icon(), draw_ruler(), draw_scroll_line(), draw_thumb(), draw_thumbs(), draw_tick_on_mouse_position(), draw_tick_text(), draw_ticks(), get_colored_band_rect(), get_scroll_step(), get_size(), and get_value_from_position().
get_size() [2/2]
void Slic3r::DoubleSlider::Control::get_size (int * w, int * h) const private
{
    GetSize(w, h);
    if (m_draw_mode == dmSequentialGCodeView)
        return; // we have no more icons for drawing
    is_horizontal() ? *w -= m_lock_icon_dim : *h -= m_lock_icon_dim;
}
References Slic3r::DoubleSlider::dmSequentialGCodeView, is_horizontal(), m_draw_mode, and m_lock_icon_dim.
get_tick_from_value()
int Slic3r::DoubleSlider::Control::get_tick_from_value (double value, bool force_lower_bound = false) private
{
    std::vector<double>::iterator it;
    if (m_is_wipe_tower && !force_lower_bound)
        it = std::find_if(m_values.begin(), m_values.end(),
                          [value](const double & val) { return fabs(value - val) <= epsilon(); });
    else
        it = std::lower_bound(m_values.begin(), m_values.end(), value - epsilon());
    if (it == m_values.end())
        return -1;
    return int(it - m_values.begin());
}
References Slic3r::DoubleSlider::epsilon(), m_is_wipe_tower, and m_values.
Referenced by edit_extruder_sequence(), jump_to_value(), and SetTicksValues().
get_tick_near_point()
int Slic3r::DoubleSlider::Control::get_tick_near_point (const wxPoint & pt) private
{
    for (auto tick : m_ticks.ticks) {
        const wxCoord pos = get_position_from_value(tick.tick);
        if (is_horizontal()) {
            if (pos - 4 <= pt.x && pt.x <= pos + 4)
                return tick.tick;
        }
        else {
            if (pos - 4 <= pt.y && pt.y <= pos + 4)
                return tick.tick;
        }
    }
    return -1;
}
References get_position_from_value(), is_horizontal(), m_ticks, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by draw_tick_on_mouse_position(), draw_ticks(), move_current_thumb_to_pos(), and OnMotion().
get_tooltip()
wxString Slic3r::DoubleSlider::Control::get_tooltip (int tick = -1) private
{
    if (m_focus == fiNone)
        return "";
    if (m_focus == fiOneLayerIcon)
        return _L("One layer mode");
    if (m_focus == fiRevertIcon)
        return _L("Discard all custom changes");
    if (m_focus == fiCogIcon)
    {
        if (m_draw_mode == dmSequentialGCodeView)
            return _L("Jump to move") + " (Shift + G)";
        else
            return m_mode == MultiAsSingle ?
            GUI::from_u8((boost::format(_u8L("Jump to height %s\n"
                                               "Set ruler mode\n"
                                               "or Set extruder sequence for the entire print")) % "(Shift + G)").str()) :
            GUI::from_u8((boost::format(_u8L("Jump to height %s\n"
                                                "or Set ruler mode")) % "(Shift + G)").str());
    }
    if (m_focus == fiColorBand)
        return m_mode != SingleExtruder ? "" :
               _L("Edit current color - Right click the colored slider segment");
    if (m_focus == fiSmartWipeTower)
        return _L("This is wipe tower layer");
    if (m_draw_mode == dmSlaPrint)
        return ""; // no drawn ticks and no tooltips for them in SlaPrinting mode
    wxString tooltip;
    const auto tick_code_it = m_ticks.ticks.find(TickCode{tick});
    if (tick_code_it == m_ticks.ticks.end() && m_focus == fiActionIcon)    // tick doesn't exist
    {
        if (m_draw_mode == dmSequentialFffPrint)
            return  (_L("The sequential print is on.\n"
                        "It's impossible to apply any custom G-code for objects printing sequentually.") + "\n");
        // Show mode as a first string of tooltop
        tooltip = "    " + _L("Print mode") + ": ";
        tooltip += (m_mode == SingleExtruder ? SingleExtruderMode :
                    m_mode == MultiAsSingle  ? MultiAsSingleMode  :
                                               MultiExtruderMode );
        tooltip += "\n\n";
        /* Note: just on OSX!!!
         * Right click event causes a little scrolling.
         * So, as a workaround we use Ctrl+LeftMouseClick instead of RightMouseClick
         * Show this information in tooltip
         * */
        // Show list of actions with new tick
        tooltip += ( m_mode == MultiAsSingle                                ?
                  _L("Add extruder change - Left click")                    :
                     m_mode == SingleExtruder                               ?
                  _L("Add color change - Left click for predefined color or "
                     "Shift + Left click for custom color selection")       :
                  _L("Add color change - Left click")  ) + " " +
                  _L("or press \"+\" key") + "\n" + (
                     is_osx ?
                  _L("Add another code - Ctrl + Left click") :
                  _L("Add another code - Right click") );
    }
    if (tick_code_it != m_ticks.ticks.end())                                    // tick exists
    {
        if (m_draw_mode == dmSequentialFffPrint)
            return   _L("The sequential print is on.\n"
                        "It's impossible to apply any custom G-code for objects printing sequentually.\n"
                        "This code won't be processed during G-code generation.");
        // Show custom Gcode as a first string of tooltop
        std::string space = "   ";
        tooltip = space;
        auto format_gcode = [space](std::string gcode) {
            // when the tooltip is too long, it starts to flicker, see: https://github.com/prusa3d/PrusaSlicer/issues/7368
            // so we limit the number of lines shown
            std::vector<std::string> lines;
            boost::split(lines, gcode, boost::is_any_of("\n"), boost::token_compress_off);
            static const size_t MAX_LINES = 10;
            if (lines.size() > MAX_LINES) {
                gcode = lines.front() + '\n';
                for (size_t i = 1; i < MAX_LINES; ++i) {
                    gcode += lines[i] + '\n';
                }
                gcode += "[" + into_u8(_L("continue")) + "]\n";
            }
            boost::replace_all(gcode, "\n", "\n" + space);
            return gcode;
        };
        tooltip +=
          tick_code_it->type == ColorChange ?
            (m_mode == SingleExtruder ?
                  format_wxstr(_L("Color change (\"%1%\")"), gcode(ColorChange)) :
                    format_wxstr(_L("Color change (\"%1%\") for Extruder %2%"), gcode(ColorChange), tick_code_it->extruder)) :
              tick_code_it->type == PausePrint ?
                  format_wxstr(_L("Pause print (\"%1%\")"), gcode(PausePrint)) :
              tick_code_it->type == Template ?
                  format_wxstr(_L("Custom template (\"%1%\")"), gcode(Template)) :
                tick_code_it->type == ToolChange ?
                    format_wxstr(_L("Extruder (tool) is changed to Extruder \"%1%\""), tick_code_it->extruder) :
                    from_u8(format_gcode(tick_code_it->extra));// tick_code_it->type == Custom
        // If tick is marked as a conflict (exclamation icon),
        // we should to explain why
        ConflictType conflict = m_ticks.is_conflict_tick(*tick_code_it, m_mode, m_only_extruder, m_values[tick]);
        if (conflict != ctNone)
            tooltip += "\n\n" + _L("Note") + "! ";
        if (conflict == ctModeConflict)
            tooltip +=  _L("G-code associated to this tick mark is in a conflict with print mode.\n"
                           "Editing it will cause changes of Slider data.");
        else if (conflict == ctMeaninglessColorChange)
            tooltip +=  _L("There is a color change for extruder that won't be used till the end of print job.\n"
                           "This code won't be processed during G-code generation.");
        else if (conflict == ctMeaninglessToolChange)
            tooltip +=  _L("There is an extruder change set to the same extruder.\n"
                           "This code won't be processed during G-code generation.");
        else if (conflict == ctRedundant)
            tooltip +=  _L("There is a color change for extruder that has not been used before.\n"
                           "Check your settings to avoid redundant color changes.");
        // Show list of actions with existing tick
        if (m_focus == fiActionIcon)
        tooltip += "\n\n" + _L("Delete tick mark - Left click or press \"-\" key") + "\n" + (
                      is_osx ?
                   _L("Edit tick mark - Ctrl + Left click") :
                   _L("Edit tick mark - Right click") );
    }
    return tooltip;
}
References _L, _u8L, Slic3r::CustomGCode::ColorChange, Slic3r::DoubleSlider::ctMeaninglessColorChange, Slic3r::DoubleSlider::ctMeaninglessToolChange, Slic3r::DoubleSlider::ctModeConflict, Slic3r::DoubleSlider::ctNone, Slic3r::DoubleSlider::ctRedundant, Slic3r::DoubleSlider::dmSequentialFffPrint, Slic3r::DoubleSlider::dmSequentialGCodeView, Slic3r::DoubleSlider::dmSlaPrint, Slic3r::DoubleSlider::fiActionIcon, Slic3r::DoubleSlider::fiCogIcon, Slic3r::DoubleSlider::fiColorBand, Slic3r::DoubleSlider::fiNone, Slic3r::DoubleSlider::fiOneLayerIcon, Slic3r::DoubleSlider::fiRevertIcon, Slic3r::DoubleSlider::fiSmartWipeTower, Slic3r::GUI::from_u8(), Slic3r::DoubleSlider::gcode(), Slic3r::DoubleSlider::TickCodeInfo::is_conflict_tick(), is_osx, m_draw_mode, m_focus, m_mode, m_only_extruder, m_ticks, m_values, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::MultiAsSingleMode, Slic3r::CustomGCode::MultiExtruderMode, Slic3r::CustomGCode::PausePrint, Slic3r::CustomGCode::SingleExtruder, Slic3r::CustomGCode::SingleExtruderMode, Slic3r::CustomGCode::Template, Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
Referenced by OnMotion().
get_value_from_position() [1/2]
int Slic3r::DoubleSlider::Control::get_value_from_position (const wxCoord x, const wxCoord y) private
{
    const int height = get_size().y;
    const double step = get_scroll_step();
    if (is_horizontal())
        return int(double(x - SLIDER_MARGIN) / step + 0.5);
    return int(m_min_value + double(height - SLIDER_MARGIN - y) / step + 0.5);
}
References get_scroll_step(), get_size(), is_horizontal(), m_min_value, and SLIDER_MARGIN.
Referenced by draw_tick_on_mouse_position(), get_edited_tick_for_position(), move_current_thumb_to_pos(), and OnMotion().
get_value_from_position() [2/2]
int Slic3r::DoubleSlider::Control::get_value_from_position (const wxPoint pos) inline private
{ return get_value_from_position(pos.x, pos.y); }
References get_value_from_position().
Referenced by get_value_from_position().
GetActiveValue()
int Slic3r::DoubleSlider::Control::GetActiveValue () const
{
    return m_selection == ssLower ?
    m_lower_value : m_selection == ssHigher ?
                m_higher_value : -1;
}
References m_higher_value, m_lower_value, m_selection, Slic3r::DoubleSlider::ssHigher, and Slic3r::DoubleSlider::ssLower.
GetHigherValue()
int Slic3r::DoubleSlider::Control::GetHigherValue () const inline
{ return m_higher_value; }
References m_higher_value.
Referenced by Slic3r::GUI::Preview::on_layers_slider_scroll_changed(), and Slic3r::GUI::Preview::update_layers_slider_from_canvas().
GetHigherValueD()
double Slic3r::DoubleSlider::Control::GetHigherValueD () inline
{ return get_double_value(ssHigher); }
References get_double_value(), and Slic3r::DoubleSlider::ssHigher.
Referenced by Slic3r::GUI::Preview::on_layers_slider_scroll_changed(), Slic3r::GUI::Preview::on_moves_slider_scroll_changed(), and Slic3r::GUI::Preview::update_layers_slider().
GetLowerValue()
int Slic3r::DoubleSlider::Control::GetLowerValue () const inline
{ return m_lower_value; }
References m_lower_value.
Referenced by Slic3r::GUI::Preview::on_layers_slider_scroll_changed().
GetLowerValueD()
double Slic3r::DoubleSlider::Control::GetLowerValueD () inline
{ return get_double_value(ssLower); }
References get_double_value(), and Slic3r::DoubleSlider::ssLower.
Referenced by Slic3r::GUI::Preview::on_layers_slider_scroll_changed(), Slic3r::GUI::Preview::on_moves_slider_scroll_changed(), and Slic3r::GUI::Preview::update_layers_slider().
GetManipulationMode()
Mode Slic3r::DoubleSlider::Control::GetManipulationMode () const inline
{ return m_mode; }
References m_mode.
GetMaxValue()
int Slic3r::DoubleSlider::Control::GetMaxValue () const inline
{ return m_max_value; }
References m_max_value.
Referenced by Slic3r::GUI::Preview::set_layers_slider_values_range(), and Slic3r::GUI::Preview::update_layers_slider().
GetMaxValueD()
double Slic3r::DoubleSlider::Control::GetMaxValueD () inline
{ return m_values.empty() ? 0. : m_values[m_max_value]; }
References m_max_value, and m_values.
Referenced by Slic3r::GUI::Preview::update_layers_slider().
GetMinValue()
int Slic3r::DoubleSlider::Control::GetMinValue () const inline
{ return m_min_value; }
References m_min_value.
Referenced by Slic3r::GUI::Preview::set_layers_slider_values_range(), and Slic3r::GUI::Preview::update_layers_slider().
GetMinValueD()
double Slic3r::DoubleSlider::Control::GetMinValueD () inline
{ return m_values.empty() ? 0. : m_values[m_min_value]; }
References m_min_value, and m_values.
GetTicksValues()
Info Slic3r::DoubleSlider::Control::GetTicksValues () const
{
    Info custom_gcode_per_print_z;
    std::vector<CustomGCode::Item>& values = custom_gcode_per_print_z.gcodes;
    const int val_size = m_values.size();
    if (!m_values.empty())
        for (const TickCode& tick : m_ticks.ticks) {
            if (tick.tick > val_size)
                break;
            values.emplace_back(CustomGCode::Item{ m_values[tick.tick], tick.type, tick.extruder, tick.color, tick.extra });
        }
    if (m_force_mode_apply)
        custom_gcode_per_print_z.mode = m_mode;
    return custom_gcode_per_print_z;
}
References Slic3r::CustomGCode::Info::gcodes, m_force_mode_apply, m_mode, m_ticks, m_values, Slic3r::CustomGCode::Info::mode, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by Slic3r::GUI::Preview::create_layers_slider_sizer().
is_full_span()
bool Slic3r::DoubleSlider::Control::is_full_span () const inline
{ return this->is_lower_at_min() && this->is_higher_at_max(); }
References is_higher_at_max(), and is_lower_at_min().
is_higher_at_max()
bool Slic3r::DoubleSlider::Control::is_higher_at_max () const inline
{ return m_higher_value == m_max_value; }
References m_higher_value, and m_max_value.
Referenced by is_full_span(), and Slic3r::GUI::Preview::update_layers_slider().
is_horizontal()
bool Slic3r::DoubleSlider::Control::is_horizontal () const inline
{ return m_style == wxSL_HORIZONTAL; }
References m_style.
Referenced by add_current_tick(), draw_action_icon(), draw_cog_icon(), draw_colored_band(), draw_info_line_with_icon(), draw_one_layer_icon(), draw_revert_icon(), draw_ruler(), draw_scroll_line(), draw_thumb(), draw_thumbs(), draw_tick_on_mouse_position(), draw_tick_text(), draw_ticks(), draw_ticks_pair(), get_colored_band_rect(), get_lower_and_higher_position(), get_min_size(), get_position_from_value(), get_size(), get_tick_near_point(), get_value_from_position(), move_current_thumb(), OnKeyDown(), OnWheel(), and update_thumb_rect().
is_lower_at_min()
bool Slic3r::DoubleSlider::Control::is_lower_at_min () const inline
{ return m_lower_value == m_min_value; }
References m_lower_value, and m_min_value.
Referenced by is_full_span(), and Slic3r::GUI::Preview::update_layers_slider().
is_lower_thumb_editable()
bool Slic3r::DoubleSlider::Control::is_lower_thumb_editable () protected
{
    if (m_draw_mode == dmSequentialGCodeView)
        return Slic3r::GUI::get_app_config()->get("seq_top_layer_only") == "0";
    return true;
}
References Slic3r::DoubleSlider::dmSequentialGCodeView, Slic3r::AppConfig::get(), Slic3r::GUI::get_app_config(), and m_draw_mode.
Referenced by detect_selected_slider(), OnKeyDown(), and OnWheel().
is_one_layer()
bool Slic3r::DoubleSlider::Control::is_one_layer () const inline
{ return m_is_one_layer; }
References m_is_one_layer.
Referenced by Slic3r::GUI::Preview::update_layers_slider_from_canvas().
is_point_in_rect()
bool Slic3r::DoubleSlider::Control::is_point_in_rect (const wxPoint & pt, const wxRect & rect) private
{
    return  rect.GetLeft() <= pt.x && pt.x <= rect.GetRight() &&
            rect.GetTop()  <= pt.y && pt.y <= rect.GetBottom();
}
Referenced by detect_selected_slider(), OnLeftDown(), OnMotion(), and OnRightDown().
is_rendering_as_disabled()
bool Slic3r::DoubleSlider::Control::is_rendering_as_disabled () const inline
{ return m_render_as_disabled; }
References m_render_as_disabled.
Referenced by Slic3r::GUI::Preview::enable_moves_slider().
is_wipe_tower_layer()
bool Slic3r::DoubleSlider::Control::is_wipe_tower_layer (int tick) const protected
{
    if (!m_is_wipe_tower || tick >= (int)m_values.size())
        return false;
    if (tick == 0 || (tick == (int)m_values.size() - 1 && m_values[tick] > m_values[tick - 1]))
        return false;
    if ((m_values[tick - 1] == m_values[tick + 1] && m_values[tick] < m_values[tick + 1]) ||
        (tick > 0 && m_values[tick] < m_values[tick - 1]) ) // if there is just one wiping on the layer
        return true;
    return false;
}
References m_is_wipe_tower, and m_values.
Referenced by draw_action_icon(), draw_tick_text(), get_label(), and OnMotion().
IsNewPrint()
bool Slic3r::DoubleSlider::Control::IsNewPrint ()
{
    if (GUI::wxGetApp().plater()->printer_technology() == ptSLA)
        return false;
    const Print& print = GUI::wxGetApp().plater()->fff_print();
    std::string idxs;
    for (auto object : print.objects())
        idxs += std::to_string(object->id().id) + "_";
    if (idxs == m_print_obj_idxs)
        return false;
    m_print_obj_idxs = idxs;
    return true;
}
References m_print_obj_idxs, Slic3r::Print::objects(), Slic3r::printer_technology(), and Slic3r::ptSLA.
Referenced by Slic3r::GUI::Preview::update_layers_slider().
jump_to_value()
void Slic3r::DoubleSlider::Control::jump_to_value ()
{
    double value = get_value_to_jump(m_values[m_selection == ssLower ? m_lower_value : m_higher_value],
                                     m_values[m_min_value], m_values[m_max_value], m_draw_mode);
    if (value < 0.0)
        return;
    int tick_value = get_tick_from_value(value);
    if (m_selection == ssLower)
        SetLowerValue(tick_value);
    else
        SetHigherValue(tick_value);
}
References get_tick_from_value(), Slic3r::DoubleSlider::get_value_to_jump(), m_draw_mode, m_higher_value, m_lower_value, m_max_value, m_min_value, m_selection, m_values, SetHigherValue(), SetLowerValue(), and Slic3r::DoubleSlider::ssLower.
Referenced by OnChar(), and show_cog_icon_context_menu().
move_current_thumb()
void Slic3r::DoubleSlider::Control::move_current_thumb (const bool condition) protected
{
//     m_is_one_layer = wxGetKeyState(WXK_CONTROL);
    int delta = condition ? -1 : 1;
    if (is_horizontal())
        delta *= -1;
    // accelerators
    int accelerator = 0;
    if (wxGetKeyState(WXK_SHIFT))
        accelerator += 5;
    if (wxGetKeyState(WXK_CONTROL))
        accelerator += 5;
    if (accelerator > 0)
        delta *= accelerator;
    if (m_selection == ssUndef)
        m_selection = ssHigher;
    if (m_selection == ssLower) {
        m_lower_value -= delta;
        correct_lower_value();
    }
    else if (m_selection == ssHigher) {
        m_higher_value -= delta;
        correct_higher_value();
    }
    Refresh();
    Update();
    wxCommandEvent e(wxEVT_SCROLL_CHANGED);
    e.SetEventObject(this);
    ProcessWindowEvent(e);
}
References correct_higher_value(), correct_lower_value(), is_horizontal(), m_higher_value, m_lower_value, m_selection, Slic3r::DoubleSlider::ssHigher, Slic3r::DoubleSlider::ssLower, and Slic3r::DoubleSlider::ssUndef.
Referenced by OnKeyDown(), and OnWheel().
move_current_thumb_to_pos()
void Slic3r::DoubleSlider::Control::move_current_thumb_to_pos (wxPoint pos)
{
    const int tick_val = get_tick_near_point(pos);
    const int mouse_val = tick_val >= 0 && m_draw_mode == dmRegular ? tick_val :
        get_value_from_position(pos);
    if (mouse_val >= 0) {
        if (m_selection == ssLower) {
            SetLowerValue(mouse_val);
            correct_lower_value();
        }
        else { // even m_selection is ssUndef, upper thumb should be selected
            SetHigherValue(mouse_val);
            correct_higher_value();
        }
    }
}
References correct_higher_value(), correct_lower_value(), Slic3r::DoubleSlider::dmRegular, get_tick_near_point(), get_value_from_position(), m_draw_mode, m_selection, SetHigherValue(), SetLowerValue(), and Slic3r::DoubleSlider::ssLower.
Referenced by OnLeftUp().
msw_rescale()
void Slic3r::DoubleSlider::Control::msw_rescale ()
{
    m_font = GUI::wxGetApp().normal_font();
    m_thumb_size = m_bmp_thumb_lower.GetSize();
    m_tick_icon_dim     = m_bmp_add_tick_on.GetWidth();
    m_lock_icon_dim     = m_bmp_one_layer_lock_on.GetWidth();
    m_revert_icon_dim   = m_bmp_revert.GetWidth();
    m_cog_icon_dim      = m_bmp_cog.GetWidth();
    SLIDER_MARGIN = 4 + GUI::wxGetApp().em_unit();
    SetMinSize(get_min_size());
    GetParent()->Layout();
    m_ruler.update_dpi();
    m_ruler.update(m_layers_values.empty() ? m_values : m_layers_values, get_scroll_step());
}
References get_min_size(), get_scroll_step(), ScalableBitmap::GetSize(), ScalableBitmap::GetWidth(), m_bmp_add_tick_on, m_bmp_cog, m_bmp_one_layer_lock_on, m_bmp_revert, m_bmp_thumb_lower, m_cog_icon_dim, m_font, m_layers_values, m_lock_icon_dim, m_revert_icon_dim, m_ruler, m_thumb_size, m_tick_icon_dim, m_values, SLIDER_MARGIN, Slic3r::DoubleSlider::Control::Ruler::update(), and Slic3r::DoubleSlider::Control::Ruler::update_dpi().
Referenced by Slic3r::GUI::Preview::msw_rescale().
OnChar()
void Slic3r::DoubleSlider::Control::OnChar (wxKeyEvent & event)
{
    const int key = event.GetKeyCode();
    if (m_draw_mode != dmSequentialGCodeView) {
        if (key == '+' && !m_ticks.suppressed_plus()) {
            add_current_tick(true);
            m_ticks.suppress_plus(false);
        }
        else if (key == '-' && !m_ticks.suppressed_minus()) {
            delete_current_tick();
            m_ticks.suppress_minus(false);
        }
    }
    if (key == 'G')
        jump_to_value();
}
References add_current_tick(), delete_current_tick(), Slic3r::DoubleSlider::dmSequentialGCodeView, jump_to_value(), m_draw_mode, m_ticks, Slic3r::DoubleSlider::TickCodeInfo::suppress_minus(), Slic3r::DoubleSlider::TickCodeInfo::suppress_plus(), Slic3r::DoubleSlider::TickCodeInfo::suppressed_minus(), and Slic3r::DoubleSlider::TickCodeInfo::suppressed_plus().
Referenced by Control(), Slic3r::GUI::Preview::edit_layers_slider(), and Slic3r::GUI::Preview::jump_layers_slider().
OnEnterWin()
void Slic3r::DoubleSlider::Control::OnEnterWin (wxMouseEvent & event) inline
{ enter_window(event, true); }
References enter_window().
Referenced by Control().
OnKeyDown()
void Slic3r::DoubleSlider::Control::OnKeyDown (wxKeyEvent & event)
{
    const int key = event.GetKeyCode();
    if (m_draw_mode != dmSequentialGCodeView && key == WXK_NUMPAD_ADD) {
        // OnChar() is called immediately after OnKeyDown(), which can cause call of add_tick() twice.
        // To avoid this case we should suppress second add_tick() call.
        m_ticks.suppress_plus(true);
        add_current_tick(true);
    }
    else if (m_draw_mode != dmSequentialGCodeView && (key == WXK_NUMPAD_SUBTRACT || key == WXK_DELETE || key == WXK_BACK)) {
        // OnChar() is called immediately after OnKeyDown(), which can cause call of delete_tick() twice.
        // To avoid this case we should suppress second delete_tick() call.
        m_ticks.suppress_minus(true);
        delete_current_tick();
    }
    else if (m_draw_mode != dmSequentialGCodeView && event.GetKeyCode() == WXK_SHIFT)
        UseDefaultColors(false);
    else if (is_horizontal()) {
        if (m_is_focused) {
            if (key == WXK_LEFT || key == WXK_RIGHT)
                move_current_thumb(key == WXK_LEFT);
            else if (key == WXK_UP || key == WXK_DOWN) {
                if (key == WXK_DOWN)
                    m_selection = ssHigher;
                else if (key == WXK_UP && is_lower_thumb_editable())
                    m_selection = ssLower;
                Refresh();
            }
        }
        else {
            if (key == WXK_LEFT || key == WXK_RIGHT)
                move_current_thumb(key == WXK_LEFT);
        }
    }
    else {
        if (m_is_focused) {
            if (key == WXK_LEFT || key == WXK_RIGHT) {
                if (key == WXK_LEFT)
                    m_selection = ssHigher;
                else if (key == WXK_RIGHT && is_lower_thumb_editable())
                    m_selection = ssLower;
                Refresh();
            }
            else if (key == WXK_UP || key == WXK_DOWN)
                move_current_thumb(key == WXK_UP);
        }
        else {
            if (key == WXK_UP || key == WXK_DOWN)
                move_current_thumb(key == WXK_UP);
        }
    }
    event.Skip(); // !Needed to have EVT_CHAR generated as well
}
References add_current_tick(), delete_current_tick(), Slic3r::DoubleSlider::dmSequentialGCodeView, is_horizontal(), is_lower_thumb_editable(), m_draw_mode, m_is_focused, m_selection, m_ticks, move_current_thumb(), Slic3r::DoubleSlider::ssHigher, Slic3r::DoubleSlider::ssLower, Slic3r::DoubleSlider::TickCodeInfo::suppress_minus(), Slic3r::DoubleSlider::TickCodeInfo::suppress_plus(), and UseDefaultColors().
Referenced by Control(), Slic3r::GUI::Preview::move_layers_slider(), and Slic3r::GUI::Preview::move_moves_slider().
OnKeyUp()
void Slic3r::DoubleSlider::Control::OnKeyUp (wxKeyEvent & event)
{
    if (event.GetKeyCode() == WXK_CONTROL)
        m_is_one_layer = false;
    else if (event.GetKeyCode() == WXK_SHIFT)
        UseDefaultColors(true);
    Refresh();
    Update();
    event.Skip();
}
References m_is_one_layer, and UseDefaultColors().
Referenced by Control().
OnLeaveWin()
void Slic3r::DoubleSlider::Control::OnLeaveWin (wxMouseEvent & event) inline
{ enter_window(event, false); }
References enter_window().
Referenced by Control().
OnLeftDown()
void Slic3r::DoubleSlider::Control::OnLeftDown (wxMouseEvent & event)
{
    if (HasCapture())
        return;
    this->CaptureMouse();
    m_is_left_down = true;
    m_mouse = maNone;
    wxPoint pos = event.GetLogicalPosition(wxClientDC(this));
    if (is_point_in_rect(pos, m_rect_one_layer_icon))
        m_mouse = maOneLayerIconClick;
    else if (is_point_in_rect(pos, m_rect_cog_icon))
        m_mouse = maCogIconClick;
    else if (m_draw_mode == dmRegular) {
        if (is_point_in_rect(pos, m_rect_tick_action)) {
            auto it = m_ticks.ticks.find(TickCode{ m_selection == ssLower ? m_lower_value : m_higher_value });
            m_mouse = it == m_ticks.ticks.end() ? maAddTick : maDeleteTick;
        }
        else if (is_point_in_rect(pos, m_rect_revert_icon))
            m_mouse = maRevertIconClick;
    }
    if (m_mouse == maNone)
        detect_selected_slider(pos);
    event.Skip();
}
References detect_selected_slider(), Slic3r::DoubleSlider::dmRegular, is_point_in_rect(), m_draw_mode, m_higher_value, m_is_left_down, m_lower_value, m_mouse, m_rect_cog_icon, m_rect_one_layer_icon, m_rect_revert_icon, m_rect_tick_action, m_selection, m_ticks, Slic3r::DoubleSlider::maAddTick, Slic3r::DoubleSlider::maCogIconClick, Slic3r::DoubleSlider::maDeleteTick, Slic3r::DoubleSlider::maNone, Slic3r::DoubleSlider::maOneLayerIconClick, Slic3r::DoubleSlider::maRevertIconClick, Slic3r::DoubleSlider::ssLower, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by Control().
OnLeftUp()
void Slic3r::DoubleSlider::Control::OnLeftUp (wxMouseEvent & event)
{
    if (!HasCapture())
        return;
    this->ReleaseMouse();
    m_is_left_down = false;
    switch (m_mouse) {
    case maNone :
        move_current_thumb_to_pos(event.GetLogicalPosition(wxClientDC(this)));
        break;
    case maDeleteTick :
        delete_current_tick();
        break;
    case maAddTick :
        add_current_tick();
        break;
    case maCogIconClick :
        show_cog_icon_context_menu();
        break;
    case maOneLayerIconClick:
        switch_one_layer_mode();
        break;
    case maRevertIconClick:
        discard_all_thicks();
        break;
    default :
        break;
    }
    Refresh();
    Update();
    event.Skip();
    wxCommandEvent e(wxEVT_SCROLL_CHANGED);
    e.SetEventObject(this);
    ProcessWindowEvent(e);
}
References add_current_tick(), delete_current_tick(), discard_all_thicks(), m_is_left_down, m_mouse, Slic3r::DoubleSlider::maAddTick, Slic3r::DoubleSlider::maCogIconClick, Slic3r::DoubleSlider::maDeleteTick, Slic3r::DoubleSlider::maNone, Slic3r::DoubleSlider::maOneLayerIconClick, Slic3r::DoubleSlider::maRevertIconClick, move_current_thumb_to_pos(), show_cog_icon_context_menu(), and switch_one_layer_mode().
Referenced by Control().
OnMotion()
void Slic3r::DoubleSlider::Control::OnMotion (wxMouseEvent & event)
{
    bool action = false;
    const wxPoint pos = event.GetLogicalPosition(wxClientDC(this));
    int tick = -1;
    if (!m_is_left_down && !m_is_right_down) {
        if (is_point_in_rect(pos, m_rect_one_layer_icon))
            m_focus = fiOneLayerIcon;
        else if (is_point_in_rect(pos, m_rect_tick_action)) {
            m_focus = fiActionIcon;
            tick = m_selection == ssLower ? m_lower_value : m_higher_value;
        }
        else if (!m_ticks.empty() && is_point_in_rect(pos, m_rect_revert_icon))
            m_focus = fiRevertIcon;
        else if (is_point_in_rect(pos, m_rect_cog_icon))
            m_focus = fiCogIcon;
        else if (m_mode == SingleExtruder && is_point_in_rect(pos, get_colored_band_rect()) &&
                 get_edited_tick_for_position(pos) >= 0 )
            m_focus = fiColorBand;
        else if (is_point_in_rect(pos, m_rect_lower_thumb))
            m_focus = fiLowerThumb;
        else if (is_point_in_rect(pos, m_rect_higher_thumb))
            m_focus = fiHigherThumb;
        else {
            tick = get_tick_near_point(pos);
            if (tick < 0 && m_is_wipe_tower) {
                tick = get_value_from_position(pos);
                m_focus = tick > 0 && is_wipe_tower_layer(tick) && (tick == m_lower_value || tick == m_higher_value) ?
                          fiSmartWipeTower : fiTick;
            }
            else
                m_focus = fiTick;
        }
        m_moving_pos = pos;
    }
    else if (m_is_left_down || m_is_right_down) {
        if (m_selection == ssLower) {
            int current_value = m_lower_value;
            m_lower_value = get_value_from_position(pos.x, pos.y);
            correct_lower_value();
            action = (current_value != m_lower_value);
        }
        else if (m_selection == ssHigher) {
            int current_value = m_higher_value;
            m_higher_value = get_value_from_position(pos.x, pos.y);
            correct_higher_value();
            action = (current_value != m_higher_value);
        }
        m_moving_pos = wxDefaultPosition;
    }
    Refresh();
    Update();
    event.Skip();
    // Set tooltips with information for each icon
    if (GUI::wxGetApp().is_editor())
        this->SetToolTip(get_tooltip(tick));
    if (action) {
        wxCommandEvent e(wxEVT_SCROLL_CHANGED);
        e.SetEventObject(this);
        e.SetString("moving");
        ProcessWindowEvent(e);
    }
}
References correct_higher_value(), correct_lower_value(), Slic3r::DoubleSlider::TickCodeInfo::empty(), Slic3r::DoubleSlider::fiActionIcon, Slic3r::DoubleSlider::fiCogIcon, Slic3r::DoubleSlider::fiColorBand, Slic3r::DoubleSlider::fiHigherThumb, Slic3r::DoubleSlider::fiLowerThumb, Slic3r::DoubleSlider::fiOneLayerIcon, Slic3r::DoubleSlider::fiRevertIcon, Slic3r::DoubleSlider::fiSmartWipeTower, Slic3r::DoubleSlider::fiTick, get_colored_band_rect(), get_edited_tick_for_position(), get_tick_near_point(), get_tooltip(), get_value_from_position(), is_point_in_rect(), is_wipe_tower_layer(), m_focus, m_higher_value, m_is_left_down, m_is_right_down, m_is_wipe_tower, m_lower_value, m_mode, m_moving_pos, m_rect_cog_icon, m_rect_higher_thumb, m_rect_lower_thumb, m_rect_one_layer_icon, m_rect_revert_icon, m_rect_tick_action, m_selection, m_ticks, Slic3r::CustomGCode::SingleExtruder, Slic3r::DoubleSlider::ssHigher, and Slic3r::DoubleSlider::ssLower.
Referenced by Control().
OnPaint()
void Slic3r::DoubleSlider::Control::OnPaint (wxPaintEvent &) inline
{ render(); }
References render().
Referenced by Control().
OnRightDown()
void Slic3r::DoubleSlider::Control::OnRightDown (wxMouseEvent & event)
{
    if (HasCapture() || m_is_left_down)
        return;
    this->CaptureMouse();
    const wxPoint pos = event.GetLogicalPosition(wxClientDC(this));
    m_mouse = maNone;
    if (m_draw_mode == dmRegular) {
        if (is_point_in_rect(pos, m_rect_tick_action)) {
            const int tick = m_selection == ssLower ? m_lower_value : m_higher_value;
            m_mouse = m_ticks.ticks.find(TickCode{ tick }) == m_ticks.ticks.end() ?
                             maAddMenu : maEditMenu;
        }
        else if (m_mode == SingleExtruder   && !detect_selected_slider(pos) && is_point_in_rect(pos, get_colored_band_rect()))
            m_mouse = maForceColorEdit;
        else if (m_mode == MultiAsSingle    && is_point_in_rect(pos, m_rect_cog_icon))
            m_mouse = maCogIconMenu;
    }
    if (m_mouse != maNone || !detect_selected_slider(pos))
        return;
    if (m_selection == ssLower)
        m_higher_value = m_lower_value;
    else
        m_lower_value = m_higher_value;
    // set slider to "one layer" mode
    m_is_right_down = m_is_one_layer = true;
    Refresh();
    Update();
    event.Skip();
}
References detect_selected_slider(), Slic3r::DoubleSlider::dmRegular, get_colored_band_rect(), is_point_in_rect(), m_draw_mode, m_higher_value, m_is_left_down, m_is_one_layer, m_is_right_down, m_lower_value, m_mode, m_mouse, m_rect_cog_icon, m_rect_tick_action, m_selection, m_ticks, Slic3r::DoubleSlider::maAddMenu, Slic3r::DoubleSlider::maCogIconMenu, Slic3r::DoubleSlider::maEditMenu, Slic3r::DoubleSlider::maForceColorEdit, Slic3r::DoubleSlider::maNone, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::SingleExtruder, Slic3r::DoubleSlider::ssLower, and Slic3r::DoubleSlider::TickCodeInfo::ticks.
Referenced by Control().
OnRightUp()
void Slic3r::DoubleSlider::Control::OnRightUp (wxMouseEvent & event)
{
    if (!HasCapture() || m_is_left_down)
        return;
    this->ReleaseMouse();
    m_is_right_down = m_is_one_layer = false;
    if (m_mouse == maForceColorEdit) {
        wxPoint pos = event.GetLogicalPosition(wxClientDC(this));
        int edited_tick = get_edited_tick_for_position(pos);
        if (edited_tick >= 0)
            edit_tick(edited_tick);
    }
    else if (m_mouse == maAddMenu)
        show_add_context_menu();
    else if (m_mouse == maEditMenu)
        show_edit_context_menu();
    else if (m_mouse == maCogIconMenu)
        show_cog_icon_context_menu();
    Refresh();
    Update();
    event.Skip();
}
References edit_tick(), get_edited_tick_for_position(), m_is_left_down, m_is_one_layer, m_is_right_down, m_mouse, Slic3r::DoubleSlider::maAddMenu, Slic3r::DoubleSlider::maCogIconMenu, Slic3r::DoubleSlider::maEditMenu, Slic3r::DoubleSlider::maForceColorEdit, show_add_context_menu(), show_cog_icon_context_menu(), and show_edit_context_menu().
Referenced by Control().
OnWheel()
void Slic3r::DoubleSlider::Control::OnWheel (wxMouseEvent & event)
{
    // Set nearest to the mouse thumb as a selected, if there is not selected thumb
    if (m_selection == ssUndef) {
        const wxPoint& pt = event.GetLogicalPosition(wxClientDC(this));
        if (is_horizontal())
            m_selection = abs(pt.x - m_rect_lower_thumb.GetRight()) <=
                          abs(pt.x - m_rect_higher_thumb.GetLeft()) ?
                          ssLower : ssHigher;
        else
            m_selection = abs(pt.y - m_rect_lower_thumb.GetTop()) <=
                          abs(pt.y - m_rect_higher_thumb.GetBottom()) ?
                          ssLower : ssHigher;
    }
    if (m_selection == ssLower && !is_lower_thumb_editable())
        m_selection = ssUndef;
    move_current_thumb((m_draw_mode == dmSequentialGCodeView) ? event.GetWheelRotation() < 0 : event.GetWheelRotation() > 0);
}
References Slic3r::DoubleSlider::dmSequentialGCodeView, is_horizontal(), is_lower_thumb_editable(), m_draw_mode, m_rect_higher_thumb, m_rect_lower_thumb, m_selection, move_current_thumb(), Slic3r::DoubleSlider::ssHigher, Slic3r::DoubleSlider::ssLower, and Slic3r::DoubleSlider::ssUndef.
Referenced by Control().
post_ticks_changed_event()
void Slic3r::DoubleSlider::Control::post_ticks_changed_event (Type type = Custom) private
{
//    m_force_mode_apply = type != ToolChange; // It looks like this condition is no needed now. Leave it for the testing
    wxPostEvent(this->GetParent(), wxCommandEvent(wxCUSTOMEVT_TICKSCHANGED));
}
Referenced by add_code_as_tick(), check_ticks_changed_event(), delete_current_tick(), discard_all_thicks(), edit_extruder_sequence(), edit_tick(), and SetTicksValues().
render()
void Slic3r::DoubleSlider::Control::render () protected
{
#ifdef _WIN32
    GUI::wxGetApp().UpdateDarkUI(this);
#else
    SetBackgroundColour(GetParent()->GetBackgroundColour());
#endif // _WIN32
    wxPaintDC dc(this);
    dc.SetFont(m_font);
    draw_focus_rect(dc);
    const wxCoord lower_pos = get_position_from_value(m_lower_value);
    const wxCoord higher_pos = get_position_from_value(m_higher_value);
    // draw colored band on the background of a scroll line
    // and only in a case of no-empty m_values
    draw_colored_band(dc);
    if (m_extra_style & wxSL_AUTOTICKS)
        draw_ruler(dc);
    if (!m_render_as_disabled) {
        // draw line
        draw_scroll_line(dc, lower_pos, higher_pos);
        // draw color print ticks
        draw_ticks(dc);
        // draw both sliders
        draw_thumbs(dc, lower_pos, higher_pos);
        // draw lock/unlock
        draw_one_layer_icon(dc);
        // draw revert bitmap (if it's shown)
        draw_revert_icon(dc);
        // draw cog bitmap (if it's shown)
        draw_cog_icon(dc);
        // draw mouse position
        draw_tick_on_mouse_position(dc);
    }
}
References draw_cog_icon(), draw_colored_band(), draw_focus_rect(), draw_one_layer_icon(), draw_revert_icon(), draw_ruler(), draw_scroll_line(), draw_thumbs(), draw_tick_on_mouse_position(), draw_ticks(), get_position_from_value(), m_extra_style, m_font, m_higher_value, m_lower_value, and m_render_as_disabled.
Referenced by OnPaint().
set_render_as_disabled()
void Slic3r::DoubleSlider::Control::set_render_as_disabled (bool value) inline
{ m_render_as_disabled = value; }
References m_render_as_disabled.
Referenced by Slic3r::GUI::Preview::enable_moves_slider().
SetDrawMode() [1/2]
void Slic3r::DoubleSlider::Control::SetDrawMode (bool is_sla_print, bool is_sequential_print)
{
    m_draw_mode = is_sla_print          ? dmSlaPrint            :
                  is_sequential_print   ? dmSequentialFffPrint  :
                                          dmRegular;
}
References Slic3r::DoubleSlider::dmRegular, Slic3r::DoubleSlider::dmSequentialFffPrint, Slic3r::DoubleSlider::dmSlaPrint, and m_draw_mode.
Referenced by Slic3r::GUI::Preview::create_layers_slider_sizer(), Slic3r::GUI::Preview::init(), and Slic3r::GUI::Preview::update_layers_slider().
SetDrawMode() [2/2]
void Slic3r::DoubleSlider::Control::SetDrawMode (DrawMode mode) inline
{ m_draw_mode = mode; }
References m_draw_mode.
SetExtruderColors()
void Slic3r::DoubleSlider::Control::SetExtruderColors (const std::vector< std::string > & extruder_colors)
{
    m_extruder_colors = extruder_colors;
}
References m_extruder_colors.
Referenced by Slic3r::GUI::Preview::update_layers_slider().
SetHigherValue()
void Slic3r::DoubleSlider::Control::SetHigherValue (const int higher_val)
{
    m_selection = ssHigher;
    m_higher_value = higher_val;
    correct_higher_value();
    Refresh();
    Update();
    wxCommandEvent e(wxEVT_SCROLL_CHANGED);
    e.SetEventObject(this);
    ProcessWindowEvent(e);
}
References correct_higher_value(), m_higher_value, m_selection, and Slic3r::DoubleSlider::ssHigher.
Referenced by discard_all_thicks(), jump_to_value(), move_current_thumb_to_pos(), Slic3r::GUI::Preview::reset_layers_slider(), Slic3r::GUI::Preview::set_layers_slider_values_range(), switch_one_layer_mode(), and Slic3r::GUI::Preview::update_layers_slider_from_canvas().
SetKoefForLabels()
void Slic3r::DoubleSlider::Control::SetKoefForLabels (const double koef) inline
{ m_label_koef = koef; }
References m_label_koef.
SetLayersTimes() [1/2]
void Slic3r::DoubleSlider::Control::SetLayersTimes (const std::vector< double > & layers_times)
{
    m_is_wipe_tower = false;
    m_layers_times = layers_times;
    for (size_t i = 1; i < m_layers_times.size(); i++)
        m_layers_times[i] += m_layers_times[i - 1];
}
References m_is_wipe_tower, and m_layers_times.
SetLayersTimes() [2/2]
void Slic3r::DoubleSlider::Control::SetLayersTimes (const std::vector< float > & layers_times, float total_time)
{
    m_layers_times.clear();
    if (layers_times.empty())
        return;
    m_layers_times.resize(layers_times.size(), 0.0);
    m_layers_times[0] = layers_times[0];
    for (size_t i = 1; i < layers_times.size(); i++)
        m_layers_times[i] = m_layers_times[i - 1] + layers_times[i];
    // Erase duplicates values from m_values and save it to the m_layers_values
    // They will be used for show the correct estimated time for MM print, when "No sparce layer" is enabled
    // See https://github.com/prusa3d/PrusaSlicer/issues/6232
    if (m_is_wipe_tower && m_values.size() != m_layers_times.size()) {
        m_layers_values = m_values;
        sort(m_layers_values.begin(), m_layers_values.end());
        m_layers_values.erase(unique(m_layers_values.begin(), m_layers_values.end()), m_layers_values.end());
        // When whipe tower is used to the end of print, there is one layer which is not marked in layers_times
        // So, add this value from the total print time value
        if (m_layers_values.size() != m_layers_times.size())
            for (size_t i = m_layers_times.size(); i < m_layers_values.size(); i++)
                m_layers_times.push_back(total_time);
        m_ruler.update(m_layers_values.empty() ? m_values : m_layers_values, get_scroll_step());
        Refresh();
        Update();
    }
    else
        m_ruler.update(m_layers_values.empty() ? m_values : m_layers_values, get_scroll_step());
}
References get_scroll_step(), m_is_wipe_tower, m_layers_times, m_layers_values, m_ruler, m_values, and Slic3r::DoubleSlider::Control::Ruler::update().
Referenced by Slic3r::GUI::Preview::update_layers_slider().
SetLowerValue()
void Slic3r::DoubleSlider::Control::SetLowerValue (const int lower_val)
{
    m_selection = ssLower;
    m_lower_value = lower_val;
    correct_lower_value();
    Refresh();
    Update();
    wxCommandEvent e(wxEVT_SCROLL_CHANGED);
    e.SetEventObject(this);
    ProcessWindowEvent(e);
}
References correct_lower_value(), m_lower_value, m_selection, and Slic3r::DoubleSlider::ssLower.
Referenced by discard_all_thicks(), jump_to_value(), move_current_thumb_to_pos(), Slic3r::GUI::Preview::reset_layers_slider(), Slic3r::GUI::Preview::set_layers_slider_values_range(), switch_one_layer_mode(), and Slic3r::GUI::Preview::update_layers_slider_from_canvas().
SetManipulationMode()
void Slic3r::DoubleSlider::Control::SetManipulationMode (Mode mode) inline
{ m_mode = mode; }
References m_mode.
SetMaxValue()
void Slic3r::DoubleSlider::Control::SetMaxValue (const int max_value)
{
    m_max_value = max_value;
    Refresh();
    Update();
}
References m_max_value.
Referenced by Slic3r::GUI::Preview::update_layers_slider(), and Slic3r::GUI::Preview::update_moves_slider().
SetModeAndOnlyExtruder()
void Slic3r::DoubleSlider::Control::SetModeAndOnlyExtruder (const bool is_one_extruder_printed_model, const int only_extruder)
{
    m_mode = !is_one_extruder_printed_model ? MultiExtruder :
             only_extruder < 0              ? SingleExtruder :
                                              MultiAsSingle;
    if (!m_ticks.mode || (m_ticks.empty() && m_ticks.mode != m_mode))
        m_ticks.mode = m_mode;
    m_only_extruder = only_extruder;
    UseDefaultColors(m_mode == SingleExtruder);
    m_is_wipe_tower = m_mode != SingleExtruder;
}
References Slic3r::DoubleSlider::TickCodeInfo::empty(), m_is_wipe_tower, m_mode, m_only_extruder, m_ticks, Slic3r::DoubleSlider::TickCodeInfo::mode, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::MultiExtruder, Slic3r::CustomGCode::SingleExtruder, and UseDefaultColors().
Referenced by Slic3r::GUI::Preview::update_layers_slider_mode().
SetSelectionSpan()
void Slic3r::DoubleSlider::Control::SetSelectionSpan (const int lower_val, const int higher_val)
{
    m_lower_value  = std::max(lower_val, m_min_value);
    m_higher_value = std::max(std::min(higher_val, m_max_value), m_lower_value);
    if (m_lower_value < m_higher_value)
        m_is_one_layer = false;
    Refresh();
    Update();
    wxCommandEvent e(wxEVT_SCROLL_CHANGED);
    e.SetEventObject(this);
    ProcessWindowEvent(e);
}
References m_higher_value, m_is_one_layer, m_lower_value, m_max_value, and m_min_value.
Referenced by Slic3r::GUI::Preview::update_layers_slider(), and Slic3r::GUI::Preview::update_moves_slider().
SetSliderAlternateValues()
void Slic3r::DoubleSlider::Control::SetSliderAlternateValues (const std::vector< double > & values) inline
{ m_alternate_values = values; }
References m_alternate_values.
Referenced by Slic3r::GUI::Preview::update_moves_slider().
SetSliderValues()
void Slic3r::DoubleSlider::Control::SetSliderValues (const std::vector< double > & values)
{
    m_values = values;
    m_ruler.init(m_values, get_scroll_step());
    // When "No sparce layer" is enabled, use m_layers_values for ruler update.
    // Because of m_values has duplicate values in this case.
//    m_ruler.update(this->GetParent(), m_layers_values.empty() ? m_values : m_layers_values, get_scroll_step());
}
References get_scroll_step(), Slic3r::DoubleSlider::Control::Ruler::init(), m_ruler, and m_values.
Referenced by Slic3r::GUI::Preview::update_layers_slider(), and Slic3r::GUI::Preview::update_moves_slider().
SetTicksValues()
void Slic3r::DoubleSlider::Control::SetTicksValues (const Info & custom_gcode_per_print_z)
{
    if (m_values.empty()) {
        m_ticks.mode = m_mode;
        return;
    }
    const bool was_empty = m_ticks.empty();
    m_ticks.ticks.clear();
    const std::vector<CustomGCode::Item>& heights = custom_gcode_per_print_z.gcodes;
    for (auto h : heights) {
        int tick = get_tick_from_value(h.print_z);
        if (tick >=0)
            m_ticks.ticks.emplace(TickCode{ tick, h.type, h.extruder, h.color, h.extra });
    }
    if (!was_empty && m_ticks.empty())
        // Switch to the "Feature type"/"Tool" from the very beginning of a new object slicing after deleting of the old one
        post_ticks_changed_event();
    // init extruder sequence in respect to the extruders count
    if (m_ticks.empty())
        m_extruders_sequence.init(m_extruder_colors.size());
    if (custom_gcode_per_print_z.mode && !custom_gcode_per_print_z.gcodes.empty())
        m_ticks.mode = custom_gcode_per_print_z.mode;
    Refresh();
    Update();
}
References Slic3r::DoubleSlider::TickCodeInfo::empty(), Slic3r::CustomGCode::Info::gcodes, get_tick_from_value(), Slic3r::DoubleSlider::ExtrudersSequence::init(), m_extruder_colors, m_extruders_sequence, m_mode, m_ticks, m_values, Slic3r::CustomGCode::Info::mode, Slic3r::DoubleSlider::TickCodeInfo::mode, post_ticks_changed_event(), Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::DoubleSlider::TickCode::type.
Referenced by Slic3r::GUI::Preview::update_layers_slider().
show_add_context_menu()
void Slic3r::DoubleSlider::Control::show_add_context_menu ()
{
    wxMenu menu;
    if (m_mode == SingleExtruder) {
        append_menu_item(&menu, wxID_ANY, _L("Add color change") + " (" + gcode(ColorChange) + ")", "",
            [this](wxCommandEvent&) { add_code_as_tick(ColorChange); }, "colorchange_add_m", &menu);
        UseDefaultColors(false);
    }
    else {
        append_change_extruder_menu_item(&menu);
        append_add_color_change_menu_item(&menu);
    }
    if (!gcode(PausePrint).empty())
        append_menu_item(&menu, wxID_ANY, _L("Add pause print") + " (" + gcode(PausePrint) + ")", "",
            [this](wxCommandEvent&) { add_code_as_tick(PausePrint); }, "pause_print", &menu);
    if (!gcode(Template).empty())
        append_menu_item(&menu, wxID_ANY, _L("Add custom template") + " (" + gcode(Template) + ")", "",
            [this](wxCommandEvent&) { add_code_as_tick(Template); }, "edit_gcode", &menu);
    append_menu_item(&menu, wxID_ANY, _L("Add custom G-code"), "",
        [this](wxCommandEvent&) { add_code_as_tick(Custom); }, "edit_gcode", &menu);
    GUI::wxGetApp().plater()->PopupMenu(&menu);
}
References _L, add_code_as_tick(), append_add_color_change_menu_item(), append_change_extruder_menu_item(), append_menu_item(), Slic3r::CustomGCode::ColorChange, Slic3r::CustomGCode::Custom, Slic3r::empty(), Slic3r::DoubleSlider::gcode(), m_mode, Slic3r::CustomGCode::PausePrint, Slic3r::CustomGCode::SingleExtruder, Slic3r::CustomGCode::Template, and UseDefaultColors().
Referenced by OnRightUp().
show_cog_icon_context_menu()
void Slic3r::DoubleSlider::Control::show_cog_icon_context_menu ()
{
    wxMenu menu;
    append_menu_item(&menu, wxID_ANY, _L("Jump to height") + " (Shift+G)", "",
                    [this](wxCommandEvent&) { jump_to_value(); }, "", & menu);
    wxMenu* ruler_mode_menu = new wxMenu();
    if (ruler_mode_menu) {
        append_menu_check_item(ruler_mode_menu, wxID_ANY, _L("None"), _L("Hide ruler"),
            [this](wxCommandEvent&) { if (m_extra_style != 0) m_extra_style = 0; }, ruler_mode_menu,
            []() { return true; }, [this]() { return m_extra_style == 0; }, GUI::wxGetApp().plater());
        append_menu_check_item(ruler_mode_menu, wxID_ANY, _L("Show object height"), _L("Show object height on the ruler"),
            [this](wxCommandEvent&) { m_extra_style & wxSL_AUTOTICKS ? m_extra_style ^= wxSL_AUTOTICKS : m_extra_style |= wxSL_AUTOTICKS; }, ruler_mode_menu,
            []() { return true; }, [this]() { return m_extra_style & wxSL_AUTOTICKS; }, GUI::wxGetApp().plater());
        append_menu_check_item(ruler_mode_menu, wxID_ANY, _L("Show estimated print time"), _L("Show estimated print time on the ruler"),
            [this](wxCommandEvent&) { m_extra_style & wxSL_VALUE_LABEL ? m_extra_style ^= wxSL_VALUE_LABEL : m_extra_style |= wxSL_VALUE_LABEL; }, ruler_mode_menu,
            []() { return true; }, [this]() { return m_extra_style & wxSL_VALUE_LABEL; }, GUI::wxGetApp().plater());
        append_submenu(&menu, ruler_mode_menu, wxID_ANY, _L("Ruler mode"), _L("Set ruler mode"), "",
            []() { return true; }, this);
    }
    if (m_mode == MultiAsSingle && m_draw_mode == dmRegular)
        append_menu_item(&menu, wxID_ANY, _L("Set extruder sequence for the entire print"), "",
            [this](wxCommandEvent&) { edit_extruder_sequence(); }, "", &menu);
    if (GUI::wxGetApp().is_editor() && m_mode != MultiExtruder && m_draw_mode == dmRegular)
        append_menu_item(&menu, wxID_ANY, _L("Set auto color changes"), "",
            [this](wxCommandEvent&) { auto_color_change(); }, "", &menu);
    GUI::wxGetApp().plater()->PopupMenu(&menu);
}
References _L, append_menu_check_item(), append_menu_item(), append_submenu(), auto_color_change(), Slic3r::DoubleSlider::dmRegular, edit_extruder_sequence(), jump_to_value(), m_draw_mode, m_extra_style, m_mode, Slic3r::CustomGCode::MultiAsSingle, and Slic3r::CustomGCode::MultiExtruder.
Referenced by OnLeftUp(), and OnRightUp().
show_edit_context_menu()
void Slic3r::DoubleSlider::Control::show_edit_context_menu ()
{
    wxMenu menu;
    std::set<TickCode>::iterator it = m_ticks.ticks.find(TickCode{ m_selection == ssLower ? m_lower_value : m_higher_value });
    if (it->type == ToolChange) {
        if (m_mode == MultiAsSingle)
            append_change_extruder_menu_item(&menu);
        append_add_color_change_menu_item(&menu, true);
    }
    else
        append_menu_item(&menu, wxID_ANY, it->type == ColorChange ? _L("Edit color") :
                                          it->type == PausePrint  ? _L("Edit pause print message") :
                                          _L("Edit custom G-code"), "",
            [this](wxCommandEvent&) { edit_tick(); }, "edit_uni", &menu);
    if (it->type == ColorChange && m_mode == MultiAsSingle)
        append_change_extruder_menu_item(&menu, true);
    append_menu_item(&menu, wxID_ANY, it->type == ColorChange ? _L("Delete color change") :
                                      it->type == ToolChange  ? _L("Delete tool change") :
                                      it->type == PausePrint  ? _L("Delete pause print") :
                                      _L("Delete custom G-code"), "",
        [this](wxCommandEvent&) { delete_current_tick();}, "colorchange_del_f", &menu);
    GUI::wxGetApp().plater()->PopupMenu(&menu);
}
References _L, append_add_color_change_menu_item(), append_change_extruder_menu_item(), append_menu_item(), Slic3r::CustomGCode::ColorChange, delete_current_tick(), edit_tick(), m_higher_value, m_lower_value, m_mode, m_selection, m_ticks, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::PausePrint, Slic3r::DoubleSlider::ssLower, Slic3r::DoubleSlider::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
Referenced by OnRightUp().
switch_one_layer_mode()
void Slic3r::DoubleSlider::Control::switch_one_layer_mode ()
{
    m_is_one_layer = !m_is_one_layer;
    if (!m_is_one_layer) {
        SetLowerValue(m_min_value);
        SetHigherValue(m_max_value);
    }
    m_selection == ssLower ? correct_lower_value() : correct_higher_value();
    if (m_selection == ssUndef) m_selection = ssHigher;
}
References correct_higher_value(), correct_lower_value(), m_is_one_layer, m_max_value, m_min_value, m_selection, SetHigherValue(), SetLowerValue(), Slic3r::DoubleSlider::ssHigher, Slic3r::DoubleSlider::ssLower, and Slic3r::DoubleSlider::ssUndef.
Referenced by OnLeftUp().
sys_color_changed()
void Slic3r::DoubleSlider::Control::sys_color_changed ()
{
    GUI::wxGetApp().UpdateDarkUI(GetParent());
    m_bmp_add_tick_on .sys_color_changed();
    m_bmp_add_tick_off.sys_color_changed();
    m_bmp_del_tick_on .sys_color_changed();
    m_bmp_del_tick_off.sys_color_changed();
    m_bmp_one_layer_lock_on   .sys_color_changed();
    m_bmp_one_layer_lock_off  .sys_color_changed();
    m_bmp_one_layer_unlock_on .sys_color_changed();
    m_bmp_one_layer_unlock_off.sys_color_changed();
    m_bmp_revert.sys_color_changed();
    m_bmp_cog   .sys_color_changed();
}
References m_bmp_add_tick_off, m_bmp_add_tick_on, m_bmp_cog, m_bmp_del_tick_off, m_bmp_del_tick_on, m_bmp_one_layer_lock_off, m_bmp_one_layer_lock_on, m_bmp_one_layer_unlock_off, m_bmp_one_layer_unlock_on, m_bmp_revert, and ScalableBitmap::sys_color_changed().
Referenced by Slic3r::GUI::Preview::sys_color_changed().
update_thumb_rect()
void Slic3r::DoubleSlider::Control::update_thumb_rect (const wxCoord begin_x, const wxCoord begin_y, const SelectedSlider & selection) protected
{
    const wxRect rect = is_horizontal() ?
        wxRect(begin_x + (selection == ssHigher ? m_thumb_size.x / 2 : 0), begin_y, m_thumb_size.x / 2, m_thumb_size.y) :
        wxRect(begin_x, begin_y + (selection == ssLower ? m_thumb_size.y / 2 : 0), m_thumb_size.x, m_thumb_size.y / 2);
    if (selection == ssLower)
        m_rect_lower_thumb = rect;
    else
        m_rect_higher_thumb = rect;
}
References is_horizontal(), m_rect_higher_thumb, m_rect_lower_thumb, m_thumb_size, Slic3r::DoubleSlider::ssHigher, and Slic3r::DoubleSlider::ssLower.
Referenced by draw_thumb_item().
UseDefaultColors()
void Slic3r::DoubleSlider::Control::UseDefaultColors (bool def_colors_on) inline
{ m_ticks.set_default_colors(def_colors_on); }
References m_ticks, and Slic3r::DoubleSlider::TickCodeInfo::set_default_colors().
Referenced by Slic3r::GUI::Preview::create_layers_slider_sizer(), OnKeyDown(), OnKeyUp(), SetModeAndOnlyExtruder(), show_add_context_menu(), and Slic3r::GUI::Preview::update_layers_slider_from_canvas().
Member Data Documentation
DARK_GREY_PEN
wxPen Slic3r::DoubleSlider::Control::DARK_GREY_PEN private
Referenced by Control(), and draw_ticks().
DARK_ORANGE_PEN
wxPen Slic3r::DoubleSlider::Control::DARK_ORANGE_PEN private
Referenced by Control(), draw_info_line_with_icon(), draw_tick_on_mouse_position(), and draw_tick_text().
FOCUS_RECT_BRUSH
wxBrush Slic3r::DoubleSlider::Control::FOCUS_RECT_BRUSH private
Referenced by Control(), and draw_focus_rect().
FOCUS_RECT_PEN
wxPen Slic3r::DoubleSlider::Control::FOCUS_RECT_PEN private
Referenced by Control(), and draw_focus_rect().
GREY_PEN
wxPen Slic3r::DoubleSlider::Control::GREY_PEN private
Referenced by Control(), draw_ruler(), draw_tick_on_mouse_position(), and draw_tick_text().
is_osx
bool Slic3r::DoubleSlider::Control::is_osx { false } private
Referenced by Control(), and get_tooltip().
LIGHT_GREY_PEN
wxPen Slic3r::DoubleSlider::Control::LIGHT_GREY_PEN private
Referenced by Control(), draw_tick_on_mouse_position(), and draw_ticks().
LIGHT_ORANGE_PEN
wxPen Slic3r::DoubleSlider::Control::LIGHT_ORANGE_PEN private
Referenced by Control().
m_alternate_values
std::vector<double> Slic3r::DoubleSlider::Control::m_alternate_values private
Referenced by get_label(), and SetSliderAlternateValues().
m_bmp_add_tick_off
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_add_tick_off private
Referenced by Control(), draw_action_icon(), and sys_color_changed().
m_bmp_add_tick_on
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_add_tick_on private
Referenced by Control(), draw_action_icon(), msw_rescale(), and sys_color_changed().
m_bmp_cog
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_cog private
Referenced by Control(), draw_cog_icon(), msw_rescale(), and sys_color_changed().
m_bmp_del_tick_off
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_del_tick_off private
Referenced by Control(), draw_action_icon(), and sys_color_changed().
m_bmp_del_tick_on
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_del_tick_on private
Referenced by Control(), draw_action_icon(), and sys_color_changed().
m_bmp_one_layer_lock_off
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_one_layer_lock_off private
Referenced by Control(), draw_one_layer_icon(), and sys_color_changed().
m_bmp_one_layer_lock_on
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_one_layer_lock_on private
Referenced by Control(), draw_one_layer_icon(), msw_rescale(), and sys_color_changed().
m_bmp_one_layer_unlock_off
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_one_layer_unlock_off private
Referenced by Control(), draw_one_layer_icon(), and sys_color_changed().
m_bmp_one_layer_unlock_on
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_one_layer_unlock_on private
Referenced by Control(), draw_one_layer_icon(), and sys_color_changed().
m_bmp_revert
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_revert private
Referenced by Control(), draw_revert_icon(), msw_rescale(), and sys_color_changed().
m_bmp_thumb_higher
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_thumb_higher private
Referenced by Control(), and draw_thumb_item().
m_bmp_thumb_lower
ScalableBitmap Slic3r::DoubleSlider::Control::m_bmp_thumb_lower private
Referenced by Control(), draw_thumb_item(), and msw_rescale().
m_cog_icon_dim
int Slic3r::DoubleSlider::Control::m_cog_icon_dim private
Referenced by Control(), draw_cog_icon(), and msw_rescale().
m_draw_mode
DrawMode Slic3r::DoubleSlider::Control::m_draw_mode = dmRegular private
Referenced by draw_action_icon(), draw_cog_icon(), draw_colored_band(), draw_info_line_with_icon(), draw_one_layer_icon(), draw_revert_icon(), draw_ticks(), get_label(), get_size(), get_tooltip(), is_lower_thumb_editable(), jump_to_value(), move_current_thumb_to_pos(), OnChar(), OnKeyDown(), OnLeftDown(), OnRightDown(), OnWheel(), SetDrawMode(), SetDrawMode(), and show_cog_icon_context_menu().
m_enable_action_icon
bool Slic3r::DoubleSlider::Control::m_enable_action_icon = true private
Referenced by draw_action_icon(), and enable_action_icon().
m_extra_style
long Slic3r::DoubleSlider::Control::m_extra_style private
Referenced by draw_tick_on_mouse_position(), render(), and show_cog_icon_context_menu().
m_extruder_colors
std::vector<std::string> Slic3r::DoubleSlider::Control::m_extruder_colors private
Referenced by Control(), draw_colored_band(), edit_extruder_sequence(), get_color_for_tool_change_tick(), SetExtruderColors(), and SetTicksValues().
m_extruders_sequence
ExtrudersSequence Slic3r::DoubleSlider::Control::m_extruders_sequence
Referenced by edit_extruder_sequence(), and SetTicksValues().
m_focus
FocusedItem Slic3r::DoubleSlider::Control::m_focus = fiNone private
Referenced by draw_action_icon(), draw_one_layer_icon(), get_tooltip(), and OnMotion().
m_font
wxFont Slic3r::DoubleSlider::Control::m_font private
Referenced by Control(), msw_rescale(), and render().
m_force_mode_apply
bool Slic3r::DoubleSlider::Control::m_force_mode_apply = true private
Referenced by GetTicksValues().
m_higher_value
int Slic3r::DoubleSlider::Control::m_higher_value private
Referenced by add_code_as_tick(), add_current_tick(), append_add_color_change_menu_item(), append_change_extruder_menu_item(), correct_higher_value(), correct_lower_value(), delete_current_tick(), draw_action_icon(), draw_thumb_text(), draw_tick_on_mouse_position(), draw_tick_text(), edit_tick(), get_double_value(), get_lower_and_higher_position(), GetActiveValue(), GetHigherValue(), is_higher_at_max(), jump_to_value(), move_current_thumb(), OnLeftDown(), OnMotion(), OnRightDown(), render(), SetHigherValue(), SetSelectionSpan(), and show_edit_context_menu().
m_is_focused
bool Slic3r::DoubleSlider::Control::m_is_focused = false private
Referenced by draw_focus_rect(), draw_tick_on_mouse_position(), enter_window(), and OnKeyDown().
m_is_left_down
bool Slic3r::DoubleSlider::Control::m_is_left_down = false private
Referenced by OnLeftDown(), OnLeftUp(), OnMotion(), OnRightDown(), and OnRightUp().
m_is_one_layer
bool Slic3r::DoubleSlider::Control::m_is_one_layer = false private
Referenced by ChangeOneLayerLock(), correct_higher_value(), correct_lower_value(), draw_one_layer_icon(), is_one_layer(), OnKeyUp(), OnRightDown(), OnRightUp(), SetSelectionSpan(), and switch_one_layer_mode().
m_is_right_down
bool Slic3r::DoubleSlider::Control::m_is_right_down = false private
Referenced by OnMotion(), OnRightDown(), and OnRightUp().
m_is_wipe_tower
bool Slic3r::DoubleSlider::Control::m_is_wipe_tower = false private
Referenced by get_label(), get_tick_from_value(), is_wipe_tower_layer(), OnMotion(), SetLayersTimes(), SetLayersTimes(), and SetModeAndOnlyExtruder().
m_label_koef
float Slic3r::DoubleSlider::Control::m_label_koef { 1.0 } private
Referenced by get_label(), and SetKoefForLabels().
m_layers_times
std::vector<double> Slic3r::DoubleSlider::Control::m_layers_times private
Referenced by get_label(), SetLayersTimes(), and SetLayersTimes().
m_layers_values
std::vector<double> Slic3r::DoubleSlider::Control::m_layers_values private
Referenced by Control(), get_label(), msw_rescale(), and SetLayersTimes().
m_line_pens
std::vector<wxPen*> Slic3r::DoubleSlider::Control::m_line_pens private
Referenced by Control(), and draw_scroll_line().
m_lock_icon_dim
int Slic3r::DoubleSlider::Control::m_lock_icon_dim private
Referenced by Control(), draw_one_layer_icon(), get_size(), and msw_rescale().
m_lower_value
int Slic3r::DoubleSlider::Control::m_lower_value private
Referenced by add_code_as_tick(), add_current_tick(), append_add_color_change_menu_item(), append_change_extruder_menu_item(), correct_higher_value(), correct_lower_value(), delete_current_tick(), draw_action_icon(), draw_thumb_text(), draw_tick_on_mouse_position(), draw_tick_text(), edit_tick(), get_double_value(), get_lower_and_higher_position(), GetActiveValue(), GetLowerValue(), is_lower_at_min(), jump_to_value(), move_current_thumb(), OnLeftDown(), OnMotion(), OnRightDown(), render(), SetLowerValue(), SetSelectionSpan(), and show_edit_context_menu().
m_max_value
int Slic3r::DoubleSlider::Control::m_max_value private
Referenced by correct_higher_value(), correct_lower_value(), discard_all_thicks(), draw_ruler(), draw_tick_on_mouse_position(), edit_extruder_sequence(), get_lower_and_higher_position(), get_position_from_value(), get_scroll_step(), GetMaxValue(), GetMaxValueD(), is_higher_at_max(), jump_to_value(), SetMaxValue(), SetSelectionSpan(), and switch_one_layer_mode().
m_min_value
int Slic3r::DoubleSlider::Control::m_min_value private
Referenced by correct_higher_value(), correct_lower_value(), discard_all_thicks(), draw_tick_on_mouse_position(), get_scroll_step(), get_value_from_position(), GetMinValue(), GetMinValueD(), is_lower_at_min(), jump_to_value(), SetSelectionSpan(), and switch_one_layer_mode().
m_mode
Mode Slic3r::DoubleSlider::Control::m_mode = SingleExtruder private
Referenced by add_current_tick(), append_change_extruder_menu_item(), check_ticks_changed_event(), draw_colored_band(), draw_ticks(), get_active_extruders_for_tick(), get_tooltip(), GetManipulationMode(), GetTicksValues(), OnMotion(), OnRightDown(), SetManipulationMode(), SetModeAndOnlyExtruder(), SetTicksValues(), show_add_context_menu(), show_cog_icon_context_menu(), and show_edit_context_menu().
m_mouse
MouseAction Slic3r::DoubleSlider::Control::m_mouse = maNone private
Referenced by OnLeftDown(), OnLeftUp(), OnRightDown(), and OnRightUp().
m_moving_pos
wxPoint Slic3r::DoubleSlider::Control::m_moving_pos = wxDefaultPosition private
Referenced by draw_tick_on_mouse_position(), draw_ticks(), and OnMotion().
m_only_extruder
int Slic3r::DoubleSlider::Control::m_only_extruder = -1 private
Referenced by add_code_as_tick(), append_add_color_change_menu_item(), draw_colored_band(), draw_ticks(), get_active_extruders_for_tick(), get_color_for_color_change_tick(), get_color_for_tool_change_tick(), get_tooltip(), and SetModeAndOnlyExtruder().
m_print_obj_idxs
std::string Slic3r::DoubleSlider::Control::m_print_obj_idxs private
Referenced by IsNewPrint().
m_rect_cog_icon
wxRect Slic3r::DoubleSlider::Control::m_rect_cog_icon private
Referenced by draw_cog_icon(), OnLeftDown(), OnMotion(), and OnRightDown().
m_rect_higher_thumb
wxRect Slic3r::DoubleSlider::Control::m_rect_higher_thumb private
Referenced by detect_selected_slider(), OnMotion(), OnWheel(), and update_thumb_rect().
m_rect_lower_thumb
wxRect Slic3r::DoubleSlider::Control::m_rect_lower_thumb private
Referenced by detect_selected_slider(), OnMotion(), OnWheel(), and update_thumb_rect().
m_rect_one_layer_icon
wxRect Slic3r::DoubleSlider::Control::m_rect_one_layer_icon private
Referenced by draw_one_layer_icon(), OnLeftDown(), and OnMotion().
m_rect_revert_icon
wxRect Slic3r::DoubleSlider::Control::m_rect_revert_icon private
Referenced by draw_revert_icon(), OnLeftDown(), and OnMotion().
m_rect_tick_action
wxRect Slic3r::DoubleSlider::Control::m_rect_tick_action private
Referenced by draw_action_icon(), OnLeftDown(), OnMotion(), and OnRightDown().
m_render_as_disabled
bool Slic3r::DoubleSlider::Control::m_render_as_disabled { false } private
Referenced by is_rendering_as_disabled(), render(), and set_render_as_disabled().
m_revert_icon_dim
int Slic3r::DoubleSlider::Control::m_revert_icon_dim private
Referenced by Control(), draw_revert_icon(), and msw_rescale().
m_ruler
class Slic3r::DoubleSlider::Control::Ruler Slic3r::DoubleSlider::Control::m_ruler private
Referenced by Control(), draw_ruler(), msw_rescale(), SetLayersTimes(), and SetSliderValues().
m_segm_pens
std::vector<wxPen*> Slic3r::DoubleSlider::Control::m_segm_pens private
Referenced by Control(), and draw_scroll_line().
m_selection
SelectedSlider Slic3r::DoubleSlider::Control::m_selection private
Referenced by Control(), add_code_as_tick(), add_current_tick(), append_add_color_change_menu_item(), append_change_extruder_menu_item(), ChangeOneLayerLock(), delete_current_tick(), detect_selected_slider(), discard_all_thicks(), draw_action_icon(), draw_info_line_with_icon(), edit_tick(), GetActiveValue(), jump_to_value(), move_current_thumb(), move_current_thumb_to_pos(), OnKeyDown(), OnLeftDown(), OnMotion(), OnRightDown(), OnWheel(), SetHigherValue(), SetLowerValue(), show_edit_context_menu(), and switch_one_layer_mode().
m_style
long Slic3r::DoubleSlider::Control::m_style private
Referenced by get_scroll_step(), and is_horizontal().
m_thumb_size
wxSize Slic3r::DoubleSlider::Control::m_thumb_size private
Referenced by Control(), draw_info_line_with_icon(), draw_thumb_item(), draw_tick_on_mouse_position(), draw_tick_text(), draw_ticks(), get_colored_band_rect(), msw_rescale(), and update_thumb_rect().
m_tick_icon_dim
int Slic3r::DoubleSlider::Control::m_tick_icon_dim private
Referenced by Control(), draw_action_icon(), draw_ticks(), and msw_rescale().
m_ticks
TickCodeInfo Slic3r::DoubleSlider::Control::m_ticks private
Referenced by Control(), add_code_as_tick(), add_current_tick(), append_add_color_change_menu_item(), auto_color_change(), check_ticks_changed_event(), delete_current_tick(), discard_all_thicks(), draw_action_icon(), draw_colored_band(), draw_revert_icon(), draw_ticks(), edit_extruder_sequence(), edit_tick(), get_active_extruders_for_tick(), get_color_for_color_change_tick(), get_color_for_tool_change_tick(), get_edited_tick_for_position(), get_tick_near_point(), get_tooltip(), GetTicksValues(), OnChar(), OnKeyDown(), OnLeftDown(), OnMotion(), OnRightDown(), SetModeAndOnlyExtruder(), SetTicksValues(), show_edit_context_menu(), and UseDefaultColors().
m_values
std::vector<double> Slic3r::DoubleSlider::Control::m_values private
Referenced by Control(), add_code_as_tick(), append_add_color_change_menu_item(), draw_ruler(), draw_ticks(), edit_tick(), get_double_value(), get_label(), get_tick_from_value(), get_tooltip(), GetMaxValueD(), GetMinValueD(), GetTicksValues(), is_wipe_tower_layer(), jump_to_value(), msw_rescale(), SetLayersTimes(), SetSliderValues(), and SetTicksValues().
ORANGE_PEN
wxPen Slic3r::DoubleSlider::Control::ORANGE_PEN private
Referenced by Control().
SLIDER_MARGIN
wxCoord Slic3r::DoubleSlider::Control::SLIDER_MARGIN private
Referenced by Control(), draw_colored_band(), draw_revert_icon(), draw_scroll_line(), get_colored_band_rect(), get_lower_and_higher_position(), get_position_from_value(), get_scroll_step(), get_value_from_position(), and msw_rescale().
The documentation for this class was generated from the following files:
src/slic3r/GUI/DoubleSlider.hpp
src/slic3r/GUI/DoubleSlider.cpp