Prusa Slicer: Slic3r::TriangleMeshStats Struct Reference
Slic3r::TriangleMeshStats Struct Reference
#include <src/libslic3r/TriangleMesh.hpp>
Public Member Functions
void clear ()
TriangleMeshStats merge (const TriangleMeshStats &rhs) const
bool manifold () const
bool repaired () const
Public Attributes
uint32_t number_of_facets = 0
stl_vertex max = stl_vertex::Zero()
stl_vertex min = stl_vertex::Zero()
stl_vertex size = stl_vertex::Zero()
float volume = -1.f
int number_of_parts = 0
int open_edges = 0
RepairedMeshErrors repaired_errors
Detailed Description
Member Function Documentation
clear()
void Slic3r::TriangleMeshStats::clear () inline
{ *this = TriangleMeshStats(); }
Referenced by Slic3r::TriangleMesh::clear().
manifold()
bool Slic3r::TriangleMeshStats::manifold () const inline
{ return open_edges == 0; }
References open_edges.
Referenced by Slic3r::GUI::ObjectList::get_mesh_errors_info(), Slic3r::GUI::get_warning_icon_name(), and Slic3r::ModelObject::print_info().
merge()
TriangleMeshStats Slic3r::TriangleMeshStats::merge (const TriangleMeshStats & rhs) const inline
{
      if (this->number_of_facets == 0)
        return rhs;
      else if (rhs.number_of_facets == 0)
        return *this;
      else {
        TriangleMeshStats out;
        out.number_of_facets        = this->number_of_facets + rhs.number_of_facets;
        out.min                     = this->min.cwiseMin(rhs.min);
        out.max                     = this->max.cwiseMax(rhs.max);
        out.size                    = out.max - out.min;
        out.number_of_parts         = this->number_of_parts     + rhs.number_of_parts;
        out.open_edges              = this->open_edges          + rhs.open_edges;
        out.volume                  = this->volume              + rhs.volume;
        out.repaired_errors.merge(rhs.repaired_errors);
        return out;
      }
    }
References max, Slic3r::RepairedMeshErrors::merge(), min, number_of_facets, number_of_parts, open_edges, repaired_errors, size, and volume.
Referenced by Slic3r::TriangleMesh::merge().
repaired()
bool Slic3r::TriangleMeshStats::repaired () const inline
{ return repaired_errors.repaired(); }
References Slic3r::RepairedMeshErrors::repaired(), and repaired_errors.
Referenced by Slic3r::GUI::ObjectList::get_mesh_errors_info(), Slic3r::GUI::get_warning_icon_name(), and Slic3r::ModelObject::print_info().
Member Data Documentation
max
stl_vertex Slic3r::TriangleMeshStats::max = stl_vertex::Zero()
Referenced by Slic3r::TriangleMesh::bounding_box(), Slic3r::is_front_up_left(), merge(), Slic3r::TriangleMesh::mirror(), Slic3r::TriangleMesh::ReadSTLFile(), Slic3r::TriangleMesh::scale(), Slic3r::TriangleMesh::translate(), and Slic3r::update_bounding_box().
min
stl_vertex Slic3r::TriangleMeshStats::min = stl_vertex::Zero()
Referenced by Slic3r::TriangleMesh::align_to_origin(), Slic3r::TriangleMesh::bounding_box(), Slic3r::is_front_up_left(), merge(), Slic3r::TriangleMesh::mirror(), Slic3r::TriangleMesh::ReadSTLFile(), Slic3r::TriangleMesh::scale(), Slic3r::TriangleMesh::translate(), and Slic3r::update_bounding_box().
number_of_facets
uint32_t Slic3r::TriangleMeshStats::number_of_facets = 0
Referenced by Slic3r::TriangleMesh::facets_count(), Slic3r::fill_initial_stats(), merge(), and Slic3r::TriangleMesh::ReadSTLFile().
number_of_parts
int Slic3r::TriangleMeshStats::number_of_parts = 0
Referenced by Slic3r::fill_initial_stats(), Slic3r::ModelObject::get_object_stl_stats(), merge(), Slic3r::ModelObject::print_info(), Slic3r::TriangleMesh::ReadSTLFile(), and Slic3r::GUI::Sidebar::show_info_sizer().
open_edges
int Slic3r::TriangleMeshStats::open_edges = 0
Referenced by Slic3r::fill_initial_stats(), Slic3r::GUI::ObjectList::get_mesh_errors_info(), Slic3r::ModelObject::get_object_stl_stats(), manifold(), merge(), Slic3r::ModelObject::print_info(), and Slic3r::TriangleMesh::ReadSTLFile().
repaired_errors
RepairedMeshErrors Slic3r::TriangleMeshStats::repaired_errors
Referenced by Slic3r::TriangleMesh::TriangleMesh(), Slic3r::GUI::ObjectList::get_mesh_errors_info(), Slic3r::ModelObject::get_object_stl_stats(), Slic3r::ModelVolume::get_repaired_errors_count(), merge(), Slic3r::ModelObject::print_info(), Slic3r::TriangleMesh::ReadSTLFile(), and repaired().
size
stl_vertex Slic3r::TriangleMeshStats::size = stl_vertex::Zero()
Referenced by merge(), Slic3r::TriangleMesh::ReadSTLFile(), Slic3r::TriangleMesh::scale(), Slic3r::TriangleMesh::size(), and Slic3r::update_bounding_box().
volume
float Slic3r::TriangleMeshStats::volume = -1.f
Referenced by Slic3r::fill_initial_stats(), Slic3r::TriangleMesh::flip_triangles(), Slic3r::ModelObject::get_object_stl_stats(), merge(), Slic3r::TriangleMesh::ReadSTLFile(), Slic3r::TriangleMesh::scale(), Slic3r::GUI::Sidebar::show_info_sizer(), Slic3r::TriangleMesh::transform(), Slic3r::TriangleMesh::transform(), and Slic3r::TriangleMesh::volume().
The documentation for this struct was generated from the following file:
src/libslic3r/TriangleMesh.hpp