Prusa Slicer: Slic3r::GLVolume::SinkingContours Class Reference
Slic3r::GLVolume::SinkingContours Class Reference
Public Member Functions
SinkingContours (GLVolume &volume)
void render ()
Private Member Functions
void update ()
Private Attributes
GLVolume & m_parent
GUI::GLModel m_model
BoundingBoxf3 m_old_box
Vec3d m_shift { Vec3d::Zero() }
Static Private Attributes
static const float HalfWidth = 0.25f
Detailed Description
Constructor & Destructor Documentation
SinkingContours()
Slic3r::GLVolume::SinkingContours::SinkingContours (GLVolume & volume) inline
: m_parent(volume) {}
Member Function Documentation
render()
void Slic3r::GLVolume::SinkingContours::render ()
{
    update();
    GLShaderProgram* shader = GUI::wxGetApp().get_current_shader();
    if (shader == nullptr)
        return;
    const GUI::Camera& camera = GUI::wxGetApp().plater()->get_camera();
    shader->set_uniform("view_model_matrix", camera.get_view_matrix() * Geometry::translation_transform(m_shift));
    shader->set_uniform("projection_matrix", camera.get_projection_matrix());
    m_model.render();
}
References Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), m_model, m_shift, Slic3r::GUI::GLModel::render(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::Geometry::translation_transform(), and update().
Referenced by Slic3r::GLVolume::render_sinking_contours().
update()
void Slic3r::GLVolume::SinkingContours::update () private
{
    const int object_idx = m_parent.object_idx();
    const Model& model = GUI::wxGetApp().plater()->model();
    if (object_idx < 0 ||
        object_idx >= int(model.objects.size()) ||
        !m_parent.is_sinking() ||
        m_parent.is_below_printbed()){
        m_model.reset();
        return;
    }
    const BoundingBoxf3& box = m_parent.transformed_convex_hull_bounding_box();
    if (m_old_box.size().isApprox(box.size()) &&
        m_old_box.min.z() == box.min.z()){
        // Fix it !!! It is not working all the time
        m_shift = box.center() - m_old_box.center();
        return;
    }
    m_old_box = box;
    m_shift = Vec3d::Zero();
    const TriangleMesh& mesh = model.objects[object_idx]->volumes[m_parent.volume_idx()]->mesh();
    m_model.reset();
    GUI::GLModel::Geometry init_data;
    init_data.format = { GUI::GLModel::Geometry::EPrimitiveType::Triangles, GUI::GLModel::Geometry::EVertexLayout::P3 };
    init_data.color = ColorRGBA::WHITE();
    unsigned int vertices_counter = 0;
    MeshSlicingParams slicing_params;
    slicing_params.trafo = m_parent.world_matrix();
    const Polygons polygons = union_(slice_mesh(mesh.its, 0.0f, slicing_params));
    if (polygons.empty()) return;
    for (const ExPolygon& expoly : diff_ex(expand(polygons, float(scale_(HalfWidth))), shrink(polygons, float(scale_(HalfWidth))))) {
        const std::vector<Vec3d> triangulation = triangulate_expolygon_3d(expoly);
        init_data.reserve_vertices(init_data.vertices_count() + triangulation.size());
        init_data.reserve_indices(init_data.indices_count() + triangulation.size());
        for (const Vec3d& v : triangulation) {
            init_data.add_vertex((Vec3f)(v.cast<float>() + 0.015f * Vec3f::UnitZ())); // add a small positive z to avoid z-fighting
            ++vertices_counter;
            if (vertices_counter % 3 == 0)
                init_data.add_triangle(vertices_counter - 3, vertices_counter - 2, vertices_counter - 1);
        }
    }
    if (init_data.vertices_count() > 0)
      m_model.init_from(std::move(init_data));
}
References Slic3r::GUI::GLModel::Geometry::add_triangle(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::BoundingBox3Base< PointType >::center(), Slic3r::GUI::GLModel::Geometry::color, Slic3r::diff_ex(), Slic3r::expand(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::GLModel::Geometry::indices_count(), Slic3r::TriangleMesh::its, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::GLVolume::model, Slic3r::GLVolume::object_idx(), Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::reset(), scale_, Slic3r::shrink(), Slic3r::BoundingBox3Base< PointType >::size(), Slic3r::slice_mesh(), Slic3r::MeshSlicingParams::trafo, Slic3r::GUI::GLModel::Geometry::Triangles, Slic3r::triangulate_expolygon_3d(), Slic3r::union_(), Slic3r::GUI::GLModel::Geometry::vertices_count(), and Slic3r::ColorRGBA::WHITE().
Referenced by render().
Member Data Documentation
HalfWidth
const float Slic3r::GLVolume::SinkingContours::HalfWidth = 0.25f static private
m_model
GUI::GLModel Slic3r::GLVolume::SinkingContours::m_model private
Referenced by render().
m_old_box
BoundingBoxf3 Slic3r::GLVolume::SinkingContours::m_old_box private
m_parent
GLVolume& Slic3r::GLVolume::SinkingContours::m_parent private
m_shift
Vec3d Slic3r::GLVolume::SinkingContours::m_shift { Vec3d::Zero() } private
Referenced by render().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DScene.hpp
src/slic3r/GUI/3DScene.cpp