Prusa Slicer: Slic3r::GUI::GLGizmoEmboss Class Reference
Slic3r::GUI::GLGizmoEmboss Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoEmboss.hpp>
Classes
struct FaceName
struct Facenames
struct GuiCfg
Public Types
enum class EGrabberExtension {
None = 0 , PosX = 1 << 0 , NegX = 1 << 1 , PosY = 1 << 2 ,
NegY = 1 << 3 , PosZ = 1 << 4 , NegZ = 1 << 5
}
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoEmboss (GLCanvas3D &parent)
void create_volume (ModelVolumeType volume_type, const Vec2d &mouse_pos)
Create new embossed text volume by type on position of mouse.
void create_volume (ModelVolumeType volume_type)
Create new text without given position.
void on_shortcut_key ()
Handle pressing of shortcut.
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
void set_common_data_pool (CommonGizmosDataPool *ptr)
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
bool is_dragging () const
bool update_items_state ()
void render ()
void render_input_window (float x, float y, float bottom_limit)
virtual std::string get_tooltip () const
Mouse tooltip text.
void register_raycasters_for_picking ()
void unregister_raycasters_for_picking ()
virtual bool is_in_editing_mode () const
virtual bool is_selection_rectangle_dragging () const
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static const unsigned int GRABBER_ELEMENTS_MAX_COUNT = 7
static const int NO_SHORTCUT_KEY_VALUE = 0
Protected Member Functions
bool on_init () override
std::string on_get_name () const override
void on_render () override
void on_register_raycasters_for_picking () override
void on_unregister_raycasters_for_picking () override
void on_render_input_window (float x, float y, float bottom_limit) override
bool on_is_selectable () const override
bool on_is_activable () const override
void on_set_state () override
void data_changed (bool is_serializing) override
Is called when data (Selection) is changed.
void on_set_hover_id () override
void on_enable_grabber (unsigned int id) override
void on_disable_grabber (unsigned int id) override
void on_start_dragging () override
void on_stop_dragging () override
void on_dragging (const UpdateData &data) override
bool on_mouse (const wxMouseEvent &mouse_event) override
Rotate by text on dragging rotate grabers.
bool wants_enter_leave_snapshots () const override
std::string get_gizmo_entering_text () const override
std::string get_gizmo_leaving_text () const override
std::string get_action_snapshot_name () const override
virtual void on_load (cereal::BinaryInputArchive &ar)
virtual void on_save (cereal::BinaryOutputArchive &ar) const
virtual CommonGizmosDataID on_get_requirements () const
void register_grabbers_for_picking ()
void unregister_grabbers_for_picking ()
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers (size_t first, size_t last, float size, bool force_hover) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
bool use_grabbers (const wxMouseEvent &mouse_event)
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
void do_stop_dragging (bool perform_mouse_cleanup)
Protected Attributes
GLCanvas3D & m_parent
int m_group_id
EState m_state
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id { -1 }
bool m_dragging { false }
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render { true }
CommonGizmosDataPool * m_c { nullptr }
Private Member Functions
bool init_create (ModelVolumeType volume_type)
void set_volume_by_selection ()
void reset_volume ()
bool process ()
void close ()
void draw_window ()
void draw_text_input ()
void draw_model_type ()
void fix_transformation (const FontProp &from, const FontProp &to)
void draw_style_list ()
void draw_delete_style_button ()
void draw_style_rename_popup ()
void draw_style_rename_button ()
void draw_style_save_button (bool is_modified)
void draw_style_save_as_popup ()
void draw_style_add_button ()
void init_font_name_texture ()
void draw_font_preview (FaceName &face, bool is_visible)
void draw_font_list_line ()
void draw_font_list ()
void draw_height (bool use_inch)
void draw_depth (bool use_inch)
bool set_height ()
bool set_depth ()
bool draw_italic_button ()
bool draw_bold_button ()
void draw_advanced ()
bool select_facename (const wxString &facename)
void do_translate (const Vec3d &relative_move)
void do_rotate (float relative_z_angle)
bool rev_input_mm (const std::string &name, float &value, const float *default_value, const std::string &undo_tooltip, float step, float step_fast, const char *format, bool use_inch, const std::optional< float > &scale)
bool rev_input (const std::string &name, float &value, const float *default_value, const std::string &undo_tooltip, float step, float step_fast, const char *format, ImGuiInputTextFlags flags=0)
Reversible input float with option to restor default value TODO: make more general, static and move to ImGuiWrapper.
bool rev_checkbox (const std::string &name, bool &value, const bool *default_value, const std::string &undo_tooltip)
bool rev_slider (const std::string &name, std::optional< int > &value, const std::optional< int > *default_value, const std::string &undo_tooltip, int v_min, int v_max, const std::string &format, const wxString &tooltip)
bool rev_slider (const std::string &name, std::optional< float > &value, const std::optional< float > *default_value, const std::string &undo_tooltip, float v_min, float v_max, const std::string &format, const wxString &tooltip)
bool rev_slider (const std::string &name, float &value, const float *default_value, const std::string &undo_tooltip, float v_min, float v_max, const std::string &format, const wxString &tooltip)
template<typename T , typename Draw >
bool revertible (const std::string &name, T &value, const T *default_value, const std::string &undo_tooltip, float undo_offset, Draw draw)
void set_minimal_window_size (bool is_advance_edit_style)
ImVec2 get_minimal_window_size () const
bool on_mouse_for_rotation (const wxMouseEvent &mouse_event)
bool on_mouse_for_translate (const wxMouseEvent &mouse_event)
void on_mouse_change_selection (const wxMouseEvent &mouse_event)
void create_notification_not_valid_font (const TextConfiguration &tc)
void create_notification_not_valid_font (const std::string &text)
void remove_notification_not_valid_font ()
void calculate_scale ()
void init_icons ()
Static Private Member Functions
static EmbossStyles create_default_styles ()
static GuiCfg create_gui_configuration ()
static bool store (const Facenames &facenames)
static bool load (Facenames &facenames)
static void init_face_names (Facenames &facenames)
static void init_truncated_names (Facenames &face_names, float max_width)
Private Attributes
bool m_should_set_minimal_windows_size = false
bool m_is_unknown_font
std::optional< const GuiCfg > m_gui_cfg
bool m_is_advanced_edit_style = false
bool m_allow_open_near_volume = false
std::optional< ImVec2 > m_set_window_offset
Emboss::StyleManager m_style_manager
struct Slic3r::GUI::GLGizmoEmboss::Facenames m_face_names
std::string m_text
bool m_keep_up = true
ModelVolume * m_volume
ObjectID m_volume_id
bool m_text_contain_unknown_glyph = false
std::shared_ptr< std::atomic< bool > > m_job_cancel
GLGizmoRotate m_rotate_gizmo
std::optional< float > m_rotate_start_angle
std::optional< SurfaceDrag > m_surface_drag
RaycastManager m_raycast_manager
std::optional< float > m_scale_height
std::optional< float > m_scale_depth
IconManager m_icon_manager
IconManager::VIcons m_icons
bool m_dirty { false }
Static Private Attributes
static const std::string M_ICON_FILENAME = "cut.svg"
Detailed Description
Class Documentation
Slic3r::GUI::GLGizmoEmboss::FaceName
struct Slic3r::GUI::GLGizmoEmboss::FaceName
Class Members
shared_ptr< atomic< bool > > cancel = nullptr
shared_ptr< bool > is_created = nullptr
string name_truncated = ""
size_t texture_index = 0
wxString wx_name
Slic3r::GUI::GLGizmoEmboss::GuiCfg
struct Slic3r::GUI::GLGizmoEmboss::GuiCfg
Class Members
float advanced_input_offset = 0.f
float delete_pos_x = 0.f
float face_name_max_width = 100.f
Vec2i face_name_size = Vec2i(100, 0)
float face_name_texture_offset_x = 105.f
float height_of_volume_type_selector = 0.f
unsigned int icon_width = 0
float indent = 0.f
float input_offset = 0.f
float input_width = 0.f
float lock_offset = 0.f
float main_toolbar_height
unsigned int max_count_opened_font_files = 10
Vec2i max_style_image_size = Vec2i(0, 0)
float max_style_name_width = 0.f
ImVec2 minimal_window_size = ImVec2(0, 0)
ImVec2 minimal_window_size_with_advance = ImVec2(0, 0)
ImVec2 minimal_window_size_with_collections = ImVec2(0, 0)
double screen_scale
ImVec2 text_size
Translations translations
Member Enumeration Documentation
EGrabberExtension
enum class Slic3r::GUI::GLGizmoBase::EGrabberExtension strong inherited
Enumerator
None
PosX
NegX
PosY
NegY
PosZ
NegZ
    {
        None = 0,
        PosX = 1 << 0,
        NegX = 1 << 1,
        PosY = 1 << 2,
        NegY = 1 << 3,
        PosZ = 1 << 4,
        NegZ = 1 << 5,
    };
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
Constructor & Destructor Documentation
GLGizmoEmboss()
GLGizmoEmboss::GLGizmoEmboss (GLCanvas3D & parent)
    : GLGizmoBase(parent, M_ICON_FILENAME, -2)
    , m_volume(nullptr)
    , m_is_unknown_font(false)
    , m_rotate_gizmo(parent, GLGizmoRotate::Axis::Z) // grab id = 2 (Z axis)
    , m_style_manager(m_imgui->get_glyph_ranges(), create_default_styles)
    , m_job_cancel(nullptr)
{
    m_rotate_gizmo.set_group_id(0);
    m_rotate_gizmo.set_force_local_coordinate(true);
    // TODO: add suggestion to use https://fontawesome.com/
    // (copy & paste) unicode symbols from web
    // paste HEX unicode into notepad move cursor after unicode press [alt] + [x]
}
References m_rotate_gizmo, Slic3r::GUI::GLGizmoRotate::set_force_local_coordinate(), and Slic3r::GUI::GLGizmoRotate::set_group_id().
Member Function Documentation
calculate_scale()
void GLGizmoEmboss::calculate_scale () private
{
    Transform3d to_world = m_parent.get_selection().get_first_volume()->world_matrix();
    auto to_world_linear = to_world.linear();
    auto calc = [&to_world_linear](const Vec3d &axe, std::optional<float>& scale)->bool {
        Vec3d  axe_world = to_world_linear * axe;
        double norm_sq   = axe_world.squaredNorm();
        if (is_approx(norm_sq, 1.)) {
            if (scale.has_value())
                scale.reset();
            else
                return false;
        } else {
            scale = sqrt(norm_sq);
        }
        return true;
    };
    bool exist_change = calc(Vec3d::UnitY(), m_scale_height);
    exist_change |= calc(Vec3d::UnitZ(), m_scale_depth);
    // Change of scale has to change font imgui font size
    if (exist_change)
        m_style_manager.clear_imgui_font();
}
References Slic3r::GUI::Emboss::StyleManager::clear_imgui_font(), exist_change(), Slic3r::GUI::Selection::get_first_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::is_approx(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Slic3r::GUI::GLGizmoBase::m_parent, m_scale_depth, m_scale_height, m_style_manager, scale(), sqrt(), and Slic3r::GLVolume::world_matrix().
Referenced by on_mouse_for_translate(), and set_volume_by_selection().
close()
void GLGizmoEmboss::close () private
{
    // remove volume when text is empty
    if (m_volume != nullptr &&
        m_volume->text_configuration.has_value() &&
        priv::is_text_empty(m_text)) {
        Plater &p = *wxGetApp().plater();
        // is the text object?
        if (m_volume->is_the_only_one_part()) {
            // delete whole object
            p.remove(m_parent.get_selection().get_object_idx());
        } else {
            // delete text volume
            p.remove_selected();
        }
    }
    // close gizmo == open it again
    auto& mng = m_parent.get_gizmos_manager();
    if (mng.get_current_type() == GLGizmosManager::Emboss)
        mng.open_gizmo(GLGizmosManager::Emboss);
}
References Slic3r::GUI::GLGizmosManager::Emboss, Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), priv::is_text_empty(), Slic3r::ModelVolume::is_the_only_one_part(), Slic3r::GUI::GLGizmoBase::m_parent, m_text, m_volume, Slic3r::GUI::GLGizmosManager::open_gizmo(), Slic3r::GUI::Plater::remove(), Slic3r::GUI::Plater::remove_selected(), and Slic3r::ModelVolume::text_configuration.
Referenced by data_changed(), on_mouse_change_selection(), and on_render_input_window().
create_default_styles()
EmbossStyles GLGizmoEmboss::create_default_styles () static private
{
    wxFontEnumerator::InvalidateCache();
    wxArrayString facenames = wxFontEnumerator::GetFacenames(Facenames::encoding);
    wxFont wx_font_normal = *wxNORMAL_FONT;
#ifdef __APPLE__
    // Set normal font to helvetica when possible
    for (const wxString &facename : facenames) {
        if (facename.IsSameAs("Helvetica")) {
            wx_font_normal = wxFont(wxFontInfo().FaceName(facename).Encoding(Facenames::encoding));
            break;
        }
    }
#endif // __APPLE__
    // https://docs.wxwidgets.org/3.0/classwx_font.html
    // Predefined objects/pointers: wxNullFont, wxNORMAL_FONT, wxSMALL_FONT, wxITALIC_FONT, wxSWISS_FONT
    EmbossStyles styles = {
        WxFontUtils::create_emboss_style(wx_font_normal, _u8L("NORMAL")), // wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT)
        WxFontUtils::create_emboss_style(*wxSMALL_FONT, _u8L("SMALL")),  // A font using the wxFONTFAMILY_SWISS family and 2 points smaller than wxNORMAL_FONT.
        WxFontUtils::create_emboss_style(*wxITALIC_FONT, _u8L("ITALIC")), // A font using the wxFONTFAMILY_ROMAN family and wxFONTSTYLE_ITALIC style and of the same size of wxNORMAL_FONT.
        WxFontUtils::create_emboss_style(*wxSWISS_FONT, _u8L("SWISS")),  // A font identic to wxNORMAL_FONT except for the family used which is wxFONTFAMILY_SWISS.
        WxFontUtils::create_emboss_style(wxFont(10, wxFONTFAMILY_MODERN, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD), _u8L("MODERN")),
    };
    // Not all predefined font for wx must be valid TTF, but at least one style must be loadable
    styles.erase(std::remove_if(styles.begin(), styles.end(), [](const EmbossStyle& style) {
        wxFont wx_font = WxFontUtils::create_wxFont(style);
        // check that face name is setabled
        if (style.prop.face_name.has_value()) {
            wxString face_name(style.prop.face_name->c_str());
            wxFont wx_font_temp;
            if (!wx_font_temp.SetFaceName(face_name))
                return true;
        }
        // Check that exsit valid TrueType Font for wx font
        return WxFontUtils::create_font_file(wx_font) == nullptr;
        }),styles.end()
    );
    // exist some valid style?
    if (!styles.empty())
        return styles;
    // No valid style in defult list
    // at least one style must contain loadable font
    wxFont wx_font;
    for (const wxString &face : facenames) {
        wx_font = wxFont(face);
        if (WxFontUtils::create_font_file(wx_font) != nullptr)
            break;
        wx_font = wxFont(); // NotOk
    }
    if (wx_font.IsOk()) {
        // use first alphabetic sorted installed font
        styles.push_back(WxFontUtils::create_emboss_style(wx_font, _u8L("First font")));
    } else {
        // On current OS is not installed any correct TTF font
        // use font packed with Slic3r
        std::string font_path = Slic3r::resources_dir() + "/fonts/NotoSans-Regular.ttf";
        styles.push_back(EmbossStyle{_u8L("Default font"), font_path, EmbossStyle::Type::file_path});
    }
    return styles;
}
References _u8L, Slic3r::GUI::WxFontUtils::create_emboss_style(), Slic3r::GUI::WxFontUtils::create_font_file(), Slic3r::GUI::GLGizmoEmboss::Facenames::encoding, and style.
create_gui_configuration()
GLGizmoEmboss::GuiCfg GLGizmoEmboss::create_gui_configuration () static private
{
    GuiCfg cfg; // initialize by default values;
    float line_height = ImGui::GetTextLineHeight();
    float line_height_with_spacing = ImGui::GetTextLineHeightWithSpacing();
    float space = line_height_with_spacing - line_height;
    const ImGuiStyle &style  = ImGui::GetStyle();
    cfg.max_style_name_width = ImGui::CalcTextSize("Maximal font name, extended").x;
    cfg.icon_width = static_cast<unsigned int>(std::ceil(line_height));
    // make size pair number
    if (cfg.icon_width % 2 != 0) ++cfg.icon_width;
    cfg.delete_pos_x = cfg.max_style_name_width + space;
    int count_line_of_text = 3;
    cfg.text_size = ImVec2(-FLT_MIN, line_height_with_spacing * count_line_of_text);
    ImVec2 letter_m_size = ImGui::CalcTextSize("M");
    int count_letter_M_in_input = 12;
    cfg.input_width = letter_m_size.x * count_letter_M_in_input;
    GuiCfg::Translations &tr = cfg.translations;
    tr.font   = _u8L("Font");
    tr.height = _u8L("Height");
    tr.depth  = _u8L("Depth");
    float max_text_width = std::max({
        ImGui::CalcTextSize(tr.font.c_str()).x,
        ImGui::CalcTextSize(tr.height.c_str()).x,
        ImGui::CalcTextSize(tr.depth.c_str()).x});
    cfg.indent       = static_cast<float>(cfg.icon_width);
    cfg.input_offset = style.WindowPadding.x + cfg.indent + max_text_width + space;
    tr.use_surface  = _u8L("Use surface");
    tr.char_gap     = _u8L("Char gap");
    tr.line_gap     = _u8L("Line gap");
    tr.boldness     = _u8L("Boldness");
    tr.skew_ration  = _u8L("Skew ratio");
    tr.from_surface = _u8L("From surface");
    tr.rotation     = _u8L("Rotation");
    tr.keep_up      = "Keep Rotation";
    tr.collection   = _u8L("Collection");
    float max_advanced_text_width = std::max({
        ImGui::CalcTextSize(tr.use_surface.c_str()).x,
        ImGui::CalcTextSize(tr.char_gap.c_str()).x,
        ImGui::CalcTextSize(tr.line_gap.c_str()).x,
        ImGui::CalcTextSize(tr.boldness.c_str()).x,
        ImGui::CalcTextSize(tr.skew_ration.c_str()).x,
        ImGui::CalcTextSize(tr.from_surface.c_str()).x,
        ImGui::CalcTextSize(tr.rotation.c_str()).x + cfg.icon_width + 2*space,
        ImGui::CalcTextSize(tr.keep_up.c_str()).x,
        ImGui::CalcTextSize(tr.collection.c_str()).x });
    cfg.advanced_input_offset = max_advanced_text_width
        + 3 * space + cfg.indent;
    cfg.lock_offset = cfg.advanced_input_offset - (cfg.icon_width + space);
    // calculate window size
    float window_title = line_height + 2*style.FramePadding.y + 2 * style.WindowTitleAlign.y;
    float input_height = line_height_with_spacing + 2*style.FramePadding.y;
    float tree_header  = line_height_with_spacing;
    float separator_height = 1 + style.FramePadding.y;
    // "Text is to object" + radio buttons
    cfg.height_of_volume_type_selector = separator_height + line_height_with_spacing + input_height;
    float window_height =
        window_title + // window title
        cfg.text_size.y +  // text field
        input_height * 4 + // font name + height + depth + style selector
        tree_header +      // advance tree
        separator_height + // presets separator line
        line_height_with_spacing + // "Presets"
        2 * style.WindowPadding.y;
    float window_width = cfg.input_offset + cfg.input_width + 2*style.WindowPadding.x
        + 2 * (cfg.icon_width + space);
    cfg.minimal_window_size = ImVec2(window_width, window_height);
    // 8 = useSurface, charGap, lineGap, bold, italic, surfDist, rotation, textFaceToCamera
    // 4 = 1px for fix each edit image of drag float
    float advance_height = input_height * 8 + 8;
    cfg.minimal_window_size_with_advance =
        ImVec2(cfg.minimal_window_size.x,
               cfg.minimal_window_size.y + advance_height);
    cfg.minimal_window_size_with_collections =
        ImVec2(cfg.minimal_window_size_with_advance.x,
            cfg.minimal_window_size_with_advance.y + input_height);
    int max_style_image_width = cfg.max_style_name_width /2 -
                                2 * style.FramePadding.x;
    int max_style_image_height = 1.5 * input_height;
    cfg.max_style_image_size = Vec2i(max_style_image_width, max_style_image_height);
    cfg.face_name_size.y() = line_height_with_spacing;
    return cfg;
}
References _u8L, Slic3r::GUI::GLGizmoEmboss::GuiCfg::advanced_input_offset, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::boldness, ImGui::CalcTextSize(), Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::char_gap, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::collection, Slic3r::GUI::GLGizmoEmboss::GuiCfg::delete_pos_x, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::depth, Slic3r::GUI::GLGizmoEmboss::GuiCfg::face_name_size, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::font, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::from_surface, ImGui::GetStyle(), ImGui::GetTextLineHeight(), ImGui::GetTextLineHeightWithSpacing(), Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::height, Slic3r::GUI::GLGizmoEmboss::GuiCfg::height_of_volume_type_selector, Slic3r::GUI::GLGizmoEmboss::GuiCfg::icon_width, Slic3r::GUI::GLGizmoEmboss::GuiCfg::indent, Slic3r::GUI::GLGizmoEmboss::GuiCfg::input_offset, Slic3r::GUI::GLGizmoEmboss::GuiCfg::input_width, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::keep_up, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::line_gap, Slic3r::GUI::GLGizmoEmboss::GuiCfg::lock_offset, Slic3r::GUI::GLGizmoEmboss::GuiCfg::max_style_image_size, Slic3r::GUI::GLGizmoEmboss::GuiCfg::max_style_name_width, Slic3r::GUI::GLGizmoEmboss::GuiCfg::minimal_window_size, Slic3r::GUI::GLGizmoEmboss::GuiCfg::minimal_window_size_with_advance, Slic3r::GUI::GLGizmoEmboss::GuiCfg::minimal_window_size_with_collections, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::rotation, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::skew_ration, style, Slic3r::GUI::GLGizmoEmboss::GuiCfg::text_size, Slic3r::GUI::GLGizmoEmboss::GuiCfg::translations, Slic3r::GUI::GLGizmoEmboss::GuiCfg::Translations::use_surface, ImVec2::x, and ImVec2::y.
Referenced by on_render_input_window().
create_notification_not_valid_font() [1/2]
void GLGizmoEmboss::create_notification_not_valid_font (const std::string & text) private
{
    // not neccessary, but for sure that old notification doesnt exist
    if (m_is_unknown_font)
        remove_notification_not_valid_font();
    m_is_unknown_font = true;
    auto type  = NotificationType::UnknownFont;
    auto level = NotificationManager::NotificationLevel::WarningNotificationLevel;
    auto notification_manager = wxGetApp().plater()->get_notification_manager();
    notification_manager->push_notification(type, level, text);
}
References m_is_unknown_font, remove_notification_not_valid_font(), Slic3r::GUI::UnknownFont, and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
create_notification_not_valid_font() [2/2]
void GLGizmoEmboss::create_notification_not_valid_font (const TextConfiguration & tc) private
{
    const EmbossStyle &es = m_style_manager.get_style();
    const auto &face_name_opt = es.prop.face_name;
    const std::string &face_name_3mf = tc.style.prop.face_name.value_or(tc.style.path);
    std::optional<std::string> face_name_by_wx;
    if (!face_name_opt.has_value()) {
        const wxFont& wx_font = m_style_manager.get_wx_font();
        if (wx_font.IsOk()) {
            wxString wx_face_name = wx_font.GetFaceName();
            if (!wx_face_name.empty())
                face_name_by_wx = std::string(wx_face_name.ToUTF8().data());
        }
    }
    const std::string &face_name = face_name_opt.value_or(face_name_by_wx.value_or(es.path));
    std::string text =
        GUI::format(_L("Can't load exactly same font(\"%1%\"). "
                       "Aplication selected a similar one(\"%2%\"). "
                       "You have to specify font for enable edit text."),
                    face_name_3mf, face_name);
    create_notification_not_valid_font(text);
}
References _L, create_notification_not_valid_font(), Slic3r::FontProp::face_name, Slic3r::GUI::format(), Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::GUI::Emboss::StyleManager::get_wx_font(), m_style_manager, Slic3r::EmbossStyle::path, Slic3r::EmbossStyle::prop, and Slic3r::TextConfiguration::style.
Referenced by create_notification_not_valid_font(), on_render_input_window(), and set_volume_by_selection().
create_volume() [1/2]
void GLGizmoEmboss::create_volume (ModelVolumeType volume_type)
Create new text without given position.
Parameters
volume_type Object part / Negative volume / Modifier
{
    if (!init_create(volume_type))
        return;
    // select position by camera position and view direction
    const Selection &selection = m_parent.get_selection();
    int object_idx = selection.get_object_idx();
    Size s = m_parent.get_canvas_size();
    Vec2d screen_center(s.get_width() / 2., s.get_height() / 2.);
    DataBase emboss_data = priv::create_emboss_data_base(m_text, m_style_manager, m_job_cancel);
    const ModelObjectPtrs &objects = selection.get_model()->objects;
    bool is_simple_mode = wxGetApp().get_mode() == comSimple;
    // No selected object so create new object
    if (selection.is_empty() || object_idx < 0 || static_cast<size_t>(object_idx) >= objects.size() || is_simple_mode) {
        // create Object on center of screen
        // when ray throw center of screen not hit bed it create object on center of bed
        priv::start_create_object_job(emboss_data, screen_center);
        return;
    }
    // create volume inside of selected object
    Vec2d coor;
    const GLVolume *vol = nullptr;
    const Camera &camera = wxGetApp().plater()->get_camera();
    priv::find_closest_volume(selection, screen_center, camera, objects, &coor, &vol);
    if (vol == nullptr) {
        priv::start_create_object_job(emboss_data, screen_center);
    } else if (!priv::start_create_volume_on_surface_job(emboss_data, volume_type, coor, vol, m_raycast_manager, m_parent)) {
        // in centroid of convex hull is not hit with object
        // soo create transfomation on border of object
        // there is no point on surface so no use of surface will be applied
        FontProp &prop = emboss_data.text_configuration.style.prop;
        if (prop.use_surface)
            prop.use_surface = false;
        // Transformation is inspired add generic volumes in ObjectList::load_generic_subobject
        const ModelObject *obj = objects[vol->object_idx()];
        BoundingBoxf3 instance_bb = obj->instance_bounding_box(vol->instance_idx());
        // Translate the new modifier to be pickable: move to the left front corner of the instance's bounding box, lift to print bed.
        Transform3d tr = vol->get_instance_transformation().get_matrix_no_offset().inverse();
        Vec3d offset_tr(0, // center of instance - Can't suggest width of text before it will be created
            - instance_bb.size().y() / 2 - prop.size_in_mm / 2, // under
            prop.emboss / 2 - instance_bb.size().z() / 2 // lay on bed
        );
        Transform3d volume_trmat = tr * Eigen::Translation3d(offset_tr);
        priv::start_create_volume_job(obj, volume_trmat, emboss_data, volume_type);
    }
}
References Slic3r::comSimple, priv::create_emboss_data_base(), Slic3r::FontProp::emboss, priv::find_closest_volume(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GLVolume::get_instance_transformation(), Slic3r::Geometry::Transformation::get_matrix_no_offset(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Size::get_width(), init_create(), Slic3r::ModelObject::instance_bounding_box(), Slic3r::GLVolume::instance_idx(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::GUI::Selection::is_empty(), m_job_cancel, Slic3r::GUI::GLGizmoBase::m_parent, m_raycast_manager, m_style_manager, m_text, Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, Slic3r::EmbossStyle::prop, Slic3r::BoundingBox3Base< PointType >::size(), Slic3r::FontProp::size_in_mm, priv::start_create_object_job(), priv::start_create_volume_job(), priv::start_create_volume_on_surface_job(), Slic3r::TextConfiguration::style, Slic3r::GUI::Emboss::DataBase::text_configuration, and Slic3r::FontProp::use_surface.
create_volume() [2/2]
void GLGizmoEmboss::create_volume (ModelVolumeType volume_type, const Vec2d & mouse_pos)
Create new embossed text volume by type on position of mouse.
Parameters
volume_type Object part / Negative volume / Modifier
mouse_pos Define position of new volume
{
    if (!init_create(volume_type))
        return;
    const GLVolume *gl_volume = get_first_hovered_gl_volume(m_parent);
    DataBase emboss_data = priv::create_emboss_data_base(m_text, m_style_manager, m_job_cancel);
    bool is_simple_mode = wxGetApp().get_mode() == comSimple;
    if (gl_volume != nullptr && !is_simple_mode) {
        // Try to cast ray into scene and find object for add volume
        if (!priv::start_create_volume_on_surface_job(emboss_data, volume_type, mouse_pos, gl_volume, m_raycast_manager, m_parent)) {
            // When model is broken. It could appear that hit miss the object.
            // So add part near by in simmilar manner as right panel do
            create_volume(volume_type);
        }
    } else {
        // object is not under mouse position soo create object on plater
        priv::start_create_object_job(emboss_data, mouse_pos);
    }
}
References Slic3r::comSimple, priv::create_emboss_data_base(), create_volume(), Slic3r::GUI::get_first_hovered_gl_volume(), init_create(), m_job_cancel, Slic3r::GUI::GLGizmoBase::m_parent, m_raycast_manager, m_style_manager, m_text, priv::start_create_object_job(), and priv::start_create_volume_on_surface_job().
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_add_text(), create_volume(), and on_shortcut_key().
data_changed()
void GLGizmoEmboss::data_changed (bool is_serializing) override protected virtual
Is called when data (Selection) is changed.
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    set_volume_by_selection();
    if (!is_serializing && m_volume == nullptr)
        close();
}
References close(), m_volume, and set_volume_by_selection().
do_rotate()
void GLGizmoEmboss::do_rotate (float relative_z_angle) private
{
    assert(m_volume != nullptr);
    assert(m_volume->text_configuration.has_value());
    Selection &selection = m_parent.get_selection();
    assert(!selection.is_empty());
    selection.setup_cache();
    selection.rotate(Vec3d(0., 0., relative_z_angle), get_transformation_type(selection));
    std::string snapshot_name; // empty meand no store undo / redo
    // NOTE: it use L instead of _L macro because prefix _ is appended
    // inside function do_move
    // snapshot_name = L("Set text rotation");
    m_parent.do_rotate(snapshot_name);
}
References Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLGizmoBase::m_parent, m_volume, Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::setup_cache(), and Slic3r::ModelVolume::text_configuration.
Referenced by draw_advanced(), and fix_transformation().
do_stop_dragging()
void Slic3r::GUI::GLGizmoBase::do_stop_dragging (bool perform_mouse_cleanup) protected inherited
{
    for (auto& grabber : m_grabbers) grabber.dragging = false;
    m_dragging = false;
    // NOTE: This should be part of GLCanvas3D
    // Reset hover_id when leave window
    if (perform_mouse_cleanup) m_parent.mouse_up_cleanup();
    on_stop_dragging();
    // There is prediction that after draggign, data are changed
    // Data are updated twice also by canvas3D::reload_scene.
    // Should be fixed.
    m_parent.get_gizmos_manager().update_data();
    wxGetApp().obj_manipul()->set_dirty();
    // Let the plater know that the dragging finished, so a delayed
    // refresh of the scene with the background processing data should
    // be performed.
    m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED));
    // updates camera target constraints
    m_parent.refresh_camera_scene_box();
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_up_cleanup(), Slic3r::GUI::GLGizmoBase::on_stop_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::refresh_camera_scene_box(), and Slic3r::GUI::GLGizmosManager::update_data().
Referenced by Slic3r::GUI::GLGizmoBase::use_grabbers().
do_translate()
void GLGizmoEmboss::do_translate (const Vec3d & relative_move) private
{
    assert(m_volume != nullptr);
    assert(m_volume->text_configuration.has_value());
    Selection &selection = m_parent.get_selection();
    assert(!selection.is_empty());
    selection.setup_cache();
    selection.translate(relative_move, TransformationType::Local);
    std::string snapshot_name; // empty mean no store undo / redo
    // NOTE: it use L instead of _L macro because prefix _ is appended inside
    // function do_move
    // snapshot_name = L("Set surface distance");
    m_parent.do_move(snapshot_name);
}
References Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::TransformationType::Local, Slic3r::GUI::GLGizmoBase::m_parent, m_volume, Slic3r::GUI::Selection::setup_cache(), Slic3r::ModelVolume::text_configuration, and Slic3r::GUI::Selection::translate().
Referenced by draw_advanced(), and fix_transformation().
draw_advanced()
void GLGizmoEmboss::draw_advanced () private
{
    const auto &ff = m_style_manager.get_font_file_with_cache();
    if (!ff.has_value()) {
        ImGui::Text("%s", _u8L("Advanced options cannot be changed for the selected font.\n"
                                   "Select another font.").c_str());
        return;
    }
    FontProp &font_prop = m_style_manager.get_style().prop;
    const auto  &cn = m_style_manager.get_font_prop().collection_number;
    unsigned int font_index = (cn.has_value()) ? *cn : 0;
    const auto  &font_info  = ff.font_file->infos[font_index];
#ifdef SHOW_FONT_FILE_PROPERTY
    ImGui::SameLine();
    int cache_size = ff.has_value()? (int)ff.cache->size() : 0;
    std::string ff_property =
        "ascent=" + std::to_string(font_info.ascent) +
        ", descent=" + std::to_string(font_info.descent) +
        ", lineGap=" + std::to_string(font_info.linegap) +
        ", unitPerEm=" + std::to_string(font_info.unit_per_em) +
        ", cache(" + std::to_string(cache_size) + " glyphs)";
    if (font_file->infos.size() > 1) {
        unsigned int collection = font_prop.collection_number.has_value() ?
            *font_prop.collection_number : 0;
        ff_property += ", collect=" + std::to_string(collection+1) + "/" + std::to_string(font_file->infos.size());
    }
    m_imgui->text_colored(ImGuiWrapper::COL_GREY_DARK, ff_property);
#endif // SHOW_FONT_FILE_PROPERTY
    bool exist_change = false;
    auto &tr = m_gui_cfg->translations;
    const EmbossStyle *stored_style = nullptr;
    if (m_style_manager.exist_stored_style())
        stored_style = m_style_manager.get_stored_style();
    bool can_use_surface = (m_volume==nullptr)? false :
                        (font_prop.use_surface)? true : // already used surface must have option to uncheck
        (m_volume->get_object()->volumes.size() > 1);
    m_imgui->disabled_begin(!can_use_surface);
    const bool *def_use_surface = stored_style ?
        &stored_style->prop.use_surface : nullptr;
    if (rev_checkbox(tr.use_surface, font_prop.use_surface, def_use_surface,
                     _u8L("Revert using of model surface."))) {
        if (font_prop.use_surface) {
            // when using surface distance is not used
            font_prop.distance.reset();
            // there should be minimal embossing depth
            if (font_prop.emboss < 0.1)
                font_prop.emboss = 1;
        }
        process();
    }
    m_imgui->disabled_end(); // !can_use_surface
    // TRN EmbossGizmo: font units
    std::string units = _u8L("points");
    std::string units_fmt = "%.0f " + units;
    // input gap between characters
    auto def_char_gap = stored_style ?
        &stored_style->prop.char_gap : nullptr;
    int half_ascent = font_info.ascent / 2;
    int min_char_gap = -half_ascent, max_char_gap = half_ascent;
    if (rev_slider(tr.char_gap, font_prop.char_gap, def_char_gap, _u8L("Revert gap between characters"),
        min_char_gap, max_char_gap, units_fmt, _L("Distance between characters"))){
        // Condition prevent recalculation when insertint out of limits value by imgui input
        if (!priv::Limits::apply(font_prop.char_gap, priv::limits.char_gap) ||
            !m_volume->text_configuration->style.prop.char_gap.has_value() ||
            m_volume->text_configuration->style.prop.char_gap != font_prop.char_gap) {
            // char gap is stored inside of imgui font atlas
            m_style_manager.clear_imgui_font();
            exist_change = true;
        }
    }
    // input gap between lines
    auto def_line_gap = stored_style ?
        &stored_style->prop.line_gap : nullptr;
    int  min_line_gap = -half_ascent, max_line_gap = half_ascent;
    if (rev_slider(tr.line_gap, font_prop.line_gap, def_line_gap, _u8L("Revert gap between lines"),
        min_line_gap, max_line_gap, units_fmt, _L("Distance between lines"))){
        // Condition prevent recalculation when insertint out of limits value by imgui input
        if (!priv::Limits::apply(font_prop.line_gap, priv::limits.line_gap) ||
            !m_volume->text_configuration->style.prop.line_gap.has_value() ||
            m_volume->text_configuration->style.prop.line_gap != font_prop.line_gap) {
            // line gap is planed to be stored inside of imgui font atlas
            m_style_manager.clear_imgui_font();
            exist_change = true;
        }
    }
    // input boldness
    auto def_boldness = stored_style ?
        &stored_style->prop.boldness : nullptr;
    if (rev_slider(tr.boldness, font_prop.boldness, def_boldness, _u8L("Undo boldness"),
        priv::limits.boldness.gui.min, priv::limits.boldness.gui.max, units_fmt, _L("Tiny / Wide glyphs"))){
        if (!priv::Limits::apply(font_prop.boldness, priv::limits.boldness.values) ||
            !m_volume->text_configuration->style.prop.boldness.has_value() ||
            m_volume->text_configuration->style.prop.boldness != font_prop.boldness)
            exist_change = true;
    }
    // input italic
    auto def_skew = stored_style ?
        &stored_style->prop.skew : nullptr;
    if (rev_slider(tr.skew_ration, font_prop.skew, def_skew, _u8L("Undo letter's skew"),
        priv::limits.skew.gui.min, priv::limits.skew.gui.max, "%.2f", _L("Italic strength ratio"))){
        if (!priv::Limits::apply(font_prop.skew, priv::limits.skew.values) ||
            !m_volume->text_configuration->style.prop.skew.has_value() ||
            m_volume->text_configuration->style.prop.skew != font_prop.skew)
            exist_change = true;
    }
    // input surface distance
    bool allowe_surface_distance =
        !m_volume->text_configuration->style.prop.use_surface &&
        !m_volume->is_the_only_one_part();
    std::optional<float> &distance = font_prop.distance;
    float prev_distance = distance.has_value() ? *distance : .0f,
          min_distance = -2 * font_prop.emboss,
          max_distance = 2 * font_prop.emboss;
    auto def_distance = stored_style ?
        &stored_style->prop.distance : nullptr;
    m_imgui->disabled_begin(!allowe_surface_distance);
    const std::string undo_move_tooltip = _u8L("Undo translation");
    const wxString move_tooltip = _L("Distance of the center of the text to the model surface.");
    bool is_moved = false;
    bool use_inch = wxGetApp().app_config->get_bool("use_inches");
    if (use_inch) {
        std::optional<float> distance_inch;
        if (distance.has_value()) distance_inch = (*distance * ObjectManipulation::mm_to_in);
        std::optional<float> def_distance_inch;
        if (def_distance != nullptr) {
            if (def_distance->has_value()) def_distance_inch = ObjectManipulation::mm_to_in * (*(*def_distance));
            def_distance = &def_distance_inch;
        }
        min_distance *= ObjectManipulation::mm_to_in;
        max_distance *= ObjectManipulation::mm_to_in;
        if (rev_slider(tr.from_surface, distance_inch, def_distance, undo_move_tooltip, min_distance, max_distance, "%.3f in", move_tooltip)) {
            if (distance_inch.has_value()) {
                font_prop.distance = *distance_inch * ObjectManipulation::in_to_mm;
            } else {
                font_prop.distance.reset();
            }
            is_moved = true;
        }
    } else {
        if (rev_slider(tr.from_surface, distance, def_distance, undo_move_tooltip,
        min_distance, max_distance, "%.2f mm", move_tooltip)) is_moved = true;
    }
    if (is_moved){
        m_volume->text_configuration->style.prop.distance = font_prop.distance;
        float act_distance = font_prop.distance.has_value() ? *font_prop.distance : .0f;
        do_translate(Vec3d::UnitZ() * (act_distance - prev_distance));
    }
    m_imgui->disabled_end();
    // slider for Clock-wise angle in degress
    // stored angle is optional CCW and in radians
    // Convert stored value to degress
    // minus create clock-wise roation from CCW
    const std::optional<float> &angle_opt = m_style_manager.get_font_prop().angle;
    float angle = angle_opt.has_value() ? *angle_opt: 0.f;
    float angle_deg = static_cast<float>(-angle * 180 / M_PI);
    float def_angle_deg_val =
        (!stored_style || !stored_style->prop.angle.has_value()) ?
        0.f : (*stored_style->prop.angle * -180 / M_PI);
    float* def_angle_deg = stored_style ?
        &def_angle_deg_val : nullptr;
    if (rev_slider(tr.rotation, angle_deg, def_angle_deg, _u8L("Undo rotation"),
        priv::limits.angle.min, priv::limits.angle.max, u8"%.2f ",
                   _L("Rotate text Clock-wise."))) {
        // convert back to radians and CCW
        float angle_rad = static_cast<float>(-angle_deg * M_PI / 180.0);
        priv::to_range_pi_pi(angle_rad);
        float diff_angle = angle_rad - angle;
        do_rotate(diff_angle);
        // calc angle after rotation
        const GLVolume *gl_volume = get_selected_gl_volume(m_parent.get_selection());
        assert(gl_volume != nullptr);
        assert(m_style_manager.is_active_font());
        if (m_style_manager.is_active_font() && gl_volume != nullptr)
            m_style_manager.get_font_prop().angle = calc_up(gl_volume->world_matrix(), priv::up_limit);
        // recalculate for surface cut
        if (font_prop.use_surface)
            process();
    }
    // Keep up - lock button icon
    ImGui::SameLine(m_gui_cfg->lock_offset);
    const IconManager::Icon &icon = get_icon(m_icons, m_keep_up ? IconType::lock : IconType::unlock, IconState::activable);
    const IconManager::Icon &icon_hover = get_icon(m_icons, m_keep_up ? IconType::lock_bold : IconType::unlock_bold, IconState::activable);
    const IconManager::Icon &icon_disable = get_icon(m_icons, m_keep_up ? IconType::lock : IconType::unlock, IconState::disabled);
    if (button(icon, icon_hover, icon_disable)) {
        m_keep_up = !m_keep_up;
        if (m_keep_up) {
            // copy angle to volume
            m_volume->text_configuration->style.prop.angle = font_prop.angle;
        }
    }
    if (ImGui::IsItemHovered())
        ImGui::SetTooltip("%s", (m_keep_up?
            _u8L("Unlock the text's rotation when moving text along the object's surface."):
            _u8L("Lock the text's rotation when moving text along the object's surface.")
        ).c_str());
    // when more collection add selector
    if (ff.font_file->infos.size() > 1) {
        ImGui::Text("%s", tr.collection.c_str());
        ImGui::SameLine(m_gui_cfg->advanced_input_offset);
        ImGui::SetNextItemWidth(m_gui_cfg->input_width);
        unsigned int selected = font_prop.collection_number.has_value() ?
                               *font_prop.collection_number : 0;
        if (ImGui::BeginCombo("## Font collection", std::to_string(selected).c_str())) {
            for (unsigned int i = 0; i < ff.font_file->infos.size(); ++i) {
                ImGui::PushID(1 << (10 + i));
                bool is_selected = (i == selected);
                if (ImGui::Selectable(std::to_string(i).c_str(), is_selected)) {
                    if (i == 0) font_prop.collection_number.reset();
                    else font_prop.collection_number = i;
                    exist_change = true;
                }
                ImGui::PopID();
            }
            ImGui::EndCombo();
        } else if (ImGui::IsItemHovered()) {
            ImGui::SetTooltip("%s", _u8L("Select from True Type Collection.").c_str());
        }
    }
    if (exist_change) {
        m_style_manager.clear_glyphs_cache();
        process();
    }
    if (ImGui::Button(_u8L("Set text to face camera").c_str())) {
        assert(get_selected_volume(m_parent.get_selection()) == m_volume);
        const Camera &cam         = wxGetApp().plater()->get_camera();
        bool          use_surface = m_style_manager.get_style().prop.use_surface;
        if (priv::apply_camera_dir(cam, m_parent) && use_surface)
            process();
    } else if (ImGui::IsItemHovered()) {
        ImGui::SetTooltip("%s", _u8L("Orient the text towards the camera.").c_str());
    }
#ifdef ALLOW_DEBUG_MODE
    ImGui::Text("family = %s", (font_prop.family.has_value() ?
                                    font_prop.family->c_str() :
                                    " --- "));
    ImGui::Text("face name = %s", (font_prop.face_name.has_value() ?
                                       font_prop.face_name->c_str() :
                                       " --- "));
    ImGui::Text("style = %s",
                (font_prop.style.has_value() ? font_prop.style->c_str() :
                                                 " --- "));
    ImGui::Text("weight = %s", (font_prop.weight.has_value() ?
                                    font_prop.weight->c_str() :
                                    " --- "));
    std::string descriptor = style.path;
    ImGui::Text("descriptor = %s", descriptor.c_str());
#endif // ALLOW_DEBUG_MODE
}
References _L, _u8L, Slic3r::angle(), Slic3r::FontProp::angle, priv::Limits::angle, priv::Limits::apply(), priv::apply_camera_dir(), ImGui::BeginCombo(), Slic3r::FontProp::boldness, priv::Limits::boldness, ImGui::Button(), Slic3r::GUI::button(), Slic3r::Emboss::calc_up(), Slic3r::FontProp::char_gap, priv::Limits::char_gap, Slic3r::GUI::Emboss::StyleManager::clear_glyphs_cache(), Slic3r::GUI::Emboss::StyleManager::clear_imgui_font(), Slic3r::GUI::ImGuiWrapper::COL_GREY_DARK, Slic3r::FontProp::collection_number, Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), Slic3r::FontProp::distance, do_rotate(), do_translate(), Slic3r::FontProp::emboss, ImGui::EndCombo(), exist_change(), Slic3r::GUI::Emboss::StyleManager::exist_stored_style(), Slic3r::FontProp::face_name, Slic3r::FontProp::family, Slic3r::GUI::Emboss::StyleManager::get_font_file_with_cache(), Slic3r::GUI::Emboss::StyleManager::get_font_prop(), priv::get_icon(), Slic3r::ModelVolume::get_object(), Slic3r::GUI::get_selected_gl_volume(), Slic3r::GUI::get_selected_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Emboss::StyleManager::get_stored_style(), Slic3r::GUI::Emboss::StyleManager::get_style(), priv::Limit< T >::gui, Slic3r::GUI::ObjectManipulation::in_to_mm, Slic3r::GUI::Emboss::StyleManager::is_active_font(), Slic3r::ModelVolume::is_the_only_one_part(), ImGui::IsItemHovered(), priv::limits, Slic3r::FontProp::line_gap, priv::Limits::line_gap, m_gui_cfg, m_icons, Slic3r::GUI::GLGizmoBase::m_imgui, m_keep_up, Slic3r::GUI::GLGizmoBase::m_parent, M_PI, m_style_manager, m_volume, priv::MinMax< T >::max, Slic3r::GUI::ObjectManipulation::mm_to_in, ImGui::PopID(), process(), Slic3r::EmbossStyle::prop, ImGui::PushID(), rev_checkbox(), rev_slider(), ImGui::SameLine(), ImGui::Selectable(), ImGui::SetNextItemWidth(), ImGui::SetTooltip(), Slic3r::FontProp::skew, priv::Limits::skew, Slic3r::FontProp::style, style, ImGui::Text(), Slic3r::GUI::ImGuiWrapper::text_colored(), Slic3r::ModelVolume::text_configuration, priv::to_range_pi_pi(), priv::up_limit, Slic3r::FontProp::use_surface, priv::Limit< T >::values, Slic3r::ModelObject::volumes, Slic3r::FontProp::weight, and Slic3r::GLVolume::world_matrix().
Referenced by draw_window().
draw_bold_button()
bool GLGizmoEmboss::draw_bold_button () private
{
    const wxFont &wx_font = m_style_manager.get_wx_font();
    const auto& ff = m_style_manager.get_font_file_with_cache();
    if (!wx_font.IsOk() || !ff.has_value()) {
        draw(get_icon(m_icons, IconType::bold, IconState::disabled));
        return false;
    }
    std::optional<float> &boldness = m_style_manager.get_font_prop().boldness;
    bool is_font_bold = boldness.has_value() || WxFontUtils::is_bold(wx_font);
    if (is_font_bold) {
        // unset bold
        if (clickable(get_icon(m_icons, IconType::bold, IconState::hovered),
                      get_icon(m_icons, IconType::unbold, IconState::hovered))) {
            boldness.reset();
            if (wx_font.GetWeight() != wxFontWeight::wxFONTWEIGHT_NORMAL) {
                wxFont new_wx_font = wx_font; // copy
                new_wx_font.SetWeight(wxFontWeight::wxFONTWEIGHT_NORMAL);
                if(!m_style_manager.set_wx_font(new_wx_font))
                    return false;
            }
            return true;
        }
        if (ImGui::IsItemHovered())
            ImGui::SetTooltip("%s", _u8L("Unset bold").c_str());
    } else {
        // set bold
        if (draw_button(m_icons, IconType::bold)) {
            wxFont new_wx_font = wx_font; // copy
            auto new_ff = WxFontUtils::set_bold(new_wx_font, *ff.font_file);
            if (new_ff != nullptr) {
                if(!m_style_manager.set_wx_font(new_wx_font, std::move(new_ff)))
                    return false;
            } else {
                // bold font can't be loaded
                // set up boldness
                boldness = 20.f;
                //font_file->cache.empty();
            }
            return true;
        }
        if (ImGui::IsItemHovered())
            ImGui::SetTooltip("%s", _u8L("Set bold").c_str());
    }
    return false;
}
References _u8L, Slic3r::FontProp::boldness, Slic3r::GUI::clickable(), Slic3r::GUI::draw(), priv::draw_button(), Slic3r::GUI::Emboss::StyleManager::get_font_file_with_cache(), Slic3r::GUI::Emboss::StyleManager::get_font_prop(), priv::get_icon(), Slic3r::GUI::Emboss::StyleManager::get_wx_font(), Slic3r::GUI::WxFontUtils::is_bold(), ImGui::IsItemHovered(), m_icons, m_style_manager, Slic3r::GUI::WxFontUtils::set_bold(), Slic3r::GUI::Emboss::StyleManager::set_wx_font(), and ImGui::SetTooltip().
Referenced by draw_font_list_line().
draw_delete_style_button()
void GLGizmoEmboss::draw_delete_style_button () private
{
    bool is_stored  = m_style_manager.exist_stored_style();
    bool is_last    = m_style_manager.get_styles().size() == 1;
    bool can_delete = is_stored && !is_last;
    if (draw_button(m_icons, IconType::erase, !can_delete)) {
        std::string style_name = m_style_manager.get_style().name; // copy
        wxString dialog_title = _L("Remove style");
        size_t next_style_index = std::numeric_limits<size_t>::max();
        Plater *plater = wxGetApp().plater();
        bool exist_change = false;
        while (true) {
            // NOTE: can't use previous loaded activ index -> erase could change index
            size_t active_index = m_style_manager.get_style_index();
            next_style_index = (active_index > 0) ? active_index - 1 :
                                                   active_index + 1;
            if (next_style_index >= m_style_manager.get_styles().size()) {
                MessageDialog msg(plater, _L("Can't remove the last existing style."), dialog_title, wxICON_ERROR | wxOK);
                msg.ShowModal();
                break;
            }
            // IMPROVE: add function can_load?
            // clean unactivable styles
            if (!m_style_manager.load_style(next_style_index)) {
                m_style_manager.erase(next_style_index);
                exist_change = true;
                continue;
            }
            wxString message = GUI::format_wxstr(_L("Are you sure you want to permanently remove the \"%1%\" style?"), style_name);
            MessageDialog msg(plater, message, dialog_title, wxICON_WARNING | wxYES | wxNO);
            if (msg.ShowModal() == wxID_YES) {
                // delete style
                m_style_manager.erase(active_index);
                exist_change = true;
                process();
            } else {
                // load back style
                m_style_manager.load_style(active_index);
            }
            break;
        }
        if (exist_change)
            m_style_manager.store_styles_to_app_config(wxGetApp().app_config);
    }
    if (ImGui::IsItemHovered()) {
        const std::string &style_name = m_style_manager.get_style().name;
        std::string tooltip;
        if (can_delete)        tooltip = GUI::format(_L("Delete \"%1%\" style."), style_name);
        else if (is_last)      tooltip = GUI::format(_L("Can't delete \"%1%\". It is last style."), style_name);
        else/*if(!is_stored)*/ tooltip = GUI::format(_L("Can't delete temporary style \"%1%\"."), style_name);
        ImGui::SetTooltip("%s", tooltip.c_str());
    }
}
References _L, priv::draw_button(), Slic3r::GUI::Emboss::StyleManager::erase(), exist_change(), Slic3r::GUI::Emboss::StyleManager::exist_stored_style(), Slic3r::GUI::format(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::GUI::Emboss::StyleManager::get_style_index(), Slic3r::GUI::Emboss::StyleManager::get_styles(), ImGui::IsItemHovered(), Slic3r::GUI::Emboss::StyleManager::load_style(), m_icons, m_style_manager, Slic3r::EmbossStyle::name, Slic3r::GUI::plater(), process(), ImGui::SetTooltip(), and Slic3r::GUI::Emboss::StyleManager::store_styles_to_app_config().
Referenced by draw_style_list().
draw_depth()
void GLGizmoEmboss::draw_depth (bool use_inch) private
{
    float &value = m_style_manager.get_style().prop.emboss;
    const EmbossStyle* stored_style = m_style_manager.get_stored_style();
    const float *stored = ((stored_style)? &stored_style->prop.emboss : nullptr);
    const std::string  revert_emboss_depth = _u8L("Revert embossed depth.");
    const char *size_format = ((use_inch) ? "%.3f in" : "%.2f mm");
    const std::string  name = m_gui_cfg->translations.depth;
    if (rev_input_mm(name, value, stored, revert_emboss_depth, 0.1f, 1.f, size_format, use_inch, m_scale_depth))
        if (set_depth())
            process();
}
References _u8L, Slic3r::FontProp::emboss, Slic3r::GUI::Emboss::StyleManager::get_stored_style(), Slic3r::GUI::Emboss::StyleManager::get_style(), m_gui_cfg, m_scale_depth, m_style_manager, process(), Slic3r::EmbossStyle::prop, rev_input_mm(), and set_depth().
Referenced by draw_window().
draw_font_list()
void GLGizmoEmboss::draw_font_list () private
{
    // Set partial
    wxString actual_face_name;
    if (m_style_manager.is_active_font()) {
        const wxFont &wx_font = m_style_manager.get_wx_font();
        if (wx_font.IsOk())
            actual_face_name = wx_font.GetFaceName();
    }
    // name of actual selected font
    const char * selected = (!actual_face_name.empty()) ?
        actual_face_name.ToUTF8().data() : " --- ";
    // Do not remove font face during enumeration
    // When deletation of font appear this variable is set
    std::optional<size_t> del_index;
    // Code
    const char *popup_id = "##font_list_popup";
    const char *input_id = "##font_list_input";
    ImGui::SetNextItemWidth(m_gui_cfg->input_width);
    // change color of hint to normal text
    bool is_popup_open = ImGui::IsPopupOpen(popup_id);
    if (!is_popup_open) {
        ImGui::PushStyleColor(ImGuiCol_TextDisabled, ImGui::GetStyleColorVec4(ImGuiCol_Text));
        // Fix clearance of search input,
        // Sometime happens that search text not disapear after font select
        m_face_names.search.clear();
    }
    if (ImGui::InputTextWithHint(input_id, selected, &m_face_names.search)) {
        // update filtration result
        m_face_names.hide = std::vector<bool>(m_face_names.faces.size(), {false});
        // search to uppercase
        std::string search = m_face_names.search; // copy
        std::transform(search.begin(), search.end(), search.begin(), ::toupper);
        for (FaceName &face : m_face_names.faces) {
            size_t index = &face - &m_face_names.faces.front();
            // font name to uppercase
            std::string name(face.wx_name.ToUTF8().data());
            std::transform(name.begin(), name.end(), name.begin(), ::toupper);
            // It should use C++ 20 feature https://en.cppreference.com/w/cpp/string/basic_string/starts_with
            bool start_with = boost::starts_with(name, search);
            m_face_names.hide[index] = !start_with;
        }
    }
    if (!is_popup_open)
        ImGui::PopStyleColor(); // revert changes for hint color
    const bool is_input_text_active = ImGui::IsItemActive();
    // is_input_text_activated
    if (ImGui::IsItemActivated())
        ImGui::OpenPopup(popup_id);
    ImGui::SetNextWindowPos(ImVec2(ImGui::GetItemRectMin().x, ImGui::GetItemRectMax().y));
    ImGui::SetNextWindowSize({2*m_gui_cfg->input_width, ImGui::GetTextLineHeight()*10});
    ImGuiWindowFlags popup_flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoMove |
                                   ImGuiWindowFlags_NoResize | ImGuiWindowFlags_ChildWindow;
    if (ImGui::BeginPopup(popup_id, popup_flags))
    {
        bool set_selection_focus = false;
        if (!m_face_names.is_init) {
            init_face_names(m_face_names);
            set_selection_focus = true;
        }
        if (!m_face_names.has_truncated_names)
            init_truncated_names(m_face_names, m_gui_cfg->face_name_max_width);
        if (m_face_names.texture_id == 0)
            init_font_name_texture();
        for (FaceName &face : m_face_names.faces) {
            const wxString &wx_face_name = face.wx_name;
            size_t index = &face - &m_face_names.faces.front();
            // Filter for face names
            if (m_face_names.hide[index])
                continue;
            ImGui::PushID(index);
            ScopeGuard sg([]() { ImGui::PopID(); });
            bool is_selected = (actual_face_name == wx_face_name);
            ImVec2 selectable_size(0, m_gui_cfg->face_name_size.y());
            ImGuiSelectableFlags flags = 0;
            if (ImGui::Selectable(face.name_truncated.c_str(), is_selected, flags, selectable_size)) {
                if (!select_facename(wx_face_name)) {
                    del_index = index;
                    MessageDialog(wxGetApp().plater(), GUI::format_wxstr(_L("Font \"%1%\" can't be selected."), wx_face_name));
                }
            }
            // tooltip as full name of font face
            if (ImGui::IsItemHovered())
                ImGui::SetTooltip("%s", wx_face_name.ToUTF8().data());
            // on first draw set focus on selected font
            if (set_selection_focus && is_selected)
                ImGui::SetScrollHereY();
            draw_font_preview(face, ImGui::IsItemVisible());
        }
        if (!ImGui::IsWindowFocused() ||
            (!is_input_text_active && ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_Escape)))) {
            // closing of popup
            ImGui::CloseCurrentPopup();
        }
        ImGui::EndPopup();
    } else if (m_face_names.is_init) {
        // Just one after close combo box
        // free texture and set id to zero
        m_face_names.is_init = false;
        m_face_names.hide.clear();
        // cancel all process for generation of texture
        for (FaceName &face : m_face_names.faces)
            if (face.cancel != nullptr)
                face.cancel->store(true);
        glsafe(::glDeleteTextures(1, &m_face_names.texture_id));
        m_face_names.texture_id = 0;
        // Remove value from search input
        ImGuiWrapper::left_inputs();
        m_face_names.search.clear();
    }
    // delete unloadable face name when try to use
    if (del_index.has_value()) {
        auto face = m_face_names.faces.begin() + (*del_index);
        std::vector<wxString>& bad = m_face_names.bad;
        // sorted insert into bad fonts
        auto it = std::upper_bound(bad.begin(), bad.end(), face->wx_name);
        bad.insert(it, face->wx_name);
        m_face_names.faces.erase(face);
        // update cached file
        store(m_face_names);
    }
#ifdef ALLOW_ADD_FONT_BY_FILE
    ImGui::SameLine();
    // select font file by file browser
    if (draw_button(IconType::open_file)) {
        if (choose_true_type_file()) {
            process();
        }
    } else if (ImGui::IsItemHovered())
        ImGui::SetTooltip("Add file with font(.ttf, .ttc)");
#endif //  ALLOW_ADD_FONT_BY_FILE
#ifdef ALLOW_ADD_FONT_BY_OS_SELECTOR
    ImGui::SameLine();
    if (draw_button(IconType::system_selector)) {
        if (choose_font_by_wxdialog()) {
            process();
        }
    } else if (ImGui::IsItemHovered())
        ImGui::SetTooltip("Open dialog for choose from fonts.");
#endif //  ALLOW_ADD_FONT_BY_OS_SELECTOR
}
References _L, Slic3r::GUI::GLGizmoEmboss::Facenames::bad, ImGui::BeginPopup(), ImGui::CloseCurrentPopup(), priv::draw_button(), draw_font_preview(), ImGui::EndPopup(), Slic3r::GUI::GLGizmoEmboss::Facenames::faces, Slic3r::GUI::format_wxstr(), Slic3r::GUI::Emboss::StyleManager::get_wx_font(), ImGui::GetItemRectMax(), ImGui::GetItemRectMin(), ImGui::GetKeyIndex(), ImGui::GetStyleColorVec4(), ImGui::GetTextLineHeight(), glsafe, Slic3r::GUI::GLGizmoEmboss::Facenames::has_truncated_names, Slic3r::GUI::GLGizmoEmboss::Facenames::hide, ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiKey_Escape, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoTitleBar, init_face_names(), init_font_name_texture(), init_truncated_names(), ImGui::InputTextWithHint(), Slic3r::GUI::Emboss::StyleManager::is_active_font(), Slic3r::GUI::GLGizmoEmboss::Facenames::is_init, ImGui::IsItemActivated(), ImGui::IsItemActive(), ImGui::IsItemHovered(), ImGui::IsItemVisible(), ImGui::IsKeyPressed(), ImGui::IsPopupOpen(), ImGui::IsWindowFocused(), Slic3r::GUI::ImGuiWrapper::left_inputs(), m_face_names, m_gui_cfg, m_style_manager, ImGui::OpenPopup(), Slic3r::GUI::plater(), ImGui::PopID(), ImGui::PopStyleColor(), process(), ImGui::PushID(), ImGui::PushStyleColor(), ImGui::SameLine(), Slic3r::GUI::GLGizmoEmboss::Facenames::search, select_facename(), ImGui::Selectable(), ImGui::SetNextItemWidth(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), ImGui::SetScrollHereY(), ImGui::SetTooltip(), store(), and Slic3r::GUI::GLGizmoEmboss::Facenames::texture_id.
Referenced by draw_font_list_line().
draw_font_list_line()
void GLGizmoEmboss::draw_font_list_line () private
{
    bool exist_stored_style   = m_style_manager.exist_stored_style();
    bool exist_change_in_font = m_style_manager.is_font_changed();
    const std::string& font_text = m_gui_cfg->translations.font;
    if (exist_change_in_font || !exist_stored_style)
        ImGuiWrapper::text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, font_text);
    else
        ImGuiWrapper::text(font_text);
    ImGui::SameLine(m_gui_cfg->input_offset);
    draw_font_list();
    bool exist_change = false;
    if (!m_is_unknown_font) {
        ImGui::SameLine();
        if (draw_italic_button())
            exist_change = true;
        ImGui::SameLine();
        if (draw_bold_button())
            exist_change = true;
    } else {
        // when exist unknown font add confirmation button
        ImGui::SameLine();
        // Apply for actual selected font
        if (ImGui::Button(_u8L("Apply").c_str()))
            exist_change = true;
    }
    EmbossStyle &style = m_style_manager.get_style();
    if (exist_change_in_font) {
        ImGui::SameLine(ImGui::GetStyle().FramePadding.x);
        if (draw_button(m_icons, IconType::undo)) {
            const EmbossStyle *stored_style = m_style_manager.get_stored_style();
            style.path          = stored_style->path;
            style.prop.boldness = stored_style->prop.boldness;
            style.prop.skew     = stored_style->prop.skew;
            wxFont new_wx_font = WxFontUtils::load_wxFont(style.path);
            if (new_wx_font.IsOk() && m_style_manager.set_wx_font(new_wx_font))
                exist_change = true;
        } else if (ImGui::IsItemHovered())
            ImGui::SetTooltip("%s", _u8L("Revert font changes.").c_str());
    }
    if (exist_change) {
        m_style_manager.clear_glyphs_cache();
        process();
    }
}
References _u8L, Slic3r::FontProp::boldness, ImGui::Button(), Slic3r::GUI::Emboss::StyleManager::clear_glyphs_cache(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, draw_bold_button(), priv::draw_button(), draw_font_list(), draw_italic_button(), exist_change(), Slic3r::GUI::Emboss::StyleManager::exist_stored_style(), Slic3r::GUI::Emboss::StyleManager::get_stored_style(), Slic3r::GUI::Emboss::StyleManager::get_style(), ImGui::GetStyle(), Slic3r::GUI::Emboss::StyleManager::is_font_changed(), ImGui::IsItemHovered(), Slic3r::GUI::WxFontUtils::load_wxFont(), m_gui_cfg, m_icons, m_is_unknown_font, m_style_manager, Slic3r::EmbossStyle::path, process(), Slic3r::EmbossStyle::prop, ImGui::SameLine(), Slic3r::GUI::Emboss::StyleManager::set_wx_font(), ImGui::SetTooltip(), Slic3r::FontProp::skew, style, Slic3r::GUI::ImGuiWrapper::text(), and Slic3r::GUI::ImGuiWrapper::text_colored().
Referenced by draw_window().
draw_font_preview()
void GLGizmoEmboss::draw_font_preview (FaceName & face, bool is_visible) private
{
    // Limit for opened font files at one moment
    unsigned int &count_opened_fonts = m_face_names.count_opened_font_files;
    // Size of texture
    ImVec2 size(m_gui_cfg->face_name_size.x(), m_gui_cfg->face_name_size.y());
    float  count_cached_textures_f = static_cast<float>(m_face_names.count_cached_textures);
    std::string state_text;
    // uv0 and uv1 set to pixel 0,0 in texture
    ImVec2 uv0(0.f, 0.f), uv1(1.f / size.x, 1.f / size.y / count_cached_textures_f);
    if (face.is_created != nullptr) {
        // not created preview
        if (*face.is_created) {
            // Already created preview
            size_t texture_index = face.texture_index;
            uv0 = ImVec2(0.f, texture_index / count_cached_textures_f);
            uv1 = ImVec2(1.f, (texture_index + 1) / count_cached_textures_f);
        } else {
            // Not finished preview
            if (is_visible) {
                // when not canceled still loading
                state_text = std::string(" ") + (face.cancel->load() ?
                    _u8L("No symbol") :
                    (dots.ToStdString() + _u8L("Loading")));
            } else {
                // not finished and not visible cancel job
                face.is_created = nullptr;
                face.cancel->store(true);
            }
        }
    } else if (is_visible && count_opened_fonts < m_gui_cfg->max_count_opened_font_files) {
        ++count_opened_fonts;
        face.cancel     = std::make_shared<std::atomic_bool>(false);
        face.is_created = std::make_shared<bool>(false);
        const unsigned char gray_level = 5;
        // format type and level must match to texture data
        const GLenum format = GL_RGBA, type = GL_UNSIGNED_BYTE;
        const GLint  level = 0;
        // select next texture index
        size_t texture_index = (m_face_names.texture_index + 1) % m_face_names.count_cached_textures;
        // set previous cach as deleted
        for (FaceName &f : m_face_names.faces)
            if (f.texture_index == texture_index) {
                if (f.cancel != nullptr) f.cancel->store(true);
                f.is_created = nullptr;
            }
        m_face_names.texture_index = texture_index;
        face.texture_index         = texture_index;
        // render text to texture
        FontImageData data{
            m_text,
            face.wx_name,
            m_face_names.encoding,
            m_face_names.texture_id,
            m_face_names.texture_index,
            m_gui_cfg->face_name_size,
            gray_level,
            format,
            type,
            level,
            &count_opened_fonts,
            face.cancel,    // copy
            face.is_created // copy
        };
        auto  job    = std::make_unique<CreateFontImageJob>(std::move(data));
        auto &worker = wxGetApp().plater()->get_ui_job_worker();
        queue_job(worker, std::move(job));
    } else {
        // cant start new thread at this moment so wait in queue
        state_text = " " + dots.ToStdString() +  " " + _u8L("Queue");
    }
    if (!state_text.empty()) {
        ImGui::SameLine(m_gui_cfg->face_name_texture_offset_x);
        m_imgui->text(state_text);
    }
    ImGui::SameLine(m_gui_cfg->face_name_texture_offset_x);
    ImTextureID tex_id = (void *) (intptr_t) m_face_names.texture_id;
    ImGui::Image(tex_id, size, uv0, uv1);
}
References _u8L, Slic3r::GUI::GLGizmoEmboss::FaceName::cancel, Slic3r::GUI::GLGizmoEmboss::Facenames::count_cached_textures, Slic3r::GUI::GLGizmoEmboss::Facenames::count_opened_font_files, Slic3r::GUI::dots(), Slic3r::GUI::GLGizmoEmboss::Facenames::encoding, Slic3r::f(), Slic3r::GUI::GLGizmoEmboss::Facenames::faces, Slic3r::GUI::GLGizmoBase::format(), ImGui::Image(), Slic3r::GUI::GLGizmoEmboss::FaceName::is_created, m_face_names, m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_imgui, m_text, Slic3r::GUI::queue_job(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::GLGizmoEmboss::Facenames::texture_id, Slic3r::GUI::GLGizmoEmboss::FaceName::texture_index, Slic3r::GUI::GLGizmoEmboss::Facenames::texture_index, and Slic3r::GUI::GLGizmoEmboss::FaceName::wx_name.
Referenced by draw_font_list().
draw_height()
void GLGizmoEmboss::draw_height (bool use_inch) private
{
    float &value = m_style_manager.get_style().prop.size_in_mm;
    const EmbossStyle* stored_style = m_style_manager.get_stored_style();
    const float *stored = (stored_style != nullptr)? &stored_style->prop.size_in_mm : nullptr;
    const char *size_format = use_inch ? "%.2f in" : "%.1f mm";
    const std::string revert_text_size = _u8L("Revert text size.");
    const std::string& name = m_gui_cfg->translations.height;
    if (rev_input_mm(name, value, stored, revert_text_size, 0.1f, 1.f, size_format, use_inch, m_scale_height))
        if (set_height())
            process();
}
References _u8L, Slic3r::GUI::Emboss::StyleManager::get_stored_style(), Slic3r::GUI::Emboss::StyleManager::get_style(), m_gui_cfg, m_scale_height, m_style_manager, process(), Slic3r::EmbossStyle::prop, rev_input_mm(), set_height(), and Slic3r::FontProp::size_in_mm.
Referenced by draw_window().
draw_italic_button()
bool GLGizmoEmboss::draw_italic_button () private
{
    const wxFont &wx_font = m_style_manager.get_wx_font();
    const auto& ff = m_style_manager.get_font_file_with_cache();
    if (!wx_font.IsOk() || !ff.has_value()) {
        draw(get_icon(m_icons, IconType::italic, IconState::disabled));
        return false;
    }
    std::optional<float> &skew = m_style_manager.get_font_prop().skew;
    bool is_font_italic = skew.has_value() || WxFontUtils::is_italic(wx_font);
    if (is_font_italic) {
        // unset italic
        if (clickable(get_icon(m_icons, IconType::italic, IconState::hovered),
                      get_icon(m_icons, IconType::unitalic, IconState::hovered))) {
            skew.reset();
            if (wx_font.GetStyle() != wxFontStyle::wxFONTSTYLE_NORMAL) {
                wxFont new_wx_font = wx_font; // copy
                new_wx_font.SetStyle(wxFontStyle::wxFONTSTYLE_NORMAL);
                if(!m_style_manager.set_wx_font(new_wx_font))
                    return false;
            }
            return true;
        }
        if (ImGui::IsItemHovered())
            ImGui::SetTooltip("%s", _u8L("Unset italic").c_str());
    } else {
        // set italic
        if (draw_button(m_icons, IconType::italic)) {
            wxFont new_wx_font = wx_font; // copy
            auto new_ff = WxFontUtils::set_italic(new_wx_font, *ff.font_file);
            if (new_ff != nullptr) {
                if(!m_style_manager.set_wx_font(new_wx_font, std::move(new_ff)))
                    return false;
            } else {
                // italic font doesn't exist
                // add skew when wxFont can't set it
                skew = 0.2f;
            }
            return true;
        }
        if (ImGui::IsItemHovered())
            ImGui::SetTooltip("%s", _u8L("Set italic").c_str());
    }
    return false;
}
References _u8L, Slic3r::GUI::clickable(), Slic3r::GUI::draw(), priv::draw_button(), Slic3r::GUI::Emboss::StyleManager::get_font_file_with_cache(), Slic3r::GUI::Emboss::StyleManager::get_font_prop(), priv::get_icon(), Slic3r::GUI::Emboss::StyleManager::get_wx_font(), Slic3r::GUI::WxFontUtils::is_italic(), ImGui::IsItemHovered(), m_icons, m_style_manager, Slic3r::GUI::WxFontUtils::set_italic(), Slic3r::GUI::Emboss::StyleManager::set_wx_font(), ImGui::SetTooltip(), and Slic3r::FontProp::skew.
Referenced by draw_font_list_line().
draw_model_type()
void GLGizmoEmboss::draw_model_type () private
{
    bool is_last_solid_part = m_volume->is_the_only_one_part();
    std::string title = _u8L("Operation");
    if (is_last_solid_part) {
        ImVec4 color{.5f, .5f, .5f, 1.f};
        m_imgui->text_colored(color, title.c_str());
    } else {
        ImGui::Text("%s", title.c_str());
    }
    std::optional<ModelVolumeType> new_type;
    ModelVolumeType modifier = ModelVolumeType::PARAMETER_MODIFIER;
    ModelVolumeType negative = ModelVolumeType::NEGATIVE_VOLUME;
    ModelVolumeType part = ModelVolumeType::MODEL_PART;
    ModelVolumeType type = m_volume->type();
    //TRN EmbossOperation
    if (ImGui::RadioButton(_u8L("Join").c_str(), type == part))
        new_type = part;
    else if (ImGui::IsItemHovered())
        ImGui::SetTooltip("%s", _u8L("Click to change text into object part.").c_str());
    ImGui::SameLine();
    std::string last_solid_part_hint = _u8L("You can't change a type of the last solid part of the object.");
    if (ImGui::RadioButton(_CTX_utf8(L_CONTEXT("Cut", "EmbossOperation"), "EmbossOperation").c_str(), type == negative))
        new_type = negative;
    else if (ImGui::IsItemHovered()) {
        if (is_last_solid_part)
            ImGui::SetTooltip("%s", last_solid_part_hint.c_str());
        else if (type != negative)
            ImGui::SetTooltip("%s", _u8L("Click to change part type into negative volume.").c_str());
    }
    // In simple mode are not modifiers
    if (wxGetApp().plater()->printer_technology() != ptSLA && wxGetApp().get_mode() != ConfigOptionMode::comSimple) {
        ImGui::SameLine();
        if (ImGui::RadioButton(_u8L("Modifier").c_str(), type == modifier))
            new_type = modifier;
        else if (ImGui::IsItemHovered()) {
            if (is_last_solid_part)
                ImGui::SetTooltip("%s", last_solid_part_hint.c_str());
            else if (type != modifier)
                ImGui::SetTooltip("%s", _u8L("Click to change part type into modifier.").c_str());
        }
    }
    if (m_volume != nullptr && new_type.has_value() && !is_last_solid_part) {
        GUI_App &app    = wxGetApp();
        Plater * plater = app.plater();
        Plater::TakeSnapshot snapshot(plater, _L("Change Text Type"), UndoRedo::SnapshotType::GizmoAction);
        m_volume->set_type(*new_type);
         // Update volume position when switch from part or into part
        if (m_volume->text_configuration->style.prop.use_surface) {
            // move inside
            bool is_volume_move_inside  = (type == part);
            bool is_volume_move_outside = (*new_type == part);
            if (is_volume_move_inside || is_volume_move_outside) process();
        }
        // inspiration in ObjectList::change_part_type()
        // how to view correct side panel with objects
        ObjectList *obj_list = app.obj_list();
        wxDataViewItemArray sel = obj_list->reorder_volumes_and_get_selection(
            obj_list->get_selected_obj_idx(),
            [volume = m_volume](const ModelVolume *vol) { return vol == volume; });
        if (!sel.IsEmpty()) obj_list->select_item(sel.front());
        // NOTE: on linux, function reorder_volumes_and_get_selection call GLCanvas3D::reload_scene(refresh_immediately = false)
        // which discard m_volume pointer and set it to nullptr also selection is cleared so gizmo is automaticaly closed
        auto &mng = m_parent.get_gizmos_manager();
        if (mng.get_current_type() != GLGizmosManager::Emboss)
            mng.open_gizmo(GLGizmosManager::Emboss);
        // TODO: select volume back - Ask @Sasa
    }
}
References _CTX_utf8, _L, _u8L, Slic3r::comSimple, Slic3r::GUI::GLGizmosManager::Emboss, Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::ObjectList::get_selected_obj_idx(), Slic3r::UndoRedo::GizmoAction, Slic3r::ModelVolume::is_the_only_one_part(), ImGui::IsItemHovered(), L_CONTEXT, Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::GLGizmoBase::m_parent, m_volume, Slic3r::MODEL_PART, Slic3r::NEGATIVE_VOLUME, Slic3r::GUI::GUI_App::obj_list(), Slic3r::GUI::obj_list(), Slic3r::GUI::GLGizmosManager::open_gizmo(), Slic3r::PARAMETER_MODIFIER, Slic3r::GUI::GUI_App::plater(), Slic3r::GUI::plater(), Slic3r::GUI::printer_technology(), process(), Slic3r::ptSLA, ImGui::RadioButton(), Slic3r::GUI::ObjectList::reorder_volumes_and_get_selection(), ImGui::SameLine(), Slic3r::GUI::ObjectList::select_item(), Slic3r::ModelVolume::set_type(), ImGui::SetTooltip(), ImGui::Text(), Slic3r::GUI::ImGuiWrapper::text_colored(), Slic3r::ModelVolume::text_configuration, and Slic3r::ModelVolume::type().
Referenced by draw_window().
draw_style_add_button()
void GLGizmoEmboss::draw_style_add_button () private
{
    bool only_add_style = !m_style_manager.exist_stored_style();
    bool can_add        = true;
    if (only_add_style &&
        m_volume->text_configuration->style.type != WxFontUtils::get_actual_type())
        can_add = false;
    std::string title    = _u8L("Save as new style");
    const char *popup_id = title.c_str();
    // save as new style
    ImGui::SameLine();
    if (draw_button(m_icons, IconType::add, !can_add)) {
        if (!m_style_manager.exist_stored_style()) {
            m_style_manager.store_styles_to_app_config(wxGetApp().app_config);
        } else {
            ImGui::OpenPopup(popup_id);
        }
    } else if (ImGui::IsItemHovered()) {
        if (!can_add) {
            ImGui::SetTooltip("%s", _u8L("Only valid font can be added to style.").c_str());
        }else if (only_add_style) {
            ImGui::SetTooltip("%s", _u8L("Add style to my list.").c_str());
        } else {
            ImGui::SetTooltip("%s", _u8L("Save as new style.").c_str());
        }
    }
    if (ImGui::BeginPopupModal(popup_id, 0, ImGuiWindowFlags_AlwaysAutoResize)) {
        m_imgui->disable_background_fadeout_animation();
        draw_style_save_as_popup();
        ImGui::EndPopup();
    }
}
References _u8L, ImGui::BeginPopupModal(), Slic3r::GUI::ImGuiWrapper::disable_background_fadeout_animation(), priv::draw_button(), draw_style_save_as_popup(), ImGui::EndPopup(), Slic3r::GUI::Emboss::StyleManager::exist_stored_style(), Slic3r::GUI::WxFontUtils::get_actual_type(), ImGuiWindowFlags_AlwaysAutoResize, ImGui::IsItemHovered(), m_icons, Slic3r::GUI::GLGizmoBase::m_imgui, m_style_manager, m_volume, ImGui::OpenPopup(), ImGui::SameLine(), ImGui::SetTooltip(), Slic3r::GUI::Emboss::StyleManager::store_styles_to_app_config(), and Slic3r::ModelVolume::text_configuration.
Referenced by draw_style_list().
draw_style_list()
void GLGizmoEmboss::draw_style_list () private
{
    if (!m_style_manager.is_active_font()) return;
    const EmbossStyle *stored_style = nullptr;
    bool is_stored = m_style_manager.exist_stored_style();
    if (is_stored)
        stored_style = m_style_manager.get_stored_style();
    const EmbossStyle &actual_style = m_style_manager.get_style();
    bool is_changed = (stored_style)? !(*stored_style == actual_style) : true;
    bool is_modified = is_stored && is_changed;
    const float &max_style_name_width = m_gui_cfg->max_style_name_width;
    std::string &trunc_name = m_style_manager.get_truncated_name();
    if (trunc_name.empty()) {
        // generate trunc name
        std::string current_name = actual_style.name;
        ImGuiWrapper::escape_double_hash(current_name);
        trunc_name = ImGuiWrapper::trunc(current_name, max_style_name_width);
    }
    std::string title = _u8L("Styles");
    if (m_style_manager.exist_stored_style())
        ImGui::Text("%s", title.c_str());
    else
        ImGui::TextColored(ImGuiWrapper::COL_ORANGE_LIGHT, "%s", title.c_str());
    ImGui::SetNextItemWidth(m_gui_cfg->input_width);
    auto add_text_modify = [&is_modified](const std::string& name) {
        if (!is_modified) return name;
        return name + Preset::suffix_modified();
    };
    std::optional<size_t> selected_style_index;
    if (ImGui::BeginCombo("##style_selector", add_text_modify(trunc_name).c_str())) {
        m_style_manager.init_style_images(m_gui_cfg->max_style_image_size, m_text);
        m_style_manager.init_trunc_names(max_style_name_width);
        std::optional<std::pair<size_t,size_t>> swap_indexes;
        const std::vector<StyleManager::Item> &styles = m_style_manager.get_styles();
        for (const auto &item : styles) {
            size_t index = &item - &styles.front();
            const EmbossStyle &style = item.style;
            const std::string &actual_style_name = style.name;
            ImGui::PushID(actual_style_name.c_str());
            bool is_selected = (index == m_style_manager.get_style_index());
            ImVec2 select_size(0,m_gui_cfg->max_style_image_size.y()); // 0,0 --> calculate in draw
            const std::optional<StyleManager::StyleImage> &img = item.image;
            // allow click delete button
            ImGuiSelectableFlags_ flags = ImGuiSelectableFlags_AllowItemOverlap;
            if (ImGui::Selectable(item.truncated_name.c_str(), is_selected, flags, select_size)) {
                selected_style_index = index;
            } else if (ImGui::IsItemHovered())
                ImGui::SetTooltip("%s", actual_style_name.c_str());
            // reorder items
            if (ImGui::IsItemActive() && !ImGui::IsItemHovered()) {
                if (ImGui::GetMouseDragDelta(0).y < 0.f) {
                    if (index > 0)
                        swap_indexes = {index, index - 1};
                } else if ((index + 1) < styles.size())
                    swap_indexes = {index, index + 1};
                if (swap_indexes.has_value())
                    ImGui::ResetMouseDragDelta();
            }
            // draw style name
            if (img.has_value()) {
                ImGui::SameLine(max_style_name_width);
                ImGui::Image(img->texture_id, img->tex_size, img->uv0, img->uv1);
            }
            ImGui::PopID();
        }
        if (swap_indexes.has_value())
            m_style_manager.swap(swap_indexes->first,
                                swap_indexes->second);
        ImGui::EndCombo();
    } else {
        // do not keep in memory style images when no combo box open
        m_style_manager.free_style_images();
        if (ImGui::IsItemHovered()) {
            std::string style_name = add_text_modify(actual_style.name);
            std::string tooltip = is_modified?
                GUI::format(_L("Modified style \"%1%\""), actual_style.name):
                GUI::format(_L("Current style is \"%1%\""), actual_style.name);
            ImGui::SetTooltip(" %s", tooltip.c_str());
        }
    }
    // Check whether user wants lose actual style modification
    if (selected_style_index.has_value() && is_modified) {
        const EmbossStyle &style = m_style_manager.get_styles()[*selected_style_index].style;
        wxString message = GUI::format_wxstr(_L("Changing style to \"%1%\" will discard current style modification.\n\nWould you like to continue anyway?"), style.name);
        MessageDialog not_loaded_style_message(nullptr, message, _L("Warning"), wxICON_WARNING | wxYES | wxNO);
        if (not_loaded_style_message.ShowModal() != wxID_YES)
            selected_style_index.reset();
    }
    // selected style from combo box
    if (selected_style_index.has_value()) {
        const EmbossStyle &style = m_style_manager.get_styles()[*selected_style_index].style;
        // create copy to be able do fix transformation only when successfully load style
        FontProp act_prop = actual_style.prop;  // copy
        FontProp new_prop = style.prop;         // copy
        if (m_style_manager.load_style(*selected_style_index)) {
            fix_transformation(act_prop, new_prop);
            process();
        } else {
            wxString title   = _L("Not valid style.");
            wxString message = GUI::format_wxstr(_L("Style \"%1%\" can't be used and will be removed from a list."), style.name);
            MessageDialog not_loaded_style_message(nullptr, message, title, wxOK);
            not_loaded_style_message.ShowModal();
            m_style_manager.erase(*selected_style_index);
        }
    }
    ImGui::SameLine();
    draw_style_rename_button();
    ImGui::SameLine();
    draw_style_save_button(is_modified);
    ImGui::SameLine();
    draw_style_add_button();
    // delete button
    ImGui::SameLine();
    draw_delete_style_button();
}
References _L, _u8L, ImGui::BeginCombo(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, draw_delete_style_button(), draw_style_add_button(), draw_style_rename_button(), draw_style_save_button(), ImGui::EndCombo(), Slic3r::GUI::Emboss::StyleManager::erase(), Slic3r::GUI::ImGuiWrapper::escape_double_hash(), Slic3r::GUI::Emboss::StyleManager::exist_stored_style(), fix_transformation(), Slic3r::GUI::format(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::Emboss::StyleManager::free_style_images(), Slic3r::GUI::Emboss::StyleManager::get_stored_style(), Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::GUI::Emboss::StyleManager::get_style_index(), Slic3r::GUI::Emboss::StyleManager::get_styles(), Slic3r::GUI::Emboss::StyleManager::get_truncated_name(), ImGui::GetMouseDragDelta(), ImGui::Image(), ImGuiSelectableFlags_AllowItemOverlap, Slic3r::GUI::Emboss::StyleManager::init_style_images(), Slic3r::GUI::Emboss::StyleManager::init_trunc_names(), Slic3r::GUI::Emboss::StyleManager::is_active_font(), ImGui::IsItemActive(), ImGui::IsItemHovered(), Slic3r::GUI::Emboss::StyleManager::load_style(), m_gui_cfg, m_style_manager, m_text, Slic3r::EmbossStyle::name, ImGui::PopID(), process(), Slic3r::EmbossStyle::prop, ImGui::PushID(), ImGui::ResetMouseDragDelta(), ImGui::SameLine(), ImGui::Selectable(), ImGui::SetNextItemWidth(), ImGui::SetTooltip(), style, Slic3r::Preset::suffix_modified(), Slic3r::GUI::Emboss::StyleManager::swap(), ImGui::Text(), ImGui::TextColored(), and Slic3r::GUI::ImGuiWrapper::trunc().
Referenced by draw_window().
draw_style_rename_button()
void GLGizmoEmboss::draw_style_rename_button () private
{
    bool can_rename = m_style_manager.exist_stored_style();
    std::string title = _u8L("Rename style");
    const char * popup_id = title.c_str();
    if (priv::draw_button(m_icons, IconType::rename, !can_rename)) {
        assert(m_style_manager.get_stored_style());
        ImGui::OpenPopup(popup_id);
    }
    else if (ImGui::IsItemHovered()) {
        if (can_rename) ImGui::SetTooltip("%s", _u8L("Rename current style.").c_str());
        else            ImGui::SetTooltip("%s", _u8L("Can't rename temporary style.").c_str());
    }
    if (ImGui::BeginPopupModal(popup_id, 0, ImGuiWindowFlags_AlwaysAutoResize)) {
        m_imgui->disable_background_fadeout_animation();
        draw_style_rename_popup();
        ImGui::EndPopup();
    }
}
References _u8L, ImGui::BeginPopupModal(), Slic3r::GUI::ImGuiWrapper::disable_background_fadeout_animation(), priv::draw_button(), draw_style_rename_popup(), ImGui::EndPopup(), Slic3r::GUI::Emboss::StyleManager::exist_stored_style(), Slic3r::GUI::Emboss::StyleManager::get_stored_style(), ImGuiWindowFlags_AlwaysAutoResize, ImGui::IsItemHovered(), m_icons, Slic3r::GUI::GLGizmoBase::m_imgui, m_style_manager, ImGui::OpenPopup(), and ImGui::SetTooltip().
Referenced by draw_style_list().
draw_style_rename_popup()
void GLGizmoEmboss::draw_style_rename_popup () private
{
    std::string& new_name = m_style_manager.get_style().name;
    const std::string &old_name = m_style_manager.get_stored_style()->name;
    std::string text_in_popup = GUI::format(_L("Rename style(%1%) for embossing text"), old_name) + ": ";
    ImGui::Text("%s", text_in_popup.c_str());
    bool is_unique = true;
    for (const auto &item : m_style_manager.get_styles()) {
        const EmbossStyle &style = item.style;
        if (&style == &m_style_manager.get_style())
            continue; // could be same as original name
        if (style.name == new_name) is_unique = false;
    }
    bool allow_change = false;
    if (new_name.empty()) {
        m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_DARK, _u8L("Name can't be empty."));
    }else if (!is_unique) {
        m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_DARK, _u8L("Name has to be unique."));
    } else {
        ImGui::NewLine();
        allow_change = true;
    }
    bool store = false;
    ImGuiInputTextFlags flags = ImGuiInputTextFlags_EnterReturnsTrue;
    if (ImGui::InputText("##rename style", &new_name, flags) && allow_change) store = true;
    if (m_imgui->button(_L("OK"), ImVec2(0.f, 0.f), allow_change)) store = true;
    ImGui::SameLine();
    if (ImGui::Button(_u8L("Cancel").c_str())) {
        new_name = old_name;
        ImGui::CloseCurrentPopup();
    }
    if (store) {
        // rename style in all objects and volumes
        for (ModelObject *mo :wxGetApp().plater()->model().objects) {
            for (ModelVolume *mv : mo->volumes) {
                if (!mv->text_configuration.has_value()) continue;
                std::string& name = mv->text_configuration->style.name;
                if (name != old_name) continue;
                name = new_name;
            }
        }
        m_style_manager.rename(new_name);
        m_style_manager.store_styles_to_app_config();
        ImGui::CloseCurrentPopup();
    }
}
References _L, _u8L, ImGui::Button(), Slic3r::GUI::ImGuiWrapper::button(), ImGui::CloseCurrentPopup(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_DARK, Slic3r::GUI::format(), Slic3r::GUI::Emboss::StyleManager::get_stored_style(), Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::GUI::Emboss::StyleManager::get_styles(), ImGuiInputTextFlags_EnterReturnsTrue, ImGui::InputText(), priv::is_unique(), Slic3r::GUI::GLGizmoBase::m_imgui, m_style_manager, Slic3r::EmbossStyle::name, ImGui::NewLine(), Slic3r::GUI::Emboss::StyleManager::rename(), ImGui::SameLine(), store(), Slic3r::GUI::Emboss::StyleManager::store_styles_to_app_config(), style, ImGui::Text(), and Slic3r::GUI::ImGuiWrapper::text_colored().
Referenced by draw_style_rename_button().
draw_style_save_as_popup()
void GLGizmoEmboss::draw_style_save_as_popup () private
{
    ImGui::Text("%s", (_u8L("New name of style") +": ").c_str());
    // use name inside of volume configuration as temporary new name
    std::string &new_name = m_volume->text_configuration->style.name;
    bool is_unique = true;
    for (const auto &item : m_style_manager.get_styles())
        if (item.style.name == new_name) is_unique = false;
    bool allow_change = false;
    if (new_name.empty()) {
        m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_DARK, _u8L("Name can't be empty."));
    }else if (!is_unique) {
        m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_DARK, _u8L("Name has to be unique."));
    } else {
        ImGui::NewLine();
        allow_change = true;
    }
    bool save_style = false;
    ImGuiInputTextFlags flags = ImGuiInputTextFlags_EnterReturnsTrue;
    if (ImGui::InputText("##save as style", &new_name, flags))
        save_style = true;
    if (m_imgui->button(_L("OK"), ImVec2(0.f, 0.f), allow_change))
        save_style = true;
    ImGui::SameLine();
    if (ImGui::Button(_u8L("Cancel").c_str())){
        // write original name to volume TextConfiguration
        new_name = m_style_manager.get_style().name;
        ImGui::CloseCurrentPopup();
    }
    if (save_style && allow_change) {
        m_style_manager.add_style(new_name);
        m_style_manager.store_styles_to_app_config();
        ImGui::CloseCurrentPopup();
    }
}
References _L, _u8L, Slic3r::GUI::Emboss::StyleManager::add_style(), ImGui::Button(), Slic3r::GUI::ImGuiWrapper::button(), ImGui::CloseCurrentPopup(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_DARK, Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::GUI::Emboss::StyleManager::get_styles(), ImGuiInputTextFlags_EnterReturnsTrue, ImGui::InputText(), priv::is_unique(), Slic3r::GUI::GLGizmoBase::m_imgui, m_style_manager, m_volume, Slic3r::EmbossStyle::name, ImGui::NewLine(), ImGui::SameLine(), Slic3r::GUI::Emboss::StyleManager::store_styles_to_app_config(), ImGui::Text(), Slic3r::GUI::ImGuiWrapper::text_colored(), and Slic3r::ModelVolume::text_configuration.
Referenced by draw_style_add_button().
draw_style_save_button()
void GLGizmoEmboss::draw_style_save_button (bool is_modified) private
{
    if (draw_button(m_icons, IconType::save, !is_modified)) {
        // save styles to app config
        m_style_manager.store_styles_to_app_config();
    }else if (ImGui::IsItemHovered()) {
        std::string tooltip;
        if (!m_style_manager.exist_stored_style()) {
            tooltip = _u8L("First Add style to list.");
        } else if (is_modified) {
            tooltip = GUI::format(_L("Save %1% style"), m_style_manager.get_style().name);
        } else {
            tooltip = _u8L("No changes to save.");
        }
        ImGui::SetTooltip("%s", tooltip.c_str());
    }
}
References _L, _u8L, priv::draw_button(), Slic3r::GUI::Emboss::StyleManager::exist_stored_style(), Slic3r::GUI::format(), Slic3r::GUI::Emboss::StyleManager::get_style(), ImGui::IsItemHovered(), m_icons, m_style_manager, Slic3r::EmbossStyle::name, ImGui::SetTooltip(), and Slic3r::GUI::Emboss::StyleManager::store_styles_to_app_config().
Referenced by draw_style_list().
draw_text_input()
void GLGizmoEmboss::draw_text_input () private
{
    auto create_range_text_prep = [&mng = m_style_manager, &text = m_text, &exist_unknown = m_text_contain_unknown_glyph]() {
        auto& ff = mng.get_font_file_with_cache();
        assert(ff.has_value());
        const auto &cn = mng.get_font_prop().collection_number;
        unsigned int font_index = (cn.has_value()) ? *cn : 0;
        return create_range_text(text, *ff.font_file, font_index, &exist_unknown);
    };
    double scale = m_scale_height.has_value() ? *m_scale_height : 1.;
    ImFont *imgui_font = m_style_manager.get_imgui_font();
    if (imgui_font == nullptr) {
        // try create new imgui font
        double screen_scale = wxDisplay(wxGetApp().plater()).GetScaleFactor();
        double imgui_scale = scale * screen_scale;
        m_style_manager.create_imgui_font(create_range_text_prep(), imgui_scale);
        imgui_font = m_style_manager.get_imgui_font();
    }
    bool exist_font =
        imgui_font != nullptr &&
        imgui_font->IsLoaded() &&
        imgui_font->Scale > 0.f &&
        imgui_font->ContainerAtlas != nullptr;
    // NOTE: Symbol fonts doesn't have atlas
    // when their glyph range is out of language character range
    if (exist_font) ImGui::PushFont(imgui_font);
    // show warning about incorrectness view of font
    std::string warning_tool_tip;
    if (!exist_font) {
        warning_tool_tip = _u8L("The text cannot be written using the selected font. Please try choosing a different font.");
    } else {
        auto append_warning = [&warning_tool_tip](std::string t) {
            if (!warning_tool_tip.empty())
                warning_tool_tip += "\n";
            warning_tool_tip += t;
        };
        if (priv::is_text_empty(m_text))
            append_warning(_u8L("Embossed text cannot contain only white spaces."));
        if (m_text_contain_unknown_glyph)
            append_warning(_u8L("Text contains character glyph (represented by '?') unknown by font."));
        const FontProp &prop = m_style_manager.get_font_prop();
        if (prop.skew.has_value()) append_warning(_u8L("Text input doesn't show font skew."));
        if (prop.boldness.has_value()) append_warning(_u8L("Text input doesn't show font boldness."));
        if (prop.line_gap.has_value())
            append_warning(_u8L("Text input doesn't show gap between lines."));
        auto &ff         = m_style_manager.get_font_file_with_cache();
        float imgui_size = StyleManager::get_imgui_font_size(prop, *ff.font_file, scale);
        if (imgui_size > StyleManager::max_imgui_font_size)
            append_warning(_u8L("Too tall, diminished font height inside text input."));
        if (imgui_size < StyleManager::min_imgui_font_size)
            append_warning(_u8L("Too small, enlarged font height inside text input."));
    }
    // flag for extend font ranges if neccessary
    // ranges can't be extend during font is activ(pushed)
    std::string range_text;
    float  window_height  = ImGui::GetWindowHeight();
    float  minimal_height = get_minimal_window_size().y;
    float  extra_height   = window_height - minimal_height;
    ImVec2 input_size(m_gui_cfg->text_size.x, m_gui_cfg->text_size.y + extra_height);
    const ImGuiInputTextFlags flags = ImGuiInputTextFlags_AllowTabInput | ImGuiInputTextFlags_AutoSelectAll;
    if (ImGui::InputTextMultiline("##Text", &m_text, input_size, flags)) {
        process();
        range_text = create_range_text_prep();
    }
    if (exist_font) ImGui::PopFont();
    // warning tooltip has to be with default font
    if (!warning_tool_tip.empty()) {
        // Multiline input has hidden window for scrolling
        ImGuiWindow *input = ImGui::GetCurrentWindow()->DC.ChildWindows.front();
        const ImGuiStyle &style = ImGui::GetStyle();
        float scrollbar_width = (input->ScrollbarY) ? style.ScrollbarSize : 0.f;
        float scrollbar_height = (input->ScrollbarX) ? style.ScrollbarSize : 0.f;
        bool hovered = ImGui::IsItemHovered();
        if (hovered)
            ImGui::SetTooltip("%s", warning_tool_tip.c_str());
        ImVec2 cursor = ImGui::GetCursorPos();
        float width = ImGui::GetContentRegionAvailWidth();
        const ImVec2& padding = style.FramePadding;
        ImVec2 icon_pos(width - m_gui_cfg->icon_width - scrollbar_width + padding.x,
                        cursor.y - m_gui_cfg->icon_width - scrollbar_height - 2*padding.y);
        ImGui::SetCursorPos(icon_pos);
        draw(get_icon(m_icons, IconType::exclamation, IconState::hovered));
        ImGui::SetCursorPos(cursor);
    }
    // NOTE: must be after ImGui::font_pop()
    //          -> imgui_font has to be unused
    // IMPROVE: only extend not clear
    // Extend font ranges
    if (!range_text.empty() &&
        !m_imgui->contain_all_glyphs(imgui_font, range_text) )
        m_style_manager.clear_imgui_font();
}
References _u8L, Slic3r::FontProp::boldness, ImGuiWindowTempData::ChildWindows, Slic3r::GUI::Emboss::StyleManager::clear_imgui_font(), Slic3r::GUI::ImGuiWrapper::contain_all_glyphs(), ImFont::ContainerAtlas, Slic3r::GUI::Emboss::StyleManager::create_imgui_font(), Slic3r::Emboss::create_range_text(), ImGuiWindow::DC, Slic3r::GUI::draw(), ImVector< T >::front(), Slic3r::GUI::Emboss::StyleManager::get_font_file_with_cache(), Slic3r::GUI::Emboss::StyleManager::get_font_prop(), priv::get_icon(), Slic3r::GUI::Emboss::StyleManager::get_imgui_font(), Slic3r::GUI::Emboss::StyleManager::get_imgui_font_size(), get_minimal_window_size(), ImGui::GetContentRegionAvailWidth(), ImGui::GetCurrentWindow(), ImGui::GetCursorPos(), ImGui::GetStyle(), ImGui::GetWindowHeight(), priv::hovered, ImGuiInputTextFlags_AllowTabInput, ImGuiInputTextFlags_AutoSelectAll, input(), ImGui::InputTextMultiline(), priv::is_text_empty(), ImGui::IsItemHovered(), ImFont::IsLoaded(), Slic3r::FontProp::line_gap, m_gui_cfg, m_icons, Slic3r::GUI::GLGizmoBase::m_imgui, m_scale_height, m_style_manager, m_text, m_text_contain_unknown_glyph, Slic3r::GUI::Emboss::StyleManager::max_imgui_font_size, Slic3r::GUI::Emboss::StyleManager::min_imgui_font_size, Slic3r::GUI::plater(), ImGui::PopFont(), process(), ImGui::PushFont(), ImFont::Scale, scale(), ImGui::SetCursorPos(), ImGui::SetTooltip(), Slic3r::FontProp::skew, style, ImVec2::x, and ImVec2::y.
Referenced by draw_window().
draw_window()
void GLGizmoEmboss::draw_window () private
{
#ifdef ALLOW_DEBUG_MODE
    if (ImGui::Button("re-process")) process();
    if (ImGui::Button("add svg")) choose_svg_file();
#endif //  ALLOW_DEBUG_MODE
    // Setter of indent must be befor disable !!!
    ImGui::PushStyleVar(ImGuiStyleVar_IndentSpacing, m_gui_cfg->indent);
    ScopeGuard indent_sc([](){ ImGui::PopStyleVar(/*ImGuiStyleVar_IndentSpacing*/); });
    // Disable all except selection of font, when open text from 3mf with unknown font
    m_imgui->disabled_begin(m_is_unknown_font);
    ScopeGuard unknown_font_sc([imgui = m_imgui]() { imgui->disabled_end(/*m_is_unknown_font*/); });
    draw_text_input();
    ImGui::Indent();
        // When unknown font is inside .3mf only font selection is allowed
        m_imgui->disabled_end(/*m_is_unknown_font*/);
        draw_font_list_line();
        m_imgui->disabled_begin(m_is_unknown_font);
        bool use_inch = wxGetApp().app_config->get_bool("use_inches");
        draw_height(use_inch);
        draw_depth(use_inch);
    ImGui::Unindent();
    // close advanced style property when unknown font is selected
    if (m_is_unknown_font && m_is_advanced_edit_style)
        ImGui::SetNextTreeNodeOpen(false);
    if (ImGui::TreeNode(_u8L("Advanced").c_str())) {
        if (!m_is_advanced_edit_style) {
            set_minimal_window_size(true);
        } else {
            draw_advanced();
        }
        ImGui::TreePop();
    } else if (m_is_advanced_edit_style)
        set_minimal_window_size(false);
    ImGui::Separator();
    draw_style_list();
    // Do not select volume type, when it is text object
    if (m_volume->get_object()->volumes.size() != 1) {
        ImGui::Separator();
        draw_model_type();
    }
#ifdef SHOW_WX_FONT_DESCRIPTOR
    if (is_selected_style)
        m_imgui->text_colored(ImGuiWrapper::COL_GREY_DARK, m_style_manager.get_style().path);
#endif // SHOW_WX_FONT_DESCRIPTOR
#ifdef SHOW_CONTAIN_3MF_FIX
    if (m_volume!=nullptr &&
        m_volume->text_configuration.has_value() &&
        m_volume->text_configuration->fix_3mf_tr.has_value()) {
        ImGui::SameLine();
        m_imgui->text_colored(ImGuiWrapper::COL_GREY_DARK, ".3mf");
        if (ImGui::IsItemHovered()) {
            Transform3d &fix = *m_volume->text_configuration->fix_3mf_tr;
            std::stringstream ss;
            ss << fix.matrix();
            std::string filename = (m_volume->source.input_file.empty())? "unknown.3mf" :
                                   m_volume->source.input_file + ".3mf";
            ImGui::SetTooltip("Text configuation contain \n"
                              "Fix Transformation Matrix \n"
                              "%s\n"
                              "loaded from \"%s\" file.",
                              ss.str().c_str(), filename.c_str()
                );
        }
    }
#endif // SHOW_CONTAIN_3MF_FIX
#ifdef SHOW_ICONS_TEXTURE
    auto &t = m_icons_texture;
    ImGui::Image((void *) t.get_id(), ImVec2(t.get_width(), t.get_height()));
#endif //SHOW_ICONS_TEXTURE
#ifdef SHOW_IMGUI_ATLAS
    const auto &atlas = m_style_manager.get_atlas();
    ImGui::Image(atlas.TexID, ImVec2(atlas.TexWidth, atlas.TexHeight));
#endif // SHOW_IMGUI_ATLAS
#ifdef ALLOW_OPEN_NEAR_VOLUME
    ImGui::SameLine();
    if (ImGui::Checkbox("##ALLOW_OPEN_NEAR_VOLUME", &m_allow_open_near_volume)) {
        if (m_allow_open_near_volume)
            m_set_window_offset = priv::calc_fine_position(m_parent.get_selection(), get_minimal_window_size(), m_parent.get_canvas_size());
    } else if (ImGui::IsItemHovered()) {
        ImGui::SetTooltip("%s", ((m_allow_open_near_volume) ?
            "Fix settings position":
            "Allow floating window near text").c_str());
    }
#endif // ALLOW_FLOAT_WINDOW
 }
References _u8L, ImGui::Button(), priv::calc_fine_position(), ImGui::Checkbox(), Slic3r::GUI::ImGuiWrapper::COL_GREY_DARK, Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), draw_advanced(), draw_depth(), draw_font_list_line(), draw_height(), draw_model_type(), draw_style_list(), draw_text_input(), Slic3r::GUI::Emboss::StyleManager::get_atlas(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), get_minimal_window_size(), Slic3r::ModelVolume::get_object(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Emboss::StyleManager::get_style(), ImGui::Image(), ImGuiStyleVar_IndentSpacing, ImGui::Indent(), Slic3r::ModelVolume::Source::input_file, ImGui::IsItemHovered(), m_allow_open_near_volume, m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_imgui, m_is_advanced_edit_style, m_is_unknown_font, Slic3r::GUI::GLGizmoBase::m_parent, m_set_window_offset, m_style_manager, m_volume, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::EmbossStyle::path, ImGui::PopStyleVar(), process(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::Separator(), set_minimal_window_size(), ImGui::SetNextTreeNodeOpen(), ImGui::SetTooltip(), Slic3r::ModelVolume::source, Slic3r::GUI::ImGuiWrapper::text_colored(), Slic3r::ModelVolume::text_configuration, ImGui::TreeNode(), ImGui::TreePop(), ImGui::Unindent(), and Slic3r::ModelObject::volumes.
Referenced by on_render_input_window().
fix_transformation()
void GLGizmoEmboss::fix_transformation (const FontProp & from, const FontProp & to) private
{
    // fix Z rotation when exists difference in styles
    const std::optional<float> &f_angle_opt = from.angle;
    const std::optional<float> &t_angle_opt = to.angle;
    if (!is_approx(f_angle_opt, t_angle_opt)) {
        // fix rotation
        float f_angle = f_angle_opt.has_value() ? *f_angle_opt : .0f;
        float t_angle = t_angle_opt.has_value() ? *t_angle_opt : .0f;
        do_rotate(t_angle - f_angle);
    }
    // fix distance (Z move) when exists difference in styles
    const std::optional<float> &f_move_opt = from.distance;
    const std::optional<float> &t_move_opt = to.distance;
    if (!is_approx(f_move_opt, t_move_opt)) {
        float f_move = f_move_opt.has_value() ? *f_move_opt : .0f;
        float t_move = t_move_opt.has_value() ? *t_move_opt : .0f;
        do_translate(Vec3d::UnitZ() * (t_move - f_move));
    }
}
References Slic3r::FontProp::angle, Slic3r::FontProp::distance, do_rotate(), do_translate(), and Slic3r::is_approx().
Referenced by draw_style_list().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by draw_font_preview(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), init_font_name_texture(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), rev_input(), rev_input_mm(), rev_slider(), rev_slider(), and rev_slider().
get_action_snapshot_name()
std::string Slic3r::GUI::GLGizmoEmboss::get_action_snapshot_name () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return _u8L("Embossing actions"); }
References _u8L.
get_gizmo_entering_text()
std::string Slic3r::GUI::GLGizmoEmboss::get_gizmo_entering_text () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return _u8L("Enter emboss gizmo"); }
References _u8L.
get_gizmo_leaving_text()
std::string Slic3r::GUI::GLGizmoEmboss::get_gizmo_leaving_text () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return _u8L("Leave emboss gizmo"); }
References _u8L.
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmosManager::grabber_contains_mouse(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), and Slic3r::GUI::GLGizmoSlaSupports::on_mouse().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_minimal_window_size()
ImVec2 GLGizmoEmboss::get_minimal_window_size () const private
{
    ImVec2 res;
    if (!m_is_advanced_edit_style)
        res = m_gui_cfg->minimal_window_size;
    else if (!m_style_manager.has_collections())
        res = m_gui_cfg->minimal_window_size_with_advance;
    else
        res = m_gui_cfg->minimal_window_size_with_collections;
    bool is_object = m_volume->get_object()->volumes.size() == 1;
    if (!is_object)
        res.y += m_gui_cfg->height_of_volume_type_selector;
    return res;
}
References Slic3r::ModelVolume::get_object(), Slic3r::GUI::Emboss::StyleManager::has_collections(), m_gui_cfg, m_is_advanced_edit_style, m_style_manager, m_volume, Slic3r::ModelObject::volumes, and ImVec2::y.
Referenced by draw_text_input(), draw_window(), on_render_input_window(), on_set_state(), and set_minimal_window_size().
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    std::string out = on_get_name();
    if (!include_shortcut) return out;
    int key = get_shortcut_key();
    assert(key==NO_SHORTCUT_KEY_VALUE || (key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z));
    out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE, and Slic3r::GUI::GLGizmoBase::on_get_name().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay().
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLCanvas3D::on_mouse().
get_tooltip()
virtual std::string Slic3r::GUI::GLGizmoBase::get_tooltip () const inline virtual inherited
Mouse tooltip text.
Returns
Text to be visible in mouse tooltip
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoScale3D.
{ return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::get_tooltip().
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
Referenced by on_init().
init_create()
bool GLGizmoEmboss::init_create (ModelVolumeType volume_type) private
{
    // check valid volume type
    if (volume_type != ModelVolumeType::MODEL_PART &&
        volume_type != ModelVolumeType::NEGATIVE_VOLUME &&
        volume_type != ModelVolumeType::PARAMETER_MODIFIER){
        BOOST_LOG_TRIVIAL(error) << "Can't create embossed volume with this type: " << (int) volume_type;
        return false;
    }
    if (!is_activable()) {
        BOOST_LOG_TRIVIAL(error) << "Can't create text. Gizmo is not activabled.";
        return false;
    }
    // Check can't be inside is_activable() cause crash
    // steps to reproduce: start App -> key 't' -> key 'delete'
    if (wxGetApp().obj_list()->has_selected_cut_object()) {
        BOOST_LOG_TRIVIAL(error) << "Can't create text on cut object";
        return false;
    }
    m_style_manager.discard_style_changes();
    // set default text
    m_text = _u8L("Embossed text");
    return true;
}
References _u8L, Slic3r::GUI::Emboss::StyleManager::discard_style_changes(), error, Slic3r::GUI::GLGizmoBase::is_activable(), m_style_manager, m_text, Slic3r::MODEL_PART, Slic3r::NEGATIVE_VOLUME, Slic3r::GUI::obj_list(), and Slic3r::PARAMETER_MODIFIER.
Referenced by create_volume(), and create_volume().
init_face_names()
void GLGizmoEmboss::init_face_names (Facenames & facenames) static private
{
    Timer t("enumerate_fonts");
    if (face_names.is_init) return;
    face_names.is_init = true;
    // to reload fonts from system, when install new one
    wxFontEnumerator::InvalidateCache();
    // try load cache
    // Only not OS enumerated face has hash value 0
    if (face_names.hash == 0) {
        load(face_names);
        face_names.has_truncated_names = false;
    }
    using namespace std::chrono;
    steady_clock::time_point enumerate_start = steady_clock::now();
    ScopeGuard sg([&enumerate_start, &face_names = face_names]() {
        steady_clock::time_point enumerate_end = steady_clock::now();
        long long enumerate_duration = duration_cast<milliseconds>(enumerate_end - enumerate_start).count();
        BOOST_LOG_TRIVIAL(info) << "OS enumerate " << face_names.faces.size() << " fonts "
                                << "(+ " << face_names.bad.size() << " can't load "
                                << "= " << face_names.faces.size() + face_names.bad.size() << " fonts) "
                                << "in " << enumerate_duration << " ms\n" << concat(face_names.bad);
    });
    wxArrayString facenames = wxFontEnumerator::GetFacenames(face_names.encoding);
    size_t hash = boost::hash_range(facenames.begin(), facenames.end());
    // Zero value is used as uninitialized hash
    if (hash == 0) hash = 1;
    // check if it is same as last time
    if (face_names.hash == hash) {
        // no new installed font
        BOOST_LOG_TRIVIAL(info) << "Same FontNames hash, cache is used. "
            << "For clear cache delete file: " << get_fontlist_cache_path().string();
        return;
    }
    BOOST_LOG_TRIVIAL(info) << ((face_names.hash == 0) ?
        "FontName list is generate from scratch." :
        "Hash are different. Only previous bad fonts are used and set again as bad");
    face_names.hash = hash;
    // validation lambda
    auto is_valid_font = [encoding = face_names.encoding, bad = face_names.bad /*copy*/](const wxString &name) {
        if (name.empty()) return false;
        // vertical font start with @, we will filter it out
        // Not sure if it is only in Windows so filtering is on all platforms
        if (name[0] == '@') return false;
        // previously detected bad font
        auto it = std::lower_bound(bad.begin(), bad.end(), name);
        if (it != bad.end() && *it == name) return false;
        wxFont wx_font(wxFontInfo().FaceName(name).Encoding(encoding));
        //*
        // Faster chech if wx_font is loadable but not 100%
        // names could contain not loadable font
        if (!WxFontUtils::can_load(wx_font)) return false;
        /*/
        // Slow copy of font files to try load font
        // After this all files are loadable
        auto font_file = WxFontUtils::create_font_file(wx_font);
        if (font_file == nullptr)
            return false; // can't create font file
        // */
        return true;
    };
    face_names.faces.clear();
    face_names.bad.clear();
    face_names.faces.reserve(facenames.size());
    std::sort(facenames.begin(), facenames.end());
    for (const wxString &name : facenames) {
        if (is_valid_font(name)) {
            face_names.faces.push_back({name});
        }else{
            face_names.bad.push_back(name);
        }
    }
    assert(std::is_sorted(face_names.bad.begin(), face_names.bad.end()));
    face_names.has_truncated_names = false;
    store(face_names);
}
References Slic3r::GUI::GLGizmoEmboss::Facenames::bad, Slic3r::GUI::WxFontUtils::can_load(), concat(), Slic3r::GUI::GLGizmoEmboss::Facenames::encoding, Slic3r::GUI::GLGizmoEmboss::Facenames::faces, get_fontlist_cache_path(), Slic3r::GUI::GLGizmoEmboss::Facenames::has_truncated_names, Slic3r::GUI::GLGizmoEmboss::Facenames::hash, Slic3r::GUI::GLGizmoEmboss::Facenames::is_init, load(), and store().
Referenced by draw_font_list(), and set_volume_by_selection().
init_font_name_texture()
void GLGizmoEmboss::init_font_name_texture () private
{
    Timer t("init_font_name_texture");
    // check if already exists
    GLuint &id = m_face_names.texture_id;
    if (id != 0) return;
    // create texture for font
    GLenum target = GL_TEXTURE_2D;
    glsafe(::glGenTextures(1, &id));
    glsafe(::glBindTexture(target, id));
    glsafe(::glTexParameteri(target, GL_TEXTURE_MIN_FILTER, GL_NEAREST));
    glsafe(::glTexParameteri(target, GL_TEXTURE_MAG_FILTER, GL_NEAREST));
    const Vec2i &size = m_gui_cfg->face_name_size;
    GLint w = size.x(), h = m_face_names.count_cached_textures * size.y();
    std::vector<unsigned char> data(4*w * h, {0});
    const GLenum format = GL_RGBA, type = GL_UNSIGNED_BYTE;
    const GLint level = 0, internal_format = GL_RGBA, border = 0;
    glsafe(::glTexImage2D(target, level, internal_format, w, h, border, format, type, data.data()));
    // bind default texture
    GLuint no_texture_id = 0;
    glsafe(::glBindTexture(target, no_texture_id));
    // clear info about creation of texture - no one is initialized yet
    for (FaceName &face : m_face_names.faces) {
        face.cancel = nullptr;
        face.is_created = nullptr;
    }
    // Prepare filtration cache
    m_face_names.hide = std::vector<bool>(m_face_names.faces.size(), {false});
}
References Slic3r::GUI::GLGizmoEmboss::Facenames::count_cached_textures, Slic3r::GUI::GLGizmoEmboss::Facenames::faces, Slic3r::GUI::GLGizmoBase::format(), glsafe, Slic3r::GUI::GLGizmoEmboss::Facenames::hide, m_face_names, m_gui_cfg, and Slic3r::GUI::GLGizmoEmboss::Facenames::texture_id.
Referenced by draw_font_list().
init_icons()
void GLGizmoEmboss::init_icons () private
{
    // icon order has to match the enum IconType
    std::vector<std::string> filenames{
        "edit_button.svg",
        "delete.svg",
        "add_copies.svg",
        "save.svg",
        "undo.svg",
        "make_italic.svg",
        "make_unitalic.svg",
        "make_bold.svg",
        "make_unbold.svg",
        "search.svg",
        "open.svg",
        "exclamation.svg",
        "lock_closed.svg",  // lock,
        "lock_closed_f.svg",// lock_bold,
        "lock_open.svg",    // unlock,
        "lock_open_f.svg"   // unlock_bold,
    };
    assert(filenames.size() == static_cast<size_t>(IconType::_count));
    std::string path = resources_dir() + "/icons/";
    for (std::string &filename : filenames) filename = path + filename;
    ImVec2 size(m_gui_cfg->icon_width, m_gui_cfg->icon_width);
    auto type = IconManager::RasterType::color_wite_gray;
    m_icons = m_icon_manager.init(filenames, size, type);
}
References Slic3r::GUI::IconManager::color_wite_gray, Slic3r::GUI::IconManager::init(), m_gui_cfg, m_icon_manager, m_icons, and Slic3r::resources_dir().
Referenced by on_render_input_window().
init_truncated_names()
void GLGizmoEmboss::init_truncated_names (Facenames & face_names, float max_width) static private
{
    for (FaceName &face : face_names.faces) {
        std::string name_str(face.wx_name.ToUTF8().data());
        face.name_truncated = ImGuiWrapper::trunc(name_str, max_width);
    }
    face_names.has_truncated_names = true;
}
References Slic3r::GUI::GLGizmoEmboss::Facenames::faces, Slic3r::GUI::GLGizmoEmboss::Facenames::has_truncated_names, and Slic3r::GUI::ImGuiWrapper::trunc().
Referenced by draw_font_list().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmosManager::handle_shortcut(), init_create(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
Referenced by Slic3r::GUI::GLGizmoCut3D::gizmo_event(), and on_mouse_for_translate().
is_in_editing_mode()
virtual bool Slic3r::GUI::GLGizmoBase::is_in_editing_mode () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::on_key().
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
is_selection_rectangle_dragging()
virtual bool Slic3r::GUI::GLGizmoBase::is_selection_rectangle_dragging () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoHollow, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::on_key().
load() [1/2]
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
load() [2/2]
bool GLGizmoEmboss::load (Facenames & facenames) static private
{
    boost::filesystem::path path = get_fontlist_cache_path();
    std::string             path_str = path.string();
    if (!boost::filesystem::exists(path)) {
        BOOST_LOG_TRIVIAL(warning) << "Fontlist cache - '" << path_str << "' does not exists.";
        return false;
    }
    boost::nowide::ifstream file(path_str, std::ios::binary);
    cereal::BinaryInputArchive archive(file);
    FacenamesSerializer data;
    try {
        archive(data);
    } catch (const std::exception &ex) {
        BOOST_LOG_TRIVIAL(error) << "Failed to load fontlist cache - '" << path_str << "'. Exception: " << ex.what();
        return false;
    }
    assert(std::is_sorted(data.bad.begin(), data.bad.end()));
    assert(std::is_sorted(data.good.begin(), data.good.end()));
    facenames.hash = data.hash;
    facenames.faces.reserve(data.good.size());
    for (const wxString &face : data.good)
        facenames.faces.push_back({face});
    facenames.bad = data.bad;
    return true;
}
References error, Slic3r::GUI::GLGizmoEmboss::Facenames::faces, get_fontlist_cache_path(), and Slic3r::GUI::GLGizmoEmboss::Facenames::hash.
Referenced by init_face_names().
on_disable_grabber()
void Slic3r::GUI::GLGizmoEmboss::on_disable_grabber (unsigned int id) inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ m_rotate_gizmo.disable_grabber(); }
References Slic3r::GUI::GLGizmoRotate::disable_grabber(), and m_rotate_gizmo.
on_dragging()
void GLGizmoEmboss::on_dragging (const UpdateData & data) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ m_rotate_gizmo.dragging(data); }
References Slic3r::GUI::GLGizmoRotate::dragging(), and m_rotate_gizmo.
on_enable_grabber()
void Slic3r::GUI::GLGizmoEmboss::on_enable_grabber (unsigned int id) inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ m_rotate_gizmo.enable_grabber(); }
References Slic3r::GUI::GLGizmoRotate::enable_grabber(), and m_rotate_gizmo.
on_get_name()
std::string GLGizmoEmboss::on_get_name () const override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{ return _u8L("Emboss"); }
References _u8L.
Referenced by on_render_input_window().
on_get_requirements()
virtual CommonGizmosDataID Slic3r::GUI::GLGizmoBase::on_get_requirements () const inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoSimplify, and Slic3r::GUI::GLGizmoSlaBase.
{ return CommonGizmosDataID(0); }
Referenced by Slic3r::GUI::GLGizmoBase::get_requirements().
on_init()
bool GLGizmoEmboss::on_init () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    m_rotate_gizmo.init();
    ColorRGBA gray_color(.6f, .6f, .6f, .3f);
    m_rotate_gizmo.set_highlight_color(gray_color);
    // NOTE: It has special handling in GLGizmosManager::handle_shortcut
    m_shortcut_key = WXK_CONTROL_T;
    // initialize text styles
    m_style_manager.init(wxGetApp().app_config);
    // Set rotation gizmo upwardrotate
    m_rotate_gizmo.set_angle(PI / 2);
    return true;
}
References Slic3r::GUI::GLGizmoBase::init(), Slic3r::GUI::Emboss::StyleManager::init(), m_rotate_gizmo, Slic3r::GUI::GLGizmoBase::m_shortcut_key, m_style_manager, PI, Slic3r::GUI::GLGizmoRotate::set_angle(), and Slic3r::GUI::GLGizmoRotate::set_highlight_color().
on_is_activable()
bool Slic3r::GUI::GLGizmoEmboss::on_is_activable () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return true; };
on_is_selectable()
bool Slic3r::GUI::GLGizmoEmboss::on_is_selectable () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return false; }
on_load()
virtual void Slic3r::GUI::GLGizmoBase::on_load (cereal::BinaryInputArchive & ar) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::load().
on_mouse()
bool GLGizmoEmboss::on_mouse (const wxMouseEvent & mouse_event) override protected virtual
Rotate by text on dragging rotate grabers.
Parameters
mouse_event Information about mouse
Returns
Propagete normaly return false.
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    // not selected volume
    if (m_volume == nullptr ||
        get_model_volume(m_volume_id, m_parent.get_selection().get_model()->objects) == nullptr ||
        !m_volume->text_configuration.has_value()) return false;
    if (on_mouse_for_rotation(mouse_event)) return true;
    if (on_mouse_for_translate(mouse_event)) return true;
    on_mouse_change_selection(mouse_event);
    return false;
}
References Slic3r::GUI::Selection::get_model(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::GLGizmoBase::m_parent, m_volume, m_volume_id, Slic3r::Model::objects, on_mouse_change_selection(), on_mouse_for_rotation(), on_mouse_for_translate(), and Slic3r::ModelVolume::text_configuration.
on_mouse_change_selection()
void GLGizmoEmboss::on_mouse_change_selection (const wxMouseEvent & mouse_event) private
{
    static bool was_dragging = true;
    if ((mouse_event.LeftUp() || mouse_event.RightUp()) && !was_dragging) {
        // is hovered volume closest hovered?
        int hovered_idx = m_parent.get_first_hover_volume_idx();
        if (hovered_idx < 0)
            // unselect object
            return close();
        const GLVolumePtrs &gl_volumes = m_parent.get_volumes().volumes;
        auto hovered_idx_ = static_cast<size_t>(hovered_idx);
        if (hovered_idx_ >= gl_volumes.size())
            return close();
        const GLVolume *gl_volume = gl_volumes[hovered_idx_];
        if (gl_volume == nullptr)
            return close();
        const ModelVolume *volume = get_model_volume(*gl_volume, m_parent.get_model()->objects);
        if (volume == nullptr || !volume->text_configuration.has_value())
            // select volume without text configuration
            return close();
        // Reselection of text to another text
    }
    was_dragging = mouse_event.Dragging();
    // Hook When click on object for reselection must be on event left down not up
    if (mouse_event.LeftDown()) {
        // is hovered volume closest hovered?
        int hovered_idx = m_parent.get_first_hover_volume_idx();
        if (hovered_idx < 0)
            // Potentionaly move with camera (drag)
            return;
        const GLVolumePtrs &gl_volumes = m_parent.get_volumes().volumes;
        auto hovered_idx_ = static_cast<size_t>(hovered_idx);
        if (hovered_idx_ >= gl_volumes.size())
            return;
        const GLVolume *gl_volume = gl_volumes[hovered_idx_];
        if (gl_volume == nullptr)
            return;
        const ModelVolume *volume = get_model_volume(*gl_volume, m_parent.get_model()->objects);
        if (volume == nullptr)
            return;
        if (volume->text_configuration.has_value())
            return; // Reselection of text to another text
        // select volume without text configuration
        return close();
    }
    // Hook When drag with scene by right mouse button
    // object it is selected after drag scene !!
    if (mouse_event.RightDown()) {
        // is hovered volume closest hovered?
        int hovered_idx = m_parent.get_first_hover_volume_idx();
        if (hovered_idx < 0)
            // Potentionaly move with camera (drag)
            return;
        const GLVolumePtrs &gl_volumes = m_parent.get_volumes().volumes;
        auto hovered_idx_ = static_cast<size_t>(hovered_idx);
        if (hovered_idx_ >= gl_volumes.size())
            return;
        const GLVolume *gl_volume = gl_volumes[hovered_idx_];
        if (gl_volume == nullptr)
            return;
        const ModelVolume *volume = get_model_volume(*gl_volume, m_parent.get_model()->objects);
        if (volume == nullptr)
            return;
        // is actual selected?
        if (m_volume->id() == volume->id())
            return;
        // select volume without text configuration
        return close();
    }
}
References close(), Slic3r::GUI::GLCanvas3D::get_first_hover_volume_idx(), Slic3r::GUI::GLCanvas3D::get_model(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::GLCanvas3D::get_volumes(), Slic3r::ObjectBase::id(), Slic3r::GUI::GLGizmoBase::m_parent, m_volume, Slic3r::Model::objects, and Slic3r::GLVolumeCollection::volumes.
Referenced by on_mouse().
on_mouse_for_rotation()
bool GLGizmoEmboss::on_mouse_for_rotation (const wxMouseEvent & mouse_event) private
{
    if (mouse_event.Moving()) return false;
    bool used = use_grabbers(mouse_event);
    if (!m_dragging) return used;
    if (mouse_event.Dragging()) {
        if (!m_rotate_start_angle.has_value()) {
            // when m_rotate_start_angle is not set mean it is not Dragging
            // when angle_opt is not set mean angle is Zero
            const std::optional<float> &angle_opt = m_style_manager.get_font_prop().angle;
            m_rotate_start_angle = angle_opt.has_value() ? *angle_opt : 0.f;
        }
        double angle = m_rotate_gizmo.get_angle();
        angle -= PI / 2; // Grabber is upward
        // temporary rotation
        Selection& selection = m_parent.get_selection();
        selection.rotate(Vec3d(0., 0., angle), get_transformation_type(selection));
        angle += *m_rotate_start_angle;
        // move to range <-M_PI, M_PI>
        priv::to_range_pi_pi(angle);
        // set into activ style
        assert(m_style_manager.is_active_font());
        if (m_style_manager.is_active_font()) {
            std::optional<float> angle_opt;
            if (!is_approx(angle, 0.))
                angle_opt = angle;
            m_style_manager.get_font_prop().angle = angle_opt;
        }
    }
    return used;
}
References Slic3r::angle(), Slic3r::FontProp::angle, Slic3r::GUI::GLGizmoRotate::get_angle(), Slic3r::GUI::Emboss::StyleManager::get_font_prop(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Emboss::StyleManager::is_active_font(), Slic3r::is_approx(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_gizmo, m_rotate_start_angle, m_style_manager, PI, Slic3r::GUI::Selection::rotate(), priv::to_range_pi_pi(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
Referenced by on_mouse().
on_mouse_for_translate()
bool GLGizmoEmboss::on_mouse_for_translate (const wxMouseEvent & mouse_event) private
{
    // exist selected volume?
    if (m_volume == nullptr)
        return false;
    std::optional<double> up_limit;
    if (m_keep_up)        up_limit = priv::up_limit;
    const Camera &camera = wxGetApp().plater()->get_camera();
    bool was_dragging = m_surface_drag.has_value();
    bool res = on_mouse_surface_drag(mouse_event, camera, m_surface_drag, m_parent, m_raycast_manager, up_limit);
    bool is_dragging = m_surface_drag.has_value();
    // End with surface dragging?
    if (was_dragging && !is_dragging) {
        // Update surface by new position
        if (m_volume->text_configuration->style.prop.use_surface)
            process();
        // Show correct value of height & depth inside of inputs
        calculate_scale();
    }
    // Start with dragging
    else if (!was_dragging && is_dragging) {
        // Cancel job to prevent interuption of dragging (duplicit result)
        if (m_job_cancel != nullptr)
            m_job_cancel->store(true);
    }
    // during drag
    else if (was_dragging && is_dragging) {
        // update scale of selected volume --> should be approx the same
        calculate_scale();
        // Recalculate angle for GUI
        if (!m_keep_up) {
            const GLVolume *gl_volume = get_selected_gl_volume(m_parent.get_selection());
            assert(gl_volume != nullptr);
            assert(m_style_manager.is_active_font());
            if (gl_volume == nullptr || !m_style_manager.is_active_font())
                return res;
            m_style_manager.get_style().prop.angle = calc_up(gl_volume->world_matrix(), priv::up_limit);
        }
    }
    return res;
}
References Slic3r::FontProp::angle, Slic3r::Emboss::calc_up(), calculate_scale(), Slic3r::GUI::get_selected_gl_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::GUI::Emboss::StyleManager::is_active_font(), Slic3r::GUI::GLGizmoBase::is_dragging(), m_job_cancel, m_keep_up, Slic3r::GUI::GLGizmoBase::m_parent, m_raycast_manager, m_style_manager, m_surface_drag, m_volume, Slic3r::GUI::on_mouse_surface_drag(), process(), Slic3r::EmbossStyle::prop, Slic3r::ModelVolume::text_configuration, priv::up_limit, and Slic3r::GLVolume::world_matrix().
Referenced by on_mouse().
on_register_raycasters_for_picking()
void GLGizmoEmboss::on_register_raycasters_for_picking () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    m_rotate_gizmo.register_raycasters_for_picking();
}
References m_rotate_gizmo, and Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking().
on_render()
void GLGizmoEmboss::on_render () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    // no volume selected
    if (m_volume == nullptr ||
        get_model_volume(m_volume_id, m_parent.get_selection().get_model()->objects) == nullptr)
        return;
    Selection &selection = m_parent.get_selection();
    if (selection.is_empty()) return;
    // prevent get local coordinate system on multi volumes
    if (!selection.is_single_volume_or_modifier() &&
        !selection.is_single_volume_instance()) return;
    bool is_surface_dragging = m_surface_drag.has_value();
    bool is_parent_dragging = m_parent.is_mouse_dragging();
    // Do NOT render rotation grabbers when dragging object
    bool is_rotate_by_grabbers = m_dragging;
    if (is_rotate_by_grabbers ||
        (!is_surface_dragging && !is_parent_dragging)) {
        glsafe(::glClear(GL_DEPTH_BUFFER_BIT));
        m_rotate_gizmo.render();
    }
}
References Slic3r::GUI::Selection::get_model(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), glsafe, Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLCanvas3D::is_mouse_dragging(), Slic3r::GUI::Selection::is_single_volume_instance(), Slic3r::GUI::Selection::is_single_volume_or_modifier(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_gizmo, m_surface_drag, m_volume, m_volume_id, Slic3r::Model::objects, and Slic3r::GUI::GLGizmoBase::render().
on_render_input_window()
void GLGizmoEmboss::on_render_input_window (float x, float y, float bottom_limit) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    assert(m_volume != nullptr);
    // Do not render window for not selected text volume
    if (m_volume == nullptr ||
        get_model_volume(m_volume_id, m_parent.get_selection().get_model()->objects) == nullptr ||
        !m_volume->text_configuration.has_value()) {
        // This closing could lead to bad behavior of undo/redo stack when unselection create snapshot before close
        close();
        return;
    }
    // Not known situation when could happend this is only for sure
    if (!m_is_unknown_font && !m_style_manager.is_active_font())
        create_notification_not_valid_font("No active font in style. Select correct one.");
    else if (!m_is_unknown_font && !m_style_manager.get_wx_font().IsOk())
        create_notification_not_valid_font("WxFont is not loaded properly.");
    // Configuration creation
    double screen_scale = wxDisplay(wxGetApp().plater()).GetScaleFactor();
    float  main_toolbar_height = m_parent.get_main_toolbar_height();
    if (!m_gui_cfg.has_value() ||                   // Exist configuration - first run
        m_gui_cfg->screen_scale != screen_scale || // change of DPI
        m_gui_cfg->main_toolbar_height != main_toolbar_height // change size of view port
        ) {
        // Create cache for gui offsets
        GuiCfg cfg = create_gui_configuration();
        cfg.screen_scale = screen_scale;
        cfg.main_toolbar_height = main_toolbar_height;
        m_gui_cfg.emplace(std::move(cfg));
        // set position near toolbar
        m_set_window_offset = ImVec2(-1.f, -1.f);
        // change resolution regenerate icons
        init_icons();
        m_style_manager.clear_imgui_font();
    }
    const ImVec2 &min_window_size = get_minimal_window_size();
    ImGui::PushStyleVar(ImGuiStyleVar_WindowMinSize, min_window_size);
    // Draw origin position of text during dragging
    if (m_surface_drag.has_value()) {
        ImVec2 mouse_pos = ImGui::GetMousePos();
        ImVec2 center(
            mouse_pos.x + m_surface_drag->mouse_offset.x(),
            mouse_pos.y + m_surface_drag->mouse_offset.y());
        ImU32 color = ImGui::GetColorU32(
            m_surface_drag->exist_hit ?
                ImVec4(1.f, 1.f, 1.f, .75f) : // transparent white
                ImVec4(1.f, .3f, .3f, .75f)
        ); // Warning color
        const float radius = 16.f;
        ImGuiWrapper::draw_cross_hair(center, radius, color);
    }
#ifdef SHOW_FINE_POSITION
    draw_fine_position(m_parent.get_selection(), m_parent.get_canvas_size(), min_window_size);
#endif // SHOW_FINE_POSITION
#ifdef DRAW_PLACE_TO_ADD_TEXT
    draw_place_to_add_text();
#endif // DRAW_PLACE_TO_ADD_TEXT
#ifdef SHOW_OFFSET_DURING_DRAGGING
    draw_mouse_offset(m_dragging_mouse_offset);
#endif // SHOW_OFFSET_DURING_DRAGGING
    // check if is set window offset
    if (m_set_window_offset.has_value()) {
        if (m_set_window_offset->y < 0)
            // position near toolbar
            m_set_window_offset = ImVec2(x, std::min(y, bottom_limit - min_window_size.y));
        ImGui::SetNextWindowPos(*m_set_window_offset, ImGuiCond_Always);
        m_set_window_offset.reset();
    } else if (!m_allow_open_near_volume) {
        y = std::min(y, bottom_limit - min_window_size.y);
        // position near toolbar
        ImVec2 pos(x, y);
        ImGui::SetNextWindowPos(pos, ImGuiCond_Once);
    }
    bool is_opened = true;
    ImGuiWindowFlags flag = ImGuiWindowFlags_NoCollapse;
    if (ImGui::Begin(on_get_name().c_str(), &is_opened, flag)) {
        // Need to pop var before draw window
        ImGui::PopStyleVar(); // WindowMinSize
        draw_window();
    } else {
        ImGui::PopStyleVar(); // WindowMinSize
    }
    // after change volume from object to volume it is necessary to recalculate
    // minimal windows size because of set type
    if (m_should_set_minimal_windows_size) {
        m_should_set_minimal_windows_size = false;
        ImGui::SetWindowSize(ImVec2(0.f, min_window_size.y), ImGuiCond_Always);
    }
    ImGui::End();
    if (!is_opened)
        close();
}
References ImGui::Begin(), Slic3r::GUI::Emboss::StyleManager::clear_imgui_font(), close(), create_gui_configuration(), create_notification_not_valid_font(), Slic3r::GUI::ImGuiWrapper::draw_cross_hair(), draw_window(), ImGui::End(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::GLCanvas3D::get_main_toolbar_height(), get_minimal_window_size(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Emboss::StyleManager::get_wx_font(), ImGui::GetColorU32(), ImGui::GetMousePos(), ImGuiCond_Always, ImGuiCond_Once, ImGuiStyleVar_WindowMinSize, ImGuiWindowFlags_NoCollapse, init_icons(), Slic3r::GUI::Emboss::StyleManager::is_active_font(), m_allow_open_near_volume, m_gui_cfg, m_is_unknown_font, Slic3r::GUI::GLGizmoBase::m_parent, m_set_window_offset, m_should_set_minimal_windows_size, m_style_manager, m_surface_drag, m_volume, m_volume_id, Slic3r::GUI::GLGizmoEmboss::GuiCfg::main_toolbar_height, Slic3r::Model::objects, on_get_name(), Slic3r::GUI::plater(), ImGui::PopStyleVar(), ImGui::PushStyleVar(), Slic3r::GUI::GLGizmoEmboss::GuiCfg::screen_scale, ImGui::SetNextWindowPos(), ImGui::SetWindowSize(), Slic3r::ModelVolume::text_configuration, ImVec2::x, and ImVec2::y.
on_save()
virtual void Slic3r::GUI::GLGizmoBase::on_save (cereal::BinaryOutputArchive & ar) const inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::save().
on_set_hover_id()
void Slic3r::GUI::GLGizmoEmboss::on_set_hover_id () inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ m_rotate_gizmo.set_hover_id(m_hover_id); }
References Slic3r::GUI::GLGizmoBase::m_hover_id, m_rotate_gizmo, and Slic3r::GUI::GLGizmoBase::set_hover_id().
on_set_state()
void GLGizmoEmboss::on_set_state () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    // enable / disable bed from picking
    // Rotation gizmo must work through bed
    m_parent.set_raycaster_gizmos_on_top(m_state == GLGizmoBase::On);
    m_rotate_gizmo.set_state(m_state);
    // Closing gizmo. e.g. selecting another one
    if (m_state == GLGizmoBase::Off) {
        // refuse outgoing during text preview
        reset_volume();
        // Store order and last activ index into app.ini
        // TODO: what to do when can't store into file?
        m_style_manager.store_styles_to_app_config(false);
        remove_notification_not_valid_font();
    } else if (m_state == GLGizmoBase::On) {
        // to reload fonts from system, when install new one
        wxFontEnumerator::InvalidateCache();
        // Immediately after set state On is called function data_changed(),
        // where one could distiguish undo/redo serialization from opening by letter 'T'
        // set_volume_by_selection();
        // change position of just opened emboss window
        if (m_allow_open_near_volume) {
            m_set_window_offset = priv::calc_fine_position(m_parent.get_selection(), get_minimal_window_size(), m_parent.get_canvas_size());
        } else {
            if (m_gui_cfg.has_value())
                priv::change_window_position(m_set_window_offset, false);
            else
                m_set_window_offset = ImVec2(-1, -1);
        }
        // when open by hyperlink it needs to show up
        // or after key 'T' windows doesn't appear
        m_parent.set_as_dirty();
    }
}
References priv::calc_fine_position(), priv::change_window_position(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), get_minimal_window_size(), Slic3r::GUI::GLCanvas3D::get_selection(), m_allow_open_near_volume, m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_gizmo, m_set_window_offset, Slic3r::GUI::GLGizmoBase::m_state, m_style_manager, Slic3r::GUI::GLGizmoBase::Off, Slic3r::GUI::GLGizmoBase::On, remove_notification_not_valid_font(), reset_volume(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::GLCanvas3D::set_raycaster_gizmos_on_top(), Slic3r::GUI::GLGizmoBase::set_state(), and Slic3r::GUI::Emboss::StyleManager::store_styles_to_app_config().
on_shortcut_key()
void GLGizmoEmboss::on_shortcut_key ()
Handle pressing of shortcut.
{
    set_volume_by_selection();
    if (m_volume == nullptr) {
        // No volume to select from selection so create volume.
        // NOTE: After finish job for creation emboss Text volume,
        // GLGizmoEmboss will be opened
        create_volume(ModelVolumeType::MODEL_PART);
    } else {
        // shortcut is pressed when text is selected soo start edit it.
        auto &mng = m_parent.get_gizmos_manager();
        if (mng.get_current_type() != GLGizmosManager::Emboss)
            mng.open_gizmo(GLGizmosManager::Emboss);
    }
}
References create_volume(), Slic3r::GUI::GLGizmosManager::Emboss, Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmoBase::m_parent, m_volume, Slic3r::MODEL_PART, Slic3r::GUI::GLGizmosManager::open_gizmo(), and set_volume_by_selection().
on_start_dragging()
void GLGizmoEmboss::on_start_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ m_rotate_gizmo.start_dragging(); }
References m_rotate_gizmo, and Slic3r::GUI::GLGizmoRotate::start_dragging().
on_stop_dragging()
void GLGizmoEmboss::on_stop_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    m_rotate_gizmo.stop_dragging();
    // TODO: when start second rotatiton previous rotation rotate draggers
    // This is fast fix for second try to rotate
    // When fixing, move grabber above text (not on side)
    m_rotate_gizmo.set_angle(PI/2);
    // apply rotation
    m_parent.do_rotate(L("Text-Rotate"));
    // Re-Calculate current angle of up vector
    const GLVolume *gl_volume = get_selected_gl_volume(m_parent.get_selection());
    assert(m_style_manager.is_active_font());
    assert(gl_volume != nullptr);
    if (m_style_manager.is_active_font() && gl_volume != nullptr)
        m_style_manager.get_font_prop().angle = calc_up(gl_volume->world_matrix(), priv::up_limit);
    m_rotate_start_angle.reset();
    // recalculate for surface cut
    const FontProp &font_prop = m_style_manager.get_style().prop;
    if (font_prop.use_surface) process();
}
References Slic3r::FontProp::angle, Slic3r::Emboss::calc_up(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::Emboss::StyleManager::get_font_prop(), Slic3r::GUI::get_selected_gl_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::GUI::Emboss::StyleManager::is_active_font(), L, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_gizmo, m_rotate_start_angle, m_style_manager, PI, process(), Slic3r::EmbossStyle::prop, Slic3r::GUI::GLGizmoRotate::set_angle(), Slic3r::GUI::GLGizmoRotate::stop_dragging(), priv::up_limit, Slic3r::FontProp::use_surface, and Slic3r::GLVolume::world_matrix().
on_unregister_raycasters_for_picking()
void GLGizmoEmboss::on_unregister_raycasters_for_picking () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    m_rotate_gizmo.unregister_raycasters_for_picking();
}
References m_rotate_gizmo, and Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking().
process()
bool GLGizmoEmboss::process () private
{
    // no volume is selected -> selection from right panel
    assert(m_volume != nullptr);
    if (m_volume == nullptr) return false;
    // without text there is nothing to emboss
    if (m_text.empty()) return false;
    // exist loaded font file?
    if (!m_style_manager.is_active_font()) return false;
    DataUpdate data{priv::create_emboss_data_base(m_text, m_style_manager, m_job_cancel), m_volume->id()};
    std::unique_ptr<Job> job = nullptr;
    // check cutting from source mesh
    bool &use_surface = data.text_configuration.style.prop.use_surface;
    bool  is_object   = m_volume->get_object()->volumes.size() == 1;
    if (use_surface && is_object)
        use_surface = false;
    if (use_surface) {
        // Model to cut surface from.
        SurfaceVolumeData::ModelSources sources = create_volume_sources(m_volume);
        if (sources.empty()) return false;
        Transform3d text_tr = m_volume->get_matrix();
        auto& fix_3mf = m_volume->text_configuration->fix_3mf_tr;
        if (fix_3mf.has_value())
            text_tr = text_tr * fix_3mf->inverse();
        // when it is new applying of use surface than move origin onto surfaca
        if (!m_volume->text_configuration->style.prop.use_surface) {
            auto offset = calc_surface_offset(m_parent.get_selection(), m_raycast_manager);
            if (offset.has_value())
                text_tr *= Eigen::Translation<double, 3>(*offset);
        }
        bool is_outside = m_volume->is_model_part();
        // check that there is not unexpected volume type
        assert(is_outside || m_volume->is_negative_volume() ||
               m_volume->is_modifier());
        UpdateSurfaceVolumeData surface_data{std::move(data), {text_tr, is_outside, std::move(sources)}};
        job = std::make_unique<UpdateSurfaceVolumeJob>(std::move(surface_data));
    } else {
        job = std::make_unique<UpdateJob>(std::move(data));
    }
#ifndef EXECUTE_PROCESS_ON_MAIN_THREAD
    auto &worker = wxGetApp().plater()->get_ui_job_worker();
    queue_job(worker, std::move(job));
#else
    // Run Job on main thread (blocking) - ONLY DEBUG
    priv::execute_job(std::move(job));
#endif // EXECUTE_PROCESS_ON_MAIN_THREAD
    // notification is removed befor object is changed by job
    remove_notification_not_valid_font();
    return true;
}
References Slic3r::GUI::calc_surface_offset(), priv::create_emboss_data_base(), Slic3r::GUI::Emboss::create_volume_sources(), Slic3r::ModelVolume::get_matrix(), Slic3r::ModelVolume::get_object(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::ObjectBase::id(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::GUI::Emboss::StyleManager::is_active_font(), Slic3r::ModelVolume::is_model_part(), Slic3r::ModelVolume::is_modifier(), Slic3r::ModelVolume::is_negative_volume(), m_job_cancel, Slic3r::GUI::GLGizmoBase::m_parent, m_raycast_manager, m_style_manager, m_text, m_volume, Slic3r::offset(), Slic3r::GUI::queue_job(), remove_notification_not_valid_font(), Slic3r::ModelVolume::text_configuration, and Slic3r::ModelObject::volumes.
Referenced by draw_advanced(), draw_delete_style_button(), draw_depth(), draw_font_list(), draw_font_list_line(), draw_height(), draw_model_type(), draw_style_list(), draw_text_input(), draw_window(), on_mouse_for_translate(), on_stop_dragging(), and select_facename().
register_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].register_raycasters_for_picking((m_group_id >= 0) ? m_group_id : i);
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking().
register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking () inline inherited
{ register_grabbers_for_picking(); on_register_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_register_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), on_register_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
remove_notification_not_valid_font()
void GLGizmoEmboss::remove_notification_not_valid_font () private
{
    if (!m_is_unknown_font) return;
    m_is_unknown_font      = false;
    auto type                 = NotificationType::UnknownFont;
    auto notification_manager = wxGetApp().plater()->get_notification_manager();
    notification_manager->close_notification_of_type(type);
}
References m_is_unknown_font, and Slic3r::GUI::UnknownFont.
Referenced by create_notification_not_valid_font(), on_set_state(), process(), reset_volume(), and set_volume_by_selection().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ on_render(); }
References Slic3r::GUI::GLGizmoBase::on_render().
Referenced by on_render().
render_grabbers() [1/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
}
References Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointType >::size().
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    render_grabbers(0, m_grabbers.size() - 1, size, false);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [3/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (size_t first, size_t last, float size, bool force_hover) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    glsafe(::glDisable(GL_CULL_FACE));
    for (size_t i = first; i <= last; ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(force_hover ? true : m_hover_id == (int)i, size);
    }
    glsafe(::glEnable(GL_CULL_FACE));
    shader->stop_using();
}
References glsafe, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // imgui windows that don't have an initial size needs to be processed once to get one
        // and are not rendered in the first frame
        // so, we forces to render another frame the first time the imgui window is shown
        // https://github.com/ocornut/imgui/issues/2949
        m_parent.set_as_dirty();
        m_parent.request_extra_frame();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), Slic3r::GUI::GLCanvas3D::request_extra_frame(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
reset_volume()
void GLGizmoEmboss::reset_volume () private
{
    if (m_volume == nullptr)
        return; // already reseted
    m_volume = nullptr;
    m_volume_id.id = 0;
    // No more need of current notification
    remove_notification_not_valid_font();
}
References Slic3r::ObjectID::id, m_volume, m_volume_id, and remove_notification_not_valid_font().
Referenced by on_set_state(), and set_volume_by_selection().
rev_checkbox()
bool GLGizmoEmboss::rev_checkbox (const std::string & name, bool & value, const bool * default_value, const std::string & undo_tooltip) private
{
    // draw offseted input
    auto draw_offseted_input = [&]() -> bool {
        ImGui::SameLine(m_gui_cfg->advanced_input_offset);
        return ImGui::Checkbox(("##" + name).c_str(), &value);
    };
    float undo_offset  = ImGui::GetStyle().FramePadding.x;
    return revertible(name, value, default_value, undo_tooltip,
                      undo_offset, draw_offseted_input);
}
References ImGui::Checkbox(), ImGuiStyle::FramePadding, ImGui::GetStyle(), m_gui_cfg, revertible(), ImGui::SameLine(), and ImVec2::x.
Referenced by draw_advanced().
rev_input()
bool GLGizmoEmboss::rev_input (const std::string & name, float & value, const float * default_value, const std::string & undo_tooltip, float step, float step_fast, const char * format, ImGuiInputTextFlags flags = 0) private
Reversible input float with option to restor default value TODO: make more general, static and move to ImGuiWrapper.
Returns
True when value changed otherwise FALSE.
{
    // draw offseted input
    auto draw_offseted_input = [&]()->bool{
        float input_offset = m_gui_cfg->input_offset;
        float input_width  = m_gui_cfg->input_width;
        ImGui::SameLine(input_offset);
        ImGui::SetNextItemWidth(input_width);
        return ImGui::InputFloat(("##" + name).c_str(),
            &value, step, step_fast, format, flags);
    };
    float undo_offset = ImGui::GetStyle().FramePadding.x;
    return revertible(name, value, default_value, undo_tooltip, undo_offset, draw_offseted_input);
}
References Slic3r::GUI::GLGizmoBase::format(), ImGuiStyle::FramePadding, ImGui::GetStyle(), ImGui::InputFloat(), m_gui_cfg, revertible(), ImGui::SameLine(), ImGui::SetNextItemWidth(), and ImVec2::x.
Referenced by rev_input_mm().
rev_input_mm()
bool GLGizmoEmboss::rev_input_mm (const std::string & name, float & value, const float * default_value, const std::string & undo_tooltip, float step, float step_fast, const char * format, bool use_inch, const std::optional< float > & scale) private
{
    // _variable which temporary keep value
    float  value_ = value;
    float  default_value_;
    if (use_inch) {
        // calc value in inch
        value_ *= ObjectManipulation::mm_to_in;
        if (default_value_ptr) {
            default_value_    = ObjectManipulation::mm_to_in * (*default_value_ptr);
            default_value_ptr = &default_value_;
        }
    }
    if (scale.has_value())
        value_ *= *scale;
    bool use_correction = use_inch || scale.has_value();
    if (rev_input(name, use_correction ? value_ : value, default_value_ptr, undo_tooltip, step, step_fast, format)) {
        if (use_correction) {
            value = value_;
            if (use_inch)
                value *= ObjectManipulation::in_to_mm;
            if (scale.has_value())
                value /= *scale;
        }
        return true;
    }
    return false;
}
References Slic3r::GUI::GLGizmoBase::format(), Slic3r::GUI::ObjectManipulation::in_to_mm, Slic3r::GUI::ObjectManipulation::mm_to_in, rev_input(), and scale().
Referenced by draw_depth(), and draw_height().
rev_slider() [1/3]
bool GLGizmoEmboss::rev_slider (const std::string & name, float & value, const float * default_value, const std::string & undo_tooltip, float v_min, float v_max, const std::string & format, const wxString & tooltip) private
{
    auto draw_slider_float = [&]() -> bool {
        float slider_offset = m_gui_cfg->advanced_input_offset;
        float slider_width  = m_gui_cfg->input_width;
        ImGui::SameLine(slider_offset);
        ImGui::SetNextItemWidth(slider_width);
        return m_imgui->slider_float("##" + name, &value, v_min, v_max,
            format.c_str(), 1.f, false, tooltip);
    };
    float undo_offset = ImGui::GetStyle().FramePadding.x;
    return revertible(name, value, default_value,
        undo_tooltip, undo_offset, draw_slider_float);
}
References Slic3r::GUI::GLGizmoBase::format(), ImGuiStyle::FramePadding, ImGui::GetStyle(), m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_imgui, revertible(), ImGui::SameLine(), ImGui::SetNextItemWidth(), Slic3r::GUI::ImGuiWrapper::slider_float(), and ImVec2::x.
rev_slider() [2/3]
bool GLGizmoEmboss::rev_slider (const std::string & name, std::optional< float > & value, const std::optional< float > * default_value, const std::string & undo_tooltip, float v_min, float v_max, const std::string & format, const wxString & tooltip) private
{
    auto draw_slider_optional_float = [&]() -> bool {
        float slider_offset = m_gui_cfg->advanced_input_offset;
        float slider_width  = m_gui_cfg->input_width;
        ImGui::SameLine(slider_offset);
        ImGui::SetNextItemWidth(slider_width);
        return m_imgui->slider_optional_float(("##" + name).c_str(), value,
            v_min, v_max, format.c_str(), 1.f, false, tooltip);
    };
    float undo_offset = ImGui::GetStyle().FramePadding.x;
    return revertible(name, value, default_value,
        undo_tooltip, undo_offset, draw_slider_optional_float);
}
References Slic3r::GUI::GLGizmoBase::format(), ImGuiStyle::FramePadding, ImGui::GetStyle(), m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_imgui, revertible(), ImGui::SameLine(), ImGui::SetNextItemWidth(), Slic3r::GUI::ImGuiWrapper::slider_optional_float(), and ImVec2::x.
rev_slider() [3/3]
bool GLGizmoEmboss::rev_slider (const std::string & name, std::optional< int > & value, const std::optional< int > * default_value, const std::string & undo_tooltip, int v_min, int v_max, const std::string & format, const wxString & tooltip) private
{
    auto draw_slider_optional_int = [&]() -> bool {
        float slider_offset = m_gui_cfg->advanced_input_offset;
        float slider_width  = m_gui_cfg->input_width;
        ImGui::SameLine(slider_offset);
        ImGui::SetNextItemWidth(slider_width);
        return m_imgui->slider_optional_int( ("##" + name).c_str(), value,
            v_min, v_max, format.c_str(), 1.f, false, tooltip);
    };
    float undo_offset = ImGui::GetStyle().FramePadding.x;
    return revertible(name, value, default_value,
        undo_tooltip, undo_offset, draw_slider_optional_int);
}
References Slic3r::GUI::GLGizmoBase::format(), ImGuiStyle::FramePadding, ImGui::GetStyle(), m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_imgui, revertible(), ImGui::SameLine(), ImGui::SetNextItemWidth(), Slic3r::GUI::ImGuiWrapper::slider_optional_int(), and ImVec2::x.
Referenced by draw_advanced().
revertible()
template<typename T , typename Draw > bool GLGizmoEmboss::revertible (const std::string & name, T & value, const T * default_value, const std::string & undo_tooltip, float undo_offset, Draw draw) private
{
    bool changed = exist_change(value, default_value);
    if (changed || default_value == nullptr)
        ImGuiWrapper::text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, name);
    else
        ImGuiWrapper::text(name);
    bool result = draw();
    // render revert changes button
    if (changed) {
        ImGui::SameLine(undo_offset);
        if (draw_button(m_icons, IconType::undo)) {
            value = *default_value;
            return true;
        } else if (ImGui::IsItemHovered())
            ImGui::SetTooltip("%s", undo_tooltip.c_str());
    }
    return result;
}
References Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, Slic3r::GUI::draw(), priv::draw_button(), exist_change(), ImGui::IsItemHovered(), m_icons, ImGui::SameLine(), ImGui::SetTooltip(), Slic3r::GUI::ImGuiWrapper::text(), and Slic3r::GUI::ImGuiWrapper::text_colored().
Referenced by rev_checkbox(), rev_input(), rev_slider(), rev_slider(), and rev_slider().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
select_facename()
bool GLGizmoEmboss::select_facename (const wxString & facename) private
{
    if (!wxFontEnumerator::IsValidFacename(facename)) return false;
    // Select font
    const wxFontEncoding &encoding = m_face_names.encoding;
    wxFont wx_font(wxFontInfo().FaceName(facename).Encoding(encoding));
    if (!wx_font.IsOk()) return false;
#ifdef USE_PIXEL_SIZE_IN_WX_FONT
    // wx font could change source file by size of font
    int point_size = static_cast<int>(m_style_manager.get_font_prop().size_in_mm);
    wx_font.SetPointSize(point_size);
#endif // USE_PIXEL_SIZE_IN_WX_FONT
    if (!m_style_manager.set_wx_font(wx_font)) return false;
    process();
    return true;
}
References Slic3r::GUI::GLGizmoEmboss::Facenames::encoding, Slic3r::GUI::Emboss::StyleManager::get_font_prop(), m_face_names, m_style_manager, process(), Slic3r::GUI::Emboss::StyleManager::set_wx_font(), and Slic3r::FontProp::size_in_mm.
Referenced by draw_font_list().
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c.
set_depth()
bool GLGizmoEmboss::set_depth () private
{
    float &value = m_style_manager.get_style().prop.emboss;
    // size can't be zero or negative
    priv::Limits::apply(value, priv::limits.emboss);
    // only different value need process
    return !is_approx(value, m_volume->text_configuration->style.prop.emboss);
}
References priv::Limits::apply(), Slic3r::FontProp::emboss, Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::is_approx(), priv::limits, m_style_manager, m_volume, Slic3r::EmbossStyle::prop, and Slic3r::ModelVolume::text_configuration.
Referenced by draw_depth().
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by Slic3r::GUI::GLGizmoCut3D::process_cut_line(), and Slic3r::GUI::GLGizmoSimplify::request_rerender().
set_height()
bool GLGizmoEmboss::set_height () private
{
    float &value = m_style_manager.get_style().prop.size_in_mm;
    // size can't be zero or negative
    priv::Limits::apply(value, priv::limits.size_in_mm);
    if (m_volume == nullptr || !m_volume->text_configuration.has_value()) {
        assert(false);
        return false;
    }
    // only different value need process
    if (is_approx(value, m_volume->text_configuration->style.prop.size_in_mm))
        return false;
#ifdef USE_PIXEL_SIZE_IN_WX_FONT
    // store font size into path serialization
    const wxFont &wx_font = m_style_manager.get_wx_font();
    if (wx_font.IsOk()) {
        wxFont wx_font_new = wx_font; // copy
        wx_font_new.SetPointSize(static_cast<int>(value));
        m_style_manager.set_wx_font(wx_font_new);
    }
#endif
    return true;
}
References priv::Limits::apply(), Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::GUI::Emboss::StyleManager::get_wx_font(), Slic3r::is_approx(), priv::limits, m_style_manager, m_volume, Slic3r::EmbossStyle::prop, Slic3r::GUI::Emboss::StyleManager::set_wx_font(), Slic3r::FontProp::size_in_mm, and Slic3r::ModelVolume::text_configuration.
Referenced by draw_height().
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    // do not change hover id during dragging
    assert(!m_dragging);
    // allow empty grabbers when not using grabbers but use hover_id - flatten, rotate
//    if (!m_grabbers.empty() && id >= (int) m_grabbers.size())
//        return;
    m_hover_id = id;
    on_set_hover_id();
}
References Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_minimal_window_size()
void GLGizmoEmboss::set_minimal_window_size (bool is_advance_edit_style) private
{
    ImVec2 window_size = ImGui::GetWindowSize();
    const ImVec2& min_win_size_prev = get_minimal_window_size();
    //ImVec2 diff(window_size.x - min_win_size_prev.x,
    //            window_size.y - min_win_size_prev.y);
    float diff_y = window_size.y - min_win_size_prev.y;
    m_is_advanced_edit_style = is_advance_edit_style;
    const ImVec2 &min_win_size = get_minimal_window_size();
    ImGui::SetWindowSize(ImVec2(0.f, min_win_size.y + diff_y),
                         ImGuiCond_Always);
    priv::change_window_position(m_set_window_offset, true);
}
References priv::change_window_position(), get_minimal_window_size(), ImGui::GetWindowSize(), ImGuiCond_Always, m_is_advanced_edit_style, m_set_window_offset, ImGui::SetWindowSize(), and ImVec2::y.
Referenced by draw_window().
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and on_set_state().
set_volume_by_selection()
void GLGizmoEmboss::set_volume_by_selection () private
{
    const Selection &selection = m_parent.get_selection();
    const GLVolume *gl_volume = get_selected_gl_volume(selection);
    if (gl_volume == nullptr)
        return reset_volume();
    const ModelObjectPtrs &objects = m_parent.get_model()->objects;
    ModelVolume *volume = get_model_volume(*gl_volume, objects);
    if (volume == nullptr)
        return reset_volume();
    // is same volume as actual selected?
    if (volume->id() == m_volume_id &&
        m_volume != nullptr &&
        volume->text_configuration->style == m_volume->text_configuration->style)
        return;
    // for changed volume notification is NOT valid
    remove_notification_not_valid_font();
    // Do not use focused input value when switch volume(it must swith value)
    if (m_volume != nullptr &&
        m_volume != volume) // when update volume it changed id BUT not pointer
        ImGuiWrapper::left_inputs();
    // Is selected volume text volume?
    const std::optional<TextConfiguration>& tc_opt = volume->text_configuration;
    if (!tc_opt.has_value())
        return reset_volume();
    const TextConfiguration &tc = *tc_opt;
    const EmbossStyle    &style = tc.style;
    // Could exist OS without getter on face_name,
    // but it is able to restore font from descriptor
    // Soo default value must be TRUE
    bool is_font_installed = true;
    wxString face_name;
    std::optional<std::string> face_name_opt = style.prop.face_name;
    if (face_name_opt.has_value()) {
        face_name = wxString(face_name_opt->c_str());
        // search in enumerated fonts
        // refresh list of installed font in the OS.
        init_face_names(m_face_names);
        m_face_names.is_init = false;
        auto cmp = [](const FaceName &fn, const wxString& face_name)->bool { return fn.wx_name < face_name; };
        const std::vector<FaceName> &faces = m_face_names.faces;
        auto it = std::lower_bound(faces.begin(), faces.end(), face_name, cmp);
        is_font_installed = it != faces.end() && it->wx_name == face_name;
        if (!is_font_installed) {
            const std::vector<wxString> &bad = m_face_names.bad;
            auto it_bad = std::lower_bound(bad.begin(), bad.end(), face_name);
            if (it_bad == bad.end() || *it_bad != face_name){
                // check if wx allowed to set it up - another encoding of name
                wxFontEnumerator::InvalidateCache();
                wxFont wx_font_; // temporary structure
                if (wx_font_.SetFaceName(face_name) &&
                    WxFontUtils::create_font_file(wx_font_) != nullptr // can load TTF file?
                    ) {
                    is_font_installed = true;
                    // QUESTION: add this name to allowed faces?
                    // Could create twin of font face name
                    // When not add it will be hard to select it again when change font
                }
            }
        }
    }
    wxFont wx_font;
    // load wxFont from same OS when font name is installed
    if (style.type == WxFontUtils::get_actual_type() && is_font_installed)
        wx_font = WxFontUtils::load_wxFont(style.path);
    // Flag that is selected same font
    bool is_exact_font = true;
    // Different OS or try found on same OS
    if (!wx_font.IsOk()) {
        is_exact_font = false;
        // Try create similar wx font by FontFamily
        wx_font = WxFontUtils::create_wxFont(style);
        if (is_font_installed)
            is_exact_font = wx_font.SetFaceName(face_name);
        // Have to use some wxFont
        if (!wx_font.IsOk())
            wx_font = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
    }
    assert(wx_font.IsOk());
    // Load style to style manager
    const auto& styles = m_style_manager.get_styles();
    auto has_same_name = [&style](const StyleManager::Item &style_item) -> bool {
        const EmbossStyle &es = style_item.style;
        return es.name == style.name;
    };
    auto it = std::find_if(styles.begin(), styles.end(), has_same_name);
    if (it == styles.end()) {
        // style was not found
        m_style_manager.load_style(style, wx_font);
    } else {
        // style name is in styles list
        size_t style_index = it - styles.begin();
        if (!m_style_manager.load_style(style_index)) {
            // can`t load stored style
            m_style_manager.erase(style_index);
            m_style_manager.load_style(style, wx_font);
        } else {
            // stored style is loaded, now set modification of style
            m_style_manager.get_style() = style;
            m_style_manager.set_wx_font(wx_font);
        }
    }
    if (!is_exact_font)
        create_notification_not_valid_font(tc);
    // The change of volume could show or hide part with setter on volume type
    if (m_volume == nullptr ||
        get_model_volume(m_volume_id, objects) == nullptr ||
        (m_volume->get_object()->volumes.size() == 1) !=
        (volume->get_object()->volumes.size() == 1)){
        m_should_set_minimal_windows_size = true;
    }
    // cancel previous job
    if (m_job_cancel != nullptr) {
        m_job_cancel->store(true);
        m_job_cancel = nullptr;
    }
    m_text   = tc.text;
    m_volume = volume;
    m_volume_id = volume->id();
    // Calculate current angle of up vector
    assert(m_style_manager.is_active_font());
    if (m_style_manager.is_active_font())
        m_style_manager.get_font_prop().angle = calc_up(gl_volume->world_matrix(), priv::up_limit);
    // calculate scale for height and depth inside of scaled object instance
    calculate_scale();
}
References Slic3r::FontProp::angle, Slic3r::GUI::GLGizmoEmboss::Facenames::bad, Slic3r::Emboss::calc_up(), calculate_scale(), Slic3r::GUI::WxFontUtils::create_font_file(), create_notification_not_valid_font(), Slic3r::GUI::WxFontUtils::create_wxFont(), Slic3r::GUI::Emboss::StyleManager::erase(), Slic3r::GUI::GLGizmoEmboss::Facenames::faces, Slic3r::GUI::WxFontUtils::get_actual_type(), Slic3r::GUI::Emboss::StyleManager::get_font_prop(), Slic3r::GUI::GLCanvas3D::get_model(), Slic3r::GUI::get_model_volume(), Slic3r::ModelVolume::get_object(), Slic3r::GUI::get_selected_gl_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Emboss::StyleManager::get_style(), Slic3r::GUI::Emboss::StyleManager::get_styles(), init_face_names(), Slic3r::GUI::Emboss::StyleManager::is_active_font(), Slic3r::GUI::GLGizmoEmboss::Facenames::is_init, Slic3r::GUI::ImGuiWrapper::left_inputs(), Slic3r::GUI::Emboss::StyleManager::load_style(), Slic3r::GUI::WxFontUtils::load_wxFont(), m_face_names, m_job_cancel, Slic3r::GUI::GLGizmoBase::m_parent, m_should_set_minimal_windows_size, m_style_manager, m_text, m_volume, m_volume_id, Slic3r::EmbossStyle::name, Slic3r::Model::objects, remove_notification_not_valid_font(), reset_volume(), Slic3r::GUI::Emboss::StyleManager::set_wx_font(), Slic3r::TextConfiguration::style, style, Slic3r::TextConfiguration::text, Slic3r::ModelVolume::text_configuration, priv::up_limit, Slic3r::ModelObject::volumes, Slic3r::GLVolume::world_matrix(), and Slic3r::GUI::GLGizmoEmboss::FaceName::wx_name.
Referenced by data_changed(), and on_shortcut_key().
store()
bool GLGizmoEmboss::store (const Facenames & facenames) static private
{
    std::string cache_path = get_fontlist_cache_path().string();
    boost::nowide::ofstream file(cache_path, std::ios::binary);
    cereal::BinaryOutputArchive archive(file);
    std::vector<wxString> good;
    good.reserve(facenames.faces.size());
    for (const FaceName &face : facenames.faces) good.push_back(face.wx_name);
    FacenamesSerializer data = {facenames.hash, good, facenames.bad};
    assert(std::is_sorted(data.bad.begin(), data.bad.end()));
    assert(std::is_sorted(data.good.begin(), data.good.end()));
    try {
        archive(data);
    } catch (const std::exception &ex) {
        BOOST_LOG_TRIVIAL(error) << "Failed to write fontlist cache - " << cache_path << ex.what();
        return false;
    }
    return true;
}
References Slic3r::GUI::GLGizmoEmboss::Facenames::bad, error, Slic3r::GUI::GLGizmoEmboss::Facenames::faces, get_fontlist_cache_path(), and Slic3r::GUI::GLGizmoEmboss::Facenames::hash.
Referenced by draw_font_list(), draw_style_rename_popup(), and init_face_names().
unregister_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].unregister_raycasters_for_picking();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers.
Referenced by Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking().
unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking () inline inherited
{ unregister_grabbers_for_picking(); on_unregister_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
use_grabbers()
bool Slic3r::GUI::GLGizmoBase::use_grabbers (const wxMouseEvent & mouse_event) protected inherited
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
Parameters
mouse_event Keep information about mouse click
Returns
same as on_mouse
{
    bool is_dragging_finished = false;
    if (mouse_event.Moving()) {
        // it should not happen but for sure
        assert(!m_dragging);
        if (m_dragging) is_dragging_finished = true;
        else return false;
    }
    if (mouse_event.LeftDown()) {
        Selection &selection = m_parent.get_selection();
        if (!selection.is_empty() && m_hover_id != -1 /* &&
            (m_grabbers.empty() || m_hover_id < static_cast<int>(m_grabbers.size()))*/) {
            selection.setup_cache();
            m_dragging = true;
            for (auto &grabber : m_grabbers) grabber.dragging = false;
//            if (!m_grabbers.empty() && m_hover_id < int(m_grabbers.size()))
//                m_grabbers[m_hover_id].dragging = true;
            on_start_dragging();
            // Let the plater know that the dragging started
            m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_STARTED));
            m_parent.set_as_dirty();
            return true;
        }
    } else if (m_dragging) {
        // when mouse cursor leave window than finish actual dragging operation
        bool is_leaving = mouse_event.Leaving();
        if (mouse_event.Dragging()) {
            Point      mouse_coord(mouse_event.GetX(), mouse_event.GetY());
            auto       ray = m_parent.mouse_ray(mouse_coord);
            UpdateData data(ray, mouse_coord);
            on_dragging(data);
            wxGetApp().obj_manipul()->set_dirty();
            m_parent.set_as_dirty();
            return true;
        }
        else if (mouse_event.LeftUp() || is_leaving || is_dragging_finished) {
            do_stop_dragging(is_leaving);
            return true;
        }
    }
    return false;
}
References Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_ray(), Slic3r::GUI::GLGizmoBase::on_dragging(), Slic3r::GUI::GLGizmoBase::on_start_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::Selection::setup_cache().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_mouse(), Slic3r::GUI::GLGizmoRotate::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), and on_mouse_for_rotation().
wants_enter_leave_snapshots()
bool Slic3r::GUI::GLGizmoEmboss::wants_enter_leave_snapshots () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return true; }
Member Data Documentation
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
GRABBER_ELEMENTS_MAX_COUNT
const unsigned int Slic3r::GUI::GLGizmoBase::GRABBER_ELEMENTS_MAX_COUNT = 7 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render().
m_allow_open_near_volume
bool Slic3r::GUI::GLGizmoEmboss::m_allow_open_near_volume = false private
Referenced by draw_window(), on_render_input_window(), and on_set_state().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c { nullptr } protected inherited
Referenced by Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoFdmSupports::auto_generate(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::GLGizmoCut3D::check_and_update_connectors_state(), Slic3r::GUI::GLGizmoCut3D::data_changed(), Slic3r::GUI::GLGizmoFdmSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoCut3D::has_valid_contour(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoCut3D::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::GLGizmoCut3D::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoHollow::reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), Slic3r::GUI::GLGizmoCut3D::render_clipper_cut(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::GLGizmoCut3D::reset_connectors(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut3D::update_bb(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty { false } private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging { false } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), on_mouse_for_rotation(), on_render(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::GLGizmoBase::set_hover_id(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_face_names
struct Slic3r::GUI::GLGizmoEmboss::Facenames Slic3r::GUI::GLGizmoEmboss::m_face_names private
Referenced by draw_font_list(), draw_font_preview(), init_font_name_texture(), select_facename(), and set_volume_by_selection().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render { true } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoRotate::disable_grabber(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoRotate::enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLGizmoRotate::start_dragging(), Slic3r::GUI::GLGizmoRotate::stop_dragging(), Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate::GLGizmoRotate(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), and Slic3r::GUI::GLGizmoRotate::set_group_id().
m_gui_cfg
std::optional<const GuiCfg> Slic3r::GUI::GLGizmoEmboss::m_gui_cfg private
Referenced by draw_advanced(), draw_depth(), draw_font_list(), draw_font_list_line(), draw_font_preview(), draw_height(), draw_style_list(), draw_text_input(), draw_window(), get_minimal_window_size(), init_font_name_texture(), init_icons(), on_render_input_window(), on_set_state(), rev_checkbox(), rev_input(), rev_slider(), rev_slider(), and rev_slider().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id { -1 } protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_xy(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_z(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoCut3D::is_selection_changed(), Slic3r::GUI::GLGizmoCut3D::on_dragging(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_dragging(), Slic3r::GUI::GLGizmoScale3D::on_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging(), Slic3r::GUI::GLGizmoCut3D::on_stop_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename().
M_ICON_FILENAME
const std::string GLGizmoEmboss::M_ICON_FILENAME = "cut.svg" static private
m_icon_manager
IconManager Slic3r::GUI::GLGizmoEmboss::m_icon_manager private
Referenced by init_icons().
m_icons
IconManager::VIcons Slic3r::GUI::GLGizmoEmboss::m_icons private
Referenced by draw_advanced(), draw_bold_button(), draw_delete_style_button(), draw_font_list_line(), draw_italic_button(), draw_style_add_button(), draw_style_rename_button(), draw_style_save_button(), draw_text_input(), init_icons(), and revertible().
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), Slic3r::GUI::GLGizmoCut3D::add_horizontal_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::add_vertical_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::adjust_window_position(), Slic3r::GUI::GLGizmoSimplify::create_gui_cfg(), draw_advanced(), draw_font_preview(), draw_model_type(), draw_style_add_button(), draw_style_rename_button(), draw_style_rename_popup(), draw_style_save_as_popup(), draw_text_input(), draw_window(), Slic3r::GUI::GLGizmoCut3D::init_input_window_data(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_build_size(), Slic3r::GUI::GLGizmoCut3D::render_combo(), Slic3r::GUI::GLGizmoCut3D::render_connectors_input_window(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoCut3D::render_double_input(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoCut3D::render_input_window_warning(), Slic3r::GUI::GLGizmoCut3D::render_move_center_input(), Slic3r::GUI::GLGizmoCut3D::render_reset_button(), Slic3r::GUI::GLGizmoCut3D::render_shortcuts(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), rev_slider(), rev_slider(), and rev_slider().
m_is_advanced_edit_style
bool Slic3r::GUI::GLGizmoEmboss::m_is_advanced_edit_style = false private
Referenced by draw_window(), get_minimal_window_size(), and set_minimal_window_size().
m_is_unknown_font
bool Slic3r::GUI::GLGizmoEmboss::m_is_unknown_font private
Referenced by create_notification_not_valid_font(), draw_font_list_line(), draw_window(), on_render_input_window(), and remove_notification_not_valid_font().
m_job_cancel
std::shared_ptr<std::atomic<bool> > Slic3r::GUI::GLGizmoEmboss::m_job_cancel private
Referenced by create_volume(), create_volume(), on_mouse_for_translate(), process(), and set_volume_by_selection().
m_keep_up
bool Slic3r::GUI::GLGizmoEmboss::m_keep_up = true private
Referenced by draw_advanced(), and on_mouse_for_translate().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::add_connector(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::GLGizmoCut3D::bounding_box(), calculate_scale(), close(), Slic3r::GUI::GLGizmoSimplify::close(), create_volume(), create_volume(), Slic3r::GUI::GLGizmoFlatten::data_changed(), Slic3r::GUI::GLGizmoMeasure::data_changed(), Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoRotate3D::data_changed(), Slic3r::GUI::GLGizmoCut3D::delete_selected_connectors(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), do_rotate(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), do_translate(), draw_advanced(), draw_model_type(), draw_window(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeasure::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeasure::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoCut3D::on_load(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), on_mouse_change_selection(), on_mouse_for_rotation(), on_mouse_for_translate(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), on_shortcut_key(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), on_stop_dragging(), Slic3r::GUI::GLGizmoMove3D::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoScale3D::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), process(), Slic3r::GUI::GLGizmoSimplify::process(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_cut_line(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::register_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::remove_selected_sphere_raycaster(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), Slic3r::GUI::GLGizmoCut3D::reset_cut_by_contours(), Slic3r::GUI::GLGizmoCut3D::reset_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), set_volume_by_selection(), Slic3r::GUI::GLGizmoCut3D::set_volumes_picking_state(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoCut3D::transformed_bounding_box(), Slic3r::GUI::GLGizmoHollow::unregister_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::unregister_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_raycast_manager
RaycastManager Slic3r::GUI::GLGizmoEmboss::m_raycast_manager private
Referenced by create_volume(), create_volume(), on_mouse_for_translate(), and process().
m_rotate_gizmo
GLGizmoRotate Slic3r::GUI::GLGizmoEmboss::m_rotate_gizmo private
Referenced by GLGizmoEmboss(), on_disable_grabber(), on_dragging(), on_enable_grabber(), on_init(), on_mouse_for_rotation(), on_register_raycasters_for_picking(), on_render(), on_set_hover_id(), on_set_state(), on_start_dragging(), on_stop_dragging(), and on_unregister_raycasters_for_picking().
m_rotate_start_angle
std::optional<float> Slic3r::GUI::GLGizmoEmboss::m_rotate_start_angle private
Referenced by on_mouse_for_rotation(), and on_stop_dragging().
m_scale_depth
std::optional<float> Slic3r::GUI::GLGizmoEmboss::m_scale_depth private
Referenced by calculate_scale(), and draw_depth().
m_scale_height
std::optional<float> Slic3r::GUI::GLGizmoEmboss::m_scale_height private
Referenced by calculate_scale(), draw_height(), and draw_text_input().
m_set_window_offset
std::optional<ImVec2> Slic3r::GUI::GLGizmoEmboss::m_set_window_offset private
Referenced by draw_window(), on_render_input_window(), on_set_state(), and set_minimal_window_size().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoCut3D::on_init(), on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), Slic3r::GUI::GLGizmoHollow::on_init(), Slic3r::GUI::GLGizmoMeasure::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), and Slic3r::GUI::GLGizmoSlaSupports::on_init().
m_should_set_minimal_windows_size
bool Slic3r::GUI::GLGizmoEmboss::m_should_set_minimal_windows_size = false private
Referenced by on_render_input_window(), and set_volume_by_selection().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_state
EState Slic3r::GUI::GLGizmoBase::m_state protected inherited
Referenced by Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoBase::load(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), Slic3r::GUI::GLGizmoRotate3D::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoBase::set_state(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), and Slic3r::GUI::GLGizmoSimplify::worker_finished().
m_style_manager
Emboss::StyleManager Slic3r::GUI::GLGizmoEmboss::m_style_manager private
Referenced by calculate_scale(), create_notification_not_valid_font(), create_volume(), create_volume(), draw_advanced(), draw_bold_button(), draw_delete_style_button(), draw_depth(), draw_font_list(), draw_font_list_line(), draw_height(), draw_italic_button(), draw_style_add_button(), draw_style_list(), draw_style_rename_button(), draw_style_rename_popup(), draw_style_save_as_popup(), draw_style_save_button(), draw_text_input(), draw_window(), get_minimal_window_size(), init_create(), on_init(), on_mouse_for_rotation(), on_mouse_for_translate(), on_render_input_window(), on_set_state(), on_stop_dragging(), process(), select_facename(), set_depth(), set_height(), and set_volume_by_selection().
m_surface_drag
std::optional<SurfaceDrag> Slic3r::GUI::GLGizmoEmboss::m_surface_drag private
Referenced by on_mouse_for_translate(), on_render(), and on_render_input_window().
m_text
std::string Slic3r::GUI::GLGizmoEmboss::m_text private
Referenced by close(), create_volume(), create_volume(), draw_font_preview(), draw_style_list(), draw_text_input(), init_create(), process(), and set_volume_by_selection().
m_text_contain_unknown_glyph
bool Slic3r::GUI::GLGizmoEmboss::m_text_contain_unknown_glyph = false private
Referenced by draw_text_input().
m_volume
ModelVolume* Slic3r::GUI::GLGizmoEmboss::m_volume private
Referenced by close(), data_changed(), do_rotate(), do_translate(), draw_advanced(), draw_model_type(), draw_style_add_button(), draw_style_save_as_popup(), draw_window(), get_minimal_window_size(), on_mouse(), on_mouse_change_selection(), on_mouse_for_translate(), on_render(), on_render_input_window(), on_shortcut_key(), process(), reset_volume(), set_depth(), set_height(), and set_volume_by_selection().
m_volume_id
ObjectID Slic3r::GUI::GLGizmoEmboss::m_volume_id private
Referenced by on_mouse(), on_render(), on_render_input_window(), reset_volume(), and set_volume_by_selection().
NO_SHORTCUT_KEY_VALUE
const int Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE = 0 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoEmboss.hpp
src/slic3r/GUI/Gizmos/GLGizmoEmboss.cpp