Prusa Slicer: Slic3r::BoundingBoxBase< PointType, APointsType > Class Template Reference
Slic3r::BoundingBoxBase< PointType, APointsType > Class Template Reference
#include <src/libslic3r/BoundingBox.hpp>
Public Types
using PointsType = APointsType
Public Member Functions
BoundingBoxBase ()
BoundingBoxBase (const PointType &pmin, const PointType &pmax)
BoundingBoxBase (const PointType &p1, const PointType &p2, const PointType &p3)
template<class It , class = IteratorOnly<It>>
BoundingBoxBase (It from, It to)
BoundingBoxBase (const PointsType &points)
void reset ()
void merge (const PointType &point)
void merge (const PointsType &points)
void merge (const BoundingBoxBase< PointType, PointsType > &bb)
void scale (double factor)
PointType size () const
double radius () const
void translate (coordf_t x, coordf_t y)
void translate (const PointType &v)
void offset (coordf_t delta)
BoundingBoxBase< PointType, PointsType > inflated (coordf_t delta) const throw ()
PointType center () const
bool contains (const PointType &point) const
bool contains (const BoundingBoxBase< PointType, PointsType > &other) const
bool overlap (const BoundingBoxBase< PointType, PointsType > &other) const
bool operator== (const BoundingBoxBase< PointType, PointsType > &rhs)
bool operator!= (const BoundingBoxBase< PointType, PointsType > &rhs)
Public Attributes
PointType min
PointType max
bool defined
Static Private Member Functions
template<bool IncludeBoundary = false, class BoundingBoxType , class It , class = IteratorOnly<It>>
static void construct (BoundingBoxType &out, It from, It to)
Friends
BoundingBox get_extents (const Points &pts)
BoundingBox get_extents (const Points &pts)
Detailed Description
template<typename PointType, typename APointsType = std::vector<PointType>>
class Slic3r::BoundingBoxBase< PointType, APointsType >
Member Typedef Documentation
PointsType
template<typename PointType , typename APointsType = std::vector<PointType>> using Slic3r::BoundingBoxBase< PointType, APointsType >::PointsType = APointsType
Constructor & Destructor Documentation
BoundingBoxBase() [1/5]
template<typename PointType , typename APointsType = std::vector<PointType>> Slic3r::BoundingBoxBase< PointType, APointsType >::BoundingBoxBase () inline
: min(PointType::Zero()), max(PointType::Zero()), defined(false) {}
BoundingBoxBase() [2/5]
template<typename PointType , typename APointsType = std::vector<PointType>> Slic3r::BoundingBoxBase< PointType, APointsType >::BoundingBoxBase (const PointType & pmin, const PointType & pmax) inline
                                                                  :
        min(pmin), max(pmax), defined(pmin.x() < pmax.x() && pmin.y() < pmax.y()) {}
BoundingBoxBase() [3/5]
template<typename PointType , typename APointsType = std::vector<PointType>> Slic3r::BoundingBoxBase< PointType, APointsType >::BoundingBoxBase (const PointType & p1, const PointType & p2, const PointType & p3) inline
                                                                                   :
        min(p1), max(p1), defined(false) { merge(p2); merge(p3); }
References Slic3r::BoundingBoxBase< PointType, APointsType >::merge().
BoundingBoxBase() [4/5]
template<typename PointType , typename APointsType = std::vector<PointType>> template<class It , class = IteratorOnly<It>> Slic3r::BoundingBoxBase< PointType, APointsType >::BoundingBoxBase (It from, It to) inline
        { construct(*this, from, to); }
References Slic3r::BoundingBoxBase< PointType, APointsType >::construct().
BoundingBoxBase() [5/5]
template<typename PointType , typename APointsType = std::vector<PointType>> Slic3r::BoundingBoxBase< PointType, APointsType >::BoundingBoxBase (const PointsType & points) inline
        : BoundingBoxBase(points.begin(), points.end())
    {}
Member Function Documentation
center()
template<class PointType , typename APointsType > template Vec2d Slic3r::BoundingBoxBase< PointType, APointsType >::center () const
{
    return (this->min + this->max) / 2;
}
Referenced by Slic3r::WipeTower::WipeTower(), Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::Fill::_infill_direction(), Slic3r::arrangement::arrange(), Slic3r::cut_surface(), priv::cut_surface(), Slic3r::GUI::Bed3D::render_model(), Slic3r::GUI::GLCanvas3D::SLAView::render_switch_button(), priv::select_patches(), and Slic3r::GUI::ImGuiWrapper::suggest_location().
construct()
template<typename PointType , typename APointsType = std::vector<PointType>> template<bool IncludeBoundary = false, class BoundingBoxType , class It , class = IteratorOnly<It>> static void Slic3r::BoundingBoxBase< PointType, APointsType >::construct (BoundingBoxType & out, It from, It to) inline static private
    {
        if (from != to) {
            auto it = from;
            out.min = it->template cast<typename PointType::Scalar>();
            out.max = out.min;
            for (++ it; it != to; ++ it) {
                auto vec = it->template cast<typename PointType::Scalar>();
                out.min = out.min.cwiseMin(vec);
                out.max = out.max.cwiseMax(vec);
            }
            out.defined = IncludeBoundary || (out.min.x() < out.max.x() && out.min.y() < out.max.y());
        }
    }
Referenced by Slic3r::BoundingBoxBase< PointType, APointsType >::BoundingBoxBase().
contains() [1/2]
template<typename PointType , typename APointsType = std::vector<PointType>> bool Slic3r::BoundingBoxBase< PointType, APointsType >::contains (const BoundingBoxBase< PointType, PointsType > & other) const inline
{
        return contains(other.min) && contains(other.max);
    }
References Slic3r::BoundingBoxBase< PointType, APointsType >::contains(), Slic3r::BoundingBoxBase< PointType, APointsType >::max, and Slic3r::BoundingBoxBase< PointType, APointsType >::min.
contains() [2/2]
template<typename PointType , typename APointsType = std::vector<PointType>> bool Slic3r::BoundingBoxBase< PointType, APointsType >::contains (const PointType & point) const inline
{
        return point.x() >= this->min.x() && point.x() <= this->max.x()
            && point.y() >= this->min.y() && point.y() <= this->max.y();
    }
Referenced by Slic3r::any_expolygon_contains(), Slic3r::MMU_Graph::append_voronoi_vertices(), Slic3r::clip_finite_voronoi_edge(), Slic3r::BoundingBoxBase< PointType, APointsType >::contains(), Slic3r::BoundingBox3Base< PointType >::contains(), Slic3r::contour_distance(), Slic3r::SupportGridPattern::extract_support(), Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::find_cell_idx(), Slic3r::FFFTreeSupport::generate_support_infill_lines(), Slic3r::GUI::MeshClipper::is_projection_inside_cut(), Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::mark_erased(), Slic3r::GUI::FillBedJob::prepare(), priv::remove_spikes_in_duplicates(), and Slic3r::EdgeGrid::Grid::visit_cells_intersecting_line().
inflated()
template<typename PointType , typename APointsType = std::vector<PointType>> BoundingBoxBase< PointType, PointsType > Slic3r::BoundingBoxBase< PointType, APointsType >::inflated (coordf_t delta) const throw () inline
{ BoundingBoxBase<PointType, PointsType> out(*this); out.offset(delta); return out; }
References Slic3r::BoundingBoxBase< PointType, APointsType >::offset().
merge() [1/3]
template<class PointType , typename APointsType > void Slic3r::BoundingBoxBase< PointType, APointsType >::merge (const BoundingBoxBase< PointType, PointsType > & bb)
{
    assert(bb.defined || bb.min.x() >= bb.max.x() || bb.min.y() >= bb.max.y());
    if (bb.defined) {
        if (this->defined) {
            this->min = this->min.cwiseMin(bb.min);
            this->max = this->max.cwiseMax(bb.max);
        } else {
            this->min = bb.min;
            this->max = bb.max;
            this->defined = true;
        }
    }
}
References Slic3r::BoundingBoxBase< PointType, APointsType >::defined, Slic3r::BoundingBoxBase< PointType, APointsType >::max, and Slic3r::BoundingBoxBase< PointType, APointsType >::min.
merge() [2/3]
template<class PointType , typename APointsType > void Slic3r::BoundingBoxBase< PointType, APointsType >::merge (const PointsType & points)
{
    this->merge(BoundingBoxBase(points));
}
merge() [3/3]
template<class PointType , typename APointsType > void Slic3r::BoundingBoxBase< PointType, APointsType >::merge (const PointType & point)
{
    if (this->defined) {
        this->min = this->min.cwiseMin(point);
        this->max = this->max.cwiseMax(point);
    } else {
        this->min = point;
        this->max = point;
        this->defined = true;
    }
}
Referenced by Slic3r::BoundingBoxBase< PointType, APointsType >::BoundingBoxBase(), Slic3r::GCode::_do_export(), Slic3r::Fill3DHoneycomb::_fill_surface_single(), Slic3r::FillGyroid::_fill_surface_single(), Slic3r::FillHoneycomb::_fill_surface_single(), Slic3r::FillLine::_fill_surface_single(), Slic3r::Voronoi::annotate_inside_outside(), Slic3r::Geometry::arrange(), Slic3r::connect_brim_lines(), Slic3r::ExPolygon::contains(), Slic3r::contour_distance(), Slic3r::contour_distance2(), Slic3r::MultiPoint::douglas_peucker(), Slic3r::dump_voronoi_to_svg(), Slic3r::expolygons_to_zpaths_shrunk(), Slic3r::SVG::export_expolygons(), Slic3r::FFFSupport::export_print_z_polygons_and_extrusions_to_svg(), Slic3r::FFFSupport::export_print_z_polygons_to_svg(), Slic3r::LayerRegion::export_region_fill_surfaces_to_svg(), Slic3r::Layer::export_region_fill_surfaces_to_svg(), Slic3r::LayerRegion::export_region_slices_to_svg(), Slic3r::Layer::export_region_slices_to_svg(), Slic3r::SurfaceCollection::export_to_svg(), Slic3r::export_to_svg(), Slic3r::SupportGridPattern::extract_support(), Slic3r::extrusion_polyline_extents(), Slic3r::extrusionentity_extents(), Slic3r::extrusionentity_extents(), Slic3r::extrusionentity_extents(), Slic3r::FillRectilinear::fill_surface_by_lines(), Slic3r::FillLightning::Generator::generateTrees(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents_rotated(), Slic3r::get_extents_rotated(), Slic3r::get_print_extrusions_extents(), Slic3r::get_print_object_extrusions_extents(), Slic3r::GUI::Selection::get_screen_space_bounding_box(), Slic3r::get_wipe_tower_extrusions_extents(), Slic3r::get_wipe_tower_priming_extrusions_extents(), Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::initialize(), Slic3r::intersecting_edges(), Slic3r::line_rounded_thick_segment_collision(), Slic3r::make_loops(), Slic3r::mark_boundary_segments_touching_infill(), Slic3r::Algorithm::merge_expansions_into_expolygons(), Slic3r::FFFTreeSupport::merge_influence_areas_two_elements(), Slic3r::mittered_offset_path_scaled(), Slic3r::FFFSupport::modulate_extrusion_by_overlapping_layers(), Slic3r::multi_material_segmentation_by_painting(), Slic3r::Voronoi::offset(), Slic3r::ExPolygon::overlaps(), Slic3r::BoundingBox::rotated(), Slic3r::slice_mesh(), Slic3r::Arachne::WallToolPaths::stitchToolPaths(), and Slic3r::traverse_extrusions().
offset()
template<class PointType , typename APointsType > template void Slic3r::BoundingBoxBase< PointType, APointsType >::offset (coordf_t delta)
{
    PointType v(delta, delta);
    this->min -= v;
    this->max += v;
}
Referenced by Slic3r::SupportGridPattern::SupportGridPattern(), Slic3r::GCode::_do_export(), Slic3r::MMU_Graph::append_voronoi_vertices(), Slic3r::arrangement::arrange(), Slic3r::elephant_foot_compensation(), Slic3r::generate_extra_perimeters_over_overhangs(), Slic3r::BoundingBoxBase< PointType, APointsType >::inflated(), Slic3r::BoundingBox::inflated(), Slic3r::init_boundary(), Slic3r::AvoidCrossingPerimeters::init_layer(), Slic3r::inner_offset(), Slic3r::intersecting_edges(), Slic3r::branchingtree::make_bed_poly(), Slic3r::multi_material_segmentation_by_painting(), Slic3r::slice_region_by_vertical_lines(), Slic3r::RetractWhenCrossingPerimeters::travel_inside_internal_regions(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops_classic().
operator!=()
template<typename PointType , typename APointsType = std::vector<PointType>> bool Slic3r::BoundingBoxBase< PointType, APointsType >::operator!= (const BoundingBoxBase< PointType, PointsType > & rhs) inline
{ return ! (*this == rhs); }
operator==()
template<typename PointType , typename APointsType = std::vector<PointType>> bool Slic3r::BoundingBoxBase< PointType, APointsType >::operator== (const BoundingBoxBase< PointType, PointsType > & rhs) inline
{ return this->min == rhs.min && this->max == rhs.max; }
References Slic3r::BoundingBoxBase< PointType, APointsType >::max, and Slic3r::BoundingBoxBase< PointType, APointsType >::min.
overlap()
template<typename PointType , typename APointsType = std::vector<PointType>> bool Slic3r::BoundingBoxBase< PointType, APointsType >::overlap (const BoundingBoxBase< PointType, PointsType > & other) const inline
{
        return ! (this->max.x() < other.min.x() || this->min.x() > other.max.x() ||
                  this->max.y() < other.min.y() || this->min.y() > other.max.y());
    }
References Slic3r::BoundingBoxBase< PointType, APointsType >::max, and Slic3r::BoundingBoxBase< PointType, APointsType >::min.
Referenced by Slic3r::GCode::_do_export(), priv::compute_intersections(), Slic3r::sla::SupportPointGenerator::Structure::overlap_area(), and Slic3r::sla::SupportPointGenerator::Structure::overlaps().
radius()
template<class PointType , typename APointsType > template double Slic3r::BoundingBoxBase< PointType, APointsType >::radius () const
{
    assert(this->defined);
    return 0.5 * (this->max - this->min).template cast<double>().norm();
}
Referenced by Slic3r::GUI::Bed3D::set_shape().
reset()
template<typename PointType , typename APointsType = std::vector<PointType>> void Slic3r::BoundingBoxBase< PointType, APointsType >::reset () inline
{ this->defined = false; this->min = PointType::Zero(); this->max = PointType::Zero(); }
Referenced by Slic3r::ModelObject::bounding_box_approx(), Slic3r::ModelObject::bounding_box_exact(), Slic3r::ModelObject::raw_bounding_box(), and Slic3r::ModelObject::raw_mesh_bounding_box().
scale()
template<class PointType , typename APointsType > template void Slic3r::BoundingBoxBase< PointType, APointsType >::scale (double factor)
{
    this->min *= factor;
    this->max *= factor;
}
Referenced by Slic3r::GUI::CreateFontImageJob::process(), Slic3r::GUI::Emboss::CreateFontStyleImagesJob::process(), and Slic3r::GUI::Camera::validate_target().
size()
template<class PointType , typename APointsType > template Vec2d Slic3r::BoundingBoxBase< PointType, APointsType >::size () const
{
    return this->max - this->min;
}
Referenced by Slic3r::BuildVolume::BuildVolume(), Slic3r::WipeTower::WipeTower(), Slic3r::GCode::_do_export(), Slic3r::Fill3DHoneycomb::_fill_surface_single(), Slic3r::FillConcentric::_fill_surface_single(), Slic3r::FillGyroid::_fill_surface_single(), Slic3r::FillLine::_fill_surface_single(), Slic3r::FillConcentric::_fill_surface_single(), Slic3r::Voronoi::annotate_inside_outside(), Slic3r::Geometry::arrange(), Slic3r::GUI::GLCanvas3D::WipeTowerInfo::bb_size(), Slic3r::clip_finite_voronoi_edge(), priv::create_bounding_rect(), Slic3r::SVGRaster::draw(), Slic3r::dump_voronoi_to_svg(), Slic3r::elephant_foot_compensation(), Slic3r::ExtrusionSimulator::evaluate_accumulator(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::FillRectilinear::fill_surface_by_lines(), Slic3r::GUI::GLCanvas3D::get_size_proportional_to_max_bed_size(), Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::initialize(), Slic3r::inner_offset(), Slic3r::Voronoi::offset(), Slic3r::GUI::CreateFontImageJob::process(), Slic3r::ExtrusionSimulator::reset_accumulator(), and Slic3r::ExtrusionSimulator::set_viewport().
translate() [1/2]
template<typename PointType , typename APointsType = std::vector<PointType>> void Slic3r::BoundingBoxBase< PointType, APointsType >::translate (const PointType & v) inline
{ this->min += v; this->max += v; }
translate() [2/2]
template<typename PointType , typename APointsType = std::vector<PointType>> void Slic3r::BoundingBoxBase< PointType, APointsType >::translate (coordf_t x, coordf_t y) inline
{ assert(this->defined); PointType v(x, y); this->min += v; this->max += v; }
Referenced by Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::arrangement::arrange(), Slic3r::Geometry::arrange(), priv::cut_surface(), and Slic3r::get_print_object_extrusions_extents().
Friends And Related Symbol Documentation
get_extents [1/2]
template<typename PointType , typename APointsType = std::vector<PointType>> BoundingBox get_extents (const Points & pts) friend
{
    BoundingBox out;
    BoundingBox::construct<IncludeBoundary>(out, pts.begin(), pts.end());
    return out;
}
get_extents [2/2]
template<typename PointType , typename APointsType = std::vector<PointType>> BoundingBox get_extents (const Points & pts) friend
{
    BoundingBox out;
    BoundingBox::construct<IncludeBoundary>(out, pts.begin(), pts.end());
    return out;
}
Member Data Documentation
defined
template<typename PointType , typename APointsType = std::vector<PointType>> bool Slic3r::BoundingBoxBase< PointType, APointsType >::defined
Referenced by Slic3r::Geometry::arrange(), Slic3r::TriangleMesh::bounding_box(), Slic3r::GUI::Bed3D::calc_extended_bounding_box(), Slic3r::EdgeGrid::Grid::closest_point_signed_distance(), Slic3r::empty(), Slic3r::empty(), Slic3r::extrusionentity_extents(), Slic3r::extrusionentity_extents(), Slic3r::extrusionentity_extents(), Slic3r::BoundingBox3Base< Vec3crd >::max_size(), Slic3r::BoundingBoxBase< PointType, APointsType >::merge(), Slic3r::GUI::GLCanvas3D::SLAView::render_switch_button(), cereal::serialize(), cereal::serialize(), cereal::serialize(), cereal::serialize(), Slic3r::GUI::Bed3D::set_shape(), Slic3r::EdgeGrid::Grid::signed_distance_edges(), Slic3r::GLVolume::transformed_bounding_box(), Slic3r::TriangleMesh::transformed_bounding_box(), and Slic3r::GUI::GLGizmoCut3D::update_bb().
max
template<typename PointType , typename APointsType = std::vector<PointType>> PointType Slic3r::BoundingBoxBase< PointType, APointsType >::max
Referenced by Slic3r::BuildVolume::BuildVolume(), Slic3r::SupportGridPattern::SupportGridPattern(), Slic3r::GCode::_do_export(), Slic3r::FillHoneycomb::_fill_surface_single(), Slic3r::FillLine::_fill_surface_single(), Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), Slic3r::JPSPathFinder::add_obstacles(), Slic3r::BuildVolume::all_paths_inside(), Slic3r::BuildVolume::all_paths_inside_vertices_and_normals_interleaved(), Slic3r::Voronoi::annotate_inside_outside(), Slic3r::arrangement::arrange(), Slic3r::Geometry::arrange(), Slic3r::bbox_point_distance(), Slic3r::bbox_point_distance_squared(), Slic3r::TriangleMesh::bounding_box(), Slic3r::arrangement::bounding_box(), Slic3r::BuildVolume::bounding_volume2d(), Slic3r::GUI::Camera::calc_tight_frustrum_zs_around(), Slic3r::GUI::Camera::calc_zoom_to_bounding_box_factor(), Slic3r::JPSPathFinder::clear(), Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox_templ(), Slic3r::Line::clip_with_bbox(), Slic3r::EdgeGrid::Grid::closest_point_signed_distance(), Slic3r::BoundingBox3Base< PointType >::contains(), Slic3r::BoundingBoxBase< PointType, APointsType >::contains(), Slic3r::GUI::contains(), priv::create_bounding_rect(), priv::cut_surface(), Slic3r::BridgeDetector::detect_angle(), Slic3r::dump_voronoi_to_svg(), Slic3r::empty(), Slic3r::empty(), Slic3r::SVG::export_expolygons(), Slic3r::FFFSupport::export_print_z_polygons_and_extrusions_to_svg(), Slic3r::FFFSupport::export_print_z_polygons_to_svg(), Slic3r::LayerRegion::export_region_fill_surfaces_to_svg(), Slic3r::Layer::export_region_fill_surfaces_to_svg(), Slic3r::LayerRegion::export_region_slices_to_svg(), Slic3r::Layer::export_region_slices_to_svg(), Slic3r::SurfaceCollection::export_to_svg(), Slic3r::SupportGridPattern::extract_support(), Slic3r::extrusion_polyline_extents(), Slic3r::extrusionentity_extents(), Slic3r::extrusionentity_extents(), Slic3r::extrusionentity_extents(), Slic3r::FillRectilinear::fill_surface_by_lines(), boost::geometry::traits::indexed_access< BB3< T >, 1, d >::get(), boost::geometry::traits::indexed_access< Slic3r::BoundingBox, 1, d >::get(), Slic3r::GUI::WipeTower::get_arrange_polygon(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::get_trapezoids2(), Slic3r::GUI::GLCanvas3D::get_wipe_tower_info(), Slic3r::get_wipe_tower_priming_extrusions_extents(), Slic3r::FillLightning::Layer::getBestGroundingLocation(), Slic3r::arrangement::height(), Slic3r::init_boundary(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::initialize(), Slic3r::insert_fills_into_islands(), Slic3r::FillAdaptive::Octree::insert_triangle(), Slic3r::BoundingBox3Base< PointType >::intersects(), Slic3r::GLVolume::is_below_printbed(), Slic3r::GLVolume::is_sinking(), Slic3r::GUI::GCodeViewer::load(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::make_fill_lines(), Slic3r::make_fill_polylines(), Slic3r::BoundingBox3Base< Vec3crd >::max_size(), Slic3r::ModelObject::max_z(), Slic3r::BoundingBoxBase< PointType, APointsType >::merge(), Slic3r::BuildVolume::object_state(), Slic3r::Voronoi::offset(), Slic3r::SVG::open(), Slic3r::BoundingBoxBase< PointType, APointsType >::operator==(), Slic3r::BoundingBoxBase< PointType, APointsType >::overlap(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::ModelObject::print_info(), Slic3r::GUI::CreateFontImageJob::process(), Slic3r::GUI::Emboss::CreateFontStyleImagesJob::process(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::GUI::GLCanvas3D::SLAView::render_switch_button(), Slic3r::sample_grid_pattern(), Slic3r::EdgeGrid::save_png(), Slic3r::scaled(), Slic3r::scaled(), Slic3r::GUI::GLCanvas3D::scene_bounding_box(), cereal::serialize(), cereal::serialize(), cereal::serialize(), cereal::serialize(), boost::geometry::traits::indexed_access< BB3< T >, 1, d >::set(), boost::geometry::traits::indexed_access< Slic3r::BoundingBox, 1, d >::set(), Slic3r::FFFTreeSupport::SupportElementMerging::set_bbox(), Slic3r::GUI::GLGizmoCut3D::set_center_pos(), priv::set_skip_for_out_of_aoi(), Slic3r::InfillPolylineClipper::sides(), Slic3r::EdgeGrid::Grid::signed_distance_edges(), Slic3r::Layer::sort_perimeters_into_islands(), Slic3r::GUI::ImGuiWrapper::suggest_location(), Slic3r::arrangement::to_nestbin(), Slic3r::anonymous_namespace{SL1_SVG.cpp}::transform(), Slic3r::BoundingBoxf3::transformed(), Slic3r::GLVolume::transformed_bounding_box(), Slic3r::TriangleMesh::transformed_bounding_box(), Slic3r::RetractWhenCrossingPerimeters::travel_inside_internal_regions(), Slic3r::FillAdaptive::triangle_AABB_intersects(), Slic3r::unscaled(), Slic3r::unscaled(), Slic3r::GUI::GLGizmoCut3D::update_bb(), Slic3r::update_bounding_box(), Slic3r::ModelObject::update_min_max_z(), Slic3r::GUI::Camera::validate_target(), Slic3r::EdgeGrid::Grid::visit_cells_intersecting_box(), Slic3r::BuildVolume::volume_state_bbox(), Slic3r::arrangement::width(), and Slic3r::GUI::GLCanvas3D::zoom_to_bed().
min
template<typename PointType , typename APointsType = std::vector<PointType>> PointType Slic3r::BoundingBoxBase< PointType, APointsType >::min
Referenced by Slic3r::BuildVolume::BuildVolume(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::SupportGridPattern::SupportGridPattern(), Slic3r::GCode::_do_export(), Slic3r::Fill3DHoneycomb::_fill_surface_single(), Slic3r::FillGyroid::_fill_surface_single(), Slic3r::FillHoneycomb::_fill_surface_single(), Slic3r::FillLine::_fill_surface_single(), Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), Slic3r::JPSPathFinder::add_obstacles(), Slic3r::BuildVolume::all_paths_inside(), Slic3r::BuildVolume::all_paths_inside_vertices_and_normals_interleaved(), Slic3r::Voronoi::annotate_inside_outside(), Slic3r::GUI::BedShape::apply_optgroup_values(), Slic3r::arrangement::arrange(), Slic3r::Geometry::arrange(), Slic3r::GUI::assign_logical_beds(), Slic3r::bbox_point_distance(), Slic3r::bbox_point_distance_squared(), Slic3r::TriangleMesh::bounding_box(), Slic3r::arrangement::bounding_box(), Slic3r::BuildVolume::bounding_volume2d(), Slic3r::GUI::Camera::calc_tight_frustrum_zs_around(), Slic3r::GUI::Camera::calc_zoom_to_bounding_box_factor(), Slic3r::JPSPathFinder::clear(), Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox_templ(), Slic3r::Line::clip_with_bbox(), Slic3r::EdgeGrid::Grid::closest_point_signed_distance(), Slic3r::BoundingBox3Base< PointType >::contains(), Slic3r::BoundingBoxBase< PointType, APointsType >::contains(), Slic3r::GUI::contains(), priv::create_bounding_rect(), priv::cut_surface(), Slic3r::BridgeDetector::detect_angle(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_reset_skew(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::dump_voronoi_to_svg(), Slic3r::empty(), Slic3r::empty(), Slic3r::ExtrusionSimulator::evaluate_accumulator(), Slic3r::SVG::export_expolygons(), Slic3r::FFFSupport::export_print_z_polygons_and_extrusions_to_svg(), Slic3r::FFFSupport::export_print_z_polygons_to_svg(), Slic3r::LayerRegion::export_region_fill_surfaces_to_svg(), Slic3r::Layer::export_region_fill_surfaces_to_svg(), Slic3r::LayerRegion::export_region_slices_to_svg(), Slic3r::Layer::export_region_slices_to_svg(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::SurfaceCollection::export_to_svg(), Slic3r::SupportGridPattern::extract_support(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::extrusion_polyline_extents(), Slic3r::extrusionentity_extents(), Slic3r::extrusionentity_extents(), Slic3r::extrusionentity_extents(), Slic3r::FillRectilinear::fill_surface_by_lines(), Slic3r::FillLightning::DistanceField::from_grid_point(), boost::geometry::traits::indexed_access< BB3< T >, 0, d >::get(), boost::geometry::traits::indexed_access< Slic3r::BoundingBox, 0, d >::get(), Slic3r::GUI::WipeTower::get_arrange_polygon(), Slic3r::GUI::BedShape::get_full_name_with_params(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::get_trapezoids2(), Slic3r::GUI::GLCanvas3D::get_wipe_tower_info(), Slic3r::get_wipe_tower_priming_extrusions_extents(), Slic3r::FillLightning::Layer::getBestGroundingLocation(), Slic3r::arrangement::height(), Slic3r::init_boundary(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::initialize(), Slic3r::insert_fills_into_islands(), Slic3r::FillAdaptive::Octree::insert_triangle(), Slic3r::BoundingBox3Base< PointType >::intersects(), Slic3r::GLVolume::is_sinking(), Slic3r::GUI::GCodeViewer::load(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::make_fill_lines(), Slic3r::make_fill_polylines(), Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::map_to_flat_array(), Slic3r::BoundingBox3Base< Vec3crd >::max_size(), Slic3r::BoundingBoxBase< PointType, APointsType >::merge(), Slic3r::ModelObject::min_z(), Slic3r::BuildVolume::object_state(), Slic3r::Voronoi::offset(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::SVG::open(), Slic3r::BoundingBoxBase< PointType, APointsType >::operator==(), Slic3r::BoundingBoxBase< PointType, APointsType >::overlap(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::ModelObject::print_info(), Slic3r::GUI::CreateFontImageJob::process(), Slic3r::GUI::Emboss::CreateFontStyleImagesJob::process(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::CLI::run(), Slic3r::sample_grid_pattern(), Slic3r::EdgeGrid::save_png(), Slic3r::GUI::Selection::scale_to_fit_print_volume(), Slic3r::scaled(), Slic3r::scaled(), Slic3r::GUI::GLCanvas3D::scene_bounding_box(), cereal::serialize(), cereal::serialize(), cereal::serialize(), cereal::serialize(), boost::geometry::traits::indexed_access< BB3< T >, 0, d >::set(), boost::geometry::traits::indexed_access< Slic3r::BoundingBox, 0, d >::set(), Slic3r::FFFTreeSupport::SupportElementMerging::set_bbox(), Slic3r::GUI::GLGizmoCut3D::set_center_pos(), priv::set_skip_for_out_of_aoi(), Slic3r::InfillPolylineClipper::sides(), Slic3r::EdgeGrid::Grid::signed_distance_edges(), Slic3r::Layer::sort_perimeters_into_islands(), Slic3r::GUI::ImGuiWrapper::suggest_location(), Slic3r::SLAPrint::Steps::support_points(), Slic3r::FillLightning::DistanceField::to_grid_point(), Slic3r::FillLightning::to_grid_point(), Slic3r::arrangement::to_nestbin(), Slic3r::anonymous_namespace{SL1_SVG.cpp}::transform(), Slic3r::BoundingBoxf3::transformed(), Slic3r::GLVolume::transformed_bounding_box(), Slic3r::TriangleMesh::transformed_bounding_box(), Slic3r::RetractWhenCrossingPerimeters::travel_inside_internal_regions(), Slic3r::FillAdaptive::triangle_AABB_intersects(), Slic3r::unscaled(), Slic3r::unscaled(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GUI::GLGizmoCut3D::update_bb(), Slic3r::update_bounding_box(), Slic3r::ModelObject::update_min_max_z(), Slic3r::GUI::ObjectManipulation::update_reset_buttons_visibility(), Slic3r::GUI::Camera::validate_target(), Slic3r::EdgeGrid::Grid::visit_cells_intersecting_box(), Slic3r::EdgeGrid::Grid::visit_cells_intersecting_line(), Slic3r::BuildVolume::volume_state_bbox(), Slic3r::arrangement::width(), and Slic3r::GUI::GLCanvas3D::zoom_to_bed().
The documentation for this class was generated from the following files:
src/libslic3r/BoundingBox.hpp
src/libslic3r/BoundingBox.cpp