Prusa Slicer: Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized > Class Template Reference
Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized > Class Template Reference
#include <src/eigen/Eigen/src/Core/Swap.h>
Public Types
typedef Base::Scalar Scalar
typedef Base::DstXprType DstXprType
typedef swap_assign_op< Scalar > Functor
typedef DstEvaluatorTypeT DstEvaluatorType
typedef SrcEvaluatorTypeT SrcEvaluatorType
typedef copy_using_evaluator_traits< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > > AssignmentTraits
typedef AssignmentTraits::PacketType PacketType
Public Member Functions
EIGEN_DEVICE_FUNC generic_dense_assignment_kernel (DstEvaluatorTypeT &dst, const SrcEvaluatorTypeT &src, const Functor &func, DstXprType &dstExpr)
template<int StoreMode, int LoadMode, typename PacketType >
void assignPacket (Index row, Index col)
template<int StoreMode, int LoadMode, typename PacketType >
void assignPacket (Index index)
template<int StoreMode, int LoadMode, typename PacketType >
void assignPacketByOuterInner (Index outer, Index inner)
EIGEN_DEVICE_FUNC Index size () const
EIGEN_DEVICE_FUNC Index innerSize () const
EIGEN_DEVICE_FUNC Index outerSize () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC DstEvaluatorType & dstEvaluator ()
EIGEN_DEVICE_FUNC const SrcEvaluatorType & srcEvaluator () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index row, Index col)
Assign src(row,col) to dst(row,col) through the assignment functor.
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeffByOuterInner (Index outer, Index inner)
EIGEN_DEVICE_FUNC const Scalar * dstDataPtr () const
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowIndexByOuterInner (Index outer, Index inner)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colIndexByOuterInner (Index outer, Index inner)
Protected Types
typedef generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, BuiltIn > Base
typedef SrcEvaluatorTypeT::XprType SrcXprType
Protected Attributes
DstEvaluatorType & m_dst
const SrcEvaluatorType & m_src
const Functor & m_functor
DstXprType & m_dstExpr
Detailed Description
template<typename DstEvaluatorTypeT, typename SrcEvaluatorTypeT>
class Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >
Member Typedef Documentation
AssignmentTraits
typedef copy_using_evaluator_traits<DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > > Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::AssignmentTraits inherited
Base
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef generic_dense_assignment_kernel<DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op<typename DstEvaluatorTypeT::Scalar>, BuiltIn> Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::Base protected
DstEvaluatorType
typedef DstEvaluatorTypeT Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::DstEvaluatorType inherited
DstXprType
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef Base::DstXprType Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::DstXprType
Functor
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef swap_assign_op<Scalar> Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::Functor
PacketType
typedef AssignmentTraits::PacketType Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::PacketType inherited
Scalar
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef Base::Scalar Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::Scalar
SrcEvaluatorType
typedef SrcEvaluatorTypeT Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::SrcEvaluatorType inherited
SrcXprType
typedef SrcEvaluatorTypeT::XprType Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::SrcXprType protected inherited
Constructor & Destructor Documentation
generic_dense_assignment_kernel()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > EIGEN_DEVICE_FUNC Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::generic_dense_assignment_kernel (DstEvaluatorTypeT & dst, const SrcEvaluatorTypeT & src, const Functor & func, DstXprType & dstExpr) inline
    : Base(dst, src, func, dstExpr)
  {}
Member Function Documentation
assignCoeff() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::assignCoeff (Index index) inline inherited
See also
assignCoeff(Index,Index)
  {
    m_functor.assignCoeff(m_dst.coeffRef(index), m_src.coeff(index));
  }
assignCoeff() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::assignCoeff (Index row, Index col) inline inherited
Assign src(row,col) to dst(row,col) through the assignment functor.
  {
    m_functor.assignCoeff(m_dst.coeffRef(row,col), m_src.coeff(row,col));
  }
assignCoeffByOuterInner()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::assignCoeffByOuterInner (Index outer, Index inner) inline inherited
See also
assignCoeff(Index,Index)
  {
    Index row = rowIndexByOuterInner(outer, inner);
    Index col = colIndexByOuterInner(outer, inner);
    assignCoeff(row, col);
  }
assignPacket() [1/2]
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > template<int StoreMode, int LoadMode, typename PacketType > void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket (Index index) inline
  {
    PacketType tmp = m_src.template packet<LoadMode,PacketType>(index);
    const_cast<SrcEvaluatorTypeT&>(m_src).template writePacket<LoadMode>(index, m_dst.template packet<StoreMode,PacketType>(index));
    m_dst.template writePacket<StoreMode>(index,tmp);
  }
References Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dst, and Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_src.
assignPacket() [2/2]
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > template<int StoreMode, int LoadMode, typename PacketType > void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket (Index row, Index col) inline
  {
    PacketType tmp = m_src.template packet<LoadMode,PacketType>(row,col);
    const_cast<SrcEvaluatorTypeT&>(m_src).template writePacket<LoadMode>(row,col, m_dst.template packet<StoreMode,PacketType>(row,col));
    m_dst.template writePacket<StoreMode>(row,col,tmp);
  }
References col(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dst, Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_src, and row().
assignPacketByOuterInner()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > template<int StoreMode, int LoadMode, typename PacketType > void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacketByOuterInner (Index outer, Index inner) inline
  {
    Index row = Base::rowIndexByOuterInner(outer, inner);
    Index col = Base::colIndexByOuterInner(outer, inner);
    assignPacket<StoreMode,LoadMode,PacketType>(row, col);
  }
References col(), and row().
colIndexByOuterInner()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::colIndexByOuterInner (Index outer, Index inner) inline static inherited
  {
    typedef typename DstEvaluatorType::ExpressionTraits Traits;
    return int(Traits::ColsAtCompileTime) == 1 ? 0
      : int(Traits::RowsAtCompileTime) == 1 ? inner
      : int(DstEvaluatorType::Flags)&RowMajorBit ? inner
      : outer;
  }
cols()
EIGEN_DEVICE_FUNC Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::cols () const inline inherited
{ return m_dstExpr.cols(); }
dstDataPtr()
EIGEN_DEVICE_FUNC const Scalar * Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::dstDataPtr () const inline inherited
  {
    return m_dstExpr.data();
  }
dstEvaluator()
EIGEN_DEVICE_FUNC DstEvaluatorType & Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::dstEvaluator () inline inherited
{ return m_dst; }
innerSize()
EIGEN_DEVICE_FUNC Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::innerSize () const inline inherited
{ return m_dstExpr.innerSize(); }
outerSize()
EIGEN_DEVICE_FUNC Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::outerSize () const inline inherited
{ return m_dstExpr.outerSize(); }
outerStride()
EIGEN_DEVICE_FUNC Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::outerStride () const inline inherited
{ return m_dstExpr.outerStride(); }
rowIndexByOuterInner()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::rowIndexByOuterInner (Index outer, Index inner) inline static inherited
  {
    typedef typename DstEvaluatorType::ExpressionTraits Traits;
    return int(Traits::RowsAtCompileTime) == 1 ? 0
      : int(Traits::ColsAtCompileTime) == 1 ? inner
      : int(DstEvaluatorType::Flags)&RowMajorBit ? outer
      : inner;
  }
rows()
EIGEN_DEVICE_FUNC Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::rows () const inline inherited
{ return m_dstExpr.rows(); }
size()
EIGEN_DEVICE_FUNC Index Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::size () const inline inherited
{ return m_dstExpr.size(); }
srcEvaluator()
EIGEN_DEVICE_FUNC const SrcEvaluatorType & Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::srcEvaluator () const inline inherited
{ return m_src; }
Member Data Documentation
m_dst
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > DstEvaluatorType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dst protected
m_dstExpr
DstXprType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > , Version >::m_dstExpr protected inherited
m_functor
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > const Functor& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_functor protected
m_src
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > const SrcEvaluatorType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_src protected
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/Swap.h