Prusa Slicer: Slic3r::GUI::Emboss::CreateObjectJob Class Reference
Slic3r::GUI::Emboss::CreateObjectJob Class Reference
Create new TextObject on the platter Should not be stopped.
#include <src/slic3r/GUI/Jobs/EmbossJob.hpp>
Public Member Functions
CreateObjectJob (DataCreateObject &&input)
Create Object.
void process (Ctl &ctl) override
void finalize (bool canceled, std::exception_ptr &eptr) override
Private Attributes
DataCreateObject m_input
TriangleMesh m_result
Transform3d m_transformation
Detailed Description
Create new TextObject on the platter Should not be stopped.
Constructor & Destructor Documentation
CreateObjectJob()
CreateObjectJob::CreateObjectJob (DataCreateObject && input)
Create Object.
    : m_input(std::move(input))
{
    assert(priv::check(m_input));
}
References priv::check(), and m_input.
Member Function Documentation
finalize()
void CreateObjectJob::finalize (bool canceled, std::exception_ptr & eptr) override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (!priv::finalize(canceled, eptr, m_input))
        return;
    // only for sure
    if (m_result.empty())
        return priv::create_message("Can't create empty object.");
    GUI_App    &app      = wxGetApp();
    Plater     *plater   = app.plater();
    ObjectList *obj_list = app.obj_list();
    GLCanvas3D *canvas   = plater->canvas3D();
    plater->take_snapshot(_L("Add Emboss text object"));
    // Create new object and change selection
    bool center = false;
    obj_list->load_mesh_object(std::move(m_result), m_input.volume_name,
                                center, &m_input.text_configuration,
                                &m_transformation);
    // When add new object selection is empty.
    // When cursor move and no one object is selected than
    // Manager::reset_all() So Gizmo could be closed before end of creation object
    GLGizmosManager &manager = canvas->get_gizmos_manager();
    if (manager.get_current_type() != GLGizmosManager::Emboss)
        manager.open_gizmo(GLGizmosManager::Emboss);
    // redraw scene
    canvas->reload_scene(true);
}
References _L, Slic3r::GUI::Plater::canvas3D(), priv::create_message(), Slic3r::GUI::GLGizmosManager::Emboss, Slic3r::TriangleMesh::empty(), priv::finalize(), Slic3r::GUI::GLGizmosManager::get_current_type(), Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::ObjectList::load_mesh_object(), m_input, m_result, m_transformation, Slic3r::GUI::GUI_App::obj_list(), Slic3r::GUI::obj_list(), Slic3r::GUI::GLGizmosManager::open_gizmo(), Slic3r::GUI::GUI_App::plater(), Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::Plater::take_snapshot(), Slic3r::GUI::Emboss::DataBase::text_configuration, and Slic3r::GUI::Emboss::DataBase::volume_name.
process()
void CreateObjectJob::process (Ctl & ctl) override virtual
Implements Slic3r::GUI::Job.
{
    if (!priv::check(m_input))
        throw std::runtime_error("Bad input data for EmbossCreateObjectJob.");
    auto was_canceled = [&ctl]()->bool { return ctl.was_canceled(); };
    m_result = priv::create_mesh(m_input, was_canceled, ctl);
    if (was_canceled()) return;
    // Create new object
    // calculate X,Y offset position for lay on platter in place of
    // mouse click
    Vec2d bed_coor = CameraUtils::get_z0_position(
        m_input.camera, m_input.screen_coor);
    // check point is on build plate:
    Points bed_shape_;
    bed_shape_.reserve(m_input.bed_shape.size());
    for (const Vec2d &p : m_input.bed_shape)
        bed_shape_.emplace_back(p.cast<int>());
    Polygon bed(bed_shape_);
    if (!bed.contains(bed_coor.cast<int>()))
        // mouse pose is out of build plate so create object in center of plate
        bed_coor = bed.centroid().cast<double>();
    double z = m_input.text_configuration.style.prop.emboss / 2;
    Vec3d  offset(bed_coor.x(), bed_coor.y(), z);
    offset -= m_result.center();
    Transform3d::TranslationType tt(offset.x(), offset.y(), offset.z());
    m_transformation = Transform3d(tt);
}
References Slic3r::GUI::Emboss::DataCreateObject::bed_shape, Slic3r::GUI::Emboss::DataCreateObject::camera, Slic3r::TriangleMesh::center(), Slic3r::Polygon::centroid(), priv::check(), Slic3r::Polygon::contains(), priv::create_mesh(), Slic3r::FontProp::emboss, Slic3r::GUI::CameraUtils::get_z0_position(), m_input, m_result, m_transformation, Slic3r::offset(), Slic3r::EmbossStyle::prop, Slic3r::GUI::Emboss::DataCreateObject::screen_coor, Slic3r::TextConfiguration::style, Slic3r::GUI::Emboss::DataBase::text_configuration, and Slic3r::GUI::Job::Ctl::was_canceled().
Member Data Documentation
m_input
DataCreateObject Slic3r::GUI::Emboss::CreateObjectJob::m_input private
Referenced by CreateObjectJob(), finalize(), and process().
m_result
TriangleMesh Slic3r::GUI::Emboss::CreateObjectJob::m_result private
Referenced by finalize(), and process().
m_transformation
Transform3d Slic3r::GUI::Emboss::CreateObjectJob::m_transformation private
Referenced by finalize(), and process().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/EmbossJob.hpp
src/slic3r/GUI/Jobs/EmbossJob.cpp