Prusa Slicer: libnest2d::Radians Class Reference
libnest2d::Radians Class Reference
Data type representing radians. It supports conversion to degrees.
#include <src/libnest2d/include/libnest2d/common.hpp>
Public Member Functions
Radians (double rads=Double())
Radians (const Degrees &degs)
operator Degrees ()
double toDegrees ()
double sin () const
double cos () const
operator double () const BP2D_NOEXCEPT
operator double & () BP2D_NOEXCEPT
Protected Attributes
double val_
Private Attributes
double sin_ = std::nan("")
double cos_ = std::nan("")
Detailed Description
Data type representing radians. It supports conversion to degrees.
Constructor & Destructor Documentation
Radians() [1/2]
libnest2d::Radians::Radians (double rads = Double()) inline
: Double(rads) {}
Radians() [2/2]
libnest2d::Radians::Radians (const Degrees & degs) inline
: Double(degs * Pi/180) {}
Member Function Documentation
cos()
double libnest2d::Radians::cos () const inline
{
        if(std::isnan(cos_)) {
            cos_ = std::cos(val_);
            sin_ = std::sin(val_);
        }
        return cos_;
    }
References cos_, sin_, and libnest2d::Double::val_.
operator Degrees()
libnest2d::Radians::operator Degrees () inline
{ return *this * 180/Pi; }
References libnest2d::Pi.
operator double()
libnest2d::Double::operator double () const inline inherited
{ return val_; }
References libnest2d::Double::val_.
operator double &()
libnest2d::Double::operator double & () inline inherited
{ return val_; }
References libnest2d::Double::val_.
sin()
double libnest2d::Radians::sin () const inline
{
        if(std::isnan(sin_)) {
            cos_ = std::cos(val_);
            sin_ = std::sin(val_);
        }
        return sin_;
    }
References cos_, sin_, and libnest2d::Double::val_.
toDegrees()
double libnest2d::Radians::toDegrees () inline
{ return operator Degrees(); }
Member Data Documentation
cos_
double libnest2d::Radians::cos_ = std::nan("") private
Referenced by cos(), and sin().
sin_
double libnest2d::Radians::sin_ = std::nan("") mutable private
Referenced by cos(), and sin().
val_
double libnest2d::Double::val_ protected inherited
Referenced by cos(), libnest2d::Double::operator double(), libnest2d::Double::operator double &(), and sin().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/common.hpp