Prusa Slicer: Eigen::SparseSelfAdjointView< MatrixType, _Mode > Class Template Reference
Eigen::SparseSelfAdjointView< MatrixType, _Mode > Class Template Reference
Pseudo expression to manipulate a triangular sparse matrix as a selfadjoint matrix.
#include <src/eigen/Eigen/src/SparseCore/SparseSelfAdjointView.h>
Public Types
enum { Mode = _Mode , TransposeMode = ((Mode & Upper) ? Lower : 0) | ((Mode & Lower) ? Upper : 0) , RowsAtCompileTime = internal::traits<SparseSelfAdjointView>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<SparseSelfAdjointView>::ColsAtCompileTime }
typedef EigenBase< SparseSelfAdjointView > Base
typedef MatrixType::Scalar Scalar
typedef MatrixType::StorageIndex StorageIndex
typedef Matrix< StorageIndex, Dynamic, 1 > VectorI
typedef internal::ref_selector< MatrixType >::non_const_type MatrixTypeNested
typedef internal::remove_all< MatrixTypeNested >::type _MatrixTypeNested
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< SparseSelfAdjointView< MatrixType, _Mode > >::StorageKind StorageKind
Public Member Functions
SparseSelfAdjointView (MatrixType &matrix)
Index rows () const
Index cols () const
const _MatrixTypeNested & matrix () const
internal::remove_reference< MatrixTypeNested >::type & matrix ()
template<typename OtherDerived >
Product< SparseSelfAdjointView, OtherDerived > operator* (const SparseMatrixBase< OtherDerived > &rhs) const
template<typename OtherDerived >
Product< SparseSelfAdjointView, OtherDerived > operator* (const MatrixBase< OtherDerived > &rhs) const
template<typename DerivedU >
SparseSelfAdjointView & rankUpdate (const SparseMatrixBase< DerivedU > &u, const Scalar &alpha=Scalar(1))
SparseSymmetricPermutationProduct< _MatrixTypeNested, Mode > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
template<typename SrcMatrixType , int SrcMode>
SparseSelfAdjointView & operator= (const SparseSymmetricPermutationProduct< SrcMatrixType, SrcMode > &permutedMatrix)
SparseSelfAdjointView & operator= (const SparseSelfAdjointView &src)
template<typename SrcMatrixType , unsigned int SrcMode>
SparseSelfAdjointView & operator= (const SparseSelfAdjointView< SrcMatrixType, SrcMode > &src)
void resize (Index rows, Index cols)
template<typename DerivedU >
SparseSelfAdjointView< MatrixType, Mode > & rankUpdate (const SparseMatrixBase< DerivedU > &u, const Scalar &alpha)
EIGEN_DEVICE_FUNC SparseSelfAdjointView< MatrixType, _Mode > & derived ()
EIGEN_DEVICE_FUNC const SparseSelfAdjointView< MatrixType, _Mode > & derived () const
EIGEN_DEVICE_FUNC SparseSelfAdjointView< MatrixType, _Mode > & const_cast_derived () const
EIGEN_DEVICE_FUNC const SparseSelfAdjointView< MatrixType, _Mode > & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Attributes
MatrixTypeNested m_matrix
Private Member Functions
template<typename Dest >
void evalTo (Dest &) const
Friends
template<typename OtherDerived >
Product< OtherDerived, SparseSelfAdjointView > operator* (const SparseMatrixBase< OtherDerived > &lhs, const SparseSelfAdjointView &rhs)
template<typename OtherDerived >
Product< OtherDerived, SparseSelfAdjointView > operator* (const MatrixBase< OtherDerived > &lhs, const SparseSelfAdjointView &rhs)
Detailed Description
template<typename MatrixType, unsigned int _Mode>
class Eigen::SparseSelfAdjointView< MatrixType, _Mode >
Pseudo expression to manipulate a triangular sparse matrix as a selfadjoint matrix.
Parameters
MatrixType the type of the dense matrix storing the coefficients
Mode can be either Lower or Upper
This class is an expression of a sefladjoint matrix from a triangular part of a matrix with given dense storage of the coefficients. It is the return type of MatrixBase::selfadjointView() and most of the time this is the only way that it is used.
See also
SparseMatrixBase::selfadjointView()
Member Typedef Documentation
_MatrixTypeNested
template<typename MatrixType , unsigned int _Mode> typedef internal::remove_all<MatrixTypeNested>::type Eigen::SparseSelfAdjointView< MatrixType, _Mode >::_MatrixTypeNested
Base
template<typename MatrixType , unsigned int _Mode> typedef EigenBase<SparseSelfAdjointView> Eigen::SparseSelfAdjointView< MatrixType, _Mode >::Base
Index
typedef Eigen::Index Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
MatrixTypeNested
template<typename MatrixType , unsigned int _Mode> typedef internal::ref_selector<MatrixType>::non_const_type Eigen::SparseSelfAdjointView< MatrixType, _Mode >::MatrixTypeNested
Scalar
template<typename MatrixType , unsigned int _Mode> typedef MatrixType::Scalar Eigen::SparseSelfAdjointView< MatrixType, _Mode >::Scalar
StorageIndex
template<typename MatrixType , unsigned int _Mode> typedef MatrixType::StorageIndex Eigen::SparseSelfAdjointView< MatrixType, _Mode >::StorageIndex
StorageKind
typedef internal::traits<SparseSelfAdjointView< MatrixType, _Mode > >::StorageKind Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::StorageKind inherited
VectorI
template<typename MatrixType , unsigned int _Mode> typedef Matrix<StorageIndex,Dynamic,1> Eigen::SparseSelfAdjointView< MatrixType, _Mode >::VectorI
Member Enumeration Documentation
anonymous enum
template<typename MatrixType , unsigned int _Mode> anonymous enum
Enumerator
Mode
TransposeMode
RowsAtCompileTime
ColsAtCompileTime
         {
      Mode = _Mode,
      TransposeMode = ((Mode & Upper) ? Lower : 0) | ((Mode & Lower) ? Upper : 0),
      RowsAtCompileTime = internal::traits<SparseSelfAdjointView>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<SparseSelfAdjointView>::ColsAtCompileTime
    };
Constructor & Destructor Documentation
SparseSelfAdjointView()
template<typename MatrixType , unsigned int _Mode> Eigen::SparseSelfAdjointView< MatrixType, _Mode >::SparseSelfAdjointView (MatrixType & matrix) inline explicit
                                                              : m_matrix(matrix)
    {
      eigen_assert(rows()==cols() && "SelfAdjointView is only for squared matrices");
    }
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::cols(), eigen_assert, and Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rows().
Member Function Documentation
addTo()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
applyThisOnTheLeft()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
applyThisOnTheRight()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
cols()
template<typename MatrixType , unsigned int _Mode> Index Eigen::SparseSelfAdjointView< MatrixType, _Mode >::cols () const inline
{ return m_matrix.cols(); }
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::m_matrix.
Referenced by Eigen::SparseSelfAdjointView< MatrixType, _Mode >::SparseSelfAdjointView(), and Eigen::SparseSelfAdjointView< MatrixType, _Mode >::resize().
const_cast_derived()
EIGEN_DEVICE_FUNC SparseSelfAdjointView< MatrixType, _Mode > & Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
const_derived()
EIGEN_DEVICE_FUNC const SparseSelfAdjointView< MatrixType, _Mode > & Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
EIGEN_DEVICE_FUNC SparseSelfAdjointView< MatrixType, _Mode > & Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::derived () inline inherited
Returns
a reference to the derived object
{ return *static_cast<Derived*>(this); }
derived() [2/2]
EIGEN_DEVICE_FUNC const SparseSelfAdjointView< MatrixType, _Mode > & Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::derived () const inline inherited
Returns
a const reference to the derived object
{ return *static_cast<const Derived*>(this); }
evalTo()
template<typename MatrixType , unsigned int _Mode> template<typename Dest > void Eigen::SparseSelfAdjointView< MatrixType, _Mode >::evalTo (Dest &) const private
matrix() [1/2]
template<typename MatrixType , unsigned int _Mode> internal::remove_reference< MatrixTypeNested >::type & Eigen::SparseSelfAdjointView< MatrixType, _Mode >::matrix () inline
{ return m_matrix; }
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::m_matrix.
matrix() [2/2]
template<typename MatrixType , unsigned int _Mode> const _MatrixTypeNested & Eigen::SparseSelfAdjointView< MatrixType, _Mode >::matrix () const inline
{ return m_matrix; }
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::m_matrix.
Referenced by Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run().
operator*() [1/2]
template<typename MatrixType , unsigned int _Mode> template<typename OtherDerived > Product< SparseSelfAdjointView, OtherDerived > Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient sparse self-adjoint matrix times dense vector/matrix product
    {
      return Product<SparseSelfAdjointView,OtherDerived>(*this, rhs.derived());
    }
operator*() [2/2]
template<typename MatrixType , unsigned int _Mode> template<typename OtherDerived > Product< SparseSelfAdjointView, OtherDerived > Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator* (const SparseMatrixBase< OtherDerived > & rhs) const inline
Returns
an expression of the matrix product between a sparse self-adjoint matrix *this and a sparse matrix rhs.
Note that there is no algorithmic advantage of performing such a product compared to a general sparse-sparse matrix product. Indeed, the SparseSelfadjointView operand is first copied into a temporary SparseMatrix before computing the product.
    {
      return Product<SparseSelfAdjointView, OtherDerived>(*this, rhs.derived());
    }
References Eigen::SparseMatrixBase< Derived >::derived().
operator=() [1/3]
template<typename MatrixType , unsigned int _Mode> SparseSelfAdjointView & Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator= (const SparseSelfAdjointView< MatrixType, _Mode > & src) inline
    {
      PermutationMatrix<Dynamic,Dynamic,StorageIndex> pnull;
      return *this = src.twistedBy(pnull);
    }
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::twistedBy().
operator=() [2/3]
template<typename MatrixType , unsigned int _Mode> template<typename SrcMatrixType , unsigned int SrcMode> SparseSelfAdjointView & Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator= (const SparseSelfAdjointView< SrcMatrixType, SrcMode > & src) inline
    {
      PermutationMatrix<Dynamic,Dynamic,StorageIndex> pnull;
      return *this = src.twistedBy(pnull);
    }
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::twistedBy().
operator=() [3/3]
template<typename MatrixType , unsigned int _Mode> template<typename SrcMatrixType , int SrcMode> SparseSelfAdjointView & Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator= (const SparseSymmetricPermutationProduct< SrcMatrixType, SrcMode > & permutedMatrix) inline
    {
      internal::call_assignment_no_alias_no_transpose(*this, permutedMatrix);
      return *this;
    }
References Eigen::internal::call_assignment_no_alias_no_transpose().
rankUpdate() [1/2]
template<typename MatrixType , unsigned int _Mode> template<typename DerivedU > SparseSelfAdjointView< MatrixType, Mode > & Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rankUpdate (const SparseMatrixBase< DerivedU > & u, const Scalar & alpha)
{
  SparseMatrix<Scalar,(MatrixType::Flags&RowMajorBit)?RowMajor:ColMajor> tmp = u * u.adjoint();
  if(alpha==Scalar(0))
    m_matrix = tmp.template triangularView<Mode>();
  else
    m_matrix += alpha * tmp.template triangularView<Mode>();
  return *this;
}
References Eigen::SparseMatrixBase< Derived >::adjoint(), Eigen::ColMajor, Eigen::SparseSelfAdjointView< MatrixType, _Mode >::m_matrix, Eigen::RowMajor, and Eigen::RowMajorBit.
rankUpdate() [2/2]
template<typename MatrixType , unsigned int _Mode> template<typename DerivedU > SparseSelfAdjointView & Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rankUpdate (const SparseMatrixBase< DerivedU > & u, const Scalar & alpha = Scalar(1))
Perform a symmetric rank K update of the selfadjoint matrix *this: where u is a vector or matrix.
Returns
a reference to *this
To perform you can simply call this function with u.adjoint().
resize()
template<typename MatrixType , unsigned int _Mode> void Eigen::SparseSelfAdjointView< MatrixType, _Mode >::resize (Index rows, Index cols) inline
    {
      EIGEN_ONLY_USED_FOR_DEBUG(rows);
      EIGEN_ONLY_USED_FOR_DEBUG(cols);
      eigen_assert(rows == this->rows() && cols == this->cols()
                && "SparseSelfadjointView::resize() does not actually allow to resize.");
    }
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::cols(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rows().
rows()
template<typename MatrixType , unsigned int _Mode> Index Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rows () const inline
{ return m_matrix.rows(); }
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::m_matrix.
Referenced by Eigen::SparseSelfAdjointView< MatrixType, _Mode >::SparseSelfAdjointView(), and Eigen::SparseSelfAdjointView< MatrixType, _Mode >::resize().
size()
EIGEN_DEVICE_FUNC Index Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
subTo()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
twistedBy()
template<typename MatrixType , unsigned int _Mode> SparseSymmetricPermutationProduct< _MatrixTypeNested, Mode > Eigen::SparseSelfAdjointView< MatrixType, _Mode >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline
Returns
an expression of P H P^-1
    {
      return SparseSymmetricPermutationProduct<_MatrixTypeNested,Mode>(m_matrix, perm);
    }
References Eigen::SparseSelfAdjointView< MatrixType, _Mode >::m_matrix.
Referenced by Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator=(), and Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator=().
Friends And Related Symbol Documentation
operator* [1/2]
template<typename MatrixType , unsigned int _Mode> template<typename OtherDerived > Product< OtherDerived, SparseSelfAdjointView > operator* (const MatrixBase< OtherDerived > & lhs, const SparseSelfAdjointView< MatrixType, _Mode > & rhs) friend
Efficient dense vector/matrix times sparse self-adjoint matrix product
    {
      return Product<OtherDerived,SparseSelfAdjointView>(lhs.derived(), rhs);
    }
operator* [2/2]
template<typename MatrixType , unsigned int _Mode> template<typename OtherDerived > Product< OtherDerived, SparseSelfAdjointView > operator* (const SparseMatrixBase< OtherDerived > & lhs, const SparseSelfAdjointView< MatrixType, _Mode > & rhs) friend
Returns
an expression of the matrix product between a sparse matrix lhs and a sparse self-adjoint matrix rhs.
Note that there is no algorithmic advantage of performing such a product compared to a general sparse-sparse matrix product. Indeed, the SparseSelfadjointView operand is first copied into a temporary SparseMatrix before computing the product.
    {
      return Product<OtherDerived, SparseSelfAdjointView>(lhs.derived(), rhs);
    }
Member Data Documentation
m_matrix
template<typename MatrixType , unsigned int _Mode> MatrixTypeNested Eigen::SparseSelfAdjointView< MatrixType, _Mode >::m_matrix protected
Referenced by Eigen::SparseSelfAdjointView< MatrixType, _Mode >::cols(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::matrix(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::matrix(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rankUpdate(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rows(), and Eigen::SparseSelfAdjointView< MatrixType, _Mode >::twistedBy().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseSelfAdjointView.h