Prusa Slicer: Slic3r::GUI::SavePresetDialog::Item Struct Reference
Slic3r::GUI::SavePresetDialog::Item Struct Reference
#include <src/slic3r/GUI/SavePresetDialog.hpp>
Public Types
enum class ValidationType { Valid , NoValid , Warning }
Public Member Functions
Item (Preset::Type type, const std::string &suffix, wxBoxSizer *sizer, SavePresetDialog *parent, bool is_for_multiple_save)
Item (wxWindow *parent, wxBoxSizer *sizer, const std::string &def_name, PrinterTechnology pt=ptFFF)
void update_valid_bmp ()
void accept ()
void Enable (bool enable=true)
bool is_valid () const
Preset::Type type () const
std::string preset_name () const
Private Member Functions
std::string get_init_preset_name (const std::string &suffix)
void init_input_name_ctrl (wxBoxSizer *input_name_sizer, std::string preset_name)
const Preset * get_existing_preset () const
void update ()
Private Attributes
Preset::Type m_type {Preset::TYPE_INVALID}
std::string m_preset_name
bool m_use_text_ctrl {true}
PrinterTechnology m_printer_technology {ptAny}
ValidationType m_valid_type {ValidationType::NoValid}
wxWindow * m_parent {nullptr}
wxStaticBitmap * m_valid_bmp {nullptr}
wxComboBox * m_combo {nullptr}
wxTextCtrl * m_text_ctrl {nullptr}
wxStaticText * m_valid_label {nullptr}
PresetCollection * m_presets {nullptr}
Detailed Description
Member Enumeration Documentation
ValidationType
enum class Slic3r::GUI::SavePresetDialog::Item::ValidationType strong
Enumerator
Valid
NoValid
Warning
        {
            Valid,
            NoValid,
            Warning
        };
Constructor & Destructor Documentation
Item() [1/2]
Slic3r::GUI::SavePresetDialog::Item::Item (Preset::Type type, const std::string & suffix, wxBoxSizer * sizer, SavePresetDialog * parent, bool is_for_multiple_save)
                                                                                                                                          :
    m_type(type),
    m_use_text_ctrl(parent->is_for_rename()),
    m_parent(parent),
    m_valid_bmp(new wxStaticBitmap(m_parent, wxID_ANY, *get_bmp_bundle("tick_mark"))),
    m_valid_label(new wxStaticText(m_parent, wxID_ANY, ""))
{
    m_valid_label->SetFont(wxGetApp().bold_font());
    wxStaticText* label_top = is_for_multiple_save ? new wxStaticText(m_parent, wxID_ANY, _(TOP_LABELS.at(m_type)) + ":") : nullptr;
    wxBoxSizer* input_name_sizer = new wxBoxSizer(wxHORIZONTAL);
    input_name_sizer->Add(m_valid_bmp,    0, wxALIGN_CENTER_VERTICAL | wxRIGHT, BORDER_W);
    init_input_name_ctrl(input_name_sizer, get_init_preset_name(suffix));
    if (label_top)
        sizer->Add(label_top,   0, wxEXPAND | wxTOP| wxBOTTOM, BORDER_W);
    sizer->Add(input_name_sizer,0, wxEXPAND | (label_top ? 0 : wxTOP) | wxBOTTOM, BORDER_W);
    sizer->Add(m_valid_label,   0, wxEXPAND | wxLEFT,   3*BORDER_W);
    if (m_type == Preset::TYPE_PRINTER)
        parent->add_info_for_edit_ph_printer(sizer);
    update();
}
References _, Slic3r::GUI::SavePresetDialog::add_info_for_edit_ph_printer(), Slic3r::GUI::BORDER_W, get_init_preset_name(), init_input_name_ctrl(), m_parent, m_type, m_valid_bmp, m_valid_label, Slic3r::GUI::suffix(), Slic3r::GUI::TOP_LABELS, Slic3r::Preset::TYPE_PRINTER, and update().
Item() [2/2]
Slic3r::GUI::SavePresetDialog::Item::Item (wxWindow * parent, wxBoxSizer * sizer, const std::string & def_name, PrinterTechnology pt = ptFFF)
                                                                                                                :
    m_preset_name(def_name),
    m_printer_technology(pt),
    m_parent(parent),
    m_valid_bmp(new wxStaticBitmap(m_parent, wxID_ANY, *get_bmp_bundle("tick_mark"))),
    m_valid_label(new wxStaticText(m_parent, wxID_ANY, ""))
{
    m_valid_label->SetFont(wxGetApp().bold_font());
    wxBoxSizer* input_name_sizer = new wxBoxSizer(wxHORIZONTAL);
    input_name_sizer->Add(m_valid_bmp,    0, wxALIGN_CENTER_VERTICAL | wxRIGHT, BORDER_W);
    init_input_name_ctrl(input_name_sizer, m_preset_name);
    sizer->Add(input_name_sizer,0, wxEXPAND | wxBOTTOM, BORDER_W);
    sizer->Add(m_valid_label,   0, wxEXPAND | wxLEFT,   3*BORDER_W);
    update();
}
References Slic3r::GUI::BORDER_W, init_input_name_ctrl(), m_preset_name, m_valid_bmp, m_valid_label, and update().
Member Function Documentation
accept()
void Slic3r::GUI::SavePresetDialog::Item::accept ()
{
    if (m_valid_type == ValidationType::Warning)
        m_presets->delete_preset(m_preset_name);
}
Enable()
void Slic3r::GUI::SavePresetDialog::Item::Enable (bool enable = true)
{
    m_valid_label->Enable(enable);
    m_valid_bmp->Enable(enable);
    m_use_text_ctrl ? m_text_ctrl->Enable(enable) : m_combo->Enable(enable);
}
Referenced by Slic3r::GUI::PageCustom::PageCustom().
get_existing_preset()
const Preset * Slic3r::GUI::SavePresetDialog::Item::get_existing_preset () const private
{
    if (m_presets)
        return m_presets->find_preset(m_preset_name, false);
    for (const Preset::Type& type : PresetBundle::types_list(m_printer_technology)) {
        const PresetCollection& presets = wxGetApp().preset_bundle->get_presets(type);
        if (const Preset* preset = presets.find_preset(m_preset_name, false))
            return preset;
    }
    return nullptr;
}
References Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::get_presets(), and Slic3r::PresetBundle::types_list().
get_init_preset_name()
std::string Slic3r::GUI::SavePresetDialog::Item::get_init_preset_name (const std::string & suffix) private
{
    PresetBundle*     preset_bundle = dynamic_cast<SavePresetDialog*>(m_parent)->get_preset_bundle();
    if (!preset_bundle)
        preset_bundle = wxGetApp().preset_bundle;
    m_presets = &preset_bundle->get_presets(m_type);
    const Preset& sel_preset = m_presets->get_selected_preset();
    std::string preset_name = sel_preset.is_default ? "Untitled" :
                              sel_preset.is_system ? (boost::format(("%1% - %2%")) % sel_preset.name % suffix).str() :
                              sel_preset.name;
    // if name contains extension
    if (boost::iends_with(preset_name, ".ini")) {
        size_t len = preset_name.length() - 4;
        preset_name.resize(len);
    }
    return preset_name;
}
References Slic3r::GUI::SavePresetDialog::get_preset_bundle(), Slic3r::PresetBundle::get_presets(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::Preset::is_default, Slic3r::Preset::is_system, m_parent, m_presets, m_type, Slic3r::Preset::name, preset_name(), and Slic3r::GUI::suffix().
Referenced by Item().
init_input_name_ctrl()
void Slic3r::GUI::SavePresetDialog::Item::init_input_name_ctrl (wxBoxSizer * input_name_sizer, std::string preset_name) private
{
    if (m_use_text_ctrl) {
#ifdef _WIN32
        long style = wxBORDER_SIMPLE;
#else
        long style = 0L;
#endif
        m_text_ctrl = new wxTextCtrl(m_parent, wxID_ANY, from_u8(preset_name), wxDefaultPosition, wxSize(35 * wxGetApp().em_unit(), -1), style);
        wxGetApp().UpdateDarkUI(m_text_ctrl);
        m_text_ctrl->Bind(wxEVT_TEXT, [this](wxCommandEvent&) { update(); });
        input_name_sizer->Add(m_text_ctrl,1, wxEXPAND, BORDER_W);
    }
    else {
        std::vector<std::string> values;
        for (const Preset&preset : *m_presets) {
            if (preset.is_default || preset.is_system || preset.is_external)
                continue;
            values.push_back(preset.name);
        }
        m_combo = new wxComboBox(m_parent, wxID_ANY, from_u8(preset_name), wxDefaultPosition, wxSize(35 * wxGetApp().em_unit(), -1));
        for (const std::string&value : values)
            m_combo->Append(from_u8(value));
        m_combo->Bind(wxEVT_TEXT, [this](wxCommandEvent&) { update(); });
#ifdef __WXOSX__
        // Under OSX wxEVT_TEXT wasn't invoked after change selection in combobox,
        // So process wxEVT_COMBOBOX too
        m_combo->Bind(wxEVT_COMBOBOX, [this](wxCommandEvent&) { update(); });
#endif //__WXOSX__
        input_name_sizer->Add(m_combo,    1, wxEXPAND, BORDER_W);
    }
}
References Slic3r::GUI::BORDER_W, Slic3r::GUI::DPIAware< P >::em_unit(), Slic3r::GUI::from_u8(), L, and style.
Referenced by Item(), and Item().
is_valid()
bool Slic3r::GUI::SavePresetDialog::Item::is_valid () const inline
{ return m_valid_type != ValidationType::NoValid; }
References m_valid_type, and NoValid.
Referenced by Slic3r::GUI::PageCustom::is_valid_profile_name().
preset_name()
std::string Slic3r::GUI::SavePresetDialog::Item::preset_name () const inline
{ return m_preset_name; }
References m_preset_name.
Referenced by get_init_preset_name(), and Slic3r::GUI::PageCustom::profile_name().
type()
Preset::Type Slic3r::GUI::SavePresetDialog::Item::type () const inline
{ return m_type; }
References m_type.
update()
void Slic3r::GUI::SavePresetDialog::Item::update () private
{
    m_preset_name = into_u8(m_use_text_ctrl ? m_text_ctrl->GetValue() : m_combo->GetValue());
    m_valid_type = ValidationType::Valid;
    wxString info_line;
    const char* unusable_symbols = "<>[]:/\\|?*\"";
    const std::string unusable_suffix = PresetCollection::get_suffix_modified();//"(modified)";
    for (size_t i = 0; i < std::strlen(unusable_symbols); i++) {
        if (m_preset_name.find_first_of(unusable_symbols[i]) != std::string::npos) {
            info_line = _L("The following characters are not allowed in the name") + ": " + unusable_symbols;
            m_valid_type = ValidationType::NoValid;
            break;
        }
    }
    if (m_valid_type == ValidationType::Valid && m_preset_name.find(unusable_suffix) != std::string::npos) {
        info_line = _L("The following suffix is not allowed in the name") + ":\n\t" +
                    from_u8(unusable_suffix);
        m_valid_type = ValidationType::NoValid;
    }
    if (m_valid_type == ValidationType::Valid && m_preset_name == "- default -") {
        info_line = _L("This name is reserved, use another.");
        m_valid_type = ValidationType::NoValid;
    }
    const Preset* existing = get_existing_preset();
    if (m_valid_type == ValidationType::Valid && existing && (existing->is_default || existing->is_system)) {
        info_line = m_use_text_ctrl ? _L("This name is used for a system profile name, use another.") :
                             _L("Cannot overwrite a system profile.");
        m_valid_type = ValidationType::NoValid;
    }
    if (m_valid_type == ValidationType::Valid && existing && (existing->is_external)) {
        info_line = m_use_text_ctrl ? _L("This name is used for an external profile name, use another.") :
                             _L("Cannot overwrite an external profile.");
        m_valid_type = ValidationType::NoValid;
    }
    SavePresetDialog* dlg = dynamic_cast<SavePresetDialog*>(m_parent);
    if (m_valid_type == ValidationType::Valid && existing)
    {
        if (m_presets && m_preset_name == m_presets->get_selected_preset_name()) {
            if ((!m_use_text_ctrl && m_presets->get_edited_preset().is_dirty) ||
                (dlg && dlg->get_preset_bundle())) // means that we save modifications from the DiffDialog
                info_line = _L("Save preset modifications to existing user profile");
            m_valid_type = ValidationType::Valid;
        }
        else {
            if (existing->is_compatible)
                info_line = from_u8((boost::format(_u8L("Preset with name \"%1%\" already exists.")) % m_preset_name).str());
            else
                info_line = from_u8((boost::format(_u8L("Preset with name \"%1%\" already exists and is incompatible with selected printer.")) % m_preset_name).str());
            info_line += "\n" + _L("Note: This preset will be replaced after saving");
            m_valid_type = ValidationType::Warning;
        }
    }
    if (m_valid_type == ValidationType::Valid && m_preset_name.empty()) {
        info_line = _L("The name cannot be empty.");
        m_valid_type = ValidationType::NoValid;
    }
#ifdef __WXMSW__
    const int max_path_length = MAX_PATH;
#else
    const int max_path_length = 255;
#endif
    if (m_valid_type == ValidationType::Valid && m_presets && m_presets->path_from_name(m_preset_name).length() >= max_path_length) {
        info_line = _L("The name is too long.");
        m_valid_type = ValidationType::NoValid;
    }
    if (m_valid_type == ValidationType::Valid && m_preset_name.find_first_of(' ') == 0) {
        info_line = _L("The name cannot start with space character.");
        m_valid_type = ValidationType::NoValid;
    }
    if (m_valid_type == ValidationType::Valid && m_preset_name.find_last_of(' ') == m_preset_name.length()-1) {
        info_line = _L("The name cannot end with space character.");
        m_valid_type = ValidationType::NoValid;
    }
    if (m_valid_type == ValidationType::Valid && m_presets && m_presets->get_preset_name_by_alias(m_preset_name) != m_preset_name) {
        info_line = _L("The name cannot be the same as a preset alias name.");
        m_valid_type = ValidationType::NoValid;
    }
    if ((dlg && !dlg->get_info_line_extention().IsEmpty()) && m_valid_type != ValidationType::NoValid)
        info_line += "\n\n" + dlg->get_info_line_extention();
    m_valid_label->SetLabel(info_line);
    m_valid_label->Show(!info_line.IsEmpty());
    update_valid_bmp();
    if (dlg && m_type == Preset::TYPE_PRINTER)
        dlg->update_info_for_edit_ph_printer(m_preset_name);
    m_parent->Layout();
}
References _L, _u8L, Slic3r::GUI::from_u8(), Slic3r::GUI::SavePresetDialog::get_info_line_extention(), Slic3r::GUI::SavePresetDialog::get_preset_bundle(), Slic3r::PresetCollection::get_suffix_modified(), Slic3r::GUI::into_u8(), Slic3r::Preset::is_compatible, Slic3r::Preset::is_default, Slic3r::Preset::is_external, Slic3r::Preset::is_system, Slic3r::Preset::TYPE_PRINTER, and Slic3r::GUI::SavePresetDialog::update_info_for_edit_ph_printer().
Referenced by Item(), and Item().
update_valid_bmp()
void Slic3r::GUI::SavePresetDialog::Item::update_valid_bmp ()
{
    std::string bmp_name =  m_valid_type == ValidationType::Warning ? "exclamation_manifold" :
                            m_valid_type == ValidationType::NoValid ? "exclamation"          : "tick_mark" ;
    m_valid_bmp->SetBitmap(*get_bmp_bundle(bmp_name));
}
References get_bmp_bundle().
Member Data Documentation
m_combo
wxComboBox* Slic3r::GUI::SavePresetDialog::Item::m_combo {nullptr} private
m_parent
wxWindow* Slic3r::GUI::SavePresetDialog::Item::m_parent {nullptr} private
Referenced by Item(), and get_init_preset_name().
m_preset_name
std::string Slic3r::GUI::SavePresetDialog::Item::m_preset_name private
Referenced by Item(), and preset_name().
m_presets
PresetCollection* Slic3r::GUI::SavePresetDialog::Item::m_presets {nullptr} private
Referenced by get_init_preset_name().
m_printer_technology
PrinterTechnology Slic3r::GUI::SavePresetDialog::Item::m_printer_technology {ptAny} private
m_text_ctrl
wxTextCtrl* Slic3r::GUI::SavePresetDialog::Item::m_text_ctrl {nullptr} private
m_type
Preset::Type Slic3r::GUI::SavePresetDialog::Item::m_type {Preset::TYPE_INVALID} private
Referenced by Item(), get_init_preset_name(), and type().
m_use_text_ctrl
bool Slic3r::GUI::SavePresetDialog::Item::m_use_text_ctrl {true} private
m_valid_bmp
wxStaticBitmap* Slic3r::GUI::SavePresetDialog::Item::m_valid_bmp {nullptr} private
Referenced by Item(), and Item().
m_valid_label
wxStaticText* Slic3r::GUI::SavePresetDialog::Item::m_valid_label {nullptr} private
Referenced by Item(), and Item().
m_valid_type
ValidationType Slic3r::GUI::SavePresetDialog::Item::m_valid_type {ValidationType::NoValid} private
Referenced by is_valid().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/SavePresetDialog.hpp
src/slic3r/GUI/SavePresetDialog.cpp