Prusa Slicer: Eigen::internal::BandMatrixBase< Derived > Class Template Reference
Eigen::internal::BandMatrixBase< Derived > Class Template Reference
#include <src/eigen/Eigen/src/Core/BandMatrix.h>
Classes
struct DiagonalIntReturnType
Public Types
enum {
Flags = internal::traits<Derived>::Flags , CoeffReadCost = internal::traits<Derived>::CoeffReadCost , RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime ,
MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime , MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , Supers = internal::traits<Derived>::Supers , Subs = internal::traits<Derived>::Subs ,
Options = internal::traits<Derived>::Options
}
typedef internal::traits< Derived >::Scalar Scalar
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType::StorageIndex StorageIndex
typedef internal::traits< Derived >::CoefficientsType CoefficientsType
typedef EigenBase< Derived > Base
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
Index supers () const
Index subs () const
const CoefficientsType & coeffs () const
CoefficientsType & coeffs ()
Block< CoefficientsType, Dynamic, 1 > col (Index i)
Block< CoefficientsType, 1, SizeAtCompileTime > diagonal ()
const Block< const CoefficientsType, 1, SizeAtCompileTime > diagonal () const
template<int N>
DiagonalIntReturnType< N >::Type diagonal ()
template<int N>
const DiagonalIntReturnType< N >::Type diagonal () const
Block< CoefficientsType, 1, Dynamic > diagonal (Index i)
const Block< const CoefficientsType, 1, Dynamic > diagonal (Index i) const
template<typename Dest >
void evalTo (Dest &dst) const
DenseMatrixType toDenseMatrix () const
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Types
enum { DataRowsAtCompileTime , SizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime) }
Protected Member Functions
Index diagonalLength (Index i) const
Detailed Description
template<typename Derived>
class Eigen::internal::BandMatrixBase< Derived >
Member Typedef Documentation
Base
template<typename Derived > typedef EigenBase<Derived> Eigen::internal::BandMatrixBase< Derived >::Base
CoefficientsType
template<typename Derived > typedef internal::traits<Derived>::CoefficientsType Eigen::internal::BandMatrixBase< Derived >::CoefficientsType
DenseMatrixType
template<typename Derived > typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime> Eigen::internal::BandMatrixBase< Derived >::DenseMatrixType
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::internal::BandMatrixBase< Derived >::Scalar
StorageIndex
template<typename Derived > typedef DenseMatrixType::StorageIndex Eigen::internal::BandMatrixBase< Derived >::StorageIndex
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::EigenBase< Derived >::StorageKind inherited
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
Flags
CoeffReadCost
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Supers
Subs
Options
         {
      Flags = internal::traits<Derived>::Flags,
      CoeffReadCost = internal::traits<Derived>::CoeffReadCost,
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
      Supers = internal::traits<Derived>::Supers,
      Subs   = internal::traits<Derived>::Subs,
      Options = internal::traits<Derived>::Options
    };
anonymous enum
template<typename Derived > anonymous enum protected
Enumerator
DataRowsAtCompileTime
SizeAtCompileTime
         {
      DataRowsAtCompileTime = ((Supers!=Dynamic) && (Subs!=Dynamic))
                            ? 1 + Supers + Subs
                            : Dynamic,
      SizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime)
    };
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
coeffs() [1/2]
template<typename Derived > CoefficientsType & Eigen::internal::BandMatrixBase< Derived >::coeffs () inline
Returns
an expression of the underlying coefficient matrix
{ return derived().coeffs(); }
References Eigen::internal::BandMatrixBase< Derived >::derived().
coeffs() [2/2]
template<typename Derived > const CoefficientsType & Eigen::internal::BandMatrixBase< Derived >::coeffs () const inline
Returns
an expression of the underlying coefficient matrix
{ return derived().coeffs(); }
References Eigen::internal::BandMatrixBase< Derived >::derived().
Referenced by Eigen::internal::BandMatrixBase< Derived >::col(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), and Eigen::internal::BandMatrixBase< Derived >::diagonal().
col()
template<typename Derived > Block< CoefficientsType, Dynamic, 1 > Eigen::internal::BandMatrixBase< Derived >::col (Index i) inline
Returns
a vector expression of the i -th column, only the meaningful part is returned.
Warning
the internal storage must be column major.
    {
      EIGEN_STATIC_ASSERT((Options&RowMajor)==0,THIS_METHOD_IS_ONLY_FOR_COLUMN_MAJOR_MATRICES);
      Index start = 0;
      Index len = coeffs().rows();
      if (i<=supers())
      {
        start = supers()-i;
        len = (std::min)(rows(),std::max<Index>(0,coeffs().rows() - (supers()-i)));
      }
      else if (i>=rows()-subs())
        len = std::max<Index>(0,coeffs().rows() - (i + 1 - rows() + subs()));
      return Block<CoefficientsType,Dynamic,1>(coeffs(), start, i, len, 1);
    }
References Eigen::internal::BandMatrixBase< Derived >::coeffs(), EIGEN_STATIC_ASSERT, Eigen::internal::BandMatrixBase< Derived >::Options, Eigen::RowMajor, Eigen::internal::BandMatrixBase< Derived >::rows(), Eigen::internal::BandMatrixBase< Derived >::subs(), and Eigen::internal::BandMatrixBase< Derived >::supers().
cols()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::cols () const inline
Returns
the number of columns.
See also
rows(), ColsAtCompileTime
{ return derived().cols(); }
Referenced by Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonalLength(), Eigen::internal::BandMatrixBase< Derived >::evalTo(), and Eigen::internal::BandMatrixBase< Derived >::toDenseMatrix().
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::derived () inline
Returns
a reference to the derived object
{ return *static_cast<Derived*>(this); }
Referenced by Eigen::internal::BandMatrixBase< Derived >::coeffs(), Eigen::internal::BandMatrixBase< Derived >::coeffs(), Eigen::internal::BandMatrixBase< Derived >::subs(), and Eigen::internal::BandMatrixBase< Derived >::supers().
derived() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::derived () const inline
Returns
a const reference to the derived object
{ return *static_cast<const Derived*>(this); }
diagonal() [1/6]
template<typename Derived > Block< CoefficientsType, 1, SizeAtCompileTime > Eigen::internal::BandMatrixBase< Derived >::diagonal () inline
Returns
a vector expression of the main diagonal
    { return Block<CoefficientsType,1,SizeAtCompileTime>(coeffs(),supers(),0,1,(std::min)(rows(),cols())); }
References Eigen::internal::BandMatrixBase< Derived >::coeffs(), Eigen::internal::BandMatrixBase< Derived >::cols(), Eigen::internal::BandMatrixBase< Derived >::rows(), and Eigen::internal::BandMatrixBase< Derived >::supers().
Referenced by Eigen::internal::BandMatrixBase< Derived >::evalTo().
diagonal() [2/6]
template<typename Derived > template<int N> DiagonalIntReturnType< N >::Type Eigen::internal::BandMatrixBase< Derived >::diagonal () inline
Returns
a vector expression of the N -th sub or super diagonal
    {
      return typename DiagonalIntReturnType<N>::BuildType(coeffs(), supers()-N, (std::max)(0,N), 1, diagonalLength(N));
    }
References Eigen::internal::BandMatrixBase< Derived >::coeffs(), Eigen::internal::BandMatrixBase< Derived >::diagonalLength(), and Eigen::internal::BandMatrixBase< Derived >::supers().
diagonal() [3/6]
template<typename Derived > const Block< const CoefficientsType, 1, SizeAtCompileTime > Eigen::internal::BandMatrixBase< Derived >::diagonal () const inline
Returns
a vector expression of the main diagonal (const version)
    { return Block<const CoefficientsType,1,SizeAtCompileTime>(coeffs(),supers(),0,1,(std::min)(rows(),cols())); }
References Eigen::internal::BandMatrixBase< Derived >::coeffs(), Eigen::internal::BandMatrixBase< Derived >::cols(), Eigen::internal::BandMatrixBase< Derived >::rows(), and Eigen::internal::BandMatrixBase< Derived >::supers().
diagonal() [4/6]
template<typename Derived > template<int N> const DiagonalIntReturnType< N >::Type Eigen::internal::BandMatrixBase< Derived >::diagonal () const inline
Returns
a vector expression of the N -th sub or super diagonal
    {
      return typename DiagonalIntReturnType<N>::BuildType(coeffs(), supers()-N, (std::max)(0,N), 1, diagonalLength(N));
    }
References Eigen::internal::BandMatrixBase< Derived >::coeffs(), Eigen::internal::BandMatrixBase< Derived >::diagonalLength(), and Eigen::internal::BandMatrixBase< Derived >::supers().
diagonal() [5/6]
template<typename Derived > Block< CoefficientsType, 1, Dynamic > Eigen::internal::BandMatrixBase< Derived >::diagonal (Index i) inline
Returns
a vector expression of the i -th sub or super diagonal
    {
      eigen_assert((i<0 && -i<=subs()) || (i>=0 && i<=supers()));
      return Block<CoefficientsType,1,Dynamic>(coeffs(), supers()-i, std::max<Index>(0,i), 1, diagonalLength(i));
    }
References Eigen::internal::BandMatrixBase< Derived >::coeffs(), Eigen::internal::BandMatrixBase< Derived >::diagonalLength(), eigen_assert, Eigen::internal::BandMatrixBase< Derived >::subs(), and Eigen::internal::BandMatrixBase< Derived >::supers().
diagonal() [6/6]
template<typename Derived > const Block< const CoefficientsType, 1, Dynamic > Eigen::internal::BandMatrixBase< Derived >::diagonal (Index i) const inline
Returns
a vector expression of the i -th sub or super diagonal
    {
      eigen_assert((i<0 && -i<=subs()) || (i>=0 && i<=supers()));
      return Block<const CoefficientsType,1,Dynamic>(coeffs(), supers()-i, std::max<Index>(0,i), 1, diagonalLength(i));
    }
References Eigen::internal::BandMatrixBase< Derived >::coeffs(), Eigen::internal::BandMatrixBase< Derived >::diagonalLength(), eigen_assert, Eigen::internal::BandMatrixBase< Derived >::subs(), and Eigen::internal::BandMatrixBase< Derived >::supers().
diagonalLength()
template<typename Derived > Index Eigen::internal::BandMatrixBase< Derived >::diagonalLength (Index i) const inline protected
    { return i<0 ? (std::min)(cols(),rows()+i) : (std::min)(rows(),cols()-i); }
References Eigen::internal::BandMatrixBase< Derived >::cols(), and Eigen::internal::BandMatrixBase< Derived >::rows().
Referenced by Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), and Eigen::internal::BandMatrixBase< Derived >::diagonal().
evalTo()
template<typename Derived > template<typename Dest > void Eigen::internal::BandMatrixBase< Derived >::evalTo (Dest & dst) const inline
    {
      dst.resize(rows(),cols());
      dst.setZero();
      dst.diagonal() = diagonal();
      for (Index i=1; i<=supers();++i)
        dst.diagonal(i) = diagonal(i);
      for (Index i=1; i<=subs();++i)
        dst.diagonal(-i) = diagonal(-i);
    }
References Eigen::internal::BandMatrixBase< Derived >::cols(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::rows(), Eigen::internal::BandMatrixBase< Derived >::subs(), and Eigen::internal::BandMatrixBase< Derived >::supers().
Referenced by Eigen::internal::BandMatrixBase< Derived >::toDenseMatrix().
rows()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::rows () const inline
Returns
the number of rows.
See also
cols(), RowsAtCompileTime
{ return derived().rows(); }
Referenced by Eigen::internal::BandMatrixBase< Derived >::col(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonalLength(), Eigen::internal::BandMatrixBase< Derived >::evalTo(), and Eigen::internal::BandMatrixBase< Derived >::toDenseMatrix().
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
References Eigen::EigenBase< Derived >::cols(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
subs()
template<typename Derived > Index Eigen::internal::BandMatrixBase< Derived >::subs () const inline
Returns
the number of sub diagonals
{ return derived().subs(); }
References Eigen::internal::BandMatrixBase< Derived >::derived().
Referenced by Eigen::internal::BandMatrixBase< Derived >::col(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), and Eigen::internal::BandMatrixBase< Derived >::evalTo().
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
supers()
template<typename Derived > Index Eigen::internal::BandMatrixBase< Derived >::supers () const inline
Returns
the number of super diagonals
{ return derived().supers(); }
References Eigen::internal::BandMatrixBase< Derived >::derived().
Referenced by Eigen::internal::BandMatrixBase< Derived >::col(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), Eigen::internal::BandMatrixBase< Derived >::diagonal(), and Eigen::internal::BandMatrixBase< Derived >::evalTo().
toDenseMatrix()
template<typename Derived > DenseMatrixType Eigen::internal::BandMatrixBase< Derived >::toDenseMatrix () const inline
    {
      DenseMatrixType res(rows(),cols());
      evalTo(res);
      return res;
    }
References Eigen::internal::BandMatrixBase< Derived >::cols(), Eigen::internal::BandMatrixBase< Derived >::evalTo(), and Eigen::internal::BandMatrixBase< Derived >::rows().
Referenced by Eigen::BDCSVD< _MatrixType >::compute().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/BandMatrix.h