Prusa Slicer: libnest2d::SelectionStrategyLike< SelectionStrategy > Class Template Reference
libnest2d::SelectionStrategyLike< SelectionStrategy > Class Template Reference
#include <src/libnest2d/include/libnest2d/nester.hpp>
Public Types
using RawShape = typename SelectionStrategy::ShapeType
using Item = _Item< RawShape >
using PackGroup = _PackGroup< RawShape >
using Config = typename SelectionStrategy::Config
Public Member Functions
void configure (const Config &config)
Provide a different configuration for the selection strategy.
void progressIndicator (ProgressFunction fn)
A function callback which should be called whenever an item or a group of items where successfully packed.
void stopCondition (StopCondition cond)
template<class TPlacer , class TIterator , class TBin = typename PlacementStrategyLike<TPlacer>::BinType, class PConfig = typename PlacementStrategyLike<TPlacer>::Config>
void packItems (TIterator first, TIterator last, TBin &&bin, PConfig &&config=PConfig())
A method to start the calculation on the input sequence.
const PackGroup & getResult () const
Get the items for a particular bin.
int lastPackedBinId () const
void clear ()
Private Attributes
SelectionStrategy impl_
Detailed Description
template<class SelectionStrategy>
class libnest2d::SelectionStrategyLike< SelectionStrategy >
A wrapper interface (trait) class for any selections strategy provider.
Member Typedef Documentation
Config
template<class SelectionStrategy > using libnest2d::SelectionStrategyLike< SelectionStrategy >::Config = typename SelectionStrategy::Config
Item
template<class SelectionStrategy > using libnest2d::SelectionStrategyLike< SelectionStrategy >::Item = _Item<RawShape>
PackGroup
template<class SelectionStrategy > using libnest2d::SelectionStrategyLike< SelectionStrategy >::PackGroup = _PackGroup<RawShape>
RawShape
template<class SelectionStrategy > using libnest2d::SelectionStrategyLike< SelectionStrategy >::RawShape = typename SelectionStrategy::ShapeType
Member Function Documentation
clear()
template<class SelectionStrategy > void libnest2d::SelectionStrategyLike< SelectionStrategy >::clear () inline
{ impl_.clear(); }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::impl_.
configure()
template<class SelectionStrategy > void libnest2d::SelectionStrategyLike< SelectionStrategy >::configure (const Config & config) inline
Provide a different configuration for the selection strategy.
Note that it depends on the particular placer implementation how it reacts to config changes in the middle of a calculation.
Parameters
config The configuration object defined by the selection strategy.
{
        impl_.configure(config);
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::impl_.
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::_Nester(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure().
getResult()
template<class SelectionStrategy > const PackGroup & libnest2d::SelectionStrategyLike< SelectionStrategy >::getResult () const inline
Get the items for a particular bin.
Parameters
binIndex The index of the requested bin.
Returns
Returns a list of all items packed into the requested bin.
{
        return impl_.getResult();
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::impl_.
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::execute(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::lastResult().
lastPackedBinId()
template<class SelectionStrategy > int libnest2d::SelectionStrategyLike< SelectionStrategy >::lastPackedBinId () const inline
{
        return impl_.lastPackedBinId();
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::impl_.
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::lastPackedBinId().
packItems()
template<class SelectionStrategy > template<class TPlacer , class TIterator , class TBin = typename PlacementStrategyLike<TPlacer>::BinType, class PConfig = typename PlacementStrategyLike<TPlacer>::Config> void libnest2d::SelectionStrategyLike< SelectionStrategy >::packItems (TIterator first, TIterator last, TBin && bin, PConfig && config = PConfig()) inline
A method to start the calculation on the input sequence.
Template Parameters
TPlacer The only mandatory template parameter is the type of placer compatible with the PlacementStrategyLike interface.
Parameters
first,last The first and last iterator if the input sequence. It can be only an iterator of a type convertible to Item.
bin. The shape of the bin. It has to be supported by the placement strategy.
An optional config object for the placer.
    {
        impl_.template packItems<TPlacer>(first, last,
                                 std::forward<TBin>(bin),
                                 std::forward<PConfig>(config));
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::impl_.
progressIndicator()
template<class SelectionStrategy > void libnest2d::SelectionStrategyLike< SelectionStrategy >::progressIndicator (ProgressFunction fn) inline
A function callback which should be called whenever an item or a group of items where successfully packed.
Parameters
fn A function callback object taking one unsigned integer as the number of the remaining items to pack.
{ impl_.progressIndicator(fn); }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::impl_.
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::progressIndicator().
stopCondition()
template<class SelectionStrategy > void libnest2d::SelectionStrategyLike< SelectionStrategy >::stopCondition (StopCondition cond) inline
{ impl_.stopCondition(cond); }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::impl_.
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::stopCondition().
Member Data Documentation
impl_
template<class SelectionStrategy > SelectionStrategy libnest2d::SelectionStrategyLike< SelectionStrategy >::impl_ private
Referenced by libnest2d::SelectionStrategyLike< SelectionStrategy >::clear(), libnest2d::SelectionStrategyLike< SelectionStrategy >::configure(), libnest2d::SelectionStrategyLike< SelectionStrategy >::getResult(), libnest2d::SelectionStrategyLike< SelectionStrategy >::lastPackedBinId(), libnest2d::SelectionStrategyLike< SelectionStrategy >::packItems(), libnest2d::SelectionStrategyLike< SelectionStrategy >::progressIndicator(), and libnest2d::SelectionStrategyLike< SelectionStrategy >::stopCondition().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/nester.hpp