Prusa Slicer: Slic3r::GUI::ProjectDirtyStateManager Class Reference
Slic3r::GUI::ProjectDirtyStateManager Class Reference
#include <src/slic3r/GUI/ProjectDirtyStateManager.hpp>
Public Member Functions
void update_from_undo_redo_stack (bool dirty)
void update_from_presets ()
void update_from_preview ()
void reset_after_save ()
void reset_initial_presets ()
bool is_dirty () const
bool is_presets_dirty () const
Private Attributes
bool m_plater_dirty { false }
bool m_presets_dirty { false }
bool m_project_config_dirty { false }
bool m_custom_gcode_per_print_z_dirty { false }
std::array< std::string, Preset::TYPE_COUNT > m_initial_presets
DynamicPrintConfig m_initial_project_config
CustomGCode::Info m_initial_custom_gcode_per_print_z
Detailed Description
Member Function Documentation
is_dirty()
bool Slic3r::GUI::ProjectDirtyStateManager::is_dirty () const inline
{ return m_plater_dirty || m_project_config_dirty || m_presets_dirty || m_custom_gcode_per_print_z_dirty; }
References m_custom_gcode_per_print_z_dirty, m_plater_dirty, m_presets_dirty, and m_project_config_dirty.
Referenced by Slic3r::GUI::Plater::priv::is_project_dirty(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), and update_from_preview().
is_presets_dirty()
bool Slic3r::GUI::ProjectDirtyStateManager::is_presets_dirty () const inline
{ return m_presets_dirty; }
References m_presets_dirty.
Referenced by Slic3r::GUI::Plater::priv::is_presets_dirty().
reset_after_save()
void Slic3r::GUI::ProjectDirtyStateManager::reset_after_save ()
{
    this->reset_initial_presets();
    m_plater_dirty  = false;
    m_presets_dirty = false;
    m_project_config_dirty = false;
    m_custom_gcode_per_print_z_dirty = false;
    wxGetApp().mainframe->update_title();
}
References m_custom_gcode_per_print_z_dirty, m_plater_dirty, m_presets_dirty, m_project_config_dirty, and reset_initial_presets().
Referenced by Slic3r::GUI::Plater::priv::reset_project_dirty_after_save().
reset_initial_presets()
void Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets ()
{
    m_initial_presets.fill(std::string{});
    GUI_App &app = wxGetApp();
    for (const PresetCollection *preset_collection : app.get_active_preset_collections())
        m_initial_presets[preset_collection->type()] = preset_collection->get_selected_preset_name();
    m_initial_project_config = app.preset_bundle->project_config;
    m_initial_custom_gcode_per_print_z = app.model().custom_gcode_per_print_z;
}
References Slic3r::Model::custom_gcode_per_print_z, Slic3r::GUI::GUI_App::get_active_preset_collections(), m_initial_custom_gcode_per_print_z, m_initial_presets, m_initial_project_config, Slic3r::GUI::GUI_App::model(), Slic3r::GUI::GUI_App::preset_bundle, and Slic3r::PresetBundle::project_config.
Referenced by reset_after_save(), and Slic3r::GUI::Plater::priv::reset_project_dirty_initial_presets().
update_from_presets()
void Slic3r::GUI::ProjectDirtyStateManager::update_from_presets ()
{
    m_presets_dirty = false;
    // check switching of the presets only for exist/loaded project, but not for new
    GUI_App &app = wxGetApp();
    bool has_project = ! app.plater()->get_project_filename().IsEmpty();
    for (const PresetCollection *preset_collection : app.get_active_preset_collections()) {
        auto type = preset_collection->type();
        m_presets_dirty |= (has_project && !m_initial_presets[type].empty() && m_initial_presets[type] != preset_collection->get_selected_preset_name()) || preset_collection->saved_is_dirty();
    }
    m_project_config_dirty = m_initial_project_config != app.preset_bundle->project_config;
    app.mainframe->update_title();
}
References Slic3r::GUI::GUI_App::get_active_preset_collections(), Slic3r::GUI::Plater::get_project_filename(), m_initial_presets, m_initial_project_config, m_presets_dirty, m_project_config_dirty, Slic3r::GUI::GUI_App::mainframe, Slic3r::GUI::GUI_App::plater(), Slic3r::GUI::GUI_App::preset_bundle, Slic3r::PresetBundle::project_config, and Slic3r::GUI::MainFrame::update_title().
Referenced by Slic3r::GUI::Plater::priv::update_project_dirty_from_presets().
update_from_preview()
void Slic3r::GUI::ProjectDirtyStateManager::update_from_preview ()
{
    const bool is_dirty = m_initial_custom_gcode_per_print_z != wxGetApp().model().custom_gcode_per_print_z;
    if (m_custom_gcode_per_print_z_dirty != is_dirty) {
        m_custom_gcode_per_print_z_dirty = is_dirty;
        wxGetApp().mainframe->update_title();
    }
}
References is_dirty(), m_custom_gcode_per_print_z_dirty, and m_initial_custom_gcode_per_print_z.
update_from_undo_redo_stack()
void Slic3r::GUI::ProjectDirtyStateManager::update_from_undo_redo_stack (bool dirty)
{
    if (m_plater_dirty != dirty) {
        m_plater_dirty = dirty;
        if (const Plater *plater = wxGetApp().plater(); plater && wxGetApp().initialized())
            wxGetApp().mainframe->update_title();
    }
}
References m_plater_dirty, and Slic3r::GUI::plater().
Member Data Documentation
m_custom_gcode_per_print_z_dirty
bool Slic3r::GUI::ProjectDirtyStateManager::m_custom_gcode_per_print_z_dirty { false } private
Referenced by is_dirty(), reset_after_save(), and update_from_preview().
m_initial_custom_gcode_per_print_z
CustomGCode::Info Slic3r::GUI::ProjectDirtyStateManager::m_initial_custom_gcode_per_print_z private
Referenced by reset_initial_presets(), and update_from_preview().
m_initial_presets
std::array<std::string, Preset::TYPE_COUNT> Slic3r::GUI::ProjectDirtyStateManager::m_initial_presets private
Referenced by reset_initial_presets(), and update_from_presets().
m_initial_project_config
DynamicPrintConfig Slic3r::GUI::ProjectDirtyStateManager::m_initial_project_config private
Referenced by reset_initial_presets(), and update_from_presets().
m_plater_dirty
bool Slic3r::GUI::ProjectDirtyStateManager::m_plater_dirty { false } private
Referenced by is_dirty(), reset_after_save(), and update_from_undo_redo_stack().
m_presets_dirty
bool Slic3r::GUI::ProjectDirtyStateManager::m_presets_dirty { false } private
Referenced by is_dirty(), is_presets_dirty(), reset_after_save(), and update_from_presets().
m_project_config_dirty
bool Slic3r::GUI::ProjectDirtyStateManager::m_project_config_dirty { false } private
Referenced by is_dirty(), reset_after_save(), and update_from_presets().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ProjectDirtyStateManager.hpp
src/slic3r/GUI/ProjectDirtyStateManager.cpp