Prusa Slicer: Slic3r::GUI::GLGizmosManager Class Reference
Slic3r::GUI::GLGizmosManager Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosManager.hpp>
Classes
struct Layout
Public Types
enum EType : unsigned char {
Move , Scale , Rotate , Flatten ,
Cut , Hollow , SlaSupports , FdmSupports ,
Seam , MmuSegmentation , Measure , Emboss ,
Simplify , Undefined
}
using Timestamp = uint64_t
Public Member Functions
GLGizmosManager (GLCanvas3D &parent)
bool init ()
bool init_arrow (const std::string &filename)
template<class Archive >
void load (Archive &ar)
template<class Archive >
void save (Archive &ar) const
bool is_enabled () const
void set_enabled (bool enable)
void set_overlay_icon_size (float size)
void set_overlay_scale (float scale)
void refresh_on_off_state ()
void reset_all_states ()
bool open_gizmo (EType type)
bool check_gizmos_closed_except (EType) const
void set_hover_id (int id)
void update_data ()
Distribute information about different data into active gizmo Should be called when selection changed.
EType get_current_type () const
GLGizmoBase * get_current () const
GLGizmoBase * get_gizmo (GLGizmosManager::EType type) const
EType get_gizmo_from_name (const std::string &gizmo_name) const
bool is_running () const
bool handle_shortcut (int key)
bool is_dragging () const
ClippingPlane get_clipping_plane () const
bool wants_reslice_supports_on_undo () const
bool is_in_editing_mode (bool error_notification=false) const
bool is_hiding_instances () const
void render_current_gizmo () const
void render_painter_gizmo ()
void render_overlay ()
void render_arrow (const GLCanvas3D &parent, EType highlighted_type) const
std::string get_tooltip () const
bool on_mouse (const wxMouseEvent &mouse_event)
bool on_mouse_wheel (const wxMouseEvent &evt)
bool on_char (wxKeyEvent &evt)
bool on_key (wxKeyEvent &evt)
void update_after_undo_redo (const UndoRedo::Snapshot &snapshot)
int get_selectable_icons_cnt () const
void set_highlight (EType gizmo, bool highlight_shown)
bool get_highlight_state () const
ObjectID id () const
virtual Timestamp timestamp () const
Static Public Attributes
static const float Default_Icons_Size = 64
Protected Member Functions
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Private Member Functions
std::vector< size_t > get_selectable_idxs () const
EType get_gizmo_from_mouse (const Vec2d &mouse_pos) const
bool activate_gizmo (EType type)
bool gizmos_toolbar_on_mouse (const wxMouseEvent &mouse_event)
Process mouse event on gizmo toolbar.
bool gizmo_event (SLAGizmoEventType action, const Vec2d &mouse_position=Vec2d::Zero(), bool shift_down=false, bool alt_down=false, bool control_down=false)
void render_background (float left, float top, float right, float bottom, float border_w, float border_h) const
void do_render_overlay () const
float get_scaled_total_height () const
float get_scaled_total_width () const
bool generate_icons_texture ()
void update_hover_state (const EType &type)
bool grabber_contains_mouse () const
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
GLCanvas3D & m_parent
bool m_enabled
std::vector< std::unique_ptr< GLGizmoBase > > m_gizmos
GLTexture m_icons_texture
bool m_icons_texture_dirty
BackgroundTexture m_background_texture
GLTexture m_arrow_texture
Layout m_layout
EType m_current
EType m_hover
std::pair< EType, bool > m_highlight
std::string m_tooltip
bool m_serializing
std::unique_ptr< CommonGizmosDataPool > m_common_gizmos_data
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Member Enumeration Documentation
EType
enum Slic3r::GUI::GLGizmosManager::EType : unsigned char
Enumerator
Move
Scale
Rotate
Flatten
Cut
Hollow
SlaSupports
FdmSupports
Seam
MmuSegmentation
Measure
Emboss
Simplify
Undefined
    {
        // Order must match index in m_gizmos!
        Move,
        Scale,
        Rotate,
        Flatten,
        Cut,
        Hollow,
        SlaSupports,
        FdmSupports,
        Seam,
        MmuSegmentation,
        Measure,
        Emboss,
        Simplify,
        Undefined
    };
Constructor & Destructor Documentation
GLGizmosManager()
Slic3r::GUI::GLGizmosManager::GLGizmosManager (GLCanvas3D & parent) explicit
    : m_parent(parent)
    , m_enabled(false)
    , m_icons_texture_dirty(true)
    , m_current(Undefined)
    , m_hover(Undefined)
    , m_tooltip("")
    , m_serializing(false)
{
}
Member Function Documentation
activate_gizmo()
bool Slic3r::GUI::GLGizmosManager::activate_gizmo (EType type) private
{
    assert(!m_gizmos.empty());
    // already activated
    if (m_current == type) return true;
    if (m_current != Undefined) {
        // clean up previous gizmo
        GLGizmoBase &old_gizmo = *m_gizmos[m_current];
        old_gizmo.set_state(GLGizmoBase::Off);
        if (old_gizmo.get_state() != GLGizmoBase::Off)
            return false; // gizmo refused to be turned off, do nothing.
        old_gizmo.unregister_raycasters_for_picking();
        if (!m_serializing && old_gizmo.wants_enter_leave_snapshots())
            Plater::TakeSnapshot
                snapshot(wxGetApp().plater(),
                         old_gizmo.get_gizmo_leaving_text(),
                         UndoRedo::SnapshotType::LeavingGizmoWithAction);
    }
    if (type == Undefined) {
        // it is deactivation of gizmo
        m_current = Undefined;
        if (m_parent.current_printer_technology() == ptSLA)
            m_parent.detect_sla_view_type();
        return true;
    }
    // set up new gizmo
    GLGizmoBase& new_gizmo = *m_gizmos[type];
    if (!new_gizmo.is_activable()) return false;
    if (!m_serializing && new_gizmo.wants_enter_leave_snapshots())
        Plater::TakeSnapshot snapshot(wxGetApp().plater(),
                                      new_gizmo.get_gizmo_entering_text(),
                                      UndoRedo::SnapshotType::EnteringGizmo);
    m_current = type;
    new_gizmo.set_state(GLGizmoBase::On);
    if (new_gizmo.get_state() != GLGizmoBase::On) {
        m_current = Undefined;
        return false; // gizmo refused to be turned on.
    }
    if (m_parent.current_printer_technology() == ptSLA)
        m_parent.set_sla_view_type(GLCanvas3D::ESLAViewType::Original);
    new_gizmo.register_raycasters_for_picking();
    // sucessful activation of gizmo
    return true;
}
References Slic3r::GUI::GLCanvas3D::current_printer_technology(), Slic3r::GUI::GLCanvas3D::detect_sla_view_type(), Slic3r::UndoRedo::EnteringGizmo, Slic3r::GUI::GLGizmoBase::get_gizmo_entering_text(), Slic3r::GUI::GLGizmoBase::get_gizmo_leaving_text(), Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoBase::is_activable(), Slic3r::UndoRedo::LeavingGizmoWithAction, m_current, m_gizmos, m_parent, m_serializing, Slic3r::GUI::GLGizmoBase::Off, Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::GLCanvas3D::Original, Slic3r::GUI::plater(), Slic3r::ptSLA, Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking(), Slic3r::GUI::GLCanvas3D::set_sla_view_type(), Slic3r::GUI::GLGizmoBase::set_state(), Undefined, Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::wants_enter_leave_snapshots().
Referenced by load(), open_gizmo(), refresh_on_off_state(), and reset_all_states().
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
check_gizmos_closed_except()
bool Slic3r::GUI::GLGizmosManager::check_gizmos_closed_except (EType type) const
{
    if (get_current_type() != type && get_current_type() != Undefined) {
        wxGetApp().plater()->get_notification_manager()->push_notification(
                    NotificationType::CustomSupportsAndSeamRemovedAfterRepair,
                    NotificationManager::NotificationLevel::PrintInfoNotificationLevel,
                    _u8L("ERROR: Please close all manipulators available from "
                         "the left toolbar first"));
        return false;
    }
    return true;
}
References _u8L, Slic3r::GUI::CustomSupportsAndSeamRemovedAfterRepair, get_current_type(), Slic3r::GUI::NotificationManager::PrintInfoNotificationLevel, and Undefined.
Referenced by Slic3r::GUI::ObjectList::simplify().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
do_render_overlay()
void Slic3r::GUI::GLGizmosManager::do_render_overlay () const private
{
    const std::vector<size_t> selectable_idxs = get_selectable_idxs();
    if (selectable_idxs.empty())
        return;
    const Size cnv_size = m_parent.get_canvas_size();
    const float cnv_w = (float)cnv_size.get_width();
    const float cnv_h = (float)cnv_size.get_height();
    if (cnv_w == 0 || cnv_h == 0)
        return;
    const float inv_cnv_w = 1.0f / cnv_w;
    const float inv_cnv_h = 1.0f / cnv_h;
    const float height = 2.0f * get_scaled_total_height() * inv_cnv_h;
    const float width  = 2.0f * get_scaled_total_width() * inv_cnv_w;
    const float border_h = 2.0f * m_layout.scaled_border() * inv_cnv_h;
    const float border_w = 2.0f * m_layout.scaled_border() * inv_cnv_w;
    float top_x = -1.0f;
    float top_y = 0.5f * height;
    render_background(top_x, top_y, top_x + width, top_y - height, border_w, border_h);
    top_x += border_w;
    top_y -= border_h;
    const float icons_size_x = 2.0f * m_layout.scaled_icons_size() * inv_cnv_w;
    const float icons_size_y = 2.0f * m_layout.scaled_icons_size() * inv_cnv_h;
    const float stride_y = 2.0f * m_layout.scaled_stride_y() * inv_cnv_h;
    const unsigned int icons_texture_id = m_icons_texture.get_id();
    const int tex_width  = m_icons_texture.get_width();
    const int tex_height = m_icons_texture.get_height();
    if (icons_texture_id == 0 || tex_width <= 1 || tex_height <= 1)
        return;
    const float du = (float)(tex_width - 1) / (6.0f * (float)tex_width); // 6 is the number of possible states if the icons
    const float dv = (float)(tex_height - 1) / (float)(m_gizmos.size() * tex_height);
    // tiles in the texture are spaced by 1 pixel
    const float u_offset = 1.0f / (float)tex_width;
    const float v_offset = 1.0f / (float)tex_height;
    float current_y = FLT_MAX;
    for (size_t idx : selectable_idxs) {
        GLGizmoBase* gizmo = m_gizmos[idx].get();
        const unsigned int sprite_id = gizmo->get_sprite_id();
        // higlighted state needs to be decided first so its highlighting in every other state
        const int icon_idx = (m_highlight.first == idx ? (m_highlight.second ? 4 : 5) : (m_current == idx) ? 2 : ((m_hover == idx) ? 1 : (gizmo->is_activable() ? 0 : 3)));
        const float u_left   = u_offset + icon_idx * du;
        const float u_right  = u_left + du - u_offset;
        const float v_top    = v_offset + sprite_id * dv;
        const float v_bottom = v_top + dv - v_offset;
        GLTexture::render_sub_texture(icons_texture_id, top_x, top_x + icons_size_x, top_y - icons_size_y, top_y, { { u_left, v_bottom }, { u_right, v_bottom }, { u_right, v_top }, { u_left, v_top } });
        if (idx == m_current || current_y == FLT_MAX) {
            // The FLT_MAX trick is here so that even non-selectable but activable
            // gizmos are passed some meaningful value.
            current_y = 0.5f * cnv_h - 0.5f * top_y * cnv_h;
        }
        top_y -= stride_y;
    }
    if (m_current != Undefined)
        m_gizmos[m_current]->render_input_window(get_scaled_total_width(), current_y, cnv_h - wxGetApp().plater()->get_view_toolbar().get_height());
}
References Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_id(), get_scaled_total_height(), get_scaled_total_width(), get_selectable_idxs(), Slic3r::GUI::GLGizmoBase::get_sprite_id(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLTexture::get_width(), Slic3r::GUI::GLGizmoBase::is_activable(), m_current, m_gizmos, m_highlight, m_hover, m_icons_texture, m_layout, m_parent, Slic3r::GUI::plater(), render_background(), Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::GLGizmosManager::Layout::scaled_border(), Slic3r::GUI::GLGizmosManager::Layout::scaled_icons_size(), Slic3r::GUI::GLGizmosManager::Layout::scaled_stride_y(), and Undefined.
Referenced by render_overlay().
generate_icons_texture()
bool Slic3r::GUI::GLGizmosManager::generate_icons_texture () private
{
    std::string path = resources_dir() + "/icons/";
    std::vector<std::string> filenames;
    for (size_t idx=0; idx<m_gizmos.size(); ++idx)
    {
        auto &gizmo = m_gizmos[idx];
        if (gizmo != nullptr)
        {
            const std::string& icon_filename = gizmo->get_icon_filename();
            if (!icon_filename.empty())
                filenames.push_back(path + icon_filename);
        }
    }
    std::vector<std::pair<int, bool>> states;
    states.push_back(std::make_pair(1, false)); // Activable
    states.push_back(std::make_pair(0, false)); // Hovered
    states.push_back(std::make_pair(0, true));  // Selected
    states.push_back(std::make_pair(2, false)); // Disabled
    states.push_back(std::make_pair(0, false)); // HighlightedShown
    states.push_back(std::make_pair(2, false)); // HighlightedHidden
    unsigned int sprite_size_px = (unsigned int)m_layout.scaled_icons_size();
//    // force even size
//    if (sprite_size_px % 2 != 0)
//        sprite_size_px += 1;
    bool res = m_icons_texture.load_from_svg_files_as_sprites_array(filenames, states, sprite_size_px, false);
    if (res)
        m_icons_texture_dirty = false;
    return res;
}
References Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), m_gizmos, m_icons_texture, m_icons_texture_dirty, m_layout, Slic3r::resources_dir(), and Slic3r::GUI::GLGizmosManager::Layout::scaled_icons_size().
Referenced by render_overlay().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_clipping_plane()
ClippingPlane Slic3r::GUI::GLGizmosManager::get_clipping_plane () const
{
    if (! m_common_gizmos_data
     || ! m_common_gizmos_data->object_clipper()
     || m_common_gizmos_data->object_clipper()->get_position() == 0.)
        return ClippingPlane::ClipsNothing();
    else {
        const ClippingPlane& clp = *m_common_gizmos_data->object_clipper()->get_clipping_plane();
        return ClippingPlane(-clp.get_normal(), clp.get_data()[3]);
    }
}
References Slic3r::GUI::ClippingPlane::ClipsNothing(), Slic3r::GUI::ClippingPlane::get_data(), Slic3r::GUI::ClippingPlane::get_normal(), and m_common_gizmos_data.
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass().
get_current()
GLGizmoBase * Slic3r::GUI::GLGizmosManager::get_current () const
{
    return ((m_current == Undefined) || m_gizmos.empty()) ? nullptr : m_gizmos[m_current].get();
}
References m_current, m_gizmos, and Undefined.
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects(), get_tooltip(), grabber_contains_mouse(), is_in_editing_mode(), on_key(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::reload_scene(), render_painter_gizmo(), Slic3r::GUI::Plater::priv::take_snapshot(), and update_data().
get_current_type()
EType Slic3r::GUI::GLGizmosManager::get_current_type () const inline
{ return m_current; }
References m_current.
Referenced by Slic3r::GUI::ObjectList::ObjectList(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::MenuFactory::append_menu_item_edit_text(), Slic3r::GUI::MenuFactory::append_menu_item_printable(), Slic3r::GUI::call_after_if_active(), check_gizmos_closed_except(), priv::create_volume(), Slic3r::GUI::GLCanvas3D::deselect_all(), Slic3r::GUI::Emboss::CreateObjectJob::finalize(), Slic3r::GUI::GLCanvas3D::on_key(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::ObjectList::part_selection_changed(), Slic3r::GUI::GLCanvas3D::render(), reset_all_states(), Slic3r::GUI::ObjectList::simplify(), Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility(), Slic3r::GUI::ObjectList::toggle_printable_state(), and priv::update_volume().
get_gizmo()
GLGizmoBase * Slic3r::GUI::GLGizmosManager::get_gizmo (GLGizmosManager::EType type) const
{
    return ((type == Undefined) || m_gizmos.empty()) ? nullptr : m_gizmos[type].get();
}
References m_gizmos, and Undefined.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_add_text(), and Slic3r::GUI::ObjectList::part_selection_changed().
get_gizmo_from_mouse()
GLGizmosManager::EType Slic3r::GUI::GLGizmosManager::get_gizmo_from_mouse (const Vec2d & mouse_pos) const private
{
    if (!m_enabled) return Undefined;
    float cnv_h      = (float) m_parent.get_canvas_size().get_height();
    float height     = get_scaled_total_height();
    float icons_size = m_layout.scaled_icons_size();
    float border     = m_layout.scaled_border();
    float stride_y   = m_layout.scaled_stride_y();
    float top_y      = 0.5f * (cnv_h - height) + border;
    // is mouse horizontally in the area?
    if ((border <= (float) mouse_pos(0) &&
         ((float) mouse_pos(0) <= border + icons_size))) {
        // which icon is it on?
        size_t from_top = (size_t) ((float) mouse_pos(1) - top_y) / stride_y;
        // is it really on the icon or already past the border?
        if ((float) mouse_pos(1) <= top_y + from_top * stride_y + icons_size) {
            std::vector<size_t> selectable = get_selectable_idxs();
            if (from_top < selectable.size())
                return static_cast<EType>(selectable[from_top]);
        }
    }
    return Undefined;
}
References Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), get_scaled_total_height(), get_selectable_idxs(), m_enabled, m_layout, m_parent, Slic3r::GUI::GLGizmosManager::Layout::scaled_border(), Slic3r::GUI::GLGizmosManager::Layout::scaled_icons_size(), Slic3r::GUI::GLGizmosManager::Layout::scaled_stride_y(), Slic3r::GUI::selectable(), and Undefined.
Referenced by gizmos_toolbar_on_mouse().
get_gizmo_from_name()
GLGizmosManager::EType Slic3r::GUI::GLGizmosManager::get_gizmo_from_name (const std::string & gizmo_name) const
{
    std::vector<size_t> selectable_idxs = get_selectable_idxs();
    for (size_t idx = 0; idx < selectable_idxs.size(); ++idx)
    {
        std::string filename = m_gizmos[selectable_idxs[idx]]->get_icon_filename();
        filename = filename.substr(0, filename.find_first_of('.'));
        if (filename == gizmo_name)
            return (GLGizmosManager::EType)selectable_idxs[idx];
    }
    return GLGizmosManager::EType::Undefined;
}
References get_selectable_idxs(), m_gizmos, and Undefined.
get_highlight_state()
bool Slic3r::GUI::GLGizmosManager::get_highlight_state () const inline
{ return m_highlight.second; }
References m_highlight.
get_scaled_total_height()
float Slic3r::GUI::GLGizmosManager::get_scaled_total_height () const private
{
    return m_layout.scale * (2.0f * m_layout.border + (float)get_selectable_idxs().size() * m_layout.stride_y() - m_layout.gap_y);
}
References Slic3r::GUI::GLGizmosManager::Layout::border, Slic3r::GUI::GLGizmosManager::Layout::gap_y, get_selectable_idxs(), m_layout, Slic3r::GUI::GLGizmosManager::Layout::scale, and Slic3r::GUI::GLGizmosManager::Layout::stride_y().
Referenced by do_render_overlay(), get_gizmo_from_mouse(), and render_arrow().
get_scaled_total_width()
float Slic3r::GUI::GLGizmosManager::get_scaled_total_width () const private
{
    return 2.0f * m_layout.scaled_border() + m_layout.scaled_icons_size();
}
References m_layout, Slic3r::GUI::GLGizmosManager::Layout::scaled_border(), and Slic3r::GUI::GLGizmosManager::Layout::scaled_icons_size().
Referenced by do_render_overlay().
get_selectable_icons_cnt()
int Slic3r::GUI::GLGizmosManager::get_selectable_icons_cnt () const inline
{ return get_selectable_idxs().size(); }
References get_selectable_idxs().
get_selectable_idxs()
std::vector< size_t > Slic3r::GUI::GLGizmosManager::get_selectable_idxs () const private
{
    std::vector<size_t> out;
    out.reserve(m_gizmos.size());
    for (size_t i=0; i<m_gizmos.size(); ++i)
        if (m_gizmos[i]->is_selectable())
            out.push_back(i);
    return out;
}
References m_gizmos.
Referenced by do_render_overlay(), get_gizmo_from_mouse(), get_gizmo_from_name(), get_scaled_total_height(), get_selectable_icons_cnt(), and render_arrow().
get_tooltip()
std::string Slic3r::GUI::GLGizmosManager::get_tooltip () const
{
    if (!m_tooltip.empty())
        return m_tooltip;
    const GLGizmoBase* curr = get_current();
    return (curr != nullptr) ? curr->get_tooltip() : "";
}
References get_current(), Slic3r::GUI::GLGizmoBase::get_tooltip(), and m_tooltip.
Referenced by Slic3r::GUI::GLCanvas3D::render().
gizmo_event()
bool Slic3r::GUI::GLGizmosManager::gizmo_event (SLAGizmoEventType action, const Vec2d & mouse_position = Vec2d::Zero(), bool shift_down = false, bool alt_down = false, bool control_down = false) private
{
    if (!m_enabled || m_gizmos.empty())
        return false;
    if (m_current == SlaSupports)
        return dynamic_cast<GLGizmoSlaSupports*>(m_gizmos[SlaSupports].get())->gizmo_event(action, mouse_position, shift_down, alt_down, control_down);
    else if (m_current == Hollow)
        return dynamic_cast<GLGizmoHollow*>(m_gizmos[Hollow].get())->gizmo_event(action, mouse_position, shift_down, alt_down, control_down);
    else if (m_current == FdmSupports)
        return dynamic_cast<GLGizmoFdmSupports*>(m_gizmos[FdmSupports].get())->gizmo_event(action, mouse_position, shift_down, alt_down, control_down);
    else if (m_current == Seam)
        return dynamic_cast<GLGizmoSeam*>(m_gizmos[Seam].get())->gizmo_event(action, mouse_position, shift_down, alt_down, control_down);
    else if (m_current == MmuSegmentation)
        return dynamic_cast<GLGizmoMmuSegmentation*>(m_gizmos[MmuSegmentation].get())->gizmo_event(action, mouse_position, shift_down, alt_down, control_down);
    else if (m_current == Measure)
        return dynamic_cast<GLGizmoMeasure*>(m_gizmos[Measure].get())->gizmo_event(action, mouse_position, shift_down, alt_down, control_down);
    else if (m_current == Cut)
        return dynamic_cast<GLGizmoCut3D*>(m_gizmos[Cut].get())->gizmo_event(action, mouse_position, shift_down, alt_down, control_down);
    else
        return false;
}
References Cut, FdmSupports, gizmo_event(), Hollow, m_current, m_enabled, m_gizmos, Measure, MmuSegmentation, Seam, and SlaSupports.
Referenced by gizmo_event(), on_char(), on_key(), and on_mouse_wheel().
gizmos_toolbar_on_mouse()
bool Slic3r::GUI::GLGizmosManager::gizmos_toolbar_on_mouse (const wxMouseEvent & mouse_event) private
Process mouse event on gizmo toolbar.
Parameters
mouse_event Event descriptor
Returns
TRUE when take responsibility for event otherwise FALSE. On true, event should not be process by others. On false, event should be process by others.
{
    assert(m_enabled);
    // keep information about events to process
    struct MouseCapture
    {
        bool left = false;
        bool middle = false;
        bool right  = false;
        bool exist_tooltip = false;
        MouseCapture() = default;
        bool any() const { return left || middle || right; }
        void reset() {
            left   = false;
            middle = false;
            right  = false;
        }
    };
    static MouseCapture mc;
    // wxCoord == int --> wx/types.h
    Vec2i mouse_coord(mouse_event.GetX(), mouse_event.GetY());
    Vec2d mouse_pos = mouse_coord.cast<double>();
    EType gizmo = get_gizmo_from_mouse(mouse_pos);
    bool  selected_gizmo = gizmo != Undefined;
    // fast reaction on move mouse
    if (mouse_event.Moving()) {
        assert(!mc.any());
        if (selected_gizmo) {
            mc.exist_tooltip = true;
            update_hover_state(gizmo);
            // at this moment is enebled to process mouse move under gizmo
            // tools bar e.g. Do not interupt dragging.
            return false;
        }
        else if (mc.exist_tooltip) {
            // first move out of gizmo tool bar - unselect tooltip
            mc.exist_tooltip = false;
            update_hover_state(Undefined);
            return false;
        }
        return false;
    }
    if (selected_gizmo) {
        // mouse is above toolbar
        if (mouse_event.LeftDown() || mouse_event.LeftDClick()) {
            mc.left = true;
            open_gizmo(gizmo);
            return true;
        }
        else if (mouse_event.RightDown()) {
            mc.right  = true;
            return true;
        }
        else if (mouse_event.MiddleDown()) {
            mc.middle = true;
            return true;
        }
    }
    if (mc.any()) {
        // Check if exist release of event started above toolbar?
        if (mouse_event.Dragging()) {
            if (!selected_gizmo && mc.exist_tooltip) {
                // dragging out of gizmo let tooltip disapear
                mc.exist_tooltip = false;
                update_hover_state(Undefined);
            }
            // draging start on toolbar so no propagation into scene
            return true;
        }
        else if (mc.left && mouse_event.LeftUp()) {
            mc.left = false;
            return true;
        }
        else if (mc.right && mouse_event.RightUp()) {
            mc.right = false;
            return true;
        }
        else if (mc.middle && mouse_event.MiddleUp()) {
            mc.middle = false;
            return true;
        }
        // event out of window is not porocessed
        // left down on gizmo -> keep down -> move out of window -> release left
        if (mouse_event.Leaving()) mc.reset();
    }
    return false;
}
References get_gizmo_from_mouse(), m_enabled, open_gizmo(), Undefined, and update_hover_state().
Referenced by on_mouse().
grabber_contains_mouse()
bool Slic3r::GUI::GLGizmosManager::grabber_contains_mouse () const private
{
    if (!m_enabled)
        return false;
    GLGizmoBase* curr = get_current();
    return (curr != nullptr) ? (curr->get_hover_id() != -1) : false;
}
References get_current(), Slic3r::GUI::GLGizmoBase::get_hover_id(), and m_enabled.
handle_shortcut()
bool Slic3r::GUI::GLGizmosManager::handle_shortcut (int key)
{
    if (!m_enabled)
        return false;
    auto is_key = [pressed_key = key](int gizmo_key) { return (gizmo_key == pressed_key - 64) || (gizmo_key == pressed_key - 96); };
    // allowe open shortcut even when selection is empty
    if (GLGizmoBase* gizmo_emboss = m_gizmos[Emboss].get();
        is_key(gizmo_emboss->get_shortcut_key())) {
        dynamic_cast<GLGizmoEmboss *>(gizmo_emboss)->on_shortcut_key();
        return true;
    }
    if (m_parent.get_selection().is_empty())
        return false;
    auto is_gizmo = [is_key](const std::unique_ptr<GLGizmoBase> &gizmo) {
        return gizmo->is_activable() && is_key(gizmo->get_shortcut_key());
    };
    auto it = std::find_if(m_gizmos.begin(), m_gizmos.end(), is_gizmo);
    if (it == m_gizmos.end())
        return false;
    EType gizmo_type = EType(it - m_gizmos.begin());
    return open_gizmo(gizmo_type);
}
References Emboss, Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::GLGizmoBase::is_activable(), Slic3r::GUI::Selection::is_empty(), m_enabled, m_gizmos, m_parent, and open_gizmo().
Referenced by on_char().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::ModelVolume::check(), Slic3r::check_model_ids_equal(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), anonymous_namespace{RaycastManager.cpp}::create_key(), priv::create_volume(), Slic3r::GUI::Emboss::create_volume_sources(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::Model::delete_object(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::ModelObjectStatusDB::get(), Slic3r::GUI::get_arrange_poly(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::inner_brim_area(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ObjectBase::load_and_construct(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::GLGizmoEmboss::process(), Slic3r::GUI::processed_objects_idxs(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::top_level_outer_brim_area(), Slic3r::GUI::update_object_cut_id(), and anonymous_namespace{EmbossJob.cpp}::update_volume_name().
init()
bool Slic3r::GUI::GLGizmosManager::init ()
{
    m_background_texture.metadata.filename = "toolbar_background.png";
    m_background_texture.metadata.left = 16;
    m_background_texture.metadata.top = 16;
    m_background_texture.metadata.right = 16;
    m_background_texture.metadata.bottom = 16;
    if (!m_background_texture.metadata.filename.empty())
    {
        if (!m_background_texture.texture.load_from_file(resources_dir() + "/icons/" + m_background_texture.metadata.filename, false, GLTexture::SingleThreaded, false))
            return false;
    }
    // Order of gizmos in the vector must match order in EType!
    m_gizmos.emplace_back(new GLGizmoMove3D(m_parent, "move.svg", 0));
    m_gizmos.emplace_back(new GLGizmoScale3D(m_parent, "scale.svg", 1));
    m_gizmos.emplace_back(new GLGizmoRotate3D(m_parent, "rotate.svg", 2));
    m_gizmos.emplace_back(new GLGizmoFlatten(m_parent, "place.svg", 3));
    m_gizmos.emplace_back(new GLGizmoCut3D(m_parent, "cut.svg", 4));
    m_gizmos.emplace_back(new GLGizmoHollow(m_parent, "hollow.svg", 5));
    m_gizmos.emplace_back(new GLGizmoSlaSupports(m_parent, "sla_supports.svg", 6));
    m_gizmos.emplace_back(new GLGizmoFdmSupports(m_parent, "fdm_supports.svg", 7));
    m_gizmos.emplace_back(new GLGizmoSeam(m_parent, "seam.svg", 8));
    m_gizmos.emplace_back(new GLGizmoMmuSegmentation(m_parent, "mmu_segmentation.svg", 9));
    m_gizmos.emplace_back(new GLGizmoMeasure(m_parent, "measure.svg", 10));
    m_gizmos.emplace_back(new GLGizmoEmboss(m_parent));
    m_gizmos.emplace_back(new GLGizmoSimplify(m_parent));
    m_common_gizmos_data.reset(new CommonGizmosDataPool(&m_parent));
    for (auto& gizmo : m_gizmos) {
        if (! gizmo->init()) {
            m_gizmos.clear();
            return false;
        }
        gizmo->set_common_data_pool(m_common_gizmos_data.get());
    }
    m_current = Undefined;
    m_hover = Undefined;
    m_highlight = std::pair<EType, bool>(Undefined, false);
    return true;
}
References Slic3r::GUI::BackgroundTexture::Metadata::bottom, Slic3r::GUI::BackgroundTexture::Metadata::filename, Slic3r::GUI::BackgroundTexture::Metadata::left, Slic3r::GUI::GLTexture::load_from_file(), m_background_texture, m_common_gizmos_data, m_current, m_gizmos, m_highlight, m_hover, m_parent, Slic3r::GUI::BackgroundTexture::metadata, Slic3r::resources_dir(), Slic3r::GUI::BackgroundTexture::Metadata::right, Slic3r::GUI::GLTexture::SingleThreaded, Slic3r::GUI::BackgroundTexture::texture, Slic3r::GUI::BackgroundTexture::Metadata::top, and Undefined.
Referenced by Slic3r::GUI::GLCanvas3D::init().
init_arrow()
bool Slic3r::GUI::GLGizmosManager::init_arrow (const std::string & filename)
{
    if (m_arrow_texture.get_id() != 0)
        return true;
    const std::string path = resources_dir() + "/icons/";
    return (!filename.empty()) ? m_arrow_texture.load_from_svg_file(path + filename, false, false, false, 512) : false;
}
References Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::GLTexture::load_from_svg_file(), m_arrow_texture, and Slic3r::resources_dir().
Referenced by Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
is_dragging()
bool Slic3r::GUI::GLGizmosManager::is_dragging () const
{
    if (! m_enabled || m_current == Undefined)
        return false;
    return m_gizmos[m_current]->is_dragging();
}
References m_current, m_enabled, m_gizmos, and Undefined.
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::GLCanvas3D::is_dragging(), on_char(), and Slic3r::GUI::GLCanvas3D::render().
is_enabled()
bool Slic3r::GUI::GLGizmosManager::is_enabled () const inline
{ return m_enabled; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::init(), and Slic3r::GUI::GLCanvas3D::on_key().
is_hiding_instances()
bool Slic3r::GUI::GLGizmosManager::is_hiding_instances () const
{
    return (m_common_gizmos_data
         && m_common_gizmos_data->instances_hider()
         && m_common_gizmos_data->instances_hider()->is_valid());
}
References m_common_gizmos_data.
is_in_editing_mode()
bool Slic3r::GUI::GLGizmosManager::is_in_editing_mode (bool error_notification = false) const
{
    if (m_current != SlaSupports || ! dynamic_cast<GLGizmoSlaSupports*>(get_current())->is_in_editing_mode())
        return false;
    if (error_notification)
        wxGetApp().plater()->get_notification_manager()->push_notification(
                    NotificationType::QuitSLAManualMode,
                    NotificationManager::NotificationLevel::ErrorNotificationLevel,
                    _u8L("You are currently editing SLA support points. Please, "
                         "apply or discard your changes first."));
    return true;
}
References _u8L, Slic3r::GUI::NotificationManager::ErrorNotificationLevel, get_current(), is_in_editing_mode(), m_current, Slic3r::GUI::QuitSLAManualMode, and SlaSupports.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::ObjectList::ObjectList(), Slic3r::GUI::MainFrame::can_save(), Slic3r::GUI::MainFrame::can_save_as(), is_in_editing_mode(), on_key(), and Slic3r::GUI::ObjectList::toggle_printable_state().
is_running()
bool Slic3r::GUI::GLGizmosManager::is_running () const
{
    if (!m_enabled)
        return false;
    //GLGizmoBase* curr = get_current();
    //return (curr != nullptr) ? (curr->get_state() == GLGizmoBase::On) : false;
    return m_current != Undefined;
}
References m_current, m_enabled, and Undefined.
Referenced by Slic3r::GUI::GLCanvas3D::_max_bounding_box().
load()
template<class Archive > void Slic3r::GUI::GLGizmosManager::load (Archive & ar) inline
    {
        if (!m_enabled)
            return;
        m_serializing = true;
        // Following is needed to know which to be turn on, but not actually modify
        // m_current prematurely, so activate_gizmo is not confused.
        EType old_current = m_current;
        ar(m_current);
        EType new_current = m_current;
        m_current = old_current;
        // activate_gizmo call sets m_current and calls set_state for the gizmo
        // it does nothing in case the gizmo is already activated
        // it can safely be called for Undefined gizmo
        activate_gizmo(new_current);
        if (m_current != Undefined)
            m_gizmos[m_current]->load(ar);
    }
References activate_gizmo(), m_current, m_enabled, m_gizmos, m_serializing, and Undefined.
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
on_char()
bool Slic3r::GUI::GLGizmosManager::on_char (wxKeyEvent & evt)
{
    // see include/wx/defs.h enum wxKeyCode
    int keyCode = evt.GetKeyCode();
    int ctrlMask = wxMOD_CONTROL;
    bool processed = false;
    if ((evt.GetModifiers() & ctrlMask) != 0) {
        switch (keyCode)
        {
#ifdef __APPLE__
        case 'a':
        case 'A':
#else /* __APPLE__ */
        case WXK_CONTROL_A:
#endif /* __APPLE__ */
        {
            // Sla gizmo selects all support points
            if ((m_current == SlaSupports || m_current == Hollow || m_current == Cut) && gizmo_event(SLAGizmoEventType::SelectAll))
                processed = true;
            break;
        }
        }
    }
    else if (!evt.HasModifiers()) {
        switch (keyCode)
        {
        // key ESC
        case WXK_ESCAPE:
        {
            if (m_current != Undefined) {
                if (m_current == Measure && gizmo_event(SLAGizmoEventType::Escape)) {
                    // do nothing
                }
                else if (m_current != SlaSupports || !gizmo_event(SLAGizmoEventType::DiscardChanges))
                    reset_all_states();
                processed = true;
            }
            break;
        }
        case WXK_RETURN:
        {
            if ((m_current == SlaSupports) && gizmo_event(SLAGizmoEventType::ApplyChanges))
                processed = true;
            break;
        }
        case 'r' :
        case 'R' :
        {
            if ((m_current == SlaSupports || m_current == Hollow || m_current == FdmSupports || m_current == Seam || m_current == MmuSegmentation) && gizmo_event(SLAGizmoEventType::ResetClippingPlane))
                processed = true;
            break;
        }
        case WXK_BACK:
        case WXK_DELETE:
        {
            if ((m_current == SlaSupports || m_current == Hollow || m_current == Cut || m_current == Measure) && gizmo_event(SLAGizmoEventType::Delete))
                processed = true;
            break;
        }
        case 'A':
        case 'a':
        {
            if (m_current == SlaSupports) {
                gizmo_event(SLAGizmoEventType::AutomaticGeneration);
                // set as processed no matter what's returned by gizmo_event() to avoid the calling canvas to process 'A' as arrange
                processed = true;
            }
            break;
        }
        case 'M':
        case 'm':
        {
            if ((m_current == SlaSupports) && gizmo_event(SLAGizmoEventType::ManualEditing))
                processed = true;
            break;
        }
        case 'F':
        case 'f':
        {
            if (m_current == Scale) {
                if (!is_dragging())
                    wxGetApp().plater()->scale_selection_to_fit_print_volume();
                processed = true;
            }
            break;
        }
        }
    }
    if (!processed && !evt.HasModifiers()) {
        if (handle_shortcut(keyCode))
            processed = true;
    }
    if (processed)
        m_parent.set_as_dirty();
    return processed;
}
References Slic3r::GUI::ApplyChanges, Slic3r::GUI::AutomaticGeneration, Cut, Slic3r::GUI::Delete, Slic3r::GUI::DiscardChanges, Slic3r::GUI::Escape, FdmSupports, gizmo_event(), handle_shortcut(), Hollow, is_dragging(), m_current, m_parent, Slic3r::GUI::ManualEditing, Measure, MmuSegmentation, reset_all_states(), Slic3r::GUI::ResetClippingPlane, Scale, Seam, Slic3r::GUI::SelectAll, Slic3r::GUI::GLCanvas3D::set_as_dirty(), SlaSupports, and Undefined.
Referenced by Slic3r::GUI::GLCanvas3D::on_char().
on_key()
bool Slic3r::GUI::GLGizmosManager::on_key (wxKeyEvent & evt)
{
    const int keyCode = evt.GetKeyCode();
    bool processed = false;
    if (evt.GetEventType() == wxEVT_KEY_UP) {
        if (m_current == SlaSupports || m_current == Hollow || m_current == Cut) {
            GLGizmoBase* gizmo = get_current();
            const bool is_editing             = m_current == Hollow ? true : gizmo->is_in_editing_mode();
            const bool is_rectangle_dragging  = gizmo->is_selection_rectangle_dragging();
            if (keyCode == WXK_SHIFT) {
                // shift has been just released - SLA gizmo might want to close rectangular selection.
                if (gizmo_event(SLAGizmoEventType::ShiftUp) || (is_editing && is_rectangle_dragging))
                    processed = true;
            }
            else if (keyCode == WXK_ALT) {
                // alt has been just released - SLA gizmo might want to close rectangular selection.
                if (gizmo_event(SLAGizmoEventType::AltUp) || (is_editing && is_rectangle_dragging))
                    processed = true;
            }
        }
        else if (m_current == Measure) {
            if (keyCode == WXK_CONTROL)
                gizmo_event(SLAGizmoEventType::CtrlUp, Vec2d::Zero(), evt.ShiftDown(), evt.AltDown(), evt.CmdDown());
            else if (keyCode == WXK_SHIFT)
                gizmo_event(SLAGizmoEventType::ShiftUp, Vec2d::Zero(), evt.ShiftDown(), evt.AltDown(), evt.CmdDown());
        }
//        if (processed)
//            m_parent.set_cursor(GLCanvas3D::Standard);
    }
    else if (evt.GetEventType() == wxEVT_KEY_DOWN) {
        if (m_current == SlaSupports && (keyCode == WXK_SHIFT || keyCode == WXK_ALT)
          && get_current()->is_in_editing_mode()) {
//            m_parent.set_cursor(GLCanvas3D::Cross);
            processed = true;
        }
        else if (m_current == Cut) {
            auto do_move = [this, &processed](double delta_z) {
                GLGizmoCut3D* cut = dynamic_cast<GLGizmoCut3D*>(get_current());
                cut->shift_cut(delta_z);
                processed = true;
            };
            switch (keyCode)
            {
            case WXK_NUMPAD_UP:   case WXK_UP:   { do_move(1.0); break; }
            case WXK_NUMPAD_DOWN: case WXK_DOWN: { do_move(-1.0); break; }
            case WXK_SHIFT :      case WXK_ALT: {
                processed = get_current()->is_in_editing_mode();
            }
            default: { break; }
            }
        }
        else if (m_current == Simplify && keyCode == WXK_ESCAPE) {
            GLGizmoSimplify *simplify = dynamic_cast<GLGizmoSimplify *>(get_current());
            if (simplify != nullptr)
                processed = simplify->on_esc_key_down();
        }
        else if (m_current == Measure) {
            if (keyCode == WXK_CONTROL)
                gizmo_event(SLAGizmoEventType::CtrlDown, Vec2d::Zero(), evt.ShiftDown(), evt.AltDown(), evt.CmdDown());
            else if (keyCode == WXK_SHIFT)
                gizmo_event(SLAGizmoEventType::ShiftDown, Vec2d::Zero(), evt.ShiftDown(), evt.AltDown(), evt.CmdDown());
        }
    }
    if (processed)
        m_parent.set_as_dirty();
    return processed;
}
References Slic3r::GUI::AltUp, Slic3r::GUI::CtrlDown, Slic3r::GUI::CtrlUp, Cut, get_current(), gizmo_event(), Hollow, Slic3r::GUI::GLGizmoBase::is_in_editing_mode(), is_in_editing_mode(), Slic3r::GUI::GLGizmoBase::is_selection_rectangle_dragging(), m_current, m_parent, Measure, Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::GLGizmoCut3D::shift_cut(), Slic3r::GUI::ShiftDown, Slic3r::GUI::ShiftUp, Simplify, and SlaSupports.
Referenced by Slic3r::GUI::GLCanvas3D::on_key().
on_mouse()
bool Slic3r::GUI::GLGizmosManager::on_mouse (const wxMouseEvent & mouse_event)
{
    if (!m_enabled) return false;
    // tool bar wants to use event?
    if (gizmos_toolbar_on_mouse(mouse_event)) return true;
    // current gizmo wants to use event?
    if (m_current != Undefined &&
        // check if gizmo override method could be slower than simple call virtual function
        // &m_gizmos[m_current]->on_mouse != &GLGizmoBase::on_mouse &&
        m_gizmos[m_current]->on_mouse(mouse_event))
        return true;
    return false;
}
References gizmos_toolbar_on_mouse(), m_current, m_enabled, m_gizmos, on_mouse(), and Undefined.
Referenced by on_mouse(), and Slic3r::GUI::GLCanvas3D::on_mouse().
on_mouse_wheel()
bool Slic3r::GUI::GLGizmosManager::on_mouse_wheel (const wxMouseEvent & evt)
{
    bool processed = false;
    if (m_current == SlaSupports || m_current == Hollow || m_current == FdmSupports || m_current == Seam || m_current == MmuSegmentation) {
        float rot = (float)evt.GetWheelRotation() / (float)evt.GetWheelDelta();
        if (gizmo_event((rot > 0.f ? SLAGizmoEventType::MouseWheelUp : SLAGizmoEventType::MouseWheelDown), Vec2d::Zero(), evt.ShiftDown(), evt.AltDown(), evt.ControlDown()))
            processed = true;
    }
    return processed;
}
References FdmSupports, gizmo_event(), Hollow, m_current, MmuSegmentation, Slic3r::GUI::MouseWheelDown, Slic3r::GUI::MouseWheelUp, Seam, and SlaSupports.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse_wheel().
open_gizmo()
bool Slic3r::GUI::GLGizmosManager::open_gizmo (EType type)
{
    int idx = static_cast<int>(type);
    // re-open same type cause closing
    if (m_current == type) type = Undefined;
    if (m_gizmos[idx]->is_activable() && activate_gizmo(type)) {
        // remove update data into gizmo itself
        update_data();
        return true;
    }
    return false;
}
References activate_gizmo(), m_current, m_gizmos, Undefined, and update_data().
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_edit_text(), Slic3r::GUI::GLGizmoEmboss::close(), Slic3r::GUI::GLGizmoSimplify::close(), priv::create_volume(), Slic3r::GUI::GLCanvas3D::deselect_all(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::Emboss::CreateObjectJob::finalize(), gizmos_toolbar_on_mouse(), handle_shortcut(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_shortcut_key(), Slic3r::GUI::ObjectList::part_selection_changed(), reset_all_states(), and Slic3r::GUI::ObjectList::simplify().
refresh_on_off_state()
void Slic3r::GUI::GLGizmosManager::refresh_on_off_state ()
{
    if (m_serializing || m_current == Undefined || m_gizmos.empty())
        return;
    // FS: Why update data after Undefined gizmo activation?
    if (!m_gizmos[m_current]->is_activable() && activate_gizmo(Undefined))
        update_data();
}
References activate_gizmo(), m_current, m_gizmos, m_serializing, Undefined, and update_data().
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::reload_scene(), and Slic3r::GUI::GLCanvas3D::update_gizmos_on_off_state().
render_arrow()
void Slic3r::GUI::GLGizmosManager::render_arrow (const GLCanvas3D & parent, EType highlighted_type) const
{
    const std::vector<size_t> selectable_idxs = get_selectable_idxs();
    if (selectable_idxs.empty())
        return;
    const Size cnv_size = m_parent.get_canvas_size();
    const float cnv_w = (float)cnv_size.get_width();
    const float cnv_h = (float)cnv_size.get_height();
    if (cnv_w == 0 || cnv_h == 0)
        return;
    const float inv_cnv_w = 1.0f / cnv_w;
    const float inv_cnv_h = 1.0f / cnv_h;
    const float top_x = -1.0f;
    float top_y = get_scaled_total_height() * inv_cnv_h;
    const float icons_size_x = 2.0f * m_layout.scaled_icons_size() * inv_cnv_w;
    const float icons_size_y = 2.0f * m_layout.scaled_icons_size() * inv_cnv_h;
    const float stride_y = 2.0f * m_layout.scaled_stride_y() * inv_cnv_h;
    top_y -= stride_y;
    for (size_t idx : selectable_idxs) {
        if (idx == highlighted_type) {
            const int tex_width = m_arrow_texture.get_width();
            const int tex_height = m_arrow_texture.get_height();
            const unsigned int tex_id = m_arrow_texture.get_id();
            const float arrow_size_x = 2.0f * m_layout.scale * float(tex_height) * inv_cnv_w;
            const float arrow_size_y = 2.0f * m_layout.scale * float(tex_width) * inv_cnv_h;
            const float left_uv   = 0.0f;
            const float right_uv  = 1.0f;
            const float top_uv    = 1.0f;
            const float bottom_uv = 0.0f;
            const float left   = top_x + icons_size_x + 6.0f * m_layout.scaled_border() * inv_cnv_w;
            const float right  = left + arrow_size_x * icons_size_y / arrow_size_y;
            GLTexture::render_sub_texture(tex_id, left, right, top_y, top_y + icons_size_y, { { left_uv, bottom_uv }, { left_uv, top_uv }, { right_uv, top_uv }, { right_uv, bottom_uv } });
            break;
        }
        top_y -= stride_y;
    }
}
References Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_id(), get_scaled_total_height(), get_selectable_idxs(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLTexture::get_width(), m_arrow_texture, m_layout, m_parent, Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::GLGizmosManager::Layout::scale, Slic3r::GUI::GLGizmosManager::Layout::scaled_border(), Slic3r::GUI::GLGizmosManager::Layout::scaled_icons_size(), and Slic3r::GUI::GLGizmosManager::Layout::scaled_stride_y().
render_background()
void Slic3r::GUI::GLGizmosManager::render_background (float left, float top, float right, float bottom, float border_w, float border_h) const private
{
    const unsigned int tex_id = m_background_texture.texture.get_id();
    const float tex_width = float(m_background_texture.texture.get_width());
    const float tex_height = float(m_background_texture.texture.get_height());
    if (tex_id != 0 && tex_width > 0 && tex_height > 0) {
        const float inv_tex_width = (tex_width != 0.0f) ? 1.0f / tex_width : 0.0f;
        const float inv_tex_height = (tex_height != 0.0f) ? 1.0f / tex_height : 0.0f;
        const float internal_left   = left + border_w;
        const float internal_right  = right - border_w;
        const float internal_top    = top - border_h;
        const float internal_bottom = bottom + border_h;
        // float left_uv = 0.0f;
        const float right_uv = 1.0f;
        const float top_uv = 1.0f;
        const float bottom_uv = 0.0f;
        const float internal_left_uv   = float(m_background_texture.metadata.left) * inv_tex_width;
        const float internal_right_uv  = 1.0f - float(m_background_texture.metadata.right) * inv_tex_width;
        const float internal_top_uv    = 1.0f - float(m_background_texture.metadata.top) * inv_tex_height;
        const float internal_bottom_uv = float(m_background_texture.metadata.bottom) * inv_tex_height;
        // top-left corner
        GLTexture::render_sub_texture(tex_id, left, internal_left, internal_top, top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        // top edge
        GLTexture::render_sub_texture(tex_id, internal_left, internal_right, internal_top, top, { { internal_left_uv, internal_top_uv }, { internal_right_uv, internal_top_uv }, { internal_right_uv, top_uv }, { internal_left_uv, top_uv } });
        // top-right corner
        GLTexture::render_sub_texture(tex_id, internal_right, right, internal_top, top, { { internal_right_uv, internal_top_uv }, { right_uv, internal_top_uv }, { right_uv, top_uv }, { internal_right_uv, top_uv } });
        // center-left edge
        GLTexture::render_sub_texture(tex_id, left, internal_left, internal_bottom, internal_top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        // center
        GLTexture::render_sub_texture(tex_id, internal_left, internal_right, internal_bottom, internal_top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        // center-right edge
        GLTexture::render_sub_texture(tex_id, internal_right, right, internal_bottom, internal_top, { { internal_right_uv, internal_bottom_uv }, { right_uv, internal_bottom_uv }, { right_uv, internal_top_uv }, { internal_right_uv, internal_top_uv } });
        // bottom-left corner
        GLTexture::render_sub_texture(tex_id, left, internal_left, bottom, internal_bottom, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        // bottom edge
        GLTexture::render_sub_texture(tex_id, internal_left, internal_right, bottom, internal_bottom, { { internal_left_uv, bottom_uv }, { internal_right_uv, bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_left_uv, internal_bottom_uv } });
        // bottom-right corner
        GLTexture::render_sub_texture(tex_id, internal_right, right, bottom, internal_bottom, { { internal_right_uv, bottom_uv }, { right_uv, bottom_uv }, { right_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv } });
    }
}
References Slic3r::GUI::BackgroundTexture::Metadata::bottom, Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::GLTexture::get_width(), Slic3r::GUI::BackgroundTexture::Metadata::left, m_background_texture, Slic3r::GUI::BackgroundTexture::metadata, Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::BackgroundTexture::Metadata::right, Slic3r::GUI::BackgroundTexture::texture, and Slic3r::GUI::BackgroundTexture::Metadata::top.
Referenced by do_render_overlay().
render_current_gizmo()
void Slic3r::GUI::GLGizmosManager::render_current_gizmo () const
{
    if (!m_enabled || m_current == Undefined)
        return;
    m_gizmos[m_current]->render();
}
References m_current, m_enabled, m_gizmos, and Undefined.
render_overlay()
void Slic3r::GUI::GLGizmosManager::render_overlay ()
{
    if (!m_enabled)
        return;
    if (m_icons_texture_dirty)
        generate_icons_texture();
    do_render_overlay();
}
References do_render_overlay(), generate_icons_texture(), m_enabled, and m_icons_texture_dirty.
render_painter_gizmo()
void Slic3r::GUI::GLGizmosManager::render_painter_gizmo ()
{
    // This function shall only be called when current gizmo is
    // derived from GLGizmoPainterBase.
    if (!m_enabled || m_current == Undefined)
        return;
    auto *gizmo = dynamic_cast<GLGizmoPainterBase*>(get_current());
    assert(gizmo); // check the precondition
    gizmo->render_painter_gizmo();
}
References get_current(), m_current, m_enabled, and Undefined.
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
reset_all_states()
void Slic3r::GUI::GLGizmosManager::reset_all_states ()
{
    if (! m_enabled || m_serializing)
        return;
    const EType current = get_current_type();
    if (current != Undefined)
        // close any open gizmo
        open_gizmo(current);
    activate_gizmo(Undefined);
    m_hover = Undefined;
}
References activate_gizmo(), get_current_type(), m_enabled, m_hover, m_serializing, open_gizmo(), and Undefined.
Referenced by Slic3r::GUI::ObjectList::del_info_item(), Slic3r::GUI::GLCanvas3D::deselect_all(), Slic3r::GUI::GLCanvas3D::handle_sidebar_focus_event(), on_char(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::reset_all_gizmos(), and Slic3r::GUI::GLCanvas3D::select_all().
save()
template<class Archive > void Slic3r::GUI::GLGizmosManager::save (Archive & ar) const inline
    {
        if (!m_enabled)
            return;
        ar(m_current);
        if (m_current != Undefined && !m_gizmos.empty())
            m_gizmos[m_current]->save(ar);
    }
References m_current, m_enabled, m_gizmos, and Undefined.
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_enabled()
void Slic3r::GUI::GLGizmosManager::set_enabled (bool enable) inline
{ m_enabled = enable; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::enable_gizmos().
set_highlight()
void Slic3r::GUI::GLGizmosManager::set_highlight (EType gizmo, bool highlight_shown) inline
{ m_highlight = std::pair<EType, bool>(gizmo, highlight_shown); }
References m_highlight.
set_hover_id()
void Slic3r::GUI::GLGizmosManager::set_hover_id (int id)
{
    if (!m_enabled || m_current == Undefined)
        return;
    m_gizmos[m_current]->set_hover_id(id);
}
References m_current, m_enabled, m_gizmos, and Undefined.
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_overlay_icon_size()
void Slic3r::GUI::GLGizmosManager::set_overlay_icon_size (float size)
{
    if (m_layout.icons_size != size)
    {
        m_layout.icons_size = size;
        m_icons_texture_dirty = true;
    }
}
References Slic3r::GUI::GLGizmosManager::Layout::icons_size, m_icons_texture_dirty, and m_layout.
set_overlay_scale()
void Slic3r::GUI::GLGizmosManager::set_overlay_scale (float scale)
{
    if (m_layout.scale != scale)
    {
        m_layout.scale = scale;
        m_icons_texture_dirty = true;
    }
}
References m_icons_texture_dirty, m_layout, Slic3r::GUI::GLGizmosManager::Layout::scale, and scale().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
Referenced by Slic3r::GUI::Plater::priv::undo_redo_to().
update_after_undo_redo()
void Slic3r::GUI::GLGizmosManager::update_after_undo_redo (const UndoRedo::Snapshot & snapshot)
{
    update_data();
    m_serializing = false;
    if (m_current == SlaSupports
     && snapshot.snapshot_data.flags & UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS)
        dynamic_cast<GLGizmoSlaSupports*>(m_gizmos[SlaSupports].get())->reslice_until_step(slaposPad, true);
}
References Slic3r::UndoRedo::SnapshotData::flags, m_current, m_gizmos, m_serializing, Slic3r::UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS, Slic3r::slaposPad, SlaSupports, Slic3r::UndoRedo::Snapshot::snapshot_data, and update_data().
update_data()
void Slic3r::GUI::GLGizmosManager::update_data ()
Distribute information about different data into active gizmo Should be called when selection changed.
{
    if (!m_enabled) return;
    if (m_common_gizmos_data)
        m_common_gizmos_data->update(get_current()
                                   ? get_current()->get_requirements()
                                   : CommonGizmosDataID(0));
    if (m_current != Undefined) m_gizmos[m_current]->data_changed(m_serializing);
}
References get_current(), m_common_gizmos_data, m_current, m_enabled, m_gizmos, m_serializing, and Undefined.
Referenced by Slic3r::GUI::GLCanvas3D::deselect_all(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLCanvas3D::on_key(), Slic3r::GUI::GLCanvas3D::on_mouse(), open_gizmo(), refresh_on_off_state(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::select_all(), Slic3r::GUI::ObjectManipulation::set_coordinates_type(), update_after_undo_redo(), and Slic3r::GUI::GLCanvas3D::update_gizmos_on_off_state().
update_hover_state()
void Slic3r::GUI::GLGizmosManager::update_hover_state (const EType & type) private
{
    assert(m_enabled);
    if (type == Undefined) {
        m_hover = Undefined;
        m_tooltip.clear();
        return;
    }
    const GLGizmoBase &hovered_gizmo = *m_gizmos[type];
    m_hover = hovered_gizmo.is_activable() ? type : Undefined;
    m_tooltip = hovered_gizmo.get_name();
}
References Slic3r::GUI::GLGizmoBase::get_name(), Slic3r::GUI::GLGizmoBase::is_activable(), m_enabled, m_gizmos, m_hover, m_tooltip, and Undefined.
Referenced by gizmos_toolbar_on_mouse().
wants_reslice_supports_on_undo()
bool Slic3r::GUI::GLGizmosManager::wants_reslice_supports_on_undo () const
{
    return (m_current == SlaSupports
        && dynamic_cast<const GLGizmoSlaSupports*>(m_gizmos.at(SlaSupports).get())->has_backend_supports());
}
References Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), m_current, m_gizmos, and SlaSupports.
Member Data Documentation
Default_Icons_Size
const float Slic3r::GUI::GLGizmosManager::Default_Icons_Size = 64 static
m_arrow_texture
GLTexture Slic3r::GUI::GLGizmosManager::m_arrow_texture private
Referenced by init_arrow(), and render_arrow().
m_background_texture
BackgroundTexture Slic3r::GUI::GLGizmosManager::m_background_texture private
Referenced by init(), and render_background().
m_common_gizmos_data
std::unique_ptr<CommonGizmosDataPool> Slic3r::GUI::GLGizmosManager::m_common_gizmos_data private
Referenced by get_clipping_plane(), init(), is_hiding_instances(), and update_data().
m_current
EType Slic3r::GUI::GLGizmosManager::m_current private
Referenced by activate_gizmo(), do_render_overlay(), get_current(), get_current_type(), gizmo_event(), init(), is_dragging(), is_in_editing_mode(), is_running(), load(), on_char(), on_key(), on_mouse(), on_mouse_wheel(), open_gizmo(), refresh_on_off_state(), render_current_gizmo(), render_painter_gizmo(), save(), set_hover_id(), update_after_undo_redo(), update_data(), and wants_reslice_supports_on_undo().
m_enabled
bool Slic3r::GUI::GLGizmosManager::m_enabled private
Referenced by get_gizmo_from_mouse(), gizmo_event(), gizmos_toolbar_on_mouse(), grabber_contains_mouse(), handle_shortcut(), is_dragging(), is_enabled(), is_running(), load(), on_mouse(), render_current_gizmo(), render_overlay(), render_painter_gizmo(), reset_all_states(), save(), set_enabled(), set_hover_id(), update_data(), and update_hover_state().
m_gizmos
std::vector<std::unique_ptr<GLGizmoBase> > Slic3r::GUI::GLGizmosManager::m_gizmos private
Referenced by activate_gizmo(), do_render_overlay(), generate_icons_texture(), get_current(), get_gizmo(), get_gizmo_from_name(), get_selectable_idxs(), gizmo_event(), handle_shortcut(), init(), is_dragging(), load(), on_mouse(), open_gizmo(), refresh_on_off_state(), render_current_gizmo(), save(), set_hover_id(), update_after_undo_redo(), update_data(), update_hover_state(), and wants_reslice_supports_on_undo().
m_highlight
std::pair<EType, bool> Slic3r::GUI::GLGizmosManager::m_highlight private
Referenced by do_render_overlay(), get_highlight_state(), init(), and set_highlight().
m_hover
EType Slic3r::GUI::GLGizmosManager::m_hover private
Referenced by do_render_overlay(), init(), reset_all_states(), and update_hover_state().
m_icons_texture
GLTexture Slic3r::GUI::GLGizmosManager::m_icons_texture private
Referenced by do_render_overlay(), and generate_icons_texture().
m_icons_texture_dirty
bool Slic3r::GUI::GLGizmosManager::m_icons_texture_dirty private
Referenced by generate_icons_texture(), render_overlay(), set_overlay_icon_size(), and set_overlay_scale().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_layout
Layout Slic3r::GUI::GLGizmosManager::m_layout private
Referenced by do_render_overlay(), generate_icons_texture(), get_gizmo_from_mouse(), get_scaled_total_height(), get_scaled_total_width(), render_arrow(), set_overlay_icon_size(), and set_overlay_scale().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmosManager::m_parent private
Referenced by activate_gizmo(), do_render_overlay(), get_gizmo_from_mouse(), handle_shortcut(), init(), on_char(), on_key(), and render_arrow().
m_serializing
bool Slic3r::GUI::GLGizmosManager::m_serializing private
Referenced by activate_gizmo(), load(), refresh_on_off_state(), reset_all_states(), update_after_undo_redo(), and update_data().
m_tooltip
std::string Slic3r::GUI::GLGizmosManager::m_tooltip private
Referenced by get_tooltip(), and update_hover_state().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmosManager.hpp
src/slic3r/GUI/Gizmos/GLGizmosManager.cpp