Prusa Slicer: ImGuiListClipper Struct Reference
ImGuiListClipper Struct Reference
#include <src/imgui/imgui.h>
Public Member Functions
IMGUI_API ImGuiListClipper ()
IMGUI_API ~ImGuiListClipper ()
IMGUI_API void Begin (int items_count, float items_height=-1.0f)
IMGUI_API void End ()
IMGUI_API bool Step ()
ImGuiListClipper (int items_count, float items_height=-1.0f)
Public Attributes
int DisplayStart
int DisplayEnd
int ItemsCount
int StepNo
int ItemsFrozen
float ItemsHeight
float StartPosY
Detailed Description
Constructor & Destructor Documentation
ImGuiListClipper() [1/2]
ImGuiListClipper::ImGuiListClipper ()
{
    memset(this, 0, sizeof(*this));
    ItemsCount = -1;
}
~ImGuiListClipper()
ImGuiListClipper::~ImGuiListClipper ()
{
    IM_ASSERT(ItemsCount == -1 && "Forgot to call End(), or to Step() until false?");
}
References IM_ASSERT.
ImGuiListClipper() [2/2]
ImGuiListClipper::ImGuiListClipper (int items_count, float items_height = -1.0f) inline
{ memset(this, 0, sizeof(*this)); ItemsCount = -1; Begin(items_count, items_height); } // [removed in 1.79]
Member Function Documentation
Begin()
void ImGuiListClipper::Begin (int items_count, float items_height = -1.0f)
{
    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = g.CurrentWindow;
    if (ImGuiTable* table = g.CurrentTable)
        if (table->IsInsideRow)
            ImGui::TableEndRow(table);
    StartPosY = window->DC.CursorPos.y;
    ItemsHeight = items_height;
    ItemsCount = items_count;
    ItemsFrozen = 0;
    StepNo = 0;
    DisplayStart = -1;
    DisplayEnd = 0;
}
References ImGuiContext::CurrentTable, ImGuiContext::CurrentWindow, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, GImGui, ImGui::TableEndRow(), and ImVec2::y.
Referenced by ImGui::DebugNodeDrawList(), ExampleAppLog::Draw(), ShowDemoWindowColumns(), ShowDemoWindowTables(), and ShowExampleAppLongText().
End()
void ImGuiListClipper::End ()
{
    if (ItemsCount < 0) // Already ended
        return;
    // In theory here we should assert that ImGui::GetCursorPosY() == StartPosY + DisplayEnd * ItemsHeight, but it feels saner to just seek at the end and not assert/crash the user.
    if (ItemsCount < INT_MAX && DisplayStart >= 0)
        SetCursorPosYAndSetupForPrevLine(StartPosY + (ItemsCount - ItemsFrozen) * ItemsHeight, ItemsHeight);
    ItemsCount = -1;
    StepNo = 3;
}
References SetCursorPosYAndSetupForPrevLine().
Referenced by ExampleAppLog::Draw().
Step()
bool ImGuiListClipper::Step ()
{
    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = g.CurrentWindow;
    ImGuiTable* table = g.CurrentTable;
    if (table && table->IsInsideRow)
        ImGui::TableEndRow(table);
    // No items
    if (ItemsCount == 0 || GetSkipItemForListClipping())
    {
        End();
        return false;
    }
    // Step 0: Let you process the first element (regardless of it being visible or not, so we can measure the element height)
    if (StepNo == 0)
    {
        // While we are in frozen row state, keep displaying items one by one, unclipped
        // FIXME: Could be stored as a table-agnostic state.
        if (table != NULL && !table->IsUnfrozenRows)
        {
            DisplayStart = ItemsFrozen;
            DisplayEnd = ItemsFrozen + 1;
            ItemsFrozen++;
            return true;
        }
        StartPosY = window->DC.CursorPos.y;
        if (ItemsHeight <= 0.0f)
        {
            // Submit the first item so we can measure its height (generally it is 0..1)
            DisplayStart = ItemsFrozen;
            DisplayEnd = ItemsFrozen + 1;
            StepNo = 1;
            return true;
        }
        // Already has item height (given by user in Begin): skip to calculating step
        DisplayStart = DisplayEnd;
        StepNo = 2;
    }
    // Step 1: the clipper infer height from first element
    if (StepNo == 1)
    {
        IM_ASSERT(ItemsHeight <= 0.0f);
        if (table)
        {
            const float pos_y1 = table->RowPosY1;   // Using this instead of StartPosY to handle clipper straddling the frozen row
            const float pos_y2 = table->RowPosY2;   // Using this instead of CursorPos.y to take account of tallest cell.
            ItemsHeight = pos_y2 - pos_y1;
            window->DC.CursorPos.y = pos_y2;
        }
        else
        {
            ItemsHeight = window->DC.CursorPos.y - StartPosY;
        }
        IM_ASSERT(ItemsHeight > 0.0f && "Unable to calculate item height! First item hasn't moved the cursor vertically!");
        StepNo = 2;
    }
    // Reached end of list
    if (DisplayEnd >= ItemsCount)
    {
        End();
        return false;
    }
    // Step 2: calculate the actual range of elements to display, and position the cursor before the first element
    if (StepNo == 2)
    {
        IM_ASSERT(ItemsHeight > 0.0f);
        int already_submitted = DisplayEnd;
        ImGui::CalcListClipping(ItemsCount - already_submitted, ItemsHeight, &DisplayStart, &DisplayEnd);
        DisplayStart += already_submitted;
        DisplayEnd += already_submitted;
        // Seek cursor
        if (DisplayStart > already_submitted)
            SetCursorPosYAndSetupForPrevLine(StartPosY + (DisplayStart - ItemsFrozen) * ItemsHeight, ItemsHeight);
        StepNo = 3;
        return true;
    }
    // Step 3: the clipper validate that we have reached the expected Y position (corresponding to element DisplayEnd),
    // Advance the cursor to the end of the list and then returns 'false' to end the loop.
    if (StepNo == 3)
    {
        // Seek cursor
        if (ItemsCount < INT_MAX)
            SetCursorPosYAndSetupForPrevLine(StartPosY + (ItemsCount - ItemsFrozen) * ItemsHeight, ItemsHeight); // advance cursor
        ItemsCount = -1;
        return false;
    }
    IM_ASSERT(0);
    return false;
}
References ImGui::CalcListClipping(), ImGuiContext::CurrentTable, ImGuiContext::CurrentWindow, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, GetSkipItemForListClipping(), GImGui, IM_ASSERT, ImGuiTable::IsInsideRow, ImGuiTable::IsUnfrozenRows, ImGuiTable::RowPosY1, ImGuiTable::RowPosY2, SetCursorPosYAndSetupForPrevLine(), ImGui::TableEndRow(), and ImVec2::y.
Referenced by ImGui::DebugNodeDrawList(), ExampleAppLog::Draw(), ShowDemoWindowColumns(), ShowDemoWindowTables(), and ShowExampleAppLongText().
Member Data Documentation
DisplayEnd
int ImGuiListClipper::DisplayEnd
Referenced by ImGui::DebugNodeDrawList(), ExampleAppLog::Draw(), ShowDemoWindowColumns(), ShowDemoWindowTables(), and ShowExampleAppLongText().
DisplayStart
int ImGuiListClipper::DisplayStart
Referenced by ImGui::DebugNodeDrawList(), ExampleAppLog::Draw(), ShowDemoWindowColumns(), ShowDemoWindowTables(), and ShowExampleAppLongText().
ItemsCount
int ImGuiListClipper::ItemsCount
ItemsFrozen
int ImGuiListClipper::ItemsFrozen
ItemsHeight
float ImGuiListClipper::ItemsHeight
StartPosY
float ImGuiListClipper::StartPosY
StepNo
int ImGuiListClipper::StepNo
The documentation for this struct was generated from the following files:
src/imgui/imgui.h
src/imgui/imgui.cpp