Prusa Slicer: Slic3r::GLShaderProgram Class Reference
Slic3r::GLShaderProgram Class Reference
#include <src/slic3r/GUI/GLShader.hpp>
Public Types
enum class EShaderType {
Vertex , Fragment , Geometry , TessEvaluation ,
TessControl , Compute , Count
}
typedef std::array< std::string, static_cast< size_t >(EShaderType::Count)> ShaderFilenames
typedef std::array< std::string, static_cast< size_t >(EShaderType::Count)> ShaderSources
Public Member Functions
~GLShaderProgram ()
bool init_from_files (const std::string &name, const ShaderFilenames &filenames, const std::initializer_list< std::string_view > &defines={})
bool init_from_texts (const std::string &name, const ShaderSources &sources)
const std::string & get_name () const
unsigned int get_id () const
void start_using () const
void stop_using () const
void set_uniform (const char *name, int value) const
void set_uniform (const char *name, bool value) const
void set_uniform (const char *name, float value) const
void set_uniform (const char *name, double value) const
void set_uniform (const char *name, const std::array< int, 2 > &value) const
void set_uniform (const char *name, const std::array< int, 3 > &value) const
void set_uniform (const char *name, const std::array< int, 4 > &value) const
void set_uniform (const char *name, const std::array< float, 2 > &value) const
void set_uniform (const char *name, const std::array< float, 3 > &value) const
void set_uniform (const char *name, const std::array< float, 4 > &value) const
void set_uniform (const char *name, const std::array< double, 4 > &value) const
void set_uniform (const char *name, const float *value, size_t size) const
void set_uniform (const char *name, const Transform3f &value) const
void set_uniform (const char *name, const Transform3d &value) const
void set_uniform (const char *name, const Matrix3f &value) const
void set_uniform (const char *name, const Matrix3d &value) const
void set_uniform (const char *name, const Matrix4f &value) const
void set_uniform (const char *name, const Matrix4d &value) const
void set_uniform (const char *name, const Vec2f &value) const
void set_uniform (const char *name, const Vec2d &value) const
void set_uniform (const char *name, const Vec3f &value) const
void set_uniform (const char *name, const Vec3d &value) const
void set_uniform (const char *name, const ColorRGB &value) const
void set_uniform (const char *name, const ColorRGBA &value) const
void set_uniform (int id, int value) const
void set_uniform (int id, bool value) const
void set_uniform (int id, float value) const
void set_uniform (int id, double value) const
void set_uniform (int id, const std::array< int, 2 > &value) const
void set_uniform (int id, const std::array< int, 3 > &value) const
void set_uniform (int id, const std::array< int, 4 > &value) const
void set_uniform (int id, const std::array< float, 2 > &value) const
void set_uniform (int id, const std::array< float, 3 > &value) const
void set_uniform (int id, const std::array< float, 4 > &value) const
void set_uniform (int id, const std::array< double, 4 > &value) const
void set_uniform (int id, const float *value, size_t size) const
void set_uniform (int id, const Transform3f &value) const
void set_uniform (int id, const Transform3d &value) const
void set_uniform (int id, const Matrix3f &value) const
void set_uniform (int id, const Matrix3d &value) const
void set_uniform (int id, const Matrix4f &value) const
void set_uniform (int id, const Matrix4d &value) const
void set_uniform (int id, const Vec2f &value) const
void set_uniform (int id, const Vec2d &value) const
void set_uniform (int id, const Vec3f &value) const
void set_uniform (int id, const Vec3d &value) const
void set_uniform (int id, const ColorRGB &value) const
void set_uniform (int id, const ColorRGBA &value) const
int get_attrib_location (const char *name) const
int get_uniform_location (const char *name) const
Private Attributes
std::string m_name
unsigned int m_id { 0 }
std::vector< std::pair< std::string, int > > m_attrib_location_cache
std::vector< std::pair< std::string, int > > m_uniform_location_cache
Detailed Description
Member Typedef Documentation
ShaderFilenames
typedef std::array<std::string, static_cast<size_t>(EShaderType::Count)> Slic3r::GLShaderProgram::ShaderFilenames
ShaderSources
typedef std::array<std::string, static_cast<size_t>(EShaderType::Count)> Slic3r::GLShaderProgram::ShaderSources
Member Enumeration Documentation
EShaderType
enum class Slic3r::GLShaderProgram::EShaderType strong
Enumerator
Vertex
Fragment
Geometry
TessEvaluation
TessControl
Compute
Count
    {
        Vertex,
        Fragment,
        Geometry,
        TessEvaluation,
        TessControl,
        Compute,
        Count
    };
Constructor & Destructor Documentation
~GLShaderProgram()
Slic3r::GLShaderProgram::~GLShaderProgram ()
{
    if (m_id > 0)
        glsafe(::glDeleteProgram(m_id));
}
References glsafe, and m_id.
Member Function Documentation
get_attrib_location()
int Slic3r::GLShaderProgram::get_attrib_location (const char * name) const
{
    assert(m_id > 0);
    if (m_id <= 0)
        // Shader program not loaded. This should not happen.
        return -1;
    auto it = std::find_if(m_attrib_location_cache.begin(), m_attrib_location_cache.end(), [name](const auto& p) { return p.first == name; });
    if (it != m_attrib_location_cache.end())
        // Attrib ID cached.
        return it->second;
    int id = ::glGetAttribLocation(m_id, name);
    const_cast<GLShaderProgram*>(this)->m_attrib_location_cache.push_back({ name, id });
    return id;
}
References m_attrib_location_cache, and m_id.
Referenced by Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLMmSegmentationGizmo3DScene::render(), Slic3r::GUI::ImGuiWrapper::render_draw_data(), Slic3r::GUI::GLModel::render_instanced(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
get_id()
unsigned int Slic3r::GLShaderProgram::get_id () const inline
{ return m_id; }
References m_id.
get_name()
const std::string & Slic3r::GLShaderProgram::get_name () const inline
{ return m_name; }
References m_name.
Referenced by Slic3r::GUI::GLModel::render_instanced().
get_uniform_location()
int Slic3r::GLShaderProgram::get_uniform_location (const char * name) const
{
    assert(m_id > 0);
    if (m_id <= 0)
        // Shader program not loaded. This should not happen.
        return -1;
    auto it = std::find_if(m_uniform_location_cache.begin(), m_uniform_location_cache.end(), [name](const auto &p) { return p.first == name; });
    if (it != m_uniform_location_cache.end())
        // Uniform ID cached.
        return it->second;
    int id = ::glGetUniformLocation(m_id, name);
    const_cast<GLShaderProgram*>(this)->m_uniform_location_cache.push_back({ name, id });
    return id;
}
Referenced by Slic3r::GUI::GCodeViewer::render_toolpaths(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), and set_uniform().
init_from_files()
bool Slic3r::GLShaderProgram::init_from_files (const std::string & name, const ShaderFilenames & filenames, const std::initializer_list< std::string_view > & defines = {})
{
    // Load a shader program from file, prepend defs block.
    auto load_from_file = [](const std::string& filename, const std::string &defs) {
        std::string path = resources_dir() + "/shaders/" + filename;
        boost::nowide::ifstream s(path, boost::nowide::ifstream::binary);
        if (!s.good()) {
            BOOST_LOG_TRIVIAL(error) << "Couldn't open file: '" << path << "'";
            return std::string();
        }
        s.seekg(0, s.end);
        int file_length = static_cast<int>(s.tellg());
        s.seekg(0, s.beg);
        std::string source(defs.size() + file_length, '\0');
        memcpy(source.data(), defs.c_str(), defs.size());
        s.read(source.data() + defs.size(), file_length);
        if (!s.good()) {
            BOOST_LOG_TRIVIAL(error) << "Error while loading file: '" << path << "'";
            return std::string();
        }
        s.close();
        if (! defs.empty()) {
            // Extract the version and flip the order of "defines" and version in the source block.
            size_t idx = source.find("\n", defs.size());
            if (idx != std::string::npos && strncmp(source.c_str() + defs.size(), "#version", 8) == 0) {
                // Swap the version line with the defines.
                size_t len = idx - defs.size() + 1;
                memmove(source.data(), source.c_str() + defs.size(), len);
                memcpy(source.data() + len, defs.c_str(), defs.size());
            }
        }
        return source;
    };
    // Create a block of C "defines" from list of symbols.
    std::string defines_program;
    for (std::string_view def : defines)
        // Our shaders are stored with "\r\n", thus replicate the same here for consistency. Likely "\n" would suffice,
        // but we don't know all the OpenGL shader compilers around.
        defines_program += format("#define %s\r\n", def);
    ShaderSources sources = {};
    for (size_t i = 0; i < static_cast<size_t>(EShaderType::Count); ++i) {
        sources[i] = filenames[i].empty() ? std::string() : load_from_file(filenames[i], defines_program);
    }
    bool valid = !sources[static_cast<size_t>(EShaderType::Vertex)].empty() && !sources[static_cast<size_t>(EShaderType::Fragment)].empty() && sources[static_cast<size_t>(EShaderType::Compute)].empty();
    valid |= !sources[static_cast<size_t>(EShaderType::Compute)].empty() && sources[static_cast<size_t>(EShaderType::Vertex)].empty() && sources[static_cast<size_t>(EShaderType::Fragment)].empty() &&
              sources[static_cast<size_t>(EShaderType::Geometry)].empty() && sources[static_cast<size_t>(EShaderType::TessEvaluation)].empty() && sources[static_cast<size_t>(EShaderType::TessControl)].empty();
    return valid ? init_from_texts(name, sources) : false;
}
References Compute, Count, Slic3r::empty(), error, Slic3r::format(), Fragment, Geometry, init_from_texts(), Slic3r::resources_dir(), TessControl, TessEvaluation, and Vertex.
init_from_texts()
bool Slic3r::GLShaderProgram::init_from_texts (const std::string & name, const ShaderSources & sources)
{
    auto shader_type_as_string = [](EShaderType type) {
        switch (type)
        {
        case EShaderType::Vertex:         { return "vertex"; }
        case EShaderType::Fragment:       { return "fragment"; }
        case EShaderType::Geometry:       { return "geometry"; }
        case EShaderType::TessEvaluation: { return "tesselation evaluation"; }
        case EShaderType::TessControl:    { return "tesselation control"; }
        case EShaderType::Compute:        { return "compute"; }
        default:                          { return "unknown"; }
        }
    };
    auto create_shader = [](EShaderType type) {
        GLuint id = 0;
        switch (type)
        {
        case EShaderType::Vertex:         { id = ::glCreateShader(GL_VERTEX_SHADER); glcheck(); break; }
        case EShaderType::Fragment:       { id = ::glCreateShader(GL_FRAGMENT_SHADER); glcheck(); break; }
        case EShaderType::Geometry:       { id = ::glCreateShader(GL_GEOMETRY_SHADER); glcheck(); break; }
        case EShaderType::TessEvaluation: { id = ::glCreateShader(GL_TESS_EVALUATION_SHADER); glcheck(); break; }
        case EShaderType::TessControl:    { id = ::glCreateShader(GL_TESS_CONTROL_SHADER); glcheck(); break; }
        case EShaderType::Compute:        { id = ::glCreateShader(GL_COMPUTE_SHADER); glcheck(); break; }
        default:                          { break; }
        }
        return (id == 0) ? std::make_pair(false, GLuint(0)) : std::make_pair(true, id);
    };
    auto release_shaders = [](const std::array<GLuint, static_cast<size_t>(EShaderType::Count)>& shader_ids) {
        for (size_t i = 0; i < static_cast<size_t>(EShaderType::Count); ++i) {
            if (shader_ids[i] > 0)
                glsafe(::glDeleteShader(shader_ids[i]));
        }
    };
    assert(m_id == 0);
    m_name = name;
    std::array<GLuint, static_cast<size_t>(EShaderType::Count)> shader_ids = { 0 };
    for (size_t i = 0; i < static_cast<size_t>(EShaderType::Count); ++i) {
        const std::string& source = sources[i];
        if (!source.empty()) {
            EShaderType type = static_cast<EShaderType>(i);
            auto [result, id] = create_shader(type);
            if (result)
                shader_ids[i] = id;
            else {
                BOOST_LOG_TRIVIAL(error) << "glCreateShader() failed for " << shader_type_as_string(type) << " shader of shader program '" << name << "'";
                // release shaders
                release_shaders(shader_ids);
                return false;
            }
            const char* source_ptr = source.c_str();
            glsafe(::glShaderSource(id, 1, &source_ptr, nullptr));
            glsafe(::glCompileShader(id));
            GLint params;
            glsafe(::glGetShaderiv(id, GL_COMPILE_STATUS, &params));
            if (params == GL_FALSE) {
                // Compilation failed.
                glsafe(::glGetShaderiv(id, GL_INFO_LOG_LENGTH, &params));
                std::vector<char> msg(params);
                glsafe(::glGetShaderInfoLog(id, params, &params, msg.data()));
                BOOST_LOG_TRIVIAL(error) << "Unable to compile " << shader_type_as_string(type) << " shader of shader program '" << name << "':\n" << msg.data();
                // release shaders
                release_shaders(shader_ids);
                return false;
            }
        }
    }
    m_id = ::glCreateProgram();
    glcheck();
    if (m_id == 0) {
        BOOST_LOG_TRIVIAL(error) << "glCreateProgram() failed for shader program '" << name << "'";
        // release shaders
        release_shaders(shader_ids);
        return false;
    }
    for (size_t i = 0; i < static_cast<size_t>(EShaderType::Count); ++i) {
        if (shader_ids[i] > 0)
            glsafe(::glAttachShader(m_id, shader_ids[i]));
    }
    glsafe(::glLinkProgram(m_id));
    GLint params;
    glsafe(::glGetProgramiv(m_id, GL_LINK_STATUS, &params));
    if (params == GL_FALSE) {
        // Linking failed.
        glsafe(::glGetProgramiv(m_id, GL_INFO_LOG_LENGTH, &params));
        std::vector<char> msg(params);
        glsafe(::glGetProgramInfoLog(m_id, params, &params, msg.data()));
        BOOST_LOG_TRIVIAL(error) << "Unable to link shader program '" << name << "':\n" << msg.data();
        // release shaders
        release_shaders(shader_ids);
        // release shader program
        glsafe(::glDeleteProgram(m_id));
        m_id = 0;
        return false;
    }
    // release shaders, they are no more needed
    release_shaders(shader_ids);
    return true;
}
References Compute, Count, error, Fragment, Geometry, GL_FALSE, glcheck, glsafe, m_id, m_name, TessControl, TessEvaluation, and Vertex.
Referenced by init_from_files().
set_uniform() [1/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, bool value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [2/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const ColorRGB & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [3/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const ColorRGBA & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [4/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const float * value, size_t size) const inline
{ set_uniform(get_uniform_location(name), value, size); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [5/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Matrix3d & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [6/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Matrix3f & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [7/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Matrix4d & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [8/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Matrix4f & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [9/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const std::array< double, 4 > & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [10/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const std::array< float, 2 > & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [11/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const std::array< float, 3 > & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [12/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const std::array< float, 4 > & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [13/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const std::array< int, 2 > & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [14/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const std::array< int, 3 > & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [15/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const std::array< int, 4 > & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [16/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Transform3d & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [17/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Transform3f & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [18/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Vec2d & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [19/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Vec2f & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [20/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Vec3d & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [21/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, const Vec3f & value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [22/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, double value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [23/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, float value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by set_uniform().
set_uniform() [24/48]
void Slic3r::GLShaderProgram::set_uniform (const char * name, int value) const inline
{ set_uniform(get_uniform_location(name), value); }
References get_uniform_location(), and set_uniform().
Referenced by Slic3r::GUI::GLCanvas3D::_render_background(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::_render_volumes_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GLVolume::SinkingContours::render(), Slic3r::GLVolume::NonManifoldEdges::render(), Slic3r::GUI::GCodeViewer::COG::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::render(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLModel::render(), Slic3r::GUI::CoordAxes::render(), Slic3r::GLVolumeCollection::render(), Slic3r::GUI::GLGizmoBase::Grabber::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::MeshClipper::render_contour(), Slic3r::GUI::Bed3D::render_contour(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere(), Slic3r::GUI::MeshClipper::render_cut(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::Bed3D::render_default(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::ImGuiWrapper::render_draw_data(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLModel::render_instanced(), Slic3r::GUI::GLGizmoCut3D::render_line(), Slic3r::GUI::Bed3D::render_model(), Slic3r::GUI::GLGizmoCut3D::render_model(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::Selection::render_sidebar_hints(), Slic3r::GUI::Selection::render_sidebar_layers_hints(), Slic3r::GUI::Selection::render_sidebar_position_hints(), Slic3r::GUI::Selection::render_sidebar_rotation_hints(), Slic3r::GUI::Selection::render_sidebar_scale_hints(), Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::Bed3D::render_texture(), Slic3r::GUI::GCodeViewer::render_toolpaths(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_volumes(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), set_uniform(), and set_uniform().
set_uniform() [25/48]
void Slic3r::GLShaderProgram::set_uniform (int id, bool value) const
{
    set_uniform(id, value ? 1 : 0);
}
References set_uniform().
set_uniform() [26/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const ColorRGB & value) const
{
    set_uniform(id, value.data(), 3);
}
References Slic3r::ColorRGB::data(), and set_uniform().
set_uniform() [27/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const ColorRGBA & value) const
{
    set_uniform(id, value.data(), 4);
}
References Slic3r::ColorRGBA::data(), and set_uniform().
set_uniform() [28/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const float * value, size_t size) const
{
    if (id >= 0) {
        if (size == 1)
            set_uniform(id, value[0]);
        else if (size == 2)
            glsafe(::glUniform2fv(id, 1, static_cast<const GLfloat*>(value)));
        else if (size == 3)
            glsafe(::glUniform3fv(id, 1, static_cast<const GLfloat*>(value)));
        else if (size == 4)
            glsafe(::glUniform4fv(id, 1, static_cast<const GLfloat*>(value)));
    }
}
References glsafe, and set_uniform().
set_uniform() [29/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Matrix3d & value) const
{
    set_uniform(id, (Matrix3f)value.cast<float>());
}
References set_uniform().
set_uniform() [30/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Matrix3f & value) const
{
    if (id >= 0)
        glsafe(::glUniformMatrix3fv(id, 1, GL_FALSE, static_cast<const GLfloat*>(value.data())));
}
References Eigen::PlainObjectBase< Derived >::data(), GL_FALSE, and glsafe.
set_uniform() [31/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Matrix4d & value) const
{
    set_uniform(id, (Matrix4f)value.cast<float>());
}
References set_uniform().
set_uniform() [32/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Matrix4f & value) const
set_uniform() [33/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const std::array< double, 4 > & value) const
{
    const std::array<float, 4> f_value = { float(value[0]), float(value[1]), float(value[2]), float(value[3]) };
    set_uniform(id, f_value);
}
References set_uniform().
set_uniform() [34/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const std::array< float, 2 > & value) const
{
    if (id >= 0)
        glsafe(::glUniform2fv(id, 1, static_cast<const GLfloat*>(value.data())));
}
References glsafe.
set_uniform() [35/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const std::array< float, 3 > & value) const
{
    if (id >= 0)
        glsafe(::glUniform3fv(id, 1, static_cast<const GLfloat*>(value.data())));
}
References glsafe.
set_uniform() [36/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const std::array< float, 4 > & value) const
{
    if (id >= 0)
        glsafe(::glUniform4fv(id, 1, static_cast<const GLfloat*>(value.data())));
}
References glsafe.
set_uniform() [37/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const std::array< int, 2 > & value) const
{
    if (id >= 0)
        glsafe(::glUniform2iv(id, 1, static_cast<const GLint*>(value.data())));
}
References glsafe.
set_uniform() [38/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const std::array< int, 3 > & value) const
{
    if (id >= 0)
        glsafe(::glUniform3iv(id, 1, static_cast<const GLint*>(value.data())));
}
References glsafe.
set_uniform() [39/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const std::array< int, 4 > & value) const
{
    if (id >= 0)
        glsafe(::glUniform4iv(id, 1, static_cast<const GLint*>(value.data())));
}
References glsafe.
set_uniform() [40/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Transform3d & value) const
{
    set_uniform(id, value.cast<float>());
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast(), and set_uniform().
set_uniform() [41/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Transform3f & value) const
{
    if (id >= 0)
        glsafe(::glUniformMatrix4fv(id, 1, GL_FALSE, static_cast<const GLfloat*>(value.matrix().data())));
}
References Eigen::PlainObjectBase< Derived >::data(), GL_FALSE, glsafe, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix().
set_uniform() [42/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Vec2d & value) const
{
    set_uniform(id, static_cast<Vec2f>(value.cast<float>()));
}
References set_uniform().
set_uniform() [43/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Vec2f & value) const
{
    if (id >= 0)
        glsafe(::glUniform2fv(id, 1, static_cast<const GLfloat*>(value.data())));
}
References Eigen::PlainObjectBase< Derived >::data(), and glsafe.
set_uniform() [44/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Vec3d & value) const
{
    set_uniform(id, static_cast<Vec3f>(value.cast<float>()));
}
References set_uniform().
set_uniform() [45/48]
void Slic3r::GLShaderProgram::set_uniform (int id, const Vec3f & value) const
{
    if (id >= 0)
        glsafe(::glUniform3fv(id, 1, static_cast<const GLfloat*>(value.data())));
}
References Eigen::PlainObjectBase< Derived >::data(), and glsafe.
set_uniform() [46/48]
void Slic3r::GLShaderProgram::set_uniform (int id, double value) const
{
    set_uniform(id, static_cast<float>(value));
}
References set_uniform().
set_uniform() [47/48]
void Slic3r::GLShaderProgram::set_uniform (int id, float value) const
{
    if (id >= 0)
        glsafe(::glUniform1f(id, value));
}
References glsafe.
set_uniform() [48/48]
void Slic3r::GLShaderProgram::set_uniform (int id, int value) const
{
    if (id >= 0)
        glsafe(::glUniform1i(id, value));
}
References glsafe.
start_using()
void Slic3r::GLShaderProgram::start_using () const
{
    assert(m_id > 0);
    glsafe(::glUseProgram(m_id));
}
References glsafe, and m_id.
Referenced by Slic3r::GUI::GLCanvas3D::_render_background(), Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::_render_volumes_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GCodeViewer::COG::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::render(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::CoordAxes::render(), Slic3r::GLVolumeCollection::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::MeshClipper::render_contour(), Slic3r::GUI::Bed3D::render_contour(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere(), Slic3r::GUI::MeshClipper::render_cut(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::Bed3D::render_default(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::ImGuiWrapper::render_draw_data(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_line(), Slic3r::GUI::Bed3D::render_model(), Slic3r::GUI::GLGizmoCut3D::render_model(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::GCodeViewer::render_shells(), Slic3r::GUI::Selection::render_sidebar_hints(), Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::Bed3D::render_texture(), Slic3r::GUI::GCodeViewer::render_toolpaths(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_volumes().
stop_using()
void Slic3r::GLShaderProgram::stop_using () const
{
    glsafe(::glUseProgram(0));
}
References glsafe.
Referenced by Slic3r::GUI::GLCanvas3D::_render_background(), Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::_render_sla_slices(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::_render_volumes_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GCodeViewer::COG::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::render(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::CoordAxes::render(), Slic3r::GLVolumeCollection::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::MeshClipper::render_contour(), Slic3r::GUI::Bed3D::render_contour(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere(), Slic3r::GUI::MeshClipper::render_cut(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::Bed3D::render_default(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::ImGuiWrapper::render_draw_data(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_line(), Slic3r::GUI::Bed3D::render_model(), Slic3r::GUI::GLGizmoCut3D::render_model(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::GCodeViewer::render_shells(), Slic3r::GUI::Selection::render_sidebar_hints(), Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::Bed3D::render_texture(), Slic3r::GUI::GCodeViewer::render_toolpaths(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_volumes().
Member Data Documentation
m_attrib_location_cache
std::vector<std::pair<std::string, int> > Slic3r::GLShaderProgram::m_attrib_location_cache private
Referenced by get_attrib_location().
m_id
unsigned int Slic3r::GLShaderProgram::m_id { 0 } private
Referenced by ~GLShaderProgram(), get_attrib_location(), get_id(), init_from_texts(), and start_using().
m_name
std::string Slic3r::GLShaderProgram::m_name private
Referenced by get_name(), and init_from_texts().
m_uniform_location_cache
std::vector<std::pair<std::string, int> > Slic3r::GLShaderProgram::m_uniform_location_cache private
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLShader.hpp
src/slic3r/GUI/GLShader.cpp