Prusa Slicer: Slic3r::GUI::GLGizmoHollow Class Reference
Slic3r::GUI::GLGizmoHollow Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoHollow.hpp>
Public Types
enum class EGrabberExtension {
None = 0 , PosX = 1 << 0 , NegX = 1 << 1 , PosY = 1 << 2 ,
NegY = 1 << 3 , PosZ = 1 << 4 , NegZ = 1 << 5
}
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoHollow (GLCanvas3D &parent, const std::string &icon_filename, unsigned int sprite_id)
void data_changed (bool is_serializing) override
Is called when data (Selection) is changed.
bool gizmo_event (SLAGizmoEventType action, const Vec2d &mouse_position, bool shift_down, bool alt_down, bool control_down)
void delete_selected_points ()
bool is_selection_rectangle_dragging () const override
bool on_mouse (const wxMouseEvent &mouse_event) override
Postpone to Grabber for move Detect move of object by dragging.
void reslice_until_step (SLAPrintObjectStep step, bool postpone_error_messages=false)
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
virtual bool wants_enter_leave_snapshots () const
virtual std::string get_gizmo_entering_text () const
virtual std::string get_gizmo_leaving_text () const
virtual std::string get_action_snapshot_name () const
void set_common_data_pool (CommonGizmosDataPool *ptr)
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
bool is_dragging () const
bool update_items_state ()
void render ()
void render_input_window (float x, float y, float bottom_limit)
virtual std::string get_tooltip () const
Mouse tooltip text.
void register_raycasters_for_picking ()
void unregister_raycasters_for_picking ()
virtual bool is_in_editing_mode () const
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static const unsigned int GRABBER_ELEMENTS_MAX_COUNT = 7
static const int NO_SHORTCUT_KEY_VALUE = 0
Protected Member Functions
bool on_init () override
void on_render () override
virtual void on_register_raycasters_for_picking () override
virtual void on_unregister_raycasters_for_picking () override
void on_set_state () override
void on_set_hover_id () override
void on_start_dragging () override
void on_stop_dragging () override
void on_dragging (const UpdateData &data) override
void on_render_input_window (float x, float y, float bottom_limit) override
std::string on_get_name () const override
bool on_is_activable () const override
bool on_is_selectable () const override
void on_load (cereal::BinaryInputArchive &ar) override
void on_save (cereal::BinaryOutputArchive &ar) const override
void init_cylinder_model ()
virtual CommonGizmosDataID on_get_requirements () const override
void update_volumes ()
void render_volumes ()
void register_volume_raycasters_for_picking ()
void unregister_volume_raycasters_for_picking ()
bool is_input_enabled () const
int get_min_sla_print_object_step () const
bool unproject_on_mesh (const Vec2d &mouse_pos, std::pair< Vec3f, Vec3f > &pos_and_normal)
bool are_sla_supports_shown () const
void show_sla_supports (bool show)
const GLVolumeCollection & volumes () const
virtual void on_enable_grabber (unsigned int id)
virtual void on_disable_grabber (unsigned int id)
void register_grabbers_for_picking ()
void unregister_grabbers_for_picking ()
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers (size_t first, size_t last, float size, bool force_hover) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
bool use_grabbers (const wxMouseEvent &mouse_event)
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
void do_stop_dragging (bool perform_mouse_cleanup)
Protected Attributes
GLCanvas3D & m_parent
int m_group_id
EState m_state
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id { -1 }
bool m_dragging { false }
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render { true }
CommonGizmosDataPool * m_c { nullptr }
Private Types
enum { AllPoints = -2 , NoPoints }
Private Member Functions
void render_points (const Selection &selection)
void register_hole_raycasters_for_picking ()
void unregister_hole_raycasters_for_picking ()
void update_hole_raycasters_for_picking_transform ()
std::vector< std::pair< const ConfigOption *, const ConfigOptionDef * > > get_config_options (const std::vector< std::string > &keys) const
bool is_mesh_point_clipped (const Vec3d &point) const
void select_point (int i)
void unselect_point (int i)
void reload_cache ()
Private Attributes
ObjectID m_old_mo_id = -1
PickingModel m_cylinder
std::vector< std::shared_ptr< SceneRaycasterItem > > m_hole_raycasters
float m_new_hole_radius = 2.f
float m_new_hole_height = 6.f
std::vector< bool > m_selected
bool m_enable_hollowing = true
float m_offset_stash = 3.0f
float m_quality_stash = 0.5f
float m_closing_d_stash = 2.f
Vec3f m_hole_before_drag = Vec3f::Zero()
sla::DrainHoles m_holes_in_drilled_mesh
sla::DrainHoles m_holes_stash
std::map< std::string, wxString > m_desc
GLSelectionRectangle m_selection_rectangle
bool m_wait_for_up_event = false
bool m_selection_empty = true
EState m_old_state = Off
GLVolumeCollection m_volumes
bool m_input_enabled { false }
bool m_show_sla_supports { false }
int m_min_sla_print_object_step { -1 }
std::vector< std::shared_ptr< SceneRaycasterItem > > m_volume_raycasters
bool m_dirty { false }
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
AllPoints
NoPoints
         {
        AllPoints = -2,
        NoPoints,
    };
EGrabberExtension
enum class Slic3r::GUI::GLGizmoBase::EGrabberExtension strong inherited
Enumerator
None
PosX
NegX
PosY
NegY
PosZ
NegZ
    {
        None = 0,
        PosX = 1 << 0,
        NegX = 1 << 1,
        PosY = 1 << 2,
        NegY = 1 << 3,
        PosZ = 1 << 4,
        NegZ = 1 << 5,
    };
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
Constructor & Destructor Documentation
GLGizmoHollow()
Slic3r::GUI::GLGizmoHollow::GLGizmoHollow (GLCanvas3D & parent, const std::string & icon_filename, unsigned int sprite_id)
    : GLGizmoSlaBase(parent, icon_filename, sprite_id, slaposAssembly)
{
}
Member Function Documentation
are_sla_supports_shown()
bool Slic3r::GUI::GLGizmoSlaBase::are_sla_supports_shown () const inline protected inherited
{ return m_show_sla_supports; }
References Slic3r::GUI::GLGizmoSlaBase::m_show_sla_supports.
Referenced by on_render(), and on_render_input_window().
data_changed()
void Slic3r::GUI::GLGizmoHollow::data_changed (bool is_serializing) override virtual
Is called when data (Selection) is changed.
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (! m_c->selection_info())
        return;
    const ModelObject* mo = m_c->selection_info()->model_object();
    if (m_state == On && mo) {
        if (m_old_mo_id != mo->id()) {
            reload_cache();
            m_old_mo_id = mo->id();
        }
        const SLAPrintObject* po = m_c->selection_info()->print_object();
        if (po != nullptr) {
            std::shared_ptr<const indexed_triangle_set> preview_mesh_ptr = po->get_mesh_to_print();
            if (!preview_mesh_ptr || preview_mesh_ptr->empty())
                reslice_until_step(slaposAssembly);
        }
        update_volumes();
        if (m_hole_raycasters.empty())
            register_hole_raycasters_for_picking();
        else
            update_hole_raycasters_for_picking_transform();
        m_c->instances_hider()->set_hide_full_scene(true);
    }
}
References Slic3r::SLAPrintObject::get_mesh_to_print(), Slic3r::ObjectBase::id(), Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::GLGizmoBase::m_c, m_hole_raycasters, m_old_mo_id, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), register_hole_raycasters_for_picking(), reload_cache(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::set_hide_full_scene(), Slic3r::slaposAssembly, update_hole_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
delete_selected_points()
void Slic3r::GUI::GLGizmoHollow::delete_selected_points ()
{
    Plater::TakeSnapshot snapshot(wxGetApp().plater(), _(L("Delete drainage hole")));
    sla::DrainHoles& drain_holes = m_c->selection_info()->model_object()->sla_drain_holes;
    for (unsigned int idx=0; idx<drain_holes.size(); ++idx) {
        if (m_selected[idx]) {
            m_selected.erase(m_selected.begin()+idx);
            drain_holes.erase(drain_holes.begin() + (idx--));
        }
    }
    unregister_hole_raycasters_for_picking();
    register_hole_raycasters_for_picking();
    select_point(NoPoints);
}
References _, L, Slic3r::GUI::GLGizmoBase::m_c, m_selected, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), NoPoints, Slic3r::GUI::plater(), register_hole_raycasters_for_picking(), select_point(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::ModelObject::sla_drain_holes, and unregister_hole_raycasters_for_picking().
Referenced by gizmo_event(), and on_render_input_window().
do_stop_dragging()
void Slic3r::GUI::GLGizmoBase::do_stop_dragging (bool perform_mouse_cleanup) protected inherited
{
    for (auto& grabber : m_grabbers) grabber.dragging = false;
    m_dragging = false;
    // NOTE: This should be part of GLCanvas3D
    // Reset hover_id when leave window
    if (perform_mouse_cleanup) m_parent.mouse_up_cleanup();
    on_stop_dragging();
    // There is prediction that after draggign, data are changed
    // Data are updated twice also by canvas3D::reload_scene.
    // Should be fixed.
    m_parent.get_gizmos_manager().update_data();
    wxGetApp().obj_manipul()->set_dirty();
    // Let the plater know that the dragging finished, so a delayed
    // refresh of the scene with the background processing data should
    // be performed.
    m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED));
    // updates camera target constraints
    m_parent.refresh_camera_scene_box();
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_up_cleanup(), Slic3r::GUI::GLGizmoBase::on_stop_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::refresh_camera_scene_box(), and Slic3r::GUI::GLGizmosManager::update_data().
Referenced by Slic3r::GUI::GLGizmoBase::use_grabbers().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoEmboss::init_font_name_texture(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoEmboss::rev_input(), Slic3r::GUI::GLGizmoEmboss::rev_input_mm(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
get_action_snapshot_name()
std::string Slic3r::GUI::GLGizmoBase::get_action_snapshot_name () const virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
{
    return _u8L("Gizmo action");
}
References _u8L.
Referenced by Slic3r::GUI::Plater::priv::take_snapshot().
get_config_options()
std::vector< std::pair< const ConfigOption *, const ConfigOptionDef * > > Slic3r::GUI::GLGizmoHollow::get_config_options (const std::vector< std::string > & keys) const private
{
    std::vector<std::pair<const ConfigOption*, const ConfigOptionDef*>> out;
    const ModelObject* mo = m_c->selection_info()->model_object();
    if (! mo)
        return out;
    const DynamicPrintConfig& object_cfg = mo->config.get();
    const DynamicPrintConfig& print_cfg = wxGetApp().preset_bundle->sla_prints.get_edited_preset().config;
    std::unique_ptr<DynamicPrintConfig> default_cfg = nullptr;
    for (const std::string& key : keys) {
        if (object_cfg.has(key))
            out.emplace_back(object_cfg.option(key), object_cfg.option_def(key));
        else
            if (print_cfg.has(key))
                out.emplace_back(print_cfg.option(key), print_cfg.option_def(key));
            else { // we must get it from defaults
                if (default_cfg == nullptr)
                    default_cfg.reset(DynamicPrintConfig::new_from_defaults_keys(keys));
                out.emplace_back(default_cfg->option(key), default_cfg->option_def(key));
            }
    }
    return out;
}
References Slic3r::ModelObject::config, Slic3r::ModelConfig::get(), Slic3r::ConfigOptionResolver::has(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::DynamicPrintConfig::new_from_defaults_keys(), Slic3r::ConfigBase::option(), Slic3r::ConfigBase::option_def(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by on_render_input_window().
get_gizmo_entering_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_entering_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
get_gizmo_leaving_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_leaving_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmosManager::grabber_contains_mouse(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), and Slic3r::GUI::GLGizmoSlaSupports::on_mouse().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_min_sla_print_object_step()
int Slic3r::GUI::GLGizmoSlaBase::get_min_sla_print_object_step () const inline protected inherited
{ return m_min_sla_print_object_step; }
References Slic3r::GUI::GLGizmoSlaBase::m_min_sla_print_object_step.
Referenced by Slic3r::GUI::GLGizmoSlaSupports::data_changed().
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    std::string out = on_get_name();
    if (!include_shortcut) return out;
    int key = get_shortcut_key();
    assert(key==NO_SHORTCUT_KEY_VALUE || (key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z));
    out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE, and Slic3r::GUI::GLGizmoBase::on_get_name().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay().
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLCanvas3D::on_mouse().
get_tooltip()
virtual std::string Slic3r::GUI::GLGizmoBase::get_tooltip () const inline virtual inherited
Mouse tooltip text.
Returns
Text to be visible in mouse tooltip
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoScale3D.
{ return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::get_tooltip().
gizmo_event()
bool Slic3r::GUI::GLGizmoHollow::gizmo_event (SLAGizmoEventType action, const Vec2d & mouse_position, bool shift_down, bool alt_down, bool control_down)
{
    ModelObject* mo = m_c->selection_info()->model_object();
    int active_inst = m_c->selection_info()->get_active_instance();
    // left down with shift - show the selection rectangle:
    if (action == SLAGizmoEventType::LeftDown && (shift_down || alt_down || control_down)) {
        if (m_hover_id == -1) {
            if (shift_down || alt_down)
                m_selection_rectangle.start_dragging(mouse_position, shift_down ? GLSelectionRectangle::EState::Select : GLSelectionRectangle::EState::Deselect);
        }
        else {
            if (m_selected[m_hover_id])
                unselect_point(m_hover_id);
            else {
                if (!alt_down)
                    select_point(m_hover_id);
            }
        }
        return true;
    }
    // left down without selection rectangle - place point on the mesh:
    if (action == SLAGizmoEventType::LeftDown && !m_selection_rectangle.is_dragging() && !shift_down) {
        // If any point is in hover state, this should initiate its move - return control back to GLCanvas:
        if (m_hover_id != -1)
            return false;
        // If there is some selection, don't add new point and deselect everything instead.
        if (m_selection_empty) {
            std::pair<Vec3f, Vec3f> pos_and_normal;
            if (unproject_on_mesh(mouse_position, pos_and_normal)) { // we got an intersection
                Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Add drainage hole"));
                mo->sla_drain_holes.emplace_back(pos_and_normal.first,
                                                -pos_and_normal.second, m_new_hole_radius, m_new_hole_height);
                m_selected.push_back(false);
                assert(m_selected.size() == mo->sla_drain_holes.size());
                m_parent.set_as_dirty();
                m_wait_for_up_event = true;
                unregister_hole_raycasters_for_picking();
                register_hole_raycasters_for_picking();
            }
            else
                return false;
        }
        else
            select_point(NoPoints);
        return true;
    }
    // left up with selection rectangle - select points inside the rectangle:
    if ((action == SLAGizmoEventType::LeftUp || action == SLAGizmoEventType::ShiftUp || action == SLAGizmoEventType::AltUp) && m_selection_rectangle.is_dragging()) {
        // Is this a selection or deselection rectangle?
        GLSelectionRectangle::EState rectangle_status = m_selection_rectangle.get_state();
        // First collect positions of all the points in world coordinates.
        Geometry::Transformation trafo = mo->instances[active_inst]->get_transformation();
        trafo.set_offset(trafo.get_offset() + Vec3d(0., 0., m_c->selection_info()->get_sla_shift()));
        std::vector<Vec3d> points;
        for (unsigned int i=0; i<mo->sla_drain_holes.size(); ++i)
            points.push_back(trafo.get_matrix() * mo->sla_drain_holes[i].pos.cast<double>());
        // Now ask the rectangle which of the points are inside.
        std::vector<Vec3f> points_inside;
        std::vector<unsigned int> points_idxs = m_selection_rectangle.contains(points);
        m_selection_rectangle.stop_dragging();
        for (size_t idx : points_idxs)
            points_inside.push_back(points[idx].cast<float>());
        // Only select/deselect points that are actually visible
        for (size_t idx : m_c->raycaster()->raycaster()->get_unobscured_idxs(
                 trafo, wxGetApp().plater()->get_camera(), points_inside,
                 m_c->object_clipper()->get_clipping_plane()))
        {
            if (rectangle_status == GLSelectionRectangle::EState::Deselect)
                unselect_point(points_idxs[idx]);
            else
                select_point(points_idxs[idx]);
        }
        return true;
    }
    // left up with no selection rectangle
    if (action == SLAGizmoEventType::LeftUp) {
        if (m_wait_for_up_event) {
            m_wait_for_up_event = false;
            return true;
        }
    }
    // dragging the selection rectangle:
    if (action == SLAGizmoEventType::Dragging) {
        if (m_wait_for_up_event)
            return true; // point has been placed and the button not released yet
                         // this prevents GLCanvas from starting scene rotation
        if (m_selection_rectangle.is_dragging())  {
            m_selection_rectangle.dragging(mouse_position);
            return true;
        }
        return false;
    }
    if (action == SLAGizmoEventType::Delete) {
        // delete key pressed
        delete_selected_points();
        return true;
    }
    if (action == SLAGizmoEventType::RightDown) {
        if (m_hover_id != -1) {
            select_point(NoPoints);
            select_point(m_hover_id);
            delete_selected_points();
            return true;
        }
        return false;
    }
    if (action == SLAGizmoEventType::SelectAll) {
        select_point(AllPoints);
        return true;
    }
    if (action == SLAGizmoEventType::MouseWheelUp && control_down) {
        double pos = m_c->object_clipper()->get_position();
        pos = std::min(1., pos + 0.01);
        m_c->object_clipper()->set_position_by_ratio(pos, true);
        return true;
    }
    if (action == SLAGizmoEventType::MouseWheelDown && control_down) {
        double pos = m_c->object_clipper()->get_position();
        pos = std::max(0., pos - 0.01);
        m_c->object_clipper()->set_position_by_ratio(pos, true);
        return true;
    }
    if (action == SLAGizmoEventType::ResetClippingPlane) {
        m_c->object_clipper()->set_position_by_ratio(-1., false);
        return true;
    }
    return false;
}
References _L, AllPoints, Slic3r::GUI::AltUp, Slic3r::GUI::GLSelectionRectangle::contains(), Slic3r::GUI::Delete, delete_selected_points(), Slic3r::GUI::GLSelectionRectangle::Deselect, Slic3r::GUI::Dragging, Slic3r::GUI::GLSelectionRectangle::dragging(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::GUI::GLSelectionRectangle::get_state(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::ModelObject::instances, Slic3r::GUI::GLSelectionRectangle::is_dragging(), Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_hover_id, m_new_hole_height, m_new_hole_radius, Slic3r::GUI::GLGizmoBase::m_parent, m_selected, m_selection_empty, m_selection_rectangle, m_wait_for_up_event, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::MouseWheelDown, Slic3r::GUI::MouseWheelUp, NoPoints, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::plater(), Slic3r::points_inside(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycaster(), register_hole_raycasters_for_picking(), Slic3r::GUI::ResetClippingPlane, Slic3r::GUI::RightDown, Slic3r::GUI::GLSelectionRectangle::Select, select_point(), Slic3r::GUI::SelectAll, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::Geometry::Transformation::set_offset(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position_by_ratio(), Slic3r::GUI::ShiftUp, Slic3r::ModelObject::sla_drain_holes, Slic3r::GUI::GLSelectionRectangle::start_dragging(), Slic3r::GUI::GLSelectionRectangle::stop_dragging(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), unregister_hole_raycasters_for_picking(), and unselect_point().
Referenced by on_mouse().
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_init().
init_cylinder_model()
void Slic3r::GUI::GLGizmoHollow::init_cylinder_model () protected
{
    if (!m_cylinder.model.is_initialized()) {
        indexed_triangle_set its = its_make_cylinder(1.0, 1.0);
        m_cylinder.model.init_from(its);
        m_cylinder.mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
    }
}
References Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::its_make_cylinder(), m_cylinder, Slic3r::GUI::PickingModel::mesh_raycaster, and Slic3r::GUI::PickingModel::model.
Referenced by register_hole_raycasters_for_picking().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmosManager::handle_shortcut(), Slic3r::GUI::GLGizmoEmboss::init_create(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
Referenced by Slic3r::GUI::GLGizmoCut3D::gizmo_event(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate().
is_in_editing_mode()
virtual bool Slic3r::GUI::GLGizmoBase::is_in_editing_mode () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::on_key().
is_input_enabled()
bool Slic3r::GUI::GLGizmoSlaBase::is_input_enabled () const inline protected inherited
{ return m_input_enabled; }
References Slic3r::GUI::GLGizmoSlaBase::m_input_enabled.
Referenced by on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), on_render_input_window(), and Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window().
is_mesh_point_clipped()
bool Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped (const Vec3d & point) const private
{
    if (m_c->object_clipper()->get_position() == 0.)
        return false;
    auto sel_info = m_c->selection_info();
    int active_inst = m_c->selection_info()->get_active_instance();
    const ModelInstance* mi = sel_info->model_object()->instances[active_inst];
    const Transform3d& trafo = mi->get_transformation().get_matrix() * sel_info->model_object()->volumes.front()->get_matrix();
    Vec3d transformed_point =  trafo * point;
    transformed_point(2) += sel_info->get_sla_shift();
    return m_c->object_clipper()->get_clipping_plane()->is_point_clipped(transformed_point);
}
References Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::ModelInstance::get_transformation(), Slic3r::GUI::ClippingPlane::is_point_clipped(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by render_points().
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
is_selection_rectangle_dragging()
bool Slic3r::GUI::GLGizmoHollow::is_selection_rectangle_dragging () const inline override virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
        return m_selection_rectangle.is_dragging();
    }
References Slic3r::GUI::GLSelectionRectangle::is_dragging(), and m_selection_rectangle.
load()
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
on_disable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_disable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_dragging()
void Slic3r::GUI::GLGizmoHollow::on_dragging (const UpdateData & data) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    assert(m_hover_id != -1);
    std::pair<Vec3f, Vec3f> pos_and_normal;
    if (!unproject_on_mesh(data.mouse_pos.cast<double>(), pos_and_normal))
        return;
    sla::DrainHoles &drain_holes =  m_c->selection_info()->model_object()->sla_drain_holes;
    drain_holes[m_hover_id].pos    = pos_and_normal.first;
    drain_holes[m_hover_id].normal = -pos_and_normal.second;
}
References Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::ModelObject::sla_drain_holes, and Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh().
on_enable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_enable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_get_name()
std::string Slic3r::GUI::GLGizmoHollow::on_get_name () const override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    return _u8L("Hollow and drill");
}
References _u8L.
on_get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoSlaBase::on_get_requirements () const override protected virtual inherited
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return CommonGizmosDataID(
                int(CommonGizmosDataID::SelectionInfo)
              | int(CommonGizmosDataID::InstancesHider)
              | int(CommonGizmosDataID::Raycaster)
              | int(CommonGizmosDataID::ObjectClipper)
              | int(CommonGizmosDataID::SupportsClipper));
}
References Slic3r::GUI::InstancesHider, Slic3r::GUI::ObjectClipper, Slic3r::GUI::Raycaster, Slic3r::GUI::SelectionInfo, and Slic3r::GUI::SupportsClipper.
on_init()
bool Slic3r::GUI::GLGizmoHollow::on_init () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    m_shortcut_key = WXK_CONTROL_H;
    m_desc["enable"]           = _(L("Hollow this object"));
    m_desc["preview"]          = _(L("Preview hollowed and drilled model"));
    m_desc["offset"]           = _(L("Offset")) + ": ";
    m_desc["quality"]          = _(L("Quality")) + ": ";
    m_desc["closing_distance"] = _(L("Closing distance")) + ": ";
    m_desc["hole_diameter"]    = _(L("Hole diameter")) + ": ";
    m_desc["hole_depth"]       = _(L("Hole depth")) + ": ";
    m_desc["remove_selected"]  = _(L("Remove selected holes"));
    m_desc["remove_all"]       = _(L("Remove all holes"));
    m_desc["clipping_of_view"] = _(L("Clipping of view"))+ ": ";
    m_desc["reset_direction"]  = _(L("Reset direction"));
    m_desc["show_supports"]    = _(L("Show supports"));
    return true;
}
References _, L, m_desc, and Slic3r::GUI::GLGizmoBase::m_shortcut_key.
on_is_activable()
bool Slic3r::GUI::GLGizmoHollow::on_is_activable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    const Selection& selection = m_parent.get_selection();
    if (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() != ptSLA
        || !selection.is_single_full_instance())
        return false;
    // Check that none of the selected volumes is outside. Only SLA auxiliaries (supports) are allowed outside.
    const Selection::IndicesList& list = selection.get_volume_idxs();
    for (const auto& idx : list)
        if (selection.get_volume(idx)->is_outside && selection.get_volume(idx)->composite_id.volume_id >= 0)
            return false;
    // Check that none of the selected volumes is marked as non-pritable.
    for (const auto& idx : list) {
        if (!selection.get_volume(idx)->printable)
            return false;
    }
    return true;
}
References Slic3r::GLVolume::composite_id, Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::ptSLA, and Slic3r::GLVolume::CompositeID::volume_id.
on_is_selectable()
bool Slic3r::GUI::GLGizmoHollow::on_is_selectable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptSLA);
}
References Slic3r::ptSLA.
on_load()
void Slic3r::GUI::GLGizmoHollow::on_load (cereal::BinaryInputArchive & ar) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar(m_new_hole_radius,
       m_new_hole_height,
       m_selected,
       m_selection_empty
    );
}
References m_new_hole_height, m_new_hole_radius, m_selected, and m_selection_empty.
on_mouse()
bool Slic3r::GUI::GLGizmoHollow::on_mouse (const wxMouseEvent & mouse_event) override virtual
Postpone to Grabber for move Detect move of object by dragging.
Parameters
mouse_event Keep information about mouse click
Returns
Return True when use the information otherwise False.
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (!is_input_enabled()) return true;
    if (mouse_event.Moving()) return false;
    if (use_grabbers(mouse_event)) return true;
    // wxCoord == int --> wx/types.h
    Vec2i mouse_coord(mouse_event.GetX(), mouse_event.GetY());
    Vec2d mouse_pos = mouse_coord.cast<double>();
    static bool pending_right_up = false;
    if (mouse_event.LeftDown()) {
        bool control_down = mouse_event.CmdDown();
        bool grabber_contains_mouse = (get_hover_id() != -1);
        if ((!control_down || grabber_contains_mouse) &&
            gizmo_event(SLAGizmoEventType::LeftDown, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), false))
            // the gizmo got the event and took some action, there is no need
            // to do anything more
            return true;
    } else if (mouse_event.Dragging()) {
        if (m_parent.get_move_volume_id() != -1)
            // don't allow dragging objects with the Sla gizmo on
            return true;
        bool control_down = mouse_event.CmdDown();
        if (control_down) {
            // CTRL has been pressed while already dragging -> stop current action
            if (mouse_event.LeftIsDown())
                gizmo_event(SLAGizmoEventType::LeftUp, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), true);
            else if (mouse_event.RightIsDown()) {
                pending_right_up = false;
            }
        } else if(gizmo_event(SLAGizmoEventType::Dragging, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), false)) {
            // the gizmo got the event and took some action, no need to do
            // anything more here
            m_parent.set_as_dirty();
            return true;
        }
    } else if (mouse_event.LeftUp()) {
        if (!m_parent.is_mouse_dragging()) {
            bool control_down = mouse_event.CmdDown();
            // in case gizmo is selected, we just pass the LeftUp event
            // and stop processing - neither object moving or selecting is
            // suppressed in that case
            gizmo_event(SLAGizmoEventType::LeftUp, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), control_down);
            return true;
        }
    } else if (mouse_event.RightDown()) {
        if (m_parent.get_selection().get_object_idx() != -1 &&
            gizmo_event(SLAGizmoEventType::RightDown, mouse_pos, false, false, false)) {
            // we need to set the following right up as processed to avoid showing
            // the context menu if the user release the mouse over the object
            pending_right_up = true;
            // event was taken care of by the SlaSupports gizmo
            return true;
        }
    } else if (mouse_event.RightUp()) {
        if (pending_right_up) {
            pending_right_up = false;
            return true;
        }
    }
    return false;
}
References Slic3r::GUI::Dragging, Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLCanvas3D::get_move_volume_id(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), gizmo_event(), Slic3r::GUI::GLGizmoSlaBase::is_input_enabled(), Slic3r::GUI::GLCanvas3D::is_mouse_dragging(), Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::RightDown, Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
on_register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoHollow::on_register_raycasters_for_picking () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    register_hole_raycasters_for_picking();
    register_volume_raycasters_for_picking();
}
References register_hole_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking().
on_render()
void Slic3r::GUI::GLGizmoHollow::on_render () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    const Selection& selection = m_parent.get_selection();
    const CommonGizmosDataObjects::SelectionInfo* sel_info = m_c->selection_info();
    // If current m_c->m_model_object does not match selection, ask GLCanvas3D to turn us off
    if (m_state == On
     && (sel_info->model_object() != selection.get_model()->objects[selection.get_object_idx()]
      || sel_info->get_active_instance() != selection.get_instance_idx())) {
        m_parent.post_event(SimpleEvent(EVT_GLCANVAS_RESETGIZMOS));
        return;
    }
    if (m_state == On) {
        // This gizmo is showing the object elevated. Tell the common
        // SelectionInfo object to lie about the actual shift.
        m_c->selection_info()->set_use_shift(true);
    }
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glEnable(GL_DEPTH_TEST));
    render_volumes();
    render_points(selection);
    m_selection_rectangle.render(m_parent);
    m_c->object_clipper()->render_cut();
    if (are_sla_supports_shown())
        m_c->supports_clipper()->render_cut();
    glsafe(::glDisable(GL_BLEND));
}
References Slic3r::GUI::GLGizmoSlaBase::are_sla_supports_shown(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), glsafe, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_parent, m_selection_rectangle, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::Model::objects, Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), render_points(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::set_use_shift(), and Slic3r::GUI::CommonGizmosDataPool::supports_clipper().
on_render_input_window()
void Slic3r::GUI::GLGizmoHollow::on_render_input_window (float x, float y, float bottom_limit) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ModelObject* mo = m_c->selection_info()->model_object();
    if (! mo)
        return;
    bool first_run = true; // This is a hack to redraw the button when all points are removed,
                           // so it is not delayed until the background process finishes.
    ConfigOptionMode current_mode = wxGetApp().get_mode();
    std::vector<std::string> opts_keys = {"hollowing_min_thickness", "hollowing_quality", "hollowing_closing_distance"};
    auto opts = get_config_options(opts_keys);
    auto* offset_cfg = static_cast<const ConfigOptionFloat*>(opts[0].first);
    float offset = offset_cfg->value;
    double offset_min = opts[0].second->min;
    double offset_max = opts[0].second->max;
    auto* quality_cfg = static_cast<const ConfigOptionFloat*>(opts[1].first);
    float quality = quality_cfg->value;
    double quality_min = opts[1].second->min;
    double quality_max = opts[1].second->max;
    ConfigOptionMode quality_mode = opts[1].second->mode;
    auto* closing_d_cfg = static_cast<const ConfigOptionFloat*>(opts[2].first);
    float closing_d = closing_d_cfg->value;
    double closing_d_min = opts[2].second->min;
    double closing_d_max = opts[2].second->max;
    ConfigOptionMode closing_d_mode = opts[2].second->mode;
    m_desc["offset"] = _(opts[0].second->label) + ":";
    m_desc["quality"] = _(opts[1].second->label) + ":";
    m_desc["closing_distance"] = _(opts[2].second->label) + ":";
RENDER_AGAIN:
    const float approx_height = m_imgui->scaled(20.0f);
    y = std::min(y, bottom_limit - approx_height);
    m_imgui->set_next_window_pos(x, y, ImGuiCond_Always);
    m_imgui->begin(get_name(), ImGuiWindowFlags_NoMove | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoCollapse);
    // First calculate width of all the texts that are could possibly be shown. We will decide set the dialog width based on that:
    const float clipping_slider_left = std::max(m_imgui->calc_text_size(m_desc.at("clipping_of_view")).x,
                                                m_imgui->calc_text_size(m_desc.at("reset_direction")).x) + m_imgui->scaled(0.5f);
    const float settings_sliders_left =
        std::max(std::max({m_imgui->calc_text_size(m_desc.at("offset")).x,
                           m_imgui->calc_text_size(m_desc.at("quality")).x,
                           m_imgui->calc_text_size(m_desc.at("closing_distance")).x,
                           m_imgui->calc_text_size(m_desc.at("hole_diameter")).x,
                           m_imgui->calc_text_size(m_desc.at("hole_depth")).x}) + m_imgui->scaled(0.5f), clipping_slider_left);
    const float diameter_slider_left = settings_sliders_left; //m_imgui->calc_text_size(m_desc.at("hole_diameter")).x + m_imgui->scaled(1.f);
    const float minimal_slider_width = m_imgui->scaled(4.f);
    const float button_preview_width = m_imgui->calc_button_size(m_desc.at("preview")).x;
    float window_width = minimal_slider_width + std::max({settings_sliders_left, clipping_slider_left, diameter_slider_left});
    window_width = std::max(window_width, button_preview_width);
    m_imgui->disabled_begin(!is_input_enabled());
    if (m_imgui->button(m_desc["preview"]))
        reslice_until_step(slaposDrillHoles);
    bool config_changed = false;
    ImGui::Separator();
    {
        auto opts = get_config_options({"hollowing_enable"});
        m_enable_hollowing = static_cast<const ConfigOptionBool*>(opts[0].first)->value;
        if (m_imgui->checkbox(m_desc["enable"], m_enable_hollowing)) {
            mo->config.set("hollowing_enable", m_enable_hollowing);
            wxGetApp().obj_list()->update_and_show_object_settings_item();
            config_changed = true;
        }
    }
    m_imgui->disabled_end();
    m_imgui->disabled_begin(!is_input_enabled() || !m_enable_hollowing);
    ImGui::AlignTextToFramePadding();
    m_imgui->text(m_desc.at("offset"));
    ImGui::SameLine(settings_sliders_left, m_imgui->get_item_spacing().x);
    ImGui::PushItemWidth(window_width - settings_sliders_left);
    m_imgui->slider_float("##offset", &offset, offset_min, offset_max, "%.1f mm", 1.0f, true, _L(opts[0].second->tooltip));
    bool slider_clicked = m_imgui->get_last_slider_status().clicked; // someone clicked the slider
    bool slider_edited =m_imgui->get_last_slider_status().edited; // someone is dragging the slider
    bool slider_released =m_imgui->get_last_slider_status().deactivated_after_edit; // someone has just released the slider
    if (current_mode >= quality_mode) {
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("quality"));
        ImGui::SameLine(settings_sliders_left, m_imgui->get_item_spacing().x);
        m_imgui->slider_float("##quality", &quality, quality_min, quality_max, "%.1f", 1.0f, true, _L(opts[1].second->tooltip));
        slider_clicked |= m_imgui->get_last_slider_status().clicked;
        slider_edited |= m_imgui->get_last_slider_status().edited;
        slider_released |= m_imgui->get_last_slider_status().deactivated_after_edit;
    }
    if (current_mode >= closing_d_mode) {
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("closing_distance"));
        ImGui::SameLine(settings_sliders_left, m_imgui->get_item_spacing().x);
        m_imgui->slider_float("##closing_distance", &closing_d, closing_d_min, closing_d_max, "%.1f mm", 1.0f, true, _L(opts[2].second->tooltip));
        slider_clicked |= m_imgui->get_last_slider_status().clicked;
        slider_edited |= m_imgui->get_last_slider_status().edited;
        slider_released |= m_imgui->get_last_slider_status().deactivated_after_edit;
    }
    if (slider_clicked) {
        m_offset_stash = offset;
        m_quality_stash = quality;
        m_closing_d_stash = closing_d;
    }
    if (slider_edited || slider_released) {
        if (slider_released) {
            mo->config.set("hollowing_min_thickness", m_offset_stash);
            mo->config.set("hollowing_quality", m_quality_stash);
            mo->config.set("hollowing_closing_distance", m_closing_d_stash);
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Hollowing parameter change"));
        }
        mo->config.set("hollowing_min_thickness", offset);
        mo->config.set("hollowing_quality", quality);
        mo->config.set("hollowing_closing_distance", closing_d);
        if (slider_released) {
            wxGetApp().obj_list()->update_and_show_object_settings_item();
            config_changed = true;
        }
    }
    m_imgui->disabled_end();
    bool force_refresh = false;
    bool remove_selected = false;
    bool remove_all = false;
    ImGui::Separator();
    float diameter_upper_cap = 60.;
    if (m_new_hole_radius * 2.f > diameter_upper_cap)
        m_new_hole_radius = diameter_upper_cap / 2.f;
    ImGui::AlignTextToFramePadding();
    m_imgui->disabled_begin(!is_input_enabled());
    m_imgui->text(m_desc.at("hole_diameter"));
    ImGui::SameLine(diameter_slider_left, m_imgui->get_item_spacing().x);
    ImGui::PushItemWidth(window_width - diameter_slider_left);
    float diam = 2.f * m_new_hole_radius;
    m_imgui->slider_float("##hole_diameter", &diam, 1.f, 25.f, "%.1f mm", 1.f, false);
    // Let's clamp the value (which could have been entered by keyboard) to a larger range
    // than the slider. This allows entering off-scale values and still protects against
    //complete non-sense.
    diam = std::clamp(diam, 0.1f, diameter_upper_cap);
    m_new_hole_radius = diam / 2.f;
    bool clicked = m_imgui->get_last_slider_status().clicked;
    bool edited = m_imgui->get_last_slider_status().edited;
    bool deactivated = m_imgui->get_last_slider_status().deactivated_after_edit;
    ImGui::AlignTextToFramePadding();
    m_imgui->text(m_desc["hole_depth"]);
    ImGui::SameLine(diameter_slider_left, m_imgui->get_item_spacing().x);
    m_imgui->slider_float("##hole_depth", &m_new_hole_height, 0.f, 10.f, "%.1f mm", 1.f, false);
    m_imgui->disabled_end();
    // Same as above:
    m_new_hole_height = std::clamp(m_new_hole_height, 0.f, 100.f);
    clicked |= m_imgui->get_last_slider_status().clicked;
    edited |= m_imgui->get_last_slider_status().edited;
    deactivated |= m_imgui->get_last_slider_status().deactivated_after_edit;;
    // Following is a nasty way to:
    //  - save the initial value of the slider before one starts messing with it
    //  - keep updating the head radius during sliding so it is continuosly refreshed in 3D scene
    //  - take correct undo/redo snapshot after the user is done with moving the slider
    if (! m_selection_empty) {
        if (clicked) {
            m_holes_stash = mo->sla_drain_holes;
        }
        if (edited) {
            for (size_t idx=0; idx<m_selected.size(); ++idx)
                if (m_selected[idx]) {
                    mo->sla_drain_holes[idx].radius = m_new_hole_radius;
                    mo->sla_drain_holes[idx].height = m_new_hole_height;
                }
        }
        if (deactivated) {
            // momentarily restore the old value to take snapshot
            sla::DrainHoles new_holes = mo->sla_drain_holes;
            mo->sla_drain_holes = m_holes_stash;
            float backup_rad = m_new_hole_radius;
            float backup_hei = m_new_hole_height;
            for (size_t i=0; i<m_holes_stash.size(); ++i) {
                if (m_selected[i]) {
                    m_new_hole_radius = m_holes_stash[i].radius;
                    m_new_hole_height = m_holes_stash[i].height;
                    break;
                }
            }
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Change drainage hole diameter"));
            m_new_hole_radius = backup_rad;
            m_new_hole_height = backup_hei;
            mo->sla_drain_holes = new_holes;
        }
    }
    m_imgui->disabled_begin(!is_input_enabled() || m_selection_empty);
    remove_selected = m_imgui->button(m_desc.at("remove_selected"));
    m_imgui->disabled_end();
    m_imgui->disabled_begin(!is_input_enabled() || mo->sla_drain_holes.empty());
    remove_all = m_imgui->button(m_desc.at("remove_all"));
    m_imgui->disabled_end();
    // Following is rendered in both editing and non-editing mode:
    ImGui::Separator();
    m_imgui->disabled_begin(!is_input_enabled());
    if (m_c->object_clipper()->get_position() == 0.f) {
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("clipping_of_view"));
    }
    else {
        if (m_imgui->button(m_desc.at("reset_direction"))) {
            wxGetApp().CallAfter([this](){
                    m_c->object_clipper()->set_position_by_ratio(-1., false);
                });
        }
    }
    ImGui::SameLine(settings_sliders_left, m_imgui->get_item_spacing().x);
    ImGui::PushItemWidth(window_width - settings_sliders_left);
    float clp_dist = m_c->object_clipper()->get_position();
    if (m_imgui->slider_float("##clp_dist", &clp_dist, 0.f, 1.f, "%.2f"))
        m_c->object_clipper()->set_position_by_ratio(clp_dist, true);
    // make sure supports are shown/hidden as appropriate
    ImGui::Separator();
    bool show_sups = are_sla_supports_shown();
    if (m_imgui->checkbox(m_desc["show_supports"], show_sups)) {
        show_sla_supports(show_sups);
        force_refresh = true;
    }
    m_imgui->disabled_end();
    m_imgui->end();
    if (remove_selected || remove_all) {
        force_refresh = false;
        m_parent.set_as_dirty();
        if (remove_all) {
            select_point(AllPoints);
            delete_selected_points();
        }
        if (remove_selected)
            delete_selected_points();
        if (first_run) {
            first_run = false;
            goto RENDER_AGAIN;
        }
    }
    if (force_refresh)
        m_parent.set_as_dirty();
    if (config_changed)
        m_parent.post_event(SimpleEvent(EVT_GLCANVAS_FORCE_UPDATE));
}
References _, _L, ImGui::AlignTextToFramePadding(), AllPoints, Slic3r::GUI::GLGizmoSlaBase::are_sla_supports_shown(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::calc_button_size(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::GUI::ImGuiWrapper::checkbox(), Slic3r::GUI::ImGuiWrapper::LastSliderStatus::clicked, Slic3r::ModelObject::config, Slic3r::GUI::ImGuiWrapper::LastSliderStatus::deactivated_after_edit, delete_selected_points(), Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), Slic3r::GUI::ImGuiWrapper::LastSliderStatus::edited, Slic3r::GUI::ImGuiWrapper::end(), get_config_options(), Slic3r::GUI::ImGuiWrapper::get_item_spacing(), Slic3r::GUI::ImGuiWrapper::get_last_slider_status(), Slic3r::GUI::GLGizmoBase::get_name(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), ImGuiCond_Always, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, Slic3r::GUI::GLGizmoSlaBase::is_input_enabled(), Slic3r::GUI::GLGizmoBase::m_c, m_closing_d_stash, m_desc, m_enable_hollowing, m_holes_stash, Slic3r::GUI::GLGizmoBase::m_imgui, m_new_hole_height, m_new_hole_radius, m_offset_stash, Slic3r::GUI::GLGizmoBase::m_parent, m_quality_stash, m_selected, m_selection_empty, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::offset(), Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::post_event(), ImGui::PushItemWidth(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::scaled(), select_point(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), ImGui::Separator(), Slic3r::ModelConfig::set(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position_by_ratio(), Slic3r::GUI::GLGizmoSlaBase::show_sla_supports(), Slic3r::ModelObject::sla_drain_holes, Slic3r::slaposDrillHoles, Slic3r::GUI::ImGuiWrapper::slider_float(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::ConfigOptionSingle< T >::value, and ImVec2::x.
on_save()
void Slic3r::GUI::GLGizmoHollow::on_save (cereal::BinaryOutputArchive & ar) const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar(m_new_hole_radius,
       m_new_hole_height,
       m_selected,
       m_selection_empty
    );
}
References m_new_hole_height, m_new_hole_radius, m_selected, and m_selection_empty.
on_set_hover_id()
void Slic3r::GUI::GLGizmoHollow::on_set_hover_id () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_c->selection_info()->model_object() == nullptr)
        return;
    if (int(m_c->selection_info()->model_object()->sla_drain_holes.size()) <= m_hover_id)
        m_hover_id = -1;
}
References Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
on_set_state()
void Slic3r::GUI::GLGizmoHollow::on_set_state () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_state == m_old_state)
        return;
    if (m_state == Off && m_old_state != Off) {
        // the gizmo was just turned Off
        m_parent.post_event(SimpleEvent(EVT_GLCANVAS_FORCE_UPDATE));
        m_c->instances_hider()->set_hide_full_scene(false);
        m_c->selection_info()->set_use_shift(false); // see top of on_render for details
    }
    m_old_state = m_state;
}
References Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::GLGizmoBase::m_c, m_old_state, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::Off, Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::set_hide_full_scene(), and Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::set_use_shift().
on_start_dragging()
void Slic3r::GUI::GLGizmoHollow::on_start_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_hover_id != -1) {
        select_point(NoPoints);
        select_point(m_hover_id);
        m_hole_before_drag = m_c->selection_info()->model_object()->sla_drain_holes[m_hover_id].pos;
    }
    else
        m_hole_before_drag = Vec3f::Zero();
}
References Slic3r::GUI::GLGizmoBase::m_c, m_hole_before_drag, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), NoPoints, select_point(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
on_stop_dragging()
void Slic3r::GUI::GLGizmoHollow::on_stop_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    sla::DrainHoles& drain_holes = m_c->selection_info()->model_object()->sla_drain_holes;
    if (m_hover_id != -1) {
        Vec3f backup = drain_holes[m_hover_id].pos;
        if (m_hole_before_drag != Vec3f::Zero() // some point was touched
         && backup != m_hole_before_drag) // and it was moved, not just selected
        {
            drain_holes[m_hover_id].pos = m_hole_before_drag;
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), _(L("Move drainage hole")));
            drain_holes[m_hover_id].pos = backup;
        }
    }
    m_hole_before_drag = Vec3f::Zero();
}
References _, L, Slic3r::GUI::GLGizmoBase::m_c, m_hole_before_drag, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::plater(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
on_unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoHollow::on_unregister_raycasters_for_picking () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    unregister_hole_raycasters_for_picking();
    unregister_volume_raycasters_for_picking();
}
References unregister_hole_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking().
register_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].register_raycasters_for_picking((m_group_id >= 0) ? m_group_id : i);
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking().
register_hole_raycasters_for_picking()
void Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking () private
{
    assert(m_hole_raycasters.empty());
    init_cylinder_model();
    const CommonGizmosDataObjects::SelectionInfo* info = m_c->selection_info();
    if (info != nullptr && !info->model_object()->sla_drain_holes.empty()) {
        const sla::DrainHoles& drain_holes = info->model_object()->sla_drain_holes;
        for (int i = 0; i < (int)drain_holes.size(); ++i) {
            m_hole_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, i, *m_cylinder.mesh_raycaster, Transform3d::Identity()));
        }
        update_hole_raycasters_for_picking_transform();
    }
}
References Slic3r::GUI::GLCanvas3D::add_raycaster_for_picking(), Slic3r::GUI::SceneRaycaster::Gizmo, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), init_cylinder_model(), Slic3r::GUI::GLGizmoBase::m_c, m_cylinder, m_hole_raycasters, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::PickingModel::mesh_raycaster, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::ModelObject::sla_drain_holes, and update_hole_raycasters_for_picking_transform().
Referenced by data_changed(), delete_selected_points(), gizmo_event(), and on_register_raycasters_for_picking().
register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking () inline inherited
{ register_grabbers_for_picking(); on_register_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_register_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_register_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
register_volume_raycasters_for_picking()
void Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking () protected inherited
{
    for (size_t i = 0; i < m_volumes.volumes.size(); ++i) {
        const GLVolume* v = m_volumes.volumes[i];
        if (!v->is_sla_pad() && !v->is_sla_support())
            m_volume_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, VOLUME_RAYCASTERS_BASE_ID + (int)i, *v->mesh_raycaster, v->world_matrix()));
    }
}
References Slic3r::GUI::GLCanvas3D::add_raycaster_for_picking(), Slic3r::GUI::SceneRaycaster::Gizmo, Slic3r::GLVolume::is_sla_pad(), Slic3r::GLVolume::is_sla_support(), Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoSlaBase::m_volume_raycasters, Slic3r::GUI::GLGizmoSlaBase::m_volumes, Slic3r::GLVolume::mesh_raycaster, Slic3r::GUI::VOLUME_RAYCASTERS_BASE_ID, Slic3r::GLVolumeCollection::volumes, and Slic3r::GLVolume::world_matrix().
Referenced by on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::on_register_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
reload_cache()
void Slic3r::GUI::GLGizmoHollow::reload_cache () private
{
    m_selected.clear();
    m_selected.assign(m_c->selection_info()->model_object()->sla_drain_holes.size(), false);
}
References Slic3r::GUI::GLGizmoBase::m_c, m_selected, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
Referenced by data_changed().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ on_render(); }
References Slic3r::GUI::GLGizmoBase::on_render().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_render().
render_grabbers() [1/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
}
References Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointType >::size().
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    render_grabbers(0, m_grabbers.size() - 1, size, false);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [3/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (size_t first, size_t last, float size, bool force_hover) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    glsafe(::glDisable(GL_CULL_FACE));
    for (size_t i = first; i <= last; ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(force_hover ? true : m_hover_id == (int)i, size);
    }
    glsafe(::glEnable(GL_CULL_FACE));
    shader->stop_using();
}
References glsafe, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // imgui windows that don't have an initial size needs to be processed once to get one
        // and are not rendered in the first frame
        // so, we forces to render another frame the first time the imgui window is shown
        // https://github.com/ocornut/imgui/issues/2949
        m_parent.set_as_dirty();
        m_parent.request_extra_frame();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), Slic3r::GUI::GLCanvas3D::request_extra_frame(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
render_points()
void Slic3r::GUI::GLGizmoHollow::render_points (const Selection & selection) private
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    ScopeGuard guard([shader]() { shader->stop_using(); });
    auto *inst = m_c->selection_info()->model_instance();
    if (!inst)
        return;
    double shift_z = m_c->selection_info()->print_object()->get_current_elevation();
    Transform3d trafo(inst->get_transformation().get_matrix());
    trafo.translation()(2) += shift_z;
    const Geometry::Transformation transformation{trafo};
    const Transform3d instance_scaling_matrix_inverse = transformation.get_scaling_factor_matrix().inverse();
    const Camera& camera = wxGetApp().plater()->get_camera();
    const Transform3d& view_matrix = camera.get_view_matrix();
    shader->set_uniform("projection_matrix", camera.get_projection_matrix());
    ColorRGBA render_color;
    const sla::DrainHoles& drain_holes = m_c->selection_info()->model_object()->sla_drain_holes;
    const size_t cache_size = drain_holes.size();
    for (size_t i = 0; i < cache_size; ++i) {
        const sla::DrainHole& drain_hole = drain_holes[i];
        const bool point_selected = m_selected[i];
        const bool clipped = is_mesh_point_clipped(drain_hole.pos.cast<double>());
        m_hole_raycasters[i]->set_active(!clipped);
        if (clipped)
            continue;
        // First decide about the color of the point.
        if (size_t(m_hover_id) == i)
            render_color = ColorRGBA::CYAN();
        else
            render_color = point_selected ? ColorRGBA(1.0f, 0.3f, 0.3f, 0.5f) : ColorRGBA(1.0f, 1.0f, 1.0f, 0.5f);
        m_cylinder.model.set_color(render_color);
        // Inverse matrix of the instance scaling is applied so that the mark does not scale with the object.
        const Transform3d hole_matrix = Geometry::translation_transform(drain_hole.pos.cast<double>()) * instance_scaling_matrix_inverse;
        if (transformation.is_left_handed())
            glsafe(::glFrontFace(GL_CW));
        // Matrices set, we can render the point mark now.
        Eigen::Quaterniond q;
        q.setFromTwoVectors(Vec3d::UnitZ(), instance_scaling_matrix_inverse * (-drain_hole.normal).cast<double>());
        const Eigen::AngleAxisd aa(q);
        const Transform3d model_matrix = trafo * hole_matrix * Transform3d(aa.toRotationMatrix()) *
            Geometry::translation_transform(-drain_hole.height * Vec3d::UnitZ()) * Geometry::scale_transform(Vec3d(drain_hole.radius, drain_hole.radius, drain_hole.height + sla::HoleStickOutLength));
        shader->set_uniform("view_model_matrix", view_matrix * model_matrix);
        const Matrix3d view_normal_matrix = view_matrix.matrix().block(0, 0, 3, 3) * model_matrix.matrix().block(0, 0, 3, 3).inverse().transpose();
        shader->set_uniform("view_normal_matrix", view_normal_matrix);
        m_cylinder.model.render();
        if (transformation.is_left_handed())
            glsafe(::glFrontFace(GL_CCW));
    }
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast(), Slic3r::ColorRGBA::CYAN(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), glsafe, Slic3r::sla::DrainHole::height, Slic3r::sla::HoleStickOutLength, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), is_mesh_point_clipped(), Slic3r::GUI::GLGizmoBase::m_c, m_cylinder, m_hole_raycasters, Slic3r::GUI::GLGizmoBase::m_hover_id, m_selected, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::PickingModel::model, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_instance(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::sla::DrainHole::normal, Slic3r::sla::DrainHole::pos, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), Slic3r::sla::DrainHole::radius, Slic3r::GUI::GLModel::render(), Slic3r::Geometry::scale_transform(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), Slic3r::ModelObject::sla_drain_holes, Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Eigen::AngleAxis< _Scalar >::toRotationMatrix(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation(), and Slic3r::Geometry::translation_transform().
Referenced by on_render().
render_volumes()
void Slic3r::GUI::GLGizmoSlaBase::render_volumes () protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light_clip");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.0f);
    const Camera& camera = wxGetApp().plater()->get_camera();
    ClippingPlane clipping_plane = (m_c->object_clipper()->get_position() == 0.0) ? ClippingPlane::ClipsNothing() : *m_c->object_clipper()->get_clipping_plane();
    if (m_c->object_clipper()->get_position() != 0.0)
        clipping_plane.set_normal(-clipping_plane.get_normal());
    else
        // on Linux the clipping plane does not work when using DBL_MAX
        clipping_plane.set_offset(FLT_MAX);
    m_volumes.set_clipping_plane(clipping_plane.get_data());
    for (GLVolume* v : m_volumes.volumes) {
        v->is_active = m_show_sla_supports || (!v->is_sla_pad() && !v->is_sla_support());
    }
    m_volumes.render(GLVolumeCollection::ERenderType::Opaque, true, camera.get_view_matrix(), camera.get_projection_matrix());
    shader->stop_using();
}
References Slic3r::GUI::ClippingPlane::ClipsNothing(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::GUI::ClippingPlane::get_data(), Slic3r::GUI::ClippingPlane::get_normal(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoSlaBase::m_show_sla_supports, Slic3r::GUI::GLGizmoSlaBase::m_volumes, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GLVolumeCollection::Opaque, Slic3r::GLVolumeCollection::render(), Slic3r::GLVolumeCollection::set_clipping_plane(), Slic3r::GUI::ClippingPlane::set_normal(), Slic3r::GUI::ClippingPlane::set_offset(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), and Slic3r::GLVolumeCollection::volumes.
Referenced by on_render(), and Slic3r::GUI::GLGizmoSlaSupports::on_render().
reslice_until_step()
void Slic3r::GUI::GLGizmoSlaBase::reslice_until_step (SLAPrintObjectStep step, bool postpone_error_messages = false) inherited
{
    wxGetApp().CallAfter([this, step, postpone_error_messages]() {
        if (m_c->selection_info())
            wxGetApp().plater()->reslice_SLA_until_step(step, *m_c->selection_info()->model_object(), postpone_error_messages);
        else {
            const Selection& selection = m_parent.get_selection();
            const int object_idx = selection.get_object_idx();
            if (object_idx >= 0 && !selection.is_wipe_tower())
                wxGetApp().plater()->reslice_SLA_until_step(step, *wxGetApp().plater()->model().objects[object_idx], postpone_error_messages);
        }
    });
}
References Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_wipe_tower(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::plater(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), and on_render_input_window().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
select_point()
void Slic3r::GUI::GLGizmoHollow::select_point (int i) private
{
    const sla::DrainHoles& drain_holes = m_c->selection_info()->model_object()->sla_drain_holes;
    if (i == AllPoints || i == NoPoints) {
        m_selected.assign(m_selected.size(), i == AllPoints);
        m_selection_empty = (i == NoPoints);
        if (i == AllPoints && !drain_holes.empty()) {
            m_new_hole_radius = drain_holes[0].radius;
            m_new_hole_height = drain_holes[0].height;
        }
    }
    else {
        while (size_t(i) >= m_selected.size())
            m_selected.push_back(false);
        m_selected[i] = true;
        m_selection_empty = false;
        m_new_hole_radius = drain_holes[i].radius;
        m_new_hole_height = drain_holes[i].height;
    }
}
References AllPoints, Slic3r::GUI::GLGizmoBase::m_c, m_new_hole_height, m_new_hole_radius, m_selected, m_selection_empty, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), NoPoints, Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
Referenced by delete_selected_points(), gizmo_event(), on_render_input_window(), and on_start_dragging().
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c.
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by Slic3r::GUI::GLGizmoCut3D::process_cut_line(), and Slic3r::GUI::GLGizmoSimplify::request_rerender().
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    // do not change hover id during dragging
    assert(!m_dragging);
    // allow empty grabbers when not using grabbers but use hover_id - flatten, rotate
//    if (!m_grabbers.empty() && id >= (int) m_grabbers.size())
//        return;
    m_hover_id = id;
    on_set_hover_id();
}
References Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLGizmoEmboss::on_set_state().
show_sla_supports()
void Slic3r::GUI::GLGizmoSlaBase::show_sla_supports (bool show) inline protected inherited
{ m_show_sla_supports = show; }
References Slic3r::GUI::GLGizmoSlaBase::m_show_sla_supports.
Referenced by Slic3r::GUI::GLGizmoSlaSupports::GLGizmoSlaSupports(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), and on_render_input_window().
unproject_on_mesh()
bool Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh (const Vec2d & mouse_pos, std::pair< Vec3f, Vec3f > & pos_and_normal) protected inherited
{
    if (m_c->raycaster()->raycasters().size() != 1)
        return false;
    if (!m_c->raycaster()->raycaster())
        return false;
    if (m_volumes.volumes.empty())
        return false;
    auto *inst = m_c->selection_info()->model_instance();
    if (!inst)
        return false;
    Transform3d trafo = m_volumes.volumes.front()->world_matrix();
    if (m_c->selection_info() && m_c->selection_info()->print_object()) {
        double shift_z = m_c->selection_info()->print_object()->get_current_elevation();
        trafo = inst->get_transformation().get_matrix();
        trafo.translation()(2) += shift_z;
    }
    // The raycaster query
    Vec3f hit;
    Vec3f normal;
    if (m_c->raycaster()->raycaster()->unproject_on_mesh(
        mouse_pos,
        trafo/*m_volumes.volumes.front()->world_matrix()*/,
        wxGetApp().plater()->get_camera(),
        hit,
        normal,
        m_c->object_clipper()->get_position() != 0.0 ? m_c->object_clipper()->get_clipping_plane() : nullptr)) {
        // Return both the point and the facet normal.
        pos_and_normal = std::make_pair(hit, normal);
        return true;
    }
    return false;
}
References Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoSlaBase::m_volumes, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_instance(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::plater(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycasters(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation(), Slic3r::GUI::MeshRaycaster::unproject_on_mesh(), and Slic3r::GLVolumeCollection::volumes.
Referenced by gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), on_dragging(), and Slic3r::GUI::GLGizmoSlaSupports::on_dragging().
unregister_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].unregister_raycasters_for_picking();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers.
Referenced by Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking().
unregister_hole_raycasters_for_picking()
void Slic3r::GUI::GLGizmoHollow::unregister_hole_raycasters_for_picking () private
{
    for (size_t i = 0; i < m_hole_raycasters.size(); ++i) {
        m_parent.remove_raycasters_for_picking(SceneRaycaster::EType::Gizmo, i);
    }
    m_hole_raycasters.clear();
}
References Slic3r::GUI::SceneRaycaster::Gizmo, m_hole_raycasters, Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::GUI::GLCanvas3D::remove_raycasters_for_picking().
Referenced by delete_selected_points(), gizmo_event(), and on_unregister_raycasters_for_picking().
unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking () inline inherited
{ unregister_grabbers_for_picking(); on_unregister_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
unregister_volume_raycasters_for_picking()
void Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking () protected inherited
{
    for (size_t i = 0; i < m_volume_raycasters.size(); ++i) {
        m_parent.remove_raycasters_for_picking(SceneRaycaster::EType::Gizmo, VOLUME_RAYCASTERS_BASE_ID + (int)i);
    }
    m_volume_raycasters.clear();
}
References Slic3r::GUI::SceneRaycaster::Gizmo, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoSlaBase::m_volume_raycasters, Slic3r::GUI::GLCanvas3D::remove_raycasters_for_picking(), and Slic3r::GUI::VOLUME_RAYCASTERS_BASE_ID.
Referenced by on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
unselect_point()
void Slic3r::GUI::GLGizmoHollow::unselect_point (int i) private
{
    m_selected[i] = false;
    m_selection_empty = true;
    for (const bool sel : m_selected) {
        if (sel) {
            m_selection_empty = false;
            break;
        }
    }
}
References m_selected, and m_selection_empty.
Referenced by gizmo_event().
update_hole_raycasters_for_picking_transform()
void Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform () private
{
    const CommonGizmosDataObjects::SelectionInfo* info = m_c->selection_info();
    if (info != nullptr) {
        const sla::DrainHoles& drain_holes = info->model_object()->sla_drain_holes;
        if (!drain_holes.empty()) {
            assert(!m_hole_raycasters.empty());
            const GLVolume* vol = m_parent.get_selection().get_first_volume();
            Geometry::Transformation transformation(vol->get_instance_transformation());
            auto *inst = m_c->selection_info()->model_instance();
            if (inst && m_c->selection_info() && m_c->selection_info()->print_object()) {
                double shift_z = m_c->selection_info()->print_object()->get_current_elevation();
                auto trafo = inst->get_transformation().get_matrix();
                trafo.translation()(2) += shift_z;
                transformation.set_matrix(trafo);
            }
            const Transform3d instance_scaling_matrix_inverse = transformation.get_scaling_factor_matrix().inverse();
            for (size_t i = 0; i < drain_holes.size(); ++i) {
                const sla::DrainHole& drain_hole = drain_holes[i];
                const Transform3d hole_matrix = Geometry::translation_transform(drain_hole.pos.cast<double>()) * instance_scaling_matrix_inverse;
                Eigen::Quaterniond q;
                q.setFromTwoVectors(Vec3d::UnitZ(), instance_scaling_matrix_inverse * (-drain_hole.normal).cast<double>());
                const Eigen::AngleAxisd aa(q);
                const Transform3d matrix = transformation.get_matrix() * hole_matrix * Transform3d(aa.toRotationMatrix()) *
                    Geometry::translation_transform(-drain_hole.height * Vec3d::UnitZ()) * Geometry::scale_transform(Vec3d(drain_hole.radius, drain_hole.radius, drain_hole.height + sla::HoleStickOutLength));
                m_hole_raycasters[i]->set_transform(matrix);
            }
        }
    }
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::Selection::get_first_volume(), Slic3r::GLVolume::get_instance_transformation(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_scaling_factor_matrix(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::sla::DrainHole::height, Slic3r::sla::HoleStickOutLength, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::GUI::GLGizmoBase::m_c, m_hole_raycasters, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_instance(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::sla::DrainHole::normal, Slic3r::sla::DrainHole::pos, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), Slic3r::sla::DrainHole::radius, Slic3r::Geometry::scale_transform(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::Geometry::Transformation::set_matrix(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), Slic3r::ModelObject::sla_drain_holes, Eigen::AngleAxis< _Scalar >::toRotationMatrix(), and Slic3r::Geometry::translation_transform().
Referenced by data_changed(), and register_hole_raycasters_for_picking().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
update_volumes()
void Slic3r::GUI::GLGizmoSlaBase::update_volumes () protected inherited
{
    m_volumes.clear();
    unregister_volume_raycasters_for_picking();
    const ModelObject* mo = m_c->selection_info()->model_object();
    if (mo == nullptr)
        return;
    const SLAPrintObject* po = m_c->selection_info()->print_object();
    if (po == nullptr)
        return;
    m_input_enabled = false;
    TriangleMesh backend_mesh;
    std::shared_ptr<const indexed_triangle_set> preview_mesh_ptr = po->get_mesh_to_print();
    if (preview_mesh_ptr != nullptr)
        backend_mesh = TriangleMesh(*preview_mesh_ptr);
    if (!backend_mesh.empty()) {
        auto last_comp_step = static_cast<int>(po->last_completed_step());
        if (last_comp_step == slaposCount)
            last_comp_step = -1;
        m_input_enabled = last_comp_step >= m_min_sla_print_object_step || po->model_object()->sla_points_status == sla::PointsStatus::UserModified;
        const int object_idx   = m_parent.get_selection().get_object_idx();
        const int instance_idx = m_parent.get_selection().get_instance_idx();
        const Geometry::Transformation& inst_trafo = po->model_object()->instances[instance_idx]->get_transformation();
        const double current_elevation = po->get_current_elevation();
        auto add_volume = [this, object_idx, instance_idx, &inst_trafo, current_elevation](const TriangleMesh& mesh, int volume_id, bool add_mesh_raycaster = false) {
            GLVolume* volume = m_volumes.volumes.emplace_back(new GLVolume());
            volume->model.init_from(mesh);
            volume->set_instance_transformation(inst_trafo);
            volume->set_sla_shift_z(current_elevation);
            if (add_mesh_raycaster)
                volume->mesh_raycaster = std::make_unique<GUI::MeshRaycaster>(mesh);
            if (m_input_enabled)
                volume->selected = true; // to set the proper color
            else
                volume->set_color(DISABLED_COLOR);
            volume->composite_id = GLVolume::CompositeID(object_idx, volume_id, instance_idx);
        };
        const Transform3d po_trafo_inverse = po->trafo().inverse();
        // main mesh
        backend_mesh.transform(po_trafo_inverse);
        add_volume(backend_mesh, 0, true);
        // supports mesh
        TriangleMesh supports_mesh = po->support_mesh();
        if (!supports_mesh.empty()) {
            supports_mesh.transform(po_trafo_inverse);
            add_volume(supports_mesh, -int(slaposSupportTree));
        }
        // pad mesh
        TriangleMesh pad_mesh = po->pad_mesh();
        if (!pad_mesh.empty()) {
            pad_mesh.transform(po_trafo_inverse);
            add_volume(pad_mesh, -int(slaposPad));
        }
    }
    if (m_volumes.volumes.empty()) {
        // No valid mesh found in the backend. Use the selection to duplicate the volumes
        const Selection& selection = m_parent.get_selection();
        const Selection::IndicesList& idxs = selection.get_volume_idxs();
        for (unsigned int idx : idxs) {
            const GLVolume* v = selection.get_volume(idx);
            if (!v->is_modifier) {
                m_volumes.volumes.emplace_back(new GLVolume());
                GLVolume* new_volume = m_volumes.volumes.back();
                const TriangleMesh& mesh = mo->volumes[v->volume_idx()]->mesh();
                new_volume->model.init_from(mesh);
                new_volume->set_instance_transformation(v->get_instance_transformation());
                new_volume->set_volume_transformation(v->get_volume_transformation());
                new_volume->set_sla_shift_z(v->get_sla_shift_z());
                new_volume->set_color(DISABLED_COLOR);
                new_volume->mesh_raycaster = std::make_unique<GUI::MeshRaycaster>(mesh);
            }
        }
    }
    register_volume_raycasters_for_picking();
}
References Slic3r::GLVolumeCollection::clear(), Slic3r::GUI::DISABLED_COLOR, Slic3r::TriangleMesh::empty(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GLVolume::get_instance_transformation(), Slic3r::SLAPrintObject::get_mesh_to_print(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GLVolume::get_sla_shift_z(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GLVolume::get_volume_transformation(), Slic3r::GUI::GLModel::init_from(), Slic3r::ModelObject::instances, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::last_completed_step(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoSlaBase::m_input_enabled, Slic3r::GUI::GLGizmoSlaBase::m_min_sla_print_object_step, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoSlaBase::m_volumes, Slic3r::GLVolume::mesh_raycaster, Slic3r::GLVolume::model, Slic3r::PrintObjectBase::model_object(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::SLAPrintObject::pad_mesh(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GLVolume::set_color(), Slic3r::GLVolume::set_instance_transformation(), Slic3r::GLVolume::set_sla_shift_z(), Slic3r::GLVolume::set_volume_transformation(), Slic3r::ModelObject::sla_points_status, Slic3r::slaposCount, Slic3r::slaposPad, Slic3r::slaposSupportTree, Slic3r::SLAPrintObject::support_mesh(), Slic3r::SLAPrintObject::trafo(), Slic3r::TriangleMesh::transform(), Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking(), Slic3r::sla::UserModified, Slic3r::GLVolume::volume_idx(), Slic3r::ModelObject::volumes, and Slic3r::GLVolumeCollection::volumes.
Referenced by data_changed(), and Slic3r::GUI::GLGizmoSlaSupports::data_changed().
use_grabbers()
bool Slic3r::GUI::GLGizmoBase::use_grabbers (const wxMouseEvent & mouse_event) protected inherited
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
Parameters
mouse_event Keep information about mouse click
Returns
same as on_mouse
{
    bool is_dragging_finished = false;
    if (mouse_event.Moving()) {
        // it should not happen but for sure
        assert(!m_dragging);
        if (m_dragging) is_dragging_finished = true;
        else return false;
    }
    if (mouse_event.LeftDown()) {
        Selection &selection = m_parent.get_selection();
        if (!selection.is_empty() && m_hover_id != -1 /* &&
            (m_grabbers.empty() || m_hover_id < static_cast<int>(m_grabbers.size()))*/) {
            selection.setup_cache();
            m_dragging = true;
            for (auto &grabber : m_grabbers) grabber.dragging = false;
//            if (!m_grabbers.empty() && m_hover_id < int(m_grabbers.size()))
//                m_grabbers[m_hover_id].dragging = true;
            on_start_dragging();
            // Let the plater know that the dragging started
            m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_STARTED));
            m_parent.set_as_dirty();
            return true;
        }
    } else if (m_dragging) {
        // when mouse cursor leave window than finish actual dragging operation
        bool is_leaving = mouse_event.Leaving();
        if (mouse_event.Dragging()) {
            Point      mouse_coord(mouse_event.GetX(), mouse_event.GetY());
            auto       ray = m_parent.mouse_ray(mouse_coord);
            UpdateData data(ray, mouse_coord);
            on_dragging(data);
            wxGetApp().obj_manipul()->set_dirty();
            m_parent.set_as_dirty();
            return true;
        }
        else if (mouse_event.LeftUp() || is_leaving || is_dragging_finished) {
            do_stop_dragging(is_leaving);
            return true;
        }
    }
    return false;
}
References Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_ray(), Slic3r::GUI::GLGizmoBase::on_dragging(), Slic3r::GUI::GLGizmoBase::on_start_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::Selection::setup_cache().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_mouse(), on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_mouse(), Slic3r::GUI::GLGizmoRotate::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation().
volumes()
const GLVolumeCollection & Slic3r::GUI::GLGizmoSlaBase::volumes () const inline protected inherited
{ return m_volumes; }
References Slic3r::GUI::GLGizmoSlaBase::m_volumes.
wants_enter_leave_snapshots()
virtual bool Slic3r::GUI::GLGizmoBase::wants_enter_leave_snapshots () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
Member Data Documentation
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
GRABBER_ELEMENTS_MAX_COUNT
const unsigned int Slic3r::GUI::GLGizmoBase::GRABBER_ELEMENTS_MAX_COUNT = 7 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c { nullptr } protected inherited
Referenced by Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoFdmSupports::auto_generate(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::GLGizmoCut3D::check_and_update_connectors_state(), Slic3r::GUI::GLGizmoCut3D::data_changed(), Slic3r::GUI::GLGizmoFdmSupports::data_changed(), data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), delete_selected_points(), Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoCut3D::has_valid_contour(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoCut3D::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), on_start_dragging(), on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::GLGizmoCut3D::put_connectors_on_cut_plane(), register_hole_raycasters_for_picking(), reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), Slic3r::GUI::GLGizmoCut3D::render_clipper_cut(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::GLGizmoCut3D::reset_connectors(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut3D::update_bb(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_closing_d_stash
float Slic3r::GUI::GLGizmoHollow::m_closing_d_stash = 2.f private
Referenced by on_render_input_window().
m_cylinder
PickingModel Slic3r::GUI::GLGizmoHollow::m_cylinder private
Referenced by init_cylinder_model(), register_hole_raycasters_for_picking(), and render_points().
m_desc
std::map<std::string, wxString> Slic3r::GUI::GLGizmoHollow::m_desc private
Referenced by on_init(), and on_render_input_window().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty { false } private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging { false } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::GLGizmoBase::set_hover_id(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_enable_hollowing
bool Slic3r::GUI::GLGizmoHollow::m_enable_hollowing = true private
Referenced by on_render_input_window().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render { true } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoRotate::disable_grabber(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoRotate::enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLGizmoRotate::start_dragging(), Slic3r::GUI::GLGizmoRotate::stop_dragging(), Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate::GLGizmoRotate(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), and Slic3r::GUI::GLGizmoRotate::set_group_id().
m_hole_before_drag
Vec3f Slic3r::GUI::GLGizmoHollow::m_hole_before_drag = Vec3f::Zero() private
Referenced by on_start_dragging(), and on_stop_dragging().
m_hole_raycasters
std::vector<std::shared_ptr<SceneRaycasterItem> > Slic3r::GUI::GLGizmoHollow::m_hole_raycasters private
Referenced by data_changed(), register_hole_raycasters_for_picking(), render_points(), unregister_hole_raycasters_for_picking(), and update_hole_raycasters_for_picking_transform().
m_holes_in_drilled_mesh
sla::DrainHoles Slic3r::GUI::GLGizmoHollow::m_holes_in_drilled_mesh private
m_holes_stash
sla::DrainHoles Slic3r::GUI::GLGizmoHollow::m_holes_stash private
Referenced by on_render_input_window().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id { -1 } protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_xy(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_z(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoCut3D::is_selection_changed(), Slic3r::GUI::GLGizmoCut3D::on_dragging(), on_dragging(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_dragging(), Slic3r::GUI::GLGizmoScale3D::on_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_start_dragging(), on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging(), Slic3r::GUI::GLGizmoCut3D::on_stop_dragging(), on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoBase::render_grabbers(), render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename().
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), Slic3r::GUI::GLGizmoCut3D::add_horizontal_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::add_vertical_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::adjust_window_position(), Slic3r::GUI::GLGizmoSimplify::create_gui_cfg(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_style_add_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_popup(), Slic3r::GUI::GLGizmoEmboss::draw_style_save_as_popup(), Slic3r::GUI::GLGizmoEmboss::draw_text_input(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::GLGizmoCut3D::init_input_window_data(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_build_size(), Slic3r::GUI::GLGizmoCut3D::render_combo(), Slic3r::GUI::GLGizmoCut3D::render_connectors_input_window(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoCut3D::render_double_input(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoCut3D::render_input_window_warning(), Slic3r::GUI::GLGizmoCut3D::render_move_center_input(), Slic3r::GUI::GLGizmoCut3D::render_reset_button(), Slic3r::GUI::GLGizmoCut3D::render_shortcuts(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
m_input_enabled
bool Slic3r::GUI::GLGizmoSlaBase::m_input_enabled { false } private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::is_input_enabled(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_min_sla_print_object_step
int Slic3r::GUI::GLGizmoSlaBase::m_min_sla_print_object_step { -1 } private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::get_min_sla_print_object_step(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_new_hole_height
float Slic3r::GUI::GLGizmoHollow::m_new_hole_height = 6.f private
Referenced by gizmo_event(), on_load(), on_render_input_window(), on_save(), and select_point().
m_new_hole_radius
float Slic3r::GUI::GLGizmoHollow::m_new_hole_radius = 2.f private
Referenced by gizmo_event(), on_load(), on_render_input_window(), on_save(), and select_point().
m_offset_stash
float Slic3r::GUI::GLGizmoHollow::m_offset_stash = 3.0f private
Referenced by on_render_input_window().
m_old_mo_id
ObjectID Slic3r::GUI::GLGizmoHollow::m_old_mo_id = -1 private
Referenced by data_changed().
m_old_state
EState Slic3r::GUI::GLGizmoHollow::m_old_state = Off private
Referenced by on_set_state().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::add_connector(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::GLGizmoCut3D::bounding_box(), Slic3r::GUI::GLGizmoEmboss::calculate_scale(), Slic3r::GUI::GLGizmoEmboss::close(), Slic3r::GUI::GLGizmoSimplify::close(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoFlatten::data_changed(), Slic3r::GUI::GLGizmoMeasure::data_changed(), Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoRotate3D::data_changed(), Slic3r::GUI::GLGizmoCut3D::delete_selected_connectors(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoEmboss::do_rotate(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoEmboss::do_translate(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), gizmo_event(), Slic3r::GUI::GLGizmoMeasure::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), on_is_activable(), Slic3r::GUI::GLGizmoMeasure::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoCut3D::on_load(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_shortcut_key(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoEmboss::on_stop_dragging(), Slic3r::GUI::GLGizmoMove3D::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoScale3D::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::GLGizmoEmboss::process(), Slic3r::GUI::GLGizmoSimplify::process(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_cut_line(), register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::register_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::remove_selected_sphere_raycaster(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), Slic3r::GUI::GLGizmoCut3D::reset_cut_by_contours(), Slic3r::GUI::GLGizmoCut3D::reset_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), Slic3r::GUI::GLGizmoCut3D::set_volumes_picking_state(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoCut3D::transformed_bounding_box(), unregister_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::unregister_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_quality_stash
float Slic3r::GUI::GLGizmoHollow::m_quality_stash = 0.5f private
Referenced by on_render_input_window().
m_selected
std::vector<bool> Slic3r::GUI::GLGizmoHollow::m_selected mutable private
Referenced by delete_selected_points(), gizmo_event(), on_load(), on_render_input_window(), on_save(), reload_cache(), render_points(), select_point(), and unselect_point().
m_selection_empty
bool Slic3r::GUI::GLGizmoHollow::m_selection_empty = true private
Referenced by gizmo_event(), on_load(), on_render_input_window(), on_save(), select_point(), and unselect_point().
m_selection_rectangle
GLSelectionRectangle Slic3r::GUI::GLGizmoHollow::m_selection_rectangle private
Referenced by gizmo_event(), is_selection_rectangle_dragging(), and on_render().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoCut3D::on_init(), Slic3r::GUI::GLGizmoEmboss::on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), on_init(), Slic3r::GUI::GLGizmoMeasure::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), and Slic3r::GUI::GLGizmoSlaSupports::on_init().
m_show_sla_supports
bool Slic3r::GUI::GLGizmoSlaBase::m_show_sla_supports { false } private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::are_sla_supports_shown(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), and Slic3r::GUI::GLGizmoSlaBase::show_sla_supports().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_state
EState Slic3r::GUI::GLGizmoBase::m_state protected inherited
Referenced by data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoBase::load(), Slic3r::GUI::GLGizmoCut3D::on_render(), on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), Slic3r::GUI::GLGizmoRotate3D::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoBase::set_state(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), and Slic3r::GUI::GLGizmoSimplify::worker_finished().
m_volume_raycasters
std::vector<std::shared_ptr<SceneRaycasterItem> > Slic3r::GUI::GLGizmoSlaBase::m_volume_raycasters private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking().
m_volumes
GLVolumeCollection Slic3r::GUI::GLGizmoSlaBase::m_volumes private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::GUI::GLGizmoSlaBase::volumes().
m_wait_for_up_event
bool Slic3r::GUI::GLGizmoHollow::m_wait_for_up_event = false private
Referenced by gizmo_event().
NO_SHORTCUT_KEY_VALUE
const int Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE = 0 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoHollow.hpp
src/slic3r/GUI/Gizmos/GLGizmoHollow.cpp