Prusa Slicer: Slic3r::GUI::ModelNode Class Reference
Slic3r::GUI::ModelNode Class Reference
#include <src/slic3r/GUI/UnsavedChangesDialog.hpp>
Public Member Functions
ModelNode (Preset::Type preset_type, wxWindow *parent_win, const wxString &text, const std::string &icon_name, const wxString &new_val_column_text)
ModelNode (ModelNode *parent, const wxString &text, const std::string &icon_name)
ModelNode (ModelNode *parent, const wxString &text)
ModelNode (ModelNode *parent, const wxString &text, const wxString &old_value, const wxString &mod_value, const wxString &new_value)
bool IsContainer () const
bool IsToggled () const
void Toggle (bool toggle=true)
bool IsRoot () const
Preset::Type type () const
const wxString & text () const
ModelNode * GetParent ()
ModelNodePtrArray & GetChildren ()
ModelNode * GetNthChild (unsigned int n)
unsigned int GetChildCount () const
void Append (std::unique_ptr< ModelNode > child)
void UpdateEnabling ()
void UpdateIcons ()
Public Attributes
bool m_toggle {true}
wxBitmap m_icon
wxBitmap m_old_color_bmp
wxBitmap m_mod_color_bmp
wxBitmap m_new_color_bmp
wxString m_text
wxString m_old_value
wxString m_mod_value
wxString m_new_value
bool m_container {true}
Private Member Functions
wxBitmap get_bitmap (const wxString &color)
Private Attributes
wxWindow * m_parent_win { nullptr }
ModelNode * m_parent
ModelNodePtrArray m_children
wxBitmap m_empty_bmp
Preset::Type m_preset_type {Preset::TYPE_INVALID}
std::string m_icon_name
wxString m_old_color
wxString m_mod_color
wxString m_new_color
Detailed Description
Constructor & Destructor Documentation
ModelNode() [1/4]
Slic3r::GUI::ModelNode::ModelNode (Preset::Type preset_type, wxWindow * parent_win, const wxString & text, const std::string & icon_name, const wxString & new_val_column_text)
                                                                                                                                                        :
    m_parent_win(parent_win),
    m_parent(nullptr),
    m_preset_type(preset_type),
    m_icon_name(icon_name),
    m_text(text),
    m_new_value(new_val_column_text)
{
    UpdateIcons();
}
References UpdateIcons().
ModelNode() [2/4]
Slic3r::GUI::ModelNode::ModelNode (ModelNode * parent, const wxString & text, const std::string & icon_name)
                                                                                        :
    m_parent_win(parent->m_parent_win),
    m_parent(parent),
    m_icon_name(icon_name),
    m_text(text)
{
    UpdateIcons();
}
References UpdateIcons().
ModelNode() [3/4]
Slic3r::GUI::ModelNode::ModelNode (ModelNode * parent, const wxString & text)
                                                            :
    m_parent_win(parent->m_parent_win),
    m_parent(parent),
    m_icon_name("dot_small"),
    m_text(text)
{
    UpdateIcons();
}
References UpdateIcons().
ModelNode() [4/4]
Slic3r::GUI::ModelNode::ModelNode (ModelNode * parent, const wxString & text, const wxString & old_value, const wxString & mod_value, const wxString & new_value)
                                                                                                                                             :
    m_parent_win(parent->m_parent_win),
    m_parent(parent),
    m_old_color(old_value.StartsWith("#") ? old_value : ""),
    m_mod_color(mod_value.StartsWith("#") ? mod_value : ""),
    m_new_color(new_value.StartsWith("#") ? new_value : ""),
    m_icon_name("empty"),
    m_text(text),
    m_old_value(old_value),
    m_mod_value(mod_value),
    m_new_value(new_value),
    m_container(false)
{
    // check if old/new_value is color
    if (m_old_color.IsEmpty()) {
        if (!m_mod_color.IsEmpty())
            m_old_value = _L("Undef");
    }
    else {
        m_old_color_bmp = get_bitmap(m_old_color);
        m_old_value.Clear();
    }
    if (m_mod_color.IsEmpty()) {
        if (!m_old_color.IsEmpty())
            m_mod_value = _L("Undef");
    }
    else {
        m_mod_color_bmp = get_bitmap(m_mod_color);
        m_mod_value.Clear();
    }
    if (m_new_color.IsEmpty()) {
        if (!m_old_color.IsEmpty() || !m_mod_color.IsEmpty())
            m_new_value = _L("Undef");
    }
    else {
        m_new_color_bmp = get_bitmap(m_new_color);
        m_new_value.Clear();
    }
    // "color" strings
    color_string(m_old_value, def_text_color());
    color_string(m_mod_value, orange);
    color_string(m_new_value, def_text_color());
    UpdateIcons();
}
References _L, Slic3r::GUI::color_string(), Slic3r::GUI::def_text_color(), get_bitmap(), m_mod_color, m_mod_color_bmp, m_mod_value, m_new_color, m_new_color_bmp, m_new_value, m_old_color, m_old_color_bmp, m_old_value, Slic3r::GUI::orange, and UpdateIcons().
Member Function Documentation
Append()
void Slic3r::GUI::ModelNode::Append (std::unique_ptr< ModelNode > child) inline
{ m_children.emplace_back(std::move(child)); }
References m_children.
Referenced by Slic3r::GUI::DiffModel::AddOption(), Slic3r::GUI::DiffModel::AddOptionWithGroup(), and Slic3r::GUI::DiffModel::AddOptionWithGroupAndCategory().
get_bitmap()
wxBitmap Slic3r::GUI::ModelNode::get_bitmap (const wxString & color) private
{
    wxBitmap bmp = get_solid_bmp_bundle(64, 16, into_u8(color))->GetBitmapFor(m_parent_win);
    if (!m_toggle)
        bmp = bmp.ConvertToDisabled();
#ifndef __linux__
    return bmp;
#else
    wxIcon icon;
    icon.CopyFromBitmap(bmp);
    return icon;
#endif // __linux__
}
References get_solid_bmp_bundle(), and Slic3r::GUI::into_u8().
Referenced by ModelNode(), and UpdateIcons().
GetChildCount()
unsigned int Slic3r::GUI::ModelNode::GetChildCount () const inline
{ return (unsigned int)(m_children.size()); }
References m_children.
GetChildren()
ModelNodePtrArray & Slic3r::GUI::ModelNode::GetChildren () inline
{ return m_children; }
References m_children.
Referenced by Slic3r::GUI::DiffModel::AddOption(), Slic3r::GUI::DiffModel::AddOptionWithGroup(), Slic3r::GUI::DiffModel::AddOptionWithGroupAndCategory(), Slic3r::GUI::DiffModel::Delete(), Slic3r::GUI::DiffModel::GetChildren(), Slic3r::GUI::rescale_children(), Slic3r::GUI::update_children(), and Slic3r::GUI::update_parents().
GetNthChild()
ModelNode * Slic3r::GUI::ModelNode::GetNthChild (unsigned int n) inline
{ return m_children[n].get(); }
References m_children.
GetParent()
ModelNode * Slic3r::GUI::ModelNode::GetParent () inline
{ return m_parent; }
References m_parent.
Referenced by Slic3r::GUI::DiffModel::Delete(), Slic3r::GUI::DiffModel::GetParent(), and Slic3r::GUI::update_parents().
IsContainer()
bool Slic3r::GUI::ModelNode::IsContainer () const inline
{ return m_container; }
References m_container.
Referenced by Slic3r::GUI::DiffModel::IsContainer(), Slic3r::GUI::rescale_children(), and Slic3r::GUI::update_children().
IsRoot()
bool Slic3r::GUI::ModelNode::IsRoot () const inline
{ return m_parent == nullptr; }
References m_parent.
Referenced by Slic3r::GUI::DiffModel::GetParent().
IsToggled()
bool Slic3r::GUI::ModelNode::IsToggled () const inline
{ return m_toggle; }
References m_toggle.
Referenced by Slic3r::GUI::DiffModel::IsEnabledItem(), and Slic3r::GUI::update_children().
text()
const wxString & Slic3r::GUI::ModelNode::text () const inline
{ return m_text; }
References m_text.
Toggle()
void Slic3r::GUI::ModelNode::Toggle (bool toggle = true) inline
{ m_toggle = toggle; }
References m_toggle.
Referenced by Slic3r::GUI::update_parents().
type()
Preset::Type Slic3r::GUI::ModelNode::type () const inline
{ return m_preset_type; }
References m_preset_type.
UpdateEnabling()
void Slic3r::GUI::ModelNode::UpdateEnabling ()
{
    auto change_text_color = [](wxString& str, const std::string& clr_from, const std::string& clr_to)
    {
#if defined(SUPPORTS_MARKUP) && !defined(__APPLE__)
        std::string old_val = into_u8(str);
        boost::replace_all(old_val, clr_from, clr_to);
        str = from_u8(old_val);
#endif
    };
    if (!m_toggle) {
        change_text_color(m_text,      def_text_color(), grey);
        change_text_color(m_old_value, def_text_color(), grey);
        change_text_color(m_mod_value, orange,grey);
        change_text_color(m_new_value, def_text_color(), grey);
    }
    else {
        change_text_color(m_text,      grey, def_text_color());
        change_text_color(m_old_value, grey, def_text_color());
        change_text_color(m_mod_value, grey, orange);
        change_text_color(m_new_value, grey, def_text_color());
    }
    // update icons for the colors
    UpdateIcons();
}
References Slic3r::GUI::def_text_color(), Slic3r::GUI::from_u8(), Slic3r::GUI::grey, Slic3r::GUI::into_u8(), m_mod_value, m_new_value, m_old_value, m_text, m_toggle, Slic3r::GUI::orange, and UpdateIcons().
Referenced by Slic3r::GUI::update_parents(), and Slic3r::GUI::DiffModel::UpdateItemEnabling().
UpdateIcons()
void Slic3r::GUI::ModelNode::UpdateIcons ()
{
    // update icons for the colors, if any exists
    if (!m_old_color.IsEmpty())
        m_old_color_bmp = get_bitmap(m_old_color);
    if (!m_mod_color.IsEmpty())
        m_mod_color_bmp = get_bitmap(m_mod_color);
    if (!m_new_color.IsEmpty())
        m_new_color_bmp = get_bitmap(m_new_color);
    // update main icon, if any exists
    if (m_icon_name.empty())
        return;
    wxBitmap bmp = get_bmp_bundle(m_icon_name)->GetBitmapFor(m_parent_win);
    if (!m_toggle)
        bmp = bmp.ConvertToDisabled();
#ifdef __linux__
    m_icon.CopyFromBitmap(bmp);
#else
    m_icon = bmp;
#endif //__linux__
}
References get_bitmap(), get_bmp_bundle(), m_icon, m_icon_name, m_mod_color, m_mod_color_bmp, m_new_color, m_new_color_bmp, m_old_color, m_old_color_bmp, m_parent_win, and m_toggle.
Referenced by ModelNode(), ModelNode(), ModelNode(), ModelNode(), and UpdateEnabling().
Member Data Documentation
m_children
ModelNodePtrArray Slic3r::GUI::ModelNode::m_children private
Referenced by Append(), GetChildCount(), GetChildren(), and GetNthChild().
m_container
bool Slic3r::GUI::ModelNode::m_container {true}
Referenced by IsContainer().
m_empty_bmp
wxBitmap Slic3r::GUI::ModelNode::m_empty_bmp private
m_icon
wxBitmap Slic3r::GUI::ModelNode::m_icon
Referenced by Slic3r::GUI::DiffModel::GetValue(), Slic3r::GUI::DiffModel::SetValue(), and UpdateIcons().
m_icon_name
std::string Slic3r::GUI::ModelNode::m_icon_name private
Referenced by UpdateIcons().
m_mod_color
wxString Slic3r::GUI::ModelNode::m_mod_color private
Referenced by ModelNode(), and UpdateIcons().
m_mod_color_bmp
wxBitmap Slic3r::GUI::ModelNode::m_mod_color_bmp
Referenced by ModelNode(), Slic3r::GUI::DiffModel::GetValue(), and UpdateIcons().
m_mod_value
wxString Slic3r::GUI::ModelNode::m_mod_value
Referenced by ModelNode(), Slic3r::GUI::DiffModel::GetValue(), and UpdateEnabling().
m_new_color
wxString Slic3r::GUI::ModelNode::m_new_color private
Referenced by ModelNode(), and UpdateIcons().
m_new_color_bmp
wxBitmap Slic3r::GUI::ModelNode::m_new_color_bmp
Referenced by ModelNode(), Slic3r::GUI::DiffModel::GetValue(), Slic3r::GUI::DiffModel::SetValue(), and UpdateIcons().
m_new_value
wxString Slic3r::GUI::ModelNode::m_new_value
Referenced by ModelNode(), Slic3r::GUI::DiffModel::GetValue(), Slic3r::GUI::DiffModel::SetValue(), and UpdateEnabling().
m_old_color
wxString Slic3r::GUI::ModelNode::m_old_color private
Referenced by ModelNode(), and UpdateIcons().
m_old_color_bmp
wxBitmap Slic3r::GUI::ModelNode::m_old_color_bmp
Referenced by ModelNode(), Slic3r::GUI::DiffModel::GetValue(), Slic3r::GUI::DiffModel::SetValue(), and UpdateIcons().
m_old_value
wxString Slic3r::GUI::ModelNode::m_old_value
Referenced by ModelNode(), Slic3r::GUI::DiffModel::GetValue(), Slic3r::GUI::DiffModel::SetValue(), and UpdateEnabling().
m_parent
ModelNode* Slic3r::GUI::ModelNode::m_parent private
Referenced by GetParent(), and IsRoot().
m_parent_win
wxWindow* Slic3r::GUI::ModelNode::m_parent_win { nullptr } private
Referenced by UpdateIcons().
m_preset_type
Preset::Type Slic3r::GUI::ModelNode::m_preset_type {Preset::TYPE_INVALID} private
Referenced by type().
m_text
wxString Slic3r::GUI::ModelNode::m_text
Referenced by Slic3r::GUI::DiffModel::GetValue(), Slic3r::GUI::DiffModel::SetValue(), text(), and UpdateEnabling().
m_toggle
bool Slic3r::GUI::ModelNode::m_toggle {true}
Referenced by Slic3r::GUI::DiffModel::GetValue(), IsToggled(), Slic3r::GUI::DiffModel::SetValue(), Toggle(), UpdateEnabling(), and UpdateIcons().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UnsavedChangesDialog.hpp
src/slic3r/GUI/UnsavedChangesDialog.cpp