Prusa Slicer: src/avrdude/stk500v2.h File Reference
stk500v2.h File Reference
Functions
void stk500v2_initpgm (PROGRAMMER *pgm)
void stk500hvsp_initpgm (PROGRAMMER *pgm)
void stk500pp_initpgm (PROGRAMMER *pgm)
void stk500v2_jtagmkII_initpgm (PROGRAMMER *pgm)
void stk500v2_jtag3_initpgm (PROGRAMMER *pgm)
void stk500v2_dragon_hvsp_initpgm (PROGRAMMER *pgm)
void stk500v2_dragon_isp_initpgm (PROGRAMMER *pgm)
void stk500v2_dragon_pp_initpgm (PROGRAMMER *pgm)
void stk600_initpgm (PROGRAMMER *pgm)
void stk600hvsp_initpgm (PROGRAMMER *pgm)
void stk600pp_initpgm (PROGRAMMER *pgm)
void stk500v2_setup (PROGRAMMER *pgm)
void stk500v2_teardown (PROGRAMMER *pgm)
int stk500v2_drain (PROGRAMMER *pgm, int display)
int stk500v2_getsync (PROGRAMMER *pgm)
void stk500v2_set_upload_size (PROGRAMMER *pgm, int size)
Variables
const char stk500v2_desc []
const char stk500hvsp_desc []
const char stk500pp_desc []
const char stk500v2_jtagmkII_desc []
const char stk500v2_dragon_hvsp_desc []
const char stk500v2_dragon_isp_desc []
const char stk500v2_dragon_pp_desc []
const char stk500v2_jtag3_desc []
const char stk600_desc []
const char stk600hvsp_desc []
const char stk600pp_desc []
Function Documentation
stk500hvsp_initpgm()
void stk500hvsp_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "STK500HVSP");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500hvsp_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500hvsp_disable;
  pgm->program_enable = stk500hvsp_program_enable;
  pgm->chip_erase     = stk500hvsp_chip_erase;
  pgm->open           = stk500v2_open;
  pgm->close          = stk500v2_close;
  pgm->read_byte      = stk500hvsp_read_byte;
  pgm->write_byte     = stk500hvsp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500hvsp_paged_write;
  pgm->paged_load     = stk500hvsp_paged_load;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_vtarget    = stk500v2_set_vtarget;
  pgm->set_varef      = stk500v2_set_varef;
  pgm->set_fosc       = stk500v2_set_fosc;
  pgm->set_sck_period = stk500v2_set_sck_period;
  pgm->setup          = stk500v2_setup;
  pgm->teardown       = stk500v2_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_fosc, programmer_t::set_sck_period, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, stk500hvsp_chip_erase(), stk500hvsp_disable(), stk500hvsp_initialize(), stk500hvsp_paged_load(), stk500hvsp_paged_write(), stk500hvsp_program_enable(), stk500hvsp_read_byte(), stk500hvsp_write_byte(), stk500v2_close(), stk500v2_display(), stk500v2_enable(), stk500v2_open(), stk500v2_print_parms(), stk500v2_set_fosc(), stk500v2_set_sck_period(), stk500v2_set_varef(), stk500v2_set_vtarget(), stk500v2_setup(), stk500v2_teardown(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
stk500pp_initpgm()
void stk500pp_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "STK500PP");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500pp_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500pp_disable;
  pgm->program_enable = stk500pp_program_enable;
  pgm->chip_erase     = stk500pp_chip_erase;
  pgm->open           = stk500v2_open;
  pgm->close          = stk500v2_close;
  pgm->read_byte      = stk500pp_read_byte;
  pgm->write_byte     = stk500pp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500pp_paged_write;
  pgm->paged_load     = stk500pp_paged_load;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_vtarget    = stk500v2_set_vtarget;
  pgm->set_varef      = stk500v2_set_varef;
  pgm->set_fosc       = stk500v2_set_fosc;
  pgm->set_sck_period = stk500v2_set_sck_period;
  pgm->setup          = stk500v2_setup;
  pgm->teardown       = stk500v2_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_fosc, programmer_t::set_sck_period, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, stk500pp_chip_erase(), stk500pp_disable(), stk500pp_initialize(), stk500pp_paged_load(), stk500pp_paged_write(), stk500pp_program_enable(), stk500pp_read_byte(), stk500pp_write_byte(), stk500v2_close(), stk500v2_display(), stk500v2_enable(), stk500v2_open(), stk500v2_print_parms(), stk500v2_set_fosc(), stk500v2_set_sck_period(), stk500v2_set_varef(), stk500v2_set_vtarget(), stk500v2_setup(), stk500v2_teardown(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
stk500v2_dragon_hvsp_initpgm()
void stk500v2_dragon_hvsp_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "DRAGON_HVSP");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500hvsp_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500hvsp_disable;
  pgm->program_enable = stk500hvsp_program_enable;
  pgm->chip_erase     = stk500hvsp_chip_erase;
  pgm->open           = stk500v2_dragon_hv_open;
  pgm->close          = stk500v2_jtagmkII_close;
  pgm->read_byte      = stk500hvsp_read_byte;
  pgm->write_byte     = stk500hvsp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500hvsp_paged_write;
  pgm->paged_load     = stk500hvsp_paged_load;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_vtarget    = stk500v2_set_vtarget;
  pgm->set_varef      = stk500v2_set_varef;
  pgm->set_fosc       = stk500v2_set_fosc;
  pgm->set_sck_period = stk500v2_set_sck_period_mk2;
  pgm->setup          = stk500v2_jtagmkII_setup;
  pgm->teardown       = stk500v2_jtagmkII_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_fosc, programmer_t::set_sck_period, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, stk500hvsp_chip_erase(), stk500hvsp_disable(), stk500hvsp_initialize(), stk500hvsp_paged_load(), stk500hvsp_paged_write(), stk500hvsp_program_enable(), stk500hvsp_read_byte(), stk500hvsp_write_byte(), stk500v2_display(), stk500v2_dragon_hv_open(), stk500v2_enable(), stk500v2_jtagmkII_close(), stk500v2_jtagmkII_setup(), stk500v2_jtagmkII_teardown(), stk500v2_print_parms(), stk500v2_set_fosc(), stk500v2_set_sck_period_mk2(), stk500v2_set_varef(), stk500v2_set_vtarget(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
stk500v2_dragon_isp_initpgm()
void stk500v2_dragon_isp_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "DRAGON_ISP");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500v2_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500v2_disable;
  pgm->program_enable = stk500v2_program_enable;
  pgm->chip_erase     = stk500v2_chip_erase;
  pgm->cmd            = stk500v2_cmd;
  pgm->open           = stk500v2_dragon_isp_open;
  pgm->close          = stk500v2_jtagmkII_close;
  pgm->read_byte      = stk500isp_read_byte;
  pgm->write_byte     = stk500isp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500v2_paged_write;
  pgm->paged_load     = stk500v2_paged_load;
  pgm->page_erase     = stk500v2_page_erase;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_sck_period = stk500v2_set_sck_period_mk2;
  pgm->setup          = stk500v2_jtagmkII_setup;
  pgm->teardown       = stk500v2_jtagmkII_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_sck_period, programmer_t::setup, stk500isp_read_byte(), stk500isp_write_byte(), stk500v2_chip_erase(), stk500v2_cmd(), stk500v2_disable(), stk500v2_display(), stk500v2_dragon_isp_open(), stk500v2_enable(), stk500v2_initialize(), stk500v2_jtagmkII_close(), stk500v2_jtagmkII_setup(), stk500v2_jtagmkII_teardown(), stk500v2_page_erase(), stk500v2_paged_load(), stk500v2_paged_write(), stk500v2_print_parms(), stk500v2_program_enable(), stk500v2_set_sck_period_mk2(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
stk500v2_dragon_pp_initpgm()
void stk500v2_dragon_pp_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "DRAGON_PP");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500pp_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500pp_disable;
  pgm->program_enable = stk500pp_program_enable;
  pgm->chip_erase     = stk500pp_chip_erase;
  pgm->open           = stk500v2_dragon_hv_open;
  pgm->close          = stk500v2_jtagmkII_close;
  pgm->read_byte      = stk500pp_read_byte;
  pgm->write_byte     = stk500pp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500pp_paged_write;
  pgm->paged_load     = stk500pp_paged_load;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_vtarget    = stk500v2_set_vtarget;
  pgm->set_varef      = stk500v2_set_varef;
  pgm->set_fosc       = stk500v2_set_fosc;
  pgm->set_sck_period = stk500v2_set_sck_period_mk2;
  pgm->setup          = stk500v2_jtagmkII_setup;
  pgm->teardown       = stk500v2_jtagmkII_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_fosc, programmer_t::set_sck_period, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, stk500pp_chip_erase(), stk500pp_disable(), stk500pp_initialize(), stk500pp_paged_load(), stk500pp_paged_write(), stk500pp_program_enable(), stk500pp_read_byte(), stk500pp_write_byte(), stk500v2_display(), stk500v2_dragon_hv_open(), stk500v2_enable(), stk500v2_jtagmkII_close(), stk500v2_jtagmkII_setup(), stk500v2_jtagmkII_teardown(), stk500v2_print_parms(), stk500v2_set_fosc(), stk500v2_set_sck_period_mk2(), stk500v2_set_varef(), stk500v2_set_vtarget(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
stk500v2_drain()
int stk500v2_drain (PROGRAMMER * pgm, int display)
{
  return serial_drain(&pgm->fd, display);
}
References programmer_t::fd, pgm, and serial_drain.
Referenced by stk500v2_open(), stk600_open(), and wiring_open().
stk500v2_getsync()
int stk500v2_getsync (PROGRAMMER * pgm)
{
  int tries = 0;
  unsigned char buf[1], resp[32];
  int status;
  DEBUG("STK500V2: stk500v2_getsync()\n");
  if (PDATA(pgm)->pgmtype == PGMTYPE_JTAGICE_MKII ||
      PDATA(pgm)->pgmtype == PGMTYPE_JTAGICE3)
    return 0;
retry:
  tries++;
  RETURN_IF_CANCEL();
  // send the sync command and see if we can get there
  buf[0] = CMD_SIGN_ON;
  if (stk500v2_send(pgm, buf, 1) != 0) {
    avrdude_message(MSG_INFO, "%s: stk500v2_getsync(): can't communicate with device\n", progname);
    return -1;
  }
  RETURN_IF_CANCEL();
  // try to get the response back and see where we got
  status = stk500v2_recv(pgm, resp, sizeof(resp));
  RETURN_IF_CANCEL();
  // if we got bytes returned, check to see what came back
  if (status > 0) {
    if ((resp[0] == CMD_SIGN_ON) && (resp[1] == STATUS_CMD_OK) &&
  (status > 3)) {
      // success!
      unsigned int siglen = resp[2];
      if (siglen >= strlen("STK500_2") &&
    memcmp(resp + 3, "STK500_2", strlen("STK500_2")) == 0) {
  PDATA(pgm)->pgmtype = PGMTYPE_STK500;
      } else if (siglen >= strlen("AVRISP_2") &&
     memcmp(resp + 3, "AVRISP_2", strlen("AVRISP_2")) == 0) {
  PDATA(pgm)->pgmtype = PGMTYPE_AVRISP;
      } else if (siglen >= strlen("AVRISP_MK2") &&
     memcmp(resp + 3, "AVRISP_MK2", strlen("AVRISP_MK2")) == 0) {
  PDATA(pgm)->pgmtype = PGMTYPE_AVRISP_MKII;
      } else if (siglen >= strlen("STK600") &&
    memcmp(resp + 3, "STK600", strlen("STK600")) == 0) {
  PDATA(pgm)->pgmtype = PGMTYPE_STK600;
      } else {
  resp[siglen + 3] = 0;
        avrdude_message(MSG_NOTICE, "%s: stk500v2_getsync(): got response from unknown "
                          "programmer %s, assuming STK500\n",
                          progname, resp + 3);
  PDATA(pgm)->pgmtype = PGMTYPE_STK500;
      }
      avrdude_message(MSG_DEBUG, "%s: stk500v2_getsync(): found %s programmer\n",
                        progname, pgmname[PDATA(pgm)->pgmtype]);
      return 0;
    } else {
      if (tries > RETRIES) {
        avrdude_message(MSG_INFO, "%s: stk500v2_getsync(): can't communicate with device: resp=0x%02x\n",
                        progname, resp[0]);
        return -6;
      } else
        goto retry;
    }
  // or if we got a timeout
  } else if (status == -1) {
    if (tries > RETRIES) {
      avrdude_message(MSG_INFO, "%s: stk500v2_getsync(): timeout communicating with programmer\n",
              progname);
      return -1;
    } else
      goto retry;
  // or any other error
  } else {
    if (tries > RETRIES) {
      avrdude_message(MSG_INFO, "%s: stk500v2_getsync(): error communicating with programmer: (%d)\n",
              progname,status);
    } else
      goto retry;
  }
  return 0;
}
References avrdude_message(), CMD_SIGN_ON, DEBUG, MSG_DEBUG, MSG_INFO, MSG_NOTICE, PDATA, pgm, pgmname, progname, RETRIES, RETURN_IF_CANCEL, STATUS_CMD_OK, stk500v2_recv(), and stk500v2_send().
Referenced by stk500v2_command(), stk500v2_open(), stk600_open(), and wiring_open().
stk500v2_initpgm()
void stk500v2_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "STK500V2");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500v2_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500v2_disable;
  pgm->program_enable = stk500v2_program_enable;
  pgm->chip_erase     = stk500v2_chip_erase;
  pgm->cmd            = stk500v2_cmd;
  pgm->open           = stk500v2_open;
  pgm->close          = stk500v2_close;
  pgm->read_byte      = stk500isp_read_byte;
  pgm->write_byte     = stk500isp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500v2_paged_write;
  pgm->paged_load     = stk500v2_paged_load;
  pgm->page_erase     = stk500v2_page_erase;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_vtarget    = stk500v2_set_vtarget;
  pgm->set_varef      = stk500v2_set_varef;
  pgm->set_fosc       = stk500v2_set_fosc;
  pgm->set_sck_period = stk500v2_set_sck_period;
  pgm->perform_osccal = stk500v2_perform_osccal;
  pgm->setup          = stk500v2_setup;
  pgm->teardown       = stk500v2_teardown;
  pgm->page_size      = 256;
  pgm->set_upload_size= stk500v2_set_upload_size;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, programmer_t::perform_osccal, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_fosc, programmer_t::set_sck_period, programmer_t::set_upload_size, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, stk500isp_read_byte(), stk500isp_write_byte(), stk500v2_chip_erase(), stk500v2_close(), stk500v2_cmd(), stk500v2_disable(), stk500v2_display(), stk500v2_enable(), stk500v2_initialize(), stk500v2_open(), stk500v2_page_erase(), stk500v2_paged_load(), stk500v2_paged_write(), stk500v2_perform_osccal(), stk500v2_print_parms(), stk500v2_program_enable(), stk500v2_set_fosc(), stk500v2_set_sck_period(), stk500v2_set_upload_size(), stk500v2_set_varef(), stk500v2_set_vtarget(), stk500v2_setup(), stk500v2_teardown(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
Referenced by stk500generic_open(), stk500generic_setup(), stk500generic_teardown(), and wiring_initpgm().
stk500v2_jtag3_initpgm()
void stk500v2_jtag3_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAG3_ISP");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500v2_jtag3_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500v2_jtag3_disable;
  pgm->program_enable = stk500v2_program_enable;
  pgm->chip_erase     = stk500v2_chip_erase;
  pgm->cmd            = stk500v2_jtag3_cmd;
  pgm->open           = stk500v2_jtag3_open;
  pgm->close          = stk500v2_jtag3_close;
  pgm->read_byte      = stk500isp_read_byte;
  pgm->write_byte     = stk500isp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500v2_paged_write;
  pgm->paged_load     = stk500v2_paged_load;
  pgm->page_erase     = stk500v2_page_erase;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_sck_period = stk500v2_jtag3_set_sck_period;
  pgm->perform_osccal = stk500v2_perform_osccal;
  pgm->setup          = stk500v2_jtag3_setup;
  pgm->teardown       = stk500v2_jtag3_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, programmer_t::perform_osccal, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_sck_period, programmer_t::setup, stk500isp_read_byte(), stk500isp_write_byte(), stk500v2_chip_erase(), stk500v2_display(), stk500v2_enable(), stk500v2_jtag3_close(), stk500v2_jtag3_cmd(), stk500v2_jtag3_disable(), stk500v2_jtag3_initialize(), stk500v2_jtag3_open(), stk500v2_jtag3_set_sck_period(), stk500v2_jtag3_setup(), stk500v2_jtag3_teardown(), stk500v2_page_erase(), stk500v2_paged_load(), stk500v2_paged_write(), stk500v2_perform_osccal(), stk500v2_print_parms(), stk500v2_program_enable(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
stk500v2_jtagmkII_initpgm()
void stk500v2_jtagmkII_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAGMKII_ISP");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500v2_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500v2_disable;
  pgm->program_enable = stk500v2_program_enable;
  pgm->chip_erase     = stk500v2_chip_erase;
  pgm->cmd            = stk500v2_cmd;
  pgm->open           = stk500v2_jtagmkII_open;
  pgm->close          = stk500v2_jtagmkII_close;
  pgm->read_byte      = stk500isp_read_byte;
  pgm->write_byte     = stk500isp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500v2_paged_write;
  pgm->paged_load     = stk500v2_paged_load;
  pgm->page_erase     = stk500v2_page_erase;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_sck_period = stk500v2_set_sck_period_mk2;
  pgm->perform_osccal = stk500v2_perform_osccal;
  pgm->setup          = stk500v2_jtagmkII_setup;
  pgm->teardown       = stk500v2_jtagmkII_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, programmer_t::perform_osccal, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_sck_period, programmer_t::setup, stk500isp_read_byte(), stk500isp_write_byte(), stk500v2_chip_erase(), stk500v2_cmd(), stk500v2_disable(), stk500v2_display(), stk500v2_enable(), stk500v2_initialize(), stk500v2_jtagmkII_close(), stk500v2_jtagmkII_open(), stk500v2_jtagmkII_setup(), stk500v2_jtagmkII_teardown(), stk500v2_page_erase(), stk500v2_paged_load(), stk500v2_paged_write(), stk500v2_perform_osccal(), stk500v2_print_parms(), stk500v2_program_enable(), stk500v2_set_sck_period_mk2(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
stk500v2_set_upload_size()
void stk500v2_set_upload_size (PROGRAMMER * pgm, int size)
{
  unsigned char buf[16];
  buf[0] = CMD_SET_UPLOAD_SIZE_PRUSA3D;
  buf[1] = size & 0xff;
  buf[2] = size >> 8;
  buf[3] = size >> 16;
  stk500v2_command(pgm, buf, 4, sizeof(buf));
}
References CMD_SET_UPLOAD_SIZE_PRUSA3D, pgm, and stk500v2_command().
Referenced by stk500v2_initpgm().
stk500v2_setup()
void stk500v2_setup (PROGRAMMER * pgm)
{
  if ((pgm->cookie = malloc(sizeof(struct pdata))) == 0) {
    // avrdude_message(MSG_INFO, "%s: stk500v2_setup(): Out of memory allocating private data\n",
    //                 progname);
    // exit(1);
    avrdude_oom("stk500v2_setup(): Out of memory allocating private data\n");
  }
  memset(pgm->cookie, 0, sizeof(struct pdata));
  PDATA(pgm)->command_sequence = 1;
  PDATA(pgm)->boot_start = ULONG_MAX;
}
References avrdude_oom(), programmer_t::cookie, malloc(), PDATA, and pgm.
Referenced by stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), stk600pp_initpgm(), and wiring_setup().
stk500v2_teardown()
void stk500v2_teardown (PROGRAMMER * pgm)
{
  free(pgm->cookie);
}
References programmer_t::cookie, free(), and pgm.
Referenced by stk500hvsp_initpgm(), stk500pp_initpgm(), stk500v2_initpgm(), stk600_initpgm(), stk600hvsp_initpgm(), stk600pp_initpgm(), and wiring_teardown().
stk600_initpgm()
void stk600_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "STK600");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500v2_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500v2_disable;
  pgm->program_enable = stk500v2_program_enable;
  pgm->chip_erase     = stk500v2_chip_erase;
  pgm->cmd            = stk500v2_cmd;
  pgm->open           = stk600_open;
  pgm->close          = stk500v2_close;
  pgm->read_byte      = stk500isp_read_byte;
  pgm->write_byte     = stk500isp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500v2_paged_write;
  pgm->paged_load     = stk500v2_paged_load;
  pgm->page_erase     = stk500v2_page_erase;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_vtarget    = stk600_set_vtarget;
  pgm->set_varef      = stk600_set_varef;
  pgm->set_fosc       = stk600_set_fosc;
  pgm->set_sck_period = stk600_set_sck_period;
  pgm->perform_osccal = stk500v2_perform_osccal;
  pgm->setup          = stk500v2_setup;
  pgm->teardown       = stk500v2_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, programmer_t::perform_osccal, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_fosc, programmer_t::set_sck_period, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, stk500isp_read_byte(), stk500isp_write_byte(), stk500v2_chip_erase(), stk500v2_close(), stk500v2_cmd(), stk500v2_disable(), stk500v2_display(), stk500v2_enable(), stk500v2_initialize(), stk500v2_page_erase(), stk500v2_paged_load(), stk500v2_paged_write(), stk500v2_perform_osccal(), stk500v2_print_parms(), stk500v2_program_enable(), stk500v2_setup(), stk500v2_teardown(), stk600_open(), stk600_set_fosc(), stk600_set_sck_period(), stk600_set_varef(), stk600_set_vtarget(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
stk600hvsp_initpgm()
void stk600hvsp_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "STK600HVSP");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500hvsp_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500hvsp_disable;
  pgm->program_enable = stk500hvsp_program_enable;
  pgm->chip_erase     = stk500hvsp_chip_erase;
  pgm->open           = stk600_open;
  pgm->close          = stk500v2_close;
  pgm->read_byte      = stk500hvsp_read_byte;
  pgm->write_byte     = stk500hvsp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500hvsp_paged_write;
  pgm->paged_load     = stk500hvsp_paged_load;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_vtarget    = stk600_set_vtarget;
  pgm->set_varef      = stk600_set_varef;
  pgm->set_fosc       = stk600_set_fosc;
  pgm->set_sck_period = stk600_set_sck_period;
  pgm->setup          = stk500v2_setup;
  pgm->teardown       = stk500v2_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_fosc, programmer_t::set_sck_period, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, stk500hvsp_chip_erase(), stk500hvsp_disable(), stk500hvsp_initialize(), stk500hvsp_paged_load(), stk500hvsp_paged_write(), stk500hvsp_program_enable(), stk500hvsp_read_byte(), stk500hvsp_write_byte(), stk500v2_close(), stk500v2_display(), stk500v2_enable(), stk500v2_print_parms(), stk500v2_setup(), stk500v2_teardown(), stk600_open(), stk600_set_fosc(), stk600_set_sck_period(), stk600_set_varef(), stk600_set_vtarget(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
stk600pp_initpgm()
void stk600pp_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "STK600PP");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500pp_initialize;
  pgm->display        = stk500v2_display;
  pgm->enable         = stk500v2_enable;
  pgm->disable        = stk500pp_disable;
  pgm->program_enable = stk500pp_program_enable;
  pgm->chip_erase     = stk500pp_chip_erase;
  pgm->open           = stk600_open;
  pgm->close          = stk500v2_close;
  pgm->read_byte      = stk500pp_read_byte;
  pgm->write_byte     = stk500pp_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500pp_paged_write;
  pgm->paged_load     = stk500pp_paged_load;
  pgm->print_parms    = stk500v2_print_parms;
  pgm->set_vtarget    = stk600_set_vtarget;
  pgm->set_varef      = stk600_set_varef;
  pgm->set_fosc       = stk600_set_fosc;
  pgm->set_sck_period = stk600_set_sck_period;
  pgm->setup          = stk500v2_setup;
  pgm->teardown       = stk500v2_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_fosc, programmer_t::set_sck_period, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, stk500pp_chip_erase(), stk500pp_disable(), stk500pp_initialize(), stk500pp_paged_load(), stk500pp_paged_write(), stk500pp_program_enable(), stk500pp_read_byte(), stk500pp_write_byte(), stk500v2_close(), stk500v2_display(), stk500v2_enable(), stk500v2_print_parms(), stk500v2_setup(), stk500v2_teardown(), stk600_open(), stk600_set_fosc(), stk600_set_sck_period(), stk600_set_varef(), stk600_set_vtarget(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
Variable Documentation
stk500hvsp_desc
const char stk500hvsp_desc[] extern
stk500pp_desc
const char stk500pp_desc[] extern
stk500v2_desc
const char stk500v2_desc[] extern
stk500v2_dragon_hvsp_desc
const char stk500v2_dragon_hvsp_desc[] extern
stk500v2_dragon_isp_desc
const char stk500v2_dragon_isp_desc[] extern
stk500v2_dragon_pp_desc
const char stk500v2_dragon_pp_desc[] extern
stk500v2_jtag3_desc
const char stk500v2_jtag3_desc[] extern
stk500v2_jtagmkII_desc
const char stk500v2_jtagmkII_desc[] extern
stk600_desc
const char stk600_desc[] extern
stk600hvsp_desc
const char stk600hvsp_desc[] extern
stk600pp_desc
const char stk600pp_desc[] extern