Prusa Slicer: Slic3r::GUI::SubstitutionManager Class Reference
Slic3r::GUI::SubstitutionManager Class Reference
#include <src/slic3r/GUI/Tab.hpp>
Public Member Functions
SubstitutionManager ()=default
~SubstitutionManager ()=default
void init (DynamicPrintConfig *config, wxWindow *parent, wxFlexGridSizer *grid_sizer)
void create_legend ()
void delete_substitution (int substitution_id)
void add_substitution (int substitution_id=-1, const std::string &plain_pattern=std::string(), const std::string &format=std::string(), const std::string &params=std::string(), const std::string &notes=std::string())
void update_from_config ()
void delete_all ()
void edit_substitution (int substitution_id, int opt_pos, const std::string &value)
void set_cb_edited_substitution (std::function< void()> cb_edited_substitution)
void call_ui_update ()
void set_cb_hide_delete_all_btn (std::function< void()> cb_hide_delete_all_btn)
void hide_delete_all_btn ()
bool is_empty_substitutions ()
Private Member Functions
void validate_lenth ()
bool is_compatibile_with_ui ()
bool is_valid_id (int substitution_id, const wxString &message)
Private Attributes
DynamicPrintConfig * m_config { nullptr }
wxWindow * m_parent { nullptr }
wxFlexGridSizer * m_grid_sizer { nullptr }
int m_em {10}
std::function< void()> m_cb_edited_substitution { nullptr }
std::function< void()> m_cb_hide_delete_all_btn { nullptr }
Detailed Description
Constructor & Destructor Documentation
SubstitutionManager()
Slic3r::GUI::SubstitutionManager::SubstitutionManager () default
~SubstitutionManager()
Slic3r::GUI::SubstitutionManager::~SubstitutionManager () default
Member Function Documentation
add_substitution()
void Slic3r::GUI::SubstitutionManager::add_substitution (int substitution_id = -1, const std::string & plain_pattern = std::string(), const std::string & format = std::string(), const std::string & params = std::string(), const std::string & notes = std::string())
{
    bool call_after_layout = false;
    if (substitution_id < 0) {
        if (m_grid_sizer->IsEmpty()) {
            create_legend();
            substitution_id = 0;
        }
        substitution_id = m_grid_sizer->GetEffectiveRowsCount() - 1;
        // create new substitution
        // it have to be added to config too
        std::vector<std::string>& substitutions = m_config->option<ConfigOptionStrings>("gcode_substitutions")->values;
        for (size_t i = 0; i < 4; i ++)
            substitutions.push_back(std::string());
        call_after_layout = true;
    }
    auto del_btn = new ScalableButton(m_parent, wxID_ANY, "cross");
    del_btn->Bind(wxEVT_BUTTON, [substitution_id, this](wxEvent&) {
        delete_substitution(substitution_id);
    });
    m_grid_sizer->Add(del_btn, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT | wxLEFT, int(0.5*m_em));
    auto top_sizer = new wxBoxSizer(wxHORIZONTAL);
    auto add_text_editor = [substitution_id, top_sizer, this](const wxString& value, int opt_pos, int proportion) {
        auto editor = new wxTextCtrl(m_parent, wxID_ANY, value, wxDefaultPosition, wxSize(15 * m_em, wxDefaultCoord), wxTE_PROCESS_ENTER
#ifdef _WIN32
            | wxBORDER_SIMPLE
#endif
        );
        editor->SetFont(wxGetApp().normal_font());
        wxGetApp().UpdateDarkUI(editor);
        top_sizer->Add(editor, proportion, wxALIGN_CENTER_VERTICAL | wxRIGHT, m_em);
        editor->Bind(wxEVT_TEXT_ENTER, [this, editor, substitution_id, opt_pos](wxEvent& e) {
#if !defined(__WXGTK__)
            e.Skip();
#endif // __WXGTK__
            edit_substitution(substitution_id, opt_pos, into_u8(editor->GetValue()));
        });
        editor->Bind(wxEVT_KILL_FOCUS, [this, editor, substitution_id, opt_pos](wxEvent& e) {
            e.Skip();
            edit_substitution(substitution_id, opt_pos, into_u8(editor->GetValue()));
        });
    };
    add_text_editor(from_u8(plain_pattern), 0, 3);
    add_text_editor(from_u8(format),        1, 3);
    add_text_editor(from_u8(notes),         3, 2);
    auto params_sizer = new wxBoxSizer(wxHORIZONTAL);
    bool regexp              = strchr(params.c_str(), 'r') != nullptr || strchr(params.c_str(), 'R') != nullptr;
    bool case_insensitive    = strchr(params.c_str(), 'i') != nullptr || strchr(params.c_str(), 'I') != nullptr;
    bool whole_word          = strchr(params.c_str(), 'w') != nullptr || strchr(params.c_str(), 'W') != nullptr;
    bool match_single_line   = strchr(params.c_str(), 's') != nullptr || strchr(params.c_str(), 'S') != nullptr;
    auto chb_regexp = new wxCheckBox(m_parent, wxID_ANY, _L("Regular expression"));
    chb_regexp->SetValue(regexp);
    params_sizer->Add(chb_regexp, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, m_em);
    auto chb_case_insensitive = new wxCheckBox(m_parent, wxID_ANY, _L("Case insensitive"));
    chb_case_insensitive->SetValue(case_insensitive);
    params_sizer->Add(chb_case_insensitive, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT | wxLEFT, m_em);
    auto chb_whole_word = new wxCheckBox(m_parent, wxID_ANY, _L("Whole word"));
    chb_whole_word->SetValue(whole_word);
    params_sizer->Add(chb_whole_word, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT | wxLEFT, m_em);
    auto chb_match_single_line = new wxCheckBox(m_parent, wxID_ANY, _L("Match single line"));
    chb_match_single_line->SetValue(match_single_line);
    chb_match_single_line->Show(regexp);
    params_sizer->Add(chb_match_single_line, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT | wxLEFT, m_em);
    for (wxCheckBox* chb : std::initializer_list<wxCheckBox*>{ chb_regexp, chb_case_insensitive, chb_whole_word, chb_match_single_line }) {
        chb->SetFont(wxGetApp().normal_font());
        chb->Bind(wxEVT_CHECKBOX, [this, substitution_id, chb_regexp, chb_case_insensitive, chb_whole_word, chb_match_single_line](wxCommandEvent e) {
            std::string value = std::string();
            if (chb_regexp->GetValue())
                value += "r";
            if (chb_case_insensitive->GetValue())
                value += "i";
            if (chb_whole_word->GetValue())
                value += "w";
            if (chb_match_single_line->GetValue())
                value += "s";
            chb_match_single_line->Show(chb_regexp->GetValue());
            m_grid_sizer->Layout();
            edit_substitution(substitution_id, 2, value);
        });
    }
    auto v_sizer = new wxBoxSizer(wxVERTICAL);
    v_sizer->Add(top_sizer, 1, wxEXPAND);
    v_sizer->Add(params_sizer, 1, wxEXPAND|wxTOP|wxBOTTOM, int(0.5* m_em));
    m_grid_sizer->Add(v_sizer, 1, wxEXPAND);
    if (call_after_layout) {
        m_parent->GetParent()->Layout();
        call_ui_update();
    }
}
References _L, Slic3r::format(), Slic3r::GUI::from_u8(), Slic3r::GUI::into_u8(), and wxEVT_BUTTON.
call_ui_update()
void Slic3r::GUI::SubstitutionManager::call_ui_update () inline
{
    if (m_cb_edited_substitution)
      m_cb_edited_substitution();
  }
References m_cb_edited_substitution.
create_legend()
void Slic3r::GUI::SubstitutionManager::create_legend ()
{
    if (!m_grid_sizer->IsEmpty())
        return;
    // name of the first column is empty
    m_grid_sizer->Add(new wxStaticText(m_parent, wxID_ANY, wxEmptyString));
    // Legend for another columns
    auto legend_sizer = new wxBoxSizer(wxHORIZONTAL); // "Find", "Replace", "Notes"
    legend_sizer->Add(new wxStaticText(m_parent, wxID_ANY, _L("Find")),         3, wxEXPAND);
    legend_sizer->Add(new wxStaticText(m_parent, wxID_ANY, _L("Replace with")), 3, wxEXPAND);
    legend_sizer->Add(new wxStaticText(m_parent, wxID_ANY, _L("Notes")),      2, wxEXPAND);
    m_grid_sizer->Add(legend_sizer, 1, wxEXPAND);
}
References _L.
delete_all()
void Slic3r::GUI::SubstitutionManager::delete_all ()
{
    m_config->option<ConfigOptionStrings>("gcode_substitutions")->values.clear();
    call_ui_update();
    if (!m_grid_sizer->IsEmpty())
        m_grid_sizer->Clear(true);
    m_parent->GetParent()->Layout();
}
References Slic3r::ConfigOptionVector< T >::clear().
delete_substitution()
void Slic3r::GUI::SubstitutionManager::delete_substitution (int substitution_id)
{
    validate_lenth();
    if (!is_valid_id(substitution_id, "Invalid substitution_id to delete"))
        return;
    // delete substitution
    std::vector<std::string>& substitutions = m_config->option<ConfigOptionStrings>("gcode_substitutions")->values;
    substitutions.erase(std::next(substitutions.begin(), substitution_id * 4), std::next(substitutions.begin(), substitution_id * 4 + 4));
    call_ui_update();
    // update grid_sizer
    update_from_config();
}
edit_substitution()
void Slic3r::GUI::SubstitutionManager::edit_substitution (int substitution_id, int opt_pos, const std::string & value)
{
    std::vector<std::string>& substitutions = m_config->option<ConfigOptionStrings>("gcode_substitutions")->values;
    validate_lenth();
    if(!is_compatibile_with_ui() || !is_valid_id(substitution_id, "Invalid substitution_id to edit"))
        return;
    substitutions[substitution_id * 4 + opt_pos] = value;
    call_ui_update();
}
hide_delete_all_btn()
void Slic3r::GUI::SubstitutionManager::hide_delete_all_btn () inline
{
    if (m_cb_hide_delete_all_btn)
      m_cb_hide_delete_all_btn();
  }
References m_cb_hide_delete_all_btn.
init()
void Slic3r::GUI::SubstitutionManager::init (DynamicPrintConfig * config, wxWindow * parent, wxFlexGridSizer * grid_sizer)
{
    m_config = config;
    m_parent = parent;
    m_grid_sizer = grid_sizer;
    m_em = em_unit(parent);
}
References em_unit().
is_compatibile_with_ui()
bool Slic3r::GUI::SubstitutionManager::is_compatibile_with_ui () private
{
    const std::vector<std::string>& substitutions = m_config->option<ConfigOptionStrings>("gcode_substitutions")->values;
    if (int(substitutions.size() / 4) != m_grid_sizer->GetEffectiveRowsCount() - 1) {
        ErrorDialog(m_parent, "Invalid compatibility between UI and BE", false).ShowModal();
        return false;
    }
    return true;
};
is_empty_substitutions()
bool Slic3r::GUI::SubstitutionManager::is_empty_substitutions ()
{
    return m_config->option<ConfigOptionStrings>("gcode_substitutions")->values.empty();
}
References Slic3r::ConfigOptionVector< T >::empty().
is_valid_id()
bool Slic3r::GUI::SubstitutionManager::is_valid_id (int substitution_id, const wxString & message) private
{
    const std::vector<std::string>& substitutions = m_config->option<ConfigOptionStrings>("gcode_substitutions")->values;
    if (int(substitutions.size() / 4) < substitution_id) {
        ErrorDialog(m_parent, message, false).ShowModal();
        return false;
    }
    return true;
}
set_cb_edited_substitution()
void Slic3r::GUI::SubstitutionManager::set_cb_edited_substitution (std::function< void()> cb_edited_substitution) inline
{
    m_cb_edited_substitution = cb_edited_substitution;
  }
References m_cb_edited_substitution.
set_cb_hide_delete_all_btn()
void Slic3r::GUI::SubstitutionManager::set_cb_hide_delete_all_btn (std::function< void()> cb_hide_delete_all_btn) inline
{
    m_cb_hide_delete_all_btn = cb_hide_delete_all_btn;
  }
References m_cb_hide_delete_all_btn.
update_from_config()
void Slic3r::GUI::SubstitutionManager::update_from_config ()
{
    if (!m_grid_sizer->IsEmpty())
        m_grid_sizer->Clear(true);
    std::vector<std::string>& subst = m_config->option<ConfigOptionStrings>("gcode_substitutions")->values;
    if (subst.empty())
        hide_delete_all_btn();
    else
        create_legend();
    validate_lenth();
    int subst_id = 0;
    for (size_t i = 0; i < subst.size(); i += 4)
        add_substitution(subst_id++, subst[i], subst[i + 1], subst[i + 2], subst[i + 3]);
    m_parent->GetParent()->Layout();
}
validate_lenth()
void Slic3r::GUI::SubstitutionManager::validate_lenth () private
{
    std::vector<std::string>& substitutions = m_config->option<ConfigOptionStrings>("gcode_substitutions")->values;
    if ((substitutions.size() % 4) != 0) {
        WarningDialog(m_parent, "Value of gcode_substitutions parameter will be cut to valid length",
                                "Invalid length of gcode_substitutions parameter").ShowModal();
        substitutions.resize(substitutions.size() - (substitutions.size() % 4));
    }
}
Member Data Documentation
m_cb_edited_substitution
std::function<void()> Slic3r::GUI::SubstitutionManager::m_cb_edited_substitution { nullptr } private
Referenced by call_ui_update(), and set_cb_edited_substitution().
m_cb_hide_delete_all_btn
std::function<void()> Slic3r::GUI::SubstitutionManager::m_cb_hide_delete_all_btn { nullptr } private
Referenced by hide_delete_all_btn(), and set_cb_hide_delete_all_btn().
m_config
DynamicPrintConfig* Slic3r::GUI::SubstitutionManager::m_config { nullptr } private
m_em
int Slic3r::GUI::SubstitutionManager::m_em {10} private
m_grid_sizer
wxFlexGridSizer* Slic3r::GUI::SubstitutionManager::m_grid_sizer { nullptr } private
m_parent
wxWindow* Slic3r::GUI::SubstitutionManager::m_parent { nullptr } private
The documentation for this class was generated from the following files:
src/slic3r/GUI/Tab.hpp
src/slic3r/GUI/Tab.cpp