Prusa Slicer: Eigen::internal::scalar_max_op< LhsScalar, RhsScalar > Struct Template Reference
Eigen::internal::scalar_max_op< LhsScalar, RhsScalar > Struct Template Reference
#include <src/eigen/Eigen/src/Core/functors/BinaryFunctors.h>
Public Types
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar, scalar_max_op >::ReturnType result_type
typedef LhsScalar first_argument_type
typedef RhsScalar second_argument_type
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const result_type operator() (const LhsScalar &a, const RhsScalar &b) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Packet packetOp (const Packet &a, const Packet &b) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const result_type predux (const Packet &a) const
Detailed Description
template<typename LhsScalar, typename RhsScalar>
struct Eigen::internal::scalar_max_op< LhsScalar, RhsScalar >
Member Typedef Documentation
first_argument_type
typedef LhsScalar Eigen::internal::binary_op_base< LhsScalar , RhsScalar >::first_argument_type inherited
result_type
template<typename LhsScalar , typename RhsScalar > typedef ScalarBinaryOpTraits<LhsScalar,RhsScalar,scalar_max_op>::ReturnType Eigen::internal::scalar_max_op< LhsScalar, RhsScalar >::result_type
second_argument_type
typedef RhsScalar Eigen::internal::binary_op_base< LhsScalar , RhsScalar >::second_argument_type inherited
Member Function Documentation
operator()()
template<typename LhsScalar , typename RhsScalar > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const result_type Eigen::internal::scalar_max_op< LhsScalar, RhsScalar >::operator() (const LhsScalar & a, const RhsScalar & b) const inline
{ return numext::maxi(a, b); }
References Eigen::numext::maxi().
packetOp()
template<typename LhsScalar , typename RhsScalar > template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Packet Eigen::internal::scalar_max_op< LhsScalar, RhsScalar >::packetOp (const Packet & a, const Packet & b) const inline
  { return internal::pmax(a,b); }
References Eigen::internal::pmax().
predux()
template<typename LhsScalar , typename RhsScalar > template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const result_type Eigen::internal::scalar_max_op< LhsScalar, RhsScalar >::predux (const Packet & a) const inline
  { return internal::predux_max(a); }
References Eigen::internal::predux_max().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/functors/BinaryFunctors.h