Prusa Slicer: agg::scanline32_p8 Class Reference
agg::scanline32_p8 Class Reference
#include <src/agg/agg_scanline_p.h>
Classes
class const_iterator
struct span
Public Types
typedef scanline32_p8 self_type
typedef int8u cover_type
typedef int32 coord_type
typedef pod_bvector< span, 4 > span_array_type
Public Member Functions
scanline32_p8 ()
void reset (int min_x, int max_x)
void add_cell (int x, unsigned cover)
void add_cells (int x, unsigned len, const cover_type *covers)
void add_span (int x, unsigned len, unsigned cover)
void finalize (int y)
void reset_spans ()
int y () const
unsigned num_spans () const
const_iterator begin () const
Private Member Functions
scanline32_p8 (const self_type &)
const self_type & operator= (const self_type &)
Private Attributes
unsigned m_max_len
int m_last_x
int m_y
pod_array< cover_type > m_covers
cover_type * m_cover_ptr
span_array_type m_spans
Detailed Description
Member Typedef Documentation
coord_type
typedef int32 agg::scanline32_p8::coord_type
cover_type
typedef int8u agg::scanline32_p8::cover_type
self_type
typedef scanline32_p8 agg::scanline32_p8::self_type
span_array_type
typedef pod_bvector<span, 4> agg::scanline32_p8::span_array_type
Constructor & Destructor Documentation
scanline32_p8() [1/2]
agg::scanline32_p8::scanline32_p8 () inline
                        :
            m_max_len(0),
            m_last_x(0x7FFFFFF0),
            m_covers(),
            m_cover_ptr(0)
        {
        }
scanline32_p8() [2/2]
agg::scanline32_p8::scanline32_p8 (const self_type &) private
Member Function Documentation
add_cell()
void agg::scanline32_p8::add_cell (int x, unsigned cover) inline
        {
            *m_cover_ptr = cover_type(cover);
            if(x == m_last_x+1 && m_spans.size() && m_spans.last().len > 0)
            {
                m_spans.last().len++;
            }
            else
            {
                m_spans.add(span(coord_type(x), 1, m_cover_ptr));
            }
            m_last_x = x;
            m_cover_ptr++;
        }
References agg::pod_bvector< T, S >::add(), agg::pod_bvector< T, S >::last(), agg::scanline32_p8::span::len, m_cover_ptr, m_last_x, m_spans, and agg::pod_bvector< T, S >::size().
add_cells()
void agg::scanline32_p8::add_cells (int x, unsigned len, const cover_type * covers) inline
        {
            memcpy(m_cover_ptr, covers, len * sizeof(cover_type));
            if(x == m_last_x+1 && m_spans.size() && m_spans.last().len > 0)
            {
                m_spans.last().len += coord_type(len);
            }
            else
            {
                m_spans.add(span(coord_type(x), coord_type(len), m_cover_ptr));
            }
            m_cover_ptr += len;
            m_last_x = x + len - 1;
        }
References agg::pod_bvector< T, S >::add(), agg::pod_bvector< T, S >::last(), agg::scanline32_p8::span::len, m_cover_ptr, m_last_x, m_spans, and agg::pod_bvector< T, S >::size().
add_span()
void agg::scanline32_p8::add_span (int x, unsigned len, unsigned cover) inline
        {
            if(x == m_last_x+1 &&
               m_spans.size() &&
               m_spans.last().len < 0 &&
               cover == *m_spans.last().covers)
            {
                m_spans.last().len -= coord_type(len);
            }
            else
            {
                *m_cover_ptr = cover_type(cover);
                m_spans.add(span(coord_type(x), -coord_type(len), m_cover_ptr++));
            }
            m_last_x = x + len - 1;
        }
References agg::pod_bvector< T, S >::add(), agg::scanline32_p8::span::covers, agg::pod_bvector< T, S >::last(), agg::scanline32_p8::span::len, m_cover_ptr, m_last_x, m_spans, and agg::pod_bvector< T, S >::size().
begin()
const_iterator agg::scanline32_p8::begin () const inline
{ return const_iterator(m_spans); }
References m_spans.
finalize()
void agg::scanline32_p8::finalize (int y) inline
        {
            m_y = y;
        }
References m_y, and y().
num_spans()
unsigned agg::scanline32_p8::num_spans () const inline
{ return m_spans.size(); }
References m_spans, and agg::pod_bvector< T, S >::size().
operator=()
const self_type & agg::scanline32_p8::operator= (const self_type &) private
reset()
void agg::scanline32_p8::reset (int min_x, int max_x) inline
        {
            unsigned max_len = max_x - min_x + 3;
            if(max_len > m_covers.size())
            {
                m_covers.resize(max_len);
            }
            m_last_x    = 0x7FFFFFF0;
            m_cover_ptr = &m_covers[0];
            m_spans.remove_all();
        }
References m_cover_ptr, m_covers, m_last_x, m_spans, agg::pod_bvector< T, S >::remove_all(), agg::pod_array< T >::resize(), and agg::pod_array< T >::size().
reset_spans()
void agg::scanline32_p8::reset_spans () inline
        {
            m_last_x    = 0x7FFFFFF0;
            m_cover_ptr = &m_covers[0];
            m_spans.remove_all();
        }
References m_cover_ptr, m_covers, m_last_x, m_spans, and agg::pod_bvector< T, S >::remove_all().
y()
int agg::scanline32_p8::y () const inline
{ return m_y; }
References m_y.
Referenced by finalize().
Member Data Documentation
m_cover_ptr
cover_type* agg::scanline32_p8::m_cover_ptr private
Referenced by add_cell(), add_cells(), add_span(), reset(), and reset_spans().
m_covers
pod_array<cover_type> agg::scanline32_p8::m_covers private
Referenced by reset(), and reset_spans().
m_last_x
int agg::scanline32_p8::m_last_x private
Referenced by add_cell(), add_cells(), add_span(), reset(), and reset_spans().
m_max_len
unsigned agg::scanline32_p8::m_max_len private
m_spans
span_array_type agg::scanline32_p8::m_spans private
Referenced by add_cell(), add_cells(), add_span(), begin(), num_spans(), reset(), and reset_spans().
m_y
int agg::scanline32_p8::m_y private
Referenced by finalize(), and y().
The documentation for this class was generated from the following file:
src/agg/agg_scanline_p.h