Prusa Slicer: Eigen::LLT< _MatrixType, _UpLo > Class Template Reference
Eigen::LLT< _MatrixType, _UpLo > Class Template Reference
Standard Cholesky decomposition (LL^T) of a matrix and associated features.
#include <src/eigen/Eigen/src/Cholesky/LLT.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
enum { PacketSize = internal::packet_traits<Scalar>::size , AlignmentMask = int(PacketSize)-1 , UpLo = _UpLo }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typenameMatrixType::Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef MatrixType::StorageIndex StorageIndex
typedef internal::LLT_Traits< MatrixType, UpLo > Traits
Public Member Functions
LLT ()
Default Constructor.
LLT (Index size)
Default Constructor with memory preallocation.
template<typename InputType >
LLT (const EigenBase< InputType > &matrix)
template<typename InputType >
LLT (EigenBase< InputType > &matrix)
Constructs a LDLT factorization from a given matrix.
Traits::MatrixU matrixU () const
Traits::MatrixL matrixL () const
template<typename Rhs >
const Solve< LLT, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Derived >
void solveInPlace (const MatrixBase< Derived > &bAndX) const
template<typename InputType >
LLT & compute (const EigenBase< InputType > &matrix)
RealScalar rcond () const
const MatrixType & matrixLLT () const
MatrixType reconstructedMatrix () const
ComputationInfo info () const
Reports whether previous computation was successful.
const LLT & adjoint () const
Index rows () const
Index cols () const
template<typename VectorType >
LLT rankUpdate (const VectorType &vec, const RealScalar &sigma=1)
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename InputType >
LLT< MatrixType, _UpLo > & compute (const EigenBase< InputType > &a)
template<typename VectorType >
LLT< _MatrixType, _UpLo > rankUpdate (const VectorType &v, const RealScalar &sigma)
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_matrix
RealScalar m_l1_norm
bool m_isInitialized
ComputationInfo m_info
Detailed Description
template<typename _MatrixType, int _UpLo>
class Eigen::LLT< _MatrixType, _UpLo >
Standard Cholesky decomposition (LL^T) of a matrix and associated features.
Template Parameters
_MatrixType the type of the matrix of which we are computing the LL^T Cholesky decomposition
_UpLo the triangular part that will be used for the decompositon: Lower (default) or Upper. The other triangular part won't be read.
This class performs a LL^T Cholesky decomposition of a symmetric, positive definite matrix A such that A = LL^* = U^*U, where L is lower triangular.
While the Cholesky decomposition is particularly useful to solve selfadjoint problems like D^*D x = b, for that purpose, we recommend the Cholesky decomposition without square root which is more stable and even faster. Nevertheless, this standard Cholesky decomposition remains useful in many other situations like generalised eigen problems with hermitian matrices.
Remember that Cholesky decompositions are not rank-revealing. This LLT decomposition is only stable on positive definite matrices, use LDLT instead for the semidefinite case. Also, do not use a Cholesky decomposition to determine whether a system of equations has a solution.
Example:
Output:
Performance: for best performance, it is recommended to use a column-major storage format with the Lower triangular part (the default), or, equivalently, a row-major storage format with the Upper triangular part. Otherwise, you might get a 20% slowdown for the full factorization step, and rank-updates can be up to 3 times slower.
This class supports the inplace decomposition mechanism.
Note that during the decomposition, only the lower (or upper, as defined by _UpLo) triangular part of A is considered. Therefore, the strict lower part does not have to store correct values.
See also
MatrixBase::llt(), SelfAdjointView::llt(), class LDLT
Member Typedef Documentation
Index
template<typename _MatrixType , int _UpLo> typedef Eigen::Index Eigen::LLT< _MatrixType, _UpLo >::Index
MatrixType
template<typename _MatrixType , int _UpLo> typedef _MatrixType Eigen::LLT< _MatrixType, _UpLo >::MatrixType
RealScalar
template<typename _MatrixType , int _UpLo> typedef NumTraits<typenameMatrixType::Scalar>::Real Eigen::LLT< _MatrixType, _UpLo >::RealScalar
Scalar
template<typename _MatrixType , int _UpLo> typedef MatrixType::Scalar Eigen::LLT< _MatrixType, _UpLo >::Scalar
StorageIndex
template<typename _MatrixType , int _UpLo> typedef MatrixType::StorageIndex Eigen::LLT< _MatrixType, _UpLo >::StorageIndex
Traits
template<typename _MatrixType , int _UpLo> typedef internal::LLT_Traits<MatrixType,UpLo> Eigen::LLT< _MatrixType, _UpLo >::Traits
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType , int _UpLo> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxColsAtCompileTime
         {
      RowsAtCompileTime = MatrixType::RowsAtCompileTime,
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
anonymous enum
template<typename _MatrixType , int _UpLo> anonymous enum
Enumerator
PacketSize
AlignmentMask
UpLo
         {
      PacketSize = internal::packet_traits<Scalar>::size,
      AlignmentMask = int(PacketSize)-1,
      UpLo = _UpLo
    };
Constructor & Destructor Documentation
LLT() [1/4]
template<typename _MatrixType , int _UpLo> Eigen::LLT< _MatrixType, _UpLo >::LLT () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via LLT::compute(const MatrixType&).
: m_matrix(), m_isInitialized(false) {}
LLT() [2/4]
template<typename _MatrixType , int _UpLo> Eigen::LLT< _MatrixType, _UpLo >::LLT (Index size) inline explicit
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
LLT()
                             : m_matrix(size, size),
                    m_isInitialized(false) {}
LLT() [3/4]
template<typename _MatrixType , int _UpLo> template<typename InputType > Eigen::LLT< _MatrixType, _UpLo >::LLT (const EigenBase< InputType > & matrix) inline explicit
      : m_matrix(matrix.rows(), matrix.cols()),
        m_isInitialized(false)
    {
      compute(matrix.derived());
    }
References Eigen::LLT< _MatrixType, _UpLo >::compute(), and Eigen::EigenBase< Derived >::derived().
LLT() [4/4]
template<typename _MatrixType , int _UpLo> template<typename InputType > Eigen::LLT< _MatrixType, _UpLo >::LLT (EigenBase< InputType > & matrix) inline explicit
Constructs a LDLT factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
LLT(const EigenBase&)
      : m_matrix(matrix.derived()),
        m_isInitialized(false)
    {
      compute(matrix.derived());
    }
References Eigen::LLT< _MatrixType, _UpLo >::compute(), and Eigen::EigenBase< Derived >::derived().
Member Function Documentation
_solve_impl() [1/2]
template<typename _MatrixType , int _UpLo> template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::LLT< _MatrixType, _UpLo >::_solve_impl (const RhsType & rhs, DstType & dst) const
_solve_impl() [2/2]
template<typename _MatrixType , int _UpLo> template<typename RhsType , typename DstType > void Eigen::LLT< _MatrixType, _UpLo >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
  dst = rhs;
  solveInPlace(dst);
}
adjoint()
template<typename _MatrixType , int _UpLo> const LLT & Eigen::LLT< _MatrixType, _UpLo >::adjoint () const inline
Returns
the adjoint of *this, that is, a const reference to the decomposition itself as the underlying matrix is self-adjoint.
This method is provided for compatibility with other matrix decompositions, thus enabling generic code such as:
x = decomposition.adjoint().solve(b)
{ return *this; };
check_template_parameters()
template<typename _MatrixType , int _UpLo> static void Eigen::LLT< _MatrixType, _UpLo >::check_template_parameters () inline static protected
    {
      EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
    }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
cols()
template<typename _MatrixType , int _UpLo> Index Eigen::LLT< _MatrixType, _UpLo >::cols () const inline
{ return m_matrix.cols(); }
References Eigen::LLT< _MatrixType, _UpLo >::m_matrix.
compute() [1/2]
template<typename _MatrixType , int _UpLo> template<typename InputType > LLT< MatrixType, _UpLo > & Eigen::LLT< _MatrixType, _UpLo >::compute (const EigenBase< InputType > & a)
Computes / recomputes the Cholesky decomposition A = LL^* = U^*U of matrix
Returns
a reference to *this
Example:
Output:
{
  check_template_parameters();
  eigen_assert(a.rows()==a.cols());
  const Index size = a.rows();
  m_matrix.resize(size, size);
  if (!internal::is_same_dense(m_matrix, a.derived()))
    m_matrix = a.derived();
  // Compute matrix L1 norm = max abs column sum.
  m_l1_norm = RealScalar(0);
  // TODO move this code to SelfAdjointView
  for (Index col = 0; col < size; ++col) {
    RealScalar abs_col_sum;
    if (_UpLo == Lower)
      abs_col_sum = m_matrix.col(col).tail(size - col).template lpNorm<1>() + m_matrix.row(col).head(col).template lpNorm<1>();
    else
      abs_col_sum = m_matrix.col(col).head(col).template lpNorm<1>() + m_matrix.row(col).tail(size - col).template lpNorm<1>();
    if (abs_col_sum > m_l1_norm)
      m_l1_norm = abs_col_sum;
  }
  m_isInitialized = true;
  bool ok = Traits::inplace_decomposition(m_matrix);
  m_info = ok ? Success : NumericalIssue;
  return *this;
}
References col(), eigen_assert, Eigen::internal::is_same_dense(), Eigen::Lower, Eigen::NumericalIssue, and Eigen::Success.
compute() [2/2]
template<typename _MatrixType , int _UpLo> template<typename InputType > LLT & Eigen::LLT< _MatrixType, _UpLo >::compute (const EigenBase< InputType > & matrix)
Referenced by Eigen::LLT< _MatrixType, _UpLo >::LLT(), Eigen::LLT< _MatrixType, _UpLo >::LLT(), and igl::copyleft::quadprog().
info()
template<typename _MatrixType , int _UpLo> ComputationInfo Eigen::LLT< _MatrixType, _UpLo >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NumericalIssue if the matrix.appears not to be positive definite.
    {
      eigen_assert(m_isInitialized && "LLT is not initialized.");
      return m_info;
    }
References eigen_assert, Eigen::LLT< _MatrixType, _UpLo >::m_info, and Eigen::LLT< _MatrixType, _UpLo >::m_isInitialized.
matrixL()
template<typename _MatrixType , int _UpLo> Traits::MatrixL Eigen::LLT< _MatrixType, _UpLo >::matrixL () const inline
Returns
a view of the lower triangular matrix L
    {
      eigen_assert(m_isInitialized && "LLT is not initialized.");
      return Traits::getL(m_matrix);
    }
References eigen_assert, Eigen::LLT< _MatrixType, _UpLo >::m_isInitialized, and Eigen::LLT< _MatrixType, _UpLo >::m_matrix.
Referenced by Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::compute().
matrixLLT()
template<typename _MatrixType , int _UpLo> const MatrixType & Eigen::LLT< _MatrixType, _UpLo >::matrixLLT () const inline
Returns
the LLT decomposition matrix
TODO: document the storage layout
    {
      eigen_assert(m_isInitialized && "LLT is not initialized.");
      return m_matrix;
    }
References eigen_assert, Eigen::LLT< _MatrixType, _UpLo >::m_isInitialized, and Eigen::LLT< _MatrixType, _UpLo >::m_matrix.
matrixU()
template<typename _MatrixType , int _UpLo> Traits::MatrixU Eigen::LLT< _MatrixType, _UpLo >::matrixU () const inline
Returns
a view of the upper triangular matrix U
    {
      eigen_assert(m_isInitialized && "LLT is not initialized.");
      return Traits::getU(m_matrix);
    }
References eigen_assert, Eigen::LLT< _MatrixType, _UpLo >::m_isInitialized, and Eigen::LLT< _MatrixType, _UpLo >::m_matrix.
Referenced by Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::compute(), and igl::copyleft::quadprog().
rankUpdate() [1/2]
template<typename _MatrixType , int _UpLo> template<typename VectorType > LLT< _MatrixType, _UpLo > Eigen::LLT< _MatrixType, _UpLo >::rankUpdate (const VectorType & v, const RealScalar & sigma)
Performs a rank one update (or dowdate) of the current decomposition. If A = LL^* before the rank one update, then after it we have LL^* = A + sigma * v v^* where v must be a vector of same dimension.
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(VectorType);
  eigen_assert(v.size()==m_matrix.cols());
  eigen_assert(m_isInitialized);
  if(internal::llt_inplace<typename MatrixType::Scalar, UpLo>::rankUpdate(m_matrix,v,sigma)>=0)
    m_info = NumericalIssue;
  else
    m_info = Success;
  return *this;
}
References eigen_assert, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::NumericalIssue, and Eigen::Success.
rankUpdate() [2/2]
template<typename _MatrixType , int _UpLo> template<typename VectorType > LLT Eigen::LLT< _MatrixType, _UpLo >::rankUpdate (const VectorType & vec, const RealScalar & sigma = 1)
rcond()
template<typename _MatrixType , int _UpLo> RealScalar Eigen::LLT< _MatrixType, _UpLo >::rcond () const inline
Returns
an estimate of the reciprocal condition number of the matrix of which *this is the Cholesky decomposition.
    {
      eigen_assert(m_isInitialized && "LLT is not initialized.");
      eigen_assert(m_info == Success && "LLT failed because matrix appears to be negative");
      return internal::rcond_estimate_helper(m_l1_norm, *this);
    }
References eigen_assert, Eigen::LLT< _MatrixType, _UpLo >::m_info, Eigen::LLT< _MatrixType, _UpLo >::m_isInitialized, Eigen::LLT< _MatrixType, _UpLo >::m_l1_norm, Eigen::internal::rcond_estimate_helper(), and Eigen::Success.
reconstructedMatrix()
template<typename MatrixType , int _UpLo> MatrixType Eigen::LLT< MatrixType, _UpLo >::reconstructedMatrix
Returns
the matrix represented by the decomposition, i.e., it returns the product: L L^*. This function is provided for debug purpose.
{
  eigen_assert(m_isInitialized && "LLT is not initialized.");
  return matrixL() * matrixL().adjoint().toDenseMatrix();
}
References eigen_assert.
rows()
template<typename _MatrixType , int _UpLo> Index Eigen::LLT< _MatrixType, _UpLo >::rows () const inline
{ return m_matrix.rows(); }
References Eigen::LLT< _MatrixType, _UpLo >::m_matrix.
solve()
template<typename _MatrixType , int _UpLo> template<typename Rhs > const Solve< LLT, Rhs > Eigen::LLT< _MatrixType, _UpLo >::solve (const MatrixBase< Rhs > & b) const inline
Returns
the solution x of using the current decomposition of A.
Since this LLT class assumes anyway that the matrix A is invertible, the solution theoretically exists and is unique regardless of b.
Example:
Output:
See also
solveInPlace(), MatrixBase::llt(), SelfAdjointView::llt()
    {
      eigen_assert(m_isInitialized && "LLT is not initialized.");
      eigen_assert(m_matrix.rows()==b.rows()
                && "LLT::solve(): invalid number of rows of the right hand side matrix b");
      return Solve<LLT, Rhs>(*this, b.derived());
    }
References eigen_assert, Eigen::LLT< _MatrixType, _UpLo >::m_isInitialized, and Eigen::LLT< _MatrixType, _UpLo >::m_matrix.
Referenced by igl::copyleft::quadprog().
solveInPlace()
template<typename MatrixType , int _UpLo> template<typename Derived > void Eigen::LLT< MatrixType, _UpLo >::solveInPlace (const MatrixBase< Derived > & bAndX) const
{
  eigen_assert(m_isInitialized && "LLT is not initialized.");
  eigen_assert(m_matrix.rows()==bAndX.rows());
  matrixL().solveInPlace(bAndX);
  matrixU().solveInPlace(bAndX);
}
References eigen_assert.
Member Data Documentation
m_info
template<typename _MatrixType , int _UpLo> ComputationInfo Eigen::LLT< _MatrixType, _UpLo >::m_info protected
Referenced by Eigen::LLT< _MatrixType, _UpLo >::info(), and Eigen::LLT< _MatrixType, _UpLo >::rcond().
m_isInitialized
template<typename _MatrixType , int _UpLo> bool Eigen::LLT< _MatrixType, _UpLo >::m_isInitialized protected
Referenced by Eigen::LLT< _MatrixType, _UpLo >::info(), Eigen::LLT< _MatrixType, _UpLo >::matrixL(), Eigen::LLT< _MatrixType, _UpLo >::matrixLLT(), Eigen::LLT< _MatrixType, _UpLo >::matrixU(), Eigen::LLT< _MatrixType, _UpLo >::rcond(), and Eigen::LLT< _MatrixType, _UpLo >::solve().
m_l1_norm
template<typename _MatrixType , int _UpLo> RealScalar Eigen::LLT< _MatrixType, _UpLo >::m_l1_norm protected
Referenced by Eigen::LLT< _MatrixType, _UpLo >::rcond().
m_matrix
template<typename _MatrixType , int _UpLo> MatrixType Eigen::LLT< _MatrixType, _UpLo >::m_matrix protected
Referenced by Eigen::LLT< _MatrixType, _UpLo >::cols(), Eigen::LLT< _MatrixType, _UpLo >::matrixL(), Eigen::LLT< _MatrixType, _UpLo >::matrixLLT(), Eigen::LLT< _MatrixType, _UpLo >::matrixU(), Eigen::LLT< _MatrixType, _UpLo >::rows(), and Eigen::LLT< _MatrixType, _UpLo >::solve().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Cholesky/LLT.h