Prusa Slicer: Slic3r::GUI::GCodeViewer::Path Struct Reference
Slic3r::GUI::GCodeViewer::Path Struct Reference
Classes
struct Endpoint
struct Sub_Path
Public Member Functions
bool matches (const GCodeProcessorResult::MoveVertex &move, bool account_for_volumetric_rate) const
size_t vertices_count () const
bool contains (size_t s_id) const
int get_id_of_sub_path_containing (size_t s_id) const
void add_sub_path (const GCodeProcessorResult::MoveVertex &move, unsigned int b_id, size_t i_id, size_t s_id)
Public Attributes
EMoveType type { EMoveType::Noop }
GCodeExtrusionRole role { GCodeExtrusionRole::None }
float delta_extruder { 0.0f }
float height { 0.0f }
float width { 0.0f }
float feedrate { 0.0f }
float fan_speed { 0.0f }
float temperature { 0.0f }
float volumetric_rate { 0.0f }
unsigned char extruder_id { 0 }
unsigned char cp_color_id { 0 }
std::vector< Sub_Path > sub_paths
Detailed Description
Class Documentation
Slic3r::GUI::GCodeViewer::Path::Endpoint
struct Slic3r::GUI::GCodeViewer::Path::Endpoint
Class Members
unsigned int b_id { 0 }
size_t i_id { 0 }
Vec3f position { Vec3f::Zero() }
size_t s_id { 0 }
Member Function Documentation
add_sub_path()
void Slic3r::GUI::GCodeViewer::Path::add_sub_path (const GCodeProcessorResult::MoveVertex & move, unsigned int b_id, size_t i_id, size_t s_id) inline
{
            Endpoint endpoint = { b_id, i_id, s_id, move.position };
            sub_paths.push_back({ endpoint , endpoint });
        }
References Slic3r::GCodeProcessorResult::MoveVertex::position, and sub_paths.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
contains()
bool Slic3r::GUI::GCodeViewer::Path::contains (size_t s_id) const inline
{
            return sub_paths.empty() ? false : sub_paths.front().first.s_id <= s_id && s_id <= sub_paths.back().last.s_id;
        }
References sub_paths.
Referenced by get_id_of_sub_path_containing(), and Slic3r::GUI::GCodeViewer::refresh_render_paths().
get_id_of_sub_path_containing()
int Slic3r::GUI::GCodeViewer::Path::get_id_of_sub_path_containing (size_t s_id) const inline
{
            if (sub_paths.empty())
                return -1;
            else {
                for (int i = 0; i < static_cast<int>(sub_paths.size()); ++i) {
                    if (sub_paths[i].contains(s_id))
                        return i;
                }
                return -1;
            }
        }
References contains(), and sub_paths.
Referenced by Slic3r::GUI::GCodeViewer::refresh_render_paths().
matches()
bool Slic3r::GUI::GCodeViewer::Path::matches (const GCodeProcessorResult::MoveVertex & move, bool account_for_volumetric_rate) const
{
    auto matches_percent = [](float value1, float value2, float max_percent) {
        return std::abs(value2 - value1) / value1 <= max_percent;
    };
    switch (move.type)
    {
    case EMoveType::Tool_change:
    case EMoveType::Color_change:
    case EMoveType::Pause_Print:
    case EMoveType::Custom_GCode:
    case EMoveType::Retract:
    case EMoveType::Unretract:
    case EMoveType::Seam:
    case EMoveType::Extrude: {
        // use rounding to reduce the number of generated paths
        if (account_for_volumetric_rate)
            return type == move.type && extruder_id == move.extruder_id && cp_color_id == move.cp_color_id && role == move.extrusion_role &&
                move.position.z() <= sub_paths.front().first.position.z() && feedrate == move.feedrate && fan_speed == move.fan_speed &&
                height == round_to_bin(move.height) && width == round_to_bin(move.width) &&
                matches_percent(volumetric_rate, move.volumetric_rate(), 0.001f);
        else
            return type == move.type && extruder_id == move.extruder_id && cp_color_id == move.cp_color_id && role == move.extrusion_role &&
                move.position.z() <= sub_paths.front().first.position.z() && feedrate == move.feedrate && fan_speed == move.fan_speed &&
                height == round_to_bin(move.height) && width == round_to_bin(move.width);
    }
    case EMoveType::Travel: {
        return type == move.type && feedrate == move.feedrate && extruder_id == move.extruder_id && cp_color_id == move.cp_color_id;
    }
    default: { return false; }
    }
}
References Slic3r::Color_change, Slic3r::GCodeProcessorResult::MoveVertex::cp_color_id, Slic3r::Custom_GCode, Slic3r::Extrude, Slic3r::GCodeProcessorResult::MoveVertex::extruder_id, Slic3r::GCodeProcessorResult::MoveVertex::extrusion_role, Slic3r::GCodeProcessorResult::MoveVertex::fan_speed, Slic3r::GCodeProcessorResult::MoveVertex::feedrate, Slic3r::GCodeProcessorResult::MoveVertex::height, Slic3r::Pause_Print, Slic3r::GCodeProcessorResult::MoveVertex::position, Slic3r::Retract, Slic3r::GUI::round_to_bin(), Slic3r::Seam, Slic3r::Tool_change, Slic3r::Travel, Slic3r::GCodeProcessorResult::MoveVertex::type, Slic3r::Unretract, Slic3r::GCodeProcessorResult::MoveVertex::volumetric_rate(), and Slic3r::GCodeProcessorResult::MoveVertex::width.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
vertices_count()
size_t Slic3r::GUI::GCodeViewer::Path::vertices_count () const inline
{
            return sub_paths.empty() ? 0 : sub_paths.back().last.s_id - sub_paths.front().first.s_id + 1;
        }
References sub_paths.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
Member Data Documentation
cp_color_id
unsigned char Slic3r::GUI::GCodeViewer::Path::cp_color_id { 0 }
delta_extruder
float Slic3r::GUI::GCodeViewer::Path::delta_extruder { 0.0f }
extruder_id
unsigned char Slic3r::GUI::GCodeViewer::Path::extruder_id { 0 }
fan_speed
float Slic3r::GUI::GCodeViewer::Path::fan_speed { 0.0f }
feedrate
float Slic3r::GUI::GCodeViewer::Path::feedrate { 0.0f }
height
float Slic3r::GUI::GCodeViewer::Path::height { 0.0f }
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
role
GCodeExtrusionRole Slic3r::GUI::GCodeViewer::Path::role { GCodeExtrusionRole::None }
Referenced by Slic3r::GUI::GCodeViewer::is_visible(), and Slic3r::GUI::GCodeViewer::refresh_render_paths().
sub_paths
std::vector<Sub_Path> Slic3r::GUI::GCodeViewer::Path::sub_paths
Referenced by add_sub_path(), contains(), get_id_of_sub_path_containing(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), and vertices_count().
temperature
float Slic3r::GUI::GCodeViewer::Path::temperature { 0.0f }
type
EMoveType Slic3r::GUI::GCodeViewer::Path::type { EMoveType::Noop }
Referenced by Slic3r::GUI::GCodeViewer::refresh_render_paths().
volumetric_rate
float Slic3r::GUI::GCodeViewer::Path::volumetric_rate { 0.0f }
width
float Slic3r::GUI::GCodeViewer::Path::width { 0.0f }
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GCodeViewer.hpp
src/slic3r/GUI/GCodeViewer.cpp