Prusa Slicer: Slic3r::instance_check_internal Namespace Reference
Slic3r::instance_check_internal Namespace Reference
Classes
struct CommandLineAnalysis
Functions
static CommandLineAnalysis process_command_line (int argc, char **argv)
static bool get_lock (const std::string &name, const std::string &path)
static void delete_lockfile ()
Variables
static bool s_created_lockfile = false
Class Documentation
Slic3r::instance_check_internal::CommandLineAnalysis
struct Slic3r::instance_check_internal::CommandLineAnalysis
Class Members
string cl_string
optional< bool > should_send
Function Documentation
delete_lockfile()
static void Slic3r::instance_check_internal::delete_lockfile () static
  {
    //BOOST_LOG_TRIVIAL(debug) << "shuting down with lockfile: " << l_created_lockfile;
    if (s_created_lockfile)
    {
      std::string path = data_dir() + "/cache/" + GUI::wxGetApp().get_instance_hash_string() + ".lock";
      if( remove( path.c_str() ) != 0 )
          BOOST_LOG_TRIVIAL(error) << "Failed to delete lockfile " << path;
        //else
        //  BOOST_LOG_TRIVIAL(error) << "success delete lockfile " << path;
#ifdef __APPLE__
      // Partial fix of #7583
      // On price of incorrect working of single instances on older OSX
      if (wxPlatformInfo::Get().GetOSMajorVersion() > 12)
          send_message_mac_closing(GUI::wxGetApp().get_instance_hash_string(),GUI::wxGetApp().get_instance_hash_string());
#endif
    }
  }
References Slic3r::data_dir(), error, s_created_lockfile, and Slic3r::send_message_mac_closing().
Referenced by Slic3r::GUI::OtherInstanceMessageHandler::shutdown().
get_lock()
static bool Slic3r::instance_check_internal::get_lock (const std::string & name, const std::string & path) static
  {
    std::string dest_dir = path + name;
    BOOST_LOG_TRIVIAL(debug) <<"full lock path: "<< dest_dir;
    struct      flock fl;
    int         fdlock;
    fl.l_type = F_WRLCK;
    fl.l_whence = SEEK_SET;
    fl.l_start = 0;
    fl.l_len = 1;
        if (! boost::filesystem::is_directory(path)) {
            BOOST_LOG_TRIVIAL(debug) << "get_lock(): datadir does not exist yet, creating...";
            if (! boost::filesystem::create_directories(path))
                BOOST_LOG_TRIVIAL(debug) << "get_lock(): unable to create datadir !!!";
        }
    if ((fdlock = open(dest_dir.c_str(), O_WRONLY | O_CREAT, 0666)) == -1) {
      BOOST_LOG_TRIVIAL(debug) << "Not creating lockfile.";
      return true;
    }
    if (fcntl(fdlock, F_SETLK, &fl) == -1) {
      BOOST_LOG_TRIVIAL(debug) << "Not creating lockfile.";
      return true;
    }
    BOOST_LOG_TRIVIAL(debug) << "Creating lockfile.";
    s_created_lockfile = true;
    return false;
  }
References s_created_lockfile, and SEEK_SET.
Referenced by Slic3r::instance_check().
process_command_line()
static CommandLineAnalysis Slic3r::instance_check_internal::process_command_line (int argc, char ** argv) static
  {
    CommandLineAnalysis ret;
    //if (argc < 2)
    //  return ret;
    std::vector<std::string> arguments { argv[0] };
        for (int i = 1; i < argc; ++i) {
      const std::string token = argv[i];
      // Processing of boolean command line arguments shall match DynamicConfig::read_cli().
      if (token == "--single-instance")
        ret.should_send = true;
      else if (token == "--no-single-instance")
        ret.should_send = false;
      else
        arguments.emplace_back(token);
    }
    ret.cl_string = escape_strings_cstyle(arguments);
    BOOST_LOG_TRIVIAL(debug) << "single instance: " <<
            (ret.should_send.has_value() ? (*ret.should_send ? "true" : "false") : "undefined") <<
      ". other params: " << ret.cl_string;
    return ret;
  }
References Slic3r::instance_check_internal::CommandLineAnalysis::cl_string, Slic3r::escape_strings_cstyle(), and Slic3r::instance_check_internal::CommandLineAnalysis::should_send.
Referenced by Slic3r::instance_check().
Variable Documentation
s_created_lockfile
bool Slic3r::instance_check_internal::s_created_lockfile = false static
Referenced by delete_lockfile(), and get_lock().