Prusa Slicer: Slic3r::ExPolygon Class Reference
Slic3r::ExPolygon Class Reference
#include <src/libslic3r/ExPolygon.hpp>
Public Member Functions
ExPolygon ()=default
ExPolygon (const ExPolygon &other)=default
ExPolygon (ExPolygon &&other)=default
ExPolygon (const Polygon &contour)
ExPolygon (Polygon &&contour)
ExPolygon (const Points &contour)
ExPolygon (Points &&contour)
ExPolygon (const Polygon &contour, const Polygon &hole)
ExPolygon (Polygon &&contour, Polygon &&hole)
ExPolygon (const Points &contour, const Points &hole)
ExPolygon (Points &&contour, Polygon &&hole)
ExPolygon (std::initializer_list< Point > contour)
ExPolygon (std::initializer_list< Point > contour, std::initializer_list< Point > hole)
ExPolygon & operator= (const ExPolygon &other)=default
ExPolygon & operator= (ExPolygon &&other)=default
void clear ()
void scale (double factor)
void scale (double factor_x, double factor_y)
void translate (double x, double y)
void translate (const Point &vector)
void rotate (double angle)
void rotate (double angle, const Point &center)
double area () const
bool empty () const
bool is_valid () const
void douglas_peucker (double tolerance)
bool contains (const Line &line) const
bool contains (const Polyline &polyline) const
bool contains (const Polylines &polylines) const
bool contains (const Point &point, bool border_result=true) const
bool on_boundary (const Point &point, double eps) const
Point point_projection (const Point &point) const
bool overlaps (const ExPolygon &other) const
void simplify_p (double tolerance, Polygons *polygons) const
Polygons simplify_p (double tolerance) const
ExPolygons simplify (double tolerance) const
void simplify (double tolerance, ExPolygons *expolygons) const
void medial_axis (double min_width, double max_width, ThickPolylines *polylines) const
void medial_axis (double min_width, double max_width, Polylines *polylines) const
Polylines medial_axis (double min_width, double max_width) const
Lines lines () const
size_t num_contours () const
Polygon & contour_or_hole (size_t idx)
const Polygon & contour_or_hole (size_t idx) const
Public Attributes
Polygon contour
Polygons holes
Detailed Description
Constructor & Destructor Documentation
ExPolygon() [1/13]
Slic3r::ExPolygon::ExPolygon () default
ExPolygon() [2/13]
Slic3r::ExPolygon::ExPolygon (const ExPolygon & other) default
ExPolygon() [3/13]
Slic3r::ExPolygon::ExPolygon (ExPolygon && other) default
ExPolygon() [4/13]
Slic3r::ExPolygon::ExPolygon (const Polygon & contour) inline explicit
: contour(contour) {}
ExPolygon() [5/13]
Slic3r::ExPolygon::ExPolygon (Polygon && contour) inline explicit
: contour(std::move(contour)) {}
ExPolygon() [6/13]
Slic3r::ExPolygon::ExPolygon (const Points & contour) inline explicit
: contour(contour) {}
ExPolygon() [7/13]
Slic3r::ExPolygon::ExPolygon (Points && contour) inline explicit
: contour(std::move(contour)) {}
ExPolygon() [8/13]
Slic3r::ExPolygon::ExPolygon (const Polygon & contour, const Polygon & hole) inline explicit
: contour(contour) { holes.emplace_back(hole); }
References holes.
ExPolygon() [9/13]
Slic3r::ExPolygon::ExPolygon (Polygon && contour, Polygon && hole) inline explicit
: contour(std::move(contour)) { holes.emplace_back(std::move(hole)); }
References holes.
ExPolygon() [10/13]
Slic3r::ExPolygon::ExPolygon (const Points & contour, const Points & hole) inline explicit
: contour(contour) { holes.emplace_back(hole); }
References holes.
ExPolygon() [11/13]
Slic3r::ExPolygon::ExPolygon (Points && contour, Polygon && hole) inline explicit
: contour(std::move(contour)) { holes.emplace_back(std::move(hole)); }
References holes.
ExPolygon() [12/13]
Slic3r::ExPolygon::ExPolygon (std::initializer_list< Point > contour) inline
: contour(contour) {}
ExPolygon() [13/13]
Slic3r::ExPolygon::ExPolygon (std::initializer_list< Point > contour, std::initializer_list< Point > hole) inline
: contour(contour), holes({ hole }) {}
Member Function Documentation
area()
double Slic3r::ExPolygon::area () const
{
    double a = this->contour.area();
    for (const Polygon &hole : holes)
        a -= - hole.area();  // holes have negative area
    return a;
}
References Slic3r::Polygon::area(), contour, and holes.
Referenced by Slic3r::Surface::area(), Slic3r::area(), Slic3r::elephant_foot_compensation(), Slic3r::GUI::FillBedJob::prepare(), and Slic3r::FFFSupport::tree_supports_generate_paths().
clear()
void Slic3r::ExPolygon::clear () inline
{ contour.points.clear(); holes.clear(); }
References contour, holes, and Slic3r::MultiPoint::points.
Referenced by Slic3r::Surface::clear(), and Slic3r::FFFSupport::tree_supports_generate_paths().
contains() [1/4]
bool Slic3r::ExPolygon::contains (const Line & line) const
{
    return this->contains(Polyline(line.a, line.b));
}
References Slic3r::Line::a, Slic3r::Line::b, and contains().
Referenced by Slic3r::FillLine::_fill_surface_single(), contains(), Slic3r::GUI::MeshClipper::is_projection_inside_cut(), and overlaps().
contains() [2/4]
bool Slic3r::ExPolygon::contains (const Point & point, bool border_result = true) const
{
    if (! Slic3r::contains(contour, point, border_result))
        // Outside the outer contour, not on the contour boundary.
        return false;
    for (const Polygon &hole : this->holes)
        if (Slic3r::contains(hole, point, ! border_result))
            // Inside a hole, not on the hole boundary.
            return false;
    return true;
}
References Slic3r::contains(), contour, and holes.
contains() [3/4]
bool Slic3r::ExPolygon::contains (const Polyline & polyline) const
{
    return diff_pl(polyline, *this).empty();
}
References Slic3r::diff_pl().
contains() [4/4]
bool Slic3r::ExPolygon::contains (const Polylines & polylines) const
{
    #if 0
    BoundingBox bbox = get_extents(polylines);
    bbox.merge(get_extents(*this));
    SVG svg(debug_out_path("ExPolygon_contains.svg"), bbox);
    svg.draw(*this);
    svg.draw_outline(*this);
    svg.draw(polylines, "blue");
    #endif
    Polylines pl_out = diff_pl(polylines, *this);
    #if 0
    svg.draw(pl_out, "red");
    #endif
    return pl_out.empty();
}
References Slic3r::debug_out_path(), Slic3r::diff_pl(), Slic3r::SVG::draw(), Slic3r::SVG::draw_outline(), Slic3r::get_extents(), and Slic3r::BoundingBoxBase< PointType, APointsType >::merge().
contour_or_hole() [1/2]
Polygon & Slic3r::ExPolygon::contour_or_hole (size_t idx) inline
{ return (idx == 0) ? this->contour : this->holes[idx - 1]; }
References contour.
Referenced by Slic3r::Algorithm::expolygons_to_zpaths_expanded_opened(), point_projection(), and Slic3r::FFFSupport::tree_supports_generate_paths().
contour_or_hole() [2/2]
const Polygon & Slic3r::ExPolygon::contour_or_hole (size_t idx) const inline
{ return (idx == 0) ? this->contour : this->holes[idx - 1]; }
References contour.
douglas_peucker()
void Slic3r::ExPolygon::douglas_peucker (double tolerance)
{
    this->contour.douglas_peucker(tolerance);
    for (Polygon &poly : this->holes)
        poly.douglas_peucker(tolerance);
}
References contour, Slic3r::Polygon::douglas_peucker(), and holes.
empty()
bool Slic3r::ExPolygon::empty () const inline
{ return contour.points.empty(); }
References contour, and Slic3r::MultiPoint::points.
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::add_cavity(), Slic3r::sla::anonymous_namespace{Pad.cpp}::create_outer_pad_geometry(), Slic3r::Surface::empty(), Slic3r::GUI::Bed3D::init_contourlines(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::GUI::Bed3D::init_triangles(), overlaps(), and Slic3r::Layer::sort_perimeters_into_islands().
is_valid()
bool Slic3r::ExPolygon::is_valid () const
{
    if (!this->contour.is_valid() || !this->contour.is_counter_clockwise()) return false;
    for (Polygons::const_iterator it = this->holes.begin(); it != this->holes.end(); ++it) {
        if (!(*it).is_valid() || (*it).is_counter_clockwise()) return false;
    }
    return true;
}
References contour, holes, and Slic3r::Polygon::is_valid().
lines()
Lines Slic3r::ExPolygon::lines () const
{
    Lines lines = this->contour.lines();
    for (Polygons::const_iterator h = this->holes.begin(); h != this->holes.end(); ++h) {
        Lines hole_lines = h->lines();
        lines.insert(lines.end(), hole_lines.begin(), hole_lines.end());
    }
    return lines;
}
References contour, holes, lines(), and Slic3r::Polygon::lines().
Referenced by lines().
medial_axis() [1/3]
Polylines Slic3r::ExPolygon::medial_axis (double min_width, double max_width) const inline
        { Polylines out; this->medial_axis(min_width, max_width, &out); return out; }
References medial_axis().
medial_axis() [2/3]
void Slic3r::ExPolygon::medial_axis (double min_width, double max_width, Polylines * polylines) const
{
    ThickPolylines tp;
    this->medial_axis(min_width, max_width, &tp);
    polylines->reserve(polylines->size() + tp.size());
    for (auto &pl : tp)
        polylines->emplace_back(pl.points);
}
References medial_axis().
medial_axis() [3/3]
void Slic3r::ExPolygon::medial_axis (double min_width, double max_width, ThickPolylines * polylines) const
{
    // init helper object
    Slic3r::Geometry::MedialAxis ma(min_width, max_width, *this);
    // compute the Voronoi diagram and extract medial axis polylines
    ThickPolylines pp;
    ma.build(&pp);
    /*
    SVG svg("medial_axis.svg");
    svg.draw(*this);
    svg.draw(pp);
    svg.Close();
    */
    /* Find the maximum width returned; we're going to use this for validating and
       filtering the output segments. */
    double max_w = 0;
    for (ThickPolylines::const_iterator it = pp.begin(); it != pp.end(); ++it)
        max_w = fmaxf(max_w, *std::max_element(it->width.begin(), it->width.end()));
    /* Loop through all returned polylines in order to extend their endpoints to the
       expolygon boundaries */
    bool removed = false;
    for (size_t i = 0; i < pp.size(); ++i) {
        ThickPolyline& polyline = pp[i];
        // extend initial and final segments of each polyline if they're actual endpoints
        /* We assign new endpoints to temporary variables because in case of a single-line
           polyline, after we extend the start point it will be caught by the intersection()
           call, so we keep the inner point until we perform the second intersection() as well */
        Point new_front = polyline.points.front();
        Point new_back  = polyline.points.back();
        if (polyline.endpoints.first && !this->on_boundary(new_front, SCALED_EPSILON)) {
            Vec2d p1 = polyline.points.front().cast<double>();
            Vec2d p2 = polyline.points[1].cast<double>();
            // prevent the line from touching on the other side, otherwise intersection() might return that solution
            if (polyline.points.size() == 2)
                p2 = (p1 + p2) * 0.5;
            // Extend the start of the segment.
            p1 -= (p2 - p1).normalized() * max_width;
            this->contour.intersection(Line(p1.cast<coord_t>(), p2.cast<coord_t>()), &new_front);
        }
        if (polyline.endpoints.second && !this->on_boundary(new_back, SCALED_EPSILON)) {
            Vec2d p1 = (polyline.points.end() - 2)->cast<double>();
            Vec2d p2 = polyline.points.back().cast<double>();
            // prevent the line from touching on the other side, otherwise intersection() might return that solution
            if (polyline.points.size() == 2)
                p1 = (p1 + p2) * 0.5;
            // Extend the start of the segment.
            p2 += (p2 - p1).normalized() * max_width;
            this->contour.intersection(Line(p1.cast<coord_t>(), p2.cast<coord_t>()), &new_back);
        }
        polyline.points.front() = new_front;
        polyline.points.back()  = new_back;
        /*  remove too short polylines
            (we can't do this check before endpoints extension and clipping because we don't
            know how long will the endpoints be extended since it depends on polygon thickness
            which is variable - extension will be <= max_width/2 on each side)  */
        if ((polyline.endpoints.first || polyline.endpoints.second)
            && polyline.length() < max_w*2) {
            pp.erase(pp.begin() + i);
            --i;
            removed = true;
            continue;
        }
    }
    /*  If we removed any short polylines we now try to connect consecutive polylines
        in order to allow loop detection. Note that this algorithm is greedier than
        MedialAxis::process_edge_neighbors() as it will connect random pairs of
        polylines even when more than two start from the same point. This has no
        drawbacks since we optimize later using nearest-neighbor which would do the
        same, but should we use a more sophisticated optimization algorithm we should
        not connect polylines when more than two meet.  */
    if (removed) {
        for (size_t i = 0; i < pp.size(); ++i) {
            ThickPolyline& polyline = pp[i];
            if (polyline.endpoints.first && polyline.endpoints.second) continue; // optimization
            // find another polyline starting here
            for (size_t j = i+1; j < pp.size(); ++j) {
                ThickPolyline& other = pp[j];
                if (polyline.last_point() == other.last_point()) {
                    other.reverse();
                } else if (polyline.first_point() == other.last_point()) {
                    polyline.reverse();
                    other.reverse();
                } else if (polyline.first_point() == other.first_point()) {
                    polyline.reverse();
                } else if (polyline.last_point() != other.first_point()) {
                    continue;
                }
                polyline.points.insert(polyline.points.end(), other.points.begin() + 1, other.points.end());
                polyline.width.insert(polyline.width.end(), other.width.begin(), other.width.end());
                polyline.endpoints.second = other.endpoints.second;
                assert(polyline.width.size() == polyline.points.size()*2 - 2);
                pp.erase(pp.begin() + j);
                j = i;  // restart search from i+1
            }
        }
    }
    polylines->insert(polylines->end(), pp.begin(), pp.end());
}
References Slic3r::Geometry::MedialAxis::build(), contour, Slic3r::ThickPolyline::endpoints, Slic3r::ThickPolyline::first_point(), Slic3r::Polygon::intersection(), Slic3r::ThickPolyline::last_point(), Slic3r::ThickPolyline::length(), Slic3r::ThickPolyline::points, Slic3r::ThickPolyline::reverse(), SCALED_EPSILON, and Slic3r::ThickPolyline::width.
Referenced by medial_axis(), and medial_axis().
num_contours()
size_t Slic3r::ExPolygon::num_contours () const inline
{ return this->holes.size() + 1; }
Referenced by Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox(), Slic3r::Algorithm::expolygons_to_zpaths_expanded_opened(), point_projection(), and Slic3r::FFFSupport::tree_supports_generate_paths().
on_boundary()
bool Slic3r::ExPolygon::on_boundary (const Point & point, double eps) const
{
    if (this->contour.on_boundary(point, eps))
        return true;
    for (const Polygon &hole : this->holes)
        if (hole.on_boundary(point, eps))
            return true;
    return false;
}
References contour, holes, and Slic3r::Polygon::on_boundary().
operator=() [1/2]
ExPolygon & Slic3r::ExPolygon::operator= (const ExPolygon & other) default
operator=() [2/2]
ExPolygon & Slic3r::ExPolygon::operator= (ExPolygon && other) default
overlaps()
bool Slic3r::ExPolygon::overlaps (const ExPolygon & other) const
{
    if (this->empty() || other.empty())
        return false;
    #if 0
    BoundingBox bbox = get_extents(other);
    bbox.merge(get_extents(*this));
    static int iRun = 0;
    SVG svg(debug_out_path("ExPolygon_overlaps-%d.svg", iRun ++), bbox);
    svg.draw(*this);
    svg.draw_outline(*this);
    svg.draw_outline(other, "blue");
    #endif
    Polylines pl_out = intersection_pl(to_polylines(other), *this);
    #if 0
    svg.draw(pl_out, "red");
    #endif
    // See unit test SCENARIO("Clipper diff with polyline", "[Clipper]")
    // for in which case the intersection_pl produces any intersection.
    return ! pl_out.empty() ||
           // If *this is completely inside other, then pl_out is empty, but the expolygons overlap. Test for that situation.
           other.contains(this->contour.points.front());
}
References contains(), contour, Slic3r::debug_out_path(), Slic3r::SVG::draw(), Slic3r::SVG::draw_outline(), empty(), Slic3r::get_extents(), Slic3r::intersection_pl(), Slic3r::BoundingBoxBase< PointType, APointsType >::merge(), Slic3r::MultiPoint::points, and Slic3r::to_polylines().
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::intersects(), and Slic3r::sla::SupportPointGenerator::Structure::overlaps().
point_projection()
Point Slic3r::ExPolygon::point_projection (const Point & point) const
{
    if (this->holes.empty()) {
        return this->contour.point_projection(point);
    } else {
        double dist_min2 = std::numeric_limits<double>::max();
        Point  closest_pt_min;
        for (size_t i = 0; i < this->num_contours(); ++ i) {
            Point closest_pt = this->contour_or_hole(i).point_projection(point);
            double d2 = (closest_pt - point).cast<double>().squaredNorm();
            if (d2 < dist_min2) {
                dist_min2      = d2;
                closest_pt_min = closest_pt;
            }
        }
        return closest_pt_min;
    }
}
References contour, contour_or_hole(), holes, num_contours(), and Slic3r::Polygon::point_projection().
rotate() [1/2]
void Slic3r::ExPolygon::rotate (double angle)
{
    contour.rotate(angle);
    for (Polygon &hole : holes)
        hole.rotate(angle);
}
References Slic3r::angle(), contour, holes, and Slic3r::MultiPoint::rotate().
Referenced by Slic3r::FillGyroid::_fill_surface_single(), Slic3r::FillLine::_fill_surface_single(), Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::get_all_polygons(), libnest2d::shapelike::rotate(), and Slic3r::arrangement::ArrangePolygon::transformed_poly().
rotate() [2/2]
void Slic3r::ExPolygon::rotate (double angle, const Point & center)
{
    contour.rotate(angle, center);
    for (Polygon &hole : holes)
        hole.rotate(angle, center);
}
References Slic3r::angle(), contour, holes, and Slic3r::MultiPoint::rotate().
scale() [1/2]
void Slic3r::ExPolygon::scale (double factor)
{
    contour.scale(factor);
    for (Polygon &hole : holes)
        hole.scale(factor);
}
References contour, holes, and Slic3r::MultiPoint::scale().
Referenced by Slic3r::GUI::MeshClipper::recalculate_triangles().
scale() [2/2]
void Slic3r::ExPolygon::scale (double factor_x, double factor_y)
{
    contour.scale(factor_x, factor_y);
    for (Polygon &hole : holes)
        hole.scale(factor_x, factor_y);
}
References contour, holes, and Slic3r::MultiPoint::scale().
simplify() [1/2]
ExPolygons Slic3r::ExPolygon::simplify (double tolerance) const
{
    return union_ex(this->simplify_p(tolerance));
}
References simplify_p(), and Slic3r::union_ex().
Referenced by Slic3r::SVGRaster::draw(), Slic3r::elephant_foot_compensation(), and simplify().
simplify() [2/2]
void Slic3r::ExPolygon::simplify (double tolerance, ExPolygons * expolygons) const
{
    append(*expolygons, this->simplify(tolerance));
}
References Slic3r::append(), and simplify().
simplify_p() [1/2]
Polygons Slic3r::ExPolygon::simplify_p (double tolerance) const
{
    Polygons pp;
    pp.reserve(this->holes.size() + 1);
    // contour
    {
        Polygon p = this->contour;
        p.points.push_back(p.points.front());
        p.points = MultiPoint::douglas_peucker(p.points, tolerance);
        p.points.pop_back();
        pp.emplace_back(std::move(p));
    }
    // holes
    for (Polygon p : this->holes) {
        p.points.push_back(p.points.front());
        p.points = MultiPoint::douglas_peucker(p.points, tolerance);
        p.points.pop_back();
        pp.emplace_back(std::move(p));
    }
    return simplify_polygons(pp);
}
References contour, Slic3r::MultiPoint::douglas_peucker(), holes, Slic3r::MultiPoint::points, and Slic3r::simplify_polygons().
simplify_p() [2/2]
void Slic3r::ExPolygon::simplify_p (double tolerance, Polygons * polygons) const
{
    Polygons pp = this->simplify_p(tolerance);
    polygons->insert(polygons->end(), pp.begin(), pp.end());
}
References simplify_p().
Referenced by Slic3r::PerimeterGenerator::process_arachne(), Slic3r::PerimeterGenerator::process_classic(), simplify(), and simplify_p().
translate() [1/2]
void Slic3r::ExPolygon::translate (const Point & vector)
{
    contour.translate(p);
    for (Polygon &hole : holes)
        hole.translate(p);
}
References contour, holes, and Slic3r::MultiPoint::translate().
translate() [2/2]
void Slic3r::ExPolygon::translate (double x, double y) inline
{ this->translate(Point(coord_t(x), coord_t(y))); }
References translate().
Referenced by Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::get_all_polygons(), Slic3r::arrangement::ArrangePolygon::transformed_poly(), translate(), and libnest2d::shapelike::translate().
Member Data Documentation
contour
Polygon Slic3r::ExPolygon::contour
Referenced by Slic3r::ExPolygonWithOffset::ExPolygonWithOffset(), Slic3r::ExPolygonWithOffset::ExPolygonWithOffset(), Slic3r::Fill3DHoneycomb::_fill_surface_single(), Slic3r::FillConcentric::_fill_surface_single(), Slic3r::FillGyroid::_fill_surface_single(), Slic3r::FillHoneycomb::_fill_surface_single(), Slic3r::FillLine::_fill_surface_single(), Slic3r::FillConcentric::_fill_surface_single(), Slic3r::Fill::_infill_direction(), Slic3r::sla::anonymous_namespace{Pad.cpp}::add_cavity(), area(), Slic3r::arrangement::arrange(), boost::polygon::polygon_traits< Slic3r::ExPolygon >::begin_points(), Slic3r::SupportSpotsGenerator::build_object_part_from_slice(), clear(), Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox(), priv::collect_close_points(), Slic3r::Fill::connect_infill(), Slic3r::FillAdaptive::connect_lines_using_hooks(), contains(), Slic3r::contour(), libnest2d::shapelike::contour(), libnest2d::shapelike::contour(), Slic3r::contour_distance(), Slic3r::contour_distance2(), contour_or_hole(), contour_or_hole(), Slic3r::count_points(), Slic3r::EdgeGrid::Grid::create(), libnest2d::shapelike::create(), libnest2d::shapelike::create(), Slic3r::sla::anonymous_namespace{Pad.cpp}::create_outer_pad_geometry(), Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint(), Slic3r::Emboss::divide_segments_for_close_point(), douglas_peucker(), Slic3r::SVG::draw_outline(), Slic3r::FFFSupport::draw_perimeters(), Slic3r::elephant_foot_compensation(), empty(), boost::polygon::polygon_traits< Slic3r::ExPolygon >::end_points(), Slic3r::expolygons_match(), Slic3r::ClipperZUtils::expolygons_to_zpaths(), priv::fill_polygon_distances(), Slic3r::FillRectilinear::fill_surface_by_multilines(), priv::find_close_point(), priv::find_closest_point_pair(), Slic3r::WipeTower::finish_layer(), Slic3r::foreach_vertex(), Slic3r::sla::foreach_vertex(), Slic3r::get_all_polygons(), Slic3r::get_arrange_poly(), Slic3r::ModelInstance::get_arrange_polygon(), Slic3r::GUI::WipeTower::get_arrange_polygon(), priv::get_closest_point_index(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents_rotated(), Slic3r::has_duplicate_points(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::intersects(), is_valid(), Slic3r::SupportGridPattern::island_samples(), lines(), medial_axis(), Slic3r::Algorithm::merge_expansions_into_expolygons(), Slic3r::sla::anonymous_namespace{Pad.cpp}::offset_contour_only(), Slic3r::offset_expolygon_inner(), on_boundary(), Slic3r::operator!=(), Slic3r::ClipperUtils::ExPolygonProvider::iterator::operator*(), Slic3r::operator==(), overlaps(), point_projection(), Slic3r::polygons_append(), Slic3r::precompute_expolygon_distances(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::arrangement::process_arrangeable(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::remove_sticks(), Slic3r::resample_expolygon(), rotate(), rotate(), Slic3r::sla::sample_expolygon_boundary(), scale(), scale(), boost::polygon::polygon_mutable_traits< Slic3r::ExPolygon >::set_points(), Slic3r::GUI::Bed3D::set_shape(), simplify_p(), boost::polygon::polygon_traits< Slic3r::ExPolygon >::size(), Slic3r::straight_walls(), Slic3r::GluTessWrapper::tesselate3d(), priv::to_expoly(), Slic3r::to_lines(), Slic3r::to_points(), Slic3r::to_polygon_ptrs(), Slic3r::to_polygons(), Slic3r::to_polylines(), libnest2d::shapelike::toString(), Slic3r::anonymous_namespace{SL1_SVG.cpp}::transform(), translate(), Slic3r::traverse_pt(), Slic3r::FFFSupport::tree_supports_generate_paths(), Slic3r::GUI::update_arrangepoly_slaprint(), Slic3r::validate_expoly_orientation(), Slic3r::variable_offset_inner_raw(), Slic3r::variable_offset_outer_ex(), and Slic3r::variable_offset_outer_raw().
holes
Polygons Slic3r::ExPolygon::holes
Referenced by ExPolygon(), ExPolygon(), ExPolygon(), ExPolygon(), Slic3r::ExPolygonWithOffset::ExPolygonWithOffset(), Slic3r::ExPolygonWithOffset::ExPolygonWithOffset(), area(), boost::polygon::polygon_with_holes_traits< Slic3r::ExPolygon >::begin_holes(), Slic3r::SupportSpotsGenerator::build_object_part_from_slice(), Slic3r::ClipperUtils::ExPolygonProvider::cend(), clear(), Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox(), priv::collect_close_points(), Slic3r::Fill::connect_infill(), Slic3r::FillAdaptive::connect_lines_using_hooks(), contains(), Slic3r::contour_distance(), Slic3r::contour_distance2(), Slic3r::count_points(), Slic3r::EdgeGrid::Grid::create(), libnest2d::shapelike::create(), libnest2d::shapelike::create(), Slic3r::sla::anonymous_namespace{Pad.cpp}::create_outer_pad_geometry(), Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint(), Slic3r::Emboss::divide_segments_for_close_point(), douglas_peucker(), Slic3r::SVG::draw_outline(), Slic3r::FFFSupport::draw_perimeters(), Slic3r::elephant_foot_compensation(), boost::polygon::polygon_with_holes_traits< Slic3r::ExPolygon >::end_holes(), Slic3r::expolygons_match(), Slic3r::ClipperZUtils::expolygons_to_zpaths(), priv::fill_polygon_distances(), priv::find_close_point(), priv::find_closest_point_pair(), Slic3r::foreach_vertex(), Slic3r::sla::foreach_vertex(), Slic3r::get_all_polygons(), priv::get_closest_point_index(), Slic3r::has_duplicate_points(), libnest2d::shapelike::hole(), libnest2d::shapelike::hole(), libnest2d::shapelike::holeCount(), Slic3r::holes(), libnest2d::shapelike::holes(), libnest2d::shapelike::holes(), is_valid(), lines(), Slic3r::mark_boundary_segments_touching_infill(), Slic3r::sla::anonymous_namespace{Pad.cpp}::offset_contour_only(), Slic3r::offset_expolygon_inner(), on_boundary(), Slic3r::operator!=(), Slic3r::ClipperUtils::ExPolygonProvider::iterator::operator*(), Slic3r::operator==(), point_projection(), Slic3r::polygons_append(), Slic3r::precompute_expolygon_distances(), Slic3r::remove_sticks(), Slic3r::resample_expolygon(), rotate(), rotate(), Slic3r::sla::sample_expolygon_boundary(), scale(), scale(), boost::polygon::polygon_with_holes_mutable_traits< Slic3r::ExPolygon >::set_holes(), simplify_p(), Slic3r::ClipperUtils::ExPolygonProvider::size(), boost::polygon::polygon_with_holes_traits< Slic3r::ExPolygon >::size_holes(), Slic3r::straight_walls(), Slic3r::GluTessWrapper::tesselate3d(), Slic3r::to_lines(), Slic3r::to_points(), Slic3r::to_polygon_ptrs(), Slic3r::to_polygons(), Slic3r::to_polylines(), libnest2d::shapelike::toString(), Slic3r::anonymous_namespace{SL1_SVG.cpp}::transform(), translate(), Slic3r::FFFSupport::tree_supports_generate_paths(), Slic3r::GUI::update_arrangepoly_slaprint(), Slic3r::validate_expoly_orientation(), Slic3r::variable_offset_inner_raw(), Slic3r::variable_offset_outer_ex(), and Slic3r::variable_offset_outer_raw().
The documentation for this class was generated from the following files:
src/libslic3r/ExPolygon.hpp
src/libslic3r/ExPolygon.cpp