Prusa Slicer: igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO > Class Template Reference
igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO > Class Template Reference
Public Member Functions
MeshCutter (const Eigen::PlainObjectBase< DerivedV > &V_, const Eigen::PlainObjectBase< DerivedF > &F_, const Eigen::PlainObjectBase< DerivedM > &Handle_MMatch_)
void cut (Eigen::PlainObjectBase< DerivedO > &Handle_Seams)
Protected Member Functions
bool IsRotSeam (const int f0, const int edge)
void FloodFill (const int start, Eigen::PlainObjectBase< DerivedO > &Handle_Seams)
void Retract (Eigen::PlainObjectBase< DerivedO > &Handle_Seams)
Protected Attributes
const Eigen::PlainObjectBase< DerivedV > & V
const Eigen::PlainObjectBase< DerivedF > & F
const Eigen::PlainObjectBase< DerivedM > & Handle_MMatch
Eigen::VectorXi F_visited
DerivedF TT
DerivedF TTi
Eigen::MatrixXi E
Eigen::MatrixXi F2E
Eigen::MatrixXi E2F
Detailed Description
template<typename DerivedV, typename DerivedF, typename DerivedM, typename DerivedO>
class igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >
Constructor & Destructor Documentation
MeshCutter()
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::MeshCutter (const Eigen::PlainObjectBase< DerivedV > & V_, const Eigen::PlainObjectBase< DerivedF > & F_, const Eigen::PlainObjectBase< DerivedM > & Handle_MMatch_) inline
                                                                    :
    V(V_),
    F(F_),
    Handle_MMatch(Handle_MMatch_)
    {
      triangle_triangle_adjacency(F,TT,TTi);
      edge_topology(V,F,E,F2E,E2F);
    };
References igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::E, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::E2F, igl::edge_topology(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F2E, igl::triangle_triangle_adjacency(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::TT, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::TTi, and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::V.
Member Function Documentation
cut()
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > void igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::cut (Eigen::PlainObjectBase< DerivedO > & Handle_Seams) inline
    {
      F_visited.setConstant(F.rows(),0);
      Handle_Seams.setConstant(F.rows(),3,1);
      int index=0;
      for (unsigned f = 0; f<F.rows(); f++)
      {
        if (!F_visited(f))
        {
          index++;
          FloodFill(f, Handle_Seams);
        }
      }
      Retract(Handle_Seams);
      for (unsigned int f=0;f<F.rows();f++)
        for (int j=0;j<3;j++)
          if (IsRotSeam(f,j))
            Handle_Seams(f,j)=true;
    }
References igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F_visited, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::FloodFill(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::IsRotSeam(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract(), Eigen::PlainObjectBase< Derived >::rows(), and Eigen::PlainObjectBase< Derived >::setConstant().
Referenced by igl::cut_mesh_from_singularities().
FloodFill()
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > void igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::FloodFill (const int start, Eigen::PlainObjectBase< DerivedO > & Handle_Seams) inline protected
clean the visited flag
    {
      std::deque<int> d;
      F_visited(start) = true;
      d.push_back(start);
      while (!d.empty())
      {
        int f = d.at(0); d.pop_front();
        for (int s = 0; s<3; s++)
        {
          int g = TT(f,s); // f->FFp(s);
          int j = TTi(f,s); // f->FFi(s);
          if (j == -1)
          {
            g = f;
            j = s;
          }
          if ((!(IsRotSeam(f,s))) && (!(IsRotSeam(g,j)))  && (!F_visited(g)) )
          {
            Handle_Seams(f,s)=false;
            Handle_Seams(g,j)=false;
            F_visited(g) = true;
            d.push_back(g);
          }
        }
      }
    }
References igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F_visited, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::IsRotSeam(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::TT, and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::TTi.
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::cut().
IsRotSeam()
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > bool igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::IsRotSeam (const int f0, const int edge) inline protected
    {
      unsigned char MM = Handle_MMatch(f0,edge);
      return (MM!=0);
    }
References igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Handle_MMatch.
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::cut(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::FloodFill(), and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract().
Retract()
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > void igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract (Eigen::PlainObjectBase< DerivedO > & Handle_Seams) inline protected
    {
      std::vector<int> e(V.rows(),0); // number of edges per vert
      // for (unsigned f=0; f<F.rows(); f++)
      // {
      //   for (int s = 0; s<3; s++)
      //   {
      //     if (Handle_Seams(f,s))
      //       if (TT(f,s)<=f)
      //       {
      //         e[ F(f,s) ] ++;
      //         e[ F(f,(s+1)%3) ] ++;
      //       }
      //   }
      // }
      for (int ei=0; ei<E.rows(); ++ei)
      {
        //only need one face
        int f0 = E2F(ei,0);
        if (f0==-1)
          f0 = E2F(ei,1);
        int k=0;
        for (k=0; k<3; ++k)
          if (F2E(f0,k)==ei)
            break;
        if (Handle_Seams(f0,k))
        {
          e[ F(f0,k) ] ++;
          e[ F(f0,(k+1)%3) ] ++;
        }
      }
      bool over=true;
      int guard = 0;
      do
      {
        over = true;
        for (int f = 0; f<F.rows(); f++) //if (!f->IsD())
        {
          for (int s = 0; s<3; s++)
          {
            if (Handle_Seams(f,s))
              if (!(IsRotSeam(f,s))) // never retract rot seams
              {
                if (e[ F(f,s) ] == 1) {
                  // dissolve seam
                  Handle_Seams(f,s)=false;
                  if (TT(f,s) != -1)
                    Handle_Seams(TT(f,s),TTi(f,s))=false;
                  e[ F(f,s)] --;
                  e[ F(f,(s+1)%3) ] --;
                  over = false;
                }
              }
          }
        }
        if (guard++>10000)
          over = true;
      } while (!over);
    }
References igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::E, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::E2F, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F2E, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::IsRotSeam(), Eigen::PlainObjectBase< Derived >::rows(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::TT, igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::TTi, and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::V.
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::cut().
Member Data Documentation
E
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > Eigen::MatrixXi igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::E protected
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::MeshCutter(), and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract().
E2F
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > Eigen::MatrixXi igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::E2F protected
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::MeshCutter(), and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract().
F
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > const Eigen::PlainObjectBase<DerivedF>& igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F protected
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::MeshCutter(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::cut(), and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract().
F2E
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > Eigen::MatrixXi igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F2E protected
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::MeshCutter(), and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract().
F_visited
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > Eigen::VectorXi igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::F_visited protected
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::cut(), and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::FloodFill().
Handle_MMatch
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > const Eigen::PlainObjectBase<DerivedM>& igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Handle_MMatch protected
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::IsRotSeam().
TT
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > DerivedF igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::TT protected
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::MeshCutter(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::FloodFill(), and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract().
TTi
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > DerivedF igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::TTi protected
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::MeshCutter(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::FloodFill(), and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract().
V
template<typename DerivedV , typename DerivedF , typename DerivedM , typename DerivedO > const Eigen::PlainObjectBase<DerivedV>& igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::V protected
Referenced by igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::MeshCutter(), and igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract().
The documentation for this class was generated from the following file:
src/libigl/igl/cut_mesh_from_singularities.cpp