Prusa Slicer: igl::geodesic::MeshElementBase Class Reference
igl::geodesic::MeshElementBase Class Reference
Public Types
typedef SimpleVector< vertex_pointer > vertex_pointer_vector
typedef SimpleVector< edge_pointer > edge_pointer_vector
typedef SimpleVector< face_pointer > face_pointer_vector
Public Member Functions
MeshElementBase ()
vertex_pointer_vector & adjacent_vertices ()
edge_pointer_vector & adjacent_edges ()
face_pointer_vector & adjacent_faces ()
unsigned & id ()
PointType type ()
Protected Attributes
vertex_pointer_vector m_adjacent_vertices
edge_pointer_vector m_adjacent_edges
face_pointer_vector m_adjacent_faces
unsigned m_id
PointType m_type
Detailed Description
Member Typedef Documentation
edge_pointer_vector
typedef SimpleVector<edge_pointer> igl::geodesic::MeshElementBase::edge_pointer_vector
face_pointer_vector
typedef SimpleVector<face_pointer> igl::geodesic::MeshElementBase::face_pointer_vector
vertex_pointer_vector
typedef SimpleVector<vertex_pointer> igl::geodesic::MeshElementBase::vertex_pointer_vector
Constructor & Destructor Documentation
MeshElementBase()
igl::geodesic::MeshElementBase::MeshElementBase () inline
                   :
    m_id(0),
    m_type(UNDEFINED_POINT)
  {};
Member Function Documentation
adjacent_edges()
edge_pointer_vector & igl::geodesic::MeshElementBase::adjacent_edges () inline
{return m_adjacent_edges;};
References m_adjacent_edges.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::GeodesicAlgorithmExact::list_edges_visible_from_source(), igl::geodesic::Face::next_edge(), igl::geodesic::Face::opposite_edge(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), igl::geodesic::Mesh::verify(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
adjacent_faces()
face_pointer_vector & igl::geodesic::MeshElementBase::adjacent_faces () inline
{return m_adjacent_faces;};
References m_adjacent_faces.
Referenced by igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::GeodesicAlgorithmExact::construct_propagated_intervals(), igl::geodesic::Edge::is_boundary(), igl::geodesic::Edge::opposite_face(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), and igl::geodesic::GeodesicAlgorithmExact::propagate().
adjacent_vertices()
vertex_pointer_vector & igl::geodesic::MeshElementBase::adjacent_vertices () inline
{return m_adjacent_vertices;};
References m_adjacent_vertices.
Referenced by igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::Edge::belongs(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Face::opposite_vertex(), igl::geodesic::Edge::opposite_vertex(), igl::geodesic::Edge::v0(), igl::geodesic::Edge::v1(), igl::geodesic::Mesh::verify(), and igl::geodesic::Face::vertex_angle().
id()
unsigned & igl::geodesic::MeshElementBase::id () inline
{return m_id;};
References m_id.
Referenced by igl::geodesic::Edge::belongs(), igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::GeodesicAlgorithmExact::construct_propagated_intervals(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Interval::initialize(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::GeodesicAlgorithmExact::intersect_intervals(), igl::geodesic::GeodesicAlgorithmExact::interval_list(), igl::geodesic::Face::next_edge(), igl::geodesic::Edge::opposite_face(), igl::geodesic::Edge::opposite_vertex(), igl::geodesic::GeodesicAlgorithmExact::propagate(), igl::geodesic::Mesh::verify(), igl::geodesic::Face::vertex_angle(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
type()
PointType igl::geodesic::MeshElementBase::type () inline
{return m_type;};
References m_type.
Referenced by igl::geodesic::Interval::initialize(), igl::geodesic::GeodesicAlgorithmExact::list_edges_visible_from_source(), and igl::geodesic::SurfacePoint::type().
Member Data Documentation
m_adjacent_edges
edge_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_edges protected
Referenced by adjacent_edges().
m_adjacent_faces
face_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_faces protected
Referenced by adjacent_faces().
m_adjacent_vertices
vertex_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_vertices protected
Referenced by adjacent_vertices().
m_id
unsigned igl::geodesic::MeshElementBase::m_id protected
Referenced by id().
m_type
PointType igl::geodesic::MeshElementBase::m_type protected
Referenced by igl::geodesic::Edge::Edge(), igl::geodesic::Face::Face(), igl::geodesic::Vertex::Vertex(), and type().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp