Prusa Slicer: Slic3r::GUI::TabPresetComboBox Class Reference
Slic3r::GUI::TabPresetComboBox Class Reference
#include <src/slic3r/GUI/PresetComboBoxes.hpp>
Public Types
enum LabelItemType {
LABEL_ITEM_PHYSICAL_PRINTER = 0xffffff01 , LABEL_ITEM_DISABLED , LABEL_ITEM_MARKER , LABEL_ITEM_PHYSICAL_PRINTERS ,
LABEL_ITEM_WIZARD_PRINTERS , LABEL_ITEM_WIZARD_FILAMENTS , LABEL_ITEM_WIZARD_MATERIALS , LABEL_ITEM_MAX
}
Public Member Functions
TabPresetComboBox (wxWindow *parent, Preset::Type preset_type)
~TabPresetComboBox ()
void set_show_incompatible_presets (bool show_incompatible_presets)
wxString get_preset_name (const Preset &preset) override
void update () override
void update_dirty ()
void msw_rescale () override
void OnSelect (wxCommandEvent &evt) override
void set_enable_all (bool enable=true)
PresetCollection * presets () const
Preset::Type type () const
void set_active_extruder (int extruder_idx)
void set_label_marker (int item, LabelItemType label_item_type=LABEL_ITEM_MARKER)
bool set_printer_technology (PrinterTechnology pt)
void set_selection_changed_function (std::function< void(int)> sel_changed)
bool is_selected_physical_printer ()
bool selection_is_changed_according_to_physical_printers ()
void update (std::string select_preset)
void update_from_bundle ()
void edit_physical_printer ()
void add_physical_printer ()
void open_physical_printer_url ()
bool del_physical_printer (const wxString &note_string=wxEmptyString)
void show_modif_preset_separately ()
Preset::Type get_type ()
void show_all (bool show_all)
virtual void sys_color_changed ()
int Append (const wxString &item, const wxBitmapBundle &bitmap)
Protected Types
typedef std::size_t Marker
Protected Member Functions
void invalidate_selection ()
void validate_selection (bool predicate=false)
void update_selection ()
wxBitmapBundle * get_bmp (std::string bitmap_key, bool wide_icons, const std::string &main_icon_name, bool is_compatible=true, bool is_system=false, bool is_single_bar=false, const std::string &filament_rgb="", const std::string &extruder_rgb="", const std::string &material_rgb="")
wxBitmapBundle * get_bmp (std::string bitmap_key, const std::string &main_icon_name, const std::string &next_icon_name, bool is_enabled=true, bool is_compatible=true, bool is_system=false)
wxBitmapBundle NullBitmapBndl ()
Static Protected Member Functions
static BitmapCache & bitmap_cache ()
static const char * separator_head ()
static const char * separator_tail ()
static wxString separator (const std::string &label)
Protected Attributes
std::function< void(int)> on_selection_changed { nullptr }
Preset::Type m_type
std::string m_main_bitmap_name
PresetBundle * m_preset_bundle {nullptr}
PresetCollection * m_collection {nullptr}
wxBitmapBundle * m_bitmapCompatible
wxBitmapBundle * m_bitmapIncompatible
int m_last_selected
int m_em_unit
bool m_suppress_change { true }
int icon_height
int norm_icon_width
int null_icon_width
int thin_icon_width
int wide_icon_width
int space_icon_width
int thin_space_icon_width
int wide_space_icon_width
PrinterTechnology printer_technology {ptAny}
Private Member Functions
void fill_width_height ()
Private Attributes
bool show_incompatible {false}
bool m_enable_all {false}
int m_active_extruder_idx {0}
bool m_show_all { false }
bool m_show_modif_preset_separately { false }
Detailed Description
Member Typedef Documentation
Marker
typedef std::size_t Slic3r::GUI::PresetComboBox::Marker protected inherited
Member Enumeration Documentation
LabelItemType
enum Slic3r::GUI::PresetComboBox::LabelItemType inherited
Enumerator
LABEL_ITEM_PHYSICAL_PRINTER
LABEL_ITEM_DISABLED
LABEL_ITEM_MARKER
LABEL_ITEM_PHYSICAL_PRINTERS
LABEL_ITEM_WIZARD_PRINTERS
LABEL_ITEM_WIZARD_FILAMENTS
LABEL_ITEM_WIZARD_MATERIALS
LABEL_ITEM_MAX
                     {
    LABEL_ITEM_PHYSICAL_PRINTER = 0xffffff01,
    LABEL_ITEM_DISABLED,
    LABEL_ITEM_MARKER,
    LABEL_ITEM_PHYSICAL_PRINTERS,
    LABEL_ITEM_WIZARD_PRINTERS,
        LABEL_ITEM_WIZARD_FILAMENTS,
        LABEL_ITEM_WIZARD_MATERIALS,
        LABEL_ITEM_MAX,
  };
Constructor & Destructor Documentation
TabPresetComboBox()
Slic3r::GUI::TabPresetComboBox::TabPresetComboBox (wxWindow * parent, Preset::Type preset_type)
                                                                             :
    PresetComboBox(parent, preset_type, wxSize(35 * wxGetApp().em_unit(), -1))
{
}
~TabPresetComboBox()
Slic3r::GUI::TabPresetComboBox::~TabPresetComboBox () inline
{}
Member Function Documentation
add_physical_printer()
void Slic3r::GUI::PresetComboBox::add_physical_printer () inherited
{
    if (PhysicalPrinterDialog(this->GetParent(), wxEmptyString).ShowModal() == wxID_OK)
        update();
}
References Slic3r::GUI::PresetComboBox::update().
Referenced by Slic3r::GUI::PlaterPresetComboBox::show_edit_menu().
Append()
int Slic3r::GUI::BitmapComboBox::Append (const wxString & item, const wxBitmapBundle & bitmap) inline inherited
    {
        return wxBitmapComboBox::Append(item, bitmap);
    }
Referenced by Slic3r::GUI::ModePaletteComboBox::ModePaletteComboBox(), BitmapChoiceRenderer::CreateEditorCtrl(), Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
bitmap_cache()
BitmapCache & Slic3r::GUI::PresetComboBox::bitmap_cache () static protected inherited
{
    static BitmapCache bmps;
    return bmps;
}
Referenced by Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::get_bmp().
del_physical_printer()
bool Slic3r::GUI::PresetComboBox::del_physical_printer (const wxString & note_string = wxEmptyString) inherited
{
    const std::string& printer_name = m_preset_bundle->physical_printers.get_selected_full_printer_name();
    if (printer_name.empty())
        return false;
    wxString msg;
    if (!note_string.IsEmpty())
        msg += note_string + "\n";
    msg += format_wxstr(_L("Are you sure you want to delete \"%1%\" printer?"), printer_name);
    if (MessageDialog(this, msg, _L("Delete Physical Printer"), wxYES_NO | wxNO_DEFAULT | wxICON_QUESTION).ShowModal() != wxID_YES)
        return false;
    m_preset_bundle->physical_printers.delete_selected_printer();
    this->update();
    if (dynamic_cast<PlaterPresetComboBox*>(this) != nullptr)
        wxGetApp().get_tab(m_type)->update_preset_choice();
    else if (dynamic_cast<TabPresetComboBox*>(this) != nullptr)
    {
        wxGetApp().get_tab(m_type)->update_btns_enabling();
        wxGetApp().plater()->sidebar().update_presets(m_type);
    }
    return true;
}
References _L, Slic3r::PhysicalPrinterCollection::delete_selected_printer(), Slic3r::GUI::format_wxstr(), Slic3r::PhysicalPrinterCollection::get_selected_full_printer_name(), Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::PresetBundle::physical_printers, and Slic3r::GUI::PresetComboBox::update().
Referenced by Slic3r::GUI::PlaterPresetComboBox::show_edit_menu().
edit_physical_printer()
void Slic3r::GUI::PresetComboBox::edit_physical_printer () inherited
{
    if (!m_preset_bundle->physical_printers.has_selection())
        return;
    PhysicalPrinterDialog dlg(this->GetParent(),this->GetString(this->GetSelection()));
    if (dlg.ShowModal() == wxID_OK)
        update();
}
References Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::PresetBundle::physical_printers, and Slic3r::GUI::PresetComboBox::update().
Referenced by Slic3r::GUI::PlaterPresetComboBox::show_edit_menu().
fill_width_height()
void Slic3r::GUI::PresetComboBox::fill_width_height () private inherited
{
    icon_height     = 16;
    norm_icon_width = 16;
    thin_icon_width = 8;
    wide_icon_width = norm_icon_width + thin_icon_width;
    null_icon_width = 2 * norm_icon_width;
    space_icon_width      = 2;
    thin_space_icon_width = 4;
    wide_space_icon_width = 6;
}
References Slic3r::GUI::PresetComboBox::icon_height, Slic3r::GUI::PresetComboBox::norm_icon_width, Slic3r::GUI::PresetComboBox::null_icon_width, Slic3r::GUI::PresetComboBox::space_icon_width, Slic3r::GUI::PresetComboBox::thin_icon_width, Slic3r::GUI::PresetComboBox::thin_space_icon_width, Slic3r::GUI::PresetComboBox::wide_icon_width, and Slic3r::GUI::PresetComboBox::wide_space_icon_width.
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox().
get_bmp() [1/2]
wxBitmapBundle * Slic3r::GUI::PresetComboBox::get_bmp (std::string bitmap_key, bool wide_icons, const std::string & main_icon_name, bool is_compatible = true, bool is_system = false, bool is_single_bar = false, const std::string & filament_rgb = "", const std::string & extruder_rgb = "", const std::string & material_rgb = "") protected inherited
{
    // If the filament preset is not compatible and there is a "red flag" icon loaded, show it left
    // to the filament color image.
    if (wide_icons)
        bitmap_key += is_compatible ? ",cmpt" : ",ncmpt";
    bitmap_key += is_system ? ",syst" : ",nsyst";
    bitmap_key += ",h" + std::to_string(icon_height);
    bool dark_mode = wxGetApp().dark_mode();
    if (dark_mode)
        bitmap_key += ",dark";
    bitmap_key += material_rgb;
    wxBitmapBundle* bmp_bndl = bitmap_cache().find_bndl(bitmap_key);
    if (bmp_bndl == nullptr) {
        // Create the bitmap with color bars.
        std::vector<wxBitmapBundle*> bmps;
        if (wide_icons)
            // Paint a red flag for incompatible presets.
            bmps.emplace_back(is_compatible ? get_empty_bmp_bundle(norm_icon_width, icon_height) : m_bitmapIncompatible);
        if (m_type == Preset::TYPE_FILAMENT && !filament_rgb.empty()) {
            // Paint the color bars.
            bmps.emplace_back(get_solid_bmp_bundle(is_single_bar ? wide_icon_width : norm_icon_width, icon_height, filament_rgb));
            if (!is_single_bar)
                bmps.emplace_back(get_solid_bmp_bundle(thin_icon_width, icon_height, extruder_rgb));
            // Paint a lock at the system presets.
            bmps.emplace_back(get_empty_bmp_bundle(space_icon_width, icon_height));
        }
        else
        {
            // Paint the color bars.
            bmps.emplace_back(get_empty_bmp_bundle(thin_space_icon_width, icon_height));
            if (m_type == Preset::TYPE_SLA_MATERIAL)
                bmps.emplace_back(bitmap_cache().from_svg(main_icon_name, 16, 16, dark_mode, material_rgb));
            else
                bmps.emplace_back(get_bmp_bundle(main_icon_name));
            // Paint a lock at the system presets.
            bmps.emplace_back(get_empty_bmp_bundle(wide_space_icon_width, icon_height));
        }
        bmps.emplace_back(is_system ? get_bmp_bundle("lock_closed") : get_empty_bmp_bundle(norm_icon_width, icon_height));
        bmp_bndl = bitmap_cache().insert_bndl(bitmap_key, bmps);
    }
    return bmp_bndl;
}
References Slic3r::GUI::PresetComboBox::bitmap_cache(), Slic3r::GUI::BitmapCache::find_bndl(), Slic3r::GUI::BitmapCache::from_svg(), get_bmp_bundle(), get_empty_bmp_bundle(), get_solid_bmp_bundle(), Slic3r::GUI::PresetComboBox::icon_height, Slic3r::GUI::BitmapCache::insert_bndl(), Slic3r::GUI::PresetComboBox::m_bitmapIncompatible, Slic3r::GUI::PresetComboBox::m_type, Slic3r::GUI::PresetComboBox::norm_icon_width, Slic3r::GUI::PresetComboBox::space_icon_width, Slic3r::GUI::PresetComboBox::thin_icon_width, Slic3r::GUI::PresetComboBox::thin_space_icon_width, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::GUI::PresetComboBox::wide_icon_width, and Slic3r::GUI::PresetComboBox::wide_space_icon_width.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
get_bmp() [2/2]
wxBitmapBundle * Slic3r::GUI::PresetComboBox::get_bmp (std::string bitmap_key, const std::string & main_icon_name, const std::string & next_icon_name, bool is_enabled = true, bool is_compatible = true, bool is_system = false) protected inherited
{
    bitmap_key += !is_enabled ? "_disabled" : "";
    bitmap_key += is_compatible ? ",cmpt" : ",ncmpt";
    bitmap_key += is_system ? ",syst" : ",nsyst";
    bitmap_key += ",h" + std::to_string(icon_height);
    if (wxGetApp().dark_mode())
        bitmap_key += ",dark";
    wxBitmapBundle* bmp = bitmap_cache().find_bndl(bitmap_key);
    if (bmp == nullptr) {
        // Create the bitmap with color bars.
        std::vector<wxBitmapBundle*> bmps;
        bmps.emplace_back(m_type == Preset::TYPE_PRINTER ? get_bmp_bundle(main_icon_name) :
                          is_compatible ? m_bitmapCompatible : m_bitmapIncompatible);
        // Paint a lock at the system presets.
        bmps.emplace_back(is_system ? get_bmp_bundle(next_icon_name) : get_empty_bmp_bundle(norm_icon_width, icon_height));
        bmp = bitmap_cache().insert_bndl(bitmap_key, bmps);
    }
    return bmp;
}
References Slic3r::GUI::PresetComboBox::bitmap_cache(), Slic3r::GUI::BitmapCache::find_bndl(), get_bmp_bundle(), get_empty_bmp_bundle(), Slic3r::GUI::PresetComboBox::icon_height, Slic3r::GUI::BitmapCache::insert_bndl(), Slic3r::GUI::PresetComboBox::m_bitmapCompatible, Slic3r::GUI::PresetComboBox::m_bitmapIncompatible, Slic3r::GUI::PresetComboBox::m_type, Slic3r::GUI::PresetComboBox::norm_icon_width, and Slic3r::Preset::TYPE_PRINTER.
get_preset_name()
wxString Slic3r::GUI::TabPresetComboBox::get_preset_name (const Preset & preset) override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    return from_u8(preset.name + suffix(preset));
}
References Slic3r::GUI::from_u8(), Slic3r::Preset::name, and Slic3r::GUI::suffix().
Referenced by update().
get_type()
Preset::Type Slic3r::GUI::PresetComboBox::get_type () inline inherited
{ return m_type; }
References Slic3r::GUI::PresetComboBox::m_type.
Referenced by Slic3r::GUI::DiffPresetDialog::create_presets_sizer(), Slic3r::GUI::Plater::priv::on_select_preset(), and Slic3r::GUI::DiffPresetDialog::update_compatibility().
invalidate_selection()
void Slic3r::GUI::PresetComboBox::invalidate_selection () protected inherited
{
    m_last_selected = INT_MAX; // this value means that no one item is selected
}
References Slic3r::GUI::PresetComboBox::m_last_selected.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
is_selected_physical_printer()
bool Slic3r::GUI::PresetComboBox::is_selected_physical_printer () inherited
{
    auto selected_item = this->GetSelection();
    auto marker = reinterpret_cast<Marker>(this->GetClientData(selected_item));
    return marker == LABEL_ITEM_PHYSICAL_PRINTER;
}
References Slic3r::GUI::PresetComboBox::LABEL_ITEM_PHYSICAL_PRINTER.
Referenced by Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), and Slic3r::GUI::PlaterPresetComboBox::show_edit_menu().
msw_rescale()
void Slic3r::GUI::TabPresetComboBox::msw_rescale () override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    PresetComboBox::msw_rescale();
    wxSize sz = wxSize(35 * m_em_unit, -1);
    SetMinSize(sz);
    SetSize(sz);
}
References Slic3r::GUI::PresetComboBox::m_em_unit, and Slic3r::GUI::PresetComboBox::msw_rescale().
NullBitmapBndl()
wxBitmapBundle Slic3r::GUI::PresetComboBox::NullBitmapBndl () protected inherited
{
    assert(null_icon_width > 0);
    return *get_empty_bmp_bundle(null_icon_width, icon_height);
}
References get_empty_bmp_bundle(), Slic3r::GUI::PresetComboBox::icon_height, and Slic3r::GUI::PresetComboBox::null_icon_width.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
OnSelect()
void Slic3r::GUI::TabPresetComboBox::OnSelect (wxCommandEvent & evt) override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    // see https://github.com/prusa3d/PrusaSlicer/issues/3889
    // Under OSX: in case of use of a same names written in different case (like "ENDER" and "Ender")
    // m_presets_choice->GetSelection() will return first item, because search in PopupListCtrl is case-insensitive.
    // So, use GetSelection() from event parameter
    auto selected_item = evt.GetSelection();
    auto marker = reinterpret_cast<Marker>(this->GetClientData(selected_item));
    if (marker >= LABEL_ITEM_DISABLED && marker < LABEL_ITEM_MAX) {
        this->SetSelection(m_last_selected);
        if (marker == LABEL_ITEM_WIZARD_PRINTERS)
            wxTheApp->CallAfter([this]() {
            run_wizard(ConfigWizard::SP_PRINTERS);
            // update combobox if its parent is a PhysicalPrinterDialog
            PhysicalPrinterDialog* parent = dynamic_cast<PhysicalPrinterDialog*>(this->GetParent());
            if (parent != nullptr)
                update();
        });
    }
    else if (on_selection_changed && (m_last_selected != selected_item || m_collection->current_is_dirty())) {
        m_last_selected = selected_item;
        on_selection_changed(selected_item);
    }
    evt.StopPropagation();
#ifdef __WXMSW__
    // From the Win 2004 preset combobox lose a focus after change the preset selection
    // and that is why the up/down arrow doesn't work properly
    // (see https://github.com/prusa3d/PrusaSlicer/issues/5531 ).
    // So, set the focus to the combobox explicitly
    this->SetFocus();
#endif
}
References Slic3r::PresetCollection::current_is_dirty(), Slic3r::GUI::PresetComboBox::LABEL_ITEM_DISABLED, Slic3r::GUI::PresetComboBox::LABEL_ITEM_MAX, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_PRINTERS, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_last_selected, Slic3r::GUI::PresetComboBox::on_selection_changed, Slic3r::GUI::run_wizard(), Slic3r::GUI::ConfigWizard::SP_PRINTERS, and update().
open_physical_printer_url()
void Slic3r::GUI::PresetComboBox::open_physical_printer_url () inherited
{
    const PhysicalPrinter& pp = m_preset_bundle->physical_printers.get_selected_printer();
    std::string host = pp.config.opt_string("print_host");
    assert(!host.empty());
    wxGetApp().open_browser_with_warning_dialog(host);
}
References Slic3r::PhysicalPrinter::config, Slic3r::PhysicalPrinterCollection::get_selected_printer(), Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::ConfigBase::opt_string(), and Slic3r::PresetBundle::physical_printers.
Referenced by Slic3r::GUI::PlaterPresetComboBox::show_edit_menu().
presets()
PresetCollection * Slic3r::GUI::TabPresetComboBox::presets () const inline
{ return m_collection; }
References Slic3r::GUI::PresetComboBox::m_collection.
Referenced by update().
selection_is_changed_according_to_physical_printers()
bool Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers () inherited
{
    if (m_type != Preset::TYPE_PRINTER)
        return false;
    const std::string           selected_string     = into_u8(this->GetString(this->GetSelection()));
    PhysicalPrinterCollection&  physical_printers   = m_preset_bundle->physical_printers;
    Tab*                        tab                 = wxGetApp().get_tab(Preset::TYPE_PRINTER);
    if (!is_selected_physical_printer()) {
        if (!physical_printers.has_selection())
            return false;
        const bool is_changed = selected_string == physical_printers.get_selected_printer_preset_name();
        physical_printers.unselect_printer();
        if (is_changed)
            tab->select_preset(selected_string);
        return is_changed;
    }
    std::string old_printer_full_name, old_printer_preset;
    if (physical_printers.has_selection()) {
        old_printer_full_name = physical_printers.get_selected_full_printer_name();
        old_printer_preset = physical_printers.get_selected_printer_preset_name();
    }
    else
        old_printer_preset = m_collection->get_edited_preset().name;
    // Select related printer preset on the Printer Settings Tab
    physical_printers.select_printer(selected_string);
    std::string preset_name = physical_printers.get_selected_printer_preset_name();
    // if new preset wasn't selected, there is no need to call update preset selection
    if (old_printer_preset == preset_name) {
        tab->update_preset_choice();
        // update action buttons to show/hide "Send to" button
        wxGetApp().plater()->show_action_buttons();
        // we need just to update according Plater<->Tab PresetComboBox
        if (dynamic_cast<PlaterPresetComboBox*>(this)!=nullptr) {
            // Synchronize config.ini with the current selections.
            m_preset_bundle->export_selections(*wxGetApp().app_config);
            this->update();
        }
        else if (dynamic_cast<TabPresetComboBox*>(this)!=nullptr)
            wxGetApp().sidebar().update_presets(m_type);
        return true;
    }
    if (tab)
        tab->select_preset(preset_name, false, old_printer_full_name);
    return true;
}
References Slic3r::PresetBundle::export_selections(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PhysicalPrinterCollection::get_selected_full_printer_name(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::GUI::into_u8(), Slic3r::GUI::PresetComboBox::is_selected_physical_printer(), Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::Preset::name, Slic3r::PresetBundle::physical_printers, Slic3r::GUI::Tab::select_preset(), Slic3r::PhysicalPrinterCollection::select_printer(), Slic3r::Preset::TYPE_PRINTER, Slic3r::PhysicalPrinterCollection::unselect_printer(), Slic3r::GUI::PresetComboBox::update(), and Slic3r::GUI::Tab::update_preset_choice().
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Plater::priv::on_select_preset().
separator()
wxString Slic3r::GUI::PresetComboBox::separator (const std::string & label) static protected inherited
{
    return wxString::FromUTF8(separator_head()) + _(label) + wxString::FromUTF8(separator_tail());
}
References _, Slic3r::GUI::PresetComboBox::separator_head(), and Slic3r::GUI::PresetComboBox::separator_tail().
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
separator_head()
static const char * Slic3r::GUI::PresetComboBox::separator_head () inline static protected inherited
{ return " "; }
Referenced by Slic3r::GUI::PresetComboBox::separator().
separator_tail()
static const char * Slic3r::GUI::PresetComboBox::separator_tail () inline static protected inherited
{ return " "; }
Referenced by Slic3r::GUI::PresetComboBox::separator().
set_active_extruder()
void Slic3r::GUI::TabPresetComboBox::set_active_extruder (int extruder_idx) inline
{ m_active_extruder_idx = extruder_idx; }
References m_active_extruder_idx.
set_enable_all()
void Slic3r::GUI::TabPresetComboBox::set_enable_all (bool enable = true) inline
{ m_enable_all = enable; }
References m_enable_all.
set_label_marker()
void Slic3r::GUI::PresetComboBox::set_label_marker (int item, LabelItemType label_item_type = LABEL_ITEM_MARKER) inherited
{
    this->SetClientData(item, (void*)label_item_type);
}
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
set_printer_technology()
bool Slic3r::GUI::PresetComboBox::set_printer_technology (PrinterTechnology pt) inherited
{
    if (printer_technology != pt) {
        printer_technology = pt;
        return true;
    }
    return false;
}
References Slic3r::GUI::PresetComboBox::printer_technology.
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter(), Slic3r::GUI::PresetForPrinter::AllowDelete(), and Slic3r::GUI::PresetForPrinter::SuppressDelete().
set_selection_changed_function()
void Slic3r::GUI::PresetComboBox::set_selection_changed_function (std::function< void(int)> sel_changed) inline inherited
{ on_selection_changed = sel_changed; }
References Slic3r::GUI::PresetComboBox::on_selection_changed.
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter(), Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::DiffPresetDialog::create_presets_sizer().
set_show_incompatible_presets()
void Slic3r::GUI::TabPresetComboBox::set_show_incompatible_presets (bool show_incompatible_presets) inline
{
        show_incompatible = show_incompatible_presets;
    }
References show_incompatible.
show_all()
void Slic3r::GUI::PresetComboBox::show_all (bool show_all) inherited
{
    m_show_all = show_all;
    update();
}
References Slic3r::GUI::PresetComboBox::m_show_all, Slic3r::GUI::PresetComboBox::show_all(), and Slic3r::GUI::PresetComboBox::update().
Referenced by Slic3r::GUI::PresetComboBox::show_all().
show_modif_preset_separately()
void Slic3r::GUI::PresetComboBox::show_modif_preset_separately () inline inherited
{ m_show_modif_preset_separately = true; }
References Slic3r::GUI::PresetComboBox::m_show_modif_preset_separately.
Referenced by Slic3r::GUI::DiffPresetDialog::create_presets_sizer().
sys_color_changed()
void Slic3r::GUI::PresetComboBox::sys_color_changed () virtual inherited
Reimplemented in Slic3r::GUI::PlaterPresetComboBox.
{
    m_bitmapCompatible = get_bmp_bundle("flag_green");
    m_bitmapIncompatible = get_bmp_bundle("flag_red");
    wxGetApp().UpdateDarkUI(this);
    // update the control to redraw the icons
    update();
}
References get_bmp_bundle(), Slic3r::GUI::PresetComboBox::m_bitmapCompatible, Slic3r::GUI::PresetComboBox::m_bitmapIncompatible, and Slic3r::GUI::PresetComboBox::update().
Referenced by Slic3r::GUI::PresetForPrinter::on_sys_color_changed(), and Slic3r::GUI::PlaterPresetComboBox::sys_color_changed().
type()
Preset::Type Slic3r::GUI::TabPresetComboBox::type () const inline
{ return m_type; }
References Slic3r::GUI::PresetComboBox::m_type.
update() [1/2]
void Slic3r::GUI::TabPresetComboBox::update () override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    Freeze();
    Clear();
    invalidate_selection();
    const ExtruderFilaments& extruder_filaments = m_preset_bundle->extruders_filaments[m_active_extruder_idx];
    const std::deque<Preset>& presets = m_collection->get_presets();
    struct PresetData {
        wxString        name;
        wxString        lower_name;
        wxBitmapBundle* bitmap;
        bool            enabled;
    };
    std::vector<PresetData> system_presets;
    std::vector<PresetData> nonsys_presets;
    std::vector<PresetData> template_presets;
    const bool allow_templates = !wxGetApp().app_config->get_bool("no_templates");
    wxString selected = "";
    if (!presets.front().is_visible)
        set_label_marker(Append(separator(L("System presets")), NullBitmapBndl()));
    size_t idx_selected = m_type == Preset::TYPE_FILAMENT ? extruder_filaments.get_selected_idx() : m_collection->get_selected_idx();
    if (m_type == Preset::TYPE_PRINTER && m_preset_bundle->physical_printers.has_selection()) {
        std::string sel_preset_name = m_preset_bundle->physical_printers.get_selected_printer_preset_name();
        Preset* preset = m_collection->find_preset(sel_preset_name);
        if (!preset)
            m_preset_bundle->physical_printers.unselect_printer();
    }
    for (size_t i = presets.front().is_visible ? 0 : m_collection->num_default_presets(); i < presets.size(); ++i)
    {
        const Preset& preset = presets[i];
        const bool is_compatible = m_type == Preset::TYPE_FILAMENT ? extruder_filaments.filament(i).is_compatible : preset.is_compatible;
        if (!preset.is_visible || (!show_incompatible && !is_compatible && i != idx_selected))
            continue;
        // marker used for disable incompatible printer models for the selected physical printer
        bool is_enabled = true;
        std::string bitmap_key = "tab";
        if (m_type == Preset::TYPE_PRINTER) {
            bitmap_key += "_printer";
            if (preset.printer_technology() == ptSLA)
                bitmap_key += "_sla";
        }
        std::string main_icon_name = m_type == Preset::TYPE_PRINTER && preset.printer_technology() == ptSLA ? "sla_printer" : m_main_bitmap_name;
        auto bmp = get_bmp(bitmap_key, main_icon_name, "lock_closed", is_enabled, is_compatible, preset.is_system || preset.is_default);
        assert(bmp);
        if (preset.is_default || preset.is_system) {
            if (preset.vendor && preset.vendor->templates_profile) {
                if (allow_templates) {
                    template_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp, is_enabled});
                    if (i == idx_selected)
                        selected = get_preset_name(preset);
                }
            } else {
                system_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp, is_enabled});
                if (i == idx_selected)
                    selected = get_preset_name(preset);
            }
        }
        else
        {
            std::pair<wxBitmapBundle*, bool> pair(bmp, is_enabled);
            nonsys_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp, is_enabled});
            if (i == idx_selected)
                selected = get_preset_name(preset);
        }
        if (i + 1 == m_collection->num_default_presets())
            set_label_marker(Append(separator(L("System presets")), NullBitmapBndl()));
    }
    if (!system_presets.empty())
    {
        std::sort(system_presets.begin(), system_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        for (std::vector<PresetData>::iterator it = system_presets.begin(); it != system_presets.end(); ++it) {
            int item_id = Append(it->name, *it->bitmap);
            if (!it->enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->name == selected);
        }
    }
    if (!nonsys_presets.empty())
    {
        std::sort(nonsys_presets.begin(), nonsys_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        set_label_marker(Append(separator(L("User presets")), NullBitmapBndl()));
        for (std::vector<PresetData>::iterator it = nonsys_presets.begin(); it != nonsys_presets.end(); ++it) {
            int item_id = Append(it->name, *it->bitmap);
            if (!it->enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->name == selected);
        }
    }
    if (!template_presets.empty())
    {
        std::sort(template_presets.begin(), template_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        set_label_marker(Append(separator(L("Template presets")), wxNullBitmap));
        for (std::vector<PresetData>::iterator it = template_presets.begin(); it != template_presets.end(); ++it) {
            int item_id = Append(it->name, *it->bitmap);
            if (!it->enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->name == selected);
        }
    }
    if (m_type == Preset::TYPE_PRINTER)
    {
        // add Physical printers, if any exists
        if (!m_preset_bundle->physical_printers.empty()) {
            set_label_marker(Append(separator(L("Physical printers")), NullBitmapBndl()));
            const PhysicalPrinterCollection& ph_printers = m_preset_bundle->physical_printers;
            // Sort Physical printers in preset_data vector and than Append it in correct order
            struct PhysicalPrinterPresetData
            {
                wxString lower_name; // just for sorting
                std::string name; // preset_name
                std::string fullname; // full name
                bool selected; // is selected
            };
            std::vector<PhysicalPrinterPresetData> preset_data;
            for (PhysicalPrinterCollection::ConstIterator it = ph_printers.begin(); it != ph_printers.end(); ++it) {
                for (const std::string& preset_name : it->get_preset_names()) {
                    preset_data.push_back({wxString::FromUTF8(it->get_full_name(preset_name)).Lower(), preset_name, it->get_full_name(preset_name), ph_printers.is_selected(it, preset_name)});
                }
            }
            std::sort(preset_data.begin(), preset_data.end(), [](const PhysicalPrinterPresetData& a, const PhysicalPrinterPresetData& b) {
                return a.lower_name < b.lower_name;
                });
            for (const PhysicalPrinterPresetData& data : preset_data)
            {
                Preset* preset = m_collection->find_preset(data.name);
                if (!preset || !preset->is_visible)
                    continue;
                std::string main_icon_name = preset->printer_technology() == ptSLA ? "sla_printer" : m_main_bitmap_name;
                auto bmp = get_bmp(main_icon_name, main_icon_name, "", true, true, false);
                assert(bmp);
                set_label_marker(Append(from_u8(data.fullname + suffix(preset)), *bmp), LABEL_ITEM_PHYSICAL_PRINTER);
                validate_selection(data.selected);
            }
        }
        // add "Add/Remove printers" item
        std::string icon_name = "edit_uni";
        auto bmp = get_bmp("edit_preset_list, tab,", icon_name, "");
        assert(bmp);
        set_label_marker(Append(separator(L("Add/Remove printers")), *bmp), LABEL_ITEM_WIZARD_PRINTERS);
    }
    update_selection();
    Thaw();
}
References Slic3r::GUI::BitmapComboBox::Append(), Slic3r::PhysicalPrinterCollection::begin(), Slic3r::PhysicalPrinterCollection::empty(), Slic3r::PhysicalPrinterCollection::end(), Slic3r::PresetBundle::extruders_filaments, Slic3r::ExtruderFilaments::filament(), Slic3r::PresetCollection::find_preset(), Slic3r::GUI::from_u8(), Slic3r::GUI::PresetComboBox::get_bmp(), get_preset_name(), Slic3r::PresetCollection::get_presets(), Slic3r::PresetCollection::get_selected_idx(), Slic3r::ExtruderFilaments::get_selected_idx(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::GUI::PresetComboBox::invalidate_selection(), Slic3r::Preset::is_compatible, Slic3r::Filament::is_compatible, Slic3r::Preset::is_default, Slic3r::PhysicalPrinterCollection::is_selected(), Slic3r::Preset::is_system, Slic3r::Preset::is_visible, L, Slic3r::GUI::PresetComboBox::LABEL_ITEM_DISABLED, Slic3r::GUI::PresetComboBox::LABEL_ITEM_PHYSICAL_PRINTER, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_PRINTERS, m_active_extruder_idx, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_main_bitmap_name, Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::GUI::PresetComboBox::NullBitmapBndl(), Slic3r::PresetCollection::num_default_presets(), Slic3r::PresetBundle::physical_printers, presets(), Slic3r::Preset::printer_technology(), Slic3r::ptSLA, Slic3r::GUI::PresetComboBox::separator(), Slic3r::GUI::PresetComboBox::set_label_marker(), show_incompatible, Slic3r::PresetCollection::size(), Slic3r::GUI::suffix(), Slic3r::VendorProfile::templates_profile, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINTER, Slic3r::PhysicalPrinterCollection::unselect_printer(), Slic3r::GUI::PresetComboBox::update_selection(), Slic3r::GUI::PresetComboBox::validate_selection(), and Slic3r::Preset::vendor.
Referenced by OnSelect().
update() [2/2]
void Slic3r::GUI::PresetComboBox::update (std::string select_preset) inherited
{
    Freeze();
    Clear();
    invalidate_selection();
    const std::deque<Preset>& presets = m_collection->get_presets();
    struct PresetData {
        wxString        name;
        wxString        lower_name;
        wxBitmapBundle* bitmap;
        bool            enabled; // not used in incomp_presets
    };
    std::vector<PresetData> system_presets;
    std::vector<PresetData> nonsys_presets;
    std::vector<PresetData> incomp_presets;
    wxString selected = "";
    if (!presets.front().is_visible)
        set_label_marker(Append(separator(L("System presets")), NullBitmapBndl()));
    for (size_t i = presets.front().is_visible ? 0 : m_collection->num_default_presets(); i < presets.size(); ++i)
    {
        const Preset& preset = presets[i];
        if (!m_show_all && (!preset.is_visible || !preset.is_compatible))
            continue;
        // marker used for disable incompatible printer models for the selected physical printer
        bool is_enabled = m_type == Preset::TYPE_PRINTER && printer_technology != ptAny ? preset.printer_technology() == printer_technology : true;
        if (select_preset_name.empty() && is_enabled)
            select_preset_name = preset.name;
        std::string   bitmap_key = "cb";
        if (m_type == Preset::TYPE_PRINTER) {
            bitmap_key += "_printer";
            if (preset.printer_technology() == ptSLA)
                bitmap_key += "_sla";
        }
        std::string main_icon_name = m_type == Preset::TYPE_PRINTER && preset.printer_technology() == ptSLA ? "sla_printer" : m_main_bitmap_name;
        auto bmp = get_bmp(bitmap_key, main_icon_name, "lock_closed", is_enabled, preset.is_compatible, preset.is_system || preset.is_default);
        assert(bmp);
        if (!is_enabled) {
            incomp_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp, false});
            if (preset.is_dirty && m_show_modif_preset_separately)
                incomp_presets.push_back({get_preset_name_with_suffix(preset), get_preset_name_with_suffix(preset).Lower(), bmp, false});
        }
        else if (preset.is_default || preset.is_system)
        {
            system_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp, is_enabled});
            if (preset.name == select_preset_name)
                selected = preset.name;
            if (preset.is_dirty && m_show_modif_preset_separately) {
                wxString preset_name = get_preset_name_with_suffix(preset);
                system_presets.push_back({preset_name, preset_name.Lower(), bmp, is_enabled});
                if (into_u8(preset_name) == select_preset_name)
                    selected = preset_name;
            }
        }
        else
        {
            nonsys_presets.push_back({get_preset_name(preset), get_preset_name(preset).Lower(), bmp, is_enabled});
            if (preset.name == select_preset_name || (select_preset_name.empty() && is_enabled))
                selected = get_preset_name(preset);
            if (preset.is_dirty && m_show_modif_preset_separately) {
                wxString preset_name = get_preset_name_with_suffix(preset);
                nonsys_presets.push_back({preset_name, preset_name.Lower(), bmp, is_enabled});
                if (preset_name == select_preset_name || (select_preset_name.empty() && is_enabled))
                    selected = preset_name;
            }
        }
        if (i + 1 == m_collection->num_default_presets())
            set_label_marker(Append(separator(L("System presets")), NullBitmapBndl()));
    }
    if (!system_presets.empty())
    {
        std::sort(system_presets.begin(), system_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        for (std::vector<PresetData>::iterator it = system_presets.begin(); it != system_presets.end(); ++it) {
            int item_id = Append(it->name, *it->bitmap);
            if (!it->enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->name == selected);
        }
    }
    if (!nonsys_presets.empty())
    {
        std::sort(nonsys_presets.begin(), nonsys_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        set_label_marker(Append(separator(L("User presets")), NullBitmapBndl()));
        for (std::vector<PresetData>::iterator it = nonsys_presets.begin(); it != nonsys_presets.end(); ++it) {
            int item_id = Append(it->name, *it->bitmap);
            if (!it->enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->name == selected);
        }
    }
    if (!incomp_presets.empty())
    {
        std::sort(incomp_presets.begin(), incomp_presets.end(), [](const PresetData& a, const PresetData& b) {
            return a.lower_name < b.lower_name;
            });
        set_label_marker(Append(separator(L("Incompatible presets")), NullBitmapBndl()));
        for (std::vector<PresetData>  ::iterator it = incomp_presets.begin(); it != incomp_presets.end(); ++it) {
            set_label_marker(Append(it->name, *it->bitmap), LABEL_ITEM_DISABLED);
        }
    }
    update_selection();
    Thaw();
}
References Slic3r::GUI::BitmapComboBox::Append(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_preset_name(), Slic3r::GUI::get_preset_name_with_suffix(), Slic3r::PresetCollection::get_presets(), Slic3r::GUI::into_u8(), Slic3r::GUI::PresetComboBox::invalidate_selection(), Slic3r::Preset::is_compatible, Slic3r::Preset::is_default, Slic3r::Preset::is_dirty, Slic3r::Preset::is_system, Slic3r::Preset::is_visible, L, Slic3r::GUI::PresetComboBox::LABEL_ITEM_DISABLED, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_main_bitmap_name, Slic3r::GUI::PresetComboBox::m_show_all, Slic3r::GUI::PresetComboBox::m_show_modif_preset_separately, Slic3r::GUI::PresetComboBox::m_type, Slic3r::Preset::name, Slic3r::GUI::PresetComboBox::NullBitmapBndl(), Slic3r::PresetCollection::num_default_presets(), Slic3r::Preset::printer_technology(), Slic3r::GUI::PresetComboBox::printer_technology, Slic3r::ptAny, Slic3r::ptSLA, Slic3r::GUI::PresetComboBox::separator(), Slic3r::GUI::PresetComboBox::set_label_marker(), Slic3r::Preset::TYPE_PRINTER, Slic3r::GUI::PresetComboBox::update_selection(), and Slic3r::GUI::PresetComboBox::validate_selection().
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter(), Slic3r::GUI::PresetForPrinter::AllowDelete(), Slic3r::GUI::DiffPresetDialog::create_presets_sizer(), Slic3r::GUI::PresetForPrinter::SuppressDelete(), and Slic3r::GUI::DiffPresetDialog::update_compatibility().
update_dirty()
void Slic3r::GUI::TabPresetComboBox::update_dirty ()
{
    // 1) Update the dirty flag of the current preset.
    m_collection->update_dirty();
    // 2) Update the labels.
    wxWindowUpdateLocker noUpdates(this);
    for (unsigned int ui_id = 0; ui_id < GetCount(); ++ui_id) {
        auto marker = reinterpret_cast<Marker>(this->GetClientData(ui_id));
        if (marker >= LABEL_ITEM_MARKER)
            continue;
        std::string   old_label = GetString(ui_id).utf8_str().data();
        std::string   preset_name = Preset::remove_suffix_modified(old_label);
        std::string   ph_printer_name;
        if (marker == LABEL_ITEM_PHYSICAL_PRINTER) {
            ph_printer_name = PhysicalPrinter::get_short_name(preset_name);
            preset_name = PhysicalPrinter::get_preset_name(preset_name);
        }
        Preset* preset = m_collection->find_preset(preset_name, false);
        if (preset) {
            std::string new_label = preset->name + suffix(preset);
            if (marker == LABEL_ITEM_PHYSICAL_PRINTER)
                new_label = ph_printer_name + PhysicalPrinter::separator() + new_label;
            if (old_label != new_label)
                SetString(ui_id, from_u8(new_label));
        }
    }
#ifdef __APPLE__
    // wxWidgets on OSX do not upload the text of the combo box line automatically.
    // Force it to update by re-selecting.
    SetSelection(GetSelection());
#endif /* __APPLE __ */
}
References Slic3r::PresetCollection::find_preset(), Slic3r::GUI::from_u8(), Slic3r::PhysicalPrinter::get_preset_name(), Slic3r::PhysicalPrinter::get_short_name(), Slic3r::GUI::PresetComboBox::LABEL_ITEM_MARKER, Slic3r::GUI::PresetComboBox::LABEL_ITEM_PHYSICAL_PRINTER, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::Preset::name, Slic3r::Preset::remove_suffix_modified(), Slic3r::PhysicalPrinter::separator(), Slic3r::GUI::suffix(), and Slic3r::PresetCollection::update_dirty().
update_from_bundle()
void Slic3r::GUI::PresetComboBox::update_from_bundle () inherited
{
    this->update(m_collection->get_selected_preset().name);
}
References Slic3r::PresetCollection::get_selected_preset(), Slic3r::GUI::PresetComboBox::m_collection, Slic3r::Preset::name, and Slic3r::GUI::PresetComboBox::update().
update_selection()
void Slic3r::GUI::PresetComboBox::update_selection () protected inherited
{
    /* If selected_preset_item is still equal to INT_MAX, it means that
     * there is no presets added to the list.
     * So, select last combobox item ("Add/Remove preset")
     */
    validate_selection();
    SetSelection(m_last_selected);
#ifdef __WXMSW__
    // From the Windows 2004 the tooltip for preset combobox doesn't work after next call of SetTooltip()
    // (There was an issue, when tooltip doesn't appears after changing of the preset selection)
    // But this workaround seems to work: We should to kill tooltip and than set new tooltip value
    SetToolTip(NULL);
#endif
    SetToolTip(GetString(m_last_selected));
// A workaround for a set of issues related to text fitting into gtk widgets:
// See e.g.: https://github.com/prusa3d/PrusaSlicer/issues/4584
#if defined(__WXGTK20__) || defined(__WXGTK3__)
    GList* cells = gtk_cell_layout_get_cells(GTK_CELL_LAYOUT(m_widget));
    // 'cells' contains the GtkCellRendererPixBuf for the icon,
    // 'cells->next' contains GtkCellRendererText for the text we need to ellipsize
    if (!cells || !cells->next) return;
    auto cell = static_cast<GtkCellRendererText *>(cells->next->data);
    if (!cell) return;
    g_object_set(G_OBJECT(cell), "ellipsize", PANGO_ELLIPSIZE_END, (char*)NULL);
    // Only the list of cells must be freed, the renderer isn't ours to free
    g_list_free(cells);
#endif
}
References Slic3r::GUI::PresetComboBox::m_last_selected, and Slic3r::GUI::PresetComboBox::validate_selection().
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
validate_selection()
void Slic3r::GUI::PresetComboBox::validate_selection (bool predicate = false) protected inherited
{
    if (predicate ||
        // just in case: mark m_last_selected as a first added element
        m_last_selected == INT_MAX)
        m_last_selected = GetCount() - 1;
}
References Slic3r::GUI::PresetComboBox::m_last_selected.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), Slic3r::GUI::PresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update_selection().
Member Data Documentation
icon_height
int Slic3r::GUI::PresetComboBox::icon_height protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::NullBitmapBndl().
m_active_extruder_idx
int Slic3r::GUI::TabPresetComboBox::m_active_extruder_idx {0} private
Referenced by set_active_extruder(), and update().
m_bitmapCompatible
wxBitmapBundle* Slic3r::GUI::PresetComboBox::m_bitmapCompatible protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::sys_color_changed().
m_bitmapIncompatible
wxBitmapBundle* Slic3r::GUI::PresetComboBox::m_bitmapIncompatible protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::sys_color_changed().
m_collection
PresetCollection* Slic3r::GUI::PresetComboBox::m_collection {nullptr} protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::OnSelect(), Slic3r::GUI::PlaterPresetComboBox::OnSelect(), OnSelect(), presets(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::update(), update(), Slic3r::GUI::PresetComboBox::update(), update_dirty(), and Slic3r::GUI::PresetComboBox::update_from_bundle().
m_em_unit
int Slic3r::GUI::PresetComboBox::m_em_unit protected inherited
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::msw_rescale(), Slic3r::GUI::PlaterPresetComboBox::msw_rescale(), msw_rescale(), and Slic3r::GUI::PlaterPresetComboBox::update().
m_enable_all
bool Slic3r::GUI::TabPresetComboBox::m_enable_all {false} private
Referenced by set_enable_all().
m_last_selected
int Slic3r::GUI::PresetComboBox::m_last_selected protected inherited
Referenced by Slic3r::GUI::PresetComboBox::invalidate_selection(), Slic3r::GUI::PresetComboBox::OnSelect(), Slic3r::GUI::PlaterPresetComboBox::OnSelect(), OnSelect(), Slic3r::GUI::PresetComboBox::update_selection(), and Slic3r::GUI::PresetComboBox::validate_selection().
m_main_bitmap_name
std::string Slic3r::GUI::PresetComboBox::m_main_bitmap_name protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
m_preset_bundle
PresetBundle* Slic3r::GUI::PresetComboBox::m_preset_bundle {nullptr} protected inherited
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::del_physical_printer(), Slic3r::GUI::PresetComboBox::edit_physical_printer(), Slic3r::GUI::PlaterPresetComboBox::get_selected_ph_printer_name(), Slic3r::GUI::PresetComboBox::open_physical_printer_url(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::show_edit_menu(), Slic3r::GUI::PlaterPresetComboBox::update(), and update().
m_show_all
bool Slic3r::GUI::PresetComboBox::m_show_all { false } private inherited
Referenced by Slic3r::GUI::PresetComboBox::show_all(), and Slic3r::GUI::PresetComboBox::update().
m_show_modif_preset_separately
bool Slic3r::GUI::PresetComboBox::m_show_modif_preset_separately { false } private inherited
Referenced by Slic3r::GUI::PresetComboBox::show_modif_preset_separately(), and Slic3r::GUI::PresetComboBox::update().
m_suppress_change
bool Slic3r::GUI::PresetComboBox::m_suppress_change { true } protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox().
m_type
Preset::Type Slic3r::GUI::PresetComboBox::m_type protected inherited
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::del_physical_printer(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PlaterPresetComboBox::get_selected_ph_printer_name(), Slic3r::GUI::PresetComboBox::get_type(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::show_edit_menu(), Slic3r::GUI::PlaterPresetComboBox::switch_to_tab(), type(), Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
norm_icon_width
int Slic3r::GUI::PresetComboBox::norm_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PlaterPresetComboBox::update().
null_icon_width
int Slic3r::GUI::PresetComboBox::null_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::NullBitmapBndl(), and Slic3r::GUI::PlaterPresetComboBox::update().
on_selection_changed
std::function<void(int)> Slic3r::GUI::PresetComboBox::on_selection_changed { nullptr } protected inherited
Referenced by Slic3r::GUI::PresetComboBox::OnSelect(), OnSelect(), and Slic3r::GUI::PresetComboBox::set_selection_changed_function().
printer_technology
PrinterTechnology Slic3r::GUI::PresetComboBox::printer_technology {ptAny} protected inherited
Referenced by Slic3r::GUI::PresetComboBox::set_printer_technology(), and Slic3r::GUI::PresetComboBox::update().
show_incompatible
bool Slic3r::GUI::TabPresetComboBox::show_incompatible {false} private
Referenced by set_show_incompatible_presets(), and update().
space_icon_width
int Slic3r::GUI::PresetComboBox::space_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
thin_icon_width
int Slic3r::GUI::PresetComboBox::thin_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
thin_space_icon_width
int Slic3r::GUI::PresetComboBox::thin_space_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PlaterPresetComboBox::update().
wide_icon_width
int Slic3r::GUI::PresetComboBox::wide_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
wide_space_icon_width
int Slic3r::GUI::PresetComboBox::wide_space_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PlaterPresetComboBox::update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/PresetComboBoxes.hpp
src/slic3r/GUI/PresetComboBoxes.cpp