Prusa Slicer: Slic3r::GUI::GUI_App Class Reference
Slic3r::GUI::GUI_App Class Reference
#include <src/slic3r/GUI/GUI_App.hpp>
Public Types
enum class EAppMode : unsigned char { Editor , GCodeViewer }
Public Member Functions
bool OnInit () override
bool initialized () const
GUI_App (EAppMode mode=EAppMode::Editor)
~GUI_App () override
EAppMode get_app_mode () const
bool is_editor () const
bool is_gcode_viewer () const
bool is_recreating_gui () const
std::string logo_name () const
void post_init ()
wxGLContext * init_glcontext (wxGLCanvas &canvas)
bool init_opengl ()
const wxColour get_label_default_clr_system ()
const wxColour get_label_default_clr_modified ()
const std::vector< std::string > get_mode_default_palette ()
void init_ui_colours ()
void update_ui_colours_from_appconfig ()
void update_label_colours ()
void UpdateDarkUI (wxWindow *window, bool highlited=false, bool just_font=false)
void UpdateDlgDarkUI (wxDialog *dlg, bool just_buttons_update=false)
void UpdateDVCDarkUI (wxDataViewCtrl *dvc, bool highlited=false)
void UpdateAllStaticTextDarkUI (wxWindow *parent)
void init_fonts ()
void update_fonts (const MainFrame *main_frame=nullptr)
void set_label_clr_modified (const wxColour &clr)
void set_label_clr_sys (const wxColour &clr)
const wxColour & get_label_clr_modified ()
const wxColour & get_label_clr_sys ()
const wxColour & get_label_clr_default ()
const wxColour & get_window_default_clr ()
const std::string & get_mode_btn_color (int mode_id)
std::vector< wxColour > get_mode_palette ()
void set_mode_palette (const std::vector< wxColour > &palette)
const wxFont & small_font ()
const wxFont & bold_font ()
const wxFont & normal_font ()
const wxFont & code_font ()
const wxFont & link_font ()
int em_unit () const
bool tabs_as_menu () const
wxSize get_min_size () const
float toolbar_icon_scale (const bool is_limited=false) const
void set_auto_toolbar_icon_scale (float scale) const
void check_printer_presets ()
void recreate_GUI (const wxString &message)
void system_info ()
void keyboard_shortcuts ()
void load_project (wxWindow *parent, wxString &input_file) const
void import_model (wxWindow *parent, wxArrayString &input_files) const
void import_zip (wxWindow *parent, wxString &input_file) const
void load_gcode (wxWindow *parent, wxString &input_file) const
void persist_window_geometry (wxTopLevelWindow *window, bool default_maximized=false)
void update_ui_from_settings ()
bool switch_language ()
bool load_language (wxString language, bool initial)
Tab * get_tab (Preset::Type type)
ConfigOptionMode get_mode ()
bool save_mode (const int mode)
void update_mode ()
void add_config_menu (wxMenuBar *menu)
bool has_unsaved_preset_changes () const
bool has_current_preset_changes () const
void update_saved_preset_from_current_preset ()
std::vector< const PresetCollection * > get_active_preset_collections () const
bool check_and_save_current_preset_changes (const wxString &caption, const wxString &header, bool remember_choice=true, bool use_dont_save_insted_of_discard=false)
void apply_keeped_preset_modifications ()
bool check_and_keep_current_preset_changes (const wxString &caption, const wxString &header, int action_buttons, bool *postponed_apply_of_keeped_changes=nullptr)
bool can_load_project ()
bool check_print_host_queue ()
bool checked_tab (Tab *tab)
void load_current_presets (bool check_printer_presets=true)
wxString current_language_code () const
wxString current_language_code_safe () const
bool is_localized () const
void open_preferences (const std::string &highlight_option=std::string(), const std::string &tab_name=std::string())
virtual bool OnExceptionInMainLoop () override
bool open_browser_with_warning_dialog (const wxString &url, wxWindow *parent=nullptr, bool force_remember_choice=true, int flags=0)
Sidebar & sidebar ()
ObjectManipulation * obj_manipul ()
ObjectSettings * obj_settings ()
ObjectList * obj_list ()
ObjectLayers * obj_layers ()
Plater * plater ()
const Plater * plater () const
Model & model ()
NotificationManager * notification_manager ()
GalleryDialog * gallery_dialog ()
Downloader * downloader ()
PresetUpdater * get_preset_updater ()
wxBookCtrlBase * tab_panel () const
int extruders_cnt () const
int extruders_edited_cnt () const
RemovableDriveManager * removable_drive_manager ()
OtherInstanceMessageHandler * other_instance_message_handler ()
wxSingleInstanceChecker * single_instance_checker ()
void init_single_instance_checker (const std::string &name, const std::string &path)
void set_instance_hash (const size_t hash)
std::string get_instance_hash_string ()
size_t get_instance_hash_int ()
ImGuiWrapper * imgui ()
PrintHostJobQueue & printhost_job_queue ()
void open_web_page_localized (const std::string &http_address)
bool may_switch_to_SLA_preset (const wxString &caption)
bool run_wizard (ConfigWizard::RunReason reason, ConfigWizard::StartPage start_page=ConfigWizard::SP_WELCOME)
void show_desktop_integration_dialog ()
void show_downloader_registration_dialog ()
GLShaderProgram * get_shader (const std::string &shader_name)
GLShaderProgram * get_current_shader ()
bool is_gl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
bool is_glsl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
int GetSingleChoiceIndex (const wxString &message, const wxString &caption, const wxArrayString &choices, int initialSelection)
void start_download (std::string url)
Static Public Member Functions
static std::string get_gl_info (bool for_github)
static unsigned get_colour_approx_luma (const wxColour &colour)
static bool dark_mode ()
static bool catch_error (std::function< void()> cb, const std::string &err)
Public Attributes
GUI_InitParams * init_params { nullptr }
AppConfig * app_config { nullptr }
PresetBundle * preset_bundle { nullptr }
PresetUpdater * preset_updater { nullptr }
MainFrame * mainframe { nullptr }
Plater * plater_ { nullptr }
std::vector< Tab * > tabs_list
Private Member Functions
bool on_init_inner ()
void init_app_config ()
std::string check_older_app_config (Semver current_version, bool backup)
void window_pos_save (wxTopLevelWindow *window, const std::string &name)
void window_pos_restore (wxTopLevelWindow *window, const std::string &name, bool default_maximized=false)
void window_pos_sanitize (wxTopLevelWindow *window)
bool select_language ()
bool config_wizard_startup ()
bool check_updates (const bool verbose)
void on_version_read (wxCommandEvent &evt)
void app_updater (bool from_user)
void app_version_check (bool from_user)
Private Attributes
bool m_initialized { false }
bool m_post_initialized { false }
bool m_app_conf_exists { false }
bool m_last_app_conf_lower_version { false }
EAppMode m_app_mode { EAppMode::Editor }
bool m_is_recreating_gui { false }
bool m_opengl_initialized { false }
wxColour m_color_label_modified
wxColour m_color_label_sys
wxColour m_color_label_default
wxColour m_color_window_default
std::vector< std::string > m_mode_palette
wxFont m_small_font
wxFont m_bold_font
wxFont m_normal_font
wxFont m_code_font
wxFont m_link_font
int m_em_unit
std::unique_ptr< wxLocale > m_wxLocale
const wxLanguageInfo * m_language_info_system = nullptr
const wxLanguageInfo * m_language_info_best = nullptr
OpenGLManager m_opengl_mgr
std::unique_ptr< RemovableDriveManager > m_removable_drive_manager
std::unique_ptr< ImGuiWrapper > m_imgui
std::unique_ptr< PrintHostJobQueue > m_printhost_job_queue
std::unique_ptr< OtherInstanceMessageHandler > m_other_instance_message_handler
std::unique_ptr< AppUpdater > m_app_updater
std::unique_ptr< wxSingleInstanceChecker > m_single_instance_checker
std::unique_ptr< Downloader > m_downloader
std::string m_instance_hash_string
size_t m_instance_hash_int
bool m_datadir_redefined { false }
Detailed Description
Member Enumeration Documentation
EAppMode
enum class Slic3r::GUI::GUI_App::EAppMode : unsigned char strong
Enumerator
Editor
GCodeViewer
    {
        Editor,
        GCodeViewer
    };
Constructor & Destructor Documentation
GUI_App()
Slic3r::GUI::GUI_App::GUI_App (EAppMode mode = EAppMode::Editor) explicit
    : wxApp()
    , m_app_mode(mode)
    , m_em_unit(10)
    , m_imgui(new ImGuiWrapper())
  , m_removable_drive_manager(std::make_unique<RemovableDriveManager>())
  , m_other_instance_message_handler(std::make_unique<OtherInstanceMessageHandler>())
    , m_downloader(std::make_unique<Downloader>())
{
  //app config initializes early becasuse it is used in instance checking in PrusaSlicer.cpp
  this->init_app_config();
    // init app downloader after path to datadir is set
    m_app_updater = std::make_unique<AppUpdater>();
}
References init_app_config(), and m_app_updater.
~GUI_App()
Slic3r::GUI::GUI_App::~GUI_App () override
{
    delete app_config;
    delete preset_bundle;
    delete preset_updater;
}
References app_config, preset_bundle, and preset_updater.
Member Function Documentation
add_config_menu()
void Slic3r::GUI::GUI_App::add_config_menu (wxMenuBar * menu)
{
    auto local_menu = new wxMenu();
    wxWindowID config_id_base = wxWindow::NewControlId(int(ConfigMenuCnt));
    const wxString config_wizard_name = _(ConfigWizard::name(true));
    const wxString config_wizard_tooltip = from_u8((boost::format(_u8L("Run %s")) % config_wizard_name).str());
    // Cmd+, is standard on OS X - what about other operating systems?
    if (is_editor()) {
        local_menu->Append(config_id_base + ConfigMenuWizard, config_wizard_name + dots, config_wizard_tooltip);
        local_menu->Append(config_id_base + ConfigMenuSnapshots, _L("&Configuration Snapshots") + dots, _L("Inspect / activate configuration snapshots"));
        local_menu->Append(config_id_base + ConfigMenuTakeSnapshot, _L("Take Configuration &Snapshot"), _L("Capture a configuration snapshot"));
        local_menu->Append(config_id_base + ConfigMenuUpdateConf, _L("Check for Configuration Updates"), _L("Check for configuration updates"));
        local_menu->Append(config_id_base + ConfigMenuUpdateApp, _L("Check for Application Updates"), _L("Check for new version of application"));
#if defined(__linux__) && defined(SLIC3R_DESKTOP_INTEGRATION)
        //if (DesktopIntegrationDialog::integration_possible())
        local_menu->Append(config_id_base + ConfigMenuDesktopIntegration, _L("Desktop Integration"), _L("Desktop Integration"));
#endif //(__linux__) && defined(SLIC3R_DESKTOP_INTEGRATION)
        local_menu->AppendSeparator();
    }
    local_menu->Append(config_id_base + ConfigMenuPreferences, _L("&Preferences") + dots +
#ifdef __APPLE__
        "\tCtrl+,",
#else
        "\tCtrl+P",
#endif
        _L("Application preferences"));
    wxMenu* mode_menu = nullptr;
    if (is_editor()) {
        local_menu->AppendSeparator();
        mode_menu = new wxMenu();
        mode_menu->AppendRadioItem(config_id_base + ConfigMenuModeSimple, _L("Simple"), _L("Simple View Mode"));
//    mode_menu->AppendRadioItem(config_id_base + ConfigMenuModeAdvanced, _L("Advanced"), _L("Advanced View Mode"));
        mode_menu->AppendRadioItem(config_id_base + ConfigMenuModeAdvanced, _CTX("Advanced", "Mode"), _L("Advanced View Mode"));
        mode_menu->AppendRadioItem(config_id_base + ConfigMenuModeExpert, _L("Expert"), _L("Expert View Mode"));
        Bind(wxEVT_UPDATE_UI, [this](wxUpdateUIEvent& evt) { if (get_mode() == comSimple) evt.Check(true); }, config_id_base + ConfigMenuModeSimple);
        Bind(wxEVT_UPDATE_UI, [this](wxUpdateUIEvent& evt) { if (get_mode() == comAdvanced) evt.Check(true); }, config_id_base + ConfigMenuModeAdvanced);
        Bind(wxEVT_UPDATE_UI, [this](wxUpdateUIEvent& evt) { if (get_mode() == comExpert) evt.Check(true); }, config_id_base + ConfigMenuModeExpert);
        local_menu->AppendSubMenu(mode_menu, _L("Mode"), wxString::Format(_L("%s View Mode"), SLIC3R_APP_NAME));
    }
    local_menu->AppendSeparator();
    local_menu->Append(config_id_base + ConfigMenuLanguage, _L("&Language"));
    if (is_editor()) {
        local_menu->AppendSeparator();
        local_menu->Append(config_id_base + ConfigMenuFlashFirmware, _L("Flash Printer &Firmware"), _L("Upload a firmware image into an Arduino based printer"));
        // TODO: for when we're able to flash dictionaries
        // local_menu->Append(config_id_base + FirmwareMenuDict,  _L("Flash Language File"),    _L("Upload a language dictionary file into a Prusa printer"));
    }
    local_menu->Bind(wxEVT_MENU, [this, config_id_base](wxEvent &event) {
        switch (event.GetId() - config_id_base) {
        case ConfigMenuWizard:
            run_wizard(ConfigWizard::RR_USER);
            break;
    case ConfigMenuUpdateConf:
      check_updates(true);
      break;
        case ConfigMenuUpdateApp:
            app_version_check(true);
            break;
#ifdef __linux__
        case ConfigMenuDesktopIntegration:
            show_desktop_integration_dialog();
            break;
#endif
        case ConfigMenuTakeSnapshot:
            // Take a configuration snapshot.
            if (wxString action_name = _L("Taking a configuration snapshot");
                check_and_save_current_preset_changes(action_name, _L("Some presets are modified and the unsaved changes will not be captured by the configuration snapshot."), false, true)) {
                wxTextEntryDialog dlg(nullptr, action_name, _L("Snapshot name"));
                UpdateDlgDarkUI(&dlg);
                // set current normal font for dialog children,
                // because of just dlg.SetFont(normal_font()) has no result;
                for (auto child : dlg.GetChildren())
                    child->SetFont(normal_font());
                if (dlg.ShowModal() == wxID_OK)
                    if (const Config::Snapshot *snapshot = Config::take_config_snapshot_report_error(
                            *app_config, Config::Snapshot::SNAPSHOT_USER, dlg.GetValue().ToUTF8().data());
                        snapshot != nullptr)
                        app_config->set("on_snapshot", snapshot->id);
            }
            break;
        case ConfigMenuSnapshots:
            if (check_and_save_current_preset_changes(_L("Loading a configuration snapshot"), "", false)) {
                std::string on_snapshot;
                if (Config::SnapshotDB::singleton().is_on_snapshot(*app_config))
                    on_snapshot = app_config->get("on_snapshot");
                ConfigSnapshotDialog dlg(Slic3r::GUI::Config::SnapshotDB::singleton(), on_snapshot);
                dlg.ShowModal();
                if (!dlg.snapshot_to_activate().empty()) {
                    if (! Config::SnapshotDB::singleton().is_on_snapshot(*app_config) &&
                        ! Config::take_config_snapshot_cancel_on_error(*app_config, Config::Snapshot::SNAPSHOT_BEFORE_ROLLBACK, "",
                                GUI::format(_L("Continue to activate a configuration snapshot %1%?"), dlg.snapshot_to_activate())))
                        break;
                    try {
                        app_config->set("on_snapshot", Config::SnapshotDB::singleton().restore_snapshot(dlg.snapshot_to_activate(), *app_config).id);
                        // Enable substitutions, log both user and system substitutions. There should not be any substitutions performed when loading system
                        // presets because compatibility of profiles shall be verified using the min_slic3r_version keys in config index, but users
                        // are known to be creative and mess with the config files in various ways.
                        if (PresetsConfigSubstitutions all_substitutions = preset_bundle->load_presets(*app_config, ForwardCompatibilitySubstitutionRule::Enable);
                            ! all_substitutions.empty())
                            show_substitutions_info(all_substitutions);
                        // Load the currently selected preset into the GUI, update the preset selection box.
                        load_current_presets();
                    } catch (std::exception &ex) {
                        GUI::show_error(nullptr, _L("Failed to activate configuration snapshot.") + "\n" + into_u8(ex.what()));
                    }
                }
            }
            break;
        case ConfigMenuPreferences:
        {
            open_preferences();
            break;
        }
        case ConfigMenuLanguage:
        {
            /* Before change application language, let's check unsaved changes on 3D-Scene
             * and draw user's attention to the application restarting after a language change
             */
            {
                // the dialog needs to be destroyed before the call to switch_language()
                // or sometimes the application crashes into wxDialogBase() destructor
                // so we put it into an inner scope
                wxString title = is_editor() ? wxString(SLIC3R_APP_NAME) : wxString(GCODEVIEWER_APP_NAME);
                title += " - " + _L("Language selection");
                //wxMessageDialog dialog(nullptr,
                MessageDialog dialog(nullptr,
                    _L("Switching the language will trigger application restart.\n"
                        "You will lose content of the plater.") + "\n\n" +
                    _L("Do you want to proceed?"),
                    title,
                    wxICON_QUESTION | wxOK | wxCANCEL);
                if (dialog.ShowModal() == wxID_CANCEL)
                    return;
            }
            switch_language();
            break;
        }
        case ConfigMenuFlashFirmware:
            FirmwareDialog::run(mainframe);
            break;
        default:
            break;
        }
    });
    using std::placeholders::_1;
    if (mode_menu != nullptr) {
        auto modfn = [this](int mode, wxCommandEvent&) { if (get_mode() != mode) save_mode(mode); };
        mode_menu->Bind(wxEVT_MENU, std::bind(modfn, comSimple, _1), config_id_base + ConfigMenuModeSimple);
        mode_menu->Bind(wxEVT_MENU, std::bind(modfn, comAdvanced, _1), config_id_base + ConfigMenuModeAdvanced);
        mode_menu->Bind(wxEVT_MENU, std::bind(modfn, comExpert, _1), config_id_base + ConfigMenuModeExpert);
    }
    menu->Append(local_menu, _L("&Configuration"));
}
References _, _CTX, _L, _u8L, app_config, app_version_check(), check_and_save_current_preset_changes(), check_updates(), Slic3r::comAdvanced, Slic3r::comExpert, Slic3r::comSimple, Slic3r::GUI::ConfigMenuCnt, Slic3r::GUI::ConfigMenuDesktopIntegration, Slic3r::GUI::ConfigMenuFlashFirmware, Slic3r::GUI::ConfigMenuLanguage, Slic3r::GUI::ConfigMenuModeAdvanced, Slic3r::GUI::ConfigMenuModeExpert, Slic3r::GUI::ConfigMenuModeSimple, Slic3r::GUI::ConfigMenuPreferences, Slic3r::GUI::ConfigMenuSnapshots, Slic3r::GUI::ConfigMenuTakeSnapshot, Slic3r::GUI::ConfigMenuUpdateApp, Slic3r::GUI::ConfigMenuUpdateConf, Slic3r::GUI::ConfigMenuWizard, Slic3r::GUI::dots(), Slic3r::Enable, Slic3r::GUI::format(), Slic3r::GUI::from_u8(), GCODEVIEWER_APP_NAME, Slic3r::AppConfig::get(), get_mode(), Slic3r::GUI::into_u8(), is_editor(), Slic3r::GUI::Config::SnapshotDB::is_on_snapshot(), load_current_presets(), Slic3r::PresetBundle::load_presets(), mainframe, Slic3r::GUI::ConfigWizard::name(), normal_font(), open_preferences(), preset_bundle, Slic3r::GUI::ConfigWizard::RR_USER, Slic3r::FirmwareDialog::run(), run_wizard(), save_mode(), Slic3r::AppConfig::set(), show_desktop_integration_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Config::SnapshotDB::singleton(), Slic3r::GUI::Config::Snapshot::SNAPSHOT_BEFORE_ROLLBACK, Slic3r::GUI::ConfigSnapshotDialog::snapshot_to_activate(), Slic3r::GUI::Config::Snapshot::SNAPSHOT_USER, switch_language(), Slic3r::GUI::Config::take_config_snapshot_cancel_on_error(), Slic3r::GUI::Config::take_config_snapshot_report_error(), and UpdateDlgDarkUI().
app_updater()
void Slic3r::GUI::GUI_App::app_updater (bool from_user) private
{
    DownloadAppData app_data = m_app_updater->get_app_data();
    if (from_user && (!app_data.version || *app_data.version <= *Semver::parse(SLIC3R_VERSION)))
    {
        BOOST_LOG_TRIVIAL(info) << "There is no newer version online.";
        MsgNoAppUpdates no_update_dialog;
        no_update_dialog.ShowModal();
        return;
    }
    assert(!app_data.url.empty());
    assert(!app_data.target_path.empty());
    // dialog with new version info
    AppUpdateAvailableDialog dialog(*Semver::parse(SLIC3R_VERSION), *app_data.version, from_user);
    auto dialog_result = dialog.ShowModal();
    // checkbox "do not show again"
    if (dialog.disable_version_check()) {
        app_config->set("notify_release", "none");
    }
    // Doesn't wish to update
    if (dialog_result != wxID_OK) {
        return;
    }
    // dialog with new version download (installer or app dependent on system) including path selection
    AppUpdateDownloadDialog dwnld_dlg(*app_data.version, app_data.target_path);
    dialog_result = dwnld_dlg.ShowModal();
    //  Doesn't wish to download
    if (dialog_result != wxID_OK) {
        return;
    }
    app_data.target_path =dwnld_dlg.get_download_path();
    // start download
    this->plater_->get_notification_manager()->push_download_progress_notification(GUI::format(_L("Downloading %1%"), app_data.target_path.filename().string()), std::bind(&AppUpdater::cancel_callback, this->m_app_updater.get()));
    app_data.start_after = dwnld_dlg.run_after_download();
    m_app_updater->set_app_data(std::move(app_data));
    m_app_updater->sync_download();
}
References _L, app_config, Slic3r::AppUpdater::cancel_callback(), Slic3r::GUI::AppUpdateAvailableDialog::disable_version_check(), Slic3r::GUI::format(), Slic3r::GUI::AppUpdateDownloadDialog::get_download_path(), Slic3r::GUI::Plater::get_notification_manager(), m_app_updater, Slic3r::Semver::parse(), plater_, Slic3r::GUI::NotificationManager::push_download_progress_notification(), Slic3r::GUI::AppUpdateDownloadDialog::run_after_download(), Slic3r::AppConfig::set(), Slic3r::DownloadAppData::start_after, Slic3r::DownloadAppData::target_path, Slic3r::DownloadAppData::url, and Slic3r::DownloadAppData::version.
Referenced by on_version_read().
app_version_check()
void Slic3r::GUI::GUI_App::app_version_check (bool from_user) private
{
    if (from_user) {
        if (m_app_updater->get_download_ongoing()) {
            MessageDialog msgdlg(nullptr, _L("Downloading of the new version is in progress. Do you want to continue?"), _L("Notice"), wxYES_NO);
            if (msgdlg.ShowModal() != wxID_YES)
                return;
        }
    }
    std::string version_check_url = app_config->version_check_url();
    m_app_updater->sync_version(version_check_url, from_user);
}
References _L, app_config, m_app_updater, and Slic3r::AppConfig::version_check_url().
Referenced by add_config_menu(), and post_init().
apply_keeped_preset_modifications()
void Slic3r::GUI::GUI_App::apply_keeped_preset_modifications ()
{
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (Tab* tab : tabs_list) {
        if (tab->supports_printer_technology(printer_technology))
            tab->apply_config_from_cache();
    }
    load_current_presets(false);
}
References Slic3r::PresetCollection::get_edited_preset(), load_current_presets(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and tabs_list.
Referenced by check_and_keep_current_preset_changes(), and Slic3r::GUI::ConfigWizard::run().
bold_font()
const wxFont & Slic3r::GUI::GUI_App::bold_font () inline
{ return m_bold_font; }
References m_bold_font.
can_load_project()
bool Slic3r::GUI::GUI_App::can_load_project ()
{
    int saved_project = plater()->save_project_if_dirty(_L("Loading a new project while the current project is modified."));
    if (saved_project == wxID_CANCEL ||
        (plater()->is_project_dirty() && saved_project == wxID_NO &&
         !check_and_save_current_preset_changes(_L("Project is loading"), _L("Opening new project while some presets are unsaved."))))
        return false;
    return true;
}
References _L, check_and_save_current_preset_changes(), plater(), and Slic3r::GUI::Plater::save_project_if_dirty().
catch_error()
bool Slic3r::GUI::GUI_App::catch_error (std::function< void()> cb, const std::string & err) static
{
    if (!err.empty()) {
        if (cb)
            cb();
        //         if (message_dialog)
        //             message_dialog->(err, "Error", wxOK | wxICON_ERROR);
        show_error(/*this*/nullptr, err);
        return true;
    }
    return false;
}
References Slic3r::GUI::show_error().
check_and_keep_current_preset_changes()
bool Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes (const wxString & caption, const wxString & header, int action_buttons, bool * postponed_apply_of_keeped_changes = nullptr)
{
    if (has_current_preset_changes()) {
        bool is_called_from_configwizard = postponed_apply_of_keeped_changes != nullptr;
        const std::string app_config_key = is_called_from_configwizard ? "" : "default_action_on_new_project";
        UnsavedChangesDialog dlg(caption, header, app_config_key, action_buttons);
        std::string act = app_config_key.empty() ? "none" : wxGetApp().app_config->get(app_config_key);
        if (act == "none" && dlg.ShowModal() == wxID_CANCEL)
            return false;
        auto reset_modifications = [this, is_called_from_configwizard]() {
            if (is_called_from_configwizard)
                return; // no need to discared changes. It will be done fromConfigWizard closing
            PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
            for (const Tab* const tab : tabs_list) {
                if (tab->supports_printer_technology(printer_technology) && tab->current_preset_is_dirty())
                    tab->m_presets->discard_current_changes();
            }
            load_current_presets(false);
        };
        if (dlg.discard())
            reset_modifications();
        else  // save selected changes
        {
            const auto& preset_names_and_types = dlg.get_names_and_types();
            if (dlg.save_preset()) {
                for (const std::pair<std::string, Preset::Type>& nt : preset_names_and_types)
                    preset_bundle->save_changes_for_preset(nt.first, nt.second, dlg.get_unselected_options(nt.second));
                // if we saved changes to the new presets, we should to
                // synchronize config.ini with the current selections.
                preset_bundle->export_selections(*app_config);
                wxString text = dlg.msg_success_saved_modifications(preset_names_and_types.size());
                if (!is_called_from_configwizard)
                    text += "\n\n" + _L("For new project all modifications will be reseted");
                MessageDialog(nullptr, text).ShowModal();
                reset_modifications();
            }
            else if (dlg.transfer_changes() && (dlg.has_unselected_options() || is_called_from_configwizard)) {
                // execute this part of code only if not all modifications are keeping to the new project
                // OR this function is called when ConfigWizard is closed and "Keep modifications" is selected
                for (const std::pair<std::string, Preset::Type>& nt : preset_names_and_types) {
                    Preset::Type type = nt.second;
                    Tab* tab = get_tab(type);
                    std::vector<std::string> selected_options = dlg.get_selected_options(type);
                    if (type == Preset::TYPE_PRINTER) {
                        auto it = std::find(selected_options.begin(), selected_options.end(), "extruders_count");
                        if (it != selected_options.end()) {
                            // erase "extruders_count" option from the list
                            selected_options.erase(it);
                            // cache the extruders count
                            static_cast<TabPrinter*>(tab)->cache_extruder_cnt();
                        }
                    }
                    tab->cache_config_diff(selected_options);
                    if (!is_called_from_configwizard)
                        tab->m_presets->discard_current_changes();
                }
                if (is_called_from_configwizard)
                    *postponed_apply_of_keeped_changes = true;
                else
                    apply_keeped_preset_modifications();
            }
        }
    }
    return true;
}
References _L, app_config, apply_keeped_preset_modifications(), Slic3r::GUI::Tab::cache_config_diff(), Slic3r::GUI::UnsavedChangesDialog::discard(), Slic3r::PresetCollection::discard_current_changes(), Slic3r::PresetBundle::export_selections(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::UnsavedChangesDialog::get_names_and_types(), Slic3r::GUI::UnsavedChangesDialog::get_selected_options(), get_tab(), Slic3r::GUI::UnsavedChangesDialog::get_unselected_options(), has_current_preset_changes(), Slic3r::GUI::UnsavedChangesDialog::has_unselected_options(), load_current_presets(), Slic3r::GUI::Tab::m_presets, Slic3r::GUI::UnsavedChangesDialog::msg_success_saved_modifications(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::GUI::UnsavedChangesDialog::save_preset(), tabs_list, Slic3r::GUI::UnsavedChangesDialog::transfer_changes(), and Slic3r::Preset::TYPE_PRINTER.
check_and_save_current_preset_changes()
bool Slic3r::GUI::GUI_App::check_and_save_current_preset_changes (const wxString & caption, const wxString & header, bool remember_choice = true, bool use_dont_save_insted_of_discard = false)
{
    if (has_current_preset_changes()) {
        const std::string app_config_key = remember_choice ? "default_action_on_close_application" : "";
        int act_buttons = ActionButtons::SAVE;
        if (dont_save_insted_of_discard)
            act_buttons |= ActionButtons::DONT_SAVE;
        UnsavedChangesDialog dlg(caption, header, app_config_key, act_buttons);
        std::string act = app_config_key.empty() ? "none" : wxGetApp().app_config->get(app_config_key);
        if (act == "none" && dlg.ShowModal() == wxID_CANCEL)
            return false;
        if (dlg.save_preset())  // save selected changes
        {
            for (const std::pair<std::string, Preset::Type>& nt : dlg.get_names_and_types())
                preset_bundle->save_changes_for_preset(nt.first, nt.second, dlg.get_unselected_options(nt.second));
            load_current_presets(false);
            // if we saved changes to the new presets, we should to
            // synchronize config.ini with the current selections.
            preset_bundle->export_selections(*app_config);
            MessageDialog(nullptr, dlg.msg_success_saved_modifications(dlg.get_names_and_types().size())).ShowModal();
        }
    }
    return true;
}
References app_config, Slic3r::GUI::DONT_SAVE, Slic3r::PresetBundle::export_selections(), Slic3r::GUI::UnsavedChangesDialog::get_names_and_types(), Slic3r::GUI::UnsavedChangesDialog::get_unselected_options(), has_current_preset_changes(), load_current_presets(), Slic3r::GUI::UnsavedChangesDialog::msg_success_saved_modifications(), preset_bundle, Slic3r::GUI::SAVE, Slic3r::PresetBundle::save_changes_for_preset(), and Slic3r::GUI::UnsavedChangesDialog::save_preset().
Referenced by add_config_menu(), and can_load_project().
check_older_app_config()
std::string Slic3r::GUI::GUI_App::check_older_app_config (Semver current_version, bool backup) private
{
    std::string older_data_dir_path;
    // If the config folder is redefined - do not check
    if (m_datadir_redefined)
        return {};
    // find other version app config (alpha / beta / release)
    std::string             config_path = app_config->config_path();
    boost::filesystem::path parent_file_path(config_path);
    std::string             filename = parent_file_path.filename().string();
    parent_file_path.remove_filename().remove_filename();
    std::vector<boost::filesystem::path> candidates;
    if (SLIC3R_APP_KEY "-alpha" != GetAppName()) candidates.emplace_back(parent_file_path / SLIC3R_APP_KEY "-alpha" / filename);
    if (SLIC3R_APP_KEY "-beta" != GetAppName())  candidates.emplace_back(parent_file_path / SLIC3R_APP_KEY "-beta" / filename);
    if (SLIC3R_APP_KEY != GetAppName())          candidates.emplace_back(parent_file_path / SLIC3R_APP_KEY / filename);
    Semver last_semver = current_version;
    for (const auto& candidate : candidates) {
        if (boost::filesystem::exists(candidate)) {
            // parse
            boost::optional<Semver>other_semver = parse_semver_from_ini(candidate.string());
            if (other_semver && *other_semver > last_semver) {
                last_semver = *other_semver;
                older_data_dir_path = candidate.parent_path().string();
            }
        }
    }
    if (older_data_dir_path.empty())
        return {};
    BOOST_LOG_TRIVIAL(info) << "last app config file used: " << older_data_dir_path;
    // ask about using older data folder
    InfoDialog msg(nullptr
        , format_wxstr(_L("You are opening %1% version %2%."), SLIC3R_APP_NAME, SLIC3R_VERSION)
        , backup ?
        format_wxstr(_L(
            "The active configuration was created by <b>%1% %2%</b>,"
            "\nwhile a newer configuration was found in <b>%3%</b>"
            "\ncreated by <b>%1% %4%</b>."
            "\n\nShall the newer configuration be imported?"
            "\nIf so, your active configuration will be backed up before importing the new configuration."
        )
            , SLIC3R_APP_NAME, current_version.to_string(), older_data_dir_path, last_semver.to_string())
        : format_wxstr(_L(
            "An existing configuration was found in <b>%3%</b>"
            "\ncreated by <b>%1% %2%</b>."
            "\n\nShall this configuration be imported?"
        )
            , SLIC3R_APP_NAME, last_semver.to_string(), older_data_dir_path)
        , true, wxYES_NO);
    if (backup) {
        msg.SetButtonLabel(wxID_YES, _L("Import"));
        msg.SetButtonLabel(wxID_NO, _L("Don't import"));
    }
    if (msg.ShowModal() == wxID_YES) {
        std::string snapshot_id;
        if (backup) {
            const Config::Snapshot* snapshot{ nullptr };
            if (! GUI::Config::take_config_snapshot_cancel_on_error(*app_config, Config::Snapshot::SNAPSHOT_USER, "",
                _u8L("Continue and import newer configuration?"), &snapshot))
                return {};
            if (snapshot) {
                // Save snapshot ID before loading the alternate AppConfig, as loading the alternate AppConfig may fail.
                snapshot_id = snapshot->id;
                assert(! snapshot_id.empty());
                app_config->set("on_snapshot", snapshot_id);
            } else
                BOOST_LOG_TRIVIAL(error) << "Failed to take congiguration snapshot";
        }
        // load app config from older file
        std::string error = app_config->load((boost::filesystem::path(older_data_dir_path) / filename).string());
        if (!error.empty()) {
            // Error while parsing config file. We'll customize the error message and rethrow to be displayed.
            if (is_editor()) {
                throw Slic3r::RuntimeError(format("Error parsing PrusaSlicer config file, it is probably corrupted. "
                        "Try to manually delete the file to recover from the error. Your user profiles will not be affected."
                        "\n\n%1%\n\n%2%", app_config->config_path(), error));
            }
            else {
                throw Slic3r::RuntimeError(format("Error parsing PrusaGCodeViewer config file, it is probably corrupted. "
                        "Try to manually delete the file to recover from the error."
                        "\n\n%1%\n\n%2%", app_config->config_path(), error));
            }
        }
        if (!snapshot_id.empty())
            app_config->set("on_snapshot", snapshot_id);
        m_app_conf_exists = true;
        return older_data_dir_path;
    }
    return {};
}
References _L, _u8L, app_config, Slic3r::AppConfig::config_path(), error, Slic3r::GUI::format(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::Config::Snapshot::id, is_editor(), Slic3r::AppConfig::load(), m_app_conf_exists, m_datadir_redefined, Slic3r::GUI::parse_semver_from_ini(), Slic3r::AppConfig::set(), Slic3r::GUI::MsgDialog::SetButtonLabel(), Slic3r::GUI::Config::Snapshot::SNAPSHOT_USER, Slic3r::GUI::Config::take_config_snapshot_cancel_on_error(), and Slic3r::Semver::to_string().
Referenced by on_init_inner().
check_print_host_queue()
bool Slic3r::GUI::GUI_App::check_print_host_queue ()
{
    wxString dirty;
    std::vector<std::pair<std::string, std::string>> jobs;
    // Get ongoing jobs from dialog
    mainframe->m_printhost_queue_dlg->get_active_jobs(jobs);
    if (jobs.empty())
        return true;
    // Show dialog
    wxString job_string = wxString();
    for (const auto& job : jobs) {
        job_string += format_wxstr("   %1% : %2% \n", job.first, job.second);
    }
    wxString message;
    message += _(L("The uploads are still ongoing")) + ":\n\n" + job_string +"\n" + _(L("Stop them and continue anyway?"));
    //wxMessageDialog dialog(mainframe,
    MessageDialog dialog(mainframe,
        message,
        wxString(SLIC3R_APP_NAME) + " - " + _(L("Ongoing uploads")),
        wxICON_QUESTION | wxYES_NO | wxNO_DEFAULT);
    if (dialog.ShowModal() == wxID_YES)
        return true;
    // TODO: If already shown, bring forward
    mainframe->m_printhost_queue_dlg->Show();
    return false;
}
References _, Slic3r::GUI::format_wxstr(), Slic3r::GUI::PrintHostQueueDialog::get_active_jobs(), L, Slic3r::GUI::MainFrame::m_printhost_queue_dlg, mainframe, and Slic3r::GUI::PrintHostQueueDialog::Show().
check_printer_presets()
void Slic3r::GUI::GUI_App::check_printer_presets ()
{
    std::vector<std::string> preset_names = PhysicalPrinter::presets_with_print_host_information(preset_bundle->printers);
    if (preset_names.empty())
        return;
    wxString msg_text =  _L("You have the following presets with saved options for \"Print Host upload\"") + ":";
    for (const std::string& preset_name : preset_names)
        msg_text += "\n    \"" + from_u8(preset_name) + "\",";
    msg_text.RemoveLast();
    msg_text += "\n\n" + _L("But since this version of PrusaSlicer we don't show this information in Printer Settings anymore.\n"
                            "Settings will be available in physical printers settings.") + "\n\n" +
                         _L("By default new Printer devices will be named as \"Printer N\" during its creation.\n"
                            "Note: This name can be changed later from the physical printers settings");
    //wxMessageDialog(nullptr, msg_text, _L("Information"), wxOK | wxICON_INFORMATION).ShowModal();
    MessageDialog(nullptr, msg_text, _L("Information"), wxOK | wxICON_INFORMATION).ShowModal();
    preset_bundle->physical_printers.load_printers_from_presets(preset_bundle->printers);
}
References _L, Slic3r::GUI::from_u8(), Slic3r::PhysicalPrinterCollection::load_printers_from_presets(), Slic3r::PresetBundle::physical_printers, preset_bundle, Slic3r::PhysicalPrinter::presets_with_print_host_information(), and Slic3r::PresetBundle::printers.
Referenced by load_current_presets().
check_updates()
bool Slic3r::GUI::GUI_App::check_updates (const bool verbose) private
{
  PresetUpdater::UpdateResult updater_result;
  try {
        preset_updater->update_index_db();
    updater_result = preset_updater->config_update(app_config->orig_version(), verbose ? PresetUpdater::UpdateParams::SHOW_TEXT_BOX : PresetUpdater::UpdateParams::SHOW_NOTIFICATION);
    if (updater_result == PresetUpdater::R_INCOMPAT_EXIT) {
      mainframe->Close();
            // Applicaiton is closing.
            return false;
    }
    else if (updater_result == PresetUpdater::R_INCOMPAT_CONFIGURED) {
            m_app_conf_exists = true;
    }
    else if (verbose && updater_result == PresetUpdater::R_NOOP) {
      MsgNoUpdates dlg;
      dlg.ShowModal();
    }
  }
  catch (const std::exception & ex) {
    show_error(nullptr, ex.what());
  }
    // Applicaiton will continue.
    return true;
}
References app_config, Slic3r::PresetUpdater::config_update(), m_app_conf_exists, mainframe, Slic3r::AppConfig::orig_version(), preset_updater, Slic3r::PresetUpdater::R_INCOMPAT_CONFIGURED, Slic3r::PresetUpdater::R_INCOMPAT_EXIT, Slic3r::PresetUpdater::R_NOOP, Slic3r::GUI::show_error(), Slic3r::PresetUpdater::SHOW_NOTIFICATION, Slic3r::PresetUpdater::SHOW_TEXT_BOX, Slic3r::PresetUpdater::update_index_db(), and verbose.
Referenced by add_config_menu(), and post_init().
checked_tab()
bool Slic3r::GUI::GUI_App::checked_tab (Tab * tab)
{
    bool ret = true;
    if (find(tabs_list.begin(), tabs_list.end(), tab) == tabs_list.end())
        ret = false;
    return ret;
}
References tabs_list.
code_font()
const wxFont & Slic3r::GUI::GUI_App::code_font () inline
{ return m_code_font; }
References m_code_font.
config_wizard_startup()
bool Slic3r::GUI::GUI_App::config_wizard_startup () private
{
    if (!m_app_conf_exists || preset_bundle->printers.only_default_printers()) {
        run_wizard(ConfigWizard::RR_DATA_EMPTY);
        return true;
    } else if (get_app_config()->legacy_datadir()) {
        // Looks like user has legacy pre-vendorbundle data directory,
        // explain what this is and run the wizard
        MsgDataLegacy dlg;
        dlg.ShowModal();
        run_wizard(ConfigWizard::RR_DATA_LEGACY);
        return true;
    }
#ifndef __APPLE__
    else if (is_editor() && m_last_app_conf_lower_version && app_config->get_bool("downloader_url_registered")) {
        show_downloader_registration_dialog();
        return true;
    }
#endif
    return false;
}
References app_config, Slic3r::GUI::get_app_config(), Slic3r::AppConfig::get_bool(), is_editor(), m_app_conf_exists, m_last_app_conf_lower_version, Slic3r::PrinterPresetCollection::only_default_printers(), preset_bundle, Slic3r::PresetBundle::printers, Slic3r::GUI::ConfigWizard::RR_DATA_EMPTY, Slic3r::GUI::ConfigWizard::RR_DATA_LEGACY, run_wizard(), and show_downloader_registration_dialog().
Referenced by post_init().
current_language_code()
wxString Slic3r::GUI::GUI_App::current_language_code () const inline
{ return m_wxLocale->GetCanonicalName(); }
References m_wxLocale.
Referenced by current_language_code_safe().
current_language_code_safe()
wxString Slic3r::GUI::GUI_App::current_language_code_safe () const
{
  // Translate the language code to a code, for which Prusa Research maintains translations.
  const std::map<wxString, wxString> mapping {
    { "cs",   "cs_CZ", },
    { "sk",   "cs_CZ", },
    { "de",   "de_DE", },
    { "es",   "es_ES", },
    { "fr",   "fr_FR", },
    { "it",   "it_IT", },
    { "ja",   "ja_JP", },
    { "ko",   "ko_KR", },
    { "pl",   "pl_PL", },
    { "uk",   "uk_UA", },
    { "zh",   "zh_CN", },
    { "ru",   "ru_RU", },
  };
  wxString language_code = this->current_language_code().BeforeFirst('_');
  auto it = mapping.find(language_code);
  if (it != mapping.end())
    language_code = it->second;
  else
    language_code = "en_US";
  return language_code;
}
References current_language_code().
Referenced by open_web_page_localized().
dark_mode()
bool Slic3r::GUI::GUI_App::dark_mode () static
{
#if __APPLE__
    // The check for dark mode returns false positive on 10.12 and 10.13,
    // which allowed setting dark menu bar and dock area, which is
    // is detected as dark mode. We must run on at least 10.14 where the
    // proper dark mode was first introduced.
    return wxPlatformInfo::Get().CheckOSVersion(10, 14) && mac_dark_mode();
#else
    if (wxGetApp().app_config->has("dark_color_mode"))
        return wxGetApp().app_config->get_bool("dark_color_mode");
    return check_dark_mode();
#endif
}
References app_config, Slic3r::GUI::check_dark_mode(), Slic3r::AppConfig::has(), and Slic3r::GUI::mac_dark_mode().
Referenced by get_label_default_clr_modified(), get_label_default_clr_system(), init_ui_colours(), and UpdateDVCDarkUI().
downloader()
Downloader * Slic3r::GUI::GUI_App::downloader ()
{
    return m_downloader.get();
}
References m_downloader.
em_unit()
int Slic3r::GUI::GUI_App::em_unit () const inline
{ return m_em_unit; }
References m_em_unit.
extruders_cnt()
int Slic3r::GUI::GUI_App::extruders_cnt () const
{
    const Preset& preset = preset_bundle->printers.get_selected_preset();
    return preset.printer_technology() == ptSLA ? 1 :
           preset.config.option<ConfigOptionFloats>("nozzle_diameter")->values.size();
}
References Slic3r::Preset::config, Slic3r::PresetCollection::get_selected_preset(), Slic3r::ConfigBase::option(), preset_bundle, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptSLA, and Slic3r::ConfigOptionVector< T >::size().
extruders_edited_cnt()
int Slic3r::GUI::GUI_App::extruders_edited_cnt () const
{
    const Preset& preset = preset_bundle->printers.get_edited_preset();
    return preset.printer_technology() == ptSLA ? 1 :
           preset.config.option<ConfigOptionFloats>("nozzle_diameter")->values.size();
}
References Slic3r::Preset::config, Slic3r::PresetCollection::get_edited_preset(), Slic3r::ConfigBase::option(), preset_bundle, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptSLA, and Slic3r::ConfigOptionVector< T >::size().
gallery_dialog()
GalleryDialog * Slic3r::GUI::GUI_App::gallery_dialog ()
{
    return mainframe->gallery_dialog();
}
References Slic3r::GUI::MainFrame::gallery_dialog(), and mainframe.
get_active_preset_collections()
std::vector< const PresetCollection * > Slic3r::GUI::GUI_App::get_active_preset_collections () const
{
    std::vector<const PresetCollection*> ret;
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (const Tab* tab : tabs_list)
        if (tab->supports_printer_technology(printer_technology))
            ret.push_back(tab->get_presets());
    return ret;
}
References Slic3r::PresetCollection::get_edited_preset(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and tabs_list.
Referenced by Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets(), and Slic3r::GUI::ProjectDirtyStateManager::update_from_presets().
get_app_mode()
EAppMode Slic3r::GUI::GUI_App::get_app_mode () const inline
{ return m_app_mode; }
References m_app_mode.
Referenced by Slic3r::GUI::GUI_Run().
get_colour_approx_luma()
unsigned Slic3r::GUI::GUI_App::get_colour_approx_luma (const wxColour & colour) static
{
    double r = colour.Red();
    double g = colour.Green();
    double b = colour.Blue();
    return std::round(std::sqrt(
        r * r * .241 +
        g * g * .691 +
        b * b * .068
        ));
}
get_current_shader()
GLShaderProgram * Slic3r::GUI::GUI_App::get_current_shader () inline
{ return m_opengl_mgr.get_current_shader(); }
References Slic3r::GUI::OpenGLManager::get_current_shader(), and m_opengl_mgr.
get_gl_info()
std::string Slic3r::GUI::GUI_App::get_gl_info (bool for_github) static
{
    return OpenGLManager::get_gl_info().to_string(for_github);
}
References Slic3r::GUI::OpenGLManager::get_gl_info(), and Slic3r::GUI::OpenGLManager::GLInfo::to_string().
get_instance_hash_int()
size_t Slic3r::GUI::GUI_App::get_instance_hash_int () inline
{ return m_instance_hash_int; }
References m_instance_hash_int.
get_instance_hash_string()
std::string Slic3r::GUI::GUI_App::get_instance_hash_string () inline
{ return m_instance_hash_string; }
References m_instance_hash_string.
get_label_clr_default()
const wxColour & Slic3r::GUI::GUI_App::get_label_clr_default () inline
{ return m_color_label_default; }
References m_color_label_default.
get_label_clr_modified()
const wxColour & Slic3r::GUI::GUI_App::get_label_clr_modified () inline
{ return m_color_label_modified; }
References m_color_label_modified.
get_label_clr_sys()
const wxColour & Slic3r::GUI::GUI_App::get_label_clr_sys () inline
{ return m_color_label_sys; }
References m_color_label_sys.
get_label_default_clr_modified()
const wxColour Slic3r::GUI::GUI_App::get_label_default_clr_modified ()
{
    return dark_mode() ? wxColour(253, 111, 40) : wxColour(252, 77, 1);
}
References dark_mode().
Referenced by init_ui_colours().
get_label_default_clr_system()
const wxColour Slic3r::GUI::GUI_App::get_label_default_clr_system ()
{
    return dark_mode() ? wxColour(115, 220, 103) : wxColour(26, 132, 57);
}
References dark_mode().
Referenced by init_ui_colours().
get_min_size()
wxSize Slic3r::GUI::GUI_App::get_min_size () const
{
    return wxSize(76*m_em_unit, 49 * m_em_unit);
}
References m_em_unit.
get_mode()
ConfigOptionMode Slic3r::GUI::GUI_App::get_mode ()
{
    if (!app_config->has("view_mode"))
        return comSimple;
    const auto mode = app_config->get("view_mode");
    return mode == "expert" ? comExpert :
           mode == "simple" ? comSimple : comAdvanced;
}
References app_config, Slic3r::comAdvanced, Slic3r::comExpert, Slic3r::comSimple, Slic3r::AppConfig::get(), and Slic3r::AppConfig::has().
Referenced by add_config_menu().
get_mode_btn_color()
const std::string & Slic3r::GUI::GUI_App::get_mode_btn_color (int mode_id)
{
    assert(0 <= mode_id && size_t(mode_id) < m_mode_palette.size());
    return m_mode_palette[mode_id];
}
References m_mode_palette.
get_mode_default_palette()
const std::vector< std::string > Slic3r::GUI::GUI_App::get_mode_default_palette ()
{
    return { "#7DF028", "#FFDC00", "#E70000" };
}
Referenced by init_ui_colours(), and update_ui_colours_from_appconfig().
get_mode_palette()
std::vector< wxColour > Slic3r::GUI::GUI_App::get_mode_palette ()
{
    return { wxColor(m_mode_palette[0]),
             wxColor(m_mode_palette[1]),
             wxColor(m_mode_palette[2]) };
}
References m_mode_palette.
get_preset_updater()
PresetUpdater * Slic3r::GUI::GUI_App::get_preset_updater () inline
{ return preset_updater; }
References preset_updater.
get_shader()
GLShaderProgram * Slic3r::GUI::GUI_App::get_shader (const std::string & shader_name) inline
{ return m_opengl_mgr.get_shader(shader_name); }
References Slic3r::GUI::OpenGLManager::get_shader(), and m_opengl_mgr.
get_tab()
Tab * Slic3r::GUI::GUI_App::get_tab (Preset::Type type)
{
    for (Tab* tab: tabs_list)
        if (tab->type() == type)
            return tab->completed() ? tab : nullptr; // To avoid actions with no-completed Tab
    return nullptr;
}
References Slic3r::GUI::Tab::completed(), and tabs_list.
Referenced by check_and_keep_current_preset_changes().
get_window_default_clr()
const wxColour & Slic3r::GUI::GUI_App::get_window_default_clr () inline
{ return m_color_window_default; }
References m_color_window_default.
GetSingleChoiceIndex()
int Slic3r::GUI::GUI_App::GetSingleChoiceIndex (const wxString & message, const wxString & caption, const wxArrayString & choices, int initialSelection)
{
#ifdef _WIN32
    wxSingleChoiceDialog dialog(nullptr, message, caption, choices);
    wxGetApp().UpdateDlgDarkUI(&dialog);
    dialog.SetSelection(initialSelection);
    return dialog.ShowModal() == wxID_OK ? dialog.GetSelection() : -1;
#else
    return wxGetSingleChoiceIndex(message, caption, choices, initialSelection);
#endif
}
Referenced by select_language().
has_current_preset_changes()
bool Slic3r::GUI::GUI_App::has_current_preset_changes () const
{
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (const Tab* const tab : tabs_list) {
        if (tab->supports_printer_technology(printer_technology) && tab->current_preset_is_dirty())
            return true;
    }
    return false;
}
References Slic3r::PresetCollection::get_edited_preset(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and tabs_list.
Referenced by check_and_keep_current_preset_changes(), and check_and_save_current_preset_changes().
has_unsaved_preset_changes()
bool Slic3r::GUI::GUI_App::has_unsaved_preset_changes () const
{
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (const Tab* const tab : tabs_list) {
        if (tab->supports_printer_technology(printer_technology) && tab->saved_preset_is_dirty())
            return true;
    }
    return false;
}
References Slic3r::PresetCollection::get_edited_preset(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and tabs_list.
imgui()
ImGuiWrapper * Slic3r::GUI::GUI_App::imgui () inline
{ return m_imgui.get(); }
References m_imgui.
import_model()
void Slic3r::GUI::GUI_App::import_model (wxWindow * parent, wxArrayString & input_files) const
{
    input_files.Clear();
    wxFileDialog dialog(parent ? parent : GetTopWindow(),
        _L("Choose one or more files (STL/3MF/STEP/OBJ/AMF/PRUSA):"),
        from_u8(app_config->get_last_dir()), "",
        file_wildcards(FT_MODEL), wxFD_OPEN | wxFD_MULTIPLE | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() == wxID_OK)
        dialog.GetPaths(input_files);
}
References _L, app_config, Slic3r::GUI::file_wildcards(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_MODEL, and Slic3r::AppConfig::get_last_dir().
import_zip()
void Slic3r::GUI::GUI_App::import_zip (wxWindow * parent, wxString & input_file) const
{
    wxFileDialog dialog(parent ? parent : GetTopWindow(),
        _L("Choose ZIP file") + ":",
        from_u8(app_config->get_last_dir()), "",
        file_wildcards(FT_ZIP), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() == wxID_OK)
        input_file = dialog.GetPath();
}
References _L, app_config, Slic3r::GUI::file_wildcards(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_ZIP, and Slic3r::AppConfig::get_last_dir().
init_app_config()
void Slic3r::GUI::GUI_App::init_app_config () private
{
  // Profiles for the alpha are stored into the PrusaSlicer-alpha directory to not mix with the current release.
    SetAppName(SLIC3R_APP_KEY);
//  SetAppName(SLIC3R_APP_KEY "-alpha");
//  SetAppName(SLIC3R_APP_KEY "-beta");
//  SetAppDisplayName(SLIC3R_APP_NAME);
  // Set the Slic3r data directory at the Slic3r XS module.
  // Unix: ~/ .Slic3r
  // Windows : "C:\Users\username\AppData\Roaming\Slic3r" or "C:\Documents and Settings\username\Application Data\Slic3r"
  // Mac : "~/Library/Application Support/Slic3r"
    if (data_dir().empty()) {
        #ifndef __linux__
            set_data_dir(wxStandardPaths::Get().GetUserDataDir().ToUTF8().data());
        #else
            // Since version 2.3, config dir on Linux is in ${XDG_CONFIG_HOME}.
            // https://github.com/prusa3d/PrusaSlicer/issues/2911
            wxString dir;
            if (! wxGetEnv(wxS("XDG_CONFIG_HOME"), &dir) || dir.empty() )
                dir = wxFileName::GetHomeDir() + wxS("/.config");
            set_data_dir((dir + "/" + GetAppName()).ToUTF8().data());
        #endif
    } else {
        m_datadir_redefined = true;
    }
  if (!app_config)
        app_config = new AppConfig(is_editor() ? AppConfig::EAppMode::Editor : AppConfig::EAppMode::GCodeViewer);
  // load settings
  m_app_conf_exists = app_config->exists();
  if (m_app_conf_exists) {
        std::string error = app_config->load();
        if (!error.empty()) {
            // Error while parsing config file. We'll customize the error message and rethrow to be displayed.
            if (is_editor()) {
                throw Slic3r::RuntimeError(format("Error parsing PrusaSlicer config file, it is probably corrupted. "
                        "Try to manually delete the file to recover from the error. Your user profiles will not be affected."
                        "\n\n%1%\n\n%2%", app_config->config_path(), error));
            }
            else {
                throw Slic3r::RuntimeError(format("Error parsing PrusaGCodeViewer config file, it is probably corrupted. "
                        "Try to manually delete the file to recover from the error."
                        "\n\n%1%\n\n%2%", app_config->config_path(), error));
            }
        }
    }
}
References app_config, Slic3r::AppConfig::config_path(), Slic3r::data_dir(), Slic3r::AppConfig::Editor, Slic3r::empty(), error, Slic3r::AppConfig::exists(), Slic3r::GUI::format(), Slic3r::AppConfig::GCodeViewer, is_editor(), Slic3r::AppConfig::load(), m_app_conf_exists, m_datadir_redefined, and Slic3r::set_data_dir().
Referenced by GUI_App().
init_fonts()
void Slic3r::GUI::GUI_App::init_fonts ()
{
    m_small_font = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
    m_bold_font = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT).Bold();
    m_normal_font = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
#ifdef __WXMAC__
    m_small_font.SetPointSize(11);
    m_bold_font.SetPointSize(13);
#endif /*__WXMAC__*/
    // wxSYS_OEM_FIXED_FONT and wxSYS_ANSI_FIXED_FONT use the same as
    // DEFAULT in wxGtk. Use the TELETYPE family as a work-around
    m_code_font = wxFont(wxFontInfo().Family(wxFONTFAMILY_TELETYPE));
    m_code_font.SetPointSize(m_normal_font.GetPointSize());
}
References m_bold_font, m_code_font, m_normal_font, and m_small_font.
Referenced by on_init_inner().
init_glcontext()
wxGLContext * Slic3r::GUI::GUI_App::init_glcontext (wxGLCanvas & canvas)
{
#if ENABLE_GL_CORE_PROFILE
#if ENABLE_OPENGL_DEBUG_OPTION
    return m_opengl_mgr.init_glcontext(canvas, init_params != nullptr ? init_params->opengl_version : std::make_pair(0, 0),
        init_params != nullptr ? init_params->opengl_debug : false);
#else
    return m_opengl_mgr.init_glcontext(canvas, init_params != nullptr ? init_params->opengl_version : std::make_pair(0, 0));
#endif // ENABLE_OPENGL_DEBUG_OPTION
#else
    return m_opengl_mgr.init_glcontext(canvas);
#endif // ENABLE_GL_CORE_PROFILE
}
References Slic3r::GUI::OpenGLManager::init_glcontext(), init_params, and m_opengl_mgr.
init_opengl()
bool Slic3r::GUI::GUI_App::init_opengl ()
{
    bool status = m_opengl_mgr.init_gl();
    m_opengl_initialized = true;
    return status;
}
References Slic3r::GUI::OpenGLManager::init_gl(), m_opengl_initialized, and m_opengl_mgr.
init_single_instance_checker()
void Slic3r::GUI::GUI_App::init_single_instance_checker (const std::string & name, const std::string & path)
{
    BOOST_LOG_TRIVIAL(debug) << "init wx instance checker " << name << " "<< path;
    m_single_instance_checker = std::make_unique<wxSingleInstanceChecker>(boost::nowide::widen(name), boost::nowide::widen(path));
}
References m_single_instance_checker, and boost::nowide::widen().
init_ui_colours()
void Slic3r::GUI::GUI_App::init_ui_colours ()
{
    m_color_label_modified          = get_label_default_clr_modified();
    m_color_label_sys               = get_label_default_clr_system();
    m_mode_palette                  = get_mode_default_palette();
    bool is_dark_mode = dark_mode();
#ifdef _WIN32
    m_color_label_default           = is_dark_mode ? wxColour(250, 250, 250): wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOWTEXT);
    m_color_highlight_label_default = is_dark_mode ? wxColour(230, 230, 230): wxSystemSettings::GetColour(/*wxSYS_COLOUR_HIGHLIGHTTEXT*/wxSYS_COLOUR_WINDOWTEXT);
    m_color_highlight_default       = is_dark_mode ? wxColour(78, 78, 78)   : wxSystemSettings::GetColour(wxSYS_COLOUR_3DLIGHT);
    m_color_hovered_btn_label       = is_dark_mode ? wxColour(253, 111, 40) : wxColour(252, 77, 1);
    m_color_default_btn_label       = is_dark_mode ? wxColour(255, 181, 100): wxColour(203, 61, 0);
    m_color_selected_btn_bg         = is_dark_mode ? wxColour(95, 73, 62)   : wxColour(228, 220, 216);
#else
    m_color_label_default = wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOWTEXT);
#endif
    m_color_window_default          = is_dark_mode ? wxColour(43, 43, 43)   : wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW);
}
References dark_mode(), get_label_default_clr_modified(), get_label_default_clr_system(), get_mode_default_palette(), m_color_label_default, m_color_label_modified, m_color_label_sys, m_color_window_default, and m_mode_palette.
Referenced by on_init_inner().
initialized()
bool Slic3r::GUI::GUI_App::initialized () const inline
{ return m_initialized; }
References m_initialized.
Referenced by post_init().
is_editor()
bool Slic3r::GUI::GUI_App::is_editor () const inline
{ return m_app_mode == EAppMode::Editor; }
References Editor, and m_app_mode.
Referenced by add_config_menu(), check_older_app_config(), config_wizard_startup(), init_app_config(), logo_name(), on_init_inner(), open_preferences(), and recreate_GUI().
is_gcode_viewer()
bool Slic3r::GUI::GUI_App::is_gcode_viewer () const inline
{ return m_app_mode == EAppMode::GCodeViewer; }
References GCodeViewer, and m_app_mode.
Referenced by post_init().
is_gl_version_greater_or_equal_to()
bool Slic3r::GUI::GUI_App::is_gl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const inline
{ return m_opengl_mgr.get_gl_info().is_version_greater_or_equal_to(major, minor); }
References Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::is_version_greater_or_equal_to(), and m_opengl_mgr.
is_glsl_version_greater_or_equal_to()
bool Slic3r::GUI::GUI_App::is_glsl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const inline
{ return m_opengl_mgr.get_gl_info().is_glsl_version_greater_or_equal_to(major, minor); }
References Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::is_glsl_version_greater_or_equal_to(), and m_opengl_mgr.
is_localized()
bool Slic3r::GUI::GUI_App::is_localized () const inline
{ return m_wxLocale->GetLocale() != "English"; }
References m_wxLocale.
is_recreating_gui()
bool Slic3r::GUI::GUI_App::is_recreating_gui () const inline
{ return m_is_recreating_gui; }
References m_is_recreating_gui.
keyboard_shortcuts()
void Slic3r::GUI::GUI_App::keyboard_shortcuts ()
{
    KBShortcutsDialog dlg;
    dlg.ShowModal();
}
link_font()
const wxFont & Slic3r::GUI::GUI_App::link_font () inline
{ return m_link_font; }
References m_link_font.
load_current_presets()
void Slic3r::GUI::GUI_App::load_current_presets (bool check_printer_presets = true)
{
    // check printer_presets for the containing information about "Print Host upload"
    // and create physical printer from it, if any exists
    if (check_printer_presets_)
        check_printer_presets();
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
  this->plater()->set_printer_technology(printer_technology);
    for (Tab *tab : tabs_list)
    if (tab->supports_printer_technology(printer_technology)) {
      if (tab->type() == Preset::TYPE_PRINTER) {
        static_cast<TabPrinter*>(tab)->update_pages();
        // Mark the plater to update print bed by tab->load_current_preset() from Plater::on_config_change().
        this->plater()->force_print_bed_update();
      }
      tab->load_current_preset();
    }
}
References check_printer_presets(), Slic3r::GUI::Plater::force_print_bed_update(), Slic3r::PresetCollection::get_edited_preset(), plater(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::GUI::Plater::set_printer_technology(), tabs_list, and Slic3r::Preset::TYPE_PRINTER.
Referenced by add_config_menu(), apply_keeped_preset_modifications(), check_and_keep_current_preset_changes(), check_and_save_current_preset_changes(), recreate_GUI(), and run_wizard().
load_gcode()
void Slic3r::GUI::GUI_App::load_gcode (wxWindow * parent, wxString & input_file) const
{
    input_file.Clear();
    wxFileDialog dialog(parent ? parent : GetTopWindow(),
        _L("Choose one file (GCODE/.GCO/.G/.ngc/NGC):"),
        app_config->get_last_dir(), "",
        file_wildcards(FT_GCODE), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() == wxID_OK)
        input_file = dialog.GetPath();
}
References _L, app_config, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_GCODE, and Slic3r::AppConfig::get_last_dir().
load_language()
bool Slic3r::GUI::GUI_App::load_language (wxString language, bool initial)
{
    if (initial) {
      // There is a static list of lookup path prefixes in wxWidgets. Add ours.
      wxFileTranslationsLoader::AddCatalogLookupPathPrefix(from_u8(localization_dir()));
      // Get the active language from PrusaSlicer.ini, or empty string if the key does not exist.
        language = app_config->get("translation_language");
        if (! language.empty())
          BOOST_LOG_TRIVIAL(trace) << boost::format("translation_language provided by PrusaSlicer.ini: %1%") % language;
        // Get the system language.
        {
          const wxLanguage lang_system = wxLanguage(wxLocale::GetSystemLanguage());
          if (lang_system != wxLANGUAGE_UNKNOWN) {
        m_language_info_system = wxLocale::GetLanguageInfo(lang_system);
            BOOST_LOG_TRIVIAL(trace) << boost::format("System language detected (user locales and such): %1%") % m_language_info_system->CanonicalName.ToUTF8().data();
          }
    }
        {
        // Allocating a temporary locale will switch the default wxTranslations to its internal wxTranslations instance.
        wxLocale temp_locale;
#ifdef __WXOSX__
            // ysFIXME - temporary workaround till it isn't fixed in wxWidgets:
            // Use English as an initial language, because of under OSX it try to load "inappropriate" language for wxLANGUAGE_DEFAULT.
            // For example in our case it's trying to load "en_CZ" and as a result PrusaSlicer catch warning message.
            // But wxWidgets guys work on it.
            temp_locale.Init(wxLANGUAGE_ENGLISH);
#else
            temp_locale.Init();
#endif // __WXOSX__
        // Set the current translation's language to default, otherwise GetBestTranslation() may not work (see the wxWidgets source code).
        wxTranslations::Get()->SetLanguage(wxLANGUAGE_DEFAULT);
        // Let the wxFileTranslationsLoader enumerate all translation dictionaries for PrusaSlicer
        // and try to match them with the system specific "preferred languages".
        // There seems to be a support for that on Windows and OSX, while on Linuxes the code just returns wxLocale::GetSystemLanguage().
        // The last parameter gets added to the list of detected dictionaries. This is a workaround
        // for not having the English dictionary. Let's hope wxWidgets of various versions process this call the same way.
      wxString best_language = wxTranslations::Get()->GetBestTranslation(SLIC3R_APP_KEY, wxLANGUAGE_ENGLISH);
      if (! best_language.IsEmpty()) {
        m_language_info_best = wxLocale::FindLanguageInfo(best_language);
            BOOST_LOG_TRIVIAL(trace) << boost::format("Best translation language detected (may be different from user locales): %1%") % m_language_info_best->CanonicalName.ToUTF8().data();
      }
            #ifdef __linux__
            wxString lc_all;
            if (wxGetEnv("LC_ALL", &lc_all) && ! lc_all.IsEmpty()) {
                // Best language returned by wxWidgets on Linux apparently does not respect LC_ALL.
                // Disregard the "best" suggestion in case LC_ALL is provided.
                m_language_info_best = nullptr;
            }
            #endif
    }
    }
  const wxLanguageInfo *language_info = language.empty() ? nullptr : wxLocale::FindLanguageInfo(language);
  if (! language.empty() && (language_info == nullptr || language_info->CanonicalName.empty())) {
    // Fix for wxWidgets issue, where the FindLanguageInfo() returns locales with undefined ANSII code (wxLANGUAGE_KONKANI or wxLANGUAGE_MANIPURI).
    language_info = nullptr;
      BOOST_LOG_TRIVIAL(error) << boost::format("Language code \"%1%\" is not supported") % language.ToUTF8().data();
  }
  if (language_info != nullptr && language_info->LayoutDirection == wxLayout_RightToLeft) {
      BOOST_LOG_TRIVIAL(trace) << boost::format("The following language code requires right to left layout, which is not supported by PrusaSlicer: %1%") % language_info->CanonicalName.ToUTF8().data();
    language_info = nullptr;
  }
    if (language_info == nullptr) {
        // PrusaSlicer does not support the Right to Left languages yet.
        if (m_language_info_system != nullptr && m_language_info_system->LayoutDirection != wxLayout_RightToLeft)
            language_info = m_language_info_system;
        if (m_language_info_best != nullptr && m_language_info_best->LayoutDirection != wxLayout_RightToLeft)
          language_info = m_language_info_best;
      if (language_info == nullptr)
      language_info = wxLocale::GetLanguageInfo(wxLANGUAGE_ENGLISH_US);
    }
  BOOST_LOG_TRIVIAL(trace) << boost::format("Switching wxLocales to %1%") % language_info->CanonicalName.ToUTF8().data();
    // Alternate language code.
    wxLanguage language_dict = wxLanguage(language_info->Language);
    if (language_info->CanonicalName.BeforeFirst('_') == "sk") {
      // Slovaks understand Czech well. Give them the Czech translation.
      language_dict = wxLANGUAGE_CZECH;
    BOOST_LOG_TRIVIAL(trace) << "Using Czech dictionaries for Slovak language";
    }
    // Select language for locales. This language may be different from the language of the dictionary.
    if (language_info == m_language_info_best || language_info == m_language_info_system) {
        // The current language matches user's default profile exactly. That's great.
    } else if (m_language_info_best != nullptr && language_info->CanonicalName.BeforeFirst('_') == m_language_info_best->CanonicalName.BeforeFirst('_')) {
        // Use whatever the operating system recommends, if it the language code of the dictionary matches the recommended language.
        // This allows a Swiss guy to use a German dictionary without forcing him to German locales.
        language_info = m_language_info_best;
    } else if (m_language_info_system != nullptr && language_info->CanonicalName.BeforeFirst('_') == m_language_info_system->CanonicalName.BeforeFirst('_'))
        language_info = m_language_info_system;
#ifdef __linux__
    // If we can't find this locale , try to use different one for the language
    // instead of just reporting that it is impossible to switch.
    if (! wxLocale::IsAvailable(language_info->Language)) {
        std::string original_lang = into_u8(language_info->CanonicalName);
        language_info = linux_get_existing_locale_language(language_info, m_language_info_system);
        BOOST_LOG_TRIVIAL(trace) << boost::format("Can't switch language to %1% (missing locales). Using %2% instead.")
                                    % original_lang % language_info->CanonicalName.ToUTF8().data();
    }
#endif
    if (! wxLocale::IsAvailable(language_info->Language)) {
      // Loading the language dictionary failed.
      wxString message = "Switching PrusaSlicer to language " + language_info->CanonicalName + " failed.";
#if !defined(_WIN32) && !defined(__APPLE__)
        // likely some linux system
        message += "\nYou may need to reconfigure the missing locales, likely by running the \"locale-gen\" and \"dpkg-reconfigure locales\" commands.\n";
#endif
        if (initial)
          message + "\n\nApplication will close.";
        wxMessageBox(message, "PrusaSlicer - Switching language failed", wxOK | wxICON_ERROR);
        if (initial)
      std::exit(EXIT_FAILURE);
    else
      return false;
    }
    // Release the old locales, create new locales.
    //FIXME wxWidgets cause havoc if the current locale is deleted. We just forget it causing memory leaks for now.
    m_wxLocale.release();
    m_wxLocale = Slic3r::make_unique<wxLocale>();
    m_wxLocale->Init(language_info->Language);
    // Override language at the active wxTranslations class (which is stored in the active m_wxLocale)
    // to load possibly different dictionary, for example, load Czech dictionary for Slovak language.
    wxTranslations::Get()->SetLanguage(language_dict);
    m_wxLocale->AddCatalog(SLIC3R_APP_KEY);
    m_imgui->set_language(into_u8(language_info->CanonicalName));
    //FIXME This is a temporary workaround, the correct solution is to switch to "C" locale during file import / export only.
    //wxSetlocale(LC_NUMERIC, "C");
    Preset::update_suffix_modified(format(" (%1%)", _L("modified")));
  return true;
}
References _L, app_config, error, Slic3r::GUI::format(), Slic3r::GUI::from_u8(), Slic3r::AppConfig::get(), Slic3r::GUI::into_u8(), Slic3r::localization_dir(), m_imgui, m_language_info_best, m_language_info_system, m_wxLocale, and Slic3r::Preset::update_suffix_modified().
Referenced by on_init_inner(), and select_language().
load_project()
void Slic3r::GUI::GUI_App::load_project (wxWindow * parent, wxString & input_file) const
{
    input_file.Clear();
    wxFileDialog dialog(parent ? parent : GetTopWindow(),
        _L("Choose one file (3MF/AMF):"),
        app_config->get_last_dir(), "",
        file_wildcards(FT_PROJECT), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() == wxID_OK)
        input_file = dialog.GetPath();
}
References _L, app_config, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_PROJECT, and Slic3r::AppConfig::get_last_dir().
logo_name()
std::string Slic3r::GUI::GUI_App::logo_name () const inline
{ return is_editor() ? "PrusaSlicer" : "PrusaSlicer-gcodeviewer"; }
References is_editor().
may_switch_to_SLA_preset()
bool Slic3r::GUI::GUI_App::may_switch_to_SLA_preset (const wxString & caption)
{
    if (model_has_parameter_modifiers_in_objects(model())) {
        show_info(nullptr,
            _L("It's impossible to print object(s) which contains parameter modifiers with SLA technology.") + "\n\n" +
            _L("Please check your object list before preset changing."),
            caption);
        return false;
    }
    return true;
}
References _L, model(), Slic3r::model_has_parameter_modifiers_in_objects(), and Slic3r::GUI::show_info().
Referenced by run_wizard().
model()
Model & Slic3r::GUI::GUI_App::model ()
{
    return plater_->model();
}
References Slic3r::GUI::Plater::model(), and plater_.
Referenced by may_switch_to_SLA_preset(), Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets(), and save_mode().
normal_font()
const wxFont & Slic3r::GUI::GUI_App::normal_font () inline
{ return m_normal_font; }
References m_normal_font.
Referenced by add_config_menu().
notification_manager()
NotificationManager * Slic3r::GUI::GUI_App::notification_manager ()
{
    return plater_->get_notification_manager();
}
References Slic3r::GUI::Plater::get_notification_manager(), and plater_.
obj_layers()
ObjectLayers * Slic3r::GUI::GUI_App::obj_layers ()
{
    return sidebar().obj_layers();
}
References Slic3r::GUI::Sidebar::obj_layers(), and sidebar().
obj_list()
ObjectList * Slic3r::GUI::GUI_App::obj_list ()
{
    return sidebar().obj_list();
}
References Slic3r::GUI::Sidebar::obj_list(), and sidebar().
Referenced by priv::create_volume(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::Emboss::CreateObjectJob::finalize(), recreate_GUI(), and Slic3r::GUI::Emboss::UpdateJob::update_volume().
obj_manipul()
ObjectManipulation * Slic3r::GUI::GUI_App::obj_manipul ()
{
    // If this method is called before plater_ has been initialized, return nullptr (to avoid a crash)
    return (plater_ != nullptr) ? sidebar().obj_manipul() : nullptr;
}
References Slic3r::GUI::Sidebar::obj_manipul(), plater_, and sidebar().
Referenced by Slic3r::GUI::ConfigWizard::run().
obj_settings()
ObjectSettings * Slic3r::GUI::GUI_App::obj_settings ()
{
    return sidebar().obj_settings();
}
References Slic3r::GUI::Sidebar::obj_settings(), and sidebar().
on_init_inner()
bool Slic3r::GUI::GUI_App::on_init_inner () private
{
    // Set initialization of image handlers before any UI actions - See GH issue #7469
    wxInitAllImageHandlers();
#if defined(_WIN32) && ! defined(_WIN64)
    // Win32 32bit build.
    if (wxPlatformInfo::Get().GetArchName().substr(0, 2) == "64") {
        RichMessageDialog dlg(nullptr,
            _L("You are running a 32 bit build of PrusaSlicer on 64-bit Windows."
                "\n32 bit build of PrusaSlicer will likely not be able to utilize all the RAM available in the system."
                "\nPlease download and install a 64 bit build of PrusaSlicer from https://www.prusa3d.cz/prusaslicer/."
                "\nDo you wish to continue?"),
            "PrusaSlicer", wxICON_QUESTION | wxYES_NO);
        if (dlg.ShowModal() != wxID_YES)
            return false;
    }
#endif // _WIN64
    // Forcing back menu icons under gtk2 and gtk3. Solution is based on:
    // https://docs.gtk.org/gtk3/class.Settings.html
    // see also https://docs.wxwidgets.org/3.0/classwx_menu_item.html#a2b5d6bcb820b992b1e4709facbf6d4fb
    // TODO: Find workaround for GTK4
#if defined(__WXGTK20__) || defined(__WXGTK3__)
    g_object_set (gtk_settings_get_default (), "gtk-menu-images", TRUE, NULL);
#endif
    // Verify resources path
    const wxString resources_dir = from_u8(Slic3r::resources_dir());
    wxCHECK_MSG(wxDirExists(resources_dir), false,
        wxString::Format("Resources path does not exist or is not a directory: %s", resources_dir));
#ifdef __linux__
    if (! check_old_linux_datadir(GetAppName())) {
        std::cerr << "Quitting, user chose to move their data to new location." << std::endl;
        return false;
    }
#endif
    // Enable this to get the default Win32 COMCTRL32 behavior of static boxes.
//    wxSystemOptions::SetOption("msw.staticbox.optimized-paint", 0);
    // Enable this to disable Windows Vista themes for all wxNotebooks. The themes seem to lead to terrible
    // performance when working on high resolution multi-display setups.
//    wxSystemOptions::SetOption("msw.notebook.themed-background", 0);
//     Slic3r::debugf "wxWidgets version %s, Wx version %s\n", wxVERSION_STRING, wxVERSION;
    // !!! Initialization of UI settings as a language, application color mode, fonts... have to be done before first UI action.
    // Like here, before the show InfoDialog in check_older_app_config()
    // If load_language() fails, the application closes.
    load_language(wxString(), true);
#ifdef _MSW_DARK_MODE
    bool init_dark_color_mode = app_config->get_bool("dark_color_mode");
    bool init_sys_menu_enabled = app_config->get_bool("sys_menu_enabled");
    NppDarkMode::InitDarkMode(init_dark_color_mode, init_sys_menu_enabled);
#endif
    // initialize label colors and fonts
    init_ui_colours();
    init_fonts();
    std::string older_data_dir_path;
    if (m_app_conf_exists) {
        if (app_config->orig_version().valid() && app_config->orig_version() < *Semver::parse(SLIC3R_VERSION)) {
            // Only copying configuration if it was saved with a newer slicer than the one currently running.
            older_data_dir_path = check_older_app_config(app_config->orig_version(), true);
            m_last_app_conf_lower_version = true;
        }
    } else {
        // No AppConfig exists, fresh install. Always try to copy from an alternate location, don't make backup of the current configuration.
        older_data_dir_path = check_older_app_config(Semver(), false);
        if (!older_data_dir_path.empty())
            m_last_app_conf_lower_version = true;
    }
#ifdef _MSW_DARK_MODE
    // app_config can be updated in check_older_app_config(), so check if dark_color_mode and sys_menu_enabled was changed
    if (bool new_dark_color_mode = app_config->get_bool("dark_color_mode");
        init_dark_color_mode != new_dark_color_mode) {
        NppDarkMode::SetDarkMode(new_dark_color_mode);
        init_ui_colours();
        update_ui_colours_from_appconfig();
    }
    if (bool new_sys_menu_enabled = app_config->get_bool("sys_menu_enabled");
        init_sys_menu_enabled != new_sys_menu_enabled)
        NppDarkMode::SetSystemMenuForApp(new_sys_menu_enabled);
#endif
    if (is_editor()) {
        std::string msg = Http::tls_global_init();
        std::string ssl_cert_store = app_config->get("tls_accepted_cert_store_location");
        bool ssl_accept = app_config->get("tls_cert_store_accepted") == "yes" && ssl_cert_store == Http::tls_system_cert_store();
        if (!msg.empty() && !ssl_accept) {
            RichMessageDialog
                dlg(nullptr,
                    wxString::Format(_L("%s\nDo you want to continue?"), msg),
                    "PrusaSlicer", wxICON_QUESTION | wxYES_NO);
            dlg.ShowCheckBox(_L("Remember my choice"));
            if (dlg.ShowModal() != wxID_YES) return false;
            app_config->set("tls_cert_store_accepted",
                dlg.IsCheckBoxChecked() ? "yes" : "no");
            app_config->set("tls_accepted_cert_store_location",
                dlg.IsCheckBoxChecked() ? Http::tls_system_cert_store() : "");
        }
    }
    SplashScreen* scrn = nullptr;
    if (app_config->get_bool("show_splash_screen")) {
        // make a bitmap with dark grey banner on the left side
        wxBitmap bmp = SplashScreen::MakeBitmap(wxBitmap(from_u8(var(is_editor() ? "splashscreen.jpg" : "splashscreen-gcodepreview.jpg")), wxBITMAP_TYPE_JPEG));
        // Detect position (display) to show the splash screen
        // Now this position is equal to the mainframe position
        wxPoint splashscreen_pos = wxDefaultPosition;
        bool default_splashscreen_pos = true;
        if (app_config->has("window_mainframe") && app_config->get_bool("restore_win_position")) {
            auto metrics = WindowMetrics::deserialize(app_config->get("window_mainframe"));
            default_splashscreen_pos = metrics == boost::none;
            if (!default_splashscreen_pos)
                splashscreen_pos = metrics->get_rect().GetPosition();
        }
        if (!default_splashscreen_pos) {
            // workaround for crash related to the positioning of the window on secondary monitor
            get_app_config()->set("restore_win_position", "crashed_at_splashscreen_pos");
            get_app_config()->save();
        }
        // create splash screen with updated bmp
        scrn = new SplashScreen(bmp.IsOk() ? bmp : get_bmp_bundle("PrusaSlicer", 400)->GetPreferredBitmapSizeAtScale(1.0),
                                wxSPLASH_CENTRE_ON_SCREEN | wxSPLASH_TIMEOUT, 4000, splashscreen_pos);
        if (!default_splashscreen_pos)
            // revert "restore_win_position" value if application wasn't crashed
            get_app_config()->set("restore_win_position", "1");
#ifndef __linux__
        wxYield();
#endif
        scrn->SetText(_L("Loading configuration")+ dots);
    }
    preset_bundle = new PresetBundle();
    // just checking for existence of Slic3r::data_dir is not enough : it may be an empty directory
    // supplied as argument to --datadir; in that case we should still run the wizard
    preset_bundle->setup_directories();
    if (! older_data_dir_path.empty()) {
        preset_bundle->import_newer_configs(older_data_dir_path);
        //app_config->save(); // It looks like redundant call of save. ysFIXME delete after testing
    }
    if (is_editor()) {
#ifdef __WXMSW__
        if (app_config->get_bool("associate_3mf"))
            associate_3mf_files();
        if (app_config->get_bool("associate_stl"))
            associate_stl_files();
#endif // __WXMSW__
        preset_updater = new PresetUpdater();
        Bind(EVT_SLIC3R_VERSION_ONLINE, &GUI_App::on_version_read, this);
        Bind(EVT_SLIC3R_EXPERIMENTAL_VERSION_ONLINE, [this](const wxCommandEvent& evt) {
            if (this->plater_ != nullptr && (m_app_updater->get_triggered_by_user() || app_config->get("notify_release") == "all")) {
                std::string evt_string = into_u8(evt.GetString());
                if (*Semver::parse(SLIC3R_VERSION) < *Semver::parse(evt_string)) {
                    auto notif_type = (evt_string.find("beta") != std::string::npos ? NotificationType::NewBetaAvailable : NotificationType::NewAlphaAvailable);
                    this->plater_->get_notification_manager()->push_version_notification( notif_type
                        , NotificationManager::NotificationLevel::ImportantNotificationLevel
                        , Slic3r::format(_u8L("New prerelease version %1% is available."), evt_string)
                        , _u8L("See Releases page.")
                        , [](wxEvtHandler* evnthndlr) {wxGetApp().open_browser_with_warning_dialog("https://github.com/prusa3d/PrusaSlicer/releases"); return true; }
                    );
                }
            }
            });
        Bind(EVT_SLIC3R_APP_DOWNLOAD_PROGRESS, [this](const wxCommandEvent& evt) {
            //lm:This does not force a render. The progress bar only updateswhen the mouse is moved.
            if (this->plater_ != nullptr)
                this->plater_->get_notification_manager()->set_download_progress_percentage((float)std::stoi(into_u8(evt.GetString())) / 100.f );
        });
        Bind(EVT_SLIC3R_APP_DOWNLOAD_FAILED, [this](const wxCommandEvent& evt) {
            if (this->plater_ != nullptr)
                this->plater_->get_notification_manager()->close_notification_of_type(NotificationType::AppDownload);
            if(!evt.GetString().IsEmpty())
                show_error(nullptr, evt.GetString());
        });
        Bind(EVT_SLIC3R_APP_OPEN_FAILED, [](const wxCommandEvent& evt) {
            show_error(nullptr, evt.GetString());
        });
    }
    else {
#ifdef __WXMSW__
        if (app_config->get_bool("associate_gcode"))
            associate_gcode_files();
#endif // __WXMSW__
    }
    std::string delayed_error_load_presets;
    // Suppress the '- default -' presets.
    preset_bundle->set_default_suppressed(app_config->get_bool("no_defaults"));
    try {
        // Enable all substitutions (in both user and system profiles), but log the substitutions in user profiles only.
        // If there are substitutions in system profiles, then a "reconfigure" event shall be triggered, which will force
        // installation of a compatible system preset, thus nullifying the system preset substitutions.
        init_params->preset_substitutions = preset_bundle->load_presets(*app_config, ForwardCompatibilitySubstitutionRule::EnableSystemSilent);
    } catch (const std::exception &ex) {
        delayed_error_load_presets = ex.what();
    }
#ifdef WIN32
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
    register_win32_dpi_event();
#endif // !wxVERSION_EQUAL_OR_GREATER_THAN
    register_win32_device_notification_event();
#endif // WIN32
    // Let the libslic3r know the callback, which will translate messages on demand.
    Slic3r::I18N::set_translate_callback(libslic3r_translate_callback);
    // application frame
    if (scrn && is_editor())
        scrn->SetText(_L("Preparing settings tabs") + dots);
    if (!delayed_error_load_presets.empty())
        show_error(nullptr, delayed_error_load_presets);
    mainframe = new MainFrame(app_config->has("font_size") ? atoi(app_config->get("font_size").c_str()) : -1);
    // hide settings tabs after first Layout
    if (is_editor())
        mainframe->select_tab(size_t(0));
    sidebar().obj_list()->init_objects(); // propagate model objects to object list
//     update_mode(); // !!! do that later
    SetTopWindow(mainframe);
    plater_->init_notification_manager();
    m_printhost_job_queue.reset(new PrintHostJobQueue(mainframe->printhost_queue_dlg()));
    if (is_gcode_viewer()) {
        mainframe->update_layout();
        if (plater_ != nullptr)
            // ensure the selected technology is ptFFF
            plater_->set_printer_technology(ptFFF);
    }
    else
        load_current_presets();
    // Save the active profiles as a "saved into project".
    update_saved_preset_from_current_preset();
    if (plater_ != nullptr) {
        // Save the names of active presets and project specific config into ProjectDirtyStateManager.
        plater_->reset_project_dirty_initial_presets();
        // Update Project dirty state, update application title bar.
        plater_->update_project_dirty_from_presets();
    }
    mainframe->Show(true);
    obj_list()->set_min_height();
    update_mode(); // update view mode after fix of the object_list size
#ifdef __APPLE__
    other_instance_message_handler()->bring_instance_forward();
#endif //__APPLE__
    Bind(wxEVT_IDLE, [this](wxIdleEvent& event)
    {
        if (! plater_)
            return;
        this->obj_manipul()->update_if_dirty();
        // An ugly solution to GH #5537 in which GUI_App::init_opengl (normally called from events wxEVT_PAINT
        // and wxEVT_SET_FOCUS before GUI_App::post_init is called) wasn't called before GUI_App::post_init and OpenGL wasn't initialized.
        // Since issue #9774 Where same problem occured on MacOS Ventura, we decided to have this check on MacOS as well.
#if defined(__linux__) || defined(__APPLE__)
        if (!m_post_initialized && m_opengl_initialized) {
#else
        if (!m_post_initialized) {
#endif
            m_post_initialized = true;
#ifdef WIN32
            this->mainframe->register_win32_callbacks();
#endif
            this->post_init();
        }
        if (m_post_initialized && app_config->dirty())
            app_config->save();
    });
    m_initialized = true;
    if (const std::string& crash_reason = app_config->get("restore_win_position");
        boost::starts_with(crash_reason,"crashed"))
    {
        wxString preferences_item = _L("Restore window position on start");
        InfoDialog dialog(nullptr,
            _L("PrusaSlicer started after a crash"),
            format_wxstr(_L("PrusaSlicer crashed last time when attempting to set window position.\n"
                "We are sorry for the inconvenience, it unfortunately happens with certain multiple-monitor setups.\n"
                "More precise reason for the crash: \"%1%\".\n"
                "For more information see our GitHub issue tracker: \"%2%\" and \"%3%\"\n\n"
                "To avoid this problem, consider disabling \"%4%\" in \"Preferences\". "
                "Otherwise, the application will most likely crash again next time."),
                "<b>" + from_u8(crash_reason) + "</b>",
                "<a href=http://github.com/prusa3d/PrusaSlicer/issues/2939>#2939</a>",
                "<a href=http://github.com/prusa3d/PrusaSlicer/issues/5573>#5573</a>",
                "<b>" + preferences_item + "</b>"),
            true, wxYES_NO);
        dialog.SetButtonLabel(wxID_YES, format_wxstr(_L("Disable \"%1%\""), preferences_item));
        dialog.SetButtonLabel(wxID_NO,  format_wxstr(_L("Leave \"%1%\" enabled") , preferences_item));
        auto answer = dialog.ShowModal();
        if (answer == wxID_YES)
            app_config->set("restore_win_position", "0");
        else if (answer == wxID_NO)
            app_config->set("restore_win_position", "1");
    }
    return true;
}
References _L, app_config, Slic3r::GUI::AppDownload, check_older_app_config(), Slic3r::GUI::NotificationManager::close_notification_of_type(), Slic3r::GUI::WindowMetrics::deserialize(), Slic3r::GUI::dots(), Slic3r::GUI::from_u8(), Slic3r::AppConfig::get(), Slic3r::GUI::get_app_config(), get_bmp_bundle(), Slic3r::AppConfig::get_bool(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::AppConfig::has(), Slic3r::PresetBundle::import_newer_configs(), init_fonts(), init_ui_colours(), Slic3r::GUI::into_u8(), is_editor(), load_language(), m_app_conf_exists, m_app_updater, m_last_app_conf_lower_version, Slic3r::GUI::SplashScreen::MakeBitmap(), on_version_read(), Slic3r::AppConfig::orig_version(), Slic3r::Semver::parse(), plater_, preset_bundle, preset_updater, Slic3r::resources_dir(), Slic3r::AppConfig::save(), Slic3r::AppConfig::set(), Slic3r::GUI::NotificationManager::set_download_progress_percentage(), Slic3r::GUI::SplashScreen::SetText(), Slic3r::PresetBundle::setup_directories(), Slic3r::GUI::show_error(), Slic3r::Http::tls_global_init(), Slic3r::Http::tls_system_cert_store(), TRUE, update_ui_colours_from_appconfig(), Slic3r::Semver::valid(), and Slic3r::var().
Referenced by OnInit().
on_version_read()
void Slic3r::GUI::GUI_App::on_version_read (wxCommandEvent & evt) private
{
    app_config->set("version_online", into_u8(evt.GetString()));
    std::string opt = app_config->get("notify_release");
    if (this->plater_ == nullptr || (!m_app_updater->get_triggered_by_user() && opt != "all" && opt != "release")) {
        BOOST_LOG_TRIVIAL(info) << "Version online: " << evt.GetString() << ". User does not wish to be notified.";
        return;
    }
    if (*Semver::parse(SLIC3R_VERSION) >= *Semver::parse(into_u8(evt.GetString()))) {
        if (m_app_updater->get_triggered_by_user())
        {
            std::string text = (*Semver::parse(into_u8(evt.GetString())) == Semver())
                ? _u8L("Check for application update has failed.")
                : Slic3r::format(_u8L("You are currently running the latest released version %1%."), evt.GetString());
            if (*Semver::parse(SLIC3R_VERSION) > *Semver::parse(into_u8(evt.GetString())))
                text = Slic3r::format(_u8L("There are no new released versions online. The latest release version is %1%."), evt.GetString());
            this->plater_->get_notification_manager()->push_version_notification(NotificationType::NoNewReleaseAvailable
                , NotificationManager::NotificationLevel::RegularNotificationLevel
                , text
                , std::string()
                , std::function<bool(wxEvtHandler*)>()
            );
        }
        return;
    }
    // notification
    /*
    this->plater_->get_notification_manager()->push_notification(NotificationType::NewAppAvailable
        , NotificationManager::NotificationLevel::ImportantNotificationLevel
        , Slic3r::format(_u8L("New release version %1% is available."), evt.GetString())
        , _u8L("See Download page.")
        , [](wxEvtHandler* evnthndlr) {wxGetApp().open_web_page_localized("https://www.prusa3d.com/slicerweb"); return true; }
    );
    */
    // updater
    // read triggered_by_user that was set when calling  GUI_App::app_version_check
    app_updater(m_app_updater->get_triggered_by_user());
}
References _u8L, app_config, app_updater(), Slic3r::format(), Slic3r::AppConfig::get(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::GUI::into_u8(), m_app_updater, Slic3r::GUI::NoNewReleaseAvailable, Slic3r::Semver::parse(), plater_, Slic3r::GUI::NotificationManager::push_version_notification(), Slic3r::GUI::NotificationManager::RegularNotificationLevel, and Slic3r::AppConfig::set().
Referenced by on_init_inner().
OnExceptionInMainLoop()
bool Slic3r::GUI::GUI_App::OnExceptionInMainLoop () override virtual
{
    generic_exception_handle();
    return false;
}
References Slic3r::GUI::generic_exception_handle().
OnInit()
bool Slic3r::GUI::GUI_App::OnInit () override
{
    try {
        return on_init_inner();
    } catch (const std::exception&) {
        generic_exception_handle();
        return false;
    }
}
References Slic3r::GUI::generic_exception_handle(), and on_init_inner().
open_browser_with_warning_dialog()
bool Slic3r::GUI::GUI_App::open_browser_with_warning_dialog (const wxString & url, wxWindow * parent = nullptr, bool force_remember_choice = true, int flags = 0)
{
    bool launch = true;
    // warning dialog containes a "Remember my choice" checkbox
    std::string option_key = "suppress_hyperlinks";
    if (force_remember_choice || app_config->get(option_key).empty()) {
        if (app_config->get(option_key).empty()) {
            RichMessageDialog dialog(parent, _L("Open hyperlink in default browser?"), _L("PrusaSlicer: Open hyperlink"), wxICON_QUESTION | wxYES_NO);
            dialog.ShowCheckBox(_L("Remember my choice"));
            auto answer = dialog.ShowModal();
            launch = answer == wxID_YES;
            if (dialog.IsCheckBoxChecked()) {
                wxString preferences_item = _L("Suppress to open hyperlink in browser");
                wxString msg =
                    _L("PrusaSlicer will remember your choice.") + "\n\n" +
                    _L("You will not be asked about it again on hyperlinks hovering.") + "\n\n" +
                    format_wxstr(_L("Visit \"Preferences\" and check \"%1%\"\nto changes your choice."), preferences_item);
                MessageDialog msg_dlg(parent, msg, _L("PrusaSlicer: Don't ask me again"), wxOK | wxCANCEL | wxICON_INFORMATION);
                if (msg_dlg.ShowModal() == wxID_CANCEL)
                    return false;
                app_config->set(option_key, answer == wxID_NO ? "1" : "0");
            }
        }
        if (launch)
            launch = !app_config->get_bool(option_key);
    }
    // warning dialog doesn't containe a "Remember my choice" checkbox
    // and will be shown only when "Suppress to open hyperlink in browser" is ON.
    else if (app_config->get_bool(option_key)) {
        MessageDialog dialog(parent, _L("Open hyperlink in default browser?"), _L("PrusaSlicer: Open hyperlink"), wxICON_QUESTION | wxYES_NO);
        launch = dialog.ShowModal() == wxID_YES;
    }
    return  launch && wxLaunchDefaultBrowser(url, flags);
}
References _L, app_config, Slic3r::GUI::format_wxstr(), Slic3r::AppConfig::get(), Slic3r::AppConfig::get_bool(), and Slic3r::AppConfig::set().
Referenced by open_web_page_localized().
open_preferences()
void Slic3r::GUI::GUI_App::open_preferences (const std::string & highlight_option = std::string(), const std::string & tab_name = std::string())
{
    mainframe->preferences_dialog->show(highlight_option, tab_name);
    if (mainframe->preferences_dialog->recreate_GUI())
        recreate_GUI(_L("Restart application") + dots);
#if ENABLE_GCODE_LINES_ID_IN_H_SLIDER
    if (dlg.seq_top_layer_only_changed() || dlg.seq_seq_top_gcode_indices_changed())
#else
    if (mainframe->preferences_dialog->seq_top_layer_only_changed())
#endif // ENABLE_GCODE_LINES_ID_IN_H_SLIDER
        this->plater_->refresh_print();
#ifdef _WIN32
    if (is_editor()) {
        if (app_config->get_bool("associate_3mf"))
            associate_3mf_files();
        if (app_config->get_bool("associate_stl"))
            associate_stl_files();
    }
    else {
        if (app_config->get_bool("associate_gcode"))
            associate_gcode_files();
    }
#endif // _WIN32
    if (mainframe->preferences_dialog->settings_layout_changed()) {
        // hide full main_sizer for mainFrame
        mainframe->GetSizer()->Show(false);
        mainframe->update_layout();
        mainframe->select_tab(size_t(0));
    }
}
References _L, app_config, Slic3r::GUI::dots(), Slic3r::AppConfig::get_bool(), is_editor(), mainframe, plater_, Slic3r::GUI::MainFrame::preferences_dialog, Slic3r::GUI::PreferencesDialog::recreate_GUI(), recreate_GUI(), Slic3r::GUI::Plater::refresh_print(), Slic3r::GUI::MainFrame::select_tab(), Slic3r::GUI::PreferencesDialog::seq_top_layer_only_changed(), Slic3r::GUI::PreferencesDialog::settings_layout_changed(), Slic3r::GUI::PreferencesDialog::show(), and Slic3r::GUI::MainFrame::update_layout().
Referenced by add_config_menu().
open_web_page_localized()
void Slic3r::GUI::GUI_App::open_web_page_localized (const std::string & http_address)
{
    open_browser_with_warning_dialog(http_address + "&lng=" + this->current_language_code_safe(), nullptr, false);
}
References current_language_code_safe(), and open_browser_with_warning_dialog().
other_instance_message_handler()
OtherInstanceMessageHandler * Slic3r::GUI::GUI_App::other_instance_message_handler () inline
{ return m_other_instance_message_handler.get(); }
References m_other_instance_message_handler.
persist_window_geometry()
void Slic3r::GUI::GUI_App::persist_window_geometry (wxTopLevelWindow * window, bool default_maximized = false)
{
    const std::string name = into_u8(window->GetName());
    window->Bind(wxEVT_CLOSE_WINDOW, [=](wxCloseEvent &event) {
        window_pos_save(window, name);
        event.Skip();
    });
    window_pos_restore(window, name, default_maximized);
    on_window_geometry(window, [=]() {
        window_pos_sanitize(window);
    });
}
References Slic3r::GUI::into_u8(), Slic3r::GUI::on_window_geometry(), window_pos_restore(), window_pos_sanitize(), and window_pos_save().
plater() [1/2]
Plater * Slic3r::GUI::GUI_App::plater ()
{
    return plater_;
}
References plater_.
Referenced by can_load_project(), priv::create_volume(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::Emboss::CreateObjectJob::finalize(), load_current_presets(), post_init(), Slic3r::GUI::ProjectDirtyStateManager::update_from_presets(), update_mode(), and Slic3r::GUI::Emboss::UpdateJob::update_volume().
plater() [2/2]
const Plater * Slic3r::GUI::GUI_App::plater () const
{
    return plater_;
}
References plater_.
post_init()
void Slic3r::GUI::GUI_App::post_init ()
{
    assert(initialized());
    if (! this->initialized())
        throw Slic3r::RuntimeError("Calling post_init() while not yet initialized");
    if (this->is_gcode_viewer()) {
        if (! this->init_params->input_files.empty())
            this->plater()->load_gcode(wxString::FromUTF8(this->init_params->input_files[0].c_str()));
    }
    else if (this->init_params->start_downloader) {
        start_download(this->init_params->download_url);
    } else {
        if (! this->init_params->preset_substitutions.empty())
            show_substitutions_info(this->init_params->preset_substitutions);
#if 0
        // Load the cummulative config over the currently active profiles.
        //FIXME if multiple configs are loaded, only the last one will have an effect.
        // We need to decide what to do about loading of separate presets (just print preset, just filament preset etc).
        // As of now only the full configs are supported here.
        if (!m_print_config.empty())
            this->gui->mainframe->load_config(m_print_config);
#endif
        if (! this->init_params->load_configs.empty())
            // Load the last config to give it a name at the UI. The name of the preset may be later
            // changed by loading an AMF or 3MF.
            //FIXME this is not strictly correct, as one may pass a print/filament/printer profile here instead of a full config.
            this->mainframe->load_config_file(this->init_params->load_configs.back());
        // If loading a 3MF file, the config is loaded from the last one.
        if (!this->init_params->input_files.empty()) {
#if 1 // #ysFIXME_delete_after_test_of
            wxArrayString fns;
            for (const std::string& name : this->init_params->input_files)
                fns.Add(from_u8(name));
            if (plater()->load_files(fns) && this->init_params->input_files.size() == 1) {
#else
            const std::vector<size_t> res = this->plater()->load_files(this->init_params->input_files, true, true);
            if (!res.empty() && this->init_params->input_files.size() == 1) {
#endif
                // Update application titlebar when opening a project file
                const std::string& filename = this->init_params->input_files.front();
                if (boost::algorithm::iends_with(filename, ".amf") ||
                    boost::algorithm::iends_with(filename, ".amf.xml") ||
                    boost::algorithm::iends_with(filename, ".3mf"))
                    this->plater()->set_project_filename(from_u8(filename));
            }
            if (this->init_params->delete_after_load) {
                for (const std::string& p : this->init_params->input_files) {
                    boost::system::error_code ec;
                    boost::filesystem::remove(boost::filesystem::path(p), ec);
                    if (ec) {
                        BOOST_LOG_TRIVIAL(error) << ec.message();
                    }
                }
            }
        }
        if (! this->init_params->extra_config.empty())
            this->mainframe->load_config(this->init_params->extra_config);
    }
    // show "Did you know" notification
    if (app_config->get_bool("show_hints") && ! is_gcode_viewer())
        plater_->get_notification_manager()->push_hint_notification(true);
    // The extra CallAfter() is needed because of Mac, where this is the only way
    // to popup a modal dialog on start without screwing combo boxes.
    // This is ugly but I honestly found no better way to do it.
    // Neither wxShowEvent nor wxWindowCreateEvent work reliably.
    if (this->preset_updater) { // G-Code Viewer does not initialize preset_updater.
        if (! this->check_updates(false))
            // Configuration is not compatible and reconfigure was refused by the user. Application is closing.
            return;
        CallAfter([this] {
            // preset_updater->sync downloads profile updates on background so it must begin after config wizard finished.
            bool cw_showed = this->config_wizard_startup();
            this->preset_updater->sync(preset_bundle);
            if (! cw_showed) {
                // The CallAfter is needed as well, without it, GL extensions did not show.
                // Also, we only want to show this when the wizard does not, so the new user
                // sees something else than "we want something" on the first start.
                show_send_system_info_dialog_if_needed();
            }
            // app version check is asynchronous and triggers blocking dialog window, better call it last
            this->app_version_check(false);
        });
    }
    // Set PrusaSlicer version and save to PrusaSlicer.ini or PrusaSlicerGcodeViewer.ini.
    app_config->set("version", SLIC3R_VERSION);
#ifdef _WIN32
    // Sets window property to mainframe so other instances can indentify it.
    OtherInstanceMessageHandler::init_windows_properties(mainframe, m_instance_hash_int);
#endif //WIN32
}
References app_config, app_version_check(), check_updates(), config_wizard_startup(), Slic3r::GUI::GUI_InitParams::delete_after_load, Slic3r::GUI::GUI_InitParams::download_url, Slic3r::DynamicConfig::empty(), error, Slic3r::GUI::GUI_InitParams::extra_config, Slic3r::GUI::from_u8(), Slic3r::AppConfig::get_bool(), Slic3r::GUI::Plater::get_notification_manager(), init_params, initialized(), Slic3r::GUI::GUI_InitParams::input_files, is_gcode_viewer(), Slic3r::GUI::MainFrame::load_config(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::GUI_InitParams::load_configs, Slic3r::GUI::Plater::load_files(), Slic3r::GUI::Plater::load_gcode(), m_instance_hash_int, mainframe, plater(), plater_, preset_bundle, Slic3r::GUI::GUI_InitParams::preset_substitutions, preset_updater, Slic3r::GUI::NotificationManager::push_hint_notification(), Slic3r::AppConfig::set(), Slic3r::GUI::Plater::set_project_filename(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), start_download(), Slic3r::GUI::GUI_InitParams::start_downloader, and Slic3r::PresetUpdater::sync().
printhost_job_queue()
PrintHostJobQueue & Slic3r::GUI::GUI_App::printhost_job_queue () inline
{ return *m_printhost_job_queue.get(); }
References m_printhost_job_queue.
recreate_GUI()
void Slic3r::GUI::GUI_App::recreate_GUI (const wxString & message)
{
    m_is_recreating_gui = true;
    mainframe->shutdown();
    wxProgressDialog dlg(msg_name, msg_name, 100, nullptr, wxPD_AUTO_HIDE);
    dlg.Pulse();
    dlg.Update(10, _L("Recreating") + dots);
    MainFrame *old_main_frame = mainframe;
    mainframe = new MainFrame(app_config->has("font_size") ? atoi(app_config->get("font_size").c_str()) : -1);
    if (is_editor())
        // hide settings tabs after first Layout
        mainframe->select_tab(size_t(0));
    // Propagate model objects to object list.
    sidebar().obj_list()->init_objects();
    SetTopWindow(mainframe);
    dlg.Update(30, _L("Recreating") + dots);
    old_main_frame->Destroy();
    dlg.Update(80, _L("Loading of current presets") + dots);
    m_printhost_job_queue.reset(new PrintHostJobQueue(mainframe->printhost_queue_dlg()));
    load_current_presets();
    mainframe->Show(true);
    dlg.Update(90, _L("Loading of a mode view") + dots);
    obj_list()->set_min_height();
    update_mode();
    // #ys_FIXME_delete_after_testing  Do we still need this  ?
//     CallAfter([]() {
//         // Run the config wizard, don't offer the "reset user profile" checkbox.
//         config_wizard_startup(true);
//     });
    m_is_recreating_gui = false;
}
References _L, app_config, Slic3r::GUI::dots(), Slic3r::AppConfig::get(), Slic3r::AppConfig::has(), Slic3r::GUI::ObjectList::init_objects(), is_editor(), load_current_presets(), m_is_recreating_gui, m_printhost_job_queue, mainframe, obj_list(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::MainFrame::printhost_queue_dlg(), Slic3r::GUI::MainFrame::select_tab(), Slic3r::GUI::ObjectList::set_min_height(), Slic3r::GUI::MainFrame::shutdown(), sidebar(), and update_mode().
Referenced by open_preferences(), and switch_language().
removable_drive_manager()
RemovableDriveManager * Slic3r::GUI::GUI_App::removable_drive_manager () inline
{ return m_removable_drive_manager.get(); }
References m_removable_drive_manager.
run_wizard()
bool Slic3r::GUI::GUI_App::run_wizard (ConfigWizard::RunReason reason, ConfigWizard::StartPage start_page = ConfigWizard::SP_WELCOME)
{
    wxCHECK_MSG(mainframe != nullptr, false, "Internal error: Main frame not created / null");
    if (reason == ConfigWizard::RR_USER) {
        // Cancel sync before starting wizard to prevent two downloads at same time
        preset_updater->cancel_sync();
        preset_updater->update_index_db();
        if (preset_updater->config_update(app_config->orig_version(), PresetUpdater::UpdateParams::FORCED_BEFORE_WIZARD) == PresetUpdater::R_ALL_CANCELED)
            return false;
    }
    auto wizard = new ConfigWizard(mainframe);
    const bool res = wizard->run(reason, start_page);
    // !!! Deallocate memory after close ConfigWizard.
    // Note, that mainframe is a parent of ConfigWizard.
    // So, wizard will be destroyed only during destroying of mainframe
    // To avoid this state the wizard have to be disconnected from mainframe and Destroyed explicitly
    mainframe->RemoveChild(wizard);
    wizard->Destroy();
    if (res) {
        load_current_presets();
        // #ysFIXME - delete after testing: This part of code looks redundant. All checks are inside ConfigWizard::priv::apply_config()
        if (preset_bundle->printers.get_edited_preset().printer_technology() == ptSLA)
            may_switch_to_SLA_preset(_L("Configuration is editing from ConfigWizard"));
    }
    return res;
}
References _L, app_config, Slic3r::PresetUpdater::cancel_sync(), Slic3r::PresetUpdater::config_update(), Slic3r::PresetUpdater::FORCED_BEFORE_WIZARD, Slic3r::PresetCollection::get_edited_preset(), load_current_presets(), mainframe, may_switch_to_SLA_preset(), Slic3r::AppConfig::orig_version(), preset_bundle, preset_updater, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptSLA, Slic3r::PresetUpdater::R_ALL_CANCELED, Slic3r::GUI::ConfigWizard::RR_USER, and Slic3r::PresetUpdater::update_index_db().
Referenced by add_config_menu(), and config_wizard_startup().
save_mode()
bool Slic3r::GUI::GUI_App::save_mode (const int mode)
{
    const std::string mode_str = mode == comExpert ? "expert" :
                                 mode == comSimple ? "simple" : "advanced";
    auto can_switch_to_simple = [](Model& model) {
        for (const ModelObject* model_object : model.objects)
            if (model_object->volumes.size() > 1) {
                for (size_t i = 1; i < model_object->volumes.size(); ++i)
                    if (!model_object->volumes[i]->is_support_modifier())
                        return false;
            }
        return true;
    };
    if (mode == comSimple && !can_switch_to_simple(model())) {
        show_info(nullptr,
            _L("Simple mode supports manipulation with single-part object(s)\n"
            "or object(s) with support modifiers only.") + "\n\n" +
            _L("Please check your object list before mode changing."),
            _L("Change application mode"));
        return false;
    }
    app_config->set("view_mode", mode_str);
    update_mode();
    return true;
}
References _L, app_config, Slic3r::comExpert, Slic3r::comSimple, model(), Slic3r::Model::objects, Slic3r::AppConfig::set(), Slic3r::GUI::show_info(), and update_mode().
Referenced by add_config_menu().
select_language()
bool Slic3r::GUI::GUI_App::select_language () private
{
  wxArrayString translations = wxTranslations::Get()->GetAvailableTranslations(SLIC3R_APP_KEY);
    std::vector<const wxLanguageInfo*> language_infos;
    language_infos.emplace_back(wxLocale::GetLanguageInfo(wxLANGUAGE_ENGLISH));
    for (size_t i = 0; i < translations.GetCount(); ++ i) {
      const wxLanguageInfo *langinfo = wxLocale::FindLanguageInfo(translations[i]);
        if (langinfo != nullptr)
            language_infos.emplace_back(langinfo);
    }
    sort_remove_duplicates(language_infos);
  std::sort(language_infos.begin(), language_infos.end(), [](const wxLanguageInfo* l, const wxLanguageInfo* r) { return l->Description < r->Description; });
    wxArrayString names;
    names.Alloc(language_infos.size());
    // Some valid language should be selected since the application start up.
    const wxLanguage current_language = wxLanguage(m_wxLocale->GetLanguage());
    int          init_selection       = -1;
    int        init_selection_alt     = -1;
    int        init_selection_default = -1;
    for (size_t i = 0; i < language_infos.size(); ++ i) {
        if (wxLanguage(language_infos[i]->Language) == current_language)
          // The dictionary matches the active language and country.
            init_selection = i;
        else if ((language_infos[i]->CanonicalName.BeforeFirst('_') == m_wxLocale->GetCanonicalName().BeforeFirst('_')) ||
             // if the active language is Slovak, mark the Czech language as active.
               (language_infos[i]->CanonicalName.BeforeFirst('_') == "cs" && m_wxLocale->GetCanonicalName().BeforeFirst('_') == "sk"))
          // The dictionary matches the active language, it does not necessarily match the country.
          init_selection_alt = i;
        if (language_infos[i]->CanonicalName.BeforeFirst('_') == "en")
          // This will be the default selection if the active language does not match any dictionary.
          init_selection_default = i;
        names.Add(language_infos[i]->Description);
    }
    if (init_selection == -1)
      // This is the dictionary matching the active language.
      init_selection = init_selection_alt;
    if (init_selection != -1)
      // This is the language to highlight in the choice dialog initially.
      init_selection_default = init_selection;
    const long index = GetSingleChoiceIndex(_L("Select the language"), _L("Language"), names, init_selection_default);
  // Try to load a new language.
    if (index != -1 && (init_selection == -1 || init_selection != index)) {
      const wxLanguageInfo *new_language_info = language_infos[index];
      if (this->load_language(new_language_info->CanonicalName, false)) {
      // Save language at application config.
            // Which language to save as the selected dictionary language?
            // 1) Hopefully the language set to wxTranslations by this->load_language(), but that API is weird and we don't want to rely on its
            //    stability in the future:
            //    wxTranslations::Get()->GetBestTranslation(SLIC3R_APP_KEY, wxLANGUAGE_ENGLISH);
            // 2) Current locale language may not match the dictionary name, see GH issue #3901
            //    m_wxLocale->GetCanonicalName()
            // 3) new_language_info->CanonicalName is a safe bet. It points to a valid dictionary name.
      app_config->set("translation_language", new_language_info->CanonicalName.ToUTF8().data());
        return true;
      }
    }
    return false;
}
References _L, app_config, GetSingleChoiceIndex(), load_language(), m_wxLocale, Slic3r::AppConfig::set(), and Slic3r::sort_remove_duplicates().
Referenced by switch_language().
set_auto_toolbar_icon_scale()
void Slic3r::GUI::GUI_App::set_auto_toolbar_icon_scale (float scale) const
{
#ifdef __APPLE__
    const float icon_sc = 1.0f; // for Retina display will be used its own scale
#else
    const float icon_sc = m_em_unit * 0.1f;
#endif // __APPLE__
    long int_val = std::min(int(std::lround(scale / icon_sc * 100)), 100);
    std::string val = std::to_string(int_val);
    app_config->set("auto_toolbar_size", val);
}
References app_config, m_em_unit, scale(), and Slic3r::AppConfig::set().
set_instance_hash()
void Slic3r::GUI::GUI_App::set_instance_hash (const size_t hash) inline
{ m_instance_hash_int = hash; m_instance_hash_string = std::to_string(hash); }
References m_instance_hash_int, and m_instance_hash_string.
set_label_clr_modified()
void Slic3r::GUI::GUI_App::set_label_clr_modified (const wxColour & clr)
{
    if (m_color_label_modified == clr)
        return;
    m_color_label_modified = clr;
    const std::string str = encode_color(ColorRGB(clr.Red(), clr.Green(), clr.Blue()));
    app_config->set("label_clr_modified", str);
}
References app_config, Slic3r::encode_color(), m_color_label_modified, and Slic3r::AppConfig::set().
set_label_clr_sys()
void Slic3r::GUI::GUI_App::set_label_clr_sys (const wxColour & clr)
{
    if (m_color_label_sys == clr)
        return;
    m_color_label_sys = clr;
    const std::string str = encode_color(ColorRGB(clr.Red(), clr.Green(), clr.Blue()));
    app_config->set("label_clr_sys", str);
}
References app_config, Slic3r::encode_color(), m_color_label_sys, and Slic3r::AppConfig::set().
set_mode_palette()
void Slic3r::GUI::GUI_App::set_mode_palette (const std::vector< wxColour > & palette)
{
    bool save = false;
    for (size_t mode = 0; mode < palette.size(); ++mode) {
        const wxColour& clr = palette[mode];
        std::string color_str = clr == wxTransparentColour ? std::string("") : encode_color(ColorRGB(clr.Red(), clr.Green(), clr.Blue()));
        if (m_mode_palette[mode] != color_str) {
            m_mode_palette[mode] = color_str;
            save = true;
        }
    }
    if (save) {
        mainframe->update_mode_markers();
        app_config->set("mode_palette", escape_strings_cstyle(m_mode_palette));
    }
}
References app_config, Slic3r::encode_color(), Slic3r::escape_strings_cstyle(), m_mode_palette, mainframe, save(), Slic3r::AppConfig::set(), and Slic3r::GUI::MainFrame::update_mode_markers().
show_desktop_integration_dialog()
void Slic3r::GUI::GUI_App::show_desktop_integration_dialog ()
{
#ifdef __linux__
    //wxCHECK_MSG(mainframe != nullptr, false, "Internal error: Main frame not created / null");
    DesktopIntegrationDialog dialog(mainframe);
    dialog.ShowModal();
#endif //__linux__
}
References mainframe.
Referenced by add_config_menu().
show_downloader_registration_dialog()
void Slic3r::GUI::GUI_App::show_downloader_registration_dialog ()
{
    InfoDialog msg(nullptr
        , format_wxstr(_L("Welcome to %1% version %2%."), SLIC3R_APP_NAME, SLIC3R_VERSION)
        , format_wxstr(_L(
            "Do you wish to register downloads from <b>Printables.com</b>"
            "\nfor this <b>%1% %2%</b> executable?"
            "\n\nDownloads can be registered for only 1 executable at time."
            ), SLIC3R_APP_NAME, SLIC3R_VERSION)
        , true, wxYES_NO);
    if (msg.ShowModal() == wxID_YES) {
        auto downloader_worker = new DownloaderUtils::Worker(nullptr);
        downloader_worker->perform_register(app_config->get("url_downloader_dest"));
#ifdef __linux__
        if (downloader_worker->get_perform_registration_linux())
            DesktopIntegrationDialog::perform_downloader_desktop_integration();
#endif // __linux__
    } else {
        app_config->set("downloader_url_registered", "0");
    }
}
References _L, app_config, Slic3r::GUI::format_wxstr(), Slic3r::AppConfig::get(), and Slic3r::AppConfig::set().
Referenced by config_wizard_startup().
sidebar()
Sidebar & Slic3r::GUI::GUI_App::sidebar ()
{
    return plater_->sidebar();
}
References plater_, and Slic3r::GUI::Plater::sidebar().
Referenced by obj_layers(), obj_list(), obj_manipul(), obj_settings(), recreate_GUI(), and update_mode().
single_instance_checker()
wxSingleInstanceChecker * Slic3r::GUI::GUI_App::single_instance_checker () inline
{return m_single_instance_checker.get();}
References m_single_instance_checker.
small_font()
const wxFont & Slic3r::GUI::GUI_App::small_font () inline
{ return m_small_font; }
References m_small_font.
start_download()
void Slic3r::GUI::GUI_App::start_download (std::string url)
{
    if (!plater_) {
        BOOST_LOG_TRIVIAL(error) << "Could not start URL download: plater is nullptr.";
        return;
    }
    //lets always init so if the download dest folder was changed, new dest is used
        boost::filesystem::path dest_folder(app_config->get("url_downloader_dest"));
        if (dest_folder.empty() || !boost::filesystem::is_directory(dest_folder)) {
            std::string msg = _u8L("Could not start URL download. Destination folder is not set. Please choose destination folder in Configuration Wizard.");
            BOOST_LOG_TRIVIAL(error) << msg;
            show_error(nullptr, msg);
            return;
        }
    m_downloader->init(dest_folder);
    m_downloader->start_download(url);
}
References _u8L, app_config, error, Slic3r::AppConfig::get(), m_downloader, plater_, and Slic3r::GUI::show_error().
Referenced by post_init().
switch_language()
bool Slic3r::GUI::GUI_App::switch_language ()
{
    if (select_language()) {
        recreate_GUI(_L("Changing of an application language") + dots);
        return true;
    } else {
        return false;
    }
}
References _L, Slic3r::GUI::dots(), recreate_GUI(), and select_language().
Referenced by add_config_menu().
system_info()
void Slic3r::GUI::GUI_App::system_info ()
{
    SysInfoDialog dlg;
    dlg.ShowModal();
}
tab_panel()
wxBookCtrlBase * Slic3r::GUI::GUI_App::tab_panel () const
{
    return mainframe->m_tabpanel;
}
References Slic3r::GUI::MainFrame::m_tabpanel, and mainframe.
tabs_as_menu()
bool Slic3r::GUI::GUI_App::tabs_as_menu () const
{
    return app_config->get_bool("tabs_as_menu"); // || dark_mode();
}
References app_config, and Slic3r::AppConfig::get_bool().
Referenced by update_mode().
toolbar_icon_scale()
float Slic3r::GUI::GUI_App::toolbar_icon_scale (const bool is_limited = false) const
{
#ifdef __APPLE__
    const float icon_sc = 1.0f; // for Retina display will be used its own scale
#else
    const float icon_sc = m_em_unit*0.1f;
#endif // __APPLE__
    const std::string& use_val  = app_config->get("use_custom_toolbar_size");
    const std::string& val      = app_config->get("custom_toolbar_size");
    const std::string& auto_val = app_config->get("auto_toolbar_size");
    if (val.empty() || auto_val.empty() || use_val.empty())
        return icon_sc;
    int int_val = use_val == "0" ? 100 : atoi(val.c_str());
    // correct value in respect to auto_toolbar_size
    int_val = std::min(atoi(auto_val.c_str()), int_val);
    if (is_limited && int_val < 50)
        int_val = 50;
    return 0.01f * int_val * icon_sc;
}
References app_config, Slic3r::AppConfig::get(), and m_em_unit.
update_fonts()
void Slic3r::GUI::GUI_App::update_fonts (const MainFrame * main_frame = nullptr)
{
    /* Only normal and bold fonts are used for an application rescale,
     * because of under MSW small and normal fonts are the same.
     * To avoid same rescaling twice, just fill this values
     * from rescaled MainFrame
     */
  if (main_frame == nullptr)
    main_frame = this->mainframe;
    m_normal_font   = main_frame->normal_font();
    m_small_font    = m_normal_font;
    m_bold_font     = main_frame->normal_font().Bold();
    m_link_font     = m_bold_font.Underlined();
    m_em_unit       = main_frame->em_unit();
    m_code_font.SetPointSize(m_normal_font.GetPointSize());
}
References Slic3r::GUI::DPIAware< P >::em_unit(), m_bold_font, m_code_font, m_em_unit, m_link_font, m_normal_font, m_small_font, mainframe, and Slic3r::GUI::DPIAware< P >::normal_font().
update_label_colours()
void Slic3r::GUI::GUI_App::update_label_colours ()
{
    for (Tab* tab : tabs_list)
        tab->update_label_colours();
}
References tabs_list.
Referenced by update_ui_from_settings().
update_mode()
void Slic3r::GUI::GUI_App::update_mode ()
{
    sidebar().update_mode();
#ifdef _WIN32 //_MSW_DARK_MODE
    if (!wxGetApp().tabs_as_menu())
        dynamic_cast<Notebook*>(mainframe->m_tabpanel)->UpdateMode();
#endif
    for (auto tab : tabs_list)
        tab->update_mode();
    plater()->update_menus();
    plater()->canvas3D()->update_gizmos_on_off_state();
}
References Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::MainFrame::m_tabpanel, mainframe, plater(), sidebar(), tabs_as_menu(), tabs_list, Slic3r::GUI::GLCanvas3D::update_gizmos_on_off_state(), Slic3r::GUI::Plater::update_menus(), and Slic3r::GUI::Sidebar::update_mode().
Referenced by recreate_GUI(), Slic3r::GUI::ConfigWizard::run(), and save_mode().
update_saved_preset_from_current_preset()
void Slic3r::GUI::GUI_App::update_saved_preset_from_current_preset ()
{
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (Tab* tab : tabs_list) {
        if (tab->supports_printer_technology(printer_technology))
            tab->update_saved_preset_from_current_preset();
    }
}
References Slic3r::PresetCollection::get_edited_preset(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and tabs_list.
update_ui_colours_from_appconfig()
void Slic3r::GUI::GUI_App::update_ui_colours_from_appconfig ()
{
    // load label colors
    if (app_config->has("label_clr_sys")) {
        auto str = app_config->get("label_clr_sys");
        if (!str.empty())
            m_color_label_sys = wxColour(str);
    }
    if (app_config->has("label_clr_modified")) {
        auto str = app_config->get("label_clr_modified");
        if (!str.empty())
            m_color_label_modified = wxColour(str);
    }
    // load mode markers colors
    if (app_config->has("mode_palette")) {
        const auto colors = app_config->get("mode_palette");
        if (!colors.empty()) {
            m_mode_palette.clear();
            if (!unescape_strings_cstyle(colors, m_mode_palette))
                m_mode_palette = get_mode_default_palette();
        }
    }
}
References app_config, Slic3r::AppConfig::get(), get_mode_default_palette(), Slic3r::AppConfig::has(), m_color_label_modified, m_color_label_sys, m_mode_palette, and Slic3r::unescape_strings_cstyle().
Referenced by on_init_inner().
update_ui_from_settings()
void Slic3r::GUI::GUI_App::update_ui_from_settings ()
{
    update_label_colours();
#ifdef _WIN32
    // Upadte UI colors before Update UI from settings
    if (m_force_colors_update) {
        m_force_colors_update = false;
        mainframe->force_color_changed();
        mainframe->diff_dialog.force_color_changed();
        mainframe->preferences_dialog->force_color_changed();
        mainframe->printhost_queue_dlg()->force_color_changed();
#ifdef _MSW_DARK_MODE
        update_scrolls(mainframe);
        if (mainframe->is_dlg_layout()) {
            // update for tabs bar
            UpdateDarkUI(&mainframe->m_settings_dialog);
            mainframe->m_settings_dialog.Fit();
            mainframe->m_settings_dialog.Refresh();
            // update scrollbars
            update_scrolls(&mainframe->m_settings_dialog);
        }
#endif //_MSW_DARK_MODE
    }
#endif
    mainframe->update_ui_from_settings();
}
References Slic3r::GUI::MainFrame::diff_dialog, Slic3r::GUI::MainFrame::is_dlg_layout(), Slic3r::GUI::MainFrame::m_settings_dialog, mainframe, Slic3r::GUI::MainFrame::preferences_dialog, Slic3r::GUI::MainFrame::printhost_queue_dlg(), update_label_colours(), Slic3r::GUI::MainFrame::update_ui_from_settings(), and UpdateDarkUI().
UpdateAllStaticTextDarkUI()
void Slic3r::GUI::GUI_App::UpdateAllStaticTextDarkUI (wxWindow * parent)
{
#ifdef _WIN32
    wxGetApp().UpdateDarkUI(parent);
    auto children = parent->GetChildren();
    for (auto child : children) {
        if (dynamic_cast<wxStaticText*>(child))
            child->SetForegroundColour(m_color_label_default);
    }
#endif
}
References m_color_label_default.
UpdateDarkUI()
void Slic3r::GUI::GUI_App::UpdateDarkUI (wxWindow * window, bool highlited = false, bool just_font = false)
{
#ifdef _WIN32
    bool is_focused_button = false;
    bool is_default_button = false;
    if (wxButton* btn = dynamic_cast<wxButton*>(window)) {
        if (!(btn->GetWindowStyle() & wxNO_BORDER)) {
            btn->SetWindowStyle(btn->GetWindowStyle() | wxNO_BORDER);
            highlited = true;
        }
        // button marking
        {
            auto mark_button = [this, btn, highlited](const bool mark) {
                if (btn->GetLabel().IsEmpty())
                    btn->SetBackgroundColour(mark ? m_color_selected_btn_bg   : highlited ? m_color_highlight_default : m_color_window_default);
                else
                    btn->SetForegroundColour(mark ? m_color_hovered_btn_label : (is_default(btn) ? m_color_default_btn_label : m_color_label_default));
                btn->Refresh();
                btn->Update();
            };
            // hovering
            btn->Bind(wxEVT_ENTER_WINDOW, [mark_button](wxMouseEvent& event) { mark_button(true); event.Skip(); });
            btn->Bind(wxEVT_LEAVE_WINDOW, [mark_button, btn](wxMouseEvent& event) { mark_button(is_focused(btn->GetHWND())); event.Skip(); });
            // focusing
            btn->Bind(wxEVT_SET_FOCUS,    [mark_button](wxFocusEvent& event) { mark_button(true); event.Skip(); });
            btn->Bind(wxEVT_KILL_FOCUS,   [mark_button](wxFocusEvent& event) { mark_button(false); event.Skip(); });
            is_focused_button = is_focused(btn->GetHWND());
            is_default_button = is_default(btn);
            if (is_focused_button || is_default_button)
                mark_button(is_focused_button);
        }
    }
    else if (wxTextCtrl* text = dynamic_cast<wxTextCtrl*>(window)) {
        if (text->GetBorder() != wxBORDER_SIMPLE)
            text->SetWindowStyle(text->GetWindowStyle() | wxBORDER_SIMPLE);
    }
    else if (wxCheckListBox* list = dynamic_cast<wxCheckListBox*>(window)) {
        list->SetWindowStyle(list->GetWindowStyle() | wxBORDER_SIMPLE);
        list->SetBackgroundColour(highlited ? m_color_highlight_default : m_color_window_default);
        for (size_t i = 0; i < list->GetCount(); i++)
            if (wxOwnerDrawn* item = list->GetItem(i)) {
                item->SetBackgroundColour(highlited ? m_color_highlight_default : m_color_window_default);
                item->SetTextColour(m_color_label_default);
            }
        return;
    }
    else if (dynamic_cast<wxListBox*>(window))
        window->SetWindowStyle(window->GetWindowStyle() | wxBORDER_SIMPLE);
    if (!just_font)
        window->SetBackgroundColour(highlited ? m_color_highlight_default : m_color_window_default);
    if (!is_focused_button && !is_default_button)
        window->SetForegroundColour(m_color_label_default);
#endif
}
References m_color_label_default, and m_color_window_default.
Referenced by update_ui_from_settings(), and UpdateDVCDarkUI().
UpdateDlgDarkUI()
void Slic3r::GUI::GUI_App::UpdateDlgDarkUI (wxDialog * dlg, bool just_buttons_update = false)
{
#ifdef _WIN32
    update_dark_children_ui(dlg, just_buttons_update);
#endif
}
Referenced by add_config_menu().
UpdateDVCDarkUI()
void Slic3r::GUI::GUI_App::UpdateDVCDarkUI (wxDataViewCtrl * dvc, bool highlited = false)
{
#ifdef _WIN32
    UpdateDarkUI(dvc, highlited ? dark_mode() : false);
#ifdef _MSW_DARK_MODE
    dvc->RefreshHeaderDarkMode(&m_normal_font);
#endif //_MSW_DARK_MODE
    if (dvc->HasFlag(wxDV_ROW_LINES))
        dvc->SetAlternateRowColour(m_color_highlight_default);
    if (dvc->GetBorder() != wxBORDER_SIMPLE)
        dvc->SetWindowStyle(dvc->GetWindowStyle() | wxBORDER_SIMPLE);
#endif
}
References dark_mode(), m_normal_font, and UpdateDarkUI().
window_pos_restore()
void Slic3r::GUI::GUI_App::window_pos_restore (wxTopLevelWindow * window, const std::string & name, bool default_maximized = false) private
{
    if (name.empty()) { return; }
    const auto config_key = (boost::format("window_%1%") % name).str();
    if (! app_config->has(config_key)) {
        window->Maximize(default_maximized);
        return;
    }
    auto metrics = WindowMetrics::deserialize(app_config->get(config_key));
    if (! metrics) {
        window->Maximize(default_maximized);
        return;
    }
    const wxRect& rect = metrics->get_rect();
    if (app_config->get_bool("restore_win_position")) {
        // workaround for crash related to the positioning of the window on secondary monitor
        app_config->set("restore_win_position", (boost::format("crashed_at_%1%_pos") % name).str());
        app_config->save();
        window->SetPosition(rect.GetPosition());
        // workaround for crash related to the positioning of the window on secondary monitor
        app_config->set("restore_win_position", (boost::format("crashed_at_%1%_size") % name).str());
        app_config->save();
        window->SetSize(rect.GetSize());
        // revert "restore_win_position" value if application wasn't crashed
        app_config->set("restore_win_position", "1");
        app_config->save();
    }
    else
        window->CenterOnScreen();
    window->Maximize(metrics->get_maximized());
}
References app_config, Slic3r::GUI::WindowMetrics::deserialize(), Slic3r::AppConfig::get(), Slic3r::AppConfig::get_bool(), Slic3r::AppConfig::has(), Slic3r::AppConfig::save(), and Slic3r::AppConfig::set().
Referenced by persist_window_geometry().
window_pos_sanitize()
void Slic3r::GUI::GUI_App::window_pos_sanitize (wxTopLevelWindow * window) private
{
    /*unsigned*/int display_idx = wxDisplay::GetFromWindow(window);
    wxRect display;
    if (display_idx == wxNOT_FOUND) {
        display = wxDisplay(0u).GetClientArea();
        window->Move(display.GetTopLeft());
    } else {
        display = wxDisplay(display_idx).GetClientArea();
    }
    auto metrics = WindowMetrics::from_window(window);
    metrics.sanitize_for_display(display);
    if (window->GetScreenRect() != metrics.get_rect()) {
        window->SetSize(metrics.get_rect());
    }
}
References Slic3r::GUI::WindowMetrics::from_window().
Referenced by persist_window_geometry().
window_pos_save()
void Slic3r::GUI::GUI_App::window_pos_save (wxTopLevelWindow * window, const std::string & name) private
{
    if (name.empty()) { return; }
    const auto config_key = (boost::format("window_%1%") % name).str();
    WindowMetrics metrics = WindowMetrics::from_window(window);
    app_config->set(config_key, metrics.serialize());
    // save changed app_config here, before all action related to a close of application is processed
    if (app_config->dirty())
        app_config->save();
}
References app_config, Slic3r::AppConfig::dirty(), Slic3r::GUI::WindowMetrics::from_window(), Slic3r::AppConfig::save(), Slic3r::GUI::WindowMetrics::serialize(), and Slic3r::AppConfig::set().
Referenced by persist_window_geometry().
Member Data Documentation
app_config
AppConfig* Slic3r::GUI::GUI_App::app_config { nullptr }
Referenced by ~GUI_App(), add_config_menu(), app_updater(), app_version_check(), check_and_keep_current_preset_changes(), check_and_save_current_preset_changes(), check_older_app_config(), check_updates(), config_wizard_startup(), dark_mode(), get_mode(), Slic3r::GUI::GUI_Run(), import_model(), import_zip(), init_app_config(), load_gcode(), load_language(), load_project(), on_init_inner(), on_version_read(), open_browser_with_warning_dialog(), open_preferences(), post_init(), recreate_GUI(), Slic3r::GUI::ConfigWizard::run(), run_wizard(), save_mode(), select_language(), set_auto_toolbar_icon_scale(), set_label_clr_modified(), set_label_clr_sys(), set_mode_palette(), show_downloader_registration_dialog(), start_download(), tabs_as_menu(), toolbar_icon_scale(), update_ui_colours_from_appconfig(), window_pos_restore(), and window_pos_save().
init_params
GUI_InitParams* Slic3r::GUI::GUI_App::init_params { nullptr }
Referenced by Slic3r::GUI::GUI_Run(), init_glcontext(), and post_init().
m_app_conf_exists
bool Slic3r::GUI::GUI_App::m_app_conf_exists { false } private
Referenced by check_older_app_config(), check_updates(), config_wizard_startup(), init_app_config(), and on_init_inner().
m_app_mode
EAppMode Slic3r::GUI::GUI_App::m_app_mode { EAppMode::Editor } private
Referenced by get_app_mode(), is_editor(), and is_gcode_viewer().
m_app_updater
std::unique_ptr<AppUpdater> Slic3r::GUI::GUI_App::m_app_updater private
Referenced by GUI_App(), app_updater(), app_version_check(), on_init_inner(), and on_version_read().
m_bold_font
wxFont Slic3r::GUI::GUI_App::m_bold_font private
Referenced by bold_font(), init_fonts(), and update_fonts().
m_code_font
wxFont Slic3r::GUI::GUI_App::m_code_font private
Referenced by code_font(), init_fonts(), and update_fonts().
m_color_label_default
wxColour Slic3r::GUI::GUI_App::m_color_label_default private
Referenced by get_label_clr_default(), init_ui_colours(), UpdateAllStaticTextDarkUI(), and UpdateDarkUI().
m_color_label_modified
wxColour Slic3r::GUI::GUI_App::m_color_label_modified private
Referenced by get_label_clr_modified(), init_ui_colours(), set_label_clr_modified(), and update_ui_colours_from_appconfig().
m_color_label_sys
wxColour Slic3r::GUI::GUI_App::m_color_label_sys private
Referenced by get_label_clr_sys(), init_ui_colours(), set_label_clr_sys(), and update_ui_colours_from_appconfig().
m_color_window_default
wxColour Slic3r::GUI::GUI_App::m_color_window_default private
Referenced by get_window_default_clr(), init_ui_colours(), and UpdateDarkUI().
m_datadir_redefined
bool Slic3r::GUI::GUI_App::m_datadir_redefined { false } private
Referenced by check_older_app_config(), and init_app_config().
m_downloader
std::unique_ptr<Downloader> Slic3r::GUI::GUI_App::m_downloader private
Referenced by downloader(), and start_download().
m_em_unit
int Slic3r::GUI::GUI_App::m_em_unit private
Referenced by em_unit(), get_min_size(), set_auto_toolbar_icon_scale(), toolbar_icon_scale(), and update_fonts().
m_imgui
std::unique_ptr<ImGuiWrapper> Slic3r::GUI::GUI_App::m_imgui private
Referenced by imgui(), and load_language().
m_initialized
bool Slic3r::GUI::GUI_App::m_initialized { false } private
Referenced by initialized().
m_instance_hash_int
size_t Slic3r::GUI::GUI_App::m_instance_hash_int private
Referenced by get_instance_hash_int(), post_init(), and set_instance_hash().
m_instance_hash_string
std::string Slic3r::GUI::GUI_App::m_instance_hash_string private
Referenced by get_instance_hash_string(), and set_instance_hash().
m_is_recreating_gui
bool Slic3r::GUI::GUI_App::m_is_recreating_gui { false } private
Referenced by is_recreating_gui(), and recreate_GUI().
m_language_info_best
const wxLanguageInfo* Slic3r::GUI::GUI_App::m_language_info_best = nullptr private
Referenced by load_language().
m_language_info_system
const wxLanguageInfo* Slic3r::GUI::GUI_App::m_language_info_system = nullptr private
Referenced by load_language().
m_last_app_conf_lower_version
bool Slic3r::GUI::GUI_App::m_last_app_conf_lower_version { false } private
Referenced by config_wizard_startup(), and on_init_inner().
m_link_font
wxFont Slic3r::GUI::GUI_App::m_link_font private
Referenced by link_font(), and update_fonts().
m_mode_palette
std::vector<std::string> Slic3r::GUI::GUI_App::m_mode_palette private
Referenced by get_mode_btn_color(), get_mode_palette(), init_ui_colours(), set_mode_palette(), and update_ui_colours_from_appconfig().
m_normal_font
wxFont Slic3r::GUI::GUI_App::m_normal_font private
Referenced by init_fonts(), normal_font(), update_fonts(), and UpdateDVCDarkUI().
m_opengl_initialized
bool Slic3r::GUI::GUI_App::m_opengl_initialized { false } private
Referenced by init_opengl().
m_opengl_mgr
OpenGLManager Slic3r::GUI::GUI_App::m_opengl_mgr private
Referenced by get_current_shader(), get_shader(), init_glcontext(), init_opengl(), is_gl_version_greater_or_equal_to(), and is_glsl_version_greater_or_equal_to().
m_other_instance_message_handler
std::unique_ptr<OtherInstanceMessageHandler> Slic3r::GUI::GUI_App::m_other_instance_message_handler private
Referenced by other_instance_message_handler().
m_post_initialized
bool Slic3r::GUI::GUI_App::m_post_initialized { false } private
m_printhost_job_queue
std::unique_ptr<PrintHostJobQueue> Slic3r::GUI::GUI_App::m_printhost_job_queue private
Referenced by printhost_job_queue(), and recreate_GUI().
m_removable_drive_manager
std::unique_ptr<RemovableDriveManager> Slic3r::GUI::GUI_App::m_removable_drive_manager private
Referenced by removable_drive_manager().
m_single_instance_checker
std::unique_ptr<wxSingleInstanceChecker> Slic3r::GUI::GUI_App::m_single_instance_checker private
Referenced by init_single_instance_checker(), and single_instance_checker().
m_small_font
wxFont Slic3r::GUI::GUI_App::m_small_font private
Referenced by init_fonts(), small_font(), and update_fonts().
m_wxLocale
std::unique_ptr<wxLocale> Slic3r::GUI::GUI_App::m_wxLocale private
Referenced by current_language_code(), is_localized(), load_language(), and select_language().
mainframe
MainFrame* Slic3r::GUI::GUI_App::mainframe { nullptr }
Referenced by add_config_menu(), check_print_host_queue(), check_updates(), gallery_dialog(), open_preferences(), post_init(), recreate_GUI(), run_wizard(), set_mode_palette(), show_desktop_integration_dialog(), tab_panel(), update_fonts(), Slic3r::GUI::ProjectDirtyStateManager::update_from_presets(), update_mode(), and update_ui_from_settings().
plater_
Plater* Slic3r::GUI::GUI_App::plater_ { nullptr }
Referenced by app_updater(), model(), notification_manager(), obj_manipul(), on_init_inner(), on_version_read(), open_preferences(), plater(), plater(), post_init(), sidebar(), and start_download().
preset_bundle
PresetBundle* Slic3r::GUI::GUI_App::preset_bundle { nullptr }
Referenced by ~GUI_App(), add_config_menu(), apply_keeped_preset_modifications(), check_and_keep_current_preset_changes(), check_and_save_current_preset_changes(), check_printer_presets(), config_wizard_startup(), extruders_cnt(), extruders_edited_cnt(), get_active_preset_collections(), has_current_preset_changes(), has_unsaved_preset_changes(), load_current_presets(), on_init_inner(), post_init(), Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets(), Slic3r::GUI::ConfigWizard::run(), run_wizard(), Slic3r::GUI::ProjectDirtyStateManager::update_from_presets(), and update_saved_preset_from_current_preset().
preset_updater
PresetUpdater* Slic3r::GUI::GUI_App::preset_updater { nullptr }
Referenced by ~GUI_App(), check_updates(), get_preset_updater(), on_init_inner(), post_init(), Slic3r::GUI::ConfigWizard::run(), and run_wizard().
tabs_list
std::vector<Tab *> Slic3r::GUI::GUI_App::tabs_list
Referenced by apply_keeped_preset_modifications(), check_and_keep_current_preset_changes(), checked_tab(), get_active_preset_collections(), get_tab(), has_current_preset_changes(), has_unsaved_preset_changes(), load_current_presets(), update_label_colours(), update_mode(), and update_saved_preset_from_current_preset().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_App.hpp
src/slic3r/GUI/GUI_App.cpp