Prusa Slicer: Slic3r::GUI::ObjectDataViewModelNode Class Reference
Slic3r::GUI::ObjectDataViewModelNode Class Reference
#include <src/slic3r/GUI/ObjectDataViewModel.hpp>
Public Member Functions
ObjectDataViewModelNode (const wxString &name, const wxString &extruder)
ObjectDataViewModelNode (ObjectDataViewModelNode *parent, const wxString &sub_obj_name, Slic3r::ModelVolumeType type, const bool is_text_volume, const wxString &extruder, const int idx=-1)
ObjectDataViewModelNode (ObjectDataViewModelNode *parent, const t_layer_height_range &layer_range, const int idx=-1, const wxString &extruder=wxEmptyString)
ObjectDataViewModelNode (ObjectDataViewModelNode *parent, const ItemType type)
ObjectDataViewModelNode (ObjectDataViewModelNode *parent, const InfoItemType type)
~ObjectDataViewModelNode ()
void init_container ()
void invalidate_container ()
bool IsContainer () const
ObjectDataViewModelNode * GetParent ()
MyObjectTreeModelNodePtrArray & GetChildren ()
ObjectDataViewModelNode * GetNthChild (unsigned int n)
void Insert (ObjectDataViewModelNode *child, unsigned int n)
void Append (ObjectDataViewModelNode *child)
void RemoveAllChildren ()
size_t GetChildCount () const
bool SetValue (const wxVariant &variant, unsigned int col)
void SetVolumeType (ModelVolumeType type)
void SetBitmap (const wxBitmapBundle &icon)
void SetExtruder (const wxString &extruder)
void SetWarningIconName (const std::string &warning_icon_name)
void SetLock (bool has_lock)
const wxBitmapBundle & GetBitmap () const
const wxString & GetName () const
ItemType GetType () const
InfoItemType GetInfoItemType () const
void SetIdx (const int &idx)
int GetIdx () const
ModelVolumeType GetVolumeType () const
t_layer_height_range GetLayerRange () const
wxString GetExtruder ()
PrintIndicator IsPrintable () const
void UpdateExtruderAndColorIcon (wxString extruder="")
void AssignAllVal (ObjectDataViewModelNode &from_node)
bool SwapChildrens (int frst_id, int scnd_id)
void set_action_and_extruder_icons ()
void set_extruder_icon ()
void set_printable_icon (PrintIndicator printable)
void update_settings_digest_bitmaps ()
bool update_settings_digest (const std::vector< std::string > &categories)
int volume_type () const
bool is_text_volume () const
void sys_color_changed ()
bool valid ()
bool invalid () const
bool has_warning_icon () const
bool has_lock () const
const std::string & warning_icon_name () const
Private Attributes
ObjectDataViewModelNode * m_parent
MyObjectTreeModelNodePtrArray m_children
wxBitmapBundle m_empty_bmp
size_t m_volumes_cnt = 0
std::vector< std::string > m_opt_categories
t_layer_height_range m_layer_range = { 0.0f, 0.0f }
wxString m_name
wxBitmapBundle & m_bmp = m_empty_bmp
ItemType m_type
int m_idx = -1
bool m_container = false
wxString m_extruder = "default"
wxBitmapBundle m_extruder_bmp
wxBitmapBundle m_action_icon
PrintIndicator m_printable {piUndef}
wxBitmapBundle m_printable_icon
std::string m_warning_icon_name { "" }
bool m_has_lock {false}
std::string m_action_icon_name = ""
ModelVolumeType m_volume_type { -1 }
bool m_is_text_volume { false }
InfoItemType m_info_item_type {InfoItemType::Undef}
Friends
class ObjectDataViewModel
Detailed Description
Constructor & Destructor Documentation
ObjectDataViewModelNode() [1/5]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (const wxString & name, const wxString & extruder) inline
                                                     :
        m_parent(NULL),
        m_name(name),
        m_type(itObject),
        m_extruder(extruder)
    {
        set_action_and_extruder_icons();
        init_container();
  }
References init_container(), and set_action_and_extruder_icons().
ObjectDataViewModelNode() [2/5]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (ObjectDataViewModelNode * parent, const wxString & sub_obj_name, Slic3r::ModelVolumeType type, const bool is_text_volume, const wxString & extruder, const int idx = -1)
                                                                                  :
    m_parent(parent),
    m_name(sub_obj_name),
    m_type(itVolume),
    m_volume_type(type),
    m_is_text_volume(is_text_volume),
    m_idx(idx),
    m_extruder(type == Slic3r::ModelVolumeType::MODEL_PART || type == Slic3r::ModelVolumeType::PARAMETER_MODIFIER ? extruder : "")
{
    set_action_and_extruder_icons();
    init_container();
}
References init_container(), and set_action_and_extruder_icons().
ObjectDataViewModelNode() [3/5]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (ObjectDataViewModelNode * parent, const t_layer_height_range & layer_range, const int idx = -1, const wxString & extruder = wxEmptyString)
                                                                           :
    m_parent(parent),
    m_type(itLayer),
    m_idx(idx),
    m_layer_range(layer_range),
    m_extruder(extruder)
{
    const int children_cnt = parent->GetChildCount();
    if (idx < 0)
        m_idx = children_cnt;
    else
    {
        // update indexes for another Laeyr Nodes
        for (int i = m_idx; i < children_cnt; i++)
            parent->GetNthChild(i)->SetIdx(i + 1);
    }
    const std::string label_range = (boost::format(" %.2f-%.2f ") % layer_range.first % layer_range.second).str();
    m_name = _(L("Range")) + label_range + "(" + _(L("mm")) + ")";
    m_bmp = *get_bmp_bundle(LayerIcon);
    set_action_and_extruder_icons();
    init_container();
}
References _, get_bmp_bundle(), GetChildCount(), GetNthChild(), init_container(), L, Slic3r::GUI::LayerIcon, m_bmp, m_idx, m_name, set_action_and_extruder_icons(), and SetIdx().
ObjectDataViewModelNode() [4/5]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (ObjectDataViewModelNode * parent, const ItemType type)
                                                                                                     :
    m_parent(parent),
    m_type(type),
    m_extruder(wxEmptyString)
{
    if (type == itSettings)
        m_name = "Settings to modified";
    else if (type == itInstanceRoot)
        m_name = _(L("Instances"));
    else if (type == itInstance)
    {
        m_idx = parent->GetChildCount();
        m_name = wxString::Format(_(L("Instance %d")), m_idx + 1);
        set_action_and_extruder_icons();
    }
    else if (type == itLayerRoot)
    {
        m_bmp = *get_bmp_bundle(LayerRootIcon);
        m_name = _(L("Layers"));
    }
    else if (type == itInfo)
        assert(false);
    if (type & (itInstanceRoot | itLayerRoot))
        init_container();
}
References _, get_bmp_bundle(), GetChildCount(), init_container(), Slic3r::GUI::itInfo, Slic3r::GUI::itInstance, Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itSettings, L, Slic3r::GUI::LayerRootIcon, m_bmp, m_idx, m_name, and set_action_and_extruder_icons().
ObjectDataViewModelNode() [5/5]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (ObjectDataViewModelNode * parent, const InfoItemType type)
                                                                                                              :
    m_parent(parent),
    m_type(itInfo),
    m_info_item_type(info_type),
    m_extruder(wxEmptyString),
    m_name(_(INFO_ITEMS.at(info_type).name))
{
}
~ObjectDataViewModelNode()
Slic3r::GUI::ObjectDataViewModelNode::~ObjectDataViewModelNode () inline
    {
        // free all our children nodes
        size_t count = m_children.GetCount();
        for (size_t i = 0; i < count; i++)
        {
            ObjectDataViewModelNode *child = m_children[i];
            delete child;
        }
#ifndef NDEBUG
        // Indicate that the object was deleted.
        m_idx = -2;
#endif /* NDEBUG */
    }
References m_children, and m_idx.
Member Function Documentation
Append()
void Slic3r::GUI::ObjectDataViewModelNode::Append (ObjectDataViewModelNode * child) inline
    {
        if (!m_container)
            m_container = true;
        m_children.Add(child);
    }
References m_children, and m_container.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddInstanceChild(), Slic3r::GUI::ObjectDataViewModel::AddLayersChild(), Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), and Slic3r::GUI::append_root_node().
AssignAllVal()
void Slic3r::GUI::ObjectDataViewModelNode::AssignAllVal (ObjectDataViewModelNode & from_node) inline
    {
        // ! Don't overwrite other values because of equality of this values for all children --
        m_name = from_node.m_name;
        m_bmp = from_node.m_bmp;
        m_idx = from_node.m_idx;
        m_extruder = from_node.m_extruder;
        m_type = from_node.m_type;
    }
References m_bmp, m_extruder, m_idx, m_name, and m_type.
GetBitmap()
const wxBitmapBundle & Slic3r::GUI::ObjectDataViewModelNode::GetBitmap () const inline
{ return m_bmp; }
References m_bmp.
Referenced by Slic3r::GUI::ObjectDataViewModel::DeleteWarningIcon().
GetChildCount()
size_t Slic3r::GUI::ObjectDataViewModelNode::GetChildCount () const inline
    {
        return m_children.GetCount();
    }
References m_children.
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModel::AddAllChildren(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteChildren(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), Slic3r::GUI::ObjectDataViewModel::DeleteVolumeChildren(), Slic3r::GUI::get_root_idx(), Slic3r::GUI::ObjectDataViewModel::GetAllChildren(), Slic3r::GUI::ObjectDataViewModel::GetChildren(), Slic3r::GUI::ObjectDataViewModel::GetInfoItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemIndexForFirstVolume(), Slic3r::GUI::ObjectDataViewModel::GetRowByItem(), invalidate_container(), RemoveAllChildren(), and SwapChildrens().
GetChildren()
MyObjectTreeModelNodePtrArray & Slic3r::GUI::ObjectDataViewModelNode::GetChildren () inline
    {
        return m_children;
    }
References m_children.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddAllChildren(), Slic3r::GUI::ObjectDataViewModel::AddInfoChild(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteChildren(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), Slic3r::GUI::ObjectDataViewModel::DeleteVolumeChildren(), Slic3r::GUI::ObjectDataViewModel::GetAllChildren(), Slic3r::GUI::ObjectDataViewModel::GetChildren(), Slic3r::GUI::ObjectDataViewModel::ReorganizeChildren(), Slic3r::GUI::ObjectDataViewModel::UpdateInstancesPrintable(), Slic3r::GUI::ObjectDataViewModel::UpdateObjectPrintable(), and Slic3r::GUI::ObjectDataViewModel::UpdateVolumesExtruderBitmap().
GetExtruder()
wxString Slic3r::GUI::ObjectDataViewModelNode::GetExtruder () inline
{ return m_extruder; }
References m_extruder.
Referenced by UpdateExtruderAndColorIcon().
GetIdx()
int Slic3r::GUI::ObjectDataViewModelNode::GetIdx () const inline
{ return m_idx; }
References m_idx.
Referenced by Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::GetIdByItemAndType(), and Slic3r::GUI::ObjectDataViewModel::GetItemInfo().
GetInfoItemType()
InfoItemType Slic3r::GUI::ObjectDataViewModelNode::GetInfoItemType () const inline
{ return m_info_item_type; }
References m_info_item_type.
GetLayerRange()
t_layer_height_range Slic3r::GUI::ObjectDataViewModelNode::GetLayerRange () const inline
{ return m_layer_range; }
References m_layer_range.
Referenced by Slic3r::GUI::ObjectDataViewModel::GetLayerRangeByItem().
GetName()
const wxString & Slic3r::GUI::ObjectDataViewModelNode::GetName () const inline
{ return m_name; }
References m_name.
Referenced by Slic3r::GUI::ObjectDataViewModel::GetItemName().
GetNthChild()
ObjectDataViewModelNode * Slic3r::GUI::ObjectDataViewModelNode::GetNthChild (unsigned int n) inline
    {
        return m_children.Item(n);
    }
References m_children.
Referenced by ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModel::AddLayersChild(), Slic3r::GUI::append_root_node(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), Slic3r::GUI::get_root_idx(), Slic3r::GUI::ObjectDataViewModel::GetInfoItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemIndexForFirstVolume(), Slic3r::GUI::ObjectDataViewModel::GetRowByItem(), Slic3r::GUI::ObjectDataViewModel::ReorganizeChildren(), SwapChildrens(), Slic3r::GUI::ObjectDataViewModel::UpdateInstancesPrintable(), and Slic3r::GUI::ObjectDataViewModel::UpdateObjectPrintable().
GetParent()
ObjectDataViewModelNode * Slic3r::GUI::ObjectDataViewModelNode::GetParent () inline
    {
        assert(m_parent == nullptr || m_parent->valid());
        return m_parent;
    }
References m_parent, and valid().
Referenced by Slic3r::GUI::ObjectDataViewModel::AddWarningIcon(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::GetItemInfo(), Slic3r::GUI::ObjectDataViewModel::GetParent(), and Slic3r::GUI::ObjectDataViewModel::GetTopParent().
GetType()
ItemType Slic3r::GUI::ObjectDataViewModelNode::GetType () const inline
{ return m_type; }
References m_type.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddLayersChild(), Slic3r::GUI::ObjectDataViewModel::AddWarningIcon(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), Slic3r::GUI::ObjectDataViewModel::DeleteWarningIcon(), Slic3r::GUI::get_root_idx(), Slic3r::GUI::ObjectDataViewModel::GetItemIndexForFirstVolume(), Slic3r::GUI::ObjectDataViewModel::GetItemInfo(), Slic3r::GUI::ObjectDataViewModel::SetExtruder(), and Slic3r::GUI::ObjectDataViewModel::UpdateLockIcon().
GetVolumeType()
ModelVolumeType Slic3r::GUI::ObjectDataViewModelNode::GetVolumeType () const inline
{ return m_volume_type; }
References m_volume_type.
Referenced by Slic3r::GUI::ObjectDataViewModel::GetVolumeType(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
has_lock()
bool Slic3r::GUI::ObjectDataViewModelNode::has_lock () const inline
{ return m_has_lock; }
References m_has_lock.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), Slic3r::GUI::ObjectDataViewModel::AddWarningIcon(), SetLock(), Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode(), and Slic3r::GUI::ObjectDataViewModel::UpdateLockIcon().
has_warning_icon()
bool Slic3r::GUI::ObjectDataViewModelNode::has_warning_icon () const inline
{ return !m_warning_icon_name.empty(); }
References m_warning_icon_name.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), Slic3r::GUI::ObjectDataViewModel::HasWarningIcon(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
init_container()
void Slic3r::GUI::ObjectDataViewModelNode::init_container ()
{
#ifdef __WXGTK__
    // it's necessary on GTK because of control have to know if this item will be container
    // in another case you couldn't to add subitem for this item
    // it will be produce "segmentation fault"
    m_container = true;
#endif  //__WXGTK__
}
References m_container.
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), ObjectDataViewModelNode(), and ObjectDataViewModelNode().
Insert()
void Slic3r::GUI::ObjectDataViewModelNode::Insert (ObjectDataViewModelNode * child, unsigned int n) inline
    {
        if (!m_container)
            m_container = true;
        m_children.Insert(child, n);
    }
References m_children, and m_container.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddInfoChild(), Slic3r::GUI::ObjectDataViewModel::AddLayersChild(), Slic3r::GUI::ObjectDataViewModel::AddSettingsChild(), Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), Slic3r::GUI::append_root_node(), and Slic3r::GUI::ObjectDataViewModel::ReorganizeChildren().
invalid()
bool Slic3r::GUI::ObjectDataViewModelNode::invalid () const inline
{ return m_idx < -1; }
References m_idx.
Referenced by Slic3r::GUI::ObjectDataViewModel::InvalidItem().
invalidate_container()
void Slic3r::GUI::ObjectDataViewModelNode::invalidate_container ()
{
#ifndef __WXGTK__
    if (this->GetChildCount() == 0)
        this->m_container = false;
#endif //__WXGTK__
}
References GetChildCount(), and m_container.
Referenced by Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteChildren(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), and Slic3r::GUI::ObjectDataViewModel::DeleteVolumeChildren().
is_text_volume()
bool Slic3r::GUI::ObjectDataViewModelNode::is_text_volume () const inline
{ return m_is_text_volume; }
References m_is_text_volume.
Referenced by Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
IsContainer()
bool Slic3r::GUI::ObjectDataViewModelNode::IsContainer () const inline
  {
    return m_container;
  }
References m_container.
Referenced by Slic3r::GUI::ObjectDataViewModel::IsContainer().
IsPrintable()
PrintIndicator Slic3r::GUI::ObjectDataViewModelNode::IsPrintable () const inline
{ return m_printable; }
References m_printable.
Referenced by Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::IsPrintable(), Slic3r::GUI::ObjectDataViewModel::UpdateInstancesPrintable(), and Slic3r::GUI::ObjectDataViewModel::UpdateObjectPrintable().
RemoveAllChildren()
void Slic3r::GUI::ObjectDataViewModelNode::RemoveAllChildren () inline
    {
        if (GetChildCount() == 0)
            return;
        for (int id = int(GetChildCount()) - 1; id >= 0; --id)
        {
            if (m_children.Item(id)->GetChildCount() > 0)
                m_children[id]->RemoveAllChildren();
            auto node = m_children[id];
            m_children.RemoveAt(id);
            delete node;
        }
    }
References GetChildCount(), and m_children.
set_action_and_extruder_icons()
void Slic3r::GUI::ObjectDataViewModelNode::set_action_and_extruder_icons ()
{
    m_action_icon_name = m_type & itObject              ? "advanced_plus" :
                         m_type & (itVolume | itLayer)  ? "cog" : /*m_type & itInstance*/ "set_separate_obj";
    m_action_icon = *get_bmp_bundle(m_action_icon_name);
    // set extruder bitmap
    set_extruder_icon();
}
References get_bmp_bundle(), Slic3r::GUI::itLayer, Slic3r::GUI::itObject, Slic3r::GUI::itVolume, m_action_icon, m_action_icon_name, m_type, and set_extruder_icon().
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), ObjectDataViewModelNode(), and ObjectDataViewModelNode().
set_extruder_icon()
void Slic3r::GUI::ObjectDataViewModelNode::set_extruder_icon ()
{
    if (m_type & (itInstance | itInstanceRoot | itLayerRoot) ||
        ((m_type & itVolume) && m_volume_type != Slic3r::ModelVolumeType::MODEL_PART && m_volume_type != Slic3r::ModelVolumeType::PARAMETER_MODIFIER))
        return; // don't set colored bitmap for Instance
    UpdateExtruderAndColorIcon();
}
References Slic3r::GUI::itInstance, Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itVolume, m_type, m_volume_type, Slic3r::MODEL_PART, Slic3r::PARAMETER_MODIFIER, and UpdateExtruderAndColorIcon().
Referenced by set_action_and_extruder_icons(), and sys_color_changed().
set_printable_icon()
void Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon (PrintIndicator printable)
{
    m_printable = printable;
    m_printable_icon = m_printable == piUndef ? m_empty_bmp :
                       *get_bmp_bundle(m_printable == piPrintable ? "eye_open" : "eye_closed");
}
References get_bmp_bundle(), m_empty_bmp, m_printable, m_printable_icon, Slic3r::GUI::piPrintable, and Slic3r::GUI::piUndef.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddInstanceChild(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::SetObjectPrintableState(), Slic3r::GUI::ObjectDataViewModel::SetPrintableState(), Slic3r::GUI::ObjectDataViewModel::UpdateInstancesPrintable(), and Slic3r::GUI::ObjectDataViewModel::UpdateObjectPrintable().
SetBitmap()
void Slic3r::GUI::ObjectDataViewModelNode::SetBitmap (const wxBitmapBundle & icon) inline
{ m_bmp = icon; }
References m_bmp.
Referenced by Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
SetExtruder()
void Slic3r::GUI::ObjectDataViewModelNode::SetExtruder (const wxString & extruder) inline
{ m_extruder = extruder; }
References m_extruder.
SetIdx()
void Slic3r::GUI::ObjectDataViewModelNode::SetIdx (const int & idx)
{
    m_idx = idx;
    // update name if this node is instance
    if (m_type == itInstance)
        m_name = wxString::Format(_(L("Instance %d")), m_idx + 1);
}
References _, Slic3r::GUI::itInstance, L, m_idx, m_name, and m_type.
Referenced by ObjectDataViewModelNode().
SetLock()
void Slic3r::GUI::ObjectDataViewModelNode::SetLock (bool has_lock) inline
{ m_has_lock = has_lock; }
References has_lock(), and m_has_lock.
Referenced by Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode(), and Slic3r::GUI::ObjectDataViewModel::UpdateLockIcon().
SetValue()
bool Slic3r::GUI::ObjectDataViewModelNode::SetValue (const wxVariant & variant, unsigned int col)
{
    switch (col)
    {
    case colPrint:
//        m_printable_icon << variant;
        return true;
    case colName: {
        DataViewBitmapText data;
        data << variant;
        m_bmp = data.GetBitmap();
        m_name = data.GetText();
        return true; }
    case colExtruder: {
        DataViewBitmapText data;
        data << variant;
        m_extruder_bmp = data.GetBitmap();
        m_extruder = data.GetText() == "0" ? _(L("default")) : data.GetText();
        return true; }
    case colEditing:
//        m_action_icon << variant;
        return true;
    default:
        printf("MyObjectTreeModel::SetValue: wrong column");
    }
    return false;
}
References _, col(), Slic3r::GUI::colEditing, Slic3r::GUI::colExtruder, Slic3r::GUI::colName, Slic3r::GUI::colPrint, L, m_bmp, m_extruder, m_extruder_bmp, and m_name.
Referenced by Slic3r::GUI::ObjectDataViewModel::SetValue().
SetVolumeType()
void Slic3r::GUI::ObjectDataViewModelNode::SetVolumeType (ModelVolumeType type) inline
{ m_volume_type = type; }
References m_volume_type.
SetWarningIconName()
void Slic3r::GUI::ObjectDataViewModelNode::SetWarningIconName (const std::string & warning_icon_name) inline
{ m_warning_icon_name = warning_icon_name; }
References m_warning_icon_name, and warning_icon_name().
Referenced by Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), Slic3r::GUI::ObjectDataViewModel::DeleteWarningIcon(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
SwapChildrens()
bool Slic3r::GUI::ObjectDataViewModelNode::SwapChildrens (int frst_id, int scnd_id) inline
{
        if (GetChildCount() < 2 ||
            frst_id < 0 || (size_t)frst_id >= GetChildCount() ||
            scnd_id < 0 || (size_t)scnd_id >= GetChildCount())
            return false;
        ObjectDataViewModelNode new_scnd = *GetNthChild(frst_id);
        ObjectDataViewModelNode new_frst = *GetNthChild(scnd_id);
        new_scnd.m_idx = m_children.Item(scnd_id)->m_idx;
        new_frst.m_idx = m_children.Item(frst_id)->m_idx;
        m_children.Item(frst_id)->AssignAllVal(new_frst);
        m_children.Item(scnd_id)->AssignAllVal(new_scnd);
        return true;
    }
References GetChildCount(), GetNthChild(), m_children, and m_idx.
sys_color_changed()
void Slic3r::GUI::ObjectDataViewModelNode::sys_color_changed ()
{
    if (!m_action_icon_name.empty())
        m_action_icon = *get_bmp_bundle(m_action_icon_name);
    if (m_printable != piUndef)
        m_printable_icon = *get_bmp_bundle(m_printable == piPrintable ? "eye_open" : "eye_closed");
    if (!m_opt_categories.empty())
        update_settings_digest_bitmaps();
    set_extruder_icon();
}
References get_bmp_bundle(), m_action_icon, m_action_icon_name, m_opt_categories, m_printable, m_printable_icon, Slic3r::GUI::piPrintable, Slic3r::GUI::piUndef, set_extruder_icon(), and update_settings_digest_bitmaps().
Referenced by Slic3r::GUI::ObjectDataViewModel::UpdateBitmaps().
update_settings_digest()
bool Slic3r::GUI::ObjectDataViewModelNode::update_settings_digest (const std::vector< std::string > & categories)
{
    if (m_type != itSettings || m_opt_categories == categories)
        return false;
    m_opt_categories = categories;
    m_name = wxEmptyString;
    for (auto& cat : m_opt_categories)
        m_name += _(cat) + "; ";
    if (!m_name.IsEmpty())
        m_name.erase(m_name.Length()-2, 2); // Delete last "; "
    update_settings_digest_bitmaps();
    return true;
}
References _, Slic3r::GUI::itSettings, m_name, m_opt_categories, m_type, and update_settings_digest_bitmaps().
Referenced by Slic3r::GUI::ObjectDataViewModel::UpdateSettingsDigest().
update_settings_digest_bitmaps()
void Slic3r::GUI::ObjectDataViewModelNode::update_settings_digest_bitmaps ()
{
    m_bmp = m_empty_bmp;
    std::string scaled_bitmap_name = m_name.ToUTF8().data();
    scaled_bitmap_name += (wxGetApp().dark_mode() ? "-dm" : "");
    wxBitmapBundle *bmp = find_bndl(scaled_bitmap_name);
    if (bmp == nullptr) {
        std::vector<wxBitmapBundle*> bmps;
        for (auto& category : m_opt_categories)
            bmps.emplace_back(SettingsFactory::get_category_bitmap(category));
        bmp = m_bitmap_cache->insert_bndl(scaled_bitmap_name, bmps);
    }
    m_bmp = *bmp;
}
References Slic3r::GUI::find_bndl(), Slic3r::GUI::SettingsFactory::get_category_bitmap(), Slic3r::GUI::BitmapCache::insert_bndl(), Slic3r::GUI::m_bitmap_cache, m_bmp, m_empty_bmp, m_name, and m_opt_categories.
Referenced by sys_color_changed(), and update_settings_digest().
UpdateExtruderAndColorIcon()
void Slic3r::GUI::ObjectDataViewModelNode::UpdateExtruderAndColorIcon (wxString extruder = "")
{
    if (m_type == itVolume && m_volume_type != ModelVolumeType::MODEL_PART && m_volume_type != ModelVolumeType::PARAMETER_MODIFIER)
        return;
    if (extruder.empty())
        extruder = m_extruder;
    else
        m_extruder = extruder; // update extruder
    // update color icon
    size_t extruder_idx = atoi(extruder.c_str());
    if (extruder_idx == 0) {
        if (m_type & itObject);
        else if (m_type & itVolume && m_volume_type == ModelVolumeType::MODEL_PART) {
            extruder_idx = atoi(m_parent->GetExtruder().c_str());
        }
        else {
            m_extruder_bmp = wxNullBitmap;
            return;
        }
    }
    if (extruder_idx > 0) --extruder_idx;
    // Create the bitmap with color bars.
    std::vector<wxBitmapBundle*> bmps = get_extruder_color_icons();// use wide icons
    if (bmps.empty()) {
        m_extruder_bmp = wxNullBitmap;
        return;
    }
    m_extruder_bmp = *bmps[extruder_idx >= bmps.size() ? 0 : extruder_idx];
}
References get_extruder_color_icons(), GetExtruder(), Slic3r::GUI::itObject, Slic3r::GUI::itVolume, m_extruder, m_extruder_bmp, m_parent, m_type, m_volume_type, Slic3r::MODEL_PART, and Slic3r::PARAMETER_MODIFIER.
Referenced by set_extruder_icon(), Slic3r::GUI::ObjectDataViewModel::SetExtruder(), Slic3r::GUI::ObjectDataViewModel::UpdateExtruderBitmap(), and Slic3r::GUI::ObjectDataViewModel::UpdateVolumesExtruderBitmap().
valid()
bool Slic3r::GUI::ObjectDataViewModelNode::valid ()
{
  // Verify that the object was not deleted yet.
  assert(m_idx >= -1);
  return m_idx >= -1;
}
References m_idx.
Referenced by GetParent(), and Slic3r::GUI::ObjectDataViewModel::GetParent().
volume_type()
int Slic3r::GUI::ObjectDataViewModelNode::volume_type () const inline
{ return int(m_volume_type); }
References m_volume_type.
warning_icon_name()
const std::string & Slic3r::GUI::ObjectDataViewModelNode::warning_icon_name () const inline
{ return m_warning_icon_name; }
References m_warning_icon_name.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), SetWarningIconName(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
Friends And Related Symbol Documentation
ObjectDataViewModel
friend class ObjectDataViewModel friend
Member Data Documentation
m_action_icon
wxBitmapBundle Slic3r::GUI::ObjectDataViewModelNode::m_action_icon private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetValue(), set_action_and_extruder_icons(), and sys_color_changed().
m_action_icon_name
std::string Slic3r::GUI::ObjectDataViewModelNode::m_action_icon_name = "" private
Referenced by set_action_and_extruder_icons(), and sys_color_changed().
m_bmp
wxBitmapBundle& Slic3r::GUI::ObjectDataViewModelNode::m_bmp = m_empty_bmp private
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), AssignAllVal(), GetBitmap(), Slic3r::GUI::ObjectDataViewModel::GetBitmap(), Slic3r::GUI::ObjectDataViewModel::GetValue(), SetBitmap(), SetValue(), update_settings_digest_bitmaps(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmaps().
m_children
MyObjectTreeModelNodePtrArray Slic3r::GUI::ObjectDataViewModelNode::m_children private
Referenced by ~ObjectDataViewModelNode(), Append(), GetChildCount(), GetChildren(), GetNthChild(), Insert(), RemoveAllChildren(), and SwapChildrens().
m_container
bool Slic3r::GUI::ObjectDataViewModelNode::m_container = false private
Referenced by Append(), init_container(), Insert(), invalidate_container(), and IsContainer().
m_empty_bmp
wxBitmapBundle Slic3r::GUI::ObjectDataViewModelNode::m_empty_bmp private
Referenced by set_printable_icon(), and update_settings_digest_bitmaps().
m_extruder
wxString Slic3r::GUI::ObjectDataViewModelNode::m_extruder = "default" private
Referenced by AssignAllVal(), GetExtruder(), Slic3r::GUI::ObjectDataViewModel::GetExtruder(), Slic3r::GUI::ObjectDataViewModel::GetExtruderNumber(), Slic3r::GUI::ObjectDataViewModel::GetValue(), Slic3r::GUI::ObjectDataViewModel::IsEnabled(), SetExtruder(), SetValue(), and UpdateExtruderAndColorIcon().
m_extruder_bmp
wxBitmapBundle Slic3r::GUI::ObjectDataViewModelNode::m_extruder_bmp private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetValue(), SetValue(), and UpdateExtruderAndColorIcon().
m_has_lock
bool Slic3r::GUI::ObjectDataViewModelNode::m_has_lock {false} private
Referenced by has_lock(), and SetLock().
m_idx
int Slic3r::GUI::ObjectDataViewModelNode::m_idx = -1 private
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), ~ObjectDataViewModelNode(), AssignAllVal(), GetIdx(), invalid(), SetIdx(), SwapChildrens(), and valid().
m_info_item_type
InfoItemType Slic3r::GUI::ObjectDataViewModelNode::m_info_item_type {InfoItemType::Undef} private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetInfoItemByType(), GetInfoItemType(), Slic3r::GUI::ObjectDataViewModel::GetInfoItemType(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmaps().
m_is_text_volume
bool Slic3r::GUI::ObjectDataViewModelNode::m_is_text_volume { false } private
Referenced by is_text_volume().
m_layer_range
t_layer_height_range Slic3r::GUI::ObjectDataViewModelNode::m_layer_range = { 0.0f, 0.0f } private
Referenced by GetLayerRange().
m_name
wxString Slic3r::GUI::ObjectDataViewModelNode::m_name private
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), AssignAllVal(), GetName(), Slic3r::GUI::ObjectDataViewModel::GetName(), Slic3r::GUI::ObjectDataViewModel::GetValue(), SetIdx(), SetValue(), update_settings_digest(), and update_settings_digest_bitmaps().
m_opt_categories
std::vector< std::string > Slic3r::GUI::ObjectDataViewModelNode::m_opt_categories private
Referenced by sys_color_changed(), update_settings_digest(), and update_settings_digest_bitmaps().
m_parent
ObjectDataViewModelNode* Slic3r::GUI::ObjectDataViewModelNode::m_parent private
Referenced by GetParent(), and UpdateExtruderAndColorIcon().
m_printable
PrintIndicator Slic3r::GUI::ObjectDataViewModelNode::m_printable {piUndef} private
Referenced by IsPrintable(), set_printable_icon(), and sys_color_changed().
m_printable_icon
wxBitmapBundle Slic3r::GUI::ObjectDataViewModelNode::m_printable_icon private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetValue(), set_printable_icon(), and sys_color_changed().
m_type
ItemType Slic3r::GUI::ObjectDataViewModelNode::m_type private
Referenced by AssignAllVal(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::GetIdByItemAndType(), Slic3r::GUI::ObjectDataViewModel::GetInfoItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemInfo(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectDataViewModel::GetLayerRangeByItem(), Slic3r::GUI::ObjectDataViewModel::GetParent(), Slic3r::GUI::ObjectDataViewModel::GetRowByItem(), Slic3r::GUI::ObjectDataViewModel::GetTopParent(), GetType(), Slic3r::GUI::ObjectDataViewModel::IsSettingsItem(), set_action_and_extruder_icons(), set_extruder_icon(), SetIdx(), update_settings_digest(), Slic3r::GUI::ObjectDataViewModel::UpdateBitmaps(), and UpdateExtruderAndColorIcon().
m_volume_type
ModelVolumeType Slic3r::GUI::ObjectDataViewModelNode::m_volume_type { -1 } private
Referenced by GetVolumeType(), set_extruder_icon(), SetVolumeType(), UpdateExtruderAndColorIcon(), and volume_type().
m_volumes_cnt
size_t Slic3r::GUI::ObjectDataViewModelNode::m_volumes_cnt = 0 private
Referenced by Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), Slic3r::GUI::ObjectDataViewModel::DeleteChildren(), Slic3r::GUI::ObjectDataViewModel::DeleteVolumeChildren(), and Slic3r::GUI::ObjectDataViewModel::GetItemIndexForFirstVolume().
m_warning_icon_name
std::string Slic3r::GUI::ObjectDataViewModelNode::m_warning_icon_name { "" } private
Referenced by has_warning_icon(), SetWarningIconName(), and warning_icon_name().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ObjectDataViewModel.hpp
src/slic3r/GUI/ObjectDataViewModel.cpp