Prusa Slicer: Slic3r::Search::SearchDialog Class Reference
Slic3r::Search::SearchDialog Class Reference
#include <src/slic3r/GUI/Search.hpp>
Public Member Functions
SearchDialog (OptionsSearcher *searcher)
~SearchDialog ()
void Popup (wxPoint position=wxDefaultPosition)
void ProcessSelection (wxDataViewItem selection)
void msw_rescale ()
void on_sys_color_changed () override
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
Protected Member Functions
void on_dpi_changed (const wxRect &suggested_rect) override
Private Member Functions
void OnInputText (wxCommandEvent &event)
void OnLeftUpInTextCtrl (wxEvent &event)
void OnKeyDown (wxKeyEvent &event)
void OnActivate (wxDataViewEvent &event)
void OnSelect (wxDataViewEvent &event)
void OnCheck (wxCommandEvent &event)
void OnMotion (wxMouseEvent &event)
void OnLeftDown (wxMouseEvent &event)
void update_list ()
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
wxString search_str
wxString default_string
bool prevent_list_events {false}
wxTextCtrl * search_line { nullptr }
wxDataViewCtrl * search_list { nullptr }
SearchListModel * search_list_model { nullptr }
wxCheckBox * check_category { nullptr }
wxCheckBox * check_english { nullptr }
OptionsSearcher * searcher { nullptr }
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
SearchDialog()
Slic3r::Search::SearchDialog::SearchDialog (OptionsSearcher * searcher)
    : GUI::DPIDialog(GUI::wxGetApp().tab_panel(), wxID_ANY, _L("Search"), wxDefaultPosition, wxDefaultSize, wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
    searcher(searcher)
{
    SetFont(GUI::wxGetApp().normal_font());
    GUI::wxGetApp().UpdateDarkUI(this);
    default_string = _L("Enter a search term");
    int border = 10;
    int em = em_unit();
    search_line = new wxTextCtrl(this, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    GUI::wxGetApp().UpdateDarkUI(search_line);
    search_list = new wxDataViewCtrl(this, wxID_ANY, wxDefaultPosition, wxSize(em * 40, em * 30), wxDV_NO_HEADER | wxDV_SINGLE
#ifdef _WIN32
        | wxBORDER_SIMPLE
#endif
    );
    GUI::wxGetApp().UpdateDarkUI(search_list);
    search_list_model = new SearchListModel(this);
    search_list->AssociateModel(search_list_model);
#ifdef __WXMSW__
    search_list->AppendColumn(new wxDataViewColumn("", new BitmapTextRenderer(true, wxDATAVIEW_CELL_INERT), SearchListModel::colIconMarkedText, wxCOL_WIDTH_AUTOSIZE, wxALIGN_LEFT));
    search_list->GetColumn(SearchListModel::colIconMarkedText)->SetWidth(48  * em_unit());
#else
    search_list->AppendBitmapColumn("", SearchListModel::colIcon);
    wxDataViewTextRenderer* const markupRenderer = new wxDataViewTextRenderer();
#ifdef SUPPORTS_MARKUP
    markupRenderer->EnableMarkup();
#endif
    search_list->AppendColumn(new wxDataViewColumn("", markupRenderer, SearchListModel::colMarkedText, wxCOL_WIDTH_AUTOSIZE, wxALIGN_LEFT));
    search_list->GetColumn(SearchListModel::colIcon      )->SetWidth(3  * em_unit());
    search_list->GetColumn(SearchListModel::colMarkedText)->SetWidth(40 * em_unit());
#endif
    wxBoxSizer* check_sizer = new wxBoxSizer(wxHORIZONTAL);
    check_category  = new wxCheckBox(this, wxID_ANY, _L("Category"));
    if (GUI::wxGetApp().is_localized())
        check_english   = new wxCheckBox(this, wxID_ANY, _L("Search in English"));
    wxStdDialogButtonSizer* cancel_btn = this->CreateStdDialogButtonSizer(wxCANCEL);
    GUI::wxGetApp().UpdateDarkUI(static_cast<wxButton*>(this->FindWindowById(wxID_CANCEL, this)));
    check_sizer->Add(new wxStaticText(this, wxID_ANY, _L("Use for search") + ":"), 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, border);
    check_sizer->Add(check_category, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, border);
    if (check_english)
        check_sizer->Add(check_english,  0, wxALIGN_CENTER_VERTICAL | wxRIGHT, border);
    check_sizer->AddStretchSpacer(border);
    check_sizer->Add(cancel_btn,     0, wxALIGN_CENTER_VERTICAL);
    wxBoxSizer* topSizer = new wxBoxSizer(wxVERTICAL);
    topSizer->Add(search_line, 0, wxEXPAND | wxLEFT | wxTOP | wxRIGHT, border);
    topSizer->Add(search_list, 1, wxEXPAND | wxLEFT | wxTOP | wxRIGHT, border);
    topSizer->Add(check_sizer, 0, wxEXPAND | wxALL, border);
    search_line->Bind(wxEVT_TEXT,    &SearchDialog::OnInputText, this);
    search_line->Bind(wxEVT_LEFT_UP, &SearchDialog::OnLeftUpInTextCtrl, this);
    // process wxEVT_KEY_DOWN to navigate inside search_list, if ArrowUp/Down was pressed
    search_line->Bind(wxEVT_KEY_DOWN,&SearchDialog::OnKeyDown, this);
    search_list->Bind(wxEVT_DATAVIEW_SELECTION_CHANGED, &SearchDialog::OnSelect,    this);
    search_list->Bind(wxEVT_DATAVIEW_ITEM_ACTIVATED,    &SearchDialog::OnActivate,  this);
#ifdef __WXMSW__
    search_list->GetMainWindow()->Bind(wxEVT_MOTION,    &SearchDialog::OnMotion,    this);
    search_list->GetMainWindow()->Bind(wxEVT_LEFT_DOWN, &SearchDialog::OnLeftDown, this);
#endif //__WXMSW__
    // Under OSX mouse and key states didn't fill after wxEVT_DATAVIEW_SELECTION_CHANGED call
    // As a result, we can't to identify what kind of actions was done
    // So, under OSX is used OnKeyDown function to navigate inside the list
#ifdef __APPLE__
    search_list->Bind(wxEVT_KEY_DOWN, &SearchDialog::OnKeyDown, this);
#endif
    check_category->Bind(wxEVT_CHECKBOX, &SearchDialog::OnCheck, this);
    if (check_english)
        check_english ->Bind(wxEVT_CHECKBOX, &SearchDialog::OnCheck, this);
//    Bind(wxEVT_MOTION, &SearchDialog::OnMotion, this);
    Bind(wxEVT_LEFT_DOWN, &SearchDialog::OnLeftDown, this);
    SetSizer(topSizer);
    topSizer->SetSizeHints(this);
}
References _L, check_category, check_english, Slic3r::Search::SearchListModel::colIcon, Slic3r::Search::SearchListModel::colMarkedText, default_string, Slic3r::GUI::DPIAware< P >::em_unit(), Slic3r::GUI::DPIAware< P >::normal_font(), OnActivate(), OnCheck(), OnInputText(), OnKeyDown(), OnLeftDown(), OnLeftUpInTextCtrl(), OnMotion(), OnSelect(), search_line, search_list, and search_list_model.
~SearchDialog()
Slic3r::Search::SearchDialog::~SearchDialog () inline
{}
Member Function Documentation
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::FileArchiveDialog::FileArchiveDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::PageMaterials::PageMaterials(), SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::ExtruderSequenceDialog::apply_extruder_sequence(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::DiffPresetDialog::complete_dialog_creation(), Slic3r::GUI::DiffPresetDialog::create_edit_sizer(), Slic3r::GUI::DiffPresetDialog::create_presets_sizer(), Slic3r::GUI::DiffPresetDialog::create_tree(), em_unit(), Slic3r::GUI::SavePresetDialog::Item::init_input_name_ctrl(), msw_rescale(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigSnapshotDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::FileArchiveDialog::on_dpi_changed(), Slic3r::FirmwareDialog::on_dpi_changed(), Slic3r::GUI::GalleryDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::LoadProjectsDialog::on_dpi_changed(), Slic3r::GUI::ProjectDropDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
Referenced by Slic3r::GUI::MainFrame::update_layout().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
msw_rescale()
void Slic3r::Search::SearchDialog::msw_rescale ()
{
    const int& em = em_unit();
#ifdef __WXMSW__
    search_list->GetColumn(SearchListModel::colIconMarkedText)->SetWidth(48  * em);
#else
    search_list->GetColumn(SearchListModel::colIcon      )->SetWidth(3  * em);
    search_list->GetColumn(SearchListModel::colMarkedText)->SetWidth(45 * em);
#endif
    const wxSize& size = wxSize(40 * em, 30 * em);
    SetMinSize(size);
    Fit();
    Refresh();
}
References Slic3r::Search::SearchListModel::colIcon, Slic3r::Search::SearchListModel::colMarkedText, Slic3r::GUI::DPIAware< P >::em_unit(), and search_list.
Referenced by Slic3r::Search::OptionsSearcher::dlg_msw_rescale(), and on_dpi_changed().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigSnapshotDialog::ConfigSnapshotDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ExtruderSequenceDialog::ExtruderSequenceDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::LoadProjectsDialog::LoadProjectsDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::MainFrame::init_tabpanel(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::MainFrame::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
on_dpi_changed()
void Slic3r::Search::SearchDialog::on_dpi_changed (const wxRect & suggested_rect) inline override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{ msw_rescale(); }
References msw_rescale().
on_sys_color_changed()
void Slic3r::Search::SearchDialog::on_sys_color_changed () override virtual
Reimplemented from Slic3r::GUI::DPIAware< P >.
{
#ifdef _WIN32
    GUI::wxGetApp().UpdateAllStaticTextDarkUI(this);
    GUI::wxGetApp().UpdateDarkUI(static_cast<wxButton*>(this->FindWindowById(wxID_CANCEL, this)), true);
    for (wxWindow* win : std::vector<wxWindow*> {search_line, search_list, check_category, check_english})
        if (win) GUI::wxGetApp().UpdateDarkUI(win);
#endif
    // msw_rescale updates just icons, so use it
    search_list_model->sys_color_changed();
    Refresh();
}
References check_category, check_english, search_line, search_list, search_list_model, and Slic3r::Search::SearchListModel::sys_color_changed().
Referenced by Slic3r::Search::OptionsSearcher::dlg_sys_color_changed().
OnActivate()
void Slic3r::Search::SearchDialog::OnActivate (wxDataViewEvent & event) private
{
    ProcessSelection(event.GetItem());
}
References ProcessSelection().
Referenced by SearchDialog().
OnCheck()
void Slic3r::Search::SearchDialog::OnCheck (wxCommandEvent & event) private
{
    OptionViewParameters& params = searcher->view_params;
    if (check_english)
        params.english  = check_english->GetValue();
    params.category = check_category->GetValue();
    searcher->search();
    update_list();
}
References Slic3r::Search::OptionViewParameters::category, check_category, check_english, Slic3r::Search::OptionViewParameters::english, Slic3r::Search::OptionsSearcher::search(), searcher, update_list(), and Slic3r::Search::OptionsSearcher::view_params.
Referenced by SearchDialog().
OnInputText()
void Slic3r::Search::SearchDialog::OnInputText (wxCommandEvent & event) private
{
    wxString input_string = search_line->GetValue();
    if (input_string == default_string)
        input_string.Clear();
    searcher->search(into_u8(input_string));
    update_list();
}
References default_string, Slic3r::Search::OptionsSearcher::search(), search_line, searcher, and update_list().
Referenced by SearchDialog().
OnKeyDown()
void Slic3r::Search::SearchDialog::OnKeyDown (wxKeyEvent & event) private
{
    int key = event.GetKeyCode();
    // change selected item in the list
    if (key == WXK_UP || key == WXK_DOWN)
    {
        // So, for the next correct navigation, set focus on the search_list
        search_list->SetFocus();
        auto item = search_list->GetSelection();
        if (item.IsOk()) {
            unsigned selection = search_list_model->GetRow(item);
            if (key == WXK_UP && selection > 0)
                selection--;
            if (key == WXK_DOWN && selection < unsigned(search_list_model->GetCount() - 1))
                selection++;
            prevent_list_events = true;
            search_list->Select(search_list_model->GetItem(selection));
            prevent_list_events = false;
        }
    }
    // process "Enter" pressed
    else if (key == WXK_NUMPAD_ENTER || key == WXK_RETURN)
        ProcessSelection(search_list->GetSelection());
    else
        event.Skip(); // !Needed to have EVT_CHAR generated as well
}
References prevent_list_events, ProcessSelection(), search_list, and search_list_model.
Referenced by SearchDialog().
OnLeftDown()
void Slic3r::Search::SearchDialog::OnLeftDown (wxMouseEvent & event) private
{
    ProcessSelection(search_list->GetSelection());
}
References ProcessSelection(), and search_list.
Referenced by SearchDialog().
OnLeftUpInTextCtrl()
void Slic3r::Search::SearchDialog::OnLeftUpInTextCtrl (wxEvent & event) private
{
    if (search_line->GetValue() == default_string)
        search_line->SetValue("");
    event.Skip();
}
References default_string, and search_line.
Referenced by SearchDialog().
OnMotion()
void Slic3r::Search::SearchDialog::OnMotion (wxMouseEvent & event) private
{
    wxDataViewItem    item;
    wxDataViewColumn* col;
    wxWindow* win = this;
#ifdef __WXMSW__
    win = search_list;
#endif
    search_list->HitTest(wxGetMousePosition() - win->GetScreenPosition(), item, col);
    search_list->Select(item);
    event.Skip();
}
References col(), and search_list.
Referenced by SearchDialog().
OnSelect()
void Slic3r::Search::SearchDialog::OnSelect (wxDataViewEvent & event) private
{
    // To avoid selection update from Select() under osx
    if (prevent_list_events)
        return;
    // Under OSX mouse and key states didn't fill after wxEVT_DATAVIEW_SELECTION_CHANGED call
    // As a result, we can't to identify what kind of actions was done
    // So, under OSX is used OnKeyDown function to navigate inside the list
#ifndef __APPLE__
    // wxEVT_DATAVIEW_SELECTION_CHANGED is processed, when selection is changed after mouse click or press the Up/Down arrows
    // But this two cases should be processed in different way:
    // Up/Down arrows   -> leave it as it is (just a navigation)
    // LeftMouseClick   -> call the ProcessSelection function
    if (wxGetMouseState().LeftIsDown())
#endif //__APPLE__
        ProcessSelection(search_list->GetSelection());
}
References prevent_list_events, ProcessSelection(), and search_list.
Referenced by SearchDialog().
Popup()
void Slic3r::Search::SearchDialog::Popup (wxPoint position = wxDefaultPosition)
{
    const std::string& line = searcher->search_string();
    search_line->SetValue(line.empty() ? default_string : from_u8(line));
    search_line->SetFocus();
    search_line->SelectAll();
    update_list();
    const OptionViewParameters& params = searcher->view_params;
    check_category->SetValue(params.category);
    if (check_english)
        check_english->SetValue(params.english);
    if (position != wxDefaultPosition)
        this->SetPosition(position);
    this->ShowModal();
}
References Slic3r::Search::OptionViewParameters::category, check_category, check_english, default_string, Slic3r::Search::OptionViewParameters::english, search_line, Slic3r::Search::OptionsSearcher::search_string(), searcher, update_list(), and Slic3r::Search::OptionsSearcher::view_params.
Referenced by Slic3r::Search::OptionsSearcher::show_dialog().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
ProcessSelection()
void Slic3r::Search::SearchDialog::ProcessSelection (wxDataViewItem selection)
{
    if (!selection.IsOk())
        return;
    this->EndModal(wxID_CLOSE);
    // If call GUI::wxGetApp().sidebar.jump_to_option() directly from here,
    // then mainframe will not have focus and found option will not be "active" (have cursor) as a result
    // SearchDialog have to be closed and have to lose a focus
    // and only after that jump_to_option() function can be called
    // So, post event to plater:
    wxCommandEvent event(wxCUSTOMEVT_JUMP_TO_OPTION);
    event.SetInt(search_list_model->GetRow(selection));
    wxPostEvent(GUI::wxGetApp().plater(), event);
}
References search_list_model.
Referenced by OnActivate(), OnKeyDown(), OnLeftDown(), and OnSelect().
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DiffPresetDialog::on_dpi_changed().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
update_list()
void Slic3r::Search::SearchDialog::update_list () private
{
    // Under OSX model->Clear invoke wxEVT_DATAVIEW_SELECTION_CHANGED, so
    // set prevent_list_events to true already here
    prevent_list_events = true;
    search_list_model->Clear();
    const std::vector<FoundOption>& filters = searcher->found_options();
    for (const FoundOption& item : filters)
        search_list_model->Prepend(item.label);
    // select first item, if search_list
    if (search_list_model->GetCount() > 0)
        search_list->Select(search_list_model->GetItem(0));
    prevent_list_events = false;
}
References Slic3r::Search::SearchListModel::Clear(), Slic3r::Search::OptionsSearcher::found_options(), Slic3r::Search::SearchListModel::Prepend(), prevent_list_events, search_list, search_list_model, and searcher.
Referenced by OnCheck(), OnInputText(), and Popup().
Member Data Documentation
check_category
wxCheckBox* Slic3r::Search::SearchDialog::check_category { nullptr } private
Referenced by SearchDialog(), on_sys_color_changed(), OnCheck(), and Popup().
check_english
wxCheckBox* Slic3r::Search::SearchDialog::check_english { nullptr } private
Referenced by SearchDialog(), on_sys_color_changed(), OnCheck(), and Popup().
default_string
wxString Slic3r::Search::SearchDialog::default_string private
Referenced by SearchDialog(), OnInputText(), OnLeftUpInTextCtrl(), and Popup().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
prevent_list_events
bool Slic3r::Search::SearchDialog::prevent_list_events {false} private
Referenced by OnKeyDown(), OnSelect(), and update_list().
search_line
wxTextCtrl* Slic3r::Search::SearchDialog::search_line { nullptr } private
Referenced by SearchDialog(), on_sys_color_changed(), OnInputText(), OnLeftUpInTextCtrl(), and Popup().
search_list
wxDataViewCtrl* Slic3r::Search::SearchDialog::search_list { nullptr } private
Referenced by SearchDialog(), msw_rescale(), on_sys_color_changed(), OnKeyDown(), OnLeftDown(), OnMotion(), OnSelect(), and update_list().
search_list_model
SearchListModel* Slic3r::Search::SearchDialog::search_list_model { nullptr } private
Referenced by SearchDialog(), on_sys_color_changed(), OnKeyDown(), ProcessSelection(), and update_list().
search_str
wxString Slic3r::Search::SearchDialog::search_str private
searcher
OptionsSearcher* Slic3r::Search::SearchDialog::searcher { nullptr } private
Referenced by OnCheck(), OnInputText(), Popup(), and update_list().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Search.hpp
src/slic3r/GUI/Search.cpp