Prusa Slicer: Slic3r::GUI::SettingsFactory Struct Reference
Slic3r::GUI::SettingsFactory Struct Reference
#include <src/slic3r/GUI/GUI_Factories.hpp>
Public Types
typedef std::map< std::string, std::vector< std::string > > Bundle
Static Public Member Functions
static wxBitmapBundle * get_category_bitmap (const std::string &category_name)
static Bundle get_bundle (const DynamicPrintConfig *config, bool is_object_settings)
static std::vector< std::string > get_options (bool is_part)
Static Public Attributes
static std::map< std::string, std::string > CATEGORY_ICON
Detailed Description
Member Typedef Documentation
Bundle
typedef std::map<std::string, std::vector<std::string> > Slic3r::GUI::SettingsFactory::Bundle
Member Function Documentation
get_bundle()
SettingsFactory::Bundle Slic3r::GUI::SettingsFactory::get_bundle (const DynamicPrintConfig * config, bool is_object_settings) static
{
    auto opt_keys = config->keys();
    if (opt_keys.empty())
        return Bundle();
    // update options list according to print technology
    auto full_current_opts = get_options(!is_object_settings);
    for (int i = opt_keys.size() - 1; i >= 0; --i)
        if (find(full_current_opts.begin(), full_current_opts.end(), opt_keys[i]) == full_current_opts.end())
            opt_keys.erase(opt_keys.begin() + i);
    if (opt_keys.empty())
        return Bundle();
    const int extruders_cnt = wxGetApp().extruders_edited_cnt();
    Bundle bundle;
    for (auto& opt_key : opt_keys)
    {
        auto category = config->def()->get(opt_key)->category;
        if (is_improper_category(category, extruders_cnt, is_object_settings))
            continue;
        std::vector< std::string > new_category;
        auto& cat_opt = bundle.find(category) == bundle.end() ? new_category : bundle.at(category);
        cat_opt.push_back(opt_key);
        if (cat_opt.size() == 1)
            bundle[category] = cat_opt;
    }
    return bundle;
}
References Slic3r::ConfigOptionDef::category, Slic3r::DynamicPrintConfig::def(), Slic3r::ConfigDef::get(), get_options(), Slic3r::GUI::is_improper_category(), and Slic3r::DynamicConfig::keys().
Referenced by Slic3r::GUI::ObjectList::add_settings_item(), and Slic3r::GUI::ObjectSettings::update_settings_list().
get_category_bitmap()
wxBitmapBundle * Slic3r::GUI::SettingsFactory::get_category_bitmap (const std::string & category_name) static
{
    if (CATEGORY_ICON.find(category_name) == CATEGORY_ICON.end())
        return get_bmp_bundle("empty");
    return get_bmp_bundle(CATEGORY_ICON.at(category_name));
}
References CATEGORY_ICON, and get_bmp_bundle().
Referenced by Slic3r::GUI::create_freq_settings_popupmenu(), Slic3r::GUI::create_settings_popupmenu(), and Slic3r::GUI::ObjectDataViewModelNode::update_settings_digest_bitmaps().
get_options()
std::vector< std::string > Slic3r::GUI::SettingsFactory::get_options (bool is_part) static
{
    if (printer_technology() == ptSLA) {
        SLAPrintObjectConfig full_sla_config;
        auto options = full_sla_config.keys();
        options.erase(find(options.begin(), options.end(), "layer_height"));
        return options;
    }
    PrintRegionConfig reg_config;
    auto options = reg_config.keys();
    if (!is_part) {
        PrintObjectConfig obj_config;
        std::vector<std::string> obj_options = obj_config.keys();
        options.insert(options.end(), obj_options.begin(), obj_options.end());
    }
    return options;
}
References Slic3r::GUI::printer_technology(), Slic3r::PrintObjectConfig, Slic3r::PrintRegionConfig, Slic3r::ptSLA, and Slic3r::SLAPrintObjectConfig.
Referenced by get_bundle(), Slic3r::GUI::get_full_settings_hierarchy(), and Slic3r::GUI::ObjectList::paste_settings_into_list().
Member Data Documentation
CATEGORY_ICON
std::map< std::string, std::string > Slic3r::GUI::SettingsFactory::CATEGORY_ICON static
Initial value:
=
{
    { L("Layers and Perimeters"), "layers"      },
    { L("Infill")               , "infill"      },
    { L("Ironing")              , "ironing"     },
    { L("Fuzzy Skin")           , "fuzzy_skin"  },
    { L("Support material")     , "support"     },
    { L("Speed")                , "time"        },
    { L("Extruders")            , "funnel"      },
    { L("Extrusion Width")      , "funnel"      },
    { L("Wipe options")         , "funnel"      },
    { L("Skirt and brim")       , "skirt+brim"  },
    { L("Advanced")             , "wrench"      },
    { L("Supports")             , "support"     },
    { L("Pad")                  , "pad"         },
    { L("Hollowing")            , "hollowing"   }
}
Referenced by get_category_bitmap().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GUI_Factories.hpp
src/slic3r/GUI/GUI_Factories.cpp