Prusa Slicer: Slic3r::GUI::ArchiveViewNode Class Reference
Slic3r::GUI::ArchiveViewNode Class Reference
#include <src/slic3r/GUI/FileArchiveDialog.hpp>
Public Member Functions
ArchiveViewNode (const wxString &name)
std::vector< std::shared_ptr< ArchiveViewNode > > & get_children ()
void set_parent (std::shared_ptr< ArchiveViewNode > parent)
std::shared_ptr< ArchiveViewNode > get_parent () const
bool is_container () const
void set_container (bool is_container)
wxString get_name () const
void set_name (const wxString &name)
bool get_toggle () const
void set_toggle (bool toggle)
bool get_is_folder () const
void set_is_folder (bool is_folder)
void set_fullpath (boost::filesystem::path path)
boost::filesystem::path get_fullpath () const
void set_size (size_t size)
size_t get_size () const
Private Attributes
wxString m_name
std::shared_ptr< ArchiveViewNode > m_parent { nullptr }
std::vector< std::shared_ptr< ArchiveViewNode > > m_children
bool m_toggle { false }
bool m_folder { false }
boost::filesystem::path m_fullpath
bool m_container { false }
size_t m_size { 0 }
Detailed Description
Constructor & Destructor Documentation
ArchiveViewNode()
Slic3r::GUI::ArchiveViewNode::ArchiveViewNode (const wxString & name) inline
: m_name(name) {}
Member Function Documentation
get_children()
std::vector< std::shared_ptr< ArchiveViewNode > > & Slic3r::GUI::ArchiveViewNode::get_children () inline
{ return m_children; }
References m_children.
Referenced by Slic3r::GUI::ArchiveViewModel::Delete(), Slic3r::GUI::ArchiveViewModel::GetChildren(), and Slic3r::GUI::ArchiveViewModel::SetValue().
get_fullpath()
boost::filesystem::path Slic3r::GUI::ArchiveViewNode::get_fullpath () const inline
{ return m_fullpath; }
References m_fullpath.
get_is_folder()
bool Slic3r::GUI::ArchiveViewNode::get_is_folder () const inline
{ return m_folder; }
References m_folder.
get_name()
wxString Slic3r::GUI::ArchiveViewNode::get_name () const inline
{ return m_name; }
References m_name.
Referenced by Slic3r::GUI::ArchiveViewModel::GetValue().
get_parent()
std::shared_ptr< ArchiveViewNode > Slic3r::GUI::ArchiveViewNode::get_parent () const inline
{ return m_parent; }
References m_parent.
Referenced by Slic3r::GUI::ArchiveViewModel::Delete(), Slic3r::GUI::ArchiveViewModel::GetParent(), Slic3r::GUI::ArchiveViewModel::SetValue(), and Slic3r::GUI::ArchiveViewModel::untoggle_folders().
get_size()
size_t Slic3r::GUI::ArchiveViewNode::get_size () const inline
{ return m_size; }
References m_size.
get_toggle()
bool Slic3r::GUI::ArchiveViewNode::get_toggle () const inline
{ return  m_toggle; }
References m_toggle.
Referenced by Slic3r::GUI::ArchiveViewModel::GetValue().
is_container()
bool Slic3r::GUI::ArchiveViewNode::is_container () const inline
{ return m_container; }
References m_container.
Referenced by Slic3r::GUI::ArchiveViewModel::IsContainer(), and set_container().
set_container()
void Slic3r::GUI::ArchiveViewNode::set_container (bool is_container) inline
{ m_container = is_container; }
References is_container(), and m_container.
set_fullpath()
void Slic3r::GUI::ArchiveViewNode::set_fullpath (boost::filesystem::path path) inline
{ m_fullpath = path; }
References m_fullpath.
set_is_folder()
void Slic3r::GUI::ArchiveViewNode::set_is_folder (bool is_folder) inline
{ m_folder = is_folder; }
References m_folder.
set_name()
void Slic3r::GUI::ArchiveViewNode::set_name (const wxString & name) inline
{ m_name = name; }
References m_name.
Referenced by Slic3r::GUI::ArchiveViewModel::SetValue().
set_parent()
void Slic3r::GUI::ArchiveViewNode::set_parent (std::shared_ptr< ArchiveViewNode > parent) inline
{ m_parent = parent; }
References m_parent.
set_size()
void Slic3r::GUI::ArchiveViewNode::set_size (size_t size) inline
{ m_size = size; }
References m_size.
set_toggle()
void Slic3r::GUI::ArchiveViewNode::set_toggle (bool toggle) inline
{ m_toggle = toggle; }
References m_toggle.
Referenced by Slic3r::GUI::ArchiveViewModel::SetValue(), and Slic3r::GUI::ArchiveViewModel::untoggle_folders().
Member Data Documentation
m_children
std::vector<std::shared_ptr<ArchiveViewNode> > Slic3r::GUI::ArchiveViewNode::m_children private
Referenced by get_children().
m_container
bool Slic3r::GUI::ArchiveViewNode::m_container { false } private
Referenced by is_container(), and set_container().
m_folder
bool Slic3r::GUI::ArchiveViewNode::m_folder { false } private
Referenced by get_is_folder(), and set_is_folder().
m_fullpath
boost::filesystem::path Slic3r::GUI::ArchiveViewNode::m_fullpath private
Referenced by get_fullpath(), and set_fullpath().
m_name
wxString Slic3r::GUI::ArchiveViewNode::m_name private
Referenced by get_name(), and set_name().
m_parent
std::shared_ptr<ArchiveViewNode> Slic3r::GUI::ArchiveViewNode::m_parent { nullptr } private
Referenced by get_parent(), and set_parent().
m_size
size_t Slic3r::GUI::ArchiveViewNode::m_size { 0 } private
Referenced by get_size(), and set_size().
m_toggle
bool Slic3r::GUI::ArchiveViewNode::m_toggle { false } private
Referenced by get_toggle(), and set_toggle().
The documentation for this class was generated from the following file:
src/slic3r/GUI/FileArchiveDialog.hpp