Prusa Slicer: agg::bezier_arc_svg Class Reference
agg::bezier_arc_svg Class Reference
#include <src/agg/agg_bezier_arc.h>
Public Member Functions
bezier_arc_svg ()
bezier_arc_svg (double x1, double y1, double rx, double ry, double angle, bool large_arc_flag, bool sweep_flag, double x2, double y2)
void init (double x1, double y1, double rx, double ry, double angle, bool large_arc_flag, bool sweep_flag, double x2, double y2)
bool radii_ok () const
void rewind (unsigned)
unsigned vertex (double *x, double *y)
unsigned num_vertices () const
const double * vertices () const
double * vertices ()
Private Attributes
bezier_arc m_arc
bool m_radii_ok
Detailed Description
Constructor & Destructor Documentation
bezier_arc_svg() [1/2]
agg::bezier_arc_svg::bezier_arc_svg () inline
: m_arc(), m_radii_ok(false) {}
bezier_arc_svg() [2/2]
agg::bezier_arc_svg::bezier_arc_svg (double x1, double y1, double rx, double ry, double angle, bool large_arc_flag, bool sweep_flag, double x2, double y2) inline
                                             :
            m_arc(), m_radii_ok(false)
        {
            init(x1, y1, rx, ry, angle, large_arc_flag, sweep_flag, x2, y2);
        }
References init().
Member Function Documentation
init()
void agg::bezier_arc_svg::init (double x1, double y1, double rx, double ry, double angle, bool large_arc_flag, bool sweep_flag, double x2, double y2)
Referenced by bezier_arc_svg().
num_vertices()
unsigned agg::bezier_arc_svg::num_vertices () const inline
{ return m_arc.num_vertices(); }
References m_arc, and agg::bezier_arc::num_vertices().
radii_ok()
bool agg::bezier_arc_svg::radii_ok () const inline
{ return m_radii_ok; }
References m_radii_ok.
rewind()
void agg::bezier_arc_svg::rewind (unsigned) inline
        {
            m_arc.rewind(0);
        }
References m_arc, and agg::bezier_arc::rewind().
vertex()
unsigned agg::bezier_arc_svg::vertex (double * x, double * y) inline
        {
            return m_arc.vertex(x, y);
        }
References m_arc, and agg::bezier_arc::vertex().
vertices() [1/2]
double * agg::bezier_arc_svg::vertices () inline
{ return m_arc.vertices();     }
References m_arc, and agg::bezier_arc::vertices().
vertices() [2/2]
const double * agg::bezier_arc_svg::vertices () const inline
{ return m_arc.vertices();     }
References m_arc, and agg::bezier_arc::vertices().
Member Data Documentation
m_arc
bezier_arc agg::bezier_arc_svg::m_arc private
Referenced by num_vertices(), rewind(), vertex(), vertices(), and vertices().
m_radii_ok
bool agg::bezier_arc_svg::m_radii_ok private
Referenced by radii_ok().
The documentation for this class was generated from the following file:
src/agg/agg_bezier_arc.h