Prusa Slicer: agg::line_adaptor Class Reference
agg::line_adaptor Class Reference
#include <src/agg/agg_path_storage.h>
Public Types
typedef double value_type
Public Member Functions
line_adaptor ()
line_adaptor (double x1, double y1, double x2, double y2)
void init (double x1, double y1, double x2, double y2)
void rewind (unsigned)
unsigned vertex (double *x, double *y)
Private Attributes
double m_coord [4]
poly_plain_adaptor< double > m_line
Detailed Description
Member Typedef Documentation
value_type
typedef double agg::line_adaptor::value_type
Constructor & Destructor Documentation
line_adaptor() [1/2]
agg::line_adaptor::line_adaptor () inline
: m_line(m_coord, 2, false) {}
line_adaptor() [2/2]
agg::line_adaptor::line_adaptor (double x1, double y1, double x2, double y2) inline
                                                                 :
            m_line(m_coord, 2, false)
        {
            m_coord[0] = x1;
            m_coord[1] = y1;
            m_coord[2] = x2;
            m_coord[3] = y2;
        }
References m_coord.
Member Function Documentation
init()
void agg::line_adaptor::init (double x1, double y1, double x2, double y2) inline
        {
            m_coord[0] = x1;
            m_coord[1] = y1;
            m_coord[2] = x2;
            m_coord[3] = y2;
            m_line.rewind(0);
        }
References m_coord, m_line, and agg::poly_plain_adaptor< T >::rewind().
rewind()
void agg::line_adaptor::rewind (unsigned) inline
        {
            m_line.rewind(0);
        }
References m_line, and agg::poly_plain_adaptor< T >::rewind().
vertex()
unsigned agg::line_adaptor::vertex (double * x, double * y) inline
        {
            return m_line.vertex(x, y);
        }
References m_line, and agg::poly_plain_adaptor< T >::vertex().
Member Data Documentation
m_coord
double agg::line_adaptor::m_coord[4] private
Referenced by line_adaptor(), and init().
m_line
poly_plain_adaptor<double> agg::line_adaptor::m_line private
Referenced by init(), rewind(), and vertex().
The documentation for this class was generated from the following file:
src/agg/agg_path_storage.h