Prusa Slicer: Slic3r::GUI::OG_Settings Class Reference
Slic3r::GUI::OG_Settings Class Reference
#include <src/slic3r/GUI/GUI_ObjectSettings.hpp>
Public Member Functions
OG_Settings (wxWindow *parent, const bool staticbox)
virtual ~OG_Settings ()
virtual bool IsShown ()
virtual void Show (const bool show)
virtual void Hide ()
virtual void UpdateAndShow (const bool show)
virtual wxSizer * get_sizer ()
ConfigOptionsGroup * get_og ()
const ConfigOptionsGroup * get_og () const
wxWindow * parent () const
Protected Attributes
std::shared_ptr< ConfigOptionsGroup > m_og
wxWindow * m_parent
Detailed Description
Constructor & Destructor Documentation
OG_Settings()
Slic3r::GUI::OG_Settings::OG_Settings (wxWindow * parent, const bool staticbox)
                                                               :
    m_parent(parent)
{
    wxString title = staticbox ? " " : ""; // temporary workaround - #ys_FIXME
    m_og = std::make_shared<ConfigOptionsGroup>(parent, title);
}
References m_og, and parent().
~OG_Settings()
virtual Slic3r::GUI::OG_Settings::~OG_Settings () inline virtual
{}
Member Function Documentation
get_og() [1/2]
ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () inline
{ return m_og.get(); }
References m_og.
Referenced by Slic3r::GUI::ObjectManipulation::msw_rescale(), and Slic3r::GUI::ObjectManipulation::sys_color_changed().
get_og() [2/2]
const ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () const inline
{ return m_og.get(); }
References m_og.
get_sizer()
wxSizer * Slic3r::GUI::OG_Settings::get_sizer () virtual
Reimplemented in Slic3r::GUI::FreqChangedParams.
{
    return m_og->sizer;
}
References m_og.
Hide()
void Slic3r::GUI::OG_Settings::Hide () virtual
{
    Show(false);
}
References Show().
IsShown()
bool Slic3r::GUI::OG_Settings::IsShown () virtual
Reimplemented in Slic3r::GUI::ObjectManipulation.
{
    return m_og->sizer->IsEmpty() ? false : m_og->sizer->IsShown(size_t(0));
}
References m_og.
parent()
wxWindow * Slic3r::GUI::OG_Settings::parent () const inline
{return m_parent; }
References m_parent.
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectSettings::ObjectSettings(), OG_Settings(), Slic3r::GUI::ObjectManipulation::msw_rescale(), and Slic3r::GUI::ObjectSettings::update_settings_list().
Show()
void Slic3r::GUI::OG_Settings::Show (const bool show) virtual
Reimplemented in Slic3r::GUI::FreqChangedParams, and Slic3r::GUI::ObjectManipulation.
{
    m_og->Show(show);
}
References m_og.
Referenced by Hide(), and UpdateAndShow().
UpdateAndShow()
void Slic3r::GUI::OG_Settings::UpdateAndShow (const bool show) virtual
Reimplemented in Slic3r::GUI::ObjectLayers, Slic3r::GUI::ObjectManipulation, and Slic3r::GUI::ObjectSettings.
{
    Show(show);
//    m_parent->Layout();
}
References Show().
Referenced by Slic3r::GUI::ObjectManipulation::UpdateAndShow(), and Slic3r::GUI::ObjectSettings::UpdateAndShow().
Member Data Documentation
m_og
std::shared_ptr<ConfigOptionsGroup> Slic3r::GUI::OG_Settings::m_og protected
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectSettings::ObjectSettings(), OG_Settings(), get_og(), get_og(), Slic3r::GUI::FreqChangedParams::get_og(), get_sizer(), IsShown(), Slic3r::GUI::ObjectManipulation::IsShown(), Slic3r::GUI::FreqChangedParams::msw_rescale(), Slic3r::GUI::FreqChangedParams::Show(), Show(), Slic3r::GUI::ObjectManipulation::Show(), Slic3r::GUI::ObjectSettings::sys_color_changed(), Slic3r::GUI::FreqChangedParams::sys_color_changed(), Slic3r::GUI::ObjectManipulation::update_if_dirty(), and Slic3r::GUI::ObjectSettings::update_settings_list().
m_parent
wxWindow* Slic3r::GUI::OG_Settings::m_parent protected
Referenced by Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), parent(), Slic3r::GUI::ObjectSettings::update_config_values(), Slic3r::GUI::ObjectSettings::update_settings_list(), and Slic3r::GUI::ObjectManipulation::update_warning_icon_state().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectSettings.hpp
src/slic3r/GUI/GUI_ObjectSettings.cpp