Prusa Slicer: Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > > Struct Template Reference
Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > > Struct Template Reference
#include <src/eigen/unsupported/Eigen/src/SparseExtra/DynamicSparseMatrix.h>
Public Types
enum { CoeffReadCost = NumTraits<_Scalar>::ReadCost , Flags = SparseMatrixType::Flags }
typedef _Scalar Scalar
typedef DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > SparseMatrixType
typedef SparseMatrixType::InnerIterator InnerIterator
typedef SparseMatrixType::ReverseInnerIterator ReverseInnerIterator
enum
typedef traits< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > > ExpressionTraits
Public Member Functions
evaluator ()
evaluator (const SparseMatrixType &mat)
operator SparseMatrixType & ()
operator const SparseMatrixType & () const
Scalar coeff (Index row, Index col) const
Index nonZerosEstimate () const
Public Attributes
const SparseMatrixType * m_matrix
Detailed Description
template<typename _Scalar, int _Options, typename _StorageIndex>
struct Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >
Member Typedef Documentation
ExpressionTraits
typedef traits<DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > > Eigen::internal::evaluator_base< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::ExpressionTraits inherited
InnerIterator
template<typename _Scalar , int _Options, typename _StorageIndex > typedef SparseMatrixType::InnerIterator Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::InnerIterator
ReverseInnerIterator
template<typename _Scalar , int _Options, typename _StorageIndex > typedef SparseMatrixType::ReverseInnerIterator Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::ReverseInnerIterator
Scalar
template<typename _Scalar , int _Options, typename _StorageIndex > typedef _Scalar Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::Scalar
SparseMatrixType
template<typename _Scalar , int _Options, typename _StorageIndex > typedef DynamicSparseMatrix<_Scalar,_Options,_StorageIndex> Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::SparseMatrixType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    Alignment = 0
  };
anonymous enum
template<typename _Scalar , int _Options, typename _StorageIndex > anonymous enum
Enumerator
CoeffReadCost
Flags
       {
    CoeffReadCost = NumTraits<_Scalar>::ReadCost,
    Flags = SparseMatrixType::Flags
  };
Constructor & Destructor Documentation
evaluator() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::evaluator () inline
: m_matrix(0) {}
evaluator() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::evaluator (const SparseMatrixType & mat) inline
: m_matrix(&mat) {}
Member Function Documentation
coeff()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::coeff (Index row, Index col) const inline
{ return m_matrix->coeff(row,col); }
References col(), and row().
nonZerosEstimate()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::nonZerosEstimate () const inline
{ return m_matrix->nonZeros(); }
operator const SparseMatrixType &()
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator const SparseMatrixType & () const inline
{ return *m_matrix; }
operator SparseMatrixType &()
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator SparseMatrixType & () inline
{ return m_matrix->const_cast_derived(); }
References Eigen::SparseMatrixBase< Derived >::const_cast_derived().
Member Data Documentation
m_matrix
template<typename _Scalar , int _Options, typename _StorageIndex > const SparseMatrixType* Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::m_matrix
The documentation for this struct was generated from the following file:
src/eigen/unsupported/Eigen/src/SparseExtra/DynamicSparseMatrix.h