Prusa Slicer: Slic3r::DoubleSlider::Control::Ruler Class Reference
Slic3r::DoubleSlider::Control::Ruler Class Reference
Public Member Functions
void set_parent (wxWindow *parent)
void update_dpi ()
void init (const std::vector< double > &values, double scroll_step)
void update (const std::vector< double > &values, double scroll_step)
bool is_ok ()
size_t count ()
bool can_draw ()
Public Attributes
double long_step
double short_step
std::vector< double > max_values
Private Attributes
wxWindow * m_parent {nullptr}
double m_min_val
double m_max_val
double m_scroll_step
size_t m_max_values_cnt
int m_DPI
Detailed Description
Member Function Documentation
can_draw()
bool Slic3r::DoubleSlider::Control::Ruler::can_draw () inline
{ return m_parent != nullptr; }
References m_parent.
Referenced by Slic3r::DoubleSlider::Control::draw_ruler().
count()
size_t Slic3r::DoubleSlider::Control::Ruler::count () inline
{ return max_values.size(); }
References max_values.
Referenced by Slic3r::DoubleSlider::Control::draw_ruler().
init()
void Slic3r::DoubleSlider::Control::Ruler::init (const std::vector< double > & values, double scroll_step)
{
    if (!m_parent)
        return;
    max_values.clear();
    max_values.reserve(std::count(values.begin(), values.end(), values.front()));
    auto it = std::find(values.begin() + 1, values.end(), values.front());
    while (it != values.end()) {
        max_values.push_back(*(it - 1));
        it = std::find(it + 1, values.end(), values.front());
    }
    max_values.push_back(*(it - 1));
    update(values, scroll_step);
}
References m_parent, max_values, and update().
Referenced by Slic3r::DoubleSlider::Control::SetSliderValues().
is_ok()
bool Slic3r::DoubleSlider::Control::Ruler::is_ok () inline
{ return long_step > 0 && short_step > 0; }
References long_step, and short_step.
set_parent()
void Slic3r::DoubleSlider::Control::Ruler::set_parent (wxWindow * parent)
{
    m_parent = parent;
    update_dpi();
}
Referenced by Slic3r::DoubleSlider::Control::Control().
update()
void Slic3r::DoubleSlider::Control::Ruler::update (const std::vector< double > & values, double scroll_step)
{
    if (!m_parent || values.empty() ||
        // check if need to update ruler in respect to input values
        (values.front() == m_min_val && values.back() == m_max_val && m_scroll_step == scroll_step && max_values.size() == m_max_values_cnt))
        return;
    m_min_val           = values.front();
    m_max_val           = values.back();
    m_scroll_step       = scroll_step;
    m_max_values_cnt    = max_values.size();
    int pixels_per_sm = lround((double)(m_DPI) * 5.0/25.4);
    if (lround(scroll_step) > pixels_per_sm) {
        long_step = -1.0;
        return;
    }
    int pow = -2;
    int step = 0;
    auto end_it = std::find(values.begin() + 1, values.end(), values.front());
    while (pow < 3) {
        for (int istep : {1, 2, 5}) {
            double val = (double)istep * std::pow(10,pow);
            auto val_it = std::lower_bound(values.begin(), end_it, val - epsilon());
            if (val_it == values.end())
                break;
            int tick = val_it - values.begin();
            // find next tick with istep
            val *= 2;
            val_it = std::lower_bound(values.begin(), end_it, val - epsilon());
            // count of short ticks between ticks
            int short_ticks_cnt = val_it == values.end() ? tick : val_it - values.begin() - tick;
            if (lround(short_ticks_cnt * scroll_step) > pixels_per_sm) {
                step = istep;
                // there couldn't be more then 10 short ticks between ticks
                short_step = 0.1 * short_ticks_cnt;
                break;
            }
        }
        if (step > 0)
            break;
        pow++;
    }
    long_step = step == 0 ? -1.0 : (double)step* std::pow(10, pow);
    if (long_step < 0)
        short_step = long_step;
}
References Slic3r::DoubleSlider::epsilon().
Referenced by Slic3r::DoubleSlider::Control::Control(), init(), Slic3r::DoubleSlider::Control::msw_rescale(), and Slic3r::DoubleSlider::Control::SetLayersTimes().
update_dpi()
void Slic3r::DoubleSlider::Control::Ruler::update_dpi ()
{
    if (m_parent)
        m_DPI = GUI::get_dpi_for_window(m_parent);
}
References Slic3r::GUI::get_dpi_for_window().
Referenced by Slic3r::DoubleSlider::Control::msw_rescale().
Member Data Documentation
long_step
double Slic3r::DoubleSlider::Control::Ruler::long_step
Referenced by Slic3r::DoubleSlider::Control::draw_ruler(), and is_ok().
m_DPI
int Slic3r::DoubleSlider::Control::Ruler::m_DPI private
m_max_val
double Slic3r::DoubleSlider::Control::Ruler::m_max_val private
m_max_values_cnt
size_t Slic3r::DoubleSlider::Control::Ruler::m_max_values_cnt private
m_min_val
double Slic3r::DoubleSlider::Control::Ruler::m_min_val private
m_parent
wxWindow* Slic3r::DoubleSlider::Control::Ruler::m_parent {nullptr} private
Referenced by can_draw(), and init().
m_scroll_step
double Slic3r::DoubleSlider::Control::Ruler::m_scroll_step private
max_values
std::vector<double> Slic3r::DoubleSlider::Control::Ruler::max_values
Referenced by count(), Slic3r::DoubleSlider::Control::draw_ruler(), and init().
short_step
double Slic3r::DoubleSlider::Control::Ruler::short_step
Referenced by Slic3r::DoubleSlider::Control::draw_ruler(), and is_ok().
The documentation for this class was generated from the following files:
src/slic3r/GUI/DoubleSlider.hpp
src/slic3r/GUI/DoubleSlider.cpp