Prusa Slicer: Slic3r::DoubleSlider::TickCodeInfo Class Reference
Slic3r::DoubleSlider::TickCodeInfo Class Reference
#include <src/slic3r/GUI/DoubleSlider.hpp>
Public Member Functions
bool empty () const
void set_pause_print_msg (const std::string &message)
bool add_tick (const int tick, Type type, int extruder, double print_z)
bool edit_tick (std::set< TickCode >::iterator it, double print_z)
void switch_code (Type type_from, Type type_to)
bool switch_code_for_tick (std::set< TickCode >::iterator it, Type type_to, const int extruder)
void erase_all_ticks_with_code (Type type)
bool has_tick_with_code (Type type)
bool has_tick (int tick)
ConflictType is_conflict_tick (const TickCode &tick, Mode out_mode, int only_extruder, double print_z)
std::set< int > get_used_extruders_for_tick (int tick, int only_extruder, double print_z, Mode force_mode=Undef) const
void suppress_plus (bool suppress)
void suppress_minus (bool suppress)
bool suppressed_plus ()
bool suppressed_minus ()
void set_default_colors (bool default_colors_on)
void set_extruder_colors (std::vector< std::string > *extruder_colors)
Public Attributes
std::set< TickCode > ticks {}
Mode mode = Undef
Private Member Functions
std::string get_color_for_tick (TickCode tick, Type type, const int extruder)
Private Attributes
std::string custom_gcode
std::string pause_print_msg
bool m_suppress_plus = false
bool m_suppress_minus = false
bool m_use_default_colors = false
std::vector< std::string > * m_colors {nullptr}
Detailed Description
Member Function Documentation
add_tick()
bool Slic3r::DoubleSlider::TickCodeInfo::add_tick (const int tick, Type type, int extruder, double print_z)
{
    std::string color;
    std::string extra;
    if (type == Custom)           // custom Gcode
    {
        extra = get_custom_code(custom_gcode, print_z);
        if (extra.empty())
            return false;
        custom_gcode = extra;
    }
    else if (type == PausePrint) {
        extra = get_pause_print_msg(pause_print_msg, print_z);
        if (extra.empty())
            return false;
        pause_print_msg = extra;
    }
    else {
        color = get_color_for_tick(TickCode{ tick }, type, extruder);
        if (color.empty())
            return false;
    }
    if (mode == SingleExtruder)
        m_use_default_colors = true;
    ticks.emplace(TickCode{ tick, type, extruder, color, extra });
    return true;
}
References Slic3r::CustomGCode::Custom, custom_gcode, get_color_for_tick(), Slic3r::DoubleSlider::get_custom_code(), Slic3r::DoubleSlider::get_pause_print_msg(), m_use_default_colors, mode, pause_print_msg, Slic3r::CustomGCode::PausePrint, Slic3r::CustomGCode::SingleExtruder, and ticks.
Referenced by Slic3r::DoubleSlider::Control::add_code_as_tick().
edit_tick()
bool Slic3r::DoubleSlider::TickCodeInfo::edit_tick (std::set< TickCode >::iterator it, double print_z)
{
    std::string edited_value;
    if (it->type == ColorChange)
        edited_value = get_new_color(it->color);
    else if (it->type == PausePrint)
        edited_value = get_pause_print_msg(it->extra, print_z);
    else
        edited_value = get_custom_code(it->type == Template ? gcode(Template) : it->extra, print_z);
    if (edited_value.empty())
        return false;
    TickCode changed_tick = *it;
    if (it->type == ColorChange) {
        if (it->color == edited_value)
            return false;
        changed_tick.color = edited_value;
    }
    else if (it->type == Template) {
        if (gcode(Template) == edited_value)
            return false;
        changed_tick.extra = edited_value;
        changed_tick.type  = Custom;
    }
    else if (it->type == Custom || it->type == PausePrint) {
        if (it->extra == edited_value)
            return false;
        changed_tick.extra = edited_value;
    }
    ticks.erase(it);
    ticks.emplace(changed_tick);
    return true;
}
References Slic3r::DoubleSlider::TickCode::color, Slic3r::CustomGCode::ColorChange, Slic3r::CustomGCode::Custom, Slic3r::DoubleSlider::TickCode::extra, Slic3r::DoubleSlider::gcode(), Slic3r::DoubleSlider::get_custom_code(), Slic3r::DoubleSlider::get_new_color(), Slic3r::DoubleSlider::get_pause_print_msg(), Slic3r::CustomGCode::PausePrint, Slic3r::CustomGCode::Template, ticks, and Slic3r::DoubleSlider::TickCode::type.
Referenced by Slic3r::DoubleSlider::Control::edit_tick().
empty()
bool Slic3r::DoubleSlider::TickCodeInfo::empty () const inline
{ return ticks.empty(); }
References ticks.
Referenced by Slic3r::DoubleSlider::Control::auto_color_change(), Slic3r::DoubleSlider::Control::draw_colored_band(), Slic3r::DoubleSlider::Control::draw_revert_icon(), Slic3r::DoubleSlider::Control::get_active_extruders_for_tick(), Slic3r::DoubleSlider::Control::get_edited_tick_for_position(), Slic3r::DoubleSlider::Control::OnMotion(), Slic3r::DoubleSlider::Control::SetModeAndOnlyExtruder(), and Slic3r::DoubleSlider::Control::SetTicksValues().
erase_all_ticks_with_code()
void Slic3r::DoubleSlider::TickCodeInfo::erase_all_ticks_with_code (Type type)
{
    for (auto it{ ticks.begin() }, end{ ticks.end() }; it != end; ) {
        if (it->type == type)
            it = ticks.erase(it);
        else
            ++it;
    }
}
References ticks.
Referenced by Slic3r::DoubleSlider::Control::check_ticks_changed_event(), and Slic3r::DoubleSlider::Control::edit_extruder_sequence().
get_color_for_tick()
std::string Slic3r::DoubleSlider::TickCodeInfo::get_color_for_tick (TickCode tick, Type type, const int extruder) private
{
    auto opposite_one_color = [](const std::string& color) {
        ColorRGB rgb;
        decode_color(color, rgb);
        return encode_color(opposite(rgb));
    };
    auto opposite_two_colors = [](const std::string& a, const std::string& b) {
        ColorRGB rgb1; decode_color(a, rgb1);
        ColorRGB rgb2; decode_color(b, rgb2);
        return encode_color(opposite(rgb1, rgb2));
    };
    if (mode == SingleExtruder && type == ColorChange && m_use_default_colors) {
#if 1
        if (ticks.empty())
            return opposite_one_color((*m_colors)[0]);
        auto before_tick_it = std::lower_bound(ticks.begin(), ticks.end(), tick);
        if (before_tick_it == ticks.end()) {
            while (before_tick_it != ticks.begin())
                if (--before_tick_it; before_tick_it->type == ColorChange)
                    break;
            if (before_tick_it->type == ColorChange)
                return opposite_one_color(before_tick_it->color);
            return opposite_one_color((*m_colors)[0]);
        }
        if (before_tick_it == ticks.begin()) {
            const std::string& frst_color = (*m_colors)[0];
            if (before_tick_it->type == ColorChange)
                return opposite_two_colors(frst_color, before_tick_it->color);
            auto next_tick_it = before_tick_it;
            while (next_tick_it != ticks.end())
                if (++next_tick_it; next_tick_it->type == ColorChange)
                    break;
            if (next_tick_it->type == ColorChange)
                return opposite_two_colors(frst_color, next_tick_it->color);
            return opposite_one_color(frst_color);
        }
        std::string frst_color = "";
        if (before_tick_it->type == ColorChange)
            frst_color = before_tick_it->color;
        else {
            auto next_tick_it = before_tick_it;
            while (next_tick_it != ticks.end())
                if (++next_tick_it; next_tick_it->type == ColorChange) {
                    frst_color = next_tick_it->color;
                    break;
                }
        }
        while (before_tick_it != ticks.begin())
            if (--before_tick_it; before_tick_it->type == ColorChange)
                break;
        if (before_tick_it->type == ColorChange) {
            if (frst_color.empty())
                return opposite_one_color(before_tick_it->color);
            return opposite_two_colors(before_tick_it->color, frst_color);
        }
        if (frst_color.empty())
            return opposite_one_color((*m_colors)[0]);
        return opposite_two_colors((*m_colors)[0], frst_color);
#else
        const std::vector<std::string>& colors = ColorPrintColors::get();
        if (ticks.empty())
            return colors[0];
        m_default_color_idx++;
        return colors[m_default_color_idx % colors.size()];
#endif
    }
    std::string color = (*m_colors)[extruder - 1];
    if (type == ColorChange) {
        if (!ticks.empty()) {
            auto before_tick_it = std::lower_bound(ticks.begin(), ticks.end(), tick );
            while (before_tick_it != ticks.begin()) {
                --before_tick_it;
                if (before_tick_it->type == ColorChange && before_tick_it->extruder == extruder) {
                    color = before_tick_it->color;
                    break;
                }
            }
        }
        color = get_new_color(color);
    }
    return color;
}
References Slic3r::CustomGCode::ColorChange, Slic3r::decode_color(), Slic3r::encode_color(), Slic3r::ColorPrintColors::get(), Slic3r::DoubleSlider::get_new_color(), m_colors, m_use_default_colors, mode, Slic3r::opposite(), Slic3r::CustomGCode::SingleExtruder, and ticks.
Referenced by add_tick(), and switch_code_for_tick().
get_used_extruders_for_tick()
std::set< int > Slic3r::DoubleSlider::TickCodeInfo::get_used_extruders_for_tick (int tick, int only_extruder, double print_z, Mode force_mode = Undef) const
{
    Mode e_mode = !force_mode ? mode : force_mode;
    if (e_mode == MultiExtruder) {
        // #ys_FIXME: get tool ordering from _correct_ place
        const ToolOrdering& tool_ordering = GUI::wxGetApp().plater()->fff_print().get_tool_ordering();
        if (tool_ordering.empty())
            return {};
        std::set<int> used_extruders;
        auto it_layer_tools = std::lower_bound(tool_ordering.begin(), tool_ordering.end(), print_z, [](const LayerTools &lhs, double rhs){ return lhs.print_z < rhs; });
        for (; it_layer_tools != tool_ordering.end(); ++it_layer_tools) {
            const std::vector<unsigned>& extruders = it_layer_tools->extruders;
            for (const auto& extruder : extruders)
                used_extruders.emplace(extruder+1);
        }
        return used_extruders;
    }
    const int default_initial_extruder = e_mode == MultiAsSingle ? std::max(only_extruder, 1) : 1;
    if (ticks.empty() || e_mode == SingleExtruder)
        return {default_initial_extruder};
    std::set<int> used_extruders;
    auto it_start = ticks.lower_bound(TickCode{tick});
    auto it = it_start;
    if (it == ticks.begin() && it->type == ToolChange &&
        tick != it->tick )  // In case of switch of ToolChange to ColorChange, when tick exists,
                            // we shouldn't change color for extruder, which will be deleted
    {
        used_extruders.emplace(it->extruder);
        if (tick < it->tick)
            used_extruders.emplace(default_initial_extruder);
    }
    while (it != ticks.begin()) {
        --it;
        if (it->type == ToolChange && tick != it->tick) {
            used_extruders.emplace(it->extruder);
            break;
        }
    }
    if (it == ticks.begin() && used_extruders.empty())
        used_extruders.emplace(default_initial_extruder);
    for (it = it_start; it != ticks.end(); ++it)
        if (it->type == ToolChange && tick != it->tick)
            used_extruders.emplace(it->extruder);
    return used_extruders;
}
References Slic3r::ToolOrdering::begin(), Slic3r::ToolOrdering::empty(), Slic3r::ToolOrdering::end(), Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::MultiExtruder, Slic3r::CustomGCode::SingleExtruder, and Slic3r::CustomGCode::ToolChange.
Referenced by Slic3r::DoubleSlider::Control::append_add_color_change_menu_item(), and is_conflict_tick().
has_tick()
bool Slic3r::DoubleSlider::TickCodeInfo::has_tick (int tick)
{
    return ticks.find(TickCode{ tick }) != ticks.end();
}
References ticks.
has_tick_with_code()
bool Slic3r::DoubleSlider::TickCodeInfo::has_tick_with_code (Type type)
{
    for (const TickCode& tick : ticks)
        if (tick.type == type)
            return true;
    return false;
}
References ticks.
Referenced by Slic3r::DoubleSlider::Control::check_ticks_changed_event().
is_conflict_tick()
ConflictType Slic3r::DoubleSlider::TickCodeInfo::is_conflict_tick (const TickCode & tick, Mode out_mode, int only_extruder, double print_z)
{
    if ((tick.type == ColorChange && (
            (mode == SingleExtruder && out_mode == MultiExtruder ) ||
            (mode == MultiExtruder  && out_mode == SingleExtruder)    )) ||
        (tick.type == ToolChange &&
            (mode == MultiAsSingle && out_mode != MultiAsSingle)) )
        return ctModeConflict;
    // check ColorChange tick
    if (tick.type == ColorChange) {
        // We should mark a tick as a "MeaninglessColorChange",
        // if it has a ColorChange for unused extruder from current print to end of the print
        std::set<int> used_extruders_for_tick = get_used_extruders_for_tick(tick.tick, only_extruder, print_z, out_mode);
        if (used_extruders_for_tick.find(tick.extruder) == used_extruders_for_tick.end())
            return ctMeaninglessColorChange;
        // We should mark a tick as a "Redundant",
        // if it has a ColorChange for extruder that has not been used before
        if (mode == MultiAsSingle && tick.extruder != std::max<int>(only_extruder, 1) )
        {
            auto it = ticks.lower_bound( tick );
            if (it == ticks.begin() && it->type == ToolChange && tick.extruder == it->extruder)
                return ctNone;
            while (it != ticks.begin()) {
                --it;
                if (it->type == ToolChange && tick.extruder == it->extruder)
                    return ctNone;
            }
            return ctRedundant;
        }
    }
    // check ToolChange tick
    if (mode == MultiAsSingle && tick.type == ToolChange) {
        // We should mark a tick as a "MeaninglessToolChange",
        // if it has a ToolChange to the same extruder
        auto it = ticks.find(tick);
        if (it == ticks.begin())
            return tick.extruder == std::max<int>(only_extruder, 1) ? ctMeaninglessToolChange : ctNone;
        while (it != ticks.begin()) {
            --it;
            if (it->type == ToolChange)
                return tick.extruder == it->extruder ? ctMeaninglessToolChange : ctNone;
        }
    }
    return ctNone;
}
References Slic3r::CustomGCode::ColorChange, Slic3r::DoubleSlider::ctMeaninglessColorChange, Slic3r::DoubleSlider::ctMeaninglessToolChange, Slic3r::DoubleSlider::ctModeConflict, Slic3r::DoubleSlider::ctNone, Slic3r::DoubleSlider::ctRedundant, Slic3r::DoubleSlider::TickCode::extruder, get_used_extruders_for_tick(), mode, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::MultiExtruder, Slic3r::CustomGCode::SingleExtruder, Slic3r::DoubleSlider::TickCode::tick, ticks, Slic3r::CustomGCode::ToolChange, and Slic3r::DoubleSlider::TickCode::type.
Referenced by Slic3r::DoubleSlider::Control::draw_ticks(), and Slic3r::DoubleSlider::Control::get_tooltip().
set_default_colors()
void Slic3r::DoubleSlider::TickCodeInfo::set_default_colors (bool default_colors_on) inline
{ m_use_default_colors = default_colors_on; }
References m_use_default_colors.
Referenced by Slic3r::DoubleSlider::Control::UseDefaultColors().
set_extruder_colors()
void Slic3r::DoubleSlider::TickCodeInfo::set_extruder_colors (std::vector< std::string > * extruder_colors) inline
{ m_colors = extruder_colors; }
References m_colors.
Referenced by Slic3r::DoubleSlider::Control::Control().
set_pause_print_msg()
void Slic3r::DoubleSlider::TickCodeInfo::set_pause_print_msg (const std::string & message) inline
{ pause_print_msg = message; }
References pause_print_msg.
Referenced by Slic3r::DoubleSlider::Control::Control().
suppress_minus()
void Slic3r::DoubleSlider::TickCodeInfo::suppress_minus (bool suppress) inline
{ m_suppress_minus = suppress; }
References m_suppress_minus.
Referenced by Slic3r::DoubleSlider::Control::OnChar(), and Slic3r::DoubleSlider::Control::OnKeyDown().
suppress_plus()
void Slic3r::DoubleSlider::TickCodeInfo::suppress_plus (bool suppress) inline
{ m_suppress_plus = suppress; }
References m_suppress_plus.
Referenced by Slic3r::DoubleSlider::Control::OnChar(), and Slic3r::DoubleSlider::Control::OnKeyDown().
suppressed_minus()
bool Slic3r::DoubleSlider::TickCodeInfo::suppressed_minus () inline
{ return m_suppress_minus; }
References m_suppress_minus.
Referenced by Slic3r::DoubleSlider::Control::OnChar().
suppressed_plus()
bool Slic3r::DoubleSlider::TickCodeInfo::suppressed_plus () inline
{ return m_suppress_plus; }
References m_suppress_plus.
Referenced by Slic3r::DoubleSlider::Control::OnChar().
switch_code()
void Slic3r::DoubleSlider::TickCodeInfo::switch_code (Type type_from, Type type_to)
{
    for (auto it{ ticks.begin() }, end{ ticks.end() }; it != end; )
        if (it->type == type_from) {
            TickCode tick = *it;
            tick.type = type_to;
            tick.extruder = 1;
            ticks.erase(it);
            it = ticks.emplace(tick).first;
        }
        else
            ++it;
}
References Slic3r::DoubleSlider::TickCode::extruder, ticks, and Slic3r::DoubleSlider::TickCode::type.
Referenced by Slic3r::DoubleSlider::Control::check_ticks_changed_event().
switch_code_for_tick()
bool Slic3r::DoubleSlider::TickCodeInfo::switch_code_for_tick (std::set< TickCode >::iterator it, Type type_to, const int extruder)
{
    const std::string color = get_color_for_tick(*it, type_to, extruder);
    if (color.empty())
        return false;
    TickCode changed_tick   = *it;
    changed_tick.type       = type_to;
    changed_tick.extruder   = extruder;
    changed_tick.color      = color;
    ticks.erase(it);
    ticks.emplace(changed_tick);
    return true;
}
References Slic3r::DoubleSlider::TickCode::color, Slic3r::DoubleSlider::TickCode::extruder, get_color_for_tick(), ticks, and Slic3r::DoubleSlider::TickCode::type.
Referenced by Slic3r::DoubleSlider::Control::add_code_as_tick().
Member Data Documentation
custom_gcode
std::string Slic3r::DoubleSlider::TickCodeInfo::custom_gcode private
Referenced by add_tick().
m_colors
std::vector<std::string>* Slic3r::DoubleSlider::TickCodeInfo::m_colors {nullptr} private
Referenced by get_color_for_tick(), and set_extruder_colors().
m_suppress_minus
bool Slic3r::DoubleSlider::TickCodeInfo::m_suppress_minus = false private
Referenced by suppress_minus(), and suppressed_minus().
m_suppress_plus
bool Slic3r::DoubleSlider::TickCodeInfo::m_suppress_plus = false private
Referenced by suppress_plus(), and suppressed_plus().
m_use_default_colors
bool Slic3r::DoubleSlider::TickCodeInfo::m_use_default_colors = false private
Referenced by add_tick(), get_color_for_tick(), and set_default_colors().
mode
Mode Slic3r::DoubleSlider::TickCodeInfo::mode = Undef
Referenced by add_tick(), Slic3r::DoubleSlider::Control::check_ticks_changed_event(), get_color_for_tick(), is_conflict_tick(), Slic3r::DoubleSlider::Control::SetModeAndOnlyExtruder(), and Slic3r::DoubleSlider::Control::SetTicksValues().
pause_print_msg
std::string Slic3r::DoubleSlider::TickCodeInfo::pause_print_msg private
Referenced by add_tick(), and set_pause_print_msg().
ticks
std::set<TickCode> Slic3r::DoubleSlider::TickCodeInfo::ticks {}
Referenced by Slic3r::DoubleSlider::Control::add_code_as_tick(), Slic3r::DoubleSlider::Control::add_current_tick(), add_tick(), Slic3r::DoubleSlider::Control::auto_color_change(), Slic3r::DoubleSlider::Control::delete_current_tick(), Slic3r::DoubleSlider::Control::discard_all_thicks(), Slic3r::DoubleSlider::Control::draw_action_icon(), Slic3r::DoubleSlider::Control::draw_colored_band(), Slic3r::DoubleSlider::Control::draw_ticks(), Slic3r::DoubleSlider::Control::edit_extruder_sequence(), Slic3r::DoubleSlider::Control::edit_tick(), edit_tick(), empty(), erase_all_ticks_with_code(), Slic3r::DoubleSlider::Control::get_active_extruders_for_tick(), Slic3r::DoubleSlider::Control::get_color_for_color_change_tick(), get_color_for_tick(), Slic3r::DoubleSlider::Control::get_color_for_tool_change_tick(), Slic3r::DoubleSlider::Control::get_edited_tick_for_position(), Slic3r::DoubleSlider::Control::get_tick_near_point(), Slic3r::DoubleSlider::Control::get_tooltip(), Slic3r::DoubleSlider::Control::GetTicksValues(), has_tick(), has_tick_with_code(), is_conflict_tick(), Slic3r::DoubleSlider::Control::OnLeftDown(), Slic3r::DoubleSlider::Control::OnRightDown(), Slic3r::DoubleSlider::Control::SetTicksValues(), Slic3r::DoubleSlider::Control::show_edit_context_menu(), switch_code(), and switch_code_for_tick().
The documentation for this class was generated from the following files:
src/slic3r/GUI/DoubleSlider.hpp
src/slic3r/GUI/DoubleSlider.cpp