Prusa Slicer: libnest2d::_Item< RawShape > Class Template Reference
libnest2d::_Item< RawShape > Class Template Reference
An item to be placed on a bin.
#include <src/libnest2d/include/libnest2d/nester.hpp>
Classes
struct BBCache
Public Types
using ShapeType = RawShape
The type of the shape which was handed over as the template argument.
using Iterator = VertexConstIterator
Iterator type for the outer vertices.
Public Member Functions
_Item (const RawShape &sh)
Constructing an _Item form an existing raw shape. The shape will be copied into the _Item object.
_Item (RawShape &&sh)
Construction of an item by moving the content of the raw shape, assuming that it supports move semantics.
_Item (const std::initializer_list< Vertex > &il)
Create an item from an initializer list.
_Item (const TContour< RawShape > &contour, const THolesContainer< RawShape > &holes={})
_Item (TContour< RawShape > &&contour, THolesContainer< RawShape > &&holes)
bool isFixed () const noexcept
void markAsFixedInBin (int binid)
void binId (int idx)
int binId () const noexcept
void priority (int p)
int priority () const noexcept
std::string toString () const
Convert the polygon to string representation. The format depends on the implementation of the polygon.
Iterator begin () const
Iterator tho the first contour vertex in the polygon.
Iterator cbegin () const
Alias to begin()
Iterator end () const
Iterator to the last contour vertex.
Iterator cend () const
Alias to end()
Vertex vertex (unsigned long idx) const
Get a copy of an outer vertex within the carried shape.
void setVertex (unsigned long idx, const Vertex &v)
Modify a vertex.
void setShape (RawShape rsh)
void setOnPackedFn (std::function< void(_Item &)> onpackedfn)
void onPacked ()
double area () const
Calculate the shape area.
bool isContourConvex () const
bool isHoleConvex (unsigned) const
bool areHolesConvex () const
size_t vertexCount () const
The number of the outer ring vertices.
size_t holeCount () const
bool isInside (const Vertex &p) const
isPointInside
bool isInside (const _Item &sh) const
bool isInside (const RawShape &sh) const
bool isInside (const _Box< TPoint< RawShape > > &box) const
bool isInside (const _Circle< TPoint< RawShape > > &box) const
void translate (const Vertex &d) BP2D_NOEXCEPT
void rotate (const Radians &rads) BP2D_NOEXCEPT
void inflation (Coord distance) BP2D_NOEXCEPT
Coord inflation () const BP2D_NOEXCEPT
void inflate (Coord distance) BP2D_NOEXCEPT
Radians rotation () const BP2D_NOEXCEPT
TPoint< RawShape > translation () const BP2D_NOEXCEPT
void rotation (Radians rot) BP2D_NOEXCEPT
void translation (const TPoint< RawShape > &tr) BP2D_NOEXCEPT
const RawShape & transformedShape () const
operator RawShape () const
const RawShape & rawShape () const BP2D_NOEXCEPT
void resetTransformation () BP2D_NOEXCEPT
Box boundingBox () const
Vertex referenceVertex () const
Vertex rightmostTopVertex () const
Vertex leftmostBottomVertex () const
Static Public Member Functions
static BP2D_CONSTEXPR Orientation orientation ()
Get the orientation of the polygon.
static bool intersects (const _Item &sh1, const _Item &sh2)
static bool touches (const _Item &sh1, const _Item &sh2)
Private Types
enum class Convexity : char { UNCHECKED , C_TRUE , C_FALSE }
using Coord = TCoord< TPoint< RawShape > >
using Vertex = TPoint< RawShape >
using Box = _Box< Vertex >
using VertexConstIterator = typename TContour< RawShape >::const_iterator
Private Member Functions
const RawShape & infaltedShape () const
void invalidateCache () const BP2D_NOEXCEPT
Static Private Member Functions
static bool vsort (const Vertex &v1, const Vertex &v2)
Private Attributes
RawShape sh_
Vertex translation_ {0, 0}
Radians rotation_ {0.0}
Coord inflation_ {0}
bool has_rotation_ = false
bool has_translation_ = false
bool has_inflation_ = false
RawShape tr_cache_
bool tr_cache_valid_ = false
double area_cache_ = 0
bool area_cache_valid_ = false
RawShape inflate_cache_
bool inflate_cache_valid_ = false
Convexity convexity_ = Convexity::UNCHECKED
VertexConstIterator rmt_
VertexConstIterator lmb_
bool rmt_valid_ = false
bool lmb_valid_ = false
struct libnest2d::_Item::BBCache bb_cache_
int binid_ {BIN_ID_UNSET}
int priority_ {0}
bool fixed_ {false}
std::function< void(_Item &)> on_packed_
Detailed Description
template<class RawShape>
class libnest2d::_Item< RawShape >
An item to be placed on a bin.
It holds a copy of the original shape object but supports move construction from the shape objects if its an rvalue reference. This way we can construct the items without the cost of copying a potentially large amount of input.
The results of some calculations are cached for maintaining fast run times. For this reason, memory demands are much higher but this should pay off.
Member Typedef Documentation
Box
template<class RawShape > using libnest2d::_Item< RawShape >::Box = _Box<Vertex> private
Coord
template<class RawShape > using libnest2d::_Item< RawShape >::Coord = TCoord<TPoint<RawShape> > private
Iterator
template<class RawShape > using libnest2d::_Item< RawShape >::Iterator = VertexConstIterator
Iterator type for the outer vertices.
Only const iterators can be used. The _Item type is not intended to modify the carried shapes from the outside. The main purpose of this type is to cache the calculation results from the various operators it supports. Giving out a non const iterator would make it impossible to perform correct cache invalidation.
ShapeType
template<class RawShape > using libnest2d::_Item< RawShape >::ShapeType = RawShape
The type of the shape which was handed over as the template argument.
Vertex
template<class RawShape > using libnest2d::_Item< RawShape >::Vertex = TPoint<RawShape> private
VertexConstIterator
template<class RawShape > using libnest2d::_Item< RawShape >::VertexConstIterator = typename TContour<RawShape>::const_iterator private
Member Enumeration Documentation
Convexity
template<class RawShape > enum class libnest2d::_Item::Convexity : char strong private
Enumerator
UNCHECKED
C_TRUE
C_FALSE
                        : char {
        UNCHECKED,
        C_TRUE,
        C_FALSE
    };
Constructor & Destructor Documentation
_Item() [1/5]
template<class RawShape > libnest2d::_Item< RawShape >::_Item (const RawShape & sh) inline explicit
Constructing an _Item form an existing raw shape. The shape will be copied into the _Item object.
Parameters
sh The original shape object.
: sh_(sh) {}
_Item() [2/5]
template<class RawShape > libnest2d::_Item< RawShape >::_Item (RawShape && sh) inline explicit
Construction of an item by moving the content of the raw shape, assuming that it supports move semantics.
Parameters
sh The original shape object.
: sh_(std::move(sh)) {}
_Item() [3/5]
template<class RawShape > libnest2d::_Item< RawShape >::_Item (const std::initializer_list< Vertex > & il) inline
Create an item from an initializer list.
Parameters
il The initializer list of vertices.
                                                         :
        sh_(sl::create<RawShape>(il)) {}
_Item() [4/5]
template<class RawShape > libnest2d::_Item< RawShape >::_Item (const TContour< RawShape > & contour, const THolesContainer< RawShape > & holes = {}) inline
                                                          {}):
        sh_(sl::create<RawShape>(contour, holes)) {}
_Item() [5/5]
template<class RawShape > libnest2d::_Item< RawShape >::_Item (TContour< RawShape > && contour, THolesContainer< RawShape > && holes) inline
                                                   :
        sh_(sl::create<RawShape>(std::move(contour), std::move(holes))) {}
Member Function Documentation
area()
template<class RawShape > double libnest2d::_Item< RawShape >::area () const inline
Calculate the shape area.
The method returns absolute value and does not reflect polygon orientation. The result is cached, subsequent calls will have very little cost.
Returns
The shape area in floating point double precision.
{
        double ret ;
        if(area_cache_valid_) ret = area_cache_;
        else {
            ret = sl::area(infaltedShape());
            area_cache_ = ret;
            area_cache_valid_ = true;
        }
        return ret;
    }
References libnest2d::shapelike::area(), libnest2d::_Item< RawShape >::area_cache_, libnest2d::_Item< RawShape >::area_cache_valid_, and libnest2d::_Item< RawShape >::infaltedShape().
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), Slic3r::arrangement::AutoArranger< TBin >::objfunc(), libnest2d::selections::_DJDHeuristic< RawShape >::packItems(), libnest2d::selections::_FillerSelection< RawShape >::packItems(), libnest2d::selections::_FirstFitSelection< RawShape >::packItems(), and libnest2d::selections::SelectionBoilerplate< RawShape >::remove_unpackable_items().
areHolesConvex()
template<class RawShape > bool libnest2d::_Item< RawShape >::areHolesConvex () const inline
{
        return false;
    }
begin()
template<class RawShape > Iterator libnest2d::_Item< RawShape >::begin () const inline
Iterator tho the first contour vertex in the polygon.
    {
        return sl::cbegin(sh_);
    }
References libnest2d::shapelike::cbegin(), and libnest2d::_Item< RawShape >::sh_.
Referenced by libnest2d::placers::_BottomLeftPlacer< RawShape >::availableSpace().
binId() [1/2]
template<class RawShape > int libnest2d::_Item< RawShape >::binId () const inline noexcept
{ return binid_; }
References libnest2d::_Item< RawShape >::binid_.
binId() [2/2]
template<class RawShape > void libnest2d::_Item< RawShape >::binId (int idx) inline
{ binid_ = idx; }
References libnest2d::_Item< RawShape >::binid_.
Referenced by Slic3r::arrangement::AutoArranger< TBin >::preload(), and libnest2d::selections::SelectionBoilerplate< RawShape >::remove_unpackable_items().
boundingBox()
template<class RawShape > Box libnest2d::_Item< RawShape >::boundingBox () const inline
{
        if(!bb_cache_.valid) {
            if(!has_rotation_)
                bb_cache_.bb = sl::boundingBox(infaltedShape());
            else {
                // TODO make sure this works
                auto rotsh = infaltedShape();
                sl::rotate(rotsh, rotation_);
                bb_cache_.bb = sl::boundingBox(rotsh);
            }
            bb_cache_.valid = true;
        }
        auto &bb = bb_cache_.bb; auto &tr = translation_;
        return {bb.minCorner() + tr, bb.maxCorner() + tr };
    }
References libnest2d::_Item< RawShape >::BBCache::bb, libnest2d::_Item< RawShape >::bb_cache_, libnest2d::shapelike::boundingBox(), libnest2d::_Item< RawShape >::has_rotation_, libnest2d::_Item< RawShape >::infaltedShape(), libnest2d::shapelike::rotate(), libnest2d::_Item< RawShape >::rotation_, libnest2d::_Item< RawShape >::translation_, and libnest2d::_Item< RawShape >::BBCache::valid.
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::finalAlign(), libnest2d::findBestRotation(), Slic3r::arrangement::AutoArranger< TBin >::objfunc(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::placeOutsideOfBin(), libnest2d::placers::_BottomLeftPlacer< RawShape >::setInitialPosition(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::setInitialPosition(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::trypack().
cbegin()
template<class RawShape > Iterator libnest2d::_Item< RawShape >::cbegin () const inline
Alias to begin()
    {
        return sl::cbegin(sh_);
    }
References libnest2d::shapelike::cbegin(), and libnest2d::_Item< RawShape >::sh_.
cend()
template<class RawShape > Iterator libnest2d::_Item< RawShape >::cend () const inline
Alias to end()
    {
        return sl::cend(sh_);
    }
References libnest2d::shapelike::cend(), and libnest2d::_Item< RawShape >::sh_.
end()
template<class RawShape > Iterator libnest2d::_Item< RawShape >::end () const inline
Iterator to the last contour vertex.
    {
        return sl::cend(sh_);
    }
References libnest2d::shapelike::cend(), and libnest2d::_Item< RawShape >::sh_.
Referenced by libnest2d::placers::_BottomLeftPlacer< RawShape >::availableSpace().
holeCount()
template<class RawShape > size_t libnest2d::_Item< RawShape >::holeCount () const inline
{
        return sl::holeCount(sh_);
    }
References libnest2d::shapelike::holeCount(), and libnest2d::_Item< RawShape >::sh_.
infaltedShape()
template<class RawShape > const RawShape & libnest2d::_Item< RawShape >::infaltedShape () const inline private
{
        if(has_inflation_ ) {
            if(inflate_cache_valid_) return inflate_cache_;
            inflate_cache_ = sh_;
            sl::offset(inflate_cache_, inflation_);
            inflate_cache_valid_ = true;
            return inflate_cache_;
        }
        return sh_;
    }
References libnest2d::_Item< RawShape >::has_inflation_, libnest2d::_Item< RawShape >::inflate_cache_, libnest2d::_Item< RawShape >::inflate_cache_valid_, libnest2d::_Item< RawShape >::inflation_, libnest2d::shapelike::offset(), and libnest2d::_Item< RawShape >::sh_.
Referenced by libnest2d::_Item< RawShape >::area(), libnest2d::_Item< RawShape >::boundingBox(), and libnest2d::_Item< RawShape >::transformedShape().
inflate()
template<class RawShape > void libnest2d::_Item< RawShape >::inflate (Coord distance) inline
    {
        inflation(inflation() + distance);
    }
References libnest2d::_Item< RawShape >::inflation().
Referenced by Slic3r::arrangement::process_arrangeable().
inflation() [1/2]
template<class RawShape > Coord libnest2d::_Item< RawShape >::inflation () const inline
{
        return inflation_;
    }
References libnest2d::_Item< RawShape >::inflation_.
Referenced by libnest2d::_Item< RawShape >::inflate().
inflation() [2/2]
template<class RawShape > void libnest2d::_Item< RawShape >::inflation (Coord distance) inline
    {
        inflation_ = distance;
        has_inflation_ = true;
        invalidateCache();
    }
References libnest2d::_Item< RawShape >::has_inflation_, libnest2d::_Item< RawShape >::inflation_, and libnest2d::_Item< RawShape >::invalidateCache().
intersects()
template<class RawShape > static bool libnest2d::_Item< RawShape >::intersects (const _Item< RawShape > & sh1, const _Item< RawShape > & sh2) inline static
    {
        return sl::intersects(sh1.transformedShape(),
                                     sh2.transformedShape());
    }
References libnest2d::shapelike::intersects(), and libnest2d::_Item< RawShape >::transformedShape().
invalidateCache()
template<class RawShape > void libnest2d::_Item< RawShape >::invalidateCache () const inline private
    {
        tr_cache_valid_ = false;
        lmb_valid_ = false; rmt_valid_ = false;
        area_cache_valid_ = false;
        inflate_cache_valid_ = false;
        bb_cache_.valid = false;
        convexity_ = Convexity::UNCHECKED;
    }
References libnest2d::_Item< RawShape >::area_cache_valid_, libnest2d::_Item< RawShape >::bb_cache_, libnest2d::_Item< RawShape >::convexity_, libnest2d::_Item< RawShape >::inflate_cache_valid_, libnest2d::_Item< RawShape >::lmb_valid_, libnest2d::_Item< RawShape >::rmt_valid_, libnest2d::_Item< RawShape >::tr_cache_valid_, libnest2d::_Item< RawShape >::UNCHECKED, and libnest2d::_Item< RawShape >::BBCache::valid.
Referenced by libnest2d::_Item< RawShape >::inflation(), libnest2d::_Item< RawShape >::resetTransformation(), libnest2d::_Item< RawShape >::setShape(), and libnest2d::_Item< RawShape >::setVertex().
isContourConvex()
template<class RawShape > bool libnest2d::_Item< RawShape >::isContourConvex () const inline
{
        bool ret = false;
        switch(convexity_) {
        case Convexity::UNCHECKED:
            ret = sl::isConvex(sl::contour(transformedShape()));
            convexity_ = ret? Convexity::C_TRUE : Convexity::C_FALSE;
            break;
        case Convexity::C_TRUE: ret = true; break;
        case Convexity::C_FALSE:;
        }
        return ret;
    }
References libnest2d::_Item< RawShape >::C_FALSE, libnest2d::_Item< RawShape >::C_TRUE, libnest2d::shapelike::contour(), libnest2d::_Item< RawShape >::convexity_, libnest2d::shapelike::isConvex(), libnest2d::_Item< RawShape >::transformedShape(), and libnest2d::_Item< RawShape >::UNCHECKED.
isFixed()
template<class RawShape > bool libnest2d::_Item< RawShape >::isFixed () const inline noexcept
{ return fixed_; }
References libnest2d::_Item< RawShape >::fixed_.
Referenced by libnest2d::selections::_FirstFitSelection< RawShape >::packItems().
isHoleConvex()
template<class RawShape > bool libnest2d::_Item< RawShape >::isHoleConvex (unsigned) const inline
{
        return false;
    }
isInside() [1/5]
template<class RawShape > bool libnest2d::_Item< RawShape >::isInside (const _Box< TPoint< RawShape > > & box) const inline
{
    return sl::isInside(boundingBox(), box);
}
References libnest2d::shapelike::isInside().
isInside() [2/5]
template<class RawShape > bool libnest2d::_Item< RawShape >::isInside (const _Circle< TPoint< RawShape > > & box) const inline
{
    return sl::isInside(transformedShape(), circ);
}
References libnest2d::shapelike::isInside().
isInside() [3/5]
template<class RawShape > bool libnest2d::_Item< RawShape >::isInside (const _Item< RawShape > & sh) const inline
    {
        return sl::isInside(transformedShape(), sh.transformedShape());
    }
References libnest2d::shapelike::isInside(), and libnest2d::_Item< RawShape >::transformedShape().
isInside() [4/5]
template<class RawShape > bool libnest2d::_Item< RawShape >::isInside (const RawShape & sh) const inline
    {
        return sl::isInside(transformedShape(), sh);
    }
References libnest2d::shapelike::isInside(), and libnest2d::_Item< RawShape >::transformedShape().
isInside() [5/5]
template<class RawShape > bool libnest2d::_Item< RawShape >::isInside (const Vertex & p) const inline
isPointInside
Parameters
p
Returns
    {
        return sl::isInside(p, transformedShape());
    }
References libnest2d::shapelike::isInside(), and libnest2d::_Item< RawShape >::transformedShape().
leftmostBottomVertex()
template<class RawShape > Vertex libnest2d::_Item< RawShape >::leftmostBottomVertex () const inline
{
        if(!lmb_valid_ || !tr_cache_valid_) {  // find min x and min y vertex
            auto& tsh = transformedShape();
            lmb_ = std::min_element(sl::cbegin(tsh), sl::cend(tsh), vsort);
            lmb_valid_ = true;
        }
        return *lmb_;
    }
References libnest2d::shapelike::cbegin(), libnest2d::shapelike::cend(), libnest2d::_Item< RawShape >::lmb_, libnest2d::_Item< RawShape >::lmb_valid_, libnest2d::_Item< RawShape >::tr_cache_valid_, libnest2d::_Item< RawShape >::transformedShape(), and libnest2d::_Item< RawShape >::vsort().
Referenced by libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::calcnfp(), libnest2d::placers::correctNfpPosition(), and libnest2d::placers::correctNfpPosition().
markAsFixedInBin()
template<class RawShape > void libnest2d::_Item< RawShape >::markAsFixedInBin (int binid) inline
    {
        fixed_ = binid >= 0;
        binid_ = binid;
    }
References libnest2d::_Item< RawShape >::binid_, and libnest2d::_Item< RawShape >::fixed_.
Referenced by Slic3r::arrangement::AutoArranger< TBin >::preload().
onPacked()
template<class RawShape > void libnest2d::_Item< RawShape >::onPacked () inline
    {
        if (on_packed_)
            on_packed_(*this);
    }
References libnest2d::_Item< RawShape >::on_packed_.
operator RawShape()
template<class RawShape > libnest2d::_Item< RawShape >::operator RawShape () const inline
    {
        return transformedShape();
    }
References libnest2d::_Item< RawShape >::transformedShape().
orientation()
template<class RawShape > static BP2D_CONSTEXPR Orientation libnest2d::_Item< RawShape >::orientation () inline static
Get the orientation of the polygon.
The orientation have to be specified as a specialization of the OrientationType struct which has a Value constant.
Returns
The orientation type identifier for the _Item type.
{
        return OrientationType<TContour<RawShape>>::Value;
    }
priority() [1/2]
template<class RawShape > int libnest2d::_Item< RawShape >::priority () const inline noexcept
{ return priority_; }
References libnest2d::_Item< RawShape >::priority_.
priority() [2/2]
template<class RawShape > void libnest2d::_Item< RawShape >::priority (int p) inline
{ priority_ = p; }
References libnest2d::_Item< RawShape >::priority_.
Referenced by libnest2d::selections::_FirstFitSelection< RawShape >::packItems().
rawShape()
template<class RawShape > const RawShape & libnest2d::_Item< RawShape >::rawShape () const inline
    {
        return sh_;
    }
References libnest2d::_Item< RawShape >::sh_.
Referenced by libnest2d::placers::_BottomLeftPlacer< RawShape >::isInTheWayOf().
referenceVertex()
template<class RawShape > Vertex libnest2d::_Item< RawShape >::referenceVertex () const inline
{
        return rightmostTopVertex();
    }
References libnest2d::_Item< RawShape >::rightmostTopVertex().
Referenced by libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::calcnfp(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::trypack().
resetTransformation()
template<class RawShape > void libnest2d::_Item< RawShape >::resetTransformation () inline
    {
        has_translation_ = false; has_rotation_ = false; has_inflation_ = false;
        invalidateCache();
    }
References libnest2d::_Item< RawShape >::has_inflation_, libnest2d::_Item< RawShape >::has_rotation_, libnest2d::_Item< RawShape >::has_translation_, and libnest2d::_Item< RawShape >::invalidateCache().
rightmostTopVertex()
template<class RawShape > Vertex libnest2d::_Item< RawShape >::rightmostTopVertex () const inline
{
        if(!rmt_valid_ || !tr_cache_valid_) {  // find max x and max y vertex
            auto& tsh = transformedShape();
            rmt_ = std::max_element(sl::cbegin(tsh), sl::cend(tsh), vsort);
            rmt_valid_ = true;
        }
        return *rmt_;
    }
References libnest2d::shapelike::cbegin(), libnest2d::shapelike::cend(), libnest2d::_Item< RawShape >::rmt_, libnest2d::_Item< RawShape >::rmt_valid_, libnest2d::_Item< RawShape >::tr_cache_valid_, libnest2d::_Item< RawShape >::transformedShape(), and libnest2d::_Item< RawShape >::vsort().
Referenced by libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::calcnfp(), libnest2d::placers::correctNfpPosition(), libnest2d::placers::correctNfpPosition(), and libnest2d::_Item< RawShape >::referenceVertex().
rotate()
template<class RawShape > void libnest2d::_Item< RawShape >::rotate (const Radians & rads) inline
    {
        rotation(rotation() + rads);
    }
References libnest2d::_Item< RawShape >::rotation().
Referenced by libnest2d::placers::_BottomLeftPlacer< RawShape >::trypack().
rotation() [1/2]
template<class RawShape > Radians libnest2d::_Item< RawShape >::rotation () const inline
    {
        return rotation_;
    }
References libnest2d::_Item< RawShape >::rotation_.
Referenced by libnest2d::placers::PlacerBoilerplate< Subclass, RawShape, TBin, Cfg >::accept(), libnest2d::findBestRotation(), libnest2d::_Item< RawShape >::rotate(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::trypack().
rotation() [2/2]
template<class RawShape > void libnest2d::_Item< RawShape >::rotation (Radians rot) inline
    {
        if(rotation_ != rot) {
            rotation_ = rot; has_rotation_ = true; tr_cache_valid_ = false;
            rmt_valid_ = false; lmb_valid_ = false;
            bb_cache_.valid = false;
        }
    }
References libnest2d::_Item< RawShape >::bb_cache_, libnest2d::_Item< RawShape >::has_rotation_, libnest2d::_Item< RawShape >::lmb_valid_, libnest2d::_Item< RawShape >::rmt_valid_, libnest2d::_Item< RawShape >::rotation_, libnest2d::_Item< RawShape >::tr_cache_valid_, and libnest2d::_Item< RawShape >::BBCache::valid.
setOnPackedFn()
template<class RawShape > void libnest2d::_Item< RawShape >::setOnPackedFn (std::function< void(_Item< RawShape > &)> onpackedfn) inline
    {
        on_packed_ = onpackedfn;
    }
References libnest2d::_Item< RawShape >::on_packed_.
setShape()
template<class RawShape > void libnest2d::_Item< RawShape >::setShape (RawShape rsh) inline
    {
        sh_ = std::move(rsh);
        invalidateCache();
    }
References libnest2d::_Item< RawShape >::invalidateCache(), and libnest2d::_Item< RawShape >::sh_.
setVertex()
template<class RawShape > void libnest2d::_Item< RawShape >::setVertex (unsigned long idx, const Vertex & v) inline
Modify a vertex.
Note that this method will invalidate every cached calculation result including polygon offset and transformations.
Parameters
idx The index of the requested vertex.
v The new vertex data.
    {
        invalidateCache();
        sl::vertex(sh_, idx) = v;
    }
References libnest2d::_Item< RawShape >::invalidateCache(), libnest2d::_Item< RawShape >::sh_, and libnest2d::shapelike::vertex().
toString()
template<class RawShape > std::string libnest2d::_Item< RawShape >::toString () const inline
Convert the polygon to string representation. The format depends on the implementation of the polygon.
Returns
    {
        return sl::toString(sh_);
    }
References libnest2d::_Item< RawShape >::sh_, and libnest2d::shapelike::toString().
touches()
template<class RawShape > static bool libnest2d::_Item< RawShape >::touches (const _Item< RawShape > & sh1, const _Item< RawShape > & sh2) inline static
    {
        return sl::touches(sh1.transformedShape(),
                                  sh2.transformedShape());
    }
References libnest2d::shapelike::touches(), and libnest2d::_Item< RawShape >::transformedShape().
transformedShape()
template<class RawShape > const RawShape & libnest2d::_Item< RawShape >::transformedShape () const inline
    {
        if(tr_cache_valid_) return tr_cache_;
        RawShape cpy = infaltedShape();
        if(has_rotation_) sl::rotate(cpy, rotation_);
        if(has_translation_) sl::translate(cpy, translation_);
        tr_cache_ = cpy; tr_cache_valid_ = true;
        rmt_valid_ = false; lmb_valid_ = false;
        return tr_cache_;
    }
References libnest2d::_Item< RawShape >::has_rotation_, libnest2d::_Item< RawShape >::has_translation_, libnest2d::_Item< RawShape >::infaltedShape(), libnest2d::_Item< RawShape >::lmb_valid_, libnest2d::_Item< RawShape >::rmt_valid_, libnest2d::shapelike::rotate(), libnest2d::_Item< RawShape >::rotation_, libnest2d::_Item< RawShape >::tr_cache_, libnest2d::_Item< RawShape >::tr_cache_valid_, libnest2d::shapelike::translate(), and libnest2d::_Item< RawShape >::translation_.
Referenced by libnest2d::placers::EdgeCache< RawShape >::EdgeCache(), libnest2d::placers::_BottomLeftPlacer< RawShape >::_trypack(), libnest2d::placers::_BottomLeftPlacer< RawShape >::availableSpace(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::calcnfp(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::finalAlign(), libnest2d::_Item< RawShape >::intersects(), libnest2d::_Item< RawShape >::isContourConvex(), libnest2d::_Item< RawShape >::isInside(), libnest2d::_Item< RawShape >::isInside(), libnest2d::_Item< RawShape >::isInside(), libnest2d::placers::_BottomLeftPlacer< RawShape >::isInTheWayOf(), libnest2d::_Item< RawShape >::leftmostBottomVertex(), libnest2d::_Item< RawShape >::operator RawShape(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), libnest2d::_Item< RawShape >::rightmostTopVertex(), libnest2d::_Item< RawShape >::touches(), libnest2d::placers::_BottomLeftPlacer< RawShape >::toWallPoly(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::trypack(), and libnest2d::svg::SVGWriter< RawShape >::writeItem().
translate()
template<class RawShape > void libnest2d::_Item< RawShape >::translate (const Vertex & d) inline
    {
        translation(translation() + d);
    }
References libnest2d::_Item< RawShape >::translation().
Referenced by libnest2d::placers::_BottomLeftPlacer< RawShape >::_trypack(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::finalAlign(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::finalAlign(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::placeOutsideOfBin(), libnest2d::placers::_BottomLeftPlacer< RawShape >::setInitialPosition(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::setInitialPosition().
translation() [1/2]
template<class RawShape > TPoint< RawShape > libnest2d::_Item< RawShape >::translation () const inline
    {
        return translation_;
    }
References libnest2d::_Item< RawShape >::translation_.
Referenced by libnest2d::placers::PlacerBoilerplate< Subclass, RawShape, TBin, Cfg >::accept(), libnest2d::_Item< RawShape >::translate(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::trypack().
translation() [2/2]
template<class RawShape > void libnest2d::_Item< RawShape >::translation (const TPoint< RawShape > & tr) inline
    {
        if(translation_ != tr) {
            translation_ = tr; has_translation_ = true; tr_cache_valid_ = false;
            //bb_cache_.valid = false;
        }
    }
References libnest2d::_Item< RawShape >::has_translation_, libnest2d::_Item< RawShape >::tr_cache_valid_, and libnest2d::_Item< RawShape >::translation_.
vertex()
template<class RawShape > Vertex libnest2d::_Item< RawShape >::vertex (unsigned long idx) const inline
Get a copy of an outer vertex within the carried shape.
Note that the vertex considered here is taken from the original shape that this item is constructed from. This means that no transformation is applied to the shape in this call.
Parameters
idx The index of the requested vertex.
Returns
A copy of the requested vertex.
    {
        return sl::vertex(sh_, idx);
    }
References libnest2d::_Item< RawShape >::sh_, and libnest2d::shapelike::vertex().
Referenced by libnest2d::placers::_BottomLeftPlacer< RawShape >::toWallPoly().
vertexCount()
template<class RawShape > size_t libnest2d::_Item< RawShape >::vertexCount () const inline
The number of the outer ring vertices.
{
        return sl::contourVertexCount(sh_);
    }
References libnest2d::shapelike::contourVertexCount(), and libnest2d::_Item< RawShape >::sh_.
vsort()
template<class RawShape > static bool libnest2d::_Item< RawShape >::vsort (const Vertex & v1, const Vertex & v2) inline static private
    {
        TCompute<Vertex> x1 = getX(v1), x2 = getX(v2);
        TCompute<Vertex> y1 = getY(v1), y2 = getY(v2);
        return y1 == y2 ? x1 < x2 : y1 < y2;
    }
References libnest2d::getX(), and libnest2d::getY().
Referenced by libnest2d::_Item< RawShape >::leftmostBottomVertex(), and libnest2d::_Item< RawShape >::rightmostTopVertex().
Member Data Documentation
area_cache_
template<class RawShape > double libnest2d::_Item< RawShape >::area_cache_ = 0 mutable private
Referenced by libnest2d::_Item< RawShape >::area().
area_cache_valid_
template<class RawShape > bool libnest2d::_Item< RawShape >::area_cache_valid_ = false mutable private
Referenced by libnest2d::_Item< RawShape >::area(), and libnest2d::_Item< RawShape >::invalidateCache().
bb_cache_
template<class RawShape > struct libnest2d::_Item::BBCache libnest2d::_Item< RawShape >::bb_cache_ private
Referenced by libnest2d::_Item< RawShape >::boundingBox(), libnest2d::_Item< RawShape >::invalidateCache(), and libnest2d::_Item< RawShape >::rotation().
binid_
template<class RawShape > int libnest2d::_Item< RawShape >::binid_ {BIN_ID_UNSET} private
Referenced by libnest2d::_Item< RawShape >::binId(), libnest2d::_Item< RawShape >::binId(), and libnest2d::_Item< RawShape >::markAsFixedInBin().
convexity_
template<class RawShape > Convexity libnest2d::_Item< RawShape >::convexity_ = Convexity::UNCHECKED mutable private
Referenced by libnest2d::_Item< RawShape >::invalidateCache(), and libnest2d::_Item< RawShape >::isContourConvex().
fixed_
template<class RawShape > bool libnest2d::_Item< RawShape >::fixed_ {false} private
Referenced by libnest2d::_Item< RawShape >::isFixed(), and libnest2d::_Item< RawShape >::markAsFixedInBin().
has_inflation_
template<class RawShape > bool libnest2d::_Item< RawShape >::has_inflation_ = false private
Referenced by libnest2d::_Item< RawShape >::infaltedShape(), libnest2d::_Item< RawShape >::inflation(), and libnest2d::_Item< RawShape >::resetTransformation().
has_rotation_
template<class RawShape > bool libnest2d::_Item< RawShape >::has_rotation_ = false private
Referenced by libnest2d::_Item< RawShape >::boundingBox(), libnest2d::_Item< RawShape >::resetTransformation(), libnest2d::_Item< RawShape >::rotation(), and libnest2d::_Item< RawShape >::transformedShape().
has_translation_
template<class RawShape > bool libnest2d::_Item< RawShape >::has_translation_ = false private
Referenced by libnest2d::_Item< RawShape >::resetTransformation(), libnest2d::_Item< RawShape >::transformedShape(), and libnest2d::_Item< RawShape >::translation().
inflate_cache_
template<class RawShape > RawShape libnest2d::_Item< RawShape >::inflate_cache_ mutable private
Referenced by libnest2d::_Item< RawShape >::infaltedShape().
inflate_cache_valid_
template<class RawShape > bool libnest2d::_Item< RawShape >::inflate_cache_valid_ = false mutable private
Referenced by libnest2d::_Item< RawShape >::infaltedShape(), and libnest2d::_Item< RawShape >::invalidateCache().
inflation_
template<class RawShape > Coord libnest2d::_Item< RawShape >::inflation_ {0} private
Referenced by libnest2d::_Item< RawShape >::infaltedShape(), libnest2d::_Item< RawShape >::inflation(), and libnest2d::_Item< RawShape >::inflation().
lmb_
template<class RawShape > VertexConstIterator libnest2d::_Item< RawShape >::lmb_ mutable private
Referenced by libnest2d::_Item< RawShape >::leftmostBottomVertex().
lmb_valid_
template<class RawShape > bool libnest2d::_Item< RawShape >::lmb_valid_ = false private
Referenced by libnest2d::_Item< RawShape >::invalidateCache(), libnest2d::_Item< RawShape >::leftmostBottomVertex(), libnest2d::_Item< RawShape >::rotation(), and libnest2d::_Item< RawShape >::transformedShape().
on_packed_
template<class RawShape > std::function<void(_Item&)> libnest2d::_Item< RawShape >::on_packed_ private
Referenced by libnest2d::_Item< RawShape >::onPacked(), and libnest2d::_Item< RawShape >::setOnPackedFn().
priority_
template<class RawShape > int libnest2d::_Item< RawShape >::priority_ {0} private
Referenced by libnest2d::_Item< RawShape >::priority(), and libnest2d::_Item< RawShape >::priority().
rmt_
template<class RawShape > VertexConstIterator libnest2d::_Item< RawShape >::rmt_ mutable private
Referenced by libnest2d::_Item< RawShape >::rightmostTopVertex().
rmt_valid_
template<class RawShape > bool libnest2d::_Item< RawShape >::rmt_valid_ = false mutable private
Referenced by libnest2d::_Item< RawShape >::invalidateCache(), libnest2d::_Item< RawShape >::rightmostTopVertex(), libnest2d::_Item< RawShape >::rotation(), and libnest2d::_Item< RawShape >::transformedShape().
rotation_
template<class RawShape > Radians libnest2d::_Item< RawShape >::rotation_ {0.0} private
Referenced by libnest2d::_Item< RawShape >::boundingBox(), libnest2d::_Item< RawShape >::rotation(), libnest2d::_Item< RawShape >::rotation(), and libnest2d::_Item< RawShape >::transformedShape().
sh_
template<class RawShape > RawShape libnest2d::_Item< RawShape >::sh_ private
Referenced by libnest2d::_Item< RawShape >::begin(), libnest2d::_Item< RawShape >::cbegin(), libnest2d::_Item< RawShape >::cend(), libnest2d::_Item< RawShape >::end(), libnest2d::_Item< RawShape >::holeCount(), libnest2d::_Item< RawShape >::infaltedShape(), libnest2d::_Item< RawShape >::rawShape(), libnest2d::_Item< RawShape >::setShape(), libnest2d::_Item< RawShape >::setVertex(), libnest2d::_Item< RawShape >::toString(), libnest2d::_Item< RawShape >::vertex(), and libnest2d::_Item< RawShape >::vertexCount().
tr_cache_
template<class RawShape > RawShape libnest2d::_Item< RawShape >::tr_cache_ mutable private
Referenced by libnest2d::_Item< RawShape >::transformedShape().
tr_cache_valid_
template<class RawShape > bool libnest2d::_Item< RawShape >::tr_cache_valid_ = false mutable private
Referenced by libnest2d::_Item< RawShape >::invalidateCache(), libnest2d::_Item< RawShape >::leftmostBottomVertex(), libnest2d::_Item< RawShape >::rightmostTopVertex(), libnest2d::_Item< RawShape >::rotation(), libnest2d::_Item< RawShape >::transformedShape(), and libnest2d::_Item< RawShape >::translation().
translation_
template<class RawShape > Vertex libnest2d::_Item< RawShape >::translation_ {0, 0} private
Referenced by libnest2d::_Item< RawShape >::boundingBox(), libnest2d::_Item< RawShape >::transformedShape(), libnest2d::_Item< RawShape >::translation(), and libnest2d::_Item< RawShape >::translation().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/nester.hpp