Prusa Slicer: src/imgui/imstb_truetype.h File Reference
imstb_truetype.h File Reference
Classes
struct stbtt__buf
struct stbtt_bakedchar
struct stbtt_aligned_quad
struct stbtt_packedchar
struct stbtt_pack_range
struct stbtt_pack_context
struct stbtt_fontinfo
struct stbtt_vertex
struct stbtt__bitmap
Macros
#define __STB_INCLUDE_STB_TRUETYPE_H__
#define STBTT_DEF extern
#define STBTT_POINT_SIZE(x) (-(x))
#define stbtt_vertex_type short
#define STBTT_MACSTYLE_DONTCARE 0
#define STBTT_MACSTYLE_BOLD 1
#define STBTT_MACSTYLE_ITALIC 2
#define STBTT_MACSTYLE_UNDERSCORE 4
#define STBTT_MACSTYLE_NONE 8
Typedefs
typedef struct stbtt_pack_context stbtt_pack_context
typedef struct stbtt_fontinfo stbtt_fontinfo
typedef struct stbrp_rect stbrp_rect
Enumerations
enum { STBTT_vmove =1 , STBTT_vline , STBTT_vcurve , STBTT_vcubic }
enum { STBTT_PLATFORM_ID_UNICODE =0 , STBTT_PLATFORM_ID_MAC =1 , STBTT_PLATFORM_ID_ISO =2 , STBTT_PLATFORM_ID_MICROSOFT =3 }
enum {
STBTT_UNICODE_EID_UNICODE_1_0 =0 , STBTT_UNICODE_EID_UNICODE_1_1 =1 , STBTT_UNICODE_EID_ISO_10646 =2 , STBTT_UNICODE_EID_UNICODE_2_0_BMP =3 ,
STBTT_UNICODE_EID_UNICODE_2_0_FULL =4
}
enum { STBTT_MS_EID_SYMBOL =0 , STBTT_MS_EID_UNICODE_BMP =1 , STBTT_MS_EID_SHIFTJIS =2 , STBTT_MS_EID_UNICODE_FULL =10 }
enum {
STBTT_MAC_EID_ROMAN =0 , STBTT_MAC_EID_ARABIC =4 , STBTT_MAC_EID_JAPANESE =1 , STBTT_MAC_EID_HEBREW =5 ,
STBTT_MAC_EID_CHINESE_TRAD =2 , STBTT_MAC_EID_GREEK =6 , STBTT_MAC_EID_KOREAN =3 , STBTT_MAC_EID_RUSSIAN =7
}
enum {
STBTT_MS_LANG_ENGLISH =0x0409 , STBTT_MS_LANG_ITALIAN =0x0410 , STBTT_MS_LANG_CHINESE =0x0804 , STBTT_MS_LANG_JAPANESE =0x0411 ,
STBTT_MS_LANG_DUTCH =0x0413 , STBTT_MS_LANG_KOREAN =0x0412 , STBTT_MS_LANG_FRENCH =0x040c , STBTT_MS_LANG_RUSSIAN =0x0419 ,
STBTT_MS_LANG_GERMAN =0x0407 , STBTT_MS_LANG_SPANISH =0x0409 , STBTT_MS_LANG_HEBREW =0x040d , STBTT_MS_LANG_SWEDISH =0x041D
}
enum {
STBTT_MAC_LANG_ENGLISH =0 , STBTT_MAC_LANG_JAPANESE =11 , STBTT_MAC_LANG_ARABIC =12 , STBTT_MAC_LANG_KOREAN =23 ,
STBTT_MAC_LANG_DUTCH =4 , STBTT_MAC_LANG_RUSSIAN =32 , STBTT_MAC_LANG_FRENCH =1 , STBTT_MAC_LANG_SPANISH =6 ,
STBTT_MAC_LANG_GERMAN =2 , STBTT_MAC_LANG_SWEDISH =5 , STBTT_MAC_LANG_HEBREW =10 , STBTT_MAC_LANG_CHINESE_SIMPLIFIED =33 ,
STBTT_MAC_LANG_ITALIAN =3 , STBTT_MAC_LANG_CHINESE_TRAD =19
}
Functions
STBTT_DEF int stbtt_BakeFontBitmap (const unsigned char *data, int offset, float pixel_height, unsigned char *pixels, int pw, int ph, int first_char, int num_chars, stbtt_bakedchar *chardata)
STBTT_DEF void stbtt_GetBakedQuad (const stbtt_bakedchar *chardata, int pw, int ph, int char_index, float *xpos, float *ypos, stbtt_aligned_quad *q, int opengl_fillrule)
STBTT_DEF void stbtt_GetScaledFontVMetrics (const unsigned char *fontdata, int index, float size, float *ascent, float *descent, float *lineGap)
STBTT_DEF int stbtt_PackBegin (stbtt_pack_context *spc, unsigned char *pixels, int width, int height, int stride_in_bytes, int padding, void *alloc_context)
STBTT_DEF void stbtt_PackEnd (stbtt_pack_context *spc)
STBTT_DEF int stbtt_PackFontRange (stbtt_pack_context *spc, const unsigned char *fontdata, int font_index, float font_size, int first_unicode_char_in_range, int num_chars_in_range, stbtt_packedchar *chardata_for_range)
STBTT_DEF int stbtt_PackFontRanges (stbtt_pack_context *spc, const unsigned char *fontdata, int font_index, stbtt_pack_range *ranges, int num_ranges)
STBTT_DEF void stbtt_PackSetOversampling (stbtt_pack_context *spc, unsigned int h_oversample, unsigned int v_oversample)
STBTT_DEF void stbtt_PackSetSkipMissingCodepoints (stbtt_pack_context *spc, int skip)
STBTT_DEF void stbtt_GetPackedQuad (const stbtt_packedchar *chardata, int pw, int ph, int char_index, float *xpos, float *ypos, stbtt_aligned_quad *q, int align_to_integer)
STBTT_DEF int stbtt_PackFontRangesGatherRects (stbtt_pack_context *spc, const stbtt_fontinfo *info, stbtt_pack_range *ranges, int num_ranges, stbrp_rect *rects)
STBTT_DEF void stbtt_PackFontRangesPackRects (stbtt_pack_context *spc, stbrp_rect *rects, int num_rects)
STBTT_DEF int stbtt_PackFontRangesRenderIntoRects (stbtt_pack_context *spc, const stbtt_fontinfo *info, stbtt_pack_range *ranges, int num_ranges, stbrp_rect *rects)
STBTT_DEF int stbtt_GetNumberOfFonts (const unsigned char *data)
STBTT_DEF int stbtt_GetFontOffsetForIndex (const unsigned char *data, int index)
STBTT_DEF int stbtt_InitFont (stbtt_fontinfo *info, const unsigned char *data, int offset)
STBTT_DEF int stbtt_FindGlyphIndex (const stbtt_fontinfo *info, int unicode_codepoint)
STBTT_DEF float stbtt_ScaleForPixelHeight (const stbtt_fontinfo *info, float pixels)
STBTT_DEF float stbtt_ScaleForMappingEmToPixels (const stbtt_fontinfo *info, float pixels)
STBTT_DEF void stbtt_GetFontVMetrics (const stbtt_fontinfo *info, int *ascent, int *descent, int *lineGap)
STBTT_DEF int stbtt_GetFontVMetricsOS2 (const stbtt_fontinfo *info, int *typoAscent, int *typoDescent, int *typoLineGap)
STBTT_DEF void stbtt_GetFontBoundingBox (const stbtt_fontinfo *info, int *x0, int *y0, int *x1, int *y1)
STBTT_DEF void stbtt_GetCodepointHMetrics (const stbtt_fontinfo *info, int codepoint, int *advanceWidth, int *leftSideBearing)
STBTT_DEF int stbtt_GetCodepointKernAdvance (const stbtt_fontinfo *info, int ch1, int ch2)
STBTT_DEF int stbtt_GetCodepointBox (const stbtt_fontinfo *info, int codepoint, int *x0, int *y0, int *x1, int *y1)
STBTT_DEF void stbtt_GetGlyphHMetrics (const stbtt_fontinfo *info, int glyph_index, int *advanceWidth, int *leftSideBearing)
STBTT_DEF int stbtt_GetGlyphKernAdvance (const stbtt_fontinfo *info, int glyph1, int glyph2)
STBTT_DEF int stbtt_GetGlyphBox (const stbtt_fontinfo *info, int glyph_index, int *x0, int *y0, int *x1, int *y1)
STBTT_DEF int stbtt_IsGlyphEmpty (const stbtt_fontinfo *info, int glyph_index)
STBTT_DEF int stbtt_GetCodepointShape (const stbtt_fontinfo *info, int unicode_codepoint, stbtt_vertex **vertices)
STBTT_DEF int stbtt_GetGlyphShape (const stbtt_fontinfo *info, int glyph_index, stbtt_vertex **vertices)
STBTT_DEF void stbtt_FreeShape (const stbtt_fontinfo *info, stbtt_vertex *vertices)
STBTT_DEF void stbtt_FreeBitmap (unsigned char *bitmap, void *userdata)
STBTT_DEF unsigned char * stbtt_GetCodepointBitmap (const stbtt_fontinfo *info, float scale_x, float scale_y, int codepoint, int *width, int *height, int *xoff, int *yoff)
STBTT_DEF unsigned char * stbtt_GetCodepointBitmapSubpixel (const stbtt_fontinfo *info, float scale_x, float scale_y, float shift_x, float shift_y, int codepoint, int *width, int *height, int *xoff, int *yoff)
STBTT_DEF void stbtt_MakeCodepointBitmap (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, int codepoint)
STBTT_DEF void stbtt_MakeCodepointBitmapSubpixel (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int codepoint)
STBTT_DEF void stbtt_MakeCodepointBitmapSubpixelPrefilter (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int oversample_x, int oversample_y, float *sub_x, float *sub_y, int codepoint)
STBTT_DEF void stbtt_GetCodepointBitmapBox (const stbtt_fontinfo *font, int codepoint, float scale_x, float scale_y, int *ix0, int *iy0, int *ix1, int *iy1)
STBTT_DEF void stbtt_GetCodepointBitmapBoxSubpixel (const stbtt_fontinfo *font, int codepoint, float scale_x, float scale_y, float shift_x, float shift_y, int *ix0, int *iy0, int *ix1, int *iy1)
STBTT_DEF unsigned char * stbtt_GetGlyphBitmap (const stbtt_fontinfo *info, float scale_x, float scale_y, int glyph, int *width, int *height, int *xoff, int *yoff)
STBTT_DEF unsigned char * stbtt_GetGlyphBitmapSubpixel (const stbtt_fontinfo *info, float scale_x, float scale_y, float shift_x, float shift_y, int glyph, int *width, int *height, int *xoff, int *yoff)
STBTT_DEF void stbtt_MakeGlyphBitmap (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, int glyph)
STBTT_DEF void stbtt_MakeGlyphBitmapSubpixel (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int glyph)
STBTT_DEF void stbtt_MakeGlyphBitmapSubpixelPrefilter (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int oversample_x, int oversample_y, float *sub_x, float *sub_y, int glyph)
STBTT_DEF void stbtt_GetGlyphBitmapBox (const stbtt_fontinfo *font, int glyph, float scale_x, float scale_y, int *ix0, int *iy0, int *ix1, int *iy1)
STBTT_DEF void stbtt_GetGlyphBitmapBoxSubpixel (const stbtt_fontinfo *font, int glyph, float scale_x, float scale_y, float shift_x, float shift_y, int *ix0, int *iy0, int *ix1, int *iy1)
STBTT_DEF void stbtt_Rasterize (stbtt__bitmap *result, float flatness_in_pixels, stbtt_vertex *vertices, int num_verts, float scale_x, float scale_y, float shift_x, float shift_y, int x_off, int y_off, int invert, void *userdata)
STBTT_DEF void stbtt_FreeSDF (unsigned char *bitmap, void *userdata)
STBTT_DEF unsigned char * stbtt_GetGlyphSDF (const stbtt_fontinfo *info, float scale, int glyph, int padding, unsigned char onedge_value, float pixel_dist_scale, int *width, int *height, int *xoff, int *yoff)
STBTT_DEF unsigned char * stbtt_GetCodepointSDF (const stbtt_fontinfo *info, float scale, int codepoint, int padding, unsigned char onedge_value, float pixel_dist_scale, int *width, int *height, int *xoff, int *yoff)
STBTT_DEF int stbtt_FindMatchingFont (const unsigned char *fontdata, const char *name, int flags)
STBTT_DEF int stbtt_CompareUTF8toUTF16_bigendian (const char *s1, int len1, const char *s2, int len2)
STBTT_DEF const char * stbtt_GetFontNameString (const stbtt_fontinfo *font, int *length, int platformID, int encodingID, int languageID, int nameID)
Class Documentation
stbtt__buf
struct stbtt__buf
Class Members
int cursor
unsigned char * data
int size
stbtt_bakedchar
struct stbtt_bakedchar
Class Members
unsigned short x0
unsigned short x1
float xadvance
float xoff
unsigned short y0
unsigned short y1
float yoff
stbtt_aligned_quad
struct stbtt_aligned_quad
Class Members
float s0
float s1
float t0
float t1
float x0
float x1
float y0
float y1
stbtt_packedchar
struct stbtt_packedchar
Class Members
unsigned short x0
unsigned short x1
float xadvance
float xoff
float xoff2
unsigned short y0
unsigned short y1
float yoff
float yoff2
stbtt_pack_range
struct stbtt_pack_range
Class Members
int * array_of_unicode_codepoints
stbtt_packedchar * chardata_for_range
int first_unicode_codepoint_in_range
float font_size
unsigned char h_oversample
int num_chars
unsigned char v_oversample
stbtt_pack_context
struct stbtt_pack_context
Class Members
unsigned int h_oversample
int height
void * nodes
void * pack_info
int padding
unsigned char * pixels
int skip_missing
int stride_in_bytes
void * user_allocator_context
unsigned int v_oversample
int width
stbtt_fontinfo
struct stbtt_fontinfo
Class Members
stbtt__buf cff
stbtt__buf charstrings
unsigned char * data
stbtt__buf fdselect
stbtt__buf fontdicts
int fontstart
int glyf
int gpos
stbtt__buf gsubrs
int head
int hhea
int hmtx
int index_map
int indexToLocFormat
int kern
int loca
int numGlyphs
stbtt__buf subrs
void * userdata
stbtt_vertex
struct stbtt_vertex
Class Members
stbtt_vertex_type cx
stbtt_vertex_type cx1
stbtt_vertex_type cy
stbtt_vertex_type cy1
unsigned char padding
unsigned char type
stbtt_vertex_type x
stbtt_vertex_type y
stbtt__bitmap
struct stbtt__bitmap
Class Members
int h
unsigned char * pixels
int stride
int w
Macro Definition Documentation
__STB_INCLUDE_STB_TRUETYPE_H__
#define __STB_INCLUDE_STB_TRUETYPE_H__
STBTT_DEF
#define STBTT_DEF extern
STBTT_MACSTYLE_BOLD
#define STBTT_MACSTYLE_BOLD 1
STBTT_MACSTYLE_DONTCARE
#define STBTT_MACSTYLE_DONTCARE 0
STBTT_MACSTYLE_ITALIC
#define STBTT_MACSTYLE_ITALIC 2
STBTT_MACSTYLE_NONE
#define STBTT_MACSTYLE_NONE 8
STBTT_MACSTYLE_UNDERSCORE
#define STBTT_MACSTYLE_UNDERSCORE 4
STBTT_POINT_SIZE
#define STBTT_POINT_SIZE (x) (-(x))
stbtt_vertex_type
#define stbtt_vertex_type short
Typedef Documentation
stbrp_rect
typedef struct stbrp_rect stbrp_rect
stbtt_fontinfo
typedef struct stbtt_fontinfo stbtt_fontinfo
stbtt_pack_context
typedef struct stbtt_pack_context stbtt_pack_context
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STBTT_vmove
STBTT_vline
STBTT_vcurve
STBTT_vcubic
        {
      STBTT_vmove=1,
      STBTT_vline,
      STBTT_vcurve,
      STBTT_vcubic
   };
anonymous enum
anonymous enum
Enumerator
STBTT_PLATFORM_ID_UNICODE
STBTT_PLATFORM_ID_MAC
STBTT_PLATFORM_ID_ISO
STBTT_PLATFORM_ID_MICROSOFT
     { // platformID
   STBTT_PLATFORM_ID_UNICODE   =0,
   STBTT_PLATFORM_ID_MAC       =1,
   STBTT_PLATFORM_ID_ISO       =2,
   STBTT_PLATFORM_ID_MICROSOFT =3
};
anonymous enum
anonymous enum
Enumerator
STBTT_UNICODE_EID_UNICODE_1_0
STBTT_UNICODE_EID_UNICODE_1_1
STBTT_UNICODE_EID_ISO_10646
STBTT_UNICODE_EID_UNICODE_2_0_BMP
STBTT_UNICODE_EID_UNICODE_2_0_FULL
     { // encodingID for STBTT_PLATFORM_ID_UNICODE
   STBTT_UNICODE_EID_UNICODE_1_0    =0,
   STBTT_UNICODE_EID_UNICODE_1_1    =1,
   STBTT_UNICODE_EID_ISO_10646      =2,
   STBTT_UNICODE_EID_UNICODE_2_0_BMP=3,
   STBTT_UNICODE_EID_UNICODE_2_0_FULL=4
};
anonymous enum
anonymous enum
Enumerator
STBTT_MS_EID_SYMBOL
STBTT_MS_EID_UNICODE_BMP
STBTT_MS_EID_SHIFTJIS
STBTT_MS_EID_UNICODE_FULL
     { // encodingID for STBTT_PLATFORM_ID_MICROSOFT
   STBTT_MS_EID_SYMBOL        =0,
   STBTT_MS_EID_UNICODE_BMP   =1,
   STBTT_MS_EID_SHIFTJIS      =2,
   STBTT_MS_EID_UNICODE_FULL  =10
};
anonymous enum
anonymous enum
Enumerator
STBTT_MAC_EID_ROMAN
STBTT_MAC_EID_ARABIC
STBTT_MAC_EID_JAPANESE
STBTT_MAC_EID_HEBREW
STBTT_MAC_EID_CHINESE_TRAD
STBTT_MAC_EID_GREEK
STBTT_MAC_EID_KOREAN
STBTT_MAC_EID_RUSSIAN
     { // encodingID for STBTT_PLATFORM_ID_MAC; same as Script Manager codes
   STBTT_MAC_EID_ROMAN        =0,   STBTT_MAC_EID_ARABIC       =4,
   STBTT_MAC_EID_JAPANESE     =1,   STBTT_MAC_EID_HEBREW       =5,
   STBTT_MAC_EID_CHINESE_TRAD =2,   STBTT_MAC_EID_GREEK        =6,
   STBTT_MAC_EID_KOREAN       =3,   STBTT_MAC_EID_RUSSIAN      =7
};
anonymous enum
anonymous enum
Enumerator
STBTT_MS_LANG_ENGLISH
STBTT_MS_LANG_ITALIAN
STBTT_MS_LANG_CHINESE
STBTT_MS_LANG_JAPANESE
STBTT_MS_LANG_DUTCH
STBTT_MS_LANG_KOREAN
STBTT_MS_LANG_FRENCH
STBTT_MS_LANG_RUSSIAN
STBTT_MS_LANG_GERMAN
STBTT_MS_LANG_SPANISH
STBTT_MS_LANG_HEBREW
STBTT_MS_LANG_SWEDISH
     { // languageID for STBTT_PLATFORM_ID_MICROSOFT; same as LCID...
       // problematic because there are e.g. 16 english LCIDs and 16 arabic LCIDs
   STBTT_MS_LANG_ENGLISH     =0x0409,   STBTT_MS_LANG_ITALIAN     =0x0410,
   STBTT_MS_LANG_CHINESE     =0x0804,   STBTT_MS_LANG_JAPANESE    =0x0411,
   STBTT_MS_LANG_DUTCH       =0x0413,   STBTT_MS_LANG_KOREAN      =0x0412,
   STBTT_MS_LANG_FRENCH      =0x040c,   STBTT_MS_LANG_RUSSIAN     =0x0419,
   STBTT_MS_LANG_GERMAN      =0x0407,   STBTT_MS_LANG_SPANISH     =0x0409,
   STBTT_MS_LANG_HEBREW      =0x040d,   STBTT_MS_LANG_SWEDISH     =0x041D
};
anonymous enum
anonymous enum
Enumerator
STBTT_MAC_LANG_ENGLISH
STBTT_MAC_LANG_JAPANESE
STBTT_MAC_LANG_ARABIC
STBTT_MAC_LANG_KOREAN
STBTT_MAC_LANG_DUTCH
STBTT_MAC_LANG_RUSSIAN
STBTT_MAC_LANG_FRENCH
STBTT_MAC_LANG_SPANISH
STBTT_MAC_LANG_GERMAN
STBTT_MAC_LANG_SWEDISH
STBTT_MAC_LANG_HEBREW
STBTT_MAC_LANG_CHINESE_SIMPLIFIED
STBTT_MAC_LANG_ITALIAN
STBTT_MAC_LANG_CHINESE_TRAD
     { // languageID for STBTT_PLATFORM_ID_MAC
   STBTT_MAC_LANG_ENGLISH      =0 ,   STBTT_MAC_LANG_JAPANESE     =11,
   STBTT_MAC_LANG_ARABIC       =12,   STBTT_MAC_LANG_KOREAN       =23,
   STBTT_MAC_LANG_DUTCH        =4 ,   STBTT_MAC_LANG_RUSSIAN      =32,
   STBTT_MAC_LANG_FRENCH       =1 ,   STBTT_MAC_LANG_SPANISH      =6 ,
   STBTT_MAC_LANG_GERMAN       =2 ,   STBTT_MAC_LANG_SWEDISH      =5 ,
   STBTT_MAC_LANG_HEBREW       =10,   STBTT_MAC_LANG_CHINESE_SIMPLIFIED =33,
   STBTT_MAC_LANG_ITALIAN      =3 ,   STBTT_MAC_LANG_CHINESE_TRAD =19
};
Function Documentation
stbtt_BakeFontBitmap()
STBTT_DEF int stbtt_BakeFontBitmap (const unsigned char * data, int offset, float pixel_height, unsigned char * pixels, int pw, int ph, int first_char, int num_chars, stbtt_bakedchar * chardata)
stbtt_CompareUTF8toUTF16_bigendian()
STBTT_DEF int stbtt_CompareUTF8toUTF16_bigendian (const char * s1, int len1, const char * s2, int len2)
stbtt_FindGlyphIndex()
STBTT_DEF int stbtt_FindGlyphIndex (const stbtt_fontinfo * info, int unicode_codepoint)
Referenced by priv::get_glyph(), and ImFontAtlasBuildWithStbTruetype().
stbtt_FindMatchingFont()
STBTT_DEF int stbtt_FindMatchingFont (const unsigned char * fontdata, const char * name, int flags)
stbtt_FreeBitmap()
STBTT_DEF void stbtt_FreeBitmap (unsigned char * bitmap, void * userdata)
stbtt_FreeSDF()
STBTT_DEF void stbtt_FreeSDF (unsigned char * bitmap, void * userdata)
stbtt_FreeShape()
STBTT_DEF void stbtt_FreeShape (const stbtt_fontinfo * info, stbtt_vertex * vertices)
stbtt_GetBakedQuad()
STBTT_DEF void stbtt_GetBakedQuad (const stbtt_bakedchar * chardata, int pw, int ph, int char_index, float * xpos, float * ypos, stbtt_aligned_quad * q, int opengl_fillrule)
stbtt_GetCodepointBitmap()
STBTT_DEF unsigned char * stbtt_GetCodepointBitmap (const stbtt_fontinfo * info, float scale_x, float scale_y, int codepoint, int * width, int * height, int * xoff, int * yoff)
stbtt_GetCodepointBitmapBox()
STBTT_DEF void stbtt_GetCodepointBitmapBox (const stbtt_fontinfo * font, int codepoint, float scale_x, float scale_y, int * ix0, int * iy0, int * ix1, int * iy1)
stbtt_GetCodepointBitmapBoxSubpixel()
STBTT_DEF void stbtt_GetCodepointBitmapBoxSubpixel (const stbtt_fontinfo * font, int codepoint, float scale_x, float scale_y, float shift_x, float shift_y, int * ix0, int * iy0, int * ix1, int * iy1)
stbtt_GetCodepointBitmapSubpixel()
STBTT_DEF unsigned char * stbtt_GetCodepointBitmapSubpixel (const stbtt_fontinfo * info, float scale_x, float scale_y, float shift_x, float shift_y, int codepoint, int * width, int * height, int * xoff, int * yoff)
stbtt_GetCodepointBox()
STBTT_DEF int stbtt_GetCodepointBox (const stbtt_fontinfo * info, int codepoint, int * x0, int * y0, int * x1, int * y1)
stbtt_GetCodepointHMetrics()
STBTT_DEF void stbtt_GetCodepointHMetrics (const stbtt_fontinfo * info, int codepoint, int * advanceWidth, int * leftSideBearing)
stbtt_GetCodepointKernAdvance()
STBTT_DEF int stbtt_GetCodepointKernAdvance (const stbtt_fontinfo * info, int ch1, int ch2)
stbtt_GetCodepointSDF()
STBTT_DEF unsigned char * stbtt_GetCodepointSDF (const stbtt_fontinfo * info, float scale, int codepoint, int padding, unsigned char onedge_value, float pixel_dist_scale, int * width, int * height, int * xoff, int * yoff)
stbtt_GetCodepointShape()
STBTT_DEF int stbtt_GetCodepointShape (const stbtt_fontinfo * info, int unicode_codepoint, stbtt_vertex ** vertices)
stbtt_GetFontBoundingBox()
STBTT_DEF void stbtt_GetFontBoundingBox (const stbtt_fontinfo * info, int * x0, int * y0, int * x1, int * y1)
stbtt_GetFontNameString()
STBTT_DEF const char * stbtt_GetFontNameString (const stbtt_fontinfo * font, int * length, int platformID, int encodingID, int languageID, int nameID)
Referenced by Slic3r::Emboss::is_italic().
stbtt_GetFontOffsetForIndex()
STBTT_DEF int stbtt_GetFontOffsetForIndex (const unsigned char * data, int index)
Referenced by ImFontAtlasBuildWithStbTruetype(), and priv::load_font_info().
stbtt_GetFontVMetrics()
STBTT_DEF void stbtt_GetFontVMetrics (const stbtt_fontinfo * info, int * ascent, int * descent, int * lineGap)
Referenced by Slic3r::Emboss::create_font_file(), and ImFontAtlasBuildWithStbTruetype().
stbtt_GetFontVMetricsOS2()
STBTT_DEF int stbtt_GetFontVMetricsOS2 (const stbtt_fontinfo * info, int * typoAscent, int * typoDescent, int * typoLineGap)
stbtt_GetGlyphBitmap()
STBTT_DEF unsigned char * stbtt_GetGlyphBitmap (const stbtt_fontinfo * info, float scale_x, float scale_y, int glyph, int * width, int * height, int * xoff, int * yoff)
stbtt_GetGlyphBitmapBox()
STBTT_DEF void stbtt_GetGlyphBitmapBox (const stbtt_fontinfo * font, int glyph, float scale_x, float scale_y, int * ix0, int * iy0, int * ix1, int * iy1)
stbtt_GetGlyphBitmapBoxSubpixel()
STBTT_DEF void stbtt_GetGlyphBitmapBoxSubpixel (const stbtt_fontinfo * font, int glyph, float scale_x, float scale_y, float shift_x, float shift_y, int * ix0, int * iy0, int * ix1, int * iy1)
Referenced by ImFontAtlasBuildWithStbTruetype().
stbtt_GetGlyphBitmapSubpixel()
STBTT_DEF unsigned char * stbtt_GetGlyphBitmapSubpixel (const stbtt_fontinfo * info, float scale_x, float scale_y, float shift_x, float shift_y, int glyph, int * width, int * height, int * xoff, int * yoff)
stbtt_GetGlyphBox()
STBTT_DEF int stbtt_GetGlyphBox (const stbtt_fontinfo * info, int glyph_index, int * x0, int * y0, int * x1, int * y1)
stbtt_GetGlyphHMetrics()
STBTT_DEF void stbtt_GetGlyphHMetrics (const stbtt_fontinfo * info, int glyph_index, int * advanceWidth, int * leftSideBearing)
Referenced by priv::get_glyph().
stbtt_GetGlyphKernAdvance()
STBTT_DEF int stbtt_GetGlyphKernAdvance (const stbtt_fontinfo * info, int glyph1, int glyph2)
stbtt_GetGlyphSDF()
STBTT_DEF unsigned char * stbtt_GetGlyphSDF (const stbtt_fontinfo * info, float scale, int glyph, int padding, unsigned char onedge_value, float pixel_dist_scale, int * width, int * height, int * xoff, int * yoff)
stbtt_GetGlyphShape()
STBTT_DEF int stbtt_GetGlyphShape (const stbtt_fontinfo * info, int glyph_index, stbtt_vertex ** vertices)
Referenced by priv::get_glyph().
stbtt_GetNumberOfFonts()
STBTT_DEF int stbtt_GetNumberOfFonts (const unsigned char * data)
Referenced by Slic3r::Emboss::create_font_file().
stbtt_GetPackedQuad()
STBTT_DEF void stbtt_GetPackedQuad (const stbtt_packedchar * chardata, int pw, int ph, int char_index, float * xpos, float * ypos, stbtt_aligned_quad * q, int align_to_integer)
Referenced by ImFontAtlasBuildWithStbTruetype().
stbtt_GetScaledFontVMetrics()
STBTT_DEF void stbtt_GetScaledFontVMetrics (const unsigned char * fontdata, int index, float size, float * ascent, float * descent, float * lineGap)
stbtt_InitFont()
STBTT_DEF int stbtt_InitFont (stbtt_fontinfo * info, const unsigned char * data, int offset)
Referenced by ImFontAtlasBuildWithStbTruetype(), and priv::load_font_info().
stbtt_IsGlyphEmpty()
STBTT_DEF int stbtt_IsGlyphEmpty (const stbtt_fontinfo * info, int glyph_index)
stbtt_MakeCodepointBitmap()
STBTT_DEF void stbtt_MakeCodepointBitmap (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, int codepoint)
stbtt_MakeCodepointBitmapSubpixel()
STBTT_DEF void stbtt_MakeCodepointBitmapSubpixel (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int codepoint)
stbtt_MakeCodepointBitmapSubpixelPrefilter()
STBTT_DEF void stbtt_MakeCodepointBitmapSubpixelPrefilter (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int oversample_x, int oversample_y, float * sub_x, float * sub_y, int codepoint)
stbtt_MakeGlyphBitmap()
STBTT_DEF void stbtt_MakeGlyphBitmap (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, int glyph)
stbtt_MakeGlyphBitmapSubpixel()
STBTT_DEF void stbtt_MakeGlyphBitmapSubpixel (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int glyph)
stbtt_MakeGlyphBitmapSubpixelPrefilter()
STBTT_DEF void stbtt_MakeGlyphBitmapSubpixelPrefilter (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int oversample_x, int oversample_y, float * sub_x, float * sub_y, int glyph)
stbtt_PackBegin()
STBTT_DEF int stbtt_PackBegin (stbtt_pack_context * spc, unsigned char * pixels, int width, int height, int stride_in_bytes, int padding, void * alloc_context)
Referenced by ImFontAtlasBuildWithStbTruetype().
stbtt_PackEnd()
STBTT_DEF void stbtt_PackEnd (stbtt_pack_context * spc)
Referenced by ImFontAtlasBuildWithStbTruetype().
stbtt_PackFontRange()
STBTT_DEF int stbtt_PackFontRange (stbtt_pack_context * spc, const unsigned char * fontdata, int font_index, float font_size, int first_unicode_char_in_range, int num_chars_in_range, stbtt_packedchar * chardata_for_range)
stbtt_PackFontRanges()
STBTT_DEF int stbtt_PackFontRanges (stbtt_pack_context * spc, const unsigned char * fontdata, int font_index, stbtt_pack_range * ranges, int num_ranges)
stbtt_PackFontRangesGatherRects()
STBTT_DEF int stbtt_PackFontRangesGatherRects (stbtt_pack_context * spc, const stbtt_fontinfo * info, stbtt_pack_range * ranges, int num_ranges, stbrp_rect * rects)
stbtt_PackFontRangesPackRects()
STBTT_DEF void stbtt_PackFontRangesPackRects (stbtt_pack_context * spc, stbrp_rect * rects, int num_rects)
stbtt_PackFontRangesRenderIntoRects()
STBTT_DEF int stbtt_PackFontRangesRenderIntoRects (stbtt_pack_context * spc, const stbtt_fontinfo * info, stbtt_pack_range * ranges, int num_ranges, stbrp_rect * rects)
Referenced by ImFontAtlasBuildWithStbTruetype().
stbtt_PackSetOversampling()
STBTT_DEF void stbtt_PackSetOversampling (stbtt_pack_context * spc, unsigned int h_oversample, unsigned int v_oversample)
stbtt_PackSetSkipMissingCodepoints()
STBTT_DEF void stbtt_PackSetSkipMissingCodepoints (stbtt_pack_context * spc, int skip)
stbtt_Rasterize()
STBTT_DEF void stbtt_Rasterize (stbtt__bitmap * result, float flatness_in_pixels, stbtt_vertex * vertices, int num_verts, float scale_x, float scale_y, float shift_x, float shift_y, int x_off, int y_off, int invert, void * userdata)
stbtt_ScaleForMappingEmToPixels()
STBTT_DEF float stbtt_ScaleForMappingEmToPixels (const stbtt_fontinfo * info, float pixels)
Referenced by Slic3r::Emboss::create_font_file(), and ImFontAtlasBuildWithStbTruetype().
stbtt_ScaleForPixelHeight()
STBTT_DEF float stbtt_ScaleForPixelHeight (const stbtt_fontinfo * info, float pixels)
Referenced by ImFontAtlasBuildWithStbTruetype().