Prusa Slicer: Eigen::ComplexEigenSolver< _MatrixType > Class Template Reference
Eigen::ComplexEigenSolver< _MatrixType > Class Template Reference
Computes eigenvalues and eigenvectors of general complex matrices.
#include <src/eigen/Eigen/src/Eigenvalues/ComplexEigenSolver.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , Options = MatrixType::Options , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
Synonym for the template parameter _MatrixType.
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType.
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef std::complex< RealScalar > ComplexScalar
Complex scalar type for MatrixType.
typedef Matrix< ComplexScalar, ColsAtCompileTime, 1, Options &(~RowMajor), MaxColsAtCompileTime, 1 > EigenvalueType
Type for vector of eigenvalues as returned by eigenvalues().
typedef Matrix< ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime > EigenvectorType
Type for matrix of eigenvectors as returned by eigenvectors().
Public Member Functions
ComplexEigenSolver ()
Default constructor.
ComplexEigenSolver (Index size)
Default Constructor with memory preallocation.
template<typename InputType >
ComplexEigenSolver (const EigenBase< InputType > &matrix, bool computeEigenvectors=true)
Constructor; computes eigendecomposition of given matrix.
const EigenvectorType & eigenvectors () const
Returns the eigenvectors of given matrix.
const EigenvalueType & eigenvalues () const
Returns the eigenvalues of given matrix.
template<typename InputType >
ComplexEigenSolver & compute (const EigenBase< InputType > &matrix, bool computeEigenvectors=true)
Computes eigendecomposition of given matrix.
ComputationInfo info () const
Reports whether previous computation was successful.
ComplexEigenSolver & setMaxIterations (Index maxIters)
Sets the maximum number of iterations allowed.
Index getMaxIterations ()
Returns the maximum number of iterations.
template<typename InputType >
ComplexEigenSolver< MatrixType > & compute (const EigenBase< InputType > &matrix, bool computeEigenvectors)
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
EigenvectorType m_eivec
EigenvalueType m_eivalues
ComplexSchur< MatrixType > m_schur
bool m_isInitialized
bool m_eigenvectorsOk
EigenvectorType m_matX
Private Member Functions
void doComputeEigenvectors (RealScalar matrixnorm)
void sortEigenvalues (bool computeEigenvectors)
Detailed Description
template<typename _MatrixType>
class Eigen::ComplexEigenSolver< _MatrixType >
Computes eigenvalues and eigenvectors of general complex matrices.
\eigenvalues_module
Template Parameters
_MatrixType the type of the matrix of which we are computing the eigendecomposition; this is expected to be an instantiation of the Matrix class template.
The eigenvalues and eigenvectors of a matrix are scalars and vectors such that . If is a diagonal matrix with the eigenvalues on the diagonal, and is a matrix with the eigenvectors as its columns, then . The matrix is almost always invertible, in which case we have . This is called the eigendecomposition.
The main function in this class is compute(), which computes the eigenvalues and eigenvectors of a given function. The documentation for that function contains an example showing the main features of the class.
See also
class EigenSolver, class SelfAdjointEigenSolver
Member Typedef Documentation
ComplexScalar
template<typename _MatrixType > typedef std::complex<RealScalar> Eigen::ComplexEigenSolver< _MatrixType >::ComplexScalar
Complex scalar type for MatrixType.
This is std::complex<Scalar> if Scalar is real (e.g., float or double) and just Scalar if Scalar is complex.
EigenvalueType
template<typename _MatrixType > typedef Matrix<ComplexScalar, ColsAtCompileTime, 1, Options&(~RowMajor), MaxColsAtCompileTime, 1> Eigen::ComplexEigenSolver< _MatrixType >::EigenvalueType
Type for vector of eigenvalues as returned by eigenvalues().
This is a column vector with entries of type ComplexScalar. The length of the vector is the size of MatrixType.
EigenvectorType
template<typename _MatrixType > typedef Matrix<ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::ComplexEigenSolver< _MatrixType >::EigenvectorType
Type for matrix of eigenvectors as returned by eigenvectors().
This is a square matrix with entries of type ComplexScalar. The size is the same as the size of MatrixType.
Index
template<typename _MatrixType > typedef Eigen::Index Eigen::ComplexEigenSolver< _MatrixType >::Index
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::ComplexEigenSolver< _MatrixType >::MatrixType
Synonym for the template parameter _MatrixType.
RealScalar
template<typename _MatrixType > typedef NumTraits<Scalar>::Real Eigen::ComplexEigenSolver< _MatrixType >::RealScalar
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::ComplexEigenSolver< _MatrixType >::Scalar
Scalar type for matrices of type MatrixType.
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
         {
      RowsAtCompileTime = MatrixType::RowsAtCompileTime,
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      Options = MatrixType::Options,
      MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
ComplexEigenSolver() [1/3]
template<typename _MatrixType > Eigen::ComplexEigenSolver< _MatrixType >::ComplexEigenSolver () inline
Default constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via compute().
            : m_eivec(),
              m_eivalues(),
              m_schur(),
              m_isInitialized(false),
              m_eigenvectorsOk(false),
              m_matX()
    {}
ComplexEigenSolver() [2/3]
template<typename _MatrixType > Eigen::ComplexEigenSolver< _MatrixType >::ComplexEigenSolver (Index size) inline explicit
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
ComplexEigenSolver()
            : m_eivec(size, size),
              m_eivalues(size),
              m_schur(size),
              m_isInitialized(false),
              m_eigenvectorsOk(false),
              m_matX(size, size)
    {}
ComplexEigenSolver() [3/3]
template<typename _MatrixType > template<typename InputType > Eigen::ComplexEigenSolver< _MatrixType >::ComplexEigenSolver (const EigenBase< InputType > & matrix, bool computeEigenvectors = true) inline explicit
Constructor; computes eigendecomposition of given matrix.
Parameters
[in] matrix Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
This constructor calls compute() to compute the eigendecomposition.
            : m_eivec(matrix.rows(),matrix.cols()),
              m_eivalues(matrix.cols()),
              m_schur(matrix.rows()),
              m_isInitialized(false),
              m_eigenvectorsOk(false),
              m_matX(matrix.rows(),matrix.cols())
    {
      compute(matrix.derived(), computeEigenvectors);
    }
References Eigen::ComplexEigenSolver< _MatrixType >::compute(), and Eigen::EigenBase< Derived >::derived().
Member Function Documentation
check_template_parameters()
template<typename _MatrixType > static void Eigen::ComplexEigenSolver< _MatrixType >::check_template_parameters () inline static protected
    {
      EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
    }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
compute() [1/2]
template<typename _MatrixType > template<typename InputType > ComplexEigenSolver< MatrixType > & Eigen::ComplexEigenSolver< _MatrixType >::compute (const EigenBase< InputType > & matrix, bool computeEigenvectors)
{
  check_template_parameters();
  // this code is inspired from Jampack
  eigen_assert(matrix.cols() == matrix.rows());
  // Do a complex Schur decomposition, A = U T U^*
  // The eigenvalues are on the diagonal of T.
  m_schur.compute(matrix.derived(), computeEigenvectors);
  if(m_schur.info() == Success)
  {
    m_eivalues = m_schur.matrixT().diagonal();
    if(computeEigenvectors)
      doComputeEigenvectors(m_schur.matrixT().norm());
    sortEigenvalues(computeEigenvectors);
  }
  m_isInitialized = true;
  m_eigenvectorsOk = computeEigenvectors;
  return *this;
}
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::derived(), eigen_assert, Eigen::EigenBase< Derived >::rows(), and Eigen::Success.
compute() [2/2]
template<typename _MatrixType > template<typename InputType > ComplexEigenSolver & Eigen::ComplexEigenSolver< _MatrixType >::compute (const EigenBase< InputType > & matrix, bool computeEigenvectors = true)
Computes eigendecomposition of given matrix.
Parameters
[in] matrix Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
Returns
Reference to *this
This function computes the eigenvalues of the complex matrix matrix. The eigenvalues() function can be used to retrieve them. If computeEigenvectors is true, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
The matrix is first reduced to Schur form using the ComplexSchur class. The Schur decomposition is then used to compute the eigenvalues and eigenvectors.
The cost of the computation is dominated by the cost of the Schur decomposition, which is where is the size of the matrix.
Example:
Output:
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::ComplexEigenSolver().
doComputeEigenvectors()
template<typename MatrixType > void Eigen::ComplexEigenSolver< MatrixType >::doComputeEigenvectors (RealScalar matrixnorm) private
{
  const Index n = m_eivalues.size();
  matrixnorm = numext::maxi(matrixnorm,(std::numeric_limits<RealScalar>::min)());
  // Compute X such that T = X D X^(-1), where D is the diagonal of T.
  // The matrix X is unit triangular.
  m_matX = EigenvectorType::Zero(n, n);
  for(Index k=n-1 ; k>=0 ; k--)
  {
    m_matX.coeffRef(k,k) = ComplexScalar(1.0,0.0);
    // Compute X(i,k) using the (i,k) entry of the equation X T = D X
    for(Index i=k-1 ; i>=0 ; i--)
    {
      m_matX.coeffRef(i,k) = -m_schur.matrixT().coeff(i,k);
      if(k-i-1>0)
        m_matX.coeffRef(i,k) -= (m_schur.matrixT().row(i).segment(i+1,k-i-1) * m_matX.col(k).segment(i+1,k-i-1)).value();
      ComplexScalar z = m_schur.matrixT().coeff(i,i) - m_schur.matrixT().coeff(k,k);
      if(z==ComplexScalar(0))
      {
        // If the i-th and k-th eigenvalue are equal, then z equals 0.
        // Use a small value instead, to prevent division by zero.
        numext::real_ref(z) = NumTraits<RealScalar>::epsilon() * matrixnorm;
      }
      m_matX.coeffRef(i,k) = m_matX.coeff(i,k) / z;
    }
  }
  // Compute V as V = U X; now A = U T U^* = U X D X^(-1) U^* = V D V^(-1)
  m_eivec.noalias() = m_schur.matrixU() * m_matX;
  // .. and normalize the eigenvectors
  for(Index k=0 ; k<n ; k++)
  {
    m_eivec.col(k).normalize();
  }
}
References Eigen::numext::maxi(), and Eigen::numext::real_ref().
eigenvalues()
template<typename _MatrixType > const EigenvalueType & Eigen::ComplexEigenSolver< _MatrixType >::eigenvalues () const inline
Returns the eigenvalues of given matrix.
Returns
A const reference to the column vector containing the eigenvalues.
Precondition
Either the constructor ComplexEigenSolver(const MatrixType& matrix, bool) or the member function compute(const MatrixType& matrix, bool) has been called before to compute the eigendecomposition of a matrix.
This function returns a column vector containing the eigenvalues. Eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix. The eigenvalues are not sorted in any particular order.
Example:
Output:
    {
      eigen_assert(m_isInitialized && "ComplexEigenSolver is not initialized.");
      return m_eivalues;
    }
References eigen_assert, Eigen::ComplexEigenSolver< _MatrixType >::m_eivalues, and Eigen::ComplexEigenSolver< _MatrixType >::m_isInitialized.
Referenced by Eigen::internal::eigenvalues_selector< Derived, IsComplex >::run().
eigenvectors()
template<typename _MatrixType > const EigenvectorType & Eigen::ComplexEigenSolver< _MatrixType >::eigenvectors () const inline
Returns the eigenvectors of given matrix.
Returns
A const reference to the matrix whose columns are the eigenvectors.
Precondition
Either the constructor ComplexEigenSolver(const MatrixType& matrix, bool) or the member function compute(const MatrixType& matrix, bool) has been called before to compute the eigendecomposition of a matrix, and computeEigenvectors was set to true (the default).
This function returns a matrix whose columns are the eigenvectors. Column is an eigenvector corresponding to eigenvalue number as returned by eigenvalues(). The eigenvectors are normalized to have (Euclidean) norm equal to one. The matrix returned by this function is the matrix in the eigendecomposition , if it exists.
Example:
Output:
    {
      eigen_assert(m_isInitialized && "ComplexEigenSolver is not initialized.");
      eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
      return m_eivec;
    }
References eigen_assert, Eigen::ComplexEigenSolver< _MatrixType >::m_eigenvectorsOk, Eigen::ComplexEigenSolver< _MatrixType >::m_eivec, and Eigen::ComplexEigenSolver< _MatrixType >::m_isInitialized.
getMaxIterations()
template<typename _MatrixType > Index Eigen::ComplexEigenSolver< _MatrixType >::getMaxIterations () inline
Returns the maximum number of iterations.
    {
      return m_schur.getMaxIterations();
    }
References Eigen::ComplexSchur< _MatrixType >::getMaxIterations(), and Eigen::ComplexEigenSolver< _MatrixType >::m_schur.
info()
template<typename _MatrixType > ComputationInfo Eigen::ComplexEigenSolver< _MatrixType >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NoConvergence otherwise.
    {
      eigen_assert(m_isInitialized && "ComplexEigenSolver is not initialized.");
      return m_schur.info();
    }
References eigen_assert, Eigen::ComplexSchur< _MatrixType >::info(), Eigen::ComplexEigenSolver< _MatrixType >::m_isInitialized, and Eigen::ComplexEigenSolver< _MatrixType >::m_schur.
setMaxIterations()
template<typename _MatrixType > ComplexEigenSolver & Eigen::ComplexEigenSolver< _MatrixType >::setMaxIterations (Index maxIters) inline
Sets the maximum number of iterations allowed.
    {
      m_schur.setMaxIterations(maxIters);
      return *this;
    }
References Eigen::ComplexEigenSolver< _MatrixType >::m_schur, and Eigen::ComplexSchur< _MatrixType >::setMaxIterations().
sortEigenvalues()
template<typename MatrixType > void Eigen::ComplexEigenSolver< MatrixType >::sortEigenvalues (bool computeEigenvectors) private
{
  const Index n =  m_eivalues.size();
  for (Index i=0; i<n; i++)
  {
    Index k;
    m_eivalues.cwiseAbs().tail(n-i).minCoeff(&k);
    if (k != 0)
    {
      k += i;
      std::swap(m_eivalues[k],m_eivalues[i]);
      if(computeEigenvectors)
  m_eivec.col(i).swap(m_eivec.col(k));
    }
  }
}
Member Data Documentation
m_eigenvectorsOk
template<typename _MatrixType > bool Eigen::ComplexEigenSolver< _MatrixType >::m_eigenvectorsOk protected
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::eigenvectors().
m_eivalues
template<typename _MatrixType > EigenvalueType Eigen::ComplexEigenSolver< _MatrixType >::m_eivalues protected
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::eigenvalues().
m_eivec
template<typename _MatrixType > EigenvectorType Eigen::ComplexEigenSolver< _MatrixType >::m_eivec protected
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::eigenvectors().
m_isInitialized
template<typename _MatrixType > bool Eigen::ComplexEigenSolver< _MatrixType >::m_isInitialized protected
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::eigenvalues(), Eigen::ComplexEigenSolver< _MatrixType >::eigenvectors(), and Eigen::ComplexEigenSolver< _MatrixType >::info().
m_matX
template<typename _MatrixType > EigenvectorType Eigen::ComplexEigenSolver< _MatrixType >::m_matX protected
m_schur
template<typename _MatrixType > ComplexSchur<MatrixType> Eigen::ComplexEigenSolver< _MatrixType >::m_schur protected
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::getMaxIterations(), Eigen::ComplexEigenSolver< _MatrixType >::info(), and Eigen::ComplexEigenSolver< _MatrixType >::setMaxIterations().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Eigenvalues/ComplexEigenSolver.h