Prusa Slicer: Slic3r::Geometry::Transformation Class Reference
Slic3r::Geometry::Transformation Class Reference
#include <src/libslic3r/Geometry.hpp>
Public Member Functions
Transformation ()=default
Transformation (const Transform3d &transform)
Vec3d get_offset () const
double get_offset (Axis axis) const
Transform3d get_offset_matrix () const
void set_offset (const Vec3d &offset)
void set_offset (Axis axis, double offset)
Vec3d get_rotation () const
double get_rotation (Axis axis) const
Transform3d get_rotation_matrix () const
void set_rotation (const Vec3d &rotation)
void set_rotation (Axis axis, double rotation)
Vec3d get_scaling_factor () const
double get_scaling_factor (Axis axis) const
Transform3d get_scaling_factor_matrix () const
bool is_scaling_uniform () const
void set_scaling_factor (const Vec3d &scaling_factor)
void set_scaling_factor (Axis axis, double scaling_factor)
Vec3d get_mirror () const
double get_mirror (Axis axis) const
Transform3d get_mirror_matrix () const
bool is_left_handed () const
void set_mirror (const Vec3d &mirror)
void set_mirror (Axis axis, double mirror)
bool has_skew () const
void reset ()
void reset_offset ()
void reset_rotation ()
void reset_scaling_factor ()
void reset_mirror ()
void reset_skew ()
const Transform3d & get_matrix () const
Transform3d get_matrix_no_offset () const
Transform3d get_matrix_no_scaling_factor () const
void set_matrix (const Transform3d &transform)
Transformation operator* (const Transformation &other) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Transformation (int)
Static Private Member Functions
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< Transformation > &construct)
Private Attributes
Transform3d m_matrix { Transform3d::Identity() }
Friends
class cereal::access
Detailed Description
Constructor & Destructor Documentation
Transformation() [1/3]
Slic3r::Geometry::Transformation::Transformation () default
Referenced by operator*().
Transformation() [2/3]
Slic3r::Geometry::Transformation::Transformation (const Transform3d & transform) inline explicit
: m_matrix(transform) {}
Transformation() [3/3]
Slic3r::Geometry::Transformation::Transformation (int) inline explicit private
{}
Member Function Documentation
get_matrix()
const Transform3d & Slic3r::Geometry::Transformation::get_matrix () const inline
{ return m_matrix; }
References m_matrix.
Referenced by priv::apply_camera_dir(), Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::ModelObject::delete_volume(), Slic3r::GUI::Selection::flattening_rotate(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::ModelVolume::get_matrix(), Slic3r::ModelInstance::get_matrix(), get_matrix_no_offset(), get_matrix_no_scaling_factor(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::on_mouse_surface_drag(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render(), operator*(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::Selection::render_synchronized_volumes(), Slic3r::GUI::Selection::reset_skew(), Slic3r::GUI::GLGizmoCut3D::rotate_vec3d_around_plane_center(), Slic3r::GUI::Selection::scale_and_translate(), Slic3r::Print::sequential_print_horizontal_clearance_valid(), Slic3r::GUI::MeshClipper::set_transformation(), priv::start_create_volume_on_surface_job(), Slic3r::GUI::Selection::synchronize_unselected_instances(), Slic3r::Geometry::trafos_differ_in_rotation_by_z_and_mirroring_by_xy_only(), Slic3r::GUI::Selection::transform_instance_relative(), Slic3r::GUI::Selection::transform_volume_relative(), Slic3r::sla::transformed_drainhole_points(), Slic3r::GUI::Selection::translate(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), and Slic3r::GLVolume::world_matrix().
get_matrix_no_offset()
Transform3d Slic3r::Geometry::Transformation::get_matrix_no_offset () const
{
    Transformation copy(*this);
    copy.reset_offset();
    return copy.get_matrix();
}
References get_matrix(), and reset_offset().
Referenced by Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::Selection::flattening_rotate(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::ModelVolume::get_matrix_no_offset(), Slic3r::ModelInstance::get_matrix_no_offset(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Selection::reset_skew(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale_and_translate(), and Slic3r::GUI::Selection::transform_volume_relative().
get_matrix_no_scaling_factor()
Transform3d Slic3r::Geometry::Transformation::get_matrix_no_scaling_factor () const
{
    Transformation copy(*this);
    copy.reset_scaling_factor();
    return copy.get_matrix();
}
References get_matrix(), and reset_scaling_factor().
Referenced by Slic3r::GUI::Selection::get_bounding_box_in_reference_system().
get_mirror() [1/2]
Vec3d Slic3r::Geometry::Transformation::get_mirror () const
{
    const Transform3d scale = extract_scale(m_matrix);
    return { scale(0, 0) / std::abs(scale(0, 0)), scale(1, 1) / std::abs(scale(1, 1)), scale(2, 2) / std::abs(scale(2, 2)) };
}
References Slic3r::Geometry::extract_scale(), m_matrix, and scale().
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::GLVolume::get_instance_mirror(), Slic3r::GLVolume::get_instance_mirror(), Slic3r::ModelVolume::get_mirror(), Slic3r::ModelInstance::get_mirror(), Slic3r::ModelVolume::get_mirror(), Slic3r::ModelInstance::get_mirror(), Slic3r::GLVolume::get_volume_mirror(), Slic3r::GLVolume::get_volume_mirror(), and Slic3r::GLVolume::is_left_handed().
get_mirror() [2/2]
double Slic3r::Geometry::Transformation::get_mirror (Axis axis) const inline
{ return get_mirror()[axis]; }
References get_mirror().
Referenced by get_mirror().
get_mirror_matrix()
Transform3d Slic3r::Geometry::Transformation::get_mirror_matrix () const
{
    Transform3d scale = extract_scale(m_matrix);
    scale(0, 0) = scale(0, 0) / std::abs(scale(0, 0));
    scale(1, 1) = scale(1, 1) / std::abs(scale(1, 1));
    scale(2, 2) = scale(2, 2) / std::abs(scale(2, 2));
    return scale;
}
References Slic3r::Geometry::extract_scale(), m_matrix, and scale().
Referenced by Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::get_mesh_to_rotate().
get_offset() [1/2]
Vec3d Slic3r::Geometry::Transformation::get_offset () const inline
{ return m_matrix.translation(); }
References m_matrix, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::Model::convert_multipart_object(), Slic3r::GLVolume::get_instance_offset(), Slic3r::GLVolume::get_instance_offset(), Slic3r::ModelVolume::get_offset(), Slic3r::ModelInstance::get_offset(), Slic3r::ModelVolume::get_offset(), Slic3r::ModelInstance::get_offset(), get_offset_matrix(), Slic3r::GLVolume::get_volume_offset(), Slic3r::GLVolume::get_volume_offset(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale_and_translate(), set_mirror(), set_mirror(), set_rotation(), set_rotation(), set_scaling_factor(), set_scaling_factor(), Slic3r::GUI::Selection::transform_instance_relative(), Slic3r::GUI::Selection::transform_volume_relative(), Slic3r::GUI::Selection::translate(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), and Slic3r::GUI::ObjectManipulation::update_settings_value().
get_offset() [2/2]
double Slic3r::Geometry::Transformation::get_offset (Axis axis) const inline
{ return get_offset()[axis]; }
References get_offset().
Referenced by get_offset().
get_offset_matrix()
Transform3d Slic3r::Geometry::Transformation::get_offset_matrix () const
{
    return translation_transform(get_offset());
}
References get_offset(), and Slic3r::Geometry::translation_transform().
Referenced by Slic3r::GUI::Selection::flattening_rotate(), reset_rotation(), reset_scaling_factor(), reset_skew(), and Slic3r::GUI::Selection::reset_skew().
get_rotation() [1/2]
Vec3d Slic3r::Geometry::Transformation::get_rotation () const
{
    return extract_rotation(extract_rotation_matrix(m_matrix));
}
References Slic3r::Geometry::extract_rotation(), Slic3r::Geometry::extract_rotation_matrix(), and m_matrix.
Referenced by Slic3r::GLVolume::get_instance_rotation(), Slic3r::GLVolume::get_instance_rotation(), Slic3r::ModelVolume::get_rotation(), Slic3r::ModelInstance::get_rotation(), Slic3r::ModelVolume::get_rotation(), Slic3r::ModelInstance::get_rotation(), Slic3r::GLVolume::get_volume_rotation(), and Slic3r::GLVolume::get_volume_rotation().
get_rotation() [2/2]
double Slic3r::Geometry::Transformation::get_rotation (Axis axis) const inline
{ return get_rotation()[axis]; }
References get_rotation().
Referenced by get_rotation().
get_rotation_matrix()
Transform3d Slic3r::Geometry::Transformation::get_rotation_matrix () const
{
    return extract_rotation_matrix(m_matrix);
}
References Slic3r::Geometry::extract_rotation_matrix(), and m_matrix.
Referenced by Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::GUI::GLGizmoMove3D::local_transform(), Slic3r::GUI::Selection::rotate(), and Slic3r::GUI::Selection::translate().
get_scaling_factor() [1/2]
Vec3d Slic3r::Geometry::Transformation::get_scaling_factor () const
{
    const Transform3d scale = extract_scale(m_matrix);
    return { std::abs(scale(0, 0)), std::abs(scale(1, 1)), std::abs(scale(2, 2)) };
}
References Slic3r::Geometry::extract_scale(), m_matrix, and scale().
Referenced by Slic3r::TriangleSelector::Cursor::Cursor(), Slic3r::_3MF_Importer::_apply_transform(), Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::GLVolume::get_instance_scaling_factor(), Slic3r::GLVolume::get_instance_scaling_factor(), Slic3r::ModelVolume::get_scaling_factor(), Slic3r::ModelInstance::get_scaling_factor(), Slic3r::ModelVolume::get_scaling_factor(), Slic3r::ModelInstance::get_scaling_factor(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::GLVolume::get_volume_scaling_factor(), Slic3r::GLVolume::get_volume_scaling_factor(), and is_scaling_uniform().
get_scaling_factor() [2/2]
double Slic3r::Geometry::Transformation::get_scaling_factor (Axis axis) const inline
{ return get_scaling_factor()[axis]; }
References get_scaling_factor().
Referenced by get_scaling_factor().
get_scaling_factor_matrix()
Transform3d Slic3r::Geometry::Transformation::get_scaling_factor_matrix () const
{
    Transform3d scale = extract_scale(m_matrix);
    scale(0, 0) = std::abs(scale(0, 0));
    scale(1, 1) = std::abs(scale(1, 1));
    scale(2, 2) = std::abs(scale(2, 2));
    return scale;
}
References Slic3r::Geometry::extract_scale(), m_matrix, and scale().
Referenced by Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::get_mesh_to_rotate(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::translate(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform().
has_skew()
bool Slic3r::Geometry::Transformation::has_skew () const
{
    return contains_skew(m_matrix);
}
References Slic3r::Geometry::contains_skew(), and m_matrix.
Referenced by Slic3r::GUI::Selection::reset_skew().
is_left_handed()
bool Slic3r::Geometry::Transformation::is_left_handed () const inline
{
        return m_matrix.linear().determinant() < 0;
    }
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), and m_matrix.
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::ModelVolume::is_left_handed(), Slic3r::ModelInstance::is_left_handed(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere(), Slic3r::GUI::Selection::rotate(), and Slic3r::GUI::GLGizmoFlatten::update_planes().
is_scaling_uniform()
bool Slic3r::Geometry::Transformation::is_scaling_uniform () const inline
{
        const Vec3d scale = get_scaling_factor();
        return std::abs(scale.x() - scale.y()) < 1e-8 && std::abs(scale.x() - scale.z()) < 1e-8;
    }
References get_scaling_factor(), and scale().
load_and_construct()
template<class Archive > static void Slic3r::Geometry::Transformation::load_and_construct (Archive & ar, cereal::construct< Transformation > & construct) inline static private
    {
        // Calling a private constructor with special "int" parameter to indicate that no construction is necessary.
        construct(1);
        ar(construct.ptr()->m_matrix);
    }
operator*()
Transformation Slic3r::Geometry::Transformation::operator* (const Transformation & other) const
{
    return Transformation(get_matrix() * other.get_matrix());
}
References Transformation(), and get_matrix().
reset()
void Slic3r::Geometry::Transformation::reset ()
{
    m_matrix = Transform3d::Identity();
}
References Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), and m_matrix.
reset_mirror()
void Slic3r::Geometry::Transformation::reset_mirror () inline
{ set_mirror(Vec3d::Ones()); }
References set_mirror().
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes().
reset_offset()
void Slic3r::Geometry::Transformation::reset_offset () inline
{ set_offset(Vec3d::Zero()); }
References set_offset().
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes(), get_matrix_no_offset(), and Slic3r::GUI::Selection::reset_skew().
reset_rotation()
void Slic3r::Geometry::Transformation::reset_rotation ()
{
    const Geometry::TransformationSVD svd(*this);
    m_matrix = get_offset_matrix() * Transform3d(svd.v * svd.s * svd.v.transpose()) * svd.mirror_matrix();
}
References get_offset_matrix(), m_matrix, Slic3r::Geometry::TransformationSVD::mirror_matrix(), Slic3r::Geometry::TransformationSVD::s, and Slic3r::Geometry::TransformationSVD::v.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), and Slic3r::GUI::Selection::synchronize_unselected_instances().
reset_scaling_factor()
void Slic3r::Geometry::Transformation::reset_scaling_factor ()
{
    const Geometry::TransformationSVD svd(*this);
    m_matrix = get_offset_matrix() * Transform3d(svd.u) * Transform3d(svd.v.transpose()) * svd.mirror_matrix();
}
References get_offset_matrix(), m_matrix, Slic3r::Geometry::TransformationSVD::mirror_matrix(), Slic3r::Geometry::TransformationSVD::u, and Slic3r::Geometry::TransformationSVD::v.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), and get_matrix_no_scaling_factor().
reset_skew()
void Slic3r::Geometry::Transformation::reset_skew ()
{
    auto new_scale_factor = [](const Matrix3d& s) {
        return pow(s(0, 0) * s(1, 1) * s(2, 2), 1. / 3.); // scale average
    };
    const Geometry::TransformationSVD svd(*this);
    m_matrix = get_offset_matrix() * Transform3d(svd.u) * scale_transform(new_scale_factor(svd.s)) * Transform3d(svd.v.transpose()) * svd.mirror_matrix();
}
References get_offset_matrix(), m_matrix, Slic3r::Geometry::TransformationSVD::mirror_matrix(), Slic3r::Geometry::TransformationSVD::s, Slic3r::Geometry::scale_transform(), Slic3r::Geometry::TransformationSVD::u, and Slic3r::Geometry::TransformationSVD::v.
Referenced by Slic3r::GUI::Selection::reset_skew().
serialize()
template<class Archive > void Slic3r::Geometry::Transformation::serialize (Archive & ar) inline private
{ ar(m_matrix); }
References m_matrix.
set_matrix()
void Slic3r::Geometry::Transformation::set_matrix (const Transform3d & transform) inline
{ m_matrix = transform; }
References m_matrix, and Slic3r::transform().
Referenced by Slic3r::GLVolume::set_instance_transformation(), Slic3r::ModelVolume::set_transformation(), Slic3r::GLVolume::set_volume_transformation(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform().
set_mirror() [1/2]
void Slic3r::Geometry::Transformation::set_mirror (Axis axis, double mirror)
{
    double abs_mirror = std::abs(mirror);
    if (abs_mirror == 0.0)
        mirror = 1.0;
    else if (abs_mirror != 1.0)
        mirror /= abs_mirror;
    auto [rotation, scale] = extract_rotation_scale(m_matrix);
    const double curr_scale = scale(axis, axis);
    const double sign = curr_scale * mirror;
    if (sign < 0.0) scale(axis, axis) = -scale(axis, axis);
    const Vec3d offset = get_offset();
    m_matrix = rotation * scale;
    m_matrix.translation() = offset;
}
References Slic3r::Geometry::extract_rotation_scale(), get_offset(), m_matrix, Slic3r::offset(), scale(), sign(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
set_mirror() [2/2]
void Slic3r::Geometry::Transformation::set_mirror (const Vec3d & mirror)
{
    Vec3d copy(mirror);
    const Vec3d abs_mirror = copy.cwiseAbs();
    for (int i = 0; i < 3; ++i) {
        if (abs_mirror(i) == 0.0)
            copy(i) = 1.0;
        else if (abs_mirror(i) != 1.0)
            copy(i) /= abs_mirror(i);
    }
    auto [rotation, scale] = extract_rotation_scale(m_matrix);
    const Vec3d curr_scales = { scale(0, 0), scale(1, 1), scale(2, 2) };
    const Vec3d signs = curr_scales.cwiseProduct(copy);
    if (signs[0] < 0.0) scale(0, 0) = -scale(0, 0);
    if (signs[1] < 0.0) scale(1, 1) = -scale(1, 1);
    if (signs[2] < 0.0) scale(2, 2) = -scale(2, 2);
    const Vec3d offset = get_offset();
    m_matrix = rotation * scale;
    m_matrix.translation() = offset;
}
References Slic3r::Geometry::extract_rotation_scale(), get_offset(), m_matrix, Slic3r::offset(), scale(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by reset_mirror(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::ModelVolume::set_mirror(), Slic3r::ModelInstance::set_mirror(), Slic3r::ModelVolume::set_mirror(), Slic3r::ModelInstance::set_mirror(), Slic3r::GLVolume::set_volume_mirror(), and Slic3r::GLVolume::set_volume_mirror().
set_offset() [1/2]
void Slic3r::Geometry::Transformation::set_offset (Axis axis, double offset) inline
{ m_matrix.translation()[axis] = offset; }
References m_matrix, Slic3r::offset(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
set_offset() [2/2]
void Slic3r::Geometry::Transformation::set_offset (const Vec3d & offset) inline
{ m_matrix.translation() = offset; }
References m_matrix, Slic3r::offset(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by Slic3r::Model::convert_multipart_object(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::Plater::increase_instances(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), reset_offset(), Slic3r::Print::sequential_print_horizontal_clearance_valid(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_offset(), Slic3r::ModelVolume::set_offset(), Slic3r::ModelInstance::set_offset(), Slic3r::ModelVolume::set_offset(), Slic3r::ModelInstance::set_offset(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_offset(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
set_rotation() [1/2]
void Slic3r::Geometry::Transformation::set_rotation (Axis axis, double rotation)
{
    rotation = angle_to_0_2PI(rotation);
    if (is_approx(std::abs(rotation), 2.0 * double(PI)))
        rotation = 0.0;
    auto [curr_rotation, scale] = extract_rotation_scale(m_matrix);
    Vec3d angles = extract_rotation(curr_rotation);
    angles[axis] = rotation;
    const Vec3d offset = get_offset();
    m_matrix = rotation_transform(angles) * scale;
    m_matrix.translation() = offset;
}
References Slic3r::Geometry::angle_to_0_2PI(), Slic3r::Geometry::extract_rotation(), Slic3r::Geometry::extract_rotation_scale(), get_offset(), Slic3r::is_approx(), m_matrix, Slic3r::offset(), PI, Slic3r::Geometry::rotation_transform(), scale(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
set_rotation() [2/2]
void Slic3r::Geometry::Transformation::set_rotation (const Vec3d & rotation)
{
    const Vec3d offset = get_offset();
    m_matrix = rotation_transform(rotation) * extract_scale(m_matrix);
    m_matrix.translation() = offset;
}
References Slic3r::Geometry::extract_scale(), get_offset(), m_matrix, Slic3r::offset(), Slic3r::Geometry::rotation_transform(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by Slic3r::GLVolume::set_instance_rotation(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::ModelVolume::set_rotation(), Slic3r::ModelInstance::set_rotation(), Slic3r::ModelVolume::set_rotation(), Slic3r::ModelInstance::set_rotation(), Slic3r::GLVolume::set_volume_rotation(), and Slic3r::GLVolume::set_volume_rotation().
set_scaling_factor() [1/2]
void Slic3r::Geometry::Transformation::set_scaling_factor (Axis axis, double scaling_factor)
{
    assert(scaling_factor > 0.0);
    auto [rotation, scale] = extract_rotation_scale(m_matrix);
    scale(axis, axis) = scaling_factor;
    const Vec3d offset = get_offset();
    m_matrix = rotation * scale;
    m_matrix.translation() = offset;
}
References Slic3r::Geometry::extract_rotation_scale(), get_offset(), m_matrix, Slic3r::offset(), scale(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
set_scaling_factor() [2/2]
void Slic3r::Geometry::Transformation::set_scaling_factor (const Vec3d & scaling_factor)
{
    assert(scaling_factor.x() > 0.0 && scaling_factor.y() > 0.0 && scaling_factor.z() > 0.0);
    const Vec3d offset = get_offset();
    m_matrix = extract_rotation_matrix(m_matrix) * scale_transform(scaling_factor);
    m_matrix.translation() = offset;
}
References Slic3r::Geometry::extract_rotation_matrix(), get_offset(), m_matrix, Slic3r::offset(), Slic3r::Geometry::scale_transform(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by Slic3r::GLVolume::set_instance_scaling_factor(), Slic3r::GLVolume::set_instance_scaling_factor(), Slic3r::ModelVolume::set_scaling_factor(), Slic3r::ModelInstance::set_scaling_factor(), Slic3r::ModelVolume::set_scaling_factor(), Slic3r::ModelInstance::set_scaling_factor(), Slic3r::GLVolume::set_volume_scaling_factor(), and Slic3r::GLVolume::set_volume_scaling_factor().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
m_matrix
Transform3d Slic3r::Geometry::Transformation::m_matrix { Transform3d::Identity() } private
Referenced by get_matrix(), get_mirror(), get_mirror_matrix(), get_offset(), get_rotation(), get_rotation_matrix(), get_scaling_factor(), get_scaling_factor_matrix(), has_skew(), is_left_handed(), reset(), reset_rotation(), reset_scaling_factor(), reset_skew(), serialize(), set_matrix(), set_mirror(), set_mirror(), set_offset(), set_offset(), set_rotation(), set_rotation(), set_scaling_factor(), and set_scaling_factor().
The documentation for this class was generated from the following files:
src/libslic3r/Geometry.hpp
src/libslic3r/Geometry.cpp