Prusa Slicer: ImBitVector Struct Reference
ImBitVector Struct Reference
#include <src/imgui/imgui_internal.h>
Public Member Functions
void Create (int sz)
void Clear ()
bool TestBit (int n) const
void SetBit (int n)
void ClearBit (int n)
Public Attributes
ImVector< ImU32 > Storage
Detailed Description
Member Function Documentation
Clear()
void ImBitVector::Clear () inline
{ Storage.clear(); }
References ImVector< T >::clear().
Referenced by ImFontAtlasBuildWithStbTruetype().
ClearBit()
void ImBitVector::ClearBit (int n) inline
{ IM_ASSERT(n < (Storage.Size << 5)); ImBitArrayClearBit(Storage.Data, n); }
References ImVector< T >::Data, IM_ASSERT, ImBitArrayClearBit(), and ImVector< T >::Size.
Create()
void ImBitVector::Create (int sz) inline
{ Storage.resize((sz + 31) >> 5); memset(Storage.Data, 0, (size_t)Storage.Size * sizeof(Storage.Data[0])); }
References ImVector< T >::Data, ImVector< T >::resize(), and ImVector< T >::Size.
Referenced by ImFontAtlasBuildWithStbTruetype().
SetBit()
void ImBitVector::SetBit (int n) inline
{ IM_ASSERT(n < (Storage.Size << 5)); ImBitArraySetBit(Storage.Data, n); }
References ImVector< T >::Data, IM_ASSERT, ImBitArraySetBit(), and ImVector< T >::Size.
Referenced by ImFontAtlasBuildWithStbTruetype().
TestBit()
bool ImBitVector::TestBit (int n) const inline
{ IM_ASSERT(n < (Storage.Size << 5)); return ImBitArrayTestBit(Storage.Data, n); }
References ImVector< T >::Data, IM_ASSERT, ImBitArrayTestBit(), and ImVector< T >::Size.
Referenced by ImFontAtlasBuildWithStbTruetype().
Member Data Documentation
Storage
ImVector<ImU32> ImBitVector::Storage
Referenced by ImFontAtlasBuildWithStbTruetype(), and UnpackBitVectorToFlatIndexList().
The documentation for this struct was generated from the following file:
src/imgui/imgui_internal.h