Prusa Slicer: Slic3r::PlaceholderParser Class Reference
Slic3r::PlaceholderParser Class Reference
#include <src/libslic3r/PlaceholderParser.hpp>
Classes
struct ContextData
Public Member Functions
PlaceholderParser (const DynamicConfig *external_config=nullptr)
void clear_config ()
std::vector< std::string > config_diff (const DynamicPrintConfig &rhs)
bool apply_config (const DynamicPrintConfig &config)
void apply_config (DynamicPrintConfig &&config)
void apply_only (const DynamicPrintConfig &config, const std::vector< std::string > &keys)
void apply_env_variables ()
void set (const std::string &key, const std::string &value)
void set (const std::string &key, std::string_view value)
void set (const std::string &key, const char *value)
void set (const std::string &key, int value)
void set (const std::string &key, unsigned int value)
void set (const std::string &key, bool value)
void set (const std::string &key, double value)
void set (const std::string &key, const std::vector< std::string > &values)
void set (const std::string &key, ConfigOption *opt)
DynamicConfig & config_writable ()
const DynamicConfig & config () const
const ConfigOption * option (const std::string &key) const
const DynamicConfig * external_config () const
std::string process (const std::string &templ, unsigned int current_extruder_id, const DynamicConfig *config_override, DynamicConfig *config_outputs, ContextData *context) const
std::string process (const std::string &templ, unsigned int current_extruder_id=0, const DynamicConfig *config_override=nullptr, ContextData *context=nullptr) const
void update_timestamp ()
Static Public Member Functions
static bool evaluate_boolean_expression (const std::string &templ, const DynamicConfig &config, const DynamicConfig *config_override=nullptr)
static void update_timestamp (DynamicConfig &config)
Private Attributes
DynamicConfig m_config
const DynamicConfig * m_external_config
Detailed Description
Class Documentation
Slic3r::PlaceholderParser::ContextData
struct Slic3r::PlaceholderParser::ContextData
Class Members
unique_ptr< DynamicConfig > global_config
mt19937 rng
Constructor & Destructor Documentation
PlaceholderParser()
Slic3r::PlaceholderParser::PlaceholderParser (const DynamicConfig * external_config = nullptr)
                                                                         : m_external_config(external_config)
{
    this->set("version", std::string(SLIC3R_VERSION));
    this->apply_env_variables();
    this->update_timestamp();
}
References apply_env_variables(), set(), and update_timestamp().
Member Function Documentation
apply_config() [1/2]
bool Slic3r::PlaceholderParser::apply_config (const DynamicPrintConfig & config)
{
    bool modified = false;
    for (const t_config_option_key &opt_key : rhs.keys()) {
        if (! opts_equal(m_config, rhs, opt_key)) {
      this->set(opt_key, rhs.option(opt_key)->clone());
            modified = true;
        }
    }
    return modified;
}
References Slic3r::ConfigOption::clone(), Slic3r::DynamicConfig::keys(), m_config, Slic3r::ConfigBase::option(), Slic3r::opts_equal(), and set().
Referenced by Slic3r::SLAPrint::apply().
apply_config() [2/2]
void Slic3r::PlaceholderParser::apply_config (DynamicPrintConfig && config)
{
  m_config += std::move(rhs);
}
References m_config.
apply_env_variables()
void Slic3r::PlaceholderParser::apply_env_variables ()
{
    for (char** env = environ; *env; ++ env) {
        if (strncmp(*env, "SLIC3R_", 7) == 0) {
            std::stringstream ss(*env);
            std::string key, value;
            std::getline(ss, key, '=');
            ss >> value;
            this->set(key, value);
        }
    }
}
References environ, and set().
Referenced by PlaceholderParser().
apply_only()
void Slic3r::PlaceholderParser::apply_only (const DynamicPrintConfig & config, const std::vector< std::string > & keys)
{
    for (const t_config_option_key &opt_key : keys)
        this->set(opt_key, rhs.option(opt_key)->clone());
}
References Slic3r::ConfigOption::clone(), Slic3r::ConfigBase::option(), and set().
clear_config()
void Slic3r::PlaceholderParser::clear_config () inline
{ m_config.clear(); }
References Slic3r::DynamicConfig::clear(), and m_config.
config()
const DynamicConfig & Slic3r::PlaceholderParser::config () const inline
{ return m_config; }
References m_config.
Referenced by evaluate_boolean_expression(), process(), and update_timestamp().
config_diff()
std::vector< std::string > Slic3r::PlaceholderParser::config_diff (const DynamicPrintConfig & rhs)
{
    std::vector<std::string> diff_keys;
    for (const t_config_option_key &opt_key : rhs.keys())
        if (! opts_equal(m_config, rhs, opt_key))
            diff_keys.emplace_back(opt_key);
    return diff_keys;
}
References Slic3r::DynamicConfig::keys(), m_config, and Slic3r::opts_equal().
Referenced by Slic3r::SLAPrint::apply().
config_writable()
DynamicConfig & Slic3r::PlaceholderParser::config_writable () inline
{ return m_config; }
References m_config.
Referenced by Slic3r::GCode::_do_export().
evaluate_boolean_expression()
bool Slic3r::PlaceholderParser::evaluate_boolean_expression (const std::string & templ, const DynamicConfig & config, const DynamicConfig * config_override = nullptr) static
{
    client::MyContext context;
    context.config              = &config;
    context.config_override     = config_override;
    // Let the macro processor parse just a boolean expression, not the full macro language.
    context.just_boolean_expression = true;
    return process_macro(templ, context) == "true";
}
References Slic3r::client::MyContext::config, config(), Slic3r::client::MyContext::config_override, Slic3r::client::MyContext::just_boolean_expression, and Slic3r::process_macro().
Referenced by Slic3r::is_compatible_with_print(), and Slic3r::is_compatible_with_printer().
external_config()
const DynamicConfig * Slic3r::PlaceholderParser::external_config () const inline
{ return m_external_config; }
References m_external_config.
Referenced by process().
option()
const ConfigOption * Slic3r::PlaceholderParser::option (const std::string & key) const inline
{ return m_config.option(key); }
References m_config, and Slic3r::ConfigBase::option().
process() [1/2]
std::string Slic3r::PlaceholderParser::process (const std::string & templ, unsigned int current_extruder_id, const DynamicConfig * config_override, DynamicConfig * config_outputs, ContextData * context) const
{
    client::MyContext context;
    context.external_config   = this->external_config();
    context.config              = &this->config();
    context.config_override     = config_override;
    context.config_outputs      = config_outputs;
    context.current_extruder_id = current_extruder_id;
    context.context_data        = context_data;
    return process_macro(templ, context);
}
References Slic3r::client::MyContext::config, config(), Slic3r::client::MyContext::config_outputs, Slic3r::client::MyContext::config_override, Slic3r::client::MyContext::context_data, Slic3r::client::MyContext::current_extruder_id, Slic3r::client::MyContext::external_config, external_config(), and Slic3r::process_macro().
Referenced by Slic3r::PrintStatistics::finalize_output_path(), Slic3r::SLAPrintStatistics::finalize_output_path(), Slic3r::PrintBase::output_filename(), Slic3r::GCode::placeholder_parser_process(), and process().
process() [2/2]
std::string Slic3r::PlaceholderParser::process (const std::string & templ, unsigned int current_extruder_id = 0, const DynamicConfig * config_override = nullptr, ContextData * context = nullptr) const inline
        { return this->process(templ, current_extruder_id, config_override, nullptr /* config_outputs */, context); }
References process().
set() [1/9]
void Slic3r::PlaceholderParser::set (const std::string & key, bool value) inline
{ this->set(key, new ConfigOptionBool(value)); }
References set().
Referenced by set().
set() [2/9]
void Slic3r::PlaceholderParser::set (const std::string & key, ConfigOption * opt) inline
{ m_config.set_key_value(key, opt); }
References m_config, and Slic3r::DynamicConfig::set_key_value().
set() [3/9]
void Slic3r::PlaceholderParser::set (const std::string & key, const char * value) inline
{ this->set(key, new ConfigOptionString(value)); }
References set().
Referenced by set().
set() [4/9]
void Slic3r::PlaceholderParser::set (const std::string & key, const std::string & value) inline
{ this->set(key, new ConfigOptionString(value)); }
References set().
Referenced by PlaceholderParser(), Slic3r::GCode::_do_export(), Slic3r::SLAPrint::apply(), apply_config(), apply_env_variables(), apply_only(), set(), and Slic3r::GCode::set_extruder().
set() [5/9]
void Slic3r::PlaceholderParser::set (const std::string & key, const std::vector< std::string > & values) inline
{ this->set(key, new ConfigOptionStrings(values)); }
References set().
Referenced by set().
set() [6/9]
void Slic3r::PlaceholderParser::set (const std::string & key, double value) inline
{ this->set(key, new ConfigOptionFloat(value)); }
References set().
Referenced by set().
set() [7/9]
void Slic3r::PlaceholderParser::set (const std::string & key, int value) inline
{ this->set(key, new ConfigOptionInt(value)); }
References set().
Referenced by set().
set() [8/9]
void Slic3r::PlaceholderParser::set (const std::string & key, std::string_view value) inline
{ this->set(key, new ConfigOptionString(std::string(value))); }
References set().
Referenced by set().
set() [9/9]
void Slic3r::PlaceholderParser::set (const std::string & key, unsigned int value) inline
{ this->set(key, int(value)); }
References set().
Referenced by set().
update_timestamp() [1/2]
void Slic3r::PlaceholderParser::update_timestamp () inline
{ update_timestamp(m_config); }
References m_config, and update_timestamp().
Referenced by PlaceholderParser(), Slic3r::PrintBase::output_filename(), and update_timestamp().
update_timestamp() [2/2]
void Slic3r::PlaceholderParser::update_timestamp (DynamicConfig & config) static
{
    time_t rawtime;
    time(&rawtime);
    struct tm* timeinfo = localtime(&rawtime);
    {
        std::ostringstream ss;
        ss << (1900 + timeinfo->tm_year);
        ss << std::setw(2) << std::setfill('0') << (1 + timeinfo->tm_mon);
        ss << std::setw(2) << std::setfill('0') << timeinfo->tm_mday;
        ss << "-";
        ss << std::setw(2) << std::setfill('0') << timeinfo->tm_hour;
        ss << std::setw(2) << std::setfill('0') << timeinfo->tm_min;
        ss << std::setw(2) << std::setfill('0') << timeinfo->tm_sec;
        config.set_key_value("timestamp", new ConfigOptionString(ss.str()));
    }
    config.set_key_value("year",   new ConfigOptionInt(1900 + timeinfo->tm_year));
    config.set_key_value("month",  new ConfigOptionInt(1 + timeinfo->tm_mon));
    config.set_key_value("day",    new ConfigOptionInt(timeinfo->tm_mday));
    config.set_key_value("hour",   new ConfigOptionInt(timeinfo->tm_hour));
    config.set_key_value("minute", new ConfigOptionInt(timeinfo->tm_min));
    config.set_key_value("second", new ConfigOptionInt(timeinfo->tm_sec));
}
References config(), and Slic3r::DynamicConfig::set_key_value().
Referenced by Slic3r::GCode::_do_export().
Member Data Documentation
m_config
DynamicConfig Slic3r::PlaceholderParser::m_config private
Referenced by apply_config(), apply_config(), clear_config(), config(), config_diff(), config_writable(), option(), set(), and update_timestamp().
m_external_config
const DynamicConfig* Slic3r::PlaceholderParser::m_external_config private
Referenced by external_config().
The documentation for this class was generated from the following files:
src/libslic3r/PlaceholderParser.hpp
src/libslic3r/PlaceholderParser.cpp