Prusa Slicer: anonymous_namespace{GLGizmoEmboss.cpp} Namespace Reference
anonymous_namespace{GLGizmoEmboss.cpp} Namespace Reference
Functions
TransformationType get_transformation_type (const Selection &selection)
Function Documentation
get_transformation_type()
TransformationType anonymous_namespace{GLGizmoEmboss.cpp}::get_transformation_type (const Selection & selection)
{
    assert(selection.is_single_full_object() || selection.is_single_volume());
    return selection.is_single_volume() ?
        TransformationType::Local_Relative_Joint :
        TransformationType::Instance_Relative_Joint; // object
}
References get_transformation_type(), Slic3r::GUI::TransformationType::Instance_Relative_Joint, Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_volume(), and Slic3r::GUI::TransformationType::Local_Relative_Joint.
Referenced by get_transformation_type().