Prusa Slicer: Slic3r::GUI::GLGizmoCut3D::PartSelection Class Reference
Slic3r::GUI::GLGizmoCut3D::PartSelection Class Reference
Classes
struct Part
Public Member Functions
PartSelection ()=default
PartSelection (const ModelObject *mo, const Transform3d &cut_matrix, int instance_idx, const Vec3d &center, const Vec3d &normal, const CommonGizmosDataObjects::ObjectClipper &oc)
~PartSelection ()
void render (const Vec3d *normal, GLModel &sphere_model)
void toggle_selection (const Vec2d &mouse_pos)
void turn_over_selection ()
ModelObject * model_object ()
bool valid () const
bool is_one_object () const
const std::vector< Part > & parts () const
const std::vector< size_t > * get_ignored_contours_ptr () const
Private Attributes
Model m_model
int m_instance_idx
std::vector< Part > m_parts
bool m_valid = false
std::vector< std::pair< std::vector< size_t >, std::vector< size_t > > > m_contour_to_parts
std::vector< size_t > m_ignored_contours
std::vector< Vec3d > m_contour_points
std::vector< std::vector< Vec3d > > m_debug_pts
Detailed Description
Class Documentation
Slic3r::GUI::GLGizmoCut3D::PartSelection::Part
struct Slic3r::GUI::GLGizmoCut3D::PartSelection::Part
Class Members
GLModel glmodel
bool is_modifier
MeshRaycaster raycaster
bool selected
Constructor & Destructor Documentation
PartSelection() [1/2]
Slic3r::GUI::GLGizmoCut3D::PartSelection::PartSelection () default
PartSelection() [2/2]
Slic3r::GUI::GLGizmoCut3D::PartSelection::PartSelection (const ModelObject * mo, const Transform3d & cut_matrix, int instance_idx, const Vec3d & center, const Vec3d & normal, const CommonGizmosDataObjects::ObjectClipper & oc)
{
    m_model = Model();
    m_model.add_object(*mo);
    ModelObjectPtrs cut_part_ptrs = m_model.objects.front()->cut(instance_idx_in, cut_matrix,
        ModelObjectCutAttribute::KeepUpper |
        ModelObjectCutAttribute::KeepLower |
        ModelObjectCutAttribute::KeepAsParts);
    assert(cut_part_ptrs.size() == 1);
    m_model = Model();
    m_model.add_object(*cut_part_ptrs.front());
    m_instance_idx = instance_idx_in;
    const ModelVolumePtrs& volumes = model_object()->volumes;
    // split to parts
    for (int id = int(volumes.size())-1; id >= 0; id--)
        if (volumes[id]->is_splittable())
            volumes[id]->split(1);
    m_parts.clear();
    for (const ModelVolume* volume : volumes) {
        assert(volume != nullptr);
        m_parts.emplace_back(Part{GLModel(), MeshRaycaster(volume->mesh()), true, !volume->is_model_part()});
        m_parts.back().glmodel.set_color({ 0.f, 0.f, 1.f, 1.f });
        m_parts.back().glmodel.init_from(volume->mesh());
        // Now check whether this part is below or above the plane.
        Transform3d tr = (model_object()->instances[m_instance_idx]->get_matrix() * volume->get_matrix()).inverse();
        Vec3f pos = (tr * center).cast<float>();
        Vec3f norm = (tr.linear().inverse().transpose() * normal).cast<float>();
        for (const Vec3f& v : volume->mesh().its.vertices) {
            double p = (v - pos).dot(norm);
            if (std::abs(p) > EPSILON) {
                m_parts.back().selected = p > 0.;
                break;
            }
        }
    }
    // Now go through the contours and create a map from contours to parts.
    m_contour_points.clear();
    m_contour_to_parts.clear();
    m_debug_pts = std::vector<std::vector<Vec3d>>(m_parts.size(), std::vector<Vec3d>());
    if (std::vector<Vec3d> pts = oc.point_per_contour();! pts.empty()) {
        m_contour_to_parts.resize(pts.size());
        for (size_t pt_idx=0; pt_idx<pts.size(); ++pt_idx) {
            const Vec3d& pt = pts[pt_idx];
            const Vec3d dir = (center-pt).dot(normal) * normal;
            m_contour_points.emplace_back(dir + pt); // the result is in world coordinates.
            // Now, cast a ray from every contour point and see which volumes of the ones above
            // the plane are hit from the inside.
            for (size_t part_id=0; part_id<m_parts.size(); ++part_id) {
                const AABBMesh& aabb = m_parts[part_id].raycaster.get_aabb_mesh();
                const Transform3d& tr = (translation_transform(model_object()->instances[m_instance_idx]->get_offset()) * translation_transform(model_object()->volumes[part_id]->get_offset())).inverse();
                for (double d : {-1., 1.}) {
                    const Vec3d dir_mesh = d * tr.linear().inverse().transpose() * normal;
                    const Vec3d src = tr * (m_contour_points[pt_idx] + d*0.01 * normal);
                    AABBMesh::hit_result hit = aabb.query_ray_hit(src, dir_mesh);
                    m_debug_pts[part_id].emplace_back(src);
                    if (hit.is_inside()) {
                        // This part belongs to this point.
                        if (d == 1.)
                            m_contour_to_parts[pt_idx].first.emplace_back(part_id);
                        else
                            m_contour_to_parts[pt_idx].second.emplace_back(part_id);
                    }
                }
            }
        }
    }
    m_valid = true;
}
References Slic3r::Model::add_object(), Slic3r::dot(), EPSILON, Slic3r::ModelObject::instances, inverse(), Slic3r::KeepAsParts, Slic3r::KeepLower, Slic3r::KeepUpper, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), m_contour_points, m_contour_to_parts, m_debug_pts, m_instance_idx, m_model, m_parts, m_valid, model_object(), Slic3r::Model::objects, Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::point_per_contour(), Slic3r::AABBMesh::query_ray_hit(), Slic3r::Geometry::translation_transform(), and Slic3r::ModelObject::volumes.
~PartSelection()
Slic3r::GUI::GLGizmoCut3D::PartSelection::~PartSelection () inline
{ m_model.clear_objects(); }
References Slic3r::Model::clear_objects(), and m_model.
Member Function Documentation
get_ignored_contours_ptr()
const std::vector< size_t > * Slic3r::GUI::GLGizmoCut3D::PartSelection::get_ignored_contours_ptr () const inline
{ return (valid() ? &m_ignored_contours : nullptr); }
References m_ignored_contours, and valid().
Referenced by Slic3r::GUI::GLGizmoCut3D::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoCut3D::render_clipper_cut(), and Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane().
is_one_object()
bool Slic3r::GUI::GLGizmoCut3D::PartSelection::is_one_object () const
{
    // In theory, the implementation could be just this:
    // return m_contour_to_parts.size() == m_ignored_contours.size();
    // However, this would require that the part-contour correspondence works
    // flawlessly. Because it is currently not always so for self-intersecting
    // objects, let's better check the parts itself:
    if (m_parts.size() < 2)
        return true;
    return std::all_of(m_parts.begin(), m_parts.end(), [this](const Part& part) {
        return part.is_modifier || part.selected == m_parts.front().selected;
    });
}
Referenced by Slic3r::GUI::GLGizmoCut3D::can_perform_cut(), and Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window().
model_object()
ModelObject * Slic3r::GUI::GLGizmoCut3D::PartSelection::model_object () inline
{ return m_model.objects.front(); }
References m_model, and Slic3r::Model::objects.
Referenced by PartSelection(), and Slic3r::GUI::GLGizmoCut3D::perform_cut().
parts()
const std::vector< Part > & Slic3r::GUI::GLGizmoCut3D::PartSelection::parts () const inline
{ return m_parts; }
References m_parts.
Referenced by Slic3r::GUI::GLGizmoCut3D::perform_cut().
render()
void Slic3r::GUI::GLGizmoCut3D::PartSelection::render (const Vec3d * normal, GLModel & sphere_model)
{
    if (! valid())
        return;
    const Camera&       camera          = wxGetApp().plater()->get_camera();
    if (GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light")) {
        shader->start_using();
        shader->set_uniform("projection_matrix", camera.get_projection_matrix());
        shader->set_uniform("emission_factor", 0.f);
        // FIXME: Cache the transforms.
        const Vec3d         inst_offset     = model_object()->instances[m_instance_idx]->get_offset();
        const Transform3d   view_inst_matrix= camera.get_view_matrix() * translation_transform(inst_offset);
        const bool is_looking_forward = normal && camera.get_dir_forward().dot(*normal) < 0.05;
        for (size_t id=0; id<m_parts.size(); ++id) {
            if (!m_parts[id].is_modifier && normal && ((is_looking_forward && m_parts[id].selected) ||
                                                      (!is_looking_forward && !m_parts[id].selected)   ) )
                continue;
            shader->set_uniform("view_model_matrix", view_inst_matrix * model_object()->volumes[id]->get_matrix());
            if (m_parts[id].is_modifier) {
                glsafe(::glEnable(GL_BLEND));
                glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
            }
            m_parts[id].glmodel.set_color(m_parts[id].is_modifier ? MODIFIER_COLOR : (m_parts[id].selected ? UPPER_PART_COLOR : LOWER_PART_COLOR));
            m_parts[id].glmodel.render();
            if (m_parts[id].is_modifier)
                glsafe(::glDisable(GL_BLEND));
        }
        shader->stop_using();
    }
    // { // Debugging render:
    //     static int idx = -1;
    //     ImGui::Begin("DEBUG");
    //     for (int i=0; i<m_parts.size(); ++i)
    //         if (ImGui::Button(std::to_string(i).c_str()))
    //             idx = i;
    //     if (idx >= m_parts.size())
    //         idx = -1;
    //     ImGui::End();
    //     ::glDisable(GL_DEPTH_TEST);
    //     if (valid()) {
    //         for (size_t i=0; i<m_contour_points.size(); ++i) {
    //             const Vec3d& pt = m_contour_points[i];
    //             ColorRGBA col = ColorRGBA::GREEN();
    //             bool red = false;
    //             bool yellow = false;
    //             for (size_t j=0; j<m_contour_to_parts[i].first.size(); ++j) {
    //                 red |= m_parts[m_contour_to_parts[i].first[j]].selected;
    //                 yellow |= m_parts[m_contour_to_parts[i].second[j]].selected;
    //             }
    //             if (red)
    //                 col = ColorRGBA::RED();
    //             if (yellow)
    //                 col = ColorRGBA::YELLOW();
    //             GLGizmoCut3D::render_model(sphere_model, col, camera.get_view_matrix() * translation_transform(pt));
    //         }
    //     }
    //     if (idx != -1) {
    //         render_model(m_parts[idx].glmodel, ColorRGBA::RED(), camera.get_view_matrix());
    //         for (const Vec3d& pt : m_debug_pts[idx]) {
    //             render_model(sphere_model, ColorRGBA::GREEN(), camera.get_view_matrix() * translation_transform(pt));
    //         }
    //     }
    //     ::glEnable(GL_DEPTH_TEST);
    // }
}
References Slic3r::GUI::Camera::get_dir_forward(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), glsafe, Slic3r::GUI::GLGizmoCut3D::is_looking_forward(), Slic3r::GUI::LOWER_PART_COLOR, Slic3r::GUI::MODIFIER_COLOR, Slic3r::Geometry::translation_transform(), and Slic3r::GUI::UPPER_PART_COLOR.
Referenced by Slic3r::GUI::GLGizmoCut3D::on_render().
toggle_selection()
void Slic3r::GUI::GLGizmoCut3D::PartSelection::toggle_selection (const Vec2d & mouse_pos)
{
    // FIXME: Cache the transforms.
    const Camera& camera     = wxGetApp().plater()->get_camera();
    const Vec3d&  camera_pos = camera.get_position();
    Vec3f pos;
    Vec3f normal;
    std::vector<std::pair<size_t, double>> hits_id_and_sqdist;
    for (size_t id=0; id<m_parts.size(); ++id) {
//        const Vec3d volume_offset = model_object()->volumes[id]->get_offset();
        Transform3d tr = translation_transform(model_object()->instances[m_instance_idx]->get_offset()) * translation_transform(model_object()->volumes[id]->get_offset());
        if (m_parts[id].raycaster.unproject_on_mesh(mouse_pos, tr, camera, pos, normal)) {
            hits_id_and_sqdist.emplace_back(id, (camera_pos - tr*(pos.cast<double>())).squaredNorm());
        }
    }
    if (! hits_id_and_sqdist.empty()) {
        size_t id = std::min_element(hits_id_and_sqdist.begin(), hits_id_and_sqdist.end(),
            [](const std::pair<size_t, double>& a, const std::pair<size_t, double>& b) { return a.second < b.second; })->first;
        m_parts[id].selected = ! m_parts[id].selected;
        // And now recalculate the contours which should be ignored.
        m_ignored_contours.clear();
        size_t cont_id = 0;
        for (const auto& [parts_above, parts_below] : m_contour_to_parts) {
            for (size_t upper : parts_above) {
                bool upper_sel = m_parts[upper].selected;
                if (std::find_if(parts_below.begin(), parts_below.end(), [this, &upper_sel](const size_t& i) { return m_parts[i].selected == upper_sel; }) != parts_below.end()) {
                    m_ignored_contours.emplace_back(cont_id);
                    break;
                }
            }
            ++cont_id;
        }
    }
}
References Slic3r::GUI::Camera::get_position(), and Slic3r::Geometry::translation_transform().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_mouse().
turn_over_selection()
void Slic3r::GUI::GLGizmoCut3D::PartSelection::turn_over_selection ()
{
    for (Part& part : m_parts)
        part.selected = !part.selected;
}
Referenced by Slic3r::GUI::GLGizmoCut3D::flip_cut_plane().
valid()
bool Slic3r::GUI::GLGizmoCut3D::PartSelection::valid () const inline
{ return m_valid; }
References m_valid.
Referenced by Slic3r::GUI::GLGizmoCut3D::can_perform_cut(), get_ignored_contours_ptr(), Slic3r::GUI::GLGizmoCut3D::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), and Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane().
Member Data Documentation
m_contour_points
std::vector<Vec3d> Slic3r::GUI::GLGizmoCut3D::PartSelection::m_contour_points private
Referenced by PartSelection().
m_contour_to_parts
std::vector<std::pair<std::vector<size_t>, std::vector<size_t> > > Slic3r::GUI::GLGizmoCut3D::PartSelection::m_contour_to_parts private
Referenced by PartSelection().
m_debug_pts
std::vector<std::vector<Vec3d> > Slic3r::GUI::GLGizmoCut3D::PartSelection::m_debug_pts private
Referenced by PartSelection().
m_ignored_contours
std::vector<size_t> Slic3r::GUI::GLGizmoCut3D::PartSelection::m_ignored_contours private
Referenced by get_ignored_contours_ptr().
m_instance_idx
int Slic3r::GUI::GLGizmoCut3D::PartSelection::m_instance_idx private
Referenced by PartSelection().
m_model
Model Slic3r::GUI::GLGizmoCut3D::PartSelection::m_model private
Referenced by PartSelection(), ~PartSelection(), and model_object().
m_parts
std::vector<Part> Slic3r::GUI::GLGizmoCut3D::PartSelection::m_parts private
Referenced by PartSelection(), and parts().
m_valid
bool Slic3r::GUI::GLGizmoCut3D::PartSelection::m_valid = false private
Referenced by PartSelection(), and valid().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoCut.hpp
src/slic3r/GUI/Gizmos/GLGizmoCut.cpp