Prusa Slicer: Slic3r::GUI::Highlighter Class Reference
Slic3r::GUI::Highlighter Class Reference abstract
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
Highlighter ()
~Highlighter ()
void set_timer_owner (wxWindow *owner, int timerid=wxID_ANY)
virtual void bind_timer (wxWindow *owner)=0
bool init (bool input_failed)
void blink ()
void invalidate ()
Private Attributes
int m_blink_counter { 0 }
wxTimer m_timer
Detailed Description
Constructor & Destructor Documentation
Highlighter()
Slic3r::GUI::Highlighter::Highlighter () inline
{}
~Highlighter()
Slic3r::GUI::Highlighter::~Highlighter () inline
{}
Member Function Documentation
bind_timer()
virtual void Slic3r::GUI::Highlighter::bind_timer (wxWindow * owner) pure virtual
Implemented in Slic3r::GUI::HighlighterForWx.
Referenced by set_timer_owner().
blink()
void Slic3r::GUI::Highlighter::blink ()
{
    if ((++m_blink_counter) == 11)
        invalidate();
}
References invalidate(), and m_blink_counter.
Referenced by Slic3r::GUI::HighlighterForWx::blink().
init()
bool Slic3r::GUI::Highlighter::init (bool input_failed)
{
    if (input_failed)
        return false;
    m_timer.Start(300, false);
    return true;
}
References m_timer.
Referenced by Slic3r::GUI::HighlighterForWx::init(), and Slic3r::GUI::HighlighterForWx::init().
invalidate()
void Slic3r::GUI::Highlighter::invalidate ()
{
    if (m_timer.IsRunning())
        m_timer.Stop();
    m_blink_counter = 0;
}
References m_blink_counter, and m_timer.
Referenced by blink(), and Slic3r::GUI::HighlighterForWx::invalidate().
set_timer_owner()
void Slic3r::GUI::Highlighter::set_timer_owner (wxWindow * owner, int timerid = wxID_ANY)
{
    m_timer.SetOwner(owner, timerid);
    bind_timer(owner);
}
References bind_timer(), and m_timer.
Referenced by Slic3r::GUI::PreferencesDialog::PreferencesDialog(), and Slic3r::GUI::Tab::Tab().
Member Data Documentation
m_blink_counter
int Slic3r::GUI::Highlighter::m_blink_counter { 0 } private
Referenced by blink(), and invalidate().
m_timer
wxTimer Slic3r::GUI::Highlighter::m_timer private
Referenced by init(), invalidate(), and set_timer_owner().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp