Prusa Slicer: priv::Limits Struct Reference
priv::Limits Struct Reference
Static Public Member Functions
template<typename T >
static bool apply (std::optional< T > &val, const MinMax< T > &limit)
template<typename T >
static bool apply (T &val, const MinMax< T > &limit)
Public Attributes
MinMax< float > emboss {0.01f, 1e4f}
MinMax< float > size_in_mm {0.1f, 1000.f}
Limit< float > boldness {{-200.f, 200.f}, {-2e4f, 2e4f}}
Limit< float > skew {{-1.f, 1.f}, {-100.f, 100.f}}
MinMax< int > char_gap {-20000, 20000}
MinMax< int > line_gap {-20000, 20000}
MinMax< float > angle {-180.f, 180.f}
Detailed Description
Member Function Documentation
apply() [1/2]
template<typename T > static bool priv::Limits::apply (std::optional< T > & val, const MinMax< T > & limit) inline static
{
        if (val.has_value())
            return apply<T>(*val, limit);
        return false;
    }
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::set_depth(), and Slic3r::GUI::GLGizmoEmboss::set_height().
apply() [2/2]
template<typename T > static bool priv::Limits::apply (T & val, const MinMax< T > & limit) inline static
    {
        if (val > limit.max) {
            val = limit.max;
            return true;
        }
        if (val < limit.min) {
            val = limit.min;
            return true;
        }
        return false;
    }
References priv::MinMax< T >::max, and priv::MinMax< T >::min.
Member Data Documentation
angle
MinMax<float> priv::Limits::angle {-180.f, 180.f}
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_advanced().
boldness
Limit<float> priv::Limits::boldness {{-200.f, 200.f}, {-2e4f, 2e4f}}
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_advanced().
char_gap
MinMax<int> priv::Limits::char_gap {-20000, 20000}
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_advanced().
emboss
MinMax<float> priv::Limits::emboss {0.01f, 1e4f}
line_gap
MinMax<int> priv::Limits::line_gap {-20000, 20000}
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_advanced().
size_in_mm
MinMax<float> priv::Limits::size_in_mm {0.1f, 1000.f}
skew
Limit<float> priv::Limits::skew {{-1.f, 1.f}, {-100.f, 100.f}}
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_advanced().
The documentation for this struct was generated from the following file:
src/slic3r/GUI/Gizmos/GLGizmoEmboss.cpp