Prusa Slicer: Slic3r::GUI::Busy Class Reference
Slic3r::GUI::Busy Class Reference
Public Member Functions
Busy (const wxString &message, wxWindow *parent=nullptr)
~Busy ()
void update (const wxString &message)
void reset ()
Private Attributes
wxWindow * m_parent { nullptr }
std::unique_ptr< wxBusyCursor > m_cursor
std::unique_ptr< wxBusyInfo > m_dlg
Detailed Description
Constructor & Destructor Documentation
Busy()
Slic3r::GUI::Busy::Busy (const wxString & message, wxWindow * parent = nullptr) inline
{
        m_parent = parent;
        m_cursor = std::make_unique<wxBusyCursor>();
        m_dlg = std::make_unique<wxBusyInfo>(message, m_parent);
    }
~Busy()
Slic3r::GUI::Busy::~Busy () inline
{ reset(); }
Member Function Documentation
reset()
void Slic3r::GUI::Busy::reset () inline
                 {
        m_cursor.reset();
        m_dlg.reset();
    }
Referenced by Slic3r::GUI::Plater::priv::reload_from_disk(), and Slic3r::GUI::Plater::priv::replace_volume_with_stl().
update()
void Slic3r::GUI::Busy::update (const wxString & message) inline
{
        // this is ugly but necessary because the call to wxBusyInfo::UpdateLabel() is not working [WX 3.1.4]
        m_dlg = std::make_unique<wxBusyInfo>(message, m_parent);
//        m_dlg->UpdateLabel(message);
    }
Referenced by Slic3r::GUI::Plater::priv::reload_from_disk().
Member Data Documentation
m_cursor
std::unique_ptr<wxBusyCursor> Slic3r::GUI::Busy::m_cursor private
m_dlg
std::unique_ptr<wxBusyInfo> Slic3r::GUI::Busy::m_dlg private
m_parent
wxWindow* Slic3r::GUI::Busy::m_parent { nullptr } private
The documentation for this class was generated from the following file:
src/slic3r/GUI/Plater.cpp