Prusa Slicer: Slic3r::FillPlanePath::InfillPolylineOutput Class Reference
Slic3r::FillPlanePath::InfillPolylineOutput Class Reference
#include <src/libslic3r/Fill/FillPlanePath.hpp>
Public Member Functions
InfillPolylineOutput (const double scale_out)
void reserve (size_t n)
void add_point (const Vec2d &pt)
Points && result ()
virtual bool clips () const
Protected Member Functions
const Point scaled (const Vec2d &fpt) const
Protected Attributes
Points m_out
Private Attributes
double m_scale_out
Detailed Description
Constructor & Destructor Documentation
InfillPolylineOutput()
Slic3r::FillPlanePath::InfillPolylineOutput::InfillPolylineOutput (const double scale_out) inline
: m_scale_out(scale_out) {}
Member Function Documentation
add_point()
void Slic3r::FillPlanePath::InfillPolylineOutput::add_point (const Vec2d & pt) inline
{ m_out.emplace_back(this->scaled(pt)); }
References m_out, and scaled().
clips()
virtual bool Slic3r::FillPlanePath::InfillPolylineOutput::clips () const inline virtual
Reimplemented in Slic3r::InfillPolylineClipper.
{ return false; }
Referenced by Slic3r::FillArchimedeanChords::generate(), Slic3r::FillHilbertCurve::generate(), and Slic3r::FillOctagramSpiral::generate().
reserve()
void Slic3r::FillPlanePath::InfillPolylineOutput::reserve (size_t n) inline
{ m_out.reserve(n); }
References m_out.
result()
Points && Slic3r::FillPlanePath::InfillPolylineOutput::result () inline
{ return std::move(m_out); }
References m_out.
Referenced by Slic3r::FillPlanePath::_fill_surface_single().
scaled()
const Point Slic3r::FillPlanePath::InfillPolylineOutput::scaled (const Vec2d & fpt) const inline protected
{ return { coord_t(floor(fpt.x() * m_scale_out + 0.5)), coord_t(floor(fpt.y() * m_scale_out + 0.5)) }; }
References floor(), and m_scale_out.
Referenced by Slic3r::InfillPolylineClipper::add_point(), and add_point().
Member Data Documentation
m_out
Points Slic3r::FillPlanePath::InfillPolylineOutput::m_out protected
Referenced by Slic3r::InfillPolylineClipper::add_point(), add_point(), reserve(), Slic3r::InfillPolylineClipper::result(), and result().
m_scale_out
double Slic3r::FillPlanePath::InfillPolylineOutput::m_scale_out private
Referenced by scaled().
The documentation for this class was generated from the following file:
src/libslic3r/Fill/FillPlanePath.hpp