Prusa Slicer: Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type > Struct Template Reference
#include <src/eigen/Eigen/src/Core/ProductEvaluators.h>
Public Types
typedef Product< Lhs, Rhs, Options > SrcXprType
Static Public Member Functions
static EIGEN_STRONG_INLINE void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< Scalar, Scalar > &)
Detailed Description
template<typename DstXprType, typename Lhs, typename Rhs, int Options, typename Scalar>
struct Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >
Member Typedef Documentation
SrcXprType
template<typename DstXprType , typename Lhs , typename Rhs , int Options, typename Scalar > typedef Product<Lhs,Rhs,Options> Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::SrcXprType
Member Function Documentation
run()
template<typename DstXprType , typename Lhs , typename Rhs , int Options, typename Scalar > static EIGEN_STRONG_INLINE void Eigen::internal::Assignment< DstXprType, Product< Lhs, Rhs, Options >, internal::assign_op< Scalar, Scalar >, Dense2Dense, typename enable_if<(Options==DefaultProduct||Options==AliasFreeProduct)>::type >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< Scalar, Scalar > &) inline static
  {
    Index dstRows = src.rows();
    Index dstCols = src.cols();
    if((dst.rows()!=dstRows) || (dst.cols()!=dstCols))
      dst.resize(dstRows, dstCols);
    // FIXME shall we handle nested_eval here?
    generic_product_impl<Lhs, Rhs>::evalTo(dst, src.lhs(), src.rhs());
  }
References Eigen::Product< _Lhs, _Rhs, Option >::cols(), Eigen::Product< _Lhs, _Rhs, Option >::lhs(), Eigen::Product< _Lhs, _Rhs, Option >::rhs(), and Eigen::Product< _Lhs, _Rhs, Option >::rows().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/ProductEvaluators.h