Prusa Slicer: agg::pod_array< T > Class Template Reference
agg::pod_array< T > Class Template Reference
#include <src/agg/agg_array.h>
Public Types
typedef T value_type
typedef pod_array< T > self_type
Public Member Functions
~pod_array ()
pod_array ()
pod_array (unsigned size)
pod_array (const self_type &v)
void resize (unsigned size)
const self_type & operator= (const self_type &v)
unsigned size () const
const T & operator[] (unsigned i) const
T & operator[] (unsigned i)
const T & at (unsigned i) const
T & at (unsigned i)
T value_at (unsigned i) const
const T * data () const
T * data ()
Private Attributes
T * m_array
unsigned m_size
Detailed Description
template<class T>
class agg::pod_array< T >
Member Typedef Documentation
self_type
template<class T > typedef pod_array<T> agg::pod_array< T >::self_type
value_type
template<class T > typedef T agg::pod_array< T >::value_type
Constructor & Destructor Documentation
~pod_array()
template<class T > agg::pod_array< T >::~pod_array () inline
{ pod_allocator<T>::deallocate(m_array, m_size); }
References agg::pod_allocator< T >::deallocate(), agg::pod_array< T >::m_array, and agg::pod_array< T >::m_size.
pod_array() [1/3]
template<class T > agg::pod_array< T >::pod_array () inline
: m_array(0), m_size(0) {}
pod_array() [2/3]
template<class T > agg::pod_array< T >::pod_array (unsigned size) inline
                                 :
            m_array(pod_allocator<T>::allocate(size)),
            m_size(size)
        {}
pod_array() [3/3]
template<class T > agg::pod_array< T >::pod_array (const self_type & v) inline
                                      :
            m_array(pod_allocator<T>::allocate(v.m_size)),
            m_size(v.m_size)
        {
            memcpy(m_array, v.m_array, sizeof(T) * m_size);
        }
References agg::pod_array< T >::m_array, and agg::pod_array< T >::m_size.
Member Function Documentation
at() [1/2]
template<class T > T & agg::pod_array< T >::at (unsigned i) inline
{ return m_array[i]; }
References agg::pod_array< T >::m_array.
at() [2/2]
template<class T > const T & agg::pod_array< T >::at (unsigned i) const inline
{ return m_array[i]; }
References agg::pod_array< T >::m_array.
data() [1/2]
template<class T > T * agg::pod_array< T >::data () inline
{ return m_array; }
References agg::pod_array< T >::m_array.
data() [2/2]
template<class T > const T * agg::pod_array< T >::data () const inline
{ return m_array; }
References agg::pod_array< T >::m_array.
operator=()
template<class T > const self_type & agg::pod_array< T >::operator= (const self_type & v) inline
        {
            resize(v.size());
            memcpy(m_array, v.m_array, sizeof(T) * m_size);
            return *this;
        }
References agg::pod_array< T >::m_array, agg::pod_array< T >::m_size, agg::pod_array< T >::resize(), and agg::pod_array< T >::size().
operator[]() [1/2]
template<class T > T & agg::pod_array< T >::operator[] (unsigned i) inline
{ return m_array[i]; }
References agg::pod_array< T >::m_array.
operator[]() [2/2]
template<class T > const T & agg::pod_array< T >::operator[] (unsigned i) const inline
{ return m_array[i]; }
References agg::pod_array< T >::m_array.
resize()
template<class T > void agg::pod_array< T >::resize (unsigned size) inline
        {
            if(size != m_size)
            {
                pod_allocator<T>::deallocate(m_array, m_size);
                m_array = pod_allocator<T>::allocate(m_size = size);
            }
        }
References agg::pod_allocator< T >::allocate(), agg::pod_allocator< T >::deallocate(), agg::pod_array< T >::m_array, agg::pod_array< T >::m_size, and agg::pod_array< T >::size().
Referenced by agg::row_ptr_cache< T >::attach(), agg::pod_array< T >::operator=(), agg::scanline_p8::reset(), and agg::scanline32_p8::reset().
size()
template<class T > unsigned agg::pod_array< T >::size () const inline
{ return m_size; }
References agg::pod_array< T >::m_size.
Referenced by agg::row_ptr_cache< T >::attach(), agg::pod_array< T >::operator=(), agg::scanline32_p8::reset(), and agg::pod_array< T >::resize().
value_at()
template<class T > T agg::pod_array< T >::value_at (unsigned i) const inline
{ return m_array[i]; }
References agg::pod_array< T >::m_array.
Member Data Documentation
m_array
template<class T > T* agg::pod_array< T >::m_array private
Referenced by agg::pod_array< T >::pod_array(), agg::pod_array< T >::~pod_array(), agg::pod_array< T >::at(), agg::pod_array< T >::at(), agg::pod_array< T >::data(), agg::pod_array< T >::data(), agg::pod_array< T >::operator=(), agg::pod_array< T >::operator[](), agg::pod_array< T >::operator[](), agg::pod_array< T >::resize(), and agg::pod_array< T >::value_at().
m_size
template<class T > unsigned agg::pod_array< T >::m_size private
Referenced by agg::pod_array< T >::pod_array(), agg::pod_array< T >::~pod_array(), agg::pod_array< T >::operator=(), agg::pod_array< T >::resize(), and agg::pod_array< T >::size().
The documentation for this class was generated from the following file:
src/agg/agg_array.h