Prusa Slicer: Slic3r::client Namespace Reference
Slic3r::client Namespace Reference
Classes
struct ascii_char_skipper_parser
struct expr
struct FactorActions
struct InterpolateTableContext
struct macro_processor
struct MyContext
struct OptWithPos
struct strict_real_policies_without_nan_inf
struct utf8_char_parser
Typedefs
using Iterator = std::string::const_iterator
using IteratorRange = boost::iterator_range< Iterator >
using skipper = ascii_char_skipper_parser
Functions
std::ostream & operator<< (std::ostream &os, OptWithPos const &opt)
std::ostream & operator<< (std::ostream &os, const expr &expression)
std::ostream & operator<< (std::ostream &os, const InterpolateTableContext &table_context)
std::ostream & operator<< (std::ostream &os, const IteratorRange &it_range)
Typedef Documentation
Iterator
using Slic3r::client::Iterator = typedef std::string::const_iterator
IteratorRange
using Slic3r::client::IteratorRange = typedef boost::iterator_range<Iterator>
skipper
using Slic3r::client::skipper = typedef ascii_char_skipper_parser
Function Documentation
operator<<() [1/4]
std::ostream & Slic3r::client::operator<< (std::ostream & os, const expr & expression)
    {
        typedef expr Expr;
        os << std::string(expression.it_range.begin(), expression.it_range.end()) << " - ";
        switch (expression.type()) {
        case Expr::TYPE_EMPTY:    os << "empty"; break;
        case Expr::TYPE_BOOL:     os << "bool ("   << expression.b() << ")"; break;
        case Expr::TYPE_INT:      os << "int ("    << expression.i() << ")"; break;
        case Expr::TYPE_DOUBLE:   os << "double (" << expression.d() << ")"; break;
        case Expr::TYPE_STRING:   os << "string (" << expression.s() << ")"; break;
        default: os << "unknown";
        };
        return os;
    }
References Slic3r::client::expr::b(), Slic3r::client::expr::d(), Slic3r::client::expr::i(), Slic3r::client::expr::it_range, Slic3r::client::expr::s(), and Slic3r::client::expr::type().
operator<<() [2/4]
std::ostream & Slic3r::client::operator<< (std::ostream & os, const InterpolateTableContext & table_context)
    {
        for (const auto &item : table_context.table)
            os << "(" << item.x << "," << item.y << ")";
        return os;
    }
References Slic3r::client::InterpolateTableContext::table.
operator<<() [3/4]
std::ostream & Slic3r::client::operator<< (std::ostream & os, const IteratorRange & it_range)
    {
        os << std::string(it_range.begin(), it_range.end());
        return os;
    }
operator<<() [4/4]
std::ostream & Slic3r::client::operator<< (std::ostream & os, OptWithPos const & opt)
    {
        os << std::string(opt.it_range.begin(), opt.it_range.end());
        return os;
    }
References Slic3r::client::OptWithPos::it_range.