Prusa Slicer: Slic3r::GUI::PresetForPrinter Class Reference
Slic3r::GUI::PresetForPrinter Class Reference
#include <src/slic3r/GUI/PhysicalPrinterDialog.hpp>
Public Member Functions
PresetForPrinter (PhysicalPrinterDialog *parent, const std::string &preset_name="")
~PresetForPrinter ()
wxBoxSizer * sizer ()
void update_full_printer_name ()
std::string get_preset_name ()
void SuppressDelete ()
void AllowDelete ()
void on_sys_color_changed ()
Private Member Functions
void DeletePreset (wxEvent &event)
Private Attributes
PhysicalPrinterDialog * m_parent { nullptr }
PresetComboBox * m_presets_list { nullptr }
ScalableButton * m_delete_preset_btn { nullptr }
wxStaticText * m_info_line { nullptr }
wxStaticText * m_full_printer_name { nullptr }
wxBoxSizer * m_sizer { nullptr }
Detailed Description
Constructor & Destructor Documentation
PresetForPrinter()
Slic3r::GUI::PresetForPrinter::PresetForPrinter (PhysicalPrinterDialog * parent, const std::string & preset_name = "")
                                                                                              :
    m_parent(parent)
{
    m_sizer = new wxBoxSizer(wxVERTICAL);
    m_delete_preset_btn = new ScalableButton(parent, wxID_ANY, "cross");
    m_delete_preset_btn->SetFont(wxGetApp().normal_font());
    m_delete_preset_btn->SetToolTip(_L("Delete this preset from this printer device"));
    m_delete_preset_btn->Bind(wxEVT_BUTTON, &PresetForPrinter::DeletePreset, this);
    m_presets_list = new PresetComboBox(parent, Preset::TYPE_PRINTER);
    m_presets_list->set_printer_technology(parent->get_printer_technology());
    m_presets_list->set_selection_changed_function([this](int selection) {
        std::string selected_string = Preset::remove_suffix_modified(m_presets_list->GetString(selection).ToUTF8().data());
        Preset* preset = wxGetApp().preset_bundle->printers.find_preset(selected_string);
        assert(preset);
        Preset& edited_preset = wxGetApp().preset_bundle->printers.get_edited_preset();
        if (preset->name == edited_preset.name)
            preset = &edited_preset;
        // if created physical printer doesn't have any settings, use the settings from the selected preset
        if (m_parent->get_printer()->has_empty_config()) {
            // update Print Host upload from the selected preset
            m_parent->get_printer()->update_from_preset(*preset);
            // update values in parent (PhysicalPrinterDialog)
        }
        // update PrinterTechnology if it was changed
        if (m_presets_list->set_printer_technology(preset->printer_technology()))
            m_parent->set_printer_technology(preset->printer_technology());
        else
            m_parent->update(true);
        update_full_printer_name();
    });
    m_presets_list->update(preset_name);
    m_info_line = new wxStaticText(parent, wxID_ANY, _L("This printer will be shown in the presets list as") + ":");
    m_full_printer_name = new wxStaticText(parent, wxID_ANY, "");
    m_full_printer_name->SetFont(wxGetApp().bold_font());
    wxBoxSizer* preset_sizer = new wxBoxSizer(wxHORIZONTAL);
    preset_sizer->Add(m_presets_list        , 1, wxEXPAND);
    preset_sizer->Add(m_delete_preset_btn   , 0, wxEXPAND | wxLEFT, BORDER_W);
    wxBoxSizer* name_sizer = new wxBoxSizer(wxHORIZONTAL);
    name_sizer->Add(m_info_line, 0, wxEXPAND);
    name_sizer->Add(m_full_printer_name, 0, wxEXPAND | wxLEFT, BORDER_W);
    m_sizer->Add(preset_sizer   , 0, wxEXPAND);
    m_sizer->Add(name_sizer, 0, wxEXPAND);
}
References _L, Slic3r::GUI::BORDER_W, DeletePreset(), Slic3r::GUI::PhysicalPrinterDialog::get_printer(), Slic3r::GUI::PhysicalPrinterDialog::get_printer_technology(), Slic3r::PhysicalPrinter::has_empty_config(), m_delete_preset_btn, m_full_printer_name, m_info_line, m_parent, m_presets_list, m_sizer, Slic3r::Preset::name, Slic3r::Preset::printer_technology(), Slic3r::Preset::remove_suffix_modified(), Slic3r::GUI::PhysicalPrinterDialog::set_printer_technology(), Slic3r::GUI::PresetComboBox::set_printer_technology(), Slic3r::GUI::PresetComboBox::set_selection_changed_function(), Slic3r::Preset::TYPE_PRINTER, Slic3r::GUI::PhysicalPrinterDialog::update(), Slic3r::GUI::PresetComboBox::update(), Slic3r::PhysicalPrinter::update_from_preset(), update_full_printer_name(), and wxEVT_BUTTON.
~PresetForPrinter()
Slic3r::GUI::PresetForPrinter::~PresetForPrinter ()
{
    m_presets_list->Destroy();
    m_delete_preset_btn->Destroy();
    m_info_line->Destroy();
    m_full_printer_name->Destroy();
}
References m_delete_preset_btn, m_full_printer_name, m_info_line, and m_presets_list.
Member Function Documentation
AllowDelete()
void Slic3r::GUI::PresetForPrinter::AllowDelete ()
{
    if (!m_delete_preset_btn->IsEnabled())
        m_delete_preset_btn->Enable();
    m_presets_list->set_printer_technology(m_parent->get_printer_technology());
    m_presets_list->update();
}
References Slic3r::GUI::PhysicalPrinterDialog::get_printer_technology(), m_delete_preset_btn, m_parent, m_presets_list, Slic3r::GUI::PresetComboBox::set_printer_technology(), and Slic3r::GUI::PresetComboBox::update().
DeletePreset()
void Slic3r::GUI::PresetForPrinter::DeletePreset (wxEvent & event) private
{
    m_parent->DeletePreset(this);
}
References Slic3r::GUI::PhysicalPrinterDialog::DeletePreset(), and m_parent.
Referenced by PresetForPrinter().
get_preset_name()
std::string Slic3r::GUI::PresetForPrinter::get_preset_name ()
{
    return into_u8(m_presets_list->GetString(m_presets_list->GetSelection()));
}
References Slic3r::GUI::into_u8(), and m_presets_list.
on_sys_color_changed()
void Slic3r::GUI::PresetForPrinter::on_sys_color_changed ()
{
    m_presets_list->sys_color_changed();
    m_delete_preset_btn->sys_color_changed();
}
References m_delete_preset_btn, m_presets_list, Slic3r::GUI::PresetComboBox::sys_color_changed(), and ScalableButton::sys_color_changed().
sizer()
wxBoxSizer * Slic3r::GUI::PresetForPrinter::sizer () inline
{ return m_sizer; }
References m_sizer.
SuppressDelete()
void Slic3r::GUI::PresetForPrinter::SuppressDelete ()
{
    m_delete_preset_btn->Enable(false);
    // this case means that now we have only one related preset for the printer
    // So, allow any selection
    m_presets_list->set_printer_technology(ptAny);
    m_presets_list->update();
}
References m_delete_preset_btn, m_presets_list, Slic3r::ptAny, Slic3r::GUI::PresetComboBox::set_printer_technology(), and Slic3r::GUI::PresetComboBox::update().
update_full_printer_name()
void Slic3r::GUI::PresetForPrinter::update_full_printer_name ()
{
    wxString printer_name   = m_parent->get_printer_name();
    wxString preset_name    = m_presets_list->GetString(m_presets_list->GetSelection());
    m_full_printer_name->SetLabelText(printer_name + from_u8(PhysicalPrinter::separator()) + preset_name);
}
References Slic3r::GUI::from_u8(), Slic3r::GUI::PhysicalPrinterDialog::get_printer_name(), m_full_printer_name, m_parent, m_presets_list, and Slic3r::PhysicalPrinter::separator().
Referenced by PresetForPrinter().
Member Data Documentation
m_delete_preset_btn
ScalableButton* Slic3r::GUI::PresetForPrinter::m_delete_preset_btn { nullptr } private
Referenced by PresetForPrinter(), ~PresetForPrinter(), AllowDelete(), on_sys_color_changed(), and SuppressDelete().
m_full_printer_name
wxStaticText* Slic3r::GUI::PresetForPrinter::m_full_printer_name { nullptr } private
Referenced by PresetForPrinter(), ~PresetForPrinter(), and update_full_printer_name().
m_info_line
wxStaticText* Slic3r::GUI::PresetForPrinter::m_info_line { nullptr } private
Referenced by PresetForPrinter(), and ~PresetForPrinter().
m_parent
PhysicalPrinterDialog* Slic3r::GUI::PresetForPrinter::m_parent { nullptr } private
Referenced by PresetForPrinter(), AllowDelete(), DeletePreset(), and update_full_printer_name().
m_presets_list
PresetComboBox* Slic3r::GUI::PresetForPrinter::m_presets_list { nullptr } private
Referenced by PresetForPrinter(), ~PresetForPrinter(), AllowDelete(), get_preset_name(), on_sys_color_changed(), SuppressDelete(), and update_full_printer_name().
m_sizer
wxBoxSizer* Slic3r::GUI::PresetForPrinter::m_sizer { nullptr } private
Referenced by PresetForPrinter(), and sizer().
The documentation for this class was generated from the following files:
src/slic3r/GUI/PhysicalPrinterDialog.hpp
src/slic3r/GUI/PhysicalPrinterDialog.cpp