Prusa Slicer: Eigen::SparseCompressedBase< Derived > Class Template Reference
Eigen::SparseCompressedBase< Derived > Class Template Reference
Common base class for sparse [compressed]-{row|column}-storage format.
#include <src/eigen/Eigen/src/SparseCore/SparseCompressedBase.h>
Classes
class InnerIterator
class ReverseInnerIterator
Public Types
typedef SparseMatrixBase< Derived > Base
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime , MaxRowsAtCompileTime = RowsAtCompileTime ,
MaxColsAtCompileTime = ColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1 , Flags = internal::traits<Derived>::Flags ,
IsRowMajor = Flags&RowMajorBit ? 1 : 0 , InnerSizeAtCompileTime , _HasDirectAccess = (int(Flags)&DirectAccessBit) ? 1 : 0
}
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typenameinternal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< constDerived > >, Transpose< constDerived > >::type AdjointReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const< Transpose< constDerived > >::type ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional< _HasDirectAccess, constScalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef Block< Derived, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > InnerVectorReturnType
typedef Block< const Derived, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > ConstInnerVectorReturnType
typedef Block< Derived, Dynamic, Dynamic, true > InnerVectorsReturnType
typedef Block< const Derived, Dynamic, Dynamic, true > ConstInnerVectorsReturnType
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
Index nonZeros () const
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
bool isCompressed () const
const Map< const Array< Scalar, Dynamic, 1 > > coeffs () const
Map< Array< Scalar, Dynamic, 1 > > coeffs ()
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator= (const Derived &other)
const Derived & derived () const
Derived & derived ()
Derived & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Derived & markAsRValue ()
template<typename OtherDerived >
Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator*= (const Scalar &other)
template<typename OtherDerived >
Derived & operator*= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator/= (const Scalar &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE const SparseMatrixBase< Derived >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Derived, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
template<int Mode>
const TriangularView< const Derived, Mode > triangularView () const
template<unsigned int UpLo>
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<typename OtherDerived >
Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
InnerVectorReturnType innerVector (Index outer)
const ConstInnerVectorReturnType innerVector (Index outer) const
InnerVectorsReturnType innerVectors (Index outerStart, Index outerSize)
const ConstInnerVectorsReturnType innerVectors (Index outerStart, Index outerSize) const
DenseMatrixType toDense () const
template<typename OtherDerived >
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Derived >::type eval () const
Scalar sum () const
const SparseView< Derived > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Types
typedef Base::IndexVector IndexVector
Protected Member Functions
Eigen::Map< IndexVector > innerNonZeros ()
const Eigen::Map< const IndexVector > innerNonZeros () const
SparseCompressedBase ()
template<typename OtherDerived >
Derived & assign (const OtherDerived &other)
template<typename OtherDerived >
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions
static StorageIndex convert_index (const Index idx)
Protected Attributes
bool m_isRValue
Private Member Functions
template<typename OtherDerived >
SparseCompressedBase (const SparseCompressedBase< OtherDerived > &)
template<typename Dest >
void evalTo (Dest &) const
Detailed Description
template<typename Derived>
class Eigen::SparseCompressedBase< Derived >
Common base class for sparse [compressed]-{row|column}-storage format.
This class defines the common interface for all derived classes implementing the compressed sparse storage format, such as:
SparseMatrix
Ref<SparseMatrixType,Options>
Map<SparseMatrixType>
Member Typedef Documentation
AdjointReturnType
template<typename Derived > typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,Eigen::Transpose<constDerived>>,Transpose<constDerived>>::type Eigen::SparseMatrixBase< Derived >::AdjointReturnType inherited
Base
template<typename Derived > typedef SparseMatrixBase<Derived> Eigen::SparseCompressedBase< Derived >::Base
CoeffReturnType
template<typename Derived > typedef internal::conditional<_HasDirectAccess,constScalar&,Scalar>::type Eigen::SparseMatrixBase< Derived >::CoeffReturnType inherited
ConstantReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,Matrix<Scalar,Dynamic,Dynamic> > Eigen::SparseMatrixBase< Derived >::ConstantReturnType inherited
ConstInnerVectorReturnType
template<typename Derived > typedef Block<const Derived,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Derived >::ConstInnerVectorReturnType inherited
ConstInnerVectorsReturnType
template<typename Derived > typedef Block<const Derived,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Derived >::ConstInnerVectorsReturnType inherited
ConstTransposeReturnType
template<typename Derived > typedef internal::add_const<Transpose<constDerived>>::type Eigen::SparseMatrixBase< Derived >::ConstTransposeReturnType inherited
DenseMatrixType
template<typename Derived > typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime> Eigen::SparseMatrixBase< Derived >::DenseMatrixType inherited
type of the equivalent dense matrix
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
IndexVector
template<typename Derived > typedef Base::IndexVector Eigen::SparseCompressedBase< Derived >::IndexVector protected
InnerVectorReturnType
template<typename Derived > typedef Block<Derived,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Derived >::InnerVectorReturnType inherited
InnerVectorsReturnType
template<typename Derived > typedef Block<Derived,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Derived >::InnerVectorsReturnType inherited
PacketReturnType
template<typename Derived > typedef internal::add_const_on_value_type_if_arithmetic<typenameinternal::packet_traits<Scalar>::type>::type Eigen::SparseMatrixBase< Derived >::PacketReturnType inherited
PacketScalar
template<typename Derived > typedef internal::packet_traits<Scalar>::type Eigen::SparseMatrixBase< Derived >::PacketScalar inherited
PlainObject
template<typename Derived > typedef SparseMatrix<Scalar, Flags&RowMajorBit ? RowMajor : ColMajor, StorageIndex> Eigen::SparseMatrixBase< Derived >::PlainObject inherited
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::SparseMatrixBase< Derived >::RealScalar inherited
This is the "real scalar" type; if the Scalar type is already real numbers (e.g. int, float or double) then RealScalar is just the same as Scalar. If Scalar is std::complex<T> then RealScalar is T.
See also
class NumTraits
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::Scalar inherited
ScalarVector
template<typename Derived > typedef Matrix<Scalar,Dynamic,1> Eigen::SparseMatrixBase< Derived >::ScalarVector inherited
SquareMatrixType
template<typename Derived > typedef Matrix<Scalar,EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime)> Eigen::SparseMatrixBase< Derived >::SquareMatrixType inherited
type of the equivalent square matrix
StorageBaseType
template<typename Derived > typedef SparseMatrixBase Eigen::SparseMatrixBase< Derived >::StorageBaseType inherited
StorageIndex
template<typename Derived > typedef internal::traits<Derived>::StorageIndex Eigen::SparseMatrixBase< Derived >::StorageIndex inherited
The integer type used to store indices within a SparseMatrix. For a SparseMatrix<Scalar,Options,IndexType> it an alias of the third template parameter IndexType.
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::SparseMatrixBase< Derived >::StorageKind inherited
TransposeReturnType
template<typename Derived > typedef Transpose<Derived> Eigen::SparseMatrixBase< Derived >::TransposeReturnType inherited
value_type
template<typename Derived > typedef Scalar Eigen::SparseMatrixBase< Derived >::value_type inherited
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxSizeAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
InnerSizeAtCompileTime
_HasDirectAccess
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = RowsAtCompileTime,
      MaxColsAtCompileTime = ColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<MaxRowsAtCompileTime,
                                                      MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1,
      Flags = internal::traits<Derived>::Flags,
      IsRowMajor = Flags&RowMajorBit ? 1 : 0,
      InnerSizeAtCompileTime = int(IsVectorAtCompileTime) ? int(SizeAtCompileTime)
                             : int(IsRowMajor) ? int(ColsAtCompileTime) : int(RowsAtCompileTime),
      #ifndef EIGEN_PARSED_BY_DOXYGEN
      _HasDirectAccess = (int(Flags)&DirectAccessBit) ? 1 : 0 // workaround sunCC
      #endif
    };
Constructor & Destructor Documentation
SparseCompressedBase() [1/2]
template<typename Derived > Eigen::SparseCompressedBase< Derived >::SparseCompressedBase () inline protected
Default constructor. Do nothing.
{}
SparseCompressedBase() [2/2]
template<typename Derived > template<typename OtherDerived > Eigen::SparseCompressedBase< Derived >::SparseCompressedBase (const SparseCompressedBase< OtherDerived > &) explicit private
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
template<typename Derived > const AdjointReturnType Eigen::SparseMatrixBase< Derived >::adjoint () const inline inherited
{ return AdjointReturnType(transpose()); }
References Eigen::SparseMatrixBase< Derived >::transpose().
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl(), and Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rankUpdate().
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
assign()
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::assign (const OtherDerived & other) inline protected inherited
assignGeneric()
template<typename Derived > template<typename OtherDerived > void Eigen::SparseMatrixBase< Derived >::assignGeneric (const OtherDerived & other) inline protected inherited
blueNorm()
template<typename Derived > NumTraits< typenameinternal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::blueNorm inline inherited
{
  return internal::blueNorm_impl(*this);
}
References Eigen::internal::blueNorm_impl().
coeffs() [1/2]
template<typename Derived > Map< Array< Scalar, Dynamic, 1 > > Eigen::SparseCompressedBase< Derived >::coeffs () inline
Returns
a read-write view of the stored coefficients as a 1D array expression
Warning
this method is for compressed storage only, and it will trigger an assertion otherwise.
Here is an example:
and the output is:
See also
valuePtr(), isCompressed()
{ eigen_assert(isCompressed()); return Array<Scalar,Dynamic,1>::Map(valuePtr(),nonZeros()); }
References Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Eigen::Map, eigen_assert, Eigen::SparseCompressedBase< Derived >::isCompressed(), Eigen::SparseCompressedBase< Derived >::nonZeros(), and Eigen::SparseCompressedBase< Derived >::valuePtr().
coeffs() [2/2]
template<typename Derived > const Map< const Array< Scalar, Dynamic, 1 > > Eigen::SparseCompressedBase< Derived >::coeffs () const inline
Returns
a read-only view of the stored coefficients as a 1D array expression.
Warning
this method is for compressed storage only, and it will trigger an assertion otherwise.
See also
valuePtr(), isCompressed()
{ eigen_assert(isCompressed()); return Array<Scalar,Dynamic,1>::Map(valuePtr(),nonZeros()); }
References Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Eigen::Map, eigen_assert, Eigen::SparseCompressedBase< Derived >::isCompressed(), Eigen::SparseCompressedBase< Derived >::nonZeros(), and Eigen::SparseCompressedBase< Derived >::valuePtr().
cols()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::cols () const inline inherited
Returns
the number of columns.
See also
rows()
{ return derived().cols(); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseMatrixBase< Derived >::innerSize(), Eigen::SparseMatrixBase< Derived >::isVector(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrixBase< Derived >::outerSize(), and Eigen::SparseMatrixBase< Derived >::size().
const_cast_derived()
template<typename Derived > Derived & Eigen::SparseMatrixBase< Derived >::const_cast_derived () const inline inherited
    { return *static_cast<Derived*>(const_cast<SparseMatrixBase*>(this)); }
Referenced by Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator SparseMatrixType &(), Eigen::internal::evaluator< SparseVector< _Scalar, _Options, _Index > >::operator SparseVectorType &(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::viewAsCholmod(), and Eigen::viewAsCholmod().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
convert_index()
template<typename Derived > static StorageIndex Eigen::SparseMatrixBase< Derived >::convert_index (const Index idx) inline static protected inherited
{
      return internal::convert_index<StorageIndex>(idx);
    }
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize().
cwiseProduct() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE const SparseMatrixBase< Derived >::template CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
{
  return typename CwiseProductDenseReturnType<OtherDerived>::Type(derived(), other.derived());
}
cwiseProduct() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
Referenced by Eigen::MatrixBase< Derived >::cwiseProduct().
derived() [1/2]
template<typename Derived > Derived & Eigen::SparseMatrixBase< Derived >::derived () inline inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
template<typename Derived > const Derived & Eigen::SparseMatrixBase< Derived >::derived () const inline inherited
{ return *static_cast<const Derived*>(this); }
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), Eigen::Ref< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector(), Eigen::IterativeSolverBase< Derived >::_solve_impl(), Eigen::SparseSolverBase< Derived >::_solve_impl(), Eigen::CholmodBase< _MatrixType, _UpLo, Derived >::_solve_impl(), Eigen::SparseMatrixBase< Derived >::cols(), Eigen::SparseMatrixBase< Derived >::dot(), Eigen::SparseMatrixBase< Derived >::eval(), Eigen::SparseCompressedBase< Derived >::innerIndexPtr(), Eigen::SparseCompressedBase< Derived >::innerIndexPtr(), Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), Eigen::SparseMatrixBase< Derived >::isApprox(), Eigen::SluMatrix::Map(), Eigen::SparseMatrixBase< Derived >::markAsRValue(), Eigen::SparseCompressedBase< Derived >::nonZeros(), Eigen::SparseMatrixBase< Derived >::operator*(), Eigen::operator*(), Eigen::SparseMatrixBase< Derived >::operator*(), Eigen::operator*(), Eigen::SparseMatrixBase< Derived >::operator*(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator*(), Eigen::operator*(), Eigen::operator*(), Eigen::SparseMatrixBase< Derived >::operator+=(), Eigen::SparseMatrixBase< Derived >::operator-=(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrixBase< Derived >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseCompressedBase< Derived >::outerIndexPtr(), Eigen::SparseCompressedBase< Derived >::outerIndexPtr(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), Eigen::SparseMatrixBase< Derived >::rows(), Eigen::SparseQR< _MatrixType, _OrderingType >::solve(), Eigen::SparseMatrixBase< Derived >::toDense(), Eigen::SparseMatrixBase< Derived >::transpose(), Eigen::SparseMatrixBase< Derived >::transpose(), Eigen::SparseMatrixBase< Derived >::twistedBy(), Eigen::SparseCompressedBase< Derived >::valuePtr(), and Eigen::SparseCompressedBase< Derived >::valuePtr().
dot() [1/4]
template<typename Derived > template<typename OtherDerived > internal::traits< Derived >::Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  eigen_assert(other.size()>0 && "you are using a non initialized vector");
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  Scalar res(0);
  while (i)
  {
    res += numext::conj(i.value()) * other.coeff(i.index());
    ++i;
  }
  return res;
}
References eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
dot() [2/4]
template<typename Derived > template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const inherited
dot() [3/4]
template<typename Derived > template<typename OtherDerived > internal::traits< Derived >::Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  internal::evaluator<OtherDerived>  otherEval(other.derived());
  typename internal::evaluator<OtherDerived>::InnerIterator j(otherEval, 0);
  Scalar res(0);
  while (i && j)
  {
    if (i.index()==j.index())
    {
      res += numext::conj(i.value()) * j.value();
      ++i; ++j;
    }
    else if (i.index()<j.index())
      ++i;
    else
      ++j;
  }
  return res;
}
References Eigen::SparseMatrixBase< Derived >::derived(), eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::SparseMatrixBase< Derived >::size().
dot() [4/4]
template<typename Derived > template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
eval()
template<typename Derived > const internal::eval< Derived >::type Eigen::SparseMatrixBase< Derived >::eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
    { return typename internal::eval<Derived>::type(derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by igl::biharmonic_coordinates().
evalTo()
template<typename Derived > template<typename Dest > void Eigen::SparseMatrixBase< Derived >::evalTo (Dest &) const private inherited
innerIndexPtr() [1/2]
template<typename Derived > StorageIndex * Eigen::SparseCompressedBase< Derived >::innerIndexPtr () inline
Returns
a non-const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See also
valuePtr(), outerIndexPtr()
{ return derived().innerIndexPtr(); }
References Eigen::SparseMatrixBase< Derived >::derived().
innerIndexPtr() [2/2]
template<typename Derived > const StorageIndex * Eigen::SparseCompressedBase< Derived >::innerIndexPtr () const inline
Returns
a const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See also
valuePtr(), outerIndexPtr()
{ return derived().innerIndexPtr(); }
References Eigen::SparseMatrixBase< Derived >::derived().
innerNonZeroPtr() [1/2]
template<typename Derived > StorageIndex * Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr () inline
Returns
a non-const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
{ return derived().innerNonZeroPtr(); }
References Eigen::SparseMatrixBase< Derived >::derived().
innerNonZeroPtr() [2/2]
template<typename Derived > const StorageIndex * Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr () const inline
Returns
a const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
{ return derived().innerNonZeroPtr(); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator(), Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), and Eigen::SparseCompressedBase< Derived >::isCompressed().
innerNonZeros() [1/2]
template<typename Derived > Eigen::Map< IndexVector > Eigen::SparseCompressedBase< Derived >::innerNonZeros () inline protected
{ return Eigen::Map<IndexVector>(innerNonZeroPtr(), isCompressed()?0:derived().outerSize()); }
References Eigen::SparseMatrixBase< Derived >::derived(), Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), and Eigen::SparseCompressedBase< Derived >::isCompressed().
Referenced by Eigen::SparseCompressedBase< Derived >::nonZeros().
innerNonZeros() [2/2]
template<typename Derived > const Eigen::Map< const IndexVector > Eigen::SparseCompressedBase< Derived >::innerNonZeros () const inline protected
{ return Eigen::Map<const IndexVector>(innerNonZeroPtr(), isCompressed()?0:derived().outerSize()); }
References Eigen::SparseMatrixBase< Derived >::derived(), Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), and Eigen::SparseCompressedBase< Derived >::isCompressed().
innerSize()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::innerSize () const inline inherited
Returns
the size of the inner dimension according to the storage order, i.e., the number of rows for a columns major matrix, and the number of cols otherwise
{ return (int(Flags)&RowMajorBit) ? this->cols() : this->rows(); }
References Eigen::SparseMatrixBase< Derived >::cols(), Eigen::SparseMatrixBase< Derived >::Flags, Eigen::RowMajorBit, and Eigen::SparseMatrixBase< Derived >::rows().
innerVector() [1/2]
template<typename Derived > SparseMatrixBase< Derived >::InnerVectorReturnType Eigen::SparseMatrixBase< Derived >::innerVector (Index outer) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{ return InnerVectorReturnType(derived(), outer); }
innerVector() [2/2]
template<typename Derived > const SparseMatrixBase< Derived >::ConstInnerVectorReturnType Eigen::SparseMatrixBase< Derived >::innerVector (Index outer) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{ return ConstInnerVectorReturnType(derived(), outer); }
innerVectors() [1/2]
template<typename Derived > SparseMatrixBase< Derived >::InnerVectorsReturnType Eigen::SparseMatrixBase< Derived >::innerVectors (Index outerStart, Index outerSize) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{
  return Block<Derived,Dynamic,Dynamic,true>(derived(),
                                             IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                             IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
innerVectors() [2/2]
template<typename Derived > const SparseMatrixBase< Derived >::ConstInnerVectorsReturnType Eigen::SparseMatrixBase< Derived >::innerVectors (Index outerStart, Index outerSize) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{
  return Block<const Derived,Dynamic,Dynamic,true>(derived(),
                                                  IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                                  IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
isApprox() [1/2]
template<typename Derived > template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inline inherited
    { return toDense().isApprox(other,prec); }
References Eigen::SparseMatrixBase< Derived >::toDense().
isApprox() [2/2]
template<typename Derived > template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const SparseMatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
{
  const typename internal::nested_eval<Derived,2,PlainObject>::type actualA(derived());
  typename internal::conditional<bool(IsRowMajor)==bool(OtherDerived::IsRowMajor),
    const typename internal::nested_eval<OtherDerived,2,PlainObject>::type,
    const PlainObject>::type actualB(other.derived());
  return (actualA - actualB).squaredNorm() <= prec * prec * numext::mini(actualA.squaredNorm(), actualB.squaredNorm());
}
References Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::numext::mini().
isCompressed()
template<typename Derived > bool Eigen::SparseCompressedBase< Derived >::isCompressed () const inline
Returns
whether *this is in compressed form.
{ return innerNonZeroPtr()==0; }
References Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr().
Referenced by Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator(), Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator(), Eigen::SparseCompressedBase< Derived >::coeffs(), Eigen::SparseCompressedBase< Derived >::coeffs(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), and Eigen::SparseCompressedBase< Derived >::nonZeros().
isRValue()
template<typename Derived > bool Eigen::SparseMatrixBase< Derived >::isRValue () const inline inherited
{ return m_isRValue; }
References Eigen::SparseMatrixBase< Derived >::m_isRValue.
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), and Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=().
isVector()
template<typename Derived > bool Eigen::SparseMatrixBase< Derived >::isVector () const inline inherited
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See also
rows(), cols(), IsVectorAtCompileTime.
{ return rows()==1 || cols()==1; }
References Eigen::SparseMatrixBase< Derived >::cols(), and Eigen::SparseMatrixBase< Derived >::rows().
markAsRValue()
template<typename Derived > Derived & Eigen::SparseMatrixBase< Derived >::markAsRValue () inline inherited
{ m_isRValue = true; return derived(); }
References Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::m_isRValue.
nonZeros()
template<typename Derived > Index Eigen::SparseCompressedBase< Derived >::nonZeros () const inline
Returns
the number of non zero coefficients
    {
      if(Derived::IsVectorAtCompileTime && outerIndexPtr()==0)
        return derived().nonZeros();
      else if(isCompressed())
        return outerIndexPtr()[derived().outerSize()]-outerIndexPtr()[0];
      else if(derived().outerSize()==0)
        return 0;
      else
        return innerNonZeros().sum();
    }
References Eigen::SparseMatrixBase< Derived >::derived(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), Eigen::SparseCompressedBase< Derived >::isCompressed(), Eigen::SparseCompressedBase< Derived >::outerIndexPtr(), and Eigen::SparseMatrixBase< Derived >::outerSize().
Referenced by Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator(), Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator(), Eigen::SparseCompressedBase< Derived >::coeffs(), and Eigen::SparseCompressedBase< Derived >::coeffs().
norm()
template<typename Derived > NumTraits< typenameinternal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::norm inline inherited
{
  using std::sqrt;
  return sqrt(squaredNorm());
}
References sqrt().
Referenced by Eigen::SPQR< _MatrixType >::compute(), and Eigen::MatrixMarketIterator< Scalar >::matrix().
operator*() [1/3]
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived > Eigen::SparseMatrixBase< Derived >::operator* (const DiagonalBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
References Eigen::DiagonalBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::derived().
operator*() [2/3]
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived > Eigen::SparseMatrixBase< Derived >::operator* (const MatrixBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
operator*() [3/3]
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived, AliasFreeProduct > Eigen::SparseMatrixBase< Derived >::operator* (const SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the product of two sparse matrices. By default a conservative product preserving the symbolic non zeros is performed. The automatic pruning of the small values can be achieved by calling the pruned() function in which case a totally different product algorithm is employed:
C = (A*B).pruned();             // supress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return Product<Derived,OtherDerived,AliasFreeProduct>(derived(), other.derived());
}
References Eigen::SparseMatrixBase< Derived >::derived().
operator*=() [1/2]
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator*= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() *= other;
  return derived();
}
operator*=() [2/2]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator*= (const SparseMatrixBase< OtherDerived > & other) inherited
operator+=() [1/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
References Eigen::DiagonalBase< Derived >::derived().
operator+=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
References Eigen::EigenBase< Derived >::derived().
operator+=() [3/4]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() + other.derived();
}
References Eigen::SparseMatrixBase< Derived >::derived().
operator+=() [4/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
operator-=() [1/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::sub_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
References Eigen::DiagonalBase< Derived >::derived().
operator-=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
References Eigen::EigenBase< Derived >::derived().
operator-=() [3/4]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() - other.derived();
}
References Eigen::SparseMatrixBase< Derived >::derived().
operator-=() [4/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
operator/=()
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator/= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() /= other;
  return derived();
}
operator=() [1/4]
template<typename Derived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const Derived & other) inline
{
  internal::call_assignment_no_alias(derived(), other.derived());
  return derived();
}
operator=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
{
  internal::call_assignment_no_alias(derived(), other.derived());
  return derived();
}
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=().
operator=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
{
  // TODO use the evaluator mechanism
  other.evalTo(derived());
  return derived();
}
operator=() [4/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (const SparseMatrixBase< OtherDerived > & other) inline
{
  // by default sparse evaluation do not alias, so we can safely bypass the generic call_assignment routine
  internal::Assignment<Derived,OtherDerived,internal::assign_op<Scalar,typename OtherDerived::Scalar> >
          ::run(derived(), other.derived(), internal::assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
outerIndexPtr() [1/2]
template<typename Derived > StorageIndex * Eigen::SparseCompressedBase< Derived >::outerIndexPtr () inline
Returns
a non-const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 for SparseVector
See also
valuePtr(), innerIndexPtr()
{ return derived().outerIndexPtr(); }
References Eigen::SparseMatrixBase< Derived >::derived().
outerIndexPtr() [2/2]
template<typename Derived > const StorageIndex * Eigen::SparseCompressedBase< Derived >::outerIndexPtr () const inline
Returns
a const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 for SparseVector
See also
valuePtr(), innerIndexPtr()
{ return derived().outerIndexPtr(); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseCompressedBase< Derived >::InnerIterator::InnerIterator(), Eigen::SparseCompressedBase< Derived >::ReverseInnerIterator::ReverseInnerIterator(), and Eigen::SparseCompressedBase< Derived >::nonZeros().
outerSize()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::outerSize () const inline inherited
Returns
the size of the storage major dimension, i.e., the number of columns for a columns major matrix, and the number of rows otherwise
{ return (int(Flags)&RowMajorBit) ? this->rows() : this->cols(); }
References Eigen::SparseMatrixBase< Derived >::cols(), Eigen::SparseMatrixBase< Derived >::Flags, Eigen::RowMajorBit, and Eigen::SparseMatrixBase< Derived >::rows().
Referenced by Eigen::SparseCompressedBase< Derived >::nonZeros().
pruned()
template<typename Derived > const SparseView< Derived > Eigen::SparseMatrixBase< Derived >::pruned (const Scalar & reference = Scalar(0), const RealScalar & epsilon = NumTraits<Scalar>::dummy_precision()) const inline inherited
Returns
an expression of *this with values smaller than reference * epsilon removed.
This method is typically used in conjunction with the product of two sparse matrices to automatically prune the smallest values as follows:
C = (A*B).pruned();             // suppress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return SparseView<Derived>(derived(), reference, epsilon);
}
rows()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::rows () const inline inherited
Returns
the number of rows.
See also
cols()
{ return derived().rows(); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseMatrixBase< Derived >::innerSize(), Eigen::SparseMatrixBase< Derived >::isVector(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrixBase< Derived >::outerSize(), Eigen::SparseMatrixBase< Derived >::size(), and Eigen::SparseQR< _MatrixType, _OrderingType >::solve().
selfadjointView() [1/4]
template<typename Derived > template<unsigned int UpLo> SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () inline inherited
selfadjointView() [2/4]
template<typename Derived > template<unsigned int UpLo> SparseMatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () inherited
{
  return SparseSelfAdjointView<Derived, UpLo>(derived());
}
References Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::derived().
selfadjointView() [3/4]
template<typename Derived > template<unsigned int UpLo> ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const inline inherited
selfadjointView() [4/4]
template<typename Derived > template<unsigned int UpLo> SparseMatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const inherited
{
  return SparseSelfAdjointView<const Derived, UpLo>(derived());
}
References Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::derived().
size()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols().
{ return rows() * cols(); }
References Eigen::SparseMatrixBase< Derived >::cols(), and Eigen::SparseMatrixBase< Derived >::rows().
Referenced by igl::active_set(), igl::cat(), igl::diag(), Eigen::SparseMatrixBase< Derived >::dot(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize(), igl::invert_diag(), igl::min_quad_with_fixed_precompute(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resizeNonZeros().
squaredNorm()
template<typename Derived > NumTraits< typenameinternal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::squaredNorm inline inherited
{
  return numext::real((*this).cwiseAbs2().sum());
}
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
sum()
template<typename Derived > internal::traits< Derived >::Scalar Eigen::SparseMatrixBase< Derived >::sum inherited
{
  eigen_assert(rows()>0 && cols()>0 && "you are using a non initialized matrix");
  Scalar res(0);
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (typename internal::evaluator<Derived>::InnerIterator iter(thisEval,j); iter; ++iter)
      res += iter.value();
  return res;
}
References eigen_assert.
toDense()
template<typename Derived > DenseMatrixType Eigen::SparseMatrixBase< Derived >::toDense () const inline inherited
    {
      return DenseMatrixType(derived());
    }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseMatrixBase< Derived >::isApprox().
transpose() [1/2]
template<typename Derived > TransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () inline inherited
{ return TransposeReturnType(derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseMatrixBase< Derived >::adjoint(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::analyzePattern(), igl::arap_dof_precomputation(), igl::AtA_cached_precompute(), igl::slim::build_linear_system(), igl::copyleft::comiso::PoissonSolver< DerivedV, DerivedF >::BuildLaplacianMatrix(), Eigen::PastixLU< _MatrixType, IsStrSym >::grabMatrix(), igl::hessian(), igl::hessian_energy(), igl::min_quad_with_fixed_precompute(), igl::mosek::mosek_quadprog(), igl::orientable_patches(), igl::shapeup_precomputation(), and igl::straighten_seams().
transpose() [2/2]
template<typename Derived > const ConstTransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () const inline inherited
{ return ConstTransposeReturnType(derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
triangularView()
template<typename Derived > template<int Mode> const TriangularView< const Derived, Mode > Eigen::SparseMatrixBase< Derived >::triangularView inline inherited
{
  return TriangularView<const Derived, Mode>(derived());
}
Referenced by igl::mosek::mosek_quadprog().
twistedBy()
template<typename Derived > SparseSymmetricPermutationProduct< Derived, Upper|Lower > Eigen::SparseMatrixBase< Derived >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline inherited
Returns
an expression of P H P^-1 where H is the matrix represented by *this
    {
      return SparseSymmetricPermutationProduct<Derived,Upper|Lower>(derived(), perm);
    }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::PardisoLLT< MatrixType, _UpLo >::getMatrix(), and Eigen::PardisoLDLT< MatrixType, Options >::getMatrix().
valuePtr() [1/2]
template<typename Derived > Scalar * Eigen::SparseCompressedBase< Derived >::valuePtr () inline
Returns
a non-const pointer to the array of values. This function is aimed at interoperability with other libraries.
See also
innerIndexPtr(), outerIndexPtr()
{ return derived().valuePtr(); }
References Eigen::SparseMatrixBase< Derived >::derived().
valuePtr() [2/2]
template<typename Derived > const Scalar * Eigen::SparseCompressedBase< Derived >::valuePtr () const inline
Returns
a const pointer to the array of values. This function is aimed at interoperability with other libraries.
See also
innerIndexPtr(), outerIndexPtr()
{ return derived().valuePtr(); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseCompressedBase< Derived >::coeffs(), and Eigen::SparseCompressedBase< Derived >::coeffs().
Member Data Documentation
m_isRValue
template<typename Derived > bool Eigen::SparseMatrixBase< Derived >::m_isRValue protected inherited
Referenced by Eigen::SparseMatrixBase< Derived >::isRValue(), and Eigen::SparseMatrixBase< Derived >::markAsRValue().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseCompressedBase.h