Prusa Slicer: agg::bezier_arc Class Reference
agg::bezier_arc Class Reference
#include <src/agg/agg_bezier_arc.h>
Public Member Functions
bezier_arc ()
bezier_arc (double x, double y, double rx, double ry, double start_angle, double sweep_angle)
void init (double x, double y, double rx, double ry, double start_angle, double sweep_angle)
void rewind (unsigned)
unsigned vertex (double *x, double *y)
unsigned num_vertices () const
const double * vertices () const
double * vertices ()
Private Attributes
unsigned m_vertex
unsigned m_num_vertices
double m_vertices [26]
unsigned m_cmd
Detailed Description
Constructor & Destructor Documentation
bezier_arc() [1/2]
agg::bezier_arc::bezier_arc () inline
: m_vertex(26), m_num_vertices(0), m_cmd(path_cmd_line_to) {}
bezier_arc() [2/2]
agg::bezier_arc::bezier_arc (double x, double y, double rx, double ry, double start_angle, double sweep_angle) inline
        {
            init(x, y, rx, ry, start_angle, sweep_angle);
        }
References init().
Member Function Documentation
init()
void agg::bezier_arc::init (double x, double y, double rx, double ry, double start_angle, double sweep_angle)
Referenced by bezier_arc().
num_vertices()
unsigned agg::bezier_arc::num_vertices () const inline
{ return m_num_vertices; }
References m_num_vertices.
Referenced by agg::bezier_arc_svg::num_vertices().
rewind()
void agg::bezier_arc::rewind (unsigned) inline
        {
            m_vertex = 0;
        }
References m_vertex.
Referenced by agg::bezier_arc_svg::rewind().
vertex()
unsigned agg::bezier_arc::vertex (double * x, double * y) inline
        {
            if(m_vertex >= m_num_vertices) return path_cmd_stop;
            *x = m_vertices[m_vertex];
            *y = m_vertices[m_vertex + 1];
            m_vertex += 2;
            return (m_vertex == 2) ? unsigned(path_cmd_move_to) : m_cmd;
        }
References m_cmd, m_num_vertices, m_vertex, m_vertices, agg::path_cmd_move_to, and agg::path_cmd_stop.
Referenced by agg::bezier_arc_svg::vertex().
vertices() [1/2]
double * agg::bezier_arc::vertices () inline
{ return m_vertices;     }
References m_vertices.
vertices() [2/2]
const double * agg::bezier_arc::vertices () const inline
{ return m_vertices;     }
References m_vertices.
Referenced by agg::bezier_arc_svg::vertices(), and agg::bezier_arc_svg::vertices().
Member Data Documentation
m_cmd
unsigned agg::bezier_arc::m_cmd private
Referenced by vertex().
m_num_vertices
unsigned agg::bezier_arc::m_num_vertices private
Referenced by num_vertices(), and vertex().
m_vertex
unsigned agg::bezier_arc::m_vertex private
Referenced by rewind(), and vertex().
m_vertices
double agg::bezier_arc::m_vertices[26] private
Referenced by vertex(), vertices(), and vertices().
The documentation for this class was generated from the following file:
src/agg/agg_bezier_arc.h