Prusa Slicer: Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > Class Template Reference
Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > Class Template Reference
General-purpose arrays with easy API for coefficient-wise operations.
#include <src/eigen/Eigen/src/Core/Array.h>
Classes
struct PrivateType
Public Types
enum { Options = _Options }
typedef PlainObjectBase< Array > Base
typedef Base::PlainObject PlainObject
enum
enum
typedef internal::traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::StorageKind StorageKind
typedef internal::traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > DenseType
typedef Eigen::Map< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >, Unaligned > MapType
typedef const Eigen::Map< const Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >, Unaligned > ConstMapType
typedef Eigen::Map< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >, AlignedMax > AlignedMapType
typedef const Eigen::Map< const Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >, AlignedMax > ConstAlignedMapType
Public Member Functions
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array & operator= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array & operator= (const Scalar &value)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array & operator= (const Array &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array ()
EIGEN_DEVICE_FUNC Array (internal::constructor_without_unaligned_array_assert)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array (const T &x)
template<typename T0 , typename T1 >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array (const T0 &val0, const T1 &val1)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array (const Scalar &val0, const Scalar &val1, const Scalar &val2)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array (const Scalar &val0, const Scalar &val1, const Scalar &val2, const Scalar &val3)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array (const Array &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array (const EigenBase< OtherDerived > &other, typename internal::enable_if< internal::is_convertible< typename OtherDerived::Scalar, Scalar >::value, PrivateType >::type=PrivateType())
EIGEN_DEVICE_FUNC Index innerStride () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Base & base ()
EIGEN_DEVICE_FUNC const Base & base () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeff (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index rowId, Index colId)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeffRef (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeffRef (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rows () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index cols () const
EIGEN_STRONG_INLINE PacketScalar packet (Index rowId, Index colId) const
EIGEN_STRONG_INLINE PacketScalar packet (Index index) const
EIGEN_STRONG_INLINE void writePacket (Index rowId, Index colId, const PacketScalar &val)
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketScalar &val)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar * data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar * data ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC void resize (Index size)
EIGEN_DEVICE_FUNC void resize (NoChange_t, Index cols)
EIGEN_DEVICE_FUNC void resize (Index rows, NoChange_t)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void resizeLike (const EigenBase< OtherDerived > &_other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResize (Index rows, Index cols)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResize (Index rows, NoChange_t)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResize (NoChange_t, Index cols)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResize (Index size)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResizeLike (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & lazyAssign (const DenseBase< OtherDerived > &other)
Protected Attributes
DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options > m_storage
Friends
template<typename Derived , typename OtherDerived , bool IsVector>
struct internal::conservative_resize_like_impl
template<typename MatrixType , typename OtherDerived , bool SwapPointers>
struct internal::matrix_swap_impl
Map
These are convenience functions returning Map objects. The Map() static functions return unaligned Map objects, while the AlignedMap() functions return aligned Map objects and thus should be called only with 16-byte-aligned data pointers.
Here is an example using strides:
Output:
See also
class Map
enum
EIGEN_DEVICE_FUNC Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & setConstant (Index size, const Scalar &val)
EIGEN_DEVICE_FUNC Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & setConstant (Index rows, Index cols, const Scalar &val)
EIGEN_DEVICE_FUNC Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & setZero (Index size)
EIGEN_DEVICE_FUNC Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & setZero (Index rows, Index cols)
EIGEN_DEVICE_FUNC Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & setOnes (Index size)
EIGEN_DEVICE_FUNC Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & setOnes (Index rows, Index cols)
Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & setRandom (Index size)
Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & setRandom (Index rows, Index cols)
EIGEN_DEVICE_FUNC void swap (DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC void swap (DenseBase< OtherDerived > const &other)
static ConstMapType Map (const Scalar *data)
static MapType Map (Scalar *data)
static ConstMapType Map (const Scalar *data, Index size)
static MapType Map (Scalar *data, Index size)
static ConstMapType Map (const Scalar *data, Index rows, Index cols)
static MapType Map (Scalar *data, Index rows, Index cols)
static StridedConstMapType< Stride< Outer, Inner > >::type Map (const Scalar *data, const Stride< Outer, Inner > &stride)
static StridedMapType< Stride< Outer, Inner > >::type Map (Scalar *data, const Stride< Outer, Inner > &stride)
static StridedConstMapType< Stride< Outer, Inner > >::type Map (const Scalar *data, Index size, const Stride< Outer, Inner > &stride)
static StridedMapType< Stride< Outer, Inner > >::type Map (Scalar *data, Index size, const Stride< Outer, Inner > &stride)
static StridedConstMapType< Stride< Outer, Inner > >::type Map (const Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
static StridedMapType< Stride< Outer, Inner > >::type Map (Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
static ConstAlignedMapType MapAligned (const Scalar *data)
static AlignedMapType MapAligned (Scalar *data)
static ConstAlignedMapType MapAligned (const Scalar *data, Index size)
static AlignedMapType MapAligned (Scalar *data, Index size)
static ConstAlignedMapType MapAligned (const Scalar *data, Index rows, Index cols)
static AlignedMapType MapAligned (Scalar *data, Index rows, Index cols)
static StridedConstAlignedMapType< Stride< Outer, Inner > >::type MapAligned (const Scalar *data, const Stride< Outer, Inner > &stride)
static StridedAlignedMapType< Stride< Outer, Inner > >::type MapAligned (Scalar *data, const Stride< Outer, Inner > &stride)
static StridedConstAlignedMapType< Stride< Outer, Inner > >::type MapAligned (const Scalar *data, Index size, const Stride< Outer, Inner > &stride)
static StridedAlignedMapType< Stride< Outer, Inner > >::type MapAligned (Scalar *data, Index size, const Stride< Outer, Inner > &stride)
static StridedConstAlignedMapType< Stride< Outer, Inner > >::type MapAligned (const Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
static StridedAlignedMapType< Stride< Outer, Inner > >::type MapAligned (Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _check_template_params ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _resize_to_match (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & _set (const DenseBase< OtherDerived > &other)
Copies the value of the expression other into *this with automatic resizing.
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & _set_noalias (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init2 (Index rows, Index cols, typename internal::enable_if< Base::SizeAtCompileTime!=2, T0 >::type *=0)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init2 (const T0 &val0, const T1 &val1, typename internal::enable_if< Base::SizeAtCompileTime==2, T0 >::type *=0)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init2 (const Index &val0, const Index &val1, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< T0, Index >::value) &&(internal::is_same< T1, Index >::value) &&Base::SizeAtCompileTime==2, T1 >::type *=0)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (Index size, typename internal::enable_if<(Base::SizeAtCompileTime!=1||!internal::is_convertible< T, Scalar >::value) &&((!internal::is_same< typename internal::traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::XprKind, ArrayXpr >::value||Base::SizeAtCompileTime==Dynamic)), T >::type *=0)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Scalar &val0, typename internal::enable_if< Base::SizeAtCompileTime==1 &&internal::is_convertible< T, Scalar >::value, T >::type *=0)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Index &val0, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< Index, T >::value) &&Base::SizeAtCompileTime==1 &&internal::is_convertible< T, Scalar >::value, T * >::type *=0)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Scalar *data)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const ReturnByValue< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const RotationBase< OtherDerived, ColsAtCompileTime > &r)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Scalar &val0, typename internal::enable_if< Base::SizeAtCompileTime!=Dynamic &&Base::SizeAtCompileTime!=1 &&internal::is_convertible< T, Scalar >::value &&internal::is_same< typename internal::traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::XprKind, ArrayXpr >::value, T >::type *=0)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Index &val0, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< Index, T >::value) &&Base::SizeAtCompileTime!=Dynamic &&Base::SizeAtCompileTime!=1 &&internal::is_convertible< T, Scalar >::value &&internal::is_same< typename internal::traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::XprKind, ArrayXpr >::value, T * >::type *=0)
Detailed Description
template<typename _Scalar, int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols>
class Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >
General-purpose arrays with easy API for coefficient-wise operations.
The Array class is very similar to the Matrix class. It provides general-purpose one- and two-dimensional arrays. The difference between the Array and the Matrix class is primarily in the API: the API for the Array class provides easy access to coefficient-wise operations, while the API for the Matrix class provides easy access to linear-algebra operations.
See documentation of class Matrix for detailed information on the template parameters storage layout.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizing_Plugins by defining the preprocessor symbol EIGEN_ARRAY_PLUGIN.
See also
\blank TutorialArrayClass, TopicClassHierarchy
Class Documentation
Eigen::Array::PrivateType
struct Eigen::Array::PrivateType
template<typename _Scalar, int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols>
struct Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::PrivateType
Member Typedef Documentation
AlignedMapType
typedef Eigen::Map<Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > , AlignedMax> Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::AlignedMapType inherited
Base
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> typedef PlainObjectBase<Array> Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Base
ConstAlignedMapType
typedef const Eigen::Map<const Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > , AlignedMax> Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::ConstAlignedMapType inherited
ConstMapType
typedef const Eigen::Map<const Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > , Unaligned> Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::ConstMapType inherited
DenseType
typedef Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::DenseType inherited
MapType
typedef Eigen::Map<Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > , Unaligned> Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapType inherited
PacketScalar
typedef internal::packet_traits<Scalar>::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PacketScalar inherited
PlainObject
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> typedef Base::PlainObject Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::PlainObject
RealScalar
typedef NumTraits<Scalar>::Real Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::RealScalar inherited
Scalar
typedef internal::traits<Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Scalar Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Scalar inherited
StorageKind
typedef internal::traits<Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::StorageKind Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::StorageKind inherited
Member Enumeration Documentation
anonymous enum
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> anonymous enum
Enumerator
Options
{ Options = _Options };
anonymous enum
anonymous enum inherited
{ Options = internal::traits<Derived>::Options };
anonymous enum
anonymous enum inherited
{ NeedsToAlign = (SizeAtCompileTime != Dynamic) && (internal::traits<Derived>::Alignment>0) };
anonymous enum
anonymous enum inherited
{ IsPlainObjectBase = 1 };
Constructor & Destructor Documentation
Array() [1/8]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array () inline
Default constructor.
For fixed-size matrices, does nothing.
For dynamic-size matrices, creates an empty matrix of size 0. Does not allocate any array. Such a matrix is called a null matrix. This constructor is the unique way to create null matrices: resizing a matrix to 0 is not supported.
See also
resize(Index,Index)
                                : Base()
    {
      Base::_check_template_params();
      EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED
    }
References Eigen::PlainObjectBase< Derived >::_check_template_params(), and EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED.
Array() [2/8]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array (internal::constructor_without_unaligned_array_assert) inline
      : Base(internal::constructor_without_unaligned_array_assert())
    {
      Base::_check_template_params();
      EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED
    }
References Eigen::PlainObjectBase< Derived >::_check_template_params(), and EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED.
Array() [3/8]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array (const T & x) inline explicit
    {
      Base::_check_template_params();
      Base::template _init1<T>(x);
    }
References Eigen::PlainObjectBase< Derived >::_check_template_params().
Array() [4/8]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> template<typename T0 , typename T1 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array (const T0 & val0, const T1 & val1) inline
    {
      Base::_check_template_params();
      this->template _init2<T0,T1>(val0, val1);
    }
References Eigen::PlainObjectBase< Derived >::_check_template_params().
Array() [5/8]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array (const Scalar & val0, const Scalar & val1, const Scalar & val2) inline
constructs an initialized 3D vector with given coefficients
    {
      Base::_check_template_params();
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(Array, 3)
      m_storage.data()[0] = val0;
      m_storage.data()[1] = val1;
      m_storage.data()[2] = val2;
    }
References Eigen::PlainObjectBase< Derived >::_check_template_params(), Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::m_storage.
Array() [6/8]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array (const Scalar & val0, const Scalar & val1, const Scalar & val2, const Scalar & val3) inline
constructs an initialized 4D vector with given coefficients
    {
      Base::_check_template_params();
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(Array, 4)
      m_storage.data()[0] = val0;
      m_storage.data()[1] = val1;
      m_storage.data()[2] = val2;
      m_storage.data()[3] = val3;
    }
References Eigen::PlainObjectBase< Derived >::_check_template_params(), Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::m_storage.
Array() [7/8]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array (const Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & other) inline
Copy constructor
            : Base(other)
    { }
Array() [8/8]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array (const EigenBase< OtherDerived > & other, typename internal::enable_if< internal::is_convertible< typename OtherDerived::Scalar, Scalar >::value, PrivateType >::type = PrivateType()) inline
See also
MatrixBase::operator=(const EigenBase<OtherDerived>&)
      : Base(other.derived())
    { }
Member Function Documentation
_check_template_params()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_check_template_params () inline static inherited
    {
      EIGEN_STATIC_ASSERT((EIGEN_IMPLIES(MaxRowsAtCompileTime==1 && MaxColsAtCompileTime!=1, (Options&RowMajor)==RowMajor)
                        && EIGEN_IMPLIES(MaxColsAtCompileTime==1 && MaxRowsAtCompileTime!=1, (Options&RowMajor)==0)
                        && ((RowsAtCompileTime == Dynamic) || (RowsAtCompileTime >= 0))
                        && ((ColsAtCompileTime == Dynamic) || (ColsAtCompileTime >= 0))
                        && ((MaxRowsAtCompileTime == Dynamic) || (MaxRowsAtCompileTime >= 0))
                        && ((MaxColsAtCompileTime == Dynamic) || (MaxColsAtCompileTime >= 0))
                        && (MaxRowsAtCompileTime == RowsAtCompileTime || RowsAtCompileTime==Dynamic)
                        && (MaxColsAtCompileTime == ColsAtCompileTime || ColsAtCompileTime==Dynamic)
                        && (Options & (DontAlign|RowMajor)) == Options),
        INVALID_MATRIX_TEMPLATE_PARAMETERS)
    }
_init1() [1/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & other) inline protected inherited
{
      this->_set_noalias(other);
    }
_init1() [2/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const DenseBase< OtherDerived > & other) inline protected inherited
{
      this->_set_noalias(other);
    }
_init1() [3/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const EigenBase< OtherDerived > & other) inline protected inherited
{
      this->derived() = other;
    }
_init1() [4/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const Index & val0, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< Index, T >::value) &&Base::SizeAtCompileTime!=Dynamic &&Base::SizeAtCompileTime!=1 &&internal::is_convertible< T, Scalar >::value &&internal::is_same< typename internal::traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::XprKind, ArrayXpr >::value, T * >::type * = 0) inline protected inherited
    {
      Base::setConstant(val0);
    }
_init1() [5/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const Index & val0, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< Index, T >::value) &&Base::SizeAtCompileTime==1 &&internal::is_convertible< T, Scalar >::value, T * >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(PlainObjectBase, 1)
      m_storage.data()[0] = Scalar(val0);
    }
_init1() [6/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const ReturnByValue< OtherDerived > & other) inline protected inherited
    {
      resize(other.rows(), other.cols());
      other.evalTo(this->derived());
    }
_init1() [7/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const RotationBase< OtherDerived, ColsAtCompileTime > & r) inline protected inherited
    {
      this->derived() = r;
    }
_init1() [8/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const Scalar & val0, typename internal::enable_if< Base::SizeAtCompileTime!=Dynamic &&Base::SizeAtCompileTime!=1 &&internal::is_convertible< T, Scalar >::value &&internal::is_same< typename internal::traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::XprKind, ArrayXpr >::value, T >::type * = 0) inline protected inherited
    {
      Base::setConstant(val0);
    }
_init1() [9/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const Scalar & val0, typename internal::enable_if< Base::SizeAtCompileTime==1 &&internal::is_convertible< T, Scalar >::value, T >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(PlainObjectBase, 1)
      m_storage.data()[0] = val0;
    }
_init1() [10/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (const Scalar * data) inline protected inherited
{
      this->_set_noalias(ConstMapType(data));
    }
_init1() [11/11]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init1 (Index size, typename internal::enable_if<(Base::SizeAtCompileTime!=1||!internal::is_convertible< T, Scalar >::value) &&((!internal::is_same< typename internal::traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::XprKind, ArrayXpr >::value||Base::SizeAtCompileTime==Dynamic)), T >::type * = 0) inline protected inherited
    {
      // NOTE MSVC 2008 complains if we directly put bool(NumTraits<T>::IsInteger) as the EIGEN_STATIC_ASSERT argument.
      const bool is_integer = NumTraits<T>::IsInteger;
      EIGEN_UNUSED_VARIABLE(is_integer);
      EIGEN_STATIC_ASSERT(is_integer,
                          FLOATING_POINT_ARGUMENT_PASSED__INTEGER_WAS_EXPECTED)
      resize(size);
    }
_init2() [1/3]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init2 (const Index & val0, const Index & val1, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< T0, Index >::value) &&(internal::is_same< T1, Index >::value) &&Base::SizeAtCompileTime==2, T1 >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(PlainObjectBase, 2)
      m_storage.data()[0] = Scalar(val0);
      m_storage.data()[1] = Scalar(val1);
    }
_init2() [2/3]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init2 (const T0 & val0, const T1 & val1, typename internal::enable_if< Base::SizeAtCompileTime==2, T0 >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(PlainObjectBase, 2)
      m_storage.data()[0] = Scalar(val0);
      m_storage.data()[1] = Scalar(val1);
    }
_init2() [3/3]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init2 (Index rows, Index cols, typename internal::enable_if< Base::SizeAtCompileTime!=2, T0 >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT(bool(NumTraits<T0>::IsInteger) &&
                          bool(NumTraits<T1>::IsInteger),
                          FLOATING_POINT_ARGUMENT_PASSED__INTEGER_WAS_EXPECTED)
      resize(rows,cols);
    }
_resize_to_match()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match (const EigenBase< OtherDerived > & other) inline protected inherited
    {
      #ifdef EIGEN_NO_AUTOMATIC_RESIZING
      eigen_assert((this->size()==0 || (IsVectorAtCompileTime ? (this->size() == other.size())
                 : (rows() == other.rows() && cols() == other.cols())))
        && "Size mismatch. Automatic resizing is disabled because EIGEN_NO_AUTOMATIC_RESIZING is defined");
      EIGEN_ONLY_USED_FOR_DEBUG(other);
      #else
      resizeLike(other);
      #endif
    }
_set()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set (const DenseBase< OtherDerived > & other) inline protected inherited
Copies the value of the expression other into *this with automatic resizing.
*this might be resized to match the dimensions of other. If *this was a null matrix (not already initialized), it will be initialized.
Note that copying a row-vector into a vector (and conversely) is allowed. The resizing, if any, is then done in the appropriate way so that row-vectors remain row-vectors and vectors remain vectors.
See also
operator=(const MatrixBase<OtherDerived>&), _set_noalias()
    {
      internal::call_assignment(this->derived(), other.derived());
      return this->derived();
    }
_set_noalias()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set_noalias (const DenseBase< OtherDerived > & other) inline protected inherited
    {
      // I don't think we need this resize call since the lazyAssign will anyways resize
      // and lazyAssign will be called by the assign selector.
      //_resize_to_match(other);
      // the 'false' below means to enforce lazy evaluation. We don't use lazyAssign() because
      // it wouldn't allow to copy a row-vector into a column-vector.
      internal::call_assignment_no_alias(this->derived(), other.derived(), internal::assign_op<Scalar,typename OtherDerived::Scalar>());
      return this->derived();
    }
base() [1/2]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC Base & Eigen::PlainObjectBase< Derived >::base () inline
{ return *static_cast<Base*>(this); }
base() [2/2]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC const Base & Eigen::PlainObjectBase< Derived >::base () const inline
{ return *static_cast<const Base*>(this); }
coeff() [1/2]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & Eigen::PlainObjectBase< Derived >::coeff (Index index) const inline
This is an overloaded version of DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index) const for details.
    {
      return m_storage.data()[index];
    }
coeff() [2/2]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & Eigen::PlainObjectBase< Derived >::coeff (Index rowId, Index colId) const inline
This is an overloaded version of DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index,Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index) const for details.
    {
      if(Flags & RowMajorBit)
        return m_storage.data()[colId + rowId * m_storage.cols()];
      else // column-major
        return m_storage.data()[rowId + colId * m_storage.rows()];
    }
coeffRef() [1/4]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::PlainObjectBase< Derived >::coeffRef (Index index) inline
This is an overloaded version of DenseCoeffsBase<Derived,WriteAccessors>::coeffRef(Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,WriteAccessors>::coeffRef(Index) const for details.
    {
      return m_storage.data()[index];
    }
coeffRef() [2/4]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & Eigen::PlainObjectBase< Derived >::coeffRef (Index index) const inline
This is the const version of coeffRef(Index) which is thus synonym of coeff(Index). It is provided for convenience.
    {
      return m_storage.data()[index];
    }
coeffRef() [3/4]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::PlainObjectBase< Derived >::coeffRef (Index rowId, Index colId) inline
This is an overloaded version of DenseCoeffsBase<Derived,WriteAccessors>::coeffRef(Index,Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,WriteAccessors>::coeffRef(Index,Index) const for details.
    {
      if(Flags & RowMajorBit)
        return m_storage.data()[colId + rowId * m_storage.cols()];
      else // column-major
        return m_storage.data()[rowId + colId * m_storage.rows()];
    }
coeffRef() [4/4]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & Eigen::PlainObjectBase< Derived >::coeffRef (Index rowId, Index colId) const inline
This is the const version of coeffRef(Index,Index) which is thus synonym of coeff(Index,Index). It is provided for convenience.
    {
      if(Flags & RowMajorBit)
        return m_storage.data()[colId + rowId * m_storage.cols()];
      else // column-major
        return m_storage.data()[rowId + colId * m_storage.rows()];
    }
cols()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::cols () const inline inherited
{ return m_storage.cols(); }
conservativeResize() [1/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResize (Index rows, Index cols) inline inherited
Resizes the matrix to rows x cols while leaving old values untouched.
The method is intended for matrices of dynamic size. If you only want to change the number of rows and/or of columns, you can use conservativeResize(NoChange_t, Index) or conservativeResize(Index, NoChange_t).
Matrices are resized relative to the top-left element. In case values need to be appended to the matrix they will be uninitialized.
    {
      internal::conservative_resize_like_impl<Derived>::run(*this, rows, cols);
    }
conservativeResize() [2/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResize (Index rows, NoChange_t) inline inherited
Resizes the matrix to rows x cols while leaving old values untouched.
As opposed to conservativeResize(Index rows, Index cols), this version leaves the number of columns unchanged.
In case the matrix is growing, new rows will be uninitialized.
    {
      // Note: see the comment in conservativeResize(Index,Index)
      conservativeResize(rows, cols());
    }
conservativeResize() [3/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResize (Index size) inline inherited
Resizes the vector to size while retaining old values.
\only_for_vectors. This method does not work for partially dynamic matrices when the static dimension is anything other than 1. For example it will not work with Matrix<double, 2, Dynamic>.
When values are appended, they will be uninitialized.
    {
      internal::conservative_resize_like_impl<Derived>::run(*this, size);
    }
conservativeResize() [4/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResize (NoChange_t , Index cols) inline inherited
Resizes the matrix to rows x cols while leaving old values untouched.
As opposed to conservativeResize(Index rows, Index cols), this version leaves the number of rows unchanged.
In case the matrix is growing, new columns will be uninitialized.
    {
      // Note: see the comment in conservativeResize(Index,Index)
      conservativeResize(rows(), cols);
    }
conservativeResizeLike()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResizeLike (const DenseBase< OtherDerived > & other) inline inherited
Resizes the matrix to rows x cols of other, while leaving old values untouched.
The method is intended for matrices of dynamic size. If you only want to change the number of rows and/or of columns, you can use conservativeResize(NoChange_t, Index) or conservativeResize(Index, NoChange_t).
Matrices are resized relative to the top-left element. In case values need to be appended to the matrix they will copied from other.
    {
      internal::conservative_resize_like_impl<Derived,OtherDerived>::run(*this, other);
    }
data() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar * Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data () inline inherited
Returns
a pointer to the data array of this matrix
    { return m_storage.data(); }
data() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar * Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data () const inline inherited
Returns
a const pointer to the data array of this matrix
    { return m_storage.data(); }
innerStride()
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC Index Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::innerStride () const inline
{ return 1; }
lazyAssign()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::lazyAssign (const DenseBase< OtherDerived > & other) inline inherited
See also
MatrixBase::lazyAssign()
    {
      _resize_to_match(other);
      return Base::lazyAssign(other.derived());
    }
Map() [1/12]
static ConstMapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (const Scalar * data) inline static inherited
    { return ConstMapType(data); }
Map() [2/12]
static StridedConstMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (const Scalar * data, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstMapType<Stride<Outer, Inner> >::type(data, stride); }
Map() [3/12]
static ConstMapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (const Scalar * data, Index rows, Index cols) inline static inherited
    { return ConstMapType(data, rows, cols); }
Map() [4/12]
static StridedConstMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (const Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstMapType<Stride<Outer, Inner> >::type(data, rows, cols, stride); }
Map() [5/12]
static ConstMapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (const Scalar * data, Index size) inline static inherited
    { return ConstMapType(data, size); }
Map() [6/12]
static StridedConstMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (const Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstMapType<Stride<Outer, Inner> >::type(data, size, stride); }
Map() [7/12]
static MapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (Scalar * data) inline static inherited
    { return MapType(data); }
Map() [8/12]
static StridedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (Scalar * data, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedMapType<Stride<Outer, Inner> >::type(data, stride); }
Map() [9/12]
static MapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (Scalar * data, Index rows, Index cols) inline static inherited
    { return MapType(data, rows, cols); }
Map() [10/12]
static StridedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedMapType<Stride<Outer, Inner> >::type(data, rows, cols, stride); }
Map() [11/12]
static MapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (Scalar * data, Index size) inline static inherited
    { return MapType(data, size); }
Map() [12/12]
static StridedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map (Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedMapType<Stride<Outer, Inner> >::type(data, size, stride); }
MapAligned() [1/12]
static ConstAlignedMapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (const Scalar * data) inline static inherited
    { return ConstAlignedMapType(data); }
MapAligned() [2/12]
static StridedConstAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (const Scalar * data, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstAlignedMapType<Stride<Outer, Inner> >::type(data, stride); }
MapAligned() [3/12]
static ConstAlignedMapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (const Scalar * data, Index rows, Index cols) inline static inherited
    { return ConstAlignedMapType(data, rows, cols); }
MapAligned() [4/12]
static StridedConstAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (const Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstAlignedMapType<Stride<Outer, Inner> >::type(data, rows, cols, stride); }
MapAligned() [5/12]
static ConstAlignedMapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (const Scalar * data, Index size) inline static inherited
    { return ConstAlignedMapType(data, size); }
MapAligned() [6/12]
static StridedConstAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (const Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstAlignedMapType<Stride<Outer, Inner> >::type(data, size, stride); }
MapAligned() [7/12]
static AlignedMapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (Scalar * data) inline static inherited
    { return AlignedMapType(data); }
MapAligned() [8/12]
static StridedAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (Scalar * data, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedAlignedMapType<Stride<Outer, Inner> >::type(data, stride); }
MapAligned() [9/12]
static AlignedMapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (Scalar * data, Index rows, Index cols) inline static inherited
    { return AlignedMapType(data, rows, cols); }
MapAligned() [10/12]
static StridedAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedAlignedMapType<Stride<Outer, Inner> >::type(data, rows, cols, stride); }
MapAligned() [11/12]
static AlignedMapType Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (Scalar * data, Index size) inline static inherited
    { return AlignedMapType(data, size); }
MapAligned() [12/12]
static StridedAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::MapAligned (Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedAlignedMapType<Stride<Outer, Inner> >::type(data, size, stride); }
operator=() [1/4]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array & Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::operator= (const Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
    {
      return Base::_set(other);
    }
References Eigen::PlainObjectBase< Derived >::_set().
operator=() [2/4]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array & Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::operator= (const DenseBase< OtherDerived > & other) inline
Copies the value of the expression other into *this with automatic resizing.
*this might be resized to match the dimensions of other. If *this was a null matrix (not already initialized), it will be initialized.
Note that copying a row-vector into a vector (and conversely) is allowed. The resizing, if any, is then done in the appropriate way so that row-vectors remain row-vectors and vectors remain vectors.
    {
      return Base::_set(other);
    }
References Eigen::PlainObjectBase< Derived >::_set().
operator=() [3/4]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array & Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::operator= (const EigenBase< OtherDerived > & other) inline
The usage of using Base::operator=; fails on MSVC. Since the code below is working with GCC and MSVC, we skipped the usage of 'using'. This should be done only for operator=.
    {
      return Base::operator=(other);
    }
References Eigen::PlainObjectBase< Derived >::operator=().
operator=() [4/4]
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array & Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::operator= (const Scalar & value) inline
Set all the entries to value.
See also
DenseBase::setConstant(), DenseBase::fill()
    {
      Base::setConstant(value);
      return *this;
    }
References Eigen::PlainObjectBase< Derived >::setConstant().
outerStride()
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> EIGEN_DEVICE_FUNC Index Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::outerStride () const inline
{ return this->innerSize(); }
packet() [1/2]
EIGEN_STRONG_INLINE PacketScalar Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::packet (Index index) const inline inherited
    {
      return internal::ploadt<PacketScalar, LoadMode>(m_storage.data() + index);
    }
packet() [2/2]
EIGEN_STRONG_INLINE PacketScalar Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::packet (Index rowId, Index colId) const inline inherited
    {
      return internal::ploadt<PacketScalar, LoadMode>
               (m_storage.data() + (Flags & RowMajorBit
                                   ? colId + rowId * m_storage.cols()
                                   : rowId + colId * m_storage.rows()));
    }
resize() [1/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize (Index rows, Index cols) inline inherited
Resizes *this to a rows x cols matrix.
This method is intended for dynamic-size matrices, although it is legal to call it on any matrix as long as fixed dimensions are left unchanged. If you only want to change the number of rows and/or of columns, you can use resize(NoChange_t, Index), resize(Index, NoChange_t).
If the current number of coefficients of *this exactly matches the product rows * cols, then no memory allocation is performed and the current values are left unchanged. In all other cases, including shrinking, the data is reallocated and all previous values are lost.
Example:
Output:
See also
resize(Index) for vectors, resize(NoChange_t, Index), resize(Index, NoChange_t)
    {
      eigen_assert(   EIGEN_IMPLIES(RowsAtCompileTime!=Dynamic,rows==RowsAtCompileTime)
                   && EIGEN_IMPLIES(ColsAtCompileTime!=Dynamic,cols==ColsAtCompileTime)
                   && EIGEN_IMPLIES(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic,rows<=MaxRowsAtCompileTime)
                   && EIGEN_IMPLIES(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic,cols<=MaxColsAtCompileTime)
                   && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array.");
      internal::check_rows_cols_for_overflow<MaxSizeAtCompileTime>::run(rows, cols);
      #ifdef EIGEN_INITIALIZE_COEFFS
        Index size = rows*cols;
        bool size_changed = size != this->size();
        m_storage.resize(size, rows, cols);
        if(size_changed) EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED
      #else
        m_storage.resize(rows*cols, rows, cols);
      #endif
    }
resize() [2/4]
EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize (Index rows, NoChange_t) inline inherited
Resizes the matrix, changing only the number of rows. For the parameter of type NoChange_t, just pass the special value NoChange as in the example below.
Example:
Output:
See also
resize(Index,Index)
    {
      resize(rows, cols());
    }
resize() [3/4]
EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize (Index size) inline inherited
Resizes *this to a vector of length size
\only_for_vectors. This method does not work for partially dynamic matrices when the static dimension is anything other than 1. For example it will not work with Matrix<double, 2, Dynamic>.
Example:
Output:
See also
resize(Index,Index), resize(NoChange_t, Index), resize(Index, NoChange_t)
    {
      EIGEN_STATIC_ASSERT_VECTOR_ONLY(PlainObjectBase)
      eigen_assert(((SizeAtCompileTime == Dynamic && (MaxSizeAtCompileTime==Dynamic || size<=MaxSizeAtCompileTime)) || SizeAtCompileTime == size) && size>=0);
      #ifdef EIGEN_INITIALIZE_COEFFS
        bool size_changed = size != this->size();
      #endif
      if(RowsAtCompileTime == 1)
        m_storage.resize(size, 1, size);
      else
        m_storage.resize(size, size, 1);
      #ifdef EIGEN_INITIALIZE_COEFFS
        if(size_changed) EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED
      #endif
    }
resize() [4/4]
EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize (NoChange_t , Index cols) inline inherited
Resizes the matrix, changing only the number of columns. For the parameter of type NoChange_t, just pass the special value NoChange as in the example below.
Example:
Output:
See also
resize(Index,Index)
    {
      resize(rows(), cols);
    }
resizeLike()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike (const EigenBase< OtherDerived > & _other) inline inherited
Resizes *this to have the same dimensions as other. Takes care of doing all the checking that's needed.
Note that copying a row-vector into a vector (and conversely) is allowed. The resizing, if any, is then done in the appropriate way so that row-vectors remain row-vectors and vectors remain vectors.
    {
      const OtherDerived& other = _other.derived();
      internal::check_rows_cols_for_overflow<MaxSizeAtCompileTime>::run(other.rows(), other.cols());
      const Index othersize = other.rows()*other.cols();
      if(RowsAtCompileTime == 1)
      {
        eigen_assert(other.rows() == 1 || other.cols() == 1);
        resize(1, othersize);
      }
      else if(ColsAtCompileTime == 1)
      {
        eigen_assert(other.rows() == 1 || other.cols() == 1);
        resize(othersize, 1);
      }
      else resize(other.rows(), other.cols());
    }
rows()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::rows () const inline inherited
{ return m_storage.rows(); }
setConstant() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setConstant (Index rows, Index cols, const Scalar & val) inherited
Resizes to the given size, and sets all coefficients in this expression to the given value val.
Parameters
rows the new number of rows
cols the new number of columns
val the value to which all coefficients are set
Example:
Output:
See also
MatrixBase::setConstant(const Scalar&), setConstant(Index,const Scalar&), class CwiseNullaryOp, MatrixBase::Constant(const Scalar&)
{
  resize(rows, cols);
  return setConstant(val);
}
setConstant() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setConstant (Index size, const Scalar & val) inherited
Resizes to the given size, and sets all coefficients in this expression to the given value val.
\only_for_vectors
Example:
Output:
See also
MatrixBase::setConstant(const Scalar&), setConstant(Index,Index,const Scalar&), class CwiseNullaryOp, MatrixBase::Constant(const Scalar&)
{
  resize(size);
  return setConstant(val);
}
setOnes() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setOnes (Index rows, Index cols) inherited
Resizes to the given size, and sets all coefficients in this expression to one.
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See also
MatrixBase::setOnes(), setOnes(Index), class CwiseNullaryOp, MatrixBase::Ones()
{
  resize(rows, cols);
  return setConstant(Scalar(1));
}
setOnes() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setOnes (Index newSize) inherited
Resizes to the given newSize, and sets all coefficients in this expression to one.
\only_for_vectors
Example:
Output:
See also
MatrixBase::setOnes(), setOnes(Index,Index), class CwiseNullaryOp, MatrixBase::Ones()
{
  resize(newSize);
  return setConstant(Scalar(1));
}
setRandom() [1/2]
EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setRandom (Index rows, Index cols) inherited
Resizes to the given size, and sets all coefficients in this expression to random values.
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
\not_reentrant
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See also
DenseBase::setRandom(), setRandom(Index), class CwiseNullaryOp, DenseBase::Random()
{
  resize(rows, cols);
  return setRandom();
}
setRandom() [2/2]
EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setRandom (Index newSize) inherited
Resizes to the given newSize, and sets all coefficients in this expression to random values.
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
\only_for_vectors \not_reentrant
Example:
Output:
See also
DenseBase::setRandom(), setRandom(Index,Index), class CwiseNullaryOp, DenseBase::Random()
{
  resize(newSize);
  return setRandom();
}
setZero() [1/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setZero (Index rows, Index cols) inherited
Resizes to the given size, and sets all coefficients in this expression to zero.
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See also
DenseBase::setZero(), setZero(Index), class CwiseNullaryOp, DenseBase::Zero()
{
  resize(rows, cols);
  return setConstant(Scalar(0));
}
setZero() [2/2]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::setZero (Index newSize) inherited
Resizes to the given size, and sets all coefficients in this expression to zero.
\only_for_vectors
Example:
Output:
See also
DenseBase::setZero(), setZero(Index,Index), class CwiseNullaryOp, DenseBase::Zero()
{
  resize(newSize);
  return setConstant(Scalar(0));
}
swap() [1/2]
EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::swap (DenseBase< OtherDerived > & other) inline inherited
    {
      enum { SwapPointers = internal::is_same<Derived, OtherDerived>::value && Base::SizeAtCompileTime==Dynamic };
      internal::matrix_swap_impl<Derived, OtherDerived, bool(SwapPointers)>::run(this->derived(), other.derived());
    }
swap() [2/2]
EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::swap (DenseBase< OtherDerived > const & other) inline inherited
    { Base::swap(other.derived()); }
writePacket() [1/2]
EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::writePacket (Index index, const PacketScalar & val) inline inherited
    {
      internal::pstoret<Scalar, PacketScalar, StoreMode>(m_storage.data() + index, val);
    }
writePacket() [2/2]
EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::writePacket (Index rowId, Index colId, const PacketScalar & val) inline inherited
    {
      internal::pstoret<Scalar, PacketScalar, StoreMode>
              (m_storage.data() + (Flags & RowMajorBit
                                   ? colId + rowId * m_storage.cols()
                                   : rowId + colId * m_storage.rows()), val);
    }
Friends And Related Symbol Documentation
internal::conservative_resize_like_impl
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> template<typename Derived , typename OtherDerived , bool IsVector> friend struct internal::conservative_resize_like_impl friend
internal::matrix_swap_impl
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> template<typename MatrixType , typename OtherDerived , bool SwapPointers> friend struct internal::matrix_swap_impl friend
Member Data Documentation
m_storage
template<typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> DenseStorage<Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options> Eigen::PlainObjectBase< Derived >::m_storage protected
Referenced by Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array(), and Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/Array.h