Prusa Slicer: Slic3r::GUI::FileGet::priv Struct Reference
Slic3r::GUI::FileGet::priv Struct Reference
Public Member Functions
priv (int ID, std::string &&url, const std::string &filename, wxEvtHandler *evt_handler, const boost::filesystem::path &dest_folder)
void get_perform ()
Public Attributes
const int m_id
std::string m_url
std::string m_filename
std::thread m_io_thread
wxEvtHandler * m_evt_handler
boost::filesystem::path m_dest_folder
boost::filesystem::path m_tmp_path
std::atomic_bool m_cancel { false }
std::atomic_bool m_pause { false }
std::atomic_bool m_stopped { false }
size_t m_written { 0 }
size_t m_absolute_size { 0 }
Detailed Description
Constructor & Destructor Documentation
priv()
Slic3r::GUI::FileGet::priv::priv (int ID, std::string && url, const std::string & filename, wxEvtHandler * evt_handler, const boost::filesystem::path & dest_folder)
  : m_id(ID)
  , m_url(std::move(url))
  , m_filename(filename)
  , m_evt_handler(evt_handler)
  , m_dest_folder(dest_folder)
{
}
Member Function Documentation
get_perform()
void Slic3r::GUI::FileGet::priv::get_perform ()
{
  assert(m_evt_handler);
  assert(!m_url.empty());
  assert(!m_filename.empty());
  assert(boost::filesystem::is_directory(m_dest_folder));
  m_stopped = false;
  // open dest file
  if (m_written == 0)
  {
    boost::filesystem::path dest_path = m_dest_folder / m_filename;
    std::string extension = boost::filesystem::extension(dest_path);
    std::string just_filename = m_filename.substr(0, m_filename.size() - extension.size());
    std::string final_filename = just_filename;
        // Find unsed filename
    try {
      size_t version = 0;
      while (boost::filesystem::exists(m_dest_folder / (final_filename + extension)) || boost::filesystem::exists(m_dest_folder / (final_filename + extension + "." + std::to_string(get_current_pid()) + ".download")))
      {
        ++version;
        if (version > 999) {
          wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_ERROR);
          evt->SetString(GUI::format_wxstr(L"Failed to find suitable filename. Last name: %1%." , (m_dest_folder / (final_filename + extension)).string()));
          evt->SetInt(m_id);
          m_evt_handler->QueueEvent(evt);
          return;
        }
        final_filename = GUI::format("%1%(%2%)", just_filename, std::to_string(version));
      }
    } catch (const boost::filesystem::filesystem_error& e)
    {
      wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_ERROR);
      evt->SetString(e.what());
      evt->SetInt(m_id);
      m_evt_handler->QueueEvent(evt);
      return;
    }
    m_filename = final_filename + extension;
    m_tmp_path = m_dest_folder / (m_filename + "." + std::to_string(get_current_pid()) + ".download");
    wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_NAME_CHANGE);
    evt->SetString(boost::nowide::widen(m_filename));
    evt->SetInt(m_id);
    m_evt_handler->QueueEvent(evt);
  }
  boost::filesystem::path dest_path = m_dest_folder / m_filename;
  wxString temp_path_wstring(m_tmp_path.wstring());
  //std::cout << "dest_path: " << dest_path.string() << std::endl;
  //std::cout << "m_tmp_path: " << m_tmp_path.string() << std::endl;
  BOOST_LOG_TRIVIAL(info) << GUI::format("Starting download from %1% to %2%. Temp path is %3%",m_url, dest_path, m_tmp_path);
  FILE* file;
  // open file for writting
  if (m_written == 0)
    file = fopen(temp_path_wstring.c_str(), "wb");
  else
    file = fopen(temp_path_wstring.c_str(), "ab");
  //assert(file != NULL);
  if (file == NULL) {
    wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_ERROR);
    // TRN %1% = file path
    evt->SetString(GUI::format_wxstr(_L("Can't create file at %1%"), temp_path_wstring));
    evt->SetInt(m_id);
    m_evt_handler->QueueEvent(evt);
    return;
  }
  std:: string range_string = std::to_string(m_written) + "-";
  size_t written_previously = m_written;
  size_t written_this_session = 0;
  Http::get(m_url)
    .size_limit(DOWNLOAD_SIZE_LIMIT) //more?
    .set_range(range_string)
    .on_progress([&](Http::Progress progress, bool& cancel) {
      // to prevent multiple calls into following ifs (m_cancel / m_pause)
      if (m_stopped){
        cancel = true;
        return;
      }
      if (m_cancel) {
        m_stopped = true;
        fclose(file);
        // remove canceled file
        std::remove(m_tmp_path.string().c_str());
        m_written = 0;
        cancel = true;
        wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_CANCELED);
        evt->SetInt(m_id);
        m_evt_handler->QueueEvent(evt);
        return;
        // TODO: send canceled event?
      }
      if (m_pause) {
        m_stopped = true;
        fclose(file);
        cancel = true;
        if (m_written == 0)
          std::remove(m_tmp_path.string().c_str());
        wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_PAUSED);
        evt->SetInt(m_id);
        m_evt_handler->QueueEvent(evt);
        return;
      }
      if (m_absolute_size < progress.dltotal) {
        m_absolute_size = progress.dltotal;
      }
      if (progress.dlnow != 0) {
        if (progress.dlnow - written_this_session > DOWNLOAD_MAX_CHUNK_SIZE || progress.dlnow == progress.dltotal) {
          try
          {
            std::string part_for_write = progress.buffer.substr(written_this_session, progress.dlnow);
            fwrite(part_for_write.c_str(), 1, part_for_write.size(), file);
          }
          catch (const std::exception& e)
          {
            // fclose(file); do it?
            wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_ERROR);
            evt->SetString(e.what());
            evt->SetInt(m_id);
            m_evt_handler->QueueEvent(evt);
            cancel = true;
            return;
          }
          written_this_session = progress.dlnow;
          m_written = written_previously + written_this_session;
        }
        wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_PROGRESS);
        int percent_total = (written_previously + progress.dlnow) * 100 / m_absolute_size;
        evt->SetString(std::to_string(percent_total));
        evt->SetInt(m_id);
        m_evt_handler->QueueEvent(evt);
      }
    })
    .on_error([&](std::string body, std::string error, unsigned http_status) {
      if (file != NULL)
        fclose(file);
      wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_ERROR);
      if (!error.empty())
        evt->SetString(GUI::from_u8(error));
      else
        evt->SetString(GUI::from_u8(body));
      evt->SetInt(m_id);
      m_evt_handler->QueueEvent(evt);
    })
    .on_complete([&](std::string body, unsigned /* http_status */) {
      // TODO: perform a body size check
      //
      //size_t body_size = body.size();
      //if (body_size != expected_size) {
      //  return;
      //}
      try
      {
        /*
        if (m_written < body.size())
        {
          // this code should never be entered. As there should be on_progress call after last bit downloaded.
          std::string part_for_write = body.substr(m_written);
          fwrite(part_for_write.c_str(), 1, part_for_write.size(), file);
        }
        */
        fclose(file);
        boost::filesystem::rename(m_tmp_path, dest_path);
      }
      catch (const std::exception& /*e*/)
      {
        //TODO: report?
        //error_message = GUI::format("Failed to write and move %1% to %2%", tmp_path, dest_path);
        wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_ERROR);
        evt->SetString("Failed to write and move.");
        evt->SetInt(m_id);
        m_evt_handler->QueueEvent(evt);
        return;
      }
      wxCommandEvent* evt = new wxCommandEvent(EVT_DWNLDR_FILE_COMPLETE);
      evt->SetString(dest_path.wstring());
      evt->SetInt(m_id);
      m_evt_handler->QueueEvent(evt);
    })
    .perform_sync();
}
References _L, Slic3r::Http::Progress::buffer, Slic3r::GUI::FileGet::cancel(), Slic3r::Http::Progress::dlnow, Slic3r::Http::Progress::dltotal, Slic3r::GUI::DOWNLOAD_MAX_CHUNK_SIZE, Slic3r::GUI::DOWNLOAD_SIZE_LIMIT, error, Slic3r::GUI::format(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::from_u8(), Slic3r::Http::get(), Slic3r::get_current_pid(), L, Slic3r::Http::on_progress(), Slic3r::Http::set_range(), Slic3r::Http::size_limit(), version, and boost::nowide::widen().
Member Data Documentation
m_absolute_size
size_t Slic3r::GUI::FileGet::priv::m_absolute_size { 0 }
m_cancel
std::atomic_bool Slic3r::GUI::FileGet::priv::m_cancel { false }
m_dest_folder
boost::filesystem::path Slic3r::GUI::FileGet::priv::m_dest_folder
m_evt_handler
wxEvtHandler* Slic3r::GUI::FileGet::priv::m_evt_handler
m_filename
std::string Slic3r::GUI::FileGet::priv::m_filename
m_id
const int Slic3r::GUI::FileGet::priv::m_id
m_io_thread
std::thread Slic3r::GUI::FileGet::priv::m_io_thread
m_pause
std::atomic_bool Slic3r::GUI::FileGet::priv::m_pause { false }
m_stopped
std::atomic_bool Slic3r::GUI::FileGet::priv::m_stopped { false }
m_tmp_path
boost::filesystem::path Slic3r::GUI::FileGet::priv::m_tmp_path
m_url
std::string Slic3r::GUI::FileGet::priv::m_url
m_written
size_t Slic3r::GUI::FileGet::priv::m_written { 0 }
The documentation for this struct was generated from the following file:
src/slic3r/GUI/DownloaderFileGet.cpp