Prusa Slicer: Slic3r::ConfigOptionEnum< T > Class Template Reference
Slic3r::ConfigOptionEnum< T > Class Template Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionEnum ()
ConfigOptionEnum (T _value)
ConfigOptionType type () const override
ConfigOption * clone () const override
ConfigOptionEnum< T > & operator= (const ConfigOption *opt)
bool operator== (const ConfigOptionEnum< T > &rhs) const throw ()
bool operator< (const ConfigOptionEnum< T > &rhs) const throw ()
int getInt () const override
void setInt (int val) override
bool operator== (const ConfigOption &rhs) const override
void set (const ConfigOption *rhs) override
std::string serialize () const override
bool deserialize (const std::string &str, bool append=false) override
operator T () const
bool operator== (const T &rhs) const throw ()
bool operator!= (const T &rhs) const throw ()
bool operator!= (const ConfigOption &rhs) const
bool operator< (const T &rhs) const throw ()
size_t hash () const override throw ()
virtual double getFloat () const
virtual bool getBool () const
bool is_scalar () const
bool is_vector () const
virtual bool nullable () const
virtual bool is_nil () const
virtual bool overriden_by (const ConfigOption *rhs) const
virtual bool apply_override (const ConfigOption *rhs)
Static Public Member Functions
static ConfigOptionType static_type ()
static bool has (T value)
static const t_config_enum_names & get_enum_names ()
static const t_config_enum_values & get_enum_values ()
static bool from_string (const std::string &str, T &value)
Public Attributes
T value
Detailed Description
template<class T>
class Slic3r::ConfigOptionEnum< T >
Constructor & Destructor Documentation
ConfigOptionEnum() [1/2]
template<class T > Slic3r::ConfigOptionEnum< T >::ConfigOptionEnum () inline
: ConfigOptionSingle<T>(static_cast<T>(0)) {}
ConfigOptionEnum() [2/2]
template<class T > Slic3r::ConfigOptionEnum< T >::ConfigOptionEnum (T _value) inline explicit
: ConfigOptionSingle<T>(_value) {}
Member Function Documentation
apply_override()
virtual bool Slic3r::ConfigOption::apply_override (const ConfigOption * rhs) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      if (*this == *rhs)
        return false;
      *this = *rhs;
      return true;
    }
Referenced by Slic3r::print_config_diffs().
clone()
template<class T > ConfigOption * Slic3r::ConfigOptionEnum< T >::clone () const inline override virtual
Implements Slic3r::ConfigOption.
{ return new ConfigOptionEnum<T>(*this); }
deserialize()
template<class T > bool Slic3r::ConfigOptionEnum< T >::deserialize (const std::string & str, bool append = false) inline override virtual
Implements Slic3r::ConfigOption.
    {
        UNUSED(append);
        return from_string(str, this->value);
    }
References Slic3r::append(), Slic3r::ConfigOptionEnum< T >::from_string(), and UNUSED.
from_string()
template<class T > static bool Slic3r::ConfigOptionEnum< T >::from_string (const std::string & str, T & value) inline static
    {
        const t_config_enum_values &enum_keys_map = ConfigOptionEnum<T>::get_enum_values();
        auto it = enum_keys_map.find(str);
        if (it == enum_keys_map.end())
            return false;
        value = static_cast<T>(it->second);
        return true;
    }
References Slic3r::ConfigOptionEnum< T >::get_enum_values(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::ConfigOptionEnum< T >::deserialize().
get_enum_names()
template<class T > static const t_config_enum_names & Slic3r::ConfigOptionEnum< T >::get_enum_names () static
Referenced by Slic3r::PrintConfigDef::init_sla_params(), Slic3r::PrintConfigDef::init_sla_support_params(), Slic3r::ConfigOptionEnum< T >::serialize(), and Slic3r::ConfigOptionEnumDef::set_enum_map().
get_enum_values()
template<class T > static const t_config_enum_values & Slic3r::ConfigOptionEnum< T >::get_enum_values () static
Referenced by Slic3r::ConfigOptionEnum< T >::from_string(), Slic3r::ConfigOptionEnum< T >::has(), Slic3r::Fill::new_from_type(), and Slic3r::ConfigOptionEnumDef::set_enum_map().
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
template<class T > int Slic3r::ConfigOptionEnum< T >::getInt () const inline override virtual
Reimplemented from Slic3r::ConfigOption.
{ return (int)this->value; }
References Slic3r::ConfigOptionSingle< T >::value.
has()
template<class T > static bool Slic3r::ConfigOptionEnum< T >::has (T value) inline static
    {
        for (const auto &kvp : ConfigOptionEnum<T>::get_enum_values())
            if (kvp.second == value)
                return true;
        return false;
    }
References Slic3r::ConfigOptionEnum< T >::get_enum_values(), and Slic3r::ConfigOptionSingle< T >::value.
hash()
template<class T > size_t Slic3r::ConfigOptionSingle< T >::hash () const throw () inline override virtual inherited
Implements Slic3r::ConfigOption.
{ return std::hash<T>{}(this->value); }
References Slic3r::ConfigOptionSingle< T >::value.
is_nil()
virtual bool Slic3r::ConfigOption::is_nil () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVectorBase, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::GCode::append_full_config(), Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_full_label(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::print_config_diffs(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::validate(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nullable()
virtual bool Slic3r::ConfigOption::nullable () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::ConfigBase::null_nullables(), Slic3r::ConfigOption::overriden_by(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::validate().
operator T()
template<class T > Slic3r::ConfigOptionSingle< T >::operator T () const inline inherited
{ return this->value; }
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
template<class T > bool Slic3r::ConfigOptionSingle< T >::operator!= (const T & rhs) const throw () inline inherited
{ return this->value != rhs; }
operator<() [1/2]
template<class T > bool Slic3r::ConfigOptionEnum< T >::operator< (const ConfigOptionEnum< T > & rhs) const throw () inline
{ return int(this->value) < int(rhs.value); }
operator<() [2/2]
template<class T > bool Slic3r::ConfigOptionSingle< T >::operator< (const T & rhs) const throw () inline inherited
{ return this->value < rhs; }
operator=()
template<class T > ConfigOptionEnum< T > & Slic3r::ConfigOptionEnum< T >::operator= (const ConfigOption * opt) inline
{ this->set(opt); return *this; }
References Slic3r::ConfigOptionEnum< T >::set().
operator==() [1/3]
template<class T > bool Slic3r::ConfigOptionEnum< T >::operator== (const ConfigOption & rhs) const inline override virtual
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionEnum<T>: Comparing incompatible types");
        // rhs could be of the following type: ConfigOptionEnumGeneric or ConfigOptionEnum<T>
        return this->value == (T)rhs.getInt();
    }
References Slic3r::ConfigOption::getInt(), and Slic3r::ConfigOption::type().
operator==() [2/3]
template<class T > bool Slic3r::ConfigOptionEnum< T >::operator== (const ConfigOptionEnum< T > & rhs) const throw () inline
{ return this->value == rhs.value; }
operator==() [3/3]
template<class T > bool Slic3r::ConfigOptionSingle< T >::operator== (const T & rhs) const throw () inline inherited
{ return this->value == rhs; }
overriden_by()
virtual bool Slic3r::ConfigOption::overriden_by (const ConfigOption * rhs) const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      assert(! this->nullable() && ! rhs->nullable());
      return *this != *rhs;
    }
References Slic3r::ConfigOption::nullable().
Referenced by Slic3r::print_config_diffs().
serialize()
template<class T > std::string Slic3r::ConfigOptionEnum< T >::serialize () const inline override virtual
Implements Slic3r::ConfigOption.
    {
        const t_config_enum_names& names = ConfigOptionEnum<T>::get_enum_names();
        assert(static_cast<int>(this->value) < int(names.size()));
        return names[static_cast<int>(this->value)];
    }
References Slic3r::ConfigOptionEnum< T >::get_enum_names(), and Slic3r::ConfigOptionSingle< T >::value.
set()
template<class T > void Slic3r::ConfigOptionEnum< T >::set (const ConfigOption * rhs) inline override virtual
Implements Slic3r::ConfigOption.
{
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionEnum<T>: Assigning an incompatible type");
        // rhs could be of the following type: ConfigOptionEnumGeneric or ConfigOptionEnum<T>
        this->value = (T)rhs->getInt();
    }
References Slic3r::ConfigOption::getInt(), and Slic3r::ConfigOption::type().
Referenced by Slic3r::ConfigOptionEnum< T >::operator=().
setInt()
template<class T > void Slic3r::ConfigOptionEnum< T >::setInt (int val) inline override virtual
Reimplemented from Slic3r::ConfigOption.
{ this->value = T(val); }
static_type()
template<class T > static ConfigOptionType Slic3r::ConfigOptionEnum< T >::static_type () inline static
{ return coEnum; }
References Slic3r::coEnum.
Referenced by Slic3r::ConfigOptionEnum< T >::type().
type()
template<class T > ConfigOptionType Slic3r::ConfigOptionEnum< T >::type () const inline override virtual
Implements Slic3r::ConfigOption.
{ return static_type(); }
References Slic3r::ConfigOptionEnum< T >::static_type().
Member Data Documentation
value
template<class T > T Slic3r::ConfigOptionSingle< T >::value inherited
Referenced by Slic3r::GUI::GLCanvas3D::_render_overlays(), Slic3r::GCodeProcessor::apply_config(), Slic3r::GCodeProcessor::apply_config(), Slic3r::apply_to_print_region_config(), Slic3r::GUI::ColourPicker::BUILD(), Slic3r::GUI::StaticText::BUILD(), Slic3r::GUI::BedShapePanel::build_panel(), Slic3r::clamp_exturder_to_default(), Slic3r::PrinterPresetCollection::default_preset_for(), Slic3r::Flow::extrusion_width(), Slic3r::first_positive(), Slic3r::PrintRegion::flow(), Slic3r::ConfigOptionEnum< T >::from_string(), Slic3r::GUI::Materials::get_filament_vendor(), Slic3r::GUI::Materials::get_material_type(), Slic3r::GUI::Materials::get_material_vendor(), Slic3r::PrintHost::get_print_host(), get_printer_technology(), Slic3r::get_raster_params(), Slic3r::GUI::get_string_value(), Slic3r::ConfigOptionEnum< T >::getInt(), Slic3r::PrintConfigDef::handle_legacy(), Slic3r::handle_legacy_project_loaded(), Slic3r::handle_legacy_sla(), Slic3r::ConfigOptionEnum< T >::has(), Slic3r::ConfigOptionSingle< T >::hash(), Slic3r::PrintObject::invalidate_state_by_config_options(), Slic3r::PresetHints::maximum_volumetric_flow_description(), Slic3r::min_object_distance(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::ConfigOptionSingle< bool >::operator bool(), Slic3r::ConfigOptionSingle< T >::operator==(), Slic3r::DynamicConfig::read_cli(), Slic3r::CLI::run(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::serialize(), Slic3r::ConfigOptionSingle< T >::set(), Slic3r::ConfigOptionVector< T >::set(), Slic3r::ConfigOptionVector< T >::set_at(), Slic3r::GUI::Plater::set_bed_shape(), Slic3r::CLI::setup(), Slic3r::AvoidCrossingPerimeters::travel_to(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), and Slic3r::validate().
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp