Prusa Slicer: Slic3r::MutablePolygon::range Class Reference
Slic3r::MutablePolygon::range Class Reference
#include <src/libslic3r/MutablePolygon.hpp>
Public Member Functions
range (MutablePolygon &poly)
range (MutablePolygon::iterator begin, MutablePolygon::iterator end)
MutablePolygon::iterator begin () const
MutablePolygon::iterator end () const
bool empty () const
MutablePolygon::iterator process_next ()
void advance_front ()
void retract_back ()
MutablePolygon::iterator remove_front (MutablePolygon::iterator it)
MutablePolygon::iterator remove_back (MutablePolygon::iterator it)
Private Member Functions
void make_empty ()
Private Attributes
MutablePolygon::iterator m_begin
MutablePolygon::iterator m_end
Detailed Description
Constructor & Destructor Documentation
range() [1/2]
Slic3r::MutablePolygon::range::range (MutablePolygon & poly) inline
: range(poly.begin(), poly.end()) {}
range() [2/2]
Slic3r::MutablePolygon::range::range (MutablePolygon::iterator begin, MutablePolygon::iterator end) inline
: m_begin(begin), m_end(end) {}
Member Function Documentation
advance_front()
void Slic3r::MutablePolygon::range::advance_front () inline
{
            assert(! this->empty());
            if (m_begin == m_end)
                this->make_empty();
            else
                ++ m_begin;
        }
References empty(), m_begin, m_end, and make_empty().
Referenced by process_next(), and remove_front().
begin()
MutablePolygon::iterator Slic3r::MutablePolygon::range::begin () const inline
{ return m_begin; }
References m_begin.
empty()
bool Slic3r::MutablePolygon::range::empty () const inline
{ return !m_begin.valid(); }
References m_begin, and Slic3r::MutablePolygon::iterator::valid().
Referenced by advance_front(), process_next(), remove_back(), remove_front(), retract_back(), and Slic3r::smooth_outward().
end()
MutablePolygon::iterator Slic3r::MutablePolygon::range::end () const inline
{ return m_end; }
References m_end.
make_empty()
void Slic3r::MutablePolygon::range::make_empty () inline private
{
            m_begin.m_idx = -1;
            m_end.m_idx = -1;
        }
References m_begin, m_end, and Slic3r::MutablePolygon::iterator::m_idx.
Referenced by advance_front(), and retract_back().
process_next()
MutablePolygon::iterator Slic3r::MutablePolygon::range::process_next () inline
{
            assert(!this->empty());
            MutablePolygon::iterator out = m_begin;
            this->advance_front();
            return out;
        }
References advance_front(), empty(), and m_begin.
Referenced by Slic3r::smooth_outward().
remove_back()
MutablePolygon::iterator Slic3r::MutablePolygon::range::remove_back (MutablePolygon::iterator it) inline
{
            if (! this->empty() && m_end == it)
                this->retract_back();
            return it.remove();
        }
References empty(), m_end, Slic3r::MutablePolygon::iterator::remove(), and retract_back().
Referenced by Slic3r::clip_narrow_corner().
remove_front()
MutablePolygon::iterator Slic3r::MutablePolygon::range::remove_front (MutablePolygon::iterator it) inline
{
            if (! this->empty() && m_begin == it)
                this->advance_front();
            return it.remove();
        }
References advance_front(), empty(), m_begin, and Slic3r::MutablePolygon::iterator::remove().
Referenced by Slic3r::clip_narrow_corner().
retract_back()
void Slic3r::MutablePolygon::range::retract_back () inline
{
            assert(! this->empty());
            if (m_begin == m_end)
                this->make_empty();
            else
                -- m_end;
        }
References empty(), m_begin, m_end, and make_empty().
Referenced by remove_back().
Member Data Documentation
m_begin
MutablePolygon::iterator Slic3r::MutablePolygon::range::m_begin private
Referenced by advance_front(), begin(), empty(), make_empty(), process_next(), remove_front(), and retract_back().
m_end
MutablePolygon::iterator Slic3r::MutablePolygon::range::m_end private
Referenced by advance_front(), end(), make_empty(), remove_back(), and retract_back().
The documentation for this class was generated from the following file:
src/libslic3r/MutablePolygon.hpp