Prusa Slicer: Dict Struct Reference
Dict Struct Reference
#include <src/glu-libtess/src/dict-list.h>
Public Attributes
DictNode head
void * frame
int(* leq)(void *frame, DictKey key1, DictKey key2)
Detailed Description
Member Data Documentation
frame
void * Dict::frame
Referenced by dictInsertBefore(), dictNewDict(), and dictSearch().
head
DictNode Dict::head
Referenced by dictDeleteDict(), dictNewDict(), and dictSearch().
leq
int(* Dict::leq)(void *frame, DictKey key1, DictKey key2)
Referenced by dictInsertBefore(), dictNewDict(), and dictSearch().
The documentation for this struct was generated from the following files:
src/glu-libtess/src/dict-list.h
src/glu-libtess/src/dict.h