Prusa Slicer: src/imgui/imgui_stdlib.cpp File Reference
imgui_stdlib.cpp File Reference
#include "imgui.h"
#include "imgui_stdlib.h"
Classes
struct InputTextCallback_UserData
Functions
static int InputTextCallback (ImGuiInputTextCallbackData *data)
Class Documentation
InputTextCallback_UserData
struct InputTextCallback_UserData
Class Members
ImGuiInputTextCallback ChainCallback
void * ChainCallbackUserData
string * Str
Function Documentation
InputTextCallback()
static int InputTextCallback (ImGuiInputTextCallbackData * data) static
{
    InputTextCallback_UserData* user_data = (InputTextCallback_UserData*)data->UserData;
    if (data->EventFlag == ImGuiInputTextFlags_CallbackResize)
    {
        // Resize string callback
        // If for some reason we refuse the new length (BufTextLen) and/or capacity (BufSize) we need to set them back to what we want.
        std::string* str = user_data->Str;
        IM_ASSERT(data->Buf == str->c_str());
        str->resize(data->BufTextLen);
        data->Buf = (char*)str->c_str();
    }
    else if (user_data->ChainCallback)
    {
        // Forward to user callback, if any
        data->UserData = user_data->ChainCallbackUserData;
        return user_data->ChainCallback(data);
    }
    return 0;
}
References InputTextCallback_UserData::ChainCallback, InputTextCallback_UserData::ChainCallbackUserData, IM_ASSERT, ImGuiInputTextFlags_CallbackResize, and InputTextCallback_UserData::Str.
Referenced by ImGui::InputText(), ImGui::InputTextMultiline(), and ImGui::InputTextWithHint().