Prusa Slicer: std::numeric_limits< const Eigen::half > Struct Reference
std::numeric_limits< const Eigen::half > Struct Reference
#include <src/eigen/Eigen/src/Core/arch/CUDA/Half.h>
Static Public Member Functions
static Eigen::half() min ()
static Eigen::half lowest ()
static Eigen::half() max ()
static Eigen::half epsilon ()
static Eigen::half round_error ()
static Eigen::half infinity ()
static Eigen::half quiet_NaN ()
static Eigen::half signaling_NaN ()
static Eigen::half denorm_min ()
Static Public Attributes
static const bool is_specialized = true
static const bool is_signed = true
static const bool is_integer = false
static const bool is_exact = false
static const bool has_infinity = true
static const bool has_quiet_NaN = true
static const bool has_signaling_NaN = true
static const float_denorm_style has_denorm = denorm_present
static const bool has_denorm_loss = false
static const std::float_round_style round_style = std::round_to_nearest
static const bool is_iec559 = false
static const bool is_bounded = false
static const bool is_modulo = false
static const int digits = 11
static const int digits10 = 3
static const int max_digits10 = 5
static const int radix = 2
static const int min_exponent = -13
static const int min_exponent10 = -4
static const int max_exponent = 16
static const int max_exponent10 = 4
static const bool traps = true
static const bool tinyness_before = false
Detailed Description
Member Function Documentation
denorm_min()
static Eigen::half std::numeric_limits< Eigen::half >::denorm_min () inline static inherited
{ return Eigen::half_impl::raw_uint16_to_half(0x1); }
References Eigen::half_impl::raw_uint16_to_half().
epsilon()
static Eigen::half std::numeric_limits< Eigen::half >::epsilon () inline static inherited
{ return Eigen::half_impl::raw_uint16_to_half(0x0800); }
References Eigen::half_impl::raw_uint16_to_half().
infinity()
static Eigen::half std::numeric_limits< Eigen::half >::infinity () inline static inherited
{ return Eigen::half_impl::raw_uint16_to_half(0x7c00); }
References Eigen::half_impl::raw_uint16_to_half().
lowest()
static Eigen::half std::numeric_limits< Eigen::half >::lowest () inline static inherited
{ return Eigen::half_impl::raw_uint16_to_half(0xfbff); }
References Eigen::half_impl::raw_uint16_to_half().
max()
static Eigen::half() std::numeric_limits< Eigen::half >::max () inline static inherited
{ return Eigen::half_impl::raw_uint16_to_half(0x7bff); }
References Eigen::half_impl::raw_uint16_to_half().
min()
static Eigen::half() std::numeric_limits< Eigen::half >::min () inline static inherited
{ return Eigen::half_impl::raw_uint16_to_half(0x400); }
References Eigen::half_impl::raw_uint16_to_half().
quiet_NaN()
static Eigen::half std::numeric_limits< Eigen::half >::quiet_NaN () inline static inherited
{ return Eigen::half_impl::raw_uint16_to_half(0x7e00); }
References Eigen::half_impl::raw_uint16_to_half().
round_error()
static Eigen::half std::numeric_limits< Eigen::half >::round_error () inline static inherited
{ return Eigen::half(0.5); }
signaling_NaN()
static Eigen::half std::numeric_limits< Eigen::half >::signaling_NaN () inline static inherited
{ return Eigen::half_impl::raw_uint16_to_half(0x7e00); }
References Eigen::half_impl::raw_uint16_to_half().
Member Data Documentation
digits
const int std::numeric_limits< Eigen::half >::digits = 11 static inherited
digits10
const int std::numeric_limits< Eigen::half >::digits10 = 3 static inherited
has_denorm
const float_denorm_style std::numeric_limits< Eigen::half >::has_denorm = denorm_present static inherited
has_denorm_loss
const bool std::numeric_limits< Eigen::half >::has_denorm_loss = false static inherited
has_infinity
const bool std::numeric_limits< Eigen::half >::has_infinity = true static inherited
has_quiet_NaN
const bool std::numeric_limits< Eigen::half >::has_quiet_NaN = true static inherited
has_signaling_NaN
const bool std::numeric_limits< Eigen::half >::has_signaling_NaN = true static inherited
is_bounded
const bool std::numeric_limits< Eigen::half >::is_bounded = false static inherited
is_exact
const bool std::numeric_limits< Eigen::half >::is_exact = false static inherited
is_iec559
const bool std::numeric_limits< Eigen::half >::is_iec559 = false static inherited
is_integer
const bool std::numeric_limits< Eigen::half >::is_integer = false static inherited
is_modulo
const bool std::numeric_limits< Eigen::half >::is_modulo = false static inherited
is_signed
const bool std::numeric_limits< Eigen::half >::is_signed = true static inherited
is_specialized
const bool std::numeric_limits< Eigen::half >::is_specialized = true static inherited
max_digits10
const int std::numeric_limits< Eigen::half >::max_digits10 = 5 static inherited
max_exponent
const int std::numeric_limits< Eigen::half >::max_exponent = 16 static inherited
max_exponent10
const int std::numeric_limits< Eigen::half >::max_exponent10 = 4 static inherited
min_exponent
const int std::numeric_limits< Eigen::half >::min_exponent = -13 static inherited
min_exponent10
const int std::numeric_limits< Eigen::half >::min_exponent10 = -4 static inherited
radix
const int std::numeric_limits< Eigen::half >::radix = 2 static inherited
round_style
const std::float_round_style std::numeric_limits< Eigen::half >::round_style = std::round_to_nearest static inherited
tinyness_before
const bool std::numeric_limits< Eigen::half >::tinyness_before = false static inherited
traps
const bool std::numeric_limits< Eigen::half >::traps = true static inherited
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/arch/CUDA/Half.h