Prusa Slicer: Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline > Class Template Reference
Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline > Class Template Reference
#include <src/libslic3r/SLA/AGGRaster.hpp>
Public Types
using TColor = typename PixelRenderer::color_type
using TValue = typename TColor::value_type
using TPixel = typename PixelRenderer::pixel_type
using TRawBuffer = agg::rendering_buffer
enum Orientation { roLandscape , roPortrait }
using TMirroring = std::array< bool, 2 >
Public Member Functions
template<class GammaFn >
AGGRaster (const Resolution &res, const PixelDim &pd, const Trafo &trafo, const TColor &foreground, const TColor &background, GammaFn &&gammafn)
Trafo trafo () const override
Get the resolution of the raster.
Resolution resolution () const
PixelDim pixel_dimensions () const
void draw (const ExPolygon &poly) override
Draw a polygon with holes.
EncodedRaster encode (RasterEncoder encoder) const override
void clear (const TColor color)
Static Public Attributes
static const constexpr TMirroring NoMirror = {false, false}
static const constexpr TMirroring MirrorX = {true, false}
static const constexpr TMirroring MirrorY = {false, true}
static const constexpr TMirroring MirrorXY = {true, true}
Protected Member Functions
void flipy (agg::path_storage &path) const
void flipx (agg::path_storage &path) const
double getPx (const Point &p)
double getPy (const Point &p)
agg::path_storage to_path (const Polygon &poly)
template<class PointVec >
agg::path_storage _to_path (const PointVec &v)
template<class PointVec >
agg::path_storage _to_path_flpxy (const PointVec &v)
template<class PointVec >
agg::path_storage to_path (const PointVec &v)
template<class P >
void _draw (const P &poly)
Protected Attributes
Resolution m_resolution
PixelDim m_pxdim_scaled
std::vector< TPixel > m_buf
agg::rendering_buffer m_rbuf
PixelRenderer m_pixrenderer
agg::renderer_base< PixelRenderer > m_raw_renderer
Renderer< agg::renderer_base< PixelRenderer > > m_renderer
Trafo m_trafo
Scanline m_scanlines
Rasterizer m_rasterizer
Detailed Description
template<class PixelRenderer, template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8>
class Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >
Member Typedef Documentation
TColor
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> using Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::TColor = typename PixelRenderer::color_type
TMirroring
using Slic3r::sla::RasterBase::TMirroring = std::array<bool, 2> inherited
TPixel
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> using Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::TPixel = typename PixelRenderer::pixel_type
TRawBuffer
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> using Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::TRawBuffer = agg::rendering_buffer
TValue
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> using Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::TValue = typename TColor::value_type
Member Enumeration Documentation
Orientation
enum Slic3r::sla::RasterBase::Orientation inherited
Enumerator
roLandscape
roPortrait
{ roLandscape, roPortrait };
Constructor & Destructor Documentation
AGGRaster()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> template<class GammaFn > Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::AGGRaster (const Resolution & res, const PixelDim & pd, const Trafo & trafo, const TColor & foreground, const TColor & background, GammaFn && gammafn) inline
        : m_resolution(res)
        , m_pxdim_scaled(SCALING_FACTOR, SCALING_FACTOR)
        , m_buf(res.pixels())
        , m_rbuf(reinterpret_cast<TValue *>(m_buf.data()),
                 unsigned(res.width_px),
                 unsigned(res.height_px),
                 int(res.width_px *PixelRenderer::num_components))
        , m_pixrenderer(m_rbuf)
        , m_raw_renderer(m_pixrenderer)
        , m_renderer(m_raw_renderer)
        , m_trafo(trafo)
    {
        // Visual Studio compiler gives warnings about possible division by zero.
        assert(pd.w_mm != 0 && pd.h_mm != 0);
        if (pd.w_mm != 0 && pd.h_mm != 0) {
            m_pxdim_scaled.w_mm /= pd.w_mm;
            m_pxdim_scaled.h_mm /= pd.h_mm;
        }
        m_renderer.color(foreground);
        clear(background);
        m_rasterizer.gamma(gammafn);
    }
References Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::clear(), Slic3r::sla::PixelDim::h_mm, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_pxdim_scaled, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_rasterizer, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_renderer, and Slic3r::sla::PixelDim::w_mm.
Member Function Documentation
_draw()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> template<class P > void Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_draw (const P & poly) inline protected
    {
        m_rasterizer.reset();
        m_rasterizer.add_path(to_path(contour(poly)));
        for(auto& h : holes(poly)) m_rasterizer.add_path(to_path(h));
        agg::render_scanlines(m_rasterizer, m_scanlines, m_renderer);
    }
References Slic3r::contour(), Slic3r::holes(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_rasterizer, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_renderer, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_scanlines, agg::render_scanlines(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path().
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::draw().
_to_path()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> template<class PointVec > agg::path_storage Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_to_path (const PointVec & v) inline protected
    {
        agg::path_storage path;
        auto it = v.begin();
        path.move_to(getPx(*it), getPy(*it));
        while(++it != v.end()) path.line_to(getPx(*it), getPy(*it));
        path.line_to(getPx(v.front()), getPy(v.front()));
        return path;
    }
References Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::getPx(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::getPy(), agg::path_base< VertexContainer >::line_to(), and agg::path_base< VertexContainer >::move_to().
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path().
_to_path_flpxy()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> template<class PointVec > agg::path_storage Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_to_path_flpxy (const PointVec & v) inline protected
    {
        agg::path_storage path;
        auto it = v.begin();
        path.move_to(getPy(*it), getPx(*it));
        while(++it != v.end()) path.line_to(getPy(*it), getPx(*it));
        path.line_to(getPy(v.front()), getPx(v.front()));
        return path;
    }
References Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::getPx(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::getPy(), agg::path_base< VertexContainer >::line_to(), and agg::path_base< VertexContainer >::move_to().
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path().
clear()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> void Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::clear (const TColor color) inline
{ m_raw_renderer.clear(color); }
References agg::renderer_base< PixelFormat >::clear(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_raw_renderer.
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::AGGRaster(), and Slic3r::sla::RasterGrayscaleAA::clear().
draw()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> void Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::draw (const ExPolygon & poly) inline override virtual
Draw a polygon with holes.
Implements Slic3r::sla::RasterBase.
{ _draw(poly); }
References Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_draw().
encode()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> EncodedRaster Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::encode (RasterEncoder encoder) const inline override virtual
Implements Slic3r::sla::RasterBase.
    {
        return encoder(m_buf.data(), m_resolution.width_px, m_resolution.height_px, 1);
    }
References Slic3r::sla::Resolution::height_px, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_buf, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_resolution, and Slic3r::sla::Resolution::width_px.
flipx()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> void Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::flipx (agg::path_storage & path) const inline protected
    {
        path.flip_x(0, double(m_resolution.width_px));
    }
References agg::path_base< VertexContainer >::flip_x(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_resolution, and Slic3r::sla::Resolution::width_px.
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path().
flipy()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> void Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::flipy (agg::path_storage & path) const inline protected
    {
        path.flip_y(0, double(m_resolution.height_px));
    }
References agg::path_base< VertexContainer >::flip_y(), Slic3r::sla::Resolution::height_px, and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_resolution.
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path().
getPx()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> double Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::getPx (const Point & p) inline protected
{ return p(0) * m_pxdim_scaled.w_mm; }
References Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_pxdim_scaled, and Slic3r::sla::PixelDim::w_mm.
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_to_path(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_to_path_flpxy().
getPy()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> double Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::getPy (const Point & p) inline protected
{ return p(1) * m_pxdim_scaled.h_mm; }
References Slic3r::sla::PixelDim::h_mm, and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_pxdim_scaled.
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_to_path(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_to_path_flpxy().
pixel_dimensions()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> PixelDim Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::pixel_dimensions () const inline
    {
        return {SCALING_FACTOR / m_pxdim_scaled.w_mm,
                SCALING_FACTOR / m_pxdim_scaled.h_mm};
    }
References Slic3r::sla::PixelDim::h_mm, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_pxdim_scaled, SCALING_FACTOR, and Slic3r::sla::PixelDim::w_mm.
Referenced by Slic3r::sla::raster_to_polygons().
resolution()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> Resolution Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::resolution () const inline
{ return m_resolution; }
References Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_resolution.
Referenced by marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA >::cols(), Slic3r::sla::raster_to_polygons(), Slic3r::sla::RasterGrayscaleAA::read_pixel(), and marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA >::rows().
to_path() [1/2]
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> template<class PointVec > agg::path_storage Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path (const PointVec & v) inline protected
    {
        auto path = m_trafo.flipXY ? _to_path_flpxy(v) : _to_path(v);
        path.translate_all_paths(m_trafo.center_x * m_pxdim_scaled.w_mm,
                                 m_trafo.center_y * m_pxdim_scaled.h_mm);
        if(m_trafo.mirror_x) flipx(path);
        if(m_trafo.mirror_y) flipy(path);
        return path;
    }
References Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_to_path(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_to_path_flpxy(), Slic3r::sla::RasterBase::Trafo::center_x, Slic3r::sla::RasterBase::Trafo::center_y, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::flipx(), Slic3r::sla::RasterBase::Trafo::flipXY, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::flipy(), Slic3r::sla::PixelDim::h_mm, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_pxdim_scaled, Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_trafo, Slic3r::sla::RasterBase::Trafo::mirror_x, Slic3r::sla::RasterBase::Trafo::mirror_y, and Slic3r::sla::PixelDim::w_mm.
to_path() [2/2]
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> agg::path_storage Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path (const Polygon & poly) inline protected
{ return to_path(poly.points); }
References Slic3r::MultiPoint::points, and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path().
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_draw(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path().
trafo()
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> Trafo Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::trafo () const inline override virtual
Get the resolution of the raster.
Implements Slic3r::sla::RasterBase.
{ return m_trafo; }
References Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_trafo.
Referenced by Slic3r::sla::raster_to_polygons().
Member Data Documentation
m_buf
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> std::vector<TPixel> Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_buf protected
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::encode(), and Slic3r::sla::RasterGrayscaleAA::read_pixel().
m_pixrenderer
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> PixelRenderer Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_pixrenderer protected
m_pxdim_scaled
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> PixelDim Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_pxdim_scaled protected
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::AGGRaster(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::getPx(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::getPy(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::pixel_dimensions(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path().
m_rasterizer
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> Rasterizer Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_rasterizer protected
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::AGGRaster(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_draw().
m_raw_renderer
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> agg::renderer_base<PixelRenderer> Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_raw_renderer protected
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::clear().
m_rbuf
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> agg::rendering_buffer Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_rbuf protected
m_renderer
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> Renderer<agg::renderer_base<PixelRenderer> > Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_renderer protected
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::AGGRaster(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_draw().
m_resolution
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> Resolution Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_resolution protected
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::encode(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::flipx(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::flipy(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::resolution().
m_scanlines
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> Scanline Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_scanlines protected
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::_draw().
m_trafo
template<class PixelRenderer , template< class > class Renderer, class Rasterizer = agg::rasterizer_scanline_aa<>, class Scanline = agg::scanline_p8> Trafo Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::m_trafo protected
Referenced by Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path(), and Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::trafo().
MirrorX
const constexpr TMirroring Slic3r::sla::RasterBase::MirrorX = {true, false} static constexpr inherited
MirrorXY
const constexpr TMirroring Slic3r::sla::RasterBase::MirrorXY = {true, true} static constexpr inherited
MirrorY
const constexpr TMirroring Slic3r::sla::RasterBase::MirrorY = {false, true} static constexpr inherited
NoMirror
const constexpr TMirroring Slic3r::sla::RasterBase::NoMirror = {false, false} static constexpr inherited
The documentation for this class was generated from the following file:
src/libslic3r/SLA/AGGRaster.hpp