Prusa Slicer: Slic3r::GCodeThumbnails Namespace Reference
Slic3r::GCodeThumbnails Namespace Reference
Classes
struct CompressedImageBuffer
struct CompressedJPG
struct CompressedPNG
struct CompressedQOI
Functions
std::unique_ptr< CompressedImageBuffer > compress_thumbnail_png (const ThumbnailData &data)
std::unique_ptr< CompressedImageBuffer > compress_thumbnail_jpg (const ThumbnailData &data)
std::unique_ptr< CompressedImageBuffer > compress_thumbnail_qoi (const ThumbnailData &data)
std::unique_ptr< CompressedImageBuffer > compress_thumbnail (const ThumbnailData &data, GCodeThumbnailsFormat format)
template<typename WriteToOutput , typename ThrowIfCanceledCallback >
void export_thumbnails_to_file (ThumbnailsGeneratorCallback &thumbnail_cb, const std::vector< Vec2d > &sizes, GCodeThumbnailsFormat format, WriteToOutput output, ThrowIfCanceledCallback throw_if_canceled)
Function Documentation
compress_thumbnail()
std::unique_ptr< CompressedImageBuffer > Slic3r::GCodeThumbnails::compress_thumbnail (const ThumbnailData & data, GCodeThumbnailsFormat format)
{
    switch (format) {
        case GCodeThumbnailsFormat::PNG:
        default:
            return compress_thumbnail_png(data);
        case GCodeThumbnailsFormat::JPG:
            return compress_thumbnail_jpg(data);
        case GCodeThumbnailsFormat::QOI:
            return compress_thumbnail_qoi(data);
    }
}
References compress_thumbnail_jpg(), compress_thumbnail_png(), compress_thumbnail_qoi(), Slic3r::format(), Slic3r::JPG, Slic3r::PNG, and Slic3r::QOI.
Referenced by export_thumbnails_to_file().
compress_thumbnail_jpg()
std::unique_ptr< CompressedImageBuffer > Slic3r::GCodeThumbnails::compress_thumbnail_jpg (const ThumbnailData & data)
{
    // Take vector of RGBA pixels and flip the image vertically
    std::vector<unsigned char> rgba_pixels(data.pixels.size());
    const unsigned int row_size = data.width * 4;
    for (unsigned int y = 0; y < data.height; ++y) {
        ::memcpy(rgba_pixels.data() + (data.height - y - 1) * row_size, data.pixels.data() + y * row_size, row_size);
    }
    // Store pointers to scanlines start for later use
    std::vector<unsigned char*> rows_ptrs;
    rows_ptrs.reserve(data.height);
    for (unsigned int y = 0; y < data.height; ++y) {
        rows_ptrs.emplace_back(&rgba_pixels[y * row_size]);
    }
    std::vector<unsigned char> compressed_data(data.pixels.size());
    unsigned char* compressed_data_ptr = compressed_data.data();
    unsigned long compressed_data_size = data.pixels.size();
    jpeg_error_mgr err;
    jpeg_compress_struct info;
    info.err = jpeg_std_error(&err);
    jpeg_create_compress(&info);
    jpeg_mem_dest(&info, &compressed_data_ptr, &compressed_data_size);
    info.image_width = data.width;
    info.image_height = data.height;
    info.input_components = 4;
    info.in_color_space = JCS_EXT_RGBA;
    jpeg_set_defaults(&info);
    jpeg_set_quality(&info, 85, TRUE);
    jpeg_start_compress(&info, TRUE);
    jpeg_write_scanlines(&info, rows_ptrs.data(), data.height);
    jpeg_finish_compress(&info);
    jpeg_destroy_compress(&info);
    // FIXME -> Add error checking
    auto out = std::make_unique<CompressedJPG>();
    out->data = malloc(compressed_data_size);
    out->size = size_t(compressed_data_size);
    ::memcpy(out->data, (const void*)compressed_data.data(), out->size);
    return out;
}
References malloc(), and TRUE.
Referenced by compress_thumbnail().
compress_thumbnail_png()
std::unique_ptr< CompressedImageBuffer > Slic3r::GCodeThumbnails::compress_thumbnail_png (const ThumbnailData & data)
{
    auto out = std::make_unique<CompressedPNG>();
    out->data = tdefl_write_image_to_png_file_in_memory_ex((const void*)data.pixels.data(), data.width, data.height, 4, &out->size, MZ_DEFAULT_LEVEL, 1);
    return out;
}
References MZ_DEFAULT_LEVEL, and tdefl_write_image_to_png_file_in_memory_ex().
Referenced by compress_thumbnail().
compress_thumbnail_qoi()
std::unique_ptr< CompressedImageBuffer > Slic3r::GCodeThumbnails::compress_thumbnail_qoi (const ThumbnailData & data)
{
    qoi_desc desc;
    desc.width      = data.width;
    desc.height     = data.height;
    desc.channels   = 4;
    desc.colorspace = QOI_SRGB;
    // Take vector of RGBA pixels and flip the image vertically
    std::vector<uint8_t> rgba_pixels(data.pixels.size() * 4);
    size_t row_size = data.width * 4;
    for (size_t y = 0; y < data.height; ++ y)
        memcpy(rgba_pixels.data() + (data.height - y - 1) * row_size, data.pixels.data() + y * row_size, row_size);
    auto out = std::make_unique<CompressedQOI>();
    int  size;
    out->data = qoi_encode((const void*)rgba_pixels.data(), &desc, &size);
    out->size = size;
    return out;
}
References qoi_desc::channels, qoi_desc::colorspace, qoi_desc::height, qoi_encode(), QOI_SRGB, and qoi_desc::width.
Referenced by compress_thumbnail().
export_thumbnails_to_file()
template<typename WriteToOutput , typename ThrowIfCanceledCallback > void Slic3r::GCodeThumbnails::export_thumbnails_to_file (ThumbnailsGeneratorCallback & thumbnail_cb, const std::vector< Vec2d > & sizes, GCodeThumbnailsFormat format, WriteToOutput output, ThrowIfCanceledCallback throw_if_canceled) inline
{
    // Write thumbnails using base64 encoding
    if (thumbnail_cb != nullptr) {
        static constexpr const size_t max_row_length = 78;
        ThumbnailsList thumbnails = thumbnail_cb(ThumbnailsParams{ sizes, true, true, true, true });
        for (const ThumbnailData& data : thumbnails)
            if (data.is_valid()) {
                auto compressed = compress_thumbnail(data, format);
                if (compressed->data && compressed->size) {
                    std::string encoded;
                    encoded.resize(boost::beast::detail::base64::encoded_size(compressed->size));
                    encoded.resize(boost::beast::detail::base64::encode((void*)encoded.data(), (const void*)compressed->data, compressed->size));
                    output((boost::format("\n;\n; %s begin %dx%d %d\n") % compressed->tag() % data.width % data.height % encoded.size()).str().c_str());
                    while (encoded.size() > max_row_length) {
                        output((boost::format("; %s\n") % encoded.substr(0, max_row_length)).str().c_str());
                        encoded = encoded.substr(max_row_length);
                    }
                    if (encoded.size() > 0)
                        output((boost::format("; %s\n") % encoded).str().c_str());
                    output((boost::format("; %s end\n;\n") % compressed->tag()).str().c_str());
                }
                throw_if_canceled();
            }
    }
}
References compress_thumbnail(), and Slic3r::format().
Referenced by Slic3r::GCode::_do_export().