Prusa Slicer: Slic3r::ConfigOptionFloatOrPercent Class Reference
Slic3r::ConfigOptionFloatOrPercent Class Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionFloatOrPercent ()
ConfigOptionFloatOrPercent (double _value, bool _percent)
ConfigOptionType type () const override
ConfigOption * clone () const override
ConfigOptionFloatOrPercent & operator= (const ConfigOption *opt)
bool operator== (const ConfigOption &rhs) const override
bool operator== (const ConfigOptionFloatOrPercent &rhs) const throw ()
size_t hash () const override throw ()
bool operator< (const ConfigOptionFloatOrPercent &rhs) const throw ()
double get_abs_value (double ratio_over) const
void set (const ConfigOption *rhs) override
std::string serialize () const override
bool deserialize (const std::string &str, bool append=false) override
bool operator== (const ConfigOptionPercent &rhs) const throw ()
bool operator== (const ConfigOptionFloat &rhs) const throw ()
bool operator== (const double &rhs) const throw ()
bool operator< (const ConfigOptionPercent &rhs) const throw ()
bool operator< (const ConfigOptionFloat &rhs) const throw ()
bool operator< (const double &rhs) const throw ()
double getFloat () const override
operator double () const
bool operator!= (const double &rhs) const throw ()
bool operator!= (const ConfigOption &rhs) const
virtual int getInt () const
virtual bool getBool () const
virtual void setInt (int)
bool is_scalar () const
bool is_vector () const
virtual bool nullable () const
virtual bool is_nil () const
virtual bool overriden_by (const ConfigOption *rhs) const
virtual bool apply_override (const ConfigOption *rhs)
Static Public Member Functions
static ConfigOptionType static_type ()
Public Attributes
bool percent
double value
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
Constructor & Destructor Documentation
ConfigOptionFloatOrPercent() [1/2]
Slic3r::ConfigOptionFloatOrPercent::ConfigOptionFloatOrPercent () inline
: ConfigOptionPercent(0), percent(false) {}
Referenced by clone().
ConfigOptionFloatOrPercent() [2/2]
Slic3r::ConfigOptionFloatOrPercent::ConfigOptionFloatOrPercent (double _value, bool _percent) inline explicit
: ConfigOptionPercent(_value), percent(_percent) {}
Member Function Documentation
apply_override()
virtual bool Slic3r::ConfigOption::apply_override (const ConfigOption * rhs) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      if (*this == *rhs)
        return false;
      *this = *rhs;
      return true;
    }
Referenced by Slic3r::print_config_diffs().
clone()
ConfigOption * Slic3r::ConfigOptionFloatOrPercent::clone () const inline override virtual
Reimplemented from Slic3r::ConfigOptionFloat.
{ return new ConfigOptionFloatOrPercent(*this); }
References ConfigOptionFloatOrPercent().
deserialize()
bool Slic3r::ConfigOptionFloatOrPercent::deserialize (const std::string & str, bool append = false) inline override virtual
Reimplemented from Slic3r::ConfigOptionFloat.
    {
        UNUSED(append);
        this->percent = str.find_first_of("%") != std::string::npos;
        std::istringstream iss(str);
        iss >> this->value;
        return !iss.fail();
    }
References Slic3r::append(), UNUSED, and Slic3r::ConfigOptionSingle< double >::value.
get_abs_value()
double Slic3r::ConfigOptionFloatOrPercent::get_abs_value (double ratio_over) const inline
        { return this->percent ? (ratio_over * this->value / 100) : this->value; }
References Slic3r::ConfigOptionSingle< double >::value.
Referenced by Slic3r::Flow::extrusion_width(), and Slic3r::PresetHints::maximum_volumetric_flow_description().
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
double Slic3r::ConfigOptionFloat::getFloat () const inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{ return this->value; }
References Slic3r::ConfigOptionSingle< double >::value.
Referenced by Slic3r::get_slice_params().
getInt()
virtual int Slic3r::ConfigOption::getInt () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::getInt on a non-int ConfigOption"); }
Referenced by Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
hash()
size_t Slic3r::ConfigOptionFloatOrPercent::hash () const throw () inline override virtual
Implements Slic3r::ConfigOption.
        { size_t seed = std::hash<double>{}(this->value); return this->percent ? seed ^ 0x9e3779b9 : seed; }
References Slic3r::ConfigOptionSingle< double >::value.
is_nil()
virtual bool Slic3r::ConfigOption::is_nil () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVectorBase, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::GCode::append_full_config(), Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_full_label(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::print_config_diffs(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::validate(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nullable()
virtual bool Slic3r::ConfigOption::nullable () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::ConfigBase::null_nullables(), Slic3r::ConfigOption::overriden_by(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::validate().
operator double()
Slic3r::ConfigOptionSingle< double >::operator double () const inline inherited
{ return this->value; }
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
bool Slic3r::ConfigOptionSingle< double >::operator!= (const double & rhs) const throw () inline inherited
{ return this->value != rhs; }
operator<() [1/4]
bool Slic3r::ConfigOptionFloat::operator< (const ConfigOptionFloat & rhs) const throw () inline inherited
{ return this->value <  rhs.value; }
operator<() [2/4]
bool Slic3r::ConfigOptionFloatOrPercent::operator< (const ConfigOptionFloatOrPercent & rhs) const throw () inline
        { return this->value < rhs.value || (this->value == rhs.value && int(this->percent) < int(rhs.percent)); }
operator<() [3/4]
bool Slic3r::ConfigOptionPercent::operator< (const ConfigOptionPercent & rhs) const throw () inline inherited
{ return this->value <  rhs.value; }
operator<() [4/4]
bool Slic3r::ConfigOptionSingle< double >::operator< (const double & rhs) const throw () inline inherited
{ return this->value < rhs; }
operator=()
ConfigOptionFloatOrPercent & Slic3r::ConfigOptionFloatOrPercent::operator= (const ConfigOption * opt) inline
{ this->set(opt); return *this; }
References set().
operator==() [1/5]
bool Slic3r::ConfigOptionFloatOrPercent::operator== (const ConfigOption & rhs) const inline override virtual
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionFloatOrPercent: Comparing incompatible types");
        assert(dynamic_cast<const ConfigOptionFloatOrPercent*>(&rhs));
        return *this == *static_cast<const ConfigOptionFloatOrPercent*>(&rhs);
    }
References Slic3r::ConfigOption::type().
operator==() [2/5]
bool Slic3r::ConfigOptionFloat::operator== (const ConfigOptionFloat & rhs) const throw () inline inherited
{ return this->value == rhs.value; }
operator==() [3/5]
bool Slic3r::ConfigOptionFloatOrPercent::operator== (const ConfigOptionFloatOrPercent & rhs) const throw () inline
        { return this->value == rhs.value && this->percent == rhs.percent; }
operator==() [4/5]
bool Slic3r::ConfigOptionPercent::operator== (const ConfigOptionPercent & rhs) const throw () inline inherited
{ return this->value == rhs.value; }
operator==() [5/5]
bool Slic3r::ConfigOptionSingle< double >::operator== (const double & rhs) const throw () inline inherited
{ return this->value == rhs; }
overriden_by()
virtual bool Slic3r::ConfigOption::overriden_by (const ConfigOption * rhs) const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      assert(! this->nullable() && ! rhs->nullable());
      return *this != *rhs;
    }
References Slic3r::ConfigOption::nullable().
Referenced by Slic3r::print_config_diffs().
serialize() [1/2]
std::string Slic3r::ConfigOptionFloatOrPercent::serialize () const inline override virtual
Reimplemented from Slic3r::ConfigOptionFloat.
    {
        std::ostringstream ss;
        ss << this->value;
        std::string s(ss.str());
        if (this->percent) s += "%";
        return s;
    }
References Slic3r::ConfigOptionSingle< double >::value.
serialize() [2/2]
template<class Archive > void Slic3r::ConfigOptionFloatOrPercent::serialize (Archive & ar) inline private
{ ar(cereal::base_class<ConfigOptionPercent>(this), percent); }
References percent.
set()
void Slic3r::ConfigOptionFloatOrPercent::set (const ConfigOption * rhs) inline override virtual
Implements Slic3r::ConfigOption.
{
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionFloatOrPercent: Assigning an incompatible type");
        assert(dynamic_cast<const ConfigOptionFloatOrPercent*>(rhs));
        *this = *static_cast<const ConfigOptionFloatOrPercent*>(rhs);
    }
References Slic3r::ConfigOption::type().
Referenced by operator=().
setInt()
virtual void Slic3r::ConfigOption::setInt (int) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::setInt on a non-int ConfigOption"); }
static_type()
static ConfigOptionType Slic3r::ConfigOptionFloatOrPercent::static_type () inline static
{ return coFloatOrPercent; }
References Slic3r::coFloatOrPercent.
Referenced by type().
type()
ConfigOptionType Slic3r::ConfigOptionFloatOrPercent::type () const inline override virtual
Reimplemented from Slic3r::ConfigOptionFloat.
{ return static_type(); }
References static_type().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
percent
bool Slic3r::ConfigOptionFloatOrPercent::percent
Referenced by Slic3r::GUI::TextCtrl::BUILD(), Slic3r::Flow::extrusion_width(), Slic3r::GUI::get_string_value(), Slic3r::handle_legacy_project_loaded(), Slic3r::PresetHints::maximum_volumetric_flow_description(), Slic3r::client::MyContext::scalar_variable_to_expr(), serialize(), Slic3r::GUI::Choice::set_selection(), and Slic3r::AvoidCrossingPerimeters::travel_to().
value
double Slic3r::ConfigOptionSingle< double >::value inherited
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp