Prusa Slicer: Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs > Class Template Reference
Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs > Class Template Reference
#include <src/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = _ConjLhs , ConjRhs = _ConjRhs , Vectorizable = packet_traits<LhsScalar>::Vectorizable && packet_traits<RhsScalar>::Vectorizable , LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1 ,
RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1 , ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1 , NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS , nr = 4 ,
default_mr = (EIGEN_PLAIN_ENUM_MIN(16,NumberOfRegisters)/2/nr)*LhsPacketSize , mr = default_mr , LhsProgress = LhsPacketSize , RhsProgress = 1
}
typedef _LhsScalar LhsScalar
typedef _RhsScalar RhsScalar
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
typedef packet_traits< LhsScalar >::type _LhsPacket
typedef packet_traits< RhsScalar >::type _RhsPacket
typedef packet_traits< ResScalar >::type _ResPacket
typedef conditional< Vectorizable, _LhsPacket, LhsScalar >::type LhsPacket
typedef conditional< Vectorizable, _RhsPacket, RhsScalar >::type RhsPacket
typedef conditional< Vectorizable, _ResPacket, ResScalar >::type ResPacket
typedef ResPacket AccPacket
Public Member Functions
EIGEN_STRONG_INLINE void initAcc (AccPacket &p)
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsPacket &b0, RhsPacket &b1, RhsPacket &b2, RhsPacket &b3)
template<typename RhsPacketType >
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, RhsPacketType &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, RhsPacket &dest) const
template<typename LhsPacketType >
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacketType &dest) const
template<typename LhsPacketType >
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacketType &dest) const
template<typename LhsPacketType , typename RhsPacketType , typename AccPacketType >
EIGEN_STRONG_INLINE void madd (const LhsPacketType &a, const RhsPacketType &b, AccPacketType &c, AccPacketType &tmp) const
EIGEN_STRONG_INLINE void acc (const AccPacket &c, const ResPacket &alpha, ResPacket &r) const
template<typename ResPacketHalf >
EIGEN_STRONG_INLINE void acc (const ResPacketHalf &c, const ResPacketHalf &alpha, ResPacketHalf &r) const
Detailed Description
template<typename _LhsScalar, typename _RhsScalar, bool _ConjLhs, bool _ConjRhs>
class Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >
Member Typedef Documentation
_LhsPacket
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<LhsScalar>::type Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::_LhsPacket
_ResPacket
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<ResScalar>::type Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::_ResPacket
_RhsPacket
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<RhsScalar>::type Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::_RhsPacket
AccPacket
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef ResPacket Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::AccPacket
LhsPacket
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,_LhsPacket,LhsScalar>::type Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::LhsPacket
LhsScalar
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef _LhsScalar Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::LhsScalar
ResPacket
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,_ResPacket,ResScalar>::type Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::ResPacket
ResScalar
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef ScalarBinaryOpTraits<LhsScalar,RhsScalar>::ReturnType Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::ResScalar
RhsPacket
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,_RhsPacket,RhsScalar>::type Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::RhsPacket
RhsScalar
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> typedef _RhsScalar Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::RhsScalar
Member Enumeration Documentation
anonymous enum
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
LhsPacketSize
RhsPacketSize
ResPacketSize
NumberOfRegisters
nr
default_mr
mr
LhsProgress
RhsProgress
       {
    ConjLhs = _ConjLhs,
    ConjRhs = _ConjRhs,
    Vectorizable = packet_traits<LhsScalar>::Vectorizable && packet_traits<RhsScalar>::Vectorizable,
    LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1,
    RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1,
    ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1,
    NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS,
    // register block size along the N direction must be 1 or 4
    nr = 4,
    // register block size along the M direction (currently, this one cannot be modified)
    default_mr = (EIGEN_PLAIN_ENUM_MIN(16,NumberOfRegisters)/2/nr)*LhsPacketSize,
#if defined(EIGEN_HAS_SINGLE_INSTRUCTION_MADD) && !defined(EIGEN_VECTORIZE_ALTIVEC) && !defined(EIGEN_VECTORIZE_VSX)
    // we assume 16 registers
    // See bug 992, if the scalar type is not vectorizable but that EIGEN_HAS_SINGLE_INSTRUCTION_MADD is defined,
    // then using 3*LhsPacketSize triggers non-implemented paths in syrk.
    mr = Vectorizable ? 3*LhsPacketSize : default_mr,
#else
    mr = default_mr,
#endif
    LhsProgress = LhsPacketSize,
    RhsProgress = 1
  };
Member Function Documentation
acc() [1/2]
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::acc (const AccPacket & c, const ResPacket & alpha, ResPacket & r) const inline
  {
    r = pmadd(c,alpha,r);
  }
References Eigen::internal::pmadd().
Referenced by Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()().
acc() [2/2]
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> template<typename ResPacketHalf > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::acc (const ResPacketHalf & c, const ResPacketHalf & alpha, ResPacketHalf & r) const inline
  {
    r = pmadd(c,alpha,r);
  }
References Eigen::internal::pmadd().
broadcastRhs()
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, RhsPacket & b0, RhsPacket & b1, RhsPacket & b2, RhsPacket & b3) inline
  {
    pbroadcast4(b, b0, b1, b2, b3);
  }
References Eigen::internal::pbroadcast4().
initAcc()
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::initAcc (AccPacket & p) inline
  {
    p = pset1<ResPacket>(ResScalar(0));
  }
Referenced by Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()().
loadLhs()
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> template<typename LhsPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadLhs (const LhsScalar * a, LhsPacketType & dest) const inline
  {
    dest = pload<LhsPacketType>(a);
  }
loadLhsUnaligned()
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> template<typename LhsPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadLhsUnaligned (const LhsScalar * a, LhsPacketType & dest) const inline
  {
    dest = ploadu<LhsPacketType>(a);
  }
Referenced by Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()().
loadRhs()
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> template<typename RhsPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadRhs (const RhsScalar * b, RhsPacketType & dest) const inline
  {
    dest = pset1<RhsPacketType>(*b);
  }
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhsQuad(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhsQuad(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::loadRhsQuad(), and Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()().
loadRhsQuad()
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadRhsQuad (const RhsScalar * b, RhsPacket & dest) const inline
  {
    dest = ploadquad<RhsPacket>(b);
  }
Referenced by Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()().
madd()
template<typename _LhsScalar , typename _RhsScalar , bool _ConjLhs, bool _ConjRhs> template<typename LhsPacketType , typename RhsPacketType , typename AccPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::madd (const LhsPacketType & a, const RhsPacketType & b, AccPacketType & c, AccPacketType & tmp) const inline
  {
    conj_helper<LhsPacketType,RhsPacketType,ConjLhs,ConjRhs> cj;
    // It would be a lot cleaner to call pmadd all the time. Unfortunately if we
    // let gcc allocate the register in which to store the result of the pmul
    // (in the case where there is no FMA) gcc fails to figure out how to avoid
    // spilling register.
#ifdef EIGEN_HAS_SINGLE_INSTRUCTION_MADD
    EIGEN_UNUSED_VARIABLE(tmp);
    c = cj.pmadd(a,b,c);
#else
    tmp = b; tmp = cj.pmul(a,tmp); c = padd(c,tmp);
#endif
  }
References EIGEN_UNUSED_VARIABLE, Eigen::internal::padd(), Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmadd(), and Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmul().
Referenced by Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h