Prusa Slicer: Slic3r::csg::detail_cgal Namespace Reference
Slic3r::csg::detail_cgal Namespace Reference
Functions
void perform_csg (CSGType op, CGALMeshPtr &dst, CGALMeshPtr &src)
template<class Ex , class It >
std::vector< CGALMeshPtr > get_cgalptrs (Ex policy, const Range< It > &csgrange)
Function Documentation
get_cgalptrs()
template<class Ex , class It > std::vector< CGALMeshPtr > Slic3r::csg::detail_cgal::get_cgalptrs (Ex policy, const Range< It > & csgrange)
{
    std::vector<CGALMeshPtr> ret(csgrange.size());
    execution::for_each(policy, size_t(0), csgrange.size(),
                        [&csgrange, &ret](size_t i) {
        auto it = csgrange.begin();
        std::advance(it, i);
        auto &csgpart = *it;
        ret[i]        = get_cgalmesh(csgpart);
    });
    return ret;
}
References Slic3r::execution::for_each(), and Slic3r::Range< It >::size().
perform_csg()
void Slic3r::csg::detail_cgal::perform_csg (CSGType op, CGALMeshPtr & dst, CGALMeshPtr & src) inline
{
    if (!dst && op == CSGType::Union && src) {
        dst = std::move(src);
        return;
    }
    if (!dst || !src)
        return;
    switch (op) {
    case CSGType::Union:
        MeshBoolean::cgal::plus(*dst, *src);
        break;
    case CSGType::Difference:
        MeshBoolean::cgal::minus(*dst, *src);
        break;
    case CSGType::Intersection:
        MeshBoolean::cgal::intersect(*dst, *src);
        break;
    }
}
References Slic3r::csg::Difference, Slic3r::MeshBoolean::cgal::intersect(), Slic3r::csg::Intersection, Slic3r::MeshBoolean::cgal::minus(), Slic3r::MeshBoolean::cgal::plus(), and Slic3r::csg::Union.