Prusa Slicer: src/avrdude/wiring.h File Reference
wiring.h File Reference
Functions
void wiring_initpgm (PROGRAMMER *pgm)
Variables
const char wiring_desc []
Function Documentation
wiring_initpgm()
void wiring_initpgm (PROGRAMMER * pgm)
{
  /* The Wiring bootloader uses a near-complete STK500v2 protocol. */
  stk500v2_initpgm(pgm);
  strcpy(pgm->type, "Wiring");
  pgm->open           = wiring_open;
  pgm->close          = wiring_close;
  pgm->setup          = wiring_setup;
  pgm->teardown       = wiring_teardown;
  pgm->parseextparams = wiring_parseextparms;
}
References programmer_t::close, programmer_t::open, programmer_t::parseextparams, pgm, programmer_t::setup, stk500v2_initpgm(), programmer_t::teardown, programmer_t::type, wiring_close(), wiring_open(), wiring_parseextparms(), wiring_setup(), and wiring_teardown().
Variable Documentation
wiring_desc
const char wiring_desc[] extern