Prusa Slicer: Slic3r::GUI::Option Struct Reference
Slic3r::GUI::Option Struct Reference
std::function<wxWindow*(wxWindow*)>;
#include <src/slic3r/GUI/OptionsGroup.hpp>
Public Member Functions
bool operator== (const Option &rhs) const
Option (const ConfigOptionDef &_opt, t_config_option_key id)
Public Attributes
ConfigOptionDef opt { ConfigOptionDef() }
t_config_option_key opt_id
widget_t side_widget {nullptr}
{""};
bool readonly {false}
Detailed Description
std::function<wxWindow*(wxWindow*)>;
Wraps a ConfigOptionDef and adds function object for creating a side_widget.
Constructor & Destructor Documentation
Option()
Slic3r::GUI::Option::Option (const ConfigOptionDef & _opt, t_config_option_key id)
                                                                  : opt(_opt), opt_id(id)
{
    if (!opt.tooltip.empty()) {
        wxString tooltip;
        if (opt.opt_key.rfind("branching", 0) == 0)
            tooltip = _L("Unavailable for this method.") + "\n";
        tooltip += _(opt.tooltip);
        edit_tooltip(tooltip);
        opt.tooltip = into_u8(tooltip);
    }
}
References _, _L, edit_tooltip(), Slic3r::GUI::into_u8(), opt, Slic3r::ConfigOptionDef::opt_key, and Slic3r::ConfigOptionDef::tooltip.
Member Function Documentation
operator==()
bool Slic3r::GUI::Option::operator== (const Option & rhs) const inline
{
    return  (rhs.opt_id == this->opt_id);
  }
References opt_id.
Member Data Documentation
opt
ConfigOptionDef Slic3r::GUI::Option::opt { ConfigOptionDef() }
Referenced by Option(), Slic3r::GUI::OptionsGroup::build_field(), and Slic3r::GUI::TabFilament::create_line_with_near_label_widget().
opt_id
t_config_option_key Slic3r::GUI::Option::opt_id
Referenced by Slic3r::GUI::OptionsGroup::build_field(), and operator==().
readonly
bool Slic3r::GUI::Option::readonly {false}
side_widget
widget_t Slic3r::GUI::Option::side_widget {nullptr}
{""};
The documentation for this struct was generated from the following files:
src/slic3r/GUI/OptionsGroup.hpp
src/slic3r/GUI/OptionsGroup.cpp