Prusa Slicer: Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs > Class Template Reference
Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs > Class Template Reference
#include <src/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = false , ConjRhs = _ConjRhs , Vectorizable , LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1 ,
RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1 , ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1 , NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS , nr = 4 ,
mr = (EIGEN_PLAIN_ENUM_MIN(16,NumberOfRegisters)/2/nr)*ResPacketSize , LhsProgress = ResPacketSize , RhsProgress = 1
}
typedef std::complex< RealScalar > Scalar
typedef RealScalar LhsScalar
typedef Scalar RhsScalar
typedef Scalar ResScalar
typedef packet_traits< LhsScalar >::type _LhsPacket
typedef packet_traits< RhsScalar >::type _RhsPacket
typedef packet_traits< ResScalar >::type _ResPacket
typedef conditional< Vectorizable, _LhsPacket, LhsScalar >::type LhsPacket
typedef conditional< Vectorizable, _RhsPacket, RhsScalar >::type RhsPacket
typedef conditional< Vectorizable, _ResPacket, ResScalar >::type ResPacket
typedef ResPacket AccPacket
Public Member Functions
EIGEN_STRONG_INLINE void initAcc (AccPacket &p)
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, RhsPacket &dest) const
void broadcastRhs (const RhsScalar *b, RhsPacket &b0, RhsPacket &b1, RhsPacket &b2, RhsPacket &b3)
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, RhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, AccPacket &c, RhsPacket &tmp) const
EIGEN_STRONG_INLINE void madd_impl (const LhsPacket &a, const RhsPacket &b, AccPacket &c, RhsPacket &tmp, const true_type &) const
EIGEN_STRONG_INLINE void madd_impl (const LhsScalar &a, const RhsScalar &b, ResScalar &c, RhsScalar &, const false_type &) const
EIGEN_STRONG_INLINE void acc (const AccPacket &c, const ResPacket &alpha, ResPacket &r) const
Protected Attributes
conj_helper< ResPacket, ResPacket, false, ConjRhs > cj
Detailed Description
template<typename RealScalar, bool _ConjRhs>
class Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >
Member Typedef Documentation
_LhsPacket
template<typename RealScalar , bool _ConjRhs> typedef packet_traits<LhsScalar>::type Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::_LhsPacket
_ResPacket
template<typename RealScalar , bool _ConjRhs> typedef packet_traits<ResScalar>::type Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::_ResPacket
_RhsPacket
template<typename RealScalar , bool _ConjRhs> typedef packet_traits<RhsScalar>::type Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::_RhsPacket
AccPacket
template<typename RealScalar , bool _ConjRhs> typedef ResPacket Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::AccPacket
LhsPacket
template<typename RealScalar , bool _ConjRhs> typedef conditional<Vectorizable,_LhsPacket,LhsScalar>::type Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::LhsPacket
LhsScalar
template<typename RealScalar , bool _ConjRhs> typedef RealScalar Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::LhsScalar
ResPacket
template<typename RealScalar , bool _ConjRhs> typedef conditional<Vectorizable,_ResPacket,ResScalar>::type Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::ResPacket
ResScalar
template<typename RealScalar , bool _ConjRhs> typedef Scalar Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::ResScalar
RhsPacket
template<typename RealScalar , bool _ConjRhs> typedef conditional<Vectorizable,_RhsPacket,RhsScalar>::type Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::RhsPacket
RhsScalar
template<typename RealScalar , bool _ConjRhs> typedef Scalar Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::RhsScalar
Scalar
template<typename RealScalar , bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::Scalar
Member Enumeration Documentation
anonymous enum
template<typename RealScalar , bool _ConjRhs> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
LhsPacketSize
RhsPacketSize
ResPacketSize
NumberOfRegisters
nr
mr
LhsProgress
RhsProgress
       {
    ConjLhs = false,
    ConjRhs = _ConjRhs,
    Vectorizable = packet_traits<RealScalar>::Vectorizable
                && packet_traits<Scalar>::Vectorizable,
    LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1,
    RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1,
    ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1,
    NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS,
    // FIXME: should depend on NumberOfRegisters
    nr = 4,
    mr = (EIGEN_PLAIN_ENUM_MIN(16,NumberOfRegisters)/2/nr)*ResPacketSize,
    LhsProgress = ResPacketSize,
    RhsProgress = 1
  };
Member Function Documentation
acc()
template<typename RealScalar , bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::acc (const AccPacket & c, const ResPacket & alpha, ResPacket & r) const inline
  {
    r = cj.pmadd(alpha,c,r);
  }
broadcastRhs()
template<typename RealScalar , bool _ConjRhs> void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::broadcastRhs (const RhsScalar * b, RhsPacket & b0, RhsPacket & b1, RhsPacket & b2, RhsPacket & b3) inline
  {
    pbroadcast4(b, b0, b1, b2, b3);
  }
References Eigen::internal::pbroadcast4().
initAcc()
template<typename RealScalar , bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::initAcc (AccPacket & p) inline
  {
    p = pset1<ResPacket>(ResScalar(0));
  }
loadLhs()
template<typename RealScalar , bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
  {
    dest = ploaddup<LhsPacket>(a);
  }
loadLhsUnaligned()
template<typename RealScalar , bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::loadLhsUnaligned (const LhsScalar * a, LhsPacket & dest) const inline
  {
    dest = ploaddup<LhsPacket>(a);
  }
loadRhs()
template<typename RealScalar , bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::loadRhs (const RhsScalar * b, RhsPacket & dest) const inline
  {
    dest = pset1<RhsPacket>(*b);
  }
loadRhsQuad()
template<typename RealScalar , bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::loadRhsQuad (const RhsScalar * b, RhsPacket & dest) const inline
  {
    eigen_internal_assert(unpacket_traits<RhsPacket>::size<=4);
    loadRhs(b,dest);
  }
References eigen_internal_assert, and Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadRhs().
madd()
template<typename RealScalar , bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::madd (const LhsPacket & a, const RhsPacket & b, AccPacket & c, RhsPacket & tmp) const inline
  {
    madd_impl(a, b, c, tmp, typename conditional<Vectorizable,true_type,false_type>::type());
  }
madd_impl() [1/2]
template<typename RealScalar , bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::madd_impl (const LhsPacket & a, const RhsPacket & b, AccPacket & c, RhsPacket & tmp, const true_type &) const inline
  {
#ifdef EIGEN_HAS_SINGLE_INSTRUCTION_MADD
    EIGEN_UNUSED_VARIABLE(tmp);
    c.v = pmadd(a,b.v,c.v);
#else
    tmp = b; tmp.v = pmul(a,tmp.v); c = padd(c,tmp);
#endif
  }
References EIGEN_UNUSED_VARIABLE, Eigen::internal::padd(), Eigen::internal::pmadd(), and Eigen::internal::pmul().
madd_impl() [2/2]
template<typename RealScalar , bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::madd_impl (const LhsScalar & a, const RhsScalar & b, ResScalar & c, RhsScalar & , const false_type &) const inline
  {
    c += a * b;
  }
Member Data Documentation
cj
template<typename RealScalar , bool _ConjRhs> conj_helper<ResPacket,ResPacket,false,ConjRhs> Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::cj protected
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h