Prusa Slicer: ImFontGlyphRangesBuilder Struct Reference
ImFontGlyphRangesBuilder Struct Reference
#include <src/imgui/imgui.h>
Public Member Functions
ImFontGlyphRangesBuilder ()
void Clear ()
bool GetBit (size_t n) const
void SetBit (size_t n)
void AddChar (ImWchar c)
IMGUI_API void AddText (const char *text, const char *text_end=NULL)
IMGUI_API void AddRanges (const ImWchar *ranges)
IMGUI_API void BuildRanges (ImVector< ImWchar > *out_ranges)
Public Attributes
ImVector< ImU32 > UsedChars
Detailed Description
Constructor & Destructor Documentation
ImFontGlyphRangesBuilder()
ImFontGlyphRangesBuilder::ImFontGlyphRangesBuilder () inline
{ Clear(); }
Member Function Documentation
AddChar()
void ImFontGlyphRangesBuilder::AddChar (ImWchar c) inline
{ SetBit(c); }                      // Add character
Referenced by AddRanges(), AddText(), and Slic3r::GUI::ImGuiWrapper::init_font().
AddRanges()
void ImFontGlyphRangesBuilder::AddRanges (const ImWchar * ranges)
{
    for (; ranges[0]; ranges += 2)
        for (ImWchar c = ranges[0]; c <= ranges[1]; c++)
            AddChar(c);
}
References AddChar().
Referenced by Slic3r::GUI::Emboss::StyleManager::create_imgui_font(), and Slic3r::GUI::ImGuiWrapper::init_font().
AddText()
void ImFontGlyphRangesBuilder::AddText (const char * text, const char * text_end = NULL)
{
    while (text_end ? (text < text_end) : *text)
    {
        unsigned int c = 0;
        int c_len = ImTextCharFromUtf8(&c, text, text_end);
        text += c_len;
        if (c_len == 0)
            break;
        AddChar((ImWchar)c);
    }
}
References AddChar(), and ImTextCharFromUtf8().
Referenced by Slic3r::GUI::Emboss::StyleManager::create_imgui_font().
BuildRanges()
void ImFontGlyphRangesBuilder::BuildRanges (ImVector< ImWchar > * out_ranges)
{
    const int max_codepoint = IM_UNICODE_CODEPOINT_MAX;
    for (int n = 0; n <= max_codepoint; n++)
        if (GetBit(n))
        {
            out_ranges->push_back((ImWchar)n);
            while (n < max_codepoint && GetBit(n + 1))
                n++;
            out_ranges->push_back((ImWchar)n);
        }
    out_ranges->push_back(0);
}
References GetBit(), IM_UNICODE_CODEPOINT_MAX, and ImVector< T >::push_back().
Referenced by Slic3r::GUI::Emboss::StyleManager::create_imgui_font(), and Slic3r::GUI::ImGuiWrapper::init_font().
Clear()
void ImFontGlyphRangesBuilder::Clear () inline
{ int size_in_bytes = (IM_UNICODE_CODEPOINT_MAX + 1) / 8; UsedChars.resize(size_in_bytes / (int)sizeof(ImU32)); memset(UsedChars.Data, 0, (size_t)size_in_bytes); }
References ImVector< T >::Data, IM_UNICODE_CODEPOINT_MAX, and ImVector< T >::resize().
GetBit()
bool ImFontGlyphRangesBuilder::GetBit (size_t n) const inline
{ int off = (int)(n >> 5); ImU32 mask = 1u << (n & 31); return (UsedChars[off] & mask) != 0; }  // Get bit n in the array
Referenced by BuildRanges().
SetBit()
void ImFontGlyphRangesBuilder::SetBit (size_t n) inline
{ int off = (int)(n >> 5); ImU32 mask = 1u << (n & 31); UsedChars[off] |= mask; }               // Set bit n in the array
Member Data Documentation
UsedChars
ImVector<ImU32> ImFontGlyphRangesBuilder::UsedChars
The documentation for this struct was generated from the following files:
src/imgui/imgui.h
src/imgui/imgui_draw.cpp