Prusa Slicer: Slic3r::GUI::GLCanvas3D::LayersEditing Class Reference
Slic3r::GUI::GLCanvas3D::LayersEditing Class Reference
Classes
struct LayersTexture
struct Profile
Public Types
enum EState : unsigned char {
Unknown , Editing , Completed , Paused ,
Num_States
}
Public Member Functions
LayersEditing ()=default
~LayersEditing ()
void init ()
void set_config (const DynamicPrintConfig *config)
void select_object (const Model &model, int object_id)
bool is_allowed () const
bool is_enabled () const
void set_enabled (bool enabled)
void render_overlay (const GLCanvas3D &canvas)
void render_volumes (const GLCanvas3D &canvas, const GLVolumeCollection &volumes)
void adjust_layer_height_profile ()
void accept_changes (GLCanvas3D &canvas)
void reset_layer_height_profile (GLCanvas3D &canvas)
void adaptive_layer_height_profile (GLCanvas3D &canvas, float quality_factor)
void smooth_layer_height_profile (GLCanvas3D &canvas, const HeightProfileSmoothingParams &smoothing_params)
float object_max_z () const
std::string get_tooltip (const GLCanvas3D &canvas) const
std::pair< SlicingParameters, const std::vector< double > > get_layers_height_data ()
Static Public Member Functions
static float get_cursor_z_relative (const GLCanvas3D &canvas)
static bool bar_rect_contains (const GLCanvas3D &canvas, float x, float y)
static Rect get_bar_rect_screen (const GLCanvas3D &canvas)
static float get_overlay_window_width ()
Public Attributes
EState state { Unknown }
float band_width { 2.0f }
float strength { 0.005f }
int last_object_id { -1 }
float last_z { 0.0f }
LayerHeightEditActionType last_action { LAYER_HEIGHT_EDIT_ACTION_INCREASE }
Profile m_profile
Static Public Attributes
static const float THICKNESS_BAR_WIDTH = 70.0f
Private Member Functions
bool is_initialized () const
void generate_layer_height_texture ()
void render_active_object_annotations (const GLCanvas3D &canvas)
void render_profile (const GLCanvas3D &canvas)
void update_slicing_parameters ()
Static Private Member Functions
static float thickness_bar_width (const GLCanvas3D &canvas)
Private Attributes
bool m_enabled { false }
unsigned int m_z_texture_id { 0 }
const DynamicPrintConfig * m_config { nullptr }
const ModelObject * m_model_object { nullptr }
float m_object_max_z { 0.0f }
SlicingParameters * m_slicing_parameters { nullptr }
std::vector< double > m_layer_height_profile
bool m_layer_height_profile_modified { false }
float m_adaptive_quality { 0.5f }
HeightProfileSmoothingParams m_smooth_params
LayersTexture m_layers_texture
Static Private Attributes
static float s_overlay_window_width
Detailed Description
Class Documentation
Slic3r::GUI::GLCanvas3D::LayersEditing::LayersTexture
struct Slic3r::GUI::GLCanvas3D::LayersEditing::LayersTexture
Class Members
size_t cells { 0 }
vector< char > data
size_t height { 0 }
size_t levels { 0 }
bool valid { false }
size_t width { 0 }
Slic3r::GUI::GLCanvas3D::LayersEditing::Profile
struct Slic3r::GUI::GLCanvas3D::LayersEditing::Profile
Class Members
GLModel background
GLModel baseline
OldCanvasWidth old_canvas_width
vector< double > old_layer_height_profile
GLModel profile
Member Enumeration Documentation
EState
enum Slic3r::GUI::GLCanvas3D::LayersEditing::EState : unsigned char
Enumerator
Unknown
Editing
Completed
Paused
Num_States
        {
            Unknown,
            Editing,
            Completed,
            Paused,
            Num_States
        };
Constructor & Destructor Documentation
LayersEditing()
Slic3r::GUI::GLCanvas3D::LayersEditing::LayersEditing () default
~LayersEditing()
Slic3r::GUI::GLCanvas3D::LayersEditing::~LayersEditing ()
{
    if (m_z_texture_id != 0) {
        glsafe(::glDeleteTextures(1, &m_z_texture_id));
        m_z_texture_id = 0;
    }
    delete m_slicing_parameters;
}
References glsafe, m_slicing_parameters, and m_z_texture_id.
Member Function Documentation
accept_changes()
void Slic3r::GUI::GLCanvas3D::LayersEditing::accept_changes (GLCanvas3D & canvas)
{
    if (last_object_id >= 0) {
        if (m_layer_height_profile_modified) {
            wxGetApp().plater()->take_snapshot(_L("Variable layer height - Manual edit"));
            const_cast<ModelObject*>(m_model_object)->layer_height_profile.set(m_layer_height_profile);
            wxGetApp().obj_list()->update_info_items(last_object_id);
            wxGetApp().plater()->schedule_background_process();
        }
    }
    m_layer_height_profile_modified = false;
}
References _L.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse().
adaptive_layer_height_profile()
void Slic3r::GUI::GLCanvas3D::LayersEditing::adaptive_layer_height_profile (GLCanvas3D & canvas, float quality_factor)
{
    this->update_slicing_parameters();
    m_layer_height_profile = layer_height_profile_adaptive(*m_slicing_parameters, *m_model_object, quality_factor);
    const_cast<ModelObject*>(m_model_object)->layer_height_profile.set(m_layer_height_profile);
    m_layers_texture.valid = false;
    canvas.post_event(SimpleEvent(EVT_GLCANVAS_SCHEDULE_BACKGROUND_PROCESS));
    wxGetApp().obj_list()->update_info_items(last_object_id);
}
References Slic3r::layer_height_profile_adaptive(), and Slic3r::GUI::GLCanvas3D::post_event().
Referenced by Slic3r::GUI::GLCanvas3D::adaptive_layer_height_profile().
adjust_layer_height_profile()
void Slic3r::GUI::GLCanvas3D::LayersEditing::adjust_layer_height_profile ()
{
    this->update_slicing_parameters();
    PrintObject::update_layer_height_profile(*m_model_object, *m_slicing_parameters, m_layer_height_profile);
    Slic3r::adjust_layer_height_profile(*m_slicing_parameters, m_layer_height_profile, this->last_z, this->strength, this->band_width, this->last_action);
    m_layer_height_profile_modified = true;
    m_layers_texture.valid = false;
}
References Slic3r::adjust_layer_height_profile(), and Slic3r::PrintObject::update_layer_height_profile().
bar_rect_contains()
bool Slic3r::GUI::GLCanvas3D::LayersEditing::bar_rect_contains (const GLCanvas3D & canvas, float x, float y) static
{
    const Rect& rect = get_bar_rect_screen(canvas);
    return rect.get_left() <= x && x <= rect.get_right() && rect.get_top() <= y && y <= rect.get_bottom();
}
References Slic3r::GUI::Rect::get_bottom(), Slic3r::GUI::Rect::get_left(), Slic3r::GUI::Rect::get_right(), and Slic3r::GUI::Rect::get_top().
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse(), and Slic3r::GUI::GLCanvas3D::on_mouse_wheel().
generate_layer_height_texture()
void Slic3r::GUI::GLCanvas3D::LayersEditing::generate_layer_height_texture () private
{
    this->update_slicing_parameters();
    // Always try to update the layer height profile.
    bool update = ! m_layers_texture.valid;
    if (PrintObject::update_layer_height_profile(*m_model_object, *m_slicing_parameters, m_layer_height_profile)) {
        // Initialized to the default value.
        m_layer_height_profile_modified = false;
        update = true;
    }
    // Update if the layer height profile was changed, or when the texture is not valid.
    if (! update && ! m_layers_texture.data.empty() && m_layers_texture.cells > 0)
        // Texture is valid, don't update.
        return;
    if (m_layers_texture.data.empty()) {
        m_layers_texture.width  = 1024;
        m_layers_texture.height = 1024;
        m_layers_texture.levels = 2;
        m_layers_texture.data.assign(m_layers_texture.width * m_layers_texture.height * 5, 0);
    }
    bool level_of_detail_2nd_level = true;
    m_layers_texture.cells = Slic3r::generate_layer_height_texture(
        *m_slicing_parameters,
        Slic3r::generate_object_layers(*m_slicing_parameters, m_layer_height_profile),
    m_layers_texture.data.data(), m_layers_texture.height, m_layers_texture.width, level_of_detail_2nd_level);
  m_layers_texture.valid = true;
}
References Slic3r::generate_layer_height_texture(), Slic3r::generate_object_layers(), and Slic3r::PrintObject::update_layer_height_profile().
get_bar_rect_screen()
Rect Slic3r::GUI::GLCanvas3D::LayersEditing::get_bar_rect_screen (const GLCanvas3D & canvas) static
{
    const Size& cnv_size = canvas.get_canvas_size();
    float w = (float)cnv_size.get_width();
    float h = (float)cnv_size.get_height();
    return { w - thickness_bar_width(canvas), 0.0f, w, h };
}
References Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), and Slic3r::GUI::Size::get_width().
get_cursor_z_relative()
float Slic3r::GUI::GLCanvas3D::LayersEditing::get_cursor_z_relative (const GLCanvas3D & canvas) static
{
    const Vec2d mouse_pos = canvas.get_local_mouse_position();
    const Rect& rect = get_bar_rect_screen(canvas);
    float x = (float)mouse_pos.x();
    float y = (float)mouse_pos.y();
    float t = rect.get_top();
    float b = rect.get_bottom();
    return (rect.get_left() <= x && x <= rect.get_right() && t <= y && y <= b) ?
        // Inside the bar.
        (b - y - 1.0f) / (b - t - 1.0f) :
        // Outside the bar.
        -1000.0f;
}
References Slic3r::GUI::Rect::get_bottom(), Slic3r::GUI::Rect::get_left(), Slic3r::GUI::GLCanvas3D::get_local_mouse_position(), Slic3r::GUI::Rect::get_right(), and Slic3r::GUI::Rect::get_top().
get_layers_height_data()
std::pair< SlicingParameters, const std::vector< double > > Slic3r::GUI::GLCanvas3D::LayersEditing::get_layers_height_data ()
{
    if (m_slicing_parameters != nullptr)
        return { *m_slicing_parameters, m_layer_height_profile };
    assert(m_model_object != nullptr);
    this->update_slicing_parameters();
    PrintObject::update_layer_height_profile(*m_model_object, *m_slicing_parameters, m_layer_height_profile);
    std::pair<SlicingParameters, const std::vector<double>> ret = { *m_slicing_parameters, m_layer_height_profile };
    delete m_slicing_parameters;
    m_slicing_parameters = nullptr;
    return ret;
}
References Slic3r::PrintObject::update_layer_height_profile().
Referenced by Slic3r::GUI::GLCanvas3D::get_layers_height_data().
get_overlay_window_width()
static float Slic3r::GUI::GLCanvas3D::LayersEditing::get_overlay_window_width () inline static
{ return LayersEditing::s_overlay_window_width; }
References s_overlay_window_width.
Referenced by Slic3r::GUI::GLCanvas3D::get_overlay_window_width().
get_tooltip()
std::string Slic3r::GUI::GLCanvas3D::LayersEditing::get_tooltip (const GLCanvas3D & canvas) const
{
    std::string ret;
    if (m_enabled && m_layer_height_profile.size() >= 4) {
        float z = get_cursor_z_relative(canvas);
        if (z != -1000.0f) {
            z *= m_object_max_z;
            float h = 0.0f;
            for (size_t i = m_layer_height_profile.size() - 2; i >= 2; i -= 2) {
                const float zi = static_cast<float>(m_layer_height_profile[i]);
                const float zi_1 = static_cast<float>(m_layer_height_profile[i - 2]);
                if (zi_1 <= z && z <= zi) {
                    float dz = zi - zi_1;
                    h = (dz != 0.0f) ? static_cast<float>(lerp(m_layer_height_profile[i - 1], m_layer_height_profile[i + 1], (z - zi_1) / dz)) :
                        static_cast<float>(m_layer_height_profile[i + 1]);
                    break;
                }
            }
            if (h > 0.0f)
                ret = std::to_string(h);
        }
    }
    return ret;
}
References Slic3r::lerp().
Referenced by Slic3r::GUI::GLCanvas3D::render().
init()
void Slic3r::GUI::GLCanvas3D::LayersEditing::init ()
{
    glsafe(::glGenTextures(1, (GLuint*)&m_z_texture_id));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_z_texture_id));
    if (!OpenGLManager::get_gl_info().is_core_profile() || !OpenGLManager::get_gl_info().is_mesa()) {
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE));
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE));
    }
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_NEAREST));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAX_LEVEL, 1));
    glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
}
References Slic3r::GUI::OpenGLManager::get_gl_info(), and glsafe.
Referenced by Slic3r::GUI::GLCanvas3D::init().
is_allowed()
bool Slic3r::GUI::GLCanvas3D::LayersEditing::is_allowed () const
{
    return wxGetApp().get_shader("variable_layer_height") != nullptr && m_z_texture_id > 0;
}
Referenced by Slic3r::GUI::GLCanvas3D::is_layers_editing_allowed().
is_enabled()
bool Slic3r::GUI::GLCanvas3D::LayersEditing::is_enabled () const
{
    return m_enabled;
}
Referenced by Slic3r::GUI::GLCanvas3D::is_layers_editing_enabled(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
is_initialized()
bool Slic3r::GUI::GLCanvas3D::LayersEditing::is_initialized () const private
{
    return wxGetApp().get_shader("variable_layer_height") != nullptr;
}
object_max_z()
float Slic3r::GUI::GLCanvas3D::LayersEditing::object_max_z () const inline
{ return m_object_max_z; }
References m_object_max_z.
render_active_object_annotations()
void Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations (const GLCanvas3D & canvas) private
{
    const Size cnv_size = canvas.get_canvas_size();
    const float cnv_width = (float)cnv_size.get_width();
    const float cnv_height = (float)cnv_size.get_height();
    if (cnv_width == 0.0f || cnv_height == 0.0f)
        return;
    const float cnv_inv_width = 1.0f / cnv_width;
    GLShaderProgram* shader = wxGetApp().get_shader("variable_layer_height");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("z_to_texture_row", float(m_layers_texture.cells - 1) / (float(m_layers_texture.width) * m_object_max_z));
    shader->set_uniform("z_texture_row_to_normalized", 1.0f / (float)m_layers_texture.height);
    shader->set_uniform("z_cursor", m_object_max_z * this->get_cursor_z_relative(canvas));
    shader->set_uniform("z_cursor_band_width", band_width);
    shader->set_uniform("object_max_z", m_object_max_z);
    shader->set_uniform("view_model_matrix", Transform3d::Identity());
    shader->set_uniform("projection_matrix", Transform3d::Identity());
    shader->set_uniform("view_normal_matrix", (Matrix3d)Matrix3d::Identity());
    glsafe(::glPixelStorei(GL_UNPACK_ALIGNMENT, 1));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_z_texture_id));
    // Render the color bar
    if (!m_profile.background.is_initialized() || m_profile.old_canvas_width.background != cnv_width) {
        m_profile.old_canvas_width.background = cnv_width;
        m_profile.background.reset();
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P3N3T2 };
        init_data.reserve_vertices(4);
        init_data.reserve_indices(6);
        // vertices
        const float l = 1.0f - 2.0f * THICKNESS_BAR_WIDTH * cnv_inv_width;
        const float r = 1.0f;
        const float t = 1.0f;
        const float b = -1.0f;
        init_data.add_vertex(Vec3f(l, b, 0.0f), Vec3f::UnitZ(), Vec2f(0.0f, 0.0f));
        init_data.add_vertex(Vec3f(r, b, 0.0f), Vec3f::UnitZ(), Vec2f(1.0f, 0.0f));
        init_data.add_vertex(Vec3f(r, t, 0.0f), Vec3f::UnitZ(), Vec2f(1.0f, 1.0f));
        init_data.add_vertex(Vec3f(l, t, 0.0f), Vec3f::UnitZ(), Vec2f(0.0f, 1.0f));
        // indices
        init_data.add_triangle(0, 1, 2);
        init_data.add_triangle(2, 3, 0);
        m_profile.background.init_from(std::move(init_data));
    }
    m_profile.background.render();
    glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
    shader->stop_using();
}
References Slic3r::GUI::GLModel::Geometry::add_triangle(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), glsafe, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::GUI::GLModel::Geometry::P3N3T2, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), and Slic3r::GUI::GLModel::Geometry::Triangles.
render_overlay()
void Slic3r::GUI::GLCanvas3D::LayersEditing::render_overlay (const GLCanvas3D & canvas)
{
    if (!m_enabled)
        return;
    const Size& cnv_size = canvas.get_canvas_size();
    ImGuiWrapper& imgui = *wxGetApp().imgui();
    imgui.set_next_window_pos(static_cast<float>(cnv_size.get_width()) - imgui.get_style_scaling() * THICKNESS_BAR_WIDTH,
        static_cast<float>(cnv_size.get_height()), ImGuiCond_Always, 1.0f, 1.0f);
    imgui.begin(_L("Variable layer height"), ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoCollapse);
    imgui.text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, _L("Left mouse button:"));
    ImGui::SameLine();
    imgui.text(_L("Add detail"));
    imgui.text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, _L("Right mouse button:"));
    ImGui::SameLine();
    imgui.text(_L("Remove detail"));
    imgui.text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, _L("Shift + Left mouse button:"));
    ImGui::SameLine();
    imgui.text(_L("Reset to base"));
    imgui.text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, _L("Shift + Right mouse button:"));
    ImGui::SameLine();
    imgui.text(_L("Smoothing"));
    imgui.text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, _L("Mouse wheel:"));
    ImGui::SameLine();
    imgui.text(_L("Increase/decrease edit area"));
    ImGui::Separator();
    if (imgui.button(_L("Adaptive")))
        wxPostEvent((wxEvtHandler*)canvas.get_wxglcanvas(), Event<float>(EVT_GLCANVAS_ADAPTIVE_LAYER_HEIGHT_PROFILE, m_adaptive_quality));
    ImGui::SameLine();
    float text_align = ImGui::GetCursorPosX();
    ImGui::AlignTextToFramePadding();
    imgui.text(_L("Quality / Speed"));
    if (ImGui::IsItemHovered()) {
        ImGui::BeginTooltip();
        ImGui::TextUnformatted(_L("Higher print quality versus higher print speed.").ToUTF8());
        ImGui::EndTooltip();
    }
    ImGui::SameLine();
    float widget_align = ImGui::GetCursorPosX();
    ImGui::PushItemWidth(imgui.get_style_scaling() * 120.0f);
    m_adaptive_quality = std::clamp(m_adaptive_quality, 0.0f, 1.f);
    imgui.slider_float("", &m_adaptive_quality, 0.0f, 1.f, "%.2f");
    ImGui::Separator();
    if (imgui.button(_L("Smooth")))
        wxPostEvent((wxEvtHandler*)canvas.get_wxglcanvas(), HeightProfileSmoothEvent(EVT_GLCANVAS_SMOOTH_LAYER_HEIGHT_PROFILE, m_smooth_params));
    ImGui::SameLine();
    ImGui::SetCursorPosX(text_align);
    ImGui::AlignTextToFramePadding();
    imgui.text(_L("Radius"));
    ImGui::SameLine();
    ImGui::SetCursorPosX(widget_align);
    ImGui::PushItemWidth(imgui.get_style_scaling() * 120.0f);
    int radius = (int)m_smooth_params.radius;
    if (ImGui::SliderInt("##1", &radius, 1, 10)) {
        radius = std::clamp(radius, 1, 10);
        m_smooth_params.radius = (unsigned int)radius;
    }
    ImGui::SetCursorPosX(text_align);
    ImGui::AlignTextToFramePadding();
    imgui.text(_L("Keep min"));
    ImGui::SameLine();
    if (ImGui::GetCursorPosX() < widget_align)  // because of line lenght after localization
        ImGui::SetCursorPosX(widget_align);
    ImGui::PushItemWidth(imgui.get_style_scaling() * 120.0f);
    imgui.checkbox("##2", m_smooth_params.keep_min);
    ImGui::Separator();
    if (imgui.button(_L("Reset")))
        wxPostEvent((wxEvtHandler*)canvas.get_wxglcanvas(), SimpleEvent(EVT_GLCANVAS_RESET_LAYER_HEIGHT_PROFILE));
    GLCanvas3D::LayersEditing::s_overlay_window_width = ImGui::GetWindowSize().x /*+ (float)m_layers_texture.width/4*/;
    imgui.end();
    render_active_object_annotations(canvas);
    render_profile(canvas);
}
References _L, ImGui::AlignTextToFramePadding(), Slic3r::GUI::ImGuiWrapper::begin(), ImGui::BeginTooltip(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::checkbox(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, Slic3r::GUI::ImGuiWrapper::end(), ImGui::EndTooltip(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::ImGuiWrapper::get_style_scaling(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLCanvas3D::get_wxglcanvas(), ImGui::GetCursorPosX(), ImGui::GetWindowSize(), ImGuiCond_Always, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGui::IsItemHovered(), ImGui::PushItemWidth(), s_overlay_window_width, ImGui::SameLine(), ImGui::Separator(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), ImGui::SetCursorPosX(), Slic3r::GUI::ImGuiWrapper::slider_float(), ImGui::SliderInt(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), ImGui::TextUnformatted(), and ImVec2::x.
render_profile()
void Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile (const GLCanvas3D & canvas) private
{
    //FIXME show some kind of legend.
    if (!m_slicing_parameters)
        return;
    const Size cnv_size = canvas.get_canvas_size();
    const float cnv_width  = (float)cnv_size.get_width();
    const float cnv_height = (float)cnv_size.get_height();
    if (cnv_width == 0.0f || cnv_height == 0.0f)
        return;
    // Make the vertical bar a bit wider so the layer height curve does not touch the edge of the bar region.
    const float scale_x = THICKNESS_BAR_WIDTH / float(1.12 * m_slicing_parameters->max_layer_height);
    const float scale_y = cnv_height / m_object_max_z;
    const float cnv_inv_width  = 1.0f / cnv_width;
    const float cnv_inv_height = 1.0f / cnv_height;
    const float left = 1.0f - 2.0f * THICKNESS_BAR_WIDTH * cnv_inv_width;
    // Baseline
    if (!m_profile.baseline.is_initialized() || m_profile.old_layer_height_profile != m_layer_height_profile || m_profile.old_canvas_width.baseline != cnv_width) {
        m_profile.old_canvas_width.baseline = cnv_width;
        m_profile.baseline.reset();
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::Lines, GLModel::Geometry::EVertexLayout::P2 };
        init_data.color = ColorRGBA::BLACK();
        init_data.reserve_vertices(2);
        init_data.reserve_indices(2);
        // vertices
        const float axis_x = left + 2.0f * float(m_slicing_parameters->layer_height) * scale_x * cnv_inv_width;
        init_data.add_vertex(Vec2f(axis_x, -1.0f));
        init_data.add_vertex(Vec2f(axis_x, 1.0f));
        // indices
        init_data.add_line(0, 1);
        m_profile.baseline.init_from(std::move(init_data));
    }
    if (!m_profile.profile.is_initialized() || m_profile.old_layer_height_profile != m_layer_height_profile || m_profile.old_canvas_width.profile != cnv_width) {
        m_profile.old_canvas_width.profile = cnv_width;
        m_profile.old_layer_height_profile = m_layer_height_profile;
        m_profile.profile.reset();
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::LineStrip, GLModel::Geometry::EVertexLayout::P2 };
        init_data.color = ColorRGBA::BLUE();
        init_data.reserve_vertices(m_layer_height_profile.size() / 2);
        init_data.reserve_indices(m_layer_height_profile.size() / 2);
        // vertices + indices
        for (unsigned int i = 0; i < (unsigned int)m_layer_height_profile.size(); i += 2) {
            init_data.add_vertex(Vec2f(left + 2.0f * float(m_layer_height_profile[i + 1]) * scale_x * cnv_inv_width,
                2.0f * (float(m_layer_height_profile[i]) * scale_y * cnv_inv_height - 0.5)));
            init_data.add_index(i / 2);
        }
        m_profile.profile.init_from(std::move(init_data));
    }
#if ENABLE_GL_CORE_PROFILE
    GLShaderProgram* shader = OpenGLManager::get_gl_info().is_core_profile() ? wxGetApp().get_shader("dashed_thick_lines") : wxGetApp().get_shader("flat");
#else
    GLShaderProgram* shader = wxGetApp().get_shader("flat");
#endif // ENABLE_GL_CORE_PROFILE
    if (shader != nullptr) {
        shader->start_using();
        shader->set_uniform("view_model_matrix", Transform3d::Identity());
        shader->set_uniform("projection_matrix", Transform3d::Identity());
#if ENABLE_GL_CORE_PROFILE
        const std::array<int, 4>& viewport = wxGetApp().plater()->get_camera().get_viewport();
        shader->set_uniform("viewport_size", Vec2d(double(viewport[2]), double(viewport[3])));
        shader->set_uniform("width", 0.25f);
        shader->set_uniform("gap_size", 0.0f);
#endif // ENABLE_GL_CORE_PROFILE
        m_profile.baseline.render();
        m_profile.profile.render();
        shader->stop_using();
    }
}
References Slic3r::GUI::GLModel::Geometry::add_index(), Slic3r::GUI::GLModel::Geometry::add_line(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::ColorRGBA::BLACK(), Slic3r::ColorRGBA::BLUE(), Slic3r::GUI::GLModel::Geometry::color, Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::GUI::OpenGLManager::GLInfo::is_core_profile(), Slic3r::GUI::GLModel::Geometry::Lines, Slic3r::GUI::GLModel::Geometry::LineStrip, Slic3r::GUI::GLModel::Geometry::P2, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_volumes()
void Slic3r::GUI::GLCanvas3D::LayersEditing::render_volumes (const GLCanvas3D & canvas, const GLVolumeCollection & volumes)
{
    assert(this->is_allowed());
    assert(this->last_object_id != -1);
    GLShaderProgram* current_shader = wxGetApp().get_current_shader();
    ScopeGuard guard([current_shader]() { if (current_shader != nullptr) current_shader->start_using(); });
    if (current_shader != nullptr)
        current_shader->stop_using();
    GLShaderProgram* shader = wxGetApp().get_shader("variable_layer_height");
    if (shader == nullptr)
        return;
    shader->start_using();
    generate_layer_height_texture();
    // Uniforms were resolved, go ahead using the layer editing shader.
    shader->set_uniform("z_to_texture_row", float(m_layers_texture.cells - 1) / (float(m_layers_texture.width) * float(m_object_max_z)));
    shader->set_uniform("z_texture_row_to_normalized", 1.0f / float(m_layers_texture.height));
    shader->set_uniform("z_cursor", float(m_object_max_z) * float(this->get_cursor_z_relative(canvas)));
    shader->set_uniform("z_cursor_band_width", float(this->band_width));
    const Camera& camera = wxGetApp().plater()->get_camera();
    shader->set_uniform("projection_matrix", camera.get_projection_matrix());
    // Initialize the layer height texture mapping.
    const GLsizei w = (GLsizei)m_layers_texture.width;
    const GLsizei h = (GLsizei)m_layers_texture.height;
    const GLsizei half_w = w / 2;
    const GLsizei half_h = h / 2;
    glsafe(::glPixelStorei(GL_UNPACK_ALIGNMENT, 1));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_z_texture_id));
    glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, w, h, 0, GL_RGBA, GL_UNSIGNED_BYTE, 0));
    glsafe(::glTexImage2D(GL_TEXTURE_2D, 1, GL_RGBA, half_w, half_h, 0, GL_RGBA, GL_UNSIGNED_BYTE, 0));
    glsafe(::glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, m_layers_texture.data.data()));
    glsafe(::glTexSubImage2D(GL_TEXTURE_2D, 1, 0, 0, half_w, half_h, GL_RGBA, GL_UNSIGNED_BYTE, m_layers_texture.data.data() + m_layers_texture.width * m_layers_texture.height * 4));
    for (GLVolume* glvolume : volumes.volumes) {
        // Render the object using the layer editing shader and texture.
        if (!glvolume->is_active || glvolume->composite_id.object_id != this->last_object_id || glvolume->is_modifier)
            continue;
        shader->set_uniform("volume_world_matrix", glvolume->world_matrix());
        shader->set_uniform("object_max_z", 0.0f);
        const Transform3d& view_matrix = camera.get_view_matrix();
        const Transform3d model_matrix = glvolume->world_matrix();
        shader->set_uniform("view_model_matrix", view_matrix * model_matrix);
        const Matrix3d view_normal_matrix = view_matrix.matrix().block(0, 0, 3, 3) * model_matrix.matrix().block(0, 0, 3, 3).inverse().transpose();
        shader->set_uniform("view_normal_matrix", view_normal_matrix);
        glvolume->render();
    }
    // Revert back to the previous shader.
    glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
}
References Slic3r::generate_layer_height_texture(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), glsafe, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), and Slic3r::GLVolumeCollection::volumes.
reset_layer_height_profile()
void Slic3r::GUI::GLCanvas3D::LayersEditing::reset_layer_height_profile (GLCanvas3D & canvas)
{
    const_cast<ModelObject*>(m_model_object)->layer_height_profile.clear();
    m_layer_height_profile.clear();
    m_layers_texture.valid = false;
    canvas.post_event(SimpleEvent(EVT_GLCANVAS_SCHEDULE_BACKGROUND_PROCESS));
    wxGetApp().obj_list()->update_info_items(last_object_id);
}
References Slic3r::GUI::GLCanvas3D::post_event().
Referenced by Slic3r::GUI::GLCanvas3D::reset_layer_height_profile().
select_object()
void Slic3r::GUI::GLCanvas3D::LayersEditing::select_object (const Model & model, int object_id)
{
    const ModelObject *model_object_new = (object_id >= 0) ? model.objects[object_id] : nullptr;
    // Maximum height of an object changes when the object gets rotated or scaled.
    // Changing maximum height of an object will invalidate the layer heigth editing profile.
    // m_model_object->bounding_box() is cached, therefore it is cheap even if this method is called frequently.
    const float new_max_z = (model_object_new == nullptr) ? 0.0f : static_cast<float>(model_object_new->max_z());
    if (m_model_object != model_object_new || this->last_object_id != object_id || m_object_max_z != new_max_z ||
        (model_object_new != nullptr && m_model_object->id() != model_object_new->id())) {
        m_layer_height_profile.clear();
        m_layer_height_profile_modified = false;
        delete m_slicing_parameters;
        m_slicing_parameters   = nullptr;
        m_layers_texture.valid = false;
        this->last_object_id   = object_id;
        m_model_object         = model_object_new;
        m_object_max_z         = new_max_z;
    }
}
References Slic3r::ObjectBase::id(), Slic3r::ModelObject::max_z(), and Slic3r::Model::objects.
Referenced by Slic3r::GUI::GLCanvas3D::get_layers_height_data(), and Slic3r::GUI::GLCanvas3D::on_mouse().
set_config()
void Slic3r::GUI::GLCanvas3D::LayersEditing::set_config (const DynamicPrintConfig * config)
{
    m_config = config;
    delete m_slicing_parameters;
    m_slicing_parameters = nullptr;
    m_layers_texture.valid = false;
    m_layer_height_profile.clear();
    m_layer_height_profile_modified = false;
}
References Slic3r::DynamicConfig::clear(), and Slic3r::GUI::GLCanvas3D::m_config.
Referenced by Slic3r::GUI::GLCanvas3D::set_config().
set_enabled()
void Slic3r::GUI::GLCanvas3D::LayersEditing::set_enabled (bool enabled)
{
    m_enabled = is_allowed() && enabled;
}
Referenced by Slic3r::GUI::GLCanvas3D::enable_layers_editing().
smooth_layer_height_profile()
void Slic3r::GUI::GLCanvas3D::LayersEditing::smooth_layer_height_profile (GLCanvas3D & canvas, const HeightProfileSmoothingParams & smoothing_params)
{
    this->update_slicing_parameters();
    m_layer_height_profile = smooth_height_profile(m_layer_height_profile, *m_slicing_parameters, smoothing_params);
    const_cast<ModelObject*>(m_model_object)->layer_height_profile.set(m_layer_height_profile);
    m_layers_texture.valid = false;
    canvas.post_event(SimpleEvent(EVT_GLCANVAS_SCHEDULE_BACKGROUND_PROCESS));
    wxGetApp().obj_list()->update_info_items(last_object_id);
}
References Slic3r::GUI::GLCanvas3D::post_event(), and Slic3r::smooth_height_profile().
Referenced by Slic3r::GUI::GLCanvas3D::smooth_layer_height_profile().
thickness_bar_width()
float Slic3r::GUI::GLCanvas3D::LayersEditing::thickness_bar_width (const GLCanvas3D & canvas) static private
{
    return
#if ENABLE_RETINA_GL
        canvas.get_canvas_size().get_scale_factor()
#else
        canvas.get_wxglcanvas()->GetContentScaleFactor()
#endif
         * THICKNESS_BAR_WIDTH;
}
References Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_scale_factor(), and Slic3r::GUI::GLCanvas3D::get_wxglcanvas().
update_slicing_parameters()
void Slic3r::GUI::GLCanvas3D::LayersEditing::update_slicing_parameters () private
{
  if (m_slicing_parameters == nullptr) {
    m_slicing_parameters = new SlicingParameters();
        *m_slicing_parameters = PrintObject::slicing_parameters(*m_config, *m_model_object, m_object_max_z);
    }
}
References Slic3r::GUI::GLCanvas3D::m_config, and Slic3r::PrintObject::slicing_parameters().
Member Data Documentation
band_width
float Slic3r::GUI::GLCanvas3D::LayersEditing::band_width { 2.0f }
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse_wheel().
last_action
LayerHeightEditActionType Slic3r::GUI::GLCanvas3D::LayersEditing::last_action { LAYER_HEIGHT_EDIT_ACTION_INCREASE }
last_object_id
int Slic3r::GUI::GLCanvas3D::LayersEditing::last_object_id { -1 }
last_z
float Slic3r::GUI::GLCanvas3D::LayersEditing::last_z { 0.0f }
m_adaptive_quality
float Slic3r::GUI::GLCanvas3D::LayersEditing::m_adaptive_quality { 0.5f } mutable private
m_config
const DynamicPrintConfig* Slic3r::GUI::GLCanvas3D::LayersEditing::m_config { nullptr } private
m_enabled
bool Slic3r::GUI::GLCanvas3D::LayersEditing::m_enabled { false } private
m_layer_height_profile
std::vector<double> Slic3r::GUI::GLCanvas3D::LayersEditing::m_layer_height_profile private
m_layer_height_profile_modified
bool Slic3r::GUI::GLCanvas3D::LayersEditing::m_layer_height_profile_modified { false } private
m_layers_texture
LayersTexture Slic3r::GUI::GLCanvas3D::LayersEditing::m_layers_texture private
m_model_object
const ModelObject* Slic3r::GUI::GLCanvas3D::LayersEditing::m_model_object { nullptr } private
m_object_max_z
float Slic3r::GUI::GLCanvas3D::LayersEditing::m_object_max_z { 0.0f } private
Referenced by object_max_z().
m_profile
Profile Slic3r::GUI::GLCanvas3D::LayersEditing::m_profile
m_slicing_parameters
SlicingParameters* Slic3r::GUI::GLCanvas3D::LayersEditing::m_slicing_parameters { nullptr } private
Referenced by ~LayersEditing().
m_smooth_params
HeightProfileSmoothingParams Slic3r::GUI::GLCanvas3D::LayersEditing::m_smooth_params mutable private
m_z_texture_id
unsigned int Slic3r::GUI::GLCanvas3D::LayersEditing::m_z_texture_id { 0 } private
Referenced by ~LayersEditing().
s_overlay_window_width
float Slic3r::GUI::GLCanvas3D::LayersEditing::s_overlay_window_width static private
Referenced by get_overlay_window_width(), and render_overlay().
state
EState Slic3r::GUI::GLCanvas3D::LayersEditing::state { Unknown }
Referenced by Slic3r::GUI::GLCanvas3D::adaptive_layer_height_profile(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::on_timer(), Slic3r::GUI::GLCanvas3D::reset_layer_height_profile(), and Slic3r::GUI::GLCanvas3D::smooth_layer_height_profile().
strength
float Slic3r::GUI::GLCanvas3D::LayersEditing::strength { 0.005f }
THICKNESS_BAR_WIDTH
const float Slic3r::GUI::GLCanvas3D::LayersEditing::THICKNESS_BAR_WIDTH = 70.0f static
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLCanvas3D.hpp
src/slic3r/GUI/GLCanvas3D.cpp