Prusa Slicer: Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
#include <src/eigen/Eigen/src/SVD/JacobiSVD.h>
Public Member Functions
void allocate (const JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > &svd)
bool run (JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > &svd, const MatrixType &matrix)
Private Types
typedef ColPivHouseholderQR< MatrixType > QRType
Private Attributes
QRType m_qr
internal::plain_col_type< MatrixType >::type m_workspace
Detailed Description
template<typename MatrixType>
class Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
Member Typedef Documentation
QRType
template<typename MatrixType > typedef ColPivHouseholderQR<MatrixType> Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::QRType private
Member Function Documentation
allocate()
template<typename MatrixType > void Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate (const JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > & svd) inline
  {
    if (svd.rows() != m_qr.rows() || svd.cols() != m_qr.cols())
    {
      m_qr.~QRType();
      ::new (&m_qr) QRType(svd.rows(), svd.cols());
    }
    if (svd.m_computeFullU) m_workspace.resize(svd.rows());
    else if (svd.m_computeThinU) m_workspace.resize(svd.cols());
  }
References Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::cols(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeFullU, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeThinU, and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::rows().
run()
template<typename MatrixType > bool Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run (JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > & svd, const MatrixType & matrix) inline
  {
    if(matrix.rows() > matrix.cols())
    {
      m_qr.compute(matrix);
      svd.m_workMatrix = m_qr.matrixQR().block(0,0,matrix.cols(),matrix.cols()).template triangularView<Upper>();
      if(svd.m_computeFullU) m_qr.householderQ().evalTo(svd.m_matrixU, m_workspace);
      else if(svd.m_computeThinU)
      {
        svd.m_matrixU.setIdentity(matrix.rows(), matrix.cols());
        m_qr.householderQ().applyThisOnTheLeft(svd.m_matrixU, m_workspace);
      }
      if(svd.computeV()) svd.m_matrixV = m_qr.colsPermutation();
      return true;
    }
    return false;
  }
References Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::computeV(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeFullU, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeThinU, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_matrixU, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_matrixV, and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_workMatrix.
Member Data Documentation
m_qr
template<typename MatrixType > QRType Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_qr private
m_workspace
template<typename MatrixType > internal::plain_col_type<MatrixType>::type Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_workspace private
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SVD/JacobiSVD.h