Prusa Slicer: ImBitArray< BITCOUNT > Struct Template Reference
ImBitArray< BITCOUNT > Struct Template Reference
#include <src/imgui/imgui_internal.h>
Public Member Functions
ImBitArray ()
void ClearAllBits ()
void SetAllBits ()
bool TestBit (int n) const
void SetBit (int n)
void ClearBit (int n)
void SetBitRange (int n, int n2)
Public Attributes
ImU32 Storage [(BITCOUNT+31) > > 5]
Detailed Description
template<int BITCOUNT>
struct ImBitArray< BITCOUNT >
Constructor & Destructor Documentation
ImBitArray()
template<int BITCOUNT> ImBitArray< BITCOUNT >::ImBitArray () inline
{ ClearAllBits(); }
Member Function Documentation
ClearAllBits()
template<int BITCOUNT> void ImBitArray< BITCOUNT >::ClearAllBits () inline
{ memset(Storage, 0, sizeof(Storage)); }
ClearBit()
template<int BITCOUNT> void ImBitArray< BITCOUNT >::ClearBit (int n) inline
{ IM_ASSERT(n < BITCOUNT); ImBitArrayClearBit(Storage, n); }
References IM_ASSERT, and ImBitArrayClearBit().
Referenced by ImGui::TableMergeDrawChannels().
SetAllBits()
template<int BITCOUNT> void ImBitArray< BITCOUNT >::SetAllBits () inline
{ memset(Storage, 255, sizeof(Storage)); }
SetBit()
template<int BITCOUNT> void ImBitArray< BITCOUNT >::SetBit (int n) inline
{ IM_ASSERT(n < BITCOUNT); ImBitArraySetBit(Storage, n); }
References IM_ASSERT, and ImBitArraySetBit().
SetBitRange()
template<int BITCOUNT> void ImBitArray< BITCOUNT >::SetBitRange (int n, int n2) inline
{ ImBitArraySetBitRange(Storage, n, n2); } // Works on range [n..n2)
References ImBitArraySetBitRange().
Referenced by ImGui::TableMergeDrawChannels().
TestBit()
template<int BITCOUNT> bool ImBitArray< BITCOUNT >::TestBit (int n) const inline
{ IM_ASSERT(n < BITCOUNT); return ImBitArrayTestBit(Storage, n); }
References IM_ASSERT, and ImBitArrayTestBit().
Referenced by ImGui::TableMergeDrawChannels().
Member Data Documentation
Storage
template<int BITCOUNT> ImU32 ImBitArray< BITCOUNT >::Storage[(BITCOUNT+31) > > 5]
Referenced by ImGui::TableMergeDrawChannels().
The documentation for this struct was generated from the following file:
src/imgui/imgui_internal.h