Prusa Slicer: Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > > Struct Template Reference
Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > > Struct Template Reference
#include <src/eigen/Eigen/src/Core/CoreEvaluators.h>
Public Types
enum {
IsRowMajor = XprType::IsRowMajor , IsColMajor = !IsRowMajor , ReverseRow = (Direction == Vertical) || (Direction == BothDirections) , ReverseCol = (Direction == Horizontal) || (Direction == BothDirections) ,
ReversePacket , CoeffReadCost = evaluator<ArgType>::CoeffReadCost , Flags0 = evaluator<ArgType>::Flags , LinearAccess ,
Flags = int(Flags0) & (HereditaryBits | PacketAccessBit | LinearAccess) , Alignment = 0
}
typedef Reverse< ArgType, Direction > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
enum
typedef traits< Reverse< ArgType, Direction > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC unary_evaluator (const XprType &reverse)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Protected Attributes
evaluator< ArgType > m_argImpl
const variable_if_dynamic< Index, ReverseRow ? ArgType::RowsAtCompileTime :1 > m_rows
const variable_if_dynamic< Index, ReverseCol ? ArgType::ColsAtCompileTime :1 > m_cols
Detailed Description
template<typename ArgType, int Direction>
struct Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >
Member Typedef Documentation
CoeffReturnType
template<typename ArgType , int Direction> typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::CoeffReturnType
ExpressionTraits
typedef traits<Reverse< ArgType, Direction > > Eigen::internal::evaluator_base< Reverse< ArgType, Direction > >::ExpressionTraits inherited
Scalar
template<typename ArgType , int Direction> typedef XprType::Scalar Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::Scalar
XprType
template<typename ArgType , int Direction> typedef Reverse<ArgType, Direction> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::XprType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    Alignment = 0
  };
anonymous enum
template<typename ArgType , int Direction> anonymous enum
Enumerator
IsRowMajor
IsColMajor
ReverseRow
ReverseCol
ReversePacket
CoeffReadCost
Flags0
LinearAccess
Flags
Alignment
       {
    IsRowMajor = XprType::IsRowMajor,
    IsColMajor = !IsRowMajor,
    ReverseRow = (Direction == Vertical)   || (Direction == BothDirections),
    ReverseCol = (Direction == Horizontal) || (Direction == BothDirections),
    ReversePacket = (Direction == BothDirections)
                    || ((Direction == Vertical)   && IsColMajor)
                    || ((Direction == Horizontal) && IsRowMajor),
    CoeffReadCost = evaluator<ArgType>::CoeffReadCost,
    // let's enable LinearAccess only with vectorization because of the product overhead
    // FIXME enable DirectAccess with negative strides?
    Flags0 = evaluator<ArgType>::Flags,
    LinearAccess = ( (Direction==BothDirections) && (int(Flags0)&PacketAccessBit) )
                  || ((ReverseRow && XprType::ColsAtCompileTime==1) || (ReverseCol && XprType::RowsAtCompileTime==1))
                 ? LinearAccessBit : 0,
    Flags = int(Flags0) & (HereditaryBits | PacketAccessBit | LinearAccess),
    Alignment = 0 // FIXME in some rare cases, Alignment could be preserved, like a Vector4f.
  };
Constructor & Destructor Documentation
unary_evaluator()
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::unary_evaluator (const XprType & reverse) inline explicit
    : m_argImpl(reverse.nestedExpression()),
      m_rows(ReverseRow ? reverse.nestedExpression().rows() : 1),
      m_cols(ReverseCol ? reverse.nestedExpression().cols() : 1)
  { }
Member Function Documentation
coeff() [1/2]
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff (Index index) const inline
  {
    return m_argImpl.coeff(m_rows.value() * m_cols.value() - index - 1);
  }
coeff() [2/2]
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff (Index row, Index col) const inline
  {
    return m_argImpl.coeff(ReverseRow ? m_rows.value() - row - 1 : row,
                           ReverseCol ? m_cols.value() - col - 1 : col);
  }
References col(), and row().
coeffRef() [1/2]
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef (Index index) inline
  {
    return m_argImpl.coeffRef(m_rows.value() * m_cols.value() - index - 1);
  }
coeffRef() [2/2]
template<typename ArgType , int Direction> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef (Index row, Index col) inline
  {
    return m_argImpl.coeffRef(ReverseRow ? m_rows.value() - row - 1 : row,
                              ReverseCol ? m_cols.value() - col - 1 : col);
  }
References col(), and row().
packet() [1/2]
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet (Index index) const inline
  {
    enum { PacketSize = unpacket_traits<PacketType>::size };
    return preverse(m_argImpl.template packet<LoadMode,PacketType>(m_rows.value() * m_cols.value() - index - PacketSize));
  }
References Eigen::internal::preverse().
packet() [2/2]
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet (Index row, Index col) const inline
  {
    enum {
      PacketSize = unpacket_traits<PacketType>::size,
      OffsetRow  = ReverseRow && IsColMajor ? PacketSize : 1,
      OffsetCol  = ReverseCol && IsRowMajor ? PacketSize : 1
    };
    typedef internal::reverse_packet_cond<PacketType,ReversePacket> reverse_packet;
    return reverse_packet::run(m_argImpl.template packet<LoadMode,PacketType>(
                                  ReverseRow ? m_rows.value() - row - OffsetRow : row,
                                  ReverseCol ? m_cols.value() - col - OffsetCol : col));
  }
References col(), and row().
writePacket() [1/2]
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket (Index index, const PacketType & x) inline
  {
    enum { PacketSize = unpacket_traits<PacketType>::size };
    m_argImpl.template writePacket<LoadMode>
      (m_rows.value() * m_cols.value() - index - PacketSize, preverse(x));
  }
References Eigen::internal::preverse().
writePacket() [2/2]
template<typename ArgType , int Direction> template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket (Index row, Index col, const PacketType & x) inline
  {
    // FIXME we could factorize some code with packet(i,j)
    enum {
      PacketSize = unpacket_traits<PacketType>::size,
      OffsetRow  = ReverseRow && IsColMajor ? PacketSize : 1,
      OffsetCol  = ReverseCol && IsRowMajor ? PacketSize : 1
    };
    typedef internal::reverse_packet_cond<PacketType,ReversePacket> reverse_packet;
    m_argImpl.template writePacket<LoadMode>(
                                  ReverseRow ? m_rows.value() - row - OffsetRow : row,
                                  ReverseCol ? m_cols.value() - col - OffsetCol : col,
                                  reverse_packet::run(x));
  }
References col(), and row().
Member Data Documentation
m_argImpl
template<typename ArgType , int Direction> evaluator<ArgType> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::m_argImpl protected
m_cols
template<typename ArgType , int Direction> const variable_if_dynamic<Index, ReverseCol ? ArgType::ColsAtCompileTime : 1> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::m_cols protected
m_rows
template<typename ArgType , int Direction> const variable_if_dynamic<Index, ReverseRow ? ArgType::RowsAtCompileTime : 1> Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::m_rows protected
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/CoreEvaluators.h