Prusa Slicer: Slic3r::sla::RotOptimizeParams Class Reference
Slic3r::sla::RotOptimizeParams Class Reference
#include <src/libslic3r/SLA/Rotfinder.hpp>
Public Member Functions
RotOptimizeParams & accuracy (float a)
RotOptimizeParams & print_config (const DynamicPrintConfig *c)
RotOptimizeParams & statucb (RotOptimizeStatusCB cb)
float accuracy () const
const DynamicPrintConfig * print_config () const
const RotOptimizeStatusCB & statuscb () const
Private Attributes
float m_accuracy = 1.
const DynamicPrintConfig * m_print_config = nullptr
RotOptimizeStatusCB m_statuscb = [](int) { return true; }
Detailed Description
Member Function Documentation
accuracy() [1/2]
float Slic3r::sla::RotOptimizeParams::accuracy () const inline
{ return m_accuracy; }
References m_accuracy.
accuracy() [2/2]
RotOptimizeParams & Slic3r::sla::RotOptimizeParams::accuracy (float a) inline
{ m_accuracy = a; return *this; }
References m_accuracy.
Referenced by Slic3r::GUI::RotoptimizeJob::process().
print_config() [1/2]
const DynamicPrintConfig * Slic3r::sla::RotOptimizeParams::print_config () const inline
{ return m_print_config; }
References m_print_config.
print_config() [2/2]
RotOptimizeParams & Slic3r::sla::RotOptimizeParams::print_config (const DynamicPrintConfig * c) inline
    {
        m_print_config = c;
        return *this;
    }
References m_print_config.
Referenced by Slic3r::sla::find_least_supports_rotation(), and Slic3r::GUI::RotoptimizeJob::process().
statucb()
RotOptimizeParams & Slic3r::sla::RotOptimizeParams::statucb (RotOptimizeStatusCB cb) inline
    {
        m_statuscb = std::move(cb);
        return *this;
    }
References m_statuscb.
Referenced by Slic3r::GUI::RotoptimizeJob::process().
statuscb()
const RotOptimizeStatusCB & Slic3r::sla::RotOptimizeParams::statuscb () const inline
{ return m_statuscb; }
References m_statuscb.
Referenced by Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::statusfn(), and Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::stopcond().
Member Data Documentation
m_accuracy
float Slic3r::sla::RotOptimizeParams::m_accuracy = 1. private
Referenced by accuracy(), and accuracy().
m_print_config
const DynamicPrintConfig* Slic3r::sla::RotOptimizeParams::m_print_config = nullptr private
Referenced by print_config(), and print_config().
m_statuscb
RotOptimizeStatusCB Slic3r::sla::RotOptimizeParams::m_statuscb = [](int) { return true; } private
Referenced by statucb(), and statuscb().
The documentation for this class was generated from the following file:
src/libslic3r/SLA/Rotfinder.hpp