Prusa Slicer: Slic3r::MutablePolygon::iterator Class Reference
Slic3r::MutablePolygon::iterator Class Reference
#include <src/libslic3r/MutablePolygon.hpp>
Public Member Functions
bool operator== (const iterator &rhs) const
bool operator!= (const iterator &rhs) const
iterator & operator-- ()
iterator operator-- (int)
iterator & operator++ ()
iterator operator++ (int)
iterator prev () const
iterator next () const
bool valid () const
PointType & operator* () const
PointType * operator-> () const
MutablePolygon & polygon () const
IndexType size () const
iterator & remove ()
iterator insert (const PointType pt) const
Private Member Functions
iterator (MutablePolygon *data, IndexType idx)
Private Attributes
MutablePolygon * m_data
IndexType m_idx
Friends
class MutablePolygon
class range
Detailed Description
Constructor & Destructor Documentation
iterator()
Slic3r::MutablePolygon::iterator::iterator (MutablePolygon * data, IndexType idx) inline private
: m_data(data), m_idx(idx) {}
Member Function Documentation
insert()
iterator Slic3r::MutablePolygon::iterator::insert (const PointType pt) const inline
{ return m_data->insert(*this, pt); }
References Slic3r::MutablePolygon::insert(), and m_data.
next()
iterator Slic3r::MutablePolygon::iterator::next () const inline
{ assert(this->valid()); return { m_data, m_data->at(m_idx).next }; }
References Slic3r::MutablePolygon::at(), m_data, m_idx, Slic3r::MutablePolygon::LinkedPoint::next, and valid().
Referenced by Slic3r::clip_narrow_corner(), and Slic3r::smooth_outward().
operator!=()
bool Slic3r::MutablePolygon::iterator::operator!= (const iterator & rhs) const inline
{ return !(*this == rhs); }
operator*()
PointType & Slic3r::MutablePolygon::iterator::operator* () const inline
{ return m_data->at(m_idx).point; }
References Slic3r::MutablePolygon::at(), m_data, m_idx, and Slic3r::MutablePolygon::LinkedPoint::point.
operator++() [1/2]
iterator & Slic3r::MutablePolygon::iterator::operator++ () inline
{ assert(this->valid()); m_idx = m_data->at(m_idx).next; return *this; }
References Slic3r::MutablePolygon::at(), m_data, m_idx, Slic3r::MutablePolygon::LinkedPoint::next, and valid().
operator++() [2/2]
iterator Slic3r::MutablePolygon::iterator::operator++ (int) inline
{ iterator result(*this); ++(*this); return result; }
operator--() [1/2]
iterator & Slic3r::MutablePolygon::iterator::operator-- () inline
{ assert(this->valid()); m_idx = m_data->at(m_idx).prev; return *this; }
References Slic3r::MutablePolygon::at(), m_data, m_idx, Slic3r::MutablePolygon::LinkedPoint::prev, and valid().
operator--() [2/2]
iterator Slic3r::MutablePolygon::iterator::operator-- (int) inline
{ iterator result(*this); --(*this); return result; }
operator->()
PointType * Slic3r::MutablePolygon::iterator::operator-> () const inline
{ return &m_data->at(m_idx).point; }
References Slic3r::MutablePolygon::at(), m_data, m_idx, and Slic3r::MutablePolygon::LinkedPoint::point.
operator==()
bool Slic3r::MutablePolygon::iterator::operator== (const iterator & rhs) const inline
{ assert(m_data == rhs.m_data); assert(this->valid()); return m_idx == rhs.m_idx; }
References m_data, m_idx, and valid().
polygon()
MutablePolygon & Slic3r::MutablePolygon::iterator::polygon () const inline
{ assert(this->valid()); return *m_data; }
References m_data, and valid().
Referenced by Slic3r::clip_narrow_corner().
prev()
iterator Slic3r::MutablePolygon::iterator::prev () const inline
{ assert(this->valid()); return { m_data, m_data->at(m_idx).prev }; }
References Slic3r::MutablePolygon::at(), m_data, m_idx, Slic3r::MutablePolygon::LinkedPoint::prev, and valid().
Referenced by Slic3r::clip_narrow_corner(), and Slic3r::smooth_outward().
remove()
iterator & Slic3r::MutablePolygon::iterator::remove () inline
{ m_idx = m_data->remove(*this).m_idx; return *this; }
References m_data, m_idx, and Slic3r::MutablePolygon::remove().
Referenced by Slic3r::MutablePolygon::range::remove_back(), and Slic3r::MutablePolygon::range::remove_front().
size()
IndexType Slic3r::MutablePolygon::iterator::size () const inline
{ assert(this->valid()); return m_data->size(); }
References m_data, Slic3r::MutablePolygon::size(), and valid().
valid()
bool Slic3r::MutablePolygon::iterator::valid () const inline
{ return m_idx >= 0; }
References m_idx.
Referenced by Slic3r::MutablePolygon::range::empty(), next(), operator++(), operator--(), operator==(), polygon(), prev(), and size().
Friends And Related Symbol Documentation
MutablePolygon
friend class MutablePolygon friend
range
friend class range friend
Member Data Documentation
m_data
MutablePolygon* Slic3r::MutablePolygon::iterator::m_data private
Referenced by Slic3r::MutablePolygon::insert(), insert(), next(), operator*(), operator++(), operator--(), operator->(), operator==(), polygon(), prev(), remove(), Slic3r::MutablePolygon::remove(), and size().
m_idx
IndexType Slic3r::MutablePolygon::iterator::m_idx private
Referenced by Slic3r::MutablePolygon::insert(), Slic3r::MutablePolygon::range::make_empty(), next(), operator*(), operator++(), operator--(), operator->(), operator==(), prev(), remove(), Slic3r::MutablePolygon::remove(), and valid().
The documentation for this class was generated from the following file:
src/libslic3r/MutablePolygon.hpp