Prusa Slicer: Slic3r::GUI::Mouse3DController::State::QueueItem Struct Reference
Slic3r::GUI::Mouse3DController::State::QueueItem Struct Reference
#include <src/slic3r/GUI/Mouse3DController.hpp>
Public Member Functions
bool is_translation () const
bool is_rotation () const
bool is_buttons () const
Static Public Member Functions
static QueueItem translation (const Vec3d &translation)
static QueueItem rotation (const Vec3d &rotation)
static QueueItem buttons (unsigned int buttons)
Public Attributes
Vec3d vector
unsigned int type_or_buttons
Static Public Attributes
static constexpr unsigned int TranslationType = std::numeric_limits<unsigned int>::max()
static constexpr unsigned int RotationType = TranslationType - 1
Detailed Description
Member Function Documentation
buttons()
static QueueItem Slic3r::GUI::Mouse3DController::State::QueueItem::buttons (unsigned int buttons) inline static
{ QueueItem out; out.type_or_buttons = buttons; return out; }
References buttons(), and type_or_buttons.
Referenced by buttons().
is_buttons()
bool Slic3r::GUI::Mouse3DController::State::QueueItem::is_buttons () const inline
{ return ! this->is_translation() && ! this->is_rotation(); }
References is_rotation(), and is_translation().
is_rotation()
bool Slic3r::GUI::Mouse3DController::State::QueueItem::is_rotation () const inline
{ return this->type_or_buttons == RotationType; }
References RotationType, and type_or_buttons.
Referenced by is_buttons().
is_translation()
bool Slic3r::GUI::Mouse3DController::State::QueueItem::is_translation () const inline
{ return this->type_or_buttons == TranslationType; }
References TranslationType, and type_or_buttons.
Referenced by is_buttons().
rotation()
static QueueItem Slic3r::GUI::Mouse3DController::State::QueueItem::rotation (const Vec3d & rotation) inline static
{ QueueItem out; out.vector = rotation; out.type_or_buttons = RotationType; return out; }
References rotation(), RotationType, type_or_buttons, and vector.
Referenced by rotation().
translation()
static QueueItem Slic3r::GUI::Mouse3DController::State::QueueItem::translation (const Vec3d & translation) inline static
{ QueueItem out; out.vector = translation; out.type_or_buttons = TranslationType; return out; }
References translation(), TranslationType, type_or_buttons, and vector.
Referenced by Slic3r::GUI::Mouse3DController::State::append_translation(), and translation().
Member Data Documentation
RotationType
constexpr unsigned int Slic3r::GUI::Mouse3DController::State::QueueItem::RotationType = TranslationType - 1 static constexpr
Referenced by is_rotation(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), and rotation().
TranslationType
constexpr unsigned int Slic3r::GUI::Mouse3DController::State::QueueItem::TranslationType = std::numeric_limits<unsigned int>::max() static constexpr
Referenced by is_translation(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), and translation().
type_or_buttons
unsigned int Slic3r::GUI::Mouse3DController::State::QueueItem::type_or_buttons
Referenced by buttons(), is_rotation(), is_translation(), rotation(), and translation().
vector
Vec3d Slic3r::GUI::Mouse3DController::State::QueueItem::vector
Referenced by rotation(), and translation().
The documentation for this struct was generated from the following file:
src/slic3r/GUI/Mouse3DController.hpp