Prusa Slicer: Slic3r::StaticPrintConfig::StaticCache< T > Class Template Reference
Slic3r::StaticPrintConfig::StaticCache< T > Class Template Reference
#include <src/libslic3r/PrintConfig.hpp>
Public Member Functions
StaticCache ()
~StaticCache ()
bool initialized () const
ConfigOption * optptr (const std::string &name, T *owner) const
const ConfigOption * optptr (const std::string &name, const T *owner) const
const std::vector< std::string > & keys () const
const T & defaults () const
void finalize (T *defaults, const ConfigDef *defs)
template<typename T >
void opt_add (const std::string &name, const char *base_ptr, const T &opt)
Protected Attributes
std::map< std::string, ptrdiff_t > m_map_name_to_offset
Private Attributes
T * m_defaults
std::vector< std::string > m_keys
Detailed Description
template<typename T>
class Slic3r::StaticPrintConfig::StaticCache< T >
Constructor & Destructor Documentation
StaticCache()
template<typename T > Slic3r::StaticPrintConfig::StaticCache< T >::StaticCache () inline
: m_defaults(nullptr) {}
~StaticCache()
template<typename T > Slic3r::StaticPrintConfig::StaticCache< T >::~StaticCache () inline
{ delete m_defaults; m_defaults = nullptr; }
References Slic3r::StaticPrintConfig::StaticCache< T >::m_defaults.
Member Function Documentation
defaults()
template<typename T > const T & Slic3r::StaticPrintConfig::StaticCache< T >::defaults () const inline
{ return *m_defaults; }
References Slic3r::StaticPrintConfig::StaticCache< T >::m_defaults.
Referenced by Slic3r::StaticPrintConfig::StaticCache< T >::finalize().
finalize()
template<typename T > void Slic3r::StaticPrintConfig::StaticCache< T >::finalize (T * defaults, const ConfigDef * defs) inline
        {
            assert(defs != nullptr);
            m_defaults = defaults;
            m_keys.clear();
            m_keys.reserve(m_map_name_to_offset.size());
            for (const auto &kvp : defs->options) {
                // Find the option given the option name kvp.first by an offset from (char*)m_defaults.
                ConfigOption *opt = this->optptr(kvp.first, m_defaults);
                if (opt == nullptr)
                    // This option is not defined by the ConfigBase of type T.
                    continue;
                m_keys.emplace_back(kvp.first);
                const ConfigOptionDef *def = defs->get(kvp.first);
                assert(def != nullptr);
                if (def->default_value)
                    opt->set(def->default_value.get());
            }
        }
References Slic3r::StaticPrintConfig::def(), Slic3r::StaticPrintConfig::StaticCache< T >::defaults(), Slic3r::ConfigDef::get(), Slic3r::StaticPrintConfig::StaticCache< T >::m_defaults, Slic3r::StaticPrintConfig::StaticCache< T >::m_keys, Slic3r::StaticPrintConfig::StaticCacheBase::m_map_name_to_offset, Slic3r::ConfigDef::options, Slic3r::StaticPrintConfig::StaticCache< T >::optptr(), and Slic3r::ConfigOption::set().
initialized()
template<typename T > bool Slic3r::StaticPrintConfig::StaticCache< T >::initialized () const inline
{ return ! m_keys.empty(); }
References Slic3r::StaticPrintConfig::StaticCache< T >::m_keys.
keys()
template<typename T > const std::vector< std::string > & Slic3r::StaticPrintConfig::StaticCache< T >::keys () const inline
{ return m_keys; }
References Slic3r::StaticPrintConfig::StaticCache< T >::m_keys.
opt_add()
template<typename T > void Slic3r::StaticPrintConfig::StaticCacheBase::opt_add (const std::string & name, const char * base_ptr, const T & opt) inline inherited
        {
            assert(m_map_name_to_offset.find(name) == m_map_name_to_offset.end());
            m_map_name_to_offset[name] = (const char*)&opt - base_ptr;
        }
References Slic3r::StaticPrintConfig::StaticCacheBase::m_map_name_to_offset.
optptr() [1/2]
template<typename T > const ConfigOption * Slic3r::StaticPrintConfig::StaticCache< T >::optptr (const std::string & name, const T * owner) const inline
        {
            const auto it = m_map_name_to_offset.find(name);
            return (it == m_map_name_to_offset.end()) ? nullptr : reinterpret_cast<const ConfigOption*>((const char*)owner + it->second);
        }
References Slic3r::StaticPrintConfig::StaticCacheBase::m_map_name_to_offset.
optptr() [2/2]
template<typename T > ConfigOption * Slic3r::StaticPrintConfig::StaticCache< T >::optptr (const std::string & name, T * owner) const inline
        {
            const auto it = m_map_name_to_offset.find(name);
            return (it == m_map_name_to_offset.end()) ? nullptr : reinterpret_cast<ConfigOption*>((char*)owner + it->second);
        }
References Slic3r::StaticPrintConfig::StaticCacheBase::m_map_name_to_offset.
Referenced by Slic3r::StaticPrintConfig::StaticCache< T >::finalize().
Member Data Documentation
m_defaults
template<typename T > T* Slic3r::StaticPrintConfig::StaticCache< T >::m_defaults private
Referenced by Slic3r::StaticPrintConfig::StaticCache< T >::~StaticCache(), Slic3r::StaticPrintConfig::StaticCache< T >::defaults(), and Slic3r::StaticPrintConfig::StaticCache< T >::finalize().
m_keys
template<typename T > std::vector<std::string> Slic3r::StaticPrintConfig::StaticCache< T >::m_keys private
Referenced by Slic3r::StaticPrintConfig::StaticCache< T >::finalize(), Slic3r::StaticPrintConfig::StaticCache< T >::initialized(), and Slic3r::StaticPrintConfig::StaticCache< T >::keys().
m_map_name_to_offset
std::map<std::string, ptrdiff_t> Slic3r::StaticPrintConfig::StaticCacheBase::m_map_name_to_offset protected inherited
Referenced by Slic3r::StaticPrintConfig::StaticCache< T >::finalize(), Slic3r::StaticPrintConfig::StaticCacheBase::opt_add(), Slic3r::StaticPrintConfig::StaticCache< T >::optptr(), and Slic3r::StaticPrintConfig::StaticCache< T >::optptr().
The documentation for this class was generated from the following file:
src/libslic3r/PrintConfig.hpp