Prusa Slicer: Slic3r::_3DScene Struct Reference
Slic3r::_3DScene Struct Reference
#include <src/slic3r/GUI/3DScene.hpp>
Static Public Member Functions
static void thick_lines_to_verts (const Lines &lines, const std::vector< double > &widths, const std::vector< double > &heights, bool closed, double top_z, GUI::GLModel::Geometry &geometry)
static void thick_lines_to_verts (const Lines3 &lines, const std::vector< double > &widths, const std::vector< double > &heights, bool closed, GUI::GLModel::Geometry &geometry)
static void extrusionentity_to_verts (const ExtrusionPath &extrusion_path, float print_z, const Point &copy, GUI::GLModel::Geometry &geometry)
static void extrusionentity_to_verts (const ExtrusionLoop &extrusion_loop, float print_z, const Point &copy, GUI::GLModel::Geometry &geometry)
static void extrusionentity_to_verts (const ExtrusionMultiPath &extrusion_multi_path, float print_z, const Point &copy, GUI::GLModel::Geometry &geometry)
static void extrusionentity_to_verts (const ExtrusionEntityCollection &extrusion_entity_collection, float print_z, const Point &copy, GUI::GLModel::Geometry &geometry)
static void extrusionentity_to_verts (const ExtrusionEntity *extrusion_entity, float print_z, const Point &copy, GUI::GLModel::Geometry &geometry)
Detailed Description
Member Function Documentation
extrusionentity_to_verts() [1/5]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionEntity * extrusion_entity, float print_z, const Point & copy, GUI::GLModel::Geometry & geometry) static
{
    if (extrusion_entity != nullptr) {
        auto* extrusion_path = dynamic_cast<const ExtrusionPath*>(extrusion_entity);
        if (extrusion_path != nullptr)
            extrusionentity_to_verts(*extrusion_path, print_z, copy, geometry);
        else {
            auto* extrusion_loop = dynamic_cast<const ExtrusionLoop*>(extrusion_entity);
            if (extrusion_loop != nullptr)
                extrusionentity_to_verts(*extrusion_loop, print_z, copy, geometry);
            else {
                auto* extrusion_multi_path = dynamic_cast<const ExtrusionMultiPath*>(extrusion_entity);
                if (extrusion_multi_path != nullptr)
                    extrusionentity_to_verts(*extrusion_multi_path, print_z, copy, geometry);
                else {
                    auto* extrusion_entity_collection = dynamic_cast<const ExtrusionEntityCollection*>(extrusion_entity);
                    if (extrusion_entity_collection != nullptr)
                        extrusionentity_to_verts(*extrusion_entity_collection, print_z, copy, geometry);
                    else
                        throw Slic3r::RuntimeError("Unexpected extrusion_entity type in to_verts()");
                }
            }
        }
    }
}
References extrusionentity_to_verts().
extrusionentity_to_verts() [2/5]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionEntityCollection & extrusion_entity_collection, float print_z, const Point & copy, GUI::GLModel::Geometry & geometry) static
{
    for (const ExtrusionEntity* extrusion_entity : extrusion_entity_collection.entities)
        extrusionentity_to_verts(extrusion_entity, print_z, copy, geometry);
}
References Slic3r::ExtrusionEntityCollection::entities, and extrusionentity_to_verts().
extrusionentity_to_verts() [3/5]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionLoop & extrusion_loop, float print_z, const Point & copy, GUI::GLModel::Geometry & geometry) static
{
    Lines               lines;
    std::vector<double> widths;
    std::vector<double> heights;
    for (const ExtrusionPath& extrusion_path : extrusion_loop.paths) {
        Polyline            polyline = extrusion_path.polyline;
        polyline.remove_duplicate_points();
        polyline.translate(copy);
        const Lines lines_this = polyline.lines();
        append(lines, lines_this);
        widths.insert(widths.end(), lines_this.size(), extrusion_path.width);
        heights.insert(heights.end(), lines_this.size(), extrusion_path.height);
    }
    thick_lines_to_verts(lines, widths, heights, true, print_z, geometry);
}
References Slic3r::append(), Slic3r::Polyline::lines(), Slic3r::ExtrusionLoop::paths, Slic3r::MultiPoint::remove_duplicate_points(), thick_lines_to_verts(), and Slic3r::MultiPoint::translate().
extrusionentity_to_verts() [4/5]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionMultiPath & extrusion_multi_path, float print_z, const Point & copy, GUI::GLModel::Geometry & geometry) static
{
    Lines               lines;
    std::vector<double> widths;
    std::vector<double> heights;
    for (const ExtrusionPath& extrusion_path : extrusion_multi_path.paths) {
        Polyline            polyline = extrusion_path.polyline;
        polyline.remove_duplicate_points();
        polyline.translate(copy);
        const Lines lines_this = polyline.lines();
        append(lines, lines_this);
        widths.insert(widths.end(), lines_this.size(), extrusion_path.width);
        heights.insert(heights.end(), lines_this.size(), extrusion_path.height);
    }
    thick_lines_to_verts(lines, widths, heights, false, print_z, geometry);
}
References Slic3r::append(), Slic3r::Polyline::lines(), Slic3r::ExtrusionMultiPath::paths, Slic3r::MultiPoint::remove_duplicate_points(), thick_lines_to_verts(), and Slic3r::MultiPoint::translate().
extrusionentity_to_verts() [5/5]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionPath & extrusion_path, float print_z, const Point & copy, GUI::GLModel::Geometry & geometry) static
{
    Polyline            polyline = extrusion_path.polyline;
    polyline.remove_duplicate_points();
    polyline.translate(copy);
    const Lines               lines = polyline.lines();
    std::vector<double> widths(lines.size(), extrusion_path.width);
    std::vector<double> heights(lines.size(), extrusion_path.height);
    thick_lines_to_verts(lines, widths, heights, false, print_z, geometry);
}
References Slic3r::ExtrusionPath::height, Slic3r::Polyline::lines(), Slic3r::ExtrusionPath::polyline, Slic3r::MultiPoint::remove_duplicate_points(), thick_lines_to_verts(), Slic3r::MultiPoint::translate(), and Slic3r::ExtrusionPath::width.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), extrusionentity_to_verts(), and extrusionentity_to_verts().
thick_lines_to_verts() [1/2]
void Slic3r::_3DScene::thick_lines_to_verts (const Lines & lines, const std::vector< double > & widths, const std::vector< double > & heights, bool closed, double top_z, GUI::GLModel::Geometry & geometry) static
{
    thick_lines_to_geometry(lines, widths, heights, closed, top_z, geometry);
}
References Slic3r::thick_lines_to_geometry().
Referenced by extrusionentity_to_verts(), extrusionentity_to_verts(), and extrusionentity_to_verts().
thick_lines_to_verts() [2/2]
void Slic3r::_3DScene::thick_lines_to_verts (const Lines3 & lines, const std::vector< double > & widths, const std::vector< double > & heights, bool closed, GUI::GLModel::Geometry & geometry) static
{
    thick_lines_to_geometry(lines, widths, heights, closed, geometry);
}
References Slic3r::thick_lines_to_geometry().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/3DScene.hpp
src/slic3r/GUI/3DScene.cpp