Prusa Slicer: libnest2d::_Box< P > Class Template Reference
libnest2d::_Box< P > Class Template Reference
An abstraction of a box;.
#include <src/libnest2d/include/libnest2d/geometry_traits.hpp>
Public Types
using Tag = BoxTag
using PointType = P
Public Member Functions
_Box (const P &center={TCoord< P >(0), TCoord< P >(0)})
_Box (const P &p, const P &pp)
_Box (TCoord< P > width, TCoord< P > height, const P &p={TCoord< P >(0), TCoord< P >(0)})
const P & minCorner () const BP2D_NOEXCEPT
const P & maxCorner () const BP2D_NOEXCEPT
P & minCorner () BP2D_NOEXCEPT
P & maxCorner () BP2D_NOEXCEPT
TCoord< P > width () const BP2D_NOEXCEPT
TCoord< P > height () const BP2D_NOEXCEPT
P center () const BP2D_NOEXCEPT
template<class Unit = TCompute<P>>
Unit area () const BP2D_NOEXCEPT
Static Public Member Functions
static _Box infinite (const P &center={TCoord< P >(0), TCoord< P >(0)})
Private Attributes
P p1
P p2
Detailed Description
template<class P>
class libnest2d::_Box< P >
An abstraction of a box;.
Member Typedef Documentation
PointType
template<class P > using libnest2d::_Box< P >::PointType = P
Tag
template<class P > using libnest2d::_Box< P >::Tag = BoxTag
Constructor & Destructor Documentation
_Box() [1/3]
template<class P > libnest2d::_Box< P >::_Box (const P & center = {TCoord<P>(0), TCoord<P>(0)}) inline
                                  {TCoord<P>(0), TCoord<P>(0)}):
        _Box(TCoord<P>(0), TCoord<P>(0), center) {}
_Box() [2/3]
template<class P > libnest2d::_Box< P >::_Box (const P & p, const P & pp) inline
                                        :
        PointPair<P>({p, pp}) {}
_Box() [3/3]
template<class P > libnest2d::_Box< P >::_Box (TCoord< P > width, TCoord< P > height, const P & p = {TCoord<P>(0), TCoord<P>(0)}) inline
                                                                        :
    PointPair<P>({center - P{width / 2, height / 2},
                  center + P{width / 2, height / 2} +
                      P{modulo(width, TCoord<P>(2)),
                        modulo(height, TCoord<P>(2))}}) {}
References libnest2d::_Box< P >::center(), libnest2d::_Box< P >::height(), libnest2d::modulo(), and libnest2d::_Box< P >::width().
Member Function Documentation
area()
template<class P > template<class Unit = TCompute<P>> Unit libnest2d::_Box< P >::area () const inline
{
        constexpr TCoord<P> Zero{0};
        Unit s = width() < Zero || height() < Zero ? Unit(-1) : Unit(1);
        return s * libnest2d::abs(Unit(width()) * height());
    }
References libnest2d::abs(), libnest2d::_Box< P >::height(), and libnest2d::_Box< P >::width().
Referenced by Slic3r::arrangement::fixed_overfit().
center()
template<class P > P libnest2d::_Box< P >::center inline
{
    auto& minc = minCorner();
    auto& maxc = maxCorner();
    using Coord = TCoord<P>;
    P ret = { // No rounding here, we dont know if these are int coords
        // Doing the division like this increases the max range of x and y coord
        getX(minc) / Coord(2) + getX(maxc) / Coord(2),
        getY(minc) / Coord(2) + getY(maxc) / Coord(2)
    };
    return ret;
}
References libnest2d::getX(), and libnest2d::getY().
Referenced by libnest2d::_Box< P >::_Box(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::finalAlign(), Slic3r::arrangement::AutoArranger< TBin >::objfunc(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::setInitialPosition().
height()
template<class P > TCoord< P > libnest2d::_Box< P >::height inline
{
    return pointlike::y(maxCorner()) - pointlike::y(minCorner());
}
References libnest2d::pointlike::y().
Referenced by libnest2d::_Box< P >::_Box(), libnest2d::placers::_BottomLeftPlacer< RawShape >::_trypack(), libnest2d::_Box< P >::area(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), and libnest2d::svg::SVGWriter< RawShape >::setSize().
infinite()
template<class P > _Box< P > libnest2d::_Box< P >::infinite (const P & center = {TCoord<P>(0), TCoord<P>(0)}) inline static
{
    using C = TCoord<P>;
    _Box<P> ret;
    // It is important for Mx and My to be strictly less than half of the
    // range of type C. width(), height() and area() will not overflow this way.
    C Mx = C((std::numeric_limits<C>::lowest() + 2 * getX(center)) / 4.01);
    C My = C((std::numeric_limits<C>::lowest() + 2 * getY(center)) / 4.01);
    ret.maxCorner() = center - P{Mx, My};
    ret.minCorner() = center + P{Mx, My};
    return ret;
}
References libnest2d::getX(), libnest2d::getY(), libnest2d::_Box< P >::maxCorner(), and libnest2d::_Box< P >::minCorner().
maxCorner() [1/2]
template<class P > P & libnest2d::_Box< P >::maxCorner () inline
{ return p2; }
References libnest2d::PointPair< P >::p2.
maxCorner() [2/2]
template<class P > const P & libnest2d::_Box< P >::maxCorner () const inline
{ return p2; }
References libnest2d::PointPair< P >::p2.
Referenced by libnest2d::shapelike::boundingBox(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::finalAlign(), boost::geometry::traits::indexed_access< bp2d::Box, max_corner, 0 >::get(), boost::geometry::traits::indexed_access< bp2d::Box, max_corner, 1 >::get(), libnest2d::_Box< P >::infinite(), libnest2d::shapelike::offset(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::placeOutsideOfBin(), boost::geometry::traits::indexed_access< bp2d::Box, max_corner, 0 >::set(), boost::geometry::traits::indexed_access< bp2d::Box, max_corner, 1 >::set(), libnest2d::placers::_BottomLeftPlacer< RawShape >::setInitialPosition(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::setInitialPosition().
minCorner() [1/2]
template<class P > P & libnest2d::_Box< P >::minCorner () inline
{ return p1; }
References libnest2d::PointPair< P >::p1.
minCorner() [2/2]
template<class P > const P & libnest2d::_Box< P >::minCorner () const inline
{ return p1; }
References libnest2d::PointPair< P >::p1.
Referenced by libnest2d::shapelike::boundingBox(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::finalAlign(), boost::geometry::traits::indexed_access< bp2d::Box, min_corner, 0 >::get(), boost::geometry::traits::indexed_access< bp2d::Box, min_corner, 1 >::get(), libnest2d::_Box< P >::infinite(), libnest2d::shapelike::offset(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), boost::geometry::traits::indexed_access< bp2d::Box, min_corner, 0 >::set(), boost::geometry::traits::indexed_access< bp2d::Box, min_corner, 1 >::set(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::setInitialPosition().
width()
template<class P > TCoord< P > libnest2d::_Box< P >::width inline
{
    return pointlike::x(maxCorner()) - pointlike::x(minCorner());
}
References libnest2d::pointlike::x().
Referenced by libnest2d::_Box< P >::_Box(), libnest2d::placers::_BottomLeftPlacer< RawShape >::_trypack(), libnest2d::_Box< P >::area(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), and libnest2d::svg::SVGWriter< RawShape >::setSize().
Member Data Documentation
p1
template<class P > P libnest2d::PointPair< P >::p1 inherited
Referenced by libnest2d::_Segment< P >::first(), libnest2d::_Segment< P >::first(), libnest2d::_Box< P >::minCorner(), and libnest2d::_Box< P >::minCorner().
p2
template<class P > P libnest2d::PointPair< P >::p2 inherited
Referenced by libnest2d::_Box< P >::maxCorner(), libnest2d::_Box< P >::maxCorner(), libnest2d::_Segment< P >::second(), and libnest2d::_Segment< P >::second().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/geometry_traits.hpp