Prusa Slicer: ModeButton Class Reference
ModeButton Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
ModeButton (wxWindow *parent, wxWindowID id, const std::string &icon_name="", const wxString &mode=wxEmptyString, const wxSize &size=wxDefaultSize, const wxPoint &pos=wxDefaultPosition)
ModeButton (wxWindow *parent, const wxString &mode=wxEmptyString, const std::string &icon_name="", int px_cnt=16)
ModeButton (wxWindow *parent, int mode_id, const wxString &mode=wxEmptyString, int px_cnt=16)
~ModeButton ()
void Init (const wxString &mode)
void OnButton (wxCommandEvent &event)
void OnEnterBtn (wxMouseEvent &event)
void OnLeaveBtn (wxMouseEvent &event)
void SetState (const bool state)
void update_bitmap ()
bool is_selected ()
void sys_color_changed () override
void SetBitmap_ (const ScalableBitmap &bmp)
bool SetBitmap_ (const std::string &bmp_name)
void SetBitmapDisabled_ (const ScalableBitmap &bmp)
int GetBitmapHeight ()
Protected Member Functions
void focus_button (const bool focus)
Protected Attributes
int m_px_cnt { 16 }
bool m_has_border {false}
Private Attributes
bool m_is_selected {false}
int m_mode_id {-1}
wxString m_tt_selected
wxString m_tt_focused
wxBitmapBundle m_bmp
wxWindow * m_parent { nullptr }
std::string m_current_icon_name
std::string m_disabled_icon_name
int m_width {-1}
int m_height {-1}
Detailed Description
Constructor & Destructor Documentation
ModeButton() [1/3]
ModeButton::ModeButton (wxWindow * parent, wxWindowID id, const std::string & icon_name = "", const wxString & mode = wxEmptyString, const wxSize & size = wxDefaultSize, const wxPoint & pos = wxDefaultPosition)
                                                           :
    ScalableButton(parent, id, icon_name, mode, size, pos, wxBU_EXACTFIT)
{
    Init(mode);
}
References Init().
ModeButton() [2/3]
ModeButton::ModeButton (wxWindow * parent, const wxString & mode = wxEmptyString, const std::string & icon_name = "", int px_cnt = 16)
                                                     :
    ScalableButton(parent, wxID_ANY, icon_name, mode, wxDefaultSize, wxDefaultPosition, wxBU_EXACTFIT, px_cnt)
{
    Init(mode);
}
References Init().
ModeButton() [3/3]
ModeButton::ModeButton (wxWindow * parent, int mode_id, const wxString & mode = wxEmptyString, int px_cnt = 16)
                                                      :
    ScalableButton(parent, wxID_ANY, "", mode, wxDefaultSize, wxDefaultPosition, wxBU_EXACTFIT, px_cnt),
    m_mode_id(mode_id)
{
    update_bitmap();
    Init(mode);
}
References Init(), and update_bitmap().
~ModeButton()
ModeButton::~ModeButton () inline
{}
Member Function Documentation
focus_button()
void ModeButton::focus_button (const bool focus) protected
{
    const wxFont& new_font = focus ?
                             Slic3r::GUI::wxGetApp().bold_font() :
                             Slic3r::GUI::wxGetApp().normal_font();
    SetFont(new_font);
#ifdef _WIN32
    GetParent()->Refresh(); // force redraw a background of the selected mode button
#else
    SetForegroundColour(wxSystemSettings::GetColour(focus ? wxSYS_COLOUR_BTNTEXT :
#if defined (__linux__) && defined (__WXGTK3__)
        wxSYS_COLOUR_GRAYTEXT
#elif defined (__linux__) && defined (__WXGTK2__)
        wxSYS_COLOUR_BTNTEXT
#else
        wxSYS_COLOUR_BTNSHADOW
#endif
    ));
#endif /* no _WIN32 */
    Refresh();
    Update();
}
Referenced by OnButton(), OnEnterBtn(), OnLeaveBtn(), and SetState().
GetBitmapHeight()
int ScalableButton::GetBitmapHeight () inherited
{
#ifdef __APPLE__
    return GetBitmap().GetScaledHeight();
#else
    return GetBitmap().GetHeight();
#endif
}
Init()
void ModeButton::Init (const wxString & mode)
{
    m_tt_focused  = Slic3r::GUI::format_wxstr(_L("Switch to the %s mode"), mode);
    m_tt_selected = Slic3r::GUI::format_wxstr(_L("Current mode is %s"),    mode);
    SetBitmapMargins(3, 0);
    //button events
    Bind(wxEVT_BUTTON,          &ModeButton::OnButton, this);
    Bind(wxEVT_ENTER_WINDOW,    &ModeButton::OnEnterBtn, this);
    Bind(wxEVT_LEAVE_WINDOW,    &ModeButton::OnLeaveBtn, this);
}
References _L, Slic3r::GUI::format_wxstr(), m_tt_focused, m_tt_selected, OnButton(), OnEnterBtn(), OnLeaveBtn(), and wxEVT_BUTTON.
Referenced by ModeButton(), ModeButton(), and ModeButton().
is_selected()
bool ModeButton::is_selected () inline
{ return m_is_selected; }
References m_is_selected.
OnButton()
void ModeButton::OnButton (wxCommandEvent & event)
{
    m_is_selected = true;
    focus_button(m_is_selected);
    event.Skip();
}
References focus_button(), and m_is_selected.
Referenced by Init().
OnEnterBtn()
void ModeButton::OnEnterBtn (wxMouseEvent & event) inline
{ focus_button(true); event.Skip(); }
References focus_button().
Referenced by Init().
OnLeaveBtn()
void ModeButton::OnLeaveBtn (wxMouseEvent & event) inline
{ focus_button(m_is_selected); event.Skip(); }
References focus_button(), and m_is_selected.
Referenced by Init().
SetBitmap_() [1/2]
void ScalableButton::SetBitmap_ (const ScalableBitmap & bmp) inherited
{
    SetBitmap(bmp.bmp());
    m_current_icon_name = bmp.name();
}
References ScalableBitmap::bmp(), ScalableButton::m_current_icon_name, and ScalableBitmap::name().
Referenced by Slic3r::GUI::ObjectSettings::update_settings_list().
SetBitmap_() [2/2]
bool ScalableButton::SetBitmap_ (const std::string & bmp_name) inherited
{
    m_current_icon_name = bmp_name;
    if (m_current_icon_name.empty())
        return false;
    wxBitmapBundle bmp = *get_bmp_bundle(m_current_icon_name, m_px_cnt);
    SetBitmap(bmp);
    SetBitmapCurrent(bmp);
    SetBitmapPressed(bmp);
    SetBitmapFocus(bmp);
    SetBitmapDisabled(bmp);
    return true;
}
References get_bmp_bundle(), ScalableButton::m_current_icon_name, and ScalableButton::m_px_cnt.
SetBitmapDisabled_()
void ScalableButton::SetBitmapDisabled_ (const ScalableBitmap & bmp) inherited
{
    SetBitmapDisabled(bmp.bmp());
    m_disabled_icon_name = bmp.name();
}
References ScalableBitmap::bmp(), ScalableButton::m_disabled_icon_name, and ScalableBitmap::name().
SetState()
void ModeButton::SetState (const bool state)
{
    m_is_selected = state;
    focus_button(m_is_selected);
    SetToolTip(state ? m_tt_selected : m_tt_focused);
}
References focus_button(), m_is_selected, m_tt_focused, and m_tt_selected.
sys_color_changed()
void ModeButton::sys_color_changed () override virtual
Reimplemented from ScalableButton.
{
    Slic3r::GUI::wxGetApp().UpdateDarkUI(this, m_has_border);
    update_bitmap();
}
References ScalableButton::m_has_border, and update_bitmap().
update_bitmap()
void ModeButton::update_bitmap ()
{
    m_bmp = *get_bmp_bundle("mode", m_px_cnt, Slic3r::GUI::wxGetApp().get_mode_btn_color(m_mode_id));
    SetBitmap(m_bmp);
    SetBitmapCurrent(m_bmp);
    SetBitmapPressed(m_bmp);
}
References get_bmp_bundle(), m_bmp, m_mode_id, and ScalableButton::m_px_cnt.
Referenced by ModeButton(), and sys_color_changed().
Member Data Documentation
m_bmp
wxBitmapBundle ModeButton::m_bmp private
Referenced by update_bitmap().
m_current_icon_name
std::string ScalableButton::m_current_icon_name private inherited
Referenced by ScalableButton::SetBitmap_(), ScalableButton::SetBitmap_(), and ScalableButton::sys_color_changed().
m_disabled_icon_name
std::string ScalableButton::m_disabled_icon_name private inherited
Referenced by ScalableButton::SetBitmapDisabled_(), and ScalableButton::sys_color_changed().
m_has_border
bool ScalableButton::m_has_border {false} protected inherited
Referenced by ScalableButton::sys_color_changed(), and sys_color_changed().
m_height
int ScalableButton::m_height {-1} private inherited
Referenced by ScalableButton::ScalableButton().
m_is_selected
bool ModeButton::m_is_selected {false} private
Referenced by is_selected(), OnButton(), OnLeaveBtn(), and SetState().
m_mode_id
int ModeButton::m_mode_id {-1} private
Referenced by update_bitmap().
m_parent
wxWindow* ScalableButton::m_parent { nullptr } private inherited
Referenced by ScalableButton::sys_color_changed().
m_px_cnt
int ScalableButton::m_px_cnt { 16 } protected inherited
Referenced by ScalableButton::ScalableButton(), ScalableButton::SetBitmap_(), ScalableButton::sys_color_changed(), and update_bitmap().
m_tt_focused
wxString ModeButton::m_tt_focused private
Referenced by Init(), and SetState().
m_tt_selected
wxString ModeButton::m_tt_selected private
Referenced by Init(), and SetState().
m_width
int ScalableButton::m_width {-1} private inherited
Referenced by ScalableButton::ScalableButton().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp