Prusa Slicer: src/avrdude/crc16.c File Reference
crc16.c File Reference
#include "crc16.h"
Macros
#define CRC_INIT 0xFFFF
#define CRC(crcval, newchar)
Functions
unsigned short crcsum (const unsigned char *message, unsigned long length, unsigned short crc)
int crcverify (const unsigned char *message, unsigned long length)
void crcappend (unsigned char *message, unsigned long length)
Variables
static const unsigned short crc_table [256]
Macro Definition Documentation
CRC
#define CRC (crcval, newchar)
Value:
  crcval = (crcval >> 8) ^ \
  crc_table[(crcval ^ newchar) & 0x00ff]
CRC_INIT
#define CRC_INIT 0xFFFF
Function Documentation
crcappend()
void crcappend (unsigned char * message, unsigned long length)
{
  unsigned long crc;
  crc = crcsum(message, length, CRC_INIT);
  message[length] = (unsigned char)(crc & 0xff);
  message[length+1] = (unsigned char)((crc >> 8) & 0xff);
}
References CRC_INIT, and crcsum().
Referenced by jtagmkII_send().
crcsum()
unsigned short crcsum (const unsigned char * message, unsigned long length, unsigned short crc)
{
  unsigned long i;
  for(i = 0; i < length; i++)
    {
      CRC(crc, message[i]);
    }
  return crc;
}
References CRC.
Referenced by crcappend(), and crcverify().
crcverify()
int crcverify (const unsigned char * message, unsigned long length)
{
  /*
   * Returns true if the last two bytes in a message is the crc of the
   * preceding bytes.
   */
  unsigned short expected;
  expected = crcsum(message, length - 2, CRC_INIT);
  return (expected & 0xff) == message[length - 2] &&
    ((expected >> 8) & 0xff) == message[length - 1];
}
References CRC_INIT, and crcsum().
Referenced by jtagmkII_recv_frame().
Variable Documentation
crc_table
const unsigned short crc_table[256] static