Prusa Slicer: src/avrdude/pgm.c File Reference
pgm.c File Reference
#include "ac_cfg.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "avrdude.h"
#include "libavrdude.h"
Functions
static int pgm_default_2 (struct programmer_t *, AVRPART *)
static int pgm_default_3 (struct programmer_t *pgm, AVRPART *p, AVRMEM *mem, unsigned long addr, unsigned char *value)
static void pgm_default_4 (struct programmer_t *)
static int pgm_default_5 (struct programmer_t *pgm, AVRPART *p, AVRMEM *mem, unsigned long addr, unsigned char data)
static void pgm_default_6 (struct programmer_t *, const char *)
static int pgm_default_open (struct programmer_t *pgm, char *name)
static int pgm_default_led (struct programmer_t *pgm, int value)
static void pgm_default_powerup_powerdown (struct programmer_t *pgm)
PROGRAMMER * pgm_new (void)
void pgm_free (PROGRAMMER *const p)
PROGRAMMER * pgm_dup (const PROGRAMMER *const src)
static void pgm_default (void)
void programmer_display (PROGRAMMER *pgm, const char *p)
void pgm_display_generic_mask (PROGRAMMER *pgm, const char *p, unsigned int show)
void pgm_display_generic (PROGRAMMER *pgm, const char *p)
PROGRAMMER * locate_programmer (LISTID programmers, const char *configid)
void walk_programmers (LISTID programmers, walk_programmers_cb cb, void *cookie)
static int sort_programmer_compare (PROGRAMMER *p1, PROGRAMMER *p2)
void sort_programmers (LISTID programmers)
Function Documentation
locate_programmer()
PROGRAMMER * locate_programmer (LISTID programmers, const char * configid)
{
  LNODEID ln1, ln2;
  PROGRAMMER * p = NULL;
  const char * id;
  int found;
  found = 0;
  for (ln1=lfirst(programmers); ln1 && !found; ln1=lnext(ln1)) {
    p = ldata(ln1);
    for (ln2=lfirst(p->id); ln2 && !found; ln2=lnext(ln2)) {
      id = ldata(ln2);
      if (strcasecmp(configid, id) == 0)
        found = 1;
    }
  }
  if (found)
    return p;
  return NULL;
}
References programmer_t::id, ldata(), lfirst(), lnext(), programmers, and strcasecmp.
Referenced by avrdude_main(), and yyparse().
pgm_default()
static void pgm_default (void) static
{
  avrdude_message(MSG_INFO, "%s: programmer operation not supported\n", progname);
}
References avrdude_message(), MSG_INFO, and progname.
Referenced by pgm_default_2(), pgm_default_3(), pgm_default_4(), pgm_default_5(), and pgm_default_6().
pgm_default_2()
static int pgm_default_2 (struct programmer_t * pgm, AVRPART * p) static
{
  pgm_default();
  return -1;
}
References pgm_default().
Referenced by pgm_new().
pgm_default_3()
static int pgm_default_3 (struct programmer_t * pgm, AVRPART * p, AVRMEM * mem, unsigned long addr, unsigned char * value) static
{
  pgm_default();
  return -1;
}
References pgm_default().
Referenced by pgm_new().
pgm_default_4()
static void pgm_default_4 (struct programmer_t * pgm) static
{
  pgm_default();
}
References pgm_default().
Referenced by pgm_new().
pgm_default_5()
static int pgm_default_5 (struct programmer_t * pgm, AVRPART * p, AVRMEM * mem, unsigned long addr, unsigned char data) static
{
  pgm_default();
  return -1;
}
References pgm_default().
Referenced by pgm_new().
pgm_default_6()
static void pgm_default_6 (struct programmer_t * pgm, const char * p) static
{
  pgm_default();
}
References pgm_default().
Referenced by pgm_new().
pgm_default_led()
static int pgm_default_led (struct programmer_t * pgm, int value) static
{
  /*
   * If programmer has no LEDs, just do nothing.
   */
  return 0;
}
Referenced by pgm_new().
pgm_default_open()
static int pgm_default_open (struct programmer_t * pgm, char * name) static
{
  avrdude_message(MSG_INFO, "\n%s: Fatal error: Programmer does not support open()",
               progname);
  return -1;
}
References avrdude_message(), MSG_INFO, and progname.
Referenced by pgm_new().
pgm_default_powerup_powerdown()
static void pgm_default_powerup_powerdown (struct programmer_t * pgm) static
{
  /*
   * If programmer does not support powerup/down, just do nothing.
   */
}
Referenced by pgm_new().
pgm_display_generic()
void pgm_display_generic (PROGRAMMER * pgm, const char * p)
{
  pgm_display_generic_mask(pgm, p, SHOW_ALL_PINS);
}
References pgm, pgm_display_generic_mask(), and SHOW_ALL_PINS.
pgm_display_generic_mask()
void pgm_display_generic_mask (PROGRAMMER * pgm, const char * p, unsigned int show)
{
  if(show & (1<<PPI_AVR_VCC))
    avrdude_message(MSG_INFO, "%s  VCC     = %s\n", p, pins_to_str(&pgm->pin[PPI_AVR_VCC]));
  if(show & (1<<PPI_AVR_BUFF))
    avrdude_message(MSG_INFO, "%s  BUFF    = %s\n", p, pins_to_str(&pgm->pin[PPI_AVR_BUFF]));
  if(show & (1<<PIN_AVR_RESET))
    avrdude_message(MSG_INFO, "%s  RESET   = %s\n", p, pins_to_str(&pgm->pin[PIN_AVR_RESET]));
  if(show & (1<<PIN_AVR_SCK))
    avrdude_message(MSG_INFO, "%s  SCK     = %s\n", p, pins_to_str(&pgm->pin[PIN_AVR_SCK]));
  if(show & (1<<PIN_AVR_MOSI))
    avrdude_message(MSG_INFO, "%s  MOSI    = %s\n", p, pins_to_str(&pgm->pin[PIN_AVR_MOSI]));
  if(show & (1<<PIN_AVR_MISO))
    avrdude_message(MSG_INFO, "%s  MISO    = %s\n", p, pins_to_str(&pgm->pin[PIN_AVR_MISO]));
  if(show & (1<<PIN_LED_ERR))
    avrdude_message(MSG_INFO, "%s  ERR LED = %s\n", p, pins_to_str(&pgm->pin[PIN_LED_ERR]));
  if(show & (1<<PIN_LED_RDY))
    avrdude_message(MSG_INFO, "%s  RDY LED = %s\n", p, pins_to_str(&pgm->pin[PIN_LED_RDY]));
  if(show & (1<<PIN_LED_PGM))
    avrdude_message(MSG_INFO, "%s  PGM LED = %s\n", p, pins_to_str(&pgm->pin[PIN_LED_PGM]));
  if(show & (1<<PIN_LED_VFY))
    avrdude_message(MSG_INFO, "%s  VFY LED = %s\n", p, pins_to_str(&pgm->pin[PIN_LED_VFY]));
}
References avrdude_message(), MSG_INFO, pgm, programmer_t::pin, PIN_AVR_MISO, PIN_AVR_MOSI, PIN_AVR_RESET, PIN_AVR_SCK, PIN_LED_ERR, PIN_LED_PGM, PIN_LED_RDY, PIN_LED_VFY, pins_to_str(), PPI_AVR_BUFF, and PPI_AVR_VCC.
Referenced by pgm_display_generic().
pgm_dup()
PROGRAMMER * pgm_dup (const PROGRAMMER *const src)
{
  PROGRAMMER * pgm;
  LNODEID ln;
  pgm = (PROGRAMMER *)malloc(sizeof(*pgm));
  if (pgm == NULL) {
    avrdude_message(MSG_INFO, "%s: out of memory allocating programmer structure\n",
            progname);
    return NULL;
  }
  memcpy(pgm, src, sizeof(*pgm));
  pgm->id = lcreat(NULL, 0);
  pgm->usbpid = lcreat(NULL, 0);
  for (ln = lfirst(src->usbpid); ln; ln = lnext(ln)) {
    int *ip = malloc(sizeof(int));
    if (ip == NULL) {
      // avrdude_message(MSG_INFO, "%s: out of memory allocating programmer structure\n",
      //         progname);
      // exit(1);
      avrdude_oom("out of memory allocating programmer structure\n");
    }
    *ip = *(int *) ldata(ln);
    ladd(pgm->usbpid, ip);
  }
  return pgm;
}
References avrdude_message(), avrdude_oom(), programmer_t::id, ladd(), lcreat(), ldata(), lfirst(), lnext(), malloc(), MSG_INFO, pgm, progname, and programmer_t::usbpid.
Referenced by yyparse().
pgm_free()
void pgm_free (PROGRAMMER *const p)
{
  ldestroy_cb(p->id, free);
  ldestroy_cb(p->usbpid, free);
  p->id = NULL;
  p->usbpid = NULL;
  /* this is done by pgm_teardown, but usually cookie is not set to NULL */
  /* if (p->cookie !=NULL) {
    free(p->cookie);
    p->cookie = NULL;
  }*/
  free(p);
}
References free(), programmer_t::id, ldestroy_cb(), and programmer_t::usbpid.
Referenced by cleanup_config(), and yyparse().
pgm_new()
PROGRAMMER * pgm_new (void)
{
  int i;
  PROGRAMMER * pgm;
  pgm = (PROGRAMMER *)malloc(sizeof(*pgm));
  if (pgm == NULL) {
    avrdude_message(MSG_INFO, "%s: out of memory allocating programmer structure\n",
            progname);
    return NULL;
  }
  memset(pgm, 0, sizeof(*pgm));
  pgm->id = lcreat(NULL, 0);
  pgm->usbpid = lcreat(NULL, 0);
  pgm->desc[0] = 0;
  pgm->type[0] = 0;
  pgm->config_file[0] = 0;
  pgm->lineno = 0;
  pgm->baudrate = 0;
  pgm->initpgm = NULL;
  for (i=0; i<N_PINS; i++) {
    pgm->pinno[i] = 0;
    pin_clear_all(&(pgm->pin[i]));
  }
  /*
   * mandatory functions - these are called without checking to see
   * whether they are assigned or not
   */
  pgm->initialize     = pgm_default_2;
  pgm->display        = pgm_default_6;
  pgm->enable         = pgm_default_4;
  pgm->disable        = pgm_default_4;
  pgm->powerup        = pgm_default_powerup_powerdown;
  pgm->powerdown      = pgm_default_powerup_powerdown;
  pgm->program_enable = pgm_default_2;
  pgm->chip_erase     = pgm_default_2;
  pgm->open           = pgm_default_open;
  pgm->close          = pgm_default_4;
  pgm->read_byte      = pgm_default_3;
  pgm->write_byte     = pgm_default_5;
  /*
   * predefined functions - these functions have a valid default
   * implementation. Hence, they don't need to be defined in
   * the programmer.
   */
  pgm->rdy_led        = pgm_default_led;
  pgm->err_led        = pgm_default_led;
  pgm->pgm_led        = pgm_default_led;
  pgm->vfy_led        = pgm_default_led;
  /*
   * optional functions - these are checked to make sure they are
   * assigned before they are called
   */
  pgm->cmd            = NULL;
  pgm->cmd_tpi        = NULL;
  pgm->spi            = NULL;
  pgm->paged_write    = NULL;
  pgm->paged_load     = NULL;
  pgm->write_setup    = NULL;
  pgm->read_sig_bytes = NULL;
  pgm->set_vtarget    = NULL;
  pgm->set_varef      = NULL;
  pgm->set_fosc       = NULL;
  pgm->perform_osccal = NULL;
  pgm->parseextparams = NULL;
  pgm->setup          = NULL;
  pgm->teardown       = NULL;
  return pgm;
}
References avrdude_message(), programmer_t::baudrate, programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::cmd_tpi, programmer_t::config_file, programmer_t::desc, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::err_led, programmer_t::id, programmer_t::initialize, programmer_t::initpgm, lcreat(), programmer_t::lineno, malloc(), MSG_INFO, N_PINS, programmer_t::open, programmer_t::paged_load, programmer_t::paged_write, programmer_t::parseextparams, programmer_t::perform_osccal, pgm, pgm_default_2(), pgm_default_3(), pgm_default_4(), pgm_default_5(), pgm_default_6(), pgm_default_led(), pgm_default_open(), pgm_default_powerup_powerdown(), programmer_t::pgm_led, programmer_t::pin, pin_clear_all(), programmer_t::pinno, programmer_t::powerdown, programmer_t::powerup, progname, programmer_t::program_enable, programmer_t::rdy_led, programmer_t::read_byte, programmer_t::read_sig_bytes, programmer_t::set_fosc, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, programmer_t::spi, programmer_t::teardown, programmer_t::type, programmer_t::usbpid, programmer_t::vfy_led, programmer_t::write_byte, and programmer_t::write_setup.
Referenced by yyparse().
programmer_display()
void programmer_display (PROGRAMMER * pgm, const char * p)
{
  avrdude_message(MSG_INFO, "%sProgrammer Type : %s\n", p, pgm->type);
  avrdude_message(MSG_INFO, "%sDescription     : %s\n", p, pgm->desc);
  pgm->display(pgm, p);
}
References avrdude_message(), programmer_t::desc, programmer_t::display, MSG_INFO, pgm, and programmer_t::type.
Referenced by avrdude_main().
sort_programmer_compare()
static int sort_programmer_compare (PROGRAMMER * p1, PROGRAMMER * p2) static
{
  char* id1;
  char* id2;
  if(p1 == NULL || p2 == NULL) {
    return 0;
  }
  id1 = ldata(lfirst(p1->id));
  id2 = ldata(lfirst(p2->id));
  return strncasecmp(id1,id2,AVR_IDLEN);
}
References AVR_IDLEN, programmer_t::id, ldata(), lfirst(), and strncasecmp.
Referenced by sort_programmers().
sort_programmers()
void sort_programmers (LISTID programmers)
{
  lsort(programmers,(int (*)(void*, void*)) sort_programmer_compare);
}
References lsort(), programmers, and sort_programmer_compare().
Referenced by list_programmers().
walk_programmers()
void walk_programmers (LISTID programmers, walk_programmers_cb cb, void * cookie)
{
  LNODEID ln1;
  LNODEID ln2;
  PROGRAMMER * p;
  for (ln1 = lfirst(programmers); ln1; ln1 = lnext(ln1)) {
    p = ldata(ln1);
    for (ln2=lfirst(p->id); ln2; ln2=lnext(ln2)) {
      cb(ldata(ln2), p->desc, p->config_file, p->lineno, cookie);
    }
  }
}
References programmer_t::config_file, programmer_t::desc, programmer_t::id, ldata(), lfirst(), programmer_t::lineno, lnext(), and programmers.
Referenced by list_programmers().