Prusa Slicer: Slic3r::BoundingBox Class Reference
Slic3r::BoundingBox Class Reference
#include <src/libslic3r/BoundingBox.hpp>
Public Types
using PointsType = Points
Public Member Functions
void polygon (Polygon *polygon) const
Polygon polygon () const
BoundingBox rotated (double angle) const
BoundingBox rotated (double angle, const Point &center) const
void rotate (double angle)
void rotate (double angle, const Point &center)
void align_to_grid (const coord_t cell_size)
BoundingBox ()
BoundingBox (const Point &pmin, const Point &pmax)
BoundingBox (const Points &points)
BoundingBox inflated (coordf_t delta) const throw ()
void reset ()
void merge (const Point &point)
void merge (const PointsType &points)
void merge (const BoundingBoxBase< Point, PointsType > &bb)
void scale (double factor)
Point size () const
double radius () const
void translate (coordf_t x, coordf_t y)
void translate (const Point &v)
void offset (coordf_t delta)
Point center () const
bool contains (const Point &point) const
bool contains (const BoundingBoxBase< Point, PointsType > &other) const
bool overlap (const BoundingBoxBase< Point, PointsType > &other) const
bool operator== (const BoundingBoxBase< Point, PointsType > &rhs)
bool operator!= (const BoundingBoxBase< Point, PointsType > &rhs)
Public Attributes
Point min
Point max
bool defined
Static Private Member Functions
static void construct (BoundingBoxType &out, It from, It to)
Friends
BoundingBox get_extents_rotated (const Points &points, double angle)
Detailed Description
Member Typedef Documentation
PointsType
using Slic3r::BoundingBoxBase< Point , Points >::PointsType = Points inherited
Constructor & Destructor Documentation
BoundingBox() [1/3]
Slic3r::BoundingBox::BoundingBox () inline
: BoundingBoxBase<Point, Points>() {}
BoundingBox() [2/3]
Slic3r::BoundingBox::BoundingBox (const Point & pmin, const Point & pmax) inline
: BoundingBoxBase<Point, Points>(pmin, pmax) {}
BoundingBox() [3/3]
Slic3r::BoundingBox::BoundingBox (const Points & points) inline
: BoundingBoxBase<Point, Points>(points) {}
Member Function Documentation
align_to_grid()
void Slic3r::BoundingBox::align_to_grid (const coord_t cell_size)
{
    if (this->defined) {
        min.x() = Slic3r::align_to_grid(min.x(), cell_size);
        min.y() = Slic3r::align_to_grid(min.y(), cell_size);
    }
}
References Slic3r::align_to_grid(), Slic3r::BoundingBoxBase< Point, Points >::defined, and Slic3r::BoundingBoxBase< Point, Points >::min.
Referenced by Slic3r::SupportGridPattern::SupportGridPattern().
center()
template Vec2d Slic3r::BoundingBoxBase< Point , Points >::center inherited
{
    return (this->min + this->max) / 2;
}
construct()
static void Slic3r::BoundingBoxBase< Point , Points >::construct (BoundingBoxType & out, It from, It to) inline static private inherited
    {
        if (from != to) {
            auto it = from;
            out.min = it->template cast<typename PointType::Scalar>();
            out.max = out.min;
            for (++ it; it != to; ++ it) {
                auto vec = it->template cast<typename PointType::Scalar>();
                out.min = out.min.cwiseMin(vec);
                out.max = out.max.cwiseMax(vec);
            }
            out.defined = IncludeBoundary || (out.min.x() < out.max.x() && out.min.y() < out.max.y());
        }
    }
contains() [1/2]
bool Slic3r::BoundingBoxBase< Point , Points >::contains (const BoundingBoxBase< Point , PointsType > & other) const inline inherited
{
        return contains(other.min) && contains(other.max);
    }
contains() [2/2]
bool Slic3r::BoundingBoxBase< Point , Points >::contains (const Point & point) const inline inherited
{
        return point.x() >= this->min.x() && point.x() <= this->max.x()
            && point.y() >= this->min.y() && point.y() <= this->max.y();
    }
inflated()
BoundingBox Slic3r::BoundingBox::inflated (coordf_t delta) const throw () inline
{ BoundingBox out(*this); out.offset(delta); return out; }
References Slic3r::BoundingBoxBase< PointType, APointsType >::offset().
Referenced by Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::connect_brim_lines(), Slic3r::create_boundary_infill_graph(), Slic3r::generate_extra_perimeters_over_overhangs(), Slic3r::FFFTreeSupport::generate_support_infill_lines(), Slic3r::FillLightning::Generator::generateTrees(), Slic3r::mark_boundary_segments_touching_infill(), and Slic3r::FFFTreeSupport::safe_offset_inc().
merge() [1/3]
void Slic3r::BoundingBoxBase< Point , Points >::merge (const BoundingBoxBase< Point , PointsType > & bb) inherited
{
    assert(bb.defined || bb.min.x() >= bb.max.x() || bb.min.y() >= bb.max.y());
    if (bb.defined) {
        if (this->defined) {
            this->min = this->min.cwiseMin(bb.min);
            this->max = this->max.cwiseMax(bb.max);
        } else {
            this->min = bb.min;
            this->max = bb.max;
            this->defined = true;
        }
    }
}
merge() [2/3]
void Slic3r::BoundingBoxBase< Point , Points >::merge (const Point & point) inherited
{
    if (this->defined) {
        this->min = this->min.cwiseMin(point);
        this->max = this->max.cwiseMax(point);
    } else {
        this->min = point;
        this->max = point;
        this->defined = true;
    }
}
merge() [3/3]
void Slic3r::BoundingBoxBase< Point , Points >::merge (const PointsType & points) inherited
{
    this->merge(BoundingBoxBase(points));
}
offset()
template void Slic3r::BoundingBoxBase< Point , Points >::offset (coordf_t delta) inherited
{
    PointType v(delta, delta);
    this->min -= v;
    this->max += v;
}
operator!=()
bool Slic3r::BoundingBoxBase< Point , Points >::operator!= (const BoundingBoxBase< Point , PointsType > & rhs) inline inherited
{ return ! (*this == rhs); }
operator==()
bool Slic3r::BoundingBoxBase< Point , Points >::operator== (const BoundingBoxBase< Point , PointsType > & rhs) inline inherited
{ return this->min == rhs.min && this->max == rhs.max; }
overlap()
bool Slic3r::BoundingBoxBase< Point , Points >::overlap (const BoundingBoxBase< Point , PointsType > & other) const inline inherited
{
        return ! (this->max.x() < other.min.x() || this->min.x() > other.max.x() ||
                  this->max.y() < other.min.y() || this->min.y() > other.max.y());
    }
polygon() [1/2]
Polygon Slic3r::BoundingBox::polygon () const
{
    Polygon p;
    this->polygon(&p);
    return p;
}
References polygon().
Referenced by polygon(), and polygon().
polygon() [2/2]
void Slic3r::BoundingBox::polygon (Polygon * polygon) const
{
    polygon->points = {
        this->min,
        { this->max.x(), this->min.y() },
        this->max,
        { this->min.x(), this->max.y() }
    };
}
References Slic3r::BoundingBoxBase< Point, Points >::max, Slic3r::BoundingBoxBase< Point, Points >::min, Slic3r::MultiPoint::points, and polygon().
Referenced by Slic3r::FillHoneycomb::_fill_surface_single().
radius()
template double Slic3r::BoundingBoxBase< Point , Points >::radius inherited
{
    assert(this->defined);
    return 0.5 * (this->max - this->min).template cast<double>().norm();
}
reset()
void Slic3r::BoundingBoxBase< Point , Points >::reset () inline inherited
{ this->defined = false; this->min = PointType::Zero(); this->max = PointType::Zero(); }
rotate() [1/2]
void Slic3r::BoundingBox::rotate (double angle) inline
{ (*this) = this->rotated(angle); }
References Slic3r::angle().
rotate() [2/2]
void Slic3r::BoundingBox::rotate (double angle, const Point & center) inline
{ (*this) = this->rotated(angle, center); }
References Slic3r::angle().
rotated() [1/2]
BoundingBox Slic3r::BoundingBox::rotated (double angle) const
{
    BoundingBox out;
    out.merge(this->min.rotated(angle));
    out.merge(this->max.rotated(angle));
    out.merge(Point(this->min.x(), this->max.y()).rotated(angle));
    out.merge(Point(this->max.x(), this->min.y()).rotated(angle));
    return out;
}
References Slic3r::BoundingBoxBase< PointType, APointsType >::merge(), Slic3r::BoundingBoxBase< Point, Points >::min, and Slic3r::Point::rotated().
Referenced by Slic3r::FillPlanePath::_fill_surface_single().
rotated() [2/2]
BoundingBox Slic3r::BoundingBox::rotated (double angle, const Point & center) const
{
    BoundingBox out;
    out.merge(this->min.rotated(angle, center));
    out.merge(this->max.rotated(angle, center));
    out.merge(Point(this->min.x(), this->max.y()).rotated(angle, center));
    out.merge(Point(this->max.x(), this->min.y()).rotated(angle, center));
    return out;
}
scale()
template void Slic3r::BoundingBoxBase< Point , Points >::scale (double factor) inherited
{
    this->min *= factor;
    this->max *= factor;
}
size()
template Vec2d Slic3r::BoundingBoxBase< Point , Points >::size inherited
{
    return this->max - this->min;
}
translate() [1/2]
void Slic3r::BoundingBoxBase< Point , Points >::translate (const Point & v) inline inherited
{ this->min += v; this->max += v; }
translate() [2/2]
void Slic3r::BoundingBoxBase< Point , Points >::translate (coordf_t x, coordf_t y) inline inherited
{ assert(this->defined); PointType v(x, y); this->min += v; this->max += v; }
Friends And Related Symbol Documentation
get_extents_rotated
BoundingBox get_extents_rotated (const Points & points, double angle) friend
{
    BoundingBox bbox;
    if (! points.empty()) {
        double s = sin(angle);
        double c = cos(angle);
        Points::const_iterator it = points.begin();
        double cur_x = (double)(*it)(0);
        double cur_y = (double)(*it)(1);
        bbox.min(0) = bbox.max(0) = (coord_t)round(c * cur_x - s * cur_y);
        bbox.min(1) = bbox.max(1) = (coord_t)round(c * cur_y + s * cur_x);
        for (++it; it != points.end(); ++it) {
            double cur_x = (double)(*it)(0);
            double cur_y = (double)(*it)(1);
            coord_t x = (coord_t)round(c * cur_x - s * cur_y);
            coord_t y = (coord_t)round(c * cur_y + s * cur_x);
            bbox.min(0) = std::min(x, bbox.min(0));
            bbox.min(1) = std::min(y, bbox.min(1));
            bbox.max(0) = std::max(x, bbox.max(0));
            bbox.max(1) = std::max(y, bbox.max(1));
        }
        bbox.defined = true;
    }
    return bbox;
}
Member Data Documentation
defined
bool Slic3r::BoundingBoxBase< Point , Points >::defined inherited
max
Point Slic3r::BoundingBoxBase< Point , Points >::max inherited
min
Point Slic3r::BoundingBoxBase< Point , Points >::min inherited
The documentation for this class was generated from the following files:
src/libslic3r/BoundingBox.hpp
src/libslic3r/BoundingBox.cpp