Prusa Slicer: Slic3r::GUI::CommonGizmosDataObjects::Raycaster Class Reference
Slic3r::GUI::CommonGizmosDataObjects::Raycaster Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
Raycaster (CommonGizmosDataPool *cgdp)
CommonGizmosDataID get_dependencies () const override
const MeshRaycaster * raycaster () const
std::vector< const MeshRaycaster * > raycasters () const
void update ()
void release ()
bool is_valid () const
Protected Member Functions
void on_update () override
void on_release () override
CommonGizmosDataPool * get_pool () const
Private Attributes
std::vector< std::unique_ptr< MeshRaycaster > > m_raycasters
std::vector< const TriangleMesh * > m_old_meshes
TriangleMesh m_sla_mesh_cache
bool m_is_valid = false
CommonGizmosDataPool * m_common = nullptr
Detailed Description
Constructor & Destructor Documentation
Raycaster()
Slic3r::GUI::CommonGizmosDataObjects::Raycaster::Raycaster (CommonGizmosDataPool * cgdp) inline explicit
        : CommonGizmosDataBase(cgdp) {}
Member Function Documentation
get_dependencies()
CommonGizmosDataID Slic3r::GUI::CommonGizmosDataObjects::Raycaster::get_dependencies () const inline override virtual
Reimplemented from Slic3r::GUI::CommonGizmosDataBase.
{ return CommonGizmosDataID::SelectionInfo; }
References Slic3r::GUI::SelectionInfo.
get_pool()
CommonGizmosDataPool * Slic3r::GUI::CommonGizmosDataBase::get_pool () const inline protected inherited
{ return m_common; }
References Slic3r::GUI::CommonGizmosDataBase::m_common.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_release(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), on_update(), and Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut().
is_valid()
bool Slic3r::GUI::CommonGizmosDataBase::is_valid () const inline inherited
{ return m_is_valid; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid.
Referenced by Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::GUI::CommonGizmosDataPool::supports_clipper().
on_release()
void Slic3r::GUI::Raycaster::on_release () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    m_raycasters.clear();
    m_old_meshes.clear();
}
References m_old_meshes, and m_raycasters.
on_update()
void Slic3r::GUI::Raycaster::on_update () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    wxBusyCursor wait;
    const ModelObject* mo = get_pool()->selection_info()->model_object();
    const ModelVolume* mv = get_pool()->selection_info()->model_volume();
    if (mo == nullptr && mv == nullptr)
        return;
    std::vector<ModelVolume*> mvs;
    if (mv != nullptr)
        mvs.push_back(const_cast<ModelVolume*>(mv));
    else
        mvs = mo->volumes;
    std::vector<const TriangleMesh*> meshes;
    bool force_raycaster_regeneration = false;
    if (wxGetApp().preset_bundle->printers.get_selected_preset().printer_technology() == ptSLA) {
        // For sla printers we use the mesh generated by the backend
        std::shared_ptr<const indexed_triangle_set> preview_mesh_ptr;
        const SLAPrintObject* po = get_pool()->selection_info()->print_object();
        if (po != nullptr)
            preview_mesh_ptr = po->get_mesh_to_print();
        else
            preview_mesh_ptr.reset();
        m_sla_mesh_cache = (preview_mesh_ptr != nullptr) ? TriangleMesh{ *preview_mesh_ptr } : TriangleMesh();
        if (!m_sla_mesh_cache.empty()) {
            m_sla_mesh_cache.transform(po->trafo().inverse());
            meshes.emplace_back(&m_sla_mesh_cache);
            force_raycaster_regeneration = true;
        }
    }
    if (meshes.empty()) {
        const std::vector<ModelVolume*>& mvs = mo->volumes;
        for (const ModelVolume* mv : mvs) {
            if (mv->is_model_part())
                meshes.push_back(&mv->mesh());
        }
    }
    if (force_raycaster_regeneration || meshes != m_old_meshes) {
        m_raycasters.clear();
        for (const TriangleMesh* mesh : meshes)
            m_raycasters.emplace_back(new MeshRaycaster(std::make_shared<const TriangleMesh>(*mesh)));
        m_old_meshes = meshes;
    }
}
References Slic3r::TriangleMesh::empty(), Slic3r::SLAPrintObject::get_mesh_to_print(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::ModelVolume::is_model_part(), m_old_meshes, m_raycasters, m_sla_mesh_cache, Slic3r::ModelVolume::mesh(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_volume(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), Slic3r::ptSLA, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::SLAPrintObject::trafo(), Slic3r::TriangleMesh::transform(), and Slic3r::ModelObject::volumes.
raycaster()
const MeshRaycaster * Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycaster () const inline
{ assert(m_raycasters.size() == 1); return m_raycasters.front().get(); }
References m_raycasters.
Referenced by Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), and Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform().
raycasters()
std::vector< const MeshRaycaster * > Slic3r::GUI::Raycaster::raycasters () const
{
    std::vector<const MeshRaycaster*> mrcs;
    for (const auto& raycaster_unique_ptr : m_raycasters)
        mrcs.push_back(raycaster_unique_ptr.get());
    return mrcs;
}
References m_raycasters.
Referenced by Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), and Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache().
release()
void Slic3r::GUI::CommonGizmosDataBase::release () inline inherited
{ on_release(); m_is_valid = false; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_release().
update()
void Slic3r::GUI::CommonGizmosDataBase::update () inline inherited
{ on_update(); m_is_valid = true; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_update().
Member Data Documentation
m_common
CommonGizmosDataPool* Slic3r::GUI::CommonGizmosDataBase::m_common = nullptr private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::get_pool().
m_is_valid
bool Slic3r::GUI::CommonGizmosDataBase::m_is_valid = false private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::is_valid(), Slic3r::GUI::CommonGizmosDataBase::release(), and Slic3r::GUI::CommonGizmosDataBase::update().
m_old_meshes
std::vector<const TriangleMesh*> Slic3r::GUI::CommonGizmosDataObjects::Raycaster::m_old_meshes private
Referenced by on_release(), and on_update().
m_raycasters
std::vector<std::unique_ptr<MeshRaycaster> > Slic3r::GUI::CommonGizmosDataObjects::Raycaster::m_raycasters private
Referenced by on_release(), on_update(), raycaster(), and raycasters().
m_sla_mesh_cache
TriangleMesh Slic3r::GUI::CommonGizmosDataObjects::Raycaster::m_sla_mesh_cache private
Referenced by on_update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp
src/slic3r/GUI/Gizmos/GLGizmosCommon.cpp