Prusa Slicer: igl::geodesic::SortedSources Class Reference
igl::geodesic::SortedSources Class Reference
Public Types
typedef sorted_vector_type::iterator sorted_iterator
typedef std::pair< sorted_iterator, sorted_iterator > sorted_iterator_pair
Public Member Functions
sorted_iterator_pair sources (base_pointer mesh_element)
void initialize (std::vector< SurfacePoint > &sources)
SurfacePointWithIndex & operator[] (unsigned i)
Public Attributes
T elements
STL member.
Private Types
typedef std::vector< SurfacePointWithIndex * > sorted_vector_type
Private Attributes
sorted_vector_type m_sorted
SurfacePointWithIndex m_search_dummy
SurfacePointWithIndex m_compare_less
Detailed Description
Member Typedef Documentation
sorted_iterator
typedef sorted_vector_type::iterator igl::geodesic::SortedSources::sorted_iterator
sorted_iterator_pair
typedef std::pair<sorted_iterator, sorted_iterator> igl::geodesic::SortedSources::sorted_iterator_pair
sorted_vector_type
typedef std::vector<SurfacePointWithIndex*> igl::geodesic::SortedSources::sorted_vector_type private
Member Function Documentation
initialize()
void igl::geodesic::SortedSources::initialize (std::vector< SurfacePoint > & sources) inline
  {
    resize(sources.size());
    m_sorted.resize(sources.size());
    for(unsigned i=0; i<sources.size(); ++i)
    {
      SurfacePointWithIndex& p = *(begin() + i);
      p.initialize(sources[i],i);
      m_sorted[i] = &p;
    }
    std::sort(m_sorted.begin(), m_sorted.end(), m_compare_less);
  };
References igl::geodesic::SurfacePointWithIndex::initialize(), m_compare_less, m_sorted, and sources().
Referenced by igl::geodesic::GeodesicAlgorithmExact::set_sources().
operator[]()
SurfacePointWithIndex & igl::geodesic::SortedSources::operator[] (unsigned i) inline
  {
    assert(i < size());
    return *(begin() + i);
  }
sources()
sorted_iterator_pair igl::geodesic::SortedSources::sources (base_pointer mesh_element) inline
  {
    m_search_dummy.base_element() = mesh_element;
    return equal_range(m_sorted.begin(),
               m_sorted.end(),
               &m_search_dummy,
               m_compare_less);
  }
References igl::geodesic::SurfacePoint::base_element(), m_compare_less, m_search_dummy, and m_sorted.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), and initialize().
Member Data Documentation
elements
T std::vector< T >::elements inherited
STL member.
m_compare_less
SurfacePointWithIndex igl::geodesic::SortedSources::m_compare_less private
Referenced by initialize(), and sources().
m_search_dummy
SurfacePointWithIndex igl::geodesic::SortedSources::m_search_dummy private
Referenced by sources().
m_sorted
sorted_vector_type igl::geodesic::SortedSources::m_sorted private
Referenced by initialize(), and sources().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp