Prusa Slicer: Slic3r::OctoPrint Class Reference
Slic3r::OctoPrint Class Reference
#include <src/slic3r/Utils/OctoPrint.hpp>
Public Types
typedef Http::ProgressFn ProgressFn
typedef std::function< void(wxString)> ErrorFn
typedef std::function< void(wxString, wxString)> InfoFn
Public Member Functions
OctoPrint (DynamicPrintConfig *config)
~OctoPrint () override=default
const char * get_name () const override
virtual bool test (wxString &curl_msg) const override
wxString get_test_ok_msg () const override
wxString get_test_failed_msg (wxString &msg) const override
bool upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const override
bool has_auto_discovery () const override
bool can_test () const override
PrintHostPostUploadActions get_post_upload_actions () const override
std::string get_host () const override
const std::string & get_apikey () const
const std::string & get_cafile () const
virtual bool supports_multiple_printers () const
virtual bool get_groups (wxArrayString &) const
virtual bool get_printers (wxArrayString &) const
virtual bool get_storage (wxArrayString &, wxArrayString &) const
Static Public Member Functions
static PrintHost * get_print_host (DynamicPrintConfig *config)
Protected Member Functions
virtual bool validate_version_text (const boost::optional< std::string > &version_text) const
virtual bool upload_inner_with_host (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const
virtual void set_auth (Http &http) const
std::string make_url (const std::string &path) const
virtual wxString format_error (const std::string &body, const std::string &error, unsigned status) const
Protected Attributes
std::string m_host
std::string m_apikey
std::string m_cafile
bool m_ssl_revoke_best_effort
Detailed Description
Member Typedef Documentation
ErrorFn
typedef std::function<void(wxString)> Slic3r::PrintHost::ErrorFn inherited
InfoFn
typedef std::function<void(wxString , wxString)> Slic3r::PrintHost::InfoFn inherited
ProgressFn
typedef Http::ProgressFn Slic3r::PrintHost::ProgressFn inherited
Constructor & Destructor Documentation
OctoPrint()
Slic3r::OctoPrint::OctoPrint (DynamicPrintConfig * config)
                                               :
    m_host(config->opt_string("print_host")),
    m_apikey(config->opt_string("printhost_apikey")),
    m_cafile(config->opt_string("printhost_cafile")),
    m_ssl_revoke_best_effort(config->opt_bool("printhost_ssl_ignore_revoke"))
{}
~OctoPrint()
Slic3r::OctoPrint::~OctoPrint () override default
Member Function Documentation
can_test()
bool Slic3r::OctoPrint::can_test () const inline override virtual
Implements Slic3r::PrintHost.
{ return true; }
format_error()
wxString Slic3r::PrintHost::format_error (const std::string & body, const std::string & error, unsigned status) const protected virtual inherited
{
    if (status != 0) {
        auto wxbody = wxString::FromUTF8(body.data());
        return wxString::Format("HTTP %u: %s", status, wxbody);
    } else {
        return wxString::FromUTF8(error.data());
    }
}
References error.
Referenced by Slic3r::Duet::connect(), Slic3r::PrusaLink::post_inner(), Slic3r::PrusaLink::put_inner(), Slic3r::Duet::start_print(), Slic3r::AstroBox::test(), Slic3r::FlashAir::test(), Slic3r::Moonraker::test(), test(), Slic3r::PrusaLink::test(), Slic3r::Repetier::test(), Slic3r::PrusaLink::test_with_method_check(), Slic3r::AstroBox::upload(), Slic3r::Duet::upload(), Slic3r::FlashAir::upload(), Slic3r::MKS::upload(), Slic3r::Moonraker::upload(), Slic3r::Repetier::upload(), and upload_inner_with_host().
get_apikey()
const std::string & Slic3r::OctoPrint::get_apikey () const inline
{ return m_apikey; }
References m_apikey.
Referenced by Slic3r::PrusaLink::set_auth().
get_cafile()
const std::string & Slic3r::OctoPrint::get_cafile () const inline
{ return m_cafile; }
References m_cafile.
Referenced by Slic3r::PrusaLink::set_auth().
get_groups()
virtual bool Slic3r::PrintHost::get_groups (wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
get_host()
std::string Slic3r::OctoPrint::get_host () const inline override virtual
Implements Slic3r::PrintHost.
{ return m_host; }
References m_host.
get_name()
const char * Slic3r::OctoPrint::get_name () const override virtual
Implements Slic3r::PrintHost.
Reimplemented in Slic3r::PrusaLink, Slic3r::PrusaConnect, and Slic3r::SL1Host.
{ return "OctoPrint"; }
Referenced by test(), and upload_inner_with_host().
get_post_upload_actions()
PrintHostPostUploadActions Slic3r::OctoPrint::get_post_upload_actions () const inline override virtual
Implements Slic3r::PrintHost.
Reimplemented in Slic3r::PrusaLink, Slic3r::PrusaConnect, and Slic3r::SL1Host.
{ return PrintHostPostUploadAction::StartPrint; }
References Slic3r::StartPrint.
get_print_host()
PrintHost * Slic3r::PrintHost::get_print_host (DynamicPrintConfig * config) static inherited
{
    PrinterTechnology tech = ptFFF;
    {
        const auto opt = config->option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
        if (opt != nullptr) {
            tech = opt->value;
        }
    }
    if (tech == ptFFF) {
        const auto opt = config->option<ConfigOptionEnum<PrintHostType>>("host_type");
        const auto host_type = opt != nullptr ? opt->value : htOctoPrint;
        switch (host_type) {
            case htOctoPrint: return new OctoPrint(config);
            case htDuet:      return new Duet(config);
            case htFlashAir:  return new FlashAir(config);
            case htAstroBox:  return new AstroBox(config);
            case htRepetier:  return new Repetier(config);
            case htPrusaLink: return new PrusaLink(config);
            case htPrusaConnect: return new PrusaConnect(config);
            case htMKS:       return new MKS(config);
            case htMoonraker: return new Moonraker(config);
            default:          return nullptr;
        }
    } else {
        return new SL1Host(config);
    }
}
References Slic3r::htAstroBox, Slic3r::htDuet, Slic3r::htFlashAir, Slic3r::htMKS, Slic3r::htMoonraker, Slic3r::htOctoPrint, Slic3r::htPrusaConnect, Slic3r::htPrusaLink, Slic3r::htRepetier, Slic3r::ConfigBase::option(), Slic3r::ptFFF, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::PhysicalPrinterDialog::update_printers(), and Slic3r::GUI::PhysicalPrinterDialog::update_printhost_buttons().
get_printers()
virtual bool Slic3r::PrintHost::get_printers (wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
get_storage()
virtual bool Slic3r::PrintHost::get_storage (wxArrayString & , wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::PrusaLink, and Slic3r::PrusaConnect.
{ return false; }
get_test_failed_msg()
wxString Slic3r::OctoPrint::get_test_failed_msg (wxString & msg) const override virtual
Implements Slic3r::PrintHost.
Reimplemented in Slic3r::PrusaLink, Slic3r::PrusaConnect, and Slic3r::SL1Host.
{
    return GUI::format_wxstr("%s: %s\n\n%s"
        , _L("Could not connect to OctoPrint")
        , msg
        , _L("Note: OctoPrint version at least 1.1.0 is required."));
}
References _L, and Slic3r::GUI::format_wxstr().
get_test_ok_msg()
wxString Slic3r::OctoPrint::get_test_ok_msg () const override virtual
Implements Slic3r::PrintHost.
Reimplemented in Slic3r::PrusaLink, Slic3r::PrusaConnect, and Slic3r::SL1Host.
{
    return _(L("Connection to OctoPrint works correctly."));
}
References _, and L.
has_auto_discovery()
bool Slic3r::OctoPrint::has_auto_discovery () const inline override virtual
Implements Slic3r::PrintHost.
{ return true; }
make_url()
std::string Slic3r::OctoPrint::make_url (const std::string & path) const protected
{
    if (m_host.find("http://") == 0 || m_host.find("https://") == 0) {
        if (m_host.back() == '/') {
            return (boost::format("%1%%2%") % m_host % path).str();
        } else {
            return (boost::format("%1%/%2%") % m_host % path).str();
        }
    } else {
        return (boost::format("http://%1%/%2%") % m_host % path).str();
    }
}
References m_host.
Referenced by Slic3r::PrusaLink::get_storage(), test(), Slic3r::PrusaLink::test(), Slic3r::PrusaLink::test_with_method_check(), upload_inner_with_host(), and Slic3r::PrusaLink::upload_inner_with_host().
set_auth()
void Slic3r::OctoPrint::set_auth (Http & http) const protected virtual
Reimplemented in Slic3r::PrusaLink.
{
    http.header("X-Api-Key", m_apikey);
    if (!m_cafile.empty()) {
        http.ca_file(m_cafile);
    }
}
References Slic3r::Http::ca_file(), Slic3r::Http::header(), m_apikey, and m_cafile.
Referenced by test(), and upload_inner_with_host().
supports_multiple_printers()
virtual bool Slic3r::PrintHost::supports_multiple_printers () const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
test()
bool Slic3r::OctoPrint::test (wxString & curl_msg) const override virtual
Implements Slic3r::PrintHost.
Reimplemented in Slic3r::PrusaLink.
{
    // Since the request is performed synchronously here,
    // it is ok to refer to `msg` from within the closure
    const char *name = get_name();
    bool res = true;
    auto url = make_url("api/version");
    BOOST_LOG_TRIVIAL(info) << boost::format("%1%: Get version at: %2%") % name % url;
    // Here we do not have to add custom "Host" header - the url contains host filled by user and libCurl will set the header by itself.
    auto http = Http::get(std::move(url));
    set_auth(http);
    http.on_error([&](std::string body, std::string error, unsigned status) {
            BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Error getting version: %2%, HTTP %3%, body: `%4%`") % name % error % status % body;
            res = false;
            msg = format_error(body, error, status);
        })
        .on_complete([&, this](std::string body, unsigned) {
            BOOST_LOG_TRIVIAL(debug) << boost::format("%1%: Got version: %2%") % name % body;
            try {
                std::stringstream ss(body);
                pt::ptree ptree;
                pt::read_json(ss, ptree);
                if (! ptree.get_optional<std::string>("api")) {
                    res = false;
                    return;
                }
                const auto text = ptree.get_optional<std::string>("text");
                res = validate_version_text(text);
                if (! res) {
                    msg = GUI::format_wxstr(_L("Mismatched type of print host: %s"), (text ? *text : name));
                }
            }
            catch (const std::exception &) {
                res = false;
                msg = "Could not parse server response";
            }
        })
#ifdef WIN32
            .ssl_revoke_best_effort(m_ssl_revoke_best_effort)
            .on_ip_resolve([&](std::string address) {
            // Workaround for Windows 10/11 mDNS resolve issue, where two mDNS resolves in succession fail.
            // Remember resolved address to be reused at successive REST API call.
            msg = GUI::from_u8(address);
        })
#endif // WIN32
        .perform_sync();
    return res;
}
References _L, error, Slic3r::PrintHost::format_error(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::from_u8(), Slic3r::Http::get(), get_name(), m_ssl_revoke_best_effort, make_url(), set_auth(), and validate_version_text().
Referenced by upload_inner_with_host().
upload()
bool Slic3r::OctoPrint::upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const override virtual
Implements Slic3r::PrintHost.
{
#ifndef WIN32
    return upload_inner_with_host(std::move(upload_data), prorgess_fn, error_fn, info_fn);
#else
    std::string host = get_host_from_url(m_host);
    // decide what to do based on m_host - resolve hostname or upload to ip
    std::vector<boost::asio::ip::address> resolved_addr;
    boost::system::error_code ec;
    boost::asio::ip::address host_ip = boost::asio::ip::make_address(host, ec);
    if (!ec) {
        resolved_addr.push_back(host_ip);
    } else if ( GUI::get_app_config()->get_bool("allow_ip_resolve") && boost::algorithm::ends_with(host, ".local")){
        Bonjour("octoprint")
            .set_hostname(host)
            .set_retries(5) // number of rounds of queries send
            .set_timeout(1) // after each timeout, if there is any answer, the resolving will stop
            .on_resolve([&ra = resolved_addr](const std::vector<BonjourReply>& replies) {
                for (const auto & rpl : replies) {
                    boost::asio::ip::address ip(rpl.ip);
                    ra.emplace_back(ip);
                    BOOST_LOG_TRIVIAL(info) << "Resolved IP address: " << rpl.ip;
                }
            })
            .resolve_sync();
    }
    if (resolved_addr.empty()) {
        // no resolved addresses - try system resolving
        BOOST_LOG_TRIVIAL(error) << "PrusaSlicer failed to resolve hostname " << m_host << " into the IP address. Starting upload with system resolving.";
        return upload_inner_with_host(std::move(upload_data), prorgess_fn, error_fn, info_fn);
    } else if (resolved_addr.size() == 1) {
        // one address resolved - upload there
        return upload_inner_with_resolved_ip(std::move(upload_data), prorgess_fn, error_fn, info_fn, resolved_addr.front());
    }  else if (resolved_addr.size() == 2 && resolved_addr[0].is_v4() != resolved_addr[1].is_v4()) {
        // there are just 2 addresses and 1 is ip_v4 and other is ip_v6
        // try sending to both. (Then if both fail, show both error msg after second try)
        wxString error_message;
        if (!upload_inner_with_resolved_ip(std::move(upload_data), prorgess_fn
            , [&msg = error_message, resolved_addr](wxString error) { msg = GUI::format_wxstr("%1%: %2%", resolved_addr.front(), error); }
            , info_fn, resolved_addr.front())
            &&
            !upload_inner_with_resolved_ip(std::move(upload_data), prorgess_fn
            , [&msg = error_message, resolved_addr](wxString error) { msg += GUI::format_wxstr("\n%1%: %2%", resolved_addr.back(), error); }
            , info_fn, resolved_addr.back())
            ) {
            error_fn(error_message);
            return false;
        }
        return true;
    } else {
        // There are multiple addresses - user needs to choose which to use.
        size_t selected_index = resolved_addr.size();
        IPListDialog dialog(nullptr, boost::nowide::widen(m_host), resolved_addr, selected_index);
        if (dialog.ShowModal() == wxID_OK && selected_index < resolved_addr.size()) {
            return upload_inner_with_resolved_ip(std::move(upload_data), prorgess_fn, error_fn, info_fn, resolved_addr[selected_index]);
        }
    }
    return false;
#endif // WIN32
}
References error, Slic3r::GUI::format_wxstr(), Slic3r::GUI::get_app_config(), m_host, Slic3r::Bonjour::on_resolve(), Slic3r::Bonjour::set_hostname(), Slic3r::Bonjour::set_retries(), Slic3r::Bonjour::set_timeout(), upload_inner_with_host(), and boost::nowide::widen().
upload_inner_with_host()
bool Slic3r::OctoPrint::upload_inner_with_host (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const protected virtual
Reimplemented in Slic3r::PrusaLink.
{
    const char* name = get_name();
    const auto upload_filename = upload_data.upload_path.filename();
    const auto upload_parent_path = upload_data.upload_path.parent_path();
    // If test fails, test_msg_or_host_ip contains the error message.
    // Otherwise on Windows it contains the resolved IP address of the host.
    wxString test_msg_or_host_ip;
    if (!test(test_msg_or_host_ip)) {
        error_fn(std::move(test_msg_or_host_ip));
        return false;
    }
    std::string url;
    bool res = true;
#ifdef WIN32
    // Workaround for Windows 10/11 mDNS resolve issue, where two mDNS resolves in succession fail.
    if (m_host.find("https://") == 0 || test_msg_or_host_ip.empty() || !GUI::get_app_config()->get_bool("allow_ip_resolve"))
#endif // _WIN32
    {
        // If https is entered we assume signed ceritificate is being used
        // IP resolving will not happen - it could resolve into address not being specified in cert
        url = make_url("api/files/local");
    }
#ifdef WIN32
    else {
        // Workaround for Windows 10/11 mDNS resolve issue, where two mDNS resolves in succession fail.
        // Curl uses easy_getinfo to get ip address of last successful transaction.
        // If it got the address use it instead of the stored in "host" variable.
        // This new address returns in "test_msg_or_host_ip" variable.
        // Solves troubles of uploades failing with name address.
        // in original address (m_host) replace host for resolved ip
        info_fn(L"resolve", test_msg_or_host_ip);
        url = substitute_host(make_url("api/files/local"), GUI::into_u8(test_msg_or_host_ip));
        BOOST_LOG_TRIVIAL(info) << "Upload address after ip resolve: " << url;
    }
#endif // _WIN32
    BOOST_LOG_TRIVIAL(info) << boost::format("%1%: Uploading file %2% at %3%, filename: %4%, path: %5%, print: %6%")
        % name
        % upload_data.source_path
        % url
        % upload_filename.string()
        % upload_parent_path.string()
        % (upload_data.post_action == PrintHostPostUploadAction::StartPrint ? "true" : "false");
    auto http = Http::post(std::move(url));
#ifdef WIN32
    // "Host" header is necessary here. In the workaround above (two mDNS..) we have got IP address from test connection and subsituted it into "url" variable.
    // And when creating Http object above, libcurl automatically includes "Host" header from address it got.
    // Thus "Host" is set to the resolved IP instead of host filled by user. We need to change it back.
    // Not changing the host would work on the most cases (where there is 1 service on 1 hostname) but would break when f.e. reverse proxy is used (issue #9734).
    // Also when allow_ip_resolve = 0, this is not needed, but it should not break anything if it stays.
    // https://www.rfc-editor.org/rfc/rfc7230#section-5.4
    std::string host = get_host_from_url(m_host);
    http.header("Host", host);
#endif // _WIN32
    set_auth(http);
    http.form_add("print", upload_data.post_action == PrintHostPostUploadAction::StartPrint ? "true" : "false")
        .form_add("path", upload_parent_path.string())      // XXX: slashes on windows ???
        .form_add_file("file", upload_data.source_path.string(), upload_filename.string())
        .on_complete([&](std::string body, unsigned status) {
            BOOST_LOG_TRIVIAL(debug) << boost::format("%1%: File uploaded: HTTP %2%: %3%") % name % status % body;
        })
        .on_error([&](std::string body, std::string error, unsigned status) {
            BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Error uploading file: %2%, HTTP %3%, body: `%4%`") % name % error % status % body;
            error_fn(format_error(body, error, status));
            res = false;
        })
        .on_progress([&](Http::Progress progress, bool& cancel) {
            prorgess_fn(std::move(progress), cancel);
            if (cancel) {
                // Upload was canceled
                BOOST_LOG_TRIVIAL(info) << name << ": Upload canceled";
                res = false;
            }
        })
#ifdef WIN32
        .ssl_revoke_best_effort(m_ssl_revoke_best_effort)
#endif
        .perform_sync();
    return res;
}
References error, Slic3r::PrintHost::format_error(), Slic3r::GUI::get_app_config(), Slic3r::AppConfig::get_bool(), get_name(), Slic3r::GUI::into_u8(), L, m_host, m_ssl_revoke_best_effort, make_url(), Slic3r::Http::post(), Slic3r::PrintHostUpload::post_action, set_auth(), Slic3r::PrintHostUpload::source_path, Slic3r::StartPrint, test(), and Slic3r::PrintHostUpload::upload_path.
Referenced by upload().
validate_version_text()
bool Slic3r::OctoPrint::validate_version_text (const boost::optional< std::string > & version_text) const protected virtual
Reimplemented in Slic3r::PrusaLink, and Slic3r::SL1Host.
{
    return version_text ? boost::starts_with(*version_text, "OctoPrint") : true;
}
Referenced by test().
Member Data Documentation
m_apikey
std::string Slic3r::OctoPrint::m_apikey protected
Referenced by get_apikey(), and set_auth().
m_cafile
std::string Slic3r::OctoPrint::m_cafile protected
Referenced by get_cafile(), and set_auth().
m_host
std::string Slic3r::OctoPrint::m_host protected
Referenced by get_host(), Slic3r::PrusaLink::get_storage(), make_url(), Slic3r::PrusaLink::post_inner(), Slic3r::PrusaLink::put_inner(), upload(), upload_inner_with_host(), and Slic3r::PrusaLink::upload_inner_with_host().
m_ssl_revoke_best_effort
bool Slic3r::OctoPrint::m_ssl_revoke_best_effort protected
Referenced by Slic3r::PrusaLink::get_storage(), Slic3r::PrusaLink::post_inner(), Slic3r::PrusaLink::put_inner(), test(), Slic3r::PrusaLink::test(), Slic3r::PrusaLink::test_with_method_check(), and upload_inner_with_host().
The documentation for this class was generated from the following files:
src/slic3r/Utils/OctoPrint.hpp
src/slic3r/Utils/OctoPrint.cpp