Prusa Slicer: Slic3r::GUI::PrintHostSendDialog Class Reference
Slic3r::GUI::PrintHostSendDialog Class Reference
#include <src/slic3r/GUI/PrintHostDialogs.hpp>
Public Member Functions
PrintHostSendDialog (const boost::filesystem::path &path, PrintHostPostUploadActions post_actions, const wxArrayString &groups, const wxArrayString &storage_paths, const wxArrayString &storage_names)
boost::filesystem::path filename () const
PrintHostPostUploadAction post_action () const
std::string group () const
std::string storage () const
virtual void EndModal (int ret) override
void SetButtonLabel (wxWindowID btn_id, const wxString &label, bool set_focus=false)
Protected Types
enum {
CONTENT_WIDTH = 70 , CONTENT_MAX_HEIGHT = 60 , BORDER = 30 , VERT_SPACING = 15 ,
HORIZ_SPACING = 5
}
Protected Member Functions
wxButton * add_button (wxWindowID btn_id, bool set_focus=false, const wxString &label=wxString())
wxButton * get_button (wxWindowID btn_id)
void apply_style (long style)
void finalize ()
Protected Attributes
wxFont boldfont
wxBoxSizer * content_sizer
wxBoxSizer * btn_sizer
wxStaticBitmap * logo
Private Attributes
wxTextCtrl * txt_filename
wxComboBox * combo_groups
wxComboBox * combo_storage
PrintHostPostUploadAction post_upload_action
wxString m_valid_suffix
wxString m_preselected_storage
wxArrayString m_paths
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum protected inherited
Enumerator
CONTENT_WIDTH
CONTENT_MAX_HEIGHT
BORDER
VERT_SPACING
HORIZ_SPACING
       {
    CONTENT_WIDTH = 70,//50,
    CONTENT_MAX_HEIGHT = 60,
    BORDER = 30,
    VERT_SPACING = 15,
    HORIZ_SPACING = 5,
  };
Constructor & Destructor Documentation
PrintHostSendDialog()
Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog (const boost::filesystem::path & path, PrintHostPostUploadActions post_actions, const wxArrayString & groups, const wxArrayString & storage_paths, const wxArrayString & storage_names)
    : MsgDialog(static_cast<wxWindow*>(wxGetApp().mainframe), _L("Send G-Code to printer host"), _L("Upload to Printer Host with the following filename:"), 0) // Set style = 0 to avoid default creation of the "OK" button.
                                                                                                                                                               // All buttons will be added later in this constructor
    , txt_filename(new wxTextCtrl(this, wxID_ANY))
    , combo_groups(!groups.IsEmpty() ? new wxComboBox(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, groups, wxCB_READONLY) : nullptr)
    , combo_storage(storage_names.GetCount() > 1 ? new wxComboBox(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, storage_names, wxCB_READONLY) : nullptr)
    , post_upload_action(PrintHostPostUploadAction::None)
    , m_paths(storage_paths)
{
#ifdef __APPLE__
    txt_filename->OSXDisableAllSmartSubstitutions();
#endif
    const AppConfig *app_config = wxGetApp().app_config;
    auto *label_dir_hint = new wxStaticText(this, wxID_ANY, _L("Use forward slashes ( / ) as a directory separator if needed."));
    label_dir_hint->Wrap(CONTENT_WIDTH * wxGetApp().em_unit());
    content_sizer->Add(txt_filename, 0, wxEXPAND);
    content_sizer->Add(label_dir_hint);
    content_sizer->AddSpacer(VERT_SPACING);
    if (combo_groups != nullptr) {
        // Repetier specific: Show a selection of file groups.
        auto *label_group = new wxStaticText(this, wxID_ANY, _L("Group"));
        content_sizer->Add(label_group);
        content_sizer->Add(combo_groups, 0, wxBOTTOM, 2*VERT_SPACING);
        wxString recent_group = from_u8(app_config->get("recent", CONFIG_KEY_GROUP));
        if (! recent_group.empty())
            combo_groups->SetValue(recent_group);
    }
    if (combo_storage != nullptr) {
        // PrusaLink specific: User needs to choose a storage
        auto* label_group = new wxStaticText(this, wxID_ANY, _L("Upload to storage") + ":");
        content_sizer->Add(label_group);
        content_sizer->Add(combo_storage, 0, wxBOTTOM, 2 * VERT_SPACING);
        combo_storage->SetValue(storage_names.front());
        wxString recent_storage = from_u8(app_config->get("recent", CONFIG_KEY_STORAGE));
        if (!recent_storage.empty())
            combo_storage->SetValue(recent_storage);
    } else if (storage_names.GetCount() == 1){
        // PrusaLink specific: Show which storage has been detected.
        auto* label_group = new wxStaticText(this, wxID_ANY, _L("Upload to storage") + ": " + storage_names.front());
        content_sizer->Add(label_group);
        m_preselected_storage = storage_paths.front();
    }
    wxString recent_path = from_u8(app_config->get("recent", CONFIG_KEY_PATH));
    if (recent_path.Length() > 0 && recent_path[recent_path.Length() - 1] != '/') {
        recent_path += '/';
    }
    const auto recent_path_len = recent_path.Length();
    recent_path += path.filename().wstring();
    wxString stem(path.stem().wstring());
    const auto stem_len = stem.Length();
    txt_filename->SetValue(recent_path);
    if (size_t extension_start = recent_path.find_last_of('.'); extension_start != std::string::npos)
        m_valid_suffix = recent_path.substr(extension_start);
    // .gcode suffix control
    auto validate_path = [this](const wxString &path) -> bool {
        if (! path.Lower().EndsWith(m_valid_suffix.Lower())) {
            MessageDialog msg_wingow(this, wxString::Format(_L("Upload filename doesn't end with \"%s\". Do you wish to continue?"), m_valid_suffix), wxString(SLIC3R_APP_NAME), wxYES | wxNO);
            if (msg_wingow.ShowModal() == wxID_NO)
                return false;
        }
        return true;
    };
    auto* btn_ok = add_button(wxID_OK, true, _L("Upload"));
    btn_ok->Bind(wxEVT_BUTTON, [this, validate_path](wxCommandEvent&) {
        if (validate_path(txt_filename->GetValue())) {
            post_upload_action = PrintHostPostUploadAction::None;
            EndDialog(wxID_OK);
        }
    });
    txt_filename->SetFocus();
    if (post_actions.has(PrintHostPostUploadAction::QueuePrint)) {
        auto* btn_print = add_button(wxID_ADD, false, _L("Upload to Queue"));
        btn_print->Bind(wxEVT_BUTTON, [this, validate_path](wxCommandEvent&) {
            if (validate_path(txt_filename->GetValue())) {
                post_upload_action = PrintHostPostUploadAction::QueuePrint;
                EndDialog(wxID_OK);
            }
            });
    }
    if (post_actions.has(PrintHostPostUploadAction::StartPrint)) {
        auto* btn_print = add_button(wxID_YES, false, _L("Upload and Print"));
        btn_print->Bind(wxEVT_BUTTON, [this, validate_path](wxCommandEvent&) {
            if (validate_path(txt_filename->GetValue())) {
                post_upload_action = PrintHostPostUploadAction::StartPrint;
                EndDialog(wxID_OK);
            }
        });
    }
    if (post_actions.has(PrintHostPostUploadAction::StartSimulation)) {
        // Using wxID_MORE as a button identifier to be different from the other buttons, wxID_MORE has no other meaning here.
        auto* btn_simulate = add_button(wxID_MORE, false, _L("Upload and Simulate"));
        btn_simulate->Bind(wxEVT_BUTTON, [this, validate_path](wxCommandEvent&) {
            if (validate_path(txt_filename->GetValue())) {
                post_upload_action = PrintHostPostUploadAction::StartSimulation;
                EndDialog(wxID_OK);
            }
        });
    }
    add_button(wxID_CANCEL);
    finalize();
#ifdef __linux__
    // On Linux with GTK2 when text control lose the focus then selection (colored background) disappears but text color stay white
    // and as a result the text is invisible with light mode
    // see https://github.com/prusa3d/PrusaSlicer/issues/4532
    // Workaround: Unselect text selection explicitly on kill focus
    txt_filename->Bind(wxEVT_KILL_FOCUS, [this](wxEvent& e) {
        e.Skip();
        txt_filename->SetInsertionPoint(txt_filename->GetLastPosition());
    }, txt_filename->GetId());
#endif /* __linux__ */
    Bind(wxEVT_SHOW, [=](const wxShowEvent &) {
        // Another similar case where the function only works with EVT_SHOW + CallAfter,
        // this time on Mac.
        CallAfter([=]() {
            txt_filename->SetInsertionPoint(0);
            txt_filename->SetSelection(recent_path_len, recent_path_len + stem_len);
        });
    });
}
References _L, Slic3r::GUI::MsgDialog::add_button(), combo_groups, combo_storage, Slic3r::GUI::CONFIG_KEY_GROUP, Slic3r::GUI::CONFIG_KEY_PATH, Slic3r::GUI::CONFIG_KEY_STORAGE, Slic3r::GUI::MsgDialog::content_sizer, Slic3r::GUI::MsgDialog::CONTENT_WIDTH, em_unit(), Slic3r::GUI::MsgDialog::finalize(), Slic3r::GUI::from_u8(), Slic3r::AppConfig::get(), Slic3r::enum_bitmask< option_type, typename >::has(), m_preselected_storage, m_valid_suffix, Slic3r::QueuePrint, Slic3r::StartPrint, Slic3r::StartSimulation, txt_filename, Slic3r::GUI::MsgDialog::VERT_SPACING, and wxEVT_BUTTON.
Member Function Documentation
add_button()
wxButton * Slic3r::GUI::MsgDialog::add_button (wxWindowID btn_id, bool set_focus = false, const wxString & label = wxString()) protected inherited
{
    wxButton* btn = new wxButton(this, btn_id, label);
    if (set_focus) {
        btn->SetFocus();
        // For non-MSW platforms SetFocus is not enought to use it as default, when the dialog is closed by ENTER
        // We have to set this button as the (permanently) default one in its dialog
        // See https://twitter.com/ZMelmed/status/1472678454168539146
        btn->SetDefault();
    }
    btn_sizer->Add(btn, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, HORIZ_SPACING);
    btn->Bind(wxEVT_BUTTON, [this, btn_id](wxCommandEvent&) { this->EndModal(btn_id); });
    return btn;
};
References Slic3r::GUI::MsgDialog::btn_sizer, Slic3r::GUI::MsgDialog::HORIZ_SPACING, and wxEVT_BUTTON.
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), PrintHostSendDialog(), and Slic3r::GUI::MsgDialog::apply_style().
apply_style()
void Slic3r::GUI::MsgDialog::apply_style (long style) protected inherited
{
    if (style & wxOK)       add_button(wxID_OK, true);
    if (style & wxYES)      add_button(wxID_YES,   !(style & wxNO_DEFAULT));
    if (style & wxNO)       add_button(wxID_NO,     (style & wxNO_DEFAULT));
    if (style & wxCANCEL)   add_button(wxID_CANCEL, (style & wxCANCEL_DEFAULT));
    std::string icon_name = style & wxICON_WARNING        ? "exclamation" :
                            style & wxICON_INFORMATION    ? "info"        :
                            style & wxICON_QUESTION       ? "question"    : "PrusaSlicer";
    logo->SetBitmap(*get_bmp_bundle(icon_name, 64));
}
References Slic3r::GUI::MsgDialog::add_button(), get_bmp_bundle(), Slic3r::GUI::MsgDialog::logo, and style.
Referenced by Slic3r::GUI::MsgDialog::MsgDialog().
EndModal()
void Slic3r::GUI::PrintHostSendDialog::EndModal (int ret) override virtual
{
    if (ret == wxID_OK) {
        // Persist path and print settings
        wxString path = txt_filename->GetValue();
        int last_slash = path.Find('/', true);
    if (last_slash == wxNOT_FOUND)
      path.clear();
    else
            path = path.SubString(0, last_slash);
    AppConfig *app_config = wxGetApp().app_config;
    app_config->set("recent", CONFIG_KEY_PATH, into_u8(path));
        if (combo_groups != nullptr) {
            wxString group = combo_groups->GetValue();
            app_config->set("recent", CONFIG_KEY_GROUP, into_u8(group));
        }
        if (combo_storage != nullptr) {
            wxString storage = combo_storage->GetValue();
            app_config->set("recent", CONFIG_KEY_STORAGE, into_u8(storage));
        }
    }
    MsgDialog::EndModal(ret);
}
References combo_groups, combo_storage, Slic3r::GUI::CONFIG_KEY_GROUP, Slic3r::GUI::CONFIG_KEY_PATH, Slic3r::GUI::CONFIG_KEY_STORAGE, group(), Slic3r::GUI::into_u8(), Slic3r::AppConfig::set(), storage(), and txt_filename.
filename()
fs::path Slic3r::GUI::PrintHostSendDialog::filename () const
{
    return into_path(txt_filename->GetValue());
}
References Slic3r::GUI::into_path(), and txt_filename.
Referenced by Slic3r::GUI::Plater::send_gcode().
finalize()
void Slic3r::GUI::MsgDialog::finalize () protected inherited
{
    wxGetApp().UpdateDlgDarkUI(this);
    Fit();
    this->CenterOnParent();
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
get_button()
wxButton * Slic3r::GUI::MsgDialog::get_button (wxWindowID btn_id) protected inherited
{
    return static_cast<wxButton*>(FindWindowById(btn_id, this));
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), and Slic3r::GUI::MsgDialog::SetButtonLabel().
group()
std::string Slic3r::GUI::PrintHostSendDialog::group () const
{
     if (combo_groups == nullptr) {
         return "";
     } else {
         wxString group = combo_groups->GetValue();
         return into_u8(group);
    }
}
References combo_groups, group(), and Slic3r::GUI::into_u8().
Referenced by EndModal(), group(), and Slic3r::GUI::Plater::send_gcode().
post_action()
PrintHostPostUploadAction Slic3r::GUI::PrintHostSendDialog::post_action () const
{
    return post_upload_action;
}
References post_upload_action.
Referenced by Slic3r::GUI::Plater::send_gcode().
SetButtonLabel()
void Slic3r::GUI::MsgDialog::SetButtonLabel (wxWindowID btn_id, const wxString & label, bool set_focus = false) inherited
{
    if (wxButton* btn = get_button(btn_id)) {
        btn->SetLabel(label);
        if (set_focus)
            btn->SetFocus();
    }
}
References Slic3r::GUI::MsgDialog::get_button().
Referenced by Slic3r::GUI::GUI_App::check_older_app_config(), Slic3r::GUI::ObjectList::del_from_cut_object(), and Slic3r::GUI::Plater::priv::delete_object_from_model().
storage()
std::string Slic3r::GUI::PrintHostSendDialog::storage () const
{
    if (!combo_storage)
        return GUI::format("%1%", m_preselected_storage);
    if (combo_storage->GetSelection() < 0 || combo_storage->GetSelection() >= int(m_paths.size()))
        return {};
    return boost::nowide::narrow(m_paths[combo_storage->GetSelection()]);
}
References combo_storage, Slic3r::GUI::format(), m_paths, m_preselected_storage, and boost::nowide::narrow().
Referenced by EndModal(), and Slic3r::GUI::Plater::send_gcode().
Member Data Documentation
boldfont
wxFont Slic3r::GUI::MsgDialog::boldfont protected inherited
Referenced by Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), and Slic3r::GUI::MsgUpdateForced::MsgUpdateForced().
btn_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::btn_sizer protected inherited
Referenced by Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::add_button().
combo_groups
wxComboBox* Slic3r::GUI::PrintHostSendDialog::combo_groups private
Referenced by PrintHostSendDialog(), EndModal(), and group().
combo_storage
wxComboBox* Slic3r::GUI::PrintHostSendDialog::combo_storage private
Referenced by PrintHostSendDialog(), EndModal(), and storage().
content_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::content_sizer protected inherited
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
logo
wxStaticBitmap* Slic3r::GUI::MsgDialog::logo protected inherited
Referenced by Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::apply_style().
m_paths
wxArrayString Slic3r::GUI::PrintHostSendDialog::m_paths private
Referenced by storage().
m_preselected_storage
wxString Slic3r::GUI::PrintHostSendDialog::m_preselected_storage private
Referenced by PrintHostSendDialog(), and storage().
m_valid_suffix
wxString Slic3r::GUI::PrintHostSendDialog::m_valid_suffix private
Referenced by PrintHostSendDialog().
post_upload_action
PrintHostPostUploadAction Slic3r::GUI::PrintHostSendDialog::post_upload_action private
Referenced by post_action().
txt_filename
wxTextCtrl* Slic3r::GUI::PrintHostSendDialog::txt_filename private
Referenced by PrintHostSendDialog(), EndModal(), and filename().
The documentation for this class was generated from the following files:
src/slic3r/GUI/PrintHostDialogs.hpp
src/slic3r/GUI/PrintHostDialogs.cpp