Prusa Slicer: Eigen::HessenbergDecomposition< _MatrixType > Class Template Reference
Eigen::HessenbergDecomposition< _MatrixType > Class Template Reference
Reduces a square matrix to Hessenberg form by an orthogonal similarity transformation.
#include <src/eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h>
Public Types
enum {
Size = MatrixType::RowsAtCompileTime , SizeMinusOne = Size == Dynamic ? Dynamic : Size - 1 , Options = MatrixType::Options , MaxSize = MatrixType::MaxRowsAtCompileTime ,
MaxSizeMinusOne = MaxSize == Dynamic ? Dynamic : MaxSize - 1
}
typedef _MatrixType MatrixType
Synonym for the template parameter _MatrixType.
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType.
typedef Eigen::Index Index
typedef Matrix< Scalar, SizeMinusOne, 1, Options &~RowMajor, MaxSizeMinusOne, 1 > CoeffVectorType
Type for vector of Householder coefficients.
typedef HouseholderSequence< MatrixType, typename internal::remove_all< typename CoeffVectorType::ConjugateReturnType >::type > HouseholderSequenceType
Return type of matrixQ()
typedef internal::HessenbergDecompositionMatrixHReturnType< MatrixType > MatrixHReturnType
Public Member Functions
HessenbergDecomposition (Index size=Size==Dynamic ? 2 :Size)
Default constructor; the decomposition will be computed later.
template<typename InputType >
HessenbergDecomposition (const EigenBase< InputType > &matrix)
Constructor; computes Hessenberg decomposition of given matrix.
template<typename InputType >
HessenbergDecomposition & compute (const EigenBase< InputType > &matrix)
Computes Hessenberg decomposition of given matrix.
const CoeffVectorType & householderCoefficients () const
Returns the Householder coefficients.
const MatrixType & packedMatrix () const
Returns the internal representation of the decomposition.
HouseholderSequenceType matrixQ () const
Reconstructs the orthogonal matrix Q in the decomposition.
MatrixHReturnType matrixH () const
Constructs the Hessenberg matrix H in the decomposition.
Protected Attributes
MatrixType m_matrix
CoeffVectorType m_hCoeffs
VectorType m_temp
bool m_isInitialized
Private Types
typedef Matrix< Scalar, 1, Size, Options|RowMajor, 1, MaxSize > VectorType
typedef NumTraits< Scalar >::Real RealScalar
Static Private Member Functions
static void _compute (MatrixType &matA, CoeffVectorType &hCoeffs, VectorType &temp)
Detailed Description
template<typename _MatrixType>
class Eigen::HessenbergDecomposition< _MatrixType >
Reduces a square matrix to Hessenberg form by an orthogonal similarity transformation.
\eigenvalues_module
Template Parameters
_MatrixType the type of the matrix of which we are computing the Hessenberg decomposition
This class performs an Hessenberg decomposition of a matrix . In the real case, the Hessenberg decomposition consists of an orthogonal matrix and a Hessenberg matrix such that . An orthogonal matrix is a matrix whose inverse equals its transpose (). A Hessenberg matrix has zeros below the subdiagonal, so it is almost upper triangular. The Hessenberg decomposition of a complex matrix is with unitary (that is,).
Call the function compute() to compute the Hessenberg decomposition of a given matrix. Alternatively, you can use the HessenbergDecomposition(const MatrixType&) constructor which computes the Hessenberg decomposition at construction time. Once the decomposition is computed, you can use the matrixH() and matrixQ() functions to construct the matrices H and Q in the decomposition.
The documentation for matrixH() contains an example of the typical use of this class.
See also
class ComplexSchur, class Tridiagonalization, QR Module
Member Typedef Documentation
CoeffVectorType
template<typename _MatrixType > typedef Matrix<Scalar, SizeMinusOne, 1, Options & ~RowMajor, MaxSizeMinusOne, 1> Eigen::HessenbergDecomposition< _MatrixType >::CoeffVectorType
Type for vector of Householder coefficients.
This is column vector with entries of type Scalar. The length of the vector is one less than the size of MatrixType, if it is a fixed-side type.
HouseholderSequenceType
template<typename _MatrixType > typedef HouseholderSequence<MatrixType,typename internal::remove_all<typename CoeffVectorType::ConjugateReturnType>::type> Eigen::HessenbergDecomposition< _MatrixType >::HouseholderSequenceType
Return type of matrixQ()
Index
template<typename _MatrixType > typedef Eigen::Index Eigen::HessenbergDecomposition< _MatrixType >::Index
MatrixHReturnType
template<typename _MatrixType > typedef internal::HessenbergDecompositionMatrixHReturnType<MatrixType> Eigen::HessenbergDecomposition< _MatrixType >::MatrixHReturnType
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::HessenbergDecomposition< _MatrixType >::MatrixType
Synonym for the template parameter _MatrixType.
RealScalar
template<typename _MatrixType > typedef NumTraits<Scalar>::Real Eigen::HessenbergDecomposition< _MatrixType >::RealScalar private
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::HessenbergDecomposition< _MatrixType >::Scalar
Scalar type for matrices of type MatrixType.
VectorType
template<typename _MatrixType > typedef Matrix<Scalar, 1, Size, Options | RowMajor, 1, MaxSize> Eigen::HessenbergDecomposition< _MatrixType >::VectorType private
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
Size
SizeMinusOne
Options
MaxSize
MaxSizeMinusOne
         {
      Size = MatrixType::RowsAtCompileTime,
      SizeMinusOne = Size == Dynamic ? Dynamic : Size - 1,
      Options = MatrixType::Options,
      MaxSize = MatrixType::MaxRowsAtCompileTime,
      MaxSizeMinusOne = MaxSize == Dynamic ? Dynamic : MaxSize - 1
    };
Constructor & Destructor Documentation
HessenbergDecomposition() [1/2]
template<typename _MatrixType > Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition (Index size = Size==Dynamic ? 2 : Size) inline explicit
Default constructor; the decomposition will be computed later.
Parameters
[in] size The size of the matrix whose Hessenberg decomposition will be computed.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See also
compute() for an example.
                                                                    : Size)
      : m_matrix(size,size),
        m_temp(size),
        m_isInitialized(false)
    {
      if(size>1)
        m_hCoeffs.resize(size-1);
    }
References Eigen::HessenbergDecomposition< _MatrixType >::m_hCoeffs, and Eigen::PlainObjectBase< Derived >::resize().
HessenbergDecomposition() [2/2]
template<typename _MatrixType > template<typename InputType > Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition (const EigenBase< InputType > & matrix) inline explicit
Constructor; computes Hessenberg decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Hessenberg decomposition is to be computed.
This constructor calls compute() to compute the Hessenberg decomposition.
See also
matrixH() for an example.
      : m_matrix(matrix.derived()),
        m_temp(matrix.rows()),
        m_isInitialized(false)
    {
      if(matrix.rows()<2)
      {
        m_isInitialized = true;
        return;
      }
      m_hCoeffs.resize(matrix.rows()-1,1);
      _compute(m_matrix, m_hCoeffs, m_temp);
      m_isInitialized = true;
    }
References Eigen::HessenbergDecomposition< _MatrixType >::_compute(), Eigen::HessenbergDecomposition< _MatrixType >::m_hCoeffs, Eigen::HessenbergDecomposition< _MatrixType >::m_isInitialized, Eigen::HessenbergDecomposition< _MatrixType >::m_matrix, Eigen::HessenbergDecomposition< _MatrixType >::m_temp, Eigen::PlainObjectBase< Derived >::resize(), and Eigen::EigenBase< Derived >::rows().
Member Function Documentation
_compute()
template<typename MatrixType > void Eigen::HessenbergDecomposition< MatrixType >::_compute (MatrixType & matA, CoeffVectorType & hCoeffs, VectorType & temp) static private
{
  eigen_assert(matA.rows()==matA.cols());
  Index n = matA.rows();
  temp.resize(n);
  for (Index i = 0; i<n-1; ++i)
  {
    // let's consider the vector v = i-th column starting at position i+1
    Index remainingSize = n-i-1;
    RealScalar beta;
    Scalar h;
    matA.col(i).tail(remainingSize).makeHouseholderInPlace(h, beta);
    matA.col(i).coeffRef(i+1) = beta;
    hCoeffs.coeffRef(i) = h;
    // Apply similarity transformation to remaining columns,
    // i.e., compute A = H A H'
    // A = H A
    matA.bottomRightCorner(remainingSize, remainingSize)
        .applyHouseholderOnTheLeft(matA.col(i).tail(remainingSize-1), h, &temp.coeffRef(0));
    // A = A H'
    matA.rightCols(remainingSize)
        .applyHouseholderOnTheRight(matA.col(i).tail(remainingSize-1).conjugate(), numext::conj(h), &temp.coeffRef(0));
  }
}
References Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::coeffRef(), eigen_assert, and Eigen::PlainObjectBase< Derived >::resize().
Referenced by Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition(), and Eigen::HessenbergDecomposition< _MatrixType >::compute().
compute()
template<typename _MatrixType > template<typename InputType > HessenbergDecomposition & Eigen::HessenbergDecomposition< _MatrixType >::compute (const EigenBase< InputType > & matrix) inline
Computes Hessenberg decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Hessenberg decomposition is to be computed.
Returns
Reference to *this
The Hessenberg decomposition is computed by bringing the columns of the matrix successively in the required form using Householder reflections (see, e.g., Algorithm 7.4.2 in Golub & Van Loan, Matrix Computations). The cost is flops, where denotes the size of the given matrix.
This method reuses of the allocated data in the HessenbergDecomposition object.
Example:
Output:
    {
      m_matrix = matrix.derived();
      if(matrix.rows()<2)
      {
        m_isInitialized = true;
        return *this;
      }
      m_hCoeffs.resize(matrix.rows()-1,1);
      _compute(m_matrix, m_hCoeffs, m_temp);
      m_isInitialized = true;
      return *this;
    }
References Eigen::HessenbergDecomposition< _MatrixType >::_compute(), Eigen::EigenBase< Derived >::derived(), Eigen::HessenbergDecomposition< _MatrixType >::m_hCoeffs, Eigen::HessenbergDecomposition< _MatrixType >::m_isInitialized, Eigen::HessenbergDecomposition< _MatrixType >::m_matrix, Eigen::HessenbergDecomposition< _MatrixType >::m_temp, Eigen::PlainObjectBase< Derived >::resize(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
householderCoefficients()
template<typename _MatrixType > const CoeffVectorType & Eigen::HessenbergDecomposition< _MatrixType >::householderCoefficients () const inline
Returns the Householder coefficients.
Returns
a const reference to the vector of Householder coefficients
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
The Householder coefficients allow the reconstruction of the matrix in the Hessenberg decomposition from the packed data.
See also
packedMatrix(), Householder module
    {
      eigen_assert(m_isInitialized && "HessenbergDecomposition is not initialized.");
      return m_hCoeffs;
    }
References eigen_assert, Eigen::HessenbergDecomposition< _MatrixType >::m_hCoeffs, and Eigen::HessenbergDecomposition< _MatrixType >::m_isInitialized.
matrixH()
template<typename _MatrixType > MatrixHReturnType Eigen::HessenbergDecomposition< _MatrixType >::matrixH () const inline
Constructs the Hessenberg matrix H in the decomposition.
Returns
expression object representing the matrix H
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
The object returned by this function constructs the Hessenberg matrix H when it is assigned to a matrix or otherwise evaluated. The matrix H is constructed from the packed matrix as returned by packedMatrix(): The upper part (including the subdiagonal) of the packed matrix contains the matrix H. It may sometimes be better to directly use the packed matrix instead of constructing the matrix H.
Example:
Output:
See also
matrixQ(), packedMatrix()
    {
      eigen_assert(m_isInitialized && "HessenbergDecomposition is not initialized.");
      return MatrixHReturnType(*this);
    }
References eigen_assert, and Eigen::HessenbergDecomposition< _MatrixType >::m_isInitialized.
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
matrixQ()
template<typename _MatrixType > HouseholderSequenceType Eigen::HessenbergDecomposition< _MatrixType >::matrixQ () const inline
Reconstructs the orthogonal matrix Q in the decomposition.
Returns
object representing the matrix Q
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
This function returns a light-weight object of template class HouseholderSequence. You can either apply it directly to a matrix or you can convert it to a matrix of type MatrixType.
See also
matrixH() for an example, class HouseholderSequence
    {
      eigen_assert(m_isInitialized && "HessenbergDecomposition is not initialized.");
      return HouseholderSequenceType(m_matrix, m_hCoeffs.conjugate())
             .setLength(m_matrix.rows() - 1)
             .setShift(1);
    }
References eigen_assert, Eigen::HessenbergDecomposition< _MatrixType >::m_hCoeffs, Eigen::HessenbergDecomposition< _MatrixType >::m_isInitialized, and Eigen::HessenbergDecomposition< _MatrixType >::m_matrix.
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
packedMatrix()
template<typename _MatrixType > const MatrixType & Eigen::HessenbergDecomposition< _MatrixType >::packedMatrix () const inline
Returns the internal representation of the decomposition.
Returns
a const reference to a matrix with the internal representation of the decomposition.
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
The returned matrix contains the following information:
the upper part and lower sub-diagonal represent the Hessenberg matrix H
the rest of the lower part contains the Householder vectors that, combined with Householder coefficients returned by householderCoefficients(), allows to reconstruct the matrix Q as . Here, the matrices are the Householder transformations where is the th Householder coefficient and is the Householder vector defined by with M the matrix returned by this function.
See LAPACK for further details on this packed storage.
Example:
Output:
See also
householderCoefficients()
    {
      eigen_assert(m_isInitialized && "HessenbergDecomposition is not initialized.");
      return m_matrix;
    }
References eigen_assert, Eigen::HessenbergDecomposition< _MatrixType >::m_isInitialized, and Eigen::HessenbergDecomposition< _MatrixType >::m_matrix.
Referenced by Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::cols(), Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::evalTo(), and Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::rows().
Member Data Documentation
m_hCoeffs
template<typename _MatrixType > CoeffVectorType Eigen::HessenbergDecomposition< _MatrixType >::m_hCoeffs protected
Referenced by Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< _MatrixType >::compute(), Eigen::HessenbergDecomposition< _MatrixType >::householderCoefficients(), and Eigen::HessenbergDecomposition< _MatrixType >::matrixQ().
m_isInitialized
template<typename _MatrixType > bool Eigen::HessenbergDecomposition< _MatrixType >::m_isInitialized protected
Referenced by Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< _MatrixType >::compute(), Eigen::HessenbergDecomposition< _MatrixType >::householderCoefficients(), Eigen::HessenbergDecomposition< _MatrixType >::matrixH(), Eigen::HessenbergDecomposition< _MatrixType >::matrixQ(), and Eigen::HessenbergDecomposition< _MatrixType >::packedMatrix().
m_matrix
template<typename _MatrixType > MatrixType Eigen::HessenbergDecomposition< _MatrixType >::m_matrix protected
Referenced by Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< _MatrixType >::compute(), Eigen::HessenbergDecomposition< _MatrixType >::matrixQ(), and Eigen::HessenbergDecomposition< _MatrixType >::packedMatrix().
m_temp
template<typename _MatrixType > VectorType Eigen::HessenbergDecomposition< _MatrixType >::m_temp protected
Referenced by Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition(), and Eigen::HessenbergDecomposition< _MatrixType >::compute().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h