Prusa Slicer: Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse > Struct Template Reference
Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse > Struct Template Reference
#include <src/eigen/Eigen/src/SparseCore/SparseSelfAdjointView.h>
Public Types
typedef DstXprType::StorageIndex StorageIndex
typedef internal::assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > AssignOpType
Static Public Member Functions
template<typename DestScalar , int StorageOrder>
static void run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > &dst, const SrcXprType &src, const AssignOpType &)
template<typename DestScalar , int StorageOrder, typename AssignFunc >
static void run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > &dst, const SrcXprType &src, const AssignFunc &func)
template<typename DestScalar , int StorageOrder>
static void run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > &dst, const SrcXprType &src, const internal::add_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
template<typename DestScalar , int StorageOrder>
static void run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > &dst, const SrcXprType &src, const internal::sub_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
template<typename DestScalar >
static void run (DynamicSparseMatrix< DestScalar, ColMajor, StorageIndex > &dst, const SrcXprType &src, const AssignOpType &)
Detailed Description
template<typename DstXprType, typename SrcXprType, typename Functor>
struct Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >
Member Typedef Documentation
AssignOpType
template<typename DstXprType , typename SrcXprType , typename Functor > typedef internal::assign_op<typename DstXprType::Scalar,typename SrcXprType::Scalar> Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::AssignOpType
StorageIndex
template<typename DstXprType , typename SrcXprType , typename Functor > typedef DstXprType::StorageIndex Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::StorageIndex
Member Function Documentation
run() [1/5]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DestScalar > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run (DynamicSparseMatrix< DestScalar, ColMajor, StorageIndex > & dst, const SrcXprType & src, const AssignOpType &) inline static
  {
    // TODO directly evaluate into dst;
    SparseMatrix<DestScalar,ColMajor,StorageIndex> tmp(dst.rows(),dst.cols());
    internal::permute_symm_to_fullsymm<SrcXprType::Mode>(src.matrix(), tmp);
    dst = tmp;
  }
References Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), and Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
run() [2/5]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DestScalar , int StorageOrder, typename AssignFunc > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > & dst, const SrcXprType & src, const AssignFunc & func) inline static
  {
    SparseMatrix<DestScalar,StorageOrder,StorageIndex> tmp(src.rows(),src.cols());
    run(tmp, src, AssignOpType());
    call_assignment_no_alias_no_transpose(dst, tmp, func);
  }
References Eigen::internal::call_assignment_no_alias_no_transpose().
run() [3/5]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DestScalar , int StorageOrder> static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > & dst, const SrcXprType & src, const AssignOpType &) inline static
  {
    internal::permute_symm_to_fullsymm<SrcXprType::Mode>(src.matrix(), dst);
  }
run() [4/5]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DestScalar , int StorageOrder> static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > & dst, const SrcXprType & src, const internal::add_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
  {
    SparseMatrix<DestScalar,StorageOrder,StorageIndex> tmp(src.rows(),src.cols());
    run(tmp, src, AssignOpType());
    dst += tmp;
  }
run() [5/5]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DestScalar , int StorageOrder> static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > & dst, const SrcXprType & src, const internal::sub_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
  {
    SparseMatrix<DestScalar,StorageOrder,StorageIndex> tmp(src.rows(),src.cols());
    run(tmp, src, AssignOpType());
    dst -= tmp;
  }
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseSelfAdjointView.h