Prusa Slicer: Slic3r::Extruder Class Reference
Slic3r::Extruder Class Reference
#include <src/libslic3r/Extruder.hpp>
Public Member Functions
Extruder (unsigned int id, GCodeConfig *config)
~Extruder ()=default
unsigned int id () const
std::pair< double, double > extrude (double dE)
std::pair< double, double > retract (double retract_length, double restart_extra)
std::pair< double, double > unretract ()
double retract_to_go (double retract_length) const
bool reset_E ()
double e_per_mm (double mm3_per_mm) const
double e_per_mm3 () const
double extruded_volume () const
double used_filament () const
double position () const
double retracted () const
double restart_extra () const
void set_position (double e)
void set_retracted (double retracted, double restart_extra)
double filament_diameter () const
double filament_crossection () const
double filament_density () const
double filament_cost () const
double extrusion_multiplier () const
double retract_before_wipe () const
double retract_length () const
double retract_lift () const
int retract_speed () const
int deretract_speed () const
double retract_restart_extra () const
double retract_length_toolchange () const
double retract_restart_extra_toolchange () const
Private Member Functions
Extruder (unsigned int id)
Private Attributes
GCodeConfig * m_config
unsigned int m_id
double m_E { 0 }
double m_absolute_E { 0 }
double m_retracted { 0 }
double m_restart_extra { 0 }
double m_e_per_mm3
Detailed Description
Constructor & Destructor Documentation
Extruder() [1/2]
Slic3r::Extruder::Extruder (unsigned int id, GCodeConfig * config)
                                                       :
    m_id(id),
    m_config(config)
{
    // cache values that are going to be called often
    m_e_per_mm3 = this->extrusion_multiplier();
    if (! m_config->use_volumetric_e)
        m_e_per_mm3 /= this->filament_crossection();
}
References extrusion_multiplier(), filament_crossection(), m_config, and m_e_per_mm3.
~Extruder()
Slic3r::Extruder::~Extruder () default
Extruder() [2/2]
Slic3r::Extruder::Extruder (unsigned int id) inline private
: m_id(id) {}
Member Function Documentation
deretract_speed()
int Slic3r::Extruder::deretract_speed () const
{
    int speed = int(floor(m_config->deretract_speed.get_at(m_id)+0.5));
    return (speed > 0) ? speed : this->retract_speed();
}
References floor(), m_config, m_id, and retract_speed().
Referenced by Slic3r::GCodeWriter::unretract().
e_per_mm()
double Slic3r::Extruder::e_per_mm (double mm3_per_mm) const inline
{ return mm3_per_mm * m_e_per_mm3; }
References m_e_per_mm3.
Referenced by Slic3r::Print::_make_skirt().
e_per_mm3()
double Slic3r::Extruder::e_per_mm3 () const inline
{ return m_e_per_mm3; }
References m_e_per_mm3.
Referenced by Slic3r::GCode::_extrude().
extrude()
std::pair< double, double > Slic3r::Extruder::extrude (double dE)
{
    // in case of relative E distances we always reset to 0 before any output
    if (m_config->use_relative_e_distances)
        m_E = 0.;
    // Quantize extruder delta to G-code resolution.
    dE = GCodeFormatter::quantize_e(dE);
    m_E          += dE;
    m_absolute_E += dE;
    if (dE < 0.)
        m_retracted -= dE;
    return std::make_pair(dE, m_E);
}
References m_absolute_E, m_config, m_E, m_retracted, and Slic3r::GCodeFormatter::quantize_e().
Referenced by Slic3r::GCodeWriter::extrude_to_xy(), and unretract().
extruded_volume()
double Slic3r::Extruder::extruded_volume () const
{
    return m_config->use_volumetric_e ?
        m_absolute_E + m_retracted :
        this->used_filament() * this->filament_crossection();
}
References filament_crossection(), m_absolute_E, m_config, m_retracted, and used_filament().
Referenced by used_filament().
extrusion_multiplier()
double Slic3r::Extruder::extrusion_multiplier () const
{
    return m_config->extrusion_multiplier.get_at(m_id);
}
References m_config, and m_id.
Referenced by Extruder().
filament_cost()
double Slic3r::Extruder::filament_cost () const
{
    return m_config->filament_cost.get_at(m_id);
}
References m_config, and m_id.
filament_crossection()
double Slic3r::Extruder::filament_crossection () const inline
{ return this->filament_diameter() * this->filament_diameter() * 0.25 * PI; }
References filament_diameter(), and PI.
Referenced by Extruder(), extruded_volume(), and used_filament().
filament_density()
double Slic3r::Extruder::filament_density () const
{
    return m_config->filament_density.get_at(m_id);
}
References m_config, and m_id.
filament_diameter()
double Slic3r::Extruder::filament_diameter () const
{
    return m_config->filament_diameter.get_at(m_id);
}
References m_config, and m_id.
Referenced by Slic3r::GCodeWriter::_retract(), and filament_crossection().
id()
unsigned int Slic3r::Extruder::id () const inline
{ return m_id; }
References m_id.
Referenced by Slic3r::GCode::_do_export(), Slic3r::GCode::_extrude(), Slic3r::OozePrevention::_get_temp(), Slic3r::GCodeWriter::lift(), Slic3r::GCodeWriter::need_toolchange(), Slic3r::need_wipe(), Slic3r::operator!=(), Slic3r::operator<(), Slic3r::operator==(), Slic3r::operator>(), Slic3r::OozePrevention::post_toolchange(), Slic3r::OozePrevention::pre_toolchange(), Slic3r::GCode::process_layer(), and Slic3r::GCode::set_extruder().
position()
double Slic3r::Extruder::position () const inline
{ return m_E; }
References m_E.
reset_E()
bool Slic3r::Extruder::reset_E () inline
{ bool modified = m_E != 0; m_E = 0.; return modified; }
References m_E.
Referenced by Slic3r::GCodeWriter::reset_e().
restart_extra()
double Slic3r::Extruder::restart_extra () const inline
{ return m_restart_extra; }
References m_restart_extra.
Referenced by retract(), and set_retracted().
retract()
std::pair< double, double > Slic3r::Extruder::retract (double retract_length, double restart_extra)
{
    assert(restart_extra >= 0);
    // in case of relative E distances we always reset to 0 before any output
    if (m_config->use_relative_e_distances)
        m_E = 0.;
    // Quantize extruder delta to G-code resolution.
    double to_retract = this->retract_to_go(retract_length);
    if (to_retract > 0.) {
        m_E             -= to_retract;
        m_absolute_E    -= to_retract;
        m_retracted     += to_retract;
        m_restart_extra  = restart_extra;
    }
    return std::make_pair(to_retract, m_E);
}
References m_absolute_E, m_config, m_E, m_restart_extra, m_retracted, restart_extra(), and retract_to_go().
Referenced by Slic3r::GCodeWriter::_retract().
retract_before_wipe()
double Slic3r::Extruder::retract_before_wipe () const
{
    return std::min(1., std::max(0., m_config->retract_before_wipe.get_at(m_id) * 0.01));
}
References m_config, and m_id.
Referenced by Slic3r::GCodeWriter::retract(), and Slic3r::GCodeWriter::retract_for_toolchange().
retract_length()
double Slic3r::Extruder::retract_length () const
{
    return m_config->retract_length.get_at(m_id);
}
References m_config, and m_id.
Referenced by Slic3r::GCodeWriter::retract(), Slic3r::GCode::retract(), retract_to_go(), and Slic3r::Wipe::wipe().
retract_length_toolchange()
double Slic3r::Extruder::retract_length_toolchange () const
{
    return m_config->retract_length_toolchange.get_at(m_id);
}
References m_config, and m_id.
Referenced by Slic3r::GCodeWriter::retract_for_toolchange(), and Slic3r::Wipe::wipe().
retract_lift()
double Slic3r::Extruder::retract_lift () const
{
    return m_config->retract_lift.get_at(m_id);
}
References m_config, and m_id.
retract_restart_extra()
double Slic3r::Extruder::retract_restart_extra () const
{
    return m_config->retract_restart_extra.get_at(m_id);
}
References m_config, and m_id.
Referenced by Slic3r::GCodeWriter::retract().
retract_restart_extra_toolchange()
double Slic3r::Extruder::retract_restart_extra_toolchange () const
{
    return m_config->retract_restart_extra_toolchange.get_at(m_id);
}
References m_config, and m_id.
Referenced by Slic3r::GCodeWriter::retract_for_toolchange().
retract_speed()
int Slic3r::Extruder::retract_speed () const
{
    return int(floor(m_config->retract_speed.get_at(m_id)+0.5));
}
References floor(), m_config, and m_id.
Referenced by Slic3r::GCodeWriter::_retract(), deretract_speed(), and Slic3r::Wipe::wipe().
retract_to_go()
double Slic3r::Extruder::retract_to_go (double retract_length) const
{
    return std::max(0., GCodeFormatter::quantize_e(retract_length - m_retracted));
}
References m_retracted, Slic3r::GCodeFormatter::quantize_e(), and retract_length().
Referenced by retract(), and Slic3r::Wipe::wipe().
retracted()
double Slic3r::Extruder::retracted () const inline
{ return m_retracted; }
References m_retracted.
Referenced by set_retracted().
set_position()
void Slic3r::Extruder::set_position (double e) inline
{ m_E = e; }
References m_E.
set_retracted()
void Slic3r::Extruder::set_retracted (double retracted, double restart_extra)
{
    if (retracted < - EPSILON)
        throw Slic3r::RuntimeError("Custom G-code reports negative z_retracted.");
    if (restart_extra < - EPSILON)
        throw Slic3r::RuntimeError("Custom G-code reports negative z_restart_extra.");
    if (retracted > EPSILON) {
        m_retracted     = retracted;
        m_restart_extra = restart_extra < EPSILON ? 0 : restart_extra;
    } else {
        m_retracted     = 0;
        m_restart_extra = 0;
    }
}
References EPSILON, m_restart_extra, m_retracted, restart_extra(), and retracted().
Referenced by Slic3r::GCode::placeholder_parser_process().
unretract()
std::pair< double, double > Slic3r::Extruder::unretract ()
{
    auto [dE, emitE] = this->extrude(m_retracted + m_restart_extra);
    m_retracted     = 0.;
    m_restart_extra = 0.;
    return std::make_pair(dE, emitE);
}
References extrude(), m_restart_extra, and m_retracted.
Referenced by Slic3r::GCodeWriter::unretract().
used_filament()
double Slic3r::Extruder::used_filament () const
{
    return m_config->use_volumetric_e ?
        this->extruded_volume() / this->filament_crossection() :
        m_absolute_E + m_retracted;
}
References extruded_volume(), filament_crossection(), m_absolute_E, m_config, and m_retracted.
Referenced by extruded_volume().
Member Data Documentation
m_absolute_E
double Slic3r::Extruder::m_absolute_E { 0 } private
Referenced by extrude(), extruded_volume(), retract(), and used_filament().
m_config
GCodeConfig* Slic3r::Extruder::m_config private
Referenced by Extruder(), deretract_speed(), extrude(), extruded_volume(), extrusion_multiplier(), filament_cost(), filament_density(), filament_diameter(), retract(), retract_before_wipe(), retract_length(), retract_length_toolchange(), retract_lift(), retract_restart_extra(), retract_restart_extra_toolchange(), retract_speed(), and used_filament().
m_E
double Slic3r::Extruder::m_E { 0 } private
Referenced by extrude(), position(), reset_E(), retract(), and set_position().
m_e_per_mm3
double Slic3r::Extruder::m_e_per_mm3 private
Referenced by Extruder(), e_per_mm(), and e_per_mm3().
m_id
unsigned int Slic3r::Extruder::m_id private
Referenced by deretract_speed(), extrusion_multiplier(), filament_cost(), filament_density(), filament_diameter(), id(), retract_before_wipe(), retract_length(), retract_length_toolchange(), retract_lift(), retract_restart_extra(), retract_restart_extra_toolchange(), and retract_speed().
m_restart_extra
double Slic3r::Extruder::m_restart_extra { 0 } private
Referenced by restart_extra(), retract(), set_retracted(), and unretract().
m_retracted
double Slic3r::Extruder::m_retracted { 0 } private
Referenced by extrude(), extruded_volume(), retract(), retract_to_go(), retracted(), set_retracted(), unretract(), and used_filament().
The documentation for this class was generated from the following files:
src/libslic3r/Extruder.hpp
src/libslic3r/Extruder.cpp