Prusa Slicer: Eigen::DiagonalWrapper< _DiagonalVectorType > Class Template Reference
Eigen::DiagonalWrapper< _DiagonalVectorType > Class Template Reference
Expression of a diagonal matrix.
#include <src/eigen/Eigen/src/Core/DiagonalMatrix.h>
Public Types
typedef _DiagonalVectorType DiagonalVectorType
typedef DiagonalWrapper Nested
enum
typedef DiagonalVectorType::Scalar Scalar
typedef DiagonalVectorType::RealScalar RealScalar
typedef internal::traits< DiagonalWrapper< _DiagonalVectorType > >::StorageKind StorageKind
typedef internal::traits< DiagonalWrapper< _DiagonalVectorType > >::StorageIndex StorageIndex
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType DenseType
typedef DiagonalMatrix< Scalar, DiagonalVectorType::SizeAtCompileTime, DiagonalVectorType::MaxSizeAtCompileTime > PlainObject
typedef DiagonalWrapper< const CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const DiagonalVectorType > > InverseReturnType
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
EIGEN_DEVICE_FUNC DiagonalWrapper (DiagonalVectorType &a_diagonal)
EIGEN_DEVICE_FUNC const DiagonalVectorType & diagonal () const
EIGEN_DEVICE_FUNC const DiagonalWrapper< _DiagonalVectorType > & derived () const
EIGEN_DEVICE_FUNC DiagonalWrapper< _DiagonalVectorType > & derived ()
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
EIGEN_DEVICE_FUNC DiagonalVectorType & diagonal ()
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC const Product< DiagonalWrapper< _DiagonalVectorType >, MatrixDerived, LazyProduct > operator* (const MatrixBase< MatrixDerived > &matrix) const
EIGEN_DEVICE_FUNC const DiagonalWrapper< const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(DiagonalVectorType, Scalar, product) > operator* (const Scalar &scalar) const
EIGEN_DEVICE_FUNC const InverseReturnType inverse () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Attributes
DiagonalVectorType::Nested m_diagonal
Detailed Description
template<typename _DiagonalVectorType>
class Eigen::DiagonalWrapper< _DiagonalVectorType >
Expression of a diagonal matrix.
Parameters
_DiagonalVectorType the type of the vector of diagonal coefficients
This class is an expression of a diagonal matrix, but not storing its own vector of diagonal coefficients, instead wrapping an existing vector expression. It is the return type of MatrixBase::asDiagonal() and most of the time this is the only way that it is used.
See also
class DiagonalMatrix, class DiagonalBase, MatrixBase::asDiagonal()
Member Typedef Documentation
DenseMatrixType
typedef Matrix<Scalar, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::DenseMatrixType inherited
DenseType
typedef DenseMatrixType Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::DenseType inherited
DiagonalVectorType
template<typename _DiagonalVectorType > typedef _DiagonalVectorType Eigen::DiagonalWrapper< _DiagonalVectorType >::DiagonalVectorType
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
InverseReturnType
typedef DiagonalWrapper<const CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const DiagonalVectorType> > Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::InverseReturnType inherited
Nested
template<typename _DiagonalVectorType > typedef DiagonalWrapper Eigen::DiagonalWrapper< _DiagonalVectorType >::Nested
PlainObject
typedef DiagonalMatrix<Scalar,DiagonalVectorType::SizeAtCompileTime,DiagonalVectorType::MaxSizeAtCompileTime> Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::PlainObject inherited
RealScalar
typedef DiagonalVectorType::RealScalar Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::RealScalar inherited
Scalar
typedef DiagonalVectorType::Scalar Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::Scalar inherited
StorageIndex
typedef internal::traits<DiagonalWrapper< _DiagonalVectorType > >::StorageIndex Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::StorageIndex inherited
StorageKind
typedef internal::traits<DiagonalWrapper< _DiagonalVectorType > >::StorageKind Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::StorageKind inherited
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
         {
      RowsAtCompileTime = DiagonalVectorType::SizeAtCompileTime,
      ColsAtCompileTime = DiagonalVectorType::SizeAtCompileTime,
      MaxRowsAtCompileTime = DiagonalVectorType::MaxSizeAtCompileTime,
      MaxColsAtCompileTime = DiagonalVectorType::MaxSizeAtCompileTime,
      IsVectorAtCompileTime = 0,
      Flags = NoPreferredStorageOrderBit
    };
Constructor & Destructor Documentation
DiagonalWrapper()
template<typename _DiagonalVectorType > EIGEN_DEVICE_FUNC Eigen::DiagonalWrapper< _DiagonalVectorType >::DiagonalWrapper (DiagonalVectorType & a_diagonal) inline explicit
Constructor from expression of diagonal coefficients to wrap.
: m_diagonal(a_diagonal) {}
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
cols()
EIGEN_DEVICE_FUNC Index Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::cols () const inline inherited
{ return diagonal().size(); }
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
EIGEN_DEVICE_FUNC DiagonalWrapper< _DiagonalVectorType > & Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::derived () inline inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
EIGEN_DEVICE_FUNC const DiagonalWrapper< _DiagonalVectorType > & Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::derived () const inline inherited
{ return *static_cast<const Derived*>(this); }
diagonal() [1/2]
EIGEN_DEVICE_FUNC DiagonalVectorType & Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::diagonal () inline inherited
{ return derived().diagonal(); }
diagonal() [2/2]
template<typename _DiagonalVectorType > EIGEN_DEVICE_FUNC const DiagonalVectorType & Eigen::DiagonalWrapper< _DiagonalVectorType >::diagonal () const inline
Returns
a const reference to the wrapped expression of diagonal coefficients.
{ return m_diagonal; }
References Eigen::DiagonalWrapper< _DiagonalVectorType >::m_diagonal.
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
Referenced by Eigen::EigenBase< Derived >::subTo().
inverse()
EIGEN_DEVICE_FUNC const InverseReturnType Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::inverse () const inline inherited
    {
      return InverseReturnType(diagonal().cwiseInverse());
    }
operator*() [1/2]
EIGEN_DEVICE_FUNC const Product< DiagonalWrapper< _DiagonalVectorType > , MatrixDerived, LazyProduct > Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::operator* (const MatrixBase< MatrixDerived > & matrix) const inline inherited
    {
      return Product<Derived, MatrixDerived, LazyProduct>(derived(),matrix.derived());
    }
operator*() [2/2]
EIGEN_DEVICE_FUNC const DiagonalWrapper< const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(DiagonalVectorType, Scalar, product) > Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::operator* (const Scalar & scalar) const inline inherited
    {
      return DiagonalWrapper<const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(DiagonalVectorType,Scalar,product) >(diagonal() * scalar);
    }
rows()
EIGEN_DEVICE_FUNC Index Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::rows () const inline inherited
{ return diagonal().size(); }
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
References Eigen::EigenBase< Derived >::cols(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
toDenseMatrix()
EIGEN_DEVICE_FUNC DenseMatrixType Eigen::DiagonalBase< DiagonalWrapper< _DiagonalVectorType > >::toDenseMatrix () const inline inherited
{ return derived(); }
Member Data Documentation
m_diagonal
template<typename _DiagonalVectorType > DiagonalVectorType::Nested Eigen::DiagonalWrapper< _DiagonalVectorType >::m_diagonal protected
Referenced by Eigen::DiagonalWrapper< _DiagonalVectorType >::diagonal().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/DiagonalMatrix.h