Prusa Slicer: Eigen::internal::UpperBidiagonalization< _MatrixType > Class Template Reference
Eigen::internal::UpperBidiagonalization< _MatrixType > Class Template Reference
#include <src/eigen/Eigen/src/SVD/UpperBidiagonalization.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , ColsAtCompileTimeMinusOne = internal::decrement_size<ColsAtCompileTime>::ret }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef Eigen::Index Index
typedef Matrix< Scalar, 1, ColsAtCompileTime > RowVectorType
typedef Matrix< Scalar, RowsAtCompileTime, 1 > ColVectorType
typedef BandMatrix< RealScalar, ColsAtCompileTime, ColsAtCompileTime, 1, 0, RowMajor > BidiagonalType
typedef Matrix< Scalar, ColsAtCompileTime, 1 > DiagVectorType
typedef Matrix< Scalar, ColsAtCompileTimeMinusOne, 1 > SuperDiagVectorType
typedef HouseholderSequence< const MatrixType, const typename internal::remove_all< typename Diagonal< const MatrixType, 0 >::ConjugateReturnType >::type > HouseholderUSequenceType
typedef HouseholderSequence< const typename internal::remove_all< typename MatrixType::ConjugateReturnType >::type, Diagonal< const MatrixType, 1 >, OnTheRight > HouseholderVSequenceType
Public Member Functions
UpperBidiagonalization ()
Default Constructor.
UpperBidiagonalization (const MatrixType &matrix)
UpperBidiagonalization & compute (const MatrixType &matrix)
UpperBidiagonalization & computeUnblocked (const MatrixType &matrix)
const MatrixType & householder () const
const BidiagonalType & bidiagonal () const
const HouseholderUSequenceType householderU () const
const HouseholderVSequenceType householderV ()
Protected Attributes
MatrixType m_householder
BidiagonalType m_bidiagonal
bool m_isInitialized
Detailed Description
template<typename _MatrixType>
class Eigen::internal::UpperBidiagonalization< _MatrixType >
Member Typedef Documentation
BidiagonalType
template<typename _MatrixType > typedef BandMatrix<RealScalar, ColsAtCompileTime, ColsAtCompileTime, 1, 0, RowMajor> Eigen::internal::UpperBidiagonalization< _MatrixType >::BidiagonalType
ColVectorType
template<typename _MatrixType > typedef Matrix<Scalar, RowsAtCompileTime, 1> Eigen::internal::UpperBidiagonalization< _MatrixType >::ColVectorType
DiagVectorType
template<typename _MatrixType > typedef Matrix<Scalar, ColsAtCompileTime, 1> Eigen::internal::UpperBidiagonalization< _MatrixType >::DiagVectorType
HouseholderUSequenceType
template<typename _MatrixType > typedef HouseholderSequence< const MatrixType, const typename internal::remove_all<typename Diagonal<const MatrixType,0>::ConjugateReturnType>::type > Eigen::internal::UpperBidiagonalization< _MatrixType >::HouseholderUSequenceType
HouseholderVSequenceType
template<typename _MatrixType > typedef HouseholderSequence< const typename internal::remove_all<typename MatrixType::ConjugateReturnType>::type, Diagonal<const MatrixType,1>, OnTheRight > Eigen::internal::UpperBidiagonalization< _MatrixType >::HouseholderVSequenceType
Index
template<typename _MatrixType > typedef Eigen::Index Eigen::internal::UpperBidiagonalization< _MatrixType >::Index
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::internal::UpperBidiagonalization< _MatrixType >::MatrixType
RealScalar
template<typename _MatrixType > typedef MatrixType::RealScalar Eigen::internal::UpperBidiagonalization< _MatrixType >::RealScalar
RowVectorType
template<typename _MatrixType > typedef Matrix<Scalar, 1, ColsAtCompileTime> Eigen::internal::UpperBidiagonalization< _MatrixType >::RowVectorType
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::internal::UpperBidiagonalization< _MatrixType >::Scalar
SuperDiagVectorType
template<typename _MatrixType > typedef Matrix<Scalar, ColsAtCompileTimeMinusOne, 1> Eigen::internal::UpperBidiagonalization< _MatrixType >::SuperDiagVectorType
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
ColsAtCompileTimeMinusOne
         {
      RowsAtCompileTime = MatrixType::RowsAtCompileTime,
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      ColsAtCompileTimeMinusOne = internal::decrement_size<ColsAtCompileTime>::ret
    };
Constructor & Destructor Documentation
UpperBidiagonalization() [1/2]
template<typename _MatrixType > Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via Bidiagonalization::compute(const MatrixType&).
: m_householder(), m_bidiagonal(), m_isInitialized(false) {}
UpperBidiagonalization() [2/2]
template<typename _MatrixType > Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization (const MatrixType & matrix) inline explicit
      : m_householder(matrix.rows(), matrix.cols()),
        m_bidiagonal(matrix.cols(), matrix.cols()),
        m_isInitialized(false)
    {
      compute(matrix);
    }
References Eigen::internal::UpperBidiagonalization< _MatrixType >::compute().
Member Function Documentation
bidiagonal()
template<typename _MatrixType > const BidiagonalType & Eigen::internal::UpperBidiagonalization< _MatrixType >::bidiagonal () const inline
{ return m_bidiagonal; }
References Eigen::internal::UpperBidiagonalization< _MatrixType >::m_bidiagonal.
Referenced by Eigen::BDCSVD< _MatrixType >::compute().
compute()
template<typename _MatrixType > UpperBidiagonalization< _MatrixType > & Eigen::internal::UpperBidiagonalization< _MatrixType >::compute (const MatrixType & matrix)
{
  Index rows = matrix.rows();
  Index cols = matrix.cols();
  EIGEN_ONLY_USED_FOR_DEBUG(rows);
  EIGEN_ONLY_USED_FOR_DEBUG(cols);
  eigen_assert(rows >= cols && "UpperBidiagonalization is only for Arices satisfying rows>=cols.");
  m_householder = matrix;
  upperbidiagonalization_inplace_blocked(m_householder, m_bidiagonal);
  m_isInitialized = true;
  return *this;
}
References eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and Eigen::internal::upperbidiagonalization_inplace_blocked().
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization().
computeUnblocked()
template<typename _MatrixType > UpperBidiagonalization< _MatrixType > & Eigen::internal::UpperBidiagonalization< _MatrixType >::computeUnblocked (const MatrixType & matrix)
{
  Index rows = matrix.rows();
  Index cols = matrix.cols();
  EIGEN_ONLY_USED_FOR_DEBUG(cols);
  eigen_assert(rows >= cols && "UpperBidiagonalization is only for Arices satisfying rows>=cols.");
  m_householder = matrix;
  ColVectorType temp(rows);
  upperbidiagonalization_inplace_unblocked(m_householder,
                                           &(m_bidiagonal.template diagonal<0>().coeffRef(0)),
                                           &(m_bidiagonal.template diagonal<1>().coeffRef(0)),
                                           temp.data());
  m_isInitialized = true;
  return *this;
}
References Eigen::PlainObjectBase< Derived >::data(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and Eigen::internal::upperbidiagonalization_inplace_unblocked().
householder()
template<typename _MatrixType > const MatrixType & Eigen::internal::UpperBidiagonalization< _MatrixType >::householder () const inline
{ return m_householder; }
References Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder.
householderU()
template<typename _MatrixType > const HouseholderUSequenceType Eigen::internal::UpperBidiagonalization< _MatrixType >::householderU () const inline
    {
      eigen_assert(m_isInitialized && "UpperBidiagonalization is not initialized.");
      return HouseholderUSequenceType(m_householder, m_householder.diagonal().conjugate());
    }
References eigen_assert, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder, and Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized.
Referenced by Eigen::BDCSVD< _MatrixType >::compute().
householderV()
template<typename _MatrixType > const HouseholderVSequenceType Eigen::internal::UpperBidiagonalization< _MatrixType >::householderV () inline
    {
      eigen_assert(m_isInitialized && "UpperBidiagonalization is not initialized.");
      return HouseholderVSequenceType(m_householder.conjugate(), m_householder.const_derived().template diagonal<1>())
             .setLength(m_householder.cols()-1)
             .setShift(1);
    }
References eigen_assert, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder, and Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized.
Referenced by Eigen::BDCSVD< _MatrixType >::compute().
Member Data Documentation
m_bidiagonal
template<typename _MatrixType > BidiagonalType Eigen::internal::UpperBidiagonalization< _MatrixType >::m_bidiagonal protected
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::bidiagonal().
m_householder
template<typename _MatrixType > MatrixType Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder protected
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::householder(), Eigen::internal::UpperBidiagonalization< _MatrixType >::householderU(), and Eigen::internal::UpperBidiagonalization< _MatrixType >::householderV().
m_isInitialized
template<typename _MatrixType > bool Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized protected
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::householderU(), and Eigen::internal::UpperBidiagonalization< _MatrixType >::householderV().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SVD/UpperBidiagonalization.h