Prusa Slicer: src/avrdude/arduino.h File Reference
arduino.h File Reference
Functions
void arduino_initpgm (PROGRAMMER *pgm)
Variables
const char arduino_desc []
Function Documentation
arduino_initpgm()
void arduino_initpgm (PROGRAMMER * pgm)
{
  /* This is mostly a STK500; just the signature is read
     differently than on real STK500v1
     and the DTR signal is set when opening the serial port
     for the Auto-Reset feature */
  stk500_initpgm(pgm);
  strcpy(pgm->type, "Arduino");
  pgm->read_sig_bytes = arduino_read_sig_bytes;
  pgm->open = arduino_open;
  pgm->close = arduino_close;
}
References arduino_close(), arduino_open(), arduino_read_sig_bytes(), programmer_t::close, programmer_t::open, pgm, programmer_t::read_sig_bytes, stk500_initpgm(), and programmer_t::type.
Variable Documentation
arduino_desc
const char arduino_desc[] extern