Prusa Slicer: Slic3r::Search Namespace Reference
Slic3r::Search Namespace Reference
Classes
struct FoundOption
struct GroupAndCategory
struct InputInfo
struct Option
class OptionsSearcher
struct OptionViewParameters
class SearchDialog
class SearchListModel
Functions
static char marker_by_type (Preset::Type type, PrinterTechnology pt)
template<class T >
void change_opt_key (std::string &opt_key, DynamicPrintConfig *config, int &cnt)
static std::string get_key (const std::string &opt_key, Preset::Type type)
static std::wstring mark_string (const std::wstring &str, const std::vector< uint16_t > &matches, Preset::Type type, PrinterTechnology pt)
static bool fuzzy_match (const std::wstring &search_pattern, const std::wstring &label, int &out_score, std::vector< uint16_t > &out_matches)
static Option create_option (const std::string &opt_key, const wxString &label, Preset::Type type, const GroupAndCategory &gc)
Variables
static const std::map< const char, int > icon_idxs
Class Documentation
Slic3r::Search::GroupAndCategory
struct Slic3r::Search::GroupAndCategory
Class Members
wxString category
wxString group
Slic3r::Search::InputInfo
struct Slic3r::Search::InputInfo
Class Members
DynamicPrintConfig * config {nullptr}
Type type {Preset::TYPE_INVALID}
Slic3r::Search::OptionViewParameters
struct Slic3r::Search::OptionViewParameters
Class Members
bool category {false}
bool english {false}
int hovered_id {0}
Function Documentation
change_opt_key()
template<class T > void Slic3r::Search::change_opt_key (std::string & opt_key, DynamicPrintConfig * config, int & cnt)
{
    T* opt_cur = static_cast<T*>(config->option(opt_key));
    cnt = opt_cur->values.size();
    return;
    if (opt_cur->values.size() > 0)
        opt_key += "#" + std::to_string(0);
}
References Slic3r::ConfigBase::option().
create_option()
static Option Slic3r::Search::create_option (const std::string & opt_key, const wxString & label, Preset::Type type, const GroupAndCategory & gc) static
{
    wxString suffix;
    wxString suffix_local;
    if (gc.category == "Machine limits") {
        suffix = opt_key.back() == '1' ? L("Stealth") : L("Normal");
        suffix_local = " " + _(suffix);
        suffix = " " + suffix;
    }
    wxString category = gc.category;
    if (type == Preset::TYPE_PRINTER && category.Contains("Extruder ")) {
        std::string opt_idx = opt_key.substr(opt_key.find("#") + 1);
        category = wxString::Format("%s %d", "Extruder", atoi(opt_idx.c_str()) + 1);
    }
    return Option{ boost::nowide::widen(get_key(opt_key, type)), type,
                (label + suffix).ToStdWstring(), (_(label) + suffix_local).ToStdWstring(),
                gc.group.ToStdWstring(), _(gc.group).ToStdWstring(),
                gc.category.ToStdWstring(), GUI::Tab::translate_category(category, type).ToStdWstring() };
}
References _, Slic3r::Search::GroupAndCategory::category, get_key(), Slic3r::Search::GroupAndCategory::group, L, Slic3r::GUI::Tab::translate_category(), Slic3r::Preset::TYPE_PRINTER, and boost::nowide::widen().
Referenced by Slic3r::Search::OptionsSearcher::get_option().
fuzzy_match()
static bool Slic3r::Search::fuzzy_match (const std::wstring & search_pattern, const std::wstring & label, int & out_score, std::vector< uint16_t > & out_matches) static
{
    uint16_t matches[fts::max_matches + 1]; // +1 for the stopper
    int score;
    if (fts::fuzzy_match(search_pattern.c_str(), label.c_str(), score, matches)) {
      size_t cnt = 0;
      for (; matches[cnt] != fts::stopper; ++cnt);
      out_matches.assign(matches, matches + cnt);
    out_score = score;
    return true;
  } else
    return false;
}
References fts::fuzzy_match(), fts::max_matches, and fts::stopper.
Referenced by Slic3r::Search::OptionsSearcher::search().
get_key()
static std::string Slic3r::Search::get_key (const std::string & opt_key, Preset::Type type) static
{
    return std::to_string(int(type)) + ";" + opt_key;
}
Referenced by Slic3r::Search::OptionsSearcher::add_key(), Slic3r::Search::OptionsSearcher::append_options(), Slic3r::Search::OptionsSearcher::append_preferences_option(), create_option(), Slic3r::Search::OptionsSearcher::get_option(), and Slic3r::Search::OptionsSearcher::get_option().
mark_string()
static std::wstring Slic3r::Search::mark_string (const std::wstring & str, const std::vector< uint16_t > & matches, Preset::Type type, PrinterTechnology pt) static
{
  std::wstring out;
    out += marker_by_type(type, pt);
  if (matches.empty())
    out += str;
  else {
    out.reserve(str.size() * 2);
    if (matches.front() > 0)
      out += str.substr(0, matches.front());
    for (size_t i = 0;;) {
      // Find the longest string of successive indices.
      size_t j = i + 1;
            while (j < matches.size() && matches[j] == matches[j - 1] + 1)
                ++ j;
            out += ImGui::ColorMarkerStart;
            out += str.substr(matches[i], matches[j - 1] - matches[i] + 1);
            out += ImGui::ColorMarkerEnd;
            if (j == matches.size()) {
        out += str.substr(matches[j - 1] + 1);
        break;
      }
            out += str.substr(matches[j - 1] + 1, matches[j] - matches[j - 1] - 1);
            i = j;
    }
  }
  return out;
}
References ImGui::ColorMarkerEnd, ImGui::ColorMarkerStart, and marker_by_type().
Referenced by Slic3r::Search::OptionsSearcher::search().
marker_by_type()
static char Slic3r::Search::marker_by_type (Preset::Type type, PrinterTechnology pt) static
{
    switch(type) {
    case Preset::TYPE_PRINT:
    case Preset::TYPE_SLA_PRINT:
        return ImGui::PrintIconMarker;
    case Preset::TYPE_FILAMENT:
        return ImGui::FilamentIconMarker;
    case Preset::TYPE_SLA_MATERIAL:
        return ImGui::MaterialIconMarker;
    case Preset::TYPE_PRINTER:
        return pt == ptSLA ? ImGui::PrinterSlaIconMarker : ImGui::PrinterIconMarker;
    case Preset::TYPE_PREFERENCES:
        return ImGui::PreferencesButton;
    default:
        return ' ';
  }
}
References ImGui::FilamentIconMarker, ImGui::MaterialIconMarker, ImGui::PreferencesButton, ImGui::PrinterIconMarker, ImGui::PrinterSlaIconMarker, ImGui::PrintIconMarker, Slic3r::ptSLA, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PREFERENCES, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, and Slic3r::Preset::TYPE_SLA_PRINT.
Referenced by mark_string(), and Slic3r::Search::OptionsSearcher::search().
Variable Documentation
icon_idxs
const std::map<const char, int> Slic3r::Search::icon_idxs static
Initial value:
= {
    {ImGui::PrintIconMarker     , 0},
    {ImGui::PrinterIconMarker   , 1},
    {ImGui::PrinterSlaIconMarker, 2},
    {ImGui::FilamentIconMarker  , 3},
    {ImGui::MaterialIconMarker  , 4},
    {ImGui::PreferencesButton   , 5},
}
Referenced by Slic3r::Search::SearchListModel::Prepend().