Prusa Slicer: Slic3r::GUI::Emboss::CreateVolumeJob Class Reference
Slic3r::GUI::Emboss::CreateVolumeJob Class Reference
Create new TextVolume on the surface of ModelObject Should not be stopped NOTE: EmbossDataBase::font_file doesn't have to be valid !!!
#include <src/slic3r/GUI/Jobs/EmbossJob.hpp>
Public Member Functions
CreateVolumeJob (DataCreateVolume &&input)
Create Volume.
void process (Ctl &ctl) override
void finalize (bool canceled, std::exception_ptr &eptr) override
Private Attributes
DataCreateVolume m_input
TriangleMesh m_result
Detailed Description
Create new TextVolume on the surface of ModelObject Should not be stopped NOTE: EmbossDataBase::font_file doesn't have to be valid !!!
Constructor & Destructor Documentation
CreateVolumeJob()
CreateVolumeJob::CreateVolumeJob (DataCreateVolume && input)
Create Volume.
    : m_input(std::move(input))
{
    assert(priv::check(m_input, true));
}
References priv::check(), and m_input.
Member Function Documentation
finalize()
void CreateVolumeJob::finalize (bool canceled, std::exception_ptr & eptr) override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (!priv::finalize(canceled, eptr, m_input))
        return;
    if (m_result.its.empty())
        return priv::create_message("Can't create empty volume.");
    priv::create_volume(std::move(m_result), m_input.object_id, m_input.volume_type, m_input.trmat, m_input);
}
References priv::create_message(), priv::create_volume(), indexed_triangle_set::empty(), priv::finalize(), Slic3r::TriangleMesh::its, m_input, m_result, Slic3r::GUI::Emboss::DataCreateVolume::object_id, Slic3r::GUI::Emboss::DataCreateVolume::trmat, and Slic3r::GUI::Emboss::DataCreateVolume::volume_type.
process()
void CreateVolumeJob::process (Ctl & ctl) override virtual
Implements Slic3r::GUI::Job.
{
    if (!priv::check(m_input)) throw std::runtime_error("Bad input data for EmbossCreateVolumeJob.");
    auto was_canceled = [&ctl]()->bool { return ctl.was_canceled(); };
    m_result = priv::create_mesh(m_input, was_canceled, ctl);
    // center result
    Vec3f c = m_result.bounding_box().center().cast<float>();
    if (!c.isApprox(Vec3f::Zero())) m_result.translate(-c);
}
References Slic3r::TriangleMesh::bounding_box(), Slic3r::BoundingBox3Base< PointType >::center(), priv::check(), priv::create_mesh(), m_input, m_result, Slic3r::TriangleMesh::translate(), and Slic3r::GUI::Job::Ctl::was_canceled().
Member Data Documentation
m_input
DataCreateVolume Slic3r::GUI::Emboss::CreateVolumeJob::m_input private
Referenced by CreateVolumeJob(), finalize(), and process().
m_result
TriangleMesh Slic3r::GUI::Emboss::CreateVolumeJob::m_result private
Referenced by finalize(), and process().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/EmbossJob.hpp
src/slic3r/GUI/Jobs/EmbossJob.cpp