Prusa Slicer: Slic3r::GLVolume::NonManifoldEdges Class Reference
Slic3r::GLVolume::NonManifoldEdges Class Reference
Public Member Functions
NonManifoldEdges (GLVolume &volume)
void render ()
void set_as_dirty ()
Private Member Functions
void update ()
Private Attributes
GLVolume & m_parent
GUI::GLModel m_model
bool m_update_needed { true }
Detailed Description
Constructor & Destructor Documentation
NonManifoldEdges()
Slic3r::GLVolume::NonManifoldEdges::NonManifoldEdges (GLVolume & volume) inline
: m_parent(volume) {}
Member Function Documentation
render()
void Slic3r::GLVolume::NonManifoldEdges::render ()
{
    update();
#if ENABLE_GL_CORE_PROFILE
    if (!GUI::OpenGLManager::get_gl_info().is_core_profile())
#endif // ENABLE_GL_CORE_PROFILE
        glsafe(::glLineWidth(2.0f));
    GLShaderProgram* shader = GUI::wxGetApp().get_current_shader();
    if (shader == nullptr)
        return;
    const GUI::Camera& camera = GUI::wxGetApp().plater()->get_camera();
    shader->set_uniform("view_model_matrix", camera.get_view_matrix() * m_parent.world_matrix());
    shader->set_uniform("projection_matrix", camera.get_projection_matrix());
#if ENABLE_GL_CORE_PROFILE
    const std::array<int, 4>& viewport = camera.get_viewport();
    shader->set_uniform("viewport_size", Vec2d(double(viewport[2]), double(viewport[3])));
    shader->set_uniform("width", 0.5f);
    shader->set_uniform("gap_size", 0.0f);
#endif // ENABLE_GL_CORE_PROFILE
    m_model.set_color(complementary(m_parent.render_color));
    m_model.render();
}
References Slic3r::complementary(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), glsafe, and Slic3r::GLShaderProgram::set_uniform().
Referenced by Slic3r::GLVolume::render_non_manifold_edges().
set_as_dirty()
void Slic3r::GLVolume::NonManifoldEdges::set_as_dirty () inline
{ m_update_needed = true; }
References m_update_needed.
update()
void Slic3r::GLVolume::NonManifoldEdges::update () private
{
    if (!m_update_needed)
        return;
    m_model.reset();
    const int object_idx = m_parent.object_idx();
    const Model& model = GUI::wxGetApp().plater()->model();
    if (0 <= object_idx && object_idx < int(model.objects.size())) {
        const ModelObject* model_object = model.objects[object_idx];
        const int volume_idx = m_parent.volume_idx();
        if (0 <= volume_idx && volume_idx < int(model_object->volumes.size())) {
            const ModelVolume* model_volume = model_object->volumes[volume_idx];
            const TriangleMesh& mesh = model_volume->mesh();
            const std::vector<std::pair<int, int>> edges = its_get_open_edges(mesh.its);
            if (!edges.empty()) {
                GUI::GLModel::Geometry init_data;
                init_data.format = { GUI::GLModel::Geometry::EPrimitiveType::Lines, GUI::GLModel::Geometry::EVertexLayout::P3 };
                init_data.reserve_vertices(2 * edges.size());
                init_data.reserve_indices(2 * edges.size());
                // vertices + indices
                unsigned int vertices_count = 0;
                for (const std::pair<int, int>& edge : edges) {
                    init_data.add_vertex((Vec3f)mesh.its.vertices[edge.first].cast<float>());
                    init_data.add_vertex((Vec3f)mesh.its.vertices[edge.second].cast<float>());
                    vertices_count += 2;
                    init_data.add_line(vertices_count - 2, vertices_count - 1);
                }
                m_model.init_from(std::move(init_data));
            }
        }
    }
    m_update_needed = false;
}
References Slic3r::GUI::GLModel::Geometry::add_line(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::TriangleMesh::its, Slic3r::its_get_open_edges(), Slic3r::GUI::GLModel::Geometry::Lines, Slic3r::ModelVolume::mesh(), Slic3r::GLVolume::model, Slic3r::GLVolume::object_idx(), Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), indexed_triangle_set::vertices, Slic3r::GLVolume::volume_idx(), and Slic3r::ModelObject::volumes.
Member Data Documentation
m_model
GUI::GLModel Slic3r::GLVolume::NonManifoldEdges::m_model private
m_parent
GLVolume& Slic3r::GLVolume::NonManifoldEdges::m_parent private
m_update_needed
bool Slic3r::GLVolume::NonManifoldEdges::m_update_needed { true } private
Referenced by set_as_dirty().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DScene.hpp
src/slic3r/GUI/3DScene.cpp