Prusa Slicer: Slic3r::SupportSpotsGenerator::ObjectPart Class Reference
Slic3r::SupportSpotsGenerator::ObjectPart Class Reference
Public Member Functions
ObjectPart ()=default
void add (const ObjectPart &other)
void add_support_point (const Vec3f &position, float sticking_area)
float compute_directional_xy_variance (const Vec2f &line_dir, const Vec3f &centroid_accumulator, const Vec2f &second_moment_of_area_accumulator, const float &second_moment_of_area_covariance_accumulator, const float &area) const
float compute_elastic_section_modulus (const Vec2f &line_dir, const Vec3f &extreme_point, const Vec3f &centroid_accumulator, const Vec2f &second_moment_of_area_accumulator, const float &second_moment_of_area_covariance_accumulator, const float &area) const
std::tuple< float, SupportPointCause > is_stable_while_extruding (const SliceConnection &connection, const ExtrusionLine &extruded_line, const Vec3f &extreme_point, float layer_z, const Params &params) const
Public Attributes
float volume {}
Vec3f volume_centroid_accumulator = Vec3f::Zero()
float sticking_area {}
Vec3f sticking_centroid_accumulator = Vec3f::Zero()
Vec2f sticking_second_moment_of_area_accumulator = Vec2f::Zero()
float sticking_second_moment_of_area_covariance_accumulator {}
bool connected_to_bed = false
Detailed Description
Constructor & Destructor Documentation
ObjectPart()
Slic3r::SupportSpotsGenerator::ObjectPart::ObjectPart () default
Member Function Documentation
add()
void Slic3r::SupportSpotsGenerator::ObjectPart::add (const ObjectPart & other) inline
    {
        this->connected_to_bed = this->connected_to_bed || other.connected_to_bed;
        this->volume_centroid_accumulator += other.volume_centroid_accumulator;
        this->volume += other.volume;
        this->sticking_area += other.sticking_area;
        this->sticking_centroid_accumulator += other.sticking_centroid_accumulator;
        this->sticking_second_moment_of_area_accumulator += other.sticking_second_moment_of_area_accumulator;
        this->sticking_second_moment_of_area_covariance_accumulator += other.sticking_second_moment_of_area_covariance_accumulator;
    }
References connected_to_bed, sticking_area, sticking_centroid_accumulator, sticking_second_moment_of_area_accumulator, sticking_second_moment_of_area_covariance_accumulator, volume, and volume_centroid_accumulator.
Referenced by Slic3r::SupportSpotsGenerator::check_stability().
add_support_point()
void Slic3r::SupportSpotsGenerator::ObjectPart::add_support_point (const Vec3f & position, float sticking_area) inline
    {
        this->sticking_area += sticking_area;
        this->sticking_centroid_accumulator += sticking_area * position;
        this->sticking_second_moment_of_area_accumulator += sticking_area * position.head<2>().cwiseProduct(position.head<2>());
        this->sticking_second_moment_of_area_covariance_accumulator += sticking_area * position.x() * position.y();
    }
Referenced by Slic3r::SupportSpotsGenerator::check_stability().
compute_directional_xy_variance()
float Slic3r::SupportSpotsGenerator::ObjectPart::compute_directional_xy_variance (const Vec2f & line_dir, const Vec3f & centroid_accumulator, const Vec2f & second_moment_of_area_accumulator, const float & second_moment_of_area_covariance_accumulator, const float & area) const inline
    {
        assert(area > 0);
        Vec3f centroid   = centroid_accumulator / area;
        Vec2f variance   = (second_moment_of_area_accumulator / area - centroid.head<2>().cwiseProduct(centroid.head<2>()));
        float covariance = second_moment_of_area_covariance_accumulator / area - centroid.x() * centroid.y();
        // Var(aX+bY)=a^2*Var(X)+b^2*Var(Y)+2*a*b*Cov(X,Y)
        float directional_xy_variance = line_dir.x() * line_dir.x() * variance.x() + line_dir.y() * line_dir.y() * variance.y() +
                                        2.0f * line_dir.x() * line_dir.y() * covariance;
#ifdef DETAILED_DEBUG_LOGS
        BOOST_LOG_TRIVIAL(debug) << "centroid: " << centroid.x() << "  " << centroid.y() << "  " << centroid.z();
        BOOST_LOG_TRIVIAL(debug) << "variance: " << variance.x() << "  " << variance.y();
        BOOST_LOG_TRIVIAL(debug) << "covariance: " << covariance;
        BOOST_LOG_TRIVIAL(debug) << "directional_xy_variance: " << directional_xy_variance;
#endif
        return directional_xy_variance;
    }
compute_elastic_section_modulus()
float Slic3r::SupportSpotsGenerator::ObjectPart::compute_elastic_section_modulus (const Vec2f & line_dir, const Vec3f & extreme_point, const Vec3f & centroid_accumulator, const Vec2f & second_moment_of_area_accumulator, const float & second_moment_of_area_covariance_accumulator, const float & area) const inline
    {
        float directional_xy_variance = compute_directional_xy_variance(line_dir, centroid_accumulator, second_moment_of_area_accumulator,
                                                                        second_moment_of_area_covariance_accumulator, area);
        if (directional_xy_variance < EPSILON) { return 0.0f; }
        Vec3f centroid                = centroid_accumulator / area;
        float extreme_fiber_dist      = line_alg::distance_to(Linef(centroid.head<2>().cast<double>(),
                                                                    (centroid.head<2>() + Vec2f(line_dir.y(), -line_dir.x())).cast<double>()),
                                                              extreme_point.head<2>().cast<double>());
        float elastic_section_modulus = area * directional_xy_variance / extreme_fiber_dist;
#ifdef DETAILED_DEBUG_LOGS
        BOOST_LOG_TRIVIAL(debug) << "extreme_fiber_dist: " << extreme_fiber_dist;
        BOOST_LOG_TRIVIAL(debug) << "elastic_section_modulus: " << elastic_section_modulus;
#endif
        return elastic_section_modulus;
    }
References EPSILON.
is_stable_while_extruding()
std::tuple< float, SupportPointCause > Slic3r::SupportSpotsGenerator::ObjectPart::is_stable_while_extruding (const SliceConnection & connection, const ExtrusionLine & extruded_line, const Vec3f & extreme_point, float layer_z, const Params & params) const inline
    {
        Vec2f        line_dir      = (extruded_line.b - extruded_line.a).normalized();
        const Vec3f &mass_centroid = this->volume_centroid_accumulator / this->volume;
        float        mass          = this->volume * params.filament_density;
        float        weight        = mass * params.gravity_constant;
        float movement_force = params.max_acceleration * mass;
        float extruder_conflict_force = params.standard_extruder_conflict_force +
                                        std::min(extruded_line.curled_up_height, 1.0f) * params.malformations_additive_conflict_extruder_force;
        // section for bed calculations
        {
            if (this->sticking_area < EPSILON) return {1.0f, SupportPointCause::UnstableFloatingPart};
            Vec3f bed_centroid     = this->sticking_centroid_accumulator / this->sticking_area;
            float bed_yield_torque = -compute_elastic_section_modulus(line_dir, extreme_point, this->sticking_centroid_accumulator,
                                                                      this->sticking_second_moment_of_area_accumulator,
                                                                      this->sticking_second_moment_of_area_covariance_accumulator,
                                                                      this->sticking_area) *
                                     params.get_bed_adhesion_yield_strength();
            Vec2f bed_weight_arm             = (mass_centroid.head<2>() - bed_centroid.head<2>());
            float bed_weight_arm_len         = bed_weight_arm.norm();
            float bed_weight_dir_xy_variance = compute_directional_xy_variance(bed_weight_arm, this->sticking_centroid_accumulator,
                                                                               this->sticking_second_moment_of_area_accumulator,
                                                                               this->sticking_second_moment_of_area_covariance_accumulator,
                                                                               this->sticking_area);
            float bed_weight_sign            = bed_weight_arm_len < 2.0f * sqrt(bed_weight_dir_xy_variance) ? -1.0f : 1.0f;
            float bed_weight_torque          = bed_weight_sign * bed_weight_arm_len * weight;
            float bed_movement_arm    = std::max(0.0f, mass_centroid.z() - bed_centroid.z());
            float bed_movement_torque = movement_force * bed_movement_arm;
            float bed_conflict_torque_arm      = layer_z - bed_centroid.z();
            float bed_extruder_conflict_torque = extruder_conflict_force * bed_conflict_torque_arm;
            float bed_total_torque = bed_movement_torque + bed_extruder_conflict_torque + bed_weight_torque + bed_yield_torque;
#ifdef DETAILED_DEBUG_LOGS
            BOOST_LOG_TRIVIAL(debug) << "bed_centroid: " << bed_centroid.x() << "  " << bed_centroid.y() << "  " << bed_centroid.z();
            BOOST_LOG_TRIVIAL(debug) << "SSG: bed_yield_torque: " << bed_yield_torque;
            BOOST_LOG_TRIVIAL(debug) << "SSG: bed_weight_arm: " << bed_weight_arm_len;
            BOOST_LOG_TRIVIAL(debug) << "SSG: bed_weight_torque: " << bed_weight_torque;
            BOOST_LOG_TRIVIAL(debug) << "SSG: bed_movement_arm: " << bed_movement_arm;
            BOOST_LOG_TRIVIAL(debug) << "SSG: bed_movement_torque: " << bed_movement_torque;
            BOOST_LOG_TRIVIAL(debug) << "SSG: bed_conflict_torque_arm: " << bed_conflict_torque_arm;
            BOOST_LOG_TRIVIAL(debug) << "SSG: extruded_line.curled_up_height: " << extruded_line.curled_up_height;
            BOOST_LOG_TRIVIAL(debug) << "SSG: extruded_line.form_quality: " << extruded_line.form_quality;
            BOOST_LOG_TRIVIAL(debug) << "SSG: extruder_conflict_force: " << extruder_conflict_force;
            BOOST_LOG_TRIVIAL(debug) << "SSG: bed_extruder_conflict_torque: " << bed_extruder_conflict_torque;
            BOOST_LOG_TRIVIAL(debug) << "SSG: total_torque: " << bed_total_torque << "   layer_z: " << layer_z;
#endif
            if (bed_total_torque > 0) {
                return {bed_total_torque / bed_conflict_torque_arm,
                        (this->connected_to_bed ? SupportPointCause::SeparationFromBed : SupportPointCause::UnstableFloatingPart)};
            }
        }
        // section for weak connection calculations
        {
            if (connection.area < EPSILON) return {1.0f, SupportPointCause::UnstableFloatingPart};
            Vec3f conn_centroid = connection.centroid_accumulator / connection.area;
            if (layer_z - conn_centroid.z() < 3.0f) { return {-1.0f, SupportPointCause::WeakObjectPart}; }
            float conn_yield_torque = compute_elastic_section_modulus(line_dir, extreme_point, connection.centroid_accumulator,
                                                                      connection.second_moment_of_area_accumulator,
                                                                      connection.second_moment_of_area_covariance_accumulator,
                                                                      connection.area) *
                                      params.material_yield_strength;
            float conn_weight_arm    = (conn_centroid.head<2>() - mass_centroid.head<2>()).norm();
            if (layer_z - conn_centroid.z() < 30.0) {
                conn_weight_arm = 0.0f; // Given that we do not have very good info about the weight distribution between the connection and current layer,
                // do not consider the weight until quite far away from the weak connection segment
            }
            float conn_weight_torque = conn_weight_arm * weight * (1.0f - conn_centroid.z() / layer_z) * (1.0f - conn_centroid.z() / layer_z);
            float conn_movement_arm    = std::max(0.0f, mass_centroid.z() - conn_centroid.z());
            float conn_movement_torque = movement_force * conn_movement_arm;
            float conn_conflict_torque_arm      = layer_z - conn_centroid.z();
            float conn_extruder_conflict_torque = extruder_conflict_force * conn_conflict_torque_arm;
            float conn_total_torque = conn_movement_torque + conn_extruder_conflict_torque + conn_weight_torque - conn_yield_torque;
#ifdef DETAILED_DEBUG_LOGS
            BOOST_LOG_TRIVIAL(debug) << "conn_centroid: " << conn_centroid.x() << "  " << conn_centroid.y() << "  " << conn_centroid.z();
            BOOST_LOG_TRIVIAL(debug) << "SSG: conn_yield_torque: " << conn_yield_torque;
            BOOST_LOG_TRIVIAL(debug) << "SSG: conn_weight_arm: " << conn_weight_arm;
            BOOST_LOG_TRIVIAL(debug) << "SSG: conn_weight_torque: " << conn_weight_torque;
            BOOST_LOG_TRIVIAL(debug) << "SSG: conn_movement_arm: " << conn_movement_arm;
            BOOST_LOG_TRIVIAL(debug) << "SSG: conn_movement_torque: " << conn_movement_torque;
            BOOST_LOG_TRIVIAL(debug) << "SSG: conn_conflict_torque_arm: " << conn_conflict_torque_arm;
            BOOST_LOG_TRIVIAL(debug) << "SSG: conn_extruder_conflict_torque: " << conn_extruder_conflict_torque;
            BOOST_LOG_TRIVIAL(debug) << "SSG: total_torque: " << conn_total_torque << "   layer_z: " << layer_z;
#endif
            return {conn_total_torque / conn_conflict_torque_arm, SupportPointCause::WeakObjectPart};
        }
    }
References Slic3r::ExtrusionLine::a, Slic3r::SupportSpotsGenerator::SliceConnection::area, Slic3r::ExtrusionLine::b, Slic3r::SupportSpotsGenerator::SliceConnection::centroid_accumulator, Slic3r::ExtrusionLine::curled_up_height, EPSILON, Slic3r::SupportSpotsGenerator::Params::filament_density, Slic3r::ExtrusionLine::form_quality, Slic3r::SupportSpotsGenerator::Params::get_bed_adhesion_yield_strength(), Slic3r::SupportSpotsGenerator::Params::gravity_constant, Slic3r::SupportSpotsGenerator::Params::malformations_additive_conflict_extruder_force, Slic3r::SupportSpotsGenerator::Params::material_yield_strength, Slic3r::SupportSpotsGenerator::Params::max_acceleration, Slic3r::SupportSpotsGenerator::SliceConnection::second_moment_of_area_accumulator, Slic3r::SupportSpotsGenerator::SliceConnection::second_moment_of_area_covariance_accumulator, sqrt(), and Slic3r::SupportSpotsGenerator::Params::standard_extruder_conflict_force.
Referenced by Slic3r::SupportSpotsGenerator::check_stability().
Member Data Documentation
connected_to_bed
bool Slic3r::SupportSpotsGenerator::ObjectPart::connected_to_bed = false
Referenced by add(), and Slic3r::SupportSpotsGenerator::build_object_part_from_slice().
sticking_area
float Slic3r::SupportSpotsGenerator::ObjectPart::sticking_area {}
Referenced by add(), and Slic3r::SupportSpotsGenerator::build_object_part_from_slice().
sticking_centroid_accumulator
Vec3f Slic3r::SupportSpotsGenerator::ObjectPart::sticking_centroid_accumulator = Vec3f::Zero()
Referenced by add(), and Slic3r::SupportSpotsGenerator::build_object_part_from_slice().
sticking_second_moment_of_area_accumulator
Vec2f Slic3r::SupportSpotsGenerator::ObjectPart::sticking_second_moment_of_area_accumulator = Vec2f::Zero()
Referenced by add(), and Slic3r::SupportSpotsGenerator::build_object_part_from_slice().
sticking_second_moment_of_area_covariance_accumulator
float Slic3r::SupportSpotsGenerator::ObjectPart::sticking_second_moment_of_area_covariance_accumulator {}
Referenced by add(), and Slic3r::SupportSpotsGenerator::build_object_part_from_slice().
volume
float Slic3r::SupportSpotsGenerator::ObjectPart::volume {}
Referenced by add(), and Slic3r::SupportSpotsGenerator::build_object_part_from_slice().
volume_centroid_accumulator
Vec3f Slic3r::SupportSpotsGenerator::ObjectPart::volume_centroid_accumulator = Vec3f::Zero()
Referenced by add(), and Slic3r::SupportSpotsGenerator::build_object_part_from_slice().
The documentation for this class was generated from the following file:
src/libslic3r/SupportSpotsGenerator.cpp