Prusa Slicer: Eigen::SelfAdjointView< _MatrixType, UpLo > Class Template Reference
Eigen::SelfAdjointView< _MatrixType, UpLo > Class Template Reference
Expression of a selfadjoint matrix from a triangular part of a dense matrix.
#include <src/eigen/Eigen/src/Core/SelfAdjointView.h>
Public Types
enum { Mode = internal::traits<SelfAdjointView>::Mode , Flags = internal::traits<SelfAdjointView>::Flags , TransposeMode = ((Mode & Upper) ? Lower : 0) | ((Mode & Lower) ? Upper : 0) }
typedef _MatrixType MatrixType
typedef TriangularBase< SelfAdjointView > Base
typedef internal::traits< SelfAdjointView >::MatrixTypeNested MatrixTypeNested
typedef internal::traits< SelfAdjointView >::MatrixTypeNestedCleaned MatrixTypeNestedCleaned
typedef MatrixTypeNestedCleaned NestedExpression
typedef internal::traits< SelfAdjointView >::Scalar Scalar
The type of coefficients in this matrix.
typedef MatrixType::StorageIndex StorageIndex
typedef internal::remove_all< typenameMatrixType::ConjugateReturnType >::type MatrixConjugateReturnType
typedef MatrixType::PlainObject PlainObject
typedef SelfAdjointView< const MatrixConjugateReturnType, UpLo > ConjugateReturnType
typedef SelfAdjointView< const typename MatrixType::AdjointReturnType, TransposeMode > AdjointReturnType
typedef SelfAdjointView< typename MatrixType::TransposeReturnType, TransposeMode > TransposeReturnType
typedef SelfAdjointView< const typename MatrixType::ConstTransposeReturnType, TransposeMode > ConstTransposeReturnType
typedef NumTraits< Scalar >::Real RealScalar
typedef Matrix< RealScalar, internal::traits< MatrixType >::ColsAtCompileTime, 1 > EigenvaluesReturnType
enum
typedef internal::traits< SelfAdjointView< _MatrixType, UpLo > >::StorageKind StorageKind
typedef internal::traits< SelfAdjointView< _MatrixType, UpLo > >::FullMatrixType DenseMatrixType
typedef DenseMatrixType DenseType
typedef SelfAdjointView< _MatrixType, UpLo > const & Nested
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
EIGEN_DEVICE_FUNC SelfAdjointView (MatrixType &matrix)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Index innerStride () const
EIGEN_DEVICE_FUNC Scalar coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC const MatrixTypeNestedCleaned & _expression () const
EIGEN_DEVICE_FUNC const MatrixTypeNestedCleaned & nestedExpression () const
EIGEN_DEVICE_FUNC MatrixTypeNestedCleaned & nestedExpression ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< SelfAdjointView, OtherDerived > operator* (const MatrixBase< OtherDerived > &rhs) const
template<typename DerivedU , typename DerivedV >
EIGEN_DEVICE_FUNC SelfAdjointView & rankUpdate (const MatrixBase< DerivedU > &u, const MatrixBase< DerivedV > &v, const Scalar &alpha=Scalar(1))
template<typename DerivedU >
EIGEN_DEVICE_FUNC SelfAdjointView & rankUpdate (const MatrixBase< DerivedU > &u, const Scalar &alpha=Scalar(1))
template<unsigned int TriMode>
EIGEN_DEVICE_FUNC internal::conditional<(TriMode &(Upper|Lower))==(UpLo &(Upper|Lower)), TriangularView< MatrixType, TriMode >, TriangularView< typenameMatrixType::AdjointReturnType, TriMode > >::type triangularView () const
EIGEN_DEVICE_FUNC const ConjugateReturnType conjugate () const
EIGEN_DEVICE_FUNC const AdjointReturnType adjoint () const
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC const ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC MatrixType::ConstDiagonalReturnType diagonal () const
const LLT< PlainObject, UpLo > llt () const
const LDLT< PlainObject, UpLo > ldlt () const
EIGEN_DEVICE_FUNC EigenvaluesReturnType eigenvalues () const
Computes the eigenvalues of a matrix.
EIGEN_DEVICE_FUNC RealScalar operatorNorm () const
Computes the L2 operator norm.
template<typename DerivedU >
SelfAdjointView< MatrixType, UpLo > & rankUpdate (const MatrixBase< DerivedU > &u, const Scalar &alpha)
template<typename DerivedU , typename DerivedV >
SelfAdjointView< MatrixType, UpLo > & rankUpdate (const MatrixBase< DerivedU > &u, const MatrixBase< DerivedV > &v, const Scalar &alpha)
void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, Other &other)
EIGEN_DEVICE_FUNC Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & operator() (Index row, Index col)
EIGEN_DEVICE_FUNC const SelfAdjointView< _MatrixType, UpLo > & derived () const
EIGEN_DEVICE_FUNC SelfAdjointView< _MatrixType, UpLo > & derived ()
EIGEN_DEVICE_FUNC void evalTo (MatrixBase< DenseDerived > &other) const
void evalTo (MatrixBase< DenseDerived > &other) const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void evalToLazy (MatrixBase< DenseDerived > &other) const
void evalToLazy (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
Protected Attributes
MatrixTypeNested m_matrix
Friends
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< OtherDerived, SelfAdjointView > operator* (const MatrixBase< OtherDerived > &lhs, const SelfAdjointView &rhs)
EIGEN_DEVICE_FUNC const SelfAdjointView< const EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(Scalar, MatrixType, product), UpLo > operator* (const Scalar &s, const SelfAdjointView &mat)
Detailed Description
template<typename _MatrixType, unsigned int UpLo>
class Eigen::SelfAdjointView< _MatrixType, UpLo >
Expression of a selfadjoint matrix from a triangular part of a dense matrix.
Parameters
MatrixType the type of the dense matrix storing the coefficients
TriangularPart can be either Lower or Upper
This class is an expression of a sefladjoint matrix from a triangular part of a matrix with given dense storage of the coefficients. It is the return type of MatrixBase::selfadjointView() and most of the time this is the only way that it is used.
See also
class TriangularBase, MatrixBase::selfadjointView()
Member Typedef Documentation
AdjointReturnType
template<typename _MatrixType , unsigned int UpLo> typedef SelfAdjointView<const typename MatrixType::AdjointReturnType,TransposeMode> Eigen::SelfAdjointView< _MatrixType, UpLo >::AdjointReturnType
Base
template<typename _MatrixType , unsigned int UpLo> typedef TriangularBase<SelfAdjointView> Eigen::SelfAdjointView< _MatrixType, UpLo >::Base
ConjugateReturnType
template<typename _MatrixType , unsigned int UpLo> typedef SelfAdjointView<const MatrixConjugateReturnType,UpLo> Eigen::SelfAdjointView< _MatrixType, UpLo >::ConjugateReturnType
ConstTransposeReturnType
template<typename _MatrixType , unsigned int UpLo> typedef SelfAdjointView<const typename MatrixType::ConstTransposeReturnType,TransposeMode> Eigen::SelfAdjointView< _MatrixType, UpLo >::ConstTransposeReturnType
DenseMatrixType
typedef internal::traits<SelfAdjointView< _MatrixType, UpLo > >::FullMatrixType Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::DenseMatrixType inherited
DenseType
typedef DenseMatrixType Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::DenseType inherited
EigenvaluesReturnType
template<typename _MatrixType , unsigned int UpLo> typedef Matrix<RealScalar, internal::traits<MatrixType>::ColsAtCompileTime, 1> Eigen::SelfAdjointView< _MatrixType, UpLo >::EigenvaluesReturnType
Return type of eigenvalues()
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
MatrixConjugateReturnType
template<typename _MatrixType , unsigned int UpLo> typedef internal::remove_all<typenameMatrixType::ConjugateReturnType>::type Eigen::SelfAdjointView< _MatrixType, UpLo >::MatrixConjugateReturnType
MatrixType
template<typename _MatrixType , unsigned int UpLo> typedef _MatrixType Eigen::SelfAdjointView< _MatrixType, UpLo >::MatrixType
MatrixTypeNested
template<typename _MatrixType , unsigned int UpLo> typedef internal::traits<SelfAdjointView>::MatrixTypeNested Eigen::SelfAdjointView< _MatrixType, UpLo >::MatrixTypeNested
MatrixTypeNestedCleaned
template<typename _MatrixType , unsigned int UpLo> typedef internal::traits<SelfAdjointView>::MatrixTypeNestedCleaned Eigen::SelfAdjointView< _MatrixType, UpLo >::MatrixTypeNestedCleaned
Nested
typedef SelfAdjointView< _MatrixType, UpLo > const& Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::Nested inherited
NestedExpression
template<typename _MatrixType , unsigned int UpLo> typedef MatrixTypeNestedCleaned Eigen::SelfAdjointView< _MatrixType, UpLo >::NestedExpression
PlainObject
template<typename _MatrixType , unsigned int UpLo> typedef MatrixType::PlainObject Eigen::SelfAdjointView< _MatrixType, UpLo >::PlainObject
RealScalar
template<typename _MatrixType , unsigned int UpLo> typedef NumTraits<Scalar>::Real Eigen::SelfAdjointView< _MatrixType, UpLo >::RealScalar
Real part of Scalar
Scalar
template<typename _MatrixType , unsigned int UpLo> typedef internal::traits<SelfAdjointView>::Scalar Eigen::SelfAdjointView< _MatrixType, UpLo >::Scalar
The type of coefficients in this matrix.
StorageIndex
template<typename _MatrixType , unsigned int UpLo> typedef MatrixType::StorageIndex Eigen::SelfAdjointView< _MatrixType, UpLo >::StorageIndex
StorageKind
typedef internal::traits<SelfAdjointView< _MatrixType, UpLo > >::StorageKind Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::StorageKind inherited
TransposeReturnType
template<typename _MatrixType , unsigned int UpLo> typedef SelfAdjointView<typename MatrixType::TransposeReturnType,TransposeMode> Eigen::SelfAdjointView< _MatrixType, UpLo >::TransposeReturnType
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType , unsigned int UpLo> anonymous enum
Enumerator
Mode
Flags
TransposeMode
         {
      Mode = internal::traits<SelfAdjointView>::Mode,
      Flags = internal::traits<SelfAdjointView>::Flags,
      TransposeMode = ((Mode & Upper) ? Lower : 0) | ((Mode & Lower) ? Upper : 0)
    };
anonymous enum
anonymous enum inherited
         {
      Mode = internal::traits<Derived>::Mode,
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxSizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::MaxRowsAtCompileTime,
                                                   internal::traits<Derived>::MaxColsAtCompileTime>::ret)
    };
Constructor & Destructor Documentation
SelfAdjointView()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC Eigen::SelfAdjointView< _MatrixType, UpLo >::SelfAdjointView (MatrixType & matrix) inline explicit
                                                        : m_matrix(matrix)
    {
      EIGEN_STATIC_ASSERT(UpLo==Lower || UpLo==Upper,SELFADJOINTVIEW_ACCEPTS_UPPER_AND_LOWER_MODE_ONLY);
    }
References EIGEN_STATIC_ASSERT, Eigen::Lower, and Eigen::Upper.
Member Function Documentation
_expression()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC const MatrixTypeNestedCleaned & Eigen::SelfAdjointView< _MatrixType, UpLo >::_expression () const inline
{ return m_matrix; }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC const AdjointReturnType Eigen::SelfAdjointView< _MatrixType, UpLo >::adjoint () const inline
See also
MatrixBase::adjoint() const
    { return AdjointReturnType(m_matrix.adjoint()); }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
check_coordinates()
void Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::check_coordinates (Index row, Index col) const inline protected inherited
    {
      EIGEN_ONLY_USED_FOR_DEBUG(row);
      EIGEN_ONLY_USED_FOR_DEBUG(col);
      eigen_assert(col>=0 && col<cols() && row>=0 && row<rows());
      const int mode = int(Mode) & ~SelfAdjoint;
      EIGEN_ONLY_USED_FOR_DEBUG(mode);
      eigen_assert((mode==Upper && col>=row)
                || (mode==Lower && col<=row)
                || ((mode==StrictlyUpper || mode==UnitUpper) && col>row)
                || ((mode==StrictlyLower || mode==UnitLower) && col<row));
    }
check_coordinates_internal()
void Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::check_coordinates_internal (Index , Index) const inline protected inherited
{}
coeff()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC Scalar Eigen::SelfAdjointView< _MatrixType, UpLo >::coeff (Index row, Index col) const inline
See also
MatrixBase::coeff()
Warning
the coordinates must fit into the referenced triangular part
    {
      Base::check_coordinates_internal(row, col);
      return m_matrix.coeff(row, col);
    }
References Eigen::TriangularBase< Derived >::check_coordinates_internal(), col(), Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix, and row().
coeffRef()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC Scalar & Eigen::SelfAdjointView< _MatrixType, UpLo >::coeffRef (Index row, Index col) inline
See also
MatrixBase::coeffRef()
Warning
the coordinates must fit into the referenced triangular part
    {
      EIGEN_STATIC_ASSERT_LVALUE(SelfAdjointView);
      Base::check_coordinates_internal(row, col);
      return m_matrix.coeffRef(row, col);
    }
References Eigen::TriangularBase< Derived >::check_coordinates_internal(), col(), EIGEN_STATIC_ASSERT_LVALUE, Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix, and row().
cols()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC Index Eigen::SelfAdjointView< _MatrixType, UpLo >::cols () const inline
{ return m_matrix.cols(); }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
conjugate()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC const ConjugateReturnType Eigen::SelfAdjointView< _MatrixType, UpLo >::conjugate () const inline
See also
MatrixBase::conjugate() const
    { return ConjugateReturnType(m_matrix.conjugate()); }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
copyCoeff()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::copyCoeff (Index row, Index col, Other & other) inline inherited
See also
MatrixBase::copyCoeff(row,col)
    {
      derived().coeffRef(row, col) = other.coeff(row, col);
    }
derived() [1/2]
EIGEN_DEVICE_FUNC SelfAdjointView< _MatrixType, UpLo > & Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::derived () inline inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
EIGEN_DEVICE_FUNC const SelfAdjointView< _MatrixType, UpLo > & Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::derived () const inline inherited
{ return *static_cast<const Derived*>(this); }
diagonal()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC MatrixType::ConstDiagonalReturnType Eigen::SelfAdjointView< _MatrixType, UpLo >::diagonal () const inline
Returns
a const expression of the main diagonal of the matrix *this
This method simply returns the diagonal of the nested expression, thus by-passing the SelfAdjointView decorator.
See also
MatrixBase::diagonal(), class Diagonal
    {
      return typename MatrixType::ConstDiagonalReturnType(m_matrix);
    }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
eigenvalues()
template<typename MatrixType , unsigned int UpLo> SelfAdjointView< MatrixType, UpLo >::EigenvaluesReturnType Eigen::SelfAdjointView< MatrixType, UpLo >::eigenvalues inline
Computes the eigenvalues of a matrix.
Returns
Column vector containing the eigenvalues.
\eigenvalues_module This function computes the eigenvalues with the help of the SelfAdjointEigenSolver class. The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix.
Example:
Output:
See also
SelfAdjointEigenSolver::eigenvalues(), MatrixBase::eigenvalues()
{
  PlainObject thisAsMatrix(*this);
  return SelfAdjointEigenSolver<PlainObject>(thisAsMatrix, false).eigenvalues();
}
References Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvalues().
evalTo() [1/3]
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
Referenced by Eigen::EigenBase< Derived >::subTo().
evalTo() [2/3]
EIGEN_DEVICE_FUNC void Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::evalTo (MatrixBase< DenseDerived > & other) const inherited
evalTo() [3/3]
void Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::evalTo (MatrixBase< DenseDerived > & other) const inherited
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
{
  evalToLazy(other.derived());
}
evalToLazy() [1/2]
EIGEN_DEVICE_FUNC void Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::evalToLazy (MatrixBase< DenseDerived > & other) const inherited
evalToLazy() [2/2]
void Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::evalToLazy (MatrixBase< DenseDerived > & other) const inherited
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
{
  other.derived().resize(this->rows(), this->cols());
  internal::call_triangular_assignment_loop<Derived::Mode,(Derived::Mode&SelfAdjoint)==0 /* SetOpposite */>(other.derived(), derived().nestedExpression());
}
innerStride()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC Index Eigen::SelfAdjointView< _MatrixType, UpLo >::innerStride () const inline
{ return m_matrix.innerStride(); }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
ldlt()
template<typename MatrixType , unsigned int UpLo> const LDLT< typename SelfAdjointView< MatrixType, UpLo >::PlainObject, UpLo > Eigen::SelfAdjointView< MatrixType, UpLo >::ldlt inline
\cholesky_module
Returns
the Cholesky decomposition with full pivoting without square root of *this
See also
MatrixBase::ldlt()
{
  return LDLT<PlainObject,UpLo>(m_matrix);
}
llt()
template<typename MatrixType , unsigned int UpLo> const LLT< typename SelfAdjointView< MatrixType, UpLo >::PlainObject, UpLo > Eigen::SelfAdjointView< MatrixType, UpLo >::llt inline
\cholesky_module
Returns
the LLT decomposition of *this
See also
SelfAdjointView::llt()
{
  return LLT<PlainObject,UpLo>(m_matrix);
}
nestedExpression() [1/2]
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC MatrixTypeNestedCleaned & Eigen::SelfAdjointView< _MatrixType, UpLo >::nestedExpression () inline
{ return m_matrix; }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
nestedExpression() [2/2]
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC const MatrixTypeNestedCleaned & Eigen::SelfAdjointView< _MatrixType, UpLo >::nestedExpression () const inline
{ return m_matrix; }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
operator()() [1/2]
EIGEN_DEVICE_FUNC Scalar & Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::operator() (Index row, Index col) inline inherited
    {
      check_coordinates(row, col);
      return coeffRef(row,col);
    }
operator()() [2/2]
EIGEN_DEVICE_FUNC Scalar Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::operator() (Index row, Index col) const inline inherited
    {
      check_coordinates(row, col);
      return coeff(row,col);
    }
operator*()
template<typename _MatrixType , unsigned int UpLo> template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product< SelfAdjointView, OtherDerived > Eigen::SelfAdjointView< _MatrixType, UpLo >::operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient triangular matrix times vector/matrix product
    {
      return Product<SelfAdjointView,OtherDerived>(*this, rhs.derived());
    }
operatorNorm()
template<typename MatrixType , unsigned int UpLo> SelfAdjointView< MatrixType, UpLo >::RealScalar Eigen::SelfAdjointView< MatrixType, UpLo >::operatorNorm inline
Computes the L2 operator norm.
Returns
Operator norm of the matrix.
\eigenvalues_module This function computes the L2 operator norm of a self-adjoint matrix. For a self-adjoint matrix, the operator norm is the largest eigenvalue.
The current implementation uses the eigenvalues of the matrix, as computed by eigenvalues(), to compute the operator norm of the matrix.
Example:
Output:
See also
eigenvalues(), MatrixBase::operatorNorm()
{
  return eigenvalues().cwiseAbs().maxCoeff();
}
outerStride()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC Index Eigen::SelfAdjointView< _MatrixType, UpLo >::outerStride () const inline
{ return m_matrix.outerStride(); }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
rankUpdate() [1/4]
template<typename _MatrixType , unsigned int UpLo> template<typename DerivedU , typename DerivedV > SelfAdjointView< MatrixType, UpLo > & Eigen::SelfAdjointView< _MatrixType, UpLo >::rankUpdate (const MatrixBase< DerivedU > & u, const MatrixBase< DerivedV > & v, const Scalar & alpha)
{
  typedef internal::blas_traits<DerivedU> UBlasTraits;
  typedef typename UBlasTraits::DirectLinearAccessType ActualUType;
  typedef typename internal::remove_all<ActualUType>::type _ActualUType;
  typename internal::add_const_on_value_type<ActualUType>::type actualU = UBlasTraits::extract(u.derived());
  typedef internal::blas_traits<DerivedV> VBlasTraits;
  typedef typename VBlasTraits::DirectLinearAccessType ActualVType;
  typedef typename internal::remove_all<ActualVType>::type _ActualVType;
  typename internal::add_const_on_value_type<ActualVType>::type actualV = VBlasTraits::extract(v.derived());
  // If MatrixType is row major, then we use the routine for lower triangular in the upper triangular case and
  // vice versa, and take the complex conjugate of all coefficients and vector entries.
  enum { IsRowMajor = (internal::traits<MatrixType>::Flags&RowMajorBit) ? 1 : 0 };
  Scalar actualAlpha = alpha * UBlasTraits::extractScalarFactor(u.derived())
                             * numext::conj(VBlasTraits::extractScalarFactor(v.derived()));
  if (IsRowMajor)
    actualAlpha = numext::conj(actualAlpha);
  typedef typename internal::remove_all<typename internal::conj_expr_if<IsRowMajor ^ UBlasTraits::NeedToConjugate,_ActualUType>::type>::type UType;
  typedef typename internal::remove_all<typename internal::conj_expr_if<IsRowMajor ^ VBlasTraits::NeedToConjugate,_ActualVType>::type>::type VType;
  internal::selfadjoint_rank2_update_selector<Scalar, Index, UType, VType,
    (IsRowMajor ? int(UpLo==Upper ? Lower : Upper) : UpLo)>
    ::run(_expression().const_cast_derived().data(),_expression().outerStride(),UType(actualU),VType(actualV),actualAlpha);
  return *this;
}
References Eigen::Lower, Eigen::RowMajorBit, and Eigen::Upper.
rankUpdate() [2/4]
template<typename _MatrixType , unsigned int UpLo> template<typename DerivedU , typename DerivedV > EIGEN_DEVICE_FUNC SelfAdjointView & Eigen::SelfAdjointView< _MatrixType, UpLo >::rankUpdate (const MatrixBase< DerivedU > & u, const MatrixBase< DerivedV > & v, const Scalar & alpha = Scalar(1))
Perform a symmetric rank 2 update of the selfadjoint matrix *this:
Returns
a reference to *this
The vectors u and v must be column vectors, however they can be a adjoint expression without any overhead. Only the meaningful triangular part of the matrix is updated, the rest is left unchanged.
See also
rankUpdate(const MatrixBase<DerivedU>&, Scalar)
rankUpdate() [3/4]
template<typename _MatrixType , unsigned int UpLo> template<typename DerivedU > SelfAdjointView< MatrixType, UpLo > & Eigen::SelfAdjointView< _MatrixType, UpLo >::rankUpdate (const MatrixBase< DerivedU > & u, const Scalar & alpha)
{
  selfadjoint_product_selector<MatrixType,DerivedU,UpLo>::run(_expression().const_cast_derived(), u.derived(), alpha);
  return *this;
}
rankUpdate() [4/4]
template<typename _MatrixType , unsigned int UpLo> template<typename DerivedU > EIGEN_DEVICE_FUNC SelfAdjointView & Eigen::SelfAdjointView< _MatrixType, UpLo >::rankUpdate (const MatrixBase< DerivedU > & u, const Scalar & alpha = Scalar(1))
Perform a symmetric rank K update of the selfadjoint matrix *this: where u is a vector or matrix.
Returns
a reference to *this
Note that to perform you can simply call this function with u.adjoint().
See also
rankUpdate(const MatrixBase<DerivedU>&, const MatrixBase<DerivedV>&, Scalar)
resize()
void Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::resize (Index rows, Index cols) inline inherited
    {
      EIGEN_UNUSED_VARIABLE(rows);
      EIGEN_UNUSED_VARIABLE(cols);
      eigen_assert(rows==this->rows() && cols==this->cols());
    }
rows()
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC Index Eigen::SelfAdjointView< _MatrixType, UpLo >::rows () const inline
{ return m_matrix.rows(); }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
References Eigen::EigenBase< Derived >::cols(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
toDenseMatrix()
EIGEN_DEVICE_FUNC DenseMatrixType Eigen::TriangularBase< SelfAdjointView< _MatrixType, UpLo > >::toDenseMatrix () const inline inherited
    {
      DenseMatrixType res(rows(), cols());
      evalToLazy(res);
      return res;
    }
transpose() [1/2]
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC TransposeReturnType Eigen::SelfAdjointView< _MatrixType, UpLo >::transpose () inline
See also
MatrixBase::transpose()
    {
      EIGEN_STATIC_ASSERT_LVALUE(MatrixType)
      typename MatrixType::TransposeReturnType tmp(m_matrix);
      return TransposeReturnType(tmp);
    }
References EIGEN_STATIC_ASSERT_LVALUE, and Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
transpose() [2/2]
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC const ConstTransposeReturnType Eigen::SelfAdjointView< _MatrixType, UpLo >::transpose () const inline
See also
MatrixBase::transpose() const
    {
      return ConstTransposeReturnType(m_matrix.transpose());
    }
References Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix.
triangularView()
template<typename _MatrixType , unsigned int UpLo> template<unsigned int TriMode> EIGEN_DEVICE_FUNC internal::conditional<(TriMode &(Upper|Lower))==(UpLo &(Upper|Lower)), TriangularView< MatrixType, TriMode >, TriangularView< typenameMatrixType::AdjointReturnType, TriMode > >::type Eigen::SelfAdjointView< _MatrixType, UpLo >::triangularView () const inline
Returns
an expression of a triangular view extracted from the current selfadjoint view of a given triangular part
The parameter TriMode can have the following values: Upper, StrictlyUpper, UnitUpper, Lower, StrictlyLower, UnitLower.
If TriMode references the same triangular part than *this, then this method simply return a TriangularView of the nested expression, otherwise, the nested expression is first transposed, thus returning a TriangularView<Transpose<MatrixType>> object.
See also
MatrixBase::triangularView(), class TriangularView
    {
      typename internal::conditional<(TriMode&(Upper|Lower))==(UpLo&(Upper|Lower)), MatrixType&, typename MatrixType::ConstTransposeReturnType>::type tmp1(m_matrix);
      typename internal::conditional<(TriMode&(Upper|Lower))==(UpLo&(Upper|Lower)), MatrixType&, typename MatrixType::AdjointReturnType>::type tmp2(tmp1);
      return typename internal::conditional<(TriMode&(Upper|Lower))==(UpLo&(Upper|Lower)),
                                   TriangularView<MatrixType,TriMode>,
                                   TriangularView<typename MatrixType::AdjointReturnType,TriMode> >::type(tmp2);
    }
References Eigen::Lower, Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix, and Eigen::Upper.
Friends And Related Symbol Documentation
operator* [1/2]
template<typename _MatrixType , unsigned int UpLo> template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product< OtherDerived, SelfAdjointView > operator* (const MatrixBase< OtherDerived > & lhs, const SelfAdjointView< _MatrixType, UpLo > & rhs) friend
Efficient vector/matrix times triangular matrix product
    {
      return Product<OtherDerived,SelfAdjointView>(lhs.derived(),rhs);
    }
operator* [2/2]
template<typename _MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC const SelfAdjointView< const EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(Scalar, MatrixType, product), UpLo > operator* (const Scalar & s, const SelfAdjointView< _MatrixType, UpLo > & mat) friend
    {
      return (s*mat.nestedExpression()).template selfadjointView<UpLo>();
    }
Member Data Documentation
m_matrix
template<typename _MatrixType , unsigned int UpLo> MatrixTypeNested Eigen::SelfAdjointView< _MatrixType, UpLo >::m_matrix protected
Referenced by Eigen::SelfAdjointView< _MatrixType, UpLo >::_expression(), Eigen::SelfAdjointView< _MatrixType, UpLo >::adjoint(), Eigen::SelfAdjointView< _MatrixType, UpLo >::coeff(), Eigen::SelfAdjointView< _MatrixType, UpLo >::coeffRef(), Eigen::SelfAdjointView< _MatrixType, UpLo >::cols(), Eigen::SelfAdjointView< _MatrixType, UpLo >::conjugate(), Eigen::SelfAdjointView< _MatrixType, UpLo >::diagonal(), Eigen::SelfAdjointView< _MatrixType, UpLo >::innerStride(), Eigen::SelfAdjointView< _MatrixType, UpLo >::nestedExpression(), Eigen::SelfAdjointView< _MatrixType, UpLo >::nestedExpression(), Eigen::SelfAdjointView< _MatrixType, UpLo >::outerStride(), Eigen::SelfAdjointView< _MatrixType, UpLo >::rows(), Eigen::SelfAdjointView< _MatrixType, UpLo >::transpose(), Eigen::SelfAdjointView< _MatrixType, UpLo >::transpose(), and Eigen::SelfAdjointView< _MatrixType, UpLo >::triangularView().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/SelfAdjointView.h
src/eigen/Eigen/src/Cholesky/LDLT.h
src/eigen/Eigen/src/Cholesky/LLT.h
src/eigen/Eigen/src/Core/products/SelfadjointProduct.h
src/eigen/Eigen/src/Core/products/SelfadjointRank2Update.h
src/eigen/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h