Prusa Slicer: Slic3r::GUI::GLMmSegmentationGizmo3DScene Class Reference
Slic3r::GUI::GLMmSegmentationGizmo3DScene Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoMmuSegmentation.hpp>
Public Member Functions
GLMmSegmentationGizmo3DScene ()=delete
GLMmSegmentationGizmo3DScene (size_t triangle_indices_buffers_count)
virtual ~GLMmSegmentationGizmo3DScene ()
bool has_VBOs (size_t triangle_indices_idx) const
void release_geometry ()
void finalize_vertices ()
void finalize_triangle_indices ()
void clear ()
void render (size_t triangle_indices_idx) const
Public Attributes
std::vector< float > vertices
std::vector< std::vector< int > > triangle_indices
std::vector< size_t > triangle_indices_sizes
unsigned int vertices_VBO_id { 0 }
std::vector< unsigned int > triangle_indices_VBO_ids
Detailed Description
Constructor & Destructor Documentation
GLMmSegmentationGizmo3DScene() [1/2]
Slic3r::GUI::GLMmSegmentationGizmo3DScene::GLMmSegmentationGizmo3DScene () delete
GLMmSegmentationGizmo3DScene() [2/2]
Slic3r::GUI::GLMmSegmentationGizmo3DScene::GLMmSegmentationGizmo3DScene (size_t triangle_indices_buffers_count) inline explicit
    {
        this->triangle_indices         = std::vector<std::vector<int>>(triangle_indices_buffers_count);
        this->triangle_indices_sizes   = std::vector<size_t>(triangle_indices_buffers_count);
        this->triangle_indices_VBO_ids = std::vector<unsigned int>(triangle_indices_buffers_count);
    }
References triangle_indices, triangle_indices_sizes, and triangle_indices_VBO_ids.
~GLMmSegmentationGizmo3DScene()
virtual Slic3r::GUI::GLMmSegmentationGizmo3DScene::~GLMmSegmentationGizmo3DScene () inline virtual
{ release_geometry(); }
References release_geometry().
Member Function Documentation
clear()
void Slic3r::GUI::GLMmSegmentationGizmo3DScene::clear () inline
    {
        this->vertices.clear();
        for (std::vector<int> &ti : this->triangle_indices)
            ti.clear();
        for (size_t &triangle_indices_size : this->triangle_indices_sizes)
            triangle_indices_size = 0;
    }
References triangle_indices, triangle_indices_sizes, and vertices.
Referenced by release_geometry().
finalize_triangle_indices()
void Slic3r::GUI::GLMmSegmentationGizmo3DScene::finalize_triangle_indices ()
{
    assert(std::all_of(triangle_indices_VBO_ids.cbegin(), triangle_indices_VBO_ids.cend(), [](const auto &ti_VBO_id) { return ti_VBO_id == 0; }));
    assert(this->triangle_indices.size() == this->triangle_indices_VBO_ids.size());
    for (size_t buffer_idx = 0; buffer_idx < this->triangle_indices.size(); ++buffer_idx)
        if (!this->triangle_indices[buffer_idx].empty()) {
            glsafe(::glGenBuffers(1, &this->triangle_indices_VBO_ids[buffer_idx]));
            glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->triangle_indices_VBO_ids[buffer_idx]));
            glsafe(::glBufferData(GL_ELEMENT_ARRAY_BUFFER, this->triangle_indices[buffer_idx].size() * sizeof(int), this->triangle_indices[buffer_idx].data(), GL_STATIC_DRAW));
            glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
            this->triangle_indices[buffer_idx].clear();
        }
}
References Slic3r::empty(), glsafe, triangle_indices, and triangle_indices_VBO_ids.
Referenced by Slic3r::GUI::TriangleSelectorMmGui::update_render_data().
finalize_vertices()
void Slic3r::GUI::GLMmSegmentationGizmo3DScene::finalize_vertices ()
{
#if ENABLE_GL_CORE_PROFILE
        assert(this->vertices_VAO_id == 0);
#endif // ENABLE_GL_CORE_PROFILE
    assert(this->vertices_VBO_id == 0);
    if (!this->vertices.empty()) {
#if ENABLE_GL_CORE_PROFILE
        if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0)) {
            glsafe(::glGenVertexArrays(1, &this->vertices_VAO_id));
            glsafe(::glBindVertexArray(this->vertices_VAO_id));
        }
#endif // ENABLE_GL_CORE_PROFILE
        glsafe(::glGenBuffers(1, &this->vertices_VBO_id));
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, this->vertices_VBO_id));
        glsafe(::glBufferData(GL_ARRAY_BUFFER, this->vertices.size() * sizeof(float), this->vertices.data(), GL_STATIC_DRAW));
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
        this->vertices.clear();
#if ENABLE_GL_CORE_PROFILE
        if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
        glsafe(::glBindVertexArray(0));
#endif // ENABLE_GL_CORE_PROFILE
    }
}
References Slic3r::GUI::OpenGLManager::get_gl_info(), glsafe, vertices, and vertices_VBO_id.
Referenced by Slic3r::GUI::TriangleSelectorMmGui::update_render_data().
has_VBOs()
bool Slic3r::GUI::GLMmSegmentationGizmo3DScene::has_VBOs (size_t triangle_indices_idx) const inline
    {
        assert(triangle_indices_idx < this->triangle_indices.size());
        return this->triangle_indices_VBO_ids[triangle_indices_idx] != 0;
    }
References triangle_indices, and triangle_indices_VBO_ids.
Referenced by Slic3r::GUI::TriangleSelectorMmGui::render().
release_geometry()
void Slic3r::GUI::GLMmSegmentationGizmo3DScene::release_geometry ()
{
    if (this->vertices_VBO_id) {
        glsafe(::glDeleteBuffers(1, &this->vertices_VBO_id));
        this->vertices_VBO_id = 0;
    }
    for(auto &triangle_indices_VBO_id : triangle_indices_VBO_ids) {
        glsafe(::glDeleteBuffers(1, &triangle_indices_VBO_id));
        triangle_indices_VBO_id = 0;
    }
#if ENABLE_GL_CORE_PROFILE
    if (this->vertices_VAO_id > 0) {
        glsafe(::glDeleteVertexArrays(1, &this->vertices_VAO_id));
        this->vertices_VAO_id = 0;
    }
#endif // ENABLE_GL_CORE_PROFILE
    this->clear();
}
References clear(), glsafe, triangle_indices_VBO_ids, and vertices_VBO_id.
Referenced by ~GLMmSegmentationGizmo3DScene(), and Slic3r::GUI::TriangleSelectorMmGui::update_render_data().
render()
void Slic3r::GUI::GLMmSegmentationGizmo3DScene::render (size_t triangle_indices_idx) const
{
    assert(triangle_indices_idx < this->triangle_indices_VBO_ids.size());
    assert(this->triangle_indices_sizes.size() == this->triangle_indices_VBO_ids.size());
#if ENABLE_GL_CORE_PROFILE
    if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
        assert(this->vertices_VAO_id != 0);
#endif // ENABLE_GL_CORE_PROFILE
    assert(this->vertices_VBO_id != 0);
    assert(this->triangle_indices_VBO_ids[triangle_indices_idx] != 0);
    GLShaderProgram* shader = wxGetApp().get_current_shader();
    if (shader == nullptr)
        return;
#if ENABLE_GL_CORE_PROFILE
    if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
        glsafe(::glBindVertexArray(this->vertices_VAO_id));
    // the following binding is needed to set the vertex attributes
#endif // ENABLE_GL_CORE_PROFILE
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, this->vertices_VBO_id));
    const GLint position_id = shader->get_attrib_location("v_position");
    if (position_id != -1) {
        glsafe(::glVertexAttribPointer(position_id, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (GLvoid*)0));
        glsafe(::glEnableVertexAttribArray(position_id));
    }
    // Render using the Vertex Buffer Objects.
    if (this->triangle_indices_VBO_ids[triangle_indices_idx] != 0 &&
        this->triangle_indices_sizes[triangle_indices_idx] > 0) {
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->triangle_indices_VBO_ids[triangle_indices_idx]));
        glsafe(::glDrawElements(GL_TRIANGLES, GLsizei(this->triangle_indices_sizes[triangle_indices_idx]), GL_UNSIGNED_INT, nullptr));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
    }
    if (position_id != -1)
        glsafe(::glDisableVertexAttribArray(position_id));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
#if ENABLE_GL_CORE_PROFILE
    if (OpenGLManager::get_gl_info().is_version_greater_or_equal_to(3, 0))
        glsafe(::glBindVertexArray(0));
#endif // ENABLE_GL_CORE_PROFILE
}
References Slic3r::GLShaderProgram::get_attrib_location(), Slic3r::GUI::OpenGLManager::get_gl_info(), GL_FALSE, GL_TRIANGLES, glsafe, triangle_indices_sizes, triangle_indices_VBO_ids, and vertices_VBO_id.
Referenced by Slic3r::GUI::TriangleSelectorMmGui::render().
Member Data Documentation
triangle_indices
std::vector<std::vector<int> > Slic3r::GUI::GLMmSegmentationGizmo3DScene::triangle_indices
Referenced by GLMmSegmentationGizmo3DScene(), clear(), finalize_triangle_indices(), has_VBOs(), Slic3r::GUI::TriangleSelectorMmGui::render(), and Slic3r::GUI::TriangleSelectorMmGui::update_render_data().
triangle_indices_sizes
std::vector<size_t> Slic3r::GUI::GLMmSegmentationGizmo3DScene::triangle_indices_sizes
Referenced by GLMmSegmentationGizmo3DScene(), clear(), render(), and Slic3r::GUI::TriangleSelectorMmGui::update_render_data().
triangle_indices_VBO_ids
std::vector<unsigned int> Slic3r::GUI::GLMmSegmentationGizmo3DScene::triangle_indices_VBO_ids
Referenced by GLMmSegmentationGizmo3DScene(), finalize_triangle_indices(), has_VBOs(), release_geometry(), and render().
vertices
std::vector<float> Slic3r::GUI::GLMmSegmentationGizmo3DScene::vertices
Referenced by clear(), finalize_vertices(), and Slic3r::GUI::TriangleSelectorMmGui::update_render_data().
vertices_VBO_id
unsigned int Slic3r::GUI::GLMmSegmentationGizmo3DScene::vertices_VBO_id { 0 }
Referenced by finalize_vertices(), release_geometry(), and render().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoMmuSegmentation.hpp
src/slic3r/GUI/Gizmos/GLGizmoMmuSegmentation.cpp