Prusa Slicer: Slic3r::GUI::ConfigOptionsGroup Class Reference
Slic3r::GUI::ConfigOptionsGroup Class Reference
#include <src/slic3r/GUI/OptionsGroup.hpp>
Public Member Functions
ConfigOptionsGroup (wxWindow *parent, const wxString &title, DynamicPrintConfig *config=nullptr, bool is_tab_opt=false, column_t extra_clmn=nullptr)
ConfigOptionsGroup (wxWindow *parent, const wxString &title, ModelConfig *config, bool is_tab_opt=false, column_t extra_clmn=nullptr)
ConfigOptionsGroup (wxWindow *parent)
~ConfigOptionsGroup () override=default
const wxString & config_category () const throw ()
int config_type () const throw ()
const t_opt_map & opt_map () const throw ()
void set_config_category_and_type (const wxString &category, int type)
void set_config (DynamicPrintConfig *config)
Option get_option (const std::string &opt_key, int opt_index=-1)
Line create_single_option_line (const std::string &title, const std::string &path=std::string(), int idx=-1)
Line create_single_option_line (const Option &option, const std::string &path=std::string()) const
void append_single_option_line (const Option &option, const std::string &path=std::string())
void append_single_option_line (const std::string title, const std::string &path=std::string(), int idx=-1)
void on_change_OG (const t_config_option_key &opt_id, const boost::any &value) override
void back_to_initial_value (const std::string &opt_key) override
void back_to_sys_value (const std::string &opt_key) override
void back_to_config_value (const DynamicPrintConfig &config, const std::string &opt_key)
void on_kill_focus (const std::string &opt_key) override
void reload_config ()
void Hide ()
void Show (const bool show)
bool is_visible (ConfigOptionMode mode)
bool update_visibility (ConfigOptionMode mode)
void msw_rescale ()
void sys_color_changed ()
void refresh ()
boost::any config_value (const std::string &opt_key, int opt_index, bool deserialize)
boost::any get_config_value (const DynamicPrintConfig &config, const std::string &opt_key, int opt_index=-1)
Field * get_fieldc (const t_config_option_key &opt_key, int opt_index)
std::pair< OG_CustomCtrl *, bool * > get_custom_ctrl_with_blinking_ptr (const t_config_option_key &opt_key, int opt_index)
wxWindow * parent () const
Returns a copy of the pointer of the parent wxWindow. Accessor function is because users are not allowed to change the parent but defining it as const means a lot of const_casts to deal with wx functions.
wxWindow * ctrl_parent () const
void append_line (const Line &line)
void activate_line (Line &line)
bool activate (std::function< void()> throw_if_canceled=[](){}, int horiz_alignment=wxALIGN_LEFT)
void clear (bool destroy_custom_ctrl=false)
void append_separator ()
Field * get_field (const t_config_option_key &id) const
Line * get_line (const t_config_option_key &id)
bool set_value (const t_config_option_key &id, const boost::any &value, bool change_event=false)
boost::any get_value (const t_config_option_key &id)
void show_field (const t_config_option_key &opt_key, bool show=true)
void hide_field (const t_config_option_key &opt_key)
void set_name (const wxString &new_name)
wxString get_name () const
void enable ()
void disable ()
void set_grid_vgap (int gap)
void clear_fields_except_of (const std::vector< std::string > left_fields)
void hide_labels ()
wxGridSizer * get_grid_sizer ()
const std::vector< Line > & get_lines ()
bool is_legend_line ()
void set_max_win_width (int max_win_width)
void set_use_custom_ctrl (bool use_custom_ctrl)
const std::map< t_config_option_key, Option > & get_optioms_map ()
bool is_activated ()
Static Public Member Functions
static wxString get_url (const std::string &path_end)
static bool launch_browser (const std::string &path_end)
static bool is_option_without_field (const std::string &opt_key)
Public Attributes
const bool staticbox {true}
const wxString title
size_t label_width = 20
wxSizer * sizer {nullptr}
OG_CustomCtrl * custom_ctrl { nullptr }
int ctrl_horiz_alignment { wxALIGN_LEFT}
column_t extra_column {nullptr}
t_change m_on_change { nullptr }
t_kill_focus m_fill_empty_value { nullptr }
std::function< DynamicPrintConfig()> m_get_initial_config { nullptr }
std::function< DynamicPrintConfig()> m_get_sys_config { nullptr }
std::function< bool()> have_sys_config { nullptr }
std::function< void(wxWindow *win)> rescale_extra_column_item { nullptr }
std::function< void(wxWindow *win)> rescale_near_label_widget { nullptr }
wxFont sidetext_font {wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT) }
wxFont label_font {wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT) }
int sidetext_width { -1 }
int sublabel_width { -1 }
Protected Member Functions
const t_field & build_field (const t_config_option_key &id, const ConfigOptionDef &opt)
Generate a wxSizer or wxWindow from a configuration option Precondition: opt resolves to a known ConfigOption Postcondition: fields contains a wx gui object.
const t_field & build_field (const t_config_option_key &id)
const t_field & build_field (const Option &opt)
Protected Attributes
wxStaticBox * stb {nullptr}
std::map< t_config_option_key, Option > m_options
wxWindow * m_parent {nullptr}
std::vector< ConfigOptionMode > m_options_mode
std::vector< wxWindow * > m_extra_column_item_ptrs
std::vector< Line > m_lines
t_optionfield_map m_fields
Field list, contains unique_ptrs of the derived type. using types that need to know what it is beyond the public interface need to cast based on the related ConfigOptionDef.
bool m_disabled {false}
wxGridSizer * m_grid_sizer {nullptr}
bool m_use_custom_ctrl { false }
bool m_use_custom_ctrl_as_parent { false }
Private Member Functions
void change_opt_value (const t_config_option_key &opt_key, const boost::any &value, int opt_index=0)
Private Attributes
const DynamicPrintConfig * m_config {nullptr}
ModelConfig * m_modelconfig { nullptr }
t_opt_map m_opt_map
wxString m_config_category
int m_config_type
Detailed Description
Constructor & Destructor Documentation
ConfigOptionsGroup() [1/3]
Slic3r::GUI::ConfigOptionsGroup::ConfigOptionsGroup (wxWindow * parent, const wxString & title, DynamicPrintConfig * config = nullptr, bool is_tab_opt = false, column_t extra_clmn = nullptr) inline
                                                                    :
    OptionsGroup(parent, title, is_tab_opt, extra_clmn), m_config(config) {}
ConfigOptionsGroup() [2/3]
Slic3r::GUI::ConfigOptionsGroup::ConfigOptionsGroup (wxWindow * parent, const wxString & title, ModelConfig * config, bool is_tab_opt = false, column_t extra_clmn = nullptr) inline
                                                                    :
    OptionsGroup(parent, title, is_tab_opt, extra_clmn), m_config(&config->get()), m_modelconfig(config) {}
ConfigOptionsGroup() [3/3]
Slic3r::GUI::ConfigOptionsGroup::ConfigOptionsGroup (wxWindow * parent) inline
                                        :
    OptionsGroup(parent, wxEmptyString, true, nullptr) {}
~ConfigOptionsGroup()
Slic3r::GUI::ConfigOptionsGroup::~ConfigOptionsGroup () override default
Member Function Documentation
activate()
bool Slic3r::GUI::OptionsGroup::activate (std::function< void()> throw_if_canceled = [](){}, int horiz_alignment = wxALIGN_LEFT) inherited
{
  if (sizer)//(!sizer->IsEmpty())
    return false;
  try {
    if (staticbox) {
      stb = new wxStaticBox(m_parent, wxID_ANY, _(title));
      if (!wxOSX) stb->SetBackgroundStyle(wxBG_STYLE_PAINT);
      stb->SetFont(wxOSX ? wxGetApp().normal_font() : wxGetApp().bold_font());
      wxGetApp().UpdateDarkUI(stb);
    }
    else
      stb = nullptr;
    sizer = (staticbox ? new wxStaticBoxSizer(stb, wxVERTICAL) : new wxBoxSizer(wxVERTICAL));
    auto num_columns = 1U;
    size_t grow_col = 1;
    if (label_width == 0)
      grow_col = 0;
    else
      num_columns++;
    if (extra_column) {
      num_columns++;
      grow_col++;
    }
    m_grid_sizer = new wxFlexGridSizer(0, num_columns, 1, 0);
    static_cast<wxFlexGridSizer*>(m_grid_sizer)->SetFlexibleDirection(wxBOTH);
    static_cast<wxFlexGridSizer*>(m_grid_sizer)->AddGrowableCol(grow_col);
    sizer->Add(m_grid_sizer, 0, wxEXPAND | wxALL, wxOSX || !staticbox ? 0 : 5);
    // activate lines
    for (Line& line: m_lines) {
      throw_if_canceled();
      activate_line(line);
    }
        ctrl_horiz_alignment = horiz_alignment;
        if (custom_ctrl)
            custom_ctrl->init_max_win_width();
  } catch (UIBuildCanceled&) {
    auto p = sizer;
    this->clear();
    p->Clear(true);
    delete p;
    throw;
  }
  return true;
}
References _, Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::clear(), Slic3r::GUI::OptionsGroup::ctrl_horiz_alignment, Slic3r::GUI::OptionsGroup::custom_ctrl, Slic3r::GUI::OptionsGroup::extra_column, Slic3r::GUI::OG_CustomCtrl::init_max_win_width(), Slic3r::GUI::OptionsGroup::label_width, Slic3r::GUI::OptionsGroup::m_grid_sizer, Slic3r::GUI::OptionsGroup::m_lines, Slic3r::GUI::OptionsGroup::m_parent, Slic3r::GUI::OptionsGroup::sizer, Slic3r::GUI::OptionsGroup::staticbox, Slic3r::GUI::OptionsGroup::stb, Slic3r::GUI::OptionsGroup::title, and wxOSX.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
activate_line()
void Slic3r::GUI::OptionsGroup::activate_line (Line & line) inherited
.target<wxWindow>()
requires verification
istead of (opt != option_set.back())
requires verification
{
    if (line.is_separator())
        return;
    m_use_custom_ctrl_as_parent = false;
  if (line.full_width && (
    line.widget != nullptr ||
    !line.get_extra_widgets().empty())
    ) {
        if (line.widget != nullptr) {
      // description lines
            sizer->Add(line.widget(this->ctrl_parent()), 0, wxEXPAND | wxALL, wxOSX ? 0 : 15);
            return;
        }
    if (!line.get_extra_widgets().empty()) {
      const auto h_sizer = new wxBoxSizer(wxHORIZONTAL);
      sizer->Add(h_sizer, 1, wxEXPAND | wxALL, wxOSX ? 0 : 15);
            bool is_first_item = true;
      for (auto extra_widget : line.get_extra_widgets()) {
        h_sizer->Add(extra_widget(this->ctrl_parent()), is_first_item ? 1 : 0, wxLEFT, 15);
        is_first_item = false;
      }
      return;
    }
    }
    const std::vector<Option>& option_set = line.get_options();
  bool is_legend_line = option_set.front().opt.gui_type == ConfigOptionDef::GUIType::legend;
    if (!custom_ctrl && m_use_custom_ctrl) {
        custom_ctrl = new OG_CustomCtrl(is_legend_line || !staticbox ? this->parent() : static_cast<wxWindow*>(this->stb), this);
    if (is_legend_line)
      sizer->Add(custom_ctrl, 0, wxEXPAND | wxLEFT, wxOSX ? 0 : 10);
    else
            sizer->Add(custom_ctrl, 0, wxEXPAND | wxALL, wxOSX || !staticbox ? 0 : 5);
    }
  // Set sidetext width for a better alignment of options in line
  // "m_show_modified_btns==true" means that options groups are in tabs
  if (option_set.size() > 1 && m_use_custom_ctrl) {
    sidetext_width = Field::def_width_thinner();
  }
  // if we have a single option with no label, no sidetext just add it directly to sizer
    if (option_set.size() == 1 && label_width == 0 && option_set.front().opt.full_width &&
    option_set.front().opt.sidetext.size() == 0 && option_set.front().side_widget == nullptr &&
    line.get_extra_widgets().size() == 0) {
    const auto& option = option_set.front();
    const auto& field = build_field(option);
    if (is_window_field(field))
      sizer->Add(field->getWindow(), 0, wxEXPAND | wxALL, wxOSX ? 0 : 5);
    if (is_sizer_field(field))
      sizer->Add(field->getSizer(), 0, wxEXPAND | wxALL, wxOSX ? 0 : 5);
    return;
  }
    if (custom_ctrl)
        m_use_custom_ctrl_as_parent = true;
    // if we have an extra column, build it
    if (extra_column) {
        m_extra_column_item_ptrs.push_back(extra_column(this->ctrl_parent(), line));
        m_grid_sizer->Add(m_extra_column_item_ptrs.back(), 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, 3);
  }
  // Build a label if we have it
  wxStaticText* label=nullptr;
    if (label_width != 0) {
        if (custom_ctrl) {
            if (line.near_label_widget)
                line.near_label_widget_win = line.near_label_widget(this->ctrl_parent());
        }
        else {
            if (!line.near_label_widget || !line.label.IsEmpty()) {
                // Only create the label if it is going to be displayed.
                long label_style = staticbox ? 0 : wxALIGN_RIGHT;
#ifdef __WXGTK__
                // workaround for correct text align of the StaticBox on Linux
                // flags wxALIGN_RIGHT and wxALIGN_CENTRE don't work when Ellipsize flags are _not_ given.
                // Text is properly aligned only when Ellipsize is checked.
                label_style |= staticbox ? 0 : wxST_ELLIPSIZE_END;
#endif /* __WXGTK__ */
                label = new wxStaticText(this->ctrl_parent(), wxID_ANY, line.label + (line.label.IsEmpty() ? "" : ": "),
                    wxDefaultPosition, wxSize(label_width * wxGetApp().em_unit(), -1), label_style);
                label->SetBackgroundStyle(wxBG_STYLE_PAINT);
                label->SetFont(wxGetApp().normal_font());
                label->Wrap(label_width * wxGetApp().em_unit()); // avoid a Linux/GTK bug
            }
            if (!line.near_label_widget)
                m_grid_sizer->Add(label, 0, (staticbox ? 0 : wxALIGN_RIGHT | wxRIGHT) | wxALIGN_CENTER_VERTICAL, line.label.IsEmpty() ? 0 : 5);
            else if (!line.label.IsEmpty()) {
                // If we're here, we have some widget near the label
                // so we need a horizontal sizer to arrange these things
                auto sizer = new wxBoxSizer(wxHORIZONTAL);
                m_grid_sizer->Add(sizer, 0, wxEXPAND | (staticbox ? wxALL : wxBOTTOM | wxTOP | wxLEFT), staticbox ? 0 : 1);
                sizer->Add(label, 0, (staticbox ? 0 : wxALIGN_RIGHT | wxRIGHT) | wxALIGN_CENTER_VERTICAL, 5);
            }
            if (label != nullptr && line.label_tooltip != "")
                label->SetToolTip(line.label_tooltip);
        }
    }
  // If there's a widget, build it and add the result to the sizer.
  if (line.widget != nullptr) {
    auto wgt = line.widget(this->ctrl_parent());
        if (custom_ctrl)
            line.widget_sizer = wgt;
        else
            m_grid_sizer->Add(wgt, 0, wxEXPAND | wxBOTTOM | wxTOP, (wxOSX || line.label.IsEmpty()) ? 0 : 5);
    return;
  }
  // If we're here, we have more than one option or a single option with sidetext
    // so we need a horizontal sizer to arrange these things
    wxBoxSizer* h_sizer{ nullptr };
    if (!custom_ctrl) {
        // but this sizer is currently used just for NON-custom_ctrl cases
        h_sizer = new wxBoxSizer(wxHORIZONTAL);
        m_grid_sizer->Add(h_sizer, 0, wxEXPAND | (staticbox ? wxALL : wxBOTTOM | wxTOP | wxLEFT), staticbox ? 0 : 1);
    }
    // If we have a single option with no sidetext just add it directly to the grid sizer
    if (option_set.size() == 1 && option_set.front().opt.sidetext.size() == 0 &&
    option_set.front().side_widget == nullptr && line.get_extra_widgets().size() == 0) {
    const auto& option = option_set.front();
    const auto& field = build_field(option);
        if (!custom_ctrl) {
            if (is_window_field(field))
                h_sizer->Add(field->getWindow(), option.opt.full_width ? 1 : 0,
                    wxBOTTOM | wxTOP | (option.opt.full_width ? int(wxEXPAND) : int(wxALIGN_CENTER_VERTICAL)), (wxOSX || !staticbox) ? 0 : 2);
            if (is_sizer_field(field))
                h_sizer->Add(field->getSizer(), 1, (option.opt.full_width ? int(wxEXPAND) : int(wxALIGN_CENTER_VERTICAL)), 0);
        }
        return;
  }
    for (const Option& opt : option_set) {
        // add field
        auto& field = build_field(opt);
        if (!custom_ctrl) {
            ConfigOptionDef option = opt.opt;
            // add label if any
            if ((option_set.size() > 1 || line.label.IsEmpty()) && !option.label.empty()) {
                // those two parameter names require localization with context
                wxString str_label = (option.label == "Top" || option.label == "Bottom") ?
                    _CTX(option.label, "Layers") :
                    _(option.label);
                label = new wxStaticText(this->ctrl_parent(), wxID_ANY, str_label + ": ", wxDefaultPosition, //wxDefaultSize);
                    wxSize(sublabel_width != -1 ? sublabel_width * wxGetApp().em_unit() : -1, -1), wxALIGN_RIGHT);
                label->SetBackgroundStyle(wxBG_STYLE_PAINT);
                label->SetFont(wxGetApp().normal_font());
                h_sizer->Add(label, 0, wxALIGN_CENTER_VERTICAL, 0);
            }
            if (option_set.size() == 1 && option_set.front().opt.full_width)
            {
                const auto v_sizer = new wxBoxSizer(wxVERTICAL);
                h_sizer->Add(v_sizer, 1, wxEXPAND);
                is_sizer_field(field) ?
                    v_sizer->Add(field->getSizer(), 0, wxEXPAND) :
                    v_sizer->Add(field->getWindow(), 0, wxEXPAND);
                break;
            }
            is_sizer_field(field) ?
                h_sizer->Add(field->getSizer(), 0, wxALIGN_CENTER_VERTICAL, 0) :
                h_sizer->Add(field->getWindow(), 0, wxALIGN_CENTER_VERTICAL, 0);
            // add sidetext if any
            if (!option.sidetext.empty() || sidetext_width > 0) {
                auto sidetext = new wxStaticText(this->ctrl_parent(), wxID_ANY, _(option.sidetext), wxDefaultPosition,
                    wxSize(sidetext_width != -1 ? sidetext_width * wxGetApp().em_unit() : -1, -1), wxALIGN_LEFT);
                sidetext->SetBackgroundStyle(wxBG_STYLE_PAINT);
                sidetext->SetFont(wxGetApp().normal_font());
                h_sizer->Add(sidetext, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, 4);
            }
            // add side widget if any
            if (opt.side_widget != nullptr) {
                h_sizer->Add(opt.side_widget(this->ctrl_parent()), 0, wxLEFT | wxALIGN_CENTER_VERTICAL, 1);
            }
            if (opt.opt_id != option_set.back().opt_id)
                h_sizer->AddSpacer(6);
        }
    }
    // add extra sizers if any
    for (auto extra_widget : line.get_extra_widgets())
    {
        if (line.get_extra_widgets().size() == 1 && !staticbox)
        {
            // extra widget for non-staticbox option group (like for the frequently used parameters on the sidebar) should be wxALIGN_RIGHT
            const auto v_sizer = new wxBoxSizer(wxVERTICAL);
            h_sizer->Add(v_sizer, option_set.size() == 1 ? 0 : 1, wxEXPAND);
            v_sizer->Add(extra_widget(this->ctrl_parent()), 0, wxALIGN_RIGHT);
            return;
        }
        line.extra_widget_sizer = extra_widget(this->ctrl_parent());
        if (!custom_ctrl)
            h_sizer->Add(line.extra_widget_sizer, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, 4);
    }
}
References _, _CTX, Slic3r::GUI::OptionsGroup::build_field(), Slic3r::GUI::OptionsGroup::ctrl_parent(), Slic3r::GUI::OptionsGroup::custom_ctrl, Slic3r::GUI::Field::def_width_thinner(), em_unit(), Slic3r::GUI::OptionsGroup::extra_column, Slic3r::GUI::Line::extra_widget_sizer, Slic3r::GUI::Line::full_width, Slic3r::GUI::Line::get_extra_widgets(), Slic3r::GUI::Line::get_options(), Slic3r::GUI::OptionsGroup::is_legend_line(), Slic3r::GUI::Line::is_separator(), Slic3r::GUI::is_sizer_field(), Slic3r::GUI::is_window_field(), Slic3r::GUI::Line::label, Slic3r::GUI::Line::label_tooltip, Slic3r::GUI::OptionsGroup::label_width, Slic3r::ConfigOptionDef::legend, Slic3r::GUI::OptionsGroup::m_extra_column_item_ptrs, Slic3r::GUI::OptionsGroup::m_grid_sizer, Slic3r::GUI::OptionsGroup::m_use_custom_ctrl, Slic3r::GUI::OptionsGroup::m_use_custom_ctrl_as_parent, Slic3r::GUI::Line::near_label_widget, Slic3r::GUI::Line::near_label_widget_win, Slic3r::GUI::OptionsGroup::parent(), Slic3r::GUI::OptionsGroup::sidetext_width, Slic3r::GUI::OptionsGroup::sizer, Slic3r::GUI::OptionsGroup::staticbox, Slic3r::GUI::OptionsGroup::stb, Slic3r::GUI::OptionsGroup::sublabel_width, Slic3r::GUI::Line::widget, Slic3r::GUI::Line::widget_sizer, and wxOSX.
Referenced by Slic3r::GUI::OptionsGroup::activate().
append_line()
void Slic3r::GUI::OptionsGroup::append_line (const Line & line) inherited
{
  m_lines.emplace_back(line);
  if (line.full_width && (
    line.widget != nullptr ||
    !line.get_extra_widgets().empty())
    )
    return;
  auto option_set = line.get_options();
  for (auto opt : option_set)
    m_options.emplace(opt.opt_id, opt);
  // add mode value for current line to m_options_mode
    if (!option_set.empty())
        m_options_mode.push_back(option_set[0].opt.mode);
}
References Slic3r::GUI::Line::full_width, Slic3r::GUI::Line::get_extra_widgets(), Slic3r::GUI::Line::get_options(), Slic3r::GUI::OptionsGroup::m_lines, Slic3r::GUI::OptionsGroup::m_options, Slic3r::GUI::OptionsGroup::m_options_mode, and Slic3r::GUI::Line::widget.
Referenced by Slic3r::GUI::OptionsGroup::append_single_option_line(), Slic3r::GUI::Tab::build_preset_description_line(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), and Slic3r::GUI::Tab::create_line_with_widget().
append_separator()
void Slic3r::GUI::OptionsGroup::append_separator () inherited
{
    m_lines.emplace_back(Line());
}
References Slic3r::GUI::OptionsGroup::m_lines.
append_single_option_line() [1/2]
void Slic3r::GUI::ConfigOptionsGroup::append_single_option_line (const Option & option, const std::string & path = std::string()) inline
{
    OptionsGroup::append_single_option_line(option, path);
  }
References Slic3r::GUI::OptionsGroup::append_single_option_line().
Referenced by append_single_option_line(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
append_single_option_line() [2/2]
void Slic3r::GUI::ConfigOptionsGroup::append_single_option_line (const std::string title, const std::string & path = std::string(), int idx = -1) inline
  {
    Option option = get_option(title, idx);
    append_single_option_line(option, path);
  }
References append_single_option_line(), get_option(), and Slic3r::GUI::OptionsGroup::title.
back_to_config_value()
void Slic3r::GUI::ConfigOptionsGroup::back_to_config_value (const DynamicPrintConfig & config, const std::string & opt_key)
{
  boost::any value;
  if (opt_key == "bed_shape") {
        for (const std::string& key : {"bed_custom_texture", "bed_custom_model"}) {
            value = config.opt_string(key);
            this->change_opt_value(key, value);
        }
  }
  if (opt_key == "extruders_count") {
    auto   *nozzle_diameter = dynamic_cast<const ConfigOptionFloats*>(config.option("nozzle_diameter"));
    value = int(nozzle_diameter->values.size());
  }
    else if (m_opt_map.find(opt_key) == m_opt_map.end() ||
        // This option doesn't have corresponded field
             is_option_without_field(opt_key) ) {
        value = get_config_value(config, opt_key);
        this->change_opt_value(opt_key, value);
        OptionsGroup::on_change_OG(opt_key, value);
        return;
    }
  else
  {
    auto opt_id = m_opt_map.find(opt_key)->first;
    std::string opt_short_key = m_opt_map.at(opt_id).first;
    int opt_index = m_opt_map.at(opt_id).second;
    value = get_config_value(config, opt_short_key, opt_index);
  }
  set_value(opt_key, value);
  on_change_OG(opt_key, get_value(opt_key));
}
References change_opt_value(), get_config_value(), Slic3r::GUI::OptionsGroup::get_value(), Slic3r::GUI::OptionsGroup::is_option_without_field(), m_opt_map, Slic3r::GUI::OptionsGroup::on_change_OG(), on_change_OG(), Slic3r::ConfigBase::opt_string(), Slic3r::ConfigBase::option(), and Slic3r::GUI::OptionsGroup::set_value().
Referenced by back_to_initial_value(), and back_to_sys_value().
back_to_initial_value()
void Slic3r::GUI::ConfigOptionsGroup::back_to_initial_value (const std::string & opt_key) override virtual
Reimplemented from Slic3r::GUI::OptionsGroup.
{
  if (m_get_initial_config == nullptr)
    return;
  back_to_config_value(m_get_initial_config(), opt_key);
}
References back_to_config_value(), and Slic3r::GUI::OptionsGroup::m_get_initial_config.
back_to_sys_value()
void Slic3r::GUI::ConfigOptionsGroup::back_to_sys_value (const std::string & opt_key) override virtual
Reimplemented from Slic3r::GUI::OptionsGroup.
{
  if (m_get_sys_config == nullptr)
    return;
  if (!have_sys_config())
    return;
  back_to_config_value(m_get_sys_config(), opt_key);
}
References back_to_config_value(), Slic3r::GUI::OptionsGroup::have_sys_config, and Slic3r::GUI::OptionsGroup::m_get_sys_config.
build_field() [1/3]
const t_field & Slic3r::GUI::OptionsGroup::build_field (const Option & opt) protected inherited
{
    return build_field(opt.opt_id, opt.opt);
}
References Slic3r::GUI::OptionsGroup::build_field(), Slic3r::GUI::Option::opt, and Slic3r::GUI::Option::opt_id.
build_field() [2/3]
const t_field & Slic3r::GUI::OptionsGroup::build_field (const t_config_option_key & id) protected inherited
{
  const ConfigOptionDef& opt = m_options.at(id).opt;
    return build_field(id, opt);
}
References Slic3r::GUI::OptionsGroup::build_field(), and Slic3r::GUI::OptionsGroup::m_options.
build_field() [3/3]
const t_field & Slic3r::GUI::OptionsGroup::build_field (const t_config_option_key & id, const ConfigOptionDef & opt) protected inherited
Generate a wxSizer or wxWindow from a configuration option Precondition: opt resolves to a known ConfigOption Postcondition: fields contains a wx gui object.
This function will be called from Field. Call OptionGroup._on_change(...)
This function will be called from Field.
{
    // Check the gui_type field first, fall through
    // is the normal type.
    switch (opt.gui_type) {
    case ConfigOptionDef::GUIType::select_close:
    case ConfigOptionDef::GUIType::select_open:
    case ConfigOptionDef::GUIType::f_enum_open:
    case ConfigOptionDef::GUIType::i_enum_open:
        m_fields.emplace(id, Choice::Create<Choice>(this->ctrl_parent(), opt, id));
        break;
    case ConfigOptionDef::GUIType::color:
        m_fields.emplace(id, ColourPicker::Create<ColourPicker>(this->ctrl_parent(), opt, id));
        break;
    case ConfigOptionDef::GUIType::slider:
        m_fields.emplace(id, SliderCtrl::Create<SliderCtrl>(this->ctrl_parent(), opt, id));
        break;
    case ConfigOptionDef::GUIType::legend: // StaticText
        m_fields.emplace(id, StaticText::Create<StaticText>(this->ctrl_parent(), opt, id));
        break;
    case ConfigOptionDef::GUIType::one_string:
        m_fields.emplace(id, TextCtrl::Create<TextCtrl>(this->ctrl_parent(), opt, id));
        break;
    default:
        switch (opt.type) {
            case coFloatOrPercent:
            case coFloatsOrPercents:
            case coFloat:
            case coFloats:
      case coPercent:
      case coPercents:
      case coString:
      case coStrings:
                m_fields.emplace(id, TextCtrl::Create<TextCtrl>(this->ctrl_parent(), opt, id));
                break;
      case coBool:
      case coBools:
                m_fields.emplace(id, CheckBox::Create<CheckBox>(this->ctrl_parent(), opt, id));
        break;
      case coInt:
      case coInts:
                m_fields.emplace(id, SpinCtrl::Create<SpinCtrl>(this->ctrl_parent(), opt, id));
        break;
            case coEnum:
                m_fields.emplace(id, Choice::Create<Choice>(this->ctrl_parent(), opt, id));
        break;
            case coPoints:
                m_fields.emplace(id, PointCtrl::Create<PointCtrl>(this->ctrl_parent(), opt, id));
        break;
            case coNone:   break;
            default:
        throw Slic3r::LogicError("This control doesn't exist till now"); break;
        }
    }
    // Grab a reference to fields for convenience
    const t_field& field = m_fields[id];
  field->m_on_change = [this](const std::string& opt_id, const boost::any& value) {
      if (!m_disabled)
        this->on_change_OG(opt_id, value);
  };
    field->m_on_kill_focus = [this](const std::string& opt_id) {
      if (!m_disabled)
        this->on_kill_focus(opt_id);
  };
    field->m_parent = parent();
  field->m_back_to_initial_value = [this](std::string opt_id) {
    if (!m_disabled)
      this->back_to_initial_value(opt_id);
  };
  field->m_back_to_sys_value = [this](std::string opt_id) {
    if (!m_disabled)
      this->back_to_sys_value(opt_id);
  };
  // assign function objects for callbacks, etc.
    return field;
}
References Slic3r::GUI::OptionsGroup::back_to_initial_value(), Slic3r::GUI::OptionsGroup::back_to_sys_value(), Slic3r::coBool, Slic3r::coBools, Slic3r::coEnum, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coFloats, Slic3r::coFloatsOrPercents, Slic3r::coInt, Slic3r::coInts, Slic3r::ConfigOptionDef::color, Slic3r::coNone, Slic3r::coPercent, Slic3r::coPercents, Slic3r::coPoints, Slic3r::coString, Slic3r::coStrings, Slic3r::GUI::OptionsGroup::ctrl_parent(), Slic3r::ConfigOptionDef::f_enum_open, Slic3r::ConfigOptionDef::gui_type, Slic3r::ConfigOptionDef::i_enum_open, Slic3r::ConfigOptionDef::legend, Slic3r::GUI::OptionsGroup::m_disabled, Slic3r::GUI::OptionsGroup::m_fields, Slic3r::GUI::OptionsGroup::on_change_OG(), Slic3r::GUI::OptionsGroup::on_kill_focus(), Slic3r::ConfigOptionDef::one_string, Slic3r::GUI::OptionsGroup::parent(), Slic3r::ConfigOptionDef::select_close, Slic3r::ConfigOptionDef::select_open, Slic3r::ConfigOptionDef::slider, and Slic3r::ConfigOptionDef::type.
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::build_field(), and Slic3r::GUI::OptionsGroup::build_field().
change_opt_value()
void Slic3r::GUI::ConfigOptionsGroup::change_opt_value (const t_config_option_key & opt_key, const boost::any & value, int opt_index = 0) private
{
  Slic3r::GUI::change_opt_value(const_cast<DynamicPrintConfig&>(*m_config), opt_key, value, opt_index);
  if (m_modelconfig)
    m_modelconfig->touch();
}
References Slic3r::GUI::change_opt_value(), m_config, m_modelconfig, and Slic3r::ModelConfig::touch().
Referenced by back_to_config_value(), and on_change_OG().
clear()
void Slic3r::GUI::OptionsGroup::clear (bool destroy_custom_ctrl = false) inherited
{
  if (!sizer)
    return;
  m_grid_sizer = nullptr;
  sizer = nullptr;
    for (Line& line : m_lines)
        line.clear();
    if (custom_ctrl) {
        for (auto const &item : m_fields) {
            wxWindow* win = item.second.get()->getWindow();
            if (win)
                win = nullptr;
        }
        if (destroy_custom_ctrl)
            custom_ctrl->Destroy();
        else
            custom_ctrl = nullptr;
    }
  m_extra_column_item_ptrs.clear();
  m_fields.clear();
}
References Slic3r::GUI::OptionsGroup::custom_ctrl, Slic3r::GUI::OptionsGroup::m_extra_column_item_ptrs, Slic3r::GUI::OptionsGroup::m_fields, Slic3r::GUI::OptionsGroup::m_grid_sizer, Slic3r::GUI::OptionsGroup::m_lines, and Slic3r::GUI::OptionsGroup::sizer.
Referenced by Slic3r::GUI::OptionsGroup::~OptionsGroup(), and Slic3r::GUI::OptionsGroup::activate().
clear_fields_except_of()
void Slic3r::GUI::OptionsGroup::clear_fields_except_of (const std::vector< std::string > left_fields) inherited
{
    auto it = m_fields.begin();
    while (it != m_fields.end()) {
        if (std::find(left_fields.begin(), left_fields.end(), it->first) == left_fields.end())
            it = m_fields.erase(it);
        else
            it++;
    }
}
References Slic3r::GUI::OptionsGroup::m_fields.
config_category()
const wxString & Slic3r::GUI::ConfigOptionsGroup::config_category () const throw () inline
{ return m_config_category; }
References m_config_category.
Referenced by get_option().
config_type()
int Slic3r::GUI::ConfigOptionsGroup::config_type () const throw () inline
{ return m_config_type; }
References m_config_type.
Referenced by get_option().
config_value()
boost::any Slic3r::GUI::ConfigOptionsGroup::config_value (const std::string & opt_key, int opt_index, bool deserialize)
{
  if (deserialize) {
    // Want to edit a vector value(currently only multi - strings) in a single edit box.
    // Aggregate the strings the old way.
    // Currently used for the post_process config value only.
    if (opt_index != -1)
      throw Slic3r::OutOfRange("Can't deserialize option indexed value");
//    return join(';', m_config->get(opt_key)});
    return get_config_value(*m_config, opt_key);
  }
  else {
//    return opt_index == -1 ? m_config->get(opt_key) : m_config->get_at(opt_key, opt_index);
    return get_config_value(*m_config, opt_key, opt_index);
  }
}
References get_config_value(), and m_config.
Referenced by reload_config().
create_single_option_line() [1/2]
Line Slic3r::GUI::ConfigOptionsGroup::create_single_option_line (const Option & option, const std::string & path = std::string()) const inline
{
    return OptionsGroup::create_single_option_line(option, path);
  }
References Slic3r::GUI::OptionsGroup::create_single_option_line().
create_single_option_line() [2/2]
Line Slic3r::GUI::ConfigOptionsGroup::create_single_option_line (const std::string & title, const std::string & path = std::string(), int idx = -1) inline
{
    Option option = get_option(title, idx);
    return OptionsGroup::create_single_option_line(option, path);
  }
References Slic3r::GUI::OptionsGroup::create_single_option_line(), get_option(), and Slic3r::GUI::OptionsGroup::title.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), and Slic3r::GUI::Tab::create_line_with_widget().
ctrl_parent()
wxWindow * Slic3r::GUI::OptionsGroup::ctrl_parent () const inherited
{
  return this->custom_ctrl && m_use_custom_ctrl_as_parent ? static_cast<wxWindow*>(this->custom_ctrl) : (this->stb ? static_cast<wxWindow*>(this->stb) : this->parent());
}
References Slic3r::GUI::OptionsGroup::custom_ctrl, Slic3r::GUI::OptionsGroup::m_use_custom_ctrl_as_parent, Slic3r::GUI::OptionsGroup::parent(), and Slic3r::GUI::OptionsGroup::stb.
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), and Slic3r::GUI::OptionsGroup::build_field().
disable()
void Slic3r::GUI::OptionsGroup::disable () inline inherited
{ for (auto& field : m_fields) field.second->disable(); }
References Slic3r::GUI::OptionsGroup::m_fields.
enable()
void Slic3r::GUI::OptionsGroup::enable () inline inherited
{ for (auto& field : m_fields) field.second->enable(); }
References Slic3r::GUI::OptionsGroup::m_fields.
get_config_value()
boost::any Slic3r::GUI::ConfigOptionsGroup::get_config_value (const DynamicPrintConfig & config, const std::string & opt_key, int opt_index = -1)
{
  size_t idx = opt_index == -1 ? 0 : opt_index;
  boost::any ret;
  wxString text_value = wxString("");
  const ConfigOptionDef* opt = config.def()->get(opt_key);
    if (opt->nullable)
    {
        switch (opt->type)
        {
        case coPercents:
        case coFloats: {
            if (config.option(opt_key)->is_nil())
                ret = _(L("N/A"));
            else {
                double val = opt->type == coFloats ?
                            config.option<ConfigOptionFloatsNullable>(opt_key)->get_at(idx) :
                            config.option<ConfigOptionPercentsNullable>(opt_key)->get_at(idx);
                ret = double_to_string(val); }
            }
            break;
        case coBools:
            ret = config.option<ConfigOptionBoolsNullable>(opt_key)->values[idx];
            break;
        case coInts:
            ret = config.option<ConfigOptionIntsNullable>(opt_key)->get_at(idx);
            break;
        default:
            break;
        }
        return ret;
    }
  switch (opt->type) {
  case coFloatOrPercent:{
    const auto &value = *config.option<ConfigOptionFloatOrPercent>(opt_key);
        text_value = double_to_string(value.value);
    if (value.percent)
      text_value += "%";
    ret = text_value;
    break;
  }
  case coFloatsOrPercents:{
    const auto& val = config.option<ConfigOptionFloatsOrPercents>(opt_key)->get_at(idx);
        text_value = double_to_string(val.value);
    if (val.percent)
      text_value += "%";
    ret = text_value;
    break;
  }
  case coPercent:{
    double val = config.option<ConfigOptionPercent>(opt_key)->value;
    text_value = wxString::Format(_T("%i"), int(val));
    ret = text_value;// += "%";
  }
    break;
  case coPercents:
  case coFloats:
  case coFloat:{
    double val = opt->type == coFloats ?
          config.opt_float(opt_key, idx) :
            opt->type == coFloat ? config.opt_float(opt_key) :
            config.option<ConfigOptionPercents>(opt_key)->get_at(idx);
    ret = double_to_string(val);
    }
    break;
  case coString:
    ret = from_u8(config.opt_string(opt_key));
    break;
  case coStrings:
    if (opt_key == "compatible_printers" || opt_key == "compatible_prints" || opt_key == "gcode_substitutions") {
      ret = config.option<ConfigOptionStrings>(opt_key)->values;
      break;
    }
    if (opt_key == "filament_ramming_parameters") {
      ret = config.opt_string(opt_key, static_cast<unsigned int>(idx));
      break;
    }
    if (config.option<ConfigOptionStrings>(opt_key)->values.empty())
      ret = text_value;
    else if (opt->gui_flags == "serialized") {
      std::vector<std::string> values = config.option<ConfigOptionStrings>(opt_key)->values;
      if (!values.empty() && !values[0].empty())
        for (auto el : values)
          text_value += el + ";";
      ret = text_value;
    }
    else
      ret = from_u8(config.opt_string(opt_key, static_cast<unsigned int>(idx)));
    break;
  case coBool:
    ret = config.opt_bool(opt_key);
    break;
  case coBools:
    ret = config.opt_bool(opt_key, idx);
    break;
  case coInt:
    ret = config.opt_int(opt_key);
    break;
  case coInts:
    ret = config.opt_int(opt_key, idx);
    break;
  case coEnum:
        ret = config.option(opt_key)->getInt();
    break;
  case coPoints:
    if (opt_key == "bed_shape")
      ret = config.option<ConfigOptionPoints>(opt_key)->values;
        else if (opt_key == "thumbnails")
            ret = get_thumbnails_string(config.option<ConfigOptionPoints>(opt_key)->values);
    else
      ret = config.option<ConfigOptionPoints>(opt_key)->get_at(idx);
    break;
  case coNone:
  default:
    break;
  }
  return ret;
}
References _, Slic3r::coBool, Slic3r::coBools, Slic3r::coEnum, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coFloats, Slic3r::coFloatsOrPercents, Slic3r::coInt, Slic3r::coInts, Slic3r::coNone, Slic3r::coPercent, Slic3r::coPercents, Slic3r::coPoints, Slic3r::coString, Slic3r::coStrings, Slic3r::DynamicPrintConfig::def(), Slic3r::GUI::double_to_string(), Slic3r::GUI::from_u8(), Slic3r::ConfigDef::get(), Slic3r::GUI::get_thumbnails_string(), Slic3r::ConfigOption::getInt(), Slic3r::ConfigOptionDef::gui_flags, Slic3r::ConfigOption::is_nil(), L, Slic3r::ConfigOptionDef::nullable, Slic3r::ConfigBase::opt_bool(), Slic3r::ConfigBase::opt_float(), Slic3r::ConfigBase::opt_int(), Slic3r::ConfigBase::opt_string(), Slic3r::ConfigBase::option(), Slic3r::ConfigOptionDef::type, and Slic3r::ConfigOptionVector< T >::values.
Referenced by back_to_config_value(), config_value(), and Slic3r::GUI::Tab::on_value_change().
get_custom_ctrl_with_blinking_ptr()
std::pair< OG_CustomCtrl *, bool * > Slic3r::GUI::ConfigOptionsGroup::get_custom_ctrl_with_blinking_ptr (const t_config_option_key & opt_key, int opt_index)
{
  Field* field = get_fieldc(opt_key, opt_index);
  if (field)
    return {custom_ctrl, field->get_blink_ptr()};
  for (Line& line : m_lines)
    for (const Option& opt : line.get_options())
      if (opt.opt_id == opt_key && line.widget)
        return { custom_ctrl, line.get_blink_ptr() };
  return { nullptr, nullptr };
}
References Slic3r::GUI::OptionsGroup::custom_ctrl, Slic3r::GUI::UndoValueUIManager::get_blink_ptr(), get_fieldc(), and Slic3r::GUI::OptionsGroup::m_lines.
get_field()
Field * Slic3r::GUI::OptionsGroup::get_field (const t_config_option_key & id) const inline inherited
{
              if (m_fields.find(id) == m_fields.end()) return nullptr;
              return m_fields.at(id).get();
    }
References Slic3r::GUI::OptionsGroup::m_fields.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), get_fieldc(), Slic3r::GUI::OG_CustomCtrl::get_pos(), Slic3r::GUI::OG_CustomCtrl::OnLeftDown(), Slic3r::GUI::OG_CustomCtrl::OnMotion(), Slic3r::GUI::OptionsGroup::show_field(), Slic3r::GUI::PhysicalPrinterDialog::update(), Slic3r::GUI::PhysicalPrinterDialog::update_host_type(), and Slic3r::GUI::PhysicalPrinterDialog::update_printers().
get_fieldc()
Field * Slic3r::GUI::ConfigOptionsGroup::get_fieldc (const t_config_option_key & opt_key, int opt_index)
{
  Field* field = get_field(opt_key);
  if (field != nullptr)
    return field;
  std::string opt_id = "";
  for (t_opt_map::iterator it = m_opt_map.begin(); it != m_opt_map.end(); ++it) {
    if (opt_key == m_opt_map.at(it->first).first && opt_index == m_opt_map.at(it->first).second) {
      opt_id = it->first;
      break;
    }
  }
  return opt_id.empty() ? nullptr : get_field(opt_id);
}
References Slic3r::GUI::OptionsGroup::get_field(), and m_opt_map.
Referenced by get_custom_ctrl_with_blinking_ptr().
get_grid_sizer()
wxGridSizer * Slic3r::GUI::OptionsGroup::get_grid_sizer () inline inherited
{ return m_grid_sizer; }
References Slic3r::GUI::OptionsGroup::m_grid_sizer.
get_line()
Line * Slic3r::GUI::OptionsGroup::get_line (const t_config_option_key & id) inline inherited
{
    for (Line& line : m_lines)
      if (line.has_only_option(id))
        return &line;
    return nullptr;
    }
References Slic3r::GUI::OptionsGroup::m_lines.
get_lines()
const std::vector< Line > & Slic3r::GUI::OptionsGroup::get_lines () inline inherited
{ return m_lines; }
References Slic3r::GUI::OptionsGroup::m_lines.
Referenced by Slic3r::GUI::OG_CustomCtrl::init_ctrl_lines().
get_name()
wxString Slic3r::GUI::OptionsGroup::get_name () const inline inherited
{ return stb->GetLabel(); }
References Slic3r::GUI::OptionsGroup::stb.
get_optioms_map()
const std::map< t_config_option_key, Option > & Slic3r::GUI::OptionsGroup::get_optioms_map () inline inherited
{ return m_options; }
References Slic3r::GUI::OptionsGroup::m_options.
get_option()
Option Slic3r::GUI::ConfigOptionsGroup::get_option (const std::string & opt_key, int opt_index = -1)
{
  if (!m_config->has(opt_key)) {
    std::cerr << "No " << opt_key << " in ConfigOptionsGroup config.\n";
  }
  std::string opt_id = opt_index == -1 ? opt_key : opt_key + "#" + std::to_string(opt_index);
  std::pair<std::string, int> pair(opt_key, opt_index);
  m_opt_map.emplace(opt_id, pair);
  if (m_use_custom_ctrl) // fill group and category values just for options from Settings Tab
      wxGetApp().sidebar().get_searcher().add_key(opt_id, static_cast<Preset::Type>(this->config_type()), title, this->config_category());
  return Option(*m_config->def()->get(opt_key), opt_id);
}
References config_category(), config_type(), Slic3r::DynamicPrintConfig::def(), Slic3r::ConfigDef::get(), Slic3r::ConfigOptionResolver::has(), m_config, m_opt_map, Slic3r::GUI::OptionsGroup::m_use_custom_ctrl, and Slic3r::GUI::OptionsGroup::title.
Referenced by append_single_option_line(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), and create_single_option_line().
get_url()
wxString Slic3r::GUI::OptionsGroup::get_url (const std::string & path_end) static inherited
{
    if (path_end.empty())
        return wxEmptyString;
    wxString language = get_app_config()->get("translation_language");
    wxString lang_marker = language.IsEmpty() ? "en" : language.BeforeFirst('_');
    return wxString("https://help.prusa3d.com/") + lang_marker + wxString("/article/" + path_end);
}
References Slic3r::AppConfig::get(), and Slic3r::GUI::get_app_config().
Referenced by Slic3r::GUI::OptionsGroup::launch_browser(), Slic3r::GUI::OG_CustomCtrl::OnMotion(), and Slic3r::GUI::ogStaticText::SetPathEnd().
get_value()
boost::any Slic3r::GUI::OptionsGroup::get_value (const t_config_option_key & id) inline inherited
{
              boost::any out;
                if (m_fields.find(id) == m_fields.end()) ;
              else
                out = m_fields.at(id)->get_value();
              return out;
    }
References Slic3r::GUI::OptionsGroup::m_fields.
Referenced by back_to_config_value().
Hide()
void Slic3r::GUI::ConfigOptionsGroup::Hide ()
{
    Show(false);
}
References Show().
hide_field()
void Slic3r::GUI::OptionsGroup::hide_field (const t_config_option_key & opt_key) inline inherited
{  show_field(opt_key, false);  }
References Slic3r::GUI::OptionsGroup::show_field().
Referenced by Slic3r::GUI::PhysicalPrinterDialog::update().
hide_labels()
void Slic3r::GUI::OptionsGroup::hide_labels () inline inherited
{ label_width = 0; }
References Slic3r::GUI::OptionsGroup::label_width.
is_activated()
bool Slic3r::GUI::OptionsGroup::is_activated () inline inherited
{ return sizer != nullptr; }
References Slic3r::GUI::OptionsGroup::sizer.
is_legend_line()
bool Slic3r::GUI::OptionsGroup::is_legend_line () inherited
{
  if (m_lines.size() == 1) {
    const std::vector<Option>& option_set = m_lines.front().get_options();
    return !option_set.empty() && option_set.front().opt.gui_type == ConfigOptionDef::GUIType::legend;
  }
  return false;
}
References Slic3r::ConfigOptionDef::legend, and Slic3r::GUI::OptionsGroup::m_lines.
Referenced by Slic3r::GUI::OptionsGroup::activate_line().
is_option_without_field()
bool Slic3r::GUI::OptionsGroup::is_option_without_field (const std::string & opt_key) static inherited
{
    return  options_without_field.find(opt_key) != options_without_field.end();
}
References Slic3r::GUI::options_without_field.
Referenced by back_to_config_value().
is_visible()
bool Slic3r::GUI::ConfigOptionsGroup::is_visible (ConfigOptionMode mode)
{
    if (m_options_mode.empty())
        return true;
    if (m_options_mode.size() == 1)
        return m_options_mode[0] <= mode;
    size_t hidden_row_cnt = 0;
    for (auto opt_mode : m_options_mode)
        if (opt_mode > mode)
            hidden_row_cnt++;
    return hidden_row_cnt != m_options_mode.size();
}
References Slic3r::GUI::OptionsGroup::m_options_mode.
launch_browser()
bool Slic3r::GUI::OptionsGroup::launch_browser (const std::string & path_end) static inherited
{
    return wxGetApp().open_browser_with_warning_dialog(OptionsGroup::get_url(path_end), wxGetApp().mainframe->m_tabpanel);
}
References Slic3r::GUI::OptionsGroup::get_url().
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::launch_browser(), and Slic3r::GUI::ogStaticText::SetPathEnd().
msw_rescale()
void Slic3r::GUI::ConfigOptionsGroup::msw_rescale ()
{
    // update bitmaps for extra column items (like "mode markers" or buttons on settings panel)
    if (rescale_extra_column_item)
        for (auto extra_col : m_extra_column_item_ptrs)
            rescale_extra_column_item(extra_col);
    // update undo buttons : rescale bitmaps
    for (const auto& field : m_fields)
        field.second->msw_rescale();
    auto rescale = [](wxSizer* sizer) {
        for (wxSizerItem* item : sizer->GetChildren())
            if (item->IsWindow()) {
                wxWindow* win = item->GetWindow();
                // check if window is ScalableButton
                ScalableButton* sc_btn = dynamic_cast<ScalableButton*>(win);
                if (sc_btn) {
                    sc_btn->SetSize(sc_btn->GetBestSize());
                    return;
                }
                // check if window is wxButton
                wxButton* btn = dynamic_cast<wxButton*>(win);
                if (btn) {
                    btn->SetSize(btn->GetBestSize());
                    return;
                }
            }
    };
    // scale widgets and extra widgets if any exists
    for (const Line& line : m_lines) {
        if (line.widget_sizer)
            rescale(line.widget_sizer);
        if (line.extra_widget_sizer)
            rescale(line.extra_widget_sizer);
    }
    if (custom_ctrl)
        custom_ctrl->msw_rescale();
}
References Slic3r::GUI::OptionsGroup::custom_ctrl, Slic3r::GUI::OptionsGroup::m_extra_column_item_ptrs, Slic3r::GUI::OptionsGroup::m_fields, Slic3r::GUI::OptionsGroup::m_lines, Slic3r::GUI::OG_CustomCtrl::msw_rescale(), Slic3r::GUI::OptionsGroup::rescale_extra_column_item, and Slic3r::GUI::OptionsGroup::sizer.
Referenced by Slic3r::GUI::ObjectManipulation::msw_rescale(), and Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed().
on_change_OG()
void Slic3r::GUI::ConfigOptionsGroup::on_change_OG (const t_config_option_key & opt_id, const boost::any & value) override virtual
Reimplemented from Slic3r::GUI::OptionsGroup.
{
  if (!m_opt_map.empty())
  {
    auto it = m_opt_map.find(opt_id);
    if (it == m_opt_map.end())
    {
      OptionsGroup::on_change_OG(opt_id, value);
      return;
    }
    auto        itOption  = it->second;
    const std::string  &opt_key   = itOption.first;
    int           opt_index = itOption.second;
    this->change_opt_value(opt_key, value, opt_index == -1 ? 0 : opt_index);
  }
  OptionsGroup::on_change_OG(opt_id, value);
}
References change_opt_value(), m_opt_map, and Slic3r::GUI::OptionsGroup::on_change_OG().
Referenced by back_to_config_value().
on_kill_focus()
void Slic3r::GUI::ConfigOptionsGroup::on_kill_focus (const std::string & opt_key) override virtual
Reimplemented from Slic3r::GUI::OptionsGroup.
{
    if (m_fill_empty_value)
        m_fill_empty_value(opt_key);
    else
      reload_config();
}
References Slic3r::GUI::OptionsGroup::m_fill_empty_value, and reload_config().
opt_map()
const t_opt_map & Slic3r::GUI::ConfigOptionsGroup::opt_map () const throw () inline
{ return m_opt_map; }
References m_opt_map.
parent()
wxWindow * Slic3r::GUI::OptionsGroup::parent () const inline inherited
Returns a copy of the pointer of the parent wxWindow. Accessor function is because users are not allowed to change the parent but defining it as const means a lot of const_casts to deal with wx functions.
{ return m_parent; }
References Slic3r::GUI::OptionsGroup::m_parent.
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::build_field(), and Slic3r::GUI::OptionsGroup::ctrl_parent().
refresh()
void Slic3r::GUI::ConfigOptionsGroup::refresh ()
{
    if (custom_ctrl)
        custom_ctrl->Refresh();
}
References Slic3r::GUI::OptionsGroup::custom_ctrl.
reload_config()
void Slic3r::GUI::ConfigOptionsGroup::reload_config ()
{
  for (auto &kvp : m_opt_map) {
    // Name of the option field (name of the configuration key, possibly suffixed with '#' and the index of a scalar inside a vector.
    const std::string &opt_id    = kvp.first;
    // option key (may be scalar or vector)
    const std::string &opt_key   = kvp.second.first;
    // index in the vector option, zero for scalars
    int          opt_index = kvp.second.second;
    const ConfigOptionDef &option = m_options.at(opt_id).opt;
    this->set_value(opt_id, config_value(opt_key, opt_index, option.gui_flags == "serialized"));
  }
}
References config_value(), m_opt_map, Slic3r::GUI::OptionsGroup::m_options, and Slic3r::GUI::OptionsGroup::set_value().
Referenced by on_kill_focus(), and Slic3r::GUI::PhysicalPrinterDialog::update().
set_config()
void Slic3r::GUI::ConfigOptionsGroup::set_config (DynamicPrintConfig * config) inline
{ m_config = config; m_modelconfig = nullptr; }
References m_config, and m_modelconfig.
set_config_category_and_type()
void Slic3r::GUI::ConfigOptionsGroup::set_config_category_and_type (const wxString & category, int type) inline
{ m_config_category = category; m_config_type = type; }
References m_config_category, and m_config_type.
set_grid_vgap()
void Slic3r::GUI::OptionsGroup::set_grid_vgap (int gap) inline inherited
{ m_grid_sizer->SetVGap(gap); }
References Slic3r::GUI::OptionsGroup::m_grid_sizer.
set_max_win_width()
void Slic3r::GUI::OptionsGroup::set_max_win_width (int max_win_width) inherited
{
    if (custom_ctrl)
        custom_ctrl->set_max_win_width(max_win_width);
}
References Slic3r::GUI::OptionsGroup::custom_ctrl, and Slic3r::GUI::OG_CustomCtrl::set_max_win_width().
set_name()
void Slic3r::GUI::OptionsGroup::set_name (const wxString & new_name) inline inherited
{ stb->SetLabel(new_name); }
References Slic3r::GUI::OptionsGroup::stb.
set_use_custom_ctrl()
void Slic3r::GUI::OptionsGroup::set_use_custom_ctrl (bool use_custom_ctrl) inline inherited
{ m_use_custom_ctrl = use_custom_ctrl; }
References Slic3r::GUI::OptionsGroup::m_use_custom_ctrl.
set_value()
bool Slic3r::GUI::OptionsGroup::set_value (const t_config_option_key & id, const boost::any & value, bool change_event = false) inline inherited
{
              if (m_fields.find(id) == m_fields.end()) return false;
              m_fields.at(id)->set_value(value, change_event);
              return true;
    }
References Slic3r::GUI::OptionsGroup::m_fields.
Referenced by back_to_config_value(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::Tab::on_value_change(), reload_config(), and Slic3r::GUI::PhysicalPrinterDialog::update().
Show()
void Slic3r::GUI::ConfigOptionsGroup::Show (const bool show)
{
    sizer->ShowItems(show);
#if 0//#ifdef __WXGTK__
    m_panel->Show(show);
    m_grid_sizer->Show(show);
#endif /* __WXGTK__ */
}
References Slic3r::GUI::OptionsGroup::m_grid_sizer, and Slic3r::GUI::OptionsGroup::sizer.
Referenced by Hide(), and update_visibility().
show_field()
void Slic3r::GUI::OptionsGroup::show_field (const t_config_option_key & opt_key, bool show = true) inherited
{
    Field* field = get_field(opt_key);
    if (!field) return;
    wxWindow* win = field->getWindow();
    if (!win) return;
    wxSizerItem* win_item = m_grid_sizer->GetItem(win, true);
    if (!win_item) return;
    const size_t cols = (size_t)m_grid_sizer->GetCols();
    const size_t rows = (size_t)m_grid_sizer->GetEffectiveRowsCount();
    auto show_row = [this, show, cols, win_item](wxSizerItem* item, size_t row_shift) {
        // check if item contanes required win
        if (!item->IsWindow() || item != win_item)
            return false;
        // show/hide hole line contanes this window
        for (size_t i = 0; i < cols; ++i)
            m_grid_sizer->Show(row_shift + i, show);
        return true;
    };
    size_t row_shift = 0;
    for (size_t j = 0; j < rows; ++j) {
        for (size_t i = 0; i < cols; ++i) {
            wxSizerItem* item = m_grid_sizer->GetItem(row_shift + i);
            if (!item)
                continue;
            if (item->IsSizer()) {
                for (wxSizerItem* child_item : item->GetSizer()->GetChildren())
                    if (show_row(child_item, row_shift))
                        return;
            }
            else if (show_row(item, row_shift))
                return;
        }
        row_shift += cols;
    }
}
References Slic3r::GUI::OptionsGroup::get_field(), Slic3r::GUI::Field::getWindow(), and Slic3r::GUI::OptionsGroup::m_grid_sizer.
Referenced by Slic3r::GUI::OptionsGroup::hide_field(), and Slic3r::GUI::PhysicalPrinterDialog::update().
sys_color_changed()
void Slic3r::GUI::ConfigOptionsGroup::sys_color_changed ()
{
#ifdef _WIN32
    if (staticbox && stb) {
        wxGetApp().UpdateAllStaticTextDarkUI(stb);
        // update bitmaps for extra column items (like "delete" buttons on settings panel)
        for (auto extra_col : m_extra_column_item_ptrs)
            wxGetApp().UpdateDarkUI(extra_col);
    }
    if (custom_ctrl)
        wxGetApp().UpdateDarkUI(custom_ctrl);
#endif
    auto update = [](wxSizer* sizer) {
        for (wxSizerItem* item : sizer->GetChildren())
            if (item->IsWindow()) {
                wxWindow* win = item->GetWindow();
                // check if window is ScalableButton
                if (ScalableButton* sc_btn = dynamic_cast<ScalableButton*>(win)) {
                    sc_btn->sys_color_changed();
                    return;
                }
                wxGetApp().UpdateDarkUI(win, dynamic_cast<wxButton*>(win) != nullptr);
            }
    };
    // scale widgets and extra widgets if any exists
    for (const Line& line : m_lines) {
        if (line.widget_sizer)
            update(line.widget_sizer);
        if (line.extra_widget_sizer)
            update(line.extra_widget_sizer);
    }
  // update undo buttons : rescale bitmaps
  for (const auto& field : m_fields)
    field.second->sys_color_changed();
}
References Slic3r::GUI::OptionsGroup::custom_ctrl, Slic3r::GUI::OptionsGroup::m_extra_column_item_ptrs, Slic3r::GUI::OptionsGroup::m_fields, Slic3r::GUI::OptionsGroup::m_lines, Slic3r::GUI::OptionsGroup::sizer, Slic3r::GUI::OptionsGroup::staticbox, and Slic3r::GUI::OptionsGroup::stb.
Referenced by Slic3r::GUI::ObjectManipulation::sys_color_changed().
update_visibility()
bool Slic3r::GUI::ConfigOptionsGroup::update_visibility (ConfigOptionMode mode)
{
  if (m_options_mode.empty() || !m_grid_sizer)
    return true;
    if (custom_ctrl) {
        bool show = custom_ctrl->update_visibility(mode);
        this->Show(show);
        return show;
    }
  int opt_mode_size = m_options_mode.size();
  if (m_grid_sizer->GetEffectiveRowsCount() != opt_mode_size &&
    opt_mode_size == 1)
    return m_options_mode[0] <= mode;
  Show(true);
    int coef = 0;
    int hidden_row_cnt = 0;
    const int cols = m_grid_sizer->GetCols();
    for (auto opt_mode : m_options_mode) {
    const bool show = opt_mode <= mode;
        if (!show) {
            hidden_row_cnt++;
            for (int i = 0; i < cols; ++i)
                m_grid_sizer->Show(coef + i, show);
        }
        coef+= cols;
  }
    if (hidden_row_cnt == opt_mode_size) {
        sizer->ShowItems(false);
        return false;
    }
    return true;
}
References Slic3r::GUI::OptionsGroup::custom_ctrl, Slic3r::GUI::OptionsGroup::m_grid_sizer, Slic3r::GUI::OptionsGroup::m_options_mode, Show(), Slic3r::GUI::OptionsGroup::sizer, and Slic3r::GUI::OG_CustomCtrl::update_visibility().
Member Data Documentation
ctrl_horiz_alignment
int Slic3r::GUI::OptionsGroup::ctrl_horiz_alignment { wxALIGN_LEFT} inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), and Slic3r::GUI::OG_CustomCtrl::init_max_win_width().
custom_ctrl
OG_CustomCtrl* Slic3r::GUI::OptionsGroup::custom_ctrl { nullptr } inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::clear(), Slic3r::GUI::OptionsGroup::ctrl_parent(), get_custom_ctrl_with_blinking_ptr(), msw_rescale(), Slic3r::GUI::OG_CustomCtrl::OnPaint(), refresh(), Slic3r::GUI::OptionsGroup::set_max_win_width(), sys_color_changed(), and update_visibility().
extra_column
column_t Slic3r::GUI::OptionsGroup::extra_column {nullptr} inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), and Slic3r::GUI::OptionsGroup::activate_line().
have_sys_config
std::function<bool()> Slic3r::GUI::OptionsGroup::have_sys_config { nullptr } inherited
Referenced by back_to_sys_value().
label_font
wxFont Slic3r::GUI::OptionsGroup::label_font {wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT) } inherited
label_width
size_t Slic3r::GUI::OptionsGroup::label_width = 20 inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OG_CustomCtrl::get_pos(), Slic3r::GUI::OptionsGroup::hide_labels(), and Slic3r::GUI::OG_CustomCtrl::init_ctrl_lines().
m_config
const DynamicPrintConfig* Slic3r::GUI::ConfigOptionsGroup::m_config {nullptr} private
Referenced by change_opt_value(), config_value(), get_option(), and set_config().
m_config_category
wxString Slic3r::GUI::ConfigOptionsGroup::m_config_category private
Referenced by config_category(), and set_config_category_and_type().
m_config_type
int Slic3r::GUI::ConfigOptionsGroup::m_config_type private
Referenced by config_type(), and set_config_category_and_type().
m_disabled
bool Slic3r::GUI::OptionsGroup::m_disabled {false} protected inherited
Referenced by Slic3r::GUI::OptionsGroup::build_field().
m_extra_column_item_ptrs
std::vector<wxWindow*> Slic3r::GUI::OptionsGroup::m_extra_column_item_ptrs protected inherited
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::clear(), msw_rescale(), and sys_color_changed().
m_fields
t_optionfield_map Slic3r::GUI::OptionsGroup::m_fields protected inherited
Field list, contains unique_ptrs of the derived type. using types that need to know what it is beyond the public interface need to cast based on the related ConfigOptionDef.
Referenced by Slic3r::GUI::OptionsGroup::build_field(), Slic3r::GUI::OptionsGroup::clear(), Slic3r::GUI::OptionsGroup::clear_fields_except_of(), Slic3r::GUI::OptionsGroup::disable(), Slic3r::GUI::OptionsGroup::enable(), Slic3r::GUI::OptionsGroup::get_field(), Slic3r::GUI::OptionsGroup::get_value(), msw_rescale(), Slic3r::GUI::OptionsGroup::set_value(), and sys_color_changed().
m_fill_empty_value
t_kill_focus Slic3r::GUI::OptionsGroup::m_fill_empty_value { nullptr } inherited
Referenced by on_kill_focus().
m_get_initial_config
std::function<DynamicPrintConfig()> Slic3r::GUI::OptionsGroup::m_get_initial_config { nullptr } inherited
Referenced by back_to_initial_value().
m_get_sys_config
std::function<DynamicPrintConfig()> Slic3r::GUI::OptionsGroup::m_get_sys_config { nullptr } inherited
Referenced by back_to_sys_value().
m_grid_sizer
wxGridSizer* Slic3r::GUI::OptionsGroup::m_grid_sizer {nullptr} protected inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::clear(), Slic3r::GUI::OptionsGroup::get_grid_sizer(), Slic3r::GUI::OptionsGroup::set_grid_vgap(), Show(), Slic3r::GUI::OptionsGroup::show_field(), and update_visibility().
m_lines
std::vector<Line> Slic3r::GUI::OptionsGroup::m_lines protected inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), Slic3r::GUI::OptionsGroup::append_line(), Slic3r::GUI::OptionsGroup::append_separator(), Slic3r::GUI::OptionsGroup::clear(), get_custom_ctrl_with_blinking_ptr(), Slic3r::GUI::OptionsGroup::get_line(), Slic3r::GUI::OptionsGroup::get_lines(), Slic3r::GUI::OptionsGroup::is_legend_line(), msw_rescale(), and sys_color_changed().
m_modelconfig
ModelConfig* Slic3r::GUI::ConfigOptionsGroup::m_modelconfig { nullptr } private
Referenced by change_opt_value(), and set_config().
m_on_change
t_change Slic3r::GUI::OptionsGroup::m_on_change { nullptr } inherited
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), and Slic3r::GUI::OptionsGroup::on_change_OG().
m_opt_map
t_opt_map Slic3r::GUI::ConfigOptionsGroup::m_opt_map private
Referenced by back_to_config_value(), get_fieldc(), get_option(), on_change_OG(), opt_map(), and reload_config().
m_options
std::map<t_config_option_key, Option> Slic3r::GUI::OptionsGroup::m_options protected inherited
Referenced by Slic3r::GUI::OptionsGroup::append_line(), Slic3r::GUI::OptionsGroup::build_field(), Slic3r::GUI::OptionsGroup::get_optioms_map(), and reload_config().
m_options_mode
std::vector<ConfigOptionMode> Slic3r::GUI::OptionsGroup::m_options_mode protected inherited
Referenced by Slic3r::GUI::OptionsGroup::append_line(), is_visible(), and update_visibility().
m_parent
wxWindow* Slic3r::GUI::OptionsGroup::m_parent {nullptr} protected inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), and Slic3r::GUI::OptionsGroup::parent().
m_use_custom_ctrl
bool Slic3r::GUI::OptionsGroup::m_use_custom_ctrl { false } protected inherited
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), get_option(), and Slic3r::GUI::OptionsGroup::set_use_custom_ctrl().
m_use_custom_ctrl_as_parent
bool Slic3r::GUI::OptionsGroup::m_use_custom_ctrl_as_parent { false } protected inherited
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), and Slic3r::GUI::OptionsGroup::ctrl_parent().
rescale_extra_column_item
std::function<void(wxWindow* win)> Slic3r::GUI::OptionsGroup::rescale_extra_column_item { nullptr } inherited
Referenced by msw_rescale().
rescale_near_label_widget
std::function<void(wxWindow* win)> Slic3r::GUI::OptionsGroup::rescale_near_label_widget { nullptr } inherited
sidetext_font
wxFont Slic3r::GUI::OptionsGroup::sidetext_font {wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT) } inherited
sidetext_width
int Slic3r::GUI::OptionsGroup::sidetext_width { -1 } inherited
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
sizer
wxSizer* Slic3r::GUI::OptionsGroup::sizer {nullptr} inherited
Referenced by Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::OptionsGroup::activate(), Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::clear(), Slic3r::GUI::OptionsGroup::is_activated(), msw_rescale(), Show(), sys_color_changed(), and update_visibility().
staticbox
const bool Slic3r::GUI::OptionsGroup::staticbox {true} inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OG_CustomCtrl::init_ctrl_lines(), and sys_color_changed().
stb
wxStaticBox* Slic3r::GUI::OptionsGroup::stb {nullptr} protected inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::ctrl_parent(), Slic3r::GUI::OptionsGroup::get_name(), Slic3r::GUI::OptionsGroup::set_name(), and sys_color_changed().
sublabel_width
int Slic3r::GUI::OptionsGroup::sublabel_width { -1 } inherited
Referenced by Slic3r::GUI::OptionsGroup::activate_line().
title
const wxString Slic3r::GUI::OptionsGroup::title inherited
Referenced by Slic3r::GUI::OptionsGroup::activate(), append_single_option_line(), create_single_option_line(), and get_option().
The documentation for this class was generated from the following files:
src/slic3r/GUI/OptionsGroup.hpp
src/slic3r/GUI/OptionsGroup.cpp