Prusa Slicer: Slic3r::GUI::GLGizmoRotate Class Reference
Slic3r::GUI::GLGizmoRotate Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoRotate.hpp>
Classes
struct GrabberConnection
Public Types
enum Axis : unsigned char { X =0 , Y =1 , Z =2 }
enum class EGrabberExtension {
None = 0 , PosX = 1 << 0 , NegX = 1 << 1 , PosY = 1 << 2 ,
NegY = 1 << 3 , PosZ = 1 << 4 , NegZ = 1 << 5
}
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoRotate (GLCanvas3D &parent, Axis axis)
virtual ~GLGizmoRotate ()=default
double get_angle () const
void set_angle (double angle)
std::string get_tooltip () const override
Mouse tooltip text.
void set_group_id (int group_id)
void set_force_local_coordinate (bool use)
void start_dragging ()
void stop_dragging ()
void enable_grabber ()
void disable_grabber ()
void set_highlight_color (const ColorRGBA &color)
bool on_mouse (const wxMouseEvent &mouse_event) override
Postpone to Grabber for move Detect move of object by dragging.
void dragging (const UpdateData &data)
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
virtual bool wants_enter_leave_snapshots () const
virtual std::string get_gizmo_entering_text () const
virtual std::string get_gizmo_leaving_text () const
virtual std::string get_action_snapshot_name () const
void set_common_data_pool (CommonGizmosDataPool *ptr)
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
bool is_dragging () const
bool update_items_state ()
void render ()
void render_input_window (float x, float y, float bottom_limit)
virtual void data_changed (bool is_serializing)
Is called when data (Selection) is changed.
void register_raycasters_for_picking ()
void unregister_raycasters_for_picking ()
virtual bool is_in_editing_mode () const
virtual bool is_selection_rectangle_dragging () const
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static const unsigned int GRABBER_ELEMENTS_MAX_COUNT = 7
static const int NO_SHORTCUT_KEY_VALUE = 0
Protected Member Functions
bool on_init () override
std::string on_get_name () const override
void on_start_dragging () override
void on_dragging (const UpdateData &data) override
void on_render () override
virtual void on_load (cereal::BinaryInputArchive &ar)
virtual void on_save (cereal::BinaryOutputArchive &ar) const
virtual void on_set_state ()
virtual void on_set_hover_id ()
virtual bool on_is_activable () const
virtual bool on_is_selectable () const
virtual CommonGizmosDataID on_get_requirements () const
virtual void on_enable_grabber (unsigned int id)
virtual void on_disable_grabber (unsigned int id)
virtual void on_stop_dragging ()
virtual void on_render_input_window (float x, float y, float bottom_limit)
void register_grabbers_for_picking ()
void unregister_grabbers_for_picking ()
virtual void on_register_raycasters_for_picking ()
virtual void on_unregister_raycasters_for_picking ()
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers (size_t first, size_t last, float size, bool force_hover) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
bool use_grabbers (const wxMouseEvent &mouse_event)
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
void do_stop_dragging (bool perform_mouse_cleanup)
Protected Attributes
GLCanvas3D & m_parent
int m_group_id
EState m_state
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id { -1 }
bool m_dragging { false }
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render { true }
CommonGizmosDataPool * m_c { nullptr }
Private Member Functions
void render_circle (const ColorRGBA &color, bool radius_changed)
void render_scale (const ColorRGBA &color, bool radius_changed)
void render_snap_radii (const ColorRGBA &color, bool radius_changed)
void render_reference_radius (const ColorRGBA &color, bool radius_changed)
void render_angle_arc (const ColorRGBA &color, bool radius_changed)
void render_grabber_connection (const ColorRGBA &color, bool radius_changed)
void render_grabber (const BoundingBoxf3 &box)
Transform3d local_transform (const Selection &selection) const
Vec3d mouse_position_in_local_plane (const Linef3 &mouse_ray) const
void init_data_from_selection (const Selection &selection)
Private Attributes
Axis m_axis
double m_angle { 0.0 }
Vec3d m_center { Vec3d::Zero() }
float m_radius { 0.0f }
float m_snap_coarse_in_radius { 0.0f }
float m_snap_coarse_out_radius { 0.0f }
float m_snap_fine_in_radius { 0.0f }
float m_snap_fine_out_radius { 0.0f }
BoundingBoxf3 m_bounding_box
Transform3d m_orient_matrix { Transform3d::Identity() }
GLModel m_circle
GLModel m_scale
GLModel m_snap_radii
GLModel m_reference_radius
GLModel m_angle_arc
GrabberConnection m_grabber_connection
float m_old_radius { 0.0f }
float m_old_hover_radius { 0.0f }
float m_old_angle { 0.0f }
bool m_force_local_coordinate { false }
ColorRGBA m_drag_color
ColorRGBA m_highlight_color
bool m_dirty { false }
Static Private Attributes
static const float Offset = 5.0f
static const unsigned int AngleResolution = 64
static const unsigned int ScaleStepsCount = 72
static const float ScaleStepRad = 2.0f * float(PI) / GLGizmoRotate::ScaleStepsCount
static const unsigned int ScaleLongEvery = 2
static const float ScaleLongTooth = 0.1f
static const unsigned int SnapRegionsCount = 8
static const float GrabberOffset = 0.15f
Detailed Description
Class Documentation
Slic3r::GUI::GLGizmoRotate::GrabberConnection
struct Slic3r::GUI::GLGizmoRotate::GrabberConnection
Class Members
GLModel model
Vec3d old_center { Vec3d::Zero() }
Member Enumeration Documentation
Axis
enum Slic3r::GUI::GLGizmoRotate::Axis : unsigned char
Enumerator
X
Y
Z
    {
        X=0,
        Y=1,
        Z=2
    };
EGrabberExtension
enum class Slic3r::GUI::GLGizmoBase::EGrabberExtension strong inherited
Enumerator
None
PosX
NegX
PosY
NegY
PosZ
NegZ
    {
        None = 0,
        PosX = 1 << 0,
        NegX = 1 << 1,
        PosY = 1 << 2,
        NegY = 1 << 3,
        PosZ = 1 << 4,
        NegZ = 1 << 5,
    };
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
Constructor & Destructor Documentation
GLGizmoRotate()
Slic3r::GUI::GLGizmoRotate::GLGizmoRotate (GLCanvas3D & parent, GLGizmoRotate::Axis axis)
    : GLGizmoBase(parent, "", -1)
    , m_axis(axis)
    , m_angle(0.0)
    , m_center(0.0, 0.0, 0.0)
    , m_radius(0.0f)
    , m_snap_coarse_in_radius(0.0f)
    , m_snap_coarse_out_radius(0.0f)
    , m_snap_fine_in_radius(0.0f)
    , m_snap_fine_out_radius(0.0f)
    , m_drag_color(DEFAULT_DRAG_COLOR)
    , m_highlight_color(DEFAULT_HIGHLIGHT_COLOR)
{
    m_group_id = static_cast<int>(axis);
}
References Slic3r::GUI::GLGizmoBase::m_group_id.
~GLGizmoRotate()
virtual Slic3r::GUI::GLGizmoRotate::~GLGizmoRotate () virtual default
Member Function Documentation
data_changed()
virtual void Slic3r::GUI::GLGizmoBase::data_changed (bool is_serializing) inline virtual inherited
Is called when data (Selection) is changed.
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{};
disable_grabber()
void Slic3r::GUI::GLGizmoRotate::disable_grabber ()
{ m_grabbers[0].enabled = false; }
References Slic3r::GUI::GLGizmoBase::m_grabbers.
Referenced by Slic3r::GUI::GLGizmoEmboss::on_disable_grabber().
do_stop_dragging()
void Slic3r::GUI::GLGizmoBase::do_stop_dragging (bool perform_mouse_cleanup) protected inherited
{
    for (auto& grabber : m_grabbers) grabber.dragging = false;
    m_dragging = false;
    // NOTE: This should be part of GLCanvas3D
    // Reset hover_id when leave window
    if (perform_mouse_cleanup) m_parent.mouse_up_cleanup();
    on_stop_dragging();
    // There is prediction that after draggign, data are changed
    // Data are updated twice also by canvas3D::reload_scene.
    // Should be fixed.
    m_parent.get_gizmos_manager().update_data();
    wxGetApp().obj_manipul()->set_dirty();
    // Let the plater know that the dragging finished, so a delayed
    // refresh of the scene with the background processing data should
    // be performed.
    m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED));
    // updates camera target constraints
    m_parent.refresh_camera_scene_box();
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_up_cleanup(), Slic3r::GUI::GLGizmoBase::on_stop_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::refresh_camera_scene_box(), and Slic3r::GUI::GLGizmosManager::update_data().
Referenced by Slic3r::GUI::GLGizmoBase::use_grabbers().
dragging()
void Slic3r::GUI::GLGizmoRotate::dragging (const UpdateData & data)
{ on_dragging(data); }
References on_dragging().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_dragging().
enable_grabber()
void Slic3r::GUI::GLGizmoRotate::enable_grabber ()
{ m_grabbers[0].enabled = true; }
References Slic3r::GUI::GLGizmoBase::m_grabbers.
Referenced by Slic3r::GUI::GLGizmoEmboss::on_enable_grabber().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoEmboss::init_font_name_texture(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoEmboss::rev_input(), Slic3r::GUI::GLGizmoEmboss::rev_input_mm(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
get_action_snapshot_name()
std::string Slic3r::GUI::GLGizmoBase::get_action_snapshot_name () const virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
{
    return _u8L("Gizmo action");
}
References _u8L.
Referenced by Slic3r::GUI::Plater::priv::take_snapshot().
get_angle()
double Slic3r::GUI::GLGizmoRotate::get_angle () const inline
{ return m_angle; }
References m_angle.
Referenced by Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation().
get_gizmo_entering_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_entering_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
get_gizmo_leaving_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_leaving_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmosManager::grabber_contains_mouse(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), and Slic3r::GUI::GLGizmoSlaSupports::on_mouse().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    std::string out = on_get_name();
    if (!include_shortcut) return out;
    int key = get_shortcut_key();
    assert(key==NO_SHORTCUT_KEY_VALUE || (key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z));
    out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE, and Slic3r::GUI::GLGizmoBase::on_get_name().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay().
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLCanvas3D::on_mouse().
get_tooltip()
std::string Slic3r::GUI::GLGizmoRotate::get_tooltip () const override virtual
Mouse tooltip text.
Returns
Text to be visible in mouse tooltip
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    std::string axis;
    switch (m_axis)
    {
    case X: { axis = "X"; break; }
    case Y: { axis = "Y"; break; }
    case Z: { axis = "Z"; break; }
    }
    return (m_hover_id == 0 || m_grabbers.front().dragging) ? axis + ": " + format(float(Geometry::rad2deg(m_angle)), 4) : "";
}
References Slic3r::GUI::GLGizmoBase::format(), m_angle, m_axis, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::Geometry::rad2deg(), X, Y, and Z.
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_init().
init_data_from_selection()
void Slic3r::GUI::GLGizmoRotate::init_data_from_selection (const Selection & selection) private
{
    const auto [box, box_trafo] = m_force_local_coordinate ?
        selection.get_bounding_box_in_reference_system(ECoordinatesType::Local) : selection.get_bounding_box_in_current_reference_system();
    m_bounding_box = box;
    m_center = box_trafo.translation();
    m_orient_matrix = box_trafo;
    m_radius = Offset + m_bounding_box.radius();
    m_snap_coarse_in_radius = m_radius / 3.0f;
    m_snap_coarse_out_radius = 2.0f * m_snap_coarse_in_radius;
    m_snap_fine_in_radius = m_radius;
    m_snap_fine_out_radius = m_snap_fine_in_radius + m_radius * ScaleLongTooth;
}
References Slic3r::GUI::Selection::get_bounding_box_in_current_reference_system(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::GUI::Local, m_bounding_box, m_center, m_force_local_coordinate, m_orient_matrix, m_radius, m_snap_coarse_in_radius, m_snap_coarse_out_radius, m_snap_fine_in_radius, m_snap_fine_out_radius, Offset, Slic3r::BoundingBox3Base< PointType >::radius(), and ScaleLongTooth.
Referenced by on_render(), and on_start_dragging().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmosManager::handle_shortcut(), Slic3r::GUI::GLGizmoEmboss::init_create(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
Referenced by Slic3r::GUI::GLGizmoCut3D::gizmo_event(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate().
is_in_editing_mode()
virtual bool Slic3r::GUI::GLGizmoBase::is_in_editing_mode () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::on_key().
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
is_selection_rectangle_dragging()
virtual bool Slic3r::GUI::GLGizmoBase::is_selection_rectangle_dragging () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoHollow, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::on_key().
load()
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
local_transform()
Transform3d Slic3r::GUI::GLGizmoRotate::local_transform (const Selection & selection) const private
{
    Transform3d ret;
    switch (m_axis)
    {
    case X:
    {
        ret = Geometry::rotation_transform(0.5 * PI * Vec3d::UnitY()) * Geometry::rotation_transform(-0.5 * PI * Vec3d::UnitZ());
        break;
    }
    case Y:
    {
        ret = Geometry::rotation_transform(-0.5 * PI * Vec3d::UnitZ()) * Geometry::rotation_transform(-0.5 * PI * Vec3d::UnitY());
        break;
    }
    default:
    case Z:
    {
        ret = Transform3d::Identity();
        break;
    }
    }
    return m_orient_matrix * ret;
}
References Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), m_axis, m_orient_matrix, PI, Slic3r::Geometry::rotation_transform(), X, Y, and Z.
Referenced by on_render().
mouse_position_in_local_plane()
Vec3d Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane (const Linef3 & mouse_ray) const private
{
    const double half_pi = 0.5 * double(PI);
    Transform3d m = Transform3d::Identity();
    switch (m_axis)
    {
    case X:
    {
        m.rotate(Eigen::AngleAxisd(half_pi, Vec3d::UnitZ()));
        m.rotate(Eigen::AngleAxisd(-half_pi, Vec3d::UnitY()));
        break;
    }
    case Y:
    {
        m.rotate(Eigen::AngleAxisd(half_pi, Vec3d::UnitY()));
        m.rotate(Eigen::AngleAxisd(half_pi, Vec3d::UnitZ()));
        break;
    }
    default:
    case Z:
    {
        // no rotation applied
        break;
    }
    }
    m = m * Geometry::Transformation(m_orient_matrix).get_matrix_no_offset().inverse();
    m.translate(-m_center);
    const Linef3 local_mouse_ray = transform(mouse_ray, m);
    if (std::abs(local_mouse_ray.vector().dot(Vec3d::UnitZ())) < EPSILON) {
        // if the ray is parallel to the plane containing the circle
        if (std::abs(local_mouse_ray.vector().dot(Vec3d::UnitY())) > 1.0 - EPSILON)
            // if the ray is parallel to grabber direction
            return Vec3d::UnitX();
        else {
            const Vec3d world_pos = (local_mouse_ray.a.x() >= 0.0) ? mouse_ray.a - m_center : mouse_ray.b - m_center;
            m.translate(m_center);
            return m * world_pos;
        }
    }
    else
        return local_mouse_ray.intersect_plane(0.0);
}
References Slic3r::Linef3::a, Slic3r::Linef3::b, EPSILON, Slic3r::Geometry::Transformation::get_matrix_no_offset(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::Linef3::intersect_plane(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), m_axis, m_center, m_orient_matrix, PI, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotate(), Slic3r::transform(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), Slic3r::Linef3::vector(), X, Y, and Z.
Referenced by on_dragging().
on_disable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_disable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_dragging()
void Slic3r::GUI::GLGizmoRotate::on_dragging (const UpdateData & data) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    const Vec2d mouse_pos = to_2d(mouse_position_in_local_plane(data.mouse_ray));
    const Vec2d orig_dir = Vec2d::UnitX();
    const Vec2d new_dir = mouse_pos.normalized();
    double theta = ::acos(std::clamp(new_dir.dot(orig_dir), -1.0, 1.0));
    if (cross2(orig_dir, new_dir) < 0.0)
        theta = 2.0 * (double)PI - theta;
    const double len = mouse_pos.norm();
    // snap to coarse snap region
    if (m_snap_coarse_in_radius <= len && len <= m_snap_coarse_out_radius) {
        const double step = 2.0 * double(PI) / double(SnapRegionsCount);
        theta = step * std::round(theta / step);
    }
    else {
        // snap to fine snap region (scale)
        if (m_snap_fine_in_radius <= len && len <= m_snap_fine_out_radius) {
            const double step = 2.0 * double(PI) / double(ScaleStepsCount);
            theta = step * std::round(theta / step);
        }
    }
    if (theta == 2.0 * double(PI))
        theta = 0.0;
    m_angle = theta;
}
References acos(), Slic3r::cross2(), m_angle, m_snap_coarse_in_radius, m_snap_coarse_out_radius, m_snap_fine_in_radius, m_snap_fine_out_radius, mouse_position_in_local_plane(), PI, ScaleStepsCount, SnapRegionsCount, and Slic3r::to_2d().
Referenced by dragging().
on_enable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_enable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_get_name()
std::string Slic3r::GUI::GLGizmoRotate::on_get_name () const inline override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{ return ""; }
on_get_requirements()
virtual CommonGizmosDataID Slic3r::GUI::GLGizmoBase::on_get_requirements () const inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoSimplify, and Slic3r::GUI::GLGizmoSlaBase.
{ return CommonGizmosDataID(0); }
Referenced by Slic3r::GUI::GLGizmoBase::get_requirements().
on_init()
bool Slic3r::GUI::GLGizmoRotate::on_init () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    m_grabbers.push_back(Grabber());
    m_grabbers.back().extensions = (GLGizmoBase::EGrabberExtension)(int(GLGizmoBase::EGrabberExtension::PosY) | int(GLGizmoBase::EGrabberExtension::NegY));
    return true;
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::NegY, and Slic3r::GUI::GLGizmoBase::PosY.
on_is_activable()
virtual bool Slic3r::GUI::GLGizmoBase::on_is_activable () const inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, Slic3r::GUI::GLGizmoSimplify, and Slic3r::GUI::GLGizmoSlaSupports.
{ return true; }
Referenced by Slic3r::GUI::GLGizmoBase::is_activable().
on_is_selectable()
virtual bool Slic3r::GUI::GLGizmoBase::on_is_selectable () const inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoSimplify, and Slic3r::GUI::GLGizmoSlaSupports.
{ return true; }
Referenced by Slic3r::GUI::GLGizmoBase::is_selectable().
on_load()
virtual void Slic3r::GUI::GLGizmoBase::on_load (cereal::BinaryInputArchive & ar) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::load().
on_mouse()
bool Slic3r::GUI::GLGizmoRotate::on_mouse (const wxMouseEvent & mouse_event) override virtual
Postpone to Grabber for move Detect move of object by dragging.
Parameters
mouse_event Keep information about mouse click
Returns
Return True when use the information otherwise False.
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return use_grabbers(mouse_event);
}
References Slic3r::GUI::GLGizmoBase::use_grabbers().
on_register_raycasters_for_picking()
virtual void Slic3r::GUI::GLGizmoBase::on_register_raycasters_for_picking () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking().
on_render()
void Slic3r::GUI::GLGizmoRotate::on_render () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    if (!m_grabbers.front().enabled)
        return;
    const Selection& selection = m_parent.get_selection();
    if (m_hover_id != 0 && !m_grabbers.front().dragging)
        init_data_from_selection(selection);
    const double grabber_radius = (double)m_radius * (1.0 + (double)GrabberOffset);
    m_grabbers.front().center = Vec3d(::cos(m_angle) * grabber_radius, ::sin(m_angle) * grabber_radius, 0.0);
    m_grabbers.front().angles.z() = m_angle;
    glsafe(::glEnable(GL_DEPTH_TEST));
    m_grabbers.front().matrix = local_transform(selection);
#if ENABLE_GL_CORE_PROFILE
    if (!OpenGLManager::get_gl_info().is_core_profile())
#endif // ENABLE_GL_CORE_PROFILE
        glsafe(::glLineWidth((m_hover_id != -1) ? 2.0f : 1.5f));
#if ENABLE_GL_CORE_PROFILE
    GLShaderProgram* shader = OpenGLManager::get_gl_info().is_core_profile() ? wxGetApp().get_shader("dashed_thick_lines") : wxGetApp().get_shader("flat");
#else
    GLShaderProgram* shader = wxGetApp().get_shader("flat");
#endif // ENABLE_GL_CORE_PROFILE
    if (shader != nullptr) {
        shader->start_using();
        const Camera& camera = wxGetApp().plater()->get_camera();
        const Transform3d view_model_matrix = camera.get_view_matrix() * m_grabbers.front().matrix;
        shader->set_uniform("view_model_matrix", view_model_matrix);
        shader->set_uniform("projection_matrix", camera.get_projection_matrix());
#if ENABLE_GL_CORE_PROFILE
        const std::array<int, 4>& viewport = camera.get_viewport();
        shader->set_uniform("viewport_size", Vec2d(double(viewport[2]), double(viewport[3])));
        shader->set_uniform("width", 0.25f);
        shader->set_uniform("gap_size", 0.0f);
#endif // ENABLE_GL_CORE_PROFILE
        const bool radius_changed = std::abs(m_old_radius - m_radius) > EPSILON;
        m_old_radius = m_radius;
        const ColorRGBA color = (m_hover_id != -1) ? m_drag_color : m_highlight_color;
        render_circle(color, radius_changed);
        if (m_hover_id != -1) {
            const bool hover_radius_changed = std::abs(m_old_hover_radius - m_radius) > EPSILON;
            m_old_hover_radius = m_radius;
            render_scale(color, hover_radius_changed);
            render_snap_radii(color, hover_radius_changed);
            render_reference_radius(color, hover_radius_changed);
            render_angle_arc(m_highlight_color, hover_radius_changed);
        }
        render_grabber_connection(color, radius_changed);
        shader->stop_using();
    }
    render_grabber(m_bounding_box);
}
References cos(), EPSILON, Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), glsafe, GrabberOffset, init_data_from_selection(), Slic3r::GUI::OpenGLManager::GLInfo::is_core_profile(), local_transform(), m_angle, m_bounding_box, m_drag_color, Slic3r::GUI::GLGizmoBase::m_grabbers, m_highlight_color, Slic3r::GUI::GLGizmoBase::m_hover_id, m_old_hover_radius, m_old_radius, Slic3r::GUI::GLGizmoBase::m_parent, m_radius, render_angle_arc(), render_circle(), render_grabber(), render_grabber_connection(), render_reference_radius(), render_scale(), render_snap_radii(), Slic3r::GLShaderProgram::set_uniform(), sin(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
on_render_input_window()
virtual void Slic3r::GUI::GLGizmoBase::on_render_input_window (float x, float y, float bottom_limit) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoSeam, Slic3r::GUI::GLGizmoSimplify, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
on_save()
virtual void Slic3r::GUI::GLGizmoBase::on_save (cereal::BinaryOutputArchive & ar) const inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::save().
on_set_hover_id()
virtual void Slic3r::GUI::GLGizmoBase::on_set_hover_id () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::set_hover_id().
on_set_state()
virtual void Slic3r::GUI::GLGizmoBase::on_set_state () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoSimplify, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::set_state().
on_start_dragging()
void Slic3r::GUI::GLGizmoRotate::on_start_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    init_data_from_selection(m_parent.get_selection());
}
References Slic3r::GUI::GLCanvas3D::get_selection(), init_data_from_selection(), and Slic3r::GUI::GLGizmoBase::m_parent.
Referenced by start_dragging().
on_stop_dragging()
virtual void Slic3r::GUI::GLGizmoBase::on_stop_dragging () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::do_stop_dragging(), and stop_dragging().
on_unregister_raycasters_for_picking()
virtual void Slic3r::GUI::GLGizmoBase::on_unregister_raycasters_for_picking () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking().
register_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].register_raycasters_for_picking((m_group_id >= 0) ? m_group_id : i);
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking().
register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking () inline inherited
{ register_grabbers_for_picking(); on_register_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_register_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_register_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ on_render(); }
References Slic3r::GUI::GLGizmoBase::on_render().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_render().
render_angle_arc()
void Slic3r::GUI::GLGizmoRotate::render_angle_arc (const ColorRGBA & color, bool radius_changed) private
{
    const float step_angle = float(m_angle) / float(AngleResolution);
    const float ex_radius = m_radius * (1.0f + GrabberOffset);
    const bool angle_changed = std::abs(m_old_angle - m_angle) > EPSILON;
    m_old_angle = m_angle;
    if (!m_angle_arc.is_initialized() || radius_changed || angle_changed) {
        m_angle_arc.reset();
        if (m_angle > 0.0f) {
            GLModel::Geometry init_data;
            init_data.format = { GLModel::Geometry::EPrimitiveType::LineStrip, GLModel::Geometry::EVertexLayout::P3 };
            init_data.reserve_vertices(1 + AngleResolution);
            init_data.reserve_indices(1 + AngleResolution);
            // vertices + indices
            for (unsigned int i = 0; i <= AngleResolution; ++i) {
                const float angle = float(i) * step_angle;
                init_data.add_vertex(Vec3f(::cos(angle) * ex_radius, ::sin(angle) * ex_radius, 0.0f));
                init_data.add_index(i);
            }
            m_angle_arc.init_from(std::move(init_data));
        }
    }
    m_angle_arc.set_color(color);
    m_angle_arc.render();
}
References Slic3r::GUI::GLModel::Geometry::add_index(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::angle(), AngleResolution, cos(), EPSILON, Slic3r::GUI::GLModel::Geometry::format, GrabberOffset, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::GLModel::Geometry::LineStrip, m_angle, m_angle_arc, m_old_angle, m_radius, Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::reset(), Slic3r::GUI::GLModel::set_color(), and sin().
Referenced by on_render().
render_circle()
void Slic3r::GUI::GLGizmoRotate::render_circle (const ColorRGBA & color, bool radius_changed) private
{
    if (!m_circle.is_initialized() || radius_changed) {
        m_circle.reset();
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::LineLoop, GLModel::Geometry::EVertexLayout::P3 };
        init_data.reserve_vertices(ScaleStepsCount);
        init_data.reserve_indices(ScaleStepsCount);
        // vertices + indices
        for (unsigned int i = 0; i < ScaleStepsCount; ++i) {
            const float angle = float(i * ScaleStepRad);
            init_data.add_vertex(Vec3f(::cos(angle) * m_radius, ::sin(angle) * m_radius, 0.0f));
            init_data.add_index(i);
        }
        m_circle.init_from(std::move(init_data));
    }
    m_circle.set_color(color);
    m_circle.render();
}
References Slic3r::GUI::GLModel::Geometry::add_index(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::angle(), cos(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::GLModel::Geometry::LineLoop, m_circle, m_radius, Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::reset(), ScaleStepRad, ScaleStepsCount, Slic3r::GUI::GLModel::set_color(), and sin().
Referenced by on_render().
render_grabber()
void Slic3r::GUI::GLGizmoRotate::render_grabber (const BoundingBoxf3 & box) private
{
    m_grabbers.front().color = m_highlight_color;
    render_grabbers(box);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, m_highlight_color, and Slic3r::GUI::GLGizmoBase::render_grabbers().
Referenced by on_render().
render_grabber_connection()
void Slic3r::GUI::GLGizmoRotate::render_grabber_connection (const ColorRGBA & color, bool radius_changed) private
{
    if (!m_grabber_connection.model.is_initialized() || radius_changed || !m_grabber_connection.old_center.isApprox(m_grabbers.front().center)) {
        m_grabber_connection.model.reset();
        m_grabber_connection.old_center = m_grabbers.front().center;
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::Lines, GLModel::Geometry::EVertexLayout::P3 };
        init_data.reserve_vertices(2);
        init_data.reserve_indices(2);
        // vertices
        init_data.add_vertex(Vec3f(0.0f, 0.0f, 0.0f));
        init_data.add_vertex((Vec3f)m_grabbers.front().center.cast<float>());
        // indices
        init_data.add_line(0, 1);
        m_grabber_connection.model.init_from(std::move(init_data));
    }
    m_grabber_connection.model.set_color(color);
    m_grabber_connection.model.render();
}
References Slic3r::GUI::GLModel::Geometry::add_line(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::GLModel::Geometry::Lines, m_grabber_connection, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoRotate::GrabberConnection::model, Slic3r::GUI::GLGizmoRotate::GrabberConnection::old_center, Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::reset(), and Slic3r::GUI::GLModel::set_color().
Referenced by on_render().
render_grabbers() [1/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
}
References Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointType >::size().
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), render_grabber(), Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    render_grabbers(0, m_grabbers.size() - 1, size, false);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [3/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (size_t first, size_t last, float size, bool force_hover) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    glsafe(::glDisable(GL_CULL_FACE));
    for (size_t i = first; i <= last; ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(force_hover ? true : m_hover_id == (int)i, size);
    }
    glsafe(::glEnable(GL_CULL_FACE));
    shader->stop_using();
}
References glsafe, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // imgui windows that don't have an initial size needs to be processed once to get one
        // and are not rendered in the first frame
        // so, we forces to render another frame the first time the imgui window is shown
        // https://github.com/ocornut/imgui/issues/2949
        m_parent.set_as_dirty();
        m_parent.request_extra_frame();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), Slic3r::GUI::GLCanvas3D::request_extra_frame(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
render_reference_radius()
void Slic3r::GUI::GLGizmoRotate::render_reference_radius (const ColorRGBA & color, bool radius_changed) private
{
    if (!m_reference_radius.is_initialized() || radius_changed) {
        m_reference_radius.reset();
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::Lines, GLModel::Geometry::EVertexLayout::P3 };
        init_data.reserve_vertices(2);
        init_data.reserve_indices(2);
        // vertices
        init_data.add_vertex(Vec3f(0.0f, 0.0f, 0.0f));
        init_data.add_vertex(Vec3f(m_radius * (1.0f + GrabberOffset), 0.0f, 0.0f));
        // indices
        init_data.add_line(0, 1);
        m_reference_radius.init_from(std::move(init_data));
    }
    m_reference_radius.set_color(color);
    m_reference_radius.render();
}
References Slic3r::GUI::GLModel::Geometry::add_line(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::GUI::GLModel::Geometry::format, GrabberOffset, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::GLModel::Geometry::Lines, m_radius, m_reference_radius, Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::reset(), and Slic3r::GUI::GLModel::set_color().
Referenced by on_render().
render_scale()
void Slic3r::GUI::GLGizmoRotate::render_scale (const ColorRGBA & color, bool radius_changed) private
{
    const float out_radius_long = m_snap_fine_out_radius;
    const float out_radius_short = m_radius * (1.0f + 0.5f * ScaleLongTooth);
    if (!m_scale.is_initialized() || radius_changed) {
        m_scale.reset();
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::Lines, GLModel::Geometry::EVertexLayout::P3 };
        init_data.reserve_vertices(2 * ScaleStepsCount);
        init_data.reserve_indices(2 * ScaleStepsCount);
        // vertices + indices
        for (unsigned int i = 0; i < ScaleStepsCount; ++i) {
            const float angle = float(i * ScaleStepRad);
            const float cosa = ::cos(angle);
            const float sina = ::sin(angle);
            const float in_x = cosa * m_radius;
            const float in_y = sina * m_radius;
            const float out_x = (i % ScaleLongEvery == 0) ? cosa * out_radius_long : cosa * out_radius_short;
            const float out_y = (i % ScaleLongEvery == 0) ? sina * out_radius_long : sina * out_radius_short;
            // vertices
            init_data.add_vertex(Vec3f(in_x, in_y, 0.0f));
            init_data.add_vertex(Vec3f(out_x, out_y, 0.0f));
            // indices
            init_data.add_line(i * 2, i * 2 + 1);
        }
        m_scale.init_from(std::move(init_data));
    }
    m_scale.set_color(color);
    m_scale.render();
}
References Slic3r::GUI::GLModel::Geometry::add_line(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::angle(), cos(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::GLModel::Geometry::Lines, m_radius, m_scale, m_snap_fine_out_radius, Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::reset(), ScaleLongEvery, ScaleLongTooth, ScaleStepRad, ScaleStepsCount, Slic3r::GUI::GLModel::set_color(), and sin().
Referenced by on_render().
render_snap_radii()
void Slic3r::GUI::GLGizmoRotate::render_snap_radii (const ColorRGBA & color, bool radius_changed) private
{
    const float step = 2.0f * float(PI) / float(SnapRegionsCount);
    const float in_radius = m_radius / 3.0f;
    const float out_radius = 2.0f * in_radius;
    if (!m_snap_radii.is_initialized() || radius_changed) {
        m_snap_radii.reset();
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::Lines, GLModel::Geometry::EVertexLayout::P3 };
        init_data.reserve_vertices(2 * ScaleStepsCount);
        init_data.reserve_indices(2 * ScaleStepsCount);
        // vertices + indices
        for (unsigned int i = 0; i < ScaleStepsCount; ++i) {
            const float angle = float(i * step);
            const float cosa = ::cos(angle);
            const float sina = ::sin(angle);
            const float in_x = cosa * in_radius;
            const float in_y = sina * in_radius;
            const float out_x = cosa * out_radius;
            const float out_y = sina * out_radius;
            // vertices
            init_data.add_vertex(Vec3f(in_x, in_y, 0.0f));
            init_data.add_vertex(Vec3f(out_x, out_y, 0.0f));
            // indices
            init_data.add_line(i * 2, i * 2 + 1);
        }
        m_snap_radii.init_from(std::move(init_data));
    }
    m_snap_radii.set_color(color);
    m_snap_radii.render();
}
References Slic3r::GUI::GLModel::Geometry::add_line(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::angle(), cos(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::GLModel::Geometry::Lines, m_radius, m_snap_radii, Slic3r::GUI::GLModel::Geometry::P3, PI, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::reset(), ScaleStepsCount, Slic3r::GUI::GLModel::set_color(), sin(), and SnapRegionsCount.
Referenced by on_render().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
set_angle()
void Slic3r::GUI::GLGizmoRotate::set_angle (double angle)
{
    if (std::abs(angle - 2.0 * double(PI)) < EPSILON)
        angle = 0.0;
    m_angle = angle;
}
References Slic3r::angle(), EPSILON, m_angle, and PI.
Referenced by Slic3r::GUI::GLGizmoEmboss::on_init(), and Slic3r::GUI::GLGizmoEmboss::on_stop_dragging().
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c.
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by Slic3r::GUI::GLGizmoCut3D::process_cut_line(), and Slic3r::GUI::GLGizmoSimplify::request_rerender().
set_force_local_coordinate()
void Slic3r::GUI::GLGizmoRotate::set_force_local_coordinate (bool use) inline
{ m_force_local_coordinate = use; }
References m_force_local_coordinate.
Referenced by Slic3r::GUI::GLGizmoEmboss::GLGizmoEmboss().
set_group_id()
void Slic3r::GUI::GLGizmoRotate::set_group_id (int group_id) inline
{ m_group_id = group_id; }
References Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoEmboss::GLGizmoEmboss().
set_highlight_color()
void Slic3r::GUI::GLGizmoRotate::set_highlight_color (const ColorRGBA & color)
{
    m_highlight_color = color;
}
References m_highlight_color.
Referenced by Slic3r::GUI::GLGizmoEmboss::on_init().
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    // do not change hover id during dragging
    assert(!m_dragging);
    // allow empty grabbers when not using grabbers but use hover_id - flatten, rotate
//    if (!m_grabbers.empty() && id >= (int) m_grabbers.size())
//        return;
    m_hover_id = id;
    on_set_hover_id();
}
References Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLGizmoEmboss::on_set_state().
start_dragging()
void Slic3r::GUI::GLGizmoRotate::start_dragging ()
{
    m_grabbers[0].dragging = true;
    on_start_dragging();
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and on_start_dragging().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_start_dragging().
stop_dragging()
void Slic3r::GUI::GLGizmoRotate::stop_dragging ()
{
    m_grabbers[0].dragging = false;
    on_stop_dragging();
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_stop_dragging().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_stop_dragging().
unregister_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].unregister_raycasters_for_picking();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers.
Referenced by Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking().
unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking () inline inherited
{ unregister_grabbers_for_picking(); on_unregister_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
use_grabbers()
bool Slic3r::GUI::GLGizmoBase::use_grabbers (const wxMouseEvent & mouse_event) protected inherited
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
Parameters
mouse_event Keep information about mouse click
Returns
same as on_mouse
{
    bool is_dragging_finished = false;
    if (mouse_event.Moving()) {
        // it should not happen but for sure
        assert(!m_dragging);
        if (m_dragging) is_dragging_finished = true;
        else return false;
    }
    if (mouse_event.LeftDown()) {
        Selection &selection = m_parent.get_selection();
        if (!selection.is_empty() && m_hover_id != -1 /* &&
            (m_grabbers.empty() || m_hover_id < static_cast<int>(m_grabbers.size()))*/) {
            selection.setup_cache();
            m_dragging = true;
            for (auto &grabber : m_grabbers) grabber.dragging = false;
//            if (!m_grabbers.empty() && m_hover_id < int(m_grabbers.size()))
//                m_grabbers[m_hover_id].dragging = true;
            on_start_dragging();
            // Let the plater know that the dragging started
            m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_STARTED));
            m_parent.set_as_dirty();
            return true;
        }
    } else if (m_dragging) {
        // when mouse cursor leave window than finish actual dragging operation
        bool is_leaving = mouse_event.Leaving();
        if (mouse_event.Dragging()) {
            Point      mouse_coord(mouse_event.GetX(), mouse_event.GetY());
            auto       ray = m_parent.mouse_ray(mouse_coord);
            UpdateData data(ray, mouse_coord);
            on_dragging(data);
            wxGetApp().obj_manipul()->set_dirty();
            m_parent.set_as_dirty();
            return true;
        }
        else if (mouse_event.LeftUp() || is_leaving || is_dragging_finished) {
            do_stop_dragging(is_leaving);
            return true;
        }
    }
    return false;
}
References Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_ray(), Slic3r::GUI::GLGizmoBase::on_dragging(), Slic3r::GUI::GLGizmoBase::on_start_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::Selection::setup_cache().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_mouse(), on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation().
wants_enter_leave_snapshots()
virtual bool Slic3r::GUI::GLGizmoBase::wants_enter_leave_snapshots () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
Member Data Documentation
AngleResolution
const unsigned int Slic3r::GUI::GLGizmoRotate::AngleResolution = 64 static private
Referenced by render_angle_arc().
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
GRABBER_ELEMENTS_MAX_COUNT
const unsigned int Slic3r::GUI::GLGizmoBase::GRABBER_ELEMENTS_MAX_COUNT = 7 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render().
GrabberOffset
const float Slic3r::GUI::GLGizmoRotate::GrabberOffset = 0.15f static private
Referenced by on_render(), render_angle_arc(), and render_reference_radius().
m_angle
double Slic3r::GUI::GLGizmoRotate::m_angle { 0.0 } private
Referenced by get_angle(), get_tooltip(), on_dragging(), on_render(), render_angle_arc(), and set_angle().
m_angle_arc
GLModel Slic3r::GUI::GLGizmoRotate::m_angle_arc private
Referenced by render_angle_arc().
m_axis
Axis Slic3r::GUI::GLGizmoRotate::m_axis private
Referenced by get_tooltip(), local_transform(), and mouse_position_in_local_plane().
m_bounding_box
BoundingBoxf3 Slic3r::GUI::GLGizmoRotate::m_bounding_box private
Referenced by init_data_from_selection(), and on_render().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c { nullptr } protected inherited
Referenced by Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoFdmSupports::auto_generate(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::GLGizmoCut3D::check_and_update_connectors_state(), Slic3r::GUI::GLGizmoCut3D::data_changed(), Slic3r::GUI::GLGizmoFdmSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoCut3D::has_valid_contour(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoCut3D::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::GLGizmoCut3D::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoHollow::reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), Slic3r::GUI::GLGizmoCut3D::render_clipper_cut(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::GLGizmoCut3D::reset_connectors(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut3D::update_bb(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_center
Vec3d Slic3r::GUI::GLGizmoRotate::m_center { Vec3d::Zero() } private
Referenced by init_data_from_selection(), and mouse_position_in_local_plane().
m_circle
GLModel Slic3r::GUI::GLGizmoRotate::m_circle private
Referenced by render_circle().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty { false } private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_drag_color
ColorRGBA Slic3r::GUI::GLGizmoRotate::m_drag_color private
Referenced by on_render().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging { false } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::GLGizmoBase::set_hover_id(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render { true } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_force_local_coordinate
bool Slic3r::GUI::GLGizmoRotate::m_force_local_coordinate { false } private
Referenced by init_data_from_selection(), and set_force_local_coordinate().
m_grabber_connection
GrabberConnection Slic3r::GUI::GLGizmoRotate::m_grabber_connection private
Referenced by render_grabber_connection().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoMove3D::data_changed(), disable_grabber(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_render(), on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), render_grabber(), render_grabber_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), start_dragging(), stop_dragging(), Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by GLGizmoRotate(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), and set_group_id().
m_highlight_color
ColorRGBA Slic3r::GUI::GLGizmoRotate::m_highlight_color private
Referenced by on_render(), render_grabber(), and set_highlight_color().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id { -1 } protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_xy(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_z(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoCut3D::is_selection_changed(), Slic3r::GUI::GLGizmoCut3D::on_dragging(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_dragging(), Slic3r::GUI::GLGizmoScale3D::on_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging(), Slic3r::GUI::GLGizmoCut3D::on_stop_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename().
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), Slic3r::GUI::GLGizmoCut3D::add_horizontal_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::add_vertical_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::adjust_window_position(), Slic3r::GUI::GLGizmoSimplify::create_gui_cfg(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_style_add_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_popup(), Slic3r::GUI::GLGizmoEmboss::draw_style_save_as_popup(), Slic3r::GUI::GLGizmoEmboss::draw_text_input(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::GLGizmoCut3D::init_input_window_data(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_build_size(), Slic3r::GUI::GLGizmoCut3D::render_combo(), Slic3r::GUI::GLGizmoCut3D::render_connectors_input_window(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoCut3D::render_double_input(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoCut3D::render_input_window_warning(), Slic3r::GUI::GLGizmoCut3D::render_move_center_input(), Slic3r::GUI::GLGizmoCut3D::render_reset_button(), Slic3r::GUI::GLGizmoCut3D::render_shortcuts(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
m_old_angle
float Slic3r::GUI::GLGizmoRotate::m_old_angle { 0.0f } private
Referenced by render_angle_arc().
m_old_hover_radius
float Slic3r::GUI::GLGizmoRotate::m_old_hover_radius { 0.0f } private
Referenced by on_render().
m_old_radius
float Slic3r::GUI::GLGizmoRotate::m_old_radius { 0.0f } private
Referenced by on_render().
m_orient_matrix
Transform3d Slic3r::GUI::GLGizmoRotate::m_orient_matrix { Transform3d::Identity() } private
Referenced by init_data_from_selection(), local_transform(), and mouse_position_in_local_plane().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::add_connector(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::GLGizmoCut3D::bounding_box(), Slic3r::GUI::GLGizmoEmboss::calculate_scale(), Slic3r::GUI::GLGizmoEmboss::close(), Slic3r::GUI::GLGizmoSimplify::close(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoFlatten::data_changed(), Slic3r::GUI::GLGizmoMeasure::data_changed(), Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoRotate3D::data_changed(), Slic3r::GUI::GLGizmoCut3D::delete_selected_connectors(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoEmboss::do_rotate(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoEmboss::do_translate(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeasure::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeasure::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoCut3D::on_load(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_shortcut_key(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), on_start_dragging(), Slic3r::GUI::GLGizmoEmboss::on_stop_dragging(), Slic3r::GUI::GLGizmoMove3D::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoScale3D::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::GLGizmoEmboss::process(), Slic3r::GUI::GLGizmoSimplify::process(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_cut_line(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::register_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::remove_selected_sphere_raycaster(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), Slic3r::GUI::GLGizmoCut3D::reset_cut_by_contours(), Slic3r::GUI::GLGizmoCut3D::reset_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), Slic3r::GUI::GLGizmoCut3D::set_volumes_picking_state(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoCut3D::transformed_bounding_box(), Slic3r::GUI::GLGizmoHollow::unregister_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::unregister_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_radius
float Slic3r::GUI::GLGizmoRotate::m_radius { 0.0f } private
Referenced by init_data_from_selection(), on_render(), render_angle_arc(), render_circle(), render_reference_radius(), render_scale(), and render_snap_radii().
m_reference_radius
GLModel Slic3r::GUI::GLGizmoRotate::m_reference_radius private
Referenced by render_reference_radius().
m_scale
GLModel Slic3r::GUI::GLGizmoRotate::m_scale private
Referenced by render_scale().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoCut3D::on_init(), Slic3r::GUI::GLGizmoEmboss::on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), Slic3r::GUI::GLGizmoHollow::on_init(), Slic3r::GUI::GLGizmoMeasure::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), and Slic3r::GUI::GLGizmoSlaSupports::on_init().
m_snap_coarse_in_radius
float Slic3r::GUI::GLGizmoRotate::m_snap_coarse_in_radius { 0.0f } private
Referenced by init_data_from_selection(), and on_dragging().
m_snap_coarse_out_radius
float Slic3r::GUI::GLGizmoRotate::m_snap_coarse_out_radius { 0.0f } private
Referenced by init_data_from_selection(), and on_dragging().
m_snap_fine_in_radius
float Slic3r::GUI::GLGizmoRotate::m_snap_fine_in_radius { 0.0f } private
Referenced by init_data_from_selection(), and on_dragging().
m_snap_fine_out_radius
float Slic3r::GUI::GLGizmoRotate::m_snap_fine_out_radius { 0.0f } private
Referenced by init_data_from_selection(), on_dragging(), and render_scale().
m_snap_radii
GLModel Slic3r::GUI::GLGizmoRotate::m_snap_radii private
Referenced by render_snap_radii().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_state
EState Slic3r::GUI::GLGizmoBase::m_state protected inherited
Referenced by Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoBase::load(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), Slic3r::GUI::GLGizmoRotate3D::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoBase::set_state(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), and Slic3r::GUI::GLGizmoSimplify::worker_finished().
NO_SHORTCUT_KEY_VALUE
const int Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE = 0 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
Offset
const float Slic3r::GUI::GLGizmoRotate::Offset = 5.0f static private
Referenced by init_data_from_selection().
ScaleLongEvery
const unsigned int Slic3r::GUI::GLGizmoRotate::ScaleLongEvery = 2 static private
Referenced by render_scale().
ScaleLongTooth
const float Slic3r::GUI::GLGizmoRotate::ScaleLongTooth = 0.1f static private
Referenced by init_data_from_selection(), and render_scale().
ScaleStepRad
const float Slic3r::GUI::GLGizmoRotate::ScaleStepRad = 2.0f * float(PI) / GLGizmoRotate::ScaleStepsCount static private
Referenced by render_circle(), and render_scale().
ScaleStepsCount
const unsigned int Slic3r::GUI::GLGizmoRotate::ScaleStepsCount = 72 static private
Referenced by on_dragging(), render_circle(), render_scale(), and render_snap_radii().
SnapRegionsCount
const unsigned int Slic3r::GUI::GLGizmoRotate::SnapRegionsCount = 8 static private
Referenced by on_dragging(), and render_snap_radii().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoRotate.hpp
src/slic3r/GUI/Gizmos/GLGizmoRotate.cpp