Prusa Slicer: RammingPanel Class Reference
RammingPanel Class Reference
#include <src/slic3r/GUI/WipeTowerDialog.hpp>
Public Member Functions
RammingPanel (wxWindow *parent)
RammingPanel (wxWindow *parent, const std::string &data)
std::string get_parameters ()
Private Member Functions
void line_parameters_changed ()
Private Attributes
Chart * m_chart = nullptr
wxSpinCtrl * m_widget_volume = nullptr
wxSpinCtrl * m_widget_ramming_line_width_multiplicator = nullptr
wxSpinCtrl * m_widget_ramming_step_multiplicator = nullptr
wxSpinCtrlDouble * m_widget_time = nullptr
int m_ramming_step_multiplicator
int m_ramming_line_width_multiplicator
Detailed Description
Constructor & Destructor Documentation
RammingPanel() [1/2]
RammingPanel::RammingPanel (wxWindow * parent)
RammingPanel() [2/2]
RammingPanel::RammingPanel (wxWindow * parent, const std::string & data)
: wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize/*,wxPoint(50,50), wxSize(800,350),wxBORDER_RAISED*/)
{
    update_ui(this);
  auto sizer_chart = new wxBoxSizer(wxVERTICAL);
  auto sizer_param = new wxBoxSizer(wxVERTICAL);
  std::stringstream stream{ parameters };
  stream >> m_ramming_line_width_multiplicator >> m_ramming_step_multiplicator;
  int ramming_speed_size = 0;
  float dummy = 0.f;
  while (stream >> dummy)
    ++ramming_speed_size;
  stream.clear();
  stream.get();
  std::vector<std::pair<float, float>> buttons;
  float x = 0.f;
  float y = 0.f;
  while (stream >> x >> y)
    buttons.push_back(std::make_pair(x, y));
  m_chart = new Chart(this, wxRect(scale(1),scale(1),scale(48),scale(36)), buttons, ramming_speed_size, 0.25f, scale(1));
#ifdef _WIN32
    update_ui(m_chart);
#else
    m_chart->SetBackgroundColour(parent->GetBackgroundColour()); // see comment in RammingDialog constructor
#endif
  sizer_chart->Add(m_chart, 0, wxALL, 5);
    m_widget_time           = new wxSpinCtrlDouble(this,wxID_ANY,wxEmptyString,wxDefaultPosition,wxSize(ITEM_WIDTH(), -1),style,0.,5.0,3.,0.5);
    m_widget_volume               = new wxSpinCtrl(this,wxID_ANY,wxEmptyString,wxDefaultPosition,wxSize(ITEM_WIDTH(), -1),style,0,10000,0);
    m_widget_ramming_line_width_multiplicator = new wxSpinCtrl(this,wxID_ANY,wxEmptyString,wxDefaultPosition,wxSize(ITEM_WIDTH(), -1),style,10,200,100);
    m_widget_ramming_step_multiplicator     = new wxSpinCtrl(this,wxID_ANY,wxEmptyString,wxDefaultPosition,wxSize(ITEM_WIDTH(), -1),style,10,200,100);
#ifdef _WIN32
    update_ui(m_widget_time->GetText());
    update_ui(m_widget_volume);
    update_ui(m_widget_ramming_line_width_multiplicator);
    update_ui(m_widget_ramming_step_multiplicator);
#endif
  auto gsizer_param = new wxFlexGridSizer(2, 5, 15);
  gsizer_param->Add(new wxStaticText(this, wxID_ANY, wxString(_(L("Total ramming time")) + " (" + _(L("s")) + "):")), 0, wxALIGN_CENTER_VERTICAL);
  gsizer_param->Add(m_widget_time);
  gsizer_param->Add(new wxStaticText(this, wxID_ANY, wxString(_(L("Total rammed volume")) + " (" + _(L("mm")) + wxString("³):", wxConvUTF8))), 0, wxALIGN_CENTER_VERTICAL);
  gsizer_param->Add(m_widget_volume);
  gsizer_param->AddSpacer(20);
  gsizer_param->AddSpacer(20);
  gsizer_param->Add(new wxStaticText(this, wxID_ANY, wxString(_(L("Ramming line width")) + " (%):")), 0, wxALIGN_CENTER_VERTICAL);
  gsizer_param->Add(m_widget_ramming_line_width_multiplicator);
  gsizer_param->Add(new wxStaticText(this, wxID_ANY, wxString(_(L("Ramming line spacing")) + " (%):")), 0, wxALIGN_CENTER_VERTICAL);
  gsizer_param->Add(m_widget_ramming_step_multiplicator);
  sizer_param->Add(gsizer_param, 0, wxTOP, scale(10));
    m_widget_time->SetValue(m_chart->get_time());
    m_widget_time->SetDigits(2);
    m_widget_volume->SetValue(m_chart->get_volume());
    m_widget_volume->Disable();
    m_widget_ramming_line_width_multiplicator->SetValue(m_ramming_line_width_multiplicator);
    m_widget_ramming_step_multiplicator->SetValue(m_ramming_step_multiplicator);
    m_widget_ramming_step_multiplicator->Bind(wxEVT_TEXT,[this](wxCommandEvent&) { line_parameters_changed(); });
    m_widget_ramming_line_width_multiplicator->Bind(wxEVT_TEXT,[this](wxCommandEvent&) { line_parameters_changed(); });
  auto sizer = new wxBoxSizer(wxHORIZONTAL);
  sizer->Add(sizer_chart, 0, wxALL, 5);
  sizer->Add(sizer_param, 0, wxALL, 10);
  sizer->SetSizeHints(this);
  SetSizer(sizer);
    m_widget_time->Bind(wxEVT_TEXT,[this](wxCommandEvent&) {m_chart->set_xy_range(m_widget_time->GetValue(),-1);});
    m_widget_time->Bind(wxEVT_CHAR,[](wxKeyEvent&){});      // do nothing - prevents the user to change the value
    m_widget_volume->Bind(wxEVT_CHAR,[](wxKeyEvent&){});    // do nothing - prevents the user to change the value
    Bind(EVT_WIPE_TOWER_CHART_CHANGED,[this](wxCommandEvent&) {m_widget_volume->SetValue(m_chart->get_volume()); m_widget_time->SetValue(m_chart->get_time());} );
    Refresh(true); // erase background
}
References _, Chart::get_time(), Chart::get_volume(), ITEM_WIDTH(), L, line_parameters_changed(), m_chart, m_ramming_line_width_multiplicator, m_ramming_step_multiplicator, m_widget_ramming_line_width_multiplicator, m_widget_ramming_step_multiplicator, m_widget_time, m_widget_volume, scale(), Chart::set_xy_range(), style, and update_ui().
Member Function Documentation
get_parameters()
std::string RammingPanel::get_parameters ()
{
    std::vector<float> speeds = m_chart->get_ramming_speed(0.25f);
    std::vector<std::pair<float,float>> buttons = m_chart->get_buttons();
    std::stringstream stream;
    stream << m_ramming_line_width_multiplicator << " " << m_ramming_step_multiplicator;
    for (const float& speed_value : speeds)
        stream << " " << speed_value;
    stream << "|";
    for (const auto& button : buttons)
        stream << " " << button.first << " " << button.second;
    return stream.str();
}
References Chart::get_buttons(), Chart::get_ramming_speed(), m_chart, m_ramming_line_width_multiplicator, and m_ramming_step_multiplicator.
Referenced by RammingDialog::RammingDialog().
line_parameters_changed()
void RammingPanel::line_parameters_changed () private
{
    m_ramming_line_width_multiplicator = m_widget_ramming_line_width_multiplicator->GetValue();
    m_ramming_step_multiplicator = m_widget_ramming_step_multiplicator->GetValue();
}
References m_ramming_line_width_multiplicator, m_ramming_step_multiplicator, m_widget_ramming_line_width_multiplicator, and m_widget_ramming_step_multiplicator.
Referenced by RammingPanel().
Member Data Documentation
m_chart
Chart* RammingPanel::m_chart = nullptr private
Referenced by RammingPanel(), and get_parameters().
m_ramming_line_width_multiplicator
int RammingPanel::m_ramming_line_width_multiplicator private
Referenced by RammingPanel(), get_parameters(), and line_parameters_changed().
m_ramming_step_multiplicator
int RammingPanel::m_ramming_step_multiplicator private
Referenced by RammingPanel(), get_parameters(), and line_parameters_changed().
m_widget_ramming_line_width_multiplicator
wxSpinCtrl* RammingPanel::m_widget_ramming_line_width_multiplicator = nullptr private
Referenced by RammingPanel(), and line_parameters_changed().
m_widget_ramming_step_multiplicator
wxSpinCtrl* RammingPanel::m_widget_ramming_step_multiplicator = nullptr private
Referenced by RammingPanel(), and line_parameters_changed().
m_widget_time
wxSpinCtrlDouble* RammingPanel::m_widget_time = nullptr private
Referenced by RammingPanel().
m_widget_volume
wxSpinCtrl* RammingPanel::m_widget_volume = nullptr private
Referenced by RammingPanel().
The documentation for this class was generated from the following files:
src/slic3r/GUI/WipeTowerDialog.hpp
src/slic3r/GUI/WipeTowerDialog.cpp