Prusa Slicer: Slic3r::SlicingProcessCompletedEvent Class Reference
Slic3r::SlicingProcessCompletedEvent Class Reference
#include <src/slic3r/GUI/BackgroundSlicingProcess.hpp>
Public Types
enum StatusType { Finished , Cancelled , Error }
Public Member Functions
SlicingProcessCompletedEvent (wxEventType eventType, int winid, StatusType status, std::exception_ptr exception)
virtual wxEvent * Clone () const
StatusType status () const
bool finished () const
bool success () const
bool cancelled () const
bool error () const
bool critical_error () const
bool invalidate_plater () const
void rethrow_exception () const
std::pair< std::string, bool > format_error_message () const
Private Attributes
StatusType m_status
std::exception_ptr m_exception
Detailed Description
Member Enumeration Documentation
StatusType
enum Slic3r::SlicingProcessCompletedEvent::StatusType
Enumerator
Finished
Cancelled
Error
                  {
    Finished,
    Cancelled,
    Error
  };
Constructor & Destructor Documentation
SlicingProcessCompletedEvent()
Slic3r::SlicingProcessCompletedEvent::SlicingProcessCompletedEvent (wxEventType eventType, int winid, StatusType status, std::exception_ptr exception) inline
                                                                                                                :
    wxEvent(winid, eventType), m_status(status), m_exception(exception) {}
Member Function Documentation
cancelled()
bool Slic3r::SlicingProcessCompletedEvent::cancelled () const inline
{ return m_status == Cancelled; }
References Cancelled, and m_status.
Referenced by Slic3r::GUI::Plater::priv::on_process_completed().
Clone()
virtual wxEvent * Slic3r::SlicingProcessCompletedEvent::Clone () const inline virtual
{ return new SlicingProcessCompletedEvent(*this); }
Referenced by Slic3r::BackgroundSlicingProcess::thread_proc().
critical_error()
bool Slic3r::SlicingProcessCompletedEvent::critical_error () const
{
  try {
    this->rethrow_exception();
  } catch (const Slic3r::SlicingError &) {
    // Exception derived from SlicingError is non-critical.
    return false;
  } catch (...) {
  }
  return true;
}
References rethrow_exception().
Referenced by invalidate_plater(), and Slic3r::GUI::Plater::priv::on_process_completed().
error()
bool Slic3r::SlicingProcessCompletedEvent::error () const inline
{ return m_status == Error; }
References Error, and m_status.
Referenced by format_error_message(), Slic3r::GUI::Plater::priv::on_process_completed(), and rethrow_exception().
finished()
bool Slic3r::SlicingProcessCompletedEvent::finished () const inline
{ return m_status == Finished; }
References Finished, and m_status.
format_error_message()
std::pair< std::string, bool > Slic3r::SlicingProcessCompletedEvent::format_error_message () const
{
  std::string error;
  bool        monospace = false;
  try {
    this->rethrow_exception();
    } catch (const std::bad_alloc &ex) {
    error = GUI::format(_L("%s has encountered an error. It was likely caused by running out of memory. "
                              "If you are sure you have enough RAM on your system, this may also be a bug and we would "
                              "be glad if you reported it."), SLIC3R_APP_NAME);
        error += "\n\n" + std::string(ex.what());
    } catch (const HardCrash &ex) {
        error = GUI::format(_L("PrusaSlicer has encountered a fatal error: \"%1%\""), ex.what()) + "\n\n" +
            _u8L("Please save your project and restart PrusaSlicer. "
                     "We would be glad if you reported the issue.");
    } catch (PlaceholderParserError &ex) {
    error = ex.what();
    monospace = true;
    } catch (std::exception &ex) {
    error = ex.what();
  } catch (...) {
    error = "Unknown C++ exception.";
  }
  return std::make_pair(std::move(error), monospace);
}
References _L, _u8L, error(), Slic3r::GUI::format(), and rethrow_exception().
Referenced by Slic3r::GUI::Plater::priv::on_process_completed().
invalidate_plater()
bool Slic3r::SlicingProcessCompletedEvent::invalidate_plater () const
{
  if (critical_error())
  {
    try {
      this->rethrow_exception();
    }
    catch (const Slic3r::ExportError&) {
      // Exception thrown by copying file does not ivalidate plater
      return false;
    }
    catch (...) {
    }
    return true;
  }
  return false;
}
References critical_error(), and rethrow_exception().
Referenced by Slic3r::GUI::Plater::priv::on_process_completed().
rethrow_exception()
void Slic3r::SlicingProcessCompletedEvent::rethrow_exception () const inline
{ assert(this->error()); assert(m_exception); std::rethrow_exception(m_exception); }
References error(), and m_exception.
Referenced by critical_error(), format_error_message(), and invalidate_plater().
status()
StatusType Slic3r::SlicingProcessCompletedEvent::status () const inline
{ return m_status; }
References m_status.
success()
bool Slic3r::SlicingProcessCompletedEvent::success () const inline
{ return m_status == Finished; }
References Finished, and m_status.
Referenced by Slic3r::GUI::Plater::priv::on_process_completed().
Member Data Documentation
m_exception
std::exception_ptr Slic3r::SlicingProcessCompletedEvent::m_exception private
Referenced by rethrow_exception().
m_status
StatusType Slic3r::SlicingProcessCompletedEvent::m_status private
Referenced by cancelled(), error(), finished(), status(), and success().
The documentation for this class was generated from the following files:
src/slic3r/GUI/BackgroundSlicingProcess.hpp
src/slic3r/GUI/BackgroundSlicingProcess.cpp