Prusa Slicer: igl::geodesic::Vertex Class Reference
igl::geodesic::Vertex Class Reference
Public Types
typedef SimpleVector< vertex_pointer > vertex_pointer_vector
typedef SimpleVector< edge_pointer > edge_pointer_vector
typedef SimpleVector< face_pointer > face_pointer_vector
Public Member Functions
Vertex ()
~Vertex ()
bool & saddle_or_boundary ()
vertex_pointer_vector & adjacent_vertices ()
edge_pointer_vector & adjacent_edges ()
face_pointer_vector & adjacent_faces ()
unsigned & id ()
PointType type ()
double * xyz ()
double & x ()
double & y ()
double & z ()
void set (double new_x, double new_y, double new_z)
void set (double *data)
double distance (double *v)
double distance (Point3D *v)
void add (Point3D *v)
void multiply (double v)
Protected Attributes
vertex_pointer_vector m_adjacent_vertices
edge_pointer_vector m_adjacent_edges
face_pointer_vector m_adjacent_faces
unsigned m_id
PointType m_type
Private Attributes
bool m_saddle_or_boundary
double m_coordinates [3]
Detailed Description
Member Typedef Documentation
edge_pointer_vector
typedef SimpleVector<edge_pointer> igl::geodesic::MeshElementBase::edge_pointer_vector inherited
face_pointer_vector
typedef SimpleVector<face_pointer> igl::geodesic::MeshElementBase::face_pointer_vector inherited
vertex_pointer_vector
typedef SimpleVector<vertex_pointer> igl::geodesic::MeshElementBase::vertex_pointer_vector inherited
Constructor & Destructor Documentation
Vertex()
igl::geodesic::Vertex::Vertex () inline
  {
    m_type = VERTEX;
  };
References igl::geodesic::MeshElementBase::m_type, and igl::geodesic::VERTEX.
~Vertex()
igl::geodesic::Vertex::~Vertex () inline
{};
Member Function Documentation
add()
void igl::geodesic::Point3D::add (Point3D * v) inline inherited
  {
    x() += v->x();
    y() += v->y();
    z() += v->z();
  };
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
Referenced by igl::geodesic::SurfacePoint::SurfacePoint().
adjacent_edges()
edge_pointer_vector & igl::geodesic::MeshElementBase::adjacent_edges () inline inherited
{return m_adjacent_edges;};
References igl::geodesic::MeshElementBase::m_adjacent_edges.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::GeodesicAlgorithmExact::list_edges_visible_from_source(), igl::geodesic::Face::next_edge(), igl::geodesic::Face::opposite_edge(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), igl::geodesic::Mesh::verify(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
adjacent_faces()
face_pointer_vector & igl::geodesic::MeshElementBase::adjacent_faces () inline inherited
{return m_adjacent_faces;};
References igl::geodesic::MeshElementBase::m_adjacent_faces.
Referenced by igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::GeodesicAlgorithmExact::construct_propagated_intervals(), igl::geodesic::Edge::is_boundary(), igl::geodesic::Edge::opposite_face(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), and igl::geodesic::GeodesicAlgorithmExact::propagate().
adjacent_vertices()
vertex_pointer_vector & igl::geodesic::MeshElementBase::adjacent_vertices () inline inherited
{return m_adjacent_vertices;};
References igl::geodesic::MeshElementBase::m_adjacent_vertices.
Referenced by igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::Edge::belongs(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Face::opposite_vertex(), igl::geodesic::Edge::opposite_vertex(), igl::geodesic::Edge::v0(), igl::geodesic::Edge::v1(), igl::geodesic::Mesh::verify(), and igl::geodesic::Face::vertex_angle().
distance() [1/2]
double igl::geodesic::Point3D::distance (double * v) inline inherited
  {
    double dx = m_coordinates[0] - v[0];
    double dy = m_coordinates[1] - v[1];
    double dz = m_coordinates[2] - v[2];
    return sqrt(dx*dx + dy*dy + dz*dz);
  };
References igl::geodesic::Point3D::m_coordinates, and sqrt().
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Point3D::distance(), igl::geodesic::Edge::local_coordinates(), igl::geodesic::GeodesicAlgorithmBase::set_stop_conditions(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
distance() [2/2]
double igl::geodesic::Point3D::distance (Point3D * v) inline inherited
  {
    return distance(v->xyz());
  };
References igl::geodesic::Point3D::distance(), and igl::geodesic::Point3D::xyz().
id()
unsigned & igl::geodesic::MeshElementBase::id () inline inherited
{return m_id;};
References igl::geodesic::MeshElementBase::m_id.
Referenced by igl::geodesic::Edge::belongs(), igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions(), igl::geodesic::GeodesicAlgorithmExact::construct_propagated_intervals(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Interval::initialize(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::GeodesicAlgorithmExact::intersect_intervals(), igl::geodesic::GeodesicAlgorithmExact::interval_list(), igl::geodesic::Face::next_edge(), igl::geodesic::Edge::opposite_face(), igl::geodesic::Edge::opposite_vertex(), igl::geodesic::GeodesicAlgorithmExact::propagate(), igl::geodesic::Mesh::verify(), igl::geodesic::Face::vertex_angle(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
multiply()
void igl::geodesic::Point3D::multiply (double v) inline inherited
  {
    x() *= v;
    y() *= v;
    z() *= v;
  };
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
Referenced by igl::geodesic::SurfacePoint::SurfacePoint().
saddle_or_boundary()
bool & igl::geodesic::Vertex::saddle_or_boundary () inline
{return m_saddle_or_boundary;};
References m_saddle_or_boundary.
Referenced by igl::geodesic::Mesh::build_adjacencies(), and igl::geodesic::GeodesicAlgorithmExact::propagate().
set() [1/2]
void igl::geodesic::Point3D::set (double * data) inline inherited
  {
    x() = *data;
    y() = *(data+1);
    z() = *(data+2);
  }
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
set() [2/2]
void igl::geodesic::Point3D::set (double new_x, double new_y, double new_z) inline inherited
  {
    x() = new_x;
    y() = new_y;
    z() = new_z;
  }
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
Referenced by igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), and igl::geodesic::fill_surface_point_structure().
type()
PointType igl::geodesic::MeshElementBase::type () inline inherited
{return m_type;};
References igl::geodesic::MeshElementBase::m_type.
Referenced by igl::geodesic::Interval::initialize(), igl::geodesic::GeodesicAlgorithmExact::list_edges_visible_from_source(), and igl::geodesic::SurfacePoint::type().
x()
double & igl::geodesic::Point3D::x () inline inherited
{return *m_coordinates;};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::Point3D(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::Point3D::add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Point3D::multiply(), igl::geodesic::SurfacePointWithIndex::operator()(), igl::geodesic::Point3D::set(), igl::geodesic::Point3D::set(), and igl::geodesic::Mesh::verify().
xyz()
double * igl::geodesic::Point3D::xyz () inline inherited
{return m_coordinates;};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::distance().
y()
double & igl::geodesic::Point3D::y () inline inherited
{return *(m_coordinates+1);};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::Point3D(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::Point3D::add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Point3D::multiply(), igl::geodesic::SurfacePointWithIndex::operator()(), igl::geodesic::Point3D::set(), igl::geodesic::Point3D::set(), and igl::geodesic::Mesh::verify().
z()
double & igl::geodesic::Point3D::z () inline inherited
{return *(m_coordinates+2);};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::Point3D(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::Point3D::add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Point3D::multiply(), igl::geodesic::Point3D::set(), igl::geodesic::Point3D::set(), and igl::geodesic::Mesh::verify().
Member Data Documentation
m_adjacent_edges
edge_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_edges protected inherited
Referenced by igl::geodesic::MeshElementBase::adjacent_edges().
m_adjacent_faces
face_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_faces protected inherited
Referenced by igl::geodesic::MeshElementBase::adjacent_faces().
m_adjacent_vertices
vertex_pointer_vector igl::geodesic::MeshElementBase::m_adjacent_vertices protected inherited
Referenced by igl::geodesic::MeshElementBase::adjacent_vertices().
m_coordinates
double igl::geodesic::Point3D::m_coordinates[3] private inherited
Referenced by igl::geodesic::Point3D::distance(), igl::geodesic::Point3D::x(), igl::geodesic::Point3D::xyz(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
m_id
unsigned igl::geodesic::MeshElementBase::m_id protected inherited
Referenced by igl::geodesic::MeshElementBase::id().
m_saddle_or_boundary
bool igl::geodesic::Vertex::m_saddle_or_boundary private
Referenced by saddle_or_boundary().
m_type
PointType igl::geodesic::MeshElementBase::m_type protected inherited
Referenced by igl::geodesic::Edge::Edge(), igl::geodesic::Face::Face(), Vertex(), and igl::geodesic::MeshElementBase::type().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp