Prusa Slicer: Slic3r::GUI::GCodeViewer::Extrusions::Range Struct Reference
Slic3r::GUI::GCodeViewer::Extrusions::Range Struct Reference
#include <src/slic3r/GUI/GCodeViewer.hpp>
Public Types
enum class EType : unsigned char { Linear , Logarithmic }
Public Member Functions
Range ()
void update_from (const float value)
void reset ()
float step_size (EType type=EType::Linear) const
ColorRGBA get_color_at (float value, EType type=EType::Linear) const
Public Attributes
float min
float max
unsigned int count
Detailed Description
Member Enumeration Documentation
EType
enum class Slic3r::GUI::GCodeViewer::Extrusions::Range::EType : unsigned char strong
Enumerator
Linear
Logarithmic
            {
                Linear,
                Logarithmic
            };
Constructor & Destructor Documentation
Range()
Slic3r::GUI::GCodeViewer::Extrusions::Range::Range () inline
{ reset(); }
References reset().
Member Function Documentation
get_color_at()
ColorRGBA Slic3r::GUI::GCodeViewer::Extrusions::Range::get_color_at (float value, EType type = EType::Linear) const
{
    // Input value scaled to the colors range
    float global_t = 0.0f;
    const float step = step_size(type);
    if (step > 0.0f) {
        switch (type)
        {
        default:
        case EType::Linear:      { global_t = (value > min) ? (value - min) / step : 0.0f; break; }
        case EType::Logarithmic: { global_t = (value > min && min > 0.0f) ? ::log(value / min) / step : 0.0f; break; }
        }
    }
    const size_t color_max_idx = Range_Colors.size() - 1;
    // Compute the two colors just below (low) and above (high) the input value
    const size_t color_low_idx  = std::clamp<size_t>(static_cast<size_t>(global_t), 0, color_max_idx);
    const size_t color_high_idx = std::clamp<size_t>(color_low_idx + 1, 0, color_max_idx);
    // Interpolate between the low and high colors to find exactly which color the input value should get
    return lerp(Range_Colors[color_low_idx], Range_Colors[color_high_idx], global_t - static_cast<float>(color_low_idx));
}
References Slic3r::lerp(), log(), and Slic3r::GUI::GCodeViewer::Range_Colors.
Referenced by Slic3r::GUI::GCodeViewer::refresh_render_paths().
reset()
void Slic3r::GUI::GCodeViewer::Extrusions::Range::reset () inline
{ min = FLT_MAX; max = -FLT_MAX; count = 0; }
References count, max, and min.
Referenced by Range(), and Slic3r::GUI::GCodeViewer::Extrusions::Ranges::reset().
step_size()
float Slic3r::GUI::GCodeViewer::Extrusions::Range::step_size (EType type = EType::Linear) const
{
    switch (type)
    {
    default:
    case EType::Linear:      { return (max > min) ? (max - min) / (static_cast<float>(Range_Colors.size()) - 1.0f) : 0.0f; }
    case EType::Logarithmic: { return (max > min && min > 0.0f) ? ::log(max / min) / (static_cast<float>(Range_Colors.size()) - 1.0f) : 0.0f; }
    }
}
References log(), and Slic3r::GUI::GCodeViewer::Range_Colors.
update_from()
void Slic3r::GUI::GCodeViewer::Extrusions::Range::update_from (const float value) inline
{
                if (value != max && value != min)
                    ++count;
                min = std::min(min, value);
                max = std::max(max, value);
            }
References count, max, and min.
Referenced by Slic3r::GUI::GCodeViewer::refresh().
Member Data Documentation
count
unsigned int Slic3r::GUI::GCodeViewer::Extrusions::Range::count
Referenced by reset(), and update_from().
max
float Slic3r::GUI::GCodeViewer::Extrusions::Range::max
Referenced by reset(), and update_from().
min
float Slic3r::GUI::GCodeViewer::Extrusions::Range::min
Referenced by reset(), and update_from().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GCodeViewer.hpp
src/slic3r/GUI/GCodeViewer.cpp