Prusa Slicer: Slic3r::sla::ConcaveHull Class Reference
Slic3r::sla::ConcaveHull Class Reference
A fake concave hull that is constructed by connecting separate shapes with explicit bridges. Bridges are generated from each shape's centroid to the center of the "scene" which is the centroid calculated from the shape centroids (a star is created...)
#include <src/libslic3r/SLA/ConcaveHull.hpp>
Public Member Functions
ConcaveHull (const ExPolygons &polys, double merge_dist, ThrowOnCancel thr)
ConcaveHull (const Polygons &polys, double mergedist, ThrowOnCancel thr)
const Polygons & polygons () const
ExPolygons to_expolygons () const
Private Member Functions
Points calculate_centroids () const
void merge_polygons ()
void add_connector_rectangles (const Points &centroids, coord_t max_dist, ThrowOnCancel thr)
Static Private Member Functions
static Point centroid (const Points &pp)
static Point centroid (const Polygon &poly)
Private Attributes
Polygons m_polys
Detailed Description
A fake concave hull that is constructed by connecting separate shapes with explicit bridges. Bridges are generated from each shape's centroid to the center of the "scene" which is the centroid calculated from the shape centroids (a star is created...)
Constructor & Destructor Documentation
ConcaveHull() [1/2]
Slic3r::sla::ConcaveHull::ConcaveHull (const ExPolygons & polys, double merge_dist, ThrowOnCancel thr) inline
        : ConcaveHull{to_polygons(polys), merge_dist, thr} {}
ConcaveHull() [2/2]
Slic3r::sla::ConcaveHull::ConcaveHull (const Polygons & polys, double mergedist, ThrowOnCancel thr)
{
    if(polys.empty()) return;
    m_polys = polys;
    merge_polygons();
    if(m_polys.size() == 1) return;
    Points centroids = calculate_centroids();
    add_connector_rectangles(centroids, scaled(mergedist), thr);
    merge_polygons();
}
References add_connector_rectangles(), calculate_centroids(), m_polys, merge_polygons(), and Slic3r::scaled().
Member Function Documentation
add_connector_rectangles()
void Slic3r::sla::ConcaveHull::add_connector_rectangles (const Points & centroids, coord_t max_dist, ThrowOnCancel thr) private
{
    // Centroid of the centroids of islands. This is where the additional
    // connector sticks are routed.
    Point cc = centroid(centroids);
    PointIndex ctrindex;
    unsigned  idx = 0;
    for(const Point &ct : centroids) ctrindex.insert(to_vec3(ct), idx++);
    m_polys.reserve(m_polys.size() + centroids.size());
    idx = 0;
    for (const Point &c : centroids) {
        thr();
        double dx = c.x() - cc.x(), dy = c.y() - cc.y();
        double l  = std::sqrt(dx * dx + dy * dy);
        double nx = dx / l, ny = dy / l;
        const Point &ct = centroids[idx];
        std::vector<PointIndexEl> result = ctrindex.nearest(to_vec3(ct), 2);
        double dist = max_dist;
        for (const PointIndexEl &el : result)
            if (el.second != idx) {
                dist = Line(to_vec2(el.first), ct).length();
                break;
            }
        idx++;
        if (dist >= max_dist) return;
        Polygon r;
        r.points.reserve(3);
        r.points.emplace_back(cc);
        Point n(scaled(nx), scaled(ny));
        r.points.emplace_back(c + Point(n.y(), -n.x()));
        r.points.emplace_back(c + Point(-n.y(), n.x()));
        offset(r, scaled<float>(1.));
        m_polys.emplace_back(r);
    }
}
References centroid(), Slic3r::sla::PointIndex::insert(), Slic3r::Line::length(), m_polys, Slic3r::sla::PointIndex::nearest(), Slic3r::offset(), Slic3r::MultiPoint::points, Slic3r::scaled(), Slic3r::sla::to_vec2(), and Slic3r::sla::to_vec3().
Referenced by ConcaveHull().
calculate_centroids()
Points Slic3r::sla::ConcaveHull::calculate_centroids () const private
{
    // We get the centroids of all the islands in the 2D slice
    Points centroids;
    centroids.reserve(m_polys.size());
    std::transform(m_polys.begin(), m_polys.end(),
                   std::back_inserter(centroids),
                   [](const Polygon &poly) { return centroid(poly); });
    return centroids;
}
References m_polys.
Referenced by ConcaveHull().
centroid() [1/2]
Point Slic3r::sla::ConcaveHull::centroid (const Points & pp) static private
{
    Point c;
    switch(pp.size()) {
    case 0: break;
    case 1: c = pp.front(); break;
    case 2: c = (pp[0] + pp[1]) / 2; break;
    default: {
        auto MAX = std::numeric_limits<Point::coord_type>::max();
        auto MIN = std::numeric_limits<Point::coord_type>::min();
        Point min = {MAX, MAX}, max = {MIN, MIN};
        for(auto& p : pp) {
            if(p(0) < min(0)) min(0) = p(0);
            if(p(1) < min(1)) min(1) = p(1);
            if(p(0) > max(0)) max(0) = p(0);
            if(p(1) > max(1)) max(1) = p(1);
        }
        c(0) = min(0) + (max(0) - min(0)) / 2;
        c(1) = min(1) + (max(1) - min(1)) / 2;
        break;
    }
    }
    return c;
}
References MAX, and MIN.
Referenced by add_connector_rectangles().
centroid() [2/2]
static Point Slic3r::sla::ConcaveHull::centroid (const Polygon & poly) inline static private
{ return poly.centroid(); }
References Slic3r::Polygon::centroid().
merge_polygons()
void Slic3r::sla::ConcaveHull::merge_polygons () private
{ m_polys = get_contours(union_ex(m_polys)); }
References Slic3r::sla::get_contours(), m_polys, and Slic3r::union_ex().
Referenced by ConcaveHull().
polygons()
const Polygons & Slic3r::sla::ConcaveHull::polygons () const inline
{ return m_polys; }
References m_polys.
Referenced by Slic3r::sla::offset_waffle_style().
to_expolygons()
ExPolygons Slic3r::sla::ConcaveHull::to_expolygons () const
{
    auto ret = reserve_vector<ExPolygon>(m_polys.size());
    for (const Polygon &p : m_polys) ret.emplace_back(ExPolygon(p));
    return ret;
}
References m_polys.
Member Data Documentation
m_polys
Polygons Slic3r::sla::ConcaveHull::m_polys private
Referenced by ConcaveHull(), add_connector_rectangles(), calculate_centroids(), merge_polygons(), polygons(), and to_expolygons().
The documentation for this class was generated from the following files:
src/libslic3r/SLA/ConcaveHull.hpp
src/libslic3r/SLA/ConcaveHull.cpp