Prusa Slicer: Slic3r::ConfigOptionIntsTempl< NULLABLE > Class Template Reference
Slic3r::ConfigOptionIntsTempl< NULLABLE > Class Template Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionIntsTempl ()
ConfigOptionIntsTempl (size_t n, int value)
ConfigOptionIntsTempl (std::initializer_list< int > il)
ConfigOptionIntsTempl (const std::vector< int > &v)
ConfigOptionIntsTempl (std::vector< int > &&v)
ConfigOptionType type () const override
ConfigOption * clone () const override
ConfigOptionIntsTempl & operator= (const ConfigOption *opt)
bool operator== (const ConfigOptionIntsTempl &rhs) const throw ()
bool operator< (const ConfigOptionIntsTempl &rhs) const throw ()
bool nullable () const override
bool is_nil () const override
bool is_nil (size_t idx) const override
std::string serialize () const override
std::vector< std::string > vserialize () const override
bool deserialize (const std::string &str, bool append=false) override
void set (const ConfigOption *rhs) override
void set (const std::vector< const ConfigOption * > &rhs) override
void set_at (const ConfigOption *rhs, size_t i, size_t j) override
const int & get_at (size_t i) const
int & get_at (size_t i)
void resize (size_t n, const ConfigOption *opt_default=nullptr) override
void clear () override
size_t size () const override
bool empty () const override
bool operator== (const ConfigOption &rhs) const override
bool operator== (const std::vector< int > &rhs) const throw ()
bool operator!= (const std::vector< int > &rhs) const throw ()
bool operator!= (const ConfigOption &rhs) const
size_t hash () const override throw ()
bool overriden_by (const ConfigOption *rhs) const override
bool apply_override (const ConfigOption *rhs) override
virtual int getInt () const
virtual double getFloat () const
virtual bool getBool () const
virtual void setInt (int)
bool is_scalar () const
bool is_vector () const
Static Public Member Functions
static ConfigOptionType static_type ()
static int nil_value ()
Public Attributes
std::vector< int > values
Protected Member Functions
ConfigOptionType scalar_type () const
Private Member Functions
void serialize_single_value (std::ostringstream &ss, const int v) const
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
template<bool NULLABLE>
class Slic3r::ConfigOptionIntsTempl< NULLABLE >
Constructor & Destructor Documentation
ConfigOptionIntsTempl() [1/5]
template<bool NULLABLE> Slic3r::ConfigOptionIntsTempl< NULLABLE >::ConfigOptionIntsTempl () inline
: ConfigOptionVector<int>() {}
Referenced by Slic3r::ConfigOptionIntsTempl< NULLABLE >::clone().
ConfigOptionIntsTempl() [2/5]
template<bool NULLABLE> Slic3r::ConfigOptionIntsTempl< NULLABLE >::ConfigOptionIntsTempl (size_t n, int value) inline explicit
: ConfigOptionVector<int>(n, value) {}
ConfigOptionIntsTempl() [3/5]
template<bool NULLABLE> Slic3r::ConfigOptionIntsTempl< NULLABLE >::ConfigOptionIntsTempl (std::initializer_list< int > il) inline explicit
: ConfigOptionVector<int>(std::move(il)) {}
ConfigOptionIntsTempl() [4/5]
template<bool NULLABLE> Slic3r::ConfigOptionIntsTempl< NULLABLE >::ConfigOptionIntsTempl (const std::vector< int > & v) inline explicit
: ConfigOptionVector<int>(v) {}
ConfigOptionIntsTempl() [5/5]
template<bool NULLABLE> Slic3r::ConfigOptionIntsTempl< NULLABLE >::ConfigOptionIntsTempl (std::vector< int > && v) inline explicit
: ConfigOptionVector<int>(std::move(v)) {}
Member Function Documentation
apply_override()
bool Slic3r::ConfigOptionVector< int >::apply_override (const ConfigOption * rhs) inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
      throw ConfigurationError("ConfigOptionVector.apply_override() applied to different types.");
    auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
    if (! rhs->nullable()) {
        // Overridding a non-nullable object with another non-nullable object.
        if (this->values != rhs_vec->values) {
          this->values = rhs_vec->values;
          return true;
        }
        return false;
      }
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      bool   modified = false;
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i]) {
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i)) {
          if (this->values.empty())
            this->values.resize(i + 1);
          else
            this->values.resize(i + 1, this->values.front());
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
        return modified;
    }
clear()
void Slic3r::ConfigOptionVector< int >::clear () inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ this->values.clear(); }
clone()
template<bool NULLABLE> ConfigOption * Slic3r::ConfigOptionIntsTempl< NULLABLE >::clone () const inline override virtual
Implements Slic3r::ConfigOption.
{ return new ConfigOptionIntsTempl(*this); }
References Slic3r::ConfigOptionIntsTempl< NULLABLE >::ConfigOptionIntsTempl().
deserialize()
template<bool NULLABLE> bool Slic3r::ConfigOptionIntsTempl< NULLABLE >::deserialize (const std::string & str, bool append = false) inline override virtual
Implements Slic3r::ConfigOption.
    {
        if (! append)
            this->values.clear();
        std::istringstream is(str);
        std::string item_str;
        while (std::getline(is, item_str, ',')) {
          boost::trim(item_str);
          if (item_str == "nil") {
            if (NULLABLE)
              this->values.push_back(nil_value());
            else
                    throw ConfigurationError("Deserializing nil into a non-nullable object");
          } else {
              std::istringstream iss(item_str);
              int value;
              iss >> value;
              this->values.push_back(value);
          }
        }
        return true;
    }
References Slic3r::append(), and Slic3r::ConfigOptionIntsTempl< NULLABLE >::nil_value().
empty()
bool Slic3r::ConfigOptionVector< int >::empty () const inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.empty(); }
get_at() [1/2]
int & Slic3r::ConfigOptionVector< int >::get_at (size_t i) inline inherited
{ return const_cast<T&>(std::as_const(*this).get_at(i)); }
get_at() [2/2]
const int & Slic3r::ConfigOptionVector< int >::get_at (size_t i) const inline inherited
    {
        assert(! this->values.empty());
        return (i < this->values.size()) ? this->values[i] : this->values.front();
    }
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
virtual int Slic3r::ConfigOption::getInt () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::getInt on a non-int ConfigOption"); }
Referenced by Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
hash()
size_t Slic3r::ConfigOptionVector< int >::hash () const throw () inline override virtual inherited
Implements Slic3r::ConfigOption.
{
        std::hash<T> hasher;
        size_t seed = 0;
        for (const auto &v : this->values)
            boost::hash_combine(seed, hasher(v));
        return seed;
    }
is_nil() [1/2]
template<bool NULLABLE> bool Slic3r::ConfigOptionIntsTempl< NULLABLE >::is_nil () const inline override virtual
Reimplemented from Slic3r::ConfigOption.
{ for (auto v : this->values) if (v != nil_value()) return false; return true; }
References Slic3r::ConfigOptionIntsTempl< NULLABLE >::nil_value(), and Slic3r::ConfigOptionVector< int >::values.
Referenced by Slic3r::OozePrevention::pre_toolchange().
is_nil() [2/2]
template<bool NULLABLE> bool Slic3r::ConfigOptionIntsTempl< NULLABLE >::is_nil (size_t idx) const inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
{ return values[idx < this->values.size() ? idx : 0] == nil_value(); }
References Slic3r::ConfigOptionIntsTempl< NULLABLE >::nil_value(), and Slic3r::ConfigOptionVector< int >::values.
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nil_value()
template<bool NULLABLE> static int Slic3r::ConfigOptionIntsTempl< NULLABLE >::nil_value () inline static
{ return std::numeric_limits<int>::max(); }
Referenced by Slic3r::GUI::SpinCtrl::BUILD(), Slic3r::ConfigOptionIntsTempl< NULLABLE >::deserialize(), Slic3r::PrintConfigDef::init_sla_params(), Slic3r::ConfigOptionIntsTempl< NULLABLE >::is_nil(), Slic3r::ConfigOptionIntsTempl< NULLABLE >::is_nil(), and Slic3r::ConfigOptionIntsTempl< NULLABLE >::serialize_single_value().
nullable()
template<bool NULLABLE> bool Slic3r::ConfigOptionIntsTempl< NULLABLE >::nullable () const inline override virtual
Reimplemented from Slic3r::ConfigOption.
{ return NULLABLE; }
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
bool Slic3r::ConfigOptionVector< int >::operator!= (const std::vector< int > & rhs) const throw () inline inherited
{ return this->values != rhs; }
operator<()
template<bool NULLABLE> bool Slic3r::ConfigOptionIntsTempl< NULLABLE >::operator< (const ConfigOptionIntsTempl< NULLABLE > & rhs) const throw () inline
{ return this->values <  rhs.values; }
operator=()
template<bool NULLABLE> ConfigOptionIntsTempl & Slic3r::ConfigOptionIntsTempl< NULLABLE >::operator= (const ConfigOption * opt) inline
{ this->set(opt); return *this; }
References Slic3r::ConfigOptionVector< int >::set().
operator==() [1/3]
bool Slic3r::ConfigOptionVector< int >::operator== (const ConfigOption & rhs) const inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionVector: Comparing incompatible types");
        assert(dynamic_cast<const ConfigOptionVector<T>*>(&rhs));
        return this->values == static_cast<const ConfigOptionVector<T>*>(&rhs)->values;
    }
operator==() [2/3]
template<bool NULLABLE> bool Slic3r::ConfigOptionIntsTempl< NULLABLE >::operator== (const ConfigOptionIntsTempl< NULLABLE > & rhs) const throw () inline
{ return this->values == rhs.values; }
operator==() [3/3]
bool Slic3r::ConfigOptionVector< int >::operator== (const std::vector< int > & rhs) const throw () inline inherited
{ return this->values == rhs; }
overriden_by()
bool Slic3r::ConfigOptionVector< int >::overriden_by (const ConfigOption * rhs) const inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector.overriden_by() applied to different types.");
      auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
      if (! rhs->nullable())
        // Overridding a non-nullable object with another non-nullable object.
        return this->values != rhs_vec->values;
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i])
          return true;
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i))
          return true;
      return false;
    }
resize()
void Slic3r::ConfigOptionVector< int >::resize (size_t n, const ConfigOption * opt_default = nullptr) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        assert(opt_default == nullptr || opt_default->is_vector());
//        assert(opt_default == nullptr || dynamic_cast<ConfigOptionVector<T>>(opt_default));
        assert(! this->values.empty() || opt_default != nullptr);
        if (n == 0)
            this->values.clear();
        else if (n < this->values.size())
            this->values.erase(this->values.begin() + n, this->values.end());
        else if (n > this->values.size()) {
            if (this->values.empty()) {
                if (opt_default == nullptr)
                    throw ConfigurationError("ConfigOptionVector::resize(): No default value provided.");
                if (opt_default->type() != this->type())
                    throw ConfigurationError("ConfigOptionVector::resize(): Extending with an incompatible type.");
                this->values.resize(n, static_cast<const ConfigOptionVector<T>*>(opt_default)->values.front());
            } else {
                // Resize by duplicating the last value.
                this->values.resize(n, this->values./*back*/front());
            }
        }
    }
scalar_type()
ConfigOptionType Slic3r::ConfigOptionVectorBase::scalar_type () const inline protected inherited
{ return static_cast<ConfigOptionType>(this->type() - coVectorType); }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::ConfigOptionVector< T >::set(), and Slic3r::ConfigOptionVector< T >::set_at().
serialize() [1/2]
template<bool NULLABLE> std::string Slic3r::ConfigOptionIntsTempl< NULLABLE >::serialize () const inline override virtual
Implements Slic3r::ConfigOption.
    {
        std::ostringstream ss;
        for (const int &v : this->values) {
            if (&v != &this->values.front())
              ss << ",";
            serialize_single_value(ss, v);
        }
        return ss.str();
    }
References Slic3r::ConfigOptionIntsTempl< NULLABLE >::serialize_single_value(), and Slic3r::ConfigOptionVector< int >::values.
serialize() [2/2]
template<bool NULLABLE> template<class Archive > void Slic3r::ConfigOptionIntsTempl< NULLABLE >::serialize (Archive & ar) inline private
{ ar(cereal::base_class<ConfigOptionVector<int>>(this)); }
serialize_single_value()
template<bool NULLABLE> void Slic3r::ConfigOptionIntsTempl< NULLABLE >::serialize_single_value (std::ostringstream & ss, const int v) const inline private
{
      if (v == nil_value()) {
            if (NULLABLE)
              ss << "nil";
            else
                    throw ConfigurationError("Serializing NaN");
          } else
            ss << v;
  }
References Slic3r::ConfigOptionIntsTempl< NULLABLE >::nil_value().
Referenced by Slic3r::ConfigOptionIntsTempl< NULLABLE >::serialize(), and Slic3r::ConfigOptionIntsTempl< NULLABLE >::vserialize().
set() [1/2]
void Slic3r::ConfigOptionVector< int >::set (const ConfigOption * rhs) inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector: Assigning an incompatible type");
        assert(dynamic_cast<const ConfigOptionVector<T>*>(rhs));
        this->values = static_cast<const ConfigOptionVector<T>*>(rhs)->values;
    }
set() [2/2]
void Slic3r::ConfigOptionVector< int >::set (const std::vector< const ConfigOption * > & rhs) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        this->values.clear();
        this->values.reserve(rhs.size());
        for (const ConfigOption *opt : rhs) {
            if (opt->type() == this->type()) {
                auto other = static_cast<const ConfigOptionVector<T>*>(opt);
                if (other->values.empty())
                    throw ConfigurationError("ConfigOptionVector::set(): Assigning from an empty vector");
                this->values.emplace_back(other->values.front());
            } else if (opt->type() == this->scalar_type())
                this->values.emplace_back(static_cast<const ConfigOptionSingle<T>*>(opt)->value);
            else
                throw ConfigurationError("ConfigOptionVector::set():: Assigning an incompatible type");
        }
    }
set_at()
void Slic3r::ConfigOptionVector< int >::set_at (const ConfigOption * rhs, size_t i, size_t j) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        // It is expected that the vector value has at least one value, which is the default, if not overwritten.
        assert(! this->values.empty());
        if (this->values.size() <= i) {
            // Resize this vector, fill in the new vector fields with the copy of the first field.
            T v = this->values.front();
            this->values.resize(i + 1, v);
        }
        if (rhs->type() == this->type()) {
            // Assign the first value of the rhs vector.
            auto other = static_cast<const ConfigOptionVector<T>*>(rhs);
            if (other->values.empty())
                throw ConfigurationError("ConfigOptionVector::set_at(): Assigning from an empty vector");
            this->values[i] = other->get_at(j);
        } else if (rhs->type() == this->scalar_type())
            this->values[i] = static_cast<const ConfigOptionSingle<T>*>(rhs)->value;
        else
            throw ConfigurationError("ConfigOptionVector::set_at(): Assigning an incompatible type");
    }
setInt()
virtual void Slic3r::ConfigOption::setInt (int) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::setInt on a non-int ConfigOption"); }
size()
size_t Slic3r::ConfigOptionVector< int >::size () const inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.size(); }
static_type()
template<bool NULLABLE> static ConfigOptionType Slic3r::ConfigOptionIntsTempl< NULLABLE >::static_type () inline static
{ return coInts; }
References Slic3r::coInts.
Referenced by Slic3r::ConfigOptionIntsTempl< NULLABLE >::type().
type()
template<bool NULLABLE> ConfigOptionType Slic3r::ConfigOptionIntsTempl< NULLABLE >::type () const inline override virtual
Implements Slic3r::ConfigOption.
{ return static_type(); }
References Slic3r::ConfigOptionIntsTempl< NULLABLE >::static_type().
vserialize()
template<bool NULLABLE> std::vector< std::string > Slic3r::ConfigOptionIntsTempl< NULLABLE >::vserialize () const inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
    {
        std::vector<std::string> vv;
        vv.reserve(this->values.size());
        for (const int v : this->values) {
            std::ostringstream ss;
          serialize_single_value(ss, v);
            vv.push_back(ss.str());
        }
        return vv;
    }
References Slic3r::ConfigOptionIntsTempl< NULLABLE >::serialize_single_value(), and Slic3r::ConfigOptionVector< int >::values.
Friends And Related Symbol Documentation
cereal::access
template<bool NULLABLE> friend class cereal::access friend
Member Data Documentation
values
std::vector<int > Slic3r::ConfigOptionVector< int >::values inherited
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp