Prusa Slicer: Slic3r::GUI::UIThreadWorker Class Reference
Slic3r::GUI::UIThreadWorker Class Reference
#include <src/slic3r/GUI/Jobs/UIThreadWorker.hpp>
Public Member Functions
UIThreadWorker (std::shared_ptr< ProgressIndicator > pri, const std::string &="")
UIThreadWorker ()=default
bool push (std::unique_ptr< Job > job) override
bool is_idle () const override
void cancel () override
void cancel_all () override
void process_events () override
bool wait_for_current_job (unsigned=0) override
bool wait_for_idle (unsigned=0) override
ProgressIndicator * get_pri ()
const ProgressIndicator * get_pri () const
Protected Member Functions
void update_status (int st, const std::string &msg="") override
bool was_canceled () const override
std::future< void > call_on_main_thread (std::function< void()> fn) override
Private Member Functions
void process_front ()
Private Attributes
std::queue< std::unique_ptr< Job >, std::deque< std::unique_ptr< Job > > > m_jobqueue
std::shared_ptr< ProgressIndicator > m_progress
bool m_running = false
bool m_canceled = false
Detailed Description
Constructor & Destructor Documentation
UIThreadWorker() [1/2]
Slic3r::GUI::UIThreadWorker::UIThreadWorker (std::shared_ptr< ProgressIndicator > pri, const std::string & = "") inline explicit
        : m_progress{pri}
    {
        if (m_progress)
            m_progress->set_cancel_callback([this]() { cancel(); });
    }
References cancel(), and m_progress.
UIThreadWorker() [2/2]
Slic3r::GUI::UIThreadWorker::UIThreadWorker () default
Member Function Documentation
call_on_main_thread()
std::future< void > Slic3r::GUI::UIThreadWorker::call_on_main_thread (std::function< void()> fn) inline override protected virtual
Implements Slic3r::GUI::Job::Ctl.
    {
        std::future<void> ftr = std::async(std::launch::deferred, [fn]{ fn(); });
        // So, it seems that the destructor of std::future will not call the
        // packaged function. The future needs to be accessed at least ones
        // or waited upon. Calling wait() instead of get() will keep the
        // returned future's state valid.
        ftr.wait();
        return ftr;
    }
cancel()
void Slic3r::GUI::UIThreadWorker::cancel () inline override virtual
Implements Slic3r::GUI::Worker.
{ m_canceled = true; }
References m_canceled.
Referenced by UIThreadWorker().
cancel_all()
void Slic3r::GUI::UIThreadWorker::cancel_all () inline override virtual
Implements Slic3r::GUI::Worker.
    {
        m_canceled = true;
        process_front();
        while (!m_jobqueue.empty())
            m_jobqueue.pop();
    }
References m_canceled, m_jobqueue, and process_front().
get_pri() [1/2]
ProgressIndicator * Slic3r::GUI::UIThreadWorker::get_pri () inline
{ return m_progress.get(); }
References m_progress.
get_pri() [2/2]
const ProgressIndicator * Slic3r::GUI::UIThreadWorker::get_pri () const inline
{ return m_progress.get(); }
References m_progress.
is_idle()
bool Slic3r::GUI::UIThreadWorker::is_idle () const inline override virtual
Implements Slic3r::GUI::Worker.
{ return !m_running && m_jobqueue.empty(); }
References m_jobqueue, and m_running.
process_events()
void Slic3r::GUI::UIThreadWorker::process_events () inline override virtual
Implements Slic3r::GUI::Worker.
{
        while (!m_jobqueue.empty())
            process_front();
    }
References m_jobqueue, and process_front().
Referenced by Slic3r::GUI::Plater::cut(), and wait_for_idle().
process_front()
void Slic3r::GUI::UIThreadWorker::process_front () inline private
    {
        std::unique_ptr<Job> job;
        if (!m_jobqueue.empty()) {
            job = std::move(m_jobqueue.front());
            m_jobqueue.pop();
        }
        if (job) {
            std::exception_ptr eptr;
            m_running = true;
            try {
                job->process(*this);
            } catch (...) {
                eptr= std::current_exception();
            }
            job->finalize(m_canceled, eptr);
            // Unhandled exceptions are rethrown without mercy.
            if (eptr)
                std::rethrow_exception(eptr);
            m_running = false;
            m_canceled = false;
        }
    }
References m_canceled, m_jobqueue, and m_running.
Referenced by cancel_all(), process_events(), and wait_for_current_job().
push()
bool Slic3r::GUI::UIThreadWorker::push (std::unique_ptr< Job > job) inline override virtual
Implements Slic3r::GUI::Worker.
    {
        m_canceled = false;
        if (job)
            m_jobqueue.push(std::move(job));
        return bool(job);
    }
References m_canceled, and m_jobqueue.
update_status()
void Slic3r::GUI::UIThreadWorker::update_status (int st, const std::string & msg = "") inline override protected virtual
Implements Slic3r::GUI::Job::Ctl.
    {
        if (m_progress) {
            m_progress->set_progress(st);
            m_progress->set_status_text(msg.c_str());
        }
    }
References m_progress.
wait_for_current_job()
bool Slic3r::GUI::UIThreadWorker::wait_for_current_job (unsigned = 0) inline override virtual
Implements Slic3r::GUI::Worker.
{
        process_front();
        return true;
    }
References process_front().
wait_for_idle()
bool Slic3r::GUI::UIThreadWorker::wait_for_idle (unsigned = 0) inline override virtual
Implements Slic3r::GUI::Worker.
{
        process_events();
        return true;
    }
References process_events().
was_canceled()
bool Slic3r::GUI::UIThreadWorker::was_canceled () const inline override protected virtual
Implements Slic3r::GUI::Job::Ctl.
{ return m_canceled; }
References m_canceled.
Member Data Documentation
m_canceled
bool Slic3r::GUI::UIThreadWorker::m_canceled = false private
Referenced by cancel(), cancel_all(), process_front(), push(), and was_canceled().
m_jobqueue
std::queue<std::unique_ptr<Job>, std::deque<std::unique_ptr<Job> > > Slic3r::GUI::UIThreadWorker::m_jobqueue private
Referenced by cancel_all(), is_idle(), process_events(), process_front(), and push().
m_progress
std::shared_ptr<ProgressIndicator> Slic3r::GUI::UIThreadWorker::m_progress private
Referenced by UIThreadWorker(), get_pri(), get_pri(), and update_status().
m_running
bool Slic3r::GUI::UIThreadWorker::m_running = false private
Referenced by is_idle(), and process_front().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Jobs/UIThreadWorker.hpp