Prusa Slicer: Slic3r::SupportSpotsGenerator::SupportGridFilter Struct Reference
Slic3r::SupportSpotsGenerator::SupportGridFilter Struct Reference
Public Member Functions
SupportGridFilter (const PrintObject *po, float voxel_size)
Vec3i to_cell_coords (const Vec3f &position) const
size_t to_cell_index (const Vec3i &cell_coords) const
Vec3f get_cell_center (const Vec3i &cell_coords) const
void take_position (const Vec3f &position)
bool position_taken (const Vec3f &position) const
Private Attributes
Vec3f cell_size
Vec3f origin
Vec3f size
Vec3i cell_count
std::unordered_set< size_t > taken_cells {}
Detailed Description
Constructor & Destructor Documentation
SupportGridFilter()
Slic3r::SupportSpotsGenerator::SupportGridFilter::SupportGridFilter (const PrintObject * po, float voxel_size) inline
    {
        cell_size = Vec3f(voxel_size, voxel_size, voxel_size);
        Vec2crd size_half = po->size().head<2>().cwiseQuotient(Vec2crd(2, 2)) + Vec2crd::Ones();
        Vec3f   min       = unscale(Vec3crd(-size_half.x(), -size_half.y(), 0)).cast<float>() - cell_size;
        Vec3f   max       = unscale(Vec3crd(size_half.x(), size_half.y(), po->height())).cast<float>() + cell_size;
        origin     = min;
        size       = max - min;
        cell_count = size.cwiseQuotient(cell_size).cast<int>() + Vec3i::Ones();
    }
References cell_count, cell_size, cwiseQuotient(), Slic3r::PrintObject::height(), origin, Slic3r::PrintObject::size(), size, and Slic3r::unscale().
Member Function Documentation
get_cell_center()
Vec3f Slic3r::SupportSpotsGenerator::SupportGridFilter::get_cell_center (const Vec3i & cell_coords) const inline
    {
        return origin + cell_coords.cast<float>().cwiseProduct(this->cell_size) + this->cell_size.cwiseQuotient(Vec3f(2.0f, 2.0f, 2.0f));
    }
References origin.
position_taken()
bool Slic3r::SupportSpotsGenerator::SupportGridFilter::position_taken (const Vec3f & position) const inline
    {
        return taken_cells.find(to_cell_index(to_cell_coords(position))) != taken_cells.end();
    }
References taken_cells, to_cell_coords(), and to_cell_index().
take_position()
void Slic3r::SupportSpotsGenerator::SupportGridFilter::take_position (const Vec3f & position) inline
{ taken_cells.insert(to_cell_index(to_cell_coords(position))); }
References taken_cells, to_cell_coords(), and to_cell_index().
to_cell_coords()
Vec3i Slic3r::SupportSpotsGenerator::SupportGridFilter::to_cell_coords (const Vec3f & position) const inline
    {
        Vec3i cell_coords = (position - this->origin).cwiseQuotient(this->cell_size).cast<int>();
        return cell_coords;
    }
References cwiseQuotient(), and origin.
Referenced by position_taken(), and take_position().
to_cell_index()
size_t Slic3r::SupportSpotsGenerator::SupportGridFilter::to_cell_index (const Vec3i & cell_coords) const inline
    {
#ifdef DETAILED_DEBUG_LOGS
        assert(cell_coords.x() >= 0);
        assert(cell_coords.x() < cell_count.x());
        assert(cell_coords.y() >= 0);
        assert(cell_coords.y() < cell_count.y());
        assert(cell_coords.z() >= 0);
        assert(cell_coords.z() < cell_count.z());
#endif
        return cell_coords.z() * cell_count.x() * cell_count.y() + cell_coords.y() * cell_count.x() + cell_coords.x();
    }
References cell_count.
Referenced by position_taken(), and take_position().
Member Data Documentation
cell_count
Vec3i Slic3r::SupportSpotsGenerator::SupportGridFilter::cell_count private
Referenced by SupportGridFilter(), and to_cell_index().
cell_size
Vec3f Slic3r::SupportSpotsGenerator::SupportGridFilter::cell_size private
Referenced by SupportGridFilter().
origin
Vec3f Slic3r::SupportSpotsGenerator::SupportGridFilter::origin private
Referenced by SupportGridFilter(), get_cell_center(), and to_cell_coords().
size
Vec3f Slic3r::SupportSpotsGenerator::SupportGridFilter::size private
Referenced by SupportGridFilter().
taken_cells
std::unordered_set<size_t> Slic3r::SupportSpotsGenerator::SupportGridFilter::taken_cells {} private
Referenced by position_taken(), and take_position().
The documentation for this struct was generated from the following file:
src/libslic3r/SupportSpotsGenerator.cpp