Prusa Slicer: Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > > Class Template Reference
Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > > Class Template Reference
#include <src/libslic3r/Optimize/NLoptOptimizer.hpp>
Public Member Functions
Optimizer & to_max ()
Optimizer & to_min ()
template<class Func , size_t N, class... EqFns, class... IneqFns>
Result< N > optimize (Func &&func, const Input< N > &initvals, const Bounds< N > &bounds, const std::tuple< EqFns... > &eq_constraints={}, const std::tuple< IneqFns... > &ineq_constraint={})
Optimizer (StopCriteria stopcr={})
Optimizer & set_criteria (const StopCriteria &cr)
const StopCriteria & get_criteria () const
void seed (long s)
void set_loc_criteria (const StopCriteria &cr)
const StopCriteria & get_loc_criteria () const noexcept
Private Attributes
detail::NLoptOpt< M > m_opt
Detailed Description
template<class M>
class Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >
Constructor & Destructor Documentation
Optimizer()
template<class M > Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::Optimizer (StopCriteria stopcr = {}) inline explicit
{}) : m_opt(stopcr) {}
Member Function Documentation
get_criteria()
template<class M > const StopCriteria & Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::get_criteria () const inline
{ return m_opt.get_criteria(); }
References Slic3r::opt::detail::NLoptOpt< M, class >::get_criteria().
get_loc_criteria()
template<class M > const StopCriteria & Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::get_loc_criteria () const inline noexcept
{ return m_opt.get_loc_criteria(); }
References Slic3r::opt::detail::NLoptOpt< M, class >::get_loc_criteria().
optimize()
template<class M > template<class Func , size_t N, class... EqFns, class... IneqFns> Result< N > Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::optimize (Func && func, const Input< N > & initvals, const Bounds< N > & bounds, const std::tuple< EqFns... > & eq_constraints = {}, const std::tuple< IneqFns... > & ineq_constraint = {}) inline
                                                                  {},
                       const std::tuple<IneqFns...> &ineq_constraint = {})
    {
        static_assert(std::tuple_size_v<std::tuple<EqFns...>> == 0
                          || SupportsEqualities<M>,
                      "Equality constraints are not supported.");
        static_assert(std::tuple_size_v<std::tuple<IneqFns...>> == 0
                          || SupportsInequalities<M>,
                      "Inequality constraints are not supported.");
        return m_opt.optimize(std::forward<Func>(func), initvals, bounds,
                              eq_constraints,
                              ineq_constraint);
    }
seed()
template<class M > void Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::seed (long s) inline
{ m_opt.seed(s); }
References Slic3r::opt::detail::NLoptOpt< M, class >::seed().
set_criteria()
template<class M > Optimizer & Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::set_criteria (const StopCriteria & cr) inline
    {
        m_opt.set_criteria(cr); return *this;
    }
References Slic3r::opt::detail::NLoptOpt< M, class >::set_criteria().
set_loc_criteria()
template<class M > void Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::set_loc_criteria (const StopCriteria & cr) inline
{ m_opt.set_loc_criteria(cr); }
References Slic3r::opt::detail::NLoptOpt< M, class >::set_loc_criteria().
to_max()
template<class M > Optimizer & Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::to_max () inline
{ m_opt.set_dir(detail::OptDir::MAX); return *this; }
References Slic3r::opt::detail::MAX, and Slic3r::opt::detail::NLoptOpt< M, class >::set_dir().
to_min()
template<class M > Optimizer & Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::to_min () inline
{ m_opt.set_dir(detail::OptDir::MIN); return *this; }
References Slic3r::opt::detail::MIN, and Slic3r::opt::detail::NLoptOpt< M, class >::set_dir().
Member Data Documentation
m_opt
template<class M > detail::NLoptOpt<M> Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::m_opt private
The documentation for this class was generated from the following file:
src/libslic3r/Optimize/NLoptOptimizer.hpp