Prusa Slicer: src/glu-libtess/src/sweep.h File Reference
sweep.h File Reference
#include "mesh.h"
#include "dict.h"
Classes
struct ActiveRegion
Macros
#define RegionBelow(r) ((ActiveRegion *) dictKey(dictPred((r)->nodeUp)))
#define RegionAbove(r) ((ActiveRegion *) dictKey(dictSucc((r)->nodeUp)))
Functions
int __gl_computeInterior (GLUtesselator *tess)
Class Documentation
ActiveRegion
struct ActiveRegion
Class Members
GLboolean dirty
GLUhalfEdge * eUp
GLboolean fixUpperEdge
GLboolean inside
DictNode * nodeUp
GLboolean sentinel
int windingNumber
Macro Definition Documentation
RegionAbove
#define RegionAbove (r) ((ActiveRegion *) dictKey(dictSucc((r)->nodeUp)))
RegionBelow
#define RegionBelow (r) ((ActiveRegion *) dictKey(dictPred((r)->nodeUp)))
Function Documentation
__gl_computeInterior()
int __gl_computeInterior (GLUtesselator * tess)
{
  GLUvertex *v, *vNext;
  tess->fatalError = FALSE;
  /* Each vertex defines an event for our sweep line.  Start by inserting
   * all the vertices in a priority queue.  Events are processed in
   * lexicographic order, ie.
   *
   *  e1 < e2  iff  e1.x < e2.x || (e1.x == e2.x && e1.y < e2.y)
   */
  RemoveDegenerateEdges( tess );
  if ( !InitPriorityQ( tess ) ) return 0; /* if error */
  InitEdgeDict( tess );
  /* __gl_pqSortExtractMin */
  while( (v = (GLUvertex *)pqExtractMin( tess->pq )) != NULL ) {
    for( ;; ) {
      vNext = (GLUvertex *)pqMinimum( tess->pq ); /* __gl_pqSortMinimum */
      if( vNext == NULL || ! VertEq( vNext, v )) break;
      /* Merge together all vertices at exactly the same location.
       * This is more efficient than processing them one at a time,
       * simplifies the code (see ConnectLeftDegenerate), and is also
       * important for correct handling of certain degenerate cases.
       * For example, suppose there are two identical edges A and B
       * that belong to different contours (so without this code they would
       * be processed by separate sweep events).  Suppose another edge C
       * crosses A and B from above.  When A is processed, we split it
       * at its intersection point with C.  However this also splits C,
       * so when we insert B we may compute a slightly different
       * intersection point.  This might leave two edges with a small
       * gap between them.  This kind of error is especially obvious
       * when using boundary extraction (GLU_TESS_BOUNDARY_ONLY).
       */
      vNext = (GLUvertex *)pqExtractMin( tess->pq ); /* __gl_pqSortExtractMin*/
      SpliceMergeVertices( tess, v->anEdge, vNext->anEdge );
    }
    SweepEvent( tess, v );
  }
  /* Set tess->event for debugging purposes */
  /* __GL_DICTLISTKEY */ /* __GL_DICTLISTMIN */
  tess->event = ((ActiveRegion *) dictKey( dictMin( tess->dict )))->eUp->Org;
  DebugEvent( tess );
  DoneEdgeDict( tess );
  DonePriorityQ( tess );
  if ( !RemoveDegenerateFaces( tess->mesh ) ) return 0;
  __gl_meshCheckMesh( tess->mesh );
  return 1;
}
References __gl_meshCheckMesh(), GLUvertex::anEdge, DebugEvent, GLUtesselator::dict, dictKey, dictMin, DoneEdgeDict(), DonePriorityQ(), GLUtesselator::event, FALSE, GLUtesselator::fatalError, InitEdgeDict(), InitPriorityQ(), GLUtesselator::mesh, GLUtesselator::pq, pqExtractMin, pqMinimum, RemoveDegenerateEdges(), RemoveDegenerateFaces(), SpliceMergeVertices(), SweepEvent(), and VertEq.
Referenced by gluTessEndPolygon().