Prusa Slicer: Slic3r::enum_bitmask< option_type, typename > Class Template Reference
Slic3r::enum_bitmask< option_type, typename > Class Template Reference
#include <src/libslic3r/enum_bitmask.hpp>
Public Member Functions
constexpr enum_bitmask ()
constexpr enum_bitmask (option_type o)
constexpr enum_bitmask operator| (option_type t) const
constexpr enum_bitmask operator| (enum_bitmask< option_type > t) const
constexpr void operator|= (option_type t)
constexpr void operator|= (enum_bitmask< option_type > t)
constexpr bool operator& (option_type t) const
constexpr bool has (option_type t) const
constexpr bool operator== (const enum_bitmask r) const
constexpr bool operator!= (const enum_bitmask r) const
constexpr bool lower (const enum_bitmask r) const
Private Types
using underlying_type = typename std::underlying_type< option_type >::type
Private Member Functions
constexpr enum_bitmask (underlying_type o)
Static Private Member Functions
static constexpr underlying_type mask_value (option_type o)
Private Attributes
underlying_type m_bits = 0
Detailed Description
template<class option_type, typename = typename std::enable_if<std::is_enum<option_type>::value>::type>
class Slic3r::enum_bitmask< option_type, typename >
Member Typedef Documentation
underlying_type
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> using Slic3r::enum_bitmask< option_type, typename >::underlying_type = typename std::underlying_type<option_type>::type private
Constructor & Destructor Documentation
enum_bitmask() [1/3]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr Slic3r::enum_bitmask< option_type, typename >::enum_bitmask (underlying_type o) inline explicit constexpr private
: m_bits(o) {}
enum_bitmask() [2/3]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr Slic3r::enum_bitmask< option_type, typename >::enum_bitmask () inline constexpr
: m_bits(0) {}
Referenced by Slic3r::enum_bitmask< option_type, typename >::operator|(), Slic3r::enum_bitmask< option_type, typename >::operator|(), Slic3r::enum_bitmask< option_type, typename >::operator|=(), and Slic3r::enum_bitmask< option_type, typename >::operator|=().
enum_bitmask() [3/3]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr Slic3r::enum_bitmask< option_type, typename >::enum_bitmask (option_type o) inline constexpr
: m_bits(mask_value(o)) {}
Member Function Documentation
has()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::has (option_type t) const inline constexpr
{ return m_bits & mask_value(t); }
References Slic3r::enum_bitmask< option_type, typename >::m_bits, and Slic3r::enum_bitmask< option_type, typename >::mask_value().
Referenced by Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::ModelObject::cut(), Slic3r::ExtrusionRole::is_bridge(), Slic3r::ExtrusionRole::is_external(), Slic3r::ExtrusionRole::is_infill(), Slic3r::ExtrusionRole::is_mixed(), Slic3r::ExtrusionRole::is_perimeter(), Slic3r::ExtrusionRole::is_solid_infill(), Slic3r::ExtrusionRole::is_support(), Slic3r::PresetBundle::load_configbundle(), Slic3r::ModelObject::process_connector_cut(), Slic3r::ModelObject::process_modifier_cut(), Slic3r::ModelObject::process_solid_part_cut(), Slic3r::ModelObject::process_volume_cut(), and Slic3r::GUI::update_object_cut_id().
lower()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::lower (const enum_bitmask< option_type, typename > r) const inline constexpr
{ return m_bits < r.m_bits; }
References Slic3r::enum_bitmask< option_type, typename >::m_bits.
Referenced by Slic3r::SurfaceFillParams::operator<().
mask_value()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> static constexpr underlying_type Slic3r::enum_bitmask< option_type, typename >::mask_value (option_type o) inline static constexpr private
{ return 1 << static_cast<underlying_type>(o); }
Referenced by Slic3r::enum_bitmask< option_type, typename >::has(), Slic3r::enum_bitmask< option_type, typename >::operator&(), Slic3r::enum_bitmask< option_type, typename >::operator|(), and Slic3r::enum_bitmask< option_type, typename >::operator|=().
operator!=()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::operator!= (const enum_bitmask< option_type, typename > r) const inline constexpr
{ return m_bits != r.m_bits; }
References Slic3r::enum_bitmask< option_type, typename >::m_bits.
operator&()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::operator& (option_type t) const inline constexpr
{ return m_bits & mask_value(t); }
References Slic3r::enum_bitmask< option_type, typename >::m_bits, and Slic3r::enum_bitmask< option_type, typename >::mask_value().
operator==()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::operator== (const enum_bitmask< option_type, typename > r) const inline constexpr
{ return m_bits == r.m_bits; }
References Slic3r::enum_bitmask< option_type, typename >::m_bits.
operator|() [1/2]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr enum_bitmask Slic3r::enum_bitmask< option_type, typename >::operator| (enum_bitmask< option_type > t) const inline constexpr
{ return enum_bitmask(m_bits | t.m_bits); }
References Slic3r::enum_bitmask< option_type, typename >::enum_bitmask(), and Slic3r::enum_bitmask< option_type, typename >::m_bits.
operator|() [2/2]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr enum_bitmask Slic3r::enum_bitmask< option_type, typename >::operator| (option_type t) const inline constexpr
{ return enum_bitmask(m_bits | mask_value(t)); }
References Slic3r::enum_bitmask< option_type, typename >::enum_bitmask(), Slic3r::enum_bitmask< option_type, typename >::m_bits, and Slic3r::enum_bitmask< option_type, typename >::mask_value().
operator|=() [1/2]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr void Slic3r::enum_bitmask< option_type, typename >::operator|= (enum_bitmask< option_type > t) inline constexpr
{ m_bits = enum_bitmask(m_bits | t.m_bits); }
References Slic3r::enum_bitmask< option_type, typename >::enum_bitmask(), and Slic3r::enum_bitmask< option_type, typename >::m_bits.
operator|=() [2/2]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr void Slic3r::enum_bitmask< option_type, typename >::operator|= (option_type t) inline constexpr
{ m_bits = enum_bitmask(m_bits | mask_value(t)); }
References Slic3r::enum_bitmask< option_type, typename >::enum_bitmask(), Slic3r::enum_bitmask< option_type, typename >::m_bits, and Slic3r::enum_bitmask< option_type, typename >::mask_value().
Member Data Documentation
m_bits
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> underlying_type Slic3r::enum_bitmask< option_type, typename >::m_bits = 0 private
Referenced by Slic3r::enum_bitmask< option_type, typename >::has(), Slic3r::enum_bitmask< option_type, typename >::lower(), Slic3r::enum_bitmask< option_type, typename >::operator!=(), Slic3r::enum_bitmask< option_type, typename >::operator&(), Slic3r::enum_bitmask< option_type, typename >::operator==(), Slic3r::enum_bitmask< option_type, typename >::operator|(), Slic3r::enum_bitmask< option_type, typename >::operator|(), Slic3r::enum_bitmask< option_type, typename >::operator|=(), and Slic3r::enum_bitmask< option_type, typename >::operator|=().
The documentation for this class was generated from the following file:
src/libslic3r/enum_bitmask.hpp