Prusa Slicer: Slic3r::SupportMaterialInternal Namespace Reference
Slic3r::SupportMaterialInternal Namespace Reference
Functions
static bool has_bridging_perimeters (const ExtrusionLoop &loop)
static bool has_bridging_perimeters (const ExtrusionEntityCollection &perimeters)
static bool has_bridging_fills (const ExtrusionEntityCollection &fills)
static bool has_bridging_extrusions (const Layer &layer)
static void collect_bridging_perimeter_areas (const ExtrusionLoop &loop, const float expansion_scaled, Polygons &out)
static void collect_bridging_perimeter_areas (const ExtrusionEntityCollection &perimeters, const float expansion_scaled, Polygons &out)
Function Documentation
collect_bridging_perimeter_areas() [1/2]
static void Slic3r::SupportMaterialInternal::collect_bridging_perimeter_areas (const ExtrusionEntityCollection & perimeters, const float expansion_scaled, Polygons & out) static
    {
        for (const ExtrusionEntity *ee : perimeters.entities) {
            if (ee->is_collection()) {
                for (const ExtrusionEntity *ee2 : static_cast<const ExtrusionEntityCollection*>(ee)->entities) {
                    assert(! ee2->is_collection());
                    if (ee2->is_loop())
                        collect_bridging_perimeter_areas(*static_cast<const ExtrusionLoop*>(ee2), expansion_scaled, out);
                }
            } else if (ee->is_loop())
                collect_bridging_perimeter_areas(*static_cast<const ExtrusionLoop*>(ee), expansion_scaled, out);
        }
    }
References collect_bridging_perimeter_areas(), and Slic3r::ExtrusionEntityCollection::entities.
collect_bridging_perimeter_areas() [2/2]
static void Slic3r::SupportMaterialInternal::collect_bridging_perimeter_areas (const ExtrusionLoop & loop, const float expansion_scaled, Polygons & out) inline static
    {
        assert(expansion_scaled >= 0.f);
        for (const ExtrusionPath &ep : loop.paths)
            if (ep.role() == ExtrusionRole::OverhangPerimeter && ! ep.polyline.empty()) {
                float exp = 0.5f * (float)scale_(ep.width) + expansion_scaled;
                if (ep.is_closed()) {
                    if (ep.size() >= 3) {
                        // This is a complete loop.
                        // Add the outer contour first.
                        Polygon poly;
                        poly.points = ep.polyline.points;
                        poly.points.pop_back();
                        if (poly.area() < 0)
                            poly.reverse();
                        polygons_append(out, offset(poly, exp, SUPPORT_SURFACES_OFFSET_PARAMETERS));
                        Polygons holes = offset(poly, - exp, SUPPORT_SURFACES_OFFSET_PARAMETERS);
                        polygons_reverse(holes);
                        polygons_append(out, holes);
                    }
                } else if (ep.size() >= 2) {
                    // Offset the polyline.
                    polygons_append(out, offset(ep.polyline, exp, SUPPORT_SURFACES_OFFSET_PARAMETERS));
                }
            }
    }
References Slic3r::Polygon::area(), exp(), Slic3r::holes(), Slic3r::offset(), Slic3r::ExtrusionRole::OverhangPerimeter, Slic3r::MultiPoint::points, Slic3r::polygons_append(), Slic3r::polygons_reverse(), Slic3r::MultiPoint::reverse(), scale_, and SUPPORT_SURFACES_OFFSET_PARAMETERS.
Referenced by collect_bridging_perimeter_areas().
has_bridging_extrusions()
static bool Slic3r::SupportMaterialInternal::has_bridging_extrusions (const Layer & layer) static
    {
        for (const LayerRegion *region : layer.regions()) {
            if (SupportMaterialInternal::has_bridging_perimeters(region->perimeters()))
                return true;
            if (region->fill_surfaces().has(stBottomBridge) && has_bridging_fills(region->fills()))
                return true;
        }
        return false;
    }
References has_bridging_fills(), has_bridging_perimeters(), Slic3r::Layer::regions(), and Slic3r::stBottomBridge.
has_bridging_fills()
static bool Slic3r::SupportMaterialInternal::has_bridging_fills (const ExtrusionEntityCollection & fills) static
    {
        for (const ExtrusionEntity *ee : fills.entities) {
            assert(ee->is_collection());
            for (const ExtrusionEntity *ee2 : static_cast<const ExtrusionEntityCollection*>(ee)->entities) {
                assert(! ee2->is_collection());
                assert(! ee2->is_loop());
                if (ee2->role() == ExtrusionRole::BridgeInfill)
                    return true;
            }
        }
        return false;
    }
References Slic3r::ExtrusionRole::BridgeInfill, and Slic3r::ExtrusionEntityCollection::entities.
Referenced by has_bridging_extrusions().
has_bridging_perimeters() [1/2]
static bool Slic3r::SupportMaterialInternal::has_bridging_perimeters (const ExtrusionEntityCollection & perimeters) static
    {
        for (const ExtrusionEntity *ee : perimeters.entities) {
            if (ee->is_collection()) {
                for (const ExtrusionEntity *ee2 : static_cast<const ExtrusionEntityCollection*>(ee)->entities) {
                    assert(! ee2->is_collection());
                    if (ee2->is_loop())
                        if (has_bridging_perimeters(*static_cast<const ExtrusionLoop*>(ee2)))
                            return true;
                }
            } else if (ee->is_loop() && has_bridging_perimeters(*static_cast<const ExtrusionLoop*>(ee)))
                return true;
        }
        return false;
    }
References Slic3r::ExtrusionEntityCollection::entities, and has_bridging_perimeters().
has_bridging_perimeters() [2/2]
static bool Slic3r::SupportMaterialInternal::has_bridging_perimeters (const ExtrusionLoop & loop) inline static
    {
        for (const ExtrusionPath &ep : loop.paths)
            if (ep.role() == ExtrusionRole::OverhangPerimeter && ! ep.polyline.empty())
                return int(ep.size()) >= (ep.is_closed() ? 3 : 2);
        return false;
    }
References Slic3r::ExtrusionRole::OverhangPerimeter.
Referenced by has_bridging_extrusions(), and has_bridging_perimeters().