Prusa Slicer: libnest2d::GeometryException Class Reference
libnest2d::GeometryException Class Reference
#include <src/libnest2d/include/libnest2d/common.hpp>
Public Member Functions
GeometryException (GeomErr code)
GeomErr errcode () const
const char * what () const BP2D_NOEXCEPT override
Private Member Functions
virtual const std::string & errorstr (GeomErr errcode) const BP2D_NOEXCEPT
Private Attributes
GeomErr errcode_
Detailed Description
Constructor & Destructor Documentation
GeometryException()
libnest2d::GeometryException::GeometryException (GeomErr code) inline
: errcode_(code) {}
Member Function Documentation
errcode()
GeomErr libnest2d::GeometryException::errcode () const inline
{ return errcode_; }
References errcode_.
Referenced by errorstr().
errorstr()
virtual const std::string & libnest2d::GeometryException::errorstr (GeomErr errcode) const inline private virtual
{
        return ERROR_STR[static_cast<std::size_t>(errcode)];
    }
References errcode(), and libnest2d::ERROR_STR.
Referenced by what().
what()
const char * libnest2d::GeometryException::what () const inline override
{
        return errorstr(errcode_).c_str();
    }
References errcode_, and errorstr().
Member Data Documentation
errcode_
GeomErr libnest2d::GeometryException::errcode_ private
Referenced by errcode(), and what().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/common.hpp