Prusa Slicer: Eigen::TransposeImpl< MatrixType, Sparse > Class Template Reference
Eigen::TransposeImpl< MatrixType, Sparse > Class Template Reference
#include <src/eigen/Eigen/src/SparseCore/SparseTranspose.h>
Public Types
enum
typedef internal::traits< Transpose< MatrixType > >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Transpose< MatrixType > >::StorageKind StorageKind
typedef internal::traits< Transpose< MatrixType > >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typenameinternal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< constDerived > >, Transpose< constDerived > >::type AdjointReturnType
typedef Transpose< Transpose< MatrixType > > TransposeReturnType
typedef internal::add_const< Transpose< constDerived > >::type ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional< _HasDirectAccess, constScalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef Block< Transpose< MatrixType >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > InnerVectorReturnType
typedef Block< const Transpose< MatrixType >, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > ConstInnerVectorReturnType
typedef Block< Transpose< MatrixType >, Dynamic, Dynamic, true > InnerVectorsReturnType
typedef Block< const Transpose< MatrixType >, Dynamic, Dynamic, true > ConstInnerVectorsReturnType
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
const Transpose< MatrixType > & derived () const
Transpose< MatrixType > & derived ()
Transpose< MatrixType > & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Transpose< MatrixType > & markAsRValue ()
Transpose< MatrixType > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator+= (const DiagonalBase< OtherDerived > &other)
Transpose< MatrixType > & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Transpose< MatrixType > & operator+= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator-= (const DiagonalBase< OtherDerived > &other)
Transpose< MatrixType > & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Transpose< MatrixType > & operator-= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator*= (const Scalar &other)
Transpose< MatrixType > & operator*= (const SparseMatrixBase< OtherDerived > &other)
Transpose< MatrixType > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SparseMatrixBase< Transpose< MatrixType > >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< Transpose< MatrixType >, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< Transpose< MatrixType >, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< Transpose< MatrixType >, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Transpose< MatrixType >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const Transpose< MatrixType >, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
SparseMatrixBase< Transpose< MatrixType > >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SparseMatrixBase< Transpose< MatrixType > >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
internal::traits< Transpose< MatrixType > >::Scalar dot (const MatrixBase< OtherDerived > &other) const
internal::traits< Transpose< MatrixType > >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
InnerVectorReturnType innerVector (Index outer)
const ConstInnerVectorReturnType innerVector (Index outer) const
InnerVectorsReturnType innerVectors (Index outerStart, Index outerSize)
const ConstInnerVectorsReturnType innerVectors (Index outerStart, Index outerSize) const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Transpose< MatrixType > >::type eval () const
Scalar sum () const
const SparseView< Transpose< MatrixType > > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Types
typedef internal::SparseTransposeImpl< MatrixType > Base
Protected Member Functions
Transpose< MatrixType > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions
static StorageIndex convert_index (const Index idx)
Protected Attributes
bool m_isRValue
Private Member Functions
void evalTo (Dest &) const
Detailed Description
template<typename MatrixType>
class Eigen::TransposeImpl< MatrixType, Sparse >
Member Typedef Documentation
AdjointReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,Eigen::Transpose<constDerived>>,Transpose<constDerived>>::type Eigen::SparseMatrixBase< Transpose< MatrixType > >::AdjointReturnType inherited
Base
template<typename MatrixType > typedef internal::SparseTransposeImpl<MatrixType> Eigen::TransposeImpl< MatrixType, Sparse >::Base protected
CoeffReturnType
typedef internal::conditional<_HasDirectAccess,constScalar&,Scalar>::type Eigen::SparseMatrixBase< Transpose< MatrixType > >::CoeffReturnType inherited
ConstantReturnType
typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,Matrix<Scalar,Dynamic,Dynamic> > Eigen::SparseMatrixBase< Transpose< MatrixType > >::ConstantReturnType inherited
ConstInnerVectorReturnType
typedef Block<const Transpose< MatrixType > ,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Transpose< MatrixType > >::ConstInnerVectorReturnType inherited
ConstInnerVectorsReturnType
typedef Block<const Transpose< MatrixType > ,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Transpose< MatrixType > >::ConstInnerVectorsReturnType inherited
ConstTransposeReturnType
typedef internal::add_const<Transpose<constDerived>>::type Eigen::SparseMatrixBase< Transpose< MatrixType > >::ConstTransposeReturnType inherited
DenseMatrixType
typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime> Eigen::SparseMatrixBase< Transpose< MatrixType > >::DenseMatrixType inherited
type of the equivalent dense matrix
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
IndexVector
typedef Matrix<StorageIndex,Dynamic,1> Eigen::SparseMatrixBase< Transpose< MatrixType > >::IndexVector inherited
InnerVectorReturnType
typedef Block<Transpose< MatrixType > ,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Transpose< MatrixType > >::InnerVectorReturnType inherited
InnerVectorsReturnType
typedef Block<Transpose< MatrixType > ,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Transpose< MatrixType > >::InnerVectorsReturnType inherited
PacketReturnType
typedef internal::add_const_on_value_type_if_arithmetic<typenameinternal::packet_traits<Scalar>::type>::type Eigen::SparseMatrixBase< Transpose< MatrixType > >::PacketReturnType inherited
PacketScalar
typedef internal::packet_traits<Scalar>::type Eigen::SparseMatrixBase< Transpose< MatrixType > >::PacketScalar inherited
PlainObject
typedef SparseMatrix<Scalar, Flags&RowMajorBit ? RowMajor : ColMajor, StorageIndex> Eigen::SparseMatrixBase< Transpose< MatrixType > >::PlainObject inherited
RealScalar
typedef NumTraits<Scalar>::Real Eigen::SparseMatrixBase< Transpose< MatrixType > >::RealScalar inherited
This is the "real scalar" type; if the Scalar type is already real numbers (e.g. int, float or double) then RealScalar is just the same as Scalar. If Scalar is std::complex<T> then RealScalar is T.
See also
class NumTraits
Scalar
typedef internal::traits<Transpose< MatrixType > >::Scalar Eigen::SparseMatrixBase< Transpose< MatrixType > >::Scalar inherited
ScalarVector
typedef Matrix<Scalar,Dynamic,1> Eigen::SparseMatrixBase< Transpose< MatrixType > >::ScalarVector inherited
SquareMatrixType
typedef Matrix<Scalar,EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime)> Eigen::SparseMatrixBase< Transpose< MatrixType > >::SquareMatrixType inherited
type of the equivalent square matrix
StorageBaseType
typedef SparseMatrixBase Eigen::SparseMatrixBase< Transpose< MatrixType > >::StorageBaseType inherited
StorageIndex
typedef internal::traits<Transpose< MatrixType > >::StorageIndex Eigen::SparseMatrixBase< Transpose< MatrixType > >::StorageIndex inherited
The integer type used to store indices within a SparseMatrix. For a SparseMatrix<Scalar,Options,IndexType> it an alias of the third template parameter IndexType.
StorageKind
typedef internal::traits<Transpose< MatrixType > >::StorageKind Eigen::SparseMatrixBase< Transpose< MatrixType > >::StorageKind inherited
TransposeReturnType
typedef Transpose<Transpose< MatrixType > > Eigen::SparseMatrixBase< Transpose< MatrixType > >::TransposeReturnType inherited
value_type
typedef Scalar Eigen::SparseMatrixBase< Transpose< MatrixType > >::value_type inherited
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = RowsAtCompileTime,
      MaxColsAtCompileTime = ColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<MaxRowsAtCompileTime,
                                                      MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1,
      Flags = internal::traits<Derived>::Flags,
      IsRowMajor = Flags&RowMajorBit ? 1 : 0,
      InnerSizeAtCompileTime = int(IsVectorAtCompileTime) ? int(SizeAtCompileTime)
                             : int(IsRowMajor) ? int(ColsAtCompileTime) : int(RowsAtCompileTime),
      #ifndef EIGEN_PARSED_BY_DOXYGEN
      _HasDirectAccess = (int(Flags)&DirectAccessBit) ? 1 : 0 // workaround sunCC
      #endif
    };
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
const AdjointReturnType Eigen::SparseMatrixBase< Transpose< MatrixType > >::adjoint () const inline inherited
{ return AdjointReturnType(transpose()); }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
assign()
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::assign (const OtherDerived & other) inline protected inherited
assignGeneric()
void Eigen::SparseMatrixBase< Transpose< MatrixType > >::assignGeneric (const OtherDerived & other) inline protected inherited
blueNorm()
NumTraits< typenameinternal::traits< Transpose< MatrixType > >::Scalar >::Real Eigen::SparseMatrixBase< Transpose< MatrixType > >::blueNorm inline inherited
{
  return internal::blueNorm_impl(*this);
}
cols()
Index Eigen::SparseMatrixBase< Transpose< MatrixType > >::cols () const inline inherited
Returns
the number of columns.
See also
rows()
{ return derived().cols(); }
const_cast_derived()
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::const_cast_derived () const inline inherited
    { return *static_cast<Derived*>(const_cast<SparseMatrixBase*>(this)); }
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
convert_index()
static StorageIndex Eigen::SparseMatrixBase< Transpose< MatrixType > >::convert_index (const Index idx) inline static protected inherited
{
      return internal::convert_index<StorageIndex>(idx);
    }
cwiseProduct() [1/2]
EIGEN_STRONG_INLINE const SparseMatrixBase< Transpose< MatrixType > >::template CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< Transpose< MatrixType > >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
{
  return typename CwiseProductDenseReturnType<OtherDerived>::Type(derived(), other.derived());
}
cwiseProduct() [2/2]
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< Transpose< MatrixType > >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
derived() [1/2]
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived () inline inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
const Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::derived () const inline inherited
{ return *static_cast<const Derived*>(this); }
dot() [1/4]
internal::traits< Transpose< MatrixType > >::Scalar Eigen::SparseMatrixBase< Transpose< MatrixType > >::dot (const MatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  eigen_assert(other.size()>0 && "you are using a non initialized vector");
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  Scalar res(0);
  while (i)
  {
    res += numext::conj(i.value()) * other.coeff(i.index());
    ++i;
  }
  return res;
}
dot() [2/4]
Scalar Eigen::SparseMatrixBase< Transpose< MatrixType > >::dot (const MatrixBase< OtherDerived > & other) const inherited
dot() [3/4]
internal::traits< Transpose< MatrixType > >::Scalar Eigen::SparseMatrixBase< Transpose< MatrixType > >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  internal::evaluator<OtherDerived>  otherEval(other.derived());
  typename internal::evaluator<OtherDerived>::InnerIterator j(otherEval, 0);
  Scalar res(0);
  while (i && j)
  {
    if (i.index()==j.index())
    {
      res += numext::conj(i.value()) * j.value();
      ++i; ++j;
    }
    else if (i.index()<j.index())
      ++i;
    else
      ++j;
  }
  return res;
}
dot() [4/4]
Scalar Eigen::SparseMatrixBase< Transpose< MatrixType > >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
eval()
const internal::eval< Transpose< MatrixType > >::type Eigen::SparseMatrixBase< Transpose< MatrixType > >::eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
    { return typename internal::eval<Derived>::type(derived()); }
evalTo()
void Eigen::SparseMatrixBase< Transpose< MatrixType > >::evalTo (Dest &) const private inherited
innerSize()
Index Eigen::SparseMatrixBase< Transpose< MatrixType > >::innerSize () const inline inherited
Returns
the size of the inner dimension according to the storage order, i.e., the number of rows for a columns major matrix, and the number of cols otherwise
{ return (int(Flags)&RowMajorBit) ? this->cols() : this->rows(); }
innerVector() [1/2]
SparseMatrixBase< Transpose< MatrixType > >::InnerVectorReturnType Eigen::SparseMatrixBase< Transpose< MatrixType > >::innerVector (Index outer) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{ return InnerVectorReturnType(derived(), outer); }
innerVector() [2/2]
const SparseMatrixBase< Transpose< MatrixType > >::ConstInnerVectorReturnType Eigen::SparseMatrixBase< Transpose< MatrixType > >::innerVector (Index outer) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{ return ConstInnerVectorReturnType(derived(), outer); }
innerVectors() [1/2]
SparseMatrixBase< Transpose< MatrixType > >::InnerVectorsReturnType Eigen::SparseMatrixBase< Transpose< MatrixType > >::innerVectors (Index outerStart, Index outerSize) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{
  return Block<Derived,Dynamic,Dynamic,true>(derived(),
                                             IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                             IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
innerVectors() [2/2]
const SparseMatrixBase< Transpose< MatrixType > >::ConstInnerVectorsReturnType Eigen::SparseMatrixBase< Transpose< MatrixType > >::innerVectors (Index outerStart, Index outerSize) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{
  return Block<const Derived,Dynamic,Dynamic,true>(derived(),
                                                  IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                                  IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
isApprox() [1/2]
bool Eigen::SparseMatrixBase< Transpose< MatrixType > >::isApprox (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inline inherited
    { return toDense().isApprox(other,prec); }
isApprox() [2/2]
bool Eigen::SparseMatrixBase< Transpose< MatrixType > >::isApprox (const SparseMatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
{
  const typename internal::nested_eval<Derived,2,PlainObject>::type actualA(derived());
  typename internal::conditional<bool(IsRowMajor)==bool(OtherDerived::IsRowMajor),
    const typename internal::nested_eval<OtherDerived,2,PlainObject>::type,
    const PlainObject>::type actualB(other.derived());
  return (actualA - actualB).squaredNorm() <= prec * prec * numext::mini(actualA.squaredNorm(), actualB.squaredNorm());
}
isRValue()
bool Eigen::SparseMatrixBase< Transpose< MatrixType > >::isRValue () const inline inherited
{ return m_isRValue; }
isVector()
bool Eigen::SparseMatrixBase< Transpose< MatrixType > >::isVector () const inline inherited
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See also
rows(), cols(), IsVectorAtCompileTime.
{ return rows()==1 || cols()==1; }
markAsRValue()
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::markAsRValue () inline inherited
{ m_isRValue = true; return derived(); }
norm()
NumTraits< typenameinternal::traits< Transpose< MatrixType > >::Scalar >::Real Eigen::SparseMatrixBase< Transpose< MatrixType > >::norm inline inherited
{
  using std::sqrt;
  return sqrt(squaredNorm());
}
operator*() [1/3]
const Product< Transpose< MatrixType > , OtherDerived > Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator* (const DiagonalBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
operator*() [2/3]
const Product< Transpose< MatrixType > , OtherDerived > Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator* (const MatrixBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
operator*() [3/3]
const Product< Transpose< MatrixType > , OtherDerived, AliasFreeProduct > Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator* (const SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the product of two sparse matrices. By default a conservative product preserving the symbolic non zeros is performed. The automatic pruning of the small values can be achieved by calling the pruned() function in which case a totally different product algorithm is employed:
C = (A*B).pruned();             // supress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return Product<Derived,OtherDerived,AliasFreeProduct>(derived(), other.derived());
}
operator*=() [1/2]
EIGEN_STRONG_INLINE Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator*= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() *= other;
  return derived();
}
operator*=() [2/2]
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator*= (const SparseMatrixBase< OtherDerived > & other) inherited
operator+=() [1/4]
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator+= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [2/4]
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator+= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [3/4]
EIGEN_STRONG_INLINE Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() + other.derived();
}
operator+=() [4/4]
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
operator-=() [1/4]
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator-= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::sub_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [2/4]
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator-= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [3/4]
EIGEN_STRONG_INLINE Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() - other.derived();
}
operator-=() [4/4]
Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
operator/=()
EIGEN_STRONG_INLINE Transpose< MatrixType > & Eigen::SparseMatrixBase< Transpose< MatrixType > >::operator/= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() /= other;
  return derived();
}
outerSize()
Index Eigen::SparseMatrixBase< Transpose< MatrixType > >::outerSize () const inline inherited
Returns
the size of the storage major dimension, i.e., the number of columns for a columns major matrix, and the number of rows otherwise
{ return (int(Flags)&RowMajorBit) ? this->rows() : this->cols(); }
pruned()
const SparseView< Transpose< MatrixType > > Eigen::SparseMatrixBase< Transpose< MatrixType > >::pruned (const Scalar & reference = Scalar(0), const RealScalar & epsilon = NumTraits<Scalar>::dummy_precision()) const inline inherited
Returns
an expression of *this with values smaller than reference * epsilon removed.
This method is typically used in conjunction with the product of two sparse matrices to automatically prune the smallest values as follows:
C = (A*B).pruned();             // suppress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return SparseView<Derived>(derived(), reference, epsilon);
}
rows()
Index Eigen::SparseMatrixBase< Transpose< MatrixType > >::rows () const inline inherited
Returns
the number of rows.
See also
cols()
{ return derived().rows(); }
selfadjointView() [1/4]
SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Transpose< MatrixType > >::selfadjointView () inline inherited
selfadjointView() [2/4]
SparseMatrixBase< Transpose< MatrixType > >::template SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Transpose< MatrixType > >::selfadjointView () inherited
{
  return SparseSelfAdjointView<Derived, UpLo>(derived());
}
selfadjointView() [3/4]
ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Transpose< MatrixType > >::selfadjointView () const inline inherited
selfadjointView() [4/4]
SparseMatrixBase< Transpose< MatrixType > >::template ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Transpose< MatrixType > >::selfadjointView () const inherited
{
  return SparseSelfAdjointView<const Derived, UpLo>(derived());
}
size()
Index Eigen::SparseMatrixBase< Transpose< MatrixType > >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols().
{ return rows() * cols(); }
squaredNorm()
NumTraits< typenameinternal::traits< Transpose< MatrixType > >::Scalar >::Real Eigen::SparseMatrixBase< Transpose< MatrixType > >::squaredNorm inline inherited
{
  return numext::real((*this).cwiseAbs2().sum());
}
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
sum()
internal::traits< Transpose< MatrixType > >::Scalar Eigen::SparseMatrixBase< Transpose< MatrixType > >::sum inherited
{
  eigen_assert(rows()>0 && cols()>0 && "you are using a non initialized matrix");
  Scalar res(0);
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (typename internal::evaluator<Derived>::InnerIterator iter(thisEval,j); iter; ++iter)
      res += iter.value();
  return res;
}
toDense()
DenseMatrixType Eigen::SparseMatrixBase< Transpose< MatrixType > >::toDense () const inline inherited
    {
      return DenseMatrixType(derived());
    }
transpose() [1/2]
TransposeReturnType Eigen::SparseMatrixBase< Transpose< MatrixType > >::transpose () inline inherited
{ return TransposeReturnType(derived()); }
transpose() [2/2]
const ConstTransposeReturnType Eigen::SparseMatrixBase< Transpose< MatrixType > >::transpose () const inline inherited
{ return ConstTransposeReturnType(derived()); }
triangularView()
const TriangularView< const Transpose< MatrixType > , Mode > Eigen::SparseMatrixBase< Transpose< MatrixType > >::triangularView inline inherited
{
  return TriangularView<const Derived, Mode>(derived());
}
twistedBy()
SparseSymmetricPermutationProduct< Transpose< MatrixType > , Upper|Lower > Eigen::SparseMatrixBase< Transpose< MatrixType > >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline inherited
Returns
an expression of P H P^-1 where H is the matrix represented by *this
    {
      return SparseSymmetricPermutationProduct<Derived,Upper|Lower>(derived(), perm);
    }
Member Data Documentation
m_isRValue
bool Eigen::SparseMatrixBase< Transpose< MatrixType > >::m_isRValue protected inherited
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseTranspose.h