Prusa Slicer: Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > > Struct Template Reference
Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > > Struct Template Reference
#include <src/eigen/Eigen/src/SuperLUSupport/SuperLUSupport.h>
Public Types
typedef Matrix< Scalar, Rows, Cols, Options, MRows, MCols > MatrixType
Static Public Member Functions
static void run (MatrixType &mat, SluMatrix &res)
Detailed Description
template<typename Scalar, int Rows, int Cols, int Options, int MRows, int MCols>
struct Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >
Member Typedef Documentation
MatrixType
template<typename Scalar , int Rows, int Cols, int Options, int MRows, int MCols> typedef Matrix<Scalar,Rows,Cols,Options,MRows,MCols> Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::MatrixType
Member Function Documentation
run()
template<typename Scalar , int Rows, int Cols, int Options, int MRows, int MCols> static void Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run (MatrixType & mat, SluMatrix & res) inline static
  {
    eigen_assert( ((Options&RowMajor)!=RowMajor) && "row-major dense matrices is not supported by SuperLU");
    res.setStorageType(SLU_DN);
    res.setScalarType<Scalar>();
    res.Mtype     = SLU_GE;
    res.nrow      = mat.rows();
    res.ncol      = mat.cols();
    res.storage.lda       = mat.outerStride();
    res.storage.values    = mat.data();
  }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), eigen_assert, Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::outerStride(), Eigen::RowMajor, Eigen::PlainObjectBase< Derived >::rows(), Eigen::SluMatrix::setScalarType(), Eigen::SluMatrix::setStorageType(), and Eigen::SluMatrix::storage.
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/SuperLUSupport/SuperLUSupport.h