Prusa Slicer: Eigen::SuperLUBase< _MatrixType, Derived > Class Template Reference
Eigen::SuperLUBase< _MatrixType, Derived > Class Template Reference
The base class for the direct and incomplete LU factorization of SuperLU.
#include <src/eigen/Eigen/src/SuperLUSupport/SuperLUSupport.h>
Public Types
enum { ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef Matrix< Scalar, Dynamic, 1 > Vector
typedef Matrix< int, 1, MatrixType::ColsAtCompileTime > IntRowVectorType
typedef Matrix< int, MatrixType::RowsAtCompileTime, 1 > IntColVectorType
typedef Map< PermutationMatrix< Dynamic, Dynamic, int > > PermutationMap
typedef SparseMatrix< Scalar > LUMatrixType
Public Member Functions
SuperLUBase ()
~SuperLUBase ()
Index rows () const
Index cols () const
superlu_options_t & options ()
ComputationInfo info () const
Reports whether previous computation was successful.
void compute (const MatrixType &matrix)
void analyzePattern (const MatrixType &)
template<typename Stream >
void dumpMemory (Stream &)
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
template<typename Rhs , typename Dest >
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Types
typedef SparseSolverBase< Derived > Base
Protected Member Functions
void initFactorization (const MatrixType &a)
void init ()
void extractData () const
void clearFactors ()
Derived & derived ()
const Derived & derived () const
Protected Attributes
LUMatrixType m_l
LUMatrixType m_u
IntColVectorType m_p
IntRowVectorType m_q
LUMatrixType m_matrix
SluMatrix m_sluA
SuperMatrix m_sluL
SuperMatrix m_sluU
SluMatrix m_sluB
SluMatrix m_sluX
SuperLUStat_t m_sluStat
superlu_options_t m_sluOptions
std::vector< int > m_sluEtree
Matrix< RealScalar, Dynamic, 1 > m_sluRscale
Matrix< RealScalar, Dynamic, 1 > m_sluCscale
Matrix< RealScalar, Dynamic, 1 > m_sluFerr
Matrix< RealScalar, Dynamic, 1 > m_sluBerr
char m_sluEqued
ComputationInfo m_info
int m_factorizationIsOk
int m_analysisIsOk
bool m_extractedDataAreDirty
bool m_isInitialized
Private Member Functions
SuperLUBase (SuperLUBase &)
Detailed Description
template<typename _MatrixType, typename Derived>
class Eigen::SuperLUBase< _MatrixType, Derived >
The base class for the direct and incomplete LU factorization of SuperLU.
Member Typedef Documentation
Base
template<typename _MatrixType , typename Derived > typedef SparseSolverBase<Derived> Eigen::SuperLUBase< _MatrixType, Derived >::Base protected
IntColVectorType
template<typename _MatrixType , typename Derived > typedef Matrix<int, MatrixType::RowsAtCompileTime, 1> Eigen::SuperLUBase< _MatrixType, Derived >::IntColVectorType
IntRowVectorType
template<typename _MatrixType , typename Derived > typedef Matrix<int, 1, MatrixType::ColsAtCompileTime> Eigen::SuperLUBase< _MatrixType, Derived >::IntRowVectorType
LUMatrixType
template<typename _MatrixType , typename Derived > typedef SparseMatrix<Scalar> Eigen::SuperLUBase< _MatrixType, Derived >::LUMatrixType
MatrixType
template<typename _MatrixType , typename Derived > typedef _MatrixType Eigen::SuperLUBase< _MatrixType, Derived >::MatrixType
PermutationMap
template<typename _MatrixType , typename Derived > typedef Map<PermutationMatrix<Dynamic,Dynamic,int> > Eigen::SuperLUBase< _MatrixType, Derived >::PermutationMap
RealScalar
template<typename _MatrixType , typename Derived > typedef MatrixType::RealScalar Eigen::SuperLUBase< _MatrixType, Derived >::RealScalar
Scalar
template<typename _MatrixType , typename Derived > typedef MatrixType::Scalar Eigen::SuperLUBase< _MatrixType, Derived >::Scalar
StorageIndex
template<typename _MatrixType , typename Derived > typedef MatrixType::StorageIndex Eigen::SuperLUBase< _MatrixType, Derived >::StorageIndex
Vector
template<typename _MatrixType , typename Derived > typedef Matrix<Scalar,Dynamic,1> Eigen::SuperLUBase< _MatrixType, Derived >::Vector
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType , typename Derived > anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
         {
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
SuperLUBase() [1/2]
template<typename _MatrixType , typename Derived > Eigen::SuperLUBase< _MatrixType, Derived >::SuperLUBase () inline
{}
~SuperLUBase()
template<typename _MatrixType , typename Derived > Eigen::SuperLUBase< _MatrixType, Derived >::~SuperLUBase () inline
    {
      clearFactors();
    }
References Eigen::SuperLUBase< _MatrixType, Derived >::clearFactors().
SuperLUBase() [2/2]
template<typename _MatrixType , typename Derived > Eigen::SuperLUBase< _MatrixType, Derived >::SuperLUBase (SuperLUBase< _MatrixType, Derived > &) inline private
{ }
Member Function Documentation
_solve_impl()
template<typename Derived > template<typename Rhs , typename Dest > void Eigen::SparseSolverBase< Derived >::_solve_impl (const SparseMatrixBase< Rhs > & b, SparseMatrixBase< Dest > & dest) const inline inherited
    {
      internal::solve_sparse_through_dense_panels(derived(), b.derived(), dest.derived());
    }
References Eigen::SparseSolverBase< Derived >::derived(), Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::internal::solve_sparse_through_dense_panels().
analyzePattern()
template<typename _MatrixType , typename Derived > void Eigen::SuperLUBase< _MatrixType, Derived >::analyzePattern (const MatrixType &) inline
Performs a symbolic decomposition on the sparcity of matrix.
This function is particularly useful when solving for several problems having the same structure.
See also
factorize()
    {
      m_isInitialized = true;
      m_info = Success;
      m_analysisIsOk = true;
      m_factorizationIsOk = false;
    }
References Eigen::SuperLUBase< _MatrixType, Derived >::m_analysisIsOk, Eigen::SuperLUBase< _MatrixType, Derived >::m_factorizationIsOk, Eigen::SuperLUBase< _MatrixType, Derived >::m_info, Eigen::SuperLUBase< _MatrixType, Derived >::m_isInitialized, and Eigen::Success.
Referenced by Eigen::SuperLU< _MatrixType >::analyzePattern().
clearFactors()
template<typename _MatrixType , typename Derived > void Eigen::SuperLUBase< _MatrixType, Derived >::clearFactors () inline protected
    {
      if(m_sluL.Store)
        Destroy_SuperNode_Matrix(&m_sluL);
      if(m_sluU.Store)
        Destroy_CompCol_Matrix(&m_sluU);
      m_sluL.Store = 0;
      m_sluU.Store = 0;
      memset(&m_sluL,0,sizeof m_sluL);
      memset(&m_sluU,0,sizeof m_sluU);
    }
References Eigen::SuperLUBase< _MatrixType, Derived >::m_sluL, and Eigen::SuperLUBase< _MatrixType, Derived >::m_sluU.
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::~SuperLUBase(), and Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
cols()
template<typename _MatrixType , typename Derived > Index Eigen::SuperLUBase< _MatrixType, Derived >::cols () const inline
{ return m_matrix.cols(); }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), and Eigen::SuperLUBase< _MatrixType, Derived >::m_matrix.
compute()
template<typename _MatrixType , typename Derived > void Eigen::SuperLUBase< _MatrixType, Derived >::compute (const MatrixType & matrix) inline
Computes the sparse Cholesky decomposition of matrix
    {
      derived().analyzePattern(matrix);
      derived().factorize(matrix);
    }
References Eigen::SuperLUBase< _MatrixType, Derived >::derived().
Referenced by Eigen::SuperLU< _MatrixType >::SuperLU().
derived() [1/2]
template<typename _MatrixType , typename Derived > Derived & Eigen::SparseSolverBase< Derived >::derived () inline protected
{ return *static_cast<Derived*>(this); }
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::compute().
derived() [2/2]
template<typename _MatrixType , typename Derived > const Derived & Eigen::SparseSolverBase< Derived >::derived () const inline protected
{ return *static_cast<const Derived*>(this); }
dumpMemory()
template<typename _MatrixType , typename Derived > template<typename Stream > void Eigen::SuperLUBase< _MatrixType, Derived >::dumpMemory (Stream &) inline
    {}
extractData()
template<typename MatrixType , typename Derived > void Eigen::SuperLUBase< MatrixType, Derived >::extractData protected
{
  eigen_assert(m_factorizationIsOk && "The decomposition is not in a valid state for extracting factors, you must first call either compute() or analyzePattern()/factorize()");
  if (m_extractedDataAreDirty)
  {
    int         upper;
    int         fsupc, istart, nsupr;
    int         lastl = 0, lastu = 0;
    SCformat    *Lstore = static_cast<SCformat*>(m_sluL.Store);
    NCformat    *Ustore = static_cast<NCformat*>(m_sluU.Store);
    Scalar      *SNptr;
    const Index size = m_matrix.rows();
    m_l.resize(size,size);
    m_l.resizeNonZeros(Lstore->nnz);
    m_u.resize(size,size);
    m_u.resizeNonZeros(Ustore->nnz);
    int* Lcol = m_l.outerIndexPtr();
    int* Lrow = m_l.innerIndexPtr();
    Scalar* Lval = m_l.valuePtr();
    int* Ucol = m_u.outerIndexPtr();
    int* Urow = m_u.innerIndexPtr();
    Scalar* Uval = m_u.valuePtr();
    Ucol[0] = 0;
    Ucol[0] = 0;
    /* for each supernode */
    for (int k = 0; k <= Lstore->nsuper; ++k)
    {
      fsupc   = L_FST_SUPC(k);
      istart  = L_SUB_START(fsupc);
      nsupr   = L_SUB_START(fsupc+1) - istart;
      upper   = 1;
      /* for each column in the supernode */
      for (int j = fsupc; j < L_FST_SUPC(k+1); ++j)
      {
        SNptr = &((Scalar*)Lstore->nzval)[L_NZ_START(j)];
        /* Extract U */
        for (int i = U_NZ_START(j); i < U_NZ_START(j+1); ++i)
        {
          Uval[lastu] = ((Scalar*)Ustore->nzval)[i];
          /* Matlab doesn't like explicit zero. */
          if (Uval[lastu] != 0.0)
            Urow[lastu++] = U_SUB(i);
        }
        for (int i = 0; i < upper; ++i)
        {
          /* upper triangle in the supernode */
          Uval[lastu] = SNptr[i];
          /* Matlab doesn't like explicit zero. */
          if (Uval[lastu] != 0.0)
            Urow[lastu++] = L_SUB(istart+i);
        }
        Ucol[j+1] = lastu;
        /* Extract L */
        Lval[lastl] = 1.0; /* unit diagonal */
        Lrow[lastl++] = L_SUB(istart + upper - 1);
        for (int i = upper; i < nsupr; ++i)
        {
          Lval[lastl] = SNptr[i];
          /* Matlab doesn't like explicit zero. */
          if (Lval[lastl] != 0.0)
            Lrow[lastl++] = L_SUB(istart+i);
        }
        Lcol[j+1] = lastl;
        ++upper;
      } /* for j ... */
    } /* for k ... */
    // squeeze the matrices :
    m_l.resizeNonZeros(lastl);
    m_u.resizeNonZeros(lastu);
    m_extractedDataAreDirty = false;
  }
}
References eigen_assert.
info()
template<typename _MatrixType , typename Derived > ComputationInfo Eigen::SuperLUBase< _MatrixType, Derived >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NumericalIssue if the matrix.appears to be negative.
    {
      eigen_assert(m_isInitialized && "Decomposition is not initialized.");
      return m_info;
    }
References eigen_assert, Eigen::SuperLUBase< _MatrixType, Derived >::m_info, and Eigen::SuperLUBase< _MatrixType, Derived >::m_isInitialized.
init()
template<typename _MatrixType , typename Derived > void Eigen::SuperLUBase< _MatrixType, Derived >::init () inline protected
    {
      m_info = InvalidInput;
      m_isInitialized = false;
      m_sluL.Store = 0;
      m_sluU.Store = 0;
    }
References Eigen::InvalidInput, Eigen::SuperLUBase< _MatrixType, Derived >::m_info, Eigen::SuperLUBase< _MatrixType, Derived >::m_isInitialized, Eigen::SuperLUBase< _MatrixType, Derived >::m_sluL, and Eigen::SuperLUBase< _MatrixType, Derived >::m_sluU.
Referenced by Eigen::SuperLU< _MatrixType >::init().
initFactorization()
template<typename _MatrixType , typename Derived > void Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization (const MatrixType & a) inline protected
    {
      set_default_options(&this->m_sluOptions);
      const Index size = a.rows();
      m_matrix = a;
      m_sluA = internal::asSluMatrix(m_matrix);
      clearFactors();
      m_p.resize(size);
      m_q.resize(size);
      m_sluRscale.resize(size);
      m_sluCscale.resize(size);
      m_sluEtree.resize(size);
      // set empty B and X
      m_sluB.setStorageType(SLU_DN);
      m_sluB.setScalarType<Scalar>();
      m_sluB.Mtype          = SLU_GE;
      m_sluB.storage.values = 0;
      m_sluB.nrow           = 0;
      m_sluB.ncol           = 0;
      m_sluB.storage.lda    = internal::convert_index<int>(size);
      m_sluX                = m_sluB;
      m_extractedDataAreDirty = true;
    }
References Eigen::internal::asSluMatrix(), Eigen::SuperLUBase< _MatrixType, Derived >::clearFactors(), Eigen::SuperLUBase< _MatrixType, Derived >::m_extractedDataAreDirty, Eigen::SuperLUBase< _MatrixType, Derived >::m_matrix, Eigen::SuperLUBase< _MatrixType, Derived >::m_p, Eigen::SuperLUBase< _MatrixType, Derived >::m_q, Eigen::SuperLUBase< _MatrixType, Derived >::m_sluA, Eigen::SuperLUBase< _MatrixType, Derived >::m_sluB, Eigen::SuperLUBase< _MatrixType, Derived >::m_sluCscale, Eigen::SuperLUBase< _MatrixType, Derived >::m_sluEtree, Eigen::SuperLUBase< _MatrixType, Derived >::m_sluOptions, Eigen::SuperLUBase< _MatrixType, Derived >::m_sluRscale, Eigen::SuperLUBase< _MatrixType, Derived >::m_sluX, Eigen::PlainObjectBase< Derived >::resize(), Eigen::SluMatrix::setScalarType(), Eigen::SluMatrix::setStorageType(), and Eigen::SluMatrix::storage.
options()
template<typename _MatrixType , typename Derived > superlu_options_t & Eigen::SuperLUBase< _MatrixType, Derived >::options () inline
Returns
a reference to the Super LU option object to configure the Super LU algorithms.
{ return m_sluOptions; }
References Eigen::SuperLUBase< _MatrixType, Derived >::m_sluOptions.
rows()
template<typename _MatrixType , typename Derived > Index Eigen::SuperLUBase< _MatrixType, Derived >::rows () const inline
{ return m_matrix.rows(); }
References Eigen::SuperLUBase< _MatrixType, Derived >::m_matrix, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
solve() [1/2]
template<typename Derived > template<typename Rhs > const Solve< Derived, Rhs > Eigen::SparseSolverBase< Derived >::solve (const MatrixBase< Rhs > & b) const inline inherited
Returns
an expression of the solution x of using the current decomposition of A.
See also
compute()
    {
      eigen_assert(m_isInitialized && "Solver is not initialized.");
      eigen_assert(derived().rows()==b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
      return Solve<Derived, Rhs>(derived(), b.derived());
    }
References Eigen::SparseSolverBase< Derived >::derived(), eigen_assert, and Eigen::SparseSolverBase< Derived >::m_isInitialized.
Referenced by igl::embree::bone_heat(), igl::Frame_field_deformer::compute_optimal_positions(), igl::eigs(), igl::copyleft::comiso::FrameInterpolator::interpolateSymmetric(), igl::slim::solve_weighted_arap(), and igl::copyleft::comiso::NRosyField::solveNoRoundings().
solve() [2/2]
template<typename Derived > template<typename Rhs > const Solve< Derived, Rhs > Eigen::SparseSolverBase< Derived >::solve (const SparseMatrixBase< Rhs > & b) const inline inherited
Returns
an expression of the solution x of using the current decomposition of A.
See also
compute()
    {
      eigen_assert(m_isInitialized && "Solver is not initialized.");
      eigen_assert(derived().rows()==b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
      return Solve<Derived, Rhs>(derived(), b.derived());
    }
Member Data Documentation
m_analysisIsOk
template<typename _MatrixType , typename Derived > int Eigen::SuperLUBase< _MatrixType, Derived >::m_analysisIsOk protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::analyzePattern().
m_extractedDataAreDirty
template<typename _MatrixType , typename Derived > bool Eigen::SuperLUBase< _MatrixType, Derived >::m_extractedDataAreDirty mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
m_factorizationIsOk
template<typename _MatrixType , typename Derived > int Eigen::SuperLUBase< _MatrixType, Derived >::m_factorizationIsOk protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::analyzePattern().
m_info
template<typename _MatrixType , typename Derived > ComputationInfo Eigen::SuperLUBase< _MatrixType, Derived >::m_info mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::analyzePattern(), Eigen::SuperLUBase< _MatrixType, Derived >::info(), and Eigen::SuperLUBase< _MatrixType, Derived >::init().
m_isInitialized
template<typename _MatrixType , typename Derived > bool Eigen::SparseSolverBase< Derived >::m_isInitialized mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::analyzePattern(), Eigen::SuperLUBase< _MatrixType, Derived >::info(), and Eigen::SuperLUBase< _MatrixType, Derived >::init().
m_l
template<typename _MatrixType , typename Derived > LUMatrixType Eigen::SuperLUBase< _MatrixType, Derived >::m_l mutable protected
m_matrix
template<typename _MatrixType , typename Derived > LUMatrixType Eigen::SuperLUBase< _MatrixType, Derived >::m_matrix mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::cols(), Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization(), and Eigen::SuperLUBase< _MatrixType, Derived >::rows().
m_p
template<typename _MatrixType , typename Derived > IntColVectorType Eigen::SuperLUBase< _MatrixType, Derived >::m_p mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
m_q
template<typename _MatrixType , typename Derived > IntRowVectorType Eigen::SuperLUBase< _MatrixType, Derived >::m_q mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
m_sluA
template<typename _MatrixType , typename Derived > SluMatrix Eigen::SuperLUBase< _MatrixType, Derived >::m_sluA mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
m_sluB
template<typename _MatrixType , typename Derived > SluMatrix Eigen::SuperLUBase< _MatrixType, Derived >::m_sluB mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
m_sluBerr
template<typename _MatrixType , typename Derived > Matrix<RealScalar,Dynamic,1> Eigen::SuperLUBase< _MatrixType, Derived >::m_sluBerr protected
m_sluCscale
template<typename _MatrixType , typename Derived > Matrix<RealScalar,Dynamic,1> Eigen::SuperLUBase< _MatrixType, Derived >::m_sluCscale protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
m_sluEqued
template<typename _MatrixType , typename Derived > char Eigen::SuperLUBase< _MatrixType, Derived >::m_sluEqued mutable protected
m_sluEtree
template<typename _MatrixType , typename Derived > std::vector<int> Eigen::SuperLUBase< _MatrixType, Derived >::m_sluEtree mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
m_sluFerr
template<typename _MatrixType , typename Derived > Matrix<RealScalar,Dynamic,1> Eigen::SuperLUBase< _MatrixType, Derived >::m_sluFerr mutable protected
m_sluL
template<typename _MatrixType , typename Derived > SuperMatrix Eigen::SuperLUBase< _MatrixType, Derived >::m_sluL mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::clearFactors(), and Eigen::SuperLUBase< _MatrixType, Derived >::init().
m_sluOptions
template<typename _MatrixType , typename Derived > superlu_options_t Eigen::SuperLUBase< _MatrixType, Derived >::m_sluOptions mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization(), and Eigen::SuperLUBase< _MatrixType, Derived >::options().
m_sluRscale
template<typename _MatrixType , typename Derived > Matrix<RealScalar,Dynamic,1> Eigen::SuperLUBase< _MatrixType, Derived >::m_sluRscale mutable protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
m_sluStat
template<typename _MatrixType , typename Derived > SuperLUStat_t Eigen::SuperLUBase< _MatrixType, Derived >::m_sluStat mutable protected
m_sluU
template<typename _MatrixType , typename Derived > SuperMatrix Eigen::SuperLUBase< _MatrixType, Derived >::m_sluU protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::clearFactors(), and Eigen::SuperLUBase< _MatrixType, Derived >::init().
m_sluX
template<typename _MatrixType , typename Derived > SluMatrix Eigen::SuperLUBase< _MatrixType, Derived >::m_sluX protected
Referenced by Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization().
m_u
template<typename _MatrixType , typename Derived > LUMatrixType Eigen::SuperLUBase< _MatrixType, Derived >::m_u mutable protected
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SuperLUSupport/SuperLUSupport.h