Prusa Slicer: Slic3r::GUI::Selection::VolumeCache::TransformCache Struct Reference
Slic3r::GUI::Selection::VolumeCache::TransformCache Struct Reference
Public Member Functions
TransformCache ()=default
TransformCache (const Geometry::Transformation &transform)
Public Attributes
Vec3d position { Vec3d::Zero() }
Vec3d rotation { Vec3d::Zero() }
Vec3d scaling_factor { Vec3d::Ones() }
Vec3d mirror { Vec3d::Ones() }
Transform3d rotation_matrix { Transform3d::Identity() }
Transform3d scale_matrix { Transform3d::Identity() }
Transform3d mirror_matrix { Transform3d::Identity() }
Transform3d full_matrix { Transform3d::Identity() }
Geometry::Transformation transform
Detailed Description
Constructor & Destructor Documentation
TransformCache() [1/2]
Slic3r::GUI::Selection::VolumeCache::TransformCache::TransformCache () default
TransformCache() [2/2]
Slic3r::GUI::Selection::VolumeCache::TransformCache::TransformCache (const Geometry::Transformation & transform) explicit
    : position(transform.get_offset())
    , rotation(transform.get_rotation())
    , scaling_factor(transform.get_scaling_factor())
    , mirror(transform.get_mirror())
    , full_matrix(transform.get_matrix())
    , transform(transform)
    , rotation_matrix(transform.get_rotation_matrix())
    , scale_matrix(transform.get_scaling_factor_matrix())
    , mirror_matrix(transform.get_mirror_matrix())
{
}
Member Data Documentation
full_matrix
Transform3d Slic3r::GUI::Selection::VolumeCache::TransformCache::full_matrix { Transform3d::Identity() }
Referenced by Slic3r::GUI::Selection::VolumeCache::get_instance_full_matrix(), and Slic3r::GUI::Selection::VolumeCache::get_volume_full_matrix().
mirror
Vec3d Slic3r::GUI::Selection::VolumeCache::TransformCache::mirror { Vec3d::Ones() }
Referenced by Slic3r::GUI::Selection::VolumeCache::get_instance_mirror().
mirror_matrix
Transform3d Slic3r::GUI::Selection::VolumeCache::TransformCache::mirror_matrix { Transform3d::Identity() }
Referenced by Slic3r::GUI::Selection::VolumeCache::get_instance_mirror_matrix(), and Slic3r::GUI::Selection::VolumeCache::get_volume_mirror_matrix().
position
Vec3d Slic3r::GUI::Selection::VolumeCache::TransformCache::position { Vec3d::Zero() }
Referenced by Slic3r::GUI::Selection::VolumeCache::get_instance_position(), and Slic3r::GUI::Selection::VolumeCache::get_volume_position().
rotation
Vec3d Slic3r::GUI::Selection::VolumeCache::TransformCache::rotation { Vec3d::Zero() }
Referenced by Slic3r::GUI::Selection::VolumeCache::get_instance_rotation().
rotation_matrix
Transform3d Slic3r::GUI::Selection::VolumeCache::TransformCache::rotation_matrix { Transform3d::Identity() }
Referenced by Slic3r::GUI::Selection::VolumeCache::get_instance_rotation_matrix(), and Slic3r::GUI::Selection::VolumeCache::get_volume_rotation_matrix().
scale_matrix
Transform3d Slic3r::GUI::Selection::VolumeCache::TransformCache::scale_matrix { Transform3d::Identity() }
Referenced by Slic3r::GUI::Selection::VolumeCache::get_instance_scale_matrix(), and Slic3r::GUI::Selection::VolumeCache::get_volume_scale_matrix().
scaling_factor
Vec3d Slic3r::GUI::Selection::VolumeCache::TransformCache::scaling_factor { Vec3d::Ones() }
Referenced by Slic3r::GUI::Selection::VolumeCache::get_instance_scaling_factor().
transform
Geometry::Transformation Slic3r::GUI::Selection::VolumeCache::TransformCache::transform
Referenced by Slic3r::GUI::Selection::VolumeCache::get_instance_transform(), and Slic3r::GUI::Selection::VolumeCache::get_volume_transform().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/Selection.hpp
src/slic3r/GUI/Selection.cpp