Prusa Slicer: Slic3r::AvrDude::priv Struct Reference
Slic3r::AvrDude::priv Struct Reference
Classes
struct HandlerGuard
Public Member Functions
void set_handlers ()
void unset_handlers ()
int run_one (const std::vector< std::string > &args)
int run ()
Public Attributes
std::deque< std::vector< std::string > > args
bool cancelled = false
int exit_code = 0
size_t current_args_set = 0
RunFn run_fn
MessageFn message_fn
ProgressFn progress_fn
CompleteFn complete_fn
std::thread avrdude_thread
Detailed Description
Member Function Documentation
run()
int Slic3r::AvrDude::priv::run ()
                     {
  for (; args.size() > 0; current_args_set++) {
    int res = run_one(args.front());
    args.pop_front();
    if (res != 0) {
      return res;
    }
  }
  return 0;
}
run_one()
int Slic3r::AvrDude::priv::run_one (const std::vector< std::string > & args)
{
  std::vector<const char*> c_args { PACKAGE };
  std::string command_line { PACKAGE };
  for (const auto &arg : args) {
    c_args.push_back(arg.c_str());
    command_line.push_back(' ');
    command_line.append(arg);
  }
  command_line.push_back('\n');
  HandlerGuard guard(*this);
  message_fn(command_line.c_str(), (unsigned)command_line.size());
  const auto res = ::avrdude_main(static_cast<int>(c_args.size()), const_cast<char**>(c_args.data()));
  return res;
}
References arg(), avrdude_main(), and PACKAGE.
set_handlers()
void Slic3r::AvrDude::priv::set_handlers ()
{
  if (message_fn) {
    ::avrdude_message_handler_set(avrdude_message_handler_closure, reinterpret_cast<void*>(&message_fn));
  } else {
    ::avrdude_message_handler_set(nullptr, nullptr);
  }
  if (progress_fn) {
    ::avrdude_progress_handler_set(avrdude_progress_handler_closure, reinterpret_cast<void*>(&progress_fn));
  } else {
    ::avrdude_progress_handler_set(nullptr, nullptr);
  }
  ::avrdude_oom_handler_set(avrdude_oom_handler, nullptr);
}
References Slic3r::avrdude_message_handler_closure(), avrdude_message_handler_set(), avrdude_oom_handler, avrdude_oom_handler_set(), Slic3r::avrdude_progress_handler_closure(), avrdude_progress_handler_set(), message_fn, and progress_fn.
Referenced by Slic3r::AvrDude::priv::HandlerGuard::HandlerGuard().
unset_handlers()
void Slic3r::AvrDude::priv::unset_handlers ()
{
  ::avrdude_message_handler_set(nullptr, nullptr);
  ::avrdude_progress_handler_set(nullptr, nullptr);
  ::avrdude_oom_handler_set(nullptr, nullptr);
}
References avrdude_message_handler_set(), avrdude_oom_handler_set(), and avrdude_progress_handler_set().
Referenced by Slic3r::AvrDude::priv::HandlerGuard::~HandlerGuard().
Member Data Documentation
args
std::deque<std::vector<std::string> > Slic3r::AvrDude::priv::args
avrdude_thread
std::thread Slic3r::AvrDude::priv::avrdude_thread
cancelled
bool Slic3r::AvrDude::priv::cancelled = false
complete_fn
CompleteFn Slic3r::AvrDude::priv::complete_fn
current_args_set
size_t Slic3r::AvrDude::priv::current_args_set = 0
exit_code
int Slic3r::AvrDude::priv::exit_code = 0
message_fn
MessageFn Slic3r::AvrDude::priv::message_fn
Referenced by set_handlers().
progress_fn
ProgressFn Slic3r::AvrDude::priv::progress_fn
Referenced by set_handlers().
run_fn
RunFn Slic3r::AvrDude::priv::run_fn
The documentation for this struct was generated from the following file:
src/avrdude/avrdude-slic3r.cpp