Prusa Slicer: src/avrdude/config_gram.c File Reference
config_gram.c File Reference
#include "ac_cfg.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "config.h"
#include <stddef.h>
Classes
union yyalloc
Macros
#define YYBISON 1
#define YYBISON_VERSION "3.0.4"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 0
#define YYPUSH 0
#define YYPULL 1
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define YY_NULLPTR 0
#define YYERROR_VERBOSE 0
#define YY_YY_CONFIG_GRAM_H_INCLUDED
#define YYDEBUG 0
#define YYTOKENTYPE
#define K_READ 258
#define K_WRITE 259
#define K_READ_LO 260
#define K_READ_HI 261
#define K_WRITE_LO 262
#define K_WRITE_HI 263
#define K_LOADPAGE_LO 264
#define K_LOADPAGE_HI 265
#define K_LOAD_EXT_ADDR 266
#define K_WRITEPAGE 267
#define K_CHIP_ERASE 268
#define K_PGM_ENABLE 269
#define K_MEMORY 270
#define K_PAGE_SIZE 271
#define K_PAGED 272
#define K_BAUDRATE 273
#define K_BS2 274
#define K_BUFF 275
#define K_CHIP_ERASE_DELAY 276
#define K_CONNTYPE 277
#define K_DEDICATED 278
#define K_DEFAULT_BITCLOCK 279
#define K_DEFAULT_PARALLEL 280
#define K_DEFAULT_PROGRAMMER 281
#define K_DEFAULT_SAFEMODE 282
#define K_DEFAULT_SERIAL 283
#define K_DESC 284
#define K_DEVICECODE 285
#define K_STK500_DEVCODE 286
#define K_AVR910_DEVCODE 287
#define K_EEPROM 288
#define K_ERRLED 289
#define K_FLASH 290
#define K_ID 291
#define K_IO 292
#define K_LOADPAGE 293
#define K_MAX_WRITE_DELAY 294
#define K_MCU_BASE 295
#define K_MIN_WRITE_DELAY 296
#define K_MISO 297
#define K_MOSI 298
#define K_NUM_PAGES 299
#define K_NVM_BASE 300
#define K_OCDREV 301
#define K_OFFSET 302
#define K_PAGEL 303
#define K_PARALLEL 304
#define K_PARENT 305
#define K_PART 306
#define K_PGMLED 307
#define K_PROGRAMMER 308
#define K_PSEUDO 309
#define K_PWROFF_AFTER_WRITE 310
#define K_RDYLED 311
#define K_READBACK_P1 312
#define K_READBACK_P2 313
#define K_READMEM 314
#define K_RESET 315
#define K_RETRY_PULSE 316
#define K_SERIAL 317
#define K_SCK 318
#define K_SIGNATURE 319
#define K_SIZE 320
#define K_USB 321
#define K_USBDEV 322
#define K_USBSN 323
#define K_USBPID 324
#define K_USBPRODUCT 325
#define K_USBVENDOR 326
#define K_USBVID 327
#define K_TYPE 328
#define K_VCC 329
#define K_VFYLED 330
#define K_NO 331
#define K_YES 332
#define K_TIMEOUT 333
#define K_STABDELAY 334
#define K_CMDEXEDELAY 335
#define K_HVSPCMDEXEDELAY 336
#define K_SYNCHLOOPS 337
#define K_BYTEDELAY 338
#define K_POLLVALUE 339
#define K_POLLINDEX 340
#define K_PREDELAY 341
#define K_POSTDELAY 342
#define K_POLLMETHOD 343
#define K_MODE 344
#define K_DELAY 345
#define K_BLOCKSIZE 346
#define K_READSIZE 347
#define K_HVENTERSTABDELAY 348
#define K_PROGMODEDELAY 349
#define K_LATCHCYCLES 350
#define K_TOGGLEVTG 351
#define K_POWEROFFDELAY 352
#define K_RESETDELAYMS 353
#define K_RESETDELAYUS 354
#define K_HVLEAVESTABDELAY 355
#define K_RESETDELAY 356
#define K_SYNCHCYCLES 357
#define K_HVCMDEXEDELAY 358
#define K_CHIPERASEPULSEWIDTH 359
#define K_CHIPERASEPOLLTIMEOUT 360
#define K_CHIPERASETIME 361
#define K_PROGRAMFUSEPULSEWIDTH 362
#define K_PROGRAMFUSEPOLLTIMEOUT 363
#define K_PROGRAMLOCKPULSEWIDTH 364
#define K_PROGRAMLOCKPOLLTIMEOUT 365
#define K_PP_CONTROLSTACK 366
#define K_HVSP_CONTROLSTACK 367
#define K_ALLOWFULLPAGEBITSTREAM 368
#define K_ENABLEPAGEPROGRAMMING 369
#define K_HAS_JTAG 370
#define K_HAS_DW 371
#define K_HAS_PDI 372
#define K_HAS_TPI 373
#define K_IDR 374
#define K_IS_AT90S1200 375
#define K_IS_AVR32 376
#define K_RAMPZ 377
#define K_SPMCR 378
#define K_EECR 379
#define K_FLASH_INSTR 380
#define K_EEPROM_INSTR 381
#define TKN_COMMA 382
#define TKN_EQUAL 383
#define TKN_SEMI 384
#define TKN_TILDE 385
#define TKN_LEFT_PAREN 386
#define TKN_RIGHT_PAREN 387
#define TKN_NUMBER 388
#define TKN_NUMBER_REAL 389
#define TKN_STRING 390
#define YYSIZE_T size_t
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YY_(Msgid) Msgid
#define YY_ATTRIBUTE(Spec) /* empty */
#define YY_ATTRIBUTE_PURE YY_ATTRIBUTE ((__pure__))
#define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#define _Noreturn YY_ATTRIBUTE ((__noreturn__))
#define YYUSE(E) ((void) (E))
#define YY_INITIAL_VALUE(Value) Value
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYMALLOC malloc
#define YYFREE free
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY_NEEDED 1
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYFINAL 22
#define YYLAST 401
#define YYNTOKENS 136
#define YYNNTS 45
#define YYNRULES 182
#define YYNSTATES 418
#define YYUNDEFTOK 2
#define YYMAXUTOK 390
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -258
#define yypact_value_is_default(Yystate) (!!((Yystate) == (-258)))
#define YYTABLE_NINF -1
#define yytable_value_is_error(Yytable_value) 0
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYDPRINTF(Args)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
Typedefs
typedef unsigned char yytype_uint8
typedef signed char yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
Enumerations
enum yytokentype {
K_READ = 258 , K_WRITE = 259 , K_READ_LO = 260 , K_READ_HI = 261 ,
K_WRITE_LO = 262 , K_WRITE_HI = 263 , K_LOADPAGE_LO = 264 , K_LOADPAGE_HI = 265 ,
K_LOAD_EXT_ADDR = 266 , K_WRITEPAGE = 267 , K_CHIP_ERASE = 268 , K_PGM_ENABLE = 269 ,
K_MEMORY = 270 , K_PAGE_SIZE = 271 , K_PAGED = 272 , K_BAUDRATE = 273 ,
K_BS2 = 274 , K_BUFF = 275 , K_CHIP_ERASE_DELAY = 276 , K_CONNTYPE = 277 ,
K_DEDICATED = 278 , K_DEFAULT_BITCLOCK = 279 , K_DEFAULT_PARALLEL = 280 , K_DEFAULT_PROGRAMMER = 281 ,
K_DEFAULT_SAFEMODE = 282 , K_DEFAULT_SERIAL = 283 , K_DESC = 284 , K_DEVICECODE = 285 ,
K_STK500_DEVCODE = 286 , K_AVR910_DEVCODE = 287 , K_EEPROM = 288 , K_ERRLED = 289 ,
K_FLASH = 290 , K_ID = 291 , K_IO = 292 , K_LOADPAGE = 293 ,
K_MAX_WRITE_DELAY = 294 , K_MCU_BASE = 295 , K_MIN_WRITE_DELAY = 296 , K_MISO = 297 ,
K_MOSI = 298 , K_NUM_PAGES = 299 , K_NVM_BASE = 300 , K_OCDREV = 301 ,
K_OFFSET = 302 , K_PAGEL = 303 , K_PARALLEL = 304 , K_PARENT = 305 ,
K_PART = 306 , K_PGMLED = 307 , K_PROGRAMMER = 308 , K_PSEUDO = 309 ,
K_PWROFF_AFTER_WRITE = 310 , K_RDYLED = 311 , K_READBACK_P1 = 312 , K_READBACK_P2 = 313 ,
K_READMEM = 314 , K_RESET = 315 , K_RETRY_PULSE = 316 , K_SERIAL = 317 ,
K_SCK = 318 , K_SIGNATURE = 319 , K_SIZE = 320 , K_USB = 321 ,
K_USBDEV = 322 , K_USBSN = 323 , K_USBPID = 324 , K_USBPRODUCT = 325 ,
K_USBVENDOR = 326 , K_USBVID = 327 , K_TYPE = 328 , K_VCC = 329 ,
K_VFYLED = 330 , K_NO = 331 , K_YES = 332 , K_TIMEOUT = 333 ,
K_STABDELAY = 334 , K_CMDEXEDELAY = 335 , K_HVSPCMDEXEDELAY = 336 , K_SYNCHLOOPS = 337 ,
K_BYTEDELAY = 338 , K_POLLVALUE = 339 , K_POLLINDEX = 340 , K_PREDELAY = 341 ,
K_POSTDELAY = 342 , K_POLLMETHOD = 343 , K_MODE = 344 , K_DELAY = 345 ,
K_BLOCKSIZE = 346 , K_READSIZE = 347 , K_HVENTERSTABDELAY = 348 , K_PROGMODEDELAY = 349 ,
K_LATCHCYCLES = 350 , K_TOGGLEVTG = 351 , K_POWEROFFDELAY = 352 , K_RESETDELAYMS = 353 ,
K_RESETDELAYUS = 354 , K_HVLEAVESTABDELAY = 355 , K_RESETDELAY = 356 , K_SYNCHCYCLES = 357 ,
K_HVCMDEXEDELAY = 358 , K_CHIPERASEPULSEWIDTH = 359 , K_CHIPERASEPOLLTIMEOUT = 360 , K_CHIPERASETIME = 361 ,
K_PROGRAMFUSEPULSEWIDTH = 362 , K_PROGRAMFUSEPOLLTIMEOUT = 363 , K_PROGRAMLOCKPULSEWIDTH = 364 , K_PROGRAMLOCKPOLLTIMEOUT = 365 ,
K_PP_CONTROLSTACK = 366 , K_HVSP_CONTROLSTACK = 367 , K_ALLOWFULLPAGEBITSTREAM = 368 , K_ENABLEPAGEPROGRAMMING = 369 ,
K_HAS_JTAG = 370 , K_HAS_DW = 371 , K_HAS_PDI = 372 , K_HAS_TPI = 373 ,
K_IDR = 374 , K_IS_AT90S1200 = 375 , K_IS_AVR32 = 376 , K_RAMPZ = 377 ,
K_SPMCR = 378 , K_EECR = 379 , K_FLASH_INSTR = 380 , K_EEPROM_INSTR = 381 ,
TKN_COMMA = 382 , TKN_EQUAL = 383 , TKN_SEMI = 384 , TKN_TILDE = 385 ,
TKN_LEFT_PAREN = 386 , TKN_RIGHT_PAREN = 387 , TKN_NUMBER = 388 , TKN_NUMBER_REAL = 389 ,
TKN_STRING = 390
}
Functions
int yylex (void)
int yyerror (char *errmsg,...)
int yywarning (char *errmsg,...)
static int assign_pin (int pinno, TOKEN *v, int invert)
static int assign_pin_list (int invert)
static int which_opcode (TOKEN *opcode)
static int parse_cmdbits (OPCODE *op)
int yyparse (void)
void * malloc (YYSIZE_T)
void free (void *)
static void yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep)
Variables
static int pin_name
YYSTYPE yylval
static const yytype_uint8 yytranslate []
static const yytype_int16 yypact []
static const yytype_uint8 yydefact []
static const yytype_int16 yypgoto []
static const yytype_int16 yydefgoto []
static const yytype_uint16 yytable []
static const yytype_int16 yycheck []
static const yytype_uint8 yystos []
static const yytype_uint8 yyr1 []
static const yytype_uint8 yyr2 []
int yychar
int yynerrs
Class Documentation
yyalloc
union yyalloc
Class Members
yytype_int16 yyss_alloc
YYSTYPE yyvs_alloc
Macro Definition Documentation
_Noreturn
#define _Noreturn YY_ATTRIBUTE ((__noreturn__))
K_ALLOWFULLPAGEBITSTREAM
#define K_ALLOWFULLPAGEBITSTREAM 368
K_AVR910_DEVCODE
#define K_AVR910_DEVCODE 287
K_BAUDRATE
#define K_BAUDRATE 273
K_BLOCKSIZE
#define K_BLOCKSIZE 346
K_BS2
#define K_BS2 274
K_BUFF
#define K_BUFF 275
K_BYTEDELAY
#define K_BYTEDELAY 338
K_CHIP_ERASE
#define K_CHIP_ERASE 268
K_CHIP_ERASE_DELAY
#define K_CHIP_ERASE_DELAY 276
K_CHIPERASEPOLLTIMEOUT
#define K_CHIPERASEPOLLTIMEOUT 360
K_CHIPERASEPULSEWIDTH
#define K_CHIPERASEPULSEWIDTH 359
K_CHIPERASETIME
#define K_CHIPERASETIME 361
K_CMDEXEDELAY
#define K_CMDEXEDELAY 335
K_CONNTYPE
#define K_CONNTYPE 277
K_DEDICATED
#define K_DEDICATED 278
K_DEFAULT_BITCLOCK
#define K_DEFAULT_BITCLOCK 279
K_DEFAULT_PARALLEL
#define K_DEFAULT_PARALLEL 280
K_DEFAULT_PROGRAMMER
#define K_DEFAULT_PROGRAMMER 281
K_DEFAULT_SAFEMODE
#define K_DEFAULT_SAFEMODE 282
K_DEFAULT_SERIAL
#define K_DEFAULT_SERIAL 283
K_DELAY
#define K_DELAY 345
K_DESC
#define K_DESC 284
K_DEVICECODE
#define K_DEVICECODE 285
K_EECR
#define K_EECR 379
K_EEPROM
#define K_EEPROM 288
K_EEPROM_INSTR
#define K_EEPROM_INSTR 381
K_ENABLEPAGEPROGRAMMING
#define K_ENABLEPAGEPROGRAMMING 369
K_ERRLED
#define K_ERRLED 289
K_FLASH
#define K_FLASH 290
K_FLASH_INSTR
#define K_FLASH_INSTR 380
K_HAS_DW
#define K_HAS_DW 371
K_HAS_JTAG
#define K_HAS_JTAG 370
K_HAS_PDI
#define K_HAS_PDI 372
K_HAS_TPI
#define K_HAS_TPI 373
K_HVCMDEXEDELAY
#define K_HVCMDEXEDELAY 358
K_HVENTERSTABDELAY
#define K_HVENTERSTABDELAY 348
K_HVLEAVESTABDELAY
#define K_HVLEAVESTABDELAY 355
K_HVSP_CONTROLSTACK
#define K_HVSP_CONTROLSTACK 367
K_HVSPCMDEXEDELAY
#define K_HVSPCMDEXEDELAY 336
K_ID
#define K_ID 291
K_IDR
#define K_IDR 374
K_IO
#define K_IO 292
K_IS_AT90S1200
#define K_IS_AT90S1200 375
K_IS_AVR32
#define K_IS_AVR32 376
K_LATCHCYCLES
#define K_LATCHCYCLES 350
K_LOAD_EXT_ADDR
#define K_LOAD_EXT_ADDR 266
K_LOADPAGE
#define K_LOADPAGE 293
K_LOADPAGE_HI
#define K_LOADPAGE_HI 265
K_LOADPAGE_LO
#define K_LOADPAGE_LO 264
K_MAX_WRITE_DELAY
#define K_MAX_WRITE_DELAY 294
K_MCU_BASE
#define K_MCU_BASE 295
K_MEMORY
#define K_MEMORY 270
K_MIN_WRITE_DELAY
#define K_MIN_WRITE_DELAY 296
K_MISO
#define K_MISO 297
K_MODE
#define K_MODE 344
K_MOSI
#define K_MOSI 298
K_NO
#define K_NO 331
K_NUM_PAGES
return K_NUM_PAGES 299
K_NVM_BASE
#define K_NVM_BASE 300
K_OCDREV
#define K_OCDREV 301
K_OFFSET
#define K_OFFSET 302
K_PAGE_SIZE
return K_PAGE_SIZE 271
K_PAGED
return K_PAGED 272
K_PAGEL
#define K_PAGEL 303
K_PARALLEL
#define K_PARALLEL 304
K_PARENT
#define K_PARENT 305
K_PART
#define K_PART 306
K_PGM_ENABLE
#define K_PGM_ENABLE 269
K_PGMLED
#define K_PGMLED 307
K_POLLINDEX
#define K_POLLINDEX 340
K_POLLMETHOD
#define K_POLLMETHOD 343
K_POLLVALUE
#define K_POLLVALUE 339
K_POSTDELAY
#define K_POSTDELAY 342
K_POWEROFFDELAY
#define K_POWEROFFDELAY 352
K_PP_CONTROLSTACK
#define K_PP_CONTROLSTACK 366
K_PREDELAY
#define K_PREDELAY 341
K_PROGMODEDELAY
#define K_PROGMODEDELAY 349
K_PROGRAMFUSEPOLLTIMEOUT
#define K_PROGRAMFUSEPOLLTIMEOUT 363
K_PROGRAMFUSEPULSEWIDTH
#define K_PROGRAMFUSEPULSEWIDTH 362
K_PROGRAMLOCKPOLLTIMEOUT
#define K_PROGRAMLOCKPOLLTIMEOUT 365
K_PROGRAMLOCKPULSEWIDTH
#define K_PROGRAMLOCKPULSEWIDTH 364
K_PROGRAMMER
#define K_PROGRAMMER 308
K_PSEUDO
#define K_PSEUDO 309
K_PWROFF_AFTER_WRITE
#define K_PWROFF_AFTER_WRITE 310
K_RAMPZ
#define K_RAMPZ 377
K_RDYLED
#define K_RDYLED 311
K_READ
#define K_READ 258
K_READ_HI
#define K_READ_HI 261
K_READ_LO
#define K_READ_LO 260
K_READBACK_P1
#define K_READBACK_P1 312
K_READBACK_P2
#define K_READBACK_P2 313
K_READMEM
#define K_READMEM 314
K_READSIZE
#define K_READSIZE 347
K_RESET
#define K_RESET 315
K_RESETDELAY
#define K_RESETDELAY 356
K_RESETDELAYMS
#define K_RESETDELAYMS 353
K_RESETDELAYUS
#define K_RESETDELAYUS 354
K_RETRY_PULSE
#define K_RETRY_PULSE 316
K_SCK
#define K_SCK 318
K_SERIAL
#define K_SERIAL 317
K_SIGNATURE
#define K_SIGNATURE 319
K_SIZE
#define K_SIZE 320
K_SPMCR
#define K_SPMCR 378
K_STABDELAY
#define K_STABDELAY 334
K_STK500_DEVCODE
#define K_STK500_DEVCODE 286
K_SYNCHCYCLES
#define K_SYNCHCYCLES 357
K_SYNCHLOOPS
#define K_SYNCHLOOPS 337
K_TIMEOUT
#define K_TIMEOUT 333
K_TOGGLEVTG
#define K_TOGGLEVTG 351
K_TYPE
#define K_TYPE 328
K_USB
#define K_USB 321
K_USBDEV
#define K_USBDEV 322
K_USBPID
#define K_USBPID 324
K_USBPRODUCT
#define K_USBPRODUCT 325
K_USBSN
#define K_USBSN 323
K_USBVENDOR
#define K_USBVENDOR 326
K_USBVID
#define K_USBVID 327
K_VCC
#define K_VCC 329
K_VFYLED
#define K_VFYLED 330
K_WRITE
#define K_WRITE 259
K_WRITE_HI
#define K_WRITE_HI 263
K_WRITE_LO
#define K_WRITE_LO 262
K_WRITEPAGE
#define K_WRITEPAGE 267
K_YES
#define K_YES 332
STRINGIFY
#define STRINGIFY (x) #x
TKN_COMMA
#define TKN_COMMA 382
TKN_EQUAL
#define TKN_EQUAL 383
TKN_LEFT_PAREN
#define TKN_LEFT_PAREN 386
TKN_NUMBER
#define TKN_NUMBER 388
TKN_NUMBER_REAL
#define TKN_NUMBER_REAL 389
TKN_RIGHT_PAREN
#define TKN_RIGHT_PAREN 387
TKN_SEMI
#define TKN_SEMI 384
TKN_STRING
#define TKN_STRING 390
TKN_TILDE
#define TKN_TILDE 385
TOSTRING
#define TOSTRING (x) STRINGIFY(x)
YY_
#define YY_ (Msgid) Msgid
YY_ATTRIBUTE
#define YY_ATTRIBUTE (Spec) /* empty */
YY_ATTRIBUTE_PURE
#define YY_ATTRIBUTE_PURE YY_ATTRIBUTE ((__pure__))
YY_ATTRIBUTE_UNUSED
#define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
YY_INITIAL_VALUE
#define YY_INITIAL_VALUE (Value) Value
YY_NULLPTR
#define YY_NULLPTR 0
YY_REDUCE_PRINT
#define YY_REDUCE_PRINT (Rule)
YY_STACK_PRINT
#define YY_STACK_PRINT (Bottom, Top)
YY_SYMBOL_PRINT
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
YY_YY_CONFIG_GRAM_H_INCLUDED
#define YY_YY_CONFIG_GRAM_H_INCLUDED
YYABORT
#define YYABORT goto yyabortlab
YYACCEPT
#define YYACCEPT goto yyacceptlab
YYBACKUP
#define YYBACKUP (Token, Value)
Value:
do                                                              \
  if (yychar == YYEMPTY)                                        \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (yylen);                                       \
      yystate = *yyssp;                                         \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (0)
YYBISON
#define YYBISON 1
YYBISON_VERSION
#define YYBISON_VERSION "3.0.4"
yyclearin
#define yyclearin (yychar = YYEMPTY)
YYCOPY_NEEDED
#define YYCOPY_NEEDED 1
YYDEBUG
#define YYDEBUG 0
YYDPRINTF
#define YYDPRINTF (Args)
YYEMPTY
#define YYEMPTY (-2)
YYEOF
#define YYEOF 0
YYERRCODE
#define YYERRCODE 256
yyerrok
#define yyerrok (yyerrstatus = 0)
YYERROR
#define YYERROR goto yyerrorlab
YYERROR_VERBOSE
#define YYERROR_VERBOSE 0
YYFINAL
#define YYFINAL 22
YYFREE
#define YYFREE free
YYINITDEPTH
#define YYINITDEPTH 200
YYLAST
#define YYLAST 401
YYMALLOC
#define YYMALLOC malloc
YYMAXDEPTH
#define YYMAXDEPTH 10000
YYMAXUTOK
#define YYMAXUTOK 390
YYNNTS
#define YYNNTS 45
YYNRULES
#define YYNRULES 182
YYNSTATES
#define YYNSTATES 418
YYNTOKENS
#define YYNTOKENS 136
YYPACT_NINF
#define YYPACT_NINF -258
yypact_value_is_default
#define yypact_value_is_default (Yystate) (!!((Yystate) == (-258)))
YYPOPSTACK
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
YYPULL
#define YYPULL 1
YYPURE
#define YYPURE 0
YYPUSH
#define YYPUSH 0
YYRECOVERING
#define YYRECOVERING () (!!yyerrstatus)
YYSIZE_MAXIMUM
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
YYSIZE_T
#define YYSIZE_T size_t
YYSKELETON_NAME
#define YYSKELETON_NAME "yacc.c"
YYSTACK_ALLOC
#define YYSTACK_ALLOC YYMALLOC
YYSTACK_ALLOC_MAXIMUM
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
YYSTACK_BYTES
#define YYSTACK_BYTES (N)
Value:
     ((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
YYSTACK_FREE
#define YYSTACK_FREE YYFREE
YYSTACK_GAP_MAXIMUM
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
YYSTACK_RELOCATE
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
    do                                                                  \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (0)
YYTABLE_NINF
#define YYTABLE_NINF -1
yytable_value_is_error
#define yytable_value_is_error (Yytable_value) 0
YYTERROR
#define YYTERROR 1
YYTOKENTYPE
#define YYTOKENTYPE
YYTRANSLATE
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
YYUNDEFTOK
#define YYUNDEFTOK 2
YYUSE
#define YYUSE (E) ((void) (E))
Typedef Documentation
yytype_int16
typedef short int yytype_int16
yytype_int8
typedef signed char yytype_int8
yytype_uint16
typedef unsigned short int yytype_uint16
yytype_uint8
typedef unsigned char yytype_uint8
Enumeration Type Documentation
yytokentype
enum yytokentype
Enumerator
K_READ
K_WRITE
K_READ_LO
K_READ_HI
K_WRITE_LO
K_WRITE_HI
K_LOADPAGE_LO
K_LOADPAGE_HI
K_LOAD_EXT_ADDR
K_WRITEPAGE
K_CHIP_ERASE
K_PGM_ENABLE
K_MEMORY
K_PAGE_SIZE
K_PAGED
K_BAUDRATE
K_BS2
K_BUFF
K_CHIP_ERASE_DELAY
K_CONNTYPE
K_DEDICATED
K_DEFAULT_BITCLOCK
K_DEFAULT_PARALLEL
K_DEFAULT_PROGRAMMER
K_DEFAULT_SAFEMODE
K_DEFAULT_SERIAL
K_DESC
K_DEVICECODE
K_STK500_DEVCODE
K_AVR910_DEVCODE
K_EEPROM
K_ERRLED
K_FLASH
K_ID
K_IO
K_LOADPAGE
K_MAX_WRITE_DELAY
K_MCU_BASE
K_MIN_WRITE_DELAY
K_MISO
K_MOSI
K_NUM_PAGES
K_NVM_BASE
K_OCDREV
K_OFFSET
K_PAGEL
K_PARALLEL
K_PARENT
K_PART
K_PGMLED
K_PROGRAMMER
K_PSEUDO
K_PWROFF_AFTER_WRITE
K_RDYLED
K_READBACK_P1
K_READBACK_P2
K_READMEM
K_RESET
K_RETRY_PULSE
K_SERIAL
K_SCK
K_SIGNATURE
K_SIZE
K_USB
K_USBDEV
K_USBSN
K_USBPID
K_USBPRODUCT
K_USBVENDOR
K_USBVID
K_TYPE
K_VCC
K_VFYLED
K_NO
K_YES
K_TIMEOUT
K_STABDELAY
K_CMDEXEDELAY
K_HVSPCMDEXEDELAY
K_SYNCHLOOPS
K_BYTEDELAY
K_POLLVALUE
K_POLLINDEX
K_PREDELAY
K_POSTDELAY
K_POLLMETHOD
K_MODE
K_DELAY
K_BLOCKSIZE
K_READSIZE
K_HVENTERSTABDELAY
K_PROGMODEDELAY
K_LATCHCYCLES
K_TOGGLEVTG
K_POWEROFFDELAY
K_RESETDELAYMS
K_RESETDELAYUS
K_HVLEAVESTABDELAY
K_RESETDELAY
K_SYNCHCYCLES
K_HVCMDEXEDELAY
K_CHIPERASEPULSEWIDTH
K_CHIPERASEPOLLTIMEOUT
K_CHIPERASETIME
K_PROGRAMFUSEPULSEWIDTH
K_PROGRAMFUSEPOLLTIMEOUT
K_PROGRAMLOCKPULSEWIDTH
K_PROGRAMLOCKPOLLTIMEOUT
K_PP_CONTROLSTACK
K_HVSP_CONTROLSTACK
K_ALLOWFULLPAGEBITSTREAM
K_ENABLEPAGEPROGRAMMING
K_HAS_JTAG
K_HAS_DW
K_HAS_PDI
K_HAS_TPI
K_IDR
K_IS_AT90S1200
K_IS_AVR32
K_RAMPZ
K_SPMCR
K_EECR
K_FLASH_INSTR
K_EEPROM_INSTR
TKN_COMMA
TKN_EQUAL
TKN_SEMI
TKN_TILDE
TKN_LEFT_PAREN
TKN_RIGHT_PAREN
TKN_NUMBER
TKN_NUMBER_REAL
TKN_STRING
  {
    K_READ = 258,
    K_WRITE = 259,
    K_READ_LO = 260,
    K_READ_HI = 261,
    K_WRITE_LO = 262,
    K_WRITE_HI = 263,
    K_LOADPAGE_LO = 264,
    K_LOADPAGE_HI = 265,
    K_LOAD_EXT_ADDR = 266,
    K_WRITEPAGE = 267,
    K_CHIP_ERASE = 268,
    K_PGM_ENABLE = 269,
    K_MEMORY = 270,
    K_PAGE_SIZE = 271,
    K_PAGED = 272,
    K_BAUDRATE = 273,
    K_BS2 = 274,
    K_BUFF = 275,
    K_CHIP_ERASE_DELAY = 276,
    K_CONNTYPE = 277,
    K_DEDICATED = 278,
    K_DEFAULT_BITCLOCK = 279,
    K_DEFAULT_PARALLEL = 280,
    K_DEFAULT_PROGRAMMER = 281,
    K_DEFAULT_SAFEMODE = 282,
    K_DEFAULT_SERIAL = 283,
    K_DESC = 284,
    K_DEVICECODE = 285,
    K_STK500_DEVCODE = 286,
    K_AVR910_DEVCODE = 287,
    K_EEPROM = 288,
    K_ERRLED = 289,
    K_FLASH = 290,
    K_ID = 291,
    K_IO = 292,
    K_LOADPAGE = 293,
    K_MAX_WRITE_DELAY = 294,
    K_MCU_BASE = 295,
    K_MIN_WRITE_DELAY = 296,
    K_MISO = 297,
    K_MOSI = 298,
    K_NUM_PAGES = 299,
    K_NVM_BASE = 300,
    K_OCDREV = 301,
    K_OFFSET = 302,
    K_PAGEL = 303,
    K_PARALLEL = 304,
    K_PARENT = 305,
    K_PART = 306,
    K_PGMLED = 307,
    K_PROGRAMMER = 308,
    K_PSEUDO = 309,
    K_PWROFF_AFTER_WRITE = 310,
    K_RDYLED = 311,
    K_READBACK_P1 = 312,
    K_READBACK_P2 = 313,
    K_READMEM = 314,
    K_RESET = 315,
    K_RETRY_PULSE = 316,
    K_SERIAL = 317,
    K_SCK = 318,
    K_SIGNATURE = 319,
    K_SIZE = 320,
    K_USB = 321,
    K_USBDEV = 322,
    K_USBSN = 323,
    K_USBPID = 324,
    K_USBPRODUCT = 325,
    K_USBVENDOR = 326,
    K_USBVID = 327,
    K_TYPE = 328,
    K_VCC = 329,
    K_VFYLED = 330,
    K_NO = 331,
    K_YES = 332,
    K_TIMEOUT = 333,
    K_STABDELAY = 334,
    K_CMDEXEDELAY = 335,
    K_HVSPCMDEXEDELAY = 336,
    K_SYNCHLOOPS = 337,
    K_BYTEDELAY = 338,
    K_POLLVALUE = 339,
    K_POLLINDEX = 340,
    K_PREDELAY = 341,
    K_POSTDELAY = 342,
    K_POLLMETHOD = 343,
    K_MODE = 344,
    K_DELAY = 345,
    K_BLOCKSIZE = 346,
    K_READSIZE = 347,
    K_HVENTERSTABDELAY = 348,
    K_PROGMODEDELAY = 349,
    K_LATCHCYCLES = 350,
    K_TOGGLEVTG = 351,
    K_POWEROFFDELAY = 352,
    K_RESETDELAYMS = 353,
    K_RESETDELAYUS = 354,
    K_HVLEAVESTABDELAY = 355,
    K_RESETDELAY = 356,
    K_SYNCHCYCLES = 357,
    K_HVCMDEXEDELAY = 358,
    K_CHIPERASEPULSEWIDTH = 359,
    K_CHIPERASEPOLLTIMEOUT = 360,
    K_CHIPERASETIME = 361,
    K_PROGRAMFUSEPULSEWIDTH = 362,
    K_PROGRAMFUSEPOLLTIMEOUT = 363,
    K_PROGRAMLOCKPULSEWIDTH = 364,
    K_PROGRAMLOCKPOLLTIMEOUT = 365,
    K_PP_CONTROLSTACK = 366,
    K_HVSP_CONTROLSTACK = 367,
    K_ALLOWFULLPAGEBITSTREAM = 368,
    K_ENABLEPAGEPROGRAMMING = 369,
    K_HAS_JTAG = 370,
    K_HAS_DW = 371,
    K_HAS_PDI = 372,
    K_HAS_TPI = 373,
    K_IDR = 374,
    K_IS_AT90S1200 = 375,
    K_IS_AVR32 = 376,
    K_RAMPZ = 377,
    K_SPMCR = 378,
    K_EECR = 379,
    K_FLASH_INSTR = 380,
    K_EEPROM_INSTR = 381,
    TKN_COMMA = 382,
    TKN_EQUAL = 383,
    TKN_SEMI = 384,
    TKN_TILDE = 385,
    TKN_LEFT_PAREN = 386,
    TKN_RIGHT_PAREN = 387,
    TKN_NUMBER = 388,
    TKN_NUMBER_REAL = 389,
    TKN_STRING = 390
  };
Function Documentation
assign_pin()
static int assign_pin (int pinno, TOKEN * v, int invert) static
{
  int value;
  value = v->value.number;
  free_token(v);
  if ((value < PIN_MIN) || (value > PIN_MAX)) {
    yyerror("pin must be in the range " TOSTRING(PIN_MIN) "-"  TOSTRING(PIN_MAX));
    return -1;
  }
  pin_set_value(&(current_prog->pin[pinno]), value, invert);
  return 0;
}
References current_prog, free_token(), value_t::number, programmer_t::pin, PIN_MAX, PIN_MIN, pin_set_value(), TOSTRING, token_t::value, and yyerror().
Referenced by yyparse().
assign_pin_list()
static int assign_pin_list (int invert) static
{
  TOKEN * t;
  int pin;
  int rv = 0;
  current_prog->pinno[pin_name] = 0;
  while (lsize(number_list)) {
    t = lrmv_n(number_list, 1);
    if (rv == 0) {
      pin = t->value.number;
      if ((pin < PIN_MIN) || (pin > PIN_MAX)) {
        yyerror("pin must be in the range " TOSTRING(PIN_MIN) "-"  TOSTRING(PIN_MAX));
        rv = -1;
      /* loop clears list and frees tokens */
      }
      pin_set_value(&(current_prog->pin[pin_name]), pin, invert);
    }
    free_token(t);
  }
  return rv;
}
References current_prog, free_token(), lrmv_n(), lsize(), value_t::number, number_list, programmer_t::pin, PIN_MAX, PIN_MIN, pin_name, pin_set_value(), programmer_t::pinno, TOSTRING, token_t::value, and yyerror().
Referenced by yyparse().
free()
void free (void *)
Referenced by Slic3r::GCodeThumbnails::CompressedJPG::~CompressedJPG(), Slic3r::GCodeThumbnails::CompressedQOI::~CompressedQOI(), ExampleAppConsole::~ExampleAppConsole(), _getopt_internal(), igl::ply::ascii_get_element(), avr910_paged_write(), avr910_teardown(), avr_display(), avr_free_mem(), avr_free_opcode(), avr_free_part(), buspirate_teardown(), butterfly_paged_write(), butterfly_teardown(), ExampleAppConsole::ClearLog(), cmd_dump(), cmd_write(), igl::opengl::ViewerCore::draw_buffer(), ExampleAppConsole::ExecCommand(), free_hid_device(), free_token(), free_update(), FreeWrapper(), get_device_string(), priv::get_glyph(), Slic3r::GUI::get_unique_id(), CurvatureCalculator::getKRing(), CurvatureCalculator::getSphere(), igl::opengl::gliReadTGA(), igl::guess_extension(), hid_close(), hid_enumerate(), hid_free_enumeration(), hid_open_path(), hid_write(), jtag3_chip_erase(), jtag3_close(), jtag3_command(), jtag3_disable(), jtag3_display(), jtag3_edbg_recv_frame(), jtag3_getparm(), jtag3_getsync(), jtag3_initialize(), jtag3_page_erase(), jtag3_paged_load(), jtag3_paged_write(), jtag3_program_disable(), jtag3_program_enable(), jtag3_read_byte(), jtag3_recv(), jtag3_recv_frame(), jtag3_send(), jtag3_setparm(), jtag3_teardown(), jtag3_write_byte(), jtagmkI_disable(), jtagmkI_initialize(), jtagmkI_paged_write(), jtagmkI_send(), jtagmkI_teardown(), jtagmkII_chip_erase(), jtagmkII_chip_erase32(), jtagmkII_close(), jtagmkII_close32(), jtagmkII_disable(), jtagmkII_getparm(), jtagmkII_getsync(), jtagmkII_initialize(), jtagmkII_initialize32(), jtagmkII_open32(), jtagmkII_page_erase(), jtagmkII_paged_load(), jtagmkII_paged_load32(), jtagmkII_paged_write(), jtagmkII_paged_write32(), jtagmkII_program_disable(), jtagmkII_program_enable(), jtagmkII_read_byte(), jtagmkII_read_SABaddr(), jtagmkII_recv(), jtagmkII_recv_frame(), jtagmkII_reset(), jtagmkII_send(), jtagmkII_set_devdescr(), jtagmkII_set_xmega_params(), jtagmkII_setparm(), jtagmkII_teardown(), jtagmkII_write_byte(), net_open(), Slic3r::GUI::BitmapCache::nsvgGetDataFromFileWithReplace(), Slic3r::GUI::BitmapCache::nsvgParseFromFileWithReplace(), parse_op(), parse_uevent_info(), pgm_free(), igl::ply::ply_close(), igl::ply::ply_read(), igl::opengl::print_program_info_log(), igl::opengl::print_shader_info_log(), igl::opengl::render_to_tga(), return_data(), semver_free(), semver_parse(), Slic3r::Semver::set_metadata(), Slic3r::Semver::set_metadata(), Slic3r::Semver::set_prerelease(), Slic3r::Semver::set_prerelease(), stk500_teardown(), stk500hv_disable(), stk500hv_initialize(), stk500v2_initialize(), stk500v2_jtag3_disable(), stk500v2_teardown(), stk600_xprog_command(), stk600_xprog_paged_load(), stk600_xprog_paged_write(), terminal_mode(), tokenize(), igl::triangle::triangulate(), utf8_to_wstr(), wiring_teardown(), Slic3r::GCode::GCodeOutputStream::write_format(), wstr_to_utf8(), and yyparse().
malloc()
void * malloc (YYSIZE_T)
Referenced by _getopt_initialize(), avr910_paged_write(), avr910_setup(), avr_display(), avr_dup_mem(), avr_dup_opcode(), avr_initmem(), avr_new_memtype(), avr_new_opcode(), avr_new_part(), butterfly_paged_write(), butterfly_setup(), cmd_dump(), cmd_write(), Slic3r::GCodeThumbnails::compress_thumbnail_jpg(), dup_update(), dup_wcs(), exchange(), Slic3r::GUI::get_unique_id(), igl::opengl::gliReadTGA(), hid_enumerate(), hid_open_path(), hid_write(), jtag3_edbg_recv_frame(), jtag3_initialize(), jtag3_paged_write(), jtag3_recv_frame(), jtag3_send(), jtag3_setparm(), jtag3_setup(), jtagmkI_initialize(), jtagmkI_paged_write(), jtagmkI_send(), jtagmkI_setup(), jtagmkII_initialize(), jtagmkII_initialize32(), jtagmkII_paged_write(), jtagmkII_paged_write32(), jtagmkII_recv_frame(), jtagmkII_send(), jtagmkII_setup(), MallocWrapper(), igl::ply::my_alloc(), new_token(), new_update(), Slic3r::GUI::BitmapCache::nsvgGetDataFromFileWithReplace(), Slic3r::GUI::BitmapCache::nsvgParseFromFileWithReplace(), parse_op(), pgm_dup(), pgm_new(), igl::ply::ply_get_other_element(), igl::opengl::print_program_info_log(), igl::opengl::print_shader_info_log(), igl::opengl::render_to_tga(), rle_fread(), semver_strdup(), stk500_setup(), stk500hv_initialize(), stk500v2_initialize(), stk500v2_setup(), stk600_xprog_command(), stk600_xprog_paged_load(), stk600_xprog_paged_write(), ExampleAppConsole::Strdup(), string(), tokenize(), utf8_to_wstr(), wiring_setup(), Slic3r::GCode::GCodeOutputStream::write_format(), wstr_to_utf8(), and yyparse().
parse_cmdbits()
static int parse_cmdbits (OPCODE * op) static
{
  TOKEN * t;
  int bitno;
  char ch;
  char * e;
  char * q;
  int len;
  char * s, *brkt = NULL;
  int rv = 0;
  bitno = 32;
  while (lsize(string_list)) {
    t = lrmv_n(string_list, 1);
    s = strtok_r(t->value.string, " ", &brkt);
    while (rv == 0 && s != NULL) {
      bitno--;
      if (bitno < 0) {
        yyerror("too many opcode bits for instruction");
        rv = -1;
        break;
      }
      len = (int)strlen(s);
      if (len == 0) {
        yyerror("invalid bit specifier \"\"");
        rv = -1;
        break;
      }
      ch = s[0];
      if (len == 1) {
        switch (ch) {
          case '1':
            op->bit[bitno].type  = AVR_CMDBIT_VALUE;
            op->bit[bitno].value = 1;
            op->bit[bitno].bitno = bitno % 8;
            break;
          case '0':
            op->bit[bitno].type  = AVR_CMDBIT_VALUE;
            op->bit[bitno].value = 0;
            op->bit[bitno].bitno = bitno % 8;
            break;
          case 'x':
            op->bit[bitno].type  = AVR_CMDBIT_IGNORE;
            op->bit[bitno].value = 0;
            op->bit[bitno].bitno = bitno % 8;
            break;
          case 'a':
            op->bit[bitno].type  = AVR_CMDBIT_ADDRESS;
            op->bit[bitno].value = 0;
            op->bit[bitno].bitno = 8*(bitno/8) + bitno % 8;
            break;
          case 'i':
            op->bit[bitno].type  = AVR_CMDBIT_INPUT;
            op->bit[bitno].value = 0;
            op->bit[bitno].bitno = bitno % 8;
            break;
          case 'o':
            op->bit[bitno].type  = AVR_CMDBIT_OUTPUT;
            op->bit[bitno].value = 0;
            op->bit[bitno].bitno = bitno % 8;
            break;
          default :
            yyerror("invalid bit specifier '%c'", ch);
            rv = -1;
            break;
        }
      }
      else {
        if (ch == 'a') {
          q = &s[1];
          op->bit[bitno].bitno = strtol(q, &e, 0);
          if ((e == q)||(*e != 0)) {
            yyerror("can't parse bit number from \"%s\"", q);
            rv = -1;
            break;
          }
          op->bit[bitno].type = AVR_CMDBIT_ADDRESS;
          op->bit[bitno].value = 0;
        }
        else {
          yyerror("invalid bit specifier \"%s\"", s);
          rv = -1;
          break;
        }
      }
      s = strtok_r(NULL, " ", &brkt);
    } /* while */
    free_token(t);
  }  /* while */
  return rv;
}
References AVR_CMDBIT_ADDRESS, AVR_CMDBIT_IGNORE, AVR_CMDBIT_INPUT, AVR_CMDBIT_OUTPUT, AVR_CMDBIT_VALUE, opcode::bit, cmdbit::bitno, free_token(), lrmv_n(), lsize(), value_t::string, string_list, cmdbit::type, token_t::value, cmdbit::value, and yyerror().
Referenced by yyparse().
which_opcode()
static int which_opcode (TOKEN * opcode) static
{
  switch (opcode->primary) {
    case K_READ        : return AVR_OP_READ; break;
    case K_WRITE       : return AVR_OP_WRITE; break;
    case K_READ_LO     : return AVR_OP_READ_LO; break;
    case K_READ_HI     : return AVR_OP_READ_HI; break;
    case K_WRITE_LO    : return AVR_OP_WRITE_LO; break;
    case K_WRITE_HI    : return AVR_OP_WRITE_HI; break;
    case K_LOADPAGE_LO : return AVR_OP_LOADPAGE_LO; break;
    case K_LOADPAGE_HI : return AVR_OP_LOADPAGE_HI; break;
    case K_LOAD_EXT_ADDR : return AVR_OP_LOAD_EXT_ADDR; break;
    case K_WRITEPAGE   : return AVR_OP_WRITEPAGE; break;
    case K_CHIP_ERASE  : return AVR_OP_CHIP_ERASE; break;
    case K_PGM_ENABLE  : return AVR_OP_PGM_ENABLE; break;
    default :
      yyerror("invalid opcode");
      return -1;
      break;
  }
}
References AVR_OP_CHIP_ERASE, AVR_OP_LOAD_EXT_ADDR, AVR_OP_LOADPAGE_HI, AVR_OP_LOADPAGE_LO, AVR_OP_PGM_ENABLE, AVR_OP_READ, AVR_OP_READ_HI, AVR_OP_READ_LO, AVR_OP_WRITE, AVR_OP_WRITE_HI, AVR_OP_WRITE_LO, AVR_OP_WRITEPAGE, K_CHIP_ERASE, K_LOAD_EXT_ADDR, K_LOADPAGE_HI, K_LOADPAGE_LO, K_PGM_ENABLE, K_READ, K_READ_HI, K_READ_LO, K_WRITE, K_WRITE_HI, K_WRITE_LO, K_WRITEPAGE, and yyerror().
Referenced by yyparse().
yydestruct()
static void yydestruct (const char * yymsg, int yytype, YYSTYPE * yyvaluep) static
{
  YYUSE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YYUSE (yytype);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}
References YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_SYMBOL_PRINT, and YYUSE.
Referenced by yyparse().
yyerror()
int yyerror (char * errmsg, ...)
{
  va_list args;
  char message[512];
  va_start(args, errmsg);
  vsnprintf(message, sizeof(message), errmsg, args);
  avrdude_message(MSG_INFO, "%s: error at %s:%d: %s\n", progname, infile, lineno, message);
  va_end(args);
  return 0;
}
References avrdude_message(), infile, lineno, MSG_INFO, and progname.
Referenced by assign_pin(), assign_pin_list(), dup_string(), hexnumber(), new_token(), parse_cmdbits(), string(), which_opcode(), and yyparse().
yylex()
int yylex (void)
 {SIGN}*{DIGIT}+            { yylval = number(yytext); return TKN_NUMBER; }
#{SIGN}*{DIGIT}+"."{DIGIT}* { yylval = number_real(yytext); return TKN_NUMBER_REAL; }
#{SIGN}*"."{DIGIT}*         { yylval = number_real(yytext); return TKN_NUMBER_REAL; }
{DIGIT}+            { yylval = number(yytext); return TKN_NUMBER; }
{DIGIT}+"."{DIGIT}* { yylval = number_real(yytext); return TKN_NUMBER_REAL; }
"."{DIGIT}+         { yylval = number_real(yytext); return TKN_NUMBER_REAL; }
"\""      { string_buf_ptr = string_buf; BEGIN(strng); }
0x{HEXDIGIT}+ { yylval = hexnumber(yytext); return TKN_NUMBER; }
#   { /* The following eats '#' style comments to end of line */
       BEGIN(comment); }
Referenced by yyparse().
yyparse()
int yyparse (void)
{
    int yystate;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus;
    /* The stacks and their tools:
       'yyss': related to states.
       'yyvs': related to semantic values.
       Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */
    /* The state stack.  */
    yytype_int16 yyssa[YYINITDEPTH];
    yytype_int16 *yyss;
    yytype_int16 *yyssp;
    /* The semantic value stack.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs;
    YYSTYPE *yyvsp;
    YYSIZE_T yystacksize;
  int yyn;
  int yyresult;
  /* Lookahead token as an internal (translated) token number.  */
  int yytoken = 0;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;
#if YYERROR_VERBOSE
  /* Buffer for error messages, and its allocated size.  */
  char yymsgbuf[128];
  char *yymsg = yymsgbuf;
  YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
#endif
#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;
  yyssp = yyss = yyssa;
  yyvsp = yyvs = yyvsa;
  yystacksize = YYINITDEPTH;
  YYDPRINTF ((stderr, "Starting parse\n"));
  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY; /* Cause a token to be read.  */
  goto yysetstate;
/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;
 yysetstate:
  *yyssp = yystate;
  if (yyss + yystacksize - 1 <= yyssp)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;
#ifdef yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        YYSTYPE *yyvs1 = yyvs;
        yytype_int16 *yyss1 = yyss;
        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * sizeof (*yyssp),
                    &yyvs1, yysize * sizeof (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyexhaustedlab;
# else
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        goto yyexhaustedlab;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;
      {
        yytype_int16 *yyss1 = yyss;
        union yyalloc *yyptr =
          (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
        if (! yyptr)
          goto yyexhaustedlab;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */
      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;
      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                  (unsigned long int) yystacksize));
      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  if (yystate == YYFINAL)
    YYACCEPT;
  goto yybackup;
/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */
  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;
  /* Not known => get a lookahead token if don't already have one.  */
  /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = yylex ();
    }
  if (yychar <= YYEOF)
    {
      yychar = yytoken = YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }
  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }
  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;
  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END
  goto yynewstate;
/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;
/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];
  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.
     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];
  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
        case 2:
#line 211 "config_gram.y" /* yacc.c:1646  */
    {
    (yyval) = (yyvsp[0]);
    /* convert value to real */
    (yyval)->value.number_real = (yyval)->value.number;
    (yyval)->value.type = V_NUM_REAL;
  }
#line 1819 "config_gram.c" /* yacc.c:1646  */
    break;
  case 3:
#line 217 "config_gram.y" /* yacc.c:1646  */
    {
    (yyval) = (yyvsp[0]);
  }
#line 1827 "config_gram.c" /* yacc.c:1646  */
    break;
  case 10:
#line 236 "config_gram.y" /* yacc.c:1646  */
    {
    strncpy(default_programmer, (yyvsp[-1])->value.string, MAX_STR_CONST);
    default_programmer[MAX_STR_CONST-1] = 0;
    free_token((yyvsp[-1]));
  }
#line 1837 "config_gram.c" /* yacc.c:1646  */
    break;
  case 11:
#line 242 "config_gram.y" /* yacc.c:1646  */
    {
    strncpy(default_parallel, (yyvsp[-1])->value.string, PATH_MAX);
    default_parallel[PATH_MAX-1] = 0;
    free_token((yyvsp[-1]));
  }
#line 1847 "config_gram.c" /* yacc.c:1646  */
    break;
  case 12:
#line 248 "config_gram.y" /* yacc.c:1646  */
    {
    strncpy(default_serial, (yyvsp[-1])->value.string, PATH_MAX);
    default_serial[PATH_MAX-1] = 0;
    free_token((yyvsp[-1]));
  }
#line 1857 "config_gram.c" /* yacc.c:1646  */
    break;
  case 13:
#line 254 "config_gram.y" /* yacc.c:1646  */
    {
    default_bitclock = (yyvsp[-1])->value.number_real;
    free_token((yyvsp[-1]));
  }
#line 1866 "config_gram.c" /* yacc.c:1646  */
    break;
  case 14:
#line 259 "config_gram.y" /* yacc.c:1646  */
    {
    if ((yyvsp[-1])->primary == K_YES)
      default_safemode = 1;
    else if ((yyvsp[-1])->primary == K_NO)
      default_safemode = 0;
    free_token((yyvsp[-1]));
  }
#line 1878 "config_gram.c" /* yacc.c:1646  */
    break;
  case 15:
#line 271 "config_gram.y" /* yacc.c:1646  */
    {
      PROGRAMMER * existing_prog;
      char * id;
      if (lsize(current_prog->id) == 0) {
        yyerror("required parameter id not specified");
        YYABORT;
      }
      if (current_prog->initpgm == NULL) {
        yyerror("programmer type not specified");
        YYABORT;
      }
      id = ldata(lfirst(current_prog->id));
      existing_prog = locate_programmer(programmers, id);
      if (existing_prog) {
        { /* temporarly set lineno to lineno of programmer start */
          int temp = lineno; lineno = current_prog->lineno;
          yywarning("programmer %s overwrites previous definition %s:%d.",
                id, existing_prog->config_file, existing_prog->lineno);
          lineno = temp;
        }
        lrmv_d(programmers, existing_prog);
        pgm_free(existing_prog);
      }
      PUSH(programmers, current_prog);
//      pgm_fill_old_pins(current_prog); // TODO to be removed if old pin data no longer needed
//      pgm_display_generic(current_prog, id);
      current_prog = NULL;
    }
#line 1911 "config_gram.c" /* yacc.c:1646  */
    break;
  case 16:
#line 304 "config_gram.y" /* yacc.c:1646  */
    { current_prog = pgm_new();
      if (current_prog == NULL) {
        yyerror("could not create pgm instance");
        YYABORT;
      }
      strcpy(current_prog->config_file, infile);
      current_prog->lineno = lineno;
    }
#line 1924 "config_gram.c" /* yacc.c:1646  */
    break;
  case 17:
#line 314 "config_gram.y" /* yacc.c:1646  */
    {
      struct programmer_t * pgm = locate_programmer(programmers, (yyvsp[0])->value.string);
      if (pgm == NULL) {
        yyerror("parent programmer %s not found", (yyvsp[0])->value.string);
        free_token((yyvsp[0]));
        YYABORT;
      }
      current_prog = pgm_dup(pgm);
      if (current_prog == NULL) {
        yyerror("could not duplicate pgm instance");
        free_token((yyvsp[0]));
        YYABORT;
      }
      strcpy(current_prog->config_file, infile);
      current_prog->lineno = lineno;
      free_token((yyvsp[0]));
    }
#line 1946 "config_gram.c" /* yacc.c:1646  */
    break;
  case 18:
#line 336 "config_gram.y" /* yacc.c:1646  */
    {
      LNODEID ln;
      AVRMEM * m;
      AVRPART * existing_part;
      if (current_part->id[0] == 0) {
        yyerror("required parameter id not specified");
        YYABORT;
      }
      /*
       * perform some sanity checking, and compute the number of bits
       * to shift a page for constructing the page address for
       * page-addressed memories.
       */
      for (ln=lfirst(current_part->mem); ln; ln=lnext(ln)) {
        m = ldata(ln);
        if (m->paged) {
          if (m->page_size == 0) {
            yyerror("must specify page_size for paged memory");
            YYABORT;
          }
          if (m->num_pages == 0) {
            yyerror("must specify num_pages for paged memory");
            YYABORT;
          }
          if (m->size != m->page_size * m->num_pages) {
            yyerror("page size (%u) * num_pages (%u) = "
                    "%u does not match memory size (%u)",
                    m->page_size,
                    m->num_pages,
                    m->page_size * m->num_pages,
                    m->size);
            YYABORT;
          }
        }
      }
      existing_part = locate_part(part_list, current_part->id);
      if (existing_part) {
        { /* temporarly set lineno to lineno of part start */
          int temp = lineno; lineno = current_part->lineno;
          yywarning("part %s overwrites previous definition %s:%d.",
                current_part->id,
                existing_part->config_file, existing_part->lineno);
          lineno = temp;
        }
        lrmv_d(part_list, existing_part);
        avr_free_part(existing_part);
      }
      PUSH(part_list, current_part);
      current_part = NULL;
    }
#line 2005 "config_gram.c" /* yacc.c:1646  */
    break;
  case 19:
#line 394 "config_gram.y" /* yacc.c:1646  */
    {
      current_part = avr_new_part();
      if (current_part == NULL) {
        yyerror("could not create part instance");
        YYABORT;
      }
      strcpy(current_part->config_file, infile);
      current_part->lineno = lineno;
    }
#line 2019 "config_gram.c" /* yacc.c:1646  */
    break;
  case 20:
#line 404 "config_gram.y" /* yacc.c:1646  */
    {
      AVRPART * parent_part = locate_part(part_list, (yyvsp[0])->value.string);
      if (parent_part == NULL) {
        yyerror("can't find parent part");
        free_token((yyvsp[0]));
        YYABORT;
      }
      current_part = avr_dup_part(parent_part);
      if (current_part == NULL) {
        yyerror("could not duplicate part instance");
        free_token((yyvsp[0]));
        YYABORT;
      }
      strcpy(current_part->config_file, infile);
      current_part->lineno = lineno;
      free_token((yyvsp[0]));
    }
#line 2043 "config_gram.c" /* yacc.c:1646  */
    break;
  case 21:
#line 426 "config_gram.y" /* yacc.c:1646  */
    { ladd(string_list, (yyvsp[0])); }
#line 2049 "config_gram.c" /* yacc.c:1646  */
    break;
  case 22:
#line 427 "config_gram.y" /* yacc.c:1646  */
    { ladd(string_list, (yyvsp[0])); }
#line 2055 "config_gram.c" /* yacc.c:1646  */
    break;
  case 23:
#line 432 "config_gram.y" /* yacc.c:1646  */
    { ladd(number_list, (yyvsp[0])); }
#line 2061 "config_gram.c" /* yacc.c:1646  */
    break;
  case 24:
#line 433 "config_gram.y" /* yacc.c:1646  */
    { ladd(number_list, (yyvsp[0])); }
#line 2067 "config_gram.c" /* yacc.c:1646  */
    break;
  case 27:
#line 442 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      char *s;
      int do_yyabort = 0;
      while (lsize(string_list)) {
        t = lrmv_n(string_list, 1);
        if (!do_yyabort) {
          s = dup_string(t->value.string);
          if (s == NULL) {
            do_yyabort = 1;
          } else {
            ladd(current_prog->id, s);
          }
        }
        /* if do_yyabort == 1 just make the list empty */
        free_token(t);
      }
      if (do_yyabort) {
        YYABORT;
      }
    }
  }
#line 2095 "config_gram.c" /* yacc.c:1646  */
    break;
  case 32:
#line 473 "config_gram.y" /* yacc.c:1646  */
    {
    strncpy(current_prog->desc, (yyvsp[0])->value.string, PGM_DESCLEN);
    current_prog->desc[PGM_DESCLEN-1] = 0;
    free_token((yyvsp[0]));
  }
#line 2105 "config_gram.c" /* yacc.c:1646  */
    break;
  case 33:
#line 478 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_prog->baudrate = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2116 "config_gram.c" /* yacc.c:1646  */
    break;
  case 35:
#line 491 "config_gram.y" /* yacc.c:1646  */
    {
  const struct programmer_type_t * pgm_type = locate_programmer_type((yyvsp[0])->value.string);
    if (pgm_type == NULL) {
        yyerror("programmer type %s not found", (yyvsp[0])->value.string);
        free_token((yyvsp[0]));
        YYABORT;
    }
    current_prog->initpgm = pgm_type->initpgm;
    free_token((yyvsp[0]));
}
#line 2131 "config_gram.c" /* yacc.c:1646  */
    break;
  case 36:
#line 502 "config_gram.y" /* yacc.c:1646  */
    {
        yyerror("programmer type must be written as \"id_type\"");
        YYABORT;
}
#line 2140 "config_gram.c" /* yacc.c:1646  */
    break;
  case 38:
#line 513 "config_gram.y" /* yacc.c:1646  */
    { current_prog->conntype = CONNTYPE_PARALLEL; }
#line 2146 "config_gram.c" /* yacc.c:1646  */
    break;
  case 39:
#line 514 "config_gram.y" /* yacc.c:1646  */
    { current_prog->conntype = CONNTYPE_SERIAL; }
#line 2152 "config_gram.c" /* yacc.c:1646  */
    break;
  case 40:
#line 515 "config_gram.y" /* yacc.c:1646  */
    { current_prog->conntype = CONNTYPE_USB; }
#line 2158 "config_gram.c" /* yacc.c:1646  */
    break;
  case 41:
#line 519 "config_gram.y" /* yacc.c:1646  */
    {
    {
      strncpy(current_prog->usbdev, (yyvsp[0])->value.string, PGM_USBSTRINGLEN);
      current_prog->usbdev[PGM_USBSTRINGLEN-1] = 0;
      free_token((yyvsp[0]));
    }
  }
#line 2170 "config_gram.c" /* yacc.c:1646  */
    break;
  case 42:
#line 526 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_prog->usbvid = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2181 "config_gram.c" /* yacc.c:1646  */
    break;
  case 44:
#line 533 "config_gram.y" /* yacc.c:1646  */
    {
    {
      strncpy(current_prog->usbsn, (yyvsp[0])->value.string, PGM_USBSTRINGLEN);
      current_prog->usbsn[PGM_USBSTRINGLEN-1] = 0;
      free_token((yyvsp[0]));
    }
  }
#line 2193 "config_gram.c" /* yacc.c:1646  */
    break;
  case 45:
#line 540 "config_gram.y" /* yacc.c:1646  */
    {
    {
      strncpy(current_prog->usbvendor, (yyvsp[0])->value.string, PGM_USBSTRINGLEN);
      current_prog->usbvendor[PGM_USBSTRINGLEN-1] = 0;
      free_token((yyvsp[0]));
    }
  }
#line 2205 "config_gram.c" /* yacc.c:1646  */
    break;
  case 46:
#line 547 "config_gram.y" /* yacc.c:1646  */
    {
    {
      strncpy(current_prog->usbproduct, (yyvsp[0])->value.string, PGM_USBSTRINGLEN);
      current_prog->usbproduct[PGM_USBSTRINGLEN-1] = 0;
      free_token((yyvsp[0]));
    }
  }
#line 2217 "config_gram.c" /* yacc.c:1646  */
    break;
  case 47:
#line 557 "config_gram.y" /* yacc.c:1646  */
    {
    {
      /* overwrite pids, so clear the existing entries */
      ldestroy_cb(current_prog->usbpid, free);
      current_prog->usbpid = lcreat(NULL, 0);
    }
    {
      int *ip = malloc(sizeof(int));
      if (ip) {
        *ip = (yyvsp[0])->value.number;
        ladd(current_prog->usbpid, ip);
      }
      free_token((yyvsp[0]));
    }
  }
#line 2237 "config_gram.c" /* yacc.c:1646  */
    break;
  case 48:
#line 572 "config_gram.y" /* yacc.c:1646  */
    {
    {
      int *ip = malloc(sizeof(int));
      if (ip) {
        *ip = (yyvsp[0])->value.number;
        ladd(current_prog->usbpid, ip);
      }
      free_token((yyvsp[0]));
    }
  }
#line 2252 "config_gram.c" /* yacc.c:1646  */
    break;
  case 49:
#line 585 "config_gram.y" /* yacc.c:1646  */
    { if(0 != assign_pin(pin_name, (yyvsp[0]), 0)) YYABORT;  }
#line 2258 "config_gram.c" /* yacc.c:1646  */
    break;
  case 50:
#line 587 "config_gram.y" /* yacc.c:1646  */
    { if(0 != assign_pin(pin_name, (yyvsp[0]), 1)) YYABORT; }
#line 2264 "config_gram.c" /* yacc.c:1646  */
    break;
  case 52:
#line 593 "config_gram.y" /* yacc.c:1646  */
    { pin_clear_all(&(current_prog->pin[pin_name])); }
#line 2270 "config_gram.c" /* yacc.c:1646  */
    break;
  case 54:
#line 599 "config_gram.y" /* yacc.c:1646  */
    { if(0 != assign_pin_list(1)) YYABORT; }
#line 2276 "config_gram.c" /* yacc.c:1646  */
    break;
  case 58:
#line 612 "config_gram.y" /* yacc.c:1646  */
    { pin_clear_all(&(current_prog->pin[pin_name])); }
#line 2282 "config_gram.c" /* yacc.c:1646  */
    break;
  case 59:
#line 616 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PPI_AVR_VCC;  }
#line 2288 "config_gram.c" /* yacc.c:1646  */
    break;
  case 61:
#line 617 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PPI_AVR_BUFF; }
#line 2294 "config_gram.c" /* yacc.c:1646  */
    break;
  case 63:
#line 618 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_AVR_RESET;}
#line 2300 "config_gram.c" /* yacc.c:1646  */
    break;
  case 64:
#line 618 "config_gram.y" /* yacc.c:1646  */
    { free_token((yyvsp[-3])); }
#line 2306 "config_gram.c" /* yacc.c:1646  */
    break;
  case 65:
#line 619 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_AVR_SCK;  }
#line 2312 "config_gram.c" /* yacc.c:1646  */
    break;
  case 66:
#line 619 "config_gram.y" /* yacc.c:1646  */
    { free_token((yyvsp[-3])); }
#line 2318 "config_gram.c" /* yacc.c:1646  */
    break;
  case 67:
#line 620 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_AVR_MOSI; }
#line 2324 "config_gram.c" /* yacc.c:1646  */
    break;
  case 69:
#line 621 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_AVR_MISO; }
#line 2330 "config_gram.c" /* yacc.c:1646  */
    break;
  case 71:
#line 622 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_LED_ERR;  }
#line 2336 "config_gram.c" /* yacc.c:1646  */
    break;
  case 73:
#line 623 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_LED_RDY;  }
#line 2342 "config_gram.c" /* yacc.c:1646  */
    break;
  case 75:
#line 624 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_LED_PGM;  }
#line 2348 "config_gram.c" /* yacc.c:1646  */
    break;
  case 77:
#line 625 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_LED_VFY;  }
#line 2354 "config_gram.c" /* yacc.c:1646  */
    break;
  case 99:
#line 664 "config_gram.y" /* yacc.c:1646  */
    {
      strncpy(current_part->id, (yyvsp[0])->value.string, AVR_IDLEN);
      current_part->id[AVR_IDLEN-1] = 0;
      free_token((yyvsp[0]));
    }
#line 2364 "config_gram.c" /* yacc.c:1646  */
    break;
  case 100:
#line 671 "config_gram.y" /* yacc.c:1646  */
    {
      strncpy(current_part->desc, (yyvsp[0])->value.string, AVR_DESCLEN);
      current_part->desc[AVR_DESCLEN-1] = 0;
      free_token((yyvsp[0]));
    }
#line 2374 "config_gram.c" /* yacc.c:1646  */
    break;
  case 101:
#line 677 "config_gram.y" /* yacc.c:1646  */
    {
    {
      yyerror("devicecode is deprecated, use "
              "stk500_devcode instead");
      YYABORT;
    }
  }
#line 2386 "config_gram.c" /* yacc.c:1646  */
    break;
  case 102:
#line 685 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_part->stk500_devcode = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2397 "config_gram.c" /* yacc.c:1646  */
    break;
  case 103:
#line 692 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_part->avr910_devcode = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2408 "config_gram.c" /* yacc.c:1646  */
    break;
  case 104:
#line 699 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_part->signature[0] = (yyvsp[-2])->value.number;
      current_part->signature[1] = (yyvsp[-1])->value.number;
      current_part->signature[2] = (yyvsp[0])->value.number;
      free_token((yyvsp[-2]));
      free_token((yyvsp[-1]));
      free_token((yyvsp[0]));
    }
  }
#line 2423 "config_gram.c" /* yacc.c:1646  */
    break;
  case 105:
#line 710 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_part->usbpid = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2434 "config_gram.c" /* yacc.c:1646  */
    break;
  case 106:
#line 717 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      unsigned nbytes;
      int ok;
      current_part->ctl_stack_type = CTL_STACK_PP;
      nbytes = 0;
      ok = 1;
      memset(current_part->controlstack, 0, CTL_STACK_SIZE);
      while (lsize(number_list)) {
        t = lrmv_n(number_list, 1);
  if (nbytes < CTL_STACK_SIZE)
    {
      current_part->controlstack[nbytes] = t->value.number;
      nbytes++;
    }
  else
    {
      ok = 0;
    }
        free_token(t);
      }
      if (!ok)
  {
    yywarning("too many bytes in control stack");
        }
    }
  }
#line 2469 "config_gram.c" /* yacc.c:1646  */
    break;
  case 107:
#line 748 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      unsigned nbytes;
      int ok;
      current_part->ctl_stack_type = CTL_STACK_HVSP;
      nbytes = 0;
      ok = 1;
      memset(current_part->controlstack, 0, CTL_STACK_SIZE);
      while (lsize(number_list)) {
        t = lrmv_n(number_list, 1);
  if (nbytes < CTL_STACK_SIZE)
    {
      current_part->controlstack[nbytes] = t->value.number;
      nbytes++;
    }
  else
    {
      ok = 0;
    }
        free_token(t);
      }
      if (!ok)
  {
    yywarning("too many bytes in control stack");
        }
    }
  }
#line 2504 "config_gram.c" /* yacc.c:1646  */
    break;
  case 108:
#line 779 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      unsigned nbytes;
      int ok;
      nbytes = 0;
      ok = 1;
      memset(current_part->flash_instr, 0, FLASH_INSTR_SIZE);
      while (lsize(number_list)) {
        t = lrmv_n(number_list, 1);
  if (nbytes < FLASH_INSTR_SIZE)
    {
      current_part->flash_instr[nbytes] = t->value.number;
      nbytes++;
    }
  else
    {
      ok = 0;
    }
        free_token(t);
      }
      if (!ok)
  {
    yywarning("too many bytes in flash instructions");
        }
    }
  }
#line 2538 "config_gram.c" /* yacc.c:1646  */
    break;
  case 109:
#line 809 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      unsigned nbytes;
      int ok;
      nbytes = 0;
      ok = 1;
      memset(current_part->eeprom_instr, 0, EEPROM_INSTR_SIZE);
      while (lsize(number_list)) {
        t = lrmv_n(number_list, 1);
  if (nbytes < EEPROM_INSTR_SIZE)
    {
      current_part->eeprom_instr[nbytes] = t->value.number;
      nbytes++;
    }
  else
    {
      ok = 0;
    }
        free_token(t);
      }
      if (!ok)
  {
    yywarning("too many bytes in EEPROM instructions");
        }
    }
  }
#line 2572 "config_gram.c" /* yacc.c:1646  */
    break;
  case 110:
#line 840 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->chip_erase_delay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2581 "config_gram.c" /* yacc.c:1646  */
    break;
  case 111:
#line 846 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->pagel = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2590 "config_gram.c" /* yacc.c:1646  */
    break;
  case 112:
#line 852 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->bs2 = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2599 "config_gram.c" /* yacc.c:1646  */
    break;
  case 113:
#line 858 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_DEDICATED)
        current_part->reset_disposition = RESET_DEDICATED;
      else if ((yyvsp[0])->primary == K_IO)
        current_part->reset_disposition = RESET_IO;
      free_tokens(2, (yyvsp[-2]), (yyvsp[0]));
    }
#line 2612 "config_gram.c" /* yacc.c:1646  */
    break;
  case 114:
#line 868 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->timeout = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2621 "config_gram.c" /* yacc.c:1646  */
    break;
  case 115:
#line 874 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->stabdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2630 "config_gram.c" /* yacc.c:1646  */
    break;
  case 116:
#line 880 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->cmdexedelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2639 "config_gram.c" /* yacc.c:1646  */
    break;
  case 117:
#line 886 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->hvspcmdexedelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2648 "config_gram.c" /* yacc.c:1646  */
    break;
  case 118:
#line 892 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->synchloops = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2657 "config_gram.c" /* yacc.c:1646  */
    break;
  case 119:
#line 898 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->bytedelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2666 "config_gram.c" /* yacc.c:1646  */
    break;
  case 120:
#line 904 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->pollvalue = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2675 "config_gram.c" /* yacc.c:1646  */
    break;
  case 121:
#line 910 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->pollindex = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2684 "config_gram.c" /* yacc.c:1646  */
    break;
  case 122:
#line 916 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->predelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2693 "config_gram.c" /* yacc.c:1646  */
    break;
  case 123:
#line 922 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->postdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2702 "config_gram.c" /* yacc.c:1646  */
    break;
  case 124:
#line 928 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->pollmethod = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2711 "config_gram.c" /* yacc.c:1646  */
    break;
  case 125:
#line 934 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->hventerstabdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2720 "config_gram.c" /* yacc.c:1646  */
    break;
  case 126:
#line 940 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->progmodedelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2729 "config_gram.c" /* yacc.c:1646  */
    break;
  case 127:
#line 946 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->latchcycles = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2738 "config_gram.c" /* yacc.c:1646  */
    break;
  case 128:
#line 952 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->togglevtg = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2747 "config_gram.c" /* yacc.c:1646  */
    break;
  case 129:
#line 958 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->poweroffdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2756 "config_gram.c" /* yacc.c:1646  */
    break;
  case 130:
#line 964 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->resetdelayms = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2765 "config_gram.c" /* yacc.c:1646  */
    break;
  case 131:
#line 970 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->resetdelayus = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2774 "config_gram.c" /* yacc.c:1646  */
    break;
  case 132:
#line 976 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->hvleavestabdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2783 "config_gram.c" /* yacc.c:1646  */
    break;
  case 133:
#line 982 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->resetdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2792 "config_gram.c" /* yacc.c:1646  */
    break;
  case 134:
#line 988 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->chiperasepulsewidth = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2801 "config_gram.c" /* yacc.c:1646  */
    break;
  case 135:
#line 994 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->chiperasepolltimeout = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2810 "config_gram.c" /* yacc.c:1646  */
    break;
  case 136:
#line 1000 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->chiperasetime = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2819 "config_gram.c" /* yacc.c:1646  */
    break;
  case 137:
#line 1006 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->programfusepulsewidth = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2828 "config_gram.c" /* yacc.c:1646  */
    break;
  case 138:
#line 1012 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->programfusepolltimeout = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2837 "config_gram.c" /* yacc.c:1646  */
    break;
  case 139:
#line 1018 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->programlockpulsewidth = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2846 "config_gram.c" /* yacc.c:1646  */
    break;
  case 140:
#line 1024 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->programlockpolltimeout = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2855 "config_gram.c" /* yacc.c:1646  */
    break;
  case 141:
#line 1030 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->synchcycles = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2864 "config_gram.c" /* yacc.c:1646  */
    break;
  case 142:
#line 1036 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_HAS_JTAG;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_HAS_JTAG;
      free_token((yyvsp[0]));
    }
#line 2877 "config_gram.c" /* yacc.c:1646  */
    break;
  case 143:
#line 1046 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_HAS_DW;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_HAS_DW;
      free_token((yyvsp[0]));
    }
#line 2890 "config_gram.c" /* yacc.c:1646  */
    break;
  case 144:
#line 1056 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_HAS_PDI;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_HAS_PDI;
      free_token((yyvsp[0]));
    }
#line 2903 "config_gram.c" /* yacc.c:1646  */
    break;
  case 145:
#line 1066 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_HAS_TPI;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_HAS_TPI;
      free_token((yyvsp[0]));
    }
#line 2916 "config_gram.c" /* yacc.c:1646  */
    break;
  case 146:
#line 1076 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_IS_AT90S1200;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_IS_AT90S1200;
      free_token((yyvsp[0]));
    }
#line 2929 "config_gram.c" /* yacc.c:1646  */
    break;
  case 147:
#line 1086 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_AVR32;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_AVR32;
      free_token((yyvsp[0]));
    }
#line 2942 "config_gram.c" /* yacc.c:1646  */
    break;
  case 148:
#line 1096 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_ALLOWFULLPAGEBITSTREAM;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_ALLOWFULLPAGEBITSTREAM;
      free_token((yyvsp[0]));
    }
#line 2955 "config_gram.c" /* yacc.c:1646  */
    break;
  case 149:
#line 1106 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_ENABLEPAGEPROGRAMMING;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_ENABLEPAGEPROGRAMMING;
      free_token((yyvsp[0]));
    }
#line 2968 "config_gram.c" /* yacc.c:1646  */
    break;
  case 150:
#line 1116 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->idr = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2977 "config_gram.c" /* yacc.c:1646  */
    break;
  case 151:
#line 1122 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->rampz = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2986 "config_gram.c" /* yacc.c:1646  */
    break;
  case 152:
#line 1128 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->spmcr = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2995 "config_gram.c" /* yacc.c:1646  */
    break;
  case 153:
#line 1134 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->eecr = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3004 "config_gram.c" /* yacc.c:1646  */
    break;
  case 154:
#line 1140 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->mcu_base = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3013 "config_gram.c" /* yacc.c:1646  */
    break;
  case 155:
#line 1146 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->nvm_base = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3022 "config_gram.c" /* yacc.c:1646  */
    break;
  case 156:
#line 1152 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->ocdrev = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3031 "config_gram.c" /* yacc.c:1646  */
    break;
  case 157:
#line 1158 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_SERIALOK;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_SERIALOK;
      free_token((yyvsp[0]));
    }
#line 3044 "config_gram.c" /* yacc.c:1646  */
    break;
  case 158:
#line 1168 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES) {
        current_part->flags |= AVRPART_PARALLELOK;
        current_part->flags &= ~AVRPART_PSEUDOPARALLEL;
      }
      else if ((yyvsp[0])->primary == K_NO) {
        current_part->flags &= ~AVRPART_PARALLELOK;
        current_part->flags &= ~AVRPART_PSEUDOPARALLEL;
      }
      else if ((yyvsp[0])->primary == K_PSEUDO) {
        current_part->flags |= AVRPART_PARALLELOK;
        current_part->flags |= AVRPART_PSEUDOPARALLEL;
      }
      free_token((yyvsp[0]));
    }
#line 3066 "config_gram.c" /* yacc.c:1646  */
    break;
  case 159:
#line 1187 "config_gram.y" /* yacc.c:1646  */
    {
      switch ((yyvsp[0])->primary) {
        case K_RESET :
          current_part->retry_pulse = PIN_AVR_RESET;
          break;
        case K_SCK :
          current_part->retry_pulse = PIN_AVR_SCK;
          break;
      }
      free_token((yyvsp[-2]));
    }
#line 3083 "config_gram.c" /* yacc.c:1646  */
    break;
  case 160:
#line 1210 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem = avr_new_memtype();
      if (current_mem == NULL) {
        yyerror("could not create mem instance");
        free_token((yyvsp[0]));
        YYABORT;
      }
      strncpy(current_mem->desc, (yyvsp[0])->value.string, AVR_MEMDESCLEN);
      current_mem->desc[AVR_MEMDESCLEN-1] = 0;
      free_token((yyvsp[0]));
    }
#line 3099 "config_gram.c" /* yacc.c:1646  */
    break;
  case 161:
#line 1222 "config_gram.y" /* yacc.c:1646  */
    {
      AVRMEM * existing_mem;
      existing_mem = avr_locate_mem(current_part, current_mem->desc);
      if (existing_mem != NULL) {
        lrmv_d(current_part->mem, existing_mem);
        avr_free_mem(existing_mem);
      }
      ladd(current_part->mem, current_mem);
      current_mem = NULL;
    }
#line 3115 "config_gram.c" /* yacc.c:1646  */
    break;
  case 162:
#line 1234 "config_gram.y" /* yacc.c:1646  */
    {
    {
      int opnum;
      OPCODE * op;
      opnum = which_opcode((yyvsp[-2]));
      if (opnum < 0) YYABORT;
      op = avr_new_opcode();
      if (op == NULL) {
        yyerror("could not create opcode instance");
        free_token((yyvsp[-2]));
        YYABORT;
      }
      if(0 != parse_cmdbits(op)) YYABORT;
      if (current_part->op[opnum] != NULL) {
        /*yywarning("operation redefined");*/
        avr_free_opcode(current_part->op[opnum]);
      }
      current_part->op[opnum] = op;
      free_token((yyvsp[-2]));
    }
  }
#line 3143 "config_gram.c" /* yacc.c:1646  */
    break;
  case 167:
#line 1273 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->paged = (yyvsp[0])->primary == K_YES ? 1 : 0;
      free_token((yyvsp[0]));
    }
#line 3152 "config_gram.c" /* yacc.c:1646  */
    break;
  case 168:
#line 1279 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->size = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3161 "config_gram.c" /* yacc.c:1646  */
    break;
  case 169:
#line 1286 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->page_size = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3170 "config_gram.c" /* yacc.c:1646  */
    break;
  case 170:
#line 1292 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->num_pages = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3179 "config_gram.c" /* yacc.c:1646  */
    break;
  case 171:
#line 1298 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->offset = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3188 "config_gram.c" /* yacc.c:1646  */
    break;
  case 172:
#line 1304 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->min_write_delay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3197 "config_gram.c" /* yacc.c:1646  */
    break;
  case 173:
#line 1310 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->max_write_delay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3206 "config_gram.c" /* yacc.c:1646  */
    break;
  case 174:
#line 1316 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->pwroff_after_write = (yyvsp[0])->primary == K_YES ? 1 : 0;
      free_token((yyvsp[0]));
    }
#line 3215 "config_gram.c" /* yacc.c:1646  */
    break;
  case 175:
#line 1322 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->readback[0] = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3224 "config_gram.c" /* yacc.c:1646  */
    break;
  case 176:
#line 1328 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->readback[1] = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3233 "config_gram.c" /* yacc.c:1646  */
    break;
  case 177:
#line 1335 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->mode = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3242 "config_gram.c" /* yacc.c:1646  */
    break;
  case 178:
#line 1341 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->delay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3251 "config_gram.c" /* yacc.c:1646  */
    break;
  case 179:
#line 1347 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->blocksize = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3260 "config_gram.c" /* yacc.c:1646  */
    break;
  case 180:
#line 1353 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->readsize = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3269 "config_gram.c" /* yacc.c:1646  */
    break;
  case 181:
#line 1359 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->pollindex = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3278 "config_gram.c" /* yacc.c:1646  */
    break;
  case 182:
#line 1365 "config_gram.y" /* yacc.c:1646  */
    {
    {
      int opnum;
      OPCODE * op;
      opnum = which_opcode((yyvsp[-2]));
      if (opnum < 0) YYABORT;
      op = avr_new_opcode();
      if (op == NULL) {
        yyerror("could not create opcode instance");
        free_token((yyvsp[-2]));
        YYABORT;
      }
      if(0 != parse_cmdbits(op)) YYABORT;
      if (current_mem->op[opnum] != NULL) {
        /*yywarning("operation redefined");*/
        avr_free_opcode(current_mem->op[opnum]);
      }
      current_mem->op[opnum] = op;
      free_token((yyvsp[-2]));
    }
  }
#line 3306 "config_gram.c" /* yacc.c:1646  */
    break;
#line 3310 "config_gram.c" /* yacc.c:1646  */
      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  *++yyvsp = yyval;
  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  yyn = yyr1[yyn];
  yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
  if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTOKENS];
  goto yynewstate;
/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
#if ! YYERROR_VERBOSE
      yyerror (YY_("syntax error"));
#else
# define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                        yyssp, yytoken)
      {
        char const *yymsgp = YY_("syntax error");
        int yysyntax_error_status;
        yysyntax_error_status = YYSYNTAX_ERROR;
        if (yysyntax_error_status == 0)
          yymsgp = yymsg;
        else if (yysyntax_error_status == 1)
          {
            if (yymsg != yymsgbuf)
              YYSTACK_FREE (yymsg);
            yymsg = (char *) YYSTACK_ALLOC (yymsg_alloc);
            if (!yymsg)
              {
                yymsg = yymsgbuf;
                yymsg_alloc = sizeof yymsgbuf;
                yysyntax_error_status = 2;
              }
            else
              {
                yysyntax_error_status = YYSYNTAX_ERROR;
                yymsgp = yymsg;
              }
          }
        yyerror (yymsgp);
        if (yysyntax_error_status == 2)
          goto yyexhaustedlab;
      }
# undef YYSYNTAX_ERROR
#endif
    }
  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */
      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }
  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;
/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers like GCC when the user code never invokes
     YYERROR and the label yyerrorlab therefore never appears in user
     code.  */
  if (/*CONSTCOND*/ 0)
     goto yyerrorlab;
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;
/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYTERROR;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }
      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;
      yydestruct ("Error: popping",
                  yystos[yystate], yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END
  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);
  yystate = yyn;
  goto yynewstate;
/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;
/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;
#if !defined yyoverflow || YYERROR_VERBOSE
/*-------------------------------------------------.
| yyexhaustedlab -- memory exhaustion comes here.  |
`-------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  /* Fall through.  */
#endif
yyreturn:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  yystos[*yyssp], yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
#if YYERROR_VERBOSE
  if (yymsg != yymsgbuf)
    YYSTACK_FREE (yymsg);
#endif
  return yyresult;
}
References assign_pin(), assign_pin_list(), avrpart::avr910_devcode, AVR_DESCLEN, avr_dup_part(), avr_free_mem(), avr_free_opcode(), avr_free_part(), AVR_IDLEN, avr_locate_mem(), AVR_MEMDESCLEN, avr_new_memtype(), avr_new_opcode(), avr_new_part(), AVRPART_ALLOWFULLPAGEBITSTREAM, AVRPART_AVR32, AVRPART_ENABLEPAGEPROGRAMMING, AVRPART_HAS_DW, AVRPART_HAS_JTAG, AVRPART_HAS_PDI, AVRPART_HAS_TPI, AVRPART_IS_AT90S1200, AVRPART_PARALLELOK, AVRPART_PSEUDOPARALLEL, AVRPART_SERIALOK, programmer_t::baudrate, avrmem::blocksize, avrpart::bs2, avrpart::bytedelay, avrpart::chip_erase_delay, avrpart::chiperasepolltimeout, avrpart::chiperasepulsewidth, avrpart::chiperasetime, avrpart::cmdexedelay, avrpart::config_file, programmer_t::config_file, programmer_t::conntype, CONNTYPE_PARALLEL, CONNTYPE_SERIAL, CONNTYPE_USB, avrpart::controlstack, CTL_STACK_HVSP, CTL_STACK_PP, CTL_STACK_SIZE, avrpart::ctl_stack_type, current_mem, current_part, current_prog, default_bitclock, default_parallel, default_programmer, default_safemode, default_serial, avrmem::delay, avrpart::desc, avrmem::desc, programmer_t::desc, dup_string(), avrpart::eecr, avrpart::eeprom_instr, EEPROM_INSTR_SIZE, avrpart::flags, avrpart::flash_instr, FLASH_INSTR_SIZE, free(), free_token(), free_tokens(), avrpart::hventerstabdelay, avrpart::hvleavestabdelay, avrpart::hvspcmdexedelay, avrpart::id, programmer_t::id, avrpart::idr, infile, programmer_t::initpgm, programmer_type_t::initpgm, K_DEDICATED, K_IO, K_NO, K_PSEUDO, K_RESET, K_SCK, K_YES, ladd(), avrpart::latchcycles, lcreat(), ldata(), ldestroy_cb(), lfirst(), lineno, avrpart::lineno, programmer_t::lineno, lnext(), locate_part(), locate_programmer(), locate_programmer_type(), lrmv_d(), lrmv_n(), lsize(), malloc(), MAX_STR_CONST, avrmem::max_write_delay, avrpart::mcu_base, avrpart::mem, avrmem::min_write_delay, avrmem::mode, avrmem::num_pages, value_t::number, number_list, avrpart::nvm_base, avrpart::ocdrev, avrmem::offset, avrpart::op, avrmem::op, avrmem::page_size, avrmem::paged, avrpart::pagel, parse_cmdbits(), part_list, PATH_MAX, pgm, PGM_DESCLEN, pgm_dup(), pgm_free(), pgm_new(), PGM_USBSTRINGLEN, programmer_t::pin, PIN_AVR_MISO, PIN_AVR_MOSI, PIN_AVR_RESET, PIN_AVR_SCK, pin_clear_all(), PIN_LED_ERR, PIN_LED_PGM, PIN_LED_RDY, PIN_LED_VFY, pin_name, avrpart::pollindex, avrmem::pollindex, avrpart::pollmethod, avrpart::pollvalue, avrpart::postdelay, avrpart::poweroffdelay, PPI_AVR_BUFF, PPI_AVR_VCC, avrpart::predelay, avrpart::progmodedelay, avrpart::programfusepolltimeout, avrpart::programfusepulsewidth, avrpart::programlockpolltimeout, avrpart::programlockpulsewidth, programmers, PUSH, avrmem::pwroff_after_write, avrpart::rampz, avrmem::readback, avrmem::readsize, RESET_DEDICATED, avrpart::reset_disposition, RESET_IO, avrpart::resetdelay, avrpart::resetdelayms, avrpart::resetdelayus, avrpart::retry_pulse, avrpart::signature, avrmem::size, avrpart::spmcr, avrpart::stabdelay, avrpart::stk500_devcode, value_t::string, string_list, avrpart::synchcycles, avrpart::synchloops, avrpart::timeout, avrpart::togglevtg, programmer_t::usbdev, avrpart::usbpid, programmer_t::usbpid, programmer_t::usbproduct, programmer_t::usbsn, programmer_t::usbvendor, programmer_t::usbvid, V_NUM_REAL, token_t::value, which_opcode(), YY_, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yychar, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror(), YYFINAL, YYINITDEPTH, YYLAST, yylex(), yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, yypact, yypact_value_is_default, yypgoto, YYPOPSTACK, yyr1, yyr2, YYSIZE_T, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yystos, yytable, yytable_value_is_error, YYTERROR, YYTRANSLATE, yyalloc::yyvs_alloc, and yywarning().
Referenced by read_config(), and read_config_builtin().
yywarning()
int yywarning (char * errmsg, ...)
{
  va_list args;
  char message[512];
  va_start(args, errmsg);
  vsnprintf(message, sizeof(message), errmsg, args);
  avrdude_message(MSG_INFO, "%s: warning at %s:%d: %s\n", progname, infile, lineno, message);
  va_end(args);
  return 0;
}
References avrdude_message(), infile, lineno, MSG_INFO, and progname.
Referenced by yyparse().
Variable Documentation
pin_name
int pin_name static
Referenced by assign_pin_list(), and yyparse().
yychar
int yychar
Referenced by yyparse().
yycheck
const yytype_int16 yycheck[] static
Referenced by yyparse().
yydefact
const yytype_uint8 yydefact[] static
Referenced by yyparse().
yydefgoto
const yytype_int16 yydefgoto[] static
Initial value:
=
{
      -1,   132,     8,     9,    10,    11,    12,    13,    14,   243,
     316,    46,    47,    48,   259,    49,   239,    50,   253,   341,
     342,   337,   338,   339,    51,   260,   235,   248,   249,   245,
     244,   241,   247,   246,   261,   127,   128,   280,   276,   283,
     129,   263,   137,   369,   370
}
Referenced by yyparse().
yylval
YYSTYPE yylval
Referenced by yyparse().
yynerrs
int yynerrs
Referenced by yyparse().
yypact
const yytype_int16 yypact[] static
Referenced by yyparse().
yypgoto
const yytype_int16 yypgoto[] static
Initial value:
=
{
    -258,  -258,  -258,  -258,   132,  -258,  -258,  -258,  -258,  -225,
    -209,  -258,   267,  -258,  -258,  -258,  -258,  -258,  -258,  -231,
    -181,  -228,  -258,  -109,  -258,  -258,  -258,  -258,  -258,  -258,
    -258,  -258,  -258,  -258,  -258,  -257,  -258,  -258,  -258,  -258,
     273,  -258,  -176,  -258,  -210
}
Referenced by yyparse().
yyr1
const yytype_uint8 yyr1[] static
Initial value:
=
{
       0,   136,   137,   137,   138,   138,   139,   139,   140,   140,
     140,   140,   140,   140,   140,   141,   142,   142,   143,   144,
     144,   145,   145,   146,   146,   147,   147,   148,   148,   148,
     148,   148,   148,   148,   149,   150,   150,   151,   152,   152,
     152,   153,   153,   153,   153,   153,   153,   154,   154,   155,
     155,   156,   156,   157,   157,   158,   158,   159,   159,   161,
     160,   162,   160,   163,   160,   164,   160,   165,   160,   166,
     160,   167,   160,   168,   160,   169,   160,   170,   160,   171,
     171,   171,   171,   171,   171,   171,   171,   171,   171,   171,
     171,   172,   172,   173,   173,   174,   174,   175,   175,   176,
     176,   176,   176,   176,   176,   176,   176,   176,   176,   176,
     176,   176,   176,   176,   176,   176,   176,   176,   176,   176,
     176,   176,   176,   176,   176,   176,   176,   176,   176,   176,
     176,   176,   176,   176,   176,   176,   176,   176,   176,   176,
     176,   176,   176,   176,   176,   176,   176,   176,   176,   176,
     176,   176,   176,   176,   176,   176,   176,   176,   176,   176,
     177,   176,   176,   178,   178,   179,   179,   180,   180,   180,
     180,   180,   180,   180,   180,   180,   180,   180,   180,   180,
     180,   180,   180
}
Referenced by yyparse().
yyr2
const yytype_uint8 yyr2[] static
Initial value:
=
{
       0,     2,     1,     1,     0,     1,     1,     2,     2,     2,
       4,     4,     4,     4,     4,     2,     1,     3,     2,     1,
       3,     1,     3,     1,     3,     2,     3,     3,     1,     1,
       1,     1,     3,     3,     3,     1,     1,     3,     1,     1,
       1,     3,     3,     3,     3,     3,     3,     1,     3,     1,
       2,     1,     0,     1,     4,     1,     3,     1,     0,     0,
       4,     0,     4,     0,     4,     0,     4,     0,     4,     0,
       4,     0,     4,     0,     4,     0,     4,     0,     4,     1,
       1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     2,     3,     1,     1,     1,     1,     1,     1,     3,
       3,     3,     3,     3,     5,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       0,     4,     3,     1,     1,     2,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3
}
Referenced by yyparse().
yystos
const yytype_uint8 yystos[] static
Referenced by yyparse().
yytable
const yytype_uint16 yytable[] static
Referenced by yyparse().
yytranslate
const yytype_uint8 yytranslate[] static