Prusa Slicer: Slic3r::Measure::AngleAndEdges Struct Reference
Slic3r::Measure::AngleAndEdges Struct Reference
#include <src/libslic3r/Measure.hpp>
Public Member Functions
AngleAndEdges (double angle_, const Vec3d &center_, const std::pair< Vec3d, Vec3d > &e1_, const std::pair< Vec3d, Vec3d > &e2_, double radius_, bool coplanar_)
Public Attributes
double angle
Vec3d center
std::pair< Vec3d, Vec3d > e1
std::pair< Vec3d, Vec3d > e2
double radius
bool coplanar
Static Public Attributes
static const AngleAndEdges Dummy = { 0.0, Vec3d::Zero(), { Vec3d::Zero(), Vec3d::Zero() }, { Vec3d::Zero(), Vec3d::Zero() }, 0.0, true }
Detailed Description
Constructor & Destructor Documentation
AngleAndEdges()
Slic3r::Measure::AngleAndEdges::AngleAndEdges (double angle_, const Vec3d & center_, const std::pair< Vec3d, Vec3d > & e1_, const std::pair< Vec3d, Vec3d > & e2_, double radius_, bool coplanar_) inline
        : angle(angle_), center(center_), e1(e1_), e2(e2_), radius(radius_), coplanar(coplanar_) {}
Member Data Documentation
angle
double Slic3r::Measure::AngleAndEdges::angle
center
Vec3d Slic3r::Measure::AngleAndEdges::center
coplanar
bool Slic3r::Measure::AngleAndEdges::coplanar
Dummy
const AngleAndEdges Slic3r::Measure::AngleAndEdges::Dummy = { 0.0, Vec3d::Zero(), { Vec3d::Zero(), Vec3d::Zero() }, { Vec3d::Zero(), Vec3d::Zero() }, 0.0, true } static
Referenced by Slic3r::Measure::angle_edge_edge(), Slic3r::Measure::angle_edge_plane(), and Slic3r::Measure::angle_plane_plane().
e1
std::pair<Vec3d, Vec3d> Slic3r::Measure::AngleAndEdges::e1
e2
std::pair<Vec3d, Vec3d> Slic3r::Measure::AngleAndEdges::e2
radius
double Slic3r::Measure::AngleAndEdges::radius
Referenced by Slic3r::Measure::angle_edge_plane(), and Slic3r::Measure::angle_plane_plane().
The documentation for this struct was generated from the following files:
src/libslic3r/Measure.hpp
src/libslic3r/Measure.cpp