Prusa Slicer: Slic3r::int128 Namespace Reference
Slic3r::int128 Namespace Reference
Functions
int orient (const Vec2crd &p1, const Vec2crd &p2, const Vec2crd &p3)
int cross (const Vec2crd &v1, const Vec2crd &v2)
Function Documentation
cross()
int Slic3r::int128::cross (const Vec2crd & v1, const Vec2crd & v2)
{
    return Int128::sign_determinant_2x2_filtered(v1.x(), v1.y(), v2.x(), v2.y());
}
References Int128::sign_determinant_2x2_filtered().
orient()
int Slic3r::int128::orient (const Vec2crd & p1, const Vec2crd & p2, const Vec2crd & p3)
{
    Slic3r::Vector v1(p2 - p1);
    Slic3r::Vector v2(p3 - p1);
    return Int128::sign_determinant_2x2_filtered(v1.x(), v1.y(), v2.x(), v2.y());
}
References orient(), and Int128::sign_determinant_2x2_filtered().
Referenced by orient().