Prusa Slicer: Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased > Struct Template Reference
Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased > Struct Template Reference
#include <src/eigen/Eigen/src/Core/CoreEvaluators.h>
Public Types
enum {
CoeffReadCost = evaluator<Lhs>::CoeffReadCost + evaluator<Rhs>::CoeffReadCost + functor_traits<BinaryOp>::Cost , LhsFlags = evaluator<Lhs>::Flags , RhsFlags = evaluator<Rhs>::Flags , SameType = is_same<typename Lhs::Scalar,typename Rhs::Scalar>::value ,
StorageOrdersAgree = (int(LhsFlags)&RowMajorBit)==(int(RhsFlags)&RowMajorBit) , Flags0 , Flags = (Flags0 & ~RowMajorBit) | (LhsFlags & RowMajorBit) , Alignment = EIGEN_PLAIN_ENUM_MIN(evaluator<Lhs>::Alignment,evaluator<Rhs>::Alignment)
}
typedef CwiseBinaryOp< BinaryOp, Lhs, Rhs > XprType
typedef XprType::CoeffReturnType CoeffReturnType
enum
typedef traits< CwiseBinaryOp< BinaryOp, Lhs, Rhs > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC binary_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE PacketType packet (Index index) const
Protected Attributes
const BinaryOp m_functor
evaluator< Lhs > m_lhsImpl
evaluator< Rhs > m_rhsImpl
Detailed Description
template<typename BinaryOp, typename Lhs, typename Rhs>
struct Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >
Member Typedef Documentation
CoeffReturnType
template<typename BinaryOp , typename Lhs , typename Rhs > typedef XprType::CoeffReturnType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::CoeffReturnType
ExpressionTraits
typedef traits<CwiseBinaryOp< BinaryOp, Lhs, Rhs > > Eigen::internal::evaluator_base< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::ExpressionTraits inherited
XprType
template<typename BinaryOp , typename Lhs , typename Rhs > typedef CwiseBinaryOp<BinaryOp, Lhs, Rhs> Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    Alignment = 0
  };
anonymous enum
template<typename BinaryOp , typename Lhs , typename Rhs > anonymous enum
Enumerator
CoeffReadCost
LhsFlags
RhsFlags
SameType
StorageOrdersAgree
Flags0
Flags
Alignment
       {
    CoeffReadCost = evaluator<Lhs>::CoeffReadCost + evaluator<Rhs>::CoeffReadCost + functor_traits<BinaryOp>::Cost,
    LhsFlags = evaluator<Lhs>::Flags,
    RhsFlags = evaluator<Rhs>::Flags,
    SameType = is_same<typename Lhs::Scalar,typename Rhs::Scalar>::value,
    StorageOrdersAgree = (int(LhsFlags)&RowMajorBit)==(int(RhsFlags)&RowMajorBit),
    Flags0 = (int(LhsFlags) | int(RhsFlags)) & (
        HereditaryBits
      | (int(LhsFlags) & int(RhsFlags) &
           ( (StorageOrdersAgree ? LinearAccessBit : 0)
           | (functor_traits<BinaryOp>::PacketAccess && StorageOrdersAgree && SameType ? PacketAccessBit : 0)
           )
        )
     ),
    Flags = (Flags0 & ~RowMajorBit) | (LhsFlags & RowMajorBit),
    Alignment = EIGEN_PLAIN_ENUM_MIN(evaluator<Lhs>::Alignment,evaluator<Rhs>::Alignment)
  };
Constructor & Destructor Documentation
binary_evaluator()
template<typename BinaryOp , typename Lhs , typename Rhs > EIGEN_DEVICE_FUNC Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::binary_evaluator (const XprType & xpr) inline explicit
    : m_functor(xpr.functor()),
      m_lhsImpl(xpr.lhs()),
      m_rhsImpl(xpr.rhs())
  {
    EIGEN_INTERNAL_CHECK_COST_VALUE(functor_traits<BinaryOp>::Cost);
    EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
  }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename BinaryOp , typename Lhs , typename Rhs > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::coeff (Index index) const inline
  {
    return m_functor(m_lhsImpl.coeff(index), m_rhsImpl.coeff(index));
  }
coeff() [2/2]
template<typename BinaryOp , typename Lhs , typename Rhs > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::coeff (Index row, Index col) const inline
  {
    return m_functor(m_lhsImpl.coeff(row, col), m_rhsImpl.coeff(row, col));
  }
References col(), and row().
packet() [1/2]
template<typename BinaryOp , typename Lhs , typename Rhs > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::packet (Index index) const inline
  {
    return m_functor.packetOp(m_lhsImpl.template packet<LoadMode,PacketType>(index),
                              m_rhsImpl.template packet<LoadMode,PacketType>(index));
  }
packet() [2/2]
template<typename BinaryOp , typename Lhs , typename Rhs > template<int LoadMode, typename PacketType > EIGEN_STRONG_INLINE PacketType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::packet (Index row, Index col) const inline
  {
    return m_functor.packetOp(m_lhsImpl.template packet<LoadMode,PacketType>(row, col),
                              m_rhsImpl.template packet<LoadMode,PacketType>(row, col));
  }
References col(), and row().
Member Data Documentation
m_functor
template<typename BinaryOp , typename Lhs , typename Rhs > const BinaryOp Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::m_functor protected
m_lhsImpl
template<typename BinaryOp , typename Lhs , typename Rhs > evaluator<Lhs> Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::m_lhsImpl protected
m_rhsImpl
template<typename BinaryOp , typename Lhs , typename Rhs > evaluator<Rhs> Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::m_rhsImpl protected
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/CoreEvaluators.h