Prusa Slicer: Slic3r::GUI::ArchiveViewCtrl Class Reference
Slic3r::GUI::ArchiveViewCtrl Class Reference
#include <src/slic3r/GUI/FileArchiveDialog.hpp>
Public Member Functions
ArchiveViewCtrl (wxWindow *parent, wxSize size)
~ArchiveViewCtrl ()
ArchiveViewModel * get_model () const
Protected Attributes
ArchiveViewModel * m_model
Detailed Description
Constructor & Destructor Documentation
ArchiveViewCtrl()
Slic3r::GUI::ArchiveViewCtrl::ArchiveViewCtrl (wxWindow * parent, wxSize size)
    : wxDataViewCtrl(parent, wxID_ANY, wxDefaultPosition, size, wxDV_VARIABLE_LINE_HEIGHT | wxDV_ROW_LINES
#ifdef _WIN32
        | wxBORDER_SIMPLE
#endif
    )
    //, m_em_unit(em_unit(parent))
{
    wxGetApp().UpdateDVCDarkUI(this);
    m_model = new ArchiveViewModel(parent);
    this->AssociateModel(m_model);
    m_model->SetAssociatedControl(this);
}
References m_model, and Slic3r::GUI::ArchiveViewModel::SetAssociatedControl().
~ArchiveViewCtrl()
Slic3r::GUI::ArchiveViewCtrl::~ArchiveViewCtrl ()
{
    if (m_model) {
        m_model->Clear();
        m_model->DecRef();
    }
}
References Slic3r::GUI::ArchiveViewModel::Clear(), and m_model.
Member Function Documentation
get_model()
ArchiveViewModel * Slic3r::GUI::ArchiveViewCtrl::get_model () const inline
{return m_model; }
References m_model.
Referenced by Slic3r::GUI::FileArchiveDialog::FileArchiveDialog(), Slic3r::GUI::FileArchiveDialog::on_all_button(), Slic3r::GUI::FileArchiveDialog::on_none_button(), and Slic3r::GUI::FileArchiveDialog::on_open_button().
Member Data Documentation
m_model
ArchiveViewModel* Slic3r::GUI::ArchiveViewCtrl::m_model protected
Referenced by ArchiveViewCtrl(), ~ArchiveViewCtrl(), and get_model().
The documentation for this class was generated from the following files:
src/slic3r/GUI/FileArchiveDialog.hpp
src/slic3r/GUI/FileArchiveDialog.cpp