Prusa Slicer: Slic3r::AppUpdater Class Reference
Slic3r::AppUpdater Class Reference
#include <src/slic3r/Utils/AppUpdater.hpp>
Classes
struct priv
Public Member Functions
AppUpdater ()
~AppUpdater ()
AppUpdater (AppUpdater &&)=delete
AppUpdater (const AppUpdater &)=delete
AppUpdater & operator= (AppUpdater &&)=delete
AppUpdater & operator= (const AppUpdater &)=delete
void sync_download ()
void sync_version (const std::string &version_check_url, bool from_user)
void cancel ()
bool cancel_callback ()
std::string get_default_dest_folder ()
bool get_triggered_by_user () const
bool get_download_ongoing () const
void set_app_data (DownloadAppData data)
DownloadAppData get_app_data ()
Static Public Member Functions
static std::string get_filename_from_url (const std::string &url)
static std::string get_file_extension_from_url (const std::string &url)
Private Attributes
std::unique_ptr< priv > p
Detailed Description
Constructor & Destructor Documentation
AppUpdater() [1/3]
Slic3r::AppUpdater::AppUpdater ()
  :p(new priv())
{
}
~AppUpdater()
Slic3r::AppUpdater::~AppUpdater ()
{
  if (p && p->m_thread.joinable()) {
    // This will stop transfers being done by the thread, if any.
    // Cancelling takes some time, but should complete soon enough.
    p->m_cancel = true;
    p->m_thread.join();
  }
}
References p.
AppUpdater() [2/3]
Slic3r::AppUpdater::AppUpdater (AppUpdater &&) delete
AppUpdater() [3/3]
Slic3r::AppUpdater::AppUpdater (const AppUpdater &) delete
Member Function Documentation
cancel()
void Slic3r::AppUpdater::cancel ()
{
  p->m_cancel = true;
}
References p.
Referenced by cancel_callback(), and Slic3r::AppUpdater::priv::http_get_file().
cancel_callback()
bool Slic3r::AppUpdater::cancel_callback ()
{
  cancel();
  return true;
}
References cancel().
Referenced by Slic3r::GUI::GUI_App::app_updater().
get_app_data()
DownloadAppData Slic3r::AppUpdater::get_app_data ()
{
  return p->get_app_data();
}
References p.
get_default_dest_folder()
std::string Slic3r::AppUpdater::get_default_dest_folder ()
{
  return p->m_default_dest_folder.string();
}
References p.
get_download_ongoing()
bool Slic3r::AppUpdater::get_download_ongoing () const
{
  return p->get_download_ongoing();
}
References p.
get_file_extension_from_url()
std::string Slic3r::AppUpdater::get_file_extension_from_url (const std::string & url) static
{
  size_t dot = url.rfind('.');
  return (dot != std::string::npos ? url.substr(dot) : url);
}
References Slic3r::dot().
get_filename_from_url()
std::string Slic3r::AppUpdater::get_filename_from_url (const std::string & url) static
{
  size_t slash = url.rfind('/');
  return (slash != std::string::npos ? url.substr(slash + 1) : url);
}
Referenced by Slic3r::AppUpdater::priv::parse_version_string().
get_triggered_by_user()
bool Slic3r::AppUpdater::get_triggered_by_user () const
{
  return p->get_triggered_by_user();
}
References p.
operator=() [1/2]
AppUpdater & Slic3r::AppUpdater::operator= (AppUpdater &&) delete
operator=() [2/2]
AppUpdater & Slic3r::AppUpdater::operator= (const AppUpdater &) delete
set_app_data()
void Slic3r::AppUpdater::set_app_data (DownloadAppData data)
{
  p->set_app_data(std::move(data));
}
References p.
Referenced by Slic3r::AppUpdater::priv::parse_version_string().
sync_download()
void Slic3r::AppUpdater::sync_download ()
{
  assert(p);
  // join thread first - it could have been in sync_version
  if (p->m_thread.joinable()) {
    // This will stop transfers being done by the thread, if any.
    // Cancelling takes some time, but should complete soon enough.
    p->m_cancel = true;
    p->m_thread.join();
  }
  p->m_cancel = false;
  DownloadAppData input_data = p->get_app_data();
  assert(!input_data.url.empty());
  p->m_thread = std::thread(
    [this, input_data]() {
      p->m_download_ongoing = true;
      if (boost::filesystem::path dest_path = p->download_file(input_data); boost::filesystem::exists(dest_path)){
        if (input_data.start_after) {
          p->run_downloaded_file(std::move(dest_path));
        } else {
          GUI::desktop_open_folder(dest_path.parent_path());
        }
      }
      p->m_download_ongoing = false;
    });
}
References Slic3r::GUI::desktop_open_folder(), p, Slic3r::DownloadAppData::start_after, and Slic3r::DownloadAppData::url.
sync_version()
void Slic3r::AppUpdater::sync_version (const std::string & version_check_url, bool from_user)
{
  assert(p);
  // join thread first - it could have been in sync_download
  if (p->m_thread.joinable()) {
    // This will stop transfers being done by the thread, if any.
    // Cancelling takes some time, but should complete soon enough.
    p->m_cancel = true;
    p->m_thread.join();
  }
  p->m_triggered_by_user = from_user;
  p->m_cancel = false;
  p->m_thread = std::thread(
    [this, version_check_url]() {
      p->version_check(version_check_url);
    });
}
References p.
Member Data Documentation
p
std::unique_ptr<priv> Slic3r::AppUpdater::p private
Referenced by ~AppUpdater(), cancel(), get_app_data(), get_default_dest_folder(), get_download_ongoing(), get_triggered_by_user(), set_app_data(), sync_download(), and sync_version().
The documentation for this class was generated from the following files:
src/slic3r/Utils/AppUpdater.hpp
src/slic3r/Utils/AppUpdater.cpp