Prusa Slicer: agg::sRGB_lut< int16u > Class Reference
agg::sRGB_lut< int16u > Class Reference
#include <src/agg/agg_gamma_lut.h>
Public Member Functions
sRGB_lut ()
int16u dir (int8u v) const
int8u inv (int16u v) const
Private Attributes
int16u m_dir_table [256]
int8u m_inv_table [65536]
Detailed Description
Constructor & Destructor Documentation
sRGB_lut()
agg::sRGB_lut< int16u >::sRGB_lut () inline
        {
            // Generate lookup tables.
            for (int i = 0; i <= 255; ++i)
            {
                m_dir_table[i] = uround(65535.0 * sRGB_to_linear(i / 255.0));
            }
      for (int i = 0; i <= 65535; ++i)
      {
        m_inv_table[i] = uround(255.0 * linear_to_sRGB(i / 65535.0));
      }
    }
References agg::linear_to_sRGB(), agg::sRGB_to_linear(), and agg::uround().
Member Function Documentation
dir()
int16u agg::sRGB_lut< int16u >::dir (int8u v) const inline
    {
      return m_dir_table[v];
    }
inv()
int8u agg::sRGB_lut< int16u >::inv (int16u v) const inline
    {
      return m_inv_table[v];
    }
Member Data Documentation
m_dir_table
int16u agg::sRGB_lut< int16u >::m_dir_table[256] private
m_inv_table
int8u agg::sRGB_lut< int16u >::m_inv_table[65536] private
The documentation for this class was generated from the following file:
src/agg/agg_gamma_lut.h