Prusa Slicer: Slic3r::GUI::EmbossStylesSerializable Class Reference
Slic3r::GUI::EmbossStylesSerializable Class Reference
For store/load font list to/from AppConfig.
#include <src/slic3r/Utils/EmbossStylesSerializable.hpp>
Public Member Functions
EmbossStylesSerializable ()=delete
Static Public Member Functions
static void store_style_index (AppConfig &cfg, unsigned index)
static std::optional< size_t > load_style_index (const AppConfig &cfg)
static EmbossStyles load_styles (const AppConfig &cfg)
static void store_styles (AppConfig &cfg, const EmbossStyles &styles)
Static Private Member Functions
static std::string create_section_name (unsigned index)
static std::optional< EmbossStyle > load_style (const std::map< std::string, std::string > &app_cfg_section)
static void store_style (AppConfig &cfg, const EmbossStyle &style, unsigned index)
static bool read (const std::map< std::string, std::string > &section, const std::string &key, bool &value)
static bool read (const std::map< std::string, std::string > &section, const std::string &key, float &value)
static bool read (const std::map< std::string, std::string > &section, const std::string &key, std::optional< int > &value)
static bool read (const std::map< std::string, std::string > &section, const std::string &key, std::optional< unsigned int > &value)
static bool read (const std::map< std::string, std::string > &section, const std::string &key, std::optional< float > &value)
Static Private Attributes
static const std::string APP_CONFIG_FONT_NAME = "name"
static const std::string APP_CONFIG_FONT_DESCRIPTOR = "descriptor"
static const std::string APP_CONFIG_FONT_LINE_HEIGHT = "line_height"
static const std::string APP_CONFIG_FONT_DEPTH = "depth"
static const std::string APP_CONFIG_FONT_USE_SURFACE = "use_surface"
static const std::string APP_CONFIG_FONT_BOLDNESS = "boldness"
static const std::string APP_CONFIG_FONT_SKEW = "skew"
static const std::string APP_CONFIG_FONT_DISTANCE = "distance"
static const std::string APP_CONFIG_FONT_ANGLE = "angle"
static const std::string APP_CONFIG_FONT_COLLECTION = "collection"
static const std::string APP_CONFIG_FONT_CHAR_GAP = "char_gap"
static const std::string APP_CONFIG_FONT_LINE_GAP = "line_gap"
static const std::string APP_CONFIG_ACTIVE_FONT = "active_font"
Detailed Description
For store/load font list to/from AppConfig.
Constructor & Destructor Documentation
EmbossStylesSerializable()
Slic3r::GUI::EmbossStylesSerializable::EmbossStylesSerializable () delete
Member Function Documentation
create_section_name()
std::string EmbossStylesSerializable::create_section_name (unsigned index) static private
{
    return AppConfig::SECTION_EMBOSS_STYLE + ':' + std::to_string(index);
}
References Slic3r::AppConfig::SECTION_EMBOSS_STYLE.
Referenced by load_styles(), store_style(), and store_styles().
load_style()
std::optional< EmbossStyle > EmbossStylesSerializable::load_style (const std::map< std::string, std::string > & app_cfg_section) static private
{
    auto path_it = app_cfg_section.find(APP_CONFIG_FONT_DESCRIPTOR);
    if (path_it == app_cfg_section.end()) return {};
    const std::string &path = path_it->second;
    auto name_it = app_cfg_section.find(APP_CONFIG_FONT_NAME);
    const std::string default_name = "font_name";
    const std::string &name =
        (name_it == app_cfg_section.end()) ?
        default_name : name_it->second;
    FontProp fp;
    read(app_cfg_section, APP_CONFIG_FONT_LINE_HEIGHT, fp.size_in_mm);
    read(app_cfg_section, APP_CONFIG_FONT_DEPTH, fp.emboss);
    read(app_cfg_section, APP_CONFIG_FONT_USE_SURFACE, fp.use_surface);
    read(app_cfg_section, APP_CONFIG_FONT_BOLDNESS, fp.boldness);
    read(app_cfg_section, APP_CONFIG_FONT_SKEW, fp.skew);
    read(app_cfg_section, APP_CONFIG_FONT_DISTANCE, fp.distance);
    read(app_cfg_section, APP_CONFIG_FONT_ANGLE, fp.angle);
    read(app_cfg_section, APP_CONFIG_FONT_COLLECTION, fp.collection_number);
    read(app_cfg_section, APP_CONFIG_FONT_CHAR_GAP, fp.char_gap);
    read(app_cfg_section, APP_CONFIG_FONT_LINE_GAP, fp.line_gap);
    EmbossStyle::Type type = WxFontUtils::get_actual_type();
    return EmbossStyle{ name, path, type, fp };
}
References Slic3r::FontProp::angle, APP_CONFIG_FONT_ANGLE, APP_CONFIG_FONT_BOLDNESS, APP_CONFIG_FONT_CHAR_GAP, APP_CONFIG_FONT_COLLECTION, APP_CONFIG_FONT_DEPTH, APP_CONFIG_FONT_DESCRIPTOR, APP_CONFIG_FONT_DISTANCE, APP_CONFIG_FONT_LINE_GAP, APP_CONFIG_FONT_LINE_HEIGHT, APP_CONFIG_FONT_NAME, APP_CONFIG_FONT_SKEW, APP_CONFIG_FONT_USE_SURFACE, Slic3r::FontProp::boldness, Slic3r::FontProp::char_gap, Slic3r::FontProp::collection_number, Slic3r::FontProp::distance, Slic3r::FontProp::emboss, Slic3r::GUI::WxFontUtils::get_actual_type(), Slic3r::FontProp::line_gap, read(), Slic3r::FontProp::size_in_mm, Slic3r::FontProp::skew, and Slic3r::FontProp::use_surface.
Referenced by load_styles().
load_style_index()
std::optional< size_t > EmbossStylesSerializable::load_style_index (const AppConfig & cfg) static
{
    if (!cfg.has_section(AppConfig::SECTION_EMBOSS_STYLE)) return {};
    auto section = cfg.get_section(AppConfig::SECTION_EMBOSS_STYLE);
    auto it      = section.find(APP_CONFIG_ACTIVE_FONT);
    if (it == section.end()) return {};
    size_t active_font = static_cast<size_t>(std::atoi(it->second.c_str()));
    // order in config starts with number 1
    return active_font - 1;
}
References APP_CONFIG_ACTIVE_FONT, Slic3r::AppConfig::get_section(), Slic3r::AppConfig::has_section(), and Slic3r::AppConfig::SECTION_EMBOSS_STYLE.
Referenced by Slic3r::GUI::Emboss::StyleManager::init().
load_styles()
EmbossStyles EmbossStylesSerializable::load_styles (const AppConfig & cfg) static
{
    EmbossStyles result;
    // human readable index inside of config starts from 1 !!
    unsigned    index        = 1;
    std::string section_name = create_section_name(index);
    while (cfg.has_section(section_name)) {
        std::optional<EmbossStyle> style_opt = load_style(cfg.get_section(section_name));
        if (style_opt.has_value()) result.emplace_back(*style_opt);
        section_name = create_section_name(++index);
    }
    return result;
}
References create_section_name(), Slic3r::AppConfig::get_section(), Slic3r::AppConfig::has_section(), and load_style().
Referenced by Slic3r::GUI::Emboss::StyleManager::init().
read() [1/5]
bool EmbossStylesSerializable::read (const std::map< std::string, std::string > & section, const std::string & key, bool & value) static private
{
    auto item = section.find(key);
    if (item == section.end()) return false;
    value = true;
    return true;
}
Referenced by load_style().
read() [2/5]
bool EmbossStylesSerializable::read (const std::map< std::string, std::string > & section, const std::string & key, float & value) static private
{
    auto item = section.find(key);
    if (item == section.end()) return false;
    const std::string &data = item->second;
    if (data.empty()) return false;
    float value_;
    fast_float::from_chars(data.c_str(), data.c_str() + data.length(), value_);
    // read only non zero value
    if (fabs(value_) <= std::numeric_limits<float>::epsilon()) return false;
    value = value_;
    return true;
}
References fast_float::from_chars().
read() [3/5]
bool EmbossStylesSerializable::read (const std::map< std::string, std::string > & section, const std::string & key, std::optional< float > & value) static private
{
    auto item = section.find(key);
    if (item == section.end()) return false;
    const std::string &data = item->second;
    if (data.empty()) return false;
    float value_;
    fast_float::from_chars(data.c_str(), data.c_str() + data.length(), value_);
    // read only non zero value
    if (fabs(value_) <= std::numeric_limits<float>::epsilon()) return false;
    value = value_;
    return true;
}
References fast_float::from_chars().
read() [4/5]
bool EmbossStylesSerializable::read (const std::map< std::string, std::string > & section, const std::string & key, std::optional< int > & value) static private
{
    auto item = section.find(key);
    if (item == section.end()) return false;
    const std::string &data = item->second;
    if (data.empty()) return false;
    int value_ = std::atoi(data.c_str());
    if (value_ == 0) return false;
    value = value_;
    return true;
}
read() [5/5]
bool EmbossStylesSerializable::read (const std::map< std::string, std::string > & section, const std::string & key, std::optional< unsigned int > & value) static private
{
    auto item = section.find(key);
    if (item == section.end()) return false;
    const std::string &data = item->second;
    if (data.empty()) return false;
    int value_ = std::atoi(data.c_str());
    if (value_ <= 0) return false;
    value = static_cast<unsigned int>(value_);
    return true;
}
store_style()
void EmbossStylesSerializable::store_style (AppConfig & cfg, const EmbossStyle & style, unsigned index) static private
{
    std::map<std::string, std::string> data;
    data[APP_CONFIG_FONT_NAME] = fi.name;
    data[APP_CONFIG_FONT_DESCRIPTOR] = fi.path;
    const FontProp &fp = fi.prop;
    data[APP_CONFIG_FONT_LINE_HEIGHT] = std::to_string(fp.size_in_mm);
    data[APP_CONFIG_FONT_DEPTH] = std::to_string(fp.emboss);
    if (fp.use_surface)
        data[APP_CONFIG_FONT_USE_SURFACE] = "true";
    if (fp.boldness.has_value())
        data[APP_CONFIG_FONT_BOLDNESS] = std::to_string(*fp.boldness);
    if (fp.skew.has_value())
        data[APP_CONFIG_FONT_SKEW] = std::to_string(*fp.skew);
    if (fp.distance.has_value())
        data[APP_CONFIG_FONT_DISTANCE] = std::to_string(*fp.distance);
    if (fp.angle.has_value())
        data[APP_CONFIG_FONT_ANGLE] = std::to_string(*fp.angle);
    if (fp.collection_number.has_value())
        data[APP_CONFIG_FONT_COLLECTION] = std::to_string(*fp.collection_number);
    if (fp.char_gap.has_value())
        data[APP_CONFIG_FONT_CHAR_GAP] = std::to_string(*fp.char_gap);
    if (fp.line_gap.has_value())
        data[APP_CONFIG_FONT_LINE_GAP] = std::to_string(*fp.line_gap);
    cfg.set_section(create_section_name(index), std::move(data));
}
References Slic3r::FontProp::angle, APP_CONFIG_FONT_ANGLE, APP_CONFIG_FONT_BOLDNESS, APP_CONFIG_FONT_CHAR_GAP, APP_CONFIG_FONT_COLLECTION, APP_CONFIG_FONT_DEPTH, APP_CONFIG_FONT_DESCRIPTOR, APP_CONFIG_FONT_DISTANCE, APP_CONFIG_FONT_LINE_GAP, APP_CONFIG_FONT_LINE_HEIGHT, APP_CONFIG_FONT_NAME, APP_CONFIG_FONT_SKEW, APP_CONFIG_FONT_USE_SURFACE, Slic3r::FontProp::boldness, Slic3r::FontProp::char_gap, Slic3r::FontProp::collection_number, create_section_name(), Slic3r::FontProp::distance, Slic3r::FontProp::emboss, Slic3r::FontProp::line_gap, Slic3r::EmbossStyle::name, Slic3r::EmbossStyle::path, Slic3r::EmbossStyle::prop, Slic3r::AppConfig::set_section(), Slic3r::FontProp::size_in_mm, Slic3r::FontProp::skew, and Slic3r::FontProp::use_surface.
Referenced by store_styles().
store_style_index()
void EmbossStylesSerializable::store_style_index (AppConfig & cfg, unsigned index) static
{
    // store actual font index
    // active font first index is +1 to correspond with section name
    std::map<std::string, std::string> data;
    data[APP_CONFIG_ACTIVE_FONT] = std::to_string(index);
    cfg.set_section(AppConfig::SECTION_EMBOSS_STYLE, std::move(data));
}
References APP_CONFIG_ACTIVE_FONT, Slic3r::AppConfig::SECTION_EMBOSS_STYLE, and Slic3r::AppConfig::set_section().
Referenced by Slic3r::GUI::Emboss::StyleManager::store_styles_to_app_config().
store_styles()
void EmbossStylesSerializable::store_styles (AppConfig & cfg, const EmbossStyles & styles) static
{
    // store styles
    unsigned index = 1;
    for (const EmbossStyle &style : styles) {
        // skip file paths + fonts from other OS(loaded from .3mf)
        assert(style.type == WxFontUtils::get_actual_type());
        // if (style_opt.type != WxFontUtils::get_actual_type()) continue;
        store_style(cfg, style, index++);
    }
    // remove rest of font sections (after deletation)
    std::string section_name = create_section_name(index);
    while (cfg.has_section(section_name)) {
        cfg.clear_section(section_name);
        section_name = create_section_name(++index);
    }
}
References Slic3r::AppConfig::clear_section(), create_section_name(), Slic3r::GUI::WxFontUtils::get_actual_type(), Slic3r::AppConfig::has_section(), store_style(), and style.
Referenced by Slic3r::GUI::Emboss::StyleManager::store_styles_to_app_config().
Member Data Documentation
APP_CONFIG_ACTIVE_FONT
const std::string EmbossStylesSerializable::APP_CONFIG_ACTIVE_FONT = "active_font" static private
Referenced by load_style_index(), and store_style_index().
APP_CONFIG_FONT_ANGLE
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_ANGLE = "angle" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_BOLDNESS
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_BOLDNESS = "boldness" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_CHAR_GAP
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_CHAR_GAP = "char_gap" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_COLLECTION
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_COLLECTION = "collection" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_DEPTH
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_DEPTH = "depth" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_DESCRIPTOR
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_DESCRIPTOR = "descriptor" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_DISTANCE
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_DISTANCE = "distance" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_LINE_GAP
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_LINE_GAP = "line_gap" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_LINE_HEIGHT
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_LINE_HEIGHT = "line_height" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_NAME
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_NAME = "name" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_SKEW
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_SKEW = "skew" static private
Referenced by load_style(), and store_style().
APP_CONFIG_FONT_USE_SURFACE
const std::string EmbossStylesSerializable::APP_CONFIG_FONT_USE_SURFACE = "use_surface" static private
Referenced by load_style(), and store_style().
The documentation for this class was generated from the following files:
src/slic3r/Utils/EmbossStylesSerializable.hpp
src/slic3r/Utils/EmbossStylesSerializable.cpp