Prusa Slicer: Slic3r::sla::anonymous_namespace{Pad.cpp}::BelowPadSkeleton Class Reference
Slic3r::sla::anonymous_namespace{Pad.cpp}::BelowPadSkeleton Class Reference
Public Member Functions
BelowPadSkeleton (const ExPolygons &support_blueprint, const ExPolygons &model_blueprint, const PadConfig &cfg, ThrowOnCancel thr)
Public Attributes
ExPolygons inner
ExPolygons outer
Detailed Description
Constructor & Destructor Documentation
BelowPadSkeleton()
Slic3r::sla::anonymous_namespace{Pad.cpp}::BelowPadSkeleton::BelowPadSkeleton (const ExPolygons & support_blueprint, const ExPolygons & model_blueprint, const PadConfig & cfg, ThrowOnCancel thr) inline
    {
        outer.reserve(support_blueprint.size() + model_blueprint.size());
        for (auto &ep : support_blueprint) outer.emplace_back(ep.contour);
        for (auto &ep : model_blueprint) outer.emplace_back(ep.contour);
        ConcaveHull ochull{outer, get_merge_distance(cfg), thr};
        outer = offset_waffle_style_ex(ochull, get_waffle_offset(cfg));
    }
References Slic3r::sla::anonymous_namespace{Pad.cpp}::get_merge_distance(), Slic3r::sla::anonymous_namespace{Pad.cpp}::get_waffle_offset(), and Slic3r::sla::offset_waffle_style_ex().
Member Data Documentation
inner
ExPolygons Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::inner inherited
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::_AroundPadSkeleton(), Slic3r::sla::anonymous_namespace{Pad.cpp}::create_pad_geometry(), and Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint().
outer
ExPolygons Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::outer inherited
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::_AroundPadSkeleton(), Slic3r::sla::anonymous_namespace{Pad.cpp}::create_pad_geometry(), and Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint().
The documentation for this class was generated from the following file:
src/libslic3r/SLA/Pad.cpp