Prusa Slicer: Slic3r::GUI::Bed3D Class Reference
Slic3r::GUI::Bed3D Class Reference
#include <src/slic3r/GUI/3DBed.hpp>
Public Types
enum class Type : unsigned char { System , Custom }
Public Member Functions
Bed3D ()=default
~Bed3D ()=default
bool set_shape (const Pointfs &bed_shape, const double max_print_height, const std::string &custom_texture, const std::string &custom_model, bool force_as_custom=false)
const BuildVolume & build_volume () const
Type get_type () const
bool is_custom () const
const BoundingBoxf3 & extended_bounding_box () const
bool contains (const Point &point) const
Point point_projection (const Point &point) const
void render (GLCanvas3D &canvas, const Transform3d &view_matrix, const Transform3d &projection_matrix, bool bottom, float scale_factor, bool show_texture)
void render_axes ()
void render_for_picking (GLCanvas3D &canvas, const Transform3d &view_matrix, const Transform3d &projection_matrix, bool bottom, float scale_factor)
Private Member Functions
BoundingBoxf3 calc_extended_bounding_box () const
void init_triangles ()
void init_gridlines ()
void init_contourlines ()
void render_internal (GLCanvas3D &canvas, const Transform3d &view_matrix, const Transform3d &projection_matrix, bool bottom, float scale_factor, bool show_texture, bool picking)
void render_system (GLCanvas3D &canvas, const Transform3d &view_matrix, const Transform3d &projection_matrix, bool bottom, bool show_texture)
void render_texture (bool bottom, GLCanvas3D &canvas, const Transform3d &view_matrix, const Transform3d &projection_matrix)
void render_model (const Transform3d &view_matrix, const Transform3d &projection_matrix)
void render_custom (GLCanvas3D &canvas, const Transform3d &view_matrix, const Transform3d &projection_matrix, bool bottom, bool show_texture, bool picking)
void render_default (bool bottom, bool picking, bool show_texture, const Transform3d &view_matrix, const Transform3d &projection_matrix)
void render_contour (const Transform3d &view_matrix, const Transform3d &projection_matrix)
void register_raycasters_for_picking (const GLModel::Geometry &geometry, const Transform3d &trafo)
Static Private Member Functions
static std::tuple< Type, std::string, std::string > detect_type (const Pointfs &shape)
Private Attributes
BuildVolume m_build_volume
Type m_type { Type::Custom }
std::string m_texture_filename
std::string m_model_filename
BoundingBoxf3 m_extended_bounding_box
ExPolygon m_contour
Polygon m_polygon
GLModel m_triangles
GLModel m_gridlines
GLModel m_contourlines
GLTexture m_texture
GLTexture m_temp_texture
PickingModel m_model
Vec3d m_model_offset { Vec3d::Zero() }
CoordAxes m_axes
float m_scale_factor { 1.0f }
Detailed Description
Member Enumeration Documentation
Type
enum class Slic3r::GUI::Bed3D::Type : unsigned char strong
Enumerator
System
Custom
    {
        // The print bed model and texture are available from some printer preset.
        System,
        // The print bed model is unknown, thus it is rendered procedurally.
        Custom
    };
Constructor & Destructor Documentation
Bed3D()
Slic3r::GUI::Bed3D::Bed3D () default
~Bed3D()
Slic3r::GUI::Bed3D::~Bed3D () default
Member Function Documentation
build_volume()
const BuildVolume & Slic3r::GUI::Bed3D::build_volume () const inline
{ return m_build_volume; }
References m_build_volume.
Referenced by Slic3r::GUI::GLCanvas3D::_max_bounding_box(), Slic3r::GUI::GLCanvas3D::check_volumes_outside_state(), Slic3r::GUI::GLCanvas3D::get_size_proportional_to_max_bed_size(), Slic3r::GUI::GLCanvas3D::load_preview(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLCanvas3D::scene_bounding_box(), and Slic3r::GUI::GLCanvas3D::zoom_to_bed().
calc_extended_bounding_box()
BoundingBoxf3 Slic3r::GUI::Bed3D::calc_extended_bounding_box () const private
{
    BoundingBoxf3 out { m_build_volume.bounding_volume() };
    const Vec3d size = out.size();
    // ensures that the bounding box is set as defined or the following calls to merge() will not work as intented
    if (size.x() > 0.0 && size.y() > 0.0 && !out.defined)
        out.defined = true;
    // Reset the build volume Z, we don't want to zoom to the top of the build volume if it is empty.
    out.min.z() = 0.0;
    out.max.z() = 0.0;
    // extend to origin in case origin is off bed
    out.merge(m_axes.get_origin());
    // extend to contain axes
    out.merge(m_axes.get_origin() + m_axes.get_total_length() * Vec3d::Ones());
    out.merge(out.min + Vec3d(-m_axes.get_tip_radius(), -m_axes.get_tip_radius(), out.max.z()));
    // extend to contain model, if any
    BoundingBoxf3 model_bb = m_model.model.get_bounding_box();
    if (model_bb.defined) {
        model_bb.translate(m_model_offset);
        out.merge(model_bb);
    }
    return out;
}
References Slic3r::BuildVolume::bounding_volume(), Slic3r::BoundingBoxBase< PointType, APointsType >::defined, Slic3r::GUI::GLModel::get_bounding_box(), Slic3r::GUI::CoordAxes::get_origin(), Slic3r::GUI::CoordAxes::get_tip_radius(), Slic3r::GUI::CoordAxes::get_total_length(), m_axes, m_build_volume, m_model, m_model_offset, Slic3r::GUI::PickingModel::model, and Slic3r::BoundingBox3Base< PointType >::translate().
Referenced by render_model(), and set_shape().
contains()
bool Slic3r::GUI::Bed3D::contains (const Point & point) const
{
    return m_polygon.contains(point);
}
References Slic3r::Polygon::contains(), and m_polygon.
detect_type()
std::tuple< Bed3D::Type, std::string, std::string > Slic3r::GUI::Bed3D::detect_type (const Pointfs & shape) static private
{
    auto bundle = wxGetApp().preset_bundle;
    if (bundle != nullptr) {
        const Preset* curr = &bundle->printers.get_selected_preset();
        while (curr != nullptr) {
            if (curr->config.has("bed_shape")) {
                if (shape == dynamic_cast<const ConfigOptionPoints*>(curr->config.option("bed_shape"))->values) {
                    std::string model_filename = PresetUtils::system_printer_bed_model(*curr);
                    std::string texture_filename = PresetUtils::system_printer_bed_texture(*curr);
                    if (!model_filename.empty() && !texture_filename.empty())
                        return { Type::System, model_filename, texture_filename };
                }
            }
            curr = bundle->printers.get_preset_parent(*curr);
        }
    }
    return { Type::Custom, {}, {} };
}
References Slic3r::Preset::config, Custom, Slic3r::ConfigOptionResolver::has(), Slic3r::ConfigBase::option(), System, Slic3r::PresetUtils::system_printer_bed_model(), Slic3r::PresetUtils::system_printer_bed_texture(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by set_shape().
extended_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::Bed3D::extended_bounding_box () const inline
{ return m_extended_bounding_box; }
References m_extended_bounding_box.
Referenced by Slic3r::GUI::GLCanvas3D::_max_bounding_box(), Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), and Slic3r::GUI::GLCanvas3D::scene_bounding_box().
get_type()
Type Slic3r::GUI::Bed3D::get_type () const inline
{ return m_type; }
References m_type.
init_contourlines()
void Slic3r::GUI::Bed3D::init_contourlines () private
{
    if (m_contourlines.is_initialized())
        return;
    if (m_contour.empty())
        return;
    const Lines contour_lines = to_lines(m_contour);
    GLModel::Geometry init_data;
    init_data.format = { GLModel::Geometry::EPrimitiveType::Lines, GLModel::Geometry::EVertexLayout::P3 };
    init_data.reserve_vertices(2 * contour_lines.size());
    init_data.reserve_indices(2 * contour_lines.size());
    for (const Slic3r::Line& l : contour_lines) {
        init_data.add_vertex(Vec3f(unscale<float>(l.a.x()), unscale<float>(l.a.y()), GROUND_Z));
        init_data.add_vertex(Vec3f(unscale<float>(l.b.x()), unscale<float>(l.b.y()), GROUND_Z));
        const unsigned int vertices_counter = (unsigned int)init_data.vertices_count();
        init_data.add_line(vertices_counter - 2, vertices_counter - 1);
    }
    m_contourlines.init_from(std::move(init_data));
    m_contourlines.set_color({ 1.0f, 1.0f, 1.0f, 0.5f });
}
References Slic3r::GUI::GLModel::Geometry::add_line(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::ExPolygon::empty(), Slic3r::GUI::GLModel::Geometry::format, GROUND_Z, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::GLModel::Geometry::Lines, m_contour, m_contourlines, Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::set_color(), Slic3r::to_lines(), and Slic3r::GUI::GLModel::Geometry::vertices_count().
Referenced by render_contour().
init_gridlines()
void Slic3r::GUI::Bed3D::init_gridlines () private
{
    if (m_gridlines.is_initialized())
        return;
    if (m_contour.empty())
        return;
    const BoundingBox& bed_bbox = m_contour.contour.bounding_box();
    const coord_t step = scale_(10.0);
    Polylines axes_lines;
    for (coord_t x = bed_bbox.min.x(); x <= bed_bbox.max.x(); x += step) {
        Polyline line;
        line.append(Point(x, bed_bbox.min.y()));
        line.append(Point(x, bed_bbox.max.y()));
        axes_lines.push_back(line);
    }
    for (coord_t y = bed_bbox.min.y(); y <= bed_bbox.max.y(); y += step) {
        Polyline line;
        line.append(Point(bed_bbox.min.x(), y));
        line.append(Point(bed_bbox.max.x(), y));
        axes_lines.push_back(line);
    }
    // clip with a slightly grown expolygon because our lines lay on the contours and may get erroneously clipped
    Lines gridlines = to_lines(intersection_pl(axes_lines, offset(m_contour, float(SCALED_EPSILON))));
    // append bed contours
    Lines contour_lines = to_lines(m_contour);
    std::copy(contour_lines.begin(), contour_lines.end(), std::back_inserter(gridlines));
    GLModel::Geometry init_data;
    init_data.format = { GLModel::Geometry::EPrimitiveType::Lines, GLModel::Geometry::EVertexLayout::P3 };
    init_data.reserve_vertices(2 * gridlines.size());
    init_data.reserve_indices(2 * gridlines.size());
    for (const Slic3r::Line& l : gridlines) {
        init_data.add_vertex(Vec3f(unscale<float>(l.a.x()), unscale<float>(l.a.y()), GROUND_Z));
        init_data.add_vertex(Vec3f(unscale<float>(l.b.x()), unscale<float>(l.b.y()), GROUND_Z));
        const unsigned int vertices_counter = (unsigned int)init_data.vertices_count();
        init_data.add_line(vertices_counter - 2, vertices_counter - 1);
    }
    m_gridlines.init_from(std::move(init_data));
}
References Slic3r::GUI::GLModel::Geometry::add_line(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::Polyline::append(), Slic3r::MultiPoint::bounding_box(), Slic3r::ExPolygon::contour, Slic3r::ExPolygon::empty(), Slic3r::GUI::GLModel::Geometry::format, GROUND_Z, Slic3r::GUI::GLModel::init_from(), Slic3r::intersection_pl(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::GLModel::Geometry::Lines, m_contour, m_gridlines, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::offset(), Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), scale_, SCALED_EPSILON, Slic3r::to_lines(), and Slic3r::GUI::GLModel::Geometry::vertices_count().
Referenced by render_default().
init_triangles()
void Slic3r::GUI::Bed3D::init_triangles () private
{
    if (m_triangles.is_initialized())
        return;
    if (m_contour.empty())
        return;
    const std::vector<Vec2f> triangles = triangulate_expolygon_2f(m_contour, NORMALS_UP);
    if (triangles.empty() || triangles.size() % 3 != 0)
        return;
    GLModel::Geometry init_data;
    init_data.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P3T2 };
    init_data.reserve_vertices(triangles.size());
    init_data.reserve_indices(triangles.size() / 3);
    Vec2f min = triangles.front();
    Vec2f max = min;
    for (const Vec2f& v : triangles) {
        min = min.cwiseMin(v).eval();
        max = max.cwiseMax(v).eval();
    }
    const Vec2f size = max - min;
    if (size.x() <= 0.0f || size.y() <= 0.0f)
        return;
    Vec2f inv_size = size.cwiseInverse();
    inv_size.y() *= -1.0f;
    // vertices + indices
    unsigned int vertices_counter = 0;
    for (const Vec2f& v : triangles) {
        const Vec3f p = { v.x(), v.y(), GROUND_Z };
        init_data.add_vertex(p, (Vec2f)(v - min).cwiseProduct(inv_size).eval());
        ++vertices_counter;
        if (vertices_counter % 3 == 0)
            init_data.add_triangle(vertices_counter - 3, vertices_counter - 2, vertices_counter - 1);
    }
    if (m_model.model.get_filename().empty() && m_model.mesh_raycaster == nullptr)
        // register for picking
        register_raycasters_for_picking(init_data, Transform3d::Identity());
    m_triangles.init_from(std::move(init_data));
    m_triangles.set_color(DEFAULT_MODEL_COLOR);
}
References Slic3r::GUI::GLModel::Geometry::add_triangle(), Slic3r::GUI::GLModel::Geometry::add_vertex(), DEFAULT_MODEL_COLOR, Slic3r::ExPolygon::empty(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::GLModel::get_filename(), GROUND_Z, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), m_contour, m_model, m_triangles, Slic3r::GUI::PickingModel::mesh_raycaster, Slic3r::GUI::PickingModel::model, Slic3r::NORMALS_UP, Slic3r::GUI::GLModel::Geometry::P3T2, register_raycasters_for_picking(), Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLModel::set_color(), Slic3r::GUI::GLModel::Geometry::Triangles, and Slic3r::triangulate_expolygon_2f().
Referenced by render_default(), and render_texture().
is_custom()
bool Slic3r::GUI::Bed3D::is_custom () const inline
{ return m_type == Type::Custom; }
References Custom, and m_type.
point_projection()
Point Slic3r::GUI::Bed3D::point_projection (const Point & point) const
{
    return m_polygon.point_projection(point);
}
References m_polygon, and Slic3r::Polygon::point_projection().
register_raycasters_for_picking()
void Slic3r::GUI::Bed3D::register_raycasters_for_picking (const GLModel::Geometry & geometry, const Transform3d & trafo) private
{
    assert(m_model.mesh_raycaster == nullptr);
    indexed_triangle_set its;
    its.vertices.reserve(geometry.vertices_count());
    for (size_t i = 0; i < geometry.vertices_count(); ++i) {
        its.vertices.emplace_back(geometry.extract_position_3(i));
    }
    its.indices.reserve(geometry.indices_count() / 3);
    for (size_t i = 0; i < geometry.indices_count() / 3; ++i) {
        const size_t tri_id = i * 3;
        its.indices.emplace_back(geometry.extract_index(tri_id), geometry.extract_index(tri_id + 1), geometry.extract_index(tri_id + 2));
    }
    m_model.mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
    wxGetApp().plater()->canvas3D()->add_raycaster_for_picking(SceneRaycaster::EType::Bed, 0, *m_model.mesh_raycaster, trafo);
}
References Slic3r::GUI::SceneRaycaster::Bed, Slic3r::GUI::GLModel::Geometry::extract_index(), Slic3r::GUI::GLModel::Geometry::extract_position_3(), indexed_triangle_set::indices, Slic3r::GUI::GLModel::Geometry::indices_count(), m_model, Slic3r::GUI::PickingModel::mesh_raycaster, indexed_triangle_set::vertices, and Slic3r::GUI::GLModel::Geometry::vertices_count().
Referenced by init_triangles(), and render_model().
render()
void Slic3r::GUI::Bed3D::render (GLCanvas3D & canvas, const Transform3d & view_matrix, const Transform3d & projection_matrix, bool bottom, float scale_factor, bool show_texture)
{
    render_internal(canvas, view_matrix, projection_matrix, bottom, scale_factor, show_texture, false);
}
References render_internal().
render_axes()
void Slic3r::GUI::Bed3D::render_axes ()
{
    if (m_build_volume.valid())
        m_axes.render(Transform3d::Identity(), 0.25f);
}
References Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), m_axes, m_build_volume, Slic3r::GUI::CoordAxes::render(), and Slic3r::BuildVolume::valid().
render_contour()
void Slic3r::GUI::Bed3D::render_contour (const Transform3d & view_matrix, const Transform3d & projection_matrix) private
{
    init_contourlines();
    GLShaderProgram* shader = wxGetApp().get_shader("flat");
    if (shader != nullptr) {
        shader->start_using();
        shader->set_uniform("view_model_matrix", view_matrix);
        shader->set_uniform("projection_matrix", projection_matrix);
        glsafe(::glEnable(GL_DEPTH_TEST));
        glsafe(::glEnable(GL_BLEND));
        glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
        // draw contour
#if ENABLE_GL_CORE_PROFILE
        if (!OpenGLManager::get_gl_info().is_core_profile())
#endif // ENABLE_GL_CORE_PROFILE
            glsafe(::glLineWidth(1.5f * m_scale_factor));
        m_contourlines.render();
        glsafe(::glDisable(GL_BLEND));
        shader->stop_using();
    }
}
References Slic3r::GUI::OpenGLManager::get_gl_info(), glsafe, init_contourlines(), m_contourlines, m_scale_factor, Slic3r::GUI::GLModel::render(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by render_custom(), render_default(), and render_system().
render_custom()
void Slic3r::GUI::Bed3D::render_custom (GLCanvas3D & canvas, const Transform3d & view_matrix, const Transform3d & projection_matrix, bool bottom, bool show_texture, bool picking) private
{
    if (m_texture_filename.empty() && m_model_filename.empty()) {
        render_default(bottom, picking, show_texture, view_matrix, projection_matrix);
        return;
    }
    if (!bottom)
        render_model(view_matrix, projection_matrix);
    if (show_texture)
        render_texture(bottom, canvas, view_matrix, projection_matrix);
    else if (bottom)
        render_contour(view_matrix, projection_matrix);
}
References m_model_filename, m_texture_filename, render_contour(), render_default(), render_model(), and render_texture().
Referenced by render_internal().
render_default()
void Slic3r::GUI::Bed3D::render_default (bool bottom, bool picking, bool show_texture, const Transform3d & view_matrix, const Transform3d & projection_matrix) private
{
    m_texture.reset();
    init_gridlines();
    init_triangles();
    GLShaderProgram* shader = wxGetApp().get_shader("flat");
    if (shader != nullptr) {
        shader->start_using();
        shader->set_uniform("view_model_matrix", view_matrix);
        shader->set_uniform("projection_matrix", projection_matrix);
        glsafe(::glEnable(GL_DEPTH_TEST));
        glsafe(::glEnable(GL_BLEND));
        glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
        const bool has_model = !m_model.model.get_filename().empty();
        if (!has_model && !bottom) {
            // draw background
            glsafe(::glDepthMask(GL_FALSE));
            m_triangles.render();
            glsafe(::glDepthMask(GL_TRUE));
        }
        if (show_texture) {
            // draw grid
#if ENABLE_GL_CORE_PROFILE
            if (!OpenGLManager::get_gl_info().is_core_profile())
#endif // ENABLE_GL_CORE_PROFILE
                glsafe(::glLineWidth(1.5f * m_scale_factor));
            m_gridlines.set_color(has_model && !bottom ? DEFAULT_SOLID_GRID_COLOR : DEFAULT_TRANSPARENT_GRID_COLOR);
            m_gridlines.render();
        }
        else
            render_contour(view_matrix, projection_matrix);
        glsafe(::glDisable(GL_BLEND));
        shader->stop_using();
    }
}
References DEFAULT_SOLID_GRID_COLOR, DEFAULT_TRANSPARENT_GRID_COLOR, Slic3r::GUI::GLModel::get_filename(), Slic3r::GUI::OpenGLManager::get_gl_info(), GL_FALSE, GL_TRUE, glsafe, init_gridlines(), init_triangles(), m_gridlines, m_model, m_scale_factor, m_texture, m_triangles, Slic3r::GUI::PickingModel::model, Slic3r::GUI::GLModel::render(), render_contour(), Slic3r::GUI::GLTexture::reset(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by render_custom(), and render_texture().
render_for_picking()
void Slic3r::GUI::Bed3D::render_for_picking (GLCanvas3D & canvas, const Transform3d & view_matrix, const Transform3d & projection_matrix, bool bottom, float scale_factor)
{
    render_internal(canvas, view_matrix, projection_matrix, bottom, scale_factor, false, true);
}
References render_internal().
render_internal()
void Slic3r::GUI::Bed3D::render_internal (GLCanvas3D & canvas, const Transform3d & view_matrix, const Transform3d & projection_matrix, bool bottom, float scale_factor, bool show_texture, bool picking) private
{
    m_scale_factor = scale_factor;
    glsafe(::glEnable(GL_DEPTH_TEST));
    m_model.model.set_color(picking ? PICKING_MODEL_COLOR : DEFAULT_MODEL_COLOR);
    switch (m_type)
    {
    case Type::System: { render_system(canvas, view_matrix, projection_matrix, bottom, show_texture); break; }
    default:
    case Type::Custom: { render_custom(canvas, view_matrix, projection_matrix, bottom, show_texture, picking); break; }
    }
    glsafe(::glDisable(GL_DEPTH_TEST));
}
References Custom, DEFAULT_MODEL_COLOR, glsafe, m_model, m_scale_factor, m_type, Slic3r::GUI::PickingModel::model, PICKING_MODEL_COLOR, render_custom(), render_system(), Slic3r::GUI::GLModel::set_color(), and System.
Referenced by render(), and render_for_picking().
render_model()
void Slic3r::GUI::Bed3D::render_model (const Transform3d & view_matrix, const Transform3d & projection_matrix) private
{
    if (m_model_filename.empty())
        return;
    if (m_model.model.get_filename() != m_model_filename && m_model.model.init_from_file(m_model_filename)) {
        m_model.model.set_color(DEFAULT_MODEL_COLOR);
        // move the model so that its origin (0.0, 0.0, 0.0) goes into the bed shape center and a bit down to avoid z-fighting with the texture quad
        m_model_offset = to_3d(m_build_volume.bounding_volume2d().center(), -0.03);
        // register for picking
        const std::vector<std::shared_ptr<SceneRaycasterItem>>* const raycaster = wxGetApp().plater()->canvas3D()->get_raycasters_for_picking(SceneRaycaster::EType::Bed);
        if (!raycaster->empty()) {
            // The raycaster may have been set by the call to init_triangles() made from render_texture() if the printbed was
            // changed while the camera was pointing upward.
            // In this case we need to remove it before creating a new using the model geometry
            wxGetApp().plater()->canvas3D()->remove_raycasters_for_picking(SceneRaycaster::EType::Bed);
            m_model.mesh_raycaster.reset();
        }
        register_raycasters_for_picking(m_model.model.get_geometry(), Geometry::translation_transform(m_model_offset));
        // update extended bounding box
        m_extended_bounding_box = this->calc_extended_bounding_box();
    }
    if (!m_model.model.get_filename().empty()) {
        GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
        if (shader != nullptr) {
            shader->start_using();
            shader->set_uniform("emission_factor", 0.0f);
            const Transform3d model_matrix = Geometry::translation_transform(m_model_offset);
            shader->set_uniform("view_model_matrix", view_matrix * model_matrix);
            shader->set_uniform("projection_matrix", projection_matrix);
            const Matrix3d view_normal_matrix = view_matrix.matrix().block(0, 0, 3, 3) * model_matrix.matrix().block(0, 0, 3, 3).inverse().transpose();
            shader->set_uniform("view_normal_matrix", view_normal_matrix);
            m_model.model.render();
            shader->stop_using();
        }
    }
}
References Slic3r::GUI::SceneRaycaster::Bed, Slic3r::BuildVolume::bounding_volume2d(), calc_extended_bounding_box(), Slic3r::BoundingBoxBase< PointType, APointsType >::center(), DEFAULT_MODEL_COLOR, Slic3r::GUI::GLModel::get_filename(), Slic3r::GUI::GLModel::get_geometry(), Slic3r::GUI::GLModel::init_from_file(), m_build_volume, m_extended_bounding_box, m_model, m_model_filename, m_model_offset, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::PickingModel::mesh_raycaster, Slic3r::GUI::PickingModel::model, register_raycasters_for_picking(), Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::to_3d(), and Slic3r::Geometry::translation_transform().
Referenced by render_custom(), and render_system().
render_system()
void Slic3r::GUI::Bed3D::render_system (GLCanvas3D & canvas, const Transform3d & view_matrix, const Transform3d & projection_matrix, bool bottom, bool show_texture) private
{
    if (!bottom)
        render_model(view_matrix, projection_matrix);
    if (show_texture)
        render_texture(bottom, canvas, view_matrix, projection_matrix);
    else if (bottom)
        render_contour(view_matrix, projection_matrix);
}
References render_contour(), render_model(), and render_texture().
Referenced by render_internal().
render_texture()
void Slic3r::GUI::Bed3D::render_texture (bool bottom, GLCanvas3D & canvas, const Transform3d & view_matrix, const Transform3d & projection_matrix) private
{
    if (m_texture_filename.empty()) {
        m_texture.reset();
        render_default(bottom, false, true, view_matrix, projection_matrix);
        return;
    }
    if (m_texture.get_id() == 0 || m_texture.get_source() != m_texture_filename) {
        m_texture.reset();
        if (boost::algorithm::iends_with(m_texture_filename, ".svg")) {
            // use higher resolution images if graphic card and opengl version allow
            GLint max_tex_size = OpenGLManager::get_gl_info().get_max_tex_size();
            if (m_temp_texture.get_id() == 0 || m_temp_texture.get_source() != m_texture_filename) {
                // generate a temporary lower resolution texture to show while no main texture levels have been compressed
                if (!m_temp_texture.load_from_svg_file(m_texture_filename, false, false, false, max_tex_size / 8)) {
                    render_default(bottom, false, true, view_matrix, projection_matrix);
                    return;
                }
                canvas.request_extra_frame();
            }
            // starts generating the main texture, compression will run asynchronously
            if (!m_texture.load_from_svg_file(m_texture_filename, true, true, true, max_tex_size)) {
                render_default(bottom, false, true, view_matrix, projection_matrix);
                return;
            }
        }
        else if (boost::algorithm::iends_with(m_texture_filename, ".png")) {
            // generate a temporary lower resolution texture to show while no main texture levels have been compressed
            if (m_temp_texture.get_id() == 0 || m_temp_texture.get_source() != m_texture_filename) {
                if (!m_temp_texture.load_from_file(m_texture_filename, false, GLTexture::None, false)) {
                    render_default(bottom, false, true, view_matrix, projection_matrix);
                    return;
                }
                canvas.request_extra_frame();
            }
            // starts generating the main texture, compression will run asynchronously
            if (!m_texture.load_from_file(m_texture_filename, true, GLTexture::MultiThreaded, true)) {
                render_default(bottom, false, true, view_matrix, projection_matrix);
                return;
            }
        }
        else {
            render_default(bottom, false, true, view_matrix, projection_matrix);
            return;
        }
    }
    else if (m_texture.unsent_compressed_data_available()) {
        // sends to gpu the already available compressed levels of the main texture
        m_texture.send_compressed_data_to_gpu();
        // the temporary texture is not needed anymore, reset it
        if (m_temp_texture.get_id() != 0)
            m_temp_texture.reset();
        canvas.request_extra_frame();
    }
    init_triangles();
    GLShaderProgram* shader = wxGetApp().get_shader("printbed");
    if (shader != nullptr) {
        shader->start_using();
        shader->set_uniform("view_model_matrix", view_matrix);
        shader->set_uniform("projection_matrix", projection_matrix);
        shader->set_uniform("transparent_background", bottom);
        shader->set_uniform("svg_source", boost::algorithm::iends_with(m_texture.get_source(), ".svg"));
        glsafe(::glEnable(GL_DEPTH_TEST));
        if (bottom)
            glsafe(::glDepthMask(GL_FALSE));
        glsafe(::glEnable(GL_BLEND));
        glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
        if (bottom)
            glsafe(::glFrontFace(GL_CW));
        // show the temporary texture while no compressed data is available
        GLuint tex_id = (GLuint)m_temp_texture.get_id();
        if (tex_id == 0)
            tex_id = (GLuint)m_texture.get_id();
        glsafe(::glBindTexture(GL_TEXTURE_2D, tex_id));
        m_triangles.render();
        glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
        if (bottom)
            glsafe(::glFrontFace(GL_CCW));
        glsafe(::glDisable(GL_BLEND));
        if (bottom)
            glsafe(::glDepthMask(GL_TRUE));
        shader->stop_using();
    }
}
References Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::OpenGLManager::GLInfo::get_max_tex_size(), Slic3r::GUI::GLTexture::get_source(), GL_FALSE, GL_TRUE, glsafe, init_triangles(), Slic3r::GUI::GLTexture::load_from_file(), Slic3r::GUI::GLTexture::load_from_svg_file(), m_temp_texture, m_texture, m_texture_filename, m_triangles, Slic3r::GUI::GLTexture::MultiThreaded, Slic3r::GUI::GLTexture::None, Slic3r::GUI::GLModel::render(), render_default(), Slic3r::GUI::GLCanvas3D::request_extra_frame(), Slic3r::GUI::GLTexture::reset(), Slic3r::GUI::GLTexture::send_compressed_data_to_gpu(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), and Slic3r::GUI::GLTexture::unsent_compressed_data_available().
Referenced by render_custom(), and render_system().
set_shape()
bool Slic3r::GUI::Bed3D::set_shape (const Pointfs & bed_shape, const double max_print_height, const std::string & custom_texture, const std::string & custom_model, bool force_as_custom = false)
{
    auto check_texture = [](const std::string& texture) {
        boost::system::error_code ec; // so the exists call does not throw (e.g. after a permission problem)
        return !texture.empty() && (boost::algorithm::iends_with(texture, ".png") || boost::algorithm::iends_with(texture, ".svg")) && boost::filesystem::exists(texture, ec);
    };
    auto check_model = [](const std::string& model) {
        boost::system::error_code ec;
        return !model.empty() && boost::algorithm::iends_with(model, ".stl") && boost::filesystem::exists(model, ec);
    };
    Type type;
    std::string model;
    std::string texture;
    if (force_as_custom)
        type = Type::Custom;
    else {
        auto [new_type, system_model, system_texture] = detect_type(bed_shape);
        type = new_type;
        model = system_model;
        texture = system_texture;
    }
    std::string texture_filename = custom_texture.empty() ? texture : custom_texture;
    if (! texture_filename.empty() && ! check_texture(texture_filename)) {
        BOOST_LOG_TRIVIAL(error) << "Unable to load bed texture: " << texture_filename;
        texture_filename.clear();
    }
    std::string model_filename = custom_model.empty() ? model : custom_model;
    if (! model_filename.empty() && ! check_model(model_filename)) {
        BOOST_LOG_TRIVIAL(error) << "Unable to load bed model: " << model_filename;
        model_filename.clear();
    }
    if (m_build_volume.bed_shape() == bed_shape && m_build_volume.max_print_height() == max_print_height && m_type == type && m_texture_filename == texture_filename && m_model_filename == model_filename)
        // No change, no need to update the UI.
        return false;
    m_type = type;
    m_build_volume = BuildVolume { bed_shape, max_print_height };
    m_texture_filename = texture_filename;
    m_model_filename = model_filename;
    m_extended_bounding_box = this->calc_extended_bounding_box();
    m_contour = ExPolygon(Polygon::new_scale(bed_shape));
    const BoundingBox bbox = m_contour.contour.bounding_box();
    if (!bbox.defined)
        throw RuntimeError(std::string("Invalid bed shape"));
    m_polygon = offset(m_contour.contour, (float)bbox.radius() * 1.7f, jtRound, scale_(0.5)).front();
    m_triangles.reset();
    m_gridlines.reset();
    m_contourlines.reset();
    m_texture.reset();
    m_model.reset();
    // Set the origin and size for rendering the coordinate system axes.
    m_axes.set_origin({ 0.0, 0.0, static_cast<double>(GROUND_Z) });
    m_axes.set_stem_length(0.1f * static_cast<float>(m_build_volume.bounding_volume().max_size()));
    // unregister from picking
    wxGetApp().plater()->canvas3D()->remove_raycasters_for_picking(SceneRaycaster::EType::Bed);
    // Let the calee to update the UI.
    return true;
}
References Slic3r::GUI::SceneRaycaster::Bed, Slic3r::BuildVolume::bed_shape(), Slic3r::MultiPoint::bounding_box(), Slic3r::BuildVolume::bounding_volume(), calc_extended_bounding_box(), Slic3r::ExPolygon::contour, Custom, Slic3r::BoundingBoxBase< PointType, APointsType >::defined, detect_type(), error, GROUND_Z, m_axes, m_build_volume, m_contour, m_contourlines, m_extended_bounding_box, m_gridlines, m_model, m_model_filename, m_polygon, m_texture, m_texture_filename, m_triangles, m_type, Slic3r::max_print_height(), Slic3r::BuildVolume::max_print_height(), Slic3r::BoundingBox3Base< PointType >::max_size(), Slic3r::Polygon::new_scale(), Slic3r::offset(), Slic3r::BoundingBoxBase< PointType, APointsType >::radius(), Slic3r::GUI::GLModel::reset(), Slic3r::GUI::GLTexture::reset(), Slic3r::GUI::PickingModel::reset(), scale_, Slic3r::GUI::CoordAxes::set_origin(), and Slic3r::GUI::CoordAxes::set_stem_length().
Member Data Documentation
m_axes
CoordAxes Slic3r::GUI::Bed3D::m_axes private
Referenced by calc_extended_bounding_box(), render_axes(), and set_shape().
m_build_volume
BuildVolume Slic3r::GUI::Bed3D::m_build_volume private
Referenced by build_volume(), calc_extended_bounding_box(), render_axes(), render_model(), and set_shape().
m_contour
ExPolygon Slic3r::GUI::Bed3D::m_contour private
Referenced by init_contourlines(), init_gridlines(), init_triangles(), and set_shape().
m_contourlines
GLModel Slic3r::GUI::Bed3D::m_contourlines private
Referenced by init_contourlines(), render_contour(), and set_shape().
m_extended_bounding_box
BoundingBoxf3 Slic3r::GUI::Bed3D::m_extended_bounding_box private
Referenced by extended_bounding_box(), render_model(), and set_shape().
m_gridlines
GLModel Slic3r::GUI::Bed3D::m_gridlines private
Referenced by init_gridlines(), render_default(), and set_shape().
m_model
PickingModel Slic3r::GUI::Bed3D::m_model private
Referenced by calc_extended_bounding_box(), init_triangles(), register_raycasters_for_picking(), render_default(), render_internal(), render_model(), and set_shape().
m_model_filename
std::string Slic3r::GUI::Bed3D::m_model_filename private
Referenced by render_custom(), render_model(), and set_shape().
m_model_offset
Vec3d Slic3r::GUI::Bed3D::m_model_offset { Vec3d::Zero() } private
Referenced by calc_extended_bounding_box(), and render_model().
m_polygon
Polygon Slic3r::GUI::Bed3D::m_polygon private
Referenced by contains(), point_projection(), and set_shape().
m_scale_factor
float Slic3r::GUI::Bed3D::m_scale_factor { 1.0f } private
Referenced by render_contour(), render_default(), and render_internal().
m_temp_texture
GLTexture Slic3r::GUI::Bed3D::m_temp_texture private
Referenced by render_texture().
m_texture
GLTexture Slic3r::GUI::Bed3D::m_texture private
Referenced by render_default(), render_texture(), and set_shape().
m_texture_filename
std::string Slic3r::GUI::Bed3D::m_texture_filename private
Referenced by render_custom(), render_texture(), and set_shape().
m_triangles
GLModel Slic3r::GUI::Bed3D::m_triangles private
Referenced by init_triangles(), render_default(), render_texture(), and set_shape().
m_type
Type Slic3r::GUI::Bed3D::m_type { Type::Custom } private
Referenced by get_type(), is_custom(), render_internal(), and set_shape().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DBed.hpp
src/slic3r/GUI/3DBed.cpp