Prusa Slicer: src/avrdude/pickit2.c File Reference
pickit2.c File Reference
#include "ac_cfg.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <unistd.h>
#include "avrdude.h"
#include "libavrdude.h"
Functions
static int pickit2_nousb_open (struct programmer_t *pgm, char *name)
void pickit2_initpgm (PROGRAMMER *pgm)
Variables
const char pickit2_desc [] = "Microchip's PICkit2 Programmer"
Function Documentation
pickit2_initpgm()
void pickit2_initpgm (PROGRAMMER * pgm)
{
    /*
     * mandatory functions - these are called without checking to see
     * whether they are assigned or not
     */
    pgm->open           = pickit2_nousb_open;
    strncpy(pgm->type, "pickit2", sizeof(pgm->type));
}
References programmer_t::open, pgm, pickit2_nousb_open(), and programmer_t::type.
pickit2_nousb_open()
static int pickit2_nousb_open (struct programmer_t * pgm, char * name) static
{
    avrdude_message(MSG_INFO,
#ifdef WIN32NATIVE
            "%s: error: no usb or hid support. Please compile again with libusb or HID support from Win32 DDK installed.\n",
#else
            "%s: error: no usb support. Please compile again with libusb installed.\n",
#endif
            progname);
    return -1;
}
References avrdude_message(), MSG_INFO, and progname.
Referenced by pickit2_initpgm().
Variable Documentation
pickit2_desc
const char pickit2_desc[] = "Microchip's PICkit2 Programmer"