Prusa Slicer: Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct > Struct Template Reference
Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct > Struct Template Reference
#include <src/eigen/Eigen/src/Core/ProductEvaluators.h>
Classes
struct add
struct adds
struct is_row_major
struct set
struct sub
Public Types
typedef Product< Lhs, Rhs >::Scalar Scalar
Static Public Member Functions
template<typename Dst >
static EIGEN_STRONG_INLINE void evalTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_STRONG_INLINE void addTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_STRONG_INLINE void subTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_STRONG_INLINE void scaleAndAddTo (Dst &dst, const Lhs &lhs, const Rhs &rhs, const Scalar &alpha)
Detailed Description
template<typename Lhs, typename Rhs>
struct Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >
Member Typedef Documentation
Scalar
template<typename Lhs , typename Rhs > typedef Product<Lhs,Rhs>::Scalar Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::Scalar
Member Function Documentation
addTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::addTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
  {
    internal::outer_product_selector_run(dst, lhs, rhs, add(), is_row_major<Dst>());
  }
References Eigen::internal::outer_product_selector_run().
evalTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::evalTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
  {
    internal::outer_product_selector_run(dst, lhs, rhs, set(), is_row_major<Dst>());
  }
References Eigen::internal::outer_product_selector_run().
scaleAndAddTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::scaleAndAddTo (Dst & dst, const Lhs & lhs, const Rhs & rhs, const Scalar & alpha) inline static
  {
    internal::outer_product_selector_run(dst, lhs, rhs, adds(alpha), is_row_major<Dst>());
  }
References Eigen::internal::outer_product_selector_run().
subTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, OuterProduct >::subTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
  {
    internal::outer_product_selector_run(dst, lhs, rhs, sub(), is_row_major<Dst>());
  }
References Eigen::internal::outer_product_selector_run().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/ProductEvaluators.h