Prusa Slicer: DataViewBitmapText Class Reference
DataViewBitmapText Class Reference
#include <src/slic3r/GUI/ExtraRenderers.hpp>
Public Member Functions
DataViewBitmapText (const wxString &text=wxEmptyString, const wxBitmap &bmp=wxNullBitmap)
DataViewBitmapText (const DataViewBitmapText &other)
void SetText (const wxString &text)
wxString GetText () const
void SetBitmap (const wxBitmap &bmp)
const wxBitmap & GetBitmap () const
bool IsSameAs (const DataViewBitmapText &other) const
bool operator== (const DataViewBitmapText &other) const
bool operator!= (const DataViewBitmapText &other) const
Private Member Functions
wxDECLARE_DYNAMIC_CLASS (DataViewBitmapText)
Private Attributes
wxString m_text
wxBitmap m_bmp
Detailed Description
Constructor & Destructor Documentation
DataViewBitmapText() [1/2]
DataViewBitmapText::DataViewBitmapText (const wxString & text = wxEmptyString, const wxBitmap & bmp = wxNullBitmap) inline
                                                            :
        m_text(text),
        m_bmp(bmp)
    { }
DataViewBitmapText() [2/2]
DataViewBitmapText::DataViewBitmapText (const DataViewBitmapText & other) inline
        : wxObject(),
        m_text(other.m_text),
        m_bmp(other.m_bmp)
    { }
Member Function Documentation
GetBitmap()
const wxBitmap & DataViewBitmapText::GetBitmap () const inline
{ return m_bmp; }
References m_bmp.
Referenced by BitmapTextRenderer::GetSize(), BitmapChoiceRenderer::GetSize(), BitmapTextRenderer::Render(), and BitmapChoiceRenderer::Render().
GetText()
wxString DataViewBitmapText::GetText () const inline
{ return m_text; }
References m_text.
Referenced by BitmapTextRenderer::GetSize(), BitmapChoiceRenderer::GetSize(), BitmapTextRenderer::Render(), BitmapChoiceRenderer::Render(), and BitmapTextRenderer::SetValue().
IsSameAs()
bool DataViewBitmapText::IsSameAs (const DataViewBitmapText & other) const inline
{
        return m_text == other.m_text && m_bmp.IsSameAs(other.m_bmp);
    }
References m_bmp, and m_text.
Referenced by operator!=(), and operator==().
operator!=()
bool DataViewBitmapText::operator!= (const DataViewBitmapText & other) const inline
{
        return !IsSameAs(other);
    }
References IsSameAs().
operator==()
bool DataViewBitmapText::operator== (const DataViewBitmapText & other) const inline
{
        return IsSameAs(other);
    }
References IsSameAs().
SetBitmap()
void DataViewBitmapText::SetBitmap (const wxBitmap & bmp) inline
{ m_bmp = bmp; }
References m_bmp.
Referenced by BitmapChoiceRenderer::GetValueFromEditorCtrl().
SetText()
void DataViewBitmapText::SetText (const wxString & text) inline
{ m_text = text; }
References m_text.
Referenced by BitmapTextRenderer::GetValueFromEditorCtrl(), BitmapChoiceRenderer::GetValueFromEditorCtrl(), and Slic3r::GUI::ObjectDataViewModel::SetName().
wxDECLARE_DYNAMIC_CLASS()
DataViewBitmapText::wxDECLARE_DYNAMIC_CLASS (DataViewBitmapText) private
Member Data Documentation
m_bmp
wxBitmap DataViewBitmapText::m_bmp private
Referenced by GetBitmap(), IsSameAs(), and SetBitmap().
m_text
wxString DataViewBitmapText::m_text private
Referenced by GetText(), IsSameAs(), and SetText().
The documentation for this class was generated from the following file:
src/slic3r/GUI/ExtraRenderers.hpp