Prusa Slicer: Slic3r::LinesBucketQueue Class Reference
Slic3r::LinesBucketQueue Class Reference
#include <src/libslic3r/GCode/ConflictChecker.hpp>
Public Member Functions
void emplace_back_bucket (std::vector< ExtrusionPaths > &&paths, const void *objPtr, Points offset)
void build_queue ()
bool valid () const
const void * idToObjsPtr (int id)
double removeLowests ()
LineWithIDs getCurLines () const
Private Attributes
std::vector< LinesBucket > _buckets
std::priority_queue< LinesBucket *, std::vector< LinesBucket * >, LinesBucketPtrComp > _pq
std::map< int, const void * > _idToObjsPtr
std::map< const void *, int > _objsPtrToId
Detailed Description
Member Function Documentation
build_queue()
void Slic3r::LinesBucketQueue::build_queue ()
{
    assert(_pq.empty());
    for (LinesBucket &bucket : _buckets)
        _pq.push(&bucket);
}
References _buckets, and _pq.
Referenced by Slic3r::ConflictChecker::find_inter_of_lines_in_diff_objs().
emplace_back_bucket()
void Slic3r::LinesBucketQueue::emplace_back_bucket (std::vector< ExtrusionPaths > && paths, const void * objPtr, Points offset)
{
    if (_objsPtrToId.find(objPtr) == _objsPtrToId.end()) {
        _objsPtrToId.insert({objPtr, _objsPtrToId.size()});
        _idToObjsPtr.insert({_objsPtrToId.size() - 1, objPtr});
    }
    _buckets.emplace_back(std::move(paths), _objsPtrToId[objPtr], offsets);
}
References _buckets, _idToObjsPtr, and _objsPtrToId.
Referenced by Slic3r::ConflictChecker::find_inter_of_lines_in_diff_objs().
getCurLines()
LineWithIDs Slic3r::LinesBucketQueue::getCurLines () const
{
    LineWithIDs lines;
    for (const LinesBucket &bucket : _buckets) {
        if (bucket.valid()) {
            LineWithIDs tmpLines = bucket.curLines();
            lines.insert(lines.end(), tmpLines.begin(), tmpLines.end());
        }
    }
    return lines;
}
References _buckets.
Referenced by Slic3r::ConflictChecker::find_inter_of_lines_in_diff_objs().
idToObjsPtr()
const void * Slic3r::LinesBucketQueue::idToObjsPtr (int id) inline
    {
        if (_idToObjsPtr.find(id) != _idToObjsPtr.end())
            return _idToObjsPtr[id];
        else
            return nullptr;
    }
References _idToObjsPtr.
removeLowests()
double Slic3r::LinesBucketQueue::removeLowests ()
{
    auto lowest = _pq.top();
    _pq.pop();
    double                     curHeight = lowest->curHeight();
    std::vector<LinesBucket *> lowests;
    lowests.push_back(lowest);
    while (_pq.empty() == false && std::abs(_pq.top()->curHeight() - lowest->curHeight()) < EPSILON) {
        lowests.push_back(_pq.top());
        _pq.pop();
    }
    for (LinesBucket *bp : lowests) {
        bp->raise();
        if (bp->valid()) { _pq.push(bp); }
    }
    return curHeight;
}
References _pq, and EPSILON.
Referenced by Slic3r::ConflictChecker::find_inter_of_lines_in_diff_objs().
valid()
bool Slic3r::LinesBucketQueue::valid () const inline
{ return _pq.empty() == false; }
References _pq.
Referenced by Slic3r::ConflictChecker::find_inter_of_lines_in_diff_objs().
Member Data Documentation
_buckets
std::vector<LinesBucket> Slic3r::LinesBucketQueue::_buckets private
Referenced by build_queue(), emplace_back_bucket(), and getCurLines().
_idToObjsPtr
std::map<int, const void *> Slic3r::LinesBucketQueue::_idToObjsPtr private
Referenced by emplace_back_bucket(), and idToObjsPtr().
_objsPtrToId
std::map<const void *, int> Slic3r::LinesBucketQueue::_objsPtrToId private
Referenced by emplace_back_bucket().
_pq
std::priority_queue<LinesBucket *, std::vector<LinesBucket *>, LinesBucketPtrComp> Slic3r::LinesBucketQueue::_pq private
Referenced by build_queue(), removeLowests(), and valid().
The documentation for this class was generated from the following files:
src/libslic3r/GCode/ConflictChecker.hpp
src/libslic3r/GCode/ConflictChecker.cpp