Prusa Slicer: Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType > Class Template Reference
Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType > Class Template Reference
Computes eigenvalues and eigenvectors of the generalized selfadjoint eigen problem.
#include <src/eigen/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h>
Public Types
typedef _MatrixType MatrixType
enum { Size = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , Options = MatrixType::Options , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type _MatrixType.
typedef Eigen::Index Index
typedef Matrix< Scalar, Size, Size, ColMajor, MaxColsAtCompileTime, MaxColsAtCompileTime > EigenvectorsType
typedef NumTraits< Scalar >::Real RealScalar
Real scalar type for _MatrixType.
typedef internal::plain_col_type< MatrixType, RealScalar >::type RealVectorType
Type for vector of eigenvalues as returned by eigenvalues().
typedef Tridiagonalization< MatrixType > TridiagonalizationType
typedef TridiagonalizationType::SubDiagonalType SubDiagonalType
Public Member Functions
GeneralizedSelfAdjointEigenSolver ()
Default constructor for fixed-size matrices.
GeneralizedSelfAdjointEigenSolver (Index size)
Constructor, pre-allocates memory for dynamic-size matrices.
GeneralizedSelfAdjointEigenSolver (const MatrixType &matA, const MatrixType &matB, int options=ComputeEigenvectors|Ax_lBx)
Constructor; computes generalized eigendecomposition of given matrix pencil.
GeneralizedSelfAdjointEigenSolver & compute (const MatrixType &matA, const MatrixType &matB, int options=ComputeEigenvectors|Ax_lBx)
Computes generalized eigendecomposition of given matrix pencil.
template<typename InputType >
EIGEN_DEVICE_FUNC SelfAdjointEigenSolver & compute (const EigenBase< InputType > &matrix, int options=ComputeEigenvectors)
Computes eigendecomposition of given matrix.
EIGEN_DEVICE_FUNC SelfAdjointEigenSolver & computeDirect (const MatrixType &matrix, int options=ComputeEigenvectors)
Computes eigendecomposition of given matrix using a closed-form algorithm.
SelfAdjointEigenSolver & computeFromTridiagonal (const RealVectorType &diag, const SubDiagonalType &subdiag, int options=ComputeEigenvectors)
Computes the eigen decomposition from a tridiagonal symmetric matrix.
EIGEN_DEVICE_FUNC const EigenvectorsType & eigenvectors () const
Returns the eigenvectors of given matrix.
EIGEN_DEVICE_FUNC const RealVectorType & eigenvalues () const
Returns the eigenvalues of given matrix.
EIGEN_DEVICE_FUNC MatrixType operatorSqrt () const
Computes the positive-definite square root of the matrix.
EIGEN_DEVICE_FUNC MatrixType operatorInverseSqrt () const
Computes the inverse square root of the matrix.
EIGEN_DEVICE_FUNC ComputationInfo info () const
Reports whether previous computation was successful.
Static Public Attributes
static const int m_maxIterations = 30
Maximum number of iterations.
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
EigenvectorsType m_eivec
RealVectorType m_eivalues
TridiagonalizationType::SubDiagonalType m_subdiag
ComputationInfo m_info
bool m_isInitialized
bool m_eigenvectorsOk
Private Types
typedef SelfAdjointEigenSolver< _MatrixType > Base
Detailed Description
template<typename _MatrixType>
class Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >
Computes eigenvalues and eigenvectors of the generalized selfadjoint eigen problem.
\eigenvalues_module
Template Parameters
_MatrixType the type of the matrix of which we are computing the eigendecomposition; this is expected to be an instantiation of the Matrix class template.
This class solves the generalized eigenvalue problem . In this case, the matrix should be selfadjoint and the matrix should be positive definite.
Only the lower triangular part of the input matrix is referenced.
Call the function compute() to compute the eigenvalues and eigenvectors of a given matrix. Alternatively, you can use the GeneralizedSelfAdjointEigenSolver(const MatrixType&, const MatrixType&, int) constructor which computes the eigenvalues and eigenvectors at construction time. Once the eigenvalue and eigenvectors are computed, they can be retrieved with the eigenvalues() and eigenvectors() functions.
The documentation for GeneralizedSelfAdjointEigenSolver(const MatrixType&, const MatrixType&, int) contains an example of the typical use of this class.
See also
class SelfAdjointEigenSolver, class EigenSolver, class ComplexEigenSolver
Member Typedef Documentation
Base
template<typename _MatrixType > typedef SelfAdjointEigenSolver<_MatrixType> Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::Base private
EigenvectorsType
template<typename _MatrixType > typedef Matrix<Scalar,Size,Size,ColMajor,MaxColsAtCompileTime,MaxColsAtCompileTime> Eigen::SelfAdjointEigenSolver< _MatrixType >::EigenvectorsType inherited
Index
template<typename _MatrixType > typedef Eigen::Index Eigen::SelfAdjointEigenSolver< _MatrixType >::Index inherited
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::MatrixType
RealScalar
template<typename _MatrixType > typedef NumTraits<Scalar>::Real Eigen::SelfAdjointEigenSolver< _MatrixType >::RealScalar inherited
Real scalar type for _MatrixType.
This is just Scalar if Scalar is real (e.g., float or double), and the type of the real part of Scalar if Scalar is complex.
RealVectorType
template<typename _MatrixType > typedef internal::plain_col_type<MatrixType,RealScalar>::type Eigen::SelfAdjointEigenSolver< _MatrixType >::RealVectorType inherited
Type for vector of eigenvalues as returned by eigenvalues().
This is a column vector with entries of type RealScalar. The length of the vector is the size of _MatrixType.
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::SelfAdjointEigenSolver< _MatrixType >::Scalar inherited
Scalar type for matrices of type _MatrixType.
SubDiagonalType
template<typename _MatrixType > typedef TridiagonalizationType::SubDiagonalType Eigen::SelfAdjointEigenSolver< _MatrixType >::SubDiagonalType inherited
TridiagonalizationType
template<typename _MatrixType > typedef Tridiagonalization<MatrixType> Eigen::SelfAdjointEigenSolver< _MatrixType >::TridiagonalizationType inherited
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum inherited
Enumerator
Size
ColsAtCompileTime
Options
MaxColsAtCompileTime
         {
      Size = MatrixType::RowsAtCompileTime,
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      Options = MatrixType::Options,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
GeneralizedSelfAdjointEigenSolver() [1/3]
template<typename _MatrixType > Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::GeneralizedSelfAdjointEigenSolver () inline
Default constructor for fixed-size matrices.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). This constructor can only be used if _MatrixType is a fixed-size matrix; use GeneralizedSelfAdjointEigenSolver(Index) for dynamic-size matrices.
: Base() {}
GeneralizedSelfAdjointEigenSolver() [2/3]
template<typename _MatrixType > Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::GeneralizedSelfAdjointEigenSolver (Index size) inline explicit
Constructor, pre-allocates memory for dynamic-size matrices.
Parameters
[in] size Positive integer, size of the matrix whose eigenvalues and eigenvectors will be computed.
This constructor is useful for dynamic-size matrices, when the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See also
compute() for an example
        : Base(size)
    {}
GeneralizedSelfAdjointEigenSolver() [3/3]
template<typename _MatrixType > Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::GeneralizedSelfAdjointEigenSolver (const MatrixType & matA, const MatrixType & matB, int options = ComputeEigenvectors|Ax_lBx) inline
Constructor; computes generalized eigendecomposition of given matrix pencil.
Parameters
[in] matA Selfadjoint matrix in matrix pencil. Only the lower triangular part of the matrix is referenced.
[in] matB Positive-definite matrix in matrix pencil. Only the lower triangular part of the matrix is referenced.
[in] options A or-ed set of flags {ComputeEigenvectors,EigenvaluesOnly} | {Ax_lBx,ABx_lx,BAx_lx}. Default is ComputeEigenvectors|Ax_lBx.
This constructor calls compute(const MatrixType&, const MatrixType&, int) to compute the eigenvalues and (if requested) the eigenvectors of the generalized eigenproblem with matA the selfadjoint matrix and matB the positive definite matrix . Each eigenvector satisfies the property . The eigenvectors are computed if options contains ComputeEigenvectors.
In addition, the two following variants can be solved via options:
ABx_lx:
BAx_lx:
Example:
Output:
See also
compute(const MatrixType&, const MatrixType&, int)
      : Base(matA.cols())
    {
      compute(matA, matB, options);
    }
References Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::compute().
Member Function Documentation
check_template_parameters()
template<typename _MatrixType > static void Eigen::SelfAdjointEigenSolver< _MatrixType >::check_template_parameters () inline static protected inherited
    {
      EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
    }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
compute() [1/2]
template<typename _MatrixType > template<typename InputType > EIGEN_DEVICE_FUNC SelfAdjointEigenSolver & Eigen::SelfAdjointEigenSolver< _MatrixType >::compute (const EigenBase< InputType > & matrix, int options = ComputeEigenvectors) inherited
Computes eigendecomposition of given matrix.
Parameters
[in] matrix Selfadjoint matrix whose eigendecomposition is to be computed. Only the lower triangular part of the matrix is referenced.
[in] options Can be ComputeEigenvectors (default) or EigenvaluesOnly.
Returns
Reference to *this
This function computes the eigenvalues of matrix. The eigenvalues() function can be used to retrieve them. If options equals ComputeEigenvectors, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
This implementation uses a symmetric QR algorithm. The matrix is first reduced to tridiagonal form using the Tridiagonalization class. The tridiagonal matrix is then brought to diagonal form with implicit symmetric QR steps with Wilkinson shift. Details can be found in Section 8.3 of Golub & Van Loan, Matrix Computations.
The cost of the computation is about if the eigenvectors are required and if they are not required.
This method reuses the memory in the SelfAdjointEigenSolver object that was allocated when the object was constructed, if the size of the matrix does not change.
Example:
Output:
See also
SelfAdjointEigenSolver(const MatrixType&, int)
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::SelfAdjointEigenSolver().
compute() [2/2]
template<typename MatrixType > GeneralizedSelfAdjointEigenSolver< MatrixType > & Eigen::GeneralizedSelfAdjointEigenSolver< MatrixType >::compute (const MatrixType & matA, const MatrixType & matB, int options = ComputeEigenvectors|Ax_lBx)
Computes generalized eigendecomposition of given matrix pencil.
Parameters
[in] matA Selfadjoint matrix in matrix pencil. Only the lower triangular part of the matrix is referenced.
[in] matB Positive-definite matrix in matrix pencil. Only the lower triangular part of the matrix is referenced.
[in] options A or-ed set of flags {ComputeEigenvectors,EigenvaluesOnly} | {Ax_lBx,ABx_lx,BAx_lx}. Default is ComputeEigenvectors|Ax_lBx.
Returns
Reference to *this
Accoring to options, this function computes eigenvalues and (if requested) the eigenvectors of one of the following three generalized eigenproblems:
Ax_lBx:
ABx_lx:
BAx_lx: with matA the selfadjoint matrix and matB the positive definite matrix . In addition, each eigenvector satisfies the property .
The eigenvalues() function can be used to retrieve the eigenvalues. If options contains ComputeEigenvectors, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
The implementation uses LLT to compute the Cholesky decomposition and computes the classical eigendecomposition of the selfadjoint matrix if options contains Ax_lBx and of otherwise. This solves the generalized eigenproblem, because any solution of the generalized eigenproblem corresponds to a solution of the eigenproblem for . Similar statements can be made for the two other variants.
Example:
Output:
See also
GeneralizedSelfAdjointEigenSolver(const MatrixType&, const MatrixType&, int)
{
  eigen_assert(matA.cols()==matA.rows() && matB.rows()==matA.rows() && matB.cols()==matB.rows());
  eigen_assert((options&~(EigVecMask|GenEigMask))==0
          && (options&EigVecMask)!=EigVecMask
          && ((options&GenEigMask)==0 || (options&GenEigMask)==Ax_lBx
           || (options&GenEigMask)==ABx_lx || (options&GenEigMask)==BAx_lx)
          && "invalid option parameter");
  bool computeEigVecs = ((options&EigVecMask)==0) || ((options&EigVecMask)==ComputeEigenvectors);
  // Compute the cholesky decomposition of matB = L L' = U'U
  LLT<MatrixType> cholB(matB);
  int type = (options&GenEigMask);
  if(type==0)
    type = Ax_lBx;
  if(type==Ax_lBx)
  {
    // compute C = inv(L) A inv(L')
    MatrixType matC = matA.template selfadjointView<Lower>();
    cholB.matrixL().template solveInPlace<OnTheLeft>(matC);
    cholB.matrixU().template solveInPlace<OnTheRight>(matC);
    Base::compute(matC, computeEigVecs ? ComputeEigenvectors : EigenvaluesOnly );
    // transform back the eigen vectors: evecs = inv(U) * evecs
    if(computeEigVecs)
      cholB.matrixU().solveInPlace(Base::m_eivec);
  }
  else if(type==ABx_lx)
  {
    // compute C = L' A L
    MatrixType matC = matA.template selfadjointView<Lower>();
    matC = matC * cholB.matrixL();
    matC = cholB.matrixU() * matC;
    Base::compute(matC, computeEigVecs ? ComputeEigenvectors : EigenvaluesOnly);
    // transform back the eigen vectors: evecs = inv(U) * evecs
    if(computeEigVecs)
      cholB.matrixU().solveInPlace(Base::m_eivec);
  }
  else if(type==BAx_lx)
  {
    // compute C = L' A L
    MatrixType matC = matA.template selfadjointView<Lower>();
    matC = matC * cholB.matrixL();
    matC = cholB.matrixU() * matC;
    Base::compute(matC, computeEigVecs ? ComputeEigenvectors : EigenvaluesOnly);
    // transform back the eigen vectors: evecs = L * evecs
    if(computeEigVecs)
      Base::m_eivec = cholB.matrixL() * Base::m_eivec;
  }
  return *this;
}
References Eigen::ABx_lx, Eigen::Ax_lBx, Eigen::BAx_lx, Eigen::ComputeEigenvectors, eigen_assert, Eigen::EigenvaluesOnly, Eigen::EigVecMask, Eigen::GenEigMask, Eigen::LLT< _MatrixType, _UpLo >::matrixL(), and Eigen::LLT< _MatrixType, _UpLo >::matrixU().
Referenced by Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::GeneralizedSelfAdjointEigenSolver().
computeDirect()
template<typename MatrixType > EIGEN_DEVICE_FUNC SelfAdjointEigenSolver< MatrixType > & Eigen::SelfAdjointEigenSolver< MatrixType >::computeDirect (const MatrixType & matrix, int options = ComputeEigenvectors) inherited
Computes eigendecomposition of given matrix using a closed-form algorithm.
This is a variant of compute(const MatrixType&, int options) which directly solves the underlying polynomial equation.
Currently only 2x2 and 3x3 matrices for which the sizes are known at compile time are supported (e.g., Matrix3d).
This method is usually significantly faster than the QR iterative algorithm but it might also be less accurate. It is also worth noting that for 3x3 matrices it involves trigonometric operations which are not necessarily available for all scalar types.
For the 3x3 case, we observed the following worst case relative error regarding the eigenvalues:
double: 1e-8
float: 1e-3
See also
compute(const MatrixType&, int options)
{
  internal::direct_selfadjoint_eigenvalues<SelfAdjointEigenSolver,Size,NumTraits<Scalar>::IsComplex>::run(*this,matrix,options);
  return *this;
}
Referenced by igl::polar_dec().
computeFromTridiagonal()
template<typename MatrixType > SelfAdjointEigenSolver< MatrixType > & Eigen::SelfAdjointEigenSolver< MatrixType >::computeFromTridiagonal (const RealVectorType & diag, const SubDiagonalType & subdiag, int options = ComputeEigenvectors) inherited
Computes the eigen decomposition from a tridiagonal symmetric matrix.
Parameters
[in] diag The vector containing the diagonal of the matrix.
[in] subdiag The subdiagonal of the matrix.
[in] options Can be ComputeEigenvectors (default) or EigenvaluesOnly.
Returns
Reference to *this
This function assumes that the matrix has been reduced to tridiagonal form.
See also
compute(const MatrixType&, int) for more information
{
  //TODO : Add an option to scale the values beforehand
  bool computeEigenvectors = (options&ComputeEigenvectors)==ComputeEigenvectors;
  m_eivalues = diag;
  m_subdiag = subdiag;
  if (computeEigenvectors)
  {
    m_eivec.setIdentity(diag.size(), diag.size());
  }
  m_info = internal::computeFromTridiagonal_impl(m_eivalues, m_subdiag, m_maxIterations, computeEigenvectors, m_eivec);
  m_isInitialized = true;
  m_eigenvectorsOk = computeEigenvectors;
  return *this;
}
References Eigen::ComputeEigenvectors, and Eigen::internal::computeFromTridiagonal_impl().
eigenvalues()
template<typename _MatrixType > EIGEN_DEVICE_FUNC const RealVectorType & Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvalues () const inline inherited
Returns the eigenvalues of given matrix.
Returns
A const reference to the column vector containing the eigenvalues.
Precondition
The eigenvalues have been computed before.
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix. The eigenvalues are sorted in increasing order.
Example:
Output:
See also
eigenvectors(), MatrixBase::eigenvalues()
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      return m_eivalues;
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivalues, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
Referenced by Eigen::SelfAdjointView< _MatrixType, UpLo >::eigenvalues(), CurvatureCalculator::finalEigenStuff(), and igl::polar_dec().
eigenvectors()
template<typename _MatrixType > EIGEN_DEVICE_FUNC const EigenvectorsType & Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvectors () const inline inherited
Returns the eigenvectors of given matrix.
Returns
A const reference to the matrix whose columns are the eigenvectors.
Precondition
The eigenvectors have been computed before.
Column of the returned matrix is an eigenvector corresponding to eigenvalue number as returned by eigenvalues(). The eigenvectors are normalized to have (Euclidean) norm equal to one. If this object was used to solve the eigenproblem for the selfadjoint matrix , then the matrix returned by this function is the matrix in the eigendecomposition .
Example:
Output:
See also
eigenvalues()
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
      return m_eivec;
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eigenvectorsOk, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivec, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
Referenced by CurvatureCalculator::finalEigenStuff(), igl::fit_plane(), and igl::polar_dec().
info()
template<typename _MatrixType > EIGEN_DEVICE_FUNC ComputationInfo Eigen::SelfAdjointEigenSolver< _MatrixType >::info () const inline inherited
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NoConvergence otherwise.
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      return m_info;
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_info, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
operatorInverseSqrt()
template<typename _MatrixType > EIGEN_DEVICE_FUNC MatrixType Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt () const inline inherited
Computes the inverse square root of the matrix.
Returns
the inverse positive-definite square root of the matrix
Precondition
The eigenvalues and eigenvectors of a positive-definite matrix have been computed before.
This function uses the eigendecomposition to compute the inverse square root as . This is cheaper than first computing the square root with operatorSqrt() and then its inverse with MatrixBase::inverse().
Example:
Output:
See also
operatorSqrt(), MatrixBase::inverse(), MatrixFunctions Module
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
      return m_eivec * m_eivalues.cwiseInverse().cwiseSqrt().asDiagonal() * m_eivec.adjoint();
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eigenvectorsOk, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivalues, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivec, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
operatorSqrt()
template<typename _MatrixType > EIGEN_DEVICE_FUNC MatrixType Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt () const inline inherited
Computes the positive-definite square root of the matrix.
Returns
the positive-definite square root of the matrix
Precondition
The eigenvalues and eigenvectors of a positive-definite matrix have been computed before.
The square root of a positive-definite matrix is the positive-definite matrix whose square equals . This function uses the eigendecomposition to compute the square root as .
Example:
Output:
See also
operatorInverseSqrt(), MatrixFunctions Module
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
      return m_eivec * m_eivalues.cwiseSqrt().asDiagonal() * m_eivec.adjoint();
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eigenvectorsOk, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivalues, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivec, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
Member Data Documentation
m_eigenvectorsOk
template<typename _MatrixType > bool Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eigenvectorsOk protected inherited
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvectors(), Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt(), and Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt().
m_eivalues
template<typename _MatrixType > RealVectorType Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivalues protected inherited
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvalues(), Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt(), and Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt().
m_eivec
template<typename _MatrixType > EigenvectorsType Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivec protected inherited
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvectors(), Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt(), and Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt().
m_info
template<typename _MatrixType > ComputationInfo Eigen::SelfAdjointEigenSolver< _MatrixType >::m_info protected inherited
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::info().
m_isInitialized
template<typename _MatrixType > bool Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized protected inherited
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvalues(), Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvectors(), Eigen::SelfAdjointEigenSolver< _MatrixType >::info(), Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt(), and Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt().
m_maxIterations
template<typename _MatrixType > const int Eigen::SelfAdjointEigenSolver< _MatrixType >::m_maxIterations = 30 static inherited
Maximum number of iterations.
The algorithm terminates if it does not converge within m_maxIterations * n iterations, where n denotes the size of the matrix. This value is currently set to 30 (copied from LAPACK).
m_subdiag
template<typename _MatrixType > TridiagonalizationType::SubDiagonalType Eigen::SelfAdjointEigenSolver< _MatrixType >::m_subdiag protected inherited
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h