Prusa Slicer: MenuWithSeparators Class Reference
MenuWithSeparators Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
MenuWithSeparators (const wxString &title, long style=0)
MenuWithSeparators (long style=0)
~MenuWithSeparators ()
void DestroySeparators ()
void SetFirstSeparator ()
void SetSecondSeparator ()
Private Attributes
wxMenuItem * m_separator_frst { nullptr }
wxMenuItem * m_separator_scnd { nullptr }
Detailed Description
Constructor & Destructor Documentation
MenuWithSeparators() [1/2]
MenuWithSeparators::MenuWithSeparators (const wxString & title, long style = 0) inline
        : wxMenu(title, style) {}
MenuWithSeparators() [2/2]
MenuWithSeparators::MenuWithSeparators (long style = 0) inline
        : wxMenu(style) {}
~MenuWithSeparators()
MenuWithSeparators::~MenuWithSeparators () inline
{}
Member Function Documentation
DestroySeparators()
void MenuWithSeparators::DestroySeparators ()
{
    if (m_separator_frst) {
        Destroy(m_separator_frst);
        m_separator_frst = nullptr;
    }
    if (m_separator_scnd) {
        Destroy(m_separator_scnd);
        m_separator_scnd = nullptr;
    }
}
References m_separator_frst, and m_separator_scnd.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_settings().
SetFirstSeparator()
void MenuWithSeparators::SetFirstSeparator ()
{
    m_separator_frst = this->AppendSeparator();
}
References m_separator_frst.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_settings().
SetSecondSeparator()
void MenuWithSeparators::SetSecondSeparator ()
{
    m_separator_scnd = this->AppendSeparator();
}
References m_separator_scnd.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_settings().
Member Data Documentation
m_separator_frst
wxMenuItem* MenuWithSeparators::m_separator_frst { nullptr } private
Referenced by DestroySeparators(), and SetFirstSeparator().
m_separator_scnd
wxMenuItem* MenuWithSeparators::m_separator_scnd { nullptr } private
Referenced by DestroySeparators(), and SetSecondSeparator().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp