Prusa Slicer: Slic3r::SupportSpotsGenerator::SliceConnection Struct Reference
Slic3r::SupportSpotsGenerator::SliceConnection Struct Reference
Public Member Functions
void add (const SliceConnection &other)
void print_info (const std::string &tag)
Public Attributes
float area {}
Vec3f centroid_accumulator = Vec3f::Zero()
Vec2f second_moment_of_area_accumulator = Vec2f::Zero()
float second_moment_of_area_covariance_accumulator {}
Detailed Description
Member Function Documentation
add()
void Slic3r::SupportSpotsGenerator::SliceConnection::add (const SliceConnection & other) inline
    {
        this->area += other.area;
        this->centroid_accumulator += other.centroid_accumulator;
        this->second_moment_of_area_accumulator += other.second_moment_of_area_accumulator;
        this->second_moment_of_area_covariance_accumulator += other.second_moment_of_area_covariance_accumulator;
    }
References area, centroid_accumulator, second_moment_of_area_accumulator, and second_moment_of_area_covariance_accumulator.
Referenced by Slic3r::SupportSpotsGenerator::check_stability().
print_info()
void Slic3r::SupportSpotsGenerator::SliceConnection::print_info (const std::string & tag) inline
    {
        Vec3f centroid   = centroid_accumulator / area;
        Vec2f variance   = (second_moment_of_area_accumulator / area - centroid.head<2>().cwiseProduct(centroid.head<2>()));
        float covariance = second_moment_of_area_covariance_accumulator / area - centroid.x() * centroid.y();
        std::cout << tag << std::endl;
        std::cout << "area: " << area << std::endl;
        std::cout << "centroid: " << centroid.x() << " " << centroid.y() << " " << centroid.z() << std::endl;
        std::cout << "variance: " << variance.x() << " " << variance.y() << std::endl;
        std::cout << "covariance: " << covariance << std::endl;
    }
References area, centroid_accumulator, second_moment_of_area_accumulator, and second_moment_of_area_covariance_accumulator.
Referenced by Slic3r::SupportSpotsGenerator::check_stability().
Member Data Documentation
area
float Slic3r::SupportSpotsGenerator::SliceConnection::area {}
Referenced by add(), Slic3r::SupportSpotsGenerator::check_stability(), Slic3r::SupportSpotsGenerator::estimate_slice_connection(), Slic3r::SupportSpotsGenerator::ObjectPart::is_stable_while_extruding(), and print_info().
centroid_accumulator
Vec3f Slic3r::SupportSpotsGenerator::SliceConnection::centroid_accumulator = Vec3f::Zero()
Referenced by add(), Slic3r::SupportSpotsGenerator::check_stability(), Slic3r::SupportSpotsGenerator::estimate_slice_connection(), Slic3r::SupportSpotsGenerator::ObjectPart::is_stable_while_extruding(), and print_info().
second_moment_of_area_accumulator
Vec2f Slic3r::SupportSpotsGenerator::SliceConnection::second_moment_of_area_accumulator = Vec2f::Zero()
Referenced by add(), Slic3r::SupportSpotsGenerator::check_stability(), Slic3r::SupportSpotsGenerator::estimate_slice_connection(), Slic3r::SupportSpotsGenerator::ObjectPart::is_stable_while_extruding(), and print_info().
second_moment_of_area_covariance_accumulator
float Slic3r::SupportSpotsGenerator::SliceConnection::second_moment_of_area_covariance_accumulator {}
Referenced by add(), Slic3r::SupportSpotsGenerator::check_stability(), Slic3r::SupportSpotsGenerator::estimate_slice_connection(), Slic3r::SupportSpotsGenerator::ObjectPart::is_stable_while_extruding(), and print_info().
The documentation for this struct was generated from the following file:
src/libslic3r/SupportSpotsGenerator.cpp