Prusa Slicer: Slic3r::sla::SupportPointGenerator::PointGrid3D Struct Reference
Slic3r::sla::SupportPointGenerator::PointGrid3D Struct Reference
#include <src/libslic3r/SLA/SupportPointGenerator.hpp>
Classes
struct GridHash
Public Types
typedef std::unordered_multimap< Vec3i, RichSupportPoint, GridHash > Grid
Public Member Functions
Vec3i cell_id (const Vec3f &pos)
void insert (const Vec2f &pos, Structure *island)
bool collides_with (const Vec2f &pos, float print_z, float radius)
Public Attributes
Vec3f cell_size
Grid grid
Private Member Functions
bool collides_with (const Vec3f &pos, float radius, Grid::const_iterator it_begin, Grid::const_iterator it_end)
Detailed Description
Member Typedef Documentation
Grid
typedef std::unordered_multimap<Vec3i, RichSupportPoint, GridHash> Slic3r::sla::SupportPointGenerator::PointGrid3D::Grid
Member Function Documentation
cell_id()
Vec3i Slic3r::sla::SupportPointGenerator::PointGrid3D::cell_id (const Vec3f & pos) inline
{
            return Vec3i(int(floor(pos.x() / cell_size.x())),
                         int(floor(pos.y() / cell_size.y())),
                         int(floor(pos.z() / cell_size.z())));
        }
References cell_size, floor(), and Slic3r::sla::pos().
Referenced by collides_with(), insert(), and Slic3r::sla::SupportPointGenerator::PointGrid3D::GridHash::operator()().
collides_with() [1/2]
bool Slic3r::sla::SupportPointGenerator::PointGrid3D::collides_with (const Vec2f & pos, float print_z, float radius) inline
{
            Vec3f pos3d(pos.x(), pos.y(), print_z);
            Vec3i cell = cell_id(pos3d);
            std::pair<Grid::const_iterator, Grid::const_iterator> it_pair = grid.equal_range(cell);
            if (collides_with(pos3d, radius, it_pair.first, it_pair.second))
                return true;
            for (int i = -1; i < 2; ++ i)
                for (int j = -1; j < 2; ++ j)
                    for (int k = -1; k < 1; ++ k) {
                        if (i == 0 && j == 0 && k == 0)
                            continue;
                        it_pair = grid.equal_range(cell + Vec3i(i, j, k));
                        if (collides_with(pos3d, radius, it_pair.first, it_pair.second))
                            return true;
                    }
            return false;
        }
References cell_id(), collides_with(), grid, and Slic3r::sla::pos().
Referenced by collides_with(), and Slic3r::sla::SupportPointGenerator::uniformly_cover().
collides_with() [2/2]
bool Slic3r::sla::SupportPointGenerator::PointGrid3D::collides_with (const Vec3f & pos, float radius, Grid::const_iterator it_begin, Grid::const_iterator it_end) inline private
{
            for (Grid::const_iterator it = it_begin; it != it_end; ++ it) {
                float dist2 = (it->second.position - pos).squaredNorm();
                if (dist2 < radius * radius)
                    return true;
            }
            return false;
        }
References Slic3r::sla::pos().
insert()
void Slic3r::sla::SupportPointGenerator::PointGrid3D::insert (const Vec2f & pos, Structure * island) inline
{
            RichSupportPoint pt;
            pt.position = Vec3f(pos.x(), pos.y(), float(island->layer->print_z));
            pt.island   = island;
            grid.emplace(cell_id(pt.position), pt);
        }
References cell_id(), grid, Slic3r::sla::SupportPointGenerator::RichSupportPoint::island, Slic3r::sla::SupportPointGenerator::Structure::layer, Slic3r::sla::pos(), Slic3r::sla::SupportPointGenerator::RichSupportPoint::position, and Slic3r::sla::SupportPointGenerator::MyLayer::print_z.
Referenced by Slic3r::sla::SupportPointGenerator::uniformly_cover().
Member Data Documentation
cell_size
Vec3f Slic3r::sla::SupportPointGenerator::PointGrid3D::cell_size
Referenced by cell_id().
grid
Grid Slic3r::sla::SupportPointGenerator::PointGrid3D::grid
Referenced by collides_with(), and insert().
The documentation for this struct was generated from the following file:
src/libslic3r/SLA/SupportPointGenerator.hpp