Prusa Slicer: Slic3r::trianglulate_wall_detail Namespace Reference
Slic3r::trianglulate_wall_detail Namespace Reference
Classes
class Ring
class Triangulator
Functions
template<class Sc >
static Sc sq_dst (const Vec< 3, Sc > &v1, const Vec< 3, Sc > &v2)
template<class Sc >
static Sc trscore (const Ring &onring, const Ring &offring, const std::vector< Vec< 3, Sc > > &pts)
Function Documentation
sq_dst()
template<class Sc > static Sc Slic3r::trianglulate_wall_detail::sq_dst (const Vec< 3, Sc > & v1, const Vec< 3, Sc > & v2) static
{
    Vec<3, Sc> v = v1 - v2;
    return v.x() * v.x() + v.y() * v.y() /*+ v.z() * v.z()*/;
}
Referenced by trscore().
trscore()
template<class Sc > static Sc Slic3r::trianglulate_wall_detail::trscore (const Ring & onring, const Ring & offring, const std::vector< Vec< 3, Sc > > & pts) static
{
    Sc a = sq_dst(pts[onring.pos().first], pts[offring.pos().first]);
    Sc b = sq_dst(pts[onring.pos().second], pts[offring.pos().first]);
    return (std::abs(a) + std::abs(b)) / 2.;
}
References Slic3r::trianglulate_wall_detail::Ring::pos(), Sc, and sq_dst().
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::calc_score(), and Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings().