Prusa Slicer: Slic3r::ModelObjectStatusDB Struct Reference
Slic3r::ModelObjectStatusDB Struct Reference
Public Member Functions
void add (const ModelObject &model_object, const ModelObjectStatus::Status status)
bool add_if_new (const ModelObject &model_object, const ModelObjectStatus::Status status)
const ModelObjectStatus & get (const ModelObject &model_object)
const ModelObjectStatus & reuse (const ModelObject &model_object)
Public Attributes
std::set< ModelObjectStatus > db
Detailed Description
Member Function Documentation
add()
void Slic3r::ModelObjectStatusDB::add (const ModelObject & model_object, const ModelObjectStatus::Status status) inline
{
        assert(db.find(ModelObjectStatus(model_object.id())) == db.end());
        db.emplace(model_object.id(), status);
    }
References Slic3r::ObjectBase::id().
Referenced by Slic3r::Print::apply().
add_if_new()
bool Slic3r::ModelObjectStatusDB::add_if_new (const ModelObject & model_object, const ModelObjectStatus::Status status) inline
{
        auto it = db.find(ModelObjectStatus(model_object.id()));
        if (it == db.end()) {
            db.emplace_hint(it, model_object.id(), status);
            return true;
        }
        return false;
    }
References Slic3r::ObjectBase::id().
Referenced by Slic3r::Print::apply().
get()
const ModelObjectStatus & Slic3r::ModelObjectStatusDB::get (const ModelObject & model_object) inline
{
        auto it = db.find(ModelObjectStatus(model_object.id()));
        assert(it != db.end());
        return *it;
    }
References Slic3r::ObjectBase::id().
Referenced by Slic3r::Print::apply().
reuse()
const ModelObjectStatus & Slic3r::ModelObjectStatusDB::reuse (const ModelObject & model_object) inline
{
        const ModelObjectStatus &result = this->get(model_object);
        assert(result.status != ModelObjectStatus::Deleted);
        return result;
    }
References Slic3r::ModelObjectStatus::status.
Referenced by Slic3r::Print::apply().
Member Data Documentation
db
std::set<ModelObjectStatus> Slic3r::ModelObjectStatusDB::db
The documentation for this struct was generated from the following file:
src/libslic3r/PrintApply.cpp