Prusa Slicer: Slic3r::ConfigOptionPercentsTempl< NULLABLE > Class Template Reference
Slic3r::ConfigOptionPercentsTempl< NULLABLE > Class Template Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionPercentsTempl ()
ConfigOptionPercentsTempl (size_t n, double value)
ConfigOptionPercentsTempl (std::initializer_list< double > il)
ConfigOptionPercentsTempl (const std::vector< double > &vec)
ConfigOptionPercentsTempl (std::vector< double > &&vec)
ConfigOptionType type () const override
ConfigOption * clone () const override
ConfigOptionPercentsTempl & operator= (const ConfigOption *opt)
bool operator== (const ConfigOptionPercentsTempl &rhs) const throw ()
bool operator< (const ConfigOptionPercentsTempl &rhs) const throw ()
std::string serialize () const override
std::vector< std::string > vserialize () const override
bool operator== (const ConfigOptionFloatsTempl &rhs) const throw ()
bool operator== (const ConfigOption &rhs) const override
bool operator== (const std::vector< double > &rhs) const throw ()
bool operator< (const ConfigOptionFloatsTempl &rhs) const throw ()
bool nullable () const override
bool is_nil () const override
bool is_nil (size_t idx) const override
bool deserialize (const std::string &str, bool append=false) override
void set (const ConfigOption *rhs) override
void set (const std::vector< const ConfigOption * > &rhs) override
void set_at (const ConfigOption *rhs, size_t i, size_t j) override
const double & get_at (size_t i) const
double & get_at (size_t i)
void resize (size_t n, const ConfigOption *opt_default=nullptr) override
void clear () override
size_t size () const override
bool empty () const override
bool operator!= (const std::vector< double > &rhs) const throw ()
bool operator!= (const ConfigOption &rhs) const
size_t hash () const override throw ()
bool overriden_by (const ConfigOption *rhs) const override
bool apply_override (const ConfigOption *rhs) override
virtual int getInt () const
virtual double getFloat () const
virtual bool getBool () const
virtual void setInt (int)
bool is_scalar () const
bool is_vector () const
Static Public Member Functions
static ConfigOptionType static_type ()
static double nil_value ()
Public Attributes
std::vector< double > values
Protected Member Functions
void serialize_single_value (std::ostringstream &ss, const double v) const
ConfigOptionType scalar_type () const
Static Protected Member Functions
static bool vectors_equal (const std::vector< double > &v1, const std::vector< double > &v2)
static bool vectors_lower (const std::vector< double > &v1, const std::vector< double > &v2)
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
template<bool NULLABLE>
class Slic3r::ConfigOptionPercentsTempl< NULLABLE >
Constructor & Destructor Documentation
ConfigOptionPercentsTempl() [1/5]
template<bool NULLABLE> Slic3r::ConfigOptionPercentsTempl< NULLABLE >::ConfigOptionPercentsTempl () inline
: ConfigOptionFloatsTempl<NULLABLE>() {}
Referenced by Slic3r::ConfigOptionPercentsTempl< NULLABLE >::clone().
ConfigOptionPercentsTempl() [2/5]
template<bool NULLABLE> Slic3r::ConfigOptionPercentsTempl< NULLABLE >::ConfigOptionPercentsTempl (size_t n, double value) inline explicit
: ConfigOptionFloatsTempl<NULLABLE>(n, value) {}
ConfigOptionPercentsTempl() [3/5]
template<bool NULLABLE> Slic3r::ConfigOptionPercentsTempl< NULLABLE >::ConfigOptionPercentsTempl (std::initializer_list< double > il) inline explicit
: ConfigOptionFloatsTempl<NULLABLE>(std::move(il)) {}
ConfigOptionPercentsTempl() [4/5]
template<bool NULLABLE> Slic3r::ConfigOptionPercentsTempl< NULLABLE >::ConfigOptionPercentsTempl (const std::vector< double > & vec) inline explicit
: ConfigOptionFloatsTempl<NULLABLE>(vec) {}
ConfigOptionPercentsTempl() [5/5]
template<bool NULLABLE> Slic3r::ConfigOptionPercentsTempl< NULLABLE >::ConfigOptionPercentsTempl (std::vector< double > && vec) inline explicit
: ConfigOptionFloatsTempl<NULLABLE>(std::move(vec)) {}
Member Function Documentation
apply_override()
bool Slic3r::ConfigOptionVector< double >::apply_override (const ConfigOption * rhs) inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
      throw ConfigurationError("ConfigOptionVector.apply_override() applied to different types.");
    auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
    if (! rhs->nullable()) {
        // Overridding a non-nullable object with another non-nullable object.
        if (this->values != rhs_vec->values) {
          this->values = rhs_vec->values;
          return true;
        }
        return false;
      }
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      bool   modified = false;
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i]) {
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i)) {
          if (this->values.empty())
            this->values.resize(i + 1);
          else
            this->values.resize(i + 1, this->values.front());
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
        return modified;
    }
clear()
void Slic3r::ConfigOptionVector< double >::clear () inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ this->values.clear(); }
clone()
template<bool NULLABLE> ConfigOption * Slic3r::ConfigOptionPercentsTempl< NULLABLE >::clone () const inline override virtual
Reimplemented from Slic3r::ConfigOptionFloatsTempl< NULLABLE >.
{ return new ConfigOptionPercentsTempl(*this); }
References Slic3r::ConfigOptionPercentsTempl< NULLABLE >::ConfigOptionPercentsTempl().
deserialize()
template<bool NULLABLE> bool Slic3r::ConfigOptionFloatsTempl< NULLABLE >::deserialize (const std::string & str, bool append = false) inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (! append)
            this->values.clear();
        std::istringstream is(str);
        std::string item_str;
        while (std::getline(is, item_str, ',')) {
          boost::trim(item_str);
          if (item_str == "nil") {
            if (NULLABLE)
              this->values.push_back(nil_value());
            else
              throw ConfigurationError("Deserializing nil into a non-nullable object");
          } else {
              std::istringstream iss(item_str);
              double value;
              iss >> value;
              this->values.push_back(value);
          }
        }
        return true;
    }
References Slic3r::append(), and Slic3r::ConfigOptionFloatsTempl< NULLABLE >::nil_value().
empty()
bool Slic3r::ConfigOptionVector< double >::empty () const inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.empty(); }
get_at() [1/2]
double & Slic3r::ConfigOptionVector< double >::get_at (size_t i) inline inherited
{ return const_cast<T&>(std::as_const(*this).get_at(i)); }
get_at() [2/2]
const double & Slic3r::ConfigOptionVector< double >::get_at (size_t i) const inline inherited
    {
        assert(! this->values.empty());
        return (i < this->values.size()) ? this->values[i] : this->values.front();
    }
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
virtual int Slic3r::ConfigOption::getInt () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::getInt on a non-int ConfigOption"); }
Referenced by Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
hash()
size_t Slic3r::ConfigOptionVector< double >::hash () const throw () inline override virtual inherited
Implements Slic3r::ConfigOption.
{
        std::hash<T> hasher;
        size_t seed = 0;
        for (const auto &v : this->values)
            boost::hash_combine(seed, hasher(v));
        return seed;
    }
is_nil() [1/2]
template<bool NULLABLE> bool Slic3r::ConfigOptionFloatsTempl< NULLABLE >::is_nil () const inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{ for (auto v : this->values) if (! std::isnan(v)) return false; return true; }
References Slic3r::ConfigOptionVector< double >::values.
is_nil() [2/2]
template<bool NULLABLE> bool Slic3r::ConfigOptionFloatsTempl< NULLABLE >::is_nil (size_t idx) const inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ return std::isnan(this->values[idx < values.size() ? idx : 0]); }
References Slic3r::ConfigOptionVector< double >::values.
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nil_value()
template<bool NULLABLE> static double Slic3r::ConfigOptionFloatsTempl< NULLABLE >::nil_value () inline static inherited
{ return std::numeric_limits<double>::quiet_NaN(); }
Referenced by Slic3r::ConfigOptionFloatsTempl< NULLABLE >::deserialize(), and Slic3r::GUI::Field::get_value_by_opt_type().
nullable()
template<bool NULLABLE> bool Slic3r::ConfigOptionFloatsTempl< NULLABLE >::nullable () const inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{ return NULLABLE; }
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
bool Slic3r::ConfigOptionVector< double >::operator!= (const std::vector< double > & rhs) const throw () inline inherited
{ return this->values != rhs; }
operator<() [1/2]
template<bool NULLABLE> bool Slic3r::ConfigOptionFloatsTempl< NULLABLE >::operator< (const ConfigOptionFloatsTempl< NULLABLE > & rhs) const throw () inline inherited
{ return vectors_lower(this->values, rhs.values); }
References Slic3r::ConfigOptionFloatsTempl< NULLABLE >::vectors_lower().
operator<() [2/2]
template<bool NULLABLE> bool Slic3r::ConfigOptionPercentsTempl< NULLABLE >::operator< (const ConfigOptionPercentsTempl< NULLABLE > & rhs) const throw () inline
{ return ConfigOptionFloatsTempl<NULLABLE>::vectors_lower(this->values, rhs.values); }
References Slic3r::ConfigOptionFloatsTempl< NULLABLE >::vectors_lower().
operator=()
template<bool NULLABLE> ConfigOptionPercentsTempl & Slic3r::ConfigOptionPercentsTempl< NULLABLE >::operator= (const ConfigOption * opt) inline
{ this->set(opt); return *this; }
References Slic3r::ConfigOptionVector< double >::set().
operator==() [1/4]
template<bool NULLABLE> bool Slic3r::ConfigOptionFloatsTempl< NULLABLE >::operator== (const ConfigOption & rhs) const inline override virtual inherited
Implements Slic3r::ConfigOption.
{
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionFloatsTempl: Comparing incompatible types");
        assert(dynamic_cast<const ConfigOptionVector<double>*>(&rhs));
        return vectors_equal(this->values, static_cast<const ConfigOptionVector<double>*>(&rhs)->values);
    }
References Slic3r::ConfigOption::type(), Slic3r::ConfigOptionVector< double >::values, and Slic3r::ConfigOptionFloatsTempl< NULLABLE >::vectors_equal().
operator==() [2/4]
template<bool NULLABLE> bool Slic3r::ConfigOptionFloatsTempl< NULLABLE >::operator== (const ConfigOptionFloatsTempl< NULLABLE > & rhs) const throw () inline inherited
{ return vectors_equal(this->values, rhs.values); }
References Slic3r::ConfigOptionFloatsTempl< NULLABLE >::vectors_equal().
operator==() [3/4]
template<bool NULLABLE> bool Slic3r::ConfigOptionPercentsTempl< NULLABLE >::operator== (const ConfigOptionPercentsTempl< NULLABLE > & rhs) const throw () inline
{ return ConfigOptionFloatsTempl<NULLABLE>::vectors_equal(this->values, rhs.values); }
References Slic3r::ConfigOptionFloatsTempl< NULLABLE >::vectors_equal().
operator==() [4/4]
bool Slic3r::ConfigOptionVector< double >::operator== (const std::vector< double > & rhs) const throw () inline inherited
{ return this->values == rhs; }
overriden_by()
bool Slic3r::ConfigOptionVector< double >::overriden_by (const ConfigOption * rhs) const inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector.overriden_by() applied to different types.");
      auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
      if (! rhs->nullable())
        // Overridding a non-nullable object with another non-nullable object.
        return this->values != rhs_vec->values;
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i])
          return true;
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i))
          return true;
      return false;
    }
resize()
void Slic3r::ConfigOptionVector< double >::resize (size_t n, const ConfigOption * opt_default = nullptr) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        assert(opt_default == nullptr || opt_default->is_vector());
//        assert(opt_default == nullptr || dynamic_cast<ConfigOptionVector<T>>(opt_default));
        assert(! this->values.empty() || opt_default != nullptr);
        if (n == 0)
            this->values.clear();
        else if (n < this->values.size())
            this->values.erase(this->values.begin() + n, this->values.end());
        else if (n > this->values.size()) {
            if (this->values.empty()) {
                if (opt_default == nullptr)
                    throw ConfigurationError("ConfigOptionVector::resize(): No default value provided.");
                if (opt_default->type() != this->type())
                    throw ConfigurationError("ConfigOptionVector::resize(): Extending with an incompatible type.");
                this->values.resize(n, static_cast<const ConfigOptionVector<T>*>(opt_default)->values.front());
            } else {
                // Resize by duplicating the last value.
                this->values.resize(n, this->values./*back*/front());
            }
        }
    }
scalar_type()
ConfigOptionType Slic3r::ConfigOptionVectorBase::scalar_type () const inline protected inherited
{ return static_cast<ConfigOptionType>(this->type() - coVectorType); }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::ConfigOptionVector< T >::set(), and Slic3r::ConfigOptionVector< T >::set_at().
serialize() [1/2]
template<bool NULLABLE> std::string Slic3r::ConfigOptionPercentsTempl< NULLABLE >::serialize () const inline override virtual
Reimplemented from Slic3r::ConfigOptionFloatsTempl< NULLABLE >.
    {
        std::ostringstream ss;
        for (const double &v : this->values) {
            if (&v != &this->values.front())
              ss << ",";
      this->serialize_single_value(ss, v);
      if (! std::isnan(v))
        ss << "%";
        }
        std::string str = ss.str();
        return str;
    }
References Slic3r::ConfigOptionFloatsTempl< NULLABLE >::serialize_single_value(), and Slic3r::ConfigOptionVector< double >::values.
serialize() [2/2]
template<bool NULLABLE> template<class Archive > void Slic3r::ConfigOptionPercentsTempl< NULLABLE >::serialize (Archive & ar) inline private
{ ar(cereal::base_class<ConfigOptionFloatsTempl<NULLABLE>>(this)); }
serialize_single_value()
template<bool NULLABLE> void Slic3r::ConfigOptionFloatsTempl< NULLABLE >::serialize_single_value (std::ostringstream & ss, const double v) const inline protected inherited
{
          if (std::isfinite(v))
              ss << v;
          else if (std::isnan(v)) {
            if (NULLABLE)
              ss << "nil";
            else
                    throw ConfigurationError("Serializing NaN");
          } else
                throw ConfigurationError("Serializing invalid number");
  }
Referenced by Slic3r::ConfigOptionFloatsTempl< NULLABLE >::serialize(), Slic3r::ConfigOptionPercentsTempl< NULLABLE >::serialize(), Slic3r::ConfigOptionFloatsTempl< NULLABLE >::vserialize(), and Slic3r::ConfigOptionPercentsTempl< NULLABLE >::vserialize().
set() [1/2]
void Slic3r::ConfigOptionVector< double >::set (const ConfigOption * rhs) inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector: Assigning an incompatible type");
        assert(dynamic_cast<const ConfigOptionVector<T>*>(rhs));
        this->values = static_cast<const ConfigOptionVector<T>*>(rhs)->values;
    }
set() [2/2]
void Slic3r::ConfigOptionVector< double >::set (const std::vector< const ConfigOption * > & rhs) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        this->values.clear();
        this->values.reserve(rhs.size());
        for (const ConfigOption *opt : rhs) {
            if (opt->type() == this->type()) {
                auto other = static_cast<const ConfigOptionVector<T>*>(opt);
                if (other->values.empty())
                    throw ConfigurationError("ConfigOptionVector::set(): Assigning from an empty vector");
                this->values.emplace_back(other->values.front());
            } else if (opt->type() == this->scalar_type())
                this->values.emplace_back(static_cast<const ConfigOptionSingle<T>*>(opt)->value);
            else
                throw ConfigurationError("ConfigOptionVector::set():: Assigning an incompatible type");
        }
    }
set_at()
void Slic3r::ConfigOptionVector< double >::set_at (const ConfigOption * rhs, size_t i, size_t j) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        // It is expected that the vector value has at least one value, which is the default, if not overwritten.
        assert(! this->values.empty());
        if (this->values.size() <= i) {
            // Resize this vector, fill in the new vector fields with the copy of the first field.
            T v = this->values.front();
            this->values.resize(i + 1, v);
        }
        if (rhs->type() == this->type()) {
            // Assign the first value of the rhs vector.
            auto other = static_cast<const ConfigOptionVector<T>*>(rhs);
            if (other->values.empty())
                throw ConfigurationError("ConfigOptionVector::set_at(): Assigning from an empty vector");
            this->values[i] = other->get_at(j);
        } else if (rhs->type() == this->scalar_type())
            this->values[i] = static_cast<const ConfigOptionSingle<T>*>(rhs)->value;
        else
            throw ConfigurationError("ConfigOptionVector::set_at(): Assigning an incompatible type");
    }
setInt()
virtual void Slic3r::ConfigOption::setInt (int) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::setInt on a non-int ConfigOption"); }
size()
size_t Slic3r::ConfigOptionVector< double >::size () const inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.size(); }
static_type()
template<bool NULLABLE> static ConfigOptionType Slic3r::ConfigOptionPercentsTempl< NULLABLE >::static_type () inline static
{ return coPercents; }
References Slic3r::coPercents.
Referenced by Slic3r::ConfigOptionPercentsTempl< NULLABLE >::type().
type()
template<bool NULLABLE> ConfigOptionType Slic3r::ConfigOptionPercentsTempl< NULLABLE >::type () const inline override virtual
Reimplemented from Slic3r::ConfigOptionFloatsTempl< NULLABLE >.
{ return static_type(); }
References Slic3r::ConfigOptionPercentsTempl< NULLABLE >::static_type().
vectors_equal()
template<bool NULLABLE> static bool Slic3r::ConfigOptionFloatsTempl< NULLABLE >::vectors_equal (const std::vector< double > & v1, const std::vector< double > & v2) inline static protected inherited
{
      if (NULLABLE) {
        if (v1.size() != v2.size())
          return false;
        for (auto it1 = v1.begin(), it2 = v2.begin(); it1 != v1.end(); ++ it1, ++ it2)
          if (! ((std::isnan(*it1) && std::isnan(*it2)) || *it1 == *it2))
            return false;
        return true;
      } else
        // Not supporting nullable values, the default vector compare is cheaper.
        return v1 == v2;
    }
Referenced by Slic3r::ConfigOptionFloatsTempl< NULLABLE >::operator==(), Slic3r::ConfigOptionFloatsTempl< NULLABLE >::operator==(), and Slic3r::ConfigOptionPercentsTempl< NULLABLE >::operator==().
vectors_lower()
template<bool NULLABLE> static bool Slic3r::ConfigOptionFloatsTempl< NULLABLE >::vectors_lower (const std::vector< double > & v1, const std::vector< double > & v2) inline static protected inherited
{
        if (NULLABLE) {
            for (auto it1 = v1.begin(), it2 = v2.begin(); it1 != v1.end() && it2 != v2.end(); ++ it1, ++ it2) {
                auto null1 = int(std::isnan(*it1));
                auto null2 = int(std::isnan(*it2));
                return (null1 < null2) || (null1 == null2 && *it1 < *it2);
            }
            return v1.size() < v2.size();
        } else
            // Not supporting nullable values, the default vector compare is cheaper.
            return v1 < v2;
    }
Referenced by Slic3r::ConfigOptionFloatsTempl< NULLABLE >::operator<(), and Slic3r::ConfigOptionPercentsTempl< NULLABLE >::operator<().
vserialize()
template<bool NULLABLE> std::vector< std::string > Slic3r::ConfigOptionPercentsTempl< NULLABLE >::vserialize () const inline override virtual
Reimplemented from Slic3r::ConfigOptionFloatsTempl< NULLABLE >.
    {
        std::vector<std::string> vv;
        vv.reserve(this->values.size());
        for (const double v : this->values) {
            std::ostringstream ss;
      this->serialize_single_value(ss, v);
      if (! std::isnan(v))
        ss << "%";
            vv.push_back(ss.str());
        }
        return vv;
    }
References Slic3r::ConfigOptionFloatsTempl< NULLABLE >::serialize_single_value(), and Slic3r::ConfigOptionVector< double >::values.
Friends And Related Symbol Documentation
cereal::access
template<bool NULLABLE> friend class cereal::access friend
Member Data Documentation
values
std::vector<double > Slic3r::ConfigOptionVector< double >::values inherited
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp