Prusa Slicer: Slic3r::Measure::Polynomial1 Class Reference
Slic3r::Measure::Polynomial1 Class Reference
#include <src/libslic3r/MeasureUtils.hpp>
Public Member Functions
Polynomial1 (std::initializer_list< double > values)
Polynomial1 (uint32_t degree)
void EliminateLeadingZeros ()
void SetCoefficients (double value)
uint32_t GetDegree () const
const double & operator[] (uint32_t i) const
double & operator[] (uint32_t i)
double operator() (double t) const
Protected Attributes
std::vector< double > m_coefficient
Detailed Description
Constructor & Destructor Documentation
Polynomial1() [1/2]
Slic3r::Measure::Polynomial1::Polynomial1 (std::initializer_list< double > values) inline
    {
        // C++ 11 will call the default constructor for
        // Polynomial1<Real> p{}, so it is guaranteed that
        // values.size() > 0.
        m_coefficient.resize(values.size());
        std::copy(values.begin(), values.end(), m_coefficient.begin());
        EliminateLeadingZeros();
    }
References EliminateLeadingZeros(), and m_coefficient.
Polynomial1() [2/2]
Slic3r::Measure::Polynomial1::Polynomial1 (uint32_t degree) inline explicit
        : m_coefficient(static_cast<size_t>(degree) + 1, 0.0)
    {}
Member Function Documentation
EliminateLeadingZeros()
void Slic3r::Measure::Polynomial1::EliminateLeadingZeros () inline
    {
        const size_t size = m_coefficient.size();
        if (size > 1) {
            const double zero = 0.0;
            int32_t leading;
            for (leading = static_cast<int32_t>(size) - 1; leading > 0; --leading) {
                if (m_coefficient[leading] != zero)
                    break;
            }
            m_coefficient.resize(++leading);
        }
    }
References m_coefficient.
Referenced by Polynomial1(), Slic3r::Measure::operator+(), and Slic3r::Measure::operator-().
GetDegree()
uint32_t Slic3r::Measure::Polynomial1::GetDegree () const inline
    {
        // By design, m_coefficient.size() > 0.
        return static_cast<uint32_t>(m_coefficient.size() - 1);
    }
References m_coefficient.
Referenced by Slic3r::Measure::get_measurement(), Slic3r::Measure::operator*(), Slic3r::Measure::operator*(), Slic3r::Measure::operator+(), and Slic3r::Measure::operator-().
operator()()
double Slic3r::Measure::Polynomial1::operator() (double t) const inline
    {
        int32_t i = static_cast<int32_t>(m_coefficient.size());
        double result = m_coefficient[--i];
        for (--i; i >= 0; --i) {
            result *= t;
            result += m_coefficient[i];
        }
        return result;
    }
References m_coefficient.
operator[]() [1/2]
double & Slic3r::Measure::Polynomial1::operator[] (uint32_t i) inline
{ return m_coefficient[i]; }
References m_coefficient.
operator[]() [2/2]
const double & Slic3r::Measure::Polynomial1::operator[] (uint32_t i) const inline
{ return m_coefficient[i]; }
References m_coefficient.
SetCoefficients()
void Slic3r::Measure::Polynomial1::SetCoefficients (double value) inline
    {
        std::fill(m_coefficient.begin(), m_coefficient.end(), value);
    }
References m_coefficient.
Referenced by Slic3r::Measure::operator*().
Member Data Documentation
m_coefficient
std::vector<double> Slic3r::Measure::Polynomial1::m_coefficient protected
Referenced by Polynomial1(), EliminateLeadingZeros(), GetDegree(), operator()(), operator[](), operator[](), and SetCoefficients().
The documentation for this class was generated from the following file:
src/libslic3r/MeasureUtils.hpp