Prusa Slicer: Slic3r::GUI::PageFirmware Struct Reference
Slic3r::GUI::PageFirmware Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
PageFirmware (ConfigWizard *parent)
virtual void apply_custom_config (DynamicPrintConfig &config)
template<class T >
T * append (T *thing, int proportion=0, int flag=wxEXPAND|wxTOP|wxBOTTOM, int border=10)
wxStaticText * append_text (wxString text)
void append_spacer (int space)
ConfigWizard::priv * wizard_p () const
virtual void set_run_reason (ConfigWizard::RunReason run_reason)
virtual void on_activate ()
Public Attributes
const ConfigOptionDef & gcode_opt
wxChoice * gcode_picker
ConfigWizard * parent
const wxString shortname
wxBoxSizer * content
const unsigned indent
Detailed Description
Constructor & Destructor Documentation
PageFirmware()
Slic3r::GUI::PageFirmware::PageFirmware (ConfigWizard * parent)
    : ConfigWizardPage(parent, _L("Firmware Type"), _L("Firmware"), 1)
    , gcode_opt(*print_config_def.get("gcode_flavor"))
    , gcode_picker(nullptr)
{
    append_text(_L("Choose the type of firmware used by your printer."));
    append_text(_(gcode_opt.tooltip));
    wxArrayString choices;
    choices.Alloc(gcode_opt.enum_def->labels().size());
    for (const auto &label : gcode_opt.enum_def->labels()) {
        choices.Add(label);
    }
    gcode_picker = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, choices);
    wxGetApp().UpdateDarkUI(gcode_picker);
    const auto &enum_values = gcode_opt.enum_def->values();
    auto needle = enum_values.cend();
    if (gcode_opt.default_value) {
        needle = std::find(enum_values.cbegin(), enum_values.cend(), gcode_opt.default_value->serialize());
    }
    if (needle != enum_values.cend()) {
        gcode_picker->SetSelection(needle - enum_values.cbegin());
    } else {
        gcode_picker->SetSelection(0);
    }
    append(gcode_picker);
}
References _, _L, Slic3r::GUI::ConfigWizardPage::append(), Slic3r::GUI::ConfigWizardPage::append_text(), Slic3r::ConfigOptionDef::default_value, Slic3r::ConfigOptionDef::enum_def, gcode_opt, gcode_picker, and Slic3r::ConfigOptionDef::tooltip.
Member Function Documentation
append()
template<class T > T * Slic3r::GUI::ConfigWizardPage::append (T * thing, int proportion = 0, int flag = wxEXPAND|wxTOP|wxBOTTOM, int border = 10) inline inherited
    {
        content->Add(thing, proportion, flag, border);
        return thing;
    }
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), PageFirmware(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), Slic3r::GUI::PageVendors::PageVendors(), and Slic3r::GUI::ConfigWizardPage::append_text().
append_spacer()
void Slic3r::GUI::ConfigWizardPage::append_spacer (int space) inherited
{
    // FIXME: scaling
    content->AddSpacer(space);
}
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageTemperatures::PageTemperatures(), and Slic3r::GUI::PageUpdate::PageUpdate().
append_text()
wxStaticText * Slic3r::GUI::ConfigWizardPage::append_text (wxString text) inherited
{
    auto *widget = new wxStaticText(this, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    widget->Wrap(WRAP_WIDTH);
    widget->SetMinSize(wxSize(WRAP_WIDTH, -1));
    append(widget);
    return widget;
}
References Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::WRAP_WIDTH.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), PageFirmware(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), and Slic3r::GUI::PageVendors::PageVendors().
apply_custom_config()
void Slic3r::GUI::PageFirmware::apply_custom_config (DynamicPrintConfig & config) virtual
Reimplemented from Slic3r::GUI::ConfigWizardPage.
{
    auto sel = gcode_picker->GetSelection();
    if (sel >= 0 && (size_t)sel < gcode_opt.enum_def->labels().size()) {
        auto *opt = new ConfigOptionEnum<GCodeFlavor>(static_cast<GCodeFlavor>(sel));
        config.set_key_value("gcode_flavor", opt);
    }
}
References gcode_picker, and Slic3r::DynamicConfig::set_key_value().
on_activate()
virtual void Slic3r::GUI::ConfigWizardPage::on_activate () inline virtual inherited
Reimplemented in Slic3r::GUI::PageMaterials.
{}
Referenced by Slic3r::GUI::PageMode::PageMode().
set_run_reason()
virtual void Slic3r::GUI::ConfigWizardPage::set_run_reason (ConfigWizard::RunReason run_reason) inline virtual inherited
Reimplemented in Slic3r::GUI::PageWelcome, and Slic3r::GUI::PagePrinters.
{}
wizard_p()
ConfigWizard::priv * Slic3r::GUI::ConfigWizardPage::wizard_p () const inline inherited
{ return parent->p.get(); }
References Slic3r::GUI::ConfigWizard::p, and Slic3r::GUI::ConfigWizardPage::parent.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageVendors::PageVendors(), Slic3r::GUI::PageMaterials::on_activate(), Slic3r::GUI::PageMaterials::select_material(), and Slic3r::GUI::PageMaterials::update_lists().
Member Data Documentation
content
wxBoxSizer* Slic3r::GUI::ConfigWizardPage::content inherited
Referenced by Slic3r::GUI::ConfigWizardPage::ConfigWizardPage(), Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::ConfigWizardPage::append_spacer().
gcode_opt
const ConfigOptionDef& Slic3r::GUI::PageFirmware::gcode_opt
Referenced by PageFirmware().
gcode_picker
wxChoice* Slic3r::GUI::PageFirmware::gcode_picker
Referenced by PageFirmware(), and apply_custom_config().
indent
const unsigned Slic3r::GUI::ConfigWizardPage::indent inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page().
parent
ConfigWizard* Slic3r::GUI::ConfigWizardPage::parent inherited
Referenced by Slic3r::GUI::PageMaterials::PageMaterials(), and Slic3r::GUI::ConfigWizardPage::wizard_p().
shortname
const wxString Slic3r::GUI::ConfigWizardPage::shortname inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page(), and Slic3r::GUI::ConfigWizard::priv::add_page().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp