Prusa Slicer: Slic3r::Model Class Reference
Slic3r::Model Class Reference final
#include <src/libslic3r/Model.hpp>
Public Types
enum class LoadAttribute : int { AddDefaultInstances , CheckVersion }
using LoadAttributes = enum_bitmask< LoadAttribute >
using Timestamp = uint64_t
Public Member Functions
Model ()
~Model ()
Model (const Model &rhs)
Model (Model &&rhs)
Model & operator= (const Model &rhs)
Model & operator= (Model &&rhs)
ModelObject * add_object ()
ModelObject * add_object (const char *name, const char *path, const TriangleMesh &mesh)
ModelObject * add_object (const char *name, const char *path, TriangleMesh &&mesh)
ModelObject * add_object (const ModelObject &other)
void delete_object (size_t idx)
bool delete_object (ObjectID id)
bool delete_object (ModelObject *object)
void clear_objects ()
ModelMaterial * add_material (t_model_material_id material_id)
ModelMaterial * add_material (t_model_material_id material_id, const ModelMaterial &other)
ModelMaterial * get_material (t_model_material_id material_id)
void delete_material (t_model_material_id material_id)
void clear_materials ()
bool add_default_instances ()
BoundingBoxf3 bounding_box_approx () const
BoundingBoxf3 bounding_box_exact () const
double max_z () const
unsigned int update_print_volume_state (const BuildVolume &build_volume)
bool center_instances_around_point (const Vec2d &point)
void translate (coordf_t x, coordf_t y, coordf_t z)
TriangleMesh mesh () const
void duplicate_objects_grid (size_t x, size_t y, coordf_t dist)
bool looks_like_multipart_object () const
void convert_multipart_object (unsigned int max_extruders)
bool looks_like_imperial_units () const
void convert_from_imperial_units (bool only_small_volumes)
bool looks_like_saved_in_meters () const
void convert_from_meters (bool only_small_volumes)
int removed_objects_with_zero_volume ()
void adjust_min_z ()
void print_info () const
std::string propose_export_file_name_and_path () const
std::string propose_export_file_name_and_path (const std::string &new_extension) const
bool is_fdm_support_painted () const
bool is_seam_painted () const
bool is_mm_painted () const
ObjectID id () const
virtual Timestamp timestamp () const
Static Public Member Functions
static Model read_from_file (const std::string &input_file, DynamicPrintConfig *config=nullptr, ConfigSubstitutionContext *config_substitutions=nullptr, LoadAttributes options=LoadAttribute::AddDefaultInstances)
static Model read_from_archive (const std::string &input_file, DynamicPrintConfig *config, ConfigSubstitutionContext *config_substitutions, LoadAttributes options=LoadAttribute::AddDefaultInstances)
Public Attributes
ModelMaterialMap materials
ModelObjectPtrs objects
ModelWipeTower wipe_tower
CustomGCode::Info custom_gcode_per_print_z
Protected Member Functions
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
Private Member Functions
Model (int)
void assign_new_unique_ids_recursive ()
void update_links_bottom_up_recursive ()
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class cereal::access
class UndoRedo::StackImpl
Detailed Description
Member Typedef Documentation
LoadAttributes
using Slic3r::Model::LoadAttributes = enum_bitmask<LoadAttribute>
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Member Enumeration Documentation
LoadAttribute
enum class Slic3r::Model::LoadAttribute : int strong
Enumerator
AddDefaultInstances
CheckVersion
                             : int {
        AddDefaultInstances,
        CheckVersion
    };
Constructor & Destructor Documentation
Model() [1/4]
Slic3r::Model::Model () inline
{ assert(this->id().valid()); }
~Model()
Slic3r::Model::~Model () inline
{ this->clear_objects(); this->clear_materials(); }
References clear_materials(), and clear_objects().
Model() [2/4]
Slic3r::Model::Model (const Model & rhs) inline
: ObjectBase(-1) { assert(this->id().invalid()); this->assign_copy(rhs); assert(this->id().valid()); assert(this->id() == rhs.id()); }
References Slic3r::ObjectBase::id().
Model() [3/4]
Slic3r::Model::Model (Model && rhs) inline explicit
: ObjectBase(-1) { assert(this->id().invalid()); this->assign_copy(std::move(rhs)); assert(this->id().valid()); assert(this->id() == rhs.id()); }
Model() [4/4]
Slic3r::Model::Model (int) inline explicit private
: ObjectBase(-1) { assert(this->id().invalid()); }
Member Function Documentation
add_default_instances()
bool Slic3r::Model::add_default_instances ()
{
    // apply a default position to all objects not having one
    for (ModelObject *o : this->objects)
        if (o->instances.empty())
            o->add_instance();
    return true;
}
References objects.
Referenced by read_from_archive(), read_from_file(), and Slic3r::CLI::run().
add_material() [1/2]
ModelMaterial * Slic3r::Model::add_material (t_model_material_id material_id)
{
    assert(! material_id.empty());
    ModelMaterial* material = this->get_material(material_id);
    if (material == nullptr)
        material = this->materials[material_id] = new ModelMaterial(this);
    return material;
}
References get_material(), and materials.
Referenced by Slic3r::ModelVolume::set_material(), and Slic3r::AMFParserContext::startElement().
add_material() [2/2]
ModelMaterial * Slic3r::Model::add_material (t_model_material_id material_id, const ModelMaterial & other)
{
    assert(! material_id.empty());
    // delete existing material if any
    ModelMaterial* material = this->get_material(material_id);
    delete material;
    // set new material
  material = new ModelMaterial(other);
  material->set_model(this);
    this->materials[material_id] = material;
    return material;
}
References get_material(), materials, and Slic3r::ModelMaterial::set_model().
add_object() [1/4]
ModelObject * Slic3r::Model::add_object ()
{
    this->objects.emplace_back(new ModelObject(this));
    return this->objects.back();
}
References objects.
Referenced by Slic3r::GUI::GLGizmoCut3D::PartSelection::PartSelection(), Slic3r::_3MF_Importer::_handle_start_object(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::GUI::Selection::Clipboard::add_object(), Slic3r::GUI::ObjectList::instances_to_separated_object(), Slic3r::GUI::ObjectList::instances_to_separated_objects(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::load_obj(), Slic3r::load_step(), Slic3r::load_stl(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::Selection::paste_objects_from_clipboard(), Slic3r::CLI::run(), and Slic3r::AMFParserContext::startElement().
add_object() [2/4]
ModelObject * Slic3r::Model::add_object (const char * name, const char * path, const TriangleMesh & mesh)
{
    ModelObject* new_object = new ModelObject(this);
    this->objects.push_back(new_object);
    new_object->name = name;
    new_object->input_file = path;
    ModelVolume *new_volume = new_object->add_volume(mesh);
    new_volume->name = name;
    new_volume->source.input_file = path;
    new_volume->source.object_idx = (int)this->objects.size() - 1;
    new_volume->source.volume_idx = (int)new_object->volumes.size() - 1;
    new_object->invalidate_bounding_box();
    return new_object;
}
References Slic3r::ModelObject::add_volume(), Slic3r::ModelObject::input_file, Slic3r::ModelVolume::Source::input_file, Slic3r::ModelObject::invalidate_bounding_box(), mesh(), Slic3r::ModelObject::name, Slic3r::ModelVolume::name, Slic3r::ModelVolume::Source::object_idx, objects, Slic3r::ModelVolume::source, Slic3r::ModelVolume::Source::volume_idx, and Slic3r::ModelObject::volumes.
add_object() [3/4]
ModelObject * Slic3r::Model::add_object (const char * name, const char * path, TriangleMesh && mesh)
{
    ModelObject* new_object = new ModelObject(this);
    this->objects.push_back(new_object);
    new_object->name = name;
    new_object->input_file = path;
    ModelVolume *new_volume = new_object->add_volume(std::move(mesh));
    new_volume->name = name;
    new_volume->source.input_file = path;
    new_volume->source.object_idx = (int)this->objects.size() - 1;
    new_volume->source.volume_idx = (int)new_object->volumes.size() - 1;
    new_object->invalidate_bounding_box();
    return new_object;
}
References Slic3r::ModelObject::add_volume(), Slic3r::ModelObject::input_file, Slic3r::ModelVolume::Source::input_file, Slic3r::ModelObject::invalidate_bounding_box(), mesh(), Slic3r::ModelObject::name, Slic3r::ModelVolume::name, Slic3r::ModelVolume::Source::object_idx, objects, Slic3r::ModelVolume::source, Slic3r::ModelVolume::Source::volume_idx, and Slic3r::ModelObject::volumes.
add_object() [4/4]
ModelObject * Slic3r::Model::add_object (const ModelObject & other)
{
  ModelObject* new_object = ModelObject::new_clone(other);
    new_object->set_model(this);
    this->objects.push_back(new_object);
    return new_object;
}
References objects, and Slic3r::ModelObject::set_model().
adjust_min_z()
void Slic3r::Model::adjust_min_z ()
{
    if (objects.empty())
        return;
    if (this->bounding_box_exact().min.z() < 0.0)
    {
        for (ModelObject* obj : objects)
        {
            if (obj != nullptr)
            {
                coordf_t obj_min_z = obj->min_z();
                if (obj_min_z < 0.0)
                    obj->translate_instances(Vec3d(0.0, 0.0, -obj_min_z));
            }
        }
    }
}
References bounding_box_exact(), and objects.
assign_new_unique_ids_recursive()
void Slic3r::Model::assign_new_unique_ids_recursive () private virtual
Reimplemented from Slic3r::ObjectBase.
{
    this->set_new_unique_id();
    for (std::pair<const t_model_material_id, ModelMaterial*> &m : this->materials)
        m.second->assign_new_unique_ids_recursive();
    for (ModelObject *model_object : this->objects)
        model_object->assign_new_unique_ids_recursive();
}
References materials, objects, and Slic3r::ObjectBase::set_new_unique_id().
bounding_box_approx()
BoundingBoxf3 Slic3r::Model::bounding_box_approx () const
{
    BoundingBoxf3 bb;
    for (ModelObject *o : this->objects)
        bb.merge(o->bounding_box_approx());
    return bb;
}
References Slic3r::BoundingBox3Base< PointType >::merge(), and objects.
bounding_box_exact()
BoundingBoxf3 Slic3r::Model::bounding_box_exact () const
{
    BoundingBoxf3 bb;
    for (ModelObject *o : this->objects)
        bb.merge(o->bounding_box_exact());
    return bb;
}
References Slic3r::BoundingBox3Base< PointType >::merge(), and objects.
Referenced by adjust_min_z().
center_instances_around_point()
bool Slic3r::Model::center_instances_around_point (const Vec2d & point)
{
    BoundingBoxf3 bb;
    for (ModelObject *o : this->objects)
        for (size_t i = 0; i < o->instances.size(); ++ i)
            bb.merge(o->instance_bounding_box(i, false));
    Vec2d shift2 = point - to_2d(bb.center());
  if (std::abs(shift2(0)) < EPSILON && std::abs(shift2(1)) < EPSILON)
    // No significant shift, don't do anything.
    return false;
  Vec3d shift3 = Vec3d(shift2(0), shift2(1), 0.0);
  for (ModelObject *o : this->objects) {
    for (ModelInstance *i : o->instances)
      i->set_offset(i->get_offset() + shift3);
    o->invalidate_bounding_box();
  }
  return true;
}
References Slic3r::BoundingBox3Base< PointType >::center(), EPSILON, Slic3r::BoundingBox3Base< PointType >::merge(), objects, and Slic3r::to_2d().
Referenced by Slic3r::GUI::generate_thumbnail_from_model(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::ObjectList::load_modifier(), and Slic3r::GUI::Plater::priv::update().
clear_materials()
void Slic3r::Model::clear_materials ()
{
    for (auto &m : this->materials)
        delete m.second;
    this->materials.clear();
}
References materials.
Referenced by ~Model(), and Slic3r::UndoRedo::StackImpl::load_snapshot().
clear_objects()
void Slic3r::Model::clear_objects ()
{
    for (ModelObject *o : this->objects)
        delete o;
    this->objects.clear();
}
References objects.
Referenced by ~Model(), Slic3r::GUI::GLGizmoCut3D::PartSelection::~PartSelection(), Slic3r::Print::clear(), Slic3r::SLAPrint::clear(), convert_multipart_object(), Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::Plater::priv::reset(), and Slic3r::GUI::Selection::Clipboard::reset().
convert_from_imperial_units()
void Slic3r::Model::convert_from_imperial_units (bool only_small_volumes)
{
    static constexpr const float in_to_mm = 25.4f;
    for (ModelObject* obj : this->objects)
        if (! only_small_volumes || obj->get_object_stl_stats().volume < volume_threshold_inches) {
            obj->scale_mesh_after_creation(in_to_mm);
            for (ModelVolume* v : obj->volumes) {
                assert(! v->source.is_converted_from_meters);
                v->source.is_converted_from_inches = true;
            }
        }
}
References objects, and Slic3r::volume_threshold_inches.
Referenced by Slic3r::GUI::Plater::priv::load_files().
convert_from_meters()
void Slic3r::Model::convert_from_meters (bool only_small_volumes)
{
    static constexpr const double m_to_mm = 1000;
    for (ModelObject* obj : this->objects)
        if (! only_small_volumes || obj->get_object_stl_stats().volume < volume_threshold_meters) {
            obj->scale_mesh_after_creation(m_to_mm);
            for (ModelVolume* v : obj->volumes) {
                assert(! v->source.is_converted_from_inches);
                v->source.is_converted_from_meters = true;
            }
        }
}
References objects, and Slic3r::volume_threshold_meters.
Referenced by Slic3r::GUI::Plater::priv::load_files().
convert_multipart_object()
void Slic3r::Model::convert_multipart_object (unsigned int max_extruders)
{
  assert(this->objects.size() >= 2);
    if (this->objects.size() < 2)
        return;
    ModelObject* object = new ModelObject(this);
    object->input_file = this->objects.front()->input_file;
    object->name = boost::filesystem::path(this->objects.front()->input_file).stem().string();
    //FIXME copy the config etc?
    unsigned int extruder_counter = 0;
  for (const ModelObject* o : this->objects)
      for (const ModelVolume* v : o->volumes) {
            // If there are more than one object, put all volumes together
            // Each object may contain any number of volumes and instances
            // The volumes transformations are relative to the object containing them...
            Geometry::Transformation trafo_volume = v->get_transformation();
            // Revert the centering operation.
            trafo_volume.set_offset(trafo_volume.get_offset() - o->origin_translation);
            int counter = 1;
            auto copy_volume = [o, max_extruders, &counter, &extruder_counter](ModelVolume *new_v) {
                assert(new_v != nullptr);
                new_v->name = (counter > 1) ? o->name + "_" + std::to_string(counter++) : o->name;
                new_v->config.set("extruder", auto_extruder_id(max_extruders, extruder_counter));
                return new_v;
            };
            if (o->instances.empty()) {
              copy_volume(object->add_volume(*v))->set_transformation(trafo_volume);
            } else {
              for (const ModelInstance* i : o->instances)
                    // ...so, transform everything to a common reference system (world)
                  copy_volume(object->add_volume(*v))->set_transformation(i->get_transformation() * trafo_volume);
            }
        }
    // commented-out to fix #2868
//    object->add_instance();
//    object->instances[0]->set_offset(object->raw_mesh_bounding_box().center());
    this->clear_objects();
    this->objects.push_back(object);
}
References Slic3r::ModelObject::add_volume(), Slic3r::auto_extruder_id(), clear_objects(), Slic3r::Geometry::Transformation::get_offset(), objects, and Slic3r::Geometry::Transformation::set_offset().
Referenced by Slic3r::GUI::Plater::priv::load_files().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
delete_material()
void Slic3r::Model::delete_material (t_model_material_id material_id)
{
    ModelMaterialMap::iterator i = this->materials.find(material_id);
    if (i != this->materials.end()) {
        delete i->second;
        this->materials.erase(i);
    }
}
References materials.
delete_object() [1/3]
bool Slic3r::Model::delete_object (ModelObject * object)
{
    if (object != nullptr) {
        size_t idx = 0;
        for (ModelObject *model_object : objects) {
            if (model_object == object) {
                delete model_object;
                objects.erase(objects.begin() + idx);
                return true;
            }
            ++ idx;
        }
    }
    return false;
}
References objects.
delete_object() [2/3]
bool Slic3r::Model::delete_object (ObjectID id)
{
    if (id.id != 0) {
        size_t idx = 0;
        for (ModelObject *model_object : objects) {
            if (model_object->id() == id) {
                delete model_object;
                objects.erase(objects.begin() + idx);
                return true;
            }
            ++ idx;
        }
    }
    return false;
}
References Slic3r::ObjectBase::id(), and objects.
delete_object() [3/3]
void Slic3r::Model::delete_object (size_t idx)
{
    ModelObjectPtrs::iterator i = this->objects.begin() + idx;
    delete *i;
    this->objects.erase(i);
}
References objects.
Referenced by Slic3r::_3MF_Importer::_handle_end_model(), Slic3r::_3MF_Importer::_handle_end_object(), Slic3r::GUI::Plater::cut(), Slic3r::GUI::ObjectList::delete_all_connectors_for_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::Plater::priv::remove(), and removed_objects_with_zero_volume().
duplicate_objects_grid()
void Slic3r::Model::duplicate_objects_grid (size_t x, size_t y, coordf_t dist)
{
    if (this->objects.size() > 1) throw "Grid duplication is not supported with multiple objects";
    if (this->objects.empty()) throw "No objects!";
    ModelObject* object = this->objects.front();
    object->clear_instances();
    Vec3d ext_size = object->bounding_box_exact().size() + dist * Vec3d::Ones();
    for (size_t x_copy = 1; x_copy <= x; ++x_copy) {
        for (size_t y_copy = 1; y_copy <= y; ++y_copy) {
            ModelInstance* instance = object->add_instance();
            instance->set_offset(Vec3d(ext_size(0) * (double)(x_copy - 1), ext_size(1) * (double)(y_copy - 1), 0.0));
        }
    }
}
References objects, and Slic3r::ModelInstance::set_offset().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_material()
ModelMaterial * Slic3r::Model::get_material (t_model_material_id material_id) inline
{
        ModelMaterialMap::iterator i = this->materials.find(material_id);
        return (i == this->materials.end()) ? nullptr : i->second;
    }
Referenced by add_material(), add_material(), and Slic3r::ModelVolume::material().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::ModelVolume::check(), Slic3r::check_model_ids_equal(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), anonymous_namespace{RaycastManager.cpp}::create_key(), priv::create_volume(), Slic3r::GUI::Emboss::create_volume_sources(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), delete_object(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::ModelObjectStatusDB::get(), Slic3r::GUI::get_arrange_poly(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::inner_brim_area(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ObjectBase::load_and_construct(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::CutObjectBase::operator<(), operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::GLGizmoEmboss::process(), Slic3r::GUI::processed_objects_idxs(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::top_level_outer_brim_area(), Slic3r::GUI::update_object_cut_id(), and anonymous_namespace{EmbossJob.cpp}::update_volume_name().
is_fdm_support_painted()
bool Slic3r::Model::is_fdm_support_painted () const
{
    return std::any_of(this->objects.cbegin(), this->objects.cend(), [](const ModelObject *mo) { return mo->is_fdm_support_painted(); });
}
References objects.
Referenced by Slic3r::_3MF_Exporter::_add_model_file_to_archive().
is_mm_painted()
bool Slic3r::Model::is_mm_painted () const
{
    return std::any_of(this->objects.cbegin(), this->objects.cend(), [](const ModelObject *mo) { return mo->is_mm_painted(); });
}
References objects.
Referenced by Slic3r::_3MF_Exporter::_add_model_file_to_archive().
is_seam_painted()
bool Slic3r::Model::is_seam_painted () const
{
    return std::any_of(this->objects.cbegin(), this->objects.cend(), [](const ModelObject *mo) { return mo->is_seam_painted(); });
}
References objects.
Referenced by Slic3r::_3MF_Exporter::_add_model_file_to_archive().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
looks_like_imperial_units()
bool Slic3r::Model::looks_like_imperial_units () const
{
    if (this->objects.empty())
        return false;
    for (ModelObject* obj : this->objects)
        if (obj->get_object_stl_stats().volume < volume_threshold_inches) {
            if (!obj->is_cut())
                return true;
            bool all_cut_parts_look_like_imperial_units = true;
            for (ModelObject* obj_other : this->objects) {
                if (obj_other == obj)
                    continue;
                if (obj_other->cut_id.is_equal(obj->cut_id) && obj_other->get_object_stl_stats().volume >= volume_threshold_inches) {
                    all_cut_parts_look_like_imperial_units = false;
                    break;
                }
            }
            if (all_cut_parts_look_like_imperial_units)
                return true;
        }
    return false;
}
References objects, and Slic3r::volume_threshold_inches.
Referenced by Slic3r::GUI::Plater::priv::load_files().
looks_like_multipart_object()
bool Slic3r::Model::looks_like_multipart_object () const
{
    if (this->objects.size() <= 1)
        return false;
    double zmin = std::numeric_limits<double>::max();
    for (const ModelObject *obj : this->objects) {
        if (obj->volumes.size() > 1 || obj->config.keys().size() > 1)
            return false;
        for (const ModelVolume *vol : obj->volumes) {
            double zmin_this = vol->mesh().bounding_box().min(2);
            if (zmin == std::numeric_limits<double>::max())
                zmin = zmin_this;
            else if (std::abs(zmin - zmin_this) > EPSILON)
                // The volumes don't share zmin.
                return true;
        }
    }
    return false;
}
References EPSILON, and objects.
Referenced by Slic3r::GUI::Plater::priv::load_files().
looks_like_saved_in_meters()
bool Slic3r::Model::looks_like_saved_in_meters () const
{
    if (this->objects.size() == 0)
        return false;
    for (ModelObject* obj : this->objects)
        if (obj->get_object_stl_stats().volume < volume_threshold_meters)
            return true;
    return false;
}
References objects, and Slic3r::volume_threshold_meters.
Referenced by Slic3r::GUI::Plater::priv::load_files().
max_z()
double Slic3r::Model::max_z () const
{
    double z = 0;
    for (ModelObject *o : this->objects)
        z = std::max(z, o->max_z());
    return z;
}
References objects.
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene().
mesh()
TriangleMesh Slic3r::Model::mesh () const
{
    TriangleMesh mesh;
    for (const ModelObject *o : this->objects)
        mesh.merge(o->mesh());
    return mesh;
}
References Slic3r::TriangleMesh::merge(), mesh(), and objects.
Referenced by add_object(), add_object(), Slic3r::GUI::generate_thumbnail_from_model(), Slic3r::GUI::GLModel::init_from_file(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::BedShapePanel::load_stl(), mesh(), Slic3r::store_obj(), and Slic3r::store_stl().
operator=() [1/2]
Model & Slic3r::Model::operator= (const Model & rhs) inline
{ this->assign_copy(rhs); assert(this->id().valid()); assert(this->id() == rhs.id()); return *this; }
References Slic3r::ObjectBase::id().
operator=() [2/2]
Model & Slic3r::Model::operator= (Model && rhs) inline
{ this->assign_copy(std::move(rhs)); assert(this->id().valid()); assert(this->id() == rhs.id()); return *this; }
print_info()
void Slic3r::Model::print_info () const inline
{ for (const ModelObject *o : this->objects) o->print_info(); }
References objects.
propose_export_file_name_and_path() [1/2]
std::string Slic3r::Model::propose_export_file_name_and_path () const
{
    std::string input_file;
    for (const ModelObject *model_object : this->objects)
        for (ModelInstance *model_instance : model_object->instances)
            if (model_instance->is_printable()) {
                input_file = model_object->get_export_filename();
                if (!input_file.empty())
                    goto end;
                // Other instances will produce the same name, skip them.
                break;
            }
end:
    return input_file;
}
References objects.
Referenced by Slic3r::GUI::Plater::priv::get_export_file_path(), Slic3r::CLI::output_filepath(), Slic3r::PrintBase::output_filepath(), and propose_export_file_name_and_path().
propose_export_file_name_and_path() [2/2]
std::string Slic3r::Model::propose_export_file_name_and_path (const std::string & new_extension) const
{
    return boost::filesystem::path(this->propose_export_file_name_and_path()).replace_extension(new_extension).string();
}
References propose_export_file_name_and_path().
read_from_archive()
Model Slic3r::Model::read_from_archive (const std::string & input_file, DynamicPrintConfig * config, ConfigSubstitutionContext * config_substitutions, LoadAttributes options = LoadAttribute::AddDefaultInstances) static
{
    assert(config != nullptr);
    assert(config_substitutions != nullptr);
    Model model;
    bool result = false;
    if (boost::algorithm::iends_with(input_file, ".3mf") || boost::algorithm::iends_with(input_file, ".zip"))
        result = load_3mf(input_file.c_str(), *config, *config_substitutions, &model, options & LoadAttribute::CheckVersion);
    else if (boost::algorithm::iends_with(input_file, ".zip.amf"))
        result = load_amf(input_file.c_str(), config, config_substitutions, &model, options & LoadAttribute::CheckVersion);
    else
        throw Slic3r::RuntimeError("Unknown file format. Input file must have .3mf or .zip.amf extension.");
    if (!result)
        throw Slic3r::RuntimeError("Loading of a model file failed.");
    for (ModelObject *o : model.objects) {
//        if (boost::algorithm::iends_with(input_file, ".zip.amf"))
//        {
//            // we remove the .zip part of the extension to avoid it be added to filenames when exporting
//            o->input_file = boost::ireplace_last_copy(input_file, ".zip.", ".");
//        }
//        else
            o->input_file = input_file;
    }
    if (options & LoadAttribute::AddDefaultInstances)
        model.add_default_instances();
    CustomGCode::update_custom_gcode_per_print_z_from_config(model.custom_gcode_per_print_z, config);
    CustomGCode::check_mode_for_custom_gcode_per_print_z(model.custom_gcode_per_print_z);
    handle_legacy_sla(*config);
    return model;
}
References add_default_instances(), AddDefaultInstances, Slic3r::CustomGCode::check_mode_for_custom_gcode_per_print_z(), CheckVersion, custom_gcode_per_print_z, Slic3r::handle_legacy_sla(), Slic3r::load_3mf(), Slic3r::load_amf(), objects, and Slic3r::CustomGCode::update_custom_gcode_per_print_z_from_config().
Referenced by Slic3r::GUI::Plater::priv::load_files().
read_from_file()
Model Slic3r::Model::read_from_file (const std::string & input_file, DynamicPrintConfig * config = nullptr, ConfigSubstitutionContext * config_substitutions = nullptr, LoadAttributes options = LoadAttribute::AddDefaultInstances) static
{
    Model model;
    DynamicPrintConfig temp_config;
    ConfigSubstitutionContext temp_config_substitutions_context(ForwardCompatibilitySubstitutionRule::EnableSilent);
    if (config == nullptr)
        config = &temp_config;
    if (config_substitutions == nullptr)
        config_substitutions = &temp_config_substitutions_context;
    bool result = false;
    if (boost::algorithm::iends_with(input_file, ".stl"))
        result = load_stl(input_file.c_str(), &model);
    else if (boost::algorithm::iends_with(input_file, ".obj"))
        result = load_obj(input_file.c_str(), &model);
    else if (boost::algorithm::iends_with(input_file, ".step") || boost::algorithm::iends_with(input_file, ".stp"))
        result = load_step(input_file.c_str(), &model);
    else if (boost::algorithm::iends_with(input_file, ".amf") || boost::algorithm::iends_with(input_file, ".amf.xml"))
        result = load_amf(input_file.c_str(), config, config_substitutions, &model, options & LoadAttribute::CheckVersion);
    else if (boost::algorithm::iends_with(input_file, ".3mf") || boost::algorithm::iends_with(input_file, ".zip"))
        //FIXME options & LoadAttribute::CheckVersion ?
        result = load_3mf(input_file.c_str(), *config, *config_substitutions, &model, false);
    else
        throw Slic3r::RuntimeError("Unknown file format. Input file must have .stl, .obj, .amf(.xml), .prusa or .step/.stp extension.");
    if (! result)
        throw Slic3r::RuntimeError("Loading of a model file failed.");
    if (model.objects.empty())
        throw Slic3r::RuntimeError("The supplied file couldn't be read because it's empty");
    for (ModelObject *o : model.objects)
        o->input_file = input_file;
    if (options & LoadAttribute::AddDefaultInstances)
        model.add_default_instances();
    CustomGCode::update_custom_gcode_per_print_z_from_config(model.custom_gcode_per_print_z, config);
    CustomGCode::check_mode_for_custom_gcode_per_print_z(model.custom_gcode_per_print_z);
    sort_remove_duplicates(config_substitutions->substitutions);
    return model;
}
References add_default_instances(), AddDefaultInstances, Slic3r::CustomGCode::check_mode_for_custom_gcode_per_print_z(), CheckVersion, custom_gcode_per_print_z, Slic3r::EnableSilent, Slic3r::load_3mf(), Slic3r::load_amf(), Slic3r::load_obj(), Slic3r::load_step(), Slic3r::load_stl(), objects, Slic3r::sort_remove_duplicates(), Slic3r::ConfigSubstitutionContext::substitutions, and Slic3r::CustomGCode::update_custom_gcode_per_print_z_from_config().
Referenced by Slic3r::GUI::generate_thumbnail_from_model(), Slic3r::GUI::GLModel::init_from_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::BedShapePanel::load_stl(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), and Slic3r::CLI::run().
removed_objects_with_zero_volume()
int Slic3r::Model::removed_objects_with_zero_volume ()
{
    if (objects.size() == 0)
        return 0;
    int removed = 0;
    for (int i = int(objects.size()) - 1; i >= 0; i--)
        if (objects[i]->get_object_stl_stats().volume < zero_volume) {
            delete_object(size_t(i));
            removed++;
        }
    return removed;
}
References delete_object(), objects, and Slic3r::zero_volume.
Referenced by Slic3r::GUI::Plater::priv::load_files().
serialize()
template<class Archive > void Slic3r::Model::serialize (Archive & ar) inline private
{
    Internal::StaticSerializationWrapper<ModelWipeTower> wipe_tower_wrapper(wipe_tower);
    ar(materials, objects, wipe_tower_wrapper);
    }
References materials, objects, and wipe_tower.
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
Referenced by Slic3r::GUI::Plater::priv::undo_redo_to().
translate()
void Slic3r::Model::translate (coordf_t x, coordf_t y, coordf_t z) inline
{ for (ModelObject *o : this->objects) o->translate(x, y, z); }
References objects.
update_links_bottom_up_recursive()
void Slic3r::Model::update_links_bottom_up_recursive () private
{
  for (std::pair<const t_model_material_id, ModelMaterial*> &kvp : this->materials)
    kvp.second->set_model(this);
  for (ModelObject *model_object : this->objects) {
    model_object->set_model(this);
    for (ModelInstance *model_instance : model_object->instances)
      model_instance->set_model_object(model_object);
    for (ModelVolume *model_volume : model_object->volumes)
      model_volume->set_model_object(model_object);
  }
}
References materials, and objects.
Referenced by Slic3r::UndoRedo::StackImpl::load_snapshot().
update_print_volume_state()
unsigned int Slic3r::Model::update_print_volume_state (const BuildVolume & build_volume)
{
    unsigned int num_printable = 0;
    for (ModelObject* model_object : this->objects)
        num_printable += model_object->update_instances_print_volume_state(build_volume);
    return num_printable;
}
References objects.
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
UndoRedo::StackImpl
friend class UndoRedo::StackImpl friend
Member Data Documentation
custom_gcode_per_print_z
CustomGCode::Info Slic3r::Model::custom_gcode_per_print_z
Referenced by Slic3r::ToolOrdering::ToolOrdering(), Slic3r::_3MF_Exporter::_add_custom_gcode_per_print_z_file_to_archive(), Slic3r::_3MF_Importer::_extract_custom_gcode_per_print_z_from_archive(), Slic3r::Print::apply(), Slic3r::ToolOrdering::assign_custom_gcodes(), Slic3r::GUI::Preview::create_layers_slider_sizer(), Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::AMFParserContext::endElement(), Slic3r::GUI::Plater::priv::load_files(), read_from_archive(), read_from_file(), Slic3r::GUI::Plater::priv::reset(), Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets(), Slic3r::store_amf(), Slic3r::GUI::Preview::update_layers_slider(), and Slic3r::DoExport::validate_custom_gcode().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
materials
ModelMaterialMap Slic3r::Model::materials
Referenced by add_material(), add_material(), assign_new_unique_ids_recursive(), Slic3r::check_model_ids_equal(), Slic3r::check_model_ids_validity(), clear_materials(), delete_material(), serialize(), Slic3r::store_amf(), and update_links_bottom_up_recursive().
objects
ModelObjectPtrs Slic3r::Model::objects
Referenced by Slic3r::GUI::GLGizmoCut3D::PartSelection::PartSelection(), Slic3r::GUI::PlaterAfterLoadAutoArrange::PlaterAfterLoadAutoArrange(), Slic3r::_3MF_Exporter::_add_cut_information_file_to_archive(), Slic3r::_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_3MF_Exporter::_add_layer_height_profile_file_to_archive(), Slic3r::_3MF_Exporter::_add_model_file_to_archive(), Slic3r::_3MF_Exporter::_add_sla_drain_holes_file_to_archive(), Slic3r::_3MF_Exporter::_add_sla_support_points_file_to_archive(), Slic3r::_3MF_Importer::_create_object_instance(), Slic3r::_3MF_Importer::_handle_end_model(), Slic3r::_3MF_Importer::_handle_start_object(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::GUI::Plater::priv::actualize_object_warnings(), Slic3r::GUI::Selection::add(), add_default_instances(), add_object(), add_object(), add_object(), add_object(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), adjust_min_z(), Slic3r::GUI::MenuFactory::append_menu_item_edit_text(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), priv::apply_camera_dir(), assign_new_unique_ids_recursive(), bounding_box_approx(), bounding_box_exact(), Slic3r::GUI::calc_surface_offset(), Slic3r::GUI::Plater::priv::can_arrange(), Slic3r::GUI::Plater::priv::can_decrease_instances(), Slic3r::GUI::MainFrame::can_delete_all(), Slic3r::GUI::Plater::priv::can_delete_all(), Slic3r::GUI::MainFrame::can_export_gcode(), Slic3r::GUI::MainFrame::can_export_gcode_sd(), Slic3r::GUI::MainFrame::can_export_model(), Slic3r::GUI::MainFrame::can_export_supports(), Slic3r::GUI::Plater::priv::can_fix_through_netfabb(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::MainFrame::can_reslice(), Slic3r::GUI::MainFrame::can_select(), Slic3r::GUI::MainFrame::can_send_gcode(), Slic3r::GUI::Plater::priv::can_set_instance_to_object(), Slic3r::GUI::Plater::priv::can_simplify(), Slic3r::GUI::MainFrame::can_slice(), Slic3r::GUI::MainFrame::can_start_new_project(), center_instances_around_point(), Slic3r::GUI::Plater::changed_mesh(), Slic3r::GUI::Plater::changed_objects(), Slic3r::check_model_ids_equal(), Slic3r::check_model_ids_validity(), Slic3r::GUI::GLCanvas3D::check_volumes_outside_state(), Slic3r::GUI::Plater::clear_before_change_mesh(), Slic3r::GUI::ArrangeJob::clear_input(), clear_objects(), convert_from_imperial_units(), convert_from_meters(), convert_multipart_object(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::create_meshes(), Slic3r::GUI::GLGizmoEmboss::create_volume(), priv::create_volume(), Slic3r::GUI::Plater::cut(), Slic3r::GUI::GLGizmoFlatten::data_changed(), delete_object(), delete_object(), delete_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_reset_skew(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::duplicate(), Slic3r::duplicate_objects(), duplicate_objects_grid(), Slic3r::AMFParserContext::endDocument(), Slic3r::AMFParserContext::endElement(), Slic3r::GUI::Selection::erase(), Slic3r::GUI::Plater::priv::export_gcode(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::generate_thumbnail_from_model(), Slic3r::get_arrange_poly(), Slic3r::get_arrange_polys(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::GUI::GLGizmoCut3D::get_cut_matrix(), Slic3r::GUI::Plater::priv::get_export_file_path(), Slic3r::GUI::get_model_instance(), Slic3r::GUI::get_model_object(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::Selection::Clipboard::get_object(), Slic3r::GUI::Selection::Clipboard::get_objects(), Slic3r::GUI::Plater::priv::get_selected_instance_idx(), Slic3r::GUI::Plater::priv::get_selected_object_idx(), Slic3r::GUI::get_selected_volume(), Slic3r::GUI::Plater::priv::get_selected_volume_idx(), Slic3r::GUI::get_volume(), Slic3r::GUI::get_volume_ids(), Slic3r::GUI::Selection::get_volume_idxs_from_object(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::Selection::instances_changed(), Slic3r::GUI::Selection::is_any_connector(), Slic3r::GUI::Selection::is_any_cut_volume(), Slic3r::GUI::Selection::Clipboard::is_empty(), is_fdm_support_painted(), Slic3r::GUI::Selection::is_from_fully_selected_instance(), Slic3r::GUI::Selection::is_from_single_object(), is_mm_painted(), is_seam_painted(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_text(), Slic3r::GUI::Plater::priv::layers_height_allowed(), Slic3r::load_3mf(), Slic3r::load_amf_archive(), Slic3r::load_amf_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::GLCanvas3D::load_object(), Slic3r::load_step(), looks_like_imperial_units(), looks_like_multipart_object(), looks_like_saved_in_meters(), max_z(), Slic3r::GUI::ObjectList::merge(), mesh(), Slic3r::model_has_advanced_features(), Slic3r::model_has_multi_part_objects(), Slic3r::model_has_parameter_modifiers_in_objects(), Slic3r::GUI::GLGizmoCut3D::PartSelection::model_object(), Slic3r::model_object_list_equal(), Slic3r::model_object_list_extended(), Slic3r::GUI::object_contains_negative_volumes(), Slic3r::GUI::object_has_sla_drain_holes(), Slic3r::GUI::Plater::priv::object_list_changed(), Slic3r::GUI::GLGizmoEmboss::on_mouse(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::on_mouse_surface_drag(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::Selection::paste_objects_from_clipboard(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_selected(), print_info(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::processed_objects_idxs(), propose_export_file_name_and_path(), read_from_archive(), read_from_file(), Slic3r::GUI::Plater::priv::reload_all_from_disk(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::reloadable_volumes(), removed_objects_with_zero_volume(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GLGizmoCut3D::reset_cut_by_contours(), Slic3r::GUI::Plater::reslice(), Slic3r::CLI::run(), Slic3r::GUI::GUI_App::save_mode(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), serialize(), Slic3r::GUI::Plater::priv::set_current_panel(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), Slic3r::sort_object_instances_by_model_order(), Slic3r::GUI::Plater::priv::split_object(), priv::start_create_volume_on_surface_job(), Slic3r::AMFParserContext::startElement(), Slic3r::store_amf(), Slic3r::GUI::synchronize_model_after_cut(), Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility(), Slic3r::GUI::GLCanvas3D::toggle_sla_auxiliaries_visibility(), translate(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::GLCanvas3D::update_instance_printable_state_for_object(), update_links_bottom_up_recursive(), Slic3r::PrintBase::update_object_placeholders(), update_print_volume_state(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), Slic3r::GUI::Selection::update_type(), priv::update_volume(), Slic3r::GUI::verify_instances_rotation_synchronized(), and Slic3r::GUI::world_matrix_fixed().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
wipe_tower
ModelWipeTower Slic3r::Model::wipe_tower
Referenced by serialize(), Slic3r::GUI::Plater::priv::take_snapshot(), and Slic3r::GUI::Plater::priv::undo_redo_to().
The documentation for this class was generated from the following files:
src/libslic3r/Model.hpp
src/libslic3r/Model.cpp