Prusa Slicer: Slic3r::opt::StopCriteria Class Reference
Slic3r::opt::StopCriteria Class Reference
#include <src/libslic3r/Optimize/Optimizer.hpp>
Public Member Functions
StopCriteria & abs_score_diff (double val)
double abs_score_diff () const
StopCriteria & rel_score_diff (double val)
double rel_score_diff () const
StopCriteria & stop_score (double val)
double stop_score () const
StopCriteria & max_iterations (unsigned val)
double max_iterations () const
template<class Fn >
StopCriteria & stop_condition (Fn &&cond)
bool stop_condition ()
Private Attributes
double m_abs_score_diff = NaNd
double m_rel_score_diff = NaNd
double m_stop_score = NaNd
std::function< bool()> m_stop_condition = [] { return false; }
unsigned m_max_iterations = 0
Detailed Description
Member Function Documentation
abs_score_diff() [1/2]
double Slic3r::opt::StopCriteria::abs_score_diff () const inline
{ return m_abs_score_diff; }
References m_abs_score_diff.
abs_score_diff() [2/2]
StopCriteria & Slic3r::opt::StopCriteria::abs_score_diff (double val) inline
    {
        m_abs_score_diff = val; return *this;
    }
References m_abs_score_diff.
Referenced by Slic3r::opt::detail::AlgBurteForce::run(), and Slic3r::opt::detail::NLoptOpt< M, class >::set_up().
max_iterations() [1/2]
double Slic3r::opt::StopCriteria::max_iterations () const inline
{ return m_max_iterations; }
References m_max_iterations.
max_iterations() [2/2]
StopCriteria & Slic3r::opt::StopCriteria::max_iterations (unsigned val) inline
    {
        m_max_iterations = val; return *this;
    }
References m_max_iterations.
Referenced by Slic3r::sla::find_best_misalignment_rotation(), Slic3r::sla::find_least_supports_rotation(), Slic3r::sla::get_criteria(), Slic3r::sla::optimize_anchor_placement(), Slic3r::sla::optimize_pinhead_placement(), Slic3r::opt::detail::AlgBurteForce::run(), and Slic3r::opt::detail::NLoptOpt< M, class >::set_up().
rel_score_diff() [1/2]
double Slic3r::opt::StopCriteria::rel_score_diff () const inline
{ return m_rel_score_diff; }
References m_rel_score_diff.
rel_score_diff() [2/2]
StopCriteria & Slic3r::opt::StopCriteria::rel_score_diff (double val) inline
    {
        m_rel_score_diff = val; return *this;
    }
References m_rel_score_diff.
Referenced by Slic3r::sla::get_criteria(), Slic3r::opt::detail::AlgBurteForce::run(), and Slic3r::opt::detail::NLoptOpt< M, class >::set_up().
stop_condition() [1/2]
bool Slic3r::opt::StopCriteria::stop_condition () inline
{ return m_stop_condition(); }
References m_stop_condition.
stop_condition() [2/2]
template<class Fn > StopCriteria & Slic3r::opt::StopCriteria::stop_condition (Fn && cond) inline
    {
        m_stop_condition = cond; return *this;
    }
References m_stop_condition.
Referenced by Slic3r::sla::find_best_misalignment_rotation(), Slic3r::sla::find_least_supports_rotation(), and Slic3r::opt::detail::AlgBurteForce::run().
stop_score() [1/2]
double Slic3r::opt::StopCriteria::stop_score () const inline
{ return m_stop_score; }
References m_stop_score.
stop_score() [2/2]
StopCriteria & Slic3r::opt::StopCriteria::stop_score (double val) inline
    {
        m_stop_score = val; return *this;
    }
References m_stop_score.
Referenced by Slic3r::sla::optimize_anchor_placement(), Slic3r::sla::optimize_pinhead_placement(), Slic3r::sla::search_ground_route(), Slic3r::sla::search_widening_path(), and Slic3r::opt::detail::NLoptOpt< M, class >::set_up().
Member Data Documentation
m_abs_score_diff
double Slic3r::opt::StopCriteria::m_abs_score_diff = NaNd private
Referenced by abs_score_diff(), and abs_score_diff().
m_max_iterations
unsigned Slic3r::opt::StopCriteria::m_max_iterations = 0 private
Referenced by max_iterations(), and max_iterations().
m_rel_score_diff
double Slic3r::opt::StopCriteria::m_rel_score_diff = NaNd private
Referenced by rel_score_diff(), and rel_score_diff().
m_stop_condition
std::function<bool()> Slic3r::opt::StopCriteria::m_stop_condition = [] { return false; } private
Referenced by stop_condition(), and stop_condition().
m_stop_score
double Slic3r::opt::StopCriteria::m_stop_score = NaNd private
Referenced by stop_score(), and stop_score().
The documentation for this class was generated from the following file:
src/libslic3r/Optimize/Optimizer.hpp