Prusa Slicer: Slic3r::sla::EncodedRaster Class Reference
Slic3r::sla::EncodedRaster Class Reference
#include <src/libslic3r/SLA/RasterBase.hpp>
Public Member Functions
EncodedRaster ()=default
EncodedRaster (std::vector< uint8_t > &&buf, std::string ext)
size_t size () const
const void * data () const
const char * extension () const
Protected Attributes
std::vector< uint8_t > m_buffer
std::string m_ext
Detailed Description
Constructor & Destructor Documentation
EncodedRaster() [1/2]
Slic3r::sla::EncodedRaster::EncodedRaster () default
EncodedRaster() [2/2]
Slic3r::sla::EncodedRaster::EncodedRaster (std::vector< uint8_t > && buf, std::string ext) inline explicit
        : m_buffer(std::move(buf)), m_ext(std::move(ext))
    {}
Member Function Documentation
data()
const void * Slic3r::sla::EncodedRaster::data () const inline
{ return m_buffer.data(); }
References m_buffer.
Referenced by Slic3r::sla::operator<<().
extension()
const char * Slic3r::sla::EncodedRaster::extension () const inline
{ return m_ext.c_str(); }
References m_ext.
size()
size_t Slic3r::sla::EncodedRaster::size () const inline
{ return m_buffer.size(); }
References m_buffer.
Referenced by Slic3r::sla::PPMRasterEncoder::operator()(), and Slic3r::sla::operator<<().
Member Data Documentation
m_buffer
std::vector<uint8_t> Slic3r::sla::EncodedRaster::m_buffer protected
Referenced by data(), and size().
m_ext
std::string Slic3r::sla::EncodedRaster::m_ext protected
Referenced by extension().
The documentation for this class was generated from the following file:
src/libslic3r/SLA/RasterBase.hpp