Prusa Slicer: Slic3r::ProcessLayer Namespace Reference
Slic3r::ProcessLayer Namespace Reference
Functions
static std::string emit_custom_gcode_per_print_z (GCode &gcodegen, const CustomGCode::Item *custom_gcode, unsigned int current_extruder_id, unsigned int first_extruder_id, const PrintConfig &config)
Function Documentation
emit_custom_gcode_per_print_z()
static std::string Slic3r::ProcessLayer::emit_custom_gcode_per_print_z (GCode & gcodegen, const CustomGCode::Item * custom_gcode, unsigned int current_extruder_id, unsigned int first_extruder_id, const PrintConfig & config) static
FIXME_in_fw show message during print pause
FIXME_in_fw show message during print pause
    {
        std::string gcode;
        bool single_extruder_printer = config.nozzle_diameter.size() == 1;
        if (custom_gcode != nullptr) {
            // Extruder switches are processed by LayerTools, they should be filtered out.
            assert(custom_gcode->type != CustomGCode::ToolChange);
            CustomGCode::Type   gcode_type   = custom_gcode->type;
            bool          color_change = gcode_type == CustomGCode::ColorChange;
            bool        tool_change  = gcode_type == CustomGCode::ToolChange;
            // Tool Change is applied as Color Change for a single extruder printer only.
            assert(! tool_change || single_extruder_printer);
            std::string pause_print_msg;
            int m600_extruder_before_layer = -1;
            if (color_change && custom_gcode->extruder > 0)
                m600_extruder_before_layer = custom_gcode->extruder - 1;
            else if (gcode_type == CustomGCode::PausePrint)
                pause_print_msg = custom_gcode->extra;
            // we should add or not colorprint_change in respect to nozzle_diameter count instead of really used extruders count
            if (color_change || tool_change)
            {
                assert(m600_extruder_before_layer >= 0);
            // Color Change or Tool Change as Color Change.
                // add tag for processor
                gcode += ";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Color_Change) + ",T" + std::to_string(m600_extruder_before_layer) + "," + custom_gcode->color + "\n";
                if (!single_extruder_printer && m600_extruder_before_layer >= 0 && first_extruder_id != (unsigned)m600_extruder_before_layer
                    // && !MMU1
                    ) {
                    // FIXME: Why is pause_print_gcode here? Why is it supplied "color_change_extruder"? Why is that not
                    //        passed to color_change_gcode below?
                    DynamicConfig cfg;
                    cfg.set_key_value("color_change_extruder", new ConfigOptionInt(m600_extruder_before_layer));
                    gcode += gcodegen.placeholder_parser_process("pause_print_gcode", config.pause_print_gcode, current_extruder_id, &cfg);
                    gcode += "\n";
                    gcode += "M117 Change filament for Extruder " + std::to_string(m600_extruder_before_layer) + "\n";
                }
                else {
                    gcode += gcodegen.placeholder_parser_process("color_change_gcode", config.color_change_gcode, current_extruder_id);
                    gcode += "\n";
                    //FIXME Tell G-code writer that M600 filled the extruder, thus the G-code writer shall reset the extruder to unretracted state after
                    // return from M600. Thus the G-code generated by the following line is ignored.
                    // see GH issue #6362
                    gcodegen.writer().unretract();
                }
          }
          else {
              if (gcode_type == CustomGCode::PausePrint) // Pause print
              {
                    // add tag for processor
                    gcode += ";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Pause_Print) + "\n";
                  if (!pause_print_msg.empty())
                      gcode += "M117 " + pause_print_msg + "\n";
                    gcode += gcodegen.placeholder_parser_process("pause_print_gcode", config.pause_print_gcode, current_extruder_id);
                }
              else {
                    // add tag for processor
                    gcode += ";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Custom_Code) + "\n";
                    if (gcode_type == CustomGCode::Template)    // Template Custom Gcode
                        gcode += gcodegen.placeholder_parser_process("template_custom_gcode", config.template_custom_gcode, current_extruder_id);
                    else                                        // custom Gcode
                        gcode += custom_gcode->extra;
                }
                gcode += "\n";
            }
        }
        return gcode;
    }
References Slic3r::CustomGCode::Item::color, Slic3r::GCodeProcessor::Color_Change, Slic3r::CustomGCode::ColorChange, Slic3r::GCodeProcessor::Custom_Code, Slic3r::CustomGCode::Item::extra, Slic3r::CustomGCode::Item::extruder, Slic3r::GCodeProcessor::Pause_Print, Slic3r::CustomGCode::PausePrint, Slic3r::GCode::placeholder_parser_process(), Slic3r::GCodeProcessor::reserved_tag(), Slic3r::DynamicConfig::set_key_value(), Slic3r::CustomGCode::Template, Slic3r::CustomGCode::ToolChange, Slic3r::CustomGCode::Item::type, Slic3r::GCodeWriter::unretract(), and Slic3r::GCode::writer().
Referenced by Slic3r::GCode::process_layer().