Prusa Slicer: Slic3r::MinDistanceVisitor Struct Reference
Slic3r::MinDistanceVisitor Struct Reference
Public Member Functions
MinDistanceVisitor (const EdgeGrid::Grid &grid, const Point &center, double max_distance_squared)
void init ()
bool operator() (coord_t iy, coord_t ix)
Public Attributes
const EdgeGrid::Grid & grid
const Slic3r::Point center
std::vector< ClosestLine > closest_lines
std::unordered_set< std::pair< size_t, size_t >, boost::hash< std::pair< size_t, size_t > > > closest_lines_set
double max_distance_squared = std::numeric_limits<double>::max()
Detailed Description
Constructor & Destructor Documentation
MinDistanceVisitor()
Slic3r::MinDistanceVisitor::MinDistanceVisitor (const EdgeGrid::Grid & grid, const Point & center, double max_distance_squared) inline explicit
        : grid(grid), center(center), max_distance_squared(max_distance_squared)
    {}
Member Function Documentation
init()
void Slic3r::MinDistanceVisitor::init () inline
    {
        this->closest_lines.clear();
        this->closest_lines_set.clear();
    }
References closest_lines, and closest_lines_set.
operator()()
bool Slic3r::MinDistanceVisitor::operator() (coord_t iy, coord_t ix) inline
    {
        // Called with a row and column of the grid cell, which is inside a bounding box.
        auto cell_data_range = grid.cell_data_range(iy, ix);
        for (auto it_contour_and_segment = cell_data_range.first; it_contour_and_segment != cell_data_range.second; ++it_contour_and_segment) {
            // End points of the line segment and their vector.
            auto  segment = grid.segment(*it_contour_and_segment);
            Point closest_point;
            if (closest_lines_set.find(*it_contour_and_segment) == closest_lines_set.end() &&
                line_alg::distance_to_squared(Line(segment.first, segment.second), center, &closest_point) <= this->max_distance_squared) {
                closest_lines.push_back({it_contour_and_segment->first, it_contour_and_segment->second, closest_point});
                closest_lines_set.insert(*it_contour_and_segment);
            }
        }
        // Continue traversing the grid along the edge.
        return true;
    }
References Slic3r::EdgeGrid::Grid::cell_data_range(), center, closest_lines, closest_lines_set, Slic3r::line_alg::distance_to_squared(), grid, max_distance_squared, Slic3r::EdgeGrid::Grid::segment(), and segment().
Member Data Documentation
center
const Slic3r::Point Slic3r::MinDistanceVisitor::center
Referenced by operator()().
closest_lines
std::vector<ClosestLine> Slic3r::MinDistanceVisitor::closest_lines
Referenced by Slic3r::get_closest_lines_in_radius(), init(), and operator()().
closest_lines_set
std::unordered_set<std::pair<size_t, size_t>, boost::hash<std::pair<size_t, size_t> > > Slic3r::MinDistanceVisitor::closest_lines_set
Referenced by init(), and operator()().
grid
const EdgeGrid::Grid& Slic3r::MinDistanceVisitor::grid
Referenced by operator()().
max_distance_squared
double Slic3r::MinDistanceVisitor::max_distance_squared = std::numeric_limits<double>::max()
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/libslic3r/GCode/AvoidCrossingPerimeters.cpp