Prusa Slicer: Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape > Struct Template Reference
Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape > Struct Template Reference
#include <src/eigen/Eigen/src/SparseCore/SparsePermutation.h>
Public Types
enum { SrcStorageOrder = MatrixTypeCleaned::Flags&RowMajorBit ? RowMajor : ColMajor , MoveOuter = SrcStorageOrder==RowMajor ? Side==OnTheLeft : Side==OnTheRight }
typedef nested_eval< ExpressionType, 1 >::type MatrixType
typedef remove_all< MatrixType >::type MatrixTypeCleaned
typedef MatrixTypeCleaned::Scalar Scalar
typedef MatrixTypeCleaned::StorageIndex StorageIndex
typedef internal::conditional< MoveOuter, SparseMatrix< Scalar, SrcStorageOrder, StorageIndex >, SparseMatrix< Scalar, int(SrcStorageOrder)==RowMajor?ColMajor:RowMajor, StorageIndex > >::type ReturnType
Static Public Member Functions
template<typename Dest , typename PermutationType >
static void run (Dest &dst, const PermutationType &perm, const ExpressionType &xpr)
Detailed Description
template<typename ExpressionType, int Side, bool Transposed>
struct Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >
Member Typedef Documentation
MatrixType
template<typename ExpressionType , int Side, bool Transposed> typedef nested_eval<ExpressionType,1>::type Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::MatrixType
MatrixTypeCleaned
template<typename ExpressionType , int Side, bool Transposed> typedef remove_all<MatrixType>::type Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::MatrixTypeCleaned
ReturnType
template<typename ExpressionType , int Side, bool Transposed> typedef internal::conditional<MoveOuter,SparseMatrix<Scalar,SrcStorageOrder,StorageIndex>,SparseMatrix<Scalar,int(SrcStorageOrder)==RowMajor?ColMajor:RowMajor,StorageIndex>>::type Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::ReturnType
Scalar
template<typename ExpressionType , int Side, bool Transposed> typedef MatrixTypeCleaned::Scalar Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::Scalar
StorageIndex
template<typename ExpressionType , int Side, bool Transposed> typedef MatrixTypeCleaned::StorageIndex Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename ExpressionType , int Side, bool Transposed> anonymous enum
Enumerator
SrcStorageOrder
MoveOuter
         {
      SrcStorageOrder = MatrixTypeCleaned::Flags&RowMajorBit ? RowMajor : ColMajor,
      MoveOuter = SrcStorageOrder==RowMajor ? Side==OnTheLeft : Side==OnTheRight
    };
Member Function Documentation
run()
template<typename ExpressionType , int Side, bool Transposed> template<typename Dest , typename PermutationType > static void Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run (Dest & dst, const PermutationType & perm, const ExpressionType & xpr) inline static
    {
      MatrixType mat(xpr);
      if(MoveOuter)
      {
        SparseMatrix<Scalar,SrcStorageOrder,StorageIndex> tmp(mat.rows(), mat.cols());
        Matrix<StorageIndex,Dynamic,1> sizes(mat.outerSize());
        for(Index j=0; j<mat.outerSize(); ++j)
        {
          Index jp = perm.indices().coeff(j);
          sizes[((Side==OnTheLeft) ^ Transposed) ? jp : j] = StorageIndex(mat.innerVector(((Side==OnTheRight) ^ Transposed) ? jp : j).nonZeros());
        }
        tmp.reserve(sizes);
        for(Index j=0; j<mat.outerSize(); ++j)
        {
          Index jp = perm.indices().coeff(j);
          Index jsrc = ((Side==OnTheRight) ^ Transposed) ? jp : j;
          Index jdst = ((Side==OnTheLeft) ^ Transposed) ? jp : j;
          for(typename MatrixTypeCleaned::InnerIterator it(mat,jsrc); it; ++it)
            tmp.insertByOuterInner(jdst,it.index()) = it.value();
        }
        dst = tmp;
      }
      else
      {
        SparseMatrix<Scalar,int(SrcStorageOrder)==RowMajor?ColMajor:RowMajor,StorageIndex> tmp(mat.rows(), mat.cols());
        Matrix<StorageIndex,Dynamic,1> sizes(tmp.outerSize());
        sizes.setZero();
        PermutationMatrix<Dynamic,Dynamic,StorageIndex> perm_cpy;
        if((Side==OnTheLeft) ^ Transposed)
          perm_cpy = perm;
        else
          perm_cpy = perm.transpose();
        for(Index j=0; j<mat.outerSize(); ++j)
          for(typename MatrixTypeCleaned::InnerIterator it(mat,j); it; ++it)
            sizes[perm_cpy.indices().coeff(it.index())]++;
        tmp.reserve(sizes);
        for(Index j=0; j<mat.outerSize(); ++j)
          for(typename MatrixTypeCleaned::InnerIterator it(mat,j); it; ++it)
            tmp.insertByOuterInner(perm_cpy.indices().coeff(it.index()),j) = it.value();
        dst = tmp;
      }
    }
References Eigen::ColMajor, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::indices(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertByOuterInner(), Eigen::OnTheLeft, Eigen::OnTheRight, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserve(), Eigen::RowMajor, Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::PermutationBase< Derived >::transpose().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparsePermutation.h