Prusa Slicer: Slic3r::GUI::SceneRaycaster::HitResult Struct Reference
Slic3r::GUI::SceneRaycaster::HitResult Struct Reference
#include <src/slic3r/GUI/SceneRaycaster.hpp>
Public Member Functions
bool is_valid () const
Public Attributes
EType type { EType::None }
int raycaster_id { -1 }
Vec3f position { Vec3f::Zero() }
Vec3f normal { Vec3f::Zero() }
Detailed Description
Member Function Documentation
is_valid()
bool Slic3r::GUI::SceneRaycaster::HitResult::is_valid () const inline
{ return raycaster_id != -1; }
References raycaster_id.
Referenced by Slic3r::GUI::GLCanvas3D::_mouse_to_3d(), Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::SceneRaycaster::hit().
Member Data Documentation
normal
Vec3f Slic3r::GUI::SceneRaycaster::HitResult::normal { Vec3f::Zero() }
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass().
position
Vec3f Slic3r::GUI::SceneRaycaster::HitResult::position { Vec3f::Zero() }
Referenced by Slic3r::GUI::GLCanvas3D::_mouse_to_3d(), Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::SceneRaycaster::hit().
raycaster_id
int Slic3r::GUI::SceneRaycaster::HitResult::raycaster_id { -1 }
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::SceneRaycaster::hit(), and is_valid().
type
EType Slic3r::GUI::SceneRaycaster::HitResult::type { EType::None }
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::SceneRaycaster::hit().
The documentation for this struct was generated from the following file:
src/slic3r/GUI/SceneRaycaster.hpp