Prusa Slicer: Slic3r::GUI::DiffPresetDialog Class Reference
Slic3r::GUI::DiffPresetDialog Class Reference
#include <src/slic3r/GUI/UnsavedChangesDialog.hpp>
Classes
struct DiffPresets
struct PresetToSave
Public Member Functions
DiffPresetDialog (MainFrame *mainframe)
~DiffPresetDialog () override=default
void show (Preset::Type type=Preset::TYPE_INVALID)
void update_presets (Preset::Type type=Preset::TYPE_INVALID, bool update_preset_bundles_from_app=true)
Preset::Type view_type () const
PrinterTechnology printer_technology () const
std::string get_left_preset_name (Preset::Type type)
std::string get_right_preset_name (Preset::Type type)
std::vector< std::string > get_selected_options (Preset::Type type) const
std::array< Preset::Type, 3 > types_list () const
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
Protected Member Functions
void on_dpi_changed (const wxRect &suggested_rect) override
void on_sys_color_changed () override
Private Member Functions
void create_buttons ()
void create_edit_sizer ()
void complete_dialog_creation ()
void create_presets_sizer ()
void create_info_lines ()
void create_tree ()
void create_show_all_presets_chb ()
void update_bottom_info (wxString bottom_info="")
void update_tree ()
void update_bundles_from_app ()
void update_controls_visibility (Preset::Type type=Preset::TYPE_INVALID)
void update_compatibility (const std::string &preset_name, Preset::Type type, PresetBundle *preset_bundle)
std::vector< std::string > get_options_to_save (Preset::Type type)
void button_event (Action act)
bool is_save_confirmed ()
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
DiffViewCtrl * m_tree { nullptr }
wxBoxSizer * m_presets_sizer { nullptr }
wxStaticText * m_top_info_line { nullptr }
wxStaticText * m_bottom_info_line { nullptr }
wxCheckBox * m_show_all_presets { nullptr }
wxCheckBox * m_use_for_transfer { nullptr }
ScalableButton * m_transfer_btn { nullptr }
ScalableButton * m_save_btn { nullptr }
ScalableButton * m_cancel_btn { nullptr }
wxBoxSizer * m_buttons { nullptr }
wxBoxSizer * m_edit_sizer { nullptr }
Preset::Type m_view_type { Preset::TYPE_INVALID }
PrinterTechnology m_pr_technology
std::unique_ptr< PresetBundle > m_preset_bundle_left
std::unique_ptr< PresetBundle > m_preset_bundle_right
std::vector< DiffPresets > m_preset_combos
std::vector< PresetToSave > presets_to_save
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Class Documentation
Slic3r::GUI::DiffPresetDialog::DiffPresets
struct Slic3r::GUI::DiffPresetDialog::DiffPresets
Class Members
ScalableButton * equal_bmp { nullptr }
PresetComboBox * presets_left { nullptr }
PresetComboBox * presets_right { nullptr }
Slic3r::GUI::DiffPresetDialog::PresetToSave
struct Slic3r::GUI::DiffPresetDialog::PresetToSave
Class Members
string from_name
string new_name
string to_name
Type type
Constructor & Destructor Documentation
DiffPresetDialog()
Slic3r::GUI::DiffPresetDialog::DiffPresetDialog (MainFrame * mainframe)
    : DPIDialog(mainframe, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER),
    m_pr_technology(wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology())
{
#if defined(__WXMSW__)
    // ys_FIXME! temporary workaround for correct font scaling
    // Because of from wxWidgets 3.1.3 auto rescaling is implemented for the Fonts,
    // From the very beginning set dialog font to the wxSYS_DEFAULT_GUI_FONT
//    this->SetFont(wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT));
    this->SetFont(mainframe->normal_font());
#endif // __WXMSW__
    // Init bundles
    assert(wxGetApp().preset_bundle);
    m_preset_bundle_left  = std::make_unique<PresetBundle>(*wxGetApp().preset_bundle);
    m_preset_bundle_right = std::make_unique<PresetBundle>(*wxGetApp().preset_bundle);
    // Create UI items
    create_info_lines();
    create_presets_sizer();
    create_show_all_presets_chb();
    create_tree();
    create_edit_sizer();
    complete_dialog_creation();
}
References complete_dialog_creation(), create_edit_sizer(), create_info_lines(), create_presets_sizer(), create_show_all_presets_chb(), create_tree(), m_preset_bundle_left, m_preset_bundle_right, and Slic3r::GUI::DPIAware< P >::normal_font().
~DiffPresetDialog()
Slic3r::GUI::DiffPresetDialog::~DiffPresetDialog () override default
Member Function Documentation
button_event()
void Slic3r::GUI::DiffPresetDialog::button_event (Action act) private
{
    if (act == Action::Save) {
        if (is_save_confirmed()) {
            size_t saved_cnt = 0;
            for (const auto& preset : presets_to_save)
                if (wxGetApp().preset_bundle->transfer_and_save(preset.type, preset.from_name, preset.to_name, preset.new_name, get_options_to_save(preset.type)))
                    saved_cnt++;
            if (saved_cnt > 0) {
                MessageDialog(this, UnsavedChangesDialog::msg_success_saved_modifications(saved_cnt)).ShowModal();
                update_bundles_from_app();
                for (const auto& preset : presets_to_save) {
                    m_preset_bundle_left->get_presets(preset.type).select_preset_by_name(preset.from_name, true);
                    m_preset_bundle_right->get_presets(preset.type).select_preset_by_name(preset.new_name, true);
                }
                update_presets(m_view_type, false);
            }
        }
    }
    else {
        Hide();
        if (act == Action::Transfer)
            wxPostEvent(this, SimpleEvent(EVT_DIFF_DIALOG_TRANSFER));
        else if (!presets_to_save.empty())
            wxPostEvent(this, SimpleEvent(EVT_DIFF_DIALOG_UPDATE_PRESETS));
    }
}
References get_options_to_save(), is_save_confirmed(), m_preset_bundle_left, m_preset_bundle_right, m_view_type, Slic3r::GUI::UnsavedChangesDialog::msg_success_saved_modifications(), presets_to_save, Slic3r::GUI::Save, Slic3r::GUI::Transfer, update_bundles_from_app(), and update_presets().
Referenced by create_buttons().
complete_dialog_creation()
void Slic3r::GUI::DiffPresetDialog::complete_dialog_creation () private
{
    wxBoxSizer*topSizer = new wxBoxSizer(wxVERTICAL);
    int border = 10;
    topSizer->Add(m_top_info_line,      0, wxEXPAND | wxLEFT | wxTOP | wxRIGHT, 2 * border);
    topSizer->Add(m_presets_sizer,      0, wxEXPAND | wxLEFT | wxTOP | wxRIGHT, border);
    topSizer->Add(m_show_all_presets,   0, wxEXPAND | wxALL, border);
    topSizer->Add(m_tree,               1, wxEXPAND | wxALL, border);
    topSizer->Add(m_bottom_info_line,   0, wxEXPAND | wxALL, 2 * border);
    topSizer->Add(m_edit_sizer,         0, wxEXPAND | wxLEFT | wxBOTTOM | wxRIGHT, 2 * border);
    this->SetMinSize(wxSize(80 * em_unit(), 30 * em_unit()));
    this->SetSizer(topSizer);
    topSizer->SetSizeHints(this);
}
References Slic3r::GUI::DPIAware< P >::em_unit(), m_bottom_info_line, m_edit_sizer, m_presets_sizer, m_show_all_presets, m_top_info_line, and m_tree.
Referenced by DiffPresetDialog().
create_buttons()
void Slic3r::GUI::DiffPresetDialog::create_buttons () private
{
    wxFont font = this->GetFont().Scaled(1.4f);
    m_buttons   = new wxBoxSizer(wxHORIZONTAL);
    auto show_in_bottom_info = [this](const wxString& ext_line, wxMouseEvent& e) {
        m_bottom_info_line->SetLabel(ext_line);
        m_bottom_info_line->Show(true);
        Layout();
        e.Skip();
    };
    // Transfer
    m_transfer_btn = new ScalableButton(this, wxID_ANY, "paste_menu", _L("Transfer"), wxDefaultSize, wxDefaultPosition, wxBORDER_DEFAULT, 24);
    m_transfer_btn->Bind(wxEVT_BUTTON, [this](wxEvent&) { button_event(Action::Transfer);});
    auto enable_transfer = [this](const Preset::Type& type) {
        const Preset& main_edited_preset = get_preset_collection(type, wxGetApp().preset_bundle)->get_edited_preset();
        if (main_edited_preset.is_dirty)
            return main_edited_preset.name == get_right_preset_name(type);
        return true;
    };
    m_transfer_btn->Bind(wxEVT_UPDATE_UI, [this, enable_transfer](wxUpdateUIEvent& evt) {
        bool enable = m_tree->has_selection();
        if (enable) {
            if (m_view_type == Preset::TYPE_INVALID) {
                for (const Preset::Type& type : types_list())
                    if (!enable_transfer(type)) {
                        enable = false;
                        break;
                    }
            }
            else
                enable = enable_transfer(m_view_type);
        }
        evt.Enable(enable);
    });
    m_transfer_btn->Bind(wxEVT_ENTER_WINDOW, [show_in_bottom_info](wxMouseEvent& e) {
        show_in_bottom_info(_L("Transfer the selected options from left preset to the right.\n"
                            "Note: New modified presets will be selected in settings tabs after close this dialog."), e); });
    // Save
    m_save_btn = new ScalableButton(this, wxID_ANY, "save", _L("Save"), wxDefaultSize, wxDefaultPosition, wxBORDER_DEFAULT, 24);
    m_save_btn->Bind(wxEVT_BUTTON, [this](wxEvent&) { button_event(Action::Save); });
    m_save_btn->Bind(wxEVT_UPDATE_UI, [this](wxUpdateUIEvent& evt) { evt.Enable(m_tree->has_selection()); });
    m_save_btn->Bind(wxEVT_ENTER_WINDOW, [show_in_bottom_info](wxMouseEvent& e) {
        show_in_bottom_info(_L("Save the selected options from left preset to the right."), e); });
    // Cancel
    m_cancel_btn = new ScalableButton(this, wxID_CANCEL, "cross", _L("Cancel"), wxDefaultSize, wxDefaultPosition, wxBORDER_DEFAULT, 24);
    m_cancel_btn->Bind(wxEVT_BUTTON, [this](wxEvent&) { button_event(Action::Discard);});
    for (ScalableButton* btn : { m_transfer_btn, m_save_btn, m_cancel_btn }) {
        btn->Bind(wxEVT_LEAVE_WINDOW, [this](wxMouseEvent& e) { update_bottom_info(); Layout(); e.Skip(); });
        m_buttons->Add(btn, 1, wxLEFT, 5);
        btn->SetFont(font);
    }
    m_buttons->Show(false);
}
References _L, button_event(), Slic3r::GUI::Discard, Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::get_preset_collection(), get_right_preset_name(), Slic3r::GUI::DiffViewCtrl::has_selection(), Slic3r::Preset::is_dirty, m_bottom_info_line, m_buttons, m_cancel_btn, m_save_btn, m_transfer_btn, m_tree, m_view_type, Slic3r::Preset::name, Slic3r::GUI::Save, Slic3r::GUI::Transfer, Slic3r::Preset::TYPE_INVALID, types_list(), update_bottom_info(), and wxEVT_BUTTON.
Referenced by create_edit_sizer().
create_edit_sizer()
void Slic3r::GUI::DiffPresetDialog::create_edit_sizer () private
{
    // Add check box for the edit mode
    m_use_for_transfer = new wxCheckBox(this, wxID_ANY, _L("Transfer values from left to right"));
    m_use_for_transfer->SetToolTip(_L("If enabled, this dialog can be used for transver selected values from left to right preset."));
    m_use_for_transfer->Bind(wxEVT_CHECKBOX, [this](wxCommandEvent&) {
        bool use = m_use_for_transfer->GetValue();
        m_tree->GetColumn(DiffModel::colToggle)->SetHidden(!use);
        if (m_tree->IsShown()) {
            m_buttons->Show(use);
            Fit();
            Refresh();
        }
        else
            this->Layout();
    });
    // Add Buttons
    create_buttons();
    // Create and fill edit sizer
    m_edit_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_edit_sizer->Add(m_use_for_transfer, 0, wxALIGN_CENTER_VERTICAL | wxLEFT | wxRIGHT, 5);
    m_edit_sizer->AddSpacer(em_unit() * 10);
    m_edit_sizer->Add(m_buttons, 1, wxLEFT, 5);
    m_edit_sizer->Show(false);
}
References _L, Slic3r::GUI::DiffModel::colToggle, create_buttons(), Slic3r::GUI::DPIAware< P >::em_unit(), m_buttons, m_edit_sizer, m_tree, and m_use_for_transfer.
Referenced by DiffPresetDialog().
create_info_lines()
void Slic3r::GUI::DiffPresetDialog::create_info_lines () private
{
//    const wxFont font = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT).Bold();
    const wxFont font = GetFont().Bold();
    m_top_info_line = new wxStaticText(this, wxID_ANY, _L("Select presets to compare"));
    m_top_info_line->SetFont(font);
    m_bottom_info_line = new wxStaticText(this, wxID_ANY, "");
    m_bottom_info_line->SetFont(font);
}
References _L, m_bottom_info_line, and m_top_info_line.
Referenced by DiffPresetDialog().
create_presets_sizer()
void Slic3r::GUI::DiffPresetDialog::create_presets_sizer () private
{
    m_presets_sizer = new wxBoxSizer(wxVERTICAL);
    for (auto new_type : { Preset::TYPE_PRINT, Preset::TYPE_SLA_PRINT, Preset::TYPE_FILAMENT, Preset::TYPE_SLA_MATERIAL, Preset::TYPE_PRINTER })
    {
        const PresetCollection* collection = get_preset_collection(new_type);
        wxBoxSizer* sizer = new wxBoxSizer(wxHORIZONTAL);
        PresetComboBox* presets_left;
        PresetComboBox* presets_right;
        ScalableButton* equal_bmp = new ScalableButton(this, wxID_ANY, "equal");
        auto add_preset_combobox = [collection, sizer, new_type, this](PresetComboBox** cb_, PresetBundle* preset_bundle) {
            *cb_ = new PresetComboBox(this, new_type, wxSize(em_unit() * 35, -1), preset_bundle);
            PresetComboBox*cb = (*cb_);
            cb->show_modif_preset_separately();
            cb->set_selection_changed_function([this, new_type, preset_bundle, cb](int selection) {
                std::string preset_name = Preset::remove_suffix_modified(cb->GetString(selection).ToUTF8().data());
                if (m_view_type == Preset::TYPE_INVALID)
                    update_compatibility(preset_name, new_type, preset_bundle);
                // update selection inside of related presets
                preset_bundle->get_presets(new_type).select_preset_by_name(preset_name, true);
                update_tree();
            });
            if (collection->get_selected_idx() != (size_t)-1)
                cb->update(collection->get_selected_preset().name);
            sizer->Add(cb, 1);
            cb->Show(new_type == Preset::TYPE_PRINTER);
        };
        add_preset_combobox(&presets_left, m_preset_bundle_left.get());
        sizer->Add(equal_bmp, 0, wxRIGHT | wxLEFT | wxALIGN_CENTER_VERTICAL, 5);
        add_preset_combobox(&presets_right, m_preset_bundle_right.get());
        m_presets_sizer->Add(sizer, 1, wxTOP, 5);
        equal_bmp->Show(new_type == Preset::TYPE_PRINTER);
        m_preset_combos.push_back({ presets_left, equal_bmp, presets_right });
        equal_bmp->Bind(wxEVT_BUTTON, [presets_left, presets_right, this](wxEvent&) {
            std::string preset_name = get_selection(presets_left);
            presets_right->update(preset_name);
            if (m_view_type == Preset::TYPE_INVALID)
                update_compatibility(preset_name, presets_right->get_type(), m_preset_bundle_right.get());
            update_tree();
        });
    }
}
References Slic3r::GUI::DPIAware< P >::em_unit(), Slic3r::GUI::get_preset_collection(), Slic3r::PresetCollection::get_selected_idx(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::GUI::get_selection(), Slic3r::GUI::PresetComboBox::get_type(), m_preset_bundle_left, m_preset_bundle_right, m_preset_combos, m_presets_sizer, m_view_type, Slic3r::Preset::name, Slic3r::Preset::remove_suffix_modified(), Slic3r::GUI::PresetComboBox::set_selection_changed_function(), Slic3r::GUI::PresetComboBox::show_modif_preset_separately(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_INVALID, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::Preset::TYPE_SLA_PRINT, Slic3r::GUI::PresetComboBox::update(), update_compatibility(), update_tree(), and wxEVT_BUTTON.
Referenced by DiffPresetDialog().
create_show_all_presets_chb()
void Slic3r::GUI::DiffPresetDialog::create_show_all_presets_chb () private
{
    m_show_all_presets = new wxCheckBox(this, wxID_ANY, _L("Show all presets (including incompatible)"));
    m_show_all_presets->Bind(wxEVT_CHECKBOX, [this](wxCommandEvent&) {
        bool show_all = m_show_all_presets->GetValue();
        for (auto preset_combos : m_preset_combos) {
            if (preset_combos.presets_left->get_type() == Preset::TYPE_PRINTER)
                continue;
            preset_combos.presets_left->show_all(show_all);
            preset_combos.presets_right->show_all(show_all);
        }
        if (m_view_type == Preset::TYPE_INVALID)
            update_tree();
    });
}
References _L, m_preset_combos, m_show_all_presets, m_view_type, Slic3r::Preset::TYPE_INVALID, Slic3r::Preset::TYPE_PRINTER, and update_tree().
Referenced by DiffPresetDialog().
create_tree()
void Slic3r::GUI::DiffPresetDialog::create_tree () private
{
    m_tree = new DiffViewCtrl(this, wxSize(em_unit() * 65, em_unit() * 40));
    m_tree->AppendToggleColumn_(L"\u2714", DiffModel::colToggle, wxLinux ? 9 : 6);
    m_tree->AppendBmpTextColumn("",                      DiffModel::colIconText, 35);
    m_tree->AppendBmpTextColumn(_L("Left Preset Value"), DiffModel::colOldValue, 15);
    m_tree->AppendBmpTextColumn(_L("Right Preset Value"),DiffModel::colModValue, 15);
    m_tree->Hide();
    m_tree->GetColumn(DiffModel::colToggle)->SetHidden(true);
}
References _L, Slic3r::GUI::DiffViewCtrl::AppendBmpTextColumn(), Slic3r::GUI::DiffViewCtrl::AppendToggleColumn_(), Slic3r::GUI::DiffModel::colIconText, Slic3r::GUI::DiffModel::colModValue, Slic3r::GUI::DiffModel::colOldValue, Slic3r::GUI::DiffModel::colToggle, Slic3r::GUI::DPIAware< P >::em_unit(), L, m_tree, and wxLinux.
Referenced by DiffPresetDialog().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::FileArchiveDialog::FileArchiveDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::ExtruderSequenceDialog::apply_extruder_sequence(), Slic3r::GUI::UnsavedChangesDialog::build(), complete_dialog_creation(), create_edit_sizer(), create_presets_sizer(), create_tree(), em_unit(), Slic3r::GUI::SavePresetDialog::Item::init_input_name_ctrl(), Slic3r::Search::SearchDialog::msw_rescale(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigSnapshotDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::FileArchiveDialog::on_dpi_changed(), Slic3r::FirmwareDialog::on_dpi_changed(), Slic3r::GUI::GalleryDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::LoadProjectsDialog::on_dpi_changed(), Slic3r::GUI::ProjectDropDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
Referenced by Slic3r::GUI::MainFrame::update_layout().
get_left_preset_name()
std::string Slic3r::GUI::DiffPresetDialog::get_left_preset_name (Preset::Type type)
{
    PresetComboBox* cb = m_preset_combos[int(type - Preset::TYPE_PRINT)].presets_left;
    return Preset::remove_suffix_modified(get_selection(cb));
}
References Slic3r::GUI::get_selection(), m_preset_combos, Slic3r::Preset::remove_suffix_modified(), and Slic3r::Preset::TYPE_PRINT.
Referenced by Slic3r::GUI::MainFrame::bind_diff_dialog(), is_save_confirmed(), and update_tree().
get_options_to_save()
std::vector< std::string > Slic3r::GUI::DiffPresetDialog::get_options_to_save (Preset::Type type) private
{
    auto options = m_tree->options(type, true);
    // erase "inherits" option from the list if it exists there
    if (const auto it = std::find(options.begin(), options.end(), "inherits"); it != options.end())
        options.erase(it);
    if (type == Preset::TYPE_PRINTER) {
        // erase "extruders_count" option from the list if it exists there
        if (const auto it = std::find(options.begin(), options.end(), "extruders_count"); it != options.end())
            options.erase(it);
    }
    return options;
}
References m_tree, Slic3r::GUI::DiffViewCtrl::options(), and Slic3r::Preset::TYPE_PRINTER.
Referenced by button_event().
get_right_preset_name()
std::string Slic3r::GUI::DiffPresetDialog::get_right_preset_name (Preset::Type type)
{
    PresetComboBox* cb = m_preset_combos[int(type - Preset::TYPE_PRINT)].presets_right;
    return Preset::remove_suffix_modified(get_selection(cb));
}
References Slic3r::GUI::get_selection(), m_preset_combos, Slic3r::Preset::remove_suffix_modified(), and Slic3r::Preset::TYPE_PRINT.
Referenced by Slic3r::GUI::MainFrame::bind_diff_dialog(), create_buttons(), is_save_confirmed(), and update_tree().
get_selected_options()
std::vector< std::string > Slic3r::GUI::DiffPresetDialog::get_selected_options (Preset::Type type) const inline
{ return m_tree->options(type, true); }
References m_tree, and Slic3r::GUI::DiffViewCtrl::options().
Referenced by Slic3r::GUI::MainFrame::bind_diff_dialog().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
is_save_confirmed()
bool Slic3r::GUI::DiffPresetDialog::is_save_confirmed () private
{
    presets_to_save.clear();
    std::vector<Preset::Type> types_for_save;
    for (const Preset::Type& type : types_list()) {
        if (!m_tree->options(type, true).empty()) {
            types_for_save.emplace_back(type);
            presets_to_save.emplace_back(PresetToSave{ type, get_left_preset_name(type), get_right_preset_name(type), get_right_preset_name(type) });
        }
    }
    if (!types_for_save.empty()) {
        SavePresetDialog save_dlg(this, types_for_save, _u8L("Modified"), m_preset_bundle_right.get());
        if (save_dlg.ShowModal() != wxID_OK)
            return false;
        for (auto& preset : presets_to_save) {
            const std::string& name = save_dlg.get_name(preset.type);
            if (!name.empty())
                preset.new_name = name;
        }
    }
    return true;
}
References _u8L, get_left_preset_name(), Slic3r::GUI::SavePresetDialog::get_name(), get_right_preset_name(), m_preset_bundle_right, m_tree, Slic3r::GUI::DiffViewCtrl::options(), presets_to_save, and types_list().
Referenced by button_event().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigSnapshotDialog::ConfigSnapshotDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), DiffPresetDialog(), Slic3r::GUI::ExtruderSequenceDialog::ExtruderSequenceDialog(), Slic3r::GUI::GalleryDialog::GalleryDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::LoadProjectsDialog::LoadProjectsDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::MainFrame::init_tabpanel(), Slic3r::GUI::ExtruderSequenceDialog::on_dpi_changed(), Slic3r::GUI::MainFrame::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
on_dpi_changed()
void Slic3r::GUI::DiffPresetDialog::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    int em = em_unit();
    msw_buttons_rescale(this, em, { wxID_CANCEL});
    const wxSize& size = wxSize(80 * em, 30 * em);
    SetMinSize(size);
    auto rescale = [em](PresetComboBox* pcb) {
        pcb->msw_rescale();
        wxSize sz = wxSize(35 * em, -1);
        pcb->SetMinSize(sz);
        pcb->SetSize(sz);
    };
    for (auto preset_combos : m_preset_combos) {
        rescale(preset_combos.presets_left);
        rescale(preset_combos.presets_right);
    }
    m_tree->Rescale(em);
    Fit();
    Refresh();
}
References Slic3r::GUI::DPIAware< P >::em_unit(), m_preset_combos, m_tree, msw_buttons_rescale(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DiffViewCtrl::Rescale().
on_sys_color_changed()
void Slic3r::GUI::DiffPresetDialog::on_sys_color_changed () override protected virtual
Reimplemented from Slic3r::GUI::DPIAware< P >.
{
#ifdef _WIN32
    wxGetApp().UpdateAllStaticTextDarkUI(this);
    wxGetApp().UpdateDarkUI(m_show_all_presets);
    wxGetApp().UpdateDVCDarkUI(m_tree);
#endif
    for (auto preset_combos : m_preset_combos) {
        preset_combos.presets_left->sys_color_changed();
        preset_combos.equal_bmp->sys_color_changed();
        preset_combos.presets_right->sys_color_changed();
    }
    for (ScalableButton* btn : { m_transfer_btn, m_save_btn, m_cancel_btn })
        btn->sys_color_changed();
    // msw_rescale updates just icons, so use it
    m_tree->Rescale();
    Refresh();
}
References m_cancel_btn, m_preset_combos, m_save_btn, m_show_all_presets, m_transfer_btn, m_tree, and Slic3r::GUI::DiffViewCtrl::Rescale().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
printer_technology()
PrinterTechnology Slic3r::GUI::DiffPresetDialog::printer_technology () const inline
{ return m_pr_technology; }
References m_pr_technology.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and on_dpi_changed().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
show()
void Slic3r::GUI::DiffPresetDialog::show (Preset::Type type = Preset::TYPE_INVALID)
{
    this->SetTitle(_L("Compare Presets"));
    m_view_type = type;
    update_bundles_from_app();
    update_controls_visibility(type);
    if (type == Preset::TYPE_INVALID)
        Fit();
    update_tree();
    // if this dialog is shown it have to be Hide and show again to be placed on the very Top of windows
    if (IsShown())
        Hide();
    Show();
}
References _L, m_view_type, Slic3r::Preset::TYPE_INVALID, update_bundles_from_app(), update_controls_visibility(), and update_tree().
Referenced by Slic3r::GUI::MainFrame::init_menubar_as_editor(), and update_controls_visibility().
types_list()
std::array< Preset::Type, 3 > Slic3r::GUI::DiffPresetDialog::types_list () const
{
    return PresetBundle::types_list(m_pr_technology);
}
References m_pr_technology, and Slic3r::PresetBundle::types_list().
Referenced by Slic3r::GUI::MainFrame::bind_diff_dialog(), create_buttons(), and is_save_confirmed().
update_bottom_info()
void Slic3r::GUI::DiffPresetDialog::update_bottom_info (wxString bottom_info = "") private
{
    if (m_tree->has_long_strings())
        bottom_info = _L("Some fields are too long to fit. Right mouse click reveals the full text.");
    const bool show_bottom_info = !m_tree->IsShown() || m_tree->has_long_strings();
    if (show_bottom_info)
        m_bottom_info_line->SetLabel(bottom_info);
    m_bottom_info_line->Show(show_bottom_info);
}
References _L, Slic3r::GUI::DiffViewCtrl::has_long_strings(), m_bottom_info_line, and m_tree.
Referenced by create_buttons(), and update_tree().
update_bundles_from_app()
void Slic3r::GUI::DiffPresetDialog::update_bundles_from_app () private
{
    *m_preset_bundle_left  = *wxGetApp().preset_bundle;
    *m_preset_bundle_right = *wxGetApp().preset_bundle;
    m_pr_technology = m_preset_bundle_left.get()->printers.get_edited_preset().printer_technology();
}
References m_pr_technology, m_preset_bundle_left, and m_preset_bundle_right.
Referenced by button_event(), show(), and update_presets().
update_compatibility()
void Slic3r::GUI::DiffPresetDialog::update_compatibility (const std::string & preset_name, Preset::Type type, PresetBundle * preset_bundle) private
{
    PresetCollection* presets = get_preset_collection(type, preset_bundle);
    bool print_tab = type == Preset::TYPE_PRINT || type == Preset::TYPE_SLA_PRINT;
    bool printer_tab = type == Preset::TYPE_PRINTER;
    bool technology_changed = false;
    if (printer_tab) {
        const Preset& new_printer_preset = *presets->find_preset(preset_name, true);
        PrinterTechnology    old_printer_technology = presets->get_selected_preset().printer_technology();
        PrinterTechnology    new_printer_technology = new_printer_preset.printer_technology();
        technology_changed = old_printer_technology != new_printer_technology;
    }
    // select preset
    presets->select_preset_by_name(preset_name, false);
    // Mark the print & filament enabled if they are compatible with the currently selected preset.
    // The following method should not discard changes of current print or filament presets on change of a printer profile,
    // if they are compatible with the current printer.
    auto update_compatible_type = [](bool technology_changed, bool on_page, bool show_incompatible_presets) {
        return  technology_changed ? PresetSelectCompatibleType::Always :
            on_page ? PresetSelectCompatibleType::Never :
            show_incompatible_presets ? PresetSelectCompatibleType::OnlyIfWasCompatible : PresetSelectCompatibleType::Always;
    };
    if (print_tab || printer_tab)
        preset_bundle->update_compatible(
            update_compatible_type(technology_changed, print_tab, true),
            update_compatible_type(technology_changed, false, true));
    bool is_left_presets = preset_bundle == m_preset_bundle_left.get();
    PrinterTechnology pr_tech = preset_bundle->printers.get_selected_preset().printer_technology();
    // update preset comboboxes
    for (auto preset_combos : m_preset_combos)
    {
        PresetComboBox* cb = is_left_presets ? preset_combos.presets_left : preset_combos.presets_right;
        Preset::Type presets_type = cb->get_type();
        if ((print_tab && (
                (pr_tech == ptFFF && presets_type == Preset::TYPE_FILAMENT) ||
                (pr_tech == ptSLA && presets_type == Preset::TYPE_SLA_MATERIAL) )) ||
            (printer_tab && (
                (pr_tech == ptFFF && (presets_type == Preset::TYPE_PRINT || presets_type == Preset::TYPE_FILAMENT) ) ||
                (pr_tech == ptSLA && (presets_type == Preset::TYPE_SLA_PRINT || presets_type == Preset::TYPE_SLA_MATERIAL) )) ))
            cb->update();
    }
    if (technology_changed &&
        m_preset_bundle_left.get()->printers.get_selected_preset().printer_technology() ==
        m_preset_bundle_right.get()->printers.get_selected_preset().printer_technology())
    {
        m_pr_technology = m_preset_bundle_left.get()->printers.get_edited_preset().printer_technology();
        update_controls_visibility();
    }
}
References Slic3r::Always, Slic3r::PresetCollection::find_preset(), Slic3r::GUI::get_preset_collection(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::GUI::PresetComboBox::get_type(), m_pr_technology, m_preset_bundle_left, m_preset_bundle_right, m_preset_combos, Slic3r::Never, Slic3r::OnlyIfWasCompatible, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::PresetCollection::select_preset_by_name(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::Preset::TYPE_SLA_PRINT, Slic3r::GUI::PresetComboBox::update(), Slic3r::PresetBundle::update_compatible(), and update_controls_visibility().
Referenced by create_presets_sizer().
update_controls_visibility()
void Slic3r::GUI::DiffPresetDialog::update_controls_visibility (Preset::Type type = Preset::TYPE_INVALID) private
{
    for (auto preset_combos : m_preset_combos) {
        Preset::Type cb_type = preset_combos.presets_left->get_type();
        bool show = type != Preset::TYPE_INVALID    ? type == cb_type :
                    cb_type == Preset::TYPE_PRINTER ? true :
                    m_pr_technology == ptFFF        ? cb_type == Preset::TYPE_PRINT || cb_type == Preset::TYPE_FILAMENT :
                                                      cb_type == Preset::TYPE_SLA_PRINT || cb_type == Preset::TYPE_SLA_MATERIAL;
        preset_combos.presets_left->Show(show);
        preset_combos.equal_bmp->Show(show);
        preset_combos.presets_right->Show(show);
        if (show) {
            preset_combos.presets_left->update_from_bundle();
            preset_combos.presets_right->update_from_bundle();
        }
    }
    m_show_all_presets->Show(type != Preset::TYPE_PRINTER);
}
References m_pr_technology, m_preset_combos, m_show_all_presets, Slic3r::ptFFF, show(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_INVALID, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, and Slic3r::Preset::TYPE_SLA_PRINT.
Referenced by show(), update_compatibility(), and update_presets().
update_presets()
void Slic3r::GUI::DiffPresetDialog::update_presets (Preset::Type type = Preset::TYPE_INVALID, bool update_preset_bundles_from_app = true)
{
    if (update_preset_bundles_from_app)
        update_bundles_from_app();
    update_controls_visibility(type);
    if (type == Preset::TYPE_INVALID)
        for (auto preset_combos : m_preset_combos) {
            if (preset_combos.presets_left->get_type() == Preset::TYPE_PRINTER) {
                preset_combos.presets_left->update_from_bundle ();
                preset_combos.presets_right->update_from_bundle();
                break;
            }
        }
    else
        for (auto preset_combos : m_preset_combos) {
            if (preset_combos.presets_left->get_type() == type) {
                preset_combos.presets_left->update();
                preset_combos.presets_right->update();
                break;
            }
        }
    update_tree();
}
References m_preset_combos, Slic3r::Preset::TYPE_INVALID, Slic3r::Preset::TYPE_PRINTER, update_bundles_from_app(), update_controls_visibility(), and update_tree().
Referenced by button_event().
update_tree()
void Slic3r::GUI::DiffPresetDialog::update_tree () private
{
    // update searcher before update of tree
    wxGetApp().sidebar().check_and_update_searcher();
    Search::OptionsSearcher& searcher = wxGetApp().sidebar().get_searcher();
    searcher.sort_options_by_key();
    m_tree->Clear();
    wxString bottom_info = "";
    bool show_tree = false;
    for (auto preset_combos : m_preset_combos)
    {
        if (!preset_combos.presets_left->IsShown())
            continue;
        Preset::Type type = preset_combos.presets_left->get_type();
        const PresetCollection* presets = get_preset_collection(type);
        std::string preset_name_full = get_selection(preset_combos.presets_left);
        std::string preset_name = Preset::remove_suffix_modified(preset_name_full);
        const Preset* left_preset  = presets->find_preset(preset_name, false, preset_name_full.length() != preset_name.length());
        preset_name_full = get_selection(preset_combos.presets_right);
        preset_name = Preset::remove_suffix_modified(preset_name_full);
        const Preset* right_preset = presets->find_preset(preset_name, false, preset_name_full.length() != preset_name.length());
        if (!left_preset || !right_preset) {
            bottom_info = _L("One of the presets doesn't found");
            preset_combos.equal_bmp->SetBitmap_(ScalableBitmap(this, "question"));
            preset_combos.equal_bmp->SetToolTip(bottom_info);
            continue;
        }
        const DynamicPrintConfig& left_config   = left_preset->config;
        const PrinterTechnology&  left_pt       = left_preset->printer_technology();
        const DynamicPrintConfig& right_congig  = right_preset->config;
        if (left_pt != right_preset->printer_technology()) {
            bottom_info = _L("Compared presets has different printer technology");
            preset_combos.equal_bmp->SetBitmap_(ScalableBitmap(this, "question"));
            preset_combos.equal_bmp->SetToolTip(bottom_info);
            continue;
        }
        // Collect dirty options.
        const bool deep_compare = type != Preset::TYPE_FILAMENT;
        auto dirty_options = type == Preset::TYPE_PRINTER && left_pt == ptFFF &&
                             left_config.opt<ConfigOptionStrings>("extruder_colour")->values.size() < right_congig.opt<ConfigOptionStrings>("extruder_colour")->values.size() ?
                             presets->dirty_options(right_preset, left_preset, deep_compare) :
                             presets->dirty_options(left_preset, right_preset, deep_compare);
        if (dirty_options.empty()) {
            bottom_info = _L("Presets are the same");
            preset_combos.equal_bmp->SetBitmap_(ScalableBitmap(this, "equal"));
            preset_combos.equal_bmp->SetToolTip(bottom_info);
            continue;
        }
        show_tree = true;
        preset_combos.equal_bmp->SetBitmap_(ScalableBitmap(this, "not_equal"));
        preset_combos.equal_bmp->SetToolTip(_L("Presets are different.\n"
                                               "Click this button to select the same preset for the right and left preset."));
        m_tree->model->AddPreset(type, "\"" + from_u8(left_preset->name) + "\" vs \"" + from_u8(right_preset->name) + "\"", left_pt);
        const std::map<wxString, std::string>& category_icon_map = wxGetApp().get_tab(type)->get_category_icon_map();
        // process changes of extruders count
        if (type == Preset::TYPE_PRINTER && left_pt == ptFFF &&
            left_config.opt<ConfigOptionStrings>("extruder_colour")->values.size() != right_congig.opt<ConfigOptionStrings>("extruder_colour")->values.size()) {
            wxString local_label = _L("Extruders count");
            wxString left_val = from_u8((boost::format("%1%") % left_config.opt<ConfigOptionStrings>("extruder_colour")->values.size()).str());
            wxString right_val = from_u8((boost::format("%1%") % right_congig.opt<ConfigOptionStrings>("extruder_colour")->values.size()).str());
            m_tree->Append("extruders_count", type, _L("General"), _L("Capabilities"), local_label, left_val, right_val, "", category_icon_map.at("General"));
        }
        for (const std::string& opt_key : dirty_options) {
            wxString left_val = get_string_value(opt_key, left_config);
            wxString right_val = get_string_value(opt_key, right_congig);
            Search::Option option = searcher.get_option(opt_key, get_full_label(opt_key, left_config), type);
            if (option.opt_key() != opt_key) {
                // temporary solution, just for testing
                m_tree->Append(opt_key, type, _L("Undef category"), _L("Undef group"), opt_key, left_val, right_val, "", "question");
                // When founded option isn't the correct one.
                // It can be for dirty_options: "default_print_profile", "printer_model", "printer_settings_id",
                // because of they don't exist in searcher
                continue;
            }
            m_tree->Append(opt_key, type, option.category_local, option.group_local, option.label_local,
                left_val, right_val, "", category_icon_map.at(option.category));
        }
    }
    bool tree_was_shown = m_tree->IsShown();
    m_tree->Show(show_tree);
    bool can_transfer_options = m_view_type == Preset::TYPE_INVALID || get_left_preset_name(m_view_type) != get_right_preset_name(m_view_type);
    m_edit_sizer->Show(show_tree && can_transfer_options);
    m_buttons->Show(m_edit_sizer->IsShown(size_t(0)) && m_use_for_transfer->GetValue());
    update_bottom_info(bottom_info);
    if (tree_was_shown == m_tree->IsShown())
        Layout();
    else {
        Fit();
        Refresh();
    }
    // Revert sort of searcher back
    searcher.sort_options_by_label();
}
References _L, Slic3r::GUI::DiffModel::AddPreset(), Slic3r::GUI::DiffViewCtrl::Append(), Slic3r::GUI::DiffViewCtrl::Clear(), Slic3r::Preset::config, Slic3r::PresetCollection::dirty_options(), Slic3r::PresetCollection::find_preset(), Slic3r::GUI::from_u8(), Slic3r::GUI::get_full_label(), get_left_preset_name(), Slic3r::Search::OptionsSearcher::get_option(), Slic3r::GUI::get_preset_collection(), get_right_preset_name(), Slic3r::GUI::get_selection(), Slic3r::GUI::get_string_value(), m_buttons, m_edit_sizer, m_preset_combos, m_tree, m_use_for_transfer, m_view_type, Slic3r::GUI::DiffViewCtrl::model, Slic3r::Preset::name, Slic3r::ConfigBase::opt(), Slic3r::Preset::printer_technology(), Slic3r::ptFFF, Slic3r::Preset::remove_suffix_modified(), Slic3r::ConfigOptionVector< T >::size(), Slic3r::Search::OptionsSearcher::sort_options_by_key(), Slic3r::Search::OptionsSearcher::sort_options_by_label(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_INVALID, Slic3r::Preset::TYPE_PRINTER, update_bottom_info(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by create_presets_sizer(), create_show_all_presets_chb(), show(), and update_presets().
view_type()
Preset::Type Slic3r::GUI::DiffPresetDialog::view_type () const inline
{ return m_view_type; }
References m_view_type.
Referenced by Slic3r::GUI::MainFrame::bind_diff_dialog().
Member Data Documentation
m_bottom_info_line
wxStaticText* Slic3r::GUI::DiffPresetDialog::m_bottom_info_line { nullptr } private
Referenced by complete_dialog_creation(), create_buttons(), create_info_lines(), and update_bottom_info().
m_buttons
wxBoxSizer* Slic3r::GUI::DiffPresetDialog::m_buttons { nullptr } private
Referenced by create_buttons(), create_edit_sizer(), and update_tree().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_cancel_btn
ScalableButton* Slic3r::GUI::DiffPresetDialog::m_cancel_btn { nullptr } private
Referenced by create_buttons(), and on_sys_color_changed().
m_edit_sizer
wxBoxSizer* Slic3r::GUI::DiffPresetDialog::m_edit_sizer { nullptr } private
Referenced by complete_dialog_creation(), create_edit_sizer(), and update_tree().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_pr_technology
PrinterTechnology Slic3r::GUI::DiffPresetDialog::m_pr_technology private
Referenced by printer_technology(), types_list(), update_bundles_from_app(), update_compatibility(), and update_controls_visibility().
m_preset_bundle_left
std::unique_ptr<PresetBundle> Slic3r::GUI::DiffPresetDialog::m_preset_bundle_left private
Referenced by DiffPresetDialog(), button_event(), create_presets_sizer(), update_bundles_from_app(), and update_compatibility().
m_preset_bundle_right
std::unique_ptr<PresetBundle> Slic3r::GUI::DiffPresetDialog::m_preset_bundle_right private
Referenced by DiffPresetDialog(), button_event(), create_presets_sizer(), is_save_confirmed(), update_bundles_from_app(), and update_compatibility().
m_preset_combos
std::vector<DiffPresets> Slic3r::GUI::DiffPresetDialog::m_preset_combos private
Referenced by create_presets_sizer(), create_show_all_presets_chb(), get_left_preset_name(), get_right_preset_name(), on_dpi_changed(), on_sys_color_changed(), update_compatibility(), update_controls_visibility(), update_presets(), and update_tree().
m_presets_sizer
wxBoxSizer* Slic3r::GUI::DiffPresetDialog::m_presets_sizer { nullptr } private
Referenced by complete_dialog_creation(), and create_presets_sizer().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_save_btn
ScalableButton* Slic3r::GUI::DiffPresetDialog::m_save_btn { nullptr } private
Referenced by create_buttons(), and on_sys_color_changed().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_show_all_presets
wxCheckBox* Slic3r::GUI::DiffPresetDialog::m_show_all_presets { nullptr } private
Referenced by complete_dialog_creation(), create_show_all_presets_chb(), on_sys_color_changed(), and update_controls_visibility().
m_top_info_line
wxStaticText* Slic3r::GUI::DiffPresetDialog::m_top_info_line { nullptr } private
Referenced by complete_dialog_creation(), and create_info_lines().
m_transfer_btn
ScalableButton* Slic3r::GUI::DiffPresetDialog::m_transfer_btn { nullptr } private
Referenced by create_buttons(), and on_sys_color_changed().
m_tree
DiffViewCtrl* Slic3r::GUI::DiffPresetDialog::m_tree { nullptr } private
Referenced by complete_dialog_creation(), create_buttons(), create_edit_sizer(), create_tree(), get_options_to_save(), get_selected_options(), is_save_confirmed(), on_dpi_changed(), on_sys_color_changed(), update_bottom_info(), and update_tree().
m_use_for_transfer
wxCheckBox* Slic3r::GUI::DiffPresetDialog::m_use_for_transfer { nullptr } private
Referenced by create_edit_sizer(), and update_tree().
m_view_type
Preset::Type Slic3r::GUI::DiffPresetDialog::m_view_type { Preset::TYPE_INVALID } private
Referenced by button_event(), create_buttons(), create_presets_sizer(), create_show_all_presets_chb(), show(), update_tree(), and view_type().
presets_to_save
std::vector<PresetToSave> Slic3r::GUI::DiffPresetDialog::presets_to_save private
Referenced by button_event(), and is_save_confirmed().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UnsavedChangesDialog.hpp
src/slic3r/GUI/UnsavedChangesDialog.cpp