Prusa Slicer: Slic3r::GUI::GLGizmoSlaSupports Class Reference
Slic3r::GUI::GLGizmoSlaSupports Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoSlaSupports.hpp>
Classes
class CacheEntry
Public Types
enum class EGrabberExtension {
None = 0 , PosX = 1 << 0 , NegX = 1 << 1 , PosY = 1 << 2 ,
NegY = 1 << 3 , PosZ = 1 << 4 , NegZ = 1 << 5
}
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoSlaSupports (GLCanvas3D &parent, const std::string &icon_filename, unsigned int sprite_id)
virtual ~GLGizmoSlaSupports ()=default
void data_changed (bool is_serializing) override
Is called when data (Selection) is changed.
bool gizmo_event (SLAGizmoEventType action, const Vec2d &mouse_position, bool shift_down, bool alt_down, bool control_down)
void delete_selected_points (bool force=false)
bool is_in_editing_mode () const override
bool is_selection_rectangle_dragging () const override
bool has_backend_supports () const
bool wants_enter_leave_snapshots () const override
std::string get_gizmo_entering_text () const override
std::string get_gizmo_leaving_text () const override
bool on_mouse (const wxMouseEvent &mouse_event) override
Process mouse event.
void reslice_until_step (SLAPrintObjectStep step, bool postpone_error_messages=false)
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
virtual std::string get_action_snapshot_name () const
void set_common_data_pool (CommonGizmosDataPool *ptr)
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
bool is_dragging () const
bool update_items_state ()
void render ()
void render_input_window (float x, float y, float bottom_limit)
virtual std::string get_tooltip () const
Mouse tooltip text.
void register_raycasters_for_picking ()
void unregister_raycasters_for_picking ()
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static const unsigned int GRABBER_ELEMENTS_MAX_COUNT = 7
static const int NO_SHORTCUT_KEY_VALUE = 0
Protected Member Functions
void on_set_state () override
void on_set_hover_id () override
void on_start_dragging () override
void on_stop_dragging () override
void on_dragging (const UpdateData &data) override
void on_render_input_window (float x, float y, float bottom_limit) override
std::string on_get_name () const override
bool on_is_activable () const override
bool on_is_selectable () const override
void on_load (cereal::BinaryInputArchive &ar) override
void on_save (cereal::BinaryOutputArchive &ar) const override
virtual CommonGizmosDataID on_get_requirements () const override
void update_volumes ()
void render_volumes ()
void register_volume_raycasters_for_picking ()
void unregister_volume_raycasters_for_picking ()
bool is_input_enabled () const
int get_min_sla_print_object_step () const
bool unproject_on_mesh (const Vec2d &mouse_pos, std::pair< Vec3f, Vec3f > &pos_and_normal)
bool are_sla_supports_shown () const
void show_sla_supports (bool show)
const GLVolumeCollection & volumes () const
virtual void on_enable_grabber (unsigned int id)
virtual void on_disable_grabber (unsigned int id)
void register_grabbers_for_picking ()
void unregister_grabbers_for_picking ()
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers (size_t first, size_t last, float size, bool force_hover) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
bool use_grabbers (const wxMouseEvent &mouse_event)
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
void do_stop_dragging (bool perform_mouse_cleanup)
Protected Attributes
GLCanvas3D & m_parent
int m_group_id
EState m_state
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id { -1 }
bool m_dragging { false }
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render { true }
CommonGizmosDataPool * m_c { nullptr }
Private Types
enum { AllPoints = -2 , NoPoints }
Private Member Functions
bool on_init () override
void on_render () override
virtual void on_register_raycasters_for_picking () override
virtual void on_unregister_raycasters_for_picking () override
void render_points (const Selection &selection)
bool unsaved_changes () const
void register_point_raycasters_for_picking ()
void unregister_point_raycasters_for_picking ()
void update_point_raycasters_for_picking_transform ()
std::vector< const ConfigOption * > get_config_options (const std::vector< std::string > &keys) const
bool is_mesh_point_clipped (const Vec3d &point) const
void select_point (int i)
void unselect_point (int i)
void editing_mode_apply_changes ()
void editing_mode_discard_changes ()
void reload_cache ()
void get_data_from_backend ()
void auto_generate ()
void switch_to_editing_mode ()
void disable_editing_mode ()
bool ask_about_changes (std::function< void()> on_yes, std::function< void()> on_no)
Private Attributes
bool m_lock_unique_islands = false
bool m_editing_mode = false
float m_new_point_head_diameter
CacheEntry m_point_before_drag
float m_old_point_head_diameter = 0.
float m_minimal_point_distance_stash = 0.f
float m_density_stash = 0.f
std::vector< CacheEntry > m_editing_cache
std::vector< sla::SupportPoint > m_normal_cache
ObjectID m_old_mo_id
PickingModel m_sphere
PickingModel m_cone
std::vector< std::pair< std::shared_ptr< SceneRaycasterItem >, std::shared_ptr< SceneRaycasterItem > > > m_point_raycasters
std::map< std::string, wxString > m_desc
GLSelectionRectangle m_selection_rectangle
bool m_wait_for_up_event = false
bool m_selection_empty = true
GLVolumeCollection m_volumes
bool m_input_enabled { false }
bool m_show_sla_supports { false }
int m_min_sla_print_object_step { -1 }
std::vector< std::shared_ptr< SceneRaycasterItem > > m_volume_raycasters
bool m_dirty { false }
Static Private Attributes
static constexpr float RenderPointScale = 1.f
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
AllPoints
NoPoints
         {
        AllPoints = -2,
        NoPoints,
    };
EGrabberExtension
enum class Slic3r::GUI::GLGizmoBase::EGrabberExtension strong inherited
Enumerator
None
PosX
NegX
PosY
NegY
PosZ
NegZ
    {
        None = 0,
        PosX = 1 << 0,
        NegX = 1 << 1,
        PosY = 1 << 2,
        NegY = 1 << 3,
        PosZ = 1 << 4,
        NegZ = 1 << 5,
    };
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
Constructor & Destructor Documentation
GLGizmoSlaSupports()
Slic3r::GUI::GLGizmoSlaSupports::GLGizmoSlaSupports (GLCanvas3D & parent, const std::string & icon_filename, unsigned int sprite_id)
: GLGizmoSlaBase(parent, icon_filename, sprite_id, slaposDrillHoles)
{
    show_sla_supports(true);
}
References Slic3r::GUI::GLGizmoSlaBase::show_sla_supports().
~GLGizmoSlaSupports()
virtual Slic3r::GUI::GLGizmoSlaSupports::~GLGizmoSlaSupports () virtual default
Member Function Documentation
are_sla_supports_shown()
bool Slic3r::GUI::GLGizmoSlaBase::are_sla_supports_shown () const inline protected inherited
{ return m_show_sla_supports; }
References Slic3r::GUI::GLGizmoSlaBase::m_show_sla_supports.
Referenced by Slic3r::GUI::GLGizmoHollow::on_render(), and Slic3r::GUI::GLGizmoHollow::on_render_input_window().
ask_about_changes()
bool Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes (std::function< void()> on_yes, std::function< void()> on_no) private
{
    MessageDialog dlg(GUI::wxGetApp().mainframe, _L("Do you want to save your manually edited support points?") + "\n",
                      _L("Save support points?"), wxICON_QUESTION | wxYES | wxNO | wxCANCEL );
    const int ret = dlg.ShowModal();
    if (ret == wxID_YES)
        on_yes();
    else if (ret == wxID_NO)
        on_no();
    else
        return false;
    return true;
}
References _L.
Referenced by gizmo_event(), and on_set_state().
auto_generate()
void Slic3r::GUI::GLGizmoSlaSupports::auto_generate () private
{
    //wxMessageDialog dlg(GUI::wxGetApp().plater(),
    MessageDialog dlg(GUI::wxGetApp().plater(),
                        _L("Autogeneration will erase all manually edited points.") + "\n\n" +
                        _L("Are you sure you want to do it?") + "\n",
                        _L("Warning"), wxICON_WARNING | wxYES | wxNO);
    ModelObject* mo = m_c->selection_info()->model_object();
    if (mo->sla_points_status != sla::PointsStatus::UserModified || m_normal_cache.empty() || dlg.ShowModal() == wxID_YES) {
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Autogenerate support points"));
        wxGetApp().CallAfter([this]() { reslice_until_step(slaposPad); });
        mo->sla_points_status = sla::PointsStatus::Generating;
    }
}
References _L, Slic3r::sla::Generating, Slic3r::GUI::GLGizmoBase::m_c, m_normal_cache, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::plater(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::ModelObject::sla_points_status, Slic3r::slaposPad, and Slic3r::sla::UserModified.
Referenced by gizmo_event(), and on_render_input_window().
data_changed()
void Slic3r::GUI::GLGizmoSlaSupports::data_changed (bool is_serializing) override virtual
Is called when data (Selection) is changed.
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (! m_c->selection_info())
        return;
    ModelObject* mo = m_c->selection_info()->model_object();
    if (m_state == On && mo && mo->id() != m_old_mo_id) {
        disable_editing_mode();
        reload_cache();
        m_old_mo_id = mo->id();
    }
    // If we triggered autogeneration before, check backend and fetch results if they are there
    if (mo) {
        m_c->instances_hider()->set_hide_full_scene(true);
        int last_comp_step = slaposCount;
        const int required_step = get_min_sla_print_object_step();
        const SLAPrintObject* po = m_c->selection_info()->print_object();
        if (po != nullptr)
            last_comp_step = static_cast<int>(po->last_completed_step());
        if (last_comp_step == slaposCount)
            last_comp_step = -1;
        if (po != nullptr && last_comp_step < required_step)
            reslice_until_step((SLAPrintObjectStep)required_step, false);
        update_volumes();
        if (mo->sla_points_status == sla::PointsStatus::Generating)
            get_data_from_backend();
        if (m_point_raycasters.empty())
            register_point_raycasters_for_picking();
        else
            update_point_raycasters_for_picking_transform();
        m_c->instances_hider()->set_hide_full_scene(true);
    }
//    m_parent.toggle_model_objects_visibility(false);
}
References disable_editing_mode(), Slic3r::sla::Generating, get_data_from_backend(), Slic3r::GUI::GLGizmoSlaBase::get_min_sla_print_object_step(), Slic3r::ObjectBase::id(), Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::last_completed_step(), Slic3r::GUI::GLGizmoBase::m_c, m_old_mo_id, m_point_raycasters, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), register_point_raycasters_for_picking(), reload_cache(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::set_hide_full_scene(), Slic3r::ModelObject::sla_points_status, Slic3r::slaposCount, update_point_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
delete_selected_points()
void Slic3r::GUI::GLGizmoSlaSupports::delete_selected_points (bool force = false)
{
    if (! m_editing_mode) {
        std::cout << "DEBUGGING: delete_selected_points called out of editing mode!" << std::endl;
        std::abort();
    }
    Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Delete support point"));
    for (unsigned int idx=0; idx<m_editing_cache.size(); ++idx) {
        if (m_editing_cache[idx].selected && (!m_editing_cache[idx].support_point.is_new_island || !m_lock_unique_islands || force)) {
            m_editing_cache.erase(m_editing_cache.begin() + (idx--));
        }
    }
    unregister_point_raycasters_for_picking();
    register_point_raycasters_for_picking();
    select_point(NoPoints);
}
References _L, m_editing_cache, m_editing_mode, m_lock_unique_islands, NoPoints, Slic3r::GUI::plater(), register_point_raycasters_for_picking(), select_point(), and unregister_point_raycasters_for_picking().
Referenced by gizmo_event(), and on_render_input_window().
disable_editing_mode()
void Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode () private
{
    if (m_editing_mode) {
        m_editing_mode = false;
        wxGetApp().plater()->leave_gizmos_stack();
        m_parent.set_as_dirty();
        unregister_point_raycasters_for_picking();
    }
    wxGetApp().plater()->get_notification_manager()->close_notification_of_type(NotificationType::QuitSLAManualMode);
}
References m_editing_mode, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::QuitSLAManualMode, Slic3r::GUI::GLCanvas3D::set_as_dirty(), and unregister_point_raycasters_for_picking().
Referenced by data_changed(), editing_mode_apply_changes(), editing_mode_discard_changes(), and on_set_state().
do_stop_dragging()
void Slic3r::GUI::GLGizmoBase::do_stop_dragging (bool perform_mouse_cleanup) protected inherited
{
    for (auto& grabber : m_grabbers) grabber.dragging = false;
    m_dragging = false;
    // NOTE: This should be part of GLCanvas3D
    // Reset hover_id when leave window
    if (perform_mouse_cleanup) m_parent.mouse_up_cleanup();
    on_stop_dragging();
    // There is prediction that after draggign, data are changed
    // Data are updated twice also by canvas3D::reload_scene.
    // Should be fixed.
    m_parent.get_gizmos_manager().update_data();
    wxGetApp().obj_manipul()->set_dirty();
    // Let the plater know that the dragging finished, so a delayed
    // refresh of the scene with the background processing data should
    // be performed.
    m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED));
    // updates camera target constraints
    m_parent.refresh_camera_scene_box();
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_up_cleanup(), Slic3r::GUI::GLGizmoBase::on_stop_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::refresh_camera_scene_box(), and Slic3r::GUI::GLGizmosManager::update_data().
Referenced by Slic3r::GUI::GLGizmoBase::use_grabbers().
editing_mode_apply_changes()
void Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes () private
{
    // If there are no changes, don't touch the front-end. The data in the cache could have been
    // taken from the backend and copying them to ModelObject would needlessly invalidate them.
    disable_editing_mode(); // this leaves the editing mode undo/redo stack and must be done before the snapshot is taken
    if (unsaved_changes()) {
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Support points edit"));
        m_normal_cache.clear();
        for (const CacheEntry& ce : m_editing_cache)
            m_normal_cache.push_back(ce.support_point);
        ModelObject* mo = m_c->selection_info()->model_object();
        mo->sla_points_status = sla::PointsStatus::UserModified;
        mo->sla_support_points.clear();
        mo->sla_support_points = m_normal_cache;
        reslice_until_step(slaposPad);
    }
}
References _L, disable_editing_mode(), Slic3r::GUI::GLGizmoBase::m_c, m_editing_cache, m_normal_cache, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::plater(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::ModelObject::sla_points_status, Slic3r::ModelObject::sla_support_points, Slic3r::slaposPad, unsaved_changes(), and Slic3r::sla::UserModified.
Referenced by gizmo_event(), on_render_input_window(), and on_set_state().
editing_mode_discard_changes()
void Slic3r::GUI::GLGizmoSlaSupports::editing_mode_discard_changes () private
{
    if (! m_editing_mode) {
        std::cout << "DEBUGGING: editing_mode_discard_changes called when out of editing mode!" << std::endl;
        std::abort();
    }
    select_point(NoPoints);
    disable_editing_mode();
}
References disable_editing_mode(), m_editing_mode, NoPoints, and select_point().
Referenced by gizmo_event(), on_render_input_window(), and on_set_state().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoEmboss::init_font_name_texture(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoEmboss::rev_input(), Slic3r::GUI::GLGizmoEmboss::rev_input_mm(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
get_action_snapshot_name()
std::string Slic3r::GUI::GLGizmoBase::get_action_snapshot_name () const virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoEmboss, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMeasure, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
{
    return _u8L("Gizmo action");
}
References _u8L.
Referenced by Slic3r::GUI::Plater::priv::take_snapshot().
get_config_options()
std::vector< const ConfigOption * > Slic3r::GUI::GLGizmoSlaSupports::get_config_options (const std::vector< std::string > & keys) const private
{
    std::vector<const ConfigOption*> out;
    const ModelObject* mo = m_c->selection_info()->model_object();
    if (! mo)
        return out;
    const DynamicPrintConfig& object_cfg = mo->config.get();
    const DynamicPrintConfig& print_cfg = wxGetApp().preset_bundle->sla_prints.get_edited_preset().config;
    std::unique_ptr<DynamicPrintConfig> default_cfg = nullptr;
    for (const std::string& key : keys) {
        if (object_cfg.has(key))
            out.push_back(object_cfg.option(key));
        else
            if (print_cfg.has(key))
                out.push_back(print_cfg.option(key));
            else { // we must get it from defaults
                if (default_cfg == nullptr)
                    default_cfg.reset(DynamicPrintConfig::new_from_defaults_keys(keys));
                out.push_back(default_cfg->option(key));
            }
    }
    return out;
}
References Slic3r::ModelObject::config, Slic3r::ModelConfig::get(), Slic3r::ConfigOptionResolver::has(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::DynamicPrintConfig::new_from_defaults_keys(), Slic3r::ConfigBase::option(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by on_render_input_window().
get_data_from_backend()
void Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend () private
{
    if (! has_backend_supports())
        return;
    ModelObject* mo = m_c->selection_info()->model_object();
    // find the respective SLAPrintObject, we need a pointer to it
    for (const SLAPrintObject* po : m_parent.sla_print()->objects()) {
        if (po->model_object()->id() == mo->id()) {
            m_normal_cache.clear();
            const std::vector<sla::SupportPoint>& points = po->get_support_points();
            auto mat = po->trafo().inverse().cast<float>();
            for (unsigned int i=0; i<points.size();++i)
                m_normal_cache.emplace_back(sla::SupportPoint(mat * points[i].pos, points[i].head_front_radius, points[i].is_new_island));
            mo->sla_points_status = sla::PointsStatus::AutoGenerated;
            break;
        }
    }
    // We don't copy the data into ModelObject, as this would stop the background processing.
}
References Slic3r::sla::AutoGenerated, has_backend_supports(), Slic3r::ObjectBase::id(), Slic3r::GUI::GLGizmoBase::m_c, m_normal_cache, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::SLAPrint::objects(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::ModelObject::sla_points_status, and Slic3r::GUI::GLCanvas3D::sla_print().
Referenced by data_changed(), and reload_cache().
get_gizmo_entering_text()
std::string Slic3r::GUI::GLGizmoSlaSupports::get_gizmo_entering_text () const inline override virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return _u8L("Entering SLA support points"); }
References _u8L.
get_gizmo_leaving_text()
std::string Slic3r::GUI::GLGizmoSlaSupports::get_gizmo_leaving_text () const inline override virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return _u8L("Leaving SLA support points"); }
References _u8L.
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmosManager::grabber_contains_mouse(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), and on_mouse().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_min_sla_print_object_step()
int Slic3r::GUI::GLGizmoSlaBase::get_min_sla_print_object_step () const inline protected inherited
{ return m_min_sla_print_object_step; }
References Slic3r::GUI::GLGizmoSlaBase::m_min_sla_print_object_step.
Referenced by data_changed().
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    std::string out = on_get_name();
    if (!include_shortcut) return out;
    int key = get_shortcut_key();
    assert(key==NO_SHORTCUT_KEY_VALUE || (key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z));
    out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE, and Slic3r::GUI::GLGizmoBase::on_get_name().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), on_render_input_window(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay().
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLCanvas3D::on_mouse().
get_tooltip()
virtual std::string Slic3r::GUI::GLGizmoBase::get_tooltip () const inline virtual inherited
Mouse tooltip text.
Returns
Text to be visible in mouse tooltip
Reimplemented in Slic3r::GUI::GLGizmoCut3D, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoScale3D.
{ return ""; }
Referenced by Slic3r::GUI::GLGizmosManager::get_tooltip().
gizmo_event()
bool Slic3r::GUI::GLGizmoSlaSupports::gizmo_event (SLAGizmoEventType action, const Vec2d & mouse_position, bool shift_down, bool alt_down, bool control_down)
{
    ModelObject* mo = m_c->selection_info()->model_object();
    int active_inst = m_c->selection_info()->get_active_instance();
    if (m_editing_mode) {
        // left down with shift - show the selection rectangle:
        if (action == SLAGizmoEventType::LeftDown && (shift_down || alt_down || control_down)) {
            if (m_hover_id == -1) {
                if (shift_down || alt_down) {
                    m_selection_rectangle.start_dragging(mouse_position, shift_down ? GLSelectionRectangle::EState::Select : GLSelectionRectangle::EState::Deselect);
                }
            }
            else {
                if (m_editing_cache[m_hover_id].selected)
                    unselect_point(m_hover_id);
                else {
                    if (!alt_down)
                        select_point(m_hover_id);
                }
            }
            return true;
        }
        // left down without selection rectangle - place point on the mesh:
        if (action == SLAGizmoEventType::LeftDown && !m_selection_rectangle.is_dragging() && !shift_down) {
            // If any point is in hover state, this should initiate its move - return control back to GLCanvas:
            if (m_hover_id != -1)
                return false;
            // If there is some selection, don't add new point and deselect everything instead.
            if (m_selection_empty) {
                std::pair<Vec3f, Vec3f> pos_and_normal;
                if (unproject_on_mesh(mouse_position, pos_and_normal)) { // we got an intersection
                    Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Add support point"));
                    m_editing_cache.emplace_back(sla::SupportPoint(pos_and_normal.first, m_new_point_head_diameter/2.f, false), false, pos_and_normal.second);
                    m_parent.set_as_dirty();
                    m_wait_for_up_event = true;
                    unregister_point_raycasters_for_picking();
                    register_point_raycasters_for_picking();
                }
                else
                    return false;
            }
            else
                select_point(NoPoints);
            return true;
        }
        // left up with selection rectangle - select points inside the rectangle:
        if ((action == SLAGizmoEventType::LeftUp || action == SLAGizmoEventType::ShiftUp || action == SLAGizmoEventType::AltUp) && m_selection_rectangle.is_dragging()) {
            // Is this a selection or deselection rectangle?
            GLSelectionRectangle::EState rectangle_status = m_selection_rectangle.get_state();
            // First collect positions of all the points in world coordinates.
            Geometry::Transformation trafo = mo->instances[active_inst]->get_transformation();
            trafo.set_offset(trafo.get_offset() + Vec3d(0., 0., m_c->selection_info()->get_sla_shift()));
            std::vector<Vec3d> points;
            for (unsigned int i=0; i<m_editing_cache.size(); ++i)
                points.push_back(trafo.get_matrix() * m_editing_cache[i].support_point.pos.cast<double>());
            // Now ask the rectangle which of the points are inside.
            std::vector<Vec3f> points_inside;
            std::vector<unsigned int> points_idxs = m_selection_rectangle.contains(points);
            m_selection_rectangle.stop_dragging();
            for (size_t idx : points_idxs)
                points_inside.push_back(points[idx].cast<float>());
            // Only select/deselect points that are actually visible. We want to check not only
            // the point itself, but also the center of base of its cone, so the points don't hide
            // under every miniature irregularity on the model. Remember the actual number and
            // append the cone bases.
            size_t orig_pts_num = points_inside.size();
            for (size_t idx : points_idxs)
                points_inside.emplace_back((trafo.get_matrix().cast<float>() * (m_editing_cache[idx].support_point.pos + m_editing_cache[idx].normal)).cast<float>());
            for (size_t idx : m_c->raycaster()->raycaster()->get_unobscured_idxs(
                    trafo, wxGetApp().plater()->get_camera(), points_inside,
                     m_c->object_clipper()->get_clipping_plane()))
            {
                if (idx >= orig_pts_num) // this is a cone-base, get index of point it belongs to
                    idx -= orig_pts_num;
                if (rectangle_status == GLSelectionRectangle::EState::Deselect)
                    unselect_point(points_idxs[idx]);
                else
                    select_point(points_idxs[idx]);
            }
            return true;
        }
        // left up with no selection rectangle
        if (action == SLAGizmoEventType::LeftUp) {
            if (m_wait_for_up_event) {
                m_wait_for_up_event = false;
                return true;
            }
        }
        // dragging the selection rectangle:
        if (action == SLAGizmoEventType::Dragging) {
            if (m_wait_for_up_event)
                return true; // point has been placed and the button not released yet
                             // this prevents GLCanvas from starting scene rotation
            if (m_selection_rectangle.is_dragging())  {
                m_selection_rectangle.dragging(mouse_position);
                return true;
            }
            return false;
        }
        if (action == SLAGizmoEventType::Delete) {
            // delete key pressed
            delete_selected_points();
            return true;
        }
        if (action ==  SLAGizmoEventType::ApplyChanges) {
            editing_mode_apply_changes();
            return true;
        }
        if (action ==  SLAGizmoEventType::DiscardChanges) {
            ask_about_changes([this](){ editing_mode_apply_changes(); },
                                         [this](){ editing_mode_discard_changes(); });
            return true;
        }
        if (action == SLAGizmoEventType::RightDown) {
            if (m_hover_id != -1) {
                select_point(NoPoints);
                select_point(m_hover_id);
                delete_selected_points();
                return true;
            }
            return false;
        }
        if (action == SLAGizmoEventType::SelectAll) {
            select_point(AllPoints);
            return true;
        }
    }
    if (!m_editing_mode) {
        if (action == SLAGizmoEventType::AutomaticGeneration) {
            auto_generate();
            return true;
        }
        if (action == SLAGizmoEventType::ManualEditing) {
            switch_to_editing_mode();
            return true;
        }
    }
    if (action == SLAGizmoEventType::MouseWheelUp && control_down) {
        double pos = m_c->object_clipper()->get_position();
        pos = std::min(1., pos + 0.01);
        m_c->object_clipper()->set_position_by_ratio(pos, true);
        return true;
    }
    if (action == SLAGizmoEventType::MouseWheelDown && control_down) {
        double pos = m_c->object_clipper()->get_position();
        pos = std::max(0., pos - 0.01);
        m_c->object_clipper()->set_position_by_ratio(pos, true);
        return true;
    }
    if (action == SLAGizmoEventType::ResetClippingPlane) {
        m_c->object_clipper()->set_position_by_ratio(-1., false);
        return true;
    }
    return false;
}
References _L, AllPoints, Slic3r::GUI::AltUp, Slic3r::GUI::ApplyChanges, ask_about_changes(), auto_generate(), Slic3r::GUI::AutomaticGeneration, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast(), Slic3r::GUI::GLSelectionRectangle::contains(), Slic3r::GUI::Delete, delete_selected_points(), Slic3r::GUI::GLSelectionRectangle::Deselect, Slic3r::GUI::DiscardChanges, Slic3r::GUI::Dragging, Slic3r::GUI::GLSelectionRectangle::dragging(), editing_mode_apply_changes(), editing_mode_discard_changes(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::GUI::GLSelectionRectangle::get_state(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::ModelObject::instances, Slic3r::GUI::GLSelectionRectangle::is_dragging(), Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, Slic3r::GUI::GLGizmoBase::m_c, m_editing_cache, m_editing_mode, Slic3r::GUI::GLGizmoBase::m_hover_id, m_new_point_head_diameter, Slic3r::GUI::GLGizmoBase::m_parent, m_selection_empty, m_selection_rectangle, m_wait_for_up_event, Slic3r::GUI::ManualEditing, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::MouseWheelDown, Slic3r::GUI::MouseWheelUp, NoPoints, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::plater(), Slic3r::points_inside(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycaster(), register_point_raycasters_for_picking(), Slic3r::GUI::ResetClippingPlane, Slic3r::GUI::RightDown, Slic3r::GUI::GLSelectionRectangle::Select, select_point(), Slic3r::GUI::SelectAll, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::Geometry::Transformation::set_offset(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position_by_ratio(), Slic3r::GUI::ShiftUp, Slic3r::GUI::GLSelectionRectangle::start_dragging(), Slic3r::GUI::GLSelectionRectangle::stop_dragging(), switch_to_editing_mode(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), unregister_point_raycasters_for_picking(), and unselect_point().
Referenced by on_mouse().
has_backend_supports()
bool Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports () const
{
    const ModelObject* mo = m_c->selection_info()->model_object();
    if (! mo)
        return false;
    // find SlaPrintObject with this ID
    for (const SLAPrintObject* po : m_parent.sla_print()->objects()) {
        if (po->model_object()->id() == mo->id())
          return po->is_step_done(slaposSupportPoints);
    }
    return false;
}
References Slic3r::ObjectBase::id(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::SLAPrint::objects(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLCanvas3D::sla_print(), and Slic3r::slaposSupportPoints.
Referenced by get_data_from_backend(), and Slic3r::GUI::GLGizmosManager::wants_reslice_supports_on_undo().
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_init().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmosManager::handle_shortcut(), Slic3r::GUI::GLGizmoEmboss::init_create(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
Referenced by Slic3r::GUI::GLGizmoCut3D::gizmo_event(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate().
is_in_editing_mode()
bool Slic3r::GUI::GLGizmoSlaSupports::is_in_editing_mode () const inline override virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return m_editing_mode; }
References m_editing_mode.
is_input_enabled()
bool Slic3r::GUI::GLGizmoSlaBase::is_input_enabled () const inline protected inherited
{ return m_input_enabled; }
References Slic3r::GUI::GLGizmoSlaBase::m_input_enabled.
Referenced by Slic3r::GUI::GLGizmoHollow::on_mouse(), on_mouse(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), and on_render_input_window().
is_mesh_point_clipped()
bool Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped (const Vec3d & point) const private
{
    if (m_c->object_clipper()->get_position() == 0.)
        return false;
    auto sel_info = m_c->selection_info();
    int active_inst = m_c->selection_info()->get_active_instance();
    const ModelInstance* mi = sel_info->model_object()->instances[active_inst];
    const Transform3d& trafo = mi->get_transformation().get_matrix() * sel_info->model_object()->volumes.front()->get_matrix();
    Vec3d transformed_point =  trafo * point;
    transformed_point(2) += sel_info->get_sla_shift();
    return m_c->object_clipper()->get_clipping_plane()->is_point_clipped(transformed_point);
}
References Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::ModelInstance::get_transformation(), Slic3r::GUI::ClippingPlane::is_point_clipped(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by render_points().
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
is_selection_rectangle_dragging()
bool Slic3r::GUI::GLGizmoSlaSupports::is_selection_rectangle_dragging () const inline override virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return m_selection_rectangle.is_dragging(); }
References Slic3r::GUI::GLSelectionRectangle::is_dragging(), and m_selection_rectangle.
load()
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
on_disable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_disable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_dragging()
void Slic3r::GUI::GLGizmoSlaSupports::on_dragging (const UpdateData & data) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    assert(m_hover_id != -1);
    if (!m_editing_mode) return;
    if (m_editing_cache[m_hover_id].support_point.is_new_island && m_lock_unique_islands)
        return;
    std::pair<Vec3f, Vec3f> pos_and_normal;
    if (!unproject_on_mesh(data.mouse_pos.cast<double>(), pos_and_normal))
        return;
    m_editing_cache[m_hover_id].support_point.pos = pos_and_normal.first;
    m_editing_cache[m_hover_id].support_point.is_new_island = false;
    m_editing_cache[m_hover_id].normal = pos_and_normal.second;
}
References m_editing_cache, m_editing_mode, Slic3r::GUI::GLGizmoBase::m_hover_id, m_lock_unique_islands, and Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh().
on_enable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_enable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_get_name()
std::string Slic3r::GUI::GLGizmoSlaSupports::on_get_name () const override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    return _u8L("SLA Support Points");
}
References _u8L.
on_get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoSlaBase::on_get_requirements () const override protected virtual inherited
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return CommonGizmosDataID(
                int(CommonGizmosDataID::SelectionInfo)
              | int(CommonGizmosDataID::InstancesHider)
              | int(CommonGizmosDataID::Raycaster)
              | int(CommonGizmosDataID::ObjectClipper)
              | int(CommonGizmosDataID::SupportsClipper));
}
References Slic3r::GUI::InstancesHider, Slic3r::GUI::ObjectClipper, Slic3r::GUI::Raycaster, Slic3r::GUI::SelectionInfo, and Slic3r::GUI::SupportsClipper.
on_init()
bool Slic3r::GUI::GLGizmoSlaSupports::on_init () override private virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    m_shortcut_key = WXK_CONTROL_L;
    m_desc["head_diameter"]    = _L("Head diameter") + ": ";
    m_desc["lock_supports"]    = _L("Lock supports under new islands");
    m_desc["remove_selected"]  = _L("Remove selected points");
    m_desc["remove_all"]       = _L("Remove all points");
    m_desc["apply_changes"]    = _L("Apply changes");
    m_desc["discard_changes"]  = _L("Discard changes");
    m_desc["minimal_distance"] = _L("Minimal points distance") + ": ";
    m_desc["points_density"]   = _L("Support points density") + ": ";
    m_desc["auto_generate"]    = _L("Auto-generate points");
    m_desc["manual_editing"]   = _L("Manual editing");
    m_desc["clipping_of_view"] = _L("Clipping of view")+ ": ";
    m_desc["reset_direction"]  = _L("Reset direction");
    return true;
}
References _L, m_desc, and Slic3r::GUI::GLGizmoBase::m_shortcut_key.
on_is_activable()
bool Slic3r::GUI::GLGizmoSlaSupports::on_is_activable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    const Selection& selection = m_parent.get_selection();
    if (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() != ptSLA
        || !selection.is_single_full_instance())
        return false;
    // Check that none of the selected volumes is outside. Only SLA auxiliaries (supports) are allowed outside.
    const Selection::IndicesList& list = selection.get_volume_idxs();
    for (const auto& idx : list)
        if (selection.get_volume(idx)->is_outside && selection.get_volume(idx)->composite_id.volume_id >= 0)
            return false;
    // Check that none of the selected volumes is marked as non-pritable.
    for (const auto& idx : list) {
        if (!selection.get_volume(idx)->printable)
          return false;
    }
    return true;
}
References Slic3r::GLVolume::composite_id, Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::ptSLA, and Slic3r::GLVolume::CompositeID::volume_id.
Referenced by on_set_state().
on_is_selectable()
bool Slic3r::GUI::GLGizmoSlaSupports::on_is_selectable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptSLA);
}
References Slic3r::ptSLA.
on_load()
void Slic3r::GUI::GLGizmoSlaSupports::on_load (cereal::BinaryInputArchive & ar) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar(m_new_point_head_diameter,
       m_normal_cache,
       m_editing_cache,
       m_selection_empty
    );
}
References m_editing_cache, m_new_point_head_diameter, m_normal_cache, and m_selection_empty.
on_mouse()
bool Slic3r::GUI::GLGizmoSlaSupports::on_mouse (const wxMouseEvent & mouse_event) override virtual
Process mouse event.
Parameters
mouse_event Keep information about mouse click
Returns
Return True when use the information otherwise False.
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (!is_input_enabled()) return true;
    if (mouse_event.Moving()) return false;
    if (!mouse_event.ShiftDown() && !mouse_event.AltDown()
        && use_grabbers(mouse_event)) return true;
    // wxCoord == int --> wx/types.h
    Vec2i mouse_coord(mouse_event.GetX(), mouse_event.GetY());
    Vec2d mouse_pos = mouse_coord.cast<double>();
    static bool pending_right_up = false;
    if (mouse_event.LeftDown()) {
        bool grabber_contains_mouse = (get_hover_id() != -1);
        bool control_down = mouse_event.CmdDown();
        if ((!control_down || grabber_contains_mouse) &&
            gizmo_event(SLAGizmoEventType::LeftDown, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), false))
        return true;
    } else if (mouse_event.Dragging()) {
        bool control_down = mouse_event.CmdDown();
        if (m_parent.get_move_volume_id() != -1) {
            // don't allow dragging objects with the Sla gizmo on
            return true;
        } else if (!control_down &&
                gizmo_event(SLAGizmoEventType::Dragging, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), false)) {
            // the gizmo got the event and took some action, no need to do
            // anything more here
            m_parent.set_as_dirty();
            return true;
        } else if (control_down && (mouse_event.LeftIsDown() || mouse_event.RightIsDown())){
            // CTRL has been pressed while already dragging -> stop current action
            if (mouse_event.LeftIsDown())
                gizmo_event(SLAGizmoEventType::LeftUp, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), true);
            else if (mouse_event.RightIsDown())
                pending_right_up = false;
        }
    } else if (mouse_event.LeftUp() && !m_parent.is_mouse_dragging()) {
        // in case SLA/FDM gizmo is selected, we just pass the LeftUp event
        // and stop processing - neither object moving or selecting is
        // suppressed in that case
        gizmo_event(SLAGizmoEventType::LeftUp, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), mouse_event.CmdDown());
        return true;
    }else if (mouse_event.RightDown()){
        if (m_parent.get_selection().get_object_idx() != -1 &&
            gizmo_event(SLAGizmoEventType::RightDown, mouse_pos, false, false, false)) {
            // we need to set the following right up as processed to avoid showing
            // the context menu if the user release the mouse over the object
            pending_right_up = true;
            // event was taken care of by the SlaSupports gizmo
            return true;
        }
    } else if (pending_right_up && mouse_event.RightUp()) {
        pending_right_up = false;
        return true;
    }
    return false;
}
References Slic3r::GUI::Dragging, Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLCanvas3D::get_move_volume_id(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), gizmo_event(), Slic3r::GUI::GLGizmoSlaBase::is_input_enabled(), Slic3r::GUI::GLCanvas3D::is_mouse_dragging(), Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::RightDown, Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
on_register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoSlaSupports::on_register_raycasters_for_picking () override private virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    register_point_raycasters_for_picking();
    register_volume_raycasters_for_picking();
}
References register_point_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking().
on_render()
void Slic3r::GUI::GLGizmoSlaSupports::on_render () override private virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    if (m_state == On) {
        // This gizmo is showing the object elevated. Tell the common
        // SelectionInfo object to lie about the actual shift.
        m_c->selection_info()->set_use_shift(true);
    }
    if (!m_sphere.model.is_initialized()) {
        indexed_triangle_set its = its_make_sphere(1.0, double(PI) / 12.0);
        m_sphere.model.init_from(its);
        m_sphere.mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
    }
    if (!m_cone.model.is_initialized()) {
        indexed_triangle_set its = its_make_cone(1.0, 1.0, double(PI) / 12.0);
        m_cone.model.init_from(its);
        m_cone.mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
    }
    ModelObject* mo = m_c->selection_info()->model_object();
    const Selection& selection = m_parent.get_selection();
    // If current m_c->m_model_object does not match selection, ask GLCanvas3D to turn us off
    if (m_state == On
     && (mo != selection.get_model()->objects[selection.get_object_idx()]
      || m_c->selection_info()->get_active_instance() != selection.get_instance_idx())) {
        m_parent.post_event(SimpleEvent(EVT_GLCANVAS_RESETGIZMOS));
        return;
    }
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glEnable(GL_DEPTH_TEST));
    show_sla_supports(!m_editing_mode);
    render_volumes();
    render_points(selection);
    m_selection_rectangle.render(m_parent);
    m_c->object_clipper()->render_cut();
    m_c->supports_clipper()->render_cut();
    glsafe(::glDisable(GL_BLEND));
}
References Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), glsafe, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::its_make_cone(), Slic3r::its_make_sphere(), Slic3r::GUI::GLGizmoBase::m_c, m_cone, m_editing_mode, Slic3r::GUI::GLGizmoBase::m_parent, m_selection_rectangle, m_sphere, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::PickingModel::mesh_raycaster, Slic3r::GUI::PickingModel::model, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::Model::objects, Slic3r::GUI::GLGizmoBase::On, PI, Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), render_points(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::set_use_shift(), Slic3r::GUI::GLGizmoSlaBase::show_sla_supports(), and Slic3r::GUI::CommonGizmosDataPool::supports_clipper().
on_render_input_window()
void Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window (float x, float y, float bottom_limit) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    static float last_y = 0.0f;
    static float last_h = 0.0f;
    ModelObject* mo = m_c->selection_info()->model_object();
    if (! mo)
        return;
    bool first_run = true; // This is a hack to redraw the button when all points are removed,
                           // so it is not delayed until the background process finishes.
RENDER_AGAIN:
    //m_imgui->set_next_window_pos(x, y, ImGuiCond_Always);
    //const ImVec2 window_size(m_imgui->scaled(18.f, 16.f));
    //ImGui::SetNextWindowPos(ImVec2(x, y - std::max(0.f, y+window_size.y-bottom_limit) ));
    //ImGui::SetNextWindowSize(ImVec2(window_size));
    m_imgui->begin(get_name(), ImGuiWindowFlags_NoMove | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoCollapse);
    // adjust window position to avoid overlap the view toolbar
    float win_h = ImGui::GetWindowHeight();
    y = std::min(y, bottom_limit - win_h);
    ImGui::SetWindowPos(ImVec2(x, y), ImGuiCond_Always);
    if (last_h != win_h || last_y != y) {
        // ask canvas for another frame to render the window in the correct position
        m_imgui->set_requires_extra_frame();
        if (last_h != win_h)
            last_h = win_h;
        if (last_y != y)
            last_y = y;
    }
    // First calculate width of all the texts that are could possibly be shown. We will decide set the dialog width based on that:
    const float settings_sliders_left = std::max(m_imgui->calc_text_size(m_desc.at("minimal_distance")).x, m_imgui->calc_text_size(m_desc.at("points_density")).x) + m_imgui->scaled(1.f);
    const float clipping_slider_left = std::max(m_imgui->calc_text_size(m_desc.at("clipping_of_view")).x, m_imgui->calc_text_size(m_desc.at("reset_direction")).x) + m_imgui->scaled(1.5f);
    const float diameter_slider_left = m_imgui->calc_text_size(m_desc.at("head_diameter")).x + m_imgui->scaled(1.f);
    const float minimal_slider_width = m_imgui->scaled(4.f);
    const float buttons_width_approx = m_imgui->calc_text_size(m_desc.at("apply_changes")).x + m_imgui->calc_text_size(m_desc.at("discard_changes")).x + m_imgui->scaled(1.5f);
    const float lock_supports_width_approx = m_imgui->calc_text_size(m_desc.at("lock_supports")).x + m_imgui->scaled(2.f);
    float window_width = minimal_slider_width + std::max(std::max(settings_sliders_left, clipping_slider_left), diameter_slider_left);
    window_width = std::max(std::max(window_width, buttons_width_approx), lock_supports_width_approx);
    bool force_refresh = false;
    bool remove_selected = false;
    bool remove_all = false;
    if (m_editing_mode) {
        float diameter_upper_cap = static_cast<ConfigOptionFloat*>(wxGetApp().preset_bundle->sla_prints.get_edited_preset().config.option("support_pillar_diameter"))->value;
        if (m_new_point_head_diameter > diameter_upper_cap)
            m_new_point_head_diameter = diameter_upper_cap;
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("head_diameter"));
        ImGui::SameLine(diameter_slider_left);
        ImGui::PushItemWidth(window_width - diameter_slider_left);
        // Following is a nasty way to:
        //  - save the initial value of the slider before one starts messing with it
        //  - keep updating the head radius during sliding so it is continuosly refreshed in 3D scene
        //  - take correct undo/redo snapshot after the user is done with moving the slider
        float initial_value = m_new_point_head_diameter;
        m_imgui->slider_float("##head_diameter", &m_new_point_head_diameter, 0.1f, diameter_upper_cap, "%.1f");
        if (m_imgui->get_last_slider_status().clicked) {
            if (m_old_point_head_diameter == 0.f)
                m_old_point_head_diameter = initial_value;
        }
        if (m_imgui->get_last_slider_status().edited) {
            for (auto& cache_entry : m_editing_cache)
                if (cache_entry.selected)
                    cache_entry.support_point.head_front_radius = m_new_point_head_diameter / 2.f;
        }
        if (m_imgui->get_last_slider_status().deactivated_after_edit) {
            // momentarily restore the old value to take snapshot
            for (auto& cache_entry : m_editing_cache)
                if (cache_entry.selected)
                    cache_entry.support_point.head_front_radius = m_old_point_head_diameter / 2.f;
            float backup = m_new_point_head_diameter;
            m_new_point_head_diameter = m_old_point_head_diameter;
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Change point head diameter"));
            m_new_point_head_diameter = backup;
            for (auto& cache_entry : m_editing_cache)
                if (cache_entry.selected)
                    cache_entry.support_point.head_front_radius = m_new_point_head_diameter / 2.f;
            m_old_point_head_diameter = 0.f;
        }
        bool changed = m_lock_unique_islands;
        m_imgui->checkbox(m_desc.at("lock_supports"), m_lock_unique_islands);
        force_refresh |= changed != m_lock_unique_islands;
        m_imgui->disabled_begin(m_selection_empty);
        remove_selected = m_imgui->button(m_desc.at("remove_selected"));
        m_imgui->disabled_end();
        m_imgui->disabled_begin(m_editing_cache.empty());
        remove_all = m_imgui->button(m_desc.at("remove_all"));
        m_imgui->disabled_end();
        m_imgui->text(" "); // vertical gap
        if (m_imgui->button(m_desc.at("apply_changes"))) {
            editing_mode_apply_changes();
            force_refresh = true;
        }
        ImGui::SameLine();
        bool discard_changes = m_imgui->button(m_desc.at("discard_changes"));
        if (discard_changes) {
            editing_mode_discard_changes();
            force_refresh = true;
        }
    }
    else { // not in editing mode:
        m_imgui->disabled_begin(!is_input_enabled());
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("minimal_distance"));
        ImGui::SameLine(settings_sliders_left);
        ImGui::PushItemWidth(window_width - settings_sliders_left);
        std::vector<const ConfigOption*> opts = get_config_options({"support_points_density_relative", "support_points_minimal_distance"});
        float density = static_cast<const ConfigOptionInt*>(opts[0])->value;
        float minimal_point_distance = static_cast<const ConfigOptionFloat*>(opts[1])->value;
        m_imgui->slider_float("##minimal_point_distance", &minimal_point_distance, 0.f, 20.f, "%.f mm");
        bool slider_clicked = m_imgui->get_last_slider_status().clicked; // someone clicked the slider
        bool slider_edited = m_imgui->get_last_slider_status().edited; // someone is dragging the slider
        bool slider_released = m_imgui->get_last_slider_status().deactivated_after_edit; // someone has just released the slider
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("points_density"));
        ImGui::SameLine(settings_sliders_left);
        m_imgui->slider_float("##points_density", &density, 0.f, 200.f, "%.f %%");
        slider_clicked |= m_imgui->get_last_slider_status().clicked;
        slider_edited |= m_imgui->get_last_slider_status().edited;
        slider_released |= m_imgui->get_last_slider_status().deactivated_after_edit;
        if (slider_clicked) { // stash the values of the settings so we know what to revert to after undo
            m_minimal_point_distance_stash = minimal_point_distance;
            m_density_stash = density;
        }
        if (slider_edited) {
            mo->config.set("support_points_minimal_distance", minimal_point_distance);
            mo->config.set("support_points_density_relative", (int)density);
        }
        if (slider_released) {
            mo->config.set("support_points_minimal_distance", m_minimal_point_distance_stash);
            mo->config.set("support_points_density_relative", (int)m_density_stash);
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Support parameter change"));
            mo->config.set("support_points_minimal_distance", minimal_point_distance);
            mo->config.set("support_points_density_relative", (int)density);
            wxGetApp().obj_list()->update_and_show_object_settings_item();
        }
        bool generate = m_imgui->button(m_desc.at("auto_generate"));
        if (generate)
            auto_generate();
        ImGui::Separator();
        if (m_imgui->button(m_desc.at("manual_editing")))
            switch_to_editing_mode();
        m_imgui->disabled_end();
        m_imgui->disabled_begin(!is_input_enabled() || m_normal_cache.empty());
        remove_all = m_imgui->button(m_desc.at("remove_all"));
        m_imgui->disabled_end();
        // m_imgui->text("");
        // m_imgui->text(m_c->m_model_object->sla_points_status == sla::PointsStatus::NoPoints ? _(L("No points  (will be autogenerated)")) :
        //              (m_c->m_model_object->sla_points_status == sla::PointsStatus::AutoGenerated ? _(L("Autogenerated points (no modifications)")) :
        //              (m_c->m_model_object->sla_points_status == sla::PointsStatus::UserModified ? _(L("User-modified points")) :
        //              (m_c->m_model_object->sla_points_status == sla::PointsStatus::Generating ? _(L("Generation in progress...")) : "UNKNOWN STATUS"))));
    }
    // Following is rendered in both editing and non-editing mode:
    m_imgui->disabled_begin(!is_input_enabled());
    ImGui::Separator();
    if (m_c->object_clipper()->get_position() == 0.f) {
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("clipping_of_view"));
    }
    else {
        if (m_imgui->button(m_desc.at("reset_direction"))) {
            wxGetApp().CallAfter([this](){
                    m_c->object_clipper()->set_position_by_ratio(-1., false);
                });
        }
    }
    ImGui::SameLine(clipping_slider_left);
    ImGui::PushItemWidth(window_width - clipping_slider_left);
    float clp_dist = m_c->object_clipper()->get_position();
    if (m_imgui->slider_float("##clp_dist", &clp_dist, 0.f, 1.f, "%.2f"))
        m_c->object_clipper()->set_position_by_ratio(clp_dist, true);
    if (m_imgui->button("?")) {
        wxGetApp().CallAfter([]() {
            SlaGizmoHelpDialog help_dlg;
            help_dlg.ShowModal();
        });
    }
    m_imgui->disabled_end();
    m_imgui->end();
    if (remove_selected || remove_all) {
        force_refresh = false;
        m_parent.set_as_dirty();
        bool was_in_editing = m_editing_mode;
        if (! was_in_editing)
            switch_to_editing_mode();
        if (remove_all) {
            select_point(AllPoints);
            delete_selected_points(true); // true - delete regardless of locked status
        }
        if (remove_selected)
            delete_selected_points(false); // leave locked points
        if (! was_in_editing)
            editing_mode_apply_changes();
        if (first_run) {
            first_run = false;
            goto RENDER_AGAIN;
        }
    }
    if (force_refresh)
        m_parent.set_as_dirty();
}
References _L, ImGui::AlignTextToFramePadding(), AllPoints, auto_generate(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::GUI::ImGuiWrapper::checkbox(), Slic3r::GUI::ImGuiWrapper::LastSliderStatus::clicked, Slic3r::ModelObject::config, Slic3r::GUI::ImGuiWrapper::LastSliderStatus::deactivated_after_edit, delete_selected_points(), Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), Slic3r::GUI::ImGuiWrapper::LastSliderStatus::edited, editing_mode_apply_changes(), editing_mode_discard_changes(), Slic3r::GUI::ImGuiWrapper::end(), get_config_options(), Slic3r::GUI::ImGuiWrapper::get_last_slider_status(), Slic3r::GUI::GLGizmoBase::get_name(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), ImGui::GetWindowHeight(), ImGuiCond_Always, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, Slic3r::GUI::GLGizmoSlaBase::is_input_enabled(), Slic3r::GUI::GLGizmoBase::m_c, m_density_stash, m_desc, m_editing_cache, m_editing_mode, Slic3r::GUI::GLGizmoBase::m_imgui, m_lock_unique_islands, m_minimal_point_distance_stash, m_new_point_head_diameter, m_normal_cache, m_old_point_head_diameter, Slic3r::GUI::GLGizmoBase::m_parent, m_selection_empty, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::plater(), ImGui::PushItemWidth(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::scaled(), select_point(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), ImGui::Separator(), Slic3r::ModelConfig::set(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position_by_ratio(), Slic3r::GUI::ImGuiWrapper::set_requires_extra_frame(), ImGui::SetWindowPos(), Slic3r::GUI::ImGuiWrapper::slider_float(), switch_to_editing_mode(), Slic3r::GUI::ImGuiWrapper::text(), and ImVec2::x.
on_save()
void Slic3r::GUI::GLGizmoSlaSupports::on_save (cereal::BinaryOutputArchive & ar) const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar(m_new_point_head_diameter,
       m_normal_cache,
       m_editing_cache,
       m_selection_empty
    );
}
References m_editing_cache, m_new_point_head_diameter, m_normal_cache, and m_selection_empty.
on_set_hover_id()
void Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id () inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
        if (! m_editing_mode || (int)m_editing_cache.size() <= m_hover_id)
            m_hover_id = -1;
    }
References m_editing_cache, m_editing_mode, and Slic3r::GUI::GLGizmoBase::m_hover_id.
on_set_state()
void Slic3r::GUI::GLGizmoSlaSupports::on_set_state () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_state == On) { // the gizmo was just turned on
        // Set default head diameter from config.
        const DynamicPrintConfig& cfg = wxGetApp().preset_bundle->sla_prints.get_edited_preset().config;
        m_new_point_head_diameter = static_cast<const ConfigOptionFloat*>(cfg.option("support_head_front_diameter"))->value;
    }
    else {
        if (m_editing_mode && unsaved_changes() && on_is_activable()) {
            if (!ask_about_changes([this]() { editing_mode_apply_changes(); },
                [this]() { editing_mode_discard_changes(); })) {
                m_state = On;
                return;
            }
        }
        else {
            // we are actually shutting down
            disable_editing_mode(); // so it is not active next time the gizmo opens
            m_old_mo_id = -1;
        }
        m_parent.post_event(SimpleEvent(EVT_GLCANVAS_FORCE_UPDATE));
        m_c->instances_hider()->set_hide_full_scene(false);
        m_c->selection_info()->set_use_shift(false); // see top of on_render for details
    }
}
References ask_about_changes(), disable_editing_mode(), editing_mode_apply_changes(), editing_mode_discard_changes(), Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::GLGizmoBase::m_c, m_editing_mode, m_new_point_head_diameter, m_old_mo_id, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, on_is_activable(), Slic3r::ConfigBase::option(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::set_hide_full_scene(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::set_use_shift(), and unsaved_changes().
on_start_dragging()
void Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_hover_id != -1) {
        select_point(NoPoints);
        select_point(m_hover_id);
        m_point_before_drag = m_editing_cache[m_hover_id];
    }
    else
        m_point_before_drag = CacheEntry();
}
References m_editing_cache, Slic3r::GUI::GLGizmoBase::m_hover_id, m_point_before_drag, NoPoints, and select_point().
on_stop_dragging()
void Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_hover_id != -1) {
        CacheEntry backup = m_editing_cache[m_hover_id];
        if (m_point_before_drag.support_point.pos != Vec3f::Zero() // some point was touched
         && backup.support_point.pos != m_point_before_drag.support_point.pos) // and it was moved, not just selected
        {
            m_editing_cache[m_hover_id] = m_point_before_drag;
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Move support point"));
            m_editing_cache[m_hover_id] = backup;
        }
    }
    m_point_before_drag = CacheEntry();
}
References _L, m_editing_cache, Slic3r::GUI::GLGizmoBase::m_hover_id, m_point_before_drag, Slic3r::GUI::plater(), Slic3r::sla::SupportPoint::pos, and Slic3r::GUI::GLGizmoSlaSupports::CacheEntry::support_point.
on_unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoSlaSupports::on_unregister_raycasters_for_picking () override private virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    unregister_point_raycasters_for_picking();
    unregister_volume_raycasters_for_picking();
}
References unregister_point_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking().
register_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].register_raycasters_for_picking((m_group_id >= 0) ? m_group_id : i);
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking().
register_point_raycasters_for_picking()
void Slic3r::GUI::GLGizmoSlaSupports::register_point_raycasters_for_picking () private
{
    assert(m_point_raycasters.empty());
    if (m_editing_mode && !m_editing_cache.empty()) {
        for (size_t i = 0; i < m_editing_cache.size(); ++i) {
            m_point_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, i, *m_sphere.mesh_raycaster, Transform3d::Identity()),
                m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, i, *m_cone.mesh_raycaster, Transform3d::Identity()));
        }
        update_point_raycasters_for_picking_transform();
    }
}
References Slic3r::GUI::GLCanvas3D::add_raycaster_for_picking(), Slic3r::GUI::SceneRaycaster::Gizmo, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), m_cone, m_editing_cache, m_editing_mode, Slic3r::GUI::GLGizmoBase::m_parent, m_point_raycasters, m_sphere, Slic3r::GUI::PickingModel::mesh_raycaster, and update_point_raycasters_for_picking_transform().
Referenced by data_changed(), delete_selected_points(), gizmo_event(), on_register_raycasters_for_picking(), and switch_to_editing_mode().
register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking () inline inherited
{ register_grabbers_for_picking(); on_register_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_register_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_register_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
register_volume_raycasters_for_picking()
void Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking () protected inherited
{
    for (size_t i = 0; i < m_volumes.volumes.size(); ++i) {
        const GLVolume* v = m_volumes.volumes[i];
        if (!v->is_sla_pad() && !v->is_sla_support())
            m_volume_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, VOLUME_RAYCASTERS_BASE_ID + (int)i, *v->mesh_raycaster, v->world_matrix()));
    }
}
References Slic3r::GUI::GLCanvas3D::add_raycaster_for_picking(), Slic3r::GUI::SceneRaycaster::Gizmo, Slic3r::GLVolume::is_sla_pad(), Slic3r::GLVolume::is_sla_support(), Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoSlaBase::m_volume_raycasters, Slic3r::GUI::GLGizmoSlaBase::m_volumes, Slic3r::GLVolume::mesh_raycaster, Slic3r::GUI::VOLUME_RAYCASTERS_BASE_ID, Slic3r::GLVolumeCollection::volumes, and Slic3r::GLVolume::world_matrix().
Referenced by Slic3r::GUI::GLGizmoHollow::on_register_raycasters_for_picking(), on_register_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
reload_cache()
void Slic3r::GUI::GLGizmoSlaSupports::reload_cache () private
{
    const ModelObject* mo = m_c->selection_info()->model_object();
    m_normal_cache.clear();
    if (mo->sla_points_status == sla::PointsStatus::AutoGenerated || mo->sla_points_status == sla::PointsStatus::Generating)
        get_data_from_backend();
    else
        for (const sla::SupportPoint& point : mo->sla_support_points)
            m_normal_cache.emplace_back(point);
}
References Slic3r::sla::AutoGenerated, Slic3r::sla::Generating, get_data_from_backend(), Slic3r::GUI::GLGizmoBase::m_c, m_normal_cache, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::ModelObject::sla_points_status, and Slic3r::ModelObject::sla_support_points.
Referenced by data_changed().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ on_render(); }
References Slic3r::GUI::GLGizmoBase::on_render().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_render().
render_grabbers() [1/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
}
References Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointType >::size().
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    render_grabbers(0, m_grabbers.size() - 1, size, false);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [3/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (size_t first, size_t last, float size, bool force_hover) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    glsafe(::glDisable(GL_CULL_FACE));
    for (size_t i = first; i <= last; ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(force_hover ? true : m_hover_id == (int)i, size);
    }
    glsafe(::glEnable(GL_CULL_FACE));
    shader->stop_using();
}
References glsafe, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // imgui windows that don't have an initial size needs to be processed once to get one
        // and are not rendered in the first frame
        // so, we forces to render another frame the first time the imgui window is shown
        // https://github.com/ocornut/imgui/issues/2949
        m_parent.set_as_dirty();
        m_parent.request_extra_frame();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), Slic3r::GUI::GLCanvas3D::request_extra_frame(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
render_points()
void Slic3r::GUI::GLGizmoSlaSupports::render_points (const Selection & selection) private
{
    const size_t cache_size = m_editing_mode ? m_editing_cache.size() : m_normal_cache.size();
    const bool has_points = (cache_size != 0);
    if (!has_points)
        return;
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    ScopeGuard guard([shader]() { shader->stop_using(); });
    auto *inst = m_c->selection_info()->model_instance();
    if (!inst)
        return;
    double shift_z = m_c->selection_info()->print_object()->get_current_elevation();
    Transform3d trafo = inst->get_transformation().get_matrix();
    trafo.translation()(2) += shift_z;
    const Geometry::Transformation transformation{trafo};
    const Transform3d instance_scaling_matrix_inverse = transformation.get_scaling_factor_matrix().inverse();
    const Camera& camera = wxGetApp().plater()->get_camera();
    const Transform3d& view_matrix = camera.get_view_matrix();
    shader->set_uniform("projection_matrix", camera.get_projection_matrix());
    ColorRGBA render_color;
    for (size_t i = 0; i < cache_size; ++i) {
        const sla::SupportPoint& support_point = m_editing_mode ? m_editing_cache[i].support_point : m_normal_cache[i];
        const bool point_selected = m_editing_mode ? m_editing_cache[i].selected : false;
        const bool clipped = is_mesh_point_clipped(support_point.pos.cast<double>());
        if (i < m_point_raycasters.size()) {
            m_point_raycasters[i].first->set_active(!clipped);
            m_point_raycasters[i].second->set_active(!clipped);
        }
        if (clipped)
            continue;
        // First decide about the color of the point.
        if (size_t(m_hover_id) == i && m_editing_mode) // ignore hover state unless editing mode is active
            render_color = { 0.f, 1.f, 1.f, 1.f };
        else { // neigher hover nor picking
            bool supports_new_island = m_lock_unique_islands && support_point.is_new_island;
            if (m_editing_mode) {
                if (point_selected)
                    render_color = { 1.f, 0.3f, 0.3f, 1.f};
                else
                    if (supports_new_island)
                        render_color = { 0.3f, 0.3f, 1.f, 1.f };
                    else
                        render_color = { 0.7f, 0.7f, 0.7f, 1.f };
            }
            else
                render_color = { 0.5f, 0.5f, 0.5f, 1.f };
        }
        m_cone.model.set_color(render_color);
        m_sphere.model.set_color(render_color);
        shader->set_uniform("emission_factor", 0.5f);
        // Inverse matrix of the instance scaling is applied so that the mark does not scale with the object.
        const Transform3d support_matrix = Geometry::translation_transform(support_point.pos.cast<double>()) * instance_scaling_matrix_inverse;
        if (transformation.is_left_handed())
            glsafe(::glFrontFace(GL_CW));
        // Matrices set, we can render the point mark now.
        // If in editing mode, we'll also render a cone pointing to the sphere.
        if (m_editing_mode) {
            // in case the normal is not yet cached, find and cache it
            if (m_editing_cache[i].normal == Vec3f::Zero())
                m_c->raycaster()->raycaster()->get_closest_point(m_editing_cache[i].support_point.pos, &m_editing_cache[i].normal);
            Eigen::Quaterniond q;
            q.setFromTwoVectors(Vec3d::UnitZ(), instance_scaling_matrix_inverse * m_editing_cache[i].normal.cast<double>());
            const Eigen::AngleAxisd aa(q);
            const Transform3d model_matrix = transformation.get_matrix() * support_matrix * Transform3d(aa.toRotationMatrix()) *
                Geometry::translation_transform((CONE_HEIGHT + support_point.head_front_radius * RenderPointScale) * Vec3d::UnitZ()) *
                Geometry::rotation_transform({ double(PI), 0.0, 0.0 }) * Geometry::scale_transform({ CONE_RADIUS, CONE_RADIUS, CONE_HEIGHT });
            shader->set_uniform("view_model_matrix", view_matrix * model_matrix);
            const Matrix3d view_normal_matrix = view_matrix.matrix().block(0, 0, 3, 3) * model_matrix.matrix().block(0, 0, 3, 3).inverse().transpose();
            shader->set_uniform("view_normal_matrix", view_normal_matrix);
            m_cone.model.render();
        }
        const double radius = (double)support_point.head_front_radius * RenderPointScale;
        const Transform3d model_matrix = transformation.get_matrix() * support_matrix * Geometry::scale_transform(radius);
        shader->set_uniform("view_model_matrix", view_matrix * model_matrix);
        const Matrix3d view_normal_matrix = view_matrix.matrix().block(0, 0, 3, 3) * model_matrix.matrix().block(0, 0, 3, 3).inverse().transpose();
        shader->set_uniform("view_normal_matrix", view_normal_matrix);
        m_sphere.model.render();
        if (transformation.is_left_handed())
            glsafe(::glFrontFace(GL_CCW));
    }
}
References CONE_HEIGHT, CONE_RADIUS, Slic3r::GUI::MeshRaycaster::get_closest_point(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), glsafe, Slic3r::sla::SupportPoint::head_front_radius, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), is_mesh_point_clipped(), Slic3r::sla::SupportPoint::is_new_island, Slic3r::GUI::GLGizmoBase::m_c, m_cone, m_editing_cache, m_editing_mode, Slic3r::GUI::GLGizmoBase::m_hover_id, m_lock_unique_islands, m_normal_cache, m_point_raycasters, m_sphere, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::PickingModel::model, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_instance(), PI, Slic3r::sla::SupportPoint::pos, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycaster(), Slic3r::GUI::GLModel::render(), RenderPointScale, Slic3r::Geometry::rotation_transform(), Slic3r::Geometry::scale_transform(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Eigen::AngleAxis< _Scalar >::toRotationMatrix(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation(), and Slic3r::Geometry::translation_transform().
Referenced by on_render().
render_volumes()
void Slic3r::GUI::GLGizmoSlaBase::render_volumes () protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light_clip");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.0f);
    const Camera& camera = wxGetApp().plater()->get_camera();
    ClippingPlane clipping_plane = (m_c->object_clipper()->get_position() == 0.0) ? ClippingPlane::ClipsNothing() : *m_c->object_clipper()->get_clipping_plane();
    if (m_c->object_clipper()->get_position() != 0.0)
        clipping_plane.set_normal(-clipping_plane.get_normal());
    else
        // on Linux the clipping plane does not work when using DBL_MAX
        clipping_plane.set_offset(FLT_MAX);
    m_volumes.set_clipping_plane(clipping_plane.get_data());
    for (GLVolume* v : m_volumes.volumes) {
        v->is_active = m_show_sla_supports || (!v->is_sla_pad() && !v->is_sla_support());
    }
    m_volumes.render(GLVolumeCollection::ERenderType::Opaque, true, camera.get_view_matrix(), camera.get_projection_matrix());
    shader->stop_using();
}
References Slic3r::GUI::ClippingPlane::ClipsNothing(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::GUI::ClippingPlane::get_data(), Slic3r::GUI::ClippingPlane::get_normal(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoSlaBase::m_show_sla_supports, Slic3r::GUI::GLGizmoSlaBase::m_volumes, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GLVolumeCollection::Opaque, Slic3r::GLVolumeCollection::render(), Slic3r::GLVolumeCollection::set_clipping_plane(), Slic3r::GUI::ClippingPlane::set_normal(), Slic3r::GUI::ClippingPlane::set_offset(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::GLGizmoHollow::on_render(), and on_render().
reslice_until_step()
void Slic3r::GUI::GLGizmoSlaBase::reslice_until_step (SLAPrintObjectStep step, bool postpone_error_messages = false) inherited
{
    wxGetApp().CallAfter([this, step, postpone_error_messages]() {
        if (m_c->selection_info())
            wxGetApp().plater()->reslice_SLA_until_step(step, *m_c->selection_info()->model_object(), postpone_error_messages);
        else {
            const Selection& selection = m_parent.get_selection();
            const int object_idx = selection.get_object_idx();
            if (object_idx >= 0 && !selection.is_wipe_tower())
                wxGetApp().plater()->reslice_SLA_until_step(step, *wxGetApp().plater()->model().objects[object_idx], postpone_error_messages);
        }
    });
}
References Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_wipe_tower(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::plater(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by auto_generate(), Slic3r::GUI::GLGizmoHollow::data_changed(), data_changed(), editing_mode_apply_changes(), and Slic3r::GUI::GLGizmoHollow::on_render_input_window().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
select_point()
void Slic3r::GUI::GLGizmoSlaSupports::select_point (int i) private
{
    if (! m_editing_mode) {
        std::cout << "DEBUGGING: select_point called when out of editing mode!" << std::endl;
        std::abort();
    }
    if (i == AllPoints || i == NoPoints) {
        for (auto& point_and_selection : m_editing_cache)
            point_and_selection.selected = ( i == AllPoints );
        m_selection_empty = (i == NoPoints);
        if (i == AllPoints && !m_editing_cache.empty())
            m_new_point_head_diameter = m_editing_cache[0].support_point.head_front_radius * 2.f;
    }
    else {
        m_editing_cache[i].selected = true;
        m_selection_empty = false;
        m_new_point_head_diameter = m_editing_cache[i].support_point.head_front_radius * 2.f;
    }
}
References AllPoints, m_editing_cache, m_editing_mode, m_new_point_head_diameter, m_selection_empty, and NoPoints.
Referenced by delete_selected_points(), editing_mode_discard_changes(), gizmo_event(), on_render_input_window(), on_start_dragging(), and switch_to_editing_mode().
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c.
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by Slic3r::GUI::GLGizmoCut3D::process_cut_line(), and Slic3r::GUI::GLGizmoSimplify::request_rerender().
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    // do not change hover id during dragging
    assert(!m_dragging);
    // allow empty grabbers when not using grabbers but use hover_id - flatten, rotate
//    if (!m_grabbers.empty() && id >= (int) m_grabbers.size())
//        return;
    m_hover_id = id;
    on_set_hover_id();
}
References Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLGizmoEmboss::on_set_state().
show_sla_supports()
void Slic3r::GUI::GLGizmoSlaBase::show_sla_supports (bool show) inline protected inherited
{ m_show_sla_supports = show; }
References Slic3r::GUI::GLGizmoSlaBase::m_show_sla_supports.
Referenced by GLGizmoSlaSupports(), on_render(), and Slic3r::GUI::GLGizmoHollow::on_render_input_window().
switch_to_editing_mode()
void Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode () private
{
    wxGetApp().plater()->enter_gizmos_stack();
    m_editing_mode = true;
    m_editing_cache.clear();
    for (const sla::SupportPoint& sp : m_normal_cache)
        m_editing_cache.emplace_back(sp);
    select_point(NoPoints);
    register_point_raycasters_for_picking();
    m_parent.set_as_dirty();
}
References m_editing_cache, m_editing_mode, m_normal_cache, Slic3r::GUI::GLGizmoBase::m_parent, NoPoints, register_point_raycasters_for_picking(), select_point(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
Referenced by gizmo_event(), and on_render_input_window().
unproject_on_mesh()
bool Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh (const Vec2d & mouse_pos, std::pair< Vec3f, Vec3f > & pos_and_normal) protected inherited
{
    if (m_c->raycaster()->raycasters().size() != 1)
        return false;
    if (!m_c->raycaster()->raycaster())
        return false;
    if (m_volumes.volumes.empty())
        return false;
    auto *inst = m_c->selection_info()->model_instance();
    if (!inst)
        return false;
    Transform3d trafo = m_volumes.volumes.front()->world_matrix();
    if (m_c->selection_info() && m_c->selection_info()->print_object()) {
        double shift_z = m_c->selection_info()->print_object()->get_current_elevation();
        trafo = inst->get_transformation().get_matrix();
        trafo.translation()(2) += shift_z;
    }
    // The raycaster query
    Vec3f hit;
    Vec3f normal;
    if (m_c->raycaster()->raycaster()->unproject_on_mesh(
        mouse_pos,
        trafo/*m_volumes.volumes.front()->world_matrix()*/,
        wxGetApp().plater()->get_camera(),
        hit,
        normal,
        m_c->object_clipper()->get_position() != 0.0 ? m_c->object_clipper()->get_clipping_plane() : nullptr)) {
        // Return both the point and the facet normal.
        pos_and_normal = std::make_pair(hit, normal);
        return true;
    }
    return false;
}
References Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoSlaBase::m_volumes, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_instance(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::plater(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycasters(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation(), Slic3r::GUI::MeshRaycaster::unproject_on_mesh(), and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::GLGizmoHollow::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoHollow::on_dragging(), and on_dragging().
unregister_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].unregister_raycasters_for_picking();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers.
Referenced by Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking().
unregister_point_raycasters_for_picking()
void Slic3r::GUI::GLGizmoSlaSupports::unregister_point_raycasters_for_picking () private
{
    for (size_t i = 0; i < m_point_raycasters.size(); ++i) {
        m_parent.remove_raycasters_for_picking(SceneRaycaster::EType::Gizmo, i);
    }
    m_point_raycasters.clear();
}
References Slic3r::GUI::SceneRaycaster::Gizmo, Slic3r::GUI::GLGizmoBase::m_parent, m_point_raycasters, and Slic3r::GUI::GLCanvas3D::remove_raycasters_for_picking().
Referenced by delete_selected_points(), disable_editing_mode(), gizmo_event(), and on_unregister_raycasters_for_picking().
unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking () inline inherited
{ unregister_grabbers_for_picking(); on_unregister_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
unregister_volume_raycasters_for_picking()
void Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking () protected inherited
{
    for (size_t i = 0; i < m_volume_raycasters.size(); ++i) {
        m_parent.remove_raycasters_for_picking(SceneRaycaster::EType::Gizmo, VOLUME_RAYCASTERS_BASE_ID + (int)i);
    }
    m_volume_raycasters.clear();
}
References Slic3r::GUI::SceneRaycaster::Gizmo, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoSlaBase::m_volume_raycasters, Slic3r::GUI::GLCanvas3D::remove_raycasters_for_picking(), and Slic3r::GUI::VOLUME_RAYCASTERS_BASE_ID.
Referenced by Slic3r::GUI::GLGizmoHollow::on_unregister_raycasters_for_picking(), on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
unsaved_changes()
bool Slic3r::GUI::GLGizmoSlaSupports::unsaved_changes () const private
{
    if (m_editing_cache.size() != m_normal_cache.size())
        return true;
    for (size_t i=0; i<m_editing_cache.size(); ++i)
        if (m_editing_cache[i].support_point != m_normal_cache[i])
            return true;
    return false;
}
References m_editing_cache, and m_normal_cache.
Referenced by editing_mode_apply_changes(), and on_set_state().
unselect_point()
void Slic3r::GUI::GLGizmoSlaSupports::unselect_point (int i) private
{
    if (! m_editing_mode) {
        std::cout << "DEBUGGING: unselect_point called when out of editing mode!" << std::endl;
        std::abort();
    }
    m_editing_cache[i].selected = false;
    m_selection_empty = true;
    for (const CacheEntry& ce : m_editing_cache) {
        if (ce.selected) {
            m_selection_empty = false;
            break;
        }
    }
}
References m_editing_cache, m_editing_mode, and m_selection_empty.
Referenced by gizmo_event().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
update_point_raycasters_for_picking_transform()
void Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform () private
{
    if (m_editing_cache.empty())
        return;
    assert(!m_point_raycasters.empty());
    const GLVolume* vol = m_parent.get_selection().get_first_volume();
    Geometry::Transformation transformation(vol->world_matrix());
    auto *inst = m_c->selection_info()->model_instance();
    if (inst && m_c->selection_info() && m_c->selection_info()->print_object()) {
        double shift_z = m_c->selection_info()->print_object()->get_current_elevation();
        auto trafo = inst->get_transformation().get_matrix();
        trafo.translation()(2) += shift_z;
        transformation.set_matrix(trafo);
    }
    const Transform3d instance_scaling_matrix_inverse = transformation.get_scaling_factor_matrix().inverse();
    for (size_t i = 0; i < m_editing_cache.size(); ++i) {
        const Transform3d support_matrix = Geometry::translation_transform(m_editing_cache[i].support_point.pos.cast<double>()) * instance_scaling_matrix_inverse;
        if (m_editing_cache[i].normal == Vec3f::Zero())
            m_c->raycaster()->raycaster()->get_closest_point(m_editing_cache[i].support_point.pos, &m_editing_cache[i].normal);
        Eigen::Quaterniond q;
        q.setFromTwoVectors(Vec3d::UnitZ(), instance_scaling_matrix_inverse * m_editing_cache[i].normal.cast<double>());
        const Eigen::AngleAxisd aa(q);
        const Transform3d cone_matrix = transformation.get_matrix() * support_matrix * Transform3d(aa.toRotationMatrix()) *
            Geometry::assemble_transform((CONE_HEIGHT + m_editing_cache[i].support_point.head_front_radius * RenderPointScale) * Vec3d::UnitZ(),
                Vec3d(PI, 0.0, 0.0), Vec3d(CONE_RADIUS, CONE_RADIUS, CONE_HEIGHT));
        m_point_raycasters[i].second->set_transform(cone_matrix);
        const double radius = (double)m_editing_cache[i].support_point.head_front_radius * RenderPointScale;
        const Transform3d sphere_matrix = transformation.get_matrix() * support_matrix * Geometry::scale_transform(radius);
        m_point_raycasters[i].first->set_transform(sphere_matrix);
    }
}
References Slic3r::Geometry::assemble_transform(), CONE_HEIGHT, CONE_RADIUS, Slic3r::GUI::MeshRaycaster::get_closest_point(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::Selection::get_first_volume(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_scaling_factor_matrix(), Slic3r::GUI::GLCanvas3D::get_selection(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::GUI::GLGizmoBase::m_c, m_editing_cache, Slic3r::GUI::GLGizmoBase::m_parent, m_point_raycasters, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_instance(), PI, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycaster(), RenderPointScale, Slic3r::Geometry::scale_transform(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::Geometry::Transformation::set_matrix(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), Eigen::AngleAxis< _Scalar >::toRotationMatrix(), Slic3r::Geometry::translation_transform(), and Slic3r::GLVolume::world_matrix().
Referenced by data_changed(), and register_point_raycasters_for_picking().
update_volumes()
void Slic3r::GUI::GLGizmoSlaBase::update_volumes () protected inherited
{
    m_volumes.clear();
    unregister_volume_raycasters_for_picking();
    const ModelObject* mo = m_c->selection_info()->model_object();
    if (mo == nullptr)
        return;
    const SLAPrintObject* po = m_c->selection_info()->print_object();
    if (po == nullptr)
        return;
    m_input_enabled = false;
    TriangleMesh backend_mesh;
    std::shared_ptr<const indexed_triangle_set> preview_mesh_ptr = po->get_mesh_to_print();
    if (preview_mesh_ptr != nullptr)
        backend_mesh = TriangleMesh(*preview_mesh_ptr);
    if (!backend_mesh.empty()) {
        auto last_comp_step = static_cast<int>(po->last_completed_step());
        if (last_comp_step == slaposCount)
            last_comp_step = -1;
        m_input_enabled = last_comp_step >= m_min_sla_print_object_step || po->model_object()->sla_points_status == sla::PointsStatus::UserModified;
        const int object_idx   = m_parent.get_selection().get_object_idx();
        const int instance_idx = m_parent.get_selection().get_instance_idx();
        const Geometry::Transformation& inst_trafo = po->model_object()->instances[instance_idx]->get_transformation();
        const double current_elevation = po->get_current_elevation();
        auto add_volume = [this, object_idx, instance_idx, &inst_trafo, current_elevation](const TriangleMesh& mesh, int volume_id, bool add_mesh_raycaster = false) {
            GLVolume* volume = m_volumes.volumes.emplace_back(new GLVolume());
            volume->model.init_from(mesh);
            volume->set_instance_transformation(inst_trafo);
            volume->set_sla_shift_z(current_elevation);
            if (add_mesh_raycaster)
                volume->mesh_raycaster = std::make_unique<GUI::MeshRaycaster>(mesh);
            if (m_input_enabled)
                volume->selected = true; // to set the proper color
            else
                volume->set_color(DISABLED_COLOR);
            volume->composite_id = GLVolume::CompositeID(object_idx, volume_id, instance_idx);
        };
        const Transform3d po_trafo_inverse = po->trafo().inverse();
        // main mesh
        backend_mesh.transform(po_trafo_inverse);
        add_volume(backend_mesh, 0, true);
        // supports mesh
        TriangleMesh supports_mesh = po->support_mesh();
        if (!supports_mesh.empty()) {
            supports_mesh.transform(po_trafo_inverse);
            add_volume(supports_mesh, -int(slaposSupportTree));
        }
        // pad mesh
        TriangleMesh pad_mesh = po->pad_mesh();
        if (!pad_mesh.empty()) {
            pad_mesh.transform(po_trafo_inverse);
            add_volume(pad_mesh, -int(slaposPad));
        }
    }
    if (m_volumes.volumes.empty()) {
        // No valid mesh found in the backend. Use the selection to duplicate the volumes
        const Selection& selection = m_parent.get_selection();
        const Selection::IndicesList& idxs = selection.get_volume_idxs();
        for (unsigned int idx : idxs) {
            const GLVolume* v = selection.get_volume(idx);
            if (!v->is_modifier) {
                m_volumes.volumes.emplace_back(new GLVolume());
                GLVolume* new_volume = m_volumes.volumes.back();
                const TriangleMesh& mesh = mo->volumes[v->volume_idx()]->mesh();
                new_volume->model.init_from(mesh);
                new_volume->set_instance_transformation(v->get_instance_transformation());
                new_volume->set_volume_transformation(v->get_volume_transformation());
                new_volume->set_sla_shift_z(v->get_sla_shift_z());
                new_volume->set_color(DISABLED_COLOR);
                new_volume->mesh_raycaster = std::make_unique<GUI::MeshRaycaster>(mesh);
            }
        }
    }
    register_volume_raycasters_for_picking();
}
References Slic3r::GLVolumeCollection::clear(), Slic3r::GUI::DISABLED_COLOR, Slic3r::TriangleMesh::empty(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GLVolume::get_instance_transformation(), Slic3r::SLAPrintObject::get_mesh_to_print(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GLVolume::get_sla_shift_z(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GLVolume::get_volume_transformation(), Slic3r::GUI::GLModel::init_from(), Slic3r::ModelObject::instances, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::last_completed_step(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoSlaBase::m_input_enabled, Slic3r::GUI::GLGizmoSlaBase::m_min_sla_print_object_step, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoSlaBase::m_volumes, Slic3r::GLVolume::mesh_raycaster, Slic3r::GLVolume::model, Slic3r::PrintObjectBase::model_object(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::SLAPrintObject::pad_mesh(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GLVolume::set_color(), Slic3r::GLVolume::set_instance_transformation(), Slic3r::GLVolume::set_sla_shift_z(), Slic3r::GLVolume::set_volume_transformation(), Slic3r::ModelObject::sla_points_status, Slic3r::slaposCount, Slic3r::slaposPad, Slic3r::slaposSupportTree, Slic3r::SLAPrintObject::support_mesh(), Slic3r::SLAPrintObject::trafo(), Slic3r::TriangleMesh::transform(), Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking(), Slic3r::sla::UserModified, Slic3r::GLVolume::volume_idx(), Slic3r::ModelObject::volumes, and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::GLGizmoHollow::data_changed(), and data_changed().
use_grabbers()
bool Slic3r::GUI::GLGizmoBase::use_grabbers (const wxMouseEvent & mouse_event) protected inherited
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
Parameters
mouse_event Keep information about mouse click
Returns
same as on_mouse
{
    bool is_dragging_finished = false;
    if (mouse_event.Moving()) {
        // it should not happen but for sure
        assert(!m_dragging);
        if (m_dragging) is_dragging_finished = true;
        else return false;
    }
    if (mouse_event.LeftDown()) {
        Selection &selection = m_parent.get_selection();
        if (!selection.is_empty() && m_hover_id != -1 /* &&
            (m_grabbers.empty() || m_hover_id < static_cast<int>(m_grabbers.size()))*/) {
            selection.setup_cache();
            m_dragging = true;
            for (auto &grabber : m_grabbers) grabber.dragging = false;
//            if (!m_grabbers.empty() && m_hover_id < int(m_grabbers.size()))
//                m_grabbers[m_hover_id].dragging = true;
            on_start_dragging();
            // Let the plater know that the dragging started
            m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_STARTED));
            m_parent.set_as_dirty();
            return true;
        }
    } else if (m_dragging) {
        // when mouse cursor leave window than finish actual dragging operation
        bool is_leaving = mouse_event.Leaving();
        if (mouse_event.Dragging()) {
            Point      mouse_coord(mouse_event.GetX(), mouse_event.GetY());
            auto       ray = m_parent.mouse_ray(mouse_coord);
            UpdateData data(ray, mouse_coord);
            on_dragging(data);
            wxGetApp().obj_manipul()->set_dirty();
            m_parent.set_as_dirty();
            return true;
        }
        else if (mouse_event.LeftUp() || is_leaving || is_dragging_finished) {
            do_stop_dragging(is_leaving);
            return true;
        }
    }
    return false;
}
References Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_ray(), Slic3r::GUI::GLGizmoBase::on_dragging(), Slic3r::GUI::GLGizmoBase::on_start_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::Selection::setup_cache().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_mouse(), Slic3r::GUI::GLGizmoRotate::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), on_mouse(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation().
volumes()
const GLVolumeCollection & Slic3r::GUI::GLGizmoSlaBase::volumes () const inline protected inherited
{ return m_volumes; }
References Slic3r::GUI::GLGizmoSlaBase::m_volumes.
wants_enter_leave_snapshots()
bool Slic3r::GUI::GLGizmoSlaSupports::wants_enter_leave_snapshots () const inline override virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return true; }
Member Data Documentation
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
GRABBER_ELEMENTS_MAX_COUNT
const unsigned int Slic3r::GUI::GLGizmoBase::GRABBER_ELEMENTS_MAX_COUNT = 7 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c { nullptr } protected inherited
Referenced by Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoFdmSupports::auto_generate(), auto_generate(), Slic3r::GUI::GLGizmoCut3D::check_and_update_connectors_state(), Slic3r::GUI::GLGizmoCut3D::data_changed(), Slic3r::GUI::GLGizmoFdmSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), data_changed(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), Slic3r::GUI::GLGizmoCut3D::dragging_connector(), editing_mode_apply_changes(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), Slic3r::GUI::GLGizmoHollow::get_config_options(), get_config_options(), get_data_from_backend(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), has_backend_supports(), Slic3r::GUI::GLGizmoCut3D::has_valid_contour(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoCut3D::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), on_render(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::GLGizmoCut3D::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoHollow::reload_cache(), reload_cache(), Slic3r::GUI::GLGizmoCut3D::render_clipper_cut(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoHollow::render_points(), render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::GLGizmoCut3D::reset_connectors(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut3D::update_bb(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_cone
PickingModel Slic3r::GUI::GLGizmoSlaSupports::m_cone private
Referenced by on_render(), register_point_raycasters_for_picking(), and render_points().
m_density_stash
float Slic3r::GUI::GLGizmoSlaSupports::m_density_stash = 0.f private
Referenced by on_render_input_window().
m_desc
std::map<std::string, wxString> Slic3r::GUI::GLGizmoSlaSupports::m_desc private
Referenced by on_init(), and on_render_input_window().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty { false } private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging { false } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::GLGizmoBase::set_hover_id(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_editing_cache
std::vector<CacheEntry> Slic3r::GUI::GLGizmoSlaSupports::m_editing_cache mutable private
Referenced by delete_selected_points(), editing_mode_apply_changes(), gizmo_event(), on_dragging(), on_load(), on_render_input_window(), on_save(), on_set_hover_id(), on_start_dragging(), on_stop_dragging(), register_point_raycasters_for_picking(), render_points(), select_point(), switch_to_editing_mode(), unsaved_changes(), unselect_point(), and update_point_raycasters_for_picking_transform().
m_editing_mode
bool Slic3r::GUI::GLGizmoSlaSupports::m_editing_mode = false private
Referenced by delete_selected_points(), disable_editing_mode(), editing_mode_discard_changes(), gizmo_event(), is_in_editing_mode(), on_dragging(), on_render(), on_render_input_window(), on_set_hover_id(), on_set_state(), register_point_raycasters_for_picking(), render_points(), select_point(), switch_to_editing_mode(), and unselect_point().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render { true } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoRotate::disable_grabber(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoRotate::enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLGizmoRotate::start_dragging(), Slic3r::GUI::GLGizmoRotate::stop_dragging(), Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate::GLGizmoRotate(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), and Slic3r::GUI::GLGizmoRotate::set_group_id().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id { -1 } protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_xy(), Slic3r::GUI::GLGizmoCut3D::dragging_grabber_z(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLGizmoCut3D::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoCut3D::is_selection_changed(), Slic3r::GUI::GLGizmoCut3D::on_dragging(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_dragging(), Slic3r::GUI::GLGizmoScale3D::on_dragging(), on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), on_set_hover_id(), Slic3r::GUI::GLGizmoCut3D::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), on_start_dragging(), Slic3r::GUI::GLGizmoCut3D::on_stop_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoHollow::render_points(), render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename().
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), Slic3r::GUI::GLGizmoCut3D::add_horizontal_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::add_vertical_scaled_interval(), Slic3r::GUI::GLGizmoCut3D::adjust_window_position(), Slic3r::GUI::GLGizmoSimplify::create_gui_cfg(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_style_add_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_popup(), Slic3r::GUI::GLGizmoEmboss::draw_style_save_as_popup(), Slic3r::GUI::GLGizmoEmboss::draw_text_input(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::GLGizmoCut3D::init_input_window_data(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::render_build_size(), Slic3r::GUI::GLGizmoCut3D::render_combo(), Slic3r::GUI::GLGizmoCut3D::render_connectors_input_window(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoCut3D::render_debug_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoCut3D::render_double_input(), Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button(), Slic3r::GUI::GLGizmoCut3D::render_input_window_warning(), Slic3r::GUI::GLGizmoCut3D::render_move_center_input(), Slic3r::GUI::GLGizmoCut3D::render_reset_button(), Slic3r::GUI::GLGizmoCut3D::render_shortcuts(), Slic3r::GUI::GLGizmoCut3D::render_slider_double_input(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
m_input_enabled
bool Slic3r::GUI::GLGizmoSlaBase::m_input_enabled { false } private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::is_input_enabled(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_lock_unique_islands
bool Slic3r::GUI::GLGizmoSlaSupports::m_lock_unique_islands = false private
Referenced by delete_selected_points(), on_dragging(), on_render_input_window(), and render_points().
m_min_sla_print_object_step
int Slic3r::GUI::GLGizmoSlaBase::m_min_sla_print_object_step { -1 } private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::get_min_sla_print_object_step(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_minimal_point_distance_stash
float Slic3r::GUI::GLGizmoSlaSupports::m_minimal_point_distance_stash = 0.f private
Referenced by on_render_input_window().
m_new_point_head_diameter
float Slic3r::GUI::GLGizmoSlaSupports::m_new_point_head_diameter private
Referenced by gizmo_event(), on_load(), on_render_input_window(), on_save(), on_set_state(), and select_point().
m_normal_cache
std::vector<sla::SupportPoint> Slic3r::GUI::GLGizmoSlaSupports::m_normal_cache private
Referenced by auto_generate(), editing_mode_apply_changes(), get_data_from_backend(), on_load(), on_render_input_window(), on_save(), reload_cache(), render_points(), switch_to_editing_mode(), and unsaved_changes().
m_old_mo_id
ObjectID Slic3r::GUI::GLGizmoSlaSupports::m_old_mo_id private
Referenced by data_changed(), and on_set_state().
m_old_point_head_diameter
float Slic3r::GUI::GLGizmoSlaSupports::m_old_point_head_diameter = 0. private
Referenced by on_render_input_window().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by Slic3r::GUI::GLGizmoCut3D::add_connector(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::GLGizmoCut3D::bounding_box(), Slic3r::GUI::GLGizmoEmboss::calculate_scale(), Slic3r::GUI::GLGizmoEmboss::close(), Slic3r::GUI::GLGizmoSimplify::close(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoFlatten::data_changed(), Slic3r::GUI::GLGizmoMeasure::data_changed(), Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoRotate3D::data_changed(), Slic3r::GUI::GLGizmoCut3D::delete_selected_connectors(), disable_editing_mode(), Slic3r::GUI::GLGizmoEmboss::do_rotate(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoEmboss::do_translate(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_window(), get_data_from_backend(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeasure::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), has_backend_supports(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeasure::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), on_is_activable(), Slic3r::GUI::GLGizmoCut3D::on_load(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), on_render(), Slic3r::GUI::GLGizmoEmboss::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_shortcut_key(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoEmboss::on_stop_dragging(), Slic3r::GUI::GLGizmoMove3D::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoScale3D::on_stop_dragging(), Slic3r::GUI::GLGizmoCut3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::GUI::GLGizmoEmboss::process(), Slic3r::GUI::GLGizmoSimplify::process(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_cut_line(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), register_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::remove_selected_sphere_raycaster(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), Slic3r::GUI::GLGizmoCut3D::reset_cut_by_contours(), Slic3r::GUI::GLGizmoCut3D::reset_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), Slic3r::GUI::GLGizmoCut3D::set_volumes_picking_state(), switch_to_editing_mode(), Slic3r::GUI::GLGizmoCut3D::transformed_bounding_box(), Slic3r::GUI::GLGizmoHollow::unregister_hole_raycasters_for_picking(), unregister_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoCut3D::update_clipper(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_point_before_drag
CacheEntry Slic3r::GUI::GLGizmoSlaSupports::m_point_before_drag private
Referenced by on_start_dragging(), and on_stop_dragging().
m_point_raycasters
std::vector<std::pair<std::shared_ptr<SceneRaycasterItem>, std::shared_ptr<SceneRaycasterItem> > > Slic3r::GUI::GLGizmoSlaSupports::m_point_raycasters private
Referenced by data_changed(), register_point_raycasters_for_picking(), render_points(), unregister_point_raycasters_for_picking(), and update_point_raycasters_for_picking_transform().
m_selection_empty
bool Slic3r::GUI::GLGizmoSlaSupports::m_selection_empty = true private
Referenced by gizmo_event(), on_load(), on_render_input_window(), on_save(), select_point(), and unselect_point().
m_selection_rectangle
GLSelectionRectangle Slic3r::GUI::GLGizmoSlaSupports::m_selection_rectangle private
Referenced by gizmo_event(), is_selection_rectangle_dragging(), and on_render().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoCut3D::on_init(), Slic3r::GUI::GLGizmoEmboss::on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), Slic3r::GUI::GLGizmoHollow::on_init(), Slic3r::GUI::GLGizmoMeasure::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), and on_init().
m_show_sla_supports
bool Slic3r::GUI::GLGizmoSlaBase::m_show_sla_supports { false } private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::are_sla_supports_shown(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), and Slic3r::GUI::GLGizmoSlaBase::show_sla_supports().
m_sphere
PickingModel Slic3r::GUI::GLGizmoSlaSupports::m_sphere private
Referenced by on_render(), register_point_raycasters_for_picking(), and render_points().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_state
EState Slic3r::GUI::GLGizmoBase::m_state protected inherited
Referenced by Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), data_changed(), Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoBase::load(), Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), on_render(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), Slic3r::GUI::GLGizmoRotate3D::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoBase::set_state(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), and Slic3r::GUI::GLGizmoSimplify::worker_finished().
m_volume_raycasters
std::vector<std::shared_ptr<SceneRaycasterItem> > Slic3r::GUI::GLGizmoSlaBase::m_volume_raycasters private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking().
m_volumes
GLVolumeCollection Slic3r::GUI::GLGizmoSlaBase::m_volumes private inherited
Referenced by Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::GUI::GLGizmoSlaBase::volumes().
m_wait_for_up_event
bool Slic3r::GUI::GLGizmoSlaSupports::m_wait_for_up_event = false private
Referenced by gizmo_event().
NO_SHORTCUT_KEY_VALUE
const int Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE = 0 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
RenderPointScale
constexpr float Slic3r::GUI::GLGizmoSlaSupports::RenderPointScale = 1.f static constexpr private
Referenced by render_points(), and update_point_raycasters_for_picking_transform().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoSlaSupports.hpp
src/slic3r/GUI/Gizmos/GLGizmoSlaSupports.cpp