Prusa Slicer: Slic3r::line_alg Namespace Reference
Slic3r::line_alg Namespace Reference
Classes
struct Traits
Typedefs
template<class L >
using Scalar = typename Traits< remove_cvref_t< L > >::Scalar
Functions
template<class L >
auto get_a (L &&l)
template<class L >
auto get_b (L &&l)
template<class L >
double distance_to_squared (const L &line, const Vec< Dim< L >, Scalar< L > > &point, Vec< Dim< L >, Scalar< L > > *nearest_point)
template<class L >
double distance_to_squared (const L &line, const Vec< Dim< L >, Scalar< L > > &point)
template<class L >
double distance_to (const L &line, const Vec< Dim< L >, Scalar< L > > &point)
template<class L >
double distance_to_infinite_squared (const L &line, const Vec< Dim< L >, Scalar< L > > &point, Vec< Dim< L >, Scalar< L > > *closest_point)
template<class L >
double distance_to_infinite_squared (const L &line, const Vec< Dim< L >, Scalar< L > > &point)
template<class L >
double distance_to_infinite (const L &line, const Vec< Dim< L >, Scalar< L > > &point)
template<class L >
bool intersection (const L &l1, const L &l2, Vec< Dim< L >, Scalar< L > > *intersection_pt)
Variables
template<class L >
const constexpr int Dim = Traits<remove_cvref_t<L>>::Dim
Typedef Documentation
Scalar
template<class L > using Slic3r::line_alg::Scalar = typedef typename Traits<remove_cvref_t<L> >::Scalar
Function Documentation
distance_to()
template<class L > double Slic3r::line_alg::distance_to (const L & line, const Vec< Dim< L >, Scalar< L > > & point)
{
    return std::sqrt(distance_to_squared(line, point));
}
References distance_to_squared().
Referenced by Slic3r::ExtrusionQualityEstimator::estimate_speed_from_extrusion_quality().
distance_to_infinite()
template<class L > double Slic3r::line_alg::distance_to_infinite (const L & line, const Vec< Dim< L >, Scalar< L > > & point)
{
    return std::sqrt(distance_to_infinite_squared(line, point));
}
References distance_to_infinite_squared().
distance_to_infinite_squared() [1/2]
template<class L > double Slic3r::line_alg::distance_to_infinite_squared (const L & line, const Vec< Dim< L >, Scalar< L > > & point)
{
    Vec<Dim<L>, Scalar<L>> nearest_point;
    return distance_to_infinite_squared<L>(line, point, &nearest_point);
}
References Slic3r::nearest_point().
distance_to_infinite_squared() [2/2]
template<class L > double Slic3r::line_alg::distance_to_infinite_squared (const L & line, const Vec< Dim< L >, Scalar< L > > & point, Vec< Dim< L >, Scalar< L > > * closest_point)
{
    const Vec<Dim<L>, double> v  = (get_b(line) - get_a(line)).template cast<double>();
    const Vec<Dim<L>, double> va = (point - get_a(line)).template cast<double>();
    const double              l2 = v.squaredNorm(); // avoid a sqrt
    if (l2 == 0.) {
        // a == b case
        *closest_point = get_a(line);
        return va.squaredNorm();
    }
    // Consider the line extending the segment, parameterized as a + t (b - a).
    // We find projection of this point onto the line.
    // It falls where t = [(this-a) . (b-a)] / |b-a|^2
    const double t = va.dot(v) / l2;
    *closest_point = (get_a(line).template cast<double>() + t * v).template cast<Scalar<L>>();
    return (t * v - va).squaredNorm();
}
References cast(), get_a(), get_b(), and Slic3r::l2().
Referenced by distance_to_infinite(), Slic3r::Line::distance_to_infinite_squared(), and Slic3r::Line::distance_to_infinite_squared().
distance_to_squared() [1/2]
template<class L > double Slic3r::line_alg::distance_to_squared (const L & line, const Vec< Dim< L >, Scalar< L > > & point)
{
    Vec<Dim<L>, Scalar<L>> nearest_point;
    return distance_to_squared<L>(line, point, &nearest_point);
}
References Slic3r::nearest_point().
distance_to_squared() [2/2]
template<class L > double Slic3r::line_alg::distance_to_squared (const L & line, const Vec< Dim< L >, Scalar< L > > & point, Vec< Dim< L >, Scalar< L > > * nearest_point) inline
{
    using VecType = Vec<Dim<L>, double>;
    const VecType  v  = (get_b(line) - get_a(line)).template cast<double>();
    const VecType  va = (point  - get_a(line)).template cast<double>();
    const double  l2 = v.squaredNorm();
    if (l2 == 0.0) {
        // a == b case
        *nearest_point = get_a(line);
        return va.squaredNorm();
    }
    // Consider the line extending the segment, parameterized as a + t (b - a).
    // We find projection of this point onto the line.
    // It falls where t = [(this-a) . (b-a)] / |b-a|^2
    const double t = va.dot(v);
    if (t <= 0.0) {
        // beyond the 'a' end of the segment
        *nearest_point = get_a(line);
        return va.squaredNorm();
    } else if (t >= l2) {
        // beyond the 'b' end of the segment
        *nearest_point = get_b(line);
        return (point - get_b(line)).template cast<double>().squaredNorm();
    }
    const VecType w = ((t / l2) * v).eval();
    *nearest_point = (get_a(line).template cast<double>() + w).template cast<Scalar<L>>();
    return (w - va).squaredNorm();
}
References cast(), get_a(), get_b(), Slic3r::l2(), and Slic3r::nearest_point().
Referenced by Slic3r::clip_extrusion(), Slic3r::AABBTreeLines::detail::IndexedLinesDistancer< ALineType, ATreeType, AVectorType >::closest_point_to_origin(), Slic3r::FillAdaptive::connect_lines_using_hooks(), distance_to(), Slic3r::Line::distance_to_squared(), Slic3r::Line::distance_to_squared(), Slic3r::foot_pt(), Slic3r::FillLightning::Layer::getBestGroundingLocation(), Slic3r::line_rounded_thick_segment_collision(), Slic3r::mark_boundary_segments_overlapping_infill(), Slic3r::MinDistanceVisitor::operator()(), and Slic3r::Polyline::split_at().
get_a()
template<class L > auto Slic3r::line_alg::get_a (L && l)
{ return Traits<remove_cvref_t<L>>::get_a(l); }
References get_a().
Referenced by distance_to_infinite_squared(), distance_to_squared(), and get_a().
get_b()
template<class L > auto Slic3r::line_alg::get_b (L && l)
{ return Traits<remove_cvref_t<L>>::get_b(l); }
References get_b().
Referenced by distance_to_infinite_squared(), distance_to_squared(), and get_b().
intersection()
template<class L > bool Slic3r::line_alg::intersection (const L & l1, const L & l2, Vec< Dim< L >, Scalar< L > > * intersection_pt)
{
    using Floating      = typename std::conditional<std::is_floating_point<Scalar<L>>::value, Scalar<L>, double>::type;
    using VecType       = const Vec<Dim<L>, Floating>;
    const VecType v1    = (l1.b - l1.a).template cast<Floating>();
    const VecType v2    = (l2.b - l2.a).template cast<Floating>();
    Floating      denom = cross2(v1, v2);
    if (fabs(denom) < EPSILON)
#if 0
        // Lines are collinear. Return true if they are coincident (overlappign).
        return ! (fabs(nume_a) < EPSILON && fabs(nume_b) < EPSILON);
#else
        return false;
#endif
    const VecType v12 = (l1.a - l2.a).template cast<Floating>();
    Floating nume_a = cross2(v2, v12);
    Floating nume_b = cross2(v1, v12);
    Floating t1     = nume_a / denom;
    Floating t2     = nume_b / denom;
    if (t1 >= 0 && t1 <= 1.0f && t2 >= 0 && t2 <= 1.0f) {
        // Get the intersection point.
        (*intersection_pt) = (l1.a.template cast<Floating>() + t1 * v1).template cast<Scalar<L>>();
        return true;
    }
    return false; // not intersecting
}
References cast(), Slic3r::cross2(), EPSILON, and Slic3r::l2().
Referenced by Slic3r::AABBTreeLines::detail::get_intersections_with_line(), and Slic3r::Line::intersection().
Variable Documentation
Dim
template<class L > const constexpr int Slic3r::line_alg::Dim = Traits<remove_cvref_t<L>>::Dim constexpr