Prusa Slicer: Slic3r::GUI::search_for_drives_internal Namespace Reference
Slic3r::GUI::search_for_drives_internal Namespace Reference
Functions
static bool compare_filesystem_id (const std::string &path_a, const std::string &path_b)
void inspect_file (const std::string &path, const std::string &parent_path, std::vector< DriveData > &out)
static void search_path (const std::string &path, const std::string &parent_path, std::vector< DriveData > &out)
Function Documentation
compare_filesystem_id()
static bool Slic3r::GUI::search_for_drives_internal::compare_filesystem_id (const std::string & path_a, const std::string & path_b) static
  {
    struct stat buf;
    stat(path_a.c_str() ,&buf);
    dev_t id_a = buf.st_dev;
    stat(path_b.c_str() ,&buf);
    dev_t id_b = buf.st_dev;
    return id_a == id_b;
  }
References stat.
Referenced by Slic3r::GUI::RemovableDriveManager::get_removable_drive_from_path(), Slic3r::GUI::RemovableDriveManager::get_removable_drive_path(), and inspect_file().
inspect_file()
void Slic3r::GUI::search_for_drives_internal::inspect_file (const std::string & path, const std::string & parent_path, std::vector< DriveData > & out)
  {
    //confirms if the file is removable drive and adds it to vector
    if (
#ifdef __linux__
      // Chromium mounts removable drives in a way that produces the same device ID.
      platform_flavor() == PlatformFlavor::LinuxOnChromium ||
#endif
      // If not same file system - could be removable drive.
      ! compare_filesystem_id(path, parent_path)) {
      //free space
      boost::system::error_code ec;
      boost::filesystem::space_info si = boost::filesystem::space(path, ec);
      if (!ec && si.available != 0) {
        //user id
        struct stat buf;
        stat(path.c_str(), &buf);
        uid_t uid = buf.st_uid;
        if (getuid() == uid)
          out.emplace_back(DriveData{ boost::filesystem::basename(boost::filesystem::path(path)), path });
      }
    }
  }
References compare_filesystem_id(), Slic3r::LinuxOnChromium, Slic3r::platform_flavor(), and stat.
Referenced by search_path().
search_path()
static void Slic3r::GUI::search_for_drives_internal::search_path (const std::string & path, const std::string & parent_path, std::vector< DriveData > & out) static
  {
      glob_t globbuf;
    globbuf.gl_offs = 2;
    int error = glob(path.c_str(), GLOB_TILDE, NULL, &globbuf);
    if (error == 0) {
      for (size_t i = 0; i < globbuf.gl_pathc; ++ i)
        inspect_file(globbuf.gl_pathv[i], parent_path, out);
    } else {
      //if error - path probably doesnt exists so function just exits
      //std::cout<<"glob error "<< error<< "\n";
    }
    globfree(&globbuf);
  }
References error, and inspect_file().
Referenced by Slic3r::GUI::RemovableDriveManager::search_for_removable_drives().