Prusa Slicer: Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node Struct Reference
Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node Struct Reference
#include <src/libslic3r/AABBTreeIndirect.hpp>
Public Member Functions
bool is_valid () const
bool is_inner () const
bool is_leaf () const
template<typename SourceNode >
void set (const SourceNode &rhs)
Public Attributes
size_t idx = npos
BoundingBox bbox
Detailed Description
template<int ANumDimensions, typename ACoordType>
struct Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node
Member Function Documentation
is_inner()
template<int ANumDimensions, typename ACoordType > bool Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node::is_inner () const inline
{ return this->idx == inner; }
References Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::inner.
Referenced by Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node::is_leaf().
is_leaf()
template<int ANumDimensions, typename ACoordType > bool Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node::is_leaf () const inline
{ return ! this->is_inner(); }
References Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node::is_inner().
Referenced by Slic3r::AABBTreeIndirect::Within< Eigen::AlignedBox< CoordType, NumD > >::operator()(), and Slic3r::AABBTreeIndirect::detail::traverse_recurse().
is_valid()
template<int ANumDimensions, typename ACoordType > bool Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node::is_valid () const inline
{ return this->idx != npos; }
References Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::npos.
Referenced by Slic3r::AABBTreeIndirect::detail::traverse_recurse().
set()
template<int ANumDimensions, typename ACoordType > template<typename SourceNode > void Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node::set (const SourceNode & rhs) inline
{
            this->idx  = rhs.idx();
            this->bbox = rhs.bbox();
    }
Member Data Documentation
bbox
template<int ANumDimensions, typename ACoordType > BoundingBox Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node::bbox
Referenced by Slic3r::AABBTreeIndirect::Intersecting< Eigen::AlignedBox< CoordType, NumD > >::operator()(), and Slic3r::AABBTreeIndirect::Within< Eigen::AlignedBox< CoordType, NumD > >::operator()().
idx
template<int ANumDimensions, typename ACoordType > size_t Slic3r::AABBTreeIndirect::Tree< ANumDimensions, ACoordType >::Node::idx = npos
The documentation for this struct was generated from the following file:
src/libslic3r/AABBTreeIndirect.hpp