Prusa Slicer: Slic3r::Utils::anonymous_namespace{Time.cpp} Namespace Reference
Slic3r::Utils::anonymous_namespace{Time.cpp} Namespace Reference
Functions
struct std::tm * _gmtime_r (const time_t *timep, struct tm *result)
struct std::tm * _localtime_r (const time_t *timep, struct tm *result)
time_t _mktime (const struct std::tm *tms)
time_t _timegm (const struct std::tm *tms)
std::string process_format (const char *fmt, TimeZone zone)
Function Documentation
_gmtime_r()
struct std::tm * Slic3r::Utils::anonymous_namespace{Time.cpp}::_gmtime_r (const time_t * timep, struct tm * result)
{
    assert(timep != nullptr && result != nullptr);
#ifdef WIN32
    time_t t = *timep;
    gmtime_s(result, &t);
    return result;
#else
    return gmtime_r(timep, result);
#endif
}
References _gmtime_r().
Referenced by _gmtime_r().
_localtime_r()
struct std::tm * Slic3r::Utils::anonymous_namespace{Time.cpp}::_localtime_r (const time_t * timep, struct tm * result)
{
    assert(timep != nullptr && result != nullptr);
#ifdef WIN32
    // Converts a time_t time value to a tm structure, and corrects for the
    // local time zone.
    time_t t = *timep;
    localtime_s(result, &t);
    return result;
#else
    return localtime_r(timep, result);
#endif
}
References _localtime_r().
Referenced by _localtime_r().
_mktime()
time_t Slic3r::Utils::anonymous_namespace{Time.cpp}::_mktime (const struct std::tm * tms)
{
    assert(tms != nullptr);
    std::tm _tms = *tms;
    return mktime(&_tms);
}
References _mktime().
Referenced by _mktime().
_timegm()
time_t Slic3r::Utils::anonymous_namespace{Time.cpp}::_timegm (const struct std::tm * tms)
{
    std::tm _tms = *tms;
#ifdef WIN32
    return _mkgmtime(&_tms);
#else /* WIN32 */
    return timegm(&_tms);
#endif /* WIN32 */
}
References _timegm().
Referenced by _timegm().
process_format()
std::string Slic3r::Utils::anonymous_namespace{Time.cpp}::process_format (const char * fmt, TimeZone zone)
{
    std::string fmtstr(fmt);
    if (fmtstr == SLICER_UTC_TIME_FMT && zone == TimeZone::utc)
        fmtstr += " UTC";
    return fmtstr;
}
References fmtstr(), process_format(), Slic3r::Utils::SLICER_UTC_TIME_FMT, and Slic3r::Utils::utc.
Referenced by process_format().