Prusa Slicer: Slic3r::GUI::GLGizmoCut3D Class Reference
Slic3r::GUI::GLGizmoCut3D Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoCut.hpp>
Classes
struct InvalidConnectorsStatistics
class PartSelection
Public Types
enum class EGrabberExtension {
None = 0 , PosX = 1 << 0 , NegX = 1 << 1 , PosY = 1 << 2 ,
NegY = 1 << 3 , PosZ = 1 << 4 , NegZ = 1 << 5
}
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoCut3D (GLCanvas3D &parent, const std::string &icon_filename, unsigned int sprite_id)
–
std::string get_tooltip () const override
Mouse tooltip text.
bool unproject_on_cut_plane (const Vec2d &mouse_pos, Vec3d &pos, Vec3d &pos_world, bool respect_disabled_contour=true)
bool gizmo_event (SLAGizmoEventType action, const Vec2d &mouse_position, bool shift_down, bool alt_down, bool control_down)
bool is_in_editing_mode () const override
bool is_selection_rectangle_dragging () const override
bool is_looking_forward () const
bool on_mouse (const wxMouseEvent &mouse_event) override
Drag of plane.
void shift_cut (double delta)
void rotate_vec3d_around_plane_center (Vec3d &vec)
void put_connectors_on_cut_plane (const Vec3d &cp_normal, double cp_offset)
void update_clipper ()
void invalidate_cut_plane ()
BoundingBoxf3 bounding_box () const
BoundingBoxf3 transformed_bounding_box (const Vec3d &plane_center, const Transform3d &rotation_m=Transform3d::Identity()) const
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
void set_common_data_pool (CommonGizmosDataPool *ptr)
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
bool is_dragging () const
bool update_items_state ()
void render ()
void render_input_window (float x, float y, float bottom_limit)
void register_raycasters_for_picking ()
void unregister_raycasters_for_picking ()
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static const unsigned int GRABBER_ELEMENTS_MAX_COUNT = 7
static const int NO_SHORTCUT_KEY_VALUE = 0
Protected Member Functions
bool on_init () override
void on_load (cereal::BinaryInputArchive &ar) override
void on_save (cereal::BinaryOutputArchive &ar) const override
std::string on_get_name () const override
void on_set_state () override
CommonGizmosDataID on_get_requirements () const override
void on_set_hover_id () override
bool on_is_activable () const override
bool on_is_selectable () const override
Vec3d mouse_position_in_local_plane (GrabberID axis, const Linef3 &mouse_ray) const
void dragging_grabber_z (const GLGizmoBase::UpdateData &data)
void dragging_grabber_xy (const GLGizmoBase::UpdateData &data)
void dragging_connector (const GLGizmoBase::UpdateData &data)
void on_dragging (const UpdateData &data) override
void on_start_dragging () override
void on_stop_dragging () override
void on_render () override
void render_debug_input_window (float x)
void adjust_window_position (float x, float y, float bottom_limit)
void unselect_all_connectors ()
void select_all_connectors ()
void render_shortcuts ()
void apply_selected_connectors (std::function< void(size_t idx)> apply_fn)
void render_connectors_input_window (CutConnectors &connectors)
void render_build_size ()
void reset_cut_plane ()
void set_connectors_editing (bool connectors_editing)
void flip_cut_plane ()
void process_contours ()
void reset_cut_by_contours ()
void render_flip_plane_button (bool disable_pred=false)
void add_vertical_scaled_interval (float interval)
void add_horizontal_scaled_interval (float interval)
void add_horizontal_shift (float shift)
void render_color_marker (float size, const ImU32 &color)
void render_cut_plane_input_window (CutConnectors &connectors)
void init_input_window_data (CutConnectors &connectors)
void render_input_window_warning () const
bool add_connector (CutConnectors &connectors, const Vec2d &mouse_position)
bool delete_selected_connectors (CutConnectors &connectors)
void select_connector (int idx, bool select)
bool is_selection_changed (bool alt_down, bool shift_down)
void process_selection_rectangle (CutConnectors &connectors)
virtual void on_register_raycasters_for_picking () override
virtual void on_unregister_raycasters_for_picking () override
void update_raycasters_for_picking ()
void set_volumes_picking_state (bool state)
void update_raycasters_for_picking_transform ()
void on_render_input_window (float x, float y, float bottom_limit) override
bool wants_enter_leave_snapshots () const override
std::string get_gizmo_entering_text () const override
std::string get_gizmo_leaving_text () const override
std::string get_action_snapshot_name () const override
void data_changed (bool is_serializing) override
Is called when data (Selection) is changed.
Transform3d get_cut_matrix (const Selection &selection)
virtual void on_enable_grabber (unsigned int id)
virtual void on_disable_grabber (unsigned int id)
void register_grabbers_for_picking ()
void unregister_grabbers_for_picking ()
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers (size_t first, size_t last, float size, bool force_hover) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
bool use_grabbers (const wxMouseEvent &mouse_event)
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
void do_stop_dragging (bool perform_mouse_cleanup)
Protected Attributes
GLCanvas3D & m_parent
int m_group_id
EState m_state
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id { -1 }
bool m_dragging { false }
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render { true }
CommonGizmosDataPool * m_c { nullptr }
Private Types
enum GrabberID {
X = 0 , Y , Z , CutPlane ,
Count
}
enum class CutMode { cutPlanar , cutGrig }
enum class CutConnectorMode { Auto , Manual }
Private Member Functions
void set_center (const Vec3d &center, bool update_tbb=false)
bool render_combo (const std::string &label, const std::vector< std::string > &lines, int &selection_idx)
bool render_double_input (const std::string &label, double &value_in)
bool render_slider_double_input (const std::string &label, float &value_in, float &tolerance_in)
void render_move_center_input (int axis)
void render_connect_mode_radio_button (CutConnectorMode mode)
bool render_reset_button (const std::string &label_id, const std::string &tooltip) const
bool render_connect_type_radio_button (CutConnectorType type)
bool is_outside_of_cut_contour (size_t idx, const CutConnectors &connectors, const Vec3d cur_pos)
bool is_conflict_for_connector (size_t idx, const CutConnectors &connectors, const Vec3d cur_pos)
void render_connectors ()
bool can_perform_cut () const
bool has_valid_contour () const
void apply_connectors_in_model (ModelObject *mo, int &dowels_count)
bool cut_line_processing () const
void discard_cut_line_processing ()
void render_cut_plane ()
void render_line (GLModel &line_model, const ColorRGBA &color, Transform3d view_model_matrix, float width)
void render_rotation_snapping (GrabberID axis, const ColorRGBA &color)
void render_grabber_connection (const ColorRGBA &color, Transform3d view_matrix)
void render_cut_plane_grabbers ()
void render_cut_line ()
void perform_cut (const Selection &selection)
void set_center_pos (const Vec3d &center_pos, bool update_tbb=false)
void update_bb ()
void init_picking_models ()
void init_rendering_items ()
void render_clipper_cut ()
void clear_selection ()
void reset_connectors ()
void init_connector_shapes ()
void update_connector_shape ()
void validate_connector_settings ()
bool process_cut_line (SLAGizmoEventType action, const Vec2d &mouse_position)
void check_and_update_connectors_state ()
Static Private Member Functions
static void render_model (GLModel &model, const ColorRGBA &color, Transform3d view_model_matrix)
Private Attributes
Transform3d m_rotation_m { Transform3d::Identity() }
double m_snap_step { 1.0 }
int m_connectors_group_id
Vec3d m_ar_plane_center { Vec3d::Zero() }
Transform3d m_start_dragging_m { Transform3d::Identity() }
Vec3d m_plane_center { Vec3d::Zero() }
Vec3d m_min_pos { Vec3d::Zero() }
Vec3d m_max_pos { Vec3d::Zero() }
Vec3d m_bb_center { Vec3d::Zero() }
Vec3d m_center_offset { Vec3d::Zero() }
BoundingBoxf3 m_bounding_box
BoundingBoxf3 m_transformed_bounding_box
double m_radius { 0.0 }
double m_grabber_radius { 0.0 }
double m_grabber_connection_len { 0.0 }
double m_snap_coarse_in_radius { 0.0 }
double m_snap_coarse_out_radius { 0.0 }
double m_snap_fine_in_radius { 0.0 }
double m_snap_fine_out_radius { 0.0 }
double m_angle { 0.0 }
TriangleMesh m_connector_mesh
Vec3d m_clp_normal { Vec3d::Ones() }
Vec3d m_line_beg { Vec3d::Zero() }
Vec3d m_line_end { Vec3d::Zero() }
Vec2d m_ldown_mouse_position { Vec2d::Zero() }
GLModel m_grabber_connection
GLModel m_cut_line
PickingModel m_plane
PickingModel m_sphere
PickingModel m_cone
std::map< CutConnectorAttributes, PickingModel > m_shapes
std::vector< std::shared_ptr< SceneRaycasterItem > > m_raycasters
GLModel m_circle
GLModel m_scale
GLModel m_snap_radii
GLModel m_reference_radius
GLModel m_angle_arc
Vec3d m_old_center
Vec3d m_cut_normal
struct Slic3r::GUI::GLGizmoCut3D::InvalidConnectorsStatistics m_info_stats
bool m_keep_upper { true }
bool m_keep_lower { true }
bool m_keep_as_parts { false }
bool m_place_on_cut_upper { true }
bool m_place_on_cut_lower { false }
bool m_rotate_upper { false }
bool m_rotate_lower { false }
bool m_hide_cut_plane { false }
bool m_connectors_editing { false }
bool m_cut_plane_as_circle { false }
float m_connector_depth_ratio { 3.f }
float m_connector_size { 2.5f }
float m_connector_depth_ratio_tolerance { 0.1f }
float m_connector_size_tolerance { 0.f }
float m_label_width { 0.f }
float m_control_width { 200.f }
bool m_imperial_units { false }
float m_contour_width { 0.4f }
float m_cut_plane_radius_koef { 1.5f }
bool m_is_contour_changed { false }
float m_shortcut_label_width { -1.f }
std::vector< bool > m_selected
int m_selected_count { 0 }
GLSelectionRectangle m_selection_rectangle
std::vector< size_t > m_invalid_connectors_idxs
bool m_was_cut_plane_dragged { false }
bool m_was_contour_selected { false }
PartSelection m_part_selection
bool m_show_shortcuts { false }
std::vector< std::pair< wxString, wxString > > m_shortcuts
size_t m_mode { size_t(CutMode::cutPlanar) }
std::vector< std::string > m_connector_modes
CutConnectorMode m_connector_mode { CutConnectorMode::Manual }
std::vector< std::string > m_connector_types
CutConnectorType m_connector_type
std::vector< std::string > m_connector_styles
int m_connector_style
std::vector< std::string > m_connector_shapes
int m_connector_shape_id
std::vector< std::string > m_axis_names
std::map< std::string, wxString > m_part_orientation_names
std::map< std::string, std::string > m_labels_map
bool m_dirty { false }
Detailed Description
Member Enumeration Documentation
CutConnectorMode
enum class Slic3r::GUI::GLGizmoCut3D::CutConnectorMode strong private
Enumerator
Auto
Manual
{
        Auto
        , Manual
    };
CutMode
enum class Slic3r::GUI::GLGizmoCut3D::CutMode strong private
Enumerator
cutPlanar
cutGrig
                       {
        cutPlanar
        , cutGrig
        //,cutRadial
        //,cutModular
    };
EGrabberExtension
enum class Slic3r::GUI::GLGizmoBase::EGrabberExtension strong inherited
Enumerator
None
PosX
NegX
PosY
NegY
PosZ
NegZ
    {
        None = 0,
        PosX = 1 << 0,
        NegX = 1 << 1,
        PosY = 1 << 2,
        NegY = 1 << 3,
        PosZ = 1 << 4,
        NegZ = 1 << 5,
    };
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
GrabberID
enum Slic3r::GUI::GLGizmoCut3D::GrabberID private
Enumerator
X
Y
Z
CutPlane
Count
                   {
        X = 0,
        Y,
        Z,
        CutPlane,
        Count,
    };
Constructor & Destructor Documentation
GLGizmoCut3D()
Slic3r::GUI::GLGizmoCut3D::GLGizmoCut3D (GLCanvas3D & parent, const std::string & icon_filename, unsigned int sprite_id)
–
    : GLGizmoBase(parent, icon_filename, sprite_id)
    , m_connectors_group_id (GrabberID::Count)
    , m_connector_type (CutConnectorType::Plug)
    , m_connector_style (int(CutConnectorStyle::Prism))
    , m_connector_shape_id (int(CutConnectorShape::Circle))
{
//    m_modes = { _u8L("Planar"), _u8L("Grid")
//              , _u8L("Radial"), _u8L("Modular")
//    };
    m_connector_modes = { _u8L("Auto"), _u8L("Manual") };
    std::map<const wchar_t, std::string> connetor_types = {
        {ImGui::PlugMarker , _u8L("Plug")  },
        {ImGui::DowelMarker, _u8L("Dowel") },
    };
    for (auto connector : connetor_types) {
        std::string type_label = " " + connector.second + " ";
        type_label += connector.first;
        m_connector_types.push_back(type_label);
    }
    m_connector_styles = { _u8L("Prism"), _u8L("Frustum")
//              , _u8L("Claw")
    };
    m_connector_shapes = { _u8L("Triangle"), _u8L("Square"), _u8L("Hexagon"), _u8L("Circle")
//              , _u8L("D-shape")
    };
    m_axis_names = { "X", "Y", "Z" };
    m_part_orientation_names = {
        {"none",    _L("Keep orientation")},
        {"on_cut",  _L("Place on cut")},
        {"flip",    _L("Flip upside down")},
    };
    m_labels_map = {
        {"Connectors"   , _u8L("Connectors")},
        {"Type"         , _u8L("Type")},
        {"Style"        , _u8L("Style")},
        {"Shape"        , _u8L("Shape")},
        {"Depth"        , _u8L("Depth")},
        {"Size"         , _u8L("Size")},
    };
    update_connector_shape();
}
References _L, _u8L, ImGui::DowelMarker, m_axis_names, m_connector_modes, m_connector_shapes, m_connector_styles, m_connector_types, m_labels_map, m_part_orientation_names, ImGui::PlugMarker, and update_connector_shape().
Member Function Documentation
add_connector()
bool Slic3r::GUI::GLGizmoCut3D::add_connector (CutConnectors & connectors, const Vec2d & mouse_position) protected
{
    if (!m_connectors_editing)
        return false;
    Vec3d pos;
    Vec3d pos_world;
    if (unproject_on_cut_plane(mouse_position.cast<double>(), pos, pos_world)) {
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Add connector"), UndoRedo::SnapshotType::GizmoAction);
        unselect_all_connectors();
        connectors.emplace_back(pos, m_rotation_m,
                                m_connector_size * 0.5f, m_connector_depth_ratio,
                                m_connector_size_tolerance * 0.5f, m_connector_depth_ratio_tolerance,
                                CutConnectorAttributes( CutConnectorType(m_connector_type),
                                                        CutConnectorStyle(m_connector_style),
                                                        CutConnectorShape(m_connector_shape_id)));
        m_selected.push_back(true);
        m_selected_count = 1;
        assert(m_selected.size() == connectors.size());
        update_raycasters_for_picking();
        m_parent.set_as_dirty();
        check_and_update_connectors_state();
        return true;
    }
    return false;
}
References _L, check_and_update_connectors_state(), Slic3r::UndoRedo::GizmoAction, m_connector_depth_ratio, m_connector_depth_ratio_tolerance, m_connector_shape_id, m_connector_size, m_connector_size_tolerance, m_connector_style, m_connector_type, m_connectors_editing, Slic3r::GUI::GLGizmoBase::m_parent, m_rotation_m, m_selected, m_selected_count, Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), unproject_on_cut_plane(), unselect_all_connectors(), and update_raycasters_for_picking().
Referenced by gizmo_event().
add_horizontal_scaled_interval()
void Slic3r::GUI::GLGizmoCut3D::add_horizontal_scaled_interval (float interval) protected
{
    ImGui::GetCurrentWindow()->DC.CursorPos.x += m_imgui->scaled(interval);
}
References ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGui::GetCurrentWindow(), Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::ImGuiWrapper::scaled(), and ImVec2::x.
Referenced by render_cut_plane_input_window().
add_horizontal_shift()
void Slic3r::GUI::GLGizmoCut3D::add_horizontal_shift (float shift) protected
{
    ImGui::GetCurrentWindow()->DC.CursorPos.x += shift;
}
References ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGui::GetCurrentWindow(), and ImVec2::x.
Referenced by render_cut_plane_input_window().
add_vertical_scaled_interval()
void Slic3r::GUI::GLGizmoCut3D::add_vertical_scaled_interval (float interval) protected
{
    ImGui::GetCurrentWindow()->DC.CursorPos.y += m_imgui->scaled(interval);
}
References ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGui::GetCurrentWindow(), Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::ImGuiWrapper::scaled(), and ImVec2::y.
Referenced by render_cut_plane_input_window().
adjust_window_position()
void Slic3r::GUI::GLGizmoCut3D::adjust_window_position (float x, float y, float bottom_limit) protected
{
    static float last_y = 0.0f;
    static float last_h = 0.0f;
    const float win_h = ImGui::GetWindowHeight();
    y                 = std::min(y, bottom_limit - win_h);
    ImGui::SetWindowPos(ImVec2(x, y), ImGuiCond_Always);
    if (!is_approx(last_h, win_h) || !is_approx(last_y, y)) {
        // ask canvas for another frame to render the window in the correct position
        m_imgui->set_requires_extra_frame();
        if (!is_approx(last_h, win_h))
            last_h = win_h;
        if (!is_approx(last_y, y))
            last_y = y;
    }
}
References ImGui::GetWindowHeight(), ImGuiCond_Always, Slic3r::is_approx(), Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::ImGuiWrapper::set_requires_extra_frame(), and ImGui::SetWindowPos().
Referenced by on_render_input_window().
apply_connectors_in_model()
void Slic3r::GUI::GLGizmoCut3D::apply_connectors_in_model (ModelObject * mo, int & dowels_count) private
{
    if (m_connector_mode == CutConnectorMode::Manual) {
        clear_selection();
        for (CutConnector&connector : mo->cut_connectors) {
            connector.rotation_m = m_rotation_m;
            if (connector.attribs.type == CutConnectorType::Dowel) {
                if (connector.attribs.style == CutConnectorStyle::Prism)
                    connector.height *= 2;
                dowels_count ++;
            }
            else {
                // calculate shift of the connector center regarding to the position on the cut plane
                connector.pos += m_cut_normal * 0.5 * double(connector.height);
            }
        }
        mo->apply_cut_connectors(_u8L("Connector"));
    }
}
References _u8L, Slic3r::ModelObject::apply_cut_connectors(), clear_selection(), Slic3r::ModelObject::cut_connectors, Slic3r::Dowel, m_connector_mode, m_cut_normal, m_rotation_m, Manual, and Slic3r::Prism.
Referenced by perform_cut().
apply_selected_connectors()
void Slic3r::GUI::GLGizmoCut3D::apply_selected_connectors (std::function< void(size_t idx)> apply_fn) protected
{
    for (size_t idx = 0; idx < m_selected.size(); idx++)
        if (m_selected[idx])
            apply_fn(idx);
    check_and_update_connectors_state();
    update_raycasters_for_picking_transform();
}
References check_and_update_connectors_state(), m_selected, and update_raycasters_for_picking_transform().
Referenced by render_connectors_input_window().
bounding_box()
BoundingBoxf3 Slic3r::GUI::GLGizmoCut3D::bounding_box () const
{
    BoundingBoxf3 ret;
    const Selection& selection = m_parent.get_selection();
    const Selection::IndicesList& idxs = selection.get_volume_idxs();
    for (unsigned int i : idxs) {
        const GLVolume* volume = selection.get_volume(i);
        // respect just to the solid parts for FFF and ignore pad and supports for SLA
        if (!volume->is_modifier && !volume->is_sla_pad() && !volume->is_sla_support())
            ret.merge(volume->transformed_convex_hull_bounding_box());
    }
    return ret;
}
References Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::BoundingBox3Base< PointType >::merge().
Referenced by update_bb().
can_perform_cut()
bool Slic3r::GUI::GLGizmoCut3D::can_perform_cut () const private
{
    if (! m_invalid_connectors_idxs.empty() || (!m_keep_upper && !m_keep_lower) || m_connectors_editing)
        return false;
    if (m_part_selection.valid())
        return ! m_part_selection.is_one_object();
    return true;// has_valid_contour();
}
References Slic3r::GUI::GLGizmoCut3D::PartSelection::is_one_object(), m_connectors_editing, m_invalid_connectors_idxs, m_keep_lower, m_keep_upper, m_part_selection, and Slic3r::GUI::GLGizmoCut3D::PartSelection::valid().
Referenced by perform_cut(), render_cut_plane(), and render_cut_plane_input_window().
check_and_update_connectors_state()
void Slic3r::GUI::GLGizmoCut3D::check_and_update_connectors_state () private
{
    m_info_stats.invalidate();
    m_invalid_connectors_idxs.clear();
    const ModelObject* mo = m_c->selection_info()->model_object();
    auto inst_id = m_c->selection_info()->get_active_instance();
    if (inst_id < 0)
        return;
    const CutConnectors& connectors = mo->cut_connectors;
    const ModelInstance* mi = mo->instances[inst_id];
    const Vec3d& instance_offset = mi->get_offset();
    const double sla_shift       = double(m_c->selection_info()->get_sla_shift());
     for (size_t i = 0; i < connectors.size(); ++i) {
        const CutConnector& connector = connectors[i];
        Vec3d pos = connector.pos + instance_offset + sla_shift * Vec3d::UnitZ(); // recalculate connector position to world position
        if (is_conflict_for_connector(i, connectors, pos))
            m_invalid_connectors_idxs.emplace_back(i);
     }
}
References Slic3r::ModelObject::cut_connectors, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::ModelInstance::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::ModelObject::instances, Slic3r::GUI::GLGizmoCut3D::InvalidConnectorsStatistics::invalidate(), is_conflict_for_connector(), Slic3r::GUI::GLGizmoBase::m_c, m_info_stats, m_invalid_connectors_idxs, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::CutConnector::pos, and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by add_connector(), apply_selected_connectors(), delete_selected_connectors(), on_dragging(), on_mouse(), reset_connectors(), and set_center().
clear_selection()
void Slic3r::GUI::GLGizmoCut3D::clear_selection () private
{
    m_selected.clear();
    m_selected_count = 0;
}
References m_selected, and m_selected_count.
Referenced by apply_connectors_in_model(), render_connectors(), reset_connectors(), and update_bb().
cut_line_processing()
bool Slic3r::GUI::GLGizmoCut3D::cut_line_processing () const private
{
    return !m_line_beg.isApprox(Vec3d::Zero());
}
References m_line_beg.
Referenced by on_mouse(), on_register_raycasters_for_picking(), process_cut_line(), render_connectors(), render_cut_line(), render_cut_plane(), and update_raycasters_for_picking_transform().
data_changed()
void Slic3r::GUI::GLGizmoCut3D::data_changed (bool is_serializing) override protected virtual
Is called when data (Selection) is changed.
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    update_bb();
    if (auto oc = m_c->object_clipper())
        oc->set_behavior(m_connectors_editing, m_connectors_editing, double(m_contour_width));
}
References Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, m_contour_width, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), and update_bb().
delete_selected_connectors()
bool Slic3r::GUI::GLGizmoCut3D::delete_selected_connectors (CutConnectors & connectors) protected
{
    if (connectors.empty())
        return false;
    Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Delete connector"), UndoRedo::SnapshotType::GizmoAction);
    // remove  connectors
    for (int i = int(connectors.size()) - 1; i >= 0; i--)
        if (m_selected[i])
            connectors.erase(connectors.begin() + i);
    // remove selections
    m_selected.erase(std::remove_if(m_selected.begin(), m_selected.end(), [](const auto& selected) {
        return selected; }), m_selected.end());
    m_selected_count = 0;
    assert(m_selected.size() == connectors.size());
    update_raycasters_for_picking();
    m_parent.set_as_dirty();
    check_and_update_connectors_state();
    return true;
}
References _L, check_and_update_connectors_state(), Slic3r::UndoRedo::GizmoAction, Slic3r::GUI::GLGizmoBase::m_parent, m_selected, m_selected_count, Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), and update_raycasters_for_picking().
Referenced by gizmo_event().
discard_cut_line_processing()
void Slic3r::GUI::GLGizmoCut3D::discard_cut_line_processing () private
{
    m_line_beg = m_line_end = Vec3d::Zero();
}
References m_line_beg, and m_line_end.
Referenced by on_mouse(), and process_cut_line().
do_stop_dragging()
void Slic3r::GUI::GLGizmoBase::do_stop_dragging (bool perform_mouse_cleanup) protected inherited
{
    for (auto& grabber : m_grabbers) grabber.dragging = false;
    m_dragging = false;
    // NOTE: This should be part of GLCanvas3D
    // Reset hover_id when leave window
    if (perform_mouse_cleanup) m_parent.mouse_up_cleanup();
    on_stop_dragging();
    // There is prediction that after draggign, data are changed
    // Data are updated twice also by canvas3D::reload_scene.
    // Should be fixed.
    m_parent.get_gizmos_manager().update_data();
    wxGetApp().obj_manipul()->set_dirty();
    // Let the plater know that the dragging finished, so a delayed
    // refresh of the scene with the background processing data should
    // be performed.
    m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED));
    // updates camera target constraints
    m_parent.refresh_camera_scene_box();
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_up_cleanup(), Slic3r::GUI::GLGizmoBase::on_stop_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::refresh_camera_scene_box(), and Slic3r::GUI::GLGizmosManager::update_data().
Referenced by Slic3r::GUI::GLGizmoBase::use_grabbers().
dragging_connector()
void Slic3r::GUI::GLGizmoCut3D::dragging_connector (const GLGizmoBase::UpdateData & data) protected
{
    CutConnectors&          connectors = m_c->selection_info()->model_object()->cut_connectors;
    Vec3d                   pos;
    Vec3d                   pos_world;
    if (unproject_on_cut_plane(data.mouse_pos.cast<double>(), pos, pos_world)) {
        connectors[m_hover_id - m_connectors_group_id].pos = pos;
        update_raycasters_for_picking_transform();
    }
}
References Slic3r::ModelObject::cut_connectors, Slic3r::GUI::GLGizmoBase::m_c, m_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), unproject_on_cut_plane(), and update_raycasters_for_picking_transform().
Referenced by on_dragging().
dragging_grabber_xy()
void Slic3r::GUI::GLGizmoCut3D::dragging_grabber_xy (const GLGizmoBase::UpdateData & data) protected
{
    const Vec2d mouse_pos = to_2d(mouse_position_in_local_plane((GrabberID)m_hover_id, data.mouse_ray));
    const Vec2d orig_dir = Vec2d::UnitX();
    const Vec2d new_dir  = mouse_pos.normalized();
    const double two_pi = 2.0 * PI;
    double theta = ::acos(std::clamp(new_dir.dot(orig_dir), -1.0, 1.0));
    if (cross2(orig_dir, new_dir) < 0.0)
        theta = two_pi - theta;
    const double len = mouse_pos.norm();
    // snap to coarse snap region
    if (m_snap_coarse_in_radius <= len && len <= m_snap_coarse_out_radius) {
        const double step = two_pi / double(SnapRegionsCount);
        theta             = step * std::round(theta / step);
    }
    // snap to fine snap region (scale)
    else if (m_snap_fine_in_radius <= len && len <= m_snap_fine_out_radius) {
        const double step = two_pi / double(ScaleStepsCount);
        theta             = step * std::round(theta / step);
    }
    if (is_approx(theta, two_pi))
        theta = 0.0;
    if (m_hover_id == X)
        theta += 0.5 * PI;
    if (!is_approx(theta, 0.0))
        reset_cut_by_contours();
    Vec3d rotation = Vec3d::Zero();
    rotation[m_hover_id] = theta;
    const Transform3d rotation_tmp = m_start_dragging_m * rotation_transform(rotation);
    const bool update_tbb = !m_rotation_m.rotation().isApprox(rotation_tmp.rotation());
    m_rotation_m = rotation_tmp;
    if (update_tbb)
        m_transformed_bounding_box = transformed_bounding_box(m_plane_center, m_rotation_m);
    m_angle = theta;
    while (m_angle > two_pi)
        m_angle -= two_pi;
    if (m_angle < 0.0)
        m_angle += two_pi;
    update_clipper();
}
References acos(), Slic3r::cross2(), Slic3r::is_approx(), m_angle, Slic3r::GUI::GLGizmoBase::m_hover_id, m_plane_center, m_rotation_m, m_snap_coarse_in_radius, m_snap_coarse_out_radius, m_snap_fine_in_radius, m_snap_fine_out_radius, m_start_dragging_m, m_transformed_bounding_box, mouse_position_in_local_plane(), PI, reset_cut_by_contours(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotation(), Slic3r::Geometry::rotation_transform(), Slic3r::GUI::ScaleStepsCount, Slic3r::GUI::SnapRegionsCount, Slic3r::to_2d(), transformed_bounding_box(), update_clipper(), and X.
Referenced by on_dragging().
dragging_grabber_z()
void Slic3r::GUI::GLGizmoCut3D::dragging_grabber_z (const GLGizmoBase::UpdateData & data) protected
{
    const Vec3d grabber_init_pos        = (m_hover_id == CutPlane ? 0. : m_grabber_connection_len) * Vec3d::UnitZ();
    const Vec3d starting_drag_position  = translation_transform(m_plane_center) * m_rotation_m * grabber_init_pos;
    double      projection              = 0.0;
    Vec3d starting_vec = m_rotation_m * Vec3d::UnitZ();
    if (starting_vec.norm() != 0.0) {
        const Vec3d mouse_dir = data.mouse_ray.unit_vector();
        // finds the intersection of the mouse ray with the plane parallel to the camera viewport and passing throught the starting position
        // use ray-plane intersection see i.e. https://en.wikipedia.org/wiki/Line%E2%80%93plane_intersection algebric form
        // in our case plane normal and ray direction are the same (orthogonal view)
        // when moving to perspective camera the negative z unit axis of the camera needs to be transformed in world space and used as plane normal
        const Vec3d inters = data.mouse_ray.a + (starting_drag_position - data.mouse_ray.a).dot(mouse_dir) * mouse_dir;
        // vector from the starting position to the found intersection
        const Vec3d inters_vec = inters - starting_drag_position;
        starting_vec.normalize();
        // finds projection of the vector along the staring direction
        projection = inters_vec.dot(starting_vec);
    }
    if (wxGetKeyState(WXK_SHIFT))
        projection = m_snap_step * std::round(projection / m_snap_step);
    const Vec3d shift = starting_vec * projection;
    if (shift != Vec3d::Zero())
        reset_cut_by_contours();
    // move  cut plane center
    set_center(m_plane_center + shift, true);
    m_was_cut_plane_dragged = true;
}
References CutPlane, Slic3r::dot(), m_grabber_connection_len, Slic3r::GUI::GLGizmoBase::m_hover_id, m_plane_center, m_rotation_m, m_snap_step, m_was_cut_plane_dragged, reset_cut_by_contours(), set_center(), and Slic3r::Geometry::translation_transform().
Referenced by on_dragging().
flip_cut_plane()
void Slic3r::GUI::GLGizmoCut3D::flip_cut_plane () protected
{
    m_rotation_m = m_rotation_m * rotation_transform(PI * Vec3d::UnitX());
    m_transformed_bounding_box = transformed_bounding_box(m_plane_center, m_rotation_m);
    Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Flip cut plane"), UndoRedo::SnapshotType::GizmoAction);
    m_start_dragging_m = m_rotation_m;
    update_clipper();
    m_part_selection.turn_over_selection();
}
References _L, Slic3r::UndoRedo::GizmoAction, m_part_selection, m_plane_center, m_rotation_m, m_start_dragging_m, m_transformed_bounding_box, PI, Slic3r::GUI::plater(), Slic3r::Geometry::rotation_transform(), transformed_bounding_box(), Slic3r::GUI::GLGizmoCut3D::PartSelection::turn_over_selection(), and update_clipper().
Referenced by on_mouse(), and render_flip_plane_button().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoEmboss::init_font_name_texture(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), render_slider_double_input(), Slic3r::GUI::GLGizmoEmboss::rev_input(), Slic3r::GUI::GLGizmoEmboss::rev_input_mm(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
get_action_snapshot_name()
std::string Slic3r::GUI::GLGizmoCut3D::get_action_snapshot_name () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return _u8L("Cut gizmo editing"); }
References _u8L.
get_cut_matrix()
Transform3d Slic3r::GUI::GLGizmoCut3D::get_cut_matrix (const Selection & selection) protected
{
    const int instance_idx = selection.get_instance_idx();
    const int object_idx = selection.get_object_idx();
    ModelObject* mo = selection.get_model()->objects[object_idx];
    if (!mo)
        return Transform3d::Identity();
    // m_cut_z is the distance from the bed. Subtract possible SLA elevation.
    const double sla_shift_z = selection.get_first_volume()->get_sla_shift_z();
    const Vec3d instance_offset = mo->instances[instance_idx]->get_offset();
    Vec3d cut_center_offset = m_plane_center - instance_offset;
    cut_center_offset[Z] -= sla_shift_z;
    return translation_transform(cut_center_offset) * m_rotation_m;
}
References Slic3r::GUI::Selection::get_first_volume(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GLVolume::get_sla_shift_z(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::ModelObject::instances, m_plane_center, m_rotation_m, Slic3r::Model::objects, Slic3r::Geometry::translation_transform(), and Z.
Referenced by perform_cut(), and process_contours().
get_gizmo_entering_text()
std::string Slic3r::GUI::GLGizmoCut3D::get_gizmo_entering_text () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return _u8L("Entering Cut gizmo"); }
References _u8L.
get_gizmo_leaving_text()
std::string Slic3r::GUI::GLGizmoCut3D::get_gizmo_leaving_text () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return _u8L("Leaving Cut gizmo"); }
References _u8L.
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmosManager::grabber_contains_mouse(), on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), and Slic3r::GUI::GLGizmoSlaSupports::on_mouse().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    std::string out = on_get_name();
    if (!include_shortcut) return out;
    int key = get_shortcut_key();
    assert(key==NO_SHORTCUT_KEY_VALUE || (key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z));
    out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE, and Slic3r::GUI::GLGizmoBase::on_get_name().
Referenced by on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay().
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLCanvas3D::on_mouse().
get_tooltip()
std::string Slic3r::GUI::GLGizmoCut3D::get_tooltip () const override virtual
Mouse tooltip text.
Returns
Text to be visible in mouse tooltip
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    std::string tooltip;
    if (m_hover_id == Z || (m_dragging && m_hover_id == CutPlane)) {
        double koef = m_imperial_units ? ObjectManipulation::mm_to_in : 1.0;
        std::string unit_str = " " + (m_imperial_units ? _u8L("in") : _u8L("mm"));
        const BoundingBoxf3& tbb = m_transformed_bounding_box;
        const std::string name = m_keep_as_parts ? _u8L("Part") : _u8L("Object");
        if (tbb.max.z() >= 0.0) {
            double top = (tbb.min.z() <= 0.0 ? tbb.max.z() : tbb.size().z()) * koef;
            tooltip += format(static_cast<float>(top), 2) + " " + unit_str + " (" + name + " A)";
            if (tbb.min.z() <= 0.0)
                tooltip += "\n";
        }
        if (tbb.min.z() <= 0.0) {
            double bottom = (tbb.max.z() <= 0.0 ? tbb.size().z() : (tbb.min.z() * (-1))) * koef;
            tooltip += format(static_cast<float>(bottom), 2) + " " + unit_str + " (" + name + " B)";
        }
        return tooltip;
    }
    if (!m_dragging && m_hover_id == CutPlane)
        return _u8L("Click to flip the cut plane\n"
                    "Drag to move the cut plane\n"
                    "Right-click a part to assign it to the other side");
    if (tooltip.empty() && (m_hover_id == X || m_hover_id == Y)) {
        std::string axis = m_hover_id == X ? "X" : "Y";
        return axis + ": " + format(float(rad2deg(m_angle)), 1) + _u8L("");
    }
    return tooltip;
}
References _u8L, CutPlane, Slic3r::GUI::GLGizmoBase::format(), m_angle, Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_hover_id, m_imperial_units, m_keep_as_parts, m_transformed_bounding_box, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::GUI::ObjectManipulation::mm_to_in, Slic3r::Geometry::rad2deg(), Slic3r::BoundingBox3Base< PointType >::size(), X, Y, and Z.
gizmo_event()
bool Slic3r::GUI::GLGizmoCut3D::gizmo_event (SLAGizmoEventType action, const Vec2d & mouse_position, bool shift_down, bool alt_down, bool control_down)
{
    if (is_dragging() || m_connector_mode == CutConnectorMode::Auto)
        return false;
    if ( (m_hover_id < 0 || m_hover_id == CutPlane) && shift_down &&  ! m_connectors_editing &&
        (action == SLAGizmoEventType::LeftDown || action == SLAGizmoEventType::LeftUp || action == SLAGizmoEventType::Moving) )
        return process_cut_line(action, mouse_position);
    if (!m_keep_upper || !m_keep_lower)
        return false;
    if (!m_connectors_editing)
        return false;
    CutConnectors& connectors = m_c->selection_info()->model_object()->cut_connectors;
    if (action == SLAGizmoEventType::LeftDown) {
        if (shift_down || alt_down) {
            // left down with shift - show the selection rectangle:
            if (m_hover_id == -1)
                m_selection_rectangle.start_dragging(mouse_position, shift_down ? GLSelectionRectangle::EState::Select : GLSelectionRectangle::EState::Deselect);
        }
        else
            // If there is no selection and no hovering, add new point
            if (m_hover_id == -1 && !shift_down && !alt_down)
                if (!add_connector(connectors, mouse_position))
                    m_ldown_mouse_position = mouse_position;
        return true;
    }
    if (action == SLAGizmoEventType::LeftUp && !m_selection_rectangle.is_dragging()) {
        if ((m_ldown_mouse_position - mouse_position).norm() < 5.)
            unselect_all_connectors();
        return is_selection_changed(alt_down, shift_down);
    }
    // left up with selection rectangle - select points inside the rectangle:
    if ((action == SLAGizmoEventType::LeftUp || action == SLAGizmoEventType::ShiftUp || action == SLAGizmoEventType::AltUp) && m_selection_rectangle.is_dragging()) {
        // Is this a selection or deselection rectangle?
        process_selection_rectangle(connectors);
        return true;
    }
    // dragging the selection rectangle:
    if (action == SLAGizmoEventType::Dragging) {
        if (m_selection_rectangle.is_dragging()) {
            m_selection_rectangle.dragging(mouse_position);
            return true;
        }
        return false;
    }
    if (action == SLAGizmoEventType::RightDown && !shift_down) {
        // If any point is in hover state, this should initiate its move - return control back to GLCanvas:
        if (m_hover_id < m_connectors_group_id)
            return false;
        unselect_all_connectors();
        select_connector(m_hover_id - m_connectors_group_id, true);
        return delete_selected_connectors(connectors);
    }
    if (action == SLAGizmoEventType::Delete)
        return delete_selected_connectors(connectors);
    if (action == SLAGizmoEventType::SelectAll) {
        select_all_connectors();
        return true;
    }
    return false;
}
References add_connector(), Slic3r::GUI::AltUp, Auto, Slic3r::ModelObject::cut_connectors, CutPlane, Slic3r::GUI::Delete, delete_selected_connectors(), Slic3r::GUI::GLSelectionRectangle::Deselect, Slic3r::GUI::Dragging, Slic3r::GUI::GLSelectionRectangle::dragging(), Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLSelectionRectangle::is_dragging(), is_selection_changed(), Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, Slic3r::GUI::GLGizmoBase::m_c, m_connector_mode, m_connectors_editing, m_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_hover_id, m_keep_lower, m_keep_upper, m_ldown_mouse_position, m_selection_rectangle, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::Moving, process_cut_line(), process_selection_rectangle(), Slic3r::GUI::RightDown, Slic3r::GUI::GLSelectionRectangle::Select, select_all_connectors(), select_connector(), Slic3r::GUI::SelectAll, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::ShiftUp, Slic3r::GUI::GLSelectionRectangle::start_dragging(), and unselect_all_connectors().
Referenced by on_mouse().
has_valid_contour()
bool Slic3r::GUI::GLGizmoCut3D::has_valid_contour () const private
{
    const auto clipper = m_c->object_clipper();
    return clipper && clipper->has_valid_contour();
}
References Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::has_valid_contour(), Slic3r::GUI::GLGizmoBase::m_c, and Slic3r::GUI::CommonGizmosDataPool::object_clipper().
Referenced by render_cut_plane(), and render_input_window_warning().
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_init().
init_connector_shapes()
void Slic3r::GUI::GLGizmoCut3D::init_connector_shapes () private
{
    for (const CutConnectorType& type : {CutConnectorType::Dowel, CutConnectorType::Plug})
        for (const CutConnectorStyle& style : {CutConnectorStyle::Frustum, CutConnectorStyle::Prism}) {
            if (type == CutConnectorType::Dowel && style == CutConnectorStyle::Frustum)
                continue;
            for (const CutConnectorShape& shape : {CutConnectorShape::Circle, CutConnectorShape::Hexagon, CutConnectorShape::Square, CutConnectorShape::Triangle}) {
                const CutConnectorAttributes attribs = { type, style, shape };
                const indexed_triangle_set its = ModelObject::get_connector_mesh(attribs);
                m_shapes[attribs].model.init_from(its);
                m_shapes[attribs].mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
            }
        }
}
References Slic3r::Circle, Slic3r::Dowel, Slic3r::Frustum, Slic3r::ModelObject::get_connector_mesh(), Slic3r::Hexagon, m_shapes, Slic3r::Plug, Slic3r::Prism, Slic3r::Square, style, and Slic3r::Triangle.
Referenced by init_picking_models().
init_input_window_data()
void Slic3r::GUI::GLGizmoCut3D::init_input_window_data (CutConnectors & connectors) protected
{
    m_imperial_units = wxGetApp().app_config->get_bool("use_inches");
    m_control_width  = m_imgui->get_font_size() * 9.f;
    if (m_connectors_editing && m_selected_count > 0) {
        float               depth_ratio             { UndefFloat };
        float               depth_ratio_tolerance   { UndefFloat };
        float               radius                  { UndefFloat };
        float               radius_tolerance        { UndefFloat };
        CutConnectorType    type                    { CutConnectorType::Undef };
        CutConnectorStyle   style                   { CutConnectorStyle::Undef };
        CutConnectorShape   shape                   { CutConnectorShape::Undef };
        bool is_init = false;
        for (size_t idx = 0; idx < m_selected.size(); idx++)
            if (m_selected[idx]) {
                const CutConnector& connector = connectors[idx];
                if (!is_init) {
                    depth_ratio             = connector.height;
                    depth_ratio_tolerance   = connector.height_tolerance;
                    radius                  = connector.radius;
                    radius_tolerance        = connector.radius_tolerance;
                    type                    = connector.attribs.type;
                    style                   = connector.attribs.style;
                    shape                   = connector.attribs.shape;
                    if (m_selected_count == 1)
                        break;
                    is_init = true;
                }
                else {
                    if (!is_approx(depth_ratio, connector.height))
                        depth_ratio         = UndefFloat;
                    if (!is_approx(depth_ratio_tolerance, connector.height_tolerance))
                        depth_ratio_tolerance = UndefFloat;
                    if (!is_approx(radius,connector.radius))
                        radius              = UndefFloat;
                    if (!is_approx(radius_tolerance, connector.radius_tolerance))
                        radius_tolerance    = UndefFloat;
                    if (type != connector.attribs.type)
                        type = CutConnectorType::Undef;
                    if (style != connector.attribs.style)
                        style = CutConnectorStyle::Undef;
                    if (shape != connector.attribs.shape)
                        shape = CutConnectorShape::Undef;
                }
            }
        m_connector_depth_ratio             = depth_ratio;
        m_connector_depth_ratio_tolerance   = depth_ratio_tolerance;
        m_connector_size                    = 2.f * radius;
        m_connector_size_tolerance          = 2.f * radius_tolerance;
        m_connector_type                    = type;
        m_connector_style                   = int(style);
        m_connector_shape_id                = int(shape);
    }
    if (m_label_width == 0.f) {
        for (const auto& item : m_labels_map) {
            const float width = ImGuiWrapper::calc_text_size(item.second).x;
            if (m_label_width < width)
                m_label_width = width;
        }
        m_label_width += m_imgui->scaled(1.f);
    }
}
References Slic3r::CutConnector::attribs, Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::GUI::ImGuiWrapper::get_font_size(), Slic3r::CutConnector::height, Slic3r::CutConnector::height_tolerance, Slic3r::is_approx(), m_connector_depth_ratio, m_connector_depth_ratio_tolerance, m_connector_shape_id, m_connector_size, m_connector_size_tolerance, m_connector_style, m_connector_type, m_connectors_editing, m_control_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_imperial_units, m_label_width, m_labels_map, m_selected, m_selected_count, Slic3r::CutConnector::radius, Slic3r::CutConnector::radius_tolerance, Slic3r::GUI::ImGuiWrapper::scaled(), Slic3r::CutConnectorAttributes::shape, Slic3r::CutConnectorAttributes::style, style, Slic3r::CutConnectorAttributes::type, Slic3r::Undef, Slic3r::GUI::UndefFloat, and ImVec2::x.
Referenced by on_render_input_window().
init_picking_models()
void Slic3r::GUI::GLGizmoCut3D::init_picking_models () private
{
    if (!m_cone.model.is_initialized()) {
        indexed_triangle_set its = its_make_cone(1.0, 1.0, PI / 12.0);
        m_cone.model.init_from(its);
        m_cone.mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
    }
    if (!m_sphere.model.is_initialized()) {
        indexed_triangle_set its = its_make_sphere(1.0, PI / 12.0);
        m_sphere.model.init_from(its);
        m_sphere.mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
    }
    if (!m_plane.model.is_initialized() && !m_hide_cut_plane && !m_connectors_editing) {
        const double cp_width = 0.02 * get_grabber_mean_size(m_bounding_box);
        indexed_triangle_set its = its_make_frustum_dowel((double)m_cut_plane_radius_koef * m_radius, cp_width, m_cut_plane_as_circle ? 180 : 4);
        m_plane.model.init_from(its);
        m_plane.mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
    }
    if (m_shapes.empty())
        init_connector_shapes();
}
References Slic3r::GUI::get_grabber_mean_size(), init_connector_shapes(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::its_make_cone(), Slic3r::its_make_frustum_dowel(), Slic3r::its_make_sphere(), m_bounding_box, m_cone, m_connectors_editing, m_cut_plane_as_circle, m_cut_plane_radius_koef, m_hide_cut_plane, m_plane, m_radius, m_shapes, m_sphere, Slic3r::GUI::PickingModel::mesh_raycaster, Slic3r::GUI::PickingModel::model, and PI.
Referenced by on_register_raycasters_for_picking(), and on_render().
init_rendering_items()
void Slic3r::GUI::GLGizmoCut3D::init_rendering_items () private
{
    if (!m_grabber_connection.is_initialized())
        m_grabber_connection.init_from(its_make_line(Vec3f::Zero(), Vec3f::UnitZ()));
    if (!m_circle.is_initialized())
        init_from_circle(m_circle, m_grabber_radius);
    if (!m_scale.is_initialized())
        init_from_scale(m_scale, m_grabber_radius);
    if (!m_snap_radii.is_initialized())
        init_from_snap_radii(m_snap_radii, m_grabber_radius);
    if (!m_reference_radius.is_initialized()) {
        m_reference_radius.init_from(its_make_line(Vec3f::Zero(), m_grabber_connection_len * Vec3f::UnitX()));
        m_reference_radius.set_color(ColorRGBA::WHITE());
    }
    if (!m_angle_arc.is_initialized() || m_angle != 0.0)
        init_from_angle_arc(m_angle_arc, m_angle, m_grabber_connection_len);
}
References Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::init_from_angle_arc(), Slic3r::GUI::init_from_circle(), Slic3r::GUI::init_from_scale(), Slic3r::GUI::init_from_snap_radii(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::its_make_line(), m_angle, m_angle_arc, m_circle, m_grabber_connection, m_grabber_connection_len, m_grabber_radius, m_reference_radius, m_scale, m_snap_radii, Slic3r::GUI::GLModel::set_color(), and Slic3r::ColorRGBA::WHITE().
Referenced by on_render().
invalidate_cut_plane()
void Slic3r::GUI::GLGizmoCut3D::invalidate_cut_plane ()
{
    m_rotation_m    = Transform3d::Identity();
    m_plane_center  = Vec3d::Zero();
    m_min_pos       = Vec3d::Zero();
    m_max_pos       = Vec3d::Zero();
    m_bb_center     = Vec3d::Zero();
    m_center_offset = Vec3d::Zero();
}
References Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), m_bb_center, m_center_offset, m_max_pos, m_min_pos, m_plane_center, and m_rotation_m.
Referenced by update_bb().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmosManager::handle_shortcut(), Slic3r::GUI::GLGizmoEmboss::init_create(), and Slic3r::GUI::GLGizmosManager::update_hover_state().
is_conflict_for_connector()
bool Slic3r::GUI::GLGizmoCut3D::is_conflict_for_connector (size_t idx, const CutConnectors & connectors, const Vec3d cur_pos) private
{
    if (is_outside_of_cut_contour(idx, connectors, cur_pos))
        return true;
    const CutConnector& cur_connector = connectors[idx];
    const Transform3d matrix = translation_transform(cur_pos) * m_rotation_m *
                               scale_transform(Vec3f(cur_connector.radius, cur_connector.radius, cur_connector.height).cast<double>());
    const BoundingBoxf3 cur_tbb = m_shapes[cur_connector.attribs].model.get_bounding_box().transformed(matrix);
    // check if connector's bounding box is inside the object's bounding box
    if (!m_bounding_box.contains(cur_tbb)) {
        m_info_stats.outside_bb++;
        return true;
    }
    // check if connectors are overlapping
    for (size_t i = 0; i < connectors.size(); ++i) {
        if (i == idx)
            continue;
        const CutConnector& connector = connectors[i];
        if ((connector.pos - cur_connector.pos).norm() < double(connector.radius + cur_connector.radius)) {
            m_info_stats.is_overlap = true;
            return true;
        }
    }
    return false;
}
References Slic3r::CutConnector::attribs, Slic3r::BoundingBox3Base< PointType >::contains(), Slic3r::CutConnector::height, is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoCut3D::InvalidConnectorsStatistics::is_overlap, m_bounding_box, m_info_stats, m_rotation_m, m_shapes, Slic3r::GUI::GLGizmoCut3D::InvalidConnectorsStatistics::outside_bb, Slic3r::CutConnector::pos, Slic3r::CutConnector::radius, Slic3r::Geometry::scale_transform(), and Slic3r::Geometry::translation_transform().
Referenced by check_and_update_connectors_state().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
Referenced by gizmo_event(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate().
is_in_editing_mode()
bool Slic3r::GUI::GLGizmoCut3D::is_in_editing_mode () const inline override virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return m_connectors_editing; }
References m_connectors_editing.
is_looking_forward()
bool Slic3r::GUI::GLGizmoCut3D::is_looking_forward () const
{
    const Camera& camera = wxGetApp().plater()->get_camera();
    const double dot = camera.get_dir_forward().dot(m_cut_normal);
    return dot < 0.05;
}
References Slic3r::dot(), Slic3r::GUI::Camera::get_dir_forward(), and m_cut_normal.
Referenced by Slic3r::GUI::GLGizmoCut3D::PartSelection::render(), render_connectors(), update_clipper(), and update_raycasters_for_picking_transform().
is_outside_of_cut_contour()
bool Slic3r::GUI::GLGizmoCut3D::is_outside_of_cut_contour (size_t idx, const CutConnectors & connectors, const Vec3d cur_pos) private
{
    // check if connector pos is out of clipping plane
    if (m_c->object_clipper() && m_c->object_clipper()->is_projection_inside_cut(cur_pos) == -1) {
        m_info_stats.outside_cut_contour++;
        return true;
    }
    // check if connector bottom contour is out of clipping plane
    const CutConnector& cur_connector = connectors[idx];
    const CutConnectorShape shape = CutConnectorShape(cur_connector.attribs.shape);
    const int   sectorCount = shape == CutConnectorShape::Triangle  ? 3 :
                              shape == CutConnectorShape::Square    ? 4 :
                              shape == CutConnectorShape::Circle    ? 60: // supposably, 60 points are enough for conflict detection
                              shape == CutConnectorShape::Hexagon   ? 6 : 1 ;
    indexed_triangle_set mesh;
    auto& vertices = mesh.vertices;
    vertices.reserve(sectorCount + 1);
    float fa = 2 * PI / sectorCount;
    auto vec = Eigen::Vector2f(0, cur_connector.radius);
    for (float angle = 0; angle < 2.f * PI; angle += fa) {
        Vec2f p = Eigen::Rotation2Df(angle) * vec;
        vertices.emplace_back(Vec3f(p(0), p(1), 0.f));
    }
    its_transform(mesh, translation_transform(cur_pos) * m_rotation_m);
    for (const Vec3f& vertex : vertices) {
        if (m_c->object_clipper()) {
            int contour_idx = m_c->object_clipper()->is_projection_inside_cut(vertex.cast<double>());
            bool is_invalid = (contour_idx == -1);
            if (m_part_selection.valid() && ! is_invalid) {
                assert(contour_idx >= 0);
                const std::vector<size_t>& ignored = *(m_part_selection.get_ignored_contours_ptr());
                is_invalid = (std::find(ignored.begin(), ignored.end(), size_t(contour_idx)) != ignored.end());
            }
            if (is_invalid) {
                m_info_stats.outside_cut_contour++;
                return true;
            }
        }
    }
    return false;
}
References Slic3r::angle(), Slic3r::CutConnector::attribs, Slic3r::Circle, Slic3r::GUI::GLGizmoCut3D::PartSelection::get_ignored_contours_ptr(), Slic3r::Hexagon, Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::is_projection_inside_cut(), its_transform(), Slic3r::GUI::GLGizmoBase::m_c, m_info_stats, m_part_selection, m_rotation_m, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::GLGizmoCut3D::InvalidConnectorsStatistics::outside_cut_contour, PI, Slic3r::CutConnector::radius, Slic3r::CutConnectorAttributes::shape, Slic3r::Square, Slic3r::Geometry::translation_transform(), Slic3r::Triangle, Slic3r::GUI::GLGizmoCut3D::PartSelection::valid(), and indexed_triangle_set::vertices.
Referenced by is_conflict_for_connector().
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
is_selection_changed()
bool Slic3r::GUI::GLGizmoCut3D::is_selection_changed (bool alt_down, bool shift_down) protected
{
    if (m_hover_id >= m_connectors_group_id) {
        if (alt_down)
            select_connector(m_hover_id - m_connectors_group_id, false);
        else {
            if (!shift_down)
                unselect_all_connectors();
            select_connector(m_hover_id - m_connectors_group_id, true);
        }
        return true;
    }
    return false;
}
References m_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_hover_id, select_connector(), and unselect_all_connectors().
Referenced by gizmo_event().
is_selection_rectangle_dragging()
bool Slic3r::GUI::GLGizmoCut3D::is_selection_rectangle_dragging () const inline override virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return m_selection_rectangle.is_dragging(); }
References Slic3r::GUI::GLSelectionRectangle::is_dragging(), and m_selection_rectangle.
load()
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
mouse_position_in_local_plane()
Vec3d Slic3r::GUI::GLGizmoCut3D::mouse_position_in_local_plane (GrabberID axis, const Linef3 & mouse_ray) const protected
{
    double half_pi = 0.5 * PI;
    Transform3d m = Transform3d::Identity();
    switch (axis)
    {
    case X:
    {
        m.rotate(Eigen::AngleAxisd(half_pi, Vec3d::UnitZ()));
        m.rotate(Eigen::AngleAxisd(-half_pi, Vec3d::UnitY()));
        break;
    }
    case Y:
    {
        m.rotate(Eigen::AngleAxisd(half_pi, Vec3d::UnitY()));
        m.rotate(Eigen::AngleAxisd(half_pi, Vec3d::UnitZ()));
        break;
    }
    default:
    case Z:
    {
        // no rotation applied
        break;
    }
    }
    m = m * m_start_dragging_m.inverse();
    m.translate(-m_plane_center);
    return transform(mouse_ray, m).intersect_plane(0.0);
}
References Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::Linef3::intersect_plane(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), m_plane_center, m_start_dragging_m, PI, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotate(), Slic3r::transform(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), X, Y, and Z.
Referenced by dragging_grabber_xy().
on_disable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_disable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_dragging()
void Slic3r::GUI::GLGizmoCut3D::on_dragging (const UpdateData & data) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_hover_id < 0)
        return;
    if (m_hover_id == Z || m_hover_id == CutPlane)
        dragging_grabber_z(data);
    else if (m_hover_id == X || m_hover_id == Y)
        dragging_grabber_xy(data);
    else if (m_hover_id >= m_connectors_group_id && m_connector_mode == CutConnectorMode::Manual)
        dragging_connector(data);
    check_and_update_connectors_state();
}
References check_and_update_connectors_state(), CutPlane, dragging_connector(), dragging_grabber_xy(), dragging_grabber_z(), m_connector_mode, m_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_hover_id, Manual, X, Y, and Z.
on_enable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_enable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoEmboss, and Slic3r::GUI::GLGizmoRotate3D.
{}
on_get_name()
std::string Slic3r::GUI::GLGizmoCut3D::on_get_name () const override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    return _u8L("Cut");
}
References _u8L.
on_get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoCut3D::on_get_requirements () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return CommonGizmosDataID(
                int(CommonGizmosDataID::SelectionInfo)
              | int(CommonGizmosDataID::InstancesHider)
              | int(CommonGizmosDataID::ObjectClipper));
}
References Slic3r::GUI::InstancesHider, Slic3r::GUI::ObjectClipper, and Slic3r::GUI::SelectionInfo.
on_init()
bool Slic3r::GUI::GLGizmoCut3D::on_init () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    m_grabbers.emplace_back();
    m_shortcut_key = WXK_CONTROL_C;
    // initiate info shortcuts
    const wxString ctrl  = GUI::shortkey_ctrl_prefix();
    const wxString alt   = GUI::shortkey_alt_prefix();
    const wxString shift = "Shift+";
    m_shortcuts.push_back(std::make_pair(_L("Left click"),         _L("Add connector")));
    m_shortcuts.push_back(std::make_pair(_L("Right click"),        _L("Remove connector")));
    m_shortcuts.push_back(std::make_pair(_L("Drag"),               _L("Move connector")));
    m_shortcuts.push_back(std::make_pair(shift + _L("Left click"), _L("Add connector to selection")));
    m_shortcuts.push_back(std::make_pair(alt   + _L("Left click"), _L("Remove connector from selection")));
    m_shortcuts.push_back(std::make_pair(ctrl  + "A",              _L("Select all connectors")));
    return true;
}
References _L, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_shortcut_key, m_shortcuts, Slic3r::GUI::shortkey_alt_prefix(), and Slic3r::GUI::shortkey_ctrl_prefix().
on_is_activable()
bool Slic3r::GUI::GLGizmoCut3D::on_is_activable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    const Selection& selection = m_parent.get_selection();
    const int object_idx = selection.get_object_idx();
    if (object_idx < 0 || selection.is_wipe_tower())
        return false;
    if (const ModelObject* mo = wxGetApp().plater()->model().objects[object_idx];
        mo->is_cut() && mo->volumes.size() == 1) {
        const ModelVolume* volume = mo->volumes[0];
        if (volume->is_cut_connector() && volume->cut_info.connector_type == CutConnectorType::Dowel)
            return false;
    }
    // This is assumed in GLCanvas3D::do_rotate, do not change this
    // without updating that function too.
    return selection.is_single_full_instance() && !m_parent.is_layers_editing_enabled();
}
References Slic3r::Dowel, Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::GLCanvas3D::is_layers_editing_enabled(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_wipe_tower(), Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::GUI::plater().
on_is_selectable()
bool Slic3r::GUI::GLGizmoCut3D::on_is_selectable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return wxGetApp().get_mode() != comSimple;
}
References Slic3r::comSimple.
on_load()
void Slic3r::GUI::GLGizmoCut3D::on_load (cereal::BinaryInputArchive & ar) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar( m_keep_upper, m_keep_lower, m_rotate_lower, m_rotate_upper, m_hide_cut_plane, m_mode, m_connectors_editing,
        m_ar_plane_center, m_rotation_m);
    m_transformed_bounding_box = transformed_bounding_box(m_ar_plane_center, m_rotation_m);
    set_center_pos(m_ar_plane_center);
    m_parent.request_extra_frame();
}
References m_ar_plane_center, m_connectors_editing, m_hide_cut_plane, m_keep_lower, m_keep_upper, m_mode, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_lower, m_rotate_upper, m_rotation_m, m_transformed_bounding_box, Slic3r::GUI::GLCanvas3D::request_extra_frame(), set_center_pos(), and transformed_bounding_box().
on_mouse()
bool Slic3r::GUI::GLGizmoCut3D::on_mouse (const wxMouseEvent & mouse_event) override virtual
Drag of plane.
Parameters
mouse_event Keep information about mouse click
Returns
Return True when use the information otherwise False.
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    Vec2i mouse_coord(mouse_event.GetX(), mouse_event.GetY());
    Vec2d mouse_pos = mouse_coord.cast<double>();
    if (mouse_event.ShiftDown() && mouse_event.LeftDown())
        return gizmo_event(SLAGizmoEventType::LeftDown, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), mouse_event.CmdDown());
    if (mouse_event.CmdDown() && mouse_event.LeftDown())
        return false;
    if (cut_line_processing()) {
        if (mouse_event.ShiftDown()) {
            if (mouse_event.Moving()|| mouse_event.Dragging())
                return gizmo_event(SLAGizmoEventType::Moving, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), mouse_event.CmdDown());
            if (mouse_event.LeftUp())
                return gizmo_event(SLAGizmoEventType::LeftUp, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), mouse_event.CmdDown());
        }
        discard_cut_line_processing();
    }
    else if (mouse_event.Moving())
        return false;
    if (use_grabbers(mouse_event)) {
        if (m_hover_id >= m_connectors_group_id) {
            if (mouse_event.LeftDown() && !mouse_event.CmdDown() && !mouse_event.AltDown())
                unselect_all_connectors();
            if (mouse_event.LeftUp() && !mouse_event.ShiftDown())
                gizmo_event(SLAGizmoEventType::LeftUp, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), mouse_event.CmdDown());
        }
        else if (m_hover_id == CutPlane) {
            if (mouse_event.LeftDown()) {
                m_was_cut_plane_dragged = m_was_contour_selected = false;
                // disable / enable current contour
                Vec3d pos;
                Vec3d pos_world;
                m_was_contour_selected = unproject_on_cut_plane(mouse_pos.cast<double>(), pos, pos_world, false);
                if (m_was_contour_selected) {
                    // Following would inform the clipper about the mouse click, so it can
                    // toggle the respective contour as disabled.
                    //m_c->object_clipper()->pass_mouse_click(pos_world);
                    //process_contours();
                    return true;
                }
            }
            else if (mouse_event.LeftUp() && !m_was_cut_plane_dragged && !m_was_contour_selected)
                flip_cut_plane();
        }
        if (m_part_selection.valid())
            m_parent.toggle_model_objects_visibility(false);
        return true;
    }
    static bool pending_right_up = false;
    if (mouse_event.LeftDown()) {
        bool grabber_contains_mouse = (get_hover_id() != -1);
        const bool shift_down = mouse_event.ShiftDown();
        if ((!shift_down || grabber_contains_mouse) &&
            gizmo_event(SLAGizmoEventType::LeftDown, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), false))
            return true;
    }
    else if (mouse_event.Dragging()) {
        bool control_down = mouse_event.CmdDown();
        if (m_parent.get_move_volume_id() != -1) {
            // don't allow dragging objects with the Sla gizmo on
            return true;
        }
        if (!control_down &&
            gizmo_event(SLAGizmoEventType::Dragging, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), false)) {
            // the gizmo got the event and took some action, no need to do
            // anything more here
            m_parent.set_as_dirty();
            return true;
        }
        if (control_down && (mouse_event.LeftIsDown() || mouse_event.RightIsDown())) {
            // CTRL has been pressed while already dragging -> stop current action
            if (mouse_event.LeftIsDown())
                gizmo_event(SLAGizmoEventType::LeftUp, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), true);
            else if (mouse_event.RightIsDown())
                pending_right_up = false;
        }
    }
    else if (mouse_event.LeftUp() && !m_parent.is_mouse_dragging()) {
        // in case SLA/FDM gizmo is selected, we just pass the LeftUp event
        // and stop processing - neither object moving or selecting is
        // suppressed in that case
        gizmo_event(SLAGizmoEventType::LeftUp, mouse_pos, mouse_event.ShiftDown(), mouse_event.AltDown(), mouse_event.CmdDown());
        return true;
    }
    else if (mouse_event.RightDown()) {
        if (! m_connectors_editing && mouse_event.GetModifiers() == wxMOD_NONE) {
            // Check the internal part raycasters.
            if (! m_part_selection.valid())
                process_contours();
            m_part_selection.toggle_selection(mouse_pos);
            check_and_update_connectors_state(); // after a contour is deactivated, its connectors are inside the object
            return true;
        }
        if (m_parent.get_selection().get_object_idx() != -1 &&
            gizmo_event(SLAGizmoEventType::RightDown, mouse_pos, false, false, false)) {
            // we need to set the following right up as processed to avoid showing
            // the context menu if the user release the mouse over the object
            pending_right_up = true;
            // event was taken care of by the SlaSupports gizmo
            return true;
        }
    }
    else if (pending_right_up && mouse_event.RightUp()) {
        pending_right_up = false;
        return true;
    }
    return false;
}
References check_and_update_connectors_state(), cut_line_processing(), CutPlane, discard_cut_line_processing(), Slic3r::GUI::Dragging, flip_cut_plane(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLCanvas3D::get_move_volume_id(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), gizmo_event(), Slic3r::GUI::GLCanvas3D::is_mouse_dragging(), Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, m_connectors_editing, m_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::GLGizmoBase::m_parent, m_part_selection, m_was_contour_selected, m_was_cut_plane_dragged, Slic3r::GUI::Moving, process_contours(), Slic3r::GUI::RightDown, Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility(), Slic3r::GUI::GLGizmoCut3D::PartSelection::toggle_selection(), unproject_on_cut_plane(), unselect_all_connectors(), Slic3r::GUI::GLGizmoBase::use_grabbers(), and Slic3r::GUI::GLGizmoCut3D::PartSelection::valid().
on_register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    assert(m_raycasters.empty());
    // the gizmo grabbers are rendered on top of the scene, so the raytraced picker should take it into account
    m_parent.set_raycaster_gizmos_on_top(true);
    init_picking_models();
    if (m_connectors_editing) {
        if (CommonGizmosDataObjects::SelectionInfo* si = m_c->selection_info()) {
            const CutConnectors& connectors = si->model_object()->cut_connectors;
            for (int i = 0; i < int(connectors.size()); ++i)
                m_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, i + m_connectors_group_id, *(m_shapes[connectors[i].attribs]).mesh_raycaster, Transform3d::Identity()));
        }
    }
    else if (!cut_line_processing()) {
        m_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, X, *m_cone.mesh_raycaster, Transform3d::Identity()));
        m_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, X, *m_cone.mesh_raycaster, Transform3d::Identity()));
        m_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, Y, *m_cone.mesh_raycaster, Transform3d::Identity()));
        m_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, Y, *m_cone.mesh_raycaster, Transform3d::Identity()));
        m_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, Z, *m_sphere.mesh_raycaster, Transform3d::Identity()));
        m_raycasters.emplace_back(m_parent.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, CutPlane, *m_plane.mesh_raycaster, Transform3d::Identity()));
    }
    update_raycasters_for_picking_transform();
}
References Slic3r::GUI::GLCanvas3D::add_raycaster_for_picking(), cut_line_processing(), CutPlane, Slic3r::GUI::SceneRaycaster::Gizmo, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), init_picking_models(), Slic3r::GUI::GLGizmoBase::m_c, m_cone, m_connectors_editing, m_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_parent, m_plane, m_raycasters, m_shapes, m_sphere, Slic3r::GUI::PickingModel::mesh_raycaster, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLCanvas3D::set_raycaster_gizmos_on_top(), update_raycasters_for_picking_transform(), X, Y, and Z.
Referenced by update_clipper(), and update_raycasters_for_picking().
on_render()
void Slic3r::GUI::GLGizmoCut3D::on_render () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    if (m_state == On) {
        // This gizmo is showing the object elevated. Tell the common
        // SelectionInfo object to lie about the actual shift.
        m_c->selection_info()->set_use_shift(true);
    }
    update_clipper();
    init_picking_models();
    init_rendering_items();
    render_connectors();
    if (!m_connectors_editing)
        m_part_selection.render(nullptr, m_sphere.model);
    else
        m_part_selection.render(&m_cut_normal, m_sphere.model);
    render_clipper_cut();
    if (!m_hide_cut_plane && !m_connectors_editing) {
        render_cut_plane();
        render_cut_plane_grabbers();
    }
    render_cut_line();
    m_selection_rectangle.render(m_parent);
}
References init_picking_models(), init_rendering_items(), Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, m_cut_normal, m_hide_cut_plane, Slic3r::GUI::GLGizmoBase::m_parent, m_part_selection, m_selection_rectangle, m_sphere, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::PickingModel::model, Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLGizmoCut3D::PartSelection::render(), render_clipper_cut(), render_connectors(), render_cut_line(), render_cut_plane(), render_cut_plane_grabbers(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::set_use_shift(), and update_clipper().
on_render_input_window()
void Slic3r::GUI::GLGizmoCut3D::on_render_input_window (float x, float y, float bottom_limit) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    m_imgui->begin(get_name(), ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse);
    // adjust window position to avoid overlap the view toolbar
    adjust_window_position(x, y, bottom_limit);
    CutConnectors& connectors = m_c->selection_info()->model_object()->cut_connectors;
    init_input_window_data(connectors);
    if (m_connectors_editing) // connectors mode
        render_connectors_input_window(connectors);
    else
        render_cut_plane_input_window(connectors);
    render_input_window_warning();
    m_imgui->end();
    if (!m_connectors_editing) // connectors mode
        render_debug_input_window(x);
}
References adjust_window_position(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::ModelObject::cut_connectors, Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLGizmoBase::get_name(), ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, init_input_window_data(), Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), render_connectors_input_window(), render_cut_plane_input_window(), render_debug_input_window(), render_input_window_warning(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
on_save()
void Slic3r::GUI::GLGizmoCut3D::on_save (cereal::BinaryOutputArchive & ar) const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar( m_keep_upper, m_keep_lower, m_rotate_lower, m_rotate_upper, m_hide_cut_plane, m_mode, m_connectors_editing,
        m_ar_plane_center, m_start_dragging_m);
}
References m_ar_plane_center, m_connectors_editing, m_hide_cut_plane, m_keep_lower, m_keep_upper, m_mode, m_rotate_lower, m_rotate_upper, and m_start_dragging_m.
on_set_hover_id()
void Slic3r::GUI::GLGizmoCut3D::on_set_hover_id () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
}
on_set_state()
void Slic3r::GUI::GLGizmoCut3D::on_set_state () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_state == On) {
        m_parent.set_use_color_clip_plane(true);
        m_parent.set_color_clip_plane_colors({ UPPER_PART_COLOR , LOWER_PART_COLOR });
        update_bb();
        m_connectors_editing = !m_selected.empty();
        m_transformed_bounding_box = transformed_bounding_box(m_plane_center, m_rotation_m);
        // initiate archived values
        m_ar_plane_center   = m_plane_center;
        m_start_dragging_m  = m_rotation_m;
        reset_cut_by_contours();
        m_parent.request_extra_frame();
    }
    else {
        if (auto oc = m_c->object_clipper()) {
            oc->set_behavior(true, true, 0.);
            oc->release();
        }
        m_selected.clear();
        m_parent.set_use_color_clip_plane(false);
        m_c->selection_info()->set_use_shift(false);
        // Make sure that the part selection data are released when the gizmo is closed.
        // The CallAfter is needed because in perform_cut, the gizmo is closed BEFORE
        // the cut is performed (because of undo/redo snapshots), so the data would
        // be deleted prematurely.
        if (m_part_selection.valid())
            wxGetApp().CallAfter([this]() { m_part_selection = PartSelection(); });
    }
}
References Slic3r::GUI::LOWER_PART_COLOR, m_ar_plane_center, Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, Slic3r::GUI::GLGizmoBase::m_parent, m_part_selection, m_plane_center, m_rotation_m, m_selected, m_start_dragging_m, Slic3r::GUI::GLGizmoBase::m_state, m_transformed_bounding_box, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::GLCanvas3D::request_extra_frame(), reset_cut_by_contours(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLCanvas3D::set_color_clip_plane_colors(), Slic3r::GUI::GLCanvas3D::set_use_color_clip_plane(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::set_use_shift(), transformed_bounding_box(), update_bb(), Slic3r::GUI::UPPER_PART_COLOR, and Slic3r::GUI::GLGizmoCut3D::PartSelection::valid().
on_start_dragging()
void Slic3r::GUI::GLGizmoCut3D::on_start_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    m_angle = 0.0;
    if (m_hover_id >= m_connectors_group_id && m_connector_mode == CutConnectorMode::Manual)
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Move connector"), UndoRedo::SnapshotType::GizmoAction);
    if (m_hover_id == X || m_hover_id == Y)
        m_start_dragging_m = m_rotation_m;
}
References _L, Slic3r::UndoRedo::GizmoAction, m_angle, m_connector_mode, m_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_hover_id, m_rotation_m, m_start_dragging_m, Manual, Slic3r::GUI::plater(), X, and Y.
on_stop_dragging()
void Slic3r::GUI::GLGizmoCut3D::on_stop_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_hover_id == X || m_hover_id == Y) {
        m_angle_arc.reset();
        m_angle = 0.0;
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Rotate cut plane"), UndoRedo::SnapshotType::GizmoAction);
        m_start_dragging_m = m_rotation_m;
    }
    else if (m_hover_id == Z || m_hover_id == CutPlane) {
        if (m_was_cut_plane_dragged)
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Move cut plane"), UndoRedo::SnapshotType::GizmoAction);
        m_ar_plane_center = m_plane_center;
    }
    //check_and_update_connectors_state();
}
References _L, CutPlane, Slic3r::UndoRedo::GizmoAction, m_angle, m_angle_arc, m_ar_plane_center, Slic3r::GUI::GLGizmoBase::m_hover_id, m_plane_center, m_rotation_m, m_start_dragging_m, m_was_cut_plane_dragged, Slic3r::GUI::plater(), Slic3r::GUI::GLModel::reset(), X, Y, and Z.
on_unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoCut3D::on_unregister_raycasters_for_picking () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    m_parent.remove_raycasters_for_picking(SceneRaycaster::EType::Gizmo);
    m_raycasters.clear();
    // the gizmo grabbers are rendered on top of the scene, so the raytraced picker should take it into account
    m_parent.set_raycaster_gizmos_on_top(false);
}
References Slic3r::GUI::SceneRaycaster::Gizmo, Slic3r::GUI::GLGizmoBase::m_parent, m_raycasters, Slic3r::GUI::GLCanvas3D::remove_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::set_raycaster_gizmos_on_top().
Referenced by process_cut_line(), update_bb(), and update_raycasters_for_picking().
perform_cut()
void Slic3r::GUI::GLGizmoCut3D::perform_cut (const Selection & selection) private
{
    if (!can_perform_cut())
        return;
    const int instance_idx = selection.get_instance_idx();
    const int object_idx = selection.get_object_idx();
    wxCHECK_RET(instance_idx >= 0 && object_idx >= 0, "GLGizmoCut: Invalid object selection");
    Plater* plater = wxGetApp().plater();
    ModelObject* mo = plater->model().objects[object_idx];
    if (!mo)
        return;
    // deactivate CutGizmo and than perform a cut
    m_parent.reset_all_gizmos();
    // perform cut
    {
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Cut by Plane"));
        // This shall delete the part selection class and deallocate the memory.
        ScopeGuard part_selection_killer([this]() { m_part_selection = PartSelection(); });
        const bool cut_by_contour = m_part_selection.valid();
        ModelObject* cut_mo = cut_by_contour ? m_part_selection.model_object() : nullptr;
        if (cut_mo)
            cut_mo->cut_connectors = mo->cut_connectors;
        else
            cut_mo = mo;
        int dowels_count = 0;
        const bool has_connectors = !mo->cut_connectors.empty();
        // update connectors pos as offset of its center before cut performing
        apply_connectors_in_model(cut_mo , dowels_count);
        wxBusyCursor wait;
        const Transform3d cut_matrix = get_cut_matrix(selection);
        ModelObjectCutAttributes attributes = only_if(has_connectors ? true : m_keep_upper, ModelObjectCutAttribute::KeepUpper) |
                                              only_if(has_connectors ? true : m_keep_lower, ModelObjectCutAttribute::KeepLower) |
                                              only_if(has_connectors ? false : m_keep_as_parts, ModelObjectCutAttribute::KeepAsParts) |
                                              only_if(m_place_on_cut_upper, ModelObjectCutAttribute::PlaceOnCutUpper) |
                                              only_if(m_place_on_cut_lower, ModelObjectCutAttribute::PlaceOnCutLower) |
                                              only_if(m_rotate_upper, ModelObjectCutAttribute::FlipUpper) |
                                              only_if(m_rotate_lower, ModelObjectCutAttribute::FlipLower) |
                                              only_if(dowels_count > 0, ModelObjectCutAttribute::CreateDowels) |
                                              only_if(!has_connectors && cut_mo->cut_id.id().invalid(), ModelObjectCutAttribute::InvalidateCutInfo);
        // update cut_id for the cut object in respect to the attributes
        update_object_cut_id(cut_mo->cut_id, attributes, dowels_count);
        ModelObjectPtrs cut_object_ptrs;
        if (cut_by_contour) {
            // Clone the object to duplicate instances, materials etc.
            ModelObject* upper{ nullptr };
            if (m_keep_upper) cut_mo->clone_for_cut(&upper);
            ModelObject* lower{ nullptr };
            if (m_keep_lower) cut_mo->clone_for_cut(&lower);
            auto add_cut_objects = [this, &instance_idx, &cut_matrix](ModelObjectPtrs& cut_objects, ModelObject* upper, ModelObject* lower) {
                if (upper && !upper->volumes.empty()) {
                    ModelObject::reset_instance_transformation(upper, instance_idx, cut_matrix, m_place_on_cut_upper, m_rotate_upper);
                    cut_objects.push_back(upper);
                }
                if (lower && !lower->volumes.empty()) {
                    ModelObject::reset_instance_transformation(lower, instance_idx, cut_matrix, m_place_on_cut_lower, m_place_on_cut_lower || m_rotate_lower);
                    cut_objects.push_back(lower);
                }
            };
            const size_t cut_parts_cnt = m_part_selection.parts().size();
            bool has_modifiers = false;
            // Distribute SolidParts to the Upper/Lower object
            for (size_t id = 0; id < cut_parts_cnt; ++id) {
                if (m_part_selection.parts()[id].is_modifier)
                    has_modifiers = true; // modifiers will be added later to the related parts
                else if (ModelObject* obj = (m_part_selection.parts()[id].selected ? upper : lower))
                    obj->add_volume(*(cut_mo->volumes[id]));
            }
            if (has_modifiers) {
                // Distribute Modifiers to the Upper/Lower object
                auto upper_bb = upper ? upper->instance_bounding_box(instance_idx) : BoundingBoxf3();
                auto lower_bb = lower ? lower->instance_bounding_box(instance_idx) : BoundingBoxf3();
                const Transform3d inst_matrix = cut_mo->instances[instance_idx]->get_transformation().get_matrix();
                for (size_t id = 0; id < cut_parts_cnt; ++id)
                    if (m_part_selection.parts()[id].is_modifier) {
                        ModelVolume* vol = cut_mo->volumes[id];
                        auto bb = vol->mesh().transformed_bounding_box(inst_matrix * vol->get_matrix());
                        // Don't add modifiers which are not intersecting with solid parts
                        if (upper_bb.intersects(bb))
                            upper->add_volume(*vol);
                        if (lower_bb.intersects(bb))
                            lower->add_volume(*vol);
                    }
            }
            ModelVolumePtrs& volumes = cut_mo->volumes;
            if (volumes.size() == cut_parts_cnt) {
                // Means that object is cut without connectors
                // Just add Upper and Lower objects to cut_object_ptrs
                add_cut_objects(cut_object_ptrs, upper, lower);
            }
            else if (volumes.size() > cut_parts_cnt) {
                // Means that object is cut with connectors
                // All volumes are distributed to Upper / Lower object,
                // So we dont need them anymore
                for (size_t id = 0; id < cut_parts_cnt; id++)
                    delete *(volumes.begin() + id);
                volumes.erase(volumes.begin(), volumes.begin() + cut_parts_cnt);
                // Perform cut just to get connectors
                const ModelObjectPtrs cut_connectors_obj = cut_mo->cut(instance_idx, get_cut_matrix(selection), attributes);
                assert(dowels_count > 0 ? cut_connectors_obj.size() >= 3 : cut_connectors_obj.size() == 2);
                // Connectors from upper object
                for (const ModelVolume* volume : cut_connectors_obj[0]->volumes)
                     upper->add_volume(*volume, volume->type());
                // Connectors from lower object
                for (const ModelVolume* volume : cut_connectors_obj[1]->volumes)
                     lower->add_volume(*volume, volume->type());
                // Add Upper and Lower objects to cut_object_ptrs
                add_cut_objects(cut_object_ptrs, upper, lower);
                // Add Dowel-connectors as separate objects to cut_object_ptrs
                if (cut_connectors_obj.size() >= 3)
                    for (size_t id = 2; id < cut_connectors_obj.size(); id++)
                        cut_object_ptrs.push_back(cut_connectors_obj[id]);
            }
            // Now merge all model parts together:
            {
                for (ModelObject* mo : cut_object_ptrs) {
                    TriangleMesh mesh;
                    // Merge all SolidPart but not Connectors
                    for (const ModelVolume* mv : mo->volumes) {
                        if (mv->is_model_part() && !mv->is_cut_connector()) {
                            TriangleMesh m = mv->mesh();
                            m.transform(mv->get_matrix());
                            mesh.merge(m);
                        }
                    }
                    if (! mesh.empty()) {
                        ModelVolume* new_volume = mo->add_volume(mesh);
                        new_volume->name = mo->name;
                        // Delete all merged SolidPart but not Connectors
                        for (int i=int(mo->volumes.size())-2; i>=0; --i) {
                            const ModelVolume* mv = mo->volumes[i];
                            if (mv->is_model_part() && !mv->is_cut_connector())
                                mo->delete_volume(i);
                        }
                    }
                }
            }
        }
        else
            cut_object_ptrs = cut_mo->cut(instance_idx, cut_matrix, attributes);
        // save cut_id to post update synchronization
        const CutObjectBase cut_id = cut_mo->cut_id;
        // update cut results on plater and in the model
        plater->cut(object_idx, cut_object_ptrs);
        synchronize_model_after_cut(plater->model(), cut_id);
    }
}
References _L, Slic3r::ModelObject::add_volume(), apply_connectors_in_model(), can_perform_cut(), Slic3r::ModelObject::clone_for_cut(), Slic3r::CreateDowels, Slic3r::ModelObject::cut(), Slic3r::GUI::Plater::cut(), Slic3r::ModelObject::cut_connectors, Slic3r::ModelObject::cut_id, Slic3r::ModelObject::delete_volume(), Slic3r::TriangleMesh::empty(), Slic3r::FlipLower, Slic3r::FlipUpper, get_cut_matrix(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::ModelVolume::get_matrix(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::ObjectBase::id(), Slic3r::ModelObject::instances, Slic3r::ObjectID::invalid(), Slic3r::InvalidateCutInfo, Slic3r::ModelVolume::is_cut_connector(), Slic3r::ModelVolume::is_model_part(), Slic3r::KeepAsParts, Slic3r::KeepLower, Slic3r::KeepUpper, m_keep_as_parts, m_keep_lower, m_keep_upper, Slic3r::GUI::GLGizmoBase::m_parent, m_part_selection, m_place_on_cut_lower, m_place_on_cut_upper, m_rotate_lower, m_rotate_upper, Slic3r::TriangleMesh::merge(), Slic3r::ModelVolume::mesh(), Slic3r::GUI::Plater::model(), Slic3r::GUI::GLGizmoCut3D::PartSelection::model_object(), Slic3r::ModelObject::name, Slic3r::ModelVolume::name, Slic3r::Model::objects, Slic3r::only_if(), Slic3r::GUI::GLGizmoCut3D::PartSelection::parts(), Slic3r::PlaceOnCutLower, Slic3r::PlaceOnCutUpper, Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::reset_all_gizmos(), Slic3r::ModelObject::reset_instance_transformation(), Slic3r::GUI::synchronize_model_after_cut(), Slic3r::TriangleMesh::transform(), Slic3r::TriangleMesh::transformed_bounding_box(), Slic3r::GUI::update_object_cut_id(), Slic3r::GUI::GLGizmoCut3D::PartSelection::valid(), and Slic3r::ModelObject::volumes.
Referenced by render_cut_plane_input_window().
process_contours()
void Slic3r::GUI::GLGizmoCut3D::process_contours () protected
{
    reset_cut_by_contours();
    const Selection& selection = m_parent.get_selection();
    const ModelObjectPtrs& model_objects = selection.get_model()->objects;
    wxBusyCursor wait;
    const int instance_idx = selection.get_instance_idx();
    const int object_idx = selection.get_object_idx();
    m_part_selection = PartSelection(model_objects[object_idx], get_cut_matrix(selection), instance_idx, m_plane_center, m_cut_normal, *m_c->object_clipper());
    m_parent.toggle_model_objects_visibility(false);
}
References get_cut_matrix(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::GLGizmoBase::m_c, m_cut_normal, Slic3r::GUI::GLGizmoBase::m_parent, m_part_selection, m_plane_center, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::Model::objects, reset_cut_by_contours(), and Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility().
Referenced by on_mouse().
process_cut_line()
bool Slic3r::GUI::GLGizmoCut3D::process_cut_line (SLAGizmoEventType action, const Vec2d & mouse_position) private
{
    const Camera& camera = wxGetApp().plater()->get_camera();
    Vec3d pt;
    Vec3d dir;
    MeshRaycaster::line_from_mouse_pos(mouse_position, Transform3d::Identity(), camera, pt, dir);
    dir.normalize();
    pt += dir; // Move the pt along dir so it is not clipped.
    if (action == SLAGizmoEventType::LeftDown && !cut_line_processing()) {
        m_line_beg = pt;
        m_line_end = pt;
        on_unregister_raycasters_for_picking();
        return true;
    }
    if (cut_line_processing()) {
        reset_cut_by_contours();
        m_line_end = pt;
        if (action == SLAGizmoEventType::LeftDown || action == SLAGizmoEventType::LeftUp) {
            Vec3d line_dir = m_line_end - m_line_beg;
            if (line_dir.norm() < 3.0)
                return true;
            Vec3d cross_dir = line_dir.cross(dir).normalized();
            Eigen::Quaterniond q;
            Transform3d m = Transform3d::Identity();
            m.matrix().block(0, 0, 3, 3) = q.setFromTwoVectors(Vec3d::UnitZ(), cross_dir).toRotationMatrix();
            const Vec3d new_plane_center = m_bb_center + cross_dir * cross_dir.dot(pt - m_bb_center);
            // update transformed bb
            const auto new_tbb = transformed_bounding_box(new_plane_center, m);
            const GLVolume* first_volume = m_parent.get_selection().get_first_volume();
            Vec3d instance_offset = first_volume->get_instance_offset();
            instance_offset[Z] += first_volume->get_sla_shift_z();
            const Vec3d trans_center_pos = m.inverse() * (new_plane_center - instance_offset) + new_tbb.center();
            if (new_tbb.contains(trans_center_pos)) {
                Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Cut by line"), UndoRedo::SnapshotType::GizmoAction);
                m_transformed_bounding_box = new_tbb;
                set_center(new_plane_center);
                m_start_dragging_m = m_rotation_m = m;
                m_ar_plane_center = m_plane_center;
            }
            m_angle_arc.reset();
            discard_cut_line_processing();
        }
        else if (action == SLAGizmoEventType::Moving)
            this->set_dirty();
        return true;
    }
    return false;
}
References _L, cut_line_processing(), discard_cut_line_processing(), Slic3r::GUI::Selection::get_first_volume(), Slic3r::GLVolume::get_instance_offset(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GLVolume::get_sla_shift_z(), Slic3r::UndoRedo::GizmoAction, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, Slic3r::GUI::MeshRaycaster::line_from_mouse_pos(), m_angle_arc, m_ar_plane_center, m_bb_center, m_line_beg, m_line_end, Slic3r::GUI::GLGizmoBase::m_parent, m_plane_center, m_rotation_m, m_start_dragging_m, m_transformed_bounding_box, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::Moving, on_unregister_raycasters_for_picking(), Slic3r::GUI::plater(), Slic3r::GUI::GLModel::reset(), reset_cut_by_contours(), set_center(), Slic3r::GUI::GLGizmoBase::set_dirty(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), transformed_bounding_box(), and Z.
Referenced by gizmo_event().
process_selection_rectangle()
void Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle (CutConnectors & connectors) protected
{
    GLSelectionRectangle::EState rectangle_status = m_selection_rectangle.get_state();
    ModelObject* mo          = m_c->selection_info()->model_object();
    int          active_inst = m_c->selection_info()->get_active_instance();
    // First collect positions of all the points in world coordinates.
    Transformation trafo = mo->instances[active_inst]->get_transformation();
    trafo.set_offset(trafo.get_offset() + double(m_c->selection_info()->get_sla_shift()) * Vec3d::UnitZ());
    std::vector<Vec3d> points;
    for (const CutConnector&connector : connectors)
        points.push_back(connector.pos + trafo.get_offset());
    // Now ask the rectangle which of the points are inside.
    std::vector<unsigned int> points_idxs = m_selection_rectangle.contains(points);
    m_selection_rectangle.stop_dragging();
    for (size_t idx : points_idxs)
        select_connector(int(idx), rectangle_status == GLSelectionRectangle::EState::Select);
}
References Slic3r::GUI::GLSelectionRectangle::contains(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::GUI::GLSelectionRectangle::get_state(), Slic3r::ModelObject::instances, Slic3r::GUI::GLGizmoBase::m_c, m_selection_rectangle, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::GLSelectionRectangle::Select, select_connector(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::Geometry::Transformation::set_offset(), and Slic3r::GUI::GLSelectionRectangle::stop_dragging().
Referenced by gizmo_event().
put_connectors_on_cut_plane()
void Slic3r::GUI::GLGizmoCut3D::put_connectors_on_cut_plane (const Vec3d & cp_normal, double cp_offset)
{
    ModelObject* mo = m_c->selection_info()->model_object();
    if (CutConnectors& connectors = mo->cut_connectors; !connectors.empty()) {
        const float sla_shift        = m_c->selection_info()->get_sla_shift();
        const Vec3d& instance_offset = mo->instances[m_c->selection_info()->get_active_instance()]->get_offset();
        for (auto& connector : connectors) {
            // convert connetor pos to the world coordinates
            Vec3d pos = connector.pos + instance_offset;
            pos[Z] += sla_shift;
            // scalar distance from point to plane along the normal
            double distance = -cp_normal.dot(pos) + cp_offset;
            // move connector
            connector.pos += distance * cp_normal;
        }
    }
}
References Slic3r::ModelObject::cut_connectors, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::ModelObject::instances, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Z.
Referenced by update_clipper().
register_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].register_raycasters_for_picking((m_group_id >= 0) ? m_group_id : i);
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking().
register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking () inline inherited
{ register_grabbers_for_picking(); on_register_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_register_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_register_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ on_render(); }
References Slic3r::GUI::GLGizmoBase::on_render().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_render().
render_build_size()
void Slic3r::GUI::GLGizmoCut3D::render_build_size () protected
{
    double              koef     = m_imperial_units ? ObjectManipulation::mm_to_in : 1.0;
    wxString            unit_str = " " + (m_imperial_units ? _L("in") : _L("mm"));
    Vec3d    tbb_sz = m_transformed_bounding_box.size();
    wxString size   =   "X: " + double_to_string(tbb_sz.x() * koef, 2) + unit_str +
                     ",  Y: " + double_to_string(tbb_sz.y() * koef, 2) + unit_str +
                     ",  Z: " + double_to_string(tbb_sz.z() * koef, 2) + unit_str;
    ImGui::AlignTextToFramePadding();
    m_imgui->text(_L("Build Volume"));
    ImGui::SameLine();
    m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, size);
}
References _L, ImGui::AlignTextToFramePadding(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, Slic3r::GUI::double_to_string(), Slic3r::GUI::GLGizmoBase::m_imgui, m_imperial_units, m_transformed_bounding_box, Slic3r::GUI::ObjectManipulation::mm_to_in, ImGui::SameLine(), Slic3r::BoundingBox3Base< PointType >::size(), Slic3r::GUI::ImGuiWrapper::text(), and Slic3r::GUI::ImGuiWrapper::text_colored().
Referenced by render_cut_plane_input_window().
render_clipper_cut()
void Slic3r::GUI::GLGizmoCut3D::render_clipper_cut () private
{
    if (! m_connectors_editing)
        ::glDisable(GL_DEPTH_TEST);
    GLboolean cull_face = GL_FALSE;
    ::glGetBooleanv(GL_CULL_FACE, &cull_face);
    ::glDisable(GL_CULL_FACE);
    m_c->object_clipper()->render_cut(m_part_selection.get_ignored_contours_ptr());
    if (cull_face)
        ::glEnable(GL_CULL_FACE);
    if (! m_connectors_editing)
        ::glEnable(GL_DEPTH_TEST);
}
References Slic3r::GUI::GLGizmoCut3D::PartSelection::get_ignored_contours_ptr(), GL_FALSE, Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, m_part_selection, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), and Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut().
Referenced by on_render().
render_color_marker()
void Slic3r::GUI::GLGizmoCut3D::render_color_marker (float size, const ImU32 & color) protected
{
    ImGui::SameLine();
    const float radius = 0.5f * size;
    ImVec2 pos = ImGui::GetCurrentWindow()->DC.CursorPos;
    pos.x += size;
    pos.y += 1.25f * radius;
    ImGui::GetCurrentWindow()->DrawList->AddNgonFilled(pos, radius, color, 6);
    ImGuiWrapper::text(" ");
}
References ImDrawList::AddNgonFilled(), ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, ImGui::GetCurrentWindow(), ImGui::SameLine(), and Slic3r::GUI::ImGuiWrapper::text().
Referenced by render_cut_plane_input_window().
render_combo()
bool Slic3r::GUI::GLGizmoCut3D::render_combo (const std::string & label, const std::vector< std::string > & lines, int & selection_idx) private
{
    ImGui::AlignTextToFramePadding();
    const bool is_changed = m_imgui->combo(label, lines, selection_idx, 0, m_label_width, m_control_width);
    if (is_changed)
        update_connector_shape();
    return is_changed;
}
References ImGui::AlignTextToFramePadding(), Slic3r::GUI::ImGuiWrapper::combo(), m_control_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_label_width, and update_connector_shape().
Referenced by render_connectors_input_window().
render_connect_mode_radio_button()
void Slic3r::GUI::GLGizmoCut3D::render_connect_mode_radio_button (CutConnectorMode mode) private
{
    ImGui::SameLine(mode == CutConnectorMode::Auto ? m_label_width : 2 * m_label_width);
    ImGui::PushItemWidth(m_control_width);
    if (ImGui::RadioButton(m_connector_modes[int(mode)].c_str(), m_connector_mode == mode))
        m_connector_mode = mode;
}
References Auto, m_connector_mode, m_connector_modes, m_control_width, m_label_width, ImGui::PushItemWidth(), ImGui::RadioButton(), and ImGui::SameLine().
render_connect_type_radio_button()
bool Slic3r::GUI::GLGizmoCut3D::render_connect_type_radio_button (CutConnectorType type) private
{
    ImGui::SameLine(type == CutConnectorType::Plug ? m_label_width : 0);
    ImGui::PushItemWidth(m_control_width);
    if (ImGui::RadioButton(m_connector_types[size_t(type)].c_str(), m_connector_type == type)) {
        m_connector_type = type;
        update_connector_shape();
        return true;
    }
    return false;
}
References m_connector_type, m_connector_types, m_control_width, m_label_width, Slic3r::Plug, ImGui::PushItemWidth(), ImGui::RadioButton(), ImGui::SameLine(), and update_connector_shape().
Referenced by render_connectors_input_window().
render_connectors()
void Slic3r::GUI::GLGizmoCut3D::render_connectors () private
{
    ::glEnable(GL_DEPTH_TEST);
    if (m_is_contour_changed || cut_line_processing() ||
        m_connector_mode == CutConnectorMode::Auto || !m_c->selection_info())
        return;
    const ModelObject* mo = m_c->selection_info()->model_object();
    auto inst_id = m_c->selection_info()->get_active_instance();
    if (inst_id < 0)
        return;
    const CutConnectors& connectors = mo->cut_connectors;
    if (connectors.size() != m_selected.size()) {
        // #ysFIXME
        clear_selection();
        m_selected.resize(connectors.size(), false);
    }
    ColorRGBA render_color = CONNECTOR_DEF_COLOR;
    const ModelInstance* mi = mo->instances[inst_id];
    const Vec3d& instance_offset = mi->get_offset();
    const double sla_shift       = double(m_c->selection_info()->get_sla_shift());
    const bool looking_forward = is_looking_forward();
    for (size_t i = 0; i < connectors.size(); ++i) {
        const CutConnector& connector = connectors[i];
        float height = connector.height;
        // recalculate connector position to world position
        Vec3d pos = connector.pos + instance_offset + sla_shift * Vec3d::UnitZ();
        // First decide about the color of the point.
        assert(std::is_sorted(m_invalid_connectors_idxs.begin(), m_invalid_connectors_idxs.end()));
        const bool conflict_connector = std::binary_search(m_invalid_connectors_idxs.begin(), m_invalid_connectors_idxs.end(), i);
        if (conflict_connector)
            render_color = CONNECTOR_ERR_COLOR;
        else // default connector color
            render_color = connector.attribs.type == CutConnectorType::Dowel ? DOWEL_COLOR          : PLAG_COLOR;
        if (!m_connectors_editing)
            render_color = CONNECTOR_ERR_COLOR;
        else if (size_t(m_hover_id - m_connectors_group_id) == i)
            render_color = conflict_connector ? HOVERED_ERR_COLOR :
                           connector.attribs.type == CutConnectorType::Dowel ? HOVERED_DOWEL_COLOR  : HOVERED_PLAG_COLOR;
        else if (m_selected[i])
            render_color = connector.attribs.type == CutConnectorType::Dowel ? SELECTED_DOWEL_COLOR : SELECTED_PLAG_COLOR;
        const Camera& camera = wxGetApp().plater()->get_camera();
        if (connector.attribs.type  == CutConnectorType::Dowel &&
            connector.attribs.style == CutConnectorStyle::Prism) {
            if (m_connectors_editing) {
                height = 0.05f;
                if (!looking_forward)
                    pos += 0.05 * m_clp_normal;
            }
            else {
                if (looking_forward)
                    pos -= static_cast<double>(height) * m_clp_normal;
                else
                    pos += static_cast<double>(height) * m_clp_normal;
                height *= 2;
            }
        }
        else if (!looking_forward)
            pos += 0.05 * m_clp_normal;
        const Transform3d view_model_matrix = camera.get_view_matrix() * translation_transform(pos) * m_rotation_m *
                                              scale_transform(Vec3f(connector.radius, connector.radius, height).cast<double>());
        render_model(m_shapes[connector.attribs].model, render_color, view_model_matrix);
    }
}
References Slic3r::CutConnector::attribs, Auto, clear_selection(), Slic3r::GUI::CONNECTOR_DEF_COLOR, Slic3r::GUI::CONNECTOR_ERR_COLOR, Slic3r::ModelObject::cut_connectors, cut_line_processing(), Slic3r::Dowel, Slic3r::GUI::DOWEL_COLOR, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::ModelInstance::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::CutConnector::height, Slic3r::GUI::HOVERED_DOWEL_COLOR, Slic3r::GUI::HOVERED_ERR_COLOR, Slic3r::GUI::HOVERED_PLAG_COLOR, Slic3r::ModelObject::instances, is_looking_forward(), Slic3r::GUI::GLGizmoBase::m_c, m_clp_normal, m_connector_mode, m_connectors_editing, m_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_hover_id, m_invalid_connectors_idxs, m_is_contour_changed, m_rotation_m, m_selected, m_shapes, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::PLAG_COLOR, Slic3r::CutConnector::pos, Slic3r::Prism, Slic3r::CutConnector::radius, render_model(), Slic3r::Geometry::scale_transform(), Slic3r::GUI::SELECTED_DOWEL_COLOR, Slic3r::GUI::SELECTED_PLAG_COLOR, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::CutConnectorAttributes::style, Slic3r::Geometry::translation_transform(), and Slic3r::CutConnectorAttributes::type.
Referenced by on_render().
render_connectors_input_window()
void Slic3r::GUI::GLGizmoCut3D::render_connectors_input_window (CutConnectors & connectors) protected
{
    // add shortcuts panel
    render_shortcuts();
    // Connectors section
    ImGui::Separator();
    // WIP : Auto : Need to implement
    // m_imgui->text(_L("Mode"));
    // render_connect_mode_radio_button(CutConnectorMode::Auto);
    // render_connect_mode_radio_button(CutConnectorMode::Manual);
    ImGui::AlignTextToFramePadding();
    m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, m_labels_map["Connectors"]);
    m_imgui->disabled_begin(connectors.empty());
    ImGui::SameLine(m_label_width);
    const wxString act_name = _L("Remove connectors");
    if (render_reset_button("connectors", into_u8(act_name))) {
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), act_name, UndoRedo::SnapshotType::GizmoAction);
        reset_connectors();
    }
    m_imgui->disabled_end();
    render_flip_plane_button(m_connectors_editing && connectors.empty());
    m_imgui->text(m_labels_map["Type"]);
    bool type_changed = render_connect_type_radio_button(CutConnectorType::Plug);
    type_changed     |= render_connect_type_radio_button(CutConnectorType::Dowel);
    if (type_changed)
        apply_selected_connectors([this, &connectors] (size_t idx) { connectors[idx].attribs.type = CutConnectorType(m_connector_type); });
    m_imgui->disabled_begin(m_connector_type == CutConnectorType::Dowel);
    if (type_changed && m_connector_type == CutConnectorType::Dowel) {
        m_connector_style = int(CutConnectorStyle::Prism);
        apply_selected_connectors([this, &connectors](size_t idx) { connectors[idx].attribs.style = CutConnectorStyle(m_connector_style); });
    }
    if (render_combo(m_labels_map["Style"], m_connector_styles, m_connector_style))
        apply_selected_connectors([this, &connectors](size_t idx) { connectors[idx].attribs.style = CutConnectorStyle(m_connector_style); });
    m_imgui->disabled_end();
    if (render_combo(m_labels_map["Shape"], m_connector_shapes, m_connector_shape_id))
        apply_selected_connectors([this, &connectors](size_t idx) { connectors[idx].attribs.shape = CutConnectorShape(m_connector_shape_id); });
    if (render_slider_double_input(m_labels_map["Depth"], m_connector_depth_ratio, m_connector_depth_ratio_tolerance))
        apply_selected_connectors([this, &connectors](size_t idx) {
            if (m_connector_depth_ratio > 0)
                connectors[idx].height           = m_connector_depth_ratio;
            if (m_connector_depth_ratio_tolerance >= 0)
                connectors[idx].height_tolerance = m_connector_depth_ratio_tolerance;
        });
    if (render_slider_double_input(m_labels_map["Size"], m_connector_size, m_connector_size_tolerance))
        apply_selected_connectors([this, &connectors](size_t idx) {
            if (m_connector_size > 0)
                connectors[idx].radius           = 0.5f * m_connector_size;
            if (m_connector_size_tolerance >= 0)
                connectors[idx].radius_tolerance = 0.5f * m_connector_size_tolerance;
        });
    ImGui::Separator();
    if (m_imgui->button(_L("Confirm connectors"))) {
        unselect_all_connectors();
        set_connectors_editing(false);
    }
    ImGui::SameLine(m_label_width + 1.15f * m_control_width);
    if (m_imgui->button(_L("Cancel"))) {
        reset_connectors();
        set_connectors_editing(false);
    }
}
References _L, ImGui::AlignTextToFramePadding(), apply_selected_connectors(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), Slic3r::Dowel, Slic3r::UndoRedo::GizmoAction, Slic3r::GUI::into_u8(), m_connector_depth_ratio, m_connector_depth_ratio_tolerance, m_connector_shape_id, m_connector_shapes, m_connector_size, m_connector_size_tolerance, m_connector_style, m_connector_styles, m_connector_type, m_connectors_editing, m_control_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_label_width, m_labels_map, Slic3r::GUI::plater(), Slic3r::Plug, Slic3r::Prism, render_combo(), render_connect_type_radio_button(), render_flip_plane_button(), render_reset_button(), render_shortcuts(), render_slider_double_input(), reset_connectors(), ImGui::SameLine(), ImGui::Separator(), set_connectors_editing(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), and unselect_all_connectors().
Referenced by on_render_input_window().
render_cut_line()
void Slic3r::GUI::GLGizmoCut3D::render_cut_line () private
{
    if (!cut_line_processing() || m_line_end.isApprox(Vec3d::Zero()))
        return;
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glClear(GL_DEPTH_BUFFER_BIT));
    m_cut_line.reset();
    m_cut_line.init_from(its_make_line((Vec3f)m_line_beg.cast<float>(), (Vec3f)m_line_end.cast<float>()));
    render_line(m_cut_line, GRABBER_COLOR, wxGetApp().plater()->get_camera().get_view_matrix(), 0.25f);
}
References cut_line_processing(), glsafe, Slic3r::GUI::GRABBER_COLOR, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::its_make_line(), m_cut_line, m_line_beg, m_line_end, Slic3r::GUI::plater(), render_line(), and Slic3r::GUI::GLModel::reset().
Referenced by on_render().
render_cut_plane()
void Slic3r::GUI::GLGizmoCut3D::render_cut_plane () private
{
    if (cut_line_processing())
        return;
    GLShaderProgram* shader = wxGetApp().get_shader("flat");
    if (shader == nullptr)
        return;
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glDisable(GL_CULL_FACE));
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
    shader->start_using();
    const Camera& camera = wxGetApp().plater()->get_camera();
    const Transform3d view_model_matrix = camera.get_view_matrix() * translation_transform(m_plane_center) * m_rotation_m;
    shader->set_uniform("view_model_matrix", view_model_matrix);
    shader->set_uniform("projection_matrix", camera.get_projection_matrix());
    if (can_perform_cut() && has_valid_contour()) {
        if (m_hover_id == CutPlane)
            m_plane.model.set_color({ 0.9f, 0.9f, 0.9f, 0.5f });
        else
            m_plane.model.set_color({ 0.8f, 0.8f, 0.8f, 0.5f });
    }
    else
        m_plane.model.set_color({ 1.0f, 0.8f, 0.8f, 0.5f });
    m_plane.model.render();
    glsafe(::glEnable(GL_CULL_FACE));
    glsafe(::glDisable(GL_BLEND));
    shader->stop_using();
}
References can_perform_cut(), cut_line_processing(), CutPlane, Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), glsafe, has_valid_contour(), Slic3r::GUI::GLGizmoBase::m_hover_id, m_plane, m_plane_center, m_rotation_m, Slic3r::GUI::PickingModel::model, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), and Slic3r::Geometry::translation_transform().
Referenced by on_render().
render_cut_plane_grabbers()
void Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers () private
{
    glsafe(::glClear(GL_DEPTH_BUFFER_BIT));
    ColorRGBA color = ColorRGBA::GRAY();
    const Transform3d view_matrix = wxGetApp().plater()->get_camera().get_view_matrix() * translation_transform(m_plane_center) * m_rotation_m;
    const double mean_size = get_grabber_mean_size(m_bounding_box);
    double size;
    const bool dragging_by_cut_plane = m_dragging && m_hover_id == CutPlane;
    if (!dragging_by_cut_plane) {
        render_grabber_connection(GRABBER_COLOR, view_matrix);
        // render sphere grabber
        size = m_dragging ? get_dragging_half_size(mean_size) : get_half_size(mean_size);
        color = m_hover_id == Y ? complementary(ColorRGBA::GREEN()) :
                m_hover_id == X ? complementary(ColorRGBA::RED())   :
                m_hover_id == Z ? GRABBER_COLOR                     :   ColorRGBA::GRAY();
        render_model(m_sphere.model, color, view_matrix * translation_transform(m_grabber_connection_len * Vec3d::UnitZ()) * scale_transform(size));
    }
    const bool no_one_grabber_hovered = !m_dragging && (m_hover_id < 0 || m_hover_id == CutPlane);
    // render X grabber
    if (no_one_grabber_hovered || m_hover_id == X)
    {
        size = m_dragging && m_hover_id == X ? get_dragging_half_size(mean_size) : get_half_size(mean_size);
        const Vec3d cone_scale = Vec3d(0.75 * size, 0.75 * size, 1.8 * size);
        color = m_hover_id == X ? complementary(ColorRGBA::RED()) : ColorRGBA::RED();
        if (m_hover_id == X) {
            render_grabber_connection(color, view_matrix);
            render_rotation_snapping(X, color);
        }
        Vec3d offset = Vec3d(0.0, 1.25 * size, m_grabber_connection_len);
        render_model(m_cone.model, color, view_matrix * translation_transform(offset) * rotation_transform(-0.5 * PI * Vec3d::UnitX()) * scale_transform(cone_scale));
        offset = Vec3d(0.0, -1.25 * size, m_grabber_connection_len);
        render_model(m_cone.model, color, view_matrix * translation_transform(offset) * rotation_transform(0.5 * PI * Vec3d::UnitX()) * scale_transform(cone_scale));
    }
    // render Y grabber
    if (no_one_grabber_hovered || m_hover_id == Y)
    {
        size = m_dragging && m_hover_id == Y ? get_dragging_half_size(mean_size) : get_half_size(mean_size);
        const Vec3d cone_scale = Vec3d(0.75 * size, 0.75 * size, 1.8 * size);
        color = m_hover_id == Y ? complementary(ColorRGBA::GREEN()) : ColorRGBA::GREEN();
        if (m_hover_id == Y) {
            render_grabber_connection(color, view_matrix);
            render_rotation_snapping(Y, color);
        }
        Vec3d offset = Vec3d(1.25 * size, 0.0, m_grabber_connection_len);
        render_model(m_cone.model, color, view_matrix * translation_transform(offset) * rotation_transform(0.5 * PI * Vec3d::UnitY()) * scale_transform(cone_scale));
        offset = Vec3d(-1.25 * size, 0.0, m_grabber_connection_len);
        render_model(m_cone.model, color, view_matrix * translation_transform(offset)* rotation_transform(-0.5 * PI * Vec3d::UnitY()) * scale_transform(cone_scale));
    }
}
References Slic3r::complementary(), CutPlane, Slic3r::GUI::get_dragging_half_size(), Slic3r::GUI::get_grabber_mean_size(), Slic3r::GUI::get_half_size(), glsafe, Slic3r::GUI::GRABBER_COLOR, Slic3r::ColorRGBA::GRAY(), Slic3r::ColorRGBA::GREEN(), m_bounding_box, m_cone, Slic3r::GUI::GLGizmoBase::m_dragging, m_grabber_connection_len, Slic3r::GUI::GLGizmoBase::m_hover_id, m_plane_center, m_rotation_m, m_sphere, Slic3r::GUI::PickingModel::model, Slic3r::offset(), PI, Slic3r::ColorRGBA::RED(), render_grabber_connection(), render_model(), render_rotation_snapping(), Slic3r::Geometry::rotation_transform(), Slic3r::Geometry::scale_transform(), Slic3r::Geometry::translation_transform(), X, Y, and Z.
Referenced by on_render().
render_cut_plane_input_window()
void Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window (CutConnectors & connectors) protected
{
    // WIP : cut plane mode
    // render_combo(_u8L("Mode"), m_modes, m_mode);
    if (m_mode == size_t(CutMode::cutPlanar)) {
        ImGui::AlignTextToFramePadding();
        ImGuiWrapper::text(wxString(ImGui::InfoMarkerSmall));
        ImGui::SameLine();
        ImGuiWrapper::text_colored(ImGuiWrapper::COL_ORANGE_LIGHT,
                              get_wraped_wxString(_L("Hold SHIFT key to draw a cut line"), 40));
        ImGui::Separator();
        render_build_size();
        ImGui::AlignTextToFramePadding();
        ImGuiWrapper::text(_L("Cut position") + ": ");
        ImGui::SameLine();
        render_move_center_input(Z);
        ImGui::SameLine();
        const bool has_connectors = !connectors.empty();
        const bool is_cut_plane_init = m_rotation_m.isApprox(Transform3d::Identity()) && m_bb_center.isApprox(m_plane_center);
        m_imgui->disabled_begin(is_cut_plane_init);
            wxString act_name = _L("Reset cutting plane");
            if (render_reset_button("cut_plane", into_u8(act_name))) {
                Plater::TakeSnapshot snapshot(wxGetApp().plater(), act_name, UndoRedo::SnapshotType::GizmoAction);
                reset_cut_plane();
            }
        m_imgui->disabled_end();
//        render_flip_plane_button();
        add_vertical_scaled_interval(0.75f);
        m_imgui->disabled_begin(!m_keep_upper || !m_keep_lower || m_keep_as_parts || (m_part_selection.valid() && m_part_selection.is_one_object()));
            if (m_imgui->button(has_connectors ? _L("Edit connectors") : _L("Add connectors")))
                set_connectors_editing(true);
        m_imgui->disabled_end();
        ImGui::SameLine(1.5f * m_control_width);
        m_imgui->disabled_begin(is_cut_plane_init && !has_connectors);
            act_name = _L("Reset cut");
            if (m_imgui->button(act_name, _L("Reset cutting plane and remove connectors"))) {
                Plater::TakeSnapshot snapshot(wxGetApp().plater(), act_name, UndoRedo::SnapshotType::GizmoAction);
                reset_cut_plane();
                reset_connectors();
            }
        m_imgui->disabled_end();
        ImGui::Separator();
        // render "After Cut" section
        ImVec2 label_size;
        for (const auto& item : m_part_orientation_names) {
            const ImVec2 text_size = ImGuiWrapper::calc_text_size(item.second);
            if (label_size.x < text_size.x)
                label_size.x = text_size.x;
            if (label_size.y < text_size.y)
                label_size.y = text_size.y;
        }
        const float h_shift     = label_size.x + m_imgui->scaled(3.f);
        const float marker_size = label_size.y;
        auto render_part_name = [this, marker_size, has_connectors](const wxString& name, bool& keep_part, const ImU32& color) {
            bool keep = true;
            add_horizontal_shift(m_imgui->scaled(1.2f));
            m_imgui->checkbox((m_keep_as_parts ? _L("Part") : _L("Object")) + " " + name, has_connectors ? keep : keep_part);
            render_color_marker(marker_size, color);
        };
        auto render_part_actions = [this, h_shift] (const wxString& suffix, const bool& keep_part, bool& place_on_cut_part, bool& rotate_part)
        {
            float shift = m_imgui->scaled(1.2f);
            if (suffix == "##lower")
                shift += h_shift;
            m_imgui->disabled_begin(!keep_part || m_keep_as_parts);
                add_horizontal_shift(shift);
                if (m_imgui->radio_button(m_part_orientation_names.at("none") + suffix, !place_on_cut_part && !rotate_part)) {
                    rotate_part = false;
                    place_on_cut_part = false;
                }
                add_horizontal_shift(shift);
                if (m_imgui->radio_button(m_part_orientation_names.at("on_cut") + suffix, place_on_cut_part)) {
                    place_on_cut_part = !place_on_cut_part;
                    rotate_part = false;
                }
                add_horizontal_shift(shift);
                if (m_imgui->radio_button(m_part_orientation_names.at("flip") + suffix, rotate_part)) {
                    rotate_part = !rotate_part;
                    place_on_cut_part = false;
                }
            m_imgui->disabled_end();
        };
        ImGuiWrapper::text(_L("Cut result") + ": ");
        add_vertical_scaled_interval(0.5f);
        m_imgui->disabled_begin(has_connectors || m_keep_as_parts);
            render_part_name("A", m_keep_upper, m_imgui->to_ImU32(UPPER_PART_COLOR));
            ImGui::SameLine(h_shift + ImGui::GetCurrentWindow()->WindowPadding.x);
            render_part_name("B", m_keep_lower, m_imgui->to_ImU32(LOWER_PART_COLOR));
        m_imgui->disabled_end();
        add_vertical_scaled_interval(0.5f);
        const ImVec2 pos = ImGui::GetCurrentWindow()->DC.CursorPos;
        render_part_actions("##upper", m_keep_upper, m_place_on_cut_upper, m_rotate_upper);
        ImGui::GetCurrentWindow()->DC.CursorPos = pos;
        render_part_actions("##lower", m_keep_lower, m_place_on_cut_lower, m_rotate_lower);
        add_vertical_scaled_interval(0.75f);
        m_imgui->disabled_begin(has_connectors || m_part_selection.valid());
            ImGuiWrapper::text(_L("Cut into") + ":");
            if (m_part_selection.valid())
                m_keep_as_parts = false;
            add_horizontal_scaled_interval(1.2f);
            // TRN CutGizmo: RadioButton Cut into ...
            if (m_imgui->radio_button(_L("Objects"), !m_keep_as_parts))
                m_keep_as_parts = false;
            ImGui::SameLine();
            // TRN CutGizmo: RadioButton Cut into ...
            if (m_imgui->radio_button(_L("Parts"), m_keep_as_parts))
                m_keep_as_parts = true;
            if (m_keep_as_parts) {
                m_keep_upper = m_keep_lower = true;
                m_place_on_cut_upper = m_place_on_cut_lower = false;
                m_rotate_upper = m_rotate_lower = false;
            }
        m_imgui->disabled_end();
    }
    ImGui::Separator();
    m_imgui->disabled_begin(!m_is_contour_changed && !can_perform_cut());
        if(m_imgui->button(_L("Perform cut")))
            perform_cut(m_parent.get_selection());
    m_imgui->disabled_end();
}
References _L, add_horizontal_scaled_interval(), add_horizontal_shift(), add_vertical_scaled_interval(), ImGui::AlignTextToFramePadding(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), can_perform_cut(), Slic3r::GUI::ImGuiWrapper::checkbox(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, ImGuiWindowTempData::CursorPos, cutPlanar, ImGuiWindow::DC, Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::get_wraped_wxString(), ImGui::GetCurrentWindow(), Slic3r::UndoRedo::GizmoAction, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), ImGui::InfoMarkerSmall, Slic3r::GUI::into_u8(), Slic3r::GUI::GLGizmoCut3D::PartSelection::is_one_object(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::isApprox(), Slic3r::GUI::LOWER_PART_COLOR, m_bb_center, m_control_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_is_contour_changed, m_keep_as_parts, m_keep_lower, m_keep_upper, m_mode, Slic3r::GUI::GLGizmoBase::m_parent, m_part_orientation_names, m_part_selection, m_place_on_cut_lower, m_place_on_cut_upper, m_plane_center, m_rotate_lower, m_rotate_upper, m_rotation_m, perform_cut(), Slic3r::GUI::plater(), Slic3r::GUI::ImGuiWrapper::radio_button(), render_build_size(), render_color_marker(), render_move_center_input(), render_reset_button(), reset_connectors(), reset_cut_plane(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::scaled(), ImGui::Separator(), set_connectors_editing(), Slic3r::GUI::suffix(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), Slic3r::GUI::ImGuiWrapper::to_ImU32(), Slic3r::GUI::UPPER_PART_COLOR, Slic3r::GUI::GLGizmoCut3D::PartSelection::valid(), ImVec2::x, ImVec2::y, and Z.
Referenced by on_render_input_window().
render_debug_input_window()
void Slic3r::GUI::GLGizmoCut3D::render_debug_input_window (float x) protected
{
    return;
    m_imgui->begin(wxString("DEBUG"));
    ImVec2 pos = ImGui::GetWindowPos();
    pos.x = x;
    ImGui::SetWindowPos(pos, ImGuiCond_Always);
/*
    static bool  hide_clipped  = false;
    static bool  fill_cut      = false;
    static float contour_width = 0.4f;
    m_imgui->checkbox(_L("Hide cut plane and grabbers"), m_hide_cut_plane);
    if (m_imgui->checkbox("hide_clipped", hide_clipped) && !hide_clipped)
        m_clp_normal = m_c->object_clipper()->get_clipping_plane()->get_normal();
    m_imgui->checkbox("fill_cut", fill_cut);
    m_imgui->slider_float("contour_width", &contour_width, 0.f, 3.f);
    if (auto oc = m_c->object_clipper())
        oc->set_behavior(hide_clipped || m_connectors_editing, fill_cut || m_connectors_editing, double(contour_width));
*/
    ImGui::PushItemWidth(0.5f * m_label_width);
    if (auto oc = m_c->object_clipper(); oc && m_imgui->slider_float("contour_width", &m_contour_width, 0.f, 3.f))
        oc->set_behavior(m_connectors_editing, m_connectors_editing, double(m_contour_width));
    ImGui::Separator();
    if (m_imgui->checkbox(("Render cut plane as disc"), m_cut_plane_as_circle))
        m_plane.reset();
    ImGui::PushItemWidth(0.5f * m_label_width);
    if (m_imgui->slider_float("cut_plane_radius_koef", &m_cut_plane_radius_koef, 1.f, 2.f))
        m_plane.reset();
    m_imgui->end();
}
References Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::checkbox(), Slic3r::GUI::ImGuiWrapper::end(), ImGui::GetWindowPos(), ImGuiCond_Always, Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, m_contour_width, m_cut_plane_as_circle, m_cut_plane_radius_koef, Slic3r::GUI::GLGizmoBase::m_imgui, m_label_width, m_plane, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), ImGui::PushItemWidth(), Slic3r::GUI::PickingModel::reset(), ImGui::Separator(), ImGui::SetWindowPos(), and Slic3r::GUI::ImGuiWrapper::slider_float().
Referenced by on_render_input_window().
render_double_input()
bool Slic3r::GUI::GLGizmoCut3D::render_double_input (const std::string & label, double & value_in) private
{
    ImGui::AlignTextToFramePadding();
    m_imgui->text(label);
    ImGui::SameLine(m_label_width);
    ImGui::PushItemWidth(m_control_width);
    double value = value_in;
    if (m_imperial_units)
        value *= ObjectManipulation::mm_to_in;
    double old_val = value;
    ImGui::InputDouble(("##" + label).c_str(), &value, 0.0f, 0.0f, "%.2f", ImGuiInputTextFlags_CharsDecimal);
    ImGui::SameLine();
    m_imgui->text(m_imperial_units ? _L("in") : _L("mm"));
    value_in = value * (m_imperial_units ? ObjectManipulation::in_to_mm : 1.0);
    return !is_approx(old_val, value);
}
References _L, ImGui::AlignTextToFramePadding(), ImGuiInputTextFlags_CharsDecimal, Slic3r::GUI::ObjectManipulation::in_to_mm, ImGui::InputDouble(), Slic3r::is_approx(), m_control_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_imperial_units, m_label_width, Slic3r::GUI::ObjectManipulation::mm_to_in, ImGui::PushItemWidth(), ImGui::SameLine(), and Slic3r::GUI::ImGuiWrapper::text().
render_flip_plane_button()
void Slic3r::GUI::GLGizmoCut3D::render_flip_plane_button (bool disable_pred = false) protected
{
    ImGui::SameLine();
    if (m_hover_id == CutPlane)
        ImGui::PushStyleColor(ImGuiCol_Button, ImGui::GetColorU32(ImGuiCol_ButtonHovered));
    m_imgui->disabled_begin(disable_pred);
        if (m_imgui->button(_L("Flip cut plane")))
            flip_cut_plane();
    m_imgui->disabled_end();
    if (m_hover_id == CutPlane)
        ImGui::PopStyleColor();
}
References _L, Slic3r::GUI::ImGuiWrapper::button(), CutPlane, Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), flip_cut_plane(), ImGui::GetColorU32(), ImGuiCol_Button, ImGuiCol_ButtonHovered, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::GLGizmoBase::m_imgui, ImGui::PopStyleColor(), ImGui::PushStyleColor(), and ImGui::SameLine().
Referenced by render_connectors_input_window().
render_grabber_connection()
void Slic3r::GUI::GLGizmoCut3D::render_grabber_connection (const ColorRGBA & color, Transform3d view_matrix) private
{
    const Transform3d line_view_matrix = view_matrix * scale_transform(Vec3d(1.0, 1.0, m_grabber_connection_len));
    render_line(m_grabber_connection, color, line_view_matrix, 0.2f);
};
References m_grabber_connection, m_grabber_connection_len, render_line(), and Slic3r::Geometry::scale_transform().
Referenced by render_cut_plane_grabbers().
render_grabbers() [1/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
}
References Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointType >::size().
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    render_grabbers(0, m_grabbers.size() - 1, size, false);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [3/3]
void Slic3r::GUI::GLGizmoBase::render_grabbers (size_t first, size_t last, float size, bool force_hover) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    glsafe(::glDisable(GL_CULL_FACE));
    for (size_t i = first; i <= last; ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(force_hover ? true : m_hover_id == (int)i, size);
    }
    glsafe(::glEnable(GL_CULL_FACE));
    shader->stop_using();
}
References glsafe, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // imgui windows that don't have an initial size needs to be processed once to get one
        // and are not rendered in the first frame
        // so, we forces to render another frame the first time the imgui window is shown
        // https://github.com/ocornut/imgui/issues/2949
        m_parent.set_as_dirty();
        m_parent.request_extra_frame();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), Slic3r::GUI::GLCanvas3D::request_extra_frame(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
render_input_window_warning()
void Slic3r::GUI::GLGizmoCut3D::render_input_window_warning () const protected
{
    if (m_is_contour_changed)
        return;
    if (! m_invalid_connectors_idxs.empty()) {
        wxString out = wxString(ImGui::WarningMarkerSmall) + _L("Invalid connectors detected") + ":";
        if (m_info_stats.outside_cut_contour > size_t(0))
            out += "\n - " + format_wxstr(_L_PLURAL("%1$d connector is out of cut contour", "%1$d connectors are out of cut contour", m_info_stats.outside_cut_contour),
                                          m_info_stats.outside_cut_contour);
        if (m_info_stats.outside_bb > size_t(0))
            out += "\n - " + format_wxstr(_L_PLURAL("%1$d connector is out of object", "%1$d connectors are out of object", m_info_stats.outside_bb),
                                           m_info_stats.outside_bb);
        if (m_info_stats.is_overlap)
            out += "\n - " + _L("Some connectors are overlapped");
        m_imgui->text(out);
    }
    if (!m_keep_upper && !m_keep_lower)
        m_imgui->text(wxString(ImGui::WarningMarkerSmall) + _L("Select at least one object to keep after cutting."));
    if (!has_valid_contour())
        m_imgui->text(wxString(ImGui::WarningMarkerSmall) + _L("Cut plane is placed out of object"));
}
References _L, _L_PLURAL, Slic3r::GUI::format_wxstr(), has_valid_contour(), Slic3r::GUI::GLGizmoCut3D::InvalidConnectorsStatistics::is_overlap, Slic3r::GUI::GLGizmoBase::m_imgui, m_info_stats, m_invalid_connectors_idxs, m_is_contour_changed, m_keep_lower, m_keep_upper, Slic3r::GUI::GLGizmoCut3D::InvalidConnectorsStatistics::outside_bb, Slic3r::GUI::GLGizmoCut3D::InvalidConnectorsStatistics::outside_cut_contour, Slic3r::GUI::ImGuiWrapper::text(), and ImGui::WarningMarkerSmall.
Referenced by on_render_input_window().
render_line()
void Slic3r::GUI::GLGizmoCut3D::render_line (GLModel & line_model, const ColorRGBA & color, Transform3d view_model_matrix, float width) private
{
    GLShaderProgram* shader = OpenGLManager::get_gl_info().is_core_profile() ? wxGetApp().get_shader("dashed_thick_lines") : wxGetApp().get_shader("flat");
    if (shader) {
        shader->start_using();
        shader->set_uniform("view_model_matrix", view_model_matrix);
        shader->set_uniform("projection_matrix", wxGetApp().plater()->get_camera().get_projection_matrix());
        shader->set_uniform("width", width);
        line_model.set_color(color);
        line_model.render();
        shader->stop_using();
    }
}
References Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::is_core_profile(), Slic3r::GUI::plater(), Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by render_cut_line(), and render_grabber_connection().
render_model()
void Slic3r::GUI::GLGizmoCut3D::render_model (GLModel & model, const ColorRGBA & color, Transform3d view_model_matrix) static private
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader) {
        shader->start_using();
        shader->set_uniform("view_model_matrix", view_model_matrix);
        shader->set_uniform("projection_matrix", wxGetApp().plater()->get_camera().get_projection_matrix());
        model.set_color(color);
        model.render();
        shader->stop_using();
    }
}
References Slic3r::GUI::plater(), Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by render_connectors(), and render_cut_plane_grabbers().
render_move_center_input()
void Slic3r::GUI::GLGizmoCut3D::render_move_center_input (int axis) private
{
    m_imgui->text(m_axis_names[axis]+":");
    ImGui::SameLine();
    ImGui::PushItemWidth(0.3f*m_control_width);
    Vec3d move = m_plane_center;
    double in_val, value = in_val = move[axis];
    if (m_imperial_units)
        value *= ObjectManipulation::mm_to_in;
    ImGui::InputDouble(("##move_" + m_axis_names[axis]).c_str(), &value, 0.0, 0.0, "%.2f", ImGuiInputTextFlags_CharsDecimal);
    ImGui::SameLine();
    double val = value * (m_imperial_units ? ObjectManipulation::in_to_mm : 1.0);
    if (in_val != val) {
        move[axis] = val;
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Move cut plane"), UndoRedo::SnapshotType::GizmoAction);
        set_center(move, true);
        m_ar_plane_center = m_plane_center;
        reset_cut_by_contours();
    }
}
References _L, Slic3r::UndoRedo::GizmoAction, ImGuiInputTextFlags_CharsDecimal, Slic3r::GUI::ObjectManipulation::in_to_mm, ImGui::InputDouble(), m_ar_plane_center, m_axis_names, m_control_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_imperial_units, m_plane_center, Slic3r::GUI::ObjectManipulation::mm_to_in, Slic3r::GUI::plater(), ImGui::PushItemWidth(), reset_cut_by_contours(), ImGui::SameLine(), set_center(), and Slic3r::GUI::ImGuiWrapper::text().
Referenced by render_cut_plane_input_window().
render_reset_button()
bool Slic3r::GUI::GLGizmoCut3D::render_reset_button (const std::string & label_id, const std::string & tooltip) const private
{
    const ImGuiStyle& style = ImGui::GetStyle();
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, { 1, style.ItemSpacing.y });
    ImGui::PushStyleColor(ImGuiCol_Button, { 0.25f, 0.25f, 0.25f, 0.0f });
    ImGui::PushStyleColor(ImGuiCol_ButtonHovered, { 0.4f, 0.4f, 0.4f, 1.0f });
    ImGui::PushStyleColor(ImGuiCol_ButtonActive, { 0.4f, 0.4f, 0.4f, 1.0f });
    std::string btn_label;
    btn_label += ImGui::RevertButton;
    const bool revert = ImGui::Button((btn_label +"##" + label_id).c_str());
    ImGui::PopStyleColor(3);
    if (ImGui::IsItemHovered())
        m_imgui->tooltip(tooltip.c_str(), ImGui::GetFontSize() * 20.0f);
    ImGui::PopStyleVar();
    return revert;
}
References ImGui::Button(), ImGui::GetFontSize(), ImGui::GetStyle(), ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiStyleVar_ItemSpacing, ImGui::IsItemHovered(), Slic3r::GUI::GLGizmoBase::m_imgui, ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::RevertButton, style, and Slic3r::GUI::ImGuiWrapper::tooltip().
Referenced by render_connectors_input_window(), and render_cut_plane_input_window().
render_rotation_snapping()
void Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping (GrabberID axis, const ColorRGBA & color) private
{
    GLShaderProgram* line_shader = OpenGLManager::get_gl_info().is_core_profile() ? wxGetApp().get_shader("dashed_thick_lines") : wxGetApp().get_shader("flat");
    if (!line_shader)
        return;
    const Camera& camera = wxGetApp().plater()->get_camera();
    Transform3d view_model_matrix = camera.get_view_matrix() * translation_transform(m_plane_center) * m_start_dragging_m;
    if (axis == X)
        view_model_matrix = view_model_matrix * rotation_transform(0.5 * PI * Vec3d::UnitY()) * rotation_transform(-PI * Vec3d::UnitZ());
    else
        view_model_matrix = view_model_matrix * rotation_transform(-0.5 * PI * Vec3d::UnitZ()) * rotation_transform(-0.5 * PI * Vec3d::UnitY());
    line_shader->start_using();
    line_shader->set_uniform("projection_matrix", camera.get_projection_matrix());
    line_shader->set_uniform("view_model_matrix", view_model_matrix);
    line_shader->set_uniform("width", 0.25f);
    m_circle.render();
    m_scale.render();
    m_snap_radii.render();
    m_reference_radius.render();
    if (m_dragging) {
        line_shader->set_uniform("width", 1.5f);
        m_angle_arc.set_color(color);
        m_angle_arc.render();
    }
    line_shader->stop_using();
}
References Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::OpenGLManager::GLInfo::is_core_profile(), m_angle_arc, m_circle, Slic3r::GUI::GLGizmoBase::m_dragging, m_plane_center, m_reference_radius, m_scale, m_snap_radii, m_start_dragging_m, PI, Slic3r::GUI::GLModel::render(), Slic3r::Geometry::rotation_transform(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::Geometry::translation_transform(), and X.
Referenced by render_cut_plane_grabbers().
render_shortcuts()
void Slic3r::GUI::GLGizmoCut3D::render_shortcuts () protected
{
    if (m_imgui->button("? " + (m_show_shortcuts ? wxString(ImGui::CollapseBtn) : wxString(ImGui::ExpandBtn))))
        m_show_shortcuts = !m_show_shortcuts;
    if (m_shortcut_label_width < 0.f) {
        for (const auto& shortcut : m_shortcuts) {
            const float width = m_imgui->calc_text_size(shortcut.first).x;
            if (m_shortcut_label_width < width)
                m_shortcut_label_width = width;
        }
        m_shortcut_label_width += +m_imgui->scaled(1.f);
    }
    if (m_show_shortcuts)
        for (const auto&shortcut : m_shortcuts ){
            m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, shortcut.first);
            ImGui::SameLine(m_shortcut_label_width);
            m_imgui->text(shortcut.second);
        }
}
References Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, ImGui::CollapseBtn, ImGui::ExpandBtn, Slic3r::GUI::GLGizmoBase::m_imgui, m_shortcut_label_width, m_shortcuts, m_show_shortcuts, ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::scaled(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), and ImVec2::x.
Referenced by render_connectors_input_window().
render_slider_double_input()
bool Slic3r::GUI::GLGizmoCut3D::render_slider_double_input (const std::string & label, float & value_in, float & tolerance_in) private
{
    constexpr float UndefMinVal = -0.1f;
    const float f_mm_to_in = static_cast<float>(ObjectManipulation::mm_to_in);
    auto render_slider = [this, UndefMinVal, f_mm_to_in]
                         (const std::string& label, float& val, float def_val, float max_val, const wxString& tooltip) {
        float min_val = val < 0.f ? UndefMinVal : def_val;
        float value = val;
        if (m_imperial_units) {
            min_val *= f_mm_to_in;
            value   *= f_mm_to_in;
        }
        const float old_val = value;
        const std::string format = val < 0.f ? UndefLabel : (m_imperial_units ? "%.4f  " + _u8L("in") : "%.2f  " + _u8L("mm"));
        m_imgui->slider_float(label.c_str(), &value, min_val, max_val, format.c_str(), 1.f, true, tooltip);
        val = value * (m_imperial_units ? static_cast<float>(ObjectManipulation::in_to_mm) : 1.f);
        return !is_approx(old_val, value);
    };
    const BoundingBoxf3 bbox = m_bounding_box;
    const float mean_size = float((bbox.size().x() + bbox.size().y() + bbox.size().z()) / 9.0) * (m_imperial_units ? f_mm_to_in : 1.f);
    ImGuiWrapper::text(label);
    ImGui::SameLine(m_label_width);
    ImGui::PushItemWidth(m_control_width * 0.7f);
    const bool is_value_changed = render_slider("##" + label, value_in, 1.f, mean_size, _L("Value"));
    ImGui::SameLine();
    ImGui::PushItemWidth(m_control_width * 0.45f);
    const bool is_tolerance_changed = render_slider("##tolerance_" + label, tolerance_in, 0.f, 0.5f * mean_size, _L("Tolerance"));
    return is_value_changed || is_tolerance_changed;
}
References _L, _u8L, Slic3r::GUI::GLGizmoBase::format(), Slic3r::GUI::ObjectManipulation::in_to_mm, Slic3r::is_approx(), m_bounding_box, m_control_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_imperial_units, m_label_width, Slic3r::GUI::ObjectManipulation::mm_to_in, ImGui::PushItemWidth(), ImGui::SameLine(), Slic3r::BoundingBox3Base< PointType >::size(), Slic3r::GUI::ImGuiWrapper::slider_float(), Slic3r::GUI::ImGuiWrapper::text(), and Slic3r::GUI::UndefLabel.
Referenced by render_connectors_input_window().
reset_connectors()
void Slic3r::GUI::GLGizmoCut3D::reset_connectors () private
{
    m_c->selection_info()->model_object()->cut_connectors.clear();
    update_raycasters_for_picking();
    clear_selection();
    check_and_update_connectors_state();
}
References check_and_update_connectors_state(), clear_selection(), Slic3r::ModelObject::cut_connectors, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and update_raycasters_for_picking().
Referenced by render_connectors_input_window(), and render_cut_plane_input_window().
reset_cut_by_contours()
void Slic3r::GUI::GLGizmoCut3D::reset_cut_by_contours () protected
{
    m_part_selection = PartSelection();
    const Selection& selection = m_parent.get_selection();
    const ModelObjectPtrs& model_objects = selection.get_model()->objects;
    m_parent.toggle_model_objects_visibility(true, model_objects[selection.get_object_idx()], selection.get_instance_idx());
}
References Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::GLGizmoBase::m_parent, m_part_selection, Slic3r::Model::objects, and Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility().
Referenced by dragging_grabber_xy(), dragging_grabber_z(), on_set_state(), process_contours(), process_cut_line(), render_move_center_input(), reset_cut_plane(), and update_bb().
reset_cut_plane()
void Slic3r::GUI::GLGizmoCut3D::reset_cut_plane () protected
{
    m_angle_arc.reset();
    m_transformed_bounding_box = transformed_bounding_box(m_bb_center);
    set_center(m_bb_center);
    m_start_dragging_m = m_rotation_m = Transform3d::Identity();
    m_ar_plane_center  = m_plane_center;
    reset_cut_by_contours();
    m_parent.request_extra_frame();
}
References Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), m_angle_arc, m_ar_plane_center, m_bb_center, Slic3r::GUI::GLGizmoBase::m_parent, m_plane_center, m_rotation_m, m_start_dragging_m, m_transformed_bounding_box, Slic3r::GUI::GLCanvas3D::request_extra_frame(), Slic3r::GUI::GLModel::reset(), reset_cut_by_contours(), set_center(), and transformed_bounding_box().
Referenced by render_cut_plane_input_window().
rotate_vec3d_around_plane_center()
void Slic3r::GUI::GLGizmoCut3D::rotate_vec3d_around_plane_center (Vec3d & vec)
{
    vec = Transformation(translation_transform(m_plane_center) * m_rotation_m * translation_transform(-m_plane_center)).get_matrix() * vec;
}
References Slic3r::Geometry::Transformation::get_matrix(), m_plane_center, m_rotation_m, and Slic3r::Geometry::translation_transform().
Referenced by update_clipper().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
select_all_connectors()
void Slic3r::GUI::GLGizmoCut3D::select_all_connectors () protected
{
    std::fill(m_selected.begin(), m_selected.end(), true);
    m_selected_count = int(m_selected.size());
}
References m_selected, and m_selected_count.
Referenced by gizmo_event().
select_connector()
void Slic3r::GUI::GLGizmoCut3D::select_connector (int idx, bool select) protected
{
    m_selected[idx] = select;
    if (select)
        ++m_selected_count;
    else
        --m_selected_count;
}
References m_selected, and m_selected_count.
Referenced by gizmo_event(), is_selection_changed(), and process_selection_rectangle().
set_center()
void Slic3r::GUI::GLGizmoCut3D::set_center (const Vec3d & center, bool update_tbb = false) private
{
    set_center_pos(center, update_tbb);
    check_and_update_connectors_state();
    update_clipper();
}
References check_and_update_connectors_state(), set_center_pos(), and update_clipper().
Referenced by dragging_grabber_z(), process_cut_line(), render_move_center_input(), reset_cut_plane(), and shift_cut().
set_center_pos()
void Slic3r::GUI::GLGizmoCut3D::set_center_pos (const Vec3d & center_pos, bool update_tbb = false) private
{
    BoundingBoxf3 tbb = m_transformed_bounding_box;
    if (update_tbb) {
        Vec3d normal = m_rotation_m.inverse() * Vec3d(m_plane_center - center_pos);
        tbb.translate(normal.z() * Vec3d::UnitZ());
    }
    bool can_set_center_pos = false;
    {
        if (tbb.max.z() > -.5 && tbb.min.z() < .5)
            can_set_center_pos = true;
        else {
            const double old_dist = (m_bb_center - m_plane_center).norm();
            const double new_dist = (m_bb_center - center_pos).norm();
            // check if forcing is reasonable
            if (new_dist < old_dist)
                can_set_center_pos = true;
        }
    }
    if (can_set_center_pos) {
        m_transformed_bounding_box = tbb;
        m_plane_center = center_pos;
        m_center_offset = m_plane_center - m_bb_center;
    }
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), m_bb_center, m_center_offset, m_plane_center, m_rotation_m, m_transformed_bounding_box, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, and Slic3r::BoundingBox3Base< PointType >::translate().
Referenced by on_load(), set_center(), and update_bb().
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c.
set_connectors_editing()
void Slic3r::GUI::GLGizmoCut3D::set_connectors_editing (bool connectors_editing) protected
{
    if (m_connectors_editing == connectors_editing)
        return;
    m_connectors_editing = connectors_editing;
    update_raycasters_for_picking();
    m_c->object_clipper()->set_behavior(m_connectors_editing, m_connectors_editing, double(m_contour_width));
    m_parent.request_extra_frame();
}
References Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, m_contour_width, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::GLCanvas3D::request_extra_frame(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_behavior(), and update_raycasters_for_picking().
Referenced by render_connectors_input_window(), and render_cut_plane_input_window().
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by process_cut_line(), and Slic3r::GUI::GLGizmoSimplify::request_rerender().
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    // do not change hover id during dragging
    assert(!m_dragging);
    // allow empty grabbers when not using grabbers but use hover_id - flatten, rotate
//    if (!m_grabbers.empty() && id >= (int) m_grabbers.size())
//        return;
    m_hover_id = id;
    on_set_hover_id();
}
References Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), and Slic3r::GUI::GLGizmoEmboss::on_set_state().
set_volumes_picking_state()
void Slic3r::GUI::GLGizmoCut3D::set_volumes_picking_state (bool state) protected
{
    std::vector<std::shared_ptr<SceneRaycasterItem>>* raycasters = m_parent.get_raycasters_for_picking(SceneRaycaster::EType::Volume);
    if (raycasters != nullptr) {
        const Selection& selection = m_parent.get_selection();
        const Selection::IndicesList ids = selection.get_volume_idxs();
        for (unsigned int id : ids) {
            const GLVolume* v = selection.get_volume(id);
            auto it = std::find_if(raycasters->begin(), raycasters->end(), [v](std::shared_ptr<SceneRaycasterItem> item) { return item->get_raycaster() == v->mesh_raycaster.get(); });
            if (it != raycasters->end())
                (*it)->set_active(state);
        }
    }
}
References Slic3r::GUI::GLCanvas3D::get_raycasters_for_picking(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::GUI::SceneRaycaster::Volume.
shift_cut()
void Slic3r::GUI::GLGizmoCut3D::shift_cut (double delta)
{
    Plater::TakeSnapshot snapshot(wxGetApp().plater(), _L("Move cut plane"), UndoRedo::SnapshotType::GizmoAction);
    set_center(m_plane_center + m_cut_normal * delta, true);
    m_ar_plane_center = m_plane_center;
}
References _L, Slic3r::UndoRedo::GizmoAction, m_ar_plane_center, m_cut_normal, m_plane_center, Slic3r::GUI::plater(), and set_center().
Referenced by Slic3r::GUI::GLGizmosManager::on_key().
transformed_bounding_box()
BoundingBoxf3 Slic3r::GUI::GLGizmoCut3D::transformed_bounding_box (const Vec3d & plane_center, const Transform3d & rotation_m = Transform3d::Identity()) const
{
    const Selection& selection = m_parent.get_selection();
    const auto first_volume = selection.get_first_volume();
    Vec3d instance_offset   = first_volume->get_instance_offset();
    instance_offset[Z]     += first_volume->get_sla_shift_z();
    const auto cut_matrix = Transform3d::Identity() * rotation_m.inverse() * translation_transform(instance_offset - plane_center);
    const Selection::IndicesList& idxs = selection.get_volume_idxs();
    BoundingBoxf3 ret;
    for (unsigned int i : idxs) {
        const GLVolume* volume = selection.get_volume(i);
        // respect just to the solid parts for FFF and ignore pad and supports for SLA
        if (!volume->is_modifier && !volume->is_sla_pad() && !volume->is_sla_support()) {
            const auto instance_matrix = volume->get_instance_transformation().get_matrix_no_offset();
            auto volume_trafo = instance_matrix * volume->get_volume_transformation().get_matrix();
            ret.merge(volume->transformed_convex_hull_bounding_box(cut_matrix * volume_trafo));
        }
    }
    return ret;
}
References Slic3r::GUI::Selection::get_first_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::BoundingBox3Base< PointType >::merge(), Slic3r::Geometry::translation_transform(), and Z.
Referenced by dragging_grabber_xy(), flip_cut_plane(), on_load(), on_set_state(), process_cut_line(), reset_cut_plane(), and update_bb().
unproject_on_cut_plane()
bool Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane (const Vec2d & mouse_pos, Vec3d & pos, Vec3d & pos_world, bool respect_disabled_contour = true)
{
    const float sla_shift = m_c->selection_info()->get_sla_shift();
    const ModelObject* mo = m_c->selection_info()->model_object();
    const ModelInstance* mi = mo->instances[m_c->selection_info()->get_active_instance()];
    const Camera& camera = wxGetApp().plater()->get_camera();
    // Calculate intersection with the clipping plane.
    const ClippingPlane* cp = m_c->object_clipper()->get_clipping_plane(true);
    Vec3d point;
    Vec3d direction;
    Vec3d hit;
    MeshRaycaster::line_from_mouse_pos(mouse_position, Transform3d::Identity(), camera, point, direction);
    Vec3d normal = -cp->get_normal().cast<double>();
    double den = normal.dot(direction);
    if (den != 0.) {
        double t = (-cp->get_offset() - normal.dot(point))/den;
        hit = (point + t * direction);
    } else
        return false;
    // Now check if the hit is not obscured by a selected part on this side of the plane.
    // FIXME: This would be better solved by remembering which contours are active. We will
    // probably need that anyway because there is not other way to find out which contours
    // to render. If you want to uncomment it, fix it first. It does not work yet.
    /*for (size_t id = 0; id < m_part_selection.parts.size(); ++id) {
        if (! m_part_selection.parts[id].selected) {
            Vec3f pos, normal;
            const ModelObject* model_object = m_part_selection.model_object;
            const Vec3d volume_offset = m_part_selection.model_object->volumes[id]->get_offset();
            Transform3d tr = model_object->instances[m_part_selection.instance_idx]->get_matrix() * model_object->volumes[id]->get_matrix();
            if (m_part_selection.parts[id].raycaster.unproject_on_mesh(mouse_position, tr, camera, pos, normal))
                return false;
        }
    }*/
    {
        // Do not react to clicks outside a contour (or inside a contour that is ignored)
        int cont_id = m_c->object_clipper()->is_projection_inside_cut(hit);
        if (cont_id == -1)
            return false;
        if (m_part_selection.valid()) {
            const std::vector<size_t>& ign = *m_part_selection.get_ignored_contours_ptr();
            if (std::find(ign.begin(), ign.end(), cont_id) != ign.end())
                return false;
        }
    }
    // recalculate hit to object's local position
    Vec3d hit_d = hit;
    hit_d -= mi->get_offset();
    hit_d[Z] -= sla_shift;
    // Return both the point and the facet normal.
    pos = hit_d;
    pos_world = hit;
    return true;
}
References Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::GUI::GLGizmoCut3D::PartSelection::get_ignored_contours_ptr(), Slic3r::GUI::ClippingPlane::get_normal(), Slic3r::ModelInstance::get_offset(), Slic3r::GUI::ClippingPlane::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::ModelObject::instances, Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::is_projection_inside_cut(), Slic3r::GUI::MeshRaycaster::line_from_mouse_pos(), Slic3r::GUI::GLGizmoBase::m_c, m_part_selection, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLGizmoCut3D::PartSelection::valid(), and Z.
Referenced by add_connector(), dragging_connector(), and on_mouse().
unregister_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking () protected inherited
{
    for (size_t i = 0; i < m_grabbers.size(); ++i) {
        m_grabbers[i].unregister_raycasters_for_picking();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers.
Referenced by Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking().
unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking () inline inherited
{ unregister_grabbers_for_picking(); on_unregister_raycasters_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking().
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo(), Slic3r::GUI::GLGizmoEmboss::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLCanvas3D::reload_scene().
unselect_all_connectors()
void Slic3r::GUI::GLGizmoCut3D::unselect_all_connectors () protected
{
    std::fill(m_selected.begin(), m_selected.end(), false);
    m_selected_count = 0;
    validate_connector_settings();
}
References m_selected, m_selected_count, and validate_connector_settings().
Referenced by add_connector(), gizmo_event(), is_selection_changed(), on_mouse(), and render_connectors_input_window().
update_bb()
void Slic3r::GUI::GLGizmoCut3D::update_bb () private
{
    const BoundingBoxf3 box = bounding_box();
    if (!box.defined)
        return;
    if (!m_max_pos.isApprox(box.max) || !m_min_pos.isApprox(box.min)) {
        m_bounding_box = box;
        invalidate_cut_plane();
        reset_cut_by_contours();
        m_max_pos = box.max;
        m_min_pos = box.min;
        m_bb_center = box.center();
        m_transformed_bounding_box = transformed_bounding_box(m_bb_center);
        if (box.contains(m_center_offset))
            set_center_pos(m_bb_center + m_center_offset);
        else
            set_center_pos(m_bb_center);
        m_radius = box.radius();
        m_grabber_connection_len = 0.5 * m_radius;// std::min<double>(0.75 * m_radius, 35.0);
        m_grabber_radius = m_grabber_connection_len * 0.85;
        m_snap_coarse_in_radius   = m_grabber_radius / 3.0;
        m_snap_coarse_out_radius  = m_snap_coarse_in_radius * 2.;
        m_snap_fine_in_radius     = m_grabber_connection_len * 0.85;
        m_snap_fine_out_radius    = m_grabber_connection_len * 1.15;
        m_plane.reset();
        m_cone.reset();
        m_sphere.reset();
        m_grabber_connection.reset();
        m_circle.reset();
        m_scale.reset();
        m_snap_radii.reset();
        m_reference_radius.reset();
        on_unregister_raycasters_for_picking();
        clear_selection();
        if (CommonGizmosDataObjects::SelectionInfo* selection = m_c->selection_info();
            selection && selection->model_object())
            m_selected.resize(selection->model_object()->cut_connectors.size(), false);
    }
}
References bounding_box(), Slic3r::BoundingBox3Base< PointType >::center(), clear_selection(), Slic3r::BoundingBox3Base< PointType >::contains(), Slic3r::BoundingBoxBase< PointType, APointsType >::defined, invalidate_cut_plane(), m_bb_center, m_bounding_box, Slic3r::GUI::GLGizmoBase::m_c, m_center_offset, m_circle, m_cone, m_grabber_connection, m_grabber_connection_len, m_grabber_radius, m_max_pos, m_min_pos, m_plane, m_radius, m_reference_radius, m_scale, m_selected, m_snap_coarse_in_radius, m_snap_coarse_out_radius, m_snap_fine_in_radius, m_snap_fine_out_radius, m_snap_radii, m_sphere, m_transformed_bounding_box, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, on_unregister_raycasters_for_picking(), Slic3r::BoundingBox3Base< PointType >::radius(), Slic3r::GUI::GLModel::reset(), Slic3r::GUI::PickingModel::reset(), reset_cut_by_contours(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), set_center_pos(), and transformed_bounding_box().
Referenced by data_changed(), and on_set_state().
update_clipper()
void Slic3r::GUI::GLGizmoCut3D::update_clipper ()
{
    // update cut_normal
    Vec3d normal = m_rotation_m * Vec3d::UnitZ();
    normal.normalize();
    m_cut_normal = normal;
    // calculate normal and offset for clipping plane
    Vec3d beg = m_bb_center;
    beg[Z] -= m_radius;
    rotate_vec3d_around_plane_center(beg);
    m_clp_normal  = normal;
    double offset = normal.dot(m_plane_center);
    double dist   = normal.dot(beg);
    m_parent.set_color_clip_plane(normal, offset);
    if (!is_looking_forward()) {
        // recalculate normal and offset for clipping plane, if camera is looking downward to cut plane
        normal = m_rotation_m * (-1. * Vec3d::UnitZ());
        normal.normalize();
        beg = m_bb_center;
        beg[Z] += m_radius;
        rotate_vec3d_around_plane_center(beg);
        m_clp_normal = normal;
        offset       = normal.dot(m_plane_center);
        dist         = normal.dot(beg);
    }
    m_c->object_clipper()->set_range_and_pos(normal, offset, dist);
    put_connectors_on_cut_plane(normal, offset);
    if (m_raycasters.empty())
        on_register_raycasters_for_picking();
    else
        update_raycasters_for_picking_transform();
}
References Slic3r::Geometry::dist(), is_looking_forward(), m_bb_center, Slic3r::GUI::GLGizmoBase::m_c, m_clp_normal, m_cut_normal, Slic3r::GUI::GLGizmoBase::m_parent, m_plane_center, m_radius, m_raycasters, m_rotation_m, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::offset(), on_register_raycasters_for_picking(), put_connectors_on_cut_plane(), rotate_vec3d_around_plane_center(), Slic3r::GUI::GLCanvas3D::set_color_clip_plane(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_range_and_pos(), update_raycasters_for_picking_transform(), and Z.
Referenced by dragging_grabber_xy(), flip_cut_plane(), on_render(), and set_center().
update_connector_shape()
void Slic3r::GUI::GLGizmoCut3D::update_connector_shape () private
{
    CutConnectorAttributes attribs = { m_connector_type, CutConnectorStyle(m_connector_style), CutConnectorShape(m_connector_shape_id) };
    const indexed_triangle_set its = ModelObject::get_connector_mesh(attribs);
    m_connector_mesh.clear();
    m_connector_mesh = TriangleMesh(its);
}
References Slic3r::TriangleMesh::clear(), Slic3r::ModelObject::get_connector_mesh(), m_connector_mesh, m_connector_shape_id, m_connector_style, and m_connector_type.
Referenced by GLGizmoCut3D(), render_combo(), and render_connect_type_radio_button().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
update_raycasters_for_picking()
void Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking () protected
{
    on_unregister_raycasters_for_picking();
    on_register_raycasters_for_picking();
}
References on_register_raycasters_for_picking(), and on_unregister_raycasters_for_picking().
Referenced by add_connector(), delete_selected_connectors(), reset_connectors(), and set_connectors_editing().
update_raycasters_for_picking_transform()
void Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform () protected
{
    if (m_connectors_editing) {
        CommonGizmosDataObjects::SelectionInfo* si = m_c->selection_info();
        if (!si)
            return;
        const ModelObject* mo = si->model_object();
        const CutConnectors& connectors = mo->cut_connectors;
        if (connectors.empty())
            return;
        auto inst_id = m_c->selection_info()->get_active_instance();
        if (inst_id < 0)
            return;
        const Vec3d& instance_offset = mo->instances[inst_id]->get_offset();
        const double sla_shift = double(m_c->selection_info()->get_sla_shift());
        const bool looking_forward = is_looking_forward();
        for (size_t i = 0; i < connectors.size(); ++i) {
            const CutConnector& connector = connectors[i];
            float height = connector.height;
            // recalculate connector position to world position
            Vec3d pos = connector.pos + instance_offset;
            if (connector.attribs.type == CutConnectorType::Dowel &&
                connector.attribs.style == CutConnectorStyle::Prism) {
                height = 0.05f;
                if (!looking_forward)
                    pos += 0.05 * m_clp_normal;
            }
            pos[Z] += sla_shift;
            const Transform3d scale_trafo = scale_transform(Vec3f(connector.radius, connector.radius, height).cast<double>());
            m_raycasters[i]->set_transform(translation_transform(pos) * m_rotation_m * scale_trafo);
        }
    }
    else if (!cut_line_processing()){
        const Transform3d trafo = translation_transform(m_plane_center) * m_rotation_m;
        const BoundingBoxf3 box = m_bounding_box;
        const double size = get_half_size(get_grabber_mean_size(box));
        Vec3d scale = Vec3d(0.75 * size, 0.75 * size, 1.8 * size);
        int id = 0;
        Vec3d offset = Vec3d(0.0, 1.25 * size, m_grabber_connection_len);
        m_raycasters[id++]->set_transform(trafo * translation_transform(offset) * rotation_transform(-0.5 * PI * Vec3d::UnitX()) * scale_transform(scale));
        offset = Vec3d(0.0, -1.25 * size, m_grabber_connection_len);
        m_raycasters[id++]->set_transform(trafo * translation_transform(offset) * rotation_transform(0.5 * PI * Vec3d::UnitX()) * scale_transform(scale));
        offset = Vec3d(1.25 * size, 0.0, m_grabber_connection_len);
        m_raycasters[id++]->set_transform(trafo * translation_transform(offset) * rotation_transform(0.5 * PI * Vec3d::UnitY()) * scale_transform(scale));
        offset = Vec3d(-1.25 * size, 0.0, m_grabber_connection_len);
        m_raycasters[id++]->set_transform(trafo * translation_transform(offset) * rotation_transform(-0.5 * PI * Vec3d::UnitY()) * scale_transform(scale));
        offset = 1.25 * size * Vec3d::UnitZ();
        m_raycasters[id++]->set_transform(trafo * translation_transform(m_grabber_connection_len * Vec3d::UnitZ()) * scale_transform(size));
        m_raycasters[id++]->set_transform(trafo);
    }
}
References Slic3r::CutConnector::attribs, Slic3r::ModelObject::cut_connectors, cut_line_processing(), Slic3r::Dowel, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::get_grabber_mean_size(), Slic3r::GUI::get_half_size(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::CutConnector::height, Slic3r::ModelObject::instances, is_looking_forward(), m_bounding_box, Slic3r::GUI::GLGizmoBase::m_c, m_clp_normal, m_connectors_editing, m_grabber_connection_len, m_plane_center, m_raycasters, m_rotation_m, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::offset(), PI, Slic3r::CutConnector::pos, Slic3r::Prism, Slic3r::CutConnector::radius, Slic3r::Geometry::rotation_transform(), scale(), Slic3r::Geometry::scale_transform(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::CutConnectorAttributes::style, Slic3r::Geometry::translation_transform(), Slic3r::CutConnectorAttributes::type, and Z.
Referenced by apply_selected_connectors(), dragging_connector(), on_register_raycasters_for_picking(), and update_clipper().
use_grabbers()
bool Slic3r::GUI::GLGizmoBase::use_grabbers (const wxMouseEvent & mouse_event) protected inherited
function which Set up m_dragging and call functions on_start_dragging / on_dragging / on_stop_dragging
Parameters
mouse_event Keep information about mouse click
Returns
same as on_mouse
{
    bool is_dragging_finished = false;
    if (mouse_event.Moving()) {
        // it should not happen but for sure
        assert(!m_dragging);
        if (m_dragging) is_dragging_finished = true;
        else return false;
    }
    if (mouse_event.LeftDown()) {
        Selection &selection = m_parent.get_selection();
        if (!selection.is_empty() && m_hover_id != -1 /* &&
            (m_grabbers.empty() || m_hover_id < static_cast<int>(m_grabbers.size()))*/) {
            selection.setup_cache();
            m_dragging = true;
            for (auto &grabber : m_grabbers) grabber.dragging = false;
//            if (!m_grabbers.empty() && m_hover_id < int(m_grabbers.size()))
//                m_grabbers[m_hover_id].dragging = true;
            on_start_dragging();
            // Let the plater know that the dragging started
            m_parent.post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_STARTED));
            m_parent.set_as_dirty();
            return true;
        }
    } else if (m_dragging) {
        // when mouse cursor leave window than finish actual dragging operation
        bool is_leaving = mouse_event.Leaving();
        if (mouse_event.Dragging()) {
            Point      mouse_coord(mouse_event.GetX(), mouse_event.GetY());
            auto       ray = m_parent.mouse_ray(mouse_coord);
            UpdateData data(ray, mouse_coord);
            on_dragging(data);
            wxGetApp().obj_manipul()->set_dirty();
            m_parent.set_as_dirty();
            return true;
        }
        else if (mouse_event.LeftUp() || is_leaving || is_dragging_finished) {
            do_stop_dragging(is_leaving);
            return true;
        }
    }
    return false;
}
References Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::mouse_ray(), Slic3r::GUI::GLGizmoBase::on_dragging(), Slic3r::GUI::GLGizmoBase::on_start_dragging(), Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::Selection::setup_cache().
Referenced by on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_mouse(), Slic3r::GUI::GLGizmoRotate::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), and Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation().
validate_connector_settings()
void Slic3r::GUI::GLGizmoCut3D::validate_connector_settings () private
{
    if (m_connector_depth_ratio < 0.f)
        m_connector_depth_ratio = 3.f;
    if (m_connector_depth_ratio_tolerance < 0.f)
        m_connector_depth_ratio_tolerance = 0.1f;
    if (m_connector_size < 0.f)
        m_connector_size = 2.5f;
    if (m_connector_size_tolerance < 0.f)
        m_connector_size_tolerance = 0.f;
    if (m_connector_type == CutConnectorType::Undef)
        m_connector_type = CutConnectorType::Plug;
    if (m_connector_style == int(CutConnectorStyle::Undef))
        m_connector_style = int(CutConnectorStyle::Prism);
    if (m_connector_shape_id == int(CutConnectorShape::Undef))
        m_connector_shape_id = int(CutConnectorShape::Circle);
}
References Slic3r::Circle, m_connector_depth_ratio, m_connector_depth_ratio_tolerance, m_connector_shape_id, m_connector_size, m_connector_size_tolerance, m_connector_style, m_connector_type, Slic3r::Plug, Slic3r::Prism, and Slic3r::Undef.
Referenced by unselect_all_connectors().
wants_enter_leave_snapshots()
bool Slic3r::GUI::GLGizmoCut3D::wants_enter_leave_snapshots () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return true; }
Member Data Documentation
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
GRABBER_ELEMENTS_MAX_COUNT
const unsigned int Slic3r::GUI::GLGizmoBase::GRABBER_ELEMENTS_MAX_COUNT = 7 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render().
m_angle
double Slic3r::GUI::GLGizmoCut3D::m_angle { 0.0 } private
Referenced by dragging_grabber_xy(), get_tooltip(), init_rendering_items(), on_start_dragging(), and on_stop_dragging().
m_angle_arc
GLModel Slic3r::GUI::GLGizmoCut3D::m_angle_arc private
Referenced by init_rendering_items(), on_stop_dragging(), process_cut_line(), render_rotation_snapping(), and reset_cut_plane().
m_ar_plane_center
Vec3d Slic3r::GUI::GLGizmoCut3D::m_ar_plane_center { Vec3d::Zero() } private
Referenced by on_load(), on_save(), on_set_state(), on_stop_dragging(), process_cut_line(), render_move_center_input(), reset_cut_plane(), and shift_cut().
m_axis_names
std::vector<std::string> Slic3r::GUI::GLGizmoCut3D::m_axis_names private
Referenced by GLGizmoCut3D(), and render_move_center_input().
m_bb_center
Vec3d Slic3r::GUI::GLGizmoCut3D::m_bb_center { Vec3d::Zero() } private
Referenced by invalidate_cut_plane(), process_cut_line(), render_cut_plane_input_window(), reset_cut_plane(), set_center_pos(), update_bb(), and update_clipper().
m_bounding_box
BoundingBoxf3 Slic3r::GUI::GLGizmoCut3D::m_bounding_box private
Referenced by init_picking_models(), is_conflict_for_connector(), render_cut_plane_grabbers(), render_slider_double_input(), update_bb(), and update_raycasters_for_picking_transform().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c { nullptr } protected inherited
Referenced by Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoFdmSupports::auto_generate(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), check_and_update_connectors_state(), data_changed(), Slic3r::GUI::GLGizmoFdmSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), dragging_connector(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), has_valid_contour(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoHollow::on_dragging(), on_register_raycasters_for_picking(), on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), process_contours(), process_selection_rectangle(), put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoHollow::reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), render_clipper_cut(), render_connectors(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), render_debug_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), reset_connectors(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), set_connectors_editing(), unproject_on_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), update_bb(), update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), update_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
m_center_offset
Vec3d Slic3r::GUI::GLGizmoCut3D::m_center_offset { Vec3d::Zero() } private
Referenced by invalidate_cut_plane(), set_center_pos(), and update_bb().
m_circle
GLModel Slic3r::GUI::GLGizmoCut3D::m_circle private
Referenced by init_rendering_items(), render_rotation_snapping(), and update_bb().
m_clp_normal
Vec3d Slic3r::GUI::GLGizmoCut3D::m_clp_normal { Vec3d::Ones() } private
Referenced by render_connectors(), update_clipper(), and update_raycasters_for_picking_transform().
m_cone
PickingModel Slic3r::GUI::GLGizmoCut3D::m_cone private
Referenced by init_picking_models(), on_register_raycasters_for_picking(), render_cut_plane_grabbers(), and update_bb().
m_connector_depth_ratio
float Slic3r::GUI::GLGizmoCut3D::m_connector_depth_ratio { 3.f } private
Referenced by add_connector(), init_input_window_data(), render_connectors_input_window(), and validate_connector_settings().
m_connector_depth_ratio_tolerance
float Slic3r::GUI::GLGizmoCut3D::m_connector_depth_ratio_tolerance { 0.1f } private
Referenced by add_connector(), init_input_window_data(), render_connectors_input_window(), and validate_connector_settings().
m_connector_mesh
TriangleMesh Slic3r::GUI::GLGizmoCut3D::m_connector_mesh private
Referenced by update_connector_shape().
m_connector_mode
CutConnectorMode Slic3r::GUI::GLGizmoCut3D::m_connector_mode { CutConnectorMode::Manual } private
Referenced by apply_connectors_in_model(), gizmo_event(), on_dragging(), on_start_dragging(), render_connect_mode_radio_button(), and render_connectors().
m_connector_modes
std::vector<std::string> Slic3r::GUI::GLGizmoCut3D::m_connector_modes private
Referenced by GLGizmoCut3D(), and render_connect_mode_radio_button().
m_connector_shape_id
int Slic3r::GUI::GLGizmoCut3D::m_connector_shape_id private
Referenced by add_connector(), init_input_window_data(), render_connectors_input_window(), update_connector_shape(), and validate_connector_settings().
m_connector_shapes
std::vector<std::string> Slic3r::GUI::GLGizmoCut3D::m_connector_shapes private
Referenced by GLGizmoCut3D(), and render_connectors_input_window().
m_connector_size
float Slic3r::GUI::GLGizmoCut3D::m_connector_size { 2.5f } private
Referenced by add_connector(), init_input_window_data(), render_connectors_input_window(), and validate_connector_settings().
m_connector_size_tolerance
float Slic3r::GUI::GLGizmoCut3D::m_connector_size_tolerance { 0.f } private
Referenced by add_connector(), init_input_window_data(), render_connectors_input_window(), and validate_connector_settings().
m_connector_style
int Slic3r::GUI::GLGizmoCut3D::m_connector_style private
Referenced by add_connector(), init_input_window_data(), render_connectors_input_window(), update_connector_shape(), and validate_connector_settings().
m_connector_styles
std::vector<std::string> Slic3r::GUI::GLGizmoCut3D::m_connector_styles private
Referenced by GLGizmoCut3D(), and render_connectors_input_window().
m_connector_type
CutConnectorType Slic3r::GUI::GLGizmoCut3D::m_connector_type private
Referenced by add_connector(), init_input_window_data(), render_connect_type_radio_button(), render_connectors_input_window(), update_connector_shape(), and validate_connector_settings().
m_connector_types
std::vector<std::string> Slic3r::GUI::GLGizmoCut3D::m_connector_types private
Referenced by GLGizmoCut3D(), and render_connect_type_radio_button().
m_connectors_editing
bool Slic3r::GUI::GLGizmoCut3D::m_connectors_editing { false } private
Referenced by add_connector(), can_perform_cut(), data_changed(), gizmo_event(), init_input_window_data(), init_picking_models(), is_in_editing_mode(), on_load(), on_mouse(), on_register_raycasters_for_picking(), on_render(), on_render_input_window(), on_save(), on_set_state(), render_clipper_cut(), render_connectors(), render_connectors_input_window(), render_debug_input_window(), set_connectors_editing(), and update_raycasters_for_picking_transform().
m_connectors_group_id
int Slic3r::GUI::GLGizmoCut3D::m_connectors_group_id private
Referenced by dragging_connector(), gizmo_event(), is_selection_changed(), on_dragging(), on_mouse(), on_register_raycasters_for_picking(), on_start_dragging(), and render_connectors().
m_contour_width
float Slic3r::GUI::GLGizmoCut3D::m_contour_width { 0.4f } private
Referenced by data_changed(), render_debug_input_window(), and set_connectors_editing().
m_control_width
float Slic3r::GUI::GLGizmoCut3D::m_control_width { 200.f } private
Referenced by init_input_window_data(), render_combo(), render_connect_mode_radio_button(), render_connect_type_radio_button(), render_connectors_input_window(), render_cut_plane_input_window(), render_double_input(), render_move_center_input(), and render_slider_double_input().
m_cut_line
GLModel Slic3r::GUI::GLGizmoCut3D::m_cut_line private
Referenced by render_cut_line().
m_cut_normal
Vec3d Slic3r::GUI::GLGizmoCut3D::m_cut_normal private
Referenced by apply_connectors_in_model(), is_looking_forward(), on_render(), process_contours(), shift_cut(), and update_clipper().
m_cut_plane_as_circle
bool Slic3r::GUI::GLGizmoCut3D::m_cut_plane_as_circle { false } private
Referenced by init_picking_models(), and render_debug_input_window().
m_cut_plane_radius_koef
float Slic3r::GUI::GLGizmoCut3D::m_cut_plane_radius_koef { 1.5f } private
Referenced by init_picking_models(), and render_debug_input_window().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty { false } private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging { false } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::do_stop_dragging(), get_tooltip(), Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_render(), render_cut_plane_grabbers(), render_rotation_snapping(), Slic3r::GUI::GLGizmoBase::set_hover_id(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render { true } protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_grabber_connection
GLModel Slic3r::GUI::GLGizmoCut3D::m_grabber_connection private
Referenced by init_rendering_items(), render_grabber_connection(), and update_bb().
m_grabber_connection_len
double Slic3r::GUI::GLGizmoCut3D::m_grabber_connection_len { 0.0 } private
Referenced by dragging_grabber_z(), init_rendering_items(), render_cut_plane_grabbers(), render_grabber_connection(), update_bb(), and update_raycasters_for_picking_transform().
m_grabber_radius
double Slic3r::GUI::GLGizmoCut3D::m_grabber_radius { 0.0 } private
Referenced by init_rendering_items(), and update_bb().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoRotate::disable_grabber(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoRotate::enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoRotate::render_grabber_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLGizmoRotate::start_dragging(), Slic3r::GUI::GLGizmoRotate::stop_dragging(), Slic3r::GUI::GLGizmoBase::unregister_grabbers_for_picking(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate::GLGizmoRotate(), Slic3r::GUI::GLGizmoBase::register_grabbers_for_picking(), and Slic3r::GUI::GLGizmoRotate::set_group_id().
m_hide_cut_plane
bool Slic3r::GUI::GLGizmoCut3D::m_hide_cut_plane { false } private
Referenced by init_picking_models(), on_load(), on_render(), and on_save().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id { -1 } protected inherited
Referenced by dragging_connector(), dragging_grabber_xy(), dragging_grabber_z(), Slic3r::GUI::GLGizmoBase::get_hover_id(), get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), is_selection_changed(), on_dragging(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_dragging(), Slic3r::GUI::GLGizmoScale3D::on_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_dragging(), on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoEmboss::on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id(), on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging(), on_stop_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging(), render_connectors(), render_cut_plane(), render_cut_plane_grabbers(), render_flip_plane_button(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename().
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), add_horizontal_scaled_interval(), add_vertical_scaled_interval(), adjust_window_position(), Slic3r::GUI::GLGizmoSimplify::create_gui_cfg(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_font_preview(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_style_add_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_button(), Slic3r::GUI::GLGizmoEmboss::draw_style_rename_popup(), Slic3r::GUI::GLGizmoEmboss::draw_style_save_as_popup(), Slic3r::GUI::GLGizmoEmboss::draw_text_input(), Slic3r::GUI::GLGizmoEmboss::draw_window(), init_input_window_data(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMeasure::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), render_build_size(), render_combo(), render_connectors_input_window(), render_cut_plane_input_window(), render_debug_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), render_double_input(), render_flip_plane_button(), render_input_window_warning(), render_move_center_input(), render_reset_button(), render_shortcuts(), render_slider_double_input(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), Slic3r::GUI::GLGizmoEmboss::rev_slider(), and Slic3r::GUI::GLGizmoEmboss::rev_slider().
m_imperial_units
bool Slic3r::GUI::GLGizmoCut3D::m_imperial_units { false } private
Referenced by get_tooltip(), init_input_window_data(), render_build_size(), render_double_input(), render_move_center_input(), and render_slider_double_input().
m_info_stats
struct Slic3r::GUI::GLGizmoCut3D::InvalidConnectorsStatistics Slic3r::GUI::GLGizmoCut3D::m_info_stats private
Referenced by check_and_update_connectors_state(), is_conflict_for_connector(), is_outside_of_cut_contour(), and render_input_window_warning().
m_invalid_connectors_idxs
std::vector<size_t> Slic3r::GUI::GLGizmoCut3D::m_invalid_connectors_idxs private
Referenced by can_perform_cut(), check_and_update_connectors_state(), render_connectors(), and render_input_window_warning().
m_is_contour_changed
bool Slic3r::GUI::GLGizmoCut3D::m_is_contour_changed { false } private
Referenced by render_connectors(), render_cut_plane_input_window(), and render_input_window_warning().
m_keep_as_parts
bool Slic3r::GUI::GLGizmoCut3D::m_keep_as_parts { false } private
Referenced by get_tooltip(), perform_cut(), and render_cut_plane_input_window().
m_keep_lower
bool Slic3r::GUI::GLGizmoCut3D::m_keep_lower { true } private
Referenced by can_perform_cut(), gizmo_event(), on_load(), on_save(), perform_cut(), render_cut_plane_input_window(), and render_input_window_warning().
m_keep_upper
bool Slic3r::GUI::GLGizmoCut3D::m_keep_upper { true } private
Referenced by can_perform_cut(), gizmo_event(), on_load(), on_save(), perform_cut(), render_cut_plane_input_window(), and render_input_window_warning().
m_label_width
float Slic3r::GUI::GLGizmoCut3D::m_label_width { 0.f } private
Referenced by init_input_window_data(), render_combo(), render_connect_mode_radio_button(), render_connect_type_radio_button(), render_connectors_input_window(), render_debug_input_window(), render_double_input(), and render_slider_double_input().
m_labels_map
std::map<std::string, std::string> Slic3r::GUI::GLGizmoCut3D::m_labels_map private
Referenced by GLGizmoCut3D(), init_input_window_data(), and render_connectors_input_window().
m_ldown_mouse_position
Vec2d Slic3r::GUI::GLGizmoCut3D::m_ldown_mouse_position { Vec2d::Zero() } private
Referenced by gizmo_event().
m_line_beg
Vec3d Slic3r::GUI::GLGizmoCut3D::m_line_beg { Vec3d::Zero() } private
Referenced by cut_line_processing(), discard_cut_line_processing(), process_cut_line(), and render_cut_line().
m_line_end
Vec3d Slic3r::GUI::GLGizmoCut3D::m_line_end { Vec3d::Zero() } private
Referenced by discard_cut_line_processing(), process_cut_line(), and render_cut_line().
m_max_pos
Vec3d Slic3r::GUI::GLGizmoCut3D::m_max_pos { Vec3d::Zero() } private
Referenced by invalidate_cut_plane(), and update_bb().
m_min_pos
Vec3d Slic3r::GUI::GLGizmoCut3D::m_min_pos { Vec3d::Zero() } private
Referenced by invalidate_cut_plane(), and update_bb().
m_mode
size_t Slic3r::GUI::GLGizmoCut3D::m_mode { size_t(CutMode::cutPlanar) } private
Referenced by on_load(), on_save(), and render_cut_plane_input_window().
m_old_center
Vec3d Slic3r::GUI::GLGizmoCut3D::m_old_center private
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by add_connector(), Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), bounding_box(), Slic3r::GUI::GLGizmoEmboss::calculate_scale(), Slic3r::GUI::GLGizmoEmboss::close(), Slic3r::GUI::GLGizmoSimplify::close(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoFlatten::data_changed(), Slic3r::GUI::GLGizmoMeasure::data_changed(), Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoRotate3D::data_changed(), delete_selected_connectors(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoEmboss::do_rotate(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoEmboss::do_translate(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeasure::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeasure::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), on_load(), on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate(), on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_register_raycasters_for_picking(), on_render(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_shortcut_key(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoEmboss::on_stop_dragging(), Slic3r::GUI::GLGizmoMove3D::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoScale3D::on_stop_dragging(), on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_unregister_raycasters_for_picking(), perform_cut(), Slic3r::GUI::GLGizmoEmboss::process(), Slic3r::GUI::GLGizmoSimplify::process(), process_contours(), process_cut_line(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::register_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::remove_selected_sphere_raycaster(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), render_cut_plane_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), reset_cut_by_contours(), reset_cut_plane(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), set_connectors_editing(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), set_volumes_picking_state(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), transformed_bounding_box(), Slic3r::GUI::GLGizmoHollow::unregister_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::unregister_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking(), update_clipper(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
m_part_orientation_names
std::map<std::string, wxString> Slic3r::GUI::GLGizmoCut3D::m_part_orientation_names private
Referenced by GLGizmoCut3D(), and render_cut_plane_input_window().
m_part_selection
PartSelection Slic3r::GUI::GLGizmoCut3D::m_part_selection private
Referenced by can_perform_cut(), flip_cut_plane(), is_outside_of_cut_contour(), on_mouse(), on_render(), on_set_state(), perform_cut(), process_contours(), render_clipper_cut(), render_cut_plane_input_window(), reset_cut_by_contours(), and unproject_on_cut_plane().
m_place_on_cut_lower
bool Slic3r::GUI::GLGizmoCut3D::m_place_on_cut_lower { false } private
Referenced by perform_cut(), and render_cut_plane_input_window().
m_place_on_cut_upper
bool Slic3r::GUI::GLGizmoCut3D::m_place_on_cut_upper { true } private
Referenced by perform_cut(), and render_cut_plane_input_window().
m_plane
PickingModel Slic3r::GUI::GLGizmoCut3D::m_plane private
Referenced by init_picking_models(), on_register_raycasters_for_picking(), render_cut_plane(), render_debug_input_window(), and update_bb().
m_plane_center
Vec3d Slic3r::GUI::GLGizmoCut3D::m_plane_center { Vec3d::Zero() } private
Referenced by dragging_grabber_xy(), dragging_grabber_z(), flip_cut_plane(), get_cut_matrix(), invalidate_cut_plane(), mouse_position_in_local_plane(), on_set_state(), on_stop_dragging(), process_contours(), process_cut_line(), render_cut_plane(), render_cut_plane_grabbers(), render_cut_plane_input_window(), render_move_center_input(), render_rotation_snapping(), reset_cut_plane(), rotate_vec3d_around_plane_center(), set_center_pos(), shift_cut(), update_clipper(), and update_raycasters_for_picking_transform().
m_radius
double Slic3r::GUI::GLGizmoCut3D::m_radius { 0.0 } private
Referenced by init_picking_models(), update_bb(), and update_clipper().
m_raycasters
std::vector<std::shared_ptr<SceneRaycasterItem> > Slic3r::GUI::GLGizmoCut3D::m_raycasters private
Referenced by on_register_raycasters_for_picking(), on_unregister_raycasters_for_picking(), update_clipper(), and update_raycasters_for_picking_transform().
m_reference_radius
GLModel Slic3r::GUI::GLGizmoCut3D::m_reference_radius private
Referenced by init_rendering_items(), render_rotation_snapping(), and update_bb().
m_rotate_lower
bool Slic3r::GUI::GLGizmoCut3D::m_rotate_lower { false } private
Referenced by on_load(), on_save(), perform_cut(), and render_cut_plane_input_window().
m_rotate_upper
bool Slic3r::GUI::GLGizmoCut3D::m_rotate_upper { false } private
Referenced by on_load(), on_save(), perform_cut(), and render_cut_plane_input_window().
m_rotation_m
Transform3d Slic3r::GUI::GLGizmoCut3D::m_rotation_m { Transform3d::Identity() } private
Referenced by add_connector(), apply_connectors_in_model(), dragging_grabber_xy(), dragging_grabber_z(), flip_cut_plane(), get_cut_matrix(), invalidate_cut_plane(), is_conflict_for_connector(), is_outside_of_cut_contour(), on_load(), on_set_state(), on_start_dragging(), on_stop_dragging(), process_cut_line(), render_connectors(), render_cut_plane(), render_cut_plane_grabbers(), render_cut_plane_input_window(), reset_cut_plane(), rotate_vec3d_around_plane_center(), set_center_pos(), update_clipper(), and update_raycasters_for_picking_transform().
m_scale
GLModel Slic3r::GUI::GLGizmoCut3D::m_scale private
Referenced by init_rendering_items(), render_rotation_snapping(), and update_bb().
m_selected
std::vector<bool> Slic3r::GUI::GLGizmoCut3D::m_selected mutable private
Referenced by add_connector(), apply_selected_connectors(), clear_selection(), delete_selected_connectors(), init_input_window_data(), on_set_state(), render_connectors(), select_all_connectors(), select_connector(), unselect_all_connectors(), and update_bb().
m_selected_count
int Slic3r::GUI::GLGizmoCut3D::m_selected_count { 0 } private
Referenced by add_connector(), clear_selection(), delete_selected_connectors(), init_input_window_data(), select_all_connectors(), select_connector(), and unselect_all_connectors().
m_selection_rectangle
GLSelectionRectangle Slic3r::GUI::GLGizmoCut3D::m_selection_rectangle private
Referenced by gizmo_event(), is_selection_rectangle_dragging(), on_render(), and process_selection_rectangle().
m_shapes
std::map<CutConnectorAttributes, PickingModel> Slic3r::GUI::GLGizmoCut3D::m_shapes private
Referenced by init_connector_shapes(), init_picking_models(), is_conflict_for_connector(), on_register_raycasters_for_picking(), and render_connectors().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), on_init(), Slic3r::GUI::GLGizmoEmboss::on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), Slic3r::GUI::GLGizmoHollow::on_init(), Slic3r::GUI::GLGizmoMeasure::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), and Slic3r::GUI::GLGizmoSlaSupports::on_init().
m_shortcut_label_width
float Slic3r::GUI::GLGizmoCut3D::m_shortcut_label_width { -1.f } private
Referenced by render_shortcuts().
m_shortcuts
std::vector<std::pair<wxString, wxString> > Slic3r::GUI::GLGizmoCut3D::m_shortcuts private
Referenced by on_init(), and render_shortcuts().
m_show_shortcuts
bool Slic3r::GUI::GLGizmoCut3D::m_show_shortcuts { false } private
Referenced by render_shortcuts().
m_snap_coarse_in_radius
double Slic3r::GUI::GLGizmoCut3D::m_snap_coarse_in_radius { 0.0 } private
Referenced by dragging_grabber_xy(), and update_bb().
m_snap_coarse_out_radius
double Slic3r::GUI::GLGizmoCut3D::m_snap_coarse_out_radius { 0.0 } private
Referenced by dragging_grabber_xy(), and update_bb().
m_snap_fine_in_radius
double Slic3r::GUI::GLGizmoCut3D::m_snap_fine_in_radius { 0.0 } private
Referenced by dragging_grabber_xy(), and update_bb().
m_snap_fine_out_radius
double Slic3r::GUI::GLGizmoCut3D::m_snap_fine_out_radius { 0.0 } private
Referenced by dragging_grabber_xy(), and update_bb().
m_snap_radii
GLModel Slic3r::GUI::GLGizmoCut3D::m_snap_radii private
Referenced by init_rendering_items(), render_rotation_snapping(), and update_bb().
m_snap_step
double Slic3r::GUI::GLGizmoCut3D::m_snap_step { 1.0 } private
Referenced by dragging_grabber_z().
m_sphere
PickingModel Slic3r::GUI::GLGizmoCut3D::m_sphere private
Referenced by init_picking_models(), on_register_raycasters_for_picking(), on_render(), render_cut_plane_grabbers(), and update_bb().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_start_dragging_m
Transform3d Slic3r::GUI::GLGizmoCut3D::m_start_dragging_m { Transform3d::Identity() } private
Referenced by dragging_grabber_xy(), flip_cut_plane(), mouse_position_in_local_plane(), on_save(), on_set_state(), on_start_dragging(), on_stop_dragging(), process_cut_line(), render_rotation_snapping(), and reset_cut_plane().
m_state
EState Slic3r::GUI::GLGizmoBase::m_state protected inherited
Referenced by Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoBase::load(), on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), on_set_state(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), Slic3r::GUI::GLGizmoRotate3D::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoBase::set_state(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), and Slic3r::GUI::GLGizmoSimplify::worker_finished().
m_transformed_bounding_box
BoundingBoxf3 Slic3r::GUI::GLGizmoCut3D::m_transformed_bounding_box private
Referenced by dragging_grabber_xy(), flip_cut_plane(), get_tooltip(), on_load(), on_set_state(), process_cut_line(), render_build_size(), reset_cut_plane(), set_center_pos(), and update_bb().
m_was_contour_selected
bool Slic3r::GUI::GLGizmoCut3D::m_was_contour_selected { false } private
Referenced by on_mouse().
m_was_cut_plane_dragged
bool Slic3r::GUI::GLGizmoCut3D::m_was_cut_plane_dragged { false } private
Referenced by dragging_grabber_z(), on_mouse(), and on_stop_dragging().
NO_SHORTCUT_KEY_VALUE
const int Slic3r::GUI::GLGizmoBase::NO_SHORTCUT_KEY_VALUE = 0 static inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoCut.hpp
src/slic3r/GUI/Gizmos/GLGizmoCut.cpp