Prusa Slicer: Eigen::TriangularBase< Derived > Class Template Reference
Eigen::TriangularBase< Derived > Class Template Reference
Base class for triangular part in a matrix.
#include <src/eigen/Eigen/src/Core/TriangularMatrix.h>
Public Types
enum {
Mode = internal::traits<Derived>::Mode , RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , SizeAtCompileTime , MaxSizeAtCompileTime
}
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::traits< Derived >::FullMatrixType DenseMatrixType
typedef DenseMatrixType DenseType
typedef Derived const & Nested
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
EIGEN_DEVICE_FUNC TriangularBase ()
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Index innerStride () const
void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC Scalar coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
template<typename Other >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, Other &other)
EIGEN_DEVICE_FUNC Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & operator() (Index row, Index col)
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & derived ()
template<typename DenseDerived >
EIGEN_DEVICE_FUNC void evalTo (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
EIGEN_DEVICE_FUNC void evalToLazy (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
void evalToLazy (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
Detailed Description
template<typename Derived>
class Eigen::TriangularBase< Derived >
Base class for triangular part in a matrix.
Member Typedef Documentation
DenseMatrixType
template<typename Derived > typedef internal::traits<Derived>::FullMatrixType Eigen::TriangularBase< Derived >::DenseMatrixType
DenseType
template<typename Derived > typedef DenseMatrixType Eigen::TriangularBase< Derived >::DenseType
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
Nested
template<typename Derived > typedef Derived const& Eigen::TriangularBase< Derived >::Nested
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::TriangularBase< Derived >::Scalar
StorageIndex
template<typename Derived > typedef internal::traits<Derived>::StorageIndex Eigen::TriangularBase< Derived >::StorageIndex
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::TriangularBase< Derived >::StorageKind
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
Mode
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxSizeAtCompileTime
         {
      Mode = internal::traits<Derived>::Mode,
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxSizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::MaxRowsAtCompileTime,
                                                   internal::traits<Derived>::MaxColsAtCompileTime>::ret)
    };
Constructor & Destructor Documentation
TriangularBase()
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::TriangularBase< Derived >::TriangularBase () inline
{ eigen_assert(!((Mode&UnitDiag) && (Mode&ZeroDiag))); }
References eigen_assert, Eigen::TriangularBase< Derived >::Mode, Eigen::UnitDiag, and Eigen::ZeroDiag.
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
check_coordinates()
template<typename Derived > void Eigen::TriangularBase< Derived >::check_coordinates (Index row, Index col) const inline protected
    {
      EIGEN_ONLY_USED_FOR_DEBUG(row);
      EIGEN_ONLY_USED_FOR_DEBUG(col);
      eigen_assert(col>=0 && col<cols() && row>=0 && row<rows());
      const int mode = int(Mode) & ~SelfAdjoint;
      EIGEN_ONLY_USED_FOR_DEBUG(mode);
      eigen_assert((mode==Upper && col>=row)
                || (mode==Lower && col<=row)
                || ((mode==StrictlyUpper || mode==UnitUpper) && col>row)
                || ((mode==StrictlyLower || mode==UnitLower) && col<row));
    }
References col(), Eigen::TriangularBase< Derived >::cols(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, Eigen::Lower, Eigen::TriangularBase< Derived >::Mode, row(), Eigen::TriangularBase< Derived >::rows(), Eigen::StrictlyLower, Eigen::StrictlyUpper, Eigen::UnitLower, Eigen::UnitUpper, and Eigen::Upper.
Referenced by Eigen::TriangularBase< Derived >::operator()(), and Eigen::TriangularBase< Derived >::operator()().
check_coordinates_internal()
template<typename Derived > void Eigen::TriangularBase< Derived >::check_coordinates_internal (Index , Index) const inline protected
{}
Referenced by Eigen::SelfAdjointView< _MatrixType, UpLo >::coeff(), and Eigen::SelfAdjointView< _MatrixType, UpLo >::coeffRef().
coeff()
template<typename Derived > EIGEN_DEVICE_FUNC Scalar Eigen::TriangularBase< Derived >::coeff (Index row, Index col) const inline
{ return derived().coeff(row,col); }
References col(), Eigen::TriangularBase< Derived >::derived(), and row().
Referenced by Eigen::TriangularBase< Derived >::operator()().
coeffRef()
template<typename Derived > EIGEN_DEVICE_FUNC Scalar & Eigen::TriangularBase< Derived >::coeffRef (Index row, Index col) inline
{ return derived().coeffRef(row,col); }
References col(), Eigen::TriangularBase< Derived >::derived(), and row().
Referenced by Eigen::TriangularBase< Derived >::operator()().
cols()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< Derived >::cols () const inline
{ return derived().cols(); }
References Eigen::TriangularBase< Derived >::derived().
Referenced by Eigen::TriangularBase< Derived >::check_coordinates(), Eigen::TriangularBase< Derived >::resize(), and Eigen::TriangularBase< Derived >::toDenseMatrix().
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
copyCoeff()
template<typename Derived > template<typename Other > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TriangularBase< Derived >::copyCoeff (Index row, Index col, Other & other) inline
See also
MatrixBase::copyCoeff(row,col)
    {
      derived().coeffRef(row, col) = other.coeff(row, col);
    }
References col(), Eigen::TriangularBase< Derived >::derived(), and row().
derived() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::TriangularBase< Derived >::derived () inline
{ return *static_cast<Derived*>(this); }
derived() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::TriangularBase< Derived >::derived () const inline
{ return *static_cast<const Derived*>(this); }
Referenced by Eigen::TriangularBase< Derived >::coeff(), Eigen::TriangularBase< Derived >::coeffRef(), Eigen::TriangularBase< Derived >::cols(), Eigen::TriangularBase< Derived >::copyCoeff(), Eigen::TriangularBase< Derived >::innerStride(), Eigen::TriangularBase< Derived >::outerStride(), and Eigen::TriangularBase< Derived >::rows().
evalTo() [1/3]
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
Referenced by Eigen::EigenBase< Derived >::subTo().
evalTo() [2/3]
template<typename Derived > template<typename DenseDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const
evalTo() [3/3]
template<typename Derived > template<typename DenseDerived > void Eigen::TriangularBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
{
  evalToLazy(other.derived());
}
evalToLazy() [1/2]
template<typename Derived > template<typename DenseDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularBase< Derived >::evalToLazy (MatrixBase< DenseDerived > & other) const
Referenced by Eigen::TriangularBase< Derived >::toDenseMatrix().
evalToLazy() [2/2]
template<typename Derived > template<typename DenseDerived > void Eigen::TriangularBase< Derived >::evalToLazy (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
{
  other.derived().resize(this->rows(), this->cols());
  internal::call_triangular_assignment_loop<Derived::Mode,(Derived::Mode&SelfAdjoint)==0 /* SetOpposite */>(other.derived(), derived().nestedExpression());
}
References Eigen::internal::call_triangular_assignment_loop(), Eigen::TriangularView< _MatrixType, _Mode >::cols(), Eigen::DenseBase< Derived >::resize(), Eigen::TriangularView< _MatrixType, _Mode >::rows(), and Eigen::SelfAdjoint.
innerStride()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< Derived >::innerStride () const inline
{ return derived().innerStride(); }
References Eigen::TriangularBase< Derived >::derived().
operator()() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Scalar & Eigen::TriangularBase< Derived >::operator() (Index row, Index col) inline
    {
      check_coordinates(row, col);
      return coeffRef(row,col);
    }
References Eigen::TriangularBase< Derived >::check_coordinates(), Eigen::TriangularBase< Derived >::coeffRef(), col(), and row().
operator()() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC Scalar Eigen::TriangularBase< Derived >::operator() (Index row, Index col) const inline
    {
      check_coordinates(row, col);
      return coeff(row,col);
    }
References Eigen::TriangularBase< Derived >::check_coordinates(), Eigen::TriangularBase< Derived >::coeff(), col(), and row().
outerStride()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< Derived >::outerStride () const inline
{ return derived().outerStride(); }
References Eigen::TriangularBase< Derived >::derived().
resize()
template<typename Derived > void Eigen::TriangularBase< Derived >::resize (Index rows, Index cols) inline
    {
      EIGEN_UNUSED_VARIABLE(rows);
      EIGEN_UNUSED_VARIABLE(cols);
      eigen_assert(rows==this->rows() && cols==this->cols());
    }
References Eigen::TriangularBase< Derived >::cols(), eigen_assert, EIGEN_UNUSED_VARIABLE, and Eigen::TriangularBase< Derived >::rows().
rows()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::TriangularBase< Derived >::rows () const inline
{ return derived().rows(); }
References Eigen::TriangularBase< Derived >::derived().
Referenced by Eigen::TriangularBase< Derived >::check_coordinates(), Eigen::TriangularBase< Derived >::resize(), and Eigen::TriangularBase< Derived >::toDenseMatrix().
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
References Eigen::EigenBase< Derived >::cols(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
toDenseMatrix()
template<typename Derived > EIGEN_DEVICE_FUNC DenseMatrixType Eigen::TriangularBase< Derived >::toDenseMatrix () const inline
    {
      DenseMatrixType res(rows(), cols());
      evalToLazy(res);
      return res;
    }
References Eigen::TriangularBase< Derived >::cols(), Eigen::TriangularBase< Derived >::evalToLazy(), and Eigen::TriangularBase< Derived >::rows().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/TriangularMatrix.h