Prusa Slicer: Slic3r::GUI::DiffViewCtrl Class Reference
Slic3r::GUI::DiffViewCtrl Class Reference
#include <src/slic3r/GUI/UnsavedChangesDialog.hpp>
Classes
struct ItemData
Public Member Functions
DiffViewCtrl (wxWindow *parent, wxSize size)
~DiffViewCtrl () override
void AppendBmpTextColumn (const wxString &label, unsigned model_column, int width, bool set_expander=false)
void AppendToggleColumn_ (const wxString &label, unsigned model_column, int width)
void Rescale (int em=0)
void Append (const std::string &opt_key, Preset::Type type, wxString category_name, wxString group_name, wxString option_name, wxString old_value, wxString mod_value, wxString new_value, const std::string category_icon_name)
void Clear ()
wxString get_short_string (wxString full_string)
bool has_selection ()
void context_menu (wxDataViewEvent &event)
void item_value_changed (wxDataViewEvent &event)
void set_em_unit (int em)
bool has_unselected_options ()
bool has_long_strings ()
bool has_new_value_column ()
std::vector< std::string > options (Preset::Type type, bool selected)
std::vector< std::string > selected_options ()
Public Attributes
DiffModel * model { nullptr }
Private Attributes
bool m_has_long_strings { false }
bool m_empty_selection { false }
int m_em_unit
std::map< wxDataViewItem, ItemData > m_items_map
std::map< unsigned int, int > m_columns_width
Detailed Description
Class Documentation
Slic3r::GUI::DiffViewCtrl::ItemData
struct Slic3r::GUI::DiffViewCtrl::ItemData
Class Members
bool is_long { false }
wxString mod_val
wxString new_val
wxString old_val
string opt_key
wxString opt_name
Type type
Constructor & Destructor Documentation
DiffViewCtrl()
Slic3r::GUI::DiffViewCtrl::DiffViewCtrl (wxWindow * parent, wxSize size)
    : wxDataViewCtrl(parent, wxID_ANY, wxDefaultPosition, size, wxDV_VARIABLE_LINE_HEIGHT | wxDV_ROW_LINES
#ifdef _WIN32
        | wxBORDER_SIMPLE
#endif
    ),
    m_em_unit(em_unit(parent))
{
    wxGetApp().UpdateDVCDarkUI(this);
    model = new DiffModel(parent);
    this->AssociateModel(model);
    model->SetAssociatedControl(this);
    this->Bind(wxEVT_DATAVIEW_ITEM_CONTEXT_MENU, &DiffViewCtrl::context_menu, this);
    this->Bind(wxEVT_DATAVIEW_ITEM_ACTIVATED,    &DiffViewCtrl::context_menu, this);
    this->Bind(wxEVT_DATAVIEW_ITEM_VALUE_CHANGED, &DiffViewCtrl::item_value_changed, this);
}
References context_menu(), item_value_changed(), model, and Slic3r::GUI::DiffModel::SetAssociatedControl().
~DiffViewCtrl()
Slic3r::GUI::DiffViewCtrl::~DiffViewCtrl () inline override
{
        if (model) {
            Clear();
            model->DecRef();
        }
    }
References Clear(), and model.
Member Function Documentation
Append()
void Slic3r::GUI::DiffViewCtrl::Append (const std::string & opt_key, Preset::Type type, wxString category_name, wxString group_name, wxString option_name, wxString old_value, wxString mod_value, wxString new_value, const std::string category_icon_name)
{
    ItemData item_data = { opt_key, option_name, old_value, mod_value, new_value, type };
    wxString old_val = get_short_string(item_data.old_val);
    wxString mod_val = get_short_string(item_data.mod_val);
    wxString new_val = get_short_string(item_data.new_val);
    if (old_val != item_data.old_val || mod_val != item_data.mod_val || new_val != item_data.new_val)
        item_data.is_long = true;
    m_items_map.emplace(model->AddOption(type, category_name, group_name, option_name, old_val, mod_val, new_val, category_icon_name), item_data);
}
References Slic3r::GUI::DiffModel::AddOption(), get_short_string(), Slic3r::GUI::DiffViewCtrl::ItemData::is_long, m_items_map, Slic3r::GUI::DiffViewCtrl::ItemData::mod_val, model, Slic3r::GUI::DiffViewCtrl::ItemData::new_val, and Slic3r::GUI::DiffViewCtrl::ItemData::old_val.
Referenced by Slic3r::GUI::DiffPresetDialog::update_tree(), and Slic3r::GUI::UnsavedChangesDialog::update_tree().
AppendBmpTextColumn()
void Slic3r::GUI::DiffViewCtrl::AppendBmpTextColumn (const wxString & label, unsigned model_column, int width, bool set_expander = false)
{
    m_columns_width.emplace(this->GetColumnCount(), width);
#ifdef __linux__
    wxDataViewIconTextRenderer* rd = new wxDataViewIconTextRenderer();
#ifdef SUPPORTS_MARKUP
    rd->EnableMarkup(true);
#endif
    wxDataViewColumn* column = new wxDataViewColumn(label, rd, model_column, width * m_em_unit, wxALIGN_TOP, wxDATAVIEW_COL_RESIZABLE | wxDATAVIEW_CELL_INERT);
#else
    wxDataViewColumn* column = new wxDataViewColumn(label, new BitmapTextRenderer(true, wxDATAVIEW_CELL_INERT), model_column, width * m_em_unit, wxALIGN_TOP, wxDATAVIEW_COL_RESIZABLE);
#endif //__linux__
    this->AppendColumn(column);
    if (set_expander)
        this->SetExpanderColumn(column);
}
References m_columns_width, and m_em_unit.
Referenced by Slic3r::GUI::UnsavedChangesDialog::build(), and Slic3r::GUI::DiffPresetDialog::create_tree().
AppendToggleColumn_()
void Slic3r::GUI::DiffViewCtrl::AppendToggleColumn_ (const wxString & label, unsigned model_column, int width)
{
    m_columns_width.emplace(this->GetColumnCount(), width);
    AppendToggleColumn(label, model_column, wxDATAVIEW_CELL_ACTIVATABLE, width * m_em_unit);
}
References m_columns_width, and m_em_unit.
Referenced by Slic3r::GUI::UnsavedChangesDialog::build(), and Slic3r::GUI::DiffPresetDialog::create_tree().
Clear()
void Slic3r::GUI::DiffViewCtrl::Clear ()
{
    model->Clear();
    m_items_map.clear();
    m_has_long_strings = false;
}
References Slic3r::GUI::DiffModel::Clear(), m_has_long_strings, m_items_map, and model.
Referenced by ~DiffViewCtrl(), and Slic3r::GUI::DiffPresetDialog::update_tree().
context_menu()
void Slic3r::GUI::DiffViewCtrl::context_menu (wxDataViewEvent & event)
{
    if (!m_has_long_strings)
        return;
    wxDataViewItem item = event.GetItem();
    if (!item) {
        wxPoint mouse_pos = wxGetMousePosition() - this->GetScreenPosition();
        wxDataViewColumn* col = nullptr;
        this->HitTest(mouse_pos, item, col);
        if (!item)
            item = this->GetSelection();
        if (!item)
            return;
    }
    auto it = m_items_map.find(item);
    if (it == m_items_map.end() || !it->second.is_long)
        return;
    const wxString old_value_header = this->GetColumn(DiffModel::colOldValue)->GetTitle();
    const wxString mod_value_header = this->GetColumn(DiffModel::colModValue)->GetTitle();
    const wxString new_value_header = has_new_value_column() ? this->GetColumn(DiffModel::colNewValue)->GetTitle() : "";
    FullCompareDialog(it->second.opt_name, it->second.old_val, it->second.mod_val, it->second.new_val,
                      old_value_header, mod_value_header, new_value_header).ShowModal();
#ifdef __WXOSX__
    wxWindow* parent = this->GetParent();
    if (parent && parent->IsShown()) {
        // if this dialog is shown it have to be Hide and show again to be placed on the very Top of windows
        parent->Hide();
        parent->Show();
    }
#endif // __WXOSX__
}
References col(), Slic3r::GUI::DiffModel::colModValue, Slic3r::GUI::DiffModel::colNewValue, Slic3r::GUI::DiffModel::colOldValue, has_new_value_column(), m_has_long_strings, and m_items_map.
Referenced by DiffViewCtrl().
get_short_string()
wxString Slic3r::GUI::DiffViewCtrl::get_short_string (wxString full_string)
{
    size_t max_len = 30;
    if (full_string.IsEmpty() || full_string.StartsWith("#") ||
        (full_string.Find("\n") == wxNOT_FOUND && full_string.Length() < max_len))
        return full_string;
    m_has_long_strings = true;
    int n_pos = full_string.Find("\n");
    if (n_pos != wxNOT_FOUND && n_pos < (int)max_len)
        max_len = n_pos;
    full_string.Truncate(max_len);
    return full_string + dots;
}
References Slic3r::GUI::dots(), and m_has_long_strings.
Referenced by Append().
has_long_strings()
bool Slic3r::GUI::DiffViewCtrl::has_long_strings () inline
{ return m_has_long_strings; }
References m_has_long_strings.
Referenced by Slic3r::GUI::UnsavedChangesDialog::show_info_line(), and Slic3r::GUI::DiffPresetDialog::update_bottom_info().
has_new_value_column()
bool Slic3r::GUI::DiffViewCtrl::has_new_value_column () inline
{ return this->GetColumnCount() == DiffModel::colMax; }
References Slic3r::GUI::DiffModel::colMax.
Referenced by context_menu(), and Slic3r::GUI::UnsavedChangesDialog::update_tree().
has_selection()
bool Slic3r::GUI::DiffViewCtrl::has_selection () inline
{ return !m_empty_selection; }
References m_empty_selection.
Referenced by Slic3r::GUI::UnsavedChangesDialog::build(), and Slic3r::GUI::DiffPresetDialog::create_buttons().
has_unselected_options()
bool Slic3r::GUI::DiffViewCtrl::has_unselected_options ()
{
    for (auto item : m_items_map)
        if (!model->IsEnabledItem(item.first))
            return true;
    return false;
}
References Slic3r::GUI::DiffModel::IsEnabledItem(), m_items_map, and model.
Referenced by Slic3r::GUI::UnsavedChangesDialog::has_unselected_options().
item_value_changed()
void Slic3r::GUI::DiffViewCtrl::item_value_changed (wxDataViewEvent & event)
{
    if (event.GetColumn() != DiffModel::colToggle)
        return;
    wxDataViewItem item = event.GetItem();
    model->UpdateItemEnabling(item);
    Refresh();
    // update an enabling of the "save/move" buttons
    m_empty_selection = selected_options().empty();
}
References Slic3r::GUI::DiffModel::colToggle, m_empty_selection, model, selected_options(), and Slic3r::GUI::DiffModel::UpdateItemEnabling().
Referenced by DiffViewCtrl().
options()
std::vector< std::string > Slic3r::GUI::DiffViewCtrl::options (Preset::Type type, bool selected)
{
    std::vector<std::string> ret;
    for (auto item : m_items_map) {
        if (item.second.type == type && model->IsEnabledItem(item.first) == selected)
            ret.emplace_back(get_pure_opt_key(item.second.opt_key));
    }
    return ret;
}
References Slic3r::GUI::get_pure_opt_key(), Slic3r::GUI::DiffModel::IsEnabledItem(), m_items_map, and model.
Referenced by Slic3r::GUI::DiffPresetDialog::get_options_to_save(), Slic3r::GUI::UnsavedChangesDialog::get_selected_options(), Slic3r::GUI::DiffPresetDialog::get_selected_options(), Slic3r::GUI::UnsavedChangesDialog::get_unselected_options(), and Slic3r::GUI::DiffPresetDialog::is_save_confirmed().
Rescale()
void Slic3r::GUI::DiffViewCtrl::Rescale (int em = 0)
{
    if (em > 0) {
        for (auto item : m_columns_width)
            GetColumn(item.first)->SetWidth(item.second * em);
        m_em_unit = em;
    }
    model->Rescale();
    Refresh();
}
References m_columns_width, m_em_unit, model, and Slic3r::GUI::DiffModel::Rescale().
Referenced by Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_sys_color_changed(), and Slic3r::GUI::DiffPresetDialog::on_sys_color_changed().
selected_options()
std::vector< std::string > Slic3r::GUI::DiffViewCtrl::selected_options ()
{
    std::vector<std::string> ret;
    for (auto item : m_items_map)
        if (model->IsEnabledItem(item.first))
            ret.emplace_back(get_pure_opt_key(item.second.opt_key));
    return ret;
}
References Slic3r::GUI::get_pure_opt_key(), Slic3r::GUI::DiffModel::IsEnabledItem(), m_items_map, and model.
Referenced by Slic3r::GUI::UnsavedChangesDialog::get_selected_options(), and item_value_changed().
set_em_unit()
void Slic3r::GUI::DiffViewCtrl::set_em_unit (int em) inline
{ m_em_unit = em; }
References m_em_unit.
Member Data Documentation
m_columns_width
std::map<unsigned int, int> Slic3r::GUI::DiffViewCtrl::m_columns_width private
Referenced by AppendBmpTextColumn(), AppendToggleColumn_(), and Rescale().
m_em_unit
int Slic3r::GUI::DiffViewCtrl::m_em_unit private
Referenced by AppendBmpTextColumn(), AppendToggleColumn_(), Rescale(), and set_em_unit().
m_empty_selection
bool Slic3r::GUI::DiffViewCtrl::m_empty_selection { false } private
Referenced by has_selection(), and item_value_changed().
m_has_long_strings
bool Slic3r::GUI::DiffViewCtrl::m_has_long_strings { false } private
Referenced by Clear(), context_menu(), get_short_string(), and has_long_strings().
m_items_map
std::map<wxDataViewItem, ItemData> Slic3r::GUI::DiffViewCtrl::m_items_map private
Referenced by Append(), Clear(), context_menu(), has_unselected_options(), options(), and selected_options().
model
DiffModel* Slic3r::GUI::DiffViewCtrl::model { nullptr }
Referenced by DiffViewCtrl(), ~DiffViewCtrl(), Append(), Clear(), has_unselected_options(), item_value_changed(), options(), Rescale(), selected_options(), Slic3r::GUI::DiffPresetDialog::update_tree(), and Slic3r::GUI::UnsavedChangesDialog::update_tree().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UnsavedChangesDialog.hpp
src/slic3r/GUI/UnsavedChangesDialog.cpp