Prusa Slicer: igl::xml::XMLSerializable Class Reference
igl::xml::XMLSerializable Class Reference abstract
#include <src/libigl/igl/xml/XMLSerializable.h>
Classes
struct XMLSerializationObject
Public Member Functions
virtual IGL_INLINE void InitSerialization ()=0
virtual IGL_INLINE bool PreSerialization () const
virtual IGL_INLINE void PostSerialization () const
virtual IGL_INLINE bool PreDeserialization ()
virtual IGL_INLINE void PostDeserialization ()
IGL_INLINE void Serialize (std::vector< char > &buffer) const
IGL_INLINE void Deserialize (const std::vector< char > &buffer)
IGL_INLINE void Serialize (tinyxml2::XMLDocument *doc, tinyxml2::XMLElement *element) const
IGL_INLINE void Deserialize (const tinyxml2::XMLDocument *doc, const tinyxml2::XMLElement *element)
IGL_INLINE XMLSerializable ()
IGL_INLINE XMLSerializable (const XMLSerializable &obj)
IGL_INLINE ~XMLSerializable ()
IGL_INLINE XMLSerializable & operator= (const XMLSerializable &obj)
template<typename T >
IGL_INLINE void Add (T &obj, std::string name, bool binary=false)
Private Attributes
bool initialized
std::vector< XMLSerializableBase * > objects
Detailed Description
Constructor & Destructor Documentation
XMLSerializable() [1/2]
IGL_INLINE igl::xml::XMLSerializable::XMLSerializable ()
    {
      initialized = false;
    }
References initialized.
XMLSerializable() [2/2]
IGL_INLINE igl::xml::XMLSerializable::XMLSerializable (const XMLSerializable & obj)
    {
      initialized = false;
      objects.clear();
    }
References initialized, and objects.
~XMLSerializable()
IGL_INLINE igl::xml::XMLSerializable::~XMLSerializable ()
    {
      initialized = false;
      objects.clear();
    }
References initialized, and objects.
Member Function Documentation
Add()
template<typename T > IGL_INLINE void igl::xml::XMLSerializable::Add (T & obj, std::string name, bool binary = false)
    {
      XMLSerializationObject<T>* object = new XMLSerializationObject<T>();
      object->Binary = binary;
      object->Name = name;
      object->Object = &obj;
      objects.push_back(object);
    }
References binary, and objects.
Deserialize() [1/2]
IGL_INLINE void igl::xml::XMLSerializable::Deserialize (const std::vector< char > & buffer) virtual
Implements igl::xml::XMLSerializableBase.
    {
      if(this->PreDeserialization())
      {
        if(initialized == false)
        {
          objects.clear();
          (const_cast<XMLSerializable*>(this))->InitSerialization();
          initialized = true;
        }
        for(unsigned int i=0;i<objects.size();i++)
          objects[i]->Deserialize(buffer);
        this->PostDeserialization();
      }
    }
References Deserialize(), initialized, objects, PostDeserialization(), and PreDeserialization().
Referenced by Deserialize(), and Deserialize().
Deserialize() [2/2]
IGL_INLINE void igl::xml::XMLSerializable::Deserialize (const tinyxml2::XMLDocument * doc, const tinyxml2::XMLElement * element) virtual
Implements igl::xml::XMLSerializableBase.
    {
      if(this->PreDeserialization())
      {
        if(initialized == false)
        {
          objects.clear();
          (const_cast<XMLSerializable*>(this))->InitSerialization();
          initialized = true;
        }
        for(unsigned int i=0;i<objects.size();i++)
          objects[i]->Deserialize(doc,element);
        this->PostDeserialization();
      }
    }
References Deserialize(), initialized, objects, PostDeserialization(), and PreDeserialization().
InitSerialization()
virtual IGL_INLINE void igl::xml::XMLSerializable::InitSerialization () pure virtual
operator=()
IGL_INLINE XMLSerializable & igl::xml::XMLSerializable::operator= (const XMLSerializable & obj)
    {
      if(this != &obj)
      {
        if(initialized)
        {
          initialized = false;
          objects.clear();
        }
      }
      return *this;
    }
References initialized, and objects.
PostDeserialization()
IGL_INLINE void igl::xml::XMLSerializable::PostDeserialization () virtual
    {
    }
Referenced by Deserialize(), and Deserialize().
PostSerialization()
IGL_INLINE void igl::xml::XMLSerializable::PostSerialization () const virtual
    {
    }
Referenced by Serialize(), and Serialize().
PreDeserialization()
IGL_INLINE bool igl::xml::XMLSerializable::PreDeserialization () virtual
    {
      return true;
    }
Referenced by Deserialize(), and Deserialize().
PreSerialization()
IGL_INLINE bool igl::xml::XMLSerializable::PreSerialization () const virtual
    {
      return true;
    }
Referenced by Serialize(), and Serialize().
Serialize() [1/2]
IGL_INLINE void igl::xml::XMLSerializable::Serialize (std::vector< char > & buffer) const virtual
Implements igl::xml::XMLSerializableBase.
    {
      if(this->PreSerialization())
      {
        if(initialized == false)
        {
          objects.clear();
          (const_cast<XMLSerializable*>(this))->InitSerialization();
          initialized = true;
        }
        for(unsigned int i=0;i<objects.size();i++)
          objects[i]->Serialize(buffer);
        this->PostSerialization();
      }
    }
References initialized, objects, PostSerialization(), PreSerialization(), and Serialize().
Referenced by Serialize(), and Serialize().
Serialize() [2/2]
IGL_INLINE void igl::xml::XMLSerializable::Serialize (tinyxml2::XMLDocument * doc, tinyxml2::XMLElement * element) const virtual
Implements igl::xml::XMLSerializableBase.
    {
      if(this->PreSerialization())
      {
        if(initialized == false)
        {
          objects.clear();
          (const_cast<XMLSerializable*>(this))->InitSerialization();
          initialized = true;
        }
        for(unsigned int i=0;i<objects.size();i++)
          objects[i]->Serialize(doc,element);
        this->PostSerialization();
      }
    }
References initialized, objects, PostSerialization(), PreSerialization(), and Serialize().
Member Data Documentation
initialized
bool igl::xml::XMLSerializable::initialized mutable private
Referenced by XMLSerializable(), XMLSerializable(), ~XMLSerializable(), Deserialize(), Deserialize(), operator=(), Serialize(), and Serialize().
objects
std::vector<XMLSerializableBase*> igl::xml::XMLSerializable::objects mutable private
Referenced by XMLSerializable(), ~XMLSerializable(), Add(), Deserialize(), Deserialize(), operator=(), Serialize(), and Serialize().
The documentation for this class was generated from the following file:
src/libigl/igl/xml/XMLSerializable.h