Prusa Slicer: Eigen::PermutationBase< Derived > Class Template Reference
Eigen::PermutationBase< Derived > Class Template Reference
Base class for permutations.
#include <src/eigen/Eigen/src/Core/PermutationMatrix.h>
Public Types
enum {
Flags = Traits::Flags , RowsAtCompileTime = Traits::RowsAtCompileTime , ColsAtCompileTime = Traits::ColsAtCompileTime , MaxRowsAtCompileTime = Traits::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = Traits::MaxColsAtCompileTime
}
typedef Traits::IndicesType IndicesType
typedef Traits::StorageIndex StorageIndex
typedef Matrix< StorageIndex, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime > DenseMatrixType
typedef PermutationMatrix< IndicesType::SizeAtCompileTime, IndicesType::MaxSizeAtCompileTime, StorageIndex > PlainPermutationType
typedef PlainPermutationType PlainObject
typedef Inverse< Derived > InverseReturnType
typedef void Scalar
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
template<typename OtherDerived >
Derived & operator= (const PermutationBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const TranspositionsBase< OtherDerived > &tr)
Derived & operator= (const PermutationBase &other)
Index rows () const
Index cols () const
Index size () const
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &other) const
DenseMatrixType toDenseMatrix () const
const IndicesType & indices () const
IndicesType & indices ()
void resize (Index newSize)
void setIdentity ()
void setIdentity (Index newSize)
Derived & applyTranspositionOnTheLeft (Index i, Index j)
Derived & applyTranspositionOnTheRight (Index i, Index j)
InverseReturnType inverse () const
InverseReturnType transpose () const
template<typename Other >
PlainPermutationType operator* (const PermutationBase< Other > &other) const
template<typename Other >
PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > &other) const
Index determinant () const
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
template<typename OtherDerived >
void assignTranspose (const PermutationBase< OtherDerived > &other)
template<typename Lhs , typename Rhs >
void assignProduct (const Lhs &lhs, const Rhs &rhs)
Private Types
typedef internal::traits< Derived > Traits
typedef EigenBase< Derived > Base
Friends
template<typename Other >
PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > &other, const PermutationBase &perm)
Detailed Description
template<typename Derived>
class Eigen::PermutationBase< Derived >
Base class for permutations.
Template Parameters
Derived the derived class
This class is the base class for all expressions representing a permutation matrix, internally stored as a vector of integers. The convention followed here is that if is a permutation, the corresponding permutation matrix is such that if is the canonical basis, we have:
This convention ensures that for any two permutations , we have:
Permutation matrices are square and invertible.
Notice that in addition to the member functions and operators listed here, there also are non-member operator* to multiply any kind of permutation object with any kind of matrix expression (MatrixBase) on either side.
See also
class PermutationMatrix, class PermutationWrapper
Member Typedef Documentation
Base
template<typename Derived > typedef EigenBase<Derived> Eigen::PermutationBase< Derived >::Base private
DenseMatrixType
template<typename Derived > typedef Matrix<StorageIndex,RowsAtCompileTime,ColsAtCompileTime,0,MaxRowsAtCompileTime,MaxColsAtCompileTime> Eigen::PermutationBase< Derived >::DenseMatrixType
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
IndicesType
template<typename Derived > typedef Traits::IndicesType Eigen::PermutationBase< Derived >::IndicesType
InverseReturnType
template<typename Derived > typedef Inverse<Derived> Eigen::PermutationBase< Derived >::InverseReturnType
PlainObject
template<typename Derived > typedef PlainPermutationType Eigen::PermutationBase< Derived >::PlainObject
PlainPermutationType
template<typename Derived > typedef PermutationMatrix<IndicesType::SizeAtCompileTime,IndicesType::MaxSizeAtCompileTime,StorageIndex> Eigen::PermutationBase< Derived >::PlainPermutationType
Scalar
template<typename Derived > typedef void Eigen::PermutationBase< Derived >::Scalar
StorageIndex
template<typename Derived > typedef Traits::StorageIndex Eigen::PermutationBase< Derived >::StorageIndex
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::EigenBase< Derived >::StorageKind inherited
Traits
template<typename Derived > typedef internal::traits<Derived> Eigen::PermutationBase< Derived >::Traits private
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
Flags
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
         {
      Flags = Traits::Flags,
      RowsAtCompileTime = Traits::RowsAtCompileTime,
      ColsAtCompileTime = Traits::ColsAtCompileTime,
      MaxRowsAtCompileTime = Traits::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = Traits::MaxColsAtCompileTime
    };
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
applyTranspositionOnTheLeft()
template<typename Derived > Derived & Eigen::PermutationBase< Derived >::applyTranspositionOnTheLeft (Index i, Index j) inline
Multiplies *this by the transposition on the left.
Returns
a reference to *this.
Warning
This is much slower than applyTranspositionOnTheRight(Index,Index): this has linear complexity and requires a lot of branching.
See also
applyTranspositionOnTheRight(Index,Index)
    {
      eigen_assert(i>=0 && j>=0 && i<size() && j<size());
      for(Index k = 0; k < size(); ++k)
      {
        if(indices().coeff(k) == i) indices().coeffRef(k) = StorageIndex(j);
        else if(indices().coeff(k) == j) indices().coeffRef(k) = StorageIndex(i);
      }
      return derived();
    }
References Eigen::PermutationBase< Derived >::derived(), eigen_assert, Eigen::PermutationBase< Derived >::indices(), and Eigen::PermutationBase< Derived >::size().
applyTranspositionOnTheRight()
template<typename Derived > Derived & Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight (Index i, Index j) inline
Multiplies *this by the transposition on the right.
Returns
a reference to *this.
This is a fast operation, it only consists in swapping two indices.
See also
applyTranspositionOnTheLeft(Index,Index)
    {
      eigen_assert(i>=0 && j>=0 && i<size() && j<size());
      std::swap(indices().coeffRef(i), indices().coeffRef(j));
      return derived();
    }
References Eigen::PermutationBase< Derived >::derived(), eigen_assert, Eigen::PermutationBase< Derived >::indices(), and Eigen::PermutationBase< Derived >::size().
Referenced by Eigen::PermutationBase< Derived >::operator=().
assignProduct()
template<typename Derived > template<typename Lhs , typename Rhs > void Eigen::PermutationBase< Derived >::assignProduct (const Lhs & lhs, const Rhs & rhs) inline protected
    {
      eigen_assert(lhs.cols() == rhs.rows());
      for (Index i=0; i<rows();++i) indices().coeffRef(i) = lhs.indices().coeff(rhs.indices().coeff(i));
    }
References eigen_assert, Eigen::PermutationBase< Derived >::indices(), and Eigen::PermutationBase< Derived >::rows().
Referenced by Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::PermutationMatrix().
assignTranspose()
template<typename Derived > template<typename OtherDerived > void Eigen::PermutationBase< Derived >::assignTranspose (const PermutationBase< OtherDerived > & other) inline protected
    {
      for (Index i=0; i<rows();++i) indices().coeffRef(other.indices().coeff(i)) = i;
    }
References Eigen::PermutationBase< Derived >::indices(), and Eigen::PermutationBase< Derived >::rows().
cols()
template<typename Derived > Index Eigen::PermutationBase< Derived >::cols () const inline
Returns
the number of columns
{ return Index(indices().size()); }
References Eigen::PermutationBase< Derived >::indices(), and Eigen::PermutationBase< Derived >::size().
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::derived () inline
Returns
a reference to the derived object
{ return *static_cast<Derived*>(this); }
Referenced by Eigen::PermutationBase< Derived >::applyTranspositionOnTheLeft(), Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight(), Eigen::PermutationBase< Derived >::indices(), Eigen::PermutationBase< Derived >::indices(), Eigen::PermutationBase< Derived >::inverse(), Eigen::operator*(), Eigen::PermutationBase< Derived >::operator*(), Eigen::operator*(), Eigen::operator*(), Eigen::operator*(), Eigen::PermutationBase< Derived >::operator=(), Eigen::Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >, _PacketAccess >::operator=(), Eigen::PermutationBase< Derived >::operator=(), Eigen::PermutationBase< Derived >::operator=(), Eigen::PermutationBase< Derived >::toDenseMatrix(), and Eigen::PermutationBase< Derived >::transpose().
derived() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::derived () const inline
Returns
a const reference to the derived object
{ return *static_cast<const Derived*>(this); }
determinant()
template<typename Derived > Index Eigen::PermutationBase< Derived >::determinant () const inline
Returns
the determinant of the permutation matrix, which is either 1 or -1 depending on the parity of the permutation.
This function is O(n) procedure allocating a buffer of n booleans.
    {
      Index res = 1;
      Index n = size();
      Matrix<bool,RowsAtCompileTime,1,0,MaxRowsAtCompileTime> mask(n);
      mask.fill(false);
      Index r = 0;
      while(r < n)
      {
        // search for the next seed
        while(r<n && mask[r]) r++;
        if(r>=n)
          break;
        // we got one, let's follow it until we are back to the seed
        Index k0 = r++;
        mask.coeffRef(k0) = true;
        for(Index k=indices().coeff(k0); k!=k0; k=indices().coeff(k))
        {
          mask.coeffRef(k) = true;
          res = -res;
        }
      }
      return res;
    }
References Eigen::PermutationBase< Derived >::size().
evalTo() [1/2]
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
Referenced by Eigen::EigenBase< Derived >::subTo().
evalTo() [2/2]
template<typename Derived > template<typename DenseDerived > void Eigen::PermutationBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const inline
    {
      other.setZero();
      for (Index i=0; i<rows(); ++i)
        other.coeffRef(indices().coeff(i),i) = typename DenseDerived::Scalar(1);
    }
References Eigen::PermutationBase< Derived >::indices(), Eigen::PermutationBase< Derived >::rows(), and Eigen::DenseBase< Derived >::setZero().
indices() [1/2]
template<typename Derived > IndicesType & Eigen::PermutationBase< Derived >::indices () inline
Returns
a reference to the stored array representing the permutation.
{ return derived().indices(); }
References Eigen::PermutationBase< Derived >::derived().
indices() [2/2]
template<typename Derived > const IndicesType & Eigen::PermutationBase< Derived >::indices () const inline
const version of indices().
{ return derived().indices(); }
References Eigen::PermutationBase< Derived >::derived().
Referenced by Eigen::PermutationBase< Derived >::applyTranspositionOnTheLeft(), Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight(), Eigen::PermutationBase< Derived >::assignProduct(), Eigen::PermutationBase< Derived >::assignTranspose(), Eigen::PermutationBase< Derived >::cols(), Eigen::PermutationBase< Derived >::evalTo(), Eigen::PermutationBase< Derived >::operator=(), Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::operator=(), Eigen::PermutationBase< Derived >::operator=(), Eigen::PermutationBase< Derived >::resize(), Eigen::PermutationBase< Derived >::rows(), Eigen::PermutationBase< Derived >::setIdentity(), and Eigen::PermutationBase< Derived >::size().
inverse()
template<typename Derived > InverseReturnType Eigen::PermutationBase< Derived >::inverse () const inline
Returns
the inverse permutation matrix.
Note
\blank \note_try_to_help_rvo
    { return InverseReturnType(derived()); }
References Eigen::PermutationBase< Derived >::derived().
Referenced by Eigen::SparseLU< _MatrixType, _OrderingType >::_solve_impl(), and Eigen::FullPivLU< _MatrixType >::_solve_impl_transposed().
operator*() [1/2]
template<typename Derived > template<typename Other > PlainPermutationType Eigen::PermutationBase< Derived >::operator* (const InverseImpl< Other, PermutationStorage > & other) const inline
Returns
the product of a permutation with another inverse permutation.
Note
\blank \note_try_to_help_rvo
    { return PlainPermutationType(internal::PermPermProduct, *this, other.eval()); }
References Eigen::internal::PermPermProduct.
operator*() [2/2]
template<typename Derived > template<typename Other > PlainPermutationType Eigen::PermutationBase< Derived >::operator* (const PermutationBase< Other > & other) const inline
Returns
the product permutation matrix.
Note
\blank \note_try_to_help_rvo
    { return PlainPermutationType(internal::PermPermProduct, derived(), other.derived()); }
References Eigen::PermutationBase< Derived >::derived(), and Eigen::internal::PermPermProduct.
operator=() [1/3]
template<typename Derived > Derived & Eigen::PermutationBase< Derived >::operator= (const PermutationBase< Derived > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
    {
      indices() = other.indices();
      return derived();
    }
References Eigen::PermutationBase< Derived >::derived(), and Eigen::PermutationBase< Derived >::indices().
operator=() [2/3]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::PermutationBase< Derived >::operator= (const PermutationBase< OtherDerived > & other) inline
Copies the other permutation into *this
    {
      indices() = other.indices();
      return derived();
    }
References Eigen::PermutationBase< Derived >::derived(), and Eigen::PermutationBase< Derived >::indices().
Referenced by Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::operator=().
operator=() [3/3]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::PermutationBase< Derived >::operator= (const TranspositionsBase< OtherDerived > & tr) inline
Assignment from the Transpositions tr
    {
      setIdentity(tr.size());
      for(Index k=size()-1; k>=0; --k)
        applyTranspositionOnTheRight(k,tr.coeff(k));
      return derived();
    }
References Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight(), Eigen::TranspositionsBase< Derived >::coeff(), Eigen::PermutationBase< Derived >::derived(), Eigen::PermutationBase< Derived >::setIdentity(), Eigen::PermutationBase< Derived >::size(), and Eigen::TranspositionsBase< Derived >::size().
resize()
template<typename Derived > void Eigen::PermutationBase< Derived >::resize (Index newSize) inline
Resizes to given size.
    {
      indices().resize(newSize);
    }
References Eigen::PermutationBase< Derived >::indices().
Referenced by Eigen::internal::minimum_degree_ordering(), Eigen::NaturalOrdering< StorageIndex >::operator()(), Eigen::MetisOrdering< StorageIndex >::operator()(), Eigen::COLAMDOrdering< StorageIndex >::operator()(), and Eigen::PermutationBase< Derived >::setIdentity().
rows()
template<typename Derived > Index Eigen::PermutationBase< Derived >::rows () const inline
Returns
the number of rows
{ return Index(indices().size()); }
References Eigen::PermutationBase< Derived >::indices(), and Eigen::PermutationBase< Derived >::size().
Referenced by Eigen::PermutationBase< Derived >::assignProduct(), Eigen::PermutationBase< Derived >::assignTranspose(), and Eigen::PermutationBase< Derived >::evalTo().
setIdentity() [1/2]
template<typename Derived > void Eigen::PermutationBase< Derived >::setIdentity () inline
Sets *this to be the identity permutation matrix
    {
      StorageIndex n = StorageIndex(size());
      for(StorageIndex i = 0; i < n; ++i)
        indices().coeffRef(i) = i;
    }
References Eigen::PermutationBase< Derived >::indices(), and Eigen::PermutationBase< Derived >::size().
Referenced by Eigen::PermutationBase< Derived >::operator=(), and Eigen::PermutationBase< Derived >::setIdentity().
setIdentity() [2/2]
template<typename Derived > void Eigen::PermutationBase< Derived >::setIdentity (Index newSize) inline
Sets *this to be the identity permutation matrix of given size.
    {
      resize(newSize);
      setIdentity();
    }
References Eigen::PermutationBase< Derived >::resize(), and Eigen::PermutationBase< Derived >::setIdentity().
size()
template<typename Derived > Index Eigen::PermutationBase< Derived >::size () const inline
Returns
the size of a side of the respective square matrix, i.e., the number of indices
{ return Index(indices().size()); }
References Eigen::PermutationBase< Derived >::indices(), and Eigen::PermutationBase< Derived >::size().
Referenced by Eigen::SimplicialCholeskyBase< Derived >::_solve_impl(), Eigen::SparseQR< _MatrixType, _OrderingType >::_solve_impl(), Eigen::PermutationBase< Derived >::applyTranspositionOnTheLeft(), Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight(), Eigen::PermutationBase< Derived >::cols(), Eigen::PermutationBase< Derived >::determinant(), Eigen::SimplicialCholeskyBase< Derived >::dumpMemory(), Eigen::SimplicialCholeskyBase< Derived >::factorize(), Eigen::PermutationBase< Derived >::operator=(), Eigen::PermutationBase< Derived >::rows(), Eigen::PermutationBase< Derived >::setIdentity(), and Eigen::PermutationBase< Derived >::size().
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
toDenseMatrix()
template<typename Derived > DenseMatrixType Eigen::PermutationBase< Derived >::toDenseMatrix () const inline
Returns
a Matrix object initialized from this permutation matrix. Notice that it is inefficient to return this Matrix object by value. For efficiency, favor using the Matrix constructor taking EigenBase objects.
    {
      return derived();
    }
References Eigen::PermutationBase< Derived >::derived().
transpose()
template<typename Derived > InverseReturnType Eigen::PermutationBase< Derived >::transpose () const inline
Returns
the tranpose permutation matrix.
Note
\blank \note_try_to_help_rvo
    { return InverseReturnType(derived()); }
References Eigen::PermutationBase< Derived >::derived().
Referenced by Eigen::PartialPivLU< _MatrixType >::_solve_impl_transposed(), and Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run().
Friends And Related Symbol Documentation
operator*
template<typename Derived > template<typename Other > PlainPermutationType operator* (const InverseImpl< Other, PermutationStorage > & other, const PermutationBase< Derived > & perm) friend
Returns
the product of an inverse permutation with another permutation.
Note
\blank \note_try_to_help_rvo
    { return PlainPermutationType(internal::PermPermProduct, other.eval(), perm); }
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/PermutationMatrix.h