Prusa Slicer: Slic3r::GUI::BoostThreadWorker::WorkerMessage Class Reference
Slic3r::GUI::BoostThreadWorker::WorkerMessage Class Reference
Public Types
enum MsgType { Empty , Status , Finalize , MainThreadCall }
Public Member Functions
WorkerMessage ()=default
WorkerMessage (int s, std::string txt)
WorkerMessage (JobEntry &&entry)
WorkerMessage (MainThreadCallData fn)
int get_type () const
void deliver (BoostThreadWorker &runner)
Private Attributes
boost::variant< EmptyMessage, StatusInfo, JobEntry, MainThreadCallData > m_data
Detailed Description
Member Enumeration Documentation
MsgType
enum Slic3r::GUI::BoostThreadWorker::WorkerMessage::MsgType
Enumerator
Empty
Status
Finalize
MainThreadCall
{ Empty, Status, Finalize, MainThreadCall };
Constructor & Destructor Documentation
WorkerMessage() [1/4]
Slic3r::GUI::BoostThreadWorker::WorkerMessage::WorkerMessage () default
WorkerMessage() [2/4]
Slic3r::GUI::BoostThreadWorker::WorkerMessage::WorkerMessage (int s, std::string txt) inline
            : m_data{StatusInfo{s, std::move(txt)}}
        {}
WorkerMessage() [3/4]
Slic3r::GUI::BoostThreadWorker::WorkerMessage::WorkerMessage (JobEntry && entry) inline
: m_data{std::move(entry)} {}
WorkerMessage() [4/4]
Slic3r::GUI::BoostThreadWorker::WorkerMessage::WorkerMessage (MainThreadCallData fn) inline
: m_data{std::move(fn)} {}
Member Function Documentation
deliver()
void Slic3r::GUI::BoostThreadWorker::WorkerMessage::deliver (BoostThreadWorker & runner)
{
    switch(MsgType(get_type())) {
    case Empty: break;
    case Status: {
        auto info = boost::get<StatusInfo>(m_data);
        if (runner.get_pri()) {
            runner.get_pri()->set_progress(info.status);
            runner.get_pri()->set_status_text(info.msg.c_str());
        }
        break;
    }
    case Finalize: {
        auto& entry = boost::get<JobEntry>(m_data);
        entry.job->finalize(entry.canceled, entry.eptr);
        // Unhandled exceptions are rethrown without mercy.
        if (entry.eptr)
            std::rethrow_exception(entry.eptr);
        break;
    }
    case MainThreadCall: {
        auto &calldata = boost::get<MainThreadCallData >(m_data);
        calldata.fn();
        calldata.promise.set_value();
        break;
    }
    }
}
References Empty, Finalize, Slic3r::GUI::BoostThreadWorker::get_pri(), get_type(), m_data, MainThreadCall, Slic3r::ProgressIndicator::set_progress(), Slic3r::ProgressIndicator::set_status_text(), and Status.
get_type()
int Slic3r::GUI::BoostThreadWorker::WorkerMessage::get_type () const inline
{ return m_data.which(); }
References m_data.
Referenced by deliver().
Member Data Documentation
m_data
boost::variant<EmptyMessage, StatusInfo, JobEntry, MainThreadCallData> Slic3r::GUI::BoostThreadWorker::WorkerMessage::m_data private
Referenced by deliver(), and get_type().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/BoostThreadWorker.hpp
src/slic3r/GUI/Jobs/BoostThreadWorker.cpp