Prusa Slicer: igl::CombLine< DerivedV, DerivedF > Class Template Reference
igl::CombLine< DerivedV, DerivedF > Class Template Reference
Public Member Functions
CombLine (const Eigen::PlainObjectBase< DerivedV > &_V, const Eigen::PlainObjectBase< DerivedF > &_F, const Eigen::PlainObjectBase< DerivedV > &_PD1)
void comb (Eigen::PlainObjectBase< DerivedV > &PD1out)
Public Attributes
const Eigen::PlainObjectBase< DerivedV > & V
const Eigen::PlainObjectBase< DerivedF > & F
const Eigen::PlainObjectBase< DerivedV > & PD1
DerivedV N
Static Private Member Functions
static double Sign (double a)
static Eigen::Matrix< typename DerivedV::Scalar, 3, 1 > K_PI_line (const Eigen::Matrix< typename DerivedV::Scalar, 3, 1 > &a, const Eigen::Matrix< typename DerivedV::Scalar, 3, 1 > &b)
Private Attributes
DerivedF TT
DerivedF TTi
Detailed Description
template<typename DerivedV, typename DerivedF>
class igl::CombLine< DerivedV, DerivedF >
Constructor & Destructor Documentation
CombLine()
template<typename DerivedV , typename DerivedF > igl::CombLine< DerivedV, DerivedF >::CombLine (const Eigen::PlainObjectBase< DerivedV > & _V, const Eigen::PlainObjectBase< DerivedF > & _F, const Eigen::PlainObjectBase< DerivedV > & _PD1) inline
                                                               :
        V(_V),
        F(_F),
        PD1(_PD1)
    {
        igl::per_face_normals(V,F,N);
        igl::triangle_triangle_adjacency(F,TT,TTi);
    }
References igl::CombLine< DerivedV, DerivedF >::F, igl::CombLine< DerivedV, DerivedF >::N, igl::per_face_normals(), igl::triangle_triangle_adjacency(), igl::CombLine< DerivedV, DerivedF >::TT, igl::CombLine< DerivedV, DerivedF >::TTi, and igl::CombLine< DerivedV, DerivedF >::V.
Member Function Documentation
comb()
template<typename DerivedV , typename DerivedF > void igl::CombLine< DerivedV, DerivedF >::comb (Eigen::PlainObjectBase< DerivedV > & PD1out) inline
    {
        PD1out.setZero(F.rows(),3);PD1out<<PD1;
        Eigen::VectorXi mark = Eigen::VectorXi::Constant(F.rows(),false);
        std::deque<int> d;
        d.push_back(0);
        mark(0) = true;
        while (!d.empty())
        {
            int f0 = d.at(0);
            d.pop_front();
            for (int k=0; k<3; k++)
            {
                int f1 = TT(f0,k);
                if (f1==-1) continue;
                if (mark(f1)) continue;
                Eigen::Matrix<typename DerivedV::Scalar, 3, 1> dir0  = PD1out.row(f0);
                Eigen::Matrix<typename DerivedV::Scalar, 3, 1> dir1  = PD1out.row(f1);
                Eigen::Matrix<typename DerivedV::Scalar, 3, 1> n0    = N.row(f0);
                Eigen::Matrix<typename DerivedV::Scalar, 3, 1> n1    = N.row(f1);
                Eigen::Matrix<typename DerivedV::Scalar, 3, 1> dir0Rot = igl::rotation_matrix_from_directions(n0, n1)*dir0;
                dir0Rot.normalize();
                Eigen::Matrix<typename DerivedV::Scalar, 3, 1> targD   = K_PI_line(dir1,dir0Rot);
                PD1out.row(f1)  = targD;
                //PD2out.row(f1)  = n1.cross(targD).normalized();
                mark(f1) = true;
                d.push_back(f1);
            }
        }
        // everything should be marked
        for (int i=0; i<F.rows(); i++)
        {
            assert(mark(i));
        }
    }
References igl::CombLine< DerivedV, DerivedF >::F, igl::CombLine< DerivedV, DerivedF >::K_PI_line(), igl::CombLine< DerivedV, DerivedF >::N, igl::CombLine< DerivedV, DerivedF >::PD1, igl::rotation_matrix_from_directions(), Eigen::PlainObjectBase< Derived >::rows(), Eigen::PlainObjectBase< Derived >::setZero(), and igl::CombLine< DerivedV, DerivedF >::TT.
Referenced by igl::comb_line_field().
K_PI_line()
template<typename DerivedV , typename DerivedF > static Eigen::Matrix< typename DerivedV::Scalar, 3, 1 > igl::CombLine< DerivedV, DerivedF >::K_PI_line (const Eigen::Matrix< typename DerivedV::Scalar, 3, 1 > & a, const Eigen::Matrix< typename DerivedV::Scalar, 3, 1 > & b) inline static private
    {
        typename DerivedV::Scalar scorea = a.dot(b);
        if (scorea<0)
            return -a;
        else
            return a;
    }
Referenced by igl::CombLine< DerivedV, DerivedF >::comb().
Sign()
template<typename DerivedV , typename DerivedF > static double igl::CombLine< DerivedV, DerivedF >::Sign (double a) inline static private
{return (double)((a>0)?+1:-1);}
Member Data Documentation
F
template<typename DerivedV , typename DerivedF > const Eigen::PlainObjectBase<DerivedF>& igl::CombLine< DerivedV, DerivedF >::F
Referenced by igl::CombLine< DerivedV, DerivedF >::CombLine(), and igl::CombLine< DerivedV, DerivedF >::comb().
N
template<typename DerivedV , typename DerivedF > DerivedV igl::CombLine< DerivedV, DerivedF >::N
Referenced by igl::CombLine< DerivedV, DerivedF >::CombLine(), and igl::CombLine< DerivedV, DerivedF >::comb().
PD1
template<typename DerivedV , typename DerivedF > const Eigen::PlainObjectBase<DerivedV>& igl::CombLine< DerivedV, DerivedF >::PD1
Referenced by igl::CombLine< DerivedV, DerivedF >::comb().
TT
template<typename DerivedV , typename DerivedF > DerivedF igl::CombLine< DerivedV, DerivedF >::TT private
Referenced by igl::CombLine< DerivedV, DerivedF >::CombLine(), and igl::CombLine< DerivedV, DerivedF >::comb().
TTi
template<typename DerivedV , typename DerivedF > DerivedF igl::CombLine< DerivedV, DerivedF >::TTi private
Referenced by igl::CombLine< DerivedV, DerivedF >::CombLine().
V
template<typename DerivedV , typename DerivedF > const Eigen::PlainObjectBase<DerivedV>& igl::CombLine< DerivedV, DerivedF >::V
Referenced by igl::CombLine< DerivedV, DerivedF >::CombLine().
The documentation for this class was generated from the following file:
src/libigl/igl/comb_line_field.cpp