Prusa Slicer: Slic3r::GUI::ArrangeJob Class Reference
Slic3r::GUI::ArrangeJob Class Reference
#include <src/slic3r/GUI/Jobs/ArrangeJob.hpp>
Public Types
enum Mode { Full , SelectionOnly }
Public Member Functions
void prepare ()
void process (Ctl &ctl) override
ArrangeJob (Mode mode=Full)
int status_range () const
void finalize (bool canceled, std::exception_ptr &e) override
Private Types
using ArrangePolygon = arrangement::ArrangePolygon
using ArrangePolygons = arrangement::ArrangePolygons
Private Member Functions
void clear_input ()
void prepare_all ()
void prepare_selected ()
ArrangePolygon get_arrange_poly_ (ModelInstance *mi)
Private Attributes
ArrangePolygons m_selected
ArrangePolygons m_unselected
ArrangePolygons m_unprintable
std::vector< ModelInstance * > m_unarranged
arrangement::ArrangeBed m_bed
coord_t m_min_bed_inset = 0.
Plater * m_plater
bool m_selection_only = false
Detailed Description
Member Typedef Documentation
ArrangePolygon
using Slic3r::GUI::ArrangeJob::ArrangePolygon = arrangement::ArrangePolygon private
ArrangePolygons
using Slic3r::GUI::ArrangeJob::ArrangePolygons = arrangement::ArrangePolygons private
Member Enumeration Documentation
Mode
enum Slic3r::GUI::ArrangeJob::Mode
Enumerator
Full
SelectionOnly
{ Full, SelectionOnly };
Constructor & Destructor Documentation
ArrangeJob()
Slic3r::GUI::ArrangeJob::ArrangeJob (Mode mode = Full)
    : m_plater{wxGetApp().plater()},
      m_selection_only{mode == Mode::SelectionOnly}
{}
Member Function Documentation
clear_input()
void Slic3r::GUI::ArrangeJob::clear_input () private
{
    const Model &model = m_plater->model();
    size_t count = 0, cunprint = 0; // To know how much space to reserve
    for (auto obj : model.objects)
        for (auto mi : obj->instances)
            mi->printable ? count++ : cunprint++;
    m_selected.clear();
    m_unselected.clear();
    m_unprintable.clear();
    m_unarranged.clear();
    m_selected.reserve(count + 1 /* for optional wti */);
    m_unselected.reserve(count + 1 /* for optional wti */);
    m_unprintable.reserve(cunprint /* for optional wti */);
}
References m_plater, m_selected, m_unarranged, m_unprintable, m_unselected, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by prepare_all(), and prepare_selected().
finalize()
void Slic3r::GUI::ArrangeJob::finalize (bool canceled, std::exception_ptr & e) override virtual
Reimplemented from Slic3r::GUI::Job.
{
    try {
        if (eptr)
            std::rethrow_exception(eptr);
    } catch (libnest2d::GeometryException &) {
        show_error(m_plater, _(L("Could not arrange model objects! "
                                 "Some geometries may be invalid.")));
        eptr = nullptr;
    } catch(...) {
        eptr = std::current_exception();
    }
    if (canceled || eptr)
        return;
    // Unprintable items go to the last virtual bed
    int beds = 0;
    // Apply the arrange result to all selected objects
    for (ArrangePolygon &ap : m_selected) {
        beds = std::max(ap.bed_idx, beds);
        ap.apply();
    }
    // Get the virtual beds from the unselected items
    for (ArrangePolygon &ap : m_unselected)
        beds = std::max(ap.bed_idx, beds);
    // Move the unprintable items to the last virtual bed.
    for (ArrangePolygon &ap : m_unprintable) {
        if (ap.bed_idx >= 0)
            ap.bed_idx += beds + 1;
        ap.apply();
    }
    m_plater->update(static_cast<unsigned int>(
        Plater::UpdateParams::FORCE_FULL_SCREEN_REFRESH));
    wxGetApp().obj_manipul()->set_dirty();
    if (!m_unarranged.empty()) {
        std::set<std::string> names;
        for (ModelInstance *mi : m_unarranged)
            names.insert(mi->get_object()->name);
        m_plater->get_notification_manager()->push_notification(GUI::format(
            _L("Arrangement ignored the following objects which can't fit into a single bed:\n%s"),
            concat_strings(names, "\n")));
    }
}
References _, _L, Slic3r::GUI::concat_strings(), Slic3r::GUI::Plater::FORCE_FULL_SCREEN_REFRESH, Slic3r::GUI::format(), Slic3r::GUI::Plater::get_notification_manager(), L, m_plater, m_selected, m_unarranged, m_unprintable, m_unselected, Slic3r::GUI::NotificationManager::push_notification(), Slic3r::GUI::show_error(), and Slic3r::GUI::Plater::update().
get_arrange_poly_()
arrangement::ArrangePolygon Slic3r::GUI::ArrangeJob::get_arrange_poly_ (ModelInstance * mi) private
{
    arrangement::ArrangePolygon ap = get_arrange_poly(mi, m_plater);
    auto setter = ap.setter;
    ap.setter = [this, setter, mi](const arrangement::ArrangePolygon &set_ap) {
        setter(set_ap);
        if (!set_ap.is_arranged())
            m_unarranged.emplace_back(mi);
    };
    return ap;
}
References Slic3r::GUI::get_arrange_poly(), m_plater, m_unarranged, and Slic3r::arrangement::ArrangePolygon::setter.
Referenced by prepare_all(), and prepare_selected().
prepare()
void Slic3r::GUI::ArrangeJob::prepare ()
{
    m_selection_only ? prepare_selected() :
                       prepare_all();
    coord_t min_offset = 0;
    for (auto &ap : m_selected) {
        min_offset = std::max(ap.inflation, min_offset);
    }
    if (m_plater->printer_technology() == ptSLA) {
        // Apply the max offset for all the objects
        for (auto &ap : m_selected) {
            ap.inflation = min_offset;
        }
    } else { // it's fff, brims only need to be minded from bed edges
        for (auto &ap : m_selected) {
            ap.inflation = 0;
        }
        m_min_bed_inset = min_offset;
    }
    double stride = bed_stride(m_plater);
    get_bed_shape(*m_plater->config(), m_bed);
    assign_logical_beds(m_unselected, m_bed, stride);
}
References Slic3r::GUI::assign_logical_beds(), Slic3r::GUI::bed_stride(), Slic3r::GUI::Plater::config(), Slic3r::get_bed_shape(), m_bed, m_min_bed_inset, m_plater, m_selected, m_selection_only, m_unselected, prepare_all(), prepare_selected(), Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptSLA.
Referenced by process().
prepare_all()
void Slic3r::GUI::ArrangeJob::prepare_all () private
{
    clear_input();
    for (ModelObject *obj: m_plater->model().objects)
        for (ModelInstance *mi : obj->instances) {
            ArrangePolygons & cont = mi->printable ? m_selected : m_unprintable;
            cont.emplace_back(get_arrange_poly_(mi));
        }
    if (auto wti = get_wipe_tower_arrangepoly(*m_plater))
        m_selected.emplace_back(std::move(*wti));
}
References clear_input(), get_arrange_poly_(), Slic3r::GUI::get_wipe_tower_arrangepoly(), m_plater, m_selected, m_unprintable, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by prepare().
prepare_selected()
void Slic3r::GUI::ArrangeJob::prepare_selected () private
{
    clear_input();
    Model &model = m_plater->model();
    std::vector<const Selection::InstanceIdxsList *>
            obj_sel(model.objects.size(), nullptr);
    for (auto &s : m_plater->get_selection().get_content())
        if (s.first < int(obj_sel.size()))
            obj_sel[size_t(s.first)] = &s.second;
    // Go through the objects and check if inside the selection
    for (size_t oidx = 0; oidx < model.objects.size(); ++oidx) {
        const Selection::InstanceIdxsList * instlist = obj_sel[oidx];
        ModelObject *mo = model.objects[oidx];
        std::vector<bool> inst_sel(mo->instances.size(), false);
        if (instlist)
            for (auto inst_id : *instlist)
                inst_sel[size_t(inst_id)] = true;
        for (size_t i = 0; i < inst_sel.size(); ++i) {
            ModelInstance * mi = mo->instances[i];
            ArrangePolygon &&ap = get_arrange_poly_(mi);
            ArrangePolygons &cont = mo->instances[i]->printable ?
                        (inst_sel[i] ? m_selected :
                                       m_unselected) :
                        m_unprintable;
            cont.emplace_back(std::move(ap));
        }
    }
    if (auto wti = get_wipe_tower(*m_plater)) {
        ArrangePolygon &&ap = get_arrange_poly(wti, m_plater);
        auto &cont = m_plater->get_selection().is_wipe_tower() ? m_selected :
                                                                 m_unselected;
        cont.emplace_back(std::move(ap));
    }
    // If the selection was empty arrange everything
    if (m_selected.empty())
        m_selected.swap(m_unselected);
}
References clear_input(), Slic3r::GUI::get_arrange_poly(), get_arrange_poly_(), Slic3r::GUI::Selection::get_content(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::get_wipe_tower(), Slic3r::ModelObject::instances, Slic3r::GUI::Selection::is_wipe_tower(), m_plater, m_selected, m_unprintable, m_unselected, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by prepare().
process()
void Slic3r::GUI::ArrangeJob::process (Ctl & ctl) override virtual
Implements Slic3r::GUI::Job.
{
    static const auto arrangestr = _u8L("Arranging");
    arrangement::ArrangeParams params;
    ctl.call_on_main_thread([this, &params]{
           prepare();
           params = get_arrange_params(m_plater);
           coord_t min_inset = get_skirt_offset(m_plater) + m_min_bed_inset;
           params.min_bed_distance = std::max(params.min_bed_distance, min_inset);
    }).wait();
    auto count  = unsigned(m_selected.size() + m_unprintable.size());
    if (count == 0) // Should be taken care of by plater, but doesn't hurt
        return;
    ctl.update_status(0, arrangestr);
    params.stopcondition = [&ctl]() { return ctl.was_canceled(); };
    params.progressind = [this, count, &ctl](unsigned st) {
        st += m_unprintable.size();
        if (st > 0) ctl.update_status(int(count - st) * 100 / status_range(), arrangestr);
    };
    ctl.update_status(0, arrangestr);
    arrangement::arrange(m_selected, m_unselected, m_bed, params);
    params.progressind = [this, count, &ctl](unsigned st) {
        if (st > 0) ctl.update_status(int(count - st) * 100 / status_range(), arrangestr);
    };
    arrangement::arrange(m_unprintable, {}, m_bed, params);
    // finalize just here.
    ctl.update_status(int(count) * 100 / status_range(), ctl.was_canceled() ?
                                      _u8L("Arranging canceled.") :
                                      _u8L("Arranging done."));
}
References _u8L, Slic3r::arrangement::arrange(), Slic3r::GUI::Job::Ctl::call_on_main_thread(), Slic3r::GUI::get_arrange_params(), Slic3r::GUI::get_skirt_offset(), m_bed, m_min_bed_inset, m_plater, m_selected, m_unprintable, m_unselected, Slic3r::arrangement::ArrangeParams::min_bed_distance, prepare(), Slic3r::arrangement::ArrangeParams::progressind, status_range(), Slic3r::arrangement::ArrangeParams::stopcondition, Slic3r::GUI::Job::Ctl::update_status(), and Slic3r::GUI::Job::Ctl::was_canceled().
status_range()
int Slic3r::GUI::ArrangeJob::status_range () const inline
    {
        return int(m_selected.size() + m_unprintable.size());
    }
References m_selected, and m_unprintable.
Referenced by process().
Member Data Documentation
m_bed
arrangement::ArrangeBed Slic3r::GUI::ArrangeJob::m_bed private
Referenced by prepare(), and process().
m_min_bed_inset
coord_t Slic3r::GUI::ArrangeJob::m_min_bed_inset = 0. private
Referenced by prepare(), and process().
m_plater
Plater* Slic3r::GUI::ArrangeJob::m_plater private
Referenced by clear_input(), finalize(), get_arrange_poly_(), prepare(), prepare_all(), prepare_selected(), and process().
m_selected
ArrangePolygons Slic3r::GUI::ArrangeJob::m_selected private
Referenced by clear_input(), finalize(), prepare(), prepare_all(), prepare_selected(), process(), and status_range().
m_selection_only
bool Slic3r::GUI::ArrangeJob::m_selection_only = false private
Referenced by prepare().
m_unarranged
std::vector<ModelInstance*> Slic3r::GUI::ArrangeJob::m_unarranged private
Referenced by clear_input(), finalize(), and get_arrange_poly_().
m_unprintable
ArrangePolygons Slic3r::GUI::ArrangeJob::m_unprintable private
Referenced by clear_input(), finalize(), prepare_all(), prepare_selected(), process(), and status_range().
m_unselected
ArrangePolygons Slic3r::GUI::ArrangeJob::m_unselected private
Referenced by clear_input(), finalize(), prepare(), prepare_selected(), and process().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/ArrangeJob.hpp
src/slic3r/GUI/Jobs/ArrangeJob.cpp