Prusa Slicer: Slic3r::GCodeProcessor::OptionsZCorrector Class Reference
Slic3r::GCodeProcessor::OptionsZCorrector Class Reference
#include <src/libslic3r/GCode/GCodeProcessor.hpp>
Public Member Functions
OptionsZCorrector (GCodeProcessorResult &result)
void set ()
void update (float height)
void reset ()
Private Attributes
GCodeProcessorResult & m_result
std::optional< size_t > m_move_id
std::optional< size_t > m_custom_gcode_per_print_z_id
Detailed Description
Constructor & Destructor Documentation
OptionsZCorrector()
Slic3r::GCodeProcessor::OptionsZCorrector::OptionsZCorrector (GCodeProcessorResult & result) inline explicit
                                                                     : m_result(result) {
            }
Member Function Documentation
reset()
void Slic3r::GCodeProcessor::OptionsZCorrector::reset () inline
{
                m_move_id.reset();
                m_custom_gcode_per_print_z_id.reset();
            }
References m_custom_gcode_per_print_z_id, and m_move_id.
Referenced by Slic3r::GCodeProcessor::reset(), and update().
set()
void Slic3r::GCodeProcessor::OptionsZCorrector::set () inline
                       {
                m_move_id = m_result.moves.size() - 1;
                m_custom_gcode_per_print_z_id = m_result.custom_gcode_per_print_z.size() - 1;
            }
References Slic3r::GCodeProcessorResult::custom_gcode_per_print_z, m_custom_gcode_per_print_z_id, m_move_id, m_result, and Slic3r::GCodeProcessorResult::moves.
Referenced by Slic3r::GCodeProcessor::process_tags().
update()
void Slic3r::GCodeProcessor::OptionsZCorrector::update (float height) inline
{
                if (!m_move_id.has_value() || !m_custom_gcode_per_print_z_id.has_value())
                    return;
                const Vec3f position = m_result.moves.back().position;
                GCodeProcessorResult::MoveVertex& move = m_result.moves.emplace_back(m_result.moves[*m_move_id]);
                move.position = position;
                move.height = height;
                m_result.moves.erase(m_result.moves.begin() + *m_move_id);
                m_result.custom_gcode_per_print_z[*m_custom_gcode_per_print_z_id].print_z = position.z();
                reset();
            }
References Slic3r::GCodeProcessorResult::custom_gcode_per_print_z, Slic3r::GCodeProcessorResult::MoveVertex::height, m_custom_gcode_per_print_z_id, m_move_id, m_result, Slic3r::GCodeProcessorResult::moves, Slic3r::GCodeProcessorResult::MoveVertex::position, and reset().
Referenced by Slic3r::GCodeProcessor::process_G1().
Member Data Documentation
m_custom_gcode_per_print_z_id
std::optional<size_t> Slic3r::GCodeProcessor::OptionsZCorrector::m_custom_gcode_per_print_z_id private
Referenced by reset(), set(), and update().
m_move_id
std::optional<size_t> Slic3r::GCodeProcessor::OptionsZCorrector::m_move_id private
Referenced by reset(), set(), and update().
m_result
GCodeProcessorResult& Slic3r::GCodeProcessor::OptionsZCorrector::m_result private
Referenced by set(), and update().
The documentation for this class was generated from the following file:
src/libslic3r/GCode/GCodeProcessor.hpp