Prusa Slicer: Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > Class Template Reference
Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > Class Template Reference
Represents a diagonal matrix with its storage.
#include <src/eigen/Eigen/src/Core/DiagonalMatrix.h>
Public Types
typedef internal::traits< DiagonalMatrix >::DiagonalVectorType DiagonalVectorType
typedef const DiagonalMatrix & Nested
typedef _Scalar Scalar
typedef internal::traits< DiagonalMatrix >::StorageKind StorageKind
typedef internal::traits< DiagonalMatrix >::StorageIndex StorageIndex
enum
typedef DiagonalVectorType::RealScalar RealScalar
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType DenseType
typedef DiagonalMatrix< Scalar, DiagonalVectorType::SizeAtCompileTime, DiagonalVectorType::MaxSizeAtCompileTime > PlainObject
typedef DiagonalWrapper< const CwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const DiagonalVectorType > > InverseReturnType
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
EIGEN_DEVICE_FUNC const DiagonalVectorType & diagonal () const
EIGEN_DEVICE_FUNC DiagonalVectorType & diagonal ()
EIGEN_DEVICE_FUNC DiagonalMatrix ()
EIGEN_DEVICE_FUNC DiagonalMatrix (Index dim)
EIGEN_DEVICE_FUNC DiagonalMatrix (const Scalar &x, const Scalar &y)
EIGEN_DEVICE_FUNC DiagonalMatrix (const Scalar &x, const Scalar &y, const Scalar &z)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC DiagonalMatrix (const DiagonalBase< OtherDerived > &other)
DiagonalMatrix (const DiagonalMatrix &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC DiagonalMatrix (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC DiagonalMatrix & operator= (const DiagonalBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC DiagonalMatrix & operator= (const DiagonalMatrix &other)
EIGEN_DEVICE_FUNC void resize (Index size)
EIGEN_DEVICE_FUNC void setZero ()
EIGEN_DEVICE_FUNC void setZero (Index size)
EIGEN_DEVICE_FUNC void setIdentity ()
EIGEN_DEVICE_FUNC void setIdentity (Index size)
EIGEN_DEVICE_FUNC const DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & derived () const
EIGEN_DEVICE_FUNC DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & derived ()
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC const Product< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >, MatrixDerived, LazyProduct > operator* (const MatrixBase< MatrixDerived > &matrix) const
EIGEN_DEVICE_FUNC const DiagonalWrapper< const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(DiagonalVectorType, Scalar, product) > operator* (const Scalar &scalar) const
EIGEN_DEVICE_FUNC const InverseReturnType inverse () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Attributes
DiagonalVectorType m_diagonal
Detailed Description
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime>
class Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >
Represents a diagonal matrix with its storage.
Parameters
_Scalar the type of coefficients
SizeAtCompileTime the dimension of the matrix, or Dynamic
MaxSizeAtCompileTime the dimension of the matrix, or Dynamic. This parameter is optional and defaults to SizeAtCompileTime. Most of the time, you do not need to specify it.
See also
class DiagonalWrapper
Member Typedef Documentation
DenseMatrixType
typedef Matrix<Scalar, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::DenseMatrixType inherited
DenseType
typedef DenseMatrixType Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::DenseType inherited
DiagonalVectorType
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef internal::traits<DiagonalMatrix>::DiagonalVectorType Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalVectorType
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
InverseReturnType
typedef DiagonalWrapper<const CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const DiagonalVectorType> > Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::InverseReturnType inherited
Nested
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef const DiagonalMatrix& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::Nested
PlainObject
typedef DiagonalMatrix<Scalar,DiagonalVectorType::SizeAtCompileTime,DiagonalVectorType::MaxSizeAtCompileTime> Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::PlainObject inherited
RealScalar
typedef DiagonalVectorType::RealScalar Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::RealScalar inherited
Scalar
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef _Scalar Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::Scalar
StorageIndex
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef internal::traits<DiagonalMatrix>::StorageIndex Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::StorageIndex
StorageKind
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef internal::traits<DiagonalMatrix>::StorageKind Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::StorageKind
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
         {
      RowsAtCompileTime = DiagonalVectorType::SizeAtCompileTime,
      ColsAtCompileTime = DiagonalVectorType::SizeAtCompileTime,
      MaxRowsAtCompileTime = DiagonalVectorType::MaxSizeAtCompileTime,
      MaxColsAtCompileTime = DiagonalVectorType::MaxSizeAtCompileTime,
      IsVectorAtCompileTime = 0,
      Flags = NoPreferredStorageOrderBit
    };
Constructor & Destructor Documentation
DiagonalMatrix() [1/7]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix () inline
Default constructor without initialization
{}
DiagonalMatrix() [2/7]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (Index dim) inline explicit
Constructs a diagonal matrix with given dimension
: m_diagonal(dim) {}
DiagonalMatrix() [3/7]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const Scalar & x, const Scalar & y) inline
2D constructor.
: m_diagonal(x,y) {}
DiagonalMatrix() [4/7]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const Scalar & x, const Scalar & y, const Scalar & z) inline
3D constructor.
: m_diagonal(x,y,z) {}
DiagonalMatrix() [5/7]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const DiagonalBase< OtherDerived > & other) inline
Copy constructor.
: m_diagonal(other.diagonal()) {}
DiagonalMatrix() [6/7]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & other) inline
copy constructor. prevent a default copy constructor from hiding the other templated constructor
: m_diagonal(other.diagonal()) {}
DiagonalMatrix() [7/7]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const MatrixBase< OtherDerived > & other) inline explicit
generic constructor from expression of the diagonal coefficients
                                                                          : m_diagonal(other)
    {}
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
cols()
EIGEN_DEVICE_FUNC Index Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::cols () const inline inherited
{ return diagonal().size(); }
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
EIGEN_DEVICE_FUNC DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::derived () inline inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
EIGEN_DEVICE_FUNC const DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::derived () const inline inherited
{ return *static_cast<const Derived*>(this); }
diagonal() [1/2]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC DiagonalVectorType & Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal () inline
Returns
a reference to the stored vector of diagonal coefficients.
{ return m_diagonal; }
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
diagonal() [2/2]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC const DiagonalVectorType & Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal () const inline
const version of diagonal().
{ return m_diagonal; }
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
Referenced by igl::biharmonic_coordinates(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator=().
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
Referenced by Eigen::EigenBase< Derived >::subTo().
inverse()
EIGEN_DEVICE_FUNC const InverseReturnType Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::inverse () const inline inherited
    {
      return InverseReturnType(diagonal().cwiseInverse());
    }
operator*() [1/2]
EIGEN_DEVICE_FUNC const Product< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > , MatrixDerived, LazyProduct > Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::operator* (const MatrixBase< MatrixDerived > & matrix) const inline inherited
    {
      return Product<Derived, MatrixDerived, LazyProduct>(derived(),matrix.derived());
    }
operator*() [2/2]
EIGEN_DEVICE_FUNC const DiagonalWrapper< const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(DiagonalVectorType, Scalar, product) > Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::operator* (const Scalar & scalar) const inline inherited
    {
      return DiagonalWrapper<const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(DiagonalVectorType,Scalar,product) >(diagonal() * scalar);
    }
operator=() [1/2]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> template<typename OtherDerived > EIGEN_DEVICE_FUNC DiagonalMatrix & Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator= (const DiagonalBase< OtherDerived > & other) inline
Copy operator.
    {
      m_diagonal = other.diagonal();
      return *this;
    }
References Eigen::DiagonalBase< Derived >::diagonal(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
operator=() [2/2]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC DiagonalMatrix & Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator= (const DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
    {
      m_diagonal = other.diagonal();
      return *this;
    }
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
resize()
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize (Index size) inline
Resizes to given size.
{ m_diagonal.resize(size); }
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal, and Eigen::EigenBase< Derived >::size().
rows()
EIGEN_DEVICE_FUNC Index Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::rows () const inline inherited
{ return diagonal().size(); }
setIdentity() [1/2]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity () inline
Sets this matrix to be the identity matrix of the current size.
{ m_diagonal.setOnes(); }
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
setIdentity() [2/2]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity (Index size) inline
Sets this matrix to be the identity matrix of the given size.
{ m_diagonal.setOnes(size); }
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal, and Eigen::EigenBase< Derived >::size().
setZero() [1/2]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero () inline
Sets all coefficients to zero.
{ m_diagonal.setZero(); }
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
setZero() [2/2]
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> EIGEN_DEVICE_FUNC void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero (Index size) inline
Resizes and sets all coefficients to zero.
{ m_diagonal.setZero(size); }
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal, and Eigen::EigenBase< Derived >::size().
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
References Eigen::EigenBase< Derived >::cols(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
toDenseMatrix()
EIGEN_DEVICE_FUNC DenseMatrixType Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::toDenseMatrix () const inline inherited
{ return derived(); }
Member Data Documentation
m_diagonal
template<typename _Scalar , int SizeAtCompileTime, int MaxSizeAtCompileTime> DiagonalVectorType Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal protected
Referenced by Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator=(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator=(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/DiagonalMatrix.h