Prusa Slicer: Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator Class Reference
Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator Class Reference
#include <src/eigen/Eigen/src/SparseCore/SparseDenseProduct.h>
Public Member Functions
InnerIterator (const sparse_dense_outer_product_evaluator &xprEval, Index outer)
EIGEN_STRONG_INLINE Index outer () const
EIGEN_STRONG_INLINE Index row () const
EIGEN_STRONG_INLINE Index col () const
EIGEN_STRONG_INLINE Scalar value () const
EIGEN_STRONG_INLINE operator bool () const
Protected Member Functions
Scalar get (const RhsEval &rhs, Index outer, Dense=Dense()) const
Scalar get (const RhsEval &rhs, Index outer, Sparse=Sparse())
Protected Attributes
Index m_outer
bool m_empty
Scalar m_factor
Detailed Description
template<typename LhsT, typename RhsT, bool NeedToTranspose>
class Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator
Constructor & Destructor Documentation
InnerIterator()
template<typename LhsT , typename RhsT , bool NeedToTranspose> Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::InnerIterator (const sparse_dense_outer_product_evaluator & xprEval, Index outer) inline
      : LhsIterator(xprEval.m_lhsXprImpl, 0),
        m_outer(outer),
        m_empty(false),
        m_factor(get(xprEval.m_rhsXprImpl, outer, typename internal::traits<ActualRhs>::StorageKind() ))
    {}
References Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::get().
Member Function Documentation
col()
template<typename LhsT , typename RhsT , bool NeedToTranspose> EIGEN_STRONG_INLINE Index Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::col () const inline
{ return NeedToTranspose ? LhsIterator::index() : m_outer; }
References Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::m_outer.
get() [1/2]
template<typename LhsT , typename RhsT , bool NeedToTranspose> Scalar Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::get (const RhsEval & rhs, Index outer, Dense = Dense()) const inline protected
    {
      return rhs.coeff(outer);
    }
References Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::outer().
Referenced by Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::InnerIterator().
get() [2/2]
template<typename LhsT , typename RhsT , bool NeedToTranspose> Scalar Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::get (const RhsEval & rhs, Index outer, Sparse = Sparse()) inline protected
    {
      typename RhsEval::InnerIterator it(rhs, outer);
      if (it && it.index()==0 && it.value()!=Scalar(0))
        return it.value();
      m_empty = true;
      return Scalar(0);
    }
References Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::m_empty, and Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::outer().
operator bool()
template<typename LhsT , typename RhsT , bool NeedToTranspose> EIGEN_STRONG_INLINE Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::operator bool () const inline
{ return LhsIterator::operator bool() && (!m_empty); }
References Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::m_empty.
outer()
template<typename LhsT , typename RhsT , bool NeedToTranspose> EIGEN_STRONG_INLINE Index Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::outer () const inline
{ return m_outer; }
References Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::m_outer.
Referenced by Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::get(), and Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::get().
row()
template<typename LhsT , typename RhsT , bool NeedToTranspose> EIGEN_STRONG_INLINE Index Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::row () const inline
{ return NeedToTranspose ? m_outer : LhsIterator::index(); }
References Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::m_outer.
value()
template<typename LhsT , typename RhsT , bool NeedToTranspose> EIGEN_STRONG_INLINE Scalar Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::value () const inline
{ return LhsIterator::value() * m_factor; }
References Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::m_factor.
Member Data Documentation
m_empty
template<typename LhsT , typename RhsT , bool NeedToTranspose> bool Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::m_empty protected
Referenced by Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::get(), and Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::operator bool().
m_factor
template<typename LhsT , typename RhsT , bool NeedToTranspose> Scalar Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::m_factor protected
Referenced by Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::value().
m_outer
template<typename LhsT , typename RhsT , bool NeedToTranspose> Index Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::m_outer protected
Referenced by Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::col(), Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::outer(), and Eigen::internal::sparse_dense_outer_product_evaluator< LhsT, RhsT, NeedToTranspose >::InnerIterator::row().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseDenseProduct.h