Prusa Slicer: agg::blender_rgb_gamma< ColorT, Order, Gamma > Class Template Reference
agg::blender_rgb_gamma< ColorT, Order, Gamma > Class Template Reference
#include <src/agg/agg_pixfmt_rgb.h>
Public Types
typedef ColorT color_type
typedef Order order_type
typedef Gamma gamma_type
typedef color_type::value_type value_type
typedef color_type::calc_type calc_type
typedef color_type::long_type long_type
Public Member Functions
blender_rgb_gamma ()
void gamma (const gamma_type &g)
AGG_INLINE void blend_pix (value_type *p, value_type cr, value_type cg, value_type cb, value_type alpha, cover_type cover)
AGG_INLINE void blend_pix (value_type *p, value_type cr, value_type cg, value_type cb, value_type alpha)
Static Public Member Functions
static rgba get (value_type r, value_type g, value_type b, value_type a, cover_type cover=cover_full)
static rgba get (const value_type *p, cover_type cover=cover_full)
static void set (value_type *p, value_type r, value_type g, value_type b, value_type a)
static void set (value_type *p, const rgba &c)
Private Attributes
const gamma_type * m_gamma
Detailed Description
template<class ColorT, class Order, class Gamma>
class agg::blender_rgb_gamma< ColorT, Order, Gamma >
Member Typedef Documentation
calc_type
template<class ColorT , class Order , class Gamma > typedef color_type::calc_type agg::blender_rgb_gamma< ColorT, Order, Gamma >::calc_type
color_type
template<class ColorT , class Order , class Gamma > typedef ColorT agg::blender_rgb_gamma< ColorT, Order, Gamma >::color_type
gamma_type
template<class ColorT , class Order , class Gamma > typedef Gamma agg::blender_rgb_gamma< ColorT, Order, Gamma >::gamma_type
long_type
template<class ColorT , class Order , class Gamma > typedef color_type::long_type agg::blender_rgb_gamma< ColorT, Order, Gamma >::long_type
order_type
template<class ColorT , class Order , class Gamma > typedef Order agg::blender_rgb_gamma< ColorT, Order, Gamma >::order_type
value_type
template<class ColorT , class Order , class Gamma > typedef color_type::value_type agg::blender_rgb_gamma< ColorT, Order, Gamma >::value_type
Constructor & Destructor Documentation
blender_rgb_gamma()
template<class ColorT , class Order , class Gamma > agg::blender_rgb_gamma< ColorT, Order, Gamma >::blender_rgb_gamma () inline
: m_gamma(0) {}
Member Function Documentation
blend_pix() [1/2]
template<class ColorT , class Order , class Gamma > AGG_INLINE void agg::blender_rgb_gamma< ColorT, Order, Gamma >::blend_pix (value_type * p, value_type cr, value_type cg, value_type cb, value_type alpha) inline
        {
            calc_type r = m_gamma->dir(p[Order::R]);
            calc_type g = m_gamma->dir(p[Order::G]);
            calc_type b = m_gamma->dir(p[Order::B]);
            p[Order::R] = m_gamma->inv(color_type::downscale((m_gamma->dir(cr) - r) * alpha) + r);
            p[Order::G] = m_gamma->inv(color_type::downscale((m_gamma->dir(cg) - g) * alpha) + g);
            p[Order::B] = m_gamma->inv(color_type::downscale((m_gamma->dir(cb) - b) * alpha) + b);
        }
References agg::blender_rgb_gamma< ColorT, Order, Gamma >::m_gamma.
blend_pix() [2/2]
template<class ColorT , class Order , class Gamma > AGG_INLINE void agg::blender_rgb_gamma< ColorT, Order, Gamma >::blend_pix (value_type * p, value_type cr, value_type cg, value_type cb, value_type alpha, cover_type cover) inline
        {
            blend_pix(p, cr, cg, cb, color_type::mult_cover(alpha, cover));
        }
References agg::blender_rgb_gamma< ColorT, Order, Gamma >::blend_pix().
Referenced by agg::blender_rgb_gamma< ColorT, Order, Gamma >::blend_pix().
gamma()
template<class ColorT , class Order , class Gamma > void agg::blender_rgb_gamma< ColorT, Order, Gamma >::gamma (const gamma_type & g) inline
{ m_gamma = &g; }
References agg::blender_rgb_gamma< ColorT, Order, Gamma >::m_gamma.
Referenced by agg::pixfmt_bgr24_gamma< Gamma >::pixfmt_bgr24_gamma(), agg::pixfmt_bgr48_gamma< Gamma >::pixfmt_bgr48_gamma(), agg::pixfmt_rgb24_gamma< Gamma >::pixfmt_rgb24_gamma(), agg::pixfmt_rgb48_gamma< Gamma >::pixfmt_rgb48_gamma(), agg::pixfmt_sbgr24_gamma< Gamma >::pixfmt_sbgr24_gamma(), and agg::pixfmt_srgb24_gamma< Gamma >::pixfmt_srgb24_gamma().
get() [1/2]
static rgba agg::blender_base< ColorT, Order >::get (const value_type * p, cover_type cover = cover_full) inline static inherited
        {
            return get(
                p[order_type::R],
                p[order_type::G],
                p[order_type::B],
                p[order_type::A],
                cover);
        }
get() [2/2]
static rgba agg::blender_base< ColorT, Order >::get (value_type r, value_type g, value_type b, value_type a, cover_type cover = cover_full) inline static inherited
        {
            if (cover > cover_none)
            {
                rgba c(
                    color_type::to_double(r),
                    color_type::to_double(g),
                    color_type::to_double(b),
                    color_type::to_double(a));
                if (cover < cover_full)
                {
                    double x = double(cover) / cover_full;
                    c.r *= x;
                    c.g *= x;
                    c.b *= x;
                    c.a *= x;
                }
                return c;
            }
            else return rgba::no_color();
        }
set() [1/2]
static void agg::blender_base< ColorT, Order >::set (value_type * p, const rgba & c) inline static inherited
        {
            p[order_type::R] = color_type::from_double(c.r);
            p[order_type::G] = color_type::from_double(c.g);
            p[order_type::B] = color_type::from_double(c.b);
            p[order_type::A] = color_type::from_double(c.a);
        }
set() [2/2]
static void agg::blender_base< ColorT, Order >::set (value_type * p, value_type r, value_type g, value_type b, value_type a) inline static inherited
        {
            p[order_type::R] = r;
            p[order_type::G] = g;
            p[order_type::B] = b;
            p[order_type::A] = a;
        }
Member Data Documentation
m_gamma
template<class ColorT , class Order , class Gamma > const gamma_type* agg::blender_rgb_gamma< ColorT, Order, Gamma >::m_gamma private
Referenced by agg::blender_rgb_gamma< ColorT, Order, Gamma >::blend_pix(), and agg::blender_rgb_gamma< ColorT, Order, Gamma >::gamma().
The documentation for this class was generated from the following file:
src/agg/agg_pixfmt_rgb.h