Prusa Slicer: src/avrdude/jtagmkI.h File Reference
jtagmkI.h File Reference
Functions
void jtagmkI_initpgm (PROGRAMMER *pgm)
Variables
const char jtagmkI_desc []
Function Documentation
jtagmkI_initpgm()
void jtagmkI_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAGMKI");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtagmkI_initialize;
  pgm->display        = jtagmkI_display;
  pgm->enable         = jtagmkI_enable;
  pgm->disable        = jtagmkI_disable;
  pgm->program_enable = jtagmkI_program_enable_dummy;
  pgm->chip_erase     = jtagmkI_chip_erase;
  pgm->open           = jtagmkI_open;
  pgm->close          = jtagmkI_close;
  pgm->read_byte      = jtagmkI_read_byte;
  pgm->write_byte     = jtagmkI_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtagmkI_paged_write;
  pgm->paged_load     = jtagmkI_paged_load;
  pgm->print_parms    = jtagmkI_print_parms;
  pgm->set_sck_period = jtagmkI_set_sck_period;
  pgm->setup          = jtagmkI_setup;
  pgm->teardown       = jtagmkI_teardown;
  pgm->page_size      = 256;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, jtagmkI_chip_erase(), jtagmkI_close(), jtagmkI_disable(), jtagmkI_display(), jtagmkI_enable(), jtagmkI_initialize(), jtagmkI_open(), jtagmkI_paged_load(), jtagmkI_paged_write(), jtagmkI_print_parms(), jtagmkI_program_enable_dummy(), jtagmkI_read_byte(), jtagmkI_set_sck_period(), jtagmkI_setup(), jtagmkI_teardown(), jtagmkI_write_byte(), programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_sck_period, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
Variable Documentation
jtagmkI_desc
const char jtagmkI_desc[] extern