Prusa Slicer: Slic3r::ColorRGB Class Reference
Slic3r::ColorRGB Class Reference
#include <src/libslic3r/Color.hpp>
Public Member Functions
ColorRGB ()=default
ColorRGB (float r, float g, float b)
ColorRGB (unsigned char r, unsigned char g, unsigned char b)
ColorRGB (const ColorRGB &other)=default
ColorRGB & operator= (const ColorRGB &other)
bool operator== (const ColorRGB &other) const
bool operator!= (const ColorRGB &other) const
bool operator< (const ColorRGB &other) const
bool operator> (const ColorRGB &other) const
ColorRGB operator+ (const ColorRGB &other) const
ColorRGB operator* (float value) const
const float *const data () const
float r () const
float g () const
float b () const
void r (float r)
void g (float g)
void b (float b)
void set (unsigned int comp, float value)
unsigned char r_uchar () const
unsigned char g_uchar () const
unsigned char b_uchar () const
Static Public Member Functions
static const ColorRGB BLACK ()
static const ColorRGB BLUE ()
static const ColorRGB BLUEISH ()
static const ColorRGB CYAN ()
static const ColorRGB DARK_GRAY ()
static const ColorRGB DARK_YELLOW ()
static const ColorRGB GRAY ()
static const ColorRGB GREEN ()
static const ColorRGB GREENISH ()
static const ColorRGB LIGHT_GRAY ()
static const ColorRGB MAGENTA ()
static const ColorRGB ORANGE ()
static const ColorRGB RED ()
static const ColorRGB REDISH ()
static const ColorRGB YELLOW ()
static const ColorRGB WHITE ()
static const ColorRGB X ()
static const ColorRGB Y ()
static const ColorRGB Z ()
Private Attributes
std::array< float, 3 > m_data {1.0f, 1.0f, 1.0f}
Detailed Description
Constructor & Destructor Documentation
ColorRGB() [1/4]
Slic3r::ColorRGB::ColorRGB () default
ColorRGB() [2/4]
Slic3r::ColorRGB::ColorRGB (float r, float g, float b)
: m_data({ std::clamp(r, 0.0f, 1.0f), std::clamp(g, 0.0f, 1.0f), std::clamp(b, 0.0f, 1.0f) })
{
}
References b(), g(), and r().
ColorRGB() [3/4]
Slic3r::ColorRGB::ColorRGB (unsigned char r, unsigned char g, unsigned char b)
: m_data({ std::clamp(r * INV_255, 0.0f, 1.0f), std::clamp(g * INV_255, 0.0f, 1.0f), std::clamp(b * INV_255, 0.0f, 1.0f) })
{
}
References b(), g(), INV_255, and r().
ColorRGB() [4/4]
Slic3r::ColorRGB::ColorRGB (const ColorRGB & other) default
Member Function Documentation
b() [1/2]
float Slic3r::ColorRGB::b () const inline
{ return m_data[2]; }
References m_data.
Referenced by ColorRGB(), ColorRGB(), b(), Slic3r::complementary(), Slic3r::decode_color(), Slic3r::opposite(), Slic3r::saturate(), Slic3r::to_rgba(), and Slic3r::to_rgba().
b() [2/2]
void Slic3r::ColorRGB::b (float b) inline
{ m_data[2] = std::clamp(b, 0.0f, 1.0f); }
References b(), and m_data.
b_uchar()
unsigned char Slic3r::ColorRGB::b_uchar () const inline
{ return static_cast<unsigned char>(m_data[2] * 255.0f); }
References m_data.
Referenced by WipingPanel::WipingPanel(), Slic3r::encode_color(), and Slic3r::GUI::BitmapCache::mksolid_bndl().
BLACK()
static const ColorRGB Slic3r::ColorRGB::BLACK () inline static
{ return { 0.0f, 0.0f, 0.0f }; }
Referenced by Slic3r::decode_color(), and Slic3r::decode_colors().
BLUE()
static const ColorRGB Slic3r::ColorRGB::BLUE () inline static
{ return { 0.0f, 0.0f, 1.0f }; }
BLUEISH()
static const ColorRGB Slic3r::ColorRGB::BLUEISH () inline static
{ return { 0.5f, 0.5f, 1.0f }; }
CYAN()
static const ColorRGB Slic3r::ColorRGB::CYAN () inline static
{ return { 0.0f, 1.0f, 1.0f }; }
DARK_GRAY()
static const ColorRGB Slic3r::ColorRGB::DARK_GRAY () inline static
{ return { 0.25f, 0.25f, 0.25f }; }
DARK_YELLOW()
static const ColorRGB Slic3r::ColorRGB::DARK_YELLOW () inline static
{ return { 0.5f, 0.5f, 0.0f }; }
data()
const float *const Slic3r::ColorRGB::data () const inline
{ return m_data.data(); }
References m_data.
Referenced by Slic3r::GLShaderProgram::set_uniform().
g() [1/2]
float Slic3r::ColorRGB::g () const inline
{ return m_data[1]; }
References m_data.
Referenced by ColorRGB(), ColorRGB(), Slic3r::complementary(), Slic3r::decode_color(), g(), Slic3r::opposite(), Slic3r::saturate(), Slic3r::to_rgba(), and Slic3r::to_rgba().
g() [2/2]
void Slic3r::ColorRGB::g (float g) inline
{ m_data[1] = std::clamp(g, 0.0f, 1.0f); }
References g(), and m_data.
g_uchar()
unsigned char Slic3r::ColorRGB::g_uchar () const inline
{ return static_cast<unsigned char>(m_data[1] * 255.0f); }
References m_data.
Referenced by WipingPanel::WipingPanel(), Slic3r::encode_color(), and Slic3r::GUI::BitmapCache::mksolid_bndl().
GRAY()
static const ColorRGB Slic3r::ColorRGB::GRAY () inline static
{ return { 0.5f, 0.5f, 0.5f }; }
GREEN()
static const ColorRGB Slic3r::ColorRGB::GREEN () inline static
{ return { 0.0f, 1.0f, 0.0f }; }
GREENISH()
static const ColorRGB Slic3r::ColorRGB::GREENISH () inline static
{ return { 0.5f, 1.0f, 0.5f }; }
LIGHT_GRAY()
static const ColorRGB Slic3r::ColorRGB::LIGHT_GRAY () inline static
{ return { 0.75f, 0.75f, 0.75f }; }
MAGENTA()
static const ColorRGB Slic3r::ColorRGB::MAGENTA () inline static
{ return { 1.0f, 0.0f, 1.0f }; }
operator!=()
bool Slic3r::ColorRGB::operator!= (const ColorRGB & other) const inline
{ return !operator==(other); }
References operator==().
operator*()
ColorRGB Slic3r::ColorRGB::operator* (float value) const
{
  assert(value >= 0.0f);
  ColorRGB ret;
  for (size_t i = 0; i < 3; ++i) {
    ret.m_data[i] = std::clamp(value * m_data[i], 0.0f, 1.0f);
  }
  return ret;
}
References m_data.
operator+()
ColorRGB Slic3r::ColorRGB::operator+ (const ColorRGB & other) const
{
  ColorRGB ret;
  for (size_t i = 0; i < 3; ++i) {
    ret.m_data[i] = std::clamp(m_data[i] + other.m_data[i], 0.0f, 1.0f);
  }
  return ret;
}
References m_data.
operator<()
bool Slic3r::ColorRGB::operator< (const ColorRGB & other) const
{
  for (size_t i = 0; i < 3; ++i) {
    if (m_data[i] < other.m_data[i])
      return true;
    else if (m_data[i] > other.m_data[i])
      return false;
  }
  return false;
}
References m_data.
operator=()
ColorRGB & Slic3r::ColorRGB::operator= (const ColorRGB & other) inline
{ m_data = other.m_data; return *this; }
References m_data.
operator==()
bool Slic3r::ColorRGB::operator== (const ColorRGB & other) const inline
{ return m_data == other.m_data; }
References m_data.
Referenced by operator!=().
operator>()
bool Slic3r::ColorRGB::operator> (const ColorRGB & other) const
{
  for (size_t i = 0; i < 3; ++i) {
    if (m_data[i] > other.m_data[i])
      return true;
    else if (m_data[i] < other.m_data[i])
      return false;
  }
  return false;
}
References m_data.
ORANGE()
static const ColorRGB Slic3r::ColorRGB::ORANGE () inline static
{ return { 0.92f, 0.50f, 0.26f }; }
r() [1/2]
float Slic3r::ColorRGB::r () const inline
{ return m_data[0]; }
References m_data.
Referenced by ColorRGB(), ColorRGB(), Slic3r::complementary(), Slic3r::decode_color(), Slic3r::opposite(), r(), Slic3r::saturate(), Slic3r::to_rgba(), and Slic3r::to_rgba().
r() [2/2]
void Slic3r::ColorRGB::r (float r) inline
{ m_data[0] = std::clamp(r, 0.0f, 1.0f); }
References m_data, and r().
r_uchar()
unsigned char Slic3r::ColorRGB::r_uchar () const inline
{ return static_cast<unsigned char>(m_data[0] * 255.0f); }
References m_data.
Referenced by WipingPanel::WipingPanel(), Slic3r::encode_color(), and Slic3r::GUI::BitmapCache::mksolid_bndl().
RED()
static const ColorRGB Slic3r::ColorRGB::RED () inline static
{ return { 1.0f, 0.0f, 0.0f }; }
REDISH()
static const ColorRGB Slic3r::ColorRGB::REDISH () inline static
{ return { 1.0f, 0.5f, 0.5f }; }
set()
void Slic3r::ColorRGB::set (unsigned int comp, float value) inline
{
    assert(0 <= comp && comp <= 2);
    m_data[comp] = std::clamp(value, 0.0f, 1.0f);
  }
References m_data.
Referenced by Slic3r::decode_color().
WHITE()
static const ColorRGB Slic3r::ColorRGB::WHITE () inline static
{ return { 1.0f, 1.0f, 1.0f }; }
Referenced by Slic3r::GUI::Selection::render().
X()
static const ColorRGB Slic3r::ColorRGB::X () inline static
{ return { 0.75f, 0.0f, 0.0f }; }
Y()
static const ColorRGB Slic3r::ColorRGB::Y () inline static
{ return { 0.0f, 0.75f, 0.0f }; }
YELLOW()
static const ColorRGB Slic3r::ColorRGB::YELLOW () inline static
{ return { 1.0f, 1.0f, 0.0f }; }
Referenced by Slic3r::GUI::Selection::render_synchronized_volumes().
Z()
static const ColorRGB Slic3r::ColorRGB::Z () inline static
{ return { 0.0f, 0.0f, 0.75f }; }
Member Data Documentation
m_data
std::array<float, 3> Slic3r::ColorRGB::m_data {1.0f, 1.0f, 1.0f} private
Referenced by b(), b(), b_uchar(), data(), g(), g(), g_uchar(), operator*(), operator+(), operator<(), operator=(), operator==(), operator>(), r(), r(), r_uchar(), and set().
The documentation for this class was generated from the following files:
src/libslic3r/Color.hpp
src/libslic3r/Color.cpp