Prusa Slicer: Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode > Class Template Reference
Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode > Class Template Reference
#include <src/eigen/Eigen/src/SparseCore/SparseSelfAdjointView.h>
Public Types
enum { RowsAtCompileTime = internal::traits<SparseSymmetricPermutationProduct>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<SparseSymmetricPermutationProduct>::ColsAtCompileTime }
typedef MatrixType::Scalar Scalar
typedef MatrixType::StorageIndex StorageIndex
typedef Matrix< StorageIndex, Dynamic, 1 > VectorI
typedef MatrixType::Nested MatrixTypeNested
typedef internal::remove_all< MatrixTypeNested >::type NestedExpression
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< SparseSymmetricPermutationProduct< MatrixType, Mode > >::StorageKind StorageKind
Public Member Functions
SparseSymmetricPermutationProduct (const MatrixType &mat, const Perm &perm)
Index rows () const
Index cols () const
const NestedExpression & matrix () const
const Perm & perm () const
EIGEN_DEVICE_FUNC SparseSymmetricPermutationProduct< MatrixType, Mode > & derived ()
EIGEN_DEVICE_FUNC const SparseSymmetricPermutationProduct< MatrixType, Mode > & derived () const
EIGEN_DEVICE_FUNC SparseSymmetricPermutationProduct< MatrixType, Mode > & const_cast_derived () const
EIGEN_DEVICE_FUNC const SparseSymmetricPermutationProduct< MatrixType, Mode > & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Types
typedef PermutationMatrix< Dynamic, Dynamic, StorageIndex > Perm
Protected Attributes
MatrixTypeNested m_matrix
const Perm & m_perm
Detailed Description
template<typename MatrixType, int Mode>
class Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >
Member Typedef Documentation
Index
typedef Eigen::Index Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
MatrixTypeNested
template<typename MatrixType , int Mode> typedef MatrixType::Nested Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::MatrixTypeNested
NestedExpression
template<typename MatrixType , int Mode> typedef internal::remove_all<MatrixTypeNested>::type Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::NestedExpression
Perm
template<typename MatrixType , int Mode> typedef PermutationMatrix<Dynamic,Dynamic,StorageIndex> Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::Perm protected
Scalar
template<typename MatrixType , int Mode> typedef MatrixType::Scalar Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::Scalar
StorageIndex
template<typename MatrixType , int Mode> typedef MatrixType::StorageIndex Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::StorageIndex
StorageKind
typedef internal::traits<SparseSymmetricPermutationProduct< MatrixType, Mode > >::StorageKind Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::StorageKind inherited
VectorI
template<typename MatrixType , int Mode> typedef Matrix<StorageIndex,Dynamic,1> Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::VectorI
Member Enumeration Documentation
anonymous enum
template<typename MatrixType , int Mode> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
         {
      RowsAtCompileTime = internal::traits<SparseSymmetricPermutationProduct>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<SparseSymmetricPermutationProduct>::ColsAtCompileTime
    };
Constructor & Destructor Documentation
SparseSymmetricPermutationProduct()
template<typename MatrixType , int Mode> Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::SparseSymmetricPermutationProduct (const MatrixType & mat, const Perm & perm) inline
      : m_matrix(mat), m_perm(perm)
    {}
Member Function Documentation
addTo()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
applyThisOnTheLeft()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
applyThisOnTheRight()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
cols()
template<typename MatrixType , int Mode> Index Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::cols () const inline
{ return m_matrix.cols(); }
const_cast_derived()
EIGEN_DEVICE_FUNC SparseSymmetricPermutationProduct< MatrixType, Mode > & Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
const_derived()
EIGEN_DEVICE_FUNC const SparseSymmetricPermutationProduct< MatrixType, Mode > & Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
EIGEN_DEVICE_FUNC SparseSymmetricPermutationProduct< MatrixType, Mode > & Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::derived () inline inherited
Returns
a reference to the derived object
{ return *static_cast<Derived*>(this); }
derived() [2/2]
EIGEN_DEVICE_FUNC const SparseSymmetricPermutationProduct< MatrixType, Mode > & Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::derived () const inline inherited
Returns
a const reference to the derived object
{ return *static_cast<const Derived*>(this); }
evalTo()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
matrix()
template<typename MatrixType , int Mode> const NestedExpression & Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::matrix () const inline
{ return m_matrix; }
Referenced by Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run(), and Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run().
perm()
template<typename MatrixType , int Mode> const Perm & Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::perm () const inline
{ return m_perm; }
Referenced by Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run(), and Eigen::internal::Assignment< DstXprType, SparseSymmetricPermutationProduct< MatrixType, Mode >, internal::assign_op< Scalar, typename MatrixType::Scalar >, Sparse2Sparse >::run().
rows()
template<typename MatrixType , int Mode> Index Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::rows () const inline
{ return m_matrix.rows(); }
size()
EIGEN_DEVICE_FUNC Index Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
subTo()
EIGEN_DEVICE_FUNC void Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, Mode > >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
Member Data Documentation
m_matrix
template<typename MatrixType , int Mode> MatrixTypeNested Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::m_matrix protected
m_perm
template<typename MatrixType , int Mode> const Perm& Eigen::SparseSymmetricPermutationProduct< MatrixType, Mode >::m_perm protected
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseSelfAdjointView.h