Prusa Slicer: ModeSizer Class Reference
ModeSizer Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
ModeSizer (wxWindow *parent, int hgap=0)
~ModeSizer ()
void SetMode (const int mode)
void set_items_flag (int flag)
void set_items_border (int border)
void sys_color_changed ()
void update_mode_markers ()
const std::vector< ModeButton * > & get_btns ()
Private Attributes
std::vector< ModeButton * > m_mode_btns
double m_hgap_unscaled
Detailed Description
Constructor & Destructor Documentation
ModeSizer()
ModeSizer::ModeSizer (wxWindow * parent, int hgap = 0)
                                                :
    wxFlexGridSizer(3, 0, hgap),
    m_hgap_unscaled((double)(hgap)/em_unit(parent))
{
    SetFlexibleDirection(wxHORIZONTAL);
    auto modebtnfn = [this](wxCommandEvent &event, int mode_id) {
        if (Slic3r::GUI::wxGetApp().save_mode(mode_id))
            event.Skip();
        else
            SetMode(Slic3r::GUI::wxGetApp().get_mode());
    };
    m_mode_btns.reserve(3);
    int mode_id = 0;
    for (const wxString& label : {_L("Simple"), _CTX(L_CONTEXT("Advanced", "Mode"), "Mode"),_L("Expert")}) {
        m_mode_btns.push_back(new ModeButton(parent, mode_id++, label, mode_icon_px_size()));
        m_mode_btns.back()->Bind(wxEVT_BUTTON, std::bind(modebtnfn, std::placeholders::_1, int(m_mode_btns.size() - 1)));
        Add(m_mode_btns.back());
    }
}
References _CTX, _L, L_CONTEXT, m_mode_btns, mode_icon_px_size(), SetMode(), and wxEVT_BUTTON.
~ModeSizer()
ModeSizer::~ModeSizer () inline
{}
Member Function Documentation
get_btns()
const std::vector< ModeButton * > & ModeSizer::get_btns () inline
{ return m_mode_btns; }
References m_mode_btns.
set_items_border()
void ModeSizer::set_items_border (int border)
{
    for (wxSizerItem* item : this->GetChildren())
        item->SetBorder(border);
}
set_items_flag()
void ModeSizer::set_items_flag (int flag)
{
    for (wxSizerItem* item : this->GetChildren())
        item->SetFlag(flag);
}
SetMode()
void ModeSizer::SetMode (const int mode)
{
    for (size_t m = 0; m < m_mode_btns.size(); m++)
        m_mode_btns[m]->SetState(int(m) == mode);
}
References m_mode_btns.
Referenced by ModeSizer().
sys_color_changed()
void ModeSizer::sys_color_changed ()
{
    for (ModeButton* btn : m_mode_btns)
        btn->sys_color_changed();
}
References m_mode_btns.
update_mode_markers()
void ModeSizer::update_mode_markers ()
{
    for (ModeButton* btn : m_mode_btns)
        btn->update_bitmap();
}
References m_mode_btns.
Member Data Documentation
m_hgap_unscaled
double ModeSizer::m_hgap_unscaled private
m_mode_btns
std::vector<ModeButton*> ModeSizer::m_mode_btns private
Referenced by ModeSizer(), get_btns(), SetMode(), sys_color_changed(), and update_mode_markers().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp