Prusa Slicer: Slic3r::DnsName Struct Reference
Slic3r::DnsName Struct Reference
Public Types
enum { MAX_RECURSION = 10 }
Static Public Member Functions
static optional< DnsName > decode (const std::vector< char > &buffer, size_t &offset, unsigned depth=0)
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MAX_RECURSION
  {
    MAX_RECURSION = 10,     // Keep this low
  };
Member Function Documentation
decode()
static optional< DnsName > Slic3r::DnsName::decode (const std::vector< char > & buffer, size_t & offset, unsigned depth = 0) inline static
  {
    // Check offset sanity:
    if (offset + 1 >= buffer.size()) {
      return boost::none;
    }
    // Check for recursion depth to prevent parsing names that are nested too deeply or end up cyclic:
    if (depth >= MAX_RECURSION) {
      return boost::none;
    }
    DnsName res;
    const size_t bsize = buffer.size();
    while (true) {
      const char* ptr = buffer.data() + offset;
      unsigned len = static_cast<unsigned char>(*ptr);
      if (len & 0xc0) {
        // This is a recursive label
        unsigned len_2 = static_cast<unsigned char>(ptr[1]);
        size_t pointer = (len & 0x3f) << 8 | len_2;
        const auto nested = decode(buffer, pointer, depth + 1);
        if (!nested) {
          return boost::none;
        } else {
          if (res.size() > 0) {
            res.push_back('.');
          }
          res.append(*nested);
          offset += 2;
          return std::move(res);
        }
      } else if (len == 0) {
        // This is a name terminator
        offset++;
        break;
      } else {
        // This is a regular label
        len &= 0x3f;
        if (len + offset + 1 >= bsize) {
          return boost::none;
        }
        res.reserve(len);
        if (res.size() > 0) {
          res.push_back('.');
        }
        ptr++;
        for (const auto end = ptr + len; ptr < end; ptr++) {
          char c = *ptr;
          if (c >= 0x20 && c <= 0x7f) {
            res.push_back(c);
          } else {
            return boost::none;
          }
        }
        offset += len + 1;
      }
    }
    if (res.size() > 0) {
      return std::move(res);
    } else {
      return boost::none;
    }
  }
References decode(), MAX_RECURSION, and Slic3r::offset().
Referenced by Slic3r::DnsRR_SRV::decode(), Slic3r::DnsQuestion::decode(), Slic3r::DnsResource::decode(), and decode().
The documentation for this struct was generated from the following file:
src/slic3r/Utils/Bonjour.cpp