Prusa Slicer: Slic3r::GUI::NotificationManager::SlicingProgressNotification Class Reference
Slic3r::GUI::NotificationManager::SlicingProgressNotification Class Reference
Public Types
enum class SlicingProgressState {
SP_NO_SLICING , SP_BEGAN , SP_PROGRESS , SP_CANCELLED ,
SP_COMPLETED
}
enum class EState {
Unknown , Hidden , Shown , NotFading ,
FadingOut , ClosePending , Finished , Hovered ,
Paused
}
Public Member Functions
SlicingProgressNotification (const NotificationData &n, NotificationIDProvider &id_provider, wxEvtHandler *evt_handler, std::function< bool()> callback)
void set_status_text (const std::string &text)
void set_cancel_callback (std::function< bool()> callback)
bool has_cancel_callback () const
bool set_progress_state (float percent)
bool set_progress_state (SlicingProgressState state, float percent=0.f)
void set_print_info (const std::string &info)
void set_sidebar_collapsed (bool collapsed)
bool update_state (bool paused, const int64_t delta) override
void set_fff (bool b)
void set_fdm (bool b)
void set_sla (bool b)
void set_export_possible (bool b)
virtual void set_percentage (float percent)
float get_percentage () const
virtual void render (GLCanvas3D &canvas, float initial_y, bool move_from_overlay, float overlay_width)
virtual void close ()
void update (const NotificationData &n)
bool is_finished () const
float get_top () const
float get_current_top () const
const NotificationType get_type () const
const NotificationData & get_data () const
const bool is_gray () const
void set_gray (bool g)
virtual bool compare_text (const std::string &text) const
void hide (bool h)
int64_t next_render () const
EState get_state () const
bool is_hovered () const
void set_hovered ()
void reset_timer ()
Protected Member Functions
void init () override
void render_text (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override
void render_bar (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override
void render_cancel_button (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override
void render_close_button (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override
void render_hypertext (ImGuiWrapper &imgui, const float text_x, const float text_y, const std::string text, bool more=false) override
void on_cancel_button ()
int get_duration () override
void render_minimize_button (ImGuiWrapper &imgui, const float win_pos_x, const float win_pos_y) override
virtual void set_next_window_size (ImGuiWrapper &imgui)
virtual void render_left_sign (ImGuiWrapper &imgui)
virtual bool on_text_click ()
virtual void on_more_hypertext_click ()
virtual void count_spaces ()
virtual void count_lines ()
virtual bool push_background_color ()
Protected Attributes
std::function< bool()> m_cancel_callback
SlicingProgressState m_sp_state { SlicingProgressState::SP_PROGRESS }
bool m_has_print_info { false }
std::string m_print_info
bool m_sidebar_collapsed { false }
bool m_is_fff { true }
bool m_export_possible { false }
float m_percentage {0.0f}
bool m_has_cancel_button {false}
bool m_render_percentage {false}
const NotificationData m_data
NotificationIDProvider & m_id_provider
int m_id { 0 }
EState m_state { EState::Unknown }
int64_t m_fading_start { 0LL }
int64_t m_notification_start
int64_t m_next_render { std::numeric_limits<int64_t>::max() }
float m_current_fade_opacity { 1.0f }
std::string m_text1
std::string m_hypertext
std::string m_text2
float m_window_width_offset
float m_left_indentation
float m_window_height { 56.0f }
float m_window_width { 450.0f }
float m_top_y { 0.0f }
float m_line_height
std::vector< size_t > m_endlines
std::vector< size_t > m_endlines2
bool m_is_gray { false }
bool m_multiline { false }
bool m_minimize_b_visible { false }
size_t m_lines_count { 1 }
size_t m_normal_lines_count { 2 }
wxEvtHandler * m_evt_handler
Detailed Description
Member Enumeration Documentation
EState
enum class Slic3r::GUI::NotificationManager::PopNotification::EState strong inherited
Enumerator
Unknown
Hidden
Shown
NotFading
FadingOut
ClosePending
Finished
Hovered
Paused
    {
      Unknown,      // NOT initialized
      Hidden,
      Shown,        // Requesting Render at some time if duration != 0
      NotFading,      // Never jumps to state Fading out even if duration says so
      FadingOut,        // Requesting Render at some time
      ClosePending,     // Requesting Render
      Finished,         // Requesting Render
      Hovered,      // Followed by Shown
      Paused
    };
SlicingProgressState
enum class Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState strong
Enumerator
SP_NO_SLICING
SP_BEGAN
SP_PROGRESS
SP_CANCELLED
SP_COMPLETED
    {
      SP_NO_SLICING, // hidden
      SP_BEGAN, // still hidden but allows to go to SP_PROGRESS state. This prevents showing progress after slicing was canceled.
      SP_PROGRESS, // never fades outs, no close button, has cancel button
      SP_CANCELLED, // fades after 10 seconds, simple message
      SP_COMPLETED // Has export hyperlink and print info, fades after 20 sec if sidebar is shown, otherwise no fade out
    };
Constructor & Destructor Documentation
SlicingProgressNotification()
Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressNotification (const NotificationData & n, NotificationIDProvider & id_provider, wxEvtHandler * evt_handler, std::function< bool()> callback) inline
    : ProgressBarNotification(n, id_provider, evt_handler)
    , m_cancel_callback(callback)
    {
      set_progress_state(SlicingProgressState::SP_NO_SLICING);
      m_has_cancel_button = false;
      m_render_percentage = true;
    }
References Slic3r::GUI::NotificationManager::ProgressBarNotification::m_has_cancel_button, Slic3r::GUI::NotificationManager::ProgressBarNotification::m_render_percentage, set_progress_state(), and SP_NO_SLICING.
Member Function Documentation
close()
virtual void Slic3r::GUI::NotificationManager::PopNotification::close () inline virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::PlaterWarningNotification, and Slic3r::GUI::NotificationManager::UpdatedItemsInfoNotification.
{ m_state = EState::ClosePending; wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);}
References Slic3r::GUI::NotificationManager::PopNotification::ClosePending, and Slic3r::GUI::NotificationManager::PopNotification::m_state.
Referenced by Slic3r::GUI::NotificationManager::UpdatedItemsInfoNotification::close(), and Slic3r::GUI::NotificationManager::set_download_URL_canceled().
compare_text()
bool Slic3r::GUI::NotificationManager::PopNotification::compare_text (const std::string & text) const virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::URLDownloadNotification, and Slic3r::GUI::NotificationManager::PrintHostUploadNotification.
{
  std::wstring wt1 = boost::nowide::widen(m_text1);
  std::wstring wt2 = boost::nowide::widen(text);
  wt1.erase(std::remove_if(wt1.begin(), wt1.end(), ::iswspace), wt1.end());
  wt2.erase(std::remove_if(wt2.begin(), wt2.end(), ::iswspace), wt2.end());
  if (wt1.compare(wt2) == 0)
    return true;
  return false;
}
References boost::nowide::widen().
count_lines()
void Slic3r::GUI::NotificationManager::PopNotification::count_lines () protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::HintNotification.
{
  std::string text    = m_text1;
  size_t      last_end  = 0;
  m_lines_count     = 0;
  if (text.empty())
    return;
  m_endlines.clear();
  while (last_end < text.length() - 1)
  {
    size_t next_hard_end = text.find_first_of('\n', last_end);
    if (next_hard_end != std::string::npos && ImGui::CalcTextSize(text.substr(last_end, next_hard_end - last_end).c_str()).x < m_window_width - m_window_width_offset) {
      //next line is ended by '/n'
      m_endlines.push_back(next_hard_end);
      last_end = next_hard_end + 1;
    }
    else {
      // find next suitable endline
      if (ImGui::CalcTextSize(text.substr(last_end).c_str()).x >= m_window_width - m_window_width_offset) {
        // more than one line till end
        size_t next_space = text.find_first_of(' ', last_end);
        if (next_space > 0 && next_space < text.length()) {
                    size_t next_space_candidate = text.find_first_of(' ', next_space + 1);
          while (next_space_candidate > 0 && ImGui::CalcTextSize(text.substr(last_end, next_space_candidate - last_end).c_str()).x < m_window_width - m_window_width_offset) {
            next_space = next_space_candidate;
            next_space_candidate = text.find_first_of(' ', next_space + 1);
          }
        } else {
          next_space = text.length();
        }
        // when one word longer than line.
        if (ImGui::CalcTextSize(text.substr(last_end, next_space - last_end).c_str()).x > m_window_width - m_window_width_offset ||
          ImGui::CalcTextSize(text.substr(last_end, next_space - last_end).c_str()).x < (m_window_width - m_window_width_offset) / 4 * 3
          ) {
          float width_of_a = ImGui::CalcTextSize("a").x;
          int letter_count = (int)((m_window_width - m_window_width_offset) / width_of_a);
          while (last_end + letter_count < text.size() && ImGui::CalcTextSize(text.substr(last_end, letter_count).c_str()).x < m_window_width - m_window_width_offset) {
            letter_count += get_utf8_sequence_length(text, last_end + letter_count);
          }
          m_endlines.push_back(last_end + letter_count);
          last_end += letter_count;
        } else {
          m_endlines.push_back(next_space);
          last_end = next_space + 1;
        }
      }
      else {
        m_endlines.push_back(text.length());
        last_end = text.length();
      }
    }
    m_lines_count++;
  }
  // original hypertext calculation (when there was no text2)
  /*
  if (!m_hypertext.empty()) {
    int prev_end = m_endlines.size() > 1 ? m_endlines[m_endlines.size() - 2] : 0; // m_endlines.size() - 2 because we are fitting hypertext instead of last endline
    if (ImGui::CalcTextSize((escape_string_cstyle(text.substr(prev_end, last_end - prev_end)) + m_hypertext).c_str()).x > m_window_width - m_window_width_offset) {
      m_endlines.push_back(last_end);
      m_lines_count++;
    }
  }
  */
  int prev_end = m_endlines.size() > 1 ? m_endlines[m_endlines.size() - 2] : 0;
  int size_of_last_line = ImGui::CalcTextSize(text.substr(prev_end, last_end - prev_end).c_str()).x;
  // hypertext calculation
  if (!m_hypertext.empty()) {
    if (size_of_last_line + ImGui::CalcTextSize(m_hypertext.c_str()).x > m_window_width - m_window_width_offset) {
      // hypertext on new line
      size_of_last_line = ImGui::CalcTextSize((m_hypertext + "  ").c_str()).x;
      m_endlines.push_back(last_end);
      m_lines_count++;
    }
    else {
      size_of_last_line += ImGui::CalcTextSize((m_hypertext + "  ").c_str()).x;
    }
  }
  // text after hypertext calculation
  if (!m_text2.empty()) {
    text = m_text2;
    last_end = 0;
    m_endlines2.clear();
    // if size_of_last_line too large to fit anything
    size_t first_end = std::min(text.find_first_of('\n'), text.find_first_of(' '));
    if (size_of_last_line >= m_window_width - m_window_width_offset - ImGui::CalcTextSize(text.substr(0, first_end).c_str()).x) {
      m_endlines2.push_back(0);
      size_of_last_line = 0;
    }
    while (last_end < text.length() - 1)
    {
      size_t next_hard_end = text.find_first_of('\n', last_end);
      if (next_hard_end != std::string::npos && ImGui::CalcTextSize(text.substr(last_end, next_hard_end - last_end).c_str()).x < m_window_width - m_window_width_offset - size_of_last_line) {
        //next line is ended by '/n'
        m_endlines2.push_back(next_hard_end);
        last_end = next_hard_end + 1;
      }
      else {
        // find next suitable endline
        if (ImGui::CalcTextSize(text.substr(last_end).c_str()).x >= m_window_width - m_window_width_offset - size_of_last_line) {
          // more than one line till end
          size_t next_space = text.find_first_of(' ', last_end);
          if (next_space > 0) {
            size_t next_space_candidate = text.find_first_of(' ', next_space + 1);
            while (next_space_candidate > 0 && ImGui::CalcTextSize(text.substr(last_end, next_space_candidate - last_end).c_str()).x < m_window_width - m_window_width_offset - size_of_last_line) {
              next_space = next_space_candidate;
              next_space_candidate = text.find_first_of(' ', next_space + 1);
            }
          }
          else {
            next_space = text.length();
          }
          // when one word longer than line.
          if (ImGui::CalcTextSize(text.substr(last_end, next_space - last_end).c_str()).x > m_window_width - m_window_width_offset - size_of_last_line ||
            ImGui::CalcTextSize(text.substr(last_end, next_space - last_end).c_str()).x + size_of_last_line < (m_window_width - m_window_width_offset) / 5 * 3
            ) {
            float width_of_a = ImGui::CalcTextSize("a").x;
            int letter_count = (int)((m_window_width - m_window_width_offset - size_of_last_line) / width_of_a);
            while (last_end + letter_count < text.size() && ImGui::CalcTextSize(text.substr(last_end, letter_count).c_str()).x < m_window_width - m_window_width_offset - size_of_last_line) {
              letter_count += get_utf8_sequence_length(text, last_end + letter_count);
            }
            m_endlines2.push_back(last_end + letter_count);
            last_end += letter_count;
          }
          else {
            m_endlines2.push_back(next_space);
            last_end = next_space + 1;
          }
        }
        else {
          m_endlines2.push_back(text.length());
          last_end = text.length();
        }
      }
      if (size_of_last_line == 0) // if first line is continuation of previous text, do not add to line count.
        m_lines_count++;
      size_of_last_line = 0; // should countain value only for first line (with hypertext)
    }
  }
}
References ImGui::CalcTextSize(), Slic3r::get_utf8_sequence_length(), and ImVec2::x.
count_spaces()
void Slic3r::GUI::NotificationManager::PopNotification::count_spaces () protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::HintNotification, Slic3r::GUI::NotificationManager::URLDownloadNotification, Slic3r::GUI::NotificationManager::PrintHostUploadNotification, Slic3r::GUI::NotificationManager::ExportFinishedNotification, and Slic3r::GUI::NotificationManager::UpdatedItemsInfoNotification.
{
  //determine line width
  m_line_height = ImGui::CalcTextSize("A").y;
  m_left_indentation = m_line_height;
  if (m_data.level == NotificationLevel::ErrorNotificationLevel
    || m_data.level == NotificationLevel::WarningNotificationLevel
    || m_data.level == NotificationLevel::PrintInfoNotificationLevel
    || m_data.level == NotificationLevel::PrintInfoShortNotificationLevel) {
    std::string text;
    text = (m_data.level == NotificationLevel::ErrorNotificationLevel ? ImGui::ErrorMarker : ImGui::WarningMarker);
    float picture_width = ImGui::CalcTextSize(text.c_str()).x;
    m_left_indentation = picture_width + m_line_height / 2;
  }
  m_window_width_offset = m_left_indentation + m_line_height * 3.f;
  m_window_width = m_line_height * 25;
}
References ImGui::CalcTextSize(), ImGui::ErrorMarker, Slic3r::GUI::NotificationManager::ErrorNotificationLevel, Slic3r::GUI::NotificationManager::PrintInfoNotificationLevel, Slic3r::GUI::NotificationManager::PrintInfoShortNotificationLevel, ImGui::WarningMarker, Slic3r::GUI::NotificationManager::WarningNotificationLevel, ImVec2::x, and ImVec2::y.
Referenced by Slic3r::GUI::NotificationManager::URLDownloadNotification::count_spaces(), and Slic3r::GUI::NotificationManager::ExportFinishedNotification::count_spaces().
get_current_top()
float Slic3r::GUI::NotificationManager::PopNotification::get_current_top () const inline inherited
{ return m_top_y; }
References Slic3r::GUI::NotificationManager::PopNotification::m_top_y.
get_data()
const NotificationData & Slic3r::GUI::NotificationManager::PopNotification::get_data () const inline inherited
{ return m_data; }
References Slic3r::GUI::NotificationManager::PopNotification::m_data.
Referenced by Slic3r::GUI::NotificationManager::activate_existing().
get_duration()
int Slic3r::GUI::NotificationManager::SlicingProgressNotification::get_duration () override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::PopNotification.
{
  if (m_sp_state == SlicingProgressState::SP_CANCELLED)
    return 2;
  else if (m_sp_state == SlicingProgressState::SP_COMPLETED && !m_sidebar_collapsed)
    return 2;
  else
    return 0;
}
get_percentage()
float Slic3r::GUI::NotificationManager::ProgressBarNotification::get_percentage () const inline inherited
{ return m_percentage; }
References Slic3r::GUI::NotificationManager::ProgressBarNotification::m_percentage.
Referenced by Slic3r::GUI::NotificationManager::set_download_progress_percentage(), Slic3r::GUI::NotificationManager::set_download_URL_error(), and Slic3r::GUI::NotificationManager::set_download_URL_progress().
get_state()
EState Slic3r::GUI::NotificationManager::PopNotification::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::NotificationManager::PopNotification::m_state.
get_top()
float Slic3r::GUI::NotificationManager::PopNotification::get_top () const inline inherited
{ return m_top_y; }
References Slic3r::GUI::NotificationManager::PopNotification::m_top_y.
get_type()
const NotificationType Slic3r::GUI::NotificationManager::PopNotification::get_type () const inline inherited
{ return m_data.type; }
References Slic3r::GUI::NotificationManager::PopNotification::m_data, and Slic3r::GUI::NotificationManager::NotificationData::type.
Referenced by Slic3r::GUI::NotificationManager::activate_existing().
has_cancel_callback()
bool Slic3r::GUI::NotificationManager::SlicingProgressNotification::has_cancel_callback () const inline
{ return m_cancel_callback != nullptr; }
References m_cancel_callback.
hide()
void Slic3r::GUI::NotificationManager::PopNotification::hide (bool h) inline inherited
{ if (is_finished()) return; m_state = h ? EState::Hidden : EState::Unknown; }
References Slic3r::GUI::NotificationManager::PopNotification::Hidden, Slic3r::GUI::NotificationManager::PopNotification::is_finished(), Slic3r::GUI::NotificationManager::PopNotification::m_state, and Slic3r::GUI::NotificationManager::PopNotification::Unknown.
init()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::init () override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::ProgressBarNotification.
{
  if (m_sp_state == SlicingProgressState::SP_PROGRESS) {
    ProgressBarNotification::init();
    //if (m_state == EState::NotFading && m_percentage >= 1.0f)
    //  m_state = EState::Shown;
  }
  else {
    PopNotification::init();
  }
}
References Slic3r::GUI::NotificationManager::PopNotification::init(), and Slic3r::GUI::NotificationManager::ProgressBarNotification::init().
is_finished()
bool Slic3r::GUI::NotificationManager::PopNotification::is_finished () const inline inherited
{ return m_state == EState::ClosePending || m_state == EState::Finished; }
References Slic3r::GUI::NotificationManager::PopNotification::ClosePending, Slic3r::GUI::NotificationManager::PopNotification::Finished, and Slic3r::GUI::NotificationManager::PopNotification::m_state.
Referenced by Slic3r::GUI::NotificationManager::PlaterWarningNotification::close(), Slic3r::GUI::NotificationManager::PopNotification::hide(), and Slic3r::GUI::NotificationManager::PopNotification::next_render().
is_gray()
const bool Slic3r::GUI::NotificationManager::PopNotification::is_gray () const inline inherited
{ return m_is_gray; }
References Slic3r::GUI::NotificationManager::PopNotification::m_is_gray.
is_hovered()
bool Slic3r::GUI::NotificationManager::PopNotification::is_hovered () const inline inherited
{ return m_state == EState::Hovered; }
References Slic3r::GUI::NotificationManager::PopNotification::Hovered, and Slic3r::GUI::NotificationManager::PopNotification::m_state.
next_render()
int64_t Slic3r::GUI::NotificationManager::PopNotification::next_render () const inline inherited
{ return is_finished() ? 0 : m_next_render; }
References Slic3r::GUI::NotificationManager::PopNotification::is_finished(), and Slic3r::GUI::NotificationManager::PopNotification::m_next_render.
on_cancel_button()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::on_cancel_button () protected
{
  if (m_cancel_callback){
    if (!m_cancel_callback()) {
      set_progress_state(SlicingProgressState::SP_NO_SLICING);
    }
  }
}
on_more_hypertext_click()
void Slic3r::GUI::NotificationManager::PopNotification::on_more_hypertext_click () protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification.
{
  m_multiline = true;
}
Referenced by Slic3r::GUI::NotificationManager::PrintHostUploadNotification::on_more_hypertext_click().
on_text_click()
bool Slic3r::GUI::NotificationManager::PopNotification::on_text_click () protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::HintNotification, and Slic3r::GUI::NotificationManager::ExportFinishedNotification.
{
  if(m_data.callback != nullptr)
    return m_data.callback(m_evt_handler);
  return false;
}
References Slic3r::GUI::NotificationManager::m_evt_handler.
push_background_color()
bool Slic3r::GUI::NotificationManager::PopNotification::push_background_color () protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification.
{
  if (m_is_gray) {
    ImVec4 backcolor(0.7f, 0.7f, 0.7f, 0.5f);
    push_style_color(ImGuiCol_WindowBg, backcolor, m_state == EState::FadingOut, m_current_fade_opacity);
    return true;
  }
  if (m_data.level == NotificationLevel::ErrorNotificationLevel) {
    ImVec4 backcolor = ImGui::GetStyleColorVec4(ImGuiCol_WindowBg);
    backcolor.x += 0.3f;
    push_style_color(ImGuiCol_WindowBg, backcolor, m_state == EState::FadingOut, m_current_fade_opacity);
    return true;
  }
  if (m_data.level == NotificationLevel::WarningNotificationLevel) {
    ImVec4 backcolor = ImGui::GetStyleColorVec4(ImGuiCol_WindowBg);
    backcolor.x += 0.3f;
    backcolor.y += 0.15f;
    push_style_color(ImGuiCol_WindowBg, backcolor, m_state == EState::FadingOut, m_current_fade_opacity);
    return true;
  }
  return false;
}
References Slic3r::GUI::NotificationManager::ErrorNotificationLevel, ImGui::GetStyleColorVec4(), ImGuiCol_WindowBg, Slic3r::GUI::NotificationManager::WarningNotificationLevel, ImVec4::x, and ImVec4::y.
render()
void Slic3r::GUI::NotificationManager::PopNotification::render (GLCanvas3D & canvas, float initial_y, bool move_from_overlay, float overlay_width) virtual inherited
{
  if (m_state == EState::Unknown)
    init();
  if (m_state == EState::Hidden) {
    m_top_y = initial_y - GAP_WIDTH;
    return;
  }
  if (m_state == EState::ClosePending || m_state == EState::Finished)
  {
    m_state = EState::Finished;
    return;
  }
  Size          cnv_size = canvas.get_canvas_size();
  ImGuiWrapper& imgui = *wxGetApp().imgui();
  ImVec2        mouse_pos = ImGui::GetMousePos();
  float         right_gap = SPACE_RIGHT_PANEL + (move_from_overlay ? overlay_width + m_line_height * 5 : 0);
  bool          fading_pop = false;
  if (m_line_height != ImGui::CalcTextSize("A").y)
    init();
  set_next_window_size(imgui);
  // top y of window
  m_top_y = initial_y + m_window_height;
  ImVec2 win_pos(1.0f * (float)cnv_size.get_width() - right_gap, 1.0f * (float)cnv_size.get_height() - m_top_y);
  imgui.set_next_window_pos(win_pos.x, win_pos.y, ImGuiCond_Always, 1.0f, 0.0f);
  imgui.set_next_window_size(m_window_width, m_window_height, ImGuiCond_Always);
  // find if hovered FIXME:  do it only in update state?
  if (m_state == EState::Hovered) {
    m_state = EState::Unknown;
    init();
  }
  if (mouse_pos.x < win_pos.x && mouse_pos.x > win_pos.x - m_window_width && mouse_pos.y > win_pos.y && mouse_pos.y < win_pos.y + m_window_height) {
    // Uncomment if imgui window focus is needed on hover. I cant find any case.
    //ImGui::SetNextWindowFocus();
    set_hovered();
  }
  // color change based on fading out
  if (m_state == EState::FadingOut) {
    push_style_color(ImGuiCol_WindowBg, ImGui::GetStyleColorVec4(ImGuiCol_WindowBg), true, m_current_fade_opacity);
    push_style_color(ImGuiCol_Text, ImGui::GetStyleColorVec4(ImGuiCol_Text), true, m_current_fade_opacity);
    push_style_color(ImGuiCol_ButtonHovered, ImGui::GetStyleColorVec4(ImGuiCol_ButtonHovered), true, m_current_fade_opacity);
    fading_pop = true;
  }
  bool bgrnd_color_pop = push_background_color();
  // name of window indentifies window - has to be unique string
  if (m_id == 0)
    m_id = m_id_provider.allocate_id();
  std::string name = "!!Ntfctn" + std::to_string(m_id);
  int flags = ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar |
                ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize |
                ImGuiWindowFlags_NoScrollbar |
                ImGuiWindowFlags_NoScrollWithMouse |
                ImGuiWindowFlags_NoFocusOnAppearing;
  if (imgui.begin(name, flags)) {
    ImVec2 win_size = ImGui::GetWindowSize();
    render_left_sign(imgui);
    render_text(imgui, win_size.x, win_size.y, win_pos.x, win_pos.y);
    render_close_button(imgui, win_size.x, win_size.y, win_pos.x, win_pos.y);
    m_minimize_b_visible = false;
    if (m_multiline && m_lines_count > 3)
      render_minimize_button(imgui, win_pos.x, win_pos.y);
  }
  imgui.end();
  if (bgrnd_color_pop)
    ImGui::PopStyleColor();
  if (fading_pop)
    ImGui::PopStyleColor(3);
}
References Slic3r::GUI::NotificationManager::NotificationIDProvider::allocate_id(), Slic3r::GUI::ImGuiWrapper::begin(), ImGui::CalcTextSize(), Slic3r::GUI::ImGuiWrapper::end(), GAP_WIDTH, Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), ImGui::GetMousePos(), ImGui::GetStyleColorVec4(), ImGui::GetWindowSize(), ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiCol_WindowBg, ImGuiCond_Always, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoFocusOnAppearing, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoScrollWithMouse, ImGuiWindowFlags_NoTitleBar, Slic3r::GUI::NotificationManager::init(), Slic3r::GUI::NotificationManager::m_id_provider, ImGui::PopStyleColor(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::ImGuiWrapper::set_next_window_size(), SPACE_RIGHT_PANEL, ImVec2::x, and ImVec2::y.
render_bar()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_bar (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::ProgressBarNotification.
{
  if (m_sp_state != SlicingProgressState::SP_PROGRESS) {
    return;
  }
  ProgressBarNotification::render_bar(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
}
References Slic3r::GUI::NotificationManager::ProgressBarNotification::render_bar().
render_cancel_button()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_cancel_button (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::ProgressBarNotification.
{
  ImVec2 win_size(win_size_x, win_size_y);
  ImVec2 win_pos(win_pos_x, win_pos_y);
  ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(.0f, .0f, .0f, .0f));
  ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(.0f, .0f, .0f, .0f));
  push_style_color(ImGuiCol_Text, ImVec4(1.f, 1.f, 1.f, 1.f), m_state == EState::FadingOut, m_current_fade_opacity);
  push_style_color(ImGuiCol_TextSelectedBg, ImVec4(0, .75f, .75f, 1.f), m_state == EState::FadingOut, m_current_fade_opacity);
  ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(.0f, .0f, .0f, .0f));
  std::string button_text;
  button_text = ImGui::CancelButton;
  if (ImGui::IsMouseHoveringRect(ImVec2(win_pos.x - win_size.x / 10.f, win_pos.y),
    ImVec2(win_pos.x, win_pos.y + win_size.y - (m_minimize_b_visible ? 2 * m_line_height : 0)),
    true))
  {
    button_text = ImGui::CancelHoverButton;
  }
  ImVec2 button_pic_size = ImGui::CalcTextSize(button_text.c_str());
  ImVec2 button_size(button_pic_size.x * 1.25f, button_pic_size.y * 1.25f);
  ImGui::SetCursorPosX(win_size.x - m_line_height * 2.75f);
  ImGui::SetCursorPosY(win_size.y / 2 - button_size.y);
  if (imgui.button(button_text.c_str(), button_size.x, button_size.y))
  {
    on_cancel_button();
  }
  //invisible large button
  ImGui::SetCursorPosX(win_size.x - m_line_height * 2.35f);
  ImGui::SetCursorPosY(0);
  if (imgui.button(" ", m_line_height * 2.125, win_size.y - (m_minimize_b_visible ? 2 * m_line_height : 0)))
  {
    on_cancel_button();
  }
  ImGui::PopStyleColor();
  ImGui::PopStyleColor();
  ImGui::PopStyleColor();
  ImGui::PopStyleColor();
  ImGui::PopStyleColor();
}
References Slic3r::GUI::ImGuiWrapper::button(), ImGui::CalcTextSize(), ImGui::CancelButton, ImGui::CancelHoverButton, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiCol_TextSelectedBg, ImGui::IsMouseHoveringRect(), ImGui::PopStyleColor(), ImGui::PushStyleColor(), ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), ImVec2::x, and ImVec2::y.
render_close_button()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_close_button (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::PopNotification.
{
  // Do not render close button while showing progress - cancel button is rendered instead
  if (m_sp_state != SlicingProgressState::SP_PROGRESS) {
    ProgressBarNotification::render_close_button(imgui, win_size_x,  win_size_y, win_pos_x, win_pos_y);
  }
}
References Slic3r::GUI::NotificationManager::PopNotification::render_close_button().
render_hypertext()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_hypertext (ImGuiWrapper & imgui, const float text_x, const float text_y, const std::string text, bool more = false) override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::PopNotification.
{
  if (m_sp_state == SlicingProgressState::SP_COMPLETED && !m_sidebar_collapsed)
    return;
  ProgressBarNotification::render_hypertext(imgui, text_x, text_y, text, more);
}
References Slic3r::GUI::NotificationManager::PopNotification::render_hypertext().
render_left_sign()
void Slic3r::GUI::NotificationManager::PopNotification::render_left_sign (ImGuiWrapper & imgui) protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification.
{
  if (m_data.level == NotificationLevel::ErrorNotificationLevel || m_data.level == NotificationLevel::WarningNotificationLevel) {
    std::string text;
    text = (m_data.level == NotificationLevel::ErrorNotificationLevel ? ImGui::ErrorMarker : ImGui::WarningMarker);
    ImGui::SetCursorPosX(m_line_height / 3);
    ImGui::SetCursorPosY(m_window_height / 2 - m_line_height);
    imgui.text(text.c_str());
  } else if (m_data.level == NotificationLevel::PrintInfoNotificationLevel || m_data.level == NotificationLevel::PrintInfoShortNotificationLevel) {
    std::wstring text;
    text = ImGui::InfoMarker;
    ImGui::SetCursorPosX(m_line_height / 3);
    ImGui::SetCursorPosY(m_window_height / 2 - m_line_height);
    imgui.text(text.c_str());
  }
}
References ImGui::ErrorMarker, Slic3r::GUI::NotificationManager::ErrorNotificationLevel, ImGui::InfoMarker, Slic3r::GUI::NotificationManager::PrintInfoNotificationLevel, Slic3r::GUI::NotificationManager::PrintInfoShortNotificationLevel, ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), Slic3r::GUI::ImGuiWrapper::text(), ImGui::WarningMarker, and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
render_minimize_button()
void Slic3r::GUI::NotificationManager::ProgressBarNotification::render_minimize_button (ImGuiWrapper & imgui, const float win_pos_x, const float win_pos_y) inline override protected virtual inherited
Reimplemented from Slic3r::GUI::NotificationManager::PopNotification.
                                                             {}
render_text()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_text (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::ProgressBarNotification.
{
  if (m_sp_state == SlicingProgressState::SP_PROGRESS /*|| (m_sp_state == SlicingProgressState::SP_COMPLETED && !m_sidebar_collapsed)*/) {
    ProgressBarNotification::render_text(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
    /* // enable for hypertext during slicing (correct call of export_enabled needed)
    if (m_multiline) {
      // two lines text, one line bar
      ImGui::SetCursorPosX(m_left_indentation);
      ImGui::SetCursorPosY(m_line_height / 4);
      imgui.text(m_text1.substr(0, m_endlines[0]).c_str());
      ImGui::SetCursorPosX(m_left_indentation);
      ImGui::SetCursorPosY(m_line_height + m_line_height / 4);
      std::string line = m_text1.substr(m_endlines[0] + (m_text1[m_endlines[0]] == '\n' || m_text1[m_endlines[0]] == ' ' ? 1 : 0), m_endlines[1] - m_endlines[0] - (m_text1[m_endlines[0]] == '\n' || m_text1[m_endlines[0]] == ' ' ? 1 : 0));
      imgui.text(line.c_str());
      if (m_sidebar_collapsed && m_sp_state == SlicingProgressState::SP_PROGRESS && m_export_possible) {
        ImVec2 text_size = ImGui::CalcTextSize(line.c_str());
        render_hypertext(imgui, m_left_indentation + text_size.x + 4, m_line_height + m_line_height / 4, m_hypertext);
      }
      if (m_has_cancel_button)
        render_cancel_button(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
      render_bar(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
    }
    else {
      //one line text, one line bar
      ImGui::SetCursorPosX(m_left_indentation);
      ImGui::SetCursorPosY(m_line_height / 4);
      std::string line = m_text1.substr(0, m_endlines[0]);
      imgui.text(line.c_str());
      if (m_sidebar_collapsed && m_sp_state == SlicingProgressState::SP_PROGRESS && m_export_possible) {
        ImVec2 text_size = ImGui::CalcTextSize(line.c_str());
        render_hypertext(imgui, m_left_indentation + text_size.x + 4, m_line_height / 4, m_hypertext);
      }
      if (m_has_cancel_button)
        render_cancel_button(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
      render_bar(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
    }
    */
  } else if (m_sp_state == SlicingProgressState::SP_COMPLETED && m_sidebar_collapsed) {
    // "Slicing Finished" on line 1 + hypertext, print info on line
    ImVec2 win_size(win_size_x, win_size_y);
    ImVec2 text1_size = ImGui::CalcTextSize(m_text1.c_str());
    float x_offset = m_left_indentation;
    std::string fulltext = m_text1 + m_hypertext + m_text2;
    ImVec2 text_size = ImGui::CalcTextSize(fulltext.c_str());
    float cursor_y = win_size.y / 2 - text_size.y / 2;
    if (m_sidebar_collapsed && m_has_print_info) {
      x_offset = 20;
      cursor_y = win_size.y / 2 + win_size.y / 6 - text_size.y / 2;
      ImGui::SetCursorPosX(x_offset);
      ImGui::SetCursorPosY(cursor_y);
      imgui.text(m_print_info.c_str());
      cursor_y = win_size.y / 2 - win_size.y / 6 - text_size.y / 2;
    }
    ImGui::SetCursorPosX(x_offset);
    ImGui::SetCursorPosY(cursor_y);
    imgui.text(m_text1.c_str());
    if (m_sidebar_collapsed)
      render_hypertext(imgui, x_offset + text1_size.x + 4, cursor_y, m_hypertext);
  } else {
    PopNotification::render_text(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
  }
}
References ImGui::CalcTextSize(), Slic3r::GUI::NotificationManager::PopNotification::render_text(), Slic3r::GUI::NotificationManager::ProgressBarNotification::render_text(), ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), Slic3r::GUI::ImGuiWrapper::text(), ImVec2::x, and ImVec2::y.
reset_timer()
void Slic3r::GUI::NotificationManager::PopNotification::reset_timer () inline inherited
{ m_notification_start = GLCanvas3D::timestamp_now(); m_state = EState::Shown; }
References Slic3r::GUI::NotificationManager::PopNotification::m_notification_start, Slic3r::GUI::NotificationManager::PopNotification::m_state, Slic3r::GUI::NotificationManager::PopNotification::Shown, and Slic3r::GUI::GLCanvas3D::timestamp_now().
set_cancel_callback()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_cancel_callback (std::function< bool()> callback) inline
{ m_cancel_callback = callback; }
References m_cancel_callback.
set_export_possible()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_export_possible (bool b) inline
{ m_export_possible = b; }
References m_export_possible.
set_fdm()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_fdm (bool b) inline
{ m_is_fff = b; }
References m_is_fff.
set_fff()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_fff (bool b) inline
{ m_is_fff = b; }
References m_is_fff.
set_gray()
void Slic3r::GUI::NotificationManager::PopNotification::set_gray (bool g) inline inherited
{ m_is_gray = g; }
References Slic3r::GUI::NotificationManager::PopNotification::m_is_gray.
set_hovered()
void Slic3r::GUI::NotificationManager::PopNotification::set_hovered () inline inherited
{ if (m_state != EState::Finished && m_state != EState::ClosePending && m_state != EState::Hidden && m_state != EState::Unknown) m_state = EState::Hovered; }
References Slic3r::GUI::NotificationManager::PopNotification::ClosePending, Slic3r::GUI::NotificationManager::PopNotification::Finished, Slic3r::GUI::NotificationManager::PopNotification::Hidden, Slic3r::GUI::NotificationManager::PopNotification::Hovered, Slic3r::GUI::NotificationManager::PopNotification::m_state, and Slic3r::GUI::NotificationManager::PopNotification::Unknown.
set_next_window_size()
void Slic3r::GUI::NotificationManager::PopNotification::set_next_window_size (ImGuiWrapper & imgui) protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::HintNotification.
{
  m_window_height = m_multiline ?
    std::max(m_lines_count, m_normal_lines_count) * m_line_height :
    m_normal_lines_count * m_line_height;
  m_window_height += 1 * m_line_height; // top and bottom
}
set_percentage()
virtual void Slic3r::GUI::NotificationManager::ProgressBarNotification::set_percentage (float percent) inline virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::ProgressBarWithCancelNotification, Slic3r::GUI::NotificationManager::URLDownloadNotification, Slic3r::GUI::NotificationManager::PrintHostUploadNotification, and Slic3r::GUI::NotificationManager::ProgressIndicatorNotification.
{ m_percentage = percent; }
References Slic3r::GUI::NotificationManager::ProgressBarNotification::m_percentage.
Referenced by Slic3r::GUI::NotificationManager::ProgressIndicatorNotification::set_percentage().
set_print_info()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_print_info (const std::string & info)
{
  if (m_sp_state != SlicingProgressState::SP_COMPLETED) {
    set_progress_state (SlicingProgressState::SP_COMPLETED);
  } else {
    m_has_print_info = true;
    m_print_info = info;
  }
}
set_progress_state() [1/2]
bool Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_progress_state (float percent)
{
  if (percent < 0.f)
    return true;//set_progress_state(SlicingProgressState::SP_CANCELLED);
  else if (percent >= 1.f)
    return set_progress_state(SlicingProgressState::SP_COMPLETED);
  else
    return set_progress_state(SlicingProgressState::SP_PROGRESS, percent);
}
Referenced by SlicingProgressNotification(), Slic3r::GUI::NotificationManager::set_slicing_progress_began(), Slic3r::GUI::NotificationManager::set_slicing_progress_canceled(), Slic3r::GUI::NotificationManager::set_slicing_progress_hidden(), and Slic3r::GUI::NotificationManager::set_slicing_progress_percentage().
set_progress_state() [2/2]
bool Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_progress_state (SlicingProgressState state, float percent = 0.f)
{
  switch (state)
  {
  case Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState::SP_NO_SLICING:
  case Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState::SP_BEGAN:
    m_state = EState::Hidden;
    set_percentage(-1);
    m_has_print_info = false;
    set_export_possible(false);
    m_sp_state = state;
    return true;
  case Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState::SP_PROGRESS:
    if ((m_sp_state != SlicingProgressState::SP_BEGAN && m_sp_state != SlicingProgressState::SP_PROGRESS) || percent < m_percentage)
      return false;
    set_percentage(percent);
    m_has_cancel_button = true;
    m_sp_state = state;
    return true;
  case Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState::SP_CANCELLED:
    set_percentage(-1);
    m_has_cancel_button = false;
    m_has_print_info = false;
    set_export_possible(false);
    m_sp_state = state;
    return true;
  case Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState::SP_COMPLETED:
    if (m_sp_state != SlicingProgressState::SP_BEGAN && m_sp_state != SlicingProgressState::SP_PROGRESS)
      return false;
    set_percentage(1);
    m_has_cancel_button = false;
    m_has_print_info = false;
    // m_export_possible is important only for SP_PROGRESS state, thus we can reset it here
    set_export_possible(false);
    m_sp_state = state;
    return true;
  default:
    break;
  }
  return false;
}
References SP_BEGAN, SP_CANCELLED, SP_COMPLETED, SP_NO_SLICING, and SP_PROGRESS.
set_sidebar_collapsed()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_sidebar_collapsed (bool collapsed)
{
  m_sidebar_collapsed = collapsed;
  if (m_sp_state == SlicingProgressState::SP_COMPLETED && collapsed)
    m_state = EState::NotFading;
}
set_sla()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_sla (bool b) inline
{ m_is_fff = !b; }
References m_is_fff.
set_status_text()
void Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_status_text (const std::string & text)
{
  switch (m_sp_state)
  {
  case Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState::SP_NO_SLICING:
    m_state = EState::Hidden;
    break;
  case Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState::SP_PROGRESS:
  {
    NotificationData data{ NotificationType::SlicingProgress, NotificationLevel::ProgressBarNotificationLevel, 0, text + "." };
    update(data);
    m_state = EState::NotFading;
  }
    break;
  case Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState::SP_CANCELLED:
  {
    NotificationData data{ NotificationType::SlicingProgress, NotificationLevel::ProgressBarNotificationLevel, 0, text };
    update(data);
    m_state = EState::Shown;
  }
    break;
  case Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressState::SP_COMPLETED:
  {
    NotificationData data{ NotificationType::SlicingProgress, NotificationLevel::ProgressBarNotificationLevel, 0,  _u8L("Slicing finished."), m_is_fff ? _u8L("Export G-Code.") : _u8L("Export.") };
    update(data);
    m_state = EState::Shown;
  }
    break;
  default:
    break;
  }
}
References _u8L, Slic3r::GUI::NotificationManager::ProgressBarNotificationLevel, Slic3r::GUI::SlicingProgress, SP_CANCELLED, SP_COMPLETED, SP_NO_SLICING, and SP_PROGRESS.
Referenced by Slic3r::GUI::NotificationManager::set_slicing_progress_canceled(), and Slic3r::GUI::NotificationManager::set_slicing_progress_percentage().
update()
void Slic3r::GUI::NotificationManager::PopNotification::update (const NotificationData & n) inherited
{
  m_text1          = n.text1;
  m_hypertext      = n.hypertext;
    m_text2          = n.text2;
  init();
}
References Slic3r::GUI::NotificationManager::NotificationData::hypertext, Slic3r::GUI::NotificationManager::init(), Slic3r::GUI::NotificationManager::NotificationData::text1, and Slic3r::GUI::NotificationManager::NotificationData::text2.
update_state()
bool Slic3r::GUI::NotificationManager::SlicingProgressNotification::update_state (bool paused, const int64_t delta) override virtual
Reimplemented from Slic3r::GUI::NotificationManager::PopNotification.
{
  bool ret = ProgressBarNotification::update_state(paused, delta);
  // sets Estate to hidden
  if (get_state() == PopNotification::EState::ClosePending || get_state() == PopNotification::EState::Finished)
    set_progress_state(SlicingProgressState::SP_NO_SLICING);
  return ret;
}
References Slic3r::GUI::NotificationManager::PopNotification::ClosePending, Slic3r::GUI::NotificationManager::PopNotification::Finished, and Slic3r::GUI::NotificationManager::PopNotification::update_state().
Member Data Documentation
m_cancel_callback
std::function<bool()> Slic3r::GUI::NotificationManager::SlicingProgressNotification::m_cancel_callback protected
Referenced by has_cancel_callback(), and set_cancel_callback().
m_current_fade_opacity
float Slic3r::GUI::NotificationManager::PopNotification::m_current_fade_opacity { 1.0f } protected inherited
m_data
const NotificationData Slic3r::GUI::NotificationManager::PopNotification::m_data protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::get_data(), Slic3r::GUI::NotificationManager::PopNotification::get_duration(), and Slic3r::GUI::NotificationManager::PopNotification::get_type().
m_endlines
std::vector<size_t> Slic3r::GUI::NotificationManager::PopNotification::m_endlines protected inherited
m_endlines2
std::vector<size_t> Slic3r::GUI::NotificationManager::PopNotification::m_endlines2 protected inherited
m_evt_handler
wxEvtHandler* Slic3r::GUI::NotificationManager::PopNotification::m_evt_handler protected inherited
m_export_possible
bool Slic3r::GUI::NotificationManager::SlicingProgressNotification::m_export_possible { false } protected
Referenced by set_export_possible().
m_fading_start
int64_t Slic3r::GUI::NotificationManager::PopNotification::m_fading_start { 0LL } protected inherited
m_has_cancel_button
bool Slic3r::GUI::NotificationManager::ProgressBarNotification::m_has_cancel_button {false} protected inherited
Referenced by Slic3r::GUI::NotificationManager::PrintHostUploadNotification::PrintHostUploadNotification(), SlicingProgressNotification(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::cancel(), and Slic3r::GUI::NotificationManager::PrintHostUploadNotification::error().
m_has_print_info
bool Slic3r::GUI::NotificationManager::SlicingProgressNotification::m_has_print_info { false } protected
m_hypertext
std::string Slic3r::GUI::NotificationManager::PopNotification::m_hypertext protected inherited
m_id
int Slic3r::GUI::NotificationManager::PopNotification::m_id { 0 } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::~PopNotification().
m_id_provider
NotificationIDProvider& Slic3r::GUI::NotificationManager::PopNotification::m_id_provider protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::~PopNotification().
m_is_fff
bool Slic3r::GUI::NotificationManager::SlicingProgressNotification::m_is_fff { true } protected
Referenced by set_fdm(), set_fff(), and set_sla().
m_is_gray
bool Slic3r::GUI::NotificationManager::PopNotification::m_is_gray { false } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::is_gray(), and Slic3r::GUI::NotificationManager::PopNotification::set_gray().
m_left_indentation
float Slic3r::GUI::NotificationManager::PopNotification::m_left_indentation protected inherited
Referenced by Slic3r::GUI::NotificationManager::HintNotification::count_spaces().
m_line_height
float Slic3r::GUI::NotificationManager::PopNotification::m_line_height protected inherited
Referenced by Slic3r::GUI::NotificationManager::HintNotification::count_spaces().
m_lines_count
size_t Slic3r::GUI::NotificationManager::PopNotification::m_lines_count { 1 } protected inherited
m_minimize_b_visible
bool Slic3r::GUI::NotificationManager::PopNotification::m_minimize_b_visible { false } protected inherited
Referenced by Slic3r::GUI::NotificationManager::ExportFinishedNotification::render_minimize_button().
m_multiline
bool Slic3r::GUI::NotificationManager::PopNotification::m_multiline { false } protected inherited
Referenced by Slic3r::GUI::NotificationManager::ExportFinishedNotification::ExportFinishedNotification().
m_next_render
int64_t Slic3r::GUI::NotificationManager::PopNotification::m_next_render { std::numeric_limits<int64_t>::max() } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::next_render().
m_normal_lines_count
size_t Slic3r::GUI::NotificationManager::PopNotification::m_normal_lines_count { 2 } protected inherited
m_notification_start
int64_t Slic3r::GUI::NotificationManager::PopNotification::m_notification_start protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::reset_timer(), and Slic3r::GUI::NotificationManager::URLDownloadNotification::set_percentage().
m_percentage
float Slic3r::GUI::NotificationManager::ProgressBarNotification::m_percentage {0.0f} protected inherited
Referenced by Slic3r::GUI::NotificationManager::ProgressBarNotification::get_percentage(), Slic3r::GUI::NotificationManager::ProgressBarNotification::set_percentage(), Slic3r::GUI::NotificationManager::ProgressBarWithCancelNotification::set_percentage(), and Slic3r::GUI::NotificationManager::URLDownloadNotification::set_percentage().
m_print_info
std::string Slic3r::GUI::NotificationManager::SlicingProgressNotification::m_print_info protected
m_render_percentage
bool Slic3r::GUI::NotificationManager::ProgressBarNotification::m_render_percentage {false} protected inherited
Referenced by Slic3r::GUI::NotificationManager::ProgressIndicatorNotification::ProgressIndicatorNotification(), and SlicingProgressNotification().
m_sidebar_collapsed
bool Slic3r::GUI::NotificationManager::SlicingProgressNotification::m_sidebar_collapsed { false } protected
m_sp_state
SlicingProgressState Slic3r::GUI::NotificationManager::SlicingProgressNotification::m_sp_state { SlicingProgressState::SP_PROGRESS } protected
m_state
EState Slic3r::GUI::NotificationManager::PopNotification::m_state { EState::Unknown } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::close(), Slic3r::GUI::NotificationManager::PlaterWarningNotification::close(), Slic3r::GUI::NotificationManager::PopNotification::get_state(), Slic3r::GUI::NotificationManager::PopNotification::hide(), Slic3r::GUI::NotificationManager::PopNotification::is_finished(), Slic3r::GUI::NotificationManager::PopNotification::is_hovered(), Slic3r::GUI::NotificationManager::PlaterWarningNotification::real_close(), Slic3r::GUI::NotificationManager::PopNotification::reset_timer(), Slic3r::GUI::NotificationManager::PopNotification::set_hovered(), Slic3r::GUI::NotificationManager::ProgressBarWithCancelNotification::set_percentage(), Slic3r::GUI::NotificationManager::URLDownloadNotification::set_percentage(), and Slic3r::GUI::NotificationManager::PlaterWarningNotification::show().
m_text1
std::string Slic3r::GUI::NotificationManager::PopNotification::m_text1 protected inherited
m_text2
std::string Slic3r::GUI::NotificationManager::PopNotification::m_text2 protected inherited
m_top_y
float Slic3r::GUI::NotificationManager::PopNotification::m_top_y { 0.0f } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::get_current_top(), and Slic3r::GUI::NotificationManager::PopNotification::get_top().
m_window_height
float Slic3r::GUI::NotificationManager::PopNotification::m_window_height { 56.0f } protected inherited
m_window_width
float Slic3r::GUI::NotificationManager::PopNotification::m_window_width { 450.0f } protected inherited
Referenced by Slic3r::GUI::NotificationManager::HintNotification::count_spaces().
m_window_width_offset
float Slic3r::GUI::NotificationManager::PopNotification::m_window_width_offset protected inherited
Referenced by Slic3r::GUI::NotificationManager::HintNotification::count_spaces().
The documentation for this class was generated from the following files:
src/slic3r/GUI/NotificationManager.hpp
src/slic3r/GUI/NotificationManager.cpp