Prusa Slicer: Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse > Struct Template Reference
Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse > Struct Template Reference
#include <src/eigen/Eigen/src/SparseCore/SparseAssign.h>
Public Types
typedef DstXprType::StorageIndex StorageIndex
typedef DstXprType::Scalar Scalar
typedef Array< StorageIndex, Dynamic, 1 > ArrayXI
typedef Array< Scalar, Dynamic, 1 > ArrayXS
Static Public Member Functions
template<int Options>
static void run (SparseMatrix< Scalar, Options, StorageIndex > &dst, const SrcXprType &src, const internal::assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
template<typename DstDerived >
static void run (SparseMatrixBase< DstDerived > &dst, const SrcXprType &src, const internal::assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
static void run (DstXprType &dst, const SrcXprType &src, const internal::add_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
static void run (DstXprType &dst, const SrcXprType &src, const internal::sub_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
Detailed Description
template<typename DstXprType, typename SrcXprType, typename Functor>
struct Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >
Member Typedef Documentation
ArrayXI
template<typename DstXprType , typename SrcXprType , typename Functor > typedef Array<StorageIndex,Dynamic,1> Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::ArrayXI
ArrayXS
template<typename DstXprType , typename SrcXprType , typename Functor > typedef Array<Scalar,Dynamic,1> Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::ArrayXS
Scalar
template<typename DstXprType , typename SrcXprType , typename Functor > typedef DstXprType::Scalar Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::Scalar
StorageIndex
template<typename DstXprType , typename SrcXprType , typename Functor > typedef DstXprType::StorageIndex Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::StorageIndex
Member Function Documentation
run() [1/4]
template<typename DstXprType , typename SrcXprType , typename Functor > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run (DstXprType & dst, const SrcXprType & src, const internal::add_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
  { dst.diagonal() += src.diagonal(); }
run() [2/4]
template<typename DstXprType , typename SrcXprType , typename Functor > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run (DstXprType & dst, const SrcXprType & src, const internal::sub_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
  { dst.diagonal() -= src.diagonal(); }
run() [3/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<int Options> static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run (SparseMatrix< Scalar, Options, StorageIndex > & dst, const SrcXprType & src, const internal::assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
  {
    Index dstRows = src.rows();
    Index dstCols = src.cols();
    if((dst.rows()!=dstRows) || (dst.cols()!=dstCols))
      dst.resize(dstRows, dstCols);
    Index size = src.diagonal().size();
    dst.makeCompressed();
    dst.resizeNonZeros(size);
    Map<ArrayXI>(dst.innerIndexPtr(), size).setLinSpaced(0,StorageIndex(size)-1);
    Map<ArrayXI>(dst.outerIndexPtr(), size+1).setLinSpaced(0,StorageIndex(size));
    Map<ArrayXS>(dst.valuePtr(), size) = src.diagonal();
  }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resizeNonZeros(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
run() [4/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DstDerived > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run (SparseMatrixBase< DstDerived > & dst, const SrcXprType & src, const internal::assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
  {
    dst.diagonal() = src.diagonal();
  }
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseAssign.h