Prusa Slicer: Slic3r::SurfaceCollection Class Reference
Slic3r::SurfaceCollection Class Reference
#include <src/libslic3r/SurfaceCollection.hpp>
Public Member Functions
SurfaceCollection ()=default
SurfaceCollection (const Surfaces &surfaces)
SurfaceCollection (Surfaces &&surfaces)
void simplify (double tolerance)
void group (std::vector< SurfacesPtr > *retval) const
template<class T >
bool any_internal_contains (const T &item) const
template<class T >
bool any_bottom_contains (const T &item) const
SurfacesPtr filter_by_type (const SurfaceType type) const
SurfacesPtr filter_by_types (std::initializer_list< SurfaceType > types) const
void keep_type (const SurfaceType type)
void keep_types (std::initializer_list< SurfaceType > types)
void remove_type (const SurfaceType type)
void remove_types (std::initializer_list< SurfaceType > types)
void filter_by_type (SurfaceType type, Polygons *polygons) const
void remove_type (const SurfaceType type, ExPolygons *polygons)
void set_type (SurfaceType type)
void clear ()
bool empty () const
size_t size () const
bool has (SurfaceType type) const
Surfaces::const_iterator cbegin () const
Surfaces::const_iterator cend () const
Surfaces::const_iterator begin () const
Surfaces::const_iterator end () const
Surfaces::iterator begin ()
Surfaces::iterator end ()
void set (const SurfaceCollection &coll)
void set (SurfaceCollection &&coll)
void set (const ExPolygons &src, SurfaceType surfaceType)
void set (const ExPolygons &src, const Surface &surfaceTempl)
void set (const Surfaces &src)
void set (ExPolygons &&src, SurfaceType surfaceType)
void set (ExPolygons &&src, const Surface &surfaceTempl)
void set (Surfaces &&src)
void append (const SurfaceCollection &coll)
void append (SurfaceCollection &&coll)
void append (const ExPolygons &src, SurfaceType surfaceType)
void append (const ExPolygons &src, const Surface &surfaceTempl)
void append (const Surfaces &src)
void append (ExPolygons &&src, SurfaceType surfaceType)
void append (ExPolygons &&src, const Surface &surfaceTempl)
void append (Surfaces &&src)
void export_to_svg (const char *path, bool show_labels)
Public Attributes
Surfaces surfaces
Detailed Description
Constructor & Destructor Documentation
SurfaceCollection() [1/3]
Slic3r::SurfaceCollection::SurfaceCollection () default
SurfaceCollection() [2/3]
Slic3r::SurfaceCollection::SurfaceCollection (const Surfaces & surfaces) inline
: surfaces(surfaces) {};
SurfaceCollection() [3/3]
Slic3r::SurfaceCollection::SurfaceCollection (Surfaces && surfaces) inline
: surfaces(std::move(surfaces)) {};
Member Function Documentation
any_bottom_contains()
template<class T > bool Slic3r::SurfaceCollection::any_bottom_contains (const T & item) const inline
{
        for (const Surface &surface : this->surfaces) if (surface.is_bottom() && surface.expolygon.contains(item)) return true;
        return false;
    }
References surfaces.
any_internal_contains()
template<class T > bool Slic3r::SurfaceCollection::any_internal_contains (const T & item) const inline
{
        for (const Surface &surface : this->surfaces) if (surface.is_internal() && surface.expolygon.contains(item)) return true;
        return false;
    }
References surfaces.
append() [1/8]
void Slic3r::SurfaceCollection::append (const ExPolygons & src, const Surface & surfaceTempl) inline
{ surfaces_append(this->surfaces, src, surfaceTempl); }
References Slic3r::surfaces_append().
append() [2/8]
void Slic3r::SurfaceCollection::append (const ExPolygons & src, SurfaceType surfaceType) inline
{ surfaces_append(this->surfaces, src, surfaceType); }
References Slic3r::surfaces_append().
append() [3/8]
void Slic3r::SurfaceCollection::append (const SurfaceCollection & coll) inline
{ this->append(coll.surfaces); }
References append(), and surfaces.
Referenced by append(), Slic3r::PrintObject::discover_vertical_shells(), Slic3r::Layer::make_perimeters(), set(), set(), set(), set(), set(), set(), and Slic3r::LayerRegion::slices_to_fill_surfaces_clipped().
append() [4/8]
void Slic3r::SurfaceCollection::append (const Surfaces & src) inline
{ surfaces_append(this->surfaces, src); }
References Slic3r::surfaces_append().
append() [5/8]
void Slic3r::SurfaceCollection::append (ExPolygons && src, const Surface & surfaceTempl) inline
{ surfaces_append(this->surfaces, std::move(src), surfaceTempl); }
References Slic3r::surfaces_append().
append() [6/8]
void Slic3r::SurfaceCollection::append (ExPolygons && src, SurfaceType surfaceType) inline
{ surfaces_append(this->surfaces, std::move(src), surfaceType); }
References Slic3r::surfaces_append().
append() [7/8]
void Slic3r::SurfaceCollection::append (SurfaceCollection && coll) inline
{ this->append(std::move(coll.surfaces)); }
References append().
Referenced by append().
append() [8/8]
void Slic3r::SurfaceCollection::append (Surfaces && src) inline
{ surfaces_append(this->surfaces, std::move(src)); }
References Slic3r::surfaces_append().
begin() [1/2]
Surfaces::iterator Slic3r::SurfaceCollection::begin () inline
{ return this->surfaces.begin(); }
begin() [2/2]
Surfaces::const_iterator Slic3r::SurfaceCollection::begin () const inline
{ return this->surfaces.cbegin(); }
cbegin()
Surfaces::const_iterator Slic3r::SurfaceCollection::cbegin () const inline
{ return this->surfaces.cbegin(); }
cend()
Surfaces::const_iterator Slic3r::SurfaceCollection::cend () const inline
{ return this->surfaces.cend(); }
clear()
void Slic3r::SurfaceCollection::clear () inline
{ surfaces.clear(); }
References surfaces.
Referenced by set(), set(), set(), set(), set(), and set().
empty()
bool Slic3r::SurfaceCollection::empty () const inline
{ return surfaces.empty(); }
References surfaces.
Referenced by Slic3r::get_extents(), and Slic3r::Layer::make_ironing().
end() [1/2]
Surfaces::iterator Slic3r::SurfaceCollection::end () inline
{ return this->surfaces.end(); }
end() [2/2]
Surfaces::const_iterator Slic3r::SurfaceCollection::end () const inline
{ return this->surfaces.cend(); }
export_to_svg()
void Slic3r::SurfaceCollection::export_to_svg (const char * path, bool show_labels)
{
    BoundingBox bbox;
    for (Surfaces::const_iterator surface = this->surfaces.begin(); surface != this->surfaces.end(); ++surface)
        bbox.merge(get_extents(surface->expolygon));
    Point legend_size = export_surface_type_legend_to_svg_box_size();
    Point legend_pos(bbox.min(0), bbox.max(1));
    bbox.merge(Point(std::max(bbox.min(0) + legend_size(0), bbox.max(0)), bbox.max(1) + legend_size(1)));
    SVG svg(path, bbox);
    const float transparency = 0.5f;
    for (Surfaces::const_iterator surface = this->surfaces.begin(); surface != this->surfaces.end(); ++surface) {
        svg.draw(surface->expolygon, surface_type_to_color_name(surface->surface_type), transparency);
        if (show_labels) {
            int idx = int(surface - this->surfaces.begin());
            char label[64];
            sprintf(label, "%d", idx);
            svg.draw_text(surface->expolygon.contour.points.front(), label, "black");
        }
    }
    export_surface_type_legend_to_svg(svg, legend_pos);
    svg.Close();
}
References Slic3r::SVG::Close(), Slic3r::SVG::draw(), Slic3r::SVG::draw_text(), Slic3r::export_surface_type_legend_to_svg(), Slic3r::export_surface_type_legend_to_svg_box_size(), Slic3r::get_extents(), Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::merge(), Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::surface_type_to_color_name(), and surfaces.
Referenced by Slic3r::LayerRegion::process_external_surfaces().
filter_by_type() [1/2]
SurfacesPtr Slic3r::SurfaceCollection::filter_by_type (const SurfaceType type) const
{
    SurfacesPtr ss;
    for (const Surface &surface : this->surfaces)
        if (surface.surface_type == type)
            ss.push_back(&surface);
    return ss;
}
References surfaces.
Referenced by Slic3r::PrintObject::discover_vertical_shells().
filter_by_type() [2/2]
void Slic3r::SurfaceCollection::filter_by_type (SurfaceType type, Polygons * polygons) const
{
    for (const Surface &surface : this->surfaces)
        if (surface.surface_type == type)
            polygons_append(*polygons, to_polygons(surface.expolygon));
}
References Slic3r::polygons_append(), surfaces, and Slic3r::to_polygons().
filter_by_types()
SurfacesPtr Slic3r::SurfaceCollection::filter_by_types (std::initializer_list< SurfaceType > types) const
{
    SurfacesPtr ss;
    for (const Surface &surface : this->surfaces)
        if (std::find(types.begin(), types.end(), surface.surface_type) != types.end())
            ss.push_back(&surface);
    return ss;
}
References surfaces.
Referenced by Slic3r::PrintObject::discover_vertical_shells().
group()
void Slic3r::SurfaceCollection::group (std::vector< SurfacesPtr > * retval) const
{
    for (const Surface &surface : this->surfaces) {
        // find a group with the same properties
        SurfacesPtr *group = nullptr;
        for (std::vector<SurfacesPtr>::iterator git = retval->begin(); git != retval->end(); ++git)
            if (! git->empty() && surfaces_could_merge(*git->front(), surface)) {
                group = &*git;
                break;
            }
        // if no group with these properties exists, add one
        if (group == nullptr) {
            retval->resize(retval->size() + 1);
            group = &retval->back();
        }
        // append surface to group
        group->push_back(&surface);
    }
}
References group(), surfaces, and Slic3r::surfaces_could_merge().
Referenced by group().
has()
bool Slic3r::SurfaceCollection::has (SurfaceType type) const inline
{
        for (const Surface &surface : this->surfaces)
            if (surface.surface_type == type) return true;
        return false;
    }
References surfaces.
keep_type()
void Slic3r::SurfaceCollection::keep_type (const SurfaceType type)
{
    size_t j = 0;
    for (size_t i = 0; i < surfaces.size(); ++ i) {
        if (surfaces[i].surface_type == type) {
            if (j < i)
                std::swap(surfaces[i], surfaces[j]);
            ++ j;
        }
    }
    if (j < surfaces.size())
        surfaces.erase(surfaces.begin() + j, surfaces.end());
}
References surfaces.
keep_types()
void Slic3r::SurfaceCollection::keep_types (std::initializer_list< SurfaceType > types)
{
    size_t j = 0;
    for (size_t i = 0; i < surfaces.size(); ++ i)
        if (std::find(types.begin(), types.end(), surfaces[i].surface_type) != types.end()) {
            if (j < i)
                std::swap(surfaces[i], surfaces[j]);
            ++ j;
        }
    if (j < surfaces.size())
        surfaces.erase(surfaces.begin() + j, surfaces.end());
}
References surfaces.
Referenced by Slic3r::PrintObject::discover_vertical_shells().
remove_type() [1/2]
void Slic3r::SurfaceCollection::remove_type (const SurfaceType type)
{
    size_t j = 0;
    for (size_t i = 0; i < surfaces.size(); ++ i) {
        if (surfaces[i].surface_type != type) {
            if (j < i)
                std::swap(surfaces[i], surfaces[j]);
            ++ j;
        }
    }
    if (j < surfaces.size())
        surfaces.erase(surfaces.begin() + j, surfaces.end());
}
References surfaces.
remove_type() [2/2]
void Slic3r::SurfaceCollection::remove_type (const SurfaceType type, ExPolygons * polygons)
{
    size_t j = 0;
    for (size_t i = 0; i < surfaces.size(); ++ i) {
        if (Surface &surface = surfaces[i]; surface.surface_type == type) {
            polygons->emplace_back(std::move(surface.expolygon));
        } else {
            if (j < i)
                std::swap(surfaces[i], surfaces[j]);
            ++ j;
        }
    }
    if (j < surfaces.size())
        surfaces.erase(surfaces.begin() + j, surfaces.end());
}
References surfaces.
remove_types()
void Slic3r::SurfaceCollection::remove_types (std::initializer_list< SurfaceType > types)
{
    size_t j = 0;
    for (size_t i = 0; i < surfaces.size(); ++ i)
        if (std::find(types.begin(), types.end(), surfaces[i].surface_type) == types.end()) {
            if (j < i)
                std::swap(surfaces[i], surfaces[j]);
            ++ j;
        }
    if (j < surfaces.size())
        surfaces.erase(surfaces.begin() + j, surfaces.end());
}
References surfaces.
set() [1/8]
void Slic3r::SurfaceCollection::set (const ExPolygons & src, const Surface & surfaceTempl) inline
{ clear(); this->append(src, surfaceTempl); }
References append(), and clear().
set() [2/8]
void Slic3r::SurfaceCollection::set (const ExPolygons & src, SurfaceType surfaceType) inline
{ clear(); this->append(src, surfaceType); }
References append(), and clear().
set() [3/8]
void Slic3r::SurfaceCollection::set (const SurfaceCollection & coll) inline
{ surfaces = coll.surfaces; }
References surfaces.
Referenced by Slic3r::Layer::restore_untyped_slices_no_extra_perimeters().
set() [4/8]
void Slic3r::SurfaceCollection::set (const Surfaces & src) inline
{ clear(); this->append(src); }
References append(), and clear().
set() [5/8]
void Slic3r::SurfaceCollection::set (ExPolygons && src, const Surface & surfaceTempl) inline
{ clear(); this->append(std::move(src), surfaceTempl); }
References append(), and clear().
set() [6/8]
void Slic3r::SurfaceCollection::set (ExPolygons && src, SurfaceType surfaceType) inline
{ clear(); this->append(std::move(src), surfaceType); }
References append(), and clear().
set() [7/8]
void Slic3r::SurfaceCollection::set (SurfaceCollection && coll) inline
{ surfaces = std::move(coll.surfaces); }
References surfaces.
set() [8/8]
void Slic3r::SurfaceCollection::set (Surfaces && src) inline
{ clear(); this->append(std::move(src)); }
References append(), and clear().
set_type()
void Slic3r::SurfaceCollection::set_type (SurfaceType type) inline
{
      for (Surface &surface : this->surfaces)
        surface.surface_type = type;
    }
References surfaces.
simplify()
void Slic3r::SurfaceCollection::simplify (double tolerance)
{
    Surfaces ss;
    for (Surfaces::const_iterator it_s = this->surfaces.begin(); it_s != this->surfaces.end(); ++it_s) {
        ExPolygons expp;
        it_s->expolygon.simplify(tolerance, &expp);
        for (ExPolygons::const_iterator it_e = expp.begin(); it_e != expp.end(); ++it_e) {
            Surface s = *it_s;
            s.expolygon = *it_e;
            ss.push_back(s);
        }
    }
    this->surfaces = ss;
}
References Slic3r::Surface::expolygon, and surfaces.
size()
size_t Slic3r::SurfaceCollection::size () const inline
{ return surfaces.size(); }
References surfaces.
Referenced by Slic3r::group_fills(), Slic3r::LayerRegion::make_perimeters(), Slic3r::LayerRegion::process_external_surfaces(), and Slic3r::Layer::sort_perimeters_into_islands().
Member Data Documentation
surfaces
Surfaces Slic3r::SurfaceCollection::surfaces
Referenced by any_bottom_contains(), any_internal_contains(), append(), clear(), Slic3r::detect_overhangs(), Slic3r::PrintObject::detect_surfaces_type(), Slic3r::PrintObject::discover_horizontal_shells(), empty(), export_to_svg(), filter_by_type(), filter_by_type(), filter_by_types(), Slic3r::get_extents(), group(), Slic3r::group_fills(), has(), keep_type(), keep_types(), Slic3r::Layer::make_perimeters(), Slic3r::LayerRegion::process_external_surfaces(), remove_type(), remove_type(), remove_types(), set(), set(), set_type(), simplify(), size(), Slic3r::LayerRegion::slices_to_fill_surfaces_clipped(), and Slic3r::Layer::sort_perimeters_into_islands().
The documentation for this class was generated from the following files:
src/libslic3r/SurfaceCollection.hpp
src/libslic3r/SurfaceCollection.cpp