Prusa Slicer: Slic3r::GCode::GCodeOutputStream Class Reference
Slic3r::GCode::GCodeOutputStream Class Reference
Public Member Functions
GCodeOutputStream (FILE *f, GCodeProcessor &processor)
~GCodeOutputStream ()
void set_find_replace (GCodeFindReplace *find_replace, bool enabled)
void find_replace_enable ()
void find_replace_supress ()
bool is_open () const
bool is_error () const
void flush ()
void close ()
void write (const std::string &what)
void write (const char *what)
void writeln (const std::string &what)
void write_format (const char *format,...)
Private Attributes
FILE * f { nullptr }
GCodeFindReplace * m_find_replace { nullptr }
GCodeFindReplace * m_find_replace_backup { nullptr }
GCodeProcessor & m_processor
Detailed Description
Constructor & Destructor Documentation
GCodeOutputStream()
Slic3r::GCode::GCodeOutputStream::GCodeOutputStream (FILE * f, GCodeProcessor & processor) inline
: f(f), m_processor(processor) {}
~GCodeOutputStream()
Slic3r::GCode::GCodeOutputStream::~GCodeOutputStream () inline
{ this->close(); }
References close().
Member Function Documentation
close()
void Slic3r::GCode::GCodeOutputStream::close ()
{
    if (this->f) {
        ::fclose(this->f);
        this->f = nullptr;
    }
}
References Slic3r::f().
Referenced by ~GCodeOutputStream(), and Slic3r::GCode::do_export().
find_replace_enable()
void Slic3r::GCode::GCodeOutputStream::find_replace_enable () inline
{ m_find_replace = m_find_replace_backup; }
References m_find_replace, and m_find_replace_backup.
Referenced by Slic3r::GCode::_do_export().
find_replace_supress()
void Slic3r::GCode::GCodeOutputStream::find_replace_supress () inline
{ m_find_replace = nullptr; }
References m_find_replace.
Referenced by Slic3r::GCode::_do_export().
flush()
void Slic3r::GCode::GCodeOutputStream::flush ()
{
    ::fflush(this->f);
}
References Slic3r::f().
Referenced by Slic3r::GCode::do_export().
is_error()
bool Slic3r::GCode::GCodeOutputStream::is_error () const
{
    return ::ferror(this->f);
}
References f.
Referenced by Slic3r::GCode::do_export().
is_open()
bool Slic3r::GCode::GCodeOutputStream::is_open () const inline
{ return f; }
References f.
Referenced by Slic3r::GCode::do_export().
set_find_replace()
void Slic3r::GCode::GCodeOutputStream::set_find_replace (GCodeFindReplace * find_replace, bool enabled) inline
{ m_find_replace_backup = find_replace; m_find_replace = enabled ? find_replace : nullptr; }
References m_find_replace, and m_find_replace_backup.
Referenced by Slic3r::GCode::_do_export().
write() [1/2]
void Slic3r::GCode::GCodeOutputStream::write (const char * what)
{
    if (what != nullptr) {
        //FIXME don't allocate a string, maybe process a batch of lines?
        std::string gcode(m_find_replace ? m_find_replace->process_layer(what) : what);
        // writes string to file
        fwrite(gcode.c_str(), 1, gcode.size(), this->f);
        m_processor.process_buffer(gcode);
    }
}
References Slic3r::GCode::m_find_replace, Slic3r::GCode::m_processor, and Slic3r::GCodeProcessor::process_buffer().
write() [2/2]
void Slic3r::GCode::GCodeOutputStream::write (const std::string & what) inline
{ this->write(what.c_str()); }
References write().
Referenced by Slic3r::GCode::_do_export(), Slic3r::GCode::_print_first_layer_bed_temperature(), Slic3r::GCode::_print_first_layer_extruder_temperatures(), and write().
write_format()
void Slic3r::GCode::GCodeOutputStream::write_format (const char * format, ...)
{
    va_list args;
    va_start(args, format);
    int buflen;
    {
        va_list args2;
        va_copy(args2, args);
        buflen =
    #ifdef _MSC_VER
            ::_vscprintf(format, args2)
    #else
            ::vsnprintf(nullptr, 0, format, args2)
    #endif
            + 1;
        va_end(args2);
    }
    char buffer[1024];
    bool buffer_dynamic = buflen > 1024;
    char *bufptr = buffer_dynamic ? (char*)malloc(buflen) : buffer;
    int res = ::vsnprintf(bufptr, buflen, format, args);
    if (res > 0)
        this->write(bufptr);
    if (buffer_dynamic)
        free(bufptr);
    va_end(args);
}
References Slic3r::format(), free(), malloc(), and va_copy.
Referenced by Slic3r::GCode::_do_export(), and Slic3r::GCode::print_machine_envelope().
writeln()
void Slic3r::GCode::GCodeOutputStream::writeln (const std::string & what)
{
    if (! what.empty())
        this->write(what.back() == '\n' ? what : what + '\n');
}
Referenced by Slic3r::GCode::_do_export().
Member Data Documentation
f
FILE* Slic3r::GCode::GCodeOutputStream::f { nullptr } private
Referenced by is_error(), and is_open().
m_find_replace
GCodeFindReplace* Slic3r::GCode::GCodeOutputStream::m_find_replace { nullptr } private
Referenced by find_replace_enable(), find_replace_supress(), and set_find_replace().
m_find_replace_backup
GCodeFindReplace* Slic3r::GCode::GCodeOutputStream::m_find_replace_backup { nullptr } private
Referenced by find_replace_enable(), and set_find_replace().
m_processor
GCodeProcessor& Slic3r::GCode::GCodeOutputStream::m_processor private
The documentation for this class was generated from the following files:
src/libslic3r/GCode.hpp
src/libslic3r/GCode.cpp