Prusa Slicer: src/slic3r/GUI/Gizmos/GLGizmoEmboss.cpp File Reference
GLGizmoEmboss.cpp File Reference
#include "GLGizmoEmboss.hpp"
#include "slic3r/GUI/GLCanvas3D.hpp"
#include "slic3r/GUI/GUI_App.hpp"
#include "slic3r/GUI/GUI_ObjectList.hpp"
#include "slic3r/GUI/GUI_ObjectManipulation.hpp"
#include "slic3r/GUI/MainFrame.hpp"
#include "slic3r/GUI/NotificationManager.hpp"
#include "slic3r/GUI/Plater.hpp"
#include "slic3r/GUI/MsgDialog.hpp"
#include "slic3r/GUI/format.hpp"
#include "slic3r/GUI/CameraUtils.hpp"
#include "slic3r/GUI/Jobs/EmbossJob.hpp"
#include "slic3r/GUI/Jobs/CreateFontNameImageJob.hpp"
#include "slic3r/GUI/Jobs/NotificationProgressIndicator.hpp"
#include "slic3r/Utils/WxFontUtils.hpp"
#include "slic3r/Utils/UndoRedo.hpp"
#include "libslic3r/SVG.hpp"
#include "libslic3r/Geometry.hpp"
#include "libslic3r/Timer.hpp"
#include "libslic3r/NSVGUtils.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/Preset.hpp"
#include "libslic3r/ClipperUtils.hpp"
#include "libslic3r/AppConfig.hpp"
#include "libslic3r/Format/OBJ.hpp"
#include "libslic3r/BuildVolume.hpp"
#include "imgui/imgui_stdlib.h"
#include "nanosvg/nanosvg.h"
#include <wx/font.h>
#include <wx/fontutil.h>
#include <wx/fontdlg.h>
#include <wx/fontenum.h>
#include <wx/display.h>
#include <boost/log/trivial.hpp>
#include <GL/glew.h>
#include <chrono>
#include "imgui/imgui_internal.h"
#include <boost/functional/hash.hpp>
#include "wx/hashmap.h"
#include <boost/filesystem.hpp>
#include <cereal/cereal.hpp>
#include <cereal/types/vector.hpp>
#include <cereal/types/string.hpp>
#include <cereal/archives/binary.hpp>
#include <boost/nowide/fstream.hpp>
Classes
struct priv::MinMax< T >
struct priv::Limit< T >
struct priv::Limits
struct FacenamesSerializer
Namespaces
namespace priv
namespace anonymous_namespace{GLGizmoEmboss.cpp}
Macros
#define FACENAMES_VERSION 1
Enumerations
enum class priv::IconType : unsigned {
priv::rename = 0 , priv::erase , priv::add , priv::save ,
priv::undo , priv::italic , priv::unitalic , priv::bold ,
priv::unbold , priv::system_selector , priv::open_file , priv::exclamation ,
priv::lock , priv::lock_bold , priv::unlock , priv::unlock_bold ,
priv::_count
}
enum class priv::IconState : unsigned { priv::activable = 0 , priv::hovered , priv::disabled }
Functions
template<typename T >
void priv::to_range_pi_pi (T &angle)
static DataBase priv::create_emboss_data_base (const std::string &text, StyleManager &style_manager, std::shared_ptr< std::atomic< bool > > &cancel)
Prepare data for emboss.
static void priv::start_create_volume_job (const ModelObject *object, const Transform3d volume_trmat, DataBase &emboss_data, ModelVolumeType volume_type)
Start job for add new volume to object with given transformation.
static bool priv::start_create_volume_on_surface_job (DataBase &emboss_data, ModelVolumeType volume_type, const Vec2d &screen_coor, const GLVolume *gl_volume, RaycastManager &raycaster, GLCanvas3D &canvas)
Start job for add new volume on surface of object defined by screen coor.
static void priv::find_closest_volume (const Selection &selection, const Vec2d &screen_center, const Camera &camera, const ModelObjectPtrs &objects, Vec2d *closest_center, const GLVolume **closest_volume)
Find volume in selected object with closest convex hull to screen center. Return.
static void priv::start_create_object_job (DataBase &emboss_data, const Vec2d &coor)
Start job for add object with text into scene.
const IconManager::Icon & priv::get_icon (const IconManager::VIcons &icons, IconType type, IconState state)
static bool priv::draw_button (const IconManager::VIcons &icons, IconType type, bool disable=false)
static bool priv::apply_camera_dir (const Camera &camera, GLCanvas3D &canvas)
Apply camera direction for emboss direction.
TransformationType anonymous_namespace{GLGizmoEmboss.cpp}::get_transformation_type (const Selection &selection)
static ImVec2 priv::calc_fine_position (const Selection &selection, const ImVec2 &windows_size, const Size &canvas_size)
Move window for edit emboss text near to embossed object NOTE: embossed object must be selected.
static void priv::change_window_position (std::optional< ImVec2 > &output_window_offset, bool try_to_fix)
Change position of emboss window.
static bool priv::is_text_empty (const std::string &text)
std::size_t hash_value (wxString const &s)
static std::string concat (std::vector< wxString > data)
static boost::filesystem::path get_fontlist_cache_path ()
template<class Archive >
void save (Archive &archive, wxString const &d)
template<class Archive >
void load (Archive &archive, wxString &d)
template<class Archive >
void serialize (Archive &ar, FacenamesSerializer &t, const std::uint32_t version)
CEREAL_CLASS_VERSION (FacenamesSerializer, FACENAMES_VERSION)
template<typename T >
bool exist_change (const T &value, const T *default_value)
template<>
bool exist_change (const std::optional< float > &value, const std::optional< float > *default_value)
template<>
bool exist_change (const float &value, const float *default_value)
Variables
static const struct priv::Limits priv::limits
constexpr double priv::up_limit = 0.9
Class Documentation
priv::MinMax
struct priv::MinMax
template<typename T>
struct priv::MinMax< T >
Class Members
T max
T min
priv::Limit
struct priv::Limit
template<typename T>
struct priv::Limit< T >
Class Members
MinMax< T > gui
MinMax< T > values
FacenamesSerializer
struct FacenamesSerializer
Class Members
vector< wxString > bad
vector< wxString > good
size_t hash = 0
Macro Definition Documentation
FACENAMES_VERSION
#define FACENAMES_VERSION 1
Function Documentation
CEREAL_CLASS_VERSION()
CEREAL_CLASS_VERSION (FacenamesSerializer , FACENAMES_VERSION)
concat()
static std::string concat (std::vector< wxString > data) static
{
    std::stringstream ss;
    for (const auto &d : data)
        ss << d.c_str() << ", ";
    return ss.str();
}
Referenced by Slic3r::GUI::GLGizmoEmboss::init_face_names().
exist_change() [1/3]
template<> bool exist_change (const float & value, const float * default_value)
{
    if (default_value == nullptr) return false;
    return !is_approx(value, *default_value);
}
References Slic3r::is_approx().
exist_change() [2/3]
template<> bool exist_change (const std::optional< float > & value, const std::optional< float > * default_value)
{
    if (default_value == nullptr) return false;
    return !is_approx(value, *default_value);
}
References Slic3r::is_approx().
exist_change() [3/3]
template<typename T > bool exist_change (const T & value, const T * default_value)
{
    if (default_value == nullptr) return false;
    return (value != *default_value);
}
Referenced by Slic3r::GUI::GLGizmoEmboss::calculate_scale(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_delete_style_button(), Slic3r::GUI::GLGizmoEmboss::draw_font_list_line(), and Slic3r::GUI::GLGizmoEmboss::revertible().
get_fontlist_cache_path()
static boost::filesystem::path get_fontlist_cache_path () static
{
    return boost::filesystem::path(data_dir()) / "cache" / "fonts.cereal";
}
References Slic3r::data_dir().
Referenced by Slic3r::GUI::GLGizmoEmboss::init_face_names(), Slic3r::GUI::GLGizmoEmboss::load(), and Slic3r::GUI::GLGizmoEmboss::store().
hash_value()
std::size_t hash_value (wxString const & s)
{
    boost::hash<std::string> hasher;
    return hasher(s.ToStdString());
}
load()
template<class Archive > void load (Archive & archive, wxString & d)
{ std::string s; archive(s); d = s;}
Referenced by igl::opengl::glfw::Viewer::load_mesh_from_file().
save()
template<class Archive > void save (Archive & archive, wxString const & d)
{ std::string s(d.ToUTF8().data()); archive(s);}
Referenced by avr_dup_part(), QuadricEdgeCollapse::change_neighbors(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PhysicalPrinterCollection::load_printer(), safemode_memfuses(), igl::matlab::MatlabWorkspace::save(), igl::matlab::MatlabWorkspace::save(), igl::matlab::MatlabWorkspace::save(), igl::matlab::MatlabWorkspace::save(), Slic3r::UndoRedo::StackImpl::save_immutable_object(), igl::matlab::MatlabWorkspace::save_index(), igl::opengl::glfw::Viewer::save_mesh_to_file(), and Slic3r::GUI::GUI_App::set_mode_palette().
serialize()
template<class Archive > void serialize (Archive & ar, FacenamesSerializer & t, const std::uint32_t version)
{
    // When performing a load, the version associated with the class
    // is whatever it was when that data was originally serialized
    // When we save, we'll use the version that is defined in the macro
    if (version != FACENAMES_VERSION) return;
    ar(t.hash, t.good, t.bad);
}
References FacenamesSerializer::bad, FACENAMES_VERSION, FacenamesSerializer::good, FacenamesSerializer::hash, and version.
Referenced by Slic3r::GUI::get_string_value(), and Slic3r::TriangleSelector::serialize().