Prusa Slicer: Slic3r::GUI::PlaterAfterLoadAutoArrange Class Reference
Slic3r::GUI::PlaterAfterLoadAutoArrange Class Reference
#include <src/slic3r/GUI/Plater.hpp>
Public Member Functions
PlaterAfterLoadAutoArrange ()
~PlaterAfterLoadAutoArrange ()
void disable ()
Private Attributes
bool m_enabled { false }
Detailed Description
Constructor & Destructor Documentation
PlaterAfterLoadAutoArrange()
Slic3r::GUI::PlaterAfterLoadAutoArrange::PlaterAfterLoadAutoArrange ()
{
    Plater* plater = wxGetApp().plater();
    m_enabled = plater->model().objects.empty() &&
                plater->printer_technology() == ptFFF &&
                is_XL_printer(plater->fff_print().config());
}
References Slic3r::Print::config(), Slic3r::GUI::Plater::fff_print(), Slic3r::is_XL_printer(), m_enabled, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::plater(), Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptFFF.
~PlaterAfterLoadAutoArrange()
Slic3r::GUI::PlaterAfterLoadAutoArrange::~PlaterAfterLoadAutoArrange ()
{
    if (m_enabled)
        wxGetApp().plater()->arrange();
}
References m_enabled.
Member Function Documentation
disable()
void Slic3r::GUI::PlaterAfterLoadAutoArrange::disable () inline
{ m_enabled = false; }
References m_enabled.
Member Data Documentation
m_enabled
bool Slic3r::GUI::PlaterAfterLoadAutoArrange::m_enabled { false } private
Referenced by PlaterAfterLoadAutoArrange(), ~PlaterAfterLoadAutoArrange(), and disable().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Plater.hpp
src/slic3r/GUI/Plater.cpp