Prusa Slicer: Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo Class Reference
Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
SelectionInfo (CommonGizmosDataPool *cgdp)
ModelObject * model_object () const
const SLAPrintObject * print_object () const
ModelVolume * model_volume () const
ModelInstance * model_instance () const
int get_active_instance () const
float get_sla_shift () const
void set_use_shift (bool use)
void update ()
void release ()
bool is_valid () const
virtual CommonGizmosDataID get_dependencies () const
Protected Member Functions
void on_update () override
void on_release () override
CommonGizmosDataPool * get_pool () const
Private Attributes
ModelObject * m_model_object = nullptr
const SLAPrintObject * m_print_object = nullptr
ModelVolume * m_model_volume = nullptr
float m_z_shift = 0.f
bool m_use_shift = false
bool m_is_valid = false
CommonGizmosDataPool * m_common = nullptr
Detailed Description
Constructor & Destructor Documentation
SelectionInfo()
Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::SelectionInfo (CommonGizmosDataPool * cgdp) inline explicit
        : CommonGizmosDataBase(cgdp) {}
Member Function Documentation
get_active_instance()
int Slic3r::GUI::SelectionInfo::get_active_instance () const
{
    return get_pool()->get_canvas()->get_selection().get_instance_idx();
}
References Slic3r::GUI::CommonGizmosDataPool::get_canvas(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), and Slic3r::GUI::GLCanvas3D::get_selection().
Referenced by Slic3r::GUI::GLGizmoCut3D::check_and_update_connectors_state(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), model_instance(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::GLGizmoCut3D::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoFlatten::update_planes(), and Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform().
get_dependencies()
virtual CommonGizmosDataID Slic3r::GUI::CommonGizmosDataBase::get_dependencies () const inline virtual inherited
Reimplemented in Slic3r::GUI::CommonGizmosDataObjects::InstancesHider, Slic3r::GUI::CommonGizmosDataObjects::Raycaster, Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper, and Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper.
{ return CommonGizmosDataID::None; }
References Slic3r::GUI::None.
get_pool()
CommonGizmosDataPool * Slic3r::GUI::CommonGizmosDataBase::get_pool () const inline protected inherited
{ return m_common; }
References Slic3r::GUI::CommonGizmosDataBase::m_common.
Referenced by get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_release(), on_update(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), and Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut().
get_sla_shift()
float Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift () const inline
{ return m_use_shift ? m_z_shift : 0.f; }
References m_use_shift, and m_z_shift.
Referenced by Slic3r::GUI::GLGizmoCut3D::check_and_update_connectors_state(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::GLGizmoCut3D::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane(), and Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform().
is_valid()
bool Slic3r::GUI::CommonGizmosDataBase::is_valid () const inline inherited
{ return m_is_valid; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid.
Referenced by Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::GUI::CommonGizmosDataPool::supports_clipper().
model_instance()
ModelInstance * Slic3r::GUI::SelectionInfo::model_instance () const
{
    int inst_idx = get_active_instance();
    return inst_idx < int(m_model_object->instances.size()) ?
               m_model_object->instances[get_active_instance()] : nullptr;
}
References get_active_instance(), Slic3r::ModelObject::instances, and m_model_object.
Referenced by Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform().
model_object()
ModelObject * Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object () const inline
{ return m_model_object; }
References m_model_object.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), Slic3r::GUI::GLGizmoFdmSupports::auto_generate(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::GLGizmoCut3D::check_and_update_connectors_state(), Slic3r::GUI::GLGizmoFdmSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), Slic3r::GUI::GLGizmoCut3D::dragging_connector(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoCut3D::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoHollow::on_dragging(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoCut3D::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), Slic3r::GUI::GLGizmoCut3D::process_selection_rectangle(), Slic3r::GUI::GLGizmoCut3D::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoHollow::reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), Slic3r::GUI::GLGizmoCut3D::render_connectors(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoCut3D::reset_connectors(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoCut3D::update_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
model_volume()
ModelVolume * Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_volume () const inline
{ return m_model_volume; }
References m_model_volume.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update().
on_release()
void Slic3r::GUI::SelectionInfo::on_release () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    m_model_object = nullptr;
    m_model_volume = nullptr;
}
References m_model_object, and m_model_volume.
on_update()
void Slic3r::GUI::SelectionInfo::on_update () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    const Selection& selection = get_pool()->get_canvas()->get_selection();
    m_model_object = nullptr;
    m_print_object = nullptr;
    if (selection.is_single_full_instance()) {
        m_model_object = selection.get_model()->objects[selection.get_object_idx()];
        if (m_model_object)
            m_print_object = get_pool()->get_canvas()->sla_print()->get_print_object_by_model_object_id(m_model_object->id());
        m_z_shift = m_print_object ? m_print_object->get_current_elevation() : selection.get_first_volume()->get_sla_shift_z();
    }
}
References Slic3r::GUI::CommonGizmosDataPool::get_canvas(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::Selection::get_first_volume(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), Slic3r::SLAPrint::get_print_object_by_model_object_id(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GLVolume::get_sla_shift_z(), Slic3r::ObjectBase::id(), Slic3r::GUI::Selection::is_single_full_instance(), m_model_object, m_print_object, m_z_shift, Slic3r::Model::objects, and Slic3r::GUI::GLCanvas3D::sla_print().
print_object()
const SLAPrintObject * Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::print_object () const inline
{ return m_print_object; }
References m_print_object.
Referenced by Slic3r::GUI::GLGizmoHollow::data_changed(), Slic3r::GUI::GLGizmoSlaSupports::data_changed(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoSlaBase::unproject_on_mesh(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
release()
void Slic3r::GUI::CommonGizmosDataBase::release () inline inherited
{ on_release(); m_is_valid = false; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_release().
set_use_shift()
void Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::set_use_shift (bool use) inline
{ m_use_shift = use; }
References m_use_shift.
Referenced by Slic3r::GUI::GLGizmoCut3D::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_set_state(), and Slic3r::GUI::GLGizmoSlaSupports::on_set_state().
update()
void Slic3r::GUI::CommonGizmosDataBase::update () inline inherited
{ on_update(); m_is_valid = true; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_update().
Member Data Documentation
m_common
CommonGizmosDataPool* Slic3r::GUI::CommonGizmosDataBase::m_common = nullptr private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::get_pool().
m_is_valid
bool Slic3r::GUI::CommonGizmosDataBase::m_is_valid = false private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::is_valid(), Slic3r::GUI::CommonGizmosDataBase::release(), and Slic3r::GUI::CommonGizmosDataBase::update().
m_model_object
ModelObject* Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::m_model_object = nullptr private
Referenced by model_instance(), model_object(), on_release(), and on_update().
m_model_volume
ModelVolume* Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::m_model_volume = nullptr private
Referenced by model_volume(), and on_release().
m_print_object
const SLAPrintObject* Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::m_print_object = nullptr private
Referenced by on_update(), and print_object().
m_use_shift
bool Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::m_use_shift = false private
Referenced by get_sla_shift(), and set_use_shift().
m_z_shift
float Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::m_z_shift = 0.f private
Referenced by get_sla_shift(), and on_update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp
src/slic3r/GUI/Gizmos/GLGizmosCommon.cpp