Prusa Slicer: Slic3r::GUI::ConfigWizardPage Struct Reference
Slic3r::GUI::ConfigWizardPage Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
ConfigWizardPage (ConfigWizard *parent, wxString title, wxString shortname, unsigned indent=0)
virtual ~ConfigWizardPage ()
template<class T >
T * append (T *thing, int proportion=0, int flag=wxEXPAND|wxTOP|wxBOTTOM, int border=10)
wxStaticText * append_text (wxString text)
void append_spacer (int space)
ConfigWizard::priv * wizard_p () const
virtual void apply_custom_config (DynamicPrintConfig &config)
virtual void set_run_reason (ConfigWizard::RunReason run_reason)
virtual void on_activate ()
Public Attributes
ConfigWizard * parent
const wxString shortname
wxBoxSizer * content
const unsigned indent
Detailed Description
Constructor & Destructor Documentation
ConfigWizardPage()
Slic3r::GUI::ConfigWizardPage::ConfigWizardPage (ConfigWizard * parent, wxString title, wxString shortname, unsigned indent = 0)
    : wxPanel(parent->p->hscroll)
    , parent(parent)
    , shortname(std::move(shortname))
    , indent(indent)
{
    wxGetApp().UpdateDarkUI(this);
    auto *sizer = new wxBoxSizer(wxVERTICAL);
    auto *text = new wxStaticText(this, wxID_ANY, std::move(title), wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    const auto font = GetFont().MakeBold().Scaled(1.5);
    text->SetFont(font);
    sizer->Add(text, 0, wxALIGN_LEFT, 0);
    sizer->AddSpacer(10);
    content = new wxBoxSizer(wxVERTICAL);
    sizer->Add(content, 1, wxEXPAND);
    SetSizer(sizer);
    // There is strange layout on Linux with GTK3,
    // see https://github.com/prusa3d/PrusaSlicer/issues/5103 and https://github.com/prusa3d/PrusaSlicer/issues/4861
    // So, non-active pages will be hidden later, on wxEVT_SHOW, after completed Layout() for all pages
    if (!wxLinux_gtk3)
        this->Hide();
    Bind(wxEVT_SIZE, [this](wxSizeEvent &event) {
        this->Layout();
        event.Skip();
    });
}
References content, and wxLinux_gtk3.
~ConfigWizardPage()
Slic3r::GUI::ConfigWizardPage::~ConfigWizardPage () virtual
{}
Member Function Documentation
append()
template<class T > T * Slic3r::GUI::ConfigWizardPage::append (T * thing, int proportion = 0, int flag = wxEXPAND|wxTOP|wxBOTTOM, int border = 10) inline
    {
        content->Add(thing, proportion, flag, border);
        return thing;
    }
References content.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), Slic3r::GUI::PageVendors::PageVendors(), and append_text().
append_spacer()
void Slic3r::GUI::ConfigWizardPage::append_spacer (int space)
{
    // FIXME: scaling
    content->AddSpacer(space);
}
References content.
Referenced by Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageTemperatures::PageTemperatures(), and Slic3r::GUI::PageUpdate::PageUpdate().
append_text()
wxStaticText * Slic3r::GUI::ConfigWizardPage::append_text (wxString text)
{
    auto *widget = new wxStaticText(this, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    widget->Wrap(WRAP_WIDTH);
    widget->SetMinSize(wxSize(WRAP_WIDTH, -1));
    append(widget);
    return widget;
}
References append(), and Slic3r::GUI::WRAP_WIDTH.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), and Slic3r::GUI::PageVendors::PageVendors().
apply_custom_config()
virtual void Slic3r::GUI::ConfigWizardPage::apply_custom_config (DynamicPrintConfig & config) inline virtual
Reimplemented in Slic3r::GUI::PageFirmware, Slic3r::GUI::PageBedShape, Slic3r::GUI::PageBuildVolume, Slic3r::GUI::PageDiameters, and Slic3r::GUI::PageTemperatures.
{}
on_activate()
virtual void Slic3r::GUI::ConfigWizardPage::on_activate () inline virtual
Reimplemented in Slic3r::GUI::PageMaterials.
{}
Referenced by Slic3r::GUI::PageMode::PageMode().
set_run_reason()
virtual void Slic3r::GUI::ConfigWizardPage::set_run_reason (ConfigWizard::RunReason run_reason) inline virtual
Reimplemented in Slic3r::GUI::PageWelcome, and Slic3r::GUI::PagePrinters.
{}
wizard_p()
ConfigWizard::priv * Slic3r::GUI::ConfigWizardPage::wizard_p () const inline
{ return parent->p.get(); }
References Slic3r::GUI::ConfigWizard::p, and parent.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageVendors::PageVendors(), Slic3r::GUI::PageMaterials::on_activate(), Slic3r::GUI::PageMaterials::select_material(), and Slic3r::GUI::PageMaterials::update_lists().
Member Data Documentation
content
wxBoxSizer* Slic3r::GUI::ConfigWizardPage::content
Referenced by ConfigWizardPage(), append(), and append_spacer().
indent
const unsigned Slic3r::GUI::ConfigWizardPage::indent
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page().
parent
ConfigWizard* Slic3r::GUI::ConfigWizardPage::parent
Referenced by Slic3r::GUI::PageMaterials::PageMaterials(), and wizard_p().
shortname
const wxString Slic3r::GUI::ConfigWizardPage::shortname
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page(), and Slic3r::GUI::ConfigWizard::priv::add_page().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp