Prusa Slicer: Slic3r::Polyline3 Class Reference
Slic3r::Polyline3 Class Reference
#include <src/libslic3r/Polyline.hpp>
Public Member Functions
double length () const
Lines3 lines () const
void append (const Vec3crd &point)
void translate (double x, double y)
void translate (const Point &vector)
bool is_valid () const
BoundingBox3 bounding_box () const
bool remove_duplicate_points ()
Public Attributes
Points3 points
Detailed Description
Member Function Documentation
append()
void Slic3r::MultiPoint3::append (const Vec3crd & point) inline inherited
{ this->points.push_back(point); }
bounding_box()
BoundingBox3 Slic3r::MultiPoint3::bounding_box () const inherited
{
    return BoundingBox3(points);
}
References Slic3r::MultiPoint3::points.
is_valid()
bool Slic3r::MultiPoint3::is_valid () const inline inherited
{ return this->points.size() >= 2; }
length()
double Slic3r::Polyline3::length () const
{
    double l = 0;
    for (size_t i = 1; i < this->points.size(); ++ i)
        l += (this->points[i] - this->points[i - 1]).cast<double>().norm();
    return l;
}
References Slic3r::MultiPoint3::points.
lines()
Lines3 Slic3r::Polyline3::lines () const
{
    Lines3 lines;
    if (points.size() >= 2)
    {
        lines.reserve(points.size() - 1);
        for (Points3::const_iterator it = points.begin(); it != points.end() - 1; ++it)
        {
            lines.emplace_back(*it, *(it + 1));
        }
    }
    return lines;
}
References lines(), and Slic3r::MultiPoint3::points.
Referenced by lines().
remove_duplicate_points()
bool Slic3r::MultiPoint3::remove_duplicate_points () inherited
{
    size_t j = 0;
    for (size_t i = 1; i < points.size(); ++i) {
        if (points[j] == points[i]) {
            // Just increase index i.
        } else {
            ++ j;
            if (j < i)
                points[j] = points[i];
        }
    }
    if (++j < points.size())
    {
        points.erase(points.begin() + j, points.end());
        return true;
    }
    return false;
}
References Slic3r::MultiPoint3::points.
translate() [1/2]
void Slic3r::MultiPoint3::translate (const Point & vector) inherited
{
    this->translate(vector(0), vector(1));
}
References Slic3r::MultiPoint3::translate().
translate() [2/2]
void Slic3r::MultiPoint3::translate (double x, double y) inherited
{
    for (Vec3crd &p : points) {
        p(0) += coord_t(x);
        p(1) += coord_t(y);
    }
}
References Slic3r::MultiPoint3::points.
Referenced by Slic3r::MultiPoint3::translate().
Member Data Documentation
points
Points3 Slic3r::MultiPoint3::points inherited
Referenced by Slic3r::MultiPoint3::bounding_box(), length(), lines(), Slic3r::MultiPoint3::remove_duplicate_points(), and Slic3r::MultiPoint3::translate().
The documentation for this class was generated from the following files:
src/libslic3r/Polyline.hpp
src/libslic3r/Polyline.cpp