Prusa Slicer: Slic3r::Timing::TimeLimitAlarm Class Reference
Slic3r::Timing::TimeLimitAlarm Class Reference
#include <src/libslic3r/Timer.hpp>
Public Member Functions
TimeLimitAlarm (uint64_t time_limit_nanoseconds, std::string_view limit_exceeded_message)
~TimeLimitAlarm ()
Static Public Member Functions
static TimeLimitAlarm new_nanos (uint64_t time_limit_nanoseconds, std::string_view limit_exceeded_message)
static TimeLimitAlarm new_milis (uint64_t time_limit_milis, std::string_view limit_exceeded_message)
static TimeLimitAlarm new_seconds (uint64_t time_limit_seconds, std::string_view limit_exceeded_message)
Private Member Functions
void report_time_exceeded () const
Private Attributes
Timer m_timer
uint64_t m_time_limit_nanoseconds
std::string_view m_limit_exceeded_message
Detailed Description
Constructor & Destructor Documentation
TimeLimitAlarm()
Slic3r::Timing::TimeLimitAlarm::TimeLimitAlarm (uint64_t time_limit_nanoseconds, std::string_view limit_exceeded_message) inline
                                                                                               :
            m_time_limit_nanoseconds(time_limit_nanoseconds), m_limit_exceeded_message(limit_exceeded_message) {
            m_timer.start();
        }
References m_timer, and Slic3r::Timing::Timer::start().
~TimeLimitAlarm()
Slic3r::Timing::TimeLimitAlarm::~TimeLimitAlarm () inline
{
            auto elapsed = m_timer.elapsed_nanoseconds();
            if (elapsed > m_time_limit_nanoseconds)
                this->report_time_exceeded();
        }
References Slic3r::Timing::Timer::elapsed_nanoseconds(), m_time_limit_nanoseconds, m_timer, and report_time_exceeded().
Member Function Documentation
new_milis()
static TimeLimitAlarm Slic3r::Timing::TimeLimitAlarm::new_milis (uint64_t time_limit_milis, std::string_view limit_exceeded_message) inline static
{
            return TimeLimitAlarm(uint64_t(time_limit_milis) * 1000000l, limit_exceeded_message);
        }
new_nanos()
static TimeLimitAlarm Slic3r::Timing::TimeLimitAlarm::new_nanos (uint64_t time_limit_nanoseconds, std::string_view limit_exceeded_message) inline static
{
            return TimeLimitAlarm(time_limit_nanoseconds, limit_exceeded_message);
        }
new_seconds()
static TimeLimitAlarm Slic3r::Timing::TimeLimitAlarm::new_seconds (uint64_t time_limit_seconds, std::string_view limit_exceeded_message) inline static
{
            return TimeLimitAlarm(uint64_t(time_limit_seconds) * 1000000000l, limit_exceeded_message);
        }
report_time_exceeded()
void Slic3r::Timing::TimeLimitAlarm::report_time_exceeded () const private
{
    BOOST_LOG_TRIVIAL(error) << "Time limit exceeded for " << m_limit_exceeded_message << ": " << m_timer.elapsed_seconds() << "s";
}
References Slic3r::Timing::Timer::elapsed_seconds(), error, m_limit_exceeded_message, and m_timer.
Referenced by ~TimeLimitAlarm().
Member Data Documentation
m_limit_exceeded_message
std::string_view Slic3r::Timing::TimeLimitAlarm::m_limit_exceeded_message private
Referenced by report_time_exceeded().
m_time_limit_nanoseconds
uint64_t Slic3r::Timing::TimeLimitAlarm::m_time_limit_nanoseconds private
Referenced by ~TimeLimitAlarm().
m_timer
Timer Slic3r::Timing::TimeLimitAlarm::m_timer private
Referenced by TimeLimitAlarm(), ~TimeLimitAlarm(), and report_time_exceeded().
The documentation for this class was generated from the following files:
src/libslic3r/Timer.hpp
src/libslic3r/Timer.cpp