Prusa Slicer: Slic3r::GUI::Plater::TakeSnapshot Class Reference
Slic3r::GUI::Plater::TakeSnapshot Class Reference
#include <src/slic3r/GUI/Plater.hpp>
Public Member Functions
TakeSnapshot (Plater *plater, const std::string &snapshot_name)
TakeSnapshot (Plater *plater, const wxString &snapshot_name)
TakeSnapshot (Plater *plater, const std::string &snapshot_name, UndoRedo::SnapshotType snapshot_type)
TakeSnapshot (Plater *plater, const wxString &snapshot_name, UndoRedo::SnapshotType snapshot_type)
~TakeSnapshot ()
Private Attributes
Plater * m_plater
Detailed Description
Constructor & Destructor Documentation
TakeSnapshot() [1/4]
Slic3r::GUI::Plater::TakeSnapshot::TakeSnapshot (Plater * plater, const std::string & snapshot_name)
: TakeSnapshot(plater, from_u8(snapshot_name)) {}
References Slic3r::GUI::from_u8().
TakeSnapshot() [2/4]
Slic3r::GUI::Plater::TakeSnapshot::TakeSnapshot (Plater * plater, const wxString & snapshot_name) inline
                                                                : m_plater(plater)
    {
      m_plater->take_snapshot(snapshot_name);
      m_plater->suppress_snapshots();
    }
References m_plater, Slic3r::GUI::Plater::suppress_snapshots(), and Slic3r::GUI::Plater::take_snapshot().
TakeSnapshot() [3/4]
Slic3r::GUI::Plater::TakeSnapshot::TakeSnapshot (Plater * plater, const std::string & snapshot_name, UndoRedo::SnapshotType snapshot_type)
: TakeSnapshot(plater, from_u8(snapshot_name), snapshot_type) {}
References Slic3r::GUI::from_u8().
TakeSnapshot() [4/4]
Slic3r::GUI::Plater::TakeSnapshot::TakeSnapshot (Plater * plater, const wxString & snapshot_name, UndoRedo::SnapshotType snapshot_type) inline
                                                                                                        : m_plater(plater)
        {
            m_plater->take_snapshot(snapshot_name, snapshot_type);
            m_plater->suppress_snapshots();
        }
References m_plater, Slic3r::GUI::Plater::suppress_snapshots(), and Slic3r::GUI::Plater::take_snapshot().
~TakeSnapshot()
Slic3r::GUI::Plater::TakeSnapshot::~TakeSnapshot () inline
    {
      m_plater->allow_snapshots();
    }
References Slic3r::GUI::Plater::allow_snapshots(), and m_plater.
Member Data Documentation
m_plater
Plater* Slic3r::GUI::Plater::TakeSnapshot::m_plater private
Referenced by TakeSnapshot(), TakeSnapshot(), and ~TakeSnapshot().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Plater.hpp
src/slic3r/GUI/Plater.cpp