Prusa Slicer: igl::Timer Class Reference
igl::Timer Class Reference
#include <src/libigl/igl/Timer.h>
Public Member Functions
Timer ()
~Timer ()
void start ()
void stop ()
double getElapsedTime ()
double getElapsedTimeInSec ()
double getElapsedTimeInMilliSec ()
double getElapsedTimeInMicroSec ()
Private Attributes
int stopped
timeval startCount
timeval endCount
Detailed Description
Constructor & Destructor Documentation
Timer()
igl::Timer::Timer () inline
           :
      stopped(0),
#ifdef WIN32
      frequency(),
      startCount(),
      endCount()
#elif __APPLE__
      startCount(0),
      endCount(0)
#else
      startCount(),
      endCount()
#endif
    {
#ifdef WIN32
      QueryPerformanceFrequency(&frequency);
      startCount.QuadPart = 0;
      endCount.QuadPart = 0;
#elif __APPLE__
      startCount = 0;
      endCount = 0;
#else
      startCount.tv_sec = startCount.tv_usec = 0;
      endCount.tv_sec = endCount.tv_usec = 0;
#endif
      stopped = 0;
    }
References endCount, startCount, and stopped.
~Timer()
igl::Timer::~Timer () inline
    {
    }
Member Function Documentation
getElapsedTime()
double igl::Timer::getElapsedTime () inline
    {
      return this->getElapsedTimeInSec();
    }
References getElapsedTimeInSec().
getElapsedTimeInMicroSec()
double igl::Timer::getElapsedTimeInMicroSec () inline
    {
      double startTimeInMicroSec = 0;
      double endTimeInMicroSec = 0;
#ifdef WIN32
      if(!stopped)
        QueryPerformanceCounter(&endCount);
      startTimeInMicroSec =
        startCount.QuadPart * (1000000.0 / frequency.QuadPart);
      endTimeInMicroSec = endCount.QuadPart * (1000000.0 / frequency.QuadPart);
#elif __APPLE__
      if (!stopped)
        endCount = mach_absolute_time();
      return subtractTimes(endCount,startCount)/1e-6;
#else
      if(!stopped)
        gettimeofday(&endCount, NULL);
      startTimeInMicroSec =
        (startCount.tv_sec * 1000000.0) + startCount.tv_usec;
      endTimeInMicroSec = (endCount.tv_sec * 1000000.0) + endCount.tv_usec;
#endif
      return endTimeInMicroSec - startTimeInMicroSec;
    }
References endCount, gettimeofday(), startCount, and stopped.
Referenced by getElapsedTimeInMilliSec(), and getElapsedTimeInSec().
getElapsedTimeInMilliSec()
double igl::Timer::getElapsedTimeInMilliSec () inline
    {
      return this->getElapsedTimeInMicroSec() * 0.001;
    }
References getElapsedTimeInMicroSec().
getElapsedTimeInSec()
double igl::Timer::getElapsedTimeInSec () inline
    {
      return this->getElapsedTimeInMicroSec() * 0.000001;
    }
References getElapsedTimeInMicroSec().
Referenced by getElapsedTime().
start()
void igl::Timer::start () inline
    {
      stopped = 0; // reset stop flag
#ifdef WIN32
      QueryPerformanceCounter(&startCount);
#elif __APPLE__
      startCount = mach_absolute_time();
#else
      gettimeofday(&startCount, NULL);
#endif
    }
References gettimeofday(), startCount, and stopped.
stop()
void igl::Timer::stop () inline
    {
      stopped = 1; // set timer stopped flag
#ifdef WIN32
      QueryPerformanceCounter(&endCount);
#elif __APPLE__
      endCount = mach_absolute_time();
#else
      gettimeofday(&endCount, NULL);
#endif
    }
References endCount, gettimeofday(), and stopped.
Member Data Documentation
endCount
timeval igl::Timer::endCount private
Referenced by Timer(), getElapsedTimeInMicroSec(), and stop().
startCount
timeval igl::Timer::startCount private
Referenced by Timer(), getElapsedTimeInMicroSec(), and start().
stopped
int igl::Timer::stopped private
Referenced by Timer(), getElapsedTimeInMicroSec(), start(), and stop().
The documentation for this class was generated from the following file:
src/libigl/igl/Timer.h