Prusa Slicer: Slic3r::sla::PointIndex Class Reference
Slic3r::sla::PointIndex Class Reference
#include <src/libslic3r/SLA/SpatIndex.hpp>
Classes
class Impl
Public Member Functions
PointIndex ()
~PointIndex ()
PointIndex (const PointIndex &)
PointIndex (PointIndex &&)
PointIndex & operator= (const PointIndex &)
PointIndex & operator= (PointIndex &&)
void insert (const PointIndexEl &)
bool remove (const PointIndexEl &)
void insert (const Vec3d &v, unsigned idx)
std::vector< PointIndexEl > query (std::function< bool(const PointIndexEl &)>) const
std::vector< PointIndexEl > nearest (const Vec3d &, unsigned k) const
std::vector< PointIndexEl > query (const Vec3d &v, unsigned k) const
size_t size () const
bool empty () const
void foreach (std::function< void(const PointIndexEl &el)> fn)
void foreach (std::function< void(const PointIndexEl &el)> fn) const
Private Attributes
std::unique_ptr< Impl > m_impl
Detailed Description
Class Documentation
Slic3r::sla::PointIndex::Impl
class Slic3r::sla::PointIndex::Impl
Class Members
typedef rtree< PointIndexEl, rstar< 16, 4 > > BoostIndex
Class Members
BoostIndex m_store
Constructor & Destructor Documentation
PointIndex() [1/3]
Slic3r::sla::PointIndex::PointIndex ()
: m_impl(new Impl()) {}
~PointIndex()
Slic3r::sla::PointIndex::~PointIndex ()
{}
PointIndex() [2/3]
Slic3r::sla::PointIndex::PointIndex (const PointIndex & cpy)
: m_impl(new Impl(*cpy.m_impl)) {}
PointIndex() [3/3]
Slic3r::sla::PointIndex::PointIndex (PointIndex && cpy)
: m_impl(std::move(cpy.m_impl)) {}
Member Function Documentation
empty()
bool Slic3r::sla::PointIndex::empty () const inline
{ return size() == 0; }
References size().
Referenced by Slic3r::sla::DefaultSupportTree::search_pillar_and_connect().
foreach() [1/2]
void Slic3r::sla::PointIndex::foreach (std::function< void(const PointIndexEl &el)> fn)
Referenced by Slic3r::sla::PillarIndex::foreach(), and Slic3r::sla::PillarIndex::guarded_foreach().
foreach() [2/2]
void Slic3r::sla::PointIndex::foreach (std::function< void(const PointIndexEl &el)> fn) const
insert() [1/2]
void Slic3r::sla::PointIndex::insert (const PointIndexEl & el)
{
    m_impl->m_store.insert(el);
}
References m_impl.
Referenced by Slic3r::sla::ConcaveHull::add_connector_rectangles(), Slic3r::sla::PillarIndex::guarded_insert(), Slic3r::sla::PillarIndex::insert(), and insert().
insert() [2/2]
void Slic3r::sla::PointIndex::insert (const Vec3d & v, unsigned idx) inline
    {
        insert(std::make_pair(v, unsigned(idx)));
    }
References insert().
nearest()
std::vector< PointIndexEl > Slic3r::sla::PointIndex::nearest (const Vec3d & el, unsigned k = 1) const
{
    namespace bgi = boost::geometry::index;
    std::vector<PointIndexEl> ret; ret.reserve(k);
    m_impl->m_store.query(bgi::nearest(el, k), std::back_inserter(ret));
    return ret;
}
References m_impl.
Referenced by Slic3r::sla::ConcaveHull::add_connector_rectangles(), query(), and Slic3r::sla::DefaultSupportTree::search_pillar_and_connect().
operator=() [1/2]
PointIndex & Slic3r::sla::PointIndex::operator= (const PointIndex & cpy)
{
    m_impl.reset(new Impl(*cpy.m_impl));
    return *this;
}
References m_impl.
operator=() [2/2]
PointIndex & Slic3r::sla::PointIndex::operator= (PointIndex && cpy)
{
    m_impl.swap(cpy.m_impl);
    return *this;
}
References m_impl.
query() [1/2]
std::vector< PointIndexEl > Slic3r::sla::PointIndex::query (const Vec3d & v, unsigned k) const inline
    {
        return nearest(v, k);
    }
References nearest().
query() [2/2]
std::vector< PointIndexEl > Slic3r::sla::PointIndex::query (std::function< bool(const PointIndexEl &)> fn) const
{
    namespace bgi = boost::geometry::index;
    std::vector<PointIndexEl> ret;
    m_impl->m_store.query(bgi::satisfies(fn), std::back_inserter(ret));
    return ret;
}
References m_impl.
Referenced by Slic3r::sla::PillarIndex::guarded_query(), and Slic3r::sla::PillarIndex::query().
remove()
bool Slic3r::sla::PointIndex::remove (const PointIndexEl & el)
{
    return m_impl->m_store.remove(el) == 1;
}
References m_impl.
Referenced by Slic3r::sla::DefaultSupportTree::search_pillar_and_connect().
size()
size_t Slic3r::sla::PointIndex::size () const
{
    return m_impl->m_store.size();
}
References m_impl.
Referenced by empty().
Member Data Documentation
m_impl
std::unique_ptr<Impl> Slic3r::sla::PointIndex::m_impl private
Referenced by insert(), nearest(), operator=(), operator=(), query(), remove(), and size().
The documentation for this class was generated from the following files:
src/libslic3r/SLA/SpatIndex.hpp
src/libslic3r/SLA/SpatIndex.cpp