Prusa Slicer: Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex > Struct Template Reference
Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex > Struct Template Reference
#include <src/eigen/Eigen/src/Eigenvalues/Tridiagonalization.h>
Public Types
typedef Tridiagonalization< MatrixType >::CoeffVectorType CoeffVectorType
typedef Tridiagonalization< MatrixType >::HouseholderSequenceType HouseholderSequenceType
Static Public Member Functions
template<typename DiagonalType , typename SubDiagonalType >
static void run (MatrixType &mat, DiagonalType &diag, SubDiagonalType &subdiag, bool extractQ)
Detailed Description
template<typename MatrixType, int Size, bool IsComplex>
struct Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >
Member Typedef Documentation
CoeffVectorType
template<typename MatrixType , int Size, bool IsComplex> typedef Tridiagonalization<MatrixType>::CoeffVectorType Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::CoeffVectorType
HouseholderSequenceType
template<typename MatrixType , int Size, bool IsComplex> typedef Tridiagonalization<MatrixType>::HouseholderSequenceType Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::HouseholderSequenceType
Member Function Documentation
run()
template<typename MatrixType , int Size, bool IsComplex> template<typename DiagonalType , typename SubDiagonalType > static void Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run (MatrixType & mat, DiagonalType & diag, SubDiagonalType & subdiag, bool extractQ) inline static
  {
    CoeffVectorType hCoeffs(mat.cols()-1);
    tridiagonalization_inplace(mat,hCoeffs);
    diag = mat.diagonal().real();
    subdiag = mat.template diagonal<-1>().real();
    if(extractQ)
      mat = HouseholderSequenceType(mat, hCoeffs.conjugate())
            .setLength(mat.rows() - 1)
            .setShift(1);
  }
References real(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setShift(), and Eigen::internal::tridiagonalization_inplace().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Eigenvalues/Tridiagonalization.h