Prusa Slicer: Slic3r::GCodeProcessor::SeamsDetector Class Reference
Slic3r::GCodeProcessor::SeamsDetector Class Reference
#include <src/libslic3r/GCode/GCodeProcessor.hpp>
Public Member Functions
void activate (bool active)
std::optional< Vec3f > get_first_vertex () const
void set_first_vertex (const Vec3f &vertex)
bool is_active () const
bool has_first_vertex () const
Private Attributes
bool m_active { false }
std::optional< Vec3f > m_first_vertex
Detailed Description
Member Function Documentation
activate()
void Slic3r::GCodeProcessor::SeamsDetector::activate (bool active) inline
{
                if (m_active != active) {
                    m_active = active;
                    if (m_active)
                        m_first_vertex.reset();
                }
            }
References m_active, and m_first_vertex.
Referenced by Slic3r::GCodeProcessor::process_bambustudio_tags(), Slic3r::GCodeProcessor::process_craftware_tags(), Slic3r::GCodeProcessor::process_cura_tags(), Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_ideamaker_tags(), Slic3r::GCodeProcessor::process_kissslicer_tags(), Slic3r::GCodeProcessor::process_simplify3d_tags(), and Slic3r::GCodeProcessor::process_tags().
get_first_vertex()
std::optional< Vec3f > Slic3r::GCodeProcessor::SeamsDetector::get_first_vertex () const inline
{ return m_first_vertex; }
References m_first_vertex.
Referenced by Slic3r::GCodeProcessor::process_G1().
has_first_vertex()
bool Slic3r::GCodeProcessor::SeamsDetector::has_first_vertex () const inline
{ return m_first_vertex.has_value(); }
References m_first_vertex.
Referenced by Slic3r::GCodeProcessor::process_G1().
is_active()
bool Slic3r::GCodeProcessor::SeamsDetector::is_active () const inline
{ return m_active; }
References m_active.
Referenced by Slic3r::GCodeProcessor::process_G1().
set_first_vertex()
void Slic3r::GCodeProcessor::SeamsDetector::set_first_vertex (const Vec3f & vertex) inline
{ m_first_vertex = vertex; }
References m_first_vertex.
Referenced by Slic3r::GCodeProcessor::process_G1().
Member Data Documentation
m_active
bool Slic3r::GCodeProcessor::SeamsDetector::m_active { false } private
Referenced by activate(), and is_active().
m_first_vertex
std::optional<Vec3f> Slic3r::GCodeProcessor::SeamsDetector::m_first_vertex private
Referenced by activate(), get_first_vertex(), has_first_vertex(), and set_first_vertex().
The documentation for this class was generated from the following file:
src/libslic3r/GCode/GCodeProcessor.hpp