Prusa Slicer: Slic3r::ConfigOptionResolver Class Reference
Slic3r::ConfigOptionResolver Class Reference abstract
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionResolver ()
virtual ~ConfigOptionResolver ()
virtual const ConfigOption * optptr (const t_config_option_key &opt_key) const =0
bool has (const t_config_option_key &opt_key) const
const ConfigOption * option (const t_config_option_key &opt_key) const
template<typename TYPE >
const TYPE * option (const t_config_option_key &opt_key) const
const ConfigOption * option_throw (const t_config_option_key &opt_key) const
template<typename TYPE >
const TYPE * option_throw (const t_config_option_key &opt_key) const
Detailed Description
Constructor & Destructor Documentation
ConfigOptionResolver()
Slic3r::ConfigOptionResolver::ConfigOptionResolver () inline
{}
~ConfigOptionResolver()
virtual Slic3r::ConfigOptionResolver::~ConfigOptionResolver () inline virtual
{}
Member Function Documentation
has()
bool Slic3r::ConfigOptionResolver::has (const t_config_option_key & opt_key) const inline
{ return this->optptr(opt_key) != nullptr; }
References optptr().
Referenced by Slic3r::GUI::Bed3D::detect_type(), Slic3r::PresetCollection::dirty_options(), Slic3r::anonymous_namespace{AnycubicSLA.cpp}::fill_header(), Slic3r::anonymous_namespace{SL1.cpp}::get_cfg_value(), Slic3r::anonymous_namespace{AnycubicSLA.cpp}::get_cfg_value_f(), Slic3r::anonymous_namespace{AnycubicSLA.cpp}::get_cfg_value_i(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::Plater::get_extruder_colors_from_plater_config(), Slic3r::GUI::ConfigOptionsGroup::get_option(), Slic3r::handle_legacy_project_loaded(), Slic3r::handle_legacy_sla(), Slic3r::ModelConfig::has(), Slic3r::PresetCollection::is_dirty(), Slic3r::DynamicPrintConfig::normalize_fdm(), Slic3r::DynamicConfig::read_cli(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::Preset::remove_invalid_keys(), and Slic3r::PresetBundle::update_compatible().
option() [1/2]
const ConfigOption * Slic3r::ConfigOptionResolver::option (const t_config_option_key & opt_key) const inline
{ return this->optptr(opt_key); }
References optptr().
Referenced by Slic3r::Flow::extrusion_width(), Slic3r::Flow::extrusion_width(), and Slic3r::PrintObject::invalidate_state_by_config_options().
option() [2/2]
template<typename TYPE > const TYPE * Slic3r::ConfigOptionResolver::option (const t_config_option_key & opt_key) const inline
    {
        const ConfigOption* opt = this->optptr(opt_key);
        return (opt == nullptr || opt->type() != TYPE::static_type()) ? nullptr : static_cast<const TYPE*>(opt);
    }
References optptr(), and Slic3r::ConfigOption::type().
option_throw() [1/2]
const ConfigOption * Slic3r::ConfigOptionResolver::option_throw (const t_config_option_key & opt_key) const inline
    {
        const ConfigOption* opt = this->optptr(opt_key);
        if (opt == nullptr)
            throw UnknownOptionException(opt_key);
        return opt;
    }
References optptr().
Referenced by option_throw().
option_throw() [2/2]
template<typename TYPE > const TYPE * Slic3r::ConfigOptionResolver::option_throw (const t_config_option_key & opt_key) const inline
    {
        const ConfigOption* opt = this->option_throw(opt_key);
        if (opt->type() != TYPE::static_type())
            throw BadOptionTypeException("Conversion to a wrong type");
        return static_cast<TYPE*>(opt);
    }
References option_throw(), and Slic3r::ConfigOption::type().
optptr()
virtual const ConfigOption * Slic3r::ConfigOptionResolver::optptr (const t_config_option_key & opt_key) const pure virtual
Implemented in Slic3r::DynamicConfig, Slic3r::client::MyContext, and Slic3r::ConfigBase.
Referenced by has(), option(), and option_throw().
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp