Prusa Slicer: Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector Class Reference
Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector Class Reference
Public Member Functions
void add (const ExPolygon &ep)
bool intersects (const ExPolygon &poly)
Private Attributes
BoxIndex m_index
ExPolygons m_polys
Detailed Description
Member Function Documentation
add()
void Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::add (const ExPolygon & ep) inline
    {
        m_polys.emplace_back(ep);
        m_index.insert(get_extents(ep), unsigned(m_index.size()));
    }
References Slic3r::get_extents(), Slic3r::sla::BoxIndex::insert(), and Slic3r::sla::BoxIndex::size().
intersects()
bool Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::intersects (const ExPolygon & poly) inline
    {
        // Create a suitable query bounding box.
        auto bb = poly.contour.bounding_box();
        std::vector<BoxIndexEl> qres = m_index.query(bb, BoxIndex::qtIntersects);
        // Now check intersections on the actual polygons (not just the boxes)
        bool is_overlap = false;
        auto qit        = qres.begin();
        while (!is_overlap && qit != qres.end())
            is_overlap = is_overlap || poly.overlaps(m_polys[(qit++)->second]);
        return is_overlap;
    }
References Slic3r::MultiPoint::bounding_box(), Slic3r::ExPolygon::contour, Slic3r::ExPolygon::overlaps(), and Slic3r::sla::BoxIndex::query().
Member Data Documentation
m_index
BoxIndex Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::m_index private
m_polys
ExPolygons Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::m_polys private
The documentation for this class was generated from the following file:
src/libslic3r/SLA/Pad.cpp