Prusa Slicer: Slic3r::ConfigOptionSingle< T > Class Template Reference
Slic3r::ConfigOptionSingle< T > Class Template Reference abstract
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionSingle (T value)
operator T () const
void set (const ConfigOption *rhs) override
bool operator== (const ConfigOption &rhs) const override
bool operator== (const T &rhs) const throw ()
bool operator!= (const T &rhs) const throw ()
bool operator< (const T &rhs) const throw ()
size_t hash () const override throw ()
virtual ConfigOptionType type () const =0
virtual std::string serialize () const =0
virtual bool deserialize (const std::string &str, bool append=false)=0
virtual ConfigOption * clone () const =0
virtual int getInt () const
virtual double getFloat () const
virtual bool getBool () const
virtual void setInt (int)
bool operator!= (const ConfigOption &rhs) const
bool is_scalar () const
bool is_vector () const
virtual bool nullable () const
virtual bool is_nil () const
virtual bool overriden_by (const ConfigOption *rhs) const
virtual bool apply_override (const ConfigOption *rhs)
Public Attributes
T value
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
template<class T>
class Slic3r::ConfigOptionSingle< T >
Constructor & Destructor Documentation
ConfigOptionSingle()
template<class T > Slic3r::ConfigOptionSingle< T >::ConfigOptionSingle (T value) inline explicit
: value(std::move(value)) {}
Member Function Documentation
apply_override()
virtual bool Slic3r::ConfigOption::apply_override (const ConfigOption * rhs) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      if (*this == *rhs)
        return false;
      *this = *rhs;
      return true;
    }
Referenced by Slic3r::print_config_diffs().
clone()
virtual ConfigOption * Slic3r::ConfigOption::clone () const pure virtual inherited
Implemented in Slic3r::ConfigOptionFloat, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionInt, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionString, Slic3r::ConfigOptionStrings, Slic3r::ConfigOptionPercent, Slic3r::ConfigOptionPercentsTempl< NULLABLE >, Slic3r::ConfigOptionFloatOrPercent, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionPoint, Slic3r::ConfigOptionPoints, Slic3r::ConfigOptionPoint3, Slic3r::ConfigOptionBool, Slic3r::ConfigOptionBoolsTempl< NULLABLE >, Slic3r::ConfigOptionEnum< T >, and Slic3r::ConfigOptionEnumGeneric.
Referenced by Slic3r::DynamicConfig::DynamicConfig(), Slic3r::GUI::ObjectSettings::add_missed_options(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::GUI::ConfigManipulation::apply(), Slic3r::PlaceholderParser::apply_config(), Slic3r::PlaceholderParser::apply_only(), Slic3r::GUI::PlaterPresetComboBox::change_extruder_color(), Slic3r::GUI::Tab::load_config(), Slic3r::GUI::Plater::on_config_change(), Slic3r::print_config_diffs(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
deserialize()
virtual bool Slic3r::ConfigOption::deserialize (const std::string & str, bool append = false) pure virtual inherited
Implemented in Slic3r::ConfigOptionFloat, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionInt, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionString, Slic3r::ConfigOptionStrings, Slic3r::ConfigOptionPercent, Slic3r::ConfigOptionFloatOrPercent, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionPoint, Slic3r::ConfigOptionPoints, Slic3r::ConfigOptionPoint3, Slic3r::ConfigOptionBool, Slic3r::ConfigOptionBoolsTempl< NULLABLE >, Slic3r::ConfigOptionEnum< T >, and Slic3r::ConfigOptionEnumGeneric.
Referenced by Slic3r::ConfigBase::null_nullables(), Slic3r::DynamicConfig::read_cli(), and Slic3r::ConfigBase::set_deserialize_raw().
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
virtual int Slic3r::ConfigOption::getInt () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::getInt on a non-int ConfigOption"); }
Referenced by Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
hash()
template<class T > size_t Slic3r::ConfigOptionSingle< T >::hash () const throw () inline override virtual
Implements Slic3r::ConfigOption.
{ return std::hash<T>{}(this->value); }
References Slic3r::ConfigOptionSingle< T >::value.
is_nil()
virtual bool Slic3r::ConfigOption::is_nil () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVectorBase, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::GCode::append_full_config(), Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_full_label(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::print_config_diffs(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::validate(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nullable()
virtual bool Slic3r::ConfigOption::nullable () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::ConfigBase::null_nullables(), Slic3r::ConfigOption::overriden_by(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::validate().
operator T()
template<class T > Slic3r::ConfigOptionSingle< T >::operator T () const inline
{ return this->value; }
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
template<class T > bool Slic3r::ConfigOptionSingle< T >::operator!= (const T & rhs) const throw () inline
{ return this->value != rhs; }
operator<()
template<class T > bool Slic3r::ConfigOptionSingle< T >::operator< (const T & rhs) const throw () inline
{ return this->value < rhs; }
operator==() [1/2]
template<class T > bool Slic3r::ConfigOptionSingle< T >::operator== (const ConfigOption & rhs) const inline override virtual
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionSingle: Comparing incompatible types");
        assert(dynamic_cast<const ConfigOptionSingle<T>*>(&rhs));
        return this->value == static_cast<const ConfigOptionSingle<T>*>(&rhs)->value;
    }
References Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionSingle< T >::value.
operator==() [2/2]
template<class T > bool Slic3r::ConfigOptionSingle< T >::operator== (const T & rhs) const throw () inline
{ return this->value == rhs; }
overriden_by()
virtual bool Slic3r::ConfigOption::overriden_by (const ConfigOption * rhs) const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      assert(! this->nullable() && ! rhs->nullable());
      return *this != *rhs;
    }
References Slic3r::ConfigOption::nullable().
Referenced by Slic3r::print_config_diffs().
serialize() [1/2]
virtual std::string Slic3r::ConfigOption::serialize () const pure virtual inherited
Implemented in Slic3r::ConfigOptionFloat, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionInt, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionString, Slic3r::ConfigOptionStrings, Slic3r::ConfigOptionPercent, Slic3r::ConfigOptionPercentsTempl< NULLABLE >, Slic3r::ConfigOptionFloatOrPercent, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionPoint, Slic3r::ConfigOptionPoints, Slic3r::ConfigOptionPoint3, Slic3r::ConfigOptionBool, Slic3r::ConfigOptionBoolsTempl< NULLABLE >, Slic3r::ConfigOptionEnum< T >, and Slic3r::ConfigOptionEnumGeneric.
Referenced by Slic3r::anonymous_namespace{AnycubicSLA.cpp}::fill_header(), Slic3r::anonymous_namespace{SL1.cpp}::get_cfg_value(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::ConfigBase::opt_serialize(), and Slic3r::client::MyContext::scalar_variable_to_expr().
serialize() [2/2]
template<class T > template<class Archive > void Slic3r::ConfigOptionSingle< T >::serialize (Archive & ar) inline private
{ ar(this->value); }
set()
template<class T > void Slic3r::ConfigOptionSingle< T >::set (const ConfigOption * rhs) inline override virtual
Implements Slic3r::ConfigOption.
    {
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionSingle: Assigning an incompatible type");
        assert(dynamic_cast<const ConfigOptionSingle<T>*>(rhs));
        this->value = static_cast<const ConfigOptionSingle<T>*>(rhs)->value;
    }
References Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionSingle< T >::value.
setInt()
virtual void Slic3r::ConfigOption::setInt (int) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::setInt on a non-int ConfigOption"); }
type()
virtual ConfigOptionType Slic3r::ConfigOption::type () const pure virtual inherited
Implemented in Slic3r::ConfigOptionFloat, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionInt, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionString, Slic3r::ConfigOptionStrings, Slic3r::ConfigOptionPercent, Slic3r::ConfigOptionPercentsTempl< NULLABLE >, Slic3r::ConfigOptionFloatOrPercent, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionPoint, Slic3r::ConfigOptionPoints, Slic3r::ConfigOptionPoint3, Slic3r::ConfigOptionBool, Slic3r::ConfigOptionBoolsTempl< NULLABLE >, Slic3r::ConfigOptionEnum< T >, and Slic3r::ConfigOptionEnumGeneric.
Referenced by Slic3r::Search::OptionsSearcher::append_options(), Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::deep_diff(), Slic3r::ConfigBase::get_abs_value(), Slic3r::ConfigBase::get_abs_value(), Slic3r::ConfigOption::is_scalar(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetBundle::load_config_file_config_bundle(), Slic3r::ConfigOptionSingle< T >::operator==(), Slic3r::ConfigOptionVector< T >::operator==(), Slic3r::ConfigOptionFloatsTempl< NULLABLE >::operator==(), Slic3r::ConfigOptionFloatOrPercent::operator==(), Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >::operator==(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::ConfigOptionResolver::option(), Slic3r::ConfigBase::option(), Slic3r::ConfigOptionResolver::option_throw(), Slic3r::ConfigBase::option_throw(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::DynamicConfig::read_cli(), Slic3r::ConfigOptionVectorBase::scalar_type(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionSingle< T >::set(), Slic3r::ConfigOptionVector< T >::set(), Slic3r::ConfigOptionFloatOrPercent::set(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), Slic3r::ConfigBase::set(), Slic3r::ConfigBase::set(), Slic3r::ConfigOptionVector< T >::set(), Slic3r::ConfigOptionVector< T >::set_at(), Slic3r::validate(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_variable_assign_expr_with_count(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
Friends And Related Symbol Documentation
cereal::access
template<class T > friend class cereal::access friend
Member Data Documentation
value
template<class T > T Slic3r::ConfigOptionSingle< T >::value
Referenced by Slic3r::GUI::GLCanvas3D::_render_overlays(), Slic3r::GCodeProcessor::apply_config(), Slic3r::GCodeProcessor::apply_config(), Slic3r::apply_to_print_region_config(), Slic3r::GUI::ColourPicker::BUILD(), Slic3r::GUI::StaticText::BUILD(), Slic3r::GUI::BedShapePanel::build_panel(), Slic3r::clamp_exturder_to_default(), Slic3r::PrinterPresetCollection::default_preset_for(), Slic3r::Flow::extrusion_width(), Slic3r::first_positive(), Slic3r::PrintRegion::flow(), Slic3r::ConfigOptionEnum< T >::from_string(), Slic3r::GUI::Materials::get_filament_vendor(), Slic3r::GUI::Materials::get_material_type(), Slic3r::GUI::Materials::get_material_vendor(), Slic3r::PrintHost::get_print_host(), get_printer_technology(), Slic3r::get_raster_params(), Slic3r::GUI::get_string_value(), Slic3r::ConfigOptionEnum< T >::getInt(), Slic3r::PrintConfigDef::handle_legacy(), Slic3r::handle_legacy_project_loaded(), Slic3r::handle_legacy_sla(), Slic3r::ConfigOptionEnum< T >::has(), Slic3r::ConfigOptionSingle< T >::hash(), Slic3r::PrintObject::invalidate_state_by_config_options(), Slic3r::PresetHints::maximum_volumetric_flow_description(), Slic3r::min_object_distance(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::ConfigOptionSingle< bool >::operator bool(), Slic3r::ConfigOptionSingle< T >::operator==(), Slic3r::DynamicConfig::read_cli(), Slic3r::CLI::run(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::serialize(), Slic3r::ConfigOptionSingle< T >::set(), Slic3r::ConfigOptionVector< T >::set(), Slic3r::ConfigOptionVector< T >::set_at(), Slic3r::GUI::Plater::set_bed_shape(), Slic3r::CLI::setup(), Slic3r::AvoidCrossingPerimeters::travel_to(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), and Slic3r::validate().
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp