Prusa Slicer: Slic3r::GUI::WxFontUtils Class Reference
Slic3r::GUI::WxFontUtils Class Reference
#include <src/slic3r/Utils/WxFontUtils.hpp>
Public Member Functions
WxFontUtils ()=delete
Static Public Member Functions
static bool can_load (const wxFont &font)
static std::unique_ptr< Slic3r::Emboss::FontFile > create_font_file (const wxFont &font)
static EmbossStyle::Type get_actual_type ()
static EmbossStyle create_emboss_style (const wxFont &font, const std::string &name="")
static std::string get_human_readable_name (const wxFont &font)
static std::string store_wxFont (const wxFont &font)
static wxFont load_wxFont (const std::string &font_descriptor)
static wxFont create_wxFont (const EmbossStyle &style)
static void update_property (FontProp &font_prop, const wxFont &font)
static bool is_italic (const wxFont &font)
static bool is_bold (const wxFont &font)
static std::unique_ptr< Slic3r::Emboss::FontFile > set_italic (wxFont &font, const Slic3r::Emboss::FontFile &prev_font_file)
Set italic into wx font When italic font is same as original return nullptr. To not load font file twice on success is font_file returned.
static std::unique_ptr< Slic3r::Emboss::FontFile > set_bold (wxFont &font, const Slic3r::Emboss::FontFile &font_file)
Set boldness into wx font When bolded font is same as original return nullptr. To not load font file twice on success is font_file returned.
Static Public Attributes
static const boost::bimap< wxFontFamily, std::string_view > type_to_family
static const boost::bimap< wxFontStyle, std::string_view > type_to_style
static const boost::bimap< wxFontWeight, std::string_view > type_to_weight
Detailed Description
Constructor & Destructor Documentation
WxFontUtils()
Slic3r::GUI::WxFontUtils::WxFontUtils () delete
Member Function Documentation
can_load()
bool WxFontUtils::can_load (const wxFont & font) static
{
    if (!font.IsOk()) return false;
#ifdef _WIN32
    return Emboss::can_load(font.GetHFONT()) != nullptr;
#elif defined(__APPLE__)
    return true;
    //return is_valid_ttf(get_file_path(font));
#elif defined(__linux__)
    return true;
    // font config check file path take about 4000ms for chech them all
    //std::string font_path = Slic3r::GUI::get_font_path(font);
    //return !font_path.empty();
#endif
    return false;
}
Referenced by Slic3r::GUI::GLGizmoEmboss::init_face_names().
create_emboss_style()
EmbossStyle WxFontUtils::create_emboss_style (const wxFont & font, const std::string & name = "") static
{
    std::string name_item = name.empty()? get_human_readable_name(font) : name;
    std::string fontDesc = store_wxFont(font);
    EmbossStyle::Type type     = get_actual_type();
    // synchronize font property with actual font
    FontProp font_prop;
    // The point size is defined as 1/72 of the Anglo-Saxon inch (25.4 mm): it
    // is approximately 0.0139 inch or 352.8 um. But it is too small, so I
    // decide use point size as mm for emboss
    font_prop.size_in_mm = font.GetPointSize(); // *0.3528f;
    font_prop.emboss     = font_prop.size_in_mm / 2.f;
    WxFontUtils::update_property(font_prop, font);
    return { name_item, fontDesc, type, font_prop };
}
References Slic3r::FontProp::emboss, get_actual_type(), get_human_readable_name(), Slic3r::FontProp::size_in_mm, store_wxFont(), and update_property().
Referenced by Slic3r::GUI::GLGizmoEmboss::create_default_styles().
create_font_file()
std::unique_ptr< Emboss::FontFile > WxFontUtils::create_font_file (const wxFont & font) static
{
#ifdef _WIN32
    return Emboss::create_font_file(font.GetHFONT());
#elif defined(__APPLE__)
    std::string file_path = get_file_path(font);
    if (!is_valid_ttf(file_path)) {
        BOOST_LOG_TRIVIAL(error) << "Can not process font('" << get_human_readable_name(font) << "'), "
                                 << "file in path('" << file_path << "') is not valid TTF.";
        return nullptr;
    }
    return Emboss::create_font_file(file_path.c_str());
#elif defined(__linux__)
    std::string font_path = Slic3r::GUI::get_font_path(font);
    if (font_path.empty()){
        BOOST_LOG_TRIVIAL(error) << "Can not read font('" << get_human_readable_name(font) << "'), "
                                 << "file path is empty.";
        return nullptr;
    }
    return Emboss::create_font_file(font_path.c_str());
#else
    // HERE is place to add implementation for another platform
    // to convert wxFont to font data as windows or font file path as linux
    return nullptr;
#endif
}
References Slic3r::Emboss::create_font_file(), error, and get_human_readable_name().
Referenced by Slic3r::GUI::GLGizmoEmboss::create_default_styles(), create_wxFont(), Slic3r::GUI::Emboss::StyleManager::init_style_images(), Slic3r::GUI::CreateFontImageJob::process(), set_bold(), set_italic(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), and Slic3r::GUI::Emboss::StyleManager::set_wx_font().
create_wxFont()
wxFont WxFontUtils::create_wxFont (const EmbossStyle & style) static
{
    const FontProp &fp = style.prop;
    double  point_size = static_cast<double>(fp.size_in_mm);
    wxFontInfo info(point_size);
    if (fp.family.has_value()) {
        auto it = type_to_family.right.find(*fp.family);
        if (it != type_to_family.right.end()) info.Family(it->second);
    }
    // Face names are not portable, so prefer to use Family() in portable code.
    /* if (fp.face_name.has_value()) {
        wxString face_name(*fp.face_name);
        info.FaceName(face_name);
    }*/
    if (fp.style.has_value()) {
        auto it = type_to_style.right.find(*fp.style);
        if (it != type_to_style.right.end()) info.Style(it->second);
    }
    if (fp.weight.has_value()) {
        auto it = type_to_weight.right.find(*fp.weight);
        if (it != type_to_weight.right.end()) info.Weight(it->second);
    }
    // Improve: load descriptor instead of store to font property to 3mf
    // switch (es.type) {
    // case EmbossStyle::Type::wx_lin_font_descr:
    // case EmbossStyle::Type::wx_win_font_descr:
    // case EmbossStyle::Type::wx_mac_font_descr:
    // case EmbossStyle::Type::file_path:
    // case EmbossStyle::Type::undefined:
    // default:
    //}
    wxFont wx_font(info);
    // Check if exist font file
    std::unique_ptr<Emboss::FontFile> ff = create_font_file(wx_font);
    if (ff == nullptr) return {};
    return wx_font;
}
References create_font_file(), Slic3r::FontProp::family, Slic3r::FontProp::size_in_mm, Slic3r::FontProp::style, style, type_to_family, type_to_style, type_to_weight, and Slic3r::FontProp::weight.
Referenced by Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection().
get_actual_type()
EmbossStyle::Type WxFontUtils::get_actual_type () static
{
#ifdef _WIN32
    return EmbossStyle::Type::wx_win_font_descr;
#elif defined(__APPLE__)
    return EmbossStyle::Type::wx_mac_font_descr;
#elif defined(__linux__)
    return EmbossStyle::Type::wx_lin_font_descr;
#else
    return EmbossStyle::Type::undefined;
#endif
}
References Slic3r::EmbossStyle::undefined, Slic3r::EmbossStyle::wx_lin_font_descr, Slic3r::EmbossStyle::wx_mac_font_descr, and Slic3r::EmbossStyle::wx_win_font_descr.
Referenced by create_emboss_style(), Slic3r::GUI::GLGizmoEmboss::draw_style_add_button(), Slic3r::GUI::Emboss::StyleManager::load_style(), Slic3r::GUI::EmbossStylesSerializable::load_style(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), Slic3r::GUI::Emboss::StyleManager::set_wx_font(), and Slic3r::GUI::EmbossStylesSerializable::store_styles().
get_human_readable_name()
std::string WxFontUtils::get_human_readable_name (const wxFont & font) static
{
    if (!font.IsOk()) return "Font is NOT ok.";
    // Face name is optional in wxFont
    if (!font.GetFaceName().empty()) {
        return std::string(font.GetFaceName().c_str());
    } else {
        return std::string((font.GetFamilyString() + " " +
                            font.GetStyleString() + " " +
                            font.GetWeightString())
                               .c_str());
    }
}
Referenced by create_emboss_style(), create_font_file(), and load_wxFont().
is_bold()
bool WxFontUtils::is_bold (const wxFont & font) static
{
    wxFontWeight wx_weight = font.GetWeight();
    return wx_weight != wxFONTWEIGHT_NORMAL;
}
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_bold_button(), and Slic3r::GUI::Emboss::StyleManager::is_font_changed().
is_italic()
bool WxFontUtils::is_italic (const wxFont & font) static
{
    wxFontStyle wx_style = font.GetStyle();
    return wx_style == wxFONTSTYLE_ITALIC ||
        wx_style == wxFONTSTYLE_SLANT;
}
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_italic_button(), and Slic3r::GUI::Emboss::StyleManager::is_font_changed().
load_wxFont()
wxFont WxFontUtils::load_wxFont (const std::string & font_descriptor) static
{
    BOOST_LOG_TRIVIAL(trace) << "'" << font_descriptor << "'font descriptor string param of load_wxFont()";
    wxString font_descriptor_wx(font_descriptor);
    BOOST_LOG_TRIVIAL(trace) << "'" << font_descriptor_wx.c_str() << "' wx string descriptor";
    wxFont wx_font(font_descriptor_wx);
    BOOST_LOG_TRIVIAL(trace) << "loaded font is '" << get_human_readable_name(wx_font) << "'.";
    return wx_font;
}
References get_human_readable_name().
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_font_list_line(), Slic3r::GUI::Emboss::StyleManager::init_style_images(), Slic3r::GUI::Emboss::StyleManager::load_style(), and Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection().
set_bold()
std::unique_ptr< Emboss::FontFile > WxFontUtils::set_bold (wxFont & font, const Slic3r::Emboss::FontFile & font_file) static
Set boldness into wx font When bolded font is same as original return nullptr. To not load font file twice on success is font_file returned.
Parameters
font wx descriptor of font
font_file file described in wx font
Returns
New created font fileon success otherwise nullptr
{
    static std::vector<wxFontWeight> bold_weight = {
        wxFontWeight::wxFONTWEIGHT_BOLD,
        wxFontWeight::wxFONTWEIGHT_HEAVY,
        wxFontWeight::wxFONTWEIGHT_EXTRABOLD,
        wxFontWeight::wxFONTWEIGHT_EXTRAHEAVY
    };
    wxFontWeight orig_weight = font.GetWeight();
    for (wxFontWeight weight : bold_weight) {
        font.SetWeight(weight);
        std::unique_ptr<Emboss::FontFile> new_font_file =
            WxFontUtils::create_font_file(font);
        // can create bold font file?
        if (new_font_file == nullptr) continue;
        // is still same font file pointer?
        if (font_file == *new_font_file) continue;
        return new_font_file;
    }
    // There is NO bold font by wx
    font.SetWeight(orig_weight);
    return nullptr;
}
References create_font_file().
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_bold_button().
set_italic()
std::unique_ptr< Emboss::FontFile > WxFontUtils::set_italic (wxFont & font, const Slic3r::Emboss::FontFile & prev_font_file) static
Set italic into wx font When italic font is same as original return nullptr. To not load font file twice on success is font_file returned.
Parameters
font wx descriptor of font
font_file file described in wx font
Returns
New created font fileon success otherwise nullptr
{
    static std::vector<wxFontStyle> italic_styles = {
        wxFontStyle::wxFONTSTYLE_ITALIC,
        wxFontStyle::wxFONTSTYLE_SLANT
    };
    wxFontStyle orig_style = font.GetStyle();
    for (wxFontStyle style : italic_styles) {
        font.SetStyle(style);
        std::unique_ptr<Emboss::FontFile> new_font_file =
            WxFontUtils::create_font_file(font);
        // can create italic font?
        if (new_font_file == nullptr) continue;
        // is still same font file pointer?
        if (font_file == *new_font_file) continue;
        return new_font_file;
    }
    // There is NO italic font by wx
    font.SetStyle(orig_style);
    return nullptr;
}
References create_font_file(), and style.
Referenced by Slic3r::GUI::GLGizmoEmboss::draw_italic_button().
store_wxFont()
std::string WxFontUtils::store_wxFont (const wxFont & font) static
{
    // wxString os = wxPlatformInfo::Get().GetOperatingSystemIdName();
    wxString font_descriptor = font.GetNativeFontInfoDesc();
    BOOST_LOG_TRIVIAL(trace) << "'" << font_descriptor << "' wx string get from GetNativeFontInfoDesc. wxFont " <<
        "IsOk(" << font.IsOk() << "), " <<
        "isNull(" << font.IsNull() << ")" <<
        // "IsFree(" << font.IsFree() << "), " << // on MacOs is no function is free
        "IsFixedWidth(" << font.IsFixedWidth() << "), " <<
        "IsUsingSizeInPixels(" << font.IsUsingSizeInPixels() << "), " <<
        "Encoding(" << (int)font.GetEncoding() << "), " ;
    return std::string(font_descriptor.c_str());
}
Referenced by priv::create_emboss_data_base(), create_emboss_style(), and Slic3r::GUI::Emboss::StyleManager::set_wx_font().
update_property()
void WxFontUtils::update_property (FontProp & font_prop, const wxFont & font) static
{
    wxString wx_face_name = font.GetFaceName();
    std::string face_name((const char *) wx_face_name.ToUTF8());
    if (!face_name.empty()) font_prop.face_name = face_name;
    wxFontFamily wx_family = font.GetFamily();
    if (wx_family != wxFONTFAMILY_DEFAULT) {
        auto it = type_to_family.left.find(wx_family);
        if (it != type_to_family.left.end()) font_prop.family = it->second;
    }
    wxFontStyle wx_style = font.GetStyle();
    if (wx_style != wxFONTSTYLE_NORMAL) {
        auto it = type_to_style.left.find(wx_style);
        if (it != type_to_style.left.end()) font_prop.style = it->second;
    }
    wxFontWeight wx_weight = font.GetWeight();
    if (wx_weight != wxFONTWEIGHT_NORMAL) {
        auto it = type_to_weight.left.find(wx_weight);
        if (it != type_to_weight.left.end()) font_prop.weight = it->second;
    }
}
References Slic3r::FontProp::face_name, Slic3r::FontProp::family, Slic3r::FontProp::style, type_to_family, type_to_style, type_to_weight, and Slic3r::FontProp::weight.
Referenced by create_emboss_style(), and Slic3r::GUI::Emboss::StyleManager::set_wx_font().
Member Data Documentation
type_to_family
const TypeToFamily WxFontUtils::type_to_family static
Initial value:
=
    boost::assign::list_of<TypeToFamily::relation>
        (wxFONTFAMILY_DEFAULT,    "default")
        (wxFONTFAMILY_DECORATIVE, "decorative")
        (wxFONTFAMILY_ROMAN,      "roman")
        (wxFONTFAMILY_SCRIPT,     "script")
        (wxFONTFAMILY_SWISS,      "swiss")
        (wxFONTFAMILY_MODERN,     "modern")
        (wxFONTFAMILY_TELETYPE,   "teletype")
Referenced by create_wxFont(), and update_property().
type_to_style
const TypeToStyle WxFontUtils::type_to_style static
Initial value:
=
    boost::assign::list_of<TypeToStyle::relation>
        (wxFONTSTYLE_ITALIC, "italic")
        (wxFONTSTYLE_SLANT,  "slant")
        (wxFONTSTYLE_NORMAL, "normal")
Referenced by create_wxFont(), and update_property().
type_to_weight
const TypeToWeight WxFontUtils::type_to_weight static
Initial value:
=
    boost::assign::list_of<TypeToWeight::relation>
        (wxFONTWEIGHT_THIN,       "thin")
        (wxFONTWEIGHT_EXTRALIGHT, "extraLight")
        (wxFONTWEIGHT_LIGHT,      "light")
        (wxFONTWEIGHT_NORMAL,     "normal")
        (wxFONTWEIGHT_MEDIUM,     "medium")
        (wxFONTWEIGHT_SEMIBOLD,   "semibold")
        (wxFONTWEIGHT_BOLD,       "bold")
        (wxFONTWEIGHT_EXTRABOLD,  "extraBold")
        (wxFONTWEIGHT_HEAVY,      "heavy")
        (wxFONTWEIGHT_EXTRAHEAVY, "extraHeavy")
Referenced by create_wxFont(), and update_property().
The documentation for this class was generated from the following files:
src/slic3r/Utils/WxFontUtils.hpp
src/slic3r/Utils/WxFontUtils.cpp