Prusa Slicer: Slic3r::sla::PillarIndex Class Reference
Slic3r::sla::PillarIndex Class Reference
#include <src/libslic3r/SLA/DefaultSupportTree.hpp>
Public Member Functions
template<class... Args>
void guarded_insert (Args &&...args)
template<class... Args>
std::vector< PointIndexEl > guarded_query (Args &&...args) const
template<class... Args>
void insert (Args &&...args)
template<class... Args>
std::vector< PointIndexEl > query (Args &&...args) const
template<class Fn >
void foreach (Fn fn)
template<class Fn >
void guarded_foreach (Fn fn)
PointIndex guarded_clone ()
Private Types
using Mutex = execution::BlockingMutex< decltype(suptree_ex_policy)>
Private Attributes
PointIndex m_index
Mutex m_mutex
Detailed Description
Member Typedef Documentation
Mutex
using Slic3r::sla::PillarIndex::Mutex = execution::BlockingMutex<decltype(suptree_ex_policy)> private
Member Function Documentation
foreach()
template<class Fn > void Slic3r::sla::PillarIndex::foreach (Fn fn) inline
{ m_index.foreach(fn); }
References Slic3r::sla::PointIndex::foreach(), and m_index.
guarded_clone()
PointIndex Slic3r::sla::PillarIndex::guarded_clone () inline
    {
        std::lock_guard<Mutex> lck(m_mutex);
        return m_index;
    }
References m_index, and m_mutex.
Referenced by Slic3r::sla::DefaultSupportTree::search_pillar_and_connect().
guarded_foreach()
template<class Fn > void Slic3r::sla::PillarIndex::guarded_foreach (Fn fn) inline
    {
        std::lock_guard<Mutex> lck(m_mutex);
        m_index.foreach(fn);
    }
References Slic3r::sla::PointIndex::foreach(), m_index, and m_mutex.
guarded_insert()
template<class... Args> void Slic3r::sla::PillarIndex::guarded_insert (Args &&... args) inline
    {
        std::lock_guard<Mutex> lck(m_mutex);
        m_index.insert(std::forward<Args>(args)...);
    }
References Slic3r::sla::PointIndex::insert(), m_index, and m_mutex.
Referenced by Slic3r::sla::DefaultSupportTree::connect_to_ground(), Slic3r::sla::DefaultSupportTree::connect_to_model_body(), and Slic3r::sla::DefaultSupportTree::create_ground_pillar().
guarded_query()
template<class... Args> std::vector< PointIndexEl > Slic3r::sla::PillarIndex::guarded_query (Args &&... args) const inline
    {
        std::lock_guard<Mutex> lck(m_mutex);
        return m_index.query(std::forward<Args>(args)...);
    }
References m_index, m_mutex, and Slic3r::sla::PointIndex::query().
insert()
template<class... Args> void Slic3r::sla::PillarIndex::insert (Args &&... args) inline
    {
        m_index.insert(std::forward<Args>(args)...);
    }
References Slic3r::sla::PointIndex::insert(), and m_index.
query()
template<class... Args> std::vector< PointIndexEl > Slic3r::sla::PillarIndex::query (Args &&... args) const inline
    {
        return m_index.query(std::forward<Args>(args)...);
    }
References m_index, and Slic3r::sla::PointIndex::query().
Referenced by Slic3r::sla::DefaultSupportTree::routing_to_ground().
Member Data Documentation
m_index
PointIndex Slic3r::sla::PillarIndex::m_index private
Referenced by foreach(), guarded_clone(), guarded_foreach(), guarded_insert(), guarded_query(), insert(), and query().
m_mutex
Mutex Slic3r::sla::PillarIndex::m_mutex mutable private
Referenced by guarded_clone(), guarded_foreach(), guarded_insert(), and guarded_query().
The documentation for this class was generated from the following file:
src/libslic3r/SLA/DefaultSupportTree.hpp