Prusa Slicer: Eigen::PastixLDLT< _MatrixType, _UpLo > Class Template Reference
Eigen::PastixLDLT< _MatrixType, _UpLo > Class Template Reference
A sparse direct supernodal Cholesky (LLT) factorization and solver based on the PaStiX library.
#include <src/eigen/Eigen/src/PaStiXSupport/PaStiXSupport.h>
Public Types
enum { UpLo = _UpLo }
typedef _MatrixType MatrixType
typedef PastixBase< PastixLDLT< MatrixType, _UpLo > > Base
typedef Base::ColSpMatrix ColSpMatrix
enum
typedef internal::pastix_traits< PastixLDLT< _MatrixType, _UpLo > >::MatrixType _MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef Matrix< Scalar, Dynamic, 1 > Vector
Public Member Functions
PastixLDLT ()
PastixLDLT (const MatrixType &matrix)
void compute (const MatrixType &matrix)
void analyzePattern (const MatrixType &matrix)
void factorize (const MatrixType &matrix)
bool _solve_impl (const MatrixBase< Rhs > &b, MatrixBase< Dest > &x) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Array< StorageIndex, IPARM_SIZE, 1 > & iparm ()
int & iparm (int idxparam)
Array< double, DPARM_SIZE, 1 > & dparm ()
double & dparm (int idxparam)
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
Protected Member Functions
void init ()
void grabMatrix (const MatrixType &matrix, ColSpMatrix &out)
void analyzePattern (ColSpMatrix &mat)
void factorize (ColSpMatrix &mat)
void clean ()
void compute (ColSpMatrix &mat)
PastixLDLT< _MatrixType, _UpLo > & derived ()
const PastixLDLT< _MatrixType, _UpLo > & derived () const
Protected Attributes
Array< int, IPARM_SIZE, 1 > m_iparm
int m_initisOk
int m_analysisIsOk
int m_factorizationIsOk
ComputationInfo m_info
pastix_data_t * m_pastixdata
int m_comm
Array< double, DPARM_SIZE, 1 > m_dparm
Matrix< StorageIndex, Dynamic, 1 > m_perm
Matrix< StorageIndex, Dynamic, 1 > m_invp
int m_size
bool m_isInitialized
Detailed Description
template<typename _MatrixType, int _UpLo>
class Eigen::PastixLDLT< _MatrixType, _UpLo >
A sparse direct supernodal Cholesky (LLT) factorization and solver based on the PaStiX library.
This class is used to solve the linear systems A.X = B via a LDL^T supernodal Cholesky factorization available in the PaStiX library. The matrix A should be symmetric and positive definite WARNING Selfadjoint complex matrices are not supported in the current version of PaStiX The vectors or matrices X and B can be either dense or sparse
Template Parameters
MatrixType the type of the sparse matrix A, it must be a SparseMatrix<>
UpLo The part of the matrix to use : Lower or Upper. The default is Lower as required by PaStiX
\implsparsesolverconcept
See also
TutorialSparseSolverConcept, class SimplicialLDLT
Member Typedef Documentation
_MatrixType
typedef internal::pastix_traits<PastixLDLT< _MatrixType, _UpLo > >::MatrixType Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::_MatrixType inherited
Base
template<typename _MatrixType , int _UpLo> typedef PastixBase<PastixLDLT<MatrixType, _UpLo> > Eigen::PastixLDLT< _MatrixType, _UpLo >::Base
ColSpMatrix
template<typename _MatrixType , int _UpLo> typedef Base::ColSpMatrix Eigen::PastixLDLT< _MatrixType, _UpLo >::ColSpMatrix
MatrixType
template<typename _MatrixType , int _UpLo> typedef _MatrixType Eigen::PastixLDLT< _MatrixType, _UpLo >::MatrixType
RealScalar
typedef MatrixType::RealScalar Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::RealScalar inherited
Scalar
typedef MatrixType::Scalar Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::Scalar inherited
StorageIndex
typedef MatrixType::StorageIndex Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::StorageIndex inherited
Vector
typedef Matrix<Scalar,Dynamic,1> Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::Vector inherited
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
         {
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
anonymous enum
template<typename _MatrixType , int _UpLo> anonymous enum
Enumerator
UpLo
{ UpLo = _UpLo };
Constructor & Destructor Documentation
PastixLDLT() [1/2]
template<typename _MatrixType , int _UpLo> Eigen::PastixLDLT< _MatrixType, _UpLo >::PastixLDLT () inline
                :Base()
    {
      init();
    }
References Eigen::PastixLDLT< _MatrixType, _UpLo >::init().
PastixLDLT() [2/2]
template<typename _MatrixType , int _UpLo> Eigen::PastixLDLT< _MatrixType, _UpLo >::PastixLDLT (const MatrixType & matrix) inline explicit
                                                 :Base()
    {
      init();
      compute(matrix);
    }
References Eigen::PastixLDLT< _MatrixType, _UpLo >::compute(), and Eigen::PastixLDLT< _MatrixType, _UpLo >::init().
Member Function Documentation
_solve_impl() [1/2]
bool Eigen::PastixBase< Base >::_solve_impl (const MatrixBase< Rhs > & b, MatrixBase< Dest > & x) const inherited
{
  eigen_assert(m_isInitialized && "The matrix should be factorized first");
  EIGEN_STATIC_ASSERT((Dest::Flags&RowMajorBit)==0,
                     THIS_METHOD_IS_ONLY_FOR_COLUMN_MAJOR_MATRICES);
  int rhs = 1;
  x = b; /* on return, x is overwritten by the computed solution */
  for (int i = 0; i < b.cols(); i++){
    m_iparm[IPARM_START_TASK]          = API_TASK_SOLVE;
    m_iparm[IPARM_END_TASK]            = API_TASK_REFINE;
    internal::eigen_pastix(&m_pastixdata, MPI_COMM_WORLD, internal::convert_index<int>(x.rows()), 0, 0, 0,
                           m_perm.data(), m_invp.data(), &x(0, i), rhs, m_iparm.data(), m_dparm.data());
  }
  // Check the returned error
  m_info = m_iparm(IPARM_ERROR_NUMBER)==0 ? Success : NumericalIssue;
  return m_iparm(IPARM_ERROR_NUMBER)==0;
}
_solve_impl() [2/2]
void Eigen::SparseSolverBase< PastixLDLT< _MatrixType, _UpLo > >::_solve_impl (const SparseMatrixBase< Rhs > & b, SparseMatrixBase< Dest > & dest) const inline inherited
    {
      internal::solve_sparse_through_dense_panels(derived(), b.derived(), dest.derived());
    }
analyzePattern() [1/2]
void Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::analyzePattern (ColSpMatrix & mat) protected inherited
{
  eigen_assert(m_initisOk && "The initialization of PaSTiX failed");
  // clean previous calls
  if(m_size>0)
    clean();
  m_size = internal::convert_index<int>(mat.rows());
  m_perm.resize(m_size);
  m_invp.resize(m_size);
  m_iparm(IPARM_START_TASK) = API_TASK_ORDERING;
  m_iparm(IPARM_END_TASK) = API_TASK_ANALYSE;
  internal::eigen_pastix(&m_pastixdata, MPI_COMM_WORLD, m_size, mat.outerIndexPtr(), mat.innerIndexPtr(),
               mat.valuePtr(), m_perm.data(), m_invp.data(), 0, 0, m_iparm.data(), m_dparm.data());
  // Check the returned error
  if(m_iparm(IPARM_ERROR_NUMBER))
  {
    m_info = NumericalIssue;
    m_analysisIsOk = false;
  }
  else
  {
    m_info = Success;
    m_analysisIsOk = true;
  }
}
analyzePattern() [2/2]
template<typename _MatrixType , int _UpLo> void Eigen::PastixLDLT< _MatrixType, _UpLo >::analyzePattern (const MatrixType & matrix) inline
Compute the LDL^T symbolic factorization of matrix using its sparsity pattern The result of this operation can be used with successive matrices having the same pattern as matrix
See also
factorize()
    {
      ColSpMatrix temp;
      grabMatrix(matrix, temp);
      Base::analyzePattern(temp);
    }
References Eigen::PastixBase< Derived >::analyzePattern(), and Eigen::PastixLDLT< _MatrixType, _UpLo >::grabMatrix().
clean()
void Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::clean () inline protected inherited
    {
      eigen_assert(m_initisOk && "The Pastix structure should be allocated first");
      m_iparm(IPARM_START_TASK) = API_TASK_CLEAN;
      m_iparm(IPARM_END_TASK) = API_TASK_CLEAN;
      internal::eigen_pastix(&m_pastixdata, MPI_COMM_WORLD, 0, 0, 0, (Scalar*)0,
                             m_perm.data(), m_invp.data(), 0, 0, m_iparm.data(), m_dparm.data());
    }
cols()
Index Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::cols () const inline inherited
{ return m_size; }
compute() [1/2]
void Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::compute (ColSpMatrix & mat) protected inherited
{
  eigen_assert(mat.rows() == mat.cols() && "The input matrix should be squared");
  analyzePattern(mat);
  factorize(mat);
  m_iparm(IPARM_MATRIX_VERIFICATION) = API_NO;
}
compute() [2/2]
template<typename _MatrixType , int _UpLo> void Eigen::PastixLDLT< _MatrixType, _UpLo >::compute (const MatrixType & matrix) inline
Compute the L and D factors of the LDL^T factorization of matrix
See also
analyzePattern() factorize()
    {
      ColSpMatrix temp;
      grabMatrix(matrix, temp);
      Base::compute(temp);
    }
References Eigen::PastixBase< Derived >::compute(), and Eigen::PastixLDLT< _MatrixType, _UpLo >::grabMatrix().
Referenced by Eigen::PastixLDLT< _MatrixType, _UpLo >::PastixLDLT().
derived() [1/2]
PastixLDLT< _MatrixType, _UpLo > & Eigen::SparseSolverBase< PastixLDLT< _MatrixType, _UpLo > >::derived () inline protected inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
const PastixLDLT< _MatrixType, _UpLo > & Eigen::SparseSolverBase< PastixLDLT< _MatrixType, _UpLo > >::derived () const inline protected inherited
{ return *static_cast<const Derived*>(this); }
dparm() [1/2]
Array< double, DPARM_SIZE, 1 > & Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::dparm () inline inherited
Returns a reference to the double vector DPARM of PaStiX parameters The statistics related to the different phases of factorization and solve are saved here as well
See also
analyzePattern() factorize()
    {
      return m_dparm;
    }
dparm() [2/2]
double & Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::dparm (int idxparam) inline inherited
Return a reference to a particular index parameter of the DPARM vector
See also
dparm()
    {
      return m_dparm(idxparam);
    }
factorize() [1/2]
void Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::factorize (ColSpMatrix & mat) protected inherited
{
//   if(&m_cpyMat != &mat) m_cpyMat = mat;
  eigen_assert(m_analysisIsOk && "The analysis phase should be called before the factorization phase");
  m_iparm(IPARM_START_TASK) = API_TASK_NUMFACT;
  m_iparm(IPARM_END_TASK) = API_TASK_NUMFACT;
  m_size = internal::convert_index<int>(mat.rows());
  internal::eigen_pastix(&m_pastixdata, MPI_COMM_WORLD, m_size, mat.outerIndexPtr(), mat.innerIndexPtr(),
               mat.valuePtr(), m_perm.data(), m_invp.data(), 0, 0, m_iparm.data(), m_dparm.data());
  // Check the returned error
  if(m_iparm(IPARM_ERROR_NUMBER))
  {
    m_info = NumericalIssue;
    m_factorizationIsOk = false;
    m_isInitialized = false;
  }
  else
  {
    m_info = Success;
    m_factorizationIsOk = true;
    m_isInitialized = true;
  }
}
factorize() [2/2]
template<typename _MatrixType , int _UpLo> void Eigen::PastixLDLT< _MatrixType, _UpLo >::factorize (const MatrixType & matrix) inline
Compute the LDL^T supernodal numerical factorization of matrix
    {
      ColSpMatrix temp;
      grabMatrix(matrix, temp);
      Base::factorize(temp);
    }
References Eigen::PastixBase< Derived >::factorize(), and Eigen::PastixLDLT< _MatrixType, _UpLo >::grabMatrix().
grabMatrix()
template<typename _MatrixType , int _UpLo> void Eigen::PastixLDLT< _MatrixType, _UpLo >::grabMatrix (const MatrixType & matrix, ColSpMatrix & out) inline protected
    {
      // Pastix supports only lower, column-major matrices
      out.resize(matrix.rows(), matrix.cols());
      out.template selfadjointView<Lower>() = matrix.template selfadjointView<UpLo>();
      internal::c_to_fortran_numbering(out);
    }
References Eigen::internal::c_to_fortran_numbering(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize().
Referenced by Eigen::PastixLDLT< _MatrixType, _UpLo >::analyzePattern(), Eigen::PastixLDLT< _MatrixType, _UpLo >::compute(), and Eigen::PastixLDLT< _MatrixType, _UpLo >::factorize().
info()
ComputationInfo Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::info () const inline inherited
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NumericalIssue if the PaStiX reports a problem InvalidInput if the input matrix is invalid
See also
iparm()
    {
      eigen_assert(m_isInitialized && "Decomposition is not initialized.");
      return m_info;
    }
init()
template<typename _MatrixType , int _UpLo> void Eigen::PastixLDLT< _MatrixType, _UpLo >::init () inline protected
    {
      m_iparm(IPARM_SYM) = API_SYM_YES;
      m_iparm(IPARM_FACTORIZATION) = API_FACT_LDLT;
    }
References Eigen::PastixLDLT< _MatrixType, _UpLo >::m_iparm.
Referenced by Eigen::PastixLDLT< _MatrixType, _UpLo >::PastixLDLT(), and Eigen::PastixLDLT< _MatrixType, _UpLo >::PastixLDLT().
iparm() [1/2]
Array< StorageIndex, IPARM_SIZE, 1 > & Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::iparm () inline inherited
Returns a reference to the integer vector IPARM of PaStiX parameters to modify the default parameters. The statistics related to the different phases of factorization and solve are saved here as well
See also
analyzePattern() factorize()
    {
      return m_iparm;
    }
iparm() [2/2]
int & Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::iparm (int idxparam) inline inherited
Return a reference to a particular index parameter of the IPARM vector
See also
iparm()
    {
      return m_iparm(idxparam);
    }
rows()
Index Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::rows () const inline inherited
{ return m_size; }
solve() [1/2]
template<typename Derived > template<typename Rhs > const Solve< Derived, Rhs > Eigen::SparseSolverBase< Derived >::solve (const MatrixBase< Rhs > & b) const inline inherited
Returns
an expression of the solution x of using the current decomposition of A.
See also
compute()
    {
      eigen_assert(m_isInitialized && "Solver is not initialized.");
      eigen_assert(derived().rows()==b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
      return Solve<Derived, Rhs>(derived(), b.derived());
    }
References Eigen::SparseSolverBase< Derived >::derived(), eigen_assert, and Eigen::SparseSolverBase< Derived >::m_isInitialized.
Referenced by igl::embree::bone_heat(), igl::Frame_field_deformer::compute_optimal_positions(), igl::eigs(), igl::copyleft::comiso::FrameInterpolator::interpolateSymmetric(), igl::slim::solve_weighted_arap(), and igl::copyleft::comiso::NRosyField::solveNoRoundings().
solve() [2/2]
template<typename Derived > template<typename Rhs > const Solve< Derived, Rhs > Eigen::SparseSolverBase< Derived >::solve (const SparseMatrixBase< Rhs > & b) const inline inherited
Returns
an expression of the solution x of using the current decomposition of A.
See also
compute()
    {
      eigen_assert(m_isInitialized && "Solver is not initialized.");
      eigen_assert(derived().rows()==b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
      return Solve<Derived, Rhs>(derived(), b.derived());
    }
Member Data Documentation
m_analysisIsOk
int Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_analysisIsOk protected inherited
m_comm
int Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_comm mutable protected inherited
m_dparm
Array<double,DPARM_SIZE,1> Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_dparm mutable protected inherited
m_factorizationIsOk
int Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_factorizationIsOk protected inherited
m_info
ComputationInfo Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_info mutable protected inherited
m_initisOk
int Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_initisOk protected inherited
m_invp
Matrix<StorageIndex,Dynamic,1> Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_invp mutable protected inherited
m_iparm
template<typename _MatrixType , int _UpLo> Array<int,IPARM_SIZE,1> Eigen::PastixBase< Derived >::m_iparm mutable protected
Referenced by Eigen::PastixLDLT< _MatrixType, _UpLo >::init().
m_isInitialized
bool Eigen::SparseSolverBase< PastixLDLT< _MatrixType, _UpLo > >::m_isInitialized mutable protected inherited
m_pastixdata
pastix_data_t* Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_pastixdata mutable protected inherited
m_perm
Matrix<StorageIndex,Dynamic,1> Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_perm mutable protected inherited
m_size
int Eigen::PastixBase< PastixLDLT< _MatrixType, _UpLo > >::m_size mutable protected inherited
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/PaStiXSupport/PaStiXSupport.h