Prusa Slicer: Eigen::half Struct Reference
Eigen::half Struct Reference
#include <src/eigen/Eigen/src/Core/arch/CUDA/Half.h>
Public Types
typedef half_impl::__half_raw __half_raw
Public Member Functions
EIGEN_DEVICE_FUNC half ()
EIGEN_DEVICE_FUNC half (const __half_raw &h)
EIGEN_DEVICE_FUNC half (const half &h)
EIGEN_DEVICE_FUNC half (bool b)
template<class T >
EIGEN_DEVICE_FUNC half (const T &val)
EIGEN_DEVICE_FUNC half (float f)
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (bool) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (signed char) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned char) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (short) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned short) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (int) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned int) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (long) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned long) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (long long) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (unsigned long long) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (float) const
EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST (double) const
EIGEN_DEVICE_FUNC half & operator= (const half &other)
Public Attributes
unsigned short x
Detailed Description
Member Typedef Documentation
__half_raw
typedef half_impl::__half_raw Eigen::half::__half_raw
Constructor & Destructor Documentation
half() [1/6]
EIGEN_DEVICE_FUNC Eigen::half::half () inline
{}
half() [2/6]
EIGEN_DEVICE_FUNC Eigen::half::half (const __half_raw & h) inline
: half_impl::half_base(h) {}
half() [3/6]
EIGEN_DEVICE_FUNC Eigen::half::half (const half & h) inline
: half_impl::half_base(h) {}
half() [4/6]
EIGEN_DEVICE_FUNC Eigen::half::half (bool b) inline explicit
      : half_impl::half_base(half_impl::raw_uint16_to_half(b ? 0x3c00 : 0)) {}
half() [5/6]
template<class T > EIGEN_DEVICE_FUNC Eigen::half::half (const T & val) inline explicit
      : half_impl::half_base(half_impl::float_to_half_rtne(static_cast<float>(val))) {}
half() [6/6]
EIGEN_DEVICE_FUNC Eigen::half::half (float f) inline explicit
      : half_impl::half_base(half_impl::float_to_half_rtne(f)) {}
Member Function Documentation
EIGEN_EXPLICIT_CAST() [1/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (bool) const inline
{
    // +0.0 and -0.0 become false, everything else becomes true.
    return (x & 0x7fff) != 0;
  }
References Eigen::half_impl::__half_raw::x.
EIGEN_EXPLICIT_CAST() [2/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (double) const inline
{
    return static_cast<double>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [3/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (float) const inline
{
    return half_impl::half_to_float(*this);
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [4/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (int) const inline
{
    return static_cast<int>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [5/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (long long) const inline
{
    return static_cast<long long>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [6/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (long) const inline
{
    return static_cast<long>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [7/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (short) const inline
{
    return static_cast<short>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [8/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (signed char) const inline
{
    return static_cast<signed char>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [9/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned char) const inline
{
    return static_cast<unsigned char>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [10/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned int) const inline
{
    return static_cast<unsigned int>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [11/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned long long) const inline
{
    return static_cast<unsigned long long>(half_to_float(*this));
  }
EIGEN_EXPLICIT_CAST() [12/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned long) const inline
{
    return static_cast<unsigned long>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
EIGEN_EXPLICIT_CAST() [13/13]
EIGEN_DEVICE_FUNC Eigen::half::EIGEN_EXPLICIT_CAST (unsigned short) const inline
{
    return static_cast<unsigned short>(half_impl::half_to_float(*this));
  }
References Eigen::half_impl::half_to_float().
operator=()
EIGEN_DEVICE_FUNC half & Eigen::half::operator= (const half & other) inline
{
    x = other.x;
    return *this;
  }
References Eigen::half_impl::__half_raw::x.
Member Data Documentation
x
unsigned short Eigen::half_impl::__half_raw::x inherited
Referenced by Eigen::half_impl::abs(), Slic3r::GUI::CameraUtils::create_hull2d(), EIGEN_EXPLICIT_CAST(), fabsh(), Eigen::half_impl::float_to_half_rtne(), Eigen::half_impl::half_to_float(), Slic3r::GUI::GCodeViewer::load(), Slic3r::branchingtree::make_bed_poly(), Eigen::half_impl::operator-(), operator=(), and Eigen::half_impl::raw_uint16_to_half().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/arch/CUDA/Half.h