Prusa Slicer: Slic3r::ClipperUtils Namespace Reference
Slic3r::ClipperUtils Namespace Reference
Classes
class EmptyPathsProvider
struct ExPolygonProvider
struct ExPolygonsProvider
class MultiPointsProvider
class PathsProvider
class PathsProviderIteratorBase
class SinglePathProvider
struct SurfacesProvider
struct SurfacesPtrProvider
Typedefs
using PolygonsProvider = MultiPointsProvider< Polygons >
using PolylinesProvider = MultiPointsProvider< Polylines >
using ZPoint = Vec3i32
using ZPoints = std::vector< Vec3i32 >
Functions
template<typename PointsType >
void clip_clipper_polygon_with_subject_bbox_templ (const PointsType &src, const BoundingBox &bbox, PointsType &out)
void clip_clipper_polygon_with_subject_bbox (const Points &src, const BoundingBox &bbox, Points &out)
void clip_clipper_polygon_with_subject_bbox (const ZPoints &src, const BoundingBox &bbox, ZPoints &out)
template<typename PointsType >
PointsType clip_clipper_polygon_with_subject_bbox_templ (const PointsType &src, const BoundingBox &bbox)
Points clip_clipper_polygon_with_subject_bbox (const Points &src, const BoundingBox &bbox)
ZPoints clip_clipper_polygon_with_subject_bbox (const ZPoints &src, const BoundingBox &bbox)
void clip_clipper_polygon_with_subject_bbox (const Polygon &src, const BoundingBox &bbox, Polygon &out)
Polygon clip_clipper_polygon_with_subject_bbox (const Polygon &src, const BoundingBox &bbox)
Polygons clip_clipper_polygons_with_subject_bbox (const Polygons &src, const BoundingBox &bbox)
Polygons clip_clipper_polygons_with_subject_bbox (const ExPolygon &src, const BoundingBox &bbox)
Typedef Documentation
PolygonsProvider
using Slic3r::ClipperUtils::PolygonsProvider = typedef MultiPointsProvider<Polygons>
PolylinesProvider
using Slic3r::ClipperUtils::PolylinesProvider = typedef MultiPointsProvider<Polylines>
ZPoint
using Slic3r::ClipperUtils::ZPoint = typedef Vec3i32
ZPoints
using Slic3r::ClipperUtils::ZPoints = typedef std::vector<Vec3i32>
Function Documentation
clip_clipper_polygon_with_subject_bbox() [1/6]
Points Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const Points & src, const BoundingBox & bbox)
        { return clip_clipper_polygon_with_subject_bbox_templ(src, bbox); }
References clip_clipper_polygon_with_subject_bbox_templ().
clip_clipper_polygon_with_subject_bbox() [2/6]
void Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const Points & src, const BoundingBox & bbox, Points & out)
        { clip_clipper_polygon_with_subject_bbox_templ(src, bbox, out); }
References clip_clipper_polygon_with_subject_bbox_templ().
Referenced by clip_clipper_polygon_with_subject_bbox(), clip_clipper_polygon_with_subject_bbox(), clip_clipper_polygon_with_subject_bbox_templ(), clip_clipper_polygons_with_subject_bbox(), clip_clipper_polygons_with_subject_bbox(), and Slic3r::traverse_extrusions().
clip_clipper_polygon_with_subject_bbox() [3/6]
Polygon Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const Polygon & src, const BoundingBox & bbox)
    {
        Polygon out;
        clip_clipper_polygon_with_subject_bbox(src.points, bbox, out.points);
        return out;
    }
References clip_clipper_polygon_with_subject_bbox(), and Slic3r::MultiPoint::points.
clip_clipper_polygon_with_subject_bbox() [4/6]
void Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const Polygon & src, const BoundingBox & bbox, Polygon & out)
    {
        clip_clipper_polygon_with_subject_bbox(src.points, bbox, out.points);
    }
References clip_clipper_polygon_with_subject_bbox(), and Slic3r::MultiPoint::points.
clip_clipper_polygon_with_subject_bbox() [5/6]
ZPoints Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const ZPoints & src, const BoundingBox & bbox)
        { return clip_clipper_polygon_with_subject_bbox_templ(src, bbox); }
References clip_clipper_polygon_with_subject_bbox_templ().
clip_clipper_polygon_with_subject_bbox() [6/6]
void Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const ZPoints & src, const BoundingBox & bbox, ZPoints & out)
        { clip_clipper_polygon_with_subject_bbox_templ(src, bbox, out); }
References clip_clipper_polygon_with_subject_bbox_templ().
clip_clipper_polygon_with_subject_bbox_templ() [1/2]
template<typename PointsType > PointsType Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox_templ (const PointsType & src, const BoundingBox & bbox)
    {
        PointsType out;
        clip_clipper_polygon_with_subject_bbox(src, bbox, out);
        return out;
    }
References clip_clipper_polygon_with_subject_bbox().
clip_clipper_polygon_with_subject_bbox_templ() [2/2]
template<typename PointsType > void Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox_templ (const PointsType & src, const BoundingBox & bbox, PointsType & out) inline
    {
        using PointType = typename PointsType::value_type;
        out.clear();
        const size_t cnt = src.size();
        if (cnt < 3)
            return;
        enum class Side {
            Left   = 1,
            Right  = 2,
            Top    = 4,
            Bottom = 8
        };
        auto sides = [bbox](const PointType &p) {
            return  int(p.x() < bbox.min.x()) * int(Side::Left) +
                    int(p.x() > bbox.max.x()) * int(Side::Right) +
                    int(p.y() < bbox.min.y()) * int(Side::Bottom) +
                    int(p.y() > bbox.max.y()) * int(Side::Top);
        };
        int sides_prev = sides(src.back());
        int sides_this = sides(src.front());
        const size_t last = cnt - 1;
        for (size_t i = 0; i < last; ++ i) {
            int sides_next = sides(src[i + 1]);
            if (// This point is inside. Take it.
                sides_this == 0 ||
                // Either this point is outside and previous or next is inside, or
                // the edge possibly cuts corner of the bounding box.
                (sides_prev & sides_this & sides_next) == 0) {
                out.emplace_back(src[i]);
                sides_prev = sides_this;
            } else {
                // All the three points (this, prev, next) are outside at the same side.
                // Ignore this point.
            }
            sides_this = sides_next;
        }
        // Never produce just a single point output polygon.
        if (! out.empty())
            if (int sides_next = sides(out.front());
                // The last point is inside. Take it.
                sides_this == 0 ||
                // Either this point is outside and previous or next is inside, or
                // the edge possibly cuts corner of the bounding box.
                (sides_prev & sides_this & sides_next) == 0)
                out.emplace_back(src.back());
    }
References Slic3r::BoundingBoxBase< PointType, APointsType >::max, and Slic3r::BoundingBoxBase< PointType, APointsType >::min.
Referenced by clip_clipper_polygon_with_subject_bbox(), clip_clipper_polygon_with_subject_bbox(), clip_clipper_polygon_with_subject_bbox(), and clip_clipper_polygon_with_subject_bbox().
clip_clipper_polygons_with_subject_bbox() [1/2]
Polygons Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox (const ExPolygon & src, const BoundingBox & bbox)
    {
        Polygons out;
        out.reserve(src.num_contours());
        out.emplace_back(clip_clipper_polygon_with_subject_bbox(src.contour, bbox));
        for (const Polygon &p : src.holes)
            out.emplace_back(clip_clipper_polygon_with_subject_bbox(p, bbox));
        out.erase(
            std::remove_if(out.begin(), out.end(), [](const Polygon &polygon) { return polygon.empty(); }),
            out.end());
        return out;
    }
References clip_clipper_polygon_with_subject_bbox(), Slic3r::ExPolygon::contour, Slic3r::ExPolygon::holes, and Slic3r::ExPolygon::num_contours().
clip_clipper_polygons_with_subject_bbox() [2/2]
Polygons Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox (const Polygons & src, const BoundingBox & bbox)
    {
        Polygons out;
        out.reserve(src.size());
        for (const Polygon &p : src)
            out.emplace_back(clip_clipper_polygon_with_subject_bbox(p, bbox));
        out.erase(
            std::remove_if(out.begin(), out.end(), [](const Polygon &polygon) { return polygon.empty(); }),
            out.end());
        return out;
    }
References clip_clipper_polygon_with_subject_bbox().
Referenced by Slic3r::diff_clipped(), Slic3r::SupportSpotsGenerator::estimate_slice_connection(), Slic3r::generate_extra_perimeters_over_overhangs(), Slic3r::intersection_clipped(), Slic3r::Algorithm::propagate_wave_from_boundary(), Slic3r::FFFTreeSupport::safe_offset_inc(), Slic3r::RetractWhenCrossingPerimeters::travel_inside_internal_regions(), and Slic3r::traverse_loops_classic().