Prusa Slicer: Eigen::SolverBase< Derived > Class Template Reference
Eigen::SolverBase< Derived > Class Template Reference
A base class for matrix decomposition and solvers.
#include <src/eigen/Eigen/src/Core/SolverBase.h>
Public Types
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime
}
typedef EigenBase< Derived > Base
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef internal::add_const< Transpose< constDerived > >::type ConstTransposeReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, ConstTransposeReturnType >, ConstTransposeReturnType >::type AdjointReturnType
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
SolverBase ()
~SolverBase ()
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
ConstTransposeReturnType transpose () const
AdjointReturnType adjoint () const
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Detailed Description
template<typename Derived>
class Eigen::SolverBase< Derived >
A base class for matrix decomposition and solvers.
Template Parameters
Derived the actual type of the decomposition/solver.
Any matrix decomposition inheriting this base class provide the following API:
MatrixType A, b, x;
DecompositionType dec(A);
x = dec.solve(b);             // solve A   * x = b
x = dec.transpose().solve(b); // solve A^T * x = b
x = dec.adjoint().solve(b);   // solve A'  * x = b
Warning
Currently, any other usage of transpose() and adjoint() are not supported and will produce compilation errors.
See also
class PartialPivLU, class FullPivLU
Member Typedef Documentation
AdjointReturnType
template<typename Derived > typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,ConstTransposeReturnType>,ConstTransposeReturnType>::type Eigen::SolverBase< Derived >::AdjointReturnType
Base
template<typename Derived > typedef EigenBase<Derived> Eigen::SolverBase< Derived >::Base
CoeffReturnType
template<typename Derived > typedef Scalar Eigen::SolverBase< Derived >::CoeffReturnType
ConstTransposeReturnType
template<typename Derived > typedef internal::add_const<Transpose<constDerived>>::type Eigen::SolverBase< Derived >::ConstTransposeReturnType
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::SolverBase< Derived >::Scalar
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::EigenBase< Derived >::StorageKind inherited
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
SizeAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxSizeAtCompileTime
IsVectorAtCompileTime
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                          internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::MaxRowsAtCompileTime,
                                                             internal::traits<Derived>::MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime == 1
                           || internal::traits<Derived>::MaxColsAtCompileTime == 1
    };
Constructor & Destructor Documentation
SolverBase()
template<typename Derived > Eigen::SolverBase< Derived >::SolverBase () inline
Default constructor
    {}
~SolverBase()
template<typename Derived > Eigen::SolverBase< Derived >::~SolverBase () inline
    {}
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
template<typename Derived > AdjointReturnType Eigen::SolverBase< Derived >::adjoint () const inline
Returns
an expression of the adjoint of the factored matrix
A typical usage is to solve for the adjoint problem A' x = b:
x = dec.adjoint().solve(b);
For real scalar types, this function is equivalent to transpose().
See also
transpose(), solve()
    {
      return AdjointReturnType(derived().transpose());
    }
References Eigen::SolverBase< Derived >::derived(), and Eigen::SolverBase< Derived >::transpose().
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
cols()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::cols () const inline inherited
Returns
the number of columns.
See also
rows(), ColsAtCompileTime
{ return derived().cols(); }
References Eigen::EigenBase< Derived >::derived().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::ComplexEigenSolver< _MatrixType >::compute(), Eigen::EigenSolver< _MatrixType >::compute(), Eigen::ComplexSchur< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::compute(), Eigen::EigenBase< Derived >::size(), and Eigen::EigenBase< Derived >::subTo().
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::derived () inline
Returns
a reference to the derived object
{ return *static_cast<Derived*>(this); }
Referenced by Eigen::SolverBase< Derived >::adjoint(), Eigen::SolverBase< Derived >::solve(), and Eigen::SolverBase< Derived >::transpose().
derived() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::derived () const inline
Returns
a const reference to the derived object
{ return *static_cast<const Derived*>(this); }
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
Referenced by Eigen::EigenBase< Derived >::subTo().
rows()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::rows () const inline inherited
Returns
the number of rows.
See also
cols(), RowsAtCompileTime
{ return derived().rows(); }
Referenced by Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition(), Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::HessenbergDecomposition< _MatrixType >::compute(), Eigen::Tridiagonalization< _MatrixType >::compute(), Eigen::ComplexEigenSolver< _MatrixType >::compute(), Eigen::EigenSolver< _MatrixType >::compute(), Eigen::ComplexSchur< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::compute(), Eigen::EigenBase< Derived >::size(), Eigen::SolverBase< Derived >::solve(), and Eigen::EigenBase< Derived >::subTo().
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
References Eigen::EigenBase< Derived >::cols(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
solve()
template<typename Derived > template<typename Rhs > const Solve< Derived, Rhs > Eigen::SolverBase< Derived >::solve (const MatrixBase< Rhs > & b) const inline
Returns
an expression of the solution x of using the current decomposition of A.
    {
      eigen_assert(derived().rows()==b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
      return Solve<Derived, Rhs>(derived(), b.derived());
    }
References Eigen::SolverBase< Derived >::derived(), eigen_assert, and Eigen::EigenBase< Derived >::rows().
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
transpose()
template<typename Derived > ConstTransposeReturnType Eigen::SolverBase< Derived >::transpose () const inline
Returns
an expression of the transposed of the factored matrix.
A typical usage is to solve for the transposed problem A^T x = b:
x = dec.transpose().solve(b);
See also
adjoint(), solve()
    {
      return ConstTransposeReturnType(derived());
    }
References Eigen::SolverBase< Derived >::derived().
Referenced by Eigen::SolverBase< Derived >::adjoint().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/SolverBase.h