Prusa Slicer: Slic3r::ThickLine Class Reference
Slic3r::ThickLine Class Reference
#include <src/libslic3r/Line.hpp>
Public Types
using Scalar = Point::Scalar
Public Member Functions
ThickLine ()
ThickLine (const Point &a, const Point &b)
ThickLine (const Point &a, const Point &b, double wa, double wb)
operator Lines () const
void scale (double factor)
void translate (const Point &v)
void translate (double x, double y)
void rotate (double angle, const Point &center)
void reverse ()
double length () const
Point midpoint () const
bool intersection_infinite (const Line &other, Point *point) const
bool operator== (const Line &rhs) const
double distance_to_squared (const Point &point) const
double distance_to_squared (const Point &point, Point *closest_point) const
double distance_to (const Point &point) const
double distance_to_infinite_squared (const Point &point, Point *closest_point) const
double perp_distance_to (const Point &point) const
bool parallel_to (double angle) const
bool parallel_to (const Line &line) const
bool perpendicular_to (double angle) const
bool perpendicular_to (const Line &line) const
double atan2_ () const
double orientation () const
double direction () const
Vector vector () const
Vector normal () const
bool intersection (const Line &line, Point *intersection) const
bool clip_with_bbox (const BoundingBox &bbox)
void extend (double offset)
Static Public Member Functions
static double distance_to_squared (const Point &point, const Point &a, const Point &b)
static double distance_to (const Point &point, const Point &a, const Point &b)
static double distance_to_infinite_squared (const Point &point, const Point &a, const Point &b)
static double distance_to_infinite (const Point &point, const Point &a, const Point &b)
Public Attributes
double a_width
double b_width
Point a
Point b
Static Public Attributes
static const constexpr int Dim = 2
Detailed Description
Member Typedef Documentation
Scalar
using Slic3r::Line::Scalar = Point::Scalar inherited
Constructor & Destructor Documentation
ThickLine() [1/3]
Slic3r::ThickLine::ThickLine () inline
: a_width(0), b_width(0) {}
ThickLine() [2/3]
Slic3r::ThickLine::ThickLine (const Point & a, const Point & b) inline
: Line(a, b), a_width(0), b_width(0) {}
ThickLine() [3/3]
Slic3r::ThickLine::ThickLine (const Point & a, const Point & b, double wa, double wb) inline
: Line(a, b), a_width(wa), b_width(wb) {}
Member Function Documentation
atan2_()
double Slic3r::Line::atan2_ () const inline inherited
{ return atan2(this->b(1) - this->a(1), this->b(0) - this->a(0)); }
References Slic3r::Line::a, Slic3r::Line::b, and Slic3r::Line::vector().
Referenced by Slic3r::Line::direction(), and Slic3r::Line::orientation().
clip_with_bbox()
bool Slic3r::Line::clip_with_bbox (const BoundingBox & bbox) inherited
{
  Vec2d x0clip, x1clip;
  bool result = Geometry::liang_barsky_line_clipping<double>(this->a.cast<double>(), this->b.cast<double>(), BoundingBoxf(bbox.min.cast<double>(), bbox.max.cast<double>()), x0clip, x1clip);
  if (result) {
    this->a = x0clip.cast<coord_t>();
    this->b = x1clip.cast<coord_t>();
  }
  return result;
}
References Slic3r::Line::a, Slic3r::Line::b, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, and Slic3r::Line::vector().
direction()
double Slic3r::Line::direction () const inherited
{
    double atan2 = this->atan2_();
    return (fabs(atan2 - PI) < EPSILON) ? 0
        : (atan2 < 0) ? (atan2 + PI)
        : atan2;
}
References Slic3r::Line::atan2_(), EPSILON, PI, and Slic3r::Line::vector().
Referenced by Slic3r::BridgeDetector::bridge_direction_candidates(), Slic3r::Polyline::is_straight(), Slic3r::Line::parallel_to(), and Slic3r::Line::perpendicular_to().
distance_to() [1/2]
double Slic3r::Line::distance_to (const Point & point) const inline inherited
{ return distance_to(point, this->a, this->b); }
References Slic3r::Line::a, Slic3r::Line::b, and Slic3r::Line::distance_to().
Referenced by Slic3r::Line::distance_to(), Slic3r::remove_collinear(), and Slic3r::Geometry::MedialAxis::validate_edge().
distance_to() [2/2]
static double Slic3r::Line::distance_to (const Point & point, const Point & a, const Point & b) inline static inherited
{ return sqrt(distance_to_squared(point, a, b)); }
References Slic3r::Line::a, Slic3r::Line::b, Slic3r::Line::distance_to_squared(), and sqrt().
distance_to_infinite()
static double Slic3r::Line::distance_to_infinite (const Point & point, const Point & a, const Point & b) inline static inherited
{ return sqrt(distance_to_infinite_squared(point, a, b)); }
References Slic3r::Line::a, Slic3r::Line::b, Slic3r::Line::distance_to_infinite_squared(), and sqrt().
Referenced by Slic3r::Arachne::ExtrusionLine::simplify(), and Slic3r::Arachne::simplify().
distance_to_infinite_squared() [1/2]
static double Slic3r::Line::distance_to_infinite_squared (const Point & point, const Point & a, const Point & b) inline static inherited
{ return line_alg::distance_to_infinite_squared(Line{a, b}, Vec<2, coord_t>{point}); }
References Slic3r::Line::a, Slic3r::Line::b, and Slic3r::line_alg::distance_to_infinite_squared().
distance_to_infinite_squared() [2/2]
double Slic3r::Line::distance_to_infinite_squared (const Point & point, Point * closest_point) const inline inherited
{ return line_alg::distance_to_infinite_squared(*this, point, closest_point); }
References Slic3r::line_alg::distance_to_infinite_squared().
Referenced by Slic3r::Arachne::VoronoiUtils::discretizeParabola(), Slic3r::Line::distance_to_infinite(), Slic3r::Arachne::SkeletalTrapezoidationGraph::makeRib(), Slic3r::Arachne::ExtrusionLine::simplify(), and Slic3r::Arachne::simplify().
distance_to_squared() [1/3]
double Slic3r::Line::distance_to_squared (const Point & point) const inline inherited
{ return distance_to_squared(point, this->a, this->b); }
References Slic3r::Line::a, Slic3r::Line::b, and Slic3r::Line::distance_to_squared().
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::Line::distance_to(), Slic3r::Line::distance_to_squared(), Slic3r::Arachne::SkeletalTrapezoidationGraph::insertRib(), Slic3r::PaintedLineVisitor::operator()(), and Slic3r::FillLightning::Node::straighten().
distance_to_squared() [2/3]
static double Slic3r::Line::distance_to_squared (const Point & point, const Point & a, const Point & b) inline static inherited
{ return line_alg::distance_to_squared(Line{a, b}, Vec<2, coord_t>{point}); }
References Slic3r::Line::a, Slic3r::Line::b, and Slic3r::line_alg::distance_to_squared().
distance_to_squared() [3/3]
double Slic3r::Line::distance_to_squared (const Point & point, Point * closest_point) const inline inherited
{ return line_alg::distance_to_squared(*this, point, closest_point); }
References Slic3r::line_alg::distance_to_squared().
extend()
void Slic3r::Line::extend (double offset) inherited
{
    Vector offset_vector = (offset * this->vector().cast<double>().normalized()).cast<coord_t>();
    this->a -= offset_vector;
    this->b += offset_vector;
}
References Slic3r::Line::a, Slic3r::Line::b, Slic3r::offset(), and Slic3r::Line::vector().
Referenced by Slic3r::FillAdaptive::create_offset_line(), and Slic3r::line_intersection_with_epsilon().
intersection()
bool Slic3r::Line::intersection (const Line & line, Point * intersection) const inherited
{
    return line_alg::intersection(*this, l2, intersection);
}
References Slic3r::line_alg::intersection(), Slic3r::Line::intersection(), and Slic3r::l2().
Referenced by priv::compute_intersections(), Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::Polygon::first_intersection(), Slic3r::Line::intersection(), Slic3r::Polygon::intersection(), Slic3r::Polygon::intersections(), Slic3r::ConflictChecker::line_intersect(), Slic3r::line_intersection_with_epsilon(), and Slic3r::AllIntersectionsVisitor::operator()().
intersection_infinite()
bool Slic3r::Line::intersection_infinite (const Line & other, Point * point) const inherited
{
    Vec2d a1 = this->a.cast<double>();
    Vec2d v12 = (other.a - this->a).cast<double>();
    Vec2d v1 = (this->b - this->a).cast<double>();
    Vec2d v2 = (other.b - other.a).cast<double>();
    double denom = cross2(v1, v2);
    if (std::fabs(denom) < EPSILON)
        return false;
    double t1 = cross2(v12, v2) / denom;
    Vec2d result = (a1 + t1 * v1);
    if (result.x() > std::numeric_limits<coord_t>::max() || result.x() < std::numeric_limits<coord_t>::lowest() ||
        result.y() > std::numeric_limits<coord_t>::max() || result.y() < std::numeric_limits<coord_t>::lowest()) {
        // Intersection has at least one of the coordinates much bigger (or smaller) than coord_t maximum value (or minimum).
        // So it can not be stored into the Point without integer overflows. That could mean that input lines are parallel or near parallel.
        return false;
    }
    *point = (result).cast<coord_t>();
    return true;
}
References Slic3r::Line::a, Slic3r::Line::b, Slic3r::cross2(), EPSILON, and Slic3r::Line::vector().
Referenced by Slic3r::Arachne::ExtrusionLine::simplify(), and Slic3r::Arachne::simplify().
length()
double Slic3r::Line::length () const inline inherited
{ return (b - a).cast<double>().norm(); }
References Slic3r::Line::a, and Slic3r::Line::b.
Referenced by Slic3r::sla::ConcaveHull::add_connector_rectangles(), Slic3r::BridgeDetector::detect_angle(), Slic3r::filter_colorized_polygon(), Slic3r::filter_painted_lines(), Slic3r::make_fill_polylines(), Slic3r::PaintedLineVisitor::operator()(), Slic3r::thick_lines_to_geometry(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), and Slic3r::AvoidCrossingPerimeters::travel_to().
midpoint()
Point Slic3r::Line::midpoint () const inline inherited
{ return (this->a + this->b) / 2; }
References Slic3r::Line::a, and Slic3r::Line::b.
normal()
Vector Slic3r::Line::normal () const inline inherited
{ return Vector((this->b(1) - this->a(1)), -(this->b(0) - this->a(0))); }
References Slic3r::Line::a, and Slic3r::Line::b.
Referenced by Slic3r::avoid_perimeters_inner(), and Slic3r::thick_lines_to_geometry().
operator Lines()
Slic3r::Line::operator Lines () const inline explicit inherited
{ Lines lines; lines.emplace_back(*this); return lines; }
operator==()
bool Slic3r::Line::operator== (const Line & rhs) const inline inherited
{ return this->a == rhs.a && this->b == rhs.b; }
References Slic3r::Line::a, and Slic3r::Line::b.
orientation()
double Slic3r::Line::orientation () const inherited
{
    double angle = this->atan2_();
    if (angle < 0) angle = 2*PI + angle;
    return angle;
}
References Slic3r::angle(), Slic3r::Line::atan2_(), and PI.
Referenced by Slic3r::Geometry::MedialAxis::validate_edge().
parallel_to() [1/2]
bool Slic3r::Line::parallel_to (const Line & line) const inherited
{
    const Vec2d v1 = (this->b - this->a).cast<double>();
    const Vec2d v2 = (line.b - line.a).cast<double>();
    return sqr(cross2(v1, v2)) < sqr(EPSILON) * v1.squaredNorm() * v2.squaredNorm();
}
References Slic3r::Line::a, Slic3r::Line::b, Slic3r::cross2(), EPSILON, Slic3r::sqr(), and Slic3r::Line::vector().
parallel_to() [2/2]
bool Slic3r::Line::parallel_to (double angle) const inherited
{
    return Slic3r::Geometry::directions_parallel(this->direction(), angle);
}
References Slic3r::Line::direction(), and Slic3r::Geometry::directions_parallel().
perp_distance_to()
double Slic3r::Line::perp_distance_to (const Point & point) const inherited
{
    const Line  &line = *this;
    const Vec2d  v  = (line.b - line.a).cast<double>();
    const Vec2d  va = (point - line.a).cast<double>();
    if (line.a == line.b)
        return va.norm();
    return std::abs(cross2(v, va)) / v.norm();
}
References Slic3r::Line::a, Slic3r::Line::b, Slic3r::cross2(), and Slic3r::Line::vector().
perpendicular_to() [1/2]
bool Slic3r::Line::perpendicular_to (const Line & line) const inherited
{
    const Vec2d v1 = (this->b - this->a).cast<double>();
    const Vec2d v2 = (line.b - line.a).cast<double>();
    return sqr(v1.dot(v2)) < sqr(EPSILON) * v1.squaredNorm() * v2.squaredNorm();
}
References Slic3r::Line::a, Slic3r::Line::b, EPSILON, Slic3r::sqr(), and Slic3r::Line::vector().
perpendicular_to() [2/2]
bool Slic3r::Line::perpendicular_to (double angle) const inherited
{
    return Slic3r::Geometry::directions_perpendicular(this->direction(), angle);
}
References Slic3r::Line::direction(), and Slic3r::Geometry::directions_perpendicular().
reverse()
void Slic3r::Line::reverse () inline inherited
{ std::swap(this->a, this->b); }
References Slic3r::Line::a, and Slic3r::Line::b.
Referenced by Slic3r::PaintedLineVisitor::operator()().
rotate()
void Slic3r::Line::rotate (double angle, const Point & center) inline inherited
{ this->a.rotate(angle, center); this->b.rotate(angle, center); }
References Slic3r::Line::a, Slic3r::Line::b, and Slic3r::Point::rotate().
scale()
void Slic3r::Line::scale (double factor) inline inherited
{ this->a *= factor; this->b *= factor; }
References Slic3r::Line::a, and Slic3r::Line::b.
translate() [1/2]
void Slic3r::Line::translate (const Point & v) inline inherited
{ this->a += v; this->b += v; }
References Slic3r::Line::a, and Slic3r::Line::b.
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks(), and Slic3r::FillAdaptive::create_offset_line().
translate() [2/2]
void Slic3r::Line::translate (double x, double y) inline inherited
{ this->translate(Point(x, y)); }
References Slic3r::Line::translate().
Referenced by Slic3r::Line::translate().
vector()
Vector Slic3r::Line::vector () const inline inherited
{ return this->b - this->a; }
References Slic3r::Line::a, and Slic3r::Line::b.
Referenced by Slic3r::Line::atan2_(), Slic3r::Line::clip_with_bbox(), Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::contours_simplified(), Slic3r::EdgeGrid::Grid::contours_simplified(), Slic3r::Line::direction(), Slic3r::Line::extend(), Slic3r::Line::intersection_infinite(), Slic3r::PaintedLineVisitor::operator()(), Slic3r::Line::parallel_to(), Slic3r::Line::perp_distance_to(), Slic3r::Line::perpendicular_to(), Slic3r::IntersectionLine::set_no_seed(), and Slic3r::thick_lines_to_geometry().
Member Data Documentation
a
Point Slic3r::Line::a inherited
Referenced by Slic3r::JPSPathFinder::add_obstacles(), Slic3r::Voronoi::annotate_inside_outside(), Slic3r::any_expolygon_contains(), Slic3r::Line::atan2_(), Slic3r::chain_lines(), Slic3r::chain_lines_by_triangle_connectivity(), Slic3r::Line::clip_with_bbox(), Slic3r::colorize_line(), priv::compute_intersections(), Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::ExPolygon::contains(), Slic3r::Voronoi::contour_point(), Slic3r::Voronoi::contour_point(), Slic3r::cut_mesh(), Slic3r::BridgeDetector::detect_angle(), Slic3r::Voronoi::detail::dist_to_site(), Slic3r::Line::distance_to(), Slic3r::Line::distance_to(), Slic3r::Line::distance_to_infinite(), Slic3r::Line::distance_to_infinite_squared(), Slic3r::Line::distance_to_squared(), Slic3r::Line::distance_to_squared(), Slic3r::SVG::draw(), Slic3r::SVG::draw(), Slic3r::Voronoi::edge_offset_contour_intersections(), Slic3r::ExtrusionQualityEstimator::estimate_speed_from_extrusion_quality(), Slic3r::Line::extend(), Slic3r::filter_painted_lines(), Slic3r::Polygon::first_intersection(), Slic3r::Geometry::foot_pt(), Slic3r::FillAdaptive::generate_infill_lines_recursive(), boost::polygon::segment_traits< Slic3r::ColoredLine >::get(), boost::polygon::segment_traits< Slic3r::Line >::get(), Slic3r::FillAdaptive::Intersection::intersect_line_dir(), Slic3r::Line::intersection_infinite(), Slic3r::Polygon::intersections(), Slic3r::is_point_closer_to_beginning_of_line(), Slic3r::Line::length(), Slic3r::ConflictChecker::line_intersect(), Slic3r::Voronoi::detail::line_point_equal_distance_points(), Slic3r::RasterizationImpl::line_rasterization(), Slic3r::make_fill_polylines(), Slic3r::Line::midpoint(), Slic3r::FillAdaptive::mk_rtree_seg(), Slic3r::need_wipe(), Slic3r::Line::normal(), Slic3r::Voronoi::offset(), Slic3r::Voronoi::detail::on_site(), Slic3r::PaintedLineVisitor::operator()(), Slic3r::Line::operator==(), Slic3r::Geometry::orientation_of_two_edges(), Slic3r::Line::parallel_to(), Slic3r::Line::perp_distance_to(), Slic3r::Line::perpendicular_to(), Slic3r::Voronoi::detail::point_segment_dr_dl_thresholds(), Slic3r::Voronoi::detail::point_segment_skeleton_thresholds(), Slic3r::points_inside(), Slic3r::FillLightning::polygonCollidesWithLineSegment(), Slic3r::post_process_painted_lines(), Slic3r::project_line_on_line(), Slic3r::Line::reverse(), Slic3r::IntersectionLine::reverse(), Slic3r::Line::rotate(), Slic3r::Line::scale(), Slic3r::Voronoi::signed_vertex_distances(), Slic3r::Voronoi::skeleton_edges_rough(), Slic3r::slice_facet(), Slic3r::slice_facet_with_slabs(), Slic3r::thick_lines_to_geometry(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), Slic3r::Line::translate(), Slic3r::Geometry::MedialAxis::validate_edge(), Slic3r::Line::vector(), and Slic3r::Voronoi::debug::verify_twin_halfedges_successive().
a_width
double Slic3r::ThickLine::a_width
Referenced by Slic3r::SVG::draw(), and Slic3r::PerimeterGenerator::thick_polyline_to_multi_path().
b
Point Slic3r::Line::b inherited
Referenced by Slic3r::FillAdaptive::Intersection::Intersection(), Slic3r::Voronoi::annotate_inside_outside(), Slic3r::any_expolygon_contains(), Slic3r::Line::atan2_(), Slic3r::chain_lines(), Slic3r::chain_lines_by_triangle_connectivity(), Slic3r::Line::clip_with_bbox(), priv::compute_intersections(), Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::ExPolygon::contains(), Slic3r::Voronoi::contour_point(), Slic3r::Voronoi::contour_point(), Slic3r::cut_mesh(), Slic3r::BridgeDetector::detect_angle(), Slic3r::Voronoi::detail::dist_to_site(), Slic3r::Line::distance_to(), Slic3r::Line::distance_to(), Slic3r::Line::distance_to_infinite(), Slic3r::Line::distance_to_infinite_squared(), Slic3r::Line::distance_to_squared(), Slic3r::Line::distance_to_squared(), Slic3r::SVG::draw(), Slic3r::SVG::draw(), Slic3r::Voronoi::edge_offset_contour_intersections(), Slic3r::ExtrusionQualityEstimator::estimate_speed_from_extrusion_quality(), Slic3r::Line::extend(), Slic3r::filter_painted_lines(), Slic3r::Polygon::first_intersection(), Slic3r::Geometry::foot_pt(), Slic3r::FillAdaptive::generate_infill_lines_recursive(), boost::polygon::segment_traits< Slic3r::ColoredLine >::get(), boost::polygon::segment_traits< Slic3r::Line >::get(), Slic3r::FillAdaptive::Intersection::intersect_line_dir(), Slic3r::Line::intersection_infinite(), Slic3r::Polygon::intersections(), Slic3r::is_point_closer_to_beginning_of_line(), Slic3r::Line::length(), Slic3r::ConflictChecker::line_intersect(), Slic3r::Voronoi::detail::line_point_equal_distance_points(), Slic3r::RasterizationImpl::line_rasterization(), Slic3r::make_fill_polylines(), Slic3r::Line::midpoint(), Slic3r::FillAdaptive::mk_rtree_seg(), Slic3r::need_wipe(), Slic3r::Line::normal(), Slic3r::Voronoi::offset(), Slic3r::Voronoi::detail::on_site(), Slic3r::PaintedLineVisitor::operator()(), Slic3r::Line::operator==(), Slic3r::Geometry::orientation_of_two_edges(), Slic3r::Line::parallel_to(), Slic3r::Line::perp_distance_to(), Slic3r::Line::perpendicular_to(), Slic3r::Voronoi::detail::point_segment_dr_dl_thresholds(), Slic3r::Voronoi::detail::point_segment_skeleton_thresholds(), Slic3r::points_inside(), Slic3r::FillLightning::polygonCollidesWithLineSegment(), Slic3r::post_process_painted_lines(), Slic3r::project_line_on_line(), Slic3r::Line::reverse(), Slic3r::IntersectionLine::reverse(), Slic3r::Line::rotate(), Slic3r::Line::scale(), Slic3r::Voronoi::signed_vertex_distances(), Slic3r::Voronoi::skeleton_edges_rough(), Slic3r::slice_facet(), Slic3r::slice_facet_with_slabs(), Slic3r::thick_lines_to_geometry(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), Slic3r::Line::translate(), Slic3r::Geometry::MedialAxis::validate_edge(), Slic3r::Line::vector(), and Slic3r::Voronoi::debug::verify_twin_halfedges_successive().
b_width
double Slic3r::ThickLine::b_width
Referenced by Slic3r::SVG::draw(), and Slic3r::PerimeterGenerator::thick_polyline_to_multi_path().
Dim
const constexpr int Slic3r::Line::Dim = 2 static constexpr inherited
The documentation for this class was generated from the following file:
src/libslic3r/Line.hpp