Prusa Slicer: Slic3r::FFFTreeSupport::InterfacePlacer Class Reference
Slic3r::FFFTreeSupport::InterfacePlacer Class Reference
#include <src/libslic3r/Support/TreeSupportCommon.hpp>
Public Member Functions
InterfacePlacer (const SlicingParameters &slicing_parameters, const SupportParameters &support_parameters, const TreeSupportSettings &config, SupportGeneratorLayerStorage &layer_storage, SupportGeneratorLayersPtr &top_contacts, SupportGeneratorLayersPtr &top_interfaces, SupportGeneratorLayersPtr &top_base_interfaces)
InterfacePlacer (const InterfacePlacer &rhs)
SupportGeneratorLayersPtr & top_contacts_mutable ()
void add_roofs (std::vector< Polygons > &&new_roofs, const size_t insert_layer_idx)
void add_roof (Polygons &&new_roof, const size_t insert_layer_idx, const size_t dtt_tip)
void add_roof_build_plate (Polygons &&overhang_areas, size_t dtt_roof)
void add_roof_unguarded (Polygons &&new_roofs, const size_t insert_layer_idx, const size_t dtt_roof)
Public Attributes
const SlicingParameters & slicing_parameters
const SupportParameters & support_parameters
const TreeSupportSettings & config
Private Attributes
SupportGeneratorLayerStorage & layer_storage
SupportGeneratorLayersPtr & top_contacts
SupportGeneratorLayersPtr & top_interfaces
SupportGeneratorLayersPtr & top_base_interfaces
std::mutex m_mutex_layer_storage
Detailed Description
Constructor & Destructor Documentation
InterfacePlacer() [1/2]
Slic3r::FFFTreeSupport::InterfacePlacer::InterfacePlacer (const SlicingParameters & slicing_parameters, const SupportParameters & support_parameters, const TreeSupportSettings & config, SupportGeneratorLayerStorage & layer_storage, SupportGeneratorLayersPtr & top_contacts, SupportGeneratorLayersPtr & top_interfaces, SupportGeneratorLayersPtr & top_base_interfaces) inline
    :
        slicing_parameters(slicing_parameters), support_parameters(support_parameters), config(config),
        layer_storage(layer_storage), top_contacts(top_contacts), top_interfaces(top_interfaces), top_base_interfaces(top_base_interfaces)
    {}
InterfacePlacer() [2/2]
Slic3r::FFFTreeSupport::InterfacePlacer::InterfacePlacer (const InterfacePlacer & rhs) inline
                                                :
        slicing_parameters(rhs.slicing_parameters), support_parameters(rhs.support_parameters), config(rhs.config),
        layer_storage(rhs.layer_storage), top_contacts(rhs.top_contacts), top_interfaces(rhs.top_interfaces), top_base_interfaces(rhs.top_base_interfaces)
    {}
Member Function Documentation
add_roof()
void Slic3r::FFFTreeSupport::InterfacePlacer::add_roof (Polygons && new_roof, const size_t insert_layer_idx, const size_t dtt_tip) inline
    {
        std::lock_guard<std::mutex> lock(m_mutex_layer_storage);
        add_roof_unguarded(std::move(new_roof), insert_layer_idx, dtt_tip);
    }
References add_roof_unguarded(), and m_mutex_layer_storage.
Referenced by Slic3r::FFFTreeSupport::RichInterfacePlacer::add_points_along_lines().
add_roof_build_plate()
void Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_build_plate (Polygons && overhang_areas, size_t dtt_roof) inline
    {
        std::lock_guard<std::mutex> lock(m_mutex_layer_storage);
        this->add_roof_unguarded(std::move(overhang_areas), 0, std::min(dtt_roof, this->support_parameters.num_top_interface_layers));
    }
References add_roof_unguarded(), m_mutex_layer_storage, and Slic3r::FFFSupport::SupportParameters::num_top_interface_layers.
Referenced by Slic3r::FFFTreeSupport::sample_overhang_area().
add_roof_unguarded()
void Slic3r::FFFTreeSupport::InterfacePlacer::add_roof_unguarded (Polygons && new_roofs, const size_t insert_layer_idx, const size_t dtt_roof) inline
    {
        assert(support_parameters.has_top_contacts);
        assert(dtt_roof <= support_parameters.num_top_interface_layers);
        SupportGeneratorLayersPtr &layers =
            dtt_roof == 0 ? this->top_contacts :
            dtt_roof <= support_parameters.num_top_interface_layers_only() ? this->top_interfaces : this->top_base_interfaces;
        SupportGeneratorLayer*& l = layers[insert_layer_idx];
        if (l == nullptr)
            l = &layer_allocate_unguarded(layer_storage, dtt_roof == 0 ? SupporLayerType::TopContact : SupporLayerType::TopInterface,
                    slicing_parameters, config, insert_layer_idx);
        // will be unioned in finalize_interface_and_support_areas()
        append(l->polygons, std::move(new_roofs));
    }
References Slic3r::append(), config, Slic3r::FFFSupport::SupportParameters::has_top_contacts, Slic3r::FFFTreeSupport::layer_allocate_unguarded(), layer_storage, Slic3r::FFFSupport::SupportParameters::num_top_interface_layers, Slic3r::FFFSupport::SupportParameters::num_top_interface_layers_only(), Slic3r::FFFSupport::SupportGeneratorLayer::polygons, slicing_parameters, support_parameters, top_base_interfaces, top_contacts, and top_interfaces.
Referenced by add_roof(), add_roof_build_plate(), add_roofs(), and Slic3r::FFFTreeSupport::generate_raft_contact().
add_roofs()
void Slic3r::FFFTreeSupport::InterfacePlacer::add_roofs (std::vector< Polygons > && new_roofs, const size_t insert_layer_idx) inline
    {
        if (! new_roofs.empty()) {
            std::lock_guard<std::mutex> lock(m_mutex_layer_storage);
            for (size_t idx = 0; idx < new_roofs.size(); ++ idx)
                if (! new_roofs[idx].empty())
                    add_roof_unguarded(std::move(new_roofs[idx]), insert_layer_idx - idx, idx);
        }
    }
References add_roof_unguarded(), Slic3r::empty(), and m_mutex_layer_storage.
Referenced by Slic3r::FFFTreeSupport::sample_overhang_area().
top_contacts_mutable()
SupportGeneratorLayersPtr & Slic3r::FFFTreeSupport::InterfacePlacer::top_contacts_mutable () inline
{ return this->top_contacts; }
References top_contacts.
Member Data Documentation
config
const TreeSupportSettings& Slic3r::FFFTreeSupport::InterfacePlacer::config
Referenced by Slic3r::FFFTreeSupport::RichInterfacePlacer::add_point_as_influence_area(), Slic3r::FFFTreeSupport::RichInterfacePlacer::add_points_along_lines(), add_roof_unguarded(), and Slic3r::FFFTreeSupport::sample_overhang_area().
layer_storage
SupportGeneratorLayerStorage& Slic3r::FFFTreeSupport::InterfacePlacer::layer_storage private
Referenced by add_roof_unguarded().
m_mutex_layer_storage
std::mutex Slic3r::FFFTreeSupport::InterfacePlacer::m_mutex_layer_storage private
Referenced by add_roof(), add_roof_build_plate(), and add_roofs().
slicing_parameters
const SlicingParameters& Slic3r::FFFTreeSupport::InterfacePlacer::slicing_parameters
Referenced by add_roof_unguarded(), and Slic3r::FFFTreeSupport::generate_support_areas().
support_parameters
const SupportParameters& Slic3r::FFFTreeSupport::InterfacePlacer::support_parameters
Referenced by add_roof_unguarded(), Slic3r::FFFTreeSupport::generate_initial_areas(), and Slic3r::FFFTreeSupport::sample_overhang_area().
top_base_interfaces
SupportGeneratorLayersPtr& Slic3r::FFFTreeSupport::InterfacePlacer::top_base_interfaces private
Referenced by add_roof_unguarded().
top_contacts
SupportGeneratorLayersPtr& Slic3r::FFFTreeSupport::InterfacePlacer::top_contacts private
Referenced by add_roof_unguarded(), and top_contacts_mutable().
top_interfaces
SupportGeneratorLayersPtr& Slic3r::FFFTreeSupport::InterfacePlacer::top_interfaces private
Referenced by add_roof_unguarded().
The documentation for this class was generated from the following file:
src/libslic3r/Support/TreeSupportCommon.hpp