Prusa Slicer: Slic3r::TriangleSelector::Cursor Class Reference
Slic3r::TriangleSelector::Cursor Class Reference abstract
#include <src/libslic3r/TriangleSelector.hpp>
Public Member Functions
Cursor ()=delete
virtual ~Cursor ()=default
bool is_pointer_in_triangle (const Triangle &tr, const std::vector< Vertex > &vertices) const
virtual bool is_mesh_point_inside (const Vec3f &point) const =0
virtual bool is_pointer_in_triangle (const Vec3f &p1, const Vec3f &p2, const Vec3f &p3) const =0
virtual int vertices_inside (const Triangle &tr, const std::vector< Vertex > &vertices) const
virtual bool is_edge_inside_cursor (const Triangle &tr, const std::vector< Vertex > &vertices) const =0
virtual bool is_facet_visible (int facet_idx, const std::vector< Vec3f > &face_normals) const =0
Static Public Member Functions
static bool is_facet_visible (const Cursor &cursor, int facet_idx, const std::vector< Vec3f > &face_normals)
Protected Member Functions
Cursor (const Vec3f &source_, float radius_world, const Transform3d &trafo_, const ClippingPlane &clipping_plane_)
Protected Attributes
Transform3f trafo
Vec3f source
bool uniform_scaling
Transform3f trafo_normal
float radius
float radius_sqr
Vec3f dir = Vec3f(0.f, 0.f, 0.f)
ClippingPlane clipping_plane
friend TriangleSelector
Detailed Description
Constructor & Destructor Documentation
Cursor() [1/2]
Slic3r::TriangleSelector::Cursor::Cursor () delete
~Cursor()
virtual Slic3r::TriangleSelector::Cursor::~Cursor () virtual default
Cursor() [2/2]
Slic3r::TriangleSelector::Cursor::Cursor (const Vec3f & source_, float radius_world, const Transform3d & trafo_, const ClippingPlane & clipping_plane_) explicit protected
    : source{source_}, trafo{trafo_.cast<float>()}, clipping_plane{clipping_plane_}
{
    Vec3d sf = Geometry::Transformation(trafo_).get_scaling_factor();
    if (is_approx(sf(0), sf(1)) && is_approx(sf(1), sf(2))) {
        radius          = float(radius_world / sf(0));
        radius_sqr      = float(Slic3r::sqr(radius_world / sf(0)));
        uniform_scaling = true;
    } else {
        // In case that the transformation is non-uniform, all checks whether
        // something is inside the cursor should be done in world coords.
        // First transform source in world coords and remember that we did this.
        source          = trafo * source;
        uniform_scaling = false;
        radius          = radius_world;
        radius_sqr      = Slic3r::sqr(radius_world);
        trafo_normal    = trafo.linear().inverse().transpose();
    }
}
References Slic3r::Geometry::Transformation::get_scaling_factor(), Slic3r::is_approx(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), radius, radius_sqr, source, Slic3r::sqr(), trafo, trafo_normal, and uniform_scaling.
Member Function Documentation
is_edge_inside_cursor()
virtual bool Slic3r::TriangleSelector::Cursor::is_edge_inside_cursor (const Triangle & tr, const std::vector< Vertex > & vertices) const pure virtual
Implemented in Slic3r::TriangleSelector::Sphere, Slic3r::TriangleSelector::Circle, Slic3r::TriangleSelector::Capsule3D, and Slic3r::TriangleSelector::Capsule2D.
is_facet_visible() [1/2]
bool Slic3r::TriangleSelector::Cursor::is_facet_visible (const Cursor & cursor, int facet_idx, const std::vector< Vec3f > & face_normals) static
{
    assert(facet_idx < int(face_normals.size()));
    Vec3f n = face_normals[facet_idx];
    if (!cursor.uniform_scaling)
        n = cursor.trafo_normal * n;
    return n.dot(cursor.dir) < 0.f;
}
References dir, trafo_normal, and uniform_scaling.
is_facet_visible() [2/2]
virtual bool Slic3r::TriangleSelector::Cursor::is_facet_visible (int facet_idx, const std::vector< Vec3f > & face_normals) const pure virtual
Implemented in Slic3r::TriangleSelector::Sphere, Slic3r::TriangleSelector::Circle, Slic3r::TriangleSelector::Capsule3D, and Slic3r::TriangleSelector::Capsule2D.
Referenced by Slic3r::TriangleSelector::Circle::is_facet_visible(), and Slic3r::TriangleSelector::Capsule2D::is_facet_visible().
is_mesh_point_inside()
virtual bool Slic3r::TriangleSelector::Cursor::is_mesh_point_inside (const Vec3f & point) const pure virtual
Implemented in Slic3r::TriangleSelector::Sphere, Slic3r::TriangleSelector::Circle, Slic3r::TriangleSelector::Capsule3D, and Slic3r::TriangleSelector::Capsule2D.
is_pointer_in_triangle() [1/2]
bool Slic3r::TriangleSelector::Cursor::is_pointer_in_triangle (const Triangle & tr, const std::vector< Vertex > & vertices) const
{
    const Vec3f& p1 = vertices[tr.verts_idxs[0]].v;
    const Vec3f& p2 = vertices[tr.verts_idxs[1]].v;
    const Vec3f& p3 = vertices[tr.verts_idxs[2]].v;
    return this->is_pointer_in_triangle(p1, p2, p3);
}
References Slic3r::TriangleSelector::Triangle::verts_idxs.
is_pointer_in_triangle() [2/2]
virtual bool Slic3r::TriangleSelector::Cursor::is_pointer_in_triangle (const Vec3f & p1, const Vec3f & p2, const Vec3f & p3) const pure virtual
Implemented in Slic3r::TriangleSelector::SinglePointCursor, and Slic3r::TriangleSelector::DoublePointCursor.
vertices_inside()
int Slic3r::TriangleSelector::Cursor::vertices_inside (const Triangle & tr, const std::vector< Vertex > & vertices) const virtual
{
    int inside = 0;
    for (size_t i = 0; i < 3; ++i)
        if (this->is_mesh_point_inside(vertices[tr.verts_idxs[i]].v))
            ++inside;
    return inside;
}
References Slic3r::TriangleSelector::Triangle::verts_idxs.
Member Data Documentation
clipping_plane
ClippingPlane Slic3r::TriangleSelector::Cursor::clipping_plane protected
Referenced by Slic3r::TriangleSelector::SinglePointCursor::cursor_factory(), and Slic3r::TriangleSelector::DoublePointCursor::cursor_factory().
dir
Vec3f Slic3r::TriangleSelector::Cursor::dir = Vec3f(0.f, 0.f, 0.f) protected
Referenced by Slic3r::TriangleSelector::DoublePointCursor::DoublePointCursor(), Slic3r::TriangleSelector::SinglePointCursor::SinglePointCursor(), and is_facet_visible().
radius
float Slic3r::TriangleSelector::Cursor::radius protected
Referenced by Cursor().
radius_sqr
float Slic3r::TriangleSelector::Cursor::radius_sqr protected
Referenced by Cursor().
source
Vec3f Slic3r::TriangleSelector::Cursor::source protected
Referenced by Cursor(), Slic3r::TriangleSelector::DoublePointCursor::DoublePointCursor(), and Slic3r::TriangleSelector::SinglePointCursor::SinglePointCursor().
trafo
Transform3f Slic3r::TriangleSelector::Cursor::trafo protected
Referenced by Cursor(), Slic3r::TriangleSelector::DoublePointCursor::DoublePointCursor(), and Slic3r::TriangleSelector::SinglePointCursor::SinglePointCursor().
trafo_normal
Transform3f Slic3r::TriangleSelector::Cursor::trafo_normal protected
Referenced by Cursor(), and is_facet_visible().
TriangleSelector
friend Slic3r::TriangleSelector::Cursor::TriangleSelector protected
uniform_scaling
bool Slic3r::TriangleSelector::Cursor::uniform_scaling protected
Referenced by Cursor(), Slic3r::TriangleSelector::DoublePointCursor::DoublePointCursor(), Slic3r::TriangleSelector::SinglePointCursor::SinglePointCursor(), and is_facet_visible().
The documentation for this class was generated from the following files:
src/libslic3r/TriangleSelector.hpp
src/libslic3r/TriangleSelector.cpp