Prusa Slicer: src/avrdude/avrftdi.c File Reference
avrftdi.c File Reference
#include "ac_cfg.h"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <errno.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdint.h>
#include <stdarg.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "avrftdi.h"
#include "avrftdi_tpi.h"
#include "avrftdi_private.h"
#include "usbdevs.h"
Macros
#define MAX(a, b) ((a)>(b)?(a):(b))
#define MIN(a, b) ((a)<(b)?(a):(b))
Functions
static int avrftdi_noftdi_open (struct programmer_t *pgm, char *name)
void avrftdi_initpgm (PROGRAMMER *pgm)
Variables
const char avrftdi_desc [] = "Interface to the MPSSE Engine of FTDI Chips using libftdi."
Macro Definition Documentation
MAX
#define MAX (a, b) ((a)>(b)?(a):(b))
MIN
#define MIN (a, b) ((a)<(b)?(a):(b))
Function Documentation
avrftdi_initpgm()
void avrftdi_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "avrftdi");
  pgm->open = avrftdi_noftdi_open;
}
References avrftdi_noftdi_open(), programmer_t::open, pgm, and programmer_t::type.
avrftdi_noftdi_open()
static int avrftdi_noftdi_open (struct programmer_t * pgm, char * name) static
{
  avrdude_message(MSG_INFO, "%s: Error: no libftdi or libusb support. Install libftdi1/libusb-1.0 or libftdi/libusb and run configure/make again.\n",
                        progname);
  return -1;
}
References avrdude_message(), MSG_INFO, and progname.
Referenced by avrftdi_initpgm().
Variable Documentation
avrftdi_desc
const char avrftdi_desc[] = "Interface to the MPSSE Engine of FTDI Chips using libftdi."