Prusa Slicer: Slic3r::anonymous_namespace{OctoPrint.cpp} Namespace Reference
Slic3r::anonymous_namespace{OctoPrint.cpp} Namespace Reference
Functions
std::string escape_string (const std::string &unescaped)
std::string escape_path_by_element (const boost::filesystem::path &path)
Function Documentation
escape_path_by_element()
std::string Slic3r::anonymous_namespace{OctoPrint.cpp}::escape_path_by_element (const boost::filesystem::path & path)
{
    std::string ret_val = escape_string(path.filename().string());
    boost::filesystem::path parent(path.parent_path());
    while (!parent.empty() && parent.string() != "/") // "/" check is for case "/file.gcode" was inserted. Then boost takes "/" as parent_path.
    {
        ret_val = escape_string(parent.filename().string()) + "/" + ret_val;
        parent = parent.parent_path();
    }
    return ret_val;
}
References escape_path_by_element(), and escape_string().
Referenced by escape_path_by_element().
escape_string()
std::string Slic3r::anonymous_namespace{OctoPrint.cpp}::escape_string (const std::string & unescaped)
{
    std::string ret_val;
    CURL* curl = curl_easy_init();
    if (curl) {
        char* decoded = curl_easy_escape(curl, unescaped.c_str(), unescaped.size());
        if (decoded) {
            ret_val = std::string(decoded);
            curl_free(decoded);
        }
        curl_easy_cleanup(curl);
    }
    return ret_val;
}
References escape_string().
Referenced by escape_path_by_element(), and escape_string().