Prusa Slicer: Slic3r::GUI::HighlighterForWx Class Reference
Slic3r::GUI::HighlighterForWx Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
HighlighterForWx ()
~HighlighterForWx ()
void bind_timer (wxWindow *owner) override
void init (BlinkingBitmap *blinking_bitmap)
void init (std::pair< OG_CustomCtrl *, bool * >)
void blink ()
void invalidate ()
void set_timer_owner (wxWindow *owner, int timerid=wxID_ANY)
bool init (bool input_failed)
Private Attributes
BlinkingBitmap * m_blinking_bitmap { nullptr }
OG_CustomCtrl * m_custom_ctrl { nullptr }
bool * m_show_blink_ptr { nullptr }
int m_blink_counter { 0 }
wxTimer m_timer
Detailed Description
Constructor & Destructor Documentation
HighlighterForWx()
Slic3r::GUI::HighlighterForWx::HighlighterForWx () inline
{}
~HighlighterForWx()
Slic3r::GUI::HighlighterForWx::~HighlighterForWx () inline
{}
Member Function Documentation
bind_timer()
void Slic3r::GUI::HighlighterForWx::bind_timer (wxWindow * owner) override virtual
Implements Slic3r::GUI::Highlighter.
{
    owner->Bind(wxEVT_TIMER, [this](wxTimerEvent&) {
        blink();
    });
}
References blink().
blink()
void Slic3r::GUI::HighlighterForWx::blink ()
{
    if (m_custom_ctrl && m_show_blink_ptr) {
        *m_show_blink_ptr = !*m_show_blink_ptr;
        m_custom_ctrl->Refresh();
    }
    else if (m_blinking_bitmap)
        m_blinking_bitmap->blink();
    else
        return;
    Highlighter::blink();
}
References BlinkingBitmap::blink(), Slic3r::GUI::Highlighter::blink(), m_blinking_bitmap, m_custom_ctrl, and m_show_blink_ptr.
Referenced by bind_timer().
init() [1/3]
void Slic3r::GUI::HighlighterForWx::init (BlinkingBitmap * blinking_bitmap)
{
    invalidate();
    if (!Highlighter::init(!blinking_bmp))
        return;
    m_blinking_bitmap = blinking_bmp;
    m_blinking_bitmap->activate();
}
References BlinkingBitmap::activate(), Slic3r::GUI::Highlighter::init(), invalidate(), and m_blinking_bitmap.
init() [2/3]
bool Slic3r::GUI::Highlighter::init (bool input_failed) inherited
{
    if (input_failed)
        return false;
    m_timer.Start(300, false);
    return true;
}
References Slic3r::GUI::Highlighter::m_timer.
Referenced by init(), and init().
init() [3/3]
void Slic3r::GUI::HighlighterForWx::init (std::pair< OG_CustomCtrl *, bool * > params)
{
    invalidate();
    if (!Highlighter::init(!params.first && !params.second))
        return;
    m_custom_ctrl = params.first;
    m_show_blink_ptr = params.second;
    *m_show_blink_ptr = true;
    m_custom_ctrl->Refresh();
}
References Slic3r::GUI::Highlighter::init(), invalidate(), m_custom_ctrl, and m_show_blink_ptr.
invalidate()
void Slic3r::GUI::HighlighterForWx::invalidate ()
{
    Highlighter::invalidate();
    if (m_custom_ctrl && m_show_blink_ptr) {
        *m_show_blink_ptr = false;
        m_custom_ctrl->Refresh();
        m_show_blink_ptr = nullptr;
        m_custom_ctrl = nullptr;
    }
    else if (m_blinking_bitmap) {
        m_blinking_bitmap->invalidate();
        m_blinking_bitmap = nullptr;
    }
}
References BlinkingBitmap::invalidate(), Slic3r::GUI::Highlighter::invalidate(), m_blinking_bitmap, m_custom_ctrl, and m_show_blink_ptr.
Referenced by init(), and init().
set_timer_owner()
void Slic3r::GUI::Highlighter::set_timer_owner (wxWindow * owner, int timerid = wxID_ANY) inherited
{
    m_timer.SetOwner(owner, timerid);
    bind_timer(owner);
}
References Slic3r::GUI::Highlighter::bind_timer(), and Slic3r::GUI::Highlighter::m_timer.
Referenced by Slic3r::GUI::PreferencesDialog::PreferencesDialog(), and Slic3r::GUI::Tab::Tab().
Member Data Documentation
m_blink_counter
int Slic3r::GUI::Highlighter::m_blink_counter { 0 } private inherited
Referenced by Slic3r::GUI::Highlighter::blink(), and Slic3r::GUI::Highlighter::invalidate().
m_blinking_bitmap
BlinkingBitmap* Slic3r::GUI::HighlighterForWx::m_blinking_bitmap { nullptr } private
Referenced by blink(), init(), and invalidate().
m_custom_ctrl
OG_CustomCtrl* Slic3r::GUI::HighlighterForWx::m_custom_ctrl { nullptr } private
Referenced by blink(), init(), and invalidate().
m_show_blink_ptr
bool* Slic3r::GUI::HighlighterForWx::m_show_blink_ptr { nullptr } private
Referenced by blink(), init(), and invalidate().
m_timer
wxTimer Slic3r::GUI::Highlighter::m_timer private inherited
Referenced by Slic3r::GUI::Highlighter::init(), Slic3r::GUI::Highlighter::invalidate(), and Slic3r::GUI::Highlighter::set_timer_owner().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp