Prusa Slicer: Slic3r::ProgressStatusBar Class Reference
Slic3r::ProgressStatusBar Class Reference
The ProgressStatusBar class is the widgets occupying the lower area of the Slicer main window. It consists of a message area to the left and a progress indication area to the right with an optional cancel button.
#include <src/slic3r/GUI/ProgressStatusBar.hpp>
Public Types
using CancelFn = std::function< void()>
Cancel callback function type.
Public Member Functions
ProgressStatusBar (wxWindow *parent=nullptr, int id=-1)
~ProgressStatusBar () override
int get_progress () const
void set_progress (int) override
int get_range () const override
void set_range (int=100) override
void show_progress (bool)
void start_busy (int=100)
void stop_busy ()
bool is_busy () const
void set_cancel_callback (CancelFn=CancelFn()) override
void reset_cancel_callback ()
void run (int rate)
void embed (wxFrame *frame=nullptr)
void set_status_text (const wxString &txt)
void set_status_text (const std::string &txt)
void set_status_text (const char *txt) override
wxString get_status_text () const
void set_font (const wxFont &font)
void show_cancel_button ()
void hide_cancel_button ()
void update_dark_ui ()
Private Attributes
wxStatusBar * self
wxGauge * m_prog
wxButton * m_cancelbutton
std::unique_ptr< wxTimer > m_timer
bool m_busy = false
CancelFn m_cancel_cb
Detailed Description
The ProgressStatusBar class is the widgets occupying the lower area of the Slicer main window. It consists of a message area to the left and a progress indication area to the right with an optional cancel button.
Member Typedef Documentation
CancelFn
using Slic3r::ProgressIndicator::CancelFn = std::function<void()> inherited
Cancel callback function type.
Constructor & Destructor Documentation
ProgressStatusBar()
Slic3r::ProgressStatusBar::ProgressStatusBar (wxWindow * parent = nullptr, int id = -1)
    : self{new wxStatusBar(parent, id == -1 ? wxID_ANY : id)}
    , m_prog{new wxGauge(self,
                         wxGA_HORIZONTAL,
                         100,
                         wxDefaultPosition,
                         wxDefaultSize)}
    , m_cancelbutton{new wxButton(self,
                                  -1,
                                  _(L("Cancel")),
                                  wxDefaultPosition,
                                  wxDefaultSize)}
    , m_timer{new wxTimer(self)}
{
    update_dark_ui();
    m_prog->Hide();
    m_cancelbutton->Hide();
    self->SetFieldsCount(3);
    int w[] = {-1, 150, 155};
    self->SetStatusWidths(3, w);
    wxSize s = m_cancelbutton->GetTextExtent(m_cancelbutton->GetLabel());
    self->SetMinHeight(int(2 * self->GetBorderY() + 1.2 * s.GetHeight()));
    self->Bind(wxEVT_TIMER, [this](const wxTimerEvent&) {
        if (m_prog->IsShown()) m_timer->Stop();
        if(is_busy()) m_prog->Pulse();
    });
    self->Bind(wxEVT_SIZE, [this](wxSizeEvent& event){
        wxRect rect;
        self->GetFieldRect(1, rect);
        auto offset = 0;
        m_cancelbutton->Move(rect.GetX() + offset, rect.GetY() + offset);
        m_cancelbutton->SetSize(rect.GetWidth() - offset, rect.GetHeight());
        self->GetFieldRect(2, rect);
        m_prog->Move(rect.GetX() + offset, rect.GetY() + offset);
        m_prog->SetSize(rect.GetWidth() - offset, rect.GetHeight());
        event.Skip();
    });
    m_cancelbutton->Bind(wxEVT_BUTTON, [this](const wxCommandEvent&) {
        if (m_cancel_cb)
            m_cancel_cb();
        m_cancelbutton->Hide();
    });
}
References is_busy(), m_cancel_cb, m_cancelbutton, m_prog, m_timer, Slic3r::offset(), self, update_dark_ui(), and wxEVT_BUTTON.
~ProgressStatusBar()
Slic3r::ProgressStatusBar::~ProgressStatusBar () override
{
    if(m_timer && m_timer->IsRunning()) m_timer->Stop();
}
References m_timer.
Member Function Documentation
embed()
void Slic3r::ProgressStatusBar::embed (wxFrame * frame = nullptr)
{
    if(frame) frame->SetStatusBar(self);
}
References self.
get_progress()
int Slic3r::ProgressStatusBar::get_progress () const
{
    return m_prog ? m_prog->GetValue() : 0;
}
References m_prog.
get_range()
int Slic3r::ProgressStatusBar::get_range () const override virtual
Implements Slic3r::ProgressIndicator.
{
    return m_prog ? m_prog->GetRange() : 0;
}
References m_prog.
get_status_text()
wxString Slic3r::ProgressStatusBar::get_status_text () const
{
    return self->GetStatusText();
}
References self.
hide_cancel_button()
void Slic3r::ProgressStatusBar::hide_cancel_button ()
{
    if(m_cancelbutton) m_cancelbutton->Hide();
}
References m_cancelbutton.
is_busy()
bool Slic3r::ProgressStatusBar::is_busy () const inline
{ return m_busy; }
References m_busy.
Referenced by ProgressStatusBar().
reset_cancel_callback()
void Slic3r::ProgressStatusBar::reset_cancel_callback () inline
{ set_cancel_callback(); }
References set_cancel_callback().
run()
void Slic3r::ProgressStatusBar::run (int rate)
{
    if(m_timer && !m_timer->IsRunning()) {
        m_timer->Start(rate);
    }
}
References m_timer.
set_cancel_callback()
void Slic3r::ProgressStatusBar::set_cancel_callback (ProgressStatusBar::CancelFn ccb = CancelFn()) override virtual
Implements Slic3r::ProgressIndicator.
{
    m_cancel_cb = ccb;
    if(m_cancelbutton) {
        if(ccb) m_cancelbutton->Show();
        else m_cancelbutton->Hide();
    }
}
References m_cancel_cb, and m_cancelbutton.
Referenced by reset_cancel_callback().
set_font()
void Slic3r::ProgressStatusBar::set_font (const wxFont & font)
{
    self->SetFont(font);
}
References self.
set_progress()
void Slic3r::ProgressStatusBar::set_progress (int val) override virtual
Implements Slic3r::ProgressIndicator.
{
    if(!m_prog) return;
    if(!m_prog->IsShown()) show_progress(true);
    if(val < 0) return;
    if(val == m_prog->GetRange()) {
        m_prog->SetValue(0);
        show_progress(false);
    }
    else {
        m_prog->SetValue(val);
    }
}
References m_prog, and show_progress().
set_range()
void Slic3r::ProgressStatusBar::set_range (int val = 100) override virtual
Implements Slic3r::ProgressIndicator.
{
    if(m_prog && val != m_prog->GetRange()) {
        m_prog->SetRange(val);
    }
}
References m_prog.
set_status_text() [1/3]
void Slic3r::ProgressStatusBar::set_status_text (const char * txt) override virtual
Implements Slic3r::ProgressIndicator.
{
    this->set_status_text(wxString::FromUTF8(txt));
}
References set_status_text().
set_status_text() [2/3]
void Slic3r::ProgressStatusBar::set_status_text (const std::string & txt)
{
    this->set_status_text(txt.c_str());
}
References set_status_text().
set_status_text() [3/3]
void Slic3r::ProgressStatusBar::set_status_text (const wxString & txt)
{
  if(self) self->SetStatusText(txt);
}
References self.
Referenced by set_status_text(), and set_status_text().
show_cancel_button()
void Slic3r::ProgressStatusBar::show_cancel_button ()
{
    if(m_cancelbutton) m_cancelbutton->Show();
}
References m_cancelbutton.
show_progress()
void Slic3r::ProgressStatusBar::show_progress (bool show)
{
    if(m_prog) {
        m_prog->Show(show);
        m_prog->Pulse();
    }
}
References m_prog.
Referenced by set_progress(), start_busy(), and stop_busy().
start_busy()
void Slic3r::ProgressStatusBar::start_busy (int rate = 100)
{
    if(!m_prog) return;
    m_busy = true;
    show_progress(true);
    if (!m_timer->IsRunning()) {
        m_timer->Start(rate);
    }
}
References m_busy, m_prog, m_timer, and show_progress().
stop_busy()
void Slic3r::ProgressStatusBar::stop_busy ()
{
    if(!m_timer || !m_prog) return;
    m_timer->Stop();
    show_progress(false);
    m_prog->SetValue(0);
    m_busy = false;
}
References m_busy, m_prog, m_timer, and show_progress().
update_dark_ui()
void Slic3r::ProgressStatusBar::update_dark_ui ()
{
    GUI::wxGetApp().UpdateDarkUI(self);
    GUI::wxGetApp().UpdateDarkUI(m_prog);
    GUI::wxGetApp().UpdateDarkUI(m_cancelbutton);
}
References m_cancelbutton, m_prog, and self.
Referenced by ProgressStatusBar().
Member Data Documentation
m_busy
bool Slic3r::ProgressStatusBar::m_busy = false private
Referenced by is_busy(), start_busy(), and stop_busy().
m_cancel_cb
CancelFn Slic3r::ProgressStatusBar::m_cancel_cb private
Referenced by ProgressStatusBar(), and set_cancel_callback().
m_cancelbutton
wxButton* Slic3r::ProgressStatusBar::m_cancelbutton private
Referenced by ProgressStatusBar(), hide_cancel_button(), set_cancel_callback(), show_cancel_button(), and update_dark_ui().
m_prog
wxGauge* Slic3r::ProgressStatusBar::m_prog private
Referenced by ProgressStatusBar(), get_progress(), get_range(), set_progress(), set_range(), show_progress(), start_busy(), stop_busy(), and update_dark_ui().
m_timer
std::unique_ptr<wxTimer> Slic3r::ProgressStatusBar::m_timer private
Referenced by ProgressStatusBar(), ~ProgressStatusBar(), run(), start_busy(), and stop_busy().
self
wxStatusBar* Slic3r::ProgressStatusBar::self private
Referenced by ProgressStatusBar(), embed(), get_status_text(), set_font(), set_status_text(), and update_dark_ui().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ProgressStatusBar.hpp
src/slic3r/GUI/ProgressStatusBar.cpp