Prusa Slicer: igl::geodesic::SimlpeMemoryAllocator< T > Class Template Reference
igl::geodesic::SimlpeMemoryAllocator< T > Class Template Reference
Public Types
typedef T * pointer
Public Member Functions
SimlpeMemoryAllocator (unsigned block_size=0, unsigned max_number_of_blocks=0)
~SimlpeMemoryAllocator ()
void reset (unsigned block_size, unsigned max_number_of_blocks)
pointer allocate (unsigned const n)
Private Attributes
std::vector< std::vector< T > > m_storage
unsigned m_block_size
unsigned m_max_number_of_blocks
unsigned m_current_position
Detailed Description
template<class T>
class igl::geodesic::SimlpeMemoryAllocator< T >
Member Typedef Documentation
pointer
template<class T > typedef T* igl::geodesic::SimlpeMemoryAllocator< T >::pointer
Constructor & Destructor Documentation
SimlpeMemoryAllocator()
template<class T > igl::geodesic::SimlpeMemoryAllocator< T >::SimlpeMemoryAllocator (unsigned block_size = 0, unsigned max_number_of_blocks = 0) inline
  {
    reset(block_size,
        max_number_of_blocks);
  };
References igl::geodesic::SimlpeMemoryAllocator< T >::reset().
~SimlpeMemoryAllocator()
template<class T > igl::geodesic::SimlpeMemoryAllocator< T >::~SimlpeMemoryAllocator () inline
{};
Member Function Documentation
allocate()
template<class T > pointer igl::geodesic::SimlpeMemoryAllocator< T >::allocate (unsigned const n) inline
  {
    assert(n < m_block_size);
    if(m_current_position + n >= m_block_size)
    {
      m_storage.push_back( std::vector<T>() );
      m_storage.back().resize(m_block_size);
      m_current_position = 0;
    }
    pointer result = & m_storage.back()[m_current_position];
    m_current_position += n;
    return result;
  };
References igl::geodesic::SimlpeMemoryAllocator< T >::m_block_size, igl::geodesic::SimlpeMemoryAllocator< T >::m_current_position, and igl::geodesic::SimlpeMemoryAllocator< T >::m_storage.
Referenced by igl::geodesic::Mesh::allocate_pointers().
reset()
template<class T > void igl::geodesic::SimlpeMemoryAllocator< T >::reset (unsigned block_size, unsigned max_number_of_blocks) inline
  {
    m_block_size = block_size;
    m_max_number_of_blocks = max_number_of_blocks;
    m_current_position = 0;
    m_storage.reserve(max_number_of_blocks);
    m_storage.resize(1);
    m_storage[0].resize(block_size);
  };
References igl::geodesic::SimlpeMemoryAllocator< T >::m_block_size, igl::geodesic::SimlpeMemoryAllocator< T >::m_current_position, igl::geodesic::SimlpeMemoryAllocator< T >::m_max_number_of_blocks, and igl::geodesic::SimlpeMemoryAllocator< T >::m_storage.
Referenced by igl::geodesic::SimlpeMemoryAllocator< T >::SimlpeMemoryAllocator(), and igl::geodesic::Mesh::initialize_mesh_data().
Member Data Documentation
m_block_size
template<class T > unsigned igl::geodesic::SimlpeMemoryAllocator< T >::m_block_size private
Referenced by igl::geodesic::SimlpeMemoryAllocator< T >::allocate(), and igl::geodesic::SimlpeMemoryAllocator< T >::reset().
m_current_position
template<class T > unsigned igl::geodesic::SimlpeMemoryAllocator< T >::m_current_position private
Referenced by igl::geodesic::SimlpeMemoryAllocator< T >::allocate(), and igl::geodesic::SimlpeMemoryAllocator< T >::reset().
m_max_number_of_blocks
template<class T > unsigned igl::geodesic::SimlpeMemoryAllocator< T >::m_max_number_of_blocks private
Referenced by igl::geodesic::SimlpeMemoryAllocator< T >::reset().
m_storage
template<class T > std::vector<std::vector<T> > igl::geodesic::SimlpeMemoryAllocator< T >::m_storage private
Referenced by igl::geodesic::SimlpeMemoryAllocator< T >::allocate(), and igl::geodesic::SimlpeMemoryAllocator< T >::reset().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp