Prusa Slicer: Slic3r::ResolveSocket Class Reference
Slic3r::ResolveSocket Class Reference
#include <src/slic3r/Utils/Bonjour.hpp>
Public Member Functions
ResolveSocket (const std::string &hostname, Bonjour::ReplyFn replyfn, const boost::asio::ip::address &multicast_address, const boost::asio::ip::address &interface_address, std::shared_ptr< boost::asio::io_service > io_service)
ResolveSocket (const std::string &hostname, Bonjour::ReplyFn replyfn, const boost::asio::ip::address &multicast_address, std::shared_ptr< boost::asio::io_service > io_service)
std::string get_hostname () const
void send ()
void async_receive ()
void cancel ()
Protected Member Functions
SharedSession create_session () const override
void create_requests ()
void receive_handler (SharedSession session, const boost::system::error_code &error, size_t bytes)
Protected Attributes
std::string hostname
Bonjour::ReplyFn replyfn
boost::asio::ip::address multicast_address
boost::asio::ip::udp::socket socket
boost::asio::ip::udp::endpoint mcast_endpoint
std::shared_ptr< boost::asio::io_service > io_service
std::vector< BonjourRequest > requests
Detailed Description
Constructor & Destructor Documentation
ResolveSocket() [1/2]
Slic3r::ResolveSocket::ResolveSocket (const std::string & hostname, Bonjour::ReplyFn replyfn, const boost::asio::ip::address & multicast_address, const boost::asio::ip::address & interface_address, std::shared_ptr< boost::asio::io_service > io_service) inline
    : UdpSocket(replyfn, multicast_address, interface_address, io_service)
    , hostname(hostname)
  {
    assert(!hostname.empty() && replyfn);
    create_requests();
  }
References create_requests(), hostname, and Slic3r::UdpSocket::replyfn.
ResolveSocket() [2/2]
Slic3r::ResolveSocket::ResolveSocket (const std::string & hostname, Bonjour::ReplyFn replyfn, const boost::asio::ip::address & multicast_address, std::shared_ptr< boost::asio::io_service > io_service) inline
    : UdpSocket(replyfn, multicast_address, io_service)
    , hostname(hostname)
  {
    assert(!hostname.empty() && replyfn);
    create_requests();
  }
References create_requests(), hostname, and Slic3r::UdpSocket::replyfn.
Member Function Documentation
async_receive()
void Slic3r::UdpSocket::async_receive () inherited
{
  try {
    // our session to hold the buffer + endpoint
    auto session = create_session();
    socket.async_receive_from(asio::buffer(session->buffer, session->buffer.size())
      , session->remote_endpoint
      , boost::bind(&UdpSocket::receive_handler, this, session, asio::placeholders::error, asio::placeholders::bytes_transferred));
  }
  catch (std::exception& e) {
    BOOST_LOG_TRIVIAL(error) << e.what();
  }
}
References Slic3r::UdpSocket::create_session(), error, Slic3r::UdpSocket::receive_handler(), and Slic3r::UdpSocket::socket.
Referenced by Slic3r::UdpSocket::receive_handler(), and Slic3r::UdpSocket::send().
cancel()
void Slic3r::UdpSocket::cancel () inline inherited
{ socket.cancel(); }
References Slic3r::UdpSocket::socket.
create_requests()
void Slic3r::ResolveSocket::create_requests () inline protected
  {
    requests.clear();
    // BonjourRequest::make_A / AAAA is now implemented to add .local correctly after the hostname.
      // If that is unsufficient, we need to change make_A / AAAA and pass full hostname.
    std::string trimmed_hostname = hostname;
    if (size_t dot_pos = trimmed_hostname.find_first_of('.'); dot_pos != std::string::npos)
      trimmed_hostname = trimmed_hostname.substr(0, dot_pos);
    if (auto rqst = BonjourRequest::make_A(trimmed_hostname); rqst)
      requests.push_back(std::move(rqst.get()));
    trimmed_hostname = hostname;
    if (size_t dot_pos = trimmed_hostname.find_first_of('.'); dot_pos != std::string::npos)
      trimmed_hostname = trimmed_hostname.substr(0, dot_pos);
    if (auto rqst = BonjourRequest::make_AAAA(trimmed_hostname); rqst)
      requests.push_back(std::move(rqst.get()));
  }
References hostname, Slic3r::BonjourRequest::make_A(), Slic3r::BonjourRequest::make_AAAA(), and Slic3r::UdpSocket::requests.
Referenced by ResolveSocket(), and ResolveSocket().
create_session()
SharedSession Slic3r::ResolveSocket::create_session () const override protected virtual
Implements Slic3r::UdpSocket.
{
  return std::shared_ptr< ResolveSession > (new ResolveSession(this, replyfn));
}
References Slic3r::UdpSocket::replyfn.
get_hostname()
std::string Slic3r::ResolveSocket::get_hostname () const inline
{ return hostname; }
References hostname.
Referenced by Slic3r::ResolveSession::handle_receive().
receive_handler()
void Slic3r::UdpSocket::receive_handler (SharedSession session, const boost::system::error_code & error, size_t bytes) protected inherited
{
  // let io_service to handle the datagram on session
  // from boost documentation io_service::post:
  // The io_service guarantees that the handler will only be called in a thread in which the run(), run_one(), poll() or poll_one() member functions is currently being invoked.
  io_service->post(boost::bind(&UdpSession::handle_receive, session, error, bytes));
  // immediately accept new datagrams
  async_receive();
}
References Slic3r::UdpSocket::async_receive(), error, Slic3r::UdpSession::handle_receive(), and Slic3r::UdpSocket::io_service.
Referenced by Slic3r::UdpSocket::async_receive().
send()
void Slic3r::UdpSocket::send () inherited
{
  try {
    for (const auto& request : requests)
      socket.send_to(asio::buffer(request.m_data), mcast_endpoint);
    // Should we care if this is called while already receiving? (async_receive call from receive_handler)
    async_receive();
  }
  catch (std::exception& e) {
    BOOST_LOG_TRIVIAL(error) << e.what();
  }
}
References Slic3r::UdpSocket::async_receive(), error, Slic3r::UdpSocket::mcast_endpoint, Slic3r::UdpSocket::requests, and Slic3r::UdpSocket::socket.
Member Data Documentation
hostname
std::string Slic3r::ResolveSocket::hostname protected
Referenced by ResolveSocket(), ResolveSocket(), create_requests(), and get_hostname().
io_service
std::shared_ptr< boost::asio::io_service > Slic3r::UdpSocket::io_service protected inherited
Referenced by Slic3r::UdpSocket::receive_handler().
mcast_endpoint
boost::asio::ip::udp::endpoint Slic3r::UdpSocket::mcast_endpoint protected inherited
Referenced by Slic3r::UdpSocket::send().
multicast_address
boost::asio::ip::address Slic3r::UdpSocket::multicast_address protected inherited
replyfn
Bonjour::ReplyFn Slic3r::UdpSocket::replyfn protected inherited
Referenced by Slic3r::LookupSocket::LookupSocket(), Slic3r::LookupSocket::LookupSocket(), ResolveSocket(), ResolveSocket(), Slic3r::LookupSocket::create_session(), and create_session().
requests
std::vector<BonjourRequest> Slic3r::UdpSocket::requests protected inherited
Referenced by Slic3r::LookupSocket::create_request(), create_requests(), and Slic3r::UdpSocket::send().
socket
boost::asio::ip::udp::socket Slic3r::UdpSocket::socket protected inherited
Referenced by Slic3r::UdpSocket::async_receive(), Slic3r::UdpSocket::cancel(), and Slic3r::UdpSocket::send().
The documentation for this class was generated from the following files:
src/slic3r/Utils/Bonjour.hpp
src/slic3r/Utils/Bonjour.cpp