Prusa Slicer: Slic3r::ExtrusionRole Struct Reference
Slic3r::ExtrusionRole Struct Reference
#include <src/libslic3r/ExtrusionRole.hpp>
Public Member Functions
constexpr ExtrusionRole (const ExtrusionRoleModifier bit)
constexpr ExtrusionRole (const ExtrusionRoleModifiers bits)
bool is_perimeter () const
bool is_external_perimeter () const
bool is_infill () const
bool is_solid_infill () const
bool is_external () const
bool is_bridge () const
bool is_support () const
bool is_support_base () const
bool is_support_interface () const
bool is_mixed () const
constexpr enum_bitmask operator| (option_type t) const
constexpr enum_bitmask operator| (enum_bitmask< option_type > t) const
constexpr void operator|= (option_type t)
constexpr void operator|= (enum_bitmask< option_type > t)
constexpr bool operator& (option_type t) const
constexpr bool has (option_type t) const
constexpr bool operator== (const enum_bitmask r) const
constexpr bool operator!= (const enum_bitmask r) const
constexpr bool lower (const enum_bitmask r) const
Static Public Attributes
static constexpr const ExtrusionRoleModifiers None {}
static constexpr const ExtrusionRoleModifiers Perimeter { ExtrusionRoleModifier::Perimeter }
static constexpr const ExtrusionRoleModifiers ExternalPerimeter { ExtrusionRoleModifier::Perimeter | ExtrusionRoleModifier::External }
static constexpr const ExtrusionRoleModifiers OverhangPerimeter { ExtrusionRoleModifier::Perimeter | ExtrusionRoleModifier::Bridge }
static constexpr const ExtrusionRoleModifiers InternalInfill { ExtrusionRoleModifier::Infill }
static constexpr const ExtrusionRoleModifiers SolidInfill { ExtrusionRoleModifier::Infill | ExtrusionRoleModifier::Solid }
static constexpr const ExtrusionRoleModifiers TopSolidInfill { ExtrusionRoleModifier::Infill | ExtrusionRoleModifier::Solid | ExtrusionRoleModifier::External }
static constexpr const ExtrusionRoleModifiers Ironing { ExtrusionRoleModifier::Infill | ExtrusionRoleModifier::Solid | ExtrusionRoleModifier::Ironing | ExtrusionRoleModifier::External }
static constexpr const ExtrusionRoleModifiers BridgeInfill { ExtrusionRoleModifier::Infill | ExtrusionRoleModifier::Solid | ExtrusionRoleModifier::Bridge | ExtrusionRoleModifier::External }
static constexpr const ExtrusionRoleModifiers GapFill { ExtrusionRoleModifier::Thin }
static constexpr const ExtrusionRoleModifiers Skirt { ExtrusionRoleModifier::Skirt }
static constexpr const ExtrusionRoleModifiers SupportMaterial { ExtrusionRoleModifier::Support }
static constexpr const ExtrusionRoleModifiers SupportMaterialInterface { ExtrusionRoleModifier::Support | ExtrusionRoleModifier::External }
static constexpr const ExtrusionRoleModifiers WipeTower { ExtrusionRoleModifier::Wipe }
static constexpr const ExtrusionRoleModifiers Mixed { ExtrusionRoleModifier::Mixed }
Private Types
using underlying_type = typename std::underlying_type< option_type >::type
Static Private Member Functions
static constexpr underlying_type mask_value (option_type o)
Private Attributes
underlying_type m_bits = 0
Detailed Description
Member Typedef Documentation
underlying_type
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> using Slic3r::enum_bitmask< option_type, typename >::underlying_type = typename std::underlying_type<option_type>::type private inherited
Constructor & Destructor Documentation
ExtrusionRole() [1/2]
constexpr Slic3r::ExtrusionRole::ExtrusionRole (const ExtrusionRoleModifier bit) inline constexpr
: ExtrusionRoleModifiers(bit) {}
ExtrusionRole() [2/2]
constexpr Slic3r::ExtrusionRole::ExtrusionRole (const ExtrusionRoleModifiers bits) inline constexpr
: ExtrusionRoleModifiers(bits) {}
Member Function Documentation
has()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::has (option_type t) const inline constexpr inherited
{ return m_bits & mask_value(t); }
References Slic3r::enum_bitmask< option_type, typename >::m_bits, and Slic3r::enum_bitmask< option_type, typename >::mask_value().
Referenced by Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::ModelObject::cut(), is_bridge(), is_external(), is_infill(), is_mixed(), is_perimeter(), is_solid_infill(), is_support(), Slic3r::PresetBundle::load_configbundle(), Slic3r::ModelObject::process_connector_cut(), Slic3r::ModelObject::process_modifier_cut(), Slic3r::ModelObject::process_solid_part_cut(), Slic3r::ModelObject::process_volume_cut(), and Slic3r::GUI::update_object_cut_id().
is_bridge()
bool Slic3r::ExtrusionRole::is_bridge () const inline
{ return this->ExtrusionRoleModifiers::has(ExtrusionRoleModifier::Bridge); }
References Slic3r::Bridge, and Slic3r::enum_bitmask< option_type, typename >::has().
Referenced by Slic3r::GCode::_extrude(), Slic3r::SupportSpotsGenerator::check_extrusion_entity_stability(), Slic3r::extrusion_role_to_gcode_extrusion_role(), Slic3r::ExtrusionPath::polygons_covered_by_spacing(), and Slic3r::PerimeterGenerator::thick_polyline_to_multi_path().
is_external()
bool Slic3r::ExtrusionRole::is_external () const inline
{ return this->ExtrusionRoleModifiers::has(ExtrusionRoleModifier::External); }
References Slic3r::External, and Slic3r::enum_bitmask< option_type, typename >::has().
Referenced by Slic3r::extrusion_role_to_gcode_extrusion_role(), is_external_perimeter(), is_support_base(), is_support_interface(), and Slic3r::Layer::sort_perimeters_into_islands().
is_external_perimeter()
bool Slic3r::ExtrusionRole::is_external_perimeter () const inline
{ return this->is_perimeter() && this->is_external(); }
References is_external(), and is_perimeter().
Referenced by Slic3r::GCode::_extrude(), and Slic3r::ExtrusionLine::is_external_perimeter().
is_infill()
bool Slic3r::ExtrusionRole::is_infill () const inline
{ return this->ExtrusionRoleModifiers::has(ExtrusionRoleModifier::Infill); }
References Slic3r::enum_bitmask< option_type, typename >::has(), and Slic3r::Infill.
Referenced by Slic3r::GCode::_extrude(), Slic3r::LayerTools::extruder(), and is_solid_infill().
is_mixed()
bool Slic3r::ExtrusionRole::is_mixed () const inline
{ return this->ExtrusionRoleModifiers::has(ExtrusionRoleModifier::Mixed); }
References Slic3r::enum_bitmask< option_type, typename >::has(), and Slic3r::Mixed.
Referenced by Slic3r::GCode::process_layer_single_object().
is_perimeter()
bool Slic3r::ExtrusionRole::is_perimeter () const inline
{ return this->ExtrusionRoleModifiers::has(ExtrusionRoleModifier::Perimeter); }
References Slic3r::enum_bitmask< option_type, typename >::has(), and Slic3r::Perimeter.
Referenced by Slic3r::GCode::_extrude(), Slic3r::SupportSpotsGenerator::check_extrusion_entity_stability(), Slic3r::extrusion_role_to_gcode_extrusion_role(), and is_external_perimeter().
is_solid_infill()
bool Slic3r::ExtrusionRole::is_solid_infill () const inline
{ return this->is_infill() && this->ExtrusionRoleModifiers::has(ExtrusionRoleModifier::Solid); }
References Slic3r::enum_bitmask< option_type, typename >::has(), is_infill(), and Slic3r::Solid.
Referenced by Slic3r::GCode::_extrude(), and Slic3r::ToolOrdering::collect_extruders().
is_support()
bool Slic3r::ExtrusionRole::is_support () const inline
{ return this->ExtrusionRoleModifiers::has(ExtrusionRoleModifier::Support); }
References Slic3r::enum_bitmask< option_type, typename >::has(), and Slic3r::Support.
Referenced by is_support_base(), and is_support_interface().
is_support_base()
bool Slic3r::ExtrusionRole::is_support_base () const inline
{ return this->is_support() && ! this->is_external(); }
References is_external(), and is_support().
Referenced by Slic3r::GCode::process_layer_single_object().
is_support_interface()
bool Slic3r::ExtrusionRole::is_support_interface () const inline
{ return this->is_support() && this->is_external(); }
References is_external(), and is_support().
Referenced by Slic3r::GCode::process_layer_single_object().
lower()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::lower (const enum_bitmask< option_type, typename > r) const inline constexpr inherited
{ return m_bits < r.m_bits; }
References Slic3r::enum_bitmask< option_type, typename >::m_bits.
Referenced by Slic3r::SurfaceFillParams::operator<().
mask_value()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> static constexpr underlying_type Slic3r::enum_bitmask< option_type, typename >::mask_value (option_type o) inline static constexpr private inherited
{ return 1 << static_cast<underlying_type>(o); }
Referenced by Slic3r::enum_bitmask< option_type, typename >::has(), Slic3r::enum_bitmask< option_type, typename >::operator&(), Slic3r::enum_bitmask< option_type, typename >::operator|(), and Slic3r::enum_bitmask< option_type, typename >::operator|=().
operator!=()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::operator!= (const enum_bitmask< option_type, typename > r) const inline constexpr inherited
{ return m_bits != r.m_bits; }
References Slic3r::enum_bitmask< option_type, typename >::m_bits.
operator&()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::operator& (option_type t) const inline constexpr inherited
{ return m_bits & mask_value(t); }
References Slic3r::enum_bitmask< option_type, typename >::m_bits, and Slic3r::enum_bitmask< option_type, typename >::mask_value().
operator==()
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr bool Slic3r::enum_bitmask< option_type, typename >::operator== (const enum_bitmask< option_type, typename > r) const inline constexpr inherited
{ return m_bits == r.m_bits; }
References Slic3r::enum_bitmask< option_type, typename >::m_bits.
operator|() [1/2]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr enum_bitmask Slic3r::enum_bitmask< option_type, typename >::operator| (enum_bitmask< option_type > t) const inline constexpr inherited
{ return enum_bitmask(m_bits | t.m_bits); }
References Slic3r::enum_bitmask< option_type, typename >::enum_bitmask(), and Slic3r::enum_bitmask< option_type, typename >::m_bits.
operator|() [2/2]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr enum_bitmask Slic3r::enum_bitmask< option_type, typename >::operator| (option_type t) const inline constexpr inherited
{ return enum_bitmask(m_bits | mask_value(t)); }
References Slic3r::enum_bitmask< option_type, typename >::enum_bitmask(), Slic3r::enum_bitmask< option_type, typename >::m_bits, and Slic3r::enum_bitmask< option_type, typename >::mask_value().
operator|=() [1/2]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr void Slic3r::enum_bitmask< option_type, typename >::operator|= (enum_bitmask< option_type > t) inline constexpr inherited
{ m_bits = enum_bitmask(m_bits | t.m_bits); }
References Slic3r::enum_bitmask< option_type, typename >::enum_bitmask(), and Slic3r::enum_bitmask< option_type, typename >::m_bits.
operator|=() [2/2]
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> constexpr void Slic3r::enum_bitmask< option_type, typename >::operator|= (option_type t) inline constexpr inherited
{ m_bits = enum_bitmask(m_bits | mask_value(t)); }
References Slic3r::enum_bitmask< option_type, typename >::enum_bitmask(), Slic3r::enum_bitmask< option_type, typename >::m_bits, and Slic3r::enum_bitmask< option_type, typename >::mask_value().
Member Data Documentation
BridgeInfill
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::BridgeInfill { ExtrusionRoleModifier::Infill | ExtrusionRoleModifier::Solid | ExtrusionRoleModifier::Bridge | ExtrusionRoleModifier::External } static constexpr
Referenced by Slic3r::GCode::_extrude(), Slic3r::SupportSpotsGenerator::check_stability(), Slic3r::extrusion_role_to_gcode_extrusion_role(), Slic3r::SupportSpotsGenerator::get_flow_width(), Slic3r::group_fills(), and Slic3r::SupportMaterialInternal::has_bridging_fills().
ExternalPerimeter
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::ExternalPerimeter { ExtrusionRoleModifier::Perimeter | ExtrusionRoleModifier::External } static constexpr
Referenced by Slic3r::GCode::_extrude(), Slic3r::SeamPlacerImpl::extract_perimeter_polygons(), Slic3r::SupportSpotsGenerator::get_flow_width(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops_classic().
GapFill
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::GapFill { ExtrusionRoleModifier::Thin } static constexpr
Referenced by Slic3r::GCode::_extrude(), Slic3r::extrusion_role_to_gcode_extrusion_role(), Slic3r::SupportSpotsGenerator::get_flow_width(), and Slic3r::PerimeterGenerator::process_classic().
InternalInfill
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::InternalInfill { ExtrusionRoleModifier::Infill } static constexpr
Referenced by Slic3r::GCode::_extrude(), Slic3r::extrusion_role_to_gcode_extrusion_role(), Slic3r::SupportSpotsGenerator::get_flow_width(), Slic3r::group_fills(), and Slic3r::is_overriddable().
Ironing
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::Ironing { ExtrusionRoleModifier::Infill | ExtrusionRoleModifier::Solid | ExtrusionRoleModifier::Ironing | ExtrusionRoleModifier::External } static constexpr
Referenced by Slic3r::GCode::_extrude(), Slic3r::extrusion_role_to_gcode_extrusion_role(), and Slic3r::GCode::process_layer_single_object().
m_bits
template<class option_type , typename = typename std::enable_if<std::is_enum<option_type>::value>::type> underlying_type Slic3r::enum_bitmask< option_type, typename >::m_bits = 0 private inherited
Referenced by Slic3r::enum_bitmask< option_type, typename >::has(), Slic3r::enum_bitmask< option_type, typename >::lower(), Slic3r::enum_bitmask< option_type, typename >::operator!=(), Slic3r::enum_bitmask< option_type, typename >::operator&(), Slic3r::enum_bitmask< option_type, typename >::operator==(), Slic3r::enum_bitmask< option_type, typename >::operator|(), Slic3r::enum_bitmask< option_type, typename >::operator|(), Slic3r::enum_bitmask< option_type, typename >::operator|=(), and Slic3r::enum_bitmask< option_type, typename >::operator|=().
Mixed
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::Mixed { ExtrusionRoleModifier::Mixed } static constexpr
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::ToolOrdering::collect_extruders(), Slic3r::filter_by_extrusion_role_in_place(), Slic3r::GCode::process_layer_single_object(), and Slic3r::ExtrusionEntityCollection::role().
None
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::None {} static constexpr
Referenced by Slic3r::GCode::_do_export(), Slic3r::ToolOrdering::collect_extruders(), Slic3r::extrusion_role_to_gcode_extrusion_role(), Slic3r::ExtrusionMultiPath::role(), Slic3r::ExtrusionLoop::role(), and Slic3r::ExtrusionEntityCollection::role().
OverhangPerimeter
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::OverhangPerimeter { ExtrusionRoleModifier::Perimeter | ExtrusionRoleModifier::Bridge } static constexpr
Referenced by Slic3r::SupportMaterialInternal::collect_bridging_perimeter_areas(), Slic3r::generate_extra_perimeters_over_overhangs(), and Slic3r::SupportMaterialInternal::has_bridging_perimeters().
Perimeter
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::Perimeter { ExtrusionRoleModifier::Perimeter } static constexpr
Referenced by Slic3r::GCode::_extrude(), Slic3r::SupportSpotsGenerator::get_flow_width(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops_classic().
Skirt
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::Skirt { ExtrusionRoleModifier::Skirt } static constexpr
Referenced by Slic3r::Print::_make_skirt(), and Slic3r::extrusion_role_to_gcode_extrusion_role().
SolidInfill
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::SolidInfill { ExtrusionRoleModifier::Infill | ExtrusionRoleModifier::Solid } static constexpr
Referenced by Slic3r::GCode::_extrude(), Slic3r::extrusion_role_to_gcode_extrusion_role(), Slic3r::SupportSpotsGenerator::get_flow_width(), and Slic3r::group_fills().
SupportMaterial
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::SupportMaterial { ExtrusionRoleModifier::Support } static constexpr
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::ToolOrdering::collect_extruders(), Slic3r::GCode::extrude_support(), Slic3r::extrusion_role_to_gcode_extrusion_role(), Slic3r::GCode::needs_retraction(), and Slic3r::GCode::process_layer_single_object().
SupportMaterialInterface
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::SupportMaterialInterface { ExtrusionRoleModifier::Support | ExtrusionRoleModifier::External } static constexpr
Referenced by Slic3r::ToolOrdering::collect_extruders(), Slic3r::GCode::extrude_support(), Slic3r::extrusion_role_to_gcode_extrusion_role(), and Slic3r::GCode::process_layer_single_object().
TopSolidInfill
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::TopSolidInfill { ExtrusionRoleModifier::Infill | ExtrusionRoleModifier::Solid | ExtrusionRoleModifier::External } static constexpr
Referenced by Slic3r::GCode::_extrude(), Slic3r::extrusion_role_to_gcode_extrusion_role(), Slic3r::SupportSpotsGenerator::get_flow_width(), and Slic3r::group_fills().
WipeTower
constexpr const ExtrusionRoleModifiers Slic3r::ExtrusionRole::WipeTower { ExtrusionRoleModifier::Wipe } static constexpr
Referenced by Slic3r::extrusion_role_to_gcode_extrusion_role(), and Slic3r::FakeWipeTower::getFakeExtrusionPathsFromWipeTower().
The documentation for this struct was generated from the following file:
src/libslic3r/ExtrusionRole.hpp