Prusa Slicer: ImGuiTextFilter Struct Reference
ImGuiTextFilter Struct Reference
#include <src/imgui/imgui.h>
Classes
struct ImGuiTextRange
Public Member Functions
IMGUI_API ImGuiTextFilter (const char *default_filter="")
IMGUI_API bool Draw (const char *label="Filter (inc,-exc)", float width=0.0f)
IMGUI_API bool PassFilter (const char *text, const char *text_end=NULL) const
IMGUI_API void Build ()
void Clear ()
bool IsActive () const
Public Attributes
char InputBuf [256]
ImVector< ImGuiTextRange > Filters
int CountGrep
Detailed Description
Constructor & Destructor Documentation
ImGuiTextFilter()
ImGuiTextFilter::ImGuiTextFilter (const char * default_filter = "")
{
    if (default_filter)
    {
        ImStrncpy(InputBuf, default_filter, IM_ARRAYSIZE(InputBuf));
        Build();
    }
    else
    {
        InputBuf[0] = 0;
        CountGrep = 0;
    }
}
References Build(), CountGrep, IM_ARRAYSIZE, ImStrncpy(), and InputBuf.
Member Function Documentation
Build()
void ImGuiTextFilter::Build ()
{
    Filters.resize(0);
    ImGuiTextRange input_range(InputBuf, InputBuf + strlen(InputBuf));
    input_range.split(',', &Filters);
    CountGrep = 0;
    for (int i = 0; i != Filters.Size; i++)
    {
        ImGuiTextRange& f = Filters[i];
        while (f.b < f.e && ImCharIsBlankA(f.b[0]))
            f.b++;
        while (f.e > f.b && ImCharIsBlankA(f.e[-1]))
            f.e--;
        if (f.empty())
            continue;
        if (Filters[i].b[0] != '-')
            CountGrep += 1;
    }
}
References ImGuiTextFilter::ImGuiTextRange::b, CountGrep, ImGuiTextFilter::ImGuiTextRange::e, ImGuiTextFilter::ImGuiTextRange::empty(), Filters, ImCharIsBlankA(), InputBuf, and ImGuiTextFilter::ImGuiTextRange::split().
Referenced by ImGuiTextFilter(), and Draw().
Clear()
void ImGuiTextFilter::Clear () inline
{ InputBuf[0] = 0; Build(); }
Draw()
bool ImGuiTextFilter::Draw (const char * label = "Filter (inc,-exc)", float width = 0.0f)
{
    if (width != 0.0f)
        ImGui::SetNextItemWidth(width);
    bool value_changed = ImGui::InputText(label, InputBuf, IM_ARRAYSIZE(InputBuf));
    if (value_changed)
        Build();
    return value_changed;
}
References Build(), IM_ARRAYSIZE, InputBuf, ImGui::InputText(), and ImGui::SetNextItemWidth().
Referenced by ExampleAppConsole::Draw(), ExampleAppLog::Draw(), ShowDemoWindowMisc(), and ImGui::ShowStyleEditor().
IsActive()
bool ImGuiTextFilter::IsActive () const inline
{ return !Filters.empty(); }
Referenced by ExampleAppLog::Draw().
PassFilter()
bool ImGuiTextFilter::PassFilter (const char * text, const char * text_end = NULL) const
{
    if (Filters.empty())
        return true;
    if (text == NULL)
        text = "";
    for (int i = 0; i != Filters.Size; i++)
    {
        const ImGuiTextRange& f = Filters[i];
        if (f.empty())
            continue;
        if (f.b[0] == '-')
        {
            // Subtract
            if (ImStristr(text, text_end, f.b + 1, f.e) != NULL)
                return false;
        }
        else
        {
            // Grep
            if (ImStristr(text, text_end, f.b, f.e) != NULL)
                return true;
        }
    }
    // Implicit * grep
    if (CountGrep == 0)
        return true;
    return false;
}
References ImGuiTextFilter::ImGuiTextRange::b, CountGrep, ImGuiTextFilter::ImGuiTextRange::e, ImGuiTextFilter::ImGuiTextRange::empty(), Filters, and ImStristr().
Referenced by ExampleAppConsole::Draw(), ExampleAppLog::Draw(), ShowDemoWindowMisc(), and ImGui::ShowStyleEditor().
Member Data Documentation
CountGrep
int ImGuiTextFilter::CountGrep
Referenced by ImGuiTextFilter(), Build(), and PassFilter().
Filters
ImVector<ImGuiTextRange> ImGuiTextFilter::Filters
Referenced by Build(), and PassFilter().
InputBuf
char ImGuiTextFilter::InputBuf[256]
Referenced by ImGuiTextFilter(), Build(), and Draw().
The documentation for this struct was generated from the following files:
src/imgui/imgui.h
src/imgui/imgui.cpp