Prusa Slicer: Slic3r::Measure::SurfaceFeature Class Reference
Slic3r::Measure::SurfaceFeature Class Reference
#include <src/libslic3r/Measure.hpp>
Public Member Functions
SurfaceFeature (SurfaceFeatureType type, const Vec3d &pt1, const Vec3d &pt2, std::optional< Vec3d > pt3=std::nullopt, double value=0.0)
SurfaceFeature (const Vec3d &pt)
SurfaceFeatureType get_type () const
Vec3d get_point () const
std::pair< Vec3d, Vec3d > get_edge () const
std::tuple< Vec3d, double, Vec3d > get_circle () const
std::tuple< int, Vec3d, Vec3d > get_plane () const
std::optional< Vec3d > get_extra_point () const
bool operator== (const SurfaceFeature &other) const
bool operator!= (const SurfaceFeature &other) const
Private Attributes
SurfaceFeatureType m_type { SurfaceFeatureType::Undef }
Vec3d m_pt1 { Vec3d::Zero() }
Vec3d m_pt2 { Vec3d::Zero() }
std::optional< Vec3d > m_pt3
double m_value { 0.0 }
Detailed Description
Constructor & Destructor Documentation
SurfaceFeature() [1/2]
Slic3r::Measure::SurfaceFeature::SurfaceFeature (SurfaceFeatureType type, const Vec3d & pt1, const Vec3d & pt2, std::optional< Vec3d > pt3 = std::nullopt, double value = 0.0) inline
        : m_type(type), m_pt1(pt1), m_pt2(pt2), m_pt3(pt3), m_value(value) {}
SurfaceFeature() [2/2]
Slic3r::Measure::SurfaceFeature::SurfaceFeature (const Vec3d & pt) inline explicit
    : m_type{SurfaceFeatureType::Point}, m_pt1{pt} {}
Member Function Documentation
get_circle()
std::tuple< Vec3d, double, Vec3d > Slic3r::Measure::SurfaceFeature::get_circle () const inline
{ assert(m_type == SurfaceFeatureType::Circle); return std::make_tuple(m_pt1, m_value, m_pt2); }
References Slic3r::Measure::Circle, m_pt1, m_pt2, m_type, and m_value.
Referenced by Slic3r::GUI::get_feature_offset(), Slic3r::Measure::get_measurement(), and Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
get_edge()
std::pair< Vec3d, Vec3d > Slic3r::Measure::SurfaceFeature::get_edge () const inline
{ assert(m_type == SurfaceFeatureType::Edge); return std::make_pair(m_pt1, m_pt2); }
References Slic3r::Measure::Edge, m_pt1, m_pt2, and m_type.
Referenced by Slic3r::Measure::edge_direction(), Slic3r::Measure::get_measurement(), and Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
get_extra_point()
std::optional< Vec3d > Slic3r::Measure::SurfaceFeature::get_extra_point () const inline
{ assert(m_type != SurfaceFeatureType::Undef); return m_pt3; }
References m_pt3, m_type, and Slic3r::Measure::Undef.
Referenced by Slic3r::GUI::get_feature_offset(), Slic3r::GUI::is_feature_with_center(), and Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
get_plane()
std::tuple< int, Vec3d, Vec3d > Slic3r::Measure::SurfaceFeature::get_plane () const inline
{ assert(m_type == SurfaceFeatureType::Plane); return std::make_tuple(int(m_value), m_pt1, m_pt2); }
References m_pt1, m_pt2, m_type, m_value, and Slic3r::Measure::Plane.
Referenced by Slic3r::Measure::get_measurement(), Slic3r::Measure::plane_normal(), and Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
get_point()
Vec3d Slic3r::Measure::SurfaceFeature::get_point () const inline
{ assert(m_type == SurfaceFeatureType::Point); return m_pt1; }
References m_pt1, m_type, and Slic3r::Measure::Point.
Referenced by Slic3r::GUI::get_feature_offset(), Slic3r::Measure::get_measurement(), and Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
get_type()
SurfaceFeatureType Slic3r::Measure::SurfaceFeature::get_type () const inline
{ return m_type; }
References m_type.
Referenced by Slic3r::Measure::are_parallel(), Slic3r::Measure::are_perpendicular(), Slic3r::Measure::edge_direction(), Slic3r::GUI::get_feature_offset(), Slic3r::Measure::get_measurement(), Slic3r::GUI::is_feature_with_center(), Slic3r::Measure::plane_normal(), and Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
operator!=()
bool Slic3r::Measure::SurfaceFeature::operator!= (const SurfaceFeature & other) const inline
{
        return !operator == (other);
    }
References operator==().
operator==()
bool Slic3r::Measure::SurfaceFeature::operator== (const SurfaceFeature & other) const inline
{
        if (this->m_type != other.m_type) return false;
        switch (this->m_type)
        {
        case SurfaceFeatureType::Undef: { break; }
        case SurfaceFeatureType::Point: { return (this->m_pt1.isApprox(other.m_pt1)); }
        case SurfaceFeatureType::Edge: {
            return (this->m_pt1.isApprox(other.m_pt1) && this->m_pt2.isApprox(other.m_pt2)) ||
                   (this->m_pt1.isApprox(other.m_pt2) && this->m_pt2.isApprox(other.m_pt1));
        }
        case SurfaceFeatureType::Plane:
        case SurfaceFeatureType::Circle: {
            return (this->m_pt1.isApprox(other.m_pt1) && this->m_pt2.isApprox(other.m_pt2) && std::abs(this->m_value - other.m_value) < EPSILON);
        }
        }
        return false;
    }
References Slic3r::Measure::Circle, Slic3r::Measure::Edge, EPSILON, m_pt1, m_pt2, m_type, m_value, Slic3r::Measure::Plane, Slic3r::Measure::Point, and Slic3r::Measure::Undef.
Referenced by operator!=().
Member Data Documentation
m_pt1
Vec3d Slic3r::Measure::SurfaceFeature::m_pt1 { Vec3d::Zero() } private
Referenced by get_circle(), get_edge(), get_plane(), get_point(), and operator==().
m_pt2
Vec3d Slic3r::Measure::SurfaceFeature::m_pt2 { Vec3d::Zero() } private
Referenced by get_circle(), get_edge(), get_plane(), and operator==().
m_pt3
std::optional<Vec3d> Slic3r::Measure::SurfaceFeature::m_pt3 private
Referenced by get_extra_point().
m_type
SurfaceFeatureType Slic3r::Measure::SurfaceFeature::m_type { SurfaceFeatureType::Undef } private
Referenced by get_circle(), get_edge(), get_extra_point(), get_plane(), get_point(), get_type(), and operator==().
m_value
double Slic3r::Measure::SurfaceFeature::m_value { 0.0 } private
Referenced by get_circle(), get_plane(), and operator==().
The documentation for this class was generated from the following file:
src/libslic3r/Measure.hpp