Prusa Slicer: LockButton Class Reference
LockButton Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
LockButton (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~LockButton ()
void OnButton (wxCommandEvent &event)
bool IsLocked () const
void SetLock (bool lock)
void enable ()
void disable ()
void sys_color_changed ()
Protected Member Functions
void update_button_bitmaps ()
Private Attributes
bool m_is_pushed = false
bool m_disabled = false
ScalableBitmap m_bmp_lock_closed
ScalableBitmap m_bmp_lock_closed_f
ScalableBitmap m_bmp_lock_open
ScalableBitmap m_bmp_lock_open_f
Detailed Description
Constructor & Destructor Documentation
LockButton()
LockButton::LockButton (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
                                             :
                        wxButton(parent, id, wxEmptyString, pos, size, wxBU_EXACTFIT | wxNO_BORDER)
{
    m_bmp_lock_closed   = ScalableBitmap(this, "lock_closed");
    m_bmp_lock_closed_f = ScalableBitmap(this, "lock_closed_f");
    m_bmp_lock_open     = ScalableBitmap(this, "lock_open");
    m_bmp_lock_open_f   = ScalableBitmap(this, "lock_open_f");
    Slic3r::GUI::wxGetApp().UpdateDarkUI(this);
    SetBitmap(m_bmp_lock_open.bmp());
    SetBitmapDisabled(m_bmp_lock_open.bmp());
    SetBitmapCurrent(m_bmp_lock_closed_f.bmp());
    //button events
    Bind(wxEVT_BUTTON, &LockButton::OnButton, this);
}
References ScalableBitmap::bmp(), m_bmp_lock_closed, m_bmp_lock_closed_f, m_bmp_lock_open, m_bmp_lock_open_f, OnButton(), and wxEVT_BUTTON.
~LockButton()
LockButton::~LockButton () inline
{}
Member Function Documentation
disable()
void LockButton::disable () inline
{ m_disabled = true;  }
References m_disabled.
enable()
void LockButton::enable () inline
{ m_disabled = false; }
References m_disabled.
Referenced by Slic3r::GUI::ObjectManipulation::update_if_dirty().
IsLocked()
bool LockButton::IsLocked () const inline
{ return m_is_pushed; }
References m_is_pushed.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation().
OnButton()
void LockButton::OnButton (wxCommandEvent & event)
{
    if (m_disabled)
        return;
    SetLock(!m_is_pushed);
    event.Skip();
}
References m_disabled, m_is_pushed, and SetLock().
Referenced by LockButton().
SetLock()
void LockButton::SetLock (bool lock)
{
    if (m_is_pushed != lock) {
        m_is_pushed = lock;
        update_button_bitmaps();
    }
}
References m_is_pushed, and update_button_bitmaps().
Referenced by OnButton(), and Slic3r::GUI::ObjectManipulation::update_if_dirty().
sys_color_changed()
void LockButton::sys_color_changed ()
{
    Slic3r::GUI::wxGetApp().UpdateDarkUI(this);
    m_bmp_lock_closed.sys_color_changed();
    m_bmp_lock_closed_f.sys_color_changed();
    m_bmp_lock_open.sys_color_changed();
    m_bmp_lock_open_f.sys_color_changed();
    update_button_bitmaps();
}
References m_bmp_lock_closed, m_bmp_lock_closed_f, m_bmp_lock_open, m_bmp_lock_open_f, ScalableBitmap::sys_color_changed(), and update_button_bitmaps().
Referenced by Slic3r::GUI::ObjectManipulation::sys_color_changed().
update_button_bitmaps()
void LockButton::update_button_bitmaps () protected
{
    SetBitmap(m_is_pushed ? m_bmp_lock_closed.bmp() : m_bmp_lock_open.bmp());
    SetBitmapCurrent(m_is_pushed ? m_bmp_lock_closed_f.bmp() : m_bmp_lock_open_f.bmp());
    Refresh();
    Update();
}
References ScalableBitmap::bmp(), m_bmp_lock_closed, m_bmp_lock_closed_f, m_bmp_lock_open, m_bmp_lock_open_f, and m_is_pushed.
Referenced by SetLock(), and sys_color_changed().
Member Data Documentation
m_bmp_lock_closed
ScalableBitmap LockButton::m_bmp_lock_closed private
Referenced by LockButton(), sys_color_changed(), and update_button_bitmaps().
m_bmp_lock_closed_f
ScalableBitmap LockButton::m_bmp_lock_closed_f private
Referenced by LockButton(), sys_color_changed(), and update_button_bitmaps().
m_bmp_lock_open
ScalableBitmap LockButton::m_bmp_lock_open private
Referenced by LockButton(), sys_color_changed(), and update_button_bitmaps().
m_bmp_lock_open_f
ScalableBitmap LockButton::m_bmp_lock_open_f private
Referenced by LockButton(), sys_color_changed(), and update_button_bitmaps().
m_disabled
bool LockButton::m_disabled = false private
Referenced by disable(), enable(), and OnButton().
m_is_pushed
bool LockButton::m_is_pushed = false private
Referenced by IsLocked(), OnButton(), SetLock(), and update_button_bitmaps().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp