Prusa Slicer: Slic3r::GUI::TransformationType Class Reference
Slic3r::GUI::TransformationType Class Reference
#include <src/slic3r/GUI/GUI_Geometry.hpp>
Public Types
enum Enum {
World = 0 , Instance = 1 , Local = 2 , Absolute = 0 ,
Relative = 4 , Joint = 0 , Independent = 8 , World_Relative_Joint = World | Relative | Joint ,
World_Relative_Independent = World | Relative | Independent , Instance_Absolute_Joint = Instance | Absolute | Joint , Instance_Absolute_Independent = Instance | Absolute | Independent , Instance_Relative_Joint = Instance | Relative | Joint ,
Instance_Relative_Independent = Instance | Relative | Independent , Local_Absolute_Joint = Local | Absolute | Joint , Local_Absolute_Independent = Local | Absolute | Independent , Local_Relative_Joint = Local | Relative | Joint ,
Local_Relative_Independent = Local | Relative | Independent
}
Public Member Functions
TransformationType ()
TransformationType (Enum value)
TransformationType & operator= (Enum value)
Enum operator() () const
bool has (Enum v) const
void set_world ()
void set_instance ()
void set_local ()
void set_absolute ()
void set_relative ()
void set_joint ()
void set_independent ()
bool world () const
bool instance () const
bool local () const
bool absolute () const
bool relative () const
bool joint () const
bool independent () const
Private Member Functions
void add (Enum v)
void remove (Enum v)
Private Attributes
Enum m_value
Detailed Description
Member Enumeration Documentation
Enum
enum Slic3r::GUI::TransformationType::Enum
Enumerator
World
Instance
Local
Absolute
Relative
Joint
Independent
World_Relative_Joint
World_Relative_Independent
Instance_Absolute_Joint
Instance_Absolute_Independent
Instance_Relative_Joint
Instance_Relative_Independent
Local_Absolute_Joint
Local_Absolute_Independent
Local_Relative_Joint
Local_Relative_Independent
              {
        // Transforming in a world coordinate system
        World = 0,
        // Transforming in a instance coordinate system
        Instance = 1,
        // Transforming in a local coordinate system
        Local = 2,
        // Absolute transformations, allowed in local coordinate system only.
        Absolute = 0,
        // Relative transformations, allowed in both local and world coordinate system.
        Relative = 4,
        // For group selection, the transformation is performed as if the group made a single solid body.
        Joint = 0,
        // For group selection, the transformation is performed on each object independently.
        Independent = 8,
        World_Relative_Joint = World | Relative | Joint,
        World_Relative_Independent = World | Relative | Independent,
        Instance_Absolute_Joint = Instance | Absolute | Joint,
        Instance_Absolute_Independent = Instance | Absolute | Independent,
        Instance_Relative_Joint = Instance | Relative | Joint,
        Instance_Relative_Independent = Instance | Relative | Independent,
        Local_Absolute_Joint = Local | Absolute | Joint,
        Local_Absolute_Independent = Local | Absolute | Independent,
        Local_Relative_Joint = Local | Relative | Joint,
        Local_Relative_Independent = Local | Relative | Independent,
    };
Constructor & Destructor Documentation
TransformationType() [1/2]
Slic3r::GUI::TransformationType::TransformationType () inline
: m_value(World) {}
TransformationType() [2/2]
Slic3r::GUI::TransformationType::TransformationType (Enum value) inline
: m_value(value) {}
Member Function Documentation
absolute()
bool Slic3r::GUI::TransformationType::absolute () const inline
{ return !this->has(Relative); }
References has(), and Relative.
Referenced by Slic3r::GUI::ObjectManipulation::change_rotation_value(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale_and_translate(), and Slic3r::GUI::Selection::translate().
add()
void Slic3r::GUI::TransformationType::add (Enum v) inline private
{ m_value = Enum((unsigned int)m_value | (unsigned int)v); }
References m_value.
Referenced by set_independent(), set_instance(), set_local(), and set_relative().
has()
bool Slic3r::GUI::TransformationType::has (Enum v) const inline
{ return ((unsigned int)m_value & (unsigned int)v) != 0; }
References m_value.
Referenced by absolute(), independent(), instance(), joint(), local(), relative(), and world().
independent()
bool Slic3r::GUI::TransformationType::independent () const inline
{ return this->has(Independent); }
References has(), and Independent.
Referenced by Slic3r::GUI::Selection::transform_instance_relative(), and Slic3r::GUI::Selection::transform_volume_relative().
instance()
bool Slic3r::GUI::TransformationType::instance () const inline
{ return this->has(Instance); }
References has(), and Instance.
Referenced by Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale_and_translate(), Slic3r::GUI::Selection::transform_instance_relative(), Slic3r::GUI::Selection::transform_volume_relative(), and Slic3r::GUI::Selection::translate().
joint()
bool Slic3r::GUI::TransformationType::joint () const inline
{ return !this->has(Independent); }
References has(), and Independent.
local()
bool Slic3r::GUI::TransformationType::local () const inline
{ return this->has(Local); }
References has(), and Local.
Referenced by Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale_and_translate(), Slic3r::GUI::Selection::transform_volume_relative(), and Slic3r::GUI::Selection::translate().
operator()()
Enum Slic3r::GUI::TransformationType::operator() () const inline
{ return m_value; }
References m_value.
operator=()
TransformationType & Slic3r::GUI::TransformationType::operator= (Enum value) inline
{ m_value = value; return *this; }
References m_value.
relative()
bool Slic3r::GUI::TransformationType::relative () const inline
{ return this->has(Relative); }
References has(), and Relative.
Referenced by Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::transform_instance_relative(), Slic3r::GUI::Selection::transform_volume_relative(), and Slic3r::GUI::Selection::translate().
remove()
void Slic3r::GUI::TransformationType::remove (Enum v) inline private
{ m_value = Enum((unsigned int)m_value & (~(unsigned int)v)); }
References m_value.
Referenced by set_absolute(), set_instance(), set_joint(), set_local(), and set_world().
set_absolute()
void Slic3r::GUI::TransformationType::set_absolute () inline
{ this->remove(Relative); }
References Relative, and remove().
set_independent()
void Slic3r::GUI::TransformationType::set_independent () inline
{ this->add(Independent); }
References add(), and Independent.
Referenced by Slic3r::GUI::ObjectManipulation::change_rotation_value(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), and Slic3r::GUI::Selection::scale_and_translate().
set_instance()
void Slic3r::GUI::TransformationType::set_instance () inline
{ this->remove(Local); this->add(Instance); }
References add(), Instance, Local, and remove().
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectManipulation::change_position_value(), Slic3r::GUI::ObjectManipulation::change_rotation_value(), Slic3r::GUI::ObjectManipulation::do_scale(), Slic3r::GUI::ObjectManipulation::do_size(), Slic3r::GUI::GLCanvas3D::mirror_selection(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), and Slic3r::GUI::GLGizmoScale3D::on_mouse().
set_joint()
void Slic3r::GUI::TransformationType::set_joint () inline
{ this->remove(Independent); }
References Independent, and remove().
Referenced by Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), and Slic3r::GUI::Selection::scale_to_fit_print_volume().
set_local()
void Slic3r::GUI::TransformationType::set_local () inline
{ this->remove(Instance); this->add(Local); }
References add(), Instance, Local, and remove().
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectManipulation::change_position_value(), Slic3r::GUI::ObjectManipulation::change_rotation_value(), Slic3r::GUI::ObjectManipulation::do_scale(), Slic3r::GUI::ObjectManipulation::do_size(), Slic3r::GUI::GLCanvas3D::mirror_selection(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), and Slic3r::GUI::GLGizmoScale3D::on_mouse().
set_relative()
void Slic3r::GUI::TransformationType::set_relative () inline
{ this->add(Relative); }
References add(), and Relative.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectManipulation::change_position_value(), Slic3r::GUI::ObjectManipulation::change_rotation_value(), Slic3r::GUI::ObjectManipulation::do_scale(), Slic3r::GUI::GLCanvas3D::mirror_selection(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLCanvas3D::on_key(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::Selection::scale_and_translate(), and Slic3r::GUI::Selection::scale_to_fit_print_volume().
set_world()
void Slic3r::GUI::TransformationType::set_world () inline
{ this->remove(Instance); this->remove(Local); }
References Instance, Local, and remove().
Referenced by Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), and Slic3r::GUI::Selection::scale_to_fit_print_volume().
world()
bool Slic3r::GUI::TransformationType::world () const inline
{ return !this->has(Instance) && !this->has(Local); }
References has(), Instance, and Local.
Referenced by Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale_and_translate(), Slic3r::GUI::Selection::transform_instance_relative(), and Slic3r::GUI::Selection::transform_volume_relative().
Member Data Documentation
m_value
Enum Slic3r::GUI::TransformationType::m_value private
Referenced by add(), has(), operator()(), operator=(), and remove().
The documentation for this class was generated from the following file:
src/slic3r/GUI/GUI_Geometry.hpp