Prusa Slicer: Benchmark Class Reference
Benchmark Class Reference
#include <src/libnest2d/tools/benchmark.h>
Public Member Functions
void start ()
void stop ()
double getElapsedSec ()
Private Types
typedef std::chrono::high_resolution_clock Clock
typedef Clock::duration Duration
typedef Clock::time_point TimePoint
Private Member Functions
double to_sec (Duration d)
Private Attributes
TimePoint t1
TimePoint t2
Duration d
Detailed Description
A class for doing benchmarks.
Member Typedef Documentation
Clock
typedef std::chrono::high_resolution_clock Benchmark::Clock private
Duration
typedef Clock::duration Benchmark::Duration private
TimePoint
typedef Clock::time_point Benchmark::TimePoint private
Member Function Documentation
getElapsedSec()
double Benchmark::getElapsedSec () inline
Get the time elapsed between a start() end a stop() call.
Returns
Returns the elapsed time in seconds.
{  d = t2 - t1; return to_sec(d); }
References d, t1, t2, and to_sec().
Referenced by Slic3r::sla::create_support_tree(), Slic3r::SLAPrint::Steps::generate_preview(), and Slic3r::SLAPrint::process().
start()
void Benchmark::start () inline
Measure time from the moment of this call.
{  t1 = Clock::now(); }
References t1.
Referenced by Slic3r::sla::create_support_tree(), Slic3r::SLAPrint::Steps::generate_preview(), and Slic3r::SLAPrint::process().
stop()
void Benchmark::stop () inline
Measure time to the moment of this call.
{  t2 = Clock::now(); }
References t2.
Referenced by Slic3r::sla::create_support_tree(), Slic3r::SLAPrint::Steps::generate_preview(), and Slic3r::SLAPrint::process().
to_sec()
double Benchmark::to_sec (Duration d) inline private
{
        return d.count() * double(Duration::period::num) / Duration::period::den;
    }
References d.
Referenced by getElapsedSec().
Member Data Documentation
d
Duration Benchmark::d private
Referenced by getElapsedSec(), and to_sec().
t1
TimePoint Benchmark::t1 private
Referenced by getElapsedSec(), and start().
t2
TimePoint Benchmark::t2 private
Referenced by getElapsedSec(), and stop().
The documentation for this class was generated from the following file:
src/libnest2d/tools/benchmark.h