Prusa Slicer: Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType > Struct Template Reference
Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType > Struct Template Reference
Expression type for return value of FullPivHouseholderQR::matrixQ()
#include <src/eigen/Eigen/src/QR/FullPivHouseholderQR.h>
Public Types
typedef FullPivHouseholderQR< MatrixType >::IntDiagSizeVectorType IntDiagSizeVectorType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef Matrix< typename MatrixType::Scalar, 1, MatrixType::RowsAtCompileTime, RowMajor, 1, MatrixType::MaxRowsAtCompileTime > WorkVectorType
typedef internal::traits< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
FullPivHouseholderQRMatrixQReturnType (const MatrixType &qr, const HCoeffsType &hCoeffs, const IntDiagSizeVectorType &rowsTranspositions)
template<typename ResultType >
void evalTo (ResultType &result) const
template<typename ResultType >
void evalTo (ResultType &result, WorkVectorType &workspace) const
Index rows () const
Index cols () const
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
MatrixType::Nested m_qr
HCoeffsType::Nested m_hCoeffs
IntDiagSizeVectorType::Nested m_rowsTranspositions
Detailed Description
template<typename MatrixType>
struct Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >
Expression type for return value of FullPivHouseholderQR::matrixQ()
Template Parameters
MatrixType type of underlying dense matrix
Member Typedef Documentation
Base
typedef internal::dense_xpr_base<ReturnByValue>::type Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::Base inherited
HCoeffsType
template<typename MatrixType > typedef internal::plain_diag_type<MatrixType>::type Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::HCoeffsType
IntDiagSizeVectorType
template<typename MatrixType > typedef FullPivHouseholderQR<MatrixType>::IntDiagSizeVectorType Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::IntDiagSizeVectorType
ReturnType
typedef internal::traits<FullPivHouseholderQRMatrixQReturnType< MatrixType > >::ReturnType Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::ReturnType inherited
WorkVectorType
template<typename MatrixType > typedef Matrix<typename MatrixType::Scalar, 1, MatrixType::RowsAtCompileTime, RowMajor, 1, MatrixType::MaxRowsAtCompileTime> Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::WorkVectorType
Constructor & Destructor Documentation
FullPivHouseholderQRMatrixQReturnType()
template<typename MatrixType > Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::FullPivHouseholderQRMatrixQReturnType (const MatrixType & qr, const HCoeffsType & hCoeffs, const IntDiagSizeVectorType & rowsTranspositions) inline
    : m_qr(qr),
      m_hCoeffs(hCoeffs),
      m_rowsTranspositions(rowsTranspositions)
  {}
Member Function Documentation
coeff() [1/2]
const Unusable & Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::coeff (Index) const inline inherited
{ return *reinterpret_cast<const Unusable*>(this); }
coeff() [2/2]
const Unusable & Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::coeff (Index , Index) const inline inherited
{ return *reinterpret_cast<const Unusable*>(this); }
coeffRef() [1/2]
Unusable & Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::coeffRef (Index) inline inherited
{ return *reinterpret_cast<Unusable*>(this); }
coeffRef() [2/2]
Unusable & Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::coeffRef (Index , Index) inline inherited
{ return *reinterpret_cast<Unusable*>(this); }
cols()
template<typename MatrixType > Index Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::cols () const inline
{ return m_qr.rows(); }
References Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_qr.
Referenced by Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo().
evalTo() [1/3]
EIGEN_DEVICE_FUNC void Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::evalTo (Dest & dst) const inline inherited
    { static_cast<const Derived*>(this)->evalTo(dst); }
evalTo() [2/3]
template<typename MatrixType > template<typename ResultType > void Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo (ResultType & result) const inline
  {
    const Index rows = m_qr.rows();
    WorkVectorType workspace(rows);
    evalTo(result, workspace);
  }
References Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_qr, and Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::rows().
Referenced by Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo().
evalTo() [3/3]
template<typename MatrixType > template<typename ResultType > void Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo (ResultType & result, WorkVectorType & workspace) const inline
  {
    using numext::conj;
    // compute the product H'_0 H'_1 ... H'_n-1,
    // where H_k is the k-th Householder transformation I - h_k v_k v_k'
    // and v_k is the k-th Householder vector [1,m_qr(k+1,k), m_qr(k+2,k), ...]
    const Index rows = m_qr.rows();
    const Index cols = m_qr.cols();
    const Index size = (std::min)(rows, cols);
    workspace.resize(rows);
    result.setIdentity(rows, rows);
    for (Index k = size-1; k >= 0; k--)
    {
      result.block(k, k, rows-k, rows-k)
            .applyHouseholderOnTheLeft(m_qr.col(k).tail(rows-k-1), conj(m_hCoeffs.coeff(k)), &workspace.coeffRef(k));
      result.row(k).swap(result.row(m_rowsTranspositions.coeff(k)));
    }
  }
References Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::coeffRef(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::cols(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_hCoeffs, Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_qr, Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_rowsTranspositions, Eigen::PlainObjectBase< Derived >::resize(), and Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::rows().
rows()
template<typename MatrixType > Index Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::rows () const inline
{ return m_qr.rows(); }
References Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_qr.
Referenced by Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), and Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo().
Member Data Documentation
m_hCoeffs
template<typename MatrixType > HCoeffsType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_hCoeffs protected
Referenced by Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo().
m_qr
template<typename MatrixType > MatrixType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_qr protected
Referenced by Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::cols(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), and Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::rows().
m_rowsTranspositions
template<typename MatrixType > IntDiagSizeVectorType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::m_rowsTranspositions protected
Referenced by Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/QR/FullPivHouseholderQR.h