Prusa Slicer: Slic3r::SLAPrintStatistics Struct Reference
Slic3r::SLAPrintStatistics Struct Reference
#include <src/libslic3r/SLAPrint.hpp>
Public Member Functions
SLAPrintStatistics ()
DynamicConfig config () const
std::string finalize_output_path (const std::string &path_in) const
void clear ()
Static Public Member Functions
static DynamicConfig placeholders ()
Public Attributes
double estimated_print_time
double objects_used_material
double support_used_material
size_t slow_layers_count
size_t fast_layers_count
double total_cost
double total_weight
std::vector< double > layers_times
Detailed Description
Constructor & Destructor Documentation
SLAPrintStatistics()
Slic3r::SLAPrintStatistics::SLAPrintStatistics () inline
{ clear(); }
Member Function Documentation
clear()
void Slic3r::SLAPrintStatistics::clear () inline
                 {
        estimated_print_time = 0.;
        objects_used_material = 0.;
        support_used_material = 0.;
        slow_layers_count = 0;
        fast_layers_count = 0;
        total_cost = 0.;
        total_weight = 0.;
        layers_times.clear();
    }
Referenced by Slic3r::SLAPrint::Steps::merge_slices_and_eval_stats().
config()
DynamicConfig Slic3r::SLAPrintStatistics::config () const
{
    DynamicConfig config;
    const std::string print_time = Slic3r::short_time(get_time_dhms(float(this->estimated_print_time)));
    config.set_key_value("print_time", new ConfigOptionString(print_time));
    config.set_key_value("objects_used_material", new ConfigOptionFloat(this->objects_used_material));
    config.set_key_value("support_used_material", new ConfigOptionFloat(this->support_used_material));
    config.set_key_value("total_cost", new ConfigOptionFloat(this->total_cost));
    config.set_key_value("total_weight", new ConfigOptionFloat(this->total_weight));
    return config;
}
References Slic3r::SLAPrintObject::config(), Slic3r::get_time_dhms(), and Slic3r::short_time().
Referenced by Slic3r::SLAPrint::output_filename().
finalize_output_path()
std::string Slic3r::SLAPrintStatistics::finalize_output_path (const std::string & path_in) const
{
    std::string final_path;
    try {
        boost::filesystem::path path(path_in);
        DynamicConfig cfg = this->config();
        PlaceholderParser pp;
        std::string new_stem = pp.process(path.stem().string(), 0, &cfg);
        final_path = (path.parent_path() / (new_stem + path.extension().string())).string();
    }
    catch (const std::exception &ex) {
        BOOST_LOG_TRIVIAL(error) << "Failed to apply the print statistics to the export file name: " << ex.what();
        final_path = path_in;
    }
    return final_path;
}
References Slic3r::SLAPrintObject::config(), error, and Slic3r::PlaceholderParser::process().
Referenced by Slic3r::BackgroundSlicingProcess::prepare_upload(), Slic3r::BackgroundSlicingProcess::process_sla(), and Slic3r::CLI::run().
placeholders()
DynamicConfig Slic3r::SLAPrintStatistics::placeholders () static
{
    DynamicConfig config;
    for (const char *key : {
        "print_time", "total_cost", "total_weight",
        "objects_used_material", "support_used_material" })
        config.set_key_value(key, new ConfigOptionString(std::string("{") + key + "}"));
    return config;
}
References Slic3r::SLAPrintObject::config().
Referenced by Slic3r::SLAPrint::output_filename().
Member Data Documentation
estimated_print_time
double Slic3r::SLAPrintStatistics::estimated_print_time
Referenced by Slic3r::anonymous_namespace{SL1.cpp}::fill_iniconf(), Slic3r::SLAPrint::Steps::merge_slices_and_eval_stats(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
fast_layers_count
size_t Slic3r::SLAPrintStatistics::fast_layers_count
Referenced by Slic3r::anonymous_namespace{SL1.cpp}::fill_iniconf(), and Slic3r::SLAPrint::Steps::merge_slices_and_eval_stats().
layers_times
std::vector<double> Slic3r::SLAPrintStatistics::layers_times
Referenced by Slic3r::SLAPrint::Steps::merge_slices_and_eval_stats(), and Slic3r::GUI::Preview::update_layers_slider().
objects_used_material
double Slic3r::SLAPrintStatistics::objects_used_material
Referenced by Slic3r::anonymous_namespace{AnycubicSLA.cpp}::fill_header(), Slic3r::anonymous_namespace{SL1.cpp}::fill_iniconf(), Slic3r::SLAPrint::Steps::merge_slices_and_eval_stats(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
slow_layers_count
size_t Slic3r::SLAPrintStatistics::slow_layers_count
Referenced by Slic3r::anonymous_namespace{SL1.cpp}::fill_iniconf(), and Slic3r::SLAPrint::Steps::merge_slices_and_eval_stats().
support_used_material
double Slic3r::SLAPrintStatistics::support_used_material
Referenced by Slic3r::anonymous_namespace{AnycubicSLA.cpp}::fill_header(), Slic3r::anonymous_namespace{SL1.cpp}::fill_iniconf(), Slic3r::SLAPrint::Steps::merge_slices_and_eval_stats(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
total_cost
double Slic3r::SLAPrintStatistics::total_cost
total_weight
double Slic3r::SLAPrintStatistics::total_weight
The documentation for this struct was generated from the following files:
src/libslic3r/SLAPrint.hpp
src/libslic3r/SLAPrint.cpp