Prusa Slicer: Slic3r::ExPolygonWithOffset Struct Reference
Slic3r::ExPolygonWithOffset Struct Reference
Public Member Functions
ExPolygonWithOffset (const ExPolygon &expolygon, float angle, coord_t aoffset1, coord_t aoffset2=0)
ExPolygonWithOffset (const ExPolygonWithOffset &rhs, float angle)
bool is_contour_outer (size_t idx) const
bool is_contour_inner (size_t idx) const
const Polygon & contour (size_t idx) const
Polygon & contour (size_t idx)
bool is_contour_ccw (size_t idx) const
BoundingBox bounding_box_src () const
BoundingBox bounding_box_outer () const
BoundingBox bounding_box_inner () const
Public Attributes
ExPolygon polygons_src
Polygons polygons_outer
Polygons polygons_inner
size_t n_contours_outer
size_t n_contours_inner
size_t n_contours
Protected Attributes
std::vector< unsigned char > polygons_ccw
Detailed Description
Constructor & Destructor Documentation
ExPolygonWithOffset() [1/2]
Slic3r::ExPolygonWithOffset::ExPolygonWithOffset (const ExPolygon & expolygon, float angle, coord_t aoffset1, coord_t aoffset2 = 0) inline
    {
        // Copy and rotate the source polygons.
        polygons_src = expolygon;
        if (angle != 0.f) {
            polygons_src.contour.rotate(angle);
            for (Polygon &hole : polygons_src.holes)
                hole.rotate(angle);
        }
        double miterLimit = DefaultMiterLimit;
        // for the infill pattern, don't cut the corners.
        // default miterLimt = 3
        //double miterLimit = 10.;
        // FIXME: Resolve properly the cases when it is constructed with aoffset1 = 0 and aoffset2 = 0,
        //        that is used in sample_grid_pattern() for Lightning infill.
        // assert(aoffset1 < 0);
        assert(aoffset2 <= 0);
        // assert(aoffset2 == 0 || aoffset2 < aoffset1);
//        bool sticks_removed =
        remove_sticks(polygons_src);
//        if (sticks_removed) BOOST_LOG_TRIVIAL(error) << "Sticks removed!";
        polygons_outer = aoffset1 == 0 ? to_polygons(polygons_src) : offset(polygons_src, float(aoffset1), ClipperLib::jtMiter, miterLimit);
        if (aoffset2 < 0)
            polygons_inner = shrink(polygons_outer, float(aoffset1 - aoffset2), ClipperLib::jtMiter, miterLimit);
    // Filter out contours with zero area or small area, contours with 2 points only.
        const double min_area_threshold = 0.01 * aoffset2 * aoffset2;
        remove_small(polygons_outer, min_area_threshold);
        remove_small(polygons_inner, min_area_threshold);
        remove_sticks(polygons_outer);
        remove_sticks(polygons_inner);
    n_contours_outer = polygons_outer.size();
        n_contours_inner = polygons_inner.size();
        n_contours = n_contours_outer + n_contours_inner;
        polygons_ccw.assign(n_contours, false);
        for (size_t i = 0; i < n_contours; ++ i) {
            contour(i).remove_duplicate_points();
            assert(! contour(i).has_duplicate_points());
            polygons_ccw[i] = Slic3r::Geometry::is_ccw(contour(i));
        }
    }
References Slic3r::angle(), Slic3r::ExPolygon::contour, contour(), Slic3r::DefaultMiterLimit, Slic3r::has_duplicate_points(), Slic3r::ExPolygon::holes, Slic3r::Geometry::is_ccw(), ClipperLib::jtMiter, n_contours, n_contours_inner, n_contours_outer, Slic3r::offset(), polygons_ccw, polygons_inner, polygons_outer, polygons_src, Slic3r::MultiPoint::remove_duplicate_points(), Slic3r::remove_small(), Slic3r::remove_sticks(), Slic3r::MultiPoint::rotate(), Slic3r::shrink(), and Slic3r::to_polygons().
ExPolygonWithOffset() [2/2]
Slic3r::ExPolygonWithOffset::ExPolygonWithOffset (const ExPolygonWithOffset & rhs, float angle) inline
                                                                     : ExPolygonWithOffset(rhs) {
        if (angle != 0.f) {
            this->polygons_src.contour.rotate(angle);
            for (Polygon &hole : this->polygons_src.holes)
                hole.rotate(angle);
            for (Polygon &poly : this->polygons_outer)
                poly.rotate(angle);
            for (Polygon &poly : this->polygons_inner)
                poly.rotate(angle);
        }
    }
References Slic3r::angle(), Slic3r::ExPolygon::contour, Slic3r::ExPolygon::holes, polygons_inner, polygons_outer, polygons_src, and Slic3r::MultiPoint::rotate().
Member Function Documentation
bounding_box_inner()
BoundingBox Slic3r::ExPolygonWithOffset::bounding_box_inner () const inline
        { return get_extents(polygons_inner); }
References Slic3r::get_extents(), and polygons_inner.
bounding_box_outer()
BoundingBox Slic3r::ExPolygonWithOffset::bounding_box_outer () const inline
        { return get_extents(polygons_outer); }
References Slic3r::get_extents(), and polygons_outer.
Referenced by Slic3r::FillSupportBase::fill_surface(), and Slic3r::FillRectilinear::fill_surface_by_lines().
bounding_box_src()
BoundingBox Slic3r::ExPolygonWithOffset::bounding_box_src () const inline
        { return get_extents(polygons_src); }
References Slic3r::get_extents(), and polygons_src.
Referenced by Slic3r::FillRectilinear::fill_surface_by_lines(), and Slic3r::make_fill_lines().
contour() [1/2]
Polygon & Slic3r::ExPolygonWithOffset::contour (size_t idx) inline
        { return is_contour_outer(idx) ? polygons_outer[idx] : polygons_inner[idx - n_contours_outer]; }
References is_contour_outer(), n_contours_outer, polygons_inner, and polygons_outer.
contour() [2/2]
const Polygon & Slic3r::ExPolygonWithOffset::contour (size_t idx) const inline
        { return is_contour_outer(idx) ? polygons_outer[idx] : polygons_inner[idx - n_contours_outer]; }
References is_contour_outer(), n_contours_outer, polygons_inner, and polygons_outer.
Referenced by ExPolygonWithOffset(), Slic3r::connect_segment_intersections_by_contours(), Slic3r::emit_perimeter_prev_next_segment(), Slic3r::emit_perimeter_segment_on_vertical_line(), Slic3r::measure_perimeter_horizontal_segment_length(), Slic3r::measure_perimeter_segment_on_vertical_line_length(), and Slic3r::slice_region_by_vertical_lines().
is_contour_ccw()
bool Slic3r::ExPolygonWithOffset::is_contour_ccw (size_t idx) const inline
{ return polygons_ccw[idx]; }
References polygons_ccw.
is_contour_inner()
bool Slic3r::ExPolygonWithOffset::is_contour_inner (size_t idx) const inline
{ return idx >= n_contours_outer; }
References n_contours_outer.
is_contour_outer()
bool Slic3r::ExPolygonWithOffset::is_contour_outer (size_t idx) const inline
{ return idx < n_contours_outer; }
References n_contours_outer.
Referenced by contour(), contour(), and Slic3r::slice_region_by_vertical_lines().
Member Data Documentation
n_contours
size_t Slic3r::ExPolygonWithOffset::n_contours
Referenced by ExPolygonWithOffset(), Slic3r::FillSupportBase::fill_surface(), Slic3r::FillRectilinear::fill_surface_by_multilines(), and Slic3r::slice_region_by_vertical_lines().
n_contours_inner
size_t Slic3r::ExPolygonWithOffset::n_contours_inner
Referenced by ExPolygonWithOffset(), and Slic3r::FillRectilinear::fill_surface_by_lines().
n_contours_outer
size_t Slic3r::ExPolygonWithOffset::n_contours_outer
Referenced by ExPolygonWithOffset(), contour(), contour(), is_contour_inner(), and is_contour_outer().
polygons_ccw
std::vector<unsigned char> Slic3r::ExPolygonWithOffset::polygons_ccw protected
Referenced by ExPolygonWithOffset(), and is_contour_ccw().
polygons_inner
Polygons Slic3r::ExPolygonWithOffset::polygons_inner
Referenced by ExPolygonWithOffset(), ExPolygonWithOffset(), bounding_box_inner(), contour(), contour(), and Slic3r::slice_region_by_vertical_lines().
polygons_outer
Polygons Slic3r::ExPolygonWithOffset::polygons_outer
Referenced by ExPolygonWithOffset(), ExPolygonWithOffset(), bounding_box_outer(), contour(), contour(), Slic3r::FillSupportBase::fill_surface(), Slic3r::FillRectilinear::fill_surface_by_multilines(), and Slic3r::slice_region_by_vertical_lines().
polygons_src
ExPolygon Slic3r::ExPolygonWithOffset::polygons_src
Referenced by ExPolygonWithOffset(), ExPolygonWithOffset(), bounding_box_src(), and Slic3r::slice_region_by_vertical_lines().
The documentation for this struct was generated from the following file:
src/libslic3r/Fill/FillRectilinear.cpp