Prusa Slicer: libnest2d::RotatedBox< Pt, Unit > Class Template Reference
libnest2d::RotatedBox< Pt, Unit > Class Template Reference
#include <src/libnest2d/include/libnest2d/utils/rotcalipers.hpp>
Public Member Functions
RotatedBox ()=default
RotatedBox (const Pt &axis, Unit b, Unit r)
long double area () const
long double width () const
long double height () const
Unit bottom_extent () const
Unit right_extent () const
const Pt & axis () const
Radians angleToX () const
Private Attributes
Pt axis_
Unit bottom_ = Unit(0)
Unit right_ = Unit(0)
Detailed Description
template<class Pt, class Unit = TCompute<Pt>>
class libnest2d::RotatedBox< Pt, Unit >
Constructor & Destructor Documentation
RotatedBox() [1/2]
template<class Pt , class Unit = TCompute<Pt>> libnest2d::RotatedBox< Pt, Unit >::RotatedBox () default
RotatedBox() [2/2]
template<class Pt , class Unit = TCompute<Pt>> libnest2d::RotatedBox< Pt, Unit >::RotatedBox (const Pt & axis, Unit b, Unit r) inline
                                              :
        axis_(axis), bottom_(b), right_(r) {}
Member Function Documentation
angleToX()
template<class Pt , class Unit = TCompute<Pt>> Radians libnest2d::RotatedBox< Pt, Unit >::angleToX () const inline
{
        double ret = std::atan2(getY(axis_), getX(axis_));
        auto s = std::signbit(ret);
        if(s) ret += Pi_2;
        return -ret;
    }
References libnest2d::RotatedBox< Pt, Unit >::axis_, libnest2d::getX(), libnest2d::getY(), and libnest2d::Pi_2.
Referenced by libnest2d::fitIntoBoxRotation().
area()
template<class Pt , class Unit = TCompute<Pt>> long double libnest2d::RotatedBox< Pt, Unit >::area () const inline
{
        long double asq = pl::magnsq<Pt, long double>(axis_);
        return cast<long double>(bottom_) * cast<long double>(right_) / asq;
    }
References libnest2d::RotatedBox< Pt, Unit >::axis_, libnest2d::RotatedBox< Pt, Unit >::bottom_, and libnest2d::RotatedBox< Pt, Unit >::right_.
axis()
template<class Pt , class Unit = TCompute<Pt>> const Pt & libnest2d::RotatedBox< Pt, Unit >::axis () const inline
{ return axis_; }
References libnest2d::RotatedBox< Pt, Unit >::axis_.
Referenced by Slic3r::MinAreaBoundigBox::MinAreaBoundigBox(), Slic3r::MinAreaBoundigBox::MinAreaBoundigBox(), Slic3r::MinAreaBoundigBox::MinAreaBoundigBox(), and libnest2d::rectarea().
bottom_extent()
template<class Pt , class Unit = TCompute<Pt>> Unit libnest2d::RotatedBox< Pt, Unit >::bottom_extent () const inline
{ return bottom_; }
References libnest2d::RotatedBox< Pt, Unit >::bottom_.
Referenced by Slic3r::MinAreaBoundigBox::MinAreaBoundigBox(), Slic3r::MinAreaBoundigBox::MinAreaBoundigBox(), Slic3r::MinAreaBoundigBox::MinAreaBoundigBox(), and libnest2d::rectarea().
height()
template<class Pt , class Unit = TCompute<Pt>> long double libnest2d::RotatedBox< Pt, Unit >::height () const inline
{
        return abs(right_) / std::sqrt(pl::magnsq<Pt, long double>(axis_));
    }
References libnest2d::RotatedBox< Pt, Unit >::axis_, and libnest2d::RotatedBox< Pt, Unit >::right_.
right_extent()
template<class Pt , class Unit = TCompute<Pt>> Unit libnest2d::RotatedBox< Pt, Unit >::right_extent () const inline
{ return right_;  }
References libnest2d::RotatedBox< Pt, Unit >::right_.
Referenced by Slic3r::MinAreaBoundigBox::MinAreaBoundigBox(), Slic3r::MinAreaBoundigBox::MinAreaBoundigBox(), Slic3r::MinAreaBoundigBox::MinAreaBoundigBox(), and libnest2d::rectarea().
width()
template<class Pt , class Unit = TCompute<Pt>> long double libnest2d::RotatedBox< Pt, Unit >::width () const inline
{
        return abs(bottom_) / std::sqrt(pl::magnsq<Pt, long double>(axis_));
    }
References libnest2d::RotatedBox< Pt, Unit >::axis_, and libnest2d::RotatedBox< Pt, Unit >::bottom_.
Member Data Documentation
axis_
template<class Pt , class Unit = TCompute<Pt>> Pt libnest2d::RotatedBox< Pt, Unit >::axis_ private
Referenced by libnest2d::RotatedBox< Pt, Unit >::angleToX(), libnest2d::RotatedBox< Pt, Unit >::area(), libnest2d::RotatedBox< Pt, Unit >::axis(), libnest2d::RotatedBox< Pt, Unit >::height(), and libnest2d::RotatedBox< Pt, Unit >::width().
bottom_
template<class Pt , class Unit = TCompute<Pt>> Unit libnest2d::RotatedBox< Pt, Unit >::bottom_ = Unit(0) private
Referenced by libnest2d::RotatedBox< Pt, Unit >::area(), libnest2d::RotatedBox< Pt, Unit >::bottom_extent(), and libnest2d::RotatedBox< Pt, Unit >::width().
right_
template<class Pt , class Unit = TCompute<Pt>> Unit libnest2d::RotatedBox< Pt, Unit >::right_ = Unit(0) private
Referenced by libnest2d::RotatedBox< Pt, Unit >::area(), libnest2d::RotatedBox< Pt, Unit >::height(), and libnest2d::RotatedBox< Pt, Unit >::right_extent().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/utils/rotcalipers.hpp