Prusa Slicer: ImPool< T > Struct Template Reference
ImPool< T > Struct Template Reference
#include <src/imgui/imgui_internal.h>
Public Member Functions
ImPool ()
~ImPool ()
T * GetByKey (ImGuiID key)
T * GetByIndex (ImPoolIdx n)
ImPoolIdx GetIndex (const T *p) const
T * GetOrAddByKey (ImGuiID key)
bool Contains (const T *p) const
void Clear ()
T * Add ()
void Remove (ImGuiID key, const T *p)
void Remove (ImGuiID key, ImPoolIdx idx)
void Reserve (int capacity)
int GetSize () const
Public Attributes
ImVector< T > Buf
ImGuiStorage Map
ImPoolIdx FreeIdx
Detailed Description
template<typename T>
struct ImPool< T >
Constructor & Destructor Documentation
ImPool()
template<typename T > ImPool< T >::ImPool () inline
{ FreeIdx = 0; }
~ImPool()
template<typename T > ImPool< T >::~ImPool () inline
{ Clear(); }
Member Function Documentation
Add()
template<typename T > T * ImPool< T >::Add () inline
{ int idx = FreeIdx; if (idx == Buf.Size) { Buf.resize(Buf.Size + 1); FreeIdx++; } else { FreeIdx = *(int*)&Buf[idx]; } IM_PLACEMENT_NEW(&Buf[idx]) T(); return &Buf[idx]; }
References IM_PLACEMENT_NEW, ImVector< T >::resize(), and ImVector< T >::Size.
Clear()
template<typename T > void ImPool< T >::Clear () inline
{ for (int n = 0; n < Map.Data.Size; n++) { int idx = Map.Data[n].val_i; if (idx != -1) Buf[idx].~T(); } Map.Clear(); Buf.clear(); FreeIdx = 0; }
References ImVector< T >::clear(), ImGuiStorage::Clear(), and ImGuiStorage::Data.
Referenced by ImGui::Shutdown().
Contains()
template<typename T > bool ImPool< T >::Contains (const T * p) const inline
{ return (p >= Buf.Data && p < Buf.Data + Buf.Size); }
References ImVector< T >::Data, and ImVector< T >::Size.
Referenced by GetTabBarRefFromTabBar().
GetByIndex()
template<typename T > T * ImPool< T >::GetByIndex (ImPoolIdx n) inline
{ return &Buf[n]; }
Referenced by ImGui::EndTable(), GetTabBarFromTabBarRef(), ImGui::NewFrame(), SetCurrentWindow(), ImGui::ShowMetricsWindow(), TableSettingsHandler_ApplyAll(), and TableSettingsHandler_ClearAll().
GetByKey()
template<typename T > T * ImPool< T >::GetByKey (ImGuiID key) inline
{ int idx = Map.GetInt(key, -1); return (idx != -1) ? &Buf[idx] : NULL; }
References ImGuiStorage::GetInt().
Referenced by ImGui::TableFindByID().
GetIndex()
template<typename T > ImPoolIdx ImPool< T >::GetIndex (const T * p) const inline
{ IM_ASSERT(p >= Buf.Data && p < Buf.Data + Buf.Size); return (ImPoolIdx)(p - Buf.Data); }
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
Referenced by ImGui::BeginTableEx(), ImGui::EndTable(), GetTabBarRefFromTabBar(), ImGui::TableGcCompactTransientBuffers(), and ImGui::TableRemove().
GetOrAddByKey()
template<typename T > T * ImPool< T >::GetOrAddByKey (ImGuiID key) inline
{ int* p_idx = Map.GetIntRef(key, -1); if (*p_idx != -1) return &Buf[*p_idx]; *p_idx = FreeIdx; return Add(); }
References ImGuiStorage::GetIntRef().
Referenced by ImGui::BeginTabBar(), and ImGui::BeginTableEx().
GetSize()
template<typename T > int ImPool< T >::GetSize () const inline
{ return Buf.Size; }
References ImVector< T >::Size.
Referenced by ImGui::ShowMetricsWindow(), TableSettingsHandler_ApplyAll(), and TableSettingsHandler_ClearAll().
Remove() [1/2]
template<typename T > void ImPool< T >::Remove (ImGuiID key, const T * p) inline
{ Remove(key, GetIndex(p)); }
References ImPool< T >::Remove().
Referenced by ImPool< T >::Remove(), and ImGui::TableRemove().
Remove() [2/2]
template<typename T > void ImPool< T >::Remove (ImGuiID key, ImPoolIdx idx) inline
{ Buf[idx].~T(); *(int*)&Buf[idx] = FreeIdx; FreeIdx = idx; Map.SetInt(key, -1); }
References ImGuiStorage::SetInt().
Reserve()
template<typename T > void ImPool< T >::Reserve (int capacity) inline
{ Buf.reserve(capacity); Map.Data.reserve(capacity); }
References ImGuiStorage::Data, and ImVector< T >::reserve().
Member Data Documentation
Buf
template<typename T > ImVector<T> ImPool< T >::Buf
FreeIdx
template<typename T > ImPoolIdx ImPool< T >::FreeIdx
Map
template<typename T > ImGuiStorage ImPool< T >::Map
The documentation for this struct was generated from the following file:
src/imgui/imgui_internal.h