Prusa Slicer: Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > > Struct Template Reference
Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > > Struct Template Reference
#include <src/eigen/Eigen/src/Core/CoreEvaluators.h>
Public Types
enum { CoeffReadCost = internal::functor_traits<NullaryOp>::Cost , Flags , Alignment = AlignedMax }
typedef CwiseNullaryOp< NullaryOp, PlainObjectType > XprType
typedef internal::remove_all< PlainObjectType >::type PlainObjectTypeCleaned
typedef XprType::CoeffReturnType CoeffReturnType
enum
typedef traits< CwiseNullaryOp< NullaryOp, PlainObjectType > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC evaluator (const XprType &n)
template<typename IndexType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (IndexType row, IndexType col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (IndexType index) const
template<int LoadMode, typename PacketType , typename IndexType >
EIGEN_STRONG_INLINE PacketType packet (IndexType row, IndexType col) const
template<int LoadMode, typename PacketType , typename IndexType >
EIGEN_STRONG_INLINE PacketType packet (IndexType index) const
Protected Attributes
const NullaryOp m_functor
const internal::nullary_wrapper< CoeffReturnType, NullaryOp > m_wrapper
Detailed Description
template<typename NullaryOp, typename PlainObjectType>
struct Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >
Member Typedef Documentation
CoeffReturnType
template<typename NullaryOp , typename PlainObjectType > typedef XprType::CoeffReturnType Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::CoeffReturnType
ExpressionTraits
typedef traits<CwiseNullaryOp< NullaryOp, PlainObjectType > > Eigen::internal::evaluator_base< CwiseNullaryOp< NullaryOp, PlainObjectType > >::ExpressionTraits inherited
PlainObjectTypeCleaned
template<typename NullaryOp , typename PlainObjectType > typedef internal::remove_all<PlainObjectType>::type Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::PlainObjectTypeCleaned
XprType
template<typename NullaryOp , typename PlainObjectType > typedef CwiseNullaryOp<NullaryOp,PlainObjectType> Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::XprType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    Alignment = 0
  };
anonymous enum
template<typename NullaryOp , typename PlainObjectType > anonymous enum
Enumerator
CoeffReadCost
Flags
Alignment
       {
    CoeffReadCost = internal::functor_traits<NullaryOp>::Cost,
    Flags = (evaluator<PlainObjectTypeCleaned>::Flags
          &  (  HereditaryBits
              | (functor_has_linear_access<NullaryOp>::ret  ? LinearAccessBit : 0)
              | (functor_traits<NullaryOp>::PacketAccess    ? PacketAccessBit : 0)))
          | (functor_traits<NullaryOp>::IsRepeatable ? 0 : EvalBeforeNestingBit),
    Alignment = AlignedMax
  };
Constructor & Destructor Documentation
evaluator()
template<typename NullaryOp , typename PlainObjectType > EIGEN_DEVICE_FUNC Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::evaluator (const XprType & n) inline explicit
    : m_functor(n.functor()), m_wrapper()
  {
    EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
  }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename NullaryOp , typename PlainObjectType > template<typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::coeff (IndexType index) const inline
  {
    return m_wrapper(m_functor,index);
  }
coeff() [2/2]
template<typename NullaryOp , typename PlainObjectType > template<typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::coeff (IndexType row, IndexType col) const inline
  {
    return m_wrapper(m_functor, row, col);
  }
References col(), and row().
packet() [1/2]
template<typename NullaryOp , typename PlainObjectType > template<int LoadMode, typename PacketType , typename IndexType > EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::packet (IndexType index) const inline
  {
    return m_wrapper.template packetOp<PacketType>(m_functor, index);
  }
packet() [2/2]
template<typename NullaryOp , typename PlainObjectType > template<int LoadMode, typename PacketType , typename IndexType > EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::packet (IndexType row, IndexType col) const inline
  {
    return m_wrapper.template packetOp<PacketType>(m_functor, row, col);
  }
References col(), and row().
Member Data Documentation
m_functor
template<typename NullaryOp , typename PlainObjectType > const NullaryOp Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::m_functor protected
m_wrapper
template<typename NullaryOp , typename PlainObjectType > const internal::nullary_wrapper<CoeffReturnType,NullaryOp> Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::m_wrapper protected
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/CoreEvaluators.h