Prusa Slicer: Slic3r::ObjectID Class Reference
Slic3r::ObjectID Class Reference
#include <src/libslic3r/ObjectID.hpp>
Public Member Functions
ObjectID (size_t id)
ObjectID ()
bool operator== (const ObjectID &rhs) const
bool operator!= (const ObjectID &rhs) const
bool operator< (const ObjectID &rhs) const
bool operator> (const ObjectID &rhs) const
bool operator<= (const ObjectID &rhs) const
bool operator>= (const ObjectID &rhs) const
bool valid () const
bool invalid () const
Public Attributes
size_t id
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
Constructor & Destructor Documentation
ObjectID() [1/2]
Slic3r::ObjectID::ObjectID (size_t id) inline
: id(id) {}
ObjectID() [2/2]
Slic3r::ObjectID::ObjectID () inline
: id(0) {}
Member Function Documentation
invalid()
bool Slic3r::ObjectID::invalid () const inline
{ return id == 0; }
Referenced by Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::ModelMaterial::serialize(), and Slic3r::GUI::update_object_cut_id().
operator!=()
bool Slic3r::ObjectID::operator!= (const ObjectID & rhs) const inline
{ return this->id != rhs.id; }
References id.
operator<()
bool Slic3r::ObjectID::operator< (const ObjectID & rhs) const inline
{ return this->id <  rhs.id; }
References id.
operator<=()
bool Slic3r::ObjectID::operator<= (const ObjectID & rhs) const inline
{ return this->id <= rhs.id; }
References id.
operator==()
bool Slic3r::ObjectID::operator== (const ObjectID & rhs) const inline
{ return this->id == rhs.id; }
References id.
operator>()
bool Slic3r::ObjectID::operator> (const ObjectID & rhs) const inline
{ return this->id >  rhs.id; }
References id.
operator>=()
bool Slic3r::ObjectID::operator>= (const ObjectID & rhs) const inline
{ return this->id >= rhs.id; }
References id.
serialize()
template<class Archive > void Slic3r::ObjectID::serialize (Archive & ar) inline private
{ ar(id); }
valid()
bool Slic3r::ObjectID::valid () const inline
{ return id != 0; }
Referenced by Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::check(), Slic3r::ModelObject::convert_units(), Slic3r::ModelObject::is_cut(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::PrintBaseWithState< PrintStepEnumType, COUNT >::set_task_impl(), and Slic3r::ModelObject::split().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
id
size_t Slic3r::ObjectID::id
Referenced by Slic3r::ModelObject::ModelObject(), Slic3r::GUI::GLCanvas3D::_set_warning_notification(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), anonymous_namespace{RaycastManager.cpp}::create_key(), Slic3r::GUI::Emboss::create_volume_sources(), Slic3r::inner_brim_area(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::ObjectList::merge(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::Plater::priv::on_slicing_update(), operator!=(), operator<(), operator<=(), Slic3r::ModelObject::operator=(), operator==(), operator>(), operator>=(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLGizmoEmboss::reset_volume(), Slic3r::GUI::Plater::reslice_until_step_inner(), Slic3r::Print::sequential_print_horizontal_clearance_valid(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), and Slic3r::top_level_outer_brim_area().
The documentation for this class was generated from the following file:
src/libslic3r/ObjectID.hpp