Prusa Slicer: Slic3r::GCodeProcessor::UsedFilaments Struct Reference
Slic3r::GCodeProcessor::UsedFilaments Struct Reference
Public Member Functions
void reset ()
void increase_caches (double extruded_volume, unsigned char extruder_id, double parking_volume, double extra_loading_volume)
void process_color_change_cache ()
void process_extruder_cache (unsigned char extruder_id)
void process_role_cache (const GCodeProcessor *processor)
void process_caches (const GCodeProcessor *processor)
Public Attributes
double color_change_cache
std::vector< double > volumes_per_color_change
double tool_change_cache
std::map< size_t, double > volumes_per_extruder
double role_cache
std::map< GCodeExtrusionRole, std::pair< double, double > > filaments_per_role
Private Attributes
std::vector< double > extruder_retracted_volume
bool recent_toolchange = false
Detailed Description
Member Function Documentation
increase_caches()
void Slic3r::GCodeProcessor::UsedFilaments::increase_caches (double extruded_volume, unsigned char extruder_id, double parking_volume, double extra_loading_volume)
{
    if (extruder_id >= extruder_retracted_volume.size())
        extruder_retracted_volume.resize(extruder_id + 1, parking_volume);
    if (recent_toolchange) {
        extruded_volume -= extra_loading_volume;
        recent_toolchange = false;
    }
    extruder_retracted_volume[extruder_id] -= extruded_volume;
    if (extruder_retracted_volume[extruder_id] < 0.) {
        extruded_volume = - extruder_retracted_volume[extruder_id];
        extruder_retracted_volume[extruder_id] = 0.;
        color_change_cache += extruded_volume;
        tool_change_cache += extruded_volume;
        role_cache += extruded_volume;
    }
}
Referenced by Slic3r::GCodeProcessor::process_G1().
process_caches()
void Slic3r::GCodeProcessor::UsedFilaments::process_caches (const GCodeProcessor * processor)
{
    process_color_change_cache();
    process_extruder_cache(processor->m_extruder_id);
    process_role_cache(processor);
}
References Slic3r::GCodeProcessor::m_extruder_id.
Referenced by Slic3r::GCodeProcessor::finalize().
process_color_change_cache()
void Slic3r::GCodeProcessor::UsedFilaments::process_color_change_cache ()
{
    if (color_change_cache != 0.0f) {
        volumes_per_color_change.push_back(color_change_cache);
        color_change_cache = 0.0f;
    }
}
Referenced by Slic3r::GCodeProcessor::process_filaments().
process_extruder_cache()
void Slic3r::GCodeProcessor::UsedFilaments::process_extruder_cache (unsigned char extruder_id)
 {
    if (tool_change_cache != 0.0) {
        volumes_per_extruder[extruder_id] += tool_change_cache;
         tool_change_cache = 0.0;
     }
    recent_toolchange = true;
}
Referenced by Slic3r::GCodeProcessor::process_filaments().
process_role_cache()
void Slic3r::GCodeProcessor::UsedFilaments::process_role_cache (const GCodeProcessor * processor)
{
    if (role_cache != 0.0) {
        std::pair<double, double> filament = { 0.0f, 0.0f };
        const double s = PI * sqr(0.5 * processor->m_result.filament_diameters[processor->m_extruder_id]);
        filament.first = role_cache / s * 0.001;
        filament.second = role_cache * processor->m_result.filament_densities[processor->m_extruder_id] * 0.001;
        GCodeExtrusionRole active_role = processor->m_extrusion_role;
        if (filaments_per_role.find(active_role) != filaments_per_role.end()) {
            filaments_per_role[active_role].first += filament.first;
            filaments_per_role[active_role].second += filament.second;
        }
        else
            filaments_per_role[active_role] = filament;
        role_cache = 0.0;
    }
}
References Slic3r::GCodeProcessorResult::filament_densities, Slic3r::GCodeProcessorResult::filament_diameters, Slic3r::GCodeProcessor::m_extruder_id, Slic3r::GCodeProcessor::m_extrusion_role, Slic3r::GCodeProcessor::m_result, PI, and Slic3r::sqr().
Referenced by Slic3r::GCodeProcessor::set_extrusion_role().
reset()
void Slic3r::GCodeProcessor::UsedFilaments::reset ()
{
    color_change_cache = 0.0;
    volumes_per_color_change = std::vector<double>();
    tool_change_cache = 0.0;
    volumes_per_extruder.clear();
    role_cache = 0.0;
    filaments_per_role.clear();
    extruder_retracted_volume.clear();
}
Referenced by Slic3r::GCodeProcessor::reset().
Member Data Documentation
color_change_cache
double Slic3r::GCodeProcessor::UsedFilaments::color_change_cache
extruder_retracted_volume
std::vector<double> Slic3r::GCodeProcessor::UsedFilaments::extruder_retracted_volume private
filaments_per_role
std::map<GCodeExtrusionRole, std::pair<double, double> > Slic3r::GCodeProcessor::UsedFilaments::filaments_per_role
Referenced by Slic3r::GCodeProcessor::update_estimated_times_stats().
recent_toolchange
bool Slic3r::GCodeProcessor::UsedFilaments::recent_toolchange = false private
role_cache
double Slic3r::GCodeProcessor::UsedFilaments::role_cache
tool_change_cache
double Slic3r::GCodeProcessor::UsedFilaments::tool_change_cache
volumes_per_color_change
std::vector<double> Slic3r::GCodeProcessor::UsedFilaments::volumes_per_color_change
Referenced by Slic3r::GCodeProcessor::update_estimated_times_stats().
volumes_per_extruder
std::map<size_t, double> Slic3r::GCodeProcessor::UsedFilaments::volumes_per_extruder
Referenced by Slic3r::GCodeProcessor::update_estimated_times_stats().
The documentation for this struct was generated from the following files:
src/libslic3r/GCode/GCodeProcessor.hpp
src/libslic3r/GCode/GCodeProcessor.cpp