Prusa Slicer: Slic3r::FillAdaptive::Intersection Struct Reference
Slic3r::FillAdaptive::Intersection Struct Reference
Public Member Functions
bool fresh () const throw ()
Intersection (const Line &closest_line, const Line &intersect_line, Polyline *intersect_pl, const Point &intersect_point, bool front)
std::optional< Line > other_hook () const
bool other_hook_intersects (const Line &l, Point &pt)
bool other_hook_intersects (const Line &l)
Vec2d intersect_line_dir () const throw ()
Public Attributes
const Line * closest_line
const Line * intersect_line
Polyline * intersect_pl
Point intersect_point
bool front
bool left
bool used = false
Detailed Description
Constructor & Destructor Documentation
Intersection()
Slic3r::FillAdaptive::Intersection::Intersection (const Line & closest_line, const Line & intersect_line, Polyline * intersect_pl, const Point & intersect_point, bool front) inline
                                                                                                                                         :
        closest_line(&closest_line), intersect_line(&intersect_line), intersect_pl(intersect_pl), intersect_point(intersect_point), front(front)
    {
        // Calculate side of this intersection line of the closest line.
        Vec2d v1((this->closest_line->b - this->closest_line->a).cast<double>());
        Vec2d v2(this->intersect_line_dir());
#ifndef NDEBUG
        {
            Vec2d v1n = v1.normalized();
            Vec2d v2n = v2.normalized();
            double c = cross2(v1n, v2n);
            assert(std::abs(c) > sin(M_PI / 12.));
        }
#endif // NDEBUG
        this->left = cross2(v1, v2) > 0.;
    }
References Slic3r::Line::b, Slic3r::cross2(), intersect_line_dir(), M_PI, and sin().
Member Function Documentation
fresh()
bool Slic3r::FillAdaptive::Intersection::fresh () const throw () inline
{ return ! used && ! intersect_pl->empty(); }
References Slic3r::MultiPoint::empty(), intersect_pl, and used.
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks().
intersect_line_dir()
Vec2d Slic3r::FillAdaptive::Intersection::intersect_line_dir () const throw () inline
{
        return (this->intersect_point == intersect_line->a ? intersect_line->b - intersect_line->a : intersect_line->a - intersect_line->b).cast<double>();
    }
References Slic3r::Line::a, Slic3r::Line::b, and intersect_line.
Referenced by Intersection().
other_hook()
std::optional< Line > Slic3r::FillAdaptive::Intersection::other_hook () const inline
{
        std::optional<Line> out;
        const Points &pts = intersect_pl->points;
        if (pts.size() >= 3)
            out = this->front ? Line(pts[1], pts[2]) : Line(pts[pts.size() - 2], pts[pts.size() - 3]);
        return out;
    }
References intersect_pl, and Slic3r::MultiPoint::points.
Referenced by other_hook_intersects().
other_hook_intersects() [1/2]
bool Slic3r::FillAdaptive::Intersection::other_hook_intersects (const Line & l) inline
{ Point pt; return this->other_hook_intersects(l, pt); }
References other_hook_intersects().
Referenced by other_hook_intersects().
other_hook_intersects() [2/2]
bool Slic3r::FillAdaptive::Intersection::other_hook_intersects (const Line & l, Point & pt) inline
{
        std::optional<Line> h = other_hook();
        return h && h->intersection(l, &pt);
    }
References other_hook().
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks().
Member Data Documentation
closest_line
const Line* Slic3r::FillAdaptive::Intersection::closest_line
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks().
front
bool Slic3r::FillAdaptive::Intersection::front
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks().
intersect_line
const Line* Slic3r::FillAdaptive::Intersection::intersect_line
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks(), and intersect_line_dir().
intersect_pl
Polyline* Slic3r::FillAdaptive::Intersection::intersect_pl
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks(), fresh(), and other_hook().
intersect_point
Point Slic3r::FillAdaptive::Intersection::intersect_point
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks().
left
bool Slic3r::FillAdaptive::Intersection::left
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks().
used
bool Slic3r::FillAdaptive::Intersection::used = false
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks(), and fresh().
The documentation for this struct was generated from the following file:
src/libslic3r/Fill/FillAdaptive.cpp