Prusa Slicer: Eigen::internal::conj_helper< Packet4cf, Packet4cf, false, true > Struct Reference
Eigen::internal::conj_helper< Packet4cf, Packet4cf, false, true > Struct Reference
#include <src/eigen/Eigen/src/Core/arch/AVX/Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet4cf pmadd (const Packet4cf &x, const Packet4cf &y, const Packet4cf &c) const
EIGEN_STRONG_INLINE Packet4cf pmul (const Packet4cf &a, const Packet4cf &b) const
Detailed Description
Member Function Documentation
pmadd()
EIGEN_STRONG_INLINE Packet4cf Eigen::internal::conj_helper< Packet4cf, Packet4cf, false, true >::pmadd (const Packet4cf & x, const Packet4cf & y, const Packet4cf & c) const inline
  { return padd(pmul(x,y),c); }
References Eigen::internal::padd(), Eigen::internal::conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs >::pmul(), and Eigen::internal::y.
pmul()
EIGEN_STRONG_INLINE Packet4cf Eigen::internal::conj_helper< Packet4cf, Packet4cf, false, true >::pmul (const Packet4cf & a, const Packet4cf & b) const inline
  {
    return internal::pmul(a, pconj(b));
  }
References Eigen::internal::pconj(), and Eigen::internal::pmul().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/arch/AVX/Complex.h