Prusa Slicer: Slic3r::ConfigOptionPoint3 Class Reference
Slic3r::ConfigOptionPoint3 Class Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionPoint3 ()
ConfigOptionPoint3 (const Vec3d &value)
ConfigOptionType type () const override
ConfigOption * clone () const override
ConfigOptionPoint3 & operator= (const ConfigOption *opt)
bool operator== (const ConfigOptionPoint3 &rhs) const throw ()
bool operator< (const ConfigOptionPoint3 &rhs) const throw ()
std::string serialize () const override
bool deserialize (const std::string &str, bool append=false) override
operator Vec3d () const
void set (const ConfigOption *rhs) override
bool operator== (const ConfigOption &rhs) const override
bool operator== (const Vec3d &rhs) const throw ()
bool operator!= (const Vec3d &rhs) const throw ()
bool operator!= (const ConfigOption &rhs) const
bool operator< (const Vec3d &rhs) const throw ()
size_t hash () const override throw ()
virtual int getInt () const
virtual double getFloat () const
virtual bool getBool () const
virtual void setInt (int)
bool is_scalar () const
bool is_vector () const
virtual bool nullable () const
virtual bool is_nil () const
virtual bool overriden_by (const ConfigOption *rhs) const
virtual bool apply_override (const ConfigOption *rhs)
Static Public Member Functions
static ConfigOptionType static_type ()
Public Attributes
Vec3d value
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
Constructor & Destructor Documentation
ConfigOptionPoint3() [1/2]
Slic3r::ConfigOptionPoint3::ConfigOptionPoint3 () inline
: ConfigOptionSingle<Vec3d>(Vec3d(0,0,0)) {}
Referenced by clone().
ConfigOptionPoint3() [2/2]
Slic3r::ConfigOptionPoint3::ConfigOptionPoint3 (const Vec3d & value) inline explicit
: ConfigOptionSingle<Vec3d>(value) {}
Member Function Documentation
apply_override()
virtual bool Slic3r::ConfigOption::apply_override (const ConfigOption * rhs) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      if (*this == *rhs)
        return false;
      *this = *rhs;
      return true;
    }
Referenced by Slic3r::print_config_diffs().
clone()
ConfigOption * Slic3r::ConfigOptionPoint3::clone () const inline override virtual
Implements Slic3r::ConfigOption.
{ return new ConfigOptionPoint3(*this); }
References ConfigOptionPoint3().
deserialize()
bool Slic3r::ConfigOptionPoint3::deserialize (const std::string & str, bool append = false) inline override virtual
Implements Slic3r::ConfigOption.
    {
        UNUSED(append);
        char dummy;
        return sscanf(str.data(), " %lf , %lf , %lf %c", &this->value(0), &this->value(1), &this->value(2), &dummy) == 3 ||
               sscanf(str.data(), " %lf x %lf x %lf %c", &this->value(0), &this->value(1), &this->value(2), &dummy) == 3;
    }
References Slic3r::append(), and UNUSED.
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
virtual int Slic3r::ConfigOption::getInt () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::getInt on a non-int ConfigOption"); }
Referenced by Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
hash()
size_t Slic3r::ConfigOptionSingle< Vec3d >::hash () const throw () inline override virtual inherited
Implements Slic3r::ConfigOption.
{ return std::hash<T>{}(this->value); }
is_nil()
virtual bool Slic3r::ConfigOption::is_nil () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVectorBase, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::GCode::append_full_config(), Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_full_label(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::print_config_diffs(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::validate(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nullable()
virtual bool Slic3r::ConfigOption::nullable () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::ConfigBase::null_nullables(), Slic3r::ConfigOption::overriden_by(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::validate().
operator Vec3d()
Slic3r::ConfigOptionSingle< Vec3d >::operator Vec3d () const inline inherited
{ return this->value; }
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
bool Slic3r::ConfigOptionSingle< Vec3d >::operator!= (const Vec3d & rhs) const throw () inline inherited
{ return this->value != rhs; }
operator<() [1/2]
bool Slic3r::ConfigOptionPoint3::operator< (const ConfigOptionPoint3 & rhs) const throw () inline
        { return this->value.x() < rhs.value.x() || (this->value.x() == rhs.value.x() && (this->value.y() < rhs.value.y() || (this->value.y() == rhs.value.y() && this->value.z() < rhs.value.z()))); }
operator<() [2/2]
bool Slic3r::ConfigOptionSingle< Vec3d >::operator< (const Vec3d & rhs) const throw () inline inherited
{ return this->value < rhs; }
operator=()
ConfigOptionPoint3 & Slic3r::ConfigOptionPoint3::operator= (const ConfigOption * opt) inline
{ this->set(opt); return *this; }
References Slic3r::ConfigOptionSingle< Vec3d >::set().
operator==() [1/3]
bool Slic3r::ConfigOptionSingle< Vec3d >::operator== (const ConfigOption & rhs) const inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionSingle: Comparing incompatible types");
        assert(dynamic_cast<const ConfigOptionSingle<T>*>(&rhs));
        return this->value == static_cast<const ConfigOptionSingle<T>*>(&rhs)->value;
    }
operator==() [2/3]
bool Slic3r::ConfigOptionPoint3::operator== (const ConfigOptionPoint3 & rhs) const throw () inline
{ return this->value == rhs.value; }
operator==() [3/3]
bool Slic3r::ConfigOptionSingle< Vec3d >::operator== (const Vec3d & rhs) const throw () inline inherited
{ return this->value == rhs; }
overriden_by()
virtual bool Slic3r::ConfigOption::overriden_by (const ConfigOption * rhs) const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionVector< T >, Slic3r::ConfigOptionVector< double >, Slic3r::ConfigOptionVector< FloatOrPercent >, Slic3r::ConfigOptionVector< int >, Slic3r::ConfigOptionVector< std::string >, Slic3r::ConfigOptionVector< unsigned char >, and Slic3r::ConfigOptionVector< Vec2d >.
{
      assert(! this->nullable() && ! rhs->nullable());
      return *this != *rhs;
    }
References Slic3r::ConfigOption::nullable().
Referenced by Slic3r::print_config_diffs().
serialize() [1/2]
std::string Slic3r::ConfigOptionPoint3::serialize () const inline override virtual
Implements Slic3r::ConfigOption.
    {
        std::ostringstream ss;
        ss << this->value(0);
        ss << ",";
        ss << this->value(1);
        ss << ",";
        ss << this->value(2);
        return ss.str();
    }
References Slic3r::ConfigOptionSingle< Vec3d >::value.
serialize() [2/2]
template<class Archive > void Slic3r::ConfigOptionPoint3::serialize (Archive & ar) inline private
{ ar(cereal::base_class<ConfigOptionSingle<Vec3d>>(this)); }
set()
void Slic3r::ConfigOptionSingle< Vec3d >::set (const ConfigOption * rhs) inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionSingle: Assigning an incompatible type");
        assert(dynamic_cast<const ConfigOptionSingle<T>*>(rhs));
        this->value = static_cast<const ConfigOptionSingle<T>*>(rhs)->value;
    }
setInt()
virtual void Slic3r::ConfigOption::setInt (int) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::setInt on a non-int ConfigOption"); }
static_type()
static ConfigOptionType Slic3r::ConfigOptionPoint3::static_type () inline static
{ return coPoint3; }
References Slic3r::coPoint3.
Referenced by type().
type()
ConfigOptionType Slic3r::ConfigOptionPoint3::type () const inline override virtual
Implements Slic3r::ConfigOption.
{ return static_type(); }
References static_type().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
value
Vec3d Slic3r::ConfigOptionSingle< Vec3d >::value inherited
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp