Prusa Slicer: Slic3r::MeshToGridParams Class Reference
Slic3r::MeshToGridParams Class Reference
#include <src/libslic3r/OpenVDBUtils.hpp>
Public Member Functions
MeshToGridParams & trafo (const Transform3f &v)
MeshToGridParams & voxel_scale (float v)
MeshToGridParams & exterior_bandwidth (float v)
MeshToGridParams & interior_bandwidth (float v)
MeshToGridParams & statusfn (std::function< bool(int)> fn)
const Transform3f & trafo () const noexcept
float voxel_scale () const noexcept
float exterior_bandwidth () const noexcept
float interior_bandwidth () const noexcept
const std::function< bool(int)> & statusfn () const noexcept
Private Attributes
Transform3f m_tr = Transform3f::Identity()
float m_voxel_scale = 1.f
float m_exteriorBandWidth = 3.0f
float m_interiorBandWidth = 3.0f
std::function< bool(int)> m_statusfn
Detailed Description
Member Function Documentation
exterior_bandwidth() [1/2]
float Slic3r::MeshToGridParams::exterior_bandwidth () const inline noexcept
{ return m_exteriorBandWidth; }
exterior_bandwidth() [2/2]
MeshToGridParams & Slic3r::MeshToGridParams::exterior_bandwidth (float v) inline
{ m_exteriorBandWidth = v; return *this; }
Referenced by Slic3r::SLAPrint::Steps::generate_preview_vdb(), and Slic3r::mesh_to_grid().
interior_bandwidth() [1/2]
float Slic3r::MeshToGridParams::interior_bandwidth () const inline noexcept
{ return m_interiorBandWidth; }
interior_bandwidth() [2/2]
MeshToGridParams & Slic3r::MeshToGridParams::interior_bandwidth (float v) inline
{ m_interiorBandWidth = v; return *this; }
Referenced by Slic3r::SLAPrint::Steps::generate_preview_vdb(), and Slic3r::mesh_to_grid().
statusfn() [1/2]
const std::function< bool(int)> & Slic3r::MeshToGridParams::statusfn () const inline noexcept
{ return m_statusfn; }
statusfn() [2/2]
MeshToGridParams & Slic3r::MeshToGridParams::statusfn (std::function< bool(int)> fn) inline
{ m_statusfn = fn; return *this; }
Referenced by Slic3r::SLAPrint::Steps::generate_preview_vdb(), and Slic3r::mesh_to_grid().
trafo() [1/2]
const Transform3f & Slic3r::MeshToGridParams::trafo () const inline noexcept
{ return m_tr; }
trafo() [2/2]
MeshToGridParams & Slic3r::MeshToGridParams::trafo (const Transform3f & v) inline
{ m_tr = v; return *this; }
Referenced by Slic3r::csg::get_voxelgrid(), and Slic3r::mesh_to_grid().
voxel_scale() [1/2]
float Slic3r::MeshToGridParams::voxel_scale () const inline noexcept
{ return m_voxel_scale; }
voxel_scale() [2/2]
MeshToGridParams & Slic3r::MeshToGridParams::voxel_scale (float v) inline
{ m_voxel_scale = v; return *this; }
Referenced by Slic3r::SLAPrint::Steps::generate_preview_vdb(), and Slic3r::mesh_to_grid().
Member Data Documentation
m_exteriorBandWidth
float Slic3r::MeshToGridParams::m_exteriorBandWidth = 3.0f private
m_interiorBandWidth
float Slic3r::MeshToGridParams::m_interiorBandWidth = 3.0f private
m_statusfn
std::function<bool(int)> Slic3r::MeshToGridParams::m_statusfn private
m_tr
Transform3f Slic3r::MeshToGridParams::m_tr = Transform3f::Identity() private
m_voxel_scale
float Slic3r::MeshToGridParams::m_voxel_scale = 1.f private
The documentation for this class was generated from the following file:
src/libslic3r/OpenVDBUtils.hpp