Prusa Slicer: Slic3r::PrintHost Class Reference
Slic3r::PrintHost Class Reference abstract
#include <src/slic3r/Utils/PrintHost.hpp>
Public Types
typedef Http::ProgressFn ProgressFn
typedef std::function< void(wxString)> ErrorFn
typedef std::function< void(wxString, wxString)> InfoFn
Public Member Functions
virtual ~PrintHost ()
virtual const char * get_name () const =0
virtual bool test (wxString &curl_msg) const =0
virtual wxString get_test_ok_msg () const =0
virtual wxString get_test_failed_msg (wxString &msg) const =0
virtual bool upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const =0
virtual bool has_auto_discovery () const =0
virtual bool can_test () const =0
virtual PrintHostPostUploadActions get_post_upload_actions () const =0
virtual bool supports_multiple_printers () const
virtual std::string get_host () const =0
virtual bool get_groups (wxArrayString &) const
virtual bool get_printers (wxArrayString &) const
virtual bool get_storage (wxArrayString &, wxArrayString &) const
Static Public Member Functions
static PrintHost * get_print_host (DynamicPrintConfig *config)
Protected Member Functions
virtual wxString format_error (const std::string &body, const std::string &error, unsigned status) const
Detailed Description
Member Typedef Documentation
ErrorFn
typedef std::function<void(wxString)> Slic3r::PrintHost::ErrorFn
InfoFn
typedef std::function<void(wxString , wxString)> Slic3r::PrintHost::InfoFn
ProgressFn
typedef Http::ProgressFn Slic3r::PrintHost::ProgressFn
Constructor & Destructor Documentation
~PrintHost()
Slic3r::PrintHost::~PrintHost () virtual
{}
Member Function Documentation
can_test()
virtual bool Slic3r::PrintHost::can_test () const pure virtual
Implemented in Slic3r::AstroBox, Slic3r::Duet, Slic3r::FlashAir, Slic3r::MKS, Slic3r::Moonraker, Slic3r::OctoPrint, and Slic3r::Repetier.
format_error()
wxString Slic3r::PrintHost::format_error (const std::string & body, const std::string & error, unsigned status) const protected virtual
{
    if (status != 0) {
        auto wxbody = wxString::FromUTF8(body.data());
        return wxString::Format("HTTP %u: %s", status, wxbody);
    } else {
        return wxString::FromUTF8(error.data());
    }
}
References error.
Referenced by Slic3r::Duet::connect(), Slic3r::PrusaLink::post_inner(), Slic3r::PrusaLink::put_inner(), Slic3r::Duet::start_print(), Slic3r::AstroBox::test(), Slic3r::FlashAir::test(), Slic3r::Moonraker::test(), Slic3r::OctoPrint::test(), Slic3r::PrusaLink::test(), Slic3r::Repetier::test(), Slic3r::PrusaLink::test_with_method_check(), Slic3r::AstroBox::upload(), Slic3r::Duet::upload(), Slic3r::FlashAir::upload(), Slic3r::MKS::upload(), Slic3r::Moonraker::upload(), Slic3r::Repetier::upload(), and Slic3r::OctoPrint::upload_inner_with_host().
get_groups()
virtual bool Slic3r::PrintHost::get_groups (wxArrayString &) const inline virtual
Reimplemented in Slic3r::Repetier.
{ return false; }
get_host()
virtual std::string Slic3r::PrintHost::get_host () const pure virtual
Implemented in Slic3r::AstroBox, Slic3r::Duet, Slic3r::FlashAir, Slic3r::MKS, Slic3r::Moonraker, Slic3r::OctoPrint, and Slic3r::Repetier.
get_name()
virtual const char * Slic3r::PrintHost::get_name () const pure virtual
Implemented in Slic3r::AstroBox, Slic3r::Duet, Slic3r::FlashAir, Slic3r::MKS, Slic3r::Moonraker, Slic3r::OctoPrint, Slic3r::PrusaLink, Slic3r::PrusaConnect, Slic3r::SL1Host, and Slic3r::Repetier.
get_post_upload_actions()
virtual PrintHostPostUploadActions Slic3r::PrintHost::get_post_upload_actions () const pure virtual
Implemented in Slic3r::AstroBox, Slic3r::Duet, Slic3r::FlashAir, Slic3r::MKS, Slic3r::Moonraker, Slic3r::OctoPrint, Slic3r::PrusaLink, Slic3r::PrusaConnect, Slic3r::SL1Host, and Slic3r::Repetier.
get_print_host()
PrintHost * Slic3r::PrintHost::get_print_host (DynamicPrintConfig * config) static
{
    PrinterTechnology tech = ptFFF;
    {
        const auto opt = config->option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
        if (opt != nullptr) {
            tech = opt->value;
        }
    }
    if (tech == ptFFF) {
        const auto opt = config->option<ConfigOptionEnum<PrintHostType>>("host_type");
        const auto host_type = opt != nullptr ? opt->value : htOctoPrint;
        switch (host_type) {
            case htOctoPrint: return new OctoPrint(config);
            case htDuet:      return new Duet(config);
            case htFlashAir:  return new FlashAir(config);
            case htAstroBox:  return new AstroBox(config);
            case htRepetier:  return new Repetier(config);
            case htPrusaLink: return new PrusaLink(config);
            case htPrusaConnect: return new PrusaConnect(config);
            case htMKS:       return new MKS(config);
            case htMoonraker: return new Moonraker(config);
            default:          return nullptr;
        }
    } else {
        return new SL1Host(config);
    }
}
References Slic3r::htAstroBox, Slic3r::htDuet, Slic3r::htFlashAir, Slic3r::htMKS, Slic3r::htMoonraker, Slic3r::htOctoPrint, Slic3r::htPrusaConnect, Slic3r::htPrusaLink, Slic3r::htRepetier, Slic3r::ConfigBase::option(), Slic3r::ptFFF, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::PhysicalPrinterDialog::update_printers(), and Slic3r::GUI::PhysicalPrinterDialog::update_printhost_buttons().
get_printers()
virtual bool Slic3r::PrintHost::get_printers (wxArrayString &) const inline virtual
Reimplemented in Slic3r::Repetier.
{ return false; }
get_storage()
virtual bool Slic3r::PrintHost::get_storage (wxArrayString & , wxArrayString &) const inline virtual
Reimplemented in Slic3r::PrusaLink, and Slic3r::PrusaConnect.
{ return false; }
get_test_failed_msg()
virtual wxString Slic3r::PrintHost::get_test_failed_msg (wxString & msg) const pure virtual
Implemented in Slic3r::AstroBox, Slic3r::Duet, Slic3r::FlashAir, Slic3r::MKS, Slic3r::Moonraker, Slic3r::OctoPrint, Slic3r::PrusaLink, Slic3r::PrusaConnect, Slic3r::SL1Host, and Slic3r::Repetier.
get_test_ok_msg()
virtual wxString Slic3r::PrintHost::get_test_ok_msg () const pure virtual
Implemented in Slic3r::AstroBox, Slic3r::Duet, Slic3r::FlashAir, Slic3r::MKS, Slic3r::Moonraker, Slic3r::OctoPrint, Slic3r::PrusaLink, Slic3r::PrusaConnect, Slic3r::SL1Host, and Slic3r::Repetier.
has_auto_discovery()
virtual bool Slic3r::PrintHost::has_auto_discovery () const pure virtual
Implemented in Slic3r::AstroBox, Slic3r::Duet, Slic3r::FlashAir, Slic3r::MKS, Slic3r::Moonraker, Slic3r::OctoPrint, and Slic3r::Repetier.
supports_multiple_printers()
virtual bool Slic3r::PrintHost::supports_multiple_printers () const inline virtual
Reimplemented in Slic3r::Repetier.
{ return false; }
test()
virtual bool Slic3r::PrintHost::test (wxString & curl_msg) const pure virtual
Implemented in Slic3r::AstroBox, Slic3r::Duet, Slic3r::FlashAir, Slic3r::MKS, Slic3r::Moonraker, Slic3r::OctoPrint, Slic3r::PrusaLink, and Slic3r::Repetier.
upload()
virtual bool Slic3r::PrintHost::upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const pure virtual
Implemented in Slic3r::AstroBox, Slic3r::Duet, Slic3r::FlashAir, Slic3r::MKS, Slic3r::Moonraker, Slic3r::OctoPrint, and Slic3r::Repetier.
The documentation for this class was generated from the following files:
src/slic3r/Utils/PrintHost.hpp
src/slic3r/Utils/PrintHost.cpp