Prusa Slicer: igl::geodesic::SurfacePoint Class Reference
igl::geodesic::SurfacePoint Class Reference
Public Member Functions
SurfacePoint ()
SurfacePoint (vertex_pointer v)
SurfacePoint (face_pointer f)
SurfacePoint (edge_pointer e, double a=0.5)
SurfacePoint (base_pointer g, double x, double y, double z, PointType t=UNDEFINED_POINT)
void initialize (SurfacePoint const &p)
~SurfacePoint ()
PointType type ()
base_pointer & base_element ()
double * xyz ()
double & x ()
double & y ()
double & z ()
void set (double new_x, double new_y, double new_z)
void set (double *data)
double distance (double *v)
double distance (Point3D *v)
void add (Point3D *v)
void multiply (double v)
Protected Attributes
base_pointer m_p
Private Attributes
double m_coordinates [3]
Detailed Description
Constructor & Destructor Documentation
SurfacePoint() [1/5]
igl::geodesic::SurfacePoint::SurfacePoint () inline
                :
    m_p(NULL)
  {};
SurfacePoint() [2/5]
igl::geodesic::SurfacePoint::SurfacePoint (vertex_pointer v) inline
                                :   //set the surface point in the vertex
    SurfacePoint::Point3D(v),
    m_p(v)
  {};
SurfacePoint() [3/5]
igl::geodesic::SurfacePoint::SurfacePoint (face_pointer f) inline
                              :   //set the surface point in the center of the face
    m_p(f)
  {
    set(0,0,0);
    add(f->adjacent_vertices()[0]);
    add(f->adjacent_vertices()[1]);
    add(f->adjacent_vertices()[2]);
    multiply(1./3.);
  };
References igl::geodesic::Point3D::add(), igl::geodesic::MeshElementBase::adjacent_vertices(), igl::geodesic::Point3D::multiply(), and igl::geodesic::Point3D::set().
SurfacePoint() [4/5]
igl::geodesic::SurfacePoint::SurfacePoint (edge_pointer e, double a = 0.5) inline
                        :
    m_p(e)
  {
    double b = 1 - a;
    vertex_pointer v0 = e->adjacent_vertices()[0];
    vertex_pointer v1 = e->adjacent_vertices()[1];
    x() = b*v0->x() + a*v1->x();
    y() = b*v0->y() + a*v1->y();
    z() = b*v0->z() + a*v1->z();
  };
References igl::geodesic::MeshElementBase::adjacent_vertices(), igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
SurfacePoint() [5/5]
igl::geodesic::SurfacePoint::SurfacePoint (base_pointer g, double x, double y, double z, PointType t = UNDEFINED_POINT) inline
                                       :
    m_p(g)
  {
    set(x,y,z);
  };
References igl::geodesic::Point3D::set(), igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
~SurfacePoint()
igl::geodesic::SurfacePoint::~SurfacePoint () inline
{};
Member Function Documentation
add()
void igl::geodesic::Point3D::add (Point3D * v) inline inherited
  {
    x() += v->x();
    y() += v->y();
    z() += v->z();
  };
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
Referenced by SurfacePoint().
base_element()
base_pointer & igl::geodesic::SurfacePoint::base_element () inline
{return m_p;};
References m_p.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::fill_surface_point_double(), igl::geodesic::fill_surface_point_structure(), igl::geodesic::Interval::initialize(), igl::geodesic::GeodesicAlgorithmExact::initialize_propagation_data(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), igl::geodesic::SortedSources::sources(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
distance() [1/2]
double igl::geodesic::Point3D::distance (double * v) inline inherited
  {
    double dx = m_coordinates[0] - v[0];
    double dy = m_coordinates[1] - v[1];
    double dz = m_coordinates[2] - v[2];
    return sqrt(dx*dx + dy*dy + dz*dz);
  };
References igl::geodesic::Point3D::m_coordinates, and sqrt().
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Point3D::distance(), igl::geodesic::Edge::local_coordinates(), igl::geodesic::GeodesicAlgorithmBase::set_stop_conditions(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
distance() [2/2]
double igl::geodesic::Point3D::distance (Point3D * v) inline inherited
  {
    return distance(v->xyz());
  };
References igl::geodesic::Point3D::distance(), and igl::geodesic::Point3D::xyz().
initialize()
void igl::geodesic::SurfacePoint::initialize (SurfacePoint const & p) inline
  {
    *this = p;
  }
Referenced by igl::geodesic::SurfacePointWithIndex::initialize().
multiply()
void igl::geodesic::Point3D::multiply (double v) inline inherited
  {
    x() *= v;
    y() *= v;
    z() *= v;
  };
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
Referenced by SurfacePoint().
set() [1/2]
void igl::geodesic::Point3D::set (double * data) inline inherited
  {
    x() = *data;
    y() = *(data+1);
    z() = *(data+2);
  }
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
set() [2/2]
void igl::geodesic::Point3D::set (double new_x, double new_y, double new_z) inline inherited
  {
    x() = new_x;
    y() = new_y;
    z() = new_z;
  }
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
Referenced by SurfacePoint(), SurfacePoint(), and igl::geodesic::fill_surface_point_structure().
type()
PointType igl::geodesic::SurfacePoint::type () inline
{return m_p ? m_p->type() : UNDEFINED_POINT;};
References m_p, igl::geodesic::MeshElementBase::type(), and igl::geodesic::UNDEFINED_POINT.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::fill_surface_point_double(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
x()
double & igl::geodesic::Point3D::x () inline inherited
{return *m_coordinates;};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::Point3D(), SurfacePoint(), SurfacePoint(), igl::geodesic::Point3D::add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Point3D::multiply(), igl::geodesic::SurfacePointWithIndex::operator()(), igl::geodesic::Point3D::set(), igl::geodesic::Point3D::set(), and igl::geodesic::Mesh::verify().
xyz()
double * igl::geodesic::Point3D::xyz () inline inherited
{return m_coordinates;};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::distance().
y()
double & igl::geodesic::Point3D::y () inline inherited
{return *(m_coordinates+1);};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::Point3D(), SurfacePoint(), SurfacePoint(), igl::geodesic::Point3D::add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Point3D::multiply(), igl::geodesic::SurfacePointWithIndex::operator()(), igl::geodesic::Point3D::set(), igl::geodesic::Point3D::set(), and igl::geodesic::Mesh::verify().
z()
double & igl::geodesic::Point3D::z () inline inherited
{return *(m_coordinates+2);};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::Point3D(), SurfacePoint(), SurfacePoint(), igl::geodesic::Point3D::add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Point3D::multiply(), igl::geodesic::Point3D::set(), igl::geodesic::Point3D::set(), and igl::geodesic::Mesh::verify().
Member Data Documentation
m_coordinates
double igl::geodesic::Point3D::m_coordinates[3] private inherited
Referenced by igl::geodesic::Point3D::distance(), igl::geodesic::Point3D::x(), igl::geodesic::Point3D::xyz(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
m_p
base_pointer igl::geodesic::SurfacePoint::m_p protected
Referenced by base_element(), and type().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp