Prusa Slicer: src/avrdude/config.h File Reference
config.h File Reference
#include "libavrdude.h"
Classes
struct value_t
struct token_t
Macros
#define MAX_STR_CONST 1024
#define YYSTYPE token_p
Typedefs
typedef struct value_t VALUE
typedef struct token_t TOKEN
typedef struct token_t * token_p
Enumerations
enum { V_NONE , V_NUM , V_NUM_REAL , V_STR }
Functions
int yyparse (void)
int yyerror (char *errmsg,...)
int yywarning (char *errmsg,...)
TOKEN * new_token (int primary)
void free_token (TOKEN *tkn)
void free_tokens (int n,...)
TOKEN * number (char *text)
TOKEN * number_real (char *text)
TOKEN * hexnumber (char *text)
TOKEN * string (char *text)
TOKEN * keyword (int primary)
void print_token (TOKEN *tkn)
void pyytext (void)
char * dup_string (const char *str)
Variables
FILE * yyin = NULL
PROGRAMMER * current_prog
AVRPART * current_part
AVRMEM * current_mem
int lineno
const char * infile
LISTID string_list
LISTID number_list
YYSTYPE yylval
char string_buf [MAX_STR_CONST]
char * string_buf_ptr
Class Documentation
value_t
struct value_t
Class Members
int number
double number_real
char * string
int type
token_t
struct token_t
Class Members
int primary
VALUE value
Macro Definition Documentation
MAX_STR_CONST
#define MAX_STR_CONST 1024
YYSTYPE
#define YYSTYPE token_p
Typedef Documentation
TOKEN
typedef struct token_t TOKEN
token_p
typedef struct token_t* token_p
VALUE
typedef struct value_t VALUE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
V_NONE
V_NUM
V_NUM_REAL
V_STR
{ V_NONE, V_NUM, V_NUM_REAL, V_STR };
Function Documentation
dup_string()
char * dup_string (const char * str)
{
  char * s;
  s = strdup(str);
  if (s == NULL) {
    yyerror("dup_string(): out of memory");
    return NULL;
  }
  return s;
}
References yyerror().
Referenced by yyparse().
free_token()
void free_token (TOKEN * tkn)
{
  if (tkn) {
    switch (tkn->value.type) {
      case V_STR:
        if (tkn->value.string)
          free(tkn->value.string);
        tkn->value.string = NULL;
        break;
    }
    free(tkn);
  }
}
References free(), value_t::string, value_t::type, V_STR, and token_t::value.
Referenced by assign_pin(), assign_pin_list(), cleanup_config(), free_tokens(), parse_cmdbits(), and yyparse().
free_tokens()
void free_tokens (int n, ...)
{
  TOKEN * t;
  va_list ap;
  va_start(ap, n);
  while (n--) {
    t = va_arg(ap, TOKEN *);
    free_token(t);
  }
  va_end(ap);
}
References free_token().
Referenced by yyparse().
hexnumber()
TOKEN * hexnumber (char * text)
{
  struct token_t * tkn;
  char * e;
  tkn = new_token(TKN_NUMBER);
  if (tkn == NULL) {
      return NULL; /* yyerror already called */
  }
  tkn->value.type   = V_NUM;
  tkn->value.number = strtoul(text, &e, 16);
  if ((e == text) || (*e != 0)) {
    yyerror("can't scan hex number \"%s\"", text);
    return NULL;
  }
#if DEBUG
  avrdude_message(MSG_INFO, "HEXNUMBER(%g)\n", tkn->value.number);
#endif
  return tkn;
}
References avrdude_message(), MSG_INFO, new_token(), value_t::number, TKN_NUMBER, value_t::type, V_NUM, token_t::value, and yyerror().
keyword()
TOKEN * keyword (int primary)
{
  struct token_t * tkn;
  tkn = new_token(primary);
  return tkn;
}
References new_token(), and token_t::primary.
Referenced by Slic3r::GCode::do_export(), and Slic3r::GUI::Tab::validate_custom_gcode().
new_token()
TOKEN * new_token (int primary)
{
  TOKEN * tkn;
  tkn = (TOKEN *)malloc(sizeof(TOKEN));
  if (tkn == NULL) {
    yyerror("new_token(): out of memory");
    return NULL;
  }
  memset(tkn, 0, sizeof(TOKEN));
  tkn->primary = primary;
  return tkn;
}
References malloc(), token_t::primary, and yyerror().
Referenced by hexnumber(), keyword(), number(), number_real(), and string().
number()
TOKEN * number (char * text)
{
  struct token_t * tkn;
  tkn = new_token(TKN_NUMBER);
  if (tkn == NULL) {
      return NULL; /* yyerror already called */
  }
  tkn->value.type   = V_NUM;
  tkn->value.number = atoi(text);
#if DEBUG
  avrdude_message(MSG_INFO, "NUMBER(%d)\n", tkn->value.number);
#endif
  return tkn;
}
References avrdude_message(), MSG_INFO, new_token(), value_t::number, TKN_NUMBER, value_t::type, V_NUM, and token_t::value.
Referenced by Slic3r::anonymous_namespace{SL1_SVG.cpp}::decimal_from().
number_real()
TOKEN * number_real (char * text)
{
  struct token_t * tkn;
  tkn = new_token(TKN_NUMBER);
  tkn->value.type   = V_NUM_REAL;
  tkn->value.number_real = atof(text);
#if DEBUG
  avrdude_message(MSG_INFO, "NUMBER(%g)\n", tkn->value.number_real);
#endif
  return tkn;
}
References avrdude_message(), MSG_INFO, new_token(), value_t::number_real, TKN_NUMBER, value_t::type, V_NUM_REAL, and token_t::value.
print_token()
void print_token (TOKEN * tkn)
{
  if (!tkn)
    return;
  avrdude_message(MSG_INFO, "token = %d = ", tkn->primary);
  switch (tkn->value.type) {
    case V_NUM:
      avrdude_message(MSG_INFO, "NUMBER, value=%d", tkn->value.number);
      break;
    case V_NUM_REAL:
      avrdude_message(MSG_INFO, "NUMBER, value=%g", tkn->value.number_real);
      break;
    case V_STR:
      avrdude_message(MSG_INFO, "STRING, value=%s", tkn->value.string);
      break;
    default:
      avrdude_message(MSG_INFO, "<other>");
      break;
  }
  avrdude_message(MSG_INFO, "\n");
}
References avrdude_message(), MSG_INFO, value_t::number, value_t::number_real, token_t::primary, value_t::string, value_t::type, V_NUM, V_NUM_REAL, V_STR, and token_t::value.
pyytext()
void pyytext (void)
{
#if DEBUG
  avrdude_message(MSG_INFO, "TOKEN: \"%s\"\n", yytext);
#endif
}
string()
TOKEN * string (char * text)
{
  struct token_t * tkn;
  int len;
  tkn = new_token(TKN_STRING);
  if (tkn == NULL) {
      return NULL; /* yyerror already called */
  }
  len = (int)strlen(text);
  tkn->value.type   = V_STR;
  tkn->value.string = (char *) malloc(len+1);
  if (tkn->value.string == NULL) {
    yyerror("string(): out of memory");
    return NULL;
  }
  strcpy(tkn->value.string, text);
#if DEBUG
  avrdude_message(MSG_INFO, "STRING(%s)\n", tkn->value.string);
#endif
  return tkn;
}
References avrdude_message(), malloc(), MSG_INFO, new_token(), value_t::string, TKN_STRING, value_t::type, V_STR, token_t::value, and yyerror().
Referenced by Slic3r::client::macro_processor::macro_processor(), igl::readOFF(), and igl::readWRL().
yyerror()
int yyerror (char * errmsg, ...)
{
  va_list args;
  char message[512];
  va_start(args, errmsg);
  vsnprintf(message, sizeof(message), errmsg, args);
  avrdude_message(MSG_INFO, "%s: error at %s:%d: %s\n", progname, infile, lineno, message);
  va_end(args);
  return 0;
}
yyparse()
int yyparse (void)
{
    int yystate;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus;
    /* The stacks and their tools:
       'yyss': related to states.
       'yyvs': related to semantic values.
       Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */
    /* The state stack.  */
    yytype_int16 yyssa[YYINITDEPTH];
    yytype_int16 *yyss;
    yytype_int16 *yyssp;
    /* The semantic value stack.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs;
    YYSTYPE *yyvsp;
    YYSIZE_T yystacksize;
  int yyn;
  int yyresult;
  /* Lookahead token as an internal (translated) token number.  */
  int yytoken = 0;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;
#if YYERROR_VERBOSE
  /* Buffer for error messages, and its allocated size.  */
  char yymsgbuf[128];
  char *yymsg = yymsgbuf;
  YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
#endif
#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;
  yyssp = yyss = yyssa;
  yyvsp = yyvs = yyvsa;
  yystacksize = YYINITDEPTH;
  YYDPRINTF ((stderr, "Starting parse\n"));
  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY; /* Cause a token to be read.  */
  goto yysetstate;
/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;
 yysetstate:
  *yyssp = yystate;
  if (yyss + yystacksize - 1 <= yyssp)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;
#ifdef yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        YYSTYPE *yyvs1 = yyvs;
        yytype_int16 *yyss1 = yyss;
        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * sizeof (*yyssp),
                    &yyvs1, yysize * sizeof (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyexhaustedlab;
# else
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        goto yyexhaustedlab;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;
      {
        yytype_int16 *yyss1 = yyss;
        union yyalloc *yyptr =
          (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
        if (! yyptr)
          goto yyexhaustedlab;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */
      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;
      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                  (unsigned long int) yystacksize));
      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  if (yystate == YYFINAL)
    YYACCEPT;
  goto yybackup;
/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */
  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;
  /* Not known => get a lookahead token if don't already have one.  */
  /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = yylex ();
    }
  if (yychar <= YYEOF)
    {
      yychar = yytoken = YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }
  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }
  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;
  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END
  goto yynewstate;
/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;
/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];
  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.
     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];
  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
        case 2:
#line 211 "config_gram.y" /* yacc.c:1646  */
    {
    (yyval) = (yyvsp[0]);
    /* convert value to real */
    (yyval)->value.number_real = (yyval)->value.number;
    (yyval)->value.type = V_NUM_REAL;
  }
#line 1819 "config_gram.c" /* yacc.c:1646  */
    break;
  case 3:
#line 217 "config_gram.y" /* yacc.c:1646  */
    {
    (yyval) = (yyvsp[0]);
  }
#line 1827 "config_gram.c" /* yacc.c:1646  */
    break;
  case 10:
#line 236 "config_gram.y" /* yacc.c:1646  */
    {
    strncpy(default_programmer, (yyvsp[-1])->value.string, MAX_STR_CONST);
    default_programmer[MAX_STR_CONST-1] = 0;
    free_token((yyvsp[-1]));
  }
#line 1837 "config_gram.c" /* yacc.c:1646  */
    break;
  case 11:
#line 242 "config_gram.y" /* yacc.c:1646  */
    {
    strncpy(default_parallel, (yyvsp[-1])->value.string, PATH_MAX);
    default_parallel[PATH_MAX-1] = 0;
    free_token((yyvsp[-1]));
  }
#line 1847 "config_gram.c" /* yacc.c:1646  */
    break;
  case 12:
#line 248 "config_gram.y" /* yacc.c:1646  */
    {
    strncpy(default_serial, (yyvsp[-1])->value.string, PATH_MAX);
    default_serial[PATH_MAX-1] = 0;
    free_token((yyvsp[-1]));
  }
#line 1857 "config_gram.c" /* yacc.c:1646  */
    break;
  case 13:
#line 254 "config_gram.y" /* yacc.c:1646  */
    {
    default_bitclock = (yyvsp[-1])->value.number_real;
    free_token((yyvsp[-1]));
  }
#line 1866 "config_gram.c" /* yacc.c:1646  */
    break;
  case 14:
#line 259 "config_gram.y" /* yacc.c:1646  */
    {
    if ((yyvsp[-1])->primary == K_YES)
      default_safemode = 1;
    else if ((yyvsp[-1])->primary == K_NO)
      default_safemode = 0;
    free_token((yyvsp[-1]));
  }
#line 1878 "config_gram.c" /* yacc.c:1646  */
    break;
  case 15:
#line 271 "config_gram.y" /* yacc.c:1646  */
    {
      PROGRAMMER * existing_prog;
      char * id;
      if (lsize(current_prog->id) == 0) {
        yyerror("required parameter id not specified");
        YYABORT;
      }
      if (current_prog->initpgm == NULL) {
        yyerror("programmer type not specified");
        YYABORT;
      }
      id = ldata(lfirst(current_prog->id));
      existing_prog = locate_programmer(programmers, id);
      if (existing_prog) {
        { /* temporarly set lineno to lineno of programmer start */
          int temp = lineno; lineno = current_prog->lineno;
          yywarning("programmer %s overwrites previous definition %s:%d.",
                id, existing_prog->config_file, existing_prog->lineno);
          lineno = temp;
        }
        lrmv_d(programmers, existing_prog);
        pgm_free(existing_prog);
      }
      PUSH(programmers, current_prog);
//      pgm_fill_old_pins(current_prog); // TODO to be removed if old pin data no longer needed
//      pgm_display_generic(current_prog, id);
      current_prog = NULL;
    }
#line 1911 "config_gram.c" /* yacc.c:1646  */
    break;
  case 16:
#line 304 "config_gram.y" /* yacc.c:1646  */
    { current_prog = pgm_new();
      if (current_prog == NULL) {
        yyerror("could not create pgm instance");
        YYABORT;
      }
      strcpy(current_prog->config_file, infile);
      current_prog->lineno = lineno;
    }
#line 1924 "config_gram.c" /* yacc.c:1646  */
    break;
  case 17:
#line 314 "config_gram.y" /* yacc.c:1646  */
    {
      struct programmer_t * pgm = locate_programmer(programmers, (yyvsp[0])->value.string);
      if (pgm == NULL) {
        yyerror("parent programmer %s not found", (yyvsp[0])->value.string);
        free_token((yyvsp[0]));
        YYABORT;
      }
      current_prog = pgm_dup(pgm);
      if (current_prog == NULL) {
        yyerror("could not duplicate pgm instance");
        free_token((yyvsp[0]));
        YYABORT;
      }
      strcpy(current_prog->config_file, infile);
      current_prog->lineno = lineno;
      free_token((yyvsp[0]));
    }
#line 1946 "config_gram.c" /* yacc.c:1646  */
    break;
  case 18:
#line 336 "config_gram.y" /* yacc.c:1646  */
    {
      LNODEID ln;
      AVRMEM * m;
      AVRPART * existing_part;
      if (current_part->id[0] == 0) {
        yyerror("required parameter id not specified");
        YYABORT;
      }
      /*
       * perform some sanity checking, and compute the number of bits
       * to shift a page for constructing the page address for
       * page-addressed memories.
       */
      for (ln=lfirst(current_part->mem); ln; ln=lnext(ln)) {
        m = ldata(ln);
        if (m->paged) {
          if (m->page_size == 0) {
            yyerror("must specify page_size for paged memory");
            YYABORT;
          }
          if (m->num_pages == 0) {
            yyerror("must specify num_pages for paged memory");
            YYABORT;
          }
          if (m->size != m->page_size * m->num_pages) {
            yyerror("page size (%u) * num_pages (%u) = "
                    "%u does not match memory size (%u)",
                    m->page_size,
                    m->num_pages,
                    m->page_size * m->num_pages,
                    m->size);
            YYABORT;
          }
        }
      }
      existing_part = locate_part(part_list, current_part->id);
      if (existing_part) {
        { /* temporarly set lineno to lineno of part start */
          int temp = lineno; lineno = current_part->lineno;
          yywarning("part %s overwrites previous definition %s:%d.",
                current_part->id,
                existing_part->config_file, existing_part->lineno);
          lineno = temp;
        }
        lrmv_d(part_list, existing_part);
        avr_free_part(existing_part);
      }
      PUSH(part_list, current_part);
      current_part = NULL;
    }
#line 2005 "config_gram.c" /* yacc.c:1646  */
    break;
  case 19:
#line 394 "config_gram.y" /* yacc.c:1646  */
    {
      current_part = avr_new_part();
      if (current_part == NULL) {
        yyerror("could not create part instance");
        YYABORT;
      }
      strcpy(current_part->config_file, infile);
      current_part->lineno = lineno;
    }
#line 2019 "config_gram.c" /* yacc.c:1646  */
    break;
  case 20:
#line 404 "config_gram.y" /* yacc.c:1646  */
    {
      AVRPART * parent_part = locate_part(part_list, (yyvsp[0])->value.string);
      if (parent_part == NULL) {
        yyerror("can't find parent part");
        free_token((yyvsp[0]));
        YYABORT;
      }
      current_part = avr_dup_part(parent_part);
      if (current_part == NULL) {
        yyerror("could not duplicate part instance");
        free_token((yyvsp[0]));
        YYABORT;
      }
      strcpy(current_part->config_file, infile);
      current_part->lineno = lineno;
      free_token((yyvsp[0]));
    }
#line 2043 "config_gram.c" /* yacc.c:1646  */
    break;
  case 21:
#line 426 "config_gram.y" /* yacc.c:1646  */
    { ladd(string_list, (yyvsp[0])); }
#line 2049 "config_gram.c" /* yacc.c:1646  */
    break;
  case 22:
#line 427 "config_gram.y" /* yacc.c:1646  */
    { ladd(string_list, (yyvsp[0])); }
#line 2055 "config_gram.c" /* yacc.c:1646  */
    break;
  case 23:
#line 432 "config_gram.y" /* yacc.c:1646  */
    { ladd(number_list, (yyvsp[0])); }
#line 2061 "config_gram.c" /* yacc.c:1646  */
    break;
  case 24:
#line 433 "config_gram.y" /* yacc.c:1646  */
    { ladd(number_list, (yyvsp[0])); }
#line 2067 "config_gram.c" /* yacc.c:1646  */
    break;
  case 27:
#line 442 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      char *s;
      int do_yyabort = 0;
      while (lsize(string_list)) {
        t = lrmv_n(string_list, 1);
        if (!do_yyabort) {
          s = dup_string(t->value.string);
          if (s == NULL) {
            do_yyabort = 1;
          } else {
            ladd(current_prog->id, s);
          }
        }
        /* if do_yyabort == 1 just make the list empty */
        free_token(t);
      }
      if (do_yyabort) {
        YYABORT;
      }
    }
  }
#line 2095 "config_gram.c" /* yacc.c:1646  */
    break;
  case 32:
#line 473 "config_gram.y" /* yacc.c:1646  */
    {
    strncpy(current_prog->desc, (yyvsp[0])->value.string, PGM_DESCLEN);
    current_prog->desc[PGM_DESCLEN-1] = 0;
    free_token((yyvsp[0]));
  }
#line 2105 "config_gram.c" /* yacc.c:1646  */
    break;
  case 33:
#line 478 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_prog->baudrate = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2116 "config_gram.c" /* yacc.c:1646  */
    break;
  case 35:
#line 491 "config_gram.y" /* yacc.c:1646  */
    {
  const struct programmer_type_t * pgm_type = locate_programmer_type((yyvsp[0])->value.string);
    if (pgm_type == NULL) {
        yyerror("programmer type %s not found", (yyvsp[0])->value.string);
        free_token((yyvsp[0]));
        YYABORT;
    }
    current_prog->initpgm = pgm_type->initpgm;
    free_token((yyvsp[0]));
}
#line 2131 "config_gram.c" /* yacc.c:1646  */
    break;
  case 36:
#line 502 "config_gram.y" /* yacc.c:1646  */
    {
        yyerror("programmer type must be written as \"id_type\"");
        YYABORT;
}
#line 2140 "config_gram.c" /* yacc.c:1646  */
    break;
  case 38:
#line 513 "config_gram.y" /* yacc.c:1646  */
    { current_prog->conntype = CONNTYPE_PARALLEL; }
#line 2146 "config_gram.c" /* yacc.c:1646  */
    break;
  case 39:
#line 514 "config_gram.y" /* yacc.c:1646  */
    { current_prog->conntype = CONNTYPE_SERIAL; }
#line 2152 "config_gram.c" /* yacc.c:1646  */
    break;
  case 40:
#line 515 "config_gram.y" /* yacc.c:1646  */
    { current_prog->conntype = CONNTYPE_USB; }
#line 2158 "config_gram.c" /* yacc.c:1646  */
    break;
  case 41:
#line 519 "config_gram.y" /* yacc.c:1646  */
    {
    {
      strncpy(current_prog->usbdev, (yyvsp[0])->value.string, PGM_USBSTRINGLEN);
      current_prog->usbdev[PGM_USBSTRINGLEN-1] = 0;
      free_token((yyvsp[0]));
    }
  }
#line 2170 "config_gram.c" /* yacc.c:1646  */
    break;
  case 42:
#line 526 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_prog->usbvid = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2181 "config_gram.c" /* yacc.c:1646  */
    break;
  case 44:
#line 533 "config_gram.y" /* yacc.c:1646  */
    {
    {
      strncpy(current_prog->usbsn, (yyvsp[0])->value.string, PGM_USBSTRINGLEN);
      current_prog->usbsn[PGM_USBSTRINGLEN-1] = 0;
      free_token((yyvsp[0]));
    }
  }
#line 2193 "config_gram.c" /* yacc.c:1646  */
    break;
  case 45:
#line 540 "config_gram.y" /* yacc.c:1646  */
    {
    {
      strncpy(current_prog->usbvendor, (yyvsp[0])->value.string, PGM_USBSTRINGLEN);
      current_prog->usbvendor[PGM_USBSTRINGLEN-1] = 0;
      free_token((yyvsp[0]));
    }
  }
#line 2205 "config_gram.c" /* yacc.c:1646  */
    break;
  case 46:
#line 547 "config_gram.y" /* yacc.c:1646  */
    {
    {
      strncpy(current_prog->usbproduct, (yyvsp[0])->value.string, PGM_USBSTRINGLEN);
      current_prog->usbproduct[PGM_USBSTRINGLEN-1] = 0;
      free_token((yyvsp[0]));
    }
  }
#line 2217 "config_gram.c" /* yacc.c:1646  */
    break;
  case 47:
#line 557 "config_gram.y" /* yacc.c:1646  */
    {
    {
      /* overwrite pids, so clear the existing entries */
      ldestroy_cb(current_prog->usbpid, free);
      current_prog->usbpid = lcreat(NULL, 0);
    }
    {
      int *ip = malloc(sizeof(int));
      if (ip) {
        *ip = (yyvsp[0])->value.number;
        ladd(current_prog->usbpid, ip);
      }
      free_token((yyvsp[0]));
    }
  }
#line 2237 "config_gram.c" /* yacc.c:1646  */
    break;
  case 48:
#line 572 "config_gram.y" /* yacc.c:1646  */
    {
    {
      int *ip = malloc(sizeof(int));
      if (ip) {
        *ip = (yyvsp[0])->value.number;
        ladd(current_prog->usbpid, ip);
      }
      free_token((yyvsp[0]));
    }
  }
#line 2252 "config_gram.c" /* yacc.c:1646  */
    break;
  case 49:
#line 585 "config_gram.y" /* yacc.c:1646  */
    { if(0 != assign_pin(pin_name, (yyvsp[0]), 0)) YYABORT;  }
#line 2258 "config_gram.c" /* yacc.c:1646  */
    break;
  case 50:
#line 587 "config_gram.y" /* yacc.c:1646  */
    { if(0 != assign_pin(pin_name, (yyvsp[0]), 1)) YYABORT; }
#line 2264 "config_gram.c" /* yacc.c:1646  */
    break;
  case 52:
#line 593 "config_gram.y" /* yacc.c:1646  */
    { pin_clear_all(&(current_prog->pin[pin_name])); }
#line 2270 "config_gram.c" /* yacc.c:1646  */
    break;
  case 54:
#line 599 "config_gram.y" /* yacc.c:1646  */
    { if(0 != assign_pin_list(1)) YYABORT; }
#line 2276 "config_gram.c" /* yacc.c:1646  */
    break;
  case 58:
#line 612 "config_gram.y" /* yacc.c:1646  */
    { pin_clear_all(&(current_prog->pin[pin_name])); }
#line 2282 "config_gram.c" /* yacc.c:1646  */
    break;
  case 59:
#line 616 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PPI_AVR_VCC;  }
#line 2288 "config_gram.c" /* yacc.c:1646  */
    break;
  case 61:
#line 617 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PPI_AVR_BUFF; }
#line 2294 "config_gram.c" /* yacc.c:1646  */
    break;
  case 63:
#line 618 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_AVR_RESET;}
#line 2300 "config_gram.c" /* yacc.c:1646  */
    break;
  case 64:
#line 618 "config_gram.y" /* yacc.c:1646  */
    { free_token((yyvsp[-3])); }
#line 2306 "config_gram.c" /* yacc.c:1646  */
    break;
  case 65:
#line 619 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_AVR_SCK;  }
#line 2312 "config_gram.c" /* yacc.c:1646  */
    break;
  case 66:
#line 619 "config_gram.y" /* yacc.c:1646  */
    { free_token((yyvsp[-3])); }
#line 2318 "config_gram.c" /* yacc.c:1646  */
    break;
  case 67:
#line 620 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_AVR_MOSI; }
#line 2324 "config_gram.c" /* yacc.c:1646  */
    break;
  case 69:
#line 621 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_AVR_MISO; }
#line 2330 "config_gram.c" /* yacc.c:1646  */
    break;
  case 71:
#line 622 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_LED_ERR;  }
#line 2336 "config_gram.c" /* yacc.c:1646  */
    break;
  case 73:
#line 623 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_LED_RDY;  }
#line 2342 "config_gram.c" /* yacc.c:1646  */
    break;
  case 75:
#line 624 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_LED_PGM;  }
#line 2348 "config_gram.c" /* yacc.c:1646  */
    break;
  case 77:
#line 625 "config_gram.y" /* yacc.c:1646  */
    {pin_name = PIN_LED_VFY;  }
#line 2354 "config_gram.c" /* yacc.c:1646  */
    break;
  case 99:
#line 664 "config_gram.y" /* yacc.c:1646  */
    {
      strncpy(current_part->id, (yyvsp[0])->value.string, AVR_IDLEN);
      current_part->id[AVR_IDLEN-1] = 0;
      free_token((yyvsp[0]));
    }
#line 2364 "config_gram.c" /* yacc.c:1646  */
    break;
  case 100:
#line 671 "config_gram.y" /* yacc.c:1646  */
    {
      strncpy(current_part->desc, (yyvsp[0])->value.string, AVR_DESCLEN);
      current_part->desc[AVR_DESCLEN-1] = 0;
      free_token((yyvsp[0]));
    }
#line 2374 "config_gram.c" /* yacc.c:1646  */
    break;
  case 101:
#line 677 "config_gram.y" /* yacc.c:1646  */
    {
    {
      yyerror("devicecode is deprecated, use "
              "stk500_devcode instead");
      YYABORT;
    }
  }
#line 2386 "config_gram.c" /* yacc.c:1646  */
    break;
  case 102:
#line 685 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_part->stk500_devcode = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2397 "config_gram.c" /* yacc.c:1646  */
    break;
  case 103:
#line 692 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_part->avr910_devcode = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2408 "config_gram.c" /* yacc.c:1646  */
    break;
  case 104:
#line 699 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_part->signature[0] = (yyvsp[-2])->value.number;
      current_part->signature[1] = (yyvsp[-1])->value.number;
      current_part->signature[2] = (yyvsp[0])->value.number;
      free_token((yyvsp[-2]));
      free_token((yyvsp[-1]));
      free_token((yyvsp[0]));
    }
  }
#line 2423 "config_gram.c" /* yacc.c:1646  */
    break;
  case 105:
#line 710 "config_gram.y" /* yacc.c:1646  */
    {
    {
      current_part->usbpid = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
  }
#line 2434 "config_gram.c" /* yacc.c:1646  */
    break;
  case 106:
#line 717 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      unsigned nbytes;
      int ok;
      current_part->ctl_stack_type = CTL_STACK_PP;
      nbytes = 0;
      ok = 1;
      memset(current_part->controlstack, 0, CTL_STACK_SIZE);
      while (lsize(number_list)) {
        t = lrmv_n(number_list, 1);
  if (nbytes < CTL_STACK_SIZE)
    {
      current_part->controlstack[nbytes] = t->value.number;
      nbytes++;
    }
  else
    {
      ok = 0;
    }
        free_token(t);
      }
      if (!ok)
  {
    yywarning("too many bytes in control stack");
        }
    }
  }
#line 2469 "config_gram.c" /* yacc.c:1646  */
    break;
  case 107:
#line 748 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      unsigned nbytes;
      int ok;
      current_part->ctl_stack_type = CTL_STACK_HVSP;
      nbytes = 0;
      ok = 1;
      memset(current_part->controlstack, 0, CTL_STACK_SIZE);
      while (lsize(number_list)) {
        t = lrmv_n(number_list, 1);
  if (nbytes < CTL_STACK_SIZE)
    {
      current_part->controlstack[nbytes] = t->value.number;
      nbytes++;
    }
  else
    {
      ok = 0;
    }
        free_token(t);
      }
      if (!ok)
  {
    yywarning("too many bytes in control stack");
        }
    }
  }
#line 2504 "config_gram.c" /* yacc.c:1646  */
    break;
  case 108:
#line 779 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      unsigned nbytes;
      int ok;
      nbytes = 0;
      ok = 1;
      memset(current_part->flash_instr, 0, FLASH_INSTR_SIZE);
      while (lsize(number_list)) {
        t = lrmv_n(number_list, 1);
  if (nbytes < FLASH_INSTR_SIZE)
    {
      current_part->flash_instr[nbytes] = t->value.number;
      nbytes++;
    }
  else
    {
      ok = 0;
    }
        free_token(t);
      }
      if (!ok)
  {
    yywarning("too many bytes in flash instructions");
        }
    }
  }
#line 2538 "config_gram.c" /* yacc.c:1646  */
    break;
  case 109:
#line 809 "config_gram.y" /* yacc.c:1646  */
    {
    {
      TOKEN * t;
      unsigned nbytes;
      int ok;
      nbytes = 0;
      ok = 1;
      memset(current_part->eeprom_instr, 0, EEPROM_INSTR_SIZE);
      while (lsize(number_list)) {
        t = lrmv_n(number_list, 1);
  if (nbytes < EEPROM_INSTR_SIZE)
    {
      current_part->eeprom_instr[nbytes] = t->value.number;
      nbytes++;
    }
  else
    {
      ok = 0;
    }
        free_token(t);
      }
      if (!ok)
  {
    yywarning("too many bytes in EEPROM instructions");
        }
    }
  }
#line 2572 "config_gram.c" /* yacc.c:1646  */
    break;
  case 110:
#line 840 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->chip_erase_delay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2581 "config_gram.c" /* yacc.c:1646  */
    break;
  case 111:
#line 846 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->pagel = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2590 "config_gram.c" /* yacc.c:1646  */
    break;
  case 112:
#line 852 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->bs2 = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2599 "config_gram.c" /* yacc.c:1646  */
    break;
  case 113:
#line 858 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_DEDICATED)
        current_part->reset_disposition = RESET_DEDICATED;
      else if ((yyvsp[0])->primary == K_IO)
        current_part->reset_disposition = RESET_IO;
      free_tokens(2, (yyvsp[-2]), (yyvsp[0]));
    }
#line 2612 "config_gram.c" /* yacc.c:1646  */
    break;
  case 114:
#line 868 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->timeout = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2621 "config_gram.c" /* yacc.c:1646  */
    break;
  case 115:
#line 874 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->stabdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2630 "config_gram.c" /* yacc.c:1646  */
    break;
  case 116:
#line 880 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->cmdexedelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2639 "config_gram.c" /* yacc.c:1646  */
    break;
  case 117:
#line 886 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->hvspcmdexedelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2648 "config_gram.c" /* yacc.c:1646  */
    break;
  case 118:
#line 892 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->synchloops = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2657 "config_gram.c" /* yacc.c:1646  */
    break;
  case 119:
#line 898 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->bytedelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2666 "config_gram.c" /* yacc.c:1646  */
    break;
  case 120:
#line 904 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->pollvalue = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2675 "config_gram.c" /* yacc.c:1646  */
    break;
  case 121:
#line 910 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->pollindex = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2684 "config_gram.c" /* yacc.c:1646  */
    break;
  case 122:
#line 916 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->predelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2693 "config_gram.c" /* yacc.c:1646  */
    break;
  case 123:
#line 922 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->postdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2702 "config_gram.c" /* yacc.c:1646  */
    break;
  case 124:
#line 928 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->pollmethod = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2711 "config_gram.c" /* yacc.c:1646  */
    break;
  case 125:
#line 934 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->hventerstabdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2720 "config_gram.c" /* yacc.c:1646  */
    break;
  case 126:
#line 940 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->progmodedelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2729 "config_gram.c" /* yacc.c:1646  */
    break;
  case 127:
#line 946 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->latchcycles = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2738 "config_gram.c" /* yacc.c:1646  */
    break;
  case 128:
#line 952 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->togglevtg = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2747 "config_gram.c" /* yacc.c:1646  */
    break;
  case 129:
#line 958 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->poweroffdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2756 "config_gram.c" /* yacc.c:1646  */
    break;
  case 130:
#line 964 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->resetdelayms = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2765 "config_gram.c" /* yacc.c:1646  */
    break;
  case 131:
#line 970 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->resetdelayus = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2774 "config_gram.c" /* yacc.c:1646  */
    break;
  case 132:
#line 976 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->hvleavestabdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2783 "config_gram.c" /* yacc.c:1646  */
    break;
  case 133:
#line 982 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->resetdelay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2792 "config_gram.c" /* yacc.c:1646  */
    break;
  case 134:
#line 988 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->chiperasepulsewidth = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2801 "config_gram.c" /* yacc.c:1646  */
    break;
  case 135:
#line 994 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->chiperasepolltimeout = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2810 "config_gram.c" /* yacc.c:1646  */
    break;
  case 136:
#line 1000 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->chiperasetime = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2819 "config_gram.c" /* yacc.c:1646  */
    break;
  case 137:
#line 1006 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->programfusepulsewidth = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2828 "config_gram.c" /* yacc.c:1646  */
    break;
  case 138:
#line 1012 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->programfusepolltimeout = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2837 "config_gram.c" /* yacc.c:1646  */
    break;
  case 139:
#line 1018 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->programlockpulsewidth = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2846 "config_gram.c" /* yacc.c:1646  */
    break;
  case 140:
#line 1024 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->programlockpolltimeout = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2855 "config_gram.c" /* yacc.c:1646  */
    break;
  case 141:
#line 1030 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->synchcycles = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2864 "config_gram.c" /* yacc.c:1646  */
    break;
  case 142:
#line 1036 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_HAS_JTAG;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_HAS_JTAG;
      free_token((yyvsp[0]));
    }
#line 2877 "config_gram.c" /* yacc.c:1646  */
    break;
  case 143:
#line 1046 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_HAS_DW;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_HAS_DW;
      free_token((yyvsp[0]));
    }
#line 2890 "config_gram.c" /* yacc.c:1646  */
    break;
  case 144:
#line 1056 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_HAS_PDI;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_HAS_PDI;
      free_token((yyvsp[0]));
    }
#line 2903 "config_gram.c" /* yacc.c:1646  */
    break;
  case 145:
#line 1066 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_HAS_TPI;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_HAS_TPI;
      free_token((yyvsp[0]));
    }
#line 2916 "config_gram.c" /* yacc.c:1646  */
    break;
  case 146:
#line 1076 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_IS_AT90S1200;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_IS_AT90S1200;
      free_token((yyvsp[0]));
    }
#line 2929 "config_gram.c" /* yacc.c:1646  */
    break;
  case 147:
#line 1086 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_AVR32;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_AVR32;
      free_token((yyvsp[0]));
    }
#line 2942 "config_gram.c" /* yacc.c:1646  */
    break;
  case 148:
#line 1096 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_ALLOWFULLPAGEBITSTREAM;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_ALLOWFULLPAGEBITSTREAM;
      free_token((yyvsp[0]));
    }
#line 2955 "config_gram.c" /* yacc.c:1646  */
    break;
  case 149:
#line 1106 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_ENABLEPAGEPROGRAMMING;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_ENABLEPAGEPROGRAMMING;
      free_token((yyvsp[0]));
    }
#line 2968 "config_gram.c" /* yacc.c:1646  */
    break;
  case 150:
#line 1116 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->idr = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2977 "config_gram.c" /* yacc.c:1646  */
    break;
  case 151:
#line 1122 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->rampz = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2986 "config_gram.c" /* yacc.c:1646  */
    break;
  case 152:
#line 1128 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->spmcr = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 2995 "config_gram.c" /* yacc.c:1646  */
    break;
  case 153:
#line 1134 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->eecr = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3004 "config_gram.c" /* yacc.c:1646  */
    break;
  case 154:
#line 1140 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->mcu_base = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3013 "config_gram.c" /* yacc.c:1646  */
    break;
  case 155:
#line 1146 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->nvm_base = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3022 "config_gram.c" /* yacc.c:1646  */
    break;
  case 156:
#line 1152 "config_gram.y" /* yacc.c:1646  */
    {
      current_part->ocdrev = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3031 "config_gram.c" /* yacc.c:1646  */
    break;
  case 157:
#line 1158 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES)
        current_part->flags |= AVRPART_SERIALOK;
      else if ((yyvsp[0])->primary == K_NO)
        current_part->flags &= ~AVRPART_SERIALOK;
      free_token((yyvsp[0]));
    }
#line 3044 "config_gram.c" /* yacc.c:1646  */
    break;
  case 158:
#line 1168 "config_gram.y" /* yacc.c:1646  */
    {
      if ((yyvsp[0])->primary == K_YES) {
        current_part->flags |= AVRPART_PARALLELOK;
        current_part->flags &= ~AVRPART_PSEUDOPARALLEL;
      }
      else if ((yyvsp[0])->primary == K_NO) {
        current_part->flags &= ~AVRPART_PARALLELOK;
        current_part->flags &= ~AVRPART_PSEUDOPARALLEL;
      }
      else if ((yyvsp[0])->primary == K_PSEUDO) {
        current_part->flags |= AVRPART_PARALLELOK;
        current_part->flags |= AVRPART_PSEUDOPARALLEL;
      }
      free_token((yyvsp[0]));
    }
#line 3066 "config_gram.c" /* yacc.c:1646  */
    break;
  case 159:
#line 1187 "config_gram.y" /* yacc.c:1646  */
    {
      switch ((yyvsp[0])->primary) {
        case K_RESET :
          current_part->retry_pulse = PIN_AVR_RESET;
          break;
        case K_SCK :
          current_part->retry_pulse = PIN_AVR_SCK;
          break;
      }
      free_token((yyvsp[-2]));
    }
#line 3083 "config_gram.c" /* yacc.c:1646  */
    break;
  case 160:
#line 1210 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem = avr_new_memtype();
      if (current_mem == NULL) {
        yyerror("could not create mem instance");
        free_token((yyvsp[0]));
        YYABORT;
      }
      strncpy(current_mem->desc, (yyvsp[0])->value.string, AVR_MEMDESCLEN);
      current_mem->desc[AVR_MEMDESCLEN-1] = 0;
      free_token((yyvsp[0]));
    }
#line 3099 "config_gram.c" /* yacc.c:1646  */
    break;
  case 161:
#line 1222 "config_gram.y" /* yacc.c:1646  */
    {
      AVRMEM * existing_mem;
      existing_mem = avr_locate_mem(current_part, current_mem->desc);
      if (existing_mem != NULL) {
        lrmv_d(current_part->mem, existing_mem);
        avr_free_mem(existing_mem);
      }
      ladd(current_part->mem, current_mem);
      current_mem = NULL;
    }
#line 3115 "config_gram.c" /* yacc.c:1646  */
    break;
  case 162:
#line 1234 "config_gram.y" /* yacc.c:1646  */
    {
    {
      int opnum;
      OPCODE * op;
      opnum = which_opcode((yyvsp[-2]));
      if (opnum < 0) YYABORT;
      op = avr_new_opcode();
      if (op == NULL) {
        yyerror("could not create opcode instance");
        free_token((yyvsp[-2]));
        YYABORT;
      }
      if(0 != parse_cmdbits(op)) YYABORT;
      if (current_part->op[opnum] != NULL) {
        /*yywarning("operation redefined");*/
        avr_free_opcode(current_part->op[opnum]);
      }
      current_part->op[opnum] = op;
      free_token((yyvsp[-2]));
    }
  }
#line 3143 "config_gram.c" /* yacc.c:1646  */
    break;
  case 167:
#line 1273 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->paged = (yyvsp[0])->primary == K_YES ? 1 : 0;
      free_token((yyvsp[0]));
    }
#line 3152 "config_gram.c" /* yacc.c:1646  */
    break;
  case 168:
#line 1279 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->size = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3161 "config_gram.c" /* yacc.c:1646  */
    break;
  case 169:
#line 1286 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->page_size = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3170 "config_gram.c" /* yacc.c:1646  */
    break;
  case 170:
#line 1292 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->num_pages = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3179 "config_gram.c" /* yacc.c:1646  */
    break;
  case 171:
#line 1298 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->offset = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3188 "config_gram.c" /* yacc.c:1646  */
    break;
  case 172:
#line 1304 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->min_write_delay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3197 "config_gram.c" /* yacc.c:1646  */
    break;
  case 173:
#line 1310 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->max_write_delay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3206 "config_gram.c" /* yacc.c:1646  */
    break;
  case 174:
#line 1316 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->pwroff_after_write = (yyvsp[0])->primary == K_YES ? 1 : 0;
      free_token((yyvsp[0]));
    }
#line 3215 "config_gram.c" /* yacc.c:1646  */
    break;
  case 175:
#line 1322 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->readback[0] = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3224 "config_gram.c" /* yacc.c:1646  */
    break;
  case 176:
#line 1328 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->readback[1] = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3233 "config_gram.c" /* yacc.c:1646  */
    break;
  case 177:
#line 1335 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->mode = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3242 "config_gram.c" /* yacc.c:1646  */
    break;
  case 178:
#line 1341 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->delay = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3251 "config_gram.c" /* yacc.c:1646  */
    break;
  case 179:
#line 1347 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->blocksize = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3260 "config_gram.c" /* yacc.c:1646  */
    break;
  case 180:
#line 1353 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->readsize = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3269 "config_gram.c" /* yacc.c:1646  */
    break;
  case 181:
#line 1359 "config_gram.y" /* yacc.c:1646  */
    {
      current_mem->pollindex = (yyvsp[0])->value.number;
      free_token((yyvsp[0]));
    }
#line 3278 "config_gram.c" /* yacc.c:1646  */
    break;
  case 182:
#line 1365 "config_gram.y" /* yacc.c:1646  */
    {
    {
      int opnum;
      OPCODE * op;
      opnum = which_opcode((yyvsp[-2]));
      if (opnum < 0) YYABORT;
      op = avr_new_opcode();
      if (op == NULL) {
        yyerror("could not create opcode instance");
        free_token((yyvsp[-2]));
        YYABORT;
      }
      if(0 != parse_cmdbits(op)) YYABORT;
      if (current_mem->op[opnum] != NULL) {
        /*yywarning("operation redefined");*/
        avr_free_opcode(current_mem->op[opnum]);
      }
      current_mem->op[opnum] = op;
      free_token((yyvsp[-2]));
    }
  }
#line 3306 "config_gram.c" /* yacc.c:1646  */
    break;
#line 3310 "config_gram.c" /* yacc.c:1646  */
      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  *++yyvsp = yyval;
  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  yyn = yyr1[yyn];
  yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
  if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTOKENS];
  goto yynewstate;
/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
#if ! YYERROR_VERBOSE
      yyerror (YY_("syntax error"));
#else
# define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                        yyssp, yytoken)
      {
        char const *yymsgp = YY_("syntax error");
        int yysyntax_error_status;
        yysyntax_error_status = YYSYNTAX_ERROR;
        if (yysyntax_error_status == 0)
          yymsgp = yymsg;
        else if (yysyntax_error_status == 1)
          {
            if (yymsg != yymsgbuf)
              YYSTACK_FREE (yymsg);
            yymsg = (char *) YYSTACK_ALLOC (yymsg_alloc);
            if (!yymsg)
              {
                yymsg = yymsgbuf;
                yymsg_alloc = sizeof yymsgbuf;
                yysyntax_error_status = 2;
              }
            else
              {
                yysyntax_error_status = YYSYNTAX_ERROR;
                yymsgp = yymsg;
              }
          }
        yyerror (yymsgp);
        if (yysyntax_error_status == 2)
          goto yyexhaustedlab;
      }
# undef YYSYNTAX_ERROR
#endif
    }
  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */
      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }
  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;
/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers like GCC when the user code never invokes
     YYERROR and the label yyerrorlab therefore never appears in user
     code.  */
  if (/*CONSTCOND*/ 0)
     goto yyerrorlab;
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;
/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYTERROR;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }
      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;
      yydestruct ("Error: popping",
                  yystos[yystate], yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END
  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);
  yystate = yyn;
  goto yynewstate;
/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;
/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;
#if !defined yyoverflow || YYERROR_VERBOSE
/*-------------------------------------------------.
| yyexhaustedlab -- memory exhaustion comes here.  |
`-------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  /* Fall through.  */
#endif
yyreturn:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  yystos[*yyssp], yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
#if YYERROR_VERBOSE
  if (yymsg != yymsgbuf)
    YYSTACK_FREE (yymsg);
#endif
  return yyresult;
}
References assign_pin(), assign_pin_list(), avrpart::avr910_devcode, AVR_DESCLEN, avr_dup_part(), avr_free_mem(), avr_free_opcode(), avr_free_part(), AVR_IDLEN, avr_locate_mem(), AVR_MEMDESCLEN, avr_new_memtype(), avr_new_opcode(), avr_new_part(), AVRPART_ALLOWFULLPAGEBITSTREAM, AVRPART_AVR32, AVRPART_ENABLEPAGEPROGRAMMING, AVRPART_HAS_DW, AVRPART_HAS_JTAG, AVRPART_HAS_PDI, AVRPART_HAS_TPI, AVRPART_IS_AT90S1200, AVRPART_PARALLELOK, AVRPART_PSEUDOPARALLEL, AVRPART_SERIALOK, programmer_t::baudrate, avrmem::blocksize, avrpart::bs2, avrpart::bytedelay, avrpart::chip_erase_delay, avrpart::chiperasepolltimeout, avrpart::chiperasepulsewidth, avrpart::chiperasetime, avrpart::cmdexedelay, avrpart::config_file, programmer_t::config_file, programmer_t::conntype, CONNTYPE_PARALLEL, CONNTYPE_SERIAL, CONNTYPE_USB, avrpart::controlstack, CTL_STACK_HVSP, CTL_STACK_PP, CTL_STACK_SIZE, avrpart::ctl_stack_type, current_mem, current_part, current_prog, default_bitclock, default_parallel, default_programmer, default_safemode, default_serial, avrmem::delay, avrpart::desc, avrmem::desc, programmer_t::desc, dup_string(), avrpart::eecr, avrpart::eeprom_instr, EEPROM_INSTR_SIZE, avrpart::flags, avrpart::flash_instr, FLASH_INSTR_SIZE, free(), free_token(), free_tokens(), avrpart::hventerstabdelay, avrpart::hvleavestabdelay, avrpart::hvspcmdexedelay, avrpart::id, programmer_t::id, avrpart::idr, infile, programmer_t::initpgm, programmer_type_t::initpgm, K_DEDICATED, K_IO, K_NO, K_PSEUDO, K_RESET, K_SCK, K_YES, ladd(), avrpart::latchcycles, lcreat(), ldata(), ldestroy_cb(), lfirst(), lineno, avrpart::lineno, programmer_t::lineno, lnext(), locate_part(), locate_programmer(), locate_programmer_type(), lrmv_d(), lrmv_n(), lsize(), malloc(), MAX_STR_CONST, avrmem::max_write_delay, avrpart::mcu_base, avrpart::mem, avrmem::min_write_delay, avrmem::mode, avrmem::num_pages, value_t::number, number_list, avrpart::nvm_base, avrpart::ocdrev, avrmem::offset, avrpart::op, avrmem::op, avrmem::page_size, avrmem::paged, avrpart::pagel, parse_cmdbits(), part_list, PATH_MAX, pgm, PGM_DESCLEN, pgm_dup(), pgm_free(), pgm_new(), PGM_USBSTRINGLEN, programmer_t::pin, PIN_AVR_MISO, PIN_AVR_MOSI, PIN_AVR_RESET, PIN_AVR_SCK, pin_clear_all(), PIN_LED_ERR, PIN_LED_PGM, PIN_LED_RDY, PIN_LED_VFY, pin_name, avrpart::pollindex, avrmem::pollindex, avrpart::pollmethod, avrpart::pollvalue, avrpart::postdelay, avrpart::poweroffdelay, PPI_AVR_BUFF, PPI_AVR_VCC, avrpart::predelay, avrpart::progmodedelay, avrpart::programfusepolltimeout, avrpart::programfusepulsewidth, avrpart::programlockpolltimeout, avrpart::programlockpulsewidth, programmers, PUSH, avrmem::pwroff_after_write, avrpart::rampz, avrmem::readback, avrmem::readsize, RESET_DEDICATED, avrpart::reset_disposition, RESET_IO, avrpart::resetdelay, avrpart::resetdelayms, avrpart::resetdelayus, avrpart::retry_pulse, avrpart::signature, avrmem::size, avrpart::spmcr, avrpart::stabdelay, avrpart::stk500_devcode, value_t::string, string_list, avrpart::synchcycles, avrpart::synchloops, avrpart::timeout, avrpart::togglevtg, programmer_t::usbdev, avrpart::usbpid, programmer_t::usbpid, programmer_t::usbproduct, programmer_t::usbsn, programmer_t::usbvendor, programmer_t::usbvid, V_NUM_REAL, token_t::value, which_opcode(), YY_, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yychar, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror(), YYFINAL, YYINITDEPTH, YYLAST, yylex(), yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, yypact, yypact_value_is_default, yypgoto, YYPOPSTACK, yyr1, yyr2, YYSIZE_T, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yystos, yytable, yytable_value_is_error, YYTERROR, YYTRANSLATE, yyalloc::yyvs_alloc, and yywarning().
Referenced by read_config(), and read_config_builtin().
yywarning()
int yywarning (char * errmsg, ...)
{
  va_list args;
  char message[512];
  va_start(args, errmsg);
  vsnprintf(message, sizeof(message), errmsg, args);
  avrdude_message(MSG_INFO, "%s: warning at %s:%d: %s\n", progname, infile, lineno, message);
  va_end(args);
  return 0;
}
Variable Documentation
current_mem
AVRMEM* current_mem extern
Referenced by init_config(), and yyparse().
current_part
AVRPART* current_part extern
Referenced by init_config(), and yyparse().
current_prog
PROGRAMMER* current_prog extern
Referenced by assign_pin(), assign_pin_list(), init_config(), and yyparse().
infile
const char* infile extern
Referenced by ihex2b(), init_config(), read_config(), read_config_builtin(), igl::readCSV(), srec2b(), yyerror(), yyparse(), and yywarning().
lineno
int lineno extern
Referenced by ihex2b(), init_config(), jtagmkII_chip_erase32(), jtagmkII_close32(), jtagmkII_flash_clear_pagebuffer32(), jtagmkII_flash_erase32(), jtagmkII_flash_lock32(), jtagmkII_flash_write_page32(), jtagmkII_paged_load32(), jtagmkII_paged_write32(), jtagmkII_reset32(), jtagmkII_smc_init32(), read_config(), read_config_builtin(), srec2b(), yyerror(), yyparse(), and yywarning().
number_list
LISTID number_list extern
Referenced by assign_pin_list(), cleanup_config(), init_config(), and yyparse().
string_buf
char string_buf[MAX_STR_CONST] extern
string_buf_ptr
char* string_buf_ptr extern
string_list
LISTID string_list extern
Referenced by cleanup_config(), init_config(), parse_cmdbits(), and yyparse().
yyin
FILE * yyin = NULL extern
Referenced by if(), and read_config().
yylval
YYSTYPE yylval extern