Prusa Slicer: Slic3r::anonymous_namespace{SLAPrintSteps.cpp} Namespace Reference
Slic3r::anonymous_namespace{SLAPrintSteps.cpp} Namespace Reference
Functions
std::string OBJ_STEP_LABELS (size_t idx)
std::string PRINT_STEP_LABELS (size_t idx)
Variables
const std::array< unsigned, slaposCount > OBJ_STEP_LEVELS
const std::array< unsigned, slapsCount > PRINT_STEP_LEVELS
Function Documentation
OBJ_STEP_LABELS()
std::string Slic3r::anonymous_namespace{SLAPrintSteps.cpp}::OBJ_STEP_LABELS (size_t idx)
{
    switch (idx) {
                                            // TRN Status of the SLA print calculation
    case slaposAssembly:             return _u8L("Assembling model from parts");
    case slaposHollowing:            return _u8L("Hollowing model");
    case slaposDrillHoles:           return _u8L("Drilling holes into model.");
    case slaposObjectSlice:          return _u8L("Slicing model");
    case slaposSupportPoints:        return _u8L("Generating support points");
    case slaposSupportTree:          return _u8L("Generating support tree");
    case slaposPad:                  return _u8L("Generating pad");
    case slaposSliceSupports:        return _u8L("Slicing supports");
    default:;
    }
    assert(false);
    return "Out of bounds!";
}
References _u8L, OBJ_STEP_LABELS(), Slic3r::slaposAssembly, Slic3r::slaposDrillHoles, Slic3r::slaposHollowing, Slic3r::slaposObjectSlice, Slic3r::slaposPad, Slic3r::slaposSliceSupports, Slic3r::slaposSupportPoints, and Slic3r::slaposSupportTree.
Referenced by OBJ_STEP_LABELS().
PRINT_STEP_LABELS()
std::string Slic3r::anonymous_namespace{SLAPrintSteps.cpp}::PRINT_STEP_LABELS (size_t idx)
{
    switch (idx) {
    case slapsMergeSlicesAndEval:   return _u8L("Merging slices and calculating statistics");
    case slapsRasterize:            return _u8L("Rasterizing layers");
    default:;
    }
    assert(false); return "Out of bounds!";
}
References _u8L, PRINT_STEP_LABELS(), Slic3r::slapsMergeSlicesAndEval, and Slic3r::slapsRasterize.
Referenced by PRINT_STEP_LABELS().
Variable Documentation
OBJ_STEP_LEVELS
const std::array<unsigned, slaposCount> Slic3r::anonymous_namespace{SLAPrintSteps.cpp}::OBJ_STEP_LEVELS
Initial value:
= {
    13,
    13,
    13,
    13,
    13,
    13,
    11,
    11,
}
PRINT_STEP_LEVELS
const std::array<unsigned, slapsCount> Slic3r::anonymous_namespace{SLAPrintSteps.cpp}::PRINT_STEP_LEVELS
Initial value:
= {
    10,
    90,
}