Prusa Slicer: Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid Class Reference
Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid Class Reference
#include <src/libslic3r/Fill/Lightning/DistanceField.hpp>
Public Member Functions
UnsupportedPointsGrid ()=default
void initialize (const std::vector< UnsupportedCell > &unsupported_points, const std::function< Point(const Point &)> &map_cell_to_grid)
size_t size () const
size_t find_cell_idx (const Point &grid_addr)
void mark_erased (const Point &grid_addr)
Private Member Functions
size_t map_to_flat_array (const Point &loc) const
Private Attributes
size_t m_size = 0
BoundingBox m_grid_range
Point m_grid_size
std::vector< size_t > m_data
std::vector< bool > m_data_erased
Detailed Description
Links the unsupported points to a grid point, so that we can quickly look up the cell belonging to a certain position in the grid.
Constructor & Destructor Documentation
UnsupportedPointsGrid()
Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::UnsupportedPointsGrid () default
Member Function Documentation
find_cell_idx()
size_t Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::find_cell_idx (const Point & grid_addr) inline
        {
            if (!m_grid_range.contains(grid_addr))
                return std::numeric_limits<size_t>::max();
            if (const size_t flat_idx = map_to_flat_array(grid_addr); !m_data_erased[flat_idx]) {
                assert(m_data[flat_idx] != std::numeric_limits<size_t>::max());
                return m_data[flat_idx];
            }
            return std::numeric_limits<size_t>::max();
        }
References Slic3r::BoundingBoxBase< PointType, APointsType >::contains(), m_data, m_data_erased, m_grid_range, and map_to_flat_array().
initialize()
void Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::initialize (const std::vector< UnsupportedCell > & unsupported_points, const std::function< Point(const Point &)> & map_cell_to_grid) inline
        {
            if (unsupported_points.empty())
                return;
            BoundingBox unsupported_points_bbox;
            for (const UnsupportedCell &cell : unsupported_points)
                unsupported_points_bbox.merge(cell.loc);
            m_size        = unsupported_points.size();
            m_grid_range  = BoundingBox(map_cell_to_grid(unsupported_points_bbox.min), map_cell_to_grid(unsupported_points_bbox.max));
            m_grid_size   = m_grid_range.size() + Point::Ones();
            m_data.assign(m_grid_size.y() * m_grid_size.x(), std::numeric_limits<size_t>::max());
            m_data_erased.assign(m_grid_size.y() * m_grid_size.x(), true);
            for (size_t cell_idx = 0; cell_idx < unsupported_points.size(); ++cell_idx) {
                const size_t flat_idx   = map_to_flat_array(map_cell_to_grid(unsupported_points[cell_idx].loc));
                assert(m_data[flat_idx] == std::numeric_limits<size_t>::max());
                m_data[flat_idx]        = cell_idx;
                m_data_erased[flat_idx] = false;
            }
        }
References m_data, m_data_erased, m_grid_range, m_grid_size, m_size, map_to_flat_array(), Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::merge(), Slic3r::BoundingBoxBase< PointType, APointsType >::min, and Slic3r::BoundingBoxBase< PointType, APointsType >::size().
map_to_flat_array()
size_t Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::map_to_flat_array (const Point & loc) const inline private
        {
            const Point  offset_loc = loc - m_grid_range.min;
            const size_t flat_idx   = m_grid_size.x() * offset_loc.y() + offset_loc.x();
            assert(offset_loc.x() >= 0 && offset_loc.y() >= 0);
            assert(flat_idx < size_t(m_grid_size.y() * m_grid_size.x()));
            return flat_idx;
        }
References m_grid_range, m_grid_size, and Slic3r::BoundingBoxBase< PointType, APointsType >::min.
Referenced by find_cell_idx(), initialize(), and mark_erased().
mark_erased()
void Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::mark_erased (const Point & grid_addr) inline
        {
            assert(m_grid_range.contains(grid_addr));
            if (!m_grid_range.contains(grid_addr))
                return;
            const size_t flat_idx = map_to_flat_array(grid_addr);
            assert(!m_data_erased[flat_idx] && m_data[flat_idx] != std::numeric_limits<size_t>::max());
            assert(m_size != 0);
            m_data_erased[flat_idx] = true;
            --m_size;
        }
References Slic3r::BoundingBoxBase< PointType, APointsType >::contains(), m_data, m_data_erased, m_grid_range, m_size, and map_to_flat_array().
size()
size_t Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::size () const inline
{ return m_size; }
References m_size.
Member Data Documentation
m_data
std::vector<size_t> Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::m_data private
Referenced by find_cell_idx(), initialize(), and mark_erased().
m_data_erased
std::vector<bool> Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::m_data_erased private
Referenced by find_cell_idx(), initialize(), and mark_erased().
m_grid_range
BoundingBox Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::m_grid_range private
Referenced by find_cell_idx(), initialize(), map_to_flat_array(), and mark_erased().
m_grid_size
Point Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::m_grid_size private
Referenced by initialize(), and map_to_flat_array().
m_size
size_t Slic3r::FillLightning::DistanceField::UnsupportedPointsGrid::m_size = 0 private
Referenced by initialize(), mark_erased(), and size().
The documentation for this class was generated from the following file:
src/libslic3r/Fill/Lightning/DistanceField.hpp