Prusa Slicer: marchsq::__impl Namespace Reference
marchsq::__impl Namespace Reference
Classes
class Grid
Typedefs
template<class T >
using RasterTraits = _RasterTraits< std::decay_t< T > >
template<class T >
using TRasterValue = typename RasterTraits< T >::ValueType
Enumerations
enum class SquareTag : uint8_t {
none , a , b , ab ,
c , ac , bc , abc ,
d , ad , bd , abd ,
cd , acd , bcd , full
}
enum class Dir : uint8_t {
left , down , right , up ,
none
}
Functions
template<class T >
size_t rows (const T &raster)
template<class T >
size_t cols (const T &raster)
template<class T >
TRasterValue< T > isoval (const T &rst, const Coord &crd)
template<class ExecutionPolicy , class It , class Fn >
void for_each (ExecutionPolicy &&policy, It from, It to, Fn &&fn)
template<class E >
constexpr std::underlying_type_t< E > _t (E e) noexcept
Coord step (const Coord &crd, Dir d)
template<class Raster , class ExecutionPolicy >
std::vector< marchsq::Ring > execute_with_policy (ExecutionPolicy &&policy, const Raster &raster, TRasterValue< Raster > isoval, Coord windowsize={})
template<class Raster >
std::vector< marchsq::Ring > execute (const Raster &raster, TRasterValue< Raster > isoval, Coord windowsize={})
Variables
static const constexpr Dir NEXT_CCW []
static const constexpr uint8_t PREV_CCW []
const constexpr uint8_t DIRMASKS []
Typedef Documentation
RasterTraits
template<class T > using marchsq::__impl::RasterTraits = typedef _RasterTraits<std::decay_t<T> >
TRasterValue
template<class T > using marchsq::__impl::TRasterValue = typedef typename RasterTraits<T>::ValueType
Enumeration Type Documentation
Dir
enum class marchsq::__impl::Dir : uint8_t strong
Enumerator
left
down
right
up
none
: uint8_t { left, down, right, up, none};
SquareTag
enum class marchsq::__impl::SquareTag : uint8_t strong
Enumerator
none
a
b
ab
c
ac
bc
abc
d
ad
bd
abd
cd
acd
bcd
full
                     : uint8_t {
//     0, 1, 2,  3, 4,  5,  6,   7, 8,  9, 10,  11, 12,  13,  14,  15
    none, a, b, ab, c, ac, bc, abc, d, ad, bd, abd, cd, acd, bcd, full
};
Function Documentation
_t()
template<class E > constexpr std::underlying_type_t< E > marchsq::__impl::_t (E e) constexpr noexcept
{
    return static_cast<std::underlying_type_t<E>>(e);
}
Referenced by marchsq::__impl::Grid< Rst >::is_visited(), marchsq::__impl::Grid< Rst >::scan_rings(), and marchsq::__impl::Grid< Rst >::set_visited().
cols()
template<class T > size_t marchsq::__impl::cols (const T & raster)
{
    return RasterTraits<T>::cols(raster);
}
References marchsq::_RasterTraits< T, Enable >::cols().
Referenced by marchsq::__impl::Grid< Rst >::edge(), and marchsq::__impl::Grid< Rst >::is_within().
execute()
template<class Raster > std::vector< marchsq::Ring > marchsq::__impl::execute (const Raster & raster, TRasterValue< Raster > isoval, Coord windowsize = {})
                                                                     {})
{
    return execute_with_policy(nullptr, raster, isoval, windowsize);
}
References execute().
Referenced by execute().
execute_with_policy()
template<class Raster , class ExecutionPolicy > std::vector< marchsq::Ring > marchsq::__impl::execute_with_policy (ExecutionPolicy && policy, const Raster & raster, TRasterValue< Raster > isoval, Coord windowsize = {})
                                                                  {})
{
    if (!rows(raster) || !cols(raster)) return {};
    size_t ratio = cols(raster) / rows(raster);
    if (!windowsize.r) windowsize.r = 2;
    if (!windowsize.c)
        windowsize.c = std::max(2l, long(windowsize.r * ratio));
    Coord overlap{1};
    Grid<Raster> grid{raster, windowsize, overlap};
    grid.tag_grid(std::forward<ExecutionPolicy>(policy), isoval);
    std::vector<marchsq::Ring> rings = grid.scan_rings();
    grid.interpolate_rings(std::forward<ExecutionPolicy>(policy), rings, isoval);
    return rings;
}
References execute_with_policy().
Referenced by execute_with_policy().
for_each()
template<class ExecutionPolicy , class It , class Fn > void marchsq::__impl::for_each (ExecutionPolicy && policy, It from, It to, Fn && fn)
{
    _Loop<ExecutionPolicy>::for_each(from, to, fn);
}
References marchsq::_Loop< ExecutionPolicy, Enable >::for_each().
Referenced by marchsq::__impl::Grid< Rst >::interpolate_rings(), and marchsq::__impl::Grid< Rst >::tag_grid().
isoval()
template<class T > TRasterValue< T > marchsq::__impl::isoval (const T & rst, const Coord & crd)
{
    return RasterTraits<T>::get(rst, crd.r, crd.c);
}
References marchsq::Coord::c, marchsq::_RasterTraits< T, Enable >::get(), and marchsq::Coord::r.
Referenced by marchsq::__impl::Grid< Rst >::get_tag_for_cell(), marchsq::__impl::Grid< Rst >::CellIt::operator*(), and marchsq::__impl::Grid< Rst >::tag_grid().
rows()
template<class T > size_t marchsq::__impl::rows (const T & raster)
{
    return RasterTraits<T>::rows(raster);
}
References marchsq::_RasterTraits< T, Enable >::rows().
Referenced by marchsq::__impl::Grid< Rst >::edge(), and marchsq::__impl::Grid< Rst >::is_within().
step()
Coord marchsq::__impl::step (const Coord & crd, Dir d) inline
{
    uint8_t dd = DIRMASKS[uint8_t(d)];
    return {crd.r - 1 + (dd & 0x0f), crd.c - 1 + (dd >> 4)};
}
References marchsq::Coord::c, d, DIRMASKS, and marchsq::Coord::r.
Referenced by marchsq::__impl::Grid< Rst >::CellIt::operator++(), and marchsq::__impl::Grid< Rst >::scan_rings().
Variable Documentation
DIRMASKS
const constexpr uint8_t marchsq::__impl::DIRMASKS[] constexpr
Initial value:
= {
     0x01,  0x12, 0x21,  0x10,  0x00
}
Referenced by step().
NEXT_CCW
const constexpr Dir marchsq::__impl::NEXT_CCW[] static constexpr
Initial value:
= {
     Dir::none,
     Dir::left,
     Dir::down,
     Dir::left,
     Dir::right,
     Dir::none,
     Dir::down,
     Dir::left,
     Dir::up,
     Dir::up,
     Dir::none,
     Dir::up,
     Dir::right,
     Dir::right,
     Dir::down,
     Dir::none
}
Referenced by marchsq::__impl::Grid< Rst >::next_dir().
PREV_CCW
const constexpr uint8_t marchsq::__impl::PREV_CCW[] static constexpr
Initial value:
= {
     1 << _t(Dir::none),
     1 << _t(Dir::up),
     1 << _t(Dir::left),
     1 << _t(Dir::left),
     1 << _t(Dir::down),
     1 << _t(Dir::up) | 1 << _t(Dir::down),
     1 << _t(Dir::down),
     1 << _t(Dir::down),
     1 << _t(Dir::right),
     1 << _t(Dir::up),
     1 << _t(Dir::left) | 1 << _t(Dir::right),
     1 << _t(Dir::left),
     1 << _t(Dir::right),
     1 << _t(Dir::up),
     1 << _t(Dir::right),
     1 << _t(Dir::none)
}
Referenced by marchsq::__impl::Grid< Rst >::is_visited().