Prusa Slicer: boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize > Class Template Reference
boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize > Class Template Reference
A class that allows to create a temporary wide or narrow UTF strings from wide or narrow UTF source.
#include <src/boost/nowide/stackstring.hpp>
Public Types
typedef CharOut output_char
typedef CharIn input_char
Public Member Functions
basic_stackstring (basic_stackstring const &other)
void swap (basic_stackstring &other)
basic_stackstring & operator= (basic_stackstring const &other)
basic_stackstring ()
bool convert (input_char const *input)
bool convert (input_char const *begin, input_char const *end)
output_char * c_str ()
output_char const * c_str () const
void clear ()
~basic_stackstring ()
Static Public Attributes
static const size_t buffer_size = BufferSize
Static Private Member Functions
static size_t get_space (size_t insize, size_t outsize, size_t in)
Private Attributes
output_char buffer_ [buffer_size]
output_char * mem_buffer_
Detailed Description
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256>
class boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >
A class that allows to create a temporary wide or narrow UTF strings from wide or narrow UTF source.
It uses on stack buffer of the string is short enough and allocated a buffer on the heap if the size of the buffer is too small
Member Typedef Documentation
input_char
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> typedef CharIn boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::input_char
output_char
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> typedef CharOut boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::output_char
Constructor & Destructor Documentation
basic_stackstring() [1/2]
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::basic_stackstring (basic_stackstring< CharOut, CharIn, BufferSize > const & other) inline
                                                      :
    mem_buffer_(0)
    {
        clear();
        if(other.mem_buffer_) {
            size_t len = 0;
            while(other.mem_buffer_[len])
                len ++;
            mem_buffer_ = new output_char[len + 1];
            memcpy(mem_buffer_,other.mem_buffer_,sizeof(output_char) * (len+1));
        }
        else {
            memcpy(buffer_,other.buffer_,buffer_size * sizeof(output_char));
        }
    }
References boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_, boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_size, boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::clear(), and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::mem_buffer_.
basic_stackstring() [2/2]
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::basic_stackstring () inline
                        : mem_buffer_(0)
    {
    }
~basic_stackstring()
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::~basic_stackstring () inline
    {
        clear();
    }
References boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::clear().
Member Function Documentation
c_str() [1/2]
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> output_char * boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::c_str () inline
    {
        if(mem_buffer_)
            return mem_buffer_;
        return buffer_;
    }
References boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_, and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::mem_buffer_.
c_str() [2/2]
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> output_char const * boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::c_str () const inline
    {
        if(mem_buffer_)
            return mem_buffer_;
        return buffer_;
    }
References boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_, and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::mem_buffer_.
clear()
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> void boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::clear () inline
    {
        if(mem_buffer_) {
            delete [] mem_buffer_;
            mem_buffer_=0;
        }
        buffer_[0] = 0;
    }
References boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_, and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::mem_buffer_.
Referenced by boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::basic_stackstring(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::~basic_stackstring(), and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert().
convert() [1/2]
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> bool boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert (input_char const * begin, input_char const * end) inline
    {
        clear();
        size_t space = get_space(sizeof(input_char),sizeof(output_char),end - begin) + 1;
        if(space <= buffer_size) {
            if(basic_convert(buffer_,buffer_size,begin,end))
                return true;
            clear();
            return false;
        }
        else {
            mem_buffer_ = new output_char[space];
            if(!basic_convert(mem_buffer_,space,begin,end)) {
                clear();
                return false;
            }
            return true;
        }
    }
References boost::nowide::basic_convert(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_, boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_size, boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::clear(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::get_space(), and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::mem_buffer_.
convert() [2/2]
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> bool boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert (input_char const * input) inline
    {
        return convert(input,details::basic_strend(input));
    }
References boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert(), and input().
Referenced by boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert().
get_space()
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> static size_t boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::get_space (size_t insize, size_t outsize, size_t in) inline static private
    {
        if(insize <= outsize)
            return in;
        else if(insize == 2 && outsize == 1)
            return 3 * in;
        else if(insize == 4 && outsize == 1)
            return 4 * in;
        else  // if(insize == 4 && outsize == 2)
            return 2 * in;
    }
Referenced by boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert().
operator=()
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> basic_stackstring & boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::operator= (basic_stackstring< CharOut, CharIn, BufferSize > const & other) inline
    {
        if(this != &other) {
            basic_stackstring tmp(other);
            swap(tmp);
        }
        return *this;
    }
References boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::swap().
swap()
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> void boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::swap (basic_stackstring< CharOut, CharIn, BufferSize > & other) inline
    {
        std::swap(mem_buffer_,other.mem_buffer_);
        for(size_t i=0;i<buffer_size;i++)
            std::swap(buffer_[i],other.buffer_[i]);
    }
References boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_, boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_size, and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::mem_buffer_.
Referenced by boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::operator=().
Member Data Documentation
buffer_
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> output_char boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_[buffer_size] private
Referenced by boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::basic_stackstring(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::c_str(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::c_str(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::clear(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert(), and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::swap().
buffer_size
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> const size_t boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::buffer_size = BufferSize static
Referenced by boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::basic_stackstring(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert(), and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::swap().
mem_buffer_
template<typename CharOut = wchar_t, typename CharIn = char, size_t BufferSize = 256> output_char* boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::mem_buffer_ private
Referenced by boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::basic_stackstring(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::c_str(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::c_str(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::clear(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::convert(), and boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >::swap().
The documentation for this class was generated from the following file:
src/boost/nowide/stackstring.hpp