Prusa Slicer: Slic3r::GUI::SLAImportJob Class Reference
Slic3r::GUI::SLAImportJob Class Reference
#include <src/slic3r/GUI/Jobs/SLAImportJob.hpp>
Classes
class priv
Public Member Functions
void prepare ()
void process (Ctl &ctl) override
void finalize (bool canceled, std::exception_ptr &) override
SLAImportJob (const SLAImportJobView *)
~SLAImportJob ()
void reset ()
Private Types
using Sel = SLAImportJobView::Sel
using Quality = SLAImportQuality
Private Attributes
std::unique_ptr< priv > p
Detailed Description
Member Typedef Documentation
Quality
using Slic3r::GUI::SLAImportJob::Quality = SLAImportQuality private
Sel
using Slic3r::GUI::SLAImportJob::Sel = SLAImportJobView::Sel private
Constructor & Destructor Documentation
SLAImportJob()
Slic3r::GUI::SLAImportJob::SLAImportJob (const SLAImportJobView * view)
    : p{std::make_unique<priv>(wxGetApp().plater(), view)}
{
    prepare();
}
References prepare().
~SLAImportJob()
Slic3r::GUI::SLAImportJob::~SLAImportJob () default
Member Function Documentation
finalize()
void Slic3r::GUI::SLAImportJob::finalize (bool canceled, std::exception_ptr & eptr) override virtual
Reimplemented from Slic3r::GUI::Job.
{
    // Ignore the arrange result if aborted.
    if (canceled || eptr)
        return;
    if (!p->err.empty()) {
        show_error(p->plater, p->err);
        p->err = "";
        return;
    }
    std::string name = wxFileName(p->path).GetName().ToUTF8().data();
    if (p->profile.empty()) {
        p->plater->get_notification_manager()->push_notification(
        NotificationType::CustomNotification,
        NotificationManager::NotificationLevel::WarningNotificationLevel,
            _u8L("The imported SLA archive did not contain any presets. "
               "The current SLA presets were used as fallback."));
    }
    if (p->sel != Sel::modelOnly) {
        if (p->profile.empty())
            p->profile = p->plater->sla_print().full_print_config();
        const ModelObjectPtrs& objects = p->plater->model().objects;
        for (auto object : objects)
            if (object->volumes.size() > 1)
            {
                Slic3r::GUI::show_info(nullptr,
                                       _(L("You cannot load SLA project with a multi-part object on the bed")) + "\n\n" +
                                       _(L("Please check your object list before preset changing.")),
                                       _(L("Attention!")) );
                return;
            }
        DynamicPrintConfig config = {};
        config.apply(SLAFullPrintConfig::defaults());
        config += std::move(p->profile);
        if (Preset::printer_technology(config) == ptSLA) {
            wxGetApp().preset_bundle->load_config_model(name, std::move(config));
            p->plater->check_selected_presets_visibility(ptSLA);
            wxGetApp().load_current_presets();
        } else {
            p->plater->get_notification_manager()->push_notification(
                NotificationType::CustomNotification,
                NotificationManager::NotificationLevel::WarningNotificationLevel,
                _u8L("The profile in the imported archive is corrupted and will not be loaded."));
        }
    }
    if (!p->mesh.empty()) {
        bool is_centered = false;
        p->plater->sidebar().obj_list()->load_mesh_object(TriangleMesh{std::move(p->mesh)},
                                                          name, is_centered);
    } else if (p->sel == Sel::modelOnly || p->sel == Sel::modelAndProfile) {
        p->plater->get_notification_manager()->push_notification(
            NotificationType::CustomNotification,
            NotificationManager::NotificationLevel::WarningNotificationLevel,
            _u8L("No object could be retrieved from the archive. The slices might be corrupted or missing."));
    }
    if (! p->config_substitutions.empty())
        show_substitutions_info(p->config_substitutions, p->path.ToUTF8().data());
    reset();
}
References _, _u8L, Slic3r::ConfigBase::apply(), Slic3r::GUI::CustomNotification, L, p, Slic3r::Preset::printer_technology(), Slic3r::ptSLA, reset(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::show_substitutions_info(), and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
prepare()
void Slic3r::GUI::SLAImportJob::prepare ()
{
    reset();
    auto path  = p->import_dlg->get_path();
    auto nm    = wxFileName(path);
    p->path    = !nm.Exists(wxFILE_EXISTS_REGULAR) ? "" : nm.GetFullPath();
    if (p->path.empty()) {
        p->err = _u8L("The file does not exist.");
        return;
    }
    p->sel     = p->import_dlg->get_selection();
    p->quality = p->import_dlg->get_quality();
    p->config_substitutions.clear();
}
References _u8L, p, and reset().
Referenced by SLAImportJob().
process()
void Slic3r::GUI::SLAImportJob::process (Ctl & ctl) override virtual
Implements Slic3r::GUI::Job.
{
    if (p->path.empty() || ! p->err.empty()) return;
    auto statustxt = _u8L("Importing SLA archive");
    ctl.update_status(0, statustxt);
    auto progr = [&ctl, &statustxt](int s) {
        if (s < 100)
            ctl.update_status(int(s), statustxt);
        return !ctl.was_canceled();
    };
    std::string path = p->path.ToUTF8().data();
    std::string format_id = p->import_dlg->get_archive_format();
    try {
        switch (p->sel) {
        case Sel::modelAndProfile:
        case Sel::modelOnly:
            p->config_substitutions = import_sla_archive(path,
                                                         format_id,
                                                         p->mesh,
                                                         p->profile,
                                                         p->quality, progr);
            break;
        case Sel::profileOnly:
            p->config_substitutions = import_sla_archive(path, format_id,
                                                         p->profile);
            break;
        }
    } catch (MissingProfileError &) {
        p->err = _u8L("The SLA archive doesn't contain any presets. "
                      "Please activate some SLA printer preset first before "
                      "importing that SLA archive.");
    } catch (ReaderUnimplementedError &) {
        p->err = _u8L("Import is unavailable for this archive format.");
    }catch (std::exception &ex) {
        p->err = ex.what();
    }
    ctl.update_status(100, ctl.was_canceled() ? _u8L("Importing canceled.") :
                                                _u8L("Importing done."));
}
References _u8L, Slic3r::import_sla_archive(), p, Slic3r::GUI::Job::Ctl::update_status(), and Slic3r::GUI::Job::Ctl::was_canceled().
reset()
void Slic3r::GUI::SLAImportJob::reset ()
{
    p->sel     = Sel::modelAndProfile;
    p->mesh    = {};
    p->profile = p->plater->sla_print().full_print_config();
    p->quality = SLAImportQuality::Balanced;
    p->path.Clear();
    p->err     = "";
}
References Slic3r::Balanced, and p.
Referenced by finalize(), and prepare().
Member Data Documentation
p
std::unique_ptr<priv> Slic3r::GUI::SLAImportJob::p private
Referenced by finalize(), prepare(), process(), and reset().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/SLAImportJob.hpp
src/slic3r/GUI/Jobs/SLAImportJob.cpp