Prusa Slicer: Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true > Struct Template Reference
Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true > Struct Template Reference
#include <src/eigen/Eigen/src/SVD/JacobiSVD.h>
Public Types
typedef JacobiSVD< MatrixType, QRPreconditioner > SVD
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
Static Public Member Functions
static bool run (typename SVD::WorkMatrixType &work_matrix, SVD &svd, Index p, Index q, RealScalar &maxDiagEntry)
Detailed Description
template<typename MatrixType, int QRPreconditioner>
struct Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >
Member Typedef Documentation
RealScalar
template<typename MatrixType , int QRPreconditioner> typedef MatrixType::RealScalar Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::RealScalar
Scalar
template<typename MatrixType , int QRPreconditioner> typedef MatrixType::Scalar Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::Scalar
SVD
template<typename MatrixType , int QRPreconditioner> typedef JacobiSVD<MatrixType, QRPreconditioner> Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::SVD
Member Function Documentation
run()
template<typename MatrixType , int QRPreconditioner> static bool Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run (typename SVD::WorkMatrixType & work_matrix, SVD & svd, Index p, Index q, RealScalar & maxDiagEntry) inline static
  {
    using std::sqrt;
    using std::abs;
    Scalar z;
    JacobiRotation<Scalar> rot;
    RealScalar n = sqrt(numext::abs2(work_matrix.coeff(p,p)) + numext::abs2(work_matrix.coeff(q,p)));
    const RealScalar considerAsZero = (std::numeric_limits<RealScalar>::min)();
    const RealScalar precision = NumTraits<Scalar>::epsilon();
    if(n==0)
    {
      // make sure first column is zero
      work_matrix.coeffRef(p,p) = work_matrix.coeffRef(q,p) = Scalar(0);
      if(abs(numext::imag(work_matrix.coeff(p,q)))>considerAsZero)
      {
        // work_matrix.coeff(p,q) can be zero if work_matrix.coeff(q,p) is not zero but small enough to underflow when computing n
        z = abs(work_matrix.coeff(p,q)) / work_matrix.coeff(p,q);
        work_matrix.row(p) *= z;
        if(svd.computeU()) svd.m_matrixU.col(p) *= conj(z);
      }
      if(abs(numext::imag(work_matrix.coeff(q,q)))>considerAsZero)
      {
        z = abs(work_matrix.coeff(q,q)) / work_matrix.coeff(q,q);
        work_matrix.row(q) *= z;
        if(svd.computeU()) svd.m_matrixU.col(q) *= conj(z);
      }
      // otherwise the second row is already zero, so we have nothing to do.
    }
    else
    {
      rot.c() = conj(work_matrix.coeff(p,p)) / n;
      rot.s() = work_matrix.coeff(q,p) / n;
      work_matrix.applyOnTheLeft(p,q,rot);
      if(svd.computeU()) svd.m_matrixU.applyOnTheRight(p,q,rot.adjoint());
      if(abs(numext::imag(work_matrix.coeff(p,q)))>considerAsZero)
      {
        z = abs(work_matrix.coeff(p,q)) / work_matrix.coeff(p,q);
        work_matrix.col(q) *= z;
        if(svd.computeV()) svd.m_matrixV.col(q) *= z;
      }
      if(abs(numext::imag(work_matrix.coeff(q,q)))>considerAsZero)
      {
        z = abs(work_matrix.coeff(q,q)) / work_matrix.coeff(q,q);
        work_matrix.row(q) *= z;
        if(svd.computeU()) svd.m_matrixU.col(q) *= conj(z);
      }
    }
    // update largest diagonal entry
    maxDiagEntry = numext::maxi<RealScalar>(maxDiagEntry,numext::maxi<RealScalar>(abs(work_matrix.coeff(p,p)), abs(work_matrix.coeff(q,q))));
    // and check whether the 2x2 block is already diagonal
    RealScalar threshold = numext::maxi<RealScalar>(considerAsZero, precision * maxDiagEntry);
    return abs(work_matrix.coeff(p,q))>threshold || abs(work_matrix.coeff(q,p)) > threshold;
  }
References Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::c(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::coeffRef(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::computeU(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::computeV(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_matrixU, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_matrixV, Eigen::JacobiRotation< Scalar >::s(), and sqrt().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/SVD/JacobiSVD.h