Prusa Slicer: Slic3r::GUI::MsgDialog Struct Reference
Slic3r::GUI::MsgDialog Struct Reference
#include <src/slic3r/GUI/MsgDialog.hpp>
Public Member Functions
MsgDialog (MsgDialog &&)=delete
MsgDialog (const MsgDialog &)=delete
MsgDialog & operator= (MsgDialog &&)=delete
MsgDialog & operator= (const MsgDialog &)=delete
virtual ~MsgDialog ()=default
void SetButtonLabel (wxWindowID btn_id, const wxString &label, bool set_focus=false)
Protected Types
enum {
CONTENT_WIDTH = 70 , CONTENT_MAX_HEIGHT = 60 , BORDER = 30 , VERT_SPACING = 15 ,
HORIZ_SPACING = 5
}
Protected Member Functions
MsgDialog (wxWindow *parent, const wxString &title, const wxString &headline, long style=wxOK, wxBitmap bitmap=wxNullBitmap)
wxButton * add_button (wxWindowID btn_id, bool set_focus=false, const wxString &label=wxString())
wxButton * get_button (wxWindowID btn_id)
void apply_style (long style)
void finalize ()
Protected Attributes
wxFont boldfont
wxBoxSizer * content_sizer
wxBoxSizer * btn_sizer
wxStaticBitmap * logo
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
CONTENT_WIDTH
CONTENT_MAX_HEIGHT
BORDER
VERT_SPACING
HORIZ_SPACING
       {
    CONTENT_WIDTH = 70,//50,
    CONTENT_MAX_HEIGHT = 60,
    BORDER = 30,
    VERT_SPACING = 15,
    HORIZ_SPACING = 5,
  };
Constructor & Destructor Documentation
MsgDialog() [1/3]
Slic3r::GUI::MsgDialog::MsgDialog (MsgDialog &&) delete
MsgDialog() [2/3]
Slic3r::GUI::MsgDialog::MsgDialog (const MsgDialog &) delete
~MsgDialog()
virtual Slic3r::GUI::MsgDialog::~MsgDialog () virtual default
MsgDialog() [3/3]
Slic3r::GUI::MsgDialog::MsgDialog (wxWindow * parent, const wxString & title, const wxString & headline, long style = wxOK, wxBitmap bitmap = wxNullBitmap) protected
  : wxDialog(parent ? parent : dynamic_cast<wxWindow*>(wxGetApp().mainframe), wxID_ANY, title, wxDefaultPosition, wxDefaultSize, wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER)
  , boldfont(wxGetApp().normal_font())
  , content_sizer(new wxBoxSizer(wxVERTICAL))
  , btn_sizer(new wxBoxSizer(wxHORIZONTAL))
{
  boldfont.SetWeight(wxFONTWEIGHT_BOLD);
    this->SetFont(wxGetApp().normal_font());
    this->CenterOnParent();
    auto *main_sizer = new wxBoxSizer(wxVERTICAL);
  auto *topsizer = new wxBoxSizer(wxHORIZONTAL);
  auto *rightsizer = new wxBoxSizer(wxVERTICAL);
  auto *headtext = new wxStaticText(this, wxID_ANY, headline);
  headtext->SetFont(boldfont);
    headtext->Wrap(CONTENT_WIDTH*wxGetApp().em_unit());
  rightsizer->Add(headtext);
  rightsizer->AddSpacer(VERT_SPACING);
  rightsizer->Add(content_sizer, 1, wxEXPAND);
    btn_sizer->AddStretchSpacer();
  logo = new wxStaticBitmap(this, wxID_ANY, bitmap.IsOk() ? bitmap : wxNullBitmap);
  topsizer->Add(logo, 0, wxALL, BORDER);
  topsizer->Add(rightsizer, 1, wxTOP | wxBOTTOM | wxRIGHT | wxEXPAND, BORDER);
    main_sizer->Add(topsizer, 1, wxEXPAND);
    main_sizer->Add(new StaticLine(this), 0, wxEXPAND | wxLEFT | wxRIGHT, HORIZ_SPACING);
    main_sizer->Add(btn_sizer, 0, wxALL | wxEXPAND, VERT_SPACING);
    apply_style(style);
  SetSizerAndFit(main_sizer);
}
References apply_style(), boldfont, BORDER, btn_sizer, content_sizer, CONTENT_WIDTH, em_unit(), HORIZ_SPACING, logo, style, and VERT_SPACING.
Member Function Documentation
add_button()
wxButton * Slic3r::GUI::MsgDialog::add_button (wxWindowID btn_id, bool set_focus = false, const wxString & label = wxString()) protected
{
    wxButton* btn = new wxButton(this, btn_id, label);
    if (set_focus) {
        btn->SetFocus();
        // For non-MSW platforms SetFocus is not enought to use it as default, when the dialog is closed by ENTER
        // We have to set this button as the (permanently) default one in its dialog
        // See https://twitter.com/ZMelmed/status/1472678454168539146
        btn->SetDefault();
    }
    btn_sizer->Add(btn, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, HORIZ_SPACING);
    btn->Bind(wxEVT_BUTTON, [this, btn_id](wxCommandEvent&) { this->EndModal(btn_id); });
    return btn;
};
References btn_sizer, HORIZ_SPACING, and wxEVT_BUTTON.
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and apply_style().
apply_style()
void Slic3r::GUI::MsgDialog::apply_style (long style) protected
{
    if (style & wxOK)       add_button(wxID_OK, true);
    if (style & wxYES)      add_button(wxID_YES,   !(style & wxNO_DEFAULT));
    if (style & wxNO)       add_button(wxID_NO,     (style & wxNO_DEFAULT));
    if (style & wxCANCEL)   add_button(wxID_CANCEL, (style & wxCANCEL_DEFAULT));
    std::string icon_name = style & wxICON_WARNING        ? "exclamation" :
                            style & wxICON_INFORMATION    ? "info"        :
                            style & wxICON_QUESTION       ? "question"    : "PrusaSlicer";
    logo->SetBitmap(*get_bmp_bundle(icon_name, 64));
}
References add_button(), get_bmp_bundle(), logo, and style.
Referenced by MsgDialog().
finalize()
void Slic3r::GUI::MsgDialog::finalize () protected
{
    wxGetApp().UpdateDlgDarkUI(this);
    Fit();
    this->CenterOnParent();
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
get_button()
wxButton * Slic3r::GUI::MsgDialog::get_button (wxWindowID btn_id) protected
{
    return static_cast<wxButton*>(FindWindowById(btn_id, this));
}
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), and SetButtonLabel().
operator=() [1/2]
MsgDialog & Slic3r::GUI::MsgDialog::operator= (const MsgDialog &) delete
operator=() [2/2]
MsgDialog & Slic3r::GUI::MsgDialog::operator= (MsgDialog &&) delete
SetButtonLabel()
void Slic3r::GUI::MsgDialog::SetButtonLabel (wxWindowID btn_id, const wxString & label, bool set_focus = false)
{
    if (wxButton* btn = get_button(btn_id)) {
        btn->SetLabel(label);
        if (set_focus)
            btn->SetFocus();
    }
}
References get_button().
Referenced by Slic3r::GUI::GUI_App::check_older_app_config(), Slic3r::GUI::ObjectList::del_from_cut_object(), and Slic3r::GUI::Plater::priv::delete_object_from_model().
Member Data Documentation
boldfont
wxFont Slic3r::GUI::MsgDialog::boldfont protected
Referenced by Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), MsgDialog(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), and Slic3r::GUI::MsgUpdateForced::MsgUpdateForced().
btn_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::btn_sizer protected
Referenced by MsgDialog(), and add_button().
content_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::content_sizer protected
Referenced by Slic3r::GUI::AppUpdateAvailableDialog::AppUpdateAvailableDialog(), Slic3r::GUI::AppUpdateDownloadDialog::AppUpdateDownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgDataLegacy::MsgDataLegacy(), MsgDialog(), Slic3r::GUI::MsgNoAppUpdates::MsgNoAppUpdates(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
logo
wxStaticBitmap* Slic3r::GUI::MsgDialog::logo protected
Referenced by Slic3r::GUI::ErrorDialog::ErrorDialog(), MsgDialog(), and apply_style().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/MsgDialog.hpp
src/slic3r/GUI/MsgDialog.cpp