Prusa Slicer: Slic3r::GUI::NotificationManager Class Reference
Slic3r::GUI::NotificationManager Class Reference
#include <src/slic3r/GUI/NotificationManager.hpp>
Classes
struct DelayedNotification
class ExportFinishedNotification
class HintNotification
struct NotificationData
class NotificationIDProvider
class ObjectIDNotification
class PlaterWarningNotification
class PopNotification
class PrintHostUploadNotification
class ProgressBarNotification
class ProgressBarWithCancelNotification
class ProgressIndicatorNotification
class SlicingProgressNotification
class UpdatedItemsInfoNotification
class URLDownloadNotification
Public Types
enum class NotificationLevel : int {
ProgressBarNotificationLevel = 1 , HintNotificationLevel , RegularNotificationLevel , PrintInfoNotificationLevel ,
PrintInfoShortNotificationLevel , ImportantNotificationLevel , WarningNotificationLevel , ErrorNotificationLevel
}
Public Member Functions
NotificationManager (wxEvtHandler *evt_handler)
~NotificationManager ()
void init ()
void push_notification (const NotificationType type, int timestamp=0)
void push_notification (const std::string &text, int timestamp=0)
void push_notification (NotificationType type, NotificationLevel level, const std::string &text, const std::string &hypertext="", std::function< bool(wxEvtHandler *)> callback=std::function< bool(wxEvtHandler *)>(), const std::string &text_after="", int timestamp=0)
void push_delayed_notification (const NotificationType type, std::function< bool(void)> condition_callback, int64_t initial_delay, int64_t delay_interval)
void stop_delayed_notifications_of_type (const NotificationType type)
void push_validate_error_notification (const std::string &text)
void push_slicing_error_notification (const std::string &text)
void push_slicing_warning_notification (const std::string &text, bool gray, ObjectID oid, int warning_step, const std::string &hypertext="", std::function< bool(wxEvtHandler *)> callback=std::function< bool(wxEvtHandler *)>())
void set_all_slicing_errors_gray (bool g)
void set_all_slicing_warnings_gray (bool g)
void close_slicing_errors_and_warnings ()
void close_slicing_error_notification (const std::string &text)
void remove_slicing_warnings_of_released_objects (const std::vector< ObjectID > &living_oids)
void push_plater_error_notification (const std::string &text)
void push_plater_warning_notification (const std::string &text)
void close_plater_error_notification (const std::string &text)
void close_plater_warning_notification (const std::string &text)
void push_simplify_suggestion_notification (const std::string &text, ObjectID object_id, const std::string &hypertext="", std::function< bool(wxEvtHandler *)> callback=std::function< bool(wxEvtHandler *)>())
void push_version_notification (NotificationType type, NotificationLevel level, const std::string &text, const std::string &hypertext, std::function< bool(wxEvtHandler *)> callback)
void remove_simplify_suggestion_of_released_objects (const std::vector< ObjectID > &living_oids)
void remove_simplify_suggestion_with_id (const ObjectID oid)
void set_sidebar_collapsed (bool collapsed)
void set_fff (bool b)
void set_fdm (bool b)
void set_sla (bool b)
void push_exporting_finished_notification (const std::string &path, const std::string &dir_path, bool on_removable)
void push_upload_job_notification (int id, float filesize, const std::string &filename, const std::string &host, float percentage=0)
void set_upload_job_notification_percentage (int id, const std::string &filename, const std::string &host, float percentage)
void set_upload_job_notification_host (int id, const std::string &host)
void set_upload_job_notification_status (int id, const std::string &status)
void set_upload_job_notification_comp_on_100 (int id, bool comp)
void set_upload_job_notification_completed (int id)
void set_upload_job_notification_completed_with_warning (int id)
void upload_job_notification_show_canceled (int id, const std::string &filename, const std::string &host)
void upload_job_notification_show_error (int id, const std::string &filename, const std::string &host)
void push_download_progress_notification (const std::string &text, std::function< bool()> cancel_callback)
void set_download_progress_percentage (float percentage)
void push_download_URL_progress_notification (size_t id, const std::string &text, std::function< bool(DownloaderUserAction, int)> user_action_callback)
void set_download_URL_progress (size_t id, float percentage)
void set_download_URL_paused (size_t id)
void set_download_URL_canceled (size_t id)
void set_download_URL_error (size_t id, const std::string &text)
void init_slicing_progress_notification (std::function< bool()> cancel_callback)
void set_slicing_progress_began ()
void set_slicing_progress_percentage (const std::string &text, float percentage)
void set_slicing_progress_canceled (const std::string &text)
void set_slicing_progress_hidden ()
void set_slicing_complete_print_time (const std::string &info, bool sidebar_colapsed)
void set_slicing_progress_export_possible ()
void init_progress_indicator ()
void progress_indicator_set_range (int range)
void progress_indicator_set_cancel_callback (CancelFn callback=CancelFn())
void progress_indicator_set_progress (int pr)
void progress_indicator_set_status_text (const char *)
int progress_indicator_get_range () const
void push_hint_notification (bool open_next)
bool is_hint_notification_open ()
void deactivate_loaded_hints ()
void push_updated_item_info_notification (InfoItemType type)
void new_export_began (bool on_removable)
void device_ejected ()
void render_notifications (GLCanvas3D &canvas, float overlay_width)
void close_notification_of_type (const NotificationType type)
void set_in_preview (bool preview)
void apply_in_preview ()
void set_move_from_overlay (bool move)
bool update_notifications (GLCanvas3D &canvas)
size_t get_notification_count () const
Private Member Functions
bool push_notification_data (const NotificationData &notification_data, int timestamp)
bool push_notification_data (std::unique_ptr< NotificationManager::PopNotification > notification, int timestamp)
void push_delayed_notification_data (std::unique_ptr< NotificationManager::PopNotification > notification, std::function< bool(void)> condition_callback, int64_t initial_delay, int64_t delay_interval)
bool activate_existing (const NotificationManager::PopNotification *notification)
void sort_notifications ()
bool has_slicing_error_notification ()
size_t get_standard_duration (NotificationLevel level)
Private Attributes
bool m_initialized { false }
wxEvtHandler * m_evt_handler
NotificationIDProvider m_id_provider
std::deque< std::unique_ptr< PopNotification > > m_pop_notifications
std::vector< DelayedNotification > m_waiting_notifications
std::unordered_set< int > m_used_timestamps
bool m_in_preview { false }
bool m_move_from_overlay { false }
int64_t m_last_render { 0LL }
const std::vector< NotificationType > m_multiple_types
const std::vector< NotificationData > basic_notifications
Detailed Description
Class Documentation
Slic3r::GUI::NotificationManager::NotificationData
struct Slic3r::GUI::NotificationManager::NotificationData
Class Members
function< bool(wxEvtHandler *)> callback
const int duration
const string hypertext
NotificationLevel level
const string text1
const string text2
NotificationType type
Member Enumeration Documentation
NotificationLevel
enum class Slic3r::GUI::NotificationManager::NotificationLevel : int strong
Enumerator
ProgressBarNotificationLevel
HintNotificationLevel
RegularNotificationLevel
PrintInfoNotificationLevel
PrintInfoShortNotificationLevel
ImportantNotificationLevel
WarningNotificationLevel
ErrorNotificationLevel
  {
    // The notifications will be presented in the order of importance, thus these enum values
    // are sorted by the importance.
    // Important notification with progress bar, no fade-out, might appear again after closing. Position at the bottom.
    ProgressBarNotificationLevel = 1,
    // "Did you know" notification with special icon and buttons, Position close to bottom.
    HintNotificationLevel,
    // "Good to know" notification, usually but not always with a quick fade-out.
    RegularNotificationLevel,
    // Regular level notifiaction containing info about objects or print. Has Icon.
    PrintInfoNotificationLevel,
    // PrintInfoNotificationLevel with shorter time
    PrintInfoShortNotificationLevel,
    // Information notification without a fade-out or with a longer fade-out.
    ImportantNotificationLevel,
    // Warning, no fade-out.
    WarningNotificationLevel,
    // Error, no fade-out. Top most position.
    ErrorNotificationLevel,
  };
Constructor & Destructor Documentation
NotificationManager()
Slic3r::GUI::NotificationManager::NotificationManager (wxEvtHandler * evt_handler)
                                                                  :
  m_evt_handler(evt_handler)
{
}
~NotificationManager()
Slic3r::GUI::NotificationManager::~NotificationManager () inline
{}
Member Function Documentation
activate_existing()
bool Slic3r::GUI::NotificationManager::activate_existing (const NotificationManager::PopNotification * notification) private
{
  NotificationType   new_type = notification->get_type();
  const std::string &new_text = notification->get_data().text1;
  for (auto it = m_pop_notifications.begin(); it != m_pop_notifications.end(); ++it) {
    if ((*it)->get_type() == new_type && !(*it)->is_finished()) {
      // multiple of one type allowed, but must have different text
      if (std::find(m_multiple_types.begin(), m_multiple_types.end(), new_type) != m_multiple_types.end()) {
        // If found same type and same text, return true - update will be performed on the old notif
        if ((*it)->compare_text(new_text) == false) {
          continue;
        }
      // multiple of one type allowed, but must have different text nad ObjectID
      } else if (new_type == NotificationType::SlicingWarning) {
        auto w1 = dynamic_cast<const ObjectIDNotification*>(notification);
        auto w2 = dynamic_cast<const ObjectIDNotification*>(it->get());
        if (w1 != nullptr && w2 != nullptr) {
          if (!(*it)->compare_text(new_text) || w1->object_id != w2->object_id) {
            continue;
          }
        } else {
          continue;
        }
      }
      if (it != m_pop_notifications.end() - 1)
        std::rotate(it, it + 1, m_pop_notifications.end());
      return true;
    }
  }
  return false;
}
References Slic3r::GUI::NotificationManager::PopNotification::get_data(), Slic3r::GUI::NotificationManager::PopNotification::get_type(), m_multiple_types, m_pop_notifications, Slic3r::GUI::SlicingWarning, and Slic3r::GUI::NotificationManager::NotificationData::text1.
Referenced by push_notification_data(), and update_notifications().
apply_in_preview()
void Slic3r::GUI::NotificationManager::apply_in_preview () inline
{ set_in_preview(m_in_preview); }
References m_in_preview, and set_in_preview().
Referenced by push_plater_warning_notification(), and Slic3r::GUI::Preview::update_layers_slider().
close_notification_of_type()
void Slic3r::GUI::NotificationManager::close_notification_of_type (const NotificationType type)
{
  for (std::unique_ptr<PopNotification> &notification : m_pop_notifications) {
    if (notification->get_type() == type) {
      notification->close();
    }
  }
}
References m_pop_notifications.
Referenced by new_export_began(), Slic3r::GUI::GUI_App::on_init_inner(), and push_exporting_finished_notification().
close_plater_error_notification()
void Slic3r::GUI::NotificationManager::close_plater_error_notification (const std::string & text)
{
  for (std::unique_ptr<PopNotification> &notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PlaterError && notification->compare_text(_u8L("ERROR:") + "\n" + text)) {
      notification->close();
    }
  }
}
References _u8L, m_pop_notifications, and Slic3r::GUI::PlaterError.
close_plater_warning_notification()
void Slic3r::GUI::NotificationManager::close_plater_warning_notification (const std::string & text)
{
  for (std::unique_ptr<PopNotification> &notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PlaterWarning && notification->compare_text(_u8L("WARNING:") + "\n" + text)) {
      dynamic_cast<PlaterWarningNotification*>(notification.get())->real_close();
    }
  }
}
References _u8L, m_pop_notifications, and Slic3r::GUI::PlaterWarning.
close_slicing_error_notification()
void Slic3r::GUI::NotificationManager::close_slicing_error_notification (const std::string & text)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingError && notification->compare_text(_u8L("ERROR:") + "\n" + text)) {
      notification->close();
    }
  }
}
References _u8L, m_pop_notifications, and Slic3r::GUI::SlicingError.
close_slicing_errors_and_warnings()
void Slic3r::GUI::NotificationManager::close_slicing_errors_and_warnings ()
{
  for (std::unique_ptr<PopNotification> &notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingError || notification->get_type() == NotificationType::SlicingWarning) {
      notification->close();
    }
  }
}
References m_pop_notifications, Slic3r::GUI::SlicingError, and Slic3r::GUI::SlicingWarning.
deactivate_loaded_hints()
void Slic3r::GUI::NotificationManager::deactivate_loaded_hints ()
{
  HintDatabase::get_instance().uninit();
}
References Slic3r::GUI::HintDatabase::get_instance(), and Slic3r::GUI::HintDatabase::uninit().
device_ejected()
void Slic3r::GUI::NotificationManager::device_ejected ()
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::ExportFinished && dynamic_cast<ExportFinishedNotification*>(notification.get())->m_to_removable)
      notification->close();
  }
}
References Slic3r::GUI::ExportFinished, and m_pop_notifications.
get_notification_count()
size_t Slic3r::GUI::NotificationManager::get_notification_count () const
{
  size_t ret = 0;
  for (const std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_state() != PopNotification::EState::Hidden)
      ret++;
  }
  return ret;
}
References Slic3r::GUI::NotificationManager::PopNotification::Hidden, and m_pop_notifications.
get_standard_duration()
size_t Slic3r::GUI::NotificationManager::get_standard_duration (NotificationLevel level) inline private
  {
    switch (level) {
    case NotificationLevel::ErrorNotificationLevel:       return 0;
    case NotificationLevel::WarningNotificationLevel:     return 0;
    case NotificationLevel::ImportantNotificationLevel:     return 20;
    case NotificationLevel::ProgressBarNotificationLevel:   return 2;
    case NotificationLevel::PrintInfoShortNotificationLevel:  return 5;
    case NotificationLevel::RegularNotificationLevel:       return 10;
    case NotificationLevel::PrintInfoNotificationLevel:     return 10;
    case NotificationLevel::HintNotificationLevel:        return 300;
    default: return 10;
    }
  }
References ErrorNotificationLevel, HintNotificationLevel, ImportantNotificationLevel, PrintInfoNotificationLevel, PrintInfoShortNotificationLevel, ProgressBarNotificationLevel, RegularNotificationLevel, and WarningNotificationLevel.
Referenced by push_notification().
has_slicing_error_notification()
bool Slic3r::GUI::NotificationManager::has_slicing_error_notification () private
{
  return std::any_of(m_pop_notifications.begin(), m_pop_notifications.end(), [](auto &n) {
      return n->get_type() == NotificationType::SlicingError;
    });
}
References m_pop_notifications.
init()
void Slic3r::GUI::NotificationManager::init () inline
{ m_initialized = true; }
References m_initialized.
Referenced by Slic3r::GUI::NotificationManager::PrintHostUploadNotification::complete(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::complete_with_warning(), Slic3r::GUI::NotificationManager::PopNotification::render(), Slic3r::GUI::NotificationManager::PopNotification::update(), and Slic3r::GUI::NotificationManager::PopNotification::update_state().
init_progress_indicator()
void Slic3r::GUI::NotificationManager::init_progress_indicator ()
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::ProgressIndicator) {
      return;
    }
  }
  NotificationData data{ NotificationType::ProgressIndicator, NotificationLevel::ProgressBarNotificationLevel, 1};
  auto notification = std::make_unique<NotificationManager::ProgressIndicatorNotification>(data, m_id_provider, m_evt_handler);
  push_notification_data(std::move(notification), 0);
}
References m_evt_handler, m_id_provider, m_pop_notifications, ProgressBarNotificationLevel, Slic3r::GUI::ProgressIndicator, and push_notification_data().
Referenced by progress_indicator_set_cancel_callback(), progress_indicator_set_progress(), progress_indicator_set_range(), and progress_indicator_set_status_text().
init_slicing_progress_notification()
void Slic3r::GUI::NotificationManager::init_slicing_progress_notification (std::function< bool()> cancel_callback)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingProgress) {
      dynamic_cast<SlicingProgressNotification*>(notification.get())->set_cancel_callback(cancel_callback);
      return;
    }
  }
  NotificationData data{ NotificationType::SlicingProgress, NotificationLevel::ProgressBarNotificationLevel, 0,  std::string(),std::string(),
              [](wxEvtHandler* evnthndlr) {
                if (evnthndlr != nullptr)
                  wxPostEvent(evnthndlr, ExportGcodeNotificationClickedEvent(EVT_EXPORT_GCODE_NOTIFICAION_CLICKED));
                return true;
              }
  };
  push_notification_data(std::make_unique<NotificationManager::SlicingProgressNotification>(data, m_id_provider, m_evt_handler, cancel_callback), 0);
}
References m_evt_handler, m_id_provider, m_pop_notifications, ProgressBarNotificationLevel, push_notification_data(), and Slic3r::GUI::SlicingProgress.
is_hint_notification_open()
bool Slic3r::GUI::NotificationManager::is_hint_notification_open ()
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::DidYouKnowHint)
      return true;
  }
  return false;
}
References Slic3r::GUI::DidYouKnowHint, and m_pop_notifications.
new_export_began()
void Slic3r::GUI::NotificationManager::new_export_began (bool on_removable)
{
  close_notification_of_type(NotificationType::ExportFinished);
  // If we want to hold information of ejecting removable on later export finished notifications
  /*
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::ExportToRemovableFinished) {
      if (!on_removable) {
        const NotificationData old_data = notification->get_data();
        notification->update( {old_data.type, old_data.level ,old_data.duration, std::string(), old_data.hypertext} );
      } else {
        notification->close();
      }
      return;
    }
  }
  */
}
References close_notification_of_type(), and Slic3r::GUI::ExportFinished.
progress_indicator_get_range()
int Slic3r::GUI::NotificationManager::progress_indicator_get_range () const
{
  for (const std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::ProgressIndicator) {
      return dynamic_cast<ProgressIndicatorNotification*>(notification.get())->get_range();
    }
  }
  return 0;
}
References m_pop_notifications, and Slic3r::GUI::ProgressIndicator.
Referenced by Slic3r::GUI::NotificationProgressIndicator::get_range().
progress_indicator_set_cancel_callback()
void Slic3r::GUI::NotificationManager::progress_indicator_set_cancel_callback (CancelFn callback = CancelFn())
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::ProgressIndicator) {
      dynamic_cast<ProgressIndicatorNotification*>(notification.get())->set_cancel_callback(callback);
      return;
    }
  }
  init_progress_indicator();
}
References init_progress_indicator(), m_pop_notifications, and Slic3r::GUI::ProgressIndicator.
Referenced by Slic3r::GUI::NotificationProgressIndicator::set_cancel_callback().
progress_indicator_set_progress()
void Slic3r::GUI::NotificationManager::progress_indicator_set_progress (int pr)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::ProgressIndicator) {
      dynamic_cast<ProgressIndicatorNotification*>(notification.get())->set_progress(pr);
      // Ask for rendering - needs to be done on every progress. Calls to here doesnt trigger IDLE event or rendering.
      wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(100);
      return;
    }
  }
  init_progress_indicator();
}
References init_progress_indicator(), m_pop_notifications, and Slic3r::GUI::ProgressIndicator.
Referenced by Slic3r::GUI::NotificationProgressIndicator::set_progress().
progress_indicator_set_range()
void Slic3r::GUI::NotificationManager::progress_indicator_set_range (int range)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::ProgressIndicator) {
      dynamic_cast<ProgressIndicatorNotification*>(notification.get())->set_range(range);
      return;
    }
  }
  init_progress_indicator();
}
References init_progress_indicator(), m_pop_notifications, Slic3r::GUI::ProgressIndicator, and Slic3r::range().
Referenced by Slic3r::GUI::NotificationProgressIndicator::set_range().
progress_indicator_set_status_text()
void Slic3r::GUI::NotificationManager::progress_indicator_set_status_text (const char * text)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::ProgressIndicator) {
      dynamic_cast<ProgressIndicatorNotification*>(notification.get())->set_status_text(text);
      return;
    }
  }
  init_progress_indicator();
}
References init_progress_indicator(), m_pop_notifications, and Slic3r::GUI::ProgressIndicator.
Referenced by Slic3r::GUI::NotificationProgressIndicator::set_status_text().
push_delayed_notification()
void Slic3r::GUI::NotificationManager::push_delayed_notification (const NotificationType type, std::function< bool(void)> condition_callback, int64_t initial_delay, int64_t delay_interval)
{
  auto it = std::find_if(std::begin(basic_notifications), std::end(basic_notifications),
    boost::bind(&NotificationData::type, boost::placeholders::_1) == type);
  assert(it != std::end(basic_notifications));
  if (it != std::end(basic_notifications))
    push_delayed_notification_data(std::make_unique<PopNotification>(*it, m_id_provider, m_evt_handler), condition_callback, initial_delay, delay_interval);
}
References basic_notifications, m_evt_handler, m_id_provider, push_delayed_notification_data(), and Slic3r::GUI::NotificationManager::NotificationData::type.
push_delayed_notification_data()
void Slic3r::GUI::NotificationManager::push_delayed_notification_data (std::unique_ptr< NotificationManager::PopNotification > notification, std::function< bool(void)> condition_callback, int64_t initial_delay, int64_t delay_interval) private
{
  if (initial_delay == 0 && condition_callback()) {
    if( push_notification_data(std::move(notification), 0))
      return;
  }
  m_waiting_notifications.emplace_back(std::move(notification), condition_callback, initial_delay == 0 ? delay_interval : initial_delay, delay_interval);
  wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(initial_delay == 0 ? delay_interval : initial_delay);
}
References m_waiting_notifications, and push_notification_data().
Referenced by push_delayed_notification(), and push_hint_notification().
push_download_progress_notification()
void Slic3r::GUI::NotificationManager::push_download_progress_notification (const std::string & text, std::function< bool()> cancel_callback)
{
  // If already exists, change text and reset progress
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::AppDownload) {
      notification->update({ NotificationType::AppDownload, NotificationLevel::ProgressBarNotificationLevel, 10, text });
      auto* pbwcn = dynamic_cast<ProgressBarWithCancelNotification*>(notification.get());
      pbwcn->set_percentage(0.0f);
      pbwcn->set_cancel_callback(cancel_callback);
      return;
    }
  }
  // push new one
  NotificationData data{ NotificationType::AppDownload, NotificationLevel::ProgressBarNotificationLevel, 10, text };
  push_notification_data(std::make_unique<NotificationManager::ProgressBarWithCancelNotification>(data, m_id_provider, m_evt_handler, cancel_callback), 0);
}
References Slic3r::GUI::AppDownload, m_evt_handler, m_id_provider, m_pop_notifications, ProgressBarNotificationLevel, push_notification_data(), and Slic3r::GUI::NotificationManager::ProgressBarWithCancelNotification::set_percentage().
Referenced by Slic3r::GUI::GUI_App::app_updater().
push_download_URL_progress_notification()
void Slic3r::GUI::NotificationManager::push_download_URL_progress_notification (size_t id, const std::string & text, std::function< bool(DownloaderUserAction, int)> user_action_callback)
{
  // If already exists
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::URLDownload && dynamic_cast<URLDownloadNotification*>(notification.get())->get_download_id() == id) {
      return;
    }
  }
  // push new one
  NotificationData data{ NotificationType::URLDownload, NotificationLevel::ProgressBarNotificationLevel, 5, _u8L("Download") + ": " + text };
  push_notification_data(std::make_unique<NotificationManager::URLDownloadNotification>(data, m_id_provider, m_evt_handler, id, user_action_callback), 0);
}
References _u8L, m_evt_handler, m_id_provider, m_pop_notifications, ProgressBarNotificationLevel, push_notification_data(), and Slic3r::GUI::URLDownload.
Referenced by Slic3r::GUI::Downloader::start_download().
push_exporting_finished_notification()
void Slic3r::GUI::NotificationManager::push_exporting_finished_notification (const std::string & path, const std::string & dir_path, bool on_removable)
{
  close_notification_of_type(NotificationType::ExportFinished);
  NotificationData data{ NotificationType::ExportFinished, NotificationLevel::RegularNotificationLevel, on_removable ? 0 : 20,  _u8L("Exporting finished.") + "\n" + path };
  push_notification_data(std::make_unique<NotificationManager::ExportFinishedNotification>(data, m_id_provider, m_evt_handler, on_removable, path, dir_path), 0);
  set_slicing_progress_hidden();
}
References _u8L, close_notification_of_type(), Slic3r::GUI::ExportFinished, m_evt_handler, m_id_provider, push_notification_data(), RegularNotificationLevel, and set_slicing_progress_hidden().
push_hint_notification()
void Slic3r::GUI::NotificationManager::push_hint_notification (bool open_next)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::DidYouKnowHint) {
      (dynamic_cast<HintNotification*>(notification.get()))->open_next();
      return;
    }
  }
  NotificationData data{ NotificationType::DidYouKnowHint, NotificationLevel::HintNotificationLevel, 300, "" };
  // from user - open now
  if (!open_next) {
    push_notification_data(std::make_unique<NotificationManager::HintNotification>(data, m_id_provider, m_evt_handler, open_next), 0);
    stop_delayed_notifications_of_type(NotificationType::DidYouKnowHint);
  // at startup - delay for half a second to let other notification pop up, than try every 30 seconds
  // show only if no notifications are shown
  } else {
    auto condition = [&self = std::as_const(*this)]() {
      return self.get_notification_count() == 0;
    };
    push_delayed_notification_data(std::make_unique<NotificationManager::HintNotification>(data, m_id_provider, m_evt_handler, open_next), condition, 500, 30000);
  }
}
References Slic3r::GUI::DidYouKnowHint, HintNotificationLevel, m_evt_handler, m_id_provider, m_pop_notifications, push_delayed_notification_data(), push_notification_data(), and stop_delayed_notifications_of_type().
Referenced by Slic3r::GUI::GUI_App::post_init().
push_notification() [1/3]
void Slic3r::GUI::NotificationManager::push_notification (const NotificationType type, int timestamp = 0)
{
  auto it = std::find_if(std::begin(basic_notifications), std::end(basic_notifications),
    boost::bind(&NotificationData::type, boost::placeholders::_1) == type);
  assert(it != std::end(basic_notifications));
  if (it != std::end(basic_notifications))
    push_notification_data(*it, timestamp);
}
References basic_notifications, push_notification_data(), and Slic3r::GUI::NotificationManager::NotificationData::type.
Referenced by Slic3r::GUI::Plater::check_selected_presets_visibility(), Slic3r::GUI::Plater::clear_before_change_mesh(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::ObjectList::fix_through_netfabb(), push_version_notification(), Slic3r::GUI::Downloader::start_download(), and Slic3r::GUI::Preview::update_layers_slider().
push_notification() [2/3]
void Slic3r::GUI::NotificationManager::push_notification (const std::string & text, int timestamp = 0)
{
  push_notification_data({ NotificationType::CustomNotification, NotificationLevel::RegularNotificationLevel, 10, text }, timestamp);
}
References Slic3r::GUI::CustomNotification, push_notification_data(), and RegularNotificationLevel.
push_notification() [3/3]
void Slic3r::GUI::NotificationManager::push_notification (NotificationType type, NotificationLevel level, const std::string & text, const std::string & hypertext = "", std::function< bool(wxEvtHandler *)> callback = std::function<bool(wxEvtHandler*)>(), const std::string & text_after = "", int timestamp = 0)
{
  int duration = get_standard_duration(level);
    push_notification_data({ type, level, duration, text, hypertext, callback, text_after }, timestamp);
}
References get_standard_duration(), and push_notification_data().
push_notification_data() [1/2]
bool Slic3r::GUI::NotificationManager::push_notification_data (const NotificationData & notification_data, int timestamp) private
{
  return push_notification_data(std::make_unique<PopNotification>(notification_data, m_id_provider, m_evt_handler), timestamp);
}
References m_evt_handler, m_id_provider, and push_notification_data().
Referenced by init_progress_indicator(), init_slicing_progress_notification(), push_delayed_notification_data(), push_download_progress_notification(), push_download_URL_progress_notification(), push_exporting_finished_notification(), push_hint_notification(), push_notification(), push_notification(), push_notification(), push_notification_data(), push_plater_error_notification(), push_plater_warning_notification(), push_simplify_suggestion_notification(), push_slicing_error_notification(), push_slicing_warning_notification(), push_updated_item_info_notification(), push_upload_job_notification(), push_validate_error_notification(), and update_notifications().
push_notification_data() [2/2]
bool Slic3r::GUI::NotificationManager::push_notification_data (std::unique_ptr< NotificationManager::PopNotification > notification, int timestamp) private
{
  // if timestamped notif, push only new one
  if (timestamp != 0) {
    if (m_used_timestamps.find(timestamp) == m_used_timestamps.end()) {
      m_used_timestamps.insert(timestamp);
    } else {
      return false;
    }
  }
  bool retval = false;
  if (this->activate_existing(notification.get())) {
    if (m_initialized) { // ignore update action - it cant be initialized if canvas and imgui context is not ready
      m_pop_notifications.back()->update(notification->get_data());
    }
  } else {
    m_pop_notifications.emplace_back(std::move(notification));
    retval = true;
  }
  if (!m_initialized)
    return retval;
  GLCanvas3D& canvas = *wxGetApp().plater()->get_current_canvas3D();
  canvas.schedule_extra_frame(0);
  return retval;
}
References activate_existing(), m_initialized, m_pop_notifications, m_used_timestamps, and Slic3r::GUI::GLCanvas3D::schedule_extra_frame().
push_plater_error_notification()
void Slic3r::GUI::NotificationManager::push_plater_error_notification (const std::string & text)
{
  push_notification_data({ NotificationType::PlaterError, NotificationLevel::ErrorNotificationLevel, 0,  _u8L("ERROR:") + "\n" + text }, 0);
}
References _u8L, ErrorNotificationLevel, Slic3r::GUI::PlaterError, and push_notification_data().
Referenced by Slic3r::GUI::Plater::export_stl_obj().
push_plater_warning_notification()
void Slic3r::GUI::NotificationManager::push_plater_warning_notification (const std::string & text)
{
  // Find if was not hidden
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PlaterWarning && notification->compare_text(_u8L("WARNING:") + "\n" + text)) {
      if (notification->get_state() == PopNotification::EState::Hidden) {
        //dynamic_cast<PlaterWarningNotification*>(notification.get())->show();
        return;
      }
    }
  }
  NotificationData data{ NotificationType::PlaterWarning, NotificationLevel::WarningNotificationLevel, 0,  _u8L("WARNING:") + "\n" + text };
  auto notification = std::make_unique<NotificationManager::PlaterWarningNotification>(data, m_id_provider, m_evt_handler);
  push_notification_data(std::move(notification), 0);
  // dissaper if in preview
  apply_in_preview();
}
References _u8L, apply_in_preview(), Slic3r::GUI::NotificationManager::PopNotification::Hidden, m_evt_handler, m_id_provider, m_pop_notifications, Slic3r::GUI::PlaterWarning, push_notification_data(), and WarningNotificationLevel.
push_simplify_suggestion_notification()
void Slic3r::GUI::NotificationManager::push_simplify_suggestion_notification (const std::string & text, ObjectID object_id, const std::string & hypertext = "", std::function< bool(wxEvtHandler *)> callback = std::function<bool(wxEvtHandler*)>())
{
  NotificationData data{ NotificationType::SimplifySuggestion, NotificationLevel::PrintInfoNotificationLevel, 10,  text, hypertext, callback };
  auto notification = std::make_unique<NotificationManager::ObjectIDNotification>(data, m_id_provider, m_evt_handler);
  notification->object_id = object_id;
  push_notification_data(std::move(notification), 0);
}
References m_evt_handler, m_id_provider, PrintInfoNotificationLevel, push_notification_data(), and Slic3r::GUI::SimplifySuggestion.
Referenced by Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification().
push_slicing_error_notification()
void Slic3r::GUI::NotificationManager::push_slicing_error_notification (const std::string & text)
{
  set_all_slicing_errors_gray(false);
  push_notification_data({ NotificationType::SlicingError, NotificationLevel::ErrorNotificationLevel, 0,  _u8L("ERROR:") + "\n" + text }, 0);
  set_slicing_progress_hidden();
}
References _u8L, ErrorNotificationLevel, push_notification_data(), set_all_slicing_errors_gray(), set_slicing_progress_hidden(), and Slic3r::GUI::SlicingError.
push_slicing_warning_notification()
void Slic3r::GUI::NotificationManager::push_slicing_warning_notification (const std::string & text, bool gray, ObjectID oid, int warning_step, const std::string & hypertext = "", std::function< bool(wxEvtHandler *)> callback = std::function<bool(wxEvtHandler*)>())
{
  NotificationData data { NotificationType::SlicingWarning, NotificationLevel::WarningNotificationLevel, 0,  _u8L("WARNING:") + "\n" + text ,  hypertext, callback};
  auto notification = std::make_unique<NotificationManager::ObjectIDNotification>(data, m_id_provider, m_evt_handler);
  notification->object_id = oid;
  notification->warning_step = warning_step;
  if (push_notification_data(std::move(notification), 0)) {
    m_pop_notifications.back()->set_gray(gray);
  }
}
References _u8L, m_evt_handler, m_id_provider, m_pop_notifications, push_notification_data(), Slic3r::GUI::SlicingWarning, and WarningNotificationLevel.
push_updated_item_info_notification()
void Slic3r::GUI::NotificationManager::push_updated_item_info_notification (InfoItemType type)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::UpdatedItemsInfo) {
      (dynamic_cast<UpdatedItemsInfoNotification*>(notification.get()))->add_type(type);
      return;
    }
  }
  NotificationData data{ NotificationType::UpdatedItemsInfo, NotificationLevel::PrintInfoNotificationLevel, 10, "" };
  auto notification = std::make_unique<NotificationManager::UpdatedItemsInfoNotification>(data, m_id_provider, m_evt_handler, type);
  if (push_notification_data(std::move(notification), 0)) {
    (dynamic_cast<UpdatedItemsInfoNotification*>(m_pop_notifications.back().get()))->add_type(type);
  }
}
References m_evt_handler, m_id_provider, m_pop_notifications, PrintInfoNotificationLevel, push_notification_data(), and Slic3r::GUI::UpdatedItemsInfo.
push_upload_job_notification()
void Slic3r::GUI::NotificationManager::push_upload_job_notification (int id, float filesize, const std::string & filename, const std::string & host, float percentage = 0)
{
  // find if upload with same id was not already in notification
  // done by compare_jon_id not compare_text thus has to be performed here
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PrintHostUpload && dynamic_cast<PrintHostUploadNotification*>(notification.get())->compare_job_id(id)) {
      return;
    }
  }
  // filename is created from boost::filesystem::path.string() which if created by path / "file" return \\ as folder division. But could also contain / as folder division. Lets unite this into "/" only.
  std::string correct_filename(filename);
  std::replace(correct_filename.begin(), correct_filename.end(), '\\', '/');
  std::string text = correct_filename + " -> " + host;
  NotificationData data{ NotificationType::PrintHostUpload, NotificationLevel::ProgressBarNotificationLevel, 10, text };
  push_notification_data(std::make_unique<NotificationManager::PrintHostUploadNotification>(data, m_id_provider, m_evt_handler, 0, id, filesize, filename, host), 0);
}
References m_evt_handler, m_id_provider, m_pop_notifications, Slic3r::GUI::PrintHostUpload, ProgressBarNotificationLevel, and push_notification_data().
push_validate_error_notification()
void Slic3r::GUI::NotificationManager::push_validate_error_notification (const std::string & text)
{
  push_notification_data({ NotificationType::ValidateError, NotificationLevel::ErrorNotificationLevel, 0,  _u8L("ERROR:") + "\n" + text }, 0);
  set_slicing_progress_hidden();
}
References _u8L, ErrorNotificationLevel, push_notification_data(), set_slicing_progress_hidden(), and Slic3r::GUI::ValidateError.
push_version_notification()
void Slic3r::GUI::NotificationManager::push_version_notification (NotificationType type, NotificationLevel level, const std::string & text, const std::string & hypertext, std::function< bool(wxEvtHandler *)> callback)
{
  assert (type == NotificationType::NewAlphaAvailable
     || type == NotificationType::NewBetaAvailable
     || type == NotificationType::NoNewReleaseAvailable);
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    // NoNewReleaseAvailable must not show if alfa / beta is on.
    if (type == NotificationType::NoNewReleaseAvailable
      && (notification->get_type() == NotificationType::NewAlphaAvailable
        || notification->get_type() == NotificationType::NewBetaAvailable)) {
      return;
    }
    // NoNewReleaseAvailable must close if alfa / beta is being push.
    if (notification->get_type() == NotificationType::NoNewReleaseAvailable
      && (type == NotificationType::NewAlphaAvailable
        || type == NotificationType::NewBetaAvailable)) {
      notification->close();
    }
  }
  push_notification(type, level, text, hypertext, callback);
}
References m_pop_notifications, Slic3r::GUI::NewAlphaAvailable, Slic3r::GUI::NewBetaAvailable, Slic3r::GUI::NoNewReleaseAvailable, and push_notification().
Referenced by Slic3r::GUI::GUI_App::on_version_read().
remove_simplify_suggestion_of_released_objects()
void Slic3r::GUI::NotificationManager::remove_simplify_suggestion_of_released_objects (const std::vector< ObjectID > & living_oids)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications)
    if (notification->get_type() == NotificationType::SimplifySuggestion) {
      if (!std::binary_search(living_oids.begin(), living_oids.end(),
        static_cast<ObjectIDNotification*>(notification.get())->object_id))
        notification->close();
    }
}
References m_pop_notifications, Slic3r::GUI::NotificationManager::ObjectIDNotification::object_id, and Slic3r::GUI::SimplifySuggestion.
remove_simplify_suggestion_with_id()
void Slic3r::GUI::NotificationManager::remove_simplify_suggestion_with_id (const ObjectID oid)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications)
    if (notification->get_type() == NotificationType::SimplifySuggestion) {
      if (static_cast<ObjectIDNotification*>(notification.get())->object_id == oid)
        notification->close();
    }
}
References m_pop_notifications, Slic3r::GUI::NotificationManager::ObjectIDNotification::object_id, and Slic3r::GUI::SimplifySuggestion.
remove_slicing_warnings_of_released_objects()
void Slic3r::GUI::NotificationManager::remove_slicing_warnings_of_released_objects (const std::vector< ObjectID > & living_oids)
{
  for (std::unique_ptr<PopNotification> &notification : m_pop_notifications)
    if (notification->get_type() == NotificationType::SlicingWarning) {
      if (! std::binary_search(living_oids.begin(), living_oids.end(),
        static_cast<ObjectIDNotification*>(notification.get())->object_id))
        notification->close();
    }
}
References m_pop_notifications, Slic3r::GUI::NotificationManager::ObjectIDNotification::object_id, and Slic3r::GUI::SlicingWarning.
render_notifications()
void Slic3r::GUI::NotificationManager::render_notifications (GLCanvas3D & canvas, float overlay_width)
{
  sort_notifications();
  float last_y = 0.0f;
  for (const auto& notification : m_pop_notifications) {
    if (notification->get_state() != PopNotification::EState::Hidden) {
      notification->render(canvas, last_y, m_move_from_overlay && !m_in_preview, overlay_width);
      if (notification->get_state() != PopNotification::EState::Finished)
        last_y = notification->get_top() + GAP_WIDTH;
    }
  }
  m_last_render = GLCanvas3D::timestamp_now();
}
References Slic3r::GUI::NotificationManager::PopNotification::Finished, GAP_WIDTH, Slic3r::GUI::NotificationManager::PopNotification::Hidden, m_in_preview, m_last_render, m_move_from_overlay, m_pop_notifications, sort_notifications(), and Slic3r::GUI::GLCanvas3D::timestamp_now().
set_all_slicing_errors_gray()
void Slic3r::GUI::NotificationManager::set_all_slicing_errors_gray (bool g)
{
  for (std::unique_ptr<PopNotification> &notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingError) {
      notification->set_gray(g);
    }
  }
}
References m_pop_notifications, and Slic3r::GUI::SlicingError.
Referenced by push_slicing_error_notification().
set_all_slicing_warnings_gray()
void Slic3r::GUI::NotificationManager::set_all_slicing_warnings_gray (bool g)
{
  for (std::unique_ptr<PopNotification> &notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingWarning) {
      notification->set_gray(g);
    }
  }
}
References m_pop_notifications, and Slic3r::GUI::SlicingWarning.
set_download_progress_percentage()
void Slic3r::GUI::NotificationManager::set_download_progress_percentage (float percentage)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::AppDownload) {
      ProgressBarWithCancelNotification* pbwcn = dynamic_cast<ProgressBarWithCancelNotification*>(notification.get());
      // if this changes the percentage, it should be shown now
      float percent_b4 = pbwcn->get_percentage();
      pbwcn->set_percentage(percentage);
      if (pbwcn->get_percentage() != percent_b4)
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
      return;
    }
  }
}
References Slic3r::GUI::AppDownload, Slic3r::GUI::NotificationManager::ProgressBarNotification::get_percentage(), m_pop_notifications, and Slic3r::GUI::NotificationManager::ProgressBarWithCancelNotification::set_percentage().
Referenced by Slic3r::GUI::GUI_App::on_init_inner().
set_download_URL_canceled()
void Slic3r::GUI::NotificationManager::set_download_URL_canceled (size_t id)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::URLDownload) {
      URLDownloadNotification* ntf = dynamic_cast<URLDownloadNotification*>(notification.get());
      if (ntf->get_download_id() != id)
        continue;
      ntf->close();
      wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
      return;
    }
  }
}
References Slic3r::GUI::NotificationManager::PopNotification::close(), Slic3r::GUI::NotificationManager::URLDownloadNotification::get_download_id(), m_pop_notifications, and Slic3r::GUI::URLDownload.
Referenced by Slic3r::GUI::Downloader::on_canceled().
set_download_URL_error()
void Slic3r::GUI::NotificationManager::set_download_URL_error (size_t id, const std::string & text)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::URLDownload) {
      URLDownloadNotification* ntf = dynamic_cast<URLDownloadNotification*>(notification.get());
      if (ntf->get_download_id() != id)
        continue;
      float percent_b4 = ntf->get_percentage();
      ntf->set_percentage(-1.f);
      ntf->set_error_message(text);
      if (ntf->get_percentage() != percent_b4)
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
      return;
    }
  }
}
References Slic3r::GUI::NotificationManager::URLDownloadNotification::get_download_id(), Slic3r::GUI::NotificationManager::ProgressBarNotification::get_percentage(), m_pop_notifications, Slic3r::GUI::NotificationManager::URLDownloadNotification::set_error_message(), Slic3r::GUI::NotificationManager::URLDownloadNotification::set_percentage(), and Slic3r::GUI::URLDownload.
Referenced by Slic3r::GUI::Downloader::on_error().
set_download_URL_paused()
void Slic3r::GUI::NotificationManager::set_download_URL_paused (size_t id)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::URLDownload) {
      URLDownloadNotification* ntf = dynamic_cast<URLDownloadNotification*>(notification.get());
      if (ntf->get_download_id() != id)
        continue;
      ntf->set_paused(true);
      wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
      return;
    }
  }
}
References Slic3r::GUI::NotificationManager::URLDownloadNotification::get_download_id(), m_pop_notifications, Slic3r::GUI::NotificationManager::URLDownloadNotification::set_paused(), and Slic3r::GUI::URLDownload.
Referenced by Slic3r::GUI::Downloader::on_paused().
set_download_URL_progress()
void Slic3r::GUI::NotificationManager::set_download_URL_progress (size_t id, float percentage)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::URLDownload) {
      URLDownloadNotification* ntf = dynamic_cast<URLDownloadNotification*>(notification.get());
      if (ntf->get_download_id() != id)
        continue;
      // if this changes the percentage, it should be shown now
      float percent_b4 = ntf->get_percentage();
      ntf->set_percentage(percentage);
      ntf->set_paused(false);
      if (ntf->get_percentage() != percent_b4)
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
      return;
    }
  }
}
References Slic3r::GUI::NotificationManager::URLDownloadNotification::get_download_id(), Slic3r::GUI::NotificationManager::ProgressBarNotification::get_percentage(), m_pop_notifications, Slic3r::GUI::NotificationManager::URLDownloadNotification::set_paused(), Slic3r::GUI::NotificationManager::URLDownloadNotification::set_percentage(), and Slic3r::GUI::URLDownload.
Referenced by Slic3r::GUI::Downloader::on_progress().
set_fdm()
void Slic3r::GUI::NotificationManager::set_fdm (bool b) inline
{ set_fff(b); }
References set_fff().
set_fff()
void Slic3r::GUI::NotificationManager::set_fff (bool b)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingProgress) {
      dynamic_cast<SlicingProgressNotification*>(notification.get())->set_fff(fff);
      break;
    }
  }
}
References m_pop_notifications, set_fff(), and Slic3r::GUI::SlicingProgress.
Referenced by set_fdm(), set_fff(), and set_sla().
set_in_preview()
void Slic3r::GUI::NotificationManager::set_in_preview (bool preview)
{
    m_in_preview = preview;
    for (std::unique_ptr<PopNotification> &notification : m_pop_notifications) {
        if (notification->get_type() == NotificationType::PlaterWarning)
            notification->hide(preview);
        if (notification->get_type() == NotificationType::SignDetected)
            notification->hide(!preview);
    if (m_in_preview && notification->get_type() == NotificationType::DidYouKnowHint)
      notification->close();
    }
}
References Slic3r::GUI::DidYouKnowHint, m_in_preview, m_pop_notifications, Slic3r::GUI::PlaterWarning, and Slic3r::GUI::SignDetected.
Referenced by apply_in_preview().
set_move_from_overlay()
void Slic3r::GUI::NotificationManager::set_move_from_overlay (bool move) inline
{ m_move_from_overlay = move; }
References m_move_from_overlay.
set_sidebar_collapsed()
void Slic3r::GUI::NotificationManager::set_sidebar_collapsed (bool collapsed)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingProgress) {
      dynamic_cast<SlicingProgressNotification*>(notification.get())->set_sidebar_collapsed(collapsed);
      break;
    }
  }
}
References m_pop_notifications, set_sidebar_collapsed(), and Slic3r::GUI::SlicingProgress.
Referenced by set_sidebar_collapsed(), and set_slicing_complete_print_time().
set_sla()
void Slic3r::GUI::NotificationManager::set_sla (bool b) inline
{ set_fff(!b); }
References set_fff().
set_slicing_complete_print_time()
void Slic3r::GUI::NotificationManager::set_slicing_complete_print_time (const std::string & info, bool sidebar_colapsed)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingProgress) {
      dynamic_cast<SlicingProgressNotification*>(notification.get())->set_sidebar_collapsed(sidebar_colapsed);
      dynamic_cast<SlicingProgressNotification*>(notification.get())->set_print_info(info);
      break;
    }
  }
}
References m_pop_notifications, set_sidebar_collapsed(), and Slic3r::GUI::SlicingProgress.
set_slicing_progress_began()
void Slic3r::GUI::NotificationManager::set_slicing_progress_began ()
{
  for (std::unique_ptr<PopNotification> & notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingProgress) {
      SlicingProgressNotification* spn = dynamic_cast<SlicingProgressNotification*>(notification.get());
      spn->set_progress_state(SlicingProgressNotification::SlicingProgressState::SP_BEGAN);
      return;
    }
  }
  // Slicing progress notification was not found - init it thru plater so correct cancel callback function is appended
  wxGetApp().plater()->init_notification_manager();
}
References m_pop_notifications, Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_progress_state(), Slic3r::GUI::SlicingProgress, and Slic3r::GUI::NotificationManager::SlicingProgressNotification::SP_BEGAN.
set_slicing_progress_canceled()
void Slic3r::GUI::NotificationManager::set_slicing_progress_canceled (const std::string & text)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingProgress) {
      SlicingProgressNotification* spn = dynamic_cast<SlicingProgressNotification*>(notification.get());
      spn->set_progress_state(SlicingProgressNotification::SlicingProgressState::SP_CANCELLED);
      spn->set_status_text(text);
      wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
      return;
    }
  }
  // Slicing progress notification was not found - init it thru plater so correct cancel callback function is appended
  wxGetApp().plater()->init_notification_manager();
}
References m_pop_notifications, Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_progress_state(), Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_status_text(), Slic3r::GUI::SlicingProgress, and Slic3r::GUI::NotificationManager::SlicingProgressNotification::SP_CANCELLED.
set_slicing_progress_export_possible()
void Slic3r::GUI::NotificationManager::set_slicing_progress_export_possible ()
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingProgress) {
      dynamic_cast<SlicingProgressNotification*>(notification.get())->set_export_possible(true);
      break;
    }
  }
}
References m_pop_notifications, and Slic3r::GUI::SlicingProgress.
set_slicing_progress_hidden()
void Slic3r::GUI::NotificationManager::set_slicing_progress_hidden ()
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingProgress) {
      SlicingProgressNotification* notif = dynamic_cast<SlicingProgressNotification*>(notification.get());
      notif->set_progress_state(SlicingProgressNotification::SlicingProgressState::SP_NO_SLICING);
      wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
      return;
    }
  }
  // Slicing progress notification was not found - init it thru plater so correct cancel callback function is appended
  wxGetApp().plater()->init_notification_manager();
}
References m_pop_notifications, Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_progress_state(), Slic3r::GUI::SlicingProgress, and Slic3r::GUI::NotificationManager::SlicingProgressNotification::SP_NO_SLICING.
Referenced by push_exporting_finished_notification(), push_slicing_error_notification(), and push_validate_error_notification().
set_slicing_progress_percentage()
void Slic3r::GUI::NotificationManager::set_slicing_progress_percentage (const std::string & text, float percentage)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::SlicingProgress) {
      SlicingProgressNotification* spn = dynamic_cast<SlicingProgressNotification*>(notification.get());
      if(spn->set_progress_state(percentage)) {
        spn->set_status_text(text);
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
      }
      return;
    }
  }
  // Slicing progress notification was not found - init it thru plater so correct cancel callback function is appended
  wxGetApp().plater()->init_notification_manager();
}
References m_pop_notifications, Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_progress_state(), Slic3r::GUI::NotificationManager::SlicingProgressNotification::set_status_text(), and Slic3r::GUI::SlicingProgress.
set_upload_job_notification_comp_on_100()
void Slic3r::GUI::NotificationManager::set_upload_job_notification_comp_on_100 (int id, bool comp)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PrintHostUpload) {
      PrintHostUploadNotification* phun = dynamic_cast<PrintHostUploadNotification*>(notification.get());
      if (phun->compare_job_id(id)) {
        phun->set_complete_on_100(comp);
        break;
      }
    }
  }
}
References Slic3r::GUI::NotificationManager::PrintHostUploadNotification::compare_job_id(), m_pop_notifications, Slic3r::GUI::PrintHostUpload, and Slic3r::GUI::NotificationManager::PrintHostUploadNotification::set_complete_on_100().
set_upload_job_notification_completed()
void Slic3r::GUI::NotificationManager::set_upload_job_notification_completed (int id)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PrintHostUpload) {
      PrintHostUploadNotification* phun = dynamic_cast<PrintHostUploadNotification*>(notification.get());
      if (phun->compare_job_id(id)) {
        phun->complete();
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
        break;
      }
    }
  }
}
References Slic3r::GUI::NotificationManager::PrintHostUploadNotification::compare_job_id(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::complete(), m_pop_notifications, and Slic3r::GUI::PrintHostUpload.
set_upload_job_notification_completed_with_warning()
void Slic3r::GUI::NotificationManager::set_upload_job_notification_completed_with_warning (int id)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PrintHostUpload) {
      PrintHostUploadNotification* phun = dynamic_cast<PrintHostUploadNotification*>(notification.get());
      if (phun->compare_job_id(id)) {
        phun->complete_with_warning();
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
        break;
      }
    }
  }
}
References Slic3r::GUI::NotificationManager::PrintHostUploadNotification::compare_job_id(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::complete_with_warning(), m_pop_notifications, and Slic3r::GUI::PrintHostUpload.
set_upload_job_notification_host()
void Slic3r::GUI::NotificationManager::set_upload_job_notification_host (int id, const std::string & host)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PrintHostUpload) {
      PrintHostUploadNotification* phun = dynamic_cast<PrintHostUploadNotification*>(notification.get());
      if (phun->compare_job_id(id)) {
        phun->set_host(host);
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
        break;
      }
    }
  }
}
References Slic3r::GUI::NotificationManager::PrintHostUploadNotification::compare_job_id(), m_pop_notifications, Slic3r::GUI::PrintHostUpload, and Slic3r::GUI::NotificationManager::PrintHostUploadNotification::set_host().
set_upload_job_notification_percentage()
void Slic3r::GUI::NotificationManager::set_upload_job_notification_percentage (int id, const std::string & filename, const std::string & host, float percentage)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PrintHostUpload) {
      PrintHostUploadNotification* phun = dynamic_cast<PrintHostUploadNotification*>(notification.get());
      if (phun->compare_job_id(id)) {
        phun->set_percentage(percentage);
        if (phun->get_host() != host)
          phun->set_host(host);
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
        break;
      }
    }
  }
}
References Slic3r::GUI::NotificationManager::PrintHostUploadNotification::compare_job_id(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::get_host(), m_pop_notifications, Slic3r::GUI::PrintHostUpload, Slic3r::GUI::NotificationManager::PrintHostUploadNotification::set_host(), and Slic3r::GUI::NotificationManager::PrintHostUploadNotification::set_percentage().
set_upload_job_notification_status()
void Slic3r::GUI::NotificationManager::set_upload_job_notification_status (int id, const std::string & status)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PrintHostUpload) {
      PrintHostUploadNotification* phun = dynamic_cast<PrintHostUploadNotification*>(notification.get());
      if (phun->compare_job_id(id)) {
        phun->set_status(status);
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
        break;
      }
    }
  }
}
References Slic3r::GUI::NotificationManager::PrintHostUploadNotification::compare_job_id(), m_pop_notifications, Slic3r::GUI::PrintHostUpload, and Slic3r::GUI::NotificationManager::PrintHostUploadNotification::set_status().
sort_notifications()
void Slic3r::GUI::NotificationManager::sort_notifications () private
{
  // Stable sorting, so that the order of equal ranges is stable.
  std::stable_sort(m_pop_notifications.begin(), m_pop_notifications.end(), [](const std::unique_ptr<PopNotification> &n1, const std::unique_ptr<PopNotification> &n2) {
    int n1l = (int)n1->get_data().level;
    int n2l = (int)n2->get_data().level;
    if (n1l == n2l && n1->is_gray() && !n2->is_gray())
      return true;
    return (n1l < n2l);
    });
}
References m_pop_notifications.
Referenced by render_notifications().
stop_delayed_notifications_of_type()
void Slic3r::GUI::NotificationManager::stop_delayed_notifications_of_type (const NotificationType type)
{
  for (auto it = m_waiting_notifications.begin(); it != m_waiting_notifications.end();) {
    if ((*it).notification->get_type() == type) {
      it = m_waiting_notifications.erase(it);
    }
    else {
      ++it;
    }
  }
}
References m_waiting_notifications.
Referenced by push_hint_notification().
update_notifications()
bool Slic3r::GUI::NotificationManager::update_notifications (GLCanvas3D & canvas)
{
  // no update if not top window
  wxWindow* p = dynamic_cast<wxWindow*>(wxGetApp().plater());
  while (p->GetParent() != nullptr)
    p = p->GetParent();
  wxTopLevelWindow* top_level_wnd = dynamic_cast<wxTopLevelWindow*>(p);
  if (!top_level_wnd->IsActive())
    return false;
  // next_render() returns numeric_limits::max if no need for frame
  const int64_t max = std::numeric_limits<int64_t>::max();
  int64_t       next_render = max;
  const int64_t time_since_render = GLCanvas3D::timestamp_now() - m_last_render;
  bool      request_render = false;
  // During render, each notification detects if its currently hovered and changes its state to EState::Hovered
  // If any notification is hovered, all restarts its countdown
  bool          hover = false;
  for (const std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->is_hovered()) {
      hover = true;
      break;
    }
  }
  // update state of all notif and erase finished
  for (auto it = m_pop_notifications.begin(); it != m_pop_notifications.end();) {
    std::unique_ptr<PopNotification>& notification = *it;
    request_render |= notification->update_state(hover, time_since_render);
    next_render = std::min<int64_t>(next_render, notification->next_render());
    if (notification->get_state() == PopNotification::EState::Finished)
      it = m_pop_notifications.erase(it);
    else
      ++it;
  }
  // delayed notifications
  for (auto it = m_waiting_notifications.begin(); it != m_waiting_notifications.end();) {
    // substract time
    if ((*it).remaining_time > 0)
      (*it).remaining_time -= time_since_render;
    if ((*it).remaining_time <= 0) {
      if ((*it).notification && (*it).condition_callback()) { // push notification, erase it from waiting list (frame is scheduled by push)
        (*it).notification->reset_timer();
        // if activate_existing returns false, we expect push to return true.
        if(!this->activate_existing((*it).notification.get()) || (*it).delay_interval == 0) {
          push_notification_data(std::move((*it).notification), 0);
          it = m_waiting_notifications.erase(it);
          continue;
        }
      }
      // not possible to push, delay for delay_interval
      (*it).remaining_time = (*it).delay_interval;
    }
    next_render = std::min<int64_t>(next_render, (*it).remaining_time);
    ++it;
  }
  // request next frame in future
  if (next_render < max)
    canvas.schedule_extra_frame(int(next_render));
  return request_render;
}
References activate_existing(), Slic3r::GUI::NotificationManager::PopNotification::Finished, m_last_render, m_pop_notifications, m_waiting_notifications, push_notification_data(), Slic3r::GUI::GLCanvas3D::schedule_extra_frame(), and Slic3r::GUI::GLCanvas3D::timestamp_now().
upload_job_notification_show_canceled()
void Slic3r::GUI::NotificationManager::upload_job_notification_show_canceled (int id, const std::string & filename, const std::string & host)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PrintHostUpload) {
      PrintHostUploadNotification* phun = dynamic_cast<PrintHostUploadNotification*>(notification.get());
      if (phun->compare_job_id(id)) {
        phun->cancel();
        if (phun->get_host() != host)
          phun->set_host(host);
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
        break;
      }
    }
  }
}
References Slic3r::GUI::NotificationManager::PrintHostUploadNotification::cancel(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::compare_job_id(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::get_host(), m_pop_notifications, Slic3r::GUI::PrintHostUpload, and Slic3r::GUI::NotificationManager::PrintHostUploadNotification::set_host().
upload_job_notification_show_error()
void Slic3r::GUI::NotificationManager::upload_job_notification_show_error (int id, const std::string & filename, const std::string & host)
{
  for (std::unique_ptr<PopNotification>& notification : m_pop_notifications) {
    if (notification->get_type() == NotificationType::PrintHostUpload) {
      PrintHostUploadNotification* phun = dynamic_cast<PrintHostUploadNotification*>(notification.get());
      if(phun->compare_job_id(id)) {
        phun->error();
        if (phun->get_host() != host)
          phun->set_host(host);
        wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);
        break;
      }
    }
  }
}
References Slic3r::GUI::NotificationManager::PrintHostUploadNotification::compare_job_id(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::error(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::get_host(), m_pop_notifications, Slic3r::GUI::PrintHostUpload, and Slic3r::GUI::NotificationManager::PrintHostUploadNotification::set_host().
Member Data Documentation
basic_notifications
const std::vector<NotificationData> Slic3r::GUI::NotificationManager::basic_notifications private
Referenced by push_delayed_notification(), and push_notification().
m_evt_handler
wxEvtHandler* Slic3r::GUI::NotificationManager::m_evt_handler private
Referenced by init_progress_indicator(), init_slicing_progress_notification(), Slic3r::GUI::NotificationManager::PopNotification::on_text_click(), push_delayed_notification(), push_download_progress_notification(), push_download_URL_progress_notification(), push_exporting_finished_notification(), push_hint_notification(), push_notification_data(), push_plater_warning_notification(), push_simplify_suggestion_notification(), push_slicing_warning_notification(), push_updated_item_info_notification(), push_upload_job_notification(), and Slic3r::GUI::NotificationManager::ExportFinishedNotification::render_eject_button().
m_id_provider
NotificationIDProvider Slic3r::GUI::NotificationManager::m_id_provider private
Referenced by init_progress_indicator(), init_slicing_progress_notification(), push_delayed_notification(), push_download_progress_notification(), push_download_URL_progress_notification(), push_exporting_finished_notification(), push_hint_notification(), push_notification_data(), push_plater_warning_notification(), push_simplify_suggestion_notification(), push_slicing_warning_notification(), push_updated_item_info_notification(), push_upload_job_notification(), and Slic3r::GUI::NotificationManager::PopNotification::render().
m_in_preview
bool Slic3r::GUI::NotificationManager::m_in_preview { false } private
Referenced by apply_in_preview(), render_notifications(), and set_in_preview().
m_initialized
bool Slic3r::GUI::NotificationManager::m_initialized { false } private
Referenced by init(), and push_notification_data().
m_last_render
int64_t Slic3r::GUI::NotificationManager::m_last_render { 0LL } private
Referenced by render_notifications(), and update_notifications().
m_move_from_overlay
bool Slic3r::GUI::NotificationManager::m_move_from_overlay { false } private
Referenced by render_notifications(), and set_move_from_overlay().
m_multiple_types
const std::vector<NotificationType> Slic3r::GUI::NotificationManager::m_multiple_types private
Initial value:
= {
    NotificationType::CustomNotification,
    NotificationType::PlaterWarning,
    NotificationType::ProgressBar,
    NotificationType::PrintHostUpload,
        NotificationType::SimplifySuggestion,
    NotificationType::URLDownload
  }
Referenced by activate_existing().
m_pop_notifications
std::deque<std::unique_ptr<PopNotification> > Slic3r::GUI::NotificationManager::m_pop_notifications private
Referenced by activate_existing(), close_notification_of_type(), close_plater_error_notification(), close_plater_warning_notification(), close_slicing_error_notification(), close_slicing_errors_and_warnings(), device_ejected(), get_notification_count(), has_slicing_error_notification(), init_progress_indicator(), init_slicing_progress_notification(), is_hint_notification_open(), progress_indicator_get_range(), progress_indicator_set_cancel_callback(), progress_indicator_set_progress(), progress_indicator_set_range(), progress_indicator_set_status_text(), push_download_progress_notification(), push_download_URL_progress_notification(), push_hint_notification(), push_notification_data(), push_plater_warning_notification(), push_slicing_warning_notification(), push_updated_item_info_notification(), push_upload_job_notification(), push_version_notification(), remove_simplify_suggestion_of_released_objects(), remove_simplify_suggestion_with_id(), remove_slicing_warnings_of_released_objects(), render_notifications(), set_all_slicing_errors_gray(), set_all_slicing_warnings_gray(), set_download_progress_percentage(), set_download_URL_canceled(), set_download_URL_error(), set_download_URL_paused(), set_download_URL_progress(), set_fff(), set_in_preview(), set_sidebar_collapsed(), set_slicing_complete_print_time(), set_slicing_progress_began(), set_slicing_progress_canceled(), set_slicing_progress_export_possible(), set_slicing_progress_hidden(), set_slicing_progress_percentage(), set_upload_job_notification_comp_on_100(), set_upload_job_notification_completed(), set_upload_job_notification_completed_with_warning(), set_upload_job_notification_host(), set_upload_job_notification_percentage(), set_upload_job_notification_status(), sort_notifications(), update_notifications(), upload_job_notification_show_canceled(), and upload_job_notification_show_error().
m_used_timestamps
std::unordered_set<int> Slic3r::GUI::NotificationManager::m_used_timestamps private
Referenced by push_notification_data().
m_waiting_notifications
std::vector<DelayedNotification> Slic3r::GUI::NotificationManager::m_waiting_notifications private
Referenced by push_delayed_notification_data(), stop_delayed_notifications_of_type(), and update_notifications().
The documentation for this class was generated from the following files:
src/slic3r/GUI/NotificationManager.hpp
src/slic3r/GUI/NotificationManager.cpp