Prusa Slicer: Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased > Struct Template Reference
#include <src/eigen/Eigen/src/Core/CoreEvaluators.h>
Public Types
enum { CoeffReadCost = evaluator<ArgType>::CoeffReadCost + functor_traits<UnaryOp>::Cost , Flags = (evaluator<ArgType>::Flags & (HereditaryBits | LinearAccessBit | DirectAccessBit)) , Alignment = 0 }
typedef CwiseUnaryView< UnaryOp, ArgType > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
enum
typedef traits< CwiseUnaryView< UnaryOp, ArgType > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC unary_evaluator (const XprType &op)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
Protected Attributes
const UnaryOp m_unaryOp
evaluator< ArgType > m_argImpl
Detailed Description
template<typename UnaryOp, typename ArgType>
struct Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >
Member Typedef Documentation
CoeffReturnType
template<typename UnaryOp , typename ArgType > typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::CoeffReturnType
ExpressionTraits
typedef traits<CwiseUnaryView< UnaryOp, ArgType > > Eigen::internal::evaluator_base< CwiseUnaryView< UnaryOp, ArgType > >::ExpressionTraits inherited
Scalar
template<typename UnaryOp , typename ArgType > typedef XprType::Scalar Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::Scalar
XprType
template<typename UnaryOp , typename ArgType > typedef CwiseUnaryView<UnaryOp, ArgType> Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    Alignment = 0
  };
anonymous enum
template<typename UnaryOp , typename ArgType > anonymous enum
Enumerator
CoeffReadCost
Flags
Alignment
       {
    CoeffReadCost = evaluator<ArgType>::CoeffReadCost + functor_traits<UnaryOp>::Cost,
    Flags = (evaluator<ArgType>::Flags & (HereditaryBits | LinearAccessBit | DirectAccessBit)),
    Alignment = 0 // FIXME it is not very clear why alignment is necessarily lost...
  };
Constructor & Destructor Documentation
unary_evaluator()
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::unary_evaluator (const XprType & op) inline explicit
    : m_unaryOp(op.functor()),
      m_argImpl(op.nestedExpression())
  {
    EIGEN_INTERNAL_CHECK_COST_VALUE(functor_traits<UnaryOp>::Cost);
    EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
  }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::coeff (Index index) const inline
  {
    return m_unaryOp(m_argImpl.coeff(index));
  }
coeff() [2/2]
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::coeff (Index row, Index col) const inline
  {
    return m_unaryOp(m_argImpl.coeff(row, col));
  }
References col(), and row().
coeffRef() [1/2]
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::coeffRef (Index index) inline
  {
    return m_unaryOp(m_argImpl.coeffRef(index));
  }
coeffRef() [2/2]
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::coeffRef (Index row, Index col) inline
  {
    return m_unaryOp(m_argImpl.coeffRef(row, col));
  }
References col(), and row().
Member Data Documentation
m_argImpl
template<typename UnaryOp , typename ArgType > evaluator<ArgType> Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::m_argImpl protected
m_unaryOp
template<typename UnaryOp , typename ArgType > const UnaryOp Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::m_unaryOp protected
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/CoreEvaluators.h