Prusa Slicer: Slic3r::GUI::Job::Ctl Class Reference
Slic3r::GUI::Job::Ctl Class Reference abstract
#include <src/slic3r/GUI/Jobs/Job.hpp>
Public Member Functions
virtual ~Ctl ()=default
virtual void update_status (int st, const std::string &msg="")=0
virtual bool was_canceled () const =0
virtual std::future< void > call_on_main_thread (std::function< void()> fn)=0
Detailed Description
Constructor & Destructor Documentation
~Ctl()
virtual Slic3r::GUI::Job::Ctl::~Ctl () virtual default
Member Function Documentation
call_on_main_thread()
virtual std::future< void > Slic3r::GUI::Job::Ctl::call_on_main_thread (std::function< void()> fn) pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, and Slic3r::GUI::UIThreadWorker.
Referenced by Slic3r::GUI::CursorSetterRAII::CursorSetterRAII(), Slic3r::GUI::CursorSetterRAII::~CursorSetterRAII(), Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::process(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::CancellableJob< JobSubclass >::process(), and Slic3r::GUI::FillBedJob::process().
update_status()
virtual void Slic3r::GUI::Job::Ctl::update_status (int st, const std::string & msg = "") pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, and Slic3r::GUI::UIThreadWorker.
Referenced by Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::process(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::CancellableJob< JobSubclass >::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::RotoptimizeJob::process(), and Slic3r::GUI::SLAImportJob::process().
was_canceled()
virtual bool Slic3r::GUI::Job::Ctl::was_canceled () const pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, and Slic3r::GUI::UIThreadWorker.
Referenced by Slic3r::GUI::PlaterWorker< WorkerSubclass >::PlaterJob::process(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::CancellableJob< JobSubclass >::process(), Slic3r::GUI::CreateFontImageJob::process(), Slic3r::GUI::Emboss::CreateVolumeJob::process(), Slic3r::GUI::Emboss::CreateObjectJob::process(), Slic3r::GUI::Emboss::UpdateJob::process(), Slic3r::GUI::Emboss::CreateSurfaceVolumeJob::process(), Slic3r::GUI::Emboss::UpdateSurfaceVolumeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::RotoptimizeJob::process(), and Slic3r::GUI::SLAImportJob::process().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Jobs/Job.hpp