Prusa Slicer: Eigen::MapBase< Derived, WriteAccessors > Class Template Reference
Eigen::MapBase< Derived, WriteAccessors > Class Template Reference
Base class for non-const dense Map and Block expression with direct access.
#include <src/eigen/Eigen/src/Core/MapBase.h>
Public Types
typedef MapBase< Derived, ReadOnlyAccessors > Base
typedef Base::Scalar Scalar
typedef Base::PacketScalar PacketScalar
typedef Base::StorageIndex StorageIndex
typedef Base::PointerType PointerType
typedef internal::conditional< internal::is_lvalue< Derived >::value, Scalar, constScalar >::type ScalarWithConstIfNotLvalue
enum { RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , InnerStrideAtCompileTime = internal::traits<Derived>::InnerStrideAtCompileTime , SizeAtCompileTime = Base::SizeAtCompileTime }
typedef internal::traits< Derived >::StorageKind StorageKind
typedef NumTraits< Scalar >::Real RealScalar
typedef Base::CoeffReturnType CoeffReturnType
Public Member Functions
EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue * data ()
EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue & coeffRef (Index index)
template<int StoreMode>
void writePacket (Index row, Index col, const PacketScalar &val)
template<int StoreMode>
void writePacket (Index index, const PacketScalar &val)
EIGEN_DEVICE_FUNC MapBase (PointerType dataPtr)
EIGEN_DEVICE_FUNC MapBase (PointerType dataPtr, Index vecSize)
EIGEN_DEVICE_FUNC MapBase (PointerType dataPtr, Index rows, Index cols)
EIGEN_DEVICE_FUNC Derived & operator= (const MapBase &other)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
EIGEN_DEVICE_FUNC const Scalar & coeff (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC const Scalar & coeff (Index index) const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index index) const
template<int LoadMode>
PacketScalar packet (Index rowId, Index colId) const
template<int LoadMode>
PacketScalar packet (Index index) const
Protected Member Functions
template<typename T >
EIGEN_DEVICE_FUNC void checkSanity (typename internal::enable_if<(internal::traits< T >::Alignment >0), void * >::type=0) const
template<typename T >
EIGEN_DEVICE_FUNC void checkSanity (typename internal::enable_if< internal::traits< T >::Alignment==0, void * >::type=0) const
Protected Attributes
PointerType m_data
const internal::variable_if_dynamic< Index, RowsAtCompileTime > m_rows
const internal::variable_if_dynamic< Index, ColsAtCompileTime > m_cols
Private Types
typedef MapBase< Derived, ReadOnlyAccessors > ReadOnlyMapBase
Detailed Description
template<typename Derived>
class Eigen::MapBase< Derived, WriteAccessors >
Base class for non-const dense Map and Block expression with direct access.
This base class provides the non-const low-level accessors (e.g. coeff and coeffRef) of dense Map and Block objects with direct access. It inherits MapBase<Derived, ReadOnlyAccessors> which defines the const variant for reading specific entries.
See also
class Map, class Block
Member Typedef Documentation
Base
template<typename Derived > typedef MapBase<Derived, ReadOnlyAccessors> Eigen::MapBase< Derived, WriteAccessors >::Base
CoeffReturnType
template<typename Derived > typedef Base::CoeffReturnType Eigen::MapBase< Derived, ReadOnlyAccessors >::CoeffReturnType inherited
PacketScalar
template<typename Derived > typedef Base::PacketScalar Eigen::MapBase< Derived, WriteAccessors >::PacketScalar
PointerType
template<typename Derived > typedef Base::PointerType Eigen::MapBase< Derived, WriteAccessors >::PointerType
ReadOnlyMapBase
template<typename Derived > typedef MapBase<Derived, ReadOnlyAccessors> Eigen::MapBase< Derived, WriteAccessors >::ReadOnlyMapBase private
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::MapBase< Derived, ReadOnlyAccessors >::RealScalar inherited
Scalar
template<typename Derived > typedef Base::Scalar Eigen::MapBase< Derived, WriteAccessors >::Scalar
ScalarWithConstIfNotLvalue
template<typename Derived > typedef internal::conditional<internal::is_lvalue<Derived>::value,Scalar,constScalar>::type Eigen::MapBase< Derived, WriteAccessors >::ScalarWithConstIfNotLvalue
StorageIndex
template<typename Derived > typedef Base::StorageIndex Eigen::MapBase< Derived, WriteAccessors >::StorageIndex
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::MapBase< Derived, ReadOnlyAccessors >::StorageKind inherited
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
RowsAtCompileTime
ColsAtCompileTime
InnerStrideAtCompileTime
SizeAtCompileTime
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      InnerStrideAtCompileTime = internal::traits<Derived>::InnerStrideAtCompileTime,
      SizeAtCompileTime = Base::SizeAtCompileTime
    };
Constructor & Destructor Documentation
MapBase() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::MapBase< Derived, WriteAccessors >::MapBase (PointerType dataPtr) inline explicit
: Base(dataPtr) {}
MapBase() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::MapBase< Derived, WriteAccessors >::MapBase (PointerType dataPtr, Index vecSize) inline
: Base(dataPtr, vecSize) {}
MapBase() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::MapBase< Derived, WriteAccessors >::MapBase (PointerType dataPtr, Index rows, Index cols) inline
: Base(dataPtr, rows, cols) {}
Member Function Documentation
checkSanity() [1/2]
template<typename Derived > template<typename T > EIGEN_DEVICE_FUNC void Eigen::MapBase< Derived, ReadOnlyAccessors >::checkSanity (typename internal::enable_if< internal::traits< T >::Alignment==0, void * >::type = 0) const inline protected inherited
    {}
checkSanity() [2/2]
template<typename Derived > template<typename T > EIGEN_DEVICE_FUNC void Eigen::MapBase< Derived, ReadOnlyAccessors >::checkSanity (typename internal::enable_if<(internal::traits< T >::Alignment >0), void * >::type = 0) const inline protected inherited
    {
#if EIGEN_MAX_ALIGN_BYTES>0
      // innerStride() is not set yet when this function is called, so we optimistically assume the lowest plausible value:
      const Index minInnerStride = InnerStrideAtCompileTime == Dynamic ? 1 : Index(InnerStrideAtCompileTime);
      EIGEN_ONLY_USED_FOR_DEBUG(minInnerStride);
      eigen_assert((   ((internal::UIntPtr(m_data) % internal::traits<Derived>::Alignment) == 0)
                    || (cols() * rows() * minInnerStride * sizeof(Scalar)) < internal::traits<Derived>::Alignment ) && "data is not aligned");
#endif
    }
References Eigen::Dynamic, eigen_assert, and EIGEN_ONLY_USED_FOR_DEBUG.
coeff() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Scalar & Eigen::MapBase< Derived, ReadOnlyAccessors >::coeff (Index index) const inline
This is an overloaded version of DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index) const for details.
    {
      EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS(Derived)
      return m_data[index * innerStride()];
    }
coeff() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Scalar & Eigen::MapBase< Derived, ReadOnlyAccessors >::coeff (Index rowId, Index colId) const inline
This is an overloaded version of DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index,Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index) const for details.
    {
      return m_data[colId * colStride() + rowId * rowStride()];
    }
coeffRef() [1/4]
template<typename Derived > EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue & Eigen::MapBase< Derived, WriteAccessors >::coeffRef (Index index) inline
    {
      EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS(Derived)
      return this->m_data[index * innerStride()];
    }
References EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS.
coeffRef() [2/4]
template<typename Derived > EIGEN_DEVICE_FUNC const Scalar & Eigen::MapBase< Derived, ReadOnlyAccessors >::coeffRef (Index index) const inline
This is the const version of coeffRef(Index) which is thus synonym of coeff(Index). It is provided for convenience.
    {
      EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS(Derived)
      return this->m_data[index * innerStride()];
    }
coeffRef() [3/4]
template<typename Derived > EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue & Eigen::MapBase< Derived, WriteAccessors >::coeffRef (Index row, Index col) inline
    {
      return this->m_data[col * colStride() + row * rowStride()];
    }
References col(), and row().
coeffRef() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC const Scalar & Eigen::MapBase< Derived, ReadOnlyAccessors >::coeffRef (Index rowId, Index colId) const inline
This is the const version of coeffRef(Index,Index) which is thus synonym of coeff(Index,Index). It is provided for convenience.
    {
      return this->m_data[colId * colStride() + rowId * rowStride()];
    }
cols()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::MapBase< Derived, ReadOnlyAccessors >::cols () const inline
{ return m_cols.value(); }
data() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue * Eigen::MapBase< Derived, WriteAccessors >::data () inline
{ return this->m_data; } // no const-cast here so non-const-correct code will give a compile error
data() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Scalar * Eigen::MapBase< Derived, WriteAccessors >::data () const inline
{ return this->m_data; }
operator=()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::MapBase< Derived, WriteAccessors >::operator= (const MapBase< Derived, WriteAccessors > & other) inline
    {
      ReadOnlyMapBase::Base::operator=(other);
      return derived();
    }
packet() [1/2]
template<typename Derived > template<int LoadMode> PacketScalar Eigen::MapBase< Derived, ReadOnlyAccessors >::packet (Index index) const inline inherited
    {
      EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS(Derived)
      return internal::ploadt<PacketScalar, LoadMode>(m_data + index * innerStride());
    }
References EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS.
packet() [2/2]
template<typename Derived > template<int LoadMode> PacketScalar Eigen::MapBase< Derived, ReadOnlyAccessors >::packet (Index rowId, Index colId) const inline inherited
    {
      return internal::ploadt<PacketScalar, LoadMode>
               (m_data + (colId * colStride() + rowId * rowStride()));
    }
rows()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::MapBase< Derived, ReadOnlyAccessors >::rows () const inline
{ return m_rows.value(); }
writePacket() [1/2]
template<typename Derived > template<int StoreMode> void Eigen::MapBase< Derived, WriteAccessors >::writePacket (Index index, const PacketScalar & val) inline
    {
      EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS(Derived)
      internal::pstoret<Scalar, PacketScalar, StoreMode>
                (this->m_data + index * innerStride(), val);
    }
References EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS.
writePacket() [2/2]
template<typename Derived > template<int StoreMode> void Eigen::MapBase< Derived, WriteAccessors >::writePacket (Index row, Index col, const PacketScalar & val) inline
    {
      internal::pstoret<Scalar, PacketScalar, StoreMode>
               (this->m_data + (col * colStride() + row * rowStride()), val);
    }
References col(), and row().
Member Data Documentation
m_cols
template<typename Derived > const internal::variable_if_dynamic<Index, ColsAtCompileTime> Eigen::MapBase< Derived, ReadOnlyAccessors >::m_cols protected inherited
m_data
template<typename Derived > PointerType Eigen::MapBase< Derived, ReadOnlyAccessors >::m_data protected inherited
m_rows
template<typename Derived > const internal::variable_if_dynamic<Index, RowsAtCompileTime> Eigen::MapBase< Derived, ReadOnlyAccessors >::m_rows protected inherited
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/MapBase.h