Prusa Slicer: Slic3r::Arachne::STHalfEdgeNode Class Reference
Slic3r::Arachne::STHalfEdgeNode Class Reference
#include <src/libslic3r/Arachne/SkeletalTrapezoidationGraph.hpp>
Public Member Functions
STHalfEdgeNode (SkeletalTrapezoidationJoint data, Point p)
bool isMultiIntersection ()
bool isCentral () const
bool isLocalMaximum (bool strict=false) const
bool operator== (const node_t &other)
Public Attributes
SkeletalTrapezoidationJoint data
Point p
edge_t * incident_edge
Private Types
using edge_t = STHalfEdge
using node_t = STHalfEdgeNode
Detailed Description
Member Typedef Documentation
edge_t
using Slic3r::Arachne::STHalfEdgeNode::edge_t = STHalfEdge private
node_t
using Slic3r::Arachne::STHalfEdgeNode::node_t = STHalfEdgeNode private
Constructor & Destructor Documentation
STHalfEdgeNode()
Slic3r::Arachne::STHalfEdgeNode::STHalfEdgeNode (SkeletalTrapezoidationJoint data, Point p)
: HalfEdgeNode(data, p) {}
Member Function Documentation
isCentral()
bool Slic3r::Arachne::STHalfEdgeNode::isCentral () const
{
    edge_t* edge = incident_edge;
    do
    {
        if (edge->data.isCentral())
        {
            return true;
        }
        assert(edge->twin); if (!edge->twin) return false;
    } while (edge = edge->twin->next, edge != incident_edge);
    return false;
}
References Slic3r::Arachne::HalfEdge< node_data_t, edge_data_t, derived_node_t, derived_edge_t >::data, Slic3r::Arachne::HalfEdgeNode< SkeletalTrapezoidationJoint, SkeletalTrapezoidationEdge, STHalfEdgeNode, STHalfEdge >::incident_edge, Slic3r::Arachne::SkeletalTrapezoidationEdge::isCentral(), Slic3r::Arachne::HalfEdge< node_data_t, edge_data_t, derived_node_t, derived_edge_t >::next, and Slic3r::Arachne::HalfEdge< node_data_t, edge_data_t, derived_node_t, derived_edge_t >::twin.
isLocalMaximum()
bool Slic3r::Arachne::STHalfEdgeNode::isLocalMaximum (bool strict = false) const
Check whether this node has a locally maximal distance_to_boundary
Parameters
strict Whether equidistant edges can count as a local maximum
{
    if (data.distance_to_boundary == 0)
    {
        return false;
    }
    edge_t* edge = incident_edge;
    do
    {
        if (edge->canGoUp(strict))
        {
            return false;
        }
        assert(edge->twin); if (!edge->twin) return false;
        if (!edge->twin->next)
        { // This point is on the boundary
            return false;
        }
    } while (edge = edge->twin->next, edge != incident_edge);
    return true;
}
References Slic3r::Arachne::STHalfEdge::canGoUp(), Slic3r::Arachne::HalfEdgeNode< SkeletalTrapezoidationJoint, SkeletalTrapezoidationEdge, STHalfEdgeNode, STHalfEdge >::data, Slic3r::Arachne::SkeletalTrapezoidationJoint::distance_to_boundary, Slic3r::Arachne::HalfEdgeNode< SkeletalTrapezoidationJoint, SkeletalTrapezoidationEdge, STHalfEdgeNode, STHalfEdge >::incident_edge, Slic3r::Arachne::HalfEdge< node_data_t, edge_data_t, derived_node_t, derived_edge_t >::next, and Slic3r::Arachne::HalfEdge< node_data_t, edge_data_t, derived_node_t, derived_edge_t >::twin.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::filterCentral().
isMultiIntersection()
bool Slic3r::Arachne::STHalfEdgeNode::isMultiIntersection ()
{
    int odd_path_count = 0;
    edge_t* outgoing = this->incident_edge;
    do
    {
        if ( ! outgoing)
        { // This is a node on the outside
            return false;
        }
        if (outgoing->data.isCentral())
        {
            odd_path_count++;
        }
    } while (outgoing = outgoing->twin->next, outgoing != this->incident_edge);
    return odd_path_count > 2;
}
References Slic3r::Arachne::HalfEdge< node_data_t, edge_data_t, derived_node_t, derived_edge_t >::data, Slic3r::Arachne::HalfEdgeNode< SkeletalTrapezoidationJoint, SkeletalTrapezoidationEdge, STHalfEdgeNode, STHalfEdge >::incident_edge, Slic3r::Arachne::SkeletalTrapezoidationEdge::isCentral(), Slic3r::Arachne::HalfEdge< node_data_t, edge_data_t, derived_node_t, derived_edge_t >::next, and Slic3r::Arachne::HalfEdge< node_data_t, edge_data_t, derived_node_t, derived_edge_t >::twin.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::connectJunctions().
operator==()
bool Slic3r::Arachne::HalfEdgeNode< SkeletalTrapezoidationJoint , SkeletalTrapezoidationEdge , STHalfEdgeNode , STHalfEdge >::operator== (const node_t & other) inline inherited
    {
        return this == &other;
    }
Member Data Documentation
data
SkeletalTrapezoidationJoint Slic3r::Arachne::HalfEdgeNode< SkeletalTrapezoidationJoint , SkeletalTrapezoidationEdge , STHalfEdgeNode , STHalfEdge >::data inherited
incident_edge
edge_t* Slic3r::Arachne::HalfEdgeNode< SkeletalTrapezoidationJoint , SkeletalTrapezoidationEdge , STHalfEdgeNode , STHalfEdge >::incident_edge inherited
p
Point Slic3r::Arachne::HalfEdgeNode< SkeletalTrapezoidationJoint , SkeletalTrapezoidationEdge , STHalfEdgeNode , STHalfEdge >::p inherited
The documentation for this class was generated from the following files:
src/libslic3r/Arachne/SkeletalTrapezoidationGraph.hpp
src/libslic3r/Arachne/SkeletalTrapezoidationGraph.cpp