Prusa Slicer: Eigen::ReturnByValue< Derived > Class Template Reference
Eigen::ReturnByValue< Derived > Class Template Reference
#include <src/eigen/Eigen/src/Core/ReturnByValue.h>
Classes
class Unusable
Public Types
typedef internal::traits< Derived >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Detailed Description
template<typename Derived>
class Eigen::ReturnByValue< Derived >
Member Typedef Documentation
Base
template<typename Derived > typedef internal::dense_xpr_base<ReturnByValue>::type Eigen::ReturnByValue< Derived >::Base
ReturnType
template<typename Derived > typedef internal::traits<Derived>::ReturnType Eigen::ReturnByValue< Derived >::ReturnType
Member Function Documentation
coeff() [1/2]
template<typename Derived > const Unusable & Eigen::ReturnByValue< Derived >::coeff (Index) const inline
{ return *reinterpret_cast<const Unusable*>(this); }
coeff() [2/2]
template<typename Derived > const Unusable & Eigen::ReturnByValue< Derived >::coeff (Index , Index) const inline
{ return *reinterpret_cast<const Unusable*>(this); }
coeffRef() [1/2]
template<typename Derived > Unusable & Eigen::ReturnByValue< Derived >::coeffRef (Index) inline
{ return *reinterpret_cast<Unusable*>(this); }
coeffRef() [2/2]
template<typename Derived > Unusable & Eigen::ReturnByValue< Derived >::coeffRef (Index , Index) inline
{ return *reinterpret_cast<Unusable*>(this); }
cols()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::ReturnByValue< Derived >::cols () const inline
{ return static_cast<const Derived*>(this)->cols(); }
References Eigen::ReturnByValue< Derived >::cols().
Referenced by Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::PlainObjectBase< Derived >::_init1(), Eigen::ReturnByValue< Derived >::cols(), and Eigen::PlainObjectBase< Derived >::operator=().
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::ReturnByValue< Derived >::evalTo (Dest & dst) const inline
    { static_cast<const Derived*>(this)->evalTo(dst); }
References Eigen::ReturnByValue< Derived >::evalTo().
Referenced by Eigen::internal::evaluator< ReturnByValue< Derived > >::evaluator(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::Transform(), Eigen::PlainObjectBase< Derived >::_init1(), Eigen::ReturnByValue< Derived >::evalTo(), Eigen::MatrixBase< Derived >::operator=(), Eigen::DenseBase< Derived >::operator=(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), and Eigen::SparseMatrixBase< Derived >::operator=().
rows()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::ReturnByValue< Derived >::rows () const inline
{ return static_cast<const Derived*>(this)->rows(); }
References Eigen::ReturnByValue< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::PlainObjectBase< Derived >::_init1(), Eigen::PlainObjectBase< Derived >::operator=(), and Eigen::ReturnByValue< Derived >::rows().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/ReturnByValue.h