Prusa Slicer: libnest2d::_Circle< P > Class Template Reference
libnest2d::_Circle< P > Class Template Reference
#include <src/libnest2d/include/libnest2d/geometry_traits.hpp>
Public Types
using Tag = CircleTag
using PointType = P
Public Member Functions
_Circle ()=default
_Circle (const P &center, double r)
const P & center () const BP2D_NOEXCEPT
void center (const P &c)
double radius () const BP2D_NOEXCEPT
void radius (double r)
double area () const BP2D_NOEXCEPT
Private Attributes
P center_
double radius_ = 0
Detailed Description
template<class P>
class libnest2d::_Circle< P >
Member Typedef Documentation
PointType
template<class P > using libnest2d::_Circle< P >::PointType = P
Tag
template<class P > using libnest2d::_Circle< P >::Tag = CircleTag
Constructor & Destructor Documentation
_Circle() [1/2]
template<class P > libnest2d::_Circle< P >::_Circle () default
_Circle() [2/2]
template<class P > libnest2d::_Circle< P >::_Circle (const P & center, double r) inline
: center_(center), radius_(r) {}
Member Function Documentation
area()
template<class P > double libnest2d::_Circle< P >::area () const inline
{
        return Pi_2 * radius_ * radius_;
    }
References libnest2d::Pi_2, and libnest2d::_Circle< P >::radius_.
Referenced by libnest2d::shapelike::area().
center() [1/2]
template<class P > const P & libnest2d::_Circle< P >::center () const inline
{ return center_; }
References libnest2d::_Circle< P >::center_.
Referenced by libnest2d::shapelike::boundingBox().
center() [2/2]
template<class P > void libnest2d::_Circle< P >::center (const P & c) inline
{ center_ = c; }
References libnest2d::_Circle< P >::center_.
radius() [1/2]
template<class P > double libnest2d::_Circle< P >::radius () const inline
{ return radius_; }
References libnest2d::_Circle< P >::radius_.
Referenced by libnest2d::shapelike::boundingBox(), libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit(), and libnest2d::placers::_NofitPolyPlacer< RawShape, TBin >::overfit().
radius() [2/2]
template<class P > void libnest2d::_Circle< P >::radius (double r) inline
{ radius_ = r; }
References libnest2d::_Circle< P >::radius_.
Member Data Documentation
center_
template<class P > P libnest2d::_Circle< P >::center_ private
Referenced by libnest2d::_Circle< P >::center(), and libnest2d::_Circle< P >::center().
radius_
template<class P > double libnest2d::_Circle< P >::radius_ = 0 private
Referenced by libnest2d::_Circle< P >::area(), libnest2d::_Circle< P >::radius(), and libnest2d::_Circle< P >::radius().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/geometry_traits.hpp