Prusa Slicer: Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true > Class Template Reference
#include <src/eigen/Eigen/src/SVD/JacobiSVD.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime ,
Options = MatrixType::Options
}
typedef MatrixType::Scalar Scalar
typedef Matrix< Scalar, ColsAtCompileTime, RowsAtCompileTime, Options, MaxColsAtCompileTime, MaxRowsAtCompileTime > TransposeTypeWithSameStorageOrder
Public Member Functions
void allocate (const JacobiSVD< MatrixType, HouseholderQRPreconditioner > &svd)
bool run (JacobiSVD< MatrixType, HouseholderQRPreconditioner > &svd, const MatrixType &matrix)
Private Types
typedef HouseholderQR< TransposeTypeWithSameStorageOrder > QRType
Private Attributes
QRType m_qr
TransposeTypeWithSameStorageOrder m_adjoint
internal::plain_row_type< MatrixType >::type m_workspace
Detailed Description
template<typename MatrixType>
class Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >
Member Typedef Documentation
QRType
template<typename MatrixType > typedef HouseholderQR<TransposeTypeWithSameStorageOrder> Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::QRType private
Scalar
template<typename MatrixType > typedef MatrixType::Scalar Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::Scalar
TransposeTypeWithSameStorageOrder
template<typename MatrixType > typedef Matrix<Scalar, ColsAtCompileTime, RowsAtCompileTime, Options, MaxColsAtCompileTime, MaxRowsAtCompileTime> Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::TransposeTypeWithSameStorageOrder
Member Enumeration Documentation
anonymous enum
template<typename MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Options
  {
    RowsAtCompileTime = MatrixType::RowsAtCompileTime,
    ColsAtCompileTime = MatrixType::ColsAtCompileTime,
    MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
    MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime,
    Options = MatrixType::Options
  };
Member Function Documentation
allocate()
template<typename MatrixType > void Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate (const JacobiSVD< MatrixType, HouseholderQRPreconditioner > & svd) inline
  {
    if (svd.cols() != m_qr.rows() || svd.rows() != m_qr.cols())
    {
      m_qr.~QRType();
      ::new (&m_qr) QRType(svd.cols(), svd.rows());
    }
    if (svd.m_computeFullV) m_workspace.resize(svd.cols());
    else if (svd.m_computeThinV) m_workspace.resize(svd.rows());
    m_adjoint.resize(svd.cols(), svd.rows());
  }
References Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::cols(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeFullV, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeThinV, and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::rows().
run()
template<typename MatrixType > bool Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run (JacobiSVD< MatrixType, HouseholderQRPreconditioner > & svd, const MatrixType & matrix) inline
  {
    if(matrix.cols() > matrix.rows())
    {
      m_adjoint = matrix.adjoint();
      m_qr.compute(m_adjoint);
      svd.m_workMatrix = m_qr.matrixQR().block(0,0,matrix.rows(),matrix.rows()).template triangularView<Upper>().adjoint();
      if(svd.m_computeFullV) m_qr.householderQ().evalTo(svd.m_matrixV, m_workspace);
      else if(svd.m_computeThinV)
      {
        svd.m_matrixV.setIdentity(matrix.cols(), matrix.rows());
        m_qr.householderQ().applyThisOnTheLeft(svd.m_matrixV, m_workspace);
      }
      if(svd.computeU()) svd.m_matrixU.setIdentity(matrix.rows(), matrix.rows());
      return true;
    }
    else return false;
  }
References Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::computeU(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeFullV, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_computeThinV, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_matrixU, Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_matrixV, and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::m_workMatrix.
Member Data Documentation
m_adjoint
template<typename MatrixType > TransposeTypeWithSameStorageOrder Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_adjoint private
m_qr
template<typename MatrixType > QRType Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_qr private
m_workspace
template<typename MatrixType > internal::plain_row_type<MatrixType>::type Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_workspace private
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SVD/JacobiSVD.h