Prusa Slicer: Slic3r::Arachne::SkeletalTrapezoidationEdge Class Reference
Slic3r::Arachne::SkeletalTrapezoidationEdge Class Reference
#include <src/libslic3r/Arachne/SkeletalTrapezoidationEdge.hpp>
Classes
struct TransitionEnd
struct TransitionMiddle
Public Types
enum class EdgeType { NORMAL = 0 , EXTRA_VD = 1 , TRANSITION_END = 2 }
Public Member Functions
SkeletalTrapezoidationEdge ()
SkeletalTrapezoidationEdge (const EdgeType &type)
bool isCentral () const
void setIsCentral (bool b)
bool centralIsSet () const
bool hasTransitions (bool ignore_empty=false) const
void setTransitions (std::shared_ptr< std::list< TransitionMiddle > > storage)
std::shared_ptr< std::list< TransitionMiddle > > getTransitions ()
bool hasTransitionEnds (bool ignore_empty=false) const
void setTransitionEnds (std::shared_ptr< std::list< TransitionEnd > > storage)
std::shared_ptr< std::list< TransitionEnd > > getTransitionEnds ()
bool hasExtrusionJunctions (bool ignore_empty=false) const
void setExtrusionJunctions (std::shared_ptr< LineJunctions > storage)
std::shared_ptr< LineJunctions > getExtrusionJunctions ()
Public Attributes
EdgeType type
Private Types
enum class Central { UNKNOWN = -1 , NO , YES }
Private Attributes
Central is_central
std::weak_ptr< std::list< TransitionMiddle > > transitions
whether the edge is significant; whether the source segments have a sharp angle; -1 is unknown
std::weak_ptr< std::list< TransitionEnd > > transition_ends
std::weak_ptr< LineJunctions > extrusion_junctions
Detailed Description
Member Enumeration Documentation
Central
enum class Slic3r::Arachne::SkeletalTrapezoidationEdge::Central strong private
Enumerator
UNKNOWN
NO
YES
{ UNKNOWN = -1, NO, YES };
EdgeType
enum class Slic3r::Arachne::SkeletalTrapezoidationEdge::EdgeType strong
Enumerator
NORMAL
EXTRA_VD
TRANSITION_END
    {
        NORMAL = 0, // from voronoi diagram
        EXTRA_VD = 1, // introduced to voronoi diagram in order to make the gMAT
        TRANSITION_END = 2 // introduced to voronoi diagram in order to make the gMAT
    };
Constructor & Destructor Documentation
SkeletalTrapezoidationEdge() [1/2]
Slic3r::Arachne::SkeletalTrapezoidationEdge::SkeletalTrapezoidationEdge () inline
: SkeletalTrapezoidationEdge(EdgeType::NORMAL) {}
SkeletalTrapezoidationEdge() [2/2]
Slic3r::Arachne::SkeletalTrapezoidationEdge::SkeletalTrapezoidationEdge (const EdgeType & type) inline
: type(type), is_central(Central::UNKNOWN) {}
Member Function Documentation
centralIsSet()
bool Slic3r::Arachne::SkeletalTrapezoidationEdge::centralIsSet () const inline
    {
        return is_central != Central::UNKNOWN;
    }
References is_central, and UNKNOWN.
getExtrusionJunctions()
std::shared_ptr< LineJunctions > Slic3r::Arachne::SkeletalTrapezoidationEdge::getExtrusionJunctions () inline
    {
        return extrusion_junctions.lock();
    }
References extrusion_junctions.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::connectJunctions().
getTransitionEnds()
std::shared_ptr< std::list< TransitionEnd > > Slic3r::Arachne::SkeletalTrapezoidationEdge::getTransitionEnds () inline
    {
        return transition_ends.lock();
    }
References transition_ends.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::generateTransitionEnd().
getTransitions()
std::shared_ptr< std::list< TransitionMiddle > > Slic3r::Arachne::SkeletalTrapezoidationEdge::getTransitions () inline
    {
        return transitions.lock();
    }
References transitions.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::dissolveNearbyTransitions(), and Slic3r::Arachne::SkeletalTrapezoidation::isGoingDown().
hasExtrusionJunctions()
bool Slic3r::Arachne::SkeletalTrapezoidationEdge::hasExtrusionJunctions (bool ignore_empty = false) const inline
    {
        return extrusion_junctions.use_count() > 0 && (ignore_empty || ! extrusion_junctions.lock()->empty());
    }
References extrusion_junctions.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::connectJunctions().
hasTransitionEnds()
bool Slic3r::Arachne::SkeletalTrapezoidationEdge::hasTransitionEnds (bool ignore_empty = false) const inline
    {
        return transition_ends.use_count() > 0 && (ignore_empty || ! transition_ends.lock()->empty());
    }
References transition_ends.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::generateTransitionEnd().
hasTransitions()
bool Slic3r::Arachne::SkeletalTrapezoidationEdge::hasTransitions (bool ignore_empty = false) const inline
    {
        return transitions.use_count() > 0 && (ignore_empty || ! transitions.lock()->empty());
    }
References transitions.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::dissolveNearbyTransitions(), and Slic3r::Arachne::SkeletalTrapezoidation::isGoingDown().
isCentral()
bool Slic3r::Arachne::SkeletalTrapezoidationEdge::isCentral () const inline
    {
        assert(is_central != Central::UNKNOWN);
        return is_central == Central::YES;
    }
References is_central, UNKNOWN, and YES.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::applyTransitions(), Slic3r::Arachne::SkeletalTrapezoidation::generateExtraRibs(), Slic3r::Arachne::SkeletalTrapezoidation::generateTransitionEnd(), Slic3r::Arachne::STHalfEdgeNode::isCentral(), Slic3r::Arachne::SkeletalTrapezoidation::isEndOfCentral(), and Slic3r::Arachne::STHalfEdgeNode::isMultiIntersection().
setExtrusionJunctions()
void Slic3r::Arachne::SkeletalTrapezoidationEdge::setExtrusionJunctions (std::shared_ptr< LineJunctions > storage) inline
    {
        extrusion_junctions = storage;
    }
References extrusion_junctions.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::connectJunctions().
setIsCentral()
void Slic3r::Arachne::SkeletalTrapezoidationEdge::setIsCentral (bool b) inline
    {
        is_central = b ? Central::YES : Central::NO;
    }
References is_central, NO, and YES.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::filterCentral(), Slic3r::Arachne::SkeletalTrapezoidation::filterNoncentralRegions(), and Slic3r::Arachne::SkeletalTrapezoidationGraph::insertRib().
setTransitionEnds()
void Slic3r::Arachne::SkeletalTrapezoidationEdge::setTransitionEnds (std::shared_ptr< std::list< TransitionEnd > > storage) inline
    {
        transition_ends = storage;
    }
References transition_ends.
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::generateTransitionEnd().
setTransitions()
void Slic3r::Arachne::SkeletalTrapezoidationEdge::setTransitions (std::shared_ptr< std::list< TransitionMiddle > > storage) inline
    {
        transitions = storage;
    }
References transitions.
Member Data Documentation
extrusion_junctions
std::weak_ptr<LineJunctions> Slic3r::Arachne::SkeletalTrapezoidationEdge::extrusion_junctions private
Referenced by getExtrusionJunctions(), hasExtrusionJunctions(), and setExtrusionJunctions().
is_central
Central Slic3r::Arachne::SkeletalTrapezoidationEdge::is_central private
Referenced by centralIsSet(), isCentral(), and setIsCentral().
transition_ends
std::weak_ptr<std::list<TransitionEnd> > Slic3r::Arachne::SkeletalTrapezoidationEdge::transition_ends private
Referenced by getTransitionEnds(), hasTransitionEnds(), and setTransitionEnds().
transitions
std::weak_ptr<std::list<TransitionMiddle> > Slic3r::Arachne::SkeletalTrapezoidationEdge::transitions private
whether the edge is significant; whether the source segments have a sharp angle; -1 is unknown
Referenced by getTransitions(), hasTransitions(), and setTransitions().
type
EdgeType Slic3r::Arachne::SkeletalTrapezoidationEdge::type
Referenced by Slic3r::Arachne::SkeletalTrapezoidation::applyTransitions(), and Slic3r::Arachne::SkeletalTrapezoidation::generateExtraRibs().
The documentation for this class was generated from the following file:
src/libslic3r/Arachne/SkeletalTrapezoidationEdge.hpp