Prusa Slicer: Slic3r::GUI::GLCanvas3D::SequentialPrintClearance Class Reference
Slic3r::GUI::GLCanvas3D::SequentialPrintClearance Class Reference
Public Member Functions
void set_contours (const ContoursList &contours, bool generate_fill)
void update_instances_trafos (const std::vector< Transform3d > &trafos)
void render ()
bool empty () const
Private Attributes
GLModel m_fill
std::vector< GLModel > m_contours
std::vector< std::pair< size_t, Transform3d > > m_instances
bool m_evaluating { false }
std::vector< std::pair< Pointf3s, Transform3d > > m_hulls_2d_cache
Friends
class GLCanvas3D
Detailed Description
Member Function Documentation
empty()
bool Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::empty () const inline
{ return m_contours.empty(); }
References m_contours.
Referenced by Slic3r::GUI::GLCanvas3D::is_sequential_print_clearance_empty(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
render()
void Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::render ()
{
    const ColorRGBA FILL_COLOR               = { 1.0f, 0.0f, 0.0f, 0.5f };
    const ColorRGBA NO_FILL_COLOR            = { 1.0f, 1.0f, 1.0f, 0.75f };
    const ColorRGBA NO_FILL_EVALUATING_COLOR = { 1.0f, 1.0f, 0.0f, 1.0f };
    if (m_contours.empty() || m_instances.empty())
        return;
    GLShaderProgram* shader = wxGetApp().get_shader("flat");
    if (shader == nullptr)
        return;
    shader->start_using();
    const Camera& camera = wxGetApp().plater()->get_camera();
    shader->set_uniform("view_model_matrix", camera.get_view_matrix());
    shader->set_uniform("projection_matrix", camera.get_projection_matrix());
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glDisable(GL_CULL_FACE));
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
    if (!m_evaluating)
        m_fill.render();
#if ENABLE_GL_CORE_PROFILE
    if (OpenGLManager::get_gl_info().is_core_profile()) {
        shader->stop_using();
        shader = wxGetApp().get_shader("dashed_thick_lines");
        if (shader == nullptr)
            return;
        shader->start_using();
        shader->set_uniform("projection_matrix", camera.get_projection_matrix());
        const std::array<int, 4>& viewport = camera.get_viewport();
        shader->set_uniform("viewport_size", Vec2d(double(viewport[2]), double(viewport[3])));
        shader->set_uniform("width", 1.0f);
        shader->set_uniform("gap_size", 0.0f);
    }
    else
#endif // ENABLE_GL_CORE_PROFILE
        glsafe(::glLineWidth(2.0f));
    for (const auto& [id, trafo] : m_instances) {
        shader->set_uniform("view_model_matrix", camera.get_view_matrix() * trafo);
        assert(id < m_contours.size());
        m_contours[id].set_color((!m_evaluating && m_fill.is_initialized()) ? FILL_COLOR : m_evaluating ? NO_FILL_EVALUATING_COLOR : NO_FILL_COLOR);
        m_contours[id].render();
    }
    glsafe(::glDisable(GL_BLEND));
    glsafe(::glEnable(GL_CULL_FACE));
    glsafe(::glDisable(GL_DEPTH_TEST));
    shader->stop_using();
}
References Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), glsafe, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
set_contours()
void Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours (const ContoursList & contours, bool generate_fill)
{
    m_contours.clear();
    m_instances.clear();
    m_fill.reset();
    if (contours.empty())
        return;
    if (generate_fill) {
        GLModel::Geometry fill_data;
        fill_data.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P3 };
        fill_data.color = { 0.3333f, 0.0f, 0.0f, 0.5f };
        // vertices + indices
        const ExPolygons polygons_union = union_ex(contours.contours);
        unsigned int vertices_counter = 0;
        for (const ExPolygon& poly : polygons_union) {
            const std::vector<Vec3d> triangulation = triangulate_expolygon_3d(poly);
            fill_data.reserve_vertices(fill_data.vertices_count() + triangulation.size());
            fill_data.reserve_indices(fill_data.indices_count() + triangulation.size());
            for (const Vec3d& v : triangulation) {
                fill_data.add_vertex((Vec3f)(v.cast<float>() + 0.0125f * Vec3f::UnitZ())); // add a small positive z to avoid z-fighting
                ++vertices_counter;
                if (vertices_counter % 3 == 0)
                    fill_data.add_triangle(vertices_counter - 3, vertices_counter - 2, vertices_counter - 1);
            }
        }
        m_fill.init_from(std::move(fill_data));
    }
    for (size_t i = 0; i < contours.contours.size(); ++i) {
        GLModel& model = m_contours.emplace_back(GLModel());
        model.init_from(contours.contours[i], 0.025f); // add a small positive z to avoid z-fighting
    }
    if (contours.trafos.has_value()) {
        // create the requested instances
        for (const auto& instance : *contours.trafos) {
            m_instances.emplace_back(instance.first, instance.second);
        }
    }
    else {
        // no instances have been specified
        // create one instance for every polygon
        for (size_t i = 0; i < contours.contours.size(); ++i) {
            m_instances.emplace_back(i, Transform3f::Identity());
        }
    }
}
References Slic3r::GUI::GLModel::Geometry::add_triangle(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::GUI::GLModel::Geometry::color, Slic3r::GUI::GLCanvas3D::ContoursList::contours, Slic3r::GUI::GLCanvas3D::ContoursList::empty(), Slic3r::GUI::GLModel::Geometry::format, Eigen::Transform< float, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::GUI::GLModel::Geometry::indices_count(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLModel::Geometry::P3, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GUI::GLCanvas3D::ContoursList::trafos, Slic3r::GUI::GLModel::Geometry::Triangles, Slic3r::triangulate_expolygon_3d(), Slic3r::union_ex(), and Slic3r::GUI::GLModel::Geometry::vertices_count().
Referenced by Slic3r::GUI::GLCanvas3D::reset_sequential_print_clearance(), and Slic3r::GUI::GLCanvas3D::set_sequential_print_clearance_contours().
update_instances_trafos()
void Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::update_instances_trafos (const std::vector< Transform3d > & trafos)
{
    if (trafos.size() == m_instances.size()) {
        for (size_t i = 0; i < trafos.size(); ++i) {
            m_instances[i].second = trafos[i];
        }
    }
    else
      assert(false);
}
Referenced by Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
Friends And Related Symbol Documentation
GLCanvas3D
friend class GLCanvas3D friend
Member Data Documentation
m_contours
std::vector<GLModel> Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_contours private
Referenced by empty().
m_evaluating
bool Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_evaluating { false } private
Referenced by Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::GUI::GLCanvas3D::is_sequential_print_clearance_evaluating(), Slic3r::GUI::GLCanvas3D::reset_sequential_print_clearance(), Slic3r::GUI::GLCanvas3D::set_sequential_clearance_as_evaluating(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
m_fill
GLModel Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_fill private
m_hulls_2d_cache
std::vector<std::pair<Pointf3s, Transform3d> > Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_hulls_2d_cache private
Referenced by Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
m_instances
std::vector<std::pair<size_t, Transform3d> > Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_instances private
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLCanvas3D.hpp
src/slic3r/GUI/GLCanvas3D.cpp