Prusa Slicer: Slic3r::GUI::KeyAutoRepeatFilter Class Reference
Slic3r::GUI::KeyAutoRepeatFilter Class Reference
#include <src/slic3r/GUI/GUI_Utils.hpp>
Public Member Functions
void increase_count ()
void reset_count ()
bool is_first () const
Private Attributes
size_t m_count { 0 }
Detailed Description
Member Function Documentation
increase_count()
void Slic3r::GUI::KeyAutoRepeatFilter::increase_count () inline
{ ++m_count; }
References m_count.
Referenced by Slic3r::GUI::GLGizmoMeasure::gizmo_event(), and Slic3r::GUI::GLCanvas3D::on_key().
is_first()
bool Slic3r::GUI::KeyAutoRepeatFilter::is_first () const inline
{ return m_count == 0; }
References m_count.
Referenced by Slic3r::GUI::GLGizmoMeasure::gizmo_event(), and Slic3r::GUI::GLCanvas3D::on_key().
reset_count()
void Slic3r::GUI::KeyAutoRepeatFilter::reset_count () inline
{ m_count = 0; }
References m_count.
Referenced by Slic3r::GUI::GLGizmoMeasure::gizmo_event(), Slic3r::GUI::GLCanvas3D::on_key(), and Slic3r::GUI::GLGizmoMeasure::on_set_state().
Member Data Documentation
m_count
size_t Slic3r::GUI::KeyAutoRepeatFilter::m_count { 0 } private
Referenced by increase_count(), is_first(), and reset_count().
The documentation for this class was generated from the following file:
src/slic3r/GUI/GUI_Utils.hpp