Prusa Slicer: src/avrdude/wiring.c File Reference
wiring.c File Reference
#include "ac_cfg.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "stk500v2_private.h"
#include "stk500v2.h"
#include "wiring.h"
Classes
struct wiringpdata
Macros
#define WIRINGPDATA(x) ((struct wiringpdata *)(x))
#define STK500V2PDATA(pgm) ((struct pdata *)(pgm->cookie))
Functions
static void wiring_setup (PROGRAMMER *pgm)
static void wiring_teardown (PROGRAMMER *pgm)
static int wiring_parseextparms (PROGRAMMER *pgm, LISTID extparms)
static int wiring_open (PROGRAMMER *pgm, char *port)
static void wiring_close (PROGRAMMER *pgm)
void wiring_initpgm (PROGRAMMER *pgm)
Variables
const char wiring_desc [] = "http://wiring.org.co/, Basically STK500v2 protocol, with some glue to trigger the bootloader."
Class Documentation
wiringpdata
struct wiringpdata
Class Members
int snoozetime
Macro Definition Documentation
STK500V2PDATA
#define STK500V2PDATA (pgm) ((struct pdata *)(pgm->cookie))
WIRINGPDATA
#define WIRINGPDATA (x) ((struct wiringpdata *)(x))
Function Documentation
wiring_close()
static void wiring_close (PROGRAMMER * pgm) static
{
  serial_set_dtr_rts(&pgm->fd, 0);
  serial_close(&pgm->fd);
  pgm->fd.ifd = -1;
}
References programmer_t::fd, filedescriptor::ifd, pgm, serial_close, and serial_set_dtr_rts.
Referenced by wiring_initpgm().
wiring_initpgm()
void wiring_initpgm (PROGRAMMER * pgm)
{
  /* The Wiring bootloader uses a near-complete STK500v2 protocol. */
  stk500v2_initpgm(pgm);
  strcpy(pgm->type, "Wiring");
  pgm->open           = wiring_open;
  pgm->close          = wiring_close;
  pgm->setup          = wiring_setup;
  pgm->teardown       = wiring_teardown;
  pgm->parseextparams = wiring_parseextparms;
}
References programmer_t::close, programmer_t::open, programmer_t::parseextparams, pgm, programmer_t::setup, stk500v2_initpgm(), programmer_t::teardown, programmer_t::type, wiring_close(), wiring_open(), wiring_parseextparms(), wiring_setup(), and wiring_teardown().
wiring_open()
static int wiring_open (PROGRAMMER * pgm, char * port) static
{
  int timetosnooze;
  void *mycookie = STK500V2PDATA(pgm)->chained_pdata;
  union pinfo pinfo;
  strcpy(pgm->port, port);
  pinfo.baud = pgm->baudrate ? pgm->baudrate: 115200;
  if (serial_open(port, pinfo, &pgm->fd) < 0) {
    return -1;
  }
  /* If we have a snoozetime, then we wait and do NOT toggle DTR/RTS */
  if (WIRINGPDATA(mycookie)->snoozetime > 0) {
    timetosnooze = WIRINGPDATA(mycookie)->snoozetime;
    avrdude_message(MSG_NOTICE2, "%s: wiring_open(): snoozing for %d ms\n",
                    progname, timetosnooze);
    while (timetosnooze--)
      usleep(1000);
    avrdude_message(MSG_NOTICE2, "%s: wiring_open(): done snoozing\n",
                    progname);
  } else {
    /* Perform Wiring programming mode RESET.           */
    /* This effectively *releases* both DTR and RTS.    */
    /* i.e. both DTR and RTS rise to a HIGH logic level */
    /* since they are active LOW signals.               */
    avrdude_message(MSG_NOTICE2, "%s: wiring_open(): releasing DTR/RTS\n",
                    progname);
    serial_set_dtr_rts(&pgm->fd, 0);
    usleep(50*1000);
    /* After releasing for 50 milliseconds, DTR and RTS */
    /* are asserted (i.e. logic LOW) again.             */
    avrdude_message(MSG_NOTICE2, "%s: wiring_open(): asserting DTR/RTS\n",
                    progname);
    serial_set_dtr_rts(&pgm->fd, 1);
    usleep(50*1000);
  }
  /* drain any extraneous input */
  stk500v2_drain(pgm, 0);
  if (stk500v2_getsync(pgm) < 0) {
    serial_close(&pgm->fd);
    return -1;
  }
  return 0;
}
References avrdude_message(), pinfo::baud, programmer_t::baudrate, programmer_t::fd, MSG_NOTICE2, pgm, programmer_t::port, progname, serial_close, serial_open, serial_set_dtr_rts, stk500v2_drain(), stk500v2_getsync(), STK500V2PDATA, usleep(), and WIRINGPDATA.
Referenced by wiring_initpgm().
wiring_parseextparms()
static int wiring_parseextparms (PROGRAMMER * pgm, LISTID extparms) static
{
  LNODEID ln;
  const char *extended_param;
  int rv = 0;
  void *mycookie = STK500V2PDATA(pgm)->chained_pdata;
  for (ln = lfirst(extparms); ln; ln = lnext(ln)) {
    extended_param = ldata(ln);
    if (strncmp(extended_param, "snooze=", strlen("snooze=")) == 0) {
      int newsnooze;
      if (sscanf(extended_param, "snooze=%i", &newsnooze) != 1 ||
          newsnooze < 0) {
        avrdude_message(MSG_INFO, "%s: wiring_parseextparms(): invalid snooze time '%s'\n",
                        progname, extended_param);
        rv = -1;
        continue;
      }
      avrdude_message(MSG_NOTICE2, "%s: wiring_parseextparms(): snooze time set to %d ms\n",
                      progname, newsnooze);
      WIRINGPDATA(mycookie)->snoozetime = newsnooze;
      continue;
    }
    avrdude_message(MSG_INFO, "%s: wiring_parseextparms(): invalid extended parameter '%s'\n",
                    progname, extended_param);
    rv = -1;
  }
  return rv;
}
References avrdude_message(), ldata(), lfirst(), lnext(), MSG_INFO, MSG_NOTICE2, pgm, progname, STK500V2PDATA, and WIRINGPDATA.
Referenced by wiring_initpgm().
wiring_setup()
static void wiring_setup (PROGRAMMER * pgm) static
{
  void *mycookie;
  /*
   * First, have STK500v2 backend allocate its own private data.
   */
  stk500v2_setup(pgm);
  /*
   * Now prepare our data
   */
  if ((mycookie = malloc(sizeof(struct wiringpdata))) == 0) {
    // avrdude_message(MSG_INFO, "%s: wiring_setup(): Out of memory allocating private data\n",
    //                 progname);
    // exit(1);
    avrdude_oom("wiring_setup(): Out of memory allocating private data\n");
  }
  memset(mycookie, 0, sizeof(struct wiringpdata));
  WIRINGPDATA(mycookie)->snoozetime = 0;
  /*
   * Store our own cookie in a safe place for the time being.
   */
  STK500V2PDATA(pgm)->chained_pdata = mycookie;
}
References avrdude_oom(), malloc(), pgm, stk500v2_setup(), STK500V2PDATA, and WIRINGPDATA.
Referenced by wiring_initpgm().
wiring_teardown()
static void wiring_teardown (PROGRAMMER * pgm) static
{
  void *mycookie;
  mycookie = STK500V2PDATA(pgm)->chained_pdata;
  free(mycookie);
  stk500v2_teardown(pgm);
}
References free(), pgm, stk500v2_teardown(), and STK500V2PDATA.
Referenced by wiring_initpgm().
Variable Documentation
wiring_desc
const char wiring_desc[] = "http://wiring.org.co/, Basically STK500v2 protocol, with some glue to trigger the bootloader."