Prusa Slicer: Slic3r::GUI::Materials Struct Reference
Slic3r::GUI::Materials Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
Materials (Technology technology)
void push (const Preset *preset)
void add_printer (const Preset *preset)
void clear ()
bool containts (const Preset *preset) const
bool get_omnipresent (const Preset *preset)
const std::vector< const Preset * > get_presets_by_alias (const std::string name)
size_t get_printer_counter (const Preset *preset)
const std::string & appconfig_section () const
const std::string & get_type (const Preset *preset) const
const std::string & get_vendor (const Preset *preset) const
template<class F >
void filter_presets (const Preset *printer, const std::string &printer_name, const std::string &type, const std::string &vendor, F cb)
Static Public Member Functions
static const std::string & get_filament_type (const Preset *preset)
static const std::string & get_filament_vendor (const Preset *preset)
static const std::string & get_material_type (const Preset *preset)
static const std::string & get_material_vendor (const Preset *preset)
Public Attributes
Technology technology
std::vector< const Preset * > presets
std::vector< std::pair< std::string, size_t > > compatibility_counter
std::set< std::string > types
std::set< const Preset * > printers
Static Public Attributes
static const std::string UNKNOWN = "(Unknown)"
Detailed Description
Constructor & Destructor Documentation
Materials()
Slic3r::GUI::Materials::Materials (Technology technology) inline
: technology(technology) {}
Member Function Documentation
add_printer()
void Slic3r::GUI::Materials::add_printer (const Preset * preset)
{
  printers.insert(preset);
}
References printers.
appconfig_section()
const std::string & Slic3r::GUI::Materials::appconfig_section () const
{
    return (technology & T_FFF) ? AppConfig::SECTION_FILAMENTS : AppConfig::SECTION_MATERIALS;
}
References Slic3r::AppConfig::SECTION_FILAMENTS, Slic3r::AppConfig::SECTION_MATERIALS, Slic3r::GUI::T_FFF, and technology.
Referenced by Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_model(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::PageMaterials::select_material(), and Slic3r::GUI::PageMaterials::update_lists().
clear()
void Slic3r::GUI::Materials::clear ()
{
    presets.clear();
    types.clear();
  printers.clear();
    compatibility_counter.clear();
}
References compatibility_counter, presets, printers, and types.
containts()
bool Slic3r::GUI::Materials::containts (const Preset * preset) const inline
{
        //return std::find(presets.begin(), presets.end(), preset) != presets.end();
        return std::find_if(presets.begin(), presets.end(),
            [preset](const Preset* element) { return element == preset; }) != presets.end();
    }
References presets.
filter_presets()
template<class F > void Slic3r::GUI::Materials::filter_presets (const Preset * printer, const std::string & printer_name, const std::string & type, const std::string & vendor, F cb) inline
{
        for (auto preset : presets) {
            const Preset& prst = *(preset);
            const Preset& prntr = *printer;
            if (((printer == nullptr && printer_name == PageMaterials::EMPTY) || (printer != nullptr && is_compatible_with_printer(PresetWithVendorProfile(prst, prst.vendor), PresetWithVendorProfile(prntr, prntr.vendor)))) &&
                (type.empty() || get_type(preset) == type) &&
                (vendor.empty() || get_vendor(preset) == vendor) &&
                prst.vendor && !prst.vendor->templates_profile) {
                cb(preset);
            }
            else if ((printer == nullptr && printer_name == PageMaterials::TEMPLATES) && prst.vendor && prst.vendor->templates_profile &&
                (type.empty() || get_type(preset) == type) &&
                (vendor.empty() || get_vendor(preset) == vendor)) {
                cb(preset);
            }
        }
    }
References Slic3r::GUI::PageMaterials::EMPTY, get_type(), get_vendor(), Slic3r::is_compatible_with_printer(), presets, Slic3r::GUI::PageMaterials::TEMPLATES, Slic3r::VendorProfile::templates_profile, and Slic3r::Preset::vendor.
Referenced by Slic3r::GUI::PageMaterials::update_lists().
get_filament_type()
const std::string & Slic3r::GUI::Materials::get_filament_type (const Preset * preset) static
{
    const auto *opt = preset->config.opt<ConfigOptionStrings>("filament_type");
    if (opt != nullptr && opt->values.size() > 0) {
        return opt->values[0];
    } else {
        return UNKNOWN;
    }
}
References Slic3r::Preset::config, Slic3r::ConfigBase::opt(), UNKNOWN, and Slic3r::ConfigOptionVector< T >::values.
Referenced by get_type(), and push().
get_filament_vendor()
const std::string & Slic3r::GUI::Materials::get_filament_vendor (const Preset * preset) static
{
    const auto *opt = preset->config.opt<ConfigOptionString>("filament_vendor");
    return opt != nullptr ? opt->value : UNKNOWN;
}
References Slic3r::Preset::config, Slic3r::ConfigBase::opt(), UNKNOWN, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by get_vendor().
get_material_type()
const std::string & Slic3r::GUI::Materials::get_material_type (const Preset * preset) static
{
    const auto *opt = preset->config.opt<ConfigOptionString>("material_type");
    if (opt != nullptr) {
        return opt->value;
    } else {
        return UNKNOWN;
    }
}
References Slic3r::Preset::config, Slic3r::ConfigBase::opt(), UNKNOWN, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by get_type(), and push().
get_material_vendor()
const std::string & Slic3r::GUI::Materials::get_material_vendor (const Preset * preset) static
{
    const auto *opt = preset->config.opt<ConfigOptionString>("material_vendor");
    return opt != nullptr ? opt->value : UNKNOWN;
}
References Slic3r::Preset::config, Slic3r::ConfigBase::opt(), UNKNOWN, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by get_vendor().
get_omnipresent()
bool Slic3r::GUI::Materials::get_omnipresent (const Preset * preset) inline
{
        return get_printer_counter(preset) == printers.size();
    }
References get_printer_counter(), and printers.
Referenced by Slic3r::GUI::PageMaterials::update_lists().
get_presets_by_alias()
const std::vector< const Preset * > Slic3r::GUI::Materials::get_presets_by_alias (const std::string name) inline
{
        std::vector<const Preset*> ret_vec;
        for (auto it = presets.begin(); it != presets.end(); ++it) {
            if ((*it)->alias == name)
                ret_vec.push_back((*it));
        }
        return ret_vec;
    }
References presets.
Referenced by Slic3r::GUI::PageMaterials::on_material_highlighted().
get_printer_counter()
size_t Slic3r::GUI::Materials::get_printer_counter (const Preset * preset) inline
{
        for (auto it : compatibility_counter) {
            if (it.first == preset->alias)
                return it.second;
        }
        return 0;
    }
References Slic3r::Preset::alias, and compatibility_counter.
Referenced by get_omnipresent().
get_type()
const std::string & Slic3r::GUI::Materials::get_type (const Preset * preset) const
{
    return (technology & T_FFF) ? get_filament_type(preset) : get_material_type(preset);
}
References get_filament_type(), get_material_type(), Slic3r::GUI::T_FFF, and technology.
Referenced by filter_presets(), and Slic3r::GUI::PageMaterials::update_lists().
get_vendor()
const std::string & Slic3r::GUI::Materials::get_vendor (const Preset * preset) const
{
    return (technology & T_FFF) ? get_filament_vendor(preset) : get_material_vendor(preset);
}
References get_filament_vendor(), get_material_vendor(), Slic3r::GUI::T_FFF, and technology.
Referenced by filter_presets(), and Slic3r::GUI::PageMaterials::update_lists().
push()
void Slic3r::GUI::Materials::push (const Preset * preset)
{
    presets.emplace_back(preset);
    types.insert(technology & T_FFF
        ? Materials::get_filament_type(preset)
        : Materials::get_material_type(preset));
}
References get_filament_type(), get_material_type(), presets, Slic3r::GUI::T_FFF, technology, and types.
Member Data Documentation
compatibility_counter
std::vector<std::pair<std::string, size_t> > Slic3r::GUI::Materials::compatibility_counter
Referenced by clear(), and get_printer_counter().
presets
std::vector<const Preset*> Slic3r::GUI::Materials::presets
Referenced by clear(), containts(), filter_presets(), get_presets_by_alias(), and push().
printers
std::set<const Preset*> Slic3r::GUI::Materials::printers
Referenced by add_printer(), clear(), get_omnipresent(), Slic3r::GUI::PageMaterials::on_material_highlighted(), Slic3r::GUI::PageMaterials::reload_presets(), and Slic3r::GUI::PageMaterials::update_lists().
technology
Technology Slic3r::GUI::Materials::technology
Referenced by Slic3r::GUI::ConfigWizard::ConfigWizard(), appconfig_section(), get_type(), get_vendor(), Slic3r::GUI::PageMaterials::on_activate(), push(), Slic3r::GUI::PageMaterials::reload_presets(), Slic3r::GUI::PageMaterials::set_compatible_printers_html_window(), Slic3r::GUI::PageMaterials::sort_list_data(), and Slic3r::GUI::PageMaterials::update_lists().
types
std::set<std::string> Slic3r::GUI::Materials::types
Referenced by clear(), and push().
UNKNOWN
const std::string Slic3r::GUI::Materials::UNKNOWN = "(Unknown)" static
Referenced by get_filament_type(), get_filament_vendor(), get_material_type(), and get_material_vendor().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp