Prusa Slicer: Slic3r::execution::Traits< ExecutionTBB > Struct Reference
Slic3r::execution::Traits< ExecutionTBB > Struct Reference
#include <src/libslic3r/Execution/ExecutionTBB.hpp>
Public Types
using SpinningMutex = tbb::spin_mutex
using BlockingMutex = std::mutex
Static Public Member Functions
template<class It , class Fn >
static void for_each (const ExecutionTBB &, It from, It to, Fn &&fn, size_t granularity)
template<class I , class MergeFn , class T , class AccessFn >
static T reduce (const ExecutionTBB &, I from, I to, const T &init, MergeFn &&mergefn, AccessFn &&accessfn, size_t granularity=1)
static size_t max_concurrency (const ExecutionTBB &)
Static Private Member Functions
template<class Fn , class It >
static IteratorOnly< It, void > loop_ (const tbb::blocked_range< It > &range, Fn &&fn)
template<class Fn , class I >
static IntegerOnly< I, void > loop_ (const tbb::blocked_range< I > &range, Fn &&fn)
Detailed Description
Member Typedef Documentation
BlockingMutex
using Slic3r::execution::Traits< ExecutionTBB >::BlockingMutex = std::mutex
SpinningMutex
using Slic3r::execution::Traits< ExecutionTBB >::SpinningMutex = tbb::spin_mutex
Member Function Documentation
for_each()
template<class It , class Fn > static void Slic3r::execution::Traits< ExecutionTBB >::for_each (const ExecutionTBB & , It from, It to, Fn && fn, size_t granularity) inline static
    {
        tbb::parallel_for(tbb::blocked_range{from, to, granularity},
                          [&fn](const auto &range) {
            loop_(range, std::forward<Fn>(fn));
        });
    }
References Slic3r::range().
loop_() [1/2]
template<class Fn , class I > static IntegerOnly< I, void > Slic3r::execution::Traits< ExecutionTBB >::loop_ (const tbb::blocked_range< I > & range, Fn && fn) inline static private
    {
        for (I i = range.begin(); i < range.end(); ++i) fn(i);
    }
References Slic3r::range().
loop_() [2/2]
template<class Fn , class It > static IteratorOnly< It, void > Slic3r::execution::Traits< ExecutionTBB >::loop_ (const tbb::blocked_range< It > & range, Fn && fn) inline static private
    {
        for (auto &el : range) fn(el);
    }
References Slic3r::range().
max_concurrency()
static size_t Slic3r::execution::Traits< ExecutionTBB >::max_concurrency (const ExecutionTBB &) inline static
    {
        return tbb::this_task_arena::max_concurrency();
    }
reduce()
template<class I , class MergeFn , class T , class AccessFn > static T Slic3r::execution::Traits< ExecutionTBB >::reduce (const ExecutionTBB & , I from, I to, const T & init, MergeFn && mergefn, AccessFn && accessfn, size_t granularity = 1) inline static
    {
        return tbb::parallel_reduce(
            tbb::blocked_range{from, to, granularity}, init,
            [&](const auto &range, T subinit) {
                T acc = subinit;
                loop_(range, [&](auto &i) { acc = mergefn(acc, accessfn(i)); });
                return acc;
            },
            std::forward<MergeFn>(mergefn));
    }
References Slic3r::range().
The documentation for this struct was generated from the following file:
src/libslic3r/Execution/ExecutionTBB.hpp