Prusa Slicer: Slic3r::ExtruderFilaments Class Reference
Slic3r::ExtruderFilaments Class Reference
#include <src/libslic3r/Preset.hpp>
Public Types
typedef std::deque< Filament >::iterator Iterator
typedef std::deque< Filament >::const_iterator ConstIterator
Public Member Functions
ExtruderFilaments (PresetCollection *filaments_collection, size_t extruder_id=0, std::string selected_name=std::string())
Iterator begin ()
ConstIterator begin () const
ConstIterator cbegin () const
Iterator end ()
ConstIterator end () const
ConstIterator cend () const
bool empty () const
const std::deque< Filament > & operator() () const
Filament & filament (size_t idx)
const Filament & filament (size_t idx) const
bool select_filament (const std::string &name, bool force=false)
void select_filament (size_t idx)
std::string get_selected_preset_name () const
const Preset * get_selected_preset () const
const Filament * get_selected_filament () const
size_t get_selected_idx () const
ExtruderFilaments ()=default
ExtruderFilaments & operator= (const ExtruderFilaments &other)=default
Private Member Functions
std::deque< Filament >::iterator find_filament_internal (const std::string &name)
std::deque< Filament >::const_iterator find_filament_internal (const std::string &name) const
void cache_selected_name ()
std::string get_cached_selected_name () const
template<typename PreferedCondition >
size_t first_compatible_idx (PreferedCondition prefered_condition) const
size_t first_compatible_idx () const
template<typename PreferedCondition >
const Preset * first_compatible (PreferedCondition prefered_condition)
const Preset * first_compatible ()
const std::string & get_preset_name_by_alias (const std::string &alias) const
size_t update_compatible_internal (const PresetWithVendorProfile &active_printer, const PresetWithVendorProfile *active_print, PresetSelectCompatibleType unselect_if_incompatible)
template<typename PreferedCondition >
void update_compatible (const PresetWithVendorProfile &active_printer, const PresetWithVendorProfile *active_print, PresetSelectCompatibleType select_other_if_incompatible, PreferedCondition prefered_condition)
void update_compatible (const PresetWithVendorProfile &active_printer, const PresetWithVendorProfile *active_print, PresetSelectCompatibleType select_other_if_incompatible)
Private Attributes
PresetCollection * m_filaments { nullptr }
size_t m_idx_selected { size_t(-1) }
std::deque< Filament > m_extr_filaments
size_t m_extruder_id
std::string m_cached_selected_name { std::string() }
Friends
class PresetBundle
Detailed Description
Member Typedef Documentation
ConstIterator
typedef std::deque<Filament>::const_iterator Slic3r::ExtruderFilaments::ConstIterator
Iterator
typedef std::deque<Filament>::iterator Slic3r::ExtruderFilaments::Iterator
Constructor & Destructor Documentation
ExtruderFilaments() [1/2]
Slic3r::ExtruderFilaments::ExtruderFilaments (PresetCollection * filaments_collection, size_t extruder_id = 0, std::string selected_name = std::string())
: m_filaments (filaments_collection)
, m_extruder_id(extruder_id)
{
    const std::deque<Preset>& presets = m_filaments->get_presets();
    for (size_t id = 0; id < presets.size(); id ++)
        m_extr_filaments.emplace_back(&(presets[id]));
    select_filament(selected_name.empty() ? m_filaments->get_selected_preset_name() : selected_name);
}
References Slic3r::PresetCollection::get_presets(), Slic3r::PresetCollection::get_selected_preset_name(), m_extr_filaments, m_filaments, and select_filament().
ExtruderFilaments() [2/2]
Slic3r::ExtruderFilaments::ExtruderFilaments () default
Member Function Documentation
begin() [1/2]
Iterator Slic3r::ExtruderFilaments::begin () inline
{ return m_extr_filaments.begin(); }
References m_extr_filaments.
begin() [2/2]
ConstIterator Slic3r::ExtruderFilaments::begin () const inline
{ return m_extr_filaments.cbegin(); }
References m_extr_filaments.
cache_selected_name()
void Slic3r::ExtruderFilaments::cache_selected_name () inline private
{ m_cached_selected_name = get_selected_preset_name(); }
References get_selected_preset_name(), and m_cached_selected_name.
cbegin()
ConstIterator Slic3r::ExtruderFilaments::cbegin () const inline
{ return m_extr_filaments.cbegin(); }
References m_extr_filaments.
cend()
ConstIterator Slic3r::ExtruderFilaments::cend () const inline
{ return m_extr_filaments.cend(); }
References m_extr_filaments.
empty()
bool Slic3r::ExtruderFilaments::empty () const inline
{ return m_extr_filaments.empty(); }
References m_extr_filaments.
end() [1/2]
Iterator Slic3r::ExtruderFilaments::end () inline
{ return m_extr_filaments.end(); }
References m_extr_filaments.
end() [2/2]
ConstIterator Slic3r::ExtruderFilaments::end () const inline
{ return m_extr_filaments.cend(); }
References m_extr_filaments.
filament() [1/2]
Filament & Slic3r::ExtruderFilaments::filament (size_t idx) inline
{ return m_extr_filaments[idx]; }
References m_extr_filaments.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and update_compatible_internal().
filament() [2/2]
const Filament & Slic3r::ExtruderFilaments::filament (size_t idx) const inline
{ return const_cast<ExtruderFilaments*>(this)->filament(idx); }
References filament().
Referenced by filament().
find_filament_internal() [1/2]
std::deque< Filament >::iterator Slic3r::ExtruderFilaments::find_filament_internal (const std::string & name) inline private
    {
        return Slic3r::lower_bound_by_predicate(m_extr_filaments.begin(), m_extr_filaments.end(), [&name](const auto& l) {
            return l.preset->name < name;
        });
    }
References Slic3r::lower_bound_by_predicate(), and m_extr_filaments.
Referenced by find_filament_internal(), get_preset_name_by_alias(), and select_filament().
find_filament_internal() [2/2]
std::deque< Filament >::const_iterator Slic3r::ExtruderFilaments::find_filament_internal (const std::string & name) const inline private
    {
        return const_cast<ExtruderFilaments*>(this)->find_filament_internal(name);
    }
References find_filament_internal().
first_compatible() [1/2]
const Preset * Slic3r::ExtruderFilaments::first_compatible () inline private
{ return m_extr_filaments[this->first_compatible_idx()].preset; }
References first_compatible_idx(), and m_extr_filaments.
first_compatible() [2/2]
template<typename PreferedCondition > const Preset * Slic3r::ExtruderFilaments::first_compatible (PreferedCondition prefered_condition) inline private
{ return m_extr_filaments[this->first_compatible_idx(prefered_condition)].preset;}
References first_compatible_idx(), and m_extr_filaments.
Referenced by Slic3r::PresetBundle::update_filaments_compatible().
first_compatible_idx() [1/2]
size_t Slic3r::ExtruderFilaments::first_compatible_idx () const inline private
{ return this->first_compatible_idx([](const /*Filament*/Preset&) -> int { return 0; }); }
References first_compatible_idx().
Referenced by first_compatible(), first_compatible(), first_compatible_idx(), and update_compatible().
first_compatible_idx() [2/2]
template<typename PreferedCondition > size_t Slic3r::ExtruderFilaments::first_compatible_idx (PreferedCondition prefered_condition) const inline private
    {
        size_t i = m_filaments->is_default_suppressed() ? m_filaments->num_default_presets() : 0;
        size_t n = m_extr_filaments.size();
        size_t i_compatible = n;
        int    match_quality = -1;
        for (; i < n; ++i)
            // Since we use the filament selection from Wizard, it's needed to control the preset visibility too
            if (m_extr_filaments[i].is_compatible && m_filaments->preset(i).is_visible) {
                int this_match_quality = prefered_condition(*(m_extr_filaments[i].preset));
                if (this_match_quality > match_quality) {
                    if (match_quality == std::numeric_limits<int>::max())
                        // Better match will not be found.
                        return i;
                    // Store the first compatible profile with highest match quality into i_compatible.
                    i_compatible = i;
                    match_quality = this_match_quality;
                }
            }
        return (i_compatible == n) ?
            // No compatible preset found, return the default preset.
            0 :
            // Compatible preset found.
            i_compatible;
    }
References Slic3r::PresetCollection::is_default_suppressed(), Slic3r::Preset::is_visible, m_extr_filaments, m_filaments, Slic3r::PresetCollection::num_default_presets(), and Slic3r::PresetCollection::preset().
get_cached_selected_name()
std::string Slic3r::ExtruderFilaments::get_cached_selected_name () const inline private
{ return m_cached_selected_name; }
References m_cached_selected_name.
get_preset_name_by_alias()
const std::string & Slic3r::ExtruderFilaments::get_preset_name_by_alias (const std::string & alias) const private
{
    const auto& aliases_map = m_filaments->map_alias_to_profile_name();
    for (
        // Find the 1st profile name with the alias.
        auto it = Slic3r::lower_bound_by_predicate(aliases_map.begin(), aliases_map.end(), [&alias](auto& l) { return l.first < alias; });
        // Continue over all profile names with the same alias.
        it != aliases_map.end() && it->first == alias; ++it)
        if (auto it_filament = find_filament_internal(it->second);
            it_filament != m_extr_filaments.end() && it_filament->preset->name == it->second &&
            it_filament->preset->is_visible && (it_filament->is_compatible || size_t(it_filament - m_extr_filaments.begin()) == m_idx_selected))
            return it_filament->preset->name;
    return alias;
}
References find_filament_internal(), Slic3r::lower_bound_by_predicate(), m_extr_filaments, m_filaments, m_idx_selected, and Slic3r::PresetCollection::map_alias_to_profile_name().
get_selected_filament()
const Filament * Slic3r::ExtruderFilaments::get_selected_filament () const inline
{ return m_idx_selected == size_t(-1) ? nullptr   : &m_extr_filaments[m_idx_selected]; }
References m_extr_filaments, and m_idx_selected.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), and Slic3r::PresetBundle::update_filaments_compatible().
get_selected_idx()
size_t Slic3r::ExtruderFilaments::get_selected_idx () const inline
{ return m_idx_selected; }
References m_idx_selected.
Referenced by Slic3r::GUI::TabPresetComboBox::update().
get_selected_preset()
const Preset * Slic3r::ExtruderFilaments::get_selected_preset () const inline
{ return m_idx_selected == size_t(-1) ? nullptr   : m_extr_filaments[m_idx_selected].preset; }
References m_extr_filaments, and m_idx_selected.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update().
get_selected_preset_name()
std::string Slic3r::ExtruderFilaments::get_selected_preset_name () const inline
{ return m_idx_selected == size_t(-1) ? std::string() : m_extr_filaments[m_idx_selected].preset->name; }
References m_extr_filaments, and m_idx_selected.
Referenced by cache_selected_name(), and Slic3r::PresetBundle::update_filaments_compatible().
operator()()
const std::deque< Filament > & Slic3r::ExtruderFilaments::operator() () const inline
{ return m_extr_filaments; }
References m_extr_filaments.
operator=()
ExtruderFilaments & Slic3r::ExtruderFilaments::operator= (const ExtruderFilaments & other) default
select_filament() [1/2]
bool Slic3r::ExtruderFilaments::select_filament (const std::string & name, bool force = false)
{
    std::string name = Preset::remove_suffix_modified(name_w_suffix);
    // 1) Try to find the preset by its name.
    auto it = this->find_filament_internal(name);
    size_t idx = 0;
    if (it != m_extr_filaments.end() && it->preset->name == name && it->preset->is_visible)
        // Preset found by its name and it is visible.
        idx = it - m_extr_filaments.begin();
    else {
        // Find the first visible preset.
        for (size_t i = 0; i < m_extr_filaments.size(); ++i)
            if (m_extr_filaments[i].preset->is_visible/* && m_extr_filaments[i].is_compatible*/) {
                idx = i;
                break;
            }
        // If the first visible preset was not found, return the 0th element, which is the default preset.
    }
    // 2) Select the new preset.
    if (m_idx_selected != idx || force) {
        this->select_filament(idx);
        return true;
    }
    return false;
}
References find_filament_internal(), m_extr_filaments, m_idx_selected, Slic3r::Preset::remove_suffix_modified(), and select_filament().
Referenced by ExtruderFilaments(), select_filament(), update_compatible(), and Slic3r::PresetBundle::update_filaments_compatible().
select_filament() [2/2]
void Slic3r::ExtruderFilaments::select_filament (size_t idx) inline
{ m_idx_selected = idx; }
References m_idx_selected.
update_compatible() [1/2]
void Slic3r::ExtruderFilaments::update_compatible (const PresetWithVendorProfile & active_printer, const PresetWithVendorProfile * active_print, PresetSelectCompatibleType select_other_if_incompatible) inline private
    {
        this->update_compatible(active_printer, active_print, select_other_if_incompatible, [](const /*Filament*/Preset&) -> int { return 0; });
    }
References update_compatible().
update_compatible() [2/2]
template<typename PreferedCondition > void Slic3r::ExtruderFilaments::update_compatible (const PresetWithVendorProfile & active_printer, const PresetWithVendorProfile * active_print, PresetSelectCompatibleType select_other_if_incompatible, PreferedCondition prefered_condition) inline private
    {
        if (this->update_compatible_internal(active_printer, active_print, select_other_if_incompatible) == (size_t)-1)
            // Find some other compatible preset, or the "-- default --" preset.
            this->select_filament(this->first_compatible_idx(prefered_condition));
    }
References first_compatible_idx(), select_filament(), and update_compatible_internal().
Referenced by update_compatible(), and Slic3r::PresetBundle::update_filaments_compatible().
update_compatible_internal()
size_t Slic3r::ExtruderFilaments::update_compatible_internal (const PresetWithVendorProfile & active_printer, const PresetWithVendorProfile * active_print, PresetSelectCompatibleType unselect_if_incompatible) private
{
    DynamicPrintConfig config;
    config.set_key_value("printer_preset", new ConfigOptionString(active_printer.preset.name));
    const ConfigOption* opt = active_printer.preset.config.option("nozzle_diameter");
    if (opt)
        config.set_key_value("num_extruders", new ConfigOptionInt((int)static_cast<const ConfigOptionFloats*>(opt)->values.size()));
    bool some_compatible = false;
    // Adjust printer preset config to the first extruder from m_extruder_id
    Preset printer_preset_adjusted = active_printer.preset;
    if (m_extruder_id > 0 && !printer_preset_adjusted.config.opt_bool("single_extruder_multi_material")) {
        DynamicPrintConfig& active_printer_config = printer_preset_adjusted.config;
        for (const std::string& key : print_config_def.extruder_option_keys()) {
            if (key == "default_filament_profile")
                continue;// Ignore this field, because this parameter is not related to the extruder but to whole printer.
            auto* opt = active_printer_config.option(key, false);
            if (opt != nullptr && opt->is_vector())
                static_cast<ConfigOptionVectorBase*>(opt)->set_at(opt, 0, m_extruder_id);
        }
    }
    PresetWithVendorProfile active_printer_adjusted(printer_preset_adjusted, active_printer.vendor);
    std::vector<size_t> indices_of_template_presets;
    indices_of_template_presets.reserve(m_extr_filaments.size());
    size_t num_default_presets = m_filaments->num_default_presets();
    for (size_t idx_preset = num_default_presets; idx_preset < m_extr_filaments.size(); ++idx_preset) {
        const bool    is_selected   = idx_preset == m_idx_selected;
        const Preset* preset        = m_extr_filaments[idx_preset].preset;
        Filament& extr_filament = m_extr_filaments[idx_preset];
        const PresetWithVendorProfile this_preset_with_vendor_profile = m_filaments->get_preset_with_vendor_profile(*preset);
        bool    was_compatible = extr_filament.is_compatible;
        extr_filament.is_compatible = is_compatible_with_printer(this_preset_with_vendor_profile, active_printer_adjusted, &config);
        some_compatible |= extr_filament.is_compatible;
        if (active_print != nullptr)
            extr_filament.is_compatible &= is_compatible_with_print(this_preset_with_vendor_profile, *active_print, active_printer_adjusted);
        if (!extr_filament.is_compatible && is_selected &&
            (unselect_if_incompatible == PresetSelectCompatibleType::Always || (unselect_if_incompatible == PresetSelectCompatibleType::OnlyIfWasCompatible && was_compatible)))
            m_idx_selected = size_t(-1);
        if (preset->vendor && preset->vendor->templates_profile) {
            if (preset->is_visible)
                indices_of_template_presets.push_back(idx_preset);
            else {
                extr_filament.is_compatible = false;
                if (is_selected)
                    m_idx_selected = size_t(-1);
            }
        }
    }
    // filter out template profiles where profile with same alias and compability exists
    if (!indices_of_template_presets.empty()) {
        for (size_t idx = num_default_presets; idx < m_extr_filaments.size(); ++idx) {
            const Filament& filament    = m_extr_filaments[idx];
            const VendorProfile*    vendor      = filament.preset->vendor;
            if (vendor && !vendor->templates_profile && filament.is_compatible) {
                const std::string& preset_alias = filament.preset->alias;
                for (const auto& template_idx : indices_of_template_presets) {
                    if (m_extr_filaments[template_idx].preset->alias == preset_alias) {
                        m_extr_filaments[template_idx].is_compatible = false;
                        // unselect selected template filament if there is non-template alias compatible
                        if (template_idx == m_idx_selected && (unselect_if_incompatible != PresetSelectCompatibleType::Never))
                            m_idx_selected = size_t(-1);
                        break;
                    }
                }
            }
        }
    }
    return m_idx_selected;
}
References Slic3r::Preset::alias, Slic3r::Always, Slic3r::Preset::config, Slic3r::PrintConfigDef::extruder_option_keys(), filament(), Slic3r::PresetCollection::get_preset_with_vendor_profile(), Slic3r::Filament::is_compatible, Slic3r::is_compatible_with_print(), Slic3r::is_compatible_with_printer(), Slic3r::ConfigOption::is_vector(), Slic3r::Preset::is_visible, m_extr_filaments, m_extruder_id, m_filaments, m_idx_selected, Slic3r::Preset::name, Slic3r::Never, Slic3r::PresetCollection::num_default_presets(), Slic3r::OnlyIfWasCompatible, Slic3r::ConfigBase::opt_bool(), Slic3r::ConfigBase::option(), Slic3r::PresetWithVendorProfile::preset, Slic3r::Filament::preset, Slic3r::print_config_def, Slic3r::ConfigOptionVectorBase::set_at(), Slic3r::DynamicConfig::set_key_value(), Slic3r::ConfigOptionVector< T >::size(), Slic3r::VendorProfile::templates_profile, Slic3r::PresetWithVendorProfile::vendor, and Slic3r::Preset::vendor.
Referenced by update_compatible().
Friends And Related Symbol Documentation
PresetBundle
friend class PresetBundle friend
Member Data Documentation
m_cached_selected_name
std::string Slic3r::ExtruderFilaments::m_cached_selected_name { std::string() } private
Referenced by cache_selected_name(), and get_cached_selected_name().
m_extr_filaments
std::deque<Filament> Slic3r::ExtruderFilaments::m_extr_filaments private
Referenced by ExtruderFilaments(), begin(), begin(), cbegin(), cend(), empty(), end(), end(), filament(), find_filament_internal(), first_compatible(), first_compatible(), first_compatible_idx(), get_preset_name_by_alias(), get_selected_filament(), get_selected_preset(), get_selected_preset_name(), operator()(), select_filament(), and update_compatible_internal().
m_extruder_id
size_t Slic3r::ExtruderFilaments::m_extruder_id private
Referenced by update_compatible_internal().
m_filaments
PresetCollection* Slic3r::ExtruderFilaments::m_filaments { nullptr } private
Referenced by ExtruderFilaments(), first_compatible_idx(), get_preset_name_by_alias(), and update_compatible_internal().
m_idx_selected
size_t Slic3r::ExtruderFilaments::m_idx_selected { size_t(-1) } private
Referenced by get_preset_name_by_alias(), get_selected_filament(), get_selected_idx(), get_selected_preset(), get_selected_preset_name(), select_filament(), select_filament(), and update_compatible_internal().
The documentation for this class was generated from the following files:
src/libslic3r/Preset.hpp
src/libslic3r/Preset.cpp