Prusa Slicer: Slic3r::ConfigOptionPoints Class Reference
Slic3r::ConfigOptionPoints Class Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionPoints ()
ConfigOptionPoints (size_t n, const Vec2d &value)
ConfigOptionPoints (std::initializer_list< Vec2d > il)
ConfigOptionPoints (const std::vector< Vec2d > &values)
ConfigOptionType type () const override
ConfigOption * clone () const override
ConfigOptionPoints & operator= (const ConfigOption *opt)
bool operator== (const ConfigOptionPoints &rhs) const throw ()
bool operator< (const ConfigOptionPoints &rhs) const throw ()
bool is_nil (size_t) const override
std::string serialize () const override
std::vector< std::string > vserialize () const override
bool deserialize (const std::string &str, bool append=false) override
void set (const ConfigOption *rhs) override
void set (const std::vector< const ConfigOption * > &rhs) override
void set_at (const ConfigOption *rhs, size_t i, size_t j) override
const Vec2d & get_at (size_t i) const
Vec2d & get_at (size_t i)
void resize (size_t n, const ConfigOption *opt_default=nullptr) override
void clear () override
size_t size () const override
bool empty () const override
bool operator== (const ConfigOption &rhs) const override
bool operator== (const std::vector< Vec2d > &rhs) const throw ()
bool operator!= (const std::vector< Vec2d > &rhs) const throw ()
bool operator!= (const ConfigOption &rhs) const
size_t hash () const override throw ()
bool overriden_by (const ConfigOption *rhs) const override
bool apply_override (const ConfigOption *rhs) override
virtual bool is_nil () const
virtual int getInt () const
virtual double getFloat () const
virtual bool getBool () const
virtual void setInt (int)
bool is_scalar () const
bool is_vector () const
virtual bool nullable () const
Static Public Member Functions
static ConfigOptionType static_type ()
Public Attributes
std::vector< Vec2d > values
Protected Member Functions
ConfigOptionType scalar_type () const
Private Member Functions
template<class Archive >
void save (Archive &archive) const
template<class Archive >
void load (Archive &archive)
Friends
class cereal::access
Detailed Description
Constructor & Destructor Documentation
ConfigOptionPoints() [1/4]
Slic3r::ConfigOptionPoints::ConfigOptionPoints () inline
: ConfigOptionVector<Vec2d>() {}
Referenced by clone().
ConfigOptionPoints() [2/4]
Slic3r::ConfigOptionPoints::ConfigOptionPoints (size_t n, const Vec2d & value) inline explicit
: ConfigOptionVector<Vec2d>(n, value) {}
ConfigOptionPoints() [3/4]
Slic3r::ConfigOptionPoints::ConfigOptionPoints (std::initializer_list< Vec2d > il) inline explicit
: ConfigOptionVector<Vec2d>(std::move(il)) {}
ConfigOptionPoints() [4/4]
Slic3r::ConfigOptionPoints::ConfigOptionPoints (const std::vector< Vec2d > & values) inline explicit
: ConfigOptionVector<Vec2d>(values) {}
Member Function Documentation
apply_override()
bool Slic3r::ConfigOptionVector< Vec2d >::apply_override (const ConfigOption * rhs) inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
      throw ConfigurationError("ConfigOptionVector.apply_override() applied to different types.");
    auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
    if (! rhs->nullable()) {
        // Overridding a non-nullable object with another non-nullable object.
        if (this->values != rhs_vec->values) {
          this->values = rhs_vec->values;
          return true;
        }
        return false;
      }
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      bool   modified = false;
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i]) {
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i)) {
          if (this->values.empty())
            this->values.resize(i + 1);
          else
            this->values.resize(i + 1, this->values.front());
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
        return modified;
    }
clear()
void Slic3r::ConfigOptionVector< Vec2d >::clear () inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ this->values.clear(); }
clone()
ConfigOption * Slic3r::ConfigOptionPoints::clone () const inline override virtual
Implements Slic3r::ConfigOption.
{ return new ConfigOptionPoints(*this); }
References ConfigOptionPoints().
deserialize()
bool Slic3r::ConfigOptionPoints::deserialize (const std::string & str, bool append = false) inline override virtual
Implements Slic3r::ConfigOption.
    {
        if (! append)
            this->values.clear();
        std::istringstream is(str);
        std::string point_str;
        while (std::getline(is, point_str, ',')) {
            Vec2d point(Vec2d::Zero());
            std::istringstream iss(point_str);
            std::string coord_str;
            if (std::getline(iss, coord_str, 'x')) {
                std::istringstream(coord_str) >> point(0);
                if (std::getline(iss, coord_str, 'x')) {
                    std::istringstream(coord_str) >> point(1);
                }
            }
            this->values.push_back(point);
        }
        return true;
    }
References Slic3r::append().
empty()
bool Slic3r::ConfigOptionVector< Vec2d >::empty () const inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.empty(); }
get_at() [1/2]
Vec2d & Slic3r::ConfigOptionVector< Vec2d >::get_at (size_t i) inline inherited
{ return const_cast<T&>(std::as_const(*this).get_at(i)); }
get_at() [2/2]
const Vec2d & Slic3r::ConfigOptionVector< Vec2d >::get_at (size_t i) const inline inherited
    {
        assert(! this->values.empty());
        return (i < this->values.size()) ? this->values[i] : this->values.front();
    }
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
virtual int Slic3r::ConfigOption::getInt () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::getInt on a non-int ConfigOption"); }
Referenced by Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
hash()
size_t Slic3r::ConfigOptionVector< Vec2d >::hash () const throw () inline override virtual inherited
Implements Slic3r::ConfigOption.
{
        std::hash<T> hasher;
        size_t seed = 0;
        for (const auto &v : this->values)
            boost::hash_combine(seed, hasher(v));
        return seed;
    }
is_nil() [1/2]
virtual bool Slic3r::ConfigOption::is_nil () const inline virtual inherited
Reimplemented from Slic3r::ConfigOption.
{ return false; }
is_nil() [2/2]
bool Slic3r::ConfigOptionPoints::is_nil (size_t) const inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
{ return false; }
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
load()
template<class Archive > void Slic3r::ConfigOptionPoints::load (Archive & archive) inline private
{
    size_t cnt;
    archive(cnt);
    this->values.assign(cnt, Vec2d());
    archive.loadBinary((char*)this->values.data(), sizeof(Vec2d) * cnt);
  }
nullable()
virtual bool Slic3r::ConfigOption::nullable () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::ConfigBase::null_nullables(), Slic3r::ConfigOption::overriden_by(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::validate().
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
bool Slic3r::ConfigOptionVector< Vec2d >::operator!= (const std::vector< Vec2d > & rhs) const throw () inline inherited
{ return this->values != rhs; }
operator<()
bool Slic3r::ConfigOptionPoints::operator< (const ConfigOptionPoints & rhs) const throw () inline
        { return std::lexicographical_compare(this->values.begin(), this->values.end(), rhs.values.begin(), rhs.values.end(), [](const auto &l, const auto &r){ return l < r; }); }
operator=()
ConfigOptionPoints & Slic3r::ConfigOptionPoints::operator= (const ConfigOption * opt) inline
{ this->set(opt); return *this; }
References Slic3r::ConfigOptionVector< Vec2d >::set().
operator==() [1/3]
bool Slic3r::ConfigOptionVector< Vec2d >::operator== (const ConfigOption & rhs) const inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionVector: Comparing incompatible types");
        assert(dynamic_cast<const ConfigOptionVector<T>*>(&rhs));
        return this->values == static_cast<const ConfigOptionVector<T>*>(&rhs)->values;
    }
operator==() [2/3]
bool Slic3r::ConfigOptionPoints::operator== (const ConfigOptionPoints & rhs) const throw () inline
{ return this->values == rhs.values; }
operator==() [3/3]
bool Slic3r::ConfigOptionVector< Vec2d >::operator== (const std::vector< Vec2d > & rhs) const throw () inline inherited
{ return this->values == rhs; }
overriden_by()
bool Slic3r::ConfigOptionVector< Vec2d >::overriden_by (const ConfigOption * rhs) const inline override virtual inherited
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector.overriden_by() applied to different types.");
      auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
      if (! rhs->nullable())
        // Overridding a non-nullable object with another non-nullable object.
        return this->values != rhs_vec->values;
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i])
          return true;
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i))
          return true;
      return false;
    }
resize()
void Slic3r::ConfigOptionVector< Vec2d >::resize (size_t n, const ConfigOption * opt_default = nullptr) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        assert(opt_default == nullptr || opt_default->is_vector());
//        assert(opt_default == nullptr || dynamic_cast<ConfigOptionVector<T>>(opt_default));
        assert(! this->values.empty() || opt_default != nullptr);
        if (n == 0)
            this->values.clear();
        else if (n < this->values.size())
            this->values.erase(this->values.begin() + n, this->values.end());
        else if (n > this->values.size()) {
            if (this->values.empty()) {
                if (opt_default == nullptr)
                    throw ConfigurationError("ConfigOptionVector::resize(): No default value provided.");
                if (opt_default->type() != this->type())
                    throw ConfigurationError("ConfigOptionVector::resize(): Extending with an incompatible type.");
                this->values.resize(n, static_cast<const ConfigOptionVector<T>*>(opt_default)->values.front());
            } else {
                // Resize by duplicating the last value.
                this->values.resize(n, this->values./*back*/front());
            }
        }
    }
save()
template<class Archive > void Slic3r::ConfigOptionPoints::save (Archive & archive) const inline private
{
    size_t cnt = this->values.size();
    archive(cnt);
    archive.saveBinary((const char*)this->values.data(), sizeof(Vec2d) * cnt);
  }
scalar_type()
ConfigOptionType Slic3r::ConfigOptionVectorBase::scalar_type () const inline protected inherited
{ return static_cast<ConfigOptionType>(this->type() - coVectorType); }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::ConfigOptionVector< T >::set(), and Slic3r::ConfigOptionVector< T >::set_at().
serialize()
std::string Slic3r::ConfigOptionPoints::serialize () const inline override virtual
Implements Slic3r::ConfigOption.
    {
        std::ostringstream ss;
        for (Pointfs::const_iterator it = this->values.begin(); it != this->values.end(); ++it) {
            if (it - this->values.begin() != 0) ss << ",";
            ss << (*it)(0);
            ss << "x";
            ss << (*it)(1);
        }
        return ss.str();
    }
set() [1/2]
void Slic3r::ConfigOptionVector< Vec2d >::set (const ConfigOption * rhs) inline override virtual inherited
Implements Slic3r::ConfigOption.
    {
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector: Assigning an incompatible type");
        assert(dynamic_cast<const ConfigOptionVector<T>*>(rhs));
        this->values = static_cast<const ConfigOptionVector<T>*>(rhs)->values;
    }
set() [2/2]
void Slic3r::ConfigOptionVector< Vec2d >::set (const std::vector< const ConfigOption * > & rhs) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        this->values.clear();
        this->values.reserve(rhs.size());
        for (const ConfigOption *opt : rhs) {
            if (opt->type() == this->type()) {
                auto other = static_cast<const ConfigOptionVector<T>*>(opt);
                if (other->values.empty())
                    throw ConfigurationError("ConfigOptionVector::set(): Assigning from an empty vector");
                this->values.emplace_back(other->values.front());
            } else if (opt->type() == this->scalar_type())
                this->values.emplace_back(static_cast<const ConfigOptionSingle<T>*>(opt)->value);
            else
                throw ConfigurationError("ConfigOptionVector::set():: Assigning an incompatible type");
        }
    }
set_at()
void Slic3r::ConfigOptionVector< Vec2d >::set_at (const ConfigOption * rhs, size_t i, size_t j) inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
    {
        // It is expected that the vector value has at least one value, which is the default, if not overwritten.
        assert(! this->values.empty());
        if (this->values.size() <= i) {
            // Resize this vector, fill in the new vector fields with the copy of the first field.
            T v = this->values.front();
            this->values.resize(i + 1, v);
        }
        if (rhs->type() == this->type()) {
            // Assign the first value of the rhs vector.
            auto other = static_cast<const ConfigOptionVector<T>*>(rhs);
            if (other->values.empty())
                throw ConfigurationError("ConfigOptionVector::set_at(): Assigning from an empty vector");
            this->values[i] = other->get_at(j);
        } else if (rhs->type() == this->scalar_type())
            this->values[i] = static_cast<const ConfigOptionSingle<T>*>(rhs)->value;
        else
            throw ConfigurationError("ConfigOptionVector::set_at(): Assigning an incompatible type");
    }
setInt()
virtual void Slic3r::ConfigOption::setInt (int) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::setInt on a non-int ConfigOption"); }
size()
size_t Slic3r::ConfigOptionVector< Vec2d >::size () const inline override virtual inherited
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.size(); }
static_type()
static ConfigOptionType Slic3r::ConfigOptionPoints::static_type () inline static
{ return coPoints; }
References Slic3r::coPoints.
Referenced by type().
type()
ConfigOptionType Slic3r::ConfigOptionPoints::type () const inline override virtual
Implements Slic3r::ConfigOption.
{ return static_type(); }
References static_type().
vserialize()
std::vector< std::string > Slic3r::ConfigOptionPoints::vserialize () const inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
    {
        std::vector<std::string> vv;
        for (Pointfs::const_iterator it = this->values.begin(); it != this->values.end(); ++it) {
            std::ostringstream ss;
            ss << *it;
            vv.push_back(ss.str());
        }
        return vv;
    }
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
values
std::vector<Vec2d > Slic3r::ConfigOptionVector< Vec2d >::values inherited
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp