Prusa Slicer: Slic3r::anonymous_namespace{ZipperArchiveImport.cpp} Namespace Reference
Slic3r::anonymous_namespace{ZipperArchiveImport.cpp} Namespace Reference
Functions
boost::property_tree::ptree read_ini (const mz_zip_archive_file_stat &entry, MZ_Archive &zip)
EntryBuffer read_entry (const mz_zip_archive_file_stat &entry, MZ_Archive &zip, const std::string &name)
Function Documentation
read_entry()
EntryBuffer Slic3r::anonymous_namespace{ZipperArchiveImport.cpp}::read_entry (const mz_zip_archive_file_stat & entry, MZ_Archive & zip, const std::string & name)
{
    std::vector<uint8_t> buf(entry.m_uncomp_size);
    if (!mz_zip_reader_extract_to_mem(&zip.arch, entry.m_file_index,
                                           buf.data(), buf.size(), 0))
        throw Slic3r::FileIOError(zip.get_errorstr());
    return {std::move(buf), (name.empty() ? entry.m_filename : name)};
}
References mz_zip_archive_file_stat::m_file_index, mz_zip_archive_file_stat::m_filename, mz_zip_archive_file_stat::m_uncomp_size, mz_zip_reader_extract_to_mem(), read_entry(), and Slic3r::zip().
Referenced by read_entry().
read_ini()
boost::property_tree::ptree Slic3r::anonymous_namespace{ZipperArchiveImport.cpp}::read_ini (const mz_zip_archive_file_stat & entry, MZ_Archive & zip)
{
    std::string buf(size_t(entry.m_uncomp_size), '\0');
    if (!mz_zip_reader_extract_to_mem(&zip.arch, entry.m_file_index,
                                           buf.data(), buf.size(), 0))
        throw Slic3r::FileIOError(zip.get_errorstr());
    boost::property_tree::ptree tree;
    std::stringstream           ss(buf);
    boost::property_tree::read_ini(ss, tree);
    return tree;
}
References mz_zip_archive_file_stat::m_file_index, mz_zip_archive_file_stat::m_uncomp_size, mz_zip_reader_extract_to_mem(), read_ini(), and Slic3r::zip().
Referenced by read_ini().