Prusa Slicer: Slic3r::IndexRange< T > Class Template Reference
Slic3r::IndexRange< T > Class Template Reference
#include <src/libslic3r/Layer.hpp>
Classes
class Iterator
Public Member Functions
IndexRange (T ibegin, T iend)
IndexRange ()=default
Iterator begin () const
Iterator end () const
bool empty () const
T size () const
Private Attributes
T m_begin { 0 }
T m_end { 0 }
Detailed Description
template<typename T>
class Slic3r::IndexRange< T >
Constructor & Destructor Documentation
IndexRange() [1/2]
template<typename T > Slic3r::IndexRange< T >::IndexRange (T ibegin, T iend) inline
: m_begin(ibegin), m_end(iend) {}
IndexRange() [2/2]
template<typename T > Slic3r::IndexRange< T >::IndexRange () default
Member Function Documentation
begin()
template<typename T > Iterator Slic3r::IndexRange< T >::begin () const inline
{ assert(m_begin <= m_end); return Iterator(m_begin); };
References Slic3r::IndexRange< T >::m_begin, and Slic3r::IndexRange< T >::m_end.
Referenced by Slic3r::LayerIsland::add_fill_range().
empty()
template<typename T > bool Slic3r::IndexRange< T >::empty () const inline
{ assert(m_begin <= m_end); return m_begin >= m_end; }
References Slic3r::IndexRange< T >::m_begin, and Slic3r::IndexRange< T >::m_end.
Referenced by Slic3r::LayerIsland::has_extrusions(), and Slic3r::Layer::sort_perimeters_into_islands().
end()
template<typename T > Iterator Slic3r::IndexRange< T >::end () const inline
{ assert(m_begin <= m_end); return Iterator(m_end); };
References Slic3r::IndexRange< T >::m_begin, and Slic3r::IndexRange< T >::m_end.
Referenced by Slic3r::LayerIsland::add_fill_range().
size()
template<typename T > T Slic3r::IndexRange< T >::size () const inline
{ assert(m_begin <= m_end); return m_end - m_begin; }
References Slic3r::IndexRange< T >::m_begin, and Slic3r::IndexRange< T >::m_end.
Referenced by Slic3r::Layer::sort_perimeters_into_islands().
Member Data Documentation
m_begin
template<typename T > T Slic3r::IndexRange< T >::m_begin { 0 } private
Referenced by Slic3r::IndexRange< T >::begin(), Slic3r::IndexRange< T >::empty(), Slic3r::IndexRange< T >::end(), and Slic3r::IndexRange< T >::size().
m_end
template<typename T > T Slic3r::IndexRange< T >::m_end { 0 } private
Referenced by Slic3r::IndexRange< T >::begin(), Slic3r::IndexRange< T >::empty(), Slic3r::IndexRange< T >::end(), and Slic3r::IndexRange< T >::size().
The documentation for this class was generated from the following file:
src/libslic3r/Layer.hpp