Prusa Slicer: Slic3r::GUI::GLCanvas3D::Tooltip Class Reference
Slic3r::GUI::GLCanvas3D::Tooltip Class Reference
Public Member Functions
bool is_empty () const
void set_text (const std::string &text)
void render (const Vec2d &mouse_position, GLCanvas3D &canvas)
void set_in_imgui (bool b)
bool is_in_imgui () const
Private Attributes
std::string m_text
std::chrono::steady_clock::time_point m_start_time
bool m_in_imgui = false
float m_cursor_height { 16.0f }
Detailed Description
Member Function Documentation
is_empty()
bool Slic3r::GUI::GLCanvas3D::Tooltip::is_empty () const inline
{ return m_text.empty(); }
References m_text.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse().
is_in_imgui()
bool Slic3r::GUI::GLCanvas3D::Tooltip::is_in_imgui () const inline
{ return m_in_imgui; }
References m_in_imgui.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse().
render()
void Slic3r::GUI::GLCanvas3D::Tooltip::render (const Vec2d & mouse_position, GLCanvas3D & canvas)
{
    static ImVec2 size(0.0f, 0.0f);
    auto validate_position = [this](const Vec2d& position, const GLCanvas3D& canvas, const ImVec2& wnd_size) {
        const Size cnv_size = canvas.get_canvas_size();
        const float x = std::clamp(float(position.x()), 0.0f, float(cnv_size.get_width()) - wnd_size.x);
        const float y = std::clamp(float(position.y()) + m_cursor_height, 0.0f, float(cnv_size.get_height()) - wnd_size.y);
        return Vec2f(x, y);
    };
    if (m_text.empty()) {
        m_start_time = std::chrono::steady_clock::now();
        return;
    }
    // draw the tooltip as hidden until the delay is expired
    // use a value of alpha slightly different from 0.0f because newer imgui does not calculate properly the window size if alpha == 0.0f
    const float alpha = (std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - m_start_time).count() < 500) ? 0.01f : 1.0f;
    const Vec2f position = validate_position(mouse_position, canvas, size);
    ImGuiWrapper& imgui = *wxGetApp().imgui();
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_Alpha, alpha);
    imgui.set_next_window_pos(position.x(), position.y(), ImGuiCond_Always, 0.0f, 0.0f);
    imgui.begin(wxString("canvas_tooltip"), ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoMouseInputs | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoFocusOnAppearing);
    ImGui::BringWindowToDisplayFront(ImGui::GetCurrentWindow());
    ImGui::TextUnformatted(m_text.c_str());
    // force re-render while the windows gets to its final size (it may take several frames) or while hidden
    if (alpha < 1.0f || ImGui::GetWindowContentRegionWidth() + 2.0f * ImGui::GetStyle().WindowPadding.x != ImGui::CalcWindowNextAutoFitSize(ImGui::GetCurrentWindow()).x)
        imgui.set_requires_extra_frame();
    size = ImGui::GetWindowSize();
    imgui.end();
    ImGui::PopStyleVar(2);
}
References Slic3r::GUI::ImGuiWrapper::begin(), ImGui::BringWindowToDisplayFront(), ImGui::CalcWindowNextAutoFitSize(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), ImGui::GetCurrentWindow(), ImGui::GetStyle(), ImGui::GetWindowContentRegionWidth(), ImGui::GetWindowSize(), ImGuiCond_Always, ImGuiStyleVar_Alpha, ImGuiStyleVar_WindowRounding, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoDecoration, ImGuiWindowFlags_NoFocusOnAppearing, ImGuiWindowFlags_NoMouseInputs, ImGuiWindowFlags_NoMove, ImGui::PopStyleVar(), ImGui::PushStyleVar(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::ImGuiWrapper::set_requires_extra_frame(), ImGui::TextUnformatted(), and ImVec2::x.
Referenced by Slic3r::GUI::GLCanvas3D::render().
set_in_imgui()
void Slic3r::GUI::GLCanvas3D::Tooltip::set_in_imgui (bool b) inline
{ m_in_imgui = b; }
References m_in_imgui.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse().
set_text()
void Slic3r::GUI::GLCanvas3D::Tooltip::set_text (const std::string & text)
{
    // If the mouse is inside an ImGUI dialog, then the tooltip is suppressed.
    const std::string& new_text = m_in_imgui ? std::string() : text;
    if (m_text != new_text) { // To avoid calling the expensive call to get_cursor_height.
        m_text = new_text;
        m_cursor_height = get_cursor_height();
    }
}
References Slic3r::GUI::get_cursor_height().
Referenced by Slic3r::GUI::GLCanvas3D::set_tooltip().
Member Data Documentation
m_cursor_height
float Slic3r::GUI::GLCanvas3D::Tooltip::m_cursor_height { 16.0f } private
m_in_imgui
bool Slic3r::GUI::GLCanvas3D::Tooltip::m_in_imgui = false private
Referenced by is_in_imgui(), and set_in_imgui().
m_start_time
std::chrono::steady_clock::time_point Slic3r::GUI::GLCanvas3D::Tooltip::m_start_time private
m_text
std::string Slic3r::GUI::GLCanvas3D::Tooltip::m_text private
Referenced by is_empty().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLCanvas3D.hpp
src/slic3r/GUI/GLCanvas3D.cpp