Prusa Slicer: Eigen::GeneralizedEigenSolver< _MatrixType > Class Template Reference
Eigen::GeneralizedEigenSolver< _MatrixType > Class Template Reference
Computes the generalized eigenvalues and eigenvectors of a pair of general matrices.
#include <src/eigen/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , Options = MatrixType::Options , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
Synonym for the template parameter _MatrixType.
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType.
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef std::complex< RealScalar > ComplexScalar
Complex scalar type for MatrixType.
typedef Matrix< Scalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > VectorType
Type for vector of real scalar values eigenvalues as returned by betas().
typedef Matrix< ComplexScalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > ComplexVectorType
Type for vector of complex scalar values eigenvalues as returned by alphas().
typedef CwiseBinaryOp< internal::scalar_quotient_op< ComplexScalar, Scalar >, ComplexVectorType, VectorType > EigenvalueType
Expression type for the eigenvalues as returned by eigenvalues().
typedef Matrix< ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime > EigenvectorsType
Type for matrix of eigenvectors as returned by eigenvectors().
Public Member Functions
GeneralizedEigenSolver ()
Default constructor.
GeneralizedEigenSolver (Index size)
Default constructor with memory preallocation.
GeneralizedEigenSolver (const MatrixType &A, const MatrixType &B, bool computeEigenvectors=true)
Constructor; computes the generalized eigendecomposition of given matrix pair.
EigenvectorsType eigenvectors () const
EigenvalueType eigenvalues () const
Returns an expression of the computed generalized eigenvalues.
ComplexVectorType alphas () const
VectorType betas () const
GeneralizedEigenSolver & compute (const MatrixType &A, const MatrixType &B, bool computeEigenvectors=true)
Computes generalized eigendecomposition of given matrix.
ComputationInfo info () const
GeneralizedEigenSolver & setMaxIterations (Index maxIters)
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
EigenvectorsType m_eivec
ComplexVectorType m_alphas
VectorType m_betas
bool m_valuesOkay
bool m_vectorsOkay
RealQZ< MatrixType > m_realQZ
ComplexVectorType m_tmp
Detailed Description
template<typename _MatrixType>
class Eigen::GeneralizedEigenSolver< _MatrixType >
Computes the generalized eigenvalues and eigenvectors of a pair of general matrices.
\eigenvalues_module
Template Parameters
_MatrixType the type of the matrices of which we are computing the eigen-decomposition; this is expected to be an instantiation of the Matrix class template. Currently, only real matrices are supported.
The generalized eigenvalues and eigenvectors of a matrix pair and are scalars and vectors such that . If is a diagonal matrix with the eigenvalues on the diagonal, and is a matrix with the eigenvectors as its columns, then . The matrix is almost always invertible, in which case we have . This is called the generalized eigen-decomposition.
The generalized eigenvalues and eigenvectors of a matrix pair may be complex, even when the matrices are real. Moreover, the generalized eigenvalue might be infinite if the matrix B is singular. To workaround this difficulty, the eigenvalues are provided as a pair of complex and real such that: . If is (nearly) zero, then one can consider the well defined left eigenvalue such that: , or even where is called the left eigenvector.
Call the function compute() to compute the generalized eigenvalues and eigenvectors of a given matrix pair. Alternatively, you can use the GeneralizedEigenSolver(const MatrixType&, const MatrixType&, bool) constructor which computes the eigenvalues and eigenvectors at construction time. Once the eigenvalue and eigenvectors are computed, they can be retrieved with the eigenvalues() and eigenvectors() functions.
Here is an usage example of this class: Example:
Output:
See also
MatrixBase::eigenvalues(), class ComplexEigenSolver, class SelfAdjointEigenSolver
Member Typedef Documentation
ComplexScalar
template<typename _MatrixType > typedef std::complex<RealScalar> Eigen::GeneralizedEigenSolver< _MatrixType >::ComplexScalar
Complex scalar type for MatrixType.
This is std::complex<Scalar> if Scalar is real (e.g., float or double) and just Scalar if Scalar is complex.
ComplexVectorType
template<typename _MatrixType > typedef Matrix<ComplexScalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::GeneralizedEigenSolver< _MatrixType >::ComplexVectorType
Type for vector of complex scalar values eigenvalues as returned by alphas().
This is a column vector with entries of type ComplexScalar. The length of the vector is the size of MatrixType.
EigenvalueType
template<typename _MatrixType > typedef CwiseBinaryOp<internal::scalar_quotient_op<ComplexScalar,Scalar>,ComplexVectorType,VectorType> Eigen::GeneralizedEigenSolver< _MatrixType >::EigenvalueType
Expression type for the eigenvalues as returned by eigenvalues().
EigenvectorsType
template<typename _MatrixType > typedef Matrix<ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::GeneralizedEigenSolver< _MatrixType >::EigenvectorsType
Type for matrix of eigenvectors as returned by eigenvectors().
This is a square matrix with entries of type ComplexScalar. The size is the same as the size of MatrixType.
Index
template<typename _MatrixType > typedef Eigen::Index Eigen::GeneralizedEigenSolver< _MatrixType >::Index
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::GeneralizedEigenSolver< _MatrixType >::MatrixType
Synonym for the template parameter _MatrixType.
RealScalar
template<typename _MatrixType > typedef NumTraits<Scalar>::Real Eigen::GeneralizedEigenSolver< _MatrixType >::RealScalar
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::GeneralizedEigenSolver< _MatrixType >::Scalar
Scalar type for matrices of type MatrixType.
VectorType
template<typename _MatrixType > typedef Matrix<Scalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::GeneralizedEigenSolver< _MatrixType >::VectorType
Type for vector of real scalar values eigenvalues as returned by betas().
This is a column vector with entries of type Scalar. The length of the vector is the size of MatrixType.
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
         {
      RowsAtCompileTime = MatrixType::RowsAtCompileTime,
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      Options = MatrixType::Options,
      MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
GeneralizedEigenSolver() [1/3]
template<typename _MatrixType > Eigen::GeneralizedEigenSolver< _MatrixType >::GeneralizedEigenSolver () inline
Default constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via EigenSolver::compute(const MatrixType&, bool).
See also
compute() for an example.
      : m_eivec(),
        m_alphas(),
        m_betas(),
        m_valuesOkay(false),
        m_vectorsOkay(false),
        m_realQZ()
    {}
GeneralizedEigenSolver() [2/3]
template<typename _MatrixType > Eigen::GeneralizedEigenSolver< _MatrixType >::GeneralizedEigenSolver (Index size) inline explicit
Default constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
GeneralizedEigenSolver()
      : m_eivec(size, size),
        m_alphas(size),
        m_betas(size),
        m_valuesOkay(false),
        m_vectorsOkay(false),
        m_realQZ(size),
        m_tmp(size)
    {}
GeneralizedEigenSolver() [3/3]
template<typename _MatrixType > Eigen::GeneralizedEigenSolver< _MatrixType >::GeneralizedEigenSolver (const MatrixType & A, const MatrixType & B, bool computeEigenvectors = true) inline
Constructor; computes the generalized eigendecomposition of given matrix pair.
Parameters
[in] A Square matrix whose eigendecomposition is to be computed.
[in] B Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
This constructor calls compute() to compute the generalized eigenvalues and eigenvectors.
See also
compute()
      : m_eivec(A.rows(), A.cols()),
        m_alphas(A.cols()),
        m_betas(A.cols()),
        m_valuesOkay(false),
        m_vectorsOkay(false),
        m_realQZ(A.cols()),
        m_tmp(A.cols())
    {
      compute(A, B, computeEigenvectors);
    }
References Eigen::GeneralizedEigenSolver< _MatrixType >::compute().
Member Function Documentation
alphas()
template<typename _MatrixType > ComplexVectorType Eigen::GeneralizedEigenSolver< _MatrixType >::alphas () const inline
Returns
A const reference to the vectors containing the alpha values
This vector permits to reconstruct the j-th eigenvalues as alphas(i)/betas(j).
See also
betas(), eigenvalues()
    {
      eigen_assert(m_valuesOkay && "GeneralizedEigenSolver is not initialized.");
      return m_alphas;
    }
References eigen_assert, Eigen::GeneralizedEigenSolver< _MatrixType >::m_alphas, and Eigen::GeneralizedEigenSolver< _MatrixType >::m_valuesOkay.
betas()
template<typename _MatrixType > VectorType Eigen::GeneralizedEigenSolver< _MatrixType >::betas () const inline
Returns
A const reference to the vectors containing the beta values
This vector permits to reconstruct the j-th eigenvalues as alphas(i)/betas(j).
See also
alphas(), eigenvalues()
    {
      eigen_assert(m_valuesOkay && "GeneralizedEigenSolver is not initialized.");
      return m_betas;
    }
References eigen_assert, Eigen::GeneralizedEigenSolver< _MatrixType >::m_betas, and Eigen::GeneralizedEigenSolver< _MatrixType >::m_valuesOkay.
check_template_parameters()
template<typename _MatrixType > static void Eigen::GeneralizedEigenSolver< _MatrixType >::check_template_parameters () inline static protected
    {
      EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
      EIGEN_STATIC_ASSERT(!NumTraits<Scalar>::IsComplex, NUMERIC_TYPE_MUST_BE_REAL);
    }
References EIGEN_STATIC_ASSERT, and EIGEN_STATIC_ASSERT_NON_INTEGER.
compute()
template<typename MatrixType > GeneralizedEigenSolver< MatrixType > & Eigen::GeneralizedEigenSolver< MatrixType >::compute (const MatrixType & A, const MatrixType & B, bool computeEigenvectors = true)
Computes generalized eigendecomposition of given matrix.
Parameters
[in] A Square matrix whose eigendecomposition is to be computed.
[in] B Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
Returns
Reference to *this
This function computes the eigenvalues of the real matrix matrix. The eigenvalues() function can be used to retrieve them. If computeEigenvectors is true, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
The matrix is first reduced to real generalized Schur form using the RealQZ class. The generalized Schur decomposition is then used to compute the eigenvalues and eigenvectors.
The cost of the computation is dominated by the cost of the generalized Schur decomposition.
This method reuses of the allocated data in the GeneralizedEigenSolver object.
{
  check_template_parameters();
  using std::sqrt;
  using std::abs;
  eigen_assert(A.cols() == A.rows() && B.cols() == A.rows() && B.cols() == B.rows());
  Index size = A.cols();
  m_valuesOkay = false;
  m_vectorsOkay = false;
  // Reduce to generalized real Schur form:
  // A = Q S Z and B = Q T Z
  m_realQZ.compute(A, B, computeEigenvectors);
  if (m_realQZ.info() == Success)
  {
    // Resize storage
    m_alphas.resize(size);
    m_betas.resize(size);
    if (computeEigenvectors)
    {
      m_eivec.resize(size,size);
      m_tmp.resize(size);
    }
    // Aliases:
    Map<VectorType> v(reinterpret_cast<Scalar*>(m_tmp.data()), size);
    ComplexVectorType &cv = m_tmp;
    const MatrixType &mS = m_realQZ.matrixS();
    const MatrixType &mT = m_realQZ.matrixT();
    Index i = 0;
    while (i < size)
    {
      if (i == size - 1 || mS.coeff(i+1, i) == Scalar(0))
      {
        // Real eigenvalue
        m_alphas.coeffRef(i) = mS.diagonal().coeff(i);
        m_betas.coeffRef(i)  = mT.diagonal().coeff(i);
        if (computeEigenvectors)
        {
          v.setConstant(Scalar(0.0));
          v.coeffRef(i) = Scalar(1.0);
          // For singular eigenvalues do nothing more
          if(abs(m_betas.coeffRef(i)) >= (std::numeric_limits<RealScalar>::min)())
          {
            // Non-singular eigenvalue
            const Scalar alpha = real(m_alphas.coeffRef(i));
            const Scalar beta = m_betas.coeffRef(i);
            for (Index j = i-1; j >= 0; j--)
            {
              const Index st = j+1;
              const Index sz = i-j;
              if (j > 0 && mS.coeff(j, j-1) != Scalar(0))
              {
                // 2x2 block
                Matrix<Scalar, 2, 1> rhs = (alpha*mT.template block<2,Dynamic>(j-1,st,2,sz) - beta*mS.template block<2,Dynamic>(j-1,st,2,sz)) .lazyProduct( v.segment(st,sz) );
                Matrix<Scalar, 2, 2> lhs = beta * mS.template block<2,2>(j-1,j-1) - alpha * mT.template block<2,2>(j-1,j-1);
                v.template segment<2>(j-1) = lhs.partialPivLu().solve(rhs);
                j--;
              }
              else
              {
                v.coeffRef(j) = -v.segment(st,sz).transpose().cwiseProduct(beta*mS.block(j,st,1,sz) - alpha*mT.block(j,st,1,sz)).sum() / (beta*mS.coeffRef(j,j) - alpha*mT.coeffRef(j,j));
              }
            }
          }
          m_eivec.col(i).real().noalias() = m_realQZ.matrixZ().transpose() * v;
          m_eivec.col(i).real().normalize();
          m_eivec.col(i).imag().setConstant(0);
        }
        ++i;
      }
      else
      {
        // We need to extract the generalized eigenvalues of the pair of a general 2x2 block S and a positive diagonal 2x2 block T
        // Then taking beta=T_00*T_11, we can avoid any division, and alpha is the eigenvalues of A = (U^-1 * S * U) * diag(T_11,T_00):
        // T =  [a 0]
        //      [0 b]
        RealScalar a = mT.diagonal().coeff(i),
                   b = mT.diagonal().coeff(i+1);
        const RealScalar beta = m_betas.coeffRef(i) = m_betas.coeffRef(i+1) = a*b;
        // ^^ NOTE: using diagonal()(i) instead of coeff(i,i) workarounds a MSVC bug.
        Matrix<RealScalar,2,2> S2 = mS.template block<2,2>(i,i) * Matrix<Scalar,2,1>(b,a).asDiagonal();
        Scalar p = Scalar(0.5) * (S2.coeff(0,0) - S2.coeff(1,1));
        Scalar z = sqrt(abs(p * p + S2.coeff(1,0) * S2.coeff(0,1)));
        const ComplexScalar alpha = ComplexScalar(S2.coeff(1,1) + p, (beta > 0) ? z : -z);
        m_alphas.coeffRef(i)   = conj(alpha);
        m_alphas.coeffRef(i+1) = alpha;
        if (computeEigenvectors) {
          // Compute eigenvector in position (i+1) and then position (i) is just the conjugate
          cv.setZero();
          cv.coeffRef(i+1) = Scalar(1.0);
          // here, the "static_cast" workaound expression template issues.
          cv.coeffRef(i) = -(static_cast<Scalar>(beta*mS.coeffRef(i,i+1)) - alpha*mT.coeffRef(i,i+1))
                          / (static_cast<Scalar>(beta*mS.coeffRef(i,i))   - alpha*mT.coeffRef(i,i));
          for (Index j = i-1; j >= 0; j--)
          {
            const Index st = j+1;
            const Index sz = i+1-j;
            if (j > 0 && mS.coeff(j, j-1) != Scalar(0))
            {
              // 2x2 block
              Matrix<ComplexScalar, 2, 1> rhs = (alpha*mT.template block<2,Dynamic>(j-1,st,2,sz) - beta*mS.template block<2,Dynamic>(j-1,st,2,sz)) .lazyProduct( cv.segment(st,sz) );
              Matrix<ComplexScalar, 2, 2> lhs = beta * mS.template block<2,2>(j-1,j-1) - alpha * mT.template block<2,2>(j-1,j-1);
              cv.template segment<2>(j-1) = lhs.partialPivLu().solve(rhs);
              j--;
            } else {
              cv.coeffRef(j) =  cv.segment(st,sz).transpose().cwiseProduct(beta*mS.block(j,st,1,sz) - alpha*mT.block(j,st,1,sz)).sum()
                              / (alpha*mT.coeffRef(j,j) - static_cast<Scalar>(beta*mS.coeffRef(j,j)));
            }
          }
          m_eivec.col(i+1).noalias() = (m_realQZ.matrixZ().transpose() * cv);
          m_eivec.col(i+1).normalize();
          m_eivec.col(i) = m_eivec.col(i+1).conjugate();
        }
        i += 2;
      }
    }
    m_valuesOkay = true;
    m_vectorsOkay = computeEigenvectors;
  }
  return *this;
}
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::coeffRef(), eigen_assert, real(), Eigen::PlainObjectBase< Derived >::setZero(), sqrt(), and Eigen::Success.
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::GeneralizedEigenSolver().
eigenvalues()
template<typename _MatrixType > EigenvalueType Eigen::GeneralizedEigenSolver< _MatrixType >::eigenvalues () const inline
Returns an expression of the computed generalized eigenvalues.
Returns
An expression of the column vector containing the eigenvalues.
It is a shortcut for
this->alphas().cwiseQuotient(this->betas());
Not that betas might contain zeros. It is therefore not recommended to use this function, but rather directly deal with the alphas and betas vectors.
Precondition
Either the constructor GeneralizedEigenSolver(const MatrixType&,const MatrixType&,bool) or the member function compute(const MatrixType&,const MatrixType&,bool) has been called before.
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix. The eigenvalues are not sorted in any particular order.
See also
alphas(), betas(), eigenvectors()
    {
      eigen_assert(m_valuesOkay && "GeneralizedEigenSolver is not initialized.");
      return EigenvalueType(m_alphas,m_betas);
    }
References eigen_assert, Eigen::GeneralizedEigenSolver< _MatrixType >::m_alphas, Eigen::GeneralizedEigenSolver< _MatrixType >::m_betas, and Eigen::GeneralizedEigenSolver< _MatrixType >::m_valuesOkay.
eigenvectors()
template<typename _MatrixType > EigenvectorsType Eigen::GeneralizedEigenSolver< _MatrixType >::eigenvectors () const inline
{
      eigen_assert(m_vectorsOkay && "Eigenvectors for GeneralizedEigenSolver were not calculated.");
      return m_eivec;
    }
References eigen_assert, Eigen::GeneralizedEigenSolver< _MatrixType >::m_eivec, and Eigen::GeneralizedEigenSolver< _MatrixType >::m_vectorsOkay.
info()
template<typename _MatrixType > ComputationInfo Eigen::GeneralizedEigenSolver< _MatrixType >::info () const inline
    {
      eigen_assert(m_valuesOkay && "EigenSolver is not initialized.");
      return m_realQZ.info();
    }
References eigen_assert, Eigen::RealQZ< _MatrixType >::info(), Eigen::GeneralizedEigenSolver< _MatrixType >::m_realQZ, and Eigen::GeneralizedEigenSolver< _MatrixType >::m_valuesOkay.
setMaxIterations()
template<typename _MatrixType > GeneralizedEigenSolver & Eigen::GeneralizedEigenSolver< _MatrixType >::setMaxIterations (Index maxIters) inline
Sets the maximal number of iterations allowed.
    {
      m_realQZ.setMaxIterations(maxIters);
      return *this;
    }
References Eigen::GeneralizedEigenSolver< _MatrixType >::m_realQZ, and Eigen::RealQZ< _MatrixType >::setMaxIterations().
Member Data Documentation
m_alphas
template<typename _MatrixType > ComplexVectorType Eigen::GeneralizedEigenSolver< _MatrixType >::m_alphas protected
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::alphas(), and Eigen::GeneralizedEigenSolver< _MatrixType >::eigenvalues().
m_betas
template<typename _MatrixType > VectorType Eigen::GeneralizedEigenSolver< _MatrixType >::m_betas protected
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::betas(), and Eigen::GeneralizedEigenSolver< _MatrixType >::eigenvalues().
m_eivec
template<typename _MatrixType > EigenvectorsType Eigen::GeneralizedEigenSolver< _MatrixType >::m_eivec protected
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::eigenvectors().
m_realQZ
template<typename _MatrixType > RealQZ<MatrixType> Eigen::GeneralizedEigenSolver< _MatrixType >::m_realQZ protected
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::info(), and Eigen::GeneralizedEigenSolver< _MatrixType >::setMaxIterations().
m_tmp
template<typename _MatrixType > ComplexVectorType Eigen::GeneralizedEigenSolver< _MatrixType >::m_tmp protected
m_valuesOkay
template<typename _MatrixType > bool Eigen::GeneralizedEigenSolver< _MatrixType >::m_valuesOkay protected
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::alphas(), Eigen::GeneralizedEigenSolver< _MatrixType >::betas(), Eigen::GeneralizedEigenSolver< _MatrixType >::eigenvalues(), and Eigen::GeneralizedEigenSolver< _MatrixType >::info().
m_vectorsOkay
template<typename _MatrixType > bool Eigen::GeneralizedEigenSolver< _MatrixType >::m_vectorsOkay protected
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::eigenvectors().
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h