Prusa Slicer: Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense > Struct Template Reference
#include <src/eigen/Eigen/src/QR/ColPivHouseholderQR.h>
Public Types
typedef ColPivHouseholderQR< MatrixType > QrType
typedef Inverse< QrType > SrcXprType
Static Public Member Functions
static void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< typename DstXprType::Scalar, typename QrType::Scalar > &)
Detailed Description
template<typename DstXprType, typename MatrixType>
struct Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >
Member Typedef Documentation
QrType
template<typename DstXprType , typename MatrixType > typedef ColPivHouseholderQR<MatrixType> Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >::QrType
SrcXprType
template<typename DstXprType , typename MatrixType > typedef Inverse<QrType> Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >::SrcXprType
Member Function Documentation
run()
template<typename DstXprType , typename MatrixType > static void Eigen::internal::Assignment< DstXprType, Inverse< ColPivHouseholderQR< MatrixType > >, internal::assign_op< typename DstXprType::Scalar, typename ColPivHouseholderQR< MatrixType >::Scalar >, Dense2Dense >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< typename DstXprType::Scalar, typename QrType::Scalar > &) inline static
  {
    dst = src.nestedExpression().solve(MatrixType::Identity(src.rows(), src.cols()));
  }
References Eigen::Inverse< XprType >::cols(), Eigen::Inverse< XprType >::nestedExpression(), and Eigen::Inverse< XprType >::rows().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/QR/ColPivHouseholderQR.h