Prusa Slicer: Slic3r::SLAPrintObject::SliceRecord Class Reference
Slic3r::SLAPrintObject::SliceRecord Class Reference
#include <src/libslic3r/SLAPrint.hpp>
Public Member Functions
SliceRecord (coord_t key, float slicez, float height)
coord_t print_level () const
float slice_level () const
float layer_height () const
bool is_valid () const
const SLAPrintObject * print_obj () const
void set_model_slice_idx (const SLAPrintObject &po, size_t id)
void set_support_slice_idx (const SLAPrintObject &po, size_t id)
const ExPolygons & get_slice (SliceOrigin o) const
size_t get_slice_idx (SliceOrigin o) const
Static Public Attributes
static const size_t NONE = size_t(-1)
static const SliceRecord EMPTY
Private Attributes
coord_t m_print_z = 0
float m_slice_z = 0.f
float m_height = 0.f
size_t m_model_slices_idx = NONE
size_t m_support_slices_idx = NONE
const SLAPrintObject * m_po = nullptr
Detailed Description
Constructor & Destructor Documentation
SliceRecord()
Slic3r::SLAPrintObject::SliceRecord::SliceRecord (coord_t key, float slicez, float height) inline
                                                            :
            m_print_z(key), m_slice_z(slicez), m_height(height) {}
Member Function Documentation
get_slice()
const ExPolygons & Slic3r::SliceRecord::get_slice (SliceOrigin o) const
{
    size_t idx = o == soModel ? m_model_slices_idx : m_support_slices_idx;
    if(m_po == nullptr) return EMPTY_SLICE;
    const std::vector<ExPolygons>& v = o == soModel? m_po->get_model_slices() :
                                                     m_po->get_support_slices();
    return idx >= v.size() ? EMPTY_SLICE : v[idx];
}
References Slic3r::SLAPrintObject::get_model_slices(), Slic3r::SLAPrintObject::get_support_slices(), m_model_slices_idx, m_po, m_support_slices_idx, and Slic3r::soModel.
Referenced by Slic3r::GUI::GLCanvas3D::_render_sla_slices(), and Slic3r::get_all_polygons().
get_slice_idx()
size_t Slic3r::SLAPrintObject::SliceRecord::get_slice_idx (SliceOrigin o) const inline
        {
            return o == soModel ? m_model_slices_idx : m_support_slices_idx;
        }
References m_model_slices_idx, m_support_slices_idx, and Slic3r::soModel.
is_valid()
bool Slic3r::SLAPrintObject::SliceRecord::is_valid () const inline
{ return m_po && ! std::isnan(m_slice_z); }
References m_po, and m_slice_z.
Referenced by Slic3r::GUI::GLCanvas3D::_render_sla_slices().
layer_height()
float Slic3r::SLAPrintObject::SliceRecord::layer_height () const inline
{ return m_height; }
References m_height.
print_level()
coord_t Slic3r::SLAPrintObject::SliceRecord::print_level () const inline
{ return m_print_z; }
References m_print_z.
Referenced by Slic3r::SLAPrintObject::level().
print_obj()
const SLAPrintObject * Slic3r::SLAPrintObject::SliceRecord::print_obj () const inline
{ return m_po; }
References m_po.
Referenced by Slic3r::get_all_polygons().
set_model_slice_idx()
void Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx (const SLAPrintObject & po, size_t id) inline
{
            m_po = &po; m_model_slices_idx = id;
        }
References Slic3r::ObjectBase::id(), m_model_slices_idx, and m_po.
set_support_slice_idx()
void Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx (const SLAPrintObject & po, size_t id) inline
{
            m_po = &po; m_support_slices_idx = id;
        }
References Slic3r::ObjectBase::id(), m_po, and m_support_slices_idx.
slice_level()
float Slic3r::SLAPrintObject::SliceRecord::slice_level () const inline
{ return m_slice_z; }
References m_slice_z.
Referenced by Slic3r::SLAPrintObject::level().
Member Data Documentation
EMPTY
const SliceRecord Slic3r::SliceRecord::EMPTY static
Referenced by Slic3r::SLAPrintObject::closest_slice_to_print_level(), and Slic3r::SLAPrintObject::closest_slice_to_slice_level().
m_height
float Slic3r::SLAPrintObject::SliceRecord::m_height = 0.f private
Referenced by layer_height().
m_model_slices_idx
size_t Slic3r::SLAPrintObject::SliceRecord::m_model_slices_idx = NONE private
Referenced by get_slice(), get_slice_idx(), and set_model_slice_idx().
m_po
const SLAPrintObject* Slic3r::SLAPrintObject::SliceRecord::m_po = nullptr private
Referenced by get_slice(), is_valid(), print_obj(), set_model_slice_idx(), and set_support_slice_idx().
m_print_z
coord_t Slic3r::SLAPrintObject::SliceRecord::m_print_z = 0 private
Referenced by print_level().
m_slice_z
float Slic3r::SLAPrintObject::SliceRecord::m_slice_z = 0.f private
Referenced by is_valid(), and slice_level().
m_support_slices_idx
size_t Slic3r::SLAPrintObject::SliceRecord::m_support_slices_idx = NONE private
Referenced by get_slice(), get_slice_idx(), and set_support_slice_idx().
NONE
const size_t Slic3r::SLAPrintObject::SliceRecord::NONE = size_t(-1) static
The documentation for this class was generated from the following files:
src/libslic3r/SLAPrint.hpp
src/libslic3r/SLAPrint.cpp