Prusa Slicer: Slic3r::GUI::GLCanvas3D::GizmoHighlighter Struct Reference
Slic3r::GUI::GLCanvas3D::GizmoHighlighter Struct Reference
Public Member Functions
void set_timer_owner (wxEvtHandler *owner, int timerid=wxID_ANY)
void init (GLGizmosManager *manager, GLGizmosManager::EType gizmo, GLCanvas3D *canvas)
void blink ()
void invalidate ()
Public Attributes
bool m_render_arrow { false }
GLGizmosManager::EType m_gizmo_type
Private Attributes
GLGizmosManager * m_gizmo_manager { nullptr }
GLCanvas3D * m_canvas { nullptr }
int m_blink_counter { 0 }
GizmoHighlighterTimer m_timer
Detailed Description
Member Function Documentation
blink()
void Slic3r::GUI::GLCanvas3D::GizmoHighlighter::blink ()
{
    if (m_gizmo_manager) {
        if (m_blink_counter % 2 == 0)
            m_gizmo_manager->set_highlight(m_gizmo_type, true);
        else
            m_gizmo_manager->set_highlight(m_gizmo_type, false);
        m_render_arrow = !m_render_arrow;
        m_canvas->set_as_dirty();
    }
    else
        invalidate();
    if ((++m_blink_counter) >= 11)
        invalidate();
}
References Slic3r::GUI::GLCanvas3D::set_as_dirty().
Referenced by Slic3r::GUI::GLCanvas3D::bind_event_handlers().
init()
void Slic3r::GUI::GLCanvas3D::GizmoHighlighter::init (GLGizmosManager * manager, GLGizmosManager::EType gizmo, GLCanvas3D * canvas)
{
    if (m_timer.IsRunning())
        invalidate();
    if (gizmo == GLGizmosManager::EType::Undefined || !canvas)
        return;
    m_timer.Start(300, false);
    m_gizmo_manager = manager;
    m_gizmo_type    = gizmo;
    m_canvas        = canvas;
}
invalidate()
void Slic3r::GUI::GLCanvas3D::GizmoHighlighter::invalidate ()
{
    m_timer.Stop();
    if (m_gizmo_manager) {
        m_gizmo_manager->set_highlight(GLGizmosManager::EType::Undefined, false);
    }
    m_gizmo_manager = nullptr;
    m_gizmo_type = GLGizmosManager::EType::Undefined;
    m_blink_counter = 0;
    m_render_arrow = false;
}
set_timer_owner()
void Slic3r::GUI::GLCanvas3D::GizmoHighlighter::set_timer_owner (wxEvtHandler * owner, int timerid = wxID_ANY)
{
    m_timer.SetOwner(owner, timerid);
}
Referenced by Slic3r::GUI::GLCanvas3D::bind_event_handlers().
Member Data Documentation
m_blink_counter
int Slic3r::GUI::GLCanvas3D::GizmoHighlighter::m_blink_counter { 0 } private
m_canvas
GLCanvas3D* Slic3r::GUI::GLCanvas3D::GizmoHighlighter::m_canvas { nullptr } private
m_gizmo_manager
GLGizmosManager* Slic3r::GUI::GLCanvas3D::GizmoHighlighter::m_gizmo_manager { nullptr } private
m_gizmo_type
GLGizmosManager::EType Slic3r::GUI::GLCanvas3D::GizmoHighlighter::m_gizmo_type
m_render_arrow
bool Slic3r::GUI::GLCanvas3D::GizmoHighlighter::m_render_arrow { false }
m_timer
GizmoHighlighterTimer Slic3r::GUI::GLCanvas3D::GizmoHighlighter::m_timer private
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GLCanvas3D.hpp
src/slic3r/GUI/GLCanvas3D.cpp