Prusa Slicer: Eigen::ArrayBase< Derived > Class Template Reference
Eigen::ArrayBase< Derived > Class Template Reference
Base class for all 1D and 2D array, and related expressions.
#include <src/eigen/Eigen/src/Core/ArrayBase.h>
Public Types
typedef ArrayBase StorageBaseType
typedef ArrayBase Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef Base::PlainObject PlainObject
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime , Flags = internal::traits<Derived>::Flags ,
IsRowMajor = int(Flags) & RowMajorBit , InnerSizeAtCompileTime , InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret , OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef internal::traits< Derived >::StorageIndex StorageIndex
The type used to store indices.
typedef Scalar value_type
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > SequentialLinSpacedReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar, PacketScalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef Matrix< typename NumTraits< typename internal::traits< Derived >::Scalar >::Real, internal::traits< Derived >::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const< Transpose< constDerived > >::type ConstTransposeReturnType
typedef internal::add_const_on_value_type< typenameinternal::eval< Derived >::type >::type EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const ArrayBase &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const Scalar &value)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator+= (const Scalar &scalar)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator-= (const Scalar &scalar)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator+= (const ArrayBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator-= (const ArrayBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const ArrayBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const ArrayBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC ArrayBase< Derived > & array ()
EIGEN_DEVICE_FUNC const ArrayBase< Derived > & array () const
EIGEN_DEVICE_FUNC MatrixWrapper< Derived > matrix ()
EIGEN_DEVICE_FUNC const MatrixWrapper< const Derived > matrix () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC Index nonZeros () const
EIGEN_DEVICE_FUNC Index outerSize () const
EIGEN_DEVICE_FUNC Index innerSize () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename Derived >
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename OtherDerived >
bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool hasNaN () const
bool allFinite () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > forceAlignedAccess () const
EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
EIGEN_DEVICE_FUNC const internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf () const
template<bool Enable>
EIGEN_DEVICE_FUNC internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC Scalar prod () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Func >
EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar redux (const Func &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, const typename ThenDerived::Scalar &elseScalar) const
template<typename ElseDerived >
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (const typename ElseDerived::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
template<int RowFactor, int ColFactor>
const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Protected Member Functions
EIGEN_DEVICE_FUNC ArrayBase ()
template<typename OtherDerived >
Derived & operator+= (const MatrixBase< OtherDerived > &)
template<typename OtherDerived >
Derived & operator-= (const MatrixBase< OtherDerived > &)
Private Member Functions
ArrayBase (Index)
ArrayBase (Index, Index)
template<typename OtherDerived >
ArrayBase (const ArrayBase< OtherDerived > &)
Related Symbols
(Note that these are not member symbols.)
template<typename Derived , typename ScalarExponent >
internal::enable_if<!(internal::is_same< typenameDerived::Scalar, ScalarExponent >::value)&&EIGEN_SCALAR_BINARY_SUPPORTED(pow, typenameDerived::Scalar, ScalarExponent), constEIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(Derived, ScalarExponent, pow)>::type pow (const Eigen::ArrayBase< Derived > &x, const ScalarExponent &exponent)
template<typename Derived , typename ExponentDerived >
const Eigen::CwiseBinaryOp< Eigen::internal::scalar_pow_op< typename Derived::Scalar, typename ExponentDerived::Scalar >, const Derived, const ExponentDerived > pow (const Eigen::ArrayBase< Derived > &x, const Eigen::ArrayBase< ExponentDerived > &exponents)
template<typename Scalar , typename Derived >
internal::enable_if<!(internal::is_same< typenameDerived::Scalar, Scalar >::value)&&EIGEN_SCALAR_BINARY_SUPPORTED(pow, Scalar, typenameDerived::Scalar), constEIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(Scalar, Derived, pow)>::type pow (const Scalar &x, const Eigen::ArrayBase< Derived > &exponents)
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename Derived>
class Eigen::ArrayBase< Derived >
Base class for all 1D and 2D array, and related expressions.
An array is similar to a dense vector or matrix. While matrices are mathematical objects with well defined linear algebra operators, an array is just a collection of scalar values arranged in a one or two dimensionnal fashion. As the main consequence, all operations applied to an array are performed coefficient wise. Furthermore, arrays support scalar math functions of the c++ standard library (e.g., std::sin(x)), and convenient constructors allowing to easily write generic code working for both scalar values and arrays.
This class is the base that is inherited by all array expression types.
Template Parameters
Derived is the derived type, e.g., an array or an expression type.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizing_Plugins by defining the preprocessor symbol EIGEN_ARRAYBASE_PLUGIN.
See also
class MatrixBase, TopicClassHierarchy
Member Typedef Documentation
Base
template<typename Derived > typedef DenseBase<Derived> Eigen::ArrayBase< Derived >::Base
CoeffReturnType
template<typename Derived > typedef Base::CoeffReturnType Eigen::ArrayBase< Derived >::CoeffReturnType
ColwiseReturnType
template<typename Derived > typedef VectorwiseOp<Derived, Vertical> Eigen::DenseBase< Derived >::ColwiseReturnType inherited
ConstantReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,PlainObject> Eigen::ArrayBase< Derived >::ConstantReturnType
ConstColwiseReturnType
template<typename Derived > typedef const VectorwiseOp<const Derived, Vertical> Eigen::DenseBase< Derived >::ConstColwiseReturnType inherited
ConstReverseReturnType
template<typename Derived > typedef const Reverse<const Derived, BothDirections> Eigen::DenseBase< Derived >::ConstReverseReturnType inherited
ConstRowwiseReturnType
template<typename Derived > typedef const VectorwiseOp<const Derived, Horizontal> Eigen::DenseBase< Derived >::ConstRowwiseReturnType inherited
ConstTransposeReturnType
template<typename Derived > typedef internal::add_const<Transpose<constDerived>>::type Eigen::DenseBase< Derived >::ConstTransposeReturnType inherited
Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl
template<typename Derived > typedef ArrayBase Eigen::ArrayBase< Derived >::Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl
EigenvaluesReturnType
template<typename Derived > typedef Matrix<typename NumTraits<typename internal::traits<Derived>::Scalar>::Real, internal::traits<Derived>::ColsAtCompileTime, 1> Eigen::DenseBase< Derived >::EigenvaluesReturnType inherited
EvalReturnType
template<typename Derived > typedef internal::add_const_on_value_type<typenameinternal::eval<Derived>::type>::type Eigen::DenseBase< Derived >::EvalReturnType inherited
InnerIterator
template<typename Derived > typedef Eigen::InnerIterator<Derived> Eigen::DenseBase< Derived >::InnerIterator inherited
Inner iterator type to iterate over the coefficients of a row or column.
See also
class InnerIterator
PacketScalar
template<typename Derived > typedef internal::packet_traits<Scalar>::type Eigen::ArrayBase< Derived >::PacketScalar
PlainArray
template<typename Derived > typedef Array<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags&RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime > Eigen::DenseBase< Derived >::PlainArray inherited
The plain array type corresponding to this expression.
See also
PlainObject
PlainMatrix
template<typename Derived > typedef Matrix<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags&RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime > Eigen::DenseBase< Derived >::PlainMatrix inherited
The plain matrix type corresponding to this expression.
See also
PlainObject
PlainObject
template<typename Derived > typedef Base::PlainObject Eigen::ArrayBase< Derived >::PlainObject
RandomAccessLinSpacedReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::linspaced_op<Scalar,PacketScalar>,PlainObject> Eigen::DenseBase< Derived >::RandomAccessLinSpacedReturnType inherited
RandomReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_random_op<Scalar>,PlainObject> Eigen::DenseBase< Derived >::RandomReturnType inherited
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::ArrayBase< Derived >::RealScalar
ReverseReturnType
template<typename Derived > typedef Reverse<Derived, BothDirections> Eigen::DenseBase< Derived >::ReverseReturnType inherited
RowwiseReturnType
template<typename Derived > typedef VectorwiseOp<Derived, Horizontal> Eigen::DenseBase< Derived >::RowwiseReturnType inherited
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::ArrayBase< Derived >::Scalar
SequentialLinSpacedReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::linspaced_op<Scalar,PacketScalar>,PlainObject> Eigen::DenseBase< Derived >::SequentialLinSpacedReturnType inherited
StorageBaseType
template<typename Derived > typedef ArrayBase Eigen::ArrayBase< Derived >::StorageBaseType
The base class for a given storage type.
StorageIndex
template<typename Derived > typedef internal::traits<Derived>::StorageIndex Eigen::DenseBase< Derived >::StorageIndex inherited
The type used to store indices.
This typedef is relevant for types that store multiple indices such as PermutationMatrix or Transpositions, otherwise it defaults to Eigen::Index
See also
\blank TopicPreprocessorDirectives, Eigen::Index, SparseMatrixBase.
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::ArrayBase< Derived >::StorageKind
TransposeReturnType
template<typename Derived > typedef Transpose<Derived> Eigen::DenseBase< Derived >::TransposeReturnType inherited
value_type
template<typename Derived > typedef Scalar Eigen::DenseBase< Derived >::value_type inherited
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
This value is equal to the maximum possible number of rows that this expression might have. If this expression might have an arbitrarily high number of rows, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
RowsAtCompileTime, MaxColsAtCompileTime, MaxSizeAtCompileTime
MaxColsAtCompileTime
This value is equal to the maximum possible number of columns that this expression might have. If this expression might have an arbitrarily high number of columns, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
ColsAtCompileTime, MaxRowsAtCompileTime, MaxSizeAtCompileTime
MaxSizeAtCompileTime
This value is equal to the maximum possible number of coefficients that this expression might have. If this expression might have an arbitrarily high number of coefficients, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
SizeAtCompileTime, MaxRowsAtCompileTime, MaxColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
True if this expression has row-major storage order.
InnerSizeAtCompileTime
InnerStrideAtCompileTime
OuterStrideAtCompileTime
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::MaxRowsAtCompileTime,
                                                      internal::traits<Derived>::MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime == 1
                           || internal::traits<Derived>::MaxColsAtCompileTime == 1,
      Flags = internal::traits<Derived>::Flags,
      IsRowMajor = int(Flags) & RowMajorBit,
      InnerSizeAtCompileTime = int(IsVectorAtCompileTime) ? int(SizeAtCompileTime)
                             : int(IsRowMajor) ? int(ColsAtCompileTime) : int(RowsAtCompileTime),
      InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret,
      OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
    };
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
IsPlainObjectBase
{ IsPlainObjectBase = 0 };
Constructor & Destructor Documentation
ArrayBase() [1/4]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::ArrayBase< Derived >::ArrayBase () inline protected
: Base() {}
ArrayBase() [2/4]
template<typename Derived > Eigen::ArrayBase< Derived >::ArrayBase (Index) explicit private
ArrayBase() [3/4]
template<typename Derived > Eigen::ArrayBase< Derived >::ArrayBase (Index , Index) private
ArrayBase() [4/4]
template<typename Derived > template<typename OtherDerived > Eigen::ArrayBase< Derived >::ArrayBase (const ArrayBase< OtherDerived > &) explicit private
Member Function Documentation
all()
template<typename Derived > bool Eigen::DenseBase< Derived >::all inline inherited
Returns
true if all coefficients are true
Example:
Output:
See also
any(), Cwise::operator<()
{
  typedef internal::evaluator<Derived> Evaluator;
  enum {
    unroll = SizeAtCompileTime != Dynamic
          && SizeAtCompileTime * (Evaluator::CoeffReadCost + NumTraits<Scalar>::AddCost) <= EIGEN_UNROLLING_LIMIT
  };
  Evaluator evaluator(derived());
  if(unroll)
    return internal::all_unroller<Evaluator, unroll ? int(SizeAtCompileTime) : Dynamic>::run(evaluator);
  else
  {
    for(Index j = 0; j < cols(); ++j)
      for(Index i = 0; i < rows(); ++i)
        if (!evaluator.coeff(i, j)) return false;
    return true;
  }
}
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
allFinite()
template<typename Derived > bool Eigen::DenseBase< Derived >::allFinite inline inherited
Returns
true if *this contains only finite numbers, i.e., no NaN and no +/-INF values.
See also
hasNaN()
{
#if EIGEN_COMP_MSVC || (defined __FAST_MATH__)
  return derived().array().isFinite().all();
#else
  return !((derived()-derived()).hasNaN());
#endif
}
any()
template<typename Derived > bool Eigen::DenseBase< Derived >::any inline inherited
Returns
true if at least one coefficient is true
See also
all()
{
  typedef internal::evaluator<Derived> Evaluator;
  enum {
    unroll = SizeAtCompileTime != Dynamic
          && SizeAtCompileTime * (Evaluator::CoeffReadCost + NumTraits<Scalar>::AddCost) <= EIGEN_UNROLLING_LIMIT
  };
  Evaluator evaluator(derived());
  if(unroll)
    return internal::any_unroller<Evaluator, unroll ? int(SizeAtCompileTime) : Dynamic>::run(evaluator);
  else
  {
    for(Index j = 0; j < cols(); ++j)
      for(Index i = 0; i < rows(); ++i)
        if (evaluator.coeff(i, j)) return true;
    return false;
  }
}
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
array() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC ArrayBase< Derived > & Eigen::ArrayBase< Derived >::array () inline
{ return *this; }
array() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const ArrayBase< Derived > & Eigen::ArrayBase< Derived >::array () const inline
{ return *this; }
colwise() [1/2]
template<typename Derived > DenseBase< Derived >::ColwiseReturnType Eigen::DenseBase< Derived >::colwise inline inherited
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
  return ColwiseReturnType(derived());
}
colwise() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ConstColwiseReturnType Eigen::DenseBase< Derived >::colwise () const inline inherited
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
      return ConstColwiseReturnType(derived());
    }
Referenced by igl::bounding_box(), igl::copyleft::offset_surface(), and Eigen::umeyama().
Constant() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (const Scalar & value) static inherited
Returns
an expression of a constant matrix of value value
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
  return DenseBase<Derived>::NullaryExpr(RowsAtCompileTime, ColsAtCompileTime, internal::scalar_constant_op<Scalar>(value));
}
References EIGEN_STATIC_ASSERT_FIXED_SIZE, and Eigen::DenseBase< Derived >::NullaryExpr().
Constant() [2/3]
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index rows, Index cols, const Scalar & value) static inherited
Returns
an expression of a constant matrix of value value
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  return DenseBase<Derived>::NullaryExpr(rows, cols, internal::scalar_constant_op<Scalar>(value));
}
References Eigen::DenseBase< Derived >::NullaryExpr().
Constant() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index size, const Scalar & value) static inherited
Returns
an expression of a constant matrix of value value
The parameter size is the size of the returned vector. Must be compatible with this DenseBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  return DenseBase<Derived>::NullaryExpr(size, internal::scalar_constant_op<Scalar>(value));
}
References Eigen::DenseBase< Derived >::NullaryExpr().
count()
template<typename Derived > Eigen::Index Eigen::DenseBase< Derived >::count inline inherited
Returns
the number of coefficients which evaluate to true
See also
all(), any()
{
  return derived().template cast<bool>().template cast<Index>().sum();
}
eval()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType Eigen::DenseBase< Derived >::eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
Warning
Be carefull with eval() and the auto C++ keyword, as detailed in this page .
    {
      // Even though MSVC does not honor strong inlining when the return type
      // is a dynamic matrix, we desperately need strong inlining for fixed
      // size types on MSVC.
      return typename internal::eval<Derived>::type(derived());
    }
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::evalTo (Dest &) const inline inherited
    {
      EIGEN_STATIC_ASSERT((internal::is_same<Dest,void>::value),THE_EVAL_EVALTO_FUNCTION_SHOULD_NEVER_BE_CALLED_FOR_DENSE_OBJECTS);
    }
References EIGEN_STATIC_ASSERT.
fill()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DenseBase< Derived >::fill (const Scalar & val) inherited
Alias for setConstant(): sets all coefficients in this expression to val.
See also
setConstant(), Constant(), class CwiseNullaryOp
{
  setConstant(val);
}
flagged()
template<typename Derived > template<unsigned int Added, unsigned int Removed> EIGEN_DEPRECATED const Derived & Eigen::DenseBase< Derived >::flagged () const inline inherited
    { return derived(); }
forceAlignedAccess() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > Eigen::DenseBase< Derived >::forceAlignedAccess () inline inherited
forceAlignedAccess() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > Eigen::DenseBase< Derived >::forceAlignedAccess () const inline inherited
forceAlignedAccessIf() [1/2]
template<typename Derived > template<bool Enable> EIGEN_DEVICE_FUNC internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type Eigen::DenseBase< Derived >::forceAlignedAccessIf () inline inherited
forceAlignedAccessIf() [2/2]
template<typename Derived > template<bool Enable> EIGEN_DEVICE_FUNC const internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type Eigen::DenseBase< Derived >::forceAlignedAccessIf () const inline inherited
format()
template<typename Derived > const WithFormat< Derived > Eigen::DenseBase< Derived >::format (const IOFormat & fmt) const inline inherited
Returns
a WithFormat proxy object allowing to print a matrix the with given format fmt.
See class IOFormat for some examples.
See also
class IOFormat, class WithFormat
    {
      return WithFormat<Derived>(derived(), fmt);
    }
Referenced by igl::matlab_format(), and igl::writeOBJ().
hasNaN()
template<typename Derived > bool Eigen::DenseBase< Derived >::hasNaN inline inherited
Returns
true is *this contains at least one Not A Number (NaN).
See also
allFinite()
{
#if EIGEN_COMP_MSVC || (defined __FAST_MATH__)
  return derived().array().isNaN().any();
#else
  return !((derived().array()==derived().array()).all());
#endif
}
innerSize()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::innerSize () const inline inherited
Returns
the inner size.
Note
For a vector, this is just the size. For a matrix (non-vector), this is the minor dimension with respect to the storage order, i.e., the number of rows for a column-major matrix, and the number of columns for a row-major matrix.
    {
      return IsVectorAtCompileTime ? this->size()
           : int(IsRowMajor) ? this->cols() : this->rows();
    }
References Eigen::DenseBase< Derived >::IsRowMajor, and Eigen::DenseBase< Derived >::IsVectorAtCompileTime.
isApprox() [1/2]
template<typename Derived > template<typename OtherDerived > bool Eigen::DenseBase< Derived >::isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec) const inherited
Returns
true if *this is approximately equal to other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. Two vectors and are considered to be approximately equal within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm (aka Frobenius norm L2 norm).
Because of the multiplicativeness of this comparison, one can't use this function to check whether *this is approximately equal to the zero matrix or vector. Indeed, isApprox(zero) returns false unless *this itself is exactly the zero matrix or vector. If you want to test whether *this is zero, use internal::isMuchSmallerThan(const RealScalar&, RealScalar) instead.
See also
internal::isMuchSmallerThan(const RealScalar&, RealScalar) const
{
  return internal::isApprox_selector<Derived, OtherDerived>::run(derived(), other.derived(), prec);
}
References Eigen::internal::isApprox_selector< Derived, OtherDerived, is_integer >::run().
isApprox() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const inherited
isApproxToConstant()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApproxToConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if all coefficients in this matrix are approximately equal to val, to within precision prec
{
  typename internal::nested_eval<Derived,1>::type self(derived());
  for(Index j = 0; j < cols(); ++j)
    for(Index i = 0; i < rows(); ++i)
      if(!internal::isApprox(self.coeff(i, j), val, prec))
        return false;
  return true;
}
References Eigen::internal::isApprox().
isConstant()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
This is just an alias for isApproxToConstant().
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
{
  return isApproxToConstant(val, prec);
}
isMuchSmallerThan() [1/4]
template<typename Derived > template<typename OtherDerived > bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec) const inherited
Returns
true if the norm of *this is much smaller than the norm of other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than a vector within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm.
See also
isApprox(), isMuchSmallerThan(const RealScalar&, RealScalar) const
{
  return internal::isMuchSmallerThan_object_selector<Derived, OtherDerived>::run(derived(), other.derived(), prec);
}
References Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >::run().
isMuchSmallerThan() [2/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const inherited
isMuchSmallerThan() [3/4]
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const RealScalar & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const inherited
isMuchSmallerThan() [4/4]
template<typename Derived > template<typename Derived > bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const typename NumTraits< Scalar >::Real & other, const RealScalar & prec) const inherited
Returns
true if the norm of *this is much smaller than other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm. For this reason, the value of the reference scalar other should come from the Hilbert-Schmidt norm of a reference matrix of same dimensions.
See also
isApprox(), isMuchSmallerThan(const DenseBase<OtherDerived>&, RealScalar) const
{
  return internal::isMuchSmallerThan_scalar_selector<Derived>::run(derived(), other, prec);
}
References Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >::run().
isOnes()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isOnes (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to the matrix where all coefficients are equal to 1, within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Ones()
{
  return isApproxToConstant(Scalar(1), prec);
}
isZero()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isZero (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to the zero matrix, within the precision given by prec.
Example:
Output:
See also
class CwiseNullaryOp, Zero()
{
  typename internal::nested_eval<Derived,1>::type self(derived());
  for(Index j = 0; j < cols(); ++j)
    for(Index i = 0; i < rows(); ++i)
      if(!internal::isMuchSmallerThan(self.coeff(i, j), static_cast<Scalar>(1), prec))
        return false;
  return true;
}
References Eigen::internal::isMuchSmallerThan().
lazyAssign() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
lazyAssign() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
{
  enum{
    SameType = internal::is_same<typename Derived::Scalar,typename OtherDerived::Scalar>::value
  };
  EIGEN_STATIC_ASSERT_LVALUE(Derived)
  EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT(SameType,YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(rows() == other.rows() && cols() == other.cols());
  internal::call_assignment_no_alias(derived(),other.derived());
  return derived();
}
LinSpaced() [1/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (const Scalar & low, const Scalar & high) static inherited
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
Example:
Output:
For integer scalar types, an even spacing is possible if and only if the length of the range, i.e., high-low is a scalar multiple of size-1, or if size is a scalar multiple of the number of values high-low+1 (meaning each value can be repeated the same number of time). If one of these two considions is not satisfied, then high is lowered to the largest value satisfying one of this constraint. Here are some examples:
Example:
Output:
See also
setLinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
  return DenseBase<Derived>::NullaryExpr(Derived::SizeAtCompileTime, internal::linspaced_op<Scalar,PacketScalar>(low,high,Derived::SizeAtCompileTime));
}
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
LinSpaced() [2/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Index size, const Scalar & low, const Scalar & high) static inherited
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
Example:
Output:
For integer scalar types, an even spacing is possible if and only if the length of the range, i.e., high-low is a scalar multiple of size-1, or if size is a scalar multiple of the number of values high-low+1 (meaning each value can be repeated the same number of time). If one of these two considions is not satisfied, then high is lowered to the largest value satisfying one of this constraint. Here are some examples:
Example:
Output:
See also
setLinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return DenseBase<Derived>::NullaryExpr(size, internal::linspaced_op<Scalar,PacketScalar>(low,high,size));
}
LinSpaced() [3/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , const Scalar & low, const Scalar & high) static inherited
See also
LinSpaced(Scalar,Scalar)
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
  return DenseBase<Derived>::NullaryExpr(Derived::SizeAtCompileTime, internal::linspaced_op<Scalar,PacketScalar>(low,high,Derived::SizeAtCompileTime));
}
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
LinSpaced() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , Index size, const Scalar & low, const Scalar & high) static inherited
See also
LinSpaced(Index,Scalar,Scalar), setLinSpaced(Index,const Scalar&,const Scalar&)
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return DenseBase<Derived>::NullaryExpr(size, internal::linspaced_op<Scalar,PacketScalar>(low,high,size));
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
lpNorm()
template<typename Derived > template<int p> RealScalar Eigen::DenseBase< Derived >::lpNorm () const inherited
matrix() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC MatrixWrapper< Derived > Eigen::ArrayBase< Derived >::matrix () inline
Returns
an Matrix expression of this array
See also
MatrixBase::array()
{ return MatrixWrapper<Derived>(derived()); }
matrix() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const MatrixWrapper< const Derived > Eigen::ArrayBase< Derived >::matrix () const inline
{ return MatrixWrapper<const Derived>(derived()); }
maxCoeff() [1/3]
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff inherited
Returns
the maximum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
{
  return derived().redux(Eigen::internal::scalar_max_op<Scalar,Scalar>());
}
Referenced by igl::copyleft::cgal::half_space_box(), igl::isolines(), igl::min_quad_with_fixed_precompute(), igl::octree(), Eigen::internal::lpNorm_selector< Derived, Infinity >::run(), and igl::slice().
maxCoeff() [2/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * index) const inherited
Returns
the maximum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  internal::max_coeff_visitor<Derived> maxVisitor;
  this->visit(maxVisitor);
  *index = (RowsAtCompileTime==1) ? maxVisitor.col : maxVisitor.row;
  return maxVisitor.res;
}
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
maxCoeff() [3/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * rowId, IndexType * colId) const inherited
Returns
the maximum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::maxCoeff()
{
  internal::max_coeff_visitor<Derived> maxVisitor;
  this->visit(maxVisitor);
  *rowPtr = maxVisitor.row;
  if (colPtr) *colPtr = maxVisitor.col;
  return maxVisitor.res;
}
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
mean()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::mean inherited
Returns
the mean of all coefficients of *this
See also
trace(), prod(), sum()
{
#ifdef __INTEL_COMPILER
  #pragma warning push
  #pragma warning ( disable : 2259 )
#endif
  return Scalar(derived().redux(Eigen::internal::scalar_sum_op<Scalar,Scalar>())) / Scalar(this->size());
#ifdef __INTEL_COMPILER
  #pragma warning pop
#endif
}
minCoeff() [1/3]
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff inherited
Returns
the minimum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
{
  return derived().redux(Eigen::internal::scalar_min_op<Scalar,Scalar>());
}
Referenced by igl::copyleft::cgal::half_space_box(), igl::isolines(), igl::min_quad_with_fixed_precompute(), igl::octree(), and igl::slice().
minCoeff() [2/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * index) const inherited
Returns
the minimum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::minCoeff()
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  internal::min_coeff_visitor<Derived> minVisitor;
  this->visit(minVisitor);
  *index = IndexType((RowsAtCompileTime==1) ? minVisitor.col : minVisitor.row);
  return minVisitor.res;
}
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
minCoeff() [3/3]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * rowId, IndexType * colId) const inherited
Returns
the minimum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(Index*), DenseBase::maxCoeff(Index*,Index*), DenseBase::visit(), DenseBase::minCoeff()
{
  internal::min_coeff_visitor<Derived> minVisitor;
  this->visit(minVisitor);
  *rowId = minVisitor.row;
  if (colId) *colId = minVisitor.col;
  return minVisitor.res;
}
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
nestByValue()
template<typename Derived > const NestByValue< Derived > Eigen::DenseBase< Derived >::nestByValue inline inherited
Returns
an expression of the temporary version of *this.
{
  return NestByValue<Derived>(derived());
}
nonZeros()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::nonZeros () const inline inherited
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
{ return size(); }
NullaryExpr() [1/6]
template<typename Derived > template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func) inherited
Returns
an expression of a matrix defined by a custom functor func
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  return CwiseNullaryOp<CustomNullaryOp, PlainObject>(RowsAtCompileTime, ColsAtCompileTime, func);
}
NullaryExpr() [2/6]
template<typename Derived > template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func) static inherited
NullaryExpr() [3/6]
template<typename Derived > template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) inherited
Returns
an expression of a matrix defined by a custom functor func
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
  return CwiseNullaryOp<CustomNullaryOp, PlainObject>(rows, cols, func);
}
NullaryExpr() [4/6]
template<typename Derived > template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) static inherited
Referenced by Eigen::DenseBase< Derived >::Constant(), Eigen::DenseBase< Derived >::Constant(), Eigen::DenseBase< Derived >::Constant(), Eigen::MatrixBase< Derived >::Identity(), Eigen::MatrixBase< Derived >::Identity(), Eigen::DenseBase< Derived >::LinSpaced(), Eigen::DenseBase< Derived >::LinSpaced(), and Eigen::DenseBase< Derived >::LinSpaced().
NullaryExpr() [5/6]
template<typename Derived > template<typename CustomNullaryOp > EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func) inherited
Returns
an expression of a matrix defined by a custom functor func
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
Here is an example with C++11 random generators:
Output:
See also
class CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  if(RowsAtCompileTime == 1) return CwiseNullaryOp<CustomNullaryOp, PlainObject>(1, size, func);
  else return CwiseNullaryOp<CustomNullaryOp, PlainObject>(size, 1, func);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
NullaryExpr() [6/6]
template<typename Derived > template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func) static inherited
Ones() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones static inherited
Returns
an expression of a fixed-size matrix or vector where all coefficients equal one.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See also
Ones(Index), Ones(Index,Index), isOnes(), class Ones
{
  return Constant(Scalar(1));
}
Ones() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index rows, Index cols) static inherited
Returns
an expression of a matrix where all coefficients equal one.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Ones() should be used instead.
Example:
Output:
See also
Ones(), Ones(Index), isOnes(), class Ones
{
  return Constant(rows, cols, Scalar(1));
}
Ones() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index newSize) static inherited
Returns
an expression of a vector where all coefficients equal one.
The parameter newSize is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Ones() should be used instead.
Example:
Output:
See also
Ones(), Ones(Index,Index), isOnes(), class Ones
{
  return Constant(newSize, Scalar(1));
}
operator*=() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator*= (const ArrayBase< OtherDerived > & other)
replaces *this by *this * other coefficient wise.
Returns
a reference to *this
{
  call_assignment(derived(), other.derived(), internal::mul_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator*=() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator*= (const Scalar & other)
{
  internal::call_assignment(this->derived(), PlainObject::Constant(rows(),cols(),other), internal::mul_assign_op<Scalar,Scalar>());
  return derived();
}
operator+=() [1/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator+= (const ArrayBase< OtherDerived > & other)
replaces *this by *this + other.
Returns
a reference to *this
{
  call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [2/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator+= (const EigenBase< OtherDerived > & other)
{
  call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator+=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::ArrayBase< Derived >::operator+= (const MatrixBase< OtherDerived > &) inline protected
    {EIGEN_STATIC_ASSERT(std::ptrdiff_t(sizeof(typename OtherDerived::Scalar))==-1,YOU_CANNOT_MIX_ARRAYS_AND_MATRICES); return *this;}
References EIGEN_STATIC_ASSERT.
operator+=() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator+= (const Scalar & scalar)
{
  internal::call_assignment(this->derived(), PlainObject::Constant(rows(),cols(),other), internal::add_assign_op<Scalar,Scalar>());
  return derived();
}
References Eigen::internal::call_assignment().
operator-=() [1/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator-= (const ArrayBase< OtherDerived > & other)
replaces *this by *this - other.
Returns
a reference to *this
{
  call_assignment(derived(), other.derived(), internal::sub_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [2/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator-= (const EigenBase< OtherDerived > & other)
{
  call_assignment(derived(), other.derived(), internal::sub_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator-=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::ArrayBase< Derived >::operator-= (const MatrixBase< OtherDerived > &) inline protected
    {EIGEN_STATIC_ASSERT(std::ptrdiff_t(sizeof(typename OtherDerived::Scalar))==-1,YOU_CANNOT_MIX_ARRAYS_AND_MATRICES); return *this;}
References EIGEN_STATIC_ASSERT.
operator-=() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator-= (const Scalar & scalar)
{
  internal::call_assignment(this->derived(), PlainObject::Constant(rows(),cols(),other), internal::sub_assign_op<Scalar,Scalar>());
  return derived();
}
References Eigen::internal::call_assignment().
operator/=() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator/= (const ArrayBase< OtherDerived > & other)
replaces *this by *this / other coefficient wise.
Returns
a reference to *this
{
  call_assignment(derived(), other.derived(), internal::div_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
operator/=() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator/= (const Scalar & other)
{
  internal::call_assignment(this->derived(), PlainObject::Constant(rows(),cols(),other), internal::div_assign_op<Scalar,Scalar>());
  return derived();
}
operator<<() [1/3]
template<typename Derived > template<typename OtherDerived > CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const DenseBase< OtherDerived > & other) inline inherited
See also
operator<<(const Scalar&)
{
  return CommaInitializer<Derived>(*static_cast<Derived *>(this), other);
}
operator<<() [2/3]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const DenseBase< OtherDerived > & other) inherited
operator<<() [3/3]
template<typename Derived > CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const Scalar & s) inline inherited
Convenient operator to set the coefficients of a matrix.
The coefficients must be provided in a row major order and exactly match the size of the matrix. Otherwise an assertion is raised.
Example:
Output:
Note
According the c++ standard, the argument expressions of this comma initializer are evaluated in arbitrary order.
See also
CommaInitializer::finished(), class CommaInitializer
{
  return CommaInitializer<Derived>(*static_cast<Derived*>(this), s);
}
operator=() [1/7]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator= (const ArrayBase< Derived > & other) inline
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
    {
      internal::call_assignment(derived(), other.derived());
      return derived();
    }
References Eigen::internal::call_assignment().
operator=() [2/7]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (const DenseBase & other)
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
{
  internal::call_assignment(derived(), other.derived());
  return derived();
}
operator=() [3/7]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (const DenseBase< OtherDerived > & other)
Copies other into *this.
Returns
a reference to *this.
{
  internal::call_assignment(derived(), other.derived());
  return derived();
}
operator=() [4/7]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
Copies the generic expression other into *this.
The expression must provide a (templated) evalTo(Derived& dst) const function which does the actual job. In practice, this allows any user to write its own special matrix without having to modify MatrixBase
Returns
a reference to *this.
{
  call_assignment(derived(), other.derived());
  return derived();
}
operator=() [5/7]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator= (const ReturnByValue< OtherDerived > & func)
operator=() [6/7]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::DenseBase< Derived >::operator= (const ReturnByValue< OtherDerived > & other)
{
  other.evalTo(derived());
  return derived();
}
operator=() [7/7]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator= (const Scalar & value) inline
Set all the entries to value.
See also
DenseBase::setConstant(), DenseBase::fill()
    { Base::setConstant(value); return derived(); }
References Eigen::DenseBase< Derived >::setConstant(), and Eigen::DenseBase< Derived >::value().
outerSize()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::outerSize () const inline inherited
Returns
the outer size.
Note
For a vector, this returns just 1. For a matrix (non-vector), this is the major dimension with respect to the storage order, i.e., the number of columns for a column-major matrix, and the number of rows for a row-major matrix.
    {
      return IsVectorAtCompileTime ? 1
           : int(IsRowMajor) ? this->rows() : this->cols();
    }
References Eigen::DenseBase< Derived >::IsRowMajor, and Eigen::DenseBase< Derived >::IsVectorAtCompileTime.
prod()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::prod inherited
Returns
the product of all coefficients of *this
Example:
Output:
See also
sum(), mean(), trace()
{
  if(SizeAtCompileTime==0 || (SizeAtCompileTime==Dynamic && size()==0))
    return Scalar(1);
  return derived().redux(Eigen::internal::scalar_product_op<Scalar>());
}
References Eigen::Dynamic.
Random() [1/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random inline static inherited
Returns
a fixed-size random matrix or vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
\not_reentrant
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random(Index)
{
  return NullaryExpr(RowsAtCompileTime, ColsAtCompileTime, internal::scalar_random_op<Scalar>());
}
Random() [2/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index rows, Index cols) inline static inherited
Returns
a random matrix expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
\not_reentrant
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See DenseBase::NullaryExpr(Index, const CustomNullaryOp&) for an example using C++11 random generators.
See also
DenseBase::setRandom(), DenseBase::Random(Index), DenseBase::Random()
{
  return NullaryExpr(rows, cols, internal::scalar_random_op<Scalar>());
}
Random() [3/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index size) inline static inherited
Returns
a random vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors \not_reentrant
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary vector whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random()
{
  return NullaryExpr(size, internal::scalar_random_op<Scalar>());
}
redux() [1/2]
template<typename Derived > template<typename BinaryOp > EIGEN_DEVICE_FUNC Scalar Eigen::DenseBase< Derived >::redux (const BinaryOp & func) const inherited
Referenced by Eigen::internal::member_redux< BinaryOp, Scalar >::operator()().
redux() [2/2]
template<typename Derived > template<typename Func > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::redux (const Func & func) const inherited
Returns
the result of a full redux operation on the whole matrix or vector using func
The template parameter BinaryOp is the type of the functor func which must be an associative operator. Both current C++98 and C++11 functor styles are handled.
See also
DenseBase::sum(), DenseBase::minCoeff(), DenseBase::maxCoeff(), MatrixBase::colwise(), MatrixBase::rowwise()
{
  eigen_assert(this->rows()>0 && this->cols()>0 && "you are using an empty matrix");
  typedef typename internal::redux_evaluator<Derived> ThisEvaluator;
  ThisEvaluator thisEval(derived());
  return internal::redux_impl<Func, ThisEvaluator>::run(thisEval, func);
}
References eigen_assert.
replicate() [1/3]
template<typename Derived > template<int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > Eigen::DenseBase< Derived >::replicate () const inherited
Referenced by igl::min_quad_with_fixed_solve().
replicate() [2/3]
template<typename Derived > template<int RowFactor, int ColFactor> const Replicate< Derived, RowFactor, ColFactor > Eigen::DenseBase< Derived >::replicate () const inherited
Returns
an expression of the replication of *this
Example:
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate(Index,Index), class Replicate
{
  return Replicate<Derived,RowFactor,ColFactor>(derived());
}
replicate() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > Eigen::DenseBase< Derived >::replicate (Index rowFactor, Index colFactor) const inline inherited
Returns
an expression of the replication of *this
Example:
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate<int,int>(), class Replicate
    {
      return Replicate<Derived, Dynamic, Dynamic>(derived(), rowFactor, colFactor);
    }
resize() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::resize (Index newSize) inline inherited
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
    {
      EIGEN_ONLY_USED_FOR_DEBUG(newSize);
      eigen_assert(newSize == this->size()
                && "DenseBase::resize() does not actually allow to resize.");
    }
References eigen_assert, and EIGEN_ONLY_USED_FOR_DEBUG.
Referenced by Eigen::TriangularBase< Derived >::evalToLazy(), igl::find(), and igl::slice_tets().
resize() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::resize (Index rows, Index cols) inline inherited
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
    {
      EIGEN_ONLY_USED_FOR_DEBUG(rows);
      EIGEN_ONLY_USED_FOR_DEBUG(cols);
      eigen_assert(rows == this->rows() && cols == this->cols()
                && "DenseBase::resize() does not actually allow to resize.");
    }
References eigen_assert, and EIGEN_ONLY_USED_FOR_DEBUG.
reverse() [1/2]
template<typename Derived > DenseBase< Derived >::ReverseReturnType Eigen::DenseBase< Derived >::reverse inline inherited
Returns
an expression of the reverse of *this.
Example:
Output:
{
  return ReverseReturnType(derived());
}
reverse() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ConstReverseReturnType Eigen::DenseBase< Derived >::reverse () const inline inherited
This is the const version of reverse().
    {
      return ConstReverseReturnType(derived());
    }
reverseInPlace()
template<typename Derived > void Eigen::DenseBase< Derived >::reverseInPlace inline inherited
This is the "in place" version of reverse: it reverses *this.
In most cases it is probably better to simply use the reversed expression of a matrix. However, when reversing the matrix data itself is really needed, then this "in-place" version is probably the right choice because it provides the following additional benefits:
less error prone: doing the same operation with .reverse() requires special care:
m = m.reverse().eval();
this API enables reverse operations without the need for a temporary
it allows future optimizations (cache friendliness, etc.)
See also
VectorwiseOp::reverseInPlace(), reverse()
{
  if(cols()>rows())
  {
    Index half = cols()/2;
    leftCols(half).swap(rightCols(half).reverse());
    if((cols()%2)==1)
    {
      Index half2 = rows()/2;
      col(half).head(half2).swap(col(half).tail(half2).reverse());
    }
  }
  else
  {
    Index half = rows()/2;
    topRows(half).swap(bottomRows(half).reverse());
    if((rows()%2)==1)
    {
      Index half2 = cols()/2;
      row(half).head(half2).swap(row(half).tail(half2).reverse());
    }
  }
}
References bottomRows(), col(), leftCols(), rightCols(), row(), tail(), and topRows().
rowwise() [1/2]
template<typename Derived > DenseBase< Derived >::RowwiseReturnType Eigen::DenseBase< Derived >::rowwise inline inherited
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
  return RowwiseReturnType(derived());
}
rowwise() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ConstRowwiseReturnType Eigen::DenseBase< Derived >::rowwise () const inline inherited
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
      return ConstRowwiseReturnType(derived());
    }
Referenced by igl::normalize_row_sums(), and Eigen::umeyama().
select() [1/3]
template<typename Derived > template<typename ThenDerived , typename ElseDerived > const Select< Derived, ThenDerived, ElseDerived > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline inherited
Returns
a matrix where each coefficient (i,j) is equal to thenMatrix(i,j) if *this(i,j), and elseMatrix(i,j) otherwise.
Example:
Output:
See also
class Select
{
  return Select<Derived,ThenDerived,ElseDerived>(derived(), thenMatrix.derived(), elseMatrix.derived());
}
select() [2/3]
template<typename Derived > template<typename ThenDerived > const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const typename ThenDerived::Scalar & elseScalar) const inline inherited
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the else expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
{
  return Select<Derived,ThenDerived,typename ThenDerived::ConstantReturnType>(
    derived(), thenMatrix.derived(), ThenDerived::Constant(rows(),cols(),elseScalar));
}
select() [3/3]
template<typename Derived > template<typename ElseDerived > const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > Eigen::DenseBase< Derived >::select (const typename ElseDerived::Scalar & thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline inherited
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the then expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
{
  return Select<Derived,typename ElseDerived::ConstantReturnType,ElseDerived>(
    derived(), ElseDerived::Constant(rows(),cols(),thenScalar), elseMatrix.derived());
}
setConstant()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setConstant (const Scalar & val) inherited
Sets all coefficients in this expression to value val.
See also
fill(), setConstant(Index,const Scalar&), setConstant(Index,Index,const Scalar&), setZero(), setOnes(), Constant(), class CwiseNullaryOp, setZero(), setOnes()
{
  return derived() = Constant(rows(), cols(), val);
}
Referenced by Eigen::ArrayBase< Derived >::operator=().
setLinSpaced() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (const Scalar & low, const Scalar & high) inherited
Sets a linearly spaced vector.
The function fills *this with equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), setLinSpaced(Index, const Scalar&, const Scalar&), CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return setLinSpaced(size(), low, high);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
setLinSpaced() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (Index newSize, const Scalar & low, const Scalar & high) inherited
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
Example:
Output:
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return derived() = Derived::NullaryExpr(newSize, internal::linspaced_op<Scalar,PacketScalar>(low,high,newSize));
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
setOnes()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setOnes inherited
Sets all coefficients in this expression to one.
Example:
Output:
See also
class CwiseNullaryOp, Ones()
{
  return setConstant(Scalar(1));
}
setRandom()
template<typename Derived > Derived & Eigen::DenseBase< Derived >::setRandom inline inherited
Sets all coefficients in this expression to random values.
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
\not_reentrant
Example:
Output:
See also
class CwiseNullaryOp, setRandom(Index), setRandom(Index,Index)
{
  return *this = Random(rows(), cols());
}
setZero()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setZero inherited
Sets all coefficients in this expression to zero.
Example:
Output:
See also
class CwiseNullaryOp, Zero()
{
  return setConstant(Scalar(0));
}
Referenced by Eigen::SPQR< _MatrixType >::_solve_impl(), Eigen::PermutationBase< Derived >::evalTo(), and Eigen::InverseImpl< PermutationType, PermutationStorage >::evalTo().
sum()
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::sum inherited
Returns
the sum of all coefficients of *this
If *this is empty, then the value 0 is returned.
See also
trace(), prod(), mean()
{
  if(SizeAtCompileTime==0 || (SizeAtCompileTime==Dynamic && size()==0))
    return Scalar(0);
  return derived().redux(Eigen::internal::scalar_sum_op<Scalar,Scalar>());
}
References Eigen::Dynamic.
Referenced by igl::normalize_row_sums(), and Eigen::internal::lpNorm_selector< Derived, 1 >::run().
swap() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::swap (const DenseBase< OtherDerived > & other) inline inherited
swaps *this with the expression other.
    {
      EIGEN_STATIC_ASSERT(!OtherDerived::IsPlainObjectBase,THIS_EXPRESSION_IS_NOT_A_LVALUE__IT_IS_READ_ONLY);
      eigen_assert(rows()==other.rows() && cols()==other.cols());
      call_assignment(derived(), other.const_cast_derived(), internal::swap_assign_op<Scalar>());
    }
References eigen_assert, and EIGEN_STATIC_ASSERT.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run(), and Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
swap() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::swap (PlainObjectBase< OtherDerived > & other) inline inherited
swaps *this with the matrix or array other.
    {
      eigen_assert(rows()==other.rows() && cols()==other.cols());
      call_assignment(derived(), other.derived(), internal::swap_assign_op<Scalar>());
    }
References Eigen::PlainObjectBase< Derived >::cols(), eigen_assert, and Eigen::PlainObjectBase< Derived >::rows().
trace()
template<typename Derived > EIGEN_DEVICE_FUNC Scalar Eigen::DenseBase< Derived >::trace () const inherited
transpose() [1/2]
template<typename Derived > Transpose< Derived > Eigen::DenseBase< Derived >::transpose inline inherited
Returns
an expression of the transpose of *this.
Example:
Output:
Warning
If you want to replace a matrix by its own transpose, do NOT do this:
m = m.transpose(); // bug!!! caused by aliasing effect
Instead, use the transposeInPlace() method:
m.transposeInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.transpose().eval();
See also
transposeInPlace(), adjoint()
{
  return TransposeReturnType(derived());
}
Referenced by igl::AABB< DerivedV, DIM >::find(), igl::AABB< DerivedV, DIM >::init(), igl::project(), igl::signed_distance_winding_number(), and igl::unproject().
transpose() [2/2]
template<typename Derived > DenseBase< Derived >::ConstTransposeReturnType Eigen::DenseBase< Derived >::transpose inline inherited
This is the const version of transpose().
Make sure you read the warning for transpose() !
See also
transposeInPlace(), adjoint()
{
  return ConstTransposeReturnType(derived());
}
transposeInPlace()
template<typename Derived > void Eigen::DenseBase< Derived >::transposeInPlace inline inherited
This is the "in place" version of transpose(): it replaces *this by its own transpose. Thus, doing
m.transposeInPlace();
has the same effect on m as doing
m = m.transpose().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own transpose. If you just need the transpose of a matrix, use transpose().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See also
transpose(), adjoint(), adjointInPlace()
{
  eigen_assert((rows() == cols() || (RowsAtCompileTime == Dynamic && ColsAtCompileTime == Dynamic))
               && "transposeInPlace() called on a non-square non-resizable matrix");
  internal::inplace_transpose_selector<Derived>::run(derived());
}
References Eigen::Dynamic, and eigen_assert.
value()
template<typename Derived > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::DenseBase< Derived >::value () const inline inherited
Returns
the unique coefficient of a 1x1 expression
    {
      EIGEN_STATIC_ASSERT_SIZE_1x1(Derived)
      eigen_assert(this->rows() == 1 && this->cols() == 1);
      return derived().coeff(0,0);
    }
References eigen_assert, and EIGEN_STATIC_ASSERT_SIZE_1x1.
Referenced by igl::find(), and Eigen::ArrayBase< Derived >::operator=().
visit()
template<typename Derived > template<typename Visitor > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::visit (Visitor & visitor) const inherited
Applies the visitor visitor to the whole coefficients of the matrix or vector.
The template parameter Visitor is the type of the visitor and provides the following interface:
struct MyVisitor {
  // called for the first coefficient
  void init(const Scalar& value, Index i, Index j);
  // called for all other coefficients
  void operator() (const Scalar& value, Index i, Index j);
};
Note
compared to one or two for loops, visitors offer automatic unrolling for small fixed size matrix.
See also
minCoeff(Index*,Index*), maxCoeff(Index*,Index*), DenseBase::redux()
{
  typedef typename internal::visitor_evaluator<Derived> ThisEvaluator;
  ThisEvaluator thisEval(derived());
  enum {
    unroll =  SizeAtCompileTime != Dynamic
           && SizeAtCompileTime * ThisEvaluator::CoeffReadCost + (SizeAtCompileTime-1) * internal::functor_traits<Visitor>::Cost <= EIGEN_UNROLLING_LIMIT
  };
  return internal::visitor_impl<Visitor, ThisEvaluator, unroll ? int(SizeAtCompileTime) : Dynamic>::run(thisEval, visitor);
}
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
Zero() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero static inherited
Returns
an expression of a fixed-size zero matrix or vector.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See also
Zero(Index), Zero(Index,Index)
{
  return Constant(Scalar(0));
}
Zero() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index rows, Index cols) static inherited
Returns
an expression of a zero matrix.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
Example:
Output:
See also
Zero(), Zero(Index)
{
  return Constant(rows, cols, Scalar(0));
}
Zero() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index size) static inherited
Returns
an expression of a zero vector.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
Example:
Output:
See also
Zero(), Zero(Index,Index)
{
  return Constant(size, Scalar(0));
}
Friends And Related Symbol Documentation
operator<<()
template<typename Derived > std::ostream & operator<< (std::ostream & s, const DenseBase< Derived > & m) related
Outputs the matrix, to the given stream.
If you wish to print the matrix with a format different than the default, use DenseBase::format().
It is also possible to change the default format by defining EIGEN_DEFAULT_IO_FORMAT before including Eigen headers. If not defined, this will automatically be defined to Eigen::IOFormat(), that is the Eigen::IOFormat with default parameters.
See also
DenseBase::format()
{
  return internal::print_matrix(s, m.eval(), EIGEN_DEFAULT_IO_FORMAT);
}
References EIGEN_DEFAULT_IO_FORMAT, and Eigen::internal::print_matrix().
pow() [1/3]
template<typename Derived , typename ExponentDerived > const Eigen::CwiseBinaryOp< Eigen::internal::scalar_pow_op< typename Derived::Scalar, typename ExponentDerived::Scalar >, const Derived, const ExponentDerived > pow (const Eigen::ArrayBase< Derived > & x, const Eigen::ArrayBase< ExponentDerived > & exponents) related
Returns
an expression of the coefficient-wise power of x to the given array of exponents.
This function computes the coefficient-wise power.
Example:
Output:
See also
ArrayBase::pow()
  {
    return Eigen::CwiseBinaryOp<Eigen::internal::scalar_pow_op<typename Derived::Scalar, typename ExponentDerived::Scalar>, const Derived, const ExponentDerived>(
      x.derived(),
      exponents.derived()
    );
  }
pow() [2/3]
template<typename Derived , typename ScalarExponent > internal::enable_if<!(internal::is_same< typenameDerived::Scalar, ScalarExponent >::value)&&EIGEN_SCALAR_BINARY_SUPPORTED(pow, typenameDerived::Scalar, ScalarExponent), constEIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(Derived, ScalarExponent, pow)>::type pow (const Eigen::ArrayBase< Derived > & x, const ScalarExponent & exponent) related
Returns
an expression of the coefficient-wise power of x to the given constant exponent.
Template Parameters
ScalarExponent is the scalar type of exponent. It must be compatible with the scalar type of the given expression (Derived::Scalar).
See also
ArrayBase::pow()
{
    return x.derived().pow(exponent);
  }
pow() [3/3]
template<typename Scalar , typename Derived > internal::enable_if<!(internal::is_same< typenameDerived::Scalar, Scalar >::value)&&EIGEN_SCALAR_BINARY_SUPPORTED(pow, Scalar, typenameDerived::Scalar), constEIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(Scalar, Derived, pow)>::type pow (const Scalar & x, const Eigen::ArrayBase< Derived > & exponents) related
Returns
an expression of the coefficient-wise power of the scalar x to the given array of exponents.
This function computes the coefficient-wise power between a scalar and an array of exponents.
Template Parameters
Scalar is the scalar type of x. It must be compatible with the scalar type of the given array expression (Derived::Scalar).
Example:
Output:
See also
ArrayBase::pow()
  {
    return EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(Scalar,Derived,pow)(
            typename internal::plain_constant_type<Derived,Scalar>::type(exponents.rows(), exponents.cols(), x), exponents.derived() );
  }
References EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE.
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/ArrayBase.h
src/eigen/Eigen/src/Core/GlobalFunctions.h
src/eigen/Eigen/src/Core/SelfCwiseBinaryOp.h