Prusa Slicer: Slic3r::ExtrusionPathOriented Class Reference
Slic3r::ExtrusionPathOriented Class Reference
#include <src/libslic3r/ExtrusionEntity.hpp>
Public Member Functions
ExtrusionPathOriented (ExtrusionRole role, double mm3_per_mm, float width, float height)
ExtrusionEntity * clone () const override
ExtrusionEntity * clone_move () override
virtual bool can_reverse () const override
void reverse () override
const Point & first_point () const override
const Point & last_point () const override
const Point & middle_point () const override
size_t size () const
bool empty () const
bool is_closed () const
void intersect_expolygons (const ExPolygons &collection, ExtrusionEntityCollection *retval) const
void subtract_expolygons (const ExPolygons &collection, ExtrusionEntityCollection *retval) const
void clip_end (double distance)
void simplify (double tolerance)
double length () const override
ExtrusionRole role () const override
void polygons_covered_by_width (Polygons &out, const float scaled_epsilon) const override
Polygons polygons_covered_by_width (const float scaled_epsilon=0.f) const
void polygons_covered_by_spacing (Polygons &out, const float scaled_epsilon) const override
Polygons polygons_covered_by_spacing (const float scaled_epsilon=0.f) const
double min_mm3_per_mm () const override
Polyline as_polyline () const override
void collect_polylines (Polylines &dst) const override
void collect_points (Points &dst) const override
double total_volume () const override
virtual bool is_collection () const
virtual bool is_loop () const
virtual Polylines as_polylines () const
Public Attributes
Polyline polyline
double mm3_per_mm
float width
float height
Private Member Functions
void _inflate_collection (const Polylines &polylines, ExtrusionEntityCollection *collection) const
Private Attributes
ExtrusionRole m_role
Detailed Description
Constructor & Destructor Documentation
ExtrusionPathOriented()
Slic3r::ExtrusionPathOriented::ExtrusionPathOriented (ExtrusionRole role, double mm3_per_mm, float width, float height) inline
: ExtrusionPath(role, mm3_per_mm, width, height) {}
Member Function Documentation
_inflate_collection()
void Slic3r::ExtrusionPath::_inflate_collection (const Polylines & polylines, ExtrusionEntityCollection * collection) const private inherited
{
    for (const Polyline &polyline : polylines)
        collection->entities.emplace_back(new ExtrusionPath(polyline, *this));
}
References Slic3r::ExtrusionEntityCollection::entities, and Slic3r::ExtrusionPath::polyline.
Referenced by Slic3r::ExtrusionPath::intersect_expolygons(), and Slic3r::ExtrusionPath::subtract_expolygons().
as_polyline()
Polyline Slic3r::ExtrusionPath::as_polyline () const inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ return this->polyline; }
References Slic3r::ExtrusionPath::polyline.
Referenced by Slic3r::paths_touch().
as_polylines()
virtual Polylines Slic3r::ExtrusionEntity::as_polylines () const inline virtual inherited
{ Polylines dst; this->collect_polylines(dst); return dst; }
References Slic3r::ExtrusionEntity::collect_polylines().
Referenced by Slic3r::FFFSupport::remove_bridges_from_contacts().
can_reverse()
virtual bool Slic3r::ExtrusionPathOriented::can_reverse () const inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ return false; }
clip_end()
void Slic3r::ExtrusionPath::clip_end (double distance) inherited
{
    this->polyline.clip_end(distance);
}
References Slic3r::Polyline::clip_end(), and Slic3r::ExtrusionPath::polyline.
clone()
ExtrusionEntity * Slic3r::ExtrusionPathOriented::clone () const inline override virtual
Reimplemented from Slic3r::ExtrusionPath.
{ return new ExtrusionPathOriented(*this); }
clone_move()
ExtrusionEntity * Slic3r::ExtrusionPathOriented::clone_move () inline override virtual
Reimplemented from Slic3r::ExtrusionPath.
{ return new ExtrusionPathOriented(std::move(*this)); }
collect_points()
void Slic3r::ExtrusionPath::collect_points (Points & dst) const inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ append(dst, this->polyline.points); }
References Slic3r::append(), and Slic3r::MultiPoint::points.
collect_polylines()
void Slic3r::ExtrusionPath::collect_polylines (Polylines & dst) const inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ if (! this->polyline.empty()) dst.emplace_back(this->polyline); }
References Slic3r::MultiPoint::empty().
empty()
bool Slic3r::ExtrusionPath::empty () const inline inherited
{ return this->polyline.empty(); }
References Slic3r::MultiPoint::empty().
Referenced by Slic3r::ExtrusionPath::is_closed(), and Slic3r::PerimeterGenerator::thick_polyline_to_multi_path().
first_point()
const Point & Slic3r::ExtrusionPath::first_point () const inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ return this->polyline.points.front(); }
References Slic3r::MultiPoint::points.
Referenced by Slic3r::GCode::_extrude(), and Slic3r::sort_extra_perimeters().
intersect_expolygons()
void Slic3r::ExtrusionPath::intersect_expolygons (const ExPolygons & collection, ExtrusionEntityCollection * retval) const inherited
{
    this->_inflate_collection(intersection_pl(Polylines{ polyline }, collection), retval);
}
References Slic3r::ExtrusionPath::_inflate_collection(), Slic3r::intersection_pl(), and Slic3r::ExtrusionPath::polyline.
is_closed()
bool Slic3r::ExtrusionPath::is_closed () const inline inherited
{ return ! this->empty() && this->polyline.points.front() == this->polyline.points.back(); }
References Slic3r::ExtrusionPath::empty(), and Slic3r::MultiPoint::points.
is_collection()
virtual bool Slic3r::ExtrusionEntity::is_collection () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionEntityCollection.
{ return false; }
Referenced by Slic3r::SupportSpotsGenerator::check_extrusion_entity_stability(), Slic3r::SupportSpotsGenerator::check_stability(), Slic3r::Layer::sort_perimeters_into_islands(), and Slic3r::SupportSpotsGenerator::to_short_lines().
is_loop()
virtual bool Slic3r::ExtrusionEntity::is_loop () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionMultiPath, and Slic3r::ExtrusionLoop.
{ return false; }
Referenced by Slic3r::chain_extrusion_entities().
last_point()
const Point & Slic3r::ExtrusionPath::last_point () const inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ return this->polyline.points.back(); }
References Slic3r::MultiPoint::points.
Referenced by Slic3r::GCode::_extrude(), and Slic3r::sort_extra_perimeters().
length()
double Slic3r::ExtrusionPath::length () const override virtual inherited
Implements Slic3r::ExtrusionEntity.
{
    return this->polyline.length();
}
References Slic3r::Polyline::length(), and Slic3r::ExtrusionPath::polyline.
Referenced by Slic3r::ExtrusionLoop::clip_end(), and Slic3r::ExtrusionPath::total_volume().
middle_point()
const Point & Slic3r::ExtrusionPath::middle_point () const inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ return this->polyline.points[this->polyline.size() / 2]; }
References Slic3r::MultiPoint::points, and Slic3r::MultiPoint::size().
min_mm3_per_mm()
double Slic3r::ExtrusionPath::min_mm3_per_mm () const inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ return this->mm3_per_mm; }
References Slic3r::ExtrusionPath::mm3_per_mm.
polygons_covered_by_spacing() [1/2]
Polygons Slic3r::ExtrusionPath::polygons_covered_by_spacing (const float scaled_epsilon = 0.f) const inline inherited
        { Polygons out; this->polygons_covered_by_spacing(out, scaled_epsilon); return out; }
References Slic3r::ExtrusionPath::polygons_covered_by_spacing().
polygons_covered_by_spacing() [2/2]
void Slic3r::ExtrusionPath::polygons_covered_by_spacing (Polygons & out, const float scaled_epsilon) const override virtual inherited
Implements Slic3r::ExtrusionEntity.
{
    // Instantiating the Flow class to get the line spacing.
    // Don't know the nozzle diameter, setting to zero. It shall not matter it shall be optimized out by the compiler.
    bool bridge = this->role().is_bridge();
    assert(! bridge || this->width == this->height);
    auto flow = bridge ? Flow::bridging_flow(this->width, 0.f) : Flow(this->width, this->height, 0.f);
    polygons_append(out, offset(this->polyline, 0.5f * float(flow.scaled_spacing()) + scaled_epsilon));
}
References Slic3r::Flow::bridging_flow(), Slic3r::ExtrusionPath::height, Slic3r::ExtrusionRole::is_bridge(), Slic3r::offset(), Slic3r::polygons_append(), Slic3r::ExtrusionPath::polyline, Slic3r::ExtrusionPath::role(), and Slic3r::ExtrusionPath::width.
Referenced by Slic3r::ExtrusionPath::polygons_covered_by_spacing().
polygons_covered_by_width() [1/2]
Polygons Slic3r::ExtrusionPath::polygons_covered_by_width (const float scaled_epsilon = 0.f) const inline inherited
        { Polygons out; this->polygons_covered_by_width(out, scaled_epsilon); return out; }
References Slic3r::ExtrusionPath::polygons_covered_by_width().
polygons_covered_by_width() [2/2]
void Slic3r::ExtrusionPath::polygons_covered_by_width (Polygons & out, const float scaled_epsilon) const override virtual inherited
Implements Slic3r::ExtrusionEntity.
{
    polygons_append(out, offset(this->polyline, float(scale_(this->width/2)) + scaled_epsilon));
}
References Slic3r::offset(), Slic3r::polygons_append(), Slic3r::ExtrusionPath::polyline, scale_, and Slic3r::ExtrusionPath::width.
Referenced by Slic3r::ExtrusionPath::polygons_covered_by_width().
reverse()
void Slic3r::ExtrusionPath::reverse () inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ this->polyline.reverse(); }
References Slic3r::MultiPoint::reverse().
Referenced by Slic3r::sort_extra_perimeters().
role()
ExtrusionRole Slic3r::ExtrusionPath::role () const inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ return m_role; }
References Slic3r::ExtrusionPath::m_role.
Referenced by Slic3r::GCode::_extrude(), Slic3r::FFFSupport::modulate_extrusion_by_overlapping_layers(), Slic3r::ExtrusionPath::polygons_covered_by_spacing(), and Slic3r::ExtrusionLoop::split_at().
simplify()
void Slic3r::ExtrusionPath::simplify (double tolerance) inherited
{
    this->polyline.simplify(tolerance);
}
References Slic3r::ExtrusionPath::polyline, and Slic3r::Polyline::simplify().
Referenced by Slic3r::GCode::extrude_path().
size()
size_t Slic3r::ExtrusionPath::size () const inline inherited
{ return this->polyline.size(); }
References Slic3r::MultiPoint::size().
subtract_expolygons()
void Slic3r::ExtrusionPath::subtract_expolygons (const ExPolygons & collection, ExtrusionEntityCollection * retval) const inherited
{
    this->_inflate_collection(diff_pl(Polylines{ this->polyline }, collection), retval);
}
References Slic3r::ExtrusionPath::_inflate_collection(), Slic3r::diff_pl(), and Slic3r::ExtrusionPath::polyline.
total_volume()
double Slic3r::ExtrusionPath::total_volume () const inline override virtual inherited
Implements Slic3r::ExtrusionEntity.
{ return mm3_per_mm * unscale<double>(length()); }
References Slic3r::ExtrusionPath::length(), and Slic3r::ExtrusionPath::mm3_per_mm.
Member Data Documentation
height
float Slic3r::ExtrusionPath::height inherited
Referenced by Slic3r::GCode::_extrude(), Slic3r::ExtrusionQualityEstimator::estimate_speed_from_extrusion_quality(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::FFFSupport::modulate_extrusion_by_overlapping_layers(), Slic3r::ExtrusionPath::operator=(), Slic3r::ExtrusionPath::polygons_covered_by_spacing(), Slic3r::ExtrusionLoop::split_at(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), and Slic3r::traverse_loops_classic().
m_role
ExtrusionRole Slic3r::ExtrusionPath::m_role private inherited
Referenced by Slic3r::ExtrusionPath::operator=(), Slic3r::ExtrusionPath::operator=(), and Slic3r::ExtrusionPath::role().
mm3_per_mm
double Slic3r::ExtrusionPath::mm3_per_mm inherited
Referenced by Slic3r::GCode::_extrude(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::ExtrusionPath::min_mm3_per_mm(), Slic3r::FFFSupport::modulate_extrusion_by_overlapping_layers(), Slic3r::ExtrusionPath::operator=(), Slic3r::ExtrusionLoop::split_at(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), Slic3r::ExtrusionPath::total_volume(), and Slic3r::traverse_loops_classic().
polyline
Polyline Slic3r::ExtrusionPath::polyline inherited
Referenced by Slic3r::GCode::_extrude(), Slic3r::ExtrusionPath::_inflate_collection(), Slic3r::ExtrusionPath::as_polyline(), Slic3r::ExtrusionPath::clip_end(), Slic3r::ExtrusionLoop::clip_end(), Slic3r::ExtrusionMultiPath::collect_points(), Slic3r::ExtrusionLoop::collect_points(), Slic3r::ExtrusionQualityEstimator::estimate_speed_from_extrusion_quality(), Slic3r::GCode::extrude_path(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::extrusion_entities_append_loops(), Slic3r::extrusion_entities_append_loops_and_paths(), Slic3r::extrusion_entities_append_paths(), Slic3r::extrusion_entities_append_paths(), Slic3r::extrusionentity_extents(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::generate_extra_perimeters_over_overhangs(), Slic3r::FakeWipeTower::getFakeExtrusionPathsFromWipeTower(), Slic3r::ExtrusionPath::intersect_expolygons(), Slic3r::ExtrusionPath::length(), Slic3r::FFFSupport::modulate_extrusion_by_overlapping_layers(), Slic3r::ExtrusionPath::operator=(), Slic3r::paths_touch(), Slic3r::ExtrusionPath::polygons_covered_by_spacing(), Slic3r::ExtrusionPath::polygons_covered_by_width(), Slic3r::ExtrusionPath::simplify(), Slic3r::ExtrusionLoop::split_at(), Slic3r::ExtrusionLoop::split_at_vertex(), Slic3r::ExtrusionPath::subtract_expolygons(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), and Slic3r::traverse_loops_classic().
width
float Slic3r::ExtrusionPath::width inherited
Referenced by Slic3r::GCode::_extrude(), Slic3r::ExtrusionQualityEstimator::estimate_speed_from_extrusion_quality(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::extrusionentity_extents(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::FFFSupport::modulate_extrusion_by_overlapping_layers(), Slic3r::ExtrusionPath::operator=(), Slic3r::ExtrusionPath::polygons_covered_by_spacing(), Slic3r::ExtrusionPath::polygons_covered_by_width(), Slic3r::ExtrusionLoop::split_at(), Slic3r::PerimeterGenerator::thick_polyline_to_multi_path(), and Slic3r::traverse_loops_classic().
The documentation for this class was generated from the following file:
src/libslic3r/ExtrusionEntity.hpp