Prusa Slicer: Slic3r::LayerIsland Struct Reference
Slic3r::LayerIsland Struct Reference
#include <src/libslic3r/Layer.hpp>
Public Member Functions
bool fill_expolygons_composite () const
bool has_extrusions () const
void add_fill_range (const LayerExtrusionRange &new_fill_range)
Public Attributes
LayerExtrusionRange perimeters
ExtrusionRange thin_fills
LayerExtrusionRanges fills
ExPolygonRange fill_expolygons
uint32_t fill_region_id
Static Private Attributes
static constexpr const uint32_t fill_region_composite_id = std::numeric_limits<uint32_t>::max()
Friends
class Layer
Detailed Description
Member Function Documentation
add_fill_range()
void Slic3r::LayerIsland::add_fill_range (const LayerExtrusionRange & new_fill_range) inline
{
        // Compress ranges.
        if (! this->fills.empty() && this->fills.back().region() == new_fill_range.region() && *this->fills.back().end() == *new_fill_range.begin())
            this->fills.back() = { new_fill_range.region(), { *this->fills.back().begin(), *new_fill_range.end() } };
        else
            this->fills.push_back(new_fill_range);
    }
References Slic3r::IndexRange< T >::begin(), Slic3r::IndexRange< T >::end(), and Slic3r::LayerExtrusionRange::region().
fill_expolygons_composite()
bool Slic3r::LayerIsland::fill_expolygons_composite () const inline
{ return this->fill_region_id == fill_region_composite_id; }
References fill_region_composite_id.
Referenced by Slic3r::insert_fills_into_islands(), and Slic3r::Layer::sort_perimeters_into_islands().
has_extrusions()
bool Slic3r::LayerIsland::has_extrusions () const inline
{ return ! this->perimeters.empty() || ! this->fills.empty(); }
References Slic3r::IndexRange< T >::empty().
Friends And Related Symbol Documentation
Layer
friend class Layer friend
Member Data Documentation
fill_expolygons
ExPolygonRange Slic3r::LayerIsland::fill_expolygons
Referenced by Slic3r::insert_fills_into_islands(), and Slic3r::Layer::sort_perimeters_into_islands().
fill_region_composite_id
constexpr const uint32_t Slic3r::LayerIsland::fill_region_composite_id = std::numeric_limits<uint32_t>::max() static constexpr private
Referenced by fill_expolygons_composite().
fill_region_id
uint32_t Slic3r::LayerIsland::fill_region_id
Referenced by Slic3r::insert_fills_into_islands(), and Slic3r::Layer::sort_perimeters_into_islands().
fills
LayerExtrusionRanges Slic3r::LayerIsland::fills
perimeters
LayerExtrusionRange Slic3r::LayerIsland::perimeters
Referenced by Slic3r::insert_fills_into_islands(), and Slic3r::Layer::sort_perimeters_into_islands().
thin_fills
ExtrusionRange Slic3r::LayerIsland::thin_fills
Referenced by Slic3r::Layer::sort_perimeters_into_islands().
The documentation for this struct was generated from the following file:
src/libslic3r/Layer.hpp