Prusa Slicer: Eigen::Ref< const TPlainObjectType, Options, StrideType > Class Template Reference
Eigen::Ref< const TPlainObjectType, Options, StrideType > Class Template Reference
#include <src/eigen/Eigen/src/Core/Ref.h>
Public Types
typedef RefBase< Ref > Base
Public Member Functions
template<typename Derived >
EIGEN_DEVICE_FUNC Ref (const DenseBase< Derived > &expr, typename internal::enable_if< bool(Traits::template match< Derived >::ScalarTypeMatch), Derived >::type *=0)
EIGEN_DEVICE_FUNC Ref (const Ref &other)
template<typename OtherRef >
EIGEN_DEVICE_FUNC Ref (const RefBase< OtherRef > &other)
EIGEN_DEVICE_FUNC Index innerStride () const
EIGEN_DEVICE_FUNC Index outerStride () const
Protected Types
typedef Stride< StrideType::OuterStrideAtCompileTime, StrideType::InnerStrideAtCompileTime > StrideBase
Protected Member Functions
template<typename Expression >
EIGEN_DEVICE_FUNC void construct (const Expression &expr, internal::true_type)
template<typename Expression >
EIGEN_DEVICE_FUNC void construct (const Expression &expr, internal::false_type)
EIGEN_DEVICE_FUNC void construct (Expression &expr)
Protected Attributes
TPlainObjectType m_object
StrideBase m_stride
Private Types
typedef internal::traits< Ref > Traits
typedef internal::traits< Ref< const TPlainObjectType, Options, StrideType > >::PlainObjectType PlainObjectType
typedef internal::traits< Ref< const TPlainObjectType, Options, StrideType > >::StrideType StrideType
Detailed Description
template<typename TPlainObjectType, int Options, typename StrideType>
class Eigen::Ref< const TPlainObjectType, Options, StrideType >
Member Typedef Documentation
Base
template<typename TPlainObjectType , int Options, typename StrideType > typedef RefBase<Ref> Eigen::Ref< const TPlainObjectType, Options, StrideType >::Base
PlainObjectType
typedef internal::traits<Ref< const TPlainObjectType, Options, StrideType > >::PlainObjectType Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >::PlainObjectType private inherited
StrideBase
typedef Stride<StrideType::OuterStrideAtCompileTime,StrideType::InnerStrideAtCompileTime> Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >::StrideBase protected inherited
StrideType
typedef internal::traits<Ref< const TPlainObjectType, Options, StrideType > >::StrideType Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >::StrideType private inherited
Traits
template<typename TPlainObjectType , int Options, typename StrideType > typedef internal::traits<Ref> Eigen::Ref< const TPlainObjectType, Options, StrideType >::Traits private
Constructor & Destructor Documentation
Ref() [1/3]
template<typename TPlainObjectType , int Options, typename StrideType > template<typename Derived > EIGEN_DEVICE_FUNC Eigen::Ref< const TPlainObjectType, Options, StrideType >::Ref (const DenseBase< Derived > & expr, typename internal::enable_if< bool(Traits::template match< Derived >::ScalarTypeMatch), Derived >::type * = 0) inline
    {
//      std::cout << match_helper<Derived>::HasDirectAccess << "," << match_helper<Derived>::OuterStrideMatch << "," << match_helper<Derived>::InnerStrideMatch << "\n";
//      std::cout << int(StrideType::OuterStrideAtCompileTime) << " - " << int(Derived::OuterStrideAtCompileTime) << "\n";
//      std::cout << int(StrideType::InnerStrideAtCompileTime) << " - " << int(Derived::InnerStrideAtCompileTime) << "\n";
      construct(expr.derived(), typename Traits::template match<Derived>::type());
    }
References Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::construct().
Ref() [2/3]
template<typename TPlainObjectType , int Options, typename StrideType > EIGEN_DEVICE_FUNC Eigen::Ref< const TPlainObjectType, Options, StrideType >::Ref (const Ref< const TPlainObjectType, Options, StrideType > & other) inline
                                                   : Base(other) {
      // copy constructor shall not copy the m_object, to avoid unnecessary malloc and copy
    }
Ref() [3/3]
template<typename TPlainObjectType , int Options, typename StrideType > template<typename OtherRef > EIGEN_DEVICE_FUNC Eigen::Ref< const TPlainObjectType, Options, StrideType >::Ref (const RefBase< OtherRef< const TPlainObjectType, Options, StrideType > > & other) inline
{
      construct(other.derived(), typename Traits::template match<OtherRef>::type());
    }
References Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::construct().
Member Function Documentation
construct() [1/3]
template<typename TPlainObjectType , int Options, typename StrideType > template<typename Expression > EIGEN_DEVICE_FUNC void Eigen::Ref< const TPlainObjectType, Options, StrideType >::construct (const Expression & expr, internal::false_type) inline protected
    {
      internal::call_assignment_no_alias(m_object,expr,internal::assign_op<Scalar,Scalar>());
      Base::construct(m_object);
    }
References Eigen::internal::call_assignment_no_alias(), and Eigen::RefBase< Derived >::construct().
construct() [2/3]
template<typename TPlainObjectType , int Options, typename StrideType > template<typename Expression > EIGEN_DEVICE_FUNC void Eigen::Ref< const TPlainObjectType, Options, StrideType >::construct (const Expression & expr, internal::true_type) inline protected
    {
      Base::construct(expr);
    }
References Eigen::RefBase< Derived >::construct().
construct() [3/3]
EIGEN_DEVICE_FUNC void Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >::construct (Expression & expr) inline protected inherited
  {
    EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE(PlainObjectType,Expression);
    if(PlainObjectType::RowsAtCompileTime==1)
    {
      eigen_assert(expr.rows()==1 || expr.cols()==1);
      ::new (static_cast<Base*>(this)) Base(expr.data(), 1, expr.size());
    }
    else if(PlainObjectType::ColsAtCompileTime==1)
    {
      eigen_assert(expr.rows()==1 || expr.cols()==1);
      ::new (static_cast<Base*>(this)) Base(expr.data(), expr.size(), 1);
    }
    else
      ::new (static_cast<Base*>(this)) Base(expr.data(), expr.rows(), expr.cols());
    if(Expression::IsVectorAtCompileTime && (!PlainObjectType::IsVectorAtCompileTime) && ((Expression::Flags&RowMajorBit)!=(PlainObjectType::Flags&RowMajorBit)))
      ::new (&m_stride) StrideBase(expr.innerStride(), StrideType::InnerStrideAtCompileTime==0?0:1);
    else
      ::new (&m_stride) StrideBase(StrideType::OuterStrideAtCompileTime==0?0:expr.outerStride(),
                                   StrideType::InnerStrideAtCompileTime==0?0:expr.innerStride());
  }
innerStride()
EIGEN_DEVICE_FUNC Index Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >::innerStride () const inline inherited
  {
    return StrideType::InnerStrideAtCompileTime != 0 ? m_stride.inner() : 1;
  }
outerStride()
EIGEN_DEVICE_FUNC Index Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >::outerStride () const inline inherited
  {
    return StrideType::OuterStrideAtCompileTime != 0 ? m_stride.outer()
         : IsVectorAtCompileTime ? this->size()
         : int(Flags)&RowMajorBit ? this->cols()
         : this->rows();
  }
Member Data Documentation
m_object
template<typename TPlainObjectType , int Options, typename StrideType > TPlainObjectType Eigen::Ref< const TPlainObjectType, Options, StrideType >::m_object protected
m_stride
StrideBase Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >::m_stride protected inherited
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/Ref.h