Prusa Slicer: src/avrdude/flip2.c File Reference
flip2.c File Reference
#include "ac_cfg.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <unistd.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "flip2.h"
#include "dfu.h"
#include "usbdevs.h"
Classes
struct flip2
struct flip2_cmd
Macros
#define FLIP2(pgm) ((struct flip2 *)(pgm->cookie))
#define FLIP2_STATUS_OK 0x0000
#define FLIP2_STATUS_STALL 0x0F0A
#define FLIP2_STATUS_MEM_UKNOWN 0x030A
#define FLIP2_STATUS_MEM_PROTECTED 0x0300
#define FLIP2_STATUS_OUTOFRANGE 0x080A
#define FLIP2_STATUS_BLANK_FAIL 0x0500
#define FLIP2_STATUS_ERASE_ONGOING 0x0904
#define FLIP2_CMD_GROUP_DOWNLOAD 0x01
#define FLIP2_CMD_GROUP_UPLOAD 0x03
#define FLIP2_CMD_GROUP_EXEC 0x04
#define FLIP2_CMD_GROUP_SELECT 0x06
#define FLIP2_CMD_PROG_START 0x00
#define FLIP2_CMD_READ_MEMORY 0x00
#define FLIP2_CMD_SELECT_MEMORY 0x03
#define FLIP2_CMD_CHIP_ERASE 0x00
#define FLIP2_CMD_START_APP 0x03
#define FLIP2_SELECT_MEMORY_UNIT 0x00
#define FLIP2_SELECT_MEMORY_PAGE 0x01
Enumerations
enum flip2_mem_unit {
FLIP2_MEM_UNIT_UNKNOWN = -1 , FLIP2_MEM_UNIT_FLASH = 0x00 , FLIP2_MEM_UNIT_EEPROM = 0x01 , FLIP2_MEM_UNIT_SECURITY = 0x02 ,
FLIP2_MEM_UNIT_CONFIGURATION = 0x03 , FLIP2_MEM_UNIT_BOOTLOADER = 0x04 , FLIP2_MEM_UNIT_SIGNATURE = 0x05 , FLIP2_MEM_UNIT_USER = 0x06 ,
FLIP2_MEM_UNIT_INT_RAM = 0x07 , FLIP2_MEM_UNIT_EXT_MEM_CS0 = 0x08 , FLIP2_MEM_UNIT_EXT_MEM_CS1 = 0x09 , FLIP2_MEM_UNIT_EXT_MEM_CS2 = 0x0A ,
FLIP2_MEM_UNIT_EXT_MEM_CS3 = 0x0B , FLIP2_MEM_UNIT_EXT_MEM_CS4 = 0x0C , FLIP2_MEM_UNIT_EXT_MEM_CS5 = 0x0D , FLIP2_MEM_UNIT_EXT_MEM_CS6 = 0x0E ,
FLIP2_MEM_UNIT_EXT_MEM_CS7 = 0x0F , FLIP2_MEM_UNIT_EXT_MEM_DF = 0x10
}
Functions
static int flip2_open (PROGRAMMER *pgm, char *port_spec)
static int flip2_initialize (PROGRAMMER *pgm, AVRPART *part)
static void flip2_close (PROGRAMMER *pgm)
static void flip2_enable (PROGRAMMER *pgm)
static void flip2_disable (PROGRAMMER *pgm)
static void flip2_display (PROGRAMMER *pgm, const char *prefix)
static int flip2_program_enable (PROGRAMMER *pgm, AVRPART *part)
static int flip2_chip_erase (PROGRAMMER *pgm, AVRPART *part)
static int flip2_read_byte (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem, unsigned long addr, unsigned char *value)
static int flip2_write_byte (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem, unsigned long addr, unsigned char value)
static int flip2_paged_load (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem, unsigned int page_size, unsigned int addr, unsigned int n_bytes)
static int flip2_paged_write (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem, unsigned int page_size, unsigned int addr, unsigned int n_bytes)
static int flip2_read_sig_bytes (PROGRAMMER *pgm, AVRPART *part, AVRMEM *mem)
static void flip2_setup (PROGRAMMER *pgm)
static void flip2_teardown (PROGRAMMER *pgm)
void flip2_initpgm (PROGRAMMER *pgm)
Variables
const char flip2_desc [] = "FLIP USB DFU protocol version 2 (AVR4023)"
Class Documentation
flip2
struct flip2
Class Members
unsigned char boot_ver
struct dfu_dev * dfu
unsigned char part_rev
unsigned char part_sig[3]
flip2_cmd
struct flip2_cmd
Class Members
unsigned char args[4]
unsigned char cmd_id
unsigned char group_id
Macro Definition Documentation
FLIP2
#define FLIP2 (pgm) ((struct flip2 *)(pgm->cookie))
FLIP2_CMD_CHIP_ERASE
#define FLIP2_CMD_CHIP_ERASE 0x00
FLIP2_CMD_GROUP_DOWNLOAD
#define FLIP2_CMD_GROUP_DOWNLOAD 0x01
FLIP2_CMD_GROUP_EXEC
#define FLIP2_CMD_GROUP_EXEC 0x04
FLIP2_CMD_GROUP_SELECT
#define FLIP2_CMD_GROUP_SELECT 0x06
FLIP2_CMD_GROUP_UPLOAD
#define FLIP2_CMD_GROUP_UPLOAD 0x03
FLIP2_CMD_PROG_START
#define FLIP2_CMD_PROG_START 0x00
FLIP2_CMD_READ_MEMORY
#define FLIP2_CMD_READ_MEMORY 0x00
FLIP2_CMD_SELECT_MEMORY
#define FLIP2_CMD_SELECT_MEMORY 0x03
FLIP2_CMD_START_APP
#define FLIP2_CMD_START_APP 0x03
FLIP2_SELECT_MEMORY_PAGE
#define FLIP2_SELECT_MEMORY_PAGE 0x01
FLIP2_SELECT_MEMORY_UNIT
#define FLIP2_SELECT_MEMORY_UNIT 0x00
FLIP2_STATUS_BLANK_FAIL
#define FLIP2_STATUS_BLANK_FAIL 0x0500
FLIP2_STATUS_ERASE_ONGOING
#define FLIP2_STATUS_ERASE_ONGOING 0x0904
FLIP2_STATUS_MEM_PROTECTED
#define FLIP2_STATUS_MEM_PROTECTED 0x0300
FLIP2_STATUS_MEM_UKNOWN
#define FLIP2_STATUS_MEM_UKNOWN 0x030A
FLIP2_STATUS_OK
#define FLIP2_STATUS_OK 0x0000
FLIP2_STATUS_OUTOFRANGE
#define FLIP2_STATUS_OUTOFRANGE 0x080A
FLIP2_STATUS_STALL
#define FLIP2_STATUS_STALL 0x0F0A
Enumeration Type Documentation
flip2_mem_unit
enum flip2_mem_unit
Enumerator
FLIP2_MEM_UNIT_UNKNOWN
FLIP2_MEM_UNIT_FLASH
FLIP2_MEM_UNIT_EEPROM
FLIP2_MEM_UNIT_SECURITY
FLIP2_MEM_UNIT_CONFIGURATION
FLIP2_MEM_UNIT_BOOTLOADER
FLIP2_MEM_UNIT_SIGNATURE
FLIP2_MEM_UNIT_USER
FLIP2_MEM_UNIT_INT_RAM
FLIP2_MEM_UNIT_EXT_MEM_CS0
FLIP2_MEM_UNIT_EXT_MEM_CS1
FLIP2_MEM_UNIT_EXT_MEM_CS2
FLIP2_MEM_UNIT_EXT_MEM_CS3
FLIP2_MEM_UNIT_EXT_MEM_CS4
FLIP2_MEM_UNIT_EXT_MEM_CS5
FLIP2_MEM_UNIT_EXT_MEM_CS6
FLIP2_MEM_UNIT_EXT_MEM_CS7
FLIP2_MEM_UNIT_EXT_MEM_DF
                    {
  FLIP2_MEM_UNIT_UNKNOWN = -1,
  FLIP2_MEM_UNIT_FLASH = 0x00,
  FLIP2_MEM_UNIT_EEPROM = 0x01,
  FLIP2_MEM_UNIT_SECURITY = 0x02,
  FLIP2_MEM_UNIT_CONFIGURATION = 0x03,
  FLIP2_MEM_UNIT_BOOTLOADER = 0x04,
  FLIP2_MEM_UNIT_SIGNATURE = 0x05,
  FLIP2_MEM_UNIT_USER = 0x06,
  FLIP2_MEM_UNIT_INT_RAM = 0x07,
  FLIP2_MEM_UNIT_EXT_MEM_CS0 = 0x08,
  FLIP2_MEM_UNIT_EXT_MEM_CS1 = 0x09,
  FLIP2_MEM_UNIT_EXT_MEM_CS2 = 0x0A,
  FLIP2_MEM_UNIT_EXT_MEM_CS3 = 0x0B,
  FLIP2_MEM_UNIT_EXT_MEM_CS4 = 0x0C,
  FLIP2_MEM_UNIT_EXT_MEM_CS5 = 0x0D,
  FLIP2_MEM_UNIT_EXT_MEM_CS6 = 0x0E,
  FLIP2_MEM_UNIT_EXT_MEM_CS7 = 0x0F,
  FLIP2_MEM_UNIT_EXT_MEM_DF = 0x10
};
Function Documentation
flip2_chip_erase()
int flip2_chip_erase (PROGRAMMER * pgm, AVRPART * part) static
{
  return -1;
}
Referenced by flip2_initpgm().
flip2_close()
void flip2_close (PROGRAMMER * pgm) static
{
}
Referenced by flip2_initpgm().
flip2_disable()
void flip2_disable (PROGRAMMER * pgm) static
{
}
Referenced by flip2_initpgm().
flip2_display()
void flip2_display (PROGRAMMER * pgm, const char * prefix) static
{
}
Referenced by flip2_initpgm().
flip2_enable()
void flip2_enable (PROGRAMMER * pgm) static
{
}
Referenced by flip2_initpgm().
flip2_initialize()
int flip2_initialize (PROGRAMMER * pgm, AVRPART * part) static
{
  return -1;
}
Referenced by flip2_initpgm().
flip2_initpgm()
void flip2_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "flip2");
  /* Mandatory Functions */
  pgm->initialize       = flip2_initialize;
  pgm->enable           = flip2_enable;
  pgm->disable          = flip2_disable;
  pgm->display          = flip2_display;
  pgm->program_enable   = flip2_program_enable;
  pgm->chip_erase       = flip2_chip_erase;
  pgm->open             = flip2_open;
  pgm->close            = flip2_close;
  pgm->paged_load       = flip2_paged_load;
  pgm->paged_write      = flip2_paged_write;
  pgm->read_byte        = flip2_read_byte;
  pgm->write_byte       = flip2_write_byte;
  pgm->read_sig_bytes   = flip2_read_sig_bytes;
  pgm->setup            = flip2_setup;
  pgm->teardown         = flip2_teardown;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, flip2_chip_erase(), flip2_close(), flip2_disable(), flip2_display(), flip2_enable(), flip2_initialize(), flip2_open(), flip2_paged_load(), flip2_paged_write(), flip2_program_enable(), flip2_read_byte(), flip2_read_sig_bytes(), flip2_setup(), flip2_teardown(), flip2_write_byte(), programmer_t::initialize, programmer_t::open, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::program_enable, programmer_t::read_byte, programmer_t::read_sig_bytes, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
flip2_open()
int flip2_open (PROGRAMMER * pgm, char * port_spec) static
{
  fprintf(stderr, "%s: Error: No USB support in this compile of avrdude\n",
    progname);
  return -1;
}
References progname.
Referenced by flip2_initpgm().
flip2_paged_load()
int flip2_paged_load (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem, unsigned int page_size, unsigned int addr, unsigned int n_bytes) static
{
  return -1;
}
Referenced by flip2_initpgm().
flip2_paged_write()
int flip2_paged_write (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem, unsigned int page_size, unsigned int addr, unsigned int n_bytes) static
{
  return -1;
}
Referenced by flip2_initpgm().
flip2_program_enable()
int flip2_program_enable (PROGRAMMER * pgm, AVRPART * part) static
{
  return -1;
}
Referenced by flip2_initpgm().
flip2_read_byte()
int flip2_read_byte (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem, unsigned long addr, unsigned char * value) static
{
  return -1;
}
Referenced by flip2_initpgm().
flip2_read_sig_bytes()
int flip2_read_sig_bytes (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem) static
{
  return -1;
}
Referenced by flip2_initpgm().
flip2_setup()
void flip2_setup (PROGRAMMER * pgm) static
{
}
Referenced by flip2_initpgm().
flip2_teardown()
void flip2_teardown (PROGRAMMER * pgm) static
{
}
Referenced by flip2_initpgm().
flip2_write_byte()
int flip2_write_byte (PROGRAMMER * pgm, AVRPART * part, AVRMEM * mem, unsigned long addr, unsigned char value) static
{
  return -1;
}
Referenced by flip2_initpgm().
Variable Documentation
flip2_desc
const char flip2_desc[] = "FLIP USB DFU protocol version 2 (AVR4023)"