Prusa Slicer: Slic3r::GUI::PagePrinters Struct Reference
Slic3r::GUI::PagePrinters Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
PagePrinters (ConfigWizard *parent, wxString title, wxString shortname, const VendorProfile &vendor, unsigned indent, Technology technology)
void select_all (bool select, bool alternates=false)
int get_width () const
bool any_selected () const
std::set< std::string > get_selected_models ()
std::string get_vendor_id () const
virtual void set_run_reason (ConfigWizard::RunReason run_reason) override
template<class T >
T * append (T *thing, int proportion=0, int flag=wxEXPAND|wxTOP|wxBOTTOM, int border=10)
wxStaticText * append_text (wxString text)
void append_spacer (int space)
ConfigWizard::priv * wizard_p () const
virtual void apply_custom_config (DynamicPrintConfig &config)
virtual void on_activate ()
Public Attributes
std::vector< PrinterPicker * > printer_pickers
Technology technology
bool install
bool has_printers { false }
bool is_primary_printer_page { false }
ConfigWizard * parent
const wxString shortname
wxBoxSizer * content
const unsigned indent
Detailed Description
Constructor & Destructor Documentation
PagePrinters()
Slic3r::GUI::PagePrinters::PagePrinters (ConfigWizard * parent, wxString title, wxString shortname, const VendorProfile & vendor, unsigned indent, Technology technology)
    : ConfigWizardPage(parent, std::move(title), std::move(shortname), indent)
    , technology(technology)
    , install(false)   // only used for 3rd party vendors
{
    enum {
        COL_SIZE = 200,
    };
    AppConfig *appconfig = &this->wizard_p()->appconfig_new;
    const auto families = vendor.families();
    for (const auto &family : families) {
        const auto filter = [&](const VendorProfile::PrinterModel &model) {
            return ((model.technology == ptFFF && technology & T_FFF)
                    || (model.technology == ptSLA && technology & T_SLA))
                && model.family == family;
        };
        if (std::find_if(vendor.models.begin(), vendor.models.end(), filter) == vendor.models.end()) {
            continue;
        }
        const auto picker_title = family.empty() ? wxString() : format_wxstr(_L("%s Family"), family);
        auto *picker = new PrinterPicker(this, vendor, picker_title, MAX_COLS, *appconfig, filter);
        picker->Bind(EVT_PRINTER_PICK, [this, appconfig](const PrinterPickerEvent &evt) {
            appconfig->set_variant(evt.vendor_id, evt.model_id, evt.variant_name, evt.enable);
            wizard_p()->on_printer_pick(this, evt);
        });
        append(new StaticLine(this));
        append(picker);
        printer_pickers.push_back(picker);
        has_printers = true;
    }
}
References _L, Slic3r::GUI::ConfigWizard::priv::appconfig_new, Slic3r::GUI::ConfigWizardPage::append(), Slic3r::GUI::PrinterPickerEvent::enable, Slic3r::VendorProfile::families(), Slic3r::GUI::format_wxstr(), has_printers, Slic3r::GUI::MAX_COLS, Slic3r::GUI::PrinterPickerEvent::model_id, Slic3r::VendorProfile::models, Slic3r::GUI::ConfigWizard::priv::on_printer_pick(), printer_pickers, Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::AppConfig::set_variant(), Slic3r::GUI::T_FFF, Slic3r::GUI::T_SLA, technology, Slic3r::GUI::PrinterPickerEvent::variant_name, Slic3r::GUI::PrinterPickerEvent::vendor_id, and Slic3r::GUI::ConfigWizardPage::wizard_p().
Member Function Documentation
any_selected()
bool Slic3r::GUI::PagePrinters::any_selected () const
{
    for (const auto *picker : printer_pickers) {
        if (picker->any_selected()) { return true; }
    }
    return false;
}
References printer_pickers.
append()
template<class T > T * Slic3r::GUI::ConfigWizardPage::append (T * thing, int proportion = 0, int flag = wxEXPAND|wxTOP|wxBOTTOM, int border = 10) inline inherited
    {
        content->Add(thing, proportion, flag, border);
        return thing;
    }
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageMode::PageMode(), PagePrinters(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), Slic3r::GUI::PageVendors::PageVendors(), and Slic3r::GUI::ConfigWizardPage::append_text().
append_spacer()
void Slic3r::GUI::ConfigWizardPage::append_spacer (int space) inherited
{
    // FIXME: scaling
    content->AddSpacer(space);
}
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageTemperatures::PageTemperatures(), and Slic3r::GUI::PageUpdate::PageUpdate().
append_text()
wxStaticText * Slic3r::GUI::ConfigWizardPage::append_text (wxString text) inherited
{
    auto *widget = new wxStaticText(this, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    widget->Wrap(WRAP_WIDTH);
    widget->SetMinSize(wxSize(WRAP_WIDTH, -1));
    append(widget);
    return widget;
}
References Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::WRAP_WIDTH.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), and Slic3r::GUI::PageVendors::PageVendors().
apply_custom_config()
virtual void Slic3r::GUI::ConfigWizardPage::apply_custom_config (DynamicPrintConfig & config) inline virtual inherited
Reimplemented in Slic3r::GUI::PageFirmware, Slic3r::GUI::PageBedShape, Slic3r::GUI::PageBuildVolume, Slic3r::GUI::PageDiameters, and Slic3r::GUI::PageTemperatures.
{}
get_selected_models()
std::set< std::string > Slic3r::GUI::PagePrinters::get_selected_models ()
{
    std::set<std::string> ret_set;
    for (const auto *picker : printer_pickers)
    {
        std::set<std::string> tmp_models = picker->get_selected_models();
        ret_set.insert(tmp_models.begin(), tmp_models.end());
    }
    return ret_set;
}
References printer_pickers.
get_vendor_id()
std::string Slic3r::GUI::PagePrinters::get_vendor_id () const inline
{ return printer_pickers.empty() ? "" : printer_pickers[0]->vendor_id; }
References printer_pickers.
get_width()
int Slic3r::GUI::PagePrinters::get_width () const
{
    return std::accumulate(printer_pickers.begin(), printer_pickers.end(), 0,
        [](int acc, const PrinterPicker *picker) { return std::max(acc, picker->get_width()); });
}
References printer_pickers.
on_activate()
virtual void Slic3r::GUI::ConfigWizardPage::on_activate () inline virtual inherited
Reimplemented in Slic3r::GUI::PageMaterials.
{}
Referenced by Slic3r::GUI::PageMode::PageMode().
select_all()
void Slic3r::GUI::PagePrinters::select_all (bool select, bool alternates = false)
{
    for (auto picker : printer_pickers) {
        picker->select_all(select, alternates);
    }
}
References printer_pickers.
set_run_reason()
void Slic3r::GUI::PagePrinters::set_run_reason (ConfigWizard::RunReason run_reason) override virtual
Reimplemented from Slic3r::GUI::ConfigWizardPage.
{
    if (is_primary_printer_page
        && (run_reason == ConfigWizard::RR_DATA_EMPTY || run_reason == ConfigWizard::RR_DATA_LEGACY)
        && printer_pickers.size() > 0
        && printer_pickers[0]->vendor_id == PresetBundle::PRUSA_BUNDLE) {
        printer_pickers[0]->select_one(0, true);
    }
}
References is_primary_printer_page, printer_pickers, Slic3r::PresetBundle::PRUSA_BUNDLE, Slic3r::GUI::ConfigWizard::RR_DATA_EMPTY, and Slic3r::GUI::ConfigWizard::RR_DATA_LEGACY.
wizard_p()
ConfigWizard::priv * Slic3r::GUI::ConfigWizardPage::wizard_p () const inline inherited
{ return parent->p.get(); }
References Slic3r::GUI::ConfigWizard::p, and Slic3r::GUI::ConfigWizardPage::parent.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageCustom::PageCustom(), PagePrinters(), Slic3r::GUI::PageVendors::PageVendors(), Slic3r::GUI::PageMaterials::on_activate(), Slic3r::GUI::PageMaterials::select_material(), and Slic3r::GUI::PageMaterials::update_lists().
Member Data Documentation
content
wxBoxSizer* Slic3r::GUI::ConfigWizardPage::content inherited
Referenced by Slic3r::GUI::ConfigWizardPage::ConfigWizardPage(), Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::ConfigWizardPage::append_spacer().
has_printers
bool Slic3r::GUI::PagePrinters::has_printers { false }
Referenced by PagePrinters().
indent
const unsigned Slic3r::GUI::ConfigWizardPage::indent inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page().
install
bool Slic3r::GUI::PagePrinters::install
is_primary_printer_page
bool Slic3r::GUI::PagePrinters::is_primary_printer_page { false }
Referenced by set_run_reason().
parent
ConfigWizard* Slic3r::GUI::ConfigWizardPage::parent inherited
Referenced by Slic3r::GUI::PageMaterials::PageMaterials(), and Slic3r::GUI::ConfigWizardPage::wizard_p().
printer_pickers
std::vector<PrinterPicker *> Slic3r::GUI::PagePrinters::printer_pickers
Referenced by PagePrinters(), any_selected(), get_selected_models(), get_vendor_id(), get_width(), select_all(), and set_run_reason().
shortname
const wxString Slic3r::GUI::ConfigWizardPage::shortname inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page(), and Slic3r::GUI::ConfigWizard::priv::add_page().
technology
Technology Slic3r::GUI::PagePrinters::technology
Referenced by PagePrinters(), and Slic3r::GUI::ConfigWizard::priv::on_printer_pick().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp