Prusa Slicer: Slic3r::GUI::NotificationProgressIndicator Class Reference
Slic3r::GUI::NotificationProgressIndicator Class Reference
#include <src/slic3r/GUI/Jobs/NotificationProgressIndicator.hpp>
Public Types
using CancelFn = std::function< void()>
Cancel callback function type.
Public Member Functions
NotificationProgressIndicator (NotificationManager *nm)
void set_range (int range) override
void set_cancel_callback (CancelFn=CancelFn()) override
void set_progress (int pr) override
void set_status_text (const char *) override
int get_range () const override
Private Attributes
NotificationManager * m_nm = nullptr
CancelFn m_cancelfn
Detailed Description
Member Typedef Documentation
CancelFn
using Slic3r::ProgressIndicator::CancelFn = std::function<void()> inherited
Cancel callback function type.
Constructor & Destructor Documentation
NotificationProgressIndicator()
Slic3r::GUI::NotificationProgressIndicator::NotificationProgressIndicator (NotificationManager * nm) explicit
: m_nm{nm} {}
Member Function Documentation
get_range()
int Slic3r::GUI::NotificationProgressIndicator::get_range () const override virtual
Implements Slic3r::ProgressIndicator.
{
    return m_nm->progress_indicator_get_range();
}
References m_nm, and Slic3r::GUI::NotificationManager::progress_indicator_get_range().
set_cancel_callback()
void Slic3r::GUI::NotificationProgressIndicator::set_cancel_callback (CancelFn fn = CancelFn()) override virtual
Implements Slic3r::ProgressIndicator.
{
    m_cancelfn = std::move(fn);
    m_nm->progress_indicator_set_cancel_callback(m_cancelfn);
}
References m_cancelfn, m_nm, and Slic3r::GUI::NotificationManager::progress_indicator_set_cancel_callback().
Referenced by set_progress().
set_progress()
void Slic3r::GUI::NotificationProgressIndicator::set_progress (int pr) override virtual
Implements Slic3r::ProgressIndicator.
{
    if (!pr)
        set_cancel_callback(m_cancelfn);
    m_nm->progress_indicator_set_progress(pr);
}
References m_cancelfn, m_nm, Slic3r::GUI::NotificationManager::progress_indicator_set_progress(), and set_cancel_callback().
set_range()
void Slic3r::GUI::NotificationProgressIndicator::set_range (int range) override virtual
Implements Slic3r::ProgressIndicator.
{
    m_nm->progress_indicator_set_range(range);
}
References m_nm, Slic3r::GUI::NotificationManager::progress_indicator_set_range(), and Slic3r::range().
set_status_text()
void Slic3r::GUI::NotificationProgressIndicator::set_status_text (const char * msg) override virtual
Implements Slic3r::ProgressIndicator.
{
    m_nm->progress_indicator_set_status_text(msg);
}
References m_nm, and Slic3r::GUI::NotificationManager::progress_indicator_set_status_text().
Member Data Documentation
m_cancelfn
CancelFn Slic3r::GUI::NotificationProgressIndicator::m_cancelfn private
Referenced by set_cancel_callback(), and set_progress().
m_nm
NotificationManager* Slic3r::GUI::NotificationProgressIndicator::m_nm = nullptr private
Referenced by get_range(), set_cancel_callback(), set_progress(), set_range(), and set_status_text().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/NotificationProgressIndicator.hpp
src/slic3r/GUI/Jobs/NotificationProgressIndicator.cpp