Prusa Slicer: Slic3r::SLAPrint::PrintLayer Class Reference
Slic3r::SLAPrint::PrintLayer Class Reference
#include <src/libslic3r/SLAPrint.hpp>
Public Member Functions
PrintLayer (coord_t lvl)
bool operator< (const PrintLayer &other) const
void add (const SliceRecord &sr)
coord_t level () const
auto slices () const -> const decltype(m_slices)&
const ExPolygons & transformed_slices () const
Private Member Functions
template<class Container >
void transformed_slices (Container &&c)
Private Attributes
coord_t m_level
std::vector< std::reference_wrapper< const SliceRecord > > m_slices
ExPolygons m_transformed_slices
Friends
class SLAPrint::Steps
Detailed Description
Constructor & Destructor Documentation
PrintLayer()
Slic3r::SLAPrint::PrintLayer::PrintLayer (coord_t lvl) inline explicit
: m_level(lvl) {}
Member Function Documentation
add()
void Slic3r::SLAPrint::PrintLayer::add (const SliceRecord & sr) inline
{ m_slices.emplace_back(sr); }
level()
coord_t Slic3r::SLAPrint::PrintLayer::level () const inline
{ return m_level; }
operator<()
bool Slic3r::SLAPrint::PrintLayer::operator< (const PrintLayer & other) const inline
{
            return m_level < other.m_level;
        }
References m_level.
slices()
auto Slic3r::SLAPrint::PrintLayer::slices () const -> const decltype (m_slices)& inline
{ return m_slices; }
Referenced by Slic3r::SLAPrint::Steps::merge_slices_and_eval_stats().
transformed_slices() [1/2]
const ExPolygons & Slic3r::SLAPrint::PrintLayer::transformed_slices () const inline
{
            return m_transformed_slices;
        }
transformed_slices() [2/2]
template<class Container > void Slic3r::SLAPrint::PrintLayer::transformed_slices (Container && c) inline private
        {
            m_transformed_slices = std::forward<Container>(c);
        }
Referenced by Slic3r::SLAPrint::Steps::merge_slices_and_eval_stats(), and Slic3r::SLAPrint::Steps::rasterize().
Friends And Related Symbol Documentation
SLAPrint::Steps
friend class SLAPrint::Steps friend
Member Data Documentation
m_level
coord_t Slic3r::SLAPrint::PrintLayer::m_level private
Referenced by operator<().
m_slices
std::vector<std::reference_wrapper<const SliceRecord> > Slic3r::SLAPrint::PrintLayer::m_slices private
m_transformed_slices
ExPolygons Slic3r::SLAPrint::PrintLayer::m_transformed_slices private
The documentation for this class was generated from the following file:
src/libslic3r/SLAPrint.hpp