Prusa Slicer: src/PrusaSlicer.cpp File Reference
PrusaSlicer.cpp File Reference
#include <cstdio>
#include <string>
#include <cstring>
#include <iostream>
#include <math.h>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem.hpp>
#include <boost/nowide/args.hpp>
#include <boost/nowide/cenv.hpp>
#include <boost/nowide/iostream.hpp>
#include <boost/nowide/integration/filesystem.hpp>
#include <boost/dll/runtime_symbol_info.hpp>
#include "unix/fhs.hpp"
#include "libslic3r/libslic3r.h"
#include "libslic3r/Config.hpp"
#include "libslic3r/Geometry.hpp"
#include "libslic3r/GCode/PostProcessor.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/ModelArrange.hpp"
#include "libslic3r/Platform.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/SLAPrint.hpp"
#include "libslic3r/TriangleMesh.hpp"
#include "libslic3r/Format/AMF.hpp"
#include "libslic3r/Format/3mf.hpp"
#include "libslic3r/Format/STL.hpp"
#include "libslic3r/Format/OBJ.hpp"
#include "libslic3r/Format/SL1.hpp"
#include "libslic3r/Utils.hpp"
#include "libslic3r/Thread.hpp"
#include "libslic3r/BlacklistedLibraryCheck.hpp"
#include "PrusaSlicer.hpp"
Macros
#define __has_feature(x) 0
Functions
static PrinterTechnology get_printer_technology (const DynamicConfig &config)
int main (int argc, char **argv)
Macro Definition Documentation
__has_feature
#define __has_feature (x) 0
Function Documentation
get_printer_technology()
static PrinterTechnology get_printer_technology (const DynamicConfig & config) static
{
    const ConfigOptionEnum<PrinterTechnology> *opt = config.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
    return (opt == nullptr) ? ptUnknown : opt->value;
}
References Slic3r::ConfigBase::option(), Slic3r::ptUnknown, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::CLI::run().
main()
int main (int argc, char ** argv)
{
    return CLI().run(argc, argv);
}
References Slic3r::CLI::run().