Prusa Slicer: Slic3r::AABBMesh Class Reference
Slic3r::AABBMesh Class Reference
#include <src/libslic3r/AABBMesh.hpp>
Classes
class AABBImpl
class hit_result
Public Member Functions
AABBMesh (const indexed_triangle_set &tmesh, bool calculate_epsilon=false)
AABBMesh (const TriangleMesh &mesh, bool calculate_epsilon=false)
AABBMesh (const AABBMesh &other)
AABBMesh & operator= (const AABBMesh &)
AABBMesh (AABBMesh &&other)
AABBMesh & operator= (AABBMesh &&other)
~AABBMesh ()
const std::vector< Vec3f > & vertices () const
const std::vector< Vec3i > & indices () const
const Vec3f & vertices (size_t idx) const
const Vec3i & indices (size_t idx) const
hit_result query_ray_hit (const Vec3d &s, const Vec3d &dir) const
std::vector< hit_result > query_ray_hits (const Vec3d &s, const Vec3d &dir) const
double squared_distance (const Vec3d &p, int &i, Vec3d &c) const
double squared_distance (const Vec3d &p) const
Vec3d normal_by_face_id (int face_id) const
const indexed_triangle_set * get_triangle_mesh () const
const VertexFaceIndex & vertex_face_index () const
const std::vector< Vec3i > & face_neighbor_index () const
Private Member Functions
template<class M >
void init (const M &mesh, bool calculate_epsilon)
Private Attributes
const indexed_triangle_set * m_tm
std::unique_ptr< AABBImpl > m_aabb
VertexFaceIndex m_vfidx
std::vector< Vec3i > m_fnidx
Detailed Description
Constructor & Destructor Documentation
AABBMesh() [1/4]
Slic3r::AABBMesh::AABBMesh (const indexed_triangle_set & tmesh, bool calculate_epsilon = false) explicit
    : m_tm(&tmesh)
    , m_aabb(new AABBImpl())
    , m_vfidx{tmesh}
    , m_fnidx{its_face_neighbors(tmesh)}
{
    init(tmesh, calculate_epsilon);
}
References init().
AABBMesh() [2/4]
Slic3r::AABBMesh::AABBMesh (const TriangleMesh & mesh, bool calculate_epsilon = false) explicit
    : m_tm(&mesh.its)
    , m_aabb(new AABBImpl())
    , m_vfidx{mesh.its}
    , m_fnidx{its_face_neighbors(mesh.its)}
{
    init(mesh, calculate_epsilon);
}
References init().
AABBMesh() [3/4]
Slic3r::AABBMesh::AABBMesh (const AABBMesh & other)
    : m_tm(other.m_tm)
    , m_aabb(new AABBImpl(*other.m_aabb))
    , m_vfidx{other.m_vfidx}
    , m_fnidx{other.m_fnidx}
{}
AABBMesh() [4/4]
Slic3r::AABBMesh::AABBMesh (AABBMesh && other) default
~AABBMesh()
Slic3r::AABBMesh::~AABBMesh ()
{}
Member Function Documentation
face_neighbor_index()
const std::vector< Vec3i > & Slic3r::AABBMesh::face_neighbor_index () const inline
{ return m_fnidx; }
References m_fnidx.
Referenced by Slic3r::get_normal().
get_triangle_mesh()
const indexed_triangle_set * Slic3r::AABBMesh::get_triangle_mesh () const inline
{ return m_tm; }
References m_tm.
Referenced by Slic3r::sla::create_branching_tree(), Slic3r::sla::create_pad(), and Slic3r::get_normal().
indices() [1/2]
const std::vector< Vec3i > & Slic3r::AABBMesh::indices () const
{
    return m_tm->indices;
}
References indexed_triangle_set::indices, and m_tm.
Referenced by Slic3r::GUI::RaycastManager::first_hit(), Slic3r::get_normal(), and Slic3r::normals().
indices() [2/2]
const Vec3i & Slic3r::AABBMesh::indices (size_t idx) const
{
    return m_tm->indices[idx];
}
References indexed_triangle_set::indices, and m_tm.
init()
template<class M > void Slic3r::AABBMesh::init (const M & mesh, bool calculate_epsilon) private
{
    // Build the AABB accelaration tree
    m_aabb->init(*m_tm, calculate_epsilon);
}
References m_aabb, and m_tm.
Referenced by AABBMesh(), and AABBMesh().
normal_by_face_id()
Vec3d Slic3r::AABBMesh::normal_by_face_id (int face_id) const
{
    return its_unnormalized_normal(*m_tm, face_id).cast<double>().normalized();
}
References Slic3r::its_unnormalized_normal(), and m_tm.
Referenced by Slic3r::get_normal(), query_ray_hit(), and query_ray_hits().
operator=() [1/2]
AABBMesh & Slic3r::AABBMesh::operator= (AABBMesh && other) default
operator=() [2/2]
AABBMesh & Slic3r::AABBMesh::operator= (const AABBMesh & other)
{
    m_tm = other.m_tm;
    m_aabb.reset(new AABBImpl(*other.m_aabb));
    m_vfidx = other.m_vfidx;
    m_fnidx = other.m_fnidx;
    return *this;
}
References m_aabb, m_fnidx, m_tm, and m_vfidx.
query_ray_hit()
AABBMesh::hit_result Slic3r::AABBMesh::query_ray_hit (const Vec3d & s, const Vec3d & dir) const
{
    assert(is_approx(dir.norm(), 1.));
    igl::Hit hit{-1, -1, 0.f, 0.f, 0.f};
    hit.t = std::numeric_limits<float>::infinity();
#ifdef SLIC3R_HOLE_RAYCASTER
    if (! m_holes.empty()) {
        // If there are holes, the hit_results will be made by
        // query_ray_hits (object) and filter_hits (holes):
        return filter_hits(query_ray_hits(s, dir));
    }
#endif
    m_aabb->intersect_ray(*m_tm, s, dir, hit);
    hit_result ret(*this);
    ret.m_t = double(hit.t);
    ret.m_dir = dir;
    ret.m_source = s;
    if(!std::isinf(hit.t) && !std::isnan(hit.t)) {
        ret.m_normal = this->normal_by_face_id(hit.id);
        ret.m_face_id = hit.id;
    }
    return ret;
}
References Slic3r::is_approx(), m_aabb, Slic3r::AABBMesh::hit_result::m_dir, Slic3r::AABBMesh::hit_result::m_face_id, Slic3r::AABBMesh::hit_result::m_normal, Slic3r::AABBMesh::hit_result::m_source, Slic3r::AABBMesh::hit_result::m_t, m_tm, normal_by_face_id(), query_ray_hits(), and igl::Hit::t.
Referenced by Slic3r::GUI::GLGizmoCut3D::PartSelection::PartSelection(), Slic3r::sla::DefaultSupportTree::connect_to_model_body(), and Slic3r::sla::DefaultSupportTree::ray_mesh_intersect().
query_ray_hits()
std::vector< AABBMesh::hit_result > Slic3r::AABBMesh::query_ray_hits (const Vec3d & s, const Vec3d & dir) const
{
    std::vector<AABBMesh::hit_result> outs;
    std::vector<igl::Hit> hits;
    m_aabb->intersect_ray(*m_tm, s, dir, hits);
    // The sort is necessary, the hits are not always sorted.
    std::sort(hits.begin(), hits.end(),
              [](const igl::Hit& a, const igl::Hit& b) { return a.t < b.t; });
    // Remove duplicates. They sometimes appear, for example when the ray is cast
    // along an axis of a cube due to floating-point approximations in igl (?)
    hits.erase(std::unique(hits.begin(), hits.end(),
                           [](const igl::Hit& a, const igl::Hit& b)
                           { return a.t == b.t; }),
               hits.end());
    //  Convert the igl::Hit into hit_result
    outs.reserve(hits.size());
    for (const igl::Hit& hit : hits) {
        outs.emplace_back(AABBMesh::hit_result(*this));
        outs.back().m_t = double(hit.t);
        outs.back().m_dir = dir;
        outs.back().m_source = s;
        if(!std::isinf(hit.t) && !std::isnan(hit.t)) {
            outs.back().m_normal = this->normal_by_face_id(hit.id);
            outs.back().m_face_id = hit.id;
        }
    }
    return outs;
}
References m_aabb, m_tm, and normal_by_face_id().
Referenced by Slic3r::GUI::MeshRaycaster::closest_hit(), Slic3r::GUI::RaycastManager::closest_hit(), Slic3r::GUI::RaycastManager::first_hit(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::GUI::MeshRaycaster::is_valid_intersection(), query_ray_hit(), and Slic3r::GUI::MeshRaycaster::unproject_on_mesh().
squared_distance() [1/2]
double Slic3r::AABBMesh::squared_distance (const Vec3d & p) const inline
    {
        int   i;
        Vec3d c;
        return squared_distance(p, i, c);
    }
References squared_distance().
squared_distance() [2/2]
double Slic3r::AABBMesh::squared_distance (const Vec3d & p, int & i, Vec3d & c) const
{
    double sqdst = 0;
    Eigen::Matrix<double, 1, 3> pp = p;
    Eigen::Matrix<double, 1, 3> cc;
    sqdst = m_aabb->squared_distance(*m_tm, pp, i, cc);
    c = cc;
    return sqdst;
}
References m_aabb, and m_tm.
Referenced by Slic3r::sla::check_ground_route(), Slic3r::GUI::RaycastManager::closest(), Slic3r::sla::create_ground_pillar(), Slic3r::GUI::MeshRaycaster::get_closest_facet(), Slic3r::GUI::MeshRaycaster::get_closest_point(), Slic3r::get_normal(), and squared_distance().
vertex_face_index()
const VertexFaceIndex & Slic3r::AABBMesh::vertex_face_index () const inline
{ return m_vfidx; }
References m_vfidx.
Referenced by Slic3r::get_normal().
vertices() [1/2]
const std::vector< Vec3f > & Slic3r::AABBMesh::vertices () const
{
    return m_tm->vertices;
}
References m_tm, and indexed_triangle_set::vertices.
Referenced by Slic3r::GUI::RaycastManager::first_hit(), Slic3r::get_normal(), and Slic3r::normals().
vertices() [2/2]
const Vec3f & Slic3r::AABBMesh::vertices (size_t idx) const
{
    return m_tm->vertices[idx];
}
References m_tm, and indexed_triangle_set::vertices.
Member Data Documentation
m_aabb
std::unique_ptr<AABBImpl> Slic3r::AABBMesh::m_aabb private
Referenced by init(), operator=(), query_ray_hit(), query_ray_hits(), and squared_distance().
m_fnidx
std::vector<Vec3i> Slic3r::AABBMesh::m_fnidx private
Referenced by face_neighbor_index(), and operator=().
m_tm
const indexed_triangle_set* Slic3r::AABBMesh::m_tm private
Referenced by get_triangle_mesh(), indices(), indices(), init(), normal_by_face_id(), operator=(), query_ray_hit(), query_ray_hits(), squared_distance(), vertices(), and vertices().
m_vfidx
VertexFaceIndex Slic3r::AABBMesh::m_vfidx private
Referenced by operator=(), and vertex_face_index().
The documentation for this class was generated from the following files:
src/libslic3r/AABBMesh.hpp
src/libslic3r/AABBMesh.cpp