Prusa Slicer: Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing > Struct Template Reference
Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing > Struct Template Reference
#include <src/eigen/Eigen/src/Core/Transpose.h>
Static Public Member Functions
static void run (const Derived &dst, const OtherDerived &other)
Detailed Description
template<typename Derived, typename OtherDerived, bool MightHaveTransposeAliasing = check_transpose_aliasing_compile_time_selector <blas_traits<Derived>::IsTransposed,OtherDerived>::ret>
struct Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing >
Member Function Documentation
run()
template<typename Derived , typename OtherDerived , bool MightHaveTransposeAliasing = check_transpose_aliasing_compile_time_selector <blas_traits<Derived>::IsTransposed,OtherDerived>::ret> static void Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing >::run (const Derived & dst, const OtherDerived & other) inline static
    {
        eigen_assert((!check_transpose_aliasing_run_time_selector
                      <typename Derived::Scalar,blas_traits<Derived>::IsTransposed,OtherDerived>
                      ::run(extract_data(dst), other))
          && "aliasing detected during transposition, use transposeInPlace() "
             "or evaluate the rhs into a temporary using .eval()");
    }
References eigen_assert, Eigen::internal::extract_data(), and Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing >::run().
Referenced by Eigen::internal::check_for_aliasing(), and Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing >::run().
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/Transpose.h