Prusa Slicer: igl::geodesic::SurfacePointWithIndex Class Reference
igl::geodesic::SurfacePointWithIndex Class Reference
Public Member Functions
unsigned index ()
void initialize (SurfacePoint &p, unsigned index)
bool operator() (SurfacePointWithIndex *x, SurfacePointWithIndex *y) const
void initialize (SurfacePoint const &p)
PointType type ()
base_pointer & base_element ()
double * xyz ()
double & x ()
double & y ()
double & z ()
void set (double new_x, double new_y, double new_z)
void set (double *data)
double distance (double *v)
double distance (Point3D *v)
void add (Point3D *v)
void multiply (double v)
Protected Attributes
base_pointer m_p
Private Attributes
unsigned m_index
double m_coordinates [3]
Detailed Description
Member Function Documentation
add()
void igl::geodesic::Point3D::add (Point3D * v) inline inherited
  {
    x() += v->x();
    y() += v->y();
    z() += v->z();
  };
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
Referenced by igl::geodesic::SurfacePoint::SurfacePoint().
base_element()
base_pointer & igl::geodesic::SurfacePoint::base_element () inline inherited
{return m_p;};
References igl::geodesic::SurfacePoint::m_p.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::fill_surface_point_double(), igl::geodesic::fill_surface_point_structure(), igl::geodesic::Interval::initialize(), igl::geodesic::GeodesicAlgorithmExact::initialize_propagation_data(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), igl::geodesic::SortedSources::sources(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
distance() [1/2]
double igl::geodesic::Point3D::distance (double * v) inline inherited
  {
    double dx = m_coordinates[0] - v[0];
    double dy = m_coordinates[1] - v[1];
    double dz = m_coordinates[2] - v[2];
    return sqrt(dx*dx + dy*dy + dz*dz);
  };
References igl::geodesic::Point3D::m_coordinates, and sqrt().
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Point3D::distance(), igl::geodesic::Edge::local_coordinates(), igl::geodesic::GeodesicAlgorithmBase::set_stop_conditions(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
distance() [2/2]
double igl::geodesic::Point3D::distance (Point3D * v) inline inherited
  {
    return distance(v->xyz());
  };
References igl::geodesic::Point3D::distance(), and igl::geodesic::Point3D::xyz().
index()
unsigned igl::geodesic::SurfacePointWithIndex::index () inline
{return m_index;};
References m_index.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), and initialize().
initialize() [1/2]
void igl::geodesic::SurfacePointWithIndex::initialize (SurfacePoint & p, unsigned index) inline
  {
    SurfacePoint::initialize(p);
    m_index = index;
  }
References index(), igl::geodesic::SurfacePoint::initialize(), and m_index.
Referenced by igl::geodesic::SortedSources::initialize().
initialize() [2/2]
void igl::geodesic::SurfacePoint::initialize (SurfacePoint const & p) inline inherited
  {
    *this = p;
  }
Referenced by initialize().
multiply()
void igl::geodesic::Point3D::multiply (double v) inline inherited
  {
    x() *= v;
    y() *= v;
    z() *= v;
  };
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
Referenced by igl::geodesic::SurfacePoint::SurfacePoint().
operator()()
bool igl::geodesic::SurfacePointWithIndex::operator() (SurfacePointWithIndex * x, SurfacePointWithIndex * y) const inline
  {
    assert(x->type() != UNDEFINED_POINT && y->type() !=UNDEFINED_POINT);
    if(x->type() != y->type())
    {
      return x->type() < y->type();
    }
    else
    {
      return x->base_element()->id() < y->base_element()->id();
    }
  }
References igl::geodesic::UNDEFINED_POINT, igl::geodesic::Point3D::x(), and igl::geodesic::Point3D::y().
set() [1/2]
void igl::geodesic::Point3D::set (double * data) inline inherited
  {
    x() = *data;
    y() = *(data+1);
    z() = *(data+2);
  }
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
set() [2/2]
void igl::geodesic::Point3D::set (double new_x, double new_y, double new_z) inline inherited
  {
    x() = new_x;
    y() = new_y;
    z() = new_z;
  }
References igl::geodesic::Point3D::x(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
Referenced by igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), and igl::geodesic::fill_surface_point_structure().
type()
PointType igl::geodesic::SurfacePoint::type () inline inherited
{return m_p ? m_p->type() : UNDEFINED_POINT;};
References igl::geodesic::SurfacePoint::m_p, igl::geodesic::MeshElementBase::type(), and igl::geodesic::UNDEFINED_POINT.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::fill_surface_point_double(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
x()
double & igl::geodesic::Point3D::x () inline inherited
{return *m_coordinates;};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::Point3D(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::Point3D::add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Point3D::multiply(), operator()(), igl::geodesic::Point3D::set(), igl::geodesic::Point3D::set(), and igl::geodesic::Mesh::verify().
xyz()
double * igl::geodesic::Point3D::xyz () inline inherited
{return m_coordinates;};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::distance().
y()
double & igl::geodesic::Point3D::y () inline inherited
{return *(m_coordinates+1);};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::Point3D(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::Point3D::add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Point3D::multiply(), operator()(), igl::geodesic::Point3D::set(), igl::geodesic::Point3D::set(), and igl::geodesic::Mesh::verify().
z()
double & igl::geodesic::Point3D::z () inline inherited
{return *(m_coordinates+2);};
References igl::geodesic::Point3D::m_coordinates.
Referenced by igl::geodesic::Point3D::Point3D(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::SurfacePoint::SurfacePoint(), igl::geodesic::Point3D::add(), igl::geodesic::fill_surface_point_double(), igl::geodesic::Mesh::initialize_mesh_data(), igl::geodesic::Point3D::multiply(), igl::geodesic::Point3D::set(), igl::geodesic::Point3D::set(), and igl::geodesic::Mesh::verify().
Member Data Documentation
m_coordinates
double igl::geodesic::Point3D::m_coordinates[3] private inherited
Referenced by igl::geodesic::Point3D::distance(), igl::geodesic::Point3D::x(), igl::geodesic::Point3D::xyz(), igl::geodesic::Point3D::y(), and igl::geodesic::Point3D::z().
m_index
unsigned igl::geodesic::SurfacePointWithIndex::m_index private
Referenced by index(), and initialize().
m_p
base_pointer igl::geodesic::SurfacePoint::m_p protected inherited
Referenced by igl::geodesic::SurfacePoint::base_element(), and igl::geodesic::SurfacePoint::type().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp