Prusa Slicer: Slic3r::GUI::Emboss Namespace Reference
Slic3r::GUI::Emboss Namespace Reference
Classes
class CreateFontStyleImagesJob
Create texture with name of styles written by its style NOTE: Access to glyph cache is possible only from job.
class CreateObjectJob
Create new TextObject on the platter Should not be stopped.
struct CreateSurfaceVolumeData
Hold neccessary data to create(cut) volume from surface object in job.
class CreateSurfaceVolumeJob
Cut surface from object and create cutted volume Should not be stopped.
class CreateVolumeJob
Create new TextVolume on the surface of ModelObject Should not be stopped NOTE: EmbossDataBase::font_file doesn't have to be valid !!!
struct DataBase
Base data holder for embossing.
struct DataCreateObject
Hold neccessary data to create ModelObject in job Object is placed on bed under screen coor OR to center of scene when it is out of bed shape.
struct DataCreateVolume
Hold neccessary data to create ModelVolume in job Volume is created on the surface of existing volume in object. NOTE: EmbossDataBase::font_file doesn't have to be valid !!!
struct DataUpdate
Hold neccessary data to update embossed text object in job.
class StyleManager
Manage Emboss text styles Cache actual state of style.
struct SurfaceVolumeData
class UpdateJob
Update text shape in existing text volume Predict that there is only one runnig(not canceled) instance of it.
struct UpdateSurfaceVolumeData
Hold neccessary data to update embossed text object in job.
class UpdateSurfaceVolumeJob
Update text volume to use surface from object.
Functions
SurfaceVolumeData::ModelSources create_sources (const ModelVolumePtrs &volumes, std::optional< size_t > text_volume_id={})
Copied triangles from object to be able create mesh for cut surface from.
SurfaceVolumeData::ModelSources create_volume_sources (const ModelVolume *text_volume)
Copied triangles from object to be able create mesh for cut surface from.
Function Documentation
create_sources()
SurfaceVolumeData::ModelSources Slic3r::GUI::Emboss::create_sources (const ModelVolumePtrs & volumes, std::optional< size_t > text_volume_id = {})
Copied triangles from object to be able create mesh for cut surface from.
Parameters
volumes Source object volumes for cut surface from
text_volume_id Source volume id
Returns
Source data for cut surface from
{
    SurfaceVolumeData::ModelSources result;
    result.reserve(volumes.size() - 1);
    for (const ModelVolume *v : volumes) {
        if (text_volume_id.has_value() && v->id().id == *text_volume_id) continue;
        // skip modifiers and negative volumes, ...
        if (!v->is_model_part()) continue;
        const TriangleMesh &tm = v->mesh();
        if (tm.empty()) continue;
        if (tm.its.empty()) continue;
        result.push_back({v->get_mesh_shared_ptr(), v->get_matrix()});
    }
    return result;
}
References indexed_triangle_set::empty(), Slic3r::TriangleMesh::empty(), and Slic3r::TriangleMesh::its.
Referenced by create_volume_sources(), and priv::start_create_volume_job().
create_volume_sources()
SurfaceVolumeData::ModelSources Slic3r::GUI::Emboss::create_volume_sources (const ModelVolume * text_volume)
Copied triangles from object to be able create mesh for cut surface from.
Parameters
text_volume Define text in object
Returns
Source data for cut surface from
{
    if (text_volume == nullptr) return {};
    if (!text_volume->text_configuration.has_value()) return {};
    const ModelVolumePtrs &volumes = text_volume->get_object()->volumes;
    // no other volume in object
    if (volumes.size() <= 1) return {};
    return create_sources(volumes, text_volume->id().id);
}
References create_sources(), Slic3r::ModelVolume::get_object(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), Slic3r::ModelVolume::text_configuration, and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::GLGizmoEmboss::process().