Prusa Slicer: libnest2d::opt::DummyOptimizer< T > Class Template Reference
libnest2d::opt::DummyOptimizer< T > Class Template Reference
#include <src/libnest2d/include/libnest2d/optimizer.hpp>
Public Member Functions
DummyOptimizer ()
DummyOptimizer (const StopCriteria &)
template<class Func , class... Args>
Result< Args... > optimize (Func &&, tuple< Args... >, Bound< Args >...)
template<class Func , class... Args>
Result< Args... > optimize_min (Func &&objectfunction, Input< Args... > initvals, Bound< Args >... bounds)
Optimize for minimum value of the provided objectfunction.
template<class Func , class... Args>
Result< Args... > optimize_min (Func &&objectfunction, Input< Args... > initvals)
template<class... Args, class Func >
Result< Args... > optimize_min (Func &&objectfunction)
template<class Func , class... Args>
Result< Args... > optimize_max (Func &&objectfunction, Input< Args... > initvals, Bound< Args >... bounds)
Same as optimize_min but optimizes for maximum function value.
template<class Func , class... Args>
Result< Args... > optimize_max (Func &&objectfunction, Input< Args... > initvals)
template<class... Args, class Func >
Result< Args... > optimize_max (Func &&objectfunction)
Protected Types
enum class OptDir { MIN , MAX }
Protected Attributes
enum libnest2d::opt::Optimizer::OptDir dir_
StopCriteria stopcr_
Friends
class Optimizer< DummyOptimizer< T > >
Detailed Description
template<class T = void>
class libnest2d::opt::DummyOptimizer< T >
Member Enumeration Documentation
OptDir
template<class Subclass > enum class libnest2d::opt::Optimizer::OptDir strong protected inherited
Enumerator
MIN
MAX
                     {
        MIN,
        MAX
    } dir_;
Constructor & Destructor Documentation
DummyOptimizer() [1/2]
template<class T = void> libnest2d::opt::DummyOptimizer< T >::DummyOptimizer () inline
                     {
        static_assert(always_false<T>::value, "Optimizer unimplemented!");
    }
DummyOptimizer() [2/2]
template<class T = void> libnest2d::opt::DummyOptimizer< T >::DummyOptimizer (const StopCriteria &) inline
{
        static_assert(always_false<T>::value, "Optimizer unimplemented!");
    }
Member Function Documentation
optimize()
template<class T = void> template<class Func , class... Args> Result< Args... > libnest2d::opt::DummyOptimizer< T >::optimize (Func && , tuple< Args... > , Bound< Args > ...) inline
    {
        return Result<Args...>();
    }
optimize_max() [1/3]
template<class Subclass > template<class... Args, class Func > Result< Args... > libnest2d::opt::Optimizer< Subclass >::optimize_max (Func && objectfunction) inline inherited
    {
        dir_ = OptDir::MAX;
        return static_cast<Subclass*>(this)->template optimize<Func, Args...>(
                    forward<Func>(objectfunction),
                    Input<Args...>(),
                    Bound<Args>()... );
    }
References libnest2d::opt::Optimizer< Subclass >::dir_, and libnest2d::opt::Optimizer< Subclass >::MAX.
optimize_max() [2/3]
template<class Subclass > template<class Func , class... Args> Result< Args... > libnest2d::opt::Optimizer< Subclass >::optimize_max (Func && objectfunction, Input< Args... > initvals) inline inherited
    {
        dir_ = OptDir::MAX;
        return static_cast<Subclass*>(this)->template optimize<Func, Args...>(
                    forward<Func>(objectfunction), initvals, Bound<Args>()... );
    }
References libnest2d::opt::Optimizer< Subclass >::dir_, libnest2d::opt::initvals(), and libnest2d::opt::Optimizer< Subclass >::MAX.
optimize_max() [3/3]
template<class Subclass > template<class Func , class... Args> Result< Args... > libnest2d::opt::Optimizer< Subclass >::optimize_max (Func && objectfunction, Input< Args... > initvals, Bound< Args >... bounds) inline inherited
Same as optimize_min but optimizes for maximum function value.
    {
        dir_ = OptDir::MAX;
        return static_cast<Subclass*>(this)->template optimize<Func, Args...>(
                    forward<Func>(objectfunction), initvals, bounds... );
    }
References libnest2d::opt::Optimizer< Subclass >::dir_, libnest2d::opt::initvals(), and libnest2d::opt::Optimizer< Subclass >::MAX.
optimize_min() [1/3]
template<class Subclass > template<class... Args, class Func > Result< Args... > libnest2d::opt::Optimizer< Subclass >::optimize_min (Func && objectfunction) inline inherited
    {
        dir_ = OptDir::MIN;
        return static_cast<Subclass*>(this)->template optimize<Func, Args...>(
                    forward<Func>(objectfunction),
                    Input<Args...>(),
                    Bound<Args>()... );
    }
References libnest2d::opt::Optimizer< Subclass >::dir_, and libnest2d::opt::Optimizer< Subclass >::MIN.
optimize_min() [2/3]
template<class Subclass > template<class Func , class... Args> Result< Args... > libnest2d::opt::Optimizer< Subclass >::optimize_min (Func && objectfunction, Input< Args... > initvals) inline inherited
    {
        dir_ = OptDir::MIN;
        return static_cast<Subclass*>(this)->template optimize<Func, Args...>(
                    forward<Func>(objectfunction), initvals, Bound<Args>()... );
    }
References libnest2d::opt::Optimizer< Subclass >::dir_, libnest2d::opt::initvals(), and libnest2d::opt::Optimizer< Subclass >::MIN.
optimize_min() [3/3]
template<class Subclass > template<class Func , class... Args> Result< Args... > libnest2d::opt::Optimizer< Subclass >::optimize_min (Func && objectfunction, Input< Args... > initvals, Bound< Args >... bounds) inline inherited
Optimize for minimum value of the provided objectfunction.
Parameters
objectfunction The function that will be searched for the minimum return value.
initvals A tuple with the initial values for the search
bounds A parameter pack with the bounds for each dimension.
Returns
Returns a Result<Args...> structure. An example call would be: auto result = opt.optimize_min([](tuple<double> x) // object function { return std::pow(std::get<0>(x), 2); }, make_tuple(-0.5), // initial value {-1.0, 1.0} // search space bounds);
    {
        dir_ = OptDir::MIN;
        return static_cast<Subclass*>(this)->template optimize<Func, Args...>(
                    forward<Func>(objectfunction), initvals, bounds... );
    }
References libnest2d::opt::Optimizer< Subclass >::dir_, libnest2d::opt::initvals(), and libnest2d::opt::Optimizer< Subclass >::MIN.
Friends And Related Symbol Documentation
Optimizer< DummyOptimizer< T > >
template<class T = void> friend class Optimizer< DummyOptimizer< T > > friend
Member Data Documentation
dir_
template<class Subclass > enum libnest2d::opt::Optimizer::OptDir libnest2d::opt::Optimizer< Subclass >::dir_ protected inherited
Referenced by libnest2d::opt::Optimizer< Subclass >::optimize_max(), libnest2d::opt::Optimizer< Subclass >::optimize_max(), libnest2d::opt::Optimizer< Subclass >::optimize_max(), libnest2d::opt::Optimizer< Subclass >::optimize_min(), libnest2d::opt::Optimizer< Subclass >::optimize_min(), and libnest2d::opt::Optimizer< Subclass >::optimize_min().
stopcr_
template<class Subclass > StopCriteria libnest2d::opt::Optimizer< Subclass >::stopcr_ protected inherited
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/optimizer.hpp