Prusa Slicer: Slic3r::GUI::OpenGLManager::GLInfo Class Reference
Slic3r::GUI::OpenGLManager::GLInfo Class Reference
#include <src/slic3r/GUI/OpenGLManager.hpp>
Public Member Functions
GLInfo ()=default
const std::string & get_version_string () const
const std::string & get_glsl_version_string () const
const std::string & get_vendor () const
const std::string & get_renderer () const
bool is_core_profile () const
void set_core_profile (bool value)
bool is_mesa () const
bool is_es () const
int get_max_tex_size () const
float get_max_anisotropy () const
bool is_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
bool is_glsl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
std::string to_string (bool for_github) const
Private Member Functions
void detect () const
Private Attributes
bool m_detected { false }
bool m_core_profile { false }
int m_max_tex_size { 0 }
float m_max_anisotropy { 0.0f }
std::string m_version_string
Semver m_version = Semver::invalid()
bool m_version_is_mesa = false
std::string m_glsl_version_string
Semver m_glsl_version = Semver::invalid()
std::string m_vendor
std::string m_renderer
Detailed Description
Constructor & Destructor Documentation
GLInfo()
Slic3r::GUI::OpenGLManager::GLInfo::GLInfo () default
Member Function Documentation
detect()
void Slic3r::GUI::OpenGLManager::GLInfo::detect () const private
{
    *const_cast<std::string*>(&m_version_string) = gl_get_string_safe(GL_VERSION, "N/A");
    *const_cast<std::string*>(&m_glsl_version_string) = gl_get_string_safe(GL_SHADING_LANGUAGE_VERSION, "N/A");
    *const_cast<std::string*>(&m_vendor)       = gl_get_string_safe(GL_VENDOR, "N/A");
    *const_cast<std::string*>(&m_renderer)     = gl_get_string_safe(GL_RENDERER, "N/A");
    *const_cast<Semver*>(&m_version)       = parse_version_string(m_version_string);
    *const_cast<bool*>(&m_version_is_mesa) = boost::icontains(m_version_string, "mesa");
    *const_cast<Semver*>(&m_glsl_version)  = parse_version_string(m_glsl_version_string);
    int* max_tex_size = const_cast<int*>(&m_max_tex_size);
    glsafe(::glGetIntegerv(GL_MAX_TEXTURE_SIZE, max_tex_size));
    *max_tex_size /= 2;
    if (Slic3r::total_physical_memory() / (1024 * 1024 * 1024) < 6)
        *max_tex_size /= 2;
    if (GLEW_EXT_texture_filter_anisotropic) {
        float* max_anisotropy = const_cast<float*>(&m_max_anisotropy);
        glsafe(::glGetFloatv(GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT, max_anisotropy));
    }
    *const_cast<bool*>(&m_detected) = true;
}
References Slic3r::GUI::gl_get_string_safe(), glsafe, Slic3r::GUI::parse_version_string(), and Slic3r::total_physical_memory().
Referenced by get_version_string().
get_glsl_version_string()
const std::string & Slic3r::GUI::OpenGLManager::GLInfo::get_glsl_version_string () const
{
    if (!m_detected)
        detect();
    return m_glsl_version_string;
}
Referenced by Slic3r::GUI::generate_system_info_json().
get_max_anisotropy()
float Slic3r::GUI::OpenGLManager::GLInfo::get_max_anisotropy () const
{
    if (!m_detected)
        detect();
    return m_max_anisotropy;
}
Referenced by Slic3r::GUI::GLTexture::load_from_png(), and Slic3r::GUI::GLTexture::load_from_svg().
get_max_tex_size()
int Slic3r::GUI::OpenGLManager::GLInfo::get_max_tex_size () const
{
    if (!m_detected)
        detect();
    // clamp to avoid the texture generation become too slow and use too much GPU memory
#ifdef __APPLE__
    // and use smaller texture for non retina systems
    return (Slic3r::GUI::mac_max_scaling_factor() > 1.0) ? std::min(m_max_tex_size, 8192) : std::min(m_max_tex_size / 2, 4096);
#else
    // and use smaller texture for older OpenGL versions
    return is_version_greater_or_equal_to(3, 0) ? std::min(m_max_tex_size, 8192) : std::min(m_max_tex_size / 2, 4096);
#endif // __APPLE__
}
References Slic3r::GUI::mac_max_scaling_factor().
Referenced by Slic3r::GUI::Bed3D::render_texture().
get_renderer()
const std::string & Slic3r::GUI::OpenGLManager::GLInfo::get_renderer () const
{
    if (!m_detected)
        detect();
    return m_renderer;
}
Referenced by Slic3r::GUI::generate_system_info_json(), and Slic3r::GUI::OpenGLManager::init_gl().
get_vendor()
const std::string & Slic3r::GUI::OpenGLManager::GLInfo::get_vendor () const
{
    if (!m_detected)
        detect();
    return m_vendor;
}
Referenced by Slic3r::GUI::generate_system_info_json(), and Slic3r::GUI::OpenGLManager::init_gl().
get_version_string()
const std::string & Slic3r::GUI::OpenGLManager::GLInfo::get_version_string () const
{
    if (!m_detected)
        detect();
    return m_version_string;
}
References detect(), m_detected, and m_version_string.
Referenced by Slic3r::GUI::generate_system_info_json(), and Slic3r::GUI::OpenGLManager::init_gl().
is_core_profile()
bool Slic3r::GUI::OpenGLManager::GLInfo::is_core_profile () const inline
{ return m_core_profile; }
References m_core_profile.
Referenced by Slic3r::GUI::OpenGLManager::init_gl(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GLVolumeCollection::render(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoCut3D::render_line(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), and Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping().
is_es()
bool Slic3r::GUI::OpenGLManager::GLInfo::is_es () const inline
{
            return
#if ENABLE_OPENGL_ES
                true;
#else
                false;
#endif // ENABLE_OPENGL_ES
        }
is_glsl_version_greater_or_equal_to()
bool Slic3r::GUI::OpenGLManager::GLInfo::is_glsl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
{
    if (!m_detected)
        detect();
    return m_glsl_version >= Semver(major, minor, 0);
}
Referenced by Slic3r::GUI::GUI_App::is_glsl_version_greater_or_equal_to().
is_mesa()
bool Slic3r::GUI::OpenGLManager::GLInfo::is_mesa () const
{
    return m_version_is_mesa;
}
is_version_greater_or_equal_to()
bool Slic3r::GUI::OpenGLManager::GLInfo::is_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
{
    if (!m_detected)
        detect();
    return m_version >= Semver(major, minor, 0);
}
Referenced by Slic3r::GUI::OpenGLManager::init_gl(), Slic3r::GUI::GUI_App::is_gl_version_greater_or_equal_to(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), Slic3r::GUI::ImGuiWrapper::render_draw_data(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
set_core_profile()
void Slic3r::GUI::OpenGLManager::GLInfo::set_core_profile (bool value) inline
{ m_core_profile = value; }
References m_core_profile.
Referenced by Slic3r::GUI::OpenGLManager::init_glcontext().
to_string()
std::string Slic3r::GUI::OpenGLManager::GLInfo::to_string (bool for_github) const
{
    if (!m_detected)
        detect();
    std::stringstream out;
    const bool format_as_html = ! for_github;
    std::string h2_start = format_as_html ? "<b>" : "";
    std::string h2_end = format_as_html ? "</b>" : "";
    std::string b_start = format_as_html ? "<b>" : "";
    std::string b_end = format_as_html ? "</b>" : "";
    std::string line_end = format_as_html ? "<br>" : "\n";
    out << h2_start << "OpenGL installation" << h2_end << line_end;
    out << b_start << "GL version:   " << b_end << m_version << line_end;
#if ENABLE_GL_CORE_PROFILE
    out << b_start << "Profile:      " << b_end << (is_core_profile() ? "Core" : "Compatibility") << line_end;
#endif // ENABLE_GL_CORE_PROFILE
    out << b_start << "Vendor:       " << b_end << m_vendor << line_end;
    out << b_start << "Renderer:     " << b_end << m_renderer << line_end;
    out << b_start << "GLSL version: " << b_end << m_glsl_version << line_end;
    out << b_start << "Textures compression:       " << b_end << (are_compressed_textures_supported() ? "Enabled" : "Disabled") << line_end;
    {
#if ENABLE_GL_CORE_PROFILE
        std::vector<std::string>  extensions_list = get_extensions_list();
#else
        const std::string extensions_str = gl_get_string_safe(GL_EXTENSIONS, "");
        std::vector<std::string> extensions_list;
        boost::split(extensions_list, extensions_str, boost::is_any_of(" "), boost::token_compress_on);
#endif // ENABLE_GL_CORE_PROFILE
        if (!extensions_list.empty()) {
            if (for_github)
                out << "<details>\n<summary>Installed extensions:</summary>\n";
            else
                out << h2_start << "Installed extensions:" << h2_end << line_end;
            std::sort(extensions_list.begin(), extensions_list.end());
            for (const std::string& ext : extensions_list)
                if (! ext.empty())
                    out << ext << line_end;
            if (for_github)
                out << "</details>\n";
        }
    }
    return out.str();
}
References Slic3r::GUI::OpenGLManager::are_compressed_textures_supported(), and Slic3r::GUI::gl_get_string_safe().
Referenced by Slic3r::GUI::GUI_App::get_gl_info().
Member Data Documentation
m_core_profile
bool Slic3r::GUI::OpenGLManager::GLInfo::m_core_profile { false } private
Referenced by is_core_profile(), and set_core_profile().
m_detected
bool Slic3r::GUI::OpenGLManager::GLInfo::m_detected { false } private
Referenced by get_version_string().
m_glsl_version
Semver Slic3r::GUI::OpenGLManager::GLInfo::m_glsl_version = Semver::invalid() private
m_glsl_version_string
std::string Slic3r::GUI::OpenGLManager::GLInfo::m_glsl_version_string private
m_max_anisotropy
float Slic3r::GUI::OpenGLManager::GLInfo::m_max_anisotropy { 0.0f } private
m_max_tex_size
int Slic3r::GUI::OpenGLManager::GLInfo::m_max_tex_size { 0 } private
m_renderer
std::string Slic3r::GUI::OpenGLManager::GLInfo::m_renderer private
m_vendor
std::string Slic3r::GUI::OpenGLManager::GLInfo::m_vendor private
m_version
Semver Slic3r::GUI::OpenGLManager::GLInfo::m_version = Semver::invalid() private
m_version_is_mesa
bool Slic3r::GUI::OpenGLManager::GLInfo::m_version_is_mesa = false private
m_version_string
std::string Slic3r::GUI::OpenGLManager::GLInfo::m_version_string private
Referenced by get_version_string().
The documentation for this class was generated from the following files:
src/slic3r/GUI/OpenGLManager.hpp
src/slic3r/GUI/OpenGLManager.cpp