Prusa Slicer: Slic3r::ColorRGBA Class Reference
Slic3r::ColorRGBA Class Reference
#include <src/libslic3r/Color.hpp>
Public Member Functions
ColorRGBA ()=default
ColorRGBA (float r, float g, float b, float a)
ColorRGBA (unsigned char r, unsigned char g, unsigned char b, unsigned char a)
ColorRGBA (const ColorRGBA &other)=default
ColorRGBA & operator= (const ColorRGBA &other)
bool operator== (const ColorRGBA &other) const
bool operator!= (const ColorRGBA &other) const
bool operator< (const ColorRGBA &other) const
bool operator> (const ColorRGBA &other) const
ColorRGBA operator+ (const ColorRGBA &other) const
ColorRGBA operator* (float value) const
const float *const data () const
float r () const
float g () const
float b () const
float a () const
void r (float r)
void g (float g)
void b (float b)
void a (float a)
void set (unsigned int comp, float value)
unsigned char r_uchar () const
unsigned char g_uchar () const
unsigned char b_uchar () const
unsigned char a_uchar () const
bool is_transparent () const
Static Public Member Functions
static const ColorRGBA BLACK ()
static const ColorRGBA BLUE ()
static const ColorRGBA BLUEISH ()
static const ColorRGBA CYAN ()
static const ColorRGBA DARK_GRAY ()
static const ColorRGBA DARK_YELLOW ()
static const ColorRGBA GRAY ()
static const ColorRGBA GREEN ()
static const ColorRGBA GREENISH ()
static const ColorRGBA LIGHT_GRAY ()
static const ColorRGBA MAGENTA ()
static const ColorRGBA ORANGE ()
static const ColorRGBA RED ()
static const ColorRGBA REDISH ()
static const ColorRGBA YELLOW ()
static const ColorRGBA WHITE ()
static const ColorRGBA X ()
static const ColorRGBA Y ()
static const ColorRGBA Z ()
Private Attributes
std::array< float, 4 > m_data { 1.0f, 1.0f, 1.0f, 1.0f }
Detailed Description
Constructor & Destructor Documentation
ColorRGBA() [1/4]
Slic3r::ColorRGBA::ColorRGBA () default
ColorRGBA() [2/4]
Slic3r::ColorRGBA::ColorRGBA (float r, float g, float b, float a)
: m_data({ std::clamp(r, 0.0f, 1.0f), std::clamp(g, 0.0f, 1.0f), std::clamp(b, 0.0f, 1.0f), std::clamp(a, 0.0f, 1.0f) })
{
}
References a(), b(), g(), and r().
ColorRGBA() [3/4]
Slic3r::ColorRGBA::ColorRGBA (unsigned char r, unsigned char g, unsigned char b, unsigned char a)
: m_data({ std::clamp(r * INV_255, 0.0f, 1.0f), std::clamp(g * INV_255, 0.0f, 1.0f), std::clamp(b * INV_255, 0.0f, 1.0f), std::clamp(a * INV_255, 0.0f, 1.0f) })
{
}
References a(), b(), g(), INV_255, and r().
ColorRGBA() [4/4]
Slic3r::ColorRGBA::ColorRGBA (const ColorRGBA & other) default
Member Function Documentation
a() [1/2]
float Slic3r::ColorRGBA::a () const inline
{ return m_data[3]; }
References m_data.
Referenced by ColorRGBA(), ColorRGBA(), a(), Slic3r::color_from_model_volume(), Slic3r::complementary(), Slic3r::decode_color(), Slic3r::GUI::GLGizmoMmuSegmentation::get_cursor_sphere_left_button_color(), Slic3r::GUI::GLGizmoMmuSegmentation::get_cursor_sphere_right_button_color(), Slic3r::saturate(), Slic3r::GLVolume::set_render_color(), Slic3r::GUI::ImGuiWrapper::to_ImU32(), and Slic3r::GUI::ImGuiWrapper::to_ImVec4().
a() [2/2]
void Slic3r::ColorRGBA::a (float a) inline
{ m_data[3] = std::clamp(a, 0.0f, 1.0f); }
References a(), and m_data.
a_uchar()
unsigned char Slic3r::ColorRGBA::a_uchar () const inline
{ return static_cast<unsigned char>(m_data[3] * 255.0f); }
References m_data.
b() [1/2]
float Slic3r::ColorRGBA::b () const inline
{ return m_data[2]; }
References m_data.
Referenced by ColorRGBA(), ColorRGBA(), b(), Slic3r::complementary(), Slic3r::GUI::ImGuiWrapper::to_ImU32(), Slic3r::GUI::ImGuiWrapper::to_ImVec4(), and Slic3r::to_rgb().
b() [2/2]
void Slic3r::ColorRGBA::b (float b) inline
{ m_data[2] = std::clamp(b, 0.0f, 1.0f); }
References b(), and m_data.
b_uchar()
unsigned char Slic3r::ColorRGBA::b_uchar () const inline
{ return static_cast<unsigned char>(m_data[2] * 255.0f); }
References m_data.
BLACK()
static const ColorRGBA Slic3r::ColorRGBA::BLACK () inline static
{ return { 0.0f, 0.0f, 0.0f, 1.0f }; }
Referenced by Slic3r::decode_colors(), Slic3r::GUI::GCodeViewer::render_legend(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile().
BLUE()
static const ColorRGBA Slic3r::ColorRGBA::BLUE () inline static
{ return { 0.0f, 0.0f, 1.0f, 1.0f }; }
Referenced by Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile().
BLUEISH()
static const ColorRGBA Slic3r::ColorRGBA::BLUEISH () inline static
{ return { 0.5f, 0.5f, 1.0f, 1.0f }; }
CYAN()
static const ColorRGBA Slic3r::ColorRGBA::CYAN () inline static
{ return { 0.0f, 1.0f, 1.0f, 1.0f }; }
Referenced by Slic3r::GUI::GLGizmoHollow::render_points().
DARK_GRAY()
static const ColorRGBA Slic3r::ColorRGBA::DARK_GRAY () inline static
{ return { 0.25f, 0.25f, 0.25f, 1.0f }; }
DARK_YELLOW()
static const ColorRGBA Slic3r::ColorRGBA::DARK_YELLOW () inline static
{ return { 0.5f, 0.5f, 0.0f, 1.0f }; }
Referenced by Slic3r::GLVolumeCollection::load_wipe_tower_preview().
data()
const float *const Slic3r::ColorRGBA::data () const inline
{ return m_data.data(); }
References m_data.
Referenced by Slic3r::GLShaderProgram::set_uniform().
g() [1/2]
float Slic3r::ColorRGBA::g () const inline
{ return m_data[1]; }
References m_data.
Referenced by ColorRGBA(), ColorRGBA(), Slic3r::complementary(), g(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::ImGuiWrapper::to_ImU32(), Slic3r::GUI::ImGuiWrapper::to_ImVec4(), and Slic3r::to_rgb().
g() [2/2]
void Slic3r::ColorRGBA::g (float g) inline
{ m_data[1] = std::clamp(g, 0.0f, 1.0f); }
References g(), and m_data.
g_uchar()
unsigned char Slic3r::ColorRGBA::g_uchar () const inline
{ return static_cast<unsigned char>(m_data[1] * 255.0f); }
References m_data.
GRAY()
static const ColorRGBA Slic3r::ColorRGBA::GRAY () inline static
{ return { 0.5f, 0.5f, 0.5f, 1.0f }; }
Referenced by Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), and Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers().
GREEN()
static const ColorRGBA Slic3r::ColorRGBA::GREEN () inline static
{ return { 0.0f, 1.0f, 0.0f, 1.0f }; }
Referenced by Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers().
GREENISH()
static const ColorRGBA Slic3r::ColorRGBA::GREENISH () inline static
{ return { 0.5f, 1.0f, 0.5f, 1.0f }; }
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths().
is_transparent()
bool Slic3r::ColorRGBA::is_transparent () const inline
{ return m_data[3] < 1.0f; }
References m_data.
LIGHT_GRAY()
static const ColorRGBA Slic3r::ColorRGBA::LIGHT_GRAY () inline static
{ return { 0.75f, 0.75f, 0.75f, 1.0f }; }
Referenced by Slic3r::GUI::GLGizmoMeasure::render_dimensioning().
MAGENTA()
static const ColorRGBA Slic3r::ColorRGBA::MAGENTA () inline static
{ return { 1.0f, 0.0f, 1.0f, 1.0f }; }
operator!=()
bool Slic3r::ColorRGBA::operator!= (const ColorRGBA & other) const inline
{ return !operator==(other); }
References operator==().
operator*()
ColorRGBA Slic3r::ColorRGBA::operator* (float value) const
{
  assert(value >= 0.0f);
  ColorRGBA ret;
  for (size_t i = 0; i < 3; ++i) {
    ret.m_data[i] = std::clamp(value * m_data[i], 0.0f, 1.0f);
  }
  ret.m_data[3] = m_data[3];
  return ret;
}
References m_data.
operator+()
ColorRGBA Slic3r::ColorRGBA::operator+ (const ColorRGBA & other) const
{
  ColorRGBA ret;
  for (size_t i = 0; i < 3; ++i) {
    ret.m_data[i] = std::clamp(m_data[i] + other.m_data[i], 0.0f, 1.0f);
  }
  return ret;
}
References m_data.
operator<()
bool Slic3r::ColorRGBA::operator< (const ColorRGBA & other) const
{
  for (size_t i = 0; i < 3; ++i) {
    if (m_data[i] < other.m_data[i])
      return true;
    else if (m_data[i] > other.m_data[i])
      return false;
  }
  return false;
}
References m_data.
operator=()
ColorRGBA & Slic3r::ColorRGBA::operator= (const ColorRGBA & other) inline
{ m_data = other.m_data; return *this; }
References m_data.
operator==()
bool Slic3r::ColorRGBA::operator== (const ColorRGBA & other) const inline
{ return m_data == other.m_data; }
References m_data.
Referenced by operator!=().
operator>()
bool Slic3r::ColorRGBA::operator> (const ColorRGBA & other) const
{
  for (size_t i = 0; i < 3; ++i) {
    if (m_data[i] > other.m_data[i])
      return true;
    else if (m_data[i] < other.m_data[i])
      return false;
  }
  return false;
}
References m_data.
ORANGE()
static const ColorRGBA Slic3r::ColorRGBA::ORANGE () inline static
{ return { 0.923f, 0.504f, 0.264f, 1.0f }; }
r() [1/2]
float Slic3r::ColorRGBA::r () const inline
{ return m_data[0]; }
References m_data.
Referenced by ColorRGBA(), ColorRGBA(), Slic3r::complementary(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), r(), Slic3r::GUI::ImGuiWrapper::to_ImU32(), Slic3r::GUI::ImGuiWrapper::to_ImVec4(), and Slic3r::to_rgb().
r() [2/2]
void Slic3r::ColorRGBA::r (float r) inline
{ m_data[0] = std::clamp(r, 0.0f, 1.0f); }
References m_data, and r().
r_uchar()
unsigned char Slic3r::ColorRGBA::r_uchar () const inline
{ return static_cast<unsigned char>(m_data[0] * 255.0f); }
References m_data.
RED()
static const ColorRGBA Slic3r::ColorRGBA::RED () inline static
{ return { 1.0f, 0.0f, 0.0f, 1.0f }; }
Referenced by Slic3r::GUI::GLGizmoCut3D::render_cut_plane_grabbers().
REDISH()
static const ColorRGBA Slic3r::ColorRGBA::REDISH () inline static
{ return { 1.0f, 0.5f, 0.5f, 1.0f }; }
set()
void Slic3r::ColorRGBA::set (unsigned int comp, float value) inline
{
    assert(0 <= comp && comp <= 3);
    m_data[comp] = std::clamp(value, 0.0f, 1.0f);
  }
References m_data.
WHITE()
static const ColorRGBA Slic3r::ColorRGBA::WHITE () inline static
{ return { 1.0f, 1.0f, 1.0f, 1.0f }; }
Referenced by Slic3r::GUI::init_from_circle(), Slic3r::GUI::init_from_scale(), Slic3r::GUI::init_from_snap_radii(), Slic3r::GUI::GLGizmoCut3D::init_rendering_items(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GCodeViewer::render_legend(), Slic3r::GLVolume::SinkingContours::update(), and Slic3r::GUI::TriangleSelectorGUI::update_paint_contour().
X()
static const ColorRGBA Slic3r::ColorRGBA::X () inline static
{ return { 0.75f, 0.0f, 0.0f, 1.0f }; }
Referenced by Slic3r::GUI::CoordAxes::render().
Y()
static const ColorRGBA Slic3r::ColorRGBA::Y () inline static
{ return { 0.0f, 0.75f, 0.0f, 1.0f }; }
Referenced by Slic3r::GUI::CoordAxes::render().
YELLOW()
static const ColorRGBA Slic3r::ColorRGBA::YELLOW () inline static
{ return { 1.0f, 1.0f, 0.0f, 1.0f }; }
Referenced by Slic3r::GUI::SceneRaycaster::SceneRaycaster().
Z()
static const ColorRGBA Slic3r::ColorRGBA::Z () inline static
{ return { 0.0f, 0.0f, 0.75f, 1.0f }; }
Referenced by Slic3r::GUI::CoordAxes::render().
Member Data Documentation
m_data
std::array<float, 4> Slic3r::ColorRGBA::m_data { 1.0f, 1.0f, 1.0f, 1.0f } private
Referenced by a(), a(), a_uchar(), b(), b(), b_uchar(), data(), g(), g(), g_uchar(), is_transparent(), operator*(), operator+(), operator<(), operator=(), operator==(), operator>(), r(), r(), r_uchar(), and set().
The documentation for this class was generated from the following files:
src/libslic3r/Color.hpp
src/libslic3r/Color.cpp