Prusa Slicer: Slic3r::GUI::GLTexture::Compressor Class Reference
Slic3r::GUI::GLTexture::Compressor Class Reference
Classes
struct Level
Public Member Functions
Compressor (GLTexture &texture)
~Compressor ()
void reset ()
void add_level (unsigned int w, unsigned int h, const std::vector< unsigned char > &data)
void start_compressing ()
bool unsent_compressed_data_available () const
void send_compressed_data_to_gpu ()
bool all_compressed_data_sent_to_gpu () const
Private Member Functions
void compress ()
Private Attributes
GLTexture & m_texture
std::vector< Level > m_levels
std::thread m_thread
std::atomic< bool > m_abort_compressing
std::atomic< unsigned int > m_num_levels_compressed
Detailed Description
Constructor & Destructor Documentation
Compressor()
Slic3r::GUI::GLTexture::Compressor::Compressor (GLTexture & texture) inline explicit
: m_texture(texture), m_abort_compressing(false), m_num_levels_compressed(0) {}
~Compressor()
Slic3r::GUI::GLTexture::Compressor::~Compressor () inline
{ reset(); }
References reset().
Member Function Documentation
add_level()
void Slic3r::GUI::GLTexture::Compressor::add_level (unsigned int w, unsigned int h, const std::vector< unsigned char > & data) inline
{ m_levels.emplace_back(w, h, data); }
References m_levels.
Referenced by Slic3r::GUI::GLTexture::load_from_png(), and Slic3r::GUI::GLTexture::load_from_svg().
all_compressed_data_sent_to_gpu()
bool Slic3r::GUI::GLTexture::Compressor::all_compressed_data_sent_to_gpu () const inline
{ return m_levels.empty(); }
References m_levels.
Referenced by Slic3r::GUI::GLTexture::all_compressed_data_sent_to_gpu().
compress()
void Slic3r::GUI::GLTexture::Compressor::compress () private
{
    // reference: https://github.com/Cyan4973/RygsDXTc
    assert(m_num_levels_compressed == 0);
    assert(m_abort_compressing == false);
    for (Level& level : m_levels) {
        if (m_abort_compressing)
            break;
        // stb_dxt library, despite claiming that the needed size of the destination buffer is equal to (source buffer size)/4,
        // crashes if doing so, requiring a minimum of 64 bytes and up to a third of the source buffer size, so we set the destination buffer initial size to be half the source buffer size
        level.compressed_data = std::vector<unsigned char>(std::max((unsigned int)64, (unsigned int)level.src_data.size() / 2), 0);
        int compressed_size = 0;
        rygCompress(level.compressed_data.data(), level.src_data.data(), level.w, level.h, 1, compressed_size);
        level.compressed_data.resize(compressed_size);
        // we are done with the source data, we can discard it
        level.src_data.clear();
        ++ m_num_levels_compressed;
    }
}
References rygCompress().
Referenced by start_compressing().
reset()
void Slic3r::GUI::GLTexture::Compressor::reset ()
{
  if (m_thread.joinable()) {
        m_abort_compressing = true;
    m_thread.join();
      m_levels.clear();
      m_num_levels_compressed = 0;
      m_abort_compressing = false;
  }
  assert(m_levels.empty());
  assert(m_abort_compressing == false);
  assert(m_num_levels_compressed == 0);
}
References m_abort_compressing, m_levels, m_num_levels_compressed, and m_thread.
Referenced by ~Compressor(), and Slic3r::GUI::GLTexture::reset().
send_compressed_data_to_gpu()
void Slic3r::GUI::GLTexture::Compressor::send_compressed_data_to_gpu ()
{
    // this method should be called inside the main thread of Slicer or a new OpenGL context (sharing resources) would be needed
  if (m_levels.empty())
    return;
    glsafe(::glPixelStorei(GL_UNPACK_ALIGNMENT, 1));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_texture.m_id));
  // Querying the atomic m_num_levels_compressed value synchronizes processor caches, so that the dat of m_levels modified by the worker thread are accessible to the calling thread.
  int num_compressed = (int)m_num_levels_compressed;
    for (int i = 0; i < num_compressed; ++ i) {
        Level& level = m_levels[i];
        if (! level.sent_to_gpu && ! level.compressed_data.empty()) {
            glsafe(::glCompressedTexSubImage2D(GL_TEXTURE_2D, (GLint)i, 0, 0, (GLsizei)level.w, (GLsizei)level.h, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, (GLsizei)level.compressed_data.size(), (const GLvoid*)level.compressed_data.data()));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAX_LEVEL, i));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, (i > 0) ? GL_LINEAR_MIPMAP_LINEAR : GL_LINEAR));
            level.sent_to_gpu = true;
            // we are done with the compressed data, we can discard it
            level.compressed_data.clear();
        }
    }
    glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
    if (num_compressed == (int)m_levels.size())
        // Finalize the worker thread, close it.
      this->reset();
}
References Slic3r::GUI::GLTexture::Compressor::Level::compressed_data, glsafe, Slic3r::GUI::GLTexture::Compressor::Level::h, Slic3r::GUI::GLTexture::reset(), Slic3r::GUI::GLTexture::Compressor::Level::sent_to_gpu, and Slic3r::GUI::GLTexture::Compressor::Level::w.
Referenced by Slic3r::GUI::GLTexture::send_compressed_data_to_gpu().
start_compressing()
void Slic3r::GUI::GLTexture::Compressor::start_compressing ()
{
  // The worker thread should be stopped already.
  assert(! m_thread.joinable());
  assert(! m_levels.empty());
  assert(m_abort_compressing == false);
  assert(m_num_levels_compressed == 0);
  if (! m_levels.empty()) {
    std::thread thrd(&GLTexture::Compressor::compress, this);
      m_thread = std::move(thrd);
    }
}
References compress().
Referenced by Slic3r::GUI::GLTexture::load_from_png(), and Slic3r::GUI::GLTexture::load_from_svg().
unsent_compressed_data_available()
bool Slic3r::GUI::GLTexture::Compressor::unsent_compressed_data_available () const
{
  if (m_levels.empty())
    return false;
  // Querying the atomic m_num_levels_compressed value synchronizes processor caches, so that the data of m_levels modified by the worker thread are accessible to the calling thread.
  unsigned int num_compressed = m_num_levels_compressed;
  for (unsigned int i = 0; i < num_compressed; ++ i)
        if (! m_levels[i].sent_to_gpu && ! m_levels[i].compressed_data.empty())
            return true;
    return false;
}
Referenced by Slic3r::GUI::GLTexture::unsent_compressed_data_available().
Member Data Documentation
m_abort_compressing
std::atomic<bool> Slic3r::GUI::GLTexture::Compressor::m_abort_compressing private
Referenced by reset().
m_levels
std::vector<Level> Slic3r::GUI::GLTexture::Compressor::m_levels private
Referenced by add_level(), all_compressed_data_sent_to_gpu(), and reset().
m_num_levels_compressed
std::atomic<unsigned int> Slic3r::GUI::GLTexture::Compressor::m_num_levels_compressed private
Referenced by reset().
m_texture
GLTexture& Slic3r::GUI::GLTexture::Compressor::m_texture private
m_thread
std::thread Slic3r::GUI::GLTexture::Compressor::m_thread private
Referenced by reset().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLTexture.hpp
src/slic3r/GUI/GLTexture.cpp