Prusa Slicer: Slic3r::PhysicalPrinter Class Reference
Slic3r::PhysicalPrinter Class Reference
#include <src/libslic3r/Preset.hpp>
Public Member Functions
PhysicalPrinter (const std::string &name, const DynamicPrintConfig &default_config)
PhysicalPrinter (const std::string &name, const DynamicPrintConfig &default_config, const Preset &preset)
void set_name (const std::string &name)
const std::set< std::string > & get_preset_names () const
bool has_empty_config () const
void update_preset_names_in_config ()
void save ()
void save (const std::string &file_name_from, const std::string &file_name_to)
void update_from_preset (const Preset &preset)
void update_from_config (const DynamicPrintConfig &new_config)
bool add_preset (const std::string &preset_name)
bool delete_preset (const std::string &preset_name)
void reset_presets ()
PrinterTechnology printer_technology () const
bool operator< (const PhysicalPrinter &other) const
std::string get_full_name (const std::string &preset_name) const
Static Public Member Functions
static std::string separator ()
static const std::vector< std::string > & printer_options ()
static const std::vector< std::string > & print_host_options ()
static std::vector< std::string > presets_with_print_host_information (const PrinterPresetCollection &printer_presets)
static bool has_print_host_information (const DynamicPrintConfig &config)
static PrinterTechnology printer_technology (const DynamicPrintConfig &cfg)
static std::string get_short_name (std::string full_name)
static std::string get_preset_name (std::string full_name)
Public Attributes
std::string name
std::string file
DynamicPrintConfig config
std::set< std::string > preset_names
bool loaded = false
Friends
class PhysicalPrinterCollection
Detailed Description
Constructor & Destructor Documentation
PhysicalPrinter() [1/2]
Slic3r::PhysicalPrinter::PhysicalPrinter (const std::string & name, const DynamicPrintConfig & default_config)
                                                                                                :
    name(name), config(default_config)
{
    update_from_config(config);
}
References config, and update_from_config().
PhysicalPrinter() [2/2]
Slic3r::PhysicalPrinter::PhysicalPrinter (const std::string & name, const DynamicPrintConfig & default_config, const Preset & preset)
                                                                                                                      :
    name(name), config(default_config)
{
    update_from_preset(preset);
}
References update_from_preset().
Member Function Documentation
add_preset()
bool Slic3r::PhysicalPrinter::add_preset (const std::string & preset_name)
{
    return preset_names.emplace(preset_name).second;
}
References preset_names.
Referenced by Slic3r::PhysicalPrinterCollection::load_printers_from_presets(), Slic3r::GUI::PhysicalPrinterDialog::OnOK(), Slic3r::PhysicalPrinterCollection::rename_preset_in_printers(), and Slic3r::GUI::SavePresetDialog::update_physical_printers().
delete_preset()
bool Slic3r::PhysicalPrinter::delete_preset (const std::string & preset_name)
{
    return preset_names.erase(preset_name) > 0;
}
References preset_names.
Referenced by Slic3r::GUI::Tab::delete_preset(), Slic3r::PhysicalPrinterCollection::delete_preset_from_printers(), Slic3r::PhysicalPrinterCollection::rename_preset_in_printers(), and Slic3r::GUI::SavePresetDialog::update_physical_printers().
get_full_name()
std::string Slic3r::PhysicalPrinter::get_full_name (const std::string & preset_name) const
{
    return name + separator() + preset_name;
}
References name, and separator().
Referenced by Slic3r::PhysicalPrinterCollection::get_selected_full_printer_name(), and Slic3r::GUI::SavePresetDialog::update_physical_printers().
get_preset_name()
std::string Slic3r::PhysicalPrinter::get_preset_name (std::string full_name) static
{
    int pos = name.find(separator());
    boost::erase_head(name, pos + 3);
    return Preset::remove_suffix_modified(name);
}
References name, Slic3r::Preset::remove_suffix_modified(), and separator().
Referenced by Slic3r::GUI::TabPresetComboBox::update_dirty().
get_preset_names()
const std::set< std::string > & Slic3r::PhysicalPrinter::get_preset_names () const
{
    return preset_names;
}
References preset_names.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog().
get_short_name()
std::string Slic3r::PhysicalPrinter::get_short_name (std::string full_name) static
{
    int pos = full_name.find(separator());
    if (pos > 0)
        boost::erase_tail(full_name, full_name.length() - pos);
    return full_name;
}
References separator().
Referenced by Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::PhysicalPrinterCollection::select_printer(), and Slic3r::GUI::TabPresetComboBox::update_dirty().
has_empty_config()
bool Slic3r::PhysicalPrinter::has_empty_config () const
{
    return  config.opt_string("print_host"        ).empty() &&
            config.opt_string("printhost_apikey"  ).empty() &&
            config.opt_string("printhost_cafile"  ).empty() &&
            config.opt_string("printhost_port"    ).empty() &&
            config.opt_string("printhost_user"    ).empty() &&
            config.opt_string("printhost_password").empty();
}
References config, and Slic3r::ConfigBase::opt_string().
Referenced by Slic3r::GUI::PresetForPrinter::PresetForPrinter().
has_print_host_information()
bool Slic3r::PhysicalPrinter::has_print_host_information (const DynamicPrintConfig & config) static
{
    for (const char *opt : legacy_print_host_options)
        if (!config.opt_string(opt).empty())
            return true;
    return false;
}
References config, Slic3r::legacy_print_host_options, and Slic3r::ConfigBase::opt_string().
Referenced by presets_with_print_host_information().
operator<()
bool Slic3r::PhysicalPrinter::operator< (const PhysicalPrinter & other) const inline
{ return this->name < other.name; }
References name.
presets_with_print_host_information()
std::vector< std::string > Slic3r::PhysicalPrinter::presets_with_print_host_information (const PrinterPresetCollection & printer_presets) static
{
    std::vector<std::string> presets;
    for (const Preset& preset : printer_presets)
        if (has_print_host_information(preset.config))
            presets.emplace_back(preset.name);
    return presets;
}
References has_print_host_information().
Referenced by Slic3r::GUI::GUI_App::check_printer_presets().
print_host_options()
static const std::vector< std::string > & Slic3r::PhysicalPrinter::print_host_options () static
printer_options()
const std::vector< std::string > & Slic3r::PhysicalPrinter::printer_options () static
{
    return s_PhysicalPrinter_opts;
}
References Slic3r::s_PhysicalPrinter_opts.
Referenced by update_from_config(), and update_from_preset().
printer_technology() [1/2]
PrinterTechnology Slic3r::PhysicalPrinter::printer_technology () const inline
{ return printer_technology(this->config); }
References printer_technology().
Referenced by printer_technology().
printer_technology() [2/2]
static PrinterTechnology Slic3r::PhysicalPrinter::printer_technology (const DynamicPrintConfig & cfg) inline static
{
        auto* opt = cfg.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
        // The following assert may trigger when importing some legacy profile,
        // but it is safer to keep it here to capture the cases where the "printer_technology" key is queried, where it should not.
        return (opt == nullptr) ? ptFFF : opt->value;
    }
References Slic3r::ConfigBase::option(), and Slic3r::ptFFF.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::get_printer_technology(), and Slic3r::PhysicalPrinterCollection::get_selected_printer_technology().
reset_presets()
void Slic3r::PhysicalPrinter::reset_presets ()
{
    return preset_names.clear();
}
References preset_names.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::OnOK().
save() [1/2]
void Slic3r::PhysicalPrinter::save () inline
{ this->config.save(this->file); }
References Slic3r::ConfigBase::save().
Referenced by Slic3r::PhysicalPrinterCollection::rename_preset_in_printers(), and Slic3r::PhysicalPrinterCollection::save_printer().
save() [2/2]
void Slic3r::PhysicalPrinter::save (const std::string & file_name_from, const std::string & file_name_to)
{
    // rename the file
    boost::nowide::rename(file_name_from.data(), file_name_to.data());
    this->file = file_name_to;
    // save configuration
    this->config.save(this->file);
}
References config, file, and Slic3r::ConfigBase::save().
separator()
std::string Slic3r::PhysicalPrinter::separator () static
{
    return " * ";
}
Referenced by get_full_name(), get_preset_name(), get_short_name(), Slic3r::PhysicalPrinterCollection::select_printer(), Slic3r::GUI::TabPresetComboBox::update_dirty(), and Slic3r::GUI::PresetForPrinter::update_full_printer_name().
set_name()
void Slic3r::PhysicalPrinter::set_name (const std::string & name)
{
    this->name = name;
}
References name.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::OnOK().
update_from_config()
void Slic3r::PhysicalPrinter::update_from_config (const DynamicPrintConfig & new_config)
{
    config.apply_only(new_config, printer_options(), false);
    const std::vector<std::string>& values = config.option<ConfigOptionStrings>("preset_names")->values;
    if (values.empty())
        preset_names.clear();
    else {
        for (const std::string& val : values)
            preset_names.emplace(val);
        // temporary workaround for compatibility with older Slicer
        update_preset_name_option(preset_names, config);
    }
}
References Slic3r::ConfigBase::apply_only(), config, Slic3r::ConfigBase::option(), preset_names, printer_options(), and Slic3r::update_preset_name_option().
Referenced by PhysicalPrinter(), and Slic3r::PhysicalPrinterCollection::load_printers().
update_from_preset()
void Slic3r::PhysicalPrinter::update_from_preset (const Preset & preset)
{
    config.apply_only(preset.config, printer_options(), true);
    // add preset names to the options list
    preset_names.emplace(preset.name);
    update_preset_names_in_config();
}
References Slic3r::ConfigBase::apply_only(), Slic3r::Preset::config, config, Slic3r::Preset::name, preset_names, printer_options(), and update_preset_names_in_config().
Referenced by PhysicalPrinter(), and Slic3r::GUI::PresetForPrinter::PresetForPrinter().
update_preset_names_in_config()
void Slic3r::PhysicalPrinter::update_preset_names_in_config ()
{
    if (!preset_names.empty()) {
        std::vector<std::string>& values = config.option<ConfigOptionStrings>("preset_names")->values;
        values.clear();
        for (const std::string& preset : preset_names)
            values.push_back(preset);
        // temporary workaround for compatibility with older Slicer
        update_preset_name_option(preset_names, config);
    }
}
References Slic3r::ConfigOptionVector< T >::clear(), config, Slic3r::ConfigBase::option(), preset_names, and Slic3r::update_preset_name_option().
Referenced by Slic3r::PhysicalPrinterCollection::rename_preset_in_printers(), Slic3r::PhysicalPrinterCollection::save_printer(), and update_from_preset().
Friends And Related Symbol Documentation
PhysicalPrinterCollection
friend class PhysicalPrinterCollection friend
Member Data Documentation
config
DynamicPrintConfig Slic3r::PhysicalPrinter::config
Referenced by PhysicalPrinter(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::PhysicalPrinterCollection::find_printer_with_same_config(), Slic3r::PhysicalPrinterCollection::get_selected_printer_config(), has_empty_config(), has_print_host_information(), Slic3r::GUI::PresetComboBox::open_physical_printer_url(), save(), Slic3r::PhysicalPrinterCollection::save_printer(), Slic3r::GUI::PlaterPresetComboBox::show_edit_menu(), update_from_config(), update_from_preset(), and update_preset_names_in_config().
file
std::string Slic3r::PhysicalPrinter::file
Referenced by Slic3r::PhysicalPrinterCollection::delete_printer(), Slic3r::PhysicalPrinterCollection::delete_selected_printer(), Slic3r::PhysicalPrinterCollection::load_printers(), save(), and Slic3r::PhysicalPrinterCollection::save_printer().
loaded
bool Slic3r::PhysicalPrinter::loaded = false
Referenced by Slic3r::PhysicalPrinterCollection::load_printers(), and Slic3r::PhysicalPrinterCollection::load_printers_from_presets().
name
std::string Slic3r::PhysicalPrinter::name
Referenced by Slic3r::GUI::Tab::delete_preset(), Slic3r::PhysicalPrinterCollection::delete_preset_from_printers(), Slic3r::PhysicalPrinterCollection::find_printer_internal(), Slic3r::PhysicalPrinterCollection::find_printer_with_same_config(), get_full_name(), get_preset_name(), Slic3r::PhysicalPrinterCollection::get_printers_with_only_preset(), Slic3r::PhysicalPrinterCollection::get_printers_with_preset(), Slic3r::PhysicalPrinterCollection::get_selected_printer_name(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::GUI::PhysicalPrinterDialog::OnOK(), operator<(), Slic3r::PhysicalPrinterCollection::save_printer(), Slic3r::PhysicalPrinterCollection::select_printer(), and set_name().
preset_names
std::set<std::string> Slic3r::PhysicalPrinter::preset_names
Referenced by add_preset(), Slic3r::GUI::Tab::delete_preset(), delete_preset(), Slic3r::PhysicalPrinterCollection::delete_preset_from_printers(), get_preset_names(), Slic3r::PhysicalPrinterCollection::get_printers_with_only_preset(), Slic3r::PhysicalPrinterCollection::get_printers_with_preset(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::GUI::PhysicalPrinterDialog::OnOK(), reset_presets(), Slic3r::PhysicalPrinterCollection::save_printer(), update_from_config(), update_from_preset(), and update_preset_names_in_config().
The documentation for this class was generated from the following files:
src/libslic3r/Preset.hpp
src/libslic3r/Preset.cpp