Prusa Slicer: Slic3r::Bonjour Class Reference
Slic3r::Bonjour Class Reference
Bonjour lookup performer.
#include <src/slic3r/Utils/Bonjour.hpp>
Classes
struct priv
Public Types
typedef std::shared_ptr< Bonjour > Ptr
typedef std::function< void(BonjourReply &&)> ReplyFn
typedef std::function< void()> CompleteFn
typedef std::function< void(const std::vector< BonjourReply > &)> ResolveFn
typedef std::set< std::string > TxtKeys
Public Member Functions
Bonjour (std::string service)
Bonjour (Bonjour &&other)
~Bonjour ()
Bonjour & set_protocol (std::string protocol)
Bonjour & set_txt_keys (TxtKeys txt_keys)
Bonjour & set_timeout (unsigned timeout)
Bonjour & set_retries (unsigned retries)
Bonjour & set_hostname (const std::string &hostname)
Bonjour & on_reply (ReplyFn fn)
Bonjour & on_complete (CompleteFn fn)
Bonjour & on_resolve (ResolveFn fn)
Ptr lookup ()
Ptr resolve ()
void resolve_sync ()
Private Attributes
std::unique_ptr< priv > p
Detailed Description
Bonjour lookup performer.
Member Typedef Documentation
CompleteFn
typedef std::function<void()> Slic3r::Bonjour::CompleteFn
Ptr
typedef std::shared_ptr<Bonjour> Slic3r::Bonjour::Ptr
ReplyFn
typedef std::function<void(BonjourReply &&)> Slic3r::Bonjour::ReplyFn
ResolveFn
typedef std::function<void(const std::vector<BonjourReply>&)> Slic3r::Bonjour::ResolveFn
TxtKeys
typedef std::set<std::string> Slic3r::Bonjour::TxtKeys
Constructor & Destructor Documentation
Bonjour() [1/2]
Slic3r::Bonjour::Bonjour (std::string service)
  : p(new priv(std::move(service)))
{}
Bonjour() [2/2]
Slic3r::Bonjour::Bonjour (Bonjour && other)
: p(std::move(other.p)) {}
~Bonjour()
Slic3r::Bonjour::~Bonjour ()
{
  if (p && p->io_thread.joinable()) {
    p->io_thread.detach();
  }
}
References p.
Member Function Documentation
lookup()
Bonjour::Ptr Slic3r::Bonjour::lookup ()
{
  auto self = std::make_shared<Bonjour>(std::move(*this));
  if (self->p) {
    auto io_thread = std::thread([self]() {
        self->p->lookup_perform();
      });
    self->p->io_thread = std::move(io_thread);
  }
  return self;
}
on_complete()
Bonjour & Slic3r::Bonjour::on_complete (CompleteFn fn)
{
  if (p) { p->completefn = std::move(fn); }
  return *this;
}
References p.
on_reply()
Bonjour & Slic3r::Bonjour::on_reply (ReplyFn fn)
{
  if (p) { p->replyfn = std::move(fn); }
  return *this;
}
References p.
Referenced by Slic3r::BonjourDialog::show_and_lookup().
on_resolve()
Bonjour & Slic3r::Bonjour::on_resolve (ResolveFn fn)
{
  if (p) { p->resolvefn = std::move(fn); }
  return *this;
}
References p.
Referenced by Slic3r::OctoPrint::upload().
resolve()
Bonjour::Ptr Slic3r::Bonjour::resolve ()
{
  auto self = std::make_shared<Bonjour>(std::move(*this));
  if (self->p) {
    auto io_thread = std::thread([self]() {
      self->p->resolve_perform();
      });
    self->p->io_thread = std::move(io_thread);
  }
  return self;
}
resolve_sync()
void Slic3r::Bonjour::resolve_sync ()
{
  if (p)
    p->resolve_perform();
}
References p.
set_hostname()
Bonjour & Slic3r::Bonjour::set_hostname (const std::string & hostname)
{
  if (p) { p->hostname = hostname; }
  return *this;
}
References p.
Referenced by Slic3r::OctoPrint::upload().
set_protocol()
Bonjour & Slic3r::Bonjour::set_protocol (std::string protocol)
{
  if (p) { p->protocol = std::move(protocol); }
  return *this;
}
References p.
set_retries()
Bonjour & Slic3r::Bonjour::set_retries (unsigned retries)
{
  if (p && retries > 0) { p->retries = retries; }
  return *this;
}
References p.
Referenced by Slic3r::BonjourDialog::show_and_lookup(), and Slic3r::OctoPrint::upload().
set_timeout()
Bonjour & Slic3r::Bonjour::set_timeout (unsigned timeout)
{
  if (p) { p->timeout = timeout; }
  return *this;
}
References p.
Referenced by Slic3r::BonjourDialog::show_and_lookup(), and Slic3r::OctoPrint::upload().
set_txt_keys()
Bonjour & Slic3r::Bonjour::set_txt_keys (TxtKeys txt_keys)
{
  if (p) { p->txt_keys = std::move(txt_keys); }
  return *this;
}
References p.
Referenced by Slic3r::BonjourDialog::show_and_lookup().
Member Data Documentation
p
std::unique_ptr<priv> Slic3r::Bonjour::p private
Referenced by ~Bonjour(), on_complete(), on_reply(), on_resolve(), resolve_sync(), set_hostname(), set_protocol(), set_retries(), set_timeout(), and set_txt_keys().
The documentation for this class was generated from the following files:
src/slic3r/Utils/Bonjour.hpp
src/slic3r/Utils/Bonjour.cpp