Prusa Slicer: igl::geodesic::SimpleVector< Data > Class Template Reference
igl::geodesic::SimpleVector< Data > Class Template Reference
Public Types
typedef Data * iterator
Public Member Functions
SimpleVector ()
unsigned size ()
iterator begin ()
iterator end ()
template<class DataPointer >
void set_allocation (DataPointer begin, unsigned size)
Data & operator[] (unsigned i)
void clear ()
Private Attributes
unsigned m_size
Data * m_begin
Detailed Description
template<class Data>
class igl::geodesic::SimpleVector< Data >
Member Typedef Documentation
iterator
template<class Data > typedef Data* igl::geodesic::SimpleVector< Data >::iterator
Constructor & Destructor Documentation
SimpleVector()
template<class Data > igl::geodesic::SimpleVector< Data >::SimpleVector () inline
                :
    m_size(0),
    m_begin(NULL)
  {};
Member Function Documentation
begin()
template<class Data > iterator igl::geodesic::SimpleVector< Data >::begin () inline
{return m_begin;};
References igl::geodesic::SimpleVector< Data >::m_begin.
Referenced by igl::geodesic::Mesh::closest_vertices(), and igl::geodesic::SimpleVector< Data >::set_allocation().
clear()
template<class Data > void igl::geodesic::SimpleVector< Data >::clear () inline
  {
    m_size = 0;
    m_begin = NULL;
  }
References igl::geodesic::SimpleVector< Data >::m_begin, and igl::geodesic::SimpleVector< Data >::m_size.
end()
template<class Data > iterator igl::geodesic::SimpleVector< Data >::end () inline
{return m_begin + m_size;};
References igl::geodesic::SimpleVector< Data >::m_begin, and igl::geodesic::SimpleVector< Data >::m_size.
operator[]()
template<class Data > Data & igl::geodesic::SimpleVector< Data >::operator[] (unsigned i) inline
  {
    assert(i < m_size);
    return *(m_begin + i);
  }
References igl::geodesic::SimpleVector< Data >::m_begin, and igl::geodesic::SimpleVector< Data >::m_size.
set_allocation()
template<class Data > template<class DataPointer > void igl::geodesic::SimpleVector< Data >::set_allocation (DataPointer begin, unsigned size) inline
  {
    assert(begin != NULL || size == 0);
    m_size = size;
    m_begin = (iterator)begin;
  }
References igl::geodesic::SimpleVector< Data >::begin(), igl::geodesic::SimpleVector< Data >::m_begin, igl::geodesic::SimpleVector< Data >::m_size, and igl::geodesic::SimpleVector< Data >::size().
Referenced by igl::geodesic::Mesh::build_adjacencies(), and igl::geodesic::Mesh::initialize_mesh_data().
size()
template<class Data > unsigned igl::geodesic::SimpleVector< Data >::size () inline
{return m_size;};
References igl::geodesic::SimpleVector< Data >::m_size.
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), igl::geodesic::Mesh::build_adjacencies(), igl::geodesic::Mesh::closest_vertices(), igl::geodesic::Edge::is_boundary(), igl::geodesic::GeodesicAlgorithmExact::list_edges_visible_from_source(), igl::geodesic::GeodesicAlgorithmExact::possible_traceback_edges(), igl::geodesic::SimpleVector< Data >::set_allocation(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
Member Data Documentation
m_begin
template<class Data > Data* igl::geodesic::SimpleVector< Data >::m_begin private
Referenced by igl::geodesic::SimpleVector< Data >::begin(), igl::geodesic::SimpleVector< Data >::clear(), igl::geodesic::SimpleVector< Data >::end(), igl::geodesic::SimpleVector< Data >::operator[](), and igl::geodesic::SimpleVector< Data >::set_allocation().
m_size
template<class Data > unsigned igl::geodesic::SimpleVector< Data >::m_size private
Referenced by igl::geodesic::SimpleVector< Data >::clear(), igl::geodesic::SimpleVector< Data >::end(), igl::geodesic::SimpleVector< Data >::operator[](), igl::geodesic::SimpleVector< Data >::set_allocation(), and igl::geodesic::SimpleVector< Data >::size().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp