Prusa Slicer: agg::blender_base< ColorT, Order > Struct Template Reference
agg::blender_base< ColorT, Order > Struct Template Reference
#include <src/agg/agg_pixfmt_base.h>
Public Types
typedef ColorT color_type
typedef Order order_type
typedef color_type::value_type value_type
Static Public Member Functions
static rgba get (value_type r, value_type g, value_type b, value_type a, cover_type cover=cover_full)
static rgba get (const value_type *p, cover_type cover=cover_full)
static void set (value_type *p, value_type r, value_type g, value_type b, value_type a)
static void set (value_type *p, const rgba &c)
Detailed Description
template<class ColorT, class Order = void>
struct agg::blender_base< ColorT, Order >
Member Typedef Documentation
color_type
template<class ColorT , class Order = void> typedef ColorT agg::blender_base< ColorT, Order >::color_type
order_type
template<class ColorT , class Order = void> typedef Order agg::blender_base< ColorT, Order >::order_type
value_type
template<class ColorT , class Order = void> typedef color_type::value_type agg::blender_base< ColorT, Order >::value_type
Member Function Documentation
get() [1/2]
template<class ColorT , class Order = void> static rgba agg::blender_base< ColorT, Order >::get (const value_type * p, cover_type cover = cover_full) inline static
        {
            return get(
                p[order_type::R],
                p[order_type::G],
                p[order_type::B],
                p[order_type::A],
                cover);
        }
References agg::blender_base< ColorT, Order >::get().
get() [2/2]
template<class ColorT , class Order = void> static rgba agg::blender_base< ColorT, Order >::get (value_type r, value_type g, value_type b, value_type a, cover_type cover = cover_full) inline static
        {
            if (cover > cover_none)
            {
                rgba c(
                    color_type::to_double(r),
                    color_type::to_double(g),
                    color_type::to_double(b),
                    color_type::to_double(a));
                if (cover < cover_full)
                {
                    double x = double(cover) / cover_full;
                    c.r *= x;
                    c.g *= x;
                    c.b *= x;
                    c.a *= x;
                }
                return c;
            }
            else return rgba::no_color();
        }
References agg::cover_full, agg::cover_none, and agg::rgba::no_color().
Referenced by agg::blender_base< ColorT, Order >::get().
set() [1/2]
template<class ColorT , class Order = void> static void agg::blender_base< ColorT, Order >::set (value_type * p, const rgba & c) inline static
        {
            p[order_type::R] = color_type::from_double(c.r);
            p[order_type::G] = color_type::from_double(c.g);
            p[order_type::B] = color_type::from_double(c.b);
            p[order_type::A] = color_type::from_double(c.a);
        }
set() [2/2]
template<class ColorT , class Order = void> static void agg::blender_base< ColorT, Order >::set (value_type * p, value_type r, value_type g, value_type b, value_type a) inline static
        {
            p[order_type::R] = r;
            p[order_type::G] = g;
            p[order_type::B] = b;
            p[order_type::A] = a;
        }
The documentation for this struct was generated from the following file:
src/agg/agg_pixfmt_base.h