Prusa Slicer: Slic3r::UndoRedo::MutableHistoryInterval Struct Reference
Slic3r::UndoRedo::MutableHistoryInterval Struct Reference
Classes
struct Data
Public Member Functions
MutableHistoryInterval (const Interval &interval, const std::string &input_data)
MutableHistoryInterval (const Interval &interval, MutableHistoryInterval &other)
MutableHistoryInterval (const size_t begin, const size_t end)
MutableHistoryInterval (MutableHistoryInterval &&rhs)
MutableHistoryInterval & operator= (MutableHistoryInterval &&rhs)
~MutableHistoryInterval ()
const Interval & interval () const
size_t begin () const
size_t end () const
void trim_begin (size_t timestamp)
void trim_end (size_t timestamp)
void extend_begin (size_t timestamp)
void extend_end (size_t timestamp)
bool operator< (const MutableHistoryInterval &rhs) const
bool operator== (const MutableHistoryInterval &rhs) const
const char * data () const
size_t size () const
size_t refcnt () const
bool matches (const std::string &data)
bool matches_timestamp (uint64_t timestamp)
size_t memsize () const
Private Member Functions
MutableHistoryInterval (const MutableHistoryInterval &rhs)
MutableHistoryInterval & operator= (const MutableHistoryInterval &rhs)
Private Attributes
Interval m_interval
Data * m_data
Detailed Description
Constructor & Destructor Documentation
MutableHistoryInterval() [1/5]
Slic3r::UndoRedo::MutableHistoryInterval::MutableHistoryInterval (const Interval & interval, const std::string & input_data) inline
                                                                                : m_interval(interval), m_data(nullptr) {
    m_data = (Data*)new char[offsetof(Data, data) + input_data.size()];
    m_data->refcnt = 1;
    m_data->size = input_data.size();
    memcpy(m_data->data, input_data.data(), input_data.size());
  }
References data(), Slic3r::UndoRedo::MutableHistoryInterval::Data::data, m_data, Slic3r::UndoRedo::MutableHistoryInterval::Data::refcnt, and Slic3r::UndoRedo::MutableHistoryInterval::Data::size.
MutableHistoryInterval() [2/5]
Slic3r::UndoRedo::MutableHistoryInterval::MutableHistoryInterval (const Interval & interval, MutableHistoryInterval & other) inline
                                                                                  : m_interval(interval), m_data(other.m_data) {
    ++ m_data->refcnt;
  }
References m_data, and Slic3r::UndoRedo::MutableHistoryInterval::Data::refcnt.
MutableHistoryInterval() [3/5]
Slic3r::UndoRedo::MutableHistoryInterval::MutableHistoryInterval (const size_t begin, const size_t end) inline
: m_interval(begin, end), m_data(nullptr) {}
MutableHistoryInterval() [4/5]
Slic3r::UndoRedo::MutableHistoryInterval::MutableHistoryInterval (MutableHistoryInterval && rhs) inline
: m_interval(rhs.m_interval), m_data(rhs.m_data) { rhs.m_data = nullptr; }
~MutableHistoryInterval()
Slic3r::UndoRedo::MutableHistoryInterval::~MutableHistoryInterval () inline
{
    if (m_data != nullptr && -- m_data->refcnt == 0)
      delete[] (char*)m_data;
  }
References m_data, and Slic3r::UndoRedo::MutableHistoryInterval::Data::refcnt.
MutableHistoryInterval() [5/5]
Slic3r::UndoRedo::MutableHistoryInterval::MutableHistoryInterval (const MutableHistoryInterval & rhs) private
Member Function Documentation
begin()
size_t Slic3r::UndoRedo::MutableHistoryInterval::begin () const inline
{ return m_interval.begin(); }
References Slic3r::UndoRedo::Interval::begin(), and m_interval.
data()
const char * Slic3r::UndoRedo::MutableHistoryInterval::data () const inline
{ return m_data->data; }
References Slic3r::UndoRedo::MutableHistoryInterval::Data::data, and m_data.
Referenced by MutableHistoryInterval(), and matches().
end()
size_t Slic3r::UndoRedo::MutableHistoryInterval::end () const inline
{ return m_interval.end(); }
References Slic3r::UndoRedo::Interval::end(), and m_interval.
extend_begin()
void Slic3r::UndoRedo::MutableHistoryInterval::extend_begin (size_t timestamp) inline
{ m_interval.extend_begin(timestamp); }
References Slic3r::UndoRedo::Interval::extend_begin(), and m_interval.
extend_end()
void Slic3r::UndoRedo::MutableHistoryInterval::extend_end (size_t timestamp) inline
{ m_interval.extend_end(timestamp); }
References Slic3r::UndoRedo::Interval::extend_end(), and m_interval.
interval()
const Interval & Slic3r::UndoRedo::MutableHistoryInterval::interval () const inline
{ return m_interval; }
References m_interval.
matches()
bool Slic3r::UndoRedo::MutableHistoryInterval::matches (const std::string & data) inline
{ return m_data->matches(data); }
References data(), m_data, and Slic3r::UndoRedo::MutableHistoryInterval::Data::matches().
matches_timestamp()
bool Slic3r::UndoRedo::MutableHistoryInterval::matches_timestamp (uint64_t timestamp) inline
{ return m_data->matches_timestamp(timestamp); }
References m_data, and Slic3r::UndoRedo::MutableHistoryInterval::Data::matches_timestamp().
memsize()
size_t Slic3r::UndoRedo::MutableHistoryInterval::memsize () const inline
{
    return m_data->refcnt == 1 ?
      // Count just the size of the snapshot data.
      m_data->size :
      // Count the size of the snapshot data divided by the number of references, rounded up.
      (m_data->size + m_data->refcnt - 1) / m_data->refcnt;
  }
References m_data, Slic3r::UndoRedo::MutableHistoryInterval::Data::refcnt, and Slic3r::UndoRedo::MutableHistoryInterval::Data::size.
operator<()
bool Slic3r::UndoRedo::MutableHistoryInterval::operator< (const MutableHistoryInterval & rhs) const inline
{ return m_interval < rhs.m_interval; }
References m_interval.
operator=() [1/2]
MutableHistoryInterval & Slic3r::UndoRedo::MutableHistoryInterval::operator= (const MutableHistoryInterval & rhs) private
operator=() [2/2]
MutableHistoryInterval & Slic3r::UndoRedo::MutableHistoryInterval::operator= (MutableHistoryInterval && rhs) inline
{ m_interval = rhs.m_interval; m_data = rhs.m_data; rhs.m_data = nullptr; return *this; }
References m_data, and m_interval.
operator==()
bool Slic3r::UndoRedo::MutableHistoryInterval::operator== (const MutableHistoryInterval & rhs) const inline
{ return m_interval == rhs.m_interval; }
References m_interval.
refcnt()
size_t Slic3r::UndoRedo::MutableHistoryInterval::refcnt () const inline
{ return m_data->refcnt; }
References m_data, and Slic3r::UndoRedo::MutableHistoryInterval::Data::refcnt.
size()
size_t Slic3r::UndoRedo::MutableHistoryInterval::size () const inline
{ return m_data->size; }
References m_data, and Slic3r::UndoRedo::MutableHistoryInterval::Data::size.
trim_begin()
void Slic3r::UndoRedo::MutableHistoryInterval::trim_begin (size_t timestamp) inline
{ m_interval.trim_begin(timestamp); }
References m_interval, and Slic3r::UndoRedo::Interval::trim_begin().
trim_end()
void Slic3r::UndoRedo::MutableHistoryInterval::trim_end (size_t timestamp) inline
{ m_interval.trim_end(timestamp); }
References m_interval, and Slic3r::UndoRedo::Interval::trim_end().
Member Data Documentation
m_data
Data* Slic3r::UndoRedo::MutableHistoryInterval::m_data private
Referenced by MutableHistoryInterval(), MutableHistoryInterval(), ~MutableHistoryInterval(), data(), matches(), matches_timestamp(), memsize(), operator=(), refcnt(), and size().
m_interval
Interval Slic3r::UndoRedo::MutableHistoryInterval::m_interval private
Referenced by begin(), end(), extend_begin(), extend_end(), interval(), operator<(), operator=(), operator==(), trim_begin(), and trim_end().
The documentation for this struct was generated from the following file:
src/slic3r/Utils/UndoRedo.cpp