Prusa Slicer: Slic3r::LayerTools Class Reference
Slic3r::LayerTools Class Reference
#include <src/libslic3r/GCode/ToolOrdering.hpp>
Public Member Functions
bool operator< (const LayerTools &rhs) const
bool operator== (const LayerTools &rhs) const
bool is_extruder_order (unsigned int a, unsigned int b) const
bool has_extruder (unsigned int extruder) const
unsigned int perimeter_extruder (const PrintRegion &region) const
unsigned int infill_extruder (const PrintRegion &region) const
unsigned int solid_infill_extruder (const PrintRegion &region) const
unsigned int extruder (const ExtrusionEntityCollection &extrusions, const PrintRegion &region) const
WipingExtrusions & wiping_extrusions_nonconst ()
const WipingExtrusions & wiping_extrusions () const
Public Attributes
coordf_t print_z = 0.
bool has_object = false
bool has_support = false
std::vector< unsigned int > extruders
unsigned int extruder_override = 0
bool has_skirt = false
bool has_wipe_tower = false
size_t wipe_tower_partitions = 0
coordf_t wipe_tower_layer_height = 0.
const CustomGCode::Item * custom_gcode = nullptr
Private Member Functions
LayerTools (const coordf_t z)
Private Attributes
WipingExtrusions m_wiping_extrusions
Friends
class ToolOrdering
Detailed Description
Constructor & Destructor Documentation
LayerTools()
Slic3r::LayerTools::LayerTools (const coordf_t z) inline private
: print_z(z) {}
Member Function Documentation
extruder()
unsigned int Slic3r::LayerTools::extruder (const ExtrusionEntityCollection & extrusions, const PrintRegion & region) const
{
  assert(region.config().perimeter_extruder.value > 0);
  assert(region.config().infill_extruder.value > 0);
  assert(region.config().solid_infill_extruder.value > 0);
  // 1 based extruder ID.
  unsigned int extruder = this->extruder_override == 0 ?
      (extrusions.role().is_infill() ?
        (extrusions.entities.front()->role().is_solid_infill() ? region.config().solid_infill_extruder : region.config().infill_extruder) :
      region.config().perimeter_extruder.value) :
    this->extruder_override;
  return (extruder == 0) ? 0 : extruder - 1;
}
References Slic3r::PrintRegion::config(), Slic3r::ExtrusionEntityCollection::entities, extruder(), extruder_override, Slic3r::ExtrusionRole::is_infill(), and Slic3r::ExtrusionEntityCollection::role().
Referenced by extruder(), has_extruder(), is_extruder_order(), Slic3r::is_overriddable(), and Slic3r::GCode::process_layer_single_object().
has_extruder()
bool Slic3r::LayerTools::has_extruder (unsigned int extruder) const inline
{ return std::find(this->extruders.begin(), this->extruders.end(), extruder) != this->extruders.end(); }
References extruder(), and extruders.
Referenced by Slic3r::WipingExtrusions::ensure_perimeters_infills_order(), and Slic3r::GCode::process_layer_single_object().
infill_extruder()
unsigned int Slic3r::LayerTools::infill_extruder (const PrintRegion & region) const
{
  assert(region.config().infill_extruder.value > 0);
  return ((this->extruder_override == 0) ? region.config().infill_extruder.value : this->extruder_override) - 1;
}
References Slic3r::PrintRegion::config(), and extruder_override.
Referenced by Slic3r::WipingExtrusions::ensure_perimeters_infills_order().
is_extruder_order()
bool Slic3r::LayerTools::is_extruder_order (unsigned int a, unsigned int b) const
{
    if (a == b)
        return false;
    for (auto extruder : extruders) {
        if (extruder == a)
            return true;
        if (extruder == b)
            return false;
    }
    return false;
}
References extruder(), and extruders.
Referenced by Slic3r::WipingExtrusions::ensure_perimeters_infills_order(), and Slic3r::WipingExtrusions::mark_wiping_extrusions().
operator<()
bool Slic3r::LayerTools::operator< (const LayerTools & rhs) const inline
{ return print_z < rhs.print_z; }
References print_z.
operator==()
bool Slic3r::LayerTools::operator== (const LayerTools & rhs) const inline
{ return print_z == rhs.print_z; }
References print_z.
perimeter_extruder()
unsigned int Slic3r::LayerTools::perimeter_extruder (const PrintRegion & region) const
{
  assert(region.config().perimeter_extruder.value > 0);
  return ((this->extruder_override == 0) ? region.config().perimeter_extruder.value : this->extruder_override) - 1;
}
References Slic3r::PrintRegion::config(), and extruder_override.
Referenced by Slic3r::WipingExtrusions::ensure_perimeters_infills_order(), and Slic3r::WipingExtrusions::mark_wiping_extrusions().
solid_infill_extruder()
unsigned int Slic3r::LayerTools::solid_infill_extruder (const PrintRegion & region) const
{
  assert(region.config().solid_infill_extruder.value > 0);
  return ((this->extruder_override == 0) ? region.config().solid_infill_extruder.value : this->extruder_override) - 1;
}
References Slic3r::PrintRegion::config(), and extruder_override.
wiping_extrusions()
const WipingExtrusions & Slic3r::LayerTools::wiping_extrusions () const inline
{ return m_wiping_extrusions; }
References m_wiping_extrusions.
Referenced by Slic3r::GCode::process_layer(), and Slic3r::GCode::process_layer_single_object().
wiping_extrusions_nonconst()
WipingExtrusions & Slic3r::LayerTools::wiping_extrusions_nonconst () inline
{ return m_wiping_extrusions; }
References m_wiping_extrusions.
Friends And Related Symbol Documentation
ToolOrdering
friend class ToolOrdering friend
Member Data Documentation
custom_gcode
const CustomGCode::Item* Slic3r::LayerTools::custom_gcode = nullptr
Referenced by Slic3r::ToolOrdering::assign_custom_gcodes(), and Slic3r::GCode::process_layer().
extruder_override
unsigned int Slic3r::LayerTools::extruder_override = 0
Referenced by extruder(), infill_extruder(), perimeter_extruder(), and solid_infill_extruder().
extruders
std::vector<unsigned int> Slic3r::LayerTools::extruders
Referenced by Slic3r::ToolOrdering::assign_custom_gcodes(), Slic3r::ToolOrdering::fill_wipe_tower_partitions(), Slic3r::first_nonsoluble_extruder_on_layer(), has_extruder(), is_extruder_order(), Slic3r::last_nonsoluble_extruder_on_layer(), Slic3r::Skirt::make_skirt_loops_per_extruder_other_layers(), Slic3r::GCode::process_layer(), Slic3r::GCode::process_layer_single_object(), Slic3r::ToolOrdering::reorder_extruders(), and Slic3r::Skirt::skirt_loops_per_extruder_all_printing().
has_object
bool Slic3r::LayerTools::has_object = false
Referenced by Slic3r::Print::_make_wipe_tower().
has_skirt
bool Slic3r::LayerTools::has_skirt = false
Referenced by Slic3r::Skirt::make_skirt_loops_per_extruder_1st_layer(), and Slic3r::Skirt::make_skirt_loops_per_extruder_other_layers().
has_support
bool Slic3r::LayerTools::has_support = false
Referenced by Slic3r::Print::_make_wipe_tower().
has_wipe_tower
bool Slic3r::LayerTools::has_wipe_tower = false
Referenced by Slic3r::Print::_make_wipe_tower(), Slic3r::ToolOrdering::fill_wipe_tower_partitions(), Slic3r::GCode::process_layer(), and Slic3r::GCode::process_layers().
m_wiping_extrusions
WipingExtrusions Slic3r::LayerTools::m_wiping_extrusions private
Referenced by wiping_extrusions(), and wiping_extrusions_nonconst().
print_z
coordf_t Slic3r::LayerTools::print_z = 0.
Referenced by Slic3r::Print::_make_wipe_tower(), Slic3r::ToolOrdering::assign_custom_gcodes(), Slic3r::WipingExtrusions::ensure_perimeters_infills_order(), Slic3r::ToolOrdering::fill_wipe_tower_partitions(), Slic3r::Skirt::make_skirt_loops_per_extruder_1st_layer(), Slic3r::Skirt::make_skirt_loops_per_extruder_other_layers(), Slic3r::WipingExtrusions::mark_wiping_extrusions(), operator<(), and operator==().
wipe_tower_layer_height
coordf_t Slic3r::LayerTools::wipe_tower_layer_height = 0.
wipe_tower_partitions
size_t Slic3r::LayerTools::wipe_tower_partitions = 0
Referenced by Slic3r::Print::_make_wipe_tower(), and Slic3r::ToolOrdering::fill_wipe_tower_partitions().
The documentation for this class was generated from the following files:
src/libslic3r/GCode/ToolOrdering.hpp
src/libslic3r/GCode/ToolOrdering.cpp