Prusa Slicer: libnest2d::_Nester< PlacementStrategy, SelectionStrategy > Class Template Reference
libnest2d::_Nester< PlacementStrategy, SelectionStrategy > Class Template Reference
#include <src/libnest2d/include/libnest2d/nester.hpp>
Public Types
using Item = typename PlacementStrategy::Item
using ShapeType = typename Item::ShapeType
using ItemRef = std::reference_wrapper< Item >
using TPlacer = PlacementStrategyLike< PlacementStrategy >
using BinType = typename TPlacer::BinType
using PlacementConfig = typename TPlacer::Config
using SelectionConfig = typename TSel::Config
using Coord = TCoord< TPoint< typename Item::ShapeType > >
using PackGroup = _PackGroup< typename Item::ShapeType >
using ResultType = PackGroup
Public Member Functions
template<class TBinType = BinType, class PConf = PlacementConfig, class SConf = SelectionConfig>
_Nester (TBinType &&bin, Coord min_obj_distance=0, const PConf &pconfig=PConf(), const SConf &sconfig=SConf())
Constructor taking the bin as the only mandatory parameter.
void configure (const PlacementConfig &pconf)
void configure (const SelectionConfig &sconf)
void configure (const PlacementConfig &pconf, const SelectionConfig &sconf)
void configure (const SelectionConfig &sconf, const PlacementConfig &pconf)
template<class It >
ItemIteratorOnly< It, size_t > execute (It from, It to)
Arrange an input sequence of _Item-s.
_Nester & progressIndicator (ProgressFunction func)
Set a progress indicator function object for the selector.
_Nester & stopCondition (StopCondition fn)
Set a predicate to tell when to abort nesting.
const PackGroup & lastResult () const
int lastPackedBinId () const
Private Types
using TSel = SelectionStrategyLike< SelectionStrategy >
using SItem = typename SelectionStrategy::Item
using TPItem = remove_cvref_t< Item >
using TSItem = remove_cvref_t< SItem >
template<class It >
using TVal = remove_ref_t< typename It::value_type >
template<class It , class Out >
using ItemIteratorOnly = enable_if_t< std::is_convertible< TVal< It > &, TPItem & >::value, Out >
Private Attributes
TSel selector_
BinType bin_
PlacementConfig pconfig_
Coord min_obj_distance_
StopCondition stopfn_
Detailed Description
template<class PlacementStrategy, class SelectionStrategy>
class libnest2d::_Nester< PlacementStrategy, SelectionStrategy >
The _Nester is the front-end class for the libnest2d library. It takes the input items and changes their transformations to be inside the provided bin.
Member Typedef Documentation
BinType
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::BinType = typename TPlacer::BinType
Coord
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::Coord = TCoord<TPoint<typename Item::ShapeType> >
Item
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::Item = typename PlacementStrategy::Item
ItemIteratorOnly
template<class PlacementStrategy , class SelectionStrategy > template<class It , class Out > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::ItemIteratorOnly = enable_if_t<std::is_convertible<TVal<It>&, TPItem&>::value, Out> private
ItemRef
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::ItemRef = std::reference_wrapper<Item>
PackGroup
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::PackGroup = _PackGroup<typename Item::ShapeType>
PlacementConfig
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::PlacementConfig = typename TPlacer::Config
ResultType
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::ResultType = PackGroup
SelectionConfig
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::SelectionConfig = typename TSel::Config
ShapeType
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::ShapeType = typename Item::ShapeType
SItem
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::SItem = typename SelectionStrategy::Item private
TPItem
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::TPItem = remove_cvref_t<Item> private
TPlacer
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::TPlacer = PlacementStrategyLike<PlacementStrategy>
TSel
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::TSel = SelectionStrategyLike<SelectionStrategy> private
TSItem
template<class PlacementStrategy , class SelectionStrategy > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::TSItem = remove_cvref_t<SItem> private
TVal
template<class PlacementStrategy , class SelectionStrategy > template<class It > using libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::TVal = remove_ref_t<typename It::value_type> private
Constructor & Destructor Documentation
_Nester()
template<class PlacementStrategy , class SelectionStrategy > template<class TBinType = BinType, class PConf = PlacementConfig, class SConf = SelectionConfig> libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::_Nester (TBinType && bin, Coord min_obj_distance = 0, const PConf & pconfig = PConf(), const SConf & sconfig = SConf()) inline
Constructor taking the bin as the only mandatory parameter.
Parameters
bin The bin shape that will be used by the placers. The type of the bin should be one that is supported by the placer type.
                                                                           :
        bin_(std::forward<TBinType>(bin)),
        pconfig_(pconfig),
        min_obj_distance_(min_obj_distance)
    {
        static_assert( std::is_same<TPItem, TSItem>::value,
                       "Incompatible placement and selection strategy!");
        selector_.configure(sconfig);
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::configure(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_.
Member Function Documentation
configure() [1/4]
template<class PlacementStrategy , class SelectionStrategy > void libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure (const PlacementConfig & pconf) inline
{ pconfig_ = pconf; }
References libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::pconfig_.
configure() [2/4]
template<class PlacementStrategy , class SelectionStrategy > void libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure (const PlacementConfig & pconf, const SelectionConfig & sconf) inline
    {
        pconfig_ = pconf;
        selector_.configure(sconf);
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::configure(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::pconfig_, and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_.
configure() [3/4]
template<class PlacementStrategy , class SelectionStrategy > void libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure (const SelectionConfig & sconf) inline
{ selector_.configure(sconf); }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::configure(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_.
configure() [4/4]
template<class PlacementStrategy , class SelectionStrategy > void libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure (const SelectionConfig & sconf, const PlacementConfig & pconf) inline
    {
        pconfig_ = pconf;
        selector_.configure(sconf);
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::configure(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::pconfig_, and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_.
execute()
template<class PlacementStrategy , class SelectionStrategy > template<class It > template std::size_t libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::execute (It from, It to) inline
Arrange an input sequence of _Item-s.
To get the result, call the translation(), rotation() and binId() methods of each item. If only the transformed polygon is needed, call transformedShape() to get the properly transformed shapes.
The number of groups in the pack group is the number of bins opened by the selection algorithm.
    {
        auto infl = static_cast<Coord>(std::ceil(min_obj_distance_/2.0));
        if(infl > 0) std::for_each(from, to, [infl](Item& item) {
            item.inflate(infl);
        });
        selector_.template packItems<PlacementStrategy>(
            from, to, bin_, pconfig_);
        if(min_obj_distance_ > 0) std::for_each(from, to, [infl](Item& item) {
            item.inflate(-infl);
        });
        return selector_.getResult().size();
    }
References libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::bin_, libnest2d::SelectionStrategyLike< SelectionStrategy >::getResult(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::min_obj_distance_, libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::pconfig_, and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_.
Referenced by Slic3r::arrangement::AutoArranger< TBin >::operator()().
lastPackedBinId()
template<class PlacementStrategy , class SelectionStrategy > int libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::lastPackedBinId () const inline
{
        return selector_.lastPackedBinId();
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::lastPackedBinId(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_.
lastResult()
template<class PlacementStrategy , class SelectionStrategy > const PackGroup & libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::lastResult () const inline
    {
        return selector_.getResult();
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::getResult(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_.
progressIndicator()
template<class PlacementStrategy , class SelectionStrategy > _Nester & libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::progressIndicator (ProgressFunction func) inline
Set a progress indicator function object for the selector.
    {
        selector_.progressIndicator(func); return *this;
    }
References libnest2d::SelectionStrategyLike< SelectionStrategy >::progressIndicator(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_.
stopCondition()
template<class PlacementStrategy , class SelectionStrategy > _Nester & libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::stopCondition (StopCondition fn) inline
Set a predicate to tell when to abort nesting.
    {
        stopfn_ = fn; selector_.stopCondition(fn); return *this;
    }
References libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_, libnest2d::SelectionStrategyLike< SelectionStrategy >::stopCondition(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::stopfn_.
Member Data Documentation
bin_
template<class PlacementStrategy , class SelectionStrategy > BinType libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::bin_ private
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::execute().
min_obj_distance_
template<class PlacementStrategy , class SelectionStrategy > Coord libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::min_obj_distance_ private
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::execute().
pconfig_
template<class PlacementStrategy , class SelectionStrategy > PlacementConfig libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::pconfig_ private
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::execute().
selector_
template<class PlacementStrategy , class SelectionStrategy > TSel libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::selector_ private
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::_Nester(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::configure(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::execute(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::lastPackedBinId(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::lastResult(), libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::progressIndicator(), and libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::stopCondition().
stopfn_
template<class PlacementStrategy , class SelectionStrategy > StopCondition libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::stopfn_ private
Referenced by libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::stopCondition().
The documentation for this class was generated from the following files:
src/libnest2d/include/libnest2d/nester.hpp
src/libnest2d/src/libnest2d.cpp