Prusa Slicer: src/avrdude/jtagmkII.h File Reference
jtagmkII.h File Reference
Functions
int jtagmkII_send (PROGRAMMER *pgm, unsigned char *data, size_t len)
int jtagmkII_recv (PROGRAMMER *pgm, unsigned char **msg)
void jtagmkII_close (PROGRAMMER *pgm)
int jtagmkII_getsync (PROGRAMMER *pgm, int mode)
int jtagmkII_getparm (PROGRAMMER *pgm, unsigned char parm, unsigned char *value)
void jtagmkII_initpgm (PROGRAMMER *pgm)
void jtagmkII_avr32_initpgm (PROGRAMMER *pgm)
void jtagmkII_dw_initpgm (PROGRAMMER *pgm)
void jtagmkII_pdi_initpgm (PROGRAMMER *pgm)
void jtagmkII_dragon_initpgm (PROGRAMMER *pgm)
void jtagmkII_dragon_dw_initpgm (PROGRAMMER *pgm)
void jtagmkII_dragon_pdi_initpgm (PROGRAMMER *pgm)
void jtagmkII_setup (PROGRAMMER *pgm)
void jtagmkII_teardown (PROGRAMMER *pgm)
Variables
const char jtagmkII_desc []
const char jtagmkII_avr32_desc []
const char jtagmkII_dw_desc []
const char jtagmkII_pdi_desc []
const char jtagmkII_dragon_desc []
const char jtagmkII_dragon_dw_desc []
const char jtagmkII_dragon_pdi_desc []
Function Documentation
jtagmkII_avr32_initpgm()
void jtagmkII_avr32_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAGMKII_AVR32");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtagmkII_initialize32;
  pgm->display        = jtagmkII_display;
  pgm->enable         = jtagmkII_enable;
  pgm->disable        = jtagmkII_disable;
  pgm->program_enable = jtagmkII_program_enable_INFO;
  pgm->chip_erase     = jtagmkII_chip_erase32;
  pgm->open           = jtagmkII_open32;
  pgm->close          = jtagmkII_close32;
  pgm->read_byte      = jtagmkII_read_byte;
  pgm->write_byte     = jtagmkII_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtagmkII_paged_write32;
  pgm->paged_load     = jtagmkII_paged_load32;
  pgm->print_parms    = jtagmkII_print_parms;
  //pgm->set_sck_period = jtagmkII_set_sck_period;
  //pgm->parseextparams = jtagmkII_parseextparms;
  pgm->setup          = jtagmkII_setup;
  pgm->teardown       = jtagmkII_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_JTAG;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtagmkII_chip_erase32(), jtagmkII_close32(), jtagmkII_disable(), jtagmkII_display(), jtagmkII_enable(), jtagmkII_initialize32(), jtagmkII_open32(), jtagmkII_paged_load32(), jtagmkII_paged_write32(), jtagmkII_print_parms(), jtagmkII_program_enable_INFO(), jtagmkII_read_byte(), jtagmkII_setup(), jtagmkII_teardown(), jtagmkII_write_byte(), programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, PGM_FL_IS_JTAG, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtagmkII_close()
void jtagmkII_close (PROGRAMMER * pgm)
{
  int status;
  unsigned char buf[1], *resp, c;
  avrdude_message(MSG_NOTICE2, "%s: jtagmkII_close()\n", progname);
  if (pgm->flag & PGM_FL_IS_PDI) {
    /* When in PDI mode, restart target. */
    buf[0] = CMND_GO;
    avrdude_message(MSG_NOTICE2, "%s: jtagmkII_close(): Sending GO command: ",
        progname);
    jtagmkII_send(pgm, buf, 1);
    status = jtagmkII_recv(pgm, &resp);
    if (status <= 0) {
      if (verbose >= 2)
  putc('\n', stderr);
      avrdude_message(MSG_INFO, "%s: jtagmkII_close(): "
                      "timeout/error communicating with programmer (status %d)\n",
                      progname, status);
    } else {
      if (verbose >= 3) {
  putc('\n', stderr);
  jtagmkII_prmsg(pgm, resp, status);
      } else if (verbose == 2)
  avrdude_message(MSG_NOTICE2, "0x%02x (%d bytes msg)\n", resp[0], status);
      c = resp[0];
      free(resp);
      if (c != RSP_OK) {
  avrdude_message(MSG_INFO, "%s: jtagmkII_close(): "
                        "bad response to GO command: %s\n",
                        progname, jtagmkII_get_rc(c));
      }
    }
  }
  buf[0] = CMND_SIGN_OFF;
  avrdude_message(MSG_NOTICE2, "%s: jtagmkII_close(): Sending sign-off command: ",
      progname);
  jtagmkII_send(pgm, buf, 1);
  status = jtagmkII_recv(pgm, &resp);
  if (status <= 0) {
    if (verbose >= 2)
      putc('\n', stderr);
    avrdude_message(MSG_INFO, "%s: jtagmkII_close(): "
                    "timeout/error communicating with programmer (status %d)\n",
                    progname, status);
    return;
  }
  if (verbose >= 3) {
    putc('\n', stderr);
    jtagmkII_prmsg(pgm, resp, status);
  } else if (verbose == 2)
    avrdude_message(MSG_NOTICE2, "0x%02x (%d bytes msg)\n", resp[0], status);
  c = resp[0];
  free(resp);
  if (c != RSP_OK) {
    avrdude_message(MSG_INFO, "%s: jtagmkII_close(): "
                    "bad response to sign-off command: %s\n",
                    progname, jtagmkII_get_rc(c));
  }
  serial_close(&pgm->fd);
  pgm->fd.ifd = -1;
}
References avrdude_message(), CMND_GO, CMND_SIGN_OFF, programmer_t::fd, programmer_t::flag, free(), filedescriptor::ifd, jtagmkII_get_rc(), jtagmkII_prmsg(), jtagmkII_recv(), jtagmkII_send(), MSG_INFO, MSG_NOTICE2, pgm, PGM_FL_IS_PDI, progname, RSP_OK, serial_close, and verbose.
Referenced by jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), and jtagmkII_pdi_initpgm().
jtagmkII_dragon_dw_initpgm()
void jtagmkII_dragon_dw_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "DRAGON_DW");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtagmkII_initialize;
  pgm->display        = jtagmkII_display;
  pgm->enable         = jtagmkII_enable;
  pgm->disable        = jtagmkII_disable;
  pgm->program_enable = jtagmkII_program_enable_INFO;
  pgm->chip_erase     = jtagmkII_chip_erase_dw;
  pgm->open           = jtagmkII_dragon_open_dw;
  pgm->close          = jtagmkII_close;
  pgm->read_byte      = jtagmkII_read_byte;
  pgm->write_byte     = jtagmkII_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtagmkII_paged_write;
  pgm->paged_load     = jtagmkII_paged_load;
  pgm->print_parms    = jtagmkII_print_parms;
  pgm->setup          = jtagmkII_setup;
  pgm->teardown       = jtagmkII_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_DW;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtagmkII_chip_erase_dw(), jtagmkII_close(), jtagmkII_disable(), jtagmkII_display(), jtagmkII_dragon_open_dw(), jtagmkII_enable(), jtagmkII_initialize(), jtagmkII_paged_load(), jtagmkII_paged_write(), jtagmkII_print_parms(), jtagmkII_program_enable_INFO(), jtagmkII_read_byte(), jtagmkII_setup(), jtagmkII_teardown(), jtagmkII_write_byte(), programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, PGM_FL_IS_DW, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtagmkII_dragon_initpgm()
void jtagmkII_dragon_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "DRAGON_JTAG");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtagmkII_initialize;
  pgm->display        = jtagmkII_display;
  pgm->enable         = jtagmkII_enable;
  pgm->disable        = jtagmkII_disable;
  pgm->program_enable = jtagmkII_program_enable_INFO;
  pgm->chip_erase     = jtagmkII_chip_erase;
  pgm->open           = jtagmkII_dragon_open;
  pgm->close          = jtagmkII_close;
  pgm->read_byte      = jtagmkII_read_byte;
  pgm->write_byte     = jtagmkII_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtagmkII_paged_write;
  pgm->paged_load     = jtagmkII_paged_load;
  pgm->page_erase     = jtagmkII_page_erase;
  pgm->print_parms    = jtagmkII_print_parms;
  pgm->set_sck_period = jtagmkII_set_sck_period;
  pgm->parseextparams = jtagmkII_parseextparms;
  pgm->setup          = jtagmkII_setup;
  pgm->teardown       = jtagmkII_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_JTAG;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtagmkII_chip_erase(), jtagmkII_close(), jtagmkII_disable(), jtagmkII_display(), jtagmkII_dragon_open(), jtagmkII_enable(), jtagmkII_initialize(), jtagmkII_page_erase(), jtagmkII_paged_load(), jtagmkII_paged_write(), jtagmkII_parseextparms(), jtagmkII_print_parms(), jtagmkII_program_enable_INFO(), jtagmkII_read_byte(), jtagmkII_set_sck_period(), jtagmkII_setup(), jtagmkII_teardown(), jtagmkII_write_byte(), programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, programmer_t::parseextparams, pgm, PGM_FL_IS_JTAG, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_sck_period, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtagmkII_dragon_pdi_initpgm()
void jtagmkII_dragon_pdi_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "DRAGON_PDI");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtagmkII_initialize;
  pgm->display        = jtagmkII_display;
  pgm->enable         = jtagmkII_enable;
  pgm->disable        = jtagmkII_disable;
  pgm->program_enable = jtagmkII_program_enable_INFO;
  pgm->chip_erase     = jtagmkII_chip_erase;
  pgm->open           = jtagmkII_dragon_open_pdi;
  pgm->close          = jtagmkII_close;
  pgm->read_byte      = jtagmkII_read_byte;
  pgm->write_byte     = jtagmkII_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtagmkII_paged_write;
  pgm->paged_load     = jtagmkII_paged_load;
  pgm->page_erase     = jtagmkII_page_erase;
  pgm->print_parms    = jtagmkII_print_parms;
  pgm->setup          = jtagmkII_setup;
  pgm->teardown       = jtagmkII_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_PDI;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtagmkII_chip_erase(), jtagmkII_close(), jtagmkII_disable(), jtagmkII_display(), jtagmkII_dragon_open_pdi(), jtagmkII_enable(), jtagmkII_initialize(), jtagmkII_page_erase(), jtagmkII_paged_load(), jtagmkII_paged_write(), jtagmkII_print_parms(), jtagmkII_program_enable_INFO(), jtagmkII_read_byte(), jtagmkII_setup(), jtagmkII_teardown(), jtagmkII_write_byte(), programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, PGM_FL_IS_PDI, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtagmkII_dw_initpgm()
void jtagmkII_dw_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAGMKII_DW");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtagmkII_initialize;
  pgm->display        = jtagmkII_display;
  pgm->enable         = jtagmkII_enable;
  pgm->disable        = jtagmkII_disable;
  pgm->program_enable = jtagmkII_program_enable_INFO;
  pgm->chip_erase     = jtagmkII_chip_erase_dw;
  pgm->open           = jtagmkII_open_dw;
  pgm->close          = jtagmkII_close;
  pgm->read_byte      = jtagmkII_read_byte;
  pgm->write_byte     = jtagmkII_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtagmkII_paged_write;
  pgm->paged_load     = jtagmkII_paged_load;
  pgm->print_parms    = jtagmkII_print_parms;
  pgm->setup          = jtagmkII_setup;
  pgm->teardown       = jtagmkII_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_DW;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtagmkII_chip_erase_dw(), jtagmkII_close(), jtagmkII_disable(), jtagmkII_display(), jtagmkII_enable(), jtagmkII_initialize(), jtagmkII_open_dw(), jtagmkII_paged_load(), jtagmkII_paged_write(), jtagmkII_print_parms(), jtagmkII_program_enable_INFO(), jtagmkII_read_byte(), jtagmkII_setup(), jtagmkII_teardown(), jtagmkII_write_byte(), programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, PGM_FL_IS_DW, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtagmkII_getparm()
int jtagmkII_getparm (PROGRAMMER * pgm, unsigned char parm, unsigned char * value)
{
  int status;
  unsigned char buf[2], *resp, c;
  avrdude_message(MSG_NOTICE2, "%s: jtagmkII_getparm()\n", progname);
  buf[0] = CMND_GET_PARAMETER;
  buf[1] = parm;
  avrdude_message(MSG_NOTICE2, "%s: jtagmkII_getparm(): "
      "Sending get parameter command (parm 0x%02x): ",
      progname, parm);
  jtagmkII_send(pgm, buf, 2);
  status = jtagmkII_recv(pgm, &resp);
  if (status <= 0) {
    if (verbose >= 2)
      putc('\n', stderr);
    avrdude_message(MSG_INFO, "%s: jtagmkII_getparm(): "
      "timeout/error communicating with programmer (status %d)\n",
      progname, status);
    return -1;
  }
  if (verbose >= 3) {
    putc('\n', stderr);
    jtagmkII_prmsg(pgm, resp, status);
  } else if (verbose == 2)
    avrdude_message(MSG_NOTICE2, "0x%02x (%d bytes msg)\n", resp[0], status);
  c = resp[0];
  if (c != RSP_PARAMETER) {
    avrdude_message(MSG_INFO, "%s: jtagmkII_getparm(): "
      "bad response to get parameter command: %s\n",
      progname, jtagmkII_get_rc(c));
    free(resp);
    return -1;
  }
  memcpy(value, resp + 1, 4);
  free(resp);
  return 0;
}
References avrdude_message(), CMND_GET_PARAMETER, free(), jtagmkII_get_rc(), jtagmkII_prmsg(), jtagmkII_recv(), jtagmkII_send(), MSG_INFO, MSG_NOTICE2, pgm, progname, RSP_PARAMETER, and verbose.
Referenced by jtagmkII_display(), jtagmkII_print_parms1(), and jtagmkII_read_byte().
jtagmkII_getsync()
int jtagmkII_getsync (PROGRAMMER * pgm, int mode)
{
  int tries;
#define MAXTRIES 33
  unsigned char buf[3], *resp, c = 0xff;
  int status;
  unsigned int fwver, hwver;
  int is_dragon;
  avrdude_message(MSG_DEBUG, "%s: jtagmkII_getsync()\n", progname);
  if (strncmp(pgm->type, "JTAG", strlen("JTAG")) == 0) {
    is_dragon = 0;
  } else if (strncmp(pgm->type, "DRAGON", strlen("DRAGON")) == 0) {
    is_dragon = 1;
  } else {
    avrdude_message(MSG_INFO, "%s: Programmer is neither JTAG ICE mkII nor AVR Dragon\n",
                    progname);
    return -1;
  }
  for (tries = 0; tries < MAXTRIES; tries++) {
    /* Get the sign-on information. */
    buf[0] = CMND_GET_SIGN_ON;
    avrdude_message(MSG_NOTICE2, "%s: jtagmkII_getsync(): Sending sign-on command: ",
        progname);
    jtagmkII_send(pgm, buf, 1);
    status = jtagmkII_recv(pgm, &resp);
    if (status <= 0) {
  avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): sign-on command: "
    "status %d\n",
    progname, status);
    } else if (verbose >= 3) {
      putc('\n', stderr);
      jtagmkII_prmsg(pgm, resp, status);
    } else if (verbose == 2)
      avrdude_message(MSG_NOTICE2, "0x%02x (%d bytes msg)\n", resp[0], status);
    if (status > 0) {
      if ((c = resp[0]) == RSP_SIGN_ON) {
  fwver = ((unsigned)resp[8] << 8) | (unsigned)resp[7];
        PDATA(pgm)->fwver = fwver;
  hwver = (unsigned)resp[9];
  memcpy(PDATA(pgm)->serno, resp + 10, 6);
  if (status > 17) {
    avrdude_message(MSG_NOTICE, "JTAG ICE mkII sign-on message:\n");
    avrdude_message(MSG_NOTICE, "Communications protocol version: %u\n",
      (unsigned)resp[1]);
    avrdude_message(MSG_NOTICE, "M_MCU:\n");
    avrdude_message(MSG_NOTICE, "  boot-loader FW version:        %u\n",
      (unsigned)resp[2]);
    avrdude_message(MSG_NOTICE, "  firmware version:              %u.%02u\n",
      (unsigned)resp[4], (unsigned)resp[3]);
    avrdude_message(MSG_NOTICE, "  hardware version:              %u\n",
      (unsigned)resp[5]);
    avrdude_message(MSG_NOTICE, "S_MCU:\n");
    avrdude_message(MSG_NOTICE, "  boot-loader FW version:        %u\n",
      (unsigned)resp[6]);
    avrdude_message(MSG_NOTICE, "  firmware version:              %u.%02u\n",
      (unsigned)resp[8], (unsigned)resp[7]);
    avrdude_message(MSG_NOTICE, "  hardware version:              %u\n",
      (unsigned)resp[9]);
    avrdude_message(MSG_NOTICE, "Serial number:                   "
      "%02x:%02x:%02x:%02x:%02x:%02x\n",
      PDATA(pgm)->serno[0], PDATA(pgm)->serno[1], PDATA(pgm)->serno[2], PDATA(pgm)->serno[3], PDATA(pgm)->serno[4], PDATA(pgm)->serno[5]);
    resp[status - 1] = '\0';
    avrdude_message(MSG_NOTICE, "Device ID:                       %s\n",
      resp + 16);
  }
  break;
      }
      free(resp);
    }
  }
  if (tries >= MAXTRIES) {
    if (status <= 0)
      avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): "
                      "timeout/error communicating with programmer (status %d)\n",
                      progname, status);
    else
      avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): "
                      "bad response to sign-on command: %s\n",
                      progname, jtagmkII_get_rc(c));
    return -1;
  }
  PDATA(pgm)->device_descriptor_length = sizeof(struct device_descriptor);
  /*
   * There's no official documentation from Atmel about what firmware
   * revision matches what device descriptor length.  The algorithm
   * below has been found empirically.
   */
#define FWVER(maj, min) ((maj << 8) | (min))
  if (!is_dragon && fwver < FWVER(3, 16)) {
    PDATA(pgm)->device_descriptor_length -= 2;
    avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): "
                    "S_MCU firmware version might be too old to work correctly\n",
                    progname);
  } else if (!is_dragon && fwver < FWVER(4, 0)) {
    PDATA(pgm)->device_descriptor_length -= 2;
  }
  if (mode != EMULATOR_MODE_SPI)
    avrdude_message(MSG_NOTICE2, "%s: jtagmkII_getsync(): Using a %u-byte device descriptor\n",
                    progname, (unsigned)PDATA(pgm)->device_descriptor_length);
  if (mode == EMULATOR_MODE_SPI) {
    PDATA(pgm)->device_descriptor_length = 0;
    if (!is_dragon && fwver < FWVER(4, 14)) {
      avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): ISP functionality requires firmware "
                      "version >= 4.14\n",
                      progname);
      return -1;
    }
  }
  if (mode == EMULATOR_MODE_PDI || mode == EMULATOR_MODE_JTAG_XMEGA) {
    if (!is_dragon && mode == EMULATOR_MODE_PDI && hwver < 1) {
      avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): Xmega PDI support requires hardware "
                      "revision >= 1\n",
                      progname);
      return -1;
    }
    if (!is_dragon && fwver < FWVER(5, 37)) {
      avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): Xmega support requires firmware "
                      "version >= 5.37\n",
                      progname);
      return -1;
    }
    if (is_dragon && fwver < FWVER(6, 11)) {
      avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): Xmega support requires firmware "
                      "version >= 6.11\n",
                      progname);
      return -1;
    }
  }
#undef FWVER
  if(mode < 0) return 0;  // for AVR32
  tries = 0;
retry:
  /* Turn the ICE into JTAG or ISP mode as requested. */
  buf[0] = mode;
  if (jtagmkII_setparm(pgm, PAR_EMULATOR_MODE, buf) < 0) {
    if (mode == EMULATOR_MODE_SPI) {
      avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): "
                      "ISP activation failed, trying debugWire\n",
                      progname);
      buf[0] = EMULATOR_MODE_DEBUGWIRE;
      if (jtagmkII_setparm(pgm, PAR_EMULATOR_MODE, buf) < 0)
  return -1;
      else {
  /*
   * We are supposed to send a CMND_RESET with the
   * MONCOM_DISABLE flag set right now, and then
   * restart from scratch.
   *
   * As this will make the ICE sign off from USB, so
   * we risk losing our USB connection, it's easier
   * to instruct the user to restart AVRDUDE rather
   * than trying to cope with all this inside the
   * program.
   */
  (void)jtagmkII_reset(pgm, 0x04);
  if (tries++ > 3) {
      avrdude_message(MSG_INFO, "%s: Failed to return from debugWIRE to ISP.\n",
                            progname);
      return -1;
  }
  avrdude_message(MSG_INFO, "%s: Target prepared for ISP, signed off.\n"
                        "%s: Now retrying without power-cycling the target.\n",
                        progname, progname);
        goto retry;
      }
    } else {
      return -1;
    }
  }
  /* GET SYNC forces the target into STOPPED mode */
  buf[0] = CMND_GET_SYNC;
  avrdude_message(MSG_NOTICE2, "%s: jtagmkII_getsync(): Sending get sync command: ",
      progname);
  jtagmkII_send(pgm, buf, 1);
  status = jtagmkII_recv(pgm, &resp);
  if (status <= 0) {
    if (verbose >= 2)
      putc('\n', stderr);
    avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): "
                    "timeout/error communicating with programmer (status %d)\n",
                    progname, status);
    return -1;
  }
  if (verbose >= 3) {
    putc('\n', stderr);
    jtagmkII_prmsg(pgm, resp, status);
  } else if (verbose == 2)
    avrdude_message(MSG_NOTICE2, "0x%02x (%d bytes msg)\n", resp[0], status);
  c = resp[0];
  free(resp);
  if (c != RSP_OK) {
    avrdude_message(MSG_INFO, "%s: jtagmkII_getsync(): "
                    "bad response to set parameter command: %s\n",
                    progname, jtagmkII_get_rc(c));
    return -1;
  }
  return 0;
}
References avrdude_message(), CMND_GET_SIGN_ON, CMND_GET_SYNC, EMULATOR_MODE_DEBUGWIRE, EMULATOR_MODE_JTAG_XMEGA, EMULATOR_MODE_PDI, EMULATOR_MODE_SPI, free(), FWVER, jtagmkII_get_rc(), jtagmkII_prmsg(), jtagmkII_recv(), jtagmkII_reset(), jtagmkII_send(), jtagmkII_setparm(), MAXTRIES, MSG_DEBUG, MSG_INFO, MSG_NOTICE, MSG_NOTICE2, PAR_EMULATOR_MODE, PDATA, pgm, progname, RSP_OK, RSP_SIGN_ON, programmer_t::type, verbose, and void().
Referenced by jtagmkII_dragon_open(), jtagmkII_dragon_open_dw(), jtagmkII_dragon_open_pdi(), jtagmkII_initialize(), jtagmkII_open(), jtagmkII_open32(), jtagmkII_open_dw(), and jtagmkII_open_pdi().
jtagmkII_initpgm()
void jtagmkII_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAGMKII");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtagmkII_initialize;
  pgm->display        = jtagmkII_display;
  pgm->enable         = jtagmkII_enable;
  pgm->disable        = jtagmkII_disable;
  pgm->program_enable = jtagmkII_program_enable_INFO;
  pgm->chip_erase     = jtagmkII_chip_erase;
  pgm->open           = jtagmkII_open;
  pgm->close          = jtagmkII_close;
  pgm->read_byte      = jtagmkII_read_byte;
  pgm->write_byte     = jtagmkII_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtagmkII_paged_write;
  pgm->paged_load     = jtagmkII_paged_load;
  pgm->page_erase     = jtagmkII_page_erase;
  pgm->print_parms    = jtagmkII_print_parms;
  pgm->set_sck_period = jtagmkII_set_sck_period;
  pgm->parseextparams = jtagmkII_parseextparms;
  pgm->setup          = jtagmkII_setup;
  pgm->teardown       = jtagmkII_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_JTAG;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtagmkII_chip_erase(), jtagmkII_close(), jtagmkII_disable(), jtagmkII_display(), jtagmkII_enable(), jtagmkII_initialize(), jtagmkII_open(), jtagmkII_page_erase(), jtagmkII_paged_load(), jtagmkII_paged_write(), jtagmkII_parseextparms(), jtagmkII_print_parms(), jtagmkII_program_enable_INFO(), jtagmkII_read_byte(), jtagmkII_set_sck_period(), jtagmkII_setup(), jtagmkII_teardown(), jtagmkII_write_byte(), programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, programmer_t::parseextparams, pgm, PGM_FL_IS_JTAG, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_sck_period, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtagmkII_pdi_initpgm()
void jtagmkII_pdi_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "JTAGMKII_PDI");
  /*
   * mandatory functions
   */
  pgm->initialize     = jtagmkII_initialize;
  pgm->display        = jtagmkII_display;
  pgm->enable         = jtagmkII_enable;
  pgm->disable        = jtagmkII_disable;
  pgm->program_enable = jtagmkII_program_enable_INFO;
  pgm->chip_erase     = jtagmkII_chip_erase;
  pgm->open           = jtagmkII_open_pdi;
  pgm->close          = jtagmkII_close;
  pgm->read_byte      = jtagmkII_read_byte;
  pgm->write_byte     = jtagmkII_write_byte;
  /*
   * optional functions
   */
  pgm->paged_write    = jtagmkII_paged_write;
  pgm->paged_load     = jtagmkII_paged_load;
  pgm->page_erase     = jtagmkII_page_erase;
  pgm->print_parms    = jtagmkII_print_parms;
  pgm->setup          = jtagmkII_setup;
  pgm->teardown       = jtagmkII_teardown;
  pgm->page_size      = 256;
  pgm->flag           = PGM_FL_IS_PDI;
}
References programmer_t::chip_erase, programmer_t::close, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::flag, programmer_t::initialize, jtagmkII_chip_erase(), jtagmkII_close(), jtagmkII_disable(), jtagmkII_display(), jtagmkII_enable(), jtagmkII_initialize(), jtagmkII_open_pdi(), jtagmkII_page_erase(), jtagmkII_paged_load(), jtagmkII_paged_write(), jtagmkII_print_parms(), jtagmkII_program_enable_INFO(), jtagmkII_read_byte(), jtagmkII_setup(), jtagmkII_teardown(), jtagmkII_write_byte(), programmer_t::open, programmer_t::page_erase, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, PGM_FL_IS_PDI, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::setup, programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
jtagmkII_recv()
int jtagmkII_recv (PROGRAMMER * pgm, unsigned char ** msg)
{
  unsigned short r_seqno;
  int rv;
  for (;;) {
    if ((rv = jtagmkII_recv_frame(pgm, msg, &r_seqno)) <= 0)
      return rv;
    avrdude_message(MSG_DEBUG, "%s: jtagmkII_recv(): "
        "Got message seqno %d (command_sequence == %d)\n",
        progname, r_seqno, PDATA(pgm)->command_sequence);
    if (r_seqno == PDATA(pgm)->command_sequence) {
      if (++(PDATA(pgm)->command_sequence) == 0xffff)
  PDATA(pgm)->command_sequence = 0;
      /*
       * We move the payload to the beginning of the buffer, to make
       * the job easier for the caller.  We have to return the
       * original pointer though, as the caller must free() it.
       */
      memmove(*msg, *msg + 8, rv);
      if (verbose == 4)
      {
          int i = rv;
          unsigned char *p = *msg;
          avrdude_message(MSG_TRACE, "%s: Recv: ", progname);
          while (i) {
            unsigned char c = *p;
            if (isprint(c)) {
              avrdude_message(MSG_TRACE, "%c ", c);
            }
            else {
              avrdude_message(MSG_TRACE, ". ");
            }
            avrdude_message(MSG_TRACE, "[%02x] ", c);
            p++;
            i--;
          }
          avrdude_message(MSG_TRACE, "\n");
      }
      return rv;
    }
    if (r_seqno == 0xffff) {
      avrdude_message(MSG_DEBUG, "%s: jtagmkII_recv(): got asynchronous event\n",
    progname);
    } else {
      avrdude_message(MSG_NOTICE2, "%s: jtagmkII_recv(): "
    "got wrong sequence number, %u != %u\n",
    progname, r_seqno, PDATA(pgm)->command_sequence);
    }
    free(*msg);
  }
}
References avrdude_message(), free(), jtagmkII_recv_frame(), MSG_DEBUG, MSG_NOTICE2, MSG_TRACE, PDATA, pgm, progname, and verbose.
Referenced by jtagmkII_avr32_reset(), jtagmkII_chip_erase(), jtagmkII_chip_erase32(), jtagmkII_close(), jtagmkII_close32(), jtagmkII_getparm(), jtagmkII_getsync(), jtagmkII_initialize32(), jtagmkII_open32(), jtagmkII_page_erase(), jtagmkII_paged_load(), jtagmkII_paged_load32(), jtagmkII_paged_write(), jtagmkII_paged_write32(), jtagmkII_program_disable(), jtagmkII_program_enable(), jtagmkII_read_byte(), jtagmkII_read_SABaddr(), jtagmkII_reset(), jtagmkII_reset32(), jtagmkII_set_devdescr(), jtagmkII_set_xmega_params(), jtagmkII_setparm(), jtagmkII_write_byte(), and jtagmkII_write_SABaddr().
jtagmkII_send()
int jtagmkII_send (PROGRAMMER * pgm, unsigned char * data, size_t len)
{
  unsigned char *buf;
  avrdude_message(MSG_DEBUG, "\n%s: jtagmkII_send(): sending %lu bytes\n",
      progname, (unsigned long)len);
  if ((buf = malloc(len + 10)) == NULL)
    {
      avrdude_message(MSG_INFO, "%s: jtagmkII_send(): out of memory",
        progname);
      return -1;
    }
  buf[0] = MESSAGE_START;
  u16_to_b2(buf + 1, PDATA(pgm)->command_sequence);
  u32_to_b4(buf + 3, len);
  buf[7] = TOKEN;
  memcpy(buf + 8, data, len);
  crcappend(buf, len + 8);
  if (serial_send(&pgm->fd, buf, len + 10) != 0) {
    avrdude_message(MSG_INFO, "%s: jtagmkII_send(): failed to send command to serial port\n",
                    progname);
    free(buf);
    return -1;
  }
  free(buf);
  return 0;
}
References avrdude_message(), crcappend(), programmer_t::fd, free(), malloc(), MESSAGE_START, MSG_DEBUG, MSG_INFO, PDATA, pgm, progname, serial_send, TOKEN, u16_to_b2(), and u32_to_b4().
Referenced by jtagmkII_avr32_reset(), jtagmkII_chip_erase(), jtagmkII_chip_erase32(), jtagmkII_close(), jtagmkII_close32(), jtagmkII_getparm(), jtagmkII_getsync(), jtagmkII_initialize32(), jtagmkII_open32(), jtagmkII_page_erase(), jtagmkII_paged_load(), jtagmkII_paged_load32(), jtagmkII_paged_write(), jtagmkII_paged_write32(), jtagmkII_program_disable(), jtagmkII_program_enable(), jtagmkII_read_byte(), jtagmkII_read_SABaddr(), jtagmkII_reset(), jtagmkII_reset32(), jtagmkII_set_devdescr(), jtagmkII_set_xmega_params(), jtagmkII_setparm(), jtagmkII_write_byte(), and jtagmkII_write_SABaddr().
jtagmkII_setup()
void jtagmkII_setup (PROGRAMMER * pgm)
{
  if ((pgm->cookie = malloc(sizeof(struct pdata))) == 0) {
    avrdude_message(MSG_INFO, "%s: jtagmkII_setup(): Out of memory allocating private data\n",
                    progname);
    exit(1);
  }
  memset(pgm->cookie, 0, sizeof(struct pdata));
}
References avrdude_message(), programmer_t::cookie, malloc(), MSG_INFO, pgm, and progname.
Referenced by jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), and jtagmkII_pdi_initpgm().
jtagmkII_teardown()
void jtagmkII_teardown (PROGRAMMER * pgm)
{
  free(pgm->cookie);
}
References programmer_t::cookie, free(), and pgm.
Referenced by jtagmkII_avr32_initpgm(), jtagmkII_dragon_dw_initpgm(), jtagmkII_dragon_initpgm(), jtagmkII_dragon_pdi_initpgm(), jtagmkII_dw_initpgm(), jtagmkII_initpgm(), and jtagmkII_pdi_initpgm().
Variable Documentation
jtagmkII_avr32_desc
const char jtagmkII_avr32_desc[] extern
jtagmkII_desc
const char jtagmkII_desc[] extern
jtagmkII_dragon_desc
const char jtagmkII_dragon_desc[] extern
jtagmkII_dragon_dw_desc
const char jtagmkII_dragon_dw_desc[] extern
jtagmkII_dragon_pdi_desc
const char jtagmkII_dragon_pdi_desc[] extern
jtagmkII_dw_desc
const char jtagmkII_dw_desc[] extern
jtagmkII_pdi_desc
const char jtagmkII_pdi_desc[] extern