Prusa Slicer: Slic3r::trianglulate_wall_detail::Triangulator< Sc > Class Template Reference
Slic3r::trianglulate_wall_detail::Triangulator< Sc > Class Template Reference
#include <src/libslic3r/TriangulateWall.hpp>
Public Member Functions
void run (std::vector< Vec3i > &indices)
Triangulator (const std::vector< Vec< 3, Sc > > *points, Ring &lower, Ring &upper)
Private Member Functions
double calc_score () const
void synchronize_rings ()
void emplace_indices (std::vector< Vec3i > &indices)
Private Attributes
const std::vector< Vec< 3, Sc > > * pts
Ring * onring
Ring * offring
Detailed Description
template<class Sc>
class Slic3r::trianglulate_wall_detail::Triangulator< Sc >
Constructor & Destructor Documentation
Triangulator()
template<class Sc > Slic3r::trianglulate_wall_detail::Triangulator< Sc >::Triangulator (const std::vector< Vec< 3, Sc > > * points, Ring & lower, Ring & upper) inline explicit
        : pts{points}, onring{&upper}, offring{&lower}
    {}
Member Function Documentation
calc_score()
template<class Sc > double Slic3r::trianglulate_wall_detail::Triangulator< Sc >::calc_score () const inline private
    {
        return trscore(*onring, *offring, *pts);
    }
References Slic3r::trianglulate_wall_detail::Triangulator< Sc >::offring, Slic3r::trianglulate_wall_detail::Triangulator< Sc >::onring, Slic3r::trianglulate_wall_detail::Triangulator< Sc >::pts, and Slic3r::trianglulate_wall_detail::trscore().
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::run().
emplace_indices()
template<class Sc > void Slic3r::trianglulate_wall_detail::Triangulator< Sc >::emplace_indices (std::vector< Vec3i > & indices) inline private
    {
        Vec3i tr{int(onring->pos().first), int(onring->pos().second),
                 int(offring->pos().first)};
        if (onring->is_lower()) std::swap(tr(0), tr(1));
        indices.emplace_back(tr);
    }
References Slic3r::trianglulate_wall_detail::Ring::is_lower(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::offring, Slic3r::trianglulate_wall_detail::Triangulator< Sc >::onring, and Slic3r::trianglulate_wall_detail::Ring::pos().
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::run().
run()
template<class Sc > void Slic3r::trianglulate_wall_detail::Triangulator< Sc >::run (std::vector< Vec3i > & indices) inline
    {
        synchronize_rings();
        double score = 0, prev_score = 0;
        while (!onring->is_finished() || !offring->is_finished()) {
            prev_score = score;
            if (onring->is_finished() || (score = calc_score()) > prev_score) {
                std::swap(onring, offring);
            } else {
                emplace_indices(indices);
                onring->inc();
            }
        }
    }
References Slic3r::trianglulate_wall_detail::Triangulator< Sc >::calc_score(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::emplace_indices(), Slic3r::trianglulate_wall_detail::Ring::inc(), Slic3r::trianglulate_wall_detail::Ring::is_finished(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::offring, Slic3r::trianglulate_wall_detail::Triangulator< Sc >::onring, and Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings().
synchronize_rings()
template<class Sc > void Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings () inline private
    {
        Ring lring = *offring;
        auto minsc = trscore(*onring, lring, *pts);
        size_t imin = lring.pos().first;
        lring.inc();
        while(!lring.is_finished()) {
            double score = trscore(*onring, lring, *pts);
            if (score < minsc) { minsc = score; imin = lring.pos().first; }
            lring.inc();
        }
        offring->init(imin);
    }
References Slic3r::trianglulate_wall_detail::Ring::inc(), Slic3r::trianglulate_wall_detail::Ring::init(), Slic3r::trianglulate_wall_detail::Ring::is_finished(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::offring, Slic3r::trianglulate_wall_detail::Triangulator< Sc >::onring, Slic3r::trianglulate_wall_detail::Ring::pos(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::pts, and Slic3r::trianglulate_wall_detail::trscore().
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::run().
Member Data Documentation
offring
template<class Sc > Ring * Slic3r::trianglulate_wall_detail::Triangulator< Sc >::offring private
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::calc_score(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::emplace_indices(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::run(), and Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings().
onring
template<class Sc > Ring* Slic3r::trianglulate_wall_detail::Triangulator< Sc >::onring private
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::calc_score(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::emplace_indices(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::run(), and Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings().
pts
template<class Sc > const std::vector<Vec<3, Sc> >* Slic3r::trianglulate_wall_detail::Triangulator< Sc >::pts private
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::calc_score(), and Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings().
The documentation for this class was generated from the following file:
src/libslic3r/TriangulateWall.hpp