Prusa Slicer: Slic3r::FlashAir Class Reference
Slic3r::FlashAir Class Reference
#include <src/slic3r/Utils/FlashAir.hpp>
Public Types
typedef Http::ProgressFn ProgressFn
typedef std::function< void(wxString)> ErrorFn
typedef std::function< void(wxString, wxString)> InfoFn
Public Member Functions
FlashAir (DynamicPrintConfig *config)
~FlashAir () override=default
const char * get_name () const override
bool test (wxString &curl_msg) const override
wxString get_test_ok_msg () const override
wxString get_test_failed_msg (wxString &msg) const override
bool upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const override
bool has_auto_discovery () const override
bool can_test () const override
PrintHostPostUploadActions get_post_upload_actions () const override
std::string get_host () const override
virtual bool supports_multiple_printers () const
virtual bool get_groups (wxArrayString &) const
virtual bool get_printers (wxArrayString &) const
virtual bool get_storage (wxArrayString &, wxArrayString &) const
Static Public Member Functions
static PrintHost * get_print_host (DynamicPrintConfig *config)
Protected Member Functions
virtual wxString format_error (const std::string &body, const std::string &error, unsigned status) const
Private Member Functions
std::string timestamp_str () const
std::string make_url (const std::string &path) const
std::string make_url (const std::string &path, const std::string &arg, const std::string &val) const
Private Attributes
std::string host
Detailed Description
Member Typedef Documentation
ErrorFn
typedef std::function<void(wxString)> Slic3r::PrintHost::ErrorFn inherited
InfoFn
typedef std::function<void(wxString , wxString)> Slic3r::PrintHost::InfoFn inherited
ProgressFn
typedef Http::ProgressFn Slic3r::PrintHost::ProgressFn inherited
Constructor & Destructor Documentation
FlashAir()
Slic3r::FlashAir::FlashAir (DynamicPrintConfig * config)
                                             :
  host(config->opt_string("print_host"))
{}
~FlashAir()
Slic3r::FlashAir::~FlashAir () override default
Member Function Documentation
can_test()
bool Slic3r::FlashAir::can_test () const inline override virtual
Implements Slic3r::PrintHost.
{ return true; }
format_error()
wxString Slic3r::PrintHost::format_error (const std::string & body, const std::string & error, unsigned status) const protected virtual inherited
{
    if (status != 0) {
        auto wxbody = wxString::FromUTF8(body.data());
        return wxString::Format("HTTP %u: %s", status, wxbody);
    } else {
        return wxString::FromUTF8(error.data());
    }
}
References error.
Referenced by Slic3r::Duet::connect(), Slic3r::PrusaLink::post_inner(), Slic3r::PrusaLink::put_inner(), Slic3r::Duet::start_print(), Slic3r::AstroBox::test(), test(), Slic3r::Moonraker::test(), Slic3r::OctoPrint::test(), Slic3r::PrusaLink::test(), Slic3r::Repetier::test(), Slic3r::PrusaLink::test_with_method_check(), Slic3r::AstroBox::upload(), Slic3r::Duet::upload(), upload(), Slic3r::MKS::upload(), Slic3r::Moonraker::upload(), Slic3r::Repetier::upload(), and Slic3r::OctoPrint::upload_inner_with_host().
get_groups()
virtual bool Slic3r::PrintHost::get_groups (wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
get_host()
std::string Slic3r::FlashAir::get_host () const inline override virtual
Implements Slic3r::PrintHost.
{ return host; }
References host.
get_name()
const char * Slic3r::FlashAir::get_name () const override virtual
Implements Slic3r::PrintHost.
{ return "FlashAir"; }
Referenced by test(), and upload().
get_post_upload_actions()
PrintHostPostUploadActions Slic3r::FlashAir::get_post_upload_actions () const inline override virtual
Implements Slic3r::PrintHost.
{ return {}; }
get_print_host()
PrintHost * Slic3r::PrintHost::get_print_host (DynamicPrintConfig * config) static inherited
{
    PrinterTechnology tech = ptFFF;
    {
        const auto opt = config->option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
        if (opt != nullptr) {
            tech = opt->value;
        }
    }
    if (tech == ptFFF) {
        const auto opt = config->option<ConfigOptionEnum<PrintHostType>>("host_type");
        const auto host_type = opt != nullptr ? opt->value : htOctoPrint;
        switch (host_type) {
            case htOctoPrint: return new OctoPrint(config);
            case htDuet:      return new Duet(config);
            case htFlashAir:  return new FlashAir(config);
            case htAstroBox:  return new AstroBox(config);
            case htRepetier:  return new Repetier(config);
            case htPrusaLink: return new PrusaLink(config);
            case htPrusaConnect: return new PrusaConnect(config);
            case htMKS:       return new MKS(config);
            case htMoonraker: return new Moonraker(config);
            default:          return nullptr;
        }
    } else {
        return new SL1Host(config);
    }
}
References Slic3r::htAstroBox, Slic3r::htDuet, Slic3r::htFlashAir, Slic3r::htMKS, Slic3r::htMoonraker, Slic3r::htOctoPrint, Slic3r::htPrusaConnect, Slic3r::htPrusaLink, Slic3r::htRepetier, Slic3r::ConfigBase::option(), Slic3r::ptFFF, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::PhysicalPrinterDialog::update_printers(), and Slic3r::GUI::PhysicalPrinterDialog::update_printhost_buttons().
get_printers()
virtual bool Slic3r::PrintHost::get_printers (wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
get_storage()
virtual bool Slic3r::PrintHost::get_storage (wxArrayString & , wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::PrusaLink, and Slic3r::PrusaConnect.
{ return false; }
get_test_failed_msg()
wxString Slic3r::FlashAir::get_test_failed_msg (wxString & msg) const override virtual
Implements Slic3r::PrintHost.
{
    return GUI::format_wxstr("%s: %s\n%s"
                    , _u8L("Could not connect to FlashAir")
                    , msg
                    , _u8L("Note: FlashAir with firmware 2.00.02 or newer and activated upload function is required."));
}
References _u8L, and Slic3r::GUI::format_wxstr().
get_test_ok_msg()
wxString Slic3r::FlashAir::get_test_ok_msg () const override virtual
Implements Slic3r::PrintHost.
{
  return _(L("Connection to FlashAir works correctly and upload is enabled."));
}
References _, and L.
has_auto_discovery()
bool Slic3r::FlashAir::has_auto_discovery () const inline override virtual
Implements Slic3r::PrintHost.
{ return false; }
make_url() [1/2]
std::string Slic3r::FlashAir::make_url (const std::string & path) const private
{
  if (host.find("http://") == 0 || host.find("https://") == 0) {
    if (host.back() == '/') {
      return (boost::format("%1%%2%") % host % path).str();
    } else {
      return (boost::format("%1%/%2%") % host % path).str();
    }
  } else {
    if (host.back() == '/') {
      return (boost::format("http://%1%%2%") % host % path).str();
    } else {
      return (boost::format("http://%1%/%2%") % host % path).str();
    }
  }
}
References host.
Referenced by test(), and upload().
make_url() [2/2]
std::string Slic3r::FlashAir::make_url (const std::string & path, const std::string & arg, const std::string & val) const private
{
  if (host.find("http://") == 0 || host.find("https://") == 0) {
    if (host.back() == '/') {
      return (boost::format("%1%%2%?%3%=%4%") % host % path % arg % val).str();
    } else {
      return (boost::format("%1%/%2%?%3%=%4%") % host % path % arg % val).str();
    }
  } else {
    if (host.back() == '/') {
      return (boost::format("http://%1%%2%?%3%=%4%") % host % path % arg % val).str();
    } else {
      return (boost::format("http://%1%/%2%?%3%=%4%") % host % path % arg % val).str();
    }
  }
}
References arg(), and host.
supports_multiple_printers()
virtual bool Slic3r::PrintHost::supports_multiple_printers () const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
test()
bool Slic3r::FlashAir::test (wxString & curl_msg) const override virtual
Implements Slic3r::PrintHost.
{
  // Since the request is performed synchronously here,
  // it is ok to refer to `msg` from within the closure
  const char *name = get_name();
  bool res = false;
  auto url = make_url("command.cgi", "op", "118");
  BOOST_LOG_TRIVIAL(info) << boost::format("%1%: Get upload enabled at: %2%") % name % url;
  auto http = Http::get(std::move(url));
  http.on_error([&](std::string body, std::string error, unsigned status) {
      BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Error getting upload enabled: %2%, HTTP %3%, body: `%4%`") % name % error % status % body;
      res = false;
      msg = format_error(body, error, status);
    })
        .on_complete([&](std::string body, unsigned) {
      BOOST_LOG_TRIVIAL(debug) << boost::format("%1%: Got upload enabled: %2%") % name % body;
      res = boost::starts_with(body, "1");
      if (! res) {
        msg = _(L("Upload not enabled on FlashAir card."));
      }
    })
    .perform_sync();
  return res;
}
References _, error, Slic3r::PrintHost::format_error(), Slic3r::Http::get(), get_name(), L, and make_url().
Referenced by upload().
timestamp_str()
std::string Slic3r::FlashAir::timestamp_str () const private
{
  auto t = std::time(nullptr);
  auto tm = *std::localtime(&t);
  unsigned long fattime = ((tm.tm_year - 80) << 25) |
              ((tm.tm_mon + 1) << 21) |
              (tm.tm_mday << 16) |
              (tm.tm_hour << 11) |
              (tm.tm_min << 5) |
              (tm.tm_sec >> 1);
  return (boost::format("%1$#x") % fattime).str();
}
Referenced by upload().
upload()
bool Slic3r::FlashAir::upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn, InfoFn info_fn) const override virtual
Implements Slic3r::PrintHost.
{
  const char *name = get_name();
  const auto upload_filename = upload_data.upload_path.filename();
  const auto upload_parent_path = upload_data.upload_path.parent_path();
  wxString test_msg;
  if (! test(test_msg)) {
    error_fn(std::move(test_msg));
    return false;
  }
  bool res = false;
    std::string strDest = upload_parent_path.string();
    if (strDest.front()!='/') // Needs a leading / else root uploads fail.
    {
        strDest.insert(0,"/");
    }
  auto urlPrepare = make_url("upload.cgi", "WRITEPROTECT=ON&FTIME", timestamp_str());
    auto urlSetDir = make_url("upload.cgi","UPDIR",strDest);
  auto urlUpload = make_url("upload.cgi");
  BOOST_LOG_TRIVIAL(info) << boost::format("%1%: Uploading file %2% at %3% / %4%, filename: %5%")
    % name
    % upload_data.source_path
    % urlPrepare
    % urlUpload
    % upload_filename.string();
  // set filetime for upload and make card writeprotect to prevent filesystem damage
  auto httpPrepare = Http::get(std::move(urlPrepare));
  httpPrepare.on_error([&](std::string body, std::string error, unsigned status) {
            BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Error preparing upload: %2%, HTTP %3%, body: `%4%`") % name % error % status % body;
      error_fn(format_error(body, error, status));
      res = false;
    })
    .on_complete([&, this](std::string body, unsigned) {
      BOOST_LOG_TRIVIAL(debug) << boost::format("%1%: Got prepare result: %2%") % name % body;
      res = boost::icontains(body, "SUCCESS");
      if (! res) {
        BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Request completed but no SUCCESS message was received.") % name;
        error_fn(format_error(body, L("Unknown error occured"), 0));
      }
    })
    .perform_sync();
  if(! res ) {
    return res;
  }
  // start file upload
    auto httpDir = Http::get(std::move(urlSetDir));
    httpDir.on_error([&](std::string body, std::string error, unsigned status) {
            BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Error setting upload dir: %2%, HTTP %3%, body: `%4%`") % name % error % status % body;
            error_fn(format_error(body, error, status));
            res = false;
        })
        .on_complete([&, this](std::string body, unsigned) {
            BOOST_LOG_TRIVIAL(debug) << boost::format("%1%: Got dir select result: %2%") % name % body;
            res = boost::icontains(body, "SUCCESS");
            if (! res) {
                BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Request completed but no SUCCESS message was received.") % name;
                error_fn(format_error(body, L("Unknown error occured"), 0));
            }
        })
        .perform_sync();
    if(! res ) {
        return res;
    }
  auto http = Http::post(std::move(urlUpload));
  http.form_add_file("file", upload_data.source_path.string(), upload_filename.string())
    .on_complete([&](std::string body, unsigned status) {
      BOOST_LOG_TRIVIAL(debug) << boost::format("%1%: File uploaded: HTTP %2%: %3%") % name % status % body;
      res = boost::icontains(body, "SUCCESS");
      if (! res) {
        BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Request completed but no SUCCESS message was received.") % name;
        error_fn(format_error(body, L("Unknown error occured"), 0));
      }
    })
    .on_error([&](std::string body, std::string error, unsigned status) {
      BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Error uploading file: %2%, HTTP %3%, body: `%4%`") % name % error % status % body;
      error_fn(format_error(body, error, status));
      res = false;
    })
    .on_progress([&](Http::Progress progress, bool &cancel) {
      prorgess_fn(std::move(progress), cancel);
      if (cancel) {
        // Upload was canceled
        BOOST_LOG_TRIVIAL(info) << boost::format("%1%: Upload canceled") % name;
        res = false;
      }
    })
    .perform_sync();
  return res;
}
References error, Slic3r::PrintHost::format_error(), Slic3r::Http::get(), get_name(), L, make_url(), Slic3r::Http::post(), Slic3r::PrintHostUpload::source_path, test(), timestamp_str(), and Slic3r::PrintHostUpload::upload_path.
Member Data Documentation
host
std::string Slic3r::FlashAir::host private
Referenced by get_host(), make_url(), and make_url().
The documentation for this class was generated from the following files:
src/slic3r/Utils/FlashAir.hpp
src/slic3r/Utils/FlashAir.cpp