Prusa Slicer: Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex > Class Template Reference
Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex > Class Template Reference
A versatible sparse matrix representation.
#include <src/eigen/Eigen/src/SparseCore/SparseMatrix.h>
Classes
struct default_prunning_func
class SingletonVector
Public Types
enum { Options = _Options }
typedef MappedSparseMatrix< Scalar, Flags > Map
typedef Diagonal< SparseMatrix > DiagonalReturnType
typedef Diagonal< const SparseMatrix > ConstDiagonalReturnType
typedef Base::InnerIterator InnerIterator
typedef Base::ReverseInnerIterator ReverseInnerIterator
typedef internal::CompressedStorage< Scalar, StorageIndex > Storage
typedef Base::IndexVector IndexVector
typedef Base::ScalarVector ScalarVector
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime , MaxRowsAtCompileTime = RowsAtCompileTime ,
MaxColsAtCompileTime = ColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1 , Flags = internal::traits<Derived>::Flags ,
IsRowMajor = Flags&RowMajorBit ? 1 : 0 , InnerSizeAtCompileTime , _HasDirectAccess = (int(Flags)&DirectAccessBit) ? 1 : 0
}
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typenameinternal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< constDerived > >, Transpose< constDerived > >::type AdjointReturnType
typedef Transpose< Derived > TransposeReturnType
typedef internal::add_const< Transpose< constDerived > >::type ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional< _HasDirectAccess, constScalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef Block< Derived, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > InnerVectorReturnType
typedef Block< const Derived, IsRowMajor?1:Dynamic, IsRowMajor?Dynamic:1, true > ConstInnerVectorReturnType
typedef Block< Derived, Dynamic, Dynamic, true > InnerVectorsReturnType
typedef Block< const Derived, Dynamic, Dynamic, true > ConstInnerVectorsReturnType
typedef Eigen::Index Index
The interface type of indices.
Public Member Functions
Index rows () const
Index cols () const
Index innerSize () const
Index outerSize () const
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
Storage & data ()
const Storage & data () const
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
Scalar & insert (Index row, Index col)
void setZero ()
void reserve (Index reserveSize)
template<class SizesType >
void reserve (const SizesType &reserveSizes, const typename SizesType::value_type &enableif=typename SizesType::value_type())
Scalar & insertBack (Index row, Index col)
Scalar & insertBackByOuterInner (Index outer, Index inner)
Scalar & insertBackByOuterInnerUnordered (Index outer, Index inner)
void startVec (Index outer)
void finalize ()
template<typename InputIterators >
void setFromTriplets (const InputIterators &begin, const InputIterators &end)
template<typename InputIterators , typename DupFunctor >
void setFromTriplets (const InputIterators &begin, const InputIterators &end, DupFunctor dup_func)
void sumupDuplicates ()
template<typename DupFunctor >
void collapseDuplicates (DupFunctor dup_func=DupFunctor())
Scalar & insertByOuterInner (Index j, Index i)
void makeCompressed ()
void uncompress ()
void prune (const Scalar &reference, const RealScalar &epsilon=NumTraits< RealScalar >::dummy_precision())
template<typename KeepFunc >
void prune (const KeepFunc &keep=KeepFunc())
void conservativeResize (Index rows, Index cols)
void resize (Index rows, Index cols)
void resizeNonZeros (Index size)
const ConstDiagonalReturnType diagonal () const
DiagonalReturnType diagonal ()
SparseMatrix ()
SparseMatrix (Index rows, Index cols)
template<typename OtherDerived >
SparseMatrix (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived , unsigned int UpLo>
SparseMatrix (const SparseSelfAdjointView< OtherDerived, UpLo > &other)
SparseMatrix (const SparseMatrix &other)
template<typename OtherDerived >
SparseMatrix (const ReturnByValue< OtherDerived > &other)
Copy constructor with in-place evaluation.
template<typename OtherDerived >
SparseMatrix (const DiagonalBase< OtherDerived > &other)
Copy constructor with in-place evaluation.
void swap (SparseMatrix &other)
void setIdentity ()
SparseMatrix & operator= (const SparseMatrix &other)
template<typename OtherDerived >
SparseMatrix & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DONT_INLINE SparseMatrix & operator= (const SparseMatrixBase< OtherDerived > &other)
~SparseMatrix ()
Scalar sum () const
EIGEN_STRONG_INLINE Scalar & insertBackUncompressed (Index row, Index col)
template<typename OtherDerived >
EIGEN_DONT_INLINE SparseMatrix< Scalar, _Options, _StorageIndex > & operator= (const SparseMatrixBase< OtherDerived > &other)
bool isCompressed () const
Index nonZeros () const
const Map< const Array< Scalar, Dynamic, 1 > > coeffs () const
Map< Array< Scalar, Dynamic, 1 > > coeffs ()
const Derived & derived () const
Derived & derived ()
Derived & const_cast_derived () const
Index size () const
bool isVector () const
bool isRValue () const
Derived & markAsRValue ()
template<typename OtherDerived >
Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator*= (const Scalar &other)
template<typename OtherDerived >
Derived & operator*= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator/= (const Scalar &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE const SparseMatrixBase< Derived >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Derived, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
template<int Mode>
const TriangularView< const Derived, Mode > triangularView () const
template<unsigned int UpLo>
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<typename OtherDerived >
Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
InnerVectorReturnType innerVector (Index outer)
const ConstInnerVectorReturnType innerVector (Index outer) const
InnerVectorsReturnType innerVectors (Index outerStart, Index outerSize)
const ConstInnerVectorsReturnType innerVectors (Index outerStart, Index outerSize) const
DenseMatrixType toDense () const
template<typename OtherDerived >
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Derived >::type eval () const
const SparseView< Derived > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Types
typedef SparseMatrix< Scalar,(Flags &~RowMajorBit)|(IsRowMajor?RowMajorBit:0)> TransposedSparseMatrix
Protected Member Functions
template<class SizesType >
void reserveInnerVectors (const SizesType &reserveSizes)
template<typename Other >
void initAssignment (const Other &other)
EIGEN_DONT_INLINE Scalar & insertCompressed (Index row, Index col)
EIGEN_DONT_INLINE Scalar & insertUncompressed (Index row, Index col)
Eigen::Map< IndexVector > innerNonZeros ()
const Eigen::Map< const IndexVector > innerNonZeros () const
template<typename OtherDerived >
Derived & assign (const OtherDerived &other)
template<typename OtherDerived >
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions
static StorageIndex convert_index (const Index idx)
Protected Attributes
Index m_outerSize
Index m_innerSize
StorageIndex * m_outerIndex
StorageIndex * m_innerNonZeros
Storage m_data
bool m_isRValue
Private Types
typedef SparseCompressedBase< SparseMatrix > Base
Private Member Functions
template<typename Dest >
void evalTo (Dest &) const
Static Private Member Functions
static void check_template_parameters ()
Friends
class SparseVector< _Scalar, 0, _StorageIndex >
std::ostream & operator<< (std::ostream &s, const SparseMatrix &m)
Detailed Description
template<typename _Scalar, int _Options, typename _StorageIndex>
class Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >
A versatible sparse matrix representation.
This class implements a more versatile variants of the common compressed row/column storage format. Each colmun's (resp. row) non zeros are stored as a pair of value with associated row (resp. colmiun) index. All the non zeros are stored in a single large buffer. Unlike the compressed format, there might be extra space inbetween the nonzeros of two successive colmuns (resp. rows) such that insertion of new non-zero can be done with limited memory reallocation and copies.
A call to the function makeCompressed() turns the matrix into the standard compressed format compatible with many library.
More details on this storage sceheme are given in the manual pages.
Template Parameters
_Scalar the scalar type, i.e. the type of the coefficients
_Options Union of bit flags controlling the storage scheme. Currently the only possibility is ColMajor or RowMajor. The default is 0 which means column-major.
_StorageIndex the type of the indices. It has to be a signed type (e.g., short, int, std::ptrdiff_t). Default is int.
Warning
In Eigen 3.2, the undocumented type SparseMatrix::Index was improperly defined as the storage index type (e.g., int), whereas it is now (starting from Eigen 3.3) deprecated and always defined as Eigen::Index. Codes making use of SparseMatrix::Index, might thus likely have to be changed to use SparseMatrix::StorageIndex instead.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizing_Plugins by defining the preprocessor symbol EIGEN_SPARSEMATRIX_PLUGIN.
Member Typedef Documentation
AdjointReturnType
template<typename Derived > typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,Eigen::Transpose<constDerived>>,Transpose<constDerived>>::type Eigen::SparseMatrixBase< Derived >::AdjointReturnType inherited
Base
template<typename _Scalar , int _Options, typename _StorageIndex > typedef SparseCompressedBase<SparseMatrix> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::Base private
CoeffReturnType
template<typename Derived > typedef internal::conditional<_HasDirectAccess,constScalar&,Scalar>::type Eigen::SparseMatrixBase< Derived >::CoeffReturnType inherited
ConstantReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,Matrix<Scalar,Dynamic,Dynamic> > Eigen::SparseMatrixBase< Derived >::ConstantReturnType inherited
ConstDiagonalReturnType
template<typename _Scalar , int _Options, typename _StorageIndex > typedef Diagonal<const SparseMatrix> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::ConstDiagonalReturnType
ConstInnerVectorReturnType
template<typename Derived > typedef Block<const Derived,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Derived >::ConstInnerVectorReturnType inherited
ConstInnerVectorsReturnType
template<typename Derived > typedef Block<const Derived,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Derived >::ConstInnerVectorsReturnType inherited
ConstTransposeReturnType
template<typename Derived > typedef internal::add_const<Transpose<constDerived>>::type Eigen::SparseMatrixBase< Derived >::ConstTransposeReturnType inherited
DenseMatrixType
template<typename Derived > typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime> Eigen::SparseMatrixBase< Derived >::DenseMatrixType inherited
type of the equivalent dense matrix
DiagonalReturnType
template<typename _Scalar , int _Options, typename _StorageIndex > typedef Diagonal<SparseMatrix> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::DiagonalReturnType
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
IndexVector
template<typename _Scalar , int _Options, typename _StorageIndex > typedef Base::IndexVector Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IndexVector
InnerIterator
template<typename _Scalar , int _Options, typename _StorageIndex > typedef Base::InnerIterator Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::InnerIterator
InnerVectorReturnType
template<typename Derived > typedef Block<Derived,IsRowMajor?1:Dynamic,IsRowMajor?Dynamic:1,true> Eigen::SparseMatrixBase< Derived >::InnerVectorReturnType inherited
InnerVectorsReturnType
template<typename Derived > typedef Block<Derived,Dynamic,Dynamic,true> Eigen::SparseMatrixBase< Derived >::InnerVectorsReturnType inherited
Map
template<typename _Scalar , int _Options, typename _StorageIndex > typedef MappedSparseMatrix<Scalar,Flags> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::Map
PacketReturnType
template<typename Derived > typedef internal::add_const_on_value_type_if_arithmetic<typenameinternal::packet_traits<Scalar>::type>::type Eigen::SparseMatrixBase< Derived >::PacketReturnType inherited
PacketScalar
template<typename Derived > typedef internal::packet_traits<Scalar>::type Eigen::SparseMatrixBase< Derived >::PacketScalar inherited
PlainObject
template<typename Derived > typedef SparseMatrix<Scalar, Flags&RowMajorBit ? RowMajor : ColMajor, StorageIndex> Eigen::SparseMatrixBase< Derived >::PlainObject inherited
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::SparseMatrixBase< Derived >::RealScalar inherited
This is the "real scalar" type; if the Scalar type is already real numbers (e.g. int, float or double) then RealScalar is just the same as Scalar. If Scalar is std::complex<T> then RealScalar is T.
See also
class NumTraits
ReverseInnerIterator
template<typename _Scalar , int _Options, typename _StorageIndex > typedef Base::ReverseInnerIterator Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::ReverseInnerIterator
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::SparseMatrixBase< Derived >::Scalar inherited
ScalarVector
template<typename _Scalar , int _Options, typename _StorageIndex > typedef Base::ScalarVector Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::ScalarVector
SquareMatrixType
template<typename Derived > typedef Matrix<Scalar,EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime), EIGEN_SIZE_MAX(RowsAtCompileTime,ColsAtCompileTime)> Eigen::SparseMatrixBase< Derived >::SquareMatrixType inherited
type of the equivalent square matrix
Storage
template<typename _Scalar , int _Options, typename _StorageIndex > typedef internal::CompressedStorage<Scalar,StorageIndex> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::Storage
StorageBaseType
template<typename Derived > typedef SparseMatrixBase Eigen::SparseMatrixBase< Derived >::StorageBaseType inherited
StorageIndex
template<typename Derived > typedef internal::traits<Derived>::StorageIndex Eigen::SparseMatrixBase< Derived >::StorageIndex inherited
The integer type used to store indices within a SparseMatrix. For a SparseMatrix<Scalar,Options,IndexType> it an alias of the third template parameter IndexType.
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::SparseMatrixBase< Derived >::StorageKind inherited
TransposedSparseMatrix
template<typename _Scalar , int _Options, typename _StorageIndex > typedef SparseMatrix<Scalar,(Flags&~RowMajorBit)|(IsRowMajor?RowMajorBit:0)> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::TransposedSparseMatrix protected
TransposeReturnType
template<typename Derived > typedef Transpose<Derived> Eigen::SparseMatrixBase< Derived >::TransposeReturnType inherited
value_type
template<typename Derived > typedef Scalar Eigen::SparseMatrixBase< Derived >::value_type inherited
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxSizeAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
InnerSizeAtCompileTime
_HasDirectAccess
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                   internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = RowsAtCompileTime,
      MaxColsAtCompileTime = ColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<MaxRowsAtCompileTime,
                                                      MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1,
      Flags = internal::traits<Derived>::Flags,
      IsRowMajor = Flags&RowMajorBit ? 1 : 0,
      InnerSizeAtCompileTime = int(IsVectorAtCompileTime) ? int(SizeAtCompileTime)
                             : int(IsRowMajor) ? int(ColsAtCompileTime) : int(RowsAtCompileTime),
      #ifndef EIGEN_PARSED_BY_DOXYGEN
      _HasDirectAccess = (int(Flags)&DirectAccessBit) ? 1 : 0 // workaround sunCC
      #endif
    };
anonymous enum
template<typename _Scalar , int _Options, typename _StorageIndex > anonymous enum
Enumerator
Options
         {
      Options = _Options
    };
Constructor & Destructor Documentation
SparseMatrix() [1/7]
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix () inline
Default constructor yielding an empty 0 x 0 matrix
      : m_outerSize(-1), m_innerSize(0), m_outerIndex(0), m_innerNonZeros(0)
    {
      check_template_parameters();
      resize(0, 0);
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::check_template_parameters(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize().
SparseMatrix() [2/7]
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (Index rows, Index cols) inline
Constructs a rows x cols empty matrix
      : m_outerSize(0), m_innerSize(0), m_outerIndex(0), m_innerNonZeros(0)
    {
      check_template_parameters();
      resize(rows, cols);
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::check_template_parameters(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
SparseMatrix() [3/7]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const SparseMatrixBase< OtherDerived > & other) inline
Constructs a sparse matrix from the sparse expression other
      : m_outerSize(0), m_innerSize(0), m_outerIndex(0), m_innerNonZeros(0)
    {
      EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
        YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
      check_template_parameters();
      const bool needToTranspose = (Flags & RowMajorBit) != (internal::evaluator<OtherDerived>::Flags & RowMajorBit);
      if (needToTranspose)
        *this = other.derived();
      else
      {
        #ifdef EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
          EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
        #endif
        internal::call_assignment_no_alias(*this, other.derived());
      }
    }
References Eigen::internal::call_assignment_no_alias(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::check_template_parameters(), Eigen::SparseMatrixBase< Derived >::derived(), EIGEN_STATIC_ASSERT, Eigen::SparseMatrixBase< Derived >::Flags, and Eigen::RowMajorBit.
SparseMatrix() [4/7]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived , unsigned int UpLo> Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const SparseSelfAdjointView< OtherDerived, UpLo > & other) inline
Constructs a sparse matrix from the sparse selfadjoint view other
      : m_outerSize(0), m_innerSize(0), m_outerIndex(0), m_innerNonZeros(0)
    {
      check_template_parameters();
      Base::operator=(other);
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::check_template_parameters(), and Eigen::SparseCompressedBase< Derived >::operator=().
SparseMatrix() [5/7]
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const SparseMatrix< _Scalar, _Options, _StorageIndex > & other) inline
Copy constructor (it performs a deep copy)
      : Base(), m_outerSize(0), m_innerSize(0), m_outerIndex(0), m_innerNonZeros(0)
    {
      check_template_parameters();
      *this = other.derived();
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::check_template_parameters(), and Eigen::SparseMatrixBase< Derived >::derived().
SparseMatrix() [6/7]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const ReturnByValue< OtherDerived > & other) inline
Copy constructor with in-place evaluation.
      : Base(), m_outerSize(0), m_innerSize(0), m_outerIndex(0), m_innerNonZeros(0)
    {
      check_template_parameters();
      initAssignment(other);
      other.evalTo(*this);
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::check_template_parameters(), Eigen::ReturnByValue< Derived >::evalTo(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::initAssignment().
SparseMatrix() [7/7]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix (const DiagonalBase< OtherDerived > & other) inline explicit
Copy constructor with in-place evaluation.
      : Base(), m_outerSize(0), m_innerSize(0), m_outerIndex(0), m_innerNonZeros(0)
    {
      check_template_parameters();
      *this = other.derived();
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::check_template_parameters(), and Eigen::DiagonalBase< Derived >::derived().
~SparseMatrix()
template<typename _Scalar , int _Options, typename _StorageIndex > Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::~SparseMatrix () inline
Destructor
    {
      std::free(m_outerIndex);
      std::free(m_innerNonZeros);
    }
Member Function Documentation
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
template<typename Derived > const AdjointReturnType Eigen::SparseMatrixBase< Derived >::adjoint () const inline inherited
{ return AdjointReturnType(transpose()); }
References Eigen::SparseMatrixBase< Derived >::transpose().
Referenced by Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::_solve_impl(), and Eigen::SparseSelfAdjointView< MatrixType, _Mode >::rankUpdate().
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
assign()
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::assign (const OtherDerived & other) inline protected inherited
assignGeneric()
template<typename Derived > template<typename OtherDerived > void Eigen::SparseMatrixBase< Derived >::assignGeneric (const OtherDerived & other) inline protected inherited
blueNorm()
template<typename Derived > NumTraits< typenameinternal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::blueNorm inline inherited
{
  return internal::blueNorm_impl(*this);
}
References Eigen::internal::blueNorm_impl().
check_template_parameters()
template<typename _Scalar , int _Options, typename _StorageIndex > static void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::check_template_parameters () inline static private
  {
    EIGEN_STATIC_ASSERT(NumTraits<StorageIndex>::IsSigned,THE_INDEX_TYPE_MUST_BE_A_SIGNED_TYPE);
    EIGEN_STATIC_ASSERT((Options&(ColMajor|RowMajor))==Options,INVALID_MATRIX_TEMPLATE_PARAMETERS);
  }
References Eigen::ColMajor, EIGEN_STATIC_ASSERT, and Eigen::RowMajor.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix().
coeff()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff (Index row, Index col) const inline
Returns
the value of the matrix at position i, j This function returns Scalar(0) if the element is an explicit zero
    {
      eigen_assert(row>=0 && row<rows() && col>=0 && col<cols());
      const Index outer = IsRowMajor ? row : col;
      const Index inner = IsRowMajor ? col : row;
      Index end = m_innerNonZeros ? m_outerIndex[outer] + m_innerNonZeros[outer] : m_outerIndex[outer+1];
      return m_data.atInRange(m_outerIndex[outer], end, StorageIndex(inner));
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::atInRange(), col(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), eigen_assert, Eigen::end(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, row(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows().
coeffRef()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef (Index row, Index col) inline
Returns
a non-const reference to the value of the matrix at position i, j
If the element does not exist then it is inserted via the insert(Index,Index) function which itself turns the matrix into a non compressed form if that was not the case.
This is a O(log(nnz_j)) operation (binary search) plus the cost of insert(Index,Index) function if the element does not already exist.
    {
      eigen_assert(row>=0 && row<rows() && col>=0 && col<cols());
      const Index outer = IsRowMajor ? row : col;
      const Index inner = IsRowMajor ? col : row;
      Index start = m_outerIndex[outer];
      Index end = m_innerNonZeros ? m_outerIndex[outer] + m_innerNonZeros[outer] : m_outerIndex[outer+1];
      eigen_assert(end>=start && "you probably called coeffRef on a non finalized matrix");
      if(end<=start)
        return insert(row,col);
      const Index p = m_data.searchLowerIndex(start,end-1,StorageIndex(inner));
      if((p<end) && (m_data.index(p)==inner))
        return m_data.value(p);
      else
        return insert(row,col);
    }
References col(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), eigen_assert, Eigen::end(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, row(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::searchLowerIndex(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
Referenced by igl::adjacency_matrix(), and igl::orientable_patches().
coeffs() [1/2]
Map< Array< Scalar, Dynamic, 1 > > Eigen::SparseCompressedBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::coeffs () inline inherited
Returns
a read-write view of the stored coefficients as a 1D array expression
Warning
this method is for compressed storage only, and it will trigger an assertion otherwise.
Here is an example:
and the output is:
See also
valuePtr(), isCompressed()
{ eigen_assert(isCompressed()); return Array<Scalar,Dynamic,1>::Map(valuePtr(),nonZeros()); }
coeffs() [2/2]
const Map< const Array< Scalar, Dynamic, 1 > > Eigen::SparseCompressedBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::coeffs () const inline inherited
Returns
a read-only view of the stored coefficients as a 1D array expression.
Warning
this method is for compressed storage only, and it will trigger an assertion otherwise.
See also
valuePtr(), isCompressed()
{ eigen_assert(isCompressed()); return Array<Scalar,Dynamic,1>::Map(valuePtr(),nonZeros()); }
collapseDuplicates()
template<typename Scalar , int _Options, typename _StorageIndex > template<typename DupFunctor > void Eigen::SparseMatrix< Scalar, _Options, _StorageIndex >::collapseDuplicates (DupFunctor dup_func = DupFunctor())
{
  eigen_assert(!isCompressed());
  // TODO, in practice we should be able to use m_innerNonZeros for that task
  IndexVector wi(innerSize());
  wi.fill(-1);
  StorageIndex count = 0;
  // for each inner-vector, wi[inner_index] will hold the position of first element into the index/value buffers
  for(Index j=0; j<outerSize(); ++j)
  {
    StorageIndex start   = count;
    Index oldEnd  = m_outerIndex[j]+m_innerNonZeros[j];
    for(Index k=m_outerIndex[j]; k<oldEnd; ++k)
    {
      Index i = m_data.index(k);
      if(wi(i)>=start)
      {
        // we already meet this entry => accumulate it
        m_data.value(wi(i)) = dup_func(m_data.value(wi(i)), m_data.value(k));
      }
      else
      {
        m_data.value(count) = m_data.value(k);
        m_data.index(count) = m_data.index(k);
        wi(i) = count;
        ++count;
      }
    }
    m_outerIndex[j] = start;
  }
  m_outerIndex[m_outerSize] = count;
  // turn the matrix into compressed form
  std::free(m_innerNonZeros);
  m_innerNonZeros = 0;
  m_data.resize(m_outerIndex[m_outerSize]);
}
References eigen_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
Referenced by Eigen::internal::set_from_triplets(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::sumupDuplicates().
cols()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols () const inline
Returns
the number of columns of the matrix
{ return IsRowMajor ? m_innerSize : m_outerSize; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), igl::active_set(), igl::arap_dof_precomputation(), igl::arap_dof_recomputation(), igl::arap_precomputation(), igl::arap_rhs(), igl::AtA_cached_precompute(), igl::bfs(), igl::slim::build_linear_system(), igl::cat(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::cols(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::cols(), Eigen::SimplicialCholeskyBase< Derived >::cols(), Eigen::SparseLU< _MatrixType, _OrderingType >::cols(), Eigen::SparseQR< _MatrixType, _OrderingType >::cols(), Eigen::SuperLUBase< _MatrixType, Derived >::cols(), igl::components(), Eigen::PastixBase< Derived >::compute(), Eigen::SPQR< _MatrixType >::compute(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize(), Eigen::SimplicialCholeskyBase< Derived >::dumpMemory(), igl::eigs(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), igl::find_zero(), igl::harmonic(), igl::harmonic(), igl::harwell_boeing(), igl::matlab_format(), igl::max(), igl::min(), igl::min_quad_with_fixed_precompute(), Eigen::internal::minimum_degree_ordering(), igl::matlab::mlsetmatrix(), igl::mosek::mosek_linprog(), igl::mosek::mosek_quadprog(), igl::matlab::prepare_lhs_double(), igl::redux(), Eigen::MatrixMarketIterator< Scalar >::refX(), igl::repdiag(), igl::repmat(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::MatrixMarketIterator< Scalar >::rhs(), Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run(), igl::matlab::MatlabWorkspace::save(), igl::serialization::serialize(), igl::xml::serialization_xml::serialize(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setIdentity().
conservativeResize()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize (Index rows, Index cols) inline
Resizes the matrix to a rows x cols matrix leaving old values untouched.
If the sizes of the matrix are decreased, then the matrix is turned to uncompressed-mode and the storage of the out of bounds coefficients is kept and reserved. Call makeCompressed() to pack the entries and squeeze extra memory.
See also
reserve(), setZero(), makeCompressed()
    {
      // No change
      if (this->rows() == rows && this->cols() == cols) return;
      // If one dimension is null, then there is nothing to be preserved
      if(rows==0 || cols==0) return resize(rows,cols);
      Index innerChange = IsRowMajor ? cols - this->cols() : rows - this->rows();
      Index outerChange = IsRowMajor ? rows - this->rows() : cols - this->cols();
      StorageIndex newInnerSize = convert_index(IsRowMajor ? cols : rows);
      // Deals with inner non zeros
      if (m_innerNonZeros)
      {
        // Resize m_innerNonZeros
        StorageIndex *newInnerNonZeros = static_cast<StorageIndex*>(std::realloc(m_innerNonZeros, (m_outerSize + outerChange) * sizeof(StorageIndex)));
        if (!newInnerNonZeros) internal::throw_std_bad_alloc();
        m_innerNonZeros = newInnerNonZeros;
        for(Index i=m_outerSize; i<m_outerSize+outerChange; i++)
          m_innerNonZeros[i] = 0;
      }
      else if (innerChange < 0)
      {
        // Inner size decreased: allocate a new m_innerNonZeros
        m_innerNonZeros = static_cast<StorageIndex*>(std::malloc((m_outerSize+outerChange+1) * sizeof(StorageIndex)));
        if (!m_innerNonZeros) internal::throw_std_bad_alloc();
        for(Index i = 0; i < m_outerSize; i++)
          m_innerNonZeros[i] = m_outerIndex[i+1] - m_outerIndex[i];
      }
      // Change the m_innerNonZeros in case of a decrease of inner size
      if (m_innerNonZeros && innerChange < 0)
      {
        for(Index i = 0; i < m_outerSize + (std::min)(outerChange, Index(0)); i++)
        {
          StorageIndex &n = m_innerNonZeros[i];
          StorageIndex start = m_outerIndex[i];
          while (n > 0 && m_data.index(start+n-1) >= newInnerSize) --n;
        }
      }
      m_innerSize = newInnerSize;
      // Re-allocate outer index structure if necessary
      if (outerChange == 0)
        return;
      StorageIndex *newOuterIndex = static_cast<StorageIndex*>(std::realloc(m_outerIndex, (m_outerSize + outerChange + 1) * sizeof(StorageIndex)));
      if (!newOuterIndex) internal::throw_std_bad_alloc();
      m_outerIndex = newOuterIndex;
      if (outerChange > 0)
      {
        StorageIndex last = m_outerSize == 0 ? 0 : m_outerIndex[m_outerSize];
        for(Index i=m_outerSize; i<m_outerSize+outerChange+1; i++)
          m_outerIndex[i] = last;
      }
      m_outerSize += outerChange;
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::SparseMatrixBase< Derived >::convert_index(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), and Eigen::internal::throw_std_bad_alloc().
Referenced by igl::shapeup_precomputation().
const_cast_derived()
template<typename Derived > Derived & Eigen::SparseMatrixBase< Derived >::const_cast_derived () const inline inherited
    { return *static_cast<Derived*>(const_cast<SparseMatrixBase*>(this)); }
Referenced by Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::operator SparseMatrixType &(), Eigen::internal::evaluator< SparseVector< _Scalar, _Options, _Index > >::operator SparseVectorType &(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::viewAsCholmod(), and Eigen::viewAsCholmod().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
convert_index()
template<typename Derived > static StorageIndex Eigen::SparseMatrixBase< Derived >::convert_index (const Index idx) inline static protected inherited
{
      return internal::convert_index<StorageIndex>(idx);
    }
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize().
cwiseProduct() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE const SparseMatrixBase< Derived >::template CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
{
  return typename CwiseProductDenseReturnType<OtherDerived>::Type(derived(), other.derived());
}
cwiseProduct() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type Eigen::SparseMatrixBase< Derived >::cwiseProduct (const MatrixBase< OtherDerived > & other) const inherited
Referenced by Eigen::MatrixBase< Derived >::cwiseProduct().
data() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > Storage & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::data () inline
{ return m_data; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data.
data() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > const Storage & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::data () const inline
{ return m_data; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data.
derived() [1/2]
template<typename Derived > Derived & Eigen::SparseMatrixBase< Derived >::derived () inline inherited
{ return *static_cast<Derived*>(this); }
derived() [2/2]
template<typename Derived > const Derived & Eigen::SparseMatrixBase< Derived >::derived () const inline inherited
{ return *static_cast<const Derived*>(this); }
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::DynamicSparseMatrix(), Eigen::Ref< const SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::SparseVector(), Eigen::IterativeSolverBase< Derived >::_solve_impl(), Eigen::SparseSolverBase< Derived >::_solve_impl(), Eigen::CholmodBase< _MatrixType, _UpLo, Derived >::_solve_impl(), Eigen::SparseMatrixBase< Derived >::cols(), Eigen::SparseMatrixBase< Derived >::dot(), Eigen::SparseMatrixBase< Derived >::eval(), Eigen::SparseCompressedBase< Derived >::innerIndexPtr(), Eigen::SparseCompressedBase< Derived >::innerIndexPtr(), Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), Eigen::SparseCompressedBase< Derived >::innerNonZeroPtr(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), Eigen::SparseCompressedBase< Derived >::innerNonZeros(), Eigen::SparseMatrixBase< Derived >::isApprox(), Eigen::SluMatrix::Map(), Eigen::SparseMatrixBase< Derived >::markAsRValue(), Eigen::SparseCompressedBase< Derived >::nonZeros(), Eigen::SparseMatrixBase< Derived >::operator*(), Eigen::operator*(), Eigen::SparseMatrixBase< Derived >::operator*(), Eigen::operator*(), Eigen::SparseMatrixBase< Derived >::operator*(), Eigen::SparseSelfAdjointView< MatrixType, _Mode >::operator*(), Eigen::operator*(), Eigen::operator*(), Eigen::SparseMatrixBase< Derived >::operator+=(), Eigen::SparseMatrixBase< Derived >::operator-=(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrixBase< Derived >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseCompressedBase< Derived >::outerIndexPtr(), Eigen::SparseCompressedBase< Derived >::outerIndexPtr(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), Eigen::SparseMatrixBase< Derived >::rows(), Eigen::SparseQR< _MatrixType, _OrderingType >::solve(), Eigen::SparseMatrixBase< Derived >::toDense(), Eigen::SparseMatrixBase< Derived >::transpose(), Eigen::SparseMatrixBase< Derived >::transpose(), Eigen::SparseMatrixBase< Derived >::twistedBy(), Eigen::SparseCompressedBase< Derived >::valuePtr(), and Eigen::SparseCompressedBase< Derived >::valuePtr().
diagonal() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > DiagonalReturnType Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::diagonal () inline
Returns
a read-write expression of the diagonal coefficients.
Warning
If the diagonal entries are written, then all diagonal entries must already exist, otherwise an assertion will be raised.
{ return DiagonalReturnType(*this); }
diagonal() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > const ConstDiagonalReturnType Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::diagonal () const inline
Returns
a const expression of the diagonal coefficients.
{ return ConstDiagonalReturnType(*this); }
Referenced by igl::biharmonic_coordinates(), Eigen::SimplicialLLT< _MatrixType, _UpLo, _Ordering >::determinant(), igl::eigs(), and Eigen::MatrixMarketIterator< Scalar >::matrix().
dot() [1/4]
template<typename Derived > template<typename OtherDerived > internal::traits< Derived >::Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  eigen_assert(other.size()>0 && "you are using a non initialized vector");
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  Scalar res(0);
  while (i)
  {
    res += numext::conj(i.value()) * other.coeff(i.index());
    ++i;
  }
  return res;
}
References eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
dot() [2/4]
template<typename Derived > template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const MatrixBase< OtherDerived > & other) const inherited
dot() [3/4]
template<typename Derived > template<typename OtherDerived > internal::traits< Derived >::Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
  EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE(Derived,OtherDerived)
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
    YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  eigen_assert(size() == other.size());
  internal::evaluator<Derived> thisEval(derived());
  typename internal::evaluator<Derived>::InnerIterator i(thisEval, 0);
  internal::evaluator<OtherDerived>  otherEval(other.derived());
  typename internal::evaluator<OtherDerived>::InnerIterator j(otherEval, 0);
  Scalar res(0);
  while (i && j)
  {
    if (i.index()==j.index())
    {
      res += numext::conj(i.value()) * j.value();
      ++i; ++j;
    }
    else if (i.index()<j.index())
      ++i;
    else
      ++j;
  }
  return res;
}
References Eigen::SparseMatrixBase< Derived >::derived(), eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_SAME_VECTOR_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::SparseMatrixBase< Derived >::size().
dot() [4/4]
template<typename Derived > template<typename OtherDerived > Scalar Eigen::SparseMatrixBase< Derived >::dot (const SparseMatrixBase< OtherDerived > & other) const inherited
eval()
template<typename Derived > const internal::eval< Derived >::type Eigen::SparseMatrixBase< Derived >::eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
    { return typename internal::eval<Derived>::type(derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by igl::biharmonic_coordinates().
evalTo()
template<typename Derived > template<typename Dest > void Eigen::SparseMatrixBase< Derived >::evalTo (Dest &) const private inherited
finalize()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize () inline
    {
      if(isCompressed())
      {
        StorageIndex size = internal::convert_index<StorageIndex>(m_data.size());
        Index i = m_outerSize;
        // find the last filled column
        while (i>=0 && m_outerIndex[i]==0)
          --i;
        ++i;
        while (i<=m_outerSize)
        {
          m_outerIndex[i] = size;
          ++i;
        }
      }
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::isCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), and Eigen::SparseMatrixBase< Derived >::size().
Referenced by igl::repmat(), and igl::speye().
initAssignment()
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename Other > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::initAssignment (const Other & other) inline protected
    {
      resize(other.rows(), other.cols());
      if(m_innerNonZeros)
      {
        std::free(m_innerNonZeros);
        m_innerNonZeros = 0;
      }
    }
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=().
innerIndexPtr() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > StorageIndex * Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr () inline
Returns
a non-const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See also
valuePtr(), outerIndexPtr()
{ return m_data.indexPtr(); }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::indexPtr(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data.
innerIndexPtr() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > const StorageIndex * Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr () const inline
Returns
a const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See also
valuePtr(), outerIndexPtr()
{ return m_data.indexPtr(); }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::indexPtr(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data.
Referenced by Eigen::PastixBase< Derived >::analyzePattern(), igl::AtA_cached_precompute(), Eigen::PastixBase< Derived >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::internal::minimum_degree_ordering(), Eigen::internal::permute_symm_to_symm(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
innerNonZeroPtr() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > StorageIndex * Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerNonZeroPtr () inline
Returns
a non-const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
{ return m_innerNonZeros; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros.
innerNonZeroPtr() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > const StorageIndex * Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerNonZeroPtr () const inline
Returns
a const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
{ return m_innerNonZeros; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros.
innerNonZeros() [1/2]
Eigen::Map< IndexVector > Eigen::SparseCompressedBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::innerNonZeros () inline protected inherited
{ return Eigen::Map<IndexVector>(innerNonZeroPtr(), isCompressed()?0:derived().outerSize()); }
innerNonZeros() [2/2]
const Eigen::Map< const IndexVector > Eigen::SparseCompressedBase< SparseMatrix< _Scalar, _Options, _StorageIndex > >::innerNonZeros () const inline protected inherited
{ return Eigen::Map<const IndexVector>(innerNonZeroPtr(), isCompressed()?0:derived().outerSize()); }
innerSize()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerSize () const inline
Returns
the number of rows (resp. columns) of the matrix if the storage order column major (resp. row major)
{ return m_innerSize; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize.
innerVector() [1/2]
template<typename Derived > SparseMatrixBase< Derived >::InnerVectorReturnType Eigen::SparseMatrixBase< Derived >::innerVector (Index outer) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{ return InnerVectorReturnType(derived(), outer); }
innerVector() [2/2]
template<typename Derived > const SparseMatrixBase< Derived >::ConstInnerVectorReturnType Eigen::SparseMatrixBase< Derived >::innerVector (Index outer) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{ return ConstInnerVectorReturnType(derived(), outer); }
innerVectors() [1/2]
template<typename Derived > SparseMatrixBase< Derived >::InnerVectorsReturnType Eigen::SparseMatrixBase< Derived >::innerVectors (Index outerStart, Index outerSize) inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
{
  return Block<Derived,Dynamic,Dynamic,true>(derived(),
                                             IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                             IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
innerVectors() [2/2]
template<typename Derived > const SparseMatrixBase< Derived >::ConstInnerVectorsReturnType Eigen::SparseMatrixBase< Derived >::innerVectors (Index outerStart, Index outerSize) const inherited
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
{
  return Block<const Derived,Dynamic,Dynamic,true>(derived(),
                                                  IsRowMajor ? outerStart : 0, IsRowMajor ? 0 : outerStart,
                                                  IsRowMajor ? outerSize : rows(), IsRowMajor ? cols() : outerSize);
}
insert()
template<typename _Scalar , int _Options, typename _StorageIndex > SparseMatrix< _Scalar, _Options, _StorageIndex >::Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert (Index row, Index col)
Returns
a reference to a novel non zero coefficient with coordinates row x col. The non zero coefficient must not already exist.
If the matrix *this is in compressed mode, then *this is turned into uncompressed mode while reserving room for 2 x this->innerSize() non zeros if reserve(Index) has not been called earlier. In this case, the insertion procedure is optimized for a sequential insertion mode where elements are assumed to be inserted by increasing outer-indices.
If that's not the case, then it is strongly recommended to either use a triplet-list to assemble the matrix, or to first call reserve(const SizesType &) to reserve the appropriate number of non-zero elements per inner vector.
Assuming memory has been appropriately reserved, this function performs a sorted insertion in O(1) if the elements of each inner vector are inserted in increasing inner index order, and in O(nnz_j) for a random insertion.
{
  eigen_assert(row>=0 && row<rows() && col>=0 && col<cols());
  const Index outer = IsRowMajor ? row : col;
  const Index inner = IsRowMajor ? col : row;
  if(isCompressed())
  {
    if(nonZeros()==0)
    {
      // reserve space if not already done
      if(m_data.allocatedSize()==0)
        m_data.reserve(2*m_innerSize);
      // turn the matrix into non-compressed mode
      m_innerNonZeros = static_cast<StorageIndex*>(std::malloc(m_outerSize * sizeof(StorageIndex)));
      if(!m_innerNonZeros) internal::throw_std_bad_alloc();
      memset(m_innerNonZeros, 0, (m_outerSize)*sizeof(StorageIndex));
      // pack all inner-vectors to the end of the pre-allocated space
      // and allocate the entire free-space to the first inner-vector
      StorageIndex end = convert_index(m_data.allocatedSize());
      for(Index j=1; j<=m_outerSize; ++j)
        m_outerIndex[j] = end;
    }
    else
    {
      // turn the matrix into non-compressed mode
      m_innerNonZeros = static_cast<StorageIndex*>(std::malloc(m_outerSize * sizeof(StorageIndex)));
      if(!m_innerNonZeros) internal::throw_std_bad_alloc();
      for(Index j=0; j<m_outerSize; ++j)
        m_innerNonZeros[j] = m_outerIndex[j+1]-m_outerIndex[j];
    }
  }
  // check whether we can do a fast "push back" insertion
  Index data_end = m_data.allocatedSize();
  // First case: we are filling a new inner vector which is packed at the end.
  // We assume that all remaining inner-vectors are also empty and packed to the end.
  if(m_outerIndex[outer]==data_end)
  {
    eigen_internal_assert(m_innerNonZeros[outer]==0);
    // pack previous empty inner-vectors to end of the used-space
    // and allocate the entire free-space to the current inner-vector.
    StorageIndex p = convert_index(m_data.size());
    Index j = outer;
    while(j>=0 && m_innerNonZeros[j]==0)
      m_outerIndex[j--] = p;
    // push back the new element
    ++m_innerNonZeros[outer];
    m_data.append(Scalar(0), inner);
    // check for reallocation
    if(data_end != m_data.allocatedSize())
    {
      // m_data has been reallocated
      //  -> move remaining inner-vectors back to the end of the free-space
      //     so that the entire free-space is allocated to the current inner-vector.
      eigen_internal_assert(data_end < m_data.allocatedSize());
      StorageIndex new_end = convert_index(m_data.allocatedSize());
      for(Index k=outer+1; k<=m_outerSize; ++k)
        if(m_outerIndex[k]==data_end)
          m_outerIndex[k] = new_end;
    }
    return m_data.value(p);
  }
  // Second case: the next inner-vector is packed to the end
  // and the current inner-vector end match the used-space.
  if(m_outerIndex[outer+1]==data_end && m_outerIndex[outer]+m_innerNonZeros[outer]==m_data.size())
  {
    eigen_internal_assert(outer+1==m_outerSize || m_innerNonZeros[outer+1]==0);
    // add space for the new element
    ++m_innerNonZeros[outer];
    m_data.resize(m_data.size()+1);
    // check for reallocation
    if(data_end != m_data.allocatedSize())
    {
      // m_data has been reallocated
      //  -> move remaining inner-vectors back to the end of the free-space
      //     so that the entire free-space is allocated to the current inner-vector.
      eigen_internal_assert(data_end < m_data.allocatedSize());
      StorageIndex new_end = convert_index(m_data.allocatedSize());
      for(Index k=outer+1; k<=m_outerSize; ++k)
        if(m_outerIndex[k]==data_end)
          m_outerIndex[k] = new_end;
    }
    // and insert it at the right position (sorted insertion)
    Index startId = m_outerIndex[outer];
    Index p = m_outerIndex[outer]+m_innerNonZeros[outer]-1;
    while ( (p > startId) && (m_data.index(p-1) > inner) )
    {
      m_data.index(p) = m_data.index(p-1);
      m_data.value(p) = m_data.value(p-1);
      --p;
    }
    m_data.index(p) = convert_index(inner);
    return (m_data.value(p) = 0);
  }
  if(m_data.size() != m_data.allocatedSize())
  {
    // make sure the matrix is compatible to random un-compressed insertion:
    m_data.resize(m_data.allocatedSize());
    this->reserveInnerVectors(Array<StorageIndex,Dynamic,1>::Constant(m_outerSize, 2));
  }
  return insertUncompressed(row,col);
}
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::allocatedSize(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append(), col(), eigen_assert, eigen_internal_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), row(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
Referenced by igl::cat(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), igl::group_sum_matrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertByOuterInner(), igl::lbs_matrix_column(), igl::lbs_matrix_column(), igl::repdiag(), igl::repmat(), and igl::speye().
insertBack()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack (Index row, Index col) inline
    {
      return insertBackByOuterInner(IsRowMajor?row:col, IsRowMajor?col:row);
    }
References col(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, and row().
insertBackByOuterInner()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner (Index outer, Index inner) inline
    {
      eigen_assert(Index(m_outerIndex[outer+1]) == m_data.size() && "Invalid ordered insertion (invalid outer index)");
      eigen_assert( (m_outerIndex[outer+1]-m_outerIndex[outer]==0 || m_data.index(m_data.size()-1)<inner) && "Invalid ordered insertion (invalid inner index)");
      Index p = m_outerIndex[outer+1];
      ++m_outerIndex[outer+1];
      m_data.append(Scalar(0), inner);
      return m_data.value(p);
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append(), eigen_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack().
insertBackByOuterInnerUnordered()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInnerUnordered (Index outer, Index inner) inline
    {
      Index p = m_outerIndex[outer+1];
      ++m_outerIndex[outer+1];
      m_data.append(Scalar(0), inner);
      return m_data.value(p);
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::append(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
insertBackUncompressed()
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_STRONG_INLINE Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackUncompressed (Index row, Index col) inline
    {
      const Index outer = IsRowMajor ? row : col;
      const Index inner = IsRowMajor ? col : row;
      eigen_assert(!isCompressed());
      eigen_assert(m_innerNonZeros[outer]<=(m_outerIndex[outer+1] - m_outerIndex[outer]));
      Index p = m_outerIndex[outer] + m_innerNonZeros[outer]++;
      m_data.index(p) = convert_index(inner);
      return (m_data.value(p) = Scalar(0));
    }
References col(), eigen_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), row(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
Referenced by Eigen::internal::set_from_triplets().
insertByOuterInner()
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertByOuterInner (Index j, Index i) inline
    {
      return insert(IsRowMajor ? j : i, IsRowMajor ? i : j);
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor.
Referenced by Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run().
insertCompressed()
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DONT_INLINE SparseMatrix< _Scalar, _Options, _StorageIndex >::Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed (Index row, Index col) protected
{
  eigen_assert(isCompressed());
  const Index outer = IsRowMajor ? row : col;
  const Index inner = IsRowMajor ? col : row;
  Index previousOuter = outer;
  if (m_outerIndex[outer+1]==0)
  {
    // we start a new inner vector
    while (previousOuter>=0 && m_outerIndex[previousOuter]==0)
    {
      m_outerIndex[previousOuter] = convert_index(m_data.size());
      --previousOuter;
    }
    m_outerIndex[outer+1] = m_outerIndex[outer];
  }
  // here we have to handle the tricky case where the outerIndex array
  // starts with: [ 0 0 0 0 0 1 ...] and we are inserted in, e.g.,
  // the 2nd inner vector...
  bool isLastVec = (!(previousOuter==-1 && m_data.size()!=0))
                && (std::size_t(m_outerIndex[outer+1]) == m_data.size());
  std::size_t startId = m_outerIndex[outer];
  // FIXME let's make sure sizeof(long int) == sizeof(std::size_t)
  std::size_t p = m_outerIndex[outer+1];
  ++m_outerIndex[outer+1];
  double reallocRatio = 1;
  if (m_data.allocatedSize()<=m_data.size())
  {
    // if there is no preallocated memory, let's reserve a minimum of 32 elements
    if (m_data.size()==0)
    {
      m_data.reserve(32);
    }
    else
    {
      // we need to reallocate the data, to reduce multiple reallocations
      // we use a smart resize algorithm based on the current filling ratio
      // in addition, we use double to avoid integers overflows
      double nnzEstimate = double(m_outerIndex[outer])*double(m_outerSize)/double(outer+1);
      reallocRatio = (nnzEstimate-double(m_data.size()))/double(m_data.size());
      // furthermore we bound the realloc ratio to:
      //   1) reduce multiple minor realloc when the matrix is almost filled
      //   2) avoid to allocate too much memory when the matrix is almost empty
      reallocRatio = (std::min)((std::max)(reallocRatio,1.5),8.);
    }
  }
  m_data.resize(m_data.size()+1,reallocRatio);
  if (!isLastVec)
  {
    if (previousOuter==-1)
    {
      // oops wrong guess.
      // let's correct the outer offsets
      for (Index k=0; k<=(outer+1); ++k)
        m_outerIndex[k] = 0;
      Index k=outer+1;
      while(m_outerIndex[k]==0)
        m_outerIndex[k++] = 1;
      while (k<=m_outerSize && m_outerIndex[k]!=0)
        m_outerIndex[k++]++;
      p = 0;
      --k;
      k = m_outerIndex[k]-1;
      while (k>0)
      {
        m_data.index(k) = m_data.index(k-1);
        m_data.value(k) = m_data.value(k-1);
        k--;
      }
    }
    else
    {
      // we are not inserting into the last inner vec
      // update outer indices:
      Index j = outer+2;
      while (j<=m_outerSize && m_outerIndex[j]!=0)
        m_outerIndex[j++]++;
      --j;
      // shift data of last vecs:
      Index k = m_outerIndex[j]-1;
      while (k>=Index(p))
      {
        m_data.index(k) = m_data.index(k-1);
        m_data.value(k) = m_data.value(k-1);
        k--;
      }
    }
  }
  while ( (p > startId) && (m_data.index(p-1) > inner) )
  {
    m_data.index(p) = m_data.index(p-1);
    m_data.value(p) = m_data.value(p-1);
    --p;
  }
  m_data.index(p) = inner;
  return (m_data.value(p) = Scalar(0));
}
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::allocatedSize(), col(), eigen_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), row(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
insertUncompressed()
template<typename _Scalar , int _Options, typename _StorageIndex > EIGEN_DONT_INLINE SparseMatrix< _Scalar, _Options, _StorageIndex >::Scalar & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed (Index row, Index col) protected
{
  eigen_assert(!isCompressed());
  const Index outer = IsRowMajor ? row : col;
  const StorageIndex inner = convert_index(IsRowMajor ? col : row);
  Index room = m_outerIndex[outer+1] - m_outerIndex[outer];
  StorageIndex innerNNZ = m_innerNonZeros[outer];
  if(innerNNZ>=room)
  {
    // this inner vector is full, we need to reallocate the whole buffer :(
    reserve(SingletonVector(outer,std::max<StorageIndex>(2,innerNNZ)));
  }
  Index startId = m_outerIndex[outer];
  Index p = startId + m_innerNonZeros[outer];
  while ( (p > startId) && (m_data.index(p-1) > inner) )
  {
    m_data.index(p) = m_data.index(p-1);
    m_data.value(p) = m_data.value(p-1);
    --p;
  }
  eigen_assert((p<=startId || m_data.index(p-1)!=inner) && "you cannot insert an element that already exists, you must call coeffRef to this end");
  m_innerNonZeros[outer]++;
  m_data.index(p) = inner;
  return (m_data.value(p) = Scalar(0));
}
References col(), eigen_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), row(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
isApprox() [1/2]
template<typename Derived > template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inline inherited
    { return toDense().isApprox(other,prec); }
References Eigen::SparseMatrixBase< Derived >::toDense().
isApprox() [2/2]
template<typename Derived > template<typename OtherDerived > bool Eigen::SparseMatrixBase< Derived >::isApprox (const SparseMatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
{
  const typename internal::nested_eval<Derived,2,PlainObject>::type actualA(derived());
  typename internal::conditional<bool(IsRowMajor)==bool(OtherDerived::IsRowMajor),
    const typename internal::nested_eval<OtherDerived,2,PlainObject>::type,
    const PlainObject>::type actualB(other.derived());
  return (actualA - actualB).squaredNorm() <= prec * prec * numext::mini(actualA.squaredNorm(), actualB.squaredNorm());
}
References Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::numext::mini().
isCompressed()
template<typename _Scalar , int _Options, typename _StorageIndex > bool Eigen::SparseCompressedBase< Derived >::isCompressed () const inline
Returns
whether *this is in compressed form.
{ return innerNonZeroPtr()==0; }
Referenced by Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref(), igl::AtA_cached_precompute(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserve(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors().
isRValue()
template<typename Derived > bool Eigen::SparseMatrixBase< Derived >::isRValue () const inline inherited
{ return m_isRValue; }
References Eigen::SparseMatrixBase< Derived >::m_isRValue.
Referenced by Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), and Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=().
isVector()
template<typename Derived > bool Eigen::SparseMatrixBase< Derived >::isVector () const inline inherited
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See also
rows(), cols(), IsVectorAtCompileTime.
{ return rows()==1 || cols()==1; }
References Eigen::SparseMatrixBase< Derived >::cols(), and Eigen::SparseMatrixBase< Derived >::rows().
makeCompressed()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed () inline
Turns the matrix into the compressed format.
    {
      if(isCompressed())
        return;
      eigen_internal_assert(m_outerIndex!=0 && m_outerSize>0);
      Index oldStart = m_outerIndex[1];
      m_outerIndex[1] = m_innerNonZeros[0];
      for(Index j=1; j<m_outerSize; ++j)
      {
        Index nextOldStart = m_outerIndex[j+1];
        Index offset = oldStart - m_outerIndex[j];
        if(offset>0)
        {
          for(Index k=0; k<m_innerNonZeros[j]; ++k)
          {
            m_data.index(m_outerIndex[j]+k) = m_data.index(oldStart+k);
            m_data.value(m_outerIndex[j]+k) = m_data.value(oldStart+k);
          }
        }
        m_outerIndex[j+1] = m_outerIndex[j] + m_innerNonZeros[j];
        oldStart = nextOldStart;
      }
      std::free(m_innerNonZeros);
      m_innerNonZeros = 0;
      m_data.resize(m_outerIndex[m_outerSize]);
      m_data.squeeze();
    }
References eigen_internal_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::isCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::squeeze(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
Referenced by igl::arap_linear_block_elements(), igl::arap_linear_block_spokes(), igl::arap_linear_block_spokes_and_rims(), igl::AtA_cached_precompute(), igl::slim::build_linear_system(), igl::cat(), Eigen::PardisoLU< MatrixType >::getMatrix(), Eigen::PardisoLLT< MatrixType, _UpLo >::getMatrix(), Eigen::PardisoLDLT< MatrixType, Options >::getMatrix(), igl::group_sum_matrix(), igl::lbs_matrix_column(), igl::lbs_matrix_column(), igl::slim::pre_calc(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), igl::repdiag(), Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run(), and igl::slice_cached_precompute().
markAsRValue()
template<typename Derived > Derived & Eigen::SparseMatrixBase< Derived >::markAsRValue () inline inherited
{ m_isRValue = true; return derived(); }
References Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::m_isRValue.
nonZeros()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::SparseCompressedBase< Derived >::nonZeros () const inline
Returns
the number of non zero coefficients
    {
      if(Derived::IsVectorAtCompileTime && outerIndexPtr()==0)
        return derived().nonZeros();
      else if(isCompressed())
        return outerIndexPtr()[derived().outerSize()]-outerIndexPtr()[0];
      else if(derived().outerSize()==0)
        return 0;
      else
        return innerNonZeros().sum();
    }
Referenced by Eigen::SimplicialCholeskyBase< Derived >::_solve_impl(), igl::AtA_cached_precompute(), igl::cat(), Eigen::SimplicialCholeskyBase< Derived >::dumpMemory(), igl::edges(), igl::serialization::getByteSize(), igl::harwell_boeing(), igl::min_quad_with_fixed_precompute(), Eigen::internal::minimum_degree_ordering(), igl::matlab::mlsetmatrix(), igl::matlab::prepare_lhs_double(), igl::repdiag(), igl::repmat(), igl::matlab::MatlabWorkspace::save(), igl::serialization::serialize(), and igl::slice_cached_precompute().
norm()
template<typename Derived > NumTraits< typenameinternal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::norm inline inherited
{
  using std::sqrt;
  return sqrt(squaredNorm());
}
References sqrt().
Referenced by Eigen::SPQR< _MatrixType >::compute(), and Eigen::MatrixMarketIterator< Scalar >::matrix().
operator*() [1/3]
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived > Eigen::SparseMatrixBase< Derived >::operator* (const DiagonalBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
References Eigen::DiagonalBase< Derived >::derived(), and Eigen::SparseMatrixBase< Derived >::derived().
operator*() [2/3]
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived > Eigen::SparseMatrixBase< Derived >::operator* (const MatrixBase< OtherDerived > & other) const inline inherited
    { return Product<Derived,OtherDerived>(derived(), other.derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
operator*() [3/3]
template<typename Derived > template<typename OtherDerived > const Product< Derived, OtherDerived, AliasFreeProduct > Eigen::SparseMatrixBase< Derived >::operator* (const SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the product of two sparse matrices. By default a conservative product preserving the symbolic non zeros is performed. The automatic pruning of the small values can be achieved by calling the pruned() function in which case a totally different product algorithm is employed:
C = (A*B).pruned();             // supress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return Product<Derived,OtherDerived,AliasFreeProduct>(derived(), other.derived());
}
References Eigen::SparseMatrixBase< Derived >::derived().
operator*=() [1/2]
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator*= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() *= other;
  return derived();
}
operator*=() [2/2]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator*= (const SparseMatrixBase< OtherDerived > & other) inherited
operator+=() [1/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
References Eigen::DiagonalBase< Derived >::derived().
operator+=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
References Eigen::EigenBase< Derived >::derived().
operator+=() [3/4]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() + other.derived();
}
References Eigen::SparseMatrixBase< Derived >::derived().
operator+=() [4/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator+= (const SparseMatrixBase< OtherDerived > & other) inherited
operator-=() [1/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const DiagonalBase< OtherDerived > & other) inherited
{
  call_assignment_no_alias(derived(), other.derived(), internal::sub_assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
References Eigen::DiagonalBase< Derived >::derived().
operator-=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const EigenBase< OtherDerived > & other) inherited
{
  call_assignment(derived(), other.derived(), internal::assign_op<Scalar,typename OtherDerived::Scalar>());
  return derived();
}
References Eigen::EigenBase< Derived >::derived().
operator-=() [3/4]
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
{
  return derived() = derived() - other.derived();
}
References Eigen::SparseMatrixBase< Derived >::derived().
operator-=() [4/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator-= (const SparseMatrixBase< OtherDerived > & other) inherited
operator/=()
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::SparseMatrixBase< Derived >::operator/= (const Scalar & other) inherited
{
  typedef typename internal::evaluator<Derived>::InnerIterator EvalIterator;
  internal::evaluator<Derived> thisEval(derived());
  for (Index j=0; j<outerSize(); ++j)
    for (EvalIterator i(thisEval,j); i; ++i)
      i.valueRef() /= other;
  return derived();
}
operator=() [1/4]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > SparseMatrix & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator= (const EigenBase< OtherDerived > & other) inline
    { return Base::operator=(other.derived()); }
References Eigen::EigenBase< Derived >::derived(), and Eigen::SparseCompressedBase< Derived >::operator=().
operator=() [2/4]
template<typename _Scalar , int _Options, typename _StorageIndex > SparseMatrix & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator= (const SparseMatrix< _Scalar, _Options, _StorageIndex > & other) inline
    {
      if (other.isRValue())
      {
        swap(other.const_cast_derived());
      }
      else if(this!=&other)
      {
        #ifdef EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
          EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
        #endif
        initAssignment(other);
        if(other.isCompressed())
        {
          internal::smart_copy(other.m_outerIndex, other.m_outerIndex + m_outerSize + 1, m_outerIndex);
          m_data = other.m_data;
        }
        else
        {
          Base::operator=(other);
        }
      }
      return *this;
    }
References Eigen::SparseMatrixBase< Derived >::const_cast_derived(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::initAssignment(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::isCompressed(), Eigen::SparseMatrixBase< Derived >::isRValue(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize, Eigen::SparseCompressedBase< Derived >::operator=(), Eigen::internal::smart_copy(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::swap().
operator=() [3/4]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > EIGEN_DONT_INLINE SparseMatrix & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator= (const SparseMatrixBase< OtherDerived > & other)
operator=() [4/4]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename OtherDerived > EIGEN_DONT_INLINE SparseMatrix< Scalar, _Options, _StorageIndex > & Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator= (const SparseMatrixBase< OtherDerived > & other)
{
  EIGEN_STATIC_ASSERT((internal::is_same<Scalar, typename OtherDerived::Scalar>::value),
        YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
  #ifdef EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
    EIGEN_SPARSE_CREATE_TEMPORARY_PLUGIN
  #endif
  const bool needToTranspose = (Flags & RowMajorBit) != (internal::evaluator<OtherDerived>::Flags & RowMajorBit);
  if (needToTranspose)
  {
    #ifdef EIGEN_SPARSE_TRANSPOSED_COPY_PLUGIN
      EIGEN_SPARSE_TRANSPOSED_COPY_PLUGIN
    #endif
    // two passes algorithm:
    //  1 - compute the number of coeffs per dest inner vector
    //  2 - do the actual copy/eval
    // Since each coeff of the rhs has to be evaluated twice, let's evaluate it if needed
    typedef typename internal::nested_eval<OtherDerived,2,typename internal::plain_matrix_type<OtherDerived>::type >::type OtherCopy;
    typedef typename internal::remove_all<OtherCopy>::type _OtherCopy;
    typedef internal::evaluator<_OtherCopy> OtherCopyEval;
    OtherCopy otherCopy(other.derived());
    OtherCopyEval otherCopyEval(otherCopy);
    SparseMatrix dest(other.rows(),other.cols());
    Eigen::Map<IndexVector> (dest.m_outerIndex,dest.outerSize()).setZero();
    // pass 1
    // FIXME the above copy could be merged with that pass
    for (Index j=0; j<otherCopy.outerSize(); ++j)
      for (typename OtherCopyEval::InnerIterator it(otherCopyEval, j); it; ++it)
        ++dest.m_outerIndex[it.index()];
    // prefix sum
    StorageIndex count = 0;
    IndexVector positions(dest.outerSize());
    for (Index j=0; j<dest.outerSize(); ++j)
    {
      StorageIndex tmp = dest.m_outerIndex[j];
      dest.m_outerIndex[j] = count;
      positions[j] = count;
      count += tmp;
    }
    dest.m_outerIndex[dest.outerSize()] = count;
    // alloc
    dest.m_data.resize(count);
    // pass 2
    for (StorageIndex j=0; j<otherCopy.outerSize(); ++j)
    {
      for (typename OtherCopyEval::InnerIterator it(otherCopyEval, j); it; ++it)
      {
        Index pos = positions[it.index()]++;
        dest.m_data.index(pos) = j;
        dest.m_data.value(pos) = it.value();
      }
    }
    this->swap(dest);
    return *this;
  }
  else
  {
    if(other.isRValue())
    {
      initAssignment(other.derived());
    }
    // there is no special optimization
    return Base::operator=(other.derived());
  }
}
References Eigen::SparseMatrixBase< Derived >::cols(), Eigen::SparseMatrixBase< Derived >::derived(), EIGEN_STATIC_ASSERT, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::SparseMatrixBase< Derived >::isRValue(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), Eigen::RowMajorBit, Eigen::SparseMatrixBase< Derived >::rows(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
outerIndexPtr() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > StorageIndex * Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr () inline
Returns
a non-const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
See also
valuePtr(), innerIndexPtr()
{ return m_outerIndex; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex.
outerIndexPtr() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > const StorageIndex * Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr () const inline
Returns
a const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
See also
valuePtr(), innerIndexPtr()
{ return m_outerIndex; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex.
Referenced by Eigen::PastixBase< Derived >::analyzePattern(), igl::AtA_cached_precompute(), Eigen::PastixBase< Derived >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::internal::minimum_degree_ordering(), and Eigen::internal::permute_symm_to_symm().
outerSize()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize () const inline
Returns
the number of columns (resp. rows) of the matrix if the storage order column major (resp. row major)
{ return m_outerSize; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize.
Referenced by igl::adjacency_matrix(), igl::PlanarizerShapeUp< DerivedV, DerivedF >::assembleQ(), igl::AtA_cached_precompute(), igl::slim::buildA(), igl::cat(), igl::components(), igl::edges(), igl::for_each(), Eigen::PastixLU< _MatrixType, IsStrSym >::grabMatrix(), igl::harwell_boeing(), igl::isdiag(), igl::matlab::mlsetmatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), igl::orientable_patches(), igl::matlab::prepare_lhs_double(), igl::repdiag(), igl::repmat(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), igl::matlab::MatlabWorkspace::save(), igl::serialization::serialize(), igl::xml::serialization_xml::serialize(), Eigen::internal::set_from_triplets(), and Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap().
prune() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > template<typename KeepFunc > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune (const KeepFunc & keep = KeepFunc()) inline
Turns the matrix into compressed format, and suppresses all nonzeros which do not satisfy the predicate keep. The functor type KeepFunc must implement the following function:
bool operator() (const Index& row, const Index& col, const Scalar& value) const;
See also
prune(Scalar,RealScalar)
    {
      // TODO optimize the uncompressed mode to avoid moving and allocating the data twice
      makeCompressed();
      StorageIndex k = 0;
      for(Index j=0; j<m_outerSize; ++j)
      {
        Index previousStart = m_outerIndex[j];
        m_outerIndex[j] = k;
        Index end = m_outerIndex[j+1];
        for(Index i=previousStart; i<end; ++i)
        {
          if(keep(IsRowMajor?j:m_data.index(i), IsRowMajor?m_data.index(i):j, m_data.value(i)))
          {
            m_data.value(k) = m_data.value(i);
            m_data.index(k) = m_data.index(i);
            ++k;
          }
        }
      }
      m_outerIndex[m_outerSize] = k;
      m_data.resize(k,0);
    }
References Eigen::end(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
prune() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune (const Scalar & reference, const RealScalar & epsilon = NumTraits<RealScalar>::dummy_precision()) inline
Suppresses all nonzeros which are much smaller than reference under the tolerence epsilon
    {
      prune(default_prunning_func(reference,epsilon));
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune().
Referenced by igl::min_quad_with_fixed_precompute(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), and igl::straighten_seams().
pruned()
template<typename Derived > const SparseView< Derived > Eigen::SparseMatrixBase< Derived >::pruned (const Scalar & reference = Scalar(0), const RealScalar & epsilon = NumTraits<Scalar>::dummy_precision()) const inline inherited
Returns
an expression of *this with values smaller than reference * epsilon removed.
This method is typically used in conjunction with the product of two sparse matrices to automatically prune the smallest values as follows:
C = (A*B).pruned();             // suppress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
{
  return SparseView<Derived>(derived(), reference, epsilon);
}
reserve() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > template<class SizesType > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserve (const SizesType & reserveSizes, const typename SizesType::value_type & enableif = typename SizesType::value_type()) inline
    {
      EIGEN_UNUSED_VARIABLE(enableif);
      reserveInnerVectors(reserveSizes);
    }
References EIGEN_UNUSED_VARIABLE, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors().
reserve() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserve (Index reserveSize) inline
Preallocates reserveSize non zeros.
Precondition: the matrix must be in compressed mode.
    {
      eigen_assert(isCompressed() && "This function does not make sense in non compressed mode.");
      m_data.reserve(reserveSize);
    }
References eigen_assert, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::isCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve().
Referenced by igl::adjacency_matrix(), igl::arap_linear_block_elements(), igl::arap_linear_block_spokes(), igl::arap_linear_block_spokes_and_rims(), igl::cat(), igl::random_points_on_mesh(), igl::repdiag(), igl::repmat(), Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run(), Eigen::internal::set_from_triplets(), and igl::speye().
reserveInnerVectors()
template<typename _Scalar , int _Options, typename _StorageIndex > template<class SizesType > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors (const SizesType & reserveSizes) inline protected
    {
      if(isCompressed())
      {
        Index totalReserveSize = 0;
        // turn the matrix into non-compressed mode
        m_innerNonZeros = static_cast<StorageIndex*>(std::malloc(m_outerSize * sizeof(StorageIndex)));
        if (!m_innerNonZeros) internal::throw_std_bad_alloc();
        // temporarily use m_innerSizes to hold the new starting points.
        StorageIndex* newOuterIndex = m_innerNonZeros;
        StorageIndex count = 0;
        for(Index j=0; j<m_outerSize; ++j)
        {
          newOuterIndex[j] = count;
          count += reserveSizes[j] + (m_outerIndex[j+1]-m_outerIndex[j]);
          totalReserveSize += reserveSizes[j];
        }
        m_data.reserve(totalReserveSize);
        StorageIndex previousOuterIndex = m_outerIndex[m_outerSize];
        for(Index j=m_outerSize-1; j>=0; --j)
        {
          StorageIndex innerNNZ = previousOuterIndex - m_outerIndex[j];
          for(Index i=innerNNZ-1; i>=0; --i)
          {
            m_data.index(newOuterIndex[j]+i) = m_data.index(m_outerIndex[j]+i);
            m_data.value(newOuterIndex[j]+i) = m_data.value(m_outerIndex[j]+i);
          }
          previousOuterIndex = m_outerIndex[j];
          m_outerIndex[j] = newOuterIndex[j];
          m_innerNonZeros[j] = innerNNZ;
        }
        m_outerIndex[m_outerSize] = m_outerIndex[m_outerSize-1] + m_innerNonZeros[m_outerSize-1] + reserveSizes[m_outerSize-1];
        m_data.resize(m_outerIndex[m_outerSize]);
      }
      else
      {
        StorageIndex* newOuterIndex = static_cast<StorageIndex*>(std::malloc((m_outerSize+1)*sizeof(StorageIndex)));
        if (!newOuterIndex) internal::throw_std_bad_alloc();
        StorageIndex count = 0;
        for(Index j=0; j<m_outerSize; ++j)
        {
          newOuterIndex[j] = count;
          StorageIndex alreadyReserved = (m_outerIndex[j+1]-m_outerIndex[j]) - m_innerNonZeros[j];
          StorageIndex toReserve = std::max<StorageIndex>(reserveSizes[j], alreadyReserved);
          count += toReserve + m_innerNonZeros[j];
        }
        newOuterIndex[m_outerSize] = count;
        m_data.resize(count);
        for(Index j=m_outerSize-1; j>=0; --j)
        {
          Index offset = newOuterIndex[j] - m_outerIndex[j];
          if(offset>0)
          {
            StorageIndex innerNNZ = m_innerNonZeros[j];
            for(Index i=innerNNZ-1; i>=0; --i)
            {
              m_data.index(newOuterIndex[j]+i) = m_data.index(m_outerIndex[j]+i);
              m_data.value(newOuterIndex[j]+i) = m_data.value(m_outerIndex[j]+i);
            }
          }
        }
        std::swap(m_outerIndex, newOuterIndex);
        std::free(newOuterIndex);
      }
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::index(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::isCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::reserve(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), Eigen::internal::throw_std_bad_alloc(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::value().
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserve().
resize()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize (Index rows, Index cols) inline
Resizes the matrix to a rows x cols matrix and initializes it to zero.
This function does not free the currently allocated memory. To release as much as memory as possible, call
mat.data().squeeze();
after resizing it.
See also
reserve(), setZero()
    {
      const Index outerSize = IsRowMajor ? rows : cols;
      m_innerSize = IsRowMajor ? cols : rows;
      m_data.clear();
      if (m_outerSize != outerSize || m_outerSize==0)
      {
        std::free(m_outerIndex);
        m_outerIndex = static_cast<StorageIndex*>(std::malloc((outerSize + 1) * sizeof(StorageIndex)));
        if (!m_outerIndex) internal::throw_std_bad_alloc();
        m_outerSize = outerSize;
      }
      if(m_innerNonZeros)
      {
        std::free(m_innerNonZeros);
        m_innerNonZeros = 0;
      }
      memset(m_outerIndex, 0, (m_outerSize+1)*sizeof(StorageIndex));
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::clear(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), and Eigen::internal::throw_std_bad_alloc().
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), igl::adjacency_matrix(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::analyzePattern(), igl::arap_linear_block_elements(), igl::arap_linear_block_spokes(), igl::arap_linear_block_spokes_and_rims(), igl::PlanarizerShapeUp< DerivedV, DerivedF >::assembleSelector(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize(), igl::crouzeix_raviart_massmatrix(), igl::xml::serialization_xml::deserialize(), igl::serialization::deserialize(), igl::matlab::MatlabWorkspace::find(), Eigen::PardisoLLT< MatrixType, _UpLo >::getMatrix(), Eigen::PardisoLDLT< MatrixType, Options >::getMatrix(), Eigen::PastixLLT< _MatrixType, _UpLo >::grabMatrix(), Eigen::PastixLDLT< _MatrixType, _UpLo >::grabMatrix(), grad_tet(), grad_tri(), igl::group_sum_matrix(), igl::in_element(), igl::lbs_matrix_column(), igl::lbs_matrix_column(), igl::loop(), igl::normal_derivative(), Eigen::SimplicialCholeskyBase< Derived >::ordering(), Eigen::internal::permute_symm_to_symm(), igl::project_isometrically_to_plane(), igl::random_points_on_mesh(), igl::remesh_along_isoline(), igl::repdiag(), igl::repmat(), Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run(), igl::slice_tets(), igl::upsample(), and igl::vector_area_matrix().
resizeNonZeros()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resizeNonZeros (Index size) inline
    {
      m_data.resize(size);
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), and Eigen::SparseMatrixBase< Derived >::size().
Referenced by Eigen::internal::minimum_degree_ordering(), Eigen::internal::permute_symm_to_symm(), and Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run().
rows()
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows () const inline
Returns
the number of rows of the matrix
{ return IsRowMajor ? m_outerSize : m_innerSize; }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::IsRowMajor, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize.
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::SparseMatrix(), Eigen::SimplicialCholeskyBase< Derived >::_solve_impl(), igl::active_set(), Eigen::PastixBase< Derived >::analyzePattern(), Eigen::SimplicialCholeskyBase< Derived >::analyzePattern_preordered(), igl::arap_dof_precomputation(), igl::arap_dof_recomputation(), igl::arap_rhs(), igl::AtA_cached_precompute(), igl::bfs(), igl::biharmonic_coordinates(), igl::slim::build_linear_system(), igl::cat(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), igl::components(), Eigen::PastixBase< Derived >::compute(), Eigen::SPQR< _MatrixType >::compute(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize(), igl::eigs(), Eigen::PastixBase< Derived >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), igl::find_zero(), igl::harmonic(), igl::harmonic(), igl::harwell_boeing(), igl::matlab_format(), igl::max(), igl::min(), igl::min_quad_with_fixed_precompute(), igl::matlab::mlsetmatrix(), igl::mosek::mosek_linprog(), igl::mosek::mosek_quadprog(), igl::matlab::prepare_lhs_double(), igl::redux(), igl::repdiag(), igl::repmat(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::rows(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::rows(), Eigen::SimplicialCholeskyBase< Derived >::rows(), Eigen::SparseLU< _MatrixType, _OrderingType >::rows(), Eigen::SparseQR< _MatrixType, _OrderingType >::rows(), Eigen::SuperLUBase< _MatrixType, Derived >::rows(), Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, Diagonal2Sparse >::run(), igl::matlab::MatlabWorkspace::save(), igl::serialization::serialize(), igl::xml::serialization_xml::serialize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setIdentity(), and igl::shapeup_solve().
selfadjointView() [1/4]
template<typename Derived > template<unsigned int UpLo> SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () inline inherited
selfadjointView() [2/4]
template<typename Derived > template<unsigned int UpLo> SparseMatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () inherited
{
  return SparseSelfAdjointView<Derived, UpLo>(derived());
}
References Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::derived().
selfadjointView() [3/4]
template<typename Derived > template<unsigned int UpLo> ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const inline inherited
selfadjointView() [4/4]
template<typename Derived > template<unsigned int UpLo> SparseMatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type Eigen::SparseMatrixBase< Derived >::selfadjointView () const inherited
{
  return SparseSelfAdjointView<const Derived, UpLo>(derived());
}
References Eigen::EigenBase< SparseSelfAdjointView< MatrixType, _Mode > >::derived().
setFromTriplets() [1/2]
template<typename Scalar , int _Options, typename _StorageIndex > template<typename InputIterators > void Eigen::SparseMatrix< Scalar, _Options, _StorageIndex >::setFromTriplets (const InputIterators & begin, const InputIterators & end)
Fill the matrix *this with the list of triplets defined by the iterator range begin - end.
A triplet is a tuple (i,j,value) defining a non-zero element. The input list of triplets does not have to be sorted, and can contains duplicated elements. In any case, the result is a sorted and compressed sparse matrix where the duplicates have been summed up. This is a O(n) operation, with n the number of triplet elements. The initial contents of *this is destroyed. The matrix *this must be properly resized beforehand using the SparseMatrix(Index,Index) constructor, or the resize(Index,Index) method. The sizes are not extracted from the triplet list.
The InputIterators value_type must provide the following interface:
Scalar value() const; // the value
Scalar row() const;   // the row index i
Scalar col() const;   // the column index j
See for instance the Eigen::Triplet template class.
Here is a typical usage example:
typedef Triplet<double> T;
std::vector<T> tripletList;
triplets.reserve(estimation_of_entries);
for(...)
{
  // ...
  tripletList.push_back(T(i,j,v_ij));
}
SparseMatrixType m(rows,cols);
m.setFromTriplets(tripletList.begin(), tripletList.end());
// m is ready to go!
Warning
The list of triplets is read multiple times (at least twice). Therefore, it is not recommended to define an abstract iterator over a complex data-structure that would be expensive to evaluate. The triplets should rather be explicitely stored into a std::vector for instance.
{
  internal::set_from_triplets<InputIterators, SparseMatrix<Scalar,_Options,_StorageIndex> >(begin, end, *this, internal::scalar_sum_op<Scalar,Scalar>());
}
Referenced by igl::adjacency_matrix(), igl::arap_linear_block_elements(), igl::arap_linear_block_spokes(), igl::arap_linear_block_spokes_and_rims(), igl::PlanarizerShapeUp< DerivedV, DerivedF >::assembleSelector(), igl::biharmonic_coordinates(), igl::slim::build_linear_system(), igl::cat(), igl::crouzeix_raviart_massmatrix(), igl::xml::serialization_xml::deserialize(), igl::serialization::deserialize(), igl::Frame_field_deformer::extractBlock(), igl::matlab::MatlabWorkspace::find(), grad_tet(), grad_tri(), igl::in_element(), igl::copyleft::comiso::FrameInterpolator::interpolateSymmetric(), igl::loop(), igl::normal_derivative(), igl::orientable_patches(), igl::copyleft::comiso::NRosyField::prepareSystemMatrix(), igl::project_isometrically_to_plane(), igl::random_points_on_mesh(), igl::remesh_along_isoline(), igl::repdiag(), igl::shapeup_precomputation(), igl::slice_tets(), igl::upsample(), and igl::vector_area_matrix().
setFromTriplets() [2/2]
template<typename Scalar , int _Options, typename _StorageIndex > template<typename InputIterators , typename DupFunctor > void Eigen::SparseMatrix< Scalar, _Options, _StorageIndex >::setFromTriplets (const InputIterators & begin, const InputIterators & end, DupFunctor dup_func)
The same as setFromTriplets but when duplicates are met the functor dup_func is applied:
value = dup_func(OldValue, NewValue)
Here is a C++11 example keeping the latest entry only:
mat.setFromTriplets(triplets.begin(), triplets.end(), [] (const Scalar&,const Scalar &b) { return b; });
{
  internal::set_from_triplets<InputIterators, SparseMatrix<Scalar,_Options,_StorageIndex>, DupFunctor>(begin, end, *this, dup_func);
}
setIdentity()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setIdentity () inline
Sets *this to the identity matrix. This function also turns the matrix into compressed mode, and drop any reserved memory.
    {
      eigen_assert(rows() == cols() && "ONLY FOR SQUARED MATRICES");
      this->m_data.resize(rows());
      Eigen::Map<IndexVector>(this->m_data.indexPtr(), rows()).setLinSpaced(0, StorageIndex(rows()-1));
      Eigen::Map<ScalarVector>(this->m_data.valuePtr(), rows()).setOnes();
      Eigen::Map<IndexVector>(this->m_outerIndex, rows()+1).setLinSpaced(0, StorageIndex(rows()));
      std::free(m_innerNonZeros);
      m_innerNonZeros = 0;
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), eigen_assert, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::indexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::valuePtr().
Referenced by igl::slim::build_linear_system(), and igl::min_quad_with_fixed_precompute().
setZero()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero () inline
Removes all non zeros but keep allocated memory
This function does not free the currently allocated memory. To release as much as memory as possible, call
mat.data().squeeze();
after resizing it.
See also
resize(Index,Index), data()
    {
      m_data.clear();
      memset(m_outerIndex, 0, (m_outerSize+1)*sizeof(StorageIndex));
      if(m_innerNonZeros)
        memset(m_innerNonZeros, 0, (m_outerSize)*sizeof(StorageIndex));
    }
References Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::clear(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize.
Referenced by igl::xml::serialization_xml::deserialize(), and igl::serialization::deserialize().
size()
template<typename Derived > Index Eigen::SparseMatrixBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols().
{ return rows() * cols(); }
References Eigen::SparseMatrixBase< Derived >::cols(), and Eigen::SparseMatrixBase< Derived >::rows().
Referenced by igl::active_set(), igl::cat(), igl::diag(), Eigen::SparseMatrixBase< Derived >::dot(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize(), igl::invert_diag(), igl::min_quad_with_fixed_precompute(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::operator=(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resizeNonZeros().
squaredNorm()
template<typename Derived > NumTraits< typenameinternal::traits< Derived >::Scalar >::Real Eigen::SparseMatrixBase< Derived >::squaredNorm inline inherited
{
  return numext::real((*this).cwiseAbs2().sum());
}
startVec()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::startVec (Index outer) inline
    {
      eigen_assert(m_outerIndex[outer]==Index(m_data.size()) && "You must call startVec for each inner vector sequentially");
      eigen_assert(m_outerIndex[outer+1]==0 && "You must call startVec for each inner vector sequentially");
      m_outerIndex[outer+1] = m_outerIndex[outer];
    }
References eigen_assert, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::size().
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
sum()
template<typename _Scalar , int _Options, typename _Index > internal::traits< SparseMatrix< _Scalar, _Options, _Index > >::Scalar Eigen::SparseMatrix< _Scalar, _Options, _Index >::sum
Overloaded for performance
{
  eigen_assert(rows()>0 && cols()>0 && "you are using a non initialized matrix");
  if(this->isCompressed())
    return Matrix<Scalar,1,Dynamic>::Map(m_data.valuePtr(), m_data.size()).sum();
  else
    return Base::sum();
}
References Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Eigen::Map, and eigen_assert.
sumupDuplicates()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::sumupDuplicates () inline
{ collapseDuplicates(internal::scalar_sum_op<Scalar,Scalar>()); }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::collapseDuplicates().
swap()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::swap (SparseMatrix< _Scalar, _Options, _StorageIndex > & other) inline
Swaps the content of two sparse matrices of the same type. This is a fast operation that simply swaps the underlying pointers and parameters.
    {
      //EIGEN_DBG_SPARSE(std::cout << "SparseMatrix:: swap\n");
      std::swap(m_outerIndex, other.m_outerIndex);
      std::swap(m_innerSize, other.m_innerSize);
      std::swap(m_outerSize, other.m_outerSize);
      std::swap(m_innerNonZeros, other.m_innerNonZeros);
      m_data.swap(other.m_data);
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::swap().
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=().
toDense()
template<typename Derived > DenseMatrixType Eigen::SparseMatrixBase< Derived >::toDense () const inline inherited
    {
      return DenseMatrixType(derived());
    }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseMatrixBase< Derived >::isApprox().
transpose() [1/2]
template<typename Derived > TransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () inline inherited
{ return TransposeReturnType(derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::SparseMatrixBase< Derived >::adjoint(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::analyzePattern(), igl::arap_dof_precomputation(), igl::AtA_cached_precompute(), igl::slim::build_linear_system(), igl::copyleft::comiso::PoissonSolver< DerivedV, DerivedF >::BuildLaplacianMatrix(), Eigen::PastixLU< _MatrixType, IsStrSym >::grabMatrix(), igl::hessian(), igl::hessian_energy(), igl::min_quad_with_fixed_precompute(), igl::mosek::mosek_quadprog(), igl::orientable_patches(), igl::shapeup_precomputation(), and igl::straighten_seams().
transpose() [2/2]
template<typename Derived > const ConstTransposeReturnType Eigen::SparseMatrixBase< Derived >::transpose () const inline inherited
{ return ConstTransposeReturnType(derived()); }
References Eigen::SparseMatrixBase< Derived >::derived().
triangularView()
template<typename Derived > template<int Mode> const TriangularView< const Derived, Mode > Eigen::SparseMatrixBase< Derived >::triangularView inline inherited
{
  return TriangularView<const Derived, Mode>(derived());
}
Referenced by igl::mosek::mosek_quadprog().
twistedBy()
template<typename Derived > SparseSymmetricPermutationProduct< Derived, Upper|Lower > Eigen::SparseMatrixBase< Derived >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & perm) const inline inherited
Returns
an expression of P H P^-1 where H is the matrix represented by *this
    {
      return SparseSymmetricPermutationProduct<Derived,Upper|Lower>(derived(), perm);
    }
References Eigen::SparseMatrixBase< Derived >::derived().
Referenced by Eigen::IncompleteLUT< _Scalar, _StorageIndex >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::PardisoLLT< MatrixType, _UpLo >::getMatrix(), and Eigen::PardisoLDLT< MatrixType, Options >::getMatrix().
uncompress()
template<typename _Scalar , int _Options, typename _StorageIndex > void Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::uncompress () inline
Turns the matrix into the uncompressed mode
    {
      if(m_innerNonZeros != 0)
        return;
      m_innerNonZeros = static_cast<StorageIndex*>(std::malloc(m_outerSize * sizeof(StorageIndex)));
      for (Index i = 0; i < m_outerSize; i++)
      {
        m_innerNonZeros[i] = m_outerIndex[i+1] - m_outerIndex[i];
      }
    }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros, Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex, and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize.
valuePtr() [1/2]
template<typename _Scalar , int _Options, typename _StorageIndex > Scalar * Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr () inline
Returns
a non-const pointer to the array of values. This function is aimed at interoperability with other libraries.
See also
innerIndexPtr(), outerIndexPtr()
{ return m_data.valuePtr(); }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::valuePtr().
valuePtr() [2/2]
template<typename _Scalar , int _Options, typename _StorageIndex > const Scalar * Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr () const inline
Returns
a const pointer to the array of values. This function is aimed at interoperability with other libraries.
See also
innerIndexPtr(), outerIndexPtr()
{ return m_data.valuePtr(); }
References Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >::valuePtr().
Referenced by Eigen::PastixBase< Derived >::analyzePattern(), igl::AtA_cached(), Eigen::PastixBase< Derived >::factorize(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::internal::permute_symm_to_symm(), and igl::slice_cached_precompute().
Friends And Related Symbol Documentation
operator<<
template<typename _Scalar , int _Options, typename _StorageIndex > std::ostream & operator<< (std::ostream & s, const SparseMatrix< _Scalar, _Options, _StorageIndex > & m) friend
    {
      EIGEN_DBG_SPARSE(
        s << "Nonzero entries:\n";
        if(m.isCompressed())
        {
          for (Index i=0; i<m.nonZeros(); ++i)
            s << "(" << m.m_data.value(i) << "," << m.m_data.index(i) << ") ";
        }
        else
        {
          for (Index i=0; i<m.outerSize(); ++i)
          {
            Index p = m.m_outerIndex[i];
            Index pe = m.m_outerIndex[i]+m.m_innerNonZeros[i];
            Index k=p;
            for (; k<pe; ++k) {
              s << "(" << m.m_data.value(k) << "," << m.m_data.index(k) << ") ";
            }
            for (; k<m.m_outerIndex[i+1]; ++k) {
              s << "(_,_) ";
            }
          }
        }
        s << std::endl;
        s << std::endl;
        s << "Outer pointers:\n";
        for (Index i=0; i<m.outerSize(); ++i) {
          s << m.m_outerIndex[i] << " ";
        }
        s << " $" << std::endl;
        if(!m.isCompressed())
        {
          s << "Inner non zeros:\n";
          for (Index i=0; i<m.outerSize(); ++i) {
            s << m.m_innerNonZeros[i] << " ";
          }
          s << " $" << std::endl;
        }
        s << std::endl;
      );
      s << static_cast<const SparseMatrixBase<SparseMatrix>&>(m);
      return s;
    }
SparseVector< _Scalar, 0, _StorageIndex >
template<typename _Scalar , int _Options, typename _StorageIndex > friend class SparseVector< _Scalar, 0, _StorageIndex > friend
Member Data Documentation
m_data
template<typename _Scalar , int _Options, typename _StorageIndex > Storage Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_data protected
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::data(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::data(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInnerUnordered(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserve(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resizeNonZeros(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::startVec(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::swap(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::valuePtr().
m_innerNonZeros
template<typename _Scalar , int _Options, typename _StorageIndex > StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerNonZeros protected
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerNonZeroPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerNonZeroPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setIdentity(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::swap(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::uncompress().
m_innerSize
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_innerSize protected
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::innerSize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::swap(), and Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::swap().
m_isRValue
template<typename Derived > bool Eigen::SparseMatrixBase< Derived >::m_isRValue protected inherited
Referenced by Eigen::SparseMatrixBase< Derived >::isRValue(), and Eigen::SparseMatrixBase< Derived >::markAsRValue().
m_outerIndex
template<typename _Scalar , int _Options, typename _StorageIndex > StorageIndex* Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerIndex protected
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInner(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackByOuterInnerUnordered(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::startVec(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::swap(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::uncompress().
m_outerSize
template<typename _Scalar , int _Options, typename _StorageIndex > Index Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::m_outerSize protected
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::cols(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::conservativeResize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::finalize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::makeCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::operator=(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::outerSize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::prune(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::reserveInnerVectors(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::rows(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::setZero(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::swap(), and Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::uncompress().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/SparseCore/SparseMatrix.h
src/eigen/Eigen/src/SparseCore/SparseRedux.h