Prusa Slicer: Slic3r::ClipperUtils::EmptyPathsProvider Class Reference
Slic3r::ClipperUtils::EmptyPathsProvider Class Reference
#include <src/libslic3r/ClipperUtils.hpp>
Classes
struct iterator
Public Member Functions
constexpr EmptyPathsProvider ()
Static Public Member Functions
static constexpr iterator cend () throw ()
static constexpr iterator end () throw ()
static constexpr iterator cbegin () throw ()
static constexpr iterator begin () throw ()
static constexpr size_t size () throw ()
Static Public Attributes
static Points s_empty_points
Detailed Description
Constructor & Destructor Documentation
EmptyPathsProvider()
constexpr Slic3r::ClipperUtils::EmptyPathsProvider::EmptyPathsProvider () inline constexpr
{}
Member Function Documentation
begin()
static constexpr iterator Slic3r::ClipperUtils::EmptyPathsProvider::begin () throw () inline static constexpr
{ return cend(); }
References cend().
cbegin()
static constexpr iterator Slic3r::ClipperUtils::EmptyPathsProvider::cbegin () throw () inline static constexpr
{ return cend(); }
References cend().
cend()
static constexpr iterator Slic3r::ClipperUtils::EmptyPathsProvider::cend () throw () inline static constexpr
{ return iterator{}; }
Referenced by begin(), cbegin(), and end().
end()
static constexpr iterator Slic3r::ClipperUtils::EmptyPathsProvider::end () throw () inline static constexpr
{ return cend(); }
References cend().
size()
static constexpr size_t Slic3r::ClipperUtils::EmptyPathsProvider::size () throw () inline static constexpr
{ return 0; }
Member Data Documentation
s_empty_points
Points Slic3r::ClipperUtils::EmptyPathsProvider::s_empty_points static
Referenced by Slic3r::ClipperUtils::EmptyPathsProvider::iterator::operator*(), and Slic3r::ClipperUtils::EmptyPathsProvider::iterator::operator++().
The documentation for this class was generated from the following files:
src/libslic3r/ClipperUtils.hpp
src/libslic3r/ClipperUtils.cpp