Prusa Slicer: igl::geodesic::IntervalList Class Reference
igl::geodesic::IntervalList Class Reference
Public Member Functions
IntervalList ()
~IntervalList ()
void clear ()
void initialize (edge_pointer e)
interval_pointer covering_interval (double offset)
void find_closest_point (SurfacePoint *point, double &offset, double &distance, interval_pointer &interval)
unsigned number_of_intervals ()
interval_pointer last ()
double signal (double x)
interval_pointer & first ()
edge_pointer & edge ()
Private Attributes
interval_pointer m_first
edge_pointer m_edge
Detailed Description
Constructor & Destructor Documentation
IntervalList()
igl::geodesic::IntervalList::IntervalList () inline
{m_first = NULL;};
References m_first.
~IntervalList()
igl::geodesic::IntervalList::~IntervalList () inline
{};
Member Function Documentation
clear()
void igl::geodesic::IntervalList::clear () inline
  {
    m_first = NULL;
  };
References m_first.
covering_interval()
interval_pointer igl::geodesic::IntervalList::covering_interval (double offset) inline
  {
    assert(offset >= 0.0 && offset <= m_edge->length());
    interval_pointer p = m_first;
    while(p && p->stop() < offset)
    {
      p = p->next();
    }
    return p;// && p->start() <= offset ? p : NULL;
  };
References igl::geodesic::length(), m_first, igl::geodesic::Interval::next(), and igl::geodesic::Interval::stop().
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), signal(), and igl::geodesic::GeodesicAlgorithmExact::visible_from_source().
edge()
edge_pointer & igl::geodesic::IntervalList::edge () inline
{return m_edge;};
References m_edge.
Referenced by igl::geodesic::GeodesicAlgorithmExact::update_list_and_queue().
find_closest_point()
void igl::geodesic::IntervalList::find_closest_point (SurfacePoint * point, double & offset, double & distance, interval_pointer & interval) inline
  {
    interval_pointer p = m_first;
    distance = GEODESIC_INF;
    interval = NULL;
    double x,y;
    m_edge->local_coordinates(point, x, y);
    while(p)
    {
      if(p->min()<GEODESIC_INF)
      {
        double o, d;
        p->find_closest_point(x, y, o, d);
        if(d < distance)
        {
          distance = d;
          offset = o;
          interval = p;
        }
      }
      p = p->next();
    }
  };
References igl::geodesic::Interval::find_closest_point(), igl::geodesic::GEODESIC_INF, igl::geodesic::Edge::local_coordinates(), m_edge, m_first, igl::geodesic::Interval::min(), and igl::geodesic::Interval::next().
Referenced by igl::geodesic::GeodesicAlgorithmExact::best_first_interval(), and igl::geodesic::GeodesicAlgorithmExact::best_point_on_the_edge_set().
first()
interval_pointer & igl::geodesic::IntervalList::first () inline
{return m_first;};
References m_first.
Referenced by igl::geodesic::GeodesicAlgorithmExact::update_list_and_queue().
initialize()
void igl::geodesic::IntervalList::initialize (edge_pointer e) inline
  {
    m_edge = e;
    m_first = NULL;
  };
References m_edge, and m_first.
last()
interval_pointer igl::geodesic::IntervalList::last () inline
  {
    interval_pointer p = m_first;
    if(p)
    {
      while(p->next())
      {
        p = p->next();
      }
    }
    return p;
  }
References m_first, and igl::geodesic::Interval::next().
number_of_intervals()
unsigned igl::geodesic::IntervalList::number_of_intervals () inline
  {
    interval_pointer p = m_first;
    unsigned count = 0;
    while(p)
    {
      ++count;
      p = p->next();
    }
    return count;
  }
References igl::count(), m_first, and igl::geodesic::Interval::next().
signal()
double igl::geodesic::IntervalList::signal (double x) inline
  {
    interval_pointer interval = covering_interval(x);
    return interval ? interval->signal(x) : GEODESIC_INF;
  }
References covering_interval(), igl::geodesic::GEODESIC_INF, and igl::geodesic::Interval::signal().
Referenced by igl::geodesic::GeodesicAlgorithmExact::check_stop_conditions().
Member Data Documentation
m_edge
edge_pointer igl::geodesic::IntervalList::m_edge private
Referenced by edge(), find_closest_point(), and initialize().
m_first
interval_pointer igl::geodesic::IntervalList::m_first private
Referenced by IntervalList(), clear(), covering_interval(), find_closest_point(), first(), initialize(), last(), and number_of_intervals().
The documentation for this class was generated from the following file:
src/libigl/igl/exact_geodesic.cpp