Prusa Slicer: agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type Struct Reference
agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type Struct Reference
#include <src/agg/agg_pixfmt_rgb.h>
Public Member Functions
void set (value_type r, value_type g, value_type b)
void set (const color_type &color)
void get (value_type &r, value_type &g, value_type &b) const
color_type get () const
pixel_type * next ()
const pixel_type * next () const
pixel_type * advance (int n)
const pixel_type * advance (int n) const
Public Attributes
value_type c [num_components]
Detailed Description
template<class Blender, class RenBuf, unsigned Step, unsigned Offset = 0>
struct agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type
Member Function Documentation
advance() [1/2]
template<class Blender , class RenBuf , unsigned Step, unsigned Offset = 0> pixel_type * agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::advance (int n) inline
            {
                return (pixel_type*)(c + n * pix_step);
            }
References agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::c, and agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pix_step.
advance() [2/2]
template<class Blender , class RenBuf , unsigned Step, unsigned Offset = 0> const pixel_type * agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::advance (int n) const inline
            {
                return (const pixel_type*)(c + n * pix_step);
            }
References agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::c, and agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pix_step.
get() [1/2]
template<class Blender , class RenBuf , unsigned Step, unsigned Offset = 0> color_type agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::get () const inline
            {
                return color_type(
                    c[order_type::R],
                    c[order_type::G],
                    c[order_type::B]);
            }
References agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::c.
get() [2/2]
template<class Blender , class RenBuf , unsigned Step, unsigned Offset = 0> void agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::get (value_type & r, value_type & g, value_type & b) const inline
            {
                r = c[order_type::R];
                g = c[order_type::G];
                b = c[order_type::B];
            }
References agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::c.
Referenced by agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_from(), and agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::read_plain_color().
next() [1/2]
template<class Blender , class RenBuf , unsigned Step, unsigned Offset = 0> pixel_type * agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::next () inline
            {
                return (pixel_type*)(c + pix_step);
            }
References agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::c, and agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pix_step.
Referenced by agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_color_hspan(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_from(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_from_color(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_from_lut(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_hline(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_solid_hspan(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::copy_color_hspan(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::copy_hline(), and agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::for_each_pixel().
next() [2/2]
template<class Blender , class RenBuf , unsigned Step, unsigned Offset = 0> const pixel_type * agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::next () const inline
            {
                return (const pixel_type*)(c + pix_step);
            }
References agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::c, and agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pix_step.
set() [1/2]
template<class Blender , class RenBuf , unsigned Step, unsigned Offset = 0> void agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::set (const color_type & color) inline
            {
                set(color.r, color.g, color.b);
            }
References agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::set().
set() [2/2]
template<class Blender , class RenBuf , unsigned Step, unsigned Offset = 0> void agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::set (value_type r, value_type g, value_type b) inline
            {
                c[order_type::R] = r;
                c[order_type::G] = g;
                c[order_type::B] = b;
            }
References agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::c.
Referenced by agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_hline(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_solid_hspan(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_solid_vspan(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_vline(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::copy_color_hspan(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::copy_color_vspan(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::copy_hline(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::copy_or_blend_pix(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::copy_or_blend_pix(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::copy_pixel(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::copy_vline(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::set(), and agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::write_plain_color().
Member Data Documentation
c
template<class Blender , class RenBuf , unsigned Step, unsigned Offset = 0> value_type agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::c[num_components]
Referenced by agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::advance(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::advance(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_from(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_pix(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_pix(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_pix(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::blend_pix(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::for_each_pixel(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::get(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::get(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::next(), agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::next(), and agg::pixfmt_alpha_blend_rgb< Blender, RenBuf, Step, Offset >::pixel_type::set().
The documentation for this struct was generated from the following file:
src/agg/agg_pixfmt_rgb.h