Prusa Slicer: Slic3r::GUI::Config::SnapshotDB Class Reference
Slic3r::GUI::Config::SnapshotDB Class Reference
#include <src/slic3r/Config/Snapshot.hpp>
Public Types
typedef std::vector< Snapshot >::const_iterator const_iterator
Public Member Functions
size_t load_db ()
void update_slic3r_versions (std::vector< Index > &index_db)
const Snapshot & take_snapshot (const AppConfig &app_config, Snapshot::Reason reason, const std::string &comment="")
const Snapshot & restore_snapshot (const std::string &id, AppConfig &app_config)
void restore_snapshot (const Snapshot &snapshot, AppConfig &app_config)
bool is_on_snapshot (AppConfig &app_config) const
const_iterator snapshot_with_vendor_preset (const std::string &vendor_name, const Semver &config_version)
const_iterator begin () const
const_iterator end () const
const_iterator snapshot (const std::string &id) const
const std::vector< Snapshot > & snapshots () const
Static Public Member Functions
static SnapshotDB & singleton ()
Static Private Member Functions
static boost::filesystem::path create_db_dir ()
Private Attributes
std::vector< Snapshot > m_snapshots
Detailed Description
Member Typedef Documentation
const_iterator
typedef std::vector<Snapshot>::const_iterator Slic3r::GUI::Config::SnapshotDB::const_iterator
Member Function Documentation
begin()
const_iterator Slic3r::GUI::Config::SnapshotDB::begin () const inline
{ return m_snapshots.begin(); }
References m_snapshots.
create_db_dir()
boost::filesystem::path Slic3r::GUI::Config::SnapshotDB::create_db_dir () static private
{
    boost::filesystem::path data_dir    = boost::filesystem::path(Slic3r::data_dir());
    boost::filesystem::path snapshots_dir = data_dir / SLIC3R_SNAPSHOTS_DIR;
    for (const boost::filesystem::path &path : { data_dir, snapshots_dir }) {
    boost::filesystem::path subdir = path;
        subdir.make_preferred();
        if (! boost::filesystem::is_directory(subdir) &&
            ! boost::filesystem::create_directory(subdir))
            throw Slic3r::RuntimeError(std::string("Slic3r was unable to create a directory at ") + subdir.string());
    }
    return snapshots_dir;
}
References Slic3r::data_dir(), and SLIC3R_SNAPSHOTS_DIR.
Referenced by load_db(), restore_snapshot(), and take_snapshot().
end()
const_iterator Slic3r::GUI::Config::SnapshotDB::end () const inline
{ return m_snapshots.end(); }
References m_snapshots.
Referenced by is_on_snapshot().
is_on_snapshot()
bool Slic3r::GUI::Config::SnapshotDB::is_on_snapshot (AppConfig & app_config) const
{
    // Is the "on_snapshot" configuration value set?
    std::string on_snapshot = app_config.get("on_snapshot");
    if (on_snapshot.empty())
        // No, we are not on a snapshot.
        return false;
    // Is the "on_snapshot" equal to the current configuration state?
    auto it_snapshot = this->snapshot(on_snapshot);
    if (it_snapshot != this->end() && it_snapshot->equal_to_active(app_config))
        // Yes, we are on the snapshot.
        return true;
    // No, we are no more on a snapshot. Reset the state.
    app_config.set("on_snapshot", "");
    return false;
}
References end(), Slic3r::AppConfig::get(), Slic3r::AppConfig::set(), and snapshot().
Referenced by Slic3r::GUI::GUI_App::add_config_menu().
load_db()
size_t Slic3r::GUI::Config::SnapshotDB::load_db ()
{
  boost::filesystem::path snapshots_dir = SnapshotDB::create_db_dir();
  m_snapshots.clear();
    // Walk over the snapshot directories and load their index.
    std::string errors_cummulative;
  for (auto &dir_entry : boost::filesystem::directory_iterator(snapshots_dir))
        if (boost::filesystem::is_directory(dir_entry.status())) {
          // Try to read "snapshot.ini".
            boost::filesystem::path path_ini = dir_entry.path() / SLIC3R_SNAPSHOT_FILE;
            Snapshot          snapshot;
            try {
              snapshot.load_ini(path_ini.string());
            } catch (const std::runtime_error &err) {
                errors_cummulative += err.what();
                errors_cummulative += "\n";
                continue;
      }
            // Check that the name of the snapshot directory matches the snapshot id stored in the snapshot.ini file.
            if (dir_entry.path().filename().string() != snapshot.id) {
              errors_cummulative += std::string("Snapshot ID ") + snapshot.id + " does not match the snapshot directory " + dir_entry.path().filename().string() + "\n";
              continue;
            }
            m_snapshots.emplace_back(std::move(snapshot));
        }
    // Sort the snapshots by their date/time.
    std::sort(m_snapshots.begin(), m_snapshots.end(), [](const Snapshot &s1, const Snapshot &s2) { return s1.time_captured < s2.time_captured; });
    if (! errors_cummulative.empty())
        throw Slic3r::RuntimeError(errors_cummulative);
    return m_snapshots.size();
}
References create_db_dir(), m_snapshots, SLIC3R_SNAPSHOT_FILE, and snapshot().
Referenced by singleton().
restore_snapshot() [1/2]
void Slic3r::GUI::Config::SnapshotDB::restore_snapshot (const Snapshot & snapshot, AppConfig & app_config)
{
  boost::filesystem::path data_dir        = boost::filesystem::path(Slic3r::data_dir());
  boost::filesystem::path snapshot_db_dir = SnapshotDB::create_db_dir();
    boost::filesystem::path snapshot_dir  = snapshot_db_dir / snapshot.id;
    // Remove existing ini files and restore the ini files from the snapshot.
    for (const char *subdir : snapshot_subdirs) {
        boost::filesystem::path src = snapshot_dir / subdir;
        boost::filesystem::path dst = data_dir / subdir;
    delete_existing_ini_files(dst);
        if (boost::filesystem::is_directory(src))
          copy_config_dir_single_level(src, dst);
    }
    // Update AppConfig with the selections of the print / sla_print / filament / sla_material / printer profiles
    // and about the installed printer types and variants.
    snapshot.export_selections(app_config);
    snapshot.export_vendor_configs(app_config);
}
References Slic3r::GUI::Config::copy_config_dir_single_level(), create_db_dir(), Slic3r::data_dir(), Slic3r::GUI::Config::delete_existing_ini_files(), snapshot(), and Slic3r::GUI::Config::snapshot_subdirs.
restore_snapshot() [2/2]
const Snapshot & Slic3r::GUI::Config::SnapshotDB::restore_snapshot (const std::string & id, AppConfig & app_config)
{
  for (const Snapshot &snapshot : m_snapshots)
    if (snapshot.id == id) {
      this->restore_snapshot(snapshot, app_config);
      return snapshot;
    }
  throw Slic3r::RuntimeError(std::string("Snapshot with id " + id + " was not found."));
}
References m_snapshots, restore_snapshot(), and snapshot().
Referenced by restore_snapshot().
singleton()
SnapshotDB & Slic3r::GUI::Config::SnapshotDB::singleton () static
{
  static SnapshotDB instance;
  static bool       loaded = false;
  if (! loaded) {
    try {
      loaded = true;
      // Load the snapshot database.
      instance.load_db();
      // Load the vendor specific configuration indices.
      std::vector<Index> index_db = Index::load_db();
      // Update the min / max slic3r versions compatible with the configurations stored inside the snapshots
      // based on the min / max slic3r versions defined by the vendor specific config indices.
      instance.update_slic3r_versions(index_db);
    } catch (std::exception & /* ex */) {
    }
  }
  return instance;
}
References load_db(), Slic3r::GUI::Config::Index::load_db(), and update_slic3r_versions().
Referenced by Slic3r::GUI::GUI_App::add_config_menu(), Slic3r::GUI::Config::take_config_snapshot_cancel_on_error(), and Slic3r::GUI::Config::take_config_snapshot_report_error().
snapshot()
SnapshotDB::const_iterator Slic3r::GUI::Config::SnapshotDB::snapshot (const std::string & id) const
{
    for (const_iterator it = m_snapshots.begin(); it != m_snapshots.end(); ++ it)
        if (it->id == id)
            return it;
    return m_snapshots.end();
}
References m_snapshots.
Referenced by is_on_snapshot(), load_db(), restore_snapshot(), restore_snapshot(), snapshot_with_vendor_preset(), take_snapshot(), and update_slic3r_versions().
snapshot_with_vendor_preset()
SnapshotDB::const_iterator Slic3r::GUI::Config::SnapshotDB::snapshot_with_vendor_preset (const std::string & vendor_name, const Semver & config_version)
{
    auto it_found = m_snapshots.end();
    Snapshot::VendorConfig key;
    key.name = vendor_name;
    for (auto it = m_snapshots.begin(); it != m_snapshots.end(); ++ it) {
        const Snapshot &snapshot = *it;
        auto it_vendor_config = std::lower_bound(snapshot.vendor_configs.begin(), snapshot.vendor_configs.end(),
            key, [](const Snapshot::VendorConfig &cfg1, const Snapshot::VendorConfig &cfg2) { return cfg1.name < cfg2.name; });
        if (it_vendor_config != snapshot.vendor_configs.end() && it_vendor_config->name == vendor_name &&
            config_version == it_vendor_config->version.config_version) {
            // Vendor config found with the correct version.
            // Save it, but continue searching, as we want the newest snapshot.
            it_found = it;
        }
    }
    return it_found;
}
References m_snapshots, Slic3r::GUI::Config::Snapshot::VendorConfig::name, and snapshot().
snapshots()
const std::vector< Snapshot > & Slic3r::GUI::Config::SnapshotDB::snapshots () const inline
{ return m_snapshots; }
References m_snapshots.
Referenced by Slic3r::GUI::generate_html_page().
take_snapshot()
const Snapshot & Slic3r::GUI::Config::SnapshotDB::take_snapshot (const AppConfig & app_config, Snapshot::Reason reason, const std::string & comment = "")
{
  boost::filesystem::path data_dir        = boost::filesystem::path(Slic3r::data_dir());
  boost::filesystem::path snapshot_db_dir = SnapshotDB::create_db_dir();
  // 1) Prepare the snapshot structure.
  Snapshot snapshot;
  // Snapshot header.
  snapshot.time_captured       = Slic3r::Utils::get_current_time_utc();
  snapshot.id            = Slic3r::Utils::iso_utc_timestamp(snapshot.time_captured);
  snapshot.slic3r_version_captured = Slic3r::SEMVER;
  snapshot.comment         = comment;
  snapshot.reason          = reason;
  // Active presets at the time of the snapshot.
    snapshot.print                   = app_config.get("presets", "print");
    snapshot.sla_print               = app_config.get("presets", "sla_print");
    snapshot.filaments.emplace_back(app_config.get("presets", "filament"));
    snapshot.sla_material            = app_config.get("presets", "sla_material");
    snapshot.printer                 = app_config.get("presets", "printer");
    snapshot.physical_printer        = app_config.get("presets", "physical_printer");
    for (unsigned i = 1; i < 1000; ++ i) {
        char name[64];
        sprintf(name, "filament_%u", i);
        if (! app_config.has("presets", name))
            break;
        snapshot.filaments.emplace_back(app_config.get("presets", name));
    }
    // Vendor specific config bundles and installed printers.
    for (const auto &vendor : app_config.vendors()) {
        Snapshot::VendorConfig cfg;
        cfg.name = vendor.first;
        cfg.models_variants_installed = vendor.second;
        for (auto it = cfg.models_variants_installed.begin(); it != cfg.models_variants_installed.end();)
            if (it->second.empty())
                cfg.models_variants_installed.erase(it ++);
            else
                ++ it;
        // Read the active config bundle, parse the config version.
        PresetBundle bundle;
        bundle.load_configbundle((data_dir / "vendor" / (cfg.name + ".ini")).string(), PresetBundle::LoadConfigBundleAttribute::LoadVendorOnly, ForwardCompatibilitySubstitutionRule::EnableSilent);
        for (const auto &vp : bundle.vendors)
            if (vp.second.id == cfg.name)
                cfg.version.config_version = vp.second.config_version;
        // Fill-in the min/max slic3r version from the config index, if possible.
        try {
            // Load the config index for the vendor.
            Index index;
            index.load(data_dir / "vendor" / (cfg.name + ".idx"));
            auto it = index.find(cfg.version.config_version);
            if (it != index.end()) {
                cfg.version.min_slic3r_version = it->min_slic3r_version;
                cfg.version.max_slic3r_version = it->max_slic3r_version;
            }
        } catch (const std::runtime_error & /* err */) {
        }
        snapshot.vendor_configs.emplace_back(std::move(cfg));
    }
  boost::filesystem::path snapshot_dir = snapshot_db_dir / snapshot.id;
    try {
      boost::filesystem::create_directory(snapshot_dir);
        // Backup the presets.
        for (const char *subdir : snapshot_subdirs)
          copy_config_dir_single_level(data_dir / subdir, snapshot_dir / subdir);
        snapshot.save_ini((snapshot_dir / "snapshot.ini").string());
        assert(m_snapshots.empty() || m_snapshots.back().time_captured <= snapshot.time_captured);
        m_snapshots.emplace_back(std::move(snapshot));
    } catch (...) {
        if (boost::filesystem::is_directory(snapshot_dir)) {
            try {
                // Clean up partially copied snapshot.
                boost::filesystem::remove_all(snapshot_dir);
            } catch (...) {
                BOOST_LOG_TRIVIAL(error) << "Failed taking snapshot and failed removing the snapshot directory " << snapshot_dir;
            }
        }
        throw;
    }
    return m_snapshots.back();
}
References comment, Slic3r::GUI::Config::Version::config_version, Slic3r::GUI::Config::copy_config_dir_single_level(), create_db_dir(), Slic3r::data_dir(), Slic3r::EnableSilent, Slic3r::GUI::Config::Index::end(), error, Slic3r::GUI::Config::Index::find(), Slic3r::AppConfig::get(), Slic3r::Utils::get_current_time_utc(), Slic3r::AppConfig::has(), Slic3r::Utils::iso_utc_timestamp(), Slic3r::GUI::Config::Index::load(), Slic3r::PresetBundle::load_configbundle(), Slic3r::PresetBundle::LoadVendorOnly, m_snapshots, Slic3r::GUI::Config::Version::max_slic3r_version, Slic3r::GUI::Config::Version::min_slic3r_version, Slic3r::GUI::Config::Snapshot::VendorConfig::models_variants_installed, Slic3r::GUI::Config::Snapshot::VendorConfig::name, Slic3r::SEMVER, snapshot(), Slic3r::GUI::Config::snapshot_subdirs, Slic3r::AppConfig::vendors(), Slic3r::PresetBundle::vendors, and Slic3r::GUI::Config::Snapshot::VendorConfig::version.
Referenced by Slic3r::GUI::Config::take_config_snapshot_cancel_on_error(), and Slic3r::GUI::Config::take_config_snapshot_report_error().
update_slic3r_versions()
void Slic3r::GUI::Config::SnapshotDB::update_slic3r_versions (std::vector< Index > & index_db)
{
  for (Snapshot &snapshot : m_snapshots) {
    for (Snapshot::VendorConfig &vendor_config : snapshot.vendor_configs) {
      auto it = std::find_if(index_db.begin(), index_db.end(), [&vendor_config](const Index &idx) { return idx.vendor() == vendor_config.name; });
      if (it != index_db.end()) {
        Index::const_iterator it_version = it->find(vendor_config.version.config_version);
        if (it_version != it->end()) {
          vendor_config.version.min_slic3r_version = it_version->min_slic3r_version;
          vendor_config.version.max_slic3r_version = it_version->max_slic3r_version;
        }
      }
    }
  }
}
References m_snapshots, and snapshot().
Referenced by singleton().
Member Data Documentation
m_snapshots
std::vector<Snapshot> Slic3r::GUI::Config::SnapshotDB::m_snapshots private
Referenced by begin(), end(), load_db(), restore_snapshot(), snapshot(), snapshot_with_vendor_preset(), snapshots(), take_snapshot(), and update_slic3r_versions().
The documentation for this class was generated from the following files:
src/slic3r/Config/Snapshot.hpp
src/slic3r/Config/Snapshot.cpp