Prusa Slicer: Slic3r::trianglulate_wall_detail::Ring Class Reference
Slic3r::trianglulate_wall_detail::Ring Class Reference
#include <src/libslic3r/TriangulateWall.hpp>
Public Member Functions
Ring (size_t from, size_t to)
size_t size () const
std::pair< size_t, size_t > pos () const
bool is_lower () const
void inc ()
void init (size_t pos)
bool is_finished () const
Private Attributes
size_t idx = 0
size_t nextidx = 1
size_t startidx = 0
size_t begin = 0
size_t end = 0
Detailed Description
Constructor & Destructor Documentation
Ring()
Slic3r::trianglulate_wall_detail::Ring::Ring (size_t from, size_t to) inline explicit
: begin(from), end(to) { init(begin); }
References begin, and init().
Member Function Documentation
inc()
void Slic3r::trianglulate_wall_detail::Ring::inc () inline
    {
        if (nextidx != startidx) nextidx++;
        if (nextidx == end) nextidx = begin;
        idx ++;
        if (idx == end) idx = begin;
    }
References begin, end, idx, nextidx, and startidx.
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::run(), and Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings().
init()
void Slic3r::trianglulate_wall_detail::Ring::init (size_t pos) inline
    {
        startidx = begin + (pos - begin) % size();
        idx = startidx;
        nextidx = begin + (idx + 1 - begin) % size();
    }
References begin, idx, nextidx, pos(), size(), and startidx.
Referenced by Ring(), and Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings().
is_finished()
bool Slic3r::trianglulate_wall_detail::Ring::is_finished () const inline
{ return nextidx == idx; }
References idx, and nextidx.
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::run(), and Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings().
is_lower()
bool Slic3r::trianglulate_wall_detail::Ring::is_lower () const inline
{ return idx < size(); }
References idx, and size().
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::emplace_indices().
pos()
std::pair< size_t, size_t > Slic3r::trianglulate_wall_detail::Ring::pos () const inline
{ return {idx, nextidx}; }
References idx, and nextidx.
Referenced by Slic3r::trianglulate_wall_detail::Triangulator< Sc >::emplace_indices(), init(), Slic3r::trianglulate_wall_detail::Triangulator< Sc >::synchronize_rings(), and Slic3r::trianglulate_wall_detail::trscore().
size()
size_t Slic3r::trianglulate_wall_detail::Ring::size () const inline
{ return end - begin; }
References begin, and end.
Referenced by init(), and is_lower().
Member Data Documentation
begin
size_t Slic3r::trianglulate_wall_detail::Ring::begin = 0 private
Referenced by Ring(), inc(), init(), and size().
end
size_t Slic3r::trianglulate_wall_detail::Ring::end = 0 private
Referenced by inc(), and size().
idx
size_t Slic3r::trianglulate_wall_detail::Ring::idx = 0 private
Referenced by inc(), init(), is_finished(), is_lower(), and pos().
nextidx
size_t Slic3r::trianglulate_wall_detail::Ring::nextidx = 1 private
Referenced by inc(), init(), is_finished(), and pos().
startidx
size_t Slic3r::trianglulate_wall_detail::Ring::startidx = 0 private
Referenced by inc(), and init().
The documentation for this class was generated from the following file:
src/libslic3r/TriangulateWall.hpp