Prusa Slicer: Slic3r::GCodeProcessor::TimeProcessor Struct Reference
Slic3r::GCodeProcessor::TimeProcessor Struct Reference
Classes
struct Planner
Public Member Functions
void reset ()
Public Attributes
bool extruder_unloaded
bool export_remaining_time_enabled
bool machine_envelope_processing_enabled
MachineEnvelopeConfig machine_limits
std::vector< float > filament_load_times
std::vector< float > filament_unload_times
std::array< TimeMachine, static_cast< size_t >(PrintEstimatedStatistics::ETimeMode::Count)> machines
Friends
class GCodeProcessor
Detailed Description
Member Function Documentation
reset()
void Slic3r::GCodeProcessor::TimeProcessor::reset ()
{
    extruder_unloaded = true;
    export_remaining_time_enabled = false;
    machine_envelope_processing_enabled = false;
    machine_limits = MachineEnvelopeConfig();
    filament_load_times = std::vector<float>();
    filament_unload_times = std::vector<float>();
    for (size_t i = 0; i < static_cast<size_t>(PrintEstimatedStatistics::ETimeMode::Count); ++i) {
        machines[i].reset();
    }
    machines[static_cast<size_t>(PrintEstimatedStatistics::ETimeMode::Normal)].enabled = true;
}
References Slic3r::PrintEstimatedStatistics::Count, and Slic3r::PrintEstimatedStatistics::Normal.
Referenced by Slic3r::GCodeProcessor::reset().
Friends And Related Symbol Documentation
GCodeProcessor
friend class GCodeProcessor friend
Member Data Documentation
export_remaining_time_enabled
bool Slic3r::GCodeProcessor::TimeProcessor::export_remaining_time_enabled
Referenced by Slic3r::GCodeProcessor::apply_config(), and Slic3r::GCodeProcessor::post_process().
extruder_unloaded
bool Slic3r::GCodeProcessor::TimeProcessor::extruder_unloaded
Referenced by Slic3r::GCodeProcessor::get_filament_load_time(), Slic3r::GCodeProcessor::get_filament_unload_time(), Slic3r::GCodeProcessor::process_M702(), and Slic3r::GCodeProcessor::process_T().
filament_load_times
std::vector<float> Slic3r::GCodeProcessor::TimeProcessor::filament_load_times
Referenced by Slic3r::GCodeProcessor::apply_config(), Slic3r::GCodeProcessor::apply_config(), and Slic3r::GCodeProcessor::get_filament_load_time().
filament_unload_times
std::vector<float> Slic3r::GCodeProcessor::TimeProcessor::filament_unload_times
Referenced by Slic3r::GCodeProcessor::apply_config(), Slic3r::GCodeProcessor::apply_config(), and Slic3r::GCodeProcessor::get_filament_unload_time().
machine_envelope_processing_enabled
bool Slic3r::GCodeProcessor::TimeProcessor::machine_envelope_processing_enabled
Referenced by Slic3r::GCodeProcessor::enable_machine_envelope_processing(), Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M204(), and Slic3r::GCodeProcessor::process_M205().
machine_limits
MachineEnvelopeConfig Slic3r::GCodeProcessor::TimeProcessor::machine_limits
Referenced by Slic3r::GCodeProcessor::apply_config(), Slic3r::GCodeProcessor::apply_config(), Slic3r::GCodeProcessor::get_axis_max_acceleration(), Slic3r::GCodeProcessor::get_axis_max_feedrate(), Slic3r::GCodeProcessor::get_axis_max_jerk(), Slic3r::GCodeProcessor::minimum_feedrate(), Slic3r::GCodeProcessor::minimum_travel_feedrate(), Slic3r::GCodeProcessor::process_M201(), Slic3r::GCodeProcessor::process_M203(), Slic3r::GCodeProcessor::process_M205(), and Slic3r::GCodeProcessor::process_M566().
machines
std::array<TimeMachine, static_cast<size_t>(PrintEstimatedStatistics::ETimeMode::Count)> Slic3r::GCodeProcessor::TimeProcessor::machines
Referenced by Slic3r::GCodeProcessor::GCodeProcessor(), Slic3r::GCodeProcessor::apply_config(), Slic3r::GCodeProcessor::apply_config(), Slic3r::GCodeProcessor::enable_stealth_time_estimator(), Slic3r::GCodeProcessor::finalize(), Slic3r::GCodeProcessor::get_acceleration(), Slic3r::GCodeProcessor::get_custom_gcode_times(), Slic3r::GCodeProcessor::get_layers_time(), Slic3r::GCodeProcessor::get_moves_time(), Slic3r::GCodeProcessor::get_retract_acceleration(), Slic3r::GCodeProcessor::get_roles_time(), Slic3r::GCodeProcessor::get_time(), Slic3r::GCodeProcessor::get_time_dhm(), Slic3r::GCodeProcessor::get_travel_acceleration(), Slic3r::GCodeProcessor::get_travel_time(), Slic3r::GCodeProcessor::get_travel_time_dhm(), Slic3r::GCodeProcessor::is_stealth_time_estimator_enabled(), Slic3r::GCodeProcessor::post_process(), Slic3r::GCodeProcessor::process_custom_gcode_time(), Slic3r::GCodeProcessor::process_G1(), Slic3r::GCodeProcessor::process_M221(), Slic3r::GCodeProcessor::set_acceleration(), Slic3r::GCodeProcessor::set_retract_acceleration(), Slic3r::GCodeProcessor::set_travel_acceleration(), Slic3r::GCodeProcessor::simulate_st_synchronize(), Slic3r::GCodeProcessor::store_move_vertex(), and Slic3r::GCodeProcessor::update_estimated_times_stats().
The documentation for this struct was generated from the following files:
src/libslic3r/GCode/GCodeProcessor.hpp
src/libslic3r/GCode/GCodeProcessor.cpp