Prusa Slicer: Slic3r::ConfigOptionVector< T > Class Template Reference
Slic3r::ConfigOptionVector< T > Class Template Reference abstract
#include <src/libslic3r/Config.hpp>
Public Member Functions
ConfigOptionVector ()
ConfigOptionVector (size_t n, const T &value)
ConfigOptionVector (std::initializer_list< T > il)
ConfigOptionVector (const std::vector< T > &values)
ConfigOptionVector (std::vector< T > &&values)
void set (const ConfigOption *rhs) override
void set (const std::vector< const ConfigOption * > &rhs) override
void set_at (const ConfigOption *rhs, size_t i, size_t j) override
const T & get_at (size_t i) const
T & get_at (size_t i)
void resize (size_t n, const ConfigOption *opt_default=nullptr) override
void clear () override
size_t size () const override
bool empty () const override
bool operator== (const ConfigOption &rhs) const override
bool operator== (const std::vector< T > &rhs) const throw ()
bool operator!= (const std::vector< T > &rhs) const throw ()
size_t hash () const override throw ()
bool overriden_by (const ConfigOption *rhs) const override
bool apply_override (const ConfigOption *rhs) override
virtual std::vector< std::string > vserialize () const =0
virtual bool is_nil (size_t idx) const =0
virtual bool is_nil () const
virtual ConfigOptionType type () const =0
virtual std::string serialize () const =0
virtual bool deserialize (const std::string &str, bool append=false)=0
virtual ConfigOption * clone () const =0
virtual int getInt () const
virtual double getFloat () const
virtual bool getBool () const
virtual void setInt (int)
bool operator!= (const ConfigOption &rhs) const
bool is_scalar () const
bool is_vector () const
virtual bool nullable () const
Public Attributes
std::vector< T > values
Protected Member Functions
ConfigOptionType scalar_type () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Friends
class cereal::access
Detailed Description
template<class T>
class Slic3r::ConfigOptionVector< T >
Constructor & Destructor Documentation
ConfigOptionVector() [1/5]
template<class T > Slic3r::ConfigOptionVector< T >::ConfigOptionVector () inline
{}
ConfigOptionVector() [2/5]
template<class T > Slic3r::ConfigOptionVector< T >::ConfigOptionVector (size_t n, const T & value) inline explicit
: values(n, value) {}
ConfigOptionVector() [3/5]
template<class T > Slic3r::ConfigOptionVector< T >::ConfigOptionVector (std::initializer_list< T > il) inline explicit
: values(std::move(il)) {}
ConfigOptionVector() [4/5]
template<class T > Slic3r::ConfigOptionVector< T >::ConfigOptionVector (const std::vector< T > & values) inline explicit
: values(values) {}
ConfigOptionVector() [5/5]
template<class T > Slic3r::ConfigOptionVector< T >::ConfigOptionVector (std::vector< T > && values) inline explicit
: values(std::move(values)) {}
Member Function Documentation
apply_override()
template<class T > bool Slic3r::ConfigOptionVector< T >::apply_override (const ConfigOption * rhs) inline override virtual
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
      throw ConfigurationError("ConfigOptionVector.apply_override() applied to different types.");
    auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
    if (! rhs->nullable()) {
        // Overridding a non-nullable object with another non-nullable object.
        if (this->values != rhs_vec->values) {
          this->values = rhs_vec->values;
          return true;
        }
        return false;
      }
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      bool   modified = false;
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i]) {
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i)) {
          if (this->values.empty())
            this->values.resize(i + 1);
          else
            this->values.resize(i + 1, this->values.front());
          this->values[i] = rhs_vec->values[i];
          modified = true;
        }
        return modified;
    }
References Slic3r::ConfigOption::nullable(), Slic3r::ConfigOptionVector< T >::size(), Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionVector< T >::values.
clear()
template<class T > void Slic3r::ConfigOptionVector< T >::clear () inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
{ this->values.clear(); }
Referenced by Slic3r::GUI::SubstitutionManager::delete_all(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetBundle::load_config_file_config_bundle(), and Slic3r::PhysicalPrinter::update_preset_names_in_config().
clone()
virtual ConfigOption * Slic3r::ConfigOption::clone () const pure virtual inherited
Implemented in Slic3r::ConfigOptionFloat, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionInt, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionString, Slic3r::ConfigOptionStrings, Slic3r::ConfigOptionPercent, Slic3r::ConfigOptionPercentsTempl< NULLABLE >, Slic3r::ConfigOptionFloatOrPercent, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionPoint, Slic3r::ConfigOptionPoints, Slic3r::ConfigOptionPoint3, Slic3r::ConfigOptionBool, Slic3r::ConfigOptionBoolsTempl< NULLABLE >, Slic3r::ConfigOptionEnum< T >, and Slic3r::ConfigOptionEnumGeneric.
Referenced by Slic3r::DynamicConfig::DynamicConfig(), Slic3r::GUI::ObjectSettings::add_missed_options(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::GUI::ConfigManipulation::apply(), Slic3r::PlaceholderParser::apply_config(), Slic3r::PlaceholderParser::apply_only(), Slic3r::GUI::PlaterPresetComboBox::change_extruder_color(), Slic3r::GUI::Tab::load_config(), Slic3r::GUI::Plater::on_config_change(), Slic3r::print_config_diffs(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
deserialize()
virtual bool Slic3r::ConfigOption::deserialize (const std::string & str, bool append = false) pure virtual inherited
Implemented in Slic3r::ConfigOptionFloat, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionInt, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionString, Slic3r::ConfigOptionStrings, Slic3r::ConfigOptionPercent, Slic3r::ConfigOptionFloatOrPercent, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionPoint, Slic3r::ConfigOptionPoints, Slic3r::ConfigOptionPoint3, Slic3r::ConfigOptionBool, Slic3r::ConfigOptionBoolsTempl< NULLABLE >, Slic3r::ConfigOptionEnum< T >, and Slic3r::ConfigOptionEnumGeneric.
Referenced by Slic3r::ConfigBase::null_nullables(), Slic3r::DynamicConfig::read_cli(), and Slic3r::ConfigBase::set_deserialize_raw().
empty()
template<class T > bool Slic3r::ConfigOptionVector< T >::empty () const inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.empty(); }
Referenced by Slic3r::GUI::TextCtrl::BUILD(), Slic3r::GUI::Tab::compatible_widget_reload(), Slic3r::GUI::get_string_value(), and Slic3r::GUI::SubstitutionManager::is_empty_substitutions().
get_at() [1/2]
template<class T > T & Slic3r::ConfigOptionVector< T >::get_at (size_t i) inline
{ return const_cast<T&>(std::as_const(*this).get_at(i)); }
get_at() [2/2]
template<class T > const T & Slic3r::ConfigOptionVector< T >::get_at (size_t i) const inline
    {
        assert(! this->values.empty());
        return (i < this->values.size()) ? this->values[i] : this->values.front();
    }
References Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::GUI::TextCtrl::BUILD(), Slic3r::GUI::get_string_value(), and Slic3r::OozePrevention::pre_toolchange().
getBool()
virtual bool Slic3r::ConfigOption::getBool () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionBool.
{ throw BadOptionTypeException("Calling ConfigOption::getBool on a non-boolean ConfigOption");  }
Referenced by Slic3r::client::MyContext::scalar_variable_to_expr().
getFloat()
virtual double Slic3r::ConfigOption::getFloat () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloat.
{ throw BadOptionTypeException("Calling ConfigOption::getFloat on a non-float ConfigOption"); }
Referenced by Slic3r::GUI::TabSLAMaterial::build(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::scalar_variable_to_expr(), and Slic3r::GUI::Sidebar::update_sliced_info_sizer().
getInt()
virtual int Slic3r::ConfigOption::getInt () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::getInt on a non-int ConfigOption"); }
Referenced by Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::get_string_value(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
hash()
template<class T > size_t Slic3r::ConfigOptionVector< T >::hash () const throw () inline override virtual
Implements Slic3r::ConfigOption.
{
        std::hash<T> hasher;
        size_t seed = 0;
        for (const auto &v : this->values)
            boost::hash_combine(seed, hasher(v));
        return seed;
    }
References Slic3r::ConfigOptionVector< T >::values.
is_nil() [1/2]
virtual bool Slic3r::ConfigOption::is_nil () const inline virtual inherited
Reimplemented from Slic3r::ConfigOption.
{ return false; }
is_nil() [2/2]
virtual bool Slic3r::ConfigOptionVectorBase::is_nil (size_t idx) const pure virtual inherited
Implemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionBoolsTempl< NULLABLE >, Slic3r::ConfigOptionStrings, and Slic3r::ConfigOptionPoints.
Referenced by Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), and Slic3r::client::MyContext::vector_element_to_expr().
is_scalar()
bool Slic3r::ConfigOption::is_scalar () const inline inherited
{ return (int(this->type()) & int(coVectorType)) == 0; }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::client::MyContext::is_nil_test(), Slic3r::ConfigOption::is_vector(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::client::MyContext::vector_variable_assign_array(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), and Slic3r::client::MyContext::vector_variable_new_from_array().
is_vector()
bool Slic3r::ConfigOption::is_vector () const inline inherited
{ return ! this->is_scalar(); }
References Slic3r::ConfigOption::is_scalar().
Referenced by Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::client::MyContext::is_nil_test(), Slic3r::client::MyContext::is_vector_empty(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::DynamicConfig::read_cli(), Slic3r::client::MyContext::scalar_variable_assign_scalar_expression(), Slic3r::client::MyContext::scalar_variable_new_from_scalar_expression(), Slic3r::client::MyContext::store_variable_index(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::client::MyContext::variable_value(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_size(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
nullable()
virtual bool Slic3r::ConfigOption::nullable () const inline virtual inherited
Reimplemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
{ return false; }
Referenced by Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::ConfigBase::null_nullables(), Slic3r::ConfigOption::overriden_by(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::validate().
operator!=() [1/2]
bool Slic3r::ConfigOption::operator!= (const ConfigOption & rhs) const inline inherited
{ return ! (*this == rhs); }
operator!=() [2/2]
template<class T > bool Slic3r::ConfigOptionVector< T >::operator!= (const std::vector< T > & rhs) const throw () inline
{ return this->values != rhs; }
operator==() [1/2]
template<class T > bool Slic3r::ConfigOptionVector< T >::operator== (const ConfigOption & rhs) const inline override virtual
Implements Slic3r::ConfigOption.
    {
        if (rhs.type() != this->type())
            throw ConfigurationError("ConfigOptionVector: Comparing incompatible types");
        assert(dynamic_cast<const ConfigOptionVector<T>*>(&rhs));
        return this->values == static_cast<const ConfigOptionVector<T>*>(&rhs)->values;
    }
References Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionVector< T >::values.
operator==() [2/2]
template<class T > bool Slic3r::ConfigOptionVector< T >::operator== (const std::vector< T > & rhs) const throw () inline
{ return this->values == rhs; }
overriden_by()
template<class T > bool Slic3r::ConfigOptionVector< T >::overriden_by (const ConfigOption * rhs) const inline override virtual
Reimplemented from Slic3r::ConfigOption.
{
        if (this->nullable())
          throw ConfigurationError("Cannot override a nullable ConfigOption.");
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector.overriden_by() applied to different types.");
      auto rhs_vec = static_cast<const ConfigOptionVector<T>*>(rhs);
      if (! rhs->nullable())
        // Overridding a non-nullable object with another non-nullable object.
        return this->values != rhs_vec->values;
      size_t i = 0;
      size_t cnt = std::min(this->size(), rhs_vec->size());
      for (; i < cnt; ++ i)
        if (! rhs_vec->is_nil(i) && this->values[i] != rhs_vec->values[i])
          return true;
      for (; i < rhs_vec->size(); ++ i)
        if (! rhs_vec->is_nil(i))
          return true;
      return false;
    }
References Slic3r::ConfigOption::nullable(), Slic3r::ConfigOptionVector< T >::size(), Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionVector< T >::values.
resize()
template<class T > void Slic3r::ConfigOptionVector< T >::resize (size_t n, const ConfigOption * opt_default = nullptr) inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
    {
        assert(opt_default == nullptr || opt_default->is_vector());
//        assert(opt_default == nullptr || dynamic_cast<ConfigOptionVector<T>>(opt_default));
        assert(! this->values.empty() || opt_default != nullptr);
        if (n == 0)
            this->values.clear();
        else if (n < this->values.size())
            this->values.erase(this->values.begin() + n, this->values.end());
        else if (n > this->values.size()) {
            if (this->values.empty()) {
                if (opt_default == nullptr)
                    throw ConfigurationError("ConfigOptionVector::resize(): No default value provided.");
                if (opt_default->type() != this->type())
                    throw ConfigurationError("ConfigOptionVector::resize(): Extending with an incompatible type.");
                this->values.resize(n, static_cast<const ConfigOptionVector<T>*>(opt_default)->values.front());
            } else {
                // Resize by duplicating the last value.
                this->values.resize(n, this->values./*back*/front());
            }
        }
    }
References Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::Preset::normalize().
scalar_type()
ConfigOptionType Slic3r::ConfigOptionVectorBase::scalar_type () const inline protected inherited
{ return static_cast<ConfigOptionType>(this->type() - coVectorType); }
References Slic3r::coVectorType, and Slic3r::ConfigOption::type().
Referenced by Slic3r::ConfigOptionVector< T >::set(), and Slic3r::ConfigOptionVector< T >::set_at().
serialize() [1/2]
virtual std::string Slic3r::ConfigOption::serialize () const pure virtual inherited
Implemented in Slic3r::ConfigOptionFloat, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionInt, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionString, Slic3r::ConfigOptionStrings, Slic3r::ConfigOptionPercent, Slic3r::ConfigOptionPercentsTempl< NULLABLE >, Slic3r::ConfigOptionFloatOrPercent, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionPoint, Slic3r::ConfigOptionPoints, Slic3r::ConfigOptionPoint3, Slic3r::ConfigOptionBool, Slic3r::ConfigOptionBoolsTempl< NULLABLE >, Slic3r::ConfigOptionEnum< T >, and Slic3r::ConfigOptionEnumGeneric.
Referenced by Slic3r::anonymous_namespace{AnycubicSLA.cpp}::fill_header(), Slic3r::anonymous_namespace{SL1.cpp}::get_cfg_value(), Slic3r::client::MyContext::legacy_variable_expansion(), Slic3r::ConfigBase::opt_serialize(), and Slic3r::client::MyContext::scalar_variable_to_expr().
serialize() [2/2]
template<class T > template<class Archive > void Slic3r::ConfigOptionVector< T >::serialize (Archive & ar) inline private
{ ar(this->values); }
set() [1/2]
template<class T > void Slic3r::ConfigOptionVector< T >::set (const ConfigOption * rhs) inline override virtual
Implements Slic3r::ConfigOption.
    {
        if (rhs->type() != this->type())
            throw ConfigurationError("ConfigOptionVector: Assigning an incompatible type");
        assert(dynamic_cast<const ConfigOptionVector<T>*>(rhs));
        this->values = static_cast<const ConfigOptionVector<T>*>(rhs)->values;
    }
References Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionVector< T >::values.
set() [2/2]
template<class T > void Slic3r::ConfigOptionVector< T >::set (const std::vector< const ConfigOption * > & rhs) inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
    {
        this->values.clear();
        this->values.reserve(rhs.size());
        for (const ConfigOption *opt : rhs) {
            if (opt->type() == this->type()) {
                auto other = static_cast<const ConfigOptionVector<T>*>(opt);
                if (other->values.empty())
                    throw ConfigurationError("ConfigOptionVector::set(): Assigning from an empty vector");
                this->values.emplace_back(other->values.front());
            } else if (opt->type() == this->scalar_type())
                this->values.emplace_back(static_cast<const ConfigOptionSingle<T>*>(opt)->value);
            else
                throw ConfigurationError("ConfigOptionVector::set():: Assigning an incompatible type");
        }
    }
References Slic3r::ConfigOptionVectorBase::scalar_type(), Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionSingle< T >::value.
set_at()
template<class T > void Slic3r::ConfigOptionVector< T >::set_at (const ConfigOption * rhs, size_t i, size_t j) inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
    {
        // It is expected that the vector value has at least one value, which is the default, if not overwritten.
        assert(! this->values.empty());
        if (this->values.size() <= i) {
            // Resize this vector, fill in the new vector fields with the copy of the first field.
            T v = this->values.front();
            this->values.resize(i + 1, v);
        }
        if (rhs->type() == this->type()) {
            // Assign the first value of the rhs vector.
            auto other = static_cast<const ConfigOptionVector<T>*>(rhs);
            if (other->values.empty())
                throw ConfigurationError("ConfigOptionVector::set_at(): Assigning from an empty vector");
            this->values[i] = other->get_at(j);
        } else if (rhs->type() == this->scalar_type())
            this->values[i] = static_cast<const ConfigOptionSingle<T>*>(rhs)->value;
        else
            throw ConfigurationError("ConfigOptionVector::set_at(): Assigning an incompatible type");
    }
References Slic3r::ConfigOptionVectorBase::scalar_type(), Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionSingle< T >::value.
setInt()
virtual void Slic3r::ConfigOption::setInt (int) inline virtual inherited
Reimplemented in Slic3r::ConfigOptionInt, and Slic3r::ConfigOptionEnum< T >.
{ throw BadOptionTypeException("Calling ConfigOption::setInt on a non-int ConfigOption"); }
size()
template<class T > size_t Slic3r::ConfigOptionVector< T >::size () const inline override virtual
Implements Slic3r::ConfigOptionVectorBase.
{ return this->values.size(); }
Referenced by Slic3r::GCodeProcessor::apply_config(), Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::GUI_App::extruders_cnt(), Slic3r::GUI::GUI_App::extruders_edited_cnt(), Slic3r::GUI::get_string_value(), Slic3r::is_compatible_with_printer(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::ObjectList::split(), Slic3r::PresetCollection::update_compatible_internal(), Slic3r::ExtruderFilaments::update_compatible_internal(), Slic3r::GUI::TabFilament::update_extruder_combobox(), Slic3r::PresetBundle::update_filaments_compatible(), Slic3r::GUI::Sidebar::update_presets(), Slic3r::GUI::DiffPresetDialog::update_tree(), and Slic3r::GUI::Tab::update_wiping_button_visibility().
type()
virtual ConfigOptionType Slic3r::ConfigOption::type () const pure virtual inherited
Implemented in Slic3r::ConfigOptionFloat, Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionInt, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionString, Slic3r::ConfigOptionStrings, Slic3r::ConfigOptionPercent, Slic3r::ConfigOptionPercentsTempl< NULLABLE >, Slic3r::ConfigOptionFloatOrPercent, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionPoint, Slic3r::ConfigOptionPoints, Slic3r::ConfigOptionPoint3, Slic3r::ConfigOptionBool, Slic3r::ConfigOptionBoolsTempl< NULLABLE >, Slic3r::ConfigOptionEnum< T >, and Slic3r::ConfigOptionEnumGeneric.
Referenced by Slic3r::Search::OptionsSearcher::append_options(), Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::client::MyContext::copy_vector_variable_to_vector_variable(), Slic3r::deep_diff(), Slic3r::ConfigBase::get_abs_value(), Slic3r::ConfigBase::get_abs_value(), Slic3r::ConfigOption::is_scalar(), Slic3r::client::MyContext::legacy_variable_expansion2(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetBundle::load_config_file_config_bundle(), Slic3r::ConfigOptionSingle< T >::operator==(), Slic3r::ConfigOptionVector< T >::operator==(), Slic3r::ConfigOptionFloatsTempl< NULLABLE >::operator==(), Slic3r::ConfigOptionFloatOrPercent::operator==(), Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >::operator==(), Slic3r::ConfigOptionEnum< T >::operator==(), Slic3r::ConfigOptionEnumGeneric::operator==(), Slic3r::ConfigOptionResolver::option(), Slic3r::ConfigBase::option(), Slic3r::ConfigOptionResolver::option_throw(), Slic3r::ConfigBase::option_throw(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::DynamicConfig::read_cli(), Slic3r::ConfigOptionVectorBase::scalar_type(), Slic3r::client::MyContext::scalar_variable_assign_scalar(), Slic3r::client::MyContext::scalar_variable_to_expr(), Slic3r::ConfigOptionSingle< T >::set(), Slic3r::ConfigOptionVector< T >::set(), Slic3r::ConfigOptionFloatOrPercent::set(), Slic3r::ConfigOptionEnum< T >::set(), Slic3r::ConfigOptionEnumGeneric::set(), Slic3r::ConfigBase::set(), Slic3r::ConfigBase::set(), Slic3r::ConfigOptionVector< T >::set(), Slic3r::ConfigOptionVector< T >::set_at(), Slic3r::validate(), Slic3r::client::MyContext::vector_element_to_expr(), Slic3r::client::MyContext::vector_variable_assign_expr_with_count(), Slic3r::client::MyContext::vector_variable_assign_initializer_list(), Slic3r::client::MyContext::vector_variable_element_assign_scalar(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
vserialize()
virtual std::vector< std::string > Slic3r::ConfigOptionVectorBase::vserialize () const pure virtual inherited
Implemented in Slic3r::ConfigOptionFloatsTempl< NULLABLE >, Slic3r::ConfigOptionIntsTempl< NULLABLE >, Slic3r::ConfigOptionStrings, Slic3r::ConfigOptionPercentsTempl< NULLABLE >, Slic3r::ConfigOptionFloatsOrPercentsTempl< NULLABLE >, Slic3r::ConfigOptionPoints, and Slic3r::ConfigOptionBoolsTempl< NULLABLE >.
Referenced by Slic3r::client::MyContext::legacy_variable_expansion(), and Slic3r::client::MyContext::legacy_variable_expansion2().
Friends And Related Symbol Documentation
cereal::access
template<class T > friend class cereal::access friend
Member Data Documentation
values
template<class T > std::vector<T> Slic3r::ConfigOptionVector< T >::values
Referenced by Slic3r::GUI::BedShape::BedShape(), Slic3r::GCodeProcessor::apply_config(), Slic3r::ConfigOptionVector< T >::apply_override(), Slic3r::GUI::TextCtrl::BUILD(), Slic3r::GUI::TabPrinter::build_extruder_pages(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::BedShapePanel::build_panel(), Slic3r::GUI::TabPrinter::cache_extruder_cnt(), Slic3r::GUI::Bed3D::detect_type(), Slic3r::GUI::TabPrinter::extruders_count_changed(), Slic3r::GUI::Plater::force_filament_colors_update(), Slic3r::PresetBundle::full_fff_config(), Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::Materials::get_filament_type(), Slic3r::GUI::get_string_value(), Slic3r::ConfigOptionVector< T >::hash(), Slic3r::PrintConfigDef::init_fff_params(), Slic3r::GUI::MainFrame::init_tabpanel(), Slic3r::is_compatible_with_print(), Slic3r::is_compatible_with_printer(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::GUI::TabPrinter::on_preset_loaded(), Slic3r::ConfigOptionVector< T >::operator==(), Slic3r::ConfigOptionVector< T >::overriden_by(), Slic3r::GCode::placeholder_parser_process(), Slic3r::ConfigOptionVector< T >::resize(), Slic3r::ConfigOptionVector< T >::set(), Slic3r::GUI::Plater::set_bed_shape(), Slic3r::GUI::BedShapePanel::set_shape(), Slic3r::GUI::PointCtrl::set_value(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GLVolumeCollection::update_colors_by_extruder(), Slic3r::PresetBundle::update_multi_material_filament_presets(), Slic3r::GUI::DiffPresetDialog::update_tree(), Slic3r::GUI::UnsavedChangesDialog::update_tree(), Slic3r::validate(), Slic3r::client::MyContext::vector_element_to_expr(), and Slic3r::client::MyContext::vector_variable_new_from_copy().
The documentation for this class was generated from the following file:
src/libslic3r/Config.hpp