Prusa Slicer: Slic3r::TriangleMesh Class Reference
Slic3r::TriangleMesh Class Reference
#include <src/libslic3r/TriangleMesh.hpp>
Public Member Functions
TriangleMesh ()=default
TriangleMesh (const std::vector< Vec3f > &vertices, const std::vector< Vec3i > &faces)
TriangleMesh (std::vector< Vec3f > &&vertices, const std::vector< Vec3i > &&faces)
TriangleMesh (const indexed_triangle_set &M)
TriangleMesh (indexed_triangle_set &&M, const RepairedMeshErrors &repaired_errors=RepairedMeshErrors())
void clear ()
bool ReadSTLFile (const char *input_file, bool repair=true)
bool write_ascii (const char *output_file)
bool write_binary (const char *output_file)
float volume ()
void WriteOBJFile (const char *output_file) const
void scale (float factor)
void scale (const Vec3f &versor)
void translate (float x, float y, float z)
void translate (const Vec3f &displacement)
void rotate (float angle, const Axis &axis)
void rotate (float angle, const Vec3d &axis)
void rotate_x (float angle)
void rotate_y (float angle)
void rotate_z (float angle)
void mirror (const Axis axis)
void mirror_x ()
void mirror_y ()
void mirror_z ()
void transform (const Transform3d &t, bool fix_left_handed=false)
void transform (const Matrix3d &t, bool fix_left_handed=false)
void flip_triangles ()
void align_to_origin ()
void rotate (double angle, Point *center)
std::vector< TriangleMesh > split () const
void merge (const TriangleMesh &mesh)
ExPolygons horizontal_projection () const
Polygon convex_hull ()
BoundingBoxf3 bounding_box () const
BoundingBoxf3 transformed_bounding_box (const Transform3d &trafo) const
BoundingBoxf3 transformed_bounding_box (const Transform3d &trafo, double world_min_z) const
Vec3d size () const
Vec3d center () const
Return the center of the related bounding box.
TriangleMesh convex_hull_3d () const
std::vector< ExPolygons > slice (const std::vector< double > &z) const
size_t facets_count () const
bool empty () const
bool repaired () const
bool is_splittable () const
bool has_zero_volume () const
size_t memsize () const
size_t release_optional ()
void restore_optional ()
const TriangleMeshStats & stats () const
Public Attributes
indexed_triangle_set its
Private Attributes
TriangleMeshStats m_stats
Detailed Description
Constructor & Destructor Documentation
TriangleMesh() [1/5]
Slic3r::TriangleMesh::TriangleMesh () default
TriangleMesh() [2/5]
Slic3r::TriangleMesh::TriangleMesh (const std::vector< Vec3f > & vertices, const std::vector< Vec3i > & faces)
                                                                                          : its { faces, vertices }
{
    fill_initial_stats(this->its, m_stats);
}
References Slic3r::fill_initial_stats(), its, and m_stats.
TriangleMesh() [3/5]
Slic3r::TriangleMesh::TriangleMesh (std::vector< Vec3f > && vertices, const std::vector< Vec3i > && faces)
                                                                                      : its { std::move(faces), std::move(vertices) }
{
    fill_initial_stats(this->its, m_stats);
}
References Slic3r::fill_initial_stats(), its, and m_stats.
TriangleMesh() [4/5]
Slic3r::TriangleMesh::TriangleMesh (const indexed_triangle_set & M) explicit
                                                          : its(its)
{
    fill_initial_stats(this->its, m_stats);
}
References Slic3r::fill_initial_stats(), and m_stats.
TriangleMesh() [5/5]
Slic3r::TriangleMesh::TriangleMesh (indexed_triangle_set && M, const RepairedMeshErrors & repaired_errors = RepairedMeshErrors()) explicit
                                                                                        : its(std::move(its))
{
    m_stats.repaired_errors = errors;
    fill_initial_stats(this->its, m_stats);
}
References Slic3r::fill_initial_stats(), its, m_stats, and Slic3r::TriangleMeshStats::repaired_errors.
Member Function Documentation
align_to_origin()
void Slic3r::TriangleMesh::align_to_origin ()
{
    this->translate(- m_stats.min(0), - m_stats.min(1), - m_stats.min(2));
}
References m_stats, Slic3r::TriangleMeshStats::min, and translate().
bounding_box()
BoundingBoxf3 Slic3r::TriangleMesh::bounding_box () const
{
    BoundingBoxf3 bb;
    bb.defined = true;
    bb.min = m_stats.min.cast<double>();
    bb.max = m_stats.max.cast<double>();
    return bb;
}
References Slic3r::BoundingBoxBase< PointType, APointsType >::defined, m_stats, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::TriangleMeshStats::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, and Slic3r::TriangleMeshStats::min.
Referenced by Slic3r::bounding_box(), center(), Slic3r::ModelVolume::center_geometry_after_creation(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::ModelObject::print_info(), Slic3r::GUI::Emboss::CreateVolumeJob::process(), Slic3r::GUI::Emboss::UpdateJob::process(), and Slic3r::GUI::Selection::scale_to_fit_print_volume().
center()
Vec3d Slic3r::TriangleMesh::center () const inline
Return the center of the related bounding box.
{ return this->bounding_box().center(); }
References bounding_box(), and Slic3r::BoundingBox3Base< PointType >::center().
Referenced by Slic3r::GUI::Emboss::CreateObjectJob::process(), and rotate().
clear()
void Slic3r::TriangleMesh::clear () inline
{ this->its.clear(); m_stats.clear(); }
References indexed_triangle_set::clear(), Slic3r::TriangleMeshStats::clear(), its, and m_stats.
Referenced by Slic3r::GUI::GLGizmoCut3D::update_connector_shape().
convex_hull()
Polygon Slic3r::TriangleMesh::convex_hull ()
{
    Points pp;
    pp.reserve(this->its.vertices.size());
    for (size_t i = 0; i < this->its.vertices.size(); ++ i) {
        const stl_vertex &v = this->its.vertices[i];
        pp.emplace_back(Point::new_scale(v(0), v(1)));
    }
    return Slic3r::Geometry::convex_hull(pp);
}
References Slic3r::Geometry::convex_hull(), its, and indexed_triangle_set::vertices.
Referenced by Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::get_chull_rotations(), and Slic3r::GUI::Selection::scale_to_fit_print_volume().
convex_hull_3d()
TriangleMesh Slic3r::TriangleMesh::convex_hull_3d () const
{
    TriangleMesh mesh(its_convex_hull(this->its));
    // Quite often qhull produces non-manifold mesh.
    // assert(mesh.stats().manifold());
    return mesh;
}
References its, and Slic3r::its_convex_hull().
Referenced by Slic3r::sla::find_min_z_height_rotation(), Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::get_chull_rotations(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), and Slic3r::GUI::GLGizmoFlatten::update_planes().
empty()
bool Slic3r::TriangleMesh::empty () const inline
{ return this->facets_count() == 0; }
References facets_count().
Referenced by Slic3r::GUI::Emboss::create_sources(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::GUI::Emboss::CreateObjectJob::finalize(), Slic3r::sla::hollow_mesh(), Slic3r::load_obj(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::load_stl(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::ModelObject::process_solid_part_cut(), Slic3r::ModelVolume::split(), Slic3r::SLAPrint::Steps::support_tree(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
facets_count()
size_t Slic3r::TriangleMesh::facets_count () const inline
{ assert(m_stats.number_of_facets == this->its.indices.size()); return m_stats.number_of_facets; }
References m_stats, and Slic3r::TriangleMeshStats::number_of_facets.
Referenced by empty(), Slic3r::SlicingAdaptive::prepare(), Slic3r::ModelObject::print_info(), Slic3r::ModelObject::split(), and Slic3r::GUI::GLGizmoFlatten::update_planes().
flip_triangles()
void Slic3r::TriangleMesh::flip_triangles ()
{
    its_flip_triangles(its);
    m_stats.volume = - m_stats.volume;
}
References its, Slic3r::its_flip_triangles(), m_stats, and Slic3r::TriangleMeshStats::volume.
Referenced by Slic3r::_3MF_Importer::_generate_volumes(), Slic3r::load_obj(), and Slic3r::GUI::GLGizmoMeasure::update_if_needed().
has_zero_volume()
bool Slic3r::TriangleMesh::has_zero_volume () const
{
    const Vec3d sz = size();
    const double volume_val = sz.x() * sz.y() * sz.z();
    return is_approx(volume_val, 0.0);
}
References Slic3r::is_approx(), and size().
Referenced by Slic3r::ModelObject::split(), and Slic3r::ModelVolume::split().
horizontal_projection()
ExPolygons Slic3r::TriangleMesh::horizontal_projection () const
{
    return union_ex(project_mesh(this->its, Transform3d::Identity(), []() {}));
}
References Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), its, Slic3r::project_mesh(), and Slic3r::union_ex().
Referenced by Slic3r::GUI::BedShapePanel::load_stl().
is_splittable()
bool Slic3r::TriangleMesh::is_splittable () const
Calculates whether or not the mesh is splittable.
{
    return its_is_splittable(this->its);
}
References its, and Slic3r::its_is_splittable().
memsize()
size_t Slic3r::TriangleMesh::memsize () const
{
    size_t memsize = 8 + this->its.memsize() + sizeof(m_stats);
    return memsize;
}
References its, m_stats, indexed_triangle_set::memsize(), and memsize().
Referenced by memsize().
merge()
void Slic3r::TriangleMesh::merge (const TriangleMesh & mesh)
{
    its_merge(this->its, mesh.its);
    m_stats = m_stats.merge(mesh.m_stats);
}
References its, Slic3r::its_merge(), m_stats, and Slic3r::TriangleMeshStats::merge().
Referenced by Slic3r::sla::cut_drainholes(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::sla::hollow_mesh(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::ModelObject::merge(), Slic3r::ModelObject::mesh(), Slic3r::Model::mesh(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::ModelObject::raw_mesh(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), and Slic3r::GUI::GLGizmoFlatten::update_planes().
mirror()
void Slic3r::TriangleMesh::mirror (const Axis axis)
{
    switch (axis) {
    case X:
        for (stl_vertex &v : its.vertices)
            v.x() *= -1.f;
        break;
    case Y:
        for (stl_vertex& v : this->its.vertices)
            v.y() *= -1.0;
        break;
    case Z:
        for (stl_vertex &v : this->its.vertices)
            v.z() *= -1.0;
        break;
    default:
        assert(false);
        return;
    };
    its_flip_triangles(this->its);
    int iaxis = int(axis);
    std::swap(m_stats.min[iaxis], m_stats.max[iaxis]);
    m_stats.min[iaxis] *= -1.0;
    m_stats.max[iaxis] *= -1.0;
}
References its, Slic3r::its_flip_triangles(), m_stats, Slic3r::TriangleMeshStats::max, Slic3r::TriangleMeshStats::min, indexed_triangle_set::vertices, Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by mirror_x(), mirror_y(), and mirror_z().
mirror_x()
void Slic3r::TriangleMesh::mirror_x () inline
{ this->mirror(X); }
References mirror(), and Slic3r::X.
mirror_y()
void Slic3r::TriangleMesh::mirror_y () inline
{ this->mirror(Y); }
References mirror(), and Slic3r::Y.
mirror_z()
void Slic3r::TriangleMesh::mirror_z () inline
{ this->mirror(Z); }
References mirror(), and Slic3r::Z.
ReadSTLFile()
bool Slic3r::TriangleMesh::ReadSTLFile (const char * input_file, bool repair = true)
{
    stl_file stl;
    if (! stl_open(&stl, input_file))
        return false;
    if (repair)
        trianglemesh_repair_on_import(stl);
    m_stats.number_of_facets        = stl.stats.number_of_facets;
    m_stats.min                     = stl.stats.min;
    m_stats.max                     = stl.stats.max;
    m_stats.size                    = stl.stats.size;
    m_stats.volume                  = stl.stats.volume;
    auto facets_w_1_bad_edge = stl.stats.connected_facets_2_edge - stl.stats.connected_facets_3_edge;
    auto facets_w_2_bad_edge = stl.stats.connected_facets_1_edge - stl.stats.connected_facets_2_edge;
    auto facets_w_3_bad_edge = stl.stats.number_of_facets - stl.stats.connected_facets_1_edge;
    m_stats.open_edges              = stl.stats.backwards_edges + facets_w_1_bad_edge + facets_w_2_bad_edge * 2 + facets_w_3_bad_edge * 3;
    m_stats.repaired_errors = { stl.stats.edges_fixed,
                                stl.stats.degenerate_facets,
                                stl.stats.facets_removed,
                                stl.stats.facets_reversed,
                                stl.stats.backwards_edges };
    m_stats.number_of_parts         = stl.stats.number_of_parts;
    stl_generate_shared_vertices(&stl, this->its);
    return true;
}
References stl_stats::backwards_edges, stl_stats::connected_facets_1_edge, stl_stats::connected_facets_2_edge, stl_stats::connected_facets_3_edge, stl_stats::degenerate_facets, stl_stats::edges_fixed, stl_stats::facets_removed, stl_stats::facets_reversed, its, m_stats, stl_stats::max, Slic3r::TriangleMeshStats::max, stl_stats::min, Slic3r::TriangleMeshStats::min, stl_stats::number_of_facets, Slic3r::TriangleMeshStats::number_of_facets, stl_stats::number_of_parts, Slic3r::TriangleMeshStats::number_of_parts, Slic3r::TriangleMeshStats::open_edges, Slic3r::TriangleMeshStats::repaired_errors, stl_stats::size, Slic3r::TriangleMeshStats::size, stl_file::stats, stl_generate_shared_vertices(), stl_open(), Slic3r::trianglemesh_repair_on_import(), stl_stats::volume, and Slic3r::TriangleMeshStats::volume.
Referenced by Slic3r::GUI::GalleryDialog::load_files(), Slic3r::GUI::GalleryDialog::load_label_icon_list(), Slic3r::load_stl(), and Slic3r::GUI::MainFrame::repair_stl().
release_optional()
size_t Slic3r::TriangleMesh::release_optional () inline
{ return 0; }
repaired()
bool Slic3r::TriangleMesh::repaired () const
restore_optional()
void Slic3r::TriangleMesh::restore_optional () inline
{}
rotate() [1/3]
void Slic3r::TriangleMesh::rotate (double angle, Point * center)
{
    if (angle != 0.) {
        Vec2f c = center->cast<float>();
        this->translate(-c(0), -c(1), 0);
        its_rotate_z(this->its, (float)angle);
        this->translate(c(0), c(1), 0);
    }
}
References Slic3r::angle(), center(), its, its_rotate_z(), and translate().
rotate() [2/3]
void Slic3r::TriangleMesh::rotate (float angle, const Axis & axis)
{
    if (angle != 0.f) {
        angle = Slic3r::Geometry::rad2deg(angle);
        switch (axis) {
        case X:  its_rotate_x(this->its, angle); break;
        case Y:  its_rotate_y(this->its, angle); break;
        case Z:  its_rotate_z(this->its, angle); break;
        default: assert(false);                  return;
        }
        update_bounding_box(this->its, m_stats);
    }
}
References Slic3r::angle(), its, its_rotate_x(), its_rotate_y(), its_rotate_z(), m_stats, Slic3r::Geometry::rad2deg(), Slic3r::update_bounding_box(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by rotate_x(), rotate_y(), and rotate_z().
rotate() [3/3]
void Slic3r::TriangleMesh::rotate (float angle, const Vec3d & axis)
{
    if (angle != 0.f) {
        Vec3d axis_norm = axis.normalized();
        Transform3d m = Transform3d::Identity();
        m.rotate(Eigen::AngleAxisd(angle, axis_norm));
        its_transform(its, m);
        update_bounding_box(this->its, m_stats);
    }
}
References Slic3r::angle(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), its, its_transform(), m_stats, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotate(), and Slic3r::update_bounding_box().
rotate_x()
void Slic3r::TriangleMesh::rotate_x (float angle) inline
{ this->rotate(angle, X); }
References rotate(), and Slic3r::X.
rotate_y()
void Slic3r::TriangleMesh::rotate_y (float angle) inline
{ this->rotate(angle, Y); }
References rotate(), and Slic3r::Y.
rotate_z()
void Slic3r::TriangleMesh::rotate_z (float angle) inline
{ this->rotate(angle, Z); }
References rotate(), and Slic3r::Z.
scale() [1/2]
void Slic3r::TriangleMesh::scale (const Vec3f & versor)
{
    // Scale extents.
    auto s = versor.array();
    m_stats.min.array() *= s;
    m_stats.max.array() *= s;
    // Scale size.
    m_stats.size.array() *= s;
    // Scale volume.
    if (m_stats.volume > 0.0)
        m_stats.volume *= s(0) * s(1) * s(2);
    if (versor.x() == versor.y() && versor.x() == versor.z()) {
        float s = versor.x();
        for (stl_vertex &v : this->its.vertices)
            v *= s;
    } else {
        for (stl_vertex &v : this->its.vertices) {
            v.x() *= versor.x();
            v.y() *= versor.y();
            v.z() *= versor.z();
        }
    }
}
References its, m_stats, Slic3r::TriangleMeshStats::max, Slic3r::TriangleMeshStats::min, Slic3r::TriangleMeshStats::size, indexed_triangle_set::vertices, and Slic3r::TriangleMeshStats::volume.
scale() [2/2]
void Slic3r::TriangleMesh::scale (float factor)
{
    this->scale(Vec3f(factor, factor, factor));
}
References scale().
Referenced by Slic3r::GLVolumeCollection::load_wipe_tower_preview(), and scale().
size()
Vec3d Slic3r::TriangleMesh::size () const inline
{ return m_stats.size.cast<double>(); }
References m_stats, and Slic3r::TriangleMeshStats::size.
Referenced by has_zero_volume().
slice()
std::vector< ExPolygons > Slic3r::TriangleMesh::slice (const std::vector< double > & z) const
{
    // convert doubles to floats
    std::vector<float> z_f(z.begin(), z.end());
    return slice_mesh_ex(this->its, z_f, 0.0004f);
}
References its, and Slic3r::slice_mesh_ex().
split()
std::vector< TriangleMesh > Slic3r::TriangleMesh::split () const
{
    std::vector<indexed_triangle_set> itss = its_split(this->its);
    std::vector<TriangleMesh> out;
    out.reserve(itss.size());
    for (indexed_triangle_set &m : itss) {
        // The TriangleMesh constructor shall fill in the mesh statistics including volume.
        out.emplace_back(std::move(m));
        if (TriangleMesh &triangle_mesh = out.back(); triangle_mesh.volume() < 0)
            // Some source mesh parts may be incorrectly oriented. Correct them.
            triangle_mesh.flip_triangles();
    }
    return out;
}
References its, Slic3r::its_split(), and volume().
Referenced by Slic3r::ModelVolume::split().
stats()
const TriangleMeshStats & Slic3r::TriangleMesh::stats () const inline
{ return m_stats; }
References m_stats.
Referenced by Slic3r::ModelVolume::get_repaired_errors_count(), Slic3r::is_front_up_left(), cereal::load(), Slic3r::ModelObject::print_info(), cereal::save(), and Slic3r::GUI::Sidebar::show_info_sizer().
transform() [1/2]
void Slic3r::TriangleMesh::transform (const Matrix3d & t, bool fix_left_handed = false)
{
    its_transform(its, m);
    double det = m.block(0, 0, 3, 3).determinant();
    if (fix_left_handed && det < 0.) {
        its_flip_triangles(its);
        det = -det;
    }
    m_stats.volume *= det;
    update_bounding_box(this->its, m_stats);
}
References its, Slic3r::its_flip_triangles(), its_transform(), m_stats, Slic3r::update_bounding_box(), and Slic3r::TriangleMeshStats::volume.
transform() [2/2]
void Slic3r::TriangleMesh::transform (const Transform3d & t, bool fix_left_handed = false)
{
    its_transform(its, t);
    double det = t.matrix().block(0, 0, 3, 3).determinant();
    if (fix_left_handed && det < 0.) {
        its_flip_triangles(its);
        det = -det;
    }
    m_stats.volume *= det;
    update_bounding_box(this->its, m_stats);
}
References its, Slic3r::its_flip_triangles(), its_transform(), m_stats, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::update_bounding_box(), and Slic3r::TriangleMeshStats::volume.
Referenced by Slic3r::_3MF_Importer::_generate_volumes(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::get_mesh_to_rotate(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), Slic3r::GUI::GLGizmoCut3D::perform_cut(), Slic3r::SlicingAdaptive::prepare(), Slic3r::ModelObject::process_volume_cut(), Slic3r::ModelObject::raw_mesh(), Slic3r::GUI::Selection::scale_to_fit_print_volume(), Slic3r::ModelInstance::transform_mesh(), Slic3r::ModelVolume::transform_this_mesh(), Slic3r::ModelVolume::transform_this_mesh(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::GLGizmoFlatten::update_planes(), and Slic3r::GUI::GLGizmoSlaBase::update_volumes().
transformed_bounding_box() [1/2]
BoundingBoxf3 Slic3r::TriangleMesh::transformed_bounding_box (const Transform3d & trafo) const
{
    BoundingBoxf3 bbox;
    for (const stl_vertex &v : this->its.vertices)
        bbox.merge(trafo * v.cast<double>());
    return bbox;
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast(), its, Slic3r::BoundingBox3Base< PointType >::merge(), and indexed_triangle_set::vertices.
Referenced by Slic3r::GUI::GLGizmoCut3D::perform_cut(), and Slic3r::GUI::Sidebar::show_info_sizer().
transformed_bounding_box() [2/2]
BoundingBoxf3 Slic3r::TriangleMesh::transformed_bounding_box (const Transform3d & trafo, double world_min_z) const
{
    // 1) Allocate transformed vertices with their position with respect to print bed surface.
    std::vector<char>           sides;
    size_t                      num_above = 0;
    Eigen::AlignedBox<float, 3> bbox;
    Transform3f                 trafo = trafod.cast<float>();
    sides.reserve(its.vertices.size());
    for (const stl_vertex &v : this->its.vertices) {
        const stl_vertex pt   = trafo * v;
        const int        sign = pt.z() > world_min_z ? 1 : pt.z() < world_min_z ? -1 : 0;
        sides.emplace_back(sign);
        if (sign >= 0) {
            // Vertex above or on print bed surface. Test whether it is inside the build volume.
            ++ num_above;
            bbox.extend(pt);
        }
    }
    // 2) Calculate intersections of triangle edges with the build surface.
    if (num_above < its.vertices.size()) {
        // Not completely above the build surface and status may still change by testing edges intersecting the build platform.
        for (const stl_triangle_vertex_indices &tri : its.indices) {
            const int s[3] = { sides[tri(0)], sides[tri(1)], sides[tri(2)] };
            if (std::min(s[0], std::min(s[1], s[2])) < 0 && std::max(s[0], std::max(s[1], s[2])) > 0) {
                // Some edge of this triangle intersects the build platform. Calculate the intersection.
                int iprev = 2;
                for (int iedge = 0; iedge < 3; ++ iedge) {
                    if (s[iprev] * s[iedge] == -1) {
                        // edge intersects the build surface. Calculate intersection point.
                        const stl_vertex p1 = trafo * its.vertices[tri(iprev)];
                        const stl_vertex p2 = trafo * its.vertices[tri(iedge)];
                        // Edge crosses the z plane. Calculate intersection point with the plane.
                        const float t = (world_min_z - p1.z()) / (p2.z() - p1.z());
                        bbox.extend(Vec3f(p1.x() + (p2.x() - p1.x()) * t, p1.y() + (p2.y() - p1.y()) * t, world_min_z));
                    }
                    iprev = iedge;
                }
            }
        }
    }
    BoundingBoxf3 out;
    if (! bbox.isEmpty()) {
        out.min = bbox.min().cast<double>();
        out.max = bbox.max().cast<double>();
        out.defined = true;
    };
    return out;
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast(), Slic3r::BoundingBoxBase< PointType, APointsType >::defined, Eigen::AlignedBox< _Scalar, _AmbientDim >::extend(), indexed_triangle_set::indices, Eigen::AlignedBox< _Scalar, _AmbientDim >::isEmpty(), its, Eigen::AlignedBox< _Scalar, _AmbientDim >::max(), Slic3r::BoundingBoxBase< PointType, APointsType >::max, Eigen::AlignedBox< _Scalar, _AmbientDim >::min(), Slic3r::BoundingBoxBase< PointType, APointsType >::min, sign(), and indexed_triangle_set::vertices.
translate() [1/2]
void Slic3r::TriangleMesh::translate (const Vec3f & displacement)
{
    if (displacement.x() != 0.f || displacement.y() != 0.f || displacement.z() != 0.f) {
        for (stl_vertex& v : this->its.vertices)
            v += displacement;
        m_stats.min += displacement;
        m_stats.max += displacement;
    }
}
References its, m_stats, Slic3r::TriangleMeshStats::max, Slic3r::TriangleMeshStats::min, and indexed_triangle_set::vertices.
translate() [2/2]
void Slic3r::TriangleMesh::translate (float x, float y, float z)
{
    this->translate(Vec3f(x, y, z));
}
References translate().
Referenced by align_to_origin(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::Emboss::CreateVolumeJob::process(), Slic3r::GUI::Emboss::UpdateJob::process(), Slic3r::ModelObject::process_connector_cut(), rotate(), and translate().
volume()
float Slic3r::TriangleMesh::volume ()
{
    if (m_stats.volume == -1)
        m_stats.volume = its_volume(this->its);
    return m_stats.volume;
}
References its, Slic3r::its_volume(), m_stats, and Slic3r::TriangleMeshStats::volume.
Referenced by Slic3r::_3MF_Importer::_generate_volumes(), Slic3r::load_obj(), Slic3r::ModelObject::print_info(), split(), and Slic3r::GUI::GLGizmoMeasure::update_if_needed().
write_ascii()
bool Slic3r::TriangleMesh::write_ascii (const char * output_file)
{
    return its_write_stl_ascii(output_file, "", this->its);
}
References its, and Slic3r::its_write_stl_ascii().
Referenced by Slic3r::store_stl().
write_binary()
bool Slic3r::TriangleMesh::write_binary (const char * output_file)
{
    return its_write_stl_binary(output_file, "", this->its);
}
References its, and Slic3r::its_write_stl_binary().
Referenced by Slic3r::store_stl().
WriteOBJFile()
void Slic3r::TriangleMesh::WriteOBJFile (const char * output_file) const
{
    its_write_obj(this->its, output_file);
}
References its, and its_write_obj().
Referenced by Slic3r::GUI::MainFrame::repair_stl(), and Slic3r::store_obj().
Member Data Documentation
its
indexed_triangle_set Slic3r::TriangleMesh::its
Referenced by TriangleMesh(), TriangleMesh(), TriangleMesh(), Slic3r::MeshBoolean::cgal::_mesh_boolean_do(), Slic3r::GUI::Camera::calc_zoom_to_volumes_factor(), clear(), convex_hull(), convex_hull_3d(), Slic3r::GUI::CameraUtils::create_hull2d(), Slic3r::GUI::Emboss::create_sources(), Slic3r::TriangleSelector::deserialize(), Slic3r::MeshBoolean::cgal::does_self_intersect(), Slic3r::TriangleSelectorWrapper::enforce_spot(), Slic3r::GUI::Emboss::CreateVolumeJob::finalize(), Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::find_ground_level(), Slic3r::sla::find_min_z_height_rotation(), flip_triangles(), Slic3r::GUI::Selection::get_bounding_box_in_reference_system(), Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::get_chull_rotations(), Slic3r::ModelObject::get_instance_max_z(), Slic3r::ModelObject::get_instance_min_z(), Slic3r::csg::get_mesh(), Slic3r::csg::get_mesh(), Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::get_misalginment_score(), Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::get_supportedness_onfloor_score(), Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::get_supportedness_score(), Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::get_triangle_vertices(), Slic3r::sla::hollow_mesh(), horizontal_projection(), Slic3r::GUI::GLModel::init_from(), is_splittable(), cereal::load(), memsize(), merge(), mirror(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::SlicingAdaptive::prepare(), Slic3r::GUI::Emboss::UpdateJob::process(), Slic3r::ModelObject::process_volume_cut(), ReadSTLFile(), Slic3r::sla::remove_inside_triangles(), Slic3r::TriangleSelector::reset(), rotate(), rotate(), rotate(), cereal::save(), scale(), slice(), split(), transform(), transform(), transformed_bounding_box(), transformed_bounding_box(), translate(), Slic3r::MeshBoolean::cgal::triangle_mesh_to_cgal(), Slic3r::MeshBoolean::triangle_mesh_to_eigen(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GLVolume::NonManifoldEdges::update(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::Measure::MeasuringImpl::update_planes(), Slic3r::GUI::GLGizmoFlatten::update_planes(), volume(), write_ascii(), write_binary(), and WriteOBJFile().
m_stats
TriangleMeshStats Slic3r::TriangleMesh::m_stats private
Referenced by TriangleMesh(), TriangleMesh(), TriangleMesh(), TriangleMesh(), align_to_origin(), bounding_box(), clear(), facets_count(), flip_triangles(), memsize(), merge(), mirror(), ReadSTLFile(), rotate(), rotate(), scale(), size(), stats(), transform(), transform(), translate(), and volume().
The documentation for this class was generated from the following files:
src/libslic3r/TriangleMesh.hpp
src/libslic3r/TriangleMesh.cpp