Prusa Slicer: Slic3r::GUI::WindowMetrics Class Reference
Slic3r::GUI::WindowMetrics Class Reference
#include <src/slic3r/GUI/GUI_Utils.hpp>
Public Member Functions
const wxRect & get_rect () const
bool get_maximized () const
void sanitize_for_display (const wxRect &screen_rect)
std::string serialize () const
Static Public Member Functions
static WindowMetrics from_window (wxTopLevelWindow *window)
static boost::optional< WindowMetrics > deserialize (const std::string &str)
Private Member Functions
WindowMetrics ()
Private Attributes
wxRect rect
bool maximized
Detailed Description
Constructor & Destructor Documentation
WindowMetrics()
Slic3r::GUI::WindowMetrics::WindowMetrics () inline private
: maximized(false) {}
Member Function Documentation
deserialize()
boost::optional< WindowMetrics > Slic3r::GUI::WindowMetrics::deserialize (const std::string & str) static
{
    std::vector<std::string> metrics_str;
    metrics_str.reserve(5);
    if (!unescape_strings_cstyle(str, metrics_str) || metrics_str.size() != 5) {
        return boost::none;
    }
    int metrics[5];
    try {
        for (size_t i = 0; i < 5; i++) {
            metrics[i] = boost::lexical_cast<int>(metrics_str[i]);
        }
    } catch(const boost::bad_lexical_cast &) {
        return boost::none;
    }
    if ((metrics[4] & ~1) != 0) {    // Checks if the maximized flag is 1 or 0
        metrics[4] = 0;
    }
    WindowMetrics res;
    res.rect = wxRect(metrics[0], metrics[1], metrics[2], metrics[3]);
    res.maximized = metrics[4] != 0;
    return res;
}
References maximized, rect, and Slic3r::unescape_strings_cstyle().
Referenced by Slic3r::GUI::GUI_App::on_init_inner(), and Slic3r::GUI::GUI_App::window_pos_restore().
from_window()
WindowMetrics Slic3r::GUI::WindowMetrics::from_window (wxTopLevelWindow * window) static
{
    WindowMetrics res;
    res.rect = window->GetScreenRect();
    res.maximized = window->IsMaximized();
    return res;
}
References maximized, and rect.
Referenced by Slic3r::GUI::GUI_App::window_pos_sanitize(), and Slic3r::GUI::GUI_App::window_pos_save().
get_maximized()
bool Slic3r::GUI::WindowMetrics::get_maximized () const inline
{ return maximized; }
References maximized.
get_rect()
const wxRect & Slic3r::GUI::WindowMetrics::get_rect () const inline
{ return rect; }
References rect.
sanitize_for_display()
void Slic3r::GUI::WindowMetrics::sanitize_for_display (const wxRect & screen_rect)
{
    rect = rect.Intersect(screen_rect);
    // Prevent the window from going too far towards the right and/or bottom edge
    // It's hardcoded here that the threshold is 80% of the screen size
    rect.x = std::min(rect.x, screen_rect.x + 4*screen_rect.width/5);
    rect.y = std::min(rect.y, screen_rect.y + 4*screen_rect.height/5);
}
References rect.
serialize()
std::string Slic3r::GUI::WindowMetrics::serialize () const
{
    return (boost::format("%1%; %2%; %3%; %4%; %5%")
        % rect.x
        % rect.y
        % rect.width
        % rect.height
        % static_cast<int>(maximized)
    ).str();
}
References maximized, and rect.
Referenced by Slic3r::GUI::operator<<(), and Slic3r::GUI::GUI_App::window_pos_save().
Member Data Documentation
maximized
bool Slic3r::GUI::WindowMetrics::maximized private
Referenced by deserialize(), from_window(), get_maximized(), and serialize().
rect
wxRect Slic3r::GUI::WindowMetrics::rect private
Referenced by deserialize(), from_window(), get_rect(), sanitize_for_display(), and serialize().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_Utils.hpp
src/slic3r/GUI/GUI_Utils.cpp