Prusa Slicer: Slic3r::SL1Archive Class Reference
Slic3r::SL1Archive Class Reference
#include <src/libslic3r/Format/SL1.hpp>
Public Member Functions
SL1Archive ()=default
SL1Archive (const SLAPrinterConfig &cfg)
SL1Archive (SLAPrinterConfig &&cfg)
void export_print (const std::string fname, const SLAPrint &print, const ThumbnailsList &thumbnails, const std::string &projectname="") override
template<class Fn , class CancelFn , class EP = ExecutionTBB>
void draw_layers (size_t layer_num, Fn &&drawfn, CancelFn cancelfn=[]() { return false;}, const EP &ep={})
Static Public Member Functions
static std::unique_ptr< SLAArchiveWriter > create (const std::string &archtype, const SLAPrinterConfig &)
Protected Member Functions
std::unique_ptr< sla::RasterBase > create_raster () const override
sla::RasterEncoder get_encoder () const override
SLAPrinterConfig & cfg ()
const SLAPrinterConfig & cfg () const
void export_print (Zipper &, const SLAPrint &print, const ThumbnailsList &thumbnails, const std::string &projectname)
Protected Attributes
std::vector< sla::EncodedRaster > m_layers
Private Attributes
SLAPrinterConfig m_cfg
Detailed Description
Constructor & Destructor Documentation
SL1Archive() [1/3]
Slic3r::SL1Archive::SL1Archive () default
SL1Archive() [2/3]
Slic3r::SL1Archive::SL1Archive (const SLAPrinterConfig & cfg) inline explicit
: m_cfg(cfg) {}
SL1Archive() [3/3]
Slic3r::SL1Archive::SL1Archive (SLAPrinterConfig && cfg) inline explicit
: m_cfg(std::move(cfg)) {}
Member Function Documentation
cfg() [1/2]
SLAPrinterConfig & Slic3r::SL1Archive::cfg () inline protected
{ return m_cfg; }
References m_cfg.
Referenced by Slic3r::SL1_SVGArchive::create_raster().
cfg() [2/2]
const SLAPrinterConfig & Slic3r::SL1Archive::cfg () const inline protected
{ return m_cfg; }
References m_cfg.
create()
std::unique_ptr< SLAArchiveWriter > Slic3r::SLAArchiveWriter::create (const std::string & archtype, const SLAPrinterConfig & cfg) static inherited
{
    std::unique_ptr<SLAArchiveWriter> ret;
    auto factory = get_writer_factory(archtype.c_str());
    if (factory)
        ret = factory(cfg);
    return ret;
}
References Slic3r::get_writer_factory().
Referenced by Slic3r::SLAPrint::apply().
create_raster()
std::unique_ptr< sla::RasterBase > Slic3r::SL1Archive::create_raster () const override protected virtual
Implements Slic3r::SLAArchiveWriter.
{
    sla::Resolution res;
    sla::PixelDim   pxdim;
    std::array<bool, 2>         mirror;
    double w  = m_cfg.display_width.getFloat();
    double h  = m_cfg.display_height.getFloat();
    auto   pw = size_t(m_cfg.display_pixels_x.getInt());
    auto   ph = size_t(m_cfg.display_pixels_y.getInt());
    mirror[X] = m_cfg.display_mirror_x.getBool();
    mirror[Y] = m_cfg.display_mirror_y.getBool();
    auto ro = m_cfg.display_orientation.getInt();
    sla::RasterBase::Orientation orientation =
        ro == sla::RasterBase::roPortrait ? sla::RasterBase::roPortrait :
                                            sla::RasterBase::roLandscape;
    if (orientation == sla::RasterBase::roPortrait) {
        std::swap(w, h);
        std::swap(pw, ph);
    }
    res   = sla::Resolution{pw, ph};
    pxdim = sla::PixelDim{w / pw, h / ph};
    sla::RasterBase::Trafo tr{orientation, mirror};
    double gamma = m_cfg.gamma_correction.getFloat();
    return sla::create_raster_grayscale_aa(res, pxdim, gamma, tr);
}
References Slic3r::sla::create_raster_grayscale_aa(), m_cfg, Slic3r::sla::RasterBase::roLandscape, Slic3r::sla::RasterBase::roPortrait, Slic3r::X, and Slic3r::Y.
draw_layers()
template<class Fn , class CancelFn , class EP = ExecutionTBB> void Slic3r::SLAArchiveWriter::draw_layers (size_t layer_num, Fn && drawfn, CancelFn cancelfn = []() { return false; }, const EP & ep = {}) inline inherited
                                 { return false; },
        const EP & ep       = {})
    {
        m_layers.resize(layer_num);
        execution::for_each(
            ep, size_t(0), m_layers.size(),
            [this, &drawfn, &cancelfn](size_t idx) {
                if (cancelfn()) return;
                sla::EncodedRaster &enc = m_layers[idx];
                auto                rst = create_raster();
                drawfn(*rst, idx);
                enc = rst->encode(get_encoder());
            },
            execution::max_concurrency(ep));
    }
export_print() [1/2]
void Slic3r::SL1Archive::export_print (const std::string fname, const SLAPrint & print, const ThumbnailsList & thumbnails, const std::string & projectname = "") override virtual
Implements Slic3r::SLAArchiveWriter.
{
    Zipper zipper{fname, Zipper::FAST_COMPRESSION};
    export_print(zipper, print, thumbnails, prjname);
}
References export_print(), and Slic3r::Zipper::FAST_COMPRESSION.
export_print() [2/2]
void Slic3r::SL1Archive::export_print (Zipper & zipper, const SLAPrint & print, const ThumbnailsList & thumbnails, const std::string & projectname) protected
{
    std::string project =
        prjname.empty() ?
            boost::filesystem::path(zipper.get_filename()).stem().string() :
            prjname;
    ConfMap iniconf, slicerconf;
    fill_iniconf(iniconf, print);
    iniconf["jobDir"] = project;
    fill_slicerconf(slicerconf, print);
    try {
        zipper.add_entry("config.ini");
        zipper << to_ini(iniconf);
        zipper.add_entry("prusaslicer.ini");
        zipper << to_ini(slicerconf);
        size_t i = 0;
        for (const sla::EncodedRaster &rst : m_layers) {
            std::string imgname = project + string_printf("%.5d", i++) + "." +
                                  rst.extension();
            zipper.add_entry(imgname.c_str(), rst.data(), rst.size());
        }
        for (const ThumbnailData& data : thumbnails)
            if (data.is_valid())
                write_thumbnail(zipper, data);
        zipper.finalize();
    } catch(std::exception& e) {
        BOOST_LOG_TRIVIAL(error) << e.what();
        // Rethrow the exception
        throw;
    }
}
References Slic3r::Zipper::add_entry(), error, Slic3r::Zipper::finalize(), Slic3r::Zipper::get_filename(), Slic3r::SLAArchiveWriter::m_layers, Slic3r::string_printf(), and Slic3r::write_thumbnail().
Referenced by export_print(), and Slic3r::SL1_SVGArchive::export_print().
get_encoder()
sla::RasterEncoder Slic3r::SL1Archive::get_encoder () const override protected virtual
Implements Slic3r::SLAArchiveWriter.
{
    return sla::PNGRasterEncoder{};
}
Member Data Documentation
m_cfg
SLAPrinterConfig Slic3r::SL1Archive::m_cfg private
Referenced by cfg(), cfg(), and create_raster().
m_layers
std::vector<sla::EncodedRaster> Slic3r::SLAArchiveWriter::m_layers protected inherited
Referenced by Slic3r::AnycubicSLAArchive::export_print(), and export_print().
The documentation for this class was generated from the following files:
src/libslic3r/Format/SL1.hpp
src/libslic3r/Format/SL1.cpp