Prusa Slicer: Slic3r::anonymous_namespace{PresetUpdater.cpp} Namespace Reference
Slic3r::anonymous_namespace{PresetUpdater.cpp} Namespace Reference
Functions
void copy_file_fix (const fs::path &source, const fs::path &target)
std::string escape_string_url (const std::string &unescaped)
Function Documentation
copy_file_fix()
void Slic3r::anonymous_namespace{PresetUpdater.cpp}::copy_file_fix (const fs::path & source, const fs::path & target)
{
  BOOST_LOG_TRIVIAL(debug) << format("PresetUpdater: Copying %1% -> %2%", source, target);
  std::string error_message;
  CopyFileResult cfr = copy_file(source.string(), target.string(), error_message, false);
  if (cfr != CopyFileResult::SUCCESS) {
    BOOST_LOG_TRIVIAL(error) << "Copying failed(" << cfr << "): " << error_message;
    throw Slic3r::CriticalException(GUI::format(
        _L("Copying of file %1% to %2% failed: %3%"),
        source, target, error_message));
  }
  // Permissions should be copied from the source file by copy_file(). We are not sure about the source
  // permissions, let's rewrite them with 644.
  static constexpr const auto perms = fs::owner_read | fs::owner_write | fs::group_read | fs::others_read;
  fs::permissions(target, perms);
}
References _L, Slic3r::copy_file(), copy_file_fix(), error, Slic3r::format(), Slic3r::GUI::format(), and Slic3r::SUCCESS.
Referenced by copy_file_fix().
escape_string_url()
std::string Slic3r::anonymous_namespace{PresetUpdater.cpp}::escape_string_url (const std::string & unescaped)
{
  std::string ret_val;
  CURL* curl = curl_easy_init();
  if (curl) {
    char* decoded = curl_easy_escape(curl, unescaped.c_str(), unescaped.size());
    if (decoded) {
      ret_val = std::string(decoded);
      curl_free(decoded);
    }
    curl_easy_cleanup(curl);
  }
  return ret_val;
}
References escape_string_url().
Referenced by escape_string_url().