var _support_point_8hpp =
[
    [ "Slic3r::sla::SupportPoint", "d7/d60/struct_slic3r_1_1sla_1_1_support_point.html", "d7/d60/struct_slic3r_1_1sla_1_1_support_point" ],
    [ "SupportPoints", "d2/dfe/_support_point_8hpp.html#ad186b75e6113f8133d80c5a08a08350a", null ],
    [ "PointsStatus", "d2/dfe/_support_point_8hpp.html#aabfc04e91c82abd11e4e85fe93384436", [
      [ "NoPoints", "d2/dfe/_support_point_8hpp.html#aabfc04e91c82abd11e4e85fe93384436a798d6040a2d646d97e67435dac1a4a59", null ],
      [ "Generating", "d2/dfe/_support_point_8hpp.html#aabfc04e91c82abd11e4e85fe93384436a7af17d92a087795e9d952fe34a6938ad", null ],
      [ "AutoGenerated", "d2/dfe/_support_point_8hpp.html#aabfc04e91c82abd11e4e85fe93384436ad5811d305c98b3ecc1c66f2ca6e1b959", null ],
      [ "UserModified", "d2/dfe/_support_point_8hpp.html#aabfc04e91c82abd11e4e85fe93384436abd32736cdf292ace9e2ed7496f9ea10d", null ]
    ] ],
    [ "transformed_support_points", "d2/dfe/_support_point_8hpp.html#a063dcd119956d9de71e4a7e7f105ebeb", null ]
];