Prusa Slicer: Slic3r::GUI::GLGizmosManager::Layout Struct Reference
Slic3r::GUI::GLGizmosManager::Layout Struct Reference
Public Member Functions
float stride_y () const
float scaled_icons_size () const
float scaled_border () const
float scaled_gap_y () const
float scaled_stride_y () const
Public Attributes
float scale { 1.0f }
float icons_size { Default_Icons_Size }
float border { 5.0f }
float gap_y { 5.0f }
Detailed Description
Member Function Documentation
scaled_border()
float Slic3r::GUI::GLGizmosManager::Layout::scaled_border () const inline
{ return scale * border; }
References border, and scale.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmosManager::get_gizmo_from_mouse(), Slic3r::GUI::GLGizmosManager::get_scaled_total_width(), and Slic3r::GUI::GLGizmosManager::render_arrow().
scaled_gap_y()
float Slic3r::GUI::GLGizmosManager::Layout::scaled_gap_y () const inline
{ return scale * gap_y; }
References gap_y, and scale.
scaled_icons_size()
float Slic3r::GUI::GLGizmosManager::Layout::scaled_icons_size () const inline
{ return scale * icons_size; }
References icons_size, and scale.
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmosManager::generate_icons_texture(), Slic3r::GUI::GLGizmosManager::get_gizmo_from_mouse(), Slic3r::GUI::GLGizmosManager::get_scaled_total_width(), and Slic3r::GUI::GLGizmosManager::render_arrow().
scaled_stride_y()
float Slic3r::GUI::GLGizmosManager::Layout::scaled_stride_y () const inline
{ return scale * stride_y(); }
References scale, and stride_y().
Referenced by Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmosManager::get_gizmo_from_mouse(), and Slic3r::GUI::GLGizmosManager::render_arrow().
stride_y()
float Slic3r::GUI::GLGizmosManager::Layout::stride_y () const inline
{ return icons_size + gap_y;}
References gap_y, and icons_size.
Referenced by Slic3r::GUI::GLGizmosManager::get_scaled_total_height(), and scaled_stride_y().
Member Data Documentation
border
float Slic3r::GUI::GLGizmosManager::Layout::border { 5.0f }
Referenced by Slic3r::GUI::GLGizmosManager::get_scaled_total_height(), and scaled_border().
gap_y
float Slic3r::GUI::GLGizmosManager::Layout::gap_y { 5.0f }
Referenced by Slic3r::GUI::GLGizmosManager::get_scaled_total_height(), scaled_gap_y(), and stride_y().
icons_size
float Slic3r::GUI::GLGizmosManager::Layout::icons_size { Default_Icons_Size }
Referenced by scaled_icons_size(), Slic3r::GUI::GLGizmosManager::set_overlay_icon_size(), and stride_y().
scale
float Slic3r::GUI::GLGizmosManager::Layout::scale { 1.0f }
Referenced by Slic3r::GUI::GLGizmosManager::get_scaled_total_height(), Slic3r::GUI::GLGizmosManager::render_arrow(), scaled_border(), scaled_gap_y(), scaled_icons_size(), scaled_stride_y(), and Slic3r::GUI::GLGizmosManager::set_overlay_scale().
The documentation for this struct was generated from the following file:
src/slic3r/GUI/Gizmos/GLGizmosManager.hpp