Prusa Slicer: Eigen::internal::linspaced_op_impl< Scalar, Packet, false > Struct Template Reference
Eigen::internal::linspaced_op_impl< Scalar, Packet, false > Struct Template Reference
#include <src/eigen/Eigen/src/Core/functors/NullaryFunctors.h>
Public Member Functions
linspaced_op_impl (const Scalar &low, const Scalar &high, Index num_steps)
template<typename IndexType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar operator() (IndexType i) const
template<typename IndexType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Packet packetOp (IndexType i) const
Public Attributes
const Scalar m_low
const Scalar m_high
const Index m_size1
const Scalar m_step
const bool m_flip
Detailed Description
template<typename Scalar, typename Packet>
struct Eigen::internal::linspaced_op_impl< Scalar, Packet, false >
Constructor & Destructor Documentation
linspaced_op_impl()
template<typename Scalar , typename Packet > Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::linspaced_op_impl (const Scalar & low, const Scalar & high, Index num_steps) inline
                                                                            :
    m_low(low), m_high(high), m_size1(num_steps==1 ? 1 : num_steps-1), m_step(num_steps==1 ? Scalar() : (high-low)/Scalar(num_steps-1)),
    m_flip(numext::abs(high)<numext::abs(low))
  {}
Member Function Documentation
operator()()
template<typename Scalar , typename Packet > template<typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::operator() (IndexType i) const inline
{
    typedef typename NumTraits<Scalar>::Real RealScalar;
    if(m_flip)
      return (i==0)? m_low : (m_high - RealScalar(m_size1-i)*m_step);
    else
      return (i==m_size1)? m_high : (m_low + RealScalar(i)*m_step);
  }
packetOp()
template<typename Scalar , typename Packet > template<typename IndexType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Packet Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::packetOp (IndexType i) const inline
  {
    // Principle:
    // [low, ..., low] + ( [step, ..., step] * ( [i, ..., i] + [0, ..., size] ) )
    if(m_flip)
    {
      Packet pi = plset<Packet>(Scalar(i-m_size1));
      Packet res = padd(pset1<Packet>(m_high), pmul(pset1<Packet>(m_step), pi));
      if(i==0)
        res = pinsertfirst(res, m_low);
      return res;
    }
    else
    {
      Packet pi = plset<Packet>(Scalar(i));
      Packet res = padd(pset1<Packet>(m_low), pmul(pset1<Packet>(m_step), pi));
      if(i==m_size1-unpacket_traits<Packet>::size+1)
        res = pinsertlast(res, m_high);
      return res;
    }
  }
References Eigen::internal::padd(), Eigen::internal::pinsertfirst(), Eigen::internal::pinsertlast(), and Eigen::internal::pmul().
Member Data Documentation
m_flip
template<typename Scalar , typename Packet > const bool Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::m_flip
m_high
template<typename Scalar , typename Packet > const Scalar Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::m_high
m_low
template<typename Scalar , typename Packet > const Scalar Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::m_low
m_size1
template<typename Scalar , typename Packet > const Index Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::m_size1
m_step
template<typename Scalar , typename Packet > const Scalar Eigen::internal::linspaced_op_impl< Scalar, Packet, false >::m_step
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/Core/functors/NullaryFunctors.h