Prusa Slicer: Slic3r::GUI::OpenGLManager Class Reference
Slic3r::GUI::OpenGLManager Class Reference
#include <src/slic3r/GUI/OpenGLManager.hpp>
Classes
class GLInfo
Public Types
enum class EFramebufferType : unsigned char { Unknown , Arb , Ext }
Public Member Functions
OpenGLManager ()=default
~OpenGLManager ()
bool init_gl ()
wxGLContext * init_glcontext (wxGLCanvas &canvas)
GLShaderProgram * get_shader (const std::string &shader_name)
GLShaderProgram * get_current_shader ()
Static Public Member Functions
static bool are_compressed_textures_supported ()
static bool can_multisample ()
static bool are_framebuffers_supported ()
static EFramebufferType get_framebuffers_type ()
static wxGLCanvas * create_wxglcanvas (wxWindow &parent)
static const GLInfo & get_gl_info ()
static bool force_power_of_two_textures ()
Private Types
enum class EMultisampleState : unsigned char { Unknown , Enabled , Disabled }
Static Private Member Functions
static void detect_multisample (int *attribList)
Private Attributes
bool m_gl_initialized { false }
wxGLContext * m_context { nullptr }
GLShadersManager m_shaders_manager
Static Private Attributes
static GLInfo s_gl_info
static bool s_compressed_textures_supported = false
static bool s_force_power_of_two_textures = false
static EMultisampleState s_multisample = OpenGLManager::EMultisampleState::Unknown
static EFramebufferType s_framebuffers_type = OpenGLManager::EFramebufferType::Unknown
Detailed Description
Member Enumeration Documentation
EFramebufferType
enum class Slic3r::GUI::OpenGLManager::EFramebufferType : unsigned char strong
Enumerator
Unknown
Arb
Ext
    {
        Unknown,
        Arb,
        Ext
    };
EMultisampleState
enum class Slic3r::GUI::OpenGLManager::EMultisampleState : unsigned char strong private
Enumerator
Unknown
Enabled
Disabled
    {
        Unknown,
        Enabled,
        Disabled
    };
Constructor & Destructor Documentation
OpenGLManager()
Slic3r::GUI::OpenGLManager::OpenGLManager () default
~OpenGLManager()
Slic3r::GUI::OpenGLManager::~OpenGLManager ()
{
    m_shaders_manager.shutdown();
#ifdef __APPLE__
    // This is an ugly hack needed to solve the crash happening when closing the application on OSX 10.9.5 with newer wxWidgets
    // The crash is triggered inside wxGLContext destructor
    if (s_os_info.major != 10 || s_os_info.minor != 9 || s_os_info.micro != 5)
    {
#endif //__APPLE__
        if (m_context != nullptr)
            delete m_context;
#ifdef __APPLE__
    }
#endif //__APPLE__
}
References m_context, m_shaders_manager, and Slic3r::GLShadersManager::shutdown().
Member Function Documentation
are_compressed_textures_supported()
static bool Slic3r::GUI::OpenGLManager::are_compressed_textures_supported () inline static
{ return s_compressed_textures_supported; }
References s_compressed_textures_supported.
Referenced by Slic3r::GUI::Emboss::StyleManager::create_imgui_font(), Slic3r::GUI::ImGuiWrapper::init_font(), Slic3r::GUI::GLTexture::load_from_png(), Slic3r::GUI::GLTexture::load_from_svg(), Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), Slic3r::GUI::GLCanvas3D::render(), and Slic3r::GUI::OpenGLManager::GLInfo::to_string().
are_framebuffers_supported()
static bool Slic3r::GUI::OpenGLManager::are_framebuffers_supported () inline static
{ return (s_framebuffers_type != EFramebufferType::Unknown); }
References s_framebuffers_type, and Unknown.
can_multisample()
static bool Slic3r::GUI::OpenGLManager::can_multisample () inline static
{ return s_multisample == EMultisampleState::Enabled; }
References Enabled, and s_multisample.
Referenced by create_wxglcanvas(), Slic3r::GUI::Preview::init(), and Slic3r::GUI::View3D::init().
create_wxglcanvas()
wxGLCanvas * Slic3r::GUI::OpenGLManager::create_wxglcanvas (wxWindow & parent) static
{
#if ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
    wxGLAttributes attribList;
    attribList.PlatformDefaults().RGBA().DoubleBuffer().MinRGBA(8, 8, 8, 8).Depth(24).SampleBuffers(1).Samplers(4).EndList();
#ifdef __APPLE__
    // on MAC the method RGBA() has no effect
    attribList.SetNeedsARB(true);
#endif // __APPLE__
#else
    int attribList[] = {
        WX_GL_RGBA,
      WX_GL_DOUBLEBUFFER,
      // RGB channels each should be allocated with 8 bit depth. One should almost certainly get these bit depths by default.
        WX_GL_MIN_RED,      8,
        WX_GL_MIN_GREEN,    8,
        WX_GL_MIN_BLUE,     8,
        // Requesting an 8 bit alpha channel. Interestingly, the NVIDIA drivers would most likely work with some alpha plane, but glReadPixels would not return
        // the alpha channel on NVIDIA if not requested when the GL context is created.
        WX_GL_MIN_ALPHA,    8,
      WX_GL_DEPTH_SIZE,     24,
      WX_GL_SAMPLE_BUFFERS,   GL_TRUE,
      WX_GL_SAMPLES,      4,
      0
    };
#endif // ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
    if (s_multisample == EMultisampleState::Unknown) {
        detect_multisample(attribList);
//        // debug output
//        std::cout << "Multisample " << (can_multisample() ? "enabled" : "disabled") << std::endl;
    }
    if (!can_multisample())
#if ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
    {
        attribList.Reset();
        attribList.PlatformDefaults().RGBA().DoubleBuffer().MinRGBA(8, 8, 8, 8).Depth(24).EndList();
#ifdef __APPLE__
        // on MAC the method RGBA() has no effect
        attribList.SetNeedsARB(true);
#endif // __APPLE__
    }
    return new wxGLCanvas(&parent, attribList, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxWANTS_CHARS);
#else
        attribList[12] = 0;
    return new wxGLCanvas(&parent, wxID_ANY, attribList, wxDefaultPosition, wxDefaultSize, wxWANTS_CHARS);
#endif // ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
}
References can_multisample(), detect_multisample(), GL_TRUE, s_multisample, and Unknown.
Referenced by Slic3r::GUI::Preview::init(), and Slic3r::GUI::View3D::init().
detect_multisample()
void Slic3r::GUI::OpenGLManager::detect_multisample (int * attribList) static private
{
    int wxVersion = wxMAJOR_VERSION * 10000 + wxMINOR_VERSION * 100 + wxRELEASE_NUMBER;
    bool enable_multisample = wxVersion >= 30003;
    s_multisample =
        enable_multisample &&
        // Disable multi-sampling on ChromeOS, as the OpenGL virtualization swaps Red/Blue channels with multi-sampling enabled,
        // at least on some platforms.
        platform_flavor() != PlatformFlavor::LinuxOnChromium &&
        wxGLCanvas::IsDisplaySupported(attribList)
        ? EMultisampleState::Enabled : EMultisampleState::Disabled;
    // Alternative method: it was working on previous version of wxWidgets but not with the latest, at least on Windows
    // s_multisample = enable_multisample && wxGLCanvas::IsExtensionSupported("WGL_ARB_multisample");
}
References Disabled, Enabled, Slic3r::LinuxOnChromium, Slic3r::platform_flavor(), and s_multisample.
Referenced by create_wxglcanvas().
force_power_of_two_textures()
static bool Slic3r::GUI::OpenGLManager::force_power_of_two_textures () inline static
{ return s_force_power_of_two_textures; }
References s_force_power_of_two_textures.
Referenced by Slic3r::GUI::GLTexture::load_from_png(), and Slic3r::GUI::GLTexture::load_from_svg().
get_current_shader()
GLShaderProgram * Slic3r::GUI::OpenGLManager::get_current_shader () inline
{ return m_shaders_manager.get_current_shader(); }
References Slic3r::GLShadersManager::get_current_shader(), and m_shaders_manager.
Referenced by Slic3r::GUI::GUI_App::get_current_shader().
get_framebuffers_type()
static EFramebufferType Slic3r::GUI::OpenGLManager::get_framebuffers_type () inline static
{ return s_framebuffers_type; }
References s_framebuffers_type.
Referenced by Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), and Slic3r::GUI::GLCanvas3D::render_thumbnail().
get_gl_info()
static const GLInfo & Slic3r::GUI::OpenGLManager::get_gl_info () inline static
{ return s_gl_info; }
References s_gl_info.
Referenced by Slic3r::GUI::GLMmSegmentationGizmo3DScene::finalize_vertices(), Slic3r::GUI::generate_system_info_json(), Slic3r::GUI::GUI_App::get_gl_info(), Slic3r::GUI::GLCanvas3D::LayersEditing::init(), Slic3r::GLShadersManager::init(), init_gl(), Slic3r::GUI::GUI_App::is_gl_version_greater_or_equal_to(), Slic3r::GUI::GUI_App::is_glsl_version_greater_or_equal_to(), Slic3r::GUI::GLTexture::load_from_png(), Slic3r::GUI::GLTexture::load_from_svg(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), Slic3r::GLVolume::NonManifoldEdges::render(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::render(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLModel::render(), Slic3r::GLVolumeCollection::render(), Slic3r::GUI::GLMmSegmentationGizmo3DScene::render(), Slic3r::GUI::Selection::render_bounding_box(), Slic3r::GUI::Bed3D::render_contour(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::Bed3D::render_default(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::ImGuiWrapper::render_draw_data(), Slic3r::GUI::GLModel::render_instanced(), Slic3r::GUI::GLGizmoCut3D::render_line(), Slic3r::GUI::TriangleSelectorGUI::render_paint_contour(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::GLGizmoCut3D::render_rotation_snapping(), Slic3r::GUI::Bed3D::render_texture(), Slic3r::GUI::GCodeViewer::render_toolpaths(), and Slic3r::GUI::GLModel::send_to_gpu().
get_shader()
GLShaderProgram * Slic3r::GUI::OpenGLManager::get_shader (const std::string & shader_name) inline
{ return m_shaders_manager.get_shader(shader_name); }
References Slic3r::GLShadersManager::get_shader(), and m_shaders_manager.
Referenced by Slic3r::GUI::GUI_App::get_shader().
init_gl()
bool Slic3r::GUI::OpenGLManager::init_gl ()
{
    if (!m_gl_initialized) {
#if ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
        glewExperimental = true;
#endif // ENABLE_GL_CORE_PROFILE || ENABLE_OPENGL_ES
        GLenum err = glewInit();
        if (err != GLEW_OK) {
            BOOST_LOG_TRIVIAL(error) << "Unable to init glew library: " << glewGetErrorString(err);
            return false;
        }
#if ENABLE_GL_CORE_PROFILE
        do {
            // glewInit() generates an OpenGL GL_INVALID_ENUM error
            err = ::glGetError();
        } while (err != GL_NO_ERROR);
#endif // ENABLE_GL_CORE_PROFILE
        m_gl_initialized = true;
        if (GLEW_EXT_texture_compression_s3tc)
            s_compressed_textures_supported = true;
        else
            s_compressed_textures_supported = false;
        if (GLEW_ARB_framebuffer_object)
            s_framebuffers_type = EFramebufferType::Arb;
        else if (GLEW_EXT_framebuffer_object)
            s_framebuffers_type = EFramebufferType::Ext;
        else
            s_framebuffers_type = EFramebufferType::Unknown;
#if ENABLE_OPENGL_ES
        bool valid_version = s_gl_info.is_version_greater_or_equal_to(2, 0);
#elif ENABLE_GL_CORE_PROFILE
        bool valid_version = s_gl_info.is_core_profile() ? s_gl_info.is_version_greater_or_equal_to(3, 2) : s_gl_info.is_version_greater_or_equal_to(2, 0);
#else
        bool valid_version = s_gl_info.is_version_greater_or_equal_to(2, 0);
#endif // ENABLE_OPENGL_ES
        if (!valid_version) {
            // Complain about the OpenGL version.
            wxString message = format_wxstr(
#if ENABLE_OPENGL_ES
                _L("PrusaSlicer requires OpenGL ES 2.0 capable graphics driver to run correctly, \n"
                    "while OpenGL version %s, render %s, vendor %s was detected."), s_gl_info.get_version_string(), s_gl_info.get_renderer(), s_gl_info.get_vendor());
#elif ENABLE_GL_CORE_PROFILE
                _L("PrusaSlicer requires OpenGL %s capable graphics driver to run correctly, \n"
                    "while OpenGL version %s, render %s, vendor %s was detected."), (s_gl_info.is_core_profile() ? "3.3" : "2.0"), s_gl_info.get_version_string(), s_gl_info.get_renderer(), s_gl_info.get_vendor());
#else
                _L("PrusaSlicer requires OpenGL 2.0 capable graphics driver to run correctly, \n"
                    "while OpenGL version %s, render %s, vendor %s was detected."), s_gl_info.get_version_string(), s_gl_info.get_renderer(), s_gl_info.get_vendor());
#endif // ENABLE_OPENGL_ES
            message += "\n";
          message += _L("You may need to update your graphics card driver.");
#ifdef _WIN32
            message += "\n";
            message += _L("As a workaround, you may run PrusaSlicer with a software rendered 3D graphics by running prusa-slicer.exe with the --sw-renderer parameter.");
#endif
          wxMessageBox(message, wxString("PrusaSlicer - ") + _L("Unsupported OpenGL version"), wxOK | wxICON_ERROR);
        }
        if (valid_version) {
            // load shaders
            auto [result, error] = m_shaders_manager.init();
            if (!result) {
                wxString message = format_wxstr(_L("Unable to load the following shaders:\n%s"), error);
                wxMessageBox(message, wxString("PrusaSlicer - ") + _L("Error loading shaders"), wxOK | wxICON_ERROR);
            }
#if ENABLE_OPENGL_DEBUG_OPTION
            if (m_debug_enabled && GLEW_KHR_debug) {
                ::glEnable(GL_DEBUG_OUTPUT);
                ::glEnable(GL_DEBUG_OUTPUT_SYNCHRONOUS);
                ::glDebugMessageCallback(CustomGLDebugOutput, nullptr);
                ::glDebugMessageControl(GL_DONT_CARE, GL_DONT_CARE, GL_DONT_CARE, 0, nullptr, GL_TRUE);
            }
#endif // ENABLE_OPENGL_DEBUG_OPTION
        }
#ifdef _WIN32
        // Since AMD driver version 22.7.1, there is probably some bug in the driver that causes the issue with the missing
        // texture of the bed (see: https://github.com/prusa3d/PrusaSlicer/issues/8417).
        // It seems that this issue only triggers when mipmaps are generated manually
        // (combined with a texture compression) with texture size not being power of two.
        // When mipmaps are generated through OpenGL function glGenerateMipmap() the driver works fine,
        // but the mipmap generation is quite slow on some machines.
        // There is no an easy way to detect the driver version without using Win32 API because the strings returned by OpenGL
        // have no standardized format, only some of them contain the driver version.
        // Until we do not know that driver will be fixed (if ever) we force the use of power of two textures on all cards
        // 1) containing the string 'Radeon' in the string returned by glGetString(GL_RENDERER)
        // 2) containing the string 'Custom' in the string returned by glGetString(GL_RENDERER)
        const auto& gl_info = OpenGLManager::get_gl_info();
        if (boost::contains(gl_info.get_vendor(), "ATI Technologies Inc.") &&
           (boost::contains(gl_info.get_renderer(), "Radeon") ||
            boost::contains(gl_info.get_renderer(), "Custom")))
            s_force_power_of_two_textures = true;
#endif // _WIN32
    }
    return true;
}
References _L, Arb, ENABLE_OPENGL_ES, error, Ext, Slic3r::GUI::format_wxstr(), get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::get_renderer(), Slic3r::GUI::OpenGLManager::GLInfo::get_vendor(), Slic3r::GUI::OpenGLManager::GLInfo::get_version_string(), GL_TRUE, Slic3r::GLShadersManager::init(), Slic3r::GUI::OpenGLManager::GLInfo::is_core_profile(), Slic3r::GUI::OpenGLManager::GLInfo::is_version_greater_or_equal_to(), m_gl_initialized, m_shaders_manager, s_compressed_textures_supported, s_force_power_of_two_textures, s_framebuffers_type, s_gl_info, and Unknown.
Referenced by Slic3r::GUI::GUI_App::init_opengl().
init_glcontext()
wxGLContext * Slic3r::GUI::OpenGLManager::init_glcontext (wxGLCanvas & canvas)
{
    if (m_context == nullptr) {
#if ENABLE_OPENGL_ES
        wxGLContextAttrs attrs;
        attrs.PlatformDefaults().ES2().MajorVersion(2).EndList();
        m_context = new wxGLContext(&canvas, nullptr, &attrs);
#elif ENABLE_GL_CORE_PROFILE
#if ENABLE_OPENGL_DEBUG_OPTION
        m_debug_enabled = enable_debug;
#endif // ENABLE_OPENGL_DEBUG_OPTION
        const int gl_major = required_opengl_version.first;
        const int gl_minor = required_opengl_version.second;
        const bool supports_core_profile = (gl_major < 3) ? false : (gl_major > 3) ? true : gl_minor >= 2;
        if (gl_major == 0) {
            // search for highest supported core profile version
            // disable wxWidgets logging to avoid showing the log dialog in case the following code fails generating a valid gl context
            wxLogNull logNo;
            for (auto v = OpenGLVersions::core.rbegin(); v != OpenGLVersions::core.rend(); ++v) {
                wxGLContextAttrs attrs;
#if ENABLE_OPENGL_DEBUG_OPTION
                attrs.PlatformDefaults().MajorVersion(v->first).MinorVersion(v->second).CoreProfile().ForwardCompatible();
                if (m_debug_enabled)
                    attrs.DebugCtx();
                attrs.EndList();
#else
                attrs.PlatformDefaults().MajorVersion(gl_major).MinorVersion(gl_minor).CoreProfile().ForwardCompatible().EndList();
#endif // ENABLE_OPENGL_DEBUG_OPTION
                m_context = new wxGLContext(&canvas, nullptr, &attrs);
                if (m_context->IsOK()) {
                    s_gl_info.set_core_profile(true);
                    break;
                }
                else {
                    delete m_context;
                    m_context = nullptr;
                }
            }
        }
        if (m_context == nullptr) {
            // search for requested core profile version
            if (supports_core_profile) {
                // disable wxWidgets logging to avoid showing the log dialog in case the following code fails generating a valid gl context
                wxLogNull logNo;
                wxGLContextAttrs attrs;
#if ENABLE_OPENGL_DEBUG_OPTION
                attrs.PlatformDefaults().MajorVersion(gl_major).MinorVersion(gl_minor).CoreProfile().ForwardCompatible();
                if (m_debug_enabled)
                    attrs.DebugCtx();
                attrs.EndList();
#else
                attrs.PlatformDefaults().MajorVersion(gl_major).MinorVersion(gl_minor).CoreProfile().ForwardCompatible().EndList();
#endif // ENABLE_OPENGL_DEBUG_OPTION
                m_context = new wxGLContext(&canvas, nullptr, &attrs);
                if (!m_context->IsOK()) {
                    BOOST_LOG_TRIVIAL(error) << "Unable to create context for required OpenGL " << gl_major << "." << gl_minor;
                    delete m_context;
                    m_context = nullptr;
                }
                else
                    s_gl_info.set_core_profile(true);
            }
        }
#if ENABLE_OPENGL_DEBUG_OPTION
        if (m_context == nullptr) {
            wxGLContextAttrs attrs;
            attrs.PlatformDefaults();
            if (m_debug_enabled)
                attrs.DebugCtx();
            attrs.EndList();
            // if no valid context was created use the default one
            m_context = new wxGLContext(&canvas, nullptr, &attrs);
        }
#else
        if (m_context == nullptr)
            // if no valid context was created use the default one
            m_context = new wxGLContext(&canvas);
#endif // ENABLE_OPENGL_DEBUG_OPTION
#else
        m_context = new wxGLContext(&canvas);
#endif // ENABLE_OPENGL_ES
#ifdef __APPLE__
        // Part of hack to remove crash when closing the application on OSX 10.9.5 when building against newer wxWidgets
        s_os_info.major = wxPlatformInfo::Get().GetOSMajorVersion();
        s_os_info.minor = wxPlatformInfo::Get().GetOSMinorVersion();
        s_os_info.micro = wxPlatformInfo::Get().GetOSMicroVersion();
#endif //__APPLE__
    }
    return m_context;
}
References Slic3r::GUI::OpenGLVersions::core, error, m_context, s_gl_info, and Slic3r::GUI::OpenGLManager::GLInfo::set_core_profile().
Referenced by Slic3r::GUI::GUI_App::init_glcontext().
Member Data Documentation
m_context
wxGLContext* Slic3r::GUI::OpenGLManager::m_context { nullptr } private
Referenced by ~OpenGLManager(), and init_glcontext().
m_gl_initialized
bool Slic3r::GUI::OpenGLManager::m_gl_initialized { false } private
Referenced by init_gl().
m_shaders_manager
GLShadersManager Slic3r::GUI::OpenGLManager::m_shaders_manager private
Referenced by ~OpenGLManager(), get_current_shader(), get_shader(), and init_gl().
s_compressed_textures_supported
bool Slic3r::GUI::OpenGLManager::s_compressed_textures_supported = false static private
Referenced by are_compressed_textures_supported(), and init_gl().
s_force_power_of_two_textures
bool Slic3r::GUI::OpenGLManager::s_force_power_of_two_textures = false static private
Referenced by force_power_of_two_textures(), and init_gl().
s_framebuffers_type
OpenGLManager::EFramebufferType Slic3r::GUI::OpenGLManager::s_framebuffers_type = OpenGLManager::EFramebufferType::Unknown static private
Referenced by are_framebuffers_supported(), get_framebuffers_type(), and init_gl().
s_gl_info
OpenGLManager::GLInfo Slic3r::GUI::OpenGLManager::s_gl_info static private
Referenced by get_gl_info(), init_gl(), and init_glcontext().
s_multisample
OpenGLManager::EMultisampleState Slic3r::GUI::OpenGLManager::s_multisample = OpenGLManager::EMultisampleState::Unknown static private
Referenced by can_multisample(), create_wxglcanvas(), and detect_multisample().
The documentation for this class was generated from the following files:
src/slic3r/GUI/OpenGLManager.hpp
src/slic3r/GUI/OpenGLManager.cpp