Prusa Slicer: Slic3r::GUI::PageTemperatures Struct Reference
Slic3r::GUI::PageTemperatures Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
PageTemperatures (ConfigWizard *parent)
virtual void apply_custom_config (DynamicPrintConfig &config)
template<class T >
T * append (T *thing, int proportion=0, int flag=wxEXPAND|wxTOP|wxBOTTOM, int border=10)
wxStaticText * append_text (wxString text)
void append_spacer (int space)
ConfigWizard::priv * wizard_p () const
virtual void set_run_reason (ConfigWizard::RunReason run_reason)
virtual void on_activate ()
Public Attributes
wxSpinCtrlDouble * spin_extr
wxSpinCtrlDouble * spin_bed
ConfigWizard * parent
const wxString shortname
wxBoxSizer * content
const unsigned indent
Detailed Description
Constructor & Destructor Documentation
PageTemperatures()
Slic3r::GUI::PageTemperatures::PageTemperatures (ConfigWizard * parent)
    : ConfigWizardPage(parent, _L("Nozzle and Bed Temperatures"), _L("Temperatures"), 1)
    , spin_extr(new SpinCtrlDouble(this))
    , spin_bed (new SpinCtrlDouble(this))
{
    spin_extr->SetIncrement(5.0);
    const auto &def_extr = *print_config_def.get("temperature");
    spin_extr->SetRange(def_extr.min, def_extr.max);
    auto *default_extr = def_extr.get_default_value<ConfigOptionInts>();
    spin_extr->SetValue(default_extr != nullptr && default_extr->size() > 0 ? default_extr->get_at(0) : 200);
    spin_bed->SetIncrement(5.0);
    const auto &def_bed = *print_config_def.get("bed_temperature");
    spin_bed->SetRange(def_bed.min, def_bed.max);
    auto *default_bed = def_bed.get_default_value<ConfigOptionInts>();
    spin_bed->SetValue(default_bed != nullptr && default_bed->size() > 0 ? default_bed->get_at(0) : 0);
    append_text(_L("Enter the temperature needed for extruding your filament."));
    append_text(_L("A rule of thumb is 160 to 230 °C for PLA, and 215 to 250 °C for ABS."));
    auto *sizer_extr = new wxFlexGridSizer(3, 5, 5);
    auto *text_extr = new wxStaticText(this, wxID_ANY, _L("Extrusion Temperature:"));
    auto *unit_extr = new wxStaticText(this, wxID_ANY, _L("°C"));
    sizer_extr->AddGrowableCol(0, 1);
    sizer_extr->Add(text_extr, 0, wxALIGN_CENTRE_VERTICAL);
    sizer_extr->Add(spin_extr);
    sizer_extr->Add(unit_extr, 0, wxALIGN_CENTRE_VERTICAL);
    append(sizer_extr);
    append_spacer(VERTICAL_SPACING);
    append_text(_L("Enter the bed temperature needed for getting your filament to stick to your heated bed."));
    append_text(_L("A rule of thumb is 60 °C for PLA and 110 °C for ABS. Leave zero if you have no heated bed."));
    auto *sizer_bed = new wxFlexGridSizer(3, 5, 5);
    auto *text_bed = new wxStaticText(this, wxID_ANY, _L("Bed Temperature") + ":");
    auto *unit_bed = new wxStaticText(this, wxID_ANY, _L("°C"));
    sizer_bed->AddGrowableCol(0, 1);
    sizer_bed->Add(text_bed, 0, wxALIGN_CENTRE_VERTICAL);
    sizer_bed->Add(spin_bed);
    sizer_bed->Add(unit_bed, 0, wxALIGN_CENTRE_VERTICAL);
    append(sizer_bed);
}
References _L, Slic3r::GUI::ConfigWizardPage::append(), Slic3r::GUI::ConfigWizardPage::append_spacer(), Slic3r::GUI::ConfigWizardPage::append_text(), Slic3r::ConfigDef::get(), Slic3r::print_config_def, spin_bed, spin_extr, and Slic3r::GUI::VERTICAL_SPACING.
Member Function Documentation
append()
template<class T > T * Slic3r::GUI::ConfigWizardPage::append (T * thing, int proportion = 0, int flag = wxEXPAND|wxTOP|wxBOTTOM, int border = 10) inline inherited
    {
        content->Add(thing, proportion, flag, border);
        return thing;
    }
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), Slic3r::GUI::PageVendors::PageVendors(), and Slic3r::GUI::ConfigWizardPage::append_text().
append_spacer()
void Slic3r::GUI::ConfigWizardPage::append_spacer (int space) inherited
{
    // FIXME: scaling
    content->AddSpacer(space);
}
References Slic3r::GUI::ConfigWizardPage::content.
Referenced by Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageMaterials::PageMaterials(), PageTemperatures(), and Slic3r::GUI::PageUpdate::PageUpdate().
append_text()
wxStaticText * Slic3r::GUI::ConfigWizardPage::append_text (wxString text) inherited
{
    auto *widget = new wxStaticText(this, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    widget->Wrap(WRAP_WIDTH);
    widget->SetMinSize(wxSize(WRAP_WIDTH, -1));
    append(widget);
    return widget;
}
References Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::WRAP_WIDTH.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageBuildVolume::PageBuildVolume(), Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageDownloader::PageDownloader(), Slic3r::GUI::PageFirmware::PageFirmware(), Slic3r::GUI::PageMode::PageMode(), Slic3r::GUI::PageReloadFromDisk::PageReloadFromDisk(), PageTemperatures(), Slic3r::GUI::PageUpdate::PageUpdate(), and Slic3r::GUI::PageVendors::PageVendors().
apply_custom_config()
void Slic3r::GUI::PageTemperatures::apply_custom_config (DynamicPrintConfig & config) virtual
Reimplemented from Slic3r::GUI::ConfigWizardPage.
{
    auto *opt_extr = new ConfigOptionInts(1, spin_extr->GetValue());
    config.set_key_value("temperature", opt_extr);
    auto *opt_extr1st = new ConfigOptionInts(1, spin_extr->GetValue());
    config.set_key_value("first_layer_temperature", opt_extr1st);
    auto *opt_bed = new ConfigOptionInts(1, spin_bed->GetValue());
    config.set_key_value("bed_temperature", opt_bed);
    auto *opt_bed1st = new ConfigOptionInts(1, spin_bed->GetValue());
    config.set_key_value("first_layer_bed_temperature", opt_bed1st);
}
References Slic3r::DynamicConfig::set_key_value(), spin_bed, and spin_extr.
on_activate()
virtual void Slic3r::GUI::ConfigWizardPage::on_activate () inline virtual inherited
Reimplemented in Slic3r::GUI::PageMaterials.
{}
Referenced by Slic3r::GUI::PageMode::PageMode().
set_run_reason()
virtual void Slic3r::GUI::ConfigWizardPage::set_run_reason (ConfigWizard::RunReason run_reason) inline virtual inherited
Reimplemented in Slic3r::GUI::PageWelcome, and Slic3r::GUI::PagePrinters.
{}
wizard_p()
ConfigWizard::priv * Slic3r::GUI::ConfigWizardPage::wizard_p () const inline inherited
{ return parent->p.get(); }
References Slic3r::GUI::ConfigWizard::p, and Slic3r::GUI::ConfigWizardPage::parent.
Referenced by Slic3r::GUI::PageBedShape::PageBedShape(), Slic3r::GUI::PageCustom::PageCustom(), Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::PageVendors::PageVendors(), Slic3r::GUI::PageMaterials::on_activate(), Slic3r::GUI::PageMaterials::select_material(), and Slic3r::GUI::PageMaterials::update_lists().
Member Data Documentation
content
wxBoxSizer* Slic3r::GUI::ConfigWizardPage::content inherited
Referenced by Slic3r::GUI::ConfigWizardPage::ConfigWizardPage(), Slic3r::GUI::ConfigWizardPage::append(), and Slic3r::GUI::ConfigWizardPage::append_spacer().
indent
const unsigned Slic3r::GUI::ConfigWizardPage::indent inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page().
parent
ConfigWizard* Slic3r::GUI::ConfigWizardPage::parent inherited
Referenced by Slic3r::GUI::PageMaterials::PageMaterials(), and Slic3r::GUI::ConfigWizardPage::wizard_p().
shortname
const wxString Slic3r::GUI::ConfigWizardPage::shortname inherited
Referenced by Slic3r::GUI::ConfigWizardIndex::add_page(), and Slic3r::GUI::ConfigWizard::priv::add_page().
spin_bed
wxSpinCtrlDouble* Slic3r::GUI::PageTemperatures::spin_bed
Referenced by PageTemperatures(), and apply_custom_config().
spin_extr
wxSpinCtrlDouble* Slic3r::GUI::PageTemperatures::spin_extr
Referenced by PageTemperatures(), and apply_custom_config().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp