Prusa Slicer: Slic3r::GUI::GCodeViewer::TBuffer Struct Reference
Slic3r::GUI::GCodeViewer::TBuffer Struct Reference
Classes
struct Model
Public Types
enum class ERenderPrimitiveType : unsigned char { Line , Triangle , InstancedModel , BatchedModel }
Public Member Functions
void reset ()
void add_path (const GCodeProcessorResult::MoveVertex &move, unsigned int b_id, size_t i_id, size_t s_id)
unsigned int max_vertices_per_segment () const
size_t max_vertices_per_segment_size_floats () const
size_t max_vertices_per_segment_size_bytes () const
unsigned int indices_per_segment () const
size_t indices_per_segment_size_bytes () const
unsigned int max_indices_per_segment () const
size_t max_indices_per_segment_size_bytes () const
bool has_data () const
Public Attributes
ERenderPrimitiveType render_primitive_type
VBuffer vertices
std::vector< IBuffer > indices
Model model
std::string shader
std::vector< Path > paths
std::vector< RenderPath > render_paths
bool visible { false }
Detailed Description
Member Enumeration Documentation
ERenderPrimitiveType
enum class Slic3r::GUI::GCodeViewer::TBuffer::ERenderPrimitiveType : unsigned char strong
Enumerator
Line
Triangle
InstancedModel
BatchedModel
        {
            Line,
            Triangle,
            InstancedModel,
            BatchedModel
        };
Member Function Documentation
add_path()
void Slic3r::GUI::GCodeViewer::TBuffer::add_path (const GCodeProcessorResult::MoveVertex & move, unsigned int b_id, size_t i_id, size_t s_id)
{
    Path::Endpoint endpoint = { b_id, i_id, s_id, move.position };
    // use rounding to reduce the number of generated paths
    paths.push_back({ move.type, move.extrusion_role, move.delta_extruder,
        round_to_bin(move.height), round_to_bin(move.width),
        move.feedrate, move.fan_speed, move.temperature,
        move.volumetric_rate(), move.extruder_id, move.cp_color_id, { { endpoint, endpoint } } });
}
References Slic3r::GCodeProcessorResult::MoveVertex::cp_color_id, Slic3r::GCodeProcessorResult::MoveVertex::delta_extruder, Slic3r::GCodeProcessorResult::MoveVertex::extruder_id, Slic3r::GCodeProcessorResult::MoveVertex::extrusion_role, Slic3r::GCodeProcessorResult::MoveVertex::fan_speed, Slic3r::GCodeProcessorResult::MoveVertex::feedrate, Slic3r::GCodeProcessorResult::MoveVertex::height, Slic3r::GCodeProcessorResult::MoveVertex::position, Slic3r::GUI::round_to_bin(), Slic3r::GCodeProcessorResult::MoveVertex::temperature, Slic3r::GCodeProcessorResult::MoveVertex::type, Slic3r::GCodeProcessorResult::MoveVertex::volumetric_rate(), and Slic3r::GCodeProcessorResult::MoveVertex::width.
has_data()
bool Slic3r::GUI::GCodeViewer::TBuffer::has_data () const inline
{
            switch (render_primitive_type)
            {
            case ERenderPrimitiveType::Line:
            case ERenderPrimitiveType::Triangle: {
                return !vertices.vbos.empty() && vertices.vbos.front() != 0 && !indices.empty() && indices.front().ibo != 0;
            }
            case ERenderPrimitiveType::InstancedModel: { return model.model.is_initialized() && !model.instances.buffer.empty(); }
            case ERenderPrimitiveType::BatchedModel: {
                return !model.data.vertices.empty() && !model.data.indices.empty() &&
                    !vertices.vbos.empty() && vertices.vbos.front() != 0 && !indices.empty() && indices.front().ibo != 0;
            }
            default: { return false; }
            }
        }
References BatchedModel, Slic3r::GUI::GCodeViewer::InstanceVBuffer::buffer, Slic3r::GUI::GCodeViewer::TBuffer::Model::data, indices, Slic3r::GUI::GLModel::Geometry::indices, InstancedModel, Slic3r::GUI::GCodeViewer::TBuffer::Model::instances, Slic3r::GUI::GLModel::is_initialized(), Line, Slic3r::GUI::GCodeViewer::TBuffer::Model::model, model, render_primitive_type, Triangle, Slic3r::GUI::GCodeViewer::VBuffer::vbos, vertices, and Slic3r::GUI::GLModel::Geometry::vertices.
Referenced by Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
indices_per_segment()
unsigned int Slic3r::GUI::GCodeViewer::TBuffer::indices_per_segment () const inline
{
            switch (render_primitive_type)
            {
            case ERenderPrimitiveType::Line:     { return 2; }
            case ERenderPrimitiveType::Triangle: { return 30; } // 3 indices x 10 triangles
            default:                             { return 0; }
            }
        }
References Line, render_primitive_type, and Triangle.
Referenced by indices_per_segment_size_bytes(), Slic3r::GUI::GCodeViewer::load_toolpaths(), and Slic3r::GUI::GCodeViewer::refresh_render_paths().
indices_per_segment_size_bytes()
size_t Slic3r::GUI::GCodeViewer::TBuffer::indices_per_segment_size_bytes () const inline
{ return static_cast<size_t>(indices_per_segment() * sizeof(IBufferType)); }
References indices_per_segment().
max_indices_per_segment()
unsigned int Slic3r::GUI::GCodeViewer::TBuffer::max_indices_per_segment () const inline
{
            switch (render_primitive_type)
            {
            case ERenderPrimitiveType::Line:     { return 2; }
            case ERenderPrimitiveType::Triangle: { return 36; } // 3 indices x 12 triangles
            default:                             { return 0; }
            }
        }
References Line, render_primitive_type, and Triangle.
Referenced by max_indices_per_segment_size_bytes().
max_indices_per_segment_size_bytes()
size_t Slic3r::GUI::GCodeViewer::TBuffer::max_indices_per_segment_size_bytes () const inline
{ return max_indices_per_segment() * sizeof(IBufferType); }
References max_indices_per_segment().
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
max_vertices_per_segment()
unsigned int Slic3r::GUI::GCodeViewer::TBuffer::max_vertices_per_segment () const inline
{
            switch (render_primitive_type)
            {
            case ERenderPrimitiveType::Line:     { return 2; }
            case ERenderPrimitiveType::Triangle: { return 8; }
            default:                             { return 0; }
            }
        }
References Line, render_primitive_type, and Triangle.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths(), and max_vertices_per_segment_size_floats().
max_vertices_per_segment_size_bytes()
size_t Slic3r::GUI::GCodeViewer::TBuffer::max_vertices_per_segment_size_bytes () const inline
{ return max_vertices_per_segment_size_floats() * sizeof(float); }
References max_vertices_per_segment_size_floats().
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
max_vertices_per_segment_size_floats()
size_t Slic3r::GUI::GCodeViewer::TBuffer::max_vertices_per_segment_size_floats () const inline
{ return vertices.vertex_size_floats() * static_cast<size_t>(max_vertices_per_segment()); }
References max_vertices_per_segment(), Slic3r::GUI::GCodeViewer::VBuffer::vertex_size_floats(), and vertices.
Referenced by max_vertices_per_segment_size_bytes().
reset()
void Slic3r::GUI::GCodeViewer::TBuffer::reset ()
{
    vertices.reset();
    for (IBuffer& buffer : indices) {
        buffer.reset();
    }
    indices.clear();
    paths.clear();
    render_paths.clear();
    model.reset();
}
Member Data Documentation
indices
std::vector<IBuffer> Slic3r::GUI::GCodeViewer::TBuffer::indices
Referenced by Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj(), has_data(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
model
Model Slic3r::GUI::GCodeViewer::TBuffer::model
Referenced by has_data(), Slic3r::GUI::GCodeViewer::init(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
paths
std::vector<Path> Slic3r::GUI::GCodeViewer::TBuffer::paths
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::GCodeViewer::log_memory_used(), and Slic3r::GUI::GCodeViewer::refresh_render_paths().
render_paths
std::vector<RenderPath> Slic3r::GUI::GCodeViewer::TBuffer::render_paths
Referenced by Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj(), Slic3r::GUI::GCodeViewer::log_memory_used(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
render_primitive_type
ERenderPrimitiveType Slic3r::GUI::GCodeViewer::TBuffer::render_primitive_type
Referenced by Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj(), has_data(), indices_per_segment(), Slic3r::GUI::GCodeViewer::init(), Slic3r::GUI::GCodeViewer::load_toolpaths(), max_indices_per_segment(), max_vertices_per_segment(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
shader
std::string Slic3r::GUI::GCodeViewer::TBuffer::shader
Referenced by Slic3r::GUI::GCodeViewer::init(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
vertices
VBuffer Slic3r::GUI::GCodeViewer::TBuffer::vertices
Referenced by Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj(), has_data(), Slic3r::GUI::GCodeViewer::init(), Slic3r::GUI::GCodeViewer::load_toolpaths(), max_vertices_per_segment_size_floats(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
visible
bool Slic3r::GUI::GCodeViewer::TBuffer::visible { false }
Referenced by Slic3r::GUI::GCodeViewer::refresh_render_paths(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GCodeViewer.hpp
src/slic3r/GUI/GCodeViewer.cpp