Prusa Slicer: src/slic3r/GUI/3DBed.cpp File Reference
3DBed.cpp File Reference
#include "libslic3r/libslic3r.h"
#include "3DBed.hpp"
#include "libslic3r/Polygon.hpp"
#include "libslic3r/ClipperUtils.hpp"
#include "libslic3r/BoundingBox.hpp"
#include "libslic3r/Geometry/Circle.hpp"
#include "libslic3r/Tesselate.hpp"
#include "libslic3r/PresetBundle.hpp"
#include "GUI_App.hpp"
#include "GLCanvas3D.hpp"
#include "Plater.hpp"
#include "Camera.hpp"
#include <GL/glew.h>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/log/trivial.hpp>
Namespaces
namespace Slic3r
namespace Slic3r::GUI
Variables
static const float GROUND_Z = -0.02f
static const Slic3r::ColorRGBA DEFAULT_MODEL_COLOR = Slic3r::ColorRGBA::DARK_GRAY()
static const Slic3r::ColorRGBA PICKING_MODEL_COLOR = Slic3r::ColorRGBA::BLACK()
static const Slic3r::ColorRGBA DEFAULT_SOLID_GRID_COLOR = { 0.9f, 0.9f, 0.9f, 1.0f }
static const Slic3r::ColorRGBA DEFAULT_TRANSPARENT_GRID_COLOR = { 0.9f, 0.9f, 0.9f, 0.6f }
Variable Documentation
DEFAULT_MODEL_COLOR
const Slic3r::ColorRGBA DEFAULT_MODEL_COLOR = Slic3r::ColorRGBA::DARK_GRAY() static
Referenced by Slic3r::GUI::Bed3D::init_triangles(), Slic3r::GUI::Bed3D::render_internal(), and Slic3r::GUI::Bed3D::render_model().
DEFAULT_SOLID_GRID_COLOR
const Slic3r::ColorRGBA DEFAULT_SOLID_GRID_COLOR = { 0.9f, 0.9f, 0.9f, 1.0f } static
Referenced by Slic3r::GUI::Bed3D::render_default().
DEFAULT_TRANSPARENT_GRID_COLOR
const Slic3r::ColorRGBA DEFAULT_TRANSPARENT_GRID_COLOR = { 0.9f, 0.9f, 0.9f, 0.6f } static
Referenced by Slic3r::GUI::Bed3D::render_default().
GROUND_Z
const float GROUND_Z = -0.02f static
Referenced by Slic3r::GUI::Bed3D::init_contourlines(), Slic3r::GUI::Bed3D::init_gridlines(), Slic3r::GUI::Bed3D::init_triangles(), and Slic3r::GUI::Bed3D::set_shape().
PICKING_MODEL_COLOR
const Slic3r::ColorRGBA PICKING_MODEL_COLOR = Slic3r::ColorRGBA::BLACK() static
Referenced by Slic3r::GUI::Bed3D::render_internal().