Prusa Slicer: Slic3r::GUI::Emboss::CreateSurfaceVolumeJob Class Reference
Slic3r::GUI::Emboss::CreateSurfaceVolumeJob Class Reference
Cut surface from object and create cutted volume Should not be stopped.
#include <src/slic3r/GUI/Jobs/EmbossJob.hpp>
Public Member Functions
CreateSurfaceVolumeJob (CreateSurfaceVolumeData &&input)
Create Surface volume.
void process (Ctl &ctl) override
void finalize (bool canceled, std::exception_ptr &eptr) override
Private Attributes
CreateSurfaceVolumeData m_input
TriangleMesh m_result
Detailed Description
Cut surface from object and create cutted volume Should not be stopped.
Constructor & Destructor Documentation
CreateSurfaceVolumeJob()
CreateSurfaceVolumeJob::CreateSurfaceVolumeJob (CreateSurfaceVolumeData && input)
Create Surface volume.
    : m_input(std::move(input))
{
    assert(priv::check(m_input, true));
}
References priv::check(), and m_input.
Member Function Documentation
finalize()
void CreateSurfaceVolumeJob::finalize (bool canceled, std::exception_ptr & eptr) override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (!priv::finalize(canceled, eptr, m_input))
        return;
    priv::create_volume(std::move(m_result), m_input.object_id,
        m_input.volume_type, m_input.text_tr, m_input);
}
References priv::create_volume(), priv::finalize(), m_input, m_result, Slic3r::GUI::Emboss::CreateSurfaceVolumeData::object_id, Slic3r::GUI::Emboss::SurfaceVolumeData::text_tr, and Slic3r::GUI::Emboss::CreateSurfaceVolumeData::volume_type.
process()
void CreateSurfaceVolumeJob::process (Ctl & ctl) override virtual
Implements Slic3r::GUI::Job.
{
    if (!priv::check(m_input))
        throw std::runtime_error("Bad input data for CreateSurfaceVolumeJob.");
    // check cancelation of process
    auto was_canceled = [&ctl]() -> bool { return ctl.was_canceled(); };
    m_result = priv::cut_surface(m_input, m_input, was_canceled);
}
References priv::check(), priv::cut_surface(), m_input, m_result, and Slic3r::GUI::Job::Ctl::was_canceled().
Member Data Documentation
m_input
CreateSurfaceVolumeData Slic3r::GUI::Emboss::CreateSurfaceVolumeJob::m_input private
Referenced by CreateSurfaceVolumeJob(), finalize(), and process().
m_result
TriangleMesh Slic3r::GUI::Emboss::CreateSurfaceVolumeJob::m_result private
Referenced by finalize(), and process().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/EmbossJob.hpp
src/slic3r/GUI/Jobs/EmbossJob.cpp