Prusa Slicer: Slic3r::opt::Optimizer< Method, Enable > Class Template Reference
Slic3r::opt::Optimizer< Method, Enable > Class Template Reference
#include <src/libslic3r/Optimize/Optimizer.hpp>
Public Member Functions
Optimizer (const StopCriteria &)
Optimizer & to_min ()
Optimizer & to_max ()
Optimizer & set_criteria (const StopCriteria &)
StopCriteria get_criteria () const
template<class Func , size_t N, class... EqConstraints, class... IneqConstraints>
Result< N > optimize (Func &&, const Input< N > &, const Bounds< N > &, const std::tuple< EqConstraints... > &eq_constraints={}, const std::tuple< IneqConstraints... > &ineq_constraint={})
void seed (long)
Detailed Description
template<class Method, class Enable = void>
class Slic3r::opt::Optimizer< Method, Enable >
Constructor & Destructor Documentation
Optimizer()
template<class Method , class Enable = void> Slic3r::opt::Optimizer< Method, Enable >::Optimizer (const StopCriteria &) inline
    {
        static_assert (always_false<Method>::value,
                       "Optimizer unimplemented for given method!");
    }
Member Function Documentation
get_criteria()
template<class Method , class Enable = void> StopCriteria Slic3r::opt::Optimizer< Method, Enable >::get_criteria () const inline
{ return {}; };
optimize()
template<class Method , class Enable = void> template<class Func , size_t N, class... EqConstraints, class... IneqConstraints> Result< N > Slic3r::opt::Optimizer< Method, Enable >::optimize (Func && , const Input< N > & , const Bounds< N > & , const std::tuple< EqConstraints... > & eq_constraints = {}, const std::tuple< IneqConstraints... > & ineq_constraint = {}) inline
                                                                          {},
                       const std::tuple<IneqConstraints...> &ineq_constraint = {}
                       ) { return {}; }
Referenced by Slic3r::sla::DefaultSupportTree::add_pinheads(), Slic3r::sla::deepsearch_ground_connection(), Slic3r::sla::find_best_misalignment_rotation(), Slic3r::sla::find_least_supports_rotation(), Slic3r::sla::optimize_anchor_placement(), Slic3r::sla::optimize_pinhead_placement(), Slic3r::sla::search_ground_route(), and Slic3r::sla::search_widening_path().
seed()
template<class Method , class Enable = void> void Slic3r::opt::Optimizer< Method, Enable >::seed (long) inline
{}
Referenced by Slic3r::sla::DefaultSupportTree::add_pinheads(), Slic3r::sla::deepsearch_ground_connection(), Slic3r::sla::optimize_anchor_placement(), Slic3r::sla::optimize_pinhead_placement(), and Slic3r::sla::search_ground_route().
set_criteria()
template<class Method , class Enable = void> Optimizer & Slic3r::opt::Optimizer< Method, Enable >::set_criteria (const StopCriteria &) inline
{ return *this; }
to_max()
template<class Method , class Enable = void> Optimizer & Slic3r::opt::Optimizer< Method, Enable >::to_max () inline
{ return *this; }
Referenced by Slic3r::sla::DefaultSupportTree::add_pinheads(), Slic3r::sla::find_best_misalignment_rotation(), Slic3r::sla::optimize_anchor_placement(), Slic3r::sla::optimize_pinhead_placement(), Slic3r::sla::search_ground_route(), and Slic3r::sla::search_widening_path().
to_min()
template<class Method , class Enable = void> Optimizer & Slic3r::opt::Optimizer< Method, Enable >::to_min () inline
{ return *this; }
Referenced by Slic3r::sla::deepsearch_ground_connection(), and Slic3r::sla::find_least_supports_rotation().
The documentation for this class was generated from the following file:
src/libslic3r/Optimize/Optimizer.hpp