Prusa Slicer: Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false > Class Template Reference
Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false > Class Template Reference
#include <src/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = _ConjLhs , ConjRhs = false , Vectorizable = packet_traits<LhsScalar>::Vectorizable && packet_traits<RhsScalar>::Vectorizable , LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1 ,
RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1 , ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1 , NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS , nr = 4 ,
mr = (EIGEN_PLAIN_ENUM_MIN(16,NumberOfRegisters)/2/nr)*LhsPacketSize , LhsProgress = LhsPacketSize , RhsProgress = 1
}
typedef std::complex< RealScalar > LhsScalar
typedef RealScalar RhsScalar
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
typedef packet_traits< LhsScalar >::type _LhsPacket
typedef packet_traits< RhsScalar >::type _RhsPacket
typedef packet_traits< ResScalar >::type _ResPacket
typedef conditional< Vectorizable, _LhsPacket, LhsScalar >::type LhsPacket
typedef conditional< Vectorizable, _RhsPacket, RhsScalar >::type RhsPacket
typedef conditional< Vectorizable, _ResPacket, ResScalar >::type ResPacket
typedef ResPacket AccPacket
Public Member Functions
EIGEN_STRONG_INLINE void initAcc (AccPacket &p)
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, RhsPacket &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, RhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsPacket &b0, RhsPacket &b1, RhsPacket &b2, RhsPacket &b3)
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, AccPacket &c, RhsPacket &tmp) const
EIGEN_STRONG_INLINE void madd_impl (const LhsPacket &a, const RhsPacket &b, AccPacket &c, RhsPacket &tmp, const true_type &) const
EIGEN_STRONG_INLINE void madd_impl (const LhsScalar &a, const RhsScalar &b, ResScalar &c, RhsScalar &, const false_type &) const
EIGEN_STRONG_INLINE void acc (const AccPacket &c, const ResPacket &alpha, ResPacket &r) const
Protected Attributes
conj_helper< ResPacket, ResPacket, ConjLhs, false > cj
Detailed Description
template<typename RealScalar, bool _ConjLhs>
class Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >
Member Typedef Documentation
_LhsPacket
template<typename RealScalar , bool _ConjLhs> typedef packet_traits<LhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::_LhsPacket
_ResPacket
template<typename RealScalar , bool _ConjLhs> typedef packet_traits<ResScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::_ResPacket
_RhsPacket
template<typename RealScalar , bool _ConjLhs> typedef packet_traits<RhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::_RhsPacket
AccPacket
template<typename RealScalar , bool _ConjLhs> typedef ResPacket Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::AccPacket
LhsPacket
template<typename RealScalar , bool _ConjLhs> typedef conditional<Vectorizable,_LhsPacket,LhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::LhsPacket
LhsScalar
template<typename RealScalar , bool _ConjLhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::LhsScalar
ResPacket
template<typename RealScalar , bool _ConjLhs> typedef conditional<Vectorizable,_ResPacket,ResScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::ResPacket
ResScalar
template<typename RealScalar , bool _ConjLhs> typedef ScalarBinaryOpTraits<LhsScalar,RhsScalar>::ReturnType Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::ResScalar
RhsPacket
template<typename RealScalar , bool _ConjLhs> typedef conditional<Vectorizable,_RhsPacket,RhsScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::RhsPacket
RhsScalar
template<typename RealScalar , bool _ConjLhs> typedef RealScalar Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::RhsScalar
Member Enumeration Documentation
anonymous enum
template<typename RealScalar , bool _ConjLhs> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
LhsPacketSize
RhsPacketSize
ResPacketSize
NumberOfRegisters
nr
mr
LhsProgress
RhsProgress
       {
    ConjLhs = _ConjLhs,
    ConjRhs = false,
    Vectorizable = packet_traits<LhsScalar>::Vectorizable && packet_traits<RhsScalar>::Vectorizable,
    LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1,
    RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1,
    ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1,
    NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS,
    nr = 4,
#if defined(EIGEN_HAS_SINGLE_INSTRUCTION_MADD) && !defined(EIGEN_VECTORIZE_ALTIVEC) && !defined(EIGEN_VECTORIZE_VSX)
    // we assume 16 registers
    mr = 3*LhsPacketSize,
#else
    mr = (EIGEN_PLAIN_ENUM_MIN(16,NumberOfRegisters)/2/nr)*LhsPacketSize,
#endif
    LhsProgress = LhsPacketSize,
    RhsProgress = 1
  };
Member Function Documentation
acc()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::acc (const AccPacket & c, const ResPacket & alpha, ResPacket & r) const inline
  {
    r = cj.pmadd(c,alpha,r);
  }
broadcastRhs()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::broadcastRhs (const RhsScalar * b, RhsPacket & b0, RhsPacket & b1, RhsPacket & b2, RhsPacket & b3) inline
  {
    pbroadcast4(b, b0, b1, b2, b3);
  }
References Eigen::internal::pbroadcast4().
initAcc()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::initAcc (AccPacket & p) inline
  {
    p = pset1<ResPacket>(ResScalar(0));
  }
loadLhs()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
  {
    dest = pload<LhsPacket>(a);
  }
loadLhsUnaligned()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadLhsUnaligned (const LhsScalar * a, LhsPacket & dest) const inline
  {
    dest = ploadu<LhsPacket>(a);
  }
loadRhs()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadRhs (const RhsScalar * b, RhsPacket & dest) const inline
  {
    dest = pset1<RhsPacket>(*b);
  }
loadRhsQuad()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::loadRhsQuad (const RhsScalar * b, RhsPacket & dest) const inline
  {
    dest = pset1<RhsPacket>(*b);
  }
madd()
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd (const LhsPacket & a, const RhsPacket & b, AccPacket & c, RhsPacket & tmp) const inline
  {
    madd_impl(a, b, c, tmp, typename conditional<Vectorizable,true_type,false_type>::type());
  }
madd_impl() [1/2]
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl (const LhsPacket & a, const RhsPacket & b, AccPacket & c, RhsPacket & tmp, const true_type &) const inline
  {
#ifdef EIGEN_HAS_SINGLE_INSTRUCTION_MADD
    EIGEN_UNUSED_VARIABLE(tmp);
    c.v = pmadd(a.v,b,c.v);
#else
    tmp = b; tmp = pmul(a.v,tmp); c.v = padd(c.v,tmp);
#endif
  }
References EIGEN_UNUSED_VARIABLE, Eigen::internal::padd(), Eigen::internal::pmadd(), and Eigen::internal::pmul().
madd_impl() [2/2]
template<typename RealScalar , bool _ConjLhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl (const LhsScalar & a, const RhsScalar & b, ResScalar & c, RhsScalar & , const false_type &) const inline
  {
    c += a * b;
  }
Member Data Documentation
cj
template<typename RealScalar , bool _ConjLhs> conj_helper<ResPacket,ResPacket,ConjLhs,false> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::cj protected
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h