Prusa Slicer: Eigen::FullPivLU< _MatrixType > Class Template Reference
Eigen::FullPivLU< _MatrixType > Class Template Reference
LU decomposition of a matrix with complete pivoting, and related features.
#include <src/eigen/Eigen/src/LU/FullPivLU.h>
Public Types
enum { MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef SolverBase< FullPivLU > Base
typedef internal::plain_row_type< MatrixType, StorageIndex >::type IntRowVectorType
typedef internal::plain_col_type< MatrixType, StorageIndex >::type IntColVectorType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime > PermutationQType
typedef PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime > PermutationPType
typedef MatrixType::PlainObject PlainObject
enum
typedef internal::traits< FullPivLU< _MatrixType > >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef internal::add_const< Transpose< constDerived > >::type ConstTransposeReturnType
typedef internal::conditional< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, ConstTransposeReturnType >, ConstTransposeReturnType >::type AdjointReturnType
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
FullPivLU ()
Default Constructor.
FullPivLU (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
FullPivLU (const EigenBase< InputType > &matrix)
template<typename InputType >
FullPivLU (EigenBase< InputType > &matrix)
Constructs a LU factorization from a given matrix.
template<typename InputType >
FullPivLU & compute (const EigenBase< InputType > &matrix)
const MatrixType & matrixLU () const
Index nonzeroPivots () const
RealScalar maxPivot () const
EIGEN_DEVICE_FUNC const PermutationPType & permutationP () const
const PermutationQType & permutationQ () const
const internal::kernel_retval< FullPivLU > kernel () const
const internal::image_retval< FullPivLU > image (const MatrixType &originalMatrix) const
template<typename Rhs >
const Solve< FullPivLU, Rhs > solve (const MatrixBase< Rhs > &b) const
RealScalar rcond () const
internal::traits< MatrixType >::Scalar determinant () const
FullPivLU & setThreshold (const RealScalar &threshold)
FullPivLU & setThreshold (Default_t)
RealScalar threshold () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< FullPivLU > inverse () const
MatrixType reconstructedMatrix () const
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC Index cols () const
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl (const RhsType &rhs, DstType &dst) const
template<bool Conjugate, typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
template<bool Conjugate, typename RhsType , typename DstType >
void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
ConstTransposeReturnType transpose () const
AdjointReturnType adjoint () const
EIGEN_DEVICE_FUNC FullPivLU< _MatrixType > & derived ()
EIGEN_DEVICE_FUNC const FullPivLU< _MatrixType > & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC Index size () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
void computeInPlace ()
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
MatrixType m_lu
PermutationPType m_p
PermutationQType m_q
IntColVectorType m_rowsTranspositions
IntRowVectorType m_colsTranspositions
Index m_nonzero_pivots
RealScalar m_l1_norm
RealScalar m_maxpivot
RealScalar m_prescribedThreshold
signed char m_det_pq
bool m_isInitialized
bool m_usePrescribedThreshold
Detailed Description
template<typename _MatrixType>
class Eigen::FullPivLU< _MatrixType >
LU decomposition of a matrix with complete pivoting, and related features.
Template Parameters
_MatrixType the type of the matrix of which we are computing the LU decomposition
This class represents a LU decomposition of any matrix, with complete pivoting: the matrix A is decomposed as where L is unit-lower-triangular, U is upper-triangular, and P and Q are permutation matrices. This is a rank-revealing LU decomposition. The eigenvalues (diagonal coefficients) of U are sorted in such a way that any zeros are at the end.
This decomposition provides the generic approach to solving systems of linear equations, computing the rank, invertibility, inverse, kernel, and determinant.
This LU decomposition is very stable and well tested with large matrices. However there are use cases where the SVD decomposition is inherently more stable and/or flexible. For example, when computing the kernel of a matrix, working with the SVD allows to select the smallest singular values of the matrix, something that the LU decomposition doesn't see.
The data of the LU decomposition can be directly accessed through the methods matrixLU(), permutationP(), permutationQ().
As an exemple, here is how the original matrix can be retrieved:
Output:
This class supports the inplace decomposition mechanism.
See also
MatrixBase::fullPivLu(), MatrixBase::determinant(), MatrixBase::inverse()
Member Typedef Documentation
AdjointReturnType
typedef internal::conditional<NumTraits<Scalar>::IsComplex,CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>,ConstTransposeReturnType>,ConstTransposeReturnType>::type Eigen::SolverBase< FullPivLU< _MatrixType > >::AdjointReturnType inherited
Base
template<typename _MatrixType > typedef SolverBase<FullPivLU> Eigen::FullPivLU< _MatrixType >::Base
CoeffReturnType
typedef Scalar Eigen::SolverBase< FullPivLU< _MatrixType > >::CoeffReturnType inherited
ConstTransposeReturnType
typedef internal::add_const<Transpose<constDerived>>::type Eigen::SolverBase< FullPivLU< _MatrixType > >::ConstTransposeReturnType inherited
Index
template<typename Derived > typedef Eigen::Index Eigen::EigenBase< Derived >::Index inherited
The interface type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
StorageIndex, TopicPreprocessorDirectives.
IntColVectorType
template<typename _MatrixType > typedef internal::plain_col_type<MatrixType,StorageIndex>::type Eigen::FullPivLU< _MatrixType >::IntColVectorType
IntRowVectorType
template<typename _MatrixType > typedef internal::plain_row_type<MatrixType,StorageIndex>::type Eigen::FullPivLU< _MatrixType >::IntRowVectorType
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::FullPivLU< _MatrixType >::MatrixType
PermutationPType
template<typename _MatrixType > typedef PermutationMatrix<RowsAtCompileTime, MaxRowsAtCompileTime> Eigen::FullPivLU< _MatrixType >::PermutationPType
PermutationQType
template<typename _MatrixType > typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::FullPivLU< _MatrixType >::PermutationQType
PlainObject
template<typename _MatrixType > typedef MatrixType::PlainObject Eigen::FullPivLU< _MatrixType >::PlainObject
Scalar
typedef internal::traits<FullPivLU< _MatrixType > >::Scalar Eigen::SolverBase< FullPivLU< _MatrixType > >::Scalar inherited
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::EigenBase< Derived >::StorageKind inherited
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
         {
      RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
      ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
      SizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::RowsAtCompileTime,
                                                          internal::traits<Derived>::ColsAtCompileTime>::ret),
      MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
      MaxSizeAtCompileTime = (internal::size_at_compile_time<internal::traits<Derived>::MaxRowsAtCompileTime,
                                                             internal::traits<Derived>::MaxColsAtCompileTime>::ret),
      IsVectorAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime == 1
                           || internal::traits<Derived>::MaxColsAtCompileTime == 1
    };
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
MaxRowsAtCompileTime
MaxColsAtCompileTime
         {
      MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
FullPivLU() [1/4]
template<typename MatrixType > Eigen::FullPivLU< MatrixType >::FullPivLU
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via LU::compute(const MatrixType&).
  : m_isInitialized(false), m_usePrescribedThreshold(false)
{
}
FullPivLU() [2/4]
template<typename MatrixType > Eigen::FullPivLU< MatrixType >::FullPivLU (Index rows, Index cols)
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
FullPivLU()
  : m_lu(rows, cols),
    m_p(rows),
    m_q(cols),
    m_rowsTranspositions(rows),
    m_colsTranspositions(cols),
    m_isInitialized(false),
    m_usePrescribedThreshold(false)
{
}
FullPivLU() [3/4]
template<typename MatrixType > template<typename InputType > Eigen::FullPivLU< MatrixType >::FullPivLU (const EigenBase< InputType > & matrix) explicit
Constructor.
Parameters
matrix the matrix of which to compute the LU decomposition. It is required to be nonzero.
  : m_lu(matrix.rows(), matrix.cols()),
    m_p(matrix.rows()),
    m_q(matrix.cols()),
    m_rowsTranspositions(matrix.rows()),
    m_colsTranspositions(matrix.cols()),
    m_isInitialized(false),
    m_usePrescribedThreshold(false)
{
  compute(matrix.derived());
}
References Eigen::FullPivLU< _MatrixType >::compute(), and Eigen::EigenBase< Derived >::derived().
FullPivLU() [4/4]
template<typename MatrixType > template<typename InputType > Eigen::FullPivLU< MatrixType >::FullPivLU (EigenBase< InputType > & matrix) explicit
Constructs a LU factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
FullPivLU(const EigenBase&)
  : m_lu(matrix.derived()),
    m_p(matrix.rows()),
    m_q(matrix.cols()),
    m_rowsTranspositions(matrix.rows()),
    m_colsTranspositions(matrix.cols()),
    m_isInitialized(false),
    m_usePrescribedThreshold(false)
{
  computeInPlace();
}
References Eigen::FullPivLU< _MatrixType >::computeInPlace().
Member Function Documentation
_solve_impl() [1/2]
template<typename _MatrixType > template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::FullPivLU< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
_solve_impl() [2/2]
template<typename _MatrixType > template<typename RhsType , typename DstType > void Eigen::FullPivLU< _MatrixType >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
  /* The decomposition PAQ = LU can be rewritten as A = P^{-1} L U Q^{-1}.
  * So we proceed as follows:
  * Step 1: compute c = P * rhs.
  * Step 2: replace c by the solution x to Lx = c. Exists because L is invertible.
  * Step 3: replace c by the solution x to Ux = c. May or may not exist.
  * Step 4: result = Q * c;
  */
  const Index rows = this->rows(),
              cols = this->cols(),
              nonzero_pivots = this->rank();
  eigen_assert(rhs.rows() == rows);
  const Index smalldim = (std::min)(rows, cols);
  if(nonzero_pivots == 0)
  {
    dst.setZero();
    return;
  }
  typename RhsType::PlainObject c(rhs.rows(), rhs.cols());
  // Step 1
  c = permutationP() * rhs;
  // Step 2
  m_lu.topLeftCorner(smalldim,smalldim)
      .template triangularView<UnitLower>()
      .solveInPlace(c.topRows(smalldim));
  if(rows>cols)
    c.bottomRows(rows-cols) -= m_lu.bottomRows(rows-cols) * c.topRows(cols);
  // Step 3
  m_lu.topLeftCorner(nonzero_pivots, nonzero_pivots)
      .template triangularView<Upper>()
      .solveInPlace(c.topRows(nonzero_pivots));
  // Step 4
  for(Index i = 0; i < nonzero_pivots; ++i)
    dst.row(permutationQ().indices().coeff(i)) = c.row(i);
  for(Index i = nonzero_pivots; i < m_lu.cols(); ++i)
    dst.row(permutationQ().indices().coeff(i)).setZero();
}
References eigen_assert.
_solve_impl_transposed() [1/2]
template<typename _MatrixType > template<bool Conjugate, typename RhsType , typename DstType > EIGEN_DEVICE_FUNC void Eigen::FullPivLU< _MatrixType >::_solve_impl_transposed (const RhsType & rhs, DstType & dst) const
_solve_impl_transposed() [2/2]
template<typename _MatrixType > template<bool Conjugate, typename RhsType , typename DstType > void Eigen::FullPivLU< _MatrixType >::_solve_impl_transposed (const RhsType & rhs, DstType & dst) const
{
  /* The decomposition PAQ = LU can be rewritten as A = P^{-1} L U Q^{-1},
   * and since permutations are real and unitary, we can write this
   * as   A^T = Q U^T L^T P,
   * So we proceed as follows:
   * Step 1: compute c = Q^T rhs.
   * Step 2: replace c by the solution x to U^T x = c. May or may not exist.
   * Step 3: replace c by the solution x to L^T x = c.
   * Step 4: result = P^T c.
   * If Conjugate is true, replace "^T" by "^*" above.
   */
  const Index rows = this->rows(), cols = this->cols(),
    nonzero_pivots = this->rank();
   eigen_assert(rhs.rows() == cols);
  const Index smalldim = (std::min)(rows, cols);
  if(nonzero_pivots == 0)
  {
    dst.setZero();
    return;
  }
  typename RhsType::PlainObject c(rhs.rows(), rhs.cols());
  // Step 1
  c = permutationQ().inverse() * rhs;
  if (Conjugate) {
    // Step 2
    m_lu.topLeftCorner(nonzero_pivots, nonzero_pivots)
        .template triangularView<Upper>()
        .adjoint()
        .solveInPlace(c.topRows(nonzero_pivots));
    // Step 3
    m_lu.topLeftCorner(smalldim, smalldim)
        .template triangularView<UnitLower>()
        .adjoint()
        .solveInPlace(c.topRows(smalldim));
  } else {
    // Step 2
    m_lu.topLeftCorner(nonzero_pivots, nonzero_pivots)
        .template triangularView<Upper>()
        .transpose()
        .solveInPlace(c.topRows(nonzero_pivots));
    // Step 3
    m_lu.topLeftCorner(smalldim, smalldim)
        .template triangularView<UnitLower>()
        .transpose()
        .solveInPlace(c.topRows(smalldim));
  }
  // Step 4
  PermutationPType invp = permutationP().inverse().eval();
  for(Index i = 0; i < smalldim; ++i)
    dst.row(invp.indices().coeff(i)) = c.row(i);
  for(Index i = smalldim; i < rows; ++i)
    dst.row(invp.indices().coeff(i)).setZero();
}
References eigen_assert, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >::indices(), and Eigen::PermutationBase< Derived >::inverse().
addTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst += res;
  }
adjoint()
AdjointReturnType Eigen::SolverBase< FullPivLU< _MatrixType > >::adjoint () const inline inherited
Returns
an expression of the adjoint of the factored matrix
A typical usage is to solve for the adjoint problem A' x = b:
x = dec.adjoint().solve(b);
For real scalar types, this function is equivalent to transpose().
See also
transpose(), solve()
    {
      return AdjointReturnType(derived().transpose());
    }
applyThisOnTheLeft()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = this->derived() * dst;
  }
References Eigen::EigenBase< Derived >::derived().
applyThisOnTheRight()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    dst = dst * this->derived();
  }
References Eigen::EigenBase< Derived >::derived().
check_template_parameters()
template<typename _MatrixType > static void Eigen::FullPivLU< _MatrixType >::check_template_parameters () inline static protected
    {
      EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
    }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
cols()
template<typename _MatrixType > EIGEN_DEVICE_FUNC Index Eigen::FullPivLU< _MatrixType >::cols () const inline
{ return m_lu.cols(); }
References Eigen::FullPivLU< _MatrixType >::m_lu.
Referenced by Eigen::FullPivLU< _MatrixType >::dimensionOfKernel(), and Eigen::FullPivLU< _MatrixType >::isInjective().
compute()
template<typename _MatrixType > template<typename InputType > FullPivLU & Eigen::FullPivLU< _MatrixType >::compute (const EigenBase< InputType > & matrix) inline
Computes the LU decomposition of the given matrix.
Parameters
matrix the matrix of which to compute the LU decomposition. It is required to be nonzero.
Returns
a reference to *this
{
      m_lu = matrix.derived();
      computeInPlace();
      return *this;
    }
References Eigen::FullPivLU< _MatrixType >::computeInPlace(), Eigen::EigenBase< Derived >::derived(), and Eigen::FullPivLU< _MatrixType >::m_lu.
Referenced by Eigen::FullPivLU< _MatrixType >::FullPivLU().
computeInPlace()
template<typename MatrixType > void Eigen::FullPivLU< MatrixType >::computeInPlace protected
{
  check_template_parameters();
  // the permutations are stored as int indices, so just to be sure:
  eigen_assert(m_lu.rows()<=NumTraits<int>::highest() && m_lu.cols()<=NumTraits<int>::highest());
  m_l1_norm = m_lu.cwiseAbs().colwise().sum().maxCoeff();
  const Index size = m_lu.diagonalSize();
  const Index rows = m_lu.rows();
  const Index cols = m_lu.cols();
  // will store the transpositions, before we accumulate them at the end.
  // can't accumulate on-the-fly because that will be done in reverse order for the rows.
  m_rowsTranspositions.resize(m_lu.rows());
  m_colsTranspositions.resize(m_lu.cols());
  Index number_of_transpositions = 0; // number of NONTRIVIAL transpositions, i.e. m_rowsTranspositions[i]!=i
  m_nonzero_pivots = size; // the generic case is that in which all pivots are nonzero (invertible case)
  m_maxpivot = RealScalar(0);
  for(Index k = 0; k < size; ++k)
  {
    // First, we need to find the pivot.
    // biggest coefficient in the remaining bottom-right corner (starting at row k, col k)
    Index row_of_biggest_in_corner, col_of_biggest_in_corner;
    typedef internal::scalar_score_coeff_op<Scalar> Scoring;
    typedef typename Scoring::result_type Score;
    Score biggest_in_corner;
    biggest_in_corner = m_lu.bottomRightCorner(rows-k, cols-k)
                        .unaryExpr(Scoring())
                        .maxCoeff(&row_of_biggest_in_corner, &col_of_biggest_in_corner);
    row_of_biggest_in_corner += k; // correct the values! since they were computed in the corner,
    col_of_biggest_in_corner += k; // need to add k to them.
    if(biggest_in_corner==Score(0))
    {
      // before exiting, make sure to initialize the still uninitialized transpositions
      // in a sane state without destroying what we already have.
      m_nonzero_pivots = k;
      for(Index i = k; i < size; ++i)
      {
        m_rowsTranspositions.coeffRef(i) = i;
        m_colsTranspositions.coeffRef(i) = i;
      }
      break;
    }
    RealScalar abs_pivot = internal::abs_knowing_score<Scalar>()(m_lu(row_of_biggest_in_corner, col_of_biggest_in_corner), biggest_in_corner);
    if(abs_pivot > m_maxpivot) m_maxpivot = abs_pivot;
    // Now that we've found the pivot, we need to apply the row/col swaps to
    // bring it to the location (k,k).
    m_rowsTranspositions.coeffRef(k) = row_of_biggest_in_corner;
    m_colsTranspositions.coeffRef(k) = col_of_biggest_in_corner;
    if(k != row_of_biggest_in_corner) {
      m_lu.row(k).swap(m_lu.row(row_of_biggest_in_corner));
      ++number_of_transpositions;
    }
    if(k != col_of_biggest_in_corner) {
      m_lu.col(k).swap(m_lu.col(col_of_biggest_in_corner));
      ++number_of_transpositions;
    }
    // Now that the pivot is at the right location, we update the remaining
    // bottom-right corner by Gaussian elimination.
    if(k<rows-1)
      m_lu.col(k).tail(rows-k-1) /= m_lu.coeff(k,k);
    if(k<size-1)
      m_lu.block(k+1,k+1,rows-k-1,cols-k-1).noalias() -= m_lu.col(k).tail(rows-k-1) * m_lu.row(k).tail(cols-k-1);
  }
  // the main loop is over, we still have to accumulate the transpositions to find the
  // permutations P and Q
  m_p.setIdentity(rows);
  for(Index k = size-1; k >= 0; --k)
    m_p.applyTranspositionOnTheRight(k, m_rowsTranspositions.coeff(k));
  m_q.setIdentity(cols);
  for(Index k = 0; k < size; ++k)
    m_q.applyTranspositionOnTheRight(k, m_colsTranspositions.coeff(k));
  m_det_pq = (number_of_transpositions%2) ? -1 : 1;
  m_isInitialized = true;
}
References eigen_assert.
Referenced by Eigen::FullPivLU< _MatrixType >::FullPivLU(), and Eigen::FullPivLU< _MatrixType >::compute().
const_cast_derived()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::EigenBase< Derived >::const_cast_derived () const inline inherited
  { return *static_cast<Derived*>(const_cast<EigenBase*>(this)); }
Referenced by Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::swap().
const_derived()
template<typename Derived > EIGEN_DEVICE_FUNC const Derived & Eigen::EigenBase< Derived >::const_derived () const inline inherited
  { return *static_cast<const Derived*>(this); }
derived() [1/2]
EIGEN_DEVICE_FUNC FullPivLU< _MatrixType > & Eigen::EigenBase< FullPivLU< _MatrixType > >::derived () inline inherited
Returns
a reference to the derived object
{ return *static_cast<Derived*>(this); }
derived() [2/2]
EIGEN_DEVICE_FUNC const FullPivLU< _MatrixType > & Eigen::EigenBase< FullPivLU< _MatrixType > >::derived () const inline inherited
Returns
a const reference to the derived object
{ return *static_cast<const Derived*>(this); }
determinant()
template<typename MatrixType > internal::traits< MatrixType >::Scalar Eigen::FullPivLU< MatrixType >::determinant
Returns
the determinant of the matrix of which *this is the LU decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the LU decomposition has already been computed.
Note
This is only for square matrices.
For fixed-size matrices of size up to 4, MatrixBase::determinant() offers optimized paths.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow.
See also
MatrixBase::determinant()
{
  eigen_assert(m_isInitialized && "LU is not initialized.");
  eigen_assert(m_lu.rows() == m_lu.cols() && "You can't take the determinant of a non-square matrix!");
  return Scalar(m_det_pq) * Scalar(m_lu.diagonal().prod());
}
References eigen_assert.
dimensionOfKernel()
template<typename _MatrixType > Index Eigen::FullPivLU< _MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the LU decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return cols() - rank();
    }
References Eigen::FullPivLU< _MatrixType >::cols(), eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, and Eigen::FullPivLU< _MatrixType >::rank().
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline inherited
  { derived().evalTo(dst); }
Referenced by Eigen::EigenBase< Derived >::subTo().
image()
template<typename _MatrixType > const internal::image_retval< FullPivLU > Eigen::FullPivLU< _MatrixType >::image (const MatrixType & originalMatrix) const inline
Returns
the image of the matrix, also called its column-space. The columns of the returned matrix will form a basis of the image (column-space).
Parameters
originalMatrix the original matrix, of which *this is the LU decomposition. The reason why it is needed to pass it here, is that this allows a large optimization, as otherwise this method would need to reconstruct it from the LU decomposition.
Note
If the image has dimension zero, then the returned matrix is a column-vector filled with zeros.
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Example:
Output:
See also
kernel()
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return internal::image_retval<FullPivLU>(*this, originalMatrix);
    }
References eigen_assert, and Eigen::FullPivLU< _MatrixType >::m_isInitialized.
inverse()
template<typename _MatrixType > const Inverse< FullPivLU > Eigen::FullPivLU< _MatrixType >::inverse () const inline
Returns
the inverse of the matrix of which *this is the LU decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
See also
MatrixBase::inverse()
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      eigen_assert(m_lu.rows() == m_lu.cols() && "You can't take the inverse of a non-square matrix!");
      return Inverse<FullPivLU>(*this);
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, and Eigen::FullPivLU< _MatrixType >::m_lu.
isInjective()
template<typename _MatrixType > bool Eigen::FullPivLU< _MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the LU decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return rank() == cols();
    }
References Eigen::FullPivLU< _MatrixType >::cols(), eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, and Eigen::FullPivLU< _MatrixType >::rank().
Referenced by Eigen::FullPivLU< _MatrixType >::isInvertible().
isInvertible()
template<typename _MatrixType > bool Eigen::FullPivLU< _MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the LU decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return isInjective() && (m_lu.rows() == m_lu.cols());
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::isInjective(), Eigen::FullPivLU< _MatrixType >::m_isInitialized, and Eigen::FullPivLU< _MatrixType >::m_lu.
isSurjective()
template<typename _MatrixType > bool Eigen::FullPivLU< _MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the LU decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return rank() == rows();
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, Eigen::FullPivLU< _MatrixType >::rank(), and Eigen::FullPivLU< _MatrixType >::rows().
kernel()
template<typename _MatrixType > const internal::kernel_retval< FullPivLU > Eigen::FullPivLU< _MatrixType >::kernel () const inline
Returns
the kernel of the matrix, also called its null-space. The columns of the returned matrix will form a basis of the kernel.
Note
If the kernel has dimension zero, then the returned matrix is a column-vector filled with zeros.
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Example:
Output:
See also
image()
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return internal::kernel_retval<FullPivLU>(*this);
    }
References eigen_assert, and Eigen::FullPivLU< _MatrixType >::m_isInitialized.
matrixLU()
template<typename _MatrixType > const MatrixType & Eigen::FullPivLU< _MatrixType >::matrixLU () const inline
Returns
the LU decomposition matrix: the upper-triangular part is U, the unit-lower-triangular part is L (at least for square matrices; in the non-square case, special care is needed, see the documentation of class FullPivLU).
See also
matrixL(), matrixU()
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return m_lu;
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, and Eigen::FullPivLU< _MatrixType >::m_lu.
maxPivot()
template<typename _MatrixType > RealScalar Eigen::FullPivLU< _MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of U.
{ return m_maxpivot; }
References Eigen::FullPivLU< _MatrixType >::m_maxpivot.
nonzeroPivots()
template<typename _MatrixType > Index Eigen::FullPivLU< _MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the LU decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return m_nonzero_pivots;
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, and Eigen::FullPivLU< _MatrixType >::m_nonzero_pivots.
permutationP()
template<typename _MatrixType > EIGEN_DEVICE_FUNC const PermutationPType & Eigen::FullPivLU< _MatrixType >::permutationP () const inline
Returns
the permutation matrix P
See also
permutationQ()
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return m_p;
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, and Eigen::FullPivLU< _MatrixType >::m_p.
permutationQ()
template<typename _MatrixType > const PermutationQType & Eigen::FullPivLU< _MatrixType >::permutationQ () const inline
Returns
the permutation matrix Q
See also
permutationP()
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return m_q;
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, and Eigen::FullPivLU< _MatrixType >::m_q.
rank()
template<typename _MatrixType > Index Eigen::FullPivLU< _MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the LU decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
    {
      using std::abs;
      eigen_assert(m_isInitialized && "LU is not initialized.");
      RealScalar premultiplied_threshold = abs(m_maxpivot) * threshold();
      Index result = 0;
      for(Index i = 0; i < m_nonzero_pivots; ++i)
        result += (abs(m_lu.coeff(i,i)) > premultiplied_threshold);
      return result;
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, Eigen::FullPivLU< _MatrixType >::m_lu, Eigen::FullPivLU< _MatrixType >::m_maxpivot, Eigen::FullPivLU< _MatrixType >::m_nonzero_pivots, and Eigen::FullPivLU< _MatrixType >::threshold().
Referenced by Eigen::FullPivLU< _MatrixType >::dimensionOfKernel(), Eigen::FullPivLU< _MatrixType >::isInjective(), and Eigen::FullPivLU< _MatrixType >::isSurjective().
rcond()
template<typename _MatrixType > RealScalar Eigen::FullPivLU< _MatrixType >::rcond () const inline
Returns
an estimate of the reciprocal condition number of the matrix of which *this is the LU decomposition.
    {
      eigen_assert(m_isInitialized && "PartialPivLU is not initialized.");
      return internal::rcond_estimate_helper(m_l1_norm, *this);
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, Eigen::FullPivLU< _MatrixType >::m_l1_norm, and Eigen::internal::rcond_estimate_helper().
reconstructedMatrix()
template<typename MatrixType > MatrixType Eigen::FullPivLU< MatrixType >::reconstructedMatrix
Returns
the matrix represented by the decomposition, i.e., it returns the product: . This function is provided for debug purposes.
{
  eigen_assert(m_isInitialized && "LU is not initialized.");
  const Index smalldim = (std::min)(m_lu.rows(), m_lu.cols());
  // LU
  MatrixType res(m_lu.rows(),m_lu.cols());
  // FIXME the .toDenseMatrix() should not be needed...
  res = m_lu.leftCols(smalldim)
            .template triangularView<UnitLower>().toDenseMatrix()
      * m_lu.topRows(smalldim)
            .template triangularView<Upper>().toDenseMatrix();
  // P^{-1}(LU)
  res = m_p.inverse() * res;
  // (P^{-1}LU)Q^{-1}
  res = res * m_q.inverse();
  return res;
}
References eigen_assert.
rows()
template<typename _MatrixType > EIGEN_DEVICE_FUNC Index Eigen::FullPivLU< _MatrixType >::rows () const inline
{ return m_lu.rows(); }
References Eigen::FullPivLU< _MatrixType >::m_lu.
Referenced by Eigen::FullPivLU< _MatrixType >::isSurjective().
setThreshold() [1/2]
template<typename _MatrixType > FullPivLU & Eigen::FullPivLU< _MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the LU decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
    {
      m_usePrescribedThreshold = true;
      m_prescribedThreshold = threshold;
      return *this;
    }
References Eigen::FullPivLU< _MatrixType >::m_prescribedThreshold, Eigen::FullPivLU< _MatrixType >::m_usePrescribedThreshold, and Eigen::FullPivLU< _MatrixType >::threshold().
setThreshold() [2/2]
template<typename _MatrixType > FullPivLU & Eigen::FullPivLU< _MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
lu.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
    {
      m_usePrescribedThreshold = false;
      return *this;
    }
References Eigen::FullPivLU< _MatrixType >::m_usePrescribedThreshold.
size()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::EigenBase< Derived >::size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
{ return rows() * cols(); }
References Eigen::EigenBase< Derived >::cols(), and Eigen::EigenBase< Derived >::rows().
Referenced by Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
solve()
template<typename _MatrixType > template<typename Rhs > const Solve< FullPivLU, Rhs > Eigen::FullPivLU< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
Returns
a solution x to the equation Ax=b, where A is the matrix of which *this is the LU decomposition.
Parameters
b the right-hand-side of the equation to solve. Can be a vector or a matrix, the only requirement in order for the equation to make sense is that b.rows()==A.rows(), where A is the matrix of which *this is the LU decomposition.
Returns
a solution.
\note_about_checking_solutions
\note_about_arbitrary_choice_of_solution \note_about_using_kernel_to_study_multiple_solutions
Example:
Output:
See also
TriangularView::solve(), kernel(), inverse()
    {
      eigen_assert(m_isInitialized && "LU is not initialized.");
      return Solve<FullPivLU, Rhs>(*this, b.derived());
    }
References eigen_assert, and Eigen::FullPivLU< _MatrixType >::m_isInitialized.
subTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline inherited
  {
    // This is the default implementation,
    // derived class can reimplement it in a more optimized way.
    typename Dest::PlainObject res(rows(),cols());
    evalTo(res);
    dst -= res;
  }
References Eigen::EigenBase< Derived >::cols(), Eigen::EigenBase< Derived >::evalTo(), and Eigen::EigenBase< Derived >::rows().
threshold()
template<typename _MatrixType > RealScalar Eigen::FullPivLU< _MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
    {
      eigen_assert(m_isInitialized || m_usePrescribedThreshold);
      return m_usePrescribedThreshold ? m_prescribedThreshold
      // this formula comes from experimenting (see "LU precision tuning" thread on the list)
      // and turns out to be identical to Higham's formula used already in LDLt.
                                      : NumTraits<Scalar>::epsilon() * m_lu.diagonalSize();
    }
References eigen_assert, Eigen::FullPivLU< _MatrixType >::m_isInitialized, Eigen::FullPivLU< _MatrixType >::m_lu, Eigen::FullPivLU< _MatrixType >::m_prescribedThreshold, and Eigen::FullPivLU< _MatrixType >::m_usePrescribedThreshold.
Referenced by Eigen::FullPivLU< _MatrixType >::rank(), and Eigen::FullPivLU< _MatrixType >::setThreshold().
transpose()
ConstTransposeReturnType Eigen::SolverBase< FullPivLU< _MatrixType > >::transpose () const inline inherited
Returns
an expression of the transposed of the factored matrix.
A typical usage is to solve for the transposed problem A^T x = b:
x = dec.transpose().solve(b);
See also
adjoint(), solve()
    {
      return ConstTransposeReturnType(derived());
    }
Member Data Documentation
m_colsTranspositions
template<typename _MatrixType > IntRowVectorType Eigen::FullPivLU< _MatrixType >::m_colsTranspositions protected
m_det_pq
template<typename _MatrixType > signed char Eigen::FullPivLU< _MatrixType >::m_det_pq protected
m_isInitialized
template<typename _MatrixType > bool Eigen::FullPivLU< _MatrixType >::m_isInitialized protected
Referenced by Eigen::FullPivLU< _MatrixType >::dimensionOfKernel(), Eigen::FullPivLU< _MatrixType >::image(), Eigen::FullPivLU< _MatrixType >::inverse(), Eigen::FullPivLU< _MatrixType >::isInjective(), Eigen::FullPivLU< _MatrixType >::isInvertible(), Eigen::FullPivLU< _MatrixType >::isSurjective(), Eigen::FullPivLU< _MatrixType >::kernel(), Eigen::FullPivLU< _MatrixType >::matrixLU(), Eigen::FullPivLU< _MatrixType >::nonzeroPivots(), Eigen::FullPivLU< _MatrixType >::permutationP(), Eigen::FullPivLU< _MatrixType >::permutationQ(), Eigen::FullPivLU< _MatrixType >::rank(), Eigen::FullPivLU< _MatrixType >::rcond(), Eigen::FullPivLU< _MatrixType >::solve(), and Eigen::FullPivLU< _MatrixType >::threshold().
m_l1_norm
template<typename _MatrixType > RealScalar Eigen::FullPivLU< _MatrixType >::m_l1_norm protected
Referenced by Eigen::FullPivLU< _MatrixType >::rcond().
m_lu
template<typename _MatrixType > MatrixType Eigen::FullPivLU< _MatrixType >::m_lu protected
Referenced by Eigen::FullPivLU< _MatrixType >::cols(), Eigen::FullPivLU< _MatrixType >::compute(), Eigen::FullPivLU< _MatrixType >::inverse(), Eigen::FullPivLU< _MatrixType >::isInvertible(), Eigen::FullPivLU< _MatrixType >::matrixLU(), Eigen::FullPivLU< _MatrixType >::rank(), Eigen::FullPivLU< _MatrixType >::rows(), and Eigen::FullPivLU< _MatrixType >::threshold().
m_maxpivot
template<typename _MatrixType > RealScalar Eigen::FullPivLU< _MatrixType >::m_maxpivot protected
Referenced by Eigen::FullPivLU< _MatrixType >::maxPivot(), and Eigen::FullPivLU< _MatrixType >::rank().
m_nonzero_pivots
template<typename _MatrixType > Index Eigen::FullPivLU< _MatrixType >::m_nonzero_pivots protected
Referenced by Eigen::FullPivLU< _MatrixType >::nonzeroPivots(), and Eigen::FullPivLU< _MatrixType >::rank().
m_p
template<typename _MatrixType > PermutationPType Eigen::FullPivLU< _MatrixType >::m_p protected
Referenced by Eigen::FullPivLU< _MatrixType >::permutationP().
m_prescribedThreshold
template<typename _MatrixType > RealScalar Eigen::FullPivLU< _MatrixType >::m_prescribedThreshold protected
Referenced by Eigen::FullPivLU< _MatrixType >::setThreshold(), and Eigen::FullPivLU< _MatrixType >::threshold().
m_q
template<typename _MatrixType > PermutationQType Eigen::FullPivLU< _MatrixType >::m_q protected
Referenced by Eigen::FullPivLU< _MatrixType >::permutationQ().
m_rowsTranspositions
template<typename _MatrixType > IntColVectorType Eigen::FullPivLU< _MatrixType >::m_rowsTranspositions protected
m_usePrescribedThreshold
template<typename _MatrixType > bool Eigen::FullPivLU< _MatrixType >::m_usePrescribedThreshold protected
Referenced by Eigen::FullPivLU< _MatrixType >::setThreshold(), Eigen::FullPivLU< _MatrixType >::setThreshold(), and Eigen::FullPivLU< _MatrixType >::threshold().
The documentation for this class was generated from the following files:
src/eigen/Eigen/src/Core/util/ForwardDeclarations.h
src/eigen/Eigen/src/LU/FullPivLU.h