Prusa Slicer: Slic3r::GUI::GLGizmoBase::Grabber Struct Reference
Slic3r::GUI::GLGizmoBase::Grabber Struct Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoBase.hpp>
Public Member Functions
Grabber ()=default
~Grabber ()
void render (bool hover, float size)
float get_half_size (float size) const
float get_dragging_half_size (float size) const
void register_raycasters_for_picking (int id)
void unregister_raycasters_for_picking ()
Public Attributes
bool enabled { true }
bool dragging { false }
Vec3d center { Vec3d::Zero() }
Vec3d angles { Vec3d::Zero() }
Transform3d matrix { Transform3d::Identity() }
ColorRGBA color { ColorRGBA::WHITE() }
EGrabberExtension extensions { EGrabberExtension::None }
int picking_id { -1 }
std::array< std::shared_ptr< SceneRaycasterItem >, GRABBER_ELEMENTS_MAX_COUNT > raycasters = { nullptr }
Static Public Attributes
static const float SizeFactor = 0.05f
static const float MinHalfSize = 1.5f
static const float DraggingScaleFactor = 1.25f
Private Member Functions
void render (float size, const ColorRGBA &render_color)
Static Private Attributes
static PickingModel s_cube
static PickingModel s_cone
Detailed Description
Constructor & Destructor Documentation
Grabber()
Slic3r::GUI::GLGizmoBase::Grabber::Grabber () default
~Grabber()
Slic3r::GUI::GLGizmoBase::Grabber::~Grabber ()
{
    if (s_cube.model.is_initialized())
        s_cube.model.reset();
    if (s_cone.model.is_initialized())
        s_cone.model.reset();
}
References Slic3r::GUI::GLModel::is_initialized(), Slic3r::GUI::PickingModel::model, Slic3r::GUI::GLModel::reset(), s_cone, and s_cube.
Member Function Documentation
get_dragging_half_size()
float Slic3r::GUI::GLGizmoBase::Grabber::get_dragging_half_size (float size) const
{
    return get_half_size(size) * DraggingScaleFactor;
}
References Slic3r::GUI::get_half_size().
get_half_size()
float Slic3r::GUI::GLGizmoBase::Grabber::get_half_size (float size) const
{
    return std::max(size * SizeFactor, MinHalfSize);
}
register_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::Grabber::register_raycasters_for_picking (int id)
{
    picking_id = id;
    // registration will happen on next call to render()
}
render() [1/2]
void Slic3r::GUI::GLGizmoBase::Grabber::render (bool hover, float size) inline
{ render(size, hover ? complementary(color) : color); }
References color, Slic3r::complementary(), and render().
Referenced by render().
render() [2/2]
void Slic3r::GUI::GLGizmoBase::Grabber::render (float size, const ColorRGBA & render_color) private
{
    GLShaderProgram* shader = wxGetApp().get_current_shader();
    if (shader == nullptr)
        return;
    if (!s_cube.model.is_initialized()) {
        // This cannot be done in constructor, OpenGL is not yet
        // initialized at that point (on Linux at least).
        indexed_triangle_set its = its_make_cube(1.0, 1.0, 1.0);
        its_translate(its, -0.5f * Vec3f::Ones());
        s_cube.model.init_from(its);
        s_cube.mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
    }
    if (!s_cone.model.is_initialized()) {
        indexed_triangle_set its = its_make_cone(0.375, 1.5, double(PI) / 18.0);
        s_cone.model.init_from(its);
        s_cone.mesh_raycaster = std::make_unique<MeshRaycaster>(std::make_shared<const TriangleMesh>(std::move(its)));
    }
    const float half_size = dragging ? get_dragging_half_size(size) : get_half_size(size);
    s_cube.model.set_color(render_color);
    s_cone.model.set_color(render_color);
    const Camera& camera = wxGetApp().plater()->get_camera();
    shader->set_uniform("projection_matrix", camera.get_projection_matrix());
    const Transform3d& view_matrix = camera.get_view_matrix();
    const Matrix3d view_matrix_no_offset = view_matrix.matrix().block(0, 0, 3, 3);
    std::vector<Transform3d> elements_matrices(GRABBER_ELEMENTS_MAX_COUNT, Transform3d::Identity());
    elements_matrices[0] = matrix * Geometry::translation_transform(center) * Geometry::rotation_transform(angles) * Geometry::scale_transform(2.0 * half_size);
    Transform3d view_model_matrix = view_matrix * elements_matrices[0];
    shader->set_uniform("view_model_matrix", view_model_matrix);
    Matrix3d view_normal_matrix = view_matrix_no_offset * elements_matrices[0].matrix().block(0, 0, 3, 3).inverse().transpose();
    shader->set_uniform("view_normal_matrix", view_normal_matrix);
    s_cube.model.render();
    auto render_extension = [&view_matrix, &view_matrix_no_offset, shader](const Transform3d& matrix) {
        const Transform3d view_model_matrix = view_matrix * matrix;
        shader->set_uniform("view_model_matrix", view_model_matrix);
        const Matrix3d view_normal_matrix = view_matrix_no_offset * matrix.matrix().block(0, 0, 3, 3).inverse().transpose();
        shader->set_uniform("view_normal_matrix", view_normal_matrix);
        s_cone.model.render();
    };
    if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::PosX)) != 0) {
        elements_matrices[1] = elements_matrices[0] * Geometry::translation_transform(Vec3d::UnitX()) * Geometry::rotation_transform({ 0.0, 0.5 * double(PI), 0.0 });
        render_extension(elements_matrices[1]);
    }
    if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::NegX)) != 0) {
        elements_matrices[2] = elements_matrices[0] * Geometry::translation_transform(-Vec3d::UnitX()) * Geometry::rotation_transform({ 0.0, -0.5 * double(PI), 0.0 });
        render_extension(elements_matrices[2]);
    }
    if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::PosY)) != 0) {
        elements_matrices[3] = elements_matrices[0] * Geometry::translation_transform(Vec3d::UnitY()) * Geometry::rotation_transform({ -0.5 * double(PI), 0.0, 0.0 });
        render_extension(elements_matrices[3]);
    }
    if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::NegY)) != 0) {
        elements_matrices[4] = elements_matrices[0] * Geometry::translation_transform(-Vec3d::UnitY()) * Geometry::rotation_transform({ 0.5 * double(PI), 0.0, 0.0 });
        render_extension(elements_matrices[4]);
    }
    if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::PosZ)) != 0) {
        elements_matrices[5] = elements_matrices[0] * Geometry::translation_transform(Vec3d::UnitZ());
        render_extension(elements_matrices[5]);
    }
    if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::NegZ)) != 0) {
        elements_matrices[6] = elements_matrices[0] * Geometry::translation_transform(-Vec3d::UnitZ()) * Geometry::rotation_transform({ double(PI), 0.0, 0.0 });
        render_extension(elements_matrices[6]);
    }
    if (raycasters[0] == nullptr) {
        GLCanvas3D& canvas = *wxGetApp().plater()->canvas3D();
        raycasters[0] = canvas.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, picking_id, *s_cube.mesh_raycaster, elements_matrices[0]);
        if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::PosX)) != 0)
            raycasters[1] = canvas.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, picking_id, *s_cone.mesh_raycaster, elements_matrices[1]);
        if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::NegX)) != 0)
            raycasters[2] = canvas.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, picking_id, *s_cone.mesh_raycaster, elements_matrices[2]);
        if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::PosY)) != 0)
            raycasters[3] = canvas.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, picking_id, *s_cone.mesh_raycaster, elements_matrices[3]);
        if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::NegY)) != 0)
            raycasters[4] = canvas.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, picking_id, *s_cone.mesh_raycaster, elements_matrices[4]);
        if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::PosZ)) != 0)
            raycasters[5] = canvas.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, picking_id, *s_cone.mesh_raycaster, elements_matrices[5]);
        if ((int(extensions) & int(GLGizmoBase::EGrabberExtension::NegZ)) != 0)
            raycasters[6] = canvas.add_raycaster_for_picking(SceneRaycaster::EType::Gizmo, picking_id, *s_cone.mesh_raycaster, elements_matrices[6]);
    }
    else {
        for (size_t i = 0; i < GRABBER_ELEMENTS_MAX_COUNT; ++i) {
            if (raycasters[i] != nullptr)
                raycasters[i]->set_transform(elements_matrices[i]);
        }
    }
}
References Slic3r::GUI::GLCanvas3D::add_raycaster_for_picking(), Slic3r::GUI::get_dragging_half_size(), Slic3r::GUI::get_half_size(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::SceneRaycaster::Gizmo, Slic3r::GUI::GLGizmoBase::GRABBER_ELEMENTS_MAX_COUNT, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::its_make_cone(), Slic3r::its_make_cube(), its_translate(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::GLGizmoBase::NegX, Slic3r::GUI::GLGizmoBase::NegY, Slic3r::GUI::GLGizmoBase::NegZ, PI, Slic3r::GUI::GLGizmoBase::PosX, Slic3r::GUI::GLGizmoBase::PosY, Slic3r::GUI::GLGizmoBase::PosZ, Slic3r::Geometry::rotation_transform(), Slic3r::Geometry::scale_transform(), Slic3r::GLShaderProgram::set_uniform(), and Slic3r::Geometry::translation_transform().
unregister_raycasters_for_picking()
void Slic3r::GUI::GLGizmoBase::Grabber::unregister_raycasters_for_picking ()
{
    wxGetApp().plater()->canvas3D()->remove_raycasters_for_picking(SceneRaycaster::EType::Gizmo, picking_id);
    picking_id = -1;
    raycasters = { nullptr };
}
References Slic3r::GUI::SceneRaycaster::Gizmo.
Member Data Documentation
angles
Vec3d Slic3r::GUI::GLGizmoBase::Grabber::angles { Vec3d::Zero() }
center
Vec3d Slic3r::GUI::GLGizmoBase::Grabber::center { Vec3d::Zero() }
color
ColorRGBA Slic3r::GUI::GLGizmoBase::Grabber::color { ColorRGBA::WHITE() }
Referenced by render().
dragging
bool Slic3r::GUI::GLGizmoBase::Grabber::dragging { false }
DraggingScaleFactor
const float Slic3r::GUI::GLGizmoBase::Grabber::DraggingScaleFactor = 1.25f static
enabled
bool Slic3r::GUI::GLGizmoBase::Grabber::enabled { true }
extensions
EGrabberExtension Slic3r::GUI::GLGizmoBase::Grabber::extensions { EGrabberExtension::None }
matrix
Transform3d Slic3r::GUI::GLGizmoBase::Grabber::matrix { Transform3d::Identity() }
MinHalfSize
const float Slic3r::GUI::GLGizmoBase::Grabber::MinHalfSize = 1.5f static
picking_id
int Slic3r::GUI::GLGizmoBase::Grabber::picking_id { -1 }
raycasters
std::array<std::shared_ptr<SceneRaycasterItem>, GRABBER_ELEMENTS_MAX_COUNT> Slic3r::GUI::GLGizmoBase::Grabber::raycasters = { nullptr }
s_cone
PickingModel Slic3r::GUI::GLGizmoBase::Grabber::s_cone static private
Referenced by ~Grabber().
s_cube
PickingModel Slic3r::GUI::GLGizmoBase::Grabber::s_cube static private
Referenced by ~Grabber().
SizeFactor
const float Slic3r::GUI::GLGizmoBase::Grabber::SizeFactor = 0.05f static
The documentation for this struct was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoBase.hpp
src/slic3r/GUI/Gizmos/GLGizmoBase.cpp