Prusa Slicer: Slic3r::GUI::Emboss::UpdateJob Class Reference
Slic3r::GUI::Emboss::UpdateJob Class Reference
Update text shape in existing text volume Predict that there is only one runnig(not canceled) instance of it.
#include <src/slic3r/GUI/Jobs/EmbossJob.hpp>
Public Member Functions
UpdateJob (DataUpdate &&input)
Update Volume.
void process (Ctl &ctl) override
Create new embossed volume by m_input data and store to m_result.
void finalize (bool canceled, std::exception_ptr &eptr) override
Update volume - change object_id.
Static Public Member Functions
static void update_volume (ModelVolume *volume, TriangleMesh &&mesh, const TextConfiguration &text_configuration, std::string_view volume_name)
Update text volume.
Private Attributes
DataUpdate m_input
TriangleMesh m_result
Detailed Description
Update text shape in existing text volume Predict that there is only one runnig(not canceled) instance of it.
Constructor & Destructor Documentation
UpdateJob()
UpdateJob::UpdateJob (DataUpdate && input)
Update Volume.
    : m_input(std::move(input))
{
    assert(priv::check(m_input, true));
}
References priv::check(), and m_input.
Member Function Documentation
finalize()
void UpdateJob::finalize (bool canceled, std::exception_ptr & eptr) override virtual
Update volume - change object_id.
Parameters
canceled Was process canceled. NOTE: Be carefull it doesn't care about time between finished process and started finalize part.
unused
Reimplemented from Slic3r::GUI::Job.
{
    if (!priv::finalize(canceled, eptr, m_input))
        return;
    priv::update_volume(std::move(m_result), m_input);
}
References priv::finalize(), m_input, m_result, and priv::update_volume().
process()
void UpdateJob::process (Ctl & ctl) override virtual
Create new embossed volume by m_input data and store to m_result.
Parameters
ctl Control containing cancel flag
Implements Slic3r::GUI::Job.
{
    if (!priv::check(m_input))
        throw std::runtime_error("Bad input data for EmbossUpdateJob.");
    auto was_canceled = [&ctl, &cancel = m_input.cancel]()->bool {
        if (cancel->load()) return true;
        return ctl.was_canceled();
    };
    m_result = priv::try_create_mesh(m_input, was_canceled);
    if (was_canceled()) return;
    if (m_result.its.empty())
        throw priv::JobException("Created text volume is empty. Change text or font.");
    // center triangle mesh
    Vec3d shift = m_result.bounding_box().center();
    m_result.translate(-shift.cast<float>());
}
References Slic3r::TriangleMesh::bounding_box(), Slic3r::GUI::Emboss::DataBase::cancel, Slic3r::BoundingBox3Base< PointType >::center(), priv::check(), indexed_triangle_set::empty(), Slic3r::TriangleMesh::its, m_input, m_result, Slic3r::TriangleMesh::translate(), priv::try_create_mesh(), and Slic3r::GUI::Job::Ctl::was_canceled().
update_volume()
void UpdateJob::update_volume (ModelVolume * volume, TriangleMesh && mesh, const TextConfiguration & text_configuration, std::string_view volume_name) static
Update text volume.
Parameters
volume Volume to be updated
mesh New Triangle mesh for volume
text_configuration Parametric description of volume
volume_name Name of volume
{
    // check inputs
    bool is_valid_input =
        volume != nullptr &&
        !mesh.empty() &&
        !volume_name.empty();
    assert(is_valid_input);
    if (!is_valid_input) return;
    // update volume
    volume->set_mesh(std::move(mesh));
    volume->set_new_unique_id();
    volume->calculate_convex_hull();
    volume->get_object()->invalidate_bounding_box();
    volume->text_configuration = text_configuration;
    // discard information about rotation, should not be stored in volume
    volume->text_configuration->style.prop.angle.reset();
    GUI_App &app = wxGetApp(); // may be move ObjectList and Plater to input?
    // update volume name in right panel( volume / object name)
    if (volume->name != volume_name) {
        volume->name = volume_name;
        update_volume_name(*volume, app.obj_list());
    }
    // When text is object.
    // When text positive volume is lowest part of object than modification of text
    // have to move object on bed.
    if (volume->type() == ModelVolumeType::MODEL_PART)
        volume->get_object()->ensure_on_bed();
    // redraw scene
    Plater *plater = app.plater();
    if (plater == nullptr)
        return;
    // Update Model and redraw scene
    plater->update();
}
References Slic3r::MODEL_PART, Slic3r::GUI::GUI_App::obj_list(), Slic3r::GUI::GUI_App::plater(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::update().
Referenced by priv::update_volume().
Member Data Documentation
m_input
DataUpdate Slic3r::GUI::Emboss::UpdateJob::m_input private
Referenced by UpdateJob(), finalize(), and process().
m_result
TriangleMesh Slic3r::GUI::Emboss::UpdateJob::m_result private
Referenced by finalize(), and process().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/EmbossJob.hpp
src/slic3r/GUI/Jobs/EmbossJob.cpp