Prusa Slicer: igl::xml Namespace Reference
igl::xml Namespace Reference
Namespaces
namespace serialization_xml
Classes
class XMLSerializable
struct XMLSerializableBase
Functions
IGL_INLINE bool save_ReAntTweakBar (::igl::anttweakbar::ReTwBar *bar, const char *file_name)
IGL_INLINE bool load_ReAntTweakBar (::igl::anttweakbar::ReTwBar *bar, const char *file_name)
template<typename T >
IGL_INLINE void serialize_xml (const T &obj, const std::string &filename)
template<typename T >
IGL_INLINE void serialize_xml (const T &obj, const std::string &objectName, const std::string &filename, bool binary, bool overwrite)
template<typename T >
IGL_INLINE void serialize_xml (const T &obj, const std::string &objectName, tinyxml2::XMLDocument *doc, tinyxml2::XMLElement *element, bool binary)
template<typename T >
IGL_INLINE void deserialize_xml (T &obj, const std::string &filename)
template<typename T >
IGL_INLINE void deserialize_xml (T &obj, const std::string &objectName, const std::string &filename)
template<typename T >
IGL_INLINE void deserialize_xml (T &obj, const std::string &objectName, const tinyxml2::XMLDocument *doc, const tinyxml2::XMLElement *element)
template<typename DerivedV , typename DerivedF >
IGL_INLINE bool write_triangle_mesh (const std::string str, const Eigen::PlainObjectBase< DerivedV > &V, const Eigen::PlainObjectBase< DerivedF > &F, const bool ascii=true)
template<typename DerivedV , typename DerivedF >
IGL_INLINE bool writeDAE (const std::string &filename, const Eigen::PlainObjectBase< DerivedV > &V, const Eigen::PlainObjectBase< DerivedF > &F)
Function Documentation
deserialize_xml() [1/3]
template<typename T > IGL_INLINE void igl::xml::deserialize_xml (T & obj, const std::string & filename)
    {
      deserialize_xml(obj,"object",filename);
    }
References deserialize_xml().
Referenced by igl::xml::XMLSerializable::XMLSerializationObject< T >::Deserialize(), deserialize_xml(), and deserialize_xml().
deserialize_xml() [2/3]
template<typename T > IGL_INLINE void igl::xml::deserialize_xml (T & obj, const std::string & objectName, const std::string & filename)
    {
      tinyxml2::XMLDocument* doc = new tinyxml2::XMLDocument();
      tinyxml2::XMLError error = doc->LoadFile(filename.c_str());
      if(error != tinyxml2::XML_SUCCESS)
      {
        std::cerr << "File not found!" << std::endl;
        doc->PrintError();
        doc = NULL;
      }
      else
      {
        tinyxml2::XMLElement* element = doc->FirstChildElement("serialization");
        if(element == NULL)
        {
          std::cerr << "Name of object not found! Initialized with default value." << std::endl;
          obj = T();
        }
        else
        {
          deserialize_xml(obj,objectName,doc,element);
        }
        delete doc;
      }
    }
References deserialize_xml(), and error.
deserialize_xml() [3/3]
template<typename T > IGL_INLINE void igl::xml::deserialize_xml (T & obj, const std::string & objectName, const tinyxml2::XMLDocument * doc, const tinyxml2::XMLElement * element)
    {
      static_assert(serialization::is_serializable<T>::value,"'igl::xml::deserialize_xml': type is not deserializable");
      std::string name(objectName);
      serialization_xml::encodeXMLElementName(name);
      const tinyxml2::XMLElement* child = element->FirstChildElement(name.c_str());
      if(child != NULL)
      {
        bool isBinary = false;
        const tinyxml2::XMLAttribute* attr = child->FindAttribute("binary");
        if(attr != NULL)
        {
          std::string code;
          serialization_xml::deserialize(code,doc,element,name);
          std::string decoded = serialization_xml::base64_decode(code);
          std::vector<char> buffer;
          std::copy(decoded.c_str(),decoded.c_str()+decoded.length(),std::back_inserter(buffer));
          deserialize(obj,name,buffer);
        }
        else
        {
          serialization_xml::deserialize(obj,doc,element,name);
        }
      }
    }
References igl::xml::serialization_xml::base64_decode(), igl::deserialize(), igl::xml::serialization_xml::deserialize(), and igl::xml::serialization_xml::encodeXMLElementName().
load_ReAntTweakBar()
IGL_INLINE bool igl::xml::load_ReAntTweakBar (::igl::anttweakbar::ReTwBar * bar, const char * file_name)
    {
      char type_str[REANTTWEAKBAR_MAX_WORD];
      char value_str[REANTTWEAKBAR_MAX_WORD];
      TwType type;
      const char * name_chars = TwGetBarName(bar->bar);
      std::string name = std::string(name_chars) + "_AntTweakBar";
      const std::vector< ::igl::anttweakbar::ReTwRWItem>& rw_items = bar->get_rw_items();
      for(std::vector< ::igl::anttweakbar::ReTwRWItem>::const_iterator it = rw_items.begin(); it != rw_items.end(); it++)
      {
        char* val;
        //::igl::XMLSerializer::LoadObject(val,it->name,name,file_name);
        ::igl::deserialize_xml(val,it->name,file_name);
        sscanf(val,"%s %[^\n]",type_str,value_str);
        if(!bar->type_from_string(type_str,type))
        {
          printf("ERROR: %s type not found... Skipping...\n",type_str);
          continue;
        }
        bar->set_value_from_string(it->name.c_str(),type,value_str);
        delete[] val;
      }
      const std::vector< ::igl::anttweakbar::ReTwCBItem>& cb_items = bar->get_cb_items();
      for(std::vector< ::igl::anttweakbar::ReTwCBItem>::const_iterator it = cb_items.begin(); it != cb_items.end(); it++)
      {
        char* val;
        //::igl::XMLSerializer::LoadObject(val,it->name,name,file_name);
        ::igl::deserialize_xml(val,it->name,file_name);
        sscanf(val,"%s %[^\n]",type_str,value_str);
        if(!bar->type_from_string(type_str,type))
        {
          printf("ERROR: %s type not found... Skipping...\n",type_str);
          continue;
        }
        bar->set_value_from_string(it->name.c_str(),type,value_str);
        delete[] val;
      }
      return true;
    }
References igl::anttweakbar::ReTwBar::bar, igl::anttweakbar::ReTwBar::get_cb_items(), igl::anttweakbar::ReTwBar::get_rw_items(), REANTTWEAKBAR_MAX_WORD, igl::anttweakbar::ReTwBar::set_value_from_string(), and igl::anttweakbar::ReTwBar::type_from_string().
save_ReAntTweakBar()
IGL_INLINE bool igl::xml::save_ReAntTweakBar (::igl::anttweakbar::ReTwBar * bar, const char * file_name)
    {
      const char * name_chars = TwGetBarName(bar->bar);
      std::string name = std::string(name_chars) + "_AntTweakBar";
      const std::vector< ::igl::anttweakbar::ReTwRWItem>& rw_items = bar->get_rw_items();
      for(std::vector< ::igl::anttweakbar::ReTwRWItem>::const_iterator it = rw_items.begin(); it != rw_items.end(); it++)
      {
        std::string val = bar->get_value_as_string(it->var,it->type);
        //::igl::XMLSerializer::SaveObject(val,it->name,name,file_name,false);
        ::igl::serialize_xml(val,it->name,file_name,false,false);
      }
      char var[REANTTWEAKBAR_MAX_CB_VAR_SIZE];
      // Print all CB variables
      const std::vector< ::igl::anttweakbar::ReTwCBItem>& cb_items = bar->get_cb_items();
      for(std::vector< ::igl::anttweakbar::ReTwCBItem>::const_iterator it = cb_items.begin(); it != cb_items.end(); it++)
      {
        TwType type = it->type;
        //TwSetVarCallback setCallback = it->setCallback;
        TwGetVarCallback getCallback = it->getCallback;
        void * clientData = it->clientData;
        // I'm not sure how to do what I want to do. getCallback needs to be sure
        // that it can write to var. So var needs to point to a valid and big
        // enough chunk of memory
        getCallback(var,clientData);
        std::string val = bar->get_value_as_string(var,type);
        //::igl::XMLSerializer::SaveObject(val,it->name,name,file_name,false);
        ::igl::serialize_xml(val,it->name,file_name,false,false);
      }
      return true;
    }
References igl::anttweakbar::ReTwBar::bar, igl::anttweakbar::ReTwBar::get_cb_items(), igl::anttweakbar::ReTwBar::get_rw_items(), igl::anttweakbar::ReTwBar::get_value_as_string(), and REANTTWEAKBAR_MAX_CB_VAR_SIZE.
serialize_xml() [1/3]
template<typename T > IGL_INLINE void igl::xml::serialize_xml (const T & obj, const std::string & filename)
    {
      serialize_xml(obj,"object",filename,false,true);
    }
References serialize_xml().
Referenced by igl::xml::XMLSerializable::XMLSerializationObject< T >::Serialize(), serialize_xml(), and serialize_xml().
serialize_xml() [2/3]
template<typename T > IGL_INLINE void igl::xml::serialize_xml (const T & obj, const std::string & objectName, const std::string & filename, bool binary, bool overwrite)
    {
      tinyxml2::XMLDocument* doc = new tinyxml2::XMLDocument();
      if(overwrite == false)
      {
        // Check if file exists
        tinyxml2::XMLError error = doc->LoadFile(filename.c_str());
        if(error != tinyxml2::XML_SUCCESS)
        {
          doc->Clear();
        }
      }
      tinyxml2::XMLElement* element = doc->FirstChildElement("serialization");
      if(element == NULL)
      {
        element = doc->NewElement("serialization");
        doc->InsertEndChild(element);
      }
      serialize_xml(obj,objectName,doc,element,binary);
      // Save
      tinyxml2::XMLError error = doc->SaveFile(filename.c_str());
      if(error != tinyxml2::XML_SUCCESS)
      {
        doc->PrintError();
      }
      delete doc;
    }
References binary, error, and serialize_xml().
serialize_xml() [3/3]
template<typename T > IGL_INLINE void igl::xml::serialize_xml (const T & obj, const std::string & objectName, tinyxml2::XMLDocument * doc, tinyxml2::XMLElement * element, bool binary)
    {
      static_assert(
        serialization_xml::is_serializable<T>::value,
        "'igl::xml::serialize_xml': type is not serializable");
      std::string name(objectName);
      serialization_xml::encodeXMLElementName(name);
      tinyxml2::XMLElement* child = element->FirstChildElement(name.c_str());
      if(child != NULL)
        element->DeleteChild(child);
      child = doc->NewElement(name.c_str());
      element->InsertEndChild(child);
      if(binary)
      {
        std::vector<char> buffer;
        serialize(obj,name,buffer);
        std::string data =
          serialization_xml::base64_encode(
            reinterpret_cast<const unsigned char*>(
              buffer.data()),buffer.size());
        child->SetAttribute("binary",true);
        serialization_xml::serialize(data,doc,element,name);
      }
      else
      {
        serialization_xml::serialize(obj,doc,element,name);
      }
    }
References igl::xml::serialization_xml::base64_encode(), binary, igl::xml::serialization_xml::encodeXMLElementName(), igl::serialize(), and igl::xml::serialization_xml::serialize().
write_triangle_mesh()
template<typename DerivedV , typename DerivedF > IGL_INLINE bool igl::xml::write_triangle_mesh (const std::string str, const Eigen::PlainObjectBase< DerivedV > & V, const Eigen::PlainObjectBase< DerivedF > & F, const bool ascii = true)
{
  using namespace std;
  // dirname, basename, extension and filename
  string d,b,e,f;
  pathinfo(str,d,b,e,f);
  // Convert extension to lower case
  std::transform(e.begin(), e.end(), e.begin(), ::tolower);
  if(e == "dae")
  {
    return writeDAE(str,V,F);
  }else
  {
    return igl::write_triangle_mesh(str,V,F,ascii);
  }
}
References ascii, igl::pathinfo(), igl::write_triangle_mesh(), and writeDAE().
writeDAE()
template<typename DerivedV , typename DerivedF > IGL_INLINE bool igl::xml::writeDAE (const std::string & filename, const Eigen::PlainObjectBase< DerivedV > & V, const Eigen::PlainObjectBase< DerivedF > & F)
{
  using namespace std;
  using namespace Eigen;
  using namespace tinyxml2;
  XMLDocument* doc = new XMLDocument();
  const auto & ele = [&doc](
    const std::string tag,
    // Can't just use `{}` as the default argument because of a clang-bug
    // http://stackoverflow.com/questions/17264067/
    const std::map<std::string,std::string> attribs =
      std::map<std::string,std::string>(),
    const std::string text="",
    const std::list<XMLElement *> children =
       std::list<XMLElement *>()
    )->XMLElement *
  {
    XMLElement * element = doc->NewElement(tag.c_str());
    for(const auto & key_value :  attribs)
    {
      element->SetAttribute(key_value.first.c_str(),key_value.second.c_str());
    }
    if(!text.empty())
    {
      element->InsertEndChild(doc->NewText(text.c_str()));
    }
    for(auto & child : children)
    {
      element->InsertEndChild(child);
    }
    return element;
  };
  Eigen::IOFormat row_format(Eigen::FullPrecision,0," "," ","","","");
  doc->InsertEndChild(
    ele("COLLADA",
    {
      {"xmlns","http://www.collada.org/2005/11/COLLADASchema"},
      {"version","1.4.1"}
    },
    "",
    {
      ele("asset",{},"",
      {
        ele("unit",{{"meter","0.0254000"},{"name","inch"}}),
        ele("up_axis",{},"Y_UP")
      }),
      ele("library_visual_scenes",{},"",
      {
        ele("visual_scene",{{"id","ID2"}},"",
        {
          ele("node",{{"name","SketchUp"}},"",
          {
            ele("node",{{"id","ID3"},{"name","group_0"}},"",
            {
              ele("matrix",{},"1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"),
              ele("instance_geometry",{{"url","#ID4"}},"",
              {
                ele("bind_material",{},"",{ele("technique_common")}),
              }),
            }),
          }),
        }),
      }),
      ele("library_geometries",{},"",
      {
        ele("geometry",{{"id","ID4"}},"",
        {
          ele("mesh",{},"",
          {
            ele("source",{{"id","ID7"}},"",
            {
              ele(
                "float_array",
                {{"count",STR(V.size())},{"id","ID10"}},
                STR(V.format(row_format))),
              ele("technique_common",{},"",
              {
                ele(
                  "accessor",
                  {{"count",STR(V.rows())},{"source","#ID8"},{"stride","3"}},
                  "",
                {
                  ele("param",{{"name","X"},{"type","float"}}),
                  ele("param",{{"name","Y"},{"type","float"}}),
                  ele("param",{{"name","Z"},{"type","float"}}),
                })
              })
            }),
            ele(
              "vertices",
              {{"id","ID9"}},
              "",
              {ele("input",{{"semantic","POSITION"},{"source","#ID7"}})}),
            ele(
              "triangles",
              {{"count",STR(F.rows())}},
              "",
            {
              ele("input",{{"semantic","VERTEX"},{"source","#ID9"}}),
              ele("p",{},STR(F.format(row_format))),
            })
          })
        })
      }),
      ele("scene",{},"",{ele("instance_visual_scene",{{"url","#ID2"}})}),
    }));
  // tinyxml2 seems **not** to print the <?xml ...?> header by default, but it
  // also seems that that's OK
  XMLError error = doc->SaveFile(filename.c_str());
  bool ret = true;
  if(error != XML_NO_ERROR)
  {
    doc->PrintError();
    ret = false;
  }
  delete doc;
  return ret;
}
References error, Eigen::FullPrecision, Eigen::PlainObjectBase< Derived >::rows(), and STR.
Referenced by write_triangle_mesh().