Prusa Slicer: Slic3r::WipeTower Class Reference
Slic3r::WipeTower Class Reference
#include <src/libslic3r/GCode/WipeTower.hpp>
Classes
struct box_coordinates
struct Extrusion
struct FilamentParameters
struct ToolChangeResult
struct WipeTowerInfo
Public Member Functions
ToolChangeResult construct_tcr (WipeTowerWriter &writer, bool priming, size_t old_tool) const
WipeTower (const PrintConfig &config, const std::vector< std::vector< float > > &wiping_matrix, size_t initial_tool)
void set_extruder (size_t idx, const PrintConfig &config)
void plan_toolchange (float z_par, float layer_height_par, unsigned int old_tool, unsigned int new_tool, float wipe_volume=0.f)
void generate (std::vector< std::vector< ToolChangeResult > > &result)
float get_depth () const
std::vector< std::pair< float, float > > get_z_and_depth_pairs () const
float get_brim_width () const
float get_wipe_tower_height () const
void set_layer (float print_z, float layer_height, size_t max_tool_changes, bool, bool is_last_layer)
const Vec2f & position () const
float width () const
bool finished () const
std::vector< ToolChangeResult > prime (float first_layer_height, const std::vector< unsigned int > &tools, bool last_wipe_inside_wipe_tower)
ToolChangeResult tool_change (size_t new_tool)
ToolChangeResult finish_layer ()
bool layer_finished () const
std::vector< float > get_used_filament () const
int get_number_of_toolchanges () const
Static Public Member Functions
static const std::string never_skip_tag ()
static std::pair< double, double > get_wipe_tower_cone_base (double width, double height, double depth, double angle_deg)
static std::vector< std::vector< float > > extract_wipe_volumes (const PrintConfig &config)
Private Types
enum wipe_shape { SHAPE_NORMAL = 1 , SHAPE_REVERSED = -1 }
enum { RectangularBed , CircularBed , CustomBed }
Private Member Functions
float filament_area () const
bool is_first_layer () const
float extrusion_flow (float layer_height=-1.f) const
float volume_to_length (float volume, float line_width, float layer_height) const
void plan_tower ()
void make_wipe_tower_square ()
void save_on_last_wipe ()
int first_toolchange_to_nonsoluble (const std::vector< WipeTowerInfo::ToolChange > &tool_changes) const
void toolchange_Unload (WipeTowerWriter &writer, const box_coordinates &cleaning_box, const std::string &current_material, const int new_temperature)
void toolchange_Change (WipeTowerWriter &writer, const size_t new_tool, const std::string &new_material)
void toolchange_Load (WipeTowerWriter &writer, const box_coordinates &cleaning_box)
void toolchange_Wipe (WipeTowerWriter &writer, const box_coordinates &cleaning_box, float wipe_volume)
Private Attributes
const float Width_To_Nozzle_Ratio = 1.25f
const float WT_EPSILON = 1e-3f
bool m_semm = true
Vec2f m_wipe_tower_pos
float m_wipe_tower_width
float m_wipe_tower_depth = 0.f
float m_wipe_tower_height = 0.f
float m_wipe_tower_cone_angle = 0.f
float m_wipe_tower_brim_width = 0.f
float m_wipe_tower_brim_width_real = 0.f
float m_wipe_tower_rotation_angle = 0.f
float m_internal_rotation = 0.f
float m_y_shift = 0.f
float m_z_pos = 0.f
float m_layer_height = 0.f
size_t m_max_color_changes = 0
int m_old_temperature = -1
float m_travel_speed = 0.f
float m_first_layer_speed = 0.f
size_t m_first_layer_idx = size_t(-1)
float m_cooling_tube_retraction = 0.f
float m_cooling_tube_length = 0.f
float m_parking_pos_retraction = 0.f
float m_extra_loading_move = 0.f
float m_bridging = 0.f
bool m_no_sparse_layers = false
bool m_set_extruder_trimpot = false
bool m_adhesion = true
GCodeFlavor m_gcode_flavor
enum Slic3r::WipeTower:: { ... } m_bed_shape
float m_bed_width
Vec2f m_bed_bottom_left
float m_perimeter_width = 0.4f * Width_To_Nozzle_Ratio
float m_extrusion_flow = 0.038f
std::vector< FilamentParameters > m_filpar
unsigned int m_num_layer_changes = 0
unsigned int m_num_tool_changes = 0
bool m_print_brim = true
unsigned int m_idx_tool_change_in_layer = 0; // Layer change counter in this layer. Counting up to m_max_color_changes.
wipe_shape m_current_shape = SHAPE_NORMAL
size_t m_current_tool = 0
const std::vector< std::vector< float > > wipe_volumes
float m_depth_traversed = 0.f
bool m_current_layer_finished = false
bool m_left_to_right = true
float m_extra_spacing = 1.f
std::vector< WipeTowerInfo > m_plan
std::vector< WipeTowerInfo >::iterator m_layer_info = m_plan.end()
float m_current_height = 0.f
std::vector< float > m_used_filament_length
Detailed Description
Class Documentation
Slic3r::WipeTower::FilamentParameters
struct Slic3r::WipeTower::FilamentParameters
Class Members
float cooling_final_speed = 0.f
float cooling_initial_speed = 0.f
int cooling_moves = 0
float delay = 0.f
float filament_area
int first_layer_temperature = 0
bool is_soluble = false
float loading_speed = 0.f
float loading_speed_start = 0.f
string material = "PLA"
float max_e_speed = std::numeric_limits<float>::max()
float nozzle_diameter
float ramming_line_width_multiplicator = 1.f
vector< float > ramming_speed
float ramming_step_multiplicator = 1.f
int temperature = 0
float unloading_speed = 0.f
float unloading_speed_start = 0.f
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
RectangularBed
CircularBed
CustomBed
         {
        RectangularBed,
        CircularBed,
        CustomBed
    } m_bed_shape;
wipe_shape
enum Slic3r::WipeTower::wipe_shape private
Enumerator
SHAPE_NORMAL
SHAPE_REVERSED
  {
    SHAPE_NORMAL = 1,
    SHAPE_REVERSED = -1
  };
Constructor & Destructor Documentation
WipeTower()
Slic3r::WipeTower::WipeTower (const PrintConfig & config, const std::vector< std::vector< float > > & wiping_matrix, size_t initial_tool)
                                                                                                                     :
    m_semm(config.single_extruder_multi_material.value),
    m_wipe_tower_pos(config.wipe_tower_x, config.wipe_tower_y),
    m_wipe_tower_width(float(config.wipe_tower_width)),
    m_wipe_tower_rotation_angle(float(config.wipe_tower_rotation_angle)),
    m_wipe_tower_brim_width(float(config.wipe_tower_brim_width)),
    m_wipe_tower_cone_angle(float(config.wipe_tower_cone_angle)),
    m_extra_spacing(float(config.wipe_tower_extra_spacing/100.)),
    m_y_shift(0.f),
    m_z_pos(0.f),
    m_bridging(float(config.wipe_tower_bridging)),
    m_no_sparse_layers(config.wipe_tower_no_sparse_layers),
    m_gcode_flavor(config.gcode_flavor),
    m_travel_speed(config.travel_speed),
    m_current_tool(initial_tool),
    wipe_volumes(wiping_matrix)
{
    // Read absolute value of first layer speed, if given as percentage,
    // it is taken over following default. Speeds from config are not
    // easily accessible here.
    const float default_speed = 60.f;
    m_first_layer_speed = config.get_abs_value("first_layer_speed", default_speed);
    if (m_first_layer_speed == 0.f) // just to make sure autospeed doesn't break it.
        m_first_layer_speed = default_speed / 2.f;
    // If this is a single extruder MM printer, we will use all the SE-specific config values.
    // Otherwise, the defaults will be used to turn off the SE stuff.
    if (m_semm) {
        m_cooling_tube_retraction = float(config.cooling_tube_retraction);
        m_cooling_tube_length     = float(config.cooling_tube_length);
        m_parking_pos_retraction  = float(config.parking_pos_retraction);
        m_extra_loading_move      = float(config.extra_loading_move);
        m_set_extruder_trimpot    = config.high_current_on_filament_swap;
    }
    // Calculate where the priming lines should be - very naive test not detecting parallelograms etc.
    const std::vector<Vec2d>& bed_points = config.bed_shape.values;
    BoundingBoxf bb(bed_points);
    m_bed_width = float(bb.size().x());
    m_bed_shape = (bed_points.size() == 4 ? RectangularBed : CircularBed);
    if (m_bed_shape == CircularBed) {
        // this may still be a custom bed, check that the points are roughly on a circle
        double r2 = std::pow(m_bed_width/2., 2.);
        double lim2 = std::pow(m_bed_width/10., 2.);
        Vec2d center = bb.center();
        for (const Vec2d& pt : bed_points)
            if (std::abs(std::pow(pt.x()-center.x(), 2.) + std::pow(pt.y()-center.y(), 2.) - r2) > lim2) {
                m_bed_shape = CustomBed;
                break;
            }
    }
    m_bed_bottom_left = m_bed_shape == RectangularBed
                  ? Vec2f(bed_points.front().x(), bed_points.front().y())
                  : Vec2f::Zero();
}
References Slic3r::BoundingBoxBase< PointType, APointsType >::center(), CircularBed, CustomBed, m_bed_bottom_left, m_bed_shape, m_bed_width, m_cooling_tube_length, m_cooling_tube_retraction, m_extra_loading_move, m_first_layer_speed, m_parking_pos_retraction, m_semm, m_set_extruder_trimpot, RectangularBed, and Slic3r::BoundingBoxBase< PointType, APointsType >::size().
Member Function Documentation
construct_tcr()
WipeTower::ToolChangeResult Slic3r::WipeTower::construct_tcr (WipeTowerWriter & writer, bool priming, size_t old_tool) const
{
    ToolChangeResult result;
    result.priming      = priming;
    result.initial_tool = int(old_tool);
    result.new_tool     = int(m_current_tool);
    result.print_z      = m_z_pos;
    result.layer_height = m_layer_height;
    result.elapsed_time = writer.elapsed_time();
    result.start_pos    = writer.start_pos_rotated();
    result.end_pos      = priming ? writer.pos() : writer.pos_rotated();
    result.gcode        = std::move(writer.gcode());
    result.extrusions   = std::move(writer.extrusions());
    result.wipe_path    = std::move(writer.wipe_path());
    return result;
}
References Slic3r::WipeTowerWriter::elapsed_time(), Slic3r::WipeTower::ToolChangeResult::elapsed_time, Slic3r::WipeTower::ToolChangeResult::end_pos, Slic3r::WipeTowerWriter::extrusions(), Slic3r::WipeTower::ToolChangeResult::extrusions, Slic3r::WipeTowerWriter::gcode(), Slic3r::WipeTower::ToolChangeResult::gcode, Slic3r::WipeTower::ToolChangeResult::initial_tool, Slic3r::WipeTower::ToolChangeResult::layer_height, m_current_tool, m_layer_height, m_z_pos, Slic3r::WipeTower::ToolChangeResult::new_tool, Slic3r::WipeTowerWriter::pos(), Slic3r::WipeTowerWriter::pos_rotated(), Slic3r::WipeTower::ToolChangeResult::priming, Slic3r::WipeTower::ToolChangeResult::print_z, Slic3r::WipeTower::ToolChangeResult::start_pos, Slic3r::WipeTowerWriter::start_pos_rotated(), Slic3r::WipeTowerWriter::wipe_path(), and Slic3r::WipeTower::ToolChangeResult::wipe_path.
Referenced by finish_layer(), prime(), and tool_change().
extract_wipe_volumes()
std::vector< std::vector< float > > Slic3r::WipeTower::extract_wipe_volumes (const PrintConfig & config) static
{
    // Get wiping matrix to get number of extruders and convert vector<double> to vector<float>:
    std::vector<float> wiping_matrix(cast<float>(config.wiping_volumes_matrix.values));
    // The values shall only be used when SEMM is enabled. The purging for other printers
    // is determined by filament_minimal_purge_on_wipe_tower.
    if (! config.single_extruder_multi_material.value)
        std::fill(wiping_matrix.begin(), wiping_matrix.end(), 0.f);
    // Extract purging volumes for each extruder pair:
    std::vector<std::vector<float>> wipe_volumes;
    const unsigned int number_of_extruders = (unsigned int)(sqrt(wiping_matrix.size())+EPSILON);
    for (unsigned int i = 0; i<number_of_extruders; ++i)
        wipe_volumes.push_back(std::vector<float>(wiping_matrix.begin()+i*number_of_extruders, wiping_matrix.begin()+(i+1)*number_of_extruders));
    // Also include filament_minimal_purge_on_wipe_tower. This is needed for the preview.
    for (unsigned int i = 0; i<number_of_extruders; ++i)
        for (unsigned int j = 0; j<number_of_extruders; ++j)
            wipe_volumes[i][j] = std::max<float>(wipe_volumes[i][j], config.filament_minimal_purge_on_wipe_tower.get_at(j));
    return wipe_volumes;
}
References EPSILON, sqrt(), and wipe_volumes.
Referenced by Slic3r::Print::_make_wipe_tower(), and Slic3r::Print::wipe_tower_data().
extrusion_flow()
float Slic3r::WipeTower::extrusion_flow (float layer_height = -1.f) const inline private
  {
    if ( layer_height < 0 )
      return m_extrusion_flow;
    return layer_height * ( m_perimeter_width - layer_height * (1.f-float(M_PI)/4.f)) / filament_area();
  }
References filament_area(), Slic3r::layer_height(), m_extrusion_flow, m_perimeter_width, and M_PI.
Referenced by set_layer().
filament_area()
float Slic3r::WipeTower::filament_area () const inline private
{
        return m_filpar[0].filament_area; // all extruders are assumed to have the same filament diameter at this point
    }
References m_filpar.
Referenced by extrusion_flow(), set_extruder(), and toolchange_Unload().
finish_layer()
WipeTower::ToolChangeResult Slic3r::WipeTower::finish_layer ()
{
  assert(! this->layer_finished());
    m_current_layer_finished = true;
    size_t old_tool = m_current_tool;
  WipeTowerWriter writer(m_layer_height, m_perimeter_width, m_gcode_flavor, m_filpar);
  writer.set_extrusion_flow(m_extrusion_flow)
    .set_z(m_z_pos)
    .set_initial_tool(m_current_tool)
        .set_y_shift(m_y_shift - (m_current_shape == SHAPE_REVERSED ? m_layer_info->toolchanges_depth() : 0.f));
  // Slow down on the 1st layer.
    bool first_layer = is_first_layer();
    float feedrate = first_layer ? m_first_layer_speed * 60.f : 2900.f;
  float current_depth = m_layer_info->depth - m_layer_info->toolchanges_depth();
    box_coordinates fill_box(Vec2f(m_perimeter_width, m_layer_info->depth-(current_depth-m_perimeter_width)),
                             m_wipe_tower_width - 2 * m_perimeter_width, current_depth-m_perimeter_width);
    writer.set_initial_position((m_left_to_right ? fill_box.ru : fill_box.lu), // so there is never a diagonal travel
                                 m_wipe_tower_width, m_wipe_tower_depth, m_internal_rotation);
    bool toolchanges_on_layer = m_layer_info->toolchanges_depth() > WT_EPSILON;
    box_coordinates wt_box(Vec2f(0.f, (m_current_shape == SHAPE_REVERSED ? m_layer_info->toolchanges_depth() : 0.f)),
                        m_wipe_tower_width, m_layer_info->depth + m_perimeter_width);
    // inner perimeter of the sparse section, if there is space for it:
    if (fill_box.ru.y() - fill_box.rd.y() > m_perimeter_width - WT_EPSILON)
        writer.rectangle(fill_box.ld, fill_box.rd.x()-fill_box.ld.x(), fill_box.ru.y()-fill_box.rd.y(), feedrate);
    // we are in one of the corners, travel to ld along the perimeter:
    if (writer.x() > fill_box.ld.x()+EPSILON) writer.travel(fill_box.ld.x(),writer.y());
    if (writer.y() > fill_box.ld.y()+EPSILON) writer.travel(writer.x(),fill_box.ld.y());
    // Extrude infill to support the material to be printed above.
    const float dy = (fill_box.lu.y() - fill_box.ld.y() - m_perimeter_width);
    float left = fill_box.lu.x() + 2*m_perimeter_width;
    float right = fill_box.ru.x() - 2 * m_perimeter_width;
    if (dy > m_perimeter_width)
    {
        writer.travel(fill_box.ld + Vec2f(m_perimeter_width * 2, 0.f))
              .append(";--------------------\n"
                      "; CP EMPTY GRID START\n")
              .comment_with_value(" layer #", m_num_layer_changes + 1);
        // Is there a soluble filament wiped/rammed at the next layer?
        // If so, the infill should not be sparse.
        bool solid_infill = m_layer_info+1 == m_plan.end()
                          ? false
                          : std::any_of((m_layer_info+1)->tool_changes.begin(),
                                        (m_layer_info+1)->tool_changes.end(),
                                   [this](const WipeTowerInfo::ToolChange& tch) {
                                       return m_filpar[tch.new_tool].is_soluble
                                           || m_filpar[tch.old_tool].is_soluble;
                                   });
        solid_infill |= first_layer && m_adhesion;
        if (solid_infill) {
            float sparse_factor = 1.5f; // 1=solid, 2=every other line, etc.
            if (first_layer) { // the infill should touch perimeters
                left  -= m_perimeter_width;
                right += m_perimeter_width;
                sparse_factor = 1.f;
            }
            float y = fill_box.ld.y() + m_perimeter_width;
            int n = dy / (m_perimeter_width * sparse_factor);
            float spacing = (dy-m_perimeter_width)/(n-1);
            int i=0;
            for (i=0; i<n; ++i) {
                writer.extrude(writer.x(), y, feedrate)
                      .extrude(i%2 ? left : right, y);
                y = y + spacing;
            }
            writer.extrude(writer.x(), fill_box.lu.y());
        } else {
            // Extrude an inverse U at the left of the region and the sparse infill.
            writer.extrude(fill_box.lu + Vec2f(m_perimeter_width * 2, 0.f), feedrate);
            const int n = 1+int((right-left)/m_bridging);
            const float dx = (right-left)/n;
            for (int i=1;i<=n;++i) {
                float x=left+dx*i;
                writer.travel(x,writer.y());
                writer.extrude(x,i%2 ? fill_box.rd.y() : fill_box.ru.y());
            }
        }
        writer.append("; CP EMPTY GRID END\n"
                      ";------------------\n\n\n\n\n\n\n");
    }
    const float spacing = m_perimeter_width - m_layer_height*float(1.-M_PI_4);
    // This block creates the stabilization cone.
    // First define a lambda to draw the rectangle with stabilization.
    auto supported_rectangle = [this, &writer, spacing](const box_coordinates& wt_box, double feedrate, bool infill_cone) -> Polygon {
        const auto [R, support_scale] = get_wipe_tower_cone_base(m_wipe_tower_width, m_wipe_tower_height, m_wipe_tower_depth, m_wipe_tower_cone_angle);
        double z = m_no_sparse_layers ? (m_current_height + m_layer_info->height) : m_layer_info->z; // the former should actually work in both cases, but let's stay on the safe side (the 2.6.0 is close)
        double r = std::tan(Geometry::deg2rad(m_wipe_tower_cone_angle/2.f)) * (m_wipe_tower_height - z);
        Vec2f center = (wt_box.lu + wt_box.rd) / 2.;
        double w = wt_box.lu.y() - wt_box.ld.y();
        enum Type {
            Arc,
            Corner,
            ArcStart,
            ArcEnd
        };
        // First generate vector of annotated point which form the boundary.
        std::vector<std::pair<Vec2f, Type>> pts = {{wt_box.ru, Corner}};
        if (double alpha_start = std::asin((0.5*w)/r); ! std::isnan(alpha_start) && r > 0.5*w+0.01) {
            for (double alpha = alpha_start; alpha < M_PI-alpha_start+0.001; alpha+=(M_PI-2*alpha_start) / 20.)
                pts.emplace_back(Vec2f(center.x() + r*std::cos(alpha)/support_scale, center.y() + r*std::sin(alpha)), alpha == alpha_start ? ArcStart : Arc);
            pts.back().second = ArcEnd;
        }
        pts.emplace_back(wt_box.lu, Corner);
        pts.emplace_back(wt_box.ld, Corner);
        for (int i=int(pts.size())-3; i>0; --i)
            pts.emplace_back(Vec2f(pts[i].first.x(), 2*center.y()-pts[i].first.y()), i == int(pts.size())-3 ? ArcStart : i == 1 ? ArcEnd : Arc);
        pts.emplace_back(wt_box.rd, Corner);
        // Create a Polygon from the points.
        Polygon poly;
        for (const auto& [pt, tag] : pts)
            poly.points.push_back(Point::new_scale(pt));
        // Prepare polygons to be filled by infill.
        Polylines polylines;
        if (infill_cone && m_wipe_tower_width > 2*spacing && m_wipe_tower_depth > 2*spacing) {
            ExPolygons infill_areas;
            ExPolygon wt_contour(poly);
            Polygon wt_rectangle(Points{Point::new_scale(wt_box.ld), Point::new_scale(wt_box.rd), Point::new_scale(wt_box.ru), Point::new_scale(wt_box.lu)});
            wt_rectangle = offset(wt_rectangle, scale_(-spacing/2.)).front();
            wt_contour = offset_ex(wt_contour, scale_(-spacing/2.)).front();
            infill_areas = diff_ex(wt_contour, wt_rectangle);
            if (infill_areas.size() == 2) {
                ExPolygon& bottom_expoly = infill_areas.front().contour.points.front().y() < infill_areas.back().contour.points.front().y() ? infill_areas[0] : infill_areas[1];
                std::unique_ptr<Fill> filler(Fill::new_from_type(ipMonotonicLines));
                filler->angle = Geometry::deg2rad(45.f);
                filler->spacing = spacing;
                FillParams params;
                params.density = 1.f;
                Surface surface(stBottom, bottom_expoly);
                filler->bounding_box = get_extents(bottom_expoly);
                polylines = filler->fill_surface(&surface, params);
                if (! polylines.empty()) {
                    if (polylines.front().points.front().x() > polylines.back().points.back().x()) {
                        std::reverse(polylines.begin(), polylines.end());
                        for (Polyline& p : polylines)
                            p.reverse();
                    }
                }
            }
        }
        // Find the closest corner and travel to it.
        int start_i = 0;
        double min_dist = std::numeric_limits<double>::max();
        for (int i=0; i<int(pts.size()); ++i) {
            if (pts[i].second == Corner) {
                double dist = (pts[i].first - Vec2f(writer.x(), writer.y())).squaredNorm();
                if (dist < min_dist) {
                    min_dist = dist;
                    start_i = i;
                }
            }
        }
        writer.travel(pts[start_i].first);
        // Now actually extrude the boundary (and possibly infill):
        int i = start_i+1 == int(pts.size()) ? 0 : start_i + 1;
        while (i != start_i) {
            writer.extrude(pts[i].first, feedrate);
            if (pts[i].second == ArcEnd) {
                // Extrude the infill.
                if (! polylines.empty()) {
                    // Extrude the infill and travel back to where we were.
                    bool mirror = ((pts[i].first.y() - center.y()) * (unscale(polylines.front().points.front()).y() - center.y())) < 0.;
                    for (const Polyline& line : polylines) {
                        writer.travel(center - (mirror ? 1.f : -1.f) * (unscale(line.points.front()).cast<float>() - center));
                        for (size_t i=0; i<line.points.size(); ++i)
                            writer.extrude(center - (mirror ? 1.f : -1.f) * (unscale(line.points[i]).cast<float>() - center));
                    }
                    writer.travel(pts[i].first);
                }
            }
            if (++i == int(pts.size()))
                i = 0;
        }
        writer.extrude(pts[start_i].first, feedrate);
        return poly;
    };
    // outer contour (always)
    bool infill_cone = first_layer && m_wipe_tower_width > 2*spacing && m_wipe_tower_depth > 2*spacing;
    Polygon poly = supported_rectangle(wt_box, feedrate, infill_cone);
    // brim (first layer only)
    if (first_layer) {
        size_t loops_num = (m_wipe_tower_brim_width + spacing/2.f) / spacing;
        for (size_t i = 0; i < loops_num; ++ i) {
            poly = offset(poly, scale_(spacing)).front();
            int cp = poly.closest_point_index(Point::new_scale(writer.x(), writer.y()));
            writer.travel(unscale(poly.points[cp]).cast<float>());
            for (int i=cp+1; true; ++i ) {
                if (i==int(poly.points.size()))
                    i = 0;
                writer.extrude(unscale(poly.points[i]).cast<float>());
                if (i == cp)
                    break;
            }
        }
        // Save actual brim width to be later passed to the Print object, which will use it
        // for skirt calculation and pass it to GLCanvas for precise preview box
        m_wipe_tower_brim_width_real = loops_num * spacing;
    }
    // Now prepare future wipe.
    int i = poly.closest_point_index(Point::new_scale(writer.x(), writer.y()));
    writer.add_wipe_point(writer.pos());
    writer.add_wipe_point(unscale(poly.points[i==0 ? int(poly.points.size())-1 : i-1]).cast<float>());
    // Ask our writer about how much material was consumed.
    // Skip this in case the layer is sparse and config option to not print sparse layers is enabled.
    if (! m_no_sparse_layers || toolchanges_on_layer || first_layer) {
        if (m_current_tool < m_used_filament_length.size())
            m_used_filament_length[m_current_tool] += writer.get_and_reset_used_filament_length();
        m_current_height += m_layer_info->height;
    }
    return construct_tcr(writer, false, old_tool);
}
References Slic3r::WipeTowerWriter::add_wipe_point(), Slic3r::WipeTowerWriter::append(), Slic3r::append(), Slic3r::MultiPoint::closest_point_index(), construct_tcr(), Slic3r::ExPolygon::contour, Slic3r::Geometry::deg2rad(), Slic3r::FillParams::density, Slic3r::diff_ex(), EPSILON, Slic3r::WipeTowerWriter::extrude(), Slic3r::WipeTowerWriter::get_and_reset_used_filament_length(), Slic3r::get_extents(), get_wipe_tower_cone_base(), Slic3r::ipMonotonicLines, is_first_layer(), layer_finished(), Slic3r::WipeTower::box_coordinates::ld, Slic3r::WipeTower::box_coordinates::lu, m_adhesion, m_bridging, m_current_height, m_current_layer_finished, m_current_shape, m_current_tool, m_extrusion_flow, m_filpar, m_first_layer_speed, m_gcode_flavor, m_internal_rotation, m_layer_height, m_layer_info, m_left_to_right, m_no_sparse_layers, m_num_layer_changes, m_perimeter_width, M_PI, m_plan, m_used_filament_length, m_wipe_tower_brim_width, m_wipe_tower_brim_width_real, m_wipe_tower_cone_angle, m_wipe_tower_depth, m_wipe_tower_height, m_wipe_tower_width, m_y_shift, m_z_pos, Slic3r::Fill::new_from_type(), Slic3r::offset(), Slic3r::offset_ex(), Slic3r::MultiPoint::points, Slic3r::WipeTowerWriter::pos(), Slic3r::WipeTower::box_coordinates::rd, Slic3r::WipeTowerWriter::rectangle(), Slic3r::WipeTower::box_coordinates::ru, scale_, Slic3r::WipeTowerWriter::set_extrusion_flow(), Slic3r::WipeTowerWriter::set_initial_position(), Slic3r::WipeTowerWriter::set_initial_tool(), Slic3r::WipeTowerWriter::set_y_shift(), Slic3r::WipeTowerWriter::set_z(), SHAPE_REVERSED, Slic3r::stBottom, Slic3r::WipeTowerWriter::travel(), Slic3r::unscale(), WT_EPSILON, Slic3r::WipeTowerWriter::x(), and Slic3r::WipeTowerWriter::y().
Referenced by generate(), and save_on_last_wipe().
finished()
bool Slic3r::WipeTower::finished () const inline
{ return m_max_color_changes == 0; }
References m_max_color_changes.
first_toolchange_to_nonsoluble()
int Slic3r::WipeTower::first_toolchange_to_nonsoluble (const std::vector< WipeTowerInfo::ToolChange > & tool_changes) const private
{
    for (size_t idx=0; idx<tool_changes.size(); ++idx)
        if (! m_filpar[tool_changes[idx].new_tool].is_soluble)
            return idx;
    return -1;
}
References m_filpar.
Referenced by generate(), and save_on_last_wipe().
generate()
void Slic3r::WipeTower::generate (std::vector< std::vector< ToolChangeResult > > & result)
{
  if (m_plan.empty())
        return;
  plan_tower();
    for (int i=0;i<5;++i) {
        save_on_last_wipe();
        plan_tower();
    }
    m_layer_info = m_plan.begin();
    m_current_height = 0.f;
    // we don't know which extruder to start with - we'll set it according to the first toolchange
    for (const auto& layer : m_plan) {
        if (!layer.tool_changes.empty()) {
            m_current_tool = layer.tool_changes.front().old_tool;
            break;
        }
    }
    for (auto& used : m_used_filament_length) // reset used filament stats
        used = 0.f;
    m_old_temperature = -1; // reset last temperature written in the gcode
    std::vector<WipeTower::ToolChangeResult> layer_result;
  for (const WipeTower::WipeTowerInfo& layer : m_plan)
  {
        set_layer(layer.z, layer.height, 0, false/*layer.z == m_plan.front().z*/, layer.z == m_plan.back().z);
        m_internal_rotation += 180.f;
        if (m_layer_info->depth < m_wipe_tower_depth - m_perimeter_width)
      m_y_shift = (m_wipe_tower_depth-m_layer_info->depth-m_perimeter_width)/2.f;
        int idx = first_toolchange_to_nonsoluble(layer.tool_changes);
        ToolChangeResult finish_layer_tcr;
        if (idx == -1) {
            // if there is no toolchange switching to non-soluble, finish layer
            // will be called at the very beginning. That's the last possibility
            // where a nonsoluble tool can be.
            finish_layer_tcr = finish_layer();
        }
        for (int i=0; i<int(layer.tool_changes.size()); ++i) {
            layer_result.emplace_back(tool_change(layer.tool_changes[i].new_tool));
            if (i == idx) // finish_layer will be called after this toolchange
                finish_layer_tcr = finish_layer();
        }
        if (layer_result.empty()) {
            // there is nothing to merge finish_layer with
            layer_result.emplace_back(std::move(finish_layer_tcr));
        }
        else {
            if (idx == -1) {
                layer_result[0] = merge_tcr(finish_layer_tcr, layer_result[0]);
                layer_result[0].force_travel = true;
            }
            else
                layer_result[idx] = merge_tcr(layer_result[idx], finish_layer_tcr);
        }
    result.emplace_back(std::move(layer_result));
  }
}
References finish_layer(), first_toolchange_to_nonsoluble(), m_current_height, m_current_tool, m_internal_rotation, m_layer_info, m_old_temperature, m_perimeter_width, m_plan, m_used_filament_length, m_wipe_tower_depth, m_y_shift, Slic3r::merge_tcr(), plan_tower(), save_on_last_wipe(), set_layer(), and tool_change().
Referenced by Slic3r::Print::_make_wipe_tower().
get_brim_width()
float Slic3r::WipeTower::get_brim_width () const inline
{ return m_wipe_tower_brim_width_real; }
References m_wipe_tower_brim_width_real.
Referenced by Slic3r::Print::_make_wipe_tower().
get_depth()
float Slic3r::WipeTower::get_depth () const inline
{ return m_wipe_tower_depth; }
References m_wipe_tower_depth.
Referenced by Slic3r::Print::_make_wipe_tower().
get_number_of_toolchanges()
int Slic3r::WipeTower::get_number_of_toolchanges () const inline
{ return m_num_tool_changes; }
References m_num_tool_changes.
Referenced by Slic3r::Print::_make_wipe_tower().
get_used_filament()
std::vector< float > Slic3r::WipeTower::get_used_filament () const inline
{ return m_used_filament_length; }
References m_used_filament_length.
Referenced by Slic3r::Print::_make_wipe_tower().
get_wipe_tower_cone_base()
std::pair< double, double > Slic3r::WipeTower::get_wipe_tower_cone_base (double width, double height, double depth, double angle_deg) static
{
    double R = std::tan(Geometry::deg2rad(angle_deg/2.)) * height;
    double fake_width = 0.66 * width;
    double diag = std::hypot(fake_width / 2., depth / 2.);
    double support_scale = 1.;
    if (R > diag) {
        double w = fake_width;
        double sin = 0.5 * depth / diag;
        double tan = depth / w;
        double t = (R - diag) * sin;
        support_scale = (w / 2. + t / tan + t * tan) / (w / 2.);
    }
    return std::make_pair(R, support_scale);
}
References Slic3r::Geometry::deg2rad(), sin(), tan(), and width().
Referenced by finish_layer(), Slic3r::Print::first_layer_wipe_tower_corners(), Slic3r::FakeWipeTower::getFakeExtrusionPathsFromWipeTower(), and Slic3r::GLVolumeCollection::load_wipe_tower_preview().
get_wipe_tower_height()
float Slic3r::WipeTower::get_wipe_tower_height () const inline
{ return m_wipe_tower_height; }
References m_wipe_tower_height.
Referenced by Slic3r::Print::_make_wipe_tower().
get_z_and_depth_pairs()
std::vector< std::pair< float, float > > Slic3r::WipeTower::get_z_and_depth_pairs () const
{
    std::vector<std::pair<float, float>> out = {{0.f, m_wipe_tower_depth}};
    for (const WipeTowerInfo& wti : m_plan) {
        assert(wti.depth < wti.depth + WT_EPSILON);
        if (wti.depth < out.back().second - WT_EPSILON)
            out.emplace_back(wti.z, wti.depth);
    }
    if (out.back().first < m_wipe_tower_height - WT_EPSILON)
        out.emplace_back(m_wipe_tower_height, 0.f);
    return out;
}
References m_plan, m_wipe_tower_depth, m_wipe_tower_height, and WT_EPSILON.
Referenced by Slic3r::Print::_make_wipe_tower().
is_first_layer()
bool Slic3r::WipeTower::is_first_layer () const inline private
{ return size_t(m_layer_info - m_plan.begin()) == m_first_layer_idx; }
References m_first_layer_idx, m_layer_info, and m_plan.
Referenced by finish_layer(), set_layer(), tool_change(), toolchange_Unload(), and toolchange_Wipe().
layer_finished()
bool Slic3r::WipeTower::layer_finished () const inline
{
        return m_current_layer_finished;
  }
References m_current_layer_finished.
Referenced by Slic3r::Print::_make_wipe_tower(), and finish_layer().
make_wipe_tower_square()
void Slic3r::WipeTower::make_wipe_tower_square () private
never_skip_tag()
static const std::string Slic3r::WipeTower::never_skip_tag () inline static
{ return "_GCODE_WIPE_TOWER_NEVER_SKIP_TAG"; }
Referenced by Slic3r::WipeTowerIntegration::post_process_wipe_tower_moves(), and toolchange_Change().
plan_toolchange()
void Slic3r::WipeTower::plan_toolchange (float z_par, float layer_height_par, unsigned int old_tool, unsigned int new_tool, float wipe_volume = 0.f)
{
  assert(m_plan.empty() || m_plan.back().z <= z_par + WT_EPSILON);  // refuses to add a layer below the last one
  if (m_plan.empty() || m_plan.back().z + WT_EPSILON < z_par) // if we moved to a new layer, we'll add it to m_plan first
    m_plan.push_back(WipeTowerInfo(z_par, layer_height_par));
    if (m_first_layer_idx == size_t(-1) && (! m_no_sparse_layers || old_tool != new_tool || m_plan.size() == 1))
        m_first_layer_idx = m_plan.size() - 1;
    if (old_tool == new_tool) // new layer without toolchanges - we are done
        return;
  // this is an actual toolchange - let's calculate depth to reserve on the wipe tower
    float depth = 0.f;
  float width = m_wipe_tower_width - 3*m_perimeter_width;
  float length_to_extrude = volume_to_length(0.25f * std::accumulate(m_filpar[old_tool].ramming_speed.begin(), m_filpar[old_tool].ramming_speed.end(), 0.f),
                    m_perimeter_width * m_filpar[old_tool].ramming_line_width_multiplicator,
                    layer_height_par);
  depth = (int(length_to_extrude / width) + 1) * (m_perimeter_width * m_filpar[old_tool].ramming_line_width_multiplicator * m_filpar[old_tool].ramming_step_multiplicator);
    float ramming_depth = depth;
    length_to_extrude = width*((length_to_extrude / width)-int(length_to_extrude / width)) - width;
    float first_wipe_line = -length_to_extrude;
    length_to_extrude += volume_to_length(wipe_volume, m_perimeter_width, layer_height_par);
    length_to_extrude = std::max(length_to_extrude,0.f);
  depth += (int(length_to_extrude / width) + 1) * m_perimeter_width;
  depth *= m_extra_spacing;
  m_plan.back().tool_changes.push_back(WipeTowerInfo::ToolChange(old_tool, new_tool, depth, ramming_depth, first_wipe_line, wipe_volume));
}
References m_extra_spacing, m_filpar, m_first_layer_idx, m_no_sparse_layers, m_perimeter_width, m_plan, m_wipe_tower_width, volume_to_length(), width(), and WT_EPSILON.
Referenced by Slic3r::Print::_make_wipe_tower().
plan_tower()
void Slic3r::WipeTower::plan_tower () private
{
  // Calculate m_wipe_tower_depth (maximum depth for all the layers) and propagate depths downwards
  m_wipe_tower_depth = 0.f;
  for (auto& layer : m_plan)
    layer.depth = 0.f;
    m_wipe_tower_height = m_plan.empty() ? 0.f : m_plan.back().z;
    m_current_height = 0.f;
    for (int layer_index = int(m_plan.size()) - 1; layer_index >= 0; --layer_index)
  {
    float this_layer_depth = std::max(m_plan[layer_index].depth, m_plan[layer_index].toolchanges_depth());
    m_plan[layer_index].depth = this_layer_depth;
    if (this_layer_depth > m_wipe_tower_depth - m_perimeter_width)
      m_wipe_tower_depth = this_layer_depth + m_perimeter_width;
    for (int i = layer_index - 1; i >= 0 ; i--)
    {
      if (m_plan[i].depth - this_layer_depth < 2*m_perimeter_width )
        m_plan[i].depth = this_layer_depth;
    }
  }
}
References m_current_height, m_perimeter_width, m_plan, m_wipe_tower_depth, and m_wipe_tower_height.
Referenced by generate().
position()
const Vec2f & Slic3r::WipeTower::position () const inline
{ return m_wipe_tower_pos; }
References m_wipe_tower_pos.
Referenced by Slic3r::Print::_make_wipe_tower().
prime()
std::vector< WipeTower::ToolChangeResult > Slic3r::WipeTower::prime (float first_layer_height, const std::vector< unsigned int > & tools, bool last_wipe_inside_wipe_tower)
{
  this->set_layer(first_layer_height, first_layer_height, tools.size(), true, false);
  m_current_tool    = tools.front();
    // The Prusa i3 MK2 has a working space of [0, -2.2] to [250, 210].
    // Due to the XYZ calibration, this working space may shrink slightly from all directions,
    // therefore the homing position is shifted inside the bed by 0.2 in the firmware to [0.2, -2.0].
//  box_coordinates cleaning_box(xy(0.5f, - 1.5f), m_wipe_tower_width, wipe_area);
    float prime_section_width = std::min(0.9f * m_bed_width / tools.size(), 60.f);
    box_coordinates cleaning_box(Vec2f(0.02f * m_bed_width, 0.01f + m_perimeter_width/2.f), prime_section_width, 100.f);
    if (m_bed_shape == CircularBed) {
        cleaning_box = box_coordinates(Vec2f(0.f, 0.f), prime_section_width, 100.f);
        float total_width_half = tools.size() * prime_section_width / 2.f;
        cleaning_box.translate(-total_width_half, -std::sqrt(std::max(0.f, std::pow(m_bed_width/2, 2.f) - std::pow(1.05f * total_width_half, 2.f))));
    }
    else
        cleaning_box.translate(m_bed_bottom_left);
    std::vector<ToolChangeResult> results;
    // Iterate over all priming toolchanges and push respective ToolChangeResults into results vector.
    for (size_t idx_tool = 0; idx_tool < tools.size(); ++ idx_tool) {
        size_t old_tool = m_current_tool;
        WipeTowerWriter writer(m_layer_height, m_perimeter_width, m_gcode_flavor, m_filpar);
        writer.set_extrusion_flow(m_extrusion_flow)
              .set_z(m_z_pos)
              .set_initial_tool(m_current_tool);
        // This is the first toolchange - initiate priming
        if (idx_tool == 0) {
            writer.append(";--------------------\n"
                          "; CP PRIMING START\n")
                  .append(";--------------------\n")
                  .speed_override_backup()
                  .speed_override(100)
                  .set_initial_position(Vec2f::Zero())  // Always move to the starting position
                  .travel(cleaning_box.ld, 7200);
            if (m_set_extruder_trimpot)
                writer.set_extruder_trimpot(750);       // Increase the extruder driver current to allow fast ramming.
        }
        else
            writer.set_initial_position(results.back().end_pos);
        unsigned int tool = tools[idx_tool];
        m_left_to_right = true;
        toolchange_Change(writer, tool, m_filpar[tool].material); // Select the tool, set a speed override for soluble and flex materials.
        toolchange_Load(writer, cleaning_box); // Prime the tool.
        if (idx_tool + 1 == tools.size()) {
            // Last tool should not be unloaded, but it should be wiped enough to become of a pure color.
            toolchange_Wipe(writer, cleaning_box, wipe_volumes[tools[idx_tool-1]][tool]);
        } else {
            // Ram the hot material out of the melt zone, retract the filament into the cooling tubes and let it cool.
            //writer.travel(writer.x(), writer.y() + m_perimeter_width, 7200);
            toolchange_Wipe(writer, cleaning_box , 20.f);
            box_coordinates box = cleaning_box;
            box.translate(0.f, writer.y() - cleaning_box.ld.y() + m_perimeter_width);
            toolchange_Unload(writer, box , m_filpar[m_current_tool].material, m_filpar[tools[idx_tool + 1]].first_layer_temperature);
            cleaning_box.translate(prime_section_width, 0.f);
            writer.travel(cleaning_box.ld, 7200);
        }
        ++ m_num_tool_changes;
        // Ask our writer about how much material was consumed:
        if (m_current_tool < m_used_filament_length.size())
            m_used_filament_length[m_current_tool] += writer.get_and_reset_used_filament_length();
        // This is the last priming toolchange - finish priming
        if (idx_tool+1 == tools.size()) {
            // Reset the extruder current to a normal value.
            if (m_set_extruder_trimpot)
                writer.set_extruder_trimpot(550);
            writer.speed_override_restore()
                  .feedrate(m_travel_speed * 60.f)
                  .flush_planner_queue()
                  .reset_extruder()
                  .append("; CP PRIMING END\n"
                          ";------------------\n"
                          "\n\n");
        }
        results.emplace_back(construct_tcr(writer, true, old_tool));
    }
    m_old_temperature = -1; // If the priming is turned off in config, the temperature changing commands will not actually appear
                            // in the output gcode - we should not remember emitting them (we will output them twice in the worst case)
  return results;
}
References Slic3r::WipeTowerWriter::append(), CircularBed, construct_tcr(), Slic3r::WipeTowerWriter::feedrate(), Slic3r::WipeTowerWriter::flush_planner_queue(), Slic3r::WipeTowerWriter::get_and_reset_used_filament_length(), Slic3r::WipeTower::box_coordinates::ld, m_bed_bottom_left, m_bed_shape, m_bed_width, m_current_tool, m_extrusion_flow, m_filpar, m_gcode_flavor, m_layer_height, m_left_to_right, m_num_tool_changes, m_old_temperature, m_perimeter_width, m_set_extruder_trimpot, m_travel_speed, m_used_filament_length, m_z_pos, Slic3r::WipeTowerWriter::reset_extruder(), Slic3r::WipeTowerWriter::set_extruder_trimpot(), Slic3r::WipeTowerWriter::set_extrusion_flow(), Slic3r::WipeTowerWriter::set_initial_position(), Slic3r::WipeTowerWriter::set_initial_tool(), set_layer(), Slic3r::WipeTowerWriter::set_z(), Slic3r::WipeTowerWriter::speed_override(), Slic3r::WipeTowerWriter::speed_override_backup(), Slic3r::WipeTowerWriter::speed_override_restore(), toolchange_Change(), toolchange_Load(), toolchange_Unload(), toolchange_Wipe(), Slic3r::WipeTower::box_coordinates::translate(), Slic3r::WipeTowerWriter::travel(), wipe_volumes, and Slic3r::WipeTowerWriter::y().
Referenced by Slic3r::Print::_make_wipe_tower().
save_on_last_wipe()
void Slic3r::WipeTower::save_on_last_wipe () private
{
    for (m_layer_info=m_plan.begin();m_layer_info<m_plan.end();++m_layer_info) {
        set_layer(m_layer_info->z, m_layer_info->height, 0, m_layer_info->z == m_plan.front().z, m_layer_info->z == m_plan.back().z);
        if (m_layer_info->tool_changes.size()==0)   // we have no way to save anything on an empty layer
            continue;
        // Which toolchange will finish_layer extrusions be subtracted from?
        int idx = first_toolchange_to_nonsoluble(m_layer_info->tool_changes);
        for (int i=0; i<int(m_layer_info->tool_changes.size()); ++i) {
            auto& toolchange = m_layer_info->tool_changes[i];
            tool_change(toolchange.new_tool);
            if (i == idx) {
                float width = m_wipe_tower_width - 3*m_perimeter_width; // width we draw into
                float length_to_save = finish_layer().total_extrusion_length_in_plane();
                float length_to_wipe = volume_to_length(toolchange.wipe_volume,
                                      m_perimeter_width, m_layer_info->height)  - toolchange.first_wipe_line - length_to_save;
                length_to_wipe = std::max(length_to_wipe,0.f);
                float depth_to_wipe = m_perimeter_width * (std::floor(length_to_wipe/width) + ( length_to_wipe > 0.f ? 1.f : 0.f ) ) * m_extra_spacing;
                toolchange.required_depth = toolchange.ramming_depth + depth_to_wipe;
            }
        }
    }
}
References finish_layer(), first_toolchange_to_nonsoluble(), m_extra_spacing, m_layer_info, m_perimeter_width, m_plan, m_wipe_tower_width, set_layer(), tool_change(), Slic3r::WipeTower::ToolChangeResult::total_extrusion_length_in_plane(), volume_to_length(), and width().
Referenced by generate().
set_extruder()
void Slic3r::WipeTower::set_extruder (size_t idx, const PrintConfig & config)
{
    //while (m_filpar.size() < idx+1)   // makes sure the required element is in the vector
    m_filpar.push_back(FilamentParameters());
    m_filpar[idx].material = config.filament_type.get_at(idx);
    m_filpar[idx].is_soluble = config.wipe_tower_extruder == 0 ? config.filament_soluble.get_at(idx) : (idx != size_t(config.wipe_tower_extruder - 1));
    m_filpar[idx].temperature = config.temperature.get_at(idx);
    m_filpar[idx].first_layer_temperature = config.first_layer_temperature.get_at(idx);
    // If this is a single extruder MM printer, we will use all the SE-specific config values.
    // Otherwise, the defaults will be used to turn off the SE stuff.
    if (m_semm) {
        m_filpar[idx].loading_speed           = float(config.filament_loading_speed.get_at(idx));
        m_filpar[idx].loading_speed_start     = float(config.filament_loading_speed_start.get_at(idx));
        m_filpar[idx].unloading_speed         = float(config.filament_unloading_speed.get_at(idx));
        m_filpar[idx].unloading_speed_start   = float(config.filament_unloading_speed_start.get_at(idx));
        m_filpar[idx].delay                   = float(config.filament_toolchange_delay.get_at(idx));
        m_filpar[idx].cooling_moves           = config.filament_cooling_moves.get_at(idx);
        m_filpar[idx].cooling_initial_speed   = float(config.filament_cooling_initial_speed.get_at(idx));
        m_filpar[idx].cooling_final_speed     = float(config.filament_cooling_final_speed.get_at(idx));
    }
    m_filpar[idx].filament_area = float((M_PI/4.f) * pow(config.filament_diameter.get_at(idx), 2)); // all extruders are assumed to have the same filament diameter at this point
    float nozzle_diameter = float(config.nozzle_diameter.get_at(idx));
    m_filpar[idx].nozzle_diameter = nozzle_diameter; // to be used in future with (non-single) multiextruder MM
    float max_vol_speed = float(config.filament_max_volumetric_speed.get_at(idx));
    if (max_vol_speed!= 0.f)
        m_filpar[idx].max_e_speed = (max_vol_speed / filament_area());
    m_perimeter_width = nozzle_diameter * Width_To_Nozzle_Ratio; // all extruders are now assumed to have the same diameter
    if (m_semm) {
        std::istringstream stream{config.filament_ramming_parameters.get_at(idx)};
        float speed = 0.f;
        stream >> m_filpar[idx].ramming_line_width_multiplicator >> m_filpar[idx].ramming_step_multiplicator;
        m_filpar[idx].ramming_line_width_multiplicator /= 100;
        m_filpar[idx].ramming_step_multiplicator /= 100;
        while (stream >> speed)
            m_filpar[idx].ramming_speed.push_back(speed);
    }
    m_used_filament_length.resize(std::max(m_used_filament_length.size(), idx + 1)); // makes sure that the vector is big enough so we don't have to check later
}
References filament_area(), m_filpar, m_perimeter_width, M_PI, m_semm, m_used_filament_length, and Width_To_Nozzle_Ratio.
Referenced by Slic3r::Print::_make_wipe_tower().
set_layer()
void Slic3r::WipeTower::set_layer (float print_z, float layer_height, size_t max_tool_changes, bool , bool is_last_layer) inline
  {
    m_z_pos         = print_z;
    m_layer_height      = layer_height;
    m_depth_traversed  = 0.f;
        m_current_layer_finished = false;
        // Advance m_layer_info iterator, making sure we got it right
    while (!m_plan.empty() && m_layer_info->z < print_z - WT_EPSILON && m_layer_info+1 != m_plan.end())
      ++m_layer_info;
    m_current_shape = (! this->is_first_layer() && m_current_shape == SHAPE_NORMAL) ? SHAPE_REVERSED : SHAPE_NORMAL;
    if (this->is_first_layer()) {
            m_num_layer_changes = 0;
            m_num_tool_changes  = 0;
        } else
            ++ m_num_layer_changes;
    // Calculate extrusion flow from desired line width, nozzle diameter, filament diameter and layer_height:
    m_extrusion_flow = extrusion_flow(layer_height);
  }
References extrusion_flow(), is_first_layer(), Slic3r::layer_height(), m_current_layer_finished, m_current_shape, m_depth_traversed, m_extrusion_flow, m_layer_height, m_layer_info, m_num_layer_changes, m_num_tool_changes, m_plan, m_z_pos, SHAPE_NORMAL, SHAPE_REVERSED, and WT_EPSILON.
Referenced by Slic3r::Print::_make_wipe_tower(), generate(), prime(), and save_on_last_wipe().
tool_change()
WipeTower::ToolChangeResult Slic3r::WipeTower::tool_change (size_t new_tool)
{
    size_t old_tool = m_current_tool;
    float wipe_area = 0.f;
  float wipe_volume = 0.f;
  // Finds this toolchange info
  if (tool != (unsigned int)(-1))
  {
    for (const auto &b : m_layer_info->tool_changes)
      if ( b.new_tool == tool ) {
                wipe_volume = b.wipe_volume;
        wipe_area = b.required_depth * m_layer_info->extra_spacing;
        break;
      }
  }
  else {
    // Otherwise we are going to Unload only. And m_layer_info would be invalid.
  }
    box_coordinates cleaning_box(
    Vec2f(m_perimeter_width / 2.f, m_perimeter_width / 2.f),
    m_wipe_tower_width - m_perimeter_width,
        (tool != (unsigned int)(-1) ? wipe_area+m_depth_traversed-0.5f*m_perimeter_width
                                    : m_wipe_tower_depth-m_perimeter_width));
  WipeTowerWriter writer(m_layer_height, m_perimeter_width, m_gcode_flavor, m_filpar);
  writer.set_extrusion_flow(m_extrusion_flow)
    .set_z(m_z_pos)
    .set_initial_tool(m_current_tool)
        .set_y_shift(m_y_shift + (tool!=(unsigned int)(-1) && (m_current_shape == SHAPE_REVERSED) ? m_layer_info->depth - m_layer_info->toolchanges_depth(): 0.f))
    .append(";--------------------\n"
        "; CP TOOLCHANGE START\n")
    .comment_with_value(" toolchange #", m_num_tool_changes + 1); // the number is zero-based
    if (tool != (unsigned)(-1))
        writer.append(std::string("; material : " + (m_current_tool < m_filpar.size() ? m_filpar[m_current_tool].material : "(NONE)") + " -> " + m_filpar[tool].material + "\n").c_str())
              .append(";--------------------\n");
    writer.speed_override_backup();
  writer.speed_override(100);
  Vec2f initial_position = cleaning_box.ld + Vec2f(0.f, m_depth_traversed);
    writer.set_initial_position(initial_position, m_wipe_tower_width, m_wipe_tower_depth, m_internal_rotation);
    // Increase the extruder driver current to allow fast ramming.
  if (m_set_extruder_trimpot)
    writer.set_extruder_trimpot(750);
    // Ram the hot material out of the melt zone, retract the filament into the cooling tubes and let it cool.
    if (tool != (unsigned int)-1){      // This is not the last change.
        toolchange_Unload(writer, cleaning_box, m_filpar[m_current_tool].material,
                          is_first_layer() ? m_filpar[tool].first_layer_temperature : m_filpar[tool].temperature);
        toolchange_Change(writer, tool, m_filpar[tool].material); // Change the tool, set a speed override for soluble and flex materials.
        toolchange_Load(writer, cleaning_box);
        writer.travel(writer.x(), writer.y()-m_perimeter_width); // cooling and loading were done a bit down the road
        toolchange_Wipe(writer, cleaning_box, wipe_volume);     // Wipe the newly loaded filament until the end of the assigned wipe area.
        ++ m_num_tool_changes;
    } else
        toolchange_Unload(writer, cleaning_box, m_filpar[m_current_tool].material, m_filpar[m_current_tool].temperature);
    m_depth_traversed += wipe_area;
  if (m_set_extruder_trimpot)
    writer.set_extruder_trimpot(550);    // Reset the extruder current to a normal value.
  writer.speed_override_restore();
    writer.feedrate(m_travel_speed * 60.f)
          .flush_planner_queue()
          .reset_extruder()
          .append("; CP TOOLCHANGE END\n"
                  ";------------------\n"
                  "\n\n");
    // Ask our writer about how much material was consumed:
    if (m_current_tool < m_used_filament_length.size())
        m_used_filament_length[m_current_tool] += writer.get_and_reset_used_filament_length();
   return construct_tcr(writer, false, old_tool);
}
References Slic3r::WipeTowerWriter::append(), Slic3r::append(), Slic3r::WipeTowerWriter::comment_with_value(), construct_tcr(), Slic3r::WipeTowerWriter::feedrate(), Slic3r::WipeTowerWriter::flush_planner_queue(), Slic3r::WipeTowerWriter::get_and_reset_used_filament_length(), is_first_layer(), Slic3r::WipeTower::box_coordinates::ld, m_current_shape, m_current_tool, m_depth_traversed, m_extrusion_flow, m_filpar, m_gcode_flavor, m_internal_rotation, m_layer_height, m_layer_info, m_num_tool_changes, m_perimeter_width, m_set_extruder_trimpot, m_travel_speed, m_used_filament_length, m_wipe_tower_depth, m_wipe_tower_width, m_y_shift, m_z_pos, Slic3r::WipeTowerWriter::reset_extruder(), Slic3r::WipeTowerWriter::set_extruder_trimpot(), Slic3r::WipeTowerWriter::set_extrusion_flow(), Slic3r::WipeTowerWriter::set_initial_position(), Slic3r::WipeTowerWriter::set_initial_tool(), Slic3r::WipeTowerWriter::set_y_shift(), Slic3r::WipeTowerWriter::set_z(), SHAPE_REVERSED, Slic3r::WipeTowerWriter::speed_override(), Slic3r::WipeTowerWriter::speed_override_backup(), Slic3r::WipeTowerWriter::speed_override_restore(), toolchange_Change(), toolchange_Load(), toolchange_Unload(), toolchange_Wipe(), Slic3r::WipeTowerWriter::travel(), Slic3r::WipeTowerWriter::x(), and Slic3r::WipeTowerWriter::y().
Referenced by Slic3r::Print::_make_wipe_tower(), generate(), and save_on_last_wipe().
toolchange_Change()
void Slic3r::WipeTower::toolchange_Change (WipeTowerWriter & writer, const size_t new_tool, const std::string & new_material) private
{
    // Ask the writer about how much of the old filament we consumed:
    if (m_current_tool < m_used_filament_length.size())
      m_used_filament_length[m_current_tool] += writer.get_and_reset_used_filament_length();
    // This is where we want to place the custom gcodes. We will use placeholders for this.
    // These will be substituted by the actual gcodes when the gcode is generated.
    //writer.append("[end_filament_gcode]\n");
    writer.append("[toolchange_gcode]\n");
    // Travel to where we assume we are. Custom toolchange or some special T code handling (parking extruder etc)
    // gcode could have left the extruder somewhere, we cannot just start extruding. We should also inform the
    // postprocessor that we absolutely want to have this in the gcode, even if it thought it is the same as before.
    Vec2f current_pos = writer.pos_rotated();
    writer.feedrate(m_travel_speed * 60.f) // see https://github.com/prusa3d/PrusaSlicer/issues/5483
          .append(std::string("G1 X") + Slic3r::float_to_string_decimal_point(current_pos.x())
                             +  " Y"  + Slic3r::float_to_string_decimal_point(current_pos.y())
                             + never_skip_tag() + "\n");
    writer.append("[deretraction_from_wipe_tower_generator]");
    // The toolchange Tn command will be inserted later, only in case that the user does
    // not provide a custom toolchange gcode.
  writer.set_tool(new_tool); // This outputs nothing, the writer just needs to know the tool has changed.
    //writer.append("[start_filament_gcode]\n");
  writer.flush_planner_queue();
  m_current_tool = new_tool;
}
References Slic3r::WipeTowerWriter::append(), Slic3r::WipeTowerWriter::feedrate(), Slic3r::float_to_string_decimal_point(), Slic3r::WipeTowerWriter::flush_planner_queue(), Slic3r::WipeTowerWriter::get_and_reset_used_filament_length(), m_current_tool, m_travel_speed, m_used_filament_length, never_skip_tag(), Slic3r::WipeTowerWriter::pos_rotated(), and Slic3r::WipeTowerWriter::set_tool().
Referenced by prime(), and tool_change().
toolchange_Load()
void Slic3r::WipeTower::toolchange_Load (WipeTowerWriter & writer, const box_coordinates & cleaning_box) private
{
    if (m_semm && (m_parking_pos_retraction != 0 || m_extra_loading_move != 0)) {
        float xl = cleaning_box.ld.x() + m_perimeter_width * 0.75f;
        float xr = cleaning_box.rd.x() - m_perimeter_width * 0.75f;
        float oldx = writer.x();  // the nozzle is in place to do the first wiping moves, we will remember the position
        // Load the filament while moving left / right, so the excess material will not create a blob at a single position.
        float turning_point = ( oldx-xl < xr-oldx ? xr : xl );
        float edist = m_parking_pos_retraction+m_extra_loading_move;
        writer.append("; CP TOOLCHANGE LOAD\n")
              .suppress_preview()
              .load(0.2f * edist, 60.f * m_filpar[m_current_tool].loading_speed_start)
              .load_move_x_advanced(turning_point, 0.7f * edist,        m_filpar[m_current_tool].loading_speed)  // Fast phase
              .load_move_x_advanced(oldx,          0.1f * edist, 0.1f * m_filpar[m_current_tool].loading_speed)  // Super slow*/
              .travel(oldx, writer.y()) // in case last move was shortened to limit x feedrate
              .resume_preview();
        // Reset the extruder current to the normal value.
        if (m_set_extruder_trimpot)
            writer.set_extruder_trimpot(550);
    }
}
References Slic3r::WipeTowerWriter::append(), Slic3r::WipeTower::box_coordinates::ld, Slic3r::WipeTowerWriter::load(), Slic3r::WipeTowerWriter::load_move_x_advanced(), m_current_tool, m_extra_loading_move, m_filpar, m_parking_pos_retraction, m_perimeter_width, m_semm, m_set_extruder_trimpot, Slic3r::WipeTower::box_coordinates::rd, Slic3r::WipeTowerWriter::set_extruder_trimpot(), Slic3r::WipeTowerWriter::suppress_preview(), Slic3r::WipeTowerWriter::travel(), Slic3r::WipeTowerWriter::x(), and Slic3r::WipeTowerWriter::y().
Referenced by prime(), and tool_change().
toolchange_Unload()
void Slic3r::WipeTower::toolchange_Unload (WipeTowerWriter & writer, const box_coordinates & cleaning_box, const std::string & current_material, const int new_temperature) private
{
  float xl = cleaning_box.ld.x() + 1.f * m_perimeter_width;
  float xr = cleaning_box.rd.x() - 1.f * m_perimeter_width;
    const float line_width = m_perimeter_width * m_filpar[m_current_tool].ramming_line_width_multiplicator;       // desired ramming line thickness
  const float y_step = line_width * m_filpar[m_current_tool].ramming_step_multiplicator * m_extra_spacing; // spacing between lines in mm
    const Vec2f ramming_start_pos = Vec2f(xl, cleaning_box.ld.y() + m_depth_traversed + y_step/2.f);
    writer.append("; CP TOOLCHANGE UNLOAD\n")
        .change_analyzer_line_width(line_width);
  unsigned i = 0;                   // iterates through ramming_speed
  m_left_to_right = true;               // current direction of ramming
  float remaining = xr - xl ;             // keeps track of distance to the next turnaround
  float e_done = 0;                 // measures E move done from each segment
    if (m_semm)
        writer.travel(ramming_start_pos); // move to starting position
    else
        writer.set_position(ramming_start_pos);
    // if the ending point of the ram would end up in mid air, align it with the end of the wipe tower:
    if (m_semm && (m_layer_info > m_plan.begin() && m_layer_info < m_plan.end() && (m_layer_info-1!=m_plan.begin() || !m_adhesion ))) {
        // this is y of the center of previous sparse infill border
        float sparse_beginning_y = 0.f;
        if (m_current_shape == SHAPE_REVERSED)
            sparse_beginning_y += ((m_layer_info-1)->depth - (m_layer_info-1)->toolchanges_depth())
                                      - ((m_layer_info)->depth-(m_layer_info)->toolchanges_depth()) ;
        else
            sparse_beginning_y += (m_layer_info-1)->toolchanges_depth() + m_perimeter_width;
        float sum_of_depths = 0.f;
        for (const auto& tch : m_layer_info->tool_changes) {  // let's find this toolchange
            if (tch.old_tool == m_current_tool) {
                sum_of_depths += tch.ramming_depth;
                float ramming_end_y = sum_of_depths;
                ramming_end_y -= (y_step/m_extra_spacing-m_perimeter_width) / 2.f;   // center of final ramming line
                if ( (m_current_shape == SHAPE_REVERSED   && ramming_end_y < sparse_beginning_y - 0.5f*m_perimeter_width  ) ||
                     (m_current_shape == SHAPE_NORMAL && ramming_end_y > sparse_beginning_y + 0.5f*m_perimeter_width  )  )
                {
                    writer.extrude(xl + tch.first_wipe_line-1.f*m_perimeter_width,writer.y());
                    remaining -= tch.first_wipe_line-1.f*m_perimeter_width;
                }
                break;
            }
            sum_of_depths += tch.required_depth;
        }
    }
    writer.disable_linear_advance();
    // now the ramming itself:
    while (m_semm && i < m_filpar[m_current_tool].ramming_speed.size())
    {
        const float x = volume_to_length(m_filpar[m_current_tool].ramming_speed[i] * 0.25f, line_width, m_layer_height);
        const float e = m_filpar[m_current_tool].ramming_speed[i] * 0.25f / filament_area(); // transform volume per sec to E move;
        const float dist = std::min(x - e_done, remaining);     // distance to travel for either the next 0.25s, or to the next turnaround
        const float actual_time = dist/x * 0.25f;
        writer.ram(writer.x(), writer.x() + (m_left_to_right ? 1.f : -1.f) * dist, 0.f, 0.f, e * (dist / x), dist / (actual_time / 60.f));
        remaining -= dist;
    if (remaining < WT_EPSILON) { // we reached a turning point
      writer.travel(writer.x(), writer.y() + y_step, 7200);
      m_left_to_right = !m_left_to_right;
      remaining = xr - xl;
    }
    e_done += dist; // subtract what was actually done
    if (e_done > x - WT_EPSILON) { // current segment finished
      ++i;
      e_done = 0;
    }
  }
  Vec2f end_of_ramming(writer.x(),writer.y());
    writer.change_analyzer_line_width(m_perimeter_width);   // so the next lines are not affected by ramming_line_width_multiplier
    // Retraction:
    float old_x = writer.x();
    float turning_point = (!m_left_to_right ? xl : xr );
    if (m_semm && (m_cooling_tube_retraction != 0 || m_cooling_tube_length != 0)) {
        float total_retraction_distance = m_cooling_tube_retraction + m_cooling_tube_length/2.f - 15.f; // the 15mm is reserved for the first part after ramming
        writer.suppress_preview()
              .retract(15.f, m_filpar[m_current_tool].unloading_speed_start * 60.f) // feedrate 5000mm/min = 83mm/s
              .retract(0.70f * total_retraction_distance, 1.0f * m_filpar[m_current_tool].unloading_speed * 60.f)
              .retract(0.20f * total_retraction_distance, 0.5f * m_filpar[m_current_tool].unloading_speed * 60.f)
              .retract(0.10f * total_retraction_distance, 0.3f * m_filpar[m_current_tool].unloading_speed * 60.f)
              .resume_preview();
    }
    // Wipe tower should only change temperature with single extruder MM. Otherwise, all temperatures should
    // be already set and there is no need to change anything. Also, the temperature could be changed
    // for wrong extruder.
    if (m_semm) {
        if (new_temperature != 0 && (new_temperature != m_old_temperature || is_first_layer()) ) {  // Set the extruder temperature, but don't wait.
            // If the required temperature is the same as last time, don't emit the M104 again (if user adjusted the value, it would be reset)
            // However, always change temperatures on the first layer (this is to avoid issues with priming lines turned off).
            writer.set_extruder_temp(new_temperature, false);
            m_old_temperature = new_temperature;
        }
    }
    // Cooling:
    const int& number_of_moves = m_filpar[m_current_tool].cooling_moves;
    if (m_semm && number_of_moves > 0) {
        const float& initial_speed = m_filpar[m_current_tool].cooling_initial_speed;
        const float& final_speed   = m_filpar[m_current_tool].cooling_final_speed;
        float speed_inc = (final_speed - initial_speed) / (2.f * number_of_moves - 1.f);
        writer.suppress_preview()
              .travel(writer.x(), writer.y() + y_step);
        old_x = writer.x();
        turning_point = xr-old_x > old_x-xl ? xr : xl;
        for (int i=0; i<number_of_moves; ++i) {
            float speed = initial_speed + speed_inc * 2*i;
            writer.load_move_x_advanced(turning_point, m_cooling_tube_length, speed);
            speed += speed_inc;
            writer.load_move_x_advanced(old_x, -m_cooling_tube_length, speed);
        }
    }
    if (m_semm) {
        // let's wait is necessary:
        writer.wait(m_filpar[m_current_tool].delay);
        // we should be at the beginning of the cooling tube again - let's move to parking position:
        writer.retract(-m_cooling_tube_length/2.f+m_parking_pos_retraction-m_cooling_tube_retraction, 2000);
    }
    // this is to align ramming and future wiping extrusions, so the future y-steps can be uniform from the start:
    // the perimeter_width will later be subtracted, it is there to not load while moving over just extruded material
    Vec2f pos = Vec2f(end_of_ramming.x(), end_of_ramming.y() + (y_step/m_extra_spacing-m_perimeter_width) / 2.f + m_perimeter_width);
    if (m_semm)
        writer.travel(pos, 2400.f);
    else
        writer.set_position(pos);
    writer.resume_preview()
          .flush_planner_queue();
}
References Slic3r::WipeTowerWriter::append(), Slic3r::WipeTowerWriter::change_analyzer_line_width(), Slic3r::WipeTowerWriter::disable_linear_advance(), Slic3r::WipeTowerWriter::extrude(), filament_area(), Slic3r::WipeTowerWriter::flush_planner_queue(), is_first_layer(), Slic3r::WipeTower::box_coordinates::ld, Slic3r::WipeTowerWriter::load_move_x_advanced(), m_adhesion, m_cooling_tube_length, m_cooling_tube_retraction, m_current_shape, m_current_tool, m_depth_traversed, m_extra_spacing, m_filpar, m_layer_height, m_layer_info, m_left_to_right, m_old_temperature, m_parking_pos_retraction, m_perimeter_width, m_plan, m_semm, Slic3r::WipeTowerWriter::ram(), Slic3r::WipeTower::box_coordinates::rd, Slic3r::WipeTowerWriter::resume_preview(), Slic3r::WipeTowerWriter::retract(), Slic3r::WipeTowerWriter::set_extruder_temp(), Slic3r::WipeTowerWriter::set_position(), SHAPE_NORMAL, SHAPE_REVERSED, Slic3r::WipeTowerWriter::suppress_preview(), Slic3r::WipeTowerWriter::travel(), volume_to_length(), Slic3r::WipeTowerWriter::wait(), WT_EPSILON, Slic3r::WipeTowerWriter::x(), and Slic3r::WipeTowerWriter::y().
Referenced by prime(), and tool_change().
toolchange_Wipe()
void Slic3r::WipeTower::toolchange_Wipe (WipeTowerWriter & writer, const box_coordinates & cleaning_box, float wipe_volume) private
{
  // Increase flow on first layer, slow down print.
    writer.set_extrusion_flow(m_extrusion_flow * (is_first_layer() ? 1.18f : 1.f))
      .append("; CP TOOLCHANGE WIPE\n");
  const float& xl = cleaning_box.ld.x();
  const float& xr = cleaning_box.rd.x();
  // Variables x_to_wipe and traversed_x are here to be able to make sure it always wipes at least
    //   the ordered volume, even if it means violating the box. This can later be removed and simply
    // wipe until the end of the assigned area.
  float x_to_wipe = volume_to_length(wipe_volume, m_perimeter_width, m_layer_height);
  float dy = m_extra_spacing*m_perimeter_width;
    const float target_speed = is_first_layer() ? m_first_layer_speed * 60.f : 4800.f;
    float wipe_speed = 0.33f * target_speed;
    // if there is less than 2.5*m_perimeter_width to the edge, advance straightaway (there is likely a blob anyway)
    if ((m_left_to_right ? xr-writer.x() : writer.x()-xl) < 2.5f*m_perimeter_width) {
        writer.travel((m_left_to_right ? xr-m_perimeter_width : xl+m_perimeter_width),writer.y()+dy);
        m_left_to_right = !m_left_to_right;
    }
    // now the wiping itself:
  for (int i = 0; true; ++i)  {
    if (i!=0) {
            if      (wipe_speed < 0.34f * target_speed) wipe_speed = 0.375f * target_speed;
            else if (wipe_speed < 0.377 * target_speed) wipe_speed = 0.458f * target_speed;
            else if (wipe_speed < 0.46f * target_speed) wipe_speed = 0.875f * target_speed;
            else wipe_speed = std::min(target_speed, wipe_speed + 50.f);
    }
    float traversed_x = writer.x();
    if (m_left_to_right)
            writer.extrude(xr - (i % 4 == 0 ? 0 : 1.5f*m_perimeter_width), writer.y(), wipe_speed);
    else
            writer.extrude(xl + (i % 4 == 1 ? 0 : 1.5f*m_perimeter_width), writer.y(), wipe_speed);
        if (writer.y()+float(EPSILON) > cleaning_box.lu.y()-0.5f*m_perimeter_width)
            break;    // in case next line would not fit
    traversed_x -= writer.x();
        x_to_wipe -= std::abs(traversed_x);
    if (x_to_wipe < WT_EPSILON) {
            writer.travel(m_left_to_right ? xl + 1.5f*m_perimeter_width : xr - 1.5f*m_perimeter_width, writer.y(), 7200);
      break;
    }
    // stepping to the next line:
        writer.extrude(writer.x() + (i % 4 == 0 ? -1.f : (i % 4 == 1 ? 1.f : 0.f)) * 1.5f*m_perimeter_width, writer.y() + dy);
    m_left_to_right = !m_left_to_right;
  }
    // We may be going back to the model - wipe the nozzle. If this is followed
    // by finish_layer, this wipe path will be overwritten.
    writer.add_wipe_point(writer.x(), writer.y())
          .add_wipe_point(writer.x(), writer.y() - dy)
          .add_wipe_point(! m_left_to_right ? m_wipe_tower_width : 0.f, writer.y() - dy);
    if (m_layer_info != m_plan.end() && m_current_tool != m_layer_info->tool_changes.back().new_tool)
        m_left_to_right = !m_left_to_right;
    writer.set_extrusion_flow(m_extrusion_flow); // Reset the extrusion flow.
}
References Slic3r::WipeTowerWriter::add_wipe_point(), Slic3r::WipeTowerWriter::append(), EPSILON, Slic3r::WipeTowerWriter::extrude(), is_first_layer(), Slic3r::WipeTower::box_coordinates::ld, Slic3r::WipeTower::box_coordinates::lu, m_current_tool, m_extra_spacing, m_extrusion_flow, m_first_layer_speed, m_layer_height, m_layer_info, m_left_to_right, m_perimeter_width, m_plan, m_wipe_tower_width, Slic3r::WipeTower::box_coordinates::rd, Slic3r::WipeTowerWriter::set_extrusion_flow(), Slic3r::WipeTowerWriter::travel(), volume_to_length(), WT_EPSILON, Slic3r::WipeTowerWriter::x(), and Slic3r::WipeTowerWriter::y().
Referenced by prime(), and tool_change().
volume_to_length()
float Slic3r::WipeTower::volume_to_length (float volume, float line_width, float layer_height) const inline private
{
    return std::max(0.f, volume / (layer_height * (line_width - layer_height * (1.f - float(M_PI) / 4.f))));
  }
References Slic3r::layer_height(), and M_PI.
Referenced by plan_toolchange(), save_on_last_wipe(), toolchange_Unload(), and toolchange_Wipe().
width()
float Slic3r::WipeTower::width () const inline
{ return m_wipe_tower_width; }
References m_wipe_tower_width.
Referenced by Slic3r::Print::_make_wipe_tower(), get_wipe_tower_cone_base(), plan_toolchange(), and save_on_last_wipe().
Member Data Documentation
m_adhesion
bool Slic3r::WipeTower::m_adhesion = true private
Referenced by finish_layer(), and toolchange_Unload().
m_bed_bottom_left
Vec2f Slic3r::WipeTower::m_bed_bottom_left private
Referenced by WipeTower(), and prime().
[]
enum { ... } Slic3r::WipeTower::m_bed_shape
Referenced by WipeTower(), and prime().
m_bed_width
float Slic3r::WipeTower::m_bed_width private
Referenced by WipeTower(), and prime().
m_bridging
float Slic3r::WipeTower::m_bridging = 0.f private
Referenced by finish_layer().
m_cooling_tube_length
float Slic3r::WipeTower::m_cooling_tube_length = 0.f private
Referenced by WipeTower(), and toolchange_Unload().
m_cooling_tube_retraction
float Slic3r::WipeTower::m_cooling_tube_retraction = 0.f private
Referenced by WipeTower(), and toolchange_Unload().
m_current_height
float Slic3r::WipeTower::m_current_height = 0.f private
Referenced by finish_layer(), generate(), and plan_tower().
m_current_layer_finished
bool Slic3r::WipeTower::m_current_layer_finished = false private
Referenced by finish_layer(), layer_finished(), and set_layer().
m_current_shape
wipe_shape Slic3r::WipeTower::m_current_shape = SHAPE_NORMAL private
Referenced by finish_layer(), set_layer(), tool_change(), and toolchange_Unload().
m_current_tool
size_t Slic3r::WipeTower::m_current_tool = 0 private
Referenced by construct_tcr(), finish_layer(), generate(), prime(), tool_change(), toolchange_Change(), toolchange_Load(), toolchange_Unload(), and toolchange_Wipe().
m_depth_traversed
float Slic3r::WipeTower::m_depth_traversed = 0.f private
Referenced by set_layer(), tool_change(), and toolchange_Unload().
m_extra_loading_move
float Slic3r::WipeTower::m_extra_loading_move = 0.f private
Referenced by WipeTower(), and toolchange_Load().
m_extra_spacing
float Slic3r::WipeTower::m_extra_spacing = 1.f private
Referenced by plan_toolchange(), save_on_last_wipe(), toolchange_Unload(), and toolchange_Wipe().
m_extrusion_flow
float Slic3r::WipeTower::m_extrusion_flow = 0.038f private
Referenced by extrusion_flow(), finish_layer(), prime(), set_layer(), tool_change(), and toolchange_Wipe().
m_filpar
std::vector<FilamentParameters> Slic3r::WipeTower::m_filpar private
Referenced by filament_area(), finish_layer(), first_toolchange_to_nonsoluble(), plan_toolchange(), prime(), set_extruder(), tool_change(), toolchange_Load(), and toolchange_Unload().
m_first_layer_idx
size_t Slic3r::WipeTower::m_first_layer_idx = size_t(-1) private
Referenced by is_first_layer(), and plan_toolchange().
m_first_layer_speed
float Slic3r::WipeTower::m_first_layer_speed = 0.f private
Referenced by WipeTower(), finish_layer(), and toolchange_Wipe().
m_gcode_flavor
GCodeFlavor Slic3r::WipeTower::m_gcode_flavor private
Referenced by finish_layer(), prime(), and tool_change().
m_internal_rotation
float Slic3r::WipeTower::m_internal_rotation = 0.f private
Referenced by finish_layer(), generate(), and tool_change().
m_layer_height
float Slic3r::WipeTower::m_layer_height = 0.f private
Referenced by construct_tcr(), finish_layer(), prime(), set_layer(), tool_change(), toolchange_Unload(), and toolchange_Wipe().
m_layer_info
std::vector<WipeTowerInfo>::iterator Slic3r::WipeTower::m_layer_info = m_plan.end() private
Referenced by finish_layer(), generate(), is_first_layer(), save_on_last_wipe(), set_layer(), tool_change(), toolchange_Unload(), and toolchange_Wipe().
m_left_to_right
bool Slic3r::WipeTower::m_left_to_right = true private
Referenced by finish_layer(), prime(), toolchange_Unload(), and toolchange_Wipe().
m_max_color_changes
size_t Slic3r::WipeTower::m_max_color_changes = 0 private
Referenced by finished().
m_no_sparse_layers
bool Slic3r::WipeTower::m_no_sparse_layers = false private
Referenced by finish_layer(), and plan_toolchange().
m_num_layer_changes
unsigned int Slic3r::WipeTower::m_num_layer_changes = 0 private
Referenced by finish_layer(), and set_layer().
m_num_tool_changes
unsigned int Slic3r::WipeTower::m_num_tool_changes = 0 private
Referenced by get_number_of_toolchanges(), prime(), set_layer(), and tool_change().
m_old_temperature
int Slic3r::WipeTower::m_old_temperature = -1 private
Referenced by generate(), prime(), and toolchange_Unload().
m_parking_pos_retraction
float Slic3r::WipeTower::m_parking_pos_retraction = 0.f private
Referenced by WipeTower(), toolchange_Load(), and toolchange_Unload().
m_perimeter_width
float Slic3r::WipeTower::m_perimeter_width = 0.4f * Width_To_Nozzle_Ratio private
Referenced by extrusion_flow(), finish_layer(), generate(), plan_toolchange(), plan_tower(), prime(), save_on_last_wipe(), set_extruder(), tool_change(), toolchange_Load(), toolchange_Unload(), and toolchange_Wipe().
m_plan
std::vector<WipeTowerInfo> Slic3r::WipeTower::m_plan private
Referenced by finish_layer(), generate(), get_z_and_depth_pairs(), is_first_layer(), plan_toolchange(), plan_tower(), save_on_last_wipe(), set_layer(), toolchange_Unload(), and toolchange_Wipe().
m_print_brim
bool Slic3r::WipeTower::m_print_brim = true private
unsigned int m_idx_tool_change_in_layer = 0; // Layer change counter in this layer. Counting up to m_max_color_changes.
m_semm
bool Slic3r::WipeTower::m_semm = true private
Referenced by WipeTower(), set_extruder(), toolchange_Load(), and toolchange_Unload().
m_set_extruder_trimpot
bool Slic3r::WipeTower::m_set_extruder_trimpot = false private
Referenced by WipeTower(), prime(), tool_change(), and toolchange_Load().
m_travel_speed
float Slic3r::WipeTower::m_travel_speed = 0.f private
Referenced by prime(), tool_change(), and toolchange_Change().
m_used_filament_length
std::vector<float> Slic3r::WipeTower::m_used_filament_length private
Referenced by finish_layer(), generate(), get_used_filament(), prime(), set_extruder(), tool_change(), and toolchange_Change().
m_wipe_tower_brim_width
float Slic3r::WipeTower::m_wipe_tower_brim_width = 0.f private
Referenced by finish_layer().
m_wipe_tower_brim_width_real
float Slic3r::WipeTower::m_wipe_tower_brim_width_real = 0.f private
Referenced by finish_layer(), and get_brim_width().
m_wipe_tower_cone_angle
float Slic3r::WipeTower::m_wipe_tower_cone_angle = 0.f private
Referenced by finish_layer().
m_wipe_tower_depth
float Slic3r::WipeTower::m_wipe_tower_depth = 0.f private
Referenced by finish_layer(), generate(), get_depth(), get_z_and_depth_pairs(), plan_tower(), and tool_change().
m_wipe_tower_height
float Slic3r::WipeTower::m_wipe_tower_height = 0.f private
Referenced by finish_layer(), get_wipe_tower_height(), get_z_and_depth_pairs(), and plan_tower().
m_wipe_tower_pos
Vec2f Slic3r::WipeTower::m_wipe_tower_pos private
Referenced by position().
m_wipe_tower_rotation_angle
float Slic3r::WipeTower::m_wipe_tower_rotation_angle = 0.f private
m_wipe_tower_width
float Slic3r::WipeTower::m_wipe_tower_width private
Referenced by finish_layer(), plan_toolchange(), save_on_last_wipe(), tool_change(), toolchange_Wipe(), and width().
m_y_shift
float Slic3r::WipeTower::m_y_shift = 0.f private
Referenced by finish_layer(), generate(), and tool_change().
m_z_pos
float Slic3r::WipeTower::m_z_pos = 0.f private
Referenced by construct_tcr(), finish_layer(), prime(), set_layer(), and tool_change().
Width_To_Nozzle_Ratio
const float Slic3r::WipeTower::Width_To_Nozzle_Ratio = 1.25f private
Referenced by set_extruder().
wipe_volumes
const std::vector<std::vector<float> > Slic3r::WipeTower::wipe_volumes private
Referenced by extract_wipe_volumes(), and prime().
WT_EPSILON
const float Slic3r::WipeTower::WT_EPSILON = 1e-3f private
Referenced by finish_layer(), get_z_and_depth_pairs(), plan_toolchange(), set_layer(), toolchange_Unload(), and toolchange_Wipe().
The documentation for this class was generated from the following files:
src/libslic3r/GCode/WipeTower.hpp
src/libslic3r/GCode/WipeTower.cpp