Prusa Slicer: Slic3r::GUI::ogStaticText Class Reference
Slic3r::GUI::ogStaticText Class Reference
#include <src/slic3r/GUI/OptionsGroup.hpp>
Public Member Functions
ogStaticText ()
ogStaticText (wxWindow *parent, const wxString &text)
~ogStaticText ()
void SetText (const wxString &value, bool wrap=true)
void SetPathEnd (const std::string &link)
void FocusText (bool focus)
Detailed Description
Constructor & Destructor Documentation
ogStaticText() [1/2]
Slic3r::GUI::ogStaticText::ogStaticText () inline
{}
ogStaticText() [2/2]
Slic3r::GUI::ogStaticText::ogStaticText (wxWindow * parent, const wxString & text)
                                                                 :
    wxStaticText(parent, wxID_ANY, text, wxDefaultPosition, wxDefaultSize)
{
    if (!text.IsEmpty()) {
    Wrap(60 * wxGetApp().em_unit());
    GetParent()->Layout();
    }
}
References em_unit().
~ogStaticText()
Slic3r::GUI::ogStaticText::~ogStaticText () inline
{}
Member Function Documentation
FocusText()
void Slic3r::GUI::ogStaticText::FocusText (bool focus)
{
    if (get_app_config()->get_bool("suppress_hyperlinks"))
        return;
    SetFont(focus ? Slic3r::GUI::wxGetApp().link_font() :
        Slic3r::GUI::wxGetApp().normal_font());
#ifdef __linux__
    this->GetContainingSizer()->Layout();
#endif
    Refresh();
}
References Slic3r::GUI::get_app_config().
Referenced by SetPathEnd().
SetPathEnd()
void Slic3r::GUI::ogStaticText::SetPathEnd (const std::string & link)
{
#ifndef __linux__
    Bind(wxEVT_ENTER_WINDOW, [this, link](wxMouseEvent& event) {
        SetToolTip(OptionsGroup::get_url(get_app_config()->get("suppress_hyperlinks") != "1" ? link : std::string()));
        FocusText(true);
        event.Skip();
    });
    Bind(wxEVT_LEAVE_WINDOW, [this](wxMouseEvent& event) { FocusText(false); event.Skip(); });
    Bind(wxEVT_LEFT_DOWN, [this](wxMouseEvent& event) {
        if (HasCapture())
            return;
        this->CaptureMouse();
        event.Skip();
    });
    Bind(wxEVT_LEFT_UP, [link, this](wxMouseEvent& event) {
        if (!HasCapture())
            return;
        ReleaseMouse();
        OptionsGroup::launch_browser(link);
        event.Skip();
    });
#else
    // Workaround: On Linux wxStaticText doesn't receive wxEVT_ENTER(LEAVE)_WINDOW events,
    // so implement this behaviour trough wxEVT_MOTION events for this control and it's parent
    Bind(wxEVT_MOTION, [link, this](wxMouseEvent& event) {
        SetToolTip(OptionsGroup::get_url(!get_app_config()->get_bool("suppress_hyperlinks") ? link : std::string()));
        FocusText(true);
        event.Skip();
    });
    GetParent()->Bind(wxEVT_MOTION, [this](wxMouseEvent& event) {
        FocusText(false);
        event.Skip();
    });
    // On Linux a mouse capturing causes a totally application freeze
    Bind(wxEVT_LEFT_UP, [link, this](wxMouseEvent& event) {
        OptionsGroup::launch_browser(link);
        event.Skip();
    });
#endif
}
References FocusText(), Slic3r::GUI::get_app_config(), Slic3r::GUI::OptionsGroup::get_url(), and Slic3r::GUI::OptionsGroup::launch_browser().
SetText()
void Slic3r::GUI::ogStaticText::SetText (const wxString & value, bool wrap = true)
{
  SetLabel(value);
    if (wrap) Wrap(60 * wxGetApp().em_unit());
  GetParent()->Layout();
}
References em_unit().
Referenced by Slic3r::GUI::TabSLAPrint::update_description_lines().
The documentation for this class was generated from the following files:
src/slic3r/GUI/OptionsGroup.hpp
src/slic3r/GUI/OptionsGroup.cpp