Prusa Slicer: Slic3r::branchingtree::Builder Class Reference
Slic3r::branchingtree::Builder Class Reference abstract
#include <src/libslic3r/BranchingTree/BranchingTree.hpp>
Public Member Functions
virtual ~Builder ()=default
virtual bool add_bridge (const Node &from, const Node &to)=0
virtual bool add_merger (const Node &node, const Node &closest, const Node &merge_node)=0
virtual bool add_ground_bridge (const Node &from, const Node &to)=0
virtual bool add_mesh_bridge (const Node &from, const Node &to)=0
virtual std::optional< Vec3f > suggest_avoidance (const Node &from, float max_bridge_len) const
virtual void report_unroutable (const Node &j)=0
virtual bool is_valid () const
Detailed Description
Constructor & Destructor Documentation
~Builder()
virtual Slic3r::branchingtree::Builder::~Builder () virtual default
Member Function Documentation
add_bridge()
virtual bool Slic3r::branchingtree::Builder::add_bridge (const Node & from, const Node & to) pure virtual
Implemented in Slic3r::sla::BranchingTreeBuilder.
Referenced by Slic3r::branchingtree::build_tree().
add_ground_bridge()
virtual bool Slic3r::branchingtree::Builder::add_ground_bridge (const Node & from, const Node & to) pure virtual
Implemented in Slic3r::sla::BranchingTreeBuilder.
Referenced by Slic3r::branchingtree::build_tree().
add_merger()
virtual bool Slic3r::branchingtree::Builder::add_merger (const Node & node, const Node & closest, const Node & merge_node) pure virtual
Implemented in Slic3r::sla::BranchingTreeBuilder.
Referenced by Slic3r::branchingtree::build_tree().
add_mesh_bridge()
virtual bool Slic3r::branchingtree::Builder::add_mesh_bridge (const Node & from, const Node & to) pure virtual
Implemented in Slic3r::sla::BranchingTreeBuilder.
Referenced by Slic3r::branchingtree::build_tree().
is_valid()
virtual bool Slic3r::branchingtree::Builder::is_valid () const inline virtual
Reimplemented in Slic3r::sla::BranchingTreeBuilder.
{ return true; }
Referenced by Slic3r::branchingtree::build_tree().
report_unroutable()
virtual void Slic3r::branchingtree::Builder::report_unroutable (const Node & j) pure virtual
Implemented in Slic3r::sla::BranchingTreeBuilder.
Referenced by Slic3r::branchingtree::build_tree().
suggest_avoidance()
virtual std::optional< Vec3f > Slic3r::branchingtree::Builder::suggest_avoidance (const Node & from, float max_bridge_len) const inline virtual
Reimplemented in Slic3r::sla::BranchingTreeBuilder.
    {
        return {};
    }
Referenced by Slic3r::branchingtree::build_tree().
The documentation for this class was generated from the following file:
src/libslic3r/BranchingTree/BranchingTree.hpp