Prusa Slicer: Slic3r::GUI::OtherInstanceMessageHandler Class Reference
Slic3r::GUI::OtherInstanceMessageHandler Class Reference
#include <src/slic3r/GUI/InstanceCheck.hpp>
Public Member Functions
OtherInstanceMessageHandler ()=default
OtherInstanceMessageHandler (OtherInstanceMessageHandler const &)=delete
void operator= (OtherInstanceMessageHandler const &)=delete
~OtherInstanceMessageHandler ()
void init (wxEvtHandler *callback_evt_handler)
void shutdown (MainFrame *main_frame)
void handle_message (const std::string &message)
Private Attributes
bool m_initialized { false }
wxEvtHandler * m_callback_evt_handler { nullptr }
Detailed Description
Constructor & Destructor Documentation
OtherInstanceMessageHandler() [1/2]
Slic3r::GUI::OtherInstanceMessageHandler::OtherInstanceMessageHandler () default
OtherInstanceMessageHandler() [2/2]
Slic3r::GUI::OtherInstanceMessageHandler::OtherInstanceMessageHandler (OtherInstanceMessageHandler const &) delete
~OtherInstanceMessageHandler()
Slic3r::GUI::OtherInstanceMessageHandler::~OtherInstanceMessageHandler () inline
{ assert(!m_initialized); }
References m_initialized.
Member Function Documentation
handle_message()
void Slic3r::GUI::OtherInstanceMessageHandler::handle_message (const std::string & message)
{
  BOOST_LOG_TRIVIAL(info) << "message from other instance: " << message;
  std::vector<std::string> args;
  bool parsed = unescape_strings_cstyle(message, args);
  assert(parsed);
  if (! parsed) {
    BOOST_LOG_TRIVIAL(error) << "message from other instance is incorrectly formatted: " << message;
    return;
  }
  std::vector<boost::filesystem::path> paths;
  std::vector<std::string> downloads;
  // Skip the first argument, it is the path to the slicer executable.
  auto it = args.begin();
  for (++ it; it != args.end(); ++ it) {
    boost::filesystem::path p = MessageHandlerInternal::get_path(*it);
    if (! p.string().empty())
      paths.emplace_back(p);
// TODO: There is a misterious slash appearing in recieved msg on windows
#ifdef _WIN32
    else if (it->rfind("prusaslicer://open/?file=", 0) == 0)
#else
      else if (it->rfind("prusaslicer://open?file=", 0) == 0)
#endif
      downloads.emplace_back(*it);
  }
  if (! paths.empty()) {
    //wxEvtHandler* evt_handler = wxGetApp().plater(); //assert here?
    //if (evt_handler) {
      wxPostEvent(m_callback_evt_handler, LoadFromOtherInstanceEvent(GUI::EVT_LOAD_MODEL_OTHER_INSTANCE, std::vector<boost::filesystem::path>(std::move(paths))));
    //}
  }
  if (!downloads.empty())
  {
    wxPostEvent(m_callback_evt_handler, StartDownloadOtherInstanceEvent(GUI::EVT_START_DOWNLOAD_OTHER_INSTANCE, std::vector<std::string>(std::move(downloads))));
  }
}
References error, Slic3r::GUI::MessageHandlerInternal::get_path(), m_callback_evt_handler, and Slic3r::unescape_strings_cstyle().
init()
void Slic3r::GUI::OtherInstanceMessageHandler::init (wxEvtHandler * callback_evt_handler)
{
  assert(!m_initialized);
  assert(m_callback_evt_handler == nullptr);
  if (m_initialized)
    return;
  m_initialized = true;
  m_callback_evt_handler = callback_evt_handler;
#if defined(__APPLE__)
  this->register_for_messages(wxGetApp().get_instance_hash_string());
#endif //__APPLE__
#ifdef BACKGROUND_MESSAGE_LISTENER
  m_thread = boost::thread((boost::bind(&OtherInstanceMessageHandler::listen, this)));
#endif //BACKGROUND_MESSAGE_LISTENER
}
References m_callback_evt_handler, and m_initialized.
operator=()
void Slic3r::GUI::OtherInstanceMessageHandler::operator= (OtherInstanceMessageHandler const &) delete
shutdown()
void Slic3r::GUI::OtherInstanceMessageHandler::shutdown (MainFrame * main_frame)
_WIN32
{
  BOOST_LOG_TRIVIAL(debug) << "message handler shutdown().";
#ifndef _WIN32
  instance_check_internal::delete_lockfile();
#endif
  assert(m_initialized);
  if (m_initialized) {
#ifdef _WIN32
    HWND hwnd = main_frame->GetHandle();
    RemoveProp(hwnd, L"Instance_Hash_Minor");
    RemoveProp(hwnd, L"Instance_Hash_Major");
#endif //_WIN32
#if __APPLE__
    //delete macos implementation
    this->unregister_for_messages();
#endif //__APPLE__
#ifdef BACKGROUND_MESSAGE_LISTENER
    if (m_thread.joinable()) {
      // Stop the worker thread, if running.
      {
        // Notify the worker thread to cancel wait on detection polling.
        std::lock_guard<std::mutex> lck(m_thread_stop_mutex);
        m_stop = true;
      }
      m_thread_stop_condition.notify_all();
      // Wait for the worker thread to stop.
      m_thread.join();
      m_stop = false;
    }
#endif //BACKGROUND_MESSAGE_LISTENER
    m_callback_evt_handler = nullptr;
    m_initialized = false;
  }
}
References Slic3r::instance_check_internal::delete_lockfile(), L, m_callback_evt_handler, and m_initialized.
Member Data Documentation
m_callback_evt_handler
wxEvtHandler* Slic3r::GUI::OtherInstanceMessageHandler::m_callback_evt_handler { nullptr } private
Referenced by handle_message(), init(), and shutdown().
m_initialized
bool Slic3r::GUI::OtherInstanceMessageHandler::m_initialized { false } private
Referenced by ~OtherInstanceMessageHandler(), init(), and shutdown().
The documentation for this class was generated from the following files:
src/slic3r/GUI/InstanceCheck.hpp
src/slic3r/GUI/InstanceCheck.cpp