Prusa Slicer: Slic3r::GUI::Worker Class Reference
Slic3r::GUI::Worker Class Reference abstract
#include <src/slic3r/GUI/Jobs/Worker.hpp>
Public Member Functions
virtual bool push (std::unique_ptr< Job > job)=0
virtual bool is_idle () const =0
virtual void cancel ()=0
virtual void cancel_all ()=0
virtual void process_events ()=0
virtual bool wait_for_current_job (unsigned timeout_ms=0)=0
virtual bool wait_for_idle (unsigned timeout_ms=0)=0
virtual ~Worker ()=default
Detailed Description
Constructor & Destructor Documentation
~Worker()
virtual Slic3r::GUI::Worker::~Worker () virtual default
Member Function Documentation
cancel()
virtual void Slic3r::GUI::Worker::cancel () pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, Slic3r::GUI::PlaterWorker< WorkerSubclass >, Slic3r::GUI::PlaterWorker< Slic3r::GUI::BoostThreadWorker >, and Slic3r::GUI::UIThreadWorker.
Referenced by Slic3r::GUI::stop_current_job().
cancel_all()
virtual void Slic3r::GUI::Worker::cancel_all () pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, Slic3r::GUI::PlaterWorker< WorkerSubclass >, Slic3r::GUI::PlaterWorker< Slic3r::GUI::BoostThreadWorker >, and Slic3r::GUI::UIThreadWorker.
Referenced by Slic3r::GUI::Plater::remove_selected(), Slic3r::GUI::replace_job(), Slic3r::GUI::MainFrame::shutdown(), and Slic3r::GUI::stop_queue().
is_idle()
virtual bool Slic3r::GUI::Worker::is_idle () const pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, Slic3r::GUI::PlaterWorker< WorkerSubclass >, Slic3r::GUI::PlaterWorker< Slic3r::GUI::BoostThreadWorker >, and Slic3r::GUI::UIThreadWorker.
Referenced by Slic3r::GUI::MainFrame::init_menubar_as_editor().
process_events()
virtual void Slic3r::GUI::Worker::process_events () pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, Slic3r::GUI::PlaterWorker< WorkerSubclass >, Slic3r::GUI::PlaterWorker< Slic3r::GUI::BoostThreadWorker >, and Slic3r::GUI::UIThreadWorker.
push()
virtual bool Slic3r::GUI::Worker::push (std::unique_ptr< Job > job) pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, Slic3r::GUI::PlaterWorker< WorkerSubclass >, Slic3r::GUI::PlaterWorker< Slic3r::GUI::BoostThreadWorker >, and Slic3r::GUI::UIThreadWorker.
Referenced by Slic3r::GUI::queue_job().
wait_for_current_job()
virtual bool Slic3r::GUI::Worker::wait_for_current_job (unsigned timeout_ms = 0) pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, Slic3r::GUI::PlaterWorker< WorkerSubclass >, Slic3r::GUI::PlaterWorker< Slic3r::GUI::BoostThreadWorker >, and Slic3r::GUI::UIThreadWorker.
Referenced by Slic3r::GUI::stop_current_job().
wait_for_idle()
virtual bool Slic3r::GUI::Worker::wait_for_idle (unsigned timeout_ms = 0) pure virtual
Implemented in Slic3r::GUI::BoostThreadWorker, Slic3r::GUI::PlaterWorker< WorkerSubclass >, Slic3r::GUI::PlaterWorker< Slic3r::GUI::BoostThreadWorker >, and Slic3r::GUI::UIThreadWorker.
Referenced by Slic3r::GUI::stop_queue().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Jobs/Worker.hpp