Prusa Slicer: Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex > Struct Template Reference
Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex > Struct Template Reference
#include <src/libslic3r/MeshSplitImpl.hpp>
Public Member Functions
NeighborVisitor (const indexed_triangle_set &its, const NeighborIndex &neighbor_index)
NeighborVisitor (const indexed_triangle_set &its, NeighborIndex &&aneighbor_index)
template<typename Visitor >
void visit (Visitor visitor)
Public Attributes
const indexed_triangle_set & its
const NeighborIndex & neighbor_index
Private Types
using stack_el = size_t
Private Member Functions
void push (const stack_el &s)
stack_el pop ()
Private Attributes
const NeighborIndex m_neighbor_index_data
std::vector< char > m_visited
std::vector< stack_el > m_facestack
size_t m_seed { 0 }
Detailed Description
template<class NeighborIndex>
struct Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >
Member Typedef Documentation
stack_el
template<class NeighborIndex > using Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::stack_el = size_t private
Constructor & Destructor Documentation
NeighborVisitor() [1/2]
template<class NeighborIndex > Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::NeighborVisitor (const indexed_triangle_set & its, const NeighborIndex & neighbor_index) inline
                                                                                          :
        its(its), neighbor_index(neighbor_index) {
        m_visited.assign(its.indices.size(), false);
        m_facestack.reserve(its.indices.size());
    }
References indexed_triangle_set::indices, Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::its, Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_facestack, and Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_visited.
NeighborVisitor() [2/2]
template<class NeighborIndex > Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::NeighborVisitor (const indexed_triangle_set & its, NeighborIndex && aneighbor_index) inline
                                                                                      :
        its(its), neighbor_index(m_neighbor_index_data), m_neighbor_index_data(std::move(aneighbor_index)) {
        m_visited.assign(its.indices.size(), false);
        m_facestack.reserve(its.indices.size());
    }
References indexed_triangle_set::indices, Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::its, Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_facestack, and Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_visited.
Member Function Documentation
pop()
template<class NeighborIndex > stack_el Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::pop () inline private
{ stack_el ret = m_facestack.back(); m_facestack.pop_back(); return ret; }
References Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_facestack.
Referenced by Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::visit().
push()
template<class NeighborIndex > void Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::push (const stack_el & s) inline private
{ m_facestack.emplace_back(s); }
References Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_facestack.
Referenced by Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::visit().
visit()
template<class NeighborIndex > template<typename Visitor > void Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::visit (Visitor visitor) inline
    {
        // find the next unvisited facet and push the index
        auto facet = std::find(m_visited.begin() + m_seed, m_visited.end(), false);
        m_seed = facet - m_visited.begin();
        if (facet != m_visited.end()) {
            // Skip this element in the next round.
            auto idx = m_seed ++;
            if (! visitor(idx))
                return;
            this->push(idx);
            m_visited[idx] = true;
            while (! m_facestack.empty()) {
                size_t facet_idx = this->pop();
                for (auto neighbor_idx : neighbor_index[facet_idx]) {
                    assert(neighbor_idx < int(m_visited.size()));
                    if (neighbor_idx >= 0 && !m_visited[neighbor_idx]) {
                        if (! visitor(size_t(neighbor_idx)))
                            return;
                        m_visited[neighbor_idx] = true;
                        this->push(stack_el(neighbor_idx));
                    }
                }
            }
        }
    }
References Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_facestack, Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_seed, Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_visited, Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::neighbor_index, Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::pop(), and Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::push().
Referenced by Slic3r::its_is_splittable(), Slic3r::its_number_of_patches(), and Slic3r::its_split().
Member Data Documentation
its
template<class NeighborIndex > const indexed_triangle_set& Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::its
Referenced by Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::NeighborVisitor(), and Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::NeighborVisitor().
m_facestack
template<class NeighborIndex > std::vector<stack_el> Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_facestack private
Referenced by Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::NeighborVisitor(), Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::NeighborVisitor(), Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::pop(), Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::push(), and Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::visit().
m_neighbor_index_data
template<class NeighborIndex > const NeighborIndex Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_neighbor_index_data private
m_seed
template<class NeighborIndex > size_t Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_seed { 0 } private
Referenced by Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::visit().
m_visited
template<class NeighborIndex > std::vector<char> Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::m_visited private
Referenced by Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::NeighborVisitor(), Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::NeighborVisitor(), and Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::visit().
neighbor_index
template<class NeighborIndex > const NeighborIndex& Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::neighbor_index
Referenced by Slic3r::meshsplit_detail::NeighborVisitor< NeighborIndex >::visit().
The documentation for this struct was generated from the following file:
src/libslic3r/MeshSplitImpl.hpp