Prusa Slicer: igl::copyleft::cgal::CSGTree Class Reference
igl::copyleft::cgal::CSGTree Class Reference
#include <src/libigl/igl/copyleft/cgal/CSGTree.h>
Public Types
typedef CGAL::Epeck::FT ExactScalar
typedef Eigen::MatrixXi POBF
typedef POBF::Index FIndex
typedef Eigen::Matrix< ExactScalar, Eigen::Dynamic, 3 > MatrixX3E
typedef Eigen::Matrix< FIndex, Eigen::Dynamic, 1 > VectorJ
Public Member Functions
CSGTree ()
CSGTree (const CSGTree &other)
CSGTree & operator= (CSGTree other)
CSGTree (CSGTree &&other)
CSGTree (const CSGTree &A, const CSGTree &B, const MeshBooleanType &type)
CSGTree (const CSGTree &A, const CSGTree &B, const std::string &s)
template<typename DerivedV >
CSGTree (const Eigen::PlainObjectBase< DerivedV > &V, const POBF &F)
const MatrixX3E & V () const
template<typename DerivedV >
DerivedV cast_V () const
const POBF & F () const
const VectorJ & J () const
const size_t & number_of_birth_faces () const
Private Attributes
MatrixX3E m_V
POBF m_F
VectorJ m_J
size_t m_number_of_birth_faces
Friends
void swap (CSGTree &first, CSGTree &second)
Detailed Description
Member Typedef Documentation
ExactScalar
typedef CGAL::Epeck::FT igl::copyleft::cgal::CSGTree::ExactScalar
FIndex
typedef POBF::Index igl::copyleft::cgal::CSGTree::FIndex
MatrixX3E
typedef Eigen::Matrix<ExactScalar,Eigen::Dynamic,3> igl::copyleft::cgal::CSGTree::MatrixX3E
POBF
typedef Eigen::MatrixXi igl::copyleft::cgal::CSGTree::POBF
VectorJ
typedef Eigen::Matrix<FIndex,Eigen::Dynamic,1> igl::copyleft::cgal::CSGTree::VectorJ
Constructor & Destructor Documentation
CSGTree() [1/6]
igl::copyleft::cgal::CSGTree::CSGTree () inline
          {
          }
CSGTree() [2/6]
igl::copyleft::cgal::CSGTree::CSGTree (const CSGTree & other) inline
            :
            // copy things
            m_V(other.m_V),
            // This is an issue if m_F is templated
            // https://forum.kde.org/viewtopic.php?f=74&t=128414
            m_F(other.m_F),
            m_J(other.m_J),
            m_number_of_birth_faces(other.m_number_of_birth_faces)
          {
          }
CSGTree() [3/6]
igl::copyleft::cgal::CSGTree::CSGTree (CSGTree && other) inline
                                  :
            // initialize via default constructor
            CSGTree()
          {
            swap(*this,other);
          }
References swap.
CSGTree() [4/6]
igl::copyleft::cgal::CSGTree::CSGTree (const CSGTree & A, const CSGTree & B, const MeshBooleanType & type) inline
          {
            // conduct boolean operation
            mesh_boolean(A.V(),A.F(),B.V(),B.F(),type,m_V,m_F,m_J);
            // reindex m_J
            std::for_each(m_J.data(),m_J.data()+m_J.size(),
              [&](typename VectorJ::Scalar & j) -> void
              {
                if(j < A.F().rows())
                {
                  j = A.J()(j);
                }else
                {
                  assert(j<(A.F().rows()+B.F().rows()));
                  j = A.number_of_birth_faces()+(B.J()(j-A.F().rows()));
                }
              });
            m_number_of_birth_faces =
              A.number_of_birth_faces() + B.number_of_birth_faces();
          }
References Eigen::PlainObjectBase< Derived >::data(), F(), m_F, m_J, m_V, igl::copyleft::cgal::mesh_boolean(), and V().
CSGTree() [5/6]
igl::copyleft::cgal::CSGTree::CSGTree (const CSGTree & A, const CSGTree & B, const std::string & s) inline
                                :
            CSGTree(A,B,string_to_mesh_boolean_type(s))
          {
            // do nothing (all done in constructor).
          }
CSGTree() [6/6]
template<typename DerivedV > igl::copyleft::cgal::CSGTree::CSGTree (const Eigen::PlainObjectBase< DerivedV > & V, const POBF & F) inline
          {
            m_V = V.template cast<ExactScalar>();
            m_F = F;
            // number of faces
            m_number_of_birth_faces = m_F.rows();
            // identity birth index
            m_J = VectorJ::LinSpaced(
              m_number_of_birth_faces,0,m_number_of_birth_faces-1);
          }
Member Function Documentation
cast_V()
template<typename DerivedV > DerivedV igl::copyleft::cgal::CSGTree::cast_V () const inline
          {
            DerivedV dV;
            dV.resize(m_V.rows(),m_V.cols());
            for(int i = 0;i<m_V.rows();i++)
            {
              for(int j = 0;j<m_V.cols();j++)
              {
                dV(i,j) = CGAL::to_double(m_V(i,j));
              }
            }
            return dV;
          }
References Eigen::PlainObjectBase< Derived >::cols(), and Eigen::PlainObjectBase< Derived >::rows().
F()
const POBF & igl::copyleft::cgal::CSGTree::F () const inline
          {
            return m_F;
          }
Referenced by CSGTree().
J()
const VectorJ & igl::copyleft::cgal::CSGTree::J () const inline
          {
            return m_J;
          }
number_of_birth_faces()
const size_t & igl::copyleft::cgal::CSGTree::number_of_birth_faces () const inline
          {
            return m_number_of_birth_faces;
          }
operator=()
CSGTree & igl::copyleft::cgal::CSGTree::operator= (CSGTree other) inline
          {
            swap(*this,other);
            return *this;
          }
References swap.
V()
const MatrixX3E & igl::copyleft::cgal::CSGTree::V () const inline
          {
            return m_V;
          }
Referenced by CSGTree().
Friends And Related Symbol Documentation
swap
void swap (CSGTree & first, CSGTree & second) friend
          {
            using std::swap;
            // swap things
            swap(first.m_V,second.m_V);
            // This is an issue if m_F is templated, similar to
            // https://forum.kde.org/viewtopic.php?f=74&t=128414
            swap(first.m_F,second.m_F);
            swap(first.m_J,second.m_J);
            swap(first.m_number_of_birth_faces,second.m_number_of_birth_faces);
          }
Referenced by CSGTree(), and operator=().
Member Data Documentation
m_F
POBF igl::copyleft::cgal::CSGTree::m_F private
Referenced by CSGTree().
m_J
VectorJ igl::copyleft::cgal::CSGTree::m_J private
Referenced by CSGTree().
m_number_of_birth_faces
size_t igl::copyleft::cgal::CSGTree::m_number_of_birth_faces private
m_V
MatrixX3E igl::copyleft::cgal::CSGTree::m_V private
Referenced by CSGTree().
The documentation for this class was generated from the following file:
src/libigl/igl/copyleft/cgal/CSGTree.h