Prusa Slicer: igl::opengl::glfw::imgui::ImGuiMenu Class Reference
igl::opengl::glfw::imgui::ImGuiMenu Class Reference
#include <src/libigl/igl/opengl/glfw/imgui/ImGuiMenu.h>
Public Member Functions
virtual IGL_INLINE void init (igl::opengl::glfw::Viewer *_viewer) override
virtual IGL_INLINE void reload_font (int font_size=13)
virtual IGL_INLINE void shutdown () override
virtual IGL_INLINE bool pre_draw () override
virtual IGL_INLINE bool post_draw () override
virtual IGL_INLINE void post_resize (int width, int height) override
virtual IGL_INLINE bool mouse_down (int button, int modifier) override
virtual IGL_INLINE bool mouse_up (int button, int modifier) override
virtual IGL_INLINE bool mouse_move (int mouse_x, int mouse_y) override
virtual IGL_INLINE bool mouse_scroll (float delta_y) override
virtual IGL_INLINE bool key_pressed (unsigned int key, int modifiers) override
virtual IGL_INLINE bool key_down (int key, int modifiers) override
virtual IGL_INLINE bool key_up (int key, int modifiers) override
virtual IGL_INLINE void draw_menu ()
virtual IGL_INLINE void draw_viewer_window ()
virtual IGL_INLINE void draw_viewer_menu ()
virtual IGL_INLINE void draw_custom_window ()
IGL_INLINE void draw_labels_window ()
IGL_INLINE void draw_labels (const igl::opengl::ViewerData &data)
IGL_INLINE void draw_text (Eigen::Vector3d pos, Eigen::Vector3d normal, const std::string &text)
IGL_INLINE float pixel_ratio ()
IGL_INLINE float hidpi_scaling ()
float menu_scaling ()
virtual IGL_INLINE bool load (std::string filename)
virtual IGL_INLINE bool save (std::string filename)
virtual IGL_INLINE bool serialize (std::vector< char > &buffer) const
virtual IGL_INLINE bool deserialize (const std::vector< char > &buffer)
virtual IGL_INLINE bool post_load ()
Public Attributes
std::function< void(void)> callback_draw_viewer_window
std::function< void(void)> callback_draw_viewer_menu
std::function< void(void)> callback_draw_custom_window
std::string plugin_name
Protected Attributes
float hidpi_scaling_
float pixel_ratio_
ImGuiContext * context_ = nullptr
Viewer * viewer
Detailed Description
Member Function Documentation
deserialize()
virtual IGL_INLINE bool igl::opengl::glfw::ViewerPlugin::deserialize (const std::vector< char > & buffer) inline virtual inherited
  {
    return false;
  }
Referenced by igl::opengl::glfw::serialization::deserialize().
draw_custom_window()
virtual IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::draw_custom_window () inline virtual
{ }
Referenced by draw_menu().
draw_labels()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::draw_labels (const igl::opengl::ViewerData & data)
{
  if (data.show_vertid)
  {
    for (int i = 0; i < data.V.rows(); ++i)
    {
      draw_text(data.V.row(i), data.V_normals.row(i), std::to_string(i));
    }
  }
  if (data.show_faceid)
  {
    for (int i = 0; i < data.F.rows(); ++i)
    {
      Eigen::RowVector3d p = Eigen::RowVector3d::Zero();
      for (int j = 0; j < data.F.cols(); ++j)
      {
        p += data.V.row(data.F(i,j));
      }
      p /= (double) data.F.cols();
      draw_text(p, data.F_normals.row(i), std::to_string(i));
    }
  }
  if (data.labels_positions.rows() > 0)
  {
    for (int i = 0; i < data.labels_positions.rows(); ++i)
    {
      draw_text(data.labels_positions.row(i), Eigen::Vector3d(0.0,0.0,0.0),
        data.labels_strings[i]);
    }
  }
}
References draw_text().
Referenced by draw_labels_window().
draw_labels_window()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::draw_labels_window ()
{
  // Text labels
  ImGui::SetNextWindowPos(ImVec2(0,0), ImGuiSetCond_Always);
  ImGui::SetNextWindowSize(ImGui::GetIO().DisplaySize, ImGuiSetCond_Always);
  bool visible = true;
  ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(0,0,0,0));
  ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0);
  ImGui::Begin("ViewerLabels", &visible,
      ImGuiWindowFlags_NoTitleBar
      | ImGuiWindowFlags_NoResize
      | ImGuiWindowFlags_NoMove
      | ImGuiWindowFlags_NoScrollbar
      | ImGuiWindowFlags_NoScrollWithMouse
      | ImGuiWindowFlags_NoCollapse
      | ImGuiWindowFlags_NoSavedSettings
      | ImGuiWindowFlags_NoInputs);
  for (const auto & data : viewer->data_list)
  {
    draw_labels(data);
  }
  ImGui::End();
  ImGui::PopStyleColor();
  ImGui::PopStyleVar();
}
References ImGui::Begin(), igl::opengl::glfw::Viewer::data_list, draw_labels(), ImGui::End(), ImGui::GetIO(), ImGuiCol_WindowBg, ImGuiStyleVar_WindowBorderSize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoInputs, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoScrollWithMouse, ImGuiWindowFlags_NoTitleBar, ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), and igl::opengl::glfw::ViewerPlugin::viewer.
Referenced by draw_menu().
draw_menu()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::draw_menu () virtual
{
  // Text labels
  draw_labels_window();
  // Viewer settings
  if (callback_draw_viewer_window) { callback_draw_viewer_window(); }
  else { draw_viewer_window(); }
  // Other windows
  if (callback_draw_custom_window) { callback_draw_custom_window(); }
  else { draw_custom_window(); }
}
References callback_draw_custom_window, callback_draw_viewer_window, draw_custom_window(), draw_labels_window(), and draw_viewer_window().
Referenced by post_draw().
draw_text()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::draw_text (Eigen::Vector3d pos, Eigen::Vector3d normal, const std::string & text)
{
  pos += normal * 0.005f * viewer->core.object_scale;
  Eigen::Vector3f coord = igl::project(Eigen::Vector3f(pos.cast<float>()),
    viewer->core.view, viewer->core.proj, viewer->core.viewport);
  // Draw text labels slightly bigger than normal text
  ImDrawList* drawList = ImGui::GetWindowDrawList();
  drawList->AddText(ImGui::GetFont(), ImGui::GetFontSize() * 1.2,
      ImVec2(coord[0]/pixel_ratio_, (viewer->core.viewport[3] - coord[1])/pixel_ratio_),
      ImGui::GetColorU32(ImVec4(0, 0, 10, 255)),
      &text[0], &text[0] + text.size());
}
References ImDrawList::AddText(), igl::opengl::glfw::Viewer::core, ImGui::GetColorU32(), ImGui::GetFont(), ImGui::GetFontSize(), ImGui::GetWindowDrawList(), igl::opengl::ViewerCore::object_scale, pixel_ratio_, igl::opengl::ViewerCore::proj, igl::project(), igl::opengl::ViewerCore::view, igl::opengl::glfw::ViewerPlugin::viewer, and igl::opengl::ViewerCore::viewport.
Referenced by draw_labels().
draw_viewer_menu()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::draw_viewer_menu () virtual
{
  // Workspace
  if (ImGui::CollapsingHeader("Workspace", ImGuiTreeNodeFlags_DefaultOpen))
  {
    float w = ImGui::GetContentRegionAvailWidth();
    float p = ImGui::GetStyle().FramePadding.x;
    if (ImGui::Button("Load##Workspace", ImVec2((w-p)/2.f, 0)))
    {
      viewer->load_scene();
    }
    ImGui::SameLine(0, p);
    if (ImGui::Button("Save##Workspace", ImVec2((w-p)/2.f, 0)))
    {
      viewer->save_scene();
    }
  }
  // Mesh
  if (ImGui::CollapsingHeader("Mesh", ImGuiTreeNodeFlags_DefaultOpen))
  {
    float w = ImGui::GetContentRegionAvailWidth();
    float p = ImGui::GetStyle().FramePadding.x;
    if (ImGui::Button("Load##Mesh", ImVec2((w-p)/2.f, 0)))
    {
      viewer->open_dialog_load_mesh();
    }
    ImGui::SameLine(0, p);
    if (ImGui::Button("Save##Mesh", ImVec2((w-p)/2.f, 0)))
    {
      viewer->open_dialog_save_mesh();
    }
  }
  // Viewing options
  if (ImGui::CollapsingHeader("Viewing Options", ImGuiTreeNodeFlags_DefaultOpen))
  {
    if (ImGui::Button("Center object", ImVec2(-1, 0)))
    {
      viewer->core.align_camera_center(viewer->data().V, viewer->data().F);
    }
    if (ImGui::Button("Snap canonical view", ImVec2(-1, 0)))
    {
      viewer->snap_to_canonical_quaternion();
    }
    // Zoom
    ImGui::PushItemWidth(80 * menu_scaling());
    ImGui::DragFloat("Zoom", &(viewer->core.camera_zoom), 0.05f, 0.1f, 20.0f);
    // Select rotation type
    int rotation_type = static_cast<int>(viewer->core.rotation_type);
    static Eigen::Quaternionf trackball_angle = Eigen::Quaternionf::Identity();
    static bool orthographic = true;
    if (ImGui::Combo("Camera Type", &rotation_type, "Trackball\0Two Axes\0002D Mode\0\0"))
    {
      using RT = igl::opengl::ViewerCore::RotationType;
      auto new_type = static_cast<RT>(rotation_type);
      if (new_type != viewer->core.rotation_type)
      {
        if (new_type == RT::ROTATION_TYPE_NO_ROTATION)
        {
          trackball_angle = viewer->core.trackball_angle;
          orthographic = viewer->core.orthographic;
          viewer->core.trackball_angle = Eigen::Quaternionf::Identity();
          viewer->core.orthographic = true;
        }
        else if (viewer->core.rotation_type == RT::ROTATION_TYPE_NO_ROTATION)
        {
          viewer->core.trackball_angle = trackball_angle;
          viewer->core.orthographic = orthographic;
        }
        viewer->core.set_rotation_type(new_type);
      }
    }
    // Orthographic view
    ImGui::Checkbox("Orthographic view", &(viewer->core.orthographic));
    ImGui::PopItemWidth();
  }
  // Draw options
  if (ImGui::CollapsingHeader("Draw Options", ImGuiTreeNodeFlags_DefaultOpen))
  {
    if (ImGui::Checkbox("Face-based", &(viewer->data().face_based)))
    {
      viewer->data().set_face_based(viewer->data().face_based);
    }
    ImGui::Checkbox("Show texture", &(viewer->data().show_texture));
    if (ImGui::Checkbox("Invert normals", &(viewer->data().invert_normals)))
    {
      viewer->data().dirty |= igl::opengl::MeshGL::DIRTY_NORMAL;
    }
    ImGui::Checkbox("Show overlay", &(viewer->data().show_overlay));
    ImGui::Checkbox("Show overlay depth", &(viewer->data().show_overlay_depth));
    ImGui::ColorEdit4("Background", viewer->core.background_color.data(),
        ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_PickerHueWheel);
    ImGui::ColorEdit4("Line color", viewer->data().line_color.data(),
        ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_PickerHueWheel);
    ImGui::PushItemWidth(ImGui::GetWindowWidth() * 0.3f);
    ImGui::DragFloat("Shininess", &(viewer->data().shininess), 0.05f, 0.0f, 100.0f);
    ImGui::PopItemWidth();
  }
  // Overlays
  if (ImGui::CollapsingHeader("Overlays", ImGuiTreeNodeFlags_DefaultOpen))
  {
    ImGui::Checkbox("Wireframe", &(viewer->data().show_lines));
    ImGui::Checkbox("Fill", &(viewer->data().show_faces));
    ImGui::Checkbox("Show vertex labels", &(viewer->data().show_vertid));
    ImGui::Checkbox("Show faces labels", &(viewer->data().show_faceid));
  }
}
References igl::opengl::ViewerCore::align_camera_center(), igl::opengl::ViewerCore::background_color, ImGui::Button(), igl::opengl::ViewerCore::camera_zoom, ImGui::Checkbox(), ImGui::CollapsingHeader(), ImGui::ColorEdit4(), ImGui::Combo(), igl::opengl::glfw::Viewer::core, igl::opengl::glfw::Viewer::data(), igl::opengl::ViewerData::dirty, igl::opengl::MeshGL::DIRTY_NORMAL, ImGui::DragFloat(), igl::opengl::ViewerData::F, igl::opengl::ViewerData::face_based, ImGuiStyle::FramePadding, ImGui::GetContentRegionAvailWidth(), ImGui::GetStyle(), ImGui::GetWindowWidth(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::Identity(), ImGuiColorEditFlags_NoInputs, ImGuiColorEditFlags_PickerHueWheel, ImGuiTreeNodeFlags_DefaultOpen, igl::opengl::ViewerData::invert_normals, igl::opengl::ViewerData::line_color, igl::opengl::glfw::Viewer::load_scene(), menu_scaling(), igl::opengl::glfw::Viewer::open_dialog_load_mesh(), igl::opengl::glfw::Viewer::open_dialog_save_mesh(), igl::opengl::ViewerCore::orthographic, ImGui::PopItemWidth(), ImGui::PushItemWidth(), igl::opengl::ViewerCore::rotation_type, ImGui::SameLine(), igl::opengl::glfw::Viewer::save_scene(), igl::opengl::ViewerData::set_face_based(), igl::opengl::ViewerCore::set_rotation_type(), igl::opengl::ViewerData::shininess, igl::opengl::ViewerData::show_faceid, igl::opengl::ViewerData::show_faces, igl::opengl::ViewerData::show_lines, igl::opengl::ViewerData::show_overlay, igl::opengl::ViewerData::show_overlay_depth, igl::opengl::ViewerData::show_texture, igl::opengl::ViewerData::show_vertid, igl::opengl::glfw::Viewer::snap_to_canonical_quaternion(), igl::opengl::ViewerCore::trackball_angle, igl::opengl::ViewerData::V, igl::opengl::glfw::ViewerPlugin::viewer, and ImVec2::x.
Referenced by draw_viewer_window().
draw_viewer_window()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::draw_viewer_window () virtual
{
  float menu_width = 180.f * menu_scaling();
  ImGui::SetNextWindowPos(ImVec2(0.0f, 0.0f), ImGuiSetCond_FirstUseEver);
  ImGui::SetNextWindowSize(ImVec2(0.0f, 0.0f), ImGuiSetCond_FirstUseEver);
  ImGui::SetNextWindowSizeConstraints(ImVec2(menu_width, -1.0f), ImVec2(menu_width, -1.0f));
  bool _viewer_menu_visible = true;
  ImGui::Begin(
      "Viewer", &_viewer_menu_visible,
      ImGuiWindowFlags_NoSavedSettings
      | ImGuiWindowFlags_AlwaysAutoResize
  );
  ImGui::PushItemWidth(ImGui::GetWindowWidth() * 0.4f);
  if (callback_draw_viewer_menu) { callback_draw_viewer_menu(); }
  else { draw_viewer_menu(); }
  ImGui::PopItemWidth();
  ImGui::End();
}
References ImGui::Begin(), callback_draw_viewer_menu, draw_viewer_menu(), ImGui::End(), ImGui::GetWindowWidth(), ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoSavedSettings, menu_scaling(), ImGui::PopItemWidth(), ImGui::PushItemWidth(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), and ImGui::SetNextWindowSizeConstraints().
Referenced by draw_menu().
hidpi_scaling()
IGL_INLINE float igl::opengl::glfw::imgui::ImGuiMenu::hidpi_scaling ()
{
  // Computes scaling factor for hidpi devices
  float xscale, yscale;
  GLFWwindow* window = glfwGetCurrentContext();
  glfwGetWindowContentScale(window, &xscale, &yscale);
  return 0.5 * (xscale + yscale);
}
Referenced by pre_draw(), and reload_font().
init()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::init (igl::opengl::glfw::Viewer * _viewer) override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  ViewerPlugin::init(_viewer);
  // Setup ImGui binding
  if (_viewer)
  {
    if (context_ == nullptr)
    {
      context_ = ImGui::CreateContext();
    }
    ImGui_ImplGlfwGL3_Init(viewer->window, false);
    ImGui::GetIO().IniFilename = nullptr;
    ImGui::StyleColorsDark();
    ImGuiStyle& style = ImGui::GetStyle();
    style.FrameRounding = 5.0f;
    reload_font();
  }
}
References context_, ImGui::CreateContext(), ImGui::GetIO(), ImGui::GetStyle(), ImGuiIO::IniFilename, igl::opengl::glfw::ViewerPlugin::init(), reload_font(), style, ImGui::StyleColorsDark(), igl::opengl::glfw::ViewerPlugin::viewer, and igl::opengl::glfw::Viewer::window.
key_down()
IGL_INLINE bool igl::opengl::glfw::imgui::ImGuiMenu::key_down (int key, int modifiers) override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  ImGui_ImplGlfwGL3_KeyCallback(viewer->window, key, 0, GLFW_PRESS, modifiers);
  return ImGui::GetIO().WantCaptureKeyboard;
}
References ImGui::GetIO(), igl::opengl::glfw::ViewerPlugin::viewer, ImGuiIO::WantCaptureKeyboard, and igl::opengl::glfw::Viewer::window.
key_pressed()
IGL_INLINE bool igl::opengl::glfw::imgui::ImGuiMenu::key_pressed (unsigned int key, int modifiers) override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  ImGui_ImplGlfwGL3_CharCallback(nullptr, key);
  return ImGui::GetIO().WantCaptureKeyboard;
}
References ImGui::GetIO(), and ImGuiIO::WantCaptureKeyboard.
key_up()
IGL_INLINE bool igl::opengl::glfw::imgui::ImGuiMenu::key_up (int key, int modifiers) override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  ImGui_ImplGlfwGL3_KeyCallback(viewer->window, key, 0, GLFW_RELEASE, modifiers);
  return ImGui::GetIO().WantCaptureKeyboard;
}
References ImGui::GetIO(), igl::opengl::glfw::ViewerPlugin::viewer, ImGuiIO::WantCaptureKeyboard, and igl::opengl::glfw::Viewer::window.
load()
virtual IGL_INLINE bool igl::opengl::glfw::ViewerPlugin::load (std::string filename) inline virtual inherited
  {
    return false;
  }
menu_scaling()
float igl::opengl::glfw::imgui::ImGuiMenu::menu_scaling () inline
{ return hidpi_scaling_ / pixel_ratio_; }
References hidpi_scaling_, and pixel_ratio_.
Referenced by draw_viewer_menu(), and draw_viewer_window().
mouse_down()
IGL_INLINE bool igl::opengl::glfw::imgui::ImGuiMenu::mouse_down (int button, int modifier) override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  ImGui_ImplGlfwGL3_MouseButtonCallback(viewer->window, button, GLFW_PRESS, modifier);
  return ImGui::GetIO().WantCaptureMouse;
}
References ImGui::GetIO(), igl::opengl::glfw::ViewerPlugin::viewer, ImGuiIO::WantCaptureMouse, and igl::opengl::glfw::Viewer::window.
mouse_move()
IGL_INLINE bool igl::opengl::glfw::imgui::ImGuiMenu::mouse_move (int mouse_x, int mouse_y) override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  return ImGui::GetIO().WantCaptureMouse;
}
References ImGui::GetIO(), and ImGuiIO::WantCaptureMouse.
mouse_scroll()
IGL_INLINE bool igl::opengl::glfw::imgui::ImGuiMenu::mouse_scroll (float delta_y) override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  ImGui_ImplGlfwGL3_ScrollCallback(viewer->window, 0.f, delta_y);
  return ImGui::GetIO().WantCaptureMouse;
}
References ImGui::GetIO(), igl::opengl::glfw::ViewerPlugin::viewer, ImGuiIO::WantCaptureMouse, and igl::opengl::glfw::Viewer::window.
mouse_up()
IGL_INLINE bool igl::opengl::glfw::imgui::ImGuiMenu::mouse_up (int button, int modifier) override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  return ImGui::GetIO().WantCaptureMouse;
}
References ImGui::GetIO(), and ImGuiIO::WantCaptureMouse.
pixel_ratio()
IGL_INLINE float igl::opengl::glfw::imgui::ImGuiMenu::pixel_ratio ()
{
  // Computes pixel ratio for hidpi devices
  int buf_size[2];
  int win_size[2];
  GLFWwindow* window = glfwGetCurrentContext();
  glfwGetFramebufferSize(window, &buf_size[0], &buf_size[1]);
  glfwGetWindowSize(window, &win_size[0], &win_size[1]);
  return (float) buf_size[0] / (float) win_size[0];
}
Referenced by reload_font().
post_draw()
IGL_INLINE bool igl::opengl::glfw::imgui::ImGuiMenu::post_draw () override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  draw_menu();
  ImGui::Render();
  return false;
}
References draw_menu(), and ImGui::Render().
post_load()
virtual IGL_INLINE bool igl::opengl::glfw::ViewerPlugin::post_load () inline virtual inherited
  {
    return false;
  }
post_resize()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::post_resize (int width, int height) override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  if (context_)
  {
    ImGui::GetIO().DisplaySize.x = float(width);
    ImGui::GetIO().DisplaySize.y = float(height);
  }
}
References context_, ImGuiIO::DisplaySize, ImGui::GetIO(), ImVec2::x, and ImVec2::y.
pre_draw()
IGL_INLINE bool igl::opengl::glfw::imgui::ImGuiMenu::pre_draw () override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  glfwPollEvents();
  // Check whether window dpi has changed
  float scaling = hidpi_scaling();
  if (std::abs(scaling - hidpi_scaling_) > 1e-5)
  {
    reload_font();
    ImGui_ImplGlfwGL3_InvalidateDeviceObjects();
  }
  ImGui_ImplGlfwGL3_NewFrame();
  return false;
}
References hidpi_scaling(), hidpi_scaling_, and reload_font().
reload_font()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::reload_font (int font_size = 13) virtual
{
  hidpi_scaling_ = hidpi_scaling();
  pixel_ratio_ = pixel_ratio();
  ImGuiIO& io = ImGui::GetIO();
  io.Fonts->Clear();
  io.Fonts->AddFontFromMemoryCompressedTTF(droid_sans_compressed_data,
    droid_sans_compressed_size, font_size * hidpi_scaling_);
  io.FontGlobalScale = 1.0 / pixel_ratio_;
}
References ImFontAtlas::AddFontFromMemoryCompressedTTF(), ImFontAtlas::Clear(), ImGuiIO::FontGlobalScale, ImGuiIO::Fonts, ImGui::GetIO(), hidpi_scaling(), hidpi_scaling_, pixel_ratio(), and pixel_ratio_.
Referenced by init(), and pre_draw().
save()
virtual IGL_INLINE bool igl::opengl::glfw::ViewerPlugin::save (std::string filename) inline virtual inherited
  {
    return false;
  }
serialize()
virtual IGL_INLINE bool igl::opengl::glfw::ViewerPlugin::serialize (std::vector< char > & buffer) const inline virtual inherited
  {
    return false;
  }
Referenced by igl::opengl::glfw::serialization::serialize().
shutdown()
IGL_INLINE void igl::opengl::glfw::imgui::ImGuiMenu::shutdown () override virtual
Reimplemented from igl::opengl::glfw::ViewerPlugin.
{
  // Cleanup
  ImGui_ImplGlfwGL3_Shutdown();
  ImGui::DestroyContext(context_);
  context_ = nullptr;
}
References context_, and ImGui::DestroyContext().
Member Data Documentation
callback_draw_custom_window
std::function<void(void)> igl::opengl::glfw::imgui::ImGuiMenu::callback_draw_custom_window
Referenced by draw_menu().
callback_draw_viewer_menu
std::function<void(void)> igl::opengl::glfw::imgui::ImGuiMenu::callback_draw_viewer_menu
Referenced by draw_viewer_window().
callback_draw_viewer_window
std::function<void(void)> igl::opengl::glfw::imgui::ImGuiMenu::callback_draw_viewer_window
Referenced by draw_menu().
context_
ImGuiContext* igl::opengl::glfw::imgui::ImGuiMenu::context_ = nullptr protected
Referenced by init(), post_resize(), and shutdown().
hidpi_scaling_
float igl::opengl::glfw::imgui::ImGuiMenu::hidpi_scaling_ protected
Referenced by menu_scaling(), pre_draw(), and reload_font().
pixel_ratio_
float igl::opengl::glfw::imgui::ImGuiMenu::pixel_ratio_ protected
Referenced by draw_text(), menu_scaling(), and reload_font().
plugin_name
std::string igl::opengl::glfw::ViewerPlugin::plugin_name inherited
Referenced by igl::opengl::glfw::ViewerPlugin::ViewerPlugin().
viewer
Viewer* igl::opengl::glfw::ViewerPlugin::viewer protected inherited
Referenced by draw_labels_window(), draw_text(), draw_viewer_menu(), init(), igl::opengl::glfw::ViewerPlugin::init(), key_down(), key_up(), mouse_down(), and mouse_scroll().
The documentation for this class was generated from the following files:
src/libigl/igl/opengl/glfw/imgui/ImGuiMenu.h
src/libigl/igl/opengl/glfw/imgui/ImGuiMenu.cpp