Prusa Slicer: Slic3r::ClipperUtils::ExPolygonProvider Struct Reference
Slic3r::ClipperUtils::ExPolygonProvider Struct Reference
#include <src/libslic3r/ClipperUtils.hpp>
Classes
struct iterator
Public Member Functions
ExPolygonProvider (const ExPolygon &expoly)
iterator cbegin () const
iterator begin () const
iterator cend () const
iterator end () const
size_t size () const
Private Attributes
const ExPolygon & m_expoly
Detailed Description
Constructor & Destructor Documentation
ExPolygonProvider()
Slic3r::ClipperUtils::ExPolygonProvider::ExPolygonProvider (const ExPolygon & expoly) inline
: m_expoly(expoly) {}
Member Function Documentation
begin()
iterator Slic3r::ClipperUtils::ExPolygonProvider::begin () const inline
{ return this->cbegin(); }
References cbegin().
cbegin()
iterator Slic3r::ClipperUtils::ExPolygonProvider::cbegin () const inline
{ return iterator(m_expoly, 0); }
References m_expoly.
Referenced by begin().
cend()
iterator Slic3r::ClipperUtils::ExPolygonProvider::cend () const inline
{ return iterator(m_expoly, m_expoly.holes.size() + 1); }
References Slic3r::ExPolygon::holes, and m_expoly.
Referenced by end().
end()
iterator Slic3r::ClipperUtils::ExPolygonProvider::end () const inline
{ return this->cend(); }
References cend().
size()
size_t Slic3r::ClipperUtils::ExPolygonProvider::size () const inline
{ return m_expoly.holes.size() + 1; }
References Slic3r::ExPolygon::holes, and m_expoly.
Member Data Documentation
m_expoly
const ExPolygon& Slic3r::ClipperUtils::ExPolygonProvider::m_expoly private
Referenced by cbegin(), cend(), and size().
The documentation for this struct was generated from the following file:
src/libslic3r/ClipperUtils.hpp