Prusa Slicer: Slic3r::csg::detail Namespace Reference
Slic3r::csg::detail Namespace Reference
Functions
void merge_slices (csg::CSGType op, size_t i, std::vector< ExPolygons > &target, std::vector< ExPolygons > &source)
void collect_nonempty_indices (csg::CSGType op, const std::vector< float > &slicegrid, const std::vector< ExPolygons > &slices, std::vector< size_t > &indices)
void perform_csg (CSGType op, VoxelGridPtr &dst, VoxelGridPtr &src)
Function Documentation
collect_nonempty_indices()
void Slic3r::csg::detail::collect_nonempty_indices (csg::CSGType op, const std::vector< float > & slicegrid, const std::vector< ExPolygons > & slices, std::vector< size_t > & indices) inline
{
    indices.clear();
    for (size_t i = 0; i < slicegrid.size(); ++i) {
        if (op == CSGType::Intersection || !slices[i].empty())
            indices.emplace_back(i);
    }
}
References Slic3r::empty(), and Slic3r::csg::Intersection.
merge_slices()
void Slic3r::csg::detail::merge_slices (csg::CSGType op, size_t i, std::vector< ExPolygons > & target, std::vector< ExPolygons > & source) inline
{
    switch(op) {
    case CSGType::Union:
        for (ExPolygon &expoly : source[i])
            target[i].emplace_back(std::move(expoly));
        break;
    case CSGType::Difference:
        target[i] = diff_ex(target[i], source[i]);
        break;
    case CSGType::Intersection:
        target[i] = intersection_ex(target[i], source[i]);
        break;
    }
}
References Slic3r::diff_ex(), Slic3r::csg::Difference, Slic3r::csg::Intersection, Slic3r::intersection_ex(), and Slic3r::csg::Union.
perform_csg()
void Slic3r::csg::detail::perform_csg (CSGType op, VoxelGridPtr & dst, VoxelGridPtr & src) inline
{
    if (!dst || !src)
        return;
    switch (op) {
    case CSGType::Union:
        if (is_grid_empty(*dst) && !is_grid_empty(*src))
            dst = clone(*src);
        else
            grid_union(*dst, *src);
        break;
    case CSGType::Difference:
        grid_difference(*dst, *src);
        break;
    case CSGType::Intersection:
        grid_intersection(*dst, *src);
        break;
    }
}
References Slic3r::clone(), Slic3r::csg::Difference, Slic3r::grid_difference(), Slic3r::grid_intersection(), Slic3r::grid_union(), Slic3r::csg::Intersection, Slic3r::is_grid_empty(), and Slic3r::csg::Union.