Prusa Slicer: BitmapTextRenderer Class Reference
BitmapTextRenderer Class Reference
#include <src/slic3r/GUI/ExtraRenderers.hpp>
Public Member Functions
BitmapTextRenderer (bool use_markup=false, wxDataViewCellMode mode=wxDATAVIEW_CELL_EDITABLE, int align=wxDVR_DEFAULT_ALIGNMENT)
~BitmapTextRenderer ()
void EnableMarkup (bool enable=true)
bool SetValue (const wxVariant &value) override
bool GetValue (wxVariant &value) const override
virtual bool Render (wxRect cell, wxDC *dc, int state) override
virtual wxSize GetSize () const override
bool HasEditorCtrl () const override
wxWindow * CreateEditorCtrl (wxWindow *parent, wxRect labelRect, const wxVariant &value) override
bool GetValueFromEditorCtrl (wxWindow *ctrl, wxVariant &value) override
bool WasCanceled () const
void set_can_create_editor_ctrl_function (std::function< bool()> can_create_fn)
Private Attributes
DataViewBitmapText m_value
bool m_was_unusable_symbol { false }
std::function< bool()> can_create_editor_ctrl { nullptr }
Detailed Description
Constructor & Destructor Documentation
BitmapTextRenderer()
BitmapTextRenderer::BitmapTextRenderer (bool use_markup = false, wxDataViewCellMode mode = wxDATAVIEW_CELL_EDITABLE, int align = wxDVR_DEFAULT_ALIGNMENT) inline
      :
    wxDataViewCustomRenderer(wxT("DataViewBitmapText"), mode, align)
    {
        EnableMarkup(use_markup);
    }
~BitmapTextRenderer()
BitmapTextRenderer::~BitmapTextRenderer ()
{
#ifdef SUPPORTS_MARKUP
    #ifdef wxHAS_GENERIC_DATAVIEWCTRL
    delete m_markupText;
    #endif //wxHAS_GENERIC_DATAVIEWCTRL
#endif // SUPPORTS_MARKUP
}
Member Function Documentation
CreateEditorCtrl()
wxWindow * BitmapTextRenderer::CreateEditorCtrl (wxWindow * parent, wxRect labelRect, const wxVariant & value) override
{
    if (can_create_editor_ctrl && !can_create_editor_ctrl())
        return nullptr;
    DataViewBitmapText data;
    data << value;
    m_was_unusable_symbol = false;
    wxPoint position = labelRect.GetPosition();
    if (data.GetBitmap().IsOk()) {
        const int bmp_width = data.GetBitmap().GetWidth();
        position.x += bmp_width;
        labelRect.SetWidth(labelRect.GetWidth() - bmp_width);
    }
#ifdef __WXMSW__
    // Case when from some reason we try to create next EditorCtrl till old one was not deleted
    if (auto children = parent->GetChildren(); children.GetCount() > 0)
        for (auto child : children)
            if (dynamic_cast<wxTextCtrl*>(child)) {
                parent->RemoveChild(child);
                child->Destroy();
                break;
            }
#endif // __WXMSW__
    wxTextCtrl* text_editor = new wxTextCtrl(parent, wxID_ANY, data.GetText(),
                                             position, labelRect.GetSize(), wxTE_PROCESS_ENTER);
    text_editor->SetInsertionPointEnd();
    text_editor->SelectAll();
    return text_editor;
}
References can_create_editor_ctrl, and m_was_unusable_symbol.
EnableMarkup()
void BitmapTextRenderer::EnableMarkup (bool enable = true)
{
#ifdef SUPPORTS_MARKUP
#ifdef wxHAS_GENERIC_DATAVIEWCTRL
    if (enable) {
        if (!m_markupText)
            m_markupText = new wxItemMarkupText(wxString());
    }
    else {
        if (m_markupText) {
            delete m_markupText;
            m_markupText = nullptr;
        }
    }
#else
    is_markupText = enable;
#endif //wxHAS_GENERIC_DATAVIEWCTRL
#endif // SUPPORTS_MARKUP
}
GetSize()
wxSize BitmapTextRenderer::GetSize () const override virtual
{
    if (!m_value.GetText().empty())
    {
        wxSize size;
#if defined(SUPPORTS_MARKUP) && defined(wxHAS_GENERIC_DATAVIEWCTRL)
        if (m_markupText)
        {
            wxDataViewCtrl* const view = GetView();
            wxClientDC dc(view);
            if (GetAttr().HasFont())
                dc.SetFont(GetAttr().GetEffectiveFont(view->GetFont()));
            size = m_markupText->Measure(dc);
            int lines = m_value.GetText().Freq('\n') + 1;
            size.SetHeight(size.GetHeight() * lines);
        }
        else
#endif // SUPPORTS_MARKUP && wxHAS_GENERIC_DATAVIEWCTRL
            size = GetTextExtent(m_value.GetText());
        if (m_value.GetBitmap().IsOk())
            size.x += m_value.GetBitmap().GetWidth() + 4;
        return size;
    }
    return wxSize(80, 20);
}
References DataViewBitmapText::GetBitmap(), DataViewBitmapText::GetText(), and m_value.
GetValue()
bool BitmapTextRenderer::GetValue (wxVariant & value) const override
{
    return false;
}
GetValueFromEditorCtrl()
bool BitmapTextRenderer::GetValueFromEditorCtrl (wxWindow * ctrl, wxVariant & value) override
{
    wxTextCtrl* text_editor = wxDynamicCast(ctrl, wxTextCtrl);
    if (!text_editor || text_editor->GetValue().IsEmpty())
        return false;
    m_was_unusable_symbol = Slic3r::GUI::Plater::has_illegal_filename_characters(text_editor->GetValue());
    if (m_was_unusable_symbol)
        return false;
    // The icon can't be edited so get its old value and reuse it.
    wxVariant valueOld;
    GetView()->GetModel()->GetValue(valueOld, m_item, /*colName*/0);
    DataViewBitmapText bmpText;
    bmpText << valueOld;
    // But replace the text with the value entered by user.
    bmpText.SetText(text_editor->GetValue());
    value << bmpText;
    return true;
}
References Slic3r::GUI::Plater::has_illegal_filename_characters(), m_was_unusable_symbol, and DataViewBitmapText::SetText().
HasEditorCtrl()
bool BitmapTextRenderer::HasEditorCtrl () const inline override
    {
#ifdef __WXOSX__
        return false;
#else
        return true;
#endif
    }
Render()
bool BitmapTextRenderer::Render (wxRect cell, wxDC * dc, int state) override virtual
{
    int xoffset = 0;
    const wxBitmap& icon = m_value.GetBitmap();
    if (icon.IsOk())
    {
        wxSize icon_sz = get_size(icon);
        dc->DrawBitmap(icon, rect.x, rect.y + (rect.height - icon_sz.y) / 2);
        xoffset = icon_sz.x + 4;
    }
#if defined(SUPPORTS_MARKUP) && defined(wxHAS_GENERIC_DATAVIEWCTRL)
    if (m_markupText)
    {
        rect.x += xoffset;
        m_markupText->Render(GetView(), *dc, rect, 0, GetEllipsizeMode());
    }
    else
#endif // SUPPORTS_MARKUP && wxHAS_GENERIC_DATAVIEWCTRL
#ifdef _WIN32
        // workaround for Windows DarkMode : Don't respect to the state & wxDATAVIEW_CELL_SELECTED to avoid update of the text color
        RenderText(m_value.GetText(), xoffset, rect, dc, state & wxDATAVIEW_CELL_SELECTED ? 0 :state);
#else
        RenderText(m_value.GetText(), xoffset, rect, dc, state);
#endif
    return true;
}
References DataViewBitmapText::GetBitmap(), DataViewBitmapText::GetText(), and m_value.
set_can_create_editor_ctrl_function()
void BitmapTextRenderer::set_can_create_editor_ctrl_function (std::function< bool()> can_create_fn) inline
{ can_create_editor_ctrl = can_create_fn; }
References can_create_editor_ctrl.
Referenced by Slic3r::GUI::ObjectList::create_objects_ctrl().
SetValue()
bool BitmapTextRenderer::SetValue (const wxVariant & value) override
{
    m_value << value;
#ifdef SUPPORTS_MARKUP
#ifdef wxHAS_GENERIC_DATAVIEWCTRL
    if (m_markupText)
        m_markupText->SetMarkup(m_value.GetText());
    /*
#else
#if defined(__WXGTK__)
   GValue gvalue = G_VALUE_INIT;
    g_value_init(&gvalue, G_TYPE_STRING);
    g_value_set_string(&gvalue, wxGTK_CONV_FONT(str.GetText(), GetOwner()->GetOwner()->GetFont()));
    g_object_set_property(G_OBJECT(m_renderer/ *.GetText()* /), is_markupText ? "markup" : "text", &gvalue);
    g_value_unset(&gvalue);
#endif // __WXGTK__
    */
#endif // wxHAS_GENERIC_DATAVIEWCTRL
#endif // SUPPORTS_MARKUP
    return true;
}
References DataViewBitmapText::GetText(), and m_value.
WasCanceled()
bool BitmapTextRenderer::WasCanceled () const inline
{ return m_was_unusable_symbol; }
References m_was_unusable_symbol.
Member Data Documentation
can_create_editor_ctrl
std::function<bool()> BitmapTextRenderer::can_create_editor_ctrl { nullptr } private
Referenced by CreateEditorCtrl(), and set_can_create_editor_ctrl_function().
m_value
DataViewBitmapText BitmapTextRenderer::m_value private
Referenced by GetSize(), Render(), and SetValue().
m_was_unusable_symbol
bool BitmapTextRenderer::m_was_unusable_symbol { false } private
Referenced by CreateEditorCtrl(), GetValueFromEditorCtrl(), and WasCanceled().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ExtraRenderers.hpp
src/slic3r/GUI/ExtraRenderers.cpp