Prusa Slicer: Slic3r::EdgeGrid::Grid::ClosestPointResult Struct Reference
Slic3r::EdgeGrid::Grid::ClosestPointResult Struct Reference
#include <src/libslic3r/EdgeGrid.hpp>
Public Member Functions
bool valid () const
Public Attributes
size_t contour_idx = size_t(-1)
size_t start_point_idx = size_t(-1)
double distance = std::numeric_limits<double>::max()
double t = 0.
Detailed Description
Member Function Documentation
valid()
bool Slic3r::EdgeGrid::Grid::ClosestPointResult::valid () const inline
{ return contour_idx != size_t(-1); }
References contour_idx.
Referenced by Slic3r::create_boundary_infill_graph().
Member Data Documentation
contour_idx
size_t Slic3r::EdgeGrid::Grid::ClosestPointResult::contour_idx = size_t(-1)
Referenced by Slic3r::EdgeGrid::Grid::closest_point_signed_distance(), and valid().
distance
double Slic3r::EdgeGrid::Grid::ClosestPointResult::distance = std::numeric_limits<double>::max()
Referenced by Slic3r::EdgeGrid::Grid::closest_point_signed_distance(), and Slic3r::create_boundary_infill_graph().
start_point_idx
size_t Slic3r::EdgeGrid::Grid::ClosestPointResult::start_point_idx = size_t(-1)
Referenced by Slic3r::EdgeGrid::Grid::closest_point_signed_distance().
t
double Slic3r::EdgeGrid::Grid::ClosestPointResult::t = 0.
Referenced by Slic3r::EdgeGrid::Grid::closest_point_signed_distance().
The documentation for this struct was generated from the following file:
src/libslic3r/EdgeGrid.hpp