Prusa Slicer: Slic3r::ExPolygonsIndices Class Reference
Slic3r::ExPolygonsIndices Class Reference
Keep conversion from ExPolygonsIndex to Index and vice versa ExPolygonsIndex .. contour(or hole) point from ExPolygons Index .. continous number.
#include <src/libslic3r/ExPolygonsIndex.hpp>
Public Member Functions
ExPolygonsIndices (const ExPolygons &shapes)
uint32_t cvt (const ExPolygonsIndex &id) const
Convert to one index number.
ExPolygonsIndex cvt (uint32_t index) const
Separate to multi index.
bool is_last_point (const ExPolygonsIndex &id) const
Check whether id is last point in polygon.
uint32_t get_count () const
Count of points in expolygons.
Private Attributes
std::vector< std::vector< uint32_t > > m_offsets
uint32_t m_count
Detailed Description
Keep conversion from ExPolygonsIndex to Index and vice versa ExPolygonsIndex .. contour(or hole) point from ExPolygons Index .. continous number.
index is used to address lines and points as result from function Slic3r::to_lines, Slic3r::to_points
Constructor & Destructor Documentation
ExPolygonsIndices()
ExPolygonsIndices::ExPolygonsIndices (const ExPolygons & shapes)
{
    // prepare offsets
    m_offsets.reserve(shapes.size());
    uint32_t offset = 0;
    for (const ExPolygon &shape : shapes) {
        assert(!shape.contour.points.empty());
        std::vector<uint32_t> shape_offsets;
        shape_offsets.reserve(shape.holes.size() + 1);
        shape_offsets.push_back(offset);
        offset += shape.contour.points.size();
        for (const Polygon &hole: shape.holes) {
            shape_offsets.push_back(offset);
            offset += hole.points.size();
        }
        m_offsets.push_back(std::move(shape_offsets));
    }
    m_count = offset;
}
References m_count, m_offsets, Slic3r::offset(), and Slic3r::MultiPoint::points.
Member Function Documentation
cvt() [1/2]
uint32_t ExPolygonsIndices::cvt (const ExPolygonsIndex & id) const
Convert to one index number.
Parameters
id Compose of adress into expolygons
Returns
Index
{
    assert(id.expolygons_index < m_offsets.size());
    const std::vector<uint32_t> &shape_offset = m_offsets[id.expolygons_index];
    assert(id.polygon_index < shape_offset.size());
    uint32_t res = shape_offset[id.polygon_index] + id.point_index;
    assert(res < m_count);
    return res;
}
References m_count, and m_offsets.
Referenced by priv::choose_best_distance(), priv::collect_close_points(), Slic3r::cut_surface(), Slic3r::Emboss::divide_segments_for_close_point(), priv::fill_shape_distances(), priv::find_close_point(), priv::get_closest_point_index(), priv::is_face_inside(), and priv::select_patches().
cvt() [2/2]
ExPolygonsIndex ExPolygonsIndices::cvt (uint32_t index) const
Separate to multi index.
Parameters
index adress into expolygons
Returns
{
    assert(index < m_count);
    ExPolygonsIndex result{0, 0, 0};
    // find expolygon index
    auto fn = [](const std::vector<uint32_t> &offsets, uint32_t index) { return offsets[0] < index; };
    auto it = std::lower_bound(m_offsets.begin() + 1, m_offsets.end(), index, fn);
    result.expolygons_index = it - m_offsets.begin();
    if (it == m_offsets.end() || it->at(0) != index) --result.expolygons_index;
    // find polygon index
    const std::vector<uint32_t> &shape_offset = m_offsets[result.expolygons_index];
    auto it2 = std::lower_bound(shape_offset.begin() + 1, shape_offset.end(), index);
    result.polygon_index = it2 - shape_offset.begin();
    if (it2 == shape_offset.end() || *it2 != index) --result.polygon_index;
    // calculate point index
    uint32_t polygon_offset = shape_offset[result.polygon_index];
    assert(index >= polygon_offset);
    result.point_index = index - polygon_offset;
    return result;
}
References m_count, and m_offsets.
get_count()
uint32_t ExPolygonsIndices::get_count () const
Count of points in expolygons.
Returns
Count of points in expolygons
{ return m_count; }
References m_count.
Referenced by priv::choose_best_distance(), priv::collect_close_points(), Slic3r::cut_surface(), Slic3r::Emboss::divide_segments_for_close_point(), and priv::find_closest_point_pair().
is_last_point()
bool ExPolygonsIndices::is_last_point (const ExPolygonsIndex & id) const
Check whether id is last point in polygon.
Parameters
id Identify point in expolygon
Returns
True when id is last point in polygon otherwise false
{
    assert(id.expolygons_index < m_offsets.size());
    const std::vector<uint32_t> &shape_offset = m_offsets[id.expolygons_index];
    assert(id.polygon_index < shape_offset.size());
    uint32_t index = shape_offset[id.polygon_index] + id.point_index;
    assert(index < m_count);
    // next index
    uint32_t next_point_index = index + 1;
    uint32_t next_poly_index = id.polygon_index + 1;
    uint32_t next_expoly_index = id.expolygons_index + 1;
    // is last expoly?
    if (next_expoly_index == m_offsets.size()) {
        // is last expoly last poly?
        if (next_poly_index == shape_offset.size())
            return next_point_index == m_count;
    } else {
        // (not last expoly) is expoly last poly?
        if (next_poly_index == shape_offset.size())
            return next_point_index == m_offsets[next_expoly_index][0];
    }
    // Not last polygon in expolygon
    return next_point_index == shape_offset[next_poly_index];
}
References m_count, and m_offsets.
Referenced by priv::collect_close_points(), and Slic3r::Emboss::divide_segments_for_close_point().
Member Data Documentation
m_count
uint32_t Slic3r::ExPolygonsIndices::m_count private
Referenced by ExPolygonsIndices(), cvt(), cvt(), get_count(), and is_last_point().
m_offsets
std::vector<std::vector<uint32_t> > Slic3r::ExPolygonsIndices::m_offsets private
Referenced by ExPolygonsIndices(), cvt(), cvt(), and is_last_point().
The documentation for this class was generated from the following files:
src/libslic3r/ExPolygonsIndex.hpp
src/libslic3r/ExPolygonsIndex.cpp