Prusa Slicer: src/avrdude/config.c File Reference
config.c File Reference
#include "ac_cfg.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include "avrdude.h"
#include "libavrdude.h"
#include "config.h"
#include "config_gram.h"
#include "avrdude-slic3r.conf.h"
Macros
#define DEBUG 0
Typedefs
typedef struct yy_buffer_state * YY_BUFFER_STATE
Functions
void cleanup_config (void)
int init_config (void)
int yywrap ()
int yyerror (char *errmsg,...)
int yywarning (char *errmsg,...)
TOKEN * new_token (int primary)
void free_token (TOKEN *tkn)
void free_tokens (int n,...)
TOKEN * number (char *text)
TOKEN * number_real (char *text)
TOKEN * hexnumber (char *text)
TOKEN * string (char *text)
TOKEN * keyword (int primary)
void print_token (TOKEN *tkn)
void pyytext (void) { yylval = NULL
char * dup_string (const char *str)
int yylex_destroy (void)
int read_config (const char *file)
YY_BUFFER_STATE yy_scan_bytes (const char *base, size_t size)
void yy_delete_buffer (YY_BUFFER_STATE b)
int read_config_builtin ()
Variables
char default_programmer [MAX_STR_CONST]
char default_parallel [PATH_MAX]
char default_serial [PATH_MAX]
double default_bitclock
int default_safemode
char string_buf [MAX_STR_CONST]
char * string_buf_ptr = '\r'
LISTID string_list
LISTID number_list
PROGRAMMER * current_prog
AVRPART * current_part
AVRMEM * current_mem
LISTID part_list
LISTID programmers
int lineno
const char * infile
char * yytext
Macro Definition Documentation
DEBUG
#define DEBUG 0
Typedef Documentation
YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE
Function Documentation
cleanup_config()
void cleanup_config (void)
{
  ldestroy_cb(part_list, (void(*)(void*))avr_free_part);
  ldestroy_cb(programmers, (void(*)(void*))pgm_free);
  ldestroy_cb(string_list, (void(*)(void*))free_token);
  ldestroy_cb(number_list, (void(*)(void*))free_token);
}
References avr_free_part(), free_token(), ldestroy_cb(), number_list, part_list, pgm_free(), programmers, and string_list.
Referenced by cleanup_main().
dup_string()
char * dup_string (const char * str)
{
  char * s;
  s = strdup(str);
  if (s == NULL) {
    yyerror("dup_string(): out of memory");
    return NULL;
  }
  return s;
}
References yyerror().
Referenced by yyparse().
free_token()
void free_token (TOKEN * tkn)
{
  if (tkn) {
    switch (tkn->value.type) {
      case V_STR:
        if (tkn->value.string)
          free(tkn->value.string);
        tkn->value.string = NULL;
        break;
    }
    free(tkn);
  }
}
References free(), value_t::string, value_t::type, V_STR, and token_t::value.
Referenced by assign_pin(), assign_pin_list(), cleanup_config(), free_tokens(), parse_cmdbits(), and yyparse().
free_tokens()
void free_tokens (int n, ...)
{
  TOKEN * t;
  va_list ap;
  va_start(ap, n);
  while (n--) {
    t = va_arg(ap, TOKEN *);
    free_token(t);
  }
  va_end(ap);
}
References free_token().
Referenced by yyparse().
hexnumber()
TOKEN * hexnumber (char * text)
{
  struct token_t * tkn;
  char * e;
  tkn = new_token(TKN_NUMBER);
  if (tkn == NULL) {
      return NULL; /* yyerror already called */
  }
  tkn->value.type   = V_NUM;
  tkn->value.number = strtoul(text, &e, 16);
  if ((e == text) || (*e != 0)) {
    yyerror("can't scan hex number \"%s\"", text);
    return NULL;
  }
#if DEBUG
  avrdude_message(MSG_INFO, "HEXNUMBER(%g)\n", tkn->value.number);
#endif
  return tkn;
}
References avrdude_message(), MSG_INFO, new_token(), value_t::number, TKN_NUMBER, value_t::type, V_NUM, token_t::value, and yyerror().
init_config()
int init_config (void)
{
  string_list  = lcreat(NULL, 0);
  number_list  = lcreat(NULL, 0);
  current_prog = NULL;
  current_part = NULL;
  current_mem  = NULL;
  part_list    = lcreat(NULL, 0);
  programmers  = lcreat(NULL, 0);
  lineno       = 1;
  infile       = NULL;
  return 0;
}
References current_mem, current_part, current_prog, infile, lcreat(), lineno, number_list, part_list, programmers, and string_list.
Referenced by avrdude_main().
keyword()
TOKEN * keyword (int primary)
{
  struct token_t * tkn;
  tkn = new_token(primary);
  return tkn;
}
References new_token(), and token_t::primary.
Referenced by Slic3r::GCode::do_export(), and Slic3r::GUI::Tab::validate_custom_gcode().
new_token()
TOKEN * new_token (int primary)
{
  TOKEN * tkn;
  tkn = (TOKEN *)malloc(sizeof(TOKEN));
  if (tkn == NULL) {
    yyerror("new_token(): out of memory");
    return NULL;
  }
  memset(tkn, 0, sizeof(TOKEN));
  tkn->primary = primary;
  return tkn;
}
References malloc(), token_t::primary, and yyerror().
Referenced by hexnumber(), keyword(), number(), number_real(), and string().
number()
TOKEN * number (char * text)
{
  struct token_t * tkn;
  tkn = new_token(TKN_NUMBER);
  if (tkn == NULL) {
      return NULL; /* yyerror already called */
  }
  tkn->value.type   = V_NUM;
  tkn->value.number = atoi(text);
#if DEBUG
  avrdude_message(MSG_INFO, "NUMBER(%d)\n", tkn->value.number);
#endif
  return tkn;
}
References avrdude_message(), MSG_INFO, new_token(), value_t::number, TKN_NUMBER, value_t::type, V_NUM, and token_t::value.
Referenced by Slic3r::anonymous_namespace{SL1_SVG.cpp}::decimal_from().
number_real()
TOKEN * number_real (char * text)
{
  struct token_t * tkn;
  tkn = new_token(TKN_NUMBER);
  tkn->value.type   = V_NUM_REAL;
  tkn->value.number_real = atof(text);
#if DEBUG
  avrdude_message(MSG_INFO, "NUMBER(%g)\n", tkn->value.number_real);
#endif
  return tkn;
}
References avrdude_message(), MSG_INFO, new_token(), value_t::number_real, TKN_NUMBER, value_t::type, V_NUM_REAL, and token_t::value.
print_token()
void print_token (TOKEN * tkn)
{
  if (!tkn)
    return;
  avrdude_message(MSG_INFO, "token = %d = ", tkn->primary);
  switch (tkn->value.type) {
    case V_NUM:
      avrdude_message(MSG_INFO, "NUMBER, value=%d", tkn->value.number);
      break;
    case V_NUM_REAL:
      avrdude_message(MSG_INFO, "NUMBER, value=%g", tkn->value.number_real);
      break;
    case V_STR:
      avrdude_message(MSG_INFO, "STRING, value=%s", tkn->value.string);
      break;
    default:
      avrdude_message(MSG_INFO, "<other>");
      break;
  }
  avrdude_message(MSG_INFO, "\n");
}
References avrdude_message(), MSG_INFO, value_t::number, value_t::number_real, token_t::primary, value_t::string, value_t::type, V_NUM, V_NUM_REAL, V_STR, and token_t::value.
pyytext()
pyytext (void) { yylval = NULL
{
#if DEBUG
  avrdude_message(MSG_INFO, "TOKEN: \"%s\"\n", yytext);
#endif
}
References avrdude_message(), MSG_INFO, and yytext.
read_config()
int read_config (const char * file)
{
  FILE * f;
  int r;
  f = fopen_utf8(file, "r");
  if (f == NULL) {
    avrdude_message(MSG_INFO, "%s: can't open config file \"%s\": %s\n",
            progname, file, strerror(errno));
    return -1;
  }
  lineno = 1;
  infile = file;
  yyin   = f;
  r = yyparse();
#ifdef HAVE_YYLEX_DESTROY
  /* reset lexer and free any allocated memory */
  yylex_destroy();
#endif
  fclose(f);
  return r;
}
References avrdude_message(), fopen_utf8(), infile, lineno, MSG_INFO, progname, yyin, yylex_destroy(), and yyparse().
Referenced by avrdude_main().
read_config_builtin()
int read_config_builtin ()
{
  int r;
  lineno = 1;
  infile = "(builtin)";
  // Note: Can't use yy_scan_buffer, it's buggy (?), leads to fread from a null FILE*
  // and so unfortunatelly we have to use the copying variant here
  YY_BUFFER_STATE buffer = yy_scan_bytes((const char *)avrdude_slic3r_conf, avrdude_slic3r_conf_SIZE);
  if (buffer == NULL) {
    avrdude_message(MSG_INFO, "%s: read_config_builtin: Failed to initialize parsing buffer\n", progname);
    return -1;
  }
  r = yyparse();
  yy_delete_buffer(buffer);
#ifdef HAVE_YYLEX_DESTROY
  /* reset lexer and free any allocated memory */
  yylex_destroy();
#endif
  return r;
}
References avrdude_message(), infile, lineno, MSG_INFO, progname, yy_delete_buffer(), yy_scan_bytes(), yylex_destroy(), and yyparse().
Referenced by avrdude_main().
string()
TOKEN * string (char * text)
{
  struct token_t * tkn;
  int len;
  tkn = new_token(TKN_STRING);
  if (tkn == NULL) {
      return NULL; /* yyerror already called */
  }
  len = (int)strlen(text);
  tkn->value.type   = V_STR;
  tkn->value.string = (char *) malloc(len+1);
  if (tkn->value.string == NULL) {
    yyerror("string(): out of memory");
    return NULL;
  }
  strcpy(tkn->value.string, text);
#if DEBUG
  avrdude_message(MSG_INFO, "STRING(%s)\n", tkn->value.string);
#endif
  return tkn;
}
References avrdude_message(), malloc(), MSG_INFO, new_token(), value_t::string, TKN_STRING, value_t::type, V_STR, token_t::value, and yyerror().
Referenced by Slic3r::client::macro_processor::macro_processor(), igl::readOFF(), and igl::readWRL().
yy_delete_buffer()
void yy_delete_buffer (YY_BUFFER_STATE b)
Referenced by read_config_builtin().
yy_scan_bytes()
YY_BUFFER_STATE yy_scan_bytes (const char * base, size_t size)
Referenced by read_config_builtin().
yyerror()
int yyerror (char * errmsg, ...)
{
  va_list args;
  char message[512];
  va_start(args, errmsg);
  vsnprintf(message, sizeof(message), errmsg, args);
  avrdude_message(MSG_INFO, "%s: error at %s:%d: %s\n", progname, infile, lineno, message);
  va_end(args);
  return 0;
}
References avrdude_message(), infile, lineno, MSG_INFO, and progname.
Referenced by assign_pin(), assign_pin_list(), dup_string(), hexnumber(), new_token(), parse_cmdbits(), string(), which_opcode(), and yyparse().
yylex_destroy()
int yylex_destroy (void)
Referenced by read_config(), and read_config_builtin().
yywarning()
int yywarning (char * errmsg, ...)
{
  va_list args;
  char message[512];
  va_start(args, errmsg);
  vsnprintf(message, sizeof(message), errmsg, args);
  avrdude_message(MSG_INFO, "%s: warning at %s:%d: %s\n", progname, infile, lineno, message);
  va_end(args);
  return 0;
}
References avrdude_message(), infile, lineno, MSG_INFO, and progname.
Referenced by yyparse().
yywrap()
int yywrap (void)
{
  return 1;
}
Variable Documentation
current_mem
AVRMEM* current_mem
Referenced by init_config(), and yyparse().
current_part
AVRPART* current_part
Referenced by init_config(), and yyparse().
current_prog
PROGRAMMER* current_prog
Referenced by assign_pin(), assign_pin_list(), init_config(), and yyparse().
default_bitclock
double default_bitclock
Referenced by avrdude_main(), and yyparse().
default_parallel
char default_parallel[PATH_MAX]
Referenced by avrdude_main(), and yyparse().
default_programmer
char default_programmer[MAX_STR_CONST]
Referenced by avrdude_main(), and yyparse().
default_safemode
int default_safemode
Referenced by avrdude_main(), and yyparse().
default_serial
char default_serial[PATH_MAX]
Referenced by avrdude_main(), and yyparse().
infile
const char* infile
Referenced by ihex2b(), init_config(), read_config(), read_config_builtin(), igl::readCSV(), srec2b(), yyerror(), yyparse(), and yywarning().
lineno
int lineno
Referenced by ihex2b(), init_config(), jtagmkII_chip_erase32(), jtagmkII_close32(), jtagmkII_flash_clear_pagebuffer32(), jtagmkII_flash_erase32(), jtagmkII_flash_lock32(), jtagmkII_flash_write_page32(), jtagmkII_paged_load32(), jtagmkII_paged_write32(), jtagmkII_reset32(), jtagmkII_smc_init32(), read_config(), read_config_builtin(), srec2b(), yyerror(), yyparse(), and yywarning().
number_list
LISTID number_list
Referenced by assign_pin_list(), cleanup_config(), init_config(), and yyparse().
part_list
LISTID part_list
Referenced by avr910_initialize(), avrdude_main(), cleanup_config(), init_config(), and yyparse().
programmers
LISTID programmers
Referenced by avrdude_main(), cleanup_config(), init_config(), list_programmers(), locate_programmer(), sort_programmers(), walk_programmers(), and yyparse().
string_buf
char string_buf[MAX_STR_CONST]
string_buf_ptr
while yptr * string_buf_ptr = '\r'
string_list
LISTID string_list
Referenced by cleanup_config(), init_config(), parse_cmdbits(), and yyparse().
yytext
char * yytext extern
Referenced by pyytext().