Prusa Slicer: Slic3r::GUI::ObjectList::dragged_item_data Struct Reference
Slic3r::GUI::ObjectList::dragged_item_data Struct Reference
Public Member Functions
void init (const int obj_idx, const int subobj_idx, const ItemType type)
void init (const int obj_idx, const ItemType type)
void clear ()
int obj_idx () const
int sub_obj_idx () const
ItemType type () const
std::set< int > & inst_idxs ()
Private Attributes
int m_obj_idx = -1
int m_vol_idx = -1
std::set< int > m_inst_idxs {}
ItemType m_type = itUndef
Detailed Description
Member Function Documentation
clear()
void Slic3r::GUI::ObjectList::dragged_item_data::clear () inline
                     {
            m_obj_idx = -1;
            m_vol_idx = -1;
            m_inst_idxs.clear();
            m_type = itUndef;
        }
References Slic3r::GUI::itUndef, m_inst_idxs, m_obj_idx, m_type, and m_vol_idx.
Referenced by Slic3r::GUI::ObjectList::OnDrop().
init() [1/2]
void Slic3r::GUI::ObjectList::dragged_item_data::init (const int obj_idx, const int subobj_idx, const ItemType type) inline
{
            m_obj_idx = obj_idx;
            m_type = type;
            if (m_type&itVolume)
                m_vol_idx = subobj_idx;
            else
                m_inst_idxs.insert(subobj_idx);
        }
References Slic3r::GUI::itVolume, m_inst_idxs, m_obj_idx, m_type, m_vol_idx, obj_idx(), and type().
Referenced by Slic3r::GUI::ObjectList::OnBeginDrag().
init() [2/2]
void Slic3r::GUI::ObjectList::dragged_item_data::init (const int obj_idx, const ItemType type) inline
{
            m_obj_idx = obj_idx;
            m_type = type;
        }
References m_obj_idx, m_type, obj_idx(), and type().
inst_idxs()
std::set< int > & Slic3r::GUI::ObjectList::dragged_item_data::inst_idxs () inline
{ return m_inst_idxs; }
References m_inst_idxs.
Referenced by Slic3r::GUI::ObjectList::OnBeginDrag(), and Slic3r::GUI::ObjectList::OnDrop().
obj_idx()
int Slic3r::GUI::ObjectList::dragged_item_data::obj_idx () const inline
{ return m_obj_idx; }
References m_obj_idx.
Referenced by Slic3r::GUI::ObjectList::can_drop(), init(), init(), and Slic3r::GUI::ObjectList::OnDrop().
sub_obj_idx()
int Slic3r::GUI::ObjectList::dragged_item_data::sub_obj_idx () const inline
{ return m_vol_idx; }
References m_vol_idx.
Referenced by Slic3r::GUI::ObjectList::can_drop(), and Slic3r::GUI::ObjectList::OnDrop().
type()
ItemType Slic3r::GUI::ObjectList::dragged_item_data::type () const inline
{ return m_type; }
References m_type.
Referenced by Slic3r::GUI::ObjectList::can_drop(), init(), init(), and Slic3r::GUI::ObjectList::OnDrop().
Member Data Documentation
m_inst_idxs
std::set<int> Slic3r::GUI::ObjectList::dragged_item_data::m_inst_idxs {} private
Referenced by clear(), init(), and inst_idxs().
m_obj_idx
int Slic3r::GUI::ObjectList::dragged_item_data::m_obj_idx = -1 private
Referenced by clear(), init(), init(), and obj_idx().
m_type
ItemType Slic3r::GUI::ObjectList::dragged_item_data::m_type = itUndef private
Referenced by clear(), init(), init(), and type().
m_vol_idx
int Slic3r::GUI::ObjectList::dragged_item_data::m_vol_idx = -1 private
Referenced by clear(), init(), and sub_obj_idx().
The documentation for this struct was generated from the following file:
src/slic3r/GUI/GUI_ObjectList.hpp