Prusa Slicer: Slic3r::GUI::Line Class Reference
Slic3r::GUI::Line Class Reference
Represents option lines.
#include <src/slic3r/GUI/OptionsGroup.hpp>
Public Member Functions
void append_option (const Option &option)
void append_widget (const widget_t widget)
Line (wxString label, wxString tooltip)
Line ()
Line (const std::string &opt_key, const wxString &label, const wxString &tooltip)
bool is_separator () const
bool has_only_option (const std::string &opt_key) const
void clear ()
const std::vector< widget_t > & get_extra_widgets () const
const std::vector< Option > & get_options () const
bool set_undo_bitmap (const ScalableBitmap *bmp)
bool set_undo_to_sys_bitmap (const ScalableBitmap *bmp)
bool set_label_colour (const wxColour *clr)
bool set_undo_tooltip (const wxString *tip)
bool set_undo_to_sys_tooltip (const wxString *tip)
bool has_undo_ui () const
const wxBitmapBundle & undo_bitmap () const
const wxString * undo_tooltip () const
const wxBitmapBundle & undo_to_sys_bitmap () const
const wxString * undo_to_sys_tooltip () const
const wxColour * label_color () const
const bool blink () const
bool * get_blink_ptr ()
Public Attributes
wxString label
wxString label_tooltip
std::string label_path
size_t full_width {0}
widget_t widget {nullptr}
std::function< wxWindow *(wxWindow *)> near_label_widget { nullptr }
wxWindow * near_label_widget_win {nullptr}
wxSizer * widget_sizer {nullptr}
wxSizer * extra_widget_sizer {nullptr}
Private Attributes
bool m_is_separator { false }
std::vector< Option > m_options
std::vector< widget_t > m_extra_widgets
{std::vector<Option>()};
UndoValueUI m_undo_ui
Detailed Description
Represents option lines.
Constructor & Destructor Documentation
Line() [1/3]
Slic3r::GUI::Line::Line (wxString label, wxString tooltip) inline
                                         :
    label(_(label)), label_tooltip(_(tooltip)) {}
Line() [2/3]
Slic3r::GUI::Line::Line () inline
: m_is_separator(true) {}
Line() [3/3]
Slic3r::GUI::Line::Line (const std::string & opt_key, const wxString & label, const wxString & tooltip) inline
                                                                                 :
    label(_(label)), label_tooltip(_(tooltip))
  {
    m_options.push_back(Option({ opt_key, coNone }, opt_key));
  }
References Slic3r::coNone, and m_options.
Member Function Documentation
append_option()
void Slic3r::GUI::Line::append_option (const Option & option) inline
{
        m_options.push_back(option);
    }
References m_options.
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), Slic3r::GUI::TabFilament::build(), Slic3r::GUI::TabPrinter::build_extruder_pages(), and Slic3r::GUI::TabPrinter::build_sla().
append_widget()
void Slic3r::GUI::Line::append_widget (const widget_t widget) inline
{
    m_extra_widgets.push_back(widget);
    }
References m_extra_widgets, and widget.
Referenced by Slic3r::GUI::FreqChangedParams::FreqChangedParams(), Slic3r::GUI::TabPrinter::build_extruder_pages(), Slic3r::GUI::Tab::build_preset_description_line(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
blink()
const bool Slic3r::GUI::UndoValueUIManager::blink () const inline inherited
{ return m_undo_ui.blink; }
References Slic3r::GUI::UndoValueUIManager::UndoValueUI::blink, and Slic3r::GUI::UndoValueUIManager::m_undo_ui.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
clear()
void Slic3r::GUI::Line::clear ()
{
    if (near_label_widget_win)
        near_label_widget_win = nullptr;
    if (widget_sizer) {
        widget_sizer->Clear(true);
        delete widget_sizer;
        widget_sizer = nullptr;
    }
    if (extra_widget_sizer) {
        extra_widget_sizer->Clear(true);
        delete extra_widget_sizer;
        extra_widget_sizer = nullptr;
    }
}
References extra_widget_sizer, near_label_widget_win, and widget_sizer.
get_blink_ptr()
bool * Slic3r::GUI::UndoValueUIManager::get_blink_ptr () inline inherited
{ return &m_undo_ui.blink; }
References Slic3r::GUI::UndoValueUIManager::UndoValueUI::blink, and Slic3r::GUI::UndoValueUIManager::m_undo_ui.
Referenced by Slic3r::GUI::ConfigOptionsGroup::get_custom_ctrl_with_blinking_ptr().
get_extra_widgets()
const std::vector< widget_t > & Slic3r::GUI::Line::get_extra_widgets () const inline
{return m_extra_widgets;}
References m_extra_widgets.
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::append_line(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
get_options()
const std::vector< Option > & Slic3r::GUI::Line::get_options () const inline
{ return m_options; }
References m_options.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::CtrlLine(), Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::append_line(), Slic3r::Search::OptionsSearcher::append_preferences_option(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
has_only_option()
bool Slic3r::GUI::Line::has_only_option (const std::string & opt_key) const inline
{ return m_options.size() == 1 && m_options[0].opt_id == opt_key; }
References m_options.
has_undo_ui()
bool Slic3r::GUI::UndoValueUIManager::has_undo_ui () const inline inherited
{ return m_undo_ui.undo_bitmap != nullptr; }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::get_pos(), and Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
is_separator()
bool Slic3r::GUI::Line::is_separator () const inline
{ return m_is_separator; }
References m_is_separator.
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), and Slic3r::GUI::OG_CustomCtrl::CtrlLine::is_separator().
label_color()
const wxColour * Slic3r::GUI::UndoValueUIManager::label_color () const inline inherited
{ return m_undo_ui.label_color; }
References Slic3r::GUI::UndoValueUIManager::UndoValueUI::label_color, and Slic3r::GUI::UndoValueUIManager::m_undo_ui.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
set_label_colour()
bool Slic3r::GUI::UndoValueUIManager::set_label_colour (const wxColour * clr) inline inherited
{ return m_undo_ui.set_label_colour(clr); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_label_colour().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), Slic3r::GUI::Tab::decorate(), and Slic3r::GUI::Tab::update_label_colours().
set_undo_bitmap()
bool Slic3r::GUI::UndoValueUIManager::set_undo_bitmap (const ScalableBitmap * bmp) inline inherited
{ return m_undo_ui.set_undo_bitmap(bmp); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_bitmap().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_undo_to_sys_bitmap()
bool Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_bitmap (const ScalableBitmap * bmp) inline inherited
{ return m_undo_ui.set_undo_to_sys_bitmap(bmp); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_to_sys_bitmap().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_undo_to_sys_tooltip()
bool Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_tooltip (const wxString * tip) inline inherited
{ return m_undo_ui.set_undo_to_sys_tooltip(tip); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_to_sys_tooltip().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_undo_tooltip()
bool Slic3r::GUI::UndoValueUIManager::set_undo_tooltip (const wxString * tip) inline inherited
{ return m_undo_ui.set_undo_tooltip(tip); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_tooltip().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
undo_bitmap()
const wxBitmapBundle & Slic3r::GUI::UndoValueUIManager::undo_bitmap () const inline inherited
{ return m_undo_ui.undo_bitmap->bmp(); }
References ScalableBitmap::bmp(), Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
undo_to_sys_bitmap()
const wxBitmapBundle & Slic3r::GUI::UndoValueUIManager::undo_to_sys_bitmap () const inline inherited
{ return m_undo_ui.undo_to_sys_bitmap->bmp(); }
References ScalableBitmap::bmp(), Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_to_sys_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
undo_to_sys_tooltip()
const wxString * Slic3r::GUI::UndoValueUIManager::undo_to_sys_tooltip () const inline inherited
{ return m_undo_ui.undo_to_sys_tooltip; }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_to_sys_tooltip.
undo_tooltip()
const wxString * Slic3r::GUI::UndoValueUIManager::undo_tooltip () const inline inherited
{ return m_undo_ui.undo_tooltip; }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_tooltip.
Member Data Documentation
extra_widget_sizer
wxSizer* Slic3r::GUI::Line::extra_widget_sizer {nullptr}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), clear(), and Slic3r::GUI::OG_CustomCtrl::correct_widgets_position().
full_width
size_t Slic3r::GUI::Line::full_width {0}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::append_line(), Slic3r::GUI::TabPrint::build(), Slic3r::GUI::TabFilament::build(), Slic3r::GUI::TabPrinter::build_extruder_pages(), Slic3r::GUI::TabPrinter::build_kinematics_page(), Slic3r::GUI::BedShapePanel::build_panel(), Slic3r::GUI::Tab::build_preset_description_line(), Slic3r::GUI::TabPrinter::build_print_host_upload_group(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::TabSLAPrint::build_sla_support_params(), Slic3r::GUI::BedShapePanel::init_model_panel(), and Slic3r::GUI::BedShapePanel::init_texture_panel().
label
wxString Slic3r::GUI::Line::label
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::add_options_into_line(), Slic3r::Search::OptionsSearcher::append_preferences_option(), Slic3r::GUI::TabPrinter::build_sla(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
label_path
std::string Slic3r::GUI::Line::label_path
Referenced by Slic3r::GUI::TabFilament::build(), and Slic3r::GUI::Tab::create_line_with_widget().
label_tooltip
wxString Slic3r::GUI::Line::label_tooltip
Referenced by Slic3r::GUI::OptionsGroup::activate_line().
m_extra_widgets
std::vector<widget_t> Slic3r::GUI::Line::m_extra_widgets private
{std::vector<Option>()};
Referenced by append_widget(), and get_extra_widgets().
m_is_separator
bool Slic3r::GUI::Line::m_is_separator { false } private
Referenced by is_separator().
m_options
std::vector<Option> Slic3r::GUI::Line::m_options private
Referenced by Line(), append_option(), get_options(), and has_only_option().
m_undo_ui
UndoValueUI Slic3r::GUI::UndoValueUIManager::m_undo_ui private inherited
Referenced by Slic3r::GUI::UndoValueUIManager::blink(), Slic3r::GUI::UndoValueUIManager::get_blink_ptr(), Slic3r::GUI::UndoValueUIManager::has_undo_ui(), Slic3r::GUI::UndoValueUIManager::label_color(), Slic3r::GUI::UndoValueUIManager::set_label_colour(), Slic3r::GUI::UndoValueUIManager::set_undo_bitmap(), Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_bitmap(), Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_tooltip(), Slic3r::GUI::UndoValueUIManager::set_undo_tooltip(), Slic3r::GUI::UndoValueUIManager::undo_bitmap(), Slic3r::GUI::UndoValueUIManager::undo_to_sys_bitmap(), Slic3r::GUI::UndoValueUIManager::undo_to_sys_tooltip(), and Slic3r::GUI::UndoValueUIManager::undo_tooltip().
near_label_widget
std::function<wxWindow*(wxWindow*)> Slic3r::GUI::Line::near_label_widget { nullptr }
Referenced by Slic3r::GUI::OptionsGroup::activate_line().
near_label_widget_win
wxWindow* Slic3r::GUI::Line::near_label_widget_win {nullptr}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), clear(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
widget
widget_t Slic3r::GUI::Line::widget {nullptr}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::append_line(), append_widget(), Slic3r::GUI::TabFilament::build(), Slic3r::GUI::TabPrinter::build_extruder_pages(), Slic3r::GUI::TabPrinter::build_print_host_upload_group(), Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
widget_sizer
wxSizer* Slic3r::GUI::Line::widget_sizer {nullptr}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), clear(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
The documentation for this class was generated from the following files:
src/slic3r/GUI/OptionsGroup.hpp
src/slic3r/GUI/OptionsGroup.cpp