Prusa Slicer: Slic3r::Range< It > Class Template Reference
Slic3r::Range< It > Class Template Reference
#include <src/libslic3r/libslic3r.h>
Public Types
using iterator = It
using value_type = typename std::iterator_traits< It >::value_type
Public Member Functions
It begin () const
It end () const
Range ()=default
Range (It b, It e)
size_t size () const
bool empty () const
Private Attributes
It from
It to
Detailed Description
template<class It>
class Slic3r::Range< It >
Member Typedef Documentation
iterator
template<class It > using Slic3r::Range< It >::iterator = It
value_type
template<class It > using Slic3r::Range< It >::value_type = typename std::iterator_traits<It>::value_type
Constructor & Destructor Documentation
Range() [1/2]
template<class It > Slic3r::Range< It >::Range () default
Range() [2/2]
template<class It > Slic3r::Range< It >::Range (It b, It e) inline
: from(std::move(b)), to(std::move(e)) {}
Member Function Documentation
begin()
template<class It > It Slic3r::Range< It >::begin () const inline
{ return from; }
References Slic3r::Range< It >::from.
Referenced by Slic3r::csg::check_csgmesh_booleans(), and Slic3r::csg::is_same().
empty()
template<class It > bool Slic3r::Range< It >::empty () const inline
{ return from == to; }
References Slic3r::Range< It >::from, and Slic3r::Range< It >::to.
end()
template<class It > It Slic3r::Range< It >::end () const inline
{ return to; }
References Slic3r::Range< It >::to.
Referenced by Slic3r::csg::check_csgmesh_booleans().
size()
template<class It > size_t Slic3r::Range< It >::size () const inline
{ return std::distance(from, to); }
References Slic3r::Range< It >::from, and Slic3r::Range< It >::to.
Referenced by Slic3r::csg::check_csgmesh_booleans(), Slic3r::csg::detail_cgal::get_cgalptrs(), and Slic3r::csg::is_same().
Member Data Documentation
from
template<class It > It Slic3r::Range< It >::from private
Referenced by Slic3r::Range< It >::begin(), Slic3r::Range< It >::empty(), and Slic3r::Range< It >::size().
to
template<class It > It Slic3r::Range< It >::to private
Referenced by Slic3r::Range< It >::empty(), Slic3r::Range< It >::end(), and Slic3r::Range< It >::size().
The documentation for this class was generated from the following file:
src/libslic3r/libslic3r.h