Prusa Slicer: Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > Class Template Reference
Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > Class Template Reference
#include <src/eigen/Eigen/src/SparseCore/SparseRef.h>
Public Types
typedef internal::SparseRefBase< Ref > Base
Public Member Functions
template<typename Derived >
Ref (const SparseMatrixBase< Derived > &expr)
Ref (const Ref &other)
template<typename OtherRef >
Ref (const RefBase< OtherRef > &other)
~Ref ()
Protected Member Functions
template<typename Expression >
void construct (const Expression &expr, internal::true_type)
template<typename Expression >
void construct (const Expression &expr, internal::false_type)
void construct (Expression &expr)
Protected Attributes
char m_object_bytes [sizeof(TPlainObjectType)]
bool m_hasCopy
Private Types
typedef SparseVector< MatScalar, MatOptions, MatIndex > TPlainObjectType
typedef internal::traits< Ref > Traits
Detailed Description
template<typename MatScalar, int MatOptions, typename MatIndex, int Options, typename StrideType>
class Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >
Member Typedef Documentation
Base
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef internal::SparseRefBase<Ref> Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Base
TPlainObjectType
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef SparseVector<MatScalar,MatOptions,MatIndex> Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::TPlainObjectType private
Traits
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef internal::traits<Ref> Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Traits private
Constructor & Destructor Documentation
Ref() [1/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename Derived > Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const SparseMatrixBase< Derived > & expr) inline
                                                      : m_hasCopy(false)
    {
      construct(expr.derived(), typename Traits::template match<Derived>::type());
    }
References Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::construct(), and Eigen::SparseMatrixBase< Derived >::derived().
Ref() [2/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > & other) inline
                                 : Base(other), m_hasCopy(false) {
      // copy constructor shall not copy the m_object, to avoid unnecessary malloc and copy
    }
Ref() [3/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename OtherRef > Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const RefBase< OtherRef< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > > & other) inline
                                               : m_hasCopy(false) {
      construct(other.derived(), typename Traits::template match<OtherRef>::type());
    }
References Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::construct().
~Ref()
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::~Ref () inline
           {
      if(m_hasCopy) {
        TPlainObjectType* obj = reinterpret_cast<TPlainObjectType*>(m_object_bytes);
        obj->~TPlainObjectType();
      }
    }
Member Function Documentation
construct() [1/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename Expression > void Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::construct (const Expression & expr, internal::false_type) inline protected
    {
      TPlainObjectType* obj = reinterpret_cast<TPlainObjectType*>(m_object_bytes);
      ::new (obj) TPlainObjectType(expr);
      m_hasCopy = true;
      Base::construct(*obj);
    }
References Eigen::RefBase< Derived >::construct().
construct() [2/3]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename Expression > void Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::construct (const Expression & expr, internal::true_type) inline protected
    {
      Base::construct(expr);
    }
References Eigen::RefBase< Derived >::construct().
construct() [3/3]
void Eigen::internal::SparseRefBase< Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType > >::construct (Expression & expr) inline protected inherited
  {
    if(expr.outerIndexPtr()==0)
      ::new (static_cast<Base*>(this)) Base(expr.size(), expr.nonZeros(), expr.innerIndexPtr(), expr.valuePtr());
    else
      ::new (static_cast<Base*>(this)) Base(expr.rows(), expr.cols(), expr.nonZeros(), expr.outerIndexPtr(), expr.innerIndexPtr(), expr.valuePtr(), expr.innerNonZeroPtr());
  }
Member Data Documentation
m_hasCopy
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > bool Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::m_hasCopy protected
m_object_bytes
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > char Eigen::Ref< const SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >::m_object_bytes[sizeof(TPlainObjectType)] protected
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseRef.h