Prusa Slicer: Slic3r::GUI::Field Class Reference
Slic3r::GUI::Field Class Reference abstract
#include <src/slic3r/GUI/Field.hpp>
Classes
class EnterPressed
Public Member Functions
void on_back_to_initial_value ()
Call the attached m_back_to_initial_value method.
void on_back_to_sys_value ()
Call the attached m_back_to_sys_value method.
virtual void set_value (const boost::any &value, bool change_event)=0
Sets a value for this control. subclasses should overload with a specific version Postcondition: Method does not fire the on_change event.
virtual void set_last_meaningful_value ()
virtual void set_na_value ()
virtual boost::any & get_value ()=0
Gets a boost::any representing this control. subclasses should overload with a specific version.
virtual void enable ()=0
virtual void disable ()=0
void toggle (bool en)
Fires the enable or disable function, based on the input.
virtual wxString get_tooltip_text (const wxString &default_string)
void field_changed ()
Field (const ConfigOptionDef &opt, const t_config_option_key &id)
Field (wxWindow *parent, const ConfigOptionDef &opt, const t_config_option_key &id)
virtual ~Field ()
virtual wxSizer * getSizer ()
If you don't know what you are getting back, check both methods for nullptr.
virtual wxWindow * getWindow ()
bool is_matched (const std::string &string, const std::string &pattern)
void get_value_by_opt_type (wxString &str, const bool check_value=true)
virtual void msw_rescale ()
virtual void sys_color_changed ()
bool get_enter_pressed () const
void set_enter_pressed (bool pressed)
bool set_undo_bitmap (const ScalableBitmap *bmp)
bool set_undo_to_sys_bitmap (const ScalableBitmap *bmp)
bool set_label_colour (const wxColour *clr)
bool set_undo_tooltip (const wxString *tip)
bool set_undo_to_sys_tooltip (const wxString *tip)
bool has_undo_ui () const
const wxBitmapBundle & undo_bitmap () const
const wxString * undo_tooltip () const
const wxBitmapBundle & undo_to_sys_bitmap () const
const wxString * undo_to_sys_tooltip () const
const wxColour * label_color () const
const bool blink () const
bool * get_blink_ptr ()
Static Public Member Functions
template<class T >
static t_field Create (wxWindow *parent, const ConfigOptionDef &opt, const t_config_option_key &id)
Factory method for generating new derived classes.
static int def_width ()
static int def_width_wider ()
static int def_width_thinner ()
Public Attributes
wxWindow * m_parent {nullptr}
parent wx item, opportunity to refactor (probably not necessary - data duplication)
t_kill_focus m_on_kill_focus {nullptr}
Function object to store callback passed in from owning object.
t_change m_on_change {nullptr}
Function object to store callback passed in from owning object.
t_back_to_init m_back_to_initial_value { nullptr }
Function object to store callback passed in from owning object.
t_back_to_init m_back_to_sys_value { nullptr }
bool m_disable_change_event {false}
bool m_is_modified_value {false}
bool m_is_nonsys_value {true}
const ConfigOptionDef m_opt {ConfigOptionDef()}
Copy of ConfigOption for deduction purposes.
const t_config_option_key m_opt_id
int m_opt_idx = 0
{""};
double opt_height { 0.0 }
bool parent_is_custom_ctrl { false }
Protected Member Functions
virtual void PostInitialize ()
virtual void BUILD ()=0
Finish constructing the Field's wxWidget-related properties, including setting its own sizer, etc.
void on_kill_focus ()
Call the attached on_kill_focus method. It's important to use wxEvent instead of wxFocusEvent, in another case we can't unfocused control at all.
void on_change_field ()
Call the attached on_change method.
Protected Attributes
boost::any m_value
boost::any m_last_meaningful_value
int m_em_unit
bool bEnterPressed = false
Private Attributes
UndoValueUI m_undo_ui
Friends
class OptionsGroup
Detailed Description
Constructor & Destructor Documentation
Field() [1/2]
Slic3r::GUI::Field::Field (const ConfigOptionDef & opt, const t_config_option_key & id) inline
: m_opt(opt), m_opt_id(id) {}
Field() [2/2]
Slic3r::GUI::Field::Field (wxWindow * parent, const ConfigOptionDef & opt, const t_config_option_key & id) inline
: m_parent(parent), m_opt(opt), m_opt_id(id) {}
~Field()
Slic3r::GUI::Field::~Field () virtual
{
  if (m_on_kill_focus)
    m_on_kill_focus = nullptr;
  if (m_on_change)
    m_on_change = nullptr;
  if (m_back_to_initial_value)
    m_back_to_initial_value = nullptr;
  if (m_back_to_sys_value)
    m_back_to_sys_value = nullptr;
  if (getWindow()) {
    wxWindow* win = getWindow();
    win->Destroy();
    win = nullptr;
  }
}
References getWindow(), m_back_to_initial_value, m_back_to_sys_value, m_on_change, and m_on_kill_focus.
Member Function Documentation
blink()
const bool Slic3r::GUI::UndoValueUIManager::blink () const inline inherited
{ return m_undo_ui.blink; }
References Slic3r::GUI::UndoValueUIManager::UndoValueUI::blink, and Slic3r::GUI::UndoValueUIManager::m_undo_ui.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
BUILD()
virtual void Slic3r::GUI::Field::BUILD () protected pure virtual
Finish constructing the Field's wxWidget-related properties, including setting its own sizer, etc.
Implemented in Slic3r::GUI::TextCtrl, Slic3r::GUI::CheckBox, Slic3r::GUI::SpinCtrl, Slic3r::GUI::Choice, Slic3r::GUI::ColourPicker, Slic3r::GUI::PointCtrl, Slic3r::GUI::StaticText, and Slic3r::GUI::SliderCtrl.
Referenced by PostInitialize().
Create()
template<class T > static t_field Slic3r::GUI::Field::Create (wxWindow * parent, const ConfigOptionDef & opt, const t_config_option_key & id) inline static
Factory method for generating new derived classes.
p;
    {
        auto p = Slic3r::make_unique<T>(parent, opt, id);
        p->PostInitialize();
    return std::move(p);
    }
def_width()
int Slic3r::GUI::Field::def_width () static
{ return 8; }
def_width_thinner()
int Slic3r::GUI::Field::def_width_thinner () static
{ return 4; }
Referenced by Slic3r::GUI::DiamTextCtrl::DiamTextCtrl(), and Slic3r::GUI::OptionsGroup::activate_line().
def_width_wider()
int Slic3r::GUI::Field::def_width_wider () static
{ return 16; }
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
disable()
virtual void Slic3r::GUI::Field::disable () pure virtual
Implemented in Slic3r::GUI::TextCtrl, Slic3r::GUI::CheckBox, Slic3r::GUI::SpinCtrl, Slic3r::GUI::Choice, Slic3r::GUI::ColourPicker, Slic3r::GUI::PointCtrl, Slic3r::GUI::StaticText, and Slic3r::GUI::SliderCtrl.
Referenced by toggle(), and Slic3r::GUI::PhysicalPrinterDialog::update_printers().
enable()
virtual void Slic3r::GUI::Field::enable () pure virtual
Implemented in Slic3r::GUI::TextCtrl, Slic3r::GUI::CheckBox, Slic3r::GUI::SpinCtrl, Slic3r::GUI::Choice, Slic3r::GUI::ColourPicker, Slic3r::GUI::PointCtrl, Slic3r::GUI::StaticText, and Slic3r::GUI::SliderCtrl.
Referenced by toggle(), and Slic3r::GUI::PhysicalPrinterDialog::update_printers().
field_changed()
void Slic3r::GUI::Field::field_changed () inline
{ on_change_field(); }
References on_change_field().
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
get_blink_ptr()
bool * Slic3r::GUI::UndoValueUIManager::get_blink_ptr () inline inherited
{ return &m_undo_ui.blink; }
References Slic3r::GUI::UndoValueUIManager::UndoValueUI::blink, and Slic3r::GUI::UndoValueUIManager::m_undo_ui.
Referenced by Slic3r::GUI::ConfigOptionsGroup::get_custom_ctrl_with_blinking_ptr().
get_enter_pressed()
bool Slic3r::GUI::Field::get_enter_pressed () const inline
{ return bEnterPressed; }
References bEnterPressed.
get_tooltip_text()
wxString Slic3r::GUI::Field::get_tooltip_text (const wxString & default_string) virtual
{
    if (m_opt.tooltip.empty())
        return "";
    std::string opt_id = m_opt_id;
    auto hash_pos = opt_id.find('#');
    if (hash_pos != std::string::npos) {
        opt_id.replace(hash_pos, 1,"[");
        opt_id += "]";
    }
  return from_u8(m_opt.tooltip) + "\n" + _L("default value") + "\t: " +
        (boost::iends_with(opt_id, "_gcode") ? "\n" : "") + default_string +
        (boost::iends_with(opt_id, "_gcode") ? "" : "\n") +
        _L("parameter name") + "\t: " + opt_id;
}
References _L, and Slic3r::GUI::from_u8().
get_value()
virtual boost::any & Slic3r::GUI::Field::get_value () pure virtual
Gets a boost::any representing this control. subclasses should overload with a specific version.
Implemented in Slic3r::GUI::TextCtrl, Slic3r::GUI::CheckBox, Slic3r::GUI::SpinCtrl, Slic3r::GUI::Choice, Slic3r::GUI::ColourPicker, Slic3r::GUI::PointCtrl, Slic3r::GUI::StaticText, and Slic3r::GUI::SliderCtrl.
get_value_by_opt_type()
void Slic3r::GUI::Field::get_value_by_opt_type (wxString & str, const bool check_value = true)
{
  switch (m_opt.type) {
  case coInt:
    m_value = wxAtoi(str);
    break;
  case coPercent:
  case coPercents:
  case coFloats:
  case coFloat:{
    if (m_opt.type == coPercent && !str.IsEmpty() &&  str.Last() == '%')
      str.RemoveLast();
    else if (!str.IsEmpty() && str.Last() == '%')
        {
            if (!check_value) {
                m_value.clear();
                break;
            }
      wxString label = m_opt.full_label.empty() ? _(m_opt.label) : _(m_opt.full_label);
            show_error(m_parent, format_wxstr(_L("%s doesn't support percentage"), label));
      set_value(double_to_string(m_opt.min), true);
      m_value = double(m_opt.min);
      break;
    }
        double val;
        bool is_na_value = m_opt.nullable && str == na_value();
        const char dec_sep = is_decimal_separator_point() ? '.' : ',';
        const char dec_sep_alt = dec_sep == '.' ? ',' : '.';
        // Replace the first incorrect separator in decimal number,
        // if this value doesn't "N/A" value in some language
        // see https://github.com/prusa3d/PrusaSlicer/issues/6921
        if (!is_na_value && str.Replace(dec_sep_alt, dec_sep, false) != 0)
            set_value(str, false);
        if (str == dec_sep)
            val = 0.0;
        else
        {
            if (is_na_value)
                val = ConfigOptionFloatsNullable::nil_value();
            else if (!str.ToDouble(&val))
            {
                if (!check_value) {
                    m_value.clear();
                    break;
                }
                show_error(m_parent, _(L("Invalid numeric input.")));
                set_value(double_to_string(val), true);
            }
            if (m_opt.min > val || val > m_opt.max)
            {
                if (!check_value) {
                    m_value.clear();
                    break;
                }
                if (m_opt_id == "extrusion_multiplier") {
                    if (m_value.empty() || boost::any_cast<double>(m_value) != val) {
                        wxString msg_text = format_wxstr(_L("Input value is out of range\n"
                            "Are you sure that %s is a correct value and that you want to continue?"), str);
//                        wxMessageDialog dialog(m_parent, msg_text, _L("Parameter validation") + ": " + m_opt_id, wxICON_WARNING | wxYES | wxNO);
                        WarningDialog dialog(m_parent, msg_text, _L("Parameter validation") + ": " + m_opt_id, wxYES | wxNO);
                        if (dialog.ShowModal() == wxID_NO) {
                            if (m_value.empty()) {
                                if (m_opt.min > val) val = m_opt.min;
                                if (val > m_opt.max) val = m_opt.max;
                            }
                            else
                                val = boost::any_cast<double>(m_value);
                            set_value(double_to_string(val), true);
                        }
                    }
                }
                else {
                    show_error(m_parent, _L("Input value is out of range"));
                    if (m_opt.min > val) val = m_opt.min;
                    if (val > m_opt.max) val = m_opt.max;
                    set_value(double_to_string(val), true);
                }
            }
        }
        m_value = val;
    break; }
  case coString:
  case coStrings:
    case coFloatsOrPercents:
    case coFloatOrPercent: {
        if (m_opt.type == coFloatOrPercent && m_opt.opt_key == "first_layer_height" && !str.IsEmpty() && str.Last() == '%') {
            // Workaroud to avoid of using of the % for first layer height
            // see https://github.com/prusa3d/PrusaSlicer/issues/7418
            wxString label = m_opt.full_label.empty() ? _(m_opt.label) : _(m_opt.full_label);
            show_error(m_parent, format_wxstr(_L("%s doesn't support percentage"), label));
            const wxString stVal = double_to_string(0.01, 2);
            set_value(stVal, true);
            m_value = into_u8(stVal);;
            break;
        }
        if ((m_opt.type == coFloatOrPercent || m_opt.type == coFloatsOrPercents) && !str.IsEmpty() &&  str.Last() != '%')
        {
            double val = 0.;
            const char dec_sep = is_decimal_separator_point() ? '.' : ',';
            const char dec_sep_alt = dec_sep == '.' ? ',' : '.';
            // Replace the first incorrect separator in decimal number.
            if (str.Replace(dec_sep_alt, dec_sep, false) != 0)
                set_value(str, false);
            // remove space and "mm" substring, if any exists
            str.Replace(" ", "", true);
            str.Replace("m", "", true);
            if (!str.ToDouble(&val))
            {
                if (!check_value) {
                    m_value.clear();
                    break;
                }
                show_error(m_parent, _(L("Invalid numeric input.")));
                set_value(double_to_string(val), true);
            }
            else if (((m_opt.sidetext.rfind("mm/s") != std::string::npos && val > m_opt.max) ||
                     (m_opt.sidetext.rfind("mm ") != std::string::npos && val > /*1*/m_opt.max_literal)) &&
                     (m_value.empty() || into_u8(str) != boost::any_cast<std::string>(m_value)))
            {
                if (!check_value) {
                    m_value.clear();
                    break;
                }
                bool infill_anchors = m_opt.opt_key == "infill_anchor" || m_opt.opt_key == "infill_anchor_max";
                const std::string sidetext = m_opt.sidetext.rfind("mm/s") != std::string::npos ? "mm/s" : "mm";
                const wxString stVal = double_to_string(val, 2);
                // TRN %1% = Value, %2% = units
                const wxString msg_text = format_wxstr(_L("Do you mean %1%%% instead of %1% %2%?\n"
                    "Select YES if you want to change this value to %1%%%, \n"
                    "or NO if you are sure that %1% %2% is a correct value."), stVal, sidetext);
                WarningDialog dialog(m_parent, msg_text, _L("Parameter validation") + ": " + m_opt_id, wxYES | wxNO);
                if ((!infill_anchors || val > 100) && dialog.ShowModal() == wxID_YES) {
                    set_value(from_u8((boost::format("%s%%") % stVal).str()), false/*true*/);
                    str += "%%";
                }
        else
          set_value(stVal, false); // it's no needed but can be helpful, when inputted value contained "," instead of "."
            }
        }
        m_value = into_u8(str);
    break; }
    case coPoints: {
        std::vector<Vec2d> out_values;
        str.Replace(" ", wxEmptyString, true);
        if (!str.IsEmpty()) {
            bool invalid_val = false;
            bool out_of_range_val = false;
            wxStringTokenizer thumbnails(str, ",");
            while (thumbnails.HasMoreTokens()) {
                wxString token = thumbnails.GetNextToken();
                double x, y;
                wxStringTokenizer thumbnail(token, "x");
                if (thumbnail.HasMoreTokens()) {
                    wxString x_str = thumbnail.GetNextToken();
                    if (x_str.ToDouble(&x) && thumbnail.HasMoreTokens()) {
                        wxString y_str = thumbnail.GetNextToken();
                        if (y_str.ToDouble(&y) && !thumbnail.HasMoreTokens()) {
                            if (0 < x && x < 1000 && 0 < y && y < 1000) {
                                out_values.push_back(Vec2d(x, y));
                                continue;
                            }
                            out_of_range_val = true;
                            break;
                        }
                    }
                }
                invalid_val = true;
                break;
            }
            if (out_of_range_val) {
                wxString text_value;
                if (!m_value.empty())
                    text_value = get_thumbnails_string(boost::any_cast<std::vector<Vec2d>>(m_value));
                set_value(text_value, true);
                show_error(m_parent, _L("Input value is out of range"));
            }
            else if (invalid_val) {
                wxString text_value;
                if (!m_value.empty())
                    text_value = get_thumbnails_string(boost::any_cast<std::vector<Vec2d>>(m_value));
                set_value(text_value, true);
                show_error(m_parent, format_wxstr(_L("Invalid input format. Expected vector of dimensions in the following format: \"%1%\""),"XxY, XxY, ..." ));
            }
        }
        m_value = out_values;
        break; }
  default:
    break;
  }
}
References _, _L, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coFloats, Slic3r::coFloatsOrPercents, Slic3r::coInt, Slic3r::coPercent, Slic3r::coPercents, Slic3r::coPoints, Slic3r::coString, Slic3r::coStrings, Slic3r::GUI::double_to_string(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::from_u8(), Slic3r::GUI::get_thumbnails_string(), Slic3r::GUI::into_u8(), Slic3r::is_decimal_separator_point(), L, Slic3r::GUI::na_value(), Slic3r::ConfigOptionFloatsTempl< NULLABLE >::nil_value(), and Slic3r::GUI::show_error().
getSizer()
virtual wxSizer * Slic3r::GUI::Field::getSizer () inline virtual
If you don't know what you are getting back, check both methods for nullptr.
Reimplemented in Slic3r::GUI::PointCtrl, and Slic3r::GUI::SliderCtrl.
{ return nullptr; }
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::correct_items_positions(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::render(), and Slic3r::GUI::OG_CustomCtrl::CtrlLine::update_visibility().
getWindow()
virtual wxWindow * Slic3r::GUI::Field::getWindow () inline virtual
Reimplemented in Slic3r::GUI::TextCtrl, Slic3r::GUI::CheckBox, Slic3r::GUI::SpinCtrl, Slic3r::GUI::Choice, Slic3r::GUI::ColourPicker, Slic3r::GUI::PointCtrl, Slic3r::GUI::StaticText, and Slic3r::GUI::SliderCtrl.
{ return nullptr; }
Referenced by ~Field(), Slic3r::GUI::Tab::activate_option(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::correct_items_positions(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::get_max_win_width(), Slic3r::GUI::OG_CustomCtrl::get_pos(), PostInitialize(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::render(), Slic3r::GUI::OptionsGroup::show_field(), and Slic3r::GUI::OG_CustomCtrl::CtrlLine::update_visibility().
has_undo_ui()
bool Slic3r::GUI::UndoValueUIManager::has_undo_ui () const inline inherited
{ return m_undo_ui.undo_bitmap != nullptr; }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::get_pos(), and Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
is_matched()
bool Slic3r::GUI::Field::is_matched (const std::string & string, const std::string & pattern)
{
  std::regex regex_pattern(pattern, std::regex_constants::icase); // use ::icase to make the matching case insensitive like /i in perl
  return std::regex_match(string, regex_pattern);
}
label_color()
const wxColour * Slic3r::GUI::UndoValueUIManager::label_color () const inline inherited
{ return m_undo_ui.label_color; }
References Slic3r::GUI::UndoValueUIManager::UndoValueUI::label_color, and Slic3r::GUI::UndoValueUIManager::m_undo_ui.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
msw_rescale()
void Slic3r::GUI::Field::msw_rescale () virtual
Reimplemented in Slic3r::GUI::TextCtrl, Slic3r::GUI::CheckBox, Slic3r::GUI::SpinCtrl, Slic3r::GUI::Choice, Slic3r::GUI::ColourPicker, Slic3r::GUI::PointCtrl, and Slic3r::GUI::StaticText.
{
  // update em_unit value
  m_em_unit = em_unit(m_parent);
}
References em_unit().
on_back_to_initial_value()
void Slic3r::GUI::Field::on_back_to_initial_value ()
Call the attached m_back_to_initial_value method.
{
  if (m_back_to_initial_value != nullptr && m_is_modified_value)
    m_back_to_initial_value(m_opt_id);
}
on_back_to_sys_value()
void Slic3r::GUI::Field::on_back_to_sys_value ()
Call the attached m_back_to_sys_value method.
{
  if (m_back_to_sys_value != nullptr && m_is_nonsys_value)
    m_back_to_sys_value(m_opt_id);
}
on_change_field()
void Slic3r::GUI::Field::on_change_field () protected
Call the attached on_change method.
{
//       std::cerr << "calling Field::_on_change \n";
    if (m_on_change != nullptr  && !m_disable_change_event)
        m_on_change(m_opt_id, get_value());
}
Referenced by field_changed().
on_kill_focus()
void Slic3r::GUI::Field::on_kill_focus () protected
Call the attached on_kill_focus method. It's important to use wxEvent instead of wxFocusEvent, in another case we can't unfocused control at all.
{
  // call the registered function if it is available
    if (m_on_kill_focus!=nullptr)
        m_on_kill_focus(m_opt_id);
}
PostInitialize()
void Slic3r::GUI::Field::PostInitialize () protected virtual
{
  auto color = wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW);
  switch (m_opt.type)
  {
  case coPercents:
  case coFloats:
  case coStrings:
  case coBools:
  case coInts: {
    auto tag_pos = m_opt_id.find("#");
    if (tag_pos != std::string::npos)
      m_opt_idx = stoi(m_opt_id.substr(tag_pos + 1, m_opt_id.size()));
    break;
  }
  default:
    break;
  }
    // initialize m_unit_value
    m_em_unit = em_unit(m_parent);
    parent_is_custom_ctrl = dynamic_cast<OG_CustomCtrl*>(m_parent) != nullptr;
  BUILD();
  // For the mode, when settings are in non-modal dialog, neither dialog nor tabpanel doesn't receive wxEVT_KEY_UP event, when some field is selected.
  // So, like a workaround check wxEVT_KEY_UP event for the Filed and switch between tabs if Ctrl+(1-4) was pressed
  if (getWindow())
    getWindow()->Bind(wxEVT_KEY_UP, [](wxKeyEvent& evt) {
        if ((evt.GetModifiers() & wxMOD_CONTROL) != 0) {
          int tab_id = -1;
          switch (evt.GetKeyCode()) {
          case '1': { tab_id = 0; break; }
          case '2': { tab_id = 1; break; }
        case '3': { tab_id = 2; break; }
        case '4': { tab_id = 3; break; }
#ifdef __APPLE__
        case 'f':
#else /* __APPLE__ */
        case WXK_CONTROL_F:
#endif /* __APPLE__ */
        case 'F': { wxGetApp().plater()->search(false); break; }
          default: break;
          }
          if (tab_id >= 0)
          wxGetApp().mainframe->select_tab(tab_id);
        if (tab_id > 0)
          // tab panel should be focused for correct navigation between tabs
            wxGetApp().tab_panel()->SetFocus();
        }
        evt.Skip();
      });
}
References BUILD(), Slic3r::coBools, Slic3r::coFloats, Slic3r::coInts, Slic3r::coPercents, Slic3r::coStrings, em_unit(), getWindow(), if(), m_em_unit, m_opt, m_opt_id, m_opt_idx, m_parent, parent_is_custom_ctrl, and Slic3r::ConfigOptionDef::type.
set_enter_pressed()
void Slic3r::GUI::Field::set_enter_pressed (bool pressed) inline
{ bEnterPressed = pressed; }
References bEnterPressed.
Referenced by Slic3r::GUI::Field::EnterPressed::EnterPressed(), and Slic3r::GUI::Field::EnterPressed::~EnterPressed().
set_label_colour()
bool Slic3r::GUI::UndoValueUIManager::set_label_colour (const wxColour * clr) inline inherited
{ return m_undo_ui.set_label_colour(clr); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_label_colour().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), Slic3r::GUI::Tab::decorate(), and Slic3r::GUI::Tab::update_label_colours().
set_last_meaningful_value()
virtual void Slic3r::GUI::Field::set_last_meaningful_value () inline virtual
Reimplemented in Slic3r::GUI::TextCtrl, Slic3r::GUI::CheckBox, and Slic3r::GUI::SpinCtrl.
{}
set_na_value()
virtual void Slic3r::GUI::Field::set_na_value () inline virtual
Reimplemented in Slic3r::GUI::TextCtrl, Slic3r::GUI::CheckBox, and Slic3r::GUI::SpinCtrl.
{}
set_undo_bitmap()
bool Slic3r::GUI::UndoValueUIManager::set_undo_bitmap (const ScalableBitmap * bmp) inline inherited
{ return m_undo_ui.set_undo_bitmap(bmp); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_bitmap().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_undo_to_sys_bitmap()
bool Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_bitmap (const ScalableBitmap * bmp) inline inherited
{ return m_undo_ui.set_undo_to_sys_bitmap(bmp); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_to_sys_bitmap().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_undo_to_sys_tooltip()
bool Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_tooltip (const wxString * tip) inline inherited
{ return m_undo_ui.set_undo_to_sys_tooltip(tip); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_to_sys_tooltip().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_undo_tooltip()
bool Slic3r::GUI::UndoValueUIManager::set_undo_tooltip (const wxString * tip) inline inherited
{ return m_undo_ui.set_undo_tooltip(tip); }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_tooltip().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_value()
virtual void Slic3r::GUI::Field::set_value (const boost::any & value, bool change_event) pure virtual
Sets a value for this control. subclasses should overload with a specific version Postcondition: Method does not fire the on_change event.
Implemented in Slic3r::GUI::TextCtrl, Slic3r::GUI::CheckBox, Slic3r::GUI::SpinCtrl, Slic3r::GUI::Choice, Slic3r::GUI::ColourPicker, Slic3r::GUI::PointCtrl, Slic3r::GUI::StaticText, and Slic3r::GUI::SliderCtrl.
Referenced by Slic3r::GUI::Tab::on_value_change().
sys_color_changed()
void Slic3r::GUI::Field::sys_color_changed () virtual
Reimplemented in Slic3r::GUI::ColourPicker, and Slic3r::GUI::PointCtrl.
{
#ifdef _WIN32
  if (wxWindow* win = this->getWindow())
    wxGetApp().UpdateDarkUI(win);
#endif
}
toggle()
void Slic3r::GUI::Field::toggle (bool en) inline
Fires the enable or disable function, based on the input.
{ en ? enable() : disable(); }
References disable(), and enable().
Referenced by Slic3r::GUI::Tab::compatible_widget_reload(), Slic3r::GUI::Tab::toggle_option(), Slic3r::GUI::ObjectSettings::update_config_values(), and Slic3r::GUI::TabFilament::update_line_with_near_label_widget().
undo_bitmap()
const wxBitmapBundle & Slic3r::GUI::UndoValueUIManager::undo_bitmap () const inline inherited
{ return m_undo_ui.undo_bitmap->bmp(); }
References ScalableBitmap::bmp(), Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
undo_to_sys_bitmap()
const wxBitmapBundle & Slic3r::GUI::UndoValueUIManager::undo_to_sys_bitmap () const inline inherited
{ return m_undo_ui.undo_to_sys_bitmap->bmp(); }
References ScalableBitmap::bmp(), Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_to_sys_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
undo_to_sys_tooltip()
const wxString * Slic3r::GUI::UndoValueUIManager::undo_to_sys_tooltip () const inline inherited
{ return m_undo_ui.undo_to_sys_tooltip; }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_to_sys_tooltip.
undo_tooltip()
const wxString * Slic3r::GUI::UndoValueUIManager::undo_tooltip () const inline inherited
{ return m_undo_ui.undo_tooltip; }
References Slic3r::GUI::UndoValueUIManager::m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_tooltip.
Friends And Related Symbol Documentation
OptionsGroup
friend class OptionsGroup friend
Member Data Documentation
bEnterPressed
bool Slic3r::GUI::Field::bEnterPressed = false protected
Referenced by get_enter_pressed(), and set_enter_pressed().
m_back_to_initial_value
t_back_to_init Slic3r::GUI::Field::m_back_to_initial_value { nullptr }
Function object to store callback passed in from owning object.
Referenced by ~Field().
m_back_to_sys_value
t_back_to_init Slic3r::GUI::Field::m_back_to_sys_value { nullptr }
Referenced by ~Field().
m_disable_change_event
bool Slic3r::GUI::Field::m_disable_change_event {false}
Referenced by Slic3r::GUI::CheckBox::set_value(), Slic3r::GUI::StaticText::set_value(), Slic3r::GUI::TextCtrl::set_value(), Slic3r::GUI::ColourPicker::set_value(), and Slic3r::GUI::StaticText::set_value().
m_em_unit
int Slic3r::GUI::Field::m_em_unit protected
Referenced by PostInitialize().
m_is_modified_value
bool Slic3r::GUI::Field::m_is_modified_value {false}
Referenced by Slic3r::GUI::Tab::decorate().
m_is_nonsys_value
bool Slic3r::GUI::Field::m_is_nonsys_value {true}
Referenced by Slic3r::GUI::Tab::decorate().
m_last_meaningful_value
boost::any Slic3r::GUI::Field::m_last_meaningful_value protected
m_on_change
t_change Slic3r::GUI::Field::m_on_change {nullptr}
Function object to store callback passed in from owning object.
Referenced by ~Field().
m_on_kill_focus
t_kill_focus Slic3r::GUI::Field::m_on_kill_focus {nullptr}
Function object to store callback passed in from owning object.
Referenced by ~Field().
m_opt
const ConfigOptionDef Slic3r::GUI::Field::m_opt {ConfigOptionDef()}
Copy of ConfigOption for deduction purposes.
Referenced by PostInitialize(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
m_opt_id
const t_config_option_key Slic3r::GUI::Field::m_opt_id
Referenced by PostInitialize().
m_opt_idx
int Slic3r::GUI::Field::m_opt_idx = 0
{""};
Referenced by PostInitialize().
m_parent
wxWindow* Slic3r::GUI::Field::m_parent {nullptr}
parent wx item, opportunity to refactor (probably not necessary - data duplication)
Referenced by PostInitialize().
m_undo_ui
UndoValueUI Slic3r::GUI::UndoValueUIManager::m_undo_ui private inherited
Referenced by Slic3r::GUI::UndoValueUIManager::blink(), Slic3r::GUI::UndoValueUIManager::get_blink_ptr(), Slic3r::GUI::UndoValueUIManager::has_undo_ui(), Slic3r::GUI::UndoValueUIManager::label_color(), Slic3r::GUI::UndoValueUIManager::set_label_colour(), Slic3r::GUI::UndoValueUIManager::set_undo_bitmap(), Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_bitmap(), Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_tooltip(), Slic3r::GUI::UndoValueUIManager::set_undo_tooltip(), Slic3r::GUI::UndoValueUIManager::undo_bitmap(), Slic3r::GUI::UndoValueUIManager::undo_to_sys_bitmap(), Slic3r::GUI::UndoValueUIManager::undo_to_sys_tooltip(), and Slic3r::GUI::UndoValueUIManager::undo_tooltip().
m_value
boost::any Slic3r::GUI::Field::m_value protected
Referenced by Slic3r::GUI::StaticText::get_value().
opt_height
double Slic3r::GUI::Field::opt_height { 0.0 }
parent_is_custom_ctrl
bool Slic3r::GUI::Field::parent_is_custom_ctrl { false }
Referenced by PostInitialize().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Field.hpp
src/slic3r/GUI/Field.cpp