Prusa Slicer: Slic3r::GUI::FreqChangedParams Class Reference
Slic3r::GUI::FreqChangedParams Class Reference
Public Member Functions
FreqChangedParams (wxWindow *parent)
~FreqChangedParams ()
wxButton * get_wiping_dialog_button ()
wxSizer * get_sizer () override
ConfigOptionsGroup * get_og (const bool is_fff)
void Show (const bool is_fff) override
void msw_rescale ()
void sys_color_changed ()
virtual bool IsShown ()
virtual void Hide ()
virtual void UpdateAndShow (const bool show)
ConfigOptionsGroup * get_og ()
const ConfigOptionsGroup * get_og () const
wxWindow * parent () const
Protected Attributes
std::shared_ptr< ConfigOptionsGroup > m_og
wxWindow * m_parent
Private Attributes
double m_brim_width = 0.0
wxButton * m_wiping_dialog_button { nullptr }
wxSizer * m_sizer {nullptr}
std::shared_ptr< ConfigOptionsGroup > m_og_sla
std::vector< ScalableButton * > m_empty_buttons
Detailed Description
Constructor & Destructor Documentation
FreqChangedParams()
Slic3r::GUI::FreqChangedParams::FreqChangedParams (wxWindow * parent)
                                                     :
    OG_Settings(parent, false)
{
    DynamicPrintConfig* config = &wxGetApp().preset_bundle->prints.get_edited_preset().config;
    // Frequently changed parameters for FFF_technology
    m_og->set_config(config);
    m_og->hide_labels();
    m_og->m_on_change = [config, this](t_config_option_key opt_key, boost::any value) {
        Tab* tab_print = wxGetApp().get_tab(Preset::TYPE_PRINT);
        if (!tab_print) return;
        if (opt_key == "fill_density") {
            tab_print->update_dirty();
            tab_print->reload_config();
            tab_print->update();
        }
        else
        {
            DynamicPrintConfig new_conf = *config;
            if (opt_key == "brim") {
                double new_val;
                double brim_width = config->opt_float("brim_width");
                if (boost::any_cast<bool>(value) == true)
                {
                    new_val = m_brim_width == 0.0 ? 5 :
                        m_brim_width < 0.0 ? m_brim_width * (-1) :
                        m_brim_width;
                }
                else {
                    m_brim_width = brim_width * (-1);
                    new_val = 0;
                }
                new_conf.set_key_value("brim_width", new ConfigOptionFloat(new_val));
            }
            else {
                assert(opt_key == "support");
                const wxString& selection = boost::any_cast<wxString>(value);
                PrinterTechnology printer_technology = wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology();
                auto support_material = selection == _("None") ? false : true;
                new_conf.set_key_value("support_material", new ConfigOptionBool(support_material));
                if (selection == _("Everywhere")) {
                    new_conf.set_key_value("support_material_buildplate_only", new ConfigOptionBool(false));
                    if (printer_technology == ptFFF)
                        new_conf.set_key_value("support_material_auto", new ConfigOptionBool(true));
                } else if (selection == _("Support on build plate only")) {
                    new_conf.set_key_value("support_material_buildplate_only", new ConfigOptionBool(true));
                    if (printer_technology == ptFFF)
                        new_conf.set_key_value("support_material_auto", new ConfigOptionBool(true));
                } else if (selection == _("For support enforcers only")) {
                    assert(printer_technology == ptFFF);
                    new_conf.set_key_value("support_material_buildplate_only", new ConfigOptionBool(false));
                    new_conf.set_key_value("support_material_auto", new ConfigOptionBool(false));
                }
            }
            tab_print->load_config(new_conf);
        }
    };
    Line line = Line { "", "" };
    ConfigOptionDef support_def;
    support_def.label = L("Supports");
    support_def.type = coStrings;
    support_def.tooltip = L("Select what kind of support do you need");
    support_def.set_enum_labels(ConfigOptionDef::GUIType::select_close, {
        L("None"),
        L("Support on build plate only"),
        L("For support enforcers only"),
        L("Everywhere")
    });
    support_def.set_default_value(new ConfigOptionStrings{ "None" });
    Option option = Option(support_def, "support");
    option.opt.full_width = true;
    line.append_option(option);
    /* Not a best solution, but
     * Temporary workaround for right border alignment
     */
    auto empty_widget = [this] (wxWindow* parent) {
        auto sizer = new wxBoxSizer(wxHORIZONTAL);
        auto btn = new ScalableButton(parent, wxID_ANY, "mirroring_transparent", wxEmptyString,
            wxDefaultSize, wxDefaultPosition, wxBU_EXACTFIT | wxNO_BORDER | wxTRANSPARENT_WINDOW);
        sizer->Add(btn, 0, wxALIGN_CENTER_VERTICAL | wxLEFT | wxRIGHT, int(0.3 * wxGetApp().em_unit()));
        m_empty_buttons.push_back(btn);
        return sizer;
    };
    line.append_widget(empty_widget);
    m_og->append_line(line);
    line = Line { "", "" };
    option = m_og->get_option("fill_density");
    option.opt.label = L("Infill");
    option.opt.width = 8;
    option.opt.sidetext = "   ";
    line.append_option(option);
    m_brim_width = config->opt_float("brim_width");
    ConfigOptionDef def;
    def.label = L("Brim");
    def.type = coBool;
    def.tooltip = L("This flag enables the brim that will be printed around each object on the first layer.");
    def.gui_type = ConfigOptionDef::GUIType::undefined;
    def.set_default_value(new ConfigOptionBool{ m_brim_width > 0.0 ? true : false });
    option = Option(def, "brim");
    option.opt.sidetext = "";
    line.append_option(option);
    auto wiping_dialog_btn = [this](wxWindow* parent) {
        m_wiping_dialog_button = new wxButton(parent, wxID_ANY, _L("Purging volumes") + dots, wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
        m_wiping_dialog_button->SetFont(wxGetApp().normal_font());
        wxGetApp().UpdateDarkUI(m_wiping_dialog_button, true);
        auto sizer = new wxBoxSizer(wxHORIZONTAL);
        sizer->Add(m_wiping_dialog_button, 0, wxALIGN_CENTER_VERTICAL);
        m_wiping_dialog_button->Bind(wxEVT_BUTTON, ([parent](wxCommandEvent& e)
        {
            auto &project_config = wxGetApp().preset_bundle->project_config;
            const std::vector<double> &init_matrix = (project_config.option<ConfigOptionFloats>("wiping_volumes_matrix"))->values;
            const std::vector<double> &init_extruders = (project_config.option<ConfigOptionFloats>("wiping_volumes_extruders"))->values;
            const std::vector<std::string> extruder_colours = wxGetApp().plater()->get_extruder_colors_from_plater_config();
            WipingDialog dlg(parent, cast<float>(init_matrix), cast<float>(init_extruders), extruder_colours);
            if (dlg.ShowModal() == wxID_OK) {
                std::vector<float> matrix = dlg.get_matrix();
                std::vector<float> extruders = dlg.get_extruders();
                (project_config.option<ConfigOptionFloats>("wiping_volumes_matrix"))->values = std::vector<double>(matrix.begin(), matrix.end());
                (project_config.option<ConfigOptionFloats>("wiping_volumes_extruders"))->values = std::vector<double>(extruders.begin(), extruders.end());
                // Update Project dirty state, update application title bar.
                wxGetApp().plater()->update_project_dirty_from_presets();
                wxPostEvent(parent, SimpleEvent(EVT_SCHEDULE_BACKGROUND_PROCESS, parent));
            }
        }));
        auto btn = new ScalableButton(parent, wxID_ANY, "mirroring_transparent", wxEmptyString,
                                      wxDefaultSize, wxDefaultPosition, wxBU_EXACTFIT | wxNO_BORDER | wxTRANSPARENT_WINDOW);
        sizer->Add(btn , 0, wxALIGN_CENTER_VERTICAL | wxLEFT | wxRIGHT,
            int(0.3 * wxGetApp().em_unit()));
        m_empty_buttons.push_back(btn);
        return sizer;
    };
    line.append_widget(wiping_dialog_btn);
    m_og->append_line(line);
    m_og->activate();
    Choice* choice = dynamic_cast<Choice*>(m_og->get_field("support"));
    choice->suppress_scroll();
    // Frequently changed parameters for SLA_technology
    m_og_sla = std::make_shared<ConfigOptionsGroup>(parent, "");
    m_og_sla->hide_labels();
    DynamicPrintConfig* config_sla = &wxGetApp().preset_bundle->sla_prints.get_edited_preset().config;
    m_og_sla->set_config(config_sla);
    m_og_sla->m_on_change = [config_sla](t_config_option_key opt_key, boost::any value) {
        Tab* tab = wxGetApp().get_tab(Preset::TYPE_SLA_PRINT);
        if (!tab) return;
        DynamicPrintConfig new_conf = *config_sla;
        if (opt_key == "pad") {
            const wxString& selection = boost::any_cast<wxString>(value);
            const bool pad_enable = selection == _("None") ? false : true;
            new_conf.set_key_value("pad_enable", new ConfigOptionBool(pad_enable));
            if (selection == _("Below object"))
                new_conf.set_key_value("pad_around_object", new ConfigOptionBool(false));
            else if (selection == _("Around object"))
                new_conf.set_key_value("pad_around_object", new ConfigOptionBool(true));
        }
        else
        {
            assert(opt_key == "support");
            const wxString& selection = boost::any_cast<wxString>(value);
            const bool supports_enable = selection == _("None") ? false : true;
            new_conf.set_key_value("supports_enable", new ConfigOptionBool(supports_enable));
            std::string treetype = get_sla_suptree_prefix(new_conf);
            if (selection == _("Everywhere")) {
                new_conf.set_key_value(treetype + "support_buildplate_only", new ConfigOptionBool(false));
                new_conf.set_key_value("support_enforcers_only", new ConfigOptionBool(false));
            }
            else if (selection == _("Support on build plate only")) {
                new_conf.set_key_value(treetype + "support_buildplate_only", new ConfigOptionBool(true));
                new_conf.set_key_value("support_enforcers_only", new ConfigOptionBool(false));
            }
            else if (selection == _("For support enforcers only")) {
                new_conf.set_key_value("support_enforcers_only", new ConfigOptionBool(true));
            }
        }
        tab->load_config(new_conf);
        tab->update_dirty();
    };
    line = Line{ "", "" };
    ConfigOptionDef support_def_sla = support_def;
    support_def_sla.set_default_value(new ConfigOptionStrings{ "None" });
    option = Option(support_def_sla, "support");
    option.opt.full_width = true;
    line.append_option(option);
    line.append_widget(empty_widget);
    m_og_sla->append_line(line);
    line = Line{ "", "" };
    ConfigOptionDef pad_def;
    pad_def.label = L("Pad");
    pad_def.type = coStrings;
    pad_def.tooltip = L("Select what kind of pad do you need");
    pad_def.set_enum_labels(ConfigOptionDef::GUIType::select_close, {
        L("None"),
        L("Below object"),
        L("Around object")
    });
    pad_def.set_default_value(new ConfigOptionStrings{ "Below object" });
    option = Option(pad_def, "pad");
    option.opt.full_width = true;
    line.append_option(option);
    line.append_widget(empty_widget);
    m_og_sla->append_line(line);
    m_og_sla->activate();
    choice = dynamic_cast<Choice*>(m_og_sla->get_field("support"));
    choice->suppress_scroll();
    choice = dynamic_cast<Choice*>(m_og_sla->get_field("pad"));
    choice->suppress_scroll();
    m_sizer = new wxBoxSizer(wxVERTICAL);
    m_sizer->Add(m_og->sizer, 0, wxEXPAND);
    m_sizer->Add(m_og_sla->sizer, 0, wxEXPAND);
}
References _, _L, Slic3r::GUI::Line::append_option(), Slic3r::GUI::Line::append_widget(), Slic3r::coBool, Slic3r::coStrings, Slic3r::GUI::dots(), em_unit(), WipingDialog::get_extruders(), WipingDialog::get_matrix(), Slic3r::get_sla_suptree_prefix(), Slic3r::ConfigOptionDef::gui_type, L, Slic3r::ConfigOptionDef::label, Slic3r::GUI::Tab::load_config(), m_brim_width, m_empty_buttons, Slic3r::GUI::OG_Settings::m_og, m_og_sla, m_sizer, m_wiping_dialog_button, Slic3r::ConfigBase::opt_float(), Slic3r::GUI::OG_Settings::parent(), Slic3r::GUI::printer_technology(), Slic3r::ptFFF, Slic3r::GUI::Tab::reload_config(), Slic3r::ConfigOptionDef::select_close, Slic3r::ConfigOptionDef::set_default_value(), Slic3r::ConfigOptionDef::set_enum_labels(), Slic3r::DynamicConfig::set_key_value(), Slic3r::supports_enable(), Slic3r::GUI::Choice::suppress_scroll(), Slic3r::ConfigOptionDef::tooltip, Slic3r::ConfigOptionDef::type, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_SLA_PRINT, Slic3r::ConfigOptionDef::undefined, Slic3r::GUI::Tab::update(), Slic3r::GUI::Tab::update_dirty(), and wxEVT_BUTTON.
~FreqChangedParams()
Slic3r::GUI::FreqChangedParams::~FreqChangedParams () inline
{}
Member Function Documentation
get_og() [1/3]
ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () inline inherited
{ return m_og.get(); }
References Slic3r::GUI::OG_Settings::m_og.
Referenced by Slic3r::GUI::ObjectManipulation::msw_rescale(), and Slic3r::GUI::ObjectManipulation::sys_color_changed().
get_og() [2/3]
const ConfigOptionsGroup * Slic3r::GUI::OG_Settings::get_og () const inline inherited
{ return m_og.get(); }
References Slic3r::GUI::OG_Settings::m_og.
get_og() [3/3]
ConfigOptionsGroup * Slic3r::GUI::FreqChangedParams::get_og (const bool is_fff)
{
    return is_fff ? m_og.get() : m_og_sla.get();
}
References Slic3r::GUI::OG_Settings::m_og, and m_og_sla.
get_sizer()
wxSizer * Slic3r::GUI::FreqChangedParams::get_sizer () override virtual
Reimplemented from Slic3r::GUI::OG_Settings.
{
    return m_sizer;
}
References m_sizer.
get_wiping_dialog_button()
wxButton * Slic3r::GUI::FreqChangedParams::get_wiping_dialog_button () inline
{ return m_wiping_dialog_button; }
References m_wiping_dialog_button.
Hide()
void Slic3r::GUI::OG_Settings::Hide () virtual inherited
{
    Show(false);
}
References Slic3r::GUI::OG_Settings::Show().
IsShown()
bool Slic3r::GUI::OG_Settings::IsShown () virtual inherited
Reimplemented in Slic3r::GUI::ObjectManipulation.
{
    return m_og->sizer->IsEmpty() ? false : m_og->sizer->IsShown(size_t(0));
}
References Slic3r::GUI::OG_Settings::m_og.
msw_rescale()
void Slic3r::GUI::FreqChangedParams::msw_rescale ()
{
    m_og->msw_rescale();
    m_og_sla->msw_rescale();
}
References Slic3r::GUI::OG_Settings::m_og, and m_og_sla.
parent()
wxWindow * Slic3r::GUI::OG_Settings::parent () const inline inherited
{return m_parent; }
References Slic3r::GUI::OG_Settings::m_parent.
Referenced by FreqChangedParams(), Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectSettings::ObjectSettings(), Slic3r::GUI::OG_Settings::OG_Settings(), Slic3r::GUI::ObjectManipulation::msw_rescale(), and Slic3r::GUI::ObjectSettings::update_settings_list().
Show()
void Slic3r::GUI::FreqChangedParams::Show (const bool is_fff) override virtual
Reimplemented from Slic3r::GUI::OG_Settings.
{
    const bool is_wdb_shown = m_wiping_dialog_button->IsShown();
    m_og->Show(is_fff);
    m_og_sla->Show(!is_fff);
    // correct showing of the FreqChangedParams sizer when m_wiping_dialog_button is hidden
    if (is_fff && !is_wdb_shown)
        m_wiping_dialog_button->Hide();
}
References Slic3r::GUI::OG_Settings::m_og, m_og_sla, and m_wiping_dialog_button.
sys_color_changed()
void Slic3r::GUI::FreqChangedParams::sys_color_changed ()
{
    m_og->sys_color_changed();
    m_og_sla->sys_color_changed();
    for (auto btn: m_empty_buttons)
        btn->sys_color_changed();
    wxGetApp().UpdateDarkUI(m_wiping_dialog_button, true);
}
References m_empty_buttons, Slic3r::GUI::OG_Settings::m_og, m_og_sla, and m_wiping_dialog_button.
UpdateAndShow()
void Slic3r::GUI::OG_Settings::UpdateAndShow (const bool show) virtual inherited
Reimplemented in Slic3r::GUI::ObjectLayers, Slic3r::GUI::ObjectManipulation, and Slic3r::GUI::ObjectSettings.
{
    Show(show);
//    m_parent->Layout();
}
References Slic3r::GUI::OG_Settings::Show().
Referenced by Slic3r::GUI::ObjectManipulation::UpdateAndShow(), and Slic3r::GUI::ObjectSettings::UpdateAndShow().
Member Data Documentation
m_brim_width
double Slic3r::GUI::FreqChangedParams::m_brim_width = 0.0 private
Referenced by FreqChangedParams().
m_empty_buttons
std::vector<ScalableButton*> Slic3r::GUI::FreqChangedParams::m_empty_buttons private
Referenced by FreqChangedParams(), and sys_color_changed().
m_og
std::shared_ptr<ConfigOptionsGroup> Slic3r::GUI::OG_Settings::m_og protected inherited
Referenced by FreqChangedParams(), Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectSettings::ObjectSettings(), Slic3r::GUI::OG_Settings::OG_Settings(), Slic3r::GUI::OG_Settings::get_og(), Slic3r::GUI::OG_Settings::get_og(), get_og(), Slic3r::GUI::OG_Settings::get_sizer(), Slic3r::GUI::OG_Settings::IsShown(), Slic3r::GUI::ObjectManipulation::IsShown(), msw_rescale(), Show(), Slic3r::GUI::OG_Settings::Show(), Slic3r::GUI::ObjectManipulation::Show(), Slic3r::GUI::ObjectSettings::sys_color_changed(), sys_color_changed(), Slic3r::GUI::ObjectManipulation::update_if_dirty(), and Slic3r::GUI::ObjectSettings::update_settings_list().
m_og_sla
std::shared_ptr<ConfigOptionsGroup> Slic3r::GUI::FreqChangedParams::m_og_sla private
Referenced by FreqChangedParams(), get_og(), msw_rescale(), Show(), and sys_color_changed().
m_parent
wxWindow* Slic3r::GUI::OG_Settings::m_parent protected inherited
Referenced by Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::OG_Settings::parent(), Slic3r::GUI::ObjectSettings::update_config_values(), Slic3r::GUI::ObjectSettings::update_settings_list(), and Slic3r::GUI::ObjectManipulation::update_warning_icon_state().
m_sizer
wxSizer* Slic3r::GUI::FreqChangedParams::m_sizer {nullptr} private
Referenced by FreqChangedParams(), and get_sizer().
m_wiping_dialog_button
wxButton* Slic3r::GUI::FreqChangedParams::m_wiping_dialog_button { nullptr } private
Referenced by FreqChangedParams(), get_wiping_dialog_button(), Show(), and sys_color_changed().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Plater.cpp