Prusa Slicer: Slic3r::GUI::UndoValueUIManager Class Reference
Slic3r::GUI::UndoValueUIManager Class Reference
#include <src/slic3r/GUI/Field.hpp>
Classes
struct UndoValueUI
Public Member Functions
UndoValueUIManager ()
~UndoValueUIManager ()
bool set_undo_bitmap (const ScalableBitmap *bmp)
bool set_undo_to_sys_bitmap (const ScalableBitmap *bmp)
bool set_label_colour (const wxColour *clr)
bool set_undo_tooltip (const wxString *tip)
bool set_undo_to_sys_tooltip (const wxString *tip)
bool has_undo_ui () const
const wxBitmapBundle & undo_bitmap () const
const wxString * undo_tooltip () const
const wxBitmapBundle & undo_to_sys_bitmap () const
const wxString * undo_to_sys_tooltip () const
const wxColour * label_color () const
const bool blink () const
bool * get_blink_ptr ()
Private Attributes
UndoValueUI m_undo_ui
Detailed Description
Constructor & Destructor Documentation
UndoValueUIManager()
Slic3r::GUI::UndoValueUIManager::UndoValueUIManager () inline
{}
~UndoValueUIManager()
Slic3r::GUI::UndoValueUIManager::~UndoValueUIManager () inline
{}
Member Function Documentation
blink()
const bool Slic3r::GUI::UndoValueUIManager::blink () const inline
{ return m_undo_ui.blink; }
References Slic3r::GUI::UndoValueUIManager::UndoValueUI::blink, and m_undo_ui.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
get_blink_ptr()
bool * Slic3r::GUI::UndoValueUIManager::get_blink_ptr () inline
{ return &m_undo_ui.blink; }
References Slic3r::GUI::UndoValueUIManager::UndoValueUI::blink, and m_undo_ui.
Referenced by Slic3r::GUI::ConfigOptionsGroup::get_custom_ctrl_with_blinking_ptr().
has_undo_ui()
bool Slic3r::GUI::UndoValueUIManager::has_undo_ui () const inline
{ return m_undo_ui.undo_bitmap != nullptr; }
References m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::get_pos(), and Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
label_color()
const wxColour * Slic3r::GUI::UndoValueUIManager::label_color () const inline
{ return m_undo_ui.label_color; }
References Slic3r::GUI::UndoValueUIManager::UndoValueUI::label_color, and m_undo_ui.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
set_label_colour()
bool Slic3r::GUI::UndoValueUIManager::set_label_colour (const wxColour * clr) inline
{ return m_undo_ui.set_label_colour(clr); }
References m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_label_colour().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), Slic3r::GUI::Tab::decorate(), and Slic3r::GUI::Tab::update_label_colours().
set_undo_bitmap()
bool Slic3r::GUI::UndoValueUIManager::set_undo_bitmap (const ScalableBitmap * bmp) inline
{ return m_undo_ui.set_undo_bitmap(bmp); }
References m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_bitmap().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_undo_to_sys_bitmap()
bool Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_bitmap (const ScalableBitmap * bmp) inline
{ return m_undo_ui.set_undo_to_sys_bitmap(bmp); }
References m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_to_sys_bitmap().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_undo_to_sys_tooltip()
bool Slic3r::GUI::UndoValueUIManager::set_undo_to_sys_tooltip (const wxString * tip) inline
{ return m_undo_ui.set_undo_to_sys_tooltip(tip); }
References m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_to_sys_tooltip().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
set_undo_tooltip()
bool Slic3r::GUI::UndoValueUIManager::set_undo_tooltip (const wxString * tip) inline
{ return m_undo_ui.set_undo_tooltip(tip); }
References m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::set_undo_tooltip().
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::decorate().
undo_bitmap()
const wxBitmapBundle & Slic3r::GUI::UndoValueUIManager::undo_bitmap () const inline
{ return m_undo_ui.undo_bitmap->bmp(); }
References ScalableBitmap::bmp(), m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
undo_to_sys_bitmap()
const wxBitmapBundle & Slic3r::GUI::UndoValueUIManager::undo_to_sys_bitmap () const inline
{ return m_undo_ui.undo_to_sys_bitmap->bmp(); }
References ScalableBitmap::bmp(), m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_to_sys_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
undo_to_sys_tooltip()
const wxString * Slic3r::GUI::UndoValueUIManager::undo_to_sys_tooltip () const inline
{ return m_undo_ui.undo_to_sys_tooltip; }
References m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_to_sys_tooltip.
undo_tooltip()
const wxString * Slic3r::GUI::UndoValueUIManager::undo_tooltip () const inline
{ return m_undo_ui.undo_tooltip; }
References m_undo_ui, and Slic3r::GUI::UndoValueUIManager::UndoValueUI::undo_tooltip.
Member Data Documentation
m_undo_ui
UndoValueUI Slic3r::GUI::UndoValueUIManager::m_undo_ui private
Referenced by blink(), get_blink_ptr(), has_undo_ui(), label_color(), set_label_colour(), set_undo_bitmap(), set_undo_to_sys_bitmap(), set_undo_to_sys_tooltip(), set_undo_tooltip(), undo_bitmap(), undo_to_sys_bitmap(), undo_to_sys_tooltip(), and undo_tooltip().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Field.hpp