Prusa Slicer: Slic3r::SLAPrintObject::SupportData Struct Reference
Slic3r::SLAPrintObject::SupportData Struct Reference
Public Member Functions
SupportData (const TriangleMesh &t)
SupportData (const indexed_triangle_set &t)
void create_support_tree (const sla::JobController &ctl)
void create_pad (const sla::JobController &ctl)
Public Attributes
sla::SupportableMesh input
std::vector< ExPolygons > support_slices
TriangleMesh tree_mesh
TriangleMesh pad_mesh
TriangleMesh full_mesh
Detailed Description
Constructor & Destructor Documentation
SupportData() [1/2]
Slic3r::SLAPrintObject::SupportData::SupportData (const TriangleMesh & t) inline
            : input{t.its, {}, {}}
        {}
SupportData() [2/2]
Slic3r::SLAPrintObject::SupportData::SupportData (const indexed_triangle_set & t) inline
            : input{t, {}, {}}
        {}
Member Function Documentation
create_pad()
void Slic3r::SLAPrintObject::SupportData::create_pad (const sla::JobController & ctl) inline
        {
            pad_mesh = TriangleMesh{sla::create_pad(input, tree_mesh.its, ctl)};
        }
References Slic3r::sla::create_pad(), and input().
create_support_tree()
void Slic3r::SLAPrintObject::SupportData::create_support_tree (const sla::JobController & ctl) inline
        {
            tree_mesh = TriangleMesh{sla::create_support_tree(input, ctl)};
        }
References Slic3r::sla::create_support_tree(), and input().
Member Data Documentation
full_mesh
TriangleMesh Slic3r::SLAPrintObject::SupportData::full_mesh
input
sla::SupportableMesh Slic3r::SLAPrintObject::SupportData::input
pad_mesh
TriangleMesh Slic3r::SLAPrintObject::SupportData::pad_mesh
support_slices
std::vector<ExPolygons> Slic3r::SLAPrintObject::SupportData::support_slices
tree_mesh
TriangleMesh Slic3r::SLAPrintObject::SupportData::tree_mesh
The documentation for this struct was generated from the following file:
src/libslic3r/SLAPrint.hpp