Prusa Slicer: QuadricEdgeCollapse::TriangleInfo Struct Reference
QuadricEdgeCollapse::TriangleInfo Struct Reference
Public Member Functions
TriangleInfo ()=default
bool is_deleted () const
void set_deleted ()
Public Attributes
Vec3f n
unsigned char min_index = 0
Detailed Description
Constructor & Destructor Documentation
TriangleInfo()
QuadricEdgeCollapse::TriangleInfo::TriangleInfo () default
Member Function Documentation
is_deleted()
bool QuadricEdgeCollapse::TriangleInfo::is_deleted () const inline
{ return n.x() > 2.f; }
References n.
Referenced by QuadricEdgeCollapse::compact(), and Slic3r::its_quadric_edge_collapse().
set_deleted()
void QuadricEdgeCollapse::TriangleInfo::set_deleted () inline
{ n.x() = 3.f; }
References n.
Referenced by Slic3r::its_quadric_edge_collapse().
Member Data Documentation
min_index
unsigned char QuadricEdgeCollapse::TriangleInfo::min_index = 0
Referenced by Slic3r::its_quadric_edge_collapse().
n
Vec3f QuadricEdgeCollapse::TriangleInfo::n
Referenced by is_deleted(), Slic3r::its_quadric_edge_collapse(), and set_deleted().
The documentation for this struct was generated from the following file:
src/libslic3r/QuadricEdgeCollapse.cpp