Prusa Slicer: src/avrdude/stk500.h File Reference
stk500.h File Reference
Functions
void stk500_initpgm (PROGRAMMER *pgm)
int stk500_getsync (PROGRAMMER *pgm)
int stk500_drain (PROGRAMMER *pgm, int display)
Variables
const char stk500_desc []
Function Documentation
stk500_drain()
int stk500_drain (PROGRAMMER * pgm, int display)
{
  return serial_drain(&pgm->fd, display);
}
References programmer_t::fd, pgm, and serial_drain.
Referenced by arduino_open(), stk500_getsync(), and stk500_open().
stk500_getsync()
int stk500_getsync (PROGRAMMER * pgm)
{
  unsigned char buf[32], resp[32];
  int attempt;
  /*
   * get in sync */
  buf[0] = Cmnd_STK_GET_SYNC;
  buf[1] = Sync_CRC_EOP;
  /*
   * First send and drain a few times to get rid of line noise
   */
  stk500_send(pgm, buf, 2);
  stk500_drain(pgm, 0);
  stk500_send(pgm, buf, 2);
  stk500_drain(pgm, 0);
  for (attempt = 0; attempt < MAX_SYNC_ATTEMPTS; attempt++) {
    stk500_send(pgm, buf, 2);
    stk500_recv(pgm, resp, 1);
    if (resp[0] == Resp_STK_INSYNC){
      break;
    }
    avrdude_message(MSG_INFO, "%s: stk500_getsync() attempt %d of %d: not in sync: resp=0x%02x\n",
                    progname, attempt + 1, MAX_SYNC_ATTEMPTS, resp[0]);
  }
  if (attempt == MAX_SYNC_ATTEMPTS) {
    stk500_drain(pgm, 0);
    return -1;
  }
  if (stk500_recv(pgm, resp, 1) < 0)
    return -1;
  if (resp[0] != Resp_STK_OK) {
    avrdude_message(MSG_INFO, "%s: stk500_getsync(): can't communicate with device: "
                    "resp=0x%02x\n",
                    progname, resp[0]);
    return -1;
  }
  return 0;
}
References avrdude_message(), Cmnd_STK_GET_SYNC, MAX_SYNC_ATTEMPTS, MSG_INFO, pgm, progname, Resp_STK_INSYNC, Resp_STK_OK, stk500_drain(), stk500_recv(), stk500_send(), and Sync_CRC_EOP.
Referenced by arduino_open(), mib510_isp(), stk500_disable(), stk500_getparm(), stk500_initialize(), stk500_loadaddr(), stk500_open(), stk500_paged_load(), stk500_paged_write(), stk500_program_enable(), stk500_set_extended_parms(), and stk500_setparm().
stk500_initpgm()
void stk500_initpgm (PROGRAMMER * pgm)
{
  strcpy(pgm->type, "STK500");
  /*
   * mandatory functions
   */
  pgm->initialize     = stk500_initialize;
  pgm->display        = stk500_display;
  pgm->enable         = stk500_enable;
  pgm->disable        = stk500_disable;
  pgm->program_enable = stk500_program_enable;
  pgm->chip_erase     = stk500_chip_erase;
  pgm->cmd            = stk500_cmd;
  pgm->open           = stk500_open;
  pgm->close          = stk500_close;
  pgm->read_byte      = avr_read_byte_default;
  pgm->write_byte     = avr_write_byte_default;
  /*
   * optional functions
   */
  pgm->paged_write    = stk500_paged_write;
  pgm->paged_load     = stk500_paged_load;
  pgm->print_parms    = stk500_print_parms;
  pgm->set_vtarget    = stk500_set_vtarget;
  pgm->set_varef      = stk500_set_varef;
  pgm->set_fosc       = stk500_set_fosc;
  pgm->set_sck_period = stk500_set_sck_period;
  pgm->setup          = stk500_setup;
  pgm->teardown       = stk500_teardown;
  pgm->page_size      = 256;
}
References avr_read_byte_default(), avr_write_byte_default(), programmer_t::chip_erase, programmer_t::close, programmer_t::cmd, programmer_t::disable, programmer_t::display, programmer_t::enable, programmer_t::initialize, programmer_t::open, programmer_t::page_size, programmer_t::paged_load, programmer_t::paged_write, pgm, programmer_t::print_parms, programmer_t::program_enable, programmer_t::read_byte, programmer_t::set_fosc, programmer_t::set_sck_period, programmer_t::set_varef, programmer_t::set_vtarget, programmer_t::setup, stk500_chip_erase(), stk500_close(), stk500_cmd(), stk500_disable(), stk500_display(), stk500_enable(), stk500_initialize(), stk500_open(), stk500_paged_load(), stk500_paged_write(), stk500_print_parms(), stk500_program_enable(), stk500_set_fosc(), stk500_set_sck_period(), stk500_set_varef(), stk500_set_vtarget(), stk500_setup(), stk500_teardown(), programmer_t::teardown, programmer_t::type, and programmer_t::write_byte.
Referenced by arduino_initpgm(), and stk500generic_open().
Variable Documentation
stk500_desc
const char stk500_desc[] extern