Prusa Slicer: Slic3r::Slicing Namespace Reference
Slic3r::Slicing Namespace Reference
Functions
coordf_t min_layer_height_from_nozzle (const DynamicPrintConfig &print_config, int idx_nozzle)
coordf_t max_layer_height_from_nozzle (const DynamicPrintConfig &print_config, int idx_nozzle)
Function Documentation
max_layer_height_from_nozzle()
coordf_t Slic3r::Slicing::max_layer_height_from_nozzle (const DynamicPrintConfig & print_config, int idx_nozzle)
{
    coordf_t min_layer_height = min_layer_height_from_nozzle(print_config, idx_nozzle);
    coordf_t max_layer_height = print_config.opt_float("max_layer_height", idx_nozzle - 1);
    coordf_t nozzle_dmr       = print_config.opt_float("nozzle_diameter", idx_nozzle - 1);
    return std::max(min_layer_height, (max_layer_height == 0.) ? (0.75 * nozzle_dmr) : max_layer_height);
}
References Slic3r::min_layer_height_from_nozzle(), and Slic3r::ConfigBase::opt_float().
min_layer_height_from_nozzle()
coordf_t Slic3r::Slicing::min_layer_height_from_nozzle (const DynamicPrintConfig & print_config, int idx_nozzle)
{
    coordf_t min_layer_height = print_config.opt_float("min_layer_height", idx_nozzle - 1);
    return (min_layer_height == 0.) ? MIN_LAYER_HEIGHT_DEFAULT : std::max(MIN_LAYER_HEIGHT, min_layer_height);
}
References Slic3r::MIN_LAYER_HEIGHT, Slic3r::MIN_LAYER_HEIGHT_DEFAULT, and Slic3r::ConfigBase::opt_float().
Referenced by Slic3r::PresetHints::top_bottom_shell_thickness_explanation().