Prusa Slicer: Eigen::internal::evaluator< SparseCompressedBase< Derived > > Struct Template Reference
Eigen::internal::evaluator< SparseCompressedBase< Derived > > Struct Template Reference
#include <src/eigen/Eigen/src/SparseCore/SparseCompressedBase.h>
Public Types
enum { CoeffReadCost = NumTraits<Scalar>::ReadCost , Flags = Derived::Flags }
typedef Derived::Scalar Scalar
typedef Derived::InnerIterator InnerIterator
typedef DenseCoeffsBase< Derived, ReadOnlyAccessors >::CoeffReturnType CoeffReturnType
enum
typedef traits< Derived > ExpressionTraits
Public Member Functions
evaluator ()
evaluator (const Derived &mat)
Index nonZerosEstimate () const
operator Derived & ()
operator const Derived & () const
const Scalar & coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
Protected Member Functions
Index find (Index row, Index col) const
Protected Attributes
const Derived * m_matrix
const Scalar m_zero
Detailed Description
template<typename Derived>
struct Eigen::internal::evaluator< SparseCompressedBase< Derived > >
Member Typedef Documentation
CoeffReturnType
template<typename Derived > typedef DenseCoeffsBase<Derived,ReadOnlyAccessors>::CoeffReturnType Eigen::internal::evaluator< SparseCompressedBase< Derived > >::CoeffReturnType
ExpressionTraits
typedef traits<Derived > Eigen::internal::evaluator_base< Derived >::ExpressionTraits inherited
InnerIterator
template<typename Derived > typedef Derived::InnerIterator Eigen::internal::evaluator< SparseCompressedBase< Derived > >::InnerIterator
Scalar
template<typename Derived > typedef Derived::Scalar Eigen::internal::evaluator< SparseCompressedBase< Derived > >::Scalar
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
       {
    Alignment = 0
  };
anonymous enum
template<typename Derived > anonymous enum
Enumerator
CoeffReadCost
Flags
       {
    CoeffReadCost = NumTraits<Scalar>::ReadCost,
    Flags = Derived::Flags
  };
Constructor & Destructor Documentation
evaluator() [1/2]
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::evaluator () inline
              : m_matrix(0), m_zero(0)
  {
    EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
  }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
evaluator() [2/2]
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::evaluator (const Derived & mat) inline explicit
                                         : m_matrix(&mat), m_zero(0)
  {
    EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
  }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff()
template<typename Derived > const Scalar & Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeff (Index row, Index col) const inline
  {
    Index p = find(row,col);
    if(p==Dynamic)
      return m_zero;
    else
      return m_matrix->const_cast_derived().valuePtr()[p];
  }
References col(), Eigen::Dynamic, and row().
coeffRef()
template<typename Derived > Scalar & Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeffRef (Index row, Index col) inline
  {
    Index p = find(row,col);
    eigen_assert(p!=Dynamic && "written coefficient does not exist");
    return m_matrix->const_cast_derived().valuePtr()[p];
  }
References col(), Eigen::Dynamic, eigen_assert, and row().
find()
template<typename Derived > Index Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find (Index row, Index col) const inline protected
  {
    eigen_internal_assert(row>=0 && row<m_matrix->rows() && col>=0 && col<m_matrix->cols());
    const Index outer = Derived::IsRowMajor ? row : col;
    const Index inner = Derived::IsRowMajor ? col : row;
    Index start = m_matrix->outerIndexPtr()[outer];
    Index end = m_matrix->isCompressed() ? m_matrix->outerIndexPtr()[outer+1] : m_matrix->outerIndexPtr()[outer] + m_matrix->innerNonZeroPtr()[outer];
    eigen_assert(end>=start && "you are using a non finalized sparse matrix or written coefficient does not exist");
    const Index p = std::lower_bound(m_matrix->innerIndexPtr()+start, m_matrix->innerIndexPtr()+end,inner) - m_matrix->innerIndexPtr();
    return ((p<end) && (m_matrix->innerIndexPtr()[p]==inner)) ? p : Dynamic;
  }
References col(), Eigen::Dynamic, eigen_assert, eigen_internal_assert, Eigen::end(), and row().
nonZerosEstimate()
template<typename Derived > Index Eigen::internal::evaluator< SparseCompressedBase< Derived > >::nonZerosEstimate () const inline
{
    return m_matrix->nonZeros();
  }
operator const Derived &()
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::operator const Derived & () const inline
{ return *m_matrix; }
operator Derived &()
template<typename Derived > Eigen::internal::evaluator< SparseCompressedBase< Derived > >::operator Derived & () inline
{ return m_matrix->const_cast_derived(); }
Member Data Documentation
m_matrix
template<typename Derived > const Derived* Eigen::internal::evaluator< SparseCompressedBase< Derived > >::m_matrix protected
m_zero
template<typename Derived > const Scalar Eigen::internal::evaluator< SparseCompressedBase< Derived > >::m_zero protected
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/SparseCore/SparseCompressedBase.h