Prusa Slicer: Eigen::SelfAdjointEigenSolver< _MatrixType > Class Template Reference
Eigen::SelfAdjointEigenSolver< _MatrixType > Class Template Reference
Computes eigenvalues and eigenvectors of selfadjoint matrices.
#include <src/eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h>
Public Types
enum { Size = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , Options = MatrixType::Options , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type _MatrixType.
typedef Eigen::Index Index
typedef Matrix< Scalar, Size, Size, ColMajor, MaxColsAtCompileTime, MaxColsAtCompileTime > EigenvectorsType
typedef NumTraits< Scalar >::Real RealScalar
Real scalar type for _MatrixType.
typedef internal::plain_col_type< MatrixType, RealScalar >::type RealVectorType
Type for vector of eigenvalues as returned by eigenvalues().
typedef Tridiagonalization< MatrixType > TridiagonalizationType
typedef TridiagonalizationType::SubDiagonalType SubDiagonalType
Public Member Functions
EIGEN_DEVICE_FUNC SelfAdjointEigenSolver ()
Default constructor for fixed-size matrices.
EIGEN_DEVICE_FUNC SelfAdjointEigenSolver (Index size)
Constructor, pre-allocates memory for dynamic-size matrices.
template<typename InputType >
EIGEN_DEVICE_FUNC SelfAdjointEigenSolver (const EigenBase< InputType > &matrix, int options=ComputeEigenvectors)
Constructor; computes eigendecomposition of given matrix.
template<typename InputType >
EIGEN_DEVICE_FUNC SelfAdjointEigenSolver & compute (const EigenBase< InputType > &matrix, int options=ComputeEigenvectors)
Computes eigendecomposition of given matrix.
EIGEN_DEVICE_FUNC SelfAdjointEigenSolver & computeDirect (const MatrixType &matrix, int options=ComputeEigenvectors)
Computes eigendecomposition of given matrix using a closed-form algorithm.
SelfAdjointEigenSolver & computeFromTridiagonal (const RealVectorType &diag, const SubDiagonalType &subdiag, int options=ComputeEigenvectors)
Computes the eigen decomposition from a tridiagonal symmetric matrix.
EIGEN_DEVICE_FUNC const EigenvectorsType & eigenvectors () const
Returns the eigenvectors of given matrix.
EIGEN_DEVICE_FUNC const RealVectorType & eigenvalues () const
Returns the eigenvalues of given matrix.
EIGEN_DEVICE_FUNC MatrixType operatorSqrt () const
Computes the positive-definite square root of the matrix.
EIGEN_DEVICE_FUNC MatrixType operatorInverseSqrt () const
Computes the inverse square root of the matrix.
EIGEN_DEVICE_FUNC ComputationInfo info () const
Reports whether previous computation was successful.
template<typename InputType >
EIGEN_DEVICE_FUNC SelfAdjointEigenSolver< MatrixType > & compute (const EigenBase< InputType > &a_matrix, int options)
Static Public Attributes
static const int m_maxIterations = 30
Maximum number of iterations.
Static Protected Member Functions
static void check_template_parameters ()
Protected Attributes
EigenvectorsType m_eivec
RealVectorType m_eivalues
TridiagonalizationType::SubDiagonalType m_subdiag
ComputationInfo m_info
bool m_isInitialized
bool m_eigenvectorsOk
Friends
struct internal::direct_selfadjoint_eigenvalues< SelfAdjointEigenSolver, Size, NumTraits< Scalar >::IsComplex >
Detailed Description
template<typename _MatrixType>
class Eigen::SelfAdjointEigenSolver< _MatrixType >
Computes eigenvalues and eigenvectors of selfadjoint matrices.
\eigenvalues_module
Template Parameters
_MatrixType the type of the matrix of which we are computing the eigendecomposition; this is expected to be an instantiation of the Matrix class template.
A matrix is selfadjoint if it equals its adjoint. For real matrices, this means that the matrix is symmetric: it equals its transpose. This class computes the eigenvalues and eigenvectors of a selfadjoint matrix. These are the scalars and vectors such that . The eigenvalues of a selfadjoint matrix are always real. If is a diagonal matrix with the eigenvalues on the diagonal, and is a matrix with the eigenvectors as its columns, then (for selfadjoint matrices, the matrix is always invertible). This is called the eigendecomposition.
The algorithm exploits the fact that the matrix is selfadjoint, making it faster and more accurate than the general purpose eigenvalue algorithms implemented in EigenSolver and ComplexEigenSolver.
Only the lower triangular part of the input matrix is referenced.
Call the function compute() to compute the eigenvalues and eigenvectors of a given matrix. Alternatively, you can use the SelfAdjointEigenSolver(const MatrixType&, int) constructor which computes the eigenvalues and eigenvectors at construction time. Once the eigenvalue and eigenvectors are computed, they can be retrieved with the eigenvalues() and eigenvectors() functions.
The documentation for SelfAdjointEigenSolver(const MatrixType&, int) contains an example of the typical use of this class.
To solve the generalized eigenvalue problem and the likes, see the class GeneralizedSelfAdjointEigenSolver.
See also
MatrixBase::eigenvalues(), class EigenSolver, class ComplexEigenSolver
Member Typedef Documentation
EigenvectorsType
template<typename _MatrixType > typedef Matrix<Scalar,Size,Size,ColMajor,MaxColsAtCompileTime,MaxColsAtCompileTime> Eigen::SelfAdjointEigenSolver< _MatrixType >::EigenvectorsType
Index
template<typename _MatrixType > typedef Eigen::Index Eigen::SelfAdjointEigenSolver< _MatrixType >::Index
MatrixType
template<typename _MatrixType > typedef _MatrixType Eigen::SelfAdjointEigenSolver< _MatrixType >::MatrixType
RealScalar
template<typename _MatrixType > typedef NumTraits<Scalar>::Real Eigen::SelfAdjointEigenSolver< _MatrixType >::RealScalar
Real scalar type for _MatrixType.
This is just Scalar if Scalar is real (e.g., float or double), and the type of the real part of Scalar if Scalar is complex.
RealVectorType
template<typename _MatrixType > typedef internal::plain_col_type<MatrixType,RealScalar>::type Eigen::SelfAdjointEigenSolver< _MatrixType >::RealVectorType
Type for vector of eigenvalues as returned by eigenvalues().
This is a column vector with entries of type RealScalar. The length of the vector is the size of _MatrixType.
Scalar
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::SelfAdjointEigenSolver< _MatrixType >::Scalar
Scalar type for matrices of type _MatrixType.
SubDiagonalType
template<typename _MatrixType > typedef TridiagonalizationType::SubDiagonalType Eigen::SelfAdjointEigenSolver< _MatrixType >::SubDiagonalType
TridiagonalizationType
template<typename _MatrixType > typedef Tridiagonalization<MatrixType> Eigen::SelfAdjointEigenSolver< _MatrixType >::TridiagonalizationType
Member Enumeration Documentation
anonymous enum
template<typename _MatrixType > anonymous enum
Enumerator
Size
ColsAtCompileTime
Options
MaxColsAtCompileTime
         {
      Size = MatrixType::RowsAtCompileTime,
      ColsAtCompileTime = MatrixType::ColsAtCompileTime,
      Options = MatrixType::Options,
      MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
    };
Constructor & Destructor Documentation
SelfAdjointEigenSolver() [1/3]
template<typename _MatrixType > EIGEN_DEVICE_FUNC Eigen::SelfAdjointEigenSolver< _MatrixType >::SelfAdjointEigenSolver () inline
Default constructor for fixed-size matrices.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). This constructor can only be used if _MatrixType is a fixed-size matrix; use SelfAdjointEigenSolver(Index) for dynamic-size matrices.
Example:
Output:
        : m_eivec(),
          m_eivalues(),
          m_subdiag(),
          m_isInitialized(false)
    { }
SelfAdjointEigenSolver() [2/3]
template<typename _MatrixType > EIGEN_DEVICE_FUNC Eigen::SelfAdjointEigenSolver< _MatrixType >::SelfAdjointEigenSolver (Index size) inline explicit
Constructor, pre-allocates memory for dynamic-size matrices.
Parameters
[in] size Positive integer, size of the matrix whose eigenvalues and eigenvectors will be computed.
This constructor is useful for dynamic-size matrices, when the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See also
compute() for an example
        : m_eivec(size, size),
          m_eivalues(size),
          m_subdiag(size > 1 ? size - 1 : 1),
          m_isInitialized(false)
    {}
SelfAdjointEigenSolver() [3/3]
template<typename _MatrixType > template<typename InputType > EIGEN_DEVICE_FUNC Eigen::SelfAdjointEigenSolver< _MatrixType >::SelfAdjointEigenSolver (const EigenBase< InputType > & matrix, int options = ComputeEigenvectors) inline explicit
Constructor; computes eigendecomposition of given matrix.
Parameters
[in] matrix Selfadjoint matrix whose eigendecomposition is to be computed. Only the lower triangular part of the matrix is referenced.
[in] options Can be ComputeEigenvectors (default) or EigenvaluesOnly.
This constructor calls compute(const MatrixType&, int) to compute the eigenvalues of the matrix matrix. The eigenvectors are computed if options equals ComputeEigenvectors.
Example:
Output:
See also
compute(const MatrixType&, int)
      : m_eivec(matrix.rows(), matrix.cols()),
        m_eivalues(matrix.cols()),
        m_subdiag(matrix.rows() > 1 ? matrix.rows() - 1 : 1),
        m_isInitialized(false)
    {
      compute(matrix.derived(), options);
    }
References Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), and Eigen::EigenBase< Derived >::derived().
Member Function Documentation
check_template_parameters()
template<typename _MatrixType > static void Eigen::SelfAdjointEigenSolver< _MatrixType >::check_template_parameters () inline static protected
    {
      EIGEN_STATIC_ASSERT_NON_INTEGER(Scalar);
    }
References EIGEN_STATIC_ASSERT_NON_INTEGER.
compute() [1/2]
template<typename _MatrixType > template<typename InputType > EIGEN_DEVICE_FUNC SelfAdjointEigenSolver< MatrixType > & Eigen::SelfAdjointEigenSolver< _MatrixType >::compute (const EigenBase< InputType > & a_matrix, int options)
{
  check_template_parameters();
  const InputType &matrix(a_matrix.derived());
  using std::abs;
  eigen_assert(matrix.cols() == matrix.rows());
  eigen_assert((options&~(EigVecMask|GenEigMask))==0
          && (options&EigVecMask)!=EigVecMask
          && "invalid option parameter");
  bool computeEigenvectors = (options&ComputeEigenvectors)==ComputeEigenvectors;
  Index n = matrix.cols();
  m_eivalues.resize(n,1);
  if(n==1)
  {
    m_eivec = matrix;
    m_eivalues.coeffRef(0,0) = numext::real(m_eivec.coeff(0,0));
    if(computeEigenvectors)
      m_eivec.setOnes(n,n);
    m_info = Success;
    m_isInitialized = true;
    m_eigenvectorsOk = computeEigenvectors;
    return *this;
  }
  // declare some aliases
  RealVectorType& diag = m_eivalues;
  EigenvectorsType& mat = m_eivec;
  // map the matrix coefficients to [-1:1] to avoid over- and underflow.
  mat = matrix.template triangularView<Lower>();
  RealScalar scale = mat.cwiseAbs().maxCoeff();
  if(scale==RealScalar(0)) scale = RealScalar(1);
  mat.template triangularView<Lower>() /= scale;
  m_subdiag.resize(n-1);
  internal::tridiagonalization_inplace(mat, diag, m_subdiag, computeEigenvectors);
  m_info = internal::computeFromTridiagonal_impl(diag, m_subdiag, m_maxIterations, computeEigenvectors, m_eivec);
  // scale back the eigen values
  m_eivalues *= scale;
  m_isInitialized = true;
  m_eigenvectorsOk = computeEigenvectors;
  return *this;
}
References Eigen::ComputeEigenvectors, Eigen::internal::computeFromTridiagonal_impl(), Eigen::EigenBase< Derived >::derived(), eigen_assert, Eigen::EigVecMask, Eigen::GenEigMask, scale(), Eigen::Success, and Eigen::internal::tridiagonalization_inplace().
compute() [2/2]
template<typename _MatrixType > template<typename InputType > EIGEN_DEVICE_FUNC SelfAdjointEigenSolver & Eigen::SelfAdjointEigenSolver< _MatrixType >::compute (const EigenBase< InputType > & matrix, int options = ComputeEigenvectors)
Computes eigendecomposition of given matrix.
Parameters
[in] matrix Selfadjoint matrix whose eigendecomposition is to be computed. Only the lower triangular part of the matrix is referenced.
[in] options Can be ComputeEigenvectors (default) or EigenvaluesOnly.
Returns
Reference to *this
This function computes the eigenvalues of matrix. The eigenvalues() function can be used to retrieve them. If options equals ComputeEigenvectors, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
This implementation uses a symmetric QR algorithm. The matrix is first reduced to tridiagonal form using the Tridiagonalization class. The tridiagonal matrix is then brought to diagonal form with implicit symmetric QR steps with Wilkinson shift. Details can be found in Section 8.3 of Golub & Van Loan, Matrix Computations.
The cost of the computation is about if the eigenvectors are required and if they are not required.
This method reuses the memory in the SelfAdjointEigenSolver object that was allocated when the object was constructed, if the size of the matrix does not change.
Example:
Output:
See also
SelfAdjointEigenSolver(const MatrixType&, int)
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::SelfAdjointEigenSolver().
computeDirect()
template<typename MatrixType > EIGEN_DEVICE_FUNC SelfAdjointEigenSolver< MatrixType > & Eigen::SelfAdjointEigenSolver< MatrixType >::computeDirect (const MatrixType & matrix, int options = ComputeEigenvectors)
Computes eigendecomposition of given matrix using a closed-form algorithm.
This is a variant of compute(const MatrixType&, int options) which directly solves the underlying polynomial equation.
Currently only 2x2 and 3x3 matrices for which the sizes are known at compile time are supported (e.g., Matrix3d).
This method is usually significantly faster than the QR iterative algorithm but it might also be less accurate. It is also worth noting that for 3x3 matrices it involves trigonometric operations which are not necessarily available for all scalar types.
For the 3x3 case, we observed the following worst case relative error regarding the eigenvalues:
double: 1e-8
float: 1e-3
See also
compute(const MatrixType&, int options)
{
  internal::direct_selfadjoint_eigenvalues<SelfAdjointEigenSolver,Size,NumTraits<Scalar>::IsComplex>::run(*this,matrix,options);
  return *this;
}
Referenced by igl::polar_dec().
computeFromTridiagonal()
template<typename MatrixType > SelfAdjointEigenSolver< MatrixType > & Eigen::SelfAdjointEigenSolver< MatrixType >::computeFromTridiagonal (const RealVectorType & diag, const SubDiagonalType & subdiag, int options = ComputeEigenvectors)
Computes the eigen decomposition from a tridiagonal symmetric matrix.
Parameters
[in] diag The vector containing the diagonal of the matrix.
[in] subdiag The subdiagonal of the matrix.
[in] options Can be ComputeEigenvectors (default) or EigenvaluesOnly.
Returns
Reference to *this
This function assumes that the matrix has been reduced to tridiagonal form.
See also
compute(const MatrixType&, int) for more information
{
  //TODO : Add an option to scale the values beforehand
  bool computeEigenvectors = (options&ComputeEigenvectors)==ComputeEigenvectors;
  m_eivalues = diag;
  m_subdiag = subdiag;
  if (computeEigenvectors)
  {
    m_eivec.setIdentity(diag.size(), diag.size());
  }
  m_info = internal::computeFromTridiagonal_impl(m_eivalues, m_subdiag, m_maxIterations, computeEigenvectors, m_eivec);
  m_isInitialized = true;
  m_eigenvectorsOk = computeEigenvectors;
  return *this;
}
References Eigen::ComputeEigenvectors, and Eigen::internal::computeFromTridiagonal_impl().
eigenvalues()
template<typename _MatrixType > EIGEN_DEVICE_FUNC const RealVectorType & Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvalues () const inline
Returns the eigenvalues of given matrix.
Returns
A const reference to the column vector containing the eigenvalues.
Precondition
The eigenvalues have been computed before.
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix. The eigenvalues are sorted in increasing order.
Example:
Output:
See also
eigenvectors(), MatrixBase::eigenvalues()
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      return m_eivalues;
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivalues, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
Referenced by Eigen::SelfAdjointView< _MatrixType, UpLo >::eigenvalues(), CurvatureCalculator::finalEigenStuff(), and igl::polar_dec().
eigenvectors()
template<typename _MatrixType > EIGEN_DEVICE_FUNC const EigenvectorsType & Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvectors () const inline
Returns the eigenvectors of given matrix.
Returns
A const reference to the matrix whose columns are the eigenvectors.
Precondition
The eigenvectors have been computed before.
Column of the returned matrix is an eigenvector corresponding to eigenvalue number as returned by eigenvalues(). The eigenvectors are normalized to have (Euclidean) norm equal to one. If this object was used to solve the eigenproblem for the selfadjoint matrix , then the matrix returned by this function is the matrix in the eigendecomposition .
Example:
Output:
See also
eigenvalues()
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
      return m_eivec;
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eigenvectorsOk, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivec, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
Referenced by CurvatureCalculator::finalEigenStuff(), igl::fit_plane(), and igl::polar_dec().
info()
template<typename _MatrixType > EIGEN_DEVICE_FUNC ComputationInfo Eigen::SelfAdjointEigenSolver< _MatrixType >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NoConvergence otherwise.
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      return m_info;
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_info, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
operatorInverseSqrt()
template<typename _MatrixType > EIGEN_DEVICE_FUNC MatrixType Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt () const inline
Computes the inverse square root of the matrix.
Returns
the inverse positive-definite square root of the matrix
Precondition
The eigenvalues and eigenvectors of a positive-definite matrix have been computed before.
This function uses the eigendecomposition to compute the inverse square root as . This is cheaper than first computing the square root with operatorSqrt() and then its inverse with MatrixBase::inverse().
Example:
Output:
See also
operatorSqrt(), MatrixBase::inverse(), MatrixFunctions Module
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
      return m_eivec * m_eivalues.cwiseInverse().cwiseSqrt().asDiagonal() * m_eivec.adjoint();
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eigenvectorsOk, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivalues, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivec, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
operatorSqrt()
template<typename _MatrixType > EIGEN_DEVICE_FUNC MatrixType Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt () const inline
Computes the positive-definite square root of the matrix.
Returns
the positive-definite square root of the matrix
Precondition
The eigenvalues and eigenvectors of a positive-definite matrix have been computed before.
The square root of a positive-definite matrix is the positive-definite matrix whose square equals . This function uses the eigendecomposition to compute the square root as .
Example:
Output:
See also
operatorInverseSqrt(), MatrixFunctions Module
    {
      eigen_assert(m_isInitialized && "SelfAdjointEigenSolver is not initialized.");
      eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
      return m_eivec * m_eivalues.cwiseSqrt().asDiagonal() * m_eivec.adjoint();
    }
References eigen_assert, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eigenvectorsOk, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivalues, Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivec, and Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized.
Friends And Related Symbol Documentation
internal::direct_selfadjoint_eigenvalues< SelfAdjointEigenSolver, Size, NumTraits< Scalar >::IsComplex >
template<typename _MatrixType > friend struct internal::direct_selfadjoint_eigenvalues< SelfAdjointEigenSolver, Size, NumTraits< Scalar >::IsComplex > friend
Member Data Documentation
m_eigenvectorsOk
template<typename _MatrixType > bool Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eigenvectorsOk protected
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvectors(), Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt(), and Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt().
m_eivalues
template<typename _MatrixType > RealVectorType Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivalues protected
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvalues(), Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt(), and Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt().
m_eivec
template<typename _MatrixType > EigenvectorsType Eigen::SelfAdjointEigenSolver< _MatrixType >::m_eivec protected
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvectors(), Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt(), and Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt().
m_info
template<typename _MatrixType > ComputationInfo Eigen::SelfAdjointEigenSolver< _MatrixType >::m_info protected
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::info().
m_isInitialized
template<typename _MatrixType > bool Eigen::SelfAdjointEigenSolver< _MatrixType >::m_isInitialized protected
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvalues(), Eigen::SelfAdjointEigenSolver< _MatrixType >::eigenvectors(), Eigen::SelfAdjointEigenSolver< _MatrixType >::info(), Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorInverseSqrt(), and Eigen::SelfAdjointEigenSolver< _MatrixType >::operatorSqrt().
m_maxIterations
template<typename _MatrixType > const int Eigen::SelfAdjointEigenSolver< _MatrixType >::m_maxIterations = 30 static
Maximum number of iterations.
The algorithm terminates if it does not converge within m_maxIterations * n iterations, where n denotes the size of the matrix. This value is currently set to 30 (copied from LAPACK).
m_subdiag
template<typename _MatrixType > TridiagonalizationType::SubDiagonalType Eigen::SelfAdjointEigenSolver< _MatrixType >::m_subdiag protected
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h