Prusa Slicer: Slic3r::GUI::PrinterPicker Struct Reference
Slic3r::GUI::PrinterPicker Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Classes
struct Checkbox
Public Member Functions
PrinterPicker (wxWindow *parent, const VendorProfile &vendor, wxString title, size_t max_cols, const AppConfig &appconfig, const ModelFilter &filter)
PrinterPicker (wxWindow *parent, const VendorProfile &vendor, wxString title, size_t max_cols, const AppConfig &appconfig)
void select_all (bool select, bool alternates=false)
void select_one (size_t i, bool select)
bool any_selected () const
std::set< std::string > get_selected_models () const
int get_width () const
const std::vector< int > & get_button_indexes ()
Public Attributes
const std::string vendor_id
std::vector< Checkbox * > cboxes
std::vector< Checkbox * > cboxes_alt
Static Public Attributes
static const std::string PRINTER_PLACEHOLDER = "printer_placeholder.png"
Private Member Functions
void on_checkbox (const Checkbox *cbox, bool checked)
Private Attributes
int width
std::vector< int > m_button_indexes
Detailed Description
Constructor & Destructor Documentation
PrinterPicker() [1/2]
Slic3r::GUI::PrinterPicker::PrinterPicker (wxWindow * parent, const VendorProfile & vendor, wxString title, size_t max_cols, const AppConfig & appconfig, const ModelFilter & filter)
    : wxPanel(parent)
    , vendor_id(vendor.id)
    , width(0)
{
    wxGetApp().UpdateDarkUI(this);
    const auto &models = vendor.models;
    auto *sizer = new wxBoxSizer(wxVERTICAL);
    const auto font_title = GetFont().MakeBold().Scaled(1.3f);
    const auto font_name = GetFont().MakeBold();
    const auto font_alt_nozzle = GetFont().Scaled(0.9f);
    // wxGrid appends widgets by rows, but we need to construct them in columns.
    // These vectors are used to hold the elements so that they can be appended in the right order.
    std::vector<wxStaticText*> titles;
    std::vector<wxStaticBitmap*> bitmaps;
    std::vector<wxPanel*> variants_panels;
    int max_row_width = 0;
    int current_row_width = 0;
    bool is_variants = false;
    const fs::path vendor_dir_path = (fs::path(Slic3r::data_dir()) / "vendor").make_preferred();
    const fs::path cache_dir_path = (fs::path(Slic3r::data_dir()) / "cache").make_preferred();
    const fs::path rsrc_dir_path = (fs::path(resources_dir()) / "profiles").make_preferred();
    for (const auto &model : models) {
        if (! filter(model)) { continue; }
        wxBitmap bitmap;
        int bitmap_width = 0;
        auto load_bitmap = [](const wxString& bitmap_file, wxBitmap& bitmap, int& bitmap_width) {
            bitmap.LoadFile(bitmap_file, wxBITMAP_TYPE_PNG);
            bitmap_width = bitmap.GetWidth();
        };
        bool found = false;
        for (const fs::path& res : { rsrc_dir_path   / vendor.id / model.thumbnail
                                   , vendor_dir_path / vendor.id / model.thumbnail
                                   , cache_dir_path  / vendor.id / model.thumbnail })
        {
            if (!fs::exists(res))
                continue;
            load_bitmap(GUI::from_u8(res.string()), bitmap, bitmap_width);
            found = true;
            break;
        }
        if (!found) {
            BOOST_LOG_TRIVIAL(warning) << boost::format("Can't find bitmap file `%1%` for vendor `%2%`, printer `%3%`, using placeholder icon instead")
                % model.thumbnail
                % vendor.id
                % model.id;
            load_bitmap(Slic3r::var(PRINTER_PLACEHOLDER), bitmap, bitmap_width);
        }
        wxStaticText* title = new wxStaticText(this, wxID_ANY, from_u8(model.name), wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
        title->SetFont(font_name);
        const int wrap_width = std::max((int)MODEL_MIN_WRAP, bitmap_width);
        title->Wrap(wrap_width);
        current_row_width += wrap_width;
        if (titles.size() % max_cols == max_cols - 1) {
            max_row_width = std::max(max_row_width, current_row_width);
            current_row_width = 0;
        }
        titles.push_back(title);
        wxStaticBitmap* bitmap_widget = new wxStaticBitmap(this, wxID_ANY, bitmap);
        bitmaps.push_back(bitmap_widget);
        auto *variants_panel = new wxPanel(this);
        wxGetApp().UpdateDarkUI(variants_panel);
        auto *variants_sizer = new wxBoxSizer(wxVERTICAL);
        variants_panel->SetSizer(variants_sizer);
        const auto model_id = model.id;
        for (size_t i = 0; i < model.variants.size(); i++) {
            const auto &variant = model.variants[i];
            const auto label = model.technology == ptFFF
                ? format_wxstr("%1% %2% %3%", variant.name, _L("mm"), _L("nozzle"))
                : from_u8(model.name);
            if (i == 1) {
                auto *alt_label = new wxStaticText(variants_panel, wxID_ANY, _L("Alternate nozzles:"));
                alt_label->SetFont(font_alt_nozzle);
                variants_sizer->Add(alt_label, 0, wxBOTTOM, 3);
                is_variants = true;
            }
            Checkbox* cbox = new Checkbox(variants_panel, label, model_id, variant.name);
            i == 0 ? cboxes.push_back(cbox) : cboxes_alt.push_back(cbox);
            const bool enabled = appconfig.get_variant(vendor.id, model_id, variant.name);
            cbox->SetValue(enabled);
            variants_sizer->Add(cbox, 0, wxBOTTOM, 3);
            cbox->Bind(wxEVT_CHECKBOX, [this, cbox](wxCommandEvent &event) {
                on_checkbox(cbox, event.IsChecked());
            });
        }
        variants_panels.push_back(variants_panel);
    }
    width = std::max(max_row_width, current_row_width);
    const size_t cols = std::min(max_cols, titles.size());
    auto *printer_grid = new wxFlexGridSizer(cols, 0, 20);
    printer_grid->SetFlexibleDirection(wxVERTICAL | wxHORIZONTAL);
    if (titles.size() > 0) {
        const size_t odd_items = titles.size() % cols;
        for (size_t i = 0; i < titles.size() - odd_items; i += cols) {
            for (size_t j = i; j < i + cols; j++) { printer_grid->Add(bitmaps[j], 0, wxBOTTOM, 20); }
            for (size_t j = i; j < i + cols; j++) { printer_grid->Add(titles[j], 0, wxBOTTOM, 3); }
            for (size_t j = i; j < i + cols; j++) { printer_grid->Add(variants_panels[j]); }
            // Add separator space to multiliners
            if (titles.size() > cols) {
                for (size_t j = i; j < i + cols; j++) { printer_grid->Add(1, 30); }
            }
        }
        if (odd_items > 0) {
            const size_t rem = titles.size() - odd_items;
            for (size_t i = rem; i < titles.size(); i++) { printer_grid->Add(bitmaps[i], 0, wxBOTTOM, 20); }
            for (size_t i = 0; i < cols - odd_items; i++) { printer_grid->AddSpacer(1); }
            for (size_t i = rem; i < titles.size(); i++) { printer_grid->Add(titles[i], 0, wxBOTTOM, 3); }
            for (size_t i = 0; i < cols - odd_items; i++) { printer_grid->AddSpacer(1); }
            for (size_t i = rem; i < titles.size(); i++) { printer_grid->Add(variants_panels[i]); }
        }
    }
    auto *title_sizer = new wxBoxSizer(wxHORIZONTAL);
    if (! title.IsEmpty()) {
        auto *title_widget = new wxStaticText(this, wxID_ANY, title);
        title_widget->SetFont(font_title);
        title_sizer->Add(title_widget);
    }
    title_sizer->AddStretchSpacer();
    if (titles.size() > 1 || is_variants) {
        // It only makes sense to add the All / None buttons if there's multiple printers
        // All Standard button is added when there are more variants for at least one printer
        auto *sel_all_std = new wxButton(this, wxID_ANY, titles.size() > 1 ? _L("All standard") : _L("Standard"));
        auto *sel_all = new wxButton(this, wxID_ANY, _L("All"));
        auto *sel_none = new wxButton(this, wxID_ANY, _L("None"));
        if (is_variants)
            sel_all_std->Bind(wxEVT_BUTTON, [this](const wxCommandEvent& event) { this->select_all(true, false); });
        sel_all->Bind(wxEVT_BUTTON, [this](const wxCommandEvent &event) { this->select_all(true, true); });
        sel_none->Bind(wxEVT_BUTTON, [this](const wxCommandEvent &event) { this->select_all(false); });
        if (is_variants)
            title_sizer->Add(sel_all_std, 0, wxRIGHT, BTN_SPACING);
        title_sizer->Add(sel_all, 0, wxRIGHT, BTN_SPACING);
        title_sizer->Add(sel_none);
        wxGetApp().UpdateDarkUI(sel_all_std);
        wxGetApp().UpdateDarkUI(sel_all);
        wxGetApp().UpdateDarkUI(sel_none);
        // fill button indexes used later for buttons rescaling
        if (is_variants)
            m_button_indexes = { sel_all_std->GetId(), sel_all->GetId(), sel_none->GetId() };
        else {
            sel_all_std->Destroy();
            m_button_indexes = { sel_all->GetId(), sel_none->GetId() };
        }
    }
    sizer->Add(title_sizer, 0, wxEXPAND | wxBOTTOM, BTN_SPACING);
    sizer->Add(printer_grid);
    SetSizer(sizer);
}
References _L, Slic3r::GUI::BTN_SPACING, cboxes, cboxes_alt, Slic3r::data_dir(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::from_u8(), Slic3r::AppConfig::get_variant(), Slic3r::VendorProfile::id, m_button_indexes, Slic3r::GUI::MODEL_MIN_WRAP, Slic3r::VendorProfile::models, on_checkbox(), PRINTER_PLACEHOLDER, Slic3r::ptFFF, Slic3r::resources_dir(), select_all(), Slic3r::var(), width, and wxEVT_BUTTON.
PrinterPicker() [2/2]
Slic3r::GUI::PrinterPicker::PrinterPicker (wxWindow * parent, const VendorProfile & vendor, wxString title, size_t max_cols, const AppConfig & appconfig)
    : PrinterPicker(parent, vendor, std::move(title), max_cols, appconfig, [](const VendorProfile::PrinterModel&) { return true; })
{}
Member Function Documentation
any_selected()
bool Slic3r::GUI::PrinterPicker::any_selected () const
{
    for (const auto &cb : cboxes) {
        if (cb->GetValue()) { return true; }
    }
    for (const auto &cb : cboxes_alt) {
        if (cb->GetValue()) { return true; }
    }
    return false;
}
References cboxes, and cboxes_alt.
get_button_indexes()
const std::vector< int > & Slic3r::GUI::PrinterPicker::get_button_indexes () inline
{ return m_button_indexes; }
References m_button_indexes.
get_selected_models()
std::set< std::string > Slic3r::GUI::PrinterPicker::get_selected_models () const
{
    std::set<std::string> ret_set;
    for (const auto& cb : cboxes)
        if (cb->GetValue())
            ret_set.emplace(cb->model);
    for (const auto& cb : cboxes_alt)
        if (cb->GetValue())
            ret_set.emplace(cb->model);
    return ret_set;
}
References cboxes, and cboxes_alt.
get_width()
int Slic3r::GUI::PrinterPicker::get_width () const inline
{ return width; }
References width.
on_checkbox()
void Slic3r::GUI::PrinterPicker::on_checkbox (const Checkbox * cbox, bool checked) private
{
    PrinterPickerEvent evt(EVT_PRINTER_PICK, GetId(), vendor_id, cbox->model, cbox->variant, checked);
    AddPendingEvent(evt);
}
References Slic3r::GUI::PrinterPicker::Checkbox::model, Slic3r::GUI::PrinterPicker::Checkbox::variant, and vendor_id.
Referenced by PrinterPicker(), select_all(), and select_one().
select_all()
void Slic3r::GUI::PrinterPicker::select_all (bool select, bool alternates = false)
{
    for (const auto &cb : cboxes) {
        if (cb->GetValue() != select) {
            cb->SetValue(select);
            on_checkbox(cb, select);
        }
    }
    if (! select) { alternates = false; }
    for (const auto &cb : cboxes_alt) {
        if (cb->GetValue() != alternates) {
            cb->SetValue(alternates);
            on_checkbox(cb, alternates);
        }
    }
}
References cboxes, cboxes_alt, and on_checkbox().
Referenced by PrinterPicker().
select_one()
void Slic3r::GUI::PrinterPicker::select_one (size_t i, bool select)
{
    if (i < cboxes.size() && cboxes[i]->GetValue() != select) {
        cboxes[i]->SetValue(select);
        on_checkbox(cboxes[i], select);
    }
}
References cboxes, and on_checkbox().
Member Data Documentation
cboxes
std::vector<Checkbox*> Slic3r::GUI::PrinterPicker::cboxes
Referenced by PrinterPicker(), any_selected(), get_selected_models(), select_all(), and select_one().
cboxes_alt
std::vector<Checkbox*> Slic3r::GUI::PrinterPicker::cboxes_alt
Referenced by PrinterPicker(), any_selected(), get_selected_models(), and select_all().
m_button_indexes
std::vector<int> Slic3r::GUI::PrinterPicker::m_button_indexes private
Referenced by PrinterPicker(), and get_button_indexes().
PRINTER_PLACEHOLDER
const std::string Slic3r::GUI::PrinterPicker::PRINTER_PLACEHOLDER = "printer_placeholder.png" static
Referenced by PrinterPicker().
vendor_id
const std::string Slic3r::GUI::PrinterPicker::vendor_id
Referenced by on_checkbox().
width
int Slic3r::GUI::PrinterPicker::width private
Referenced by PrinterPicker(), and get_width().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp