Prusa Slicer: src/eigen/Eigen/src/plugins/BlockMethods.h File Reference
BlockMethods.h File Reference
Classes
struct NColsBlockXpr< N >
struct ConstNColsBlockXpr< N >
struct NRowsBlockXpr< N >
struct ConstNRowsBlockXpr< N >
struct FixedBlockXpr< Rows, Cols >
struct ConstFixedBlockXpr< Rows, Cols >
struct FixedSegmentReturnType< Size >
struct ConstFixedSegmentReturnType< Size >
Typedefs
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ColXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, 1, !IsRowMajor > ConstColXpr
typedef Block< Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowXpr
typedef const Block< const Derived, 1, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowXpr
typedef Block< Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ColsBlockXpr
typedef const Block< const Derived, internal::traits< Derived >::RowsAtCompileTime, Dynamic, !IsRowMajor > ConstColsBlockXpr
typedef Block< Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > RowsBlockXpr
typedef const Block< const Derived, Dynamic, internal::traits< Derived >::ColsAtCompileTime, IsRowMajor > ConstRowsBlockXpr
typedef Block< Derived > BlockXpr
typedef const Block< const Derived > ConstBlockXpr
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock< const Derived > ConstSegmentReturnType
Functions
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block(Index,Index,Index,Index). *‍/.
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const
This is the const version of topRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const
This is the const version of topRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const
This is the const version of topLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const
This is the const version of topLeftCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const
This is the const version of bottomRightCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const
This is the const version of bottomRightCorner<int, int>(Index, Index).
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC BlockXpr bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner(Index, Index).
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner ()
template<int CRows, int CCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const
This is the const version of bottomLeftCorner<int, int>().
template<int CRows, int CCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const
This is the const version of bottomLeftCorner<int, int>(Index, Index).
EIGEN_DEVICE_FUNC RowsBlockXpr topRows (Index n) const
This is the const version of topRows(Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
This is the const version of topRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr bottomRows (Index n) const
This is the const version of bottomRows(Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
This is the const version of bottomRows<int>().
EIGEN_DEVICE_FUNC RowsBlockXpr middleRows (Index startRow, Index n) const
This is the const version of middleRows(Index,Index).
template<int N>
EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
This is the const version of middleRows<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr leftCols (Index n) const
This is the const version of leftCols(Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
This is the const version of leftCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr rightCols (Index n) const
This is the const version of rightCols(Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
This is the const version of rightCols<int>().
EIGEN_DEVICE_FUNC ColsBlockXpr middleCols (Index startCol, Index numCols) const
This is the const version of middleCols(Index,Index).
template<int N>
EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
This is the const version of middleCols<int>().
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol)
template<int NRows, int NCols>
EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const
This is the const version of block<>(Index, Index). *‍/.
template<int NRows, int NCols>
EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int NRows, int NCols>
const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
This is the const version of block<>(Index, Index, Index, Index).
EIGEN_DEVICE_FUNC ColXpr col (Index i) const
This is the const version of col().
EIGEN_DEVICE_FUNC RowXpr row (Index i) const
This is the const version of row(). *‍/.
EIGEN_DEVICE_FUNC SegmentReturnType segment (Index start, Index n) const
This is the const version of segment(Index,Index).
EIGEN_DEVICE_FUNC SegmentReturnType head (Index n) const
This is the const version of head(Index).
EIGEN_DEVICE_FUNC SegmentReturnType tail (Index n) const
This is the const version of tail(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
This is the const version of segment<int>(Index).
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
This is the const version of head<int>().
template<int N>
EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
This is the const version of tail<int>.
Class Documentation
NColsBlockXpr
struct NColsBlockXpr
template<int N>
struct NColsBlockXpr< N >
Class Members
typedef RowsAtCompileTime, N, !IsRowMajor > Type
ConstNColsBlockXpr
struct ConstNColsBlockXpr
template<int N>
struct ConstNColsBlockXpr< N >
Class Members
typedef const RowsAtCompileTime, N, !IsRowMajor > Type
NRowsBlockXpr
struct NRowsBlockXpr
template<int N>
struct NRowsBlockXpr< N >
Class Members
typedef ColsAtCompileTime, IsRowMajor > Type
ConstNRowsBlockXpr
struct ConstNRowsBlockXpr
template<int N>
struct ConstNRowsBlockXpr< N >
Class Members
typedef const ColsAtCompileTime, IsRowMajor > Type
FixedBlockXpr
struct FixedBlockXpr
template<int Rows, int Cols>
struct FixedBlockXpr< Rows, Cols >
Class Members
typedef Block< Derived, Rows, Cols > Type
ConstFixedBlockXpr
struct ConstFixedBlockXpr
template<int Rows, int Cols>
struct ConstFixedBlockXpr< Rows, Cols >
Class Members
typedef Block< const Derived, Rows, Cols > Type
FixedSegmentReturnType
struct FixedSegmentReturnType
template<int Size>
struct FixedSegmentReturnType< Size >
Class Members
typedef VectorBlock< Derived, Size > Type
ConstFixedSegmentReturnType
struct ConstFixedSegmentReturnType
template<int Size>
struct ConstFixedSegmentReturnType< Size >
Class Members
typedef const VectorBlock< const Derived, Size > Type
Typedef Documentation
BlockXpr
typedef Block<Derived> BlockXpr
ColsBlockXpr
typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> ColsBlockXpr
ColXpr
typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> ColXpr
ConstBlockXpr
typedef const Block<const Derived> ConstBlockXpr
ConstColsBlockXpr
typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> ConstColsBlockXpr
ConstColXpr
typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> ConstColXpr
ConstRowsBlockXpr
typedef const Block<const Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> ConstRowsBlockXpr
ConstRowXpr
typedef const Block<const Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> ConstRowXpr
ConstSegmentReturnType
typedef const VectorBlock<const Derived> ConstSegmentReturnType
RowsBlockXpr
typedef Block<Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> RowsBlockXpr
RowXpr
typedef Block<Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> RowXpr
SegmentReturnType
typedef VectorBlock<Derived> SegmentReturnType
Function Documentation
block() [1/5]
template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block in *this.
The template parameters NRows and NCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Output:
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See also
class Block, block(Index,Index,Index,Index)
{
  return typename FixedBlockXpr<NRows,NCols>::Type(derived(), startRow, startCol);
}
block() [2/5]
template<int NRows, int NCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index). *‍/.
{
  return typename ConstFixedBlockXpr<NRows,NCols>::Type(derived(), startRow, startCol);
}
block() [3/5]
template<int NRows, int NCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
an expression of a block in *this.
Template Parameters
NRows number of rows in block as specified at compile-time
NCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal NRows unless NRows is Dynamic, and the same for the number of columns.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename FixedBlockXpr<NRows,NCols>::Type(derived(), startRow, startCol, blockRows, blockCols);
}
block() [4/5]
EIGEN_DEVICE_FUNC const ConstBlockXpr block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
This is the const version of block(Index,Index,Index,Index). *‍/.
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
{
  return BlockXpr(derived(), startRow, startCol, blockRows, blockCols);
}
Referenced by Eigen::internal::block_evaluator< ArgType, BlockRows, BlockCols, InnerPanel, true >::block_evaluator(), Slic3r::GCodeProcessor::TimeMachine::calculate_time(), Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo(), agg::vertex_block_storage< T, BlockShift, BlockPool >::modify_vertex(), igl::Frame_field_deformer::precompute_SMOOTH(), Slic3r::GCodeProcessor::process_G1(), Slic3r::recalculate_trapezoids(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), and igl::slice().
block() [5/5]
template<int NRows, int NCols> const ConstFixedBlockXpr< NRows, NCols >::Type block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block<>(Index, Index, Index, Index).
{
  return typename ConstFixedBlockXpr<NRows,NCols>::Type(derived(), startRow, startCol, blockRows, blockCols);
}
bottomLeftCorner() [1/5]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename FixedBlockXpr<CRows,CCols>::Type(derived(), rows() - CRows, 0);
}
bottomLeftCorner() [2/5]
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
{
  return typename ConstFixedBlockXpr<CRows,CCols>::Type(derived(), rows() - CRows, 0);
}
bottomLeftCorner() [3/5]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
class Block
{
  return typename FixedBlockXpr<CRows,CCols>::Type(derived(), rows() - cRows, 0, cRows, cCols);
}
bottomLeftCorner() [4/5]
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomLeftCorner (Index cRows, Index cCols) inline
This is the const version of bottomLeftCorner(Index, Index).
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return BlockXpr(derived(), rows() - cRows, 0, cRows, cCols);
}
bottomLeftCorner() [5/5]
template<int CRows, int CCols> const ConstFixedBlockXpr< CRows, CCols >::Type bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner<int, int>(Index, Index).
{
  return typename ConstFixedBlockXpr<CRows,CCols>::Type(derived(), rows() - cRows, 0, cRows, cCols);
}
bottomRightCorner() [1/5]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename FixedBlockXpr<CRows,CCols>::Type(derived(), rows() - CRows, cols() - CCols);
}
bottomRightCorner() [2/5]
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
{
  return typename ConstFixedBlockXpr<CRows,CCols>::Type(derived(), rows() - CRows, cols() - CCols);
}
bottomRightCorner() [3/5]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
class Block
{
  return typename FixedBlockXpr<CRows,CCols>::Type(derived(), rows() - cRows, cols() - cCols, cRows, cCols);
}
bottomRightCorner() [4/5]
EIGEN_DEVICE_FUNC const ConstBlockXpr bottomRightCorner (Index cRows, Index cCols) inline
This is the const version of bottomRightCorner(Index, Index).
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return BlockXpr(derived(), rows() - cRows, cols() - cCols, cRows, cCols);
}
bottomRightCorner() [5/5]
template<int CRows, int CCols> const ConstFixedBlockXpr< CRows, CCols >::Type bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner<int, int>(Index, Index).
{
  return typename ConstFixedBlockXpr<CRows,CCols>::Type(derived(), rows() - cRows, cols() - cCols, cRows, cCols);
}
bottomRows() [1/3]
EIGEN_DEVICE_FUNC ConstRowsBlockXpr bottomRows (Index n) inline
This is the const version of bottomRows(Index).
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return RowsBlockXpr(derived(), rows() - n, 0, n, cols());
}
Referenced by Eigen::DenseBase< Derived >::reverseInPlace().
bottomRows() [2/3]
template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type bottomRows (Index n = N) inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename NRowsBlockXpr<N>::Type(derived(), rows() - n, 0, n, cols());
}
bottomRows() [3/3]
template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type bottomRows (Index n = N) const inline
This is the const version of bottomRows<int>().
{
  return typename ConstNRowsBlockXpr<N>::Type(derived(), rows() - n, 0, n, cols());
}
col()
EIGEN_DEVICE_FUNC ConstColXpr col (Index i) inline
This is the const version of col().
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Output:
See also
row(), class Block
{
  return ColXpr(derived(), i);
}
Referenced by Slic3r::GUI::FullCompareDialog::FullCompareDialog(), ImColor::ImColor(), Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::ObjectList::ObjectList(), ImDrawList::AddBezierCubic(), ImDrawList::AddBezierCurve(), ImDrawList::AddBezierQuadratic(), ImDrawList::AddCircle(), ImDrawList::AddCircleFilled(), ImDrawList::AddConvexPolyFilled(), ImDrawList::AddImage(), ImDrawList::AddImageQuad(), ImDrawList::AddImageRounded(), ImDrawList::AddLine(), ImDrawList::AddNgon(), ImDrawList::AddNgonFilled(), ImDrawList::AddPolyline(), ImDrawList::AddQuad(), ImDrawList::AddQuadFilled(), ImDrawList::AddRect(), ImDrawList::AddRectFilled(), ImDrawList::AddText(), ImDrawList::AddText(), ImDrawList::AddTriangle(), ImDrawList::AddTriangleFilled(), Eigen::MatrixBase< Derived >::applyHouseholderOnTheRight(), Eigen::MatrixBase< Derived >::applyOnTheRight(), igl::PlanarizerShapeUp< DerivedV, DerivedF >::assembleQ(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeffByOuterInner(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, Mode, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignOppositeCoeff(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignPacketByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacketByOuterInner(), igl::AtA_cached_precompute(), ImGui::BeginTabBarEx(), ImGui::ButtonEx(), Slic3r::EdgeGrid::Grid::cell_data_range(), Eigen::TriangularBase< Derived >::check_coordinates(), ImGui::CloseButton(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeff(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeff(), Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::coeff(), Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::coeff(), Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::coeff(), Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::coeff(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff(), Eigen::internal::evaluator< Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType > >::coeff(), Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::coeff(), Eigen::internal::evaluator_wrapper_base< XprType >::coeff(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::ForceAlignedAccess< ExpressionType >::coeff(), Eigen::NestByValue< ExpressionType >::coeff(), Eigen::ProductImpl< Lhs, Rhs, Option, Dense >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::coeff(), Eigen::internal::redux_evaluator< _XprType >::coeff(), Eigen::SelfAdjointView< _MatrixType, UpLo >::coeff(), Eigen::TriangularBase< Derived >::coeff(), Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::coeff(), Eigen::internal::visitor_evaluator< XprType >::coeff(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::coeff(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeff(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeff(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeff(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::coeff(), Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::coeff(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeffRef(), Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::coeffRef(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef(), Eigen::internal::evaluator_wrapper_base< XprType >::coeffRef(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::coeffRef(), Eigen::ForceAlignedAccess< ExpressionType >::coeffRef(), Eigen::MapBase< Derived, WriteAccessors >::coeffRef(), Eigen::NestByValue< ExpressionType >::coeffRef(), Eigen::SelfAdjointView< _MatrixType, UpLo >::coeffRef(), Eigen::TriangularBase< Derived >::coeffRef(), Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::coeffRef(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeffRef(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeffRef(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeffRef(), Eigen::SparseMapBase< Derived, WriteAccessors >::coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeffRef(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::internal::coletree(), ImGui::ColorButton(), ImGui::ColorEdit3(), ImGui::ColorEdit4(), ImGui::ColorEditOptionsPopup(), ImGui::ColorPicker3(), ImGui::ColorPicker4(), ImGui::ColorTooltip(), Eigen::SPQR< _MatrixType >::compute(), Eigen::LDLT< _MatrixType, _UpLo >::compute(), Eigen::LLT< _MatrixType, _UpLo >::compute(), Slic3r::GUI::DiffViewCtrl::context_menu(), Eigen::TriangularBase< Derived >::copyCoeff(), CreateSphere(), ImGui::DebugDrawItemRect(), igl::xml::serialization_xml::deserialize(), internal::detect_super_cols(), ImGui::EndColumns(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fill(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fillrand(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find(), internal::find_ordering(), Slic3r::generate_layer_height_texture(), marchsq::_RasterTraits< Slic3r::png::ImageGreyscale >::get(), marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA >::get(), Slic3r::png::Image< PxT >::get(), ImGui::GetColorU32(), ImGui::GetColorU32(), Slic3r::GUI::ArchiveViewModel::GetColumnType(), Slic3r::GUI::ObjectDataViewModel::GetColumnType(), Slic3r::Search::SearchListModel::GetColumnType(), Slic3r::GUI::DiffModel::GetColumnType(), Slic3r::GUI::ArchiveViewModel::GetValue(), Slic3r::GUI::ObjectDataViewModel::GetValue(), Slic3r::GUI::DiffModel::GetValue(), Slic3r::Search::SearchListModel::GetValueByRow(), Slic3r::GUI::image_button_ex(), ImGui::ImageButtonEx(), internal::init_rows_cols(), ImGui::InputTextEx(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insert(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed(), Slic3r::GUI::ObjectDataViewModel::IsEnabled(), Slic3r::GUI::DiffModel::IsEnabled(), Slic3r::GUI::ObjectList::list_manipulation(), Eigen::loadMarketVector(), igl::copyleft::comiso::PoissonSolver< DerivedV, DerivedF >::MixedIntegerSolve(), ImGui::NavUpdate(), Slic3r::Search::SearchDialog::OnMotion(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::keep_diag::operator()(), Eigen::SimplicialCholeskyBase< Derived >::keep_diag::operator()(), Slic3r::AntPathMatrix::operator()(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator()(), Eigen::TriangularBase< Derived >::operator()(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator()(), Eigen::RandomSetter< SparseMatrixType, MapTraits, OuterPacketBits >::operator()(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::operator()(), Eigen::TriangularBase< Derived >::operator()(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator()(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), Eigen::internal::scalar_identity_op< Scalar >::operator()(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet(), Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::packet(), Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::packet(), Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::packet(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet(), Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::packet(), Eigen::internal::evaluator_wrapper_base< XprType >::packet(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::packet(), Eigen::ForceAlignedAccess< ExpressionType >::packet(), Eigen::NestByValue< ExpressionType >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet(), Eigen::internal::redux_evaluator< _XprType >::packet(), Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::packet(), Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::packet_impl(), Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::packet_impl(), ImDrawList::PathFillConvex(), ImDrawList::PathStroke(), ImDrawList::PrimQuadUV(), ImDrawList::PrimRect(), ImDrawList::PrimRectUV(), ImDrawList::PrimVtx(), ImDrawList::PrimWriteVtx(), Eigen::internal::sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true >::processRow(), Slic3r::GUI::anonymous_namespace{HintNotification.cpp}::push_style_color(), Slic3r::GUI::anonymous_namespace{NotificationManager.cpp}::push_style_color(), ImGui::PushStyleColor(), ImGui::PushStyleColor(), Eigen::internal::PutMatrixElt(), Eigen::internal::PutMatrixElt(), Slic3r::sla::RasterGrayscaleAA::read_pixel(), Slic3r::GUI::ImGuiWrapper::render_draw_data(), ImGui::RenderArrow(), ImGui::RenderArrowPointingAt(), ImGui::RenderBullet(), ImFont::RenderChar(), ImGui::RenderCheckMark(), ImGui::RenderColorRectWithAlphaCheckerboard(), ImGui::RenderRectFilledRangeH(), ImGui::RenderRectFilledWithHole(), ImFont::RenderText(), Eigen::DenseBase< Derived >::reverseInPlace(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, RowMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, RowMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::triangular_assignment_loop< Kernel, Mode, UnrollCount, SetOpposite >::run(), Slic3r::GUI::selectable(), ImGui::Selectable(), Slic3r::GUI::ObjectList::set_tooltip_for_item(), Slic3r::GUI::ObjectDataViewModel::SetValue(), Slic3r::GUI::ArchiveViewModel::SetValue(), Slic3r::GUI::ObjectDataViewModel::SetValue(), Slic3r::GUI::DiffModel::SetValue(), Slic3r::GUI::ObjectDataViewModelNode::SetValue(), ShowExampleAppCustomRendering(), ImGui::ShowMetricsWindow(), ImGui::ShowStyleEditor(), igl::sparse_cached_precompute(), ImGui::SplitterBehavior(), Slic3r::Arachne::WallToolPaths::stitchToolPaths(), ImGui::TabItemBackground(), ImGui::TableDrawBorders(), ImGui::TableHeader(), ImGui::TextColored(), ImGui::TextColoredV(), Slic3r::GUI::ObjectDataViewModel::UpdateColumValues(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::updateList(), Eigen::MapBase< Derived, WriteAccessors >::writePacket(), Eigen::ForceAlignedAccess< ExpressionType >::writePacket(), Eigen::NestByValue< ExpressionType >::writePacket(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket(), Eigen::internal::evaluator_wrapper_base< XprType >::writePacket(), and Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket().
head() [1/3]
EIGEN_DEVICE_FUNC ConstSegmentReturnType head (Index n) inline
This is the const version of head(Index).
Returns
a dynamic-size expression of the first coefficients of *this.
\only_for_vectors
Parameters
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return SegmentReturnType(derived(), 0, n);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
Referenced by Slic3r::sla::calculate_pinhead_placement(), Slic3r::sla::DefaultSupportTree::classify(), Eigen::BDCSVD< _MatrixType >::computeSVDofM(), Slic3r::sla::DefaultSupportTree::connect_to_ground(), Slic3r::sla::DefaultSupportTree::connect_to_model_body(), Slic3r::sla::DefaultSupportTree::connect_to_nearpillar(), Eigen::internal::cs_tdfs(), internal::detect_super_cols(), dictNewDict(), igl::opengl2::RotateWidget::down(), internal::find_ordering(), internal::init_scoring(), Eigen::internal::minimum_degree_ordering(), Slic3r::sla::optimize_pinhead_placement(), Slic3r::sla::pinhead_mesh_hit(), igl::pseudonormal_test(), Slic3r::sla::DefaultSupportTree::routing_to_model(), and stl_fix_normal_directions().
head() [2/3]
template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type head (Index n = N) inline
Returns
a fixed-size expression of the first coefficients of *this.
\only_for_vectors
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return typename FixedSegmentReturnType<N>::Type(derived(), 0, n);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
head() [3/3]
template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type head (Index n = N) const inline
This is the const version of head<int>().
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return typename ConstFixedSegmentReturnType<N>::Type(derived(), 0, n);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
leftCols() [1/3]
EIGEN_DEVICE_FUNC ConstColsBlockXpr leftCols (Index n) inline
This is the const version of leftCols(Index).
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return ColsBlockXpr(derived(), 0, 0, rows(), n);
}
Referenced by Eigen::DenseBase< Derived >::reverseInPlace().
leftCols() [2/3]
template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type leftCols (Index n = N) inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename NColsBlockXpr<N>::Type(derived(), 0, 0, rows(), n);
}
leftCols() [3/3]
template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type leftCols (Index n = N) const inline
This is the const version of leftCols<int>().
{
  return typename ConstNColsBlockXpr<N>::Type(derived(), 0, 0, rows(), n);
}
middleCols() [1/3]
template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type middleCols (Index startCol, Index n = N) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename NColsBlockXpr<N>::Type(derived(), 0, startCol, rows(), n);
}
middleCols() [2/3]
template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n = N) const inline
This is the const version of middleCols<int>().
{
  return typename ConstNColsBlockXpr<N>::Type(derived(), 0, startCol, rows(), n);
}
middleCols() [3/3]
EIGEN_DEVICE_FUNC ConstColsBlockXpr middleCols (Index startCol, Index numCols) inline
This is the const version of middleCols(Index,Index).
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return ColsBlockXpr(derived(), 0, startCol, rows(), numCols);
}
middleRows() [1/3]
EIGEN_DEVICE_FUNC ConstRowsBlockXpr middleRows (Index startRow, Index n) inline
This is the const version of middleRows(Index,Index).
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return RowsBlockXpr(derived(), startRow, 0, n, cols());
}
middleRows() [2/3]
template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n = N) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename NRowsBlockXpr<N>::Type(derived(), startRow, 0, n, cols());
}
middleRows() [3/3]
template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n = N) const inline
This is the const version of middleRows<int>().
{
  return typename ConstNRowsBlockXpr<N>::Type(derived(), startRow, 0, n, cols());
}
rightCols() [1/3]
EIGEN_DEVICE_FUNC ConstColsBlockXpr rightCols (Index n) inline
This is the const version of rightCols(Index).
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return ColsBlockXpr(derived(), 0, cols() - n, rows(), n);
}
Referenced by Eigen::DenseBase< Derived >::reverseInPlace().
rightCols() [2/3]
template<int N> EIGEN_DEVICE_FUNC NColsBlockXpr< N >::Type rightCols (Index n = N) inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename NColsBlockXpr<N>::Type(derived(), 0, cols() - n, rows(), n);
}
rightCols() [3/3]
template<int N> EIGEN_DEVICE_FUNC ConstNColsBlockXpr< N >::Type rightCols (Index n = N) const inline
This is the const version of rightCols<int>().
{
  return typename ConstNColsBlockXpr<N>::Type(derived(), 0, cols() - n, rows(), n);
}
row()
EIGEN_DEVICE_FUNC ConstRowXpr row (Index i) inline
This is the const version of row(). *‍/.
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Output:
See also
col(), class Block
{
  return RowXpr(derived(), i);
}
Referenced by Slic3r::Geometry::TransformationSVD::TransformationSVD(), Eigen::MatrixBase< Derived >::applyHouseholderOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::CompleteOrthogonalDecomposition< _MatrixType >::applyZAdjointOnTheLeftInPlace(), igl::PlanarizerShapeUp< DerivedV, DerivedF >::assembleQ(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeffByOuterInner(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, Mode, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignOppositeCoeff(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignPacketByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacketByOuterInner(), igl::AtA_cached_precompute(), igl::cat(), Slic3r::EdgeGrid::Grid::cell_data_range(), Eigen::TriangularBase< Derived >::check_coordinates(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeff(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeff(), Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::coeff(), Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::coeff(), Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::coeff(), Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::coeff(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff(), Eigen::internal::evaluator< Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType > >::coeff(), Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::coeff(), Eigen::internal::evaluator_wrapper_base< XprType >::coeff(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::ForceAlignedAccess< ExpressionType >::coeff(), Eigen::NestByValue< ExpressionType >::coeff(), Eigen::ProductImpl< Lhs, Rhs, Option, Dense >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::coeff(), Eigen::internal::redux_evaluator< _XprType >::coeff(), Eigen::SelfAdjointView< _MatrixType, UpLo >::coeff(), Eigen::TriangularBase< Derived >::coeff(), Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::coeff(), Eigen::internal::visitor_evaluator< XprType >::coeff(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::coeff(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeff(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeff(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeff(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeff(), Eigen::internal::evaluator< DynamicSparseMatrix< _Scalar, _Options, _StorageIndex > >::coeff(), Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::coeff(), Eigen::Diagonal< MatrixType, _DiagIndex >::coeff(), Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::coeff(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeffRef(), Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType >, IndexBased >::coeffRef(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef(), Eigen::internal::evaluator_wrapper_base< XprType >::coeffRef(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::coeffRef(), Eigen::ForceAlignedAccess< ExpressionType >::coeffRef(), Eigen::MapBase< Derived, WriteAccessors >::coeffRef(), Eigen::NestByValue< ExpressionType >::coeffRef(), Eigen::SelfAdjointView< _MatrixType, UpLo >::coeffRef(), Eigen::TriangularBase< Derived >::coeffRef(), Eigen::TriangularViewImpl< _MatrixType, _Mode, Dense >::coeffRef(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeffRef(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeffRef(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeffRef(), Eigen::SparseMapBase< Derived, WriteAccessors >::coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeffRef(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::coeffRef(), Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::coeffRef(), Eigen::Diagonal< MatrixType, _DiagIndex >::coeffRef(), Eigen::Diagonal< MatrixType, _DiagIndex >::coeffRef(), Eigen::internal::coletree(), Eigen::TriangularBase< Derived >::copyCoeff(), igl::xml::serialization_xml::deserialize(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fill(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::fillrand(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find(), internal::find_ordering(), Slic3r::generate_layer_height_texture(), marchsq::_RasterTraits< Slic3r::png::ImageGreyscale >::get(), marchsq::_RasterTraits< Slic3r::sla::RasterGrayscaleAA >::get(), Slic3r::png::Image< PxT >::get(), Slic3r::Search::SearchListModel::GetValueByRow(), internal::init_rows_cols(), internal::init_scoring(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseVector< _Scalar, _Options, _StorageIndex >::insert(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack(), Eigen::DynamicSparseMatrix< _Scalar, _Options, _StorageIndex >::insertBack(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertBackUncompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertCompressed(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >::insertUncompressed(), igl::list_to_matrix(), igl::copyleft::comiso::PoissonSolver< DerivedV, DerivedF >::MixedIntegerSolve(), Eigen::IncompleteLUT< _Scalar, _StorageIndex >::keep_diag::operator()(), Eigen::SimplicialCholeskyBase< Derived >::keep_diag::operator()(), Slic3r::AntPathMatrix::operator()(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator()(), Eigen::TriangularBase< Derived >::operator()(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator()(), Eigen::RandomSetter< SparseMatrixType, MapTraits, OuterPacketBits >::operator()(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::operator()(), Eigen::TriangularBase< Derived >::operator()(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator()(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), Eigen::internal::scalar_identity_op< Scalar >::operator()(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet(), Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::packet(), Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::packet(), Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::packet(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet(), Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::packet(), Eigen::internal::evaluator_wrapper_base< XprType >::packet(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::packet(), Eigen::ForceAlignedAccess< ExpressionType >::packet(), Eigen::NestByValue< ExpressionType >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet(), Eigen::internal::redux_evaluator< _XprType >::packet(), Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::packet(), Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::packet_impl(), Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::packet_impl(), igl::copyleft::comiso::NRosyField::prepareSystemMatrix(), Eigen::internal::PutMatrixElt(), Eigen::internal::PutMatrixElt(), Eigen::internal::QuickSplit(), igl::random_dir_stratified(), Slic3r::sla::RasterGrayscaleAA::read_pixel(), igl::remesh_along_isoline(), Eigen::DenseBase< Derived >::reverseInPlace(), Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::triangular_assignment_loop< Kernel, Mode, UnrollCount, SetOpposite >::run(), ShowDemoWindowTables(), igl::sparse_cached_precompute(), Slic3r::png::write_rgb_or_gray_to_file(), Slic3r::png::write_rgb_or_gray_to_file_scaled(), Eigen::MapBase< Derived, WriteAccessors >::writePacket(), Eigen::ForceAlignedAccess< ExpressionType >::writePacket(), Eigen::NestByValue< ExpressionType >::writePacket(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket(), Eigen::internal::evaluator_wrapper_base< XprType >::writePacket(), and Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket().
segment() [1/3]
EIGEN_DEVICE_FUNC ConstSegmentReturnType segment (Index start, Index n) inline
This is the const version of segment(Index,Index).
Returns
a dynamic-size expression of a segment (i.e. a vector block) in *this.
\only_for_vectors
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, segment(Index)
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return SegmentReturnType(derived(), start, n);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
Referenced by Slic3r::FillAdaptive::add_hook(), Slic3r::chain_extrusion_entities(), Slic3r::Voronoi::Internal::clip_infinite_edge(), Slic3r::connect_brim_lines(), Slic3r::contour_distance(), Slic3r::contour_distance(), Slic3r::contour_distance2(), boost::polygon::voronoi_visual_utils< CT >::discretize(), Slic3r::Arachne::VoronoiUtils::discretizeParabola(), Slic3r::filter_colorized_polygon(), Slic3r::Geometry::fit_curve(), Slic3r::Arachne::fixSelfIntersections(), Slic3r::generate_montonous_regions(), Slic3r::Arachne::SkeletalTrapezoidation::generateLocalMaximaSingleBeads(), boost::polygon::voronoi_visual_utils< CT >::get_point_projection(), Slic3r::FillLightning::lineSegmentPolygonsIntersection(), Slic3r::make_fill_polylines(), Slic3r::mark_boundary_segments_touching_infill(), Slic3r::FirstIntersectionVisitor::operator()(), Slic3r::MinDistanceVisitor::operator()(), pins_check(), Slic3r::FillLightning::polygonCollidesWithLineSegment(), Slic3r::Voronoi::Internal::sample_curved_edge(), and Slic3r::trim_loop().
segment() [2/3]
template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type segment (Index start, Index n = N) inline
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
\only_for_vectors
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return typename FixedSegmentReturnType<N>::Type(derived(), start, n);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
segment() [3/3]
template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n = N) const inline
This is the const version of segment<int>(Index).
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return typename ConstFixedSegmentReturnType<N>::Type(derived(), start, n);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
tail() [1/3]
EIGEN_DEVICE_FUNC ConstSegmentReturnType tail (Index n) inline
This is the const version of tail(Index).
Returns
a dynamic-size expression of the last coefficients of *this.
\only_for_vectors
Parameters
n the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return SegmentReturnType(derived(), this->size() - n, n);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
Referenced by Eigen::CompleteOrthogonalDecomposition< _MatrixType >::applyZAdjointOnTheLeftInPlace(), igl::boundary_conditions(), igl::opengl2::draw_skeleton_vector_graphics(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::DenseBase< Derived >::reverseInPlace(), igl::sample_edges(), stl_fix_normal_directions(), and Slic3r::GUI::ImGuiWrapper::trunc().
tail() [2/3]
template<int N> EIGEN_DEVICE_FUNC FixedSegmentReturnType< N >::Type tail (Index n = N) inline
Returns
a fixed-size expression of the last coefficients of *this.
\only_for_vectors
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
See also
class Block
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return typename FixedSegmentReturnType<N>::Type(derived(), size() - n);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
tail() [3/3]
template<int N> EIGEN_DEVICE_FUNC ConstFixedSegmentReturnType< N >::Type tail (Index n = N) const inline
This is the const version of tail<int>.
{
  EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
  return typename ConstFixedSegmentReturnType<N>::Type(derived(), size() - n);
}
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
topLeftCorner() [1/5]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename FixedBlockXpr<CRows,CCols>::Type(derived(), 0, 0);
}
topLeftCorner() [2/5]
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
{
  return typename ConstFixedBlockXpr<CRows,CCols>::Type(derived(), 0, 0);
}
topLeftCorner() [3/5]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
class Block
{
  return typename FixedBlockXpr<CRows,CCols>::Type(derived(), 0, 0, cRows, cCols);
}
topLeftCorner() [4/5]
EIGEN_DEVICE_FUNC const ConstBlockXpr topLeftCorner (Index cRows, Index cCols) inline
This is the const version of topLeftCorner(Index, Index).
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return BlockXpr(derived(), 0, 0, cRows, cCols);
}
topLeftCorner() [5/5]
template<int CRows, int CCols> const ConstFixedBlockXpr< CRows, CCols >::Type topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner<int, int>(Index, Index).
{
  return typename ConstFixedBlockXpr<CRows,CCols>::Type(derived(), 0, 0, cRows, cCols);
}
topRightCorner() [1/5]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL EIGEN_DEVICE_FUNC FixedBlockXpr< CRows, CCols >::Type topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Output:
class Block, block<int,int>(Index,Index)
{
  return typename FixedBlockXpr<CRows,CCols>::Type(derived(), 0, cols() - CCols);
}
topRightCorner() [2/5]
template<int CRows, int CCols> EIGEN_DEVICE_FUNC const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
{
  return typename ConstFixedBlockXpr<CRows,CCols>::Type(derived(), 0, cols() - CCols);
}
topRightCorner() [3/5]
template<int CRows, int CCols> EIGEN_DOC_BLOCK_ADDONS_NOT_INNER_PANEL FixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Output:
class Block
{
  return typename FixedBlockXpr<CRows,CCols>::Type(derived(), 0, cols() - cCols, cRows, cCols);
}
topRightCorner() [4/5]
EIGEN_DEVICE_FUNC const ConstBlockXpr topRightCorner (Index cRows, Index cCols) inline
This is the const version of topRightCorner(Index, Index).
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return BlockXpr(derived(), 0, cols() - cCols, cRows, cCols);
}
topRightCorner() [5/5]
template<int CRows, int CCols> const ConstFixedBlockXpr< CRows, CCols >::Type topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner<int, int>(Index, Index).
{
  return typename ConstFixedBlockXpr<CRows,CCols>::Type(derived(), 0, cols() - cCols, cRows, cCols);
}
topRows() [1/3]
EIGEN_DEVICE_FUNC ConstRowsBlockXpr topRows (Index n) inline
This is the const version of topRows(Index).
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return RowsBlockXpr(derived(), 0, 0, n, cols());
}
Referenced by Eigen::DenseBase< Derived >::reverseInPlace().
topRows() [2/3]
template<int N> EIGEN_DEVICE_FUNC NRowsBlockXpr< N >::Type topRows (Index n = N) inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Output:
class Block, block(Index,Index,Index,Index)
{
  return typename NRowsBlockXpr<N>::Type(derived(), 0, 0, n, cols());
}
topRows() [3/3]
template<int N> EIGEN_DEVICE_FUNC ConstNRowsBlockXpr< N >::Type topRows (Index n = N) const inline
This is the const version of topRows<int>().
{
  return typename ConstNRowsBlockXpr<N>::Type(derived(), 0, 0, n, cols());
}