Prusa Slicer: Slic3r::GUI::GLCanvas3D Class Reference
Slic3r::GUI::GLCanvas3D Class Reference
#include <src/slic3r/GUI/GLCanvas3D.hpp>
Classes
struct ArrangeSettings
struct ContoursList
struct GizmoHighlighter
class GizmoHighlighterTimer
class Labels
class LayersEditing
struct Mouse
class RenderStats
class RenderTimer
class SequentialPrintClearance
struct SlaCap
class SLAView
class Slope
struct ToolbarHighlighter
class ToolbarHighlighterTimer
class Tooltip
class WipeTowerInfo
Public Types
enum ECursorType : unsigned char { Standard , Cross }
enum class ESLAViewType { Original , Processed }
Public Member Functions
ArrangeSettings get_arrange_settings () const
GLCanvas3D (wxGLCanvas *canvas, Bed3D &bed)
~GLCanvas3D ()
bool is_initialized () const
void set_context (wxGLContext *context)
wxGLCanvas * get_wxglcanvas ()
const wxGLCanvas * get_wxglcanvas () const
bool init ()
void post_event (wxEvent &&event)
std::shared_ptr< SceneRaycasterItem > add_raycaster_for_picking (SceneRaycaster::EType type, int id, const MeshRaycaster &raycaster, const Transform3d &trafo=Transform3d::Identity(), bool use_back_faces=false)
void remove_raycasters_for_picking (SceneRaycaster::EType type, int id)
void remove_raycasters_for_picking (SceneRaycaster::EType type)
std::vector< std::shared_ptr< SceneRaycasterItem > > * get_raycasters_for_picking (SceneRaycaster::EType type)
void set_raycaster_gizmos_on_top (bool value)
void set_as_dirty ()
void requires_check_outside_state ()
unsigned int get_volumes_count () const
const GLVolumeCollection & get_volumes () const
void reset_volumes ()
ModelInstanceEPrintVolumeState check_volumes_outside_state (bool selection_only=true) const
bool check_volumes_outside_state (const Slic3r::BuildVolume &build_volume, ModelInstanceEPrintVolumeState *out_state, bool selection_only=true) const
void init_gcode_viewer ()
void reset_gcode_toolpaths ()
const GCodeViewer::SequentialView & get_gcode_sequential_view () const
void update_gcode_sequential_view_current (unsigned int first, unsigned int last)
void toggle_sla_auxiliaries_visibility (bool visible, const ModelObject *mo=nullptr, int instance_idx=-1)
void toggle_model_objects_visibility (bool visible, const ModelObject *mo=nullptr, int instance_idx=-1, const ModelVolume *mv=nullptr)
void update_instance_printable_state_for_object (size_t obj_idx)
void update_instance_printable_state_for_objects (const std::vector< size_t > &object_idxs)
void set_config (const DynamicPrintConfig *config)
void set_process (BackgroundSlicingProcess *process)
void set_model (Model *model)
const Model * get_model () const
const Selection & get_selection () const
Selection & get_selection ()
const GLGizmosManager & get_gizmos_manager () const
GLGizmosManager & get_gizmos_manager ()
void bed_shape_changed ()
void set_clipping_plane (unsigned int id, const ClippingPlane &plane)
void reset_clipping_planes_cache ()
void set_use_clipping_planes (bool use)
bool get_use_clipping_planes () const
const std::array< ClippingPlane, 2 > & get_clipping_planes () const
void set_use_color_clip_plane (bool use)
void set_color_clip_plane (const Vec3d &cp_normal, double offset)
void set_color_clip_plane_colors (const std::array< ColorRGBA, 2 > &colors)
void refresh_camera_scene_box ()
BoundingBoxf3 volumes_bounding_box () const
BoundingBoxf3 scene_bounding_box () const
bool is_layers_editing_enabled () const
bool is_layers_editing_allowed () const
bool is_search_pressed () const
void reset_layer_height_profile ()
void adaptive_layer_height_profile (float quality_factor)
void smooth_layer_height_profile (const HeightProfileSmoothingParams &smoothing_params)
bool is_reload_delayed () const
void enable_layers_editing (bool enable)
void enable_legend_texture (bool enable)
void enable_picking (bool enable)
void enable_moving (bool enable)
void enable_gizmos (bool enable)
void enable_selection (bool enable)
void enable_main_toolbar (bool enable)
void enable_undoredo_toolbar (bool enable)
void enable_dynamic_background (bool enable)
void enable_labels (bool enable)
void enable_slope (bool enable)
void allow_multisample (bool allow)
void zoom_to_bed ()
void zoom_to_volumes ()
void zoom_to_selection ()
void zoom_to_gcode ()
void select_view (const std::string &direction)
PrinterTechnology current_printer_technology () const
void update_volumes_colors_by_extruder ()
bool is_dragging () const
void render ()
void render_thumbnail (ThumbnailData &thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams &thumbnail_params, Camera::EType camera_type)
void render_thumbnail (ThumbnailData &thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams &thumbnail_params, const GLVolumeCollection &volumes, Camera::EType camera_type)
void select_all ()
void deselect_all ()
void delete_selected ()
void ensure_on_bed (unsigned int object_idx, bool allow_negative_z)
bool is_gcode_legend_enabled () const
GCodeViewer::EViewType get_gcode_view_type () const
const std::vector< double > & get_gcode_layers_zs () const
std::vector< double > get_volumes_print_zs (bool active_only) const
unsigned int get_gcode_options_visibility_flags () const
void set_gcode_options_visibility_from_flags (unsigned int flags)
unsigned int get_toolpath_role_visibility_flags () const
void set_toolpath_role_visibility_flags (unsigned int flags)
void set_toolpath_view_type (GCodeViewer::EViewType type)
void set_volumes_z_range (const std::array< double, 2 > &range)
void set_toolpaths_z_range (const std::array< unsigned int, 2 > &range)
std::vector< CustomGCode::Item > & get_custom_gcode_per_print_z ()
size_t get_gcode_extruders_count ()
std::vector< int > load_object (const ModelObject &model_object, int obj_idx, std::vector< int > instance_idxs)
std::vector< int > load_object (const Model &model, int obj_idx)
void mirror_selection (Axis axis)
void reload_scene (bool refresh_immediately, bool force_full_scene_refresh=false)
void load_gcode_preview (const GCodeProcessorResult &gcode_result, const std::vector< std::string > &str_tool_colors)
void refresh_gcode_preview_render_paths (bool keep_sequential_current_first, bool keep_sequential_current_last)
void set_gcode_view_preview_type (GCodeViewer::EViewType type)
GCodeViewer::EViewType get_gcode_view_preview_type () const
void load_sla_preview ()
void load_preview (const std::vector< std::string > &str_tool_colors, const std::vector< CustomGCode::Item > &color_print_values)
void bind_event_handlers ()
void unbind_event_handlers ()
void on_size (wxSizeEvent &evt)
void on_idle (wxIdleEvent &evt)
void on_char (wxKeyEvent &evt)
void on_key (wxKeyEvent &evt)
void on_mouse_wheel (wxMouseEvent &evt)
void on_timer (wxTimerEvent &evt)
void on_render_timer (wxTimerEvent &evt)
void on_mouse (wxMouseEvent &evt)
void on_paint (wxPaintEvent &evt)
void on_set_focus (wxFocusEvent &evt)
Size get_canvas_size () const
Vec2d get_local_mouse_position () const
void set_popup_menu_position (const Vec2d &position)
const std::optional< Vec2d > & get_popup_menu_position () const
void clear_popup_menu_position ()
void set_tooltip (const std::string &tooltip)
void do_move (const std::string &snapshot_type)
void do_rotate (const std::string &snapshot_type)
void do_scale (const std::string &snapshot_type)
void do_mirror (const std::string &snapshot_type)
void do_reset_skew (const std::string &snapshot_type)
void update_gizmos_on_off_state ()
void reset_all_gizmos ()
void handle_sidebar_focus_event (const std::string &opt_key, bool focus_on)
void handle_layers_data_focus_event (const t_layer_height_range range, const EditorType type)
void update_ui_from_settings ()
int get_move_volume_id () const
int get_first_hover_volume_idx () const
void set_selected_extruder (int extruder)
WipeTowerInfo get_wipe_tower_info () const
Linef3 mouse_ray (const Point &mouse_pos)
bool is_mouse_dragging () const
double get_size_proportional_to_max_bed_size (double factor) const
void set_cursor (ECursorType type)
void msw_rescale ()
void request_extra_frame ()
void schedule_extra_frame (int miliseconds)
float get_main_toolbar_height ()
int get_main_toolbar_item_id (const std::string &name) const
void force_main_toolbar_left_action (int item_id)
void force_main_toolbar_right_action (int item_id)
void update_tooltip_for_settings_item_in_main_toolbar ()
bool has_toolpaths_to_export () const
void export_toolpaths_to_obj (const char *filename) const
void mouse_up_cleanup ()
bool are_labels_shown () const
void show_labels (bool show)
bool is_legend_shown () const
void show_legend (bool show)
bool is_using_slope () const
void use_slope (bool use)
void set_slope_normal_angle (float angle_in_deg)
void highlight_toolbar_item (const std::string &item_name)
void highlight_gizmo (const std::string &gizmo_name)
void reset_sequential_print_clearance ()
void set_sequential_print_clearance_contours (const ContoursList &contours, bool generate_fill)
bool is_sequential_print_clearance_empty () const
bool is_sequential_print_clearance_evaluating () const
void update_sequential_clearance (bool force_contours_generation)
void set_sequential_clearance_as_evaluating ()
const Print * fff_print () const
const SLAPrint * sla_print () const
void reset_old_size ()
bool is_object_sinking (int object_idx) const
void apply_retina_scale (Vec2d &screen_coordinate) const
std::pair< SlicingParameters, const std::vector< double > > get_layers_height_data (int object_id)
void detect_sla_view_type ()
void set_sla_view_type (ESLAViewType type)
void set_sla_view_type (const GLVolume::CompositeID &id, ESLAViewType type)
void enable_sla_view_type_detection ()
Static Public Member Functions
static int64_t timestamp_now ()
Public Attributes
std::optional< Vec2d > m_popup_menu_positon
Private Types
enum class EWarning {
ObjectOutside , ToolpathOutside , SlaSupportsOutside , SomethingNotShown ,
ObjectClashed , GCodeConflict
}
Private Member Functions
bool is_arrange_alignment_enabled () const
void load_arrange_settings ()
bool _is_shown_on_screen () const
bool _init_toolbars ()
bool _init_main_toolbar ()
bool _init_undoredo_toolbar ()
bool _init_view_toolbar ()
bool _init_collapse_toolbar ()
bool _set_current ()
void _resize (unsigned int w, unsigned int h)
BoundingBoxf3 _max_bounding_box (bool include_gizmos, bool include_bed_model) const
void _zoom_to_box (const BoundingBoxf3 &box, double margin_factor=DefaultCameraZoomToBoxMarginFactor)
void _update_camera_zoom (double zoom)
void _refresh_if_shown_on_screen ()
void _picking_pass ()
void _rectangular_selection_picking_pass ()
void _render_background ()
void _render_bed (const Transform3d &view_matrix, const Transform3d &projection_matrix, bool bottom)
void _render_bed_axes ()
void _render_bed_for_picking (const Transform3d &view_matrix, const Transform3d &projection_matrix, bool bottom)
void _render_objects (GLVolumeCollection::ERenderType type)
void _render_gcode ()
void _render_gcode_cog ()
void _render_selection ()
void _render_sequential_clearance ()
void _check_and_update_toolbar_icon_scale ()
void _render_overlays ()
void _render_volumes_for_picking (const Camera &camera) const
void _render_current_gizmo () const
void _render_gizmos_overlay ()
void _render_main_toolbar ()
void _render_undoredo_toolbar ()
void _render_collapse_toolbar () const
void _render_view_toolbar () const
void _render_sla_slices ()
void _render_selection_sidebar_hints ()
bool _render_undo_redo_stack (const bool is_undo, float pos_x)
bool _render_search_list (float pos_x)
bool _render_arrange_menu (float pos_x)
void _render_thumbnail_internal (ThumbnailData &thumbnail_data, const ThumbnailsParams &thumbnail_params, const GLVolumeCollection &volumes, Camera::EType camera_type)
void _render_thumbnail_framebuffer (ThumbnailData &thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams &thumbnail_params, const GLVolumeCollection &volumes, Camera::EType camera_type)
void _render_thumbnail_framebuffer_ext (ThumbnailData &thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams &thumbnail_params, const GLVolumeCollection &volumes, Camera::EType camera_type)
void _render_thumbnail_legacy (ThumbnailData &thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams &thumbnail_params, const GLVolumeCollection &volumes, Camera::EType camera_type)
void _update_volumes_hover_state ()
void _perform_layer_editing_action (wxMouseEvent *evt=nullptr)
Vec3d _mouse_to_3d (const Point &mouse_pos, float *z=nullptr)
Vec3d _mouse_to_bed_3d (const Point &mouse_pos)
void _start_timer ()
void _stop_timer ()
void _load_print_toolpaths (const BuildVolume &build_volume)
void _load_print_object_toolpaths (const PrintObject &print_object, const BuildVolume &build_volume, const std::vector< std::string > &str_tool_colors, const std::vector< CustomGCode::Item > &color_print_values)
void _load_wipe_tower_toolpaths (const BuildVolume &build_volume, const std::vector< std::string > &str_tool_colors)
void _load_sla_shells ()
void _update_sla_shells_outside_state ()
void _set_warning_notification_if_needed (EWarning warning)
void _set_warning_notification (EWarning warning, bool state)
std::pair< bool, const GLVolume * > _is_any_volume_outside () const
void _update_selection_from_hover ()
bool _deactivate_undo_redo_toolbar_items ()
bool _deactivate_search_toolbar_item ()
bool _activate_search_toolbar_item ()
bool _deactivate_collapse_toolbar_items ()
bool _deactivate_arrange_menu ()
float get_overlay_window_width ()
Static Private Member Functions
template<class Self >
static auto & get_arrange_settings_ref (Self *self)
Private Attributes
wxGLCanvas * m_canvas
wxGLContext * m_context
SceneRaycaster m_scene_raycaster
Bed3D & m_bed
bool m_in_render
wxTimer m_timer
LayersEditing m_layers_editing
Mouse m_mouse
GLGizmosManager m_gizmos
GLToolbar m_main_toolbar
GLToolbar m_undoredo_toolbar
std::array< ClippingPlane, 2 > m_clipping_planes
ClippingPlane m_camera_clipping_plane
bool m_use_clipping_planes
std::array< SlaCap, 2 > m_sla_caps
std::string m_sidebar_field
bool m_extra_frame_requested
bool m_event_handlers_bound { false }
GLVolumeCollection m_volumes
GCodeViewer m_gcode_viewer
RenderTimer m_render_timer
Selection m_selection
const DynamicPrintConfig * m_config
Model * m_model
BackgroundSlicingProcess * m_process
bool m_requires_check_outside_state { false }
std::array< unsigned int, 2 > m_old_size { 0, 0 }
bool m_dirty
bool m_initialized
bool m_apply_zoom_to_volumes_filter
bool m_picking_enabled
bool m_moving_enabled
bool m_dynamic_background_enabled
bool m_multisample_allowed
bool m_moving
bool m_tab_down
ECursorType m_cursor_type
GLSelectionRectangle m_rectangle_selection
std::vector< int > m_hover_volume_idxs
bool m_render_sla_auxiliaries
bool m_reload_delayed
KeyAutoRepeatFilter m_shift_kar_filter
KeyAutoRepeatFilter m_ctrl_kar_filter
RenderStats m_render_stats
int m_imgui_undo_redo_hovered_pos { -1 }
int m_mouse_wheel { 0 }
int m_selected_extruder
Labels m_labels
Tooltip m_tooltip
bool m_tooltip_enabled { true }
Slope m_slope
SLAView m_sla_view
bool m_sla_view_type_detection_active { false }
ArrangeSettings m_arrange_settings_fff
ArrangeSettings m_arrange_settings_sla
ArrangeSettings m_arrange_settings_fff_seq_print
SequentialPrintClearance m_sequential_print_clearance
bool m_sequential_print_clearance_first_displacement { true }
struct Slic3r::GUI::GLCanvas3D::ToolbarHighlighter m_toolbar_highlighter
struct Slic3r::GUI::GLCanvas3D::GizmoHighlighter m_gizmo_highlighter
GLModel m_background
Static Private Attributes
static const double DefaultCameraZoomToBoxMarginFactor = 1.25
Detailed Description
Class Documentation
Slic3r::GUI::GLCanvas3D::ArrangeSettings
struct Slic3r::GUI::GLCanvas3D::ArrangeSettings
Class Members
float accuracy = 0.65f
int alignment = 0
float distance = 6.f
float distance_from_bed = 0.f
bool enable_rotation = false
Member Enumeration Documentation
ECursorType
enum Slic3r::GUI::GLCanvas3D::ECursorType : unsigned char
Enumerator
Standard
Cross
    {
        Standard,
        Cross
    };
ESLAViewType
enum class Slic3r::GUI::GLCanvas3D::ESLAViewType strong
Enumerator
Original
Processed
    {
        Original,
        Processed
    };
EWarning
enum class Slic3r::GUI::GLCanvas3D::EWarning strong private
Enumerator
ObjectOutside
ToolpathOutside
SlaSupportsOutside
SomethingNotShown
ObjectClashed
GCodeConflict
{
        ObjectOutside,
        ToolpathOutside,
        SlaSupportsOutside,
        SomethingNotShown,
        ObjectClashed,
        GCodeConflict
    };
Constructor & Destructor Documentation
GLCanvas3D()
Slic3r::GUI::GLCanvas3D::GLCanvas3D (wxGLCanvas * canvas, Bed3D & bed)
    : m_canvas(canvas)
    , m_context(nullptr)
    , m_bed(bed)
#if ENABLE_RETINA_GL
    , m_retina_helper(nullptr)
#endif
    , m_in_render(false)
    , m_main_toolbar(GLToolbar::Normal, "Main")
    , m_undoredo_toolbar(GLToolbar::Normal, "Undo_Redo")
    , m_gizmos(*this)
    , m_use_clipping_planes(false)
    , m_sidebar_field("")
    , m_extra_frame_requested(false)
    , m_config(nullptr)
    , m_process(nullptr)
    , m_model(nullptr)
    , m_dirty(true)
    , m_initialized(false)
    , m_apply_zoom_to_volumes_filter(false)
    , m_picking_enabled(false)
    , m_moving_enabled(false)
    , m_dynamic_background_enabled(false)
    , m_multisample_allowed(false)
    , m_moving(false)
    , m_tab_down(false)
    , m_cursor_type(Standard)
    , m_reload_delayed(false)
    , m_render_sla_auxiliaries(true)
    , m_labels(*this)
    , m_slope(m_volumes)
    , m_sla_view(*this)
{
    if (m_canvas != nullptr) {
        m_timer.SetOwner(m_canvas);
        m_render_timer.SetOwner(m_canvas);
#if ENABLE_RETINA_GL
        m_retina_helper.reset(new RetinaHelper(canvas));
#endif // ENABLE_RETINA_GL
    }
    load_arrange_settings();
    m_selection.set_volumes(&m_volumes.volumes);
}
References load_arrange_settings(), m_canvas, m_render_timer, m_selection, m_timer, m_volumes, Slic3r::GUI::Selection::set_volumes(), and Slic3r::GLVolumeCollection::volumes.
~GLCanvas3D()
Slic3r::GUI::GLCanvas3D::~GLCanvas3D ()
{
    reset_volumes();
}
References reset_volumes().
Member Function Documentation
_activate_search_toolbar_item()
bool Slic3r::GUI::GLCanvas3D::_activate_search_toolbar_item () private
{
    if (!m_main_toolbar.is_item_pressed("search")) {
        m_main_toolbar.force_left_action(m_main_toolbar.get_item_id("search"), *this);
        return true;
    }
    return false;
}
Referenced by on_char().
_check_and_update_toolbar_icon_scale()
void Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale () private
{
    // Don't update a toolbar scale, when we are on a Preview
    if (wxGetApp().plater()->is_preview_shown())
        return;
    const float scale = wxGetApp().toolbar_icon_scale();
    const Size cnv_size = get_canvas_size();
    int size = int(GLToolbar::Default_Icons_Size * scale);
    // Set current size for all top toolbars. It will be used for next calculations
    GLToolbar& collapse_toolbar = wxGetApp().plater()->get_collapse_toolbar();
#if ENABLE_RETINA_GL
    const float sc = m_retina_helper->get_scale_factor() * scale;
    m_main_toolbar.set_scale(sc);
    m_undoredo_toolbar.set_scale(sc);
    collapse_toolbar.set_scale(sc);
    size *= int(m_retina_helper->get_scale_factor());
#else
    m_main_toolbar.set_icons_size(size);
    m_undoredo_toolbar.set_icons_size(size);
    collapse_toolbar.set_icons_size(size);
#endif // ENABLE_RETINA_GL
    const float top_tb_width = m_main_toolbar.get_width() + m_undoredo_toolbar.get_width() + collapse_toolbar.get_width();
    int   items_cnt = m_main_toolbar.get_visible_items_cnt() + m_undoredo_toolbar.get_visible_items_cnt() + collapse_toolbar.get_visible_items_cnt();
    const float noitems_width = top_tb_width - float(size) * items_cnt; // width of separators and borders in top toolbars
    // calculate scale needed for items in all top toolbars
    // the std::max() is there because on some Linux dialects/virtual machines this code is called when the canvas has not been properly initialized yet,
    // leading to negative values for the scale.
    // See: https://github.com/prusa3d/PrusaSlicer/issues/8563
    //      https://github.com/supermerill/SuperSlicer/issues/854
    const float new_h_scale = std::max((cnv_size.get_width() - noitems_width), 1.0f) / (items_cnt * GLToolbar::Default_Icons_Size);
    items_cnt = m_gizmos.get_selectable_icons_cnt() + 3; // +3 means a place for top and view toolbars and separators in gizmos toolbar
    // calculate scale needed for items in the gizmos toolbar
    const float new_v_scale = cnv_size.get_height() / (items_cnt * GLGizmosManager::Default_Icons_Size);
    // set minimum scale as a auto scale for the toolbars
    float new_scale = std::min(new_h_scale, new_v_scale);
#if ENABLE_RETINA_GL
    new_scale /= m_retina_helper->get_scale_factor();
#endif
    if (fabs(new_scale - scale) > 0.01) // scale is changed by 1% and more
        wxGetApp().set_auto_toolbar_icon_scale(new_scale);
}
References Slic3r::GUI::Size::get_height(), Slic3r::GUI::GLToolbar::get_visible_items_cnt(), Slic3r::GUI::GLToolbar::get_width(), Slic3r::GUI::Size::get_width(), scale(), Slic3r::GUI::GLToolbar::set_icons_size(), and Slic3r::GUI::GLToolbar::set_scale().
_deactivate_arrange_menu()
bool Slic3r::GUI::GLCanvas3D::_deactivate_arrange_menu () private
{
    if (m_main_toolbar.is_item_pressed("arrange")) {
        m_main_toolbar.force_right_action(m_main_toolbar.get_item_id("arrange"), *this);
        return true;
    }
    return false;
}
Referenced by on_char(), and on_mouse().
_deactivate_collapse_toolbar_items()
bool Slic3r::GUI::GLCanvas3D::_deactivate_collapse_toolbar_items () private
{
    GLToolbar& collapse_toolbar = wxGetApp().plater()->get_collapse_toolbar();
    if (collapse_toolbar.is_item_pressed("print")) {
        collapse_toolbar.force_left_action(collapse_toolbar.get_item_id("print"), *this);
        return true;
    }
    return false;
}
References Slic3r::GUI::GLToolbar::force_left_action(), Slic3r::GUI::GLToolbar::get_item_id(), and Slic3r::GUI::GLToolbar::is_item_pressed().
_deactivate_search_toolbar_item()
bool Slic3r::GUI::GLCanvas3D::_deactivate_search_toolbar_item () private
{
    if (is_search_pressed()) {
        m_main_toolbar.force_left_action(m_main_toolbar.get_item_id("search"), *this);
        return true;
    }
    return false;
}
Referenced by _init_main_toolbar(), on_char(), and on_mouse().
_deactivate_undo_redo_toolbar_items()
bool Slic3r::GUI::GLCanvas3D::_deactivate_undo_redo_toolbar_items () private
{
    if (m_undoredo_toolbar.is_item_pressed("undo")) {
        m_undoredo_toolbar.force_right_action(m_undoredo_toolbar.get_item_id("undo"), *this);
        return true;
    }
    else if (m_undoredo_toolbar.is_item_pressed("redo")) {
        m_undoredo_toolbar.force_right_action(m_undoredo_toolbar.get_item_id("redo"), *this);
        return true;
    }
    return false;
}
Referenced by _init_undoredo_toolbar(), on_char(), and on_mouse().
_init_collapse_toolbar()
bool Slic3r::GUI::GLCanvas3D::_init_collapse_toolbar () private
{
    return wxGetApp().plater()->init_collapse_toolbar();
}
Referenced by _init_toolbars().
_init_main_toolbar()
bool Slic3r::GUI::GLCanvas3D::_init_main_toolbar () private
{
    if (!m_main_toolbar.is_enabled())
        return true;
    BackgroundTexture::Metadata background_data;
    background_data.filename = "toolbar_background.png";
    background_data.left = 16;
    background_data.top = 16;
    background_data.right = 16;
    background_data.bottom = 16;
    if (!m_main_toolbar.init(background_data)) {
        // unable to init the toolbar texture, disable it
        m_main_toolbar.set_enabled(false);
        return true;
    }
    // init arrow
    if (!m_main_toolbar.init_arrow("toolbar_arrow_2.svg"))
        BOOST_LOG_TRIVIAL(error) << "Main toolbar failed to load arrow texture.";
    // m_gizmos is created at constructor, thus we can init arrow here.
    if (!m_gizmos.init_arrow("toolbar_arrow_2.svg"))
        BOOST_LOG_TRIVIAL(error) << "Gizmos manager failed to load arrow texture.";
//    m_main_toolbar.set_layout_type(GLToolbar::Layout::Vertical);
    m_main_toolbar.set_layout_type(GLToolbar::Layout::Horizontal);
    m_main_toolbar.set_horizontal_orientation(GLToolbar::Layout::HO_Right);
    m_main_toolbar.set_vertical_orientation(GLToolbar::Layout::VO_Top);
    m_main_toolbar.set_border(5.0f);
    m_main_toolbar.set_separator_size(5);
    m_main_toolbar.set_gap_size(4);
    GLToolbarItem::Data item;
    item.name = "add";
    item.icon_filename = "add.svg";
    item.tooltip = _u8L("Add...") + " [" + GUI::shortkey_ctrl_prefix() + "I]";
    item.sprite_id = 0;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_ADD)); };
    if (!m_main_toolbar.add_item(item))
        return false;
    item.name = "delete";
    item.icon_filename = "remove.svg";
    item.tooltip = _u8L("Delete") + " [Del]";
    item.sprite_id = 1;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_DELETE)); };
    item.enabling_callback = []()->bool { return wxGetApp().plater()->can_delete(); };
    if (!m_main_toolbar.add_item(item))
        return false;
    item.name = "deleteall";
    item.icon_filename = "delete_all.svg";
    item.tooltip = _u8L("Delete all") + " [" + GUI::shortkey_ctrl_prefix() + "Del]";
    item.sprite_id = 2;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_DELETE_ALL)); };
    item.enabling_callback = []()->bool { return wxGetApp().plater()->can_delete_all(); };
    if (!m_main_toolbar.add_item(item))
        return false;
    item.name = "arrange";
    item.icon_filename = "arrange.svg";
    item.tooltip = _u8L("Arrange") + " [A]\n" + _u8L("Arrange selection") + " [Shift+A]\n" + _u8L("Click right mouse button to show arrangement options");
    item.sprite_id = 3;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_ARRANGE)); };
    item.enabling_callback = []()->bool { return wxGetApp().plater()->can_arrange(); };
    item.right.toggable = true;
    item.right.render_callback = [this](float left, float right, float, float) {
        if (m_canvas != nullptr)
            _render_arrange_menu(0.5f * (left + right));
    };
    if (!m_main_toolbar.add_item(item))
        return false;
    item.right.toggable = false;
    item.right.render_callback = GLToolbarItem::Default_Render_Callback;
    if (!m_main_toolbar.add_separator())
        return false;
    item.name = "copy";
    item.icon_filename = "copy.svg";
    item.tooltip = _u8L("Copy") + " [" + GUI::shortkey_ctrl_prefix() + "C]";
    item.sprite_id = 4;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_COPY)); };
    item.enabling_callback = []()->bool { return wxGetApp().plater()->can_copy_to_clipboard(); };
    if (!m_main_toolbar.add_item(item))
        return false;
    item.name = "paste";
    item.icon_filename = "paste.svg";
    item.tooltip = _u8L("Paste") + " [" + GUI::shortkey_ctrl_prefix() + "V]";
    item.sprite_id = 5;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_PASTE)); };
    item.enabling_callback = []()->bool { return wxGetApp().plater()->can_paste_from_clipboard(); };
    if (!m_main_toolbar.add_item(item))
        return false;
    if (!m_main_toolbar.add_separator())
        return false;
    item.name = "more";
    item.icon_filename = "instance_add.svg";
    item.tooltip = _u8L("Add instance") + " [+]";
    item.sprite_id = 6;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_MORE)); };
    item.visibility_callback = []()->bool { return wxGetApp().get_mode() != comSimple; };
    item.enabling_callback = []()->bool { return wxGetApp().plater()->can_increase_instances(); };
    if (!m_main_toolbar.add_item(item))
        return false;
    item.name = "fewer";
    item.icon_filename = "instance_remove.svg";
    item.tooltip = _u8L("Remove instance") + " [-]";
    item.sprite_id = 7;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_FEWER)); };
    item.visibility_callback = []()->bool { return wxGetApp().get_mode() != comSimple; };
    item.enabling_callback = []()->bool { return wxGetApp().plater()->can_decrease_instances(); };
    if (!m_main_toolbar.add_item(item))
        return false;
    if (!m_main_toolbar.add_separator())
        return false;
    item.name = "splitobjects";
    item.icon_filename = "split_objects.svg";
    item.tooltip = _u8L("Split to objects");
    item.sprite_id = 8;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_SPLIT_OBJECTS)); };
    item.visibility_callback = GLToolbarItem::Default_Visibility_Callback;
    item.enabling_callback = []()->bool { return wxGetApp().plater()->can_split_to_objects(); };
    if (!m_main_toolbar.add_item(item))
        return false;
    item.name = "splitvolumes";
    item.icon_filename = "split_parts.svg";
    item.tooltip = _u8L("Split to parts");
    item.sprite_id = 9;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_SPLIT_VOLUMES)); };
    item.visibility_callback = []()->bool { return wxGetApp().get_mode() != comSimple; };
    item.enabling_callback = []()->bool { return wxGetApp().plater()->can_split_to_volumes(); };
    if (!m_main_toolbar.add_item(item))
        return false;
    if (!m_main_toolbar.add_separator())
        return false;
    item.name = "settings";
    item.icon_filename = "settings.svg";
    item.tooltip = _u8L("Switch to Settings") + "\n" + "[" + GUI::shortkey_ctrl_prefix() + "2] - " + _u8L("Print Settings Tab")    +
                                                "\n" + "[" + GUI::shortkey_ctrl_prefix() + "3] - " + (current_printer_technology() == ptFFF ? _u8L("Filament Settings Tab") : _u8L("Material Settings Tab") +
                                                "\n" + "[" + GUI::shortkey_ctrl_prefix() + "4] - " + _u8L("Printer Settings Tab")) ;
    item.sprite_id = 10;
    item.enabling_callback    = GLToolbarItem::Default_Enabling_Callback;
    item.visibility_callback  = []() { return wxGetApp().app_config->get_bool("new_settings_layout_mode") ||
                                              wxGetApp().app_config->get_bool("dlg_settings_layout_mode"); };
    item.left.action_callback = []() { wxGetApp().mainframe->select_tab(); };
    if (!m_main_toolbar.add_item(item))
        return false;
    /*
    if (!m_main_toolbar.add_separator())
        return false;
        */
    item.name = "search";
    item.icon_filename = "search_.svg";
    item.tooltip = _u8L("Search") + " [" + GUI::shortkey_ctrl_prefix() + "F]";
    item.sprite_id = 11;
    item.left.toggable = true;
    item.left.render_callback = [this](float left, float right, float, float) {
        if (m_canvas != nullptr) {
            if (!m_canvas->HasFocus())
                m_canvas->SetFocus();
            if (_render_search_list(0.5f * (left + right)))
                _deactivate_search_toolbar_item();
        }
    };
    item.left.action_callback   = GLToolbarItem::Default_Action_Callback;
    item.visibility_callback    = GLToolbarItem::Default_Visibility_Callback;
    item.enabling_callback      = [this]()->bool { return m_gizmos.get_current_type() == GLGizmosManager::Undefined; };
    if (!m_main_toolbar.add_item(item))
        return false;
    if (!m_main_toolbar.add_separator())
        return false;
    item.name = "layersediting";
    item.icon_filename = "layers_white.svg";
    item.tooltip = _u8L("Variable layer height");
    item.sprite_id = 12;
    item.left.action_callback = [this]() { if (m_canvas != nullptr) wxPostEvent(m_canvas, SimpleEvent(EVT_GLTOOLBAR_LAYERSEDITING)); };
    item.visibility_callback = [this]()->bool {
        bool res = current_printer_technology() == ptFFF;
        // turns off if changing printer technology
        if (!res && m_main_toolbar.is_item_visible("layersediting") && m_main_toolbar.is_item_pressed("layersediting"))
            force_main_toolbar_left_action(get_main_toolbar_item_id("layersediting"));
        return res;
    };
    item.enabling_callback      = []()->bool { return wxGetApp().plater()->can_layers_editing(); };
    item.left.render_callback   = GLToolbarItem::Default_Render_Callback;
    if (!m_main_toolbar.add_item(item))
        return false;
    return true;
}
References _deactivate_search_toolbar_item(), _render_arrange_menu(), _render_search_list(), _u8L, Slic3r::GUI::GLToolbarItem::Data::Option::action_callback, Slic3r::GUI::GLToolbar::add_item(), Slic3r::GUI::GLToolbar::add_separator(), Slic3r::GUI::BackgroundTexture::Metadata::bottom, Slic3r::comSimple, current_printer_technology(), Slic3r::GUI::GLToolbarItem::Default_Action_Callback, Slic3r::GUI::GLToolbarItem::Default_Enabling_Callback, Slic3r::GUI::GLToolbarItem::Default_Render_Callback, Slic3r::GUI::GLToolbarItem::Default_Visibility_Callback, Slic3r::GUI::GLToolbarItem::Data::enabling_callback, error, Slic3r::GUI::BackgroundTexture::Metadata::filename, force_main_toolbar_left_action(), Slic3r::GUI::GLGizmosManager::get_current_type(), get_main_toolbar_item_id(), Slic3r::GUI::GLToolbar::Layout::HO_Right, Slic3r::GUI::GLToolbar::Layout::Horizontal, Slic3r::GUI::GLToolbarItem::Data::icon_filename, Slic3r::GUI::GLToolbar::init(), Slic3r::GUI::GLGizmosManager::init_arrow(), Slic3r::GUI::GLToolbar::init_arrow(), Slic3r::GUI::GLToolbar::is_enabled(), Slic3r::GUI::GLToolbar::is_item_pressed(), Slic3r::GUI::GLToolbar::is_item_visible(), Slic3r::GUI::GLToolbarItem::Data::left, Slic3r::GUI::BackgroundTexture::Metadata::left, m_canvas, m_gizmos, m_main_toolbar, Slic3r::GUI::GLToolbarItem::Data::name, Slic3r::ptFFF, Slic3r::GUI::GLToolbarItem::Data::Option::render_callback, Slic3r::GUI::GLToolbarItem::Data::right, Slic3r::GUI::BackgroundTexture::Metadata::right, Slic3r::GUI::GLToolbar::set_border(), Slic3r::GUI::GLToolbar::set_enabled(), Slic3r::GUI::GLToolbar::set_gap_size(), Slic3r::GUI::GLToolbar::set_horizontal_orientation(), Slic3r::GUI::GLToolbar::set_layout_type(), Slic3r::GUI::GLToolbar::set_separator_size(), Slic3r::GUI::GLToolbar::set_vertical_orientation(), Slic3r::GUI::shortkey_ctrl_prefix(), Slic3r::GUI::GLToolbarItem::Data::sprite_id, Slic3r::GUI::GLToolbarItem::Data::Option::toggable, Slic3r::GUI::GLToolbarItem::Data::tooltip, Slic3r::GUI::BackgroundTexture::Metadata::top, Slic3r::GUI::GLGizmosManager::Undefined, Slic3r::GUI::GLToolbarItem::Data::visibility_callback, and Slic3r::GUI::GLToolbar::Layout::VO_Top.
Referenced by _init_toolbars().
_init_toolbars()
bool Slic3r::GUI::GLCanvas3D::_init_toolbars () private
{
    if (!_init_main_toolbar())
        return false;
    if (!_init_undoredo_toolbar())
        return false;
    if (!_init_view_toolbar())
        return false;
    if (!_init_collapse_toolbar())
        return false;
    return true;
}
References _init_collapse_toolbar(), _init_main_toolbar(), _init_undoredo_toolbar(), and _init_view_toolbar().
Referenced by init().
_init_undoredo_toolbar()
bool Slic3r::GUI::GLCanvas3D::_init_undoredo_toolbar () private
{
    if (!m_undoredo_toolbar.is_enabled())
        return true;
    BackgroundTexture::Metadata background_data;
    background_data.filename = "toolbar_background.png";
    background_data.left = 16;
    background_data.top = 16;
    background_data.right = 16;
    background_data.bottom = 16;
    if (!m_undoredo_toolbar.init(background_data)) {
        // unable to init the toolbar texture, disable it
        m_undoredo_toolbar.set_enabled(false);
        return true;
    }
    // init arrow
    if (!m_undoredo_toolbar.init_arrow("toolbar_arrow_2.svg"))
        BOOST_LOG_TRIVIAL(error) << "Undo/Redo toolbar failed to load arrow texture.";
//    m_undoredo_toolbar.set_layout_type(GLToolbar::Layout::Vertical);
    m_undoredo_toolbar.set_layout_type(GLToolbar::Layout::Horizontal);
    m_undoredo_toolbar.set_horizontal_orientation(GLToolbar::Layout::HO_Left);
    m_undoredo_toolbar.set_vertical_orientation(GLToolbar::Layout::VO_Top);
    m_undoredo_toolbar.set_border(5.0f);
    m_undoredo_toolbar.set_separator_size(5);
    m_undoredo_toolbar.set_gap_size(4);
    GLToolbarItem::Data item;
    item.name = "undo";
    item.icon_filename = "undo_toolbar.svg";
    item.tooltip = _u8L("Undo") + " [" + GUI::shortkey_ctrl_prefix() + "Z]\n" + _u8L("Click right mouse button to open/close History");
    item.sprite_id = 0;
    item.left.action_callback = [this]() { post_event(SimpleEvent(EVT_GLCANVAS_UNDO)); };
    item.right.toggable = true;
    item.right.action_callback = [this]() { m_imgui_undo_redo_hovered_pos = -1; };
    item.right.render_callback = [this](float left, float right, float, float) {
        if (m_canvas != nullptr) {
            if (_render_undo_redo_stack(true, 0.5f * (left + right)))
                _deactivate_undo_redo_toolbar_items();
        }
    };
    item.enabling_callback = [this]()->bool {
        bool can_undo = wxGetApp().plater()->can_undo();
        int id = m_undoredo_toolbar.get_item_id("undo");
        std::string curr_additional_tooltip;
        m_undoredo_toolbar.get_additional_tooltip(id, curr_additional_tooltip);
        std::string new_additional_tooltip;
        if (can_undo) {
          std::string action;
            wxGetApp().plater()->undo_redo_topmost_string_getter(true, action);
            new_additional_tooltip = format(_L("Next Undo action: %1%"), action);
        }
        if (new_additional_tooltip != curr_additional_tooltip) {
            m_undoredo_toolbar.set_additional_tooltip(id, new_additional_tooltip);
            set_tooltip("");
        }
        return can_undo;
    };
    if (!m_undoredo_toolbar.add_item(item))
        return false;
    item.name = "redo";
    item.icon_filename = "redo_toolbar.svg";
    item.tooltip = _u8L("Redo") + " [" + GUI::shortkey_ctrl_prefix() + "Y]\n" + _u8L("Click right mouse button to open/close History");
    item.sprite_id = 1;
    item.left.action_callback = [this]() { post_event(SimpleEvent(EVT_GLCANVAS_REDO)); };
    item.right.action_callback = [this]() { m_imgui_undo_redo_hovered_pos = -1; };
    item.right.render_callback = [this](float left, float right, float, float) {
        if (m_canvas != nullptr) {
            if (_render_undo_redo_stack(false, 0.5f * (left + right)))
                _deactivate_undo_redo_toolbar_items();
        }
    };
    item.enabling_callback = [this]()->bool {
        bool can_redo = wxGetApp().plater()->can_redo();
        int id = m_undoredo_toolbar.get_item_id("redo");
        std::string curr_additional_tooltip;
        m_undoredo_toolbar.get_additional_tooltip(id, curr_additional_tooltip);
        std::string new_additional_tooltip;
        if (can_redo) {
          std::string action;
            wxGetApp().plater()->undo_redo_topmost_string_getter(false, action);
            new_additional_tooltip = format(_L("Next Redo action: %1%"), action);
        }
        if (new_additional_tooltip != curr_additional_tooltip) {
            m_undoredo_toolbar.set_additional_tooltip(id, new_additional_tooltip);
            set_tooltip("");
        }
        return can_redo;
    };
    if (!m_undoredo_toolbar.add_item(item))
        return false;
    /*
    if (!m_undoredo_toolbar.add_separator())
        return false;
        */
    return true;
}
References _deactivate_undo_redo_toolbar_items(), _L, _render_undo_redo_stack(), _u8L, Slic3r::GUI::GLToolbarItem::Data::Option::action_callback, Slic3r::GUI::GLToolbar::add_item(), Slic3r::GUI::BackgroundTexture::Metadata::bottom, Slic3r::GUI::GLToolbarItem::Data::enabling_callback, error, Slic3r::GUI::BackgroundTexture::Metadata::filename, Slic3r::GUI::format(), Slic3r::GUI::GLToolbar::get_additional_tooltip(), Slic3r::GUI::GLToolbar::get_item_id(), Slic3r::GUI::GLToolbar::Layout::HO_Left, Slic3r::GUI::GLToolbar::Layout::Horizontal, Slic3r::GUI::GLToolbarItem::Data::icon_filename, Slic3r::GUI::GLToolbar::init(), Slic3r::GUI::GLToolbar::init_arrow(), Slic3r::GUI::GLToolbar::is_enabled(), Slic3r::GUI::GLToolbarItem::Data::left, Slic3r::GUI::BackgroundTexture::Metadata::left, m_canvas, m_imgui_undo_redo_hovered_pos, m_undoredo_toolbar, Slic3r::GUI::GLToolbarItem::Data::name, post_event(), Slic3r::GUI::GLToolbarItem::Data::Option::render_callback, Slic3r::GUI::GLToolbarItem::Data::right, Slic3r::GUI::BackgroundTexture::Metadata::right, Slic3r::GUI::GLToolbar::set_additional_tooltip(), Slic3r::GUI::GLToolbar::set_border(), Slic3r::GUI::GLToolbar::set_enabled(), Slic3r::GUI::GLToolbar::set_gap_size(), Slic3r::GUI::GLToolbar::set_horizontal_orientation(), Slic3r::GUI::GLToolbar::set_layout_type(), Slic3r::GUI::GLToolbar::set_separator_size(), set_tooltip(), Slic3r::GUI::GLToolbar::set_vertical_orientation(), Slic3r::GUI::shortkey_ctrl_prefix(), Slic3r::GUI::GLToolbarItem::Data::sprite_id, Slic3r::GUI::GLToolbarItem::Data::Option::toggable, Slic3r::GUI::GLToolbarItem::Data::tooltip, Slic3r::GUI::BackgroundTexture::Metadata::top, and Slic3r::GUI::GLToolbar::Layout::VO_Top.
Referenced by _init_toolbars().
_init_view_toolbar()
bool Slic3r::GUI::GLCanvas3D::_init_view_toolbar () private
{
    return wxGetApp().plater()->init_view_toolbar();
}
Referenced by _init_toolbars().
_is_any_volume_outside()
std::pair< bool, const GLVolume * > Slic3r::GUI::GLCanvas3D::_is_any_volume_outside () const private
{
    for (const GLVolume* volume : m_volumes.volumes) {
        if (volume != nullptr && volume->is_outside)
            return std::make_pair(true, volume);
    }
    return std::make_pair(false, nullptr);
}
Referenced by reload_scene().
_is_shown_on_screen()
bool Slic3r::GUI::GLCanvas3D::_is_shown_on_screen () const private
{
    return (m_canvas != nullptr) ? m_canvas->IsShownOnScreen() : false;
}
References m_canvas.
Referenced by _refresh_if_shown_on_screen(), and render().
_load_print_object_toolpaths()
void Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths (const PrintObject & print_object, const BuildVolume & build_volume, const std::vector< std::string > & str_tool_colors, const std::vector< CustomGCode::Item > & color_print_values) private
{
    std::vector<ColorRGBA> tool_colors;
    decode_colors(str_tool_colors, tool_colors);
    struct Ctxt
    {
        const PrintInstances        *shifted_copies;
        std::vector<const Layer*>    layers;
        bool                         has_perimeters;
        bool                         has_infill;
        bool                         has_support;
        const std::vector<ColorRGBA>* tool_colors;
        bool                         is_single_material_print;
        int                          extruders_cnt;
        const std::vector<CustomGCode::Item>*   color_print_values;
        static ColorRGBA color_perimeters()           { return ColorRGBA::YELLOW(); }
        static ColorRGBA color_infill()               { return ColorRGBA::REDISH(); }
        static ColorRGBA color_support()              { return ColorRGBA::GREENISH(); }
        static ColorRGBA color_pause_or_custom_code() { return ColorRGBA::GRAY(); }
        // For cloring by a tool, return a parsed color.
        bool                         color_by_tool() const { return tool_colors != nullptr; }
        size_t                       number_tools() const { return color_by_tool() ? tool_colors->size() : 0; }
        const ColorRGBA&             color_tool(size_t tool) const { return (*tool_colors)[tool]; }
        // For coloring by a color_print(M600), return a parsed color.
        bool                         color_by_color_print() const { return color_print_values!=nullptr; }
        const size_t                 color_print_color_idx_by_layer_idx(const size_t layer_idx) const {
            const CustomGCode::Item value{layers[layer_idx]->print_z + EPSILON, CustomGCode::Custom, 0, ""};
            auto it = std::lower_bound(color_print_values->begin(), color_print_values->end(), value);
            return (it - color_print_values->begin()) % number_tools();
        }
        const size_t                 color_print_color_idx_by_layer_idx_and_extruder(const size_t layer_idx, const int extruder) const
        {
            const coordf_t print_z = layers[layer_idx]->print_z;
            auto it = std::find_if(color_print_values->begin(), color_print_values->end(),
                [print_z](const CustomGCode::Item& code)
                { return fabs(code.print_z - print_z) < EPSILON; });
            if (it != color_print_values->end()) {
                CustomGCode::Type type = it->type;
                // pause print or custom Gcode
                if (type == CustomGCode::PausePrint ||
                    (type != CustomGCode::ColorChange && type != CustomGCode::ToolChange))
                    return number_tools()-1; // last color item is a gray color for pause print or custom G-code
                // change tool (extruder)
                if (type == CustomGCode::ToolChange)
                    return get_color_idx_for_tool_change(it, extruder);
                // change color for current extruder
                if (type == CustomGCode::ColorChange) {
                    int color_idx = get_color_idx_for_color_change(it, extruder);
                    if (color_idx >= 0)
                        return color_idx;
                }
            }
            const CustomGCode::Item value{print_z + EPSILON, CustomGCode::Custom, 0, ""};
            it = std::lower_bound(color_print_values->begin(), color_print_values->end(), value);
            while (it != color_print_values->begin()) {
                --it;
                // change color for current extruder
                if (it->type == CustomGCode::ColorChange) {
                    int color_idx = get_color_idx_for_color_change(it, extruder);
                    if (color_idx >= 0)
                        return color_idx;
                }
                // change tool (extruder)
                if (it->type == CustomGCode::ToolChange)
                    return get_color_idx_for_tool_change(it, extruder);
            }
            return std::min<int>(extruders_cnt - 1, std::max<int>(extruder - 1, 0));;
        }
    private:
        int get_m600_color_idx(std::vector<CustomGCode::Item>::const_iterator it) const
        {
            int shift = 0;
            while (it != color_print_values->begin()) {
                --it;
                if (it->type == CustomGCode::ColorChange)
                    shift++;
            }
            return extruders_cnt + shift;
        }
        int get_color_idx_for_tool_change(std::vector<CustomGCode::Item>::const_iterator it, const int extruder) const
        {
            const int current_extruder = it->extruder == 0 ? extruder : it->extruder;
            if (number_tools() == size_t(extruders_cnt + 1)) // there is no one "M600"
                return std::min<int>(extruders_cnt - 1, std::max<int>(current_extruder - 1, 0));
            auto it_n = it;
            while (it_n != color_print_values->begin()) {
                --it_n;
                if (it_n->type == CustomGCode::ColorChange && it_n->extruder == current_extruder)
                    return get_m600_color_idx(it_n);
            }
            return std::min<int>(extruders_cnt - 1, std::max<int>(current_extruder - 1, 0));
        }
        int get_color_idx_for_color_change(std::vector<CustomGCode::Item>::const_iterator it, const int extruder) const
        {
            if (extruders_cnt == 1)
                return get_m600_color_idx(it);
            auto it_n = it;
            bool is_tool_change = false;
            while (it_n != color_print_values->begin()) {
                --it_n;
                if (it_n->type == CustomGCode::ToolChange) {
                    is_tool_change = true;
                    if (it_n->extruder == it->extruder || (it_n->extruder == 0 && it->extruder == extruder))
                        return get_m600_color_idx(it);
                    break;
                }
            }
            if (!is_tool_change && it->extruder == extruder)
                return get_m600_color_idx(it);
            return -1;
        }
    } ctxt;
    ctxt.has_perimeters = print_object.is_step_done(posPerimeters);
    ctxt.has_infill = print_object.is_step_done(posInfill);
    ctxt.has_support = print_object.is_step_done(posSupportMaterial);
    ctxt.tool_colors = tool_colors.empty() ? nullptr : &tool_colors;
    ctxt.color_print_values = color_print_values.empty() ? nullptr : &color_print_values;
    ctxt.is_single_material_print = this->fff_print()->extruders().size()==1;
    ctxt.extruders_cnt = wxGetApp().extruders_edited_cnt();
    ctxt.shifted_copies = &print_object.instances();
    // order layers by print_z
    {
        size_t nlayers = 0;
        if (ctxt.has_perimeters || ctxt.has_infill)
            nlayers = print_object.layers().size();
        if (ctxt.has_support)
            nlayers += print_object.support_layers().size();
        ctxt.layers.reserve(nlayers);
    }
    if (ctxt.has_perimeters || ctxt.has_infill)
        for (const Layer *layer : print_object.layers())
            ctxt.layers.emplace_back(layer);
    if (ctxt.has_support)
        for (const Layer *layer : print_object.support_layers())
            ctxt.layers.emplace_back(layer);
    std::sort(ctxt.layers.begin(), ctxt.layers.end(), [](const Layer *l1, const Layer *l2) { return l1->print_z < l2->print_z; });
    // Maximum size of an allocation block: 32MB / sizeof(float)
    BOOST_LOG_TRIVIAL(debug) << "Loading print object toolpaths in parallel - start" << m_volumes.log_memory_info() << log_memory_info();
    const bool is_selected_separate_extruder = m_selected_extruder > 0 && ctxt.color_by_color_print();
    //FIXME Improve the heuristics for a grain size.
    size_t          grain_size = std::max(ctxt.layers.size() / 16, size_t(1));
    tbb::spin_mutex new_volume_mutex;
    auto            new_volume = [this, &new_volume_mutex](const ColorRGBA& color) {
        // Allocate the volume before locking.
    GLVolume *volume = new GLVolume(color);
    volume->is_extrusion_path = true;
        // to prevent sending data to gpu (in the main thread) while
        // editing the model geometry
        volume->model.disable_render();
        tbb::spin_mutex::scoped_lock lock;
      // Lock by ROII, so if the emplace_back() fails, the lock will be released.
        lock.acquire(new_volume_mutex);
        m_volumes.volumes.emplace_back(volume);
        lock.release();
        return volume;
    };
    const size_t    volumes_cnt_initial = m_volumes.volumes.size();
    // Limit the number of threads as the code below does not scale well due to memory pressure.
    // (most of the time is spent in malloc / free / memmove)
    // Not using all the threads leaves some of the threads to G-code generator.
    tbb::task_arena limited_arena(std::min(tbb::this_task_arena::max_concurrency(), 4));
    limited_arena.execute([&ctxt, grain_size, &new_volume, is_selected_separate_extruder, this]{
    tbb::parallel_for(
        tbb::blocked_range<size_t>(0, ctxt.layers.size(), grain_size),
        [&ctxt, &new_volume, is_selected_separate_extruder, this](const tbb::blocked_range<size_t>& range) {
        GLVolumePtrs    vols;
        std::vector<GLModel::Geometry> geometries;
        auto select_geometry = [&ctxt, &geometries](size_t layer_idx, int extruder, int feature) -> GLModel::Geometry& {
            return geometries[ctxt.color_by_color_print() ?
                ctxt.color_print_color_idx_by_layer_idx_and_extruder(layer_idx, extruder) :
                ctxt.color_by_tool() ?
                std::min<int>(ctxt.number_tools() - 1, std::max<int>(extruder - 1, 0)) :
                feature
            ];
        };
        if (ctxt.color_by_color_print() || ctxt.color_by_tool()) {
            for (size_t i = 0; i < ctxt.number_tools(); ++i) {
                vols.emplace_back(new_volume(ctxt.color_tool(i)));
                geometries.emplace_back(GLModel::Geometry());
            }
        }
        else {
            vols = { new_volume(ctxt.color_perimeters()), new_volume(ctxt.color_infill()), new_volume(ctxt.color_support()) };
            geometries = { GLModel::Geometry(), GLModel::Geometry(), GLModel::Geometry() };
        }
        assert(vols.size() == geometries.size());
        for (GLModel::Geometry& g : geometries) {
            g.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P3N3 };
        }
        for (size_t idx_layer = range.begin(); idx_layer < range.end(); ++ idx_layer) {
            const Layer *layer = ctxt.layers[idx_layer];
            if (is_selected_separate_extruder) {
                bool at_least_one_has_correct_extruder = false;
                for (const LayerRegion* layerm : layer->regions()) {
                    if (layerm->slices().empty())
                        continue;
                    const PrintRegionConfig& cfg = layerm->region().config();
                    if (cfg.perimeter_extruder.value    == m_selected_extruder ||
                        cfg.infill_extruder.value       == m_selected_extruder ||
                        cfg.solid_infill_extruder.value == m_selected_extruder ) {
                        at_least_one_has_correct_extruder = true;
                        break;
                    }
                }
                if (!at_least_one_has_correct_extruder)
                    continue;
            }
            for (size_t i = 0; i < vols.size(); ++i) {
                GLVolume* vol = vols[i];
                if (vol->print_zs.empty() || vol->print_zs.back() != layer->print_z) {
                    vol->print_zs.emplace_back(layer->print_z);
                    vol->offsets.emplace_back(geometries[i].indices_count());
                }
            }
            for (const PrintInstance &instance : *ctxt.shifted_copies) {
                const Point &copy = instance.shift;
                for (const LayerRegion *layerm : layer->regions()) {
                    if (is_selected_separate_extruder) {
                        const PrintRegionConfig& cfg = layerm->region().config();
                        if (cfg.perimeter_extruder.value    != m_selected_extruder ||
                            cfg.infill_extruder.value       != m_selected_extruder ||
                            cfg.solid_infill_extruder.value != m_selected_extruder)
                            continue;
                    }
                    if (ctxt.has_perimeters)
                        _3DScene::extrusionentity_to_verts(layerm->perimeters(), float(layer->print_z), copy,
                            select_geometry(idx_layer, layerm->region().config().perimeter_extruder.value, 0));
                    if (ctxt.has_infill) {
                        for (const ExtrusionEntity *ee : layerm->fills()) {
                            // fill represents infill extrusions of a single island.
                            const auto *fill = dynamic_cast<const ExtrusionEntityCollection*>(ee);
                            if (! fill->entities.empty())
                                _3DScene::extrusionentity_to_verts(*fill, float(layer->print_z), copy,
                                    select_geometry(idx_layer, fill->entities.front()->role().is_solid_infill() ?
                                                    layerm->region().config().solid_infill_extruder :
                                                    layerm->region().config().infill_extruder, 1));
                        }
                    }
                }
                if (ctxt.has_support) {
                    const SupportLayer *support_layer = dynamic_cast<const SupportLayer*>(layer);
                    if (support_layer) {
                        for (const ExtrusionEntity *extrusion_entity : support_layer->support_fills.entities)
                            _3DScene::extrusionentity_to_verts(extrusion_entity, float(layer->print_z), copy,
                                select_geometry(idx_layer, (extrusion_entity->role() == ExtrusionRole::SupportMaterial) ?
                                                support_layer->object()->config().support_material_extruder :
                                                support_layer->object()->config().support_material_interface_extruder, 2));
                    }
                }
            }
            // Ensure that no volume grows over the limits. If the volume is too large, allocate a new one.
          for (size_t i = 0; i < vols.size(); ++i) {
              GLVolume &vol = *vols[i];
                if (geometries[i].vertices_size_bytes() > MAX_VERTEX_BUFFER_SIZE) {
                    vol.model.init_from(std::move(geometries[i]));
                    vols[i] = new_volume(vol.color);
                }
          }
        }
        for (size_t i = 0; i < vols.size(); ++i) {
            if (!geometries[i].is_empty())
                vols[i]->model.init_from(std::move(geometries[i]));
        }
    });
    }); // task arena
    BOOST_LOG_TRIVIAL(debug) << "Loading print object toolpaths in parallel - finalizing results" << m_volumes.log_memory_info() << log_memory_info();
    // Remove empty volumes from the newly added volumes.
    {
        for (auto ptr_it = m_volumes.volumes.begin() + volumes_cnt_initial; ptr_it != m_volumes.volumes.end(); ++ptr_it)
            if ((*ptr_it)->empty()) {
                delete *ptr_it;
                *ptr_it = nullptr;
            }
        m_volumes.volumes.erase(std::remove(m_volumes.volumes.begin() + volumes_cnt_initial, m_volumes.volumes.end(), nullptr), m_volumes.volumes.end());
    }
    for (size_t i = volumes_cnt_initial; i < m_volumes.volumes.size(); ++i) {
        GLVolume* v = m_volumes.volumes[i];
        v->is_outside = !contains(build_volume, v->model);
        // We are done editinig the model, now it can be sent to gpu
        v->model.enable_render();
    }
    BOOST_LOG_TRIVIAL(debug) << "Loading print object toolpaths in parallel - end" << m_volumes.log_memory_info() << log_memory_info();
}
References Slic3r::GLVolume::color, Slic3r::PrintObject::config(), Slic3r::decode_colors(), Slic3r::ExtrusionEntityCollection::entities, EPSILON, Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::GUI::GLModel::init_from(), Slic3r::PrintObject::instances(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_done(), Slic3r::l2(), Slic3r::PrintObject::layers(), Slic3r::log_memory_info(), MAX_VERTEX_BUFFER_SIZE, Slic3r::GLVolume::model, Slic3r::Layer::object(), Slic3r::GLVolume::offsets, Slic3r::posInfill, Slic3r::posPerimeters, Slic3r::posSupportMaterial, Slic3r::CustomGCode::Item::print_z, Slic3r::Layer::print_z, Slic3r::GLVolume::print_zs, Slic3r::PrintRegionConfig, Slic3r::range(), Slic3r::Layer::regions(), Slic3r::SupportLayer::support_fills, Slic3r::PrintObject::support_layers(), and Slic3r::ExtrusionRole::SupportMaterial.
Referenced by load_preview().
_load_print_toolpaths()
void Slic3r::GUI::GLCanvas3D::_load_print_toolpaths (const BuildVolume & build_volume) private
{
    const Print *print = this->fff_print();
    if (print == nullptr)
        return;
    if (! print->is_step_done(psSkirtBrim))
        return;
    if (!print->has_skirt() && !print->has_brim())
        return;
    const ColorRGBA color = ColorRGBA::GREENISH();
    // number of skirt layers
    size_t total_layer_count = 0;
    for (const PrintObject* print_object : print->objects()) {
        total_layer_count = std::max(total_layer_count, print_object->total_layer_count());
    }
    size_t skirt_height = print->has_infinite_skirt() ? total_layer_count : std::min<size_t>(print->config().skirt_height.value, total_layer_count);
    if (skirt_height == 0 && print->has_brim())
        skirt_height = 1;
    // Get first skirt_height layers.
    //FIXME This code is fishy. It may not work for multiple objects with different layering due to variable layer height feature.
    // This is not critical as this is just an initial preview.
    const PrintObject* highest_object = *std::max_element(print->objects().begin(), print->objects().end(), [](auto l, auto r){ return l->layers().size() < r->layers().size(); });
    std::vector<float> print_zs;
    print_zs.reserve(skirt_height * 2);
    for (size_t i = 0; i < std::min(skirt_height, highest_object->layers().size()); ++ i)
        print_zs.emplace_back(float(highest_object->layers()[i]->print_z));
    // Only add skirt for the raft layers.
    for (size_t i = 0; i < std::min(skirt_height, std::min(highest_object->slicing_parameters().raft_layers(), highest_object->support_layers().size())); ++ i)
        print_zs.emplace_back(float(highest_object->support_layers()[i]->print_z));
    sort_remove_duplicates(print_zs);
    skirt_height = std::min(skirt_height, print_zs.size());
    print_zs.erase(print_zs.begin() + skirt_height, print_zs.end());
    GLVolume* volume = m_volumes.new_toolpath_volume(color);
    GLModel::Geometry init_data;
    init_data.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P3N3 };
    for (size_t i = 0; i < skirt_height; ++ i) {
        volume->print_zs.emplace_back(print_zs[i]);
        volume->offsets.emplace_back(init_data.indices_count());
        if (i == 0)
            _3DScene::extrusionentity_to_verts(print->brim(), print_zs[i], Point(0, 0), init_data);
        _3DScene::extrusionentity_to_verts(print->skirt(), print_zs[i], Point(0, 0), init_data);
        // Ensure that no volume grows over the limits. If the volume is too large, allocate a new one.
        if (init_data.vertices_size_bytes() > MAX_VERTEX_BUFFER_SIZE) {
            volume->model.init_from(std::move(init_data));
            GLVolume &vol = *volume;
            volume = m_volumes.new_toolpath_volume(vol.color);
        }
    }
    volume->model.init_from(std::move(init_data));
    volume->is_outside = !contains(build_volume, volume->model);
}
References Slic3r::Print::brim(), Slic3r::GLVolume::color, Slic3r::Print::config(), Slic3r::contains(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::ColorRGBA::GREENISH(), Slic3r::Print::has_brim(), Slic3r::Print::has_infinite_skirt(), Slic3r::Print::has_skirt(), Slic3r::GUI::GLModel::Geometry::indices_count(), Slic3r::Print::is_step_done(), Slic3r::PrintObject::layers(), MAX_VERTEX_BUFFER_SIZE, Slic3r::Print::objects(), Slic3r::psSkirtBrim, Slic3r::SlicingParameters::raft_layers(), Slic3r::Print::skirt(), Slic3r::PrintObject::slicing_parameters(), Slic3r::sort_remove_duplicates(), Slic3r::PrintObject::support_layers(), and Slic3r::GUI::GLModel::Geometry::vertices_size_bytes().
Referenced by load_preview().
_load_sla_shells()
void Slic3r::GUI::GLCanvas3D::_load_sla_shells () private
{
    const SLAPrint* print = this->sla_print();
    if (print->objects().empty())
        // nothing to render, return
        return;
    auto add_volume = [this](const SLAPrintObject &object, int volume_id, const SLAPrintObject::Instance& instance,
        const indexed_triangle_set& mesh, const ColorRGBA& color, bool outside_printer_detection_enabled) {
        m_volumes.volumes.emplace_back(new GLVolume(color));
        GLVolume& v = *m_volumes.volumes.back();
#if ENABLE_SMOOTH_NORMALS
        v.model.init_from(mesh, true);
#else
        v.model.init_from(mesh);
#endif // ENABLE_SMOOTH_NORMALS
        v.shader_outside_printer_detection_enabled = outside_printer_detection_enabled;
        v.composite_id.volume_id = volume_id;
        v.set_instance_offset(unscale(instance.shift.x(), instance.shift.y(), 0.0));
        v.set_instance_rotation({ 0.0, 0.0, (double)instance.rotation });
        v.set_instance_mirror(X, object.is_left_handed() ? -1. : 1.);
        v.set_convex_hull(TriangleMesh{its_convex_hull(mesh)});
    };
    // adds objects' volumes
    for (const SLAPrintObject* obj : print->objects()) {
        unsigned int initial_volumes_count = (unsigned int)m_volumes.volumes.size();
        std::shared_ptr<const indexed_triangle_set> m = obj->get_mesh_to_print();
        if (m && !m->empty()) {
            for (const SLAPrintObject::Instance& instance : obj->instances()) {
                add_volume(*obj, 0, instance, *m, GLVolume::MODEL_COLOR[0], true);
                // Set the extruder_id and volume_id to achieve the same color as in the 3D scene when
                // through the update_volumes_colors_by_extruder() call.
                m_volumes.volumes.back()->extruder_id = obj->model_object()->volumes.front()->extruder_id();
                if (auto &tree_mesh = obj->support_mesh().its; !tree_mesh.empty())
                    add_volume(*obj, -int(slaposSupportTree), instance, tree_mesh, GLVolume::SLA_SUPPORT_COLOR, true);
                if (auto &pad_mesh = obj->pad_mesh().its; !pad_mesh.empty())
                    add_volume(*obj, -int(slaposPad), instance, pad_mesh, GLVolume::SLA_PAD_COLOR, false);
            }
        }
        const double shift_z = obj->get_current_elevation();
        for (unsigned int i = initial_volumes_count; i < m_volumes.volumes.size(); ++ i) {
            // apply shift z
            m_volumes.volumes[i]->set_sla_shift_z(shift_z);
        }
    }
    update_volumes_colors_by_extruder();
}
References Slic3r::GLVolume::composite_id, Slic3r::GUI::GLModel::init_from(), Slic3r::its_convex_hull(), Slic3r::GLVolume::model, Slic3r::SLAPrint::objects(), Slic3r::GLVolume::set_convex_hull(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::slaposPad, Slic3r::slaposSupportTree, Slic3r::unscale(), Slic3r::GLVolume::CompositeID::volume_id, and Slic3r::X.
Referenced by load_sla_preview().
_load_wipe_tower_toolpaths()
void Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths (const BuildVolume & build_volume, const std::vector< std::string > & str_tool_colors) private
{
    const Print *print = this->fff_print();
    if (print == nullptr || print->wipe_tower_data().tool_changes.empty())
        return;
    if (!print->is_step_done(psWipeTower))
        return;
    std::vector<ColorRGBA> tool_colors;
    decode_colors(str_tool_colors, tool_colors);
    struct Ctxt
    {
        const Print                  *print;
        const std::vector<ColorRGBA> *tool_colors;
        Vec2f                         wipe_tower_pos;
        float                         wipe_tower_angle;
        static ColorRGBA color_support() { return ColorRGBA::GREENISH(); }
        // For cloring by a tool, return a parsed color.
        bool                         color_by_tool() const { return tool_colors != nullptr; }
        size_t                       number_tools() const { return this->color_by_tool() ? tool_colors->size() : 0; }
        const ColorRGBA&             color_tool(size_t tool) const { return (*tool_colors)[tool]; }
        int                          volume_idx(int tool, int feature) const {
            return this->color_by_tool() ? std::min<int>(this->number_tools() - 1, std::max<int>(tool, 0)) : feature;
        }
        const std::vector<WipeTower::ToolChangeResult>& tool_change(size_t idx) {
            const auto &tool_changes = print->wipe_tower_data().tool_changes;
            return priming.empty() ?
                ((idx == tool_changes.size()) ? final : tool_changes[idx]) :
                ((idx == 0) ? priming : (idx == tool_changes.size() + 1) ? final : tool_changes[idx - 1]);
        }
        std::vector<WipeTower::ToolChangeResult> priming;
        std::vector<WipeTower::ToolChangeResult> final;
    } ctxt;
    ctxt.print = print;
    ctxt.tool_colors = tool_colors.empty() ? nullptr : &tool_colors;
    if (print->wipe_tower_data().priming && print->config().single_extruder_multi_material_priming)
        for (int i=0; i<(int)print->wipe_tower_data().priming.get()->size(); ++i)
            ctxt.priming.emplace_back(print->wipe_tower_data().priming.get()->at(i));
    if (print->wipe_tower_data().final_purge)
        ctxt.final.emplace_back(*print->wipe_tower_data().final_purge.get());
    ctxt.wipe_tower_angle = ctxt.print->config().wipe_tower_rotation_angle.value/180.f * PI;
    ctxt.wipe_tower_pos = Vec2f(ctxt.print->config().wipe_tower_x.value, ctxt.print->config().wipe_tower_y.value);
    BOOST_LOG_TRIVIAL(debug) << "Loading wipe tower toolpaths in parallel - start" << m_volumes.log_memory_info() << log_memory_info();
    //FIXME Improve the heuristics for a grain size.
    size_t          n_items = print->wipe_tower_data().tool_changes.size() + (ctxt.priming.empty() ? 0 : 1);
    size_t          grain_size = std::max(n_items / 128, size_t(1));
    tbb::spin_mutex new_volume_mutex;
    auto            new_volume = [this, &new_volume_mutex](const ColorRGBA& color) {
        auto *volume = new GLVolume(color);
    volume->is_extrusion_path = true;
        // to prevent sending data to gpu (in the main thread) while
        // editing the model geometry
        volume->model.disable_render();
        tbb::spin_mutex::scoped_lock lock;
        lock.acquire(new_volume_mutex);
        m_volumes.volumes.emplace_back(volume);
        lock.release();
        return volume;
    };
    const size_t   volumes_cnt_initial = m_volumes.volumes.size();
    std::vector<GLVolumeCollection> volumes_per_thread(n_items);
    tbb::parallel_for(
        tbb::blocked_range<size_t>(0, n_items, grain_size),
        [&ctxt, &new_volume](const tbb::blocked_range<size_t>& range) {
        // Bounding box of this slab of a wipe tower.
        GLVolumePtrs vols;
        std::vector<GLModel::Geometry> geometries;
        if (ctxt.color_by_tool()) {
            for (size_t i = 0; i < ctxt.number_tools(); ++i) {
                vols.emplace_back(new_volume(ctxt.color_tool(i)));
                geometries.emplace_back(GLModel::Geometry());
            }
        }
        else {
            vols = { new_volume(ctxt.color_support()) };
            geometries = { GLModel::Geometry() };
        }
        assert(vols.size() == geometries.size());
        for (GLModel::Geometry& g : geometries) {
            g.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P3N3 };
        }
        for (size_t idx_layer = range.begin(); idx_layer < range.end(); ++idx_layer) {
            const std::vector<WipeTower::ToolChangeResult> &layer = ctxt.tool_change(idx_layer);
            for (size_t i = 0; i < vols.size(); ++i) {
                GLVolume &vol = *vols[i];
                if (vol.print_zs.empty() || vol.print_zs.back() != layer.front().print_z) {
                    vol.print_zs.emplace_back(layer.front().print_z);
                    vol.offsets.emplace_back(geometries[i].indices_count());
                }
            }
            for (const WipeTower::ToolChangeResult &extrusions : layer) {
                for (size_t i = 1; i < extrusions.extrusions.size();) {
                    const WipeTower::Extrusion &e = extrusions.extrusions[i];
                    if (e.width == 0.) {
                        ++i;
                        continue;
                    }
                    size_t j = i + 1;
                    if (ctxt.color_by_tool())
                        for (; j < extrusions.extrusions.size() && extrusions.extrusions[j].tool == e.tool && extrusions.extrusions[j].width > 0.f; ++j);
                    else
                        for (; j < extrusions.extrusions.size() && extrusions.extrusions[j].width > 0.f; ++j);
                    size_t              n_lines = j - i;
                    Lines               lines;
                    std::vector<double> widths;
                    std::vector<double> heights;
                    lines.reserve(n_lines);
                    widths.reserve(n_lines);
                    heights.assign(n_lines, extrusions.layer_height);
                    WipeTower::Extrusion e_prev = extrusions.extrusions[i-1];
                    if (!extrusions.priming) { // wipe tower extrusions describe the wipe tower at the origin with no rotation
                        e_prev.pos = Eigen::Rotation2Df(ctxt.wipe_tower_angle) * e_prev.pos;
                        e_prev.pos += ctxt.wipe_tower_pos;
                    }
                    for (; i < j; ++i) {
                        WipeTower::Extrusion e = extrusions.extrusions[i];
                        assert(e.width > 0.f);
                        if (!extrusions.priming) {
                            e.pos = Eigen::Rotation2Df(ctxt.wipe_tower_angle) * e.pos;
                            e.pos += ctxt.wipe_tower_pos;
                        }
                        lines.emplace_back(Point::new_scale(e_prev.pos.x(), e_prev.pos.y()), Point::new_scale(e.pos.x(), e.pos.y()));
                        widths.emplace_back(e.width);
                        e_prev = e;
                    }
                    _3DScene::thick_lines_to_verts(lines, widths, heights, lines.front().a == lines.back().b, extrusions.print_z,
                        geometries[ctxt.volume_idx(e.tool, 0)]);
                }
            }
        }
        for (size_t i = 0; i < vols.size(); ++i) {
            GLVolume &vol = *vols[i];
            if (geometries[i].vertices_size_bytes() > MAX_VERTEX_BUFFER_SIZE) {
                vol.model.init_from(std::move(geometries[i]));
                vols[i] = new_volume(vol.color);
            }
        }
        for (size_t i = 0; i < vols.size(); ++i) {
            if (!geometries[i].is_empty())
                vols[i]->model.init_from(std::move(geometries[i]));
        }
        });
    BOOST_LOG_TRIVIAL(debug) << "Loading wipe tower toolpaths in parallel - finalizing results" << m_volumes.log_memory_info() << log_memory_info();
    // Remove empty volumes from the newly added volumes.
    {
        for (auto ptr_it = m_volumes.volumes.begin() + volumes_cnt_initial; ptr_it != m_volumes.volumes.end(); ++ptr_it)
            if ((*ptr_it)->empty()) {
                delete *ptr_it;
                *ptr_it = nullptr;
            }
        m_volumes.volumes.erase(std::remove(m_volumes.volumes.begin() + volumes_cnt_initial, m_volumes.volumes.end(), nullptr), m_volumes.volumes.end());
    }
    for (size_t i = volumes_cnt_initial; i < m_volumes.volumes.size(); ++i) {
        GLVolume* v = m_volumes.volumes[i];
        v->is_outside = !contains(build_volume, v->model);
        // We are done editinig the model, now it can be sent to gpu
        v->model.enable_render();
    }
    BOOST_LOG_TRIVIAL(debug) << "Loading wipe tower toolpaths in parallel - end" << m_volumes.log_memory_info() << log_memory_info();
}
References Slic3r::GLVolume::color, Slic3r::Print::config(), Slic3r::decode_colors(), Slic3r::Print::empty(), Slic3r::WipeTowerData::final_purge, Slic3r::GUI::GLModel::init_from(), Slic3r::Print::is_step_done(), Slic3r::log_memory_info(), MAX_VERTEX_BUFFER_SIZE, Slic3r::GLVolume::model, Slic3r::GLVolume::offsets, PI, Slic3r::WipeTower::Extrusion::pos, Slic3r::WipeTowerData::priming, Slic3r::GLVolume::print_zs, Slic3r::psWipeTower, Slic3r::range(), Slic3r::WipeTower::Extrusion::tool, Slic3r::WipeTowerData::tool_changes, Slic3r::WipeTower::Extrusion::width, and Slic3r::Print::wipe_tower_data().
Referenced by load_preview().
_max_bounding_box()
BoundingBoxf3 Slic3r::GUI::GLCanvas3D::_max_bounding_box (bool include_gizmos, bool include_bed_model) const private
{
    BoundingBoxf3 bb = volumes_bounding_box();
    // The following is a workaround for gizmos not being taken in account when calculating the tight camera frustrum
    // A better solution would ask the gizmo manager for the bounding box of the current active gizmo, if any
    if (include_gizmos && m_gizmos.is_running()) {
        const BoundingBoxf3 sel_bb = m_selection.get_bounding_box();
        const Vec3d sel_bb_center = sel_bb.center();
        const Vec3d extend_by = sel_bb.max_size() * Vec3d::Ones();
        bb.merge(BoundingBoxf3(sel_bb_center - extend_by, sel_bb_center + extend_by));
    }
    const BoundingBoxf3 bed_bb = include_bed_model ? m_bed.extended_bounding_box() : m_bed.build_volume().bounding_volume();
    bb.merge(bed_bb);
    if (!m_main_toolbar.is_enabled())
        bb.merge(m_gcode_viewer.get_max_bounding_box());
    // clamp max bb size with respect to bed bb size
    if (!m_picking_enabled) {
        static const double max_scale_factor = 2.0;
        const Vec3d bb_size = bb.size();
        const Vec3d bed_bb_size = m_bed.build_volume().bounding_volume().size();
        if ((bed_bb_size.x() > 0.0 && bb_size.x() > max_scale_factor * bed_bb_size.x()) ||
            (bed_bb_size.y() > 0.0 && bb_size.y() > max_scale_factor * bed_bb_size.y()) ||
            (bed_bb_size.z() > 0.0 && bb_size.z() > max_scale_factor * bed_bb_size.z())) {
            const Vec3d bed_bb_center = bed_bb.center();
            const Vec3d extend_by = max_scale_factor * bed_bb_size;
            bb = BoundingBoxf3(bed_bb_center - extend_by, bed_bb_center + extend_by);
        }
    }
    return bb;
}
References Slic3r::BuildVolume::bounding_volume(), Slic3r::GUI::Bed3D::build_volume(), Slic3r::BoundingBox3Base< PointType >::center(), Slic3r::GUI::Bed3D::extended_bounding_box(), Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::GCodeViewer::get_max_bounding_box(), Slic3r::GUI::GLToolbar::is_enabled(), Slic3r::GUI::GLGizmosManager::is_running(), m_bed, m_gcode_viewer, m_gizmos, m_main_toolbar, m_picking_enabled, m_selection, Slic3r::BoundingBox3Base< PointType >::max_size(), Slic3r::BoundingBox3Base< PointType >::merge(), Slic3r::BoundingBox3Base< PointType >::size(), and volumes_bounding_box().
Referenced by render().
_mouse_to_3d()
Vec3d Slic3r::GUI::GLCanvas3D::_mouse_to_3d (const Point & mouse_pos, float * z = nullptr) private
{
    if (m_canvas == nullptr)
        return Vec3d(DBL_MAX, DBL_MAX, DBL_MAX);
    if (z == nullptr) {
        const SceneRaycaster::HitResult hit = m_scene_raycaster.hit(mouse_pos.cast<double>(), wxGetApp().plater()->get_camera(), nullptr);
        return hit.is_valid() ? hit.position.cast<double>() : _mouse_to_bed_3d(mouse_pos);
    }
    else {
        const Camera& camera = wxGetApp().plater()->get_camera();
        const Vec4i viewport(camera.get_viewport().data());
        Vec3d out;
        igl::unproject(Vec3d(mouse_pos.x(), viewport[3] - mouse_pos.y(), *z), camera.get_view_matrix().matrix(), camera.get_projection_matrix().matrix(), viewport, out);
        return out;
    }
}
References Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), Slic3r::GUI::SceneRaycaster::HitResult::is_valid(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::SceneRaycaster::HitResult::position, and igl::unproject().
Referenced by mouse_ray(), on_mouse(), on_mouse_wheel(), and render().
_mouse_to_bed_3d()
Vec3d Slic3r::GUI::GLCanvas3D::_mouse_to_bed_3d (const Point & mouse_pos) private
{
    const Linef3 ray = mouse_ray(mouse_pos);
    return (std::abs(ray.unit_vector().z()) < EPSILON) ? ray.a : ray.intersect_plane(0.0);
}
References Slic3r::Linef3::a, EPSILON, Slic3r::Linef3::intersect_plane(), and Slic3r::Linef3::unit_vector().
_perform_layer_editing_action()
void Slic3r::GUI::GLCanvas3D::_perform_layer_editing_action (wxMouseEvent * evt = nullptr) private
{
    int object_idx_selected = m_layers_editing.last_object_id;
    if (object_idx_selected == -1)
        return;
    // A volume is selected. Test, whether hovering over a layer thickness bar.
    if (evt != nullptr) {
        const Rect& rect = LayersEditing::get_bar_rect_screen(*this);
        float b = rect.get_bottom();
        m_layers_editing.last_z = m_layers_editing.object_max_z() * (b - evt->GetY() - 1.0f) / (b - rect.get_top());
        m_layers_editing.last_action =
            evt->ShiftDown() ? (evt->RightIsDown() ? LAYER_HEIGHT_EDIT_ACTION_SMOOTH : LAYER_HEIGHT_EDIT_ACTION_REDUCE) :
                               (evt->RightIsDown() ? LAYER_HEIGHT_EDIT_ACTION_INCREASE : LAYER_HEIGHT_EDIT_ACTION_DECREASE);
    }
    if (m_layers_editing.state != LayersEditing::Paused) {
        m_layers_editing.adjust_layer_height_profile();
        _refresh_if_shown_on_screen();
    }
    // Automatic action on mouse down with the same coordinate.
    _start_timer();
}
References Slic3r::GUI::Rect::get_bottom(), Slic3r::GUI::Rect::get_top(), Slic3r::LAYER_HEIGHT_EDIT_ACTION_DECREASE, Slic3r::LAYER_HEIGHT_EDIT_ACTION_INCREASE, Slic3r::LAYER_HEIGHT_EDIT_ACTION_REDUCE, and Slic3r::LAYER_HEIGHT_EDIT_ACTION_SMOOTH.
Referenced by on_mouse(), and on_timer().
_picking_pass()
void Slic3r::GUI::GLCanvas3D::_picking_pass () private
{
    if (!m_picking_enabled || m_mouse.dragging || m_mouse.position == Vec2d(DBL_MAX, DBL_MAX) || m_gizmos.is_dragging()) {
#if ENABLE_RAYCAST_PICKING_DEBUG
        ImGuiWrapper& imgui = *wxGetApp().imgui();
        imgui.begin(std::string("Hit result"), ImGuiWindowFlags_AlwaysAutoResize);
        imgui.text("Picking disabled");
        imgui.end();
#endif // ENABLE_RAYCAST_PICKING_DEBUG
        return;
    }
    m_hover_volume_idxs.clear();
    const ClippingPlane clipping_plane = m_gizmos.get_clipping_plane().inverted_normal();
    const SceneRaycaster::HitResult hit = m_scene_raycaster.hit(m_mouse.position, wxGetApp().plater()->get_camera(), &clipping_plane);
    if (hit.is_valid()) {
        switch (hit.type)
        {
        case SceneRaycaster::EType::Volume:
        {
            if (0 <= hit.raycaster_id && hit.raycaster_id < (int)m_volumes.volumes.size()) {
                const GLVolume* volume = m_volumes.volumes[hit.raycaster_id];
                if (volume->is_active && !volume->disabled && (volume->composite_id.volume_id >= 0 || m_render_sla_auxiliaries)) {
                    // do not add the volume id if any gizmo is active and CTRL is pressed
                    if (m_gizmos.get_current_type() == GLGizmosManager::EType::Undefined || !wxGetKeyState(WXK_CONTROL))
                        m_hover_volume_idxs.emplace_back(hit.raycaster_id);
                    m_gizmos.set_hover_id(-1);
                }
            }
            else
                assert(false);
            break;
        }
        case SceneRaycaster::EType::Gizmo:
        {
            const Size& cnv_size = get_canvas_size();
            const bool inside = 0 <= m_mouse.position.x() && m_mouse.position.x() < cnv_size.get_width() &&
                0 <= m_mouse.position.y() && m_mouse.position.y() < cnv_size.get_height();
            m_gizmos.set_hover_id(inside ? hit.raycaster_id : -1);
            break;
        }
        case SceneRaycaster::EType::Bed:
        {
            m_gizmos.set_hover_id(-1);
            break;
        }
        default:
        {
            assert(false);
            break;
        }
        }
    }
    else
        m_gizmos.set_hover_id(-1);
    _update_volumes_hover_state();
#if ENABLE_RAYCAST_PICKING_DEBUG
    ImGuiWrapper& imgui = *wxGetApp().imgui();
    imgui.begin(std::string("Hit result"), ImGuiWindowFlags_AlwaysAutoResize);
    std::string object_type = "None";
    switch (hit.type)
    {
    case SceneRaycaster::EType::Bed:   { object_type = "Bed"; break; }
    case SceneRaycaster::EType::Gizmo: { object_type = "Gizmo element"; break; }
    case SceneRaycaster::EType::Volume:
    {
        if (m_volumes.volumes[hit.raycaster_id]->is_wipe_tower)
            object_type = "Volume (Wipe tower)";
        else if (m_volumes.volumes[hit.raycaster_id]->volume_idx() == -int(slaposPad))
            object_type = "Volume (SLA pad)";
        else if (m_volumes.volumes[hit.raycaster_id]->volume_idx() == -int(slaposSupportTree))
            object_type = "Volume (SLA supports)";
        else if (m_volumes.volumes[hit.raycaster_id]->is_modifier)
            object_type = "Volume (Modifier)";
        else
            object_type = "Volume (Part)";
        break;
    }
    default: { break; }
    }
    auto add_strings_row_to_table = [&imgui](const std::string& col_1, const ImVec4& col_1_color, const std::string& col_2, const ImVec4& col_2_color,
        const std::string& col_3 = "", const ImVec4& col_3_color = ImGui::GetStyleColorVec4(ImGuiCol_Text)) {
        ImGui::TableNextRow();
        ImGui::TableSetColumnIndex(0);
        imgui.text_colored(col_1_color, col_1.c_str());
        ImGui::TableSetColumnIndex(1);
        imgui.text_colored(col_2_color, col_2.c_str());
        if (!col_3.empty()) {
            ImGui::TableSetColumnIndex(2);
            imgui.text_colored(col_3_color, col_3.c_str());
        }
    };
    char buf[1024];
    if (hit.type != SceneRaycaster::EType::None) {
        if (ImGui::BeginTable("Hit", 2)) {
            add_strings_row_to_table("Object ID", ImGuiWrapper::COL_ORANGE_LIGHT, std::to_string(hit.raycaster_id), ImGui::GetStyleColorVec4(ImGuiCol_Text));
            add_strings_row_to_table("Type", ImGuiWrapper::COL_ORANGE_LIGHT, object_type, ImGui::GetStyleColorVec4(ImGuiCol_Text));
            sprintf(buf, "%.3f, %.3f, %.3f", hit.position.x(), hit.position.y(), hit.position.z());
            add_strings_row_to_table("Position", ImGuiWrapper::COL_ORANGE_LIGHT, std::string(buf), ImGui::GetStyleColorVec4(ImGuiCol_Text));
            sprintf(buf, "%.3f, %.3f, %.3f", hit.normal.x(), hit.normal.y(), hit.normal.z());
            add_strings_row_to_table("Normal", ImGuiWrapper::COL_ORANGE_LIGHT, std::string(buf), ImGui::GetStyleColorVec4(ImGuiCol_Text));
            ImGui::EndTable();
        }
    }
    else
        imgui.text("NO HIT");
    ImGui::Separator();
    imgui.text("Registered for picking:");
    if (ImGui::BeginTable("Raycasters", 2)) {
        sprintf(buf, "%d (%d)", (int)m_scene_raycaster.beds_count(), (int)m_scene_raycaster.active_beds_count());
        add_strings_row_to_table("Beds", ImGuiWrapper::COL_ORANGE_LIGHT, std::string(buf), ImGui::GetStyleColorVec4(ImGuiCol_Text));
        sprintf(buf, "%d (%d)", (int)m_scene_raycaster.volumes_count(), (int)m_scene_raycaster.active_volumes_count());
        add_strings_row_to_table("Volumes", ImGuiWrapper::COL_ORANGE_LIGHT, std::string(buf), ImGui::GetStyleColorVec4(ImGuiCol_Text));
        sprintf(buf, "%d (%d)", (int)m_scene_raycaster.gizmos_count(), (int)m_scene_raycaster.active_gizmos_count());
        add_strings_row_to_table("Gizmo elements", ImGuiWrapper::COL_ORANGE_LIGHT, std::string(buf), ImGui::GetStyleColorVec4(ImGuiCol_Text));
        ImGui::EndTable();
    }
    std::vector<std::shared_ptr<SceneRaycasterItem>>* gizmo_raycasters = m_scene_raycaster.get_raycasters(SceneRaycaster::EType::Gizmo);
    if (gizmo_raycasters != nullptr && !gizmo_raycasters->empty()) {
        ImGui::Separator();
        imgui.text("Gizmo raycasters IDs:");
        if (ImGui::BeginTable("GizmoRaycasters", 3)) {
            for (size_t i = 0; i < gizmo_raycasters->size(); ++i) {
                add_strings_row_to_table(std::to_string(i), ImGuiWrapper::COL_ORANGE_LIGHT,
                    std::to_string(SceneRaycaster::decode_id(SceneRaycaster::EType::Gizmo, (*gizmo_raycasters)[i]->get_id())), ImGui::GetStyleColorVec4(ImGuiCol_Text),
                    to_string(Geometry::Transformation((*gizmo_raycasters)[i]->get_transform()).get_offset()), ImGui::GetStyleColorVec4(ImGuiCol_Text));
            }
            ImGui::EndTable();
        }
    }
    imgui.end();
#endif // ENABLE_RAYCAST_PICKING_DEBUG
}
References _update_volumes_hover_state(), Slic3r::GUI::add_strings_row_to_table(), Slic3r::GUI::SceneRaycaster::Bed, Slic3r::GUI::ImGuiWrapper::begin(), ImGui::BeginTable(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, Slic3r::GUI::SceneRaycaster::decode_id(), Slic3r::GUI::GLCanvas3D::Mouse::dragging, Slic3r::GUI::ImGuiWrapper::end(), ImGui::EndTable(), get_canvas_size(), Slic3r::GUI::GLGizmosManager::get_clipping_plane(), Slic3r::GUI::GLGizmosManager::get_current_type(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::SceneRaycaster::get_raycasters(), Slic3r::GUI::Size::get_width(), ImGui::GetStyleColorVec4(), Slic3r::GUI::SceneRaycaster::Gizmo, Slic3r::GUI::SceneRaycaster::hit(), ImGuiCol_Text, ImGuiWindowFlags_AlwaysAutoResize, Slic3r::GUI::ClippingPlane::inverted_normal(), Slic3r::GUI::GLGizmosManager::is_dragging(), Slic3r::GUI::SceneRaycaster::HitResult::is_valid(), m_gizmos, m_hover_volume_idxs, m_mouse, m_picking_enabled, m_render_sla_auxiliaries, m_scene_raycaster, m_volumes, Slic3r::GUI::SceneRaycaster::None, Slic3r::GUI::SceneRaycaster::HitResult::normal, Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::Mouse::position, Slic3r::GUI::SceneRaycaster::HitResult::position, Slic3r::GUI::SceneRaycaster::HitResult::raycaster_id, ImGui::Separator(), Slic3r::GUI::GLGizmosManager::set_hover_id(), Slic3r::slaposPad, Slic3r::slaposSupportTree, ImGui::TableNextRow(), ImGui::TableSetColumnIndex(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), Slic3r::to_string(), Slic3r::GUI::SceneRaycaster::HitResult::type, Slic3r::GUI::GLGizmosManager::Undefined, Slic3r::GUI::SceneRaycaster::Volume, and Slic3r::GLVolumeCollection::volumes.
Referenced by render().
_rectangular_selection_picking_pass()
void Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass () private
{
    m_gizmos.set_hover_id(-1);
    std::set<int> idxs;
    if (m_picking_enabled) {
        const size_t width  = std::max<size_t>(m_rectangle_selection.get_width(), 1);
        const size_t height = std::max<size_t>(m_rectangle_selection.get_height(), 1);
        const OpenGLManager::EFramebufferType framebuffers_type = OpenGLManager::get_framebuffers_type();
        bool use_framebuffer = framebuffers_type != OpenGLManager::EFramebufferType::Unknown;
        GLuint render_fbo = 0;
        GLuint render_tex = 0;
        GLuint render_depth = 0;
        if (use_framebuffer) {
            // setup a framebuffer which covers only the selection rectangle
            if (framebuffers_type == OpenGLManager::EFramebufferType::Arb) {
                glsafe(::glGenFramebuffers(1, &render_fbo));
                glsafe(::glBindFramebuffer(GL_FRAMEBUFFER, render_fbo));
            }
            else {
                glsafe(::glGenFramebuffersEXT(1, &render_fbo));
                glsafe(::glBindFramebufferEXT(GL_FRAMEBUFFER_EXT, render_fbo));
            }
            glsafe(::glGenTextures(1, &render_tex));
            glsafe(::glBindTexture(GL_TEXTURE_2D, render_tex));
            glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST));
            if (framebuffers_type == OpenGLManager::EFramebufferType::Arb) {
                glsafe(::glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, render_tex, 0));
                glsafe(::glGenRenderbuffers(1, &render_depth));
                glsafe(::glBindRenderbuffer(GL_RENDERBUFFER, render_depth));
#if ENABLE_OPENGL_ES
                glsafe(::glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT16, width, height));
#else
                glsafe(::glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT, width, height));
#endif // ENABLE_OPENGL_ES
                glsafe(::glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, render_depth));
            }
            else {
                glsafe(::glFramebufferTexture2D(GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, GL_TEXTURE_2D, render_tex, 0));
                glsafe(::glGenRenderbuffersEXT(1, &render_depth));
                glsafe(::glBindRenderbufferEXT(GL_RENDERBUFFER_EXT, render_depth));
                glsafe(::glRenderbufferStorageEXT(GL_RENDERBUFFER_EXT, GL_DEPTH_COMPONENT, width, height));
                glsafe(::glFramebufferRenderbufferEXT(GL_FRAMEBUFFER_EXT, GL_DEPTH_ATTACHMENT_EXT, GL_RENDERBUFFER_EXT, render_depth));
            }
            const GLenum drawBufs[] = { GL_COLOR_ATTACHMENT0 };
            glsafe(::glDrawBuffers(1, drawBufs));
            if (framebuffers_type == OpenGLManager::EFramebufferType::Arb) {
                if (::glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
                    use_framebuffer = false;
            }
            else {
                if (::glCheckFramebufferStatusEXT(GL_FRAMEBUFFER_EXT) != GL_FRAMEBUFFER_COMPLETE_EXT)
                    use_framebuffer = false;
            }
        }
        if (m_multisample_allowed)
          // This flag is often ignored by NVIDIA drivers if rendering into a screen buffer.
            glsafe(::glDisable(GL_MULTISAMPLE));
        glsafe(::glDisable(GL_BLEND));
        glsafe(::glEnable(GL_DEPTH_TEST));
        glsafe(::glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT));
        const Camera& main_camera = wxGetApp().plater()->get_camera();
        Camera framebuffer_camera;
        framebuffer_camera.set_type(main_camera.get_type());
        const Camera* camera = &main_camera;
        if (use_framebuffer) {
            // setup a camera which covers only the selection rectangle
            const std::array<int, 4>& viewport = camera->get_viewport();
            const double near_left   = camera->get_near_left();
            const double near_bottom = camera->get_near_bottom();
            const double near_width  = camera->get_near_width();
            const double near_height = camera->get_near_height();
            const double ratio_x = near_width / double(viewport[2]);
            const double ratio_y = near_height / double(viewport[3]);
            const double rect_near_left   = near_left + double(m_rectangle_selection.get_left()) * ratio_x;
            const double rect_near_bottom = near_bottom + (double(viewport[3]) - double(m_rectangle_selection.get_bottom())) * ratio_y;
            double rect_near_right = near_left + double(m_rectangle_selection.get_right()) * ratio_x;
            double rect_near_top   = near_bottom + (double(viewport[3]) - double(m_rectangle_selection.get_top())) * ratio_y;
            if (rect_near_left == rect_near_right)
                rect_near_right = rect_near_left + ratio_x;
            if (rect_near_bottom == rect_near_top)
                rect_near_top = rect_near_bottom + ratio_y;
            framebuffer_camera.look_at(camera->get_position(), camera->get_target(), camera->get_dir_up());
            framebuffer_camera.apply_projection(rect_near_left, rect_near_right, rect_near_bottom, rect_near_top, camera->get_near_z(), camera->get_far_z());
            framebuffer_camera.set_viewport(0, 0, width, height);
            framebuffer_camera.apply_viewport();
            camera = &framebuffer_camera;
        }
        _render_volumes_for_picking(*camera);
        _render_bed_for_picking(camera->get_view_matrix(), camera->get_projection_matrix(), !camera->is_looking_downward());
        if (m_multisample_allowed)
            glsafe(::glEnable(GL_MULTISAMPLE));
        const size_t px_count = width * height;
        const size_t left = use_framebuffer ? 0 : (size_t)m_rectangle_selection.get_left();
        const size_t top  = use_framebuffer ? 0 : (size_t)get_canvas_size().get_height() - (size_t)m_rectangle_selection.get_top();
#define USE_PARALLEL 1
#if USE_PARALLEL
            struct Pixel
            {
                std::array<GLubyte, 4> data;
              // Only non-interpolated colors are valid, those have their lowest three bits zeroed.
                bool valid() const { return picking_checksum_alpha_channel(data[0], data[1], data[2]) == data[3]; }
                // we reserve color = (0,0,0) for occluders (as the printbed)
                // volumes' id are shifted by 1
                // see: _render_volumes_for_picking()
                int id() const { return data[0] + (data[1] << 8) + (data[2] << 16) - 1; }
            };
            std::vector<Pixel> frame(px_count);
            glsafe(::glReadPixels(left, top, width, height, GL_RGBA, GL_UNSIGNED_BYTE, (void*)frame.data()));
            tbb::spin_mutex mutex;
            tbb::parallel_for(tbb::blocked_range<size_t>(0, frame.size(), (size_t)width),
                [this, &frame, &idxs, &mutex](const tbb::blocked_range<size_t>& range) {
                for (size_t i = range.begin(); i < range.end(); ++i)
                  if (frame[i].valid()) {
                      int volume_id = frame[i].id();
                      if (0 <= volume_id && volume_id < (int)m_volumes.volumes.size()) {
                          mutex.lock();
                          idxs.insert(volume_id);
                          mutex.unlock();
                      }
                  }
            });
#else
            std::vector<GLubyte> frame(4 * px_count);
            glsafe(::glReadPixels(left, top, width, height, GL_RGBA, GL_UNSIGNED_BYTE, (void*)frame.data()));
            for (int i = 0; i < px_count; ++i) {
                int px_id = 4 * i;
                int volume_id = frame[px_id] + (frame[px_id + 1] << 8) + (frame[px_id + 2] << 16);
                if (0 <= volume_id && volume_id < (int)m_volumes.volumes.size())
                    idxs.insert(volume_id);
            }
#endif // USE_PARALLEL
            if (camera != &main_camera)
                main_camera.apply_viewport();
            if (framebuffers_type == OpenGLManager::EFramebufferType::Arb) {
                glsafe(::glBindFramebuffer(GL_FRAMEBUFFER, 0));
                if (render_depth != 0)
                    glsafe(::glDeleteRenderbuffers(1, &render_depth));
                if (render_fbo != 0)
                    glsafe(::glDeleteFramebuffers(1, &render_fbo));
            }
            else if (framebuffers_type == OpenGLManager::EFramebufferType::Ext) {
                glsafe(::glBindFramebufferEXT(GL_FRAMEBUFFER_EXT, 0));
                if (render_depth != 0)
                    glsafe(::glDeleteRenderbuffersEXT(1, &render_depth));
                if (render_fbo != 0)
                    glsafe(::glDeleteFramebuffersEXT(1, &render_fbo));
            }
            if (render_tex != 0)
                glsafe(::glDeleteTextures(1, &render_tex));
    }
    m_hover_volume_idxs.assign(idxs.begin(), idxs.end());
    _update_volumes_hover_state();
}
References _render_bed_for_picking(), _render_volumes_for_picking(), Slic3r::GUI::Camera::apply_projection(), Slic3r::GUI::Camera::apply_viewport(), Slic3r::GUI::OpenGLManager::Arb, Slic3r::GUI::OpenGLManager::Ext, Slic3r::GUI::GLSelectionRectangle::get_bottom(), get_canvas_size(), Slic3r::GUI::Camera::get_dir_up(), Slic3r::GUI::Camera::get_far_z(), Slic3r::GUI::OpenGLManager::get_framebuffers_type(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::GLSelectionRectangle::get_height(), Slic3r::GUI::GLSelectionRectangle::get_left(), Slic3r::GUI::Camera::get_near_bottom(), Slic3r::GUI::Camera::get_near_height(), Slic3r::GUI::Camera::get_near_left(), Slic3r::GUI::Camera::get_near_width(), Slic3r::GUI::Camera::get_near_z(), Slic3r::GUI::Camera::get_position(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::GLSelectionRectangle::get_right(), Slic3r::GUI::Camera::get_target(), Slic3r::GUI::GLSelectionRectangle::get_top(), Slic3r::GUI::Camera::get_type(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), Slic3r::GUI::GLSelectionRectangle::get_width(), glsafe, Slic3r::GUI::Camera::is_looking_downward(), Slic3r::GUI::Camera::look_at(), m_gizmos, m_multisample_allowed, m_picking_enabled, m_rectangle_selection, m_volumes, Slic3r::picking_checksum_alpha_channel(), Slic3r::range(), Slic3r::GUI::GLGizmosManager::set_hover_id(), Slic3r::GUI::Camera::set_type(), Slic3r::GUI::Camera::set_viewport(), Slic3r::GUI::OpenGLManager::Unknown, and Slic3r::GLVolumeCollection::volumes.
Referenced by render().
_refresh_if_shown_on_screen()
void Slic3r::GUI::GLCanvas3D::_refresh_if_shown_on_screen () private
{
    if (_is_shown_on_screen()) {
        const Size& cnv_size = get_canvas_size();
        _resize((unsigned int)cnv_size.get_width(), (unsigned int)cnv_size.get_height());
        // When the application starts the following call to render() triggers the opengl initialization.
        // We need to ask for an extra call to reload_scene() to force the generation of the model for wipe tower
        // for printers using it, which is skipped by all the previous calls to reload_scene() because m_initialized == false
        const bool requires_reload_scene = !m_initialized;
        // Because of performance problems on macOS, where PaintEvents are not delivered
        // frequently enough, we call render() here directly when we can.
        render();
        assert(m_initialized);
        if (requires_reload_scene) {
            if (wxGetApp().plater()->is_view3D_shown())
                reload_scene(true);
        }
    }
}
References _is_shown_on_screen(), _resize(), get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), m_initialized, Slic3r::GUI::plater(), reload_scene(), and render().
Referenced by on_idle(), on_mouse(), on_set_focus(), and update_ui_from_settings().
_render_arrange_menu()
bool Slic3r::GUI::GLCanvas3D::_render_arrange_menu (float pos_x) private
{
    ImGuiWrapper *imgui = wxGetApp().imgui();
    imgui->set_next_window_pos(pos_x, m_main_toolbar.get_height(), ImGuiCond_Always, 0.5f, 0.0f);
    imgui->begin(_L("Arrange options"), ImGuiWindowFlags_NoMove | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoCollapse);
    ArrangeSettings settings = get_arrange_settings();
    ArrangeSettings &settings_out = get_arrange_settings_ref(this);
    auto &appcfg = wxGetApp().app_config;
    PrinterTechnology ptech = current_printer_technology();
    bool settings_changed = false;
    float dist_min = 0.f;
    float dist_bed_min = 0.f;
    std::string dist_key = "min_object_distance";
    std::string dist_bed_key = "min_bed_distance";
    std::string rot_key = "enable_rotation";
    std::string align_key = "alignment";
    std::string postfix;
    if (ptech == ptSLA) {
        postfix      = "_sla";
    } else if (ptech == ptFFF) {
        auto co_opt = m_config->option<ConfigOptionBool>("complete_objects");
        if (co_opt && co_opt->value) {
            dist_min     = float(min_object_distance(*m_config));
            postfix      = "_fff_seq_print";
        } else {
            dist_min     = 0.f;
            postfix     = "_fff";
        }
    }
    dist_key += postfix;
    dist_bed_key += postfix;
    rot_key += postfix;
    align_key += postfix;
    imgui->text(GUI::format_wxstr(_L("Press %1%left mouse button to enter the exact value"), shortkey_ctrl_prefix()));
    if (imgui->slider_float(_L("Spacing"), &settings.distance, dist_min, 100.0f, "%5.2f") || dist_min > settings.distance) {
        settings.distance = std::max(dist_min, settings.distance);
        settings_out.distance = settings.distance;
        appcfg->set("arrange", dist_key.c_str(), float_to_string_decimal_point(settings_out.distance));
        settings_changed = true;
    }
    if (imgui->slider_float(_L("Spacing from bed"), &settings.distance_from_bed, dist_bed_min, 100.0f, "%5.2f") || dist_bed_min > settings.distance_from_bed) {
        settings.distance_from_bed = std::max(dist_bed_min, settings.distance_from_bed);
        settings_out.distance_from_bed = settings.distance_from_bed;
        appcfg->set("arrange", dist_bed_key.c_str(), float_to_string_decimal_point(settings_out.distance_from_bed));
        settings_changed = true;
    }
    if (imgui->checkbox(_L("Enable rotations (slow)"), settings.enable_rotation)) {
        settings_out.enable_rotation = settings.enable_rotation;
        appcfg->set("arrange", rot_key.c_str(), settings_out.enable_rotation? "1" : "0");
        settings_changed = true;
    }
    Points bed = m_config ? get_bed_shape(*m_config) : Points{};
    if (arrangement::is_box(bed) && settings.alignment >= 0 &&
        imgui->combo(_L("Alignment"), {_u8L("Center"), _u8L("Rear left"), _u8L("Front left"), _u8L("Front right"), _u8L("Rear right"), _u8L("Random") }, settings.alignment)) {
        settings_out.alignment = settings.alignment;
        appcfg->set("arrange", align_key.c_str(), std::to_string(settings_out.alignment));
        settings_changed = true;
    }
    ImGui::Separator();
    if (imgui->button(_L("Reset"))) {
        auto alignment = settings_out.alignment;
        settings_out = ArrangeSettings{};
        settings_out.distance = std::max(dist_min, settings_out.distance);
        // Default alignment for XL printers set explicitly:
        if (is_arrange_alignment_enabled())
            settings_out.alignment = static_cast<int>(arrangement::Pivots::BottomLeft);
        else
            settings_out.alignment = alignment;
        appcfg->set("arrange", dist_key.c_str(), float_to_string_decimal_point(settings_out.distance));
        appcfg->set("arrange", dist_bed_key.c_str(), float_to_string_decimal_point(settings_out.distance_from_bed));
        appcfg->set("arrange", rot_key.c_str(), settings_out.enable_rotation? "1" : "0");
        settings_changed = true;
    }
    ImGui::SameLine();
    if (imgui->button(_L("Arrange"))) {
        wxGetApp().plater()->arrange();
    }
    imgui->end();
    return settings_changed;
}
References _L, _u8L, Slic3r::GUI::GLCanvas3D::ArrangeSettings::alignment, Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::arrangement::BottomLeft, Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::checkbox(), Slic3r::GUI::ImGuiWrapper::combo(), current_printer_technology(), Slic3r::GUI::GLCanvas3D::ArrangeSettings::distance, Slic3r::GUI::GLCanvas3D::ArrangeSettings::distance_from_bed, Slic3r::GUI::GLCanvas3D::ArrangeSettings::enable_rotation, Slic3r::GUI::ImGuiWrapper::end(), Slic3r::float_to_string_decimal_point(), Slic3r::GUI::format_wxstr(), get_arrange_settings(), get_arrange_settings_ref(), Slic3r::get_bed_shape(), Slic3r::GUI::GLToolbar::get_height(), ImGuiCond_Always, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, is_arrange_alignment_enabled(), Slic3r::arrangement::is_box(), m_config, m_main_toolbar, Slic3r::min_object_distance(), Slic3r::ConfigBase::option(), Slic3r::ptFFF, Slic3r::ptSLA, ImGui::SameLine(), ImGui::Separator(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::shortkey_ctrl_prefix(), Slic3r::GUI::ImGuiWrapper::slider_float(), and Slic3r::GUI::ImGuiWrapper::text().
Referenced by _init_main_toolbar().
_render_background()
void Slic3r::GUI::GLCanvas3D::_render_background () private
{
    bool use_error_color = false;
    if (wxGetApp().is_editor()) {
        use_error_color = m_dynamic_background_enabled &&
        (current_printer_technology() != ptSLA || !m_volumes.empty());
        if (!m_volumes.empty())
            use_error_color &= _is_any_volume_outside().first;
        else
            use_error_color &= m_gcode_viewer.has_data() && !m_gcode_viewer.is_contained_in_bed();
    }
    // Draws a bottom to top gradient over the complete screen.
    glsafe(::glDisable(GL_DEPTH_TEST));
    const ColorRGBA bottom_color = use_error_color ? ERROR_BG_DARK_COLOR : DEFAULT_BG_DARK_COLOR;
    if (!m_background.is_initialized()) {
        m_background.reset();
        GLModel::Geometry init_data;
        init_data.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P2T2 };
        init_data.reserve_vertices(4);
        init_data.reserve_indices(6);
        // vertices
        init_data.add_vertex(Vec2f(-1.0f, -1.0f), Vec2f(0.0f, 0.0f));
        init_data.add_vertex(Vec2f(1.0f, -1.0f),  Vec2f(1.0f, 0.0f));
        init_data.add_vertex(Vec2f(1.0f, 1.0f),   Vec2f(1.0f, 1.0f));
        init_data.add_vertex(Vec2f(-1.0f, 1.0f),  Vec2f(0.0f, 1.0f));
        // indices
        init_data.add_triangle(0, 1, 2);
        init_data.add_triangle(2, 3, 0);
        m_background.init_from(std::move(init_data));
    }
    GLShaderProgram* shader = wxGetApp().get_shader("background");
    if (shader != nullptr) {
        shader->start_using();
        shader->set_uniform("top_color", use_error_color ? ERROR_BG_LIGHT_COLOR : DEFAULT_BG_LIGHT_COLOR);
        shader->set_uniform("bottom_color", bottom_color);
        m_background.render();
        shader->stop_using();
    }
    glsafe(::glEnable(GL_DEPTH_TEST));
}
References Slic3r::GUI::GLModel::Geometry::add_triangle(), Slic3r::GUI::GLModel::Geometry::add_vertex(), DEFAULT_BG_DARK_COLOR, DEFAULT_BG_LIGHT_COLOR, ERROR_BG_DARK_COLOR, ERROR_BG_LIGHT_COLOR, Slic3r::GUI::GLModel::Geometry::format, glsafe, Slic3r::ptSLA, Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by render().
_render_bed()
void Slic3r::GUI::GLCanvas3D::_render_bed (const Transform3d & view_matrix, const Transform3d & projection_matrix, bool bottom) private
{
    float scale_factor = 1.0;
#if ENABLE_RETINA_GL
    scale_factor = m_retina_helper->get_scale_factor();
#endif // ENABLE_RETINA_GL
    bool show_texture = ! bottom ||
            (m_gizmos.get_current_type() != GLGizmosManager::FdmSupports
          && m_gizmos.get_current_type() != GLGizmosManager::SlaSupports
          && m_gizmos.get_current_type() != GLGizmosManager::Hollow
          && m_gizmos.get_current_type() != GLGizmosManager::Seam
          && m_gizmos.get_current_type() != GLGizmosManager::MmuSegmentation);
    m_bed.render(*this, view_matrix, projection_matrix, bottom, scale_factor, show_texture);
}
Referenced by _render_thumbnail_internal(), and render().
_render_bed_axes()
void Slic3r::GUI::GLCanvas3D::_render_bed_axes () private
{
  m_bed.render_axes();
}
Referenced by render().
_render_bed_for_picking()
void Slic3r::GUI::GLCanvas3D::_render_bed_for_picking (const Transform3d & view_matrix, const Transform3d & projection_matrix, bool bottom) private
{
    float scale_factor = 1.0;
#if ENABLE_RETINA_GL
    scale_factor = m_retina_helper->get_scale_factor();
#endif // ENABLE_RETINA_GL
    m_bed.render_for_picking(*this, view_matrix, projection_matrix, bottom, scale_factor);
}
Referenced by _rectangular_selection_picking_pass().
_render_collapse_toolbar()
void Slic3r::GUI::GLCanvas3D::_render_collapse_toolbar () const private
{
    GLToolbar& collapse_toolbar = wxGetApp().plater()->get_collapse_toolbar();
    const Size cnv_size = get_canvas_size();
    const float band = m_layers_editing.is_enabled() ? (wxGetApp().imgui()->get_style_scaling() * LayersEditing::THICKNESS_BAR_WIDTH) : 0.0;
    const float top  = 0.5f * (float)cnv_size.get_height();
    const float left = 0.5f * (float)cnv_size.get_width() - collapse_toolbar.get_width() - band;
    collapse_toolbar.set_position(top, left);
    collapse_toolbar.render(*this);
}
References Slic3r::GUI::Size::get_height(), Slic3r::GUI::GLToolbar::get_width(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLToolbar::render(), and Slic3r::GUI::GLToolbar::set_position().
_render_current_gizmo()
void Slic3r::GUI::GLCanvas3D::_render_current_gizmo () const private
{
    m_gizmos.render_current_gizmo();
}
Referenced by render().
_render_gcode()
void Slic3r::GUI::GLCanvas3D::_render_gcode () private
{
    m_gcode_viewer.render();
}
Referenced by render().
_render_gcode_cog()
void Slic3r::GUI::GLCanvas3D::_render_gcode_cog () private
{
    m_gcode_viewer.render_cog();
}
Referenced by render().
_render_gizmos_overlay()
void Slic3r::GUI::GLCanvas3D::_render_gizmos_overlay () private
#ys_FIXME_experiment
{
#if ENABLE_RETINA_GL
//     m_gizmos.set_overlay_scale(m_retina_helper->get_scale_factor());
    const float scale = m_retina_helper->get_scale_factor()*wxGetApp().toolbar_icon_scale();
    m_gizmos.set_overlay_scale(scale);
#else
//     m_gizmos.set_overlay_scale(m_canvas->GetContentScaleFactor());
//     m_gizmos.set_overlay_scale(wxGetApp().em_unit()*0.1f);
    const float size = int(GLGizmosManager::Default_Icons_Size * wxGetApp().toolbar_icon_scale());
    m_gizmos.set_overlay_icon_size(size);
#endif /* __WXMSW__ */
    m_gizmos.render_overlay();
    if (m_gizmo_highlighter.m_render_arrow)
        m_gizmos.render_arrow(*this, m_gizmo_highlighter.m_gizmo_type);
}
References scale().
_render_main_toolbar()
void Slic3r::GUI::GLCanvas3D::_render_main_toolbar () private
{
    if (!m_main_toolbar.is_enabled())
        return;
    const Size cnv_size = get_canvas_size();
    const float top = 0.5f * (float)cnv_size.get_height();
    GLToolbar& collapse_toolbar = wxGetApp().plater()->get_collapse_toolbar();
    const float collapse_toolbar_width = collapse_toolbar.is_enabled() ? collapse_toolbar.get_width() : 0.0f;
    const float left = -0.5f * (m_main_toolbar.get_width() + m_undoredo_toolbar.get_width() + collapse_toolbar_width);
    m_main_toolbar.set_position(top, left);
    m_main_toolbar.render(*this);
    if (m_toolbar_highlighter.m_render_arrow)
        m_main_toolbar.render_arrow(*this, m_toolbar_highlighter.m_toolbar_item);
}
References Slic3r::GUI::Size::get_height(), Slic3r::GUI::GLToolbar::get_width(), and Slic3r::GUI::GLToolbar::is_enabled().
_render_objects()
void Slic3r::GUI::GLCanvas3D::_render_objects (GLVolumeCollection::ERenderType type) private
{
    if (m_volumes.empty())
        return;
    glsafe(::glEnable(GL_DEPTH_TEST));
    m_camera_clipping_plane = m_gizmos.get_clipping_plane();
    if (m_picking_enabled)
        // Update the layer editing selection to the first object selected, update the current object maximum Z.
        m_layers_editing.select_object(*m_model, this->is_layers_editing_enabled() ? m_selection.get_object_idx() : -1);
    if (const BuildVolume &build_volume = m_bed.build_volume(); build_volume.valid()) {
        switch (build_volume.type()) {
        case BuildVolume::Type::Rectangle: {
            const BoundingBox3Base<Vec3d> bed_bb = build_volume.bounding_volume().inflated(BuildVolume::SceneEpsilon);
            m_volumes.set_print_volume({ 0, // circle
                { float(bed_bb.min.x()), float(bed_bb.min.y()), float(bed_bb.max.x()), float(bed_bb.max.y()) },
                { 0.0f, float(build_volume.max_print_height()) } });
            break;
        }
        case BuildVolume::Type::Circle: {
            m_volumes.set_print_volume({ 1, // rectangle
                { unscaled<float>(build_volume.circle().center.x()), unscaled<float>(build_volume.circle().center.y()), unscaled<float>(build_volume.circle().radius + BuildVolume::SceneEpsilon), 0.0f },
                { 0.0f, float(build_volume.max_print_height() + BuildVolume::SceneEpsilon) } });
            break;
        }
        default:
        case BuildVolume::Type::Convex:
        case BuildVolume::Type::Custom: {
            m_volumes.set_print_volume({ static_cast<int>(type),
                { -FLT_MAX, -FLT_MAX, FLT_MAX, FLT_MAX },
                { -FLT_MAX, FLT_MAX } }
            );
        }
        }
        if (m_requires_check_outside_state) {
            check_volumes_outside_state(build_volume, nullptr);
            m_requires_check_outside_state = false;
        }
    }
    if (m_use_clipping_planes)
        m_volumes.set_z_range(-m_clipping_planes[0].get_data()[3], m_clipping_planes[1].get_data()[3]);
    else
        m_volumes.set_z_range(-FLT_MAX, FLT_MAX);
    m_volumes.set_clipping_plane(m_camera_clipping_plane.get_data());
    m_volumes.set_show_sinking_contours(! m_gizmos.is_hiding_instances());
    m_volumes.set_show_non_manifold_edges(!m_gizmos.is_hiding_instances() && m_gizmos.get_current_type() != GLGizmosManager::Simplify);
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud");
    if (shader != nullptr) {
        shader->start_using();
        switch (type)
        {
        default:
        case GLVolumeCollection::ERenderType::Opaque:
        {
            if (m_picking_enabled && !m_gizmos.is_dragging() && m_layers_editing.is_enabled() && (m_layers_editing.last_object_id != -1) && (m_layers_editing.object_max_z() > 0.0f)) {
                int object_id = m_layers_editing.last_object_id;
                const Camera& camera = wxGetApp().plater()->get_camera();
                m_volumes.render(type, false, camera.get_view_matrix(), camera.get_projection_matrix(), [object_id](const GLVolume& volume) {
                    // Which volume to paint without the layer height profile shader?
                    return volume.is_active && (volume.is_modifier || volume.composite_id.object_id != object_id);
                    });
                // Let LayersEditing handle rendering of the active object using the layer height profile shader.
                m_layers_editing.render_volumes(*this, m_volumes);
            }
            else {
                // do not cull backfaces to show broken geometry, if any
                const Camera& camera = wxGetApp().plater()->get_camera();
                m_volumes.render(type, m_picking_enabled, camera.get_view_matrix(), camera.get_projection_matrix(), [this](const GLVolume& volume) {
                    return (m_render_sla_auxiliaries || volume.composite_id.volume_id >= 0);
                    });
            }
            // In case a painting gizmo is open, it should render the painted triangles
            // before transparent objects are rendered. Otherwise they would not be
            // visible when inside modifier meshes etc.
            {
                GLGizmosManager& gm = get_gizmos_manager();
//                GLGizmosManager::EType type = gm.get_current_type();
                if (dynamic_cast<GLGizmoPainterBase*>(gm.get_current())) {
                    shader->stop_using();
                    gm.render_painter_gizmo();
                    shader->start_using();
                }
            }
            break;
        }
        case GLVolumeCollection::ERenderType::Transparent:
        {
            const Camera& camera = wxGetApp().plater()->get_camera();
            m_volumes.render(type, false, camera.get_view_matrix(), camera.get_projection_matrix());
            break;
        }
        }
        shader->stop_using();
    }
    m_camera_clipping_plane = ClippingPlane::ClipsNothing();
}
References Slic3r::BuildVolume::Circle, Slic3r::BuildVolume::Convex, Slic3r::BuildVolume::Custom, Slic3r::GUI::GLGizmosManager::get_current(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), glsafe, Slic3r::BoundingBox3Base< PointType >::inflated(), Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::GLVolumeCollection::Opaque, Slic3r::BuildVolume::Rectangle, Slic3r::GUI::GLGizmosManager::render_painter_gizmo(), Slic3r::BuildVolume::SceneEpsilon, Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::GLVolumeCollection::Transparent, and Slic3r::BuildVolume::valid().
Referenced by render().
_render_overlays()
void Slic3r::GUI::GLCanvas3D::_render_overlays () private
{
    glsafe(::glDisable(GL_DEPTH_TEST));
    // main toolbar and undoredo toolbar need to be both updated before rendering because both their sizes are needed
    // to correctly place them
    _check_and_update_toolbar_icon_scale();
    _render_gizmos_overlay();
    _render_main_toolbar();
    _render_undoredo_toolbar();
    _render_collapse_toolbar();
    _render_view_toolbar();
    if (m_layers_editing.last_object_id >= 0 && m_layers_editing.object_max_z() > 0.0f)
        m_layers_editing.render_overlay(*this);
    const ConfigOptionBool* opt = dynamic_cast<const ConfigOptionBool*>(m_config->option("complete_objects"));
    bool sequential_print = opt != nullptr && opt->value;
    std::vector<const ModelInstance*> sorted_instances;
    if (sequential_print) {
        for (ModelObject* model_object : m_model->objects)
            for (ModelInstance* model_instance : model_object->instances) {
                sorted_instances.emplace_back(model_instance);
            }
    }
    m_labels.render(sorted_instances);
}
References glsafe, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by render().
_render_search_list()
bool Slic3r::GUI::GLCanvas3D::_render_search_list (float pos_x) private
{
    bool action_taken = false;
    ImGuiWrapper* imgui = wxGetApp().imgui();
    imgui->set_next_window_pos(pos_x, m_main_toolbar.get_height(), ImGuiCond_Always, 0.5f, 0.0f);
    std::string title = L("Search");
    imgui->begin(_(title), ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse);
    int selected = -1;
    bool edited = false;
    float em = static_cast<float>(wxGetApp().em_unit());
#if ENABLE_RETINA_GL
  em *= m_retina_helper->get_scale_factor();
#endif // ENABLE_RETINA_GL
    Sidebar& sidebar = wxGetApp().sidebar();
    std::string& search_line = sidebar.get_search_line();
    char *s = new char[255];
    strcpy(s, search_line.empty() ? _u8L("Enter a search term").c_str() : search_line.c_str());
    imgui->search_list(ImVec2(45 * em, 30 * em), &search_string_getter, s,
        sidebar.get_searcher().view_params,
        selected, edited, m_mouse_wheel, wxGetApp().is_localized());
    search_line = s;
    delete [] s;
    if (search_line == _u8L("Enter a search term"))
        search_line.clear();
    if (edited)
        sidebar.search();
    if (selected >= 0) {
        // selected == 9999 means that Esc kye was pressed
        /*// revert commit https://github.com/prusa3d/PrusaSlicer/commit/91897589928789b261ca0dc735ffd46f2b0b99f2
        if (selected == 9999)
            action_taken = true;
        else
            sidebar.jump_to_option(selected);*/
        if (selected != 9999) {
            imgui->end(); // end imgui before the jump to option
            sidebar.jump_to_option(selected);
            return true;
        }
        action_taken = true;
    }
    imgui->end();
    return action_taken;
}
References _, _u8L, Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLToolbar::get_height(), Slic3r::GUI::Sidebar::get_search_line(), Slic3r::GUI::Sidebar::get_searcher(), ImGuiCond_Always, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, Slic3r::GUI::Sidebar::jump_to_option(), L, m_main_toolbar, m_mouse_wheel, Slic3r::GUI::Sidebar::search(), Slic3r::GUI::ImGuiWrapper::search_list(), Slic3r::GUI::search_string_getter(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), and Slic3r::Search::OptionsSearcher::view_params.
Referenced by _init_main_toolbar().
_render_selection()
void Slic3r::GUI::GLCanvas3D::_render_selection () private
{
    float scale_factor = 1.0;
#if ENABLE_RETINA_GL
    scale_factor = m_retina_helper->get_scale_factor();
#endif // ENABLE_RETINA_GL
    if (!m_gizmos.is_running())
        m_selection.render(scale_factor);
#if ENABLE_MATRICES_DEBUG
    m_selection.render_debug_window();
#endif // ENABLE_MATRICES_DEBUG
}
Referenced by render().
_render_selection_sidebar_hints()
void Slic3r::GUI::GLCanvas3D::_render_selection_sidebar_hints () private
{
    m_selection.render_sidebar_hints(m_sidebar_field);
}
Referenced by render().
_render_sequential_clearance()
void Slic3r::GUI::GLCanvas3D::_render_sequential_clearance () private
{
    if (current_printer_technology() != ptFFF || !fff_print()->config().complete_objects)
        return;
    if (m_layers_editing.is_enabled())
        return;
    switch (m_gizmos.get_current_type())
    {
    case GLGizmosManager::EType::Flatten:
    case GLGizmosManager::EType::Cut:
    case GLGizmosManager::EType::MmuSegmentation:
    case GLGizmosManager::EType::Measure:
    case GLGizmosManager::EType::Emboss:
    case GLGizmosManager::EType::Simplify:
    case GLGizmosManager::EType::FdmSupports:
    case GLGizmosManager::EType::Seam: { return; }
    default: { break; }
    }
    m_sequential_print_clearance.render();
}
References Slic3r::ptFFF.
Referenced by render().
_render_sla_slices()
void Slic3r::GUI::GLCanvas3D::_render_sla_slices () private
{
    if (!m_use_clipping_planes || current_printer_technology() != ptSLA)
        return;
    const SLAPrint* print = this->sla_print();
    const PrintObjects& print_objects = print->objects();
    if (print_objects.empty())
        // nothing to render, return
        return;
    double clip_min_z = -m_clipping_planes[0].get_data()[3];
    double clip_max_z = m_clipping_planes[1].get_data()[3];
    for (unsigned int i = 0; i < (unsigned int)print_objects.size(); ++i) {
        const SLAPrintObject* obj = print_objects[i];
        if (!obj->is_step_done(slaposSliceSupports))
            continue;
        SlaCap::ObjectIdToModelsMap::iterator it_caps_bottom = m_sla_caps[0].triangles.find(i);
        SlaCap::ObjectIdToModelsMap::iterator it_caps_top = m_sla_caps[1].triangles.find(i);
        {
            if (it_caps_bottom == m_sla_caps[0].triangles.end())
                it_caps_bottom = m_sla_caps[0].triangles.emplace(i, SlaCap::Triangles()).first;
            if (!m_sla_caps[0].matches(clip_min_z)) {
                m_sla_caps[0].z = clip_min_z;
                it_caps_bottom->second.object.reset();
                it_caps_bottom->second.supports.reset();
            }
            if (it_caps_top == m_sla_caps[1].triangles.end())
                it_caps_top = m_sla_caps[1].triangles.emplace(i, SlaCap::Triangles()).first;
            if (!m_sla_caps[1].matches(clip_max_z)) {
                m_sla_caps[1].z = clip_max_z;
                it_caps_top->second.object.reset();
                it_caps_top->second.supports.reset();
            }
        }
        GLModel& bottom_obj_triangles = it_caps_bottom->second.object;
        GLModel& bottom_sup_triangles = it_caps_bottom->second.supports;
        GLModel& top_obj_triangles = it_caps_top->second.object;
        GLModel& top_sup_triangles = it_caps_top->second.supports;
        auto init_model = [](GLModel& model, const Pointf3s& triangles, const ColorRGBA& color) {
            GLModel::Geometry init_data;
            init_data.format = { GLModel::Geometry::EPrimitiveType::Triangles, GLModel::Geometry::EVertexLayout::P3 };
            init_data.reserve_vertices(triangles.size());
            init_data.reserve_indices(triangles.size() / 3);
            init_data.color = color;
            unsigned int vertices_count = 0;
            for (const Vec3d& v : triangles) {
                init_data.add_vertex((Vec3f)v.cast<float>());
                ++vertices_count;
                if (vertices_count % 3 == 0)
                    init_data.add_triangle(vertices_count - 3, vertices_count - 2, vertices_count - 1);
            }
            if (!init_data.is_empty())
                model.init_from(std::move(init_data));
        };
        if ((!bottom_obj_triangles.is_initialized() || !bottom_sup_triangles.is_initialized() ||
            !top_obj_triangles.is_initialized() || !top_sup_triangles.is_initialized()) && !obj->get_slice_index().empty()) {
            double layer_height         = print->default_object_config().layer_height.value;
            double initial_layer_height = print->material_config().initial_layer_height.value;
            bool   left_handed          = obj->is_left_handed();
            coord_t key_zero = obj->get_slice_index().front().print_level();
            // Slice at the center of the slab starting at clip_min_z will be rendered for the lower plane.
            coord_t key_low  = coord_t((clip_min_z - initial_layer_height + layer_height) / SCALING_FACTOR) + key_zero;
            // Slice at the center of the slab ending at clip_max_z will be rendered for the upper plane.
            coord_t key_high = coord_t((clip_max_z - initial_layer_height) / SCALING_FACTOR) + key_zero;
            const SliceRecord& slice_low  = obj->closest_slice_to_print_level(key_low, coord_t(SCALED_EPSILON));
            const SliceRecord& slice_high = obj->closest_slice_to_print_level(key_high, coord_t(SCALED_EPSILON));
            // Offset to avoid OpenGL Z fighting between the object's horizontal surfaces and the triangluated surfaces of the cuts.
            const double plane_shift_z = 0.002;
            if (slice_low.is_valid()) {
                const ExPolygons& obj_bottom = slice_low.get_slice(soModel);
                const ExPolygons& sup_bottom = slice_low.get_slice(soSupport);
                // calculate model bottom cap
                if (!bottom_obj_triangles.is_initialized() && !obj_bottom.empty())
                    init_model(bottom_obj_triangles, triangulate_expolygons_3d(obj_bottom, clip_min_z - plane_shift_z, !left_handed), { 1.0f, 0.37f, 0.0f, 1.0f });
                // calculate support bottom cap
                if (!bottom_sup_triangles.is_initialized() && !sup_bottom.empty())
                    init_model(bottom_sup_triangles, triangulate_expolygons_3d(sup_bottom, clip_min_z - plane_shift_z, !left_handed), { 1.0f, 0.0f, 0.37f, 1.0f });
            }
            if (slice_high.is_valid()) {
                const ExPolygons& obj_top = slice_high.get_slice(soModel);
                const ExPolygons& sup_top = slice_high.get_slice(soSupport);
                // calculate model top cap
                if (!top_obj_triangles.is_initialized() && !obj_top.empty())
                    init_model(top_obj_triangles, triangulate_expolygons_3d(obj_top, clip_max_z + plane_shift_z, left_handed), { 1.0f, 0.37f, 0.0f, 1.0f });
                // calculate support top cap
                if (!top_sup_triangles.is_initialized() && !sup_top.empty())
                    init_model(top_sup_triangles, triangulate_expolygons_3d(sup_top, clip_max_z + plane_shift_z, left_handed), { 1.0f, 0.0f, 0.37f, 1.0f });
            }
        }
        GLShaderProgram* shader = wxGetApp().get_shader("flat");
        if (shader != nullptr) {
            shader->start_using();
            for (const SLAPrintObject::Instance& inst : obj->instances()) {
                const Camera& camera = wxGetApp().plater()->get_camera();
                Transform3d view_model_matrix = camera.get_view_matrix() *
                    Geometry::translation_transform({ unscale<double>(inst.shift.x()), unscale<double>(inst.shift.y()), 0.0 }) *
                    Geometry::rotation_transform(inst.rotation * Vec3d::UnitZ());
                if (obj->is_left_handed())
                    view_model_matrix = view_model_matrix * Geometry::scale_transform({ -1.0f, 1.0f, 1.0f });
                shader->set_uniform("view_model_matrix", view_model_matrix);
                shader->set_uniform("projection_matrix", camera.get_projection_matrix());
                bottom_obj_triangles.render();
                top_obj_triangles.render();
                bottom_sup_triangles.render();
                top_sup_triangles.render();
            }
            shader->stop_using();
        }
    }
}
References Slic3r::GUI::GLModel::Geometry::add_triangle(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::SLAPrintObject::closest_slice_to_print_level(), Slic3r::GUI::GLModel::Geometry::color, Slic3r::SLAPrint::default_object_config(), Slic3r::GUI::GLModel::Geometry::format, Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::SLAPrintObject::SliceRecord::get_slice(), Slic3r::SLAPrintObject::get_slice_index(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::GLModel::init_from(), Slic3r::SLAPrintObject::instances(), Slic3r::GUI::GLModel::Geometry::is_empty(), Slic3r::GUI::GLModel::is_initialized(), Slic3r::SLAPrintObject::is_left_handed(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnumType, COUNT >::is_step_done(), Slic3r::SLAPrintObject::SliceRecord::is_valid(), Slic3r::layer_height(), Slic3r::SLAPrint::material_config(), Slic3r::SLAPrint::objects(), Slic3r::ptSLA, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::Geometry::reserve_indices(), Slic3r::GUI::GLModel::Geometry::reserve_vertices(), Slic3r::Geometry::rotation_transform(), Slic3r::Geometry::scale_transform(), SCALED_EPSILON, SCALING_FACTOR, Slic3r::GLShaderProgram::set_uniform(), Slic3r::slaposSliceSupports, Slic3r::soModel, Slic3r::soSupport, Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::Geometry::translation_transform(), and Slic3r::triangulate_expolygons_3d().
Referenced by render().
_render_thumbnail_framebuffer()
void Slic3r::GUI::GLCanvas3D::_render_thumbnail_framebuffer (ThumbnailData & thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams & thumbnail_params, const GLVolumeCollection & volumes, Camera::EType camera_type) private
{
    thumbnail_data.set(w, h);
    if (!thumbnail_data.is_valid())
        return;
    bool multisample = m_multisample_allowed;
    if (multisample)
        glsafe(::glEnable(GL_MULTISAMPLE));
    GLint max_samples;
    glsafe(::glGetIntegerv(GL_MAX_SAMPLES, &max_samples));
    GLsizei num_samples = max_samples / 2;
    GLuint render_fbo;
    glsafe(::glGenFramebuffers(1, &render_fbo));
    glsafe(::glBindFramebuffer(GL_FRAMEBUFFER, render_fbo));
    GLuint render_tex = 0;
    GLuint render_tex_buffer = 0;
    if (multisample) {
        // use renderbuffer instead of texture to avoid the need to use glTexImage2DMultisample which is available only since OpenGL 3.2
        glsafe(::glGenRenderbuffers(1, &render_tex_buffer));
        glsafe(::glBindRenderbuffer(GL_RENDERBUFFER, render_tex_buffer));
        glsafe(::glRenderbufferStorageMultisample(GL_RENDERBUFFER, num_samples, GL_RGBA8, w, h));
        glsafe(::glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_RENDERBUFFER, render_tex_buffer));
    }
    else {
        glsafe(::glGenTextures(1, &render_tex));
        glsafe(::glBindTexture(GL_TEXTURE_2D, render_tex));
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, w, h, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr));
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
        glsafe(::glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, render_tex, 0));
    }
    GLuint render_depth;
    glsafe(::glGenRenderbuffers(1, &render_depth));
    glsafe(::glBindRenderbuffer(GL_RENDERBUFFER, render_depth));
    if (multisample)
        glsafe(::glRenderbufferStorageMultisample(GL_RENDERBUFFER, num_samples, GL_DEPTH_COMPONENT24, w, h));
    else
        glsafe(::glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT, w, h));
    glsafe(::glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, render_depth));
    GLenum drawBufs[] = { GL_COLOR_ATTACHMENT0 };
    glsafe(::glDrawBuffers(1, drawBufs));
    if (::glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE) {
        _render_thumbnail_internal(thumbnail_data, thumbnail_params, volumes, camera_type);
        if (multisample) {
            GLuint resolve_fbo;
            glsafe(::glGenFramebuffers(1, &resolve_fbo));
            glsafe(::glBindFramebuffer(GL_FRAMEBUFFER, resolve_fbo));
            GLuint resolve_tex;
            glsafe(::glGenTextures(1, &resolve_tex));
            glsafe(::glBindTexture(GL_TEXTURE_2D, resolve_tex));
            glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, w, h, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
            glsafe(::glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, resolve_tex, 0));
            glsafe(::glDrawBuffers(1, drawBufs));
            if (::glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE) {
                glsafe(::glBindFramebuffer(GL_READ_FRAMEBUFFER, render_fbo));
                glsafe(::glBindFramebuffer(GL_DRAW_FRAMEBUFFER, resolve_fbo));
                glsafe(::glBlitFramebuffer(0, 0, w, h, 0, 0, w, h, GL_COLOR_BUFFER_BIT, GL_LINEAR));
                glsafe(::glBindFramebuffer(GL_READ_FRAMEBUFFER, resolve_fbo));
                glsafe(::glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, (void*)thumbnail_data.pixels.data()));
            }
            glsafe(::glDeleteTextures(1, &resolve_tex));
            glsafe(::glDeleteFramebuffers(1, &resolve_fbo));
        }
        else
            glsafe(::glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, (void*)thumbnail_data.pixels.data()));
#if ENABLE_THUMBNAIL_GENERATOR_DEBUG_OUTPUT
        debug_output_thumbnail(thumbnail_data);
#endif // ENABLE_THUMBNAIL_GENERATOR_DEBUG_OUTPUT
    }
    glsafe(::glBindFramebuffer(GL_FRAMEBUFFER, 0));
    glsafe(::glDeleteRenderbuffers(1, &render_depth));
    if (render_tex_buffer != 0)
        glsafe(::glDeleteRenderbuffers(1, &render_tex_buffer));
    if (render_tex != 0)
        glsafe(::glDeleteTextures(1, &render_tex));
    glsafe(::glDeleteFramebuffers(1, &render_fbo));
    if (multisample)
        glsafe(::glDisable(GL_MULTISAMPLE));
}
References _render_thumbnail_internal(), glsafe, Slic3r::ThumbnailData::is_valid(), m_multisample_allowed, Slic3r::ThumbnailData::pixels, and Slic3r::ThumbnailData::set().
Referenced by render_thumbnail().
_render_thumbnail_framebuffer_ext()
void Slic3r::GUI::GLCanvas3D::_render_thumbnail_framebuffer_ext (ThumbnailData & thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams & thumbnail_params, const GLVolumeCollection & volumes, Camera::EType camera_type) private
{
    thumbnail_data.set(w, h);
    if (!thumbnail_data.is_valid())
        return;
    bool multisample = m_multisample_allowed;
    if (multisample)
        glsafe(::glEnable(GL_MULTISAMPLE));
    GLint max_samples;
    glsafe(::glGetIntegerv(GL_MAX_SAMPLES_EXT, &max_samples));
    GLsizei num_samples = max_samples / 2;
    GLuint render_fbo;
    glsafe(::glGenFramebuffersEXT(1, &render_fbo));
    glsafe(::glBindFramebufferEXT(GL_FRAMEBUFFER_EXT, render_fbo));
    GLuint render_tex = 0;
    GLuint render_tex_buffer = 0;
    if (multisample) {
        // use renderbuffer instead of texture to avoid the need to use glTexImage2DMultisample which is available only since OpenGL 3.2
        glsafe(::glGenRenderbuffersEXT(1, &render_tex_buffer));
        glsafe(::glBindRenderbufferEXT(GL_RENDERBUFFER_EXT, render_tex_buffer));
        glsafe(::glRenderbufferStorageMultisampleEXT(GL_RENDERBUFFER_EXT, num_samples, GL_RGBA8, w, h));
        glsafe(::glFramebufferRenderbufferEXT(GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, GL_RENDERBUFFER_EXT, render_tex_buffer));
    }
    else {
        glsafe(::glGenTextures(1, &render_tex));
        glsafe(::glBindTexture(GL_TEXTURE_2D, render_tex));
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, w, h, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr));
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
        glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
        glsafe(::glFramebufferTexture2D(GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, GL_TEXTURE_2D, render_tex, 0));
    }
    GLuint render_depth;
    glsafe(::glGenRenderbuffersEXT(1, &render_depth));
    glsafe(::glBindRenderbufferEXT(GL_RENDERBUFFER_EXT, render_depth));
    if (multisample)
        glsafe(::glRenderbufferStorageMultisampleEXT(GL_RENDERBUFFER_EXT, num_samples, GL_DEPTH_COMPONENT24, w, h));
    else
        glsafe(::glRenderbufferStorageEXT(GL_RENDERBUFFER_EXT, GL_DEPTH_COMPONENT, w, h));
    glsafe(::glFramebufferRenderbufferEXT(GL_FRAMEBUFFER_EXT, GL_DEPTH_ATTACHMENT_EXT, GL_RENDERBUFFER_EXT, render_depth));
    GLenum drawBufs[] = { GL_COLOR_ATTACHMENT0 };
    glsafe(::glDrawBuffers(1, drawBufs));
    if (::glCheckFramebufferStatusEXT(GL_FRAMEBUFFER_EXT) == GL_FRAMEBUFFER_COMPLETE_EXT) {
        _render_thumbnail_internal(thumbnail_data, thumbnail_params, volumes, camera_type);
        if (multisample) {
            GLuint resolve_fbo;
            glsafe(::glGenFramebuffersEXT(1, &resolve_fbo));
            glsafe(::glBindFramebufferEXT(GL_FRAMEBUFFER_EXT, resolve_fbo));
            GLuint resolve_tex;
            glsafe(::glGenTextures(1, &resolve_tex));
            glsafe(::glBindTexture(GL_TEXTURE_2D, resolve_tex));
            glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, w, h, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
            glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
            glsafe(::glFramebufferTexture2DEXT(GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, GL_TEXTURE_2D, resolve_tex, 0));
            glsafe(::glDrawBuffers(1, drawBufs));
            if (::glCheckFramebufferStatusEXT(GL_FRAMEBUFFER_EXT) == GL_FRAMEBUFFER_COMPLETE_EXT) {
                glsafe(::glBindFramebufferEXT(GL_READ_FRAMEBUFFER_EXT, render_fbo));
                glsafe(::glBindFramebufferEXT(GL_DRAW_FRAMEBUFFER_EXT, resolve_fbo));
                glsafe(::glBlitFramebufferEXT(0, 0, w, h, 0, 0, w, h, GL_COLOR_BUFFER_BIT, GL_LINEAR));
                glsafe(::glBindFramebufferEXT(GL_READ_FRAMEBUFFER_EXT, resolve_fbo));
                glsafe(::glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, (void*)thumbnail_data.pixels.data()));
            }
            glsafe(::glDeleteTextures(1, &resolve_tex));
            glsafe(::glDeleteFramebuffersEXT(1, &resolve_fbo));
        }
        else
            glsafe(::glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, (void*)thumbnail_data.pixels.data()));
#if ENABLE_THUMBNAIL_GENERATOR_DEBUG_OUTPUT
        debug_output_thumbnail(thumbnail_data);
#endif // ENABLE_THUMBNAIL_GENERATOR_DEBUG_OUTPUT
    }
    glsafe(::glBindFramebufferEXT(GL_FRAMEBUFFER_EXT, 0));
    glsafe(::glDeleteRenderbuffersEXT(1, &render_depth));
    if (render_tex_buffer != 0)
        glsafe(::glDeleteRenderbuffersEXT(1, &render_tex_buffer));
    if (render_tex != 0)
        glsafe(::glDeleteTextures(1, &render_tex));
    glsafe(::glDeleteFramebuffersEXT(1, &render_fbo));
    if (multisample)
        glsafe(::glDisable(GL_MULTISAMPLE));
}
References _render_thumbnail_internal(), glsafe, Slic3r::ThumbnailData::is_valid(), m_multisample_allowed, Slic3r::ThumbnailData::pixels, and Slic3r::ThumbnailData::set().
Referenced by render_thumbnail().
_render_thumbnail_internal()
void Slic3r::GUI::GLCanvas3D::_render_thumbnail_internal (ThumbnailData & thumbnail_data, const ThumbnailsParams & thumbnail_params, const GLVolumeCollection & volumes, Camera::EType camera_type) private
{
    auto is_visible = [](const GLVolume& v) {
        bool ret = v.printable;
        ret &= (!v.shader_outside_printer_detection_enabled || !v.is_outside);
        return ret;
    };
    GLVolumePtrs visible_volumes;
    for (GLVolume* vol : volumes.volumes) {
        if (!vol->is_modifier && !vol->is_wipe_tower && (!thumbnail_params.parts_only || vol->composite_id.volume_id >= 0)) {
            if (!thumbnail_params.printable_only || is_visible(*vol))
                visible_volumes.emplace_back(vol);
        }
    }
    BoundingBoxf3 volumes_box;
    if (!visible_volumes.empty()) {
        for (const GLVolume* vol : visible_volumes) {
            volumes_box.merge(vol->transformed_bounding_box());
        }
    }
    else
        // This happens for empty projects
        volumes_box = m_bed.extended_bounding_box();
    Camera camera;
    camera.set_type(camera_type);
    camera.set_scene_box(scene_bounding_box());
    camera.set_viewport(0, 0, thumbnail_data.width, thumbnail_data.height);
    camera.apply_viewport();
    camera.zoom_to_box(volumes_box);
    const Transform3d& view_matrix = camera.get_view_matrix();
    double near_z = -1.0;
    double far_z = -1.0;
    if (thumbnail_params.show_bed) {
        // extends the near and far z of the frustrum to avoid the bed being clipped
        // box in eye space
        const BoundingBoxf3 t_bed_box = m_bed.extended_bounding_box().transformed(view_matrix);
        near_z = -t_bed_box.max.z();
        far_z = -t_bed_box.min.z();
    }
    camera.apply_projection(volumes_box, near_z, far_z);
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    if (thumbnail_params.transparent_background)
        glsafe(::glClearColor(0.0f, 0.0f, 0.0f, 0.0f));
    glsafe(::glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT));
    glsafe(::glEnable(GL_DEPTH_TEST));
    shader->start_using();
    shader->set_uniform("emission_factor", 0.0f);
    const Transform3d& projection_matrix = camera.get_projection_matrix();
    for (GLVolume* vol : visible_volumes) {
        vol->model.set_color((vol->printable && !vol->is_outside) ? vol->color : ColorRGBA::GRAY());
        // the volume may have been deactivated by an active gizmo
        const bool is_active = vol->is_active;
        vol->is_active = true;
        const Transform3d model_matrix = vol->world_matrix();
        shader->set_uniform("view_model_matrix", view_matrix * model_matrix);
        shader->set_uniform("projection_matrix", projection_matrix);
        const Matrix3d view_normal_matrix = view_matrix.matrix().block(0, 0, 3, 3) * model_matrix.matrix().block(0, 0, 3, 3).inverse().transpose();
        shader->set_uniform("view_normal_matrix", view_normal_matrix);
        vol->render();
        vol->is_active = is_active;
    }
    shader->stop_using();
    glsafe(::glDisable(GL_DEPTH_TEST));
    if (thumbnail_params.show_bed)
        _render_bed(view_matrix, projection_matrix, !camera.is_looking_downward());
    // restore background color
    if (thumbnail_params.transparent_background)
        glsafe(::glClearColor(1.0f, 1.0f, 1.0f, 1.0f));
}
References _render_bed(), Slic3r::GUI::Camera::apply_projection(), Slic3r::GUI::Camera::apply_viewport(), Slic3r::GUI::Bed3D::extended_bounding_box(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), glsafe, Slic3r::ColorRGBA::GRAY(), Slic3r::ThumbnailData::height, Slic3r::GUI::Camera::is_looking_downward(), m_bed, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBox3Base< PointType >::merge(), Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::ThumbnailsParams::parts_only, Slic3r::ThumbnailsParams::printable_only, scene_bounding_box(), Slic3r::GUI::Camera::set_scene_box(), Slic3r::GUI::Camera::set_type(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GUI::Camera::set_viewport(), Slic3r::ThumbnailsParams::show_bed, Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::BoundingBoxf3::transformed(), Slic3r::ThumbnailsParams::transparent_background, Slic3r::GLVolumeCollection::volumes, Slic3r::ThumbnailData::width, and Slic3r::GUI::Camera::zoom_to_box().
Referenced by _render_thumbnail_framebuffer(), _render_thumbnail_framebuffer_ext(), and _render_thumbnail_legacy().
_render_thumbnail_legacy()
void Slic3r::GUI::GLCanvas3D::_render_thumbnail_legacy (ThumbnailData & thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams & thumbnail_params, const GLVolumeCollection & volumes, Camera::EType camera_type) private
{
    // check that thumbnail size does not exceed the default framebuffer size
    const Size& cnv_size = get_canvas_size();
    unsigned int cnv_w = (unsigned int)cnv_size.get_width();
    unsigned int cnv_h = (unsigned int)cnv_size.get_height();
    if (w > cnv_w || h > cnv_h) {
        float ratio = std::min((float)cnv_w / (float)w, (float)cnv_h / (float)h);
        w = (unsigned int)(ratio * (float)w);
        h = (unsigned int)(ratio * (float)h);
    }
    thumbnail_data.set(w, h);
    if (!thumbnail_data.is_valid())
        return;
    _render_thumbnail_internal(thumbnail_data, thumbnail_params, volumes, camera_type);
    glsafe(::glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, (void*)thumbnail_data.pixels.data()));
#if ENABLE_THUMBNAIL_GENERATOR_DEBUG_OUTPUT
    debug_output_thumbnail(thumbnail_data);
#endif // ENABLE_THUMBNAIL_GENERATOR_DEBUG_OUTPUT
    // restore the default framebuffer size to avoid flickering on the 3D scene
    wxGetApp().plater()->get_camera().apply_viewport();
}
References _render_thumbnail_internal(), get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), glsafe, Slic3r::ThumbnailData::is_valid(), Slic3r::ThumbnailData::pixels, and Slic3r::ThumbnailData::set().
Referenced by render_thumbnail().
_render_undo_redo_stack()
bool Slic3r::GUI::GLCanvas3D::_render_undo_redo_stack (const bool is_undo, float pos_x) private
{
    bool action_taken = false;
    ImGuiWrapper* imgui = wxGetApp().imgui();
    imgui->set_next_window_pos(pos_x, m_undoredo_toolbar.get_height(), ImGuiCond_Always, 0.5f, 0.0f);
    std::string title = is_undo ? L("Undo History") : L("Redo History");
    imgui->begin(_(title), ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse);
    int hovered = m_imgui_undo_redo_hovered_pos;
    int selected = -1;
    float em = static_cast<float>(wxGetApp().em_unit());
#if ENABLE_RETINA_GL
  em *= m_retina_helper->get_scale_factor();
#endif
    if (imgui->undo_redo_list(ImVec2(18 * em, 26 * em), is_undo, &string_getter, hovered, selected, m_mouse_wheel))
        m_imgui_undo_redo_hovered_pos = hovered;
    else
        m_imgui_undo_redo_hovered_pos = -1;
    if (selected >= 0) {
        is_undo ? wxGetApp().plater()->undo_to(selected) : wxGetApp().plater()->redo_to(selected);
        action_taken = true;
    }
    imgui->text(wxString::Format(is_undo ? _L_PLURAL("Undo %1$d Action", "Undo %1$d Actions", hovered + 1) : _L_PLURAL("Redo %1$d Action", "Redo %1$d Actions", hovered + 1), hovered + 1));
    imgui->end();
    return action_taken;
}
References _, _L_PLURAL, Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLToolbar::get_height(), ImGuiCond_Always, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, L, m_imgui_undo_redo_hovered_pos, m_mouse_wheel, m_undoredo_toolbar, Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::string_getter(), Slic3r::GUI::ImGuiWrapper::text(), and Slic3r::GUI::ImGuiWrapper::undo_redo_list().
Referenced by _init_undoredo_toolbar().
_render_undoredo_toolbar()
void Slic3r::GUI::GLCanvas3D::_render_undoredo_toolbar () private
{
    if (!m_undoredo_toolbar.is_enabled())
        return;
    const Size cnv_size = get_canvas_size();
    const float top = 0.5f * (float)cnv_size.get_height();
    GLToolbar& collapse_toolbar = wxGetApp().plater()->get_collapse_toolbar();
    const float collapse_toolbar_width = collapse_toolbar.is_enabled() ? collapse_toolbar.get_width() : 0.0f;
    const float left = m_main_toolbar.get_width() - 0.5f * (m_main_toolbar.get_width() + m_undoredo_toolbar.get_width() + collapse_toolbar_width);
    m_undoredo_toolbar.set_position(top, left);
    m_undoredo_toolbar.render(*this);
    if (m_toolbar_highlighter.m_render_arrow)
        m_undoredo_toolbar.render_arrow(*this, m_toolbar_highlighter.m_toolbar_item);
}
References Slic3r::GUI::Size::get_height(), Slic3r::GUI::GLToolbar::get_width(), and Slic3r::GUI::GLToolbar::is_enabled().
_render_view_toolbar()
void Slic3r::GUI::GLCanvas3D::_render_view_toolbar () const private
{
    GLToolbar& view_toolbar = wxGetApp().plater()->get_view_toolbar();
#if ENABLE_RETINA_GL
    const float scale = m_retina_helper->get_scale_factor() * wxGetApp().toolbar_icon_scale();
#if __APPLE__
    view_toolbar.set_scale(scale);
#else // if GTK3
    const float size = int(GLGizmosManager::Default_Icons_Size * scale);
    view_toolbar.set_icons_size(size);
#endif // __APPLE__
#else
    const float size = int(GLGizmosManager::Default_Icons_Size * wxGetApp().toolbar_icon_scale());
    view_toolbar.set_icons_size(size);
#endif // ENABLE_RETINA_GL
    const Size cnv_size = get_canvas_size();
    // places the toolbar on the bottom-left corner of the 3d scene
    const float top = -0.5f * (float)cnv_size.get_height() + view_toolbar.get_height();
    const float left = -0.5f * (float)cnv_size.get_width();
    view_toolbar.set_position(top, left);
    view_toolbar.render(*this);
}
References Slic3r::GUI::GLToolbar::get_height(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLToolbar::render(), scale(), Slic3r::GUI::GLToolbar::set_icons_size(), Slic3r::GUI::GLToolbar::set_position(), and Slic3r::GUI::GLToolbar::set_scale().
_render_volumes_for_picking()
void Slic3r::GUI::GLCanvas3D::_render_volumes_for_picking (const Camera & camera) const private
{
    GLShaderProgram* shader = wxGetApp().get_shader("flat_clip");
    if (shader == nullptr)
        return;
    // do not cull backfaces to show broken geometry, if any
    glsafe(::glDisable(GL_CULL_FACE));
    const Transform3d& view_matrix = camera.get_view_matrix();
    for (size_t type = 0; type < 2; ++ type) {
        GLVolumeWithIdAndZList to_render = volumes_to_render(m_volumes.volumes, (type == 0) ? GLVolumeCollection::ERenderType::Opaque : GLVolumeCollection::ERenderType::Transparent, view_matrix);
        for (const GLVolumeWithIdAndZ& volume : to_render)
          if (!volume.first->disabled && (volume.first->composite_id.volume_id >= 0 || m_render_sla_auxiliaries)) {
            // Object picking mode. Render the object with a color encoding the object index.
                // we reserve color = (0,0,0) for occluders (as the printbed)
                // so we shift volumes' id by 1 to get the proper color
                const unsigned int id = 1 + volume.second.first;
                volume.first->model.set_color(picking_decode(id));
                shader->start_using();
                shader->set_uniform("view_model_matrix", view_matrix * volume.first->world_matrix());
                shader->set_uniform("projection_matrix", camera.get_projection_matrix());
                shader->set_uniform("volume_world_matrix", volume.first->world_matrix());
                shader->set_uniform("z_range", m_volumes.get_z_range());
                shader->set_uniform("clipping_plane", m_volumes.get_clipping_plane());
                volume.first->render();
                shader->stop_using();
          }
    }
    glsafe(::glEnable(GL_CULL_FACE));
}
References Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_view_matrix(), glsafe, Slic3r::GLVolumeCollection::Opaque, Slic3r::picking_decode(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::GLVolumeCollection::Transparent, and Slic3r::volumes_to_render().
Referenced by _rectangular_selection_picking_pass().
_resize()
void Slic3r::GUI::GLCanvas3D::_resize (unsigned int w, unsigned int h) private
{
    if (m_canvas == nullptr && m_context == nullptr)
        return;
    const std::array<unsigned int, 2> new_size = { w, h };
    if (m_old_size == new_size)
        return;
    m_old_size = new_size;
    auto *imgui = wxGetApp().imgui();
    imgui->set_display_size(static_cast<float>(w), static_cast<float>(h));
    const float font_size = 1.5f * wxGetApp().em_unit();
#if ENABLE_RETINA_GL
    imgui->set_scaling(font_size, 1.0f, m_retina_helper->get_scale_factor());
#else
    imgui->set_scaling(font_size, m_canvas->GetContentScaleFactor(), 1.0f);
#endif
    this->request_extra_frame();
    // ensures that this canvas is current
    _set_current();
}
References _set_current(), m_canvas, m_context, m_old_size, request_extra_frame(), Slic3r::GUI::ImGuiWrapper::set_display_size(), and Slic3r::GUI::ImGuiWrapper::set_scaling().
Referenced by _refresh_if_shown_on_screen(), and render().
_set_current()
bool Slic3r::GUI::GLCanvas3D::_set_current () private
{
    return m_context != nullptr && m_canvas->SetCurrent(*m_context);
}
References m_canvas, and m_context.
Referenced by _resize(), load_preview(), load_sla_preview(), on_mouse(), reload_scene(), render(), and reset_volumes().
_set_warning_notification()
void Slic3r::GUI::GLCanvas3D::_set_warning_notification (EWarning warning, bool state) private
{
    enum ErrorType{
        PLATER_WARNING,
        PLATER_ERROR,
        SLICING_ERROR
    };
    std::string text;
    ErrorType error = ErrorType::PLATER_WARNING;
    switch (warning) {
    case EWarning::ObjectOutside:      text = _u8L("An object outside the print area was detected."); break;
    case EWarning::ToolpathOutside:    text = _u8L("A toolpath outside the print area was detected."); error = ErrorType::SLICING_ERROR; break;
    case EWarning::SlaSupportsOutside: text = _u8L("SLA supports outside the print area were detected."); error = ErrorType::PLATER_ERROR; break;
    case EWarning::SomethingNotShown:  text = _u8L("Some objects are not visible during editing."); break;
    case EWarning::ObjectClashed:
        text = _u8L("An object outside the print area was detected.\n"
            "Resolve the current problem to continue slicing.");
        error = ErrorType::PLATER_ERROR;
        break;
    case EWarning::GCodeConflict: {
        const ConflictResultOpt& conflict_result = m_gcode_viewer.get_conflict_result();
        if (!conflict_result.has_value()) { break; }
        std::string objName1 = conflict_result->_objName1;
        std::string objName2 = conflict_result->_objName2;
        double      height = conflict_result->_height;
        int         layer = conflict_result->layer;
        // TRN %3% is name of Object1, %4% is name of Object2
        text = format(_u8L("Conflicts in G-code paths have been detected at layer %1%, z=%2$.2f mm. Please reposition the conflicting objects (%3% <-> %4%) further apart."),
                      layer, height, objName1, objName2);
        error = ErrorType::SLICING_ERROR;
        break;
    }
    }
    auto& notification_manager = *wxGetApp().plater()->get_notification_manager();
    const ConflictResultOpt& conflict_result = m_gcode_viewer.get_conflict_result();
    if (warning == EWarning::GCodeConflict) {
        if (conflict_result.has_value()) {
            const PrintObject* obj2 = reinterpret_cast<const PrintObject*>(conflict_result->_obj2);
            auto     mo = obj2->model_object();
            ObjectID id = mo->id();
            int layer_id = conflict_result->layer;
            auto     action_fn = [id, layer_id](wxEvtHandler*) {
                auto& objects = wxGetApp().model().objects;
                auto  iter = id.id ? std::find_if(objects.begin(), objects.end(), [id](auto o) { return o->id() == id; }) : objects.end();
                if (iter != objects.end()) {
                    const unsigned int obj_idx = std::distance(objects.begin(), iter);
                    wxGetApp().CallAfter([obj_idx, layer_id]() {
                        wxGetApp().plater()->set_preview_layers_slider_values_range(0, layer_id - 1);
                        wxGetApp().plater()->select_view_3D("3D");
                        wxGetApp().plater()->canvas3D()->reset_all_gizmos();
                        wxGetApp().plater()->canvas3D()->get_selection().add_object(obj_idx, true);
                        wxGetApp().obj_list()->update_selections();
                    });
                }
                return false;
            };
            auto hypertext = _u8L("Jump to");
            hypertext += std::string(" [") + mo->name + "]";
            notification_manager.push_notification(NotificationType::SlicingError, NotificationManager::NotificationLevel::ErrorNotificationLevel,
                _u8L("ERROR:") + "\n" + text, hypertext, action_fn);
        }
        else
            notification_manager.close_slicing_error_notification(text);
        return;
    }
    switch (error)
    {
    case PLATER_WARNING:
        if (state)
            notification_manager.push_plater_warning_notification(text);
        else
            notification_manager.close_plater_warning_notification(text);
        break;
    case PLATER_ERROR:
        if (state)
            notification_manager.push_plater_error_notification(text);
        else
            notification_manager.close_plater_error_notification(text);
        break;
    case SLICING_ERROR:
        if (state)
            notification_manager.push_slicing_error_notification(text);
        else
            notification_manager.close_slicing_error_notification(text);
        break;
    default:
        break;
    }
}
References _u8L, error, Slic3r::format(), Slic3r::ObjectID::id, and Slic3r::PrintObjectBase::model_object().
Referenced by reload_scene(), reset_volumes(), and toggle_model_objects_visibility().
_set_warning_notification_if_needed()
void Slic3r::GUI::GLCanvas3D::_set_warning_notification_if_needed (EWarning warning) private
{
    _set_current();
    bool show = false;
    if (!m_volumes.empty()) {
        if (current_printer_technology() == ptSLA) {
            const auto [res, volume] = _is_any_volume_outside();
            if (res) {
                if (warning == EWarning::ObjectClashed)
                    show = !volume->is_sla_support();
                else if (warning == EWarning::SlaSupportsOutside)
                    show = volume->is_sla_support();
            }
        }
        else
            show = _is_any_volume_outside().first;
    }
    else {
        if (wxGetApp().is_editor()) {
            if (current_printer_technology() != ptSLA) {
                if (warning == EWarning::ToolpathOutside)
                    show = m_gcode_viewer.has_data() && !m_gcode_viewer.is_contained_in_bed();
                else if (warning == EWarning::GCodeConflict)
                    show = m_gcode_viewer.has_data() && m_gcode_viewer.is_contained_in_bed() && m_gcode_viewer.get_conflict_result().has_value();
            }
        }
    }
    _set_warning_notification(warning, show);
}
References Slic3r::ptSLA.
Referenced by load_gcode_preview(), load_preview(), and load_sla_preview().
_start_timer()
void Slic3r::GUI::GLCanvas3D::_start_timer () private
{
    m_timer.Start(100, wxTIMER_CONTINUOUS);
}
_stop_timer()
void Slic3r::GUI::GLCanvas3D::_stop_timer () private
{
    m_timer.Stop();
}
Referenced by on_mouse().
_update_camera_zoom()
void Slic3r::GUI::GLCanvas3D::_update_camera_zoom (double zoom) private
{
    wxGetApp().plater()->get_camera().update_zoom(zoom);
    m_dirty = true;
}
References m_dirty.
Referenced by on_char(), and on_mouse_wheel().
_update_selection_from_hover()
void Slic3r::GUI::GLCanvas3D::_update_selection_from_hover () private
{
    bool ctrl_pressed = wxGetKeyState(WXK_CONTROL);
    bool selection_changed = false;
    if (m_hover_volume_idxs.empty()) {
        if (!ctrl_pressed && m_rectangle_selection.get_state() == GLSelectionRectangle::EState::Select) {
            selection_changed = ! m_selection.is_empty();
            m_selection.remove_all();
        }
    }
    GLSelectionRectangle::EState state = m_rectangle_selection.get_state();
    bool hover_modifiers_only = true;
    for (int i : m_hover_volume_idxs) {
        if (!m_volumes.volumes[i]->is_modifier) {
            hover_modifiers_only = false;
            break;
        }
    }
    if (!m_rectangle_selection.is_empty()) {
        if (state == GLSelectionRectangle::EState::Select) {
            bool contains_all = true;
            for (int i : m_hover_volume_idxs) {
                if (!m_selection.contains_volume((unsigned int)i)) {
                    contains_all = false;
                    break;
                }
            }
            // the selection is going to be modified (Add)
            if (!contains_all) {
                wxGetApp().plater()->take_snapshot(_L("Selection-Add from rectangle"), UndoRedo::SnapshotType::Selection);
                selection_changed = true;
            }
        }
        else {
            bool contains_any = false;
            for (int i : m_hover_volume_idxs) {
                if (m_selection.contains_volume((unsigned int)i)) {
                    contains_any = true;
                    break;
                }
            }
            // the selection is going to be modified (Remove)
            if (contains_any) {
                wxGetApp().plater()->take_snapshot(_L("Selection-Remove from rectangle"), UndoRedo::SnapshotType::Selection);
                selection_changed = true;
            }
        }
    }
    if (!selection_changed)
        return;
    Plater::SuppressSnapshots suppress(wxGetApp().plater());
    if (state == GLSelectionRectangle::EState::Select && !ctrl_pressed)
        m_selection.clear();
    for (int i : m_hover_volume_idxs) {
        if (state == GLSelectionRectangle::EState::Select) {
            if (hover_modifiers_only) {
                const GLVolume& v = *m_volumes.volumes[i];
                m_selection.add_volume(v.object_idx(), v.volume_idx(), v.instance_idx(), false);
            }
            else
                m_selection.add(i, false);
        }
        else
            m_selection.remove(i);
    }
    if (m_selection.is_empty())
        m_gizmos.reset_all_states();
    else
        m_gizmos.refresh_on_off_state();
    m_gizmos.update_data();
    post_event(SimpleEvent(EVT_GLCANVAS_OBJECT_SELECT));
    m_dirty = true;
}
References _L, Slic3r::GLVolume::instance_idx(), Slic3r::GLVolume::object_idx(), and Slic3r::GLVolume::volume_idx().
Referenced by on_key(), and on_mouse().
_update_sla_shells_outside_state()
void Slic3r::GUI::GLCanvas3D::_update_sla_shells_outside_state () private
{
    check_volumes_outside_state();
}
Referenced by load_sla_preview().
_update_volumes_hover_state()
void Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state () private
{
    // skip update if the Gizmo Measure is active
    if (m_gizmos.get_current_type() == GLGizmosManager::Measure)
        return;
    for (GLVolume* v : m_volumes.volumes) {
        v->hover = GLVolume::HS_None;
    }
    if (m_hover_volume_idxs.empty())
        return;
    const bool ctrl_pressed  = wxGetKeyState(WXK_CONTROL);
    const bool shift_pressed = wxGetKeyState(WXK_SHIFT);
    const bool alt_pressed   = wxGetKeyState(WXK_ALT);
    if (alt_pressed && (shift_pressed || ctrl_pressed)) {
        // illegal combinations of keys
        m_hover_volume_idxs.clear();
        return;
    }
    bool hover_modifiers_only = true;
    for (int i : m_hover_volume_idxs) {
        if (!m_volumes.volumes[i]->is_modifier) {
            hover_modifiers_only = false;
            break;
        }
    }
    std::set<std::pair<int, int>> hover_instances;
    for (int i : m_hover_volume_idxs) {
        const GLVolume& v = *m_volumes.volumes[i];
        hover_instances.insert(std::make_pair(v.object_idx(), v.instance_idx()));
    }
    bool hover_from_single_instance = hover_instances.size() == 1;
    if (hover_modifiers_only && !hover_from_single_instance) {
        // do not allow to select volumes from different instances
        m_hover_volume_idxs.clear();
        return;
    }
    for (int i : m_hover_volume_idxs) {
        GLVolume& volume = *m_volumes.volumes[i];
        if (volume.hover != GLVolume::HS_None)
            continue;
        const bool deselect = volume.selected && ((shift_pressed && m_rectangle_selection.is_empty()) || (alt_pressed && !m_rectangle_selection.is_empty()));
        const bool select   = !volume.selected && (m_rectangle_selection.is_empty() || (shift_pressed && !m_rectangle_selection.is_empty()));
        if (select || deselect) {
            const bool as_volume =
                volume.is_modifier && hover_from_single_instance && !ctrl_pressed &&
                (
                !deselect ||
                (deselect && !m_selection.is_single_full_instance() && volume.object_idx() == m_selection.get_object_idx() && volume.instance_idx() == m_selection.get_instance_idx())
                );
            if (as_volume)
                volume.hover = deselect ? GLVolume::HS_Deselect : GLVolume::HS_Select;
            else {
                const int object_idx = volume.object_idx();
                const int instance_idx = volume.instance_idx();
                for (GLVolume* v : m_volumes.volumes) {
                    if (v->object_idx() == object_idx && v->instance_idx() == instance_idx)
                        v->hover = deselect ? GLVolume::HS_Deselect : GLVolume::HS_Select;
                }
            }
        }
        else if (volume.selected)
            volume.hover = GLVolume::HS_Hover;
    }
}
References Slic3r::GLVolume::HS_Deselect, Slic3r::GLVolume::HS_Hover, Slic3r::GLVolume::HS_None, Slic3r::GLVolume::HS_Select, Slic3r::GLVolume::instance_idx(), and Slic3r::GLVolume::object_idx().
Referenced by _picking_pass().
_zoom_to_box()
void Slic3r::GUI::GLCanvas3D::_zoom_to_box (const BoundingBoxf3 & box, double margin_factor = DefaultCameraZoomToBoxMarginFactor) private
{
    wxGetApp().plater()->get_camera().zoom_to_box(box, margin_factor);
    m_dirty = true;
}
References m_dirty.
Referenced by on_char(), zoom_to_bed(), zoom_to_gcode(), zoom_to_selection(), and zoom_to_volumes().
adaptive_layer_height_profile()
void Slic3r::GUI::GLCanvas3D::adaptive_layer_height_profile (float quality_factor)
{
    wxGetApp().plater()->take_snapshot(_L("Variable layer height - Adaptive"));
    m_layers_editing.adaptive_layer_height_profile(*this, quality_factor);
    m_layers_editing.state = LayersEditing::Completed;
    m_dirty = true;
}
References _L, Slic3r::GUI::GLCanvas3D::LayersEditing::adaptive_layer_height_profile(), Slic3r::GUI::GLCanvas3D::LayersEditing::Completed, m_dirty, m_layers_editing, and Slic3r::GUI::GLCanvas3D::LayersEditing::state.
add_raycaster_for_picking()
std::shared_ptr< SceneRaycasterItem > Slic3r::GUI::GLCanvas3D::add_raycaster_for_picking (SceneRaycaster::EType type, int id, const MeshRaycaster & raycaster, const Transform3d & trafo = Transform3d::Identity(), bool use_back_faces = false) inline
{
        return m_scene_raycaster.add_raycaster(type, id, raycaster, trafo, use_back_faces);
    }
References Slic3r::GUI::SceneRaycaster::add_raycaster(), and m_scene_raycaster.
Referenced by Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoHollow::register_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::register_point_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaBase::register_volume_raycasters_for_picking(), reload_scene(), and Slic3r::GUI::GLGizmoBase::Grabber::render().
allow_multisample()
void Slic3r::GUI::GLCanvas3D::allow_multisample (bool allow)
{
    m_multisample_allowed = allow;
}
References m_multisample_allowed.
Referenced by Slic3r::GUI::Preview::init(), and Slic3r::GUI::View3D::init().
apply_retina_scale()
void Slic3r::GUI::GLCanvas3D::apply_retina_scale (Vec2d & screen_coordinate) const
{
#if ENABLE_RETINA_GL
    double scale = static_cast<double>(m_retina_helper->get_scale_factor());
    screen_coordinate *= scale;
#endif // ENABLE_RETINA_GL
}
References scale().
Referenced by Slic3r::GUI::Plater::priv::on_right_click().
are_labels_shown()
bool Slic3r::GUI::GLCanvas3D::are_labels_shown () const inline
{ return m_labels.is_shown(); }
References Slic3r::GUI::GLCanvas3D::Labels::is_shown(), and m_labels.
Referenced by Slic3r::GUI::Plater::priv::are_view3D_labels_shown().
bed_shape_changed()
void Slic3r::GUI::GLCanvas3D::bed_shape_changed ()
{
    refresh_camera_scene_box();
    wxGetApp().plater()->get_camera().requires_zoom_to_bed = true;
    m_dirty = true;
}
References m_dirty, and refresh_camera_scene_box().
Referenced by Slic3r::GUI::View3D::bed_shape_changed(), and Slic3r::GUI::Preview::bed_shape_changed().
bind_event_handlers()
void Slic3r::GUI::GLCanvas3D::bind_event_handlers ()
{
    if (m_canvas != nullptr) {
        m_canvas->Bind(wxEVT_SIZE, &GLCanvas3D::on_size, this);
        m_canvas->Bind(wxEVT_IDLE, &GLCanvas3D::on_idle, this);
        m_canvas->Bind(wxEVT_CHAR, &GLCanvas3D::on_char, this);
        m_canvas->Bind(wxEVT_KEY_DOWN, &GLCanvas3D::on_key, this);
        m_canvas->Bind(wxEVT_KEY_UP, &GLCanvas3D::on_key, this);
        m_canvas->Bind(wxEVT_MOUSEWHEEL, &GLCanvas3D::on_mouse_wheel, this);
        m_canvas->Bind(wxEVT_TIMER, &GLCanvas3D::on_timer, this);
        m_canvas->Bind(EVT_GLCANVAS_RENDER_TIMER, &GLCanvas3D::on_render_timer, this);
        m_toolbar_highlighter.set_timer_owner(m_canvas, 0);
        m_canvas->Bind(EVT_GLCANVAS_TOOLBAR_HIGHLIGHTER_TIMER, [this](wxTimerEvent&) { m_toolbar_highlighter.blink(); });
        m_gizmo_highlighter.set_timer_owner(m_canvas, 0);
        m_canvas->Bind(EVT_GLCANVAS_GIZMO_HIGHLIGHTER_TIMER, [this](wxTimerEvent&) { m_gizmo_highlighter.blink(); });
        m_canvas->Bind(wxEVT_LEFT_DOWN, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_LEFT_UP, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_MIDDLE_DOWN, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_MIDDLE_UP, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_RIGHT_DOWN, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_RIGHT_UP, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_MOTION, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_ENTER_WINDOW, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_LEAVE_WINDOW, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_LEFT_DCLICK, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_MIDDLE_DCLICK, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_RIGHT_DCLICK, &GLCanvas3D::on_mouse, this);
        m_canvas->Bind(wxEVT_PAINT, &GLCanvas3D::on_paint, this);
        m_canvas->Bind(wxEVT_SET_FOCUS, &GLCanvas3D::on_set_focus, this);
        m_event_handlers_bound = true;
    }
}
References Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::blink(), Slic3r::GUI::GLCanvas3D::GizmoHighlighter::blink(), m_canvas, m_event_handlers_bound, m_gizmo_highlighter, m_toolbar_highlighter, on_char(), on_idle(), on_key(), on_mouse(), on_mouse_wheel(), on_paint(), on_render_timer(), on_set_focus(), on_size(), on_timer(), Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::set_timer_owner(), and Slic3r::GUI::GLCanvas3D::GizmoHighlighter::set_timer_owner().
check_volumes_outside_state() [1/2]
ModelInstanceEPrintVolumeState Slic3r::GUI::GLCanvas3D::check_volumes_outside_state (bool selection_only = true) const
{
    ModelInstanceEPrintVolumeState state = ModelInstanceEPrintVolumeState::ModelInstancePVS_Inside;
    if (m_initialized && !m_volumes.empty())
        check_volumes_outside_state(m_bed.build_volume(), &state, selection_only);
    return state;
}
References Slic3r::GUI::Bed3D::build_volume(), check_volumes_outside_state(), Slic3r::GLVolumeCollection::empty(), m_bed, m_initialized, m_volumes, and Slic3r::ModelInstancePVS_Inside.
Referenced by check_volumes_outside_state(), reload_scene(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
check_volumes_outside_state() [2/2]
bool Slic3r::GUI::GLCanvas3D::check_volumes_outside_state (const Slic3r::BuildVolume & build_volume, ModelInstanceEPrintVolumeState * out_state, bool selection_only = true) const
{
    auto                volume_below = [](GLVolume& volume) -> bool
    { return volume.object_idx() != -1 && volume.volume_idx() != -1 && volume.is_below_printbed(); };
    // Volume is partially below the print bed, thus a pre-calculated convex hull cannot be used.
    auto                volume_sinking = [](GLVolume& volume) -> bool
    { return volume.object_idx() != -1 && volume.volume_idx() != -1 && volume.is_sinking(); };
    // Cached bounding box of a volume above the print bed.
    auto                volume_bbox = [volume_sinking](GLVolume& volume) -> BoundingBoxf3
    { return volume_sinking(volume) ? volume.transformed_non_sinking_bounding_box() : volume.transformed_convex_hull_bounding_box(); };
    // Cached 3D convex hull of a volume above the print bed.
    auto                volume_convex_mesh = [this, volume_sinking](GLVolume& volume) -> const TriangleMesh&
    { return volume_sinking(volume) ? m_model->objects[volume.object_idx()]->volumes[volume.volume_idx()]->mesh() : *volume.convex_hull(); };
    auto volumes_to_process_idxs = [this, selection_only]() {
        std::vector<unsigned int> ret;
        if (!selection_only || m_selection.is_empty()) {
            ret = std::vector<unsigned int>(m_volumes.volumes.size());
            std::iota(ret.begin(), ret.end(), 0);
        }
        else {
            const GUI::Selection::IndicesList& selected_volume_idxs = m_selection.get_volume_idxs();
            ret.assign(selected_volume_idxs.begin(), selected_volume_idxs.end());
        }
        return ret;
    };
    ModelInstanceEPrintVolumeState overall_state = ModelInstancePVS_Inside;
    bool contained_min_one = false;
    const std::vector<unsigned int> volumes_idxs = volumes_to_process_idxs();
    for (unsigned int vol_idx : volumes_idxs) {
        GLVolume* volume = m_volumes.volumes[vol_idx];
        if (!volume->is_modifier && (volume->shader_outside_printer_detection_enabled || (!volume->is_wipe_tower && volume->composite_id.volume_id >= 0))) {
            BuildVolume::ObjectState state;
            if (volume_below(*volume))
                state = BuildVolume::ObjectState::Below;
            else {
                switch (build_volume.type()) {
                case BuildVolume::Type::Rectangle:
                    //FIXME this test does not evaluate collision of a build volume bounding box with non-convex objects.
                    state = build_volume.volume_state_bbox(volume_bbox(*volume));
                    break;
                case BuildVolume::Type::Circle:
                case BuildVolume::Type::Convex:
                    //FIXME doing test on convex hull until we learn to do test on non-convex polygons efficiently.
                case BuildVolume::Type::Custom:
                    state = build_volume.object_state(volume_convex_mesh(*volume).its, volume->world_matrix().cast<float>(), volume_sinking(*volume));
                    break;
                default:
                    // Ignore, don't produce any collision.
                    state = BuildVolume::ObjectState::Inside;
                    break;
                }
                assert(state != BuildVolume::ObjectState::Below);
            }
            volume->is_outside = state != BuildVolume::ObjectState::Inside;
            if (volume->printable) {
                if (overall_state == ModelInstancePVS_Inside && volume->is_outside)
                    overall_state = ModelInstancePVS_Fully_Outside;
                if (overall_state == ModelInstancePVS_Fully_Outside && volume->is_outside && state == BuildVolume::ObjectState::Colliding)
                    overall_state = ModelInstancePVS_Partly_Outside;
                contained_min_one |= !volume->is_outside;
            }
        }
    }
    for (unsigned int vol_idx = 0; vol_idx < m_volumes.volumes.size(); ++vol_idx) {
        if (std::find(volumes_idxs.begin(), volumes_idxs.end(), vol_idx) == volumes_idxs.end()) {
            if (!m_volumes.volumes[vol_idx]->is_outside) {
                contained_min_one = true;
                break;
            }
        }
    }
    if (out_state != nullptr)
        *out_state = overall_state;
    return contained_min_one;
}
References Slic3r::BuildVolume::Below, Slic3r::BuildVolume::Circle, Slic3r::BuildVolume::Colliding, Slic3r::BuildVolume::Convex, Slic3r::BuildVolume::Custom, Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::BuildVolume::Inside, Slic3r::GUI::Selection::is_empty(), m_model, m_selection, m_volumes, Slic3r::ModelInstancePVS_Fully_Outside, Slic3r::ModelInstancePVS_Inside, Slic3r::ModelInstancePVS_Partly_Outside, Slic3r::BuildVolume::object_state(), Slic3r::Model::objects, Slic3r::BuildVolume::Rectangle, Slic3r::BuildVolume::type(), Slic3r::BuildVolume::volume_state_bbox(), and Slic3r::GLVolumeCollection::volumes.
clear_popup_menu_position()
void Slic3r::GUI::GLCanvas3D::clear_popup_menu_position () inline
{ m_popup_menu_positon.reset(); }
References m_popup_menu_positon.
Referenced by Slic3r::GUI::Plater::priv::on_right_click().
current_printer_technology()
PrinterTechnology Slic3r::GUI::GLCanvas3D::current_printer_technology () const
{
    return m_process->current_printer_technology();
}
References Slic3r::BackgroundSlicingProcess::current_printer_technology(), and m_process.
Referenced by _init_main_toolbar(), _render_arrange_menu(), Slic3r::GUI::GLGizmosManager::activate_gizmo(), do_move(), do_rotate(), do_scale(), on_mouse(), reload_scene(), render(), toggle_sla_auxiliaries_visibility(), update_sequential_clearance(), and update_tooltip_for_settings_item_in_main_toolbar().
delete_selected()
void Slic3r::GUI::GLCanvas3D::delete_selected ()
{
    m_selection.erase();
}
References Slic3r::GUI::Selection::erase(), and m_selection.
Referenced by Slic3r::GUI::View3D::delete_selected().
deselect_all()
void Slic3r::GUI::GLCanvas3D::deselect_all ()
{
    if (m_selection.is_empty())
        return;
    // close actual opened gizmo before deselection(m_selection.remove_all()) write to undo/redo snapshot
    if (GLGizmosManager::EType current_type = m_gizmos.get_current_type();
        current_type != GLGizmosManager::Undefined)
        m_gizmos.open_gizmo(current_type);
    m_selection.remove_all();
    wxGetApp().obj_manipul()->set_dirty();
    m_gizmos.reset_all_states();
    m_gizmos.update_data();
    post_event(SimpleEvent(EVT_GLCANVAS_OBJECT_SELECT));
}
References Slic3r::GUI::GLGizmosManager::get_current_type(), Slic3r::GUI::Selection::is_empty(), m_gizmos, m_selection, Slic3r::GUI::GLGizmosManager::open_gizmo(), post_event(), Slic3r::GUI::Selection::remove_all(), Slic3r::GUI::GLGizmosManager::reset_all_states(), Slic3r::GUI::GLGizmosManager::Undefined, and Slic3r::GUI::GLGizmosManager::update_data().
Referenced by Slic3r::GUI::View3D::deselect_all(), on_char(), and on_mouse().
detect_sla_view_type()
void Slic3r::GUI::GLCanvas3D::detect_sla_view_type ()
{
    m_sla_view.detect_type_from_volumes(m_volumes.volumes);
    m_sla_view.update_volumes_visibility(m_volumes.volumes);
    m_dirty = true;
}
References Slic3r::GUI::GLCanvas3D::SLAView::detect_type_from_volumes(), m_dirty, m_sla_view, m_volumes, Slic3r::GUI::GLCanvas3D::SLAView::update_volumes_visibility(), and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
do_mirror()
void Slic3r::GUI::GLCanvas3D::do_mirror (const std::string & snapshot_type)
{
    if (m_model == nullptr)
        return;
    if (!snapshot_type.empty())
        wxGetApp().plater()->take_snapshot(_(snapshot_type));
    // stores current min_z of instances
    std::map<std::pair<int, int>, double> min_zs;
    if (!snapshot_type.empty()) {
        for (int i = 0; i < static_cast<int>(m_model->objects.size()); ++i) {
            const ModelObject* obj = m_model->objects[i];
            for (int j = 0; j < static_cast<int>(obj->instances.size()); ++j) {
                min_zs[{ i, j }] = obj->instance_bounding_box(j).min.z();
            }
        }
    }
    std::set<std::pair<int, int>> done;  // keeps track of modified instances
    Selection::EMode selection_mode = m_selection.get_mode();
    for (const GLVolume* v : m_volumes.volumes) {
        int object_idx = v->object_idx();
        if (object_idx < 0 || (int)m_model->objects.size() <= object_idx)
            continue;
        int instance_idx = v->instance_idx();
        int volume_idx = v->volume_idx();
        done.insert(std::pair<int, int>(object_idx, instance_idx));
        // Mirror instances/volumes
        ModelObject* model_object = m_model->objects[object_idx];
        if (model_object != nullptr) {
            if (selection_mode == Selection::Instance)
                model_object->instances[instance_idx]->set_transformation(v->get_instance_transformation());
            else if (selection_mode == Selection::Volume)
                model_object->volumes[volume_idx]->set_transformation(v->get_volume_transformation());
            model_object->invalidate_bounding_box();
        }
    }
    // Fixes sinking/flying instances
    std::set<int> obj_idx_for_update_info_items;
    for (const std::pair<int, int>& i : done) {
        ModelObject* m = m_model->objects[i.first];
        double shift_z = m->get_instance_min_z(i.second);
        // leave sinking instances as sinking
        if (min_zs.empty() || min_zs.find({ i.first, i.second })->second >= SINKING_Z_THRESHOLD || shift_z > SINKING_Z_THRESHOLD) {
            Vec3d shift(0.0, 0.0, -shift_z);
            m_selection.translate(i.first, i.second, shift);
            m->translate_instance(i.second, shift);
        }
        obj_idx_for_update_info_items.emplace(i.first);
    }
    //update sinking information in ObjectList
    for (int id : obj_idx_for_update_info_items)
        wxGetApp().obj_list()->update_info_items(static_cast<size_t>(id));
    post_event(SimpleEvent(EVT_GLCANVAS_SCHEDULE_BACKGROUND_PROCESS));
    m_dirty = true;
}
References _, done, Slic3r::ModelObject::get_instance_min_z(), Slic3r::GUI::Selection::get_mode(), Slic3r::GUI::Selection::Instance, Slic3r::ModelObject::instance_bounding_box(), Slic3r::ModelObject::instances, Slic3r::ModelObject::invalidate_bounding_box(), m_dirty, m_model, m_selection, m_volumes, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::Model::objects, post_event(), Slic3r::SINKING_Z_THRESHOLD, Slic3r::GUI::Selection::translate(), Slic3r::ModelObject::translate_instance(), Slic3r::GUI::Selection::Volume, Slic3r::ModelObject::volumes, and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), and mirror_selection().
do_move()
void Slic3r::GUI::GLCanvas3D::do_move (const std::string & snapshot_type)
{
    if (m_model == nullptr)
        return;
    if (!snapshot_type.empty())
        wxGetApp().plater()->take_snapshot(_(snapshot_type));
    std::set<std::pair<int, int>> done;  // keeps track of modified instances
    bool object_moved = false;
    Vec3d wipe_tower_origin = Vec3d::Zero();
    Selection::EMode selection_mode = m_selection.get_mode();
    for (const GLVolume* v : m_volumes.volumes) {
        int object_idx = v->object_idx();
        int instance_idx = v->instance_idx();
        int volume_idx = v->volume_idx();
        if (volume_idx < 0)
            continue;
        std::pair<int, int> done_id(object_idx, instance_idx);
        if (0 <= object_idx && object_idx < (int)m_model->objects.size()) {
            done.insert(done_id);
            // Move instances/volumes
            ModelObject* model_object = m_model->objects[object_idx];
            if (model_object != nullptr) {
                if (selection_mode == Selection::Instance)
                    model_object->instances[instance_idx]->set_transformation(v->get_instance_transformation());
                else if (selection_mode == Selection::Volume)
                    model_object->volumes[volume_idx]->set_transformation(v->get_volume_transformation());
                object_moved = true;
                model_object->invalidate_bounding_box();
            }
        }
        else if (v->is_wipe_tower)
            // Move a wipe tower proxy.
            wipe_tower_origin = v->get_volume_offset();
    }
    // Fixes flying instances
    std::set<int> obj_idx_for_update_info_items;
    for (const std::pair<int, int>& i : done) {
        ModelObject* m = m_model->objects[i.first];
        const double shift_z = m->get_instance_min_z(i.second);
        if (current_printer_technology() == ptSLA || shift_z > SINKING_Z_THRESHOLD) {
            const Vec3d shift(0.0, 0.0, -shift_z);
            m_selection.translate(i.first, i.second, shift);
            m->translate_instance(i.second, shift);
        }
        obj_idx_for_update_info_items.emplace(i.first);
    }
    //update sinking information in ObjectList
    for (int id : obj_idx_for_update_info_items)
        wxGetApp().obj_list()->update_info_items(static_cast<size_t>(id));
    // if the selection is not valid to allow for layer editing after the move, we need to turn off the tool if it is running
    // similar to void Plater::priv::selection_changed()
    if (!wxGetApp().plater()->can_layers_editing() && is_layers_editing_enabled())
        post_event(SimpleEvent(EVT_GLTOOLBAR_LAYERSEDITING));
    if (object_moved)
        post_event(SimpleEvent(EVT_GLCANVAS_INSTANCE_MOVED));
    if (wipe_tower_origin != Vec3d::Zero())
        post_event(Vec3dEvent(EVT_GLCANVAS_WIPETOWER_MOVED, std::move(wipe_tower_origin)));
    if (current_printer_technology() == ptFFF && fff_print()->config().complete_objects) {
        update_sequential_clearance(true);
        m_sequential_print_clearance.m_evaluating = true;
    }
    m_dirty = true;
}
References _, current_printer_technology(), done, fff_print(), Slic3r::ModelObject::get_instance_min_z(), Slic3r::GUI::Selection::get_mode(), Slic3r::GUI::Selection::Instance, Slic3r::ModelObject::instances, Slic3r::ModelObject::invalidate_bounding_box(), is_layers_editing_enabled(), m_dirty, Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_evaluating, m_model, m_selection, m_sequential_print_clearance, m_volumes, Slic3r::Model::objects, post_event(), Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::SINKING_Z_THRESHOLD, Slic3r::GUI::Selection::translate(), Slic3r::ModelObject::translate_instance(), update_sequential_clearance(), Slic3r::GUI::Selection::Volume, Slic3r::ModelObject::volumes, and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::GLGizmoEmboss::do_translate(), on_key(), on_mouse(), Slic3r::GUI::on_mouse_surface_drag(), and Slic3r::GUI::GLGizmoMove3D::on_stop_dragging().
do_reset_skew()
void Slic3r::GUI::GLCanvas3D::do_reset_skew (const std::string & snapshot_type)
{
    if (m_model == nullptr)
        return;
    if (!snapshot_type.empty())
        wxGetApp().plater()->take_snapshot(_(snapshot_type));
    // stores current min_z of instances
    std::map<std::pair<int, int>, double> min_zs;
    if (!snapshot_type.empty()) {
        for (int i = 0; i < static_cast<int>(m_model->objects.size()); ++i) {
            const ModelObject* obj = m_model->objects[i];
            for (int j = 0; j < static_cast<int>(obj->instances.size()); ++j) {
                min_zs[{ i, j }] = obj->instance_bounding_box(j).min.z();
            }
        }
    }
    std::set<std::pair<int, int>> done;  // keeps track of modified instances
    Selection::EMode selection_mode = m_selection.get_mode();
    for (const GLVolume* v : m_volumes.volumes) {
        int object_idx = v->object_idx();
        if (object_idx < 0 || (int)m_model->objects.size() <= object_idx)
            continue;
        int instance_idx = v->instance_idx();
        int volume_idx = v->volume_idx();
        done.insert(std::pair<int, int>(object_idx, instance_idx));
        // Mirror instances/volumes
        ModelObject* model_object = m_model->objects[object_idx];
        if (model_object != nullptr) {
            if (selection_mode == Selection::Instance)
                model_object->instances[instance_idx]->set_transformation(v->get_instance_transformation());
            else if (selection_mode == Selection::Volume)
                model_object->volumes[volume_idx]->set_transformation(v->get_volume_transformation());
            model_object->invalidate_bounding_box();
        }
    }
    // Fixes sinking/flying instances
    std::set<int> obj_idx_for_update_info_items;
    for (const std::pair<int, int>& i : done) {
        ModelObject* m = m_model->objects[i.first];
        double shift_z = m->get_instance_min_z(i.second);
        // leave sinking instances as sinking
        if (min_zs.empty() || min_zs.find({ i.first, i.second })->second >= SINKING_Z_THRESHOLD || shift_z > SINKING_Z_THRESHOLD) {
            Vec3d shift(0.0, 0.0, -shift_z);
            m_selection.translate(i.first, i.second, shift);
            m->translate_instance(i.second, shift);
        }
        obj_idx_for_update_info_items.emplace(i.first);
    }
    //update sinking information in ObjectList
    for (int id : obj_idx_for_update_info_items)
        wxGetApp().obj_list()->update_info_items(static_cast<size_t>(id));
    post_event(SimpleEvent(EVT_GLCANVAS_RESET_SKEW));
    m_dirty = true;
}
References _, done, Slic3r::ModelObject::get_instance_min_z(), Slic3r::GUI::Selection::get_mode(), Slic3r::GUI::Selection::Instance, Slic3r::ModelObject::instance_bounding_box(), Slic3r::ModelObject::instances, Slic3r::ModelObject::invalidate_bounding_box(), m_dirty, m_model, m_selection, m_volumes, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::Model::objects, post_event(), Slic3r::SINKING_Z_THRESHOLD, Slic3r::GUI::Selection::translate(), Slic3r::ModelObject::translate_instance(), Slic3r::GUI::Selection::Volume, Slic3r::ModelObject::volumes, and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation().
do_rotate()
void Slic3r::GUI::GLCanvas3D::do_rotate (const std::string & snapshot_type)
{
    if (m_model == nullptr)
        return;
    if (!snapshot_type.empty())
        wxGetApp().plater()->take_snapshot(_(snapshot_type));
    // stores current min_z of instances
    std::map<std::pair<int, int>, double> min_zs;
    for (int i = 0; i < static_cast<int>(m_model->objects.size()); ++i) {
        const ModelObject* obj = m_model->objects[i];
        for (int j = 0; j < static_cast<int>(obj->instances.size()); ++j) {
            if (snapshot_type == L("Gizmo-Place on Face") && m_selection.get_object_idx() == i) {
                // This means we are flattening this object. In that case pretend
                // that it is not sinking (even if it is), so it is placed on bed
                // later on (whatever is sinking will be left sinking).
                min_zs[{ i, j }] = SINKING_Z_THRESHOLD;
            }
            else
                min_zs[{ i, j }] = obj->instance_bounding_box(j).min.z();
        }
    }
    std::set<std::pair<int, int>> done;  // keeps track of modified instances
    Selection::EMode selection_mode = m_selection.get_mode();
    for (const GLVolume* v : m_volumes.volumes) {
        if (v->is_wipe_tower) {
            const Vec3d offset = v->get_volume_offset();
            Vec3d rot_unit_x = v->get_volume_transformation().get_matrix().linear() * Vec3d::UnitX();
            double z_rot = std::atan2(rot_unit_x.y(), rot_unit_x.x());
            post_event(Vec3dEvent(EVT_GLCANVAS_WIPETOWER_ROTATED, Vec3d(offset.x(), offset.y(), z_rot)));
        }
        const int object_idx = v->object_idx();
        if (object_idx < 0 || (int)m_model->objects.size() <= object_idx)
            continue;
        const int instance_idx = v->instance_idx();
        const int volume_idx = v->volume_idx();
        if (volume_idx < 0)
            continue;
        done.insert(std::pair<int, int>(object_idx, instance_idx));
        // Rotate instances/volumes.
        ModelObject* model_object = m_model->objects[object_idx];
        if (model_object != nullptr) {
            if (selection_mode == Selection::Instance)
                model_object->instances[instance_idx]->set_transformation(v->get_instance_transformation());
            else if (selection_mode == Selection::Volume)
                model_object->volumes[volume_idx]->set_transformation(v->get_volume_transformation());
            model_object->invalidate_bounding_box();
        }
    }
    // Fixes sinking/flying instances
    std::set<int> obj_idx_for_update_info_items;
    for (const std::pair<int, int>& i : done) {
        ModelObject* m = m_model->objects[i.first];
        const double shift_z = m->get_instance_min_z(i.second);
        // leave sinking instances as sinking
        if (min_zs.find({ i.first, i.second })->second >= SINKING_Z_THRESHOLD || shift_z > SINKING_Z_THRESHOLD) {
            const Vec3d shift(0.0, 0.0, -shift_z);
            m_selection.translate(i.first, i.second, shift);
            m->translate_instance(i.second, shift);
        }
        obj_idx_for_update_info_items.emplace(i.first);
    }
    //update sinking information in ObjectList
    for (int id : obj_idx_for_update_info_items)
        wxGetApp().obj_list()->update_info_items(static_cast<size_t>(id));
    if (!done.empty())
        post_event(SimpleEvent(EVT_GLCANVAS_INSTANCE_ROTATED));
    if (current_printer_technology() == ptFFF && fff_print()->config().complete_objects) {
        update_sequential_clearance(true);
        m_sequential_print_clearance.m_evaluating = true;
    }
    m_dirty = true;
}
References _, Slic3r::Print::config(), current_printer_technology(), done, fff_print(), Slic3r::ModelObject::get_instance_min_z(), Slic3r::GUI::Selection::get_mode(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::Selection::Instance, Slic3r::ModelObject::instance_bounding_box(), Slic3r::ModelObject::instances, Slic3r::ModelObject::invalidate_bounding_box(), L, m_dirty, Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_evaluating, m_model, m_selection, m_sequential_print_clearance, m_volumes, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::Model::objects, Slic3r::offset(), post_event(), Slic3r::ptFFF, Slic3r::SINKING_Z_THRESHOLD, Slic3r::GUI::Selection::translate(), Slic3r::ModelObject::translate_instance(), update_sequential_clearance(), Slic3r::GUI::Selection::Volume, Slic3r::ModelObject::volumes, and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::ObjectManipulation::change_rotation_value(), Slic3r::GUI::GLGizmoEmboss::do_rotate(), on_key(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_stop_dragging(), and Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging().
do_scale()
void Slic3r::GUI::GLCanvas3D::do_scale (const std::string & snapshot_type)
{
    if (m_model == nullptr)
        return;
    if (!snapshot_type.empty())
        wxGetApp().plater()->take_snapshot(_(snapshot_type));
    // stores current min_z of instances
    std::map<std::pair<int, int>, double> min_zs;
    if (!snapshot_type.empty()) {
        for (int i = 0; i < static_cast<int>(m_model->objects.size()); ++i) {
            const ModelObject* obj = m_model->objects[i];
            for (int j = 0; j < static_cast<int>(obj->instances.size()); ++j) {
                min_zs[{ i, j }] = obj->instance_bounding_box(j).min.z();
            }
        }
    }
    std::set<std::pair<int, int>> done;  // keeps track of modified instances
    Selection::EMode selection_mode = m_selection.get_mode();
    for (const GLVolume* v : m_volumes.volumes) {
        const int object_idx = v->object_idx();
        if (object_idx < 0 || (int)m_model->objects.size() <= object_idx)
            continue;
        const int instance_idx = v->instance_idx();
        const int volume_idx = v->volume_idx();
        if (volume_idx < 0)
            continue;
        done.insert(std::pair<int, int>(object_idx, instance_idx));
        // Rotate instances/volumes
        ModelObject* model_object = m_model->objects[object_idx];
        if (model_object != nullptr) {
            if (selection_mode == Selection::Instance)
                model_object->instances[instance_idx]->set_transformation(v->get_instance_transformation());
            else if (selection_mode == Selection::Volume) {
                model_object->instances[instance_idx]->set_transformation(v->get_instance_transformation());
                model_object->volumes[volume_idx]->set_transformation(v->get_volume_transformation());
            }
            model_object->invalidate_bounding_box();
        }
    }
    // Fixes sinking/flying instances
    std::set<int> obj_idx_for_update_info_items;
    for (const std::pair<int, int>& i : done) {
        ModelObject* m = m_model->objects[i.first];
        const double shift_z = m->get_instance_min_z(i.second);
        // leave sinking instances as sinking
        if (min_zs.empty() || min_zs.find({ i.first, i.second })->second >= SINKING_Z_THRESHOLD || shift_z > SINKING_Z_THRESHOLD) {
            const Vec3d shift(0.0, 0.0, -shift_z);
            m_selection.translate(i.first, i.second, shift);
            m->translate_instance(i.second, shift);
        }
        obj_idx_for_update_info_items.emplace(i.first);
    }
    //update sinking information in ObjectList
    for (int id : obj_idx_for_update_info_items)
        wxGetApp().obj_list()->update_info_items(static_cast<size_t>(id));
    if (!done.empty())
        post_event(SimpleEvent(EVT_GLCANVAS_INSTANCE_SCALED));
    if (current_printer_technology() == ptFFF && fff_print()->config().complete_objects) {
        update_sequential_clearance(true);
        m_sequential_print_clearance.m_evaluating = true;
    }
    m_dirty = true;
}
References _, Slic3r::Print::config(), current_printer_technology(), done, fff_print(), Slic3r::ModelObject::get_instance_min_z(), Slic3r::GUI::Selection::get_mode(), Slic3r::GUI::Selection::Instance, Slic3r::ModelObject::instance_bounding_box(), Slic3r::ModelObject::instances, Slic3r::ModelObject::invalidate_bounding_box(), m_dirty, Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_evaluating, m_model, m_selection, m_sequential_print_clearance, m_volumes, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::Model::objects, post_event(), Slic3r::ptFFF, Slic3r::SINKING_Z_THRESHOLD, Slic3r::GUI::Selection::translate(), Slic3r::ModelObject::translate_instance(), update_sequential_clearance(), Slic3r::GUI::Selection::Volume, Slic3r::ModelObject::volumes, and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), and Slic3r::GUI::GLGizmoScale3D::on_stop_dragging().
enable_dynamic_background()
void Slic3r::GUI::GLCanvas3D::enable_dynamic_background (bool enable)
{
    m_dynamic_background_enabled = enable;
}
References m_dynamic_background_enabled.
Referenced by Slic3r::GUI::Preview::init().
enable_gizmos()
void Slic3r::GUI::GLCanvas3D::enable_gizmos (bool enable)
{
    m_gizmos.set_enabled(enable);
}
References m_gizmos, and Slic3r::GUI::GLGizmosManager::set_enabled().
Referenced by Slic3r::GUI::View3D::init().
enable_labels()
void Slic3r::GUI::GLCanvas3D::enable_labels (bool enable) inline
{ m_labels.enable(enable); }
References Slic3r::GUI::GLCanvas3D::Labels::enable(), and m_labels.
Referenced by Slic3r::GUI::View3D::init().
enable_layers_editing()
void Slic3r::GUI::GLCanvas3D::enable_layers_editing (bool enable)
{
    m_layers_editing.set_enabled(enable);
    set_as_dirty();
}
References m_layers_editing, set_as_dirty(), and Slic3r::GUI::GLCanvas3D::LayersEditing::set_enabled().
Referenced by Slic3r::GUI::View3D::enable_layers_editing().
enable_legend_texture()
void Slic3r::GUI::GLCanvas3D::enable_legend_texture (bool enable)
{
    m_gcode_viewer.enable_legend(enable);
}
References Slic3r::GUI::GCodeViewer::enable_legend(), and m_gcode_viewer.
Referenced by Slic3r::GUI::Preview::init().
enable_main_toolbar()
void Slic3r::GUI::GLCanvas3D::enable_main_toolbar (bool enable)
{
    m_main_toolbar.set_enabled(enable);
}
References m_main_toolbar, and Slic3r::GUI::GLToolbar::set_enabled().
Referenced by Slic3r::GUI::View3D::init().
enable_moving()
void Slic3r::GUI::GLCanvas3D::enable_moving (bool enable)
{
    m_moving_enabled = enable;
}
References m_moving_enabled.
Referenced by Slic3r::GUI::View3D::init(), and Slic3r::GUI::on_mouse_surface_drag().
enable_picking()
void Slic3r::GUI::GLCanvas3D::enable_picking (bool enable)
{
    m_picking_enabled = enable;
}
References m_picking_enabled.
Referenced by Slic3r::GUI::View3D::init(), and Slic3r::GUI::on_mouse_surface_drag().
enable_selection()
void Slic3r::GUI::GLCanvas3D::enable_selection (bool enable)
{
    m_selection.set_enabled(enable);
}
References m_selection, and Slic3r::GUI::Selection::set_enabled().
Referenced by Slic3r::GUI::View3D::init().
enable_sla_view_type_detection()
void Slic3r::GUI::GLCanvas3D::enable_sla_view_type_detection () inline
{ m_sla_view_type_detection_active = true; }
References m_sla_view_type_detection_active.
enable_slope()
void Slic3r::GUI::GLCanvas3D::enable_slope (bool enable) inline
{ m_slope.enable(enable); }
References Slic3r::GUI::GLCanvas3D::Slope::enable(), and m_slope.
Referenced by Slic3r::GUI::View3D::init().
enable_undoredo_toolbar()
void Slic3r::GUI::GLCanvas3D::enable_undoredo_toolbar (bool enable)
{
    m_undoredo_toolbar.set_enabled(enable);
}
References m_undoredo_toolbar, and Slic3r::GUI::GLToolbar::set_enabled().
Referenced by Slic3r::GUI::View3D::init().
ensure_on_bed()
void Slic3r::GUI::GLCanvas3D::ensure_on_bed (unsigned int object_idx, bool allow_negative_z)
{
    if (allow_negative_z)
        return;
    typedef std::map<std::pair<int, int>, double> InstancesToZMap;
    InstancesToZMap instances_min_z;
    for (GLVolume* volume : m_volumes.volumes) {
        if (volume->object_idx() == (int)object_idx && !volume->is_modifier) {
            double min_z = volume->transformed_convex_hull_bounding_box().min.z();
            std::pair<int, int> instance = std::make_pair(volume->object_idx(), volume->instance_idx());
            InstancesToZMap::iterator it = instances_min_z.find(instance);
            if (it == instances_min_z.end())
                it = instances_min_z.insert(InstancesToZMap::value_type(instance, DBL_MAX)).first;
            it->second = std::min(it->second, min_z);
        }
    }
    for (GLVolume* volume : m_volumes.volumes) {
        std::pair<int, int> instance = std::make_pair(volume->object_idx(), volume->instance_idx());
        InstancesToZMap::iterator it = instances_min_z.find(instance);
        if (it != instances_min_z.end())
            volume->set_instance_offset(Z, volume->get_instance_offset(Z) - it->second);
    }
}
References m_volumes, Slic3r::GLVolumeCollection::volumes, and Slic3r::Z.
export_toolpaths_to_obj()
void Slic3r::GUI::GLCanvas3D::export_toolpaths_to_obj (const char * filename) const
{
    m_gcode_viewer.export_toolpaths_to_obj(filename);
}
References Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj(), and m_gcode_viewer.
fff_print()
const Print * Slic3r::GUI::GLCanvas3D::fff_print () const
{
    return (m_process == nullptr) ? nullptr : m_process->fff_print();
}
Referenced by Slic3r::GUI::GLGizmoFdmSupports::apply_data_from_backend(), do_move(), do_rotate(), do_scale(), Slic3r::GUI::GLGizmoFdmSupports::has_backend_supports(), load_gcode_preview(), load_preview(), on_mouse(), and update_sequential_clearance().
force_main_toolbar_left_action()
void Slic3r::GUI::GLCanvas3D::force_main_toolbar_left_action (int item_id) inline
{ m_main_toolbar.force_left_action(item_id, *this); }
References Slic3r::GUI::GLToolbar::force_left_action(), and m_main_toolbar.
Referenced by _init_main_toolbar(), Slic3r::GUI::ObjectList::del_info_item(), and Slic3r::GUI::Plater::toggle_layers_editing().
force_main_toolbar_right_action()
void Slic3r::GUI::GLCanvas3D::force_main_toolbar_right_action (int item_id) inline
{ m_main_toolbar.force_right_action(item_id, *this); }
References Slic3r::GUI::GLToolbar::force_right_action(), and m_main_toolbar.
get_arrange_settings()
ArrangeSettings Slic3r::GUI::GLCanvas3D::get_arrange_settings () const inline
{
        const ArrangeSettings &settings = get_arrange_settings_ref(this);
        ArrangeSettings ret = settings;
        if (&settings == &m_arrange_settings_fff_seq_print) {
            ret.distance = std::max(ret.distance,
                                    float(min_object_distance(*m_config)));
        }
        if (!is_arrange_alignment_enabled())
            ret.alignment = -1;
        return ret;
    }
References Slic3r::GUI::GLCanvas3D::ArrangeSettings::alignment, Slic3r::GUI::GLCanvas3D::ArrangeSettings::distance, get_arrange_settings_ref(), is_arrange_alignment_enabled(), m_arrange_settings_fff_seq_print, m_config, and Slic3r::min_object_distance().
Referenced by _render_arrange_menu(), and Slic3r::GUI::get_arrange_params().
get_arrange_settings_ref()
template<class Self > static auto & Slic3r::GUI::GLCanvas3D::get_arrange_settings_ref (Self * self) inline static private
{
        PrinterTechnology ptech = self->current_printer_technology();
        auto *ptr = &self->m_arrange_settings_fff;
        if (ptech == ptSLA) {
            ptr = &self->m_arrange_settings_sla;
        } else if (ptech == ptFFF) {
            auto co_opt = self->m_config->template option<ConfigOptionBool>("complete_objects");
            if (co_opt && co_opt->value)
                ptr = &self->m_arrange_settings_fff_seq_print;
            else
                ptr = &self->m_arrange_settings_fff;
        }
        return *ptr;
    }
References Slic3r::ptFFF, and Slic3r::ptSLA.
Referenced by _render_arrange_menu(), and get_arrange_settings().
get_canvas_size()
Size Slic3r::GUI::GLCanvas3D::get_canvas_size () const
{
    int w = 0;
    int h = 0;
    if (m_canvas != nullptr)
        m_canvas->GetSize(&w, &h);
#if ENABLE_RETINA_GL
    const float factor = m_retina_helper->get_scale_factor();
    w *= factor;
    h *= factor;
#else
    const float factor = 1.0f;
#endif
    return Size(w, h, factor);
}
References m_canvas.
Referenced by _picking_pass(), _rectangular_selection_picking_pass(), _refresh_if_shown_on_screen(), _render_thumbnail_legacy(), Slic3r::GUI::GLToolbar::contains_mouse_horizontal(), Slic3r::GUI::GLToolbar::contains_mouse_vertical(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmosManager::do_render_overlay(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::GLCanvas3D::LayersEditing::get_bar_rect_screen(), Slic3r::GUI::GLGizmosManager::get_gizmo_from_mouse(), on_mouse_wheel(), Slic3r::GUI::GLGizmoEmboss::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), render(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLToolbarItem::render(), Slic3r::GUI::GLCanvas3D::Tooltip::render(), Slic3r::GUI::NotificationManager::PopNotification::render(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_active_object_annotations(), Slic3r::GUI::GLGizmosManager::render_arrow(), Slic3r::GUI::GLToolbar::render_arrow(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLToolbar::render_horizontal(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_overlay(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_profile(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::GLToolbar::render_vertical(), Slic3r::GUI::GLCanvas3D::LayersEditing::thickness_bar_width(), Slic3r::GUI::GLToolbar::update_hover_state_horizontal(), and Slic3r::GUI::GLToolbar::update_hover_state_vertical().
get_clipping_planes()
const std::array< ClippingPlane, 2 > & Slic3r::GUI::GLCanvas3D::get_clipping_planes () const inline
{ return m_clipping_planes; };
References m_clipping_planes.
Referenced by Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data().
get_custom_gcode_per_print_z()
std::vector< CustomGCode::Item > & Slic3r::GUI::GLCanvas3D::get_custom_gcode_per_print_z () inline
{ return m_gcode_viewer.get_custom_gcode_per_print_z(); }
References Slic3r::GUI::GCodeViewer::get_custom_gcode_per_print_z(), and m_gcode_viewer.
Referenced by Slic3r::GUI::Preview::load_print_as_fff(), and Slic3r::GUI::Preview::update_layers_slider().
get_first_hover_volume_idx()
int Slic3r::GUI::GLCanvas3D::get_first_hover_volume_idx () const inline
{ return m_hover_volume_idxs.empty() ? -1 : m_hover_volume_idxs.front(); }
References m_hover_volume_idxs.
Referenced by Slic3r::GUI::get_first_hovered_gl_volume(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), and Slic3r::GUI::on_mouse_surface_drag().
get_gcode_extruders_count()
size_t Slic3r::GUI::GLCanvas3D::get_gcode_extruders_count () inline
{ return m_gcode_viewer.get_extruders_count(); }
References Slic3r::GUI::GCodeViewer::get_extruders_count(), and m_gcode_viewer.
Referenced by Slic3r::GUI::Preview::load_print_as_fff().
get_gcode_layers_zs()
const std::vector< double > & Slic3r::GUI::GLCanvas3D::get_gcode_layers_zs () const
{
    return m_gcode_viewer.get_layers_zs();
}
References Slic3r::GUI::GCodeViewer::get_layers_zs(), and m_gcode_viewer.
Referenced by Slic3r::GUI::Preview::load_print_as_fff().
get_gcode_options_visibility_flags()
unsigned int Slic3r::GUI::GLCanvas3D::get_gcode_options_visibility_flags () const inline
{ return m_gcode_viewer.get_options_visibility_flags(); }
References Slic3r::GUI::GCodeViewer::get_options_visibility_flags(), and m_gcode_viewer.
get_gcode_sequential_view()
const GCodeViewer::SequentialView & Slic3r::GUI::GLCanvas3D::get_gcode_sequential_view () const inline
{ return m_gcode_viewer.get_sequential_view(); }
References Slic3r::GUI::GCodeViewer::get_sequential_view(), and m_gcode_viewer.
Referenced by Slic3r::GUI::Preview::update_moves_slider().
get_gcode_view_preview_type()
GCodeViewer::EViewType Slic3r::GUI::GLCanvas3D::get_gcode_view_preview_type () const inline
{ return m_gcode_viewer.get_view_type(); }
References Slic3r::GUI::GCodeViewer::get_view_type(), and m_gcode_viewer.
Referenced by Slic3r::GUI::Preview::load_print_as_fff().
get_gcode_view_type()
GCodeViewer::EViewType Slic3r::GUI::GLCanvas3D::get_gcode_view_type () const inline
{ return m_gcode_viewer.get_view_type(); }
References Slic3r::GUI::GCodeViewer::get_view_type(), and m_gcode_viewer.
get_gizmos_manager() [1/2]
GLGizmosManager & Slic3r::GUI::GLCanvas3D::get_gizmos_manager () inline
{ return m_gizmos; }
References m_gizmos.
get_gizmos_manager() [2/2]
const GLGizmosManager & Slic3r::GUI::GLCanvas3D::get_gizmos_manager () const inline
{ return m_gizmos; }
References m_gizmos.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), Slic3r::GUI::MenuFactory::append_menu_item_add_text(), Slic3r::GUI::MenuFactory::append_menu_item_edit_text(), Slic3r::GUI::MenuFactory::append_menu_item_printable(), Slic3r::GUI::call_after_if_active(), Slic3r::GUI::MainFrame::can_save(), Slic3r::GUI::MainFrame::can_save_as(), Slic3r::GUI::GLGizmoEmboss::close(), Slic3r::GUI::GLGizmoSimplify::close(), priv::create_volume(), Slic3r::GUI::ObjectList::del_info_item(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), Slic3r::GUI::GLGizmoEmboss::draw_model_type(), Slic3r::GUI::Emboss::CreateObjectJob::finalize(), Slic3r::GUI::GLGizmoEmboss::on_shortcut_key(), Slic3r::GUI::ObjectManipulation::set_coordinates_type(), Slic3r::GUI::ObjectList::simplify(), toggle_model_objects_visibility(), and priv::update_volume().
get_layers_height_data()
std::pair< SlicingParameters, const std::vector< double > > Slic3r::GUI::GLCanvas3D::get_layers_height_data (int object_id)
{
    m_layers_editing.select_object(*m_model, object_id);
    std::pair<SlicingParameters, const std::vector<double>> ret = m_layers_editing.get_layers_height_data();
    m_layers_editing.select_object(*m_model, -1);
    return ret;
}
References Slic3r::GUI::GLCanvas3D::LayersEditing::get_layers_height_data(), m_layers_editing, m_model, and Slic3r::GUI::GLCanvas3D::LayersEditing::select_object().
get_local_mouse_position()
Vec2d Slic3r::GUI::GLCanvas3D::get_local_mouse_position () const
{
    if (m_canvas == nullptr)
    return Vec2d::Zero();
    wxPoint mouse_pos = m_canvas->ScreenToClient(wxGetMousePosition());
    const double factor =
#if ENABLE_RETINA_GL
        m_retina_helper->get_scale_factor();
#else
        1.0;
#endif
    return Vec2d(factor * mouse_pos.x, factor * mouse_pos.y);
}
References m_canvas.
Referenced by Slic3r::GUI::GLCanvas3D::LayersEditing::get_cursor_z_relative(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), and Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle().
get_main_toolbar_height()
float Slic3r::GUI::GLCanvas3D::get_main_toolbar_height () inline
{ return m_main_toolbar.get_height(); }
References Slic3r::GUI::GLToolbar::get_height(), and m_main_toolbar.
Referenced by Slic3r::GUI::GLGizmoEmboss::on_render_input_window(), and Slic3r::GUI::GLGizmoSimplify::on_render_input_window().
get_main_toolbar_item_id()
int Slic3r::GUI::GLCanvas3D::get_main_toolbar_item_id (const std::string & name) const inline
{ return m_main_toolbar.get_item_id(name); }
References Slic3r::GUI::GLToolbar::get_item_id(), and m_main_toolbar.
Referenced by _init_main_toolbar(), Slic3r::GUI::ObjectList::del_info_item(), and update_tooltip_for_settings_item_in_main_toolbar().
get_model()
const Model * Slic3r::GUI::GLCanvas3D::get_model () const inline
{ return m_model; }
References m_model.
Referenced by Slic3r::GUI::create_meshes(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), Slic3r::GUI::on_mouse_surface_drag(), and Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection().
get_move_volume_id()
int Slic3r::GUI::GLCanvas3D::get_move_volume_id () const inline
{ return m_mouse.drag.move_volume_idx; }
References Slic3r::GUI::GLCanvas3D::Mouse::drag, m_mouse, and Slic3r::GUI::GLCanvas3D::Mouse::Drag::move_volume_idx.
Referenced by Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), and Slic3r::GUI::GLGizmoSlaSupports::on_mouse().
get_overlay_window_width()
float Slic3r::GUI::GLCanvas3D::get_overlay_window_width () inline private
{ return LayersEditing::get_overlay_window_width(); }
References Slic3r::GUI::GLCanvas3D::LayersEditing::get_overlay_window_width().
Referenced by render().
get_popup_menu_position()
const std::optional< Vec2d > & Slic3r::GUI::GLCanvas3D::get_popup_menu_position () const inline
{ return m_popup_menu_positon; }
References m_popup_menu_positon.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_add_text().
get_raycasters_for_picking()
std::vector< std::shared_ptr< SceneRaycasterItem > > * Slic3r::GUI::GLCanvas3D::get_raycasters_for_picking (SceneRaycaster::EType type) inline
{
        return m_scene_raycaster.get_raycasters(type);
    }
References Slic3r::GUI::SceneRaycaster::get_raycasters(), and m_scene_raycaster.
Referenced by Slic3r::GUI::create_meshes(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::GLGizmoCut3D::set_volumes_picking_state(), toggle_model_objects_visibility(), and toggle_sla_auxiliaries_visibility().
get_selection() [1/2]
Selection & Slic3r::GUI::GLCanvas3D::get_selection () inline
{ return m_selection; }
References m_selection.
get_selection() [2/2]
const Selection & Slic3r::GUI::GLCanvas3D::get_selection () const inline
{ return m_selection; }
References m_selection.
Referenced by Slic3r::GUI::ObjectManipulation::ObjectManipulation(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), Slic3r::GUI::MenuFactory::append_menu_item_export_stl(), Slic3r::GUI::MenuFactory::append_menu_item_instance_to_object(), priv::apply_camera_dir(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::GLGizmoCut3D::bounding_box(), Slic3r::GUI::GLGizmoEmboss::calculate_scale(), Slic3r::GUI::ObjectManipulation::change_rotation_value(), Slic3r::GUI::GLGizmoEmboss::close(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmoFlatten::data_changed(), Slic3r::GUI::GLGizmoMove3D::data_changed(), Slic3r::GUI::GLGizmoPainterBase::data_changed(), Slic3r::GUI::GLGizmoRotate3D::data_changed(), Slic3r::GUI::GLGizmoEmboss::do_rotate(), Slic3r::GUI::GLGizmoEmboss::do_translate(), Slic3r::GUI::GLGizmoEmboss::draw_advanced(), Slic3r::GUI::GLGizmoEmboss::draw_window(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::get_selected_gl_volume(), Slic3r::GUI::get_selection(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmosManager::handle_shortcut(), Slic3r::GUI::View3D::init(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMove3D::on_dragging(), Slic3r::GUI::GLGizmoCut3D::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeasure::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), Slic3r::GUI::GLGizmoRotate3D::on_mouse(), Slic3r::GUI::GLGizmoScale3D::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_rotation(), Slic3r::GUI::GLGizmoEmboss::on_mouse_for_translate(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoEmboss::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoEmboss::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoEmboss::on_stop_dragging(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::GLGizmoEmboss::process(), Slic3r::GUI::GLGizmoSimplify::process(), Slic3r::GUI::GLGizmoCut3D::process_contours(), Slic3r::GUI::GLGizmoCut3D::process_cut_line(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoCut3D::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoMeasure::render_dimensioning(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoCut3D::reset_cut_by_contours(), Slic3r::GUI::GLGizmoSlaBase::reslice_until_step(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoEmboss::set_volume_by_selection(), Slic3r::GUI::GLGizmoCut3D::set_volumes_picking_state(), Slic3r::GUI::GLGizmoCut3D::transformed_bounding_box(), Slic3r::GUI::GLGizmoHollow::update_hole_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoMeasure::update_if_needed(), Slic3r::GUI::GLGizmoSlaSupports::update_point_raycasters_for_picking_transform(), Slic3r::GUI::GLGizmoScale3D::update_render_data(), Slic3r::GUI::ObjectManipulation::update_reset_buttons_visibility(), Slic3r::GUI::GLGizmoSlaBase::update_volumes(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
get_size_proportional_to_max_bed_size()
double Slic3r::GUI::GLCanvas3D::get_size_proportional_to_max_bed_size (double factor) const
{
    const BoundingBoxf& bbox = m_bed.build_volume().bounding_volume2d();
    return factor * std::max(bbox.size()[0], bbox.size()[1]);
}
References Slic3r::BuildVolume::bounding_volume2d(), Slic3r::GUI::Bed3D::build_volume(), m_bed, and Slic3r::BoundingBoxBase< PointType, APointsType >::size().
Referenced by Slic3r::GUI::Plater::increase_instances().
get_toolpath_role_visibility_flags()
unsigned int Slic3r::GUI::GLCanvas3D::get_toolpath_role_visibility_flags () const inline
{ return m_gcode_viewer.get_toolpath_role_visibility_flags(); }
References Slic3r::GUI::GCodeViewer::get_toolpath_role_visibility_flags(), and m_gcode_viewer.
get_use_clipping_planes()
bool Slic3r::GUI::GLCanvas3D::get_use_clipping_planes () const inline
{ return m_use_clipping_planes; }
References m_use_clipping_planes.
Referenced by Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data().
get_volumes()
const GLVolumeCollection & Slic3r::GUI::GLCanvas3D::get_volumes () const inline
{ return m_volumes; }
References m_volumes.
Referenced by Slic3r::GUI::create_meshes(), Slic3r::GUI::get_first_hovered_gl_volume(), Slic3r::GUI::get_selected_gl_volume(), Slic3r::GUI::GLGizmoEmboss::on_mouse_change_selection(), and Slic3r::GUI::on_mouse_surface_drag().
get_volumes_count()
unsigned int Slic3r::GUI::GLCanvas3D::get_volumes_count () const
{
    return (unsigned int)m_volumes.volumes.size();
}
References m_volumes, and Slic3r::GLVolumeCollection::volumes.
get_volumes_print_zs()
std::vector< double > Slic3r::GUI::GLCanvas3D::get_volumes_print_zs (bool active_only) const
{
    return m_volumes.get_current_print_zs(active_only);
}
References Slic3r::GLVolumeCollection::get_current_print_zs(), and m_volumes.
Referenced by Slic3r::GUI::Preview::load_print_as_fff().
get_wipe_tower_info()
GLCanvas3D::WipeTowerInfo Slic3r::GUI::GLCanvas3D::get_wipe_tower_info () const
{
    WipeTowerInfo wti;
    for (const GLVolume* vol : m_volumes.volumes) {
        if (vol->is_wipe_tower) {
            wti.m_pos = Vec2d(m_config->opt_float("wipe_tower_x"),
                            m_config->opt_float("wipe_tower_y"));
            wti.m_rotation = (M_PI/180.) * m_config->opt_float("wipe_tower_rotation_angle");
            const BoundingBoxf3& bb = vol->bounding_box();
            wti.m_bb = BoundingBoxf{to_2d(bb.min), to_2d(bb.max)};
            break;
        }
    }
    return wti;
}
References Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_bb, m_config, M_PI, Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_pos, Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_rotation, m_volumes, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, Slic3r::ConfigBase::opt_float(), Slic3r::to_2d(), and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::get_wipe_tower().
get_wxglcanvas() [1/2]
wxGLCanvas * Slic3r::GUI::GLCanvas3D::get_wxglcanvas () inline
{ return m_canvas; }
References m_canvas.
Referenced by Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_overlay(), and Slic3r::GUI::GLCanvas3D::LayersEditing::thickness_bar_width().
get_wxglcanvas() [2/2]
const wxGLCanvas * Slic3r::GUI::GLCanvas3D::get_wxglcanvas () const inline
{ return m_canvas; }
References m_canvas.
handle_layers_data_focus_event()
void Slic3r::GUI::GLCanvas3D::handle_layers_data_focus_event (const t_layer_height_range range, const EditorType type)
{
    std::string field = "layer_" + std::to_string(type) + "_" + float_to_string_decimal_point(range.first) + "_" + float_to_string_decimal_point(range.second);
    handle_sidebar_focus_event(field, true);
}
References Slic3r::float_to_string_decimal_point(), handle_sidebar_focus_event(), and Slic3r::range().
handle_sidebar_focus_event()
void Slic3r::GUI::GLCanvas3D::handle_sidebar_focus_event (const std::string & opt_key, bool focus_on)
{
    m_sidebar_field = focus_on ? opt_key : "";
    if (!m_sidebar_field.empty())
        m_gizmos.reset_all_states();
    m_dirty = true;
}
References m_dirty, m_gizmos, m_sidebar_field, and Slic3r::GUI::GLGizmosManager::reset_all_states().
Referenced by handle_layers_data_focus_event().
has_toolpaths_to_export()
bool Slic3r::GUI::GLCanvas3D::has_toolpaths_to_export () const
{
    return m_gcode_viewer.can_export_toolpaths();
}
References Slic3r::GUI::GCodeViewer::can_export_toolpaths(), and m_gcode_viewer.
highlight_gizmo()
void Slic3r::GUI::GLCanvas3D::highlight_gizmo (const std::string & gizmo_name)
{
    GLGizmosManager::EType gizmo = m_gizmos.get_gizmo_from_name(gizmo_name);
    if(gizmo == GLGizmosManager::EType::Undefined)
        return;
    m_gizmo_highlighter.init(&m_gizmos, gizmo, this);
}
highlight_toolbar_item()
void Slic3r::GUI::GLCanvas3D::highlight_toolbar_item (const std::string & item_name)
{
    GLToolbarItem* item = m_main_toolbar.get_item(item_name);
    if (!item)
        item = m_undoredo_toolbar.get_item(item_name);
    if (!item || !item->is_visible())
        return;
    m_toolbar_highlighter.init(item, this);
}
References Slic3r::GUI::GLToolbarItem::is_visible().
init()
bool Slic3r::GUI::GLCanvas3D::init ()
{
    if (m_initialized)
        return true;
    if (m_canvas == nullptr || m_context == nullptr)
        return false;
    glsafe(::glClearColor(1.0f, 1.0f, 1.0f, 1.0f));
#if ENABLE_OPENGL_ES
    glsafe(::glClearDepthf(1.0f));
#else
    glsafe(::glClearDepth(1.0f));
#endif // ENABLE_OPENGL_ES
    glsafe(::glDepthFunc(GL_LESS));
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glEnable(GL_CULL_FACE));
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
    if (m_multisample_allowed)
        glsafe(::glEnable(GL_MULTISAMPLE));
    if (m_main_toolbar.is_enabled())
        m_layers_editing.init();
    if (m_gizmos.is_enabled() && !m_gizmos.init())
        std::cout << "Unable to initialize gizmos: please, check that all the required textures are available" << std::endl;
    if (!_init_toolbars())
        return false;
    if (m_selection.is_enabled() && !m_selection.init())
        return false;
    m_initialized = true;
    return true;
}
References _init_toolbars(), glsafe, Slic3r::GUI::GLGizmosManager::init(), Slic3r::GUI::GLCanvas3D::LayersEditing::init(), Slic3r::GUI::Selection::init(), Slic3r::GUI::GLGizmosManager::is_enabled(), Slic3r::GUI::GLToolbar::is_enabled(), Slic3r::GUI::Selection::is_enabled(), m_canvas, m_context, m_gizmos, m_initialized, m_layers_editing, m_main_toolbar, m_multisample_allowed, and m_selection.
Referenced by render().
init_gcode_viewer()
void Slic3r::GUI::GLCanvas3D::init_gcode_viewer () inline
{ m_gcode_viewer.init(); }
References Slic3r::GUI::GCodeViewer::init(), and m_gcode_viewer.
is_arrange_alignment_enabled()
bool Slic3r::GUI::GLCanvas3D::is_arrange_alignment_enabled () const private
{
    return m_config ? is_XL_printer(*m_config) : false;
}
References Slic3r::is_XL_printer(), and m_config.
Referenced by _render_arrange_menu(), and get_arrange_settings().
is_dragging()
bool Slic3r::GUI::GLCanvas3D::is_dragging () const inline
{ return m_gizmos.is_dragging() || (m_moving && !m_mouse.scene_position.isApprox(m_mouse.drag.start_position_3D)); }
References Slic3r::GUI::GLCanvas3D::Mouse::drag, Slic3r::GUI::GLGizmosManager::is_dragging(), m_gizmos, m_mouse, m_moving, Slic3r::GUI::GLCanvas3D::Mouse::scene_position, and Slic3r::GUI::GLCanvas3D::Mouse::Drag::start_position_3D.
Referenced by Slic3r::GUI::View3D::is_dragging().
is_gcode_legend_enabled()
bool Slic3r::GUI::GLCanvas3D::is_gcode_legend_enabled () const inline
{ return m_gcode_viewer.is_legend_enabled(); }
References Slic3r::GUI::GCodeViewer::is_legend_enabled(), and m_gcode_viewer.
is_initialized()
bool Slic3r::GUI::GLCanvas3D::is_initialized () const inline
{ return m_initialized; }
References m_initialized.
Referenced by render().
is_layers_editing_allowed()
bool Slic3r::GUI::GLCanvas3D::is_layers_editing_allowed () const
{
    return m_layers_editing.is_allowed();
}
References Slic3r::GUI::GLCanvas3D::LayersEditing::is_allowed(), and m_layers_editing.
Referenced by Slic3r::GUI::View3D::is_layers_editing_allowed().
is_layers_editing_enabled()
bool Slic3r::GUI::GLCanvas3D::is_layers_editing_enabled () const
{
    return m_layers_editing.is_enabled();
}
References Slic3r::GUI::GLCanvas3D::LayersEditing::is_enabled(), and m_layers_editing.
Referenced by Slic3r::GUI::ObjectList::del_info_item(), do_move(), Slic3r::GUI::View3D::is_layers_editing_enabled(), Slic3r::GUI::Plater::priv::is_view3D_layers_editing_enabled(), Slic3r::GUI::GLGizmoCut3D::on_is_activable(), on_mouse(), and on_mouse_wheel().
is_legend_shown()
bool Slic3r::GUI::GLCanvas3D::is_legend_shown () const inline
{ return m_gcode_viewer.is_legend_enabled(); }
References Slic3r::GUI::GCodeViewer::is_legend_enabled(), and m_gcode_viewer.
Referenced by Slic3r::GUI::Plater::priv::is_legend_shown(), and on_char().
is_mouse_dragging()
bool Slic3r::GUI::GLCanvas3D::is_mouse_dragging () const inline
{ return m_mouse.dragging; }
References Slic3r::GUI::GLCanvas3D::Mouse::dragging, and m_mouse.
Referenced by Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoMeasure::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), Slic3r::GUI::GLGizmoEmboss::on_render(), and Slic3r::GUI::ObjectList::OnContextMenu().
is_object_sinking()
bool Slic3r::GUI::GLCanvas3D::is_object_sinking (int object_idx) const
{
    for (const GLVolume* v : m_volumes.volumes) {
        if (v->object_idx() == object_idx && (v->is_sinking() || (!v->is_modifier && v->is_below_printbed())))
            return true;
    }
    return false;
}
References m_volumes, and Slic3r::GLVolumeCollection::volumes.
is_reload_delayed()
bool Slic3r::GUI::GLCanvas3D::is_reload_delayed () const
{
    return m_reload_delayed;
}
References m_reload_delayed.
Referenced by Slic3r::GUI::View3D::is_reload_delayed().
is_search_pressed()
bool Slic3r::GUI::GLCanvas3D::is_search_pressed () const
{
    return m_main_toolbar.is_item_pressed("search");
}
Referenced by Slic3r::GUI::MainFrame::select_tab().
is_sequential_print_clearance_empty()
bool Slic3r::GUI::GLCanvas3D::is_sequential_print_clearance_empty () const inline
{
        return m_sequential_print_clearance.empty();
    }
References Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::empty(), and m_sequential_print_clearance.
Referenced by Slic3r::GUI::Plater::priv::update_background_process().
is_sequential_print_clearance_evaluating()
bool Slic3r::GUI::GLCanvas3D::is_sequential_print_clearance_evaluating () const inline
{
        return m_sequential_print_clearance.m_evaluating;
    }
References Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_evaluating, and m_sequential_print_clearance.
Referenced by Slic3r::GUI::Plater::priv::update_background_process().
is_using_slope()
bool Slic3r::GUI::GLCanvas3D::is_using_slope () const inline
{ return m_slope.is_used(); }
References Slic3r::GUI::GLCanvas3D::Slope::is_used(), and m_slope.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window().
load_arrange_settings()
void Slic3r::GUI::GLCanvas3D::load_arrange_settings () private
{
    std::string dist_fff_str =
        wxGetApp().app_config->get("arrange", "min_object_distance_fff");
    std::string dist_bed_fff_str =
        wxGetApp().app_config->get("arrange", "min_bed_distance_fff");
    std::string dist_fff_seq_print_str =
        wxGetApp().app_config->get("arrange", "min_object_distance_fff_seq_print");
    std::string dist_bed_fff_seq_print_str =
        wxGetApp().app_config->get("arrange", "min_bed_distance_fff_seq_print");
    std::string dist_sla_str =
        wxGetApp().app_config->get("arrange", "min_object_distance_sla");
    std::string dist_bed_sla_str =
        wxGetApp().app_config->get("arrange", "min_bed_distance_sla");
    std::string en_rot_fff_str =
        wxGetApp().app_config->get("arrange", "enable_rotation_fff");
    std::string en_rot_fff_seqp_str =
        wxGetApp().app_config->get("arrange", "enable_rotation_fff_seq_print");
    std::string en_rot_sla_str =
        wxGetApp().app_config->get("arrange", "enable_rotation_sla");
//    std::string alignment_fff_str =
//        wxGetApp().app_config->get("arrange", "alignment_fff");
//    std::string alignment_fff_seqp_str =
//        wxGetApp().app_config->get("arrange", "alignment_fff_seq_pring");
//    std::string alignment_sla_str =
//        wxGetApp().app_config->get("arrange", "alignment_sla");
    // Override default alignment and save save/load it to a temporary slot "alignment_xl"
    std::string alignment_xl_str =
        wxGetApp().app_config->get("arrange", "alignment_xl");
    if (!dist_fff_str.empty())
        m_arrange_settings_fff.distance = string_to_float_decimal_point(dist_fff_str);
    if (!dist_bed_fff_str.empty())
        m_arrange_settings_fff.distance_from_bed = string_to_float_decimal_point(dist_bed_fff_str);
    if (!dist_fff_seq_print_str.empty())
        m_arrange_settings_fff_seq_print.distance = string_to_float_decimal_point(dist_fff_seq_print_str);
    if (!dist_bed_fff_seq_print_str.empty())
        m_arrange_settings_fff_seq_print.distance_from_bed = string_to_float_decimal_point(dist_bed_fff_seq_print_str);
    if (!dist_sla_str.empty())
        m_arrange_settings_sla.distance = string_to_float_decimal_point(dist_sla_str);
    if (!dist_bed_sla_str.empty())
        m_arrange_settings_sla.distance_from_bed = string_to_float_decimal_point(dist_bed_sla_str);
    if (!en_rot_fff_str.empty())
        m_arrange_settings_fff.enable_rotation = (en_rot_fff_str == "1" || en_rot_fff_str == "yes");
    if (!en_rot_fff_seqp_str.empty())
        m_arrange_settings_fff_seq_print.enable_rotation = (en_rot_fff_seqp_str == "1" || en_rot_fff_seqp_str == "yes");
    if (!en_rot_sla_str.empty())
        m_arrange_settings_sla.enable_rotation = (en_rot_sla_str == "1" || en_rot_sla_str == "yes");
//    if (!alignment_sla_str.empty())
//        m_arrange_settings_sla.alignment = std::stoi(alignment_sla_str);
//    if (!alignment_fff_str.empty())
//        m_arrange_settings_fff.alignment = std::stoi(alignment_fff_str);
//    if (!alignment_fff_seqp_str.empty())
//        m_arrange_settings_fff_seq_print.alignment = std::stoi(alignment_fff_seqp_str);
    // Override default alignment and save save/load it to a temporary slot "alignment_xl"
    int arr_alignment = static_cast<int>(arrangement::Pivots::BottomLeft);
    if (!alignment_xl_str.empty())
        arr_alignment = std::stoi(alignment_xl_str);
    m_arrange_settings_sla.alignment = arr_alignment ;
    m_arrange_settings_fff.alignment = arr_alignment ;
    m_arrange_settings_fff_seq_print.alignment = arr_alignment ;
}
References Slic3r::GUI::GLCanvas3D::ArrangeSettings::alignment, Slic3r::arrangement::BottomLeft, Slic3r::GUI::GLCanvas3D::ArrangeSettings::distance, Slic3r::GUI::GLCanvas3D::ArrangeSettings::distance_from_bed, Slic3r::GUI::GLCanvas3D::ArrangeSettings::enable_rotation, m_arrange_settings_fff, m_arrange_settings_fff_seq_print, m_arrange_settings_sla, and Slic3r::string_to_float_decimal_point().
Referenced by GLCanvas3D().
load_gcode_preview()
void Slic3r::GUI::GLCanvas3D::load_gcode_preview (const GCodeProcessorResult & gcode_result, const std::vector< std::string > & str_tool_colors)
{
    m_gcode_viewer.load(gcode_result, *this->fff_print());
    if (wxGetApp().is_editor()) {
        m_gcode_viewer.update_shells_color_by_extruder(m_config);
        _set_warning_notification_if_needed(EWarning::ToolpathOutside);
        _set_warning_notification_if_needed(EWarning::GCodeConflict);
    }
    m_gcode_viewer.refresh(gcode_result, str_tool_colors);
    set_as_dirty();
    request_extra_frame();
}
References _set_warning_notification_if_needed(), fff_print(), GCodeConflict, Slic3r::GUI::GCodeViewer::load(), m_config, m_gcode_viewer, Slic3r::GUI::GCodeViewer::refresh(), request_extra_frame(), set_as_dirty(), ToolpathOutside, and Slic3r::GUI::GCodeViewer::update_shells_color_by_extruder().
Referenced by Slic3r::GUI::Preview::load_print_as_fff().
load_object() [1/2]
std::vector< int > Slic3r::GUI::GLCanvas3D::load_object (const Model & model, int obj_idx)
{
    if (0 <= obj_idx && obj_idx < (int)model.objects.size()) {
        const ModelObject* model_object = model.objects[obj_idx];
        if (model_object != nullptr)
            return load_object(*model_object, obj_idx, std::vector<int>());
    }
    return std::vector<int>();
}
References load_object(), and Slic3r::Model::objects.
load_object() [2/2]
std::vector< int > Slic3r::GUI::GLCanvas3D::load_object (const ModelObject & model_object, int obj_idx, std::vector< int > instance_idxs)
{
    if (instance_idxs.empty()) {
        for (unsigned int i = 0; i < model_object.instances.size(); ++i) {
            instance_idxs.emplace_back(i);
        }
    }
    return m_volumes.load_object(&model_object, obj_idx, instance_idxs);
}
References Slic3r::ModelObject::instances, Slic3r::GLVolumeCollection::load_object(), and m_volumes.
Referenced by load_object().
load_preview()
void Slic3r::GUI::GLCanvas3D::load_preview (const std::vector< std::string > & str_tool_colors, const std::vector< CustomGCode::Item > & color_print_values)
{
    const Print *print = this->fff_print();
    if (print == nullptr)
        return;
    _set_current();
    // Release OpenGL data before generating new data.
    this->reset_volumes();
    const BuildVolume &build_volume = m_bed.build_volume();
    _load_print_toolpaths(build_volume);
    _load_wipe_tower_toolpaths(build_volume, str_tool_colors);
    for (const PrintObject* object : print->objects())
        _load_print_object_toolpaths(*object, build_volume, str_tool_colors, color_print_values);
    _set_warning_notification_if_needed(EWarning::ToolpathOutside);
}
References _load_print_object_toolpaths(), _load_print_toolpaths(), _load_wipe_tower_toolpaths(), _set_current(), _set_warning_notification_if_needed(), Slic3r::GUI::Bed3D::build_volume(), fff_print(), m_bed, Slic3r::Print::objects(), reset_volumes(), and ToolpathOutside.
Referenced by Slic3r::GUI::Preview::load_print_as_fff().
load_sla_preview()
void Slic3r::GUI::GLCanvas3D::load_sla_preview ()
{
    const SLAPrint* print = sla_print();
    if (m_canvas != nullptr && print != nullptr) {
        _set_current();
      // Release OpenGL data before generating new data.
      reset_volumes();
        _load_sla_shells();
        _update_sla_shells_outside_state();
        _set_warning_notification_if_needed(EWarning::ObjectClashed);
        _set_warning_notification_if_needed(EWarning::SlaSupportsOutside);
    }
}
References _load_sla_shells(), _set_current(), _set_warning_notification_if_needed(), _update_sla_shells_outside_state(), m_canvas, ObjectClashed, reset_volumes(), sla_print(), and SlaSupportsOutside.
Referenced by Slic3r::GUI::Preview::load_print_as_sla().
mirror_selection()
void Slic3r::GUI::GLCanvas3D::mirror_selection (Axis axis)
{
    TransformationType transformation_type;
    if (wxGetApp().obj_manipul()->is_local_coordinates())
        transformation_type.set_local();
    else if (wxGetApp().obj_manipul()->is_instance_coordinates())
        transformation_type.set_instance();
    transformation_type.set_relative();
    m_selection.setup_cache();
    m_selection.mirror(axis, transformation_type);
    do_mirror(L("Mirror Object"));
    wxGetApp().obj_manipul()->set_dirty();
}
References do_mirror(), L, m_selection, Slic3r::GUI::Selection::mirror(), Slic3r::GUI::TransformationType::set_instance(), Slic3r::GUI::TransformationType::set_local(), Slic3r::GUI::TransformationType::set_relative(), and Slic3r::GUI::Selection::setup_cache().
Referenced by Slic3r::GUI::View3D::mirror_selection().
mouse_ray()
Linef3 Slic3r::GUI::GLCanvas3D::mouse_ray (const Point & mouse_pos)
{
    float z0 = 0.0f;
    float z1 = 1.0f;
    return Linef3(_mouse_to_3d(mouse_pos, &z0), _mouse_to_3d(mouse_pos, &z1));
}
References _mouse_to_3d().
Referenced by on_mouse(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
mouse_up_cleanup()
void Slic3r::GUI::GLCanvas3D::mouse_up_cleanup ()
{
    m_moving = false;
    m_mouse.drag.move_volume_idx = -1;
    m_mouse.set_start_position_3D_as_invalid();
    m_mouse.set_start_position_2D_as_invalid();
    m_mouse.dragging = false;
    m_mouse.ignore_left_up = false;
    m_dirty = true;
    if (m_canvas->HasCapture())
        m_canvas->ReleaseMouse();
}
References Slic3r::GUI::GLCanvas3D::Mouse::drag, Slic3r::GUI::GLCanvas3D::Mouse::dragging, Slic3r::GUI::GLCanvas3D::Mouse::ignore_left_up, m_canvas, m_dirty, m_mouse, m_moving, Slic3r::GUI::GLCanvas3D::Mouse::Drag::move_volume_idx, Slic3r::GUI::GLCanvas3D::Mouse::set_start_position_2D_as_invalid(), and Slic3r::GUI::GLCanvas3D::Mouse::set_start_position_3D_as_invalid().
Referenced by Slic3r::GUI::GLGizmoBase::do_stop_dragging(), and on_mouse().
msw_rescale()
void Slic3r::GUI::GLCanvas3D::msw_rescale ()
{
    m_gcode_viewer.invalidate_legend();
}
References Slic3r::GUI::GCodeViewer::invalidate_legend(), and m_gcode_viewer.
Referenced by Slic3r::GUI::Preview::msw_rescale().
on_char()
void Slic3r::GUI::GLCanvas3D::on_char (wxKeyEvent & evt)
{
    if (!m_initialized)
        return;
#ifdef SHOW_IMGUI_DEMO_WINDOW
    static int cur = 0;
    if (wxString("demo")[cur] == evt.GetUnicodeKey()) ++cur; else cur = 0;
    if (cur == 4) { show_imgui_demo_window = !show_imgui_demo_window; cur = 0;}
#endif // SHOW_IMGUI_DEMO_WINDOW
    auto imgui = wxGetApp().imgui();
    if (imgui->update_key_data(evt)) {
        render();
        return;
    }
    // see include/wx/defs.h enum wxKeyCode
    int keyCode = evt.GetKeyCode();
    int ctrlMask = wxMOD_CONTROL;
    int shiftMask = wxMOD_SHIFT;
    if (keyCode == WXK_ESCAPE && (_deactivate_undo_redo_toolbar_items() || _deactivate_search_toolbar_item() || _deactivate_arrange_menu()))
        return;
    if (m_gizmos.on_char(evt))
        return;
    if ((evt.GetModifiers() & ctrlMask) != 0) {
        // CTRL is pressed
        switch (keyCode) {
#ifdef __APPLE__
        case 'a':
        case 'A':
#else /* __APPLE__ */
        case WXK_CONTROL_A:
#endif /* __APPLE__ */
            post_event(SimpleEvent(EVT_GLCANVAS_SELECT_ALL));
        break;
#ifdef __APPLE__
        case 'c':
        case 'C':
#else /* __APPLE__ */
        case WXK_CONTROL_C:
#endif /* __APPLE__ */
            post_event(SimpleEvent(EVT_GLTOOLBAR_COPY));
        break;
#ifdef __APPLE__
        case 'f':
        case 'F':
#else /* __APPLE__ */
        case WXK_CONTROL_F:
#endif /* __APPLE__ */
            _activate_search_toolbar_item();
            break;
#ifdef __APPLE__
        case 'm':
        case 'M':
#else /* __APPLE__ */
        case WXK_CONTROL_M:
#endif /* __APPLE__ */
        {
#ifdef _WIN32
            if (wxGetApp().app_config->get_bool("use_legacy_3DConnexion")) {
#endif //_WIN32
#ifdef __APPLE__
            // On OSX use Cmd+Shift+M to "Show/Hide 3Dconnexion devices settings dialog"
            if ((evt.GetModifiers() & shiftMask) != 0) {
#endif // __APPLE__
                Mouse3DController& controller = wxGetApp().plater()->get_mouse3d_controller();
                controller.show_settings_dialog(!controller.is_settings_dialog_shown());
                m_dirty = true;
#ifdef __APPLE__
            }
            else
            // and Cmd+M to minimize application
                wxGetApp().mainframe->Iconize();
#endif // __APPLE__
#ifdef _WIN32
            }
#endif //_WIN32
            break;
        }
#ifdef __APPLE__
        case 'v':
        case 'V':
#else /* __APPLE__ */
        case WXK_CONTROL_V:
#endif /* __APPLE__ */
            post_event(SimpleEvent(EVT_GLTOOLBAR_PASTE));
        break;
#ifdef __APPLE__
        case 'y':
        case 'Y':
#else /* __APPLE__ */
        case WXK_CONTROL_Y:
#endif /* __APPLE__ */
            post_event(SimpleEvent(EVT_GLCANVAS_REDO));
        break;
#ifdef __APPLE__
        case 'z':
        case 'Z':
#else /* __APPLE__ */
        case WXK_CONTROL_Z:
#endif /* __APPLE__ */
            post_event(SimpleEvent(EVT_GLCANVAS_UNDO));
        break;
        case WXK_BACK:
        case WXK_DELETE:
             post_event(SimpleEvent(EVT_GLTOOLBAR_DELETE_ALL)); break;
        default:            evt.Skip();
        }
    } else {
        switch (keyCode)
        {
        case WXK_BACK:
        case WXK_DELETE: { post_event(SimpleEvent(EVT_GLTOOLBAR_DELETE)); break; }
        case WXK_ESCAPE: { deselect_all(); break; }
        case WXK_F5: {
            if ((wxGetApp().is_editor() && !wxGetApp().plater()->model().objects.empty()) ||
                (wxGetApp().is_gcode_viewer() && !wxGetApp().plater()->get_last_loaded_gcode().empty()))
                post_event(SimpleEvent(EVT_GLCANVAS_RELOAD_FROM_DISK));
            break;
        }
        case '0': { select_view("iso"); break; }
        case '1': { select_view("top"); break; }
        case '2': { select_view("bottom"); break; }
        case '3': { select_view("front"); break; }
        case '4': { select_view("rear"); break; }
        case '5': { select_view("left"); break; }
        case '6': { select_view("right"); break; }
        case '+': {
            if (dynamic_cast<Preview*>(m_canvas->GetParent()) != nullptr)
                post_event(wxKeyEvent(EVT_GLCANVAS_EDIT_COLOR_CHANGE, evt));
            else
                post_event(Event<int>(EVT_GLCANVAS_INCREASE_INSTANCES, +1));
            break;
        }
        case '-': {
            if (dynamic_cast<Preview*>(m_canvas->GetParent()) != nullptr)
                post_event(wxKeyEvent(EVT_GLCANVAS_EDIT_COLOR_CHANGE, evt));
            else
                post_event(Event<int>(EVT_GLCANVAS_INCREASE_INSTANCES, -1));
            break;
        }
        case '?': { post_event(SimpleEvent(EVT_GLCANVAS_QUESTION_MARK)); break; }
        case 'A':
        case 'a': { post_event(SimpleEvent(EVT_GLCANVAS_ARRANGE)); break; }
        case 'B':
        case 'b': { zoom_to_bed(); break; }
        case 'C':
        case 'c': { m_gcode_viewer.toggle_gcode_window_visibility(); m_dirty = true; request_extra_frame(); break; }
        case 'E':
        case 'e': { m_labels.show(!m_labels.is_shown()); m_dirty = true; break; }
        case 'G':
        case 'g': {
            if ((evt.GetModifiers() & shiftMask) != 0) {
                if (dynamic_cast<Preview*>(m_canvas->GetParent()) != nullptr)
                    post_event(wxKeyEvent(EVT_GLCANVAS_JUMP_TO, evt));
            }
            break;
        }
        case 'I':
        case 'i': { _update_camera_zoom(1.0); break; }
        case 'K':
        case 'k': { wxGetApp().plater()->get_camera().select_next_type(); m_dirty = true; break; }
        case 'L':
        case 'l': {
            if (!m_main_toolbar.is_enabled())
                show_legend(!is_legend_shown());
            break;
        }
        case 'O':
        case 'o': { _update_camera_zoom(-1.0); break; }
        case 'Z':
        case 'z': {
            if (!m_selection.is_empty())
                zoom_to_selection();
            else {
                if (!m_volumes.empty())
                    zoom_to_volumes();
                else
                    _zoom_to_box(m_gcode_viewer.get_paths_bounding_box());
            }
            break;
        }
        default:  { evt.Skip(); break; }
        }
    }
}
References _activate_search_toolbar_item(), _deactivate_arrange_menu(), _deactivate_search_toolbar_item(), _deactivate_undo_redo_toolbar_items(), _update_camera_zoom(), _zoom_to_box(), deselect_all(), Slic3r::GLVolumeCollection::empty(), Slic3r::empty(), Slic3r::GUI::GCodeViewer::get_paths_bounding_box(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLToolbar::is_enabled(), is_legend_shown(), Slic3r::GUI::Mouse3DController::is_settings_dialog_shown(), Slic3r::GUI::GLCanvas3D::Labels::is_shown(), m_canvas, m_dirty, m_gcode_viewer, m_gizmos, m_initialized, m_labels, m_main_toolbar, m_selection, m_volumes, Slic3r::GUI::GLGizmosManager::on_char(), Slic3r::GUI::plater(), post_event(), render(), request_extra_frame(), select_view(), Slic3r::GUI::GLCanvas3D::Labels::show(), show_imgui_demo_window, show_legend(), Slic3r::GUI::Mouse3DController::show_settings_dialog(), Slic3r::GUI::GCodeViewer::toggle_gcode_window_visibility(), Slic3r::GUI::ImGuiWrapper::update_key_data(), zoom_to_bed(), zoom_to_selection(), and zoom_to_volumes().
Referenced by bind_event_handlers(), Slic3r::GUI::Plater::search(), and unbind_event_handlers().
on_idle()
void Slic3r::GUI::GLCanvas3D::on_idle (wxIdleEvent & evt)
{
    if (!m_initialized)
        return;
    m_dirty |= m_main_toolbar.update_items_state();
    m_dirty |= m_undoredo_toolbar.update_items_state();
    m_dirty |= wxGetApp().plater()->get_view_toolbar().update_items_state();
    m_dirty |= wxGetApp().plater()->get_collapse_toolbar().update_items_state();
    bool mouse3d_controller_applied = wxGetApp().plater()->get_mouse3d_controller().apply(wxGetApp().plater()->get_camera());
    m_dirty |= mouse3d_controller_applied;
    m_dirty |= wxGetApp().plater()->get_notification_manager()->update_notifications(*this);
    auto gizmo = wxGetApp().plater()->canvas3D()->get_gizmos_manager().get_current();
    if (gizmo != nullptr) m_dirty |= gizmo->update_items_state();
    // ImGuiWrapper::m_requires_extra_frame may have been set by a render made outside of the OnIdle mechanism
    bool imgui_requires_extra_frame = wxGetApp().imgui()->requires_extra_frame();
    m_dirty |= imgui_requires_extra_frame;
    if (!m_dirty)
        return;
    // this needs to be done here.
    // during the render launched by the refresh the value may be set again
    wxGetApp().imgui()->reset_requires_extra_frame();
    _refresh_if_shown_on_screen();
    if (m_extra_frame_requested || mouse3d_controller_applied || imgui_requires_extra_frame || wxGetApp().imgui()->requires_extra_frame()) {
        m_extra_frame_requested = false;
        evt.RequestMore();
    }
    else
        m_dirty = false;
}
References _refresh_if_shown_on_screen(), m_dirty, m_extra_frame_requested, m_initialized, m_main_toolbar, m_undoredo_toolbar, Slic3r::GUI::plater(), and Slic3r::GUI::GLToolbar::update_items_state().
Referenced by bind_event_handlers(), and unbind_event_handlers().
on_key()
void Slic3r::GUI::GLCanvas3D::on_key (wxKeyEvent & evt)
{
    static TranslationProcessor translationProcessor(
        [this]() {
            do_move(L("Gizmo-Move"));
            m_gizmos.update_data();
            wxGetApp().obj_manipul()->set_dirty();
            // Let the plater know that the dragging finished, so a delayed refresh
            // of the scene with the background processing data should be performed.
            post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED));
            // updates camera target constraints
            refresh_camera_scene_box();
            m_dirty = true;
        },
        [this](const Vec3d& direction, bool slow, bool camera_space) {
            m_selection.setup_cache();
            double multiplier = slow ? 1.0 : 10.0;
            Vec3d displacement;
            if (camera_space) {
                Eigen::Matrix<double, 3, 3, Eigen::DontAlign> inv_view_3x3 = wxGetApp().plater()->get_camera().get_view_matrix().inverse().matrix().block(0, 0, 3, 3);
                displacement = multiplier * (inv_view_3x3 * direction);
                displacement.z() = 0.0;
            }
            else
                displacement = multiplier * direction;
            TransformationType trafo_type;
            trafo_type.set_relative();
            m_selection.translate(displacement, trafo_type);
            m_dirty = true;
        }
    );
    const int keyCode = evt.GetKeyCode();
    auto imgui = wxGetApp().imgui();
    if (imgui->update_key_data(evt)) {
        render();
    }
    else {
        if (!m_gizmos.on_key(evt)) {
            if (evt.GetEventType() == wxEVT_KEY_UP) {
                if (evt.ShiftDown() && evt.ControlDown() && keyCode == WXK_SPACE) {
                    wxGetApp().plater()->toggle_render_statistic_dialog();
                    m_dirty = true;
                }
                if (m_tab_down && keyCode == WXK_TAB && !evt.HasAnyModifiers()) {
                    // Enable switching between 3D and Preview with Tab
                    // m_canvas->HandleAsNavigationKey(evt);   // XXX: Doesn't work in some cases / on Linux
                    post_event(SimpleEvent(EVT_GLCANVAS_TAB));
                }
                else if (keyCode == WXK_TAB && evt.ShiftDown() && ! wxGetApp().is_gcode_viewer()) {
                    // Collapse side-panel with Shift+Tab
                    post_event(SimpleEvent(EVT_GLCANVAS_COLLAPSE_SIDEBAR));
                }
                else if (keyCode == WXK_SHIFT) {
                    translationProcessor.process(evt);
                    if (m_picking_enabled && m_rectangle_selection.is_dragging()) {
                        _update_selection_from_hover();
                        m_rectangle_selection.stop_dragging();
                        m_mouse.ignore_left_up = true;
                    }
                    m_shift_kar_filter.reset_count();
                    m_dirty = true;
//                    set_cursor(Standard);
                }
                else if (keyCode == WXK_ALT) {
                    if (m_picking_enabled && m_rectangle_selection.is_dragging()) {
                        _update_selection_from_hover();
                        m_rectangle_selection.stop_dragging();
                        m_mouse.ignore_left_up = true;
                        m_dirty = true;
                    }
//                    set_cursor(Standard);
                }
                else if (keyCode == WXK_CONTROL) {
                  if (m_mouse.dragging && !m_moving) {
                        // if the user releases CTRL while rotating the 3D scene
                        // prevent from moving the selected volume
                        m_mouse.drag.move_volume_idx = -1;
                        m_mouse.set_start_position_3D_as_invalid();
                    }
                    m_ctrl_kar_filter.reset_count();
                    m_dirty = true;
                }
                else if (m_gizmos.is_enabled() && !m_selection.is_empty()) {
                    translationProcessor.process(evt);
                    switch (keyCode)
                    {
                    case WXK_NUMPAD_PAGEUP:   case WXK_PAGEUP:
                    case WXK_NUMPAD_PAGEDOWN: case WXK_PAGEDOWN:
                    {
                        do_rotate(L("Gizmo-Rotate"));
                        m_gizmos.update_data();
                        wxGetApp().obj_manipul()->set_dirty();
                        // Let the plater know that the dragging finished, so a delayed refresh
                        // of the scene with the background processing data should be performed.
                        post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED));
                        // updates camera target constraints
                        refresh_camera_scene_box();
                        m_dirty = true;
                        break;
                    }
                    default: { break; }
                    }
                }
            }
            else if (evt.GetEventType() == wxEVT_KEY_DOWN) {
                m_tab_down = keyCode == WXK_TAB && !evt.HasAnyModifiers();
                if (keyCode == WXK_SHIFT) {
                    translationProcessor.process(evt);
                    if (m_picking_enabled && (m_gizmos.get_current_type() != GLGizmosManager::SlaSupports)) {
                        m_mouse.ignore_left_up = false;
//                        set_cursor(Cross);
                    }
                    if (m_shift_kar_filter.is_first())
                        m_dirty = true;
                    m_shift_kar_filter.increase_count();
                }
                else if (keyCode == WXK_ALT) {
                    if (m_picking_enabled && (m_gizmos.get_current_type() != GLGizmosManager::SlaSupports)) {
                        m_mouse.ignore_left_up = false;
//                        set_cursor(Cross);
                    }
                }
                else if (keyCode == WXK_CONTROL) {
                    if (m_ctrl_kar_filter.is_first())
                        m_dirty = true;
                    m_ctrl_kar_filter.increase_count();
                }
                else if (m_gizmos.is_enabled() && !m_selection.is_empty()) {
                    auto do_rotate = [this](double angle_z_rad) {
                        m_selection.setup_cache();
                        m_selection.rotate(Vec3d(0.0, 0.0, angle_z_rad), TransformationType(TransformationType::World_Relative_Joint));
                        m_dirty = true;
//                        wxGetApp().obj_manipul()->set_dirty();
                    };
                    translationProcessor.process(evt);
                    switch (keyCode)
                    {
                    case WXK_NUMPAD_PAGEUP:   case WXK_PAGEUP:   { do_rotate(0.25 * M_PI); break; }
                    case WXK_NUMPAD_PAGEDOWN: case WXK_PAGEDOWN: { do_rotate(-0.25 * M_PI); break; }
                    default: { break; }
                    }
                }
                else if (!m_gizmos.is_enabled()) {
                    // DoubleSlider navigation in Preview
                    if (keyCode == WXK_LEFT ||
                        keyCode == WXK_RIGHT ||
                        keyCode == WXK_UP ||
                        keyCode == WXK_DOWN) {
                        if (dynamic_cast<Preview*>(m_canvas->GetParent()) != nullptr)
                            post_event(wxKeyEvent(EVT_GLCANVAS_MOVE_SLIDERS, evt));
                    }
                }
            }
        }
    }
    if (keyCode != WXK_TAB
        && keyCode != WXK_LEFT
        && keyCode != WXK_UP
        && keyCode != WXK_RIGHT
        && keyCode != WXK_DOWN) {
        evt.Skip();   // Needed to have EVT_CHAR generated as well
    }
}
References _update_selection_from_hover(), do_move(), do_rotate(), Slic3r::GUI::GLCanvas3D::Mouse::drag, Slic3r::GUI::GLCanvas3D::Mouse::dragging, Slic3r::GUI::GLGizmosManager::get_current_type(), Slic3r::GUI::GLCanvas3D::Mouse::ignore_left_up, Slic3r::GUI::KeyAutoRepeatFilter::increase_count(), Slic3r::GUI::GLSelectionRectangle::is_dragging(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLGizmosManager::is_enabled(), Slic3r::GUI::KeyAutoRepeatFilter::is_first(), L, m_canvas, m_ctrl_kar_filter, m_dirty, m_gizmos, m_mouse, m_moving, M_PI, m_picking_enabled, m_rectangle_selection, m_selection, m_shift_kar_filter, m_tab_down, Slic3r::GUI::GLCanvas3D::Mouse::Drag::move_volume_idx, Slic3r::GUI::GLGizmosManager::on_key(), post_event(), refresh_camera_scene_box(), render(), Slic3r::GUI::KeyAutoRepeatFilter::reset_count(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::TransformationType::set_relative(), Slic3r::GUI::GLCanvas3D::Mouse::set_start_position_3D_as_invalid(), Slic3r::GUI::Selection::setup_cache(), Slic3r::GUI::GLGizmosManager::SlaSupports, Slic3r::GUI::GLSelectionRectangle::stop_dragging(), Slic3r::GUI::Selection::translate(), Slic3r::GUI::GLGizmosManager::update_data(), Slic3r::GUI::ImGuiWrapper::update_key_data(), and Slic3r::GUI::TransformationType::World_Relative_Joint.
Referenced by bind_event_handlers(), and unbind_event_handlers().
on_mouse()
void Slic3r::GUI::GLCanvas3D::on_mouse (wxMouseEvent & evt)
{
    if (!m_initialized || !_set_current())
        return;
#if ENABLE_RETINA_GL
    const float scale = m_retina_helper->get_scale_factor();
    evt.SetX(evt.GetX() * scale);
    evt.SetY(evt.GetY() * scale);
#endif
    Point pos(evt.GetX(), evt.GetY());
    ImGuiWrapper* imgui = wxGetApp().imgui();
    if (m_tooltip.is_in_imgui() && evt.LeftUp())
        // ignore left up events coming from imgui windows and not processed by them
        m_mouse.ignore_left_up = true;
    m_tooltip.set_in_imgui(false);
    if (imgui->update_mouse_data(evt)) {
        m_mouse.position = evt.Leaving() ? Vec2d(-1.0, -1.0) : pos.cast<double>();
        m_tooltip.set_in_imgui(true);
        render();
#ifdef SLIC3R_DEBUG_MOUSE_EVENTS
        printf((format_mouse_event_debug_message(evt) + " - Consumed by ImGUI\n").c_str());
#endif /* SLIC3R_DEBUG_MOUSE_EVENTS */
        m_dirty = true;
        // do not return if dragging or tooltip not empty to allow for tooltip update
        // also, do not return if the mouse is moving and also is inside MM gizmo to allow update seed fill selection
        if (!m_mouse.dragging && m_tooltip.is_empty() && (m_gizmos.get_current_type() != GLGizmosManager::MmuSegmentation || !evt.Moving()))
            return;
    }
#ifdef __WXMSW__
  bool on_enter_workaround = false;
    if (! evt.Entering() && ! evt.Leaving() && m_mouse.position.x() == -1.0) {
        // Workaround for SPE-832: There seems to be a mouse event sent to the window before evt.Entering()
        m_mouse.position = pos.cast<double>();
        render();
#ifdef SLIC3R_DEBUG_MOUSE_EVENTS
    printf((format_mouse_event_debug_message(evt) + " - OnEnter workaround\n").c_str());
#endif /* SLIC3R_DEBUG_MOUSE_EVENTS */
    on_enter_workaround = true;
    } else
#endif /* __WXMSW__ */
    {
#ifdef SLIC3R_DEBUG_MOUSE_EVENTS
    printf((format_mouse_event_debug_message(evt) + " - other\n").c_str());
#endif /* SLIC3R_DEBUG_MOUSE_EVENTS */
  }
    if (m_main_toolbar.on_mouse(evt, *this)) {
        if (evt.LeftUp() || evt.MiddleUp() || evt.RightUp())
            mouse_up_cleanup();
        m_mouse.set_start_position_3D_as_invalid();
        return;
    }
    if (m_undoredo_toolbar.on_mouse(evt, *this)) {
        if (evt.LeftUp() || evt.MiddleUp() || evt.RightUp())
            mouse_up_cleanup();
        m_mouse.set_start_position_3D_as_invalid();
        return;
    }
    if (wxGetApp().plater()->get_collapse_toolbar().on_mouse(evt, *this)) {
        if (evt.LeftUp() || evt.MiddleUp() || evt.RightUp())
            mouse_up_cleanup();
        m_mouse.set_start_position_3D_as_invalid();
        return;
    }
    if (wxGetApp().plater()->get_view_toolbar().on_mouse(evt, *this)) {
        if (evt.LeftUp() || evt.MiddleUp() || evt.RightUp())
            mouse_up_cleanup();
        m_mouse.set_start_position_3D_as_invalid();
        return;
    }
    for (GLVolume* volume : m_volumes.volumes) {
        volume->force_sinking_contours = false;
    }
    auto show_sinking_contours = [this]() {
        const Selection::IndicesList& idxs = m_selection.get_volume_idxs();
        for (unsigned int idx : idxs) {
            m_volumes.volumes[idx]->force_sinking_contours = true;
        }
        m_dirty = true;
    };
    if (m_gizmos.on_mouse(evt)) {
        if (wxWindow::FindFocus() != m_canvas)
            // Grab keyboard focus for input in gizmo dialogs.
            m_canvas->SetFocus();
        if (evt.LeftUp() || evt.MiddleUp() || evt.RightUp())
            mouse_up_cleanup();
        m_mouse.set_start_position_3D_as_invalid();
        m_mouse.position = pos.cast<double>();
        // It should be detection of volume change
        // Not only detection of some modifiers !!!
        if (evt.Dragging()) {
            GLGizmosManager::EType c = m_gizmos.get_current_type();
            if (c == GLGizmosManager::EType::Move ||
                c == GLGizmosManager::EType::Scale ||
                c == GLGizmosManager::EType::Rotate) {
                show_sinking_contours();
                if (current_printer_technology() == ptFFF && fff_print()->config().complete_objects)
                    update_sequential_clearance(true);
            }
        }
        else if (evt.LeftUp() &&
            m_gizmos.get_current_type() == GLGizmosManager::EType::Scale &&
            m_gizmos.get_current()->get_state() == GLGizmoBase::EState::On) {
            wxGetApp().obj_list()->selection_changed();
        }
        return;
    }
    bool any_gizmo_active = m_gizmos.get_current() != nullptr;
    int selected_object_idx = m_selection.get_object_idx();
    int layer_editing_object_idx = is_layers_editing_enabled() ? selected_object_idx : -1;
    m_layers_editing.select_object(*m_model, layer_editing_object_idx);
    if (m_mouse.drag.move_requires_threshold && m_mouse.is_move_start_threshold_position_2D_defined() && m_mouse.is_move_threshold_met(pos)) {
        m_mouse.drag.move_requires_threshold = false;
        m_mouse.set_move_start_threshold_position_2D_as_invalid();
    }
    if (evt.ButtonDown() && wxWindow::FindFocus() != m_canvas)
        // Grab keyboard focus on any mouse click event.
        m_canvas->SetFocus();
    if (evt.Entering()) {
        if (m_mouse.dragging && !evt.LeftIsDown() && !evt.RightIsDown() && !evt.MiddleIsDown()) {
            // ensure to stop layers editing if enabled
            if (m_layers_editing.state != LayersEditing::Unknown) {
                m_layers_editing.state = LayersEditing::Unknown;
                _stop_timer();
                m_layers_editing.accept_changes(*this);
            }
            mouse_up_cleanup();
        }
//#if defined(__WXMSW__) || defined(__linux__)
//        // On Windows and Linux needs focus in order to catch key events
        // Set focus in order to remove it from object list
        if (m_canvas != nullptr) {
            // Only set focus, if the top level window of this canvas is active
            // and ObjectList has a focus
            auto p = dynamic_cast<wxWindow*>(evt.GetEventObject());
            while (p->GetParent())
                p = p->GetParent();
#ifdef __WIN32__
            wxWindow* const obj_list = wxGetApp().obj_list()->GetMainWindow();
#else
            wxWindow* const obj_list = wxGetApp().obj_list();
#endif
            if (obj_list == p->FindFocus())
                m_canvas->SetFocus();
            m_mouse.position = pos.cast<double>();
            m_tooltip_enabled = false;
            // 1) forces a frame render to ensure that m_hover_volume_idxs is updated even when the user right clicks while
            // the context menu is shown, ensuring it to disappear if the mouse is outside any volume and to
            // change the volume hover state if any is under the mouse
            // 2) when switching between 3d view and preview the size of the canvas changes if the side panels are visible,
            // so forces a resize to avoid multiple renders with different sizes (seen as flickering)
            _refresh_if_shown_on_screen();
            m_tooltip_enabled = true;
        }
        m_mouse.set_start_position_2D_as_invalid();
//#endif
    }
    else if (evt.Leaving()) {
        _deactivate_undo_redo_toolbar_items();
        if (m_layers_editing.state != LayersEditing::Unknown)
            m_layers_editing.state = LayersEditing::Paused;
        // to remove hover on objects when the mouse goes out of this canvas
        m_mouse.position = Vec2d(-1.0, -1.0);
        m_dirty = true;
    }
    else if (evt.LeftDown() || evt.RightDown() || evt.MiddleDown()) {
        if (_deactivate_undo_redo_toolbar_items() || _deactivate_search_toolbar_item() || _deactivate_arrange_menu())
            return;
        // If user pressed left or right button we first check whether this happened
        // on a volume or not.
        m_layers_editing.state = LayersEditing::Unknown;
        if (layer_editing_object_idx != -1 && m_layers_editing.bar_rect_contains(*this, pos(0), pos(1))) {
            // A volume is selected and the mouse is inside the layer thickness bar.
            // Start editing the layer height.
            m_layers_editing.state = LayersEditing::Editing;
            _perform_layer_editing_action(&evt);
        }
        else {
            const bool rectangle_selection_dragging = m_rectangle_selection.is_dragging();
            if (evt.LeftDown() && (evt.ShiftDown() || evt.AltDown()) && m_picking_enabled) {
                if (m_gizmos.get_current_type() != GLGizmosManager::SlaSupports &&
                    m_gizmos.get_current_type() != GLGizmosManager::FdmSupports &&
                    m_gizmos.get_current_type() != GLGizmosManager::Seam &&
                    m_gizmos.get_current_type() != GLGizmosManager::Cut &&
                    m_gizmos.get_current_type() != GLGizmosManager::Measure &&
                    m_gizmos.get_current_type() != GLGizmosManager::MmuSegmentation) {
                    m_rectangle_selection.start_dragging(m_mouse.position, evt.ShiftDown() ? GLSelectionRectangle::EState::Select : GLSelectionRectangle::EState::Deselect);
                    m_dirty = true;
                }
            }
            // Select volume in this 3D canvas.
            // Don't deselect a volume if layer editing is enabled or any gizmo is active. We want the object to stay selected
            // during the scene manipulation.
            if (m_picking_enabled && (!any_gizmo_active || !evt.CmdDown()) && (!m_hover_volume_idxs.empty() || !is_layers_editing_enabled()) && !rectangle_selection_dragging) {
                if (evt.LeftDown() && !m_hover_volume_idxs.empty()) {
                    int volume_idx = get_first_hover_volume_idx();
                    bool already_selected = m_selection.contains_volume(volume_idx);
                    bool shift_down = evt.ShiftDown();
                    Selection::IndicesList curr_idxs = m_selection.get_volume_idxs();
                    if (already_selected && shift_down)
                        m_selection.remove(volume_idx);
                    else {
                        m_selection.add(volume_idx, !shift_down, true);
                        m_mouse.drag.move_requires_threshold = !already_selected;
                        if (already_selected)
                            m_mouse.set_move_start_threshold_position_2D_as_invalid();
                        else
                            m_mouse.drag.move_start_threshold_position_2D = pos;
                    }
                    // propagate event through callback
                    if (curr_idxs != m_selection.get_volume_idxs()) {
                        if (m_selection.is_empty())
                            m_gizmos.reset_all_states();
                        else
                            m_gizmos.refresh_on_off_state();
                        m_gizmos.update_data();
                        post_event(SimpleEvent(EVT_GLCANVAS_OBJECT_SELECT));
                        m_dirty = true;
                    }
                }
            }
            if (!m_hover_volume_idxs.empty() && !m_rectangle_selection.is_dragging()) {
                if (evt.LeftDown() && m_moving_enabled && m_mouse.drag.move_volume_idx == -1) {
                    // Only accept the initial position, if it is inside the volume bounding box.
                    const int volume_idx = get_first_hover_volume_idx();
                    BoundingBoxf3 volume_bbox = m_volumes.volumes[volume_idx]->transformed_bounding_box();
                    volume_bbox.offset(1.0);
                    const bool is_cut_connector_selected = m_selection.is_any_connector();
                    if ((!any_gizmo_active || !evt.CmdDown()) && volume_bbox.contains(m_mouse.scene_position) && !is_cut_connector_selected) {
                        m_volumes.volumes[volume_idx]->hover = GLVolume::HS_None;
                        // The dragging operation is initiated.
                        m_mouse.drag.move_volume_idx = volume_idx;
                        m_selection.setup_cache();
                        if (!evt.CmdDown())
                            m_mouse.drag.start_position_3D = m_mouse.scene_position;
                        m_sequential_print_clearance_first_displacement = true;
                    }
                }
            }
        }
    }
    else if (evt.Dragging() && evt.LeftIsDown() && !evt.CmdDown() && m_layers_editing.state == LayersEditing::Unknown &&
             m_mouse.drag.move_volume_idx != -1 && m_mouse.is_start_position_3D_defined()) {
        if (!m_mouse.drag.move_requires_threshold) {
            m_mouse.dragging = true;
            Vec3d cur_pos = m_mouse.drag.start_position_3D;
            // we do not want to translate objects if the user just clicked on an object while pressing shift to remove it from the selection and then drag
            if (m_selection.contains_volume(get_first_hover_volume_idx())) {
                const Camera& camera = wxGetApp().plater()->get_camera();
                if (std::abs(camera.get_dir_forward().z()) < EPSILON) {
                    // side view -> move selected volumes orthogonally to camera view direction
                    const Linef3 ray = mouse_ray(pos);
                    const Vec3d dir = ray.unit_vector();
                    // finds the intersection of the mouse ray with the plane parallel to the camera viewport and passing throught the starting position
                    // use ray-plane intersection see i.e. https://en.wikipedia.org/wiki/Line%E2%80%93plane_intersection algebric form
                    // in our case plane normal and ray direction are the same (orthogonal view)
                    // when moving to perspective camera the negative z unit axis of the camera needs to be transformed in world space and used as plane normal
                    const Vec3d inters = ray.a + (m_mouse.drag.start_position_3D - ray.a).dot(dir) / dir.squaredNorm() * dir;
                    // vector from the starting position to the found intersection
                    const Vec3d inters_vec = inters - m_mouse.drag.start_position_3D;
                    const Vec3d camera_right = camera.get_dir_right();
                    const Vec3d camera_up = camera.get_dir_up();
                    // finds projection of the vector along the camera axes
                    const double projection_x = inters_vec.dot(camera_right);
                    const double projection_z = inters_vec.dot(camera_up);
                    // apply offset
                    cur_pos = m_mouse.drag.start_position_3D + projection_x * camera_right + projection_z * camera_up;
                }
                else {
                    // Generic view
                    // Get new position at the same Z of the initial click point.
                    cur_pos = mouse_ray(pos).intersect_plane(m_mouse.drag.start_position_3D.z());
                }
            }
            m_moving = true;
            TransformationType trafo_type;
            trafo_type.set_relative();
            m_selection.translate(cur_pos - m_mouse.drag.start_position_3D, trafo_type);
            if (current_printer_technology() == ptFFF && fff_print()->config().complete_objects)
                update_sequential_clearance(false);
            wxGetApp().obj_manipul()->set_dirty();
            m_dirty = true;
        }
    }
    else if (evt.Dragging() && evt.LeftIsDown() && m_picking_enabled && m_rectangle_selection.is_dragging()) {
        // keeps the mouse position updated while dragging the selection rectangle
        m_mouse.position = pos.cast<double>();
        m_rectangle_selection.dragging(m_mouse.position);
        m_dirty = true;
    }
    else if (evt.Dragging()) {
        m_mouse.dragging = true;
        if (m_layers_editing.state != LayersEditing::Unknown && layer_editing_object_idx != -1) {
            if (m_layers_editing.state == LayersEditing::Editing) {
                _perform_layer_editing_action(&evt);
                m_mouse.position = pos.cast<double>();
            }
        }
        // do not process the dragging if the left mouse was set down in another canvas
        else if (evt.LeftIsDown()) {
            // if dragging over blank area with left button, rotate
            if (!m_moving) {
                if ((any_gizmo_active || evt.CmdDown() || m_hover_volume_idxs.empty()) && m_mouse.is_start_position_3D_defined()) {
                    const Vec3d rot = (Vec3d(pos.x(), pos.y(), 0.0) - m_mouse.drag.start_position_3D) * (PI * TRACKBALLSIZE / 180.0);
                    if (wxGetApp().app_config->get_bool("use_free_camera"))
                        // Virtual track ball (similar to the 3DConnexion mouse).
                        wxGetApp().plater()->get_camera().rotate_local_around_target(Vec3d(rot.y(), rot.x(), 0.0));
                    else {
                        // Forces camera right vector to be parallel to XY plane in case it has been misaligned using the 3D mouse free rotation.
                        // It is cheaper to call this function right away instead of testing wxGetApp().plater()->get_mouse3d_controller().connected(),
                        // which checks an atomics (flushes CPU caches).
                        // See GH issue #3816.
                        Camera& camera = wxGetApp().plater()->get_camera();
                        camera.recover_from_free_camera();
                        camera.rotate_on_sphere(rot.x(), rot.y(), current_printer_technology() != ptSLA);
                    }
                    m_dirty = true;
                }
                m_mouse.drag.start_position_3D = Vec3d((double)pos.x(), (double)pos.y(), 0.0);
            }
        }
        else if (evt.MiddleIsDown() || evt.RightIsDown()) {
            // If dragging over blank area with right/middle button, pan.
            if (m_mouse.is_start_position_2D_defined()) {
                // get point in model space at Z = 0
                float z = 0.0f;
                const Vec3d cur_pos = _mouse_to_3d(pos, &z);
                const Vec3d orig = _mouse_to_3d(m_mouse.drag.start_position_2D, &z);
                Camera& camera = wxGetApp().plater()->get_camera();
                if (!wxGetApp().app_config->get_bool("use_free_camera"))
                    // Forces camera right vector to be parallel to XY plane in case it has been misaligned using the 3D mouse free rotation.
                    // It is cheaper to call this function right away instead of testing wxGetApp().plater()->get_mouse3d_controller().connected(),
                    // which checks an atomics (flushes CPU caches).
                    // See GH issue #3816.
                    camera.recover_from_free_camera();
                camera.set_target(camera.get_target() + orig - cur_pos);
                m_dirty = true;
            }
            m_mouse.drag.start_position_2D = pos;
        }
    }
    else if (evt.LeftUp() || evt.MiddleUp() || evt.RightUp()) {
        m_mouse.position = pos.cast<double>();
        if (m_layers_editing.state != LayersEditing::Unknown) {
            m_layers_editing.state = LayersEditing::Unknown;
            _stop_timer();
            m_layers_editing.accept_changes(*this);
        }
        else if (m_mouse.drag.move_volume_idx != -1 && m_mouse.dragging) {
            do_move(L("Move Object"));
            wxGetApp().obj_manipul()->set_dirty();
            // Let the plater know that the dragging finished, so a delayed refresh
            // of the scene with the background processing data should be performed.
            post_event(SimpleEvent(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED));
        }
        else if (evt.LeftUp() && m_picking_enabled && m_rectangle_selection.is_dragging()) {
            if (evt.ShiftDown() || evt.AltDown())
                _update_selection_from_hover();
            m_rectangle_selection.stop_dragging();
        }
        else if (evt.LeftUp() && !m_mouse.ignore_left_up && !m_mouse.dragging && m_hover_volume_idxs.empty() && !is_layers_editing_enabled()) {
            // deselect and propagate event through callback
            if (!evt.ShiftDown() && (!any_gizmo_active || !evt.CmdDown()) && m_picking_enabled)
                deselect_all();
        }
        else if (evt.RightUp()) {
            // forces a frame render to ensure that m_hover_volume_idxs is updated even when the user right clicks while
            // the context menu is already shown
            render();
            if (!m_hover_volume_idxs.empty()) {
                // if right clicking on volume, propagate event through callback (shows context menu)
                int volume_idx = get_first_hover_volume_idx();
                if (!m_volumes.volumes[volume_idx]->is_wipe_tower // no context menu for the wipe tower
                    && (m_gizmos.get_current_type() != GLGizmosManager::SlaSupports && m_gizmos.get_current_type() != GLGizmosManager::Measure))  // disable context menu when the gizmo is open
                {
                    // forces the selection of the volume
                    /* m_selection.add(volume_idx); // #et_FIXME_if_needed
                     * To avoid extra "Add-Selection" snapshots,
                     * call add() with check_for_already_contained=true
                     * */
                    m_selection.add(volume_idx, true, true);
                    m_gizmos.refresh_on_off_state();
                    post_event(SimpleEvent(EVT_GLCANVAS_OBJECT_SELECT));
                    m_gizmos.update_data();
                    wxGetApp().obj_manipul()->set_dirty();
                    // forces a frame render to update the view before the context menu is shown
                    render();
                }
            }
            Vec2d logical_pos = pos.cast<double>();
#if ENABLE_RETINA_GL
            const float factor = m_retina_helper->get_scale_factor();
            logical_pos = logical_pos.cwiseQuotient(Vec2d(factor, factor));
#endif // ENABLE_RETINA_GL
            if (!m_mouse.dragging) {
                // do not post the event if the user is panning the scene
                // or if right click was done over the wipe tower
                const bool post_right_click_event = (m_hover_volume_idxs.empty() || !m_volumes.volumes[get_first_hover_volume_idx()]->is_wipe_tower) &&
                    m_gizmos.get_current_type() != GLGizmosManager::Measure;
                if (post_right_click_event)
                    post_event(RBtnEvent(EVT_GLCANVAS_RIGHT_CLICK, { logical_pos, m_hover_volume_idxs.empty() }));
            }
        }
        mouse_up_cleanup();
    }
    else if (evt.Moving()) {
        m_mouse.position = pos.cast<double>();
        // updates gizmos overlay
        if (m_selection.is_empty())
            m_gizmos.reset_all_states();
        m_dirty = true;
    }
    else
        evt.Skip();
    // Detection of doubleclick on text to open emboss edit window
    auto type = m_gizmos.get_current_type();
    if (evt.LeftDClick() && !m_hover_volume_idxs.empty() &&
        (type == GLGizmosManager::EType::Undefined ||
         type == GLGizmosManager::EType::Move ||
         type == GLGizmosManager::EType::Rotate ||
         type == GLGizmosManager::EType::Scale ||
         type == GLGizmosManager::EType::Emboss) ) {
        for (int hover_volume_id : m_hover_volume_idxs) {
            const GLVolume &hover_gl_volume = *m_volumes.volumes[hover_volume_id];
            int object_idx = hover_gl_volume.object_idx();
            if (object_idx < 0 || static_cast<size_t>(object_idx) >= m_model->objects.size()) continue;
            const ModelObject* hover_object = m_model->objects[object_idx];
            int hover_volume_idx = hover_gl_volume.volume_idx();
            if (hover_volume_idx < 0 || static_cast<size_t>(hover_volume_idx) >= hover_object->volumes.size()) continue;
            const ModelVolume* hover_volume = hover_object->volumes[hover_volume_idx];
            if (!hover_volume->text_configuration.has_value()) continue;
            m_selection.add_volumes(Selection::EMode::Volume, {(unsigned) hover_volume_id});
            if (type != GLGizmosManager::EType::Emboss)
                m_gizmos.open_gizmo(GLGizmosManager::EType::Emboss);
            wxGetApp().obj_list()->update_selections();
            return;
        }
    }
    if (m_moving)
        show_sinking_contours();
#ifdef __WXMSW__
  if (on_enter_workaround)
    m_mouse.position = Vec2d(-1., -1.);
#endif /* __WXMSW__ */
}
References _deactivate_arrange_menu(), _deactivate_search_toolbar_item(), _deactivate_undo_redo_toolbar_items(), _mouse_to_3d(), _perform_layer_editing_action(), _refresh_if_shown_on_screen(), _set_current(), _stop_timer(), _update_selection_from_hover(), Slic3r::Linef3::a, Slic3r::GUI::GLCanvas3D::LayersEditing::accept_changes(), Slic3r::GUI::Selection::add(), Slic3r::GUI::Selection::add_volumes(), Slic3r::GUI::GLCanvas3D::LayersEditing::bar_rect_contains(), Slic3r::BoundingBox3Base< PointType >::contains(), Slic3r::GUI::Selection::contains_volume(), current_printer_technology(), Slic3r::GUI::GLGizmosManager::Cut, Slic3r::GUI::GLSelectionRectangle::Deselect, deselect_all(), do_move(), Slic3r::dot(), Slic3r::GUI::GLCanvas3D::Mouse::drag, Slic3r::GUI::GLCanvas3D::Mouse::dragging, Slic3r::GUI::GLSelectionRectangle::dragging(), Slic3r::GUI::GLCanvas3D::LayersEditing::Editing, Slic3r::GUI::GLGizmosManager::Emboss, EPSILON, Slic3r::GUI::GLGizmosManager::FdmSupports, fff_print(), Slic3r::GUI::GLGizmosManager::get_current(), Slic3r::GUI::GLGizmosManager::get_current_type(), Slic3r::GUI::Camera::get_dir_forward(), Slic3r::GUI::Camera::get_dir_right(), Slic3r::GUI::Camera::get_dir_up(), get_first_hover_volume_idx(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::Camera::get_target(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GLVolume::HS_None, Slic3r::GUI::GLCanvas3D::Mouse::ignore_left_up, Slic3r::Linef3::intersect_plane(), Slic3r::GUI::Selection::is_any_connector(), Slic3r::GUI::GLSelectionRectangle::is_dragging(), Slic3r::GUI::GLCanvas3D::Tooltip::is_empty(), Slic3r::GUI::Selection::is_empty(), Slic3r::GUI::GLCanvas3D::Tooltip::is_in_imgui(), is_layers_editing_enabled(), Slic3r::GUI::GLCanvas3D::Mouse::is_move_start_threshold_position_2D_defined(), Slic3r::GUI::GLCanvas3D::Mouse::is_move_threshold_met(), Slic3r::GUI::GLCanvas3D::Mouse::is_start_position_2D_defined(), Slic3r::GUI::GLCanvas3D::Mouse::is_start_position_3D_defined(), L, m_canvas, m_dirty, m_gizmos, m_hover_volume_idxs, m_initialized, m_layers_editing, m_main_toolbar, m_model, m_mouse, m_moving, m_moving_enabled, m_picking_enabled, m_rectangle_selection, m_selection, m_sequential_print_clearance_first_displacement, m_tooltip, m_tooltip_enabled, m_undoredo_toolbar, m_volumes, Slic3r::GUI::GLGizmosManager::Measure, Slic3r::GUI::GLGizmosManager::MmuSegmentation, mouse_ray(), mouse_up_cleanup(), Slic3r::GUI::GLGizmosManager::Move, Slic3r::GUI::GLCanvas3D::Mouse::Drag::move_requires_threshold, Slic3r::GUI::GLCanvas3D::Mouse::Drag::move_start_threshold_position_2D, Slic3r::GUI::GLCanvas3D::Mouse::Drag::move_volume_idx, Slic3r::GUI::obj_list(), Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, Slic3r::BoundingBox3Base< PointType >::offset(), Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::GLGizmosManager::on_mouse(), on_mouse(), Slic3r::GUI::GLToolbar::on_mouse(), Slic3r::GUI::GLGizmosManager::open_gizmo(), Slic3r::GUI::GLCanvas3D::LayersEditing::Paused, PI, Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::Mouse::position, post_event(), Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::GUI::Camera::recover_from_free_camera(), Slic3r::GUI::GLGizmosManager::refresh_on_off_state(), Slic3r::GUI::Selection::remove(), render(), Slic3r::GUI::GLGizmosManager::reset_all_states(), Slic3r::GUI::GLGizmosManager::Rotate, Slic3r::GUI::Camera::rotate_on_sphere(), Slic3r::GUI::GLGizmosManager::Scale, scale(), Slic3r::GUI::GLCanvas3D::Mouse::scene_position, Slic3r::GUI::GLGizmosManager::Seam, Slic3r::GUI::GLSelectionRectangle::Select, Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::GUI::GLCanvas3D::Tooltip::set_in_imgui(), Slic3r::GUI::GLCanvas3D::Mouse::set_move_start_threshold_position_2D_as_invalid(), Slic3r::GUI::TransformationType::set_relative(), Slic3r::GUI::GLCanvas3D::Mouse::set_start_position_2D_as_invalid(), Slic3r::GUI::GLCanvas3D::Mouse::set_start_position_3D_as_invalid(), Slic3r::GUI::Camera::set_target(), Slic3r::GUI::Selection::setup_cache(), Slic3r::GUI::GLGizmosManager::SlaSupports, Slic3r::GUI::GLSelectionRectangle::start_dragging(), Slic3r::GUI::GLCanvas3D::Mouse::Drag::start_position_2D, Slic3r::GUI::GLCanvas3D::Mouse::Drag::start_position_3D, Slic3r::GUI::GLCanvas3D::LayersEditing::state, Slic3r::GUI::GLSelectionRectangle::stop_dragging(), Slic3r::ModelVolume::text_configuration, TRACKBALLSIZE, Slic3r::GUI::Selection::translate(), Slic3r::GUI::GLGizmosManager::Undefined, Slic3r::Linef3::unit_vector(), Slic3r::GUI::GLCanvas3D::LayersEditing::Unknown, Slic3r::GUI::GLGizmosManager::update_data(), Slic3r::GUI::ImGuiWrapper::update_mouse_data(), update_sequential_clearance(), Slic3r::GUI::Selection::Volume, Slic3r::GLVolume::volume_idx(), Slic3r::ModelObject::volumes, and Slic3r::GLVolumeCollection::volumes.
Referenced by bind_event_handlers(), on_mouse(), and unbind_event_handlers().
on_mouse_wheel()
void Slic3r::GUI::GLCanvas3D::on_mouse_wheel (wxMouseEvent & evt)
{
#ifdef WIN32
    // Try to filter out spurious mouse wheel events comming from 3D mouse.
    if (wxGetApp().plater()->get_mouse3d_controller().process_mouse_wheel())
        return;
#endif
    if (!m_initialized)
        return;
    // Ignore the wheel events if the middle button is pressed.
    if (evt.MiddleIsDown())
        return;
#if ENABLE_RETINA_GL
    const float scale = m_retina_helper->get_scale_factor();
    evt.SetX(evt.GetX() * scale);
    evt.SetY(evt.GetY() * scale);
#endif
    if (wxGetApp().imgui()->update_mouse_data(evt)) {
        m_dirty = true;
        return;
    }
#ifdef __WXMSW__
  // For some reason the Idle event is not being generated after the mouse scroll event in case of scrolling with the two fingers on the touch pad,
  // if the event is not allowed to be passed further.
  // https://github.com/prusa3d/PrusaSlicer/issues/2750
    // evt.Skip() used to trigger the needed screen refresh, but it does no more. wxWakeUpIdle() seem to work now.
    wxWakeUpIdle();
#endif /* __WXMSW__ */
    // Performs layers editing updates, if enabled
    if (is_layers_editing_enabled()) {
        int object_idx_selected = m_selection.get_object_idx();
        if (object_idx_selected != -1) {
            // A volume is selected. Test, whether hovering over a layer thickness bar.
            if (m_layers_editing.bar_rect_contains(*this, (float)evt.GetX(), (float)evt.GetY())) {
                // Adjust the width of the selection.
                m_layers_editing.band_width = std::max(std::min(m_layers_editing.band_width * (1.0f + 0.1f * (float)evt.GetWheelRotation() / (float)evt.GetWheelDelta()), 10.0f), 1.5f);
                if (m_canvas != nullptr)
                    m_canvas->Refresh();
                return;
            }
        }
    }
    // If the Search window or Undo/Redo list is opened,
    // update them according to the event
    if (m_main_toolbar.is_item_pressed("search")    ||
        m_undoredo_toolbar.is_item_pressed("undo")  ||
        m_undoredo_toolbar.is_item_pressed("redo")) {
        m_mouse_wheel = int((double)evt.GetWheelRotation() / (double)evt.GetWheelDelta());
        return;
    }
    // Inform gizmos about the event so they have the opportunity to react.
    if (m_gizmos.on_mouse_wheel(evt))
        return;
    // Calculate the zoom delta and apply it to the current zoom factor
    const double direction_factor = wxGetApp().app_config->get_bool("reverse_mouse_wheel_zoom") ? -1.0 : 1.0;
    const double delta = direction_factor * (double)evt.GetWheelRotation() / (double)evt.GetWheelDelta();
    if (wxGetKeyState(WXK_SHIFT)) {
        const auto cnv_size = get_canvas_size();
        const Vec3d screen_center_3d_pos = _mouse_to_3d({ cnv_size.get_width() * 0.5, cnv_size.get_height() * 0.5 });
        const Vec3d mouse_3d_pos = _mouse_to_3d({ evt.GetX(), evt.GetY() });
        const Vec3d displacement = mouse_3d_pos - screen_center_3d_pos;
        wxGetApp().plater()->get_camera().translate_world(displacement);
        const double origin_zoom = wxGetApp().plater()->get_camera().get_zoom();
        _update_camera_zoom(delta);
        const double new_zoom = wxGetApp().plater()->get_camera().get_zoom();
        wxGetApp().plater()->get_camera().translate_world((-displacement) / (new_zoom / origin_zoom));
    }
    else
        _update_camera_zoom(delta);
}
References _mouse_to_3d(), _update_camera_zoom(), Slic3r::GUI::GLCanvas3D::LayersEditing::band_width, Slic3r::GUI::GLCanvas3D::LayersEditing::bar_rect_contains(), get_canvas_size(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLToolbar::is_item_pressed(), is_layers_editing_enabled(), m_canvas, m_dirty, m_gizmos, m_initialized, m_layers_editing, m_main_toolbar, m_mouse_wheel, m_selection, m_undoredo_toolbar, Slic3r::GUI::GLGizmosManager::on_mouse_wheel(), Slic3r::GUI::plater(), Slic3r::GUI::process_mouse_wheel(), and scale().
Referenced by bind_event_handlers(), and unbind_event_handlers().
on_paint()
void Slic3r::GUI::GLCanvas3D::on_paint (wxPaintEvent & evt)
{
    if (m_initialized)
        m_dirty = true;
    else
        // Call render directly, so it gets initialized immediately, not from On Idle handler.
        this->render();
}
References m_dirty, m_initialized, and render().
Referenced by bind_event_handlers(), and unbind_event_handlers().
on_render_timer()
void Slic3r::GUI::GLCanvas3D::on_render_timer (wxTimerEvent & evt)
{
    // no need to wake up idle
    // right after this event, idle event is fired
    // m_dirty = true;
    // wxWakeUpIdle();
}
Referenced by bind_event_handlers(), and unbind_event_handlers().
on_set_focus()
void Slic3r::GUI::GLCanvas3D::on_set_focus (wxFocusEvent & evt)
{
    m_tooltip_enabled = false;
    _refresh_if_shown_on_screen();
    m_tooltip_enabled = true;
}
References _refresh_if_shown_on_screen(), and m_tooltip_enabled.
Referenced by bind_event_handlers(), and unbind_event_handlers().
on_size()
void Slic3r::GUI::GLCanvas3D::on_size (wxSizeEvent & evt)
{
    m_dirty = true;
}
References m_dirty.
Referenced by bind_event_handlers(), and unbind_event_handlers().
on_timer()
void Slic3r::GUI::GLCanvas3D::on_timer (wxTimerEvent & evt)
{
    if (m_layers_editing.state == LayersEditing::Editing)
        _perform_layer_editing_action();
}
References _perform_layer_editing_action(), Slic3r::GUI::GLCanvas3D::LayersEditing::Editing, m_layers_editing, and Slic3r::GUI::GLCanvas3D::LayersEditing::state.
Referenced by bind_event_handlers(), and unbind_event_handlers().
post_event()
void Slic3r::GUI::GLCanvas3D::post_event (wxEvent && event)
{
    event.SetEventObject(m_canvas);
    wxPostEvent(m_canvas, event);
}
References m_canvas.
Referenced by _init_undoredo_toolbar(), Slic3r::GUI::GLCanvas3D::LayersEditing::adaptive_layer_height_profile(), Slic3r::GUI::ObjectList::del_info_item(), deselect_all(), do_mirror(), do_move(), do_reset_skew(), do_rotate(), do_scale(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), on_char(), on_key(), on_mouse(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), reload_scene(), render(), Slic3r::GUI::GLCanvas3D::LayersEditing::reset_layer_height_profile(), select_all(), Slic3r::GUI::GLCanvas3D::LayersEditing::smooth_layer_height_profile(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
refresh_camera_scene_box()
void Slic3r::GUI::GLCanvas3D::refresh_camera_scene_box ()
{
    wxGetApp().plater()->get_camera().set_scene_box(scene_bounding_box());
}
References scene_bounding_box().
Referenced by bed_shape_changed(), Slic3r::GUI::GLGizmoBase::do_stop_dragging(), on_key(), and reload_scene().
refresh_gcode_preview_render_paths()
void Slic3r::GUI::GLCanvas3D::refresh_gcode_preview_render_paths (bool keep_sequential_current_first, bool keep_sequential_current_last)
{
    m_gcode_viewer.refresh_render_paths(keep_sequential_current_first, keep_sequential_current_last);
    set_as_dirty();
    request_extra_frame();
}
References m_gcode_viewer, Slic3r::GUI::GCodeViewer::refresh_render_paths(), request_extra_frame(), and set_as_dirty().
reload_scene()
void Slic3r::GUI::GLCanvas3D::reload_scene (bool refresh_immediately, bool force_full_scene_refresh = false)
{
    if (m_canvas == nullptr || m_config == nullptr || m_model == nullptr)
        return;
    if (!m_initialized)
        return;
    _set_current();
    m_hover_volume_idxs.clear();
    struct ModelVolumeState {
        ModelVolumeState(const GLVolume* volume) :
            model_volume(nullptr), geometry_id(volume->geometry_id), volume_idx(-1) {}
        ModelVolumeState(const ModelVolume* model_volume, const ObjectID& instance_id, const GLVolume::CompositeID& composite_id) :
            model_volume(model_volume), geometry_id(std::make_pair(model_volume->id().id, instance_id.id)), composite_id(composite_id), volume_idx(-1) {}
        ModelVolumeState(const ObjectID& volume_id, const ObjectID& instance_id) :
            model_volume(nullptr), geometry_id(std::make_pair(volume_id.id, instance_id.id)), volume_idx(-1) {}
        bool new_geometry() const { return this->volume_idx == size_t(-1); }
        const ModelVolume* model_volume;
        // ObjectID of ModelVolume + ObjectID of ModelInstance
        // or timestamp of an SLAPrintObjectStep + ObjectID of ModelInstance
        std::pair<size_t, size_t>   geometry_id;
        GLVolume::CompositeID       composite_id;
        // Volume index in the new GLVolume vector.
        size_t                      volume_idx;
    };
    std::vector<ModelVolumeState> model_volume_state;
    std::vector<ModelVolumeState> aux_volume_state;
    struct GLVolumeState {
        GLVolumeState() :
            volume_idx(size_t(-1)) {}
        GLVolumeState(const GLVolume* volume, unsigned int volume_idx) :
            composite_id(volume->composite_id), volume_idx(volume_idx) {}
        GLVolumeState(const GLVolume::CompositeID &composite_id) :
            composite_id(composite_id), volume_idx(size_t(-1)) {}
        GLVolume::CompositeID       composite_id;
        // Volume index in the old GLVolume vector.
        size_t                      volume_idx;
    };
    std::vector<std::pair<GLVolume::CompositeID, GLVolume::CompositeID>> new_to_old_ids_map;
    // SLA steps to pull the preview meshes for.
    typedef std::array<SLAPrintObjectStep, 3> SLASteps;
    SLASteps sla_steps = { slaposDrillHoles, slaposSupportTree, slaposPad };
    struct SLASupportState {
        std::array<PrintStateBase::StateWithTimeStamp, std::tuple_size<SLASteps>::value> step;
    };
    // State of the sla_steps for all SLAPrintObjects.
    std::vector<SLASupportState> sla_support_state;
    std::vector<size_t> instance_ids_selected;
    std::vector<size_t> map_glvolume_old_to_new(m_volumes.volumes.size(), size_t(-1));
    std::vector<GLVolumeState> deleted_volumes;
    std::vector<GLVolume*> glvolumes_new;
    glvolumes_new.reserve(m_volumes.volumes.size());
    auto model_volume_state_lower = [](const ModelVolumeState& m1, const ModelVolumeState& m2) { return m1.geometry_id < m2.geometry_id; };
    m_reload_delayed = !m_canvas->IsShown() && !refresh_immediately && !force_full_scene_refresh;
    PrinterTechnology printer_technology = current_printer_technology();
    int               volume_idx_wipe_tower_old = -1;
    // Release invalidated volumes to conserve GPU memory in case of delayed refresh (see m_reload_delayed).
    // First initialize model_volumes_new_sorted & model_instances_new_sorted.
    for (int object_idx = 0; object_idx < (int)m_model->objects.size(); ++object_idx) {
        const ModelObject* model_object = m_model->objects[object_idx];
        for (int instance_idx = 0; instance_idx < (int)model_object->instances.size(); ++instance_idx) {
            const ModelInstance* model_instance = model_object->instances[instance_idx];
            for (int volume_idx = 0; volume_idx < (int)model_object->volumes.size(); ++volume_idx) {
                const ModelVolume* model_volume = model_object->volumes[volume_idx];
                model_volume_state.emplace_back(model_volume, model_instance->id(), GLVolume::CompositeID(object_idx, volume_idx, instance_idx));
            }
        }
    }
    if (printer_technology == ptSLA) {
        const SLAPrint* sla_print = this->sla_print();
#ifndef NDEBUG
        // Verify that the SLAPrint object is synchronized with m_model.
        check_model_ids_equal(*m_model, sla_print->model());
#endif // NDEBUG
        sla_support_state.reserve(sla_print->objects().size());
        for (const SLAPrintObject* print_object : sla_print->objects()) {
            SLASupportState state;
            for (size_t istep = 0; istep < sla_steps.size(); ++istep) {
                state.step[istep] = print_object->step_state_with_timestamp(sla_steps[istep]);
                if (state.step[istep].state == PrintStateBase::State::Done) {
                    std::shared_ptr<const indexed_triangle_set> m = print_object->get_mesh_to_print();
                    if (m == nullptr || m->empty())
                        // Consider the DONE step without a valid mesh as invalid for the purpose
                        // of mesh visualization.
                        state.step[istep].state = PrintStateBase::State::Invalidated;
                    else {
                        for (const ModelInstance* model_instance : print_object->model_object()->instances) {
                            // Only the instances, which are currently printable, will have the SLA support structures kept.
                            // The instances outside the print bed will have the GLVolumes of their support structures released.
                            if (model_instance->is_printable())
                                aux_volume_state.emplace_back(state.step[istep].timestamp, model_instance->id());
                        }
                    }
                }
            }
            sla_support_state.emplace_back(state);
        }
    }
    std::sort(model_volume_state.begin(), model_volume_state.end(), model_volume_state_lower);
    std::sort(aux_volume_state.begin(), aux_volume_state.end(), model_volume_state_lower);
    // Release all ModelVolume based GLVolumes not found in the current Model. Find the GLVolume of a hollowed mesh.
    for (size_t volume_id = 0; volume_id < m_volumes.volumes.size(); ++volume_id) {
        GLVolume* volume = m_volumes.volumes[volume_id];
        ModelVolumeState  key(volume);
        ModelVolumeState* mvs = nullptr;
        if (volume->volume_idx() < 0) {
            auto it = std::lower_bound(aux_volume_state.begin(), aux_volume_state.end(), key, model_volume_state_lower);
            if (it != aux_volume_state.end() && it->geometry_id == key.geometry_id)
                // This can be an SLA support structure that should not be rendered (in case someone used undo
                // to revert to before it was generated). We only reuse the volume if that's not the case.
                if (m_model->objects[volume->composite_id.object_id]->sla_points_status != sla::PointsStatus::NoPoints)
                    mvs = &(*it);
        }
        else {
            auto it = std::lower_bound(model_volume_state.begin(), model_volume_state.end(), key, model_volume_state_lower);
            if (it != model_volume_state.end() && it->geometry_id == key.geometry_id)
                mvs = &(*it);
        }
        // Emplace instance ID of the volume. Both the aux volumes and model volumes share the same instance ID.
        // The wipe tower has its own wipe_tower_instance_id().
        if (m_selection.contains_volume(volume_id))
            instance_ids_selected.emplace_back(volume->geometry_id.second);
        if (mvs == nullptr || force_full_scene_refresh) {
            // This GLVolume will be released.
            if (volume->is_wipe_tower) {
                // There is only one wipe tower.
                assert(volume_idx_wipe_tower_old == -1);
#if ENABLE_OPENGL_ES
                m_wipe_tower_mesh.clear();
#endif // ENABLE_OPENGL_ES
                volume_idx_wipe_tower_old = (int)volume_id;
            }
            if (!m_reload_delayed) {
                deleted_volumes.emplace_back(volume, volume_id);
                delete volume;
            }
        }
        else {
            // This GLVolume will be reused.
            volume->set_sla_shift_z(0.0);
            map_glvolume_old_to_new[volume_id] = glvolumes_new.size();
            mvs->volume_idx = glvolumes_new.size();
            glvolumes_new.emplace_back(volume);
            // Update color of the volume based on the current extruder.
            if (mvs->model_volume != nullptr) {
                int extruder_id = mvs->model_volume->extruder_id();
                if (extruder_id != -1)
                    volume->extruder_id = extruder_id;
                volume->is_modifier = !mvs->model_volume->is_model_part();
                volume->set_color(color_from_model_volume(*mvs->model_volume));
                // force update of render_color alpha channel
                volume->set_render_color(volume->color.is_transparent());
                // updates volumes transformations
                volume->set_instance_transformation(mvs->model_volume->get_object()->instances[mvs->composite_id.instance_id]->get_transformation());
                volume->set_volume_transformation(mvs->model_volume->get_transformation());
                // updates volumes convex hull
                if (mvs->model_volume->is_model_part() && ! volume->convex_hull())
                    // Model volume was likely changed from modifier or support blocker / enforcer to a model part.
                    // Only model parts require convex hulls.
                    volume->set_convex_hull(mvs->model_volume->get_convex_hull_shared_ptr());
            }
        }
    }
    sort_remove_duplicates(instance_ids_selected);
    auto deleted_volumes_lower = [](const GLVolumeState &v1, const GLVolumeState &v2) { return v1.composite_id < v2.composite_id; };
    std::sort(deleted_volumes.begin(), deleted_volumes.end(), deleted_volumes_lower);
    if (m_reload_delayed)
        return;
    bool update_object_list = false;
    if (m_volumes.volumes != glvolumes_new)
    update_object_list = true;
    m_volumes.volumes = std::move(glvolumes_new);
    for (unsigned int obj_idx = 0; obj_idx < (unsigned int)m_model->objects.size(); ++ obj_idx) {
        const ModelObject &model_object = *m_model->objects[obj_idx];
        for (int volume_idx = 0; volume_idx < (int)model_object.volumes.size(); ++ volume_idx) {
            const ModelVolume &model_volume = *model_object.volumes[volume_idx];
            for (int instance_idx = 0; instance_idx < (int)model_object.instances.size(); ++ instance_idx) {
                const ModelInstance &model_instance = *model_object.instances[instance_idx];
                ModelVolumeState key(model_volume.id(), model_instance.id());
                auto it = std::lower_bound(model_volume_state.begin(), model_volume_state.end(), key, model_volume_state_lower);
                assert(it != model_volume_state.end() && it->geometry_id == key.geometry_id);
                if (it->new_geometry()) {
                    // New volume.
                    auto it_old_volume = std::lower_bound(deleted_volumes.begin(), deleted_volumes.end(), GLVolumeState(it->composite_id), deleted_volumes_lower);
                    if (it_old_volume != deleted_volumes.end() && it_old_volume->composite_id == it->composite_id)
                        // If a volume changed its ObjectID, but it reuses a GLVolume's CompositeID, maintain its selection.
                        map_glvolume_old_to_new[it_old_volume->volume_idx] = m_volumes.volumes.size();
                    // Note the index of the loaded volume, so that we can reload the main model GLVolume with the hollowed mesh
                    // later in this function.
                    it->volume_idx = m_volumes.volumes.size();
                    m_volumes.load_object_volume(&model_object, obj_idx, volume_idx, instance_idx);
                    m_volumes.volumes.back()->geometry_id = key.geometry_id;
                    update_object_list = true;
                }
                else {
                    // Recycling an old GLVolume.
                    GLVolume &existing_volume = *m_volumes.volumes[it->volume_idx];
                    assert(existing_volume.geometry_id == key.geometry_id);
                    // Update the Object/Volume/Instance indices into the current Model.
                    if (existing_volume.composite_id != it->composite_id) {
                        new_to_old_ids_map.push_back(std::make_pair(it->composite_id, existing_volume.composite_id));
                        existing_volume.composite_id = it->composite_id;
                        update_object_list = true;
                    }
                }
            }
        }
    }
    if (printer_technology == ptSLA) {
        size_t idx = 0;
        const SLAPrint *sla_print = this->sla_print();
        std::vector<double> shift_zs(m_model->objects.size(), 0);
        double relative_correction_z = sla_print->relative_correction().z();
        if (relative_correction_z <= EPSILON)
            relative_correction_z = 1.;
        for (const SLAPrintObject *print_object : sla_print->objects()) {
            SLASupportState   &state        = sla_support_state[idx ++];
            const ModelObject *model_object = print_object->model_object();
            // Find an index of the ModelObject
            int object_idx;
            // There may be new SLA volumes added to the scene for this print_object.
            // Find the object index of this print_object in the Model::objects list.
            auto it = std::find(sla_print->model().objects.begin(), sla_print->model().objects.end(), model_object);
            assert(it != sla_print->model().objects.end());
            object_idx = it - sla_print->model().objects.begin();
            // Cache the Z offset to be applied to all volumes with this object_idx.
            shift_zs[object_idx] = print_object->get_current_elevation() / relative_correction_z;
            // Collect indices of this print_object's instances, for which the SLA support meshes are to be added to the scene.
            // pairs of <instance_idx, print_instance_idx>
            std::vector<std::pair<size_t, size_t>> instances[std::tuple_size<SLASteps>::value];
            for (size_t print_instance_idx = 0; print_instance_idx < print_object->instances().size(); ++ print_instance_idx) {
                const SLAPrintObject::Instance &instance = print_object->instances()[print_instance_idx];
                // Find index of ModelInstance corresponding to this SLAPrintObject::Instance.
                auto it = std::find_if(model_object->instances.begin(), model_object->instances.end(),
                    [&instance](const ModelInstance *mi) { return mi->id() == instance.instance_id; });
                assert(it != model_object->instances.end());
                int instance_idx = it - model_object->instances.begin();
                for (size_t istep = 0; istep < sla_steps.size(); ++istep) {
                    if (state.step[istep].state == PrintStateBase::State::Done) {
                        // Check whether there is an existing auxiliary volume to be updated, or a new auxiliary volume to be created.
                        ModelVolumeState key(state.step[istep].timestamp, instance.instance_id.id);
                        auto it = std::lower_bound(aux_volume_state.begin(), aux_volume_state.end(), key, model_volume_state_lower);
                        assert(it != aux_volume_state.end() && it->geometry_id == key.geometry_id);
                        if (it->new_geometry()) {
                            // This can be an SLA support structure that should not be rendered (in case someone used undo
                            // to revert to before it was generated). If that's the case, we should not generate anything.
                            if (model_object->sla_points_status != sla::PointsStatus::NoPoints)
                                instances[istep].emplace_back(std::pair<size_t, size_t>(instance_idx, print_instance_idx));
                            else
                                shift_zs[object_idx] = 0.;
                        }
                        else {
                            // Recycling an old GLVolume. Update the Object/Instance indices into the current Model.
                            const GLVolume::CompositeID new_id(object_idx, m_volumes.volumes[it->volume_idx]->volume_idx(), instance_idx);
                            new_to_old_ids_map.push_back(std::make_pair(new_id, m_volumes.volumes[it->volume_idx]->composite_id));
                            m_volumes.volumes[it->volume_idx]->composite_id = new_id;
                            m_volumes.volumes[it->volume_idx]->set_instance_transformation(model_object->instances[instance_idx]->get_transformation());
                        }
                    }
                }
            }
            for (size_t istep = 0; istep < sla_steps.size(); ++istep) {
                if (!instances[istep].empty())
                    m_volumes.load_object_auxiliary(print_object, object_idx, instances[istep], sla_steps[istep], state.step[istep].timestamp);
            }
        }
        // Shift-up all volumes of the object so that it has the right elevation with respect to the print bed
        for (GLVolume* volume : m_volumes.volumes) {
            const ModelObject* model_object = (volume->object_idx() < (int)m_model->objects.size()) ? m_model->objects[volume->object_idx()] : nullptr;
            if (model_object != nullptr && model_object->instances[volume->instance_idx()]->is_printable()) {
                const SLAPrintObject* po = sla_print->get_print_object_by_model_object_id(model_object->id());
                if (po != nullptr)
                    volume->set_sla_shift_z(po->get_current_elevation() / sla_print->relative_correction().z());
            }
        }
    }
    if (printer_technology == ptFFF && m_config->has("nozzle_diameter")) {
        // Should the wipe tower be visualized ?
        unsigned int extruders_count = (unsigned int)dynamic_cast<const ConfigOptionFloats*>(m_config->option("nozzle_diameter"))->values.size();
        const bool wt = dynamic_cast<const ConfigOptionBool*>(m_config->option("wipe_tower"))->value;
        const bool co = dynamic_cast<const ConfigOptionBool*>(m_config->option("complete_objects"))->value;
        if (extruders_count > 1 && wt && !co) {
            const float x = dynamic_cast<const ConfigOptionFloat*>(m_config->option("wipe_tower_x"))->value;
            const float y = dynamic_cast<const ConfigOptionFloat*>(m_config->option("wipe_tower_y"))->value;
            const float w = dynamic_cast<const ConfigOptionFloat*>(m_config->option("wipe_tower_width"))->value;
            const float a = dynamic_cast<const ConfigOptionFloat*>(m_config->option("wipe_tower_rotation_angle"))->value;
            const float bw = dynamic_cast<const ConfigOptionFloat*>(m_config->option("wipe_tower_brim_width"))->value;
            const float ca = dynamic_cast<const ConfigOptionFloat*>(m_config->option("wipe_tower_cone_angle"))->value;
            const Print *print = m_process->fff_print();
            const float depth = print->wipe_tower_data(extruders_count).depth;
            const std::vector<std::pair<float, float>> z_and_depth_pairs = print->wipe_tower_data(extruders_count).z_and_depth_pairs;
            const float height_real = print->wipe_tower_data(extruders_count).height; // -1.f = unknown
            // Height of a print (Show at least a slab).
            const double height = height_real < 0.f ? std::max(m_model->max_z(), 10.0) : height_real;
            if (depth != 0.) {
    #if ENABLE_OPENGL_ES
                int volume_idx_wipe_tower_new = m_volumes.load_wipe_tower_preview(
                    x, y, w, depth, z_and_depth_pairs, (float)height, ca, a, !print->is_step_done(psWipeTower),
                    bw, &m_wipe_tower_mesh);
    #else
                int volume_idx_wipe_tower_new = m_volumes.load_wipe_tower_preview(
                    x, y, w, depth, z_and_depth_pairs, (float)height, ca, a, !print->is_step_done(psWipeTower),
                    bw);
    #endif // ENABLE_OPENGL_ES
                if (volume_idx_wipe_tower_old != -1)
                    map_glvolume_old_to_new[volume_idx_wipe_tower_old] = volume_idx_wipe_tower_new;
            }
        }
    }
    update_volumes_colors_by_extruder();
    // Update selection indices based on the old/new GLVolumeCollection.
    if (m_selection.get_mode() == Selection::Instance)
        m_selection.instances_changed(instance_ids_selected);
    else
        m_selection.volumes_changed(map_glvolume_old_to_new);
    if (printer_technology == ptSLA) {
        std::sort(new_to_old_ids_map.begin(), new_to_old_ids_map.end(),
            [](const std::pair<GLVolume::CompositeID, GLVolume::CompositeID>& i1, const std::pair<GLVolume::CompositeID, GLVolume::CompositeID>& i2) {
                return i1.first.object_id < i2.first.object_id || (i1.first.object_id == i2.first.object_id && i1.first.instance_id < i2.first.instance_id); });
        new_to_old_ids_map.erase(std::unique(new_to_old_ids_map.begin(), new_to_old_ids_map.end(),
            [](const std::pair<GLVolume::CompositeID, GLVolume::CompositeID>& i1, const std::pair<GLVolume::CompositeID, GLVolume::CompositeID>& i2) {
                return composite_id_match(i1.first, i2.first); }), new_to_old_ids_map.end());
        m_sla_view.update_instances_cache(new_to_old_ids_map);
        if (m_sla_view_type_detection_active) {
            m_sla_view.detect_type_from_volumes(m_volumes.volumes);
            m_sla_view_type_detection_active = false;
        }
        m_sla_view.update_volumes_visibility(m_volumes.volumes);
        update_object_list = true;
    }
    m_gizmos.update_data();
    m_gizmos.refresh_on_off_state();
    // Update the toolbar
    if (update_object_list)
        post_event(SimpleEvent(EVT_GLCANVAS_OBJECT_SELECT));
    // checks for geometry outside the print volume to render it accordingly
    if (!m_volumes.empty()) {
        ModelInstanceEPrintVolumeState state;
        const bool contained_min_one = check_volumes_outside_state(m_bed.build_volume(), &state, !force_full_scene_refresh);
        const bool partlyOut = (state == ModelInstanceEPrintVolumeState::ModelInstancePVS_Partly_Outside);
        const bool fullyOut = (state == ModelInstanceEPrintVolumeState::ModelInstancePVS_Fully_Outside);
        if (printer_technology != ptSLA) {
            _set_warning_notification(EWarning::ObjectClashed, partlyOut);
            _set_warning_notification(EWarning::ObjectOutside, fullyOut);
            _set_warning_notification(EWarning::SlaSupportsOutside, false);
        }
        else {
            const auto [res, volume] = _is_any_volume_outside();
            const bool is_support = volume != nullptr && volume->is_sla_support();
            if (is_support) {
                _set_warning_notification(EWarning::ObjectClashed, false);
                _set_warning_notification(EWarning::ObjectOutside, false);
                _set_warning_notification(EWarning::SlaSupportsOutside, partlyOut || fullyOut);
            }
            else {
                _set_warning_notification(EWarning::ObjectClashed, partlyOut);
                _set_warning_notification(EWarning::ObjectOutside, fullyOut);
                _set_warning_notification(EWarning::SlaSupportsOutside, false);
            }
        }
        post_event(Event<bool>(EVT_GLCANVAS_ENABLE_ACTION_BUTTONS,
                               contained_min_one && !m_model->objects.empty() && !partlyOut));
    }
    else {
        _set_warning_notification(EWarning::ObjectOutside, false);
        _set_warning_notification(EWarning::ObjectClashed, false);
        _set_warning_notification(EWarning::SlaSupportsOutside, false);
        post_event(Event<bool>(EVT_GLCANVAS_ENABLE_ACTION_BUTTONS, false));
    }
    refresh_camera_scene_box();
    if (m_selection.is_empty()) {
        // If no object is selected, deactivate the active gizmo, if any
        // Otherwise it may be shown after cleaning the scene (if it was active while the objects were deleted)
        m_gizmos.reset_all_states();
        // If no object is selected, reset the objects manipulator on the sidebar
        // to force a reset of its cache
        auto manip = wxGetApp().obj_manipul();
        if (manip != nullptr)
            manip->set_dirty();
    }
    // refresh volume raycasters for picking
    m_scene_raycaster.remove_raycasters(SceneRaycaster::EType::Volume);
    for (size_t i = 0; i < m_volumes.volumes.size(); ++i) {
        const GLVolume* v = m_volumes.volumes[i];
        assert(v->mesh_raycaster != nullptr);
        std::shared_ptr<SceneRaycasterItem> raycaster = add_raycaster_for_picking(SceneRaycaster::EType::Volume, i, *v->mesh_raycaster, v->world_matrix());
        raycaster->set_active(v->is_active);
    }
    for (GLVolume* volume : m_volumes.volumes)
        if (volume->object_idx() < (int)m_model->objects.size() && m_model->objects[volume->object_idx()]->instances[volume->instance_idx()]->is_printable()) {
            if (volume->is_modifier && m_model->objects[volume->object_idx()]->volumes[volume->volume_idx()]->is_modifier())
                volume->is_active = printer_technology != ptSLA;
        }
    // refresh gizmo elements raycasters for picking
    GLGizmoBase* curr_gizmo = m_gizmos.get_current();
    if (curr_gizmo != nullptr)
        curr_gizmo->unregister_raycasters_for_picking();
    m_scene_raycaster.remove_raycasters(SceneRaycaster::EType::Gizmo);
    if (curr_gizmo != nullptr && !m_selection.is_empty())
        curr_gizmo->register_raycasters_for_picking();
    // and force this canvas to be redrawn.
    m_dirty = true;
}
References _is_any_volume_outside(), _set_current(), _set_warning_notification(), add_raycaster_for_picking(), Slic3r::GUI::Bed3D::build_volume(), Slic3r::check_model_ids_equal(), check_volumes_outside_state(), Slic3r::color_from_model_volume(), Slic3r::GLVolume::composite_id, Slic3r::GUI::Selection::contains_volume(), current_printer_technology(), Slic3r::WipeTowerData::depth, Slic3r::GUI::GLCanvas3D::SLAView::detect_type_from_volumes(), Slic3r::PrintStateBase::Done, Slic3r::GLVolumeCollection::empty(), Slic3r::empty(), EPSILON, Slic3r::GUI::extruders_count(), Slic3r::BackgroundSlicingProcess::fff_print(), Slic3r::GLVolume::geometry_id, Slic3r::GUI::GLGizmosManager::get_current(), Slic3r::SLAPrintObject::get_current_elevation(), Slic3r::GUI::Selection::get_mode(), Slic3r::SLAPrint::get_print_object_by_model_object_id(), Slic3r::GUI::SceneRaycaster::Gizmo, Slic3r::ConfigOptionResolver::has(), Slic3r::WipeTowerData::height, Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), Slic3r::GUI::Selection::Instance, Slic3r::SLAPrintObject::Instance::instance_id, Slic3r::ModelObject::instances, Slic3r::GUI::Selection::instances_changed(), Slic3r::PrintStateBase::Invalidated, Slic3r::GUI::Selection::is_empty(), Slic3r::Print::is_step_done(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), m_bed, m_canvas, m_config, m_dirty, m_gizmos, m_hover_volume_idxs, m_initialized, m_model, m_process, m_reload_delayed, m_scene_raycaster, m_selection, m_sla_view, m_sla_view_type_detection_active, m_volumes, Slic3r::Model::max_z(), Slic3r::GLVolume::mesh_raycaster, Slic3r::PrintBase::model(), Slic3r::ModelInstancePVS_Fully_Outside, Slic3r::ModelInstancePVS_Partly_Outside, Slic3r::sla::NoPoints, ObjectClashed, ObjectOutside, Slic3r::Model::objects, Slic3r::SLAPrint::objects(), Slic3r::ConfigBase::option(), post_event(), Slic3r::GUI::printer_technology(), Slic3r::psWipeTower, Slic3r::ptFFF, Slic3r::ptSLA, refresh_camera_scene_box(), Slic3r::GUI::GLGizmosManager::refresh_on_off_state(), Slic3r::GUI::GLGizmoBase::register_raycasters_for_picking(), Slic3r::SLAPrint::relative_correction(), Slic3r::GUI::SceneRaycaster::remove_raycasters(), Slic3r::GUI::GLGizmosManager::reset_all_states(), Slic3r::ConfigOptionVector< T >::size(), Slic3r::ModelObject::sla_points_status, sla_print(), Slic3r::slaposDrillHoles, Slic3r::slaposPad, Slic3r::slaposSupportTree, SlaSupportsOutside, Slic3r::sort_remove_duplicates(), Slic3r::GUI::GLGizmoBase::unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmosManager::update_data(), Slic3r::GUI::GLCanvas3D::SLAView::update_instances_cache(), update_volumes_colors_by_extruder(), Slic3r::GUI::GLCanvas3D::SLAView::update_volumes_visibility(), Slic3r::GUI::SceneRaycaster::Volume, Slic3r::ModelObject::volumes, Slic3r::GLVolumeCollection::volumes, Slic3r::GUI::Selection::volumes_changed(), Slic3r::Print::wipe_tower_data(), Slic3r::GLVolume::world_matrix(), and Slic3r::WipeTowerData::z_and_depth_pairs.
Referenced by _refresh_if_shown_on_screen(), Slic3r::GUI::ObjectList::del_info_item(), Slic3r::GUI::Emboss::CreateObjectJob::finalize(), and Slic3r::GUI::View3D::reload_scene().
remove_raycasters_for_picking() [1/2]
void Slic3r::GUI::GLCanvas3D::remove_raycasters_for_picking (SceneRaycaster::EType type) inline
{
        m_scene_raycaster.remove_raycasters(type);
    }
References m_scene_raycaster, and Slic3r::GUI::SceneRaycaster::remove_raycasters().
remove_raycasters_for_picking() [2/2]
void Slic3r::GUI::GLCanvas3D::remove_raycasters_for_picking (SceneRaycaster::EType type, int id) inline
{
        m_scene_raycaster.remove_raycasters(type, id);
    }
References m_scene_raycaster, and Slic3r::GUI::SceneRaycaster::remove_raycasters().
Referenced by Slic3r::GUI::GLGizmoMeasure::on_render(), Slic3r::GUI::GLGizmoCut3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::remove_selected_sphere_raycaster(), Slic3r::GUI::GLGizmoHollow::unregister_hole_raycasters_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::unregister_point_raycasters_for_picking(), and Slic3r::GUI::GLGizmoSlaBase::unregister_volume_raycasters_for_picking().
render()
void Slic3r::GUI::GLCanvas3D::render ()
{
    if (m_in_render) {
        // if called recursively, return
        m_dirty = true;
        return;
    }
    m_in_render = true;
    Slic3r::ScopeGuard in_render_guard([this]() { m_in_render = false; });
    (void)in_render_guard;
    if (m_canvas == nullptr)
        return;
    // ensures this canvas is current and initialized
    if (!_is_shown_on_screen() || !_set_current() || !wxGetApp().init_opengl())
        return;
    if (!is_initialized() && !init())
        return;
    if (!m_main_toolbar.is_enabled())
        m_gcode_viewer.init();
    if (! m_bed.build_volume().valid()) {
        // this happens at startup when no data is still saved under <>\AppData\Roaming\Slic3rPE
        post_event(SimpleEvent(EVT_GLCANVAS_UPDATE_BED_SHAPE));
        return;
    }
#if ENABLE_ENVIRONMENT_MAP
    if (wxGetApp().is_editor())
        wxGetApp().plater()->init_environment_texture();
#endif // ENABLE_ENVIRONMENT_MAP
#if ENABLE_GLMODEL_STATISTICS
    GLModel::reset_statistics_counters();
#endif // ENABLE_GLMODEL_STATISTICS
    const Size& cnv_size = get_canvas_size();
    // Probably due to different order of events on Linux/GTK2, when one switched from 3D scene
    // to preview, this was called before canvas had its final size. It reported zero width
    // and the viewport was set incorrectly, leading to tripping glAsserts further down
    // the road (in apply_projection). That's why the minimum size is forced to 10.
    Camera& camera = wxGetApp().plater()->get_camera();
    camera.set_viewport(0, 0, std::max(10u, (unsigned int)cnv_size.get_width()), std::max(10u, (unsigned int)cnv_size.get_height()));
    camera.apply_viewport();
    if (camera.requires_zoom_to_bed) {
        zoom_to_bed();
        _resize((unsigned int)cnv_size.get_width(), (unsigned int)cnv_size.get_height());
        camera.requires_zoom_to_bed = false;
    }
    camera.apply_projection(_max_bounding_box(true, true));
    wxGetApp().imgui()->new_frame();
    if (m_picking_enabled) {
        if (m_rectangle_selection.is_dragging() && !m_rectangle_selection.is_empty())
            // picking pass using rectangle selection
            _rectangular_selection_picking_pass();
        else if (!m_volumes.empty())
            // regular picking pass
            _picking_pass();
#if ENABLE_RAYCAST_PICKING_DEBUG
        else {
            ImGuiWrapper& imgui = *wxGetApp().imgui();
            imgui.begin(std::string("Hit result"), ImGuiWindowFlags_AlwaysAutoResize);
            imgui.text("Picking disabled");
            imgui.end();
        }
#endif // ENABLE_RAYCAST_PICKING_DEBUG
    }
#ifdef SHOW_IMGUI_DEMO_WINDOW
    if (show_imgui_demo_window) ImGui::ShowDemoWindow();
#endif // SHOW_IMGUI_DEMO_WINDOW
    const bool is_looking_downward = camera.is_looking_downward();
    // draw scene
    glsafe(::glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT));
    _render_background();
    _render_objects(GLVolumeCollection::ERenderType::Opaque);
    _render_sla_slices();
    _render_selection();
    _render_bed_axes();
    if (is_looking_downward)
        _render_bed(camera.get_view_matrix(), camera.get_projection_matrix(), false);
    if (!m_main_toolbar.is_enabled())
        _render_gcode();
    _render_objects(GLVolumeCollection::ERenderType::Transparent);
    _render_sequential_clearance();
#if ENABLE_RENDER_SELECTION_CENTER
    _render_selection_center();
#endif // ENABLE_RENDER_SELECTION_CENTER
    if (!m_main_toolbar.is_enabled())
        _render_gcode_cog();
    // we need to set the mouse's scene position here because the depth buffer
    // could be invalidated by the following gizmo render methods
    // this position is used later into on_mouse() to drag the objects
    if (m_picking_enabled)
        m_mouse.scene_position = _mouse_to_3d(m_mouse.position.cast<coord_t>());
    // sidebar hints need to be rendered before the gizmos because the depth buffer
    // could be invalidated by the following gizmo render methods
    _render_selection_sidebar_hints();
    _render_current_gizmo();
    if (!is_looking_downward)
        _render_bed(camera.get_view_matrix(), camera.get_projection_matrix(), true);
#if ENABLE_RAYCAST_PICKING_DEBUG
    if (m_picking_enabled && !m_mouse.dragging && !m_gizmos.is_dragging() && !m_rectangle_selection.is_dragging())
        m_scene_raycaster.render_hit(camera);
#endif // ENABLE_RAYCAST_PICKING_DEBUG
#if ENABLE_SHOW_CAMERA_TARGET
    _render_camera_target();
#endif // ENABLE_SHOW_CAMERA_TARGET
    if (m_picking_enabled && m_rectangle_selection.is_dragging())
        m_rectangle_selection.render(*this);
    // draw overlays
    _render_overlays();
    if (wxGetApp().plater()->is_render_statistic_dialog_visible()) {
        ImGuiWrapper& imgui = *wxGetApp().imgui();
        imgui.begin(std::string("Render statistics"), ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse);
        imgui.text("FPS (SwapBuffers() calls per second):");
        ImGui::SameLine();
        imgui.text(std::to_string(m_render_stats.get_fps_and_reset_if_needed()));
        ImGui::Separator();
        imgui.text("Compressed textures:");
        ImGui::SameLine();
        imgui.text(OpenGLManager::are_compressed_textures_supported() ? "supported" : "not supported");
        imgui.text("Max texture size:");
        ImGui::SameLine();
        imgui.text(std::to_string(OpenGLManager::get_gl_info().get_max_tex_size()));
        imgui.end();
    }
#if ENABLE_PROJECT_DIRTY_STATE_DEBUG_WINDOW
    if (wxGetApp().is_editor() && wxGetApp().plater()->is_view3D_shown())
        wxGetApp().plater()->render_project_state_debug_window();
#endif // ENABLE_PROJECT_DIRTY_STATE_DEBUG_WINDOW
#if ENABLE_CAMERA_STATISTICS
    camera.debug_render();
#endif // ENABLE_CAMERA_STATISTICS
#if ENABLE_GLMODEL_STATISTICS
    GLModel::render_statistics();
#endif // ENABLE_GLMODEL_STATISTICS
#if ENABLE_OBJECT_MANIPULATION_DEBUG
    wxGetApp().obj_manipul()->render_debug_window();
#endif // ENABLE_OBJECT_MANIPULATION_DEBUG
    if (wxGetApp().plater()->is_view3D_shown() && current_printer_technology() == ptSLA) {
        const GLGizmosManager::EType type = m_gizmos.get_current_type();
        if (type == GLGizmosManager::EType::Undefined)
            m_sla_view.render_switch_button();
#if ENABLE_SLA_VIEW_DEBUG_WINDOW
        m_sla_view.render_debug_window();
#endif // ENABLE_SLA_VIEW_DEBUG_WINDOW
    }
    std::string tooltip;
  // Negative coordinate means out of the window, likely because the window was deactivated.
  // In that case the tooltip should be hidden.
    if (m_mouse.position.x() >= 0. && m_mouse.position.y() >= 0.) {
      if (tooltip.empty())
          tooltip = m_layers_editing.get_tooltip(*this);
      if (tooltip.empty())
          tooltip = m_gizmos.get_tooltip();
      if (tooltip.empty())
          tooltip = m_main_toolbar.get_tooltip();
      if (tooltip.empty())
          tooltip = m_undoredo_toolbar.get_tooltip();
      if (tooltip.empty())
            tooltip = wxGetApp().plater()->get_collapse_toolbar().get_tooltip();
      if (tooltip.empty())
            tooltip = wxGetApp().plater()->get_view_toolbar().get_tooltip();
    }
    set_tooltip(tooltip);
    if (m_tooltip_enabled)
        m_tooltip.render(m_mouse.position, *this);
    wxGetApp().plater()->get_mouse3d_controller().render_settings_dialog(*this);
    wxGetApp().plater()->get_notification_manager()->render_notifications(*this, get_overlay_window_width());
    wxGetApp().imgui()->render();
    m_canvas->SwapBuffers();
    m_render_stats.increment_fps_counter();
}
References _is_shown_on_screen(), _max_bounding_box(), _mouse_to_3d(), _picking_pass(), _rectangular_selection_picking_pass(), _render_background(), _render_bed(), _render_bed_axes(), _render_current_gizmo(), _render_gcode(), _render_gcode_cog(), _render_objects(), _render_overlays(), _render_selection(), _render_selection_sidebar_hints(), _render_sequential_clearance(), _render_sla_slices(), _resize(), _set_current(), Slic3r::GUI::Camera::apply_projection(), Slic3r::GUI::Camera::apply_viewport(), Slic3r::GUI::OpenGLManager::are_compressed_textures_supported(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::Bed3D::build_volume(), current_printer_technology(), Slic3r::GUI::GLCanvas3D::Mouse::dragging, Slic3r::GLVolumeCollection::empty(), Slic3r::GUI::ImGuiWrapper::end(), get_canvas_size(), Slic3r::GUI::GLGizmosManager::get_current_type(), Slic3r::GUI::GLCanvas3D::RenderStats::get_fps_and_reset_if_needed(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::Size::get_height(), get_overlay_window_width(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::GLGizmosManager::get_tooltip(), Slic3r::GUI::GLToolbar::get_tooltip(), Slic3r::GUI::GLCanvas3D::LayersEditing::get_tooltip(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Size::get_width(), glsafe, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoResize, Slic3r::GUI::GLCanvas3D::RenderStats::increment_fps_counter(), Slic3r::GUI::GCodeViewer::init(), init(), Slic3r::GUI::GLGizmosManager::is_dragging(), Slic3r::GUI::GLSelectionRectangle::is_dragging(), Slic3r::GUI::GLSelectionRectangle::is_empty(), Slic3r::GUI::GLToolbar::is_enabled(), is_initialized(), Slic3r::GUI::Camera::is_looking_downward(), m_bed, m_canvas, m_dirty, m_gcode_viewer, m_gizmos, m_in_render, m_layers_editing, m_main_toolbar, m_mouse, m_picking_enabled, m_rectangle_selection, m_render_stats, m_scene_raycaster, m_sla_view, m_tooltip, m_tooltip_enabled, m_undoredo_toolbar, m_volumes, Slic3r::GLVolumeCollection::Opaque, Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::Mouse::position, post_event(), Slic3r::ptSLA, Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::GLCanvas3D::Tooltip::render(), Slic3r::GUI::GLCanvas3D::SLAView::render_switch_button(), Slic3r::GUI::Camera::requires_zoom_to_bed, ImGui::SameLine(), Slic3r::GUI::GLCanvas3D::Mouse::scene_position, ImGui::Separator(), set_tooltip(), Slic3r::GUI::Camera::set_viewport(), show_imgui_demo_window, ImGui::ShowDemoWindow(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GLVolumeCollection::Transparent, Slic3r::GUI::GLGizmosManager::Undefined, Slic3r::BuildVolume::valid(), void(), and zoom_to_bed().
Referenced by _refresh_if_shown_on_screen(), Slic3r::GUI::GLToolbar::do_action(), on_char(), on_key(), Slic3r::GUI::Preview::on_layers_slider_scroll_changed(), on_mouse(), Slic3r::GUI::Preview::on_moves_slider_scroll_changed(), on_paint(), Slic3r::GUI::MainFrame::select_tab(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
render_thumbnail() [1/2]
void Slic3r::GUI::GLCanvas3D::render_thumbnail (ThumbnailData & thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams & thumbnail_params, Camera::EType camera_type)
{
    render_thumbnail(thumbnail_data, w, h, thumbnail_params, m_volumes, camera_type);
}
References m_volumes, and render_thumbnail().
Referenced by render_thumbnail().
render_thumbnail() [2/2]
void Slic3r::GUI::GLCanvas3D::render_thumbnail (ThumbnailData & thumbnail_data, unsigned int w, unsigned int h, const ThumbnailsParams & thumbnail_params, const GLVolumeCollection & volumes, Camera::EType camera_type)
{
    switch (OpenGLManager::get_framebuffers_type())
    {
    case OpenGLManager::EFramebufferType::Arb: { _render_thumbnail_framebuffer(thumbnail_data, w, h, thumbnail_params, volumes, camera_type); break; }
    case OpenGLManager::EFramebufferType::Ext: { _render_thumbnail_framebuffer_ext(thumbnail_data, w, h, thumbnail_params, volumes, camera_type); break; }
    default: { _render_thumbnail_legacy(thumbnail_data, w, h, thumbnail_params, volumes, camera_type); break; }
    }
}
References _render_thumbnail_framebuffer(), _render_thumbnail_framebuffer_ext(), _render_thumbnail_legacy(), Slic3r::GUI::OpenGLManager::Arb, Slic3r::GUI::OpenGLManager::Ext, and Slic3r::GUI::OpenGLManager::get_framebuffers_type().
request_extra_frame()
void Slic3r::GUI::GLCanvas3D::request_extra_frame () inline
{ m_extra_frame_requested = true; }
References m_extra_frame_requested.
Referenced by _resize(), Slic3r::GUI::Selection::erase(), Slic3r::GUI::GLGizmoMeasure::gizmo_event(), load_gcode_preview(), on_char(), Slic3r::GUI::GLGizmoCut3D::on_load(), Slic3r::GUI::GLGizmoCut3D::on_set_state(), refresh_gcode_preview_render_paths(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::Bed3D::render_texture(), Slic3r::GUI::GLGizmoCut3D::reset_cut_plane(), Slic3r::GUI::GLGizmoCut3D::set_connectors_editing(), Slic3r::GUI::ObjectManipulation::set_coordinates_type(), and Slic3r::GUI::Plater::priv::update_background_process().
requires_check_outside_state()
void Slic3r::GUI::GLCanvas3D::requires_check_outside_state () inline
{ m_requires_check_outside_state = true; }
References m_requires_check_outside_state.
reset_all_gizmos()
void Slic3r::GUI::GLCanvas3D::reset_all_gizmos () inline
{ m_gizmos.reset_all_states(); }
References m_gizmos, and Slic3r::GUI::GLGizmosManager::reset_all_states().
Referenced by Slic3r::GUI::GLGizmoCut3D::perform_cut().
reset_clipping_planes_cache()
void Slic3r::GUI::GLCanvas3D::reset_clipping_planes_cache () inline
{ m_sla_caps[0].triangles.clear(); m_sla_caps[1].triangles.clear(); }
References m_sla_caps.
Referenced by Slic3r::GUI::Preview::load_print_as_sla().
reset_gcode_toolpaths()
void Slic3r::GUI::GLCanvas3D::reset_gcode_toolpaths () inline
{ m_gcode_viewer.reset(); }
References m_gcode_viewer, and Slic3r::GUI::GCodeViewer::reset().
reset_layer_height_profile()
void Slic3r::GUI::GLCanvas3D::reset_layer_height_profile ()
{
    wxGetApp().plater()->take_snapshot(_L("Variable layer height - Reset"));
    m_layers_editing.reset_layer_height_profile(*this);
    m_layers_editing.state = LayersEditing::Completed;
    m_dirty = true;
}
References _L, Slic3r::GUI::GLCanvas3D::LayersEditing::Completed, m_dirty, m_layers_editing, Slic3r::GUI::GLCanvas3D::LayersEditing::reset_layer_height_profile(), and Slic3r::GUI::GLCanvas3D::LayersEditing::state.
reset_old_size()
void Slic3r::GUI::GLCanvas3D::reset_old_size () inline
{ m_old_size = { 0, 0 }; }
References m_old_size.
reset_sequential_print_clearance()
void Slic3r::GUI::GLCanvas3D::reset_sequential_print_clearance () inline
{
        m_sequential_print_clearance.m_evaluating = false;
        m_sequential_print_clearance.set_contours(ContoursList(), false);
    }
References Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_evaluating, m_sequential_print_clearance, and Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours().
Referenced by Slic3r::GUI::Plater::priv::update_background_process().
reset_volumes()
void Slic3r::GUI::GLCanvas3D::reset_volumes ()
{
    if (!m_initialized)
        return;
    if (m_volumes.empty())
        return;
    _set_current();
    m_selection.clear();
    m_volumes.clear();
    m_dirty = true;
    _set_warning_notification(EWarning::ObjectOutside, false);
}
References _set_current(), _set_warning_notification(), Slic3r::GLVolumeCollection::clear(), Slic3r::GUI::Selection::clear(), Slic3r::GLVolumeCollection::empty(), m_dirty, m_initialized, m_selection, m_volumes, and ObjectOutside.
Referenced by ~GLCanvas3D(), load_preview(), load_sla_preview(), and Slic3r::GUI::Preview::reload_print().
scene_bounding_box()
BoundingBoxf3 Slic3r::GUI::GLCanvas3D::scene_bounding_box () const
{
    BoundingBoxf3 bb = volumes_bounding_box();
    bb.merge(m_bed.extended_bounding_box());
    double h = m_bed.build_volume().max_print_height();
    //FIXME why -h?
    bb.min.z() = std::min(bb.min.z(), -h);
    bb.max.z() = std::max(bb.max.z(), h);
    return bb;
}
References Slic3r::GUI::Bed3D::build_volume(), Slic3r::GUI::Bed3D::extended_bounding_box(), m_bed, Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BuildVolume::max_print_height(), Slic3r::BoundingBox3Base< PointType >::merge(), Slic3r::BoundingBoxBase< PointType, APointsType >::min, and volumes_bounding_box().
Referenced by _render_thumbnail_internal(), and refresh_camera_scene_box().
schedule_extra_frame()
void Slic3r::GUI::GLCanvas3D::schedule_extra_frame (int miliseconds)
{
    // Schedule idle event right now
    if (miliseconds == 0)
    {
        // We want to wakeup idle evnt but most likely this is call inside render cycle so we need to wait
        if (m_in_render)
            miliseconds = 33;
        else {
            m_dirty = true;
            wxWakeUpIdle();
            return;
        }
    }
    int remaining_time = m_render_timer.GetInterval();
    // Timer is not running
    if (!m_render_timer.IsRunning()) {
        m_render_timer.StartOnce(miliseconds);
    // Timer is running - restart only if new period is shorter than remaning period
    } else {
        if (miliseconds + 20 < remaining_time) {
            m_render_timer.Stop();
            m_render_timer.StartOnce(miliseconds);
        }
    }
}
References m_dirty, m_in_render, and m_render_timer.
Referenced by Slic3r::GUI::NotificationManager::push_notification_data(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), and Slic3r::GUI::NotificationManager::update_notifications().
select_all()
void Slic3r::GUI::GLCanvas3D::select_all ()
{
    m_selection.add_all();
    m_dirty = true;
    wxGetApp().obj_manipul()->set_dirty();
    m_gizmos.reset_all_states();
    m_gizmos.update_data();
    post_event(SimpleEvent(EVT_GLCANVAS_OBJECT_SELECT));
}
References Slic3r::GUI::Selection::add_all(), m_dirty, m_gizmos, m_selection, post_event(), Slic3r::GUI::GLGizmosManager::reset_all_states(), and Slic3r::GUI::GLGizmosManager::update_data().
Referenced by Slic3r::GUI::View3D::select_all().
select_view()
void Slic3r::GUI::GLCanvas3D::select_view (const std::string & direction)
{
    wxGetApp().plater()->get_camera().select_view(direction);
    if (m_canvas != nullptr)
        m_canvas->Refresh();
}
References m_canvas.
Referenced by on_char(), Slic3r::GUI::View3D::select_view(), and Slic3r::GUI::Preview::select_view().
set_as_dirty()
void Slic3r::GUI::GLCanvas3D::set_as_dirty ()
{
    m_dirty = true;
}
References m_dirty.
Referenced by Slic3r::GUI::GLGizmoCut3D::add_connector(), Slic3r::GUI::GLCanvas3D::ToolbarHighlighter::blink(), Slic3r::GUI::GLCanvas3D::GizmoHighlighter::blink(), Slic3r::GUI::GLGizmoCut3D::delete_selected_connectors(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), enable_layers_editing(), Slic3r::GUI::Selection::erase(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), load_gcode_preview(), Slic3r::GUI::GLGizmosManager::on_char(), Slic3r::GUI::GLGizmosManager::on_key(), Slic3r::GUI::Preview::on_layers_slider_scroll_changed(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::GLGizmoHollow::on_mouse(), Slic3r::GUI::GLGizmoPainterBase::on_mouse(), Slic3r::GUI::GLGizmoSlaSupports::on_mouse(), Slic3r::GUI::GLToolbar::on_mouse(), Slic3r::GUI::on_mouse_surface_drag(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), refresh_gcode_preview_render_paths(), Slic3r::GUI::View3D::render(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::View3D::set_as_dirty(), Slic3r::GUI::Preview::set_as_dirty(), Slic3r::GUI::ObjectManipulation::set_coordinates_type(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::Plater::priv::update_background_process(), update_gizmos_on_off_state(), Slic3r::GUI::GLToolbar::update_hover_state_horizontal(), Slic3r::GUI::GLToolbar::update_hover_state_vertical(), and Slic3r::GUI::GLGizmoBase::use_grabbers().
set_clipping_plane()
void Slic3r::GUI::GLCanvas3D::set_clipping_plane (unsigned int id, const ClippingPlane & plane) inline
{
        if (id < 2) {
            m_clipping_planes[id] = plane;
            m_sla_caps[id].reset();
        }
    }
References m_clipping_planes, and m_sla_caps.
Referenced by Slic3r::GUI::Preview::on_layers_slider_scroll_changed(), and Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update().
set_color_clip_plane()
void Slic3r::GUI::GLCanvas3D::set_color_clip_plane (const Vec3d & cp_normal, double offset) inline
{ m_volumes.set_color_clip_plane(cp_normal, offset); }
References m_volumes, Slic3r::offset(), and Slic3r::GLVolumeCollection::set_color_clip_plane().
Referenced by Slic3r::GUI::GLGizmoCut3D::update_clipper().
set_color_clip_plane_colors()
void Slic3r::GUI::GLCanvas3D::set_color_clip_plane_colors (const std::array< ColorRGBA, 2 > & colors) inline
{ m_volumes.set_color_clip_plane_colors(colors); }
References m_volumes, and Slic3r::GLVolumeCollection::set_color_clip_plane_colors().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_set_state().
set_config()
void Slic3r::GUI::GLCanvas3D::set_config (const DynamicPrintConfig * config)
{
    m_config = config;
    m_layers_editing.set_config(config);
}
References m_config, m_layers_editing, and Slic3r::GUI::GLCanvas3D::LayersEditing::set_config().
Referenced by Slic3r::GUI::Preview::init(), and Slic3r::GUI::View3D::init().
set_context()
void Slic3r::GUI::GLCanvas3D::set_context (wxGLContext * context) inline
{ m_context = context; }
References m_context.
Referenced by Slic3r::GUI::Preview::init(), and Slic3r::GUI::View3D::init().
set_cursor()
void Slic3r::GUI::GLCanvas3D::set_cursor (ECursorType type)
{
    if ((m_canvas != nullptr) && (m_cursor_type != type))
    {
        switch (type)
        {
        case Standard: { m_canvas->SetCursor(*wxSTANDARD_CURSOR); break; }
        case Cross: { m_canvas->SetCursor(*wxCROSS_CURSOR); break; }
        }
        m_cursor_type = type;
    }
}
References Cross, m_canvas, m_cursor_type, and Standard.
set_gcode_options_visibility_from_flags()
void Slic3r::GUI::GLCanvas3D::set_gcode_options_visibility_from_flags (unsigned int flags)
{
    m_gcode_viewer.set_options_visibility_from_flags(flags);
}
References m_gcode_viewer, and Slic3r::GUI::GCodeViewer::set_options_visibility_from_flags().
set_gcode_view_preview_type()
void Slic3r::GUI::GLCanvas3D::set_gcode_view_preview_type (GCodeViewer::EViewType type) inline
{ return m_gcode_viewer.set_view_type(type); }
References m_gcode_viewer, and Slic3r::GUI::GCodeViewer::set_view_type().
Referenced by Slic3r::GUI::Preview::load_print_as_fff().
set_model()
void Slic3r::GUI::GLCanvas3D::set_model (Model * model)
{
    m_model = model;
    m_selection.set_model(m_model);
}
References m_model, m_selection, and Slic3r::GUI::Selection::set_model().
Referenced by Slic3r::GUI::Preview::init(), and Slic3r::GUI::View3D::init().
set_popup_menu_position()
void Slic3r::GUI::GLCanvas3D::set_popup_menu_position (const Vec2d & position) inline
{ m_popup_menu_positon = position; }
References m_popup_menu_positon.
Referenced by Slic3r::GUI::Plater::priv::on_right_click().
set_process()
void Slic3r::GUI::GLCanvas3D::set_process (BackgroundSlicingProcess * process)
{
    m_process = process;
}
References m_process.
Referenced by Slic3r::GUI::Preview::init(), and Slic3r::GUI::View3D::init().
set_raycaster_gizmos_on_top()
void Slic3r::GUI::GLCanvas3D::set_raycaster_gizmos_on_top (bool value) inline
{
        m_scene_raycaster.set_gizmos_on_top(value);
    }
References m_scene_raycaster, and Slic3r::GUI::SceneRaycaster::set_gizmos_on_top().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_register_raycasters_for_picking(), Slic3r::GUI::GLGizmoEmboss::on_set_state(), Slic3r::GUI::GLGizmoCut3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMeasure::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_unregister_raycasters_for_picking(), Slic3r::GUI::GLGizmoRotate3D::on_unregister_raycasters_for_picking(), and Slic3r::GUI::GLGizmoScale3D::on_unregister_raycasters_for_picking().
set_selected_extruder()
void Slic3r::GUI::GLCanvas3D::set_selected_extruder (int extruder) inline
{ m_selected_extruder = extruder;}
References m_selected_extruder.
Referenced by Slic3r::GUI::Preview::load_print_as_fff().
set_sequential_clearance_as_evaluating()
void Slic3r::GUI::GLCanvas3D::set_sequential_clearance_as_evaluating () inline
{ m_sequential_print_clearance.m_evaluating = true; }
References Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_evaluating, and m_sequential_print_clearance.
Referenced by Slic3r::GUI::Selection::erase().
set_sequential_print_clearance_contours()
void Slic3r::GUI::GLCanvas3D::set_sequential_print_clearance_contours (const ContoursList & contours, bool generate_fill) inline
{
        m_sequential_print_clearance.set_contours(contours, generate_fill);
    }
References m_sequential_print_clearance, and Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_contours().
Referenced by Slic3r::GUI::Plater::priv::update_background_process(), and update_sequential_clearance().
set_sla_view_type() [1/2]
void Slic3r::GUI::GLCanvas3D::set_sla_view_type (const GLVolume::CompositeID & id, ESLAViewType type)
{
    m_sla_view.set_type(id, type);
    m_sla_view.update_volumes_visibility(m_volumes.volumes);
    m_dirty = true;
}
References m_dirty, m_sla_view, m_volumes, Slic3r::GUI::GLCanvas3D::SLAView::set_type(), Slic3r::GUI::GLCanvas3D::SLAView::update_volumes_visibility(), and Slic3r::GLVolumeCollection::volumes.
set_sla_view_type() [2/2]
void Slic3r::GUI::GLCanvas3D::set_sla_view_type (ESLAViewType type)
{
    m_sla_view.set_type(type);
    m_sla_view.update_volumes_visibility(m_volumes.volumes);
    m_dirty = true;
}
References m_dirty, m_sla_view, m_volumes, Slic3r::GUI::GLCanvas3D::SLAView::set_type(), Slic3r::GUI::GLCanvas3D::SLAView::update_volumes_visibility(), and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::GLGizmosManager::activate_gizmo().
set_slope_normal_angle()
void Slic3r::GUI::GLCanvas3D::set_slope_normal_angle (float angle_in_deg) inline
{ m_slope.set_normal_angle(angle_in_deg); }
References m_slope, and Slic3r::GUI::GLCanvas3D::Slope::set_normal_angle().
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window().
set_toolpath_role_visibility_flags()
void Slic3r::GUI::GLCanvas3D::set_toolpath_role_visibility_flags (unsigned int flags)
{
    m_gcode_viewer.set_toolpath_role_visibility_flags(flags);
}
References m_gcode_viewer, and Slic3r::GUI::GCodeViewer::set_toolpath_role_visibility_flags().
set_toolpath_view_type()
void Slic3r::GUI::GLCanvas3D::set_toolpath_view_type (GCodeViewer::EViewType type)
{
    m_gcode_viewer.set_view_type(type);
}
References m_gcode_viewer, and Slic3r::GUI::GCodeViewer::set_view_type().
set_toolpaths_z_range()
void Slic3r::GUI::GLCanvas3D::set_toolpaths_z_range (const std::array< unsigned int, 2 > & range)
{
    if (m_gcode_viewer.has_data())
        m_gcode_viewer.set_layers_z_range(range);
}
References Slic3r::GUI::GCodeViewer::has_data(), m_gcode_viewer, Slic3r::range(), and Slic3r::GUI::GCodeViewer::set_layers_z_range().
Referenced by Slic3r::GUI::Preview::on_layers_slider_scroll_changed().
set_tooltip()
void Slic3r::GUI::GLCanvas3D::set_tooltip (const std::string & tooltip)
{
    if (m_canvas != nullptr)
        m_tooltip.set_text(tooltip);
}
References m_canvas, m_tooltip, and Slic3r::GUI::GLCanvas3D::Tooltip::set_text().
Referenced by _init_undoredo_toolbar(), and render().
set_use_clipping_planes()
void Slic3r::GUI::GLCanvas3D::set_use_clipping_planes (bool use) inline
{ m_use_clipping_planes = use; }
References m_use_clipping_planes.
Referenced by Slic3r::GUI::Preview::load_print_as_sla(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_release(), and Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update().
set_use_color_clip_plane()
void Slic3r::GUI::GLCanvas3D::set_use_color_clip_plane (bool use) inline
{ m_volumes.set_use_color_clip_plane(use); }
References m_volumes, and Slic3r::GLVolumeCollection::set_use_color_clip_plane().
Referenced by Slic3r::GUI::GLGizmoCut3D::on_set_state().
set_volumes_z_range()
void Slic3r::GUI::GLCanvas3D::set_volumes_z_range (const std::array< double, 2 > & range)
{
    m_volumes.set_range(range[0] - 1e-6, range[1] + 1e-6);
}
References m_volumes, Slic3r::range(), and Slic3r::GLVolumeCollection::set_range().
Referenced by Slic3r::GUI::Preview::on_layers_slider_scroll_changed().
show_labels()
void Slic3r::GUI::GLCanvas3D::show_labels (bool show) inline
{ m_labels.show(show); }
References m_labels, and Slic3r::GUI::GLCanvas3D::Labels::show().
Referenced by Slic3r::GUI::Plater::priv::show_view3D_labels().
show_legend()
void Slic3r::GUI::GLCanvas3D::show_legend (bool show) inline
{ m_gcode_viewer.enable_legend(show); m_dirty = true; }
References Slic3r::GUI::GCodeViewer::enable_legend(), m_dirty, and m_gcode_viewer.
Referenced by on_char(), and Slic3r::GUI::Plater::priv::show_legend().
sla_print()
const SLAPrint * Slic3r::GUI::GLCanvas3D::sla_print () const
{
    return (m_process == nullptr) ? nullptr : m_process->sla_print();
}
Referenced by Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), load_sla_preview(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::processed_objects_idxs(), reload_scene(), Slic3r::GUI::GLCanvas3D::SLAView::render_switch_button(), and Slic3r::GUI::GLCanvas3D::SLAView::update_volumes_visibility().
smooth_layer_height_profile()
void Slic3r::GUI::GLCanvas3D::smooth_layer_height_profile (const HeightProfileSmoothingParams & smoothing_params)
{
    wxGetApp().plater()->take_snapshot(_L("Variable layer height - Smooth all"));
    m_layers_editing.smooth_layer_height_profile(*this, smoothing_params);
    m_layers_editing.state = LayersEditing::Completed;
    m_dirty = true;
}
References _L, Slic3r::GUI::GLCanvas3D::LayersEditing::Completed, m_dirty, m_layers_editing, Slic3r::GUI::GLCanvas3D::LayersEditing::smooth_layer_height_profile(), and Slic3r::GUI::GLCanvas3D::LayersEditing::state.
timestamp_now()
static int64_t Slic3r::GUI::GLCanvas3D::timestamp_now () inline static
{
#ifdef _WIN32
        // Cheaper on Windows, calls GetSystemTimeAsFileTime()
        return wxGetUTCTimeMillis().GetValue();
#else
        // calls clock()
        return wxGetLocalTimeMillis().GetValue();
#endif
    }
Referenced by Slic3r::AppUpdater::priv::download_file(), Slic3r::GUI::NotificationManager::PopNotification::init(), Slic3r::GUI::NotificationManager::HintNotification::init(), Slic3r::GUI::NotificationManager::render_notifications(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), Slic3r::GUI::NotificationManager::PopNotification::reset_timer(), Slic3r::GUI::NotificationManager::URLDownloadNotification::set_percentage(), Slic3r::GUI::NotificationManager::update_notifications(), and Slic3r::GUI::NotificationManager::PopNotification::update_state().
toggle_model_objects_visibility()
void Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility (bool visible, const ModelObject * mo = nullptr, int instance_idx = -1, const ModelVolume * mv = nullptr)
{
    std::vector<std::shared_ptr<SceneRaycasterItem>>* raycasters = get_raycasters_for_picking(SceneRaycaster::EType::Volume);
    for (GLVolume* vol : m_volumes.volumes) {
        if (vol->is_wipe_tower)
            vol->is_active = (visible && mo == nullptr);
        else {
            if ((mo == nullptr || m_model->objects[vol->composite_id.object_id] == mo)
            && (instance_idx == -1 || vol->composite_id.instance_id == instance_idx)
            && (mv == nullptr || m_model->objects[vol->composite_id.object_id]->volumes[vol->composite_id.volume_id] == mv)) {
                vol->is_active = visible;
                if (!vol->is_modifier)
                    vol->color.a(1.f);
                if (instance_idx == -1) {
                    vol->force_native_color = false;
                    vol->force_neutral_color = false;
                } else {
                    const GLGizmosManager& gm = get_gizmos_manager();
                    auto gizmo_type = gm.get_current_type();
                    if (  (gizmo_type == GLGizmosManager::FdmSupports
                        || gizmo_type == GLGizmosManager::Seam
                        || gizmo_type == GLGizmosManager::Cut)
                        && !vol->is_modifier) {
                        vol->force_neutral_color = true;
                    }
                    else if (gizmo_type == GLGizmosManager::MmuSegmentation)
                        vol->is_active = false;
                    else
                        vol->force_native_color = true;
                }
            }
        }
        auto it = std::find_if(raycasters->begin(), raycasters->end(), [vol](std::shared_ptr<SceneRaycasterItem> item) { return item->get_raycaster() == vol->mesh_raycaster.get(); });
        if (it != raycasters->end())
            (*it)->set_active(vol->is_active);
    }
    if (visible && !mo)
        toggle_sla_auxiliaries_visibility(true, mo, instance_idx);
    if (!mo && !visible && !m_model->objects.empty() && (m_model->objects.size() > 1 || m_model->objects.front()->instances.size() > 1))
        _set_warning_notification(EWarning::SomethingNotShown, true);
    if (!mo && visible)
        _set_warning_notification(EWarning::SomethingNotShown, false);
}
References _set_warning_notification(), Slic3r::GUI::GLGizmosManager::Cut, Slic3r::GUI::GLGizmosManager::FdmSupports, Slic3r::GUI::GLGizmosManager::get_current_type(), get_gizmos_manager(), get_raycasters_for_picking(), m_model, m_volumes, Slic3r::GUI::GLGizmosManager::MmuSegmentation, Slic3r::Model::objects, Slic3r::GUI::GLGizmosManager::Seam, SomethingNotShown, toggle_sla_auxiliaries_visibility(), Slic3r::GUI::SceneRaycaster::Volume, and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoCut3D::on_mouse(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_release(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), Slic3r::GUI::GLGizmoCut3D::process_contours(), and Slic3r::GUI::GLGizmoCut3D::reset_cut_by_contours().
toggle_sla_auxiliaries_visibility()
void Slic3r::GUI::GLCanvas3D::toggle_sla_auxiliaries_visibility (bool visible, const ModelObject * mo = nullptr, int instance_idx = -1)
{
    if (current_printer_technology() != ptSLA)
        return;
    m_render_sla_auxiliaries = visible;
    std::vector<std::shared_ptr<SceneRaycasterItem>>* raycasters = get_raycasters_for_picking(SceneRaycaster::EType::Volume);
    for (GLVolume* vol : m_volumes.volumes) {
      if ((mo == nullptr || m_model->objects[vol->composite_id.object_id] == mo)
            && (instance_idx == -1 || vol->composite_id.instance_id == instance_idx)
            && vol->composite_id.volume_id < 0) {
            vol->is_active = visible;
            auto it = std::find_if(raycasters->begin(), raycasters->end(), [vol](std::shared_ptr<SceneRaycasterItem> item) { return item->get_raycaster() == vol->mesh_raycaster.get(); });
            if (it != raycasters->end())
                (*it)->set_active(vol->is_active);
        }
    }
}
References current_printer_technology(), get_raycasters_for_picking(), m_model, m_render_sla_auxiliaries, m_volumes, Slic3r::Model::objects, Slic3r::ptSLA, Slic3r::GUI::SceneRaycaster::Volume, and Slic3r::GLVolumeCollection::volumes.
Referenced by Slic3r::GUI::GLGizmoMeasure::data_changed(), Slic3r::GUI::GLGizmoMeasure::on_set_state(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), and toggle_model_objects_visibility().
unbind_event_handlers()
void Slic3r::GUI::GLCanvas3D::unbind_event_handlers ()
{
    if (m_canvas != nullptr && m_event_handlers_bound) {
        m_canvas->Unbind(wxEVT_SIZE, &GLCanvas3D::on_size, this);
        m_canvas->Unbind(wxEVT_IDLE, &GLCanvas3D::on_idle, this);
        m_canvas->Unbind(wxEVT_CHAR, &GLCanvas3D::on_char, this);
        m_canvas->Unbind(wxEVT_KEY_DOWN, &GLCanvas3D::on_key, this);
        m_canvas->Unbind(wxEVT_KEY_UP, &GLCanvas3D::on_key, this);
        m_canvas->Unbind(wxEVT_MOUSEWHEEL, &GLCanvas3D::on_mouse_wheel, this);
        m_canvas->Unbind(wxEVT_TIMER, &GLCanvas3D::on_timer, this);
        m_canvas->Unbind(EVT_GLCANVAS_RENDER_TIMER, &GLCanvas3D::on_render_timer, this);
        m_canvas->Unbind(wxEVT_LEFT_DOWN, &GLCanvas3D::on_mouse, this);
    m_canvas->Unbind(wxEVT_LEFT_UP, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_MIDDLE_DOWN, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_MIDDLE_UP, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_RIGHT_DOWN, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_RIGHT_UP, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_MOTION, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_ENTER_WINDOW, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_LEAVE_WINDOW, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_LEFT_DCLICK, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_MIDDLE_DCLICK, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_RIGHT_DCLICK, &GLCanvas3D::on_mouse, this);
        m_canvas->Unbind(wxEVT_PAINT, &GLCanvas3D::on_paint, this);
        m_canvas->Unbind(wxEVT_SET_FOCUS, &GLCanvas3D::on_set_focus, this);
        m_event_handlers_bound = false;
    }
}
References m_canvas, m_event_handlers_bound, on_char(), on_idle(), on_key(), on_mouse(), on_mouse_wheel(), on_paint(), on_render_timer(), on_set_focus(), on_size(), and on_timer().
update_gcode_sequential_view_current()
void Slic3r::GUI::GLCanvas3D::update_gcode_sequential_view_current (unsigned int first, unsigned int last) inline
{ m_gcode_viewer.update_sequential_view_current(first, last); }
References m_gcode_viewer, and Slic3r::GUI::GCodeViewer::update_sequential_view_current().
Referenced by Slic3r::GUI::Preview::on_moves_slider_scroll_changed().
update_gizmos_on_off_state()
void Slic3r::GUI::GLCanvas3D::update_gizmos_on_off_state ()
{
    set_as_dirty();
    m_gizmos.update_data();
    m_gizmos.refresh_on_off_state();
}
References m_gizmos, Slic3r::GUI::GLGizmosManager::refresh_on_off_state(), set_as_dirty(), and Slic3r::GUI::GLGizmosManager::update_data().
Referenced by Slic3r::GUI::GUI_App::update_mode(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
update_instance_printable_state_for_object()
void Slic3r::GUI::GLCanvas3D::update_instance_printable_state_for_object (size_t obj_idx)
{
    ModelObject* model_object = m_model->objects[obj_idx];
    for (int inst_idx = 0; inst_idx < (int)model_object->instances.size(); ++inst_idx) {
        ModelInstance* instance = model_object->instances[inst_idx];
        for (GLVolume* volume : m_volumes.volumes) {
            if (volume->object_idx() == (int)obj_idx && volume->instance_idx() == inst_idx)
                volume->printable = instance->printable;
        }
    }
}
References Slic3r::ModelObject::instances, m_model, m_volumes, Slic3r::Model::objects, Slic3r::ModelInstance::printable, and Slic3r::GLVolumeCollection::volumes.
Referenced by priv::create_volume(), Slic3r::GUI::Plater::priv::reload_from_disk(), and update_instance_printable_state_for_objects().
update_instance_printable_state_for_objects()
void Slic3r::GUI::GLCanvas3D::update_instance_printable_state_for_objects (const std::vector< size_t > & object_idxs)
{
    for (size_t obj_idx : object_idxs)
        update_instance_printable_state_for_object(obj_idx);
}
References update_instance_printable_state_for_object().
update_sequential_clearance()
void Slic3r::GUI::GLCanvas3D::update_sequential_clearance (bool force_contours_generation)
{
    if (current_printer_technology() != ptFFF || !fff_print()->config().complete_objects)
        return;
    if (m_layers_editing.is_enabled())
        return;
    auto instance_transform_from_volumes = [this](int object_idx, int instance_idx) {
        for (const GLVolume* v : m_volumes.volumes) {
            if (v->object_idx() == object_idx && v->instance_idx() == instance_idx)
                return v->get_instance_transformation();
        }
        assert(false);
        return Geometry::Transformation();
    };
    auto is_object_outside_printbed = [this](int object_idx) {
        for (const GLVolume* v : m_volumes.volumes) {
            if (v->object_idx() == object_idx && v->is_outside)
                return true;
        }
        return false;
    };
    // collects instance transformations from volumes
    // first: define temporary cache
    unsigned int instances_count = 0;
    std::vector<std::vector<std::optional<Geometry::Transformation>>> instance_transforms;
    for (size_t obj = 0; obj < m_model->objects.size(); ++obj) {
        instance_transforms.emplace_back(std::vector<std::optional<Geometry::Transformation>>());
        const ModelObject* model_object = m_model->objects[obj];
        for (size_t i = 0; i < model_object->instances.size(); ++i) {
            instance_transforms[obj].emplace_back(std::optional<Geometry::Transformation>());
            ++instances_count;
        }
    }
    if (instances_count == 1)
        return;
    // second: fill temporary cache with data from volumes
    for (const GLVolume* v : m_volumes.volumes) {
        if (v->is_wipe_tower)
            continue;
        const int object_idx = v->object_idx();
        const int instance_idx = v->instance_idx();
        auto& transform = instance_transforms[object_idx][instance_idx];
        if (!transform.has_value())
            transform = instance_transform_from_volumes(object_idx, instance_idx);
    }
    // helper function to calculate the transformation to be applied to the sequential print clearance contours
    auto instance_trafo = [](const Transform3d& hull_trafo, const Geometry::Transformation& inst_trafo) {
        Vec3d offset = inst_trafo.get_offset() - hull_trafo.translation();
        offset.z() = 0.0;
        return Geometry::translation_transform(offset) *
            Geometry::rotation_transform(Geometry::rotation_diff_z(hull_trafo, inst_trafo.get_matrix()) * Vec3d::UnitZ());
    };
    // calculates objects 2d hulls (see also: Print::sequential_print_horizontal_clearance_valid())
    // this is done only the first time this method is called while moving the mouse,
    // the results are then cached for following displacements
    if (force_contours_generation || m_sequential_print_clearance_first_displacement) {
        m_sequential_print_clearance.m_evaluating = false;
        m_sequential_print_clearance.m_hulls_2d_cache.clear();
        const float shrink_factor = static_cast<float>(scale_(0.5 * fff_print()->config().extruder_clearance_radius.value - EPSILON));
        const double mitter_limit = scale_(0.1);
        m_sequential_print_clearance.m_hulls_2d_cache.reserve(m_model->objects.size());
        for (size_t i = 0; i < m_model->objects.size(); ++i) {
            ModelObject* model_object = m_model->objects[i];
            Geometry::Transformation trafo = instance_transform_from_volumes((int)i, 0);
            trafo.set_offset({ 0.0, 0.0, trafo.get_offset().z() });
            Pointf3s& new_hull_2d = m_sequential_print_clearance.m_hulls_2d_cache.emplace_back(std::make_pair(Pointf3s(), trafo.get_matrix())).first;
            if (is_object_outside_printbed((int)i))
                continue;
            Polygon hull_2d = model_object->convex_hull_2d(trafo.get_matrix());
            if (!hull_2d.empty()) {
                // Shrink the extruder_clearance_radius a tiny bit, so that if the object arrangement algorithm placed the objects
                // exactly by satisfying the extruder_clearance_radius, this test will not trigger collision.
                const Polygons offset_res = offset(hull_2d, shrink_factor, jtRound, mitter_limit);
                if (!offset_res.empty())
                    hull_2d = offset_res.front();
            }
            new_hull_2d.reserve(hull_2d.points.size());
            for (const Point& p : hull_2d.points) {
                new_hull_2d.emplace_back(Vec3d(unscale<double>(p.x()), unscale<double>(p.y()), 0.0));
            }
        }
        ContoursList contours;
        contours.contours.reserve(instance_transforms.size());
        contours.trafos = std::vector<std::pair<size_t, Transform3d>>();
        (*contours.trafos).reserve(instances_count);
        for (size_t i = 0; i < instance_transforms.size(); ++i) {
            const auto& [hull, hull_trafo] = m_sequential_print_clearance.m_hulls_2d_cache[i];
            Points hull_pts;
            hull_pts.reserve(hull.size());
            for (size_t j = 0; j < hull.size(); ++j) {
                hull_pts.emplace_back(scaled<double>(hull[j].x()), scaled<double>(hull[j].y()));
            }
            contours.contours.emplace_back(Geometry::convex_hull(std::move(hull_pts)));
            const auto& instances = instance_transforms[i];
            for (const auto& instance : instances) {
                (*contours.trafos).emplace_back(i, instance_trafo(hull_trafo, *instance));
            }
        }
        set_sequential_print_clearance_contours(contours, false);
        m_sequential_print_clearance_first_displacement = false;
    }
    else {
        if (!m_sequential_print_clearance.empty()) {
            std::vector<Transform3d> trafos;
            trafos.reserve(instances_count);
            for (size_t i = 0; i < instance_transforms.size(); ++i) {
                const auto& [hull, hull_trafo] = m_sequential_print_clearance.m_hulls_2d_cache[i];
                const auto& instances = instance_transforms[i];
                for (const auto& instance : instances) {
                    trafos.emplace_back(instance_trafo(hull_trafo, *instance));
                }
            }
            m_sequential_print_clearance.update_instances_trafos(trafos);
        }
    }
}
References Slic3r::GUI::GLCanvas3D::ContoursList::contours, Slic3r::Geometry::convex_hull(), Slic3r::ModelObject::convex_hull_2d(), current_printer_technology(), Slic3r::MultiPoint::empty(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::empty(), EPSILON, fff_print(), Slic3r::MultiPoint::front(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::ModelObject::instances, Slic3r::GUI::GLCanvas3D::LayersEditing::is_enabled(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_evaluating, Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_hulls_2d_cache, m_layers_editing, m_model, m_sequential_print_clearance, m_sequential_print_clearance_first_displacement, m_volumes, Slic3r::Model::objects, Slic3r::offset(), Slic3r::MultiPoint::points, Slic3r::ptFFF, Slic3r::Geometry::rotation_diff_z(), Slic3r::Geometry::rotation_transform(), scale_, Slic3r::Geometry::Transformation::set_offset(), set_sequential_print_clearance_contours(), Slic3r::GUI::GLCanvas3D::ContoursList::trafos, Slic3r::transform(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation(), Slic3r::Geometry::translation_transform(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::update_instances_trafos(), and Slic3r::GLVolumeCollection::volumes.
Referenced by do_move(), do_rotate(), do_scale(), and on_mouse().
update_tooltip_for_settings_item_in_main_toolbar()
void Slic3r::GUI::GLCanvas3D::update_tooltip_for_settings_item_in_main_toolbar ()
{
    std::string new_tooltip = _u8L("Switch to Settings") +
                             "\n" + "[" + GUI::shortkey_ctrl_prefix() + "2] - " + _u8L("Print Settings Tab")    +
                             "\n" + "[" + GUI::shortkey_ctrl_prefix() + "3] - " + (current_printer_technology() == ptFFF ? _u8L("Filament Settings Tab") : _u8L("Material Settings Tab")) +
                             "\n" + "[" + GUI::shortkey_ctrl_prefix() + "4] - " + _u8L("Printer Settings Tab") ;
    m_main_toolbar.set_tooltip(get_main_toolbar_item_id("settings"), new_tooltip);
}
References _u8L, current_printer_technology(), get_main_toolbar_item_id(), m_main_toolbar, Slic3r::ptFFF, Slic3r::GUI::GLToolbar::set_tooltip(), and Slic3r::GUI::shortkey_ctrl_prefix().
update_ui_from_settings()
void Slic3r::GUI::GLCanvas3D::update_ui_from_settings ()
{
    m_dirty = true;
#if __APPLE__
    // Update OpenGL scaling on OSX after the user toggled the "use_retina_opengl" settings in Preferences dialog.
    const float orig_scaling = m_retina_helper->get_scale_factor();
    const bool use_retina = wxGetApp().app_config->get_bool("use_retina_opengl");
    BOOST_LOG_TRIVIAL(debug) << "GLCanvas3D: Use Retina OpenGL: " << use_retina;
    m_retina_helper->set_use_retina(use_retina);
    const float new_scaling = m_retina_helper->get_scale_factor();
    if (new_scaling != orig_scaling) {
        BOOST_LOG_TRIVIAL(debug) << "GLCanvas3D: Scaling factor: " << new_scaling;
        Camera& camera = wxGetApp().plater()->get_camera();
        camera.set_zoom(camera.get_zoom() * new_scaling / orig_scaling);
        _refresh_if_shown_on_screen();
    }
#endif // ENABLE_RETINA_GL
    if (wxGetApp().is_editor())
        wxGetApp().plater()->enable_collapse_toolbar(wxGetApp().app_config->get_bool("show_collapse_button"));
}
References _refresh_if_shown_on_screen(), Slic3r::GUI::Camera::get_zoom(), m_dirty, and Slic3r::GUI::Camera::set_zoom().
update_volumes_colors_by_extruder()
void Slic3r::GUI::GLCanvas3D::update_volumes_colors_by_extruder ()
{
    if (m_config != nullptr)
        m_volumes.update_colors_by_extruder(m_config);
}
References m_config, m_volumes, and Slic3r::GLVolumeCollection::update_colors_by_extruder().
Referenced by reload_scene().
use_slope()
void Slic3r::GUI::GLCanvas3D::use_slope (bool use) inline
{ m_slope.use(use); }
References m_slope, and Slic3r::GUI::GLCanvas3D::Slope::use().
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), and Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown().
volumes_bounding_box()
BoundingBoxf3 Slic3r::GUI::GLCanvas3D::volumes_bounding_box () const
{
    BoundingBoxf3 bb;
    for (const GLVolume* volume : m_volumes.volumes) {
        if (!m_apply_zoom_to_volumes_filter || ((volume != nullptr) && volume->zoom_to_volumes))
            bb.merge(volume->transformed_bounding_box());
    }
    return bb;
}
References m_apply_zoom_to_volumes_filter, m_volumes, Slic3r::BoundingBox3Base< PointType >::merge(), and Slic3r::GLVolumeCollection::volumes.
Referenced by _max_bounding_box(), scene_bounding_box(), and zoom_to_volumes().
zoom_to_bed()
void Slic3r::GUI::GLCanvas3D::zoom_to_bed ()
{
    BoundingBoxf3 box = m_bed.build_volume().bounding_volume();
    box.min.z() = 0.0;
    box.max.z() = 0.0;
    _zoom_to_box(box);
}
References _zoom_to_box(), Slic3r::BuildVolume::bounding_volume(), Slic3r::GUI::Bed3D::build_volume(), m_bed, Slic3r::BoundingBoxBase< PointType, APointsType >::max, and Slic3r::BoundingBoxBase< PointType, APointsType >::min.
Referenced by on_char(), and render().
zoom_to_gcode()
void Slic3r::GUI::GLCanvas3D::zoom_to_gcode ()
{
    _zoom_to_box(m_gcode_viewer.get_paths_bounding_box(), 1.05);
}
References _zoom_to_box(), Slic3r::GUI::GCodeViewer::get_paths_bounding_box(), and m_gcode_viewer.
zoom_to_selection()
void Slic3r::GUI::GLCanvas3D::zoom_to_selection ()
{
    if (!m_selection.is_empty())
        _zoom_to_box(m_selection.get_bounding_box());
}
References _zoom_to_box(), Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::Selection::is_empty(), and m_selection.
Referenced by on_char().
zoom_to_volumes()
void Slic3r::GUI::GLCanvas3D::zoom_to_volumes ()
{
    m_apply_zoom_to_volumes_filter = true;
    _zoom_to_box(volumes_bounding_box());
    m_apply_zoom_to_volumes_filter = false;
}
References _zoom_to_box(), m_apply_zoom_to_volumes_filter, and volumes_bounding_box().
Referenced by on_char().
Member Data Documentation
DefaultCameraZoomToBoxMarginFactor
const double Slic3r::GUI::GLCanvas3D::DefaultCameraZoomToBoxMarginFactor = 1.25 static private
m_apply_zoom_to_volumes_filter
bool Slic3r::GUI::GLCanvas3D::m_apply_zoom_to_volumes_filter private
Referenced by volumes_bounding_box(), and zoom_to_volumes().
m_arrange_settings_fff
ArrangeSettings Slic3r::GUI::GLCanvas3D::m_arrange_settings_fff private
Referenced by load_arrange_settings().
m_arrange_settings_fff_seq_print
ArrangeSettings Slic3r::GUI::GLCanvas3D::m_arrange_settings_fff_seq_print private
Referenced by get_arrange_settings(), and load_arrange_settings().
m_arrange_settings_sla
ArrangeSettings Slic3r::GUI::GLCanvas3D::m_arrange_settings_sla private
Referenced by load_arrange_settings().
m_background
GLModel Slic3r::GUI::GLCanvas3D::m_background private
m_bed
Bed3D& Slic3r::GUI::GLCanvas3D::m_bed private
Referenced by _max_bounding_box(), _render_thumbnail_internal(), check_volumes_outside_state(), get_size_proportional_to_max_bed_size(), load_preview(), reload_scene(), render(), scene_bounding_box(), and zoom_to_bed().
m_camera_clipping_plane
ClippingPlane Slic3r::GUI::GLCanvas3D::m_camera_clipping_plane private
m_canvas
wxGLCanvas* Slic3r::GUI::GLCanvas3D::m_canvas private
Referenced by GLCanvas3D(), _init_main_toolbar(), _init_undoredo_toolbar(), _is_shown_on_screen(), _resize(), _set_current(), bind_event_handlers(), get_canvas_size(), get_local_mouse_position(), get_wxglcanvas(), get_wxglcanvas(), init(), load_sla_preview(), mouse_up_cleanup(), on_char(), on_key(), on_mouse(), on_mouse_wheel(), post_event(), reload_scene(), render(), Slic3r::GUI::GLCanvas3D::Labels::render(), select_view(), set_cursor(), set_tooltip(), and unbind_event_handlers().
m_clipping_planes
std::array<ClippingPlane, 2> Slic3r::GUI::GLCanvas3D::m_clipping_planes private
Referenced by get_clipping_planes(), and set_clipping_plane().
m_config
const DynamicPrintConfig* Slic3r::GUI::GLCanvas3D::m_config private
Referenced by _render_arrange_menu(), get_arrange_settings(), get_wipe_tower_info(), is_arrange_alignment_enabled(), load_gcode_preview(), reload_scene(), Slic3r::GUI::GLCanvas3D::LayersEditing::set_config(), set_config(), Slic3r::GUI::GLCanvas3D::LayersEditing::update_slicing_parameters(), and update_volumes_colors_by_extruder().
m_context
wxGLContext* Slic3r::GUI::GLCanvas3D::m_context private
Referenced by _resize(), _set_current(), init(), and set_context().
m_ctrl_kar_filter
KeyAutoRepeatFilter Slic3r::GUI::GLCanvas3D::m_ctrl_kar_filter private
Referenced by on_key().
m_cursor_type
ECursorType Slic3r::GUI::GLCanvas3D::m_cursor_type private
Referenced by set_cursor().
m_dirty
bool Slic3r::GUI::GLCanvas3D::m_dirty private
Referenced by _update_camera_zoom(), _zoom_to_box(), adaptive_layer_height_profile(), bed_shape_changed(), detect_sla_view_type(), do_mirror(), do_move(), do_reset_skew(), do_rotate(), do_scale(), handle_sidebar_focus_event(), mouse_up_cleanup(), on_char(), on_idle(), on_key(), on_mouse(), on_mouse_wheel(), on_paint(), on_size(), reload_scene(), render(), reset_layer_height_profile(), reset_volumes(), schedule_extra_frame(), select_all(), set_as_dirty(), set_sla_view_type(), set_sla_view_type(), show_legend(), smooth_layer_height_profile(), and update_ui_from_settings().
m_dynamic_background_enabled
bool Slic3r::GUI::GLCanvas3D::m_dynamic_background_enabled private
Referenced by enable_dynamic_background().
m_event_handlers_bound
bool Slic3r::GUI::GLCanvas3D::m_event_handlers_bound { false } private
Referenced by bind_event_handlers(), and unbind_event_handlers().
m_extra_frame_requested
bool Slic3r::GUI::GLCanvas3D::m_extra_frame_requested private
Referenced by on_idle(), and request_extra_frame().
m_gcode_viewer
GCodeViewer Slic3r::GUI::GLCanvas3D::m_gcode_viewer private
Referenced by _max_bounding_box(), enable_legend_texture(), export_toolpaths_to_obj(), get_custom_gcode_per_print_z(), get_gcode_extruders_count(), get_gcode_layers_zs(), get_gcode_options_visibility_flags(), get_gcode_sequential_view(), get_gcode_view_preview_type(), get_gcode_view_type(), get_toolpath_role_visibility_flags(), has_toolpaths_to_export(), init_gcode_viewer(), is_gcode_legend_enabled(), is_legend_shown(), load_gcode_preview(), msw_rescale(), on_char(), refresh_gcode_preview_render_paths(), render(), reset_gcode_toolpaths(), set_gcode_options_visibility_from_flags(), set_gcode_view_preview_type(), set_toolpath_role_visibility_flags(), set_toolpath_view_type(), set_toolpaths_z_range(), show_legend(), update_gcode_sequential_view_current(), and zoom_to_gcode().
m_gizmo_highlighter
struct Slic3r::GUI::GLCanvas3D::GizmoHighlighter Slic3r::GUI::GLCanvas3D::m_gizmo_highlighter private
Referenced by bind_event_handlers().
m_gizmos
GLGizmosManager Slic3r::GUI::GLCanvas3D::m_gizmos private
Referenced by _init_main_toolbar(), _max_bounding_box(), _picking_pass(), _rectangular_selection_picking_pass(), deselect_all(), enable_gizmos(), get_gizmos_manager(), get_gizmos_manager(), handle_sidebar_focus_event(), init(), is_dragging(), on_char(), on_key(), on_mouse(), on_mouse_wheel(), reload_scene(), render(), reset_all_gizmos(), select_all(), and update_gizmos_on_off_state().
m_hover_volume_idxs
std::vector<int> Slic3r::GUI::GLCanvas3D::m_hover_volume_idxs private
Referenced by _picking_pass(), get_first_hover_volume_idx(), on_mouse(), and reload_scene().
m_imgui_undo_redo_hovered_pos
int Slic3r::GUI::GLCanvas3D::m_imgui_undo_redo_hovered_pos { -1 } private
Referenced by _init_undoredo_toolbar(), and _render_undo_redo_stack().
m_in_render
bool Slic3r::GUI::GLCanvas3D::m_in_render private
Referenced by render(), and schedule_extra_frame().
m_initialized
bool Slic3r::GUI::GLCanvas3D::m_initialized private
Referenced by _refresh_if_shown_on_screen(), check_volumes_outside_state(), init(), is_initialized(), on_char(), on_idle(), on_mouse(), on_mouse_wheel(), on_paint(), reload_scene(), and reset_volumes().
m_labels
Labels Slic3r::GUI::GLCanvas3D::m_labels private
Referenced by are_labels_shown(), enable_labels(), on_char(), and show_labels().
m_layers_editing
LayersEditing Slic3r::GUI::GLCanvas3D::m_layers_editing private
Referenced by adaptive_layer_height_profile(), enable_layers_editing(), get_layers_height_data(), init(), is_layers_editing_allowed(), is_layers_editing_enabled(), on_mouse(), on_mouse_wheel(), on_timer(), render(), reset_layer_height_profile(), set_config(), smooth_layer_height_profile(), and update_sequential_clearance().
m_main_toolbar
GLToolbar Slic3r::GUI::GLCanvas3D::m_main_toolbar private
Referenced by _init_main_toolbar(), _max_bounding_box(), _render_arrange_menu(), _render_search_list(), enable_main_toolbar(), force_main_toolbar_left_action(), force_main_toolbar_right_action(), get_main_toolbar_height(), get_main_toolbar_item_id(), init(), on_char(), on_idle(), on_mouse(), on_mouse_wheel(), render(), and update_tooltip_for_settings_item_in_main_toolbar().
m_model
Model* Slic3r::GUI::GLCanvas3D::m_model private
Referenced by check_volumes_outside_state(), do_mirror(), do_move(), do_reset_skew(), do_rotate(), do_scale(), get_layers_height_data(), get_model(), on_mouse(), reload_scene(), set_model(), toggle_model_objects_visibility(), toggle_sla_auxiliaries_visibility(), update_instance_printable_state_for_object(), and update_sequential_clearance().
m_mouse
Mouse Slic3r::GUI::GLCanvas3D::m_mouse private
Referenced by _picking_pass(), get_move_volume_id(), is_dragging(), is_mouse_dragging(), mouse_up_cleanup(), on_key(), on_mouse(), and render().
m_mouse_wheel
int Slic3r::GUI::GLCanvas3D::m_mouse_wheel { 0 } private
Referenced by _render_search_list(), _render_undo_redo_stack(), and on_mouse_wheel().
m_moving
bool Slic3r::GUI::GLCanvas3D::m_moving private
Referenced by is_dragging(), mouse_up_cleanup(), on_key(), and on_mouse().
m_moving_enabled
bool Slic3r::GUI::GLCanvas3D::m_moving_enabled private
Referenced by enable_moving(), and on_mouse().
m_multisample_allowed
bool Slic3r::GUI::GLCanvas3D::m_multisample_allowed private
Referenced by _rectangular_selection_picking_pass(), _render_thumbnail_framebuffer(), _render_thumbnail_framebuffer_ext(), allow_multisample(), and init().
m_old_size
std::array<unsigned int, 2> Slic3r::GUI::GLCanvas3D::m_old_size { 0, 0 } private
Referenced by _resize(), and reset_old_size().
m_picking_enabled
bool Slic3r::GUI::GLCanvas3D::m_picking_enabled private
Referenced by _max_bounding_box(), _picking_pass(), _rectangular_selection_picking_pass(), enable_picking(), on_key(), on_mouse(), and render().
m_popup_menu_positon
std::optional<Vec2d> Slic3r::GUI::GLCanvas3D::m_popup_menu_positon
Referenced by clear_popup_menu_position(), get_popup_menu_position(), and set_popup_menu_position().
m_process
BackgroundSlicingProcess* Slic3r::GUI::GLCanvas3D::m_process private
Referenced by current_printer_technology(), reload_scene(), and set_process().
m_rectangle_selection
GLSelectionRectangle Slic3r::GUI::GLCanvas3D::m_rectangle_selection private
Referenced by _rectangular_selection_picking_pass(), on_key(), on_mouse(), and render().
m_reload_delayed
bool Slic3r::GUI::GLCanvas3D::m_reload_delayed private
Referenced by is_reload_delayed(), and reload_scene().
m_render_sla_auxiliaries
bool Slic3r::GUI::GLCanvas3D::m_render_sla_auxiliaries private
Referenced by _picking_pass(), and toggle_sla_auxiliaries_visibility().
m_render_stats
RenderStats Slic3r::GUI::GLCanvas3D::m_render_stats private
Referenced by render().
m_render_timer
RenderTimer Slic3r::GUI::GLCanvas3D::m_render_timer private
Referenced by GLCanvas3D(), and schedule_extra_frame().
m_requires_check_outside_state
bool Slic3r::GUI::GLCanvas3D::m_requires_check_outside_state { false } private
Referenced by requires_check_outside_state().
m_scene_raycaster
SceneRaycaster Slic3r::GUI::GLCanvas3D::m_scene_raycaster private
Referenced by _picking_pass(), add_raycaster_for_picking(), get_raycasters_for_picking(), reload_scene(), remove_raycasters_for_picking(), remove_raycasters_for_picking(), render(), and set_raycaster_gizmos_on_top().
m_selected_extruder
int Slic3r::GUI::GLCanvas3D::m_selected_extruder private
Referenced by set_selected_extruder().
m_selection
Selection Slic3r::GUI::GLCanvas3D::m_selection private
Referenced by GLCanvas3D(), _max_bounding_box(), check_volumes_outside_state(), delete_selected(), deselect_all(), do_mirror(), do_move(), do_reset_skew(), do_rotate(), do_scale(), enable_selection(), get_selection(), get_selection(), init(), mirror_selection(), on_char(), on_key(), on_mouse(), on_mouse_wheel(), reload_scene(), reset_volumes(), select_all(), set_model(), and zoom_to_selection().
m_sequential_print_clearance
SequentialPrintClearance Slic3r::GUI::GLCanvas3D::m_sequential_print_clearance private
Referenced by do_move(), do_rotate(), do_scale(), is_sequential_print_clearance_empty(), is_sequential_print_clearance_evaluating(), reset_sequential_print_clearance(), set_sequential_clearance_as_evaluating(), set_sequential_print_clearance_contours(), and update_sequential_clearance().
m_sequential_print_clearance_first_displacement
bool Slic3r::GUI::GLCanvas3D::m_sequential_print_clearance_first_displacement { true } private
Referenced by on_mouse(), and update_sequential_clearance().
m_shift_kar_filter
KeyAutoRepeatFilter Slic3r::GUI::GLCanvas3D::m_shift_kar_filter private
Referenced by on_key().
m_sidebar_field
std::string Slic3r::GUI::GLCanvas3D::m_sidebar_field private
Referenced by handle_sidebar_focus_event().
m_sla_caps
std::array<SlaCap, 2> Slic3r::GUI::GLCanvas3D::m_sla_caps private
Referenced by reset_clipping_planes_cache(), and set_clipping_plane().
m_sla_view
SLAView Slic3r::GUI::GLCanvas3D::m_sla_view private
Referenced by detect_sla_view_type(), reload_scene(), render(), set_sla_view_type(), and set_sla_view_type().
m_sla_view_type_detection_active
bool Slic3r::GUI::GLCanvas3D::m_sla_view_type_detection_active { false } private
Referenced by enable_sla_view_type_detection(), and reload_scene().
m_slope
Slope Slic3r::GUI::GLCanvas3D::m_slope private
Referenced by enable_slope(), is_using_slope(), set_slope_normal_angle(), and use_slope().
m_tab_down
bool Slic3r::GUI::GLCanvas3D::m_tab_down private
Referenced by on_key().
m_timer
wxTimer Slic3r::GUI::GLCanvas3D::m_timer private
Referenced by GLCanvas3D().
m_toolbar_highlighter
struct Slic3r::GUI::GLCanvas3D::ToolbarHighlighter Slic3r::GUI::GLCanvas3D::m_toolbar_highlighter private
Referenced by bind_event_handlers().
m_tooltip
Tooltip Slic3r::GUI::GLCanvas3D::m_tooltip private
Referenced by on_mouse(), render(), and set_tooltip().
m_tooltip_enabled
bool Slic3r::GUI::GLCanvas3D::m_tooltip_enabled { true } private
Referenced by on_mouse(), on_set_focus(), and render().
m_undoredo_toolbar
GLToolbar Slic3r::GUI::GLCanvas3D::m_undoredo_toolbar private
Referenced by _init_undoredo_toolbar(), _render_undo_redo_stack(), enable_undoredo_toolbar(), on_idle(), on_mouse(), on_mouse_wheel(), and render().
m_use_clipping_planes
bool Slic3r::GUI::GLCanvas3D::m_use_clipping_planes private
Referenced by get_use_clipping_planes(), and set_use_clipping_planes().
m_volumes
GLVolumeCollection Slic3r::GUI::GLCanvas3D::m_volumes private
Referenced by GLCanvas3D(), _picking_pass(), _rectangular_selection_picking_pass(), check_volumes_outside_state(), check_volumes_outside_state(), detect_sla_view_type(), do_mirror(), do_move(), do_reset_skew(), do_rotate(), do_scale(), ensure_on_bed(), get_volumes(), get_volumes_count(), get_volumes_print_zs(), get_wipe_tower_info(), is_object_sinking(), load_object(), on_char(), on_mouse(), reload_scene(), render(), render_thumbnail(), reset_volumes(), set_color_clip_plane(), set_color_clip_plane_colors(), set_sla_view_type(), set_sla_view_type(), set_use_color_clip_plane(), set_volumes_z_range(), toggle_model_objects_visibility(), toggle_sla_auxiliaries_visibility(), update_instance_printable_state_for_object(), update_sequential_clearance(), update_volumes_colors_by_extruder(), and volumes_bounding_box().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLCanvas3D.hpp
src/slic3r/GUI/GLCanvas3D.cpp