Prusa Slicer: Slic3r::TriangleSelector::Triangle Class Reference
Slic3r::TriangleSelector::Triangle Class Reference
#include <src/libslic3r/TriangleSelector.hpp>
Public Member Functions
Triangle (int a, int b, int c, int source_triangle, const EnforcerBlockerType init_state)
void set_division (int sides_to_split, int special_side_idx)
void set_state (EnforcerBlockerType type)
EnforcerBlockerType get_state () const
void select_by_seed_fill ()
void unselect_by_seed_fill ()
bool is_selected_by_seed_fill () const
bool valid () const noexcept
bool is_split () const noexcept
int number_of_split_sides () const noexcept
int special_side () const noexcept
Public Attributes
std::array< int, 3 > verts_idxs
int source_triangle
std::array< int, 4 > children
Private Attributes
friend TriangleSelector
char number_of_splits { 0 }
char special_side_idx { 0 }
EnforcerBlockerType state
bool m_selected_by_seed_fill: 1
bool m_valid: 1
Detailed Description
Constructor & Destructor Documentation
Triangle()
Slic3r::TriangleSelector::Triangle::Triangle (int a, int b, int c, int source_triangle, const EnforcerBlockerType init_state) inline
            : verts_idxs{a, b, c},
              source_triangle{source_triangle},
              state{init_state}
        {
            // Initialize bit fields. Default member initializers are not supported by C++17.
            m_selected_by_seed_fill = false;
            m_valid = true;
        }
References m_selected_by_seed_fill, and m_valid.
Member Function Documentation
get_state()
EnforcerBlockerType Slic3r::TriangleSelector::Triangle::get_state () const inline
{ assert(! is_split()); return state; }
References is_split(), and state.
Referenced by Slic3r::TriangleSelector::get_facets_strict_recursive(), Slic3r::TriangleSelector::select_triangle_recursive(), Slic3r::TriangleSelector::serialize(), and Slic3r::TriangleSelector::split_triangle().
is_selected_by_seed_fill()
bool Slic3r::TriangleSelector::Triangle::is_selected_by_seed_fill () const inline
{ assert(! is_split()); return m_selected_by_seed_fill; }
References is_split(), and m_selected_by_seed_fill.
Referenced by Slic3r::TriangleSelector::get_seed_fill_contour_recursive().
is_split()
bool Slic3r::TriangleSelector::Triangle::is_split () const inline noexcept
{ return number_of_split_sides() != 0; }
References number_of_split_sides().
Referenced by Slic3r::TriangleSelector::garbage_collect(), Slic3r::TriangleSelector::get_facets_strict_recursive(), Slic3r::TriangleSelector::get_seed_fill_contour_recursive(), get_state(), is_selected_by_seed_fill(), Slic3r::TriangleSelector::perform_split(), Slic3r::TriangleSelector::precompute_all_neighbors_recursive(), Slic3r::TriangleSelector::remove_useless_children(), select_by_seed_fill(), Slic3r::TriangleSelector::select_triangle_recursive(), Slic3r::TriangleSelector::select_unsplit_triangle(), Slic3r::TriangleSelector::serialize(), set_state(), special_side(), Slic3r::TriangleSelector::undivide_triangle(), and unselect_by_seed_fill().
number_of_split_sides()
int Slic3r::TriangleSelector::Triangle::number_of_split_sides () const inline noexcept
{ return number_of_splits; }
References number_of_splits.
Referenced by Slic3r::TriangleSelector::child_neighbors(), Slic3r::TriangleSelector::child_neighbors_propagated(), Slic3r::TriangleSelector::garbage_collect(), Slic3r::TriangleSelector::get_facets_strict_recursive(), Slic3r::TriangleSelector::get_seed_fill_contour_recursive(), is_split(), Slic3r::TriangleSelector::neighbor_child(), Slic3r::TriangleSelector::perform_split(), Slic3r::TriangleSelector::precompute_all_neighbors_recursive(), Slic3r::TriangleSelector::remove_useless_children(), Slic3r::TriangleSelector::select_triangle_recursive(), Slic3r::TriangleSelector::select_unsplit_triangle(), Slic3r::TriangleSelector::serialize(), Slic3r::TriangleSelector::triangle_midpoint(), Slic3r::TriangleSelector::triangle_subtriangles(), and Slic3r::TriangleSelector::undivide_triangle().
select_by_seed_fill()
void Slic3r::TriangleSelector::Triangle::select_by_seed_fill () inline
{ assert(! is_split()); m_selected_by_seed_fill = true; }
References is_split(), and m_selected_by_seed_fill.
set_division()
void Slic3r::TriangleSelector::Triangle::set_division (int sides_to_split, int special_side_idx)
{
    assert(sides_to_split >= 0 && sides_to_split <= 3);
    assert(special_side_idx >= 0 && special_side_idx < 3);
    assert(sides_to_split == 1 || sides_to_split == 2 || special_side_idx == 0);
    this->number_of_splits = char(sides_to_split);
    this->special_side_idx = char(special_side_idx);
}
References number_of_splits, and special_side_idx.
Referenced by Slic3r::TriangleSelector::split_triangle(), and Slic3r::TriangleSelector::undivide_triangle().
set_state()
void Slic3r::TriangleSelector::Triangle::set_state (EnforcerBlockerType type) inline
{ assert(! is_split()); state = type; }
References is_split(), and state.
Referenced by Slic3r::TriangleSelector::remove_useless_children(), and Slic3r::TriangleSelector::select_triangle_recursive().
special_side()
int Slic3r::TriangleSelector::Triangle::special_side () const inline noexcept
{ assert(is_split()); return special_side_idx; }
References is_split(), and special_side_idx.
Referenced by Slic3r::TriangleSelector::child_neighbors(), Slic3r::TriangleSelector::child_neighbors_propagated(), Slic3r::TriangleSelector::neighbor_child(), Slic3r::TriangleSelector::perform_split(), Slic3r::TriangleSelector::serialize(), Slic3r::TriangleSelector::triangle_midpoint(), and Slic3r::TriangleSelector::triangle_subtriangles().
unselect_by_seed_fill()
void Slic3r::TriangleSelector::Triangle::unselect_by_seed_fill () inline
{ assert(! is_split()); m_selected_by_seed_fill = false; }
References is_split(), and m_selected_by_seed_fill.
valid()
bool Slic3r::TriangleSelector::Triangle::valid () const inline noexcept
{ return m_valid; }
References m_valid.
Referenced by Slic3r::TriangleSelector::garbage_collect(), Slic3r::TriangleSelector::get_seed_fill_contour_recursive(), Slic3r::TriangleSelector::precompute_all_neighbors_recursive(), Slic3r::TriangleSelector::select_triangle_recursive(), Slic3r::TriangleSelector::select_unsplit_triangle(), and Slic3r::TriangleSelector::undivide_triangle().
Member Data Documentation
children
std::array<int, 4> Slic3r::TriangleSelector::Triangle::children
Referenced by Slic3r::TriangleSelector::child_neighbors(), Slic3r::TriangleSelector::deserialize(), Slic3r::TriangleSelector::garbage_collect(), Slic3r::TriangleSelector::get_facets_strict_recursive(), Slic3r::TriangleSelector::get_seed_fill_contour_recursive(), Slic3r::TriangleSelector::neighbor_child(), Slic3r::TriangleSelector::perform_split(), Slic3r::TriangleSelector::precompute_all_neighbors_recursive(), Slic3r::TriangleSelector::remove_useless_children(), Slic3r::TriangleSelector::select_triangle_recursive(), Slic3r::TriangleSelector::select_unsplit_triangle(), Slic3r::TriangleSelector::serialize(), Slic3r::TriangleSelector::triangle_midpoint(), Slic3r::TriangleSelector::triangle_subtriangles(), and Slic3r::TriangleSelector::undivide_triangle().
m_selected_by_seed_fill
bool Slic3r::TriangleSelector::Triangle::m_selected_by_seed_fill private
Referenced by Triangle(), is_selected_by_seed_fill(), select_by_seed_fill(), and unselect_by_seed_fill().
m_valid
bool Slic3r::TriangleSelector::Triangle::m_valid private
Referenced by Triangle(), Slic3r::TriangleSelector::undivide_triangle(), and valid().
number_of_splits
char Slic3r::TriangleSelector::Triangle::number_of_splits { 0 } private
Referenced by number_of_split_sides(), and set_division().
source_triangle
int Slic3r::TriangleSelector::Triangle::source_triangle
Referenced by Slic3r::TriangleSelector::perform_split().
special_side_idx
char Slic3r::TriangleSelector::Triangle::special_side_idx { 0 } private
Referenced by set_division(), and special_side().
state
EnforcerBlockerType Slic3r::TriangleSelector::Triangle::state private
Referenced by get_state(), and set_state().
TriangleSelector
friend Slic3r::TriangleSelector::Triangle::TriangleSelector private
verts_idxs
std::array<int, 3> Slic3r::TriangleSelector::Triangle::verts_idxs
Referenced by Slic3r::TriangleSelector::child_neighbors(), Slic3r::TriangleSelector::garbage_collect(), Slic3r::TriangleSelector::get_facets_strict_recursive(), Slic3r::TriangleSelector::Sphere::is_edge_inside_cursor(), Slic3r::TriangleSelector::Circle::is_edge_inside_cursor(), Slic3r::TriangleSelector::Capsule3D::is_edge_inside_cursor(), Slic3r::TriangleSelector::Capsule2D::is_edge_inside_cursor(), Slic3r::TriangleSelector::Cursor::is_pointer_in_triangle(), Slic3r::TriangleSelector::neighbor_child(), Slic3r::TriangleSelector::perform_split(), Slic3r::TriangleSelector::split_triangle(), Slic3r::TriangleSelector::triangle_midpoint(), Slic3r::TriangleSelector::triangle_subtriangles(), Slic3r::TriangleSelector::undivide_triangle(), Slic3r::TriangleSelector::verify_triangle_midpoints(), Slic3r::TriangleSelector::verify_triangle_neighbors(), and Slic3r::TriangleSelector::Cursor::vertices_inside().
The documentation for this class was generated from the following files:
src/libslic3r/TriangleSelector.hpp
src/libslic3r/TriangleSelector.cpp