Prusa Slicer: Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor > Struct Template Reference
Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor > Struct Template Reference
#include <src/eigen/Eigen/src/SparseCore/TriangularSolver.h>
Public Types
typedef Rhs::Scalar Scalar
typedef promote_index_type< typenametraits< Lhs >::StorageIndex, typenametraits< Rhs >::StorageIndex >::type StorageIndex
Static Public Member Functions
static void run (const Lhs &lhs, Rhs &other)
Detailed Description
template<typename Lhs, typename Rhs, int Mode, int UpLo>
struct Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >
Member Typedef Documentation
Scalar
template<typename Lhs , typename Rhs , int Mode, int UpLo> typedef Rhs::Scalar Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::Scalar
StorageIndex
template<typename Lhs , typename Rhs , int Mode, int UpLo> typedef promote_index_type<typenametraits<Lhs>::StorageIndex,typenametraits<Rhs>::StorageIndex>::type Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::StorageIndex
Member Function Documentation
run()
template<typename Lhs , typename Rhs , int Mode, int UpLo> static void Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run (const Lhs & lhs, Rhs & other) inline static
  {
    const bool IsLower = (UpLo==Lower);
    AmbiVector<Scalar,StorageIndex> tempVector(other.rows()*2);
    tempVector.setBounds(0,other.rows());
    Rhs res(other.rows(), other.cols());
    res.reserve(other.nonZeros());
    for(Index col=0 ; col<other.cols() ; ++col)
    {
      // FIXME estimate number of non zeros
      tempVector.init(.99/*float(other.col(col).nonZeros())/float(other.rows())*/);
      tempVector.setZero();
      tempVector.restart();
      for (typename Rhs::InnerIterator rhsIt(other, col); rhsIt; ++rhsIt)
      {
        tempVector.coeffRef(rhsIt.index()) = rhsIt.value();
      }
      for(Index i=IsLower?0:lhs.cols()-1;
          IsLower?i<lhs.cols():i>=0;
          i+=IsLower?1:-1)
      {
        tempVector.restart();
        Scalar& ci = tempVector.coeffRef(i);
        if (ci!=Scalar(0))
        {
          // find
          typename Lhs::InnerIterator it(lhs, i);
          if(!(Mode & UnitDiag))
          {
            if (IsLower)
            {
              eigen_assert(it.index()==i);
              ci /= it.value();
            }
            else
              ci /= lhs.coeff(i,i);
          }
          tempVector.restart();
          if (IsLower)
          {
            if (it.index()==i)
              ++it;
            for(; it; ++it)
              tempVector.coeffRef(it.index()) -= ci * it.value();
          }
          else
          {
            for(; it && it.index()<i; ++it)
              tempVector.coeffRef(it.index()) -= ci * it.value();
          }
        }
      }
      Index count = 0;
      // FIXME compute a reference value to filter zeros
      for (typename AmbiVector<Scalar,StorageIndex>::Iterator it(tempVector/*,1e-12*/); it; ++it)
      {
        ++ count;
//         std::cerr << "fill " << it.index() << ", " << col << "\n";
//         std::cout << it.value() << "  ";
        // FIXME use insertBack
        res.insert(it.index(), col) = it.value();
      }
//       std::cout << "tempVector.nonZeros() == " << int(count) << " / " << (other.rows()) << "\n";
    }
    res.finalize();
    other = res.markAsRValue();
  }
References Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::coeffRef(), col(), eigen_assert, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::init(), Eigen::Lower, Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::restart(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setBounds(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >::setZero(), and Eigen::UnitDiag.
The documentation for this struct was generated from the following file:
src/eigen/Eigen/src/SparseCore/TriangularSolver.h