Prusa Slicer: Slic3r::DnsQuestion Struct Reference
Slic3r::DnsQuestion Struct Reference
Public Types
enum { MIN_SIZE = 5 }
Public Member Functions
DnsQuestion ()
Static Public Member Functions
static optional< DnsQuestion > decode (const std::vector< char > &buffer, size_t &offset)
Public Attributes
DnsName name
uint16_t type
uint16_t qclass
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MIN_SIZE
  {
    MIN_SIZE = 5,
  };
Constructor & Destructor Documentation
DnsQuestion()
Slic3r::DnsQuestion::DnsQuestion () inline
    : type(0)
    , qclass(0)
  {}
Member Function Documentation
decode()
static optional< DnsQuestion > Slic3r::DnsQuestion::decode (const std::vector< char > & buffer, size_t & offset) inline static
  {
    auto qname = DnsName::decode(buffer, offset);
    if (!qname) {
      return boost::none;
    }
    DnsQuestion res;
    res.name = std::move(*qname);
    const uint16_t *data_16 = reinterpret_cast<const uint16_t*>(buffer.data() + offset);
    res.type = endian::big_to_native(data_16[0]);
    res.qclass = endian::big_to_native(data_16[1]);
    offset += 4;
    return std::move(res);
  }
References Slic3r::DnsName::decode(), name, Slic3r::offset(), qclass, and type.
Referenced by Slic3r::DnsMessage::decode().
Member Data Documentation
name
DnsName Slic3r::DnsQuestion::name
Referenced by decode().
qclass
uint16_t Slic3r::DnsQuestion::qclass
Referenced by decode().
type
uint16_t Slic3r::DnsQuestion::type
Referenced by decode().
The documentation for this struct was generated from the following file:
src/slic3r/Utils/Bonjour.cpp