Prusa Slicer: Slic3r::AABBTreeLines::LinesDistancer< LineType > Class Template Reference
Slic3r::AABBTreeLines::LinesDistancer< LineType > Class Template Reference
#include <src/libslic3r/AABBTreeLines.hpp>
Public Types
using Scalar = typename LineType::Scalar
using Floating = typename std::conditional< std::is_floating_point< Scalar >::value, Scalar, double >::type
Public Member Functions
LinesDistancer (const std::vector< LineType > &lines)
LinesDistancer (std::vector< LineType > &&lines)
LinesDistancer ()=default
int outside (const Vec< 2, Scalar > &point) const
template<bool SIGNED_DISTANCE>
std::tuple< Floating, size_t, Vec< 2, Floating > > distance_from_lines_extra (const Vec< 2, Scalar > &point) const
template<bool SIGNED_DISTANCE>
Floating distance_from_lines (const Vec< 2, Scalar > &point) const
std::vector< size_t > all_lines_in_radius (const Vec< 2, Scalar > &point, Floating radius)
template<bool sorted>
std::vector< std::pair< Vec< 2, Scalar >, size_t > > intersections_with_line (const LineType &line) const
const LineType & get_line (size_t line_idx) const
const std::vector< LineType > & get_lines () const
Private Attributes
std::vector< LineType > lines
AABBTreeIndirect::Tree< 2, Scalar > tree
Detailed Description
template<typename LineType>
class Slic3r::AABBTreeLines::LinesDistancer< LineType >
Member Typedef Documentation
Floating
template<typename LineType > using Slic3r::AABBTreeLines::LinesDistancer< LineType >::Floating = typename std::conditional<std::is_floating_point<Scalar>::value, Scalar, double>::type
Scalar
template<typename LineType > using Slic3r::AABBTreeLines::LinesDistancer< LineType >::Scalar = typename LineType::Scalar
Constructor & Destructor Documentation
LinesDistancer() [1/3]
template<typename LineType > Slic3r::AABBTreeLines::LinesDistancer< LineType >::LinesDistancer (const std::vector< LineType > & lines) inline explicit
                                                              : lines(lines)
    {
        tree = AABBTreeLines::build_aabb_tree_over_indexed_lines(this->lines);
    }
References Slic3r::AABBTreeLines::build_aabb_tree_over_indexed_lines(), and Slic3r::AABBTreeLines::LinesDistancer< LineType >::tree.
LinesDistancer() [2/3]
template<typename LineType > Slic3r::AABBTreeLines::LinesDistancer< LineType >::LinesDistancer (std::vector< LineType > && lines) inline explicit
                                                         : lines(lines)
    {
        tree = AABBTreeLines::build_aabb_tree_over_indexed_lines(this->lines);
    }
References Slic3r::AABBTreeLines::build_aabb_tree_over_indexed_lines(), and Slic3r::AABBTreeLines::LinesDistancer< LineType >::tree.
LinesDistancer() [3/3]
template<typename LineType > Slic3r::AABBTreeLines::LinesDistancer< LineType >::LinesDistancer () default
Member Function Documentation
all_lines_in_radius()
template<typename LineType > std::vector< size_t > Slic3r::AABBTreeLines::LinesDistancer< LineType >::all_lines_in_radius (const Vec< 2, Scalar > & point, Floating radius) inline
    {
        return AABBTreeLines::all_lines_in_radius(this->lines, this->tree, point.template cast<Floating>(), radius * radius);
    }
References Slic3r::AABBTreeLines::all_lines_in_radius().
distance_from_lines()
template<typename LineType > template<bool SIGNED_DISTANCE> Floating Slic3r::AABBTreeLines::LinesDistancer< LineType >::distance_from_lines (const Vec< 2, Scalar > & point) const inline
    {
        auto [dist, idx, np] = distance_from_lines_extra<SIGNED_DISTANCE>(point);
        return dist;
    }
Referenced by Slic3r::SupportSpotsGenerator::check_extrusion_entity_stability().
distance_from_lines_extra()
template<typename LineType > template<bool SIGNED_DISTANCE> std::tuple< Floating, size_t, Vec< 2, Floating > > Slic3r::AABBTreeLines::LinesDistancer< LineType >::distance_from_lines_extra (const Vec< 2, Scalar > & point) const inline
    {
        size_t           nearest_line_index_out = size_t(-1);
        Vec<2, Floating> nearest_point_out      = Vec<2, Floating>::Zero();
        Vec<2, Floating> p                      = point.template cast<Floating>();
        auto distance = AABBTreeLines::squared_distance_to_indexed_lines(lines, tree, p, nearest_line_index_out, nearest_point_out);
        if (distance < 0) {
            return {std::numeric_limits<Floating>::infinity(), nearest_line_index_out, nearest_point_out};
        }
        distance = sqrt(distance);
        if (SIGNED_DISTANCE) {
            distance *= outside(point);
        }
        return {distance, nearest_line_index_out, nearest_point_out};
    }
References Slic3r::AABBTreeLines::LinesDistancer< LineType >::lines, Slic3r::AABBTreeLines::LinesDistancer< LineType >::outside(), sqrt(), Slic3r::AABBTreeLines::squared_distance_to_indexed_lines(), and Slic3r::AABBTreeLines::LinesDistancer< LineType >::tree.
Referenced by Slic3r::SupportSpotsGenerator::check_extrusion_entity_stability().
get_line()
template<typename LineType > const LineType & Slic3r::AABBTreeLines::LinesDistancer< LineType >::get_line (size_t line_idx) const inline
{ return lines[line_idx]; }
References Slic3r::AABBTreeLines::LinesDistancer< LineType >::lines.
Referenced by Slic3r::SupportSpotsGenerator::check_extrusion_entity_stability().
get_lines()
template<typename LineType > const std::vector< LineType > & Slic3r::AABBTreeLines::LinesDistancer< LineType >::get_lines () const inline
{ return lines; }
References Slic3r::AABBTreeLines::LinesDistancer< LineType >::lines.
Referenced by Slic3r::SupportSpotsGenerator::check_extrusion_entity_stability(), and Slic3r::SupportSpotsGenerator::check_stability().
intersections_with_line()
template<typename LineType > template<bool sorted> std::vector< std::pair< Vec< 2, Scalar >, size_t > > Slic3r::AABBTreeLines::LinesDistancer< LineType >::intersections_with_line (const LineType & line) const inline
    {
        return get_intersections_with_line<sorted, Vec<2, Scalar>>(lines, tree, line);
    }
References Slic3r::AABBTreeLines::LinesDistancer< LineType >::lines, and Slic3r::AABBTreeLines::LinesDistancer< LineType >::tree.
outside()
template<typename LineType > int Slic3r::AABBTreeLines::LinesDistancer< LineType >::outside (const Vec< 2, Scalar > & point) const inline
{ return point_outside_closed_contours(lines, tree, point); }
References Slic3r::AABBTreeLines::LinesDistancer< LineType >::lines, Slic3r::AABBTreeLines::point_outside_closed_contours(), and Slic3r::AABBTreeLines::LinesDistancer< LineType >::tree.
Referenced by Slic3r::AABBTreeLines::LinesDistancer< LineType >::distance_from_lines_extra().
Member Data Documentation
lines
template<typename LineType > std::vector<LineType> Slic3r::AABBTreeLines::LinesDistancer< LineType >::lines private
Referenced by Slic3r::AABBTreeLines::LinesDistancer< LineType >::distance_from_lines_extra(), Slic3r::AABBTreeLines::LinesDistancer< LineType >::get_line(), Slic3r::AABBTreeLines::LinesDistancer< LineType >::get_lines(), Slic3r::AABBTreeLines::LinesDistancer< LineType >::intersections_with_line(), and Slic3r::AABBTreeLines::LinesDistancer< LineType >::outside().
tree
template<typename LineType > AABBTreeIndirect::Tree<2, Scalar> Slic3r::AABBTreeLines::LinesDistancer< LineType >::tree private
Referenced by Slic3r::AABBTreeLines::LinesDistancer< LineType >::LinesDistancer(), Slic3r::AABBTreeLines::LinesDistancer< LineType >::LinesDistancer(), Slic3r::AABBTreeLines::LinesDistancer< LineType >::distance_from_lines_extra(), Slic3r::AABBTreeLines::LinesDistancer< LineType >::intersections_with_line(), and Slic3r::AABBTreeLines::LinesDistancer< LineType >::outside().
The documentation for this class was generated from the following file:
src/libslic3r/AABBTreeLines.hpp