Prusa Slicer: Slic3r::FFFTreeSupport::SupportElementMerging Struct Reference
Slic3r::FFFTreeSupport::SupportElementMerging Struct Reference
Public Member Functions
const Eigen::AlignedBox< coord_t, 2 > & bbox () const
const Point centroid () const
void set_bbox (const BoundingBox &abbox)
Static Public Member Functions
static size_t idx ()
Public Attributes
SupportElementState state
SupportElement::ParentIndices parents
All elements in the layer above the current one that are supported by this element.
SupportElementInfluenceAreas areas
Eigen::AlignedBox< coord_t, 2 > bbox_data
Detailed Description
Member Function Documentation
bbox()
const Eigen::AlignedBox< coord_t, 2 > & Slic3r::FFFTreeSupport::SupportElementMerging::bbox () const inline
{ return bbox_data;}
Referenced by Slic3r::FFFTreeSupport::merge_influence_areas_two_elements().
centroid()
const Point Slic3r::FFFTreeSupport::SupportElementMerging::centroid () const inline
{ return (bbox_data.min() + bbox_data.max()) / 2; }
References Eigen::AlignedBox< _Scalar, _AmbientDim >::max(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::min().
idx()
static size_t Slic3r::FFFTreeSupport::SupportElementMerging::idx () inline static
{ return 0; }
set_bbox()
void Slic3r::FFFTreeSupport::SupportElementMerging::set_bbox (const BoundingBox & abbox) inline
        { Point eps { coord_t(SCALED_EPSILON), coord_t(SCALED_EPSILON) }; bbox_data = { abbox.min - eps, abbox.max + eps }; }
References Slic3r::BoundingBoxBase< PointType, APointsType >::max, Slic3r::BoundingBoxBase< PointType, APointsType >::min, and SCALED_EPSILON.
Referenced by Slic3r::FFFTreeSupport::merge_influence_areas_two_elements().
Member Data Documentation
areas
SupportElementInfluenceAreas Slic3r::FFFTreeSupport::SupportElementMerging::areas
Referenced by Slic3r::FFFTreeSupport::merge_influence_areas_two_elements().
bbox_data
Eigen::AlignedBox<coord_t, 2> Slic3r::FFFTreeSupport::SupportElementMerging::bbox_data
parents
SupportElement::ParentIndices Slic3r::FFFTreeSupport::SupportElementMerging::parents
All elements in the layer above the current one that are supported by this element.
Referenced by Slic3r::FFFTreeSupport::merge_influence_areas_two_elements().
state
SupportElementState Slic3r::FFFTreeSupport::SupportElementMerging::state
Referenced by Slic3r::FFFTreeSupport::merge_influence_areas_two_elements().
The documentation for this struct was generated from the following file:
src/libslic3r/Support/TreeSupport.cpp