Prusa Slicer: Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs > Class Template Reference
Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs > Class Template Reference
#include <src/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = _ConjLhs , ConjRhs = _ConjRhs , Vectorizable , RealPacketSize = Vectorizable ? packet_traits<RealScalar>::size : 1 ,
ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1 , LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1 , RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1 , nr = 4 ,
mr = ResPacketSize , LhsProgress = ResPacketSize , RhsProgress = 1
}
typedef std::complex< RealScalar > Scalar
typedef std::complex< RealScalar > LhsScalar
typedef std::complex< RealScalar > RhsScalar
typedef std::complex< RealScalar > ResScalar
typedef packet_traits< RealScalar >::type RealPacket
typedef packet_traits< Scalar >::type ScalarPacket
typedef DoublePacket< RealPacket > DoublePacketType
typedef conditional< Vectorizable, RealPacket, Scalar >::type LhsPacket
typedef conditional< Vectorizable, DoublePacketType, Scalar >::type RhsPacket
typedef conditional< Vectorizable, ScalarPacket, Scalar >::type ResPacket
typedef conditional< Vectorizable, DoublePacketType, Scalar >::type AccPacket
Public Member Functions
EIGEN_STRONG_INLINE void initAcc (Scalar &p)
EIGEN_STRONG_INLINE void initAcc (DoublePacketType &p)
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, ResPacket &dest) const
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, DoublePacketType &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, ResPacket &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, DoublePacketType &dest) const
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsPacket &b0, RhsPacket &b1, RhsPacket &b2, RhsPacket &b3)
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, DoublePacketType &b0, DoublePacketType &b1)
EIGEN_STRONG_INLINE void broadcastRhs (const RhsScalar *b, RhsScalar &b0, RhsScalar &b1)
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, DoublePacketType &c, RhsPacket &) const
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, ResPacket &c, RhsPacket &) const
EIGEN_STRONG_INLINE void acc (const Scalar &c, const Scalar &alpha, Scalar &r) const
EIGEN_STRONG_INLINE void acc (const DoublePacketType &c, const ResPacket &alpha, ResPacket &r) const
Protected Attributes
conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs > cj
Detailed Description
template<typename RealScalar, bool _ConjLhs, bool _ConjRhs>
class Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >
Member Typedef Documentation
AccPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,DoublePacketType,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::AccPacket
DoublePacketType
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef DoublePacket<RealPacket> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::DoublePacketType
LhsPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,RealPacket,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::LhsPacket
LhsScalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::LhsScalar
RealPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<RealScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RealPacket
ResPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,ScalarPacket,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ResPacket
ResScalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ResScalar
RhsPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,DoublePacketType,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RhsPacket
RhsScalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RhsScalar
Scalar
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::Scalar
ScalarPacket
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ScalarPacket
Member Enumeration Documentation
anonymous enum
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
RealPacketSize
ResPacketSize
LhsPacketSize
RhsPacketSize
nr
mr
LhsProgress
RhsProgress
       {
    ConjLhs = _ConjLhs,
    ConjRhs = _ConjRhs,
    Vectorizable = packet_traits<RealScalar>::Vectorizable
                && packet_traits<Scalar>::Vectorizable,
    RealPacketSize  = Vectorizable ? packet_traits<RealScalar>::size : 1,
    ResPacketSize   = Vectorizable ? packet_traits<ResScalar>::size : 1,
    LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1,
    RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1,
    // FIXME: should depend on NumberOfRegisters
    nr = 4,
    mr = ResPacketSize,
    LhsProgress = ResPacketSize,
    RhsProgress = 1
  };
Member Function Documentation
acc() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc (const DoublePacketType & c, const ResPacket & alpha, ResPacket & r) const inline
  {
    // assemble c
    ResPacket tmp;
    if((!ConjLhs)&&(!ConjRhs))
    {
      tmp = pcplxflip(pconj(ResPacket(c.second)));
      tmp = padd(ResPacket(c.first),tmp);
    }
    else if((!ConjLhs)&&(ConjRhs))
    {
      tmp = pconj(pcplxflip(ResPacket(c.second)));
      tmp = padd(ResPacket(c.first),tmp);
    }
    else if((ConjLhs)&&(!ConjRhs))
    {
      tmp = pcplxflip(ResPacket(c.second));
      tmp = padd(pconj(ResPacket(c.first)),tmp);
    }
    else if((ConjLhs)&&(ConjRhs))
    {
      tmp = pcplxflip(ResPacket(c.second));
      tmp = psub(pconj(ResPacket(c.first)),tmp);
    }
    r = pmadd(tmp,alpha,r);
  }
References Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::ConjLhs, Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::ConjRhs, Eigen::internal::padd(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pmadd(), and Eigen::internal::psub().
acc() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc (const Scalar & c, const Scalar & alpha, Scalar & r) const inline
{ r += alpha * c; }
broadcastRhs() [1/3]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, DoublePacketType & b0, DoublePacketType & b1) inline
  {
    // FIXME not sure that's the best way to implement it!
    loadRhs(b+0, b0);
    loadRhs(b+1, b1);
  }
References Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadRhs().
broadcastRhs() [2/3]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, RhsPacket & b0, RhsPacket & b1, RhsPacket & b2, RhsPacket & b3) inline
  {
    // FIXME not sure that's the best way to implement it!
    loadRhs(b+0, b0);
    loadRhs(b+1, b1);
    loadRhs(b+2, b2);
    loadRhs(b+3, b3);
  }
References Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadRhs().
broadcastRhs() [3/3]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::broadcastRhs (const RhsScalar * b, RhsScalar & b0, RhsScalar & b1) inline
  {
    // FIXME not sure that's the best way to implement it!
    loadRhs(b+0, b0);
    loadRhs(b+1, b1);
  }
References Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadRhs().
initAcc() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::initAcc (DoublePacketType & p) inline
  {
    p.first   = pset1<RealPacket>(RealScalar(0));
    p.second  = pset1<RealPacket>(RealScalar(0));
  }
References Eigen::internal::DoublePacket< Packet >::first, and Eigen::internal::DoublePacket< Packet >::second.
initAcc() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::initAcc (Scalar & p) inline
{ p = Scalar(0); }
loadLhs()
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
  {
    dest = pload<LhsPacket>((const typename unpacket_traits<LhsPacket>::type*)(a));
  }
loadLhsUnaligned()
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadLhsUnaligned (const LhsScalar * a, LhsPacket & dest) const inline
  {
    dest = ploadu<LhsPacket>((const typename unpacket_traits<LhsPacket>::type*)(a));
  }
loadRhs() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs (const RhsScalar * b, DoublePacketType & dest) const inline
  {
    dest.first  = pset1<RealPacket>(real(*b));
    dest.second = pset1<RealPacket>(imag(*b));
  }
References Eigen::internal::DoublePacket< Packet >::first, imag(), real(), and Eigen::internal::DoublePacket< Packet >::second.
loadRhs() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs (const RhsScalar * b, ResPacket & dest) const inline
  {
    dest = pset1<ResPacket>(*b);
  }
loadRhsQuad() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhsQuad (const RhsScalar * b, DoublePacketType & dest) const inline
  {
    eigen_internal_assert(unpacket_traits<ScalarPacket>::size<=4);
    loadRhs(b,dest);
  }
References eigen_internal_assert, and Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadRhs().
loadRhsQuad() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhsQuad (const RhsScalar * b, ResPacket & dest) const inline
  {
    loadRhs(b,dest);
  }
References Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadRhs().
madd() [1/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd (const LhsPacket & a, const RhsPacket & b, DoublePacketType & c, RhsPacket &) const inline
  {
    c.first   = padd(pmul(a,b.first), c.first);
    c.second  = padd(pmul(a,b.second),c.second);
  }
References Eigen::internal::padd(), and Eigen::internal::pmul().
madd() [2/2]
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd (const LhsPacket & a, const RhsPacket & b, ResPacket & c, RhsPacket &) const inline
  {
    c = cj.pmadd(a,b,c);
  }
Member Data Documentation
cj
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> conj_helper<LhsScalar,RhsScalar,ConjLhs,ConjRhs> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::cj protected
The documentation for this class was generated from the following file:
src/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h