Prusa Slicer: Slic3r::GUI::MenuFactory Class Reference
Slic3r::GUI::MenuFactory Class Reference
#include <src/slic3r/GUI/GUI_Factories.hpp>
Public Member Functions
MenuFactory ()
~MenuFactory ()=default
void init (wxWindow *parent)
void update ()
void update_objects_menu ()
void update_default_menu ()
void sys_color_changed ()
wxMenu * default_menu ()
wxMenu * object_menu ()
wxMenu * sla_object_menu ()
wxMenu * part_menu ()
wxMenu * text_part_menu ()
wxMenu * instance_menu ()
wxMenu * layer_menu ()
wxMenu * multi_selection_menu ()
Static Public Member Functions
static std::vector< wxBitmapBundle * > get_volume_bitmaps ()
static std::vector< wxBitmapBundle * > get_text_volume_bitmaps ()
static void sys_color_changed (wxMenuBar *menu_bar)
Private Types
enum MenuType { mtObjectFFF = 0 , mtObjectSLA , mtCount }
Private Member Functions
void create_default_menu ()
void create_common_object_menu (wxMenu *menu)
void append_immutable_part_menu_items (wxMenu *menu)
void append_mutable_part_menu_items (wxMenu *menu)
void create_part_menu ()
void create_text_part_menu ()
void create_instance_menu ()
wxMenu * append_submenu_add_generic (wxMenu *menu, ModelVolumeType type)
void append_menu_item_add_text (wxMenu *menu, ModelVolumeType type, bool is_submenu_item=true)
void append_menu_items_add_volume (MenuType type)
wxMenuItem * append_menu_item_layers_editing (wxMenu *menu)
wxMenuItem * append_menu_item_settings (wxMenu *menu)
wxMenuItem * append_menu_item_change_type (wxMenu *menu)
wxMenuItem * append_menu_item_instance_to_object (wxMenu *menu)
wxMenuItem * append_menu_item_printable (wxMenu *menu)
void append_menu_item_invalidate_cut_info (wxMenu *menu)
void append_menu_items_osx (wxMenu *menu)
wxMenuItem * append_menu_item_fix_through_netfabb (wxMenu *menu)
wxMenuItem * append_menu_item_simplify (wxMenu *menu)
void append_menu_item_export_stl (wxMenu *menu)
void append_menu_item_reload_from_disk (wxMenu *menu)
void append_menu_item_replace_with_stl (wxMenu *menu)
void append_menu_item_change_extruder (wxMenu *menu)
void append_menu_item_delete (wxMenu *menu)
void append_menu_item_scale_selection_to_fit_print_volume (wxMenu *menu)
void append_menu_items_convert_unit (wxMenu *menu, int insert_pos=1)
void append_menu_item_merge_to_multipart_object (wxMenu *menu)
void append_menu_items_mirror (wxMenu *menu)
void append_menu_item_edit_text (wxMenu *menu)
void append_menu_items_instance_manipulation (wxMenu *menu)
void update_menu_items_instance_manipulation (MenuType type)
void append_menu_items_split (wxMenu *menu)
Private Attributes
wxWindow * m_parent {nullptr}
MenuWithSeparators m_object_menu
MenuWithSeparators m_part_menu
MenuWithSeparators m_text_part_menu
MenuWithSeparators m_sla_object_menu
MenuWithSeparators m_default_menu
MenuWithSeparators m_instance_menu
std::array< wxMenuItem *, mtCount > items_increase
std::array< wxMenuItem *, mtCount > items_decrease
std::array< wxMenuItem *, mtCount > items_set_number_of_copies
Detailed Description
Member Enumeration Documentation
MenuType
enum Slic3r::GUI::MenuFactory::MenuType private
Enumerator
mtObjectFFF
mtObjectSLA
mtCount
                  {
        mtObjectFFF = 0,
        mtObjectSLA,
        mtCount
    };
Constructor & Destructor Documentation
MenuFactory()
Slic3r::GUI::MenuFactory::MenuFactory ()
{
    for (int i = 0; i < mtCount; i++) {
        items_increase[i] = nullptr;
        items_decrease[i] = nullptr;
        items_set_number_of_copies[i] = nullptr;
    }
}
~MenuFactory()
Slic3r::GUI::MenuFactory::~MenuFactory () default
Member Function Documentation
append_immutable_part_menu_items()
void Slic3r::GUI::MenuFactory::append_immutable_part_menu_items (wxMenu * menu) private
{
    append_menu_items_mirror(menu);
    menu->AppendSeparator();
    append_menu_item_change_type(menu);
}
append_menu_item_add_text()
void Slic3r::GUI::MenuFactory::append_menu_item_add_text (wxMenu * menu, ModelVolumeType type, bool is_submenu_item = true) private
{
    auto add_text = [type](wxCommandEvent& evt) {
        GLCanvas3D* canvas = plater()->canvas3D();
        GLGizmosManager& mng = canvas->get_gizmos_manager();
        GLGizmoBase* gizmo = mng.get_gizmo(GLGizmosManager::Emboss);
        GLGizmoEmboss* emboss = dynamic_cast<GLGizmoEmboss *>(gizmo);
        assert(emboss != nullptr);
        if (emboss == nullptr) return;
        ModelVolumeType volume_type = type;
        // no selected object means create new object
        if (volume_type == ModelVolumeType::INVALID)
            volume_type = ModelVolumeType::MODEL_PART;
        auto screen_position = canvas->get_popup_menu_position();
        if (screen_position.has_value()) {
            emboss->create_volume(volume_type, *screen_position);
        } else {
            emboss->create_volume(volume_type);
        }
    };
    if (   type == ModelVolumeType::MODEL_PART
        || type == ModelVolumeType::NEGATIVE_VOLUME
        || type == ModelVolumeType::PARAMETER_MODIFIER
        || type == ModelVolumeType::INVALID // cannot use gizmo without selected object
        ) {
        wxString item_name = is_submenu_item ? "" : _(ADD_VOLUME_MENU_ITEMS[int(type)].first) + ": ";
        item_name += _L("Text");
        menu->AppendSeparator();
        const std::string icon_name = is_submenu_item ? "" : ADD_VOLUME_MENU_ITEMS[int(type)].second;
        append_menu_item(menu, wxID_ANY, item_name, "", add_text, icon_name, menu);
    }
}
References _, _L, Slic3r::GUI::ADD_VOLUME_MENU_ITEMS, append_menu_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLGizmoEmboss::create_volume(), Slic3r::GUI::GLGizmosManager::get_gizmo(), Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLCanvas3D::get_popup_menu_position(), and Slic3r::GUI::plater().
append_menu_item_change_extruder()
void Slic3r::GUI::MenuFactory::append_menu_item_change_extruder (wxMenu * menu) private
{
    const std::vector<wxString> names = { _L("Change extruder"), _L("Set extruder for selected items") };
    // Delete old menu item
    for (const wxString& name : names) {
        const int item_id = menu->FindItem(name);
        if (item_id != wxNOT_FOUND)
            menu->Destroy(item_id);
    }
    const int extruders_cnt = extruders_count();
    if (extruders_cnt <= 1)
        return;
    wxDataViewItemArray sels;
    obj_list()->GetSelections(sels);
    if (sels.IsEmpty())
        return;
    if (sels.Count() == 1) {
        const auto sel_vol = obj_list()->get_selected_model_volume();
        if (sel_vol && sel_vol->type() != ModelVolumeType::MODEL_PART && sel_vol->type() != ModelVolumeType::PARAMETER_MODIFIER)
            return;
    }
    std::vector<wxBitmapBundle*> icons = get_extruder_color_icons(true);
    wxMenu* extruder_selection_menu = new wxMenu();
    const wxString& name = sels.Count() == 1 ? names[0] : names[1];
    int initial_extruder = -1; // negative value for multiple object/part selection
    if (sels.Count() == 1) {
        const ModelConfig& config = obj_list()->get_item_config(sels[0]);
        initial_extruder = config.has("extruder") ? config.extruder() : 0;
    }
    for (int i = 0; i <= extruders_cnt; i++)
    {
        bool is_active_extruder = i == initial_extruder;
        int icon_idx = i == 0 ? 0 : i - 1;
        const wxString& item_name = (i == 0 ? _L("Default") : wxString::Format(_L("Extruder %d"), i)) +
            (is_active_extruder ? " (" + _L("active") + ")" : "");
        append_menu_item(extruder_selection_menu, wxID_ANY, item_name, "",
            [i](wxCommandEvent&) { obj_list()->set_extruder_for_selected_items(i); }, icons[icon_idx], menu,
            [is_active_extruder]() { return !is_active_extruder; }, m_parent);
    }
    append_submenu(menu, extruder_selection_menu, wxID_ANY, name, _L("Use another extruder"),
        "edit_uni"/* : "change_extruder"*/, []() {return true; }, m_parent);
//    menu->AppendSubMenu(extruder_selection_menu, name);
}
References _L, append_menu_item(), append_submenu(), Slic3r::ModelConfig::extruder(), Slic3r::GUI::extruders_count(), get_extruder_color_icons(), Slic3r::GUI::ObjectList::get_item_config(), Slic3r::GUI::ObjectList::get_selected_model_volume(), Slic3r::ModelConfig::has(), Slic3r::GUI::obj_list(), and Slic3r::GUI::ObjectList::set_extruder_for_selected_items().
append_menu_item_change_type()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_change_type (wxMenu * menu) private
{
    return append_menu_item(menu, wxID_ANY, _L("Change type"), "",
        [](wxCommandEvent&) { obj_list()->change_part_type(); }, "", menu,
        []() {
            wxDataViewItem item = obj_list()->GetSelection();
            return item.IsOk() || obj_list()->GetModel()->GetItemType(item) == itVolume;
        }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::change_part_type(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectList::GetModel(), Slic3r::GUI::itVolume, and Slic3r::GUI::obj_list().
append_menu_item_delete()
void Slic3r::GUI::MenuFactory::append_menu_item_delete (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Delete") + "\tDel", _L("Remove the selected object"),
        [](wxCommandEvent&) { plater()->remove_selected(); }, "delete", nullptr,
        []() { return plater()->can_delete(); }, m_parent);
    menu->AppendSeparator();
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_delete(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::remove_selected().
append_menu_item_edit_text()
void Slic3r::GUI::MenuFactory::append_menu_item_edit_text (wxMenu * menu) private
{
    wxString name        = _L("Edit text");
    auto can_edit_text = []() {
        if (plater() != nullptr) {
            const Selection& sel = plater()->get_selection();
            if (sel.volumes_count() == 1) {
                const GLVolume* gl_vol = sel.get_first_volume();
                const ModelVolume* vol = plater()->model().objects[gl_vol->object_idx()]->volumes[gl_vol->volume_idx()];
                return vol->text_configuration.has_value();
            }
        }
        return false;
    };
    if (menu != &m_text_part_menu) {
        const int menu_item_id = menu->FindItem(name);
        if (menu_item_id != wxNOT_FOUND)
            menu->Destroy(menu_item_id);
        if (!can_edit_text())
            return;
    }
    wxString description = _L("Ability to change text, font, size, ...");
    std::string icon = "";
    auto open_emboss = [](const wxCommandEvent &) {
        GLGizmosManager &mng = plater()->canvas3D()->get_gizmos_manager();
        if (mng.get_current_type() == GLGizmosManager::Emboss)
            mng.open_gizmo(GLGizmosManager::Emboss); // close() and reopen - move to be visible
        mng.open_gizmo(GLGizmosManager::Emboss);
    };
    append_menu_item(menu, wxID_ANY, name, description, open_emboss, icon, nullptr, can_edit_text, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLGizmosManager::get_current_type(), Slic3r::GUI::Selection::get_first_volume(), Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Plater::model(), Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, Slic3r::GUI::GLGizmosManager::open_gizmo(), Slic3r::GUI::plater(), Slic3r::ModelVolume::text_configuration, Slic3r::GLVolume::volume_idx(), and Slic3r::GUI::Selection::volumes_count().
append_menu_item_export_stl()
void Slic3r::GUI::MenuFactory::append_menu_item_export_stl (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Export as STL/OBJ") + dots, "",
        [](wxCommandEvent&) { plater()->export_stl_obj(false, true); }, "", nullptr,
        []() {
            const Selection& selection = plater()->canvas3D()->get_selection();
            return selection.is_single_full_instance() || selection.is_single_full_object() || selection.is_single_volume() || selection.is_single_modifier();
        }, m_parent);
    menu->AppendSeparator();
}
References _L, append_menu_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::Plater::export_stl_obj(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_modifier(), Slic3r::GUI::Selection::is_single_volume(), and Slic3r::GUI::plater().
append_menu_item_fix_through_netfabb()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_fix_through_netfabb (wxMenu * menu) private
{
    if (!is_windows10())
        return nullptr;
    wxMenuItem* menu_item = append_menu_item(menu, wxID_ANY, _L("Fix through the Netfabb"), "",
        [](wxCommandEvent&) { obj_list()->fix_through_netfabb(); }, "", menu,
        []() {return plater()->can_fix_through_netfabb(); }, m_parent);
    return menu_item;
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_fix_through_netfabb(), Slic3r::GUI::ObjectList::fix_through_netfabb(), Slic3r::is_windows10(), Slic3r::GUI::obj_list(), and Slic3r::GUI::plater().
append_menu_item_instance_to_object()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_instance_to_object (wxMenu * menu) private
{
    wxMenuItem* menu_item = append_menu_item(menu, wxID_ANY, _L("Set as a Separated Object"), "",
        [](wxCommandEvent&) { obj_list()->split_instances(); }, "", menu);
    /* New behavior logic:
     * 1. Split Object to several separated object, if ALL instances are selected
     * 2. Separate selected instances from the initial object to the separated object,
     *    if some (not all) instances are selected
     */
    m_parent->Bind(wxEVT_UPDATE_UI, [](wxUpdateUIEvent& evt)
        {
            const Selection& selection = plater()->canvas3D()->get_selection();
            evt.SetText(selection.is_single_full_object() ?
                _L("Set as a Separated Objects") : _L("Set as a Separated Object"));
            evt.Enable(plater()->can_set_instance_to_object());
        }, menu_item->GetId());
    return menu_item;
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_set_instance_to_object(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::obj_list(), Slic3r::GUI::plater(), and Slic3r::GUI::ObjectList::split_instances().
append_menu_item_invalidate_cut_info()
void Slic3r::GUI::MenuFactory::append_menu_item_invalidate_cut_info (wxMenu * menu) private
{
    const wxString menu_name = _L("Invalidate cut info");
    auto menu_item_id = menu->FindItem(menu_name);
    if (menu_item_id != wxNOT_FOUND)
        // Delete old menu item if selected object isn't cut
        menu->Destroy(menu_item_id);
    if (obj_list()->has_selected_cut_object())
        append_menu_item(menu, wxID_ANY, menu_name, "",
            [](wxCommandEvent&) { obj_list()->invalidate_cut_info_for_selection(); }, "", menu,
            []() { return true; }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::invalidate_cut_info_for_selection(), and Slic3r::GUI::obj_list().
append_menu_item_layers_editing()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_layers_editing (wxMenu * menu) private
{
    return append_menu_item(menu, wxID_ANY, _L("Height range Modifier"), "",
        [](wxCommandEvent&) { obj_list()->layers_editing(); }, "edit_layers_all", menu,
        []() { return obj_list()->is_instance_or_object_selected(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::is_instance_or_object_selected(), Slic3r::GUI::ObjectList::layers_editing(), and Slic3r::GUI::obj_list().
append_menu_item_merge_to_multipart_object()
void Slic3r::GUI::MenuFactory::append_menu_item_merge_to_multipart_object (wxMenu * menu) private
{
    menu->AppendSeparator();
    append_menu_item(menu, wxID_ANY, _L("Merge"), _L("Merge objects to the one multipart object"),
        [](wxCommandEvent&) { obj_list()->merge(true); }, "", menu,
        []() { return obj_list()->can_merge_to_multipart_object(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::can_merge_to_multipart_object(), Slic3r::GUI::ObjectList::merge(), and Slic3r::GUI::obj_list().
append_menu_item_printable()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_printable (wxMenu * menu) private
{
    wxMenuItem* menu_item_printable = append_menu_check_item(menu, wxID_ANY, _L("Printable"), "",
        [](wxCommandEvent& ) { obj_list()->toggle_printable_state(); }, menu);
    m_parent->Bind(wxEVT_UPDATE_UI, [](wxUpdateUIEvent& evt) {
        ObjectList* list = obj_list();
        wxDataViewItemArray sels;
        list->GetSelections(sels);
        wxDataViewItem frst_item = sels[0];
        ItemType type = list->GetModel()->GetItemType(frst_item);
        bool check;
        if (type != itInstance && type != itObject)
            check = false;
        else {
            int obj_idx = list->GetModel()->GetObjectIdByItem(frst_item);
            int inst_idx = type == itObject ? 0 : list->GetModel()->GetInstanceIdByItem(frst_item);
            check = list->object(obj_idx)->instances[inst_idx]->printable;
        }
        evt.Check(check);
        // disable the menu item if SLA supports or Hollow gizmos are active
        if (printer_technology() == ptSLA) {
            const auto gizmo_type = plater()->canvas3D()->get_gizmos_manager().get_current_type();
            const bool enable = gizmo_type != GLGizmosManager::SlaSupports && gizmo_type != GLGizmosManager::Hollow;
            evt.Enable(enable);
        }
        plater()->set_current_canvas_as_dirty();
    }, menu_item_printable->GetId());
    return menu_item_printable;
}
References _L, append_menu_check_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLGizmosManager::get_current_type(), Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::ObjectDataViewModel::GetInstanceIdByItem(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectList::GetModel(), Slic3r::GUI::ObjectDataViewModel::GetObjectIdByItem(), Slic3r::ModelObject::instances, Slic3r::GUI::itInstance, Slic3r::GUI::itObject, Slic3r::GUI::obj_list(), Slic3r::GUI::ObjectList::object(), Slic3r::GUI::plater(), Slic3r::printer_technology(), Slic3r::ptSLA, Slic3r::GUI::Plater::set_current_canvas_as_dirty(), and Slic3r::GUI::ObjectList::toggle_printable_state().
append_menu_item_reload_from_disk()
void Slic3r::GUI::MenuFactory::append_menu_item_reload_from_disk (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Reload from disk"), _L("Reload the selected volumes from disk"),
        [](wxCommandEvent&) { plater()->reload_from_disk(); }, "", menu,
        []() { return plater()->can_reload_from_disk(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_reload_from_disk(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::reload_from_disk().
append_menu_item_replace_with_stl()
void Slic3r::GUI::MenuFactory::append_menu_item_replace_with_stl (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Replace with STL"), _L("Replace the selected volume with new STL"),
        [](wxCommandEvent&) { plater()->replace_with_stl(); }, "", menu,
        []() { return plater()->can_replace_with_stl(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_replace_with_stl(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::replace_with_stl().
append_menu_item_scale_selection_to_fit_print_volume()
void Slic3r::GUI::MenuFactory::append_menu_item_scale_selection_to_fit_print_volume (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Scale to print volume"), _L("Scale the selected object to fit the print volume"),
        [](wxCommandEvent&) { plater()->scale_selection_to_fit_print_volume(); }, "", menu,
        []() { return plater()->can_scale_to_print_volume(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_scale_to_print_volume(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::scale_selection_to_fit_print_volume().
append_menu_item_settings()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_settings (wxMenu * menu) private
{
    MenuWithSeparators* menu = dynamic_cast<MenuWithSeparators*>(menu_);
    const wxString menu_name = _L("Add settings");
    // Delete old items from settings popupmenu
    auto settings_id = menu->FindItem(menu_name);
    if (settings_id != wxNOT_FOUND)
        menu->Destroy(settings_id);
    for (auto& it : FREQ_SETTINGS_BUNDLE_FFF)
    {
        settings_id = menu->FindItem(_(it.first));
        if (settings_id != wxNOT_FOUND)
            menu->Destroy(settings_id);
    }
    for (auto& it : FREQ_SETTINGS_BUNDLE_SLA)
    {
        settings_id = menu->FindItem(_(it.first));
        if (settings_id != wxNOT_FOUND)
            menu->Destroy(settings_id);
    }
#if 0
    for (auto& it : m_freq_settings_fff)
    {
        settings_id = menu->FindItem(format_wxstr(_L("Quick Add Settings (%s)"), _(it.first)));
        if (settings_id != wxNOT_FOUND)
            menu->Destroy(settings_id);
    }
    for (auto& it : m_freq_settings_sla)
    {
        settings_id = menu->FindItem(format_wxstr(_L("Quick Add Settings (%s)"), _(it.first)));
        if (settings_id != wxNOT_FOUND)
            menu->Destroy(settings_id);
    }
#endif
    menu->DestroySeparators(); // delete old separators
    // If there are selected more then one instance but not all of them
    // don't add settings menu items
    const Selection& selection = get_selection();
    if ((selection.is_multiple_full_instance() && !selection.is_single_full_object()) || (printer_technology() == ptSLA && selection.is_single_volume()) ||
        selection.is_multiple_volume() || selection.is_mixed()) // more than one volume(part) is selected on the scene
        return nullptr;
    const auto sel_vol = obj_list()->get_selected_model_volume();
    if (sel_vol && sel_vol->type() != ModelVolumeType::MODEL_PART && sel_vol->type() != ModelVolumeType::PARAMETER_MODIFIER )
        return nullptr;
    const ConfigOptionMode mode = wxGetApp().get_mode();
    if (mode == comSimple)
        return nullptr;
    // Create new items for settings popupmenu
    if (printer_technology() == ptFFF ||
        (menu->GetMenuItems().size() > 0 && !menu->GetMenuItems().back()->IsSeparator()))
        menu->SetFirstSeparator();
    // detect itemm for adding of the setting
    ObjectList* object_list = obj_list();
    ObjectDataViewModel* obj_model = list_model();
    const wxDataViewItem sel_item = // when all instances in object are selected
                                    object_list->GetSelectedItemsCount() > 1 && selection.is_single_full_object() ?
                                    obj_model->GetItemById(selection.get_object_idx()) :
                                    object_list->GetSelection();
    if (!sel_item)
        return nullptr;
    // If we try to add settings for object/part from 3Dscene,
    // for the second try there is selected ItemSettings in ObjectList.
    // So, check if selected item isn't SettingsItem. And get a SettingsItem's parent item, if yes
    wxDataViewItem item = obj_model->GetItemType(sel_item) & itSettings ? obj_model->GetParent(sel_item) : sel_item;
    const ItemType item_type = obj_model->GetItemType(item);
    const bool is_object_settings = !(item_type& itVolume || item_type & itLayer);
    // Add frequently settings
    create_freq_settings_popupmenu(menu, is_object_settings, item);
    if (mode == comAdvanced)
        return nullptr;
    menu->SetSecondSeparator();
    // Add full settings list
    auto  menu_item = new wxMenuItem(menu, wxID_ANY, menu_name);
    menu_item->SetBitmap(*get_bmp_bundle("cog"));
    menu_item->SetSubMenu(create_settings_popupmenu(menu, is_object_settings, item));
    return menu->Append(menu_item);
}
References _, _L, Slic3r::comAdvanced, Slic3r::comSimple, Slic3r::GUI::create_freq_settings_popupmenu(), Slic3r::GUI::create_settings_popupmenu(), MenuWithSeparators::DestroySeparators(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::FREQ_SETTINGS_BUNDLE_FFF, Slic3r::GUI::FREQ_SETTINGS_BUNDLE_SLA, get_bmp_bundle(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::ObjectList::get_selected_model_volume(), Slic3r::GUI::get_selection(), Slic3r::GUI::ObjectDataViewModel::GetItemById(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectDataViewModel::GetParent(), Slic3r::GUI::Selection::is_mixed(), Slic3r::GUI::Selection::is_multiple_full_instance(), Slic3r::GUI::Selection::is_multiple_volume(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_volume(), Slic3r::GUI::itLayer, Slic3r::GUI::itSettings, Slic3r::GUI::itVolume, Slic3r::GUI::list_model(), Slic3r::GUI::obj_list(), Slic3r::printer_technology(), Slic3r::ptFFF, Slic3r::ptSLA, MenuWithSeparators::SetFirstSeparator(), and MenuWithSeparators::SetSecondSeparator().
append_menu_item_simplify()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_simplify (wxMenu * menu) private
{
    wxMenuItem* menu_item = append_menu_item(menu, wxID_ANY, _L("Simplify model"), "",
        [](wxCommandEvent&) { obj_list()->simplify(); }, "", menu,
        []() {return plater()->can_simplify(); }, m_parent);
    menu->AppendSeparator();
    return menu_item;
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_simplify(), Slic3r::GUI::obj_list(), Slic3r::GUI::plater(), and Slic3r::GUI::ObjectList::simplify().
append_menu_items_add_volume()
void Slic3r::GUI::MenuFactory::append_menu_items_add_volume (MenuType type) private
{
    wxMenu* menu = menu_type == mtObjectFFF ? &m_object_menu : menu_type == mtObjectSLA ? &m_sla_object_menu : nullptr;
    if (!menu)
        return;
    // Update "add" items(delete old & create new) items popupmenu
    for (auto& item : ADD_VOLUME_MENU_ITEMS) {
        const wxString item_name = _(item.first);
        int item_id = menu->FindItem(item_name);
        if (item_id != wxNOT_FOUND)
            menu->Destroy(item_id);
        item_id = menu->FindItem(item_name + ": " + _L("Text"));
        if (item_id != wxNOT_FOUND)
            menu->Destroy(item_id);
    }
    // Update "Height range Modifier" item (delete old & create new)
    if (const auto range_id = menu->FindItem(_L("Height range Modifier")); range_id != wxNOT_FOUND)
        menu->Destroy(range_id);
    if (const auto range_id = menu->FindItem(_L("Height range Modifier")); range_id != wxNOT_FOUND)
        menu->Destroy(range_id);
    if (wxGetApp().get_mode() == comSimple) {
        //append_menu_item_add_text(menu, ModelVolumeType::MODEL_PART, false);
        //append_menu_item_add_text(menu, ModelVolumeType::NEGATIVE_VOLUME, false);
        append_menu_item(menu, wxID_ANY, _(ADD_VOLUME_MENU_ITEMS[int(ModelVolumeType::SUPPORT_ENFORCER)].first), "",
            [](wxCommandEvent&) { obj_list()->load_generic_subobject(L("Box"), ModelVolumeType::SUPPORT_ENFORCER); },
            ADD_VOLUME_MENU_ITEMS[int(ModelVolumeType::SUPPORT_ENFORCER)].second, nullptr,
            []() { return obj_list()->is_instance_or_object_selected(); }, m_parent);
        append_menu_item(menu, wxID_ANY, _(ADD_VOLUME_MENU_ITEMS[int(ModelVolumeType::SUPPORT_BLOCKER)].first), "",
            [](wxCommandEvent&) { obj_list()->load_generic_subobject(L("Box"), ModelVolumeType::SUPPORT_BLOCKER); },
            ADD_VOLUME_MENU_ITEMS[int(ModelVolumeType::SUPPORT_BLOCKER)].second, nullptr,
            []() { return obj_list()->is_instance_or_object_selected(); }, m_parent);
        return;
    }
    for (size_t type = 0; type < ADD_VOLUME_MENU_ITEMS.size(); type++) {
        auto& item = ADD_VOLUME_MENU_ITEMS[type];
        if (menu_type == mtObjectSLA && ModelVolumeType(type) == ModelVolumeType::PARAMETER_MODIFIER)
            continue;
        wxMenu* sub_menu = append_submenu_add_generic(menu, ModelVolumeType(type));
        append_submenu(menu, sub_menu, wxID_ANY, _(item.first), "", item.second,
            [type]() {
                bool can_add = type < size_t(ModelVolumeType::PARAMETER_MODIFIER) ? !obj_list()->is_selected_object_cut() : true;
                return can_add && obj_list()->is_instance_or_object_selected();
            }, m_parent);
    }
    if (menu_type == mtObjectFFF)
        append_menu_item_layers_editing(menu);
}
References _, _L, Slic3r::GUI::ADD_VOLUME_MENU_ITEMS, append_menu_item(), append_submenu(), Slic3r::comSimple, Slic3r::GUI::ObjectList::is_instance_or_object_selected(), L, Slic3r::GUI::ObjectList::load_generic_subobject(), and Slic3r::GUI::obj_list().
append_menu_items_convert_unit()
void Slic3r::GUI::MenuFactory::append_menu_items_convert_unit (wxMenu * menu, int insert_pos = 1) private
{
    std::vector<int> obj_idxs, vol_idxs;
    obj_list()->get_selection_indexes(obj_idxs, vol_idxs);
    if (obj_idxs.empty() && vol_idxs.empty())
        return;
    auto volume_respects_conversion = [](ModelVolume* volume, ConversionType conver_type)
    {
        return  (conver_type == ConversionType::CONV_FROM_INCH && volume->source.is_converted_from_inches) ||
            (conver_type == ConversionType::CONV_TO_INCH && !volume->source.is_converted_from_inches) ||
            (conver_type == ConversionType::CONV_FROM_METER && volume->source.is_converted_from_meters) ||
            (conver_type == ConversionType::CONV_TO_METER && !volume->source.is_converted_from_meters);
    };
    auto can_append = [obj_idxs, vol_idxs, volume_respects_conversion](ConversionType conver_type)
    {
        ModelObjectPtrs objects;
        for (int obj_idx : obj_idxs) {
            ModelObject* object = obj_list()->object(obj_idx);
            if (object->is_cut())
                return false;
            if (vol_idxs.empty()) {
                for (ModelVolume* volume : object->volumes)
                    if (volume_respects_conversion(volume, conver_type))
                        return false;
            }
            else {
                for (int vol_idx : vol_idxs)
                    if (volume_respects_conversion(object->volumes[vol_idx], conver_type))
                        return false;
            }
        }
        return true;
    };
    std::vector<std::pair<ConversionType, wxString>> items = {
        {ConversionType::CONV_FROM_INCH , _L("Convert from imperial units") },
        {ConversionType::CONV_TO_INCH   , _L("Revert conversion from imperial units") },
        {ConversionType::CONV_FROM_METER, _L("Convert from meters") },
        {ConversionType::CONV_TO_METER  , _L("Revert conversion from meters") } };
    for (auto item : items) {
        int menu_id = menu->FindItem(item.second);
        if (can_append(item.first)) {
            // Add menu item if it doesn't exist
            if (menu_id == wxNOT_FOUND)
                append_menu_item(menu, wxID_ANY, item.second, item.second,
                    [item](wxCommandEvent&) { plater()->convert_unit(item.first); }, "", menu,
                    []() { return true; }, m_parent, insert_pos);
        }
        else if (menu_id != wxNOT_FOUND) {
            // Delete menu item
            menu->Destroy(menu_id);
        }
    }
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::get_selection_indexes(), Slic3r::ModelObject::is_cut(), Slic3r::GUI::obj_list(), Slic3r::GUI::ObjectList::object(), and Slic3r::ModelObject::volumes.
append_menu_items_instance_manipulation()
void Slic3r::GUI::MenuFactory::append_menu_items_instance_manipulation (wxMenu * menu) private
{
    MenuType type = menu == &m_object_menu ? mtObjectFFF : mtObjectSLA;
    items_increase[type]                = append_menu_item(menu, wxID_ANY, _L("Add instance") + "\t+", _L("Add one more instance of the selected object"),
        [](wxCommandEvent&) { plater()->increase_instances();      }, "add_copies", nullptr,
        []() { return plater()->can_increase_instances(); }, m_parent);
    items_decrease[type]                = append_menu_item(menu, wxID_ANY, _L("Remove instance") + "\t-", _L("Remove one instance of the selected object"),
        [](wxCommandEvent&) { plater()->decrease_instances();      }, "remove_copies", nullptr,
        []() { return plater()->can_decrease_instances(); }, m_parent);
    items_set_number_of_copies[type]    = append_menu_item(menu, wxID_ANY, _L("Set number of instances") + dots, _L("Change the number of instances of the selected object"),
        [](wxCommandEvent&) { plater()->set_number_of_copies();    }, "number_of_copies", nullptr,
        []() { return plater()->can_increase_instances(); }, m_parent);
    append_menu_item(menu, wxID_ANY, _L("Fill bed with instances") + dots, _L("Fill the remaining area of bed with instances of the selected object"),
        [](wxCommandEvent&) { plater()->fill_bed_with_instances();    }, "", nullptr,
        []() { return plater()->can_increase_instances(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_decrease_instances(), Slic3r::GUI::Plater::can_increase_instances(), Slic3r::GUI::Plater::decrease_instances(), Slic3r::GUI::Plater::fill_bed_with_instances(), Slic3r::GUI::Plater::increase_instances(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::set_number_of_copies().
append_menu_items_mirror()
void Slic3r::GUI::MenuFactory::append_menu_items_mirror (wxMenu * menu) private
{
    wxMenu* mirror_menu = new wxMenu();
    if (!mirror_menu)
        return;
    append_menu_item(mirror_menu, wxID_ANY, _L("Along X axis"), _L("Mirror the selected object along the X axis"),
        [](wxCommandEvent&) { plater()->mirror(X); }, "mark_X", menu);
    append_menu_item(mirror_menu, wxID_ANY, _L("Along Y axis"), _L("Mirror the selected object along the Y axis"),
        [](wxCommandEvent&) { plater()->mirror(Y); }, "mark_Y", menu);
    append_menu_item(mirror_menu, wxID_ANY, _L("Along Z axis"), _L("Mirror the selected object along the Z axis"),
        [](wxCommandEvent&) { plater()->mirror(Z); }, "mark_Z", menu);
    append_submenu(menu, mirror_menu, wxID_ANY, _L("Mirror"), _L("Mirror the selected object"), "",
        []() { return plater()->can_mirror(); }, m_parent);
}
References _L, append_menu_item(), append_submenu(), Slic3r::GUI::Plater::can_mirror(), Slic3r::GUI::Plater::mirror(), Slic3r::GUI::plater(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
append_menu_items_osx()
void Slic3r::GUI::MenuFactory::append_menu_items_osx (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Rename"), "",
        [](wxCommandEvent&) { obj_list()->rename_item(); }, "", menu);
    menu->AppendSeparator();
}
References _L, append_menu_item(), Slic3r::GUI::obj_list(), and Slic3r::GUI::ObjectList::rename_item().
append_menu_items_split()
void Slic3r::GUI::MenuFactory::append_menu_items_split (wxMenu * menu) private
{
    wxMenu* split_menu = new wxMenu();
    if (!split_menu)
        return;
    append_menu_item(split_menu, wxID_ANY, _L("To objects"), _L("Split the selected object into individual objects"),
        [](wxCommandEvent&) { plater()->split_object(); }, "split_object_SMALL", menu,
        []() { return plater()->can_split(true); }, m_parent);
    append_menu_item(split_menu, wxID_ANY, _L("To parts"), _L("Split the selected object into individual parts"),
        [](wxCommandEvent&) { plater()->split_volume(); }, "split_parts_SMALL", menu,
        []() { return plater()->can_split(false); }, m_parent);
    append_submenu(menu, split_menu, wxID_ANY, _L("Split"), _L("Split the selected object"), "",
        []() { return plater()->can_split(true); }, m_parent);
}
References _L, append_menu_item(), append_submenu(), Slic3r::GUI::Plater::can_split(), Slic3r::GUI::plater(), Slic3r::GUI::Plater::split_object(), and Slic3r::GUI::Plater::split_volume().
append_mutable_part_menu_items()
void Slic3r::GUI::MenuFactory::append_mutable_part_menu_items (wxMenu * menu) private
{
    append_menu_item_settings(menu);
    append_menu_item_change_extruder(menu);
}
append_submenu_add_generic()
wxMenu * Slic3r::GUI::MenuFactory::append_submenu_add_generic (wxMenu * menu, ModelVolumeType type) private
{
    auto sub_menu = new wxMenu;
    const ConfigOptionMode mode = wxGetApp().get_mode();
    if (type != ModelVolumeType::INVALID && mode > comSimple) {
        append_menu_item(sub_menu, wxID_ANY, _L("Load") + " " + dots, "",
            [type](wxCommandEvent&) { obj_list()->load_subobject(type); }, "", menu);
        sub_menu->AppendSeparator();
    }
    //if (!(type == ModelVolumeType::MODEL_PART && mode == comAdvanced))
        for (auto& item : { L("Box"), L("Cylinder"), L("Sphere"), L("Slab") })
        {
            if (type == ModelVolumeType::INVALID && strncmp(item, "Slab", 4) == 0)
                continue;
            append_menu_item(sub_menu, wxID_ANY, _(item), "",
                [type, item](wxCommandEvent&) { obj_list()->load_generic_subobject(item, type); }, "", menu);
        }
    append_menu_item_add_text(sub_menu, type);
    if (mode >= comAdvanced) {
        sub_menu->AppendSeparator();
        append_menu_item(sub_menu, wxID_ANY, _L("Gallery"), "",
            [type](wxCommandEvent&) { obj_list()->load_subobject(type, true); }, "", menu);
    }
    return sub_menu;
}
References _, _L, append_menu_item(), Slic3r::comAdvanced, Slic3r::comSimple, L, Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_subobject(), and Slic3r::GUI::obj_list().
create_common_object_menu()
void Slic3r::GUI::MenuFactory::create_common_object_menu (wxMenu * menu) private
{
#ifdef __WXOSX__
    append_menu_items_osx(menu);
#endif // __WXOSX__
    append_menu_items_instance_manipulation(menu);
    // Delete menu was moved to be after +/- instace to make it more difficult to be selected by mistake.
    append_menu_item_delete(menu);
    append_menu_item_instance_to_object(menu);
    menu->AppendSeparator();
    append_menu_item_printable(menu);
    menu->AppendSeparator();
    append_menu_item_reload_from_disk(menu);
    append_menu_item_replace_with_stl(menu);
    append_menu_item_export_stl(menu);
    // "Scale to print volume" makes a sense just for whole object
    append_menu_item_scale_selection_to_fit_print_volume(menu);
    append_menu_item_fix_through_netfabb(menu);
    append_menu_item_simplify(menu);
    append_menu_items_mirror(menu);
    append_menu_items_split(menu);
    menu->AppendSeparator();
}
create_default_menu()
void Slic3r::GUI::MenuFactory::create_default_menu () private
{
    wxMenu* sub_menu = append_submenu_add_generic(&m_default_menu, ModelVolumeType::INVALID);
    append_submenu(&m_default_menu, sub_menu, wxID_ANY, _L("Add Shape"), "", "add_part",
        []() {return true; }, m_parent);
}
References _L, and append_submenu().
create_instance_menu()
void Slic3r::GUI::MenuFactory::create_instance_menu () private
{
    wxMenu* menu = &m_instance_menu;
    // create "Instance to Object" menu item
    append_menu_item_instance_to_object(menu);
    append_menu_item_printable(menu);
}
create_part_menu()
void Slic3r::GUI::MenuFactory::create_part_menu () private
{
    wxMenu* menu = &m_part_menu;
#ifdef __WXOSX__
    append_menu_items_osx(menu);
#endif // __WXOSX__
    append_menu_item_delete(menu);
    append_menu_item_reload_from_disk(menu);
    append_menu_item_replace_with_stl(menu);
    append_menu_item_export_stl(menu);
    append_menu_item_fix_through_netfabb(menu);
    append_menu_item_simplify(menu);
    append_menu_item(menu, wxID_ANY, _L("Split"), _L("Split the selected object into individual parts"),
        [](wxCommandEvent&) { plater()->split_volume(); }, "split_parts_SMALL", nullptr,
        []() { return plater()->can_split(false); }, m_parent);
    append_immutable_part_menu_items(menu);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_split(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::split_volume().
create_text_part_menu()
void Slic3r::GUI::MenuFactory::create_text_part_menu () private
{
    wxMenu* menu = &m_text_part_menu;
    append_menu_item_delete(menu);
    append_menu_item_edit_text(menu);
    append_menu_item_fix_through_netfabb(menu);
    append_menu_item_simplify(menu);
    append_immutable_part_menu_items(menu);
}
default_menu()
wxMenu * Slic3r::GUI::MenuFactory::default_menu ()
{
    return &m_default_menu;
}
get_text_volume_bitmaps()
std::vector< wxBitmapBundle * > Slic3r::GUI::MenuFactory::get_text_volume_bitmaps () static
{
    std::vector<wxBitmapBundle*> volume_bmps;
    volume_bmps.reserve(TEXT_VOLUME_ICONS.size());
    for (auto item : TEXT_VOLUME_ICONS)
        volume_bmps.push_back(get_bmp_bundle(item.second));
    return volume_bmps;
}
References get_bmp_bundle(), and Slic3r::GUI::TEXT_VOLUME_ICONS.
Referenced by Slic3r::GUI::ObjectDataViewModel::ObjectDataViewModel(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmaps().
get_volume_bitmaps()
std::vector< wxBitmapBundle * > Slic3r::GUI::MenuFactory::get_volume_bitmaps () static
{
    std::vector<wxBitmapBundle*> volume_bmps;
    volume_bmps.reserve(ADD_VOLUME_MENU_ITEMS.size());
    for (auto item : ADD_VOLUME_MENU_ITEMS)
        volume_bmps.push_back(get_bmp_bundle(item.second));
    return volume_bmps;
}
References Slic3r::GUI::ADD_VOLUME_MENU_ITEMS, and get_bmp_bundle().
Referenced by Slic3r::GUI::ObjectDataViewModel::ObjectDataViewModel(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmaps().
init()
void Slic3r::GUI::MenuFactory::init (wxWindow * parent)
{
    m_parent = parent;
    create_default_menu();
    create_common_object_menu(&m_object_menu);
    create_common_object_menu(&m_sla_object_menu);
    create_part_menu();
    create_text_part_menu();
    create_instance_menu();
}
instance_menu()
wxMenu * Slic3r::GUI::MenuFactory::instance_menu ()
{
    return &m_instance_menu;
}
layer_menu()
wxMenu * Slic3r::GUI::MenuFactory::layer_menu ()
{
    MenuWithSeparators* menu = new MenuWithSeparators();
    append_menu_item_settings(menu);
    return menu;
}
multi_selection_menu()
wxMenu * Slic3r::GUI::MenuFactory::multi_selection_menu ()
{
    wxDataViewItemArray sels;
    obj_list()->GetSelections(sels);
    if (sels.IsEmpty())
        return nullptr;
    for (const wxDataViewItem& item : sels)
        if (!(list_model()->GetItemType(item) & (itVolume | itObject | itInstance)))
            // show this menu only for Objects(Instances mixed with Objects)/Volumes selection
            return nullptr;
    wxMenu* menu = new MenuWithSeparators();
    append_menu_item_fix_through_netfabb(menu);
    append_menu_item_reload_from_disk(menu);
    append_menu_items_convert_unit(menu);
    if (obj_list()->can_merge_to_multipart_object())
        append_menu_item_merge_to_multipart_object(menu);
    if (extruders_count() > 1)
        append_menu_item_change_extruder(menu);
    if (list_model()->GetItemType(sels[0]) != itVolume) {
        append_menu_item_printable(menu);
        if (wxGetApp().get_mode() != comSimple)
            append_menu_item(menu, wxID_ANY, _L("Set number of instances") + dots, _L("Change the number of instances of the selected objects"),
            [](wxCommandEvent&) { plater()->set_number_of_copies();    }, "number_of_copies", nullptr,
            []() { return plater()->can_increase_instances(); }, m_parent);
    }
    return menu;
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_increase_instances(), Slic3r::comSimple, Slic3r::GUI::extruders_count(), Slic3r::GUI::itInstance, Slic3r::GUI::itObject, Slic3r::GUI::itVolume, Slic3r::GUI::list_model(), Slic3r::GUI::obj_list(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::set_number_of_copies().
object_menu()
wxMenu * Slic3r::GUI::MenuFactory::object_menu ()
{
    append_menu_items_convert_unit(&m_object_menu, 11);
    append_menu_item_settings(&m_object_menu);
    append_menu_item_change_extruder(&m_object_menu);
    update_menu_items_instance_manipulation(mtObjectFFF);
    append_menu_item_invalidate_cut_info(&m_object_menu);
    append_menu_item_edit_text(&m_object_menu);
    return &m_object_menu;
}
part_menu()
wxMenu * Slic3r::GUI::MenuFactory::part_menu ()
{
    append_menu_items_convert_unit(&m_part_menu, 2);
    append_mutable_part_menu_items(&m_part_menu);
    return &m_part_menu;
}
sla_object_menu()
wxMenu * Slic3r::GUI::MenuFactory::sla_object_menu ()
{
    append_menu_items_convert_unit(&m_sla_object_menu, 11);
    append_menu_item_settings(&m_sla_object_menu);
    update_menu_items_instance_manipulation(mtObjectSLA);
    append_menu_item_invalidate_cut_info(&m_sla_object_menu);
    append_menu_item_edit_text(&m_sla_object_menu);
    return &m_sla_object_menu;
}
sys_color_changed() [1/2]
void Slic3r::GUI::MenuFactory::sys_color_changed ()
{
    for (MenuWithSeparators* menu : { &m_object_menu, &m_sla_object_menu, &m_part_menu, &m_default_menu }) {
        sys_color_changed_menu(dynamic_cast<wxMenu*>(menu));// msw_rescale_menu updates just icons, so use it
#ifdef _WIN32
        // but under MSW we have to update item's bachground color
        for (wxMenuItem* item : menu->GetMenuItems())
            update_menu_item_def_colors(item);
#endif
    }
}
References sys_color_changed_menu().
Referenced by Slic3r::GUI::MainFrame::on_sys_color_changed().
sys_color_changed() [2/2]
void Slic3r::GUI::MenuFactory::sys_color_changed (wxMenuBar * menu_bar) static
{
    for (size_t id = 0; id < menubar->GetMenuCount(); id++) {
        wxMenu* menu = menubar->GetMenu(id);
        sys_color_changed_menu(menu);
#ifndef __linux__
        menu->SetupBitmaps();
#ifdef _WIN32
        // but under MSW we have to update item's bachground color
        for (wxMenuItem* item : menu->GetMenuItems())
            update_menu_item_def_colors(item);
#endif
#endif
    }
//    menubar->Refresh();
}
References sys_color_changed_menu().
text_part_menu()
wxMenu * Slic3r::GUI::MenuFactory::text_part_menu ()
{
    append_mutable_part_menu_items(&m_text_part_menu);
    return &m_text_part_menu;
}
update()
void Slic3r::GUI::MenuFactory::update ()
{
    update_default_menu();
    update_objects_menu();
}
update_default_menu()
void Slic3r::GUI::MenuFactory::update_default_menu ()
{
    const auto menu_item_id = m_default_menu.FindItem(_("Add Shape"));
    if (menu_item_id != wxNOT_FOUND)
        m_default_menu.Destroy(menu_item_id);
    create_default_menu();
}
References _.
update_menu_items_instance_manipulation()
void Slic3r::GUI::MenuFactory::update_menu_items_instance_manipulation (MenuType type) private
{
    wxMenu* menu = type == mtObjectFFF ? &m_object_menu : type == mtObjectSLA ? &m_sla_object_menu : nullptr;
    if (menu)
        return;
    // Remove/Prepend "increase/decrease instances" menu items according to the view mode.
    // Suppress to show those items for a Simple mode
    if (wxGetApp().get_mode() == comSimple) {
        if (menu->FindItem(_L("Add instance")) != wxNOT_FOUND)
        {
            // Detach an items from the menu, but don't delete them
            // so that they can be added back later
            // (after switching to the Advanced/Expert mode)
            menu->Remove(items_increase[type]);
            menu->Remove(items_decrease[type]);
            menu->Remove(items_set_number_of_copies[type]);
        }
    }
    else {
        if (menu->FindItem(_L("Add instance")) == wxNOT_FOUND)
        {
            // Prepend items to the menu, if those aren't not there
            menu->Prepend(items_set_number_of_copies[type]);
            menu->Prepend(items_decrease[type]);
            menu->Prepend(items_increase[type]);
        }
    }
}
References _L, and Slic3r::comSimple.
update_objects_menu()
void Slic3r::GUI::MenuFactory::update_objects_menu ()
{
    append_menu_items_add_volume(mtObjectFFF);
    append_menu_items_add_volume(mtObjectSLA);
}
Member Data Documentation
items_decrease
std::array<wxMenuItem*, mtCount> Slic3r::GUI::MenuFactory::items_decrease private
items_increase
std::array<wxMenuItem*, mtCount> Slic3r::GUI::MenuFactory::items_increase private
items_set_number_of_copies
std::array<wxMenuItem*, mtCount> Slic3r::GUI::MenuFactory::items_set_number_of_copies private
m_default_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_default_menu private
m_instance_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_instance_menu private
m_object_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_object_menu private
m_parent
wxWindow* Slic3r::GUI::MenuFactory::m_parent {nullptr} private
m_part_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_part_menu private
m_sla_object_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_sla_object_menu private
m_text_part_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_text_part_menu private
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_Factories.hpp
src/slic3r/GUI/GUI_Factories.cpp