Prusa Slicer: Slic3r::GUI::ClippingPlane Class Reference
Slic3r::GUI::ClippingPlane Class Reference
#include <src/slic3r/GUI/MeshUtils.hpp>
Public Member Functions
ClippingPlane ()
ClippingPlane (const Vec3d &direction, double offset)
bool operator== (const ClippingPlane &cp) const
bool operator!= (const ClippingPlane &cp) const
double distance (const Vec3d &pt) const
bool is_point_clipped (const Vec3d &point) const
void set_normal (const Vec3d &normal)
void set_offset (double offset)
double get_offset () const
Vec3d get_normal () const
void invert_normal ()
ClippingPlane inverted_normal () const
bool is_active () const
const std::array< double, 4 > & get_data () const
template<class Archive >
void serialize (Archive &ar)
Static Public Member Functions
static ClippingPlane ClipsNothing ()
Private Attributes
std::array< double, 4 > m_data
Detailed Description
Constructor & Destructor Documentation
ClippingPlane() [1/2]
Slic3r::GUI::ClippingPlane::ClippingPlane () inline
                    {
        *this = ClipsNothing();
    }
References ClipsNothing().
Referenced by ClipsNothing(), and inverted_normal().
ClippingPlane() [2/2]
Slic3r::GUI::ClippingPlane::ClippingPlane (const Vec3d & direction, double offset) inline
{
        set_normal(direction);
        set_offset(offset);
    }
References Slic3r::offset(), set_normal(), and set_offset().
Member Function Documentation
ClipsNothing()
static ClippingPlane Slic3r::GUI::ClippingPlane::ClipsNothing () inline static
{ return ClippingPlane(Vec3d(0., 0., 1.), DBL_MAX); }
References ClippingPlane().
Referenced by ClippingPlane(), Slic3r::GUI::GLGizmosManager::get_clipping_plane(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), and Slic3r::GUI::GLGizmoSlaBase::render_volumes().
distance()
double Slic3r::GUI::ClippingPlane::distance (const Vec3d & pt) const inline
{
        // FIXME: this fails: assert(is_approx(get_normal().norm(), 1.));
        return (-get_normal().dot(pt) + m_data[3]);
    }
References Slic3r::dot(), get_normal(), and m_data.
Referenced by is_point_clipped(), and Slic3r::GUI::MeshClipper::recalculate_triangles().
get_data()
const std::array< double, 4 > & Slic3r::GUI::ClippingPlane::get_data () const inline
{ return m_data; }
References m_data.
Referenced by Slic3r::GUI::GLGizmosManager::get_clipping_plane(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::MeshClipper::recalculate_triangles(), and Slic3r::GUI::GLGizmoSlaBase::render_volumes().
get_normal()
Vec3d Slic3r::GUI::ClippingPlane::get_normal () const inline
{ return Vec3d(m_data[0], m_data[1], m_data[2]); }
References m_data.
Referenced by distance(), Slic3r::GUI::GLGizmosManager::get_clipping_plane(), inverted_normal(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::GLGizmoSlaBase::render_volumes(), and Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane().
get_offset()
double Slic3r::GUI::ClippingPlane::get_offset () const inline
{ return m_data[3]; }
References m_data.
Referenced by inverted_normal(), and Slic3r::GUI::GLGizmoCut3D::unproject_on_cut_plane().
invert_normal()
void Slic3r::GUI::ClippingPlane::invert_normal () inline
{ m_data[0] *= -1.0; m_data[1] *= -1.0; m_data[2] *= -1.0; }
References m_data.
inverted_normal()
ClippingPlane Slic3r::GUI::ClippingPlane::inverted_normal () const inline
{ return ClippingPlane(-get_normal(), get_offset()); }
References ClippingPlane(), get_normal(), and get_offset().
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass().
is_active()
bool Slic3r::GUI::ClippingPlane::is_active () const inline
{ return m_data[3] != DBL_MAX; }
References m_data.
is_point_clipped()
bool Slic3r::GUI::ClippingPlane::is_point_clipped (const Vec3d & point) const inline
{ return distance(point) < 0.; }
References distance().
Referenced by Slic3r::GUI::MeshRaycaster::closest_hit(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), and Slic3r::GUI::MeshRaycaster::unproject_on_mesh().
operator!=()
bool Slic3r::GUI::ClippingPlane::operator!= (const ClippingPlane & cp) const inline
{ return ! (*this==cp); }
operator==()
bool Slic3r::GUI::ClippingPlane::operator== (const ClippingPlane & cp) const inline
{
        return m_data[0]==cp.m_data[0] && m_data[1]==cp.m_data[1] && m_data[2]==cp.m_data[2] && m_data[3]==cp.m_data[3];
    }
References m_data.
serialize()
template<class Archive > void Slic3r::GUI::ClippingPlane::serialize (Archive & ar) inline
{
        ar( m_data[0], m_data[1], m_data[2], m_data[3] );
    }
References m_data.
set_normal()
void Slic3r::GUI::ClippingPlane::set_normal (const Vec3d & normal) inline
{
        const Vec3d norm_dir = normal.normalized();
        m_data[0] = norm_dir.x();
        m_data[1] = norm_dir.y();
        m_data[2] = norm_dir.z();
    }
References m_data.
Referenced by ClippingPlane(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), and Slic3r::GUI::GLGizmoSlaBase::render_volumes().
set_offset()
void Slic3r::GUI::ClippingPlane::set_offset (double offset) inline
{ m_data[3] = offset; }
References m_data, and Slic3r::offset().
Referenced by ClippingPlane(), and Slic3r::GUI::GLGizmoSlaBase::render_volumes().
Member Data Documentation
m_data
std::array<double, 4> Slic3r::GUI::ClippingPlane::m_data private
Referenced by distance(), get_data(), get_normal(), get_offset(), invert_normal(), is_active(), operator==(), serialize(), set_normal(), and set_offset().
The documentation for this class was generated from the following file:
src/slic3r/GUI/MeshUtils.hpp