Prusa Slicer: Slic3r::GUI::Mouse3DController Class Reference
Slic3r::GUI::Mouse3DController Class Reference
#include <src/slic3r/GUI/Mouse3DController.hpp>
Classes
struct Params
class State
Public Member Functions
void load_config (const AppConfig &appconfig)
void save_config (AppConfig &appconfig) const
void init ()
void shutdown ()
bool connected () const
bool apply (Camera &camera)
bool is_settings_dialog_shown () const
void show_settings_dialog (bool show)
void render_settings_dialog (GLCanvas3D &canvas) const
Private Types
typedef std::array< unsigned char, 13 > DataPacketRaw
Private Member Functions
bool connect_device ()
void disconnect_device ()
void run ()
void collect_input ()
Static Private Member Functions
static bool handle_input (const DataPacketRaw &packet, const int packet_length, const Params &params, State &state_in_out)
static bool handle_packet (const DataPacketRaw &packet, const int packet_length, const Params &params, State &state_in_out)
static bool handle_packet_translation (const DataPacketRaw &packet, const Params &params, State &state_in_out)
static bool handle_packet_rotation (const DataPacketRaw &packet, unsigned int first_byte, const Params &params, State &state_in_out)
static bool handle_packet_button (const DataPacketRaw &packet, unsigned int packet_size, const Params &params, State &state_in_out)
Private Attributes
Params m_params
Params m_params_ui
bool m_params_ui_changed { false }
std::mutex m_params_ui_mutex
std::map< std::string, Params > m_params_by_device
State m_state
std::atomic< bool > m_connected { false }
std::string m_device_str
std::thread m_thread
hid_device * m_device { nullptr }
bool m_stop { false }
std::mutex m_stop_condition_mutex
std::condition_variable m_stop_condition
bool m_show_settings_dialog { false }
bool m_settings_dialog_closed_by_user { false }
Detailed Description
Member Typedef Documentation
DataPacketRaw
typedef std::array<unsigned char, 13> Slic3r::GUI::Mouse3DController::DataPacketRaw private
Member Function Documentation
apply()
bool Slic3r::GUI::Mouse3DController::apply (Camera & camera)
{
    // check if the user unplugged the device
    if (! m_connected) {
        // hides the settings dialog if the user un-plug the device
        m_show_settings_dialog = false;
        m_settings_dialog_closed_by_user = false;
    }
#ifdef _WIN32
    {
        std::scoped_lock<std::mutex> lock(m_params_ui_mutex);
        if (m_params_ui_changed) {
            m_params = m_params_ui;
            m_params_ui_changed = false;
        }
    }
#endif // _WIN32
    return m_state.apply(m_params, camera);
}
References Slic3r::GUI::Mouse3DController::State::apply(), m_connected, m_params, m_params_ui, m_params_ui_changed, m_params_ui_mutex, m_settings_dialog_closed_by_user, m_show_settings_dialog, and m_state.
collect_input()
void Slic3r::GUI::Mouse3DController::collect_input () private
{
    DataPacketRaw packet = { 0 };
    // Read packet, block maximum 100 ms. That means when closing the application, closing the application will be delayed by 100 ms.
    int res = hid_read_timeout(m_device, packet.data(), packet.size(), 100);
    if (res < 0) {
        // An error occourred (device detached from pc ?). Close the 3Dconnexion device.
        this->disconnect_device();
    } else
    this->handle_input(packet, res, m_params, m_state);
}
References disconnect_device(), handle_input(), hid_read_timeout(), m_device, m_params, and m_state.
Referenced by run().
connect_device()
bool Slic3r::GUI::Mouse3DController::connect_device () private
{
    if (m_stop)
      return false;
    {
      // Wait for 2 seconds, but cancellable by m_stop.
      std::unique_lock<std::mutex> lock(m_stop_condition_mutex);
#ifdef _WIN32
      // Wait indifinetely for the stop signal.
        m_stop_condition.wait(lock, [this]{ return m_stop || m_wakeup; });
        m_wakeup = false;
#else
        m_stop_condition.wait_for(lock, std::chrono::seconds(2), [this]{ return m_stop; });
#endif
    }
    if (m_stop)
      return false;
    // Enumerates devices
    hid_device_info* devices = hid_enumerate(0, 0);
    if (devices == nullptr) {
        BOOST_LOG_TRIVIAL(trace) << "Mouse3DController::connect_device() - no HID device enumerated.";
        return false;
    }
#ifdef _WIN32
    BOOST_LOG_TRIVIAL(trace) << "Mouse3DController::connect_device() - enumerating HID devices.";
#endif // _WIN32
    // Searches for 1st connected 3Dconnexion device
    struct DeviceData
    {
        std::string path;
        unsigned short usage_page;
        unsigned short usage;
        DeviceData()
            : path(""), usage_page(0), usage(0)
        {}
        DeviceData(const std::string& path, unsigned short usage_page, unsigned short usage)
            : path(path), usage_page(usage_page), usage(usage)
        {}
        // https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf
        // Usage page 1 - Generic Desktop Controls
        // Usage page 1, usage 8 - Multi-axis Controller
        bool has_valid_usage() const { return usage_page == 1 && usage == 8; }
    };
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    hid_device_info* cur = devices;
    std::cout << std::endl << "======================================================================================================================================" << std::endl;
    std::cout << "Detected devices:" << std::endl;
    while (cur != nullptr) {
        std::cout << "\"";
        std::wcout << ((cur->manufacturer_string != nullptr) ? cur->manufacturer_string : L"Unknown");
        std::cout << "/";
        std::wcout << ((cur->product_string != nullptr) ? cur->product_string : L"Unknown");
        std::cout << "\" code: " << cur->vendor_id << "/" << cur->product_id << " (" << std::hex << cur->vendor_id << "/" << cur->product_id << std::dec << ")";
        std::cout << " serial number: '";
        std::wcout << ((cur->serial_number != nullptr) ? cur->serial_number : L"Unknown");
        std::cout << "' usage page: " << cur->usage_page << " usage: " << cur->usage << " interface number: " << cur->interface_number << std::endl;
        cur = cur->next;
    }
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    // When using 3Dconnexion universal receiver, multiple devices are detected sharing the same vendor_id and product_id.
    // To choose from them the right one we use:
    // On Windows and Mac: usage_page == 1 and usage == 8
    // On Linux: as usage_page and usage are not defined (see hidapi.h) we try all detected devices until one is succesfully open
    // When only a single device is detected, as for wired connections, vendor_id and product_id are enough
    // First we count all the valid devices from the enumerated list,
    hid_device_info* current = devices;
    typedef std::pair<unsigned short, unsigned short> DeviceIds;
    typedef std::vector<DeviceData> DeviceDataList;
    typedef std::map<DeviceIds, DeviceDataList> DetectedDevices;
    DetectedDevices detected_devices;
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    std::cout << std::endl << "Detected 3D connexion devices:" << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    while (current != nullptr) {
        unsigned short vendor_id = 0;
        unsigned short product_id = 0;
        for (size_t i = 0; i < _3DCONNEXION_VENDORS.size(); ++i) {
            if (_3DCONNEXION_VENDORS[i] == current->vendor_id) {
                vendor_id = current->vendor_id;
                break;
            }
        }
        if (vendor_id != 0) {
            for (size_t i = 0; i < _3DCONNEXION_DEVICES.size(); ++i) {
                if (_3DCONNEXION_DEVICES[i] == current->product_id) {
                    product_id = current->product_id;
                    DeviceIds detected_device(vendor_id, product_id);
                    DetectedDevices::iterator it = detected_devices.find(detected_device);
                    if (it == detected_devices.end())
                        it = detected_devices.insert(DetectedDevices::value_type(detected_device, DeviceDataList())).first;
                    it->second.emplace_back(current->path, current->usage_page, current->usage);
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
                    std::wcout << "\"" << ((current->manufacturer_string != nullptr) ? current->manufacturer_string : L"Unknown");
                    std::cout << "/";
                    std::wcout << ((current->product_string != nullptr) ? current->product_string : L"Unknown");
                    std::cout << "\" code: " << current->vendor_id << "/" << current->product_id << " (" << std::hex << current->vendor_id << "/" << current->product_id << std::dec << ")";
                    std::cout << " serial number: '";
                    std::wcout << ((current->serial_number != nullptr) ? current->serial_number : L"Unknown");
                    std::cout << "' usage page: " << current->usage_page << " usage: " << current->usage << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
                }
            }
        }
        current = current->next;
    }
    // Free enumerated devices
    hid_free_enumeration(devices);
    if (detected_devices.empty())
        return false;
    std::string path;
    unsigned short vendor_id = 0;
    unsigned short product_id = 0;
    // Then we'll decide the choosing logic to apply in dependence of the device count and operating system
    for (const DetectedDevices::value_type& device : detected_devices) {
        if (device.second.size() == 1) {
#if defined(__linux__)
            hid_device* test_device = hid_open(device.first.first, device.first.second, nullptr);
            if (test_device == nullptr) {
                BOOST_LOG_TRIVIAL(error) << "3DConnexion device cannot be opened: " << device.second.front().path <<
                    " You may need to update /etc/udev/rules.d";
            } else {
                hid_close(test_device);
#else
            if (device.second.front().has_valid_usage()) {
#endif // __linux__
                vendor_id = device.first.first;
                product_id = device.first.second;
                break;
            }
        }
        else {
            bool found = false;
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            std::cout << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            for (const DeviceData& data : device.second) {
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
                std::cout << "Test device: " << std::hex << device.first.first << std::dec << "/" << std::hex << device.first.second << std::dec << " \"" << data.path << "\"";
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
#ifdef __linux__
                hid_device* test_device = hid_open_path(data.path.c_str());
                if (test_device != nullptr) {
                    path = data.path;
                    vendor_id = device.first.first;
                    product_id = device.first.second;
                    found = true;
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
                    std::cout << "-> PASSED" << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
                    hid_close(test_device);
                    break;
                }
#else // !__linux__
                if (data.has_valid_usage()) {
                    path = data.path;
                    vendor_id = device.first.first;
                    product_id = device.first.second;
                    found = true;
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
                    std::cout << "-> PASSED" << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
                    break;
                }
#endif // __linux__
                else {
                    BOOST_LOG_TRIVIAL(error) << "3DConnexion device cannot be opened: " << data.path <<
                        " You may need to update /etc/udev/rules.d";
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
                    std::cout << "-> NOT PASSED" << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
                }
            }
            if (found)
                break;
        }
    }
    if (path.empty()) {
        if ((vendor_id != 0) && (product_id != 0)) {
            // Open the 3Dconnexion device using vendor_id and product_id
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            std::cout << std::endl << "Opening device: " << std::hex << vendor_id << std::dec << "/" << std::hex << product_id << std::dec << " using hid_open()" << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            m_device = hid_open(vendor_id, product_id, nullptr);
        }
        else
            return false;
    }
    else {
        // Open the 3Dconnexion device using the device path
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
        std::cout << std::endl << "Opening device: " << std::hex << vendor_id << std::dec << "/" << std::hex << product_id << std::dec << "\"" << path << "\" using hid_open_path()" << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
        m_device = hid_open_path(path.c_str());
    }
    if (m_device != nullptr) {
        wchar_t buffer[1024];
        hid_get_manufacturer_string(m_device, buffer, 1024);
        m_device_str = boost::nowide::narrow(buffer);
        // #3479 seems to show that sometimes an extra whitespace is added, so we remove it
        boost::algorithm::trim(m_device_str);
        hid_get_product_string(m_device, buffer, 1024);
        m_device_str += "/" + boost::nowide::narrow(buffer);
        // #3479 seems to show that sometimes an extra whitespace is added, so we remove it
        boost::algorithm::trim(m_device_str);
        BOOST_LOG_TRIVIAL(info) << "Connected 3DConnexion device:";
        BOOST_LOG_TRIVIAL(info) << "Manufacturer/product: " << m_device_str;
        BOOST_LOG_TRIVIAL(info) << "Manufacturer id.....: " << vendor_id << " (" << std::hex << vendor_id << std::dec << ")";
        BOOST_LOG_TRIVIAL(info) << "Product id..........: " << product_id << " (" << std::hex << product_id << std::dec << ")";
        if (!path.empty())
            BOOST_LOG_TRIVIAL(info) << "Path................: '" << path << "'";
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
        std::cout << "Opened device." << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
        // Copy the parameters for m_device_str into the current parameters.
        if (auto it_params = m_params_by_device.find(m_device_str); it_params != m_params_by_device.end()) {
        std::scoped_lock<std::mutex> lock(m_params_ui_mutex);
        m_params = m_params_ui = it_params->second;
      }
    }
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    else {
        std::cout << std::endl << "Unable to connect to device:" << std::endl;
        std::cout << "Manufacturer/product: " << m_device_str << std::endl;
        std::cout << "Manufacturer id.....: " << vendor_id << " (" << std::hex << vendor_id << std::dec << ")" << std::endl;
        std::cout << "Product id..........: " << product_id << " (" << std::hex << product_id << std::dec << ")" << std::endl;
        std::cout << "Path................: '" << path << "'" << std::endl;
    }
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    return (m_device != nullptr);
}
References _3DCONNEXION_DEVICES, _3DCONNEXION_VENDORS, error, hid_close(), hid_enumerate(), hid_free_enumeration(), hid_get_manufacturer_string(), hid_get_product_string(), hid_open(), hid_open_path(), hid_device_info::interface_number, L, m_device, m_device_str, m_params, m_params_by_device, m_params_ui, m_params_ui_mutex, m_stop, m_stop_condition, m_stop_condition_mutex, hid_device_info::manufacturer_string, boost::nowide::narrow(), hid_device_info::next, hid_device_info::path, hid_device_info::product_id, hid_device_info::product_string, hid_device_info::serial_number, usage(), hid_device_info::usage, hid_device_info::usage_page, and hid_device_info::vendor_id.
Referenced by run().
connected()
bool Slic3r::GUI::Mouse3DController::connected () const inline
{ return m_connected; }
References m_connected.
Referenced by DeviceAdded(), and show_settings_dialog().
disconnect_device()
void Slic3r::GUI::Mouse3DController::disconnect_device () private
{
    if (m_device) {
      hid_close(m_device);
      m_device = nullptr;
      BOOST_LOG_TRIVIAL(info) << "Disconnected device: " << m_device_str;
        // Copy the current parameters for m_device_str into the parameter database.
        {
          std::scoped_lock<std::mutex> lock(m_params_ui_mutex);
          m_params_by_device[m_device_str] = m_params_ui;
      }
      m_device_str.clear();
      m_connected = false;
#ifdef _WIN32
      // Enumerate once immediately after disconnect.
      m_wakeup = true;
#endif // _WIN32
        wxGetApp().plater()->CallAfter([]() {
          Plater *plater = wxGetApp().plater();
          if (plater != nullptr) {
            plater->get_camera().recover_from_free_camera();
            plater->set_current_canvas_as_dirty();
          }
      });
    }
}
References Slic3r::GUI::Plater::get_camera(), hid_close(), m_connected, m_device, m_device_str, m_params_by_device, m_params_ui, m_params_ui_mutex, Slic3r::GUI::plater(), Slic3r::GUI::Camera::recover_from_free_camera(), and Slic3r::GUI::Plater::set_current_canvas_as_dirty().
Referenced by collect_input(), and run().
handle_input()
bool Slic3r::GUI::Mouse3DController::handle_input (const DataPacketRaw & packet, const int packet_length, const Params & params, State & state_in_out) static private
{
    if (! wxGetApp().IsActive())
        return false;
    int res = packet_length;
    bool updated = false;
    if (res == 7 || res == 13 ||
        // On Mac button packets can be 3 bytes long
        ((res == 3) && (packet[0] == 3)))
        updated = handle_packet(packet, res, params, state_in_out);
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    else if (res > 0)
        std::cout << "Got unknown data packet of length: " << res << ", code:" << (int)packet[0] << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
    if (updated) {
        wxGetApp().plater()->set_current_canvas_as_dirty();
        // ask for an idle event to update 3D scene
        wxWakeUpIdle();
    }
    return updated;
}
References handle_packet().
Referenced by collect_input(), and DeviceEvent().
handle_packet()
bool Slic3r::GUI::Mouse3DController::handle_packet (const DataPacketRaw & packet, const int packet_length, const Params & params, State & state_in_out) static private
{
    switch (packet[0])
    {
    case 1: // Translation + Rotation
        {
            bool updated = handle_packet_translation(packet, params, state_in_out);
            if (packet_length == 13)
              updated |= handle_packet_rotation(packet, 7, params, state_in_out);
            if (updated)
                return true;
            break;
        }
    case 2: // Rotation
        {
            if (handle_packet_rotation(packet, 1, params, state_in_out))
                return true;
            break;
        }
    case 3: // Button
        {
            if (params.buttons_enabled && handle_packet_button(packet, packet.size() - 1, params, state_in_out))
                return true;
            break;
        }
    case 23: // Battery charge
        {
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            std::cout << "3DConnexion - battery level: " << (int)packet[1] << " percent" << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            break;
        }
    default:
        {
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            std::cout << "3DConnexion - Got unknown data packet of code: " << (int)packet[0] << std::endl;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            break;
        }
    }
    return false;
}
References Slic3r::GUI::Mouse3DController::Params::buttons_enabled, handle_packet_button(), handle_packet_rotation(), and handle_packet_translation().
Referenced by handle_input().
handle_packet_button()
bool Slic3r::GUI::Mouse3DController::handle_packet_button (const DataPacketRaw & packet, unsigned int packet_size, const Params & params, State & state_in_out) static private
{
    unsigned int data = 0;
    for (unsigned int i = 1; i < packet_size; ++i)
    {
        data |= packet[i] << 8 * (i - 1);
    }
    const std::bitset<32> data_bits{ data };
    for (size_t i = 0; i < data_bits.size(); ++i)
    {
        if (data_bits.test(i))
        {
            state_in_out.append_button((unsigned int)i, params.input_queue_max_size);
            return true;
        }
    }
    return false;
}
References Slic3r::GUI::Mouse3DController::State::append_button(), and Slic3r::GUI::Mouse3DController::Params::input_queue_max_size.
Referenced by handle_packet().
handle_packet_rotation()
bool Slic3r::GUI::Mouse3DController::handle_packet_rotation (const DataPacketRaw & packet, unsigned int first_byte, const Params & params, State & state_in_out) static private
{
    double deadzone = (double)params.rotation.deadzone;
    Vec3f rotation((float)convert_input(packet[first_byte + 0], packet[first_byte + 1], deadzone),
        (float)convert_input(packet[first_byte + 2], packet[first_byte + 3], deadzone),
        (float)convert_input(packet[first_byte + 4], packet[first_byte + 5], deadzone));
    if (!rotation.isApprox(Vec3f::Zero()))
    {
        state_in_out.append_rotation(rotation, params.input_queue_max_size);
        return true;
    }
    return false;
}
References Slic3r::GUI::Mouse3DController::State::append_rotation(), Slic3r::GUI::convert_input(), Slic3r::GUI::Mouse3DController::Params::CustomParameters< Number >::deadzone, Slic3r::GUI::Mouse3DController::Params::input_queue_max_size, and Slic3r::GUI::Mouse3DController::Params::rotation.
Referenced by handle_packet().
handle_packet_translation()
bool Slic3r::GUI::Mouse3DController::handle_packet_translation (const DataPacketRaw & packet, const Params & params, State & state_in_out) static private
{
    double deadzone = params.translation.deadzone;
    Vec3d translation(-convert_input(packet[1], packet[2], deadzone),
        convert_input(packet[3], packet[4], deadzone),
        convert_input(packet[5], packet[6], deadzone));
    if (!translation.isApprox(Vec3d::Zero()))
    {
        state_in_out.append_translation(translation, params.input_queue_max_size);
        return true;
    }
    return false;
}
References Slic3r::GUI::Mouse3DController::State::append_translation(), Slic3r::GUI::convert_input(), Slic3r::GUI::Mouse3DController::Params::CustomParameters< Number >::deadzone, Slic3r::GUI::Mouse3DController::Params::input_queue_max_size, and Slic3r::GUI::Mouse3DController::Params::translation.
Referenced by handle_packet().
init()
void Slic3r::GUI::Mouse3DController::init ()
{
#ifdef _WIN32
    m_device_str = detect_attached_device();
    if (!m_device_str.empty()) {
        m_connected = true;
        if (auto it_params = m_params_by_device.find(m_device_str); it_params != m_params_by_device.end())
            m_params = m_params_ui = it_params->second;
    }
#endif // _WIN32
  assert(! m_thread.joinable());
    if (! m_thread.joinable()) {
      m_stop = false;
#ifndef _WIN32
      // Don't start the background thread on Windows, as the HID messages are sent as Windows messages.
      m_thread = std::thread(&Mouse3DController::run, this);
#else
        // For some reason, HID message routing does not work well with remote session. Requires further investigation
        if (::GetSystemMetrics(SM_REMOTESESSION)) {
            m_thread = std::thread(&Mouse3DController::run, this);
        }
#endif // _WIN32
  }
}
References m_connected, m_device_str, m_params, m_params_by_device, m_params_ui, m_stop, m_thread, and run().
is_settings_dialog_shown()
bool Slic3r::GUI::Mouse3DController::is_settings_dialog_shown () const inline
{ return m_show_settings_dialog; }
References m_show_settings_dialog.
Referenced by Slic3r::GUI::GLCanvas3D::on_char().
load_config()
void Slic3r::GUI::Mouse3DController::load_config (const AppConfig & appconfig)
{
  // We do not synchronize m_params_by_device with the background thread explicitely
  // as there should be a full memory barrier executed once the background thread is started.
  m_params_by_device.clear();
  for (const std::string &device_name : appconfig.get_mouse_device_names()) {
      double translation_speed  = 4.0;
      float  rotation_speed     = 4.0;
      double translation_deadzone = Params::DefaultTranslationDeadzone;
      float  rotation_deadzone  = Params::DefaultRotationDeadzone;
      double zoom_speed       = 2.0;
        bool   swap_yz              = false;
        appconfig.get_mouse_device_translation_speed(device_name, translation_speed);
      appconfig.get_mouse_device_translation_deadzone(device_name, translation_deadzone);
      appconfig.get_mouse_device_rotation_speed(device_name, rotation_speed);
      appconfig.get_mouse_device_rotation_deadzone(device_name, rotation_deadzone);
      appconfig.get_mouse_device_zoom_speed(device_name, zoom_speed);
        appconfig.get_mouse_device_swap_yz(device_name, swap_yz);
        // clamp to valid values
      Params params;
      params.translation.scale = Params::DefaultTranslationScale * std::clamp(translation_speed, Params::MinTranslationScale, Params::MaxTranslationScale);
      params.translation.deadzone = std::clamp(translation_deadzone, 0.0, Params::MaxTranslationDeadzone);
      params.rotation.scale = Params::DefaultRotationScale * std::clamp(rotation_speed, 0.1f, 10.0f);
      params.rotation.deadzone = std::clamp(rotation_deadzone, 0.0f, Params::MaxRotationDeadzone);
      params.zoom.scale = Params::DefaultZoomScale * std::clamp(zoom_speed, 0.1, 10.0);
        params.swap_yz = swap_yz;
        m_params_by_device[device_name] = std::move(params);
  }
}
References Slic3r::GUI::Mouse3DController::Params::CustomParameters< Number >::deadzone, Slic3r::GUI::Mouse3DController::Params::DefaultRotationDeadzone, Slic3r::GUI::Mouse3DController::Params::DefaultRotationScale, Slic3r::GUI::Mouse3DController::Params::DefaultTranslationDeadzone, Slic3r::GUI::Mouse3DController::Params::DefaultTranslationScale, Slic3r::GUI::Mouse3DController::Params::DefaultZoomScale, Slic3r::AppConfig::get_mouse_device_names(), Slic3r::AppConfig::get_mouse_device_rotation_deadzone(), Slic3r::AppConfig::get_mouse_device_rotation_speed(), Slic3r::AppConfig::get_mouse_device_swap_yz(), Slic3r::AppConfig::get_mouse_device_translation_deadzone(), Slic3r::AppConfig::get_mouse_device_translation_speed(), Slic3r::AppConfig::get_mouse_device_zoom_speed(), m_params_by_device, Slic3r::GUI::Mouse3DController::Params::MaxRotationDeadzone, Slic3r::GUI::Mouse3DController::Params::MaxTranslationDeadzone, Slic3r::GUI::Mouse3DController::Params::MaxTranslationScale, Slic3r::GUI::Mouse3DController::Params::MinTranslationScale, Slic3r::GUI::Mouse3DController::Params::rotation, Slic3r::GUI::Mouse3DController::Params::CustomParameters< Number >::scale, Slic3r::GUI::Mouse3DController::Params::swap_yz, Slic3r::GUI::Mouse3DController::Params::translation, and Slic3r::GUI::Mouse3DController::Params::zoom.
render_settings_dialog()
void Slic3r::GUI::Mouse3DController::render_settings_dialog (GLCanvas3D & canvas) const
{
    if (! m_show_settings_dialog || ! m_connected)
        return;
    // when the user clicks on [X] or [Close] button we need to trigger
    // an extra frame to let the dialog disappear
    if (m_settings_dialog_closed_by_user) {
        m_show_settings_dialog = false;
        m_settings_dialog_closed_by_user = false;
        canvas.request_extra_frame();
        return;
    }
    Params params_copy;
    bool   params_changed = false;
    {
      std::scoped_lock<std::mutex> lock(m_params_ui_mutex);
      params_copy = m_params_ui;
    }
    Size cnv_size = canvas.get_canvas_size();
    ImGuiWrapper& imgui = *wxGetApp().imgui();
    imgui.set_next_window_pos(0.5f * (float)cnv_size.get_width(), 0.5f * (float)cnv_size.get_height(), ImGuiCond_Always, 0.5f, 0.5f);
    static ImVec2 last_win_size(0.0f, 0.0f);
    bool shown = true;
    if (imgui.begin(_L("3Dconnexion settings"), &shown, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoCollapse)) {
        if (shown) {
            ImVec2 win_size = ImGui::GetWindowSize();
            if (last_win_size.x != win_size.x || last_win_size.y != win_size.y) {
                // when the user clicks on [X] button, the next time the dialog is shown
                // has a dummy size, so we trigger an extra frame to let it have the correct size
                last_win_size = win_size;
                canvas.request_extra_frame();
            }
            const ImVec4& color = ImGui::GetStyleColorVec4(ImGuiCol_Separator);
            imgui.text_colored(color, _L("Device:"));
            ImGui::SameLine();
            imgui.text(m_device_str);
            ImGui::Separator();
            imgui.text_colored(color, _L("Speed:"));
            float translation_scale = float(params_copy.translation.scale) / float(Params::DefaultTranslationScale);
            if (imgui.slider_float(_L("Translation"), &translation_scale, float(Params::MinTranslationScale), float(Params::MaxTranslationScale), "%.1f")) {
                params_copy.translation.scale = Params::DefaultTranslationScale * double(translation_scale);
              params_changed = true;
            }
            float rotation_scale = params_copy.rotation.scale / Params::DefaultRotationScale;
            if (imgui.slider_float(_L("Rotation") + "##1", &rotation_scale, 0.1f, 10.0f, "%.1f")) {
              params_copy.rotation.scale = Params::DefaultRotationScale * rotation_scale;
              params_changed = true;
            }
            float zoom_scale = params_copy.zoom.scale / Params::DefaultZoomScale;
            if (imgui.slider_float(_L("Zoom"), &zoom_scale, 0.1f, 10.0f, "%.1f")) {
              params_copy.zoom.scale = Params::DefaultZoomScale * zoom_scale;
              params_changed = true;
            }
            ImGui::Separator();
            imgui.text_colored(color, _L("Deadzone:"));
            float translation_deadzone = (float)params_copy.translation.deadzone;
            if (imgui.slider_float(_L("Translation") + "/" + _L("Zoom"), &translation_deadzone, 0.0f, (float)Params::MaxTranslationDeadzone, "%.2f")) {
              params_copy.translation.deadzone = (double)translation_deadzone;
              params_changed = true;
            }
            float rotation_deadzone = params_copy.rotation.deadzone;
            if (imgui.slider_float(_L("Rotation") + "##2", &rotation_deadzone, 0.0f, Params::MaxRotationDeadzone, "%.2f")) {
              params_copy.rotation.deadzone = rotation_deadzone;
              params_changed = true;
            }
            ImGui::Separator();
            imgui.text_colored(color, _L("Options:"));
            bool swap_yz = params_copy.swap_yz;
            if (imgui.checkbox(_L("Swap Y/Z axes"), swap_yz)) {
                params_copy.swap_yz = swap_yz;
                params_changed = true;
            }
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            ImGui::Separator();
            ImGui::Separator();
            imgui.text_colored(color, "DEBUG:");
            imgui.text_colored(color, "Vectors:");
            Vec3f translation = m_state.get_first_vector_of_type(State::QueueItem::TranslationType).cast<float>();
            Vec3f rotation = m_state.get_first_vector_of_type(State::QueueItem::RotationType).cast<float>();
            ImGui::InputFloat3("Translation##2", translation.data(), "%.3f", ImGuiInputTextFlags_ReadOnly);
            ImGui::InputFloat3("Rotation##3", rotation.data(), "%.3f", ImGuiInputTextFlags_ReadOnly);
            imgui.text_colored(color, "Queue size:");
            int input_queue_size_current[2] = { int(m_state.input_queue_size_current()), int(m_state.input_queue_max_size_achieved) };
            ImGui::InputInt2("Current", input_queue_size_current, ImGuiInputTextFlags_ReadOnly);
            int input_queue_size_param = int(params_copy.input_queue_max_size);
            if (ImGui::InputInt("Max size", &input_queue_size_param, 1, 1, ImGuiInputTextFlags_ReadOnly)) {
                if (input_queue_size_param > 0) {
                params_copy.input_queue_max_size = input_queue_size_param;
                params_changed = true;
                }
            }
            ImGui::Separator();
            imgui.text_colored(color, "Camera:");
            Vec3f target = wxGetApp().plater()->get_camera().get_target().cast<float>();
            ImGui::InputFloat3("Target", target.data(), "%.3f", ImGuiInputTextFlags_ReadOnly);
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
            ImGui::Separator();
            if (imgui.button(_L("Close"))) {
                // the user clicked on the [Close] button
                m_settings_dialog_closed_by_user = true;
                canvas.set_as_dirty();
            }
        }
        else {
            // the user clicked on the [X] button
            m_settings_dialog_closed_by_user = true;
            canvas.set_as_dirty();
        }
    }
    imgui.end();
    if (params_changed) {
        // Synchronize front end parameters to back end.
      std::scoped_lock<std::mutex> lock(m_params_ui_mutex);
        auto pthis = const_cast<Mouse3DController*>(this);
#if ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
        if (params_copy.input_queue_max_size != params_copy.input_queue_max_size)
          // Reset the statistics counter.
            m_state.input_queue_max_size_achieved = 0;
#endif // ENABLE_3DCONNEXION_DEVICES_DEBUG_OUTPUT
        pthis->m_params_ui = params_copy;
        pthis->m_params_ui_changed = true;
    }
}
References _L, Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::checkbox(), Eigen::PlainObjectBase< Derived >::data(), Slic3r::GUI::Mouse3DController::Params::CustomParameters< Number >::deadzone, Slic3r::GUI::Mouse3DController::Params::DefaultRotationScale, Slic3r::GUI::Mouse3DController::Params::DefaultTranslationScale, Slic3r::GUI::Mouse3DController::Params::DefaultZoomScale, Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), ImGui::GetStyleColorVec4(), ImGui::GetWindowSize(), ImGuiCol_Separator, ImGuiCond_Always, ImGuiInputTextFlags_ReadOnly, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, Slic3r::GUI::Mouse3DController::Params::input_queue_max_size, ImGui::InputFloat3(), ImGui::InputInt(), ImGui::InputInt2(), m_connected, m_device_str, m_params_ui, m_params_ui_mutex, m_settings_dialog_closed_by_user, m_show_settings_dialog, m_state, Slic3r::GUI::Mouse3DController::Params::MaxRotationDeadzone, Slic3r::GUI::Mouse3DController::Params::MaxTranslationDeadzone, Slic3r::GUI::Mouse3DController::Params::MaxTranslationScale, Slic3r::GUI::Mouse3DController::Params::MinTranslationScale, Slic3r::GUI::GLCanvas3D::request_extra_frame(), Slic3r::GUI::Mouse3DController::Params::rotation, Slic3r::GUI::Mouse3DController::State::QueueItem::RotationType, ImGui::SameLine(), Slic3r::GUI::Mouse3DController::Params::CustomParameters< Number >::scale, ImGui::Separator(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::ImGuiWrapper::slider_float(), Slic3r::GUI::Mouse3DController::Params::swap_yz, Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), Slic3r::GUI::Mouse3DController::Params::translation, Slic3r::GUI::Mouse3DController::State::QueueItem::TranslationType, ImVec2::x, ImVec2::y, and Slic3r::GUI::Mouse3DController::Params::zoom.
run()
void Slic3r::GUI::Mouse3DController::run () private
{
    // Initialize the hidapi library
    int res = hid_init();
    if (res != 0) {
      // Give up.
#if defined(__unix__) || defined(__unix) || defined(unix)
      if (res == -1)
        // Hopefully this error code comes from our bundled patched hidapi. In that case, -1 is returned by hid_wrapper_udev_init() and it mean
      BOOST_LOG_TRIVIAL(error) << "Unable to initialize hidapi library: failed to load libudev.so.1 or libudev.so.0";
      else if (res == -2)
        // Hopefully this error code comes from our bundled patched hidapi. In that case, -2 is returned by hid_wrapper_udev_init() and it mean
      BOOST_LOG_TRIVIAL(error) << "Unable to initialize hidapi library: failed to resolve some function from libudev.so.1 or libudev.so.0";
      else
#endif // unixes
          BOOST_LOG_TRIVIAL(error) << "Unable to initialize hidapi library";
        return;
    }
#ifdef _WIN32
    // Enumerate once just after thread start.
  m_wakeup = true;
#endif // _WIN32
    for (;;) {
        {
          std::scoped_lock<std::mutex> lock(m_params_ui_mutex);
          if (m_stop)
            break;
          if (m_params_ui_changed) {
                m_params = m_params_ui;
            m_params_ui_changed = false;
          }
        }
      if (m_device == nullptr)
        // Polls the HID devices, blocks for maximum 2 seconds.
        m_connected = this->connect_device();
      else
        // Waits for 3DConnexion mouse input for maximum 100ms, then repeats.
          this->collect_input();
    }
    this->disconnect_device();
    // Finalize the hidapi library
    hid_exit();
}
References collect_input(), connect_device(), disconnect_device(), error, hid_exit(), hid_init(), m_connected, m_device, m_params, m_params_ui, m_params_ui_changed, m_params_ui_mutex, and m_stop.
Referenced by init().
save_config()
void Slic3r::GUI::Mouse3DController::save_config (AppConfig & appconfig) const
{
  // We do not synchronize m_params_by_device with the background thread explicitely
  // as there should be a full memory barrier executed once the background thread is stopped.
    for (const auto &key_value_pair : m_params_by_device) {
    const std::string &device_name = key_value_pair.first;
    const Params      &params      = key_value_pair.second;
      // Store current device parameters into the config
        appconfig.set_mouse_device(device_name, params.translation.scale / Params::DefaultTranslationScale, params.translation.deadzone,
            params.rotation.scale / Params::DefaultRotationScale, params.rotation.deadzone, params.zoom.scale / Params::DefaultZoomScale, params.swap_yz);
    }
}
References Slic3r::GUI::Mouse3DController::Params::CustomParameters< Number >::deadzone, Slic3r::GUI::Mouse3DController::Params::DefaultRotationScale, Slic3r::GUI::Mouse3DController::Params::DefaultTranslationScale, Slic3r::GUI::Mouse3DController::Params::DefaultZoomScale, m_params_by_device, Slic3r::GUI::Mouse3DController::Params::rotation, Slic3r::GUI::Mouse3DController::Params::CustomParameters< Number >::scale, Slic3r::AppConfig::set_mouse_device(), Slic3r::GUI::Mouse3DController::Params::swap_yz, Slic3r::GUI::Mouse3DController::Params::translation, and Slic3r::GUI::Mouse3DController::Params::zoom.
Referenced by Slic3r::GUI::MainFrame::shutdown().
show_settings_dialog()
void Slic3r::GUI::Mouse3DController::show_settings_dialog (bool show) inline
{ m_show_settings_dialog = show && this->connected(); }
References connected(), and m_show_settings_dialog.
Referenced by Slic3r::GUI::GLCanvas3D::on_char().
shutdown()
void Slic3r::GUI::Mouse3DController::shutdown ()
{
    if (m_thread.joinable()) {
      // Stop the worker thread, if running.
      {
        // Notify the worker thread to cancel wait on detection polling.
      std::lock_guard<std::mutex> lock(m_stop_condition_mutex);
      m_stop = true;
    }
    m_stop_condition.notify_all();
    // Wait for the worker thread to stop.
        m_thread.join();
        m_stop = false;
  }
#ifdef _WIN32
    if (!m_device_str.empty())
        m_params_by_device[m_device_str] = m_params_ui;
#endif // _WIN32
}
References m_device_str, m_params_by_device, m_params_ui, m_stop, m_stop_condition, m_stop_condition_mutex, and m_thread.
Referenced by Slic3r::GUI::MainFrame::shutdown().
Member Data Documentation
m_connected
std::atomic<bool> Slic3r::GUI::Mouse3DController::m_connected { false } private
Referenced by apply(), connected(), disconnect_device(), init(), render_settings_dialog(), and run().
m_device
hid_device* Slic3r::GUI::Mouse3DController::m_device { nullptr } private
Referenced by collect_input(), connect_device(), disconnect_device(), and run().
m_device_str
std::string Slic3r::GUI::Mouse3DController::m_device_str private
Referenced by connect_device(), disconnect_device(), init(), render_settings_dialog(), and shutdown().
m_params
Params Slic3r::GUI::Mouse3DController::m_params private
Referenced by apply(), collect_input(), connect_device(), init(), and run().
m_params_by_device
std::map<std::string, Params> Slic3r::GUI::Mouse3DController::m_params_by_device private
Referenced by connect_device(), disconnect_device(), init(), load_config(), save_config(), and shutdown().
m_params_ui
Params Slic3r::GUI::Mouse3DController::m_params_ui private
Referenced by apply(), connect_device(), disconnect_device(), init(), render_settings_dialog(), run(), and shutdown().
m_params_ui_changed
bool Slic3r::GUI::Mouse3DController::m_params_ui_changed { false } private
Referenced by apply(), and run().
m_params_ui_mutex
std::mutex Slic3r::GUI::Mouse3DController::m_params_ui_mutex mutable private
Referenced by apply(), connect_device(), disconnect_device(), render_settings_dialog(), and run().
m_settings_dialog_closed_by_user
bool Slic3r::GUI::Mouse3DController::m_settings_dialog_closed_by_user { false } mutable private
Referenced by apply(), and render_settings_dialog().
m_show_settings_dialog
bool Slic3r::GUI::Mouse3DController::m_show_settings_dialog { false } mutable private
Referenced by apply(), is_settings_dialog_shown(), render_settings_dialog(), and show_settings_dialog().
m_state
State Slic3r::GUI::Mouse3DController::m_state mutable private
Referenced by apply(), collect_input(), and render_settings_dialog().
m_stop
bool Slic3r::GUI::Mouse3DController::m_stop { false } private
Referenced by connect_device(), init(), run(), and shutdown().
m_stop_condition
std::condition_variable Slic3r::GUI::Mouse3DController::m_stop_condition private
Referenced by connect_device(), and shutdown().
m_stop_condition_mutex
std::mutex Slic3r::GUI::Mouse3DController::m_stop_condition_mutex private
Referenced by connect_device(), and shutdown().
m_thread
std::thread Slic3r::GUI::Mouse3DController::m_thread private
Referenced by init(), and shutdown().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Mouse3DController.hpp
src/slic3r/GUI/Mouse3DController.cpp
src/slic3r/GUI/Mouse3DHandlerMac.mm