Prusa Slicer: libnest2d::_Segment< P > Class Template Reference
libnest2d::_Segment< P > Class Template Reference
An abstraction of a directed line segment with two points.
#include <src/libnest2d/include/libnest2d/geometry_traits.hpp>
Public Types
using PointType = P
Public Member Functions
_Segment ()=default
_Segment (const P &p, const P &pp)
const P & first () const BP2D_NOEXCEPT
Get the first point.
const P & second () const BP2D_NOEXCEPT
The end point.
void first (const P &p) BP2D_NOEXCEPT
void second (const P &p) BP2D_NOEXCEPT
Radians angleToXaxis () const
Returns the angle measured to the X (horizontal) axis.
template<class Unit = TCompute<P>>
Unit sqlength () const
The length of the segment in the measure of the coordinate system.
Private Attributes
Radians angletox_ = std::nan("")
P p1
P p2
Detailed Description
template<class P>
class libnest2d::_Segment< P >
An abstraction of a directed line segment with two points.
Member Typedef Documentation
PointType
template<class P > using libnest2d::_Segment< P >::PointType = P
Constructor & Destructor Documentation
_Segment() [1/2]
template<class P > libnest2d::_Segment< P >::_Segment () inline default
_Segment() [2/2]
template<class P > libnest2d::_Segment< P >::_Segment (const P & p, const P & pp) inline
                                            :
        PointPair<P>({p, pp}) {}
Member Function Documentation
angleToXaxis()
template<class P > Radians libnest2d::_Segment< P >::angleToXaxis inline
Returns the angle measured to the X (horizontal) axis.
{
    if(std::isnan(static_cast<double>(angletox_))) {
        TCoord<P> dx = getX(second()) - getX(first());
        TCoord<P> dy = getY(second()) - getY(first());
        double a = std::atan2(dy, dx);
        auto s = std::signbit(a);
        if(s) a += Pi_2;
        angletox_ = a;
    }
    return angletox_;
}
References libnest2d::getX(), libnest2d::getY(), and libnest2d::Pi_2.
first() [1/2]
template<class P > const P & libnest2d::_Segment< P >::first () const inline
Get the first point.
Returns
Returns the starting point.
{ return p1; }
References libnest2d::PointPair< P >::p1.
Referenced by boost::geometry::traits::indexed_access< bp2d::Segment, 0, 0 >::get(), boost::geometry::traits::indexed_access< bp2d::Segment, 0, 1 >::get(), libnest2d::pointlike::horizontalDistance(), boost::geometry::traits::indexed_access< bp2d::Segment, 0, 0 >::set(), boost::geometry::traits::indexed_access< bp2d::Segment, 0, 1 >::set(), and libnest2d::pointlike::verticalDistance().
first() [2/2]
template<class P > void libnest2d::_Segment< P >::first (const P & p) inline
    {
        angletox_ = std::nan(""); p1 = p;
    }
References libnest2d::_Segment< P >::angletox_, and libnest2d::PointPair< P >::p1.
second() [1/2]
template<class P > const P & libnest2d::_Segment< P >::second () const inline
The end point.
Returns
Returns the end point of the segment.
{ return p2; }
References libnest2d::PointPair< P >::p2.
Referenced by boost::geometry::traits::indexed_access< bp2d::Segment, 1, 0 >::get(), boost::geometry::traits::indexed_access< bp2d::Segment, 1, 1 >::get(), libnest2d::pointlike::horizontalDistance(), boost::geometry::traits::indexed_access< bp2d::Segment, 1, 0 >::set(), boost::geometry::traits::indexed_access< bp2d::Segment, 1, 1 >::set(), and libnest2d::pointlike::verticalDistance().
second() [2/2]
template<class P > void libnest2d::_Segment< P >::second (const P & p) inline
{
        angletox_ = std::nan(""); p2 = p;
    }
References libnest2d::_Segment< P >::angletox_, and libnest2d::PointPair< P >::p2.
sqlength()
template<class P > template<class Unit > Unit libnest2d::_Segment< P >::sqlength inline
The length of the segment in the measure of the coordinate system.
{
    return pointlike::squaredDistance<P, Unit>(first(), second());
}
Member Data Documentation
angletox_
template<class P > Radians libnest2d::_Segment< P >::angletox_ = std::nan("") mutable private
Referenced by libnest2d::_Segment< P >::first(), and libnest2d::_Segment< P >::second().
p1
template<class P > P libnest2d::PointPair< P >::p1 inherited
Referenced by libnest2d::_Segment< P >::first(), libnest2d::_Segment< P >::first(), libnest2d::_Box< P >::minCorner(), and libnest2d::_Box< P >::minCorner().
p2
template<class P > P libnest2d::PointPair< P >::p2 inherited
Referenced by libnest2d::_Box< P >::maxCorner(), libnest2d::_Box< P >::maxCorner(), libnest2d::_Segment< P >::second(), and libnest2d::_Segment< P >::second().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/geometry_traits.hpp