Prusa Slicer: libnest2d::opt Namespace Reference
libnest2d::opt Namespace Reference
Classes
class Bound
An interval of possible input values for optimization.
class DummyOptimizer
class GeneticOptimizer
struct limits
A Type trait for upper and lower limit of a numeric type.
struct limits< T, enable_if_t< std::numeric_limits< T >::has_infinity, void > >
class metaloop
Helper class to be able to loop over a parameter pack's elements.
class NloptOptimizer
class Optimizer
The Optimizer base class with CRTP pattern.
struct OptimizerSubclass
struct OptimizerSubclass< Method::G_GENETIC >
struct OptimizerSubclass< Method::L_SIMPLEX >
struct OptimizerSubclass< Method::L_SUBPLEX >
struct Result
A type to hold the complete result of the optimization.
class SimplexOptimizer
struct StopCriteria
A type for specifying the stop criteria.
class SubplexOptimizer
Typedefs
template<class... Args>
using Input = tuple< Args... >
template<Method m>
using TOptimizer = typename OptimizerSubclass< m >::Type
Optimizer type based on the method provided in parameter m.
Enumerations
enum class Method { L_SIMPLEX , L_SUBPLEX , G_GENETIC , G_PARTICLE_SWARM }
Specific optimization methods for which a default optimizer implementation can be instantiated.
enum ResultCodes {
FAILURE = -1 , INVALID_ARGS = -2 , OUT_OF_MEMORY = -3 , ROUNDOFF_LIMITED = -4 ,
FORCED_STOP = -5 , SUCCESS = 1 , STOPVAL_REACHED = 2 , FTOL_REACHED = 3 ,
XTOL_REACHED = 4 , MAXEVAL_REACHED = 5 , MAXTIME_REACHED = 6
}
Info about result of an optimization. These codes are exactly the same as the nlopt codes for convinience.
Functions
template<class T >
Bound< T > bound (const T &min, const T &max)
template<class... Args>
tuple< Args... > initvals (Args...args)
template<Method m>
TOptimizer< m > GlobalOptimizer (Method, const StopCriteria &scr={})
Global optimizer with an explicitly specified local method.
template<>
TOptimizer< Method::G_GENETIC > GlobalOptimizer< Method::G_GENETIC > (Method localm, const StopCriteria &scr)
nlopt::algorithm method2nloptAlg (Method m)
Class Documentation
libnest2d::opt::OptimizerSubclass
struct libnest2d::opt::OptimizerSubclass
template<Method m>
struct libnest2d::opt::OptimizerSubclass< m >
Class Members
typedef DummyOptimizer<> Type
libnest2d::opt::OptimizerSubclass< Method::G_GENETIC >
struct libnest2d::opt::OptimizerSubclass< Method::G_GENETIC >
Class Members
typedef GeneticOptimizer Type
libnest2d::opt::OptimizerSubclass< Method::L_SIMPLEX >
struct libnest2d::opt::OptimizerSubclass< Method::L_SIMPLEX >
Class Members
typedef SimplexOptimizer Type
libnest2d::opt::OptimizerSubclass< Method::L_SUBPLEX >
struct libnest2d::opt::OptimizerSubclass< Method::L_SUBPLEX >
Class Members
typedef SubplexOptimizer Type
libnest2d::opt::Result
struct libnest2d::opt::Result
template<class... Args>
struct libnest2d::opt::Result< Args >
A type to hold the complete result of the optimization.
Class Members
tuple< Args... > optimum
ResultCodes resultcode
double score
libnest2d::opt::StopCriteria
struct libnest2d::opt::StopCriteria
A type for specifying the stop criteria.
Class Members
double absolute_score_difference = std::nan("") If the absolute value difference between two scores.
unsigned max_iterations = 0 The max allowed number of iterations.
double relative_score_difference = std::nan("") If the relative value difference between two scores.
function< bool()> stop_condition = [] { return false; } A predicate that if evaluates to true, the optimization should terminate and the best result found prior to termination should be returned.
double stop_score = std::nan("") Stop if this value or better is found.
Typedef Documentation
Input
template<class... Args> using libnest2d::opt::Input = typedef tuple<Args...>
This is the type of an input tuple for the object function. It holds the values and their type in each dimension.
TOptimizer
template<Method m> using libnest2d::opt::TOptimizer = typedef typename OptimizerSubclass<m>::Type
Optimizer type based on the method provided in parameter m.
Enumeration Type Documentation
Method
enum class libnest2d::opt::Method strong
Specific optimization methods for which a default optimizer implementation can be instantiated.
Enumerator
L_SIMPLEX
L_SUBPLEX
G_GENETIC
G_PARTICLE_SWARM
                  {
    L_SIMPLEX,
    L_SUBPLEX,
    G_GENETIC,
    G_PARTICLE_SWARM
    //...
};
ResultCodes
enum libnest2d::opt::ResultCodes
Info about result of an optimization. These codes are exactly the same as the nlopt codes for convinience.
Enumerator
FAILURE
INVALID_ARGS
OUT_OF_MEMORY
ROUNDOFF_LIMITED
FORCED_STOP
SUCCESS
STOPVAL_REACHED
FTOL_REACHED
XTOL_REACHED
MAXEVAL_REACHED
MAXTIME_REACHED
                 {
    FAILURE = -1, /* generic failure code */
    INVALID_ARGS = -2,
    OUT_OF_MEMORY = -3,
    ROUNDOFF_LIMITED = -4,
    FORCED_STOP = -5,
    SUCCESS = 1, /* generic success code */
    STOPVAL_REACHED = 2,
    FTOL_REACHED = 3,
    XTOL_REACHED = 4,
    MAXEVAL_REACHED = 5,
    MAXTIME_REACHED = 6
};
Function Documentation
bound()
template<class T > Bound< T > libnest2d::opt::bound (const T & min, const T & max) inline
Helper function to make a Bound object with its type deduced automatically.
{ return Bound<T>(min, max); }
Referenced by libnest2d::placers::minimizeCircle().
GlobalOptimizer()
template<Method m> TOptimizer< m > libnest2d::opt::GlobalOptimizer (Method , const StopCriteria & scr = {}) inline
Global optimizer with an explicitly specified local method.
                                                                       {})
{ // Need to be specialized in order to do anything useful.
    return TOptimizer<m>(scr);
}
GlobalOptimizer< Method::G_GENETIC >()
template<> TOptimizer< Method::G_GENETIC > libnest2d::opt::GlobalOptimizer< Method::G_GENETIC > (Method localm, const StopCriteria & scr) inline
{
    return GeneticOptimizer (scr).localMethod(localm);
}
initvals()
template<class... Args> tuple< Args... > libnest2d::opt::initvals (Args... args) inline
{ return make_tuple(args...); }
References initvals().
Referenced by libnest2d::findBestRotation(), initvals(), libnest2d::placers::minimizeCircle(), libnest2d::opt::NloptOptimizer::optimize(), libnest2d::opt::Optimizer< Subclass >::optimize_max(), libnest2d::opt::Optimizer< Subclass >::optimize_max(), libnest2d::opt::Optimizer< Subclass >::optimize_min(), and libnest2d::opt::Optimizer< Subclass >::optimize_min().
method2nloptAlg()
nlopt::algorithm libnest2d::opt::method2nloptAlg (Method m) inline
{
    switch(m) {
    case Method::L_SIMPLEX: return nlopt::LN_NELDERMEAD;
    case Method::L_SUBPLEX: return nlopt::LN_SBPLX;
    case Method::G_GENETIC: return nlopt::GN_ESCH;
    default: assert(false); throw(m);
    }
}
References G_GENETIC, L_SIMPLEX, and L_SUBPLEX.
Referenced by libnest2d::opt::NloptOptimizer::optimize().