Prusa Slicer: Slic3r::PressureEqualizer Class Reference
Slic3r::PressureEqualizer Class Reference
#include <src/libslic3r/GCode/PressureEqualizer.hpp>
Classes
struct ExtrusionRateSlope
struct GCodeLine
Public Member Functions
PressureEqualizer ()=delete
PressureEqualizer (const Slic3r::GCodeConfig &config)
~PressureEqualizer ()=default
LayerResult process_layer (LayerResult &&input)
Public Attributes
std::queue< LayerResult * > m_layer_results
std::vector< GCodeLine > m_gcode_lines
Private Types
enum GCodeLineType {
GCODELINETYPE_INVALID , GCODELINETYPE_NOOP , GCODELINETYPE_OTHER , GCODELINETYPE_RETRACT ,
GCODELINETYPE_UNRETRACT , GCODELINETYPE_TOOL_CHANGE , GCODELINETYPE_MOVE , GCODELINETYPE_EXTRUDE
}
Private Member Functions
void process_layer (const std::string &gcode)
bool process_line (const char *line, const char *line_end, GCodeLine &buf)
void output_gcode_line (size_t line_idx)
void adjust_volumetric_rate ()
void push_to_output (GCodeG1Formatter &formatter)
void push_to_output (const std::string &text, bool add_eol)
void push_to_output (const char *text, size_t len, bool add_eol=true)
void push_line_to_output (size_t line_idx, float new_feedrate, const char *comment)
Private Attributes
ExtrusionRateSlope m_max_volumetric_extrusion_rate_slopes [size_t(GCodeExtrusionRole::Count)]
float m_max_volumetric_extrusion_rate_slope_positive
float m_max_volumetric_extrusion_rate_slope_negative
std::vector< float > m_filament_crossections
float m_current_pos [5]
size_t m_current_extruder
GCodeExtrusionRole m_current_extrusion_role
bool m_retracted
bool m_use_relative_e_distances
bool opened_extrude_set_speed_block = false
std::vector< char > output_buffer
size_t output_buffer_length
size_t output_buffer_prev_length
Detailed Description
Class Documentation
Slic3r::PressureEqualizer::ExtrusionRateSlope
struct Slic3r::PressureEqualizer::ExtrusionRateSlope
Class Members
float negative
float positive
Member Enumeration Documentation
GCodeLineType
enum Slic3r::PressureEqualizer::GCodeLineType private
Enumerator
GCODELINETYPE_INVALID
GCODELINETYPE_NOOP
GCODELINETYPE_OTHER
GCODELINETYPE_RETRACT
GCODELINETYPE_UNRETRACT
GCODELINETYPE_TOOL_CHANGE
GCODELINETYPE_MOVE
GCODELINETYPE_EXTRUDE
                       {
        GCODELINETYPE_INVALID,
        GCODELINETYPE_NOOP,
        GCODELINETYPE_OTHER,
        GCODELINETYPE_RETRACT,
        GCODELINETYPE_UNRETRACT,
        GCODELINETYPE_TOOL_CHANGE,
        GCODELINETYPE_MOVE,
        GCODELINETYPE_EXTRUDE,
    };
Constructor & Destructor Documentation
PressureEqualizer() [1/2]
Slic3r::PressureEqualizer::PressureEqualizer () delete
PressureEqualizer() [2/2]
Slic3r::PressureEqualizer::PressureEqualizer (const Slic3r::GCodeConfig & config) explicit
                                                                    : m_use_relative_e_distances(config.use_relative_e_distances.value)
{
    // Preallocate some data, so that output_buffer.data() will return an empty string.
    output_buffer.assign(32, 0);
    output_buffer_length      = 0;
    output_buffer_prev_length = 0;
    m_current_extruder = 0;
    // Zero the position of the XYZE axes + the current feed
    memset(m_current_pos, 0, sizeof(float) * 5);
    m_current_extrusion_role = GCodeExtrusionRole::None;
    // Expect the first command to fill the nozzle (deretract).
    m_retracted = true;
    // Calculate filamet crossections for the multiple extruders.
    m_filament_crossections.clear();
    for (double r : config.filament_diameter.values) {
        double a = 0.25f * M_PI * r * r;
        m_filament_crossections.push_back(float(a));
    }
    // Volumetric rate of a 0.45mm x 0.2mm extrusion at 60mm/s XY movement: 0.45*0.2*60*60=5.4*60 = 324 mm^3/min
    // Volumetric rate of a 0.45mm x 0.2mm extrusion at 20mm/s XY movement: 0.45*0.2*20*60=1.8*60 = 108 mm^3/min
    // Slope of the volumetric rate, changing from 20mm/s to 60mm/s over 2 seconds: (5.4-1.8)*60*60/2=60*60*1.8 = 6480 mm^3/min^2 = 1.8 mm^3/s^2
    m_max_volumetric_extrusion_rate_slope_positive = float(config.max_volumetric_extrusion_rate_slope_positive.value) * 60.f * 60.f;
    m_max_volumetric_extrusion_rate_slope_negative = float(config.max_volumetric_extrusion_rate_slope_negative.value) * 60.f * 60.f;
    for (ExtrusionRateSlope &extrusion_rate_slope : m_max_volumetric_extrusion_rate_slopes) {
        extrusion_rate_slope.negative = m_max_volumetric_extrusion_rate_slope_negative;
        extrusion_rate_slope.positive = m_max_volumetric_extrusion_rate_slope_positive;
    }
    // Don't regulate the pressure before and after gap-fill and ironing.
    for (const GCodeExtrusionRole er : {GCodeExtrusionRole::GapFill, GCodeExtrusionRole::Ironing}) {
        m_max_volumetric_extrusion_rate_slopes[size_t(er)].negative = 0;
        m_max_volumetric_extrusion_rate_slopes[size_t(er)].positive = 0;
    }
    opened_extrude_set_speed_block = false;
#ifdef PRESSURE_EQUALIZER_STATISTIC
    m_stat.reset();
#endif
#ifdef PRESSURE_EQUALIZER_DEBUG
    line_idx = 0;
#endif
}
References Slic3r::GapFill, Slic3r::Ironing, m_current_extruder, m_current_extrusion_role, m_current_pos, m_filament_crossections, m_max_volumetric_extrusion_rate_slope_negative, m_max_volumetric_extrusion_rate_slope_positive, m_max_volumetric_extrusion_rate_slopes, M_PI, m_retracted, Slic3r::PressureEqualizer::ExtrusionRateSlope::negative, Slic3r::None, opened_extrude_set_speed_block, output_buffer, output_buffer_length, output_buffer_prev_length, and Slic3r::PressureEqualizer::ExtrusionRateSlope::positive.
~PressureEqualizer()
Slic3r::PressureEqualizer::~PressureEqualizer () default
Member Function Documentation
adjust_volumetric_rate()
void Slic3r::PressureEqualizer::adjust_volumetric_rate () private
{
    if (m_gcode_lines.size() < 2)
        return;
    // Go back from the current circular_buffer_pos and lower the feedtrate to decrease the slope of the extrusion rate changes.
    size_t       fist_line_idx = size_t(std::max<int>(0, int(m_gcode_lines.size()) - max_look_back_limit));
    const size_t last_line_idx = m_gcode_lines.size() - 1;
    size_t       line_idx      = last_line_idx;
    if (line_idx == fist_line_idx || !m_gcode_lines[line_idx].extruding())
        // Nothing to do, the last move is not extruding.
        return;
    std::array<float, size_t(GCodeExtrusionRole::Count)> feedrate_per_extrusion_role{};
    feedrate_per_extrusion_role.fill(std::numeric_limits<float>::max());
    feedrate_per_extrusion_role[int(m_gcode_lines[line_idx].extrusion_role)] = m_gcode_lines[line_idx].volumetric_extrusion_rate_start;
    while (line_idx != fist_line_idx) {
        size_t idx_prev = line_idx - 1;
        for (; !m_gcode_lines[idx_prev].extruding() && idx_prev != fist_line_idx; --idx_prev);
        if (!m_gcode_lines[idx_prev].extruding())
            break;
        // Don't decelerate before ironing and gap-fill.
        if (m_gcode_lines[line_idx].extrusion_role == GCodeExtrusionRole::Ironing || m_gcode_lines[line_idx].extrusion_role == GCodeExtrusionRole::GapFill) {
            line_idx = idx_prev;
            continue;
        }
        // Volumetric extrusion rate at the start of the succeding segment.
        float rate_succ = m_gcode_lines[line_idx].volumetric_extrusion_rate_start;
        // What is the gradient of the extrusion rate between idx_prev and idx?
        line_idx        = idx_prev;
        GCodeLine &line = m_gcode_lines[line_idx];
        for (size_t iRole = 1; iRole < size_t(GCodeExtrusionRole::Count); ++ iRole) {
            const float &rate_slope = m_max_volumetric_extrusion_rate_slopes[iRole].negative;
            if (rate_slope == 0 || feedrate_per_extrusion_role[iRole] == std::numeric_limits<float>::max())
                continue; // The negative rate is unlimited or the rate for GCodeExtrusionRole iRole is unlimited.
            float rate_end = feedrate_per_extrusion_role[iRole];
            if (iRole == size_t(line.extrusion_role) && rate_succ < rate_end)
                // Limit by the succeeding volumetric flow rate.
                rate_end = rate_succ;
            if (!line.adjustable_flow || line.extrusion_role == GCodeExtrusionRole::ExternalPerimeter || line.extrusion_role == GCodeExtrusionRole::GapFill || line.extrusion_role == GCodeExtrusionRole::BridgeInfill || line.extrusion_role == GCodeExtrusionRole::Ironing) {
                rate_end = line.volumetric_extrusion_rate_end;
            } else if (line.volumetric_extrusion_rate_end > rate_end) {
                line.volumetric_extrusion_rate_end = rate_end;
                line.max_volumetric_extrusion_rate_slope_negative = rate_slope;
                line.modified = true;
            } else if (iRole == size_t(line.extrusion_role)) {
                rate_end = line.volumetric_extrusion_rate_end;
            } else {
                // Use the original, 'floating' extrusion rate as a starting point for the limiter.
            }
            if (line.adjustable_flow) {
                float rate_start = rate_end + rate_slope * line.time_corrected();
                if (rate_start < line.volumetric_extrusion_rate_start) {
                    // Limit the volumetric extrusion rate at the start of this segment due to a segment
                    // of ExtrusionType iRole, which will be extruded in the future.
                    line.volumetric_extrusion_rate_start = rate_start;
                    line.max_volumetric_extrusion_rate_slope_negative = rate_slope;
                    line.modified = true;
                }
            }
//            feedrate_per_extrusion_role[iRole] = (iRole == line.extrusion_role) ? line.volumetric_extrusion_rate_start : rate_start;
            // Don't store feed rate for ironing and gap-fill.
            if (line.extrusion_role != GCodeExtrusionRole::Ironing && line.extrusion_role != GCodeExtrusionRole::GapFill)
                feedrate_per_extrusion_role[iRole] = line.volumetric_extrusion_rate_start;
        }
    }
    feedrate_per_extrusion_role.fill(std::numeric_limits<float>::max());
    feedrate_per_extrusion_role[size_t(m_gcode_lines[line_idx].extrusion_role)] = m_gcode_lines[line_idx].volumetric_extrusion_rate_end;
    assert(m_gcode_lines[line_idx].extruding());
    while (line_idx != last_line_idx) {
        size_t idx_next = line_idx + 1;
        for (; !m_gcode_lines[idx_next].extruding() && idx_next != last_line_idx; ++idx_next);
        if (!m_gcode_lines[idx_next].extruding())
            break;
        // Don't accelerate after ironing and gap-fill.
        if (m_gcode_lines[line_idx].extrusion_role == GCodeExtrusionRole::Ironing || m_gcode_lines[line_idx].extrusion_role == GCodeExtrusionRole::GapFill) {
            line_idx = idx_next;
            continue;
        }
        float rate_prec = m_gcode_lines[line_idx].volumetric_extrusion_rate_end;
        // What is the gradient of the extrusion rate between idx_prev and idx?
        line_idx = idx_next;
        GCodeLine &line = m_gcode_lines[line_idx];
        for (size_t iRole = 1; iRole < size_t(GCodeExtrusionRole::Count); ++ iRole) {
            const float &rate_slope = m_max_volumetric_extrusion_rate_slopes[iRole].positive;
            if (rate_slope == 0 || feedrate_per_extrusion_role[iRole] == std::numeric_limits<float>::max())
                continue; // The positive rate is unlimited or the rate for GCodeExtrusionRole iRole is unlimited.
            float rate_start = feedrate_per_extrusion_role[iRole];
            if (!line.adjustable_flow || line.extrusion_role == GCodeExtrusionRole::ExternalPerimeter || line.extrusion_role == GCodeExtrusionRole::GapFill || line.extrusion_role == GCodeExtrusionRole::BridgeInfill || line.extrusion_role == GCodeExtrusionRole::Ironing) {
                rate_start = line.volumetric_extrusion_rate_start;
            } else if (iRole == size_t(line.extrusion_role) && rate_prec < rate_start)
                rate_start = rate_prec;
            if (line.volumetric_extrusion_rate_start > rate_start) {
                line.volumetric_extrusion_rate_start = rate_start;
                line.max_volumetric_extrusion_rate_slope_positive = rate_slope;
                line.modified = true;
            } else if (iRole == size_t(line.extrusion_role)) {
                rate_start = line.volumetric_extrusion_rate_start;
            } else {
                // Use the original, 'floating' extrusion rate as a starting point for the limiter.
            }
            if (line.adjustable_flow) {
                float rate_end = rate_start + rate_slope * line.time_corrected();
                if (rate_end < line.volumetric_extrusion_rate_end) {
                    // Limit the volumetric extrusion rate at the start of this segment due to a segment
                    // of ExtrusionType iRole, which was extruded before.
                    line.volumetric_extrusion_rate_end                = rate_end;
                    line.max_volumetric_extrusion_rate_slope_positive = rate_slope;
                    line.modified                                     = true;
                }
            }
//            feedrate_per_extrusion_role[iRole] = (iRole == line.extrusion_role) ? line.volumetric_extrusion_rate_end : rate_end;
            // Don't store feed rate for ironing and gap-fill.
            if (line.extrusion_role != GCodeExtrusionRole::Ironing && line.extrusion_role != GCodeExtrusionRole::GapFill)
                feedrate_per_extrusion_role[iRole] = line.volumetric_extrusion_rate_end;
        }
    }
}
References Slic3r::PressureEqualizer::GCodeLine::adjustable_flow, Slic3r::BridgeInfill, Slic3r::Count, Slic3r::ExternalPerimeter, Slic3r::PressureEqualizer::GCodeLine::extrusion_role, Slic3r::GapFill, Slic3r::Ironing, m_gcode_lines, m_max_volumetric_extrusion_rate_slopes, Slic3r::max_look_back_limit, Slic3r::PressureEqualizer::GCodeLine::max_volumetric_extrusion_rate_slope_negative, Slic3r::PressureEqualizer::GCodeLine::max_volumetric_extrusion_rate_slope_positive, Slic3r::PressureEqualizer::GCodeLine::modified, Slic3r::PressureEqualizer::ExtrusionRateSlope::negative, Slic3r::PressureEqualizer::ExtrusionRateSlope::positive, Slic3r::PressureEqualizer::GCodeLine::time_corrected(), Slic3r::PressureEqualizer::GCodeLine::volumetric_extrusion_rate_end, and Slic3r::PressureEqualizer::GCodeLine::volumetric_extrusion_rate_start.
Referenced by process_line().
output_gcode_line()
void Slic3r::PressureEqualizer::output_gcode_line (size_t line_idx) private
{
    GCodeLine &line = m_gcode_lines[line_idx];
    if (!line.modified) {
        push_to_output(line.raw.data(), line.raw_length, true);
        return;
    }
    // The line was modified.
    // Find the comment.
    const char *comment = line.raw.data();
    while (*comment != ';' && *comment != 0) ++comment;
    if (*comment != ';')
        comment = nullptr;
    // Emit the line with lowered extrusion rates.
    float l = line.dist_xyz();
    if (auto nSegments = size_t(ceil(l / max_segment_length)); nSegments == 1) { // Just update this segment.
        push_line_to_output(line_idx, line.feedrate() * line.volumetric_correction_avg(), comment);
    } else {
        bool accelerating = line.volumetric_extrusion_rate_start < line.volumetric_extrusion_rate_end;
        // Update the initial and final feed rate values.
        line.pos_start[4] = line.volumetric_extrusion_rate_start * line.pos_end[4] / line.volumetric_extrusion_rate;
        line.pos_end  [4] = line.volumetric_extrusion_rate_end   * line.pos_end[4] / line.volumetric_extrusion_rate;
        float feed_avg = 0.5f * (line.pos_start[4] + line.pos_end[4]);
        // Limiting volumetric extrusion rate slope for this segment.
        float max_volumetric_extrusion_rate_slope = accelerating ? line.max_volumetric_extrusion_rate_slope_positive :
                                                                   line.max_volumetric_extrusion_rate_slope_negative;
        // Total time for the segment, corrected for the possibly lowered volumetric feed rate,
        // if accelerating / decelerating over the complete segment.
        float t_total = line.dist_xyz() / feed_avg;
        // Time of the acceleration / deceleration part of the segment, if accelerating / decelerating
        // with the maximum volumetric extrusion rate slope.
        float t_acc    = 0.5f * (line.volumetric_extrusion_rate_start + line.volumetric_extrusion_rate_end) / max_volumetric_extrusion_rate_slope;
        float l_acc    = l;
        float l_steady = 0.f;
        if (t_acc < t_total) {
            // One may achieve higher print speeds if part of the segment is not speed limited.
            l_acc    = t_acc * feed_avg;
            l_steady = l - l_acc;
            if (l_steady < 0.5f * max_segment_length) {
                l_acc    = l;
                l_steady = 0.f;
            } else
                nSegments = size_t(ceil(l_acc / max_segment_length));
        }
        float pos_start[5];
        float pos_end[5];
        float pos_end2[4];
        memcpy(pos_start, line.pos_start, sizeof(float) * 5);
        memcpy(pos_end, line.pos_end, sizeof(float) * 5);
        if (l_steady > 0.f) {
            // There will be a steady feed segment emitted.
            if (accelerating) {
                // Prepare the final steady feed rate segment.
                memcpy(pos_end2, pos_end, sizeof(float)*4);
                float t = l_acc / l;
                for (int i = 0; i < 4; ++ i) {
                    pos_end[i] = pos_start[i] + (pos_end[i] - pos_start[i]) * t;
                    line.pos_provided[i] = true;
                }
            } else {
                // Emit the steady feed rate segment.
                float t = l_steady / l;
                for (int i = 0; i < 4; ++ i) {
                    line.pos_end[i] = pos_start[i] + (pos_end[i] - pos_start[i]) * t;
                    line.pos_provided[i] = true;
                }
                push_line_to_output(line_idx, pos_start[4], comment);
                comment = nullptr;
                float new_pos_start_feedrate = pos_start[4];
                memcpy(line.pos_start, line.pos_end, sizeof(float)*5);
                memcpy(pos_start, line.pos_end, sizeof(float)*5);
                line.pos_start[4] = new_pos_start_feedrate;
                pos_start[4] = new_pos_start_feedrate;
            }
        }
        // Split the segment into pieces.
        for (size_t i = 1; i < nSegments; ++ i) {
            float t = float(i) / float(nSegments);
            for (size_t j = 0; j < 4; ++ j) {
                line.pos_end[j] = pos_start[j] + (pos_end[j] - pos_start[j]) * t;
                line.pos_provided[j] = true;
            }
            // Interpolate the feed rate at the center of the segment.
            push_line_to_output(line_idx, pos_start[4] + (pos_end[4] - pos_start[4]) * (float(i) - 0.5f) / float(nSegments), comment);
            comment = nullptr;
            memcpy(line.pos_start, line.pos_end, sizeof(float)*5);
        }
    if (l_steady > 0.f && accelerating) {
            for (int i = 0; i < 4; ++ i) {
                line.pos_end[i] = pos_end2[i];
                line.pos_provided[i] = true;
            }
            push_line_to_output(line_idx, pos_end[4], comment);
        } else {
            for (int i = 0; i < 4; ++ i) {
                line.pos_end[i] = pos_end[i];
                line.pos_provided[i] = true;
            }
            push_line_to_output(line_idx, pos_end[4], comment);
        }
    }
}
References ceil(), comment, Slic3r::PressureEqualizer::GCodeLine::dist_xyz(), Slic3r::PressureEqualizer::GCodeLine::feedrate(), m_gcode_lines, Slic3r::max_segment_length, Slic3r::PressureEqualizer::GCodeLine::max_volumetric_extrusion_rate_slope_negative, Slic3r::PressureEqualizer::GCodeLine::max_volumetric_extrusion_rate_slope_positive, Slic3r::PressureEqualizer::GCodeLine::modified, Slic3r::PressureEqualizer::GCodeLine::pos_end, Slic3r::PressureEqualizer::GCodeLine::pos_provided, Slic3r::PressureEqualizer::GCodeLine::pos_start, push_line_to_output(), push_to_output(), Slic3r::PressureEqualizer::GCodeLine::raw, Slic3r::PressureEqualizer::GCodeLine::raw_length, Slic3r::PressureEqualizer::GCodeLine::volumetric_correction_avg(), Slic3r::PressureEqualizer::GCodeLine::volumetric_extrusion_rate, Slic3r::PressureEqualizer::GCodeLine::volumetric_extrusion_rate_end, and Slic3r::PressureEqualizer::GCodeLine::volumetric_extrusion_rate_start.
Referenced by process_layer().
process_layer() [1/2]
void Slic3r::PressureEqualizer::process_layer (const std::string & gcode) private
{
    if (!gcode.empty()) {
        const char *gcode_begin = gcode.c_str();
        while (*gcode_begin != 0) {
            // Find end of the line.
            const char *gcode_end = gcode_begin;
            // Slic3r always generates end of lines in a Unix style.
            for (; *gcode_end != 0 && *gcode_end != '\n'; ++gcode_end);
            m_gcode_lines.emplace_back();
            if (!this->process_line(gcode_begin, gcode_end, m_gcode_lines.back())) {
                // The line has to be forgotten. It contains comment marks, which shall be filtered out of the target g-code.
                m_gcode_lines.pop_back();
            }
            gcode_begin = gcode_end;
            if (*gcode_begin == '\n')
                ++gcode_begin;
        }
        assert(!this->opened_extrude_set_speed_block);
    }
}
References m_gcode_lines, opened_extrude_set_speed_block, and process_line().
process_layer() [2/2]
LayerResult Slic3r::PressureEqualizer::process_layer (LayerResult && input)
{
    const bool   is_first_layer       = m_layer_results.empty();
    const size_t next_layer_first_idx = m_gcode_lines.size();
    if (!input.nop_layer_result) {
        this->process_layer(input.gcode);
        input.gcode.clear(); // GCode is already processed, so it isn't needed to store it.
        m_layer_results.emplace(new LayerResult(input));
    }
    if (is_first_layer) // Buffer previous input result and output NOP.
        return LayerResult::make_nop_layer_result();
    // Export previous layer.
    LayerResult *prev_layer_result = m_layer_results.front();
    m_layer_results.pop();
    output_buffer_length      = 0;
    output_buffer_prev_length = 0;
    for (size_t line_idx = 0; line_idx < next_layer_first_idx; ++line_idx)
        output_gcode_line(line_idx);
    m_gcode_lines.erase(m_gcode_lines.begin(), m_gcode_lines.begin() + int(next_layer_first_idx));
    if (output_buffer_length > 0)
        prev_layer_result->gcode = std::string(output_buffer.data());
    assert(!input.nop_layer_result || m_layer_results.empty());
    LayerResult out = *prev_layer_result;
    delete prev_layer_result;
    return out;
}
References Slic3r::LayerResult::gcode, input(), m_gcode_lines, m_layer_results, Slic3r::LayerResult::make_nop_layer_result(), output_buffer, output_buffer_length, output_buffer_prev_length, output_gcode_line(), and process_layer().
Referenced by process_layer().
process_line()
bool Slic3r::PressureEqualizer::process_line (const char * line, const char * line_end, GCodeLine & buf) private
{
    const size_t len = line_end - line;
    if (strncmp(line, EXTRUSION_ROLE_TAG.data(), EXTRUSION_ROLE_TAG.length()) == 0) {
        line += EXTRUSION_ROLE_TAG.length();
        int role = atoi(line);
        m_current_extrusion_role = GCodeExtrusionRole(role);
#ifdef PRESSURE_EQUALIZER_DEBUG
        ++line_idx;
#endif
        return false;
    }
    // Set the type, copy the line to the buffer.
    buf.type = GCODELINETYPE_OTHER;
    buf.modified = false;
    if (buf.raw.size() < len + 1)
        buf.raw.assign(line, line + len + 1);
    else
        memcpy(buf.raw.data(), line, len);
    buf.raw[len] = 0;
    buf.raw_length = len;
    memcpy(buf.pos_start, m_current_pos, sizeof(float)*5);
    memcpy(buf.pos_end, m_current_pos, sizeof(float)*5);
    memset(buf.pos_provided, 0, 5);
    buf.volumetric_extrusion_rate = 0.f;
    buf.volumetric_extrusion_rate_start = 0.f;
    buf.volumetric_extrusion_rate_end = 0.f;
    buf.max_volumetric_extrusion_rate_slope_positive = 0.f;
    buf.max_volumetric_extrusion_rate_slope_negative = 0.f;
  buf.extrusion_role = m_current_extrusion_role;
    std::string str_line(line, line_end);
    const bool found_extrude_set_speed_tag = boost::contains(str_line, EXTRUDE_SET_SPEED_TAG);
    const bool found_extrude_end_tag = boost::contains(str_line, EXTRUDE_END_TAG);
    assert(!found_extrude_set_speed_tag || !found_extrude_end_tag);
    if (found_extrude_set_speed_tag)
        this->opened_extrude_set_speed_block = true;
    else if (found_extrude_end_tag)
        this->opened_extrude_set_speed_block = false;
    // Parse the G-code line, store the result into the buf.
    switch (toupper(*line ++)) {
    case 'G': {
        int gcode = -1;
        try {
            gcode = parse_int(line);
        } catch (Slic3r::InvalidArgument &) {
            // Ignore invalid GCodes.
            eatws(line);
            break;
        }
        assert(gcode != -1);
        eatws(line);
        switch (gcode) {
        case 0:
        case 1:
        {
            // G0, G1: A FFF 3D printer does not make a difference between the two.
            buf.adjustable_flow = this->opened_extrude_set_speed_block;
            buf.extrude_set_speed_tag = found_extrude_set_speed_tag;
            buf.extrude_end_tag = found_extrude_end_tag;
            float new_pos[5];
            memcpy(new_pos, m_current_pos, sizeof(float)*5);
            bool  changed[5] = { false, false, false, false, false };
            while (!is_eol(*line)) {
                const char axis = toupper(*line++);
                int  i = -1;
                switch (axis) {
                case 'X':
                case 'Y':
                case 'Z':
                    i = axis - 'X';
                    break;
                case 'E':
                    i = 3;
                    break;
                case 'F':
                    i = 4;
                    break;
                default:
                    break;
                }
                if (i != -1) {
                    buf.pos_provided[i] = true;
                    new_pos[i] = parse_float(line, line_end - line);
                    if (i == 3 && m_use_relative_e_distances)
                        new_pos[i] += m_current_pos[i];
                    changed[i] = new_pos[i] != m_current_pos[i];
                    eatws(line);
                }
            }
            if (changed[3]) {
                // Extrusion, retract or unretract.
                float diff = new_pos[3] - m_current_pos[3];
                if (diff < 0) {
                    buf.type = GCODELINETYPE_RETRACT;
                    m_retracted = true;
                } else if (! changed[0] && ! changed[1] && ! changed[2]) {
                    // assert(m_retracted);
                    buf.type = GCODELINETYPE_UNRETRACT;
                    m_retracted = false;
                } else {
                    assert(changed[0] || changed[1]);
                    // Moving in XY plane.
                    buf.type = GCODELINETYPE_EXTRUDE;
                    // Calculate the volumetric extrusion rate.
                    float diff[4];
                    for (size_t i = 0; i < 4; ++ i)
                        diff[i] = new_pos[i] - m_current_pos[i];
                    // volumetric extrusion rate = A_filament * F_xyz * L_e / L_xyz [mm^3/min]
                    float len2 = diff[0]*diff[0]+diff[1]*diff[1]+diff[2]*diff[2];
                    float rate = m_filament_crossections[m_current_extruder] * new_pos[4] * sqrt((diff[3]*diff[3])/len2);
                    buf.volumetric_extrusion_rate       = rate;
                    buf.volumetric_extrusion_rate_start = rate;
                    buf.volumetric_extrusion_rate_end   = rate;
#ifdef PRESSURE_EQUALIZER_STATISTIC
                    m_stat.update(rate, sqrt(len2));
#endif
#ifdef PRESSURE_EQUALIZER_DEBUG
                    if (rate < 40.f) {
                        printf("Extremely low flow rate: %f. Line %d, Length: %f, extrusion: %f Old position: (%f, %f, %f), new position: (%f, %f, %f)\n",
                               rate, int(line_idx), sqrt(len2), sqrt((diff[3] * diff[3]) / len2), m_current_pos[0], m_current_pos[1], m_current_pos[2],
                               new_pos[0], new_pos[1], new_pos[2]);
                    }
#endif
                }
            } else if (changed[0] || changed[1] || changed[2]) {
                // Moving without extrusion.
                buf.type = GCODELINETYPE_MOVE;
            }
            memcpy(m_current_pos, new_pos, sizeof(float) * 5);
            break;
        }
        case 92:
        {
            // G92 : Set Position
            // Set a logical coordinate position to a new value without actually moving the machine motors.
            // Which axes to set?
            while (!is_eol(*line)) {
                const char axis = toupper(*line++);
                switch (axis) {
                case 'X':
                case 'Y':
                case 'Z':
                    m_current_pos[axis - 'X'] = (!is_ws_or_eol(*line)) ? parse_float(line, line_end - line) : 0.f;
                    break;
                case 'E':
                    m_current_pos[3] = (!is_ws_or_eol(*line)) ? parse_float(line, line_end - line) : 0.f;
                    break;
                default:
                    break;
                }
                eatws(line);
            }
            break;
        }
        case 10:
        case 22:
            // Firmware retract.
            buf.type = GCODELINETYPE_RETRACT;
            m_retracted = true;
            break;
        case 11:
        case 23:
            // Firmware unretract.
            buf.type = GCODELINETYPE_UNRETRACT;
            m_retracted = false;
            break;
        default:
            // Ignore the rest.
        break;
        }
        break;
    }
    case 'M': {
        eatws(line);
        // Ignore the rest of the M-codes.
        break;
    }
    case 'T':
    {
        // Activate an extruder head.
        int new_extruder = -1;
        try {
            new_extruder = parse_int(line);
        } catch (Slic3r::InvalidArgument &) {
            // Ignore invalid GCodes starting with T.
            eatws(line);
            break;
        }
        assert(new_extruder != -1);
        if (new_extruder != int(m_current_extruder)) {
            m_current_extruder = new_extruder;
            m_retracted = true;
            buf.type = GCODELINETYPE_TOOL_CHANGE;
        } else {
            buf.type = GCODELINETYPE_NOOP;
        }
        break;
    }
    }
    buf.extruder_id = m_current_extruder;
    memcpy(buf.pos_end, m_current_pos, sizeof(float)*5);
    adjust_volumetric_rate();
#ifdef PRESSURE_EQUALIZER_DEBUG
    ++line_idx;
#endif
    return true;
}
References adjust_volumetric_rate(), Slic3r::PressureEqualizer::GCodeLine::adjustable_flow, Slic3r::diff(), Slic3r::eatws(), Slic3r::EXTRUDE_END_TAG, Slic3r::PressureEqualizer::GCodeLine::extrude_end_tag, Slic3r::EXTRUDE_SET_SPEED_TAG, Slic3r::PressureEqualizer::GCodeLine::extrude_set_speed_tag, Slic3r::PressureEqualizer::GCodeLine::extruder_id, Slic3r::PressureEqualizer::GCodeLine::extrusion_role, Slic3r::EXTRUSION_ROLE_TAG, GCODELINETYPE_EXTRUDE, GCODELINETYPE_MOVE, GCODELINETYPE_NOOP, GCODELINETYPE_OTHER, GCODELINETYPE_RETRACT, GCODELINETYPE_TOOL_CHANGE, GCODELINETYPE_UNRETRACT, Slic3r::is_eol(), Slic3r::is_ws_or_eol(), m_current_extruder, m_current_extrusion_role, m_current_pos, m_filament_crossections, m_retracted, m_use_relative_e_distances, Slic3r::PressureEqualizer::GCodeLine::max_volumetric_extrusion_rate_slope_negative, Slic3r::PressureEqualizer::GCodeLine::max_volumetric_extrusion_rate_slope_positive, Slic3r::PressureEqualizer::GCodeLine::modified, opened_extrude_set_speed_block, Slic3r::parse_float(), Slic3r::parse_int(), Slic3r::PressureEqualizer::GCodeLine::pos_end, Slic3r::PressureEqualizer::GCodeLine::pos_provided, Slic3r::PressureEqualizer::GCodeLine::pos_start, Slic3r::PressureEqualizer::GCodeLine::raw, Slic3r::PressureEqualizer::GCodeLine::raw_length, sqrt(), Slic3r::PressureEqualizer::GCodeLine::type, Slic3r::PressureEqualizer::GCodeLine::volumetric_extrusion_rate, Slic3r::PressureEqualizer::GCodeLine::volumetric_extrusion_rate_end, and Slic3r::PressureEqualizer::GCodeLine::volumetric_extrusion_rate_start.
Referenced by process_layer().
push_line_to_output()
void Slic3r::PressureEqualizer::push_line_to_output (size_t line_idx, float new_feedrate, const char * comment) private
{
    const GCodeLine &line = m_gcode_lines[line_idx];
    if (line_idx > 0 && output_buffer_length > 0) {
        const std::string prev_line_str = std::string(output_buffer.begin() + int(this->output_buffer_prev_length),
                                                      output_buffer.begin() + int(this->output_buffer_length) + 1);
        if (is_just_line_with_extrude_set_speed_tag(prev_line_str))
            this->output_buffer_length = this->output_buffer_prev_length; // Remove the last line because it only sets the speed for an empty block of g-code lines, so it is useless.
        else
            push_to_output(EXTRUDE_END_TAG.data(), EXTRUDE_END_TAG.length(), true);
    } else
        push_to_output(EXTRUDE_END_TAG.data(), EXTRUDE_END_TAG.length(), true);
    GCodeG1Formatter feedrate_formatter;
    feedrate_formatter.emit_f(new_feedrate);
    feedrate_formatter.emit_string(std::string(EXTRUDE_SET_SPEED_TAG.data(), EXTRUDE_SET_SPEED_TAG.length()));
    if (line.extrusion_role == GCodeExtrusionRole::ExternalPerimeter)
        feedrate_formatter.emit_string(std::string(EXTERNAL_PERIMETER_TAG.data(), EXTERNAL_PERIMETER_TAG.length()));
    push_to_output(feedrate_formatter);
    GCodeG1Formatter extrusion_formatter;
    for (size_t axis_idx = 0; axis_idx < 3; ++axis_idx)
        if (line.pos_provided[axis_idx])
            extrusion_formatter.emit_axis(char('X' + axis_idx), line.pos_end[axis_idx], GCodeFormatter::XYZF_EXPORT_DIGITS);
    extrusion_formatter.emit_axis('E', m_use_relative_e_distances ? (line.pos_end[3] - line.pos_start[3]) : line.pos_end[3], GCodeFormatter::E_EXPORT_DIGITS);
    if (comment != nullptr)
        extrusion_formatter.emit_string(std::string(comment));
    push_to_output(extrusion_formatter);
}
References comment, Slic3r::GCodeFormatter::E_EXPORT_DIGITS, Slic3r::GCodeFormatter::emit_axis(), Slic3r::GCodeFormatter::emit_f(), Slic3r::GCodeFormatter::emit_string(), Slic3r::EXTERNAL_PERIMETER_TAG, Slic3r::ExternalPerimeter, Slic3r::EXTRUDE_END_TAG, Slic3r::EXTRUDE_SET_SPEED_TAG, Slic3r::PressureEqualizer::GCodeLine::extrusion_role, Slic3r::is_just_line_with_extrude_set_speed_tag(), m_gcode_lines, m_use_relative_e_distances, output_buffer, output_buffer_length, output_buffer_prev_length, Slic3r::PressureEqualizer::GCodeLine::pos_end, Slic3r::PressureEqualizer::GCodeLine::pos_provided, Slic3r::PressureEqualizer::GCodeLine::pos_start, push_to_output(), and Slic3r::GCodeFormatter::XYZF_EXPORT_DIGITS.
Referenced by output_gcode_line().
push_to_output() [1/3]
void Slic3r::PressureEqualizer::push_to_output (const char * text, size_t len, bool add_eol = true) inline private
{
    // New length of the output buffer content.
    size_t len_new = output_buffer_length + len + 1;
    if (add_eol)
        ++len_new;
    // Resize the output buffer to a power of 2 higher than the required memory.
    if (output_buffer.size() < len_new) {
        size_t v = len_new;
        // Compute the next highest power of 2 of 32-bit v
        // http://graphics.stanford.edu/~seander/bithacks.html
        v--;
        v |= v >> 1;
        v |= v >> 2;
        v |= v >> 4;
        v |= v >> 8;
        v |= v >> 16;
        v++;
        output_buffer.resize(v);
    }
    // Copy the text to the output.
    if (len != 0) {
        memcpy(output_buffer.data() + output_buffer_length, text, len);
        this->output_buffer_prev_length = this->output_buffer_length;
        output_buffer_length += len;
    }
    if (add_eol)
        output_buffer[output_buffer_length++] = '\n';
    output_buffer[output_buffer_length] = 0;
}
References output_buffer, output_buffer_length, and output_buffer_prev_length.
push_to_output() [2/3]
void Slic3r::PressureEqualizer::push_to_output (const std::string & text, bool add_eol) inline private
{
    return this->push_to_output(text.data(), text.size(), add_eol);
}
References push_to_output().
push_to_output() [3/3]
void Slic3r::PressureEqualizer::push_to_output (GCodeG1Formatter & formatter) inline private
{
    return this->push_to_output(formatter.string(), false);
}
References push_to_output(), and Slic3r::GCodeFormatter::string().
Referenced by output_gcode_line(), push_line_to_output(), push_to_output(), and push_to_output().
Member Data Documentation
m_current_extruder
size_t Slic3r::PressureEqualizer::m_current_extruder private
Referenced by PressureEqualizer(), and process_line().
m_current_extrusion_role
GCodeExtrusionRole Slic3r::PressureEqualizer::m_current_extrusion_role private
Referenced by PressureEqualizer(), and process_line().
m_current_pos
float Slic3r::PressureEqualizer::m_current_pos[5] private
Referenced by PressureEqualizer(), and process_line().
m_filament_crossections
std::vector<float> Slic3r::PressureEqualizer::m_filament_crossections private
Referenced by PressureEqualizer(), and process_line().
m_gcode_lines
std::vector<GCodeLine> Slic3r::PressureEqualizer::m_gcode_lines
Referenced by adjust_volumetric_rate(), output_gcode_line(), process_layer(), process_layer(), and push_line_to_output().
m_layer_results
std::queue<LayerResult*> Slic3r::PressureEqualizer::m_layer_results
Referenced by process_layer().
m_max_volumetric_extrusion_rate_slope_negative
float Slic3r::PressureEqualizer::m_max_volumetric_extrusion_rate_slope_negative private
Referenced by PressureEqualizer().
m_max_volumetric_extrusion_rate_slope_positive
float Slic3r::PressureEqualizer::m_max_volumetric_extrusion_rate_slope_positive private
Referenced by PressureEqualizer().
m_max_volumetric_extrusion_rate_slopes
ExtrusionRateSlope Slic3r::PressureEqualizer::m_max_volumetric_extrusion_rate_slopes[size_t(GCodeExtrusionRole::Count)] private
Referenced by PressureEqualizer(), and adjust_volumetric_rate().
m_retracted
bool Slic3r::PressureEqualizer::m_retracted private
Referenced by PressureEqualizer(), and process_line().
m_use_relative_e_distances
bool Slic3r::PressureEqualizer::m_use_relative_e_distances private
Referenced by process_line(), and push_line_to_output().
opened_extrude_set_speed_block
bool Slic3r::PressureEqualizer::opened_extrude_set_speed_block = false private
Referenced by PressureEqualizer(), process_layer(), and process_line().
output_buffer
std::vector<char> Slic3r::PressureEqualizer::output_buffer private
Referenced by PressureEqualizer(), process_layer(), push_line_to_output(), and push_to_output().
output_buffer_length
size_t Slic3r::PressureEqualizer::output_buffer_length private
Referenced by PressureEqualizer(), process_layer(), push_line_to_output(), and push_to_output().
output_buffer_prev_length
size_t Slic3r::PressureEqualizer::output_buffer_prev_length private
Referenced by PressureEqualizer(), process_layer(), push_line_to_output(), and push_to_output().
The documentation for this class was generated from the following files:
src/libslic3r/GCode/PressureEqualizer.hpp
src/libslic3r/GCode/PressureEqualizer.cpp