Prusa Slicer: Slic3r::GUI::Selection::Clipboard Class Reference
Slic3r::GUI::Selection::Clipboard Class Reference
#include <src/slic3r/GUI/Selection.hpp>
Public Member Functions
Clipboard ()
void reset ()
bool is_empty () const
bool is_sla_compliant () const
ModelObject * add_object ()
ModelObject * get_object (unsigned int id)
const ModelObjectPtrs & get_objects () const
Selection::EMode get_mode () const
void set_mode (Selection::EMode mode)
Private Attributes
std::unique_ptr< Model > m_model
Selection::EMode m_mode
Detailed Description
Constructor & Destructor Documentation
Clipboard()
Slic3r::GUI::Selection::Clipboard::Clipboard ()
{
    m_model.reset(new Model);
}
References Slic3r::GUI::Selection::m_model.
Member Function Documentation
add_object()
ModelObject * Slic3r::GUI::Selection::Clipboard::add_object ()
{
    return m_model->add_object();
}
References Slic3r::Model::add_object(), and Slic3r::GUI::Selection::m_model.
Referenced by Slic3r::GUI::Selection::copy_to_clipboard().
get_mode()
Selection::EMode Slic3r::GUI::Selection::Clipboard::get_mode () const inline
{ return m_mode; }
References m_mode.
Referenced by Slic3r::GUI::Plater::can_paste_from_clipboard(), and Slic3r::GUI::Selection::paste_from_clipboard().
get_object()
ModelObject * Slic3r::GUI::Selection::Clipboard::get_object (unsigned int id)
{
    return (id < (unsigned int)m_model->objects.size()) ? m_model->objects[id] : nullptr;
}
References Slic3r::GUI::Selection::m_model, and Slic3r::Model::objects.
Referenced by Slic3r::GUI::Selection::paste_volumes_from_clipboard().
get_objects()
const ModelObjectPtrs & Slic3r::GUI::Selection::Clipboard::get_objects () const
{
    return m_model->objects;
}
References Slic3r::GUI::Selection::m_model, and Slic3r::Model::objects.
Referenced by Slic3r::GUI::Selection::paste_objects_from_clipboard().
is_empty()
bool Slic3r::GUI::Selection::Clipboard::is_empty () const
{
    return m_model->objects.empty();
}
References Slic3r::GUI::Selection::m_model, and Slic3r::Model::objects.
Referenced by Slic3r::GUI::Plater::can_paste_from_clipboard(), and Slic3r::GUI::Selection::paste_from_clipboard().
is_sla_compliant()
bool Slic3r::GUI::Selection::Clipboard::is_sla_compliant () const
{
//    if (m_mode == Selection::Volume)
//        return false;
//    for (const ModelObject* o : m_model->objects) {
//        if (o->is_multiparts())
//            return false;
//        for (const ModelVolume* v : o->volumes) {
//            if (v->is_modifier())
//                return false;
//        }
//    }
    return true;
}
Referenced by Slic3r::GUI::Plater::can_paste_from_clipboard().
reset()
void Slic3r::GUI::Selection::Clipboard::reset ()
{
    m_model->clear_objects();
}
References Slic3r::Model::clear_objects(), and Slic3r::GUI::Selection::m_model.
Referenced by Slic3r::GUI::Selection::copy_to_clipboard().
set_mode()
void Slic3r::GUI::Selection::Clipboard::set_mode (Selection::EMode mode) inline
{ m_mode = mode; }
References m_mode.
Referenced by Slic3r::GUI::Selection::copy_to_clipboard().
Member Data Documentation
m_mode
Selection::EMode Slic3r::GUI::Selection::Clipboard::m_mode private
Referenced by get_mode(), and set_mode().
m_model
std::unique_ptr<Model> Slic3r::GUI::Selection::Clipboard::m_model private
The documentation for this class was generated from the following files:
src/slic3r/GUI/Selection.hpp
src/slic3r/GUI/Selection.cpp