Prusa Slicer: Slic3r::GUI::BitmapComboBox Class Reference
Slic3r::GUI::BitmapComboBox Class Reference
#include <src/slic3r/GUI/BitmapComboBox.hpp>
Public Member Functions
BitmapComboBox (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &value=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int n=0, const wxString choices[]=NULL, long style=0)
~BitmapComboBox ()
int Append (const wxString &item, const wxBitmapBundle &bitmap)
Detailed Description
Constructor & Destructor Documentation
BitmapComboBox()
Slic3r::GUI::BitmapComboBox::BitmapComboBox (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & value = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int n = 0, const wxString choices[] = NULL, long style = 0)
                                                 :
    wxBitmapComboBox(parent, id, value, pos, size, n, choices, style)
{
    SetFont(Slic3r::GUI::wxGetApp().normal_font());
#ifdef _WIN32
    // Workaround for ignoring CBN_EDITCHANGE events, which are processed after the content of the combo box changes, so that
    // the index of the item inside CBN_EDITCHANGE may no more be valid.
    EnableTextChangedEvents(false);
    wxGetApp().UpdateDarkUI(this);
    if (!HasFlag(wxCB_READONLY))
        wxTextEntry::SetMargins(0,0);
#endif /* _WIN32 */
}
~BitmapComboBox()
Slic3r::GUI::BitmapComboBox::~BitmapComboBox ()
{
}
Member Function Documentation
Append()
int Slic3r::GUI::BitmapComboBox::Append (const wxString & item, const wxBitmapBundle & bitmap) inline
    {
        return wxBitmapComboBox::Append(item, bitmap);
    }
Referenced by Slic3r::GUI::ModePaletteComboBox::ModePaletteComboBox(), BitmapChoiceRenderer::CreateEditorCtrl(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/BitmapComboBox.hpp
src/slic3r/GUI/BitmapComboBox.cpp