Prusa Slicer: Slic3r::GUI::GCodeViewer::VBuffer Struct Reference
Slic3r::GUI::GCodeViewer::VBuffer Struct Reference
Public Types
enum class EFormat : unsigned char { Position , PositionNormal1 , PositionNormal3 }
Public Member Functions
size_t data_size_bytes () const
size_t max_size_bytes () const
size_t vertex_size_floats () const
size_t vertex_size_bytes () const
size_t position_offset_floats () const
size_t position_offset_bytes () const
size_t position_size_floats () const
size_t position_size_bytes () const
size_t normal_offset_floats () const
size_t normal_offset_bytes () const
size_t normal_size_floats () const
size_t normal_size_bytes () const
void reset ()
Public Attributes
EFormat format { EFormat::Position }
std::vector< unsigned int > vbos
std::vector< size_t > sizes
size_t count { 0 }
Detailed Description
Member Enumeration Documentation
EFormat
enum class Slic3r::GUI::GCodeViewer::VBuffer::EFormat : unsigned char strong
Enumerator
Position
PositionNormal1
PositionNormal3
        {
            // vertex format: 3 floats -> position.x|position.y|position.z
            Position,
            // vertex format: 4 floats -> position.x|position.y|position.z|normal.x
            PositionNormal1,
            // vertex format: 6 floats -> position.x|position.y|position.z|normal.x|normal.y|normal.z
            PositionNormal3
        };
Member Function Documentation
data_size_bytes()
size_t Slic3r::GUI::GCodeViewer::VBuffer::data_size_bytes () const inline
{ return count * vertex_size_bytes(); }
References count, and vertex_size_bytes().
max_size_bytes()
size_t Slic3r::GUI::GCodeViewer::VBuffer::max_size_bytes () const inline
{ return 65536 * vertex_size_bytes(); }
References vertex_size_bytes().
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
normal_offset_bytes()
size_t Slic3r::GUI::GCodeViewer::VBuffer::normal_offset_bytes () const inline
{ return normal_offset_floats() * sizeof(float); }
References normal_offset_floats().
Referenced by Slic3r::GUI::GCodeViewer::render_toolpaths().
normal_offset_floats()
size_t Slic3r::GUI::GCodeViewer::VBuffer::normal_offset_floats () const inline
{
            assert(format == EFormat::PositionNormal1 || format == EFormat::PositionNormal3);
            return position_size_floats();
        }
References format, position_size_floats(), PositionNormal1, and PositionNormal3.
Referenced by normal_offset_bytes().
normal_size_bytes()
size_t Slic3r::GUI::GCodeViewer::VBuffer::normal_size_bytes () const inline
{ return normal_size_floats() * sizeof(float); }
References normal_size_floats().
normal_size_floats()
size_t Slic3r::GUI::GCodeViewer::VBuffer::normal_size_floats () const inline
{
            switch (format)
            {
            case EFormat::PositionNormal1: { return 1; }
            case EFormat::PositionNormal3: { return 3; }
            default:                       { return 0; }
            }
        }
References format, PositionNormal1, and PositionNormal3.
Referenced by normal_size_bytes(), Slic3r::GUI::GCodeViewer::render_toolpaths(), and vertex_size_floats().
position_offset_bytes()
size_t Slic3r::GUI::GCodeViewer::VBuffer::position_offset_bytes () const inline
{ return position_offset_floats() * sizeof(float); }
References position_offset_floats().
Referenced by Slic3r::GUI::GCodeViewer::render_toolpaths().
position_offset_floats()
size_t Slic3r::GUI::GCodeViewer::VBuffer::position_offset_floats () const inline
{ return 0; }
Referenced by position_offset_bytes().
position_size_bytes()
size_t Slic3r::GUI::GCodeViewer::VBuffer::position_size_bytes () const inline
{ return position_size_floats() * sizeof(float); }
References position_size_floats().
position_size_floats()
size_t Slic3r::GUI::GCodeViewer::VBuffer::position_size_floats () const inline
{ return 3; }
Referenced by normal_offset_floats(), position_size_bytes(), Slic3r::GUI::GCodeViewer::render_toolpaths(), and vertex_size_floats().
reset()
void Slic3r::GUI::GCodeViewer::VBuffer::reset ()
{
    // release gpu memory
    if (!vbos.empty()) {
        glsafe(::glDeleteBuffers(static_cast<GLsizei>(vbos.size()), static_cast<const GLuint*>(vbos.data())));
        vbos.clear();
    }
#if ENABLE_GL_CORE_PROFILE
    if (!vaos.empty()) {
        glsafe(::glDeleteVertexArrays(static_cast<GLsizei>(vaos.size()), static_cast<const GLuint*>(vaos.data())));
        vaos.clear();
    }
#endif // ENABLE_GL_CORE_PROFILE
    sizes.clear();
    count = 0;
}
References count, glsafe, sizes, and vbos.
vertex_size_bytes()
size_t Slic3r::GUI::GCodeViewer::VBuffer::vertex_size_bytes () const inline
{ return vertex_size_floats() * sizeof(float); }
References vertex_size_floats().
Referenced by data_size_bytes(), Slic3r::GUI::GCodeViewer::load_toolpaths(), max_size_bytes(), and Slic3r::GUI::GCodeViewer::render_toolpaths().
vertex_size_floats()
size_t Slic3r::GUI::GCodeViewer::VBuffer::vertex_size_floats () const inline
{ return position_size_floats() + normal_size_floats(); }
References normal_size_floats(), and position_size_floats().
Referenced by Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::GUI::GCodeViewer::TBuffer::max_vertices_per_segment_size_floats(), and vertex_size_bytes().
Member Data Documentation
count
size_t Slic3r::GUI::GCodeViewer::VBuffer::count { 0 }
Referenced by data_size_bytes(), Slic3r::GUI::GCodeViewer::load_toolpaths(), and reset().
format
EFormat Slic3r::GUI::GCodeViewer::VBuffer::format { EFormat::Position }
Referenced by Slic3r::GUI::GCodeViewer::init(), normal_offset_floats(), and normal_size_floats().
sizes
std::vector<size_t> Slic3r::GUI::GCodeViewer::VBuffer::sizes
Referenced by Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj(), Slic3r::GUI::GCodeViewer::load_toolpaths(), and reset().
vbos
std::vector<unsigned int> Slic3r::GUI::GCodeViewer::VBuffer::vbos
Referenced by Slic3r::GUI::GCodeViewer::export_toolpaths_to_obj(), Slic3r::GUI::GCodeViewer::TBuffer::has_data(), Slic3r::GUI::GCodeViewer::load_toolpaths(), and reset().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GCodeViewer.hpp
src/slic3r/GUI/GCodeViewer.cpp