Prusa Slicer: Slic3r::SegmentIntersection Struct Reference
Slic3r::SegmentIntersection Struct Reference
Public Types
enum SegmentIntersectionType : char {
UNKNOWN , OUTER_LOW , OUTER_HIGH , INNER_LOW ,
INNER_HIGH
}
enum class LinkType : uint8_t { Horizontal , Up , Down , Phony }
enum class LinkQuality : uint8_t { Invalid , Valid , TooLong }
enum class Side { Left , Right }
enum class Direction { Up , Down }
Public Member Functions
coord_t pos () const
bool is_inner () const
bool is_outer () const
bool is_low () const
bool is_high () const
bool has_left_horizontal () const
bool has_right_horizontal () const
bool has_horizontal (Side side) const
bool has_left_vertical_up () const
bool has_left_vertical_down () const
bool has_left_vertical (Direction dir) const
bool has_left_vertical () const
bool has_left_vertical_outside () const
bool has_right_vertical_up () const
bool has_right_vertical_down () const
bool has_right_vertical (Direction dir) const
bool has_right_vertical () const
bool has_right_vertical_outside () const
bool has_vertical () const
bool has_vertical (Side side) const
bool has_vertical_up () const
bool has_vertical_down () const
bool has_vertical (Direction dir) const
int left_horizontal () const
int right_horizontal () const
int horizontal (Side side) const
LinkQuality horizontal_quality (Side side) const
int left_vertical_up () const
int left_vertical_down () const
int left_vertical (Direction dir) const
int left_vertical () const
int left_vertical_outside () const
int right_vertical_up () const
int right_vertical_down () const
int right_vertical (Direction dir) const
int right_vertical () const
int right_vertical_outside () const
int vertical_up (Side side) const
int vertical_down (Side side) const
int vertical_outside (Side side) const
int vertical_up () const
LinkQuality vertical_up_quality () const
int vertical_down () const
LinkQuality vertical_down_quality () const
int vertical_outside () const
LinkQuality vertical_outside_quality () const
bool operator< (const SegmentIntersection &other) const
bool operator== (const SegmentIntersection &other) const
Public Attributes
size_t iContour { 0 }
size_t iSegment { 0 }
int64_t pos_p { 0 }
uint32_t pos_q { 1 }
int32_t prev_on_contour { 0 }
int32_t next_on_contour { 0 }
SegmentIntersectionType type { UNKNOWN }
LinkType prev_on_contour_type { LinkType::Horizontal }
LinkType next_on_contour_type { LinkType::Horizontal }
LinkQuality prev_on_contour_quality { LinkQuality::Valid }
LinkQuality next_on_contour_quality { LinkQuality::Valid }
bool consumed_vertical_up { false }
bool consumed_perimeter_right { false }
Detailed Description
Member Enumeration Documentation
Direction
enum class Slic3r::SegmentIntersection::Direction strong
Enumerator
Up
Down
{
      Up,
      Down
    };
LinkQuality
enum class Slic3r::SegmentIntersection::LinkQuality : uint8_t strong
Enumerator
Invalid
Valid
TooLong
                           : uint8_t {
      Invalid,
        Valid,
      // Valid link, but too long to be followed.
      TooLong,
    };
LinkType
enum class Slic3r::SegmentIntersection::LinkType : uint8_t strong
Enumerator
Horizontal
Up
Down
Phony
                        : uint8_t {
      // Horizontal link (left or right).
      Horizontal,
      // Vertical link, up.
      Up,
      // Vertical link, down.
      Down,
        // Phony intersection point has no link.
        Phony,
    };
SegmentIntersectionType
enum Slic3r::SegmentIntersection::SegmentIntersectionType : char
Enumerator
UNKNOWN
OUTER_LOW
OUTER_HIGH
INNER_LOW
INNER_HIGH
                                 : char {
        UNKNOWN,
        OUTER_LOW,
        OUTER_HIGH,
        INNER_LOW,
        INNER_HIGH,
    };
Side
enum class Slic3r::SegmentIntersection::Side strong
Enumerator
Left
Right
                    {
      Left,
      Right
    };
Member Function Documentation
has_horizontal()
bool Slic3r::SegmentIntersection::has_horizontal (Side side) const inline
{ return side == Side::Left ? this->has_left_horizontal() : this->has_right_horizontal(); }
References has_left_horizontal(), has_right_horizontal(), and Left.
Referenced by horizontal_quality().
has_left_horizontal()
bool Slic3r::SegmentIntersection::has_left_horizontal () const inline
{ return this->prev_on_contour_type == LinkType::Horizontal; }
References Horizontal, and prev_on_contour_type.
Referenced by has_horizontal(), left_horizontal(), and Slic3r::validate_segment_intersection_connectivity().
has_left_vertical() [1/2]
bool Slic3r::SegmentIntersection::has_left_vertical () const inline
{ return this->has_left_vertical_up() || this->has_left_vertical_down(); }
References has_left_vertical_down(), and has_left_vertical_up().
Referenced by has_vertical(), has_vertical(), and left_vertical().
has_left_vertical() [2/2]
bool Slic3r::SegmentIntersection::has_left_vertical (Direction dir) const inline
{ return dir == Direction::Up ? this->has_left_vertical_up() : this->has_left_vertical_down(); }
References has_left_vertical_down(), has_left_vertical_up(), and Up.
Referenced by Slic3r::connect_segment_intersections_by_contours().
has_left_vertical_down()
bool Slic3r::SegmentIntersection::has_left_vertical_down () const inline
{ return this->prev_on_contour_type == LinkType::Down; }
References Down, and prev_on_contour_type.
Referenced by has_left_vertical(), has_left_vertical(), has_left_vertical_outside(), has_vertical_down(), left_vertical(), left_vertical_down(), vertical_down(), and vertical_down_quality().
has_left_vertical_outside()
bool Slic3r::SegmentIntersection::has_left_vertical_outside () const inline
{ return this->is_low() ? this->has_left_vertical_down() : this->has_left_vertical_up(); }
References has_left_vertical_down(), has_left_vertical_up(), and is_low().
has_left_vertical_up()
bool Slic3r::SegmentIntersection::has_left_vertical_up () const inline
{ return this->prev_on_contour_type == LinkType::Up; }
References prev_on_contour_type, and Up.
Referenced by has_left_vertical(), has_left_vertical(), has_left_vertical_outside(), has_vertical_up(), left_vertical(), left_vertical_up(), Slic3r::polylines_from_paths(), Slic3r::traverse_graph_generate_polylines(), vertical_up(), and vertical_up_quality().
has_right_horizontal()
bool Slic3r::SegmentIntersection::has_right_horizontal () const inline
{ return this->next_on_contour_type == LinkType::Horizontal; }
References Horizontal, and next_on_contour_type.
Referenced by has_horizontal(), right_horizontal(), and Slic3r::validate_segment_intersection_connectivity().
has_right_vertical() [1/2]
bool Slic3r::SegmentIntersection::has_right_vertical () const inline
{ return this->has_right_vertical_up() || this->has_right_vertical_down(); }
References has_right_vertical_down(), and has_right_vertical_up().
Referenced by has_vertical(), has_vertical(), and right_vertical().
has_right_vertical() [2/2]
bool Slic3r::SegmentIntersection::has_right_vertical (Direction dir) const inline
{ return dir == Direction::Up ? this->has_right_vertical_up() : this->has_right_vertical_down(); }
References has_right_vertical_down(), has_right_vertical_up(), and Up.
Referenced by Slic3r::connect_segment_intersections_by_contours().
has_right_vertical_down()
bool Slic3r::SegmentIntersection::has_right_vertical_down () const inline
{ return this->next_on_contour_type == LinkType::Down; }
References Down, and next_on_contour_type.
Referenced by has_right_vertical(), has_right_vertical(), has_right_vertical_outside(), has_vertical_down(), Slic3r::polylines_from_paths(), right_vertical(), right_vertical_down(), and Slic3r::traverse_graph_generate_polylines().
has_right_vertical_outside()
bool Slic3r::SegmentIntersection::has_right_vertical_outside () const inline
{ return this->is_low() ? this->has_right_vertical_down() : this->has_right_vertical_up(); }
References has_right_vertical_down(), has_right_vertical_up(), and is_low().
has_right_vertical_up()
bool Slic3r::SegmentIntersection::has_right_vertical_up () const inline
{ return this->next_on_contour_type == LinkType::Up; }
References next_on_contour_type, and Up.
Referenced by has_right_vertical(), has_right_vertical(), has_right_vertical_outside(), has_vertical_up(), right_vertical(), and right_vertical_up().
has_vertical() [1/3]
bool Slic3r::SegmentIntersection::has_vertical () const inline
{ return this->has_left_vertical() || this->has_right_vertical(); }
References has_left_vertical(), and has_right_vertical().
Referenced by Slic3r::intersection_on_prev_next_vertical_line_valid().
has_vertical() [2/3]
bool Slic3r::SegmentIntersection::has_vertical (Direction dir) const inline
{ return dir == Direction::Up ? this->has_vertical_up() : this->has_vertical_down(); }
References has_vertical_down(), has_vertical_up(), and Up.
has_vertical() [3/3]
bool Slic3r::SegmentIntersection::has_vertical (Side side) const inline
{ return side == Side::Left ? this->has_left_vertical() : this->has_right_vertical(); }
References has_left_vertical(), has_right_vertical(), and Left.
has_vertical_down()
bool Slic3r::SegmentIntersection::has_vertical_down () const inline
{ return this->has_left_vertical_down() || this->has_right_vertical_down(); }
References has_left_vertical_down(), and has_right_vertical_down().
Referenced by has_vertical().
has_vertical_up()
bool Slic3r::SegmentIntersection::has_vertical_up () const inline
{ return this->has_left_vertical_up() || this->has_right_vertical_up(); }
References has_left_vertical_up(), and has_right_vertical_up().
Referenced by has_vertical().
horizontal()
int Slic3r::SegmentIntersection::horizontal (Side side) const inline
{ return side == Side::Left ? this->left_horizontal() : this->right_horizontal(); }
References Left, left_horizontal(), and right_horizontal().
Referenced by Slic3r::intersection_on_prev_next_vertical_line_valid(), Slic3r::overlap_bottom(), and Slic3r::overlap_top().
horizontal_quality()
LinkQuality Slic3r::SegmentIntersection::horizontal_quality (Side side) const inline
{
      assert(this->has_horizontal(side));
      return side == Side::Left ? this->prev_on_contour_quality : this->next_on_contour_quality;
    }
References has_horizontal(), Left, next_on_contour_quality, and prev_on_contour_quality.
Referenced by Slic3r::intersection_on_prev_next_vertical_line_valid().
is_high()
bool Slic3r::SegmentIntersection::is_high () const inline
{ return type == INNER_HIGH || type == OUTER_HIGH; }
References INNER_HIGH, OUTER_HIGH, and type.
Referenced by Slic3r::montonous_region_path_length(), Slic3r::polylines_from_paths(), and Slic3r::traverse_graph_generate_polylines().
is_inner()
bool Slic3r::SegmentIntersection::is_inner () const inline
{ return type == INNER_LOW  || type == INNER_HIGH; }
References INNER_HIGH, INNER_LOW, and type.
Referenced by Slic3r::connect_segment_intersections_by_contours(), Slic3r::emit_perimeter_prev_next_segment(), Slic3r::emit_perimeter_segment_on_vertical_line(), Slic3r::intersection_on_prev_next_vertical_line_valid(), Slic3r::measure_perimeter_segment_on_vertical_line_length(), Slic3r::montonous_region_path_length(), Slic3r::overlap_bottom(), Slic3r::overlap_top(), Slic3r::polylines_from_paths(), Slic3r::traverse_graph_generate_polylines(), Slic3r::vertical_run_bottom(), and Slic3r::vertical_run_top().
is_low()
bool Slic3r::SegmentIntersection::is_low () const inline
{ return type == INNER_LOW  || type == OUTER_LOW; }
References INNER_LOW, OUTER_LOW, and type.
Referenced by Slic3r::connect_segment_intersections_by_contours(), Slic3r::emit_perimeter_prev_next_segment(), has_left_vertical_outside(), has_right_vertical_outside(), Slic3r::intersection_on_prev_next_vertical_line_valid(), left_vertical_outside(), Slic3r::measure_perimeter_horizontal_segment_length(), Slic3r::montonous_region_path_length(), Slic3r::polylines_from_paths(), right_vertical_outside(), Slic3r::traverse_graph_generate_polylines(), vertical_outside(), and vertical_outside_quality().
is_outer()
bool Slic3r::SegmentIntersection::is_outer () const inline
{ return type == OUTER_LOW  || type == OUTER_HIGH; }
References OUTER_HIGH, OUTER_LOW, and type.
Referenced by Slic3r::montonous_region_path_length(), Slic3r::polylines_from_paths(), and Slic3r::traverse_graph_generate_polylines().
left_horizontal()
int Slic3r::SegmentIntersection::left_horizontal () const inline
{ return this->has_left_horizontal()  ? this->prev_on_contour : -1; }
References has_left_horizontal(), and prev_on_contour.
Referenced by horizontal(), Slic3r::traverse_graph_generate_polylines(), and Slic3r::validate_segment_intersection_connectivity().
left_vertical() [1/2]
int Slic3r::SegmentIntersection::left_vertical () const inline
{ return this->has_left_vertical()     ? this->prev_on_contour : -1; }
References has_left_vertical(), and prev_on_contour.
left_vertical() [2/2]
int Slic3r::SegmentIntersection::left_vertical (Direction dir) const inline
{ return (dir == Direction::Up ? this->has_left_vertical_up() : this->has_left_vertical_down()) ? this->prev_on_contour : -1; }
References has_left_vertical_down(), has_left_vertical_up(), prev_on_contour, and Up.
Referenced by Slic3r::connect_segment_intersections_by_contours().
left_vertical_down()
int Slic3r::SegmentIntersection::left_vertical_down () const inline
{ return this->has_left_vertical_down()  ? this->prev_on_contour : -1; }
References has_left_vertical_down(), and prev_on_contour.
Referenced by left_vertical_outside(), vertical_down(), and vertical_down().
left_vertical_outside()
int Slic3r::SegmentIntersection::left_vertical_outside () const inline
{ return this->is_low() ? this->left_vertical_down() : this->left_vertical_up(); }
References is_low(), left_vertical_down(), and left_vertical_up().
Referenced by vertical_outside().
left_vertical_up()
int Slic3r::SegmentIntersection::left_vertical_up () const inline
{ return this->has_left_vertical_up()    ? this->prev_on_contour : -1; }
References has_left_vertical_up(), and prev_on_contour.
Referenced by left_vertical_outside(), vertical_up(), and vertical_up().
operator<()
bool Slic3r::SegmentIntersection::operator< (const SegmentIntersection & other) const inline
    {
        assert(pos_q > 0);
        assert(other.pos_q > 0);
        if (pos_p == 0 || other.pos_p == 0) {
            // Because the denominators are positive and one of the nominators is zero,
            // following simple statement holds.
            return pos_p < other.pos_p;
        } else {
            // None of the nominators is zero.
            int sign1 = (pos_p > 0) ? 1 : -1;
            int sign2 = (other.pos_p > 0) ? 1 : -1;
            int signs = sign1 * sign2;
            assert(signs == 1 || signs == -1);
            if (signs < 0) {
                // The nominators have different signs.
                return sign1 < 0;
            } else {
                // The nominators have the same sign.
                // Absolute values
                uint64_t p1, p2;
                if (sign1 > 0) {
                    p1 = uint64_t(pos_p);
                    p2 = uint64_t(other.pos_p);
                } else {
                    p1 = uint64_t(- pos_p);
                    p2 = uint64_t(- other.pos_p);
                };
                // Multiply low and high 32bit words of p1 by other_pos.q
                // 32bit x 32bit => 64bit
                // l_hi and l_lo overlap by 32 bits.
                uint64_t l_hi = (p1 >> 32) * uint64_t(other.pos_q);
                uint64_t l_lo = (p1 & 0xffffffffll) * uint64_t(other.pos_q);
                l_hi += (l_lo >> 32);
                uint64_t r_hi = (p2 >> 32) * uint64_t(pos_q);
                uint64_t r_lo = (p2 & 0xffffffffll) * uint64_t(pos_q);
                r_hi += (r_lo >> 32);
                // Compare the high 64 bits.
                if (l_hi == r_hi) {
                    // Compare the low 32 bits.
                    l_lo &= 0xffffffffll;
                    r_lo &= 0xffffffffll;
                    return (sign1 < 0) ? (l_lo > r_lo) : (l_lo < r_lo);
                }
                return (sign1 < 0) ? (l_hi > r_hi) : (l_hi < r_hi);
            }
        }
    }
References pos_p, and pos_q.
operator==()
bool Slic3r::SegmentIntersection::operator== (const SegmentIntersection & other) const inline
    {
        assert(pos_q > 0);
        assert(other.pos_q > 0);
        if (pos_p == 0 || other.pos_p == 0) {
            // Because the denominators are positive and one of the nominators is zero,
            // following simple statement holds.
            return pos_p == other.pos_p;
        }
        // None of the nominators is zero, none of the denominators is zero.
        bool positive = pos_p > 0;
        if (positive != (other.pos_p > 0))
            return false;
        // The nominators have the same sign.
        // Absolute values
        uint64_t p1 = positive ? uint64_t(pos_p) : uint64_t(- pos_p);
        uint64_t p2 = positive ? uint64_t(other.pos_p) : uint64_t(- other.pos_p);
        // Multiply low and high 32bit words of p1 by other_pos.q
        // 32bit x 32bit => 64bit
        // l_hi and l_lo overlap by 32 bits.
        uint64_t l_lo = (p1 & 0xffffffffll) * uint64_t(other.pos_q);
        uint64_t r_lo = (p2 & 0xffffffffll) * uint64_t(pos_q);
        if (l_lo != r_lo)
            return false;
        uint64_t l_hi = (p1 >> 32) * uint64_t(other.pos_q);
        uint64_t r_hi = (p2 >> 32) * uint64_t(pos_q);
        return l_hi + (l_lo >> 32) == r_hi + (r_lo >> 32);
    }
References pos_p, and pos_q.
pos()
coord_t Slic3r::SegmentIntersection::pos () const inline
{
        // Division rounds both positive and negative down to zero.
        // Add half of q for an arithmetic rounding effect.
        int64_t p = pos_p;
        if (p < 0)
            p -= int64_t(pos_q>>1);
        else
            p += int64_t(pos_q>>1);
        return coord_t(p / int64_t(pos_q));
    }
References pos_p, and pos_q.
Referenced by Slic3r::emit_perimeter_prev_next_segment(), Slic3r::emit_perimeter_segment_on_vertical_line(), Slic3r::measure_perimeter_horizontal_segment_length(), Slic3r::measure_perimeter_segment_on_vertical_line_length(), Slic3r::montonous_region_path_length(), Slic3r::polylines_from_paths(), Slic3r::slice_region_by_vertical_lines(), and Slic3r::traverse_graph_generate_polylines().
right_horizontal()
int Slic3r::SegmentIntersection::right_horizontal () const inline
{ return this->has_right_horizontal() ? this->next_on_contour : -1; }
References has_right_horizontal(), and next_on_contour.
Referenced by horizontal(), Slic3r::montonous_region_path_length(), Slic3r::polylines_from_paths(), Slic3r::traverse_graph_generate_polylines(), and Slic3r::validate_segment_intersection_connectivity().
right_vertical() [1/2]
int Slic3r::SegmentIntersection::right_vertical () const inline
{ return this->has_right_vertical()      ? this->next_on_contour : -1; }
References has_right_vertical(), and next_on_contour.
right_vertical() [2/2]
int Slic3r::SegmentIntersection::right_vertical (Direction dir) const inline
{ return (dir == Direction::Up ? this->has_right_vertical_up() : this->has_right_vertical_down()) ? this->next_on_contour : -1; }
References has_right_vertical_down(), has_right_vertical_up(), next_on_contour, and Up.
Referenced by Slic3r::connect_segment_intersections_by_contours().
right_vertical_down()
int Slic3r::SegmentIntersection::right_vertical_down () const inline
{ return this->has_right_vertical_down() ? this->next_on_contour : -1; }
References has_right_vertical_down(), and next_on_contour.
Referenced by right_vertical_outside(), vertical_down(), and vertical_down().
right_vertical_outside()
int Slic3r::SegmentIntersection::right_vertical_outside () const inline
{ return this->is_low() ? this->right_vertical_down() : this->right_vertical_up(); }
References is_low(), right_vertical_down(), and right_vertical_up().
Referenced by vertical_outside().
right_vertical_up()
int Slic3r::SegmentIntersection::right_vertical_up () const inline
{ return this->has_right_vertical_up()   ? this->next_on_contour : -1; }
References has_right_vertical_up(), and next_on_contour.
Referenced by right_vertical_outside(), vertical_up(), and vertical_up().
vertical_down() [1/2]
int Slic3r::SegmentIntersection::vertical_down () const inline
{
//      assert(! this->has_left_vertical_down() || ! this->has_right_vertical_down());
      return this->has_left_vertical_down() ? this->left_vertical_down() : this->right_vertical_down();
    }
References has_left_vertical_down(), left_vertical_down(), and right_vertical_down().
Referenced by vertical_outside().
vertical_down() [2/2]
int Slic3r::SegmentIntersection::vertical_down (Side side) const inline
{ return side == Side::Left ? this->left_vertical_down() : this->right_vertical_down(); }
References Left, left_vertical_down(), and right_vertical_down().
Referenced by Slic3r::montonous_region_path_length(), Slic3r::overlap_top(), Slic3r::polylines_from_paths(), and Slic3r::vertical_run_bottom().
vertical_down_quality()
LinkQuality Slic3r::SegmentIntersection::vertical_down_quality () const inline
{
      return this->has_left_vertical_down() ? this->prev_on_contour_quality : this->next_on_contour_quality;
    }
References has_left_vertical_down(), next_on_contour_quality, and prev_on_contour_quality.
Referenced by Slic3r::montonous_region_path_length(), Slic3r::overlap_top(), Slic3r::polylines_from_paths(), vertical_outside_quality(), and Slic3r::vertical_run_bottom().
vertical_outside() [1/2]
int Slic3r::SegmentIntersection::vertical_outside () const inline
{ return this->is_low() ? this->vertical_down() : this->vertical_up(); }
References is_low(), vertical_down(), and vertical_up().
vertical_outside() [2/2]
int Slic3r::SegmentIntersection::vertical_outside (Side side) const inline
{ return side == Side::Left ? this->left_vertical_outside() : this->right_vertical_outside(); }
References Left, left_vertical_outside(), and right_vertical_outside().
Referenced by Slic3r::traverse_graph_generate_polylines().
vertical_outside_quality()
LinkQuality Slic3r::SegmentIntersection::vertical_outside_quality () const inline
{ return this->is_low() ? this->vertical_down_quality() : this->vertical_up_quality(); }
References is_low(), vertical_down_quality(), and vertical_up_quality().
Referenced by Slic3r::traverse_graph_generate_polylines().
vertical_up() [1/2]
int Slic3r::SegmentIntersection::vertical_up () const inline
{
      return this->has_left_vertical_up() ? this->left_vertical_up() : this->right_vertical_up();
    }
References has_left_vertical_up(), left_vertical_up(), and right_vertical_up().
Referenced by vertical_outside().
vertical_up() [2/2]
int Slic3r::SegmentIntersection::vertical_up (Side side) const inline
{ return side == Side::Left ? this->left_vertical_up() : this->right_vertical_up(); }
References Left, left_vertical_up(), and right_vertical_up().
Referenced by Slic3r::montonous_region_path_length(), Slic3r::overlap_bottom(), Slic3r::polylines_from_paths(), and Slic3r::vertical_run_top().
vertical_up_quality()
LinkQuality Slic3r::SegmentIntersection::vertical_up_quality () const inline
{
      return this->has_left_vertical_up() ? this->prev_on_contour_quality : this->next_on_contour_quality;
    }
References has_left_vertical_up(), next_on_contour_quality, and prev_on_contour_quality.
Referenced by Slic3r::montonous_region_path_length(), Slic3r::overlap_bottom(), Slic3r::polylines_from_paths(), vertical_outside_quality(), and Slic3r::vertical_run_top().
Member Data Documentation
consumed_perimeter_right
bool Slic3r::SegmentIntersection::consumed_perimeter_right { false }
Referenced by Slic3r::intersection_on_prev_next_vertical_line_valid(), and Slic3r::traverse_graph_generate_polylines().
consumed_vertical_up
bool Slic3r::SegmentIntersection::consumed_vertical_up { false }
Referenced by Slic3r::generate_montonous_regions(), and Slic3r::traverse_graph_generate_polylines().
iContour
size_t Slic3r::SegmentIntersection::iContour { 0 }
Referenced by Slic3r::connect_segment_intersections_by_contours(), Slic3r::emit_perimeter_prev_next_segment(), Slic3r::emit_perimeter_segment_on_vertical_line(), Slic3r::end_of_vertical_run(), Slic3r::measure_perimeter_horizontal_segment_length(), Slic3r::measure_perimeter_segment_on_vertical_line_length(), Slic3r::montonous_region_path_length(), Slic3r::phony_outer_intersection(), Slic3r::polylines_from_paths(), Slic3r::slice_region_by_vertical_lines(), Slic3r::traverse_graph_generate_polylines(), and Slic3r::validate_segment_intersection_connectivity().
iSegment
size_t Slic3r::SegmentIntersection::iSegment { 0 }
Referenced by Slic3r::connect_segment_intersections_by_contours(), Slic3r::emit_perimeter_prev_next_segment(), Slic3r::emit_perimeter_segment_on_vertical_line(), Slic3r::measure_perimeter_horizontal_segment_length(), Slic3r::measure_perimeter_segment_on_vertical_line_length(), Slic3r::phony_outer_intersection(), and Slic3r::slice_region_by_vertical_lines().
next_on_contour
int32_t Slic3r::SegmentIntersection::next_on_contour { 0 }
Referenced by Slic3r::connect_segment_intersections_by_contours(), Slic3r::phony_outer_intersection(), right_horizontal(), right_vertical(), right_vertical(), right_vertical_down(), and right_vertical_up().
next_on_contour_quality
LinkQuality Slic3r::SegmentIntersection::next_on_contour_quality { LinkQuality::Valid }
Referenced by Slic3r::connect_segment_intersections_by_contours(), horizontal_quality(), Slic3r::montonous_region_path_length(), Slic3r::phony_outer_intersection(), Slic3r::polylines_from_paths(), vertical_down_quality(), and vertical_up_quality().
next_on_contour_type
LinkType Slic3r::SegmentIntersection::next_on_contour_type { LinkType::Horizontal }
Referenced by Slic3r::connect_segment_intersections_by_contours(), has_right_horizontal(), has_right_vertical_down(), has_right_vertical_up(), and Slic3r::phony_outer_intersection().
pos_p
int64_t Slic3r::SegmentIntersection::pos_p { 0 }
Referenced by operator<(), operator==(), Slic3r::phony_outer_intersection(), pos(), and Slic3r::slice_region_by_vertical_lines().
pos_q
uint32_t Slic3r::SegmentIntersection::pos_q { 1 }
Referenced by operator<(), operator==(), pos(), and Slic3r::slice_region_by_vertical_lines().
prev_on_contour
int32_t Slic3r::SegmentIntersection::prev_on_contour { 0 }
Referenced by Slic3r::connect_segment_intersections_by_contours(), left_horizontal(), left_vertical(), left_vertical(), left_vertical_down(), left_vertical_up(), and Slic3r::phony_outer_intersection().
prev_on_contour_quality
LinkQuality Slic3r::SegmentIntersection::prev_on_contour_quality { LinkQuality::Valid }
Referenced by Slic3r::connect_segment_intersections_by_contours(), horizontal_quality(), Slic3r::phony_outer_intersection(), vertical_down_quality(), and vertical_up_quality().
prev_on_contour_type
LinkType Slic3r::SegmentIntersection::prev_on_contour_type { LinkType::Horizontal }
Referenced by Slic3r::connect_segment_intersections_by_contours(), has_left_horizontal(), has_left_vertical_down(), has_left_vertical_up(), and Slic3r::phony_outer_intersection().
type
SegmentIntersectionType Slic3r::SegmentIntersection::type { UNKNOWN }
Referenced by Slic3r::connect_monotonic_regions(), Slic3r::connect_segment_intersections_by_contours(), Slic3r::emit_perimeter_prev_next_segment(), Slic3r::emit_perimeter_segment_on_vertical_line(), Slic3r::end_of_vertical_run(), Slic3r::end_of_vertical_run_raw(), is_high(), is_inner(), is_low(), is_outer(), Slic3r::measure_perimeter_horizontal_segment_length(), Slic3r::measure_perimeter_segment_on_vertical_line_length(), Slic3r::montonous_region_path_length(), Slic3r::overlap_bottom(), Slic3r::overlap_top(), Slic3r::phony_outer_intersection(), Slic3r::polylines_from_paths(), Slic3r::slice_region_by_vertical_lines(), Slic3r::traverse_graph_generate_polylines(), Slic3r::validate_segment_intersection_connectivity(), Slic3r::vertical_run_bottom(), and Slic3r::vertical_run_top().
The documentation for this struct was generated from the following file:
src/libslic3r/Fill/FillRectilinear.cpp