Prusa Slicer: Slic3r::Point Class Reference
Slic3r::Point Class Reference
#include <src/libslic3r/Point.hpp>
Public Types
using coord_type = coord_t
enum
typedef PlainObjectBase< Matrix > Base
Base class typedef.
typedef Base::PlainObject PlainObject
enum { Options = internal::traits<Derived>::Options }
enum { NeedsToAlign = (SizeAtCompileTime != Dynamic) && (internal::traits<Derived>::Alignment>0) }
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Derived DenseType
typedef Eigen::Map< Derived, Unaligned > MapType
typedef const Eigen::Map< const Derived, Unaligned > ConstMapType
typedef Eigen::Map< Derived, AlignedMax > AlignedMapType
typedef const Eigen::Map< const Derived, AlignedMax > ConstAlignedMapType
Public Member Functions
Point ()
Point (int32_t x, int32_t y)
Point (int64_t x, int64_t y)
Point (double x, double y)
Point (const Point &rhs)
Point (const Vec2d &rhs)
template<typename OtherDerived >
Point (const Eigen::MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Point & operator= (const Eigen::MatrixBase< OtherDerived > &other)
Point & operator+= (const Point &rhs)
Point & operator-= (const Point &rhs)
Point & operator*= (const double &rhs)
Point operator* (const double &rhs)
void rotate (double angle)
void rotate (double cos_a, double sin_a)
void rotate (double angle, const Point &center)
Point rotated (double angle) const
Point rotated (double cos_a, double sin_a) const
Point rotated (double angle, const Point &center) const
EIGEN_DEVICE_FUNC Index innerStride () const
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Base & base ()
EIGEN_DEVICE_FUNC const Base & base () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index rowId, Index colId)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeffRef (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeffRef (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rows () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index cols () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeff (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & coeff (Index index) const
template<int LoadMode>
EIGEN_STRONG_INLINE PacketScalar packet (Index rowId, Index colId) const
template<int LoadMode>
EIGEN_STRONG_INLINE PacketScalar packet (Index index) const
template<int StoreMode>
EIGEN_STRONG_INLINE void writePacket (Index rowId, Index colId, const PacketScalar &val)
template<int StoreMode>
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketScalar &val)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar * data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar * data ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC void resize (Index size)
EIGEN_DEVICE_FUNC void resize (NoChange_t, Index cols)
EIGEN_DEVICE_FUNC void resize (Index rows, NoChange_t)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void resizeLike (const EigenBase< OtherDerived > &_other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResize (Index rows, Index cols)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResize (Index rows, NoChange_t)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResize (NoChange_t, Index cols)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResize (Index size)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void conservativeResizeLike (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
Static Public Member Functions
static Point new_scale (coordf_t x, coordf_t y)
static Point new_scale (const Vec2d &v)
static Point new_scale (const Vec2f &v)
Protected Attributes
DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options > m_storage
Map
These are convenience functions returning Map objects. The Map() static functions return unaligned Map objects, while the AlignedMap() functions return aligned Map objects and thus should be called only with 16-byte-aligned data pointers.
Here is an example using strides:
Output:
See also
class Map
enum { IsPlainObjectBase = 1 }
EIGEN_DEVICE_FUNC Derived & setConstant (Index size, const Scalar &val)
EIGEN_DEVICE_FUNC Derived & setConstant (Index rows, Index cols, const Scalar &val)
EIGEN_DEVICE_FUNC Derived & setZero (Index size)
EIGEN_DEVICE_FUNC Derived & setZero (Index rows, Index cols)
EIGEN_DEVICE_FUNC Derived & setOnes (Index size)
EIGEN_DEVICE_FUNC Derived & setOnes (Index rows, Index cols)
Derived & setRandom (Index size)
Derived & setRandom (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (DenseBase< OtherDerived > const &other)
static ConstMapType Map (const Scalar *data)
static MapType Map (Scalar *data)
static ConstMapType Map (const Scalar *data, Index size)
static MapType Map (Scalar *data, Index size)
static ConstMapType Map (const Scalar *data, Index rows, Index cols)
static MapType Map (Scalar *data, Index rows, Index cols)
template<int Outer, int Inner>
static StridedConstMapType< Stride< Outer, Inner > >::type Map (const Scalar *data, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedMapType< Stride< Outer, Inner > >::type Map (Scalar *data, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedConstMapType< Stride< Outer, Inner > >::type Map (const Scalar *data, Index size, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedMapType< Stride< Outer, Inner > >::type Map (Scalar *data, Index size, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedConstMapType< Stride< Outer, Inner > >::type Map (const Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedMapType< Stride< Outer, Inner > >::type Map (Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
static ConstAlignedMapType MapAligned (const Scalar *data)
static AlignedMapType MapAligned (Scalar *data)
static ConstAlignedMapType MapAligned (const Scalar *data, Index size)
static AlignedMapType MapAligned (Scalar *data, Index size)
static ConstAlignedMapType MapAligned (const Scalar *data, Index rows, Index cols)
static AlignedMapType MapAligned (Scalar *data, Index rows, Index cols)
template<int Outer, int Inner>
static StridedConstAlignedMapType< Stride< Outer, Inner > >::type MapAligned (const Scalar *data, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedAlignedMapType< Stride< Outer, Inner > >::type MapAligned (Scalar *data, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedConstAlignedMapType< Stride< Outer, Inner > >::type MapAligned (const Scalar *data, Index size, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedAlignedMapType< Stride< Outer, Inner > >::type MapAligned (Scalar *data, Index size, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedConstAlignedMapType< Stride< Outer, Inner > >::type MapAligned (const Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedAlignedMapType< Stride< Outer, Inner > >::type MapAligned (Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _check_template_params ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _resize_to_match (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & _set (const DenseBase< OtherDerived > &other)
Copies the value of the expression other into *this with automatic resizing.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & _set_noalias (const DenseBase< OtherDerived > &other)
template<typename T0 , typename T1 >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init2 (Index rows, Index cols, typename internal::enable_if< Base::SizeAtCompileTime!=2, T0 >::type *=0)
template<typename T0 , typename T1 >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init2 (const T0 &val0, const T1 &val1, typename internal::enable_if< Base::SizeAtCompileTime==2, T0 >::type *=0)
template<typename T0 , typename T1 >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init2 (const Index &val0, const Index &val1, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< T0, Index >::value) &&(internal::is_same< T1, Index >::value) &&Base::SizeAtCompileTime==2, T1 >::type *=0)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (Index size, typename internal::enable_if<(Base::SizeAtCompileTime!=1||!internal::is_convertible< T, Scalar >::value) &&((!internal::is_same< typename internal::traits< Derived >::XprKind, ArrayXpr >::value||Base::SizeAtCompileTime==Dynamic)), T >::type *=0)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Scalar &val0, typename internal::enable_if< Base::SizeAtCompileTime==1 &&internal::is_convertible< T, Scalar >::value, T >::type *=0)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Index &val0, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< Index, T >::value) &&Base::SizeAtCompileTime==1 &&internal::is_convertible< T, Scalar >::value, T * >::type *=0)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Scalar *data)
template<typename T , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const DenseBase< OtherDerived > &other)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Derived &other)
template<typename T , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const EigenBase< OtherDerived > &other)
template<typename T , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const ReturnByValue< OtherDerived > &other)
template<typename T , typename OtherDerived , int ColsAtCompileTime>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const RotationBase< OtherDerived, ColsAtCompileTime > &r)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Scalar &val0, typename internal::enable_if< Base::SizeAtCompileTime!=Dynamic &&Base::SizeAtCompileTime!=1 &&internal::is_convertible< T, Scalar >::value &&internal::is_same< typename internal::traits< Derived >::XprKind, ArrayXpr >::value, T >::type *=0)
template<typename T >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _init1 (const Index &val0, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< Index, T >::value) &&Base::SizeAtCompileTime!=Dynamic &&Base::SizeAtCompileTime!=1 &&internal::is_convertible< T, Scalar >::value &&internal::is_same< typename internal::traits< Derived >::XprKind, ArrayXpr >::value, T * >::type *=0)
Detailed Description
Member Typedef Documentation
AlignedMapType
template<typename Derived > typedef Eigen::Map<Derived, AlignedMax> Eigen::PlainObjectBase< Derived >::AlignedMapType inherited
Base
typedef PlainObjectBase<Matrix> Eigen::Matrix< coord_t , _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Base inherited
Base class typedef.
See also
PlainObjectBase
ConstAlignedMapType
template<typename Derived > typedef const Eigen::Map<const Derived, AlignedMax> Eigen::PlainObjectBase< Derived >::ConstAlignedMapType inherited
ConstMapType
template<typename Derived > typedef const Eigen::Map<const Derived, Unaligned> Eigen::PlainObjectBase< Derived >::ConstMapType inherited
coord_type
using Slic3r::Point::coord_type = coord_t
DenseType
template<typename Derived > typedef Derived Eigen::PlainObjectBase< Derived >::DenseType inherited
MapType
template<typename Derived > typedef Eigen::Map<Derived, Unaligned> Eigen::PlainObjectBase< Derived >::MapType inherited
PacketScalar
template<typename Derived > typedef internal::packet_traits<Scalar>::type Eigen::PlainObjectBase< Derived >::PacketScalar inherited
PlainObject
typedef Base::PlainObject Eigen::Matrix< coord_t , _Rows, _Cols, _Options, _MaxRows, _MaxCols >::PlainObject inherited
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::PlainObjectBase< Derived >::RealScalar inherited
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::PlainObjectBase< Derived >::Scalar inherited
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::PlainObjectBase< Derived >::StorageKind inherited
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
{ Options = _Options };
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
Options
{ Options = internal::traits<Derived>::Options };
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
NeedsToAlign
{ NeedsToAlign = (SizeAtCompileTime != Dynamic) && (internal::traits<Derived>::Alignment>0) };
anonymous enum
template<typename Derived > anonymous enum inherited
Enumerator
IsPlainObjectBase
{ IsPlainObjectBase = 1 };
Constructor & Destructor Documentation
Point() [1/7]
Slic3r::Point::Point () inline
: Vec2crd(0, 0) {}
Referenced by new_scale(), new_scale(), new_scale(), and operator*().
Point() [2/7]
Slic3r::Point::Point (int32_t x, int32_t y) inline
: Vec2crd(coord_t(x), coord_t(y)) {}
Point() [3/7]
Slic3r::Point::Point (int64_t x, int64_t y) inline
: Vec2crd(coord_t(x), coord_t(y)) {}
Point() [4/7]
Slic3r::Point::Point (double x, double y) inline
: Vec2crd(coord_t(std::round(x)), coord_t(std::round(y))) {}
Point() [5/7]
Slic3r::Point::Point (const Point & rhs) inline
{ *this = rhs; }
Point() [6/7]
Slic3r::Point::Point (const Vec2d & rhs) inline explicit
: Vec2crd(coord_t(std::round(rhs.x())), coord_t(std::round(rhs.y()))) {}
Point() [7/7]
template<typename OtherDerived > Slic3r::Point::Point (const Eigen::MatrixBase< OtherDerived > & other) inline
: Vec2crd(other) {}
Member Function Documentation
_check_template_params()
template<typename Derived > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_check_template_params () inline static inherited
    {
      EIGEN_STATIC_ASSERT((EIGEN_IMPLIES(MaxRowsAtCompileTime==1 && MaxColsAtCompileTime!=1, (Options&RowMajor)==RowMajor)
                        && EIGEN_IMPLIES(MaxColsAtCompileTime==1 && MaxRowsAtCompileTime!=1, (Options&RowMajor)==0)
                        && ((RowsAtCompileTime == Dynamic) || (RowsAtCompileTime >= 0))
                        && ((ColsAtCompileTime == Dynamic) || (ColsAtCompileTime >= 0))
                        && ((MaxRowsAtCompileTime == Dynamic) || (MaxRowsAtCompileTime >= 0))
                        && ((MaxColsAtCompileTime == Dynamic) || (MaxColsAtCompileTime >= 0))
                        && (MaxRowsAtCompileTime == RowsAtCompileTime || RowsAtCompileTime==Dynamic)
                        && (MaxColsAtCompileTime == ColsAtCompileTime || ColsAtCompileTime==Dynamic)
                        && (Options & (DontAlign|RowMajor)) == Options),
        INVALID_MATRIX_TEMPLATE_PARAMETERS)
    }
References Eigen::DontAlign, Eigen::Dynamic, EIGEN_IMPLIES, EIGEN_STATIC_ASSERT, Eigen::PlainObjectBase< Derived >::Options, and Eigen::RowMajor.
Referenced by Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array(), Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array(), Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array(), Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array(), Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array(), Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::Array(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), and Eigen::PlainObjectBase< Derived >::PlainObjectBase().
_init1() [1/11]
template<typename Derived > template<typename T , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const DenseBase< OtherDerived > & other) inline protected inherited
{
      this->_set_noalias(other);
    }
References Eigen::PlainObjectBase< Derived >::_set_noalias().
_init1() [2/11]
template<typename Derived > template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const Derived & other) inline protected inherited
{
      this->_set_noalias(other);
    }
References Eigen::PlainObjectBase< Derived >::_set_noalias().
_init1() [3/11]
template<typename Derived > template<typename T , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const EigenBase< OtherDerived > & other) inline protected inherited
{
      this->derived() = other;
    }
_init1() [4/11]
template<typename Derived > template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const Index & val0, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< Index, T >::value) &&Base::SizeAtCompileTime!=Dynamic &&Base::SizeAtCompileTime!=1 &&internal::is_convertible< T, Scalar >::value &&internal::is_same< typename internal::traits< Derived >::XprKind, ArrayXpr >::value, T * >::type * = 0) inline protected inherited
    {
      Base::setConstant(val0);
    }
_init1() [5/11]
template<typename Derived > template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const Index & val0, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< Index, T >::value) &&Base::SizeAtCompileTime==1 &&internal::is_convertible< T, Scalar >::value, T * >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(PlainObjectBase, 1)
      m_storage.data()[0] = Scalar(val0);
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::PlainObjectBase< Derived >::m_storage.
_init1() [6/11]
template<typename Derived > template<typename T , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const ReturnByValue< OtherDerived > & other) inline protected inherited
    {
      resize(other.rows(), other.cols());
      other.evalTo(this->derived());
    }
References Eigen::ReturnByValue< Derived >::cols(), Eigen::ReturnByValue< Derived >::evalTo(), Eigen::PlainObjectBase< Derived >::resize(), and Eigen::ReturnByValue< Derived >::rows().
_init1() [7/11]
template<typename Derived > template<typename T , typename OtherDerived , int ColsAtCompileTime> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const RotationBase< OtherDerived, ColsAtCompileTime > & r) inline protected inherited
    {
      this->derived() = r;
    }
_init1() [8/11]
template<typename Derived > template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const Scalar & val0, typename internal::enable_if< Base::SizeAtCompileTime!=Dynamic &&Base::SizeAtCompileTime!=1 &&internal::is_convertible< T, Scalar >::value &&internal::is_same< typename internal::traits< Derived >::XprKind, ArrayXpr >::value, T >::type * = 0) inline protected inherited
    {
      Base::setConstant(val0);
    }
_init1() [9/11]
template<typename Derived > template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const Scalar & val0, typename internal::enable_if< Base::SizeAtCompileTime==1 &&internal::is_convertible< T, Scalar >::value, T >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(PlainObjectBase, 1)
      m_storage.data()[0] = val0;
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::PlainObjectBase< Derived >::m_storage.
_init1() [10/11]
template<typename Derived > template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (const Scalar * data) inline protected inherited
{
      this->_set_noalias(ConstMapType(data));
    }
References Eigen::PlainObjectBase< Derived >::_set_noalias().
_init1() [11/11]
template<typename Derived > template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init1 (Index size, typename internal::enable_if<(Base::SizeAtCompileTime!=1||!internal::is_convertible< T, Scalar >::value) &&((!internal::is_same< typename internal::traits< Derived >::XprKind, ArrayXpr >::value||Base::SizeAtCompileTime==Dynamic)), T >::type * = 0) inline protected inherited
    {
      // NOTE MSVC 2008 complains if we directly put bool(NumTraits<T>::IsInteger) as the EIGEN_STATIC_ASSERT argument.
      const bool is_integer = NumTraits<T>::IsInteger;
      EIGEN_UNUSED_VARIABLE(is_integer);
      EIGEN_STATIC_ASSERT(is_integer,
                          FLOATING_POINT_ARGUMENT_PASSED__INTEGER_WAS_EXPECTED)
      resize(size);
    }
References EIGEN_STATIC_ASSERT, EIGEN_UNUSED_VARIABLE, and Eigen::PlainObjectBase< Derived >::resize().
_init2() [1/3]
template<typename Derived > template<typename T0 , typename T1 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init2 (const Index & val0, const Index & val1, typename internal::enable_if<(!internal::is_same< Index, Scalar >::value) &&(internal::is_same< T0, Index >::value) &&(internal::is_same< T1, Index >::value) &&Base::SizeAtCompileTime==2, T1 >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(PlainObjectBase, 2)
      m_storage.data()[0] = Scalar(val0);
      m_storage.data()[1] = Scalar(val1);
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::PlainObjectBase< Derived >::m_storage.
_init2() [2/3]
template<typename Derived > template<typename T0 , typename T1 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init2 (const T0 & val0, const T1 & val1, typename internal::enable_if< Base::SizeAtCompileTime==2, T0 >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(PlainObjectBase, 2)
      m_storage.data()[0] = Scalar(val0);
      m_storage.data()[1] = Scalar(val1);
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::PlainObjectBase< Derived >::m_storage.
_init2() [3/3]
template<typename Derived > template<typename T0 , typename T1 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init2 (Index rows, Index cols, typename internal::enable_if< Base::SizeAtCompileTime!=2, T0 >::type * = 0) inline protected inherited
    {
      EIGEN_STATIC_ASSERT(bool(NumTraits<T0>::IsInteger) &&
                          bool(NumTraits<T1>::IsInteger),
                          FLOATING_POINT_ARGUMENT_PASSED__INTEGER_WAS_EXPECTED)
      resize(rows,cols);
    }
References Eigen::PlainObjectBase< Derived >::cols(), EIGEN_STATIC_ASSERT, Eigen::PlainObjectBase< Derived >::resize(), and Eigen::PlainObjectBase< Derived >::rows().
_resize_to_match()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_resize_to_match (const EigenBase< OtherDerived > & other) inline protected inherited
    {
      #ifdef EIGEN_NO_AUTOMATIC_RESIZING
      eigen_assert((this->size()==0 || (IsVectorAtCompileTime ? (this->size() == other.size())
                 : (rows() == other.rows() && cols() == other.cols())))
        && "Size mismatch. Automatic resizing is disabled because EIGEN_NO_AUTOMATIC_RESIZING is defined");
      EIGEN_ONLY_USED_FOR_DEBUG(other);
      #else
      resizeLike(other);
      #endif
    }
References Eigen::EigenBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::cols(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, Eigen::PlainObjectBase< Derived >::resizeLike(), Eigen::EigenBase< Derived >::rows(), Eigen::PlainObjectBase< Derived >::rows(), and Eigen::EigenBase< Derived >::size().
Referenced by Eigen::PlainObjectBase< Derived >::lazyAssign(), and Eigen::PlainObjectBase< Derived >::operator=().
_set()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::_set (const DenseBase< OtherDerived > & other) inline protected inherited
Copies the value of the expression other into *this with automatic resizing.
*this might be resized to match the dimensions of other. If *this was a null matrix (not already initialized), it will be initialized.
Note that copying a row-vector into a vector (and conversely) is allowed. The resizing, if any, is then done in the appropriate way so that row-vectors remain row-vectors and vectors remain vectors.
See also
operator=(const MatrixBase<OtherDerived>&), _set_noalias()
    {
      internal::call_assignment(this->derived(), other.derived());
      return this->derived();
    }
References Eigen::internal::call_assignment().
Referenced by Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::operator=(), Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::operator=(), and Eigen::PlainObjectBase< Derived >::operator=().
_set_noalias()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::_set_noalias (const DenseBase< OtherDerived > & other) inline protected inherited
    {
      // I don't think we need this resize call since the lazyAssign will anyways resize
      // and lazyAssign will be called by the assign selector.
      //_resize_to_match(other);
      // the 'false' below means to enforce lazy evaluation. We don't use lazyAssign() because
      // it wouldn't allow to copy a row-vector into a column-vector.
      internal::call_assignment_no_alias(this->derived(), other.derived(), internal::assign_op<Scalar,typename OtherDerived::Scalar>());
      return this->derived();
    }
References Eigen::internal::call_assignment_no_alias().
Referenced by Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::PlainObjectBase< Derived >::_init1(), Eigen::PlainObjectBase< Derived >::_init1(), and Eigen::PlainObjectBase< Derived >::_init1().
base() [1/2]
EIGEN_DEVICE_FUNC Base & Eigen::PlainObjectBase< Derived >::base () inline inherited
{ return *static_cast<Base*>(this); }
base() [2/2]
EIGEN_DEVICE_FUNC const Base & Eigen::PlainObjectBase< Derived >::base () const inline inherited
{ return *static_cast<const Base*>(this); }
coeff() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & Eigen::PlainObjectBase< Derived >::coeff (Index index) const inline inherited
This is an overloaded version of DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index) const for details.
    {
      return m_storage.data()[index];
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), and Eigen::PlainObjectBase< Derived >::m_storage.
coeff() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & Eigen::PlainObjectBase< Derived >::coeff (Index rowId, Index colId) const inline inherited
This is an overloaded version of DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index,Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,ReadOnlyAccessors>::coeff(Index) const for details.
    {
      if(Flags & RowMajorBit)
        return m_storage.data()[colId + rowId * m_storage.cols()];
      else // column-major
        return m_storage.data()[rowId + colId * m_storage.rows()];
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::cols(), Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), Eigen::PlainObjectBase< Derived >::m_storage, Eigen::RowMajorBit, and Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::rows().
Referenced by Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::ComplexSchur< _MatrixType >::computeShift(), Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::internal::image_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::RealSchur< _MatrixType >::initFrancisQRStep(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::intersection(), Eigen::Hyperplane< _Scalar, _AmbientDim, _Options >::offset(), Eigen::internal::real_2x2_jacobi_svd(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::RealQZ< _MatrixType >::step(), and Eigen::ComplexSchur< _MatrixType >::subdiagonalEntryIsNeglegible().
coeffRef() [1/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::PlainObjectBase< Derived >::coeffRef (Index index) inline inherited
This is an overloaded version of DenseCoeffsBase<Derived,WriteAccessors>::coeffRef(Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,WriteAccessors>::coeffRef(Index) const for details.
    {
      return m_storage.data()[index];
    }
coeffRef() [2/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & Eigen::PlainObjectBase< Derived >::coeffRef (Index index) const inline inherited
This is the const version of coeffRef(Index) which is thus synonym of coeff(Index). It is provided for convenience.
    {
      return m_storage.data()[index];
    }
coeffRef() [3/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & Eigen::PlainObjectBase< Derived >::coeffRef (Index rowId, Index colId) inline inherited
This is an overloaded version of DenseCoeffsBase<Derived,WriteAccessors>::coeffRef(Index,Index) const provided to by-pass the creation of an evaluator of the expression, thus saving compilation efforts.
See DenseCoeffsBase<Derived,WriteAccessors>::coeffRef(Index,Index) const for details.
    {
      if(Flags & RowMajorBit)
        return m_storage.data()[colId + rowId * m_storage.cols()];
      else // column-major
        return m_storage.data()[rowId + colId * m_storage.rows()];
    }
coeffRef() [4/4]
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar & Eigen::PlainObjectBase< Derived >::coeffRef (Index rowId, Index colId) const inline inherited
This is the const version of coeffRef(Index,Index) which is thus synonym of coeff(Index,Index). It is provided for convenience.
    {
      if(Flags & RowMajorBit)
        return m_storage.data()[colId + rowId * m_storage.cols()];
      else // column-major
        return m_storage.data()[rowId + colId * m_storage.rows()];
    }
cols()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::PlainObjectBase< Derived >::cols () const inline inherited
{ return m_storage.cols(); }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::cols(), and Eigen::PlainObjectBase< Derived >::m_storage.
Referenced by MarchingCubes< Derivedvalues, Derivedpoints, Derivedvertices, DerivedF >::MarchingCubes(), Eigen::PlainObjectBase< Derived >::_init2(), Eigen::PlainObjectBase< Derived >::_resize_to_match(), igl::active_set(), igl::arap_linear_block_elements(), igl::arap_linear_block_spokes(), igl::arap_linear_block_spokes_and_rims(), igl::arap_precomputation(), igl::arap_solve(), igl::average_onto_faces(), Eigen::internal::bicgstab(), igl::biharmonic_coordinates(), igl::opengl::bind_vertex_attrib_array(), igl::boundary_facets(), igl::copyleft::cgal::CSGTree::cast_V(), igl::triangle::cdt(), igl::copyleft::tetgen::cdt(), igl::copyleft::cgal::closest_facet(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cols(), igl::columnize(), Eigen::BDCSVD< _MatrixType >::computeSVDofM(), Eigen::internal::conjugate_gradient(), igl::connect_boundary_to_infinity(), igl::connect_boundary_to_infinity(), Eigen::PlainObjectBase< Derived >::conservativeResize(), Eigen::PlainObjectBase< Derived >::conservativeResize(), Eigen::PlainObjectBase< Derived >::conservativeResize(), igl::cross(), igl::delaunay_triangulation(), igl::dihedral_angles(), igl::dot_row(), igl::dqs(), igl::opengl::ViewerCore::draw_buffer(), igl::opengl2::draw_skeleton_3d(), igl::opengl2::draw_skeleton_vector_graphics(), igl::copyleft::cgal::extract_feature(), igl::fast_winding_number(), igl::matlab::MatlabWorkspace::find(), igl::fit_rotations(), igl::fit_rotations_planar(), igl::flipped_triangles(), igl::serialization::getByteSize(), grad_tet(), igl::hausdorff(), igl::hsv_to_rgb(), igl::AABB< DerivedV, DIM >::init(), igl::is_symmetric(), igl::ismember(), Eigen::internal::llt_rank_update_lower(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), igl::massmatrix(), igl::WindingNumberAABB< Point, DerivedV, DerivedF >::max_simple_abs_winding_number(), igl::min_quad_dense_precompute(), igl::min_quad_with_fixed_solve(), igl::copyleft::cgal::minkowski_sum(), igl::copyleft::cgal::minkowski_sum(), igl::matlab::mlgetmatrix(), igl::matlab::mlsetmatrix(), igl::mod(), igl::normal_derivative(), igl::null(), igl::copyleft::cgal::order_facets_around_edge(), igl::orient_outward(), igl::copyleft::cgal::peel_outer_hull_layers(), igl::per_vertex_attribute_smoothing(), igl::copyleft::cgal::point_mesh_squared_distance(), igl::point_mesh_squared_distance(), igl::copyleft::cgal::point_mesh_squared_distance_precompute(), igl::polar_dec(), igl::polar_svd(), igl::matlab::prepare_lhs_double(), igl::matlab::prepare_lhs_logical(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), igl::copyleft::cgal::remesh_intersections(), igl::remove_duplicates(), igl::embree::reorient_facets_raycast(), igl::repdiag(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::resize(), igl::copyleft::cgal::resolve_intersections(), igl::rgb_to_hsv(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rows(), Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), igl::matlab::MatlabWorkspace::save(), igl::seam_edges(), igl::xml::serialization_xml::serialize(), igl::serialization::serialize(), igl::opengl::ViewerData::set_texture(), igl::snap_points(), igl::snap_points(), igl::sort_angles(), igl::sort_vectors_ccw(), igl::sort_vectors_ccw(), igl::sort_vectors_ccw(), igl::sort_vectors_ccw(), igl::sparse(), igl::straighten_seams(), igl::copyleft::cgal::subdivide_segments(), Eigen::DenseBase< Derived >::swap(), igl::copyleft::cork::to_cork_mesh(), igl::transpose_blocks(), igl::triangle_triangle_adjacency(), igl::upsample(), igl::opengl::vertex_array(), igl::writeOFF(), igl::writeOFF(), igl::png::writePNG(), and igl::writeWRL().
conservativeResize() [1/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResize (Index rows, Index cols) inline inherited
Resizes the matrix to rows x cols while leaving old values untouched.
The method is intended for matrices of dynamic size. If you only want to change the number of rows and/or of columns, you can use conservativeResize(NoChange_t, Index) or conservativeResize(Index, NoChange_t).
Matrices are resized relative to the top-left element. In case values need to be appended to the matrix they will be uninitialized.
    {
      internal::conservative_resize_like_impl<Derived>::run(*this, rows, cols);
    }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::rows(), and Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
Referenced by MarchingCubes< Derivedvalues, Derivedpoints, Derivedvertices, DerivedF >::MarchingCubes(), MarchingCubes< Derivedvalues, Derivedpoints, Derivedvertices, DerivedF >::add_vertex(), Eigen::PlainObjectBase< Derived >::conservativeResize(), Eigen::PlainObjectBase< Derived >::conservativeResize(), igl::cut_mesh(), igl::edges_to_path(), igl::WindingNumberAABB< Point, DerivedV, DerivedF >::max_simple_abs_winding_number(), igl::ramer_douglas_peucker(), igl::remove_duplicates(), igl::embree::reorient_facets_raycast(), igl::seam_edges(), igl::shapeup_identity_projection(), igl::shapeup_regular_face_projection(), and igl::shapeup_solve().
conservativeResize() [2/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResize (Index rows, NoChange_t) inline inherited
Resizes the matrix to rows x cols while leaving old values untouched.
As opposed to conservativeResize(Index rows, Index cols), this version leaves the number of columns unchanged.
In case the matrix is growing, new rows will be uninitialized.
    {
      // Note: see the comment in conservativeResize(Index,Index)
      conservativeResize(rows, cols());
    }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::conservativeResize(), and Eigen::PlainObjectBase< Derived >::rows().
conservativeResize() [3/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResize (Index size) inline inherited
Resizes the vector to size while retaining old values.
\only_for_vectors. This method does not work for partially dynamic matrices when the static dimension is anything other than 1. For example it will not work with Matrix<double, 2, Dynamic>.
When values are appended, they will be uninitialized.
    {
      internal::conservative_resize_like_impl<Derived>::run(*this, size);
    }
References Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
conservativeResize() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResize (NoChange_t , Index cols) inline inherited
Resizes the matrix to rows x cols while leaving old values untouched.
As opposed to conservativeResize(Index rows, Index cols), this version leaves the number of rows unchanged.
In case the matrix is growing, new columns will be uninitialized.
    {
      // Note: see the comment in conservativeResize(Index,Index)
      conservativeResize(rows(), cols);
    }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::conservativeResize(), and Eigen::PlainObjectBase< Derived >::rows().
conservativeResizeLike()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResizeLike (const DenseBase< OtherDerived > & other) inline inherited
Resizes the matrix to rows x cols of other, while leaving old values untouched.
The method is intended for matrices of dynamic size. If you only want to change the number of rows and/or of columns, you can use conservativeResize(NoChange_t, Index) or conservativeResize(Index, NoChange_t).
Matrices are resized relative to the top-left element. In case values need to be appended to the matrix they will copied from other.
    {
      internal::conservative_resize_like_impl<Derived,OtherDerived>::run(*this, other);
    }
References Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
data() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar * Eigen::PlainObjectBase< Derived >::data () inline inherited
Returns
a pointer to the data array of this matrix
    { return m_storage.data(); }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), and Eigen::PlainObjectBase< Derived >::m_storage.
data() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Scalar * Eigen::PlainObjectBase< Derived >::data () const inline inherited
Returns
a const pointer to the data array of this matrix
    { return m_storage.data(); }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), and Eigen::PlainObjectBase< Derived >::m_storage.
Referenced by igl::copyleft::cgal::CSGTree::CSGTree(), Eigen::PardisoImpl< Derived >::_solve_impl(), Eigen::UmfPackLU< _MatrixType >::_solve_impl(), igl::active_set(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Slic3r::GUI::GLModel::Geometry::add_vertex(), Eigen::UmfPackLU< _MatrixType >::analyzePattern_impl(), Eigen::begin(), Eigen::begin(), igl::opengl::bind_vertex_attrib_array(), Eigen::PastixBase< Derived >::clean(), Eigen::internal::UpperBidiagonalization< _MatrixType >::computeUnblocked(), igl::opengl::create_vector_vbo(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data(), igl::serialization::deserialize(), igl::opengl2::draw_mesh(), Eigen::end(), Eigen::end(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::UmfPackLU< _MatrixType >::factorize_impl(), igl::fast_winding_number(), igl::fast_winding_number(), Eigen::UmfPackLU< _MatrixType >::init(), igl::copyleft::cgal::intersect_with_half_space(), igl::ismember(), Slic3r::GUI::ObjectList::load_modifier(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::MetisOrdering< StorageIndex >::operator()(), Eigen::COLAMDOrdering< StorageIndex >::operator()(), Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, UpLo >::operator()(), igl::copyleft::cgal::outer_edge(), igl::outer_edge(), igl::copyleft::cgal::outer_facet(), igl::copyleft::cgal::outer_vertex(), igl::outer_vertex(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::panel_bmod(), Eigen::PardisoImpl< Derived >::pardisoRelease(), igl::copyleft::cgal::peel_outer_hull_layers(), igl::randperm(), Slic3r::GUI::GCodeViewer::refresh_render_paths(), igl::copyleft::cgal::remesh_intersections(), igl::remove_unreferenced(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), igl::resolve_duplicated_faces(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), igl::serialization::serialize(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::set_uniform(), Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::setInfos(), igl::slice_tets(), igl::copyleft::cgal::snap_rounding(), igl::sort_angles(), Eigen::RealQZ< _MatrixType >::step(), igl::straighten_seams(), Slic3r::transform(), Eigen::UmfPackLU< _MatrixType >::umfpackReportControl(), Eigen::UmfPackLU< _MatrixType >::umfpackReportInfo(), Eigen::UmfPackLU< _MatrixType >::umfpackReportStatus(), igl::opengl2::unproject_to_zero_plane(), Slic3r::GCode::PlaceholderParserIntegration::update_from_gcodewriter(), and igl::opengl::vertex_array().
innerStride()
EIGEN_DEVICE_FUNC Index Eigen::Matrix< coord_t , _Rows, _Cols, _Options, _MaxRows, _MaxCols >::innerStride () const inline inherited
{ return 1; }
lazyAssign()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other) inline inherited
See also
MatrixBase::lazyAssign()
    {
      _resize_to_match(other);
      return Base::lazyAssign(other.derived());
    }
References Eigen::PlainObjectBase< Derived >::_resize_to_match().
Map() [1/12]
template<typename Derived > static ConstMapType Eigen::PlainObjectBase< Derived >::Map (const Scalar * data) inline static inherited
    { return ConstMapType(data); }
References Eigen::PlainObjectBase< Derived >::data().
Map() [2/12]
template<typename Derived > template<int Outer, int Inner> static StridedConstMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstMapType<Stride<Outer, Inner> >::type(data, stride); }
References Eigen::PlainObjectBase< Derived >::data().
Map() [3/12]
template<typename Derived > static ConstMapType Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, Index rows, Index cols) inline static inherited
    { return ConstMapType(data, rows, cols); }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), and Eigen::PlainObjectBase< Derived >::rows().
Map() [4/12]
template<typename Derived > template<int Outer, int Inner> static StridedConstMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstMapType<Stride<Outer, Inner> >::type(data, rows, cols, stride); }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), and Eigen::PlainObjectBase< Derived >::rows().
Map() [5/12]
template<typename Derived > static ConstMapType Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, Index size) inline static inherited
    { return ConstMapType(data, size); }
References Eigen::PlainObjectBase< Derived >::data().
Map() [6/12]
template<typename Derived > template<int Outer, int Inner> static StridedConstMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstMapType<Stride<Outer, Inner> >::type(data, size, stride); }
References Eigen::PlainObjectBase< Derived >::data().
Map() [7/12]
template<typename Derived > static MapType Eigen::PlainObjectBase< Derived >::Map (Scalar * data) inline static inherited
    { return MapType(data); }
References Eigen::PlainObjectBase< Derived >::data().
Map() [8/12]
template<typename Derived > template<int Outer, int Inner> static StridedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::Map (Scalar * data, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedMapType<Stride<Outer, Inner> >::type(data, stride); }
References Eigen::PlainObjectBase< Derived >::data().
Map() [9/12]
template<typename Derived > static MapType Eigen::PlainObjectBase< Derived >::Map (Scalar * data, Index rows, Index cols) inline static inherited
    { return MapType(data, rows, cols); }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), and Eigen::PlainObjectBase< Derived >::rows().
Map() [10/12]
template<typename Derived > template<int Outer, int Inner> static StridedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::Map (Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedMapType<Stride<Outer, Inner> >::type(data, rows, cols, stride); }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), and Eigen::PlainObjectBase< Derived >::rows().
Map() [11/12]
template<typename Derived > static MapType Eigen::PlainObjectBase< Derived >::Map (Scalar * data, Index size) inline static inherited
    { return MapType(data, size); }
References Eigen::PlainObjectBase< Derived >::data().
Map() [12/12]
template<typename Derived > template<int Outer, int Inner> static StridedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::Map (Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedMapType<Stride<Outer, Inner> >::type(data, size, stride); }
References Eigen::PlainObjectBase< Derived >::data().
MapAligned() [1/12]
template<typename Derived > static ConstAlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data) inline static inherited
    { return ConstAlignedMapType(data); }
References Eigen::PlainObjectBase< Derived >::data().
MapAligned() [2/12]
template<typename Derived > template<int Outer, int Inner> static StridedConstAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstAlignedMapType<Stride<Outer, Inner> >::type(data, stride); }
References Eigen::PlainObjectBase< Derived >::data().
MapAligned() [3/12]
template<typename Derived > static ConstAlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, Index rows, Index cols) inline static inherited
    { return ConstAlignedMapType(data, rows, cols); }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), and Eigen::PlainObjectBase< Derived >::rows().
MapAligned() [4/12]
template<typename Derived > template<int Outer, int Inner> static StridedConstAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstAlignedMapType<Stride<Outer, Inner> >::type(data, rows, cols, stride); }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), and Eigen::PlainObjectBase< Derived >::rows().
MapAligned() [5/12]
template<typename Derived > static ConstAlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, Index size) inline static inherited
    { return ConstAlignedMapType(data, size); }
References Eigen::PlainObjectBase< Derived >::data().
MapAligned() [6/12]
template<typename Derived > template<int Outer, int Inner> static StridedConstAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedConstAlignedMapType<Stride<Outer, Inner> >::type(data, size, stride); }
References Eigen::PlainObjectBase< Derived >::data().
MapAligned() [7/12]
template<typename Derived > static AlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data) inline static inherited
    { return AlignedMapType(data); }
References Eigen::PlainObjectBase< Derived >::data().
MapAligned() [8/12]
template<typename Derived > template<int Outer, int Inner> static StridedAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedAlignedMapType<Stride<Outer, Inner> >::type(data, stride); }
References Eigen::PlainObjectBase< Derived >::data().
MapAligned() [9/12]
template<typename Derived > static AlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, Index rows, Index cols) inline static inherited
    { return AlignedMapType(data, rows, cols); }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), and Eigen::PlainObjectBase< Derived >::rows().
MapAligned() [10/12]
template<typename Derived > template<int Outer, int Inner> static StridedAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedAlignedMapType<Stride<Outer, Inner> >::type(data, rows, cols, stride); }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::data(), and Eigen::PlainObjectBase< Derived >::rows().
MapAligned() [11/12]
template<typename Derived > static AlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, Index size) inline static inherited
    { return AlignedMapType(data, size); }
References Eigen::PlainObjectBase< Derived >::data().
MapAligned() [12/12]
template<typename Derived > template<int Outer, int Inner> static StridedAlignedMapType< Stride< Outer, Inner > >::type Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static inherited
    { return typename StridedAlignedMapType<Stride<Outer, Inner> >::type(data, size, stride); }
References Eigen::PlainObjectBase< Derived >::data().
new_scale() [1/3]
static Point Slic3r::Point::new_scale (const Vec2d & v) inline static
{ return Point(coord_t(scale_(v.x())), coord_t(scale_(v.y()))); }
References Point(), and scale_.
new_scale() [2/3]
static Point Slic3r::Point::new_scale (const Vec2f & v) inline static
{ return Point(coord_t(scale_(v.x())), coord_t(scale_(v.y()))); }
References Point(), and scale_.
new_scale() [3/3]
static Point Slic3r::Point::new_scale (coordf_t x, coordf_t y) inline static
{ return Point(coord_t(scale_(x)), coord_t(scale_(y))); }
References Point(), and scale_.
operator*()
Point Slic3r::Point::operator* (const double & rhs) inline
{ return Point(this->x() * rhs, this->y() * rhs); }
References Point().
operator*=()
Point & Slic3r::Point::operator*= (const double & rhs) inline
{ this->x() = coord_t(this->x() * rhs); this->y() = coord_t(this->y() * rhs); return *this; }
operator+=()
Point & Slic3r::Point::operator+= (const Point & rhs) inline
{ this->x() += rhs.x(); this->y() += rhs.y(); return *this; }
operator-=()
Point & Slic3r::Point::operator-= (const Point & rhs) inline
{ this->x() -= rhs.x(); this->y() -= rhs.y(); return *this; }
operator=()
template<typename OtherDerived > Point & Slic3r::Point::operator= (const Eigen::MatrixBase< OtherDerived > & other) inline
    {
        this->Vec2crd::operator=(other);
        return *this;
    }
References Eigen::Matrix< coord_t, 2, 1, Eigen::DontAlign >::operator=().
outerStride()
EIGEN_DEVICE_FUNC Index Eigen::Matrix< coord_t , _Rows, _Cols, _Options, _MaxRows, _MaxCols >::outerStride () const inline inherited
{ return this->innerSize(); }
packet() [1/2]
template<typename Derived > template<int LoadMode> EIGEN_STRONG_INLINE PacketScalar Eigen::PlainObjectBase< Derived >::packet (Index index) const inline inherited
    {
      return internal::ploadt<PacketScalar, LoadMode>(m_storage.data() + index);
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), and Eigen::PlainObjectBase< Derived >::m_storage.
packet() [2/2]
template<typename Derived > template<int LoadMode> EIGEN_STRONG_INLINE PacketScalar Eigen::PlainObjectBase< Derived >::packet (Index rowId, Index colId) const inline inherited
    {
      return internal::ploadt<PacketScalar, LoadMode>
               (m_storage.data() + (Flags & RowMajorBit
                                   ? colId + rowId * m_storage.cols()
                                   : rowId + colId * m_storage.rows()));
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::cols(), Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), Eigen::PlainObjectBase< Derived >::m_storage, Eigen::RowMajorBit, and Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::rows().
resize() [1/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::resize (Index rows, Index cols) inline inherited
Resizes *this to a rows x cols matrix.
This method is intended for dynamic-size matrices, although it is legal to call it on any matrix as long as fixed dimensions are left unchanged. If you only want to change the number of rows and/or of columns, you can use resize(NoChange_t, Index), resize(Index, NoChange_t).
If the current number of coefficients of *this exactly matches the product rows * cols, then no memory allocation is performed and the current values are left unchanged. In all other cases, including shrinking, the data is reallocated and all previous values are lost.
Example:
Output:
See also
resize(Index) for vectors, resize(NoChange_t, Index), resize(Index, NoChange_t)
    {
      eigen_assert(   EIGEN_IMPLIES(RowsAtCompileTime!=Dynamic,rows==RowsAtCompileTime)
                   && EIGEN_IMPLIES(ColsAtCompileTime!=Dynamic,cols==ColsAtCompileTime)
                   && EIGEN_IMPLIES(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic,rows<=MaxRowsAtCompileTime)
                   && EIGEN_IMPLIES(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic,cols<=MaxColsAtCompileTime)
                   && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array.");
      internal::check_rows_cols_for_overflow<MaxSizeAtCompileTime>::run(rows, cols);
      #ifdef EIGEN_INITIALIZE_COEFFS
        Index size = rows*cols;
        bool size_changed = size != this->size();
        m_storage.resize(size, rows, cols);
        if(size_changed) EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED
      #else
        m_storage.resize(rows*cols, rows, cols);
      #endif
    }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::Dynamic, eigen_assert, EIGEN_IMPLIES, EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED, Eigen::PlainObjectBase< Derived >::m_storage, Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::resize(), Eigen::PlainObjectBase< Derived >::rows(), and Eigen::internal::check_rows_cols_for_overflow< MaxSizeAtCompileTime >::run().
Referenced by Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition(), MarchingCubes< Derivedvalues, Derivedpoints, Derivedvertices, DerivedF >::MarchingCubes(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), igl::copyleft::cgal::SelfIntersectMesh< Kernel, DerivedV, DerivedF, DerivedVV, DerivedFF, DerivedIF, DerivedJ, DerivedIM >::SelfIntersectMesh(), Eigen::HessenbergDecomposition< _MatrixType >::_compute(), Eigen::PlainObjectBase< Derived >::_init1(), Eigen::PlainObjectBase< Derived >::_init1(), Eigen::PlainObjectBase< Derived >::_init2(), Eigen::UmfPackLU< _MatrixType >::_solve_impl(), igl::ambient_occlusion(), Eigen::SparseLU< _MatrixType, _OrderingType >::analyzePattern(), igl::barycentric_to_global(), igl::bbw(), igl::mosek::bbw(), igl::bone_parents(), igl::embree::bone_visible(), igl::embree::bone_visible(), igl::bounding_box(), igl::copyleft::cgal::closest_facet(), igl::colormap(), igl::columnize(), igl::comb_frame_field(), igl::combine(), igl::copyleft::cgal::complex_to_mesh(), igl::components(), Eigen::HessenbergDecomposition< _MatrixType >::compute(), Eigen::Tridiagonalization< _MatrixType >::compute(), igl::compute_frame_field_bisectors(), Eigen::BDCSVD< _MatrixType >::computeSVDofM(), igl::connect_boundary_to_infinity(), igl::connect_boundary_to_infinity(), igl::cotmatrix_entries(), igl::cross(), igl::cylinder(), igl::xml::serialization_xml::deserialize(), igl::serialization::deserialize(), igl::dihedral_angles_intrinsic(), igl::doublearea(), igl::doublearea(), igl::doublearea_quad(), igl::edges_to_path(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), igl::exact_geodesic(), igl::copyleft::cgal::extract_cells(), igl::copyleft::cgal::extract_cells(), igl::copyleft::cgal::extract_cells_single_component(), igl::copyleft::cgal::extract_feature(), igl::extract_manifold_patches(), igl::face_areas(), igl::facet_components(), Eigen::IncompleteCholesky< Scalar, _UpLo, _OrderingType >::factorize(), Eigen::DiagonalPreconditioner< _Scalar >::factorize(), Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::factorize(), igl::false_barycentric_subdivision(), igl::fast_winding_number(), igl::fast_winding_number(), igl::find(), igl::find(), igl::find(), igl::matlab::MatlabWorkspace::find(), igl::fit_rotations(), igl::fit_rotations_planar(), igl::copyleft::cork::from_cork_mesh(), Eigen::MetisOrdering< StorageIndex >::get_symmetrized_graph(), igl::grid(), igl::copyleft::cgal::half_space_box(), igl::harmonic(), igl::histc(), igl::histc(), Eigen::internal::householder_qr_inplace_unblocked(), Eigen::SuperLUBase< _MatrixType, Derived >::initFactorization(), igl::copyleft::cgal::intersect_other_helper(), igl::is_boundary_edge(), igl::is_boundary_edge(), igl::is_edge_manifold(), igl::ismember_rows(), igl::isolines(), igl::knn(), igl::list_to_matrix(), igl::list_to_matrix(), igl::list_to_matrix(), igl::local_basis(), igl::loop(), igl::massmatrix(), igl::mat_max(), igl::mat_min(), igl::matlab_format(), igl::max(), igl::min(), igl::min_quad_with_fixed_solve(), igl::copyleft::cgal::minkowski_sum(), igl::copyleft::cgal::minkowski_sum(), igl::mode(), igl::nchoosek(), igl::octree(), Eigen::PlainObjectBase< Derived >::operator=(), igl::copyleft::cgal::order_facets_around_edge(), igl::orient_outward(), igl::orientable_patches(), igl::copyleft::cgal::outer_edge(), igl::outer_edge(), igl::copyleft::cgal::outer_hull(), igl::copyleft::cgal::outer_hull_legacy(), igl::copyleft::cgal::outer_vertex(), igl::outer_vertex(), igl::partition(), igl::copyleft::cgal::peel_outer_hull_layers(), igl::copyleft::cgal::peel_winding_number_layers(), igl::per_face_normals(), igl::per_face_normals_stable(), igl::copyleft::cgal::point_mesh_squared_distance(), igl::point_simplex_squared_distance(), igl::copyleft::cgal::polyhedron_to_mesh(), igl::principal_curvature(), igl::project_isometrically_to_plane(), igl::project_to_line(), igl::copyleft::cgal::projected_cdt(), igl::copyleft::cgal::propagate_winding_numbers(), igl::random_points_on_mesh(), igl::readBF(), igl::readCSV(), igl::readDMAT(), igl::readMESH(), igl::readMSH(), igl::readNODE(), igl::png::readPNG(), Eigen::MatrixMarketIterator< Scalar >::refX(), igl::copyleft::cgal::remesh_intersections(), igl::remove_duplicates(), igl::remove_unreferenced(), igl::embree::reorient_facets_raycast(), igl::repdiag(), igl::repmat(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::resizeLike(), igl::resolve_duplicated_faces(), Eigen::MatrixMarketIterator< Scalar >::rhs(), Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run(), igl::AABB< DerivedV, DIM >::serialize(), igl::setdiff(), igl::setunion(), igl::shape_diameter_function(), igl::signed_distance(), igl::signed_distance_pseudonormal(), igl::slice(), igl::slice_into(), igl::slice_into(), igl::slice_tets(), igl::snap_points(), igl::sort_angles(), igl::sort_vectors_ccw(), igl::sort_vectors_ccw(), igl::sort_vectors_ccw(), igl::AABB< DerivedV, DIM >::squared_distance(), igl::AABB< DerivedV, DIM >::squared_distance(), igl::png::texture_from_png(), igl::transpose_blocks(), igl::copyleft::cgal::trim_with_solid(), igl::unique_rows(), igl::unique_simplices(), igl::unproject(), igl::unzip_corners(), igl::opengl::ViewerData::updateGL(), Eigen::internal::upperbidiagonalization_inplace_unblocked(), igl::upsample(), igl::volume(), igl::volume(), igl::winding_number(), and igl::copyleft::cgal::wire_mesh().
resize() [2/4]
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Derived >::resize (Index rows, NoChange_t) inline inherited
Resizes the matrix, changing only the number of rows. For the parameter of type NoChange_t, just pass the special value NoChange as in the example below.
Example:
Output:
See also
resize(Index,Index)
    {
      resize(rows, cols());
    }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::resize(), and Eigen::PlainObjectBase< Derived >::rows().
resize() [3/4]
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Derived >::resize (Index size) inline inherited
Resizes *this to a vector of length size
\only_for_vectors. This method does not work for partially dynamic matrices when the static dimension is anything other than 1. For example it will not work with Matrix<double, 2, Dynamic>.
Example:
Output:
See also
resize(Index,Index), resize(NoChange_t, Index), resize(Index, NoChange_t)
    {
      EIGEN_STATIC_ASSERT_VECTOR_ONLY(PlainObjectBase)
      eigen_assert(((SizeAtCompileTime == Dynamic && (MaxSizeAtCompileTime==Dynamic || size<=MaxSizeAtCompileTime)) || SizeAtCompileTime == size) && size>=0);
      #ifdef EIGEN_INITIALIZE_COEFFS
        bool size_changed = size != this->size();
      #endif
      if(RowsAtCompileTime == 1)
        m_storage.resize(size, 1, size);
      else
        m_storage.resize(size, size, 1);
      #ifdef EIGEN_INITIALIZE_COEFFS
        if(size_changed) EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED
      #endif
    }
References Eigen::Dynamic, eigen_assert, EIGEN_INITIALIZE_COEFFS_IF_THAT_OPTION_IS_ENABLED, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::PlainObjectBase< Derived >::m_storage, and Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::resize().
resize() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Derived >::resize (NoChange_t , Index cols) inline inherited
Resizes the matrix, changing only the number of columns. For the parameter of type NoChange_t, just pass the special value NoChange as in the example below.
Example:
Output:
See also
resize(Index,Index)
    {
      resize(rows(), cols);
    }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::PlainObjectBase< Derived >::resize(), and Eigen::PlainObjectBase< Derived >::rows().
resizeLike()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::resizeLike (const EigenBase< OtherDerived > & _other) inline inherited
Resizes *this to have the same dimensions as other. Takes care of doing all the checking that's needed.
Note that copying a row-vector into a vector (and conversely) is allowed. The resizing, if any, is then done in the appropriate way so that row-vectors remain row-vectors and vectors remain vectors.
    {
      const OtherDerived& other = _other.derived();
      internal::check_rows_cols_for_overflow<MaxSizeAtCompileTime>::run(other.rows(), other.cols());
      const Index othersize = other.rows()*other.cols();
      if(RowsAtCompileTime == 1)
      {
        eigen_assert(other.rows() == 1 || other.cols() == 1);
        resize(1, othersize);
      }
      else if(ColsAtCompileTime == 1)
      {
        eigen_assert(other.rows() == 1 || other.cols() == 1);
        resize(othersize, 1);
      }
      else resize(other.rows(), other.cols());
    }
References Eigen::EigenBase< Derived >::derived(), eigen_assert, Eigen::PlainObjectBase< Derived >::resize(), and Eigen::internal::check_rows_cols_for_overflow< MaxSizeAtCompileTime >::run().
Referenced by Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::PlainObjectBase< Derived >::_resize_to_match(), igl::copyleft::cgal::assign(), igl::dqs(), igl::hsv_to_rgb(), igl::ismember(), igl::mod(), igl::normalize_row_lengths(), igl::remove_duplicate_vertices(), igl::remove_duplicates(), igl::rgb_to_hsv(), igl::sort(), igl::sort2(), igl::sort3(), igl::sort_new(), and igl::AABB< DerivedV, DIM >::squared_distance().
rotate() [1/3]
void Slic3r::Point::rotate (double angle) inline
{ this->rotate(std::cos(angle), std::sin(angle)); }
References Slic3r::angle(), and rotate().
Referenced by Slic3r::FillLine::_fill_surface_single(), Slic3r::GCode::extrude_loop(), Slic3r::GUI::MeshClipper::recalculate_triangles(), rotate(), Slic3r::Line::rotate(), rotated(), rotated(), and rotated().
rotate() [2/3]
void Slic3r::Point::rotate (double angle, const Point & center)
{
    double cur_x = (double)(*this)(0);
    double cur_y = (double)(*this)(1);
    double s     = ::sin(angle);
    double c     = ::cos(angle);
    double dx    = cur_x - (double)center(0);
    double dy    = cur_y - (double)center(1);
    (*this)(0) = (coord_t)round( (double)center(0) + c * dx - s * dy );
    (*this)(1) = (coord_t)round( (double)center(1) + c * dy + s * dx );
}
References Slic3r::angle(), cos(), round(), and sin().
rotate() [3/3]
void Slic3r::Point::rotate (double cos_a, double sin_a) inline
{
        double cur_x = (double)this->x();
        double cur_y = (double)this->y();
        this->x() = (coord_t)round(cos_a * cur_x - sin_a * cur_y);
        this->y() = (coord_t)round(cos_a * cur_y + sin_a * cur_x);
    }
References round().
rotated() [1/3]
Point Slic3r::Point::rotated (double angle) const inline
{ Point res(*this); res.rotate(angle); return res; }
References Slic3r::angle(), and rotate().
Referenced by Slic3r::FillLine::_fill_surface_single(), Slic3r::FillRectilinear::fill_surface_by_lines(), Slic3r::make_fill_lines(), and Slic3r::BoundingBox::rotated().
rotated() [2/3]
Point Slic3r::Point::rotated (double angle, const Point & center) const inline
{ Point res(*this); res.rotate(angle, center); return res; }
References Slic3r::angle(), and rotate().
rotated() [3/3]
Point Slic3r::Point::rotated (double cos_a, double sin_a) const inline
{ Point res(*this); res.rotate(cos_a, sin_a); return res; }
References rotate().
rows()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::PlainObjectBase< Derived >::rows () const inline inherited
{ return m_storage.rows(); }
References Eigen::PlainObjectBase< Derived >::m_storage, and Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::rows().
Referenced by MarchingCubes< Derivedvalues, Derivedpoints, Derivedvertices, DerivedF >::MarchingCubes(), igl::MeshCutterMini< DerivedV, DerivedF, VFType, DerivedTT, DerivedC >::MeshCutterMini(), igl::copyleft::comiso::MIQ_class< DerivedV, DerivedF, DerivedU >::MIQ_class(), igl::copyleft::comiso::PoissonSolver< DerivedV, DerivedF >::PoissonSolver(), igl::copyleft::comiso::VertexIndexing< DerivedV, DerivedF >::VertexIndexing(), Eigen::PlainObjectBase< Derived >::_init2(), Eigen::PlainObjectBase< Derived >::_resize_to_match(), igl::active_set(), MarchingCubes< Derivedvalues, Derivedpoints, Derivedvertices, DerivedF >::add_vertex(), igl::ambient_occlusion(), igl::arap_dof_precomputation(), igl::arap_dof_update(), igl::arap_precomputation(), igl::barycentric_to_global(), igl::bbw(), igl::mosek::bbw(), igl::bfs_orient(), igl::biharmonic_coordinates(), igl::bone_parents(), igl::embree::bone_visible(), igl::MissMatchCalculator< DerivedV, DerivedF, DerivedM >::calculateMissmatch(), igl::MissMatchCalculatorLine< DerivedV, DerivedF, DerivedO >::calculateMissmatchLine(), igl::copyleft::cgal::CSGTree::cast_V(), igl::triangle::cdt(), igl::copyleft::tetgen::cdt(), igl::copyleft::cgal::cell_adjacency(), igl::copyleft::cgal::closest_facet(), igl::copyleft::cgal::closest_facet(), igl::columnize(), igl::CombLine< DerivedV, DerivedF >::comb(), igl::Comb< DerivedV, DerivedF >::comb(), igl::comb_frame_field(), igl::combine(), igl::copyleft::cgal::component_inside_component(), igl::copyleft::cgal::component_inside_component(), igl::compute_frame_field_bisectors(), igl::connect_boundary_to_infinity(), igl::connect_boundary_to_infinity(), Eigen::PlainObjectBase< Derived >::conservativeResize(), Eigen::PlainObjectBase< Derived >::conservativeResize(), Eigen::PlainObjectBase< Derived >::conservativeResize(), igl::copyleft::cgal::convex_hull(), igl::cross(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::cut(), igl::cut_mesh(), igl::copyleft::cgal::points_inside_component_helper::determine_point_vertex_orientation(), igl::dihedral_angles_intrinsic(), igl::dot_row(), igl::doublearea(), igl::dqs(), igl::opengl::ViewerCore::draw_buffer(), igl::opengl2::draw_skeleton_3d(), igl::opengl2::draw_skeleton_vector_graphics(), igl::edge_topology(), igl::euler_characteristic(), igl::copyleft::cgal::points_inside_component_helper::extract_adj_faces(), igl::copyleft::cgal::points_inside_component_helper::extract_adj_vertices(), igl::copyleft::cgal::extract_cells(), igl::copyleft::cgal::extract_cells_single_component(), igl::copyleft::cgal::extract_feature(), igl::false_barycentric_subdivision(), igl::matlab::MatlabWorkspace::find(), igl::find_cross_field_singularities(), igl::fit_rotations(), igl::fit_rotations_planar(), igl::gaussian_curvature(), igl::serialization::getByteSize(), grad_tet(), grad_tri(), igl::group_sum_matrix(), igl::hsv_to_rgb(), igl::in_element(), igl::in_element(), igl::AABB< DerivedV, DIM >::init(), igl::copyleft::cgal::intersect_other_helper(), igl::is_border_vertex(), igl::is_boundary_edge(), igl::is_edge_manifold(), igl::is_symmetric(), igl::ismember(), Eigen::internal::least_square_conjugate_gradient(), igl::lexicographic_triangulation(), igl::loop(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::Map(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::PlainObjectBase< Derived >::MapAligned(), igl::massmatrix(), igl::matlab_format(), igl::WindingNumberAABB< Point, DerivedV, DerivedF >::max_simple_abs_winding_number(), igl::min_quad_dense_precompute(), igl::min_quad_with_fixed_solve(), igl::copyleft::cgal::minkowski_sum(), igl::copyleft::cgal::minkowski_sum(), igl::matlab::mlgetmatrix(), igl::matlab::mlsetmatrix(), igl::mod(), igl::normal_derivative(), igl::normalize_row_lengths(), igl::copyleft::cgal::order_facets_around_edges(), igl::copyleft::cgal::order_facets_around_edges(), igl::orient_outward(), igl::orientable_patches(), igl::copyleft::cgal::outer_hull_legacy(), igl::copyleft::cgal::outer_vertex(), igl::outer_vertex(), igl::partition(), igl::copyleft::cgal::peel_outer_hull_layers(), igl::per_vertex_attribute_smoothing(), igl::copyleft::cgal::point_mesh_squared_distance(), igl::copyleft::cgal::point_solid_signed_squared_distance(), igl::copyleft::cgal::points_inside_component(), igl::matlab::prepare_lhs_double(), igl::matlab::prepare_lhs_logical(), igl::principal_curvature(), Slic3r::GUI::CameraUtils::project(), igl::project(), igl::project_isometrically_to_plane(), igl::ramer_douglas_peucker(), igl::random_points_on_mesh(), igl::readBF(), igl::readNODE(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), igl::copyleft::cgal::relabel_small_immersed_cells(), igl::copyleft::cgal::remesh_intersections(), igl::remove_duplicates(), igl::embree::reorient_facets_raycast(), igl::repdiag(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::resize(), igl::resolve_duplicated_faces(), igl::copyleft::cgal::resolve_intersections(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::Retract(), igl::rgb_to_hsv(), Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), igl::matlab::MatlabWorkspace::save(), igl::seam_edges(), igl::xml::serialization_xml::serialize(), igl::serialization::serialize(), igl::opengl::ViewerData::set_texture(), igl::shape_diameter_function(), igl::shapeup_identity_projection(), igl::shapeup_precomputation(), igl::shapeup_regular_face_projection(), igl::slice_tets(), igl::slice_tets(), igl::snap_points(), igl::snap_points(), igl::sort_angles(), igl::sparse(), igl::straighten_seams(), igl::copyleft::cgal::subdivide_segments(), igl::copyleft::cgal::submesh_aabb_tree(), Eigen::DenseBase< Derived >::swap(), igl::copyleft::cork::to_cork_mesh(), igl::transpose_blocks(), igl::triangle_triangle_adjacency(), igl::copyleft::cgal::trim_with_solid(), igl::unique_edge_map(), igl::unique_simplices(), igl::upsample(), igl::upsample(), igl::writeBF(), igl::xml::writeDAE(), igl::writeMESH(), igl::writeOFF(), igl::writeOFF(), igl::png::writePNG(), and igl::writeSTL().
setConstant() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setConstant (Index rows, Index cols, const Scalar & val) inherited
Resizes to the given size, and sets all coefficients in this expression to the given value val.
Parameters
rows the new number of rows
cols the new number of columns
val the value to which all coefficients are set
Example:
Output:
See also
MatrixBase::setConstant(const Scalar&), setConstant(Index,const Scalar&), class CwiseNullaryOp, MatrixBase::Constant(const Scalar&)
{
  resize(rows, cols);
  return setConstant(val);
}
setConstant() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setConstant (Index size, const Scalar & val) inherited
Resizes to the given size, and sets all coefficients in this expression to the given value val.
\only_for_vectors
Example:
Output:
See also
MatrixBase::setConstant(const Scalar&), setConstant(Index,Index,const Scalar&), class CwiseNullaryOp, MatrixBase::Constant(const Scalar&)
{
  resize(size);
  return setConstant(val);
}
Referenced by igl::MissMatchCalculator< DerivedV, DerivedF, DerivedM >::calculateMissmatch(), igl::MissMatchCalculatorLine< DerivedV, DerivedF, DerivedO >::calculateMissmatchLine(), Eigen::RealSchur< _MatrixType >::computeShift(), igl::connect_boundary_to_infinity(), igl::connect_boundary_to_infinity(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >::cut(), igl::dijkstra_compute_paths(), igl::copyleft::cgal::extract_cells_single_component(), igl::extract_manifold_patches(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), igl::frustum(), Eigen::MetisOrdering< StorageIndex >::get_symmetrized_graph(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::heap_relax_snode(), igl::histc(), igl::is_vertex_manifold(), igl::ismember(), igl::ismember_rows(), igl::max(), igl::min(), igl::copyleft::cgal::minkowski_sum(), Eigen::Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::operator=(), igl::copyleft::cgal::outer_hull_legacy(), igl::per_vertex_normals(), igl::project(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::relax_snode(), Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty(), igl::signed_distance(), igl::snap_points(), igl::sort2(), igl::sort3(), igl::AABB< DerivedV, DIM >::squared_distance(), igl::triangle_triangle_adjacency_extractTT(), igl::triangle_triangle_adjacency_extractTTi(), and igl::writeWRL().
setOnes() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setOnes (Index rows, Index cols) inherited
Resizes to the given size, and sets all coefficients in this expression to one.
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See also
MatrixBase::setOnes(), setOnes(Index), class CwiseNullaryOp, MatrixBase::Ones()
{
  resize(rows, cols);
  return setConstant(Scalar(1));
}
setOnes() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setOnes (Index newSize) inherited
Resizes to the given newSize, and sets all coefficients in this expression to one.
\only_for_vectors
Example:
Output:
See also
MatrixBase::setOnes(), setOnes(Index,Index), class CwiseNullaryOp, MatrixBase::Ones()
{
  resize(newSize);
  return setConstant(Scalar(1));
}
Referenced by Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), and Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run().
setRandom() [1/2]
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setRandom (Index rows, Index cols) inherited
Resizes to the given size, and sets all coefficients in this expression to random values.
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
\not_reentrant
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See also
DenseBase::setRandom(), setRandom(Index), class CwiseNullaryOp, DenseBase::Random()
{
  resize(rows, cols);
  return setRandom();
}
setRandom() [2/2]
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setRandom (Index newSize) inherited
Resizes to the given newSize, and sets all coefficients in this expression to random values.
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
\only_for_vectors \not_reentrant
Example:
Output:
See also
DenseBase::setRandom(), setRandom(Index,Index), class CwiseNullaryOp, DenseBase::Random()
{
  resize(newSize);
  return setRandom();
}
Referenced by Eigen::MatrixMarketIterator< Scalar >::rhs().
setZero() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setZero (Index rows, Index cols) inherited
Resizes to the given size, and sets all coefficients in this expression to zero.
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See also
DenseBase::setZero(), setZero(Index), class CwiseNullaryOp, DenseBase::Zero()
{
  resize(rows, cols);
  return setConstant(Scalar(0));
}
setZero() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setZero (Index newSize) inherited
Resizes to the given size, and sets all coefficients in this expression to zero.
\only_for_vectors
Example:
Output:
See also
DenseBase::setZero(), setZero(Index,Index), class CwiseNullaryOp, DenseBase::Zero()
{
  resize(newSize);
  return setConstant(Scalar(0));
}
Referenced by Eigen::PardisoImpl< Derived >::PardisoImpl(), igl::PlanarizerShapeUp< DerivedV, DerivedF >::PlanarizerShapeUp(), igl::PlanarizerShapeUp< DerivedV, DerivedF >::assembleP(), igl::average_onto_vertices(), igl::barycenter(), igl::centroid(), igl::CombLine< DerivedV, DerivedF >::comb(), igl::Comb< DerivedV, DerivedF >::comb(), Eigen::GeneralizedEigenSolver< _MatrixType >::compute(), Eigen::BDCSVD< _MatrixType >::compute(), Eigen::BDCSVD< _MatrixType >::computeSingVecs(), igl::cut_mesh(), Eigen::SparseQR< _MatrixType, _OrderingType >::factorize(), Eigen::SparseLU< _MatrixType, _OrderingType >::factorize(), Eigen::LeastSquareDiagonalPreconditioner< _Scalar >::factorize(), igl::fast_winding_number(), igl::fast_winding_number(), igl::find_cross_field_singularities(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::heap_relax_snode(), igl::min_quad_dense_precompute(), Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, UpLo >::operator()(), Eigen::Translation< _Scalar, _Dim >::operator*(), Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Translation< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), igl::partition(), igl::per_corner_normals(), igl::per_edge_normals(), igl::per_vertex_normals(), igl::copyleft::cgal::point_areas(), igl::quad_planarity(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::relax_snode(), igl::embree::reorient_facets_raycast(), Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), igl::seam_edges(), and Eigen::internal::MappedSuperNodalMatrix< _Scalar, _StorageIndex >::solveInPlace().
swap() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Derived >::swap (DenseBase< OtherDerived > & other) inline inherited
    {
      enum { SwapPointers = internal::is_same<Derived, OtherDerived>::value && Base::SizeAtCompileTime==Dynamic };
      internal::matrix_swap_impl<Derived, OtherDerived, bool(SwapPointers)>::run(this->derived(), other.derived());
    }
References Eigen::Dynamic.
Referenced by Eigen::IterativeSolverBase< Derived >::_solve_impl(), Eigen::BDCSVD< _MatrixType >::computeSVDofM(), Slic3r::sla::DefaultSupportTree::interconnect(), and Slic3r::pinch_contours_insert_phony_outer_intersections().
swap() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::PlainObjectBase< Derived >::swap (DenseBase< OtherDerived > const & other) inline inherited
    { Base::swap(other.derived()); }
writePacket() [1/2]
template<typename Derived > template<int StoreMode> EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::writePacket (Index index, const PacketScalar & val) inline inherited
    {
      internal::pstoret<Scalar, PacketScalar, StoreMode>(m_storage.data() + index, val);
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), and Eigen::PlainObjectBase< Derived >::m_storage.
writePacket() [2/2]
template<typename Derived > template<int StoreMode> EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::writePacket (Index rowId, Index colId, const PacketScalar & val) inline inherited
    {
      internal::pstoret<Scalar, PacketScalar, StoreMode>
              (m_storage.data() + (Flags & RowMajorBit
                                   ? colId + rowId * m_storage.cols()
                                   : rowId + colId * m_storage.rows()), val);
    }
References Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::cols(), Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data(), Eigen::PlainObjectBase< Derived >::m_storage, Eigen::RowMajorBit, and Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::rows().
Member Data Documentation
m_storage
DenseStorage<Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options> Eigen::PlainObjectBase< Derived >::m_storage protected inherited
The documentation for this class was generated from the following files:
src/libslic3r/Point.hpp
src/libslic3r/Point.cpp